### ISSUE TITLE
使用finalspeed无速度

### ISSUE THREAD

**Issue by ltyj2003** [coolsnowwolf/lede#10]
您好，我使用finalspeed连接ss速度几乎没有，lede 版本R7.3.2 。不使用finalspeed直接连接正常，不经过路由器直接拨号也正常。请问应该怎么设置lede

**Comment by coolsnowwolf** [comment]
不清楚，现在基本都用 BBR 和 KCP 了，放弃 FinalSpeed 了，很正常
