### ISSUE TITLE
编译无线不能用请教，但是官网用官网15051和17012 无线都能正常配置使用！

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/lede#100]
硬件是mr3420 v1 ，官网固件无线可使用的配置文件为：
cat /etc/config/wireless
config wifi-device 'radio0'
        option type 'mac80211'
        option channel '11'
        option hwmode '11g'
        option path 'pci0000:00/0000:00:00.0'
        option htmode 'HT20'
        option country 'US'
config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option encryption 'none'
        option ssid '2214LEDE'

使用这个配置文件我编译的固件还是不能使用（mode始终是unkown），但是页面配置里面的scan又能扫描出来周边的AP信号！

而硬件k2p则没找到硬件驱动
root@K2P:~# lspci 
00:00.0 PCI bridge: Device 0e8d:0801 (rev 01)
01:00.0 Unclassified device [0002]: MEDIATEK Corp. Device 7615
root@K2P:~# lsmod|grep 7615
mt7615_dbdc          3481177  2 

换成其它固件，比如下面这个就正常
root@K2P:~# cat /etc/config/wireless 

config wifi-device 'ra'
        option type 'mt_dbdc'
        option hwmode '11g'
        option channel 'auto'
        option txpower '100'
        option htmode 'HT40'
        option country 'CN'
        option txburst '1'
        option noscan '1'
        option smart '1'

config wifi-iface 'default_ra'
        option device 'ra'
        option network 'lan'
        option mode 'ap'
        option encryption 'none'
        option ssid '2214-PandoraBox-2.4G'
        option rssikick '0'
        option rssiassoc '0'

config wifi-device 'rax'
        option type 'mt_dbdc'
        option hwmode '11a'
        option channel 'auto'
        option txpower '100'
        option htmode 'VHT80'
        option country 'CN'
        option txburst '1'
        option noscan '1'

config wifi-iface 'default_rax'
        option device 'rax'
        option network 'lan'
        option mode 'ap'
        option encryption 'none'
        option ssid '2214-PandoraBox-5G'
        option rssikick '0'
        option rssiassoc '0'

同mr3420样,用上面这个可用的配置文件配置无线还是不能启动无线,,提示如下：

通用 802.11 无线控制器 (ra) 0% 	SSID: 2214-PandoraBox-2.4G | 模式: Master
无线未开启或未关联 
通用 802.11 无线控制器 (rax) 0% SSID: 2214-PandoraBox-5G | 模式: Master
无线未开启或未关联

**Comment by coolsnowwolf** [comment]
没有系统日志，不评论

K2P 没有开源的驱动

**Comment by hzjnet** [comment]
先请教 mr3420的吧，贴上log，可惜日志为空！  不知道找对没有：
root@LEDE:~# find /var/log |xargs ls -la
-rw-r--r--    1 root     root           745 Oct  4 07:09 /var/log/ddns/myddns_ipv4.log
-rw-r--r--    1 root     root           853 Oct  4 07:09 /var/log/ddns/myddns_ipv6.log
-rw-r--r--    1 root     root             0 Oct  4 06:00 /var/log/lastlog
-rw-r--r--    1 root     root             0 Oct  4 06:00 /var/log/wtmp

/var/log:
drwxr-xr-x    3 root     root           100 Oct  4 07:09 .
drwxrwxrwt   20 root     root           540 Oct  4 07:10 ..
drwxr-xr-x    2 root     root            80 Oct  4 07:09 ddns
-rw-r--r--    1 root     root             0 Oct  4 06:00 lastlog
-rw-r--r--    1 root     root             0 Oct  4 06:00 wtmp

/var/log/ddns:
drwxr-xr-x    2 root     root            80 Oct  4 07:09 .
drwxr-xr-x    3 root     root           100 Oct  4 07:09 ..
-rw-r--r--    1 root     root           745 Oct  4 07:09 myddns_ipv4.log
-rw-r--r--    1 root     root           853 Oct  4 07:09 myddns_ipv6.log

**Comment by coolsnowwolf** [comment]
当然不能用，目前没有开源的驱动是支持 K2P 无线的
