### ISSUE TITLE
请教各位大佬，Mipsel可以升级5.19内核吗

### ISSUE THREAD

**Issue by Kalansas** [coolsnowwolf/lede#10009]
如题，我的路由器是 小米AC2100，MTK Ralink MIPS 平台，看 issue 里大家都在忙着升级5.19，所以就想请教一下能否升级，谢谢

**Comment by aiamadeus** [comment]
以后再也不给你们 mips 优化内核了，做了那么多优化天天就想着高版本内核。

**Comment by EnnawYang** [comment]
咱还想降级呢，越往上越卡，**放过mips吧**

**Comment by ricksuzade-maker** [comment]
暗云专门优化的5.4真的已经是MIPS的上限了，放过MIPS吧，就让它慢慢走入历史舞台。

**Comment by minlang112** [comment]
小孩开大车很好玩吗

**Comment by Aes64X** [comment]
5.19主要给x86核显，用PCIE网卡的或者带上NTFS读写，smb的内核的。一mips来凑什么热闹。。。。。。。。

**Comment by openwrt-try** [comment]
> 

请问这个内核在哪儿呀，lede里默认就有么，谢谢啦，

**Comment by openwrt-try** [comment]
> 

请问暗云专门优化的5.4，在lede里就有么，还是需要另外添加呀，谢谢啦

**Comment by openwrt-try** [comment]
> 暗云专门优化的5.4真的已经是MIPS的上限了，放过MIPS吧，就让它慢慢走入历史舞台。

请问暗云专门优化的5.4，在lede里就有么，还是需要另外添加呀，谢谢啦 @ricksuzade-maker
