### ISSUE TITLE
编译x86 5.15内核报错

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#10004]
日志如下：
Applying /home/x86/lede/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch using plaintext:
patching file drivers/pci/controller/pci-aardvark.c
patch: **** malformed patch at line 29: @@ -1631,9 +1631,7 @@ static int advk_pcie_enable_phy(struct a

Patch failed!  Please fix /home/x86/lede/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch!
Makefile:112: recipe for target '/home/x86/lede/build_dir/toolchain-x86_64_gcc-8.4.0_musl/linux-5.15.63/.prepared' failed
make[3]: *** [/home/x86/lede/build_dir/toolchain-x86_64_gcc-8.4.0_musl/linux-5.15.63/.prepared] Error 1
make[3]: Leaving directory '/home/x86/lede/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#16.87#72.20#72.83
    ERROR: toolchain/kernel-headers failed to build.
toolchain/Makefile:95: recipe for target 'toolchain/kernel-headers/compile' failed
make[2]: *** [toolchain/kernel-headers/compile] Error 1
make[2]: Leaving directory '/home/x86/lede'
toolchain/Makefile:93: recipe for target '/home/x86/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/stamp/.toolchain_compile' failed
make[1]: *** [/home/x86/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/x86/lede'
/home/x86/lede/include/toplevel.mk:228: recipe for target 'world' failed

**Comment by lifetyper** [comment]
一样的错误

**Comment by 759071793** [comment]
一样的错误

**Comment by fxvbv** [comment]
确实出现了这个错误。

**Comment by zhangguanzhang** [comment]
```
Patch failed! Please fix /home/x86/lede/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch!
```
这个 patch有问题

**Comment by CoderKwong** [comment]
同一个问题

**Comment by MIAOBUSI** [comment]
pull完最新源码还是这个错误 日志如下：

**Comment by MIAOBUSI** [comment]
Applying /home/miao/lede/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch using plaintext: 
patching file drivers/pci/controller/pci-aardvark.c
patch: **** malformed patch at line 29: @@ -1631,9 +1631,7 @@ static int advk_pcie_enable_phy(struct a

Patch failed!  Please fix /home/miao/lede/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch!
make[3]: *** [Makefile:122: /home/miao/lede/build_dir/toolchain-x86_64_gcc-8.4.0_musl/linux-5.15.63/.prepared] Error 1
make[3]: Leaving directory '/home/miao/lede/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#8.85#6.10#13.97
    ERROR: toolchain/kernel-headers failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/kernel-headers/compile] Error 1
make[2]: Leaving directory '/home/miao/lede'
make[1]: *** [toolchain/Makefile:93: /home/miao/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/miao/lede'
make: *** [/home/miao/lede/include/toplevel.mk:230：world] 错误 2

**Comment by lovehackintosh** [comment]
临时解决办法:
```shell
```

**Comment by MIAOBUSI** [comment]
> 临时解决办法:
> 
> ```shell
> wget -O target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch https://github.com/benihi/lede/raw/5db1b1986a1b1b9d7c294f1c6526c54c33a43814/target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch
> ```

OK 感谢
