### ISSUE TITLE
哪位大神来帮忙一下 Sed 默认源 下载没速度

### ISSUE THREAD

**Issue by shedkiss** [coolsnowwolf/lede#10011]
make download -j8 后:
 make[2] -C tools/sed download  一直卡着没速度 ,是不是没有镜像？国内的源镜像找到了在https://mirrors.tuna.tsinghua.edu.cn/gnu/sed/   ，如何添加描述？或者能否请大神更新一下，万分感谢

**Comment by 1054009064** [comment]
默认有腾讯源，按道理不会没有速度吧，你要加个 V=s 看看是哪个卡了
https://github.com/coolsnowwolf/lede/blob/f8015dd5e9d738c9706361c52ddf89d813f8b519/scripts/download.pl#L227

**Comment by xcyll** [comment]
最近2天 lean仓库action里的 make download也要17-8分钟了
以前3-5分钟吧

**Comment by 1054009064** [comment]
还是建议提供单线程的详细下载日志。😅

**Comment by Racon94** [comment]
我全局翻墙解决了，用虚拟机编译

**Comment by rahxyz** [comment]
SHELL= flock /home/raxx/lede/tmp/.xxd-1.10.tar.gz.flock -c '    /home/raxx/lede/scripts/download.pl "/home/raxx/lede/dl" "xxd-1.10.tar.gz" "9bf05c19b9084973e3cc877696a7f9881a5c87fa5a9fa438d9962519726559f9" "" "http://grail.cba.csuohio.edu/~somos/"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://grail.cba.csuohio.edu/~somos/xxd-1.10.tar.gz

这个卡住了，几天了都。

**Comment by 1054009064** [comment]
你们可以参考这个取消的 pr 改。 #10015

**Comment by shedkiss** [comment]
还是卡住

**Comment by 1054009064** [comment]
我改动后的

![Screenshot_20220901_133237](https://user-images.githubusercontent.com/44148148/187838841-93bb754a-e97b-4f47-8bb3-1dd1e0b6ba19.png)

**Comment by bihell** [comment]
是要卡一段时间的，挂代理吧，也要卡一会

**Comment by 1054009064** [comment]
卡还有一个原因就是某些包并不是打包好，需要拉源码到本地打包，如果那个源码比较大，这时候就要看你的电脑打包性能了

**Comment by lifetyper** [comment]
老美太不敬业了，服务器挂了几天了都不修。grail.cba.csuohio.edu这个站点从美国服务器都拉不动。

**Comment by Cathgao** [comment]
有个服务器挂掉了，包半天拉不下来。我这没开详细日志，不知道卡的是哪个包
![QQ截图20220902091311](https://user-images.githubusercontent.com/21031564/188038130-79ac21bc-6c53-44d8-9cef-2d010006e587.png)

**Comment by coderhwz** [comment]
现在是全世界都ping不通，翻墙也没用，这位老哥临时提供了文件，来解决 https://github.com/openwrt/openwrt/issues/10555 。 在22.03 rc6里还存在这个东西，不过master 已经没了。即没用，又恶心人。   也可以  https://github.com/openwrt/openwrt/commit/c6d3f39ecce43c4a9858157e9e2ee8718750a9ab  去掉

**Comment by xiaopang0v0** [comment]
> 老美太不敬业了，服务器挂了几天了都不修。grail.cba.csuohio.edu这个站点从美国服务器都拉不动。

你应该是卡在了 `xxd` 吧，这并不是由于这个网站挂掉了，而是因为这个网站**屏蔽了 http 请求**，只需要进入这个包的 Makefile 里，把 http 改成 https 就可以了
```
tools/xxd/Makefile
```
