### ISSUE TITLE
最新编译x86固件好大

### ISSUE THREAD

**Issue by HangYijun** [coolsnowwolf/lede#10039]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：为什么最新编译出来的x86固件没有img输出，只有gz输出？img.gz解压缩后居然有500m，一个月前相同配置的config编译完只有170m-180m的img输出，不知道我哪里出了问题？

另gz解压后的500m img文件转成vmdk后新建虚拟机总是提示硬盘要大于源文件，何解？

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
修改了root分区大小了，以前是160

**Comment by WYC-2020** [comment]
自己改回来，现在是480
