### ISSUE TITLE
Rock3 A，内核选中<*>Support for frame buffer devices，SD卡无法启动系统

### ISSUE THREAD

**Issue by LinuxSzp** [coolsnowwolf/lede#10048]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Rock3 A，内核选中<*>Support for frame buffer devices，SD卡无法启动系统
目标板Radxa Rock3 A，首次构建后，使用etcher制作镜像，SD卡启动系统后发现/dev下没有fb0。于是重新构建5.15.63内核，只单单选中Device Drivers-->Graphics support-->Frame buffer Devices--> <*>Support for frame buffer devices，重新构建使用SD卡启动，卡在Waiting for root device PARTUUID=5452574f-02...无法启动

### (2) 路由器型号和固件版本

A：radxa Rock3 Model A

### (3) 详细日志

A：
DDR Version V1.13 20220218
In
ddrconfig:7
LPDDR4X, 324MHz
BW=32 Col=10 Bk=8 CS0 Row=17 CS1 Row=17 CS=2 Die BW=8 Size=8192MB
tdqss: cs0 dqs0: 72ps, dqs1: -48ps, dqs2: -48ps, dqs3: -120ps,
tdqss: cs1 dqs0: 72ps, dqs1: -72ps, dqs2: -48ps, dqs3: -120ps,

change to: 324MHz
PHY drv:clk:36,ca:36,DQ:29,odt:0
vrefinner:24%, vrefout:41%
dram drv:40,odt:0
clk skew:0x60

change to: 528MHz
PHY drv:clk:36,ca:36,DQ:29,odt:0
vrefinner:24%, vrefout:41%
dram drv:40,odt:0
clk skew:0x58

change to: 780MHz
PHY drv:clk:36,ca:36,DQ:29,odt:0
vrefinner:24%, vrefout:41%
dram drv:40,odt:0
clk skew:0x58

change to: 1560MHz(final freq)
PHY drv:clk:36,ca:36,DQ:29,odt:60
vrefinner:16%, vrefout:22%
dram drv:40,odt:80
vref_ca:00000071
clk skew:0x1c
cs 0:
the read training result:
DQS0:0x30, DQS1:0x31, DQS2:0x35, DQS3:0x2e,
min  : 0xd  0xe 0x11  0xe  0x2  0x4  0x6  0x4 , 0xc  0x8  0x4  0x2 0x11  0xb  0xe  0xb ,
      0x11 0x11  0xe  0xa  0x4  0x1  0x4  0x5 , 0xc  0x8  0x8  0x1  0xe  0xd  0xc  0xe ,
mid  :0x25 0x26 0x28 0x26 0x1a 0x1e 0x20 0x1d ,0x23 0x21 0x1b 0x1d 0x28 0x25 0x26 0x23 ,
      0x2a 0x2a 0x26 0x24 0x1d 0x1b 0x1c 0x1e ,0x23 0x20 0x1f 0x1b 0x28 0x27 0x25 0x27 ,
max  :0x3e 0x3f 0x40 0x3f 0x32 0x38 0x3b 0x37 ,0x3a 0x3a 0x33 0x38 0x3f 0x3f 0x3f 0x3c ,
      0x43 0x43 0x3f 0x3e 0x37 0x35 0x35 0x38 ,0x3b 0x39 0x36 0x35 0x42 0x42 0x3e 0x41 ,
range:0x31 0x31 0x2f 0x31 0x30 0x34 0x35 0x33 ,0x2e 0x32 0x2f 0x36 0x2e 0x34 0x31 0x31 ,
      0x32 0x32 0x31 0x34 0x33 0x34 0x31 0x33 ,0x2f 0x31 0x2e 0x34 0x34 0x35 0x32 0x33 ,
the write training result:
DQS0:0x2a, DQS1:0x13, DQS2:0x13, DQS3:0x5,
min  :0x6f 0x71 0x75 0x71 0x63 0x66 0x6b 0x6b 0x6a ,0x53 0x51 0x4d 0x50 0x57 0x55 0x57 0x55 0x51 ,
      0x5b 0x5b 0x55 0x53 0x4c 0x4a 0x4e 0x51 0x51 ,0x4a 0x48 0x46 0x44 0x4e 0x4e 0x4c 0x51 0x44 ,
mid  :0x8b 0x8d 0x90 0x8d 0x7c 0x80 0x86 0x84 0x82 ,0x70 0x6d 0x67 0x69 0x72 0x6f 0x72 0x70 0x6c ,
      0x77 0x76 0x6f 0x70 0x66 0x63 0x68 0x6c 0x6c ,0x65 0x62 0x5f 0x5d 0x68 0x69 0x66 0x6c 0x5d ,
max  :0xa7 0xa9 0xab 0xa9 0x96 0x9a 0xa1 0x9e 0x9a ,0x8d 0x8a 0x82 0x83 0x8d 0x8a 0x8d 0x8b 0x87 ,
      0x94 0x92 0x8a 0x8d 0x81 0x7d 0x83 0x87 0x87 ,0x80 0x7c 0x78 0x76 0x83 0x85 0x81 0x87 0x77 ,
range:0x38 0x38 0x36 0x38 0x33 0x34 0x36 0x33 0x30 ,0x3a 0x39 0x35 0x33 0x36 0x35 0x36 0x36 0x36 ,
      0x39 0x37 0x35 0x3a 0x35 0x33 0x35 0x36 0x36 ,0x36 0x34 0x32 0x32 0x35 0x37 0x35 0x36 0x33 ,
cs 1:
the read training result:
DQS0:0x31, DQS1:0x33, DQS2:0x35, DQS3:0x2f,
min  : 0xc  0xe 0x11  0xe  0x2  0x3  0x6  0x3 , 0xb  0x7  0x4  0x2 0x11  0xa  0xd  0x9 ,
      0x11 0x12  0xc  0xb  0x5  0x2  0x5  0x5 , 0xc  0x8  0x8  0x2  0xe  0xd  0xc  0xe ,
mid  :0x25 0x28 0x29 0x28 0x1a 0x1e 0x21 0x1e ,0x23 0x21 0x1c 0x1e 0x29 0x25 0x27 0x23 ,
      0x29 0x2a 0x25 0x24 0x1d 0x1b 0x1c 0x1e ,0x23 0x21 0x1f 0x1b 0x27 0x27 0x25 0x27 ,
max  :0x3f 0x42 0x42 0x42 0x33 0x3a 0x3c 0x39 ,0x3b 0x3c 0x35 0x3a 0x42 0x41 0x42 0x3d ,
      0x42 0x42 0x3f 0x3e 0x36 0x34 0x33 0x38 ,0x3a 0x3a 0x37 0x35 0x41 0x42 0x3e 0x40 ,
range:0x33 0x34 0x31 0x34 0x31 0x37 0x36 0x36 ,0x30 0x35 0x31 0x38 0x31 0x37 0x35 0x34 ,
      0x31 0x30 0x33 0x33 0x31 0x32 0x2e 0x33 ,0x2e 0x32 0x2f 0x33 0x33 0x35 0x32 0x32 ,
the write training result:
DQS0:0x2a, DQS1:0x13, DQS2:0x13, DQS3:0x5,
min  :0x6e 0x70 0x74 0x71 0x62 0x67 0x6b 0x6b 0x69 ,0x4e 0x4c 0x49 0x4b 0x51 0x4f 0x52 0x50 0x4c ,
      0x59 0x5a 0x53 0x54 0x4a 0x48 0x4e 0x50 0x51 ,0x48 0x48 0x44 0x42 0x4d 0x4e 0x4c 0x51 0x46 ,
mid  :0x8a 0x8c 0x8f 0x8c 0x7b 0x81 0x85 0x83 0x81 ,0x6a 0x68 0x62 0x63 0x6d 0x6a 0x6d 0x6b 0x67 ,
      0x76 0x76 0x6f 0x70 0x66 0x64 0x68 0x6b 0x6c ,0x64 0x64 0x5f 0x5d 0x68 0x6a 0x67 0x6c 0x5f ,
max  :0xa7 0xa9 0xab 0xa7 0x95 0x9b 0x9f 0x9c 0x9a ,0x87 0x85 0x7c 0x7c 0x89 0x86 0x88 0x87 0x83 ,
      0x94 0x92 0x8c 0x8c 0x82 0x80 0x83 0x87 0x88 ,0x81 0x80 0x7a 0x78 0x83 0x86 0x83 0x88 0x79 ,
range:0x39 0x39 0x37 0x36 0x33 0x34 0x34 0x31 0x31 ,0x39 0x39 0x33 0x31 0x38 0x37 0x36 0x37 0x37 ,
      0x3b 0x38 0x39 0x38 0x38 0x38 0x35 0x37 0x37 ,0x39 0x38 0x36 0x36 0x36 0x38 0x37 0x37 0x33 ,
CA Training result:
cs:0 min  :0x4e 0x50 0x47 0x46 0x47 0x42 0x4c ,0x4b 0x4c 0x43 0x42 0x44 0x42 0x4c ,
cs:0 mid  :0x8d 0x8d 0x85 0x82 0x85 0x7d 0x7e ,0x8b 0x88 0x80 0x7d 0x82 0x7f 0x7d ,
cs:0 max  :0xcd 0xca 0xc3 0xbf 0xc3 0xb9 0xb1 ,0xcb 0xc5 0xbe 0xb9 0xc1 0xbd 0xaf ,
cs:0 range:0x7f 0x7a 0x7c 0x79 0x7c 0x77 0x65 ,0x80 0x79 0x7b 0x77 0x7d 0x7b 0x63 ,
cs:1 min  :0x4c 0x54 0x44 0x4a 0x46 0x47 0x51 ,0x4b 0x4e 0x43 0x47 0x44 0x46 0x4c ,
cs:1 mid  :0x8f 0x8e 0x85 0x83 0x87 0x7e 0x82 ,0x8d 0x88 0x84 0x7f 0x85 0x7f 0x7e ,
cs:1 max  :0xd2 0xc8 0xc7 0xbc 0xc8 0xb6 0xb4 ,0xd0 0xc3 0xc5 0xb7 0xc7 0xb8 0xb0 ,
cs:1 range:0x86 0x74 0x83 0x72 0x82 0x6f 0x63 ,0x85 0x75 0x82 0x70 0x83 0x72 0x64 ,
out
rockchip_sdram_size fdc20208 10000a02
rank=2 cs0_col=10 cs1_col=10 bk=3 cs0_row=17 cs1_row=17 bg=0 bw=2 row_3_4=0
SDRAM base=0, size=200000000

U-Boot SPL 2022.07 (Sep 03 2022 - 01:34:02 +0000)
Trying to boot from MMC1
INFO:    Preloader serial: 2
NOTICE:  BL31: v2.3():v2.3-152-g4e725b15f:cl
NOTICE:  BL31: Built : 10:51:13, Jul 15 2021
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    pmu v1 is valid
INFO:    dfs DDR fsp_param[0].freq_mhz= 1560MHz
INFO:    dfs DDR fsp_param[1].freq_mhz= 324MHz
INFO:    dfs DDR fsp_param[2].freq_mhz= 528MHz
INFO:    dfs DDR fsp_param[3].freq_mhz= 780MHz
INFO:    Using opteed sec cpu_context!
INFO:    boot cpu mask: 0
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0xa00000
INFO:    SPSR = 0x3c9

U-Boot 2022.07 (Sep 03 2022 - 01:34:02 +0000) OpenWrt

Model: Radxa ROCK3 Model A
DRAM:  rockchip_sdram_size fdc20208 10000a02
rank=2 cs0_col=10 cs1_col=10 bk=3 cs0_row=17 cs1_row=17 bg=0 bw=2 row_3_4=0
SDRAM base=0, size=200000000
8 GiB
Core:  280 devices, 21 uclasses, devicetree: separate
MMC:   mmc@fe2b0000: 1, mmc@fe310000: 0
Loading Environment from nowhere... OK
In:    serial@fe660000
Out:   serial@fe660000
Err:   serial@fe660000
Model: Radxa ROCK3 Model A
can't get vref-supply: -2
rockchip_dnl_key_pressed: adc_channel_single_shot fail!
Net:   No ethernet found.
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Found U-Boot script /boot.scr
352 bytes read in 2 ms (171.9 KiB/s)
## Executing script at 00c00000
50553 bytes read in 8 ms (6 MiB/s)
15038472 bytes read in 1246 ms (11.5 MiB/s)
Moving Image from 0x2080000 to 0x2200000, end=3120000
## Flattened Device Tree blob at 0a100000
   Booting using the fdt blob at 0xa100000
   Loading Device Tree to 00000000edef0000, end 00000000edeff578 ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x412fd050]
[    0.000000] Linux version 5.15.63 (embzp@linux) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 8.4.0 r4907-d496bf88a) 8.4.0, GNU ld (GNU Binutils) 2.34) #0 SMP PREEMPT Sat Sep 3 01:34:02 2022
[    0.000000] Machine model: Radxa ROCK3 Model A
[    0.000000] earlycon: uart8250 at MMIO32 0x00000000fe660000 (options '')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000200000-0x00000000ffffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000200000-0x00000000efffffff]
[    0.000000]   node   0: [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000200000-0x00000001ffffffff]
[    0.000000] On node 0, zone DMA: 512 pages in unavailable ranges
[    0.000000] cma: Reserved 8 MiB at 0x00000000ef800000
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.2
[    0.000000] percpu: Embedded 18 pages/cpu s35288 r8192 d30248 u73728
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: GIC system register CPU interface
[    0.000000] CPU features: detected: Virtualization Host Extensions
[    0.000000] CPU features: detected: ARM errata 1165522, 1319367, or 1530923
[    0.000000] alternatives: patching kernel code
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 1999368
[    0.000000] Kernel command line: console=ttyS2,1500000 earlycon=uart8250,mmio32,0xfe660000 root=PARTUUID=5452574f-02 rw rootwait
[    0.000000] Dentry cache hash table entries: 1048576 (order: 11, 8388608 bytes, linear)
[    0.000000] Inode-cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x00000000e9ef0000-0x00000000edef0000] (64MB)
[    0.000000] Memory: 7878612K/8124416K available (8448K kernel code, 2270K rwdata, 2540K rodata, 1280K init, 729K bss, 237612K reserved, 8192K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GICv3: GIC: Using split EOI/Deactivate mode
[    0.000000] GICv3: 320 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] GICv3: Distributor has no Range Selector support
[    0.000000] GICv3: MBI range [296:319]
[    0.000000] GICv3: Using MBI frame 0x00000000fd410000
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GICv3: 16 PPIs implemented
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x00000000fd460000
[    0.000000] ITS: No ITS available, not enabling LPIs
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000000] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.001235] Console: colour dummy device 80x25
[    0.001731] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=96000)
[    0.002781] pid_max: default: 32768 minimum: 301
[    0.003472] Mount-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.004262] Mountpoint-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.007424] rcu: Hierarchical SRCU implementation.
[    0.008198] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.009735] smp: Bringing up secondary CPUs ...
[    0.011016] Detected VIPT I-cache on CPU1
[    0.011067] GICv3: CPU1: found redistributor 100 region 0:0x00000000fd480000
[    0.011127] CPU1: Booted secondary processor 0x0000000100 [0x412fd050]
[    0.011991] Detected VIPT I-cache on CPU2
[    0.012034] GICv3: CPU2: found redistributor 200 region 0:0x00000000fd4a0000
[    0.012078] CPU2: Booted secondary processor 0x0000000200 [0x412fd050]
[    0.012891] Detected VIPT I-cache on CPU3
[    0.012934] GICv3: CPU3: found redistributor 300 region 0:0x00000000fd4c0000
[    0.012976] CPU3: Booted secondary processor 0x0000000300 [0x412fd050]
[    0.013106] smp: Brought up 1 node, 4 CPUs
[    0.018705] SMP: Total of 4 processors activated.
[    0.019174] CPU features: detected: 32-bit EL0 Support
[    0.019697] CPU features: detected: Data cache clean to the PoU not required for I/D coherence
[    0.020542] CPU features: detected: Common not Private translations
[    0.021155] CPU features: detected: CRC32 instructions
[    0.021661] CPU features: detected: RCpc load-acquire (LDAPR)
[    0.022222] CPU features: detected: LSE atomic instructions
[    0.022767] CPU features: detected: Privileged Access Never
[    0.023312] CPU features: detected: RAS Extension Support
[    0.023884] CPU features: detected: Speculative Store Bypassing Safe (SSBS)
[    0.045076] CPU: All CPU(s) started at EL2
[    0.057701] KASLR disabled due to lack of seed
[    0.058291] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.059268] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.060356] pinctrl core: initialized pinctrl subsystem
[    0.062045] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.064320] DMA: preallocated 1024 KiB GFP_KERNEL pool for atomic allocations
[    0.065299] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.066460] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.067837] thermal_sys: Registered thermal governor 'step_wise'
[    0.067847] thermal_sys: Registered thermal governor 'user_space'
[    0.068462] thermal_sys: Registered thermal governor 'power_allocator'
[    0.069508] cpuidle: using governor menu
[    0.070664] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.071474] ASID allocator initialised with 65536 entries
[    0.105771] cryptd: max_cpu_qlen set to 1000
[    0.108467] vcc3v3_sys: supplied by vcc12v_dcin
[    0.109531] vcc5v0_sys: supplied by vcc12v_dcin
[    0.110421] vcc5v0_usb: supplied by vcc12v_dcin
[    0.111538] iommu: Default domain type: Translated
[    0.112025] iommu: DMA domain TLB invalidation policy: strict mode
[    0.112938] SCSI subsystem initialized
[    0.113616] usbcore: registered new interface driver usbfs
[    0.114207] usbcore: registered new interface driver hub
[    0.114772] usbcore: registered new device driver usb
[    0.116775] clocksource: Switched to clocksource arch_sys_counter
[    0.117636] VFS: Disk quotas dquot_6.6.0
[    0.118094] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.123227] NET: Registered PF_INET protocol family
[    0.124183] IP idents hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.129173] tcp_listen_portaddr_hash hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.130094] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.130867] TCP established hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.132154] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes, linear)
[    0.133865] TCP: Hash tables configured (established 65536 bind 65536)
[    0.134649] UDP hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    0.135467] UDP-Lite hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    0.136529] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.137155] PCI: CLS 0 bytes, default 64
[    0.138580] hw perfevents: enabled with armv8_cortex_a55 PMU driver, 7 counters available
[    0.141262] workingset: timestamp_bits=46 max_order=21 bucket_order=0
[    0.149076] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.149660] jffs2: version 2.2 (NAND) (SUMMARY) (ZLIB) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.152235] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.153240] io scheduler mq-deadline registered
[    0.157971] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.160598] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.165622] loop: module loaded
[    0.165950] mtip32xx Version 1.3.1
[    0.167632] SPI driver spidev has no spi_device_id for siliconlabs,si3210
[    0.171893] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.172545] ehci-platform: EHCI generic platform driver
[    0.173449] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.174076] ohci-platform: OHCI generic platform driver
[    0.175387] usbcore: registered new interface driver usb-storage
[    0.176095] i2c_dev: i2c /dev entries driver
[    0.177617] sdhci: Secure Digital Host Controller Interface driver
[    0.178227] sdhci: Copyright(c) Pierre Ossman
[    0.178654] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.180380] ledtrig-cpu: registered to indicate activity on CPUs
[    0.181032] SMCCC: SOC_ID: ARCH_FEATURES(ARCH_SOC_ID) returned error: fffffffffffffffd
[    0.181962] usbcore: registered new interface driver usbhid
[    0.182513] usbhid: USB HID core driver
[    0.183719] NET: Registered PF_INET6 protocol family
[    0.185433] Segment Routing with IPv6
[    0.185849] In-situ OAM (IOAM) with IPv6
[    0.186297] NET: Registered PF_PACKET protocol family
[    0.186848] 8021q: 802.1Q VLAN Support v1.8
[    0.190516] sdhci-dwcmshc fe310000.mmc: deferred probe timeout, ignoring dependency
[    0.190556] reg-fixed-voltage vcc5v0-usb-host: deferred probe timeout, ignoring dependency
[    0.192129] reg-fixed-voltage vcc5v0-usb-hub: deferred probe timeout, ignoring dependency
[    0.193003] reg-fixed-voltage vcc5v0-usb-otg: deferred probe timeout, ignoring dependency
[    0.193842] reg-fixed-voltage vcc3v3-pcie: deferred probe timeout, ignoring dependency
[    0.194688] dw-apb-uart fe660000.serial: deferred probe timeout, ignoring dependency
[    0.196716] rk3x-i2c fdd40000.i2c: deferred probe timeout, ignoring dependency
[    0.197569] rk3x-i2c fe5e0000.i2c: deferred probe timeout, ignoring dependency
[    0.198974] Warning: unable to open an initial console.
[    0.199528] Waiting for root device PARTUUID=5452574f-02...

**Comment by coolsnowwolf** [comment]
Rockchip 5.15 内核目前不支持 FB，需要 5.19 内核
