### ISSUE TITLE
X86编译失败,编译提示找不到依赖，samba4-server 的 samba4-libs

### ISSUE THREAD

**Issue by SinglePledge** [coolsnowwolf/lede#10040]
## X86编译失败，编译提示找不到依赖，samba4-server 的 samba4-libs

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：编译提示找不到依赖，samba4-server 的 samba4-libs

### (2) 路由器型号和固件版本

A：X86
### (3) 详细日志

A：
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency samba4-libs for samba4-server
 * pkg_hash_fetch_best_installation_candidate: Packages for samba4-server found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-samba4:
 *      samba4-libs
 * opkg_install_cmd: Cannot install package luci-app-samba4.
 * check_conflicts_for: The following packages conflict with samba4-server:
 * check_conflicts_for:         samba36-server * 
 * opkg_install_cmd: Cannot install package samba4-server.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/x/lede'
make[1]: *** [package/Makefile:111: /home/x/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/x/lede'
make: *** [/opt/lede/x/new/lede/include/toplevel.mk:230: world] Error 2

**Comment by zhangguanzhang** [comment]
samba4 和 samba36-server 只能二选一
