### ISSUE TITLE
5.19内核设置ftp端口转发，访问ftp openwrt死机重启恢复，继续访问死机，其他的端口没测试以退回5.15内核

### ISSUE THREAD

**Issue by dongc123** [coolsnowwolf/lede#10058]
5.19内核设置ftp端口转发，访问ftp openwrt死机重启恢复，继续访问死机，其他的端口没测试以退回5.15内核

**Comment by coolsnowwolf** [comment]
标准 20 21 端口测试的么？

**Comment by dongc123** [comment]
> 标准 20 21 端口测试的么？

没有测试标准的20 和21端口

**Comment by dongc123** [comment]
> 标准 20 21 端口测试的么？

下次有版本更新我在编译测试下
