### ISSUE TITLE
7621机器刷最新源码编译的固件有线和无线网页加载很卡很慢，刷回几个星期前的固件网页正常秒开

### ISSUE THREAD

**Issue by vsvkhs** [coolsnowwolf/lede#10053]
几台7621的机器刷完有线连电脑都是打开任何网页都在一直转圈图片什么的都没法加载出来，刷回几个星期前的固件则无此现象。

**Comment by vsvkhs** [comment]
机器为5962，dir882，ac85p都会这样

**Comment by wuzhuang123** [comment]
我是有线连接时asp页面的OA不行，其他网页都没问题，ssh和钉钉有问题。无线连接时都能打开，就是2分钟断开一次。现在只能用备用路由器连主机去编译，不然坚持不到一次完整编译putty就挂了

**Comment by britneyjeanspears** [comment]
k2p正常。你这几个机器刚好都是用dsa的，估计是dsa的问题，自己改switch驱动试试吧。

**Comment by britneyjeanspears** [comment]
https://github.com/coolsnowwolf/lede/commit/c78af7bc2160cfca7feb6fd773a37621503582ce
参考这个，然后不保留配置刷入

**Comment by wuzhuang123** [comment]
> [c78af7b](https://github.com/coolsnowwolf/lede/commit/c78af7bc2160cfca7feb6fd773a37621503582ce) 参考这个，然后不保留配置刷入

瞎改了下，但是家里没带网口的电脑，砖了没法恢复。有机会了去弄个备用的路由器

**Comment by tckxjzc** [comment]
小米3g也是，刷完无线卡的不行。退回以前的版本就正常了

**Comment by tckxjzc** [comment]
猜测是最近的代码更新了，开了hwnat的原因
