### ISSUE TITLE
R22.8.2使用一段时间之后，端口无法DHCP，只能设置静态IP地址

### ISSUE THREAD

**Issue by yanxin152133** [coolsnowwolf/lede#10052]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：端口无法进行DHCP ，只能设置静态IP地址

### (2) 路由器型号和固件版本

A：
![image](https://user-images.githubusercontent.com/43341537/188267074-bcea9c58-8f2b-4b63-ab0d-dab1fc12e92c.png)

### (3) 详细日志

A：
以`eth1`为例：
![image](https://user-images.githubusercontent.com/43341537/188267105-c3b07c51-c99a-403e-86be-3ce56f6d1685.png)

系统日志：
Sat Sep  3 18:34:16 2022 daemon.notice netifd: Network device 'eth1' link is down
Sat Sep  3 18:34:16 2022 daemon.notice netifd: Interface 'lan' has link connectivity loss
Sat Sep  3 18:34:16 2022 kern.info kernel: [  328.693292] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Down
Sat Sep  3 18:34:20 2022 daemon.notice netifd: Network device 'eth1' link is up
Sat Sep  3 18:34:20 2022 daemon.notice netifd: Interface 'lan' has link connectivity
Sat Sep  3 18:34:20 2022 kern.info kernel: [  333.025910] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Sat Sep  3 18:34:26 2022 user.notice shadowsocksr: ssrplus redir udp error.restart!
Sat Sep  3 18:34:32 2022 daemon.crit dnsmasq[11961]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:34:32 2022 daemon.crit dnsmasq[11961]: FAILED to start up
Sat Sep  3 18:34:37 2022 daemon.crit dnsmasq[12139]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:34:37 2022 daemon.crit dnsmasq[12139]: FAILED to start up
Sat Sep  3 18:34:42 2022 daemon.crit dnsmasq[12264]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:34:42 2022 daemon.crit dnsmasq[12264]: FAILED to start up
Sat Sep  3 18:34:51 2022 daemon.crit dnsmasq[12696]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:34:51 2022 daemon.crit dnsmasq[12696]: FAILED to start up
Sat Sep  3 18:34:56 2022 daemon.crit dnsmasq[12785]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:34:56 2022 daemon.crit dnsmasq[12785]: FAILED to start up
Sat Sep  3 18:35:00 2022 cron.err crond[8589]: USER root pid 12820 cmd /usr/share/unblockneteasemusic/log_check.sh
Sat Sep  3 18:35:01 2022 daemon.crit dnsmasq[12827]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:35:01 2022 daemon.crit dnsmasq[12827]: FAILED to start up
Sat Sep  3 18:35:06 2022 daemon.crit dnsmasq[12868]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:35:06 2022 daemon.crit dnsmasq[12868]: FAILED to start up
Sat Sep  3 18:35:11 2022 daemon.crit dnsmasq[12905]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:35:11 2022 daemon.crit dnsmasq[12905]: FAILED to start up
Sat Sep  3 18:35:16 2022 daemon.crit dnsmasq[12942]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:35:16 2022 daemon.crit dnsmasq[12942]: FAILED to start up
Sat Sep  3 18:35:16 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Sat Sep  3 18:39:51 2022 user.notice shadowsocksr: ssrplus redir udp error.restart!
Sat Sep  3 18:39:57 2022 daemon.crit dnsmasq[15366]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:39:57 2022 daemon.crit dnsmasq[15366]: FAILED to start up
Sat Sep  3 18:40:00 2022 cron.err crond[8589]: USER root pid 15471 cmd /usr/share/unblockneteasemusic/log_check.sh
Sat Sep  3 18:40:02 2022 daemon.crit dnsmasq[15529]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:02 2022 daemon.crit dnsmasq[15529]: FAILED to start up
Sat Sep  3 18:40:07 2022 daemon.crit dnsmasq[15654]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:07 2022 daemon.crit dnsmasq[15654]: FAILED to start up
Sat Sep  3 18:40:15 2022 daemon.crit dnsmasq[16085]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:15 2022 daemon.crit dnsmasq[16085]: FAILED to start up
Sat Sep  3 18:40:20 2022 daemon.crit dnsmasq[16173]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:20 2022 daemon.crit dnsmasq[16173]: FAILED to start up
Sat Sep  3 18:40:25 2022 daemon.crit dnsmasq[16236]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:25 2022 daemon.crit dnsmasq[16236]: FAILED to start up
Sat Sep  3 18:40:30 2022 daemon.crit dnsmasq[16249]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:30 2022 daemon.crit dnsmasq[16249]: FAILED to start up
Sat Sep  3 18:40:35 2022 daemon.crit dnsmasq[16293]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:35 2022 daemon.crit dnsmasq[16293]: FAILED to start up
Sat Sep  3 18:40:40 2022 daemon.crit dnsmasq[16355]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:40:40 2022 daemon.crit dnsmasq[16355]: FAILED to start up
Sat Sep  3 18:40:40 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Sat Sep  3 18:44:36 2022 daemon.notice netifd: Network device 'eth1' link is down
Sat Sep  3 18:44:36 2022 daemon.notice netifd: Interface 'lan' has link connectivity loss
Sat Sep  3 18:44:36 2022 kern.info kernel: [  949.577285] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Down
Sat Sep  3 18:45:00 2022 cron.err crond[8589]: USER root pid 18363 cmd /usr/share/unblockneteasemusic/log_check.sh
Sat Sep  3 18:45:15 2022 user.notice shadowsocksr: ssrplus redir udp error.restart!
Sat Sep  3 18:45:22 2022 daemon.crit dnsmasq[18766]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:22 2022 daemon.crit dnsmasq[18766]: FAILED to start up
Sat Sep  3 18:45:27 2022 daemon.crit dnsmasq[18944]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:27 2022 daemon.crit dnsmasq[18944]: FAILED to start up
Sat Sep  3 18:45:32 2022 daemon.crit dnsmasq[19070]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:32 2022 daemon.crit dnsmasq[19070]: FAILED to start up
Sat Sep  3 18:45:40 2022 daemon.notice netifd: Network device 'eth1' link is up
Sat Sep  3 18:45:40 2022 daemon.notice netifd: Interface 'lan' has link connectivity
Sat Sep  3 18:45:40 2022 kern.info kernel: [ 1013.101907] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Sat Sep  3 18:45:40 2022 daemon.crit dnsmasq[19500]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:40 2022 daemon.crit dnsmasq[19500]: FAILED to start up
Sat Sep  3 18:45:45 2022 daemon.crit dnsmasq[19588]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:45 2022 daemon.crit dnsmasq[19588]: FAILED to start up
Sat Sep  3 18:45:50 2022 daemon.crit dnsmasq[19626]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:50 2022 daemon.crit dnsmasq[19626]: FAILED to start up
Sat Sep  3 18:45:55 2022 daemon.crit dnsmasq[19638]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:45:55 2022 daemon.crit dnsmasq[19638]: FAILED to start up
Sat Sep  3 18:46:00 2022 daemon.crit dnsmasq[19699]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:46:00 2022 daemon.crit dnsmasq[19699]: FAILED to start up
Sat Sep  3 18:46:05 2022 daemon.crit dnsmasq[19745]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Sat Sep  3 18:46:05 2022 daemon.crit dnsmasq[19745]: FAILED to start up
Sat Sep  3 18:46:05 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
内核日志：
[    0.976851] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.977519] PTP clock support registered
[    0.978659] Button Hotplug driver version 0.4.1
[    0.981103] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.981523] usbcore: registered new interface driver uas
[    0.981721] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    0.985073] init: - preinit -
[    1.011488] random: jshn: uninitialized urandom read (4 bytes read)
[    1.017658] random: jshn: uninitialized urandom read (4 bytes read)
[    1.019497] random: jshn: uninitialized urandom read (4 bytes read)
[    5.047740] mount_root: mounting /dev/root
[    5.047993] EXT4-fs (sda2): warning: mounting unchecked fs, running e2fsck is recommended
[    5.057072] EXT4-fs (sda2): re-mounted. Opts: (null). Quota mode: disabled.
[    5.057331] mount_root: loading kmods from internal overlay
[    5.061862] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[    5.062444] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[    5.075520] block: attempting to load /etc/config/fstab
[    5.075936] block: extroot: not configured
[    5.093369] EXT4-fs (sda1): warning: mounting unchecked fs, running e2fsck is recommended
[    5.093680] EXT4-fs (sda1): mounted filesystem without journal. Opts: (null). Quota mode: disabled.
[    5.097272] urandom-seed: Seeding with /etc/urandom.seed
[    5.100301] procd: - early -
[    5.611725] procd: - ubus -
[    5.614090] random: ubusd: uninitialized urandom read (4 bytes read)
[    5.661386] random: ubusd: uninitialized urandom read (4 bytes read)
[    5.661636] random: ubusd: uninitialized urandom read (4 bytes read)
[    5.662240] procd: - init -
[    5.687188] kmodloader: loading kernel modules from /etc/modules.d/*
[    5.691453] NET: Registered PF_ALG protocol family
[    5.697335] ntfs3: Max link count 4000
[    5.697452] ntfs3: Enabled Linux POSIX ACLs support
[    5.697577] ntfs3: Warning: Activated 64 bits per cluster. Windows does not support this
[    5.697778] ntfs3: Read-only LZX/Xpress compression included
[    5.699857] tun: Universal TUN/TAP device driver, 1.6
[    5.703460] e1000: Intel(R) PRO/1000 Network Driver
[    5.703601] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    5.705576] Intel(R) Gigabit Ethernet Linux Driver - version 5.10.2
[    5.705747] Copyright(c) 2007 - 2022 Intel Corporation.
[    5.797589] igb 0000:03:00.0: added PHC on eth0
[    5.797729] igb 0000:03:00.0: Intel(R) Gigabit Ethernet Linux Driver
[    5.797889] igb 0000:03:00.0: eth0: (PCIe:5.0GT/s:unknown) 
[    5.798032] igb 0000:03:00.0 eth0: MAC: a0:3e:6b:a0:b7:f6
[    5.798172] igb 0000:03:00.0: eth0: PBA No: Unknown
[    5.798309] igb 0000:03:00.0: LRO is disabled
[    5.798428] igb 0000:03:00.0: Using MSI-X interrupts. 1 rx queue(s), 1 tx queue(s)
[    5.889582] igb 0000:0b:00.0: added PHC on eth1
[    5.889717] igb 0000:0b:00.0: Intel(R) Gigabit Ethernet Linux Driver
[    5.889876] igb 0000:0b:00.0: eth1: (PCIe:5.0GT/s:unknown) 
[    5.890019] igb 0000:0b:00.0 eth1: MAC: a0:3e:6b:a0:b7:f7
[    5.890162] igb 0000:0b:00.0: eth1: PBA No: Unknown
[    5.890301] igb 0000:0b:00.0: LRO is disabled
[    5.890416] igb 0000:0b:00.0: Using MSI-X interrupts. 1 rx queue(s), 1 tx queue(s)
[    5.981570] igb 0000:13:00.0: added PHC on eth2
[    5.981705] igb 0000:13:00.0: Intel(R) Gigabit Ethernet Linux Driver
[    5.981865] igb 0000:13:00.0: eth2: (PCIe:5.0GT/s:unknown) 
[    5.982009] igb 0000:13:00.0 eth2: MAC: a0:3e:6b:a0:b7:f8
[    5.982153] igb 0000:13:00.0: eth2: PBA No: Unknown
[    5.982319] igb 0000:13:00.0: LRO is disabled
[    5.982437] igb 0000:13:00.0: Using MSI-X interrupts. 1 rx queue(s), 1 tx queue(s)
[    5.983542] igbvf: Intel(R) Gigabit Virtual Function Network Driver
[    5.983710] igbvf: Copyright (c) 2009 - 2012 Intel Corporation.
[    5.986004] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver
[    5.986172] ixgbe: Copyright (c) 1999-2016 Intel Corporation.
[    5.994495] cryptodev: driver 1.12 loaded.
[    5.995352] i2c_dev: i2c /dev entries driver
[    5.997089] 8139too: 8139too Fast Ethernet driver 0.9.28
[    6.004704] e1000e: Intel(R) PRO/1000 Network Driver
[    6.004846] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    6.007760] i40e: Intel(R) Ethernet Connection XL710 Network Driver
[    6.007933] i40e: Copyright (c) 2013 - 2019 Intel Corporation.
[    6.024223] iavf: Intel(R) Ethernet Adaptive Virtual Function Network Driver
[    6.024415] Copyright (c) 2013 - 2018 Intel Corporation.
[    6.025300] Intel(R) 2.5G Ethernet Linux Driver
[    6.025428] Copyright(c) 2018 Intel Corporation.
[    6.039197] usbcore: registered new interface driver r8152
[    6.041692] usbcore: registered new interface driver rtl8150
[    6.043226] usbcore: registered new interface driver ums-alauda
[    6.043537] usbcore: registered new interface driver ums-cypress
[    6.043855] usbcore: registered new interface driver ums-datafab
[    6.044155] usbcore: registered new interface driver ums-freecom
[    6.044763] usbcore: registered new interface driver ums-isd200
[    6.045241] usbcore: registered new interface driver ums-jumpshot
[    6.045575] usbcore: registered new interface driver ums-karma
[    6.045922] usbcore: registered new interface driver ums-sddr09
[    6.046262] usbcore: registered new interface driver ums-sddr55
[    6.046593] usbcore: registered new interface driver ums-usbat
[    6.051502] xt_time: kernel timezone is -0000
[    6.051942] usbcore: registered new interface driver ax88179_178a
[    6.064020] PPP generic driver version 2.4.2
[    6.064366] PPP MPPE Compression module registered
[    6.064710] NET: Registered PF_PPPOX protocol family
[    6.065517] wireguard: WireGuard 1.0.0 loaded. See www.wireguard.com for information.
[    6.065720] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    6.068844] kmodloader: done loading kernel modules from /etc/modules.d/*
[    7.124722] random: jshn: uninitialized urandom read (4 bytes read)
[    7.126473] random: ubusd: uninitialized urandom read (4 bytes read)
[    7.126698] random: ubus: uninitialized urandom read (4 bytes read)
[    9.225049] random: crng init done
[    9.225161] random: 68 urandom warning(s) missed due to ratelimiting
[   10.812249] 8021q: adding VLAN 0 to HW filter on device eth1
[   12.300246] 8021q: adding VLAN 0 to HW filter on device eth2
[   13.609923] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[   13.700098] 8021q: adding VLAN 0 to HW filter on device eth0
[   13.700357] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[  328.693292] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Down
[  333.025910] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[  949.577285] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Down
[ 1013.101907] igb 0000:0b:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX

**Comment by rongcenter** [comment]
估计还是adbyby的问题

**Comment by yanxin152133** [comment]
> 估计还是adbyby的问题

好像是我多点了几次重新连接lan口，然后那个dnsmasq出问题了。我恢复出厂设置好了

**Comment by uosX** [comment]
> 估计还是adbyby的问题

Wed Sep 21 00:12:22 2022 daemon.crit dnsmasq[19674]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:12:22 2022 daemon.crit dnsmasq[19674]: FAILED to start up
Wed Sep 21 00:12:22 2022 cron.err crond[19715]: crond (busybox 1.35.0) started, log level 8

x86的软路由也会这样子；
补充了以下2条订阅规则
https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
https://easylist-downloads.adblockplus.org/easylistchina.txt

关闭Turbo ACC网络加速的，DNS缓存选项后，问题依旧；
Wed Sep 21 00:15:25 2022 daemon.crit dnsmasq[23302]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:25 2022 daemon.crit dnsmasq[23302]: FAILED to start up
Wed Sep 21 00:15:26 2022 kern.warn kernel: [168501.324993] test 65534
Wed Sep 21 00:15:27 2022 kern.warn kernel: [168502.377737] test 65534
Wed Sep 21 00:15:27 2022 kern.warn kernel: [168503.433491] test 65534
Wed Sep 21 00:15:28 2022 kern.warn kernel: [168503.753960] test 65534
Wed Sep 21 00:15:29 2022 kern.warn kernel: [168504.498719] test 65534
Wed Sep 21 00:15:29 2022 kern.warn kernel: [168505.550004] test 65534
Wed Sep 21 00:15:30 2022 kern.warn kernel: [168505.836201] test 512
Wed Sep 21 00:15:30 2022 daemon.crit dnsmasq[23325]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:30 2022 daemon.crit dnsmasq[23325]: FAILED to start up
Wed Sep 21 00:15:31 2022 kern.warn kernel: [168506.604748] test 65534
Wed Sep 21 00:15:32 2022 kern.warn kernel: [168507.658410] test 65534
Wed Sep 21 00:15:33 2022 kern.warn kernel: [168508.713028] test 65534
Wed Sep 21 00:15:34 2022 kern.warn kernel: [168509.768541] test 65534
Wed Sep 21 00:15:35 2022 daemon.crit dnsmasq[23346]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:35 2022 daemon.crit dnsmasq[23346]: FAILED to start up
Wed Sep 21 00:15:35 2022 kern.warn kernel: [168510.819120] test 65534
Wed Sep 21 00:15:36 2022 kern.warn kernel: [168511.868564] test 65534
Wed Sep 21 00:15:37 2022 kern.warn kernel: [168512.922035] test 65534
Wed Sep 21 00:15:37 2022 kern.warn kernel: [168513.818559] test 65534
Wed Sep 21 00:15:38 2022 kern.warn kernel: [168513.977830] test 65534
Wed Sep 21 00:15:39 2022 kern.warn kernel: [168515.029287] test 65534
Wed Sep 21 00:15:40 2022 daemon.crit dnsmasq[23378]: bad option at line 1 of /var/etc/dnsmasq-adbyby.d/04-dnsmasq.adblock
Wed Sep 21 00:15:40 2022 daemon.crit dnsmasq[23378]: FAILED to start up
Wed Sep 21 00:15:40 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Wed Sep 21 00:15:40 2022 kern.warn kernel: [168516.084328] test 65534
Wed Sep 21 00:15:41 2022 kern.warn kernel: [168517.137872] test 65534
Wed Sep 21 00:15:41 2022 kern.warn kernel: [168517.241848] test 512
Wed Sep 21 00:15:43 2022 kern.warn kernel: [168518.189266] test 65534

**Comment by yanxin152133** [comment]
我直接把这个插件给卸载了，反正也没啥用处

uosX ***@***.***>于2022年9月21日 周三上午12:18写道：
