### ISSUE TITLE
请问Rockchip emmc线刷包如何生成？

### ISSUE THREAD

**Issue by jzhou404** [coolsnowwolf/lede#10054]
请问R22.8.22 Release : Let's Rock !~ 里emmc_update 为线刷文件，在 maskrom 模式刷入 emmc的刷机文件， 是如何生成的？ 

我编译只能生成sysupgrade 是 web 升级文件

谢谢

**Comment by HongJie-Master** [comment]
目前貌似maskrom处于闭源状态

**Comment by jzhou404** [comment]
> 目前貌似maskrom处于闭源状态

我看这里 https://github.com/coolsnowwolf/lede/releases/tag/20220716 的发布，所以请教版主一下。

**Comment by coolsnowwolf** [comment]
emmc 格式是 RKDEV 的闭源代码生成的
