### ISSUE TITLE
固件会隔三差五自动重启，没有任何日志可查看

### ISSUE THREAD

**Issue by daidaiwood** [coolsnowwolf/lede#1008]
主机名 | OpenWrt
主机型号 | Netgear Nighthawk X4S R7800
架构 | ARMv7 Processor rev 0 (v7l)
固件版本 | OpenWrt R9.1.1 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
内核版本 | 4.14.91
本地时间 | Tue Jan 15 09:43:27 2019
运行时间 | 2h 38m 22s

最近几个月刷机固件都会出现隔三差五自动重启，重启后没有任何日志可供分析。
请问有什么有什么方法可以找到自动重启原因？

**Comment by hcym** [comment]
我的还行，不过没用大雕的默认，只保留翻墙有关的东西，其他都去掉默认选项。就是v2有点不得劲，换成ssr反而快点

**Comment by opsiff** [comment]
do not save logs in /tmp

**Comment by qiang-yu** [comment]
我也遇到这个情况了，隔几个小时就会自己莫名其妙的重启，找不出原因

**Comment by freeznet** [comment]
同R7800，同样的问题，有时候还会很频繁的重启，同找不出原因
