### ISSUE TITLE
docker无法拉取镜像

### ISSUE THREAD

**Issue by fuokgfw** [coolsnowwolf/lede#10085]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：使用dockerman，无法拉取镜像，报错code:200 operation not supported!，之前的老固件docker版本为20.10.17，今天编译下来发现docker版本更新了才出现这个问题，是不是不兼容

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

今天刚编译的最新固件

**Comment by achinese888** [comment]
解决了吗
我也是

**Comment by fuokgfw** [comment]
> 解决了吗 我也是
没有，应该是dockerhub的大佬们还没适配，9号才更新的docker

**Comment by fuokgfw** [comment]
dockerd的makefile版本没改，还是20.10.18
