### ISSUE TITLE
ESXI 6.7U3的虚机版LEDE执行reboot会变成关机

### ISSUE THREAD

**Issue by shzstone** [coolsnowwolf/lede#10082]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：ESXI的虚机版LEDE执行reboot会变成关机

### (2) 路由器型号和固件版本

A：X86 ESXI虚机版，试过很多个版本，发现都是一样，但是在网上又搜索不到任何类似的信息，是我哪里配置的有问题吗？

### (3) 详细日志

A：执行reboot就关机了，重启后日志就没了，采集不到日志

**Comment by guoshh1978** [comment]
难道就我有这种情况？算了，再过一天没人回答就关掉算了。。。
