### ISSUE TITLE
生成的固件运行时总有这个错误提示应该修改哪里

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#10092]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
daemon.err uhttpd[3401]: sh: out of range
daemon.err uhttpd[3401]: sh: out of range
daemon.err uhttpd[3401]: sh: out of range
daemon.err uhttpd[3401]: sh: out of range
daemon.err uhttpd[3401]: sh: out of range

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by ccblinda** [comment]
同样问题

**Comment by EnnawYang** [comment]
turboacc的问题，打开页面就会有错误日志
