### ISSUE TITLE
请问K3的无线除了选择k3wifi，还需要选择什么包？

### ISSUE THREAD

**Issue by chsalan** [coolsnowwolf/lede#101]
感谢谢大神开源！
只选择k3wifi，发现5g信号比2.4g信号差10-20，而且5g信号不稳定，请问除了选择k3wifi，还需要选择什么包？

**Comment by chsalan** [comment]
求大神K3的.config配置文件 @coolsnowwolf

**Comment by wheretoteardown** [comment]
kernel model找到wireless drivers，选中brcmfmac
firmware选中brcmfmac-4366

**Comment by chsalan** [comment]
感谢楼上的兄弟，不过在L大提供的这个SDK中：
kernel mode是自动选中brcmfmac
firmware是在Extra packages下，也是自动选中的。
这两天，我在LEDE官版上直接添加L大的K3机型相关驱动和patch支持，无线貌似是OK的。
