### ISSUE TITLE
5.10选了IPV6编译失败

### ISSUE THREAD

**Issue by cyzzc** [coolsnowwolf/lede#10107]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by w311ang** [comment]
同问题

**Comment by bootli** [comment]
一样

**Comment by nn-lang** [comment]
一样

**Comment by binge8** [comment]
一样
![1663118662751](https://user-images.githubusercontent.com/53508344/190037885-33540ddb-6a2b-4fa8-8335-64c61cba60d3.png)

**Comment by odex365** [comment]
一样的问题
Collected errors:
 * check_data_file_clashes: Package kmod-ip6tables wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/lib/modules/5.4.203/nf_log_ipv6.ko
	But that file is already provided by package  * kmod-nf-log6
 * opkg_install_cmd: Cannot install package kmod-ipt-raw6.
 * check_data_file_clashes: Package kmod-ip6tables wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/lib/modules/5.4.203/nf_log_ipv6.ko
	But that file is already provided by package  * kmod-nf-log6
 * opkg_install_cmd: Cannot install package kmod-ipt-nat6.
 * check_data_file_clashes: Package kmod-ip6tables wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/lib/modules/5.4.203/nf_log_ipv6.ko
	But that file is already provided by package  * kmod-nf-log6
 * opkg_install_cmd: Cannot install package kmod-ip6tables.
 * check_data_file_clashes: Package kmod-ip6tables wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/lib/modules/5.4.203/nf_log_ipv6.ko
	But that file is already provided by package  * kmod-nf-log6
 * opkg_install_cmd: Cannot install package ip6tables.
