### ISSUE TITLE
更新源码后执行 make download -j1 V=s 后出现以下提示

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#10118]
X86

更新源码后执行 make download -j1 V=s 后出现以下提示

![无标题](https://user-images.githubusercontent.com/38887306/190352101-f1390630-a15b-40f8-bbde-1002b54728fc.png)

**Comment by Aes64X** [comment]
llvm-project-14.0.6.src估计炸了，在等错误报告，这玩意单线程太慢了。
