### ISSUE TITLE
miniupnpd报错

### ISSUE THREAD

**Issue by tone88** [coolsnowwolf/lede#10127]
今天最新源码编辑，X86
日志报错如下图：
![photo_2022-09-16_10-39-40](https://user-images.githubusercontent.com/47731895/190546452-ebc4040d-2dc3-4278-8e23-36f5ca7edbcb.jpg)
是不是和最近切换过版本有关？

**Comment by firkerword** [comment]
一样    把安全模式关了好像就没了

**Comment by suizhenmin** [comment]
有同样问题。

**Comment by xiaojing110** [comment]
同样的问题

**Comment by conscloud** [comment]
![image](https://user-images.githubusercontent.com/18484709/190829718-73b041c0-dea0-441a-84e2-aeab128deb9a.png)
报错日志
