### ISSUE TITLE
K3编译出错，bcm53xx系列target-arm_cortex-a9分支 代码有问题

### ISSUE THREAD

**Issue by anjue39** [coolsnowwolf/lede#10132]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
有类似的问题，9.13日开始出现，至今仍有问题。请lede重视并修复。

同类一模一样的问题如下
[K3 5.15内核编译错误 #10131]
K3编译时出错 #10129
[9.13日开始，lede源makefile时出现下面问题 #10120]

2. 详细叙述

### (1) 具体问题

A：如下图，经测试，x86没这个问题。斐讯k3，有问题。发生在bcm53xx系列target-arm_cortex-a9分支

### (2) 路由器型号和固件版本

A：经测试，x86没这个问题。斐讯k3，有问题。发生在bcm53xx系列target-arm_cortex-a9分支

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/98279987/190730786-beb73d7a-51da-4c74-be1a-a1687d484e96.png)

**Comment by mitsukileung** [comment]
5.15内核把easymesh删除后，可以编译成功

![无标题](https://user-images.githubusercontent.com/38887306/190836410-6a4759e8-1f9a-426a-8d54-12536eb7b157.png)
