### ISSUE TITLE
建议：openwrt的防火墙默认开启IPv6外网访问

### ISSUE THREAD

**Issue by AutoCONFIG** [coolsnowwolf/lede#10135]
建议openwrt默认状态下，防火墙开启IPv6外网访问，即通信规则里接受所有地址和端口的对内访问。
体现在“BitComet”软件上就是IPv6端口开放

很多厂家的家用路由器（TP-Link，水星，腾达等等）的IPv6防火墙默认状态下就接受全部外部访问。我感觉对于大多数用户而言，默认开放IPv6访问是优大于劣的，其他一些需要阻塞IPv6外部访问的用户，想必也会有这方面的动手配置能力。

可能我的建议不够合理，考虑的比较片面，希望大家给一些意见，共同完善openwrt

**Comment by Cathgao** [comment]
默认开放端口方便当肉鸡吗。opw
rt的防火墙设置又不难，要开啥端口去通信规则里加一下就行了，几分钟都不要

**Comment by wybb** [comment]
既然叫防火墙，那肯定是默认设置是严格模式，对于不懂精通网络的用户就应该安全第一，假如你对端口开放有需求，那你本身就属于对技术有要求的小部分用户，自己去打开就是了
