### ISSUE TITLE
K3 5.15内核编译错误

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#10131]
K3

![无标题](https://user-images.githubusercontent.com/38887306/190716369-dc7c9b48-e18e-4dbc-959b-1e053df23630.png)

K3 5.15内核编译错误

**Comment by anjue39** [comment]
同样的问题，反馈好几天了，老大可能还没重视，这个问题很严重，都进行不下去，代码在bcm53xx系，arm-9分支代码有问题

**Comment by mitsukileung** [comment]
> 同样的问题，反馈好几天了，老大可能还没重视，这个问题很严重，都进行不下去，代码在bcm53xx系，arm-9分支代码有问题

![无标题](https://user-images.githubusercontent.com/38887306/190836325-c6b0ce48-c704-4d66-ab8d-0afc12f5b5c7.png)

刚刚试过把easymesh删了可以编译成功

**Comment by hcym** [comment]
没编译这个easy，还是出错，不管了，两年没刷，就是编译看看的

**Comment by anjue39** [comment]
我配置中没设easymesh也不成功



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mitsukileung ***@***.***&gt;
发送时间: 2022年9月17日 10:07
收件人: coolsnowwolf/lede ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [coolsnowwolf/lede] K3 5.15内核编译错误 (Issue #10131)





  
同样的问题，反馈好几天了，老大可能还没重视，这个问题很严重，都进行不下去，代码在bcm53xx系，arm-9分支代码有问题
  

 
刚刚试过把easymesh删了可以编译成功

**Comment by anjue39** [comment]
你说的删指的是config中取消？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mitsukileung ***@***.***&gt;
发送时间: 2022年9月17日 10:07
收件人: coolsnowwolf/lede ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [coolsnowwolf/lede] K3 5.15内核编译错误 (Issue #10131)





  
同样的问题，反馈好几天了，老大可能还没重视，这个问题很严重，都进行不下去，代码在bcm53xx系，arm-9分支代码有问题
  

 
刚刚试过把easymesh删了可以编译成功

**Comment by anjue39** [comment]
编译20多次了，都不行，代码明显有问题
从9.13日开始一换内核就根本编译不成



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hcym ***@***.***&gt;
发送时间: 2022年9月17日 10:10
收件人: coolsnowwolf/lede ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [coolsnowwolf/lede] K3 5.15内核编译错误 (Issue #10131)





 
没编译这个easy，还是出错，不管了，两年没刷，就是编译看看的

**Comment by mitsukileung** [comment]
我用的5.15内核，不是5.10，看清楚上图
