### ISSUE TITLE
有人用frp么，编译后的R8或R9一直提示tcp_mux不一致，但实际服务端都是开启了的。

### ISSUE THREAD

**Issue by ChuckPeng** [coolsnowwolf/lede#1014]
原来在R7上是可以得，升级后就不行了。但在R8或R9路由下的windows主机用frpc.exe测试一切正常，路由上就提示这个问题：tcp_mux不一致

**Comment by zxlhhyccc** [comment]
修改package/lean/luci-app-frpc/root/etc/init.d/frp，将：
echo "${opt}=true" >> $tmpconf，修改为：
echo "${opt}=1" >> $tmpconf
就可以解决！
