### ISSUE TITLE
现在R5S编译的都是5.15内核版本，，怎么编译5.10的

### ISSUE THREAD

**Issue by hai2012** [coolsnowwolf/lede#10149]
lede/target/linux/rockchip/Makefile
把KERNEL_PATCHVER=5.15,改成5.10的
编译最后失败的，，怎么解决啊

rm -f /home/hai/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3328-nanopi-neo3.dtb.tmp
make[5]: Leaving directory '/home/hai/lede/target/linux/rockchip/image'
make[4]: *** [Makefile:24: install] Error 2
make[4]: Leaving directory '/home/hai/lede/target/linux/rockchip'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/hai/lede/target/linux'
time: target/linux/install#5.21#1.51#48.16
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/hai/lede'
make[1]: *** [target/Makefile:24: /home/hai/lede/staging_dir/target-aarch64_generic_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/hai/lede'
make: *** [/home/hai/lede/include/toplevel.mk:230：world] 错误 2

A：
[新建文本文档 (3).txt](https://github.com/coolsnowwolf/lede/files/9593887/3.txt)

**Comment by DHDAXCW** [comment]
rk356x不支持5.10以下
