### ISSUE TITLE
云编译固件nginx的附件大小如何再编译前更改大一些

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#10157]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
云编译拉取的lede，使用nginx作为http服务，但是编译后更新固件总提示没有足够的空间，查阅发现需要更改nginx的配置文件，有什么办法在编译前能够改成需要的大小，默认配置文件里是256，希望改成1024或者2048
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Jejz168** [comment]
CONFIG_TARGET_ROOTFS_PARTSIZE=2048

**Comment by sjkhsl** [comment]
找到解决办法了吗？
