### ISSUE TITLE
Ubuntu Arm 编译 x86_64 找不到 cpuid.h

### ISSUE THREAD

**Issue by qiyuey** [coolsnowwolf/lede#10162]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Ubuntu Arm 交叉编译 x86_64 时，编译 iucode-tool 时找不到 cpuid.h，其中 config 里面并没有选择这个包，但是编译的时候还是被加上了

### (2) 路由器型号和固件版本

A：x86_64 软路由，版本 a7a5b42

### (3) 详细日志

A：configure: project-wide base CPPFLAGS: -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include
configure: project-wide base CFLAGS:   -O2 -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include
configure: project-wide base LDFLAGS:  -L/home/parallels/lede/staging_dir/host/lib -L/home/parallels/lede/staging_dir/hostpkg/lib -L/home/parallels/lede/staging_dir/target-x86_64_musl/host/lib
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating iucode_tool.8
config.status: creating iucode_tool_config.h
config.status: executing depfiles commands
touch /home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1/.configured
CFLAGS="-O2 -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include" CPPFLAGS="-I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include" CXXFLAGS="" LDFLAGS="-L/home/parallels/lede/staging_dir/host/lib -L/home/parallels/lede/staging_dir/hostpkg/lib -L/home/parallels/lede/staging_dir/target-x86_64_musl/host/lib" make -j1 -C /home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1  
make[4]: Entering directory '/home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1'
make  all-am
make[5]: Entering directory '/home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1'
gcc -DHAVE_CONFIG_H -I.   -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include  -O2 -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include -MT intel_microcode.o -MD -MP -MF .deps/intel_microcode.Tpo -c -o intel_microcode.o intel_microcode.c
mv -f .deps/intel_microcode.Tpo .deps/intel_microcode.Po
gcc -DHAVE_CONFIG_H -I.   -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include  -O2 -I/home/parallels/lede/staging_dir/host/include -I/home/parallels/lede/staging_dir/hostpkg/include -I/home/parallels/lede/staging_dir/target-x86_64_musl/host/include -MT iucode_tool.o -MD -MP -MF .deps/iucode_tool.Tpo -c -o iucode_tool.o iucode_tool.c
iucode_tool.c:33:10: fatal error: cpuid.h: No such file or directory
   33 | #include <cpuid.h>
      |          ^~~~~~~~~
compilation terminated.
make[5]: *** [Makefile:440: iucode_tool.o] Error 1
make[5]: Leaving directory '/home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1'
make[4]: *** [Makefile:329: all] Error 2
make[4]: Leaving directory '/home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1'
make[3]: *** [Makefile:49: /home/parallels/lede/build_dir/hostpkg/iucode-tool-2.3.1/.built] Error 2
make[3]: Leaving directory '/home/parallels/lede/package/system/iucode-tool'
time: package/system/iucode-tool/host-compile#1.79#1.01#2.62
    ERROR: package/system/iucode-tool [host] failed to build.
make[2]: *** [package/Makefile:114: package/system/iucode-tool/host/compile] Error 1
make[2]: Leaving directory '/home/parallels/lede'
make[1]: *** [package/Makefile:110: /home/parallels/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/parallels/lede'
make: *** [/home/parallels/lede/include/toplevel.mk:230：world] 错误 2

**Comment by zhangguanzhang** [comment]
貌似被这个修复了 https://github.com/coolsnowwolf/lede/commit/d0460e6b9258ccd64abb5bbc1becddcc17269616
