### ISSUE TITLE
请问默认设置编译的插件在编译的时候，在make menuconfig是不是取消勾选也会被编译？

### ISSUE THREAD

**Issue by yanxin152133** [coolsnowwolf/lede#10160]
比如这个`luci-app-adbyby-plus`，在`make menuconfig`的时候取消勾选，
<img width="495" alt="image" src="https://user-images.githubusercontent.com/43341537/191197351-6d689fad-2a59-4557-a8bd-98b896e514ed.png">

但是默认设置还是有的
<img width="418" alt="image" src="https://user-images.githubusercontent.com/43341537/191197795-d1566443-3cd2-4b85-b464-818b3bc12b94.png">

**Comment by hzjnet** [comment]
> 比如这个`luci-app-adbyby-plus`，在`make menuconfig`的时候取消勾选， <img alt="image" width="495" src="https://user-images.githubusercontent.com/43341537/191197351-6d689fad-2a59-4557-a8bd-98b896e514ed.png">
> 
> 但是默认设置还是有的 <img alt="image" width="418" src="https://user-images.githubusercontent.com/43341537/191197795-d1566443-3cd2-4b85-b464-818b3bc12b94.png">

不会的

**Comment by yanxin152133** [comment]
> > 比如这个`luci-app-adbyby-plus`，在`make menuconfig`的时候取消勾选， <img alt="image" width="495" src="https://user-images.githubusercontent.com/43341537/191197351-6d689fad-2a59-4557-a8bd-98b896e514ed.png">
> > 但是默认设置还是有的 <img alt="image" width="418" src="https://user-images.githubusercontent.com/43341537/191197795-d1566443-3cd2-4b85-b464-818b3bc12b94.png">
> 
> 不会的
我再试试，好几次编译这个插件都还在

**Comment by hzjnet** [comment]
> > > 比如这个`luci-app-adbyby-plus`，在`make menuconfig`的时候取消勾选， <img alt="image" width="495" src="https://user-images.githubusercontent.com/43341537/191197351-6d689fad-2a59-4557-a8bd-98b896e514ed.png">
> > > 但是默认设置还是有的 <img alt="image" width="418" src="https://user-images.githubusercontent.com/43341537/191197795-d1566443-3cd2-4b85-b464-818b3bc12b94.png">
> > 
> > 
> > 不会的
> > 我再试试，好几次编译这个插件都还在

那是其它地方还有该配置，比如：target/linux/ipq896x/Makefile

**Comment by GreatMichaelLee** [comment]
我也发现你这个问题，我一般都是采用暴力方式，直接编辑.config然后直接搜索相关的包，全部注释掉。这样才算干净，不然总是有狗皮膏药粘着。
