### ISSUE TITLE
友善R2S

### ISSUE THREAD

**Issue by 159321** [coolsnowwolf/lede#10176]
友善r2s编译失败

友善R2s 版本5.15.69

### (3) 详细日志

A：/home/www/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2022.07/scripts/dtc/pylibfdt/setup.py:21: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup, Extension
error: command 'swig' failed: No such file or directory
make[6]: *** [scripts/dtc/pylibfdt/Makefile:30: rebuild] Error 1
make[5]: *** [scripts/Makefile.build:398: scripts/dtc/pylibfdt] Error 2
make[4]: *** [Makefile:2069: scripts_dtc] Error 2
make[4]: Leaving directory '/home/www/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2022.07'
make[3]: *** [Makefile:247: /home/www/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2022.07/.built] Error 2
make[3]: Leaving directory '/home/www/lede/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r2s-rk3328/compile#27.75#7.02#31.80
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r2s-rk3328).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/www/lede'
make[1]: *** [package/Makefile:110: /home/www/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/www/lede'
make: *** [/home/www/lede/include/toplevel.mk:230：world] 错误 2

#

**Comment by adamgonglj** [comment]
编译5.19，去改/lede/target/linux/rockchip/makefile的第10行，把5.15改成5.19，可以编译成功的。
