### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wwz09** [coolsnowwolf/lede#10185]
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
76ab48|OK  |   111MiB/s|/workdir/openwrt/tmp/aria2c/jq-1.6.tar.gz_npfEbQVPSH

Status Legend:
(OK):download completed.
Hash of the downloaded file does not match (file: 5de8c8e29aaa3fb9cc6b47bb27299f271354ebb72514e3accadc7d38b5bbaa72, requested: 9625784cf2e4fd9842f1d407681ce4878b5b0dcddbcd31c6135114a30c71e6a8) - deleting download.
No more mirrors to try - giving up.
make[3]: *** [Makefile:52: /workdir/openwrt/dl/jq-1.6.tar.gz] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/utils/jq'
time: package/feeds/packages/jq/compile#0.22#0.10#0.41
    ERROR: package/feeds/packages/jq failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/jq/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by DHDAXCW** [comment]
因为源码改aria2下载，需要安装依赖 `sudo apt install aria2` 即可解决
