### ISSUE TITLE
小米4A千兆版云编译报错

### ISSUE THREAD

**Issue by lxc368** [coolsnowwolf/lede#10182]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：小米4A千兆版云编译报错

### (2) 路由器型号和固件版本

A：小米路由器4A千兆版，最新源码

### (3) 详细日志

A：[Github Action](https://github.com/lxc368/MI4A-G_Openwrt/actions/runs/3121570024/jobs/5062954187)

**Comment by aiamadeus** [comment]
你这报错日志就不能贴出来吗，还要人自己去翻

**Comment by lxc368** [comment]
#10143
