### ISSUE TITLE
K3编译通过，但是Bin目录里没有固件文件。

### ISSUE THREAD

**Issue by arthas2015** [coolsnowwolf/lede#102]
只有packages和targets两个文件夹，targets里面一路点进去，有一堆。trx文件，大小都在9MB左右。没有bin文件。

**Comment by lphgor** [comment]
本来就是 trx 格式的呀，配置里就是这么设定的。
[https://github.com/coolsnowwolf/lede/blob/master/target/linux/bcm53xx/image/Makefile#L254](https://github.com/coolsnowwolf/lede/blob/master/target/linux/bcm53xx/image/Makefile#L254)

**Comment by arthas2015** [comment]
噢，是这样啊。下午又编译了一个EA8500的，有bin文件。这说明每个cpu或者机型的配置文件都不一样吗？麻烦再告诉一下：那个trx才不到10MB，有luci界面的吗？其他所有的apk是需要自己手动安装吗？
