### ISSUE TITLE
这是哪里出问题了，日志里全是这些？

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#10207]
IPQ870X

这是系统日志

![截屏2022-09-30 下午10 38 25](https://user-images.githubusercontent.com/38887306/193294313-39b1d9a0-f554-486e-a976-362c663bac91.png)

这是内核日志

![截屏2022-09-30 下午10 39 07](https://user-images.githubusercontent.com/38887306/193294453-fe081215-33c4-403a-bbbb-a2aeeffeb024.png)

大佬们，这是什么问题？

**Comment by uosX** [comment]
关闭 Turbo Acc 软件流量分载
检查修改/etc/config/firewall以下；
flow_offloading_hw '0'
flow_offloading '0'

**Comment by mitsukileung** [comment]
> 关闭 Turbo Acc 软件流量分载 检查修改/etc/config/firewall以下； flow_offloading_hw '0' flow_offloading '0'

的确是这样，编译时同时选上了offloading 和 sfe 出现这些日志
