### ISSUE TITLE
红米AX6 自编译5.15版本

### ISSUE THREAD

**Issue by gtcar2020** [coolsnowwolf/lede#10202]
![图片](https://user-images.githubusercontent.com/90398542/193276918-dd79ece2-6dc0-4ed4-b01b-cacbe8a1951a.png)
上图所示，系统日志和内核日志都显示建议使用UBI block devices，如何解决？编译5.10版本没有这个提示，5.10版本的系统日志似乎也只是挂载了mtd 12 为ubifs.

**Comment by gtcar2020** [comment]
MTD device 如果没有执行ubiattach ,会不会引起flash不均衡的磨损？

**Comment by aiamadeus** [comment]
高版本内核就是这样的，忽略即可。
