### ISSUE TITLE
ShadowsocksR Plus + 对于 v2ray 有 bug

### ISSUE THREAD

**Issue by qiang-yu** [coolsnowwolf/lede#1020]
用三合一的 ShadowsocksR Plus +
1. 添加了 2 个 v2ray 服务器，想要尝试 监控自动切换 功能
2. 添加之后，重启 路由器
3. 重启之后， luci 界面进不去了 （路由器正常工作，可以上网，只是 luci 无法打开）

显示错误界面见界面截图

我手动 ssh 进入路由器，编辑   vim /etc/config/shadowsocksr  把里面一个 v2ray 服务器配置删除，重启路由器，一切恢复正常

结论： 如果加了多个v2ray服务器的配置，重启路由器之后， luci 会出错

![bug](https://user-images.githubusercontent.com/5996702/51421364-30601580-1bd8-11e9-84ff-b5e4103f75d0.png)

**Comment by xiaofami** [comment]
冒昧问下这个插件怎么添加自己的服务器，我的这个只有订阅地址可选呢 
![image](https://user-images.githubusercontent.com/4654044/57455728-5d772780-729e-11e9-958d-7136e5a637c6.png)
