### ISSUE TITLE
请教下；新编译的固件用于升级（系统-备份-升级里）后如何判断是否升级成功？

### ISSUE THREAD

**Issue by sheiy** [coolsnowwolf/lede#10215]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/12210038/193416929-eee213b9-26fc-490e-a283-1bca5411910d.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/12210038/193416940-248484e3-4c14-4cf3-be15-b29e08ffadb1.png">
我看这里没有变化

**Comment by 1054009064** [comment]
内核日志的编译时间

**Comment by mitsukileung** [comment]
或者看看计划任务里面有没有coremark 这个任务，如果升级完成后有，就应该是升级成功，如果没有就是没有成功

**Comment by zhangguanzhang** [comment]
网页下面不是有git的commit id吗

**Comment by Travel2Here** [comment]
你都会编译了还问这个？
