### ISSUE TITLE
请教如何添加wan口下面的dhcp选项，我看有些人编译出来的固件有这个标签

### ISSUE THREAD

**Issue by xuexijiaoben** [coolsnowwolf/lede#10222]
如下图中所示，可以直接在这里设置ipv6的一些选项，我编译出来的k2p没有这些选项，谢谢啦

![图片](https://user-images.githubusercontent.com/85658957/193720477-b3184889-4a9a-41da-a86c-a3f1219765da.png)

**Comment by lovehackintosh** [comment]
make menuconfig 勾选extra packages——>ipv6helper
