### ISSUE TITLE
最近编译的固件解压报错

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#10223]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：自从源码加入了固件压缩后，编译完的固件解压就报错，但是固件刷机使用是正常的

### (2) 路由器型号和固件版本

A：x86最新源码

### (3) 详细日志

A：看截图
![捕获](https://user-images.githubusercontent.com/53508344/193724337-94cab9e7-7c8e-4289-a395-f2797f2c22a3.JPG)

**Comment by lovehackintosh** [comment]
为什么要解压呢？
如果必须解压，请在Linux环境中用extra packages——ipv6helper

**Comment by binge8** [comment]
对啊，我为什么要解压啊，糊涂了

> 为什么要解压呢？ 如果必须解压，请在Linux环境中用squashfs-tools
