### ISSUE TITLE
取消选择IPV6支持，显示缺少依赖

### ISSUE THREAD

**Issue by iowclz** [coolsnowwolf/lede#10239]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
![image](https://user-images.githubusercontent.com/14866856/194583574-69a7b719-614a-47e4-a669-9faddcd6b445.png)

Package kmod-nft-core is missing dependencies for the following libraries:
nf_reject_ipv6.ko

### (1) 具体问题

A：取消选择IPV6支持，显示缺少依赖

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

Package kmod-nft-core is missing dependencies for the following libraries:
nf_reject_ipv6.ko

**Comment by gsblay** [comment]
rm .config
rm .config.old
重新配置

**Comment by iowclz** [comment]
> rm .config rm .config.old 重新配置

已解决，谢谢！
