### ISSUE TITLE
v2ray体积精简

### ISSUE THREAD

**Issue by starP-W** [coolsnowwolf/lede#1024]
看了一下v2ray的Makefile，感觉现在是简单地将v2ray和v2ctl加入固件中，且v2ctl在固件中的作用似乎只有加载配置文件。
根据v2ray的模块化和精简说明，将v2ray源码中main/distro/all/all.go中的
`_ "v2ray.com/core/main/json"`
进行注释并解除
`// _ "v2ray.com/core/main/jsonem"`
的注释后编译出的v2ray可以直接加载json文件而不必经过v2ctl。
经过上述操作后编译出的v2ray 4.13版经过i386 SDK编译后的ipk大小是4.7M且可运行(未测试是否能在openwrt下正常工作，但其它版本的可执行文件均能在对应的系统下正常运行)，日后根据v2ray的代码更新有可能可将文件体积在模块裁剪后进一步缩小。
不知大佬是否有兴趣对v2ray的安装再做进一步的修改?

**Comment by coolsnowwolf** [comment]
曾经做过，太麻烦了，放弃

**Comment by WKZD** [comment]
> 曾经做过，太麻烦了，放弃

订阅可以支持v2ray吗？
