### ISSUE TITLE
R4S 状态/概览显示不全

### ISSUE THREAD

**Issue by ZZMHA227** [coolsnowwolf/lede#10251]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
10月13日编译的R4S固件。如果做旁路由，删掉WAN口，则概览显示不全。再添加WAN口后则正常。看到之前的issues里，R2S也有这样的问题
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
![屏幕截图 2022-10-13 152735](https://user-images.githubusercontent.com/57690855/195532021-6f7b8962-73d0-4292-b5ae-e9a1124cd9fb.png)
![屏幕截图 2022-10-13 152751](https://user-images.githubusercontent.com/57690855/195532071-c3b5a5d8-17f0-4a17-afb4-bc34f7b61659.png)
![屏幕截图 2022-10-13 153659](https://user-images.githubusercontent.com/57690855/195532271-b868c4ad-8946-4bdf-8d68-f99210ff7f7c.png)
![屏幕截图 2022-10-13 153736](https://user-images.githubusercontent.com/57690855/195532417-4d4fa280-8aab-40c8-be69-8c028efe94a3.png)

### (2) 路由器型号和固件版本

A：R4S（R2S也有这可能)

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
没必要删除 WAN 口，又不妨碍你

**Comment by felixxiao99** [comment]
> 

兄弟，你也一样啊

**Comment by edmondfr** [comment]
这个问题搞得旁路由强迫症患者茶饭不思，夜不能寐
