### ISSUE TITLE
默认配置下，5.15编译通过，6.0编译失败，有日志

### ISSUE THREAD

**Issue by tony198911** [coolsnowwolf/lede#10254]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

默认配置下
5.15编译通过，6.0编译失败

### (2) 路由器型号和固件版本

N/A

### (3) 详细日志

A：
ERROR: module '/home/tony/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-6.0.1/drivers/dma-buf/dma-shared-buffer.ko' is missing.
modules/other.mk:138: recipe for target '/home/tony/lede/bin/targets/x86/64/packages/kmod-dma-buf_6.0.1-1_x86_64.ipk' failed
make[3]: *** [/home/tony/lede/bin/targets/x86/64/packages/kmod-dma-buf_6.0.1-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/tony/lede/package/kernel/linux'
time: package/kernel/linux/compile#1.44#0.12#1.55
    ERROR: package/kernel/linux failed to build.
package/Makefile:114: recipe for target 'package/kernel/linux/compile' failed
make[2]: *** [package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/home/tony/lede'
package/Makefile:110: recipe for target '/home/tony/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/tony/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/tony/lede'
/home/tony/lede/include/toplevel.mk:228: recipe for target 'world' failed

**Comment by coolsnowwolf** [comment]
git pull
