### ISSUE TITLE
k2p 潘多拉v2ray tls和速度问题

### ISSUE THREAD

**Issue by ntgeralt** [coolsnowwolf/lede#1025]
你好，感谢你制作的固件。使用中我发现几个问题，反馈一下：
1：v2ray实测能用，但看日志时间v2ray start是凌晨3点，我本机时间是11点。
2:测试ws+tls时，发现allowInsecure打钩会无法使用；去掉打钩则正常。但我服务端证书还有2个多月才过期，小火箭“允许不安全”关闭也是正常连接。
3：v2ray 速度油管固定7000kbps，PC同节点有30000kbps……

**Comment by youwei5683** [comment]
路由器性能问题。你换x86路由器速度马上上来

**Comment by ntgeralt** [comment]
> 路由器性能问题。你换x86路由器速度马上上来

PS:k2p 官改v2ray 28000kbps+
