### ISSUE TITLE
h68k-f 刷入自己编译固件无法启动

### ISSUE THREAD

**Issue by zhangguanzhang** [coolsnowwolf/lede#10286]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

刷sd卡后开机，接屏幕没开机tty输出，灯也不会亮

### (1) 具体问题

```
CONFIG_TARGET_rockchip=y
CONFIG_TARGET_rockchip_armv8=y

CONFIG_TARGET_DEVICE_rockchip_armv8_DEVICE_hinlink_opc-h68k=y

CONFIG_TARGET_KERNEL_PARTSIZE=18
CONFIG_TARGET_ROOTFS_PARTSIZE=656
# CONFIG_TARGET_ROOTFS_TARGZ is not set
CONFIG_TARGET_ROOTFS_EXT4FS=y
CONFIG_TARGET_ROOTFS_SQUASHFS=y

```

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by TendernessRadif** [comment]
EMMC启动 群禁言了 直接EMMC刷入且启动就行了

**Comment by aiamadeus** [comment]
emmc 有固件的话要先格式化掉，问就是 rk 的启不动主线 uboot（sd 卡正常启动如下图：
![test](https://user-images.githubusercontent.com/42570690/196932020-2cc2906e-098b-4b9c-ab33-c964907b743d.png)
