### ISSUE TITLE
拉取最新源码后make defconfig无法通过

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#10288]
make clean后拉取最新源码，然后rm -rf ./tmp && rm -rf ./feeds && rm -rf ./pacakges/feeds，接着./scripts/feeds update -a && ./scripts/feeds install -a，最后make defconfig依旧不通过，提示：
Collecting target info: done
Config.in:9: syntax error
Config.in:8: invalid statement
Config.in:9: invalid statement
Config.in:10: invalid statement

**Comment by lovehackintosh** [comment]
删掉重新clone,亲测可行

**Comment by bi4tms** [comment]
> 删掉重新clone,亲测可行

请教下，删掉哪些内容，如何重新克隆

**Comment by bi4tms** [comment]
> 删掉重新clone,亲测可行

重新clone是相当于删掉项目然后重建吗

**Comment by lovehackintosh** [comment]
对，就是删除lede文件夹，然后
   ```bash
   git clone https://github.com/coolsnowwolf/lede
   cd lede
   ./scripts/feeds update -a
   ./scripts/feeds install -a
   make menuconfig
   ```

**Comment by zhangguanzhang** [comment]
https://github.com/coolsnowwolf/lede/issues/10287
重复issue

**Comment by bi4tms** [comment]
> 对，就是删除lede文件夹，然后
> 
> ```shell
> git clone https://github.com/coolsnowwolf/lede
> cd lede
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> make menuconfig
> make download -j8
> make -j$(nproc)
> ```

感谢
