### ISSUE TITLE
同步最新源码后，保存配置出现以下错误

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#10284]
X86_64

执行 rm -rf ./tmp && rm -rf .config
        git pull
        ./scripts/feeds update -a && ./scripts/feeds install -a
        make menuconfig 配置完后
        ./scripts/diffconfig.sh > 64 保存配置时出现以下错误

Config.in:9: syntax error
Config.in:8: invalid statement
Config.in:9: invalid statement
Config.in:10: invalid statement
Config.in:9: syntax error
Config.in:8: invalid statement
Config.in:9: invalid statement
Config.in:10: invalid statement

**Comment by coolsnowwolf** [comment]
index 需要重新生成缓存

rm -rf ./tmp && rm -rf ./feeds && rm -rf ./pacakges/feeds

重新运行

**Comment by mitsukileung** [comment]
> index 需要重新生成缓存
> 
> rm -rf ./tmp && rm -rf ./feeds && rm -rf ./pacakges/feeds
> 
> 重新运行

还是会出错

执行完上面的命令，重新运行后还是出现错误

Config.in:9: syntax error
Config.in:8: invalid statement
Config.in:9: invalid statement
Config.in:10: invalid statement
can't open file 'tmp/.diffconfig.stage1' at ./scripts/kconfig.pl line 32.
Config.in:9: syntax error
Config.in:8: invalid statement
Config.in:9: invalid statement
Config.in:10: invalid statement
can't open file 'tmp/.diffconfig.stage2' at ./scripts/kconfig.pl line 32

**Comment by lovehackintosh** [comment]
重新生成缓存后还需要
```bash
./scripts/feeds update -a
./scripts/feeds install -a
```
如果还不行的话,删除重新clone，亲测可以成功。

**Comment by bi4tms** [comment]
> > 重新生成缓存后还需要
> > ```shell
> > ./scripts/feeds update -a
> > ./scripts/feeds install -a
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果还不行的话,删除重新clone，亲测可以成功。
> 
> 重clone后可以了，谢谢

请教下如何重新clone
