### ISSUE TITLE
复活节彩蛋是什么

### ISSUE THREAD

**Issue by cygmris** [coolsnowwolf/lede#1028]
[https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua](https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua)

编译的固件luci界面没有ssr-plus，最后发现12月份的一次commit把lua controller替换成了一个加密的二进制文件并备注为 (easter eggs) 复活节彩蛋，是什么彩蛋捏。

**Comment by redchenjs** [comment]
#881
