### ISSUE TITLE
拉取今天的最新代码自编译H68K-F型固件成功，但写TF卡后启动不了

### ISSUE THREAD

**Issue by HangYijun** [coolsnowwolf/lede#10295]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
拉取10-21的代码，在线编译H68k固件（配置全默认），成功生成img.gz文件，写TF卡后不能引导（gz直写，解压后用img写都不行）
### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by HangYijun** [comment]
相同的刷写方式写L大预制的openwrt-rockchip-R22.10.10-hinlink_opc-h68k-d-squashfs-sysupgrade.img.gz则可以引导，不知问题在哪里？

**Comment by zhangguanzhang** [comment]
https://github.com/coolsnowwolf/lede/issues/10286
