### ISSUE TITLE
编译AU58U时选v2ray出错

### ISSUE THREAD

**Issue by vvenemy** [coolsnowwolf/lede#1030]
编译AU58U时选v2ray就出错，不选正常出固件。

echo "s-sr-libev-S-S R-local" >> /home/qwe123/lede/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/s-sr-libev.default.installmake[3]: Leaving directory `/home/qwe123/lede/lede/package/lean/s-sr-libev'time: package/lean/s-sr-libev/compile#0.08#0.13#0.36make[3]: Entering directory `/home/qwe123/lede/lede/package/lean/v2ray'rm -f /home/qwe123/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-v4.13.0/.builttouch /home/qwe123/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-v4.13.0/.built_checkchmod +x /home/qwe123/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-v4.13.0/v2ray_armv7 && upx --ultra-brute /home/qwe123/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-v4.13.0/v2ray_armv7bash: upx: command not foundmake[3]: *** [/home/qwe123/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/v2ray-v4.13.0/.built] Error 127make[3]: Leaving directory `/home/qwe123/lede/lede/package/lean/v2ray'time: package/lean/v2ray/compile#0.04#0.03#0.20make[2]: *** [package/lean/v2ray/compile] Error 2make[2]: Leaving directory `/home/qwe123/lede/lede'make[1]: *** [/home/qwe123/lede/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2make[1]: Leaving directory `/home/qwe123/lede/lede'make: *** [world] 错误 2
--

**Comment by hcym** [comment]
哈哈，多了压缩压缩，还有v2包的下载地址有点怪，极其慢
