### ISSUE TITLE
系统升级到 Ubuntu 22.04.1 LTS 后无法编译

### ISSUE THREAD

**Issue by sheiy** [coolsnowwolf/lede#10305]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/12210038/197352743-c64d538e-2c2a-4412-b5ca-61076481c0be.png">

**Comment by ecrasy** [comment]
Build system setup 变了，22.04 需要安装不同的编译环境工具[官方setup](https://openwrt.org/docs/guide-developer/build-system/install-buildsystem)

**Comment by hcym** [comment]
好像没有什么不同，我的还是那句老话
