### ISSUE TITLE
K2无法编译出升级文件 squashfs-sysupgrade.bin

### ISSUE THREAD

**Issue by zhuzhengjing** [coolsnowwolf/lede#10307]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
准备编译一个K2的固件，拉取了最新代码，选择了psg1218a型号，其他都为默认。只能生成 initramfs-kernel.bin
将 `image/mt7620.mk` 改为 `IMAGE_SIZE := 16064k`，可以正常编译，编译出的大小超出psg1218a flash大小。
尝试修改 menuconfig，将所有能去的包都删掉，最终编译出的bin文件还是超过 `7872k` 

### (1) 具体问题

![image](https://user-images.githubusercontent.com/5308436/197367020-bce337ae-e044-4b28-a09c-40e7b55798cb.png)

### (2) 路由器型号和固件版本

A：psg1218a

### (3) 详细日志

A：无

**Comment by EnnawYang** [comment]
换个路由器吧！

**Comment by Haaooo** [comment]
同样的问题
