### ISSUE TITLE
syntax error: operand expected (error token is "*1024*1024")

### ISSUE THREAD

**Issue by openrouter** [coolsnowwolf/lede#10308]
issue1:
make mt7621 image  error

make[2]: Leaving directory '/home/tony/master/scripts/config'
bash: *1024*1024: syntax error: operand expected (error token is "*1024*1024")
bash: *1024*1024: syntax error: operand expected (error token is "*1024*1024")
time: target/linux/prereq#0.42#0.04#0.45

issue2：
 make[3] -C tools/findutils compile
 make[3] -C tools/bc compile
    ERROR: tools/cmake failed to build.

**Comment by lovehackintosh** [comment]
issue 2日志没发全,执行`make tools/install V=s -j1`把完整日志贴上来

**Comment by openrouter** [comment]
> issue 2日志没发全,执行`make tools/install V=s -j1`把完整日志贴上来

after updated cmake issue 2 shutdown, tks.

how is issue1 ?

**Comment by lovehackintosh** [comment]
please run `make target/linux/{clean,compile} V=s -j1` and provide full log

**Comment by openrouter** [comment]
full logfile  attached 
[make.log](https://github.com/coolsnowwolf/lede/files/9847791/make.log)

**Comment by lovehackintosh** [comment]
Please use ubuntu or debina to compile,don't use wsl

**Comment by openrouter** [comment]
> Please use ubuntu or debina to compile,don't use wsl

Host OS is 18.04.2-Ubuntu

**Comment by lovehackintosh** [comment]
Please use Ubuntu-20.04

**Comment by yuzhe1129** [comment]
This is the case with me. I don't know what happened

**Comment by yuzhe1129** [comment]
> Refer



> 请使用 Ubuntu-20.04

我也是使用20.04啊，也是出错这个错误 到底是什么引起的啊

**Comment by schidler** [comment]
我这也是一样，我是用docker措的编译环境，是否对什么工具的版本有要求？

bash: *1024*1024: syntax error: operand expected (error token is "*1024*1024")

确认是这里引起
/include/image.mk
167 ROOTFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE)*1024*1024)))

**Comment by yuzhe1129** [comment]
> 



> 我这也是一样，我是用docker的编译环境，对什么工具的版本有要求吗？
> 
> bash：_1024_ 1024：语法错误：预期操作数（错误标记为“ _1024_ 1024”）
> 
> 确认是这里引发 /include/image.mk 167 ROFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE) _1024_ 1024)))

是什么意思？我不怎么懂，我只会编译，能否解释简单点怎么解决

**Comment by schidler** [comment]
> > 
> 
> > 我这也是一样，我是用docker的编译环境，对什么工具的版本有要求吗？
> > bash：_1024_ 1024：语法错误：预期操作数（错误标记为“ _1024_ 1024”）
> > 确认是这里引发 /include/image.mk 167 ROFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE) _1024_ 1024)))
> 
> 是什么意思？我不怎么懂，我只会编译，能否解释简单点怎么解决

`ROOTFS_PARTSIZE := $(shell expr $$(( $(CONFIG_TARGET_ROOTFS_PARTSIZE) * 1024 * 1024)))
`
可以这样试下

**Comment by yuzhe1129** [comment]
> > > 
> > 
> > 
> > > 我这也是一样，我是用docker的编译环境，对什么工具的版本有要求吗？
> > > bash：_1024_ 1024：语法错误：预期操作数（错误标记为“ _1024_ 1024”）
> > > 确认是这里引发 /include/image.mk 167 ROFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE) _1024_ 1024)))
> > 
> > 
> > 是什么意思？我不怎么懂，我只会编译，能否解释简单点怎么解决
> 
> `ROOTFS_PARTSIZE := $(shell expr $$(( $(CONFIG_TARGET_ROOTFS_PARTSIZE) * 1024 * 1024))) ` 可以这样试下

:~$ cd lede
xxoo@ubuntu:~/lede$ ROOTFS_PARTSIZE := $(shell expr $$(( $(CONFIG_TARGET_ROOTFS_PARTSIZE) * 1024 * 1024)))
-bash: command substitution: 行 3: 未预期的符号“(”附近有语法错误
-bash: command substitution: 行 3: `shell expr $$(( $(CONFIG_TARGET_ROOTFS_PARTSIZE) * 1024 * 1024)))'


错误？

**Comment by schidler** [comment]
> > > > 
> > > 
> > > 
> > > > 我这也是一样，我是用docker的编译环境，对什么工具的版本有要求吗？
> > > > bash：_1024_ 1024：语法错误：预期操作数（错误标记为“ _1024_ 1024”）
> > > > 确认是这里引发 /include/image.mk 167 ROFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE) _1024_ 1024)))
> > > 
> > > 
> > > 是什么意思？我不怎么懂，我只会编译，能否解释简单点怎么解决
> > 
> > 
> > `ROOTFS_PARTSIZE := $(shell expr $$(( $(CONFIG_TARGET_ROOTFS_PARTSIZE) * 1024 * 1024))) ` 可以这样试下
> 
> ROOTFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE)_1024_1024)))
> 
> 看了下， 原来是echo 改了expr就行了？

+ifdef CONFIG_TARGET_ROOTFS_PARTSIZE
 ROOTFS_PARTSIZE=$(shell echo $$(($(CONFIG_TARGET_ROOTFS_PARTSIZE)*1024*1024)))
+endif

估计是CONFIG_TARGET_ROOTFS_PARTSIZE这个没有定义
增加下判断
