### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Karmylr** [coolsnowwolf/lede#10318]
执行 make menuconfig 之后出现“ERROR: please fix target/linux/silicon/Makefile - see logs/target/linux/silicon/dump.txt for details”.
logs/target/linux/silicon/dump.txt:
/home/conter/lede/include/kernel-version.mk:11: *** Missing kernel version/hash file for 5.19. Please create /home/conter/lede/include/kernel-5.19.  Stop.

**Comment by AXBNG** [comment]
也许可能大概........
https://github.com/coolsnowwolf/lede/commit/3c294bd503a88c03362f6234e658e6e65161b4f3

**Comment by 1054009064** [comment]
本来就还不能编译，只是换了一种报错方式罢了

**Comment by cerellean** [comment]
我是直接把target/linux/silicon/Makefile的直接改成6.0了就没报错了
