### ISSUE TITLE
您好！问一下能否给r4s添加edimax wifi6 usb3.0 1800m 无线网卡驱动吗？网卡芯片型号rtl8832au

### ISSUE THREAD

**Issue by yuanjinhua2019** [coolsnowwolf/lede#10326]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by aiamadeus** [comment]
不能，我们没有你说的网卡。
