### ISSUE TITLE
发现ssh 拒绝连接，web UI正常登录

### ISSUE THREAD

**Issue by yuhongwei380** [coolsnowwolf/lede#10332]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
ssh相关问题
Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：近期编译固件发现新版本的固件编译出来，我qm import 到pve上，发现op发现ssh 拒绝连接，web UI正常登录；ssh -vvv localhost 也是 拒绝连接；

### (2) 路由器型号和固件版本

A：X86版本；虚拟机，5.15.58

### (3) 详细日志

A：ssh连接，提示拒绝连接；

**Comment by zhangguanzhang** [comment]
你都有pve了，pve的console进去看看日志和系统日志不行吗，以及consol里ssh -vvv localhost试试

**Comment by yuhongwei380** [comment]
目前发现是xshell 无法ssh 连接到自编译新版本 的问题，用cmd 和 terminal可以ssh访问；case 先关了

**Comment by zhangguanzhang** [comment]
应该是ssh的密钥算法和op里的不匹配

**Comment by yuhongwei380** [comment]
害，我也不知道哪儿出问题了；新编了一个版本，发现又没法 cmd 和terminal访问了；感觉是网络层面的问题或者是ssh 这边的问题，之前遇到了centos8 ssh 无法ssh，是因为ipqos 影响到。我们是访问ipsec 对端的 op；

**Comment by zhangguanzhang** [comment]
你找个局域网的大型linux，或者你的pve，ssh -vvvv 看下调试信息

**Comment by yuhongwei380** [comment]
root@OpenWrt:~# ssh localhost
ssh: Connection to root@localhost:22 exited: Connect failed: Connection refused

**Comment by yuhongwei380** [comment]
大局域网内是可以ssh 的，跨ipsec 的访问就有问题了

**Comment by yuhongwei380** [comment]
我真的醉了，刚装好新OP那会，配置好网络等参数没法连，等我跟你回复完消息又可以连接了 ；

**Comment by zhangguanzhang** [comment]
你这是ipsec 的段冲突了吧。。。，你ssh的不是你的op

**Comment by yuhongwei380** [comment]
ispec 段没冲突的哈；我是用的同局域网的ssh 到这台15.X的OP上，-vvv打印信息；

**Comment by yuhongwei380** [comment]
这样子吗

**Comment by yuhongwei380** [comment]
![Uploading QQ图片20221031193517.png…]()

**Comment by yuhongwei380** [comment]
我把op的版本降级回我们今年22-3月编译的版本，直接本地就ssh上了

**Comment by yuhongwei380** [comment]
![image](https://user-images.githubusercontent.com/44333391/199144681-dd7b1f27-6a5a-4ba1-9269-87228ffbd6d2.png)

**Comment by zhangguanzhang** [comment]
🤔你用git 的ssh试试呢
```
ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa  xxx
```

**Comment by yuhongwei380** [comment]
![image](https://user-images.githubusercontent.com/44333391/199152341-e7321a06-69b0-4a0d-9c2a-a2e9e46478f8.png)

**Comment by yuhongwei380** [comment]
还是一样的

**Comment by zhangguanzhang** [comment]
```
ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -vvvv  xxx
```

**Comment by yuhongwei380** [comment]
![image](https://user-images.githubusercontent.com/44333391/199192616-4d5c19ce-8501-4017-9f19-a8906c1b0f13.png)
mu'

**Comment by zhangguanzhang** [comment]
🤔也就是说搞了个另类的qos吗

**Comment by zhangguanzhang** [comment]
🤔也就是说搞了个另类的qos吗

**Comment by yuhongwei380** [comment]
算是吧，你搜 IPQos  ssh 这种可能会更有相关信息；

**Comment by yuhongwei380** [comment]
我到dropbear 那个项目下提出这个问题了，作者表示后续会出一个选项，用来避免这样的情况。https://github.com/mkj/dropbear/issues/193

**Comment by zhangguanzhang** [comment]
👍很棒
