### ISSUE TITLE
v2ray的诡异现象.[用v2ray不能看安卓油管,网页看正常]

### ISSUE THREAD

**Issue by itwarlock** [coolsnowwolf/lede#1034]
v2ray ,电脑上看 web油管正常能看,  但是安卓机器(手机,电视都是)上油管app看不了.,看网页是正常的.
(同样的情况, 用 5-5-R 就一切正常)

**Comment by dongjuanyong** [comment]
安卓app上油管是通过quic协议，现在v2透明代理处理udp时有bug，看看v2的commit应该快要修复了

**Comment by itwarlock** [comment]
4.14貌似已经没有这个问题。
