### ISSUE TITLE
增加鲁班路由支持

### ISSUE THREAD

**Issue by muziling** [coolsnowwolf/lede#10361]
[luban.patch.zip](https://github.com/coolsnowwolf/lede/files/9929570/luban.patch.zip)

没有fork，所以就不pr了，这个patch打进去就能支持鲁班路由器了
uboot分区好像我去掉锁了

**Comment by 1582130940** [comment]
"0:lan" "1:lan" "2:lan" "3:lan" "4:wan" "6u@eth0" "5u@eth1"
这玩意也没五个口啊
https://github.com/coolsnowwolf/lede/pull/10365

**Comment by muziling** [comment]
官方固件开启SSH后，进去看了也是写了5个网口。

**Comment by muziling** [comment]
LEDE不接受此PR，那就看看PR给OP官方呗，但是LEDE改了mt7621的DTSI，不知道这个DTS能不能用。

**Comment by tckxjzc** [comment]
👍

**Comment by maxxwall** [comment]
感谢大佬
