### ISSUE TITLE
error: 您对下列文件的本地修改将被合并操作覆盖：         feeds.conf.default 请在合并前提交或贮藏您的修改。 正在终止

### ISSUE THREAD

**Issue by lvmingye523** [coolsnowwolf/lede#10360]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
搜索了，无
### (1) 具体问题
git pull时提示
A：error: 您对下列文件的本地修改将被合并操作覆盖：
        feeds.conf.default
请在合并前提交或贮藏您的修改。
正在终止

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AXBNG** [comment]
因为源码文件有改动..........这需要issue么  (￢_￢)

**Comment by lvmingye523** [comment]
> 因为源码文件有改动..........这需要issue么 (￢_￢)

那咋搞啊。。。

**Comment by AXBNG** [comment]
> > 因为源码文件有改动..........这需要issue么 (￢_￢)
> 
> 那咋搞啊。。。

你要是没什么重要的修改的话，直接全删掉重新clone；有重要修改就先备份一下

**Comment by 1054009064** [comment]
git restore feeds.conf.default

git pull

重新添加自定义源
