### ISSUE TITLE
新版本的固件用softether 连不上。

### ISSUE THREAD

**Issue by lvmingye523** [coolsnowwolf/lede#10371]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
没有
### (1) 具体问题

A：用了以前的旧固件能连上softeher。目前新版本的固件一样的设置，就连不上，一个插件都没开。

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by dlj390** [comment]
同样的问题，希望尽快解决。

**Comment by lvmingye523** [comment]
没有大佬修一下吗？设备r5s。固件版本OpenWrt R22.11.11 / LuCI Master (git-22.289.58375-2a380a3) 内核版本5.15.77。softeher vpn不能用好不方便啊
