### ISSUE TITLE
MT7621編譯錯誤

### ISSUE THREAD

**Issue by ifurther** [coolsnowwolf/lede#10370]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
bash: /home/user/lede/scripts/sercomm-kernel.sh: No such file or directory
### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Image Name:   MIPS OpenWrt Linux-5.4.222
Created:      Fri Nov  4 08:23:01 2022
Image Type:   MIPS Linux Kernel Image (lzma compressed)
Data Size:    2661677 Bytes = 2599.29 KiB = 2.54 MiB
Load Address: 81001000
Entry Point:  81001000
mv /home/user/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/beeline_smartbox-turbo-plus-kernel.bin.new /home/user/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/beeline_smartbox-turbo-plus-kernel.bin
/home/user/lede/scripts/sercomm-kernel.sh /home/user/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/beeline_smartbox-turbo-plus-kernel.bin 0x400100 0x1000000
bash: /home/user/lede/scripts/sercomm-kernel.sh: No such file or directory
make[5]: *** [Makefile:217: /home/user/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/beeline_smartbox-turbo-plus-kernel.bin] Error 127

**Comment by coolsnowwolf** [comment]
已修复
