### ISSUE TITLE
尝试编译OUI后报错，请教解决方法

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#10374]
全选OUI后编译报错，请教解决方法，谢谢，@zhaojh329 
具体日志如下：
Collected errors:
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-acl.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-backup.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-demo.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-dhcp-lease.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-home.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-layout.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-login.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-stations.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-system.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-upgrade.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-app-user.
 * check_data_file_clashes: Package oui-ui-core wants to install file /home/x86.6.0/lede/build_dir/target-x86_64_musl/root-x86/www/index.html
        But that file is already provided by package  * luci-base
 * opkg_install_cmd: Cannot install package oui-ui-core.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/x86.6.0/lede'
make[1]: *** [package/Makefile:111: /home/x86.6.0/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/x86.6.0/lede'
make: *** [/home/x86.6.0/lede/include/toplevel.mk:230: world] Error 2

**Comment by zhaojh329** [comment]
先取消 luci 相关的选项
