### ISSUE TITLE
该版本SSR是否支持xchacha20-ietf-poly1305加密方式

### ISSUE THREAD

**Issue by xiangp126** [coolsnowwolf/lede#1038]

**Comment by royalwei** [comment]
支持chacha20 ietf

**Comment by xiangp126** [comment]
@royalwei 
最近用的是aes-256-cfb，每过两周左右就感觉被墙了 感觉被识别了

chacha20 ietf 方式用的可以吗？

**Comment by royalwei** [comment]
确定可以用的

> @royalwei
> 最近用的是aes-256-cfb，每过两周左右就感觉被墙了 感觉被识别了
> 
> chacha20 ietf 方式用的可以吗？

**Comment by hcym** [comment]
没那么邪门吧？我有一个节点一直rc4-md5 
专门给7260的用，快一年也没事，也没感觉比chacha20-ietf快

**Comment by royalwei** [comment]
> 没那么邪门吧？我有一个节点一直rc4-md5
> 专门给7260的用，快一年也没事，也没感觉比chacha20-ietf快

7620也就那性能了，换7621，四线程的神秘力量

**Comment by pcteams** [comment]
chacha20-ietf-poly1305 属 AEAD 加密，AEAD 加密主要目的是防止对服务器的主动探测。
SSR 通过协议和混淆来预防主动探测，仅支持流加密，不支持 AEAD 加密(这一点从 SSR 服务商后端设置界面，没有 xchacha20-ietf-poly1305/chacha20-ietf-poly1305/aes-XXX-gcm 选项也可以看出来)。
