### ISSUE TITLE
X86 的Legacy目标文件编译失败,X86 64的没问题

### ISSUE THREAD

**Issue by liuhejun2020** [coolsnowwolf/lede#10390]
X86 的Legacy目标文件编译失败,X86 64的没问题,日志如下:

time: package/utils/bzip2/compile#0.40#0.13#0.52
make[3]: Entering directory '/home/deepin/文档/lede/package/system/ca-certificates'
mkdir -p /home/deepin/文档/lede/dl
SHELL= flock /home/deepin/文档/lede/tmp/.ca-certificates_20210119.tar.xz.flock -c ' /home/deepin/文档/lede/scripts/download.pl "/home/deepin/文档/lede/dl" "ca-certificates_20210119.tar.xz" "daa3afae563711c30a0586ddae4336e8e3974c2b627faaca404c4e0141b64665" "" "@DEBIAN/pool/main/c/ca-certificates" '
mkdir -p /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/deepin/文档/lede/tmp/.root-copy.flock -c 'cp -fpR /home/deepin/文档/lede/build_dir/target-x86_64_musl/ca-certificates-20210119/.pkgdir/ca-bundle/. /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.ca-bundle_installed
echo "ca-bundle" >> /home/deepin/文档/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install
mkdir -p /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/deepin/文档/lede/tmp/.root-copy.flock -c 'cp -fpR /home/deepin/文档/lede/build_dir/target-x86_64_musl/ca-certificates-20210119/.pkgdir/ca-certificates/. /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/deepin/文档/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.ca-certificates_installed
echo "ca-certificates" >> /home/deepin/文档/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install
make[3]: Leaving directory '/home/deepin/文档/lede/package/system/ca-certificates'
time: package/system/ca-certificates/compile#0.33#0.20#0.75
make[3]: Entering directory '/home/deepin/文档/lede/feeds/packages/lang/python/python3'
mkdir -p /home/deepin/文档/lede/dl
SHELL= flock /home/deepin/文档/lede/tmp/.Python-3.9.15.tar.xz.flock -c ' /home/deepin/文档/lede/scripts/download.pl "/home/deepin/文档/lede/dl" "Python-3.9.15.tar.xz" "12daff6809528d9f6154216950423c9e30f0e47336cb57c6aa0b4387dd5eb4b2" "" "https://www.python.org/ftp/python/3.9.15" '
rm -f /home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15/.built
touch /home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15/.built_check
CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15=Python-3.9.15 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15=Python-3.9.15 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DNDEBUG -fno-inline -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include " LDFLAGS="-L/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/deepin/文档/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15 -L/home/deepin/文档/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/deepin/文档/lede/staging_dir/target-x86_64_musl/lib" make -C /home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15=Python-3.9.15 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size READELF="x86_64-openwrt-linux-musl-readelf" CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" LD="x86_64-openwrt-linux-musl-gcc" ;
make[4]: Entering directory '/home/deepin/文档/lede/build_dir/target-x86_64_musl/Python-3.9.15'
Running code to generate profile data (this can take a while):

**Comment by aiamadeus** [comment]
不能用中文目录
