### ISSUE TITLE
Windows的WSL2环境，编译X86固件，一直报Broken pipe出错

### ISSUE THREAD

**Issue by Wilson-coder** [coolsnowwolf/lede#10391]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译出错，一开始做了make clean，一直到删除lede目录，重新git clone，用默认设置，都是同一个问题，屡试不爽。

### (2) 路由器型号和固件版本

A：X86 早上刚刚拉取的最新代码

### (3) 详细日志

A：make[3]: Entering directory '/home/wilson/lede/toolchain/kernel-headers'
rm -rf /home/wilson/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/linux-*
xzcat /home/wilson/lede/dl/linux-5.15.77.tar.xz | tar -C /home/wilson/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl -xf -
bash: line 1:   471 **Broken pipe**             xzcat /home/wilson/lede/dl/linux-5.15.77.tar.xz
       472 Killed                  | tar -C /home/wilson/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl -xf -
make[3]: *** [Makefile:116: /home/wilson/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/linux-5.15.77/.prepared] Error 137
make[3]: Leaving directory '/home/wilson/lede/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#1.37#12.15#12.00
    ERROR: toolchain/kernel-headers failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/kernel-headers/compile] Error 1
make[2]: Leaving directory '/home/wilson/lede'
make[1]: *** [toolchain/Makefile:93: /home/wilson/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/wilson/lede'
make: *** [/home/wilson/lede/include/toplevel.mk:230: world] Error 2

**Comment by ecrasy** [comment]
我1小时前刚actions编译完成
环境Ubuntu 22.04
刚烧写完这个固件上网

**Comment by Wilson-coder** [comment]
自己摸索出了原因，原来用的环境一直都是WSL1，可能是内核版本停留在了4.4，代码升级之后出现了兼容问题。后来把子系统改成了WSL2，已经可以正常编译了。这个话题就可以关掉了。
