### ISSUE TITLE
N1 和HK1那个包编译完了都过了正常，但就今天又更新了一下源码打包新的内核还是没有IP地址

### ISSUE THREAD

**Issue by liuhejun2020** [coolsnowwolf/lede#10412]
N1 和HK1那个包编译完了都过了正常，但就今天又更新了一下源码打包新的内核还是没有IP地址

**Comment by liuhejun2020** [comment]
都没有 /etc/config/network 这个文件

**Comment by binge8** [comment]
只有你出现了这个问题，我们都正常，找自己的原因吧

**Comment by liuhejun2020** [comment]
实验了几次，基本判断是floppy的打包软件与编译的固件不兼容，他的许多内核打包后都没有配置文件

binge8 ***@***.***>于2022年11月13日 周日11:53写道：
