### ISSUE TITLE
Failure to compile and error for AX6S modem

### ISSUE THREAD

**Issue by rootergod** [coolsnowwolf/lede#10417]
I get this error when compiling from the source

`openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073/mt7915/init.c:334:44: error: 'IEEE80211_MAX_AMPDU_BUF_HE' undeclared (first use in this function); did you mean 'IEEE80211_MAX_AMPDU_BUF_HT'?
  334 |         hw->max_rx_aggregation_subframes = IEEE80211_MAX_AMPDU_BUF_HE;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            IEEE80211_MAX_AMPDU_BUF_HT
/home/Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073/mt7915/init.c:334:44: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [scripts/Makefile.build:289: /home/Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073/mt7915/init.o] Error 1
make[5]: *** [scripts/Makefile.build:552: /home//Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073/mt7915] Error 2
make[4]: *** [Makefile:1900: /home//Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073] Error 2
make[4]: Leaving directory '/home//Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.78'
make[3]: *** [Makefile:509: /home/Downloads/DL1/openWRT/ax6s/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/mt76-2022-11-13-4bf26073/.built] Error 2
make[3]: Leaving directory '/home/Downloads/DL1/openWRT/ax6s/lede/package/kernel/mt76'
time: package/kernel/mt76/compile#2.12#0.80#2.91
    ERROR: package/kernel/mt76 failed to build.
make[2]: *** [package/Makefile:116: package/kernel/mt76/compile] Error 1
make[2]: Leaving directory '/home/Downloads/DL1/openWRT/ax6s/lede'
make[1]: *** [package/Makefile:110: /home/Downloads/DL1/openWRT/ax6s/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home//Downloads/DL1/openWRT/ax6s/lede'
make: *** [/home//Downloads/DL1/openWRT/ax6s/lede/include/toplevel.mk:230: world] Error 2
`

Is there a solution to this problem?

**Comment by 1054009064** [comment]
https://github.com/openwrt/openwrt/commit/6e9613844ca1ddea7e36abc44a513c89ef0598ff#commitcomment-84973691

The mac80211 used by the repo is based on 5.15.33 and less than 5.15.61, there (https://github.com/coolsnowwolf/lede/commit/1770fdd3196bf03b913cc0d73a421384c10da308) is no need to use macro definitions, just backport directly.

Like this: 
https://github.com/1054009064/lede/commit/8c24004ff73541ae6d9ab5b1faf64fd832456196
