### ISSUE TITLE
SSR不可用，显示连接错误，之前正常使用，之后一旦开SSR，谷歌连接性检测显示：连接错误，百度也显示连接错误，求助

### ISSUE THREAD

**Issue by excue0310** [coolsnowwolf/lede#10425]
因工作需要搞得软路由，不是很懂，之前一直正常，前段时间突然无法连接，重启也无用，重启后显示百度正常，一旦开了SSR就显示连接错误，换过节点也没有用。按照之前的回复说修改了网络-接口-LAN-基本设置，设置DNS和网关同一个地址，不要用其他国内的自定义DNS地址，无果。不确定是不是pdnsd的问题，有在网页端重启过。希望能得到帮助，有偿均可，谢谢。

**Comment by xiechangan123** [comment]
qq，微信，邮箱也不留一个，别人怎么帮。。。

**Comment by WYC-2020** [comment]
pdnsd 这玩意 不是早就被ssr 移除了，除了个人的修改版，用官网的都没这个功能了，你用那玩意肯定不行撒
