### ISSUE TITLE
x86 4.19内核exfat编译失败。

### ISSUE THREAD

**Issue by Azreulo** [coolsnowwolf/lede#1042]
make[4]: Entering directory `/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/linux-4.19.16'
  CC [M]  /home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.o
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c: In function 'exfat_fill_inode':
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:1927:27: error: passing argument 2 of 'exfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_fat2unix(sbi, &inode->i_mtime, &info.ModifyTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:150:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_fat2unix(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:1928:27: error: passing argument 2 of 'exfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_fat2unix(sbi, &inode->i_ctime, &info.CreateTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:150:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_fat2unix(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:1929:27: error: passing argument 2 of 'exfat_time_fat2unix' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_fat2unix(sbi, &inode->i_atime, &info.AccessTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:150:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_fat2unix(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c: In function 'exfat_write_inode':
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:2010:27: error: passing argument 2 of 'exfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_unix2fat(sbi, &inode->i_mtime, &info.ModifyTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:169:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_unix2fat(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:2011:27: error: passing argument 2 of 'exfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_unix2fat(sbi, &inode->i_ctime, &info.CreateTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:169:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_unix2fat(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:2012:27: error: passing argument 2 of 'exfat_time_unix2fat' from incompatible pointer type [-Werror=incompatible-pointer-types]
  exfat_time_unix2fat(sbi, &inode->i_atime, &info.AccessTimestamp);
                           ^
/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.c:169:6: note: expected 'struct timespec *' but argument is of type 'struct timespec64 *'
 void exfat_time_unix2fat(struct exfat_sb_info *sbi, struct timespec *ts,
      ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/exfat_super.o] Error 1
make[4]: *** [_module_/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5] Error 2
make[4]: Leaving directory `/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/linux-4.19.16'
make[3]: *** [/home/raphael/lean/build_dir/target-i386_pentium4_musl/linux-x86_generic/exfat-nofuse-2018-04-17-01c30ad5/.built] Error 2
make[3]: Leaving directory `/home/raphael/lean/feeds/packages/kernel/exfat-nofuse'
time: package/feeds/packages/exfat-nofuse/compile#1.79#0.92#2.56
make[2]: *** [package/feeds/packages/exfat-nofuse/compile] Error 2
make[2]: Leaving directory `/home/raphael/lean'
make[1]: *** [/home/raphael/lean/staging_dir/target-i386_pentium4_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/raphael/lean'
make: *** [world] 错误 2
----------------------------------------------------
貌似exfat不支持4.19内核？

**Comment by ope087** [comment]
去openwrt官方的packages源里找exfat的包,4.19需要补丁
