### ISSUE TITLE
ppp-mod-pppoe

### ISSUE THREAD

**Issue by sontjer** [coolsnowwolf/lede#10446]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

编译到这里就挂

### (2) 路由器型号和固件版本

x86

### (3) 详细日志

Configuring fdisk.
Configuring strongswan-ipsec.
Configuring strongswan-mod-stroke.
Configuring kmod-drm-i915.
Configuring kmod-amazon-ena.
Configuring kmod-e1000e.
Configuring autocore-x86.
Configuring luci-i18n-upnp-zh-cn.
Configuring kmod-button-hotplug.
Configuring kmod-dummy.
Configuring luci-app-docker.
Configuring kmod-igb.
Configuring strongswan-mod-gmp.
Configuring strongswan-minimal.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring luci-i18n-firewall-zh-cn.
Configuring luci-i18n-docker-zh-cn.
Configuring ppp-mod-pppoe.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by allgreenL** [comment]
也有同样的错误
