### ISSUE TITLE
不能安装依赖怎么办 

### ISSUE THREAD

**Issue by abcdefg1225** [coolsnowwolf/lede#10455]
Configuring luci-app-v2ray.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.79-1-5825865e598f06729fd62239dff65a73) for kmod-nf-reject6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-reject6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.79-1-5825865e598f06729fd62239dff65a73) for kmod-nf-log6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-log6 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.79-1-5825865e598f06729fd62239dff65a73) for kmod-nft-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.79-1-5825865e598f06729fd62239dff65a73) for kmod-nft-compat
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-compat found, but incompatible with the architectures configured
root@OpenWrt:~# opkg install  kmod-nf-reject6
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Unknown package 'kmod-nf-reject6'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.79-1-5825865e598f06729fd62239dff65a73) for kmod-nf-reject6
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-reject6 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-nf-reject6.
root@OpenWrt:~#

**Comment by aiamadeus** [comment]
自己编译
