### ISSUE TITLE
启用FullCone-NAT改为高性能模式重启后失效

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#10458]
拉取最新源码编译5.15内核x86固件，在防火墙中将启用FullCone-NAT改为高性能模式后turbo acc中全锥型 NAT提示未运行，重启后启用FullCone-NAT变为停用状态。
请教应该如何正确设置启用FullCone-NAT中的高性能模式@coolsnowwolf

**Comment by coolsnowwolf** [comment]
这个模式在目前开源代码中还不可用，只能选兼容模式
