### ISSUE TITLE
shadowsocks-libev 启用了新的插件v2ray-plugin

### ISSUE THREAD

**Issue by lyin888** [coolsnowwolf/lede#1045]
shadowsocks-libev 启用了新的插件https://github.com/shadowsocks/v2ray-plugin
现在又网友做出了适合openwrt的安装包https://github.com/chenhw2/openwrt-v2ray-plugin
大雕什么时候有时间了能否集成进固件里，谢谢！
@coolsnowwolf

**Comment by hcym** [comment]
疗效如何？现在姿势太多，路由器感觉ss方便也够用，kcp，udp，v2，quic等等等等用pc玩玩而已

**Comment by coolsnowwolf** [comment]
这个其实就是将 v2ray 的ss 部分单独拿出来，不是新的轮子

**Comment by lyin888** [comment]
> 这个其实就是将v2ray的ss部分单独拿出来，不是新的轮子

明白了，谢谢！
