### ISSUE TITLE
init.d文件细节问题导致ntpd启动失败

### ISSUE THREAD

**Issue by devioa** [coolsnowwolf/lede#10466]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
init.d文件细节问题导致ntpd启动失败，系统日志里会疯狂报：
`user.err : jail: ntpd is not an absolute path`
`user.err : jail: failed to load dependencies`
`daemon.info procd: Instance sysntpd::instance1 s in a crash loop 9 crashes, 0 seconds since last crash`
![2](https://user-images.githubusercontent.com/38558065/203026688-19140cd3-0919-4784-b36b-e8b2154c9bb2.png)

找到的解决办法：
报错说`ntpd`非绝对路径，那么用`which`带上绝对路径即可
把`/etc/init.d/sysntpd`里：
`PROG=ntpd`改为`PROG=$(which ntpd)`
`procd_add_jail ntpd ubus`改为`procd_add_jail $(which ntpd ubus)`
保存过后`restart`就能正常启动了：
![3](https://user-images.githubusercontent.com/38558065/203027030-8cf7e9f8-a688-4c15-92be-5682d63070a0.png)

### (2) 路由器型号和固件版本
`Linux OpenWrt 5.15.79 #0 SMP Sun Nov 20 14:14:41 2022 x86_64 GNU/Linux`

### (3) 详细日志
![1](https://user-images.githubusercontent.com/38558065/203025903-bd746412-c006-48db-8efc-0c8e28d465bc.png)

**Comment by kaiwater** [comment]
我今天遇到了类似的问题，正好有个同类环境参照

安装了opkg的ntpd 在/sbin/ntpd ,busybox的则是link ：/usr/sbin/ntpd -> ../../bin/busybox*

没有独立安装ntpd的系统是可以正常工作的，
ntpd组件不用busybox的，独立再装一次似乎会引来问题
