### ISSUE TITLE
强烈建议放回AR71xx 4.9内核的编译

### ISSUE THREAD

**Issue by royalwei** [coolsnowwolf/lede#1047]

**Comment by dzhuqi** [comment]
我备份有大屌的4.9.146的源码。感觉这个新的源码打开网页没有4.9的顺溜

**Comment by royalwei** [comment]
> 
> 
> 我备份有大屌的4.9.146的源码。感觉这个新的源码打开网页没有4.9的顺溜

您源码备份的哪个版本，后面的版本编译会失败
