### ISSUE TITLE
编译完openwrt后，ssrplus+不能科学上网

### ISSUE THREAD

**Issue by Mrli2022** [coolsnowwolf/lede#10494]
斐讯K3编译完openwrt后，ssrplus+能更新出节点信息，但是不能科学上网，luci-app里只选了ssrplus+，想问下是否还需要安装别的软件才能科学上网

**Comment by mitsukileung** [comment]
我也刚刚刷完机（IPQ807X），没有遇到这样的问题

**Comment by Mrli2022** [comment]
> 我也刚刚刷完机（IPQ807X），没有遇到这样的问题

我刷别人的固件就可以科学上网，自己编译了好几次，就是不行，不知道问题出在哪里

**Comment by l4326769** [comment]
选了luci下面还有include，把看着顺眼的include全加进去

**Comment by Mrli2022** [comment]
> 选了luci下面还有include，把看着顺眼的include全加进去

感谢指点，我再试试

**Comment by yuzhe1129** [comment]
我也是，昨晚编译K2P的固件，节点也是正常的，保存应用，ssr不运行，然后刷回来旧的版本就行了，

**Comment by yuzhe1129** [comment]
应该是有问题了要修复，不是编译的问题，我也是用不了

**Comment by Mrli2022** [comment]
> 应该是有问题了要修复，不是编译的问题，我也是用不了

我是第一次编译openwrt固件，一直以为是操作有问题导致不能科学上网

**Comment by FMJYY23** [comment]
重启防火墙试试你懂的
