### ISSUE TITLE
最新的 rockchip: 5.15: add missing kernel config全部炸了

### ISSUE THREAD

**Issue by Potterli20** [coolsnowwolf/lede#10491]
https://github.com/coolsnowwolf/lede/commit/1f9c2a3e1f4c79355fae15af5ca1799a09680264

https://user-images.githubusercontent.com/28734349/203795170-1ab21630-20d3-4e2b-a45f-24862cf67124.mp4

**Comment by gswangmd-gssi** [comment]
同样的问题

**Comment by aiamadeus** [comment]
。。make clean 然后重新编译
