### ISSUE TITLE
编译最后阶段，配置arpbind和guest-wifi的时候出错

### ISSUE THREAD

**Issue by imaomao** [coolsnowwolf/lede#1050]
编译最后阶段，配置arpbind和guest-wifi的时候出错。

cp -fpR /OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips /OS/lede/build_dir/target-mipsel_24kc_musl/root.orig-ramips
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
mkdir: cannot create directory '/etc/config': Permission denied
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 10: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 11: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 12: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 13: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 14: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 15: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 16: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 17: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 18: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 19: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 20: uci: command not found
/OS/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/guest-wifi: line 21: uci: command not found
./etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
./etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
mkdir: cannot create directory '/etc/config': Permission denied
./etc/init.d/guest-wifi: line 10: uci: command not found
./etc/init.d/guest-wifi: line 11: uci: command not found
./etc/init.d/guest-wifi: line 12: uci: command not found
./etc/init.d/guest-wifi: line 13: uci: command not found
./etc/init.d/guest-wifi: line 14: uci: command not found
./etc/init.d/guest-wifi: line 15: uci: command not found
./etc/init.d/guest-wifi: line 16: uci: command not found
./etc/init.d/guest-wifi: line 17: uci: command not found
./etc/init.d/guest-wifi: line 18: uci: command not found
./etc/init.d/guest-wifi: line 19: uci: command not found
./etc/init.d/guest-wifi: line 20: uci: command not found
./etc/init.d/guest-wifi: line 21: uci: command not found

**Comment by zxlhhyccc** [comment]
同样问题
