### ISSUE TITLE
新装的ubuntu 20.04 LTS 中 amule 编译错误

### ISSUE THREAD

**Issue by aaronbagot** [coolsnowwolf/lede#10514]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：编译环境 Debian GNU/Linux 11 (bullseye)  和 Ubuntu 20.04.5 LTS 都试了，但amule编译一直出错。
检查log发现是gettext不支持某个旧参数了。但是gettext早就升级到0.20以上了，以前编译也没错，不知道哪儿的问题。
复现错误的方法：新装的debian 或 Ubuntu 20.04 LTS :
sudo apt update -y
sudo apt full-upgrade -y
sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

git clone https://github.com/coolsnowwolf/lede
cd lede
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
选上luci-app-amule, 其它任何地方都不动
然后
make download -j17
make -j17
出错后 复现log: make package/amule/compile -j1 V=s 

### (2) 路由器型号和固件版本

A：X86-64-generic R22.10.1

### (3) 详细日志

A：make[2]: Entering directory '/home/user1/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/user1/lede/scripts/config'
make[1]: Entering directory '/home/user1/lede'
make[2]: Entering directory '/home/user1/lede/package/libs/toolchain'
echo "libc" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libatomic" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/user1/lede/package/libs/toolchain'
time: package/libs/toolchain/compile#0.09#0.01#0.10
make[2]: Entering directory '/home/user1/lede/package/libs/zlib'
echo "zlib" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/zlib.default.install
make[2]: Leaving directory '/home/user1/lede/package/libs/zlib'
time: package/libs/zlib/compile#0.09#0.00#0.09
make[2]: Entering directory '/home/user1/lede/package/devel/binutils'
echo "libbfd" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/binutils.default.install
make[2]: Leaving directory '/home/user1/lede/package/devel/binutils'
time: package/devel/binutils/compile#0.23#0.03#0.22
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/libpng'
echo "libpng" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/libpng.default.install
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/libpng'
time: package/feeds/packages/libpng/compile#0.10#0.00#0.09
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/freetype'
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/freetype'
time: package/feeds/packages/freetype/compile#0.08#0.02#0.09
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/libjpeg-turbo'
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/libjpeg-turbo'
time: package/feeds/packages/libjpeg-turbo/compile#0.09#0.01#0.10
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/libwebp'
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/libwebp'
time: package/feeds/packages/libwebp/compile#0.09#0.01#0.10
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/tiff'
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/tiff'
time: package/feeds/packages/tiff/compile#0.08#0.02#0.10
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/libgd'
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/libgd'
time: package/feeds/packages/libgd/default/compile#0.10#0.00#0.10
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/libupnp'
echo "libupnp" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/libupnp.default.install
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/libupnp'
time: package/feeds/packages/libupnp/compile#0.08#0.01#0.09
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/expat'
echo "libexpat" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/expat.default.install
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/expat'
time: package/feeds/packages/expat/compile#0.09#0.01#0.09
make[2]: Entering directory '/home/user1/lede/feeds/packages/libs/wxbase'
mkdir -p /home/user1/lede/dl
SHELL= flock /home/user1/lede/tmp/.wxGTK-2.8.12.tar.bz2.flock -c '      /home/user1/lede/scripts/download.pl "/home/user1/lede/dl" "wxGTK-2.8.12.tar.bz2" "08f81ab60647308058f6ce99712b14f8" "" "@SF/wxwindows"    '
echo "libwxbase" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/wxbase.default.install
make[2]: Leaving directory '/home/user1/lede/feeds/packages/libs/wxbase'
time: package/feeds/packages/wxbase/compile#0.14#0.06#0.18
make[2]: Entering directory '/home/user1/lede/package/lean/libcryptopp'
echo "libcryptopp" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/libcryptopp.default.install
make[2]: Leaving directory '/home/user1/lede/package/lean/libcryptopp'
time: package/lean/libcryptopp/compile#0.13#0.00#0.13
make[2]: Entering directory '/home/user1/lede/package/libs/ncurses'
make[2]: Leaving directory '/home/user1/lede/package/libs/ncurses'
time: package/libs/ncurses/host-compile#0.14#0.02#0.15
make[2]: Entering directory '/home/user1/lede/package/libs/ncurses'
echo "terminfo" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/ncurses.default.install
echo "libncurses" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/ncurses.default.install
make[2]: Leaving directory '/home/user1/lede/package/libs/ncurses'
time: package/libs/ncurses/compile#0.18#0.00#0.17
make[2]: Entering directory '/home/user1/lede/package/libs/readline'
echo "libreadline" >> /home/user1/lede/staging_dir/target-x86_64_musl/pkginfo/readline.default.install
make[2]: Leaving directory '/home/user1/lede/package/libs/readline'
time: package/libs/readline/compile#0.11#0.02#0.13
make[2]: Entering directory '/home/user1/lede/feeds/packages/net/amule'
rm -f /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/.configured_*
rm -f /home/user1/lede/staging_dir/target-x86_64_musl/stamp/.amule_installed
cd /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3 && sh ./autogen.sh
Setting up internationalization files.
Copying file intl/ChangeLog
Copying file intl/Makefile.in
Copying file intl/VERSION
Copying file intl/bindtextdom.c
Copying file intl/config.charset
Copying file intl/dcgettext.c
Copying file intl/dcigettext.c
Copying file intl/dcngettext.c
Copying file intl/dgettext.c
Copying file intl/dngettext.c
Copying file intl/eval-plural.h
Copying file intl/explodename.c
Copying file intl/finddomain.c
Copying file intl/gettext.c
Copying file intl/gettextP.h
Copying file intl/gmo.h
Copying file intl/hash-string.h
Copying file intl/intl-compat.c
Copying file intl/l10nflist.c
Copying file intl/libgnuintl.h
Copying file intl/loadinfo.h
Copying file intl/loadmsgcat.c
Copying file intl/localcharset.c
Copying file intl/locale.alias
Copying file intl/localealias.c
Copying file intl/localename.c
Copying file intl/ngettext.c
Copying file intl/os2compat.c
Copying file intl/os2compat.h
Copying file intl/osdep.c
Copying file intl/plural-exp.c
Copying file intl/plural-exp.h
Copying file intl/plural.c
Copying file intl/plural.y
Copying file intl/ref-add.sin
Copying file intl/ref-del.sin
Copying file intl/textdomain.c
Copying file mkinstalldirs
Copying file po/Makefile.in.in
autopoint does not honor dataroot variable, patching.
Running aclocal -I m4
ERROR: invalid first argument to AM_GNU_GETTEXT
ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.
ERROR: invalid first argument to AM_GNU_GETTEXT
ERROR: Use of AM_GNU_GETTEXT without [external] argument is no longer supported.
Running autoheader
Running autoconf
Creating pixmaps Makefile.am
Running automake --foreign -a -c -f
src/Makefile.am:72: warning: source file 'kademlia/utils/UInt128.cpp' is in a subdirectory,
src/Makefile.am:72: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/Makefile.am:97: warning: source file 'kademlia/kademlia/Entry.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/kademlia/Indexed.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/kademlia/SearchManager.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/routing/RoutingBin.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:123: warning: source file 'extern/wxWidgets/listctrl.cpp' is in a subdirectory,
src/Makefile.am:123: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Kademlia.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Prefs.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Search.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/UDPFirewallTester.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/net/KademliaUDPListener.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/net/PacketTracking.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/routing/Contact.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/routing/RoutingZone.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../CFile.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../SafeFile.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../OtherFunctions.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../Tag.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../kademlia/utils/UInt128.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/ExternalConnector.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/OtherFunctions.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/RLE.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/NetworkFunctions.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/LoggerConsole.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/UPnPBase.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
unittests/muleunit/Makefile.am:2: warning: source file '$(top_srcdir)/src/libs/common/MuleDebug.cpp' is in a subdirectory,
unittests/muleunit/Makefile.am:2: but option 'subdir-objects' is disabled
unittests/muleunit/Makefile.am:2: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/muleunit/Makefile.am:2: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/SafeFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/MemFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/Tag.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/kademlia/utils/UInt128.cpp' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/SafeFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/CFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/MemFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/kademlia/utils/UInt128.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/Tag.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:25: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:25: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:25: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:25: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/NetworkFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/LibSocket.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:43: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:43: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:43: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:43: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:28: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:28: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:28: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:28: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/TextFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
(cd /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/./; if [ -x ./configure ]; then find /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/ -name config.guess | xargs -r chmod u+w; find /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/ -name config.guess | xargs -r -n1 cp --remove-destination /home/user1/lede/scripts/config.guess; find /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/ -name config.sub | xargs -r chmod u+w; find /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/ -name config.sub | xargs -r -n1 cp --remove-destination /home/user1/lede/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3=aMule-2.3.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  " LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3=aMule-2.3.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro   " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3=aMule-2.3.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro   " CPPFLAGS="-I/home/user1/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/home/user1/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/home/user1/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include   " LDFLAGS="-L/home/user1/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/user1/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro   -liconv  "   ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  --disable-static --disable-rpath --with-gnu-ld --disable-ccache --disable-optimize --disable-profile --disable-monolithic --enable-amule-daemon --enable-amulecmd --enable-webserver --disable-amule-gui --disable-cas --disable-wxcas --disable-ed2k --disable-alc --disable-alcc --disable-fileview --disable-plasmamule --without-wxdebug --enable-dlp --enable-upnp --with-zlib="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --with-gdlib-prefix="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --with-libpng-prefix="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --with-wx-prefix="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --with-crypto-prefix="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --with-libiconv-prefix="" --with-libintl-prefix="" --with-libupnp-prefix="/home/user1/lede/staging_dir/target-x86_64_musl/usr" --without-x --disable-debug  ; fi; )
configure: WARNING: unrecognized options: --without-x
configure: loading site script /home/user1/lede/include/site/x86_64
checking for a BSD-compatible install... /home/user1/lede/staging_dir/host/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-openwrt-linux-strip... x86_64-openwrt-linux-musl-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-openwrt-linux-gnu
checking if this is a FreeBSD 4 or earlier system... no
checking whether the C++ compiler works... no
configure: error: in `/home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
make[2]: *** [Makefile:115: /home/user1/lede/build_dir/target-x86_64_musl/aMule-2.3.3/.configured_a17fb5ef857664f03cd0ce37cc5ea591] Error 77
make[2]: Leaving directory '/home/user1/lede/feeds/packages/net/amule'
time: package/feeds/packages/amule/compile#4.39#0.24#4.53
    ERROR: package/feeds/packages/amule failed to build.
make[1]: *** [package/Makefile:116: package/feeds/packages/amule/compile] Error 1
make[1]: Leaving directory '/home/user1/lede'
make: *** [/home/user1/lede/include/toplevel.mk:231: package/amule/compile] Error 2

**Comment by bootli** [comment]
一样

**Comment by zhg-em** [comment]
我也遇到同样的问题，希望能够修复！

**Comment by WYC-2020** [comment]
去掉liconv

**Comment by coolsnowwolf** [comment]
fixed

**Comment by aaronbagot** [comment]
多谢，问题解决了。
