### ISSUE TITLE
r8101驱动要更新配置文件

### ISSUE THREAD

**Issue by ligehhh** [coolsnowwolf/lede#10522]
SHELL= flock /home/lihh/cs/lede/tmp/.r8101-1.038.02.tar.bz2.flock -c '          /home/lihh/cs/lede/scripts/download.pl "/home/lihh/cs/lede/dl" "r8101-1.038.02.tar.bz2" "4141ebda97e277b5807a98b4090d7884d4463ac7a048676c72cb648ae4e8ae9e" "" "https://github.com/umarizulkifli/r8101/raw/main/"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://github.com/umarizulkifli/r8101/raw/main/r8101-1.038.02.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/r8101-1.038.02.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.cdn.openwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/r8101-1.038.02.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/r8101-1.038.02.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
make[2]: *** [Makefile:41: /home/lihh/cs/lede/dl/r8101-1.038.02.tar.bz2] Error 2
make[2]: Leaving directory '/home/lihh/cs/lede/package/lean/r8101'

作者删除了1.038版本

**Comment by 1582130940** [comment]
https://github.com/coolsnowwolf/lede/pull/10523
