### ISSUE TITLE
mt7621 云编译 选择auto samba 这一个月就没有成功过，什么原因

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#10527]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ *]* 没有类似的issue

### (1) 具体问题
？

A：芯片mt7621  mt7620 等，最近一个月，luci界面选择auto samba 云编译，，就没有成功过。需要修改什么地方吗？？
大家有遇到过吗？？

### (2) 路由器型号和固件版本

A：mt7621 mt7620   
  极路由4  优酷路由   等
### (3) 详细日志

A：

**Comment by vsvkhs** [comment]
应该是有编译报错了

**Comment by xiangfeigao** [comment]
那还用说，但排错，太难了，
