### ISSUE TITLE
在线编译出错，卡在 libiperf3

### ISSUE THREAD

**Issue by zzy19868** [coolsnowwolf/lede#10548]
反馈bug/问题模板，提建议请删除

### (2) 路由器型号和固件版本

X86

### (3) 详细日志

 make[3]: Entering directory '/workdir/openwrt/feeds/packages/net/iperf3'
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/iperf-nossl/iperf-3.12/.pkgdir/iperf3/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.iperf3_installed
mkdir -p /workdir/openwrt/bin/targets/x86/64/packages /workdir/openwrt/build_dir/target-x86_64_musl/iperf-nossl/iperf-3.12/ipkg-x86_64/libiperf3/CONTROL /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo
ifeq (nossl,ssl)
bash: -c: line 0: syntax error near unexpected token `nossl,ssl'
bash: -c: line 0: `ifeq (nossl,ssl)'
make[3]: *** [Makefile:113: /workdir/openwrt/bin/packages/x86_64/packages/libiperf3_3.12-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/iperf3'
time: package/feeds/packages/iperf3/nossl/compile#0.17#0.05#0.21
    ERROR: package/feeds/packages/iperf3 failed to build (build variant: nossl).
make[2]: *** [package/Makefile:116: package/feeds/packages/iperf3/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by ximiTech** [comment]
libiperf3 和 iperf3 都编不过

**Comment by wybb** [comment]
一样的问题

**Comment by WYC-2020** [comment]
看另外一个帖子我又说怎么解决
