### ISSUE TITLE
什么时候能加入360T7路由器

### ISSUE THREAD

**Issue by siren202101** [coolsnowwolf/lede#10542]
最近360T7涨价了，买的人应该挺多了这个什么时候能加入

**Comment by vsvkhs** [comment]
你捐一台就能加入了

**Comment by aiamadeus** [comment]
建议去问 mtk 什么时候 mt76 能支持 mt7981

**Comment by minlang112** [comment]
有无线闭源驱动的固件，这SOC的运营商OEM货无线都挺拉的好像

**Comment by padavanonly** [comment]
> 有无线闭源驱动的固件，这SOC的运营商OEM货无线都挺拉的好像

t7的无线是同价位最强的一档，只比tp卖300+的7981稍弱

**Comment by w22gb8** [comment]
360 t7无线信号不错的，5g比k2p都强。

**Comment by hcym** [comment]
hanwckf哪个应该可以的

**Comment by liwenjie119** [comment]
前一段入了这个，很期待能有，但是估计很难

**Comment by uparrows** [comment]
360T7 移植lede 23.3.3固件，有线无线内外网跑满千兆：https://www.right.com.cn/forum/thread-8282287-1-1.html
