### ISSUE TITLE
HWNAT zerotier 冲突

### ISSUE THREAD

**Issue by huangjackey1111** [coolsnowwolf/lede#1054]
在打开HWNAT 的时候不能通过 zerotier 设置的IP地址访问，关闭HWNAT 就没问题了。能否同时开启HWNAT 与 zerotier ？

**Comment by coolsnowwolf** [comment]
不能的。。。

**Comment by huangjackey1111** [comment]
> 不能的。。。

嗯，那只不能开HWNAT 了。
