### ISSUE TITLE
编译报错：bash: -c: line 1: syntax error near unexpected token `nossl,ssl'

### ISSUE THREAD

**Issue by devioa** [coolsnowwolf/lede#10551]
## 1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题
```
ifeq (nossl,ssl)
bash: -c: line 1: syntax error near unexpected token `nossl,ssl'
bash: -c: line 1: `ifeq (nossl,ssl)'
make[3]: *** [Makefile:113: /home/devioa/lede/bin/packages/x86_64/packages/libiperf3_3.12-1_x86_64.ipk] Error 2
```

### (2) 路由器型号和固件版本
`Linux OpenWrt 5.15.80 #0 SMP Tue Nov 29 14:40:22 2022 x86_64 GNU/Linux`

### (3) 详细日志
![1](https://user-images.githubusercontent.com/38558065/205589390-6a5a19d9-6358-4aec-85a6-e02bc8f27662.png)

**Comment by WYC-2020** [comment]
看关闭的帖子，按我那个方式修复
