### ISSUE TITLE
动态dnspod没有按预期方式运行

### ISSUE THREAD

**Issue by qyh214** [coolsnowwolf/lede#1055]
主机名 | R7800
-- | --
主机型号 | Netgear Nighthawk X4S R7800
架构 | ARMv7 Processor rev 0 (v7l)
固件版本 | OpenWrt  R9.1.1 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
内核版本 | 4.14.94

核心基于commit： d840ca199753c5e44d762ff3e68965c1cb61f100

设置了登录邮箱、密码、主域名、需要设置的子域名，但是并无常驻进程存在，似乎并未启动，且ip变动超过24小时也没有改变。

由于域名提供商用的是dnspod，期待大雕能有空提供对dnspod的支持，例如考虑使用现在的token方式

**Comment by xydche** [comment]
同样的问题，目前暂时用脚本实现了

**Comment by qyh214** [comment]
@xydche 你好，你使用的是哪个脚本呀，我目前正在测试https://github.com/kkkgo/dnspod-ddns-with-bashshell/

**Comment by wspzf** [comment]
DNSPod API 旧的“用户名 + 密码”的鉴权方式已下线，请升级为更安全的 API Token 的方式。另请确保调用接口url为 https://dnsapi.cn ，避免API操作不当影响使用
