### ISSUE TITLE
编译irqbalance提示cannot find -liconv

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#10565]
好像也有类似issue, 说是上游的问题，怎么解决呢

OpenWrt-libtool: link: x86_64-openwrt-linux-musl-gcc -I/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/include/glib-2.0 -I/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/lib/glib-2.0/include -I/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/irqbalance-1.8.0=irqbalance-1.8.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z -Wl,now -Wl,-z -Wl,relro -znow -zrelro -o irqbalance activate.o bitmap.o classify.o cputree.o irqbalance.o irqlist.o numa.o placement.o procinterrupts.o  -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib /home/builder/lede_x86/staging_dir/target-x86_64_musl/usr/lib/libglib-2.0.a -liconv -lm
/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
make[6]: *** [Makefile:561: irqbalance] Error 1
make[6]: Leaving directory '/home/builder/lede_x86/build_dir/target-x86_64_musl/irqbalance-1.8.0'
make[5]: *** [Makefile:648: all-recursive] Error 1
make[5]: Leaving directory '/home/builder/lede_x86/build_dir/target-x86_64_musl/irqbalance-1.8.0'
make[4]: *** [Makefile:457: all] Error 2
make[4]: Leaving directory '/home/builder/lede_x86/build_dir/target-x86_64_musl/irqbalance-1.8.0'
make[3]: *** [Makefile:83: /home/builder/lede_x86/build_dir/target-x86_64_musl/irqbalance-1.8.0/.built] Error 2
make[3]: Leaving directory '/home/builder/lede_x86/feeds/packages/utils/irqbalance'
time: package/feeds/packages/irqbalance/compile#0.25#0.24#0.45
    ERROR: package/feeds/packages/irqbalance failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/irqbalance/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2
builder@UBUNTU-LH-SZ:~/lede_x86$

**Comment by lovehackintosh** [comment]
libiconv已经被libiconv-full取代
把libiconv替换成libiconv-full试试

**Comment by GreatMichaelLee** [comment]
这里已经强制选择了，要怎么换？
![image](https://user-images.githubusercontent.com/20067401/206441121-2b2648c5-e42f-4347-981a-359de6801296.png)

**Comment by lovehackintosh** [comment]
执行
```bash
wget https://github.com/coolsnowwolf/packages/pull/621.patch -O ./feeds/packages/621.patch
git -C feeds/packages/ apply 621.patch
```

**Comment by GreatMichaelLee** [comment]
> 已修复，更新feeds即可

irqbalance还是不行，昨天那个patch是可以的，但这个621的merge还是过不了。我试试make clean再看看怎么样

**Comment by lovehackintosh** [comment]
已经合并到https://github.com/coolsnowwolf/packages/commit/24a50e6a71914cb9ce63f90306c6dd06f08b1edd ，不用应用那个patch
`./scripts/feeds update -a && ./scripts/feeds install -a `
再编译试试

**Comment by GreatMichaelLee** [comment]
> 已经合并到[coolsnowwolf/packages@24a50e6](https://github.com/coolsnowwolf/packages/commit/24a50e6a71914cb9ce63f90306c6dd06f08b1edd) ，不用应用那个patch `git -C feeds/packages/ clean -df && git -C feeds/packages/ checkout .` `./scripts/feeds update -a && ./scripts/feeds install -a ` 再编译试试

make clean之后OK了
