### ISSUE TITLE
海特实验室 HATLab

### ISSUE THREAD

**Issue by qgzqgz** [coolsnowwolf/lede#10577]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by qgzqgz** [comment]
海特实验室 HATLab mt7621A开发板编译好固件后，刷写到TF卡上不能识别不到TF卡系统，会直接跳到了板子上自带的系统，这个问题能解决吗？

**Comment by aiamadeus** [comment]
这机子是云支持的，建议去问客服。

**Comment by qgzqgz** [comment]
> 这机子是云支持的，建议去问客服。

我是用你们的源码编译才会出现这种情况，lede修改过几次，前几次修改编译出来能识别tf卡里系统，但是反复重启，最后一次修改后就连tf卡固件识别不到了，现在也没看见lede跟进这个问题
