### ISSUE TITLE
Linksys（WRT1900ACS V2）路由器设备编译world报错，无法继续

### ISSUE THREAD

**Issue by dodogao** [coolsnowwolf/lede#10589]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ √] 没有类似的issue

### (1) 具体问题

A：Linksys（WRT1900ACS V2）路由器设备编译world报错，无法继续

### (2) 路由器型号和固件版本

A：Linksys（WRT1900ACS V2）

### (3) 详细日志

A：gaoh@ubuntu:~/lede$ make V=s -j1
make[2]: Entering directory '/home/gaoh/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/gaoh/lede/scripts/config'
make[1]: Entering directory '/home/gaoh/lede'
make[2]: Entering directory '/home/gaoh/lede'
make[3]: Entering directory '/home/gaoh/lede/target/linux'
make[4]: Entering directory '/home/gaoh/lede/target/linux/mvebu'
rm -f /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/localversion
/home/gaoh/lede/scripts/kconfig.pl  + + /home/gaoh/lede/target/linux/generic/config-5.10 /home/gaoh/lede/target/linux/mvebu/config-5.10 /home/gaoh/lede/target/linux/mvebu/cortexa9/config-5.10 > /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/gaoh/lede/.config >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target
/home/gaoh/lede/scripts/package-metadata.pl kconfig /home/gaoh/lede/tmp/.packageinfo /home/gaoh/lede/.config 5.10 > /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.override
/home/gaoh/lede/scripts/kconfig.pl 'm+' '+' /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.target /dev/null /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.override > /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set
mv /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.old
grep -v INITRAMFS /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.old > /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set
rm -rf /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/modules
cmp -s /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.prev || { cp /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config; cp /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.prev; }
export MAKEFLAGS= ; [ -d /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/user_headers ] || make -C /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi=target-arm_cortex-a9+vfpv3-d16_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/gaoh/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 07:28:35 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/gaoh/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="arm-openwrt-linux-muslgnueabi-gcc"  INSTALL_HDR_PATH=/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/user_headers headers_install
grep '=[ym]' /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.config.set | LC_ALL=C sort | /home/gaoh/lede/staging_dir/host/bin/mkhash md5 > /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.vermagic
touch /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.configured
rm -f /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/vmlinux /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/System.map
make -C /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi=target-arm_cortex-a9+vfpv3-d16_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/gaoh/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 07:28:35 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/gaoh/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="arm-openwrt-linux-muslgnueabi-gcc" olddefconfig
make[5]: Entering directory '/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158'
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:486:warning: multi-line strings not supported
#
# No change to .config
#
make[5]: Leaving directory '/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158'
make -C /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi=target-arm_cortex-a9+vfpv3-d16_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/gaoh/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 07:28:35 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/gaoh/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="arm-openwrt-linux-muslgnueabi-gcc" zImage dtbs modules
make[5]: Entering directory '/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      net/core/dev.o
In file included from ./include/linux/linkage.h:7,
                 from ./arch/arm/include/asm/bug.h:5,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/thread_info.h:12,
                 from ./include/asm-generic/current.h:5,
                 from ./arch/arm/include/generated/asm/current.h:1,
                 from ./include/linux/sched.h:12,
                 from ./include/linux/uaccess.h:8,
                 from net/core/dev.c:71:
./include/linux/export.h:67:43: error: redefinition of '__ksymtab_dev_set_threaded'
   67 |         static const struct kernel_symbol __ksymtab_##sym               \
      |                                           ^~~~~~~~~~
./include/linux/export.h:114:9: note: in expansion of macro '__KSYMTAB_ENTRY'
  114 |         __KSYMTAB_ENTRY(sym, sec)
      |         ^~~~~~~~~~~~~~~
./include/linux/export.h:153:41: note: in expansion of macro '___EXPORT_SYMBOL'
  153 | #define __EXPORT_SYMBOL(sym, sec, ns)   ___EXPORT_SYMBOL(sym, sec, ns)
      |                                         ^~~~~~~~~~~~~~~~
./include/linux/export.h:161:41: note: in expansion of macro '__EXPORT_SYMBOL'
  161 | #define _EXPORT_SYMBOL(sym, sec)        __EXPORT_SYMBOL(sym, sec, "")
      |                                         ^~~~~~~~~~~~~~~
./include/linux/export.h:164:41: note: in expansion of macro '_EXPORT_SYMBOL'
  164 | #define EXPORT_SYMBOL(sym)              _EXPORT_SYMBOL(sym, "")
      |                                         ^~~~~~~~~~~~~~
net/core/dev.c:6907:1: note: in expansion of macro 'EXPORT_SYMBOL'
 6907 | EXPORT_SYMBOL(dev_set_threaded);
      | ^~~~~~~~~~~~~
./include/linux/export.h:67:43: note: previous definition of '__ksymtab_dev_set_threaded' with type 'const struct kernel_symbol'
   67 |         static const struct kernel_symbol __ksymtab_##sym               \
      |                                           ^~~~~~~~~~
./include/linux/export.h:114:9: note: in expansion of macro '__KSYMTAB_ENTRY'
  114 |         __KSYMTAB_ENTRY(sym, sec)
      |         ^~~~~~~~~~~~~~~
./include/linux/export.h:153:41: note: in expansion of macro '___EXPORT_SYMBOL'
  153 | #define __EXPORT_SYMBOL(sym, sec, ns)   ___EXPORT_SYMBOL(sym, sec, ns)
      |                                         ^~~~~~~~~~~~~~~~
./include/linux/export.h:161:41: note: in expansion of macro '__EXPORT_SYMBOL'
  161 | #define _EXPORT_SYMBOL(sym, sec)        __EXPORT_SYMBOL(sym, sec, "")
      |                                         ^~~~~~~~~~~~~~~
./include/linux/export.h:164:41: note: in expansion of macro '_EXPORT_SYMBOL'
  164 | #define EXPORT_SYMBOL(sym)              _EXPORT_SYMBOL(sym, "")
      |                                         ^~~~~~~~~~~~~~
net/core/dev.c:6863:1: note: in expansion of macro 'EXPORT_SYMBOL'
 6863 | EXPORT_SYMBOL(dev_set_threaded);
      | ^~~~~~~~~~~~~
make[7]: *** [scripts/Makefile.build:286: net/core/dev.o] Error 1
make[6]: *** [scripts/Makefile.build:503: net/core] Error 2
make[5]: *** [Makefile:1837: net] Error 2
make[5]: Leaving directory '/home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158'
make[4]: *** [Makefile:21: /home/gaoh/lede/build_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/linux-mvebu_cortexa9/linux-5.10.158/.modules] Error 2
make[4]: Leaving directory '/home/gaoh/lede/target/linux/mvebu'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/gaoh/lede/target/linux'
time: target/linux/compile#2.46#6.89#10.05
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/gaoh/lede'
make[1]: *** [target/Makefile:23: /home/gaoh/lede/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/gaoh/lede'
make: *** [/home/gaoh/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
这命算不出来，避免不了被关闭的命运，要解决问题，贴单线程日志
