### ISSUE TITLE
x86编译报错，希望能够解决一下

### ISSUE THREAD

**Issue by Licolnlee** [coolsnowwolf/lede#10584]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
拉取的最新代码，显示shortcutfecm和某个mod有冲突，想请教一下需要如何解决，谢谢。
A：

### (2) 路由器型号和固件版本
j4125
A：

### (3) 详细日志
![image](https://user-images.githubusercontent.com/32893599/206882245-a677ec6f-4d20-460b-8d13-00081fb2af92.png)

A：

**Comment by aiamadeus** [comment]
你自己选冲突了。
