### ISSUE TITLE
X86中编译 Multi Stream Daemon Lite找不到

### ISSUE THREAD

**Issue by Nothend** [coolsnowwolf/lede#10596]
X86编译。
大雕 是不是 把 Multi Stream Daemon Lite又去掉了？周末看到大雕新开发的功能，今天想加进去，结果编译的时候找不到。
默认config未设置状态：
![~)%@ ~UA 6I 3887U@}Z2 L](https://user-images.githubusercontent.com/73117056/206973244-b9e429c4-7e63-40f5-9262-09cb3e22105e.png)

luci中也没有

![image](https://user-images.githubusercontent.com/73117056/206973381-0754cf0c-a1eb-4d50-a0c6-986c16e8b54b.png)

需要添加什么package吗

**Comment by Nothend** [comment]
![@1H}P_9@{CZTF4I3(4MCWEK](https://user-images.githubusercontent.com/73117056/206974432-adf3065f-e98e-499f-bbe2-be41f6e27df6.png)

大雕是把这个功能 下架了吗？

**Comment by sdf8057** [comment]
没开源

**Comment by Nothend** [comment]
> 没开源

呃。。可惜了。 谢谢楼上！

**Comment by WYC-2020** [comment]
难道不是这个https://github.com/rozhuk-im/msd_lite.git

**Comment by Nothend** [comment]
> 难道不是这个https://github.com/rozhuk-im/msd_lite.git

牛逼啊 大佬，这个没有luci界面吧，大雕应该是适配了

**Comment by WYC-2020** [comment]
luci 随便参考一个写下就是了啊

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/207262155-1efc6a75-a814-43e3-a3ac-9c4ad6d83f39.png)

**Comment by WYC-2020** [comment]
@Nothend https://github.com/syb999/openwrt-19.07.1/tree/master/package/network/services/msd_lite 这里 luci 自己根据自己的需求修改即可，或者直接用

**Comment by Nothend** [comment]
> @Nothend https://github.com/syb999/openwrt-19.07.1/tree/master/package/network/services/msd_lite 这里 luci 自己根据自己的需求修改即可，或者直接用

谢谢大佬，我来试试，感谢！

**Comment by WYC-2020** [comment]
那个版本我看了 没有汉化，并且布局的话 感觉不是很合理，参考l大那个截图 我仿了一个
![image](https://user-images.githubusercontent.com/34025388/207634300-d34fd14f-c428-4278-9afd-92d8bd3e6a19.png)
![image](https://user-images.githubusercontent.com/34025388/207634332-b4fd6ab0-a5ee-4a73-94a5-1b2750ddb776.png)

**Comment by Nothend** [comment]
> 那个版本我看了 没有汉化，并且布局的话 感觉不是很合理，参考l大那个截图 我仿了一个 ![image](https://user-images.githubusercontent.com/34025388/207634300-d34fd14f-c428-4278-9afd-92d8bd3e6a19.png) ![image](https://user-images.githubusercontent.com/34025388/207634332-b4fd6ab0-a5ee-4a73-94a5-1b2750ddb776.png)

牛啊，大佬，目前你这个运行良好吗？怎么把你这个加入编译中呢？我看大雕的有人反应权限问题，启动不了
![%I%W@{GJUD7`_9XM9W_ 00A](https://user-images.githubusercontent.com/73117056/207743681-02779761-870f-465c-8101-d2781a01f0cf.png)
