### ISSUE TITLE
更新12月10日的dnsmasq补丁会导致ssr中的chinadns-ng异常

### ISSUE THREAD

**Issue by wybb** [coolsnowwolf/lede#10591]
更新补丁后，启用chinadns-ng将导致系统的dns功能不能正常解析，禁用chinadns或回滚到之前的dnsmasq版本都是正常的

**Comment by ZGNCZMY** [comment]
我是遇到了这个
Sun Dec 11 22:08:52 2022 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-adbyby.d: No such file or directory
Sun Dec 11 22:08:52 2022 daemon.crit dnsmasq[1]: FAILED to start up

**Comment by minlang112** [comment]
请移步https://github.com/fw876/helloworld提交

**Comment by starxu1971** [comment]
这个不是SSR的问题是dnsmasq更新后产生的问题且不是一个软件只要涉及DHCP或者防火墙操作就会出现问题。

**Comment by wybb** [comment]
> 请移步 https://github.com/fw876/helloworld 提交

是dnsmasq的问题，不是ssr的，ssr这期间代码并没有更新

**Comment by wybb** [comment]
root@OpenWrt:~# nslookup www.baidu.com
Server:         127.0.0.1
Address:        127.0.0.1:53

**_** server can't find www.baidu.com: REFUSED_**

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 180.101.49.13
Name:   www.a.shifen.com
Address: 180.101.49.14

**Comment by jxph1123** [comment]
不更新这个dnsmasq不就行了
