### ISSUE TITLE
最新拉取的源码编译报错，大佬们帮忙看一下

### ISSUE THREAD

**Issue by Z139724** [coolsnowwolf/lede#10595]
1反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
最新拉取的源码编译报错

### (2) 路由器型号和固件版本
N1
### (3) 详细日志
zhang@zhang:~/lede$ make -j1 V=s
make[2]: Entering directory '/home/zhang/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/zhang/lede/scripts/config'
make[1]: Entering directory '/home/zhang/lede'
make[2]: Entering directory '/home/zhang/lede'
make[3]: Entering directory '/home/zhang/lede/target/linux'
make[4]: Entering directory '/home/zhang/lede/target/linux/armvirt'
rm -f /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/localversion
/home/zhang/lede/scripts/kconfig.pl  + + /home/zhang/lede/target/linux/generic/config-5.10 /home/zhang/lede/target/linux/armvirt/config-5.10 /home/zhang/lede/target/linux/armvirt/64/config-5.10 > /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/zhang/lede/.config >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target
/home/zhang/lede/scripts/package-metadata.pl kconfig /home/zhang/lede/tmp/.packageinfo /home/zhang/lede/.config 5.10 > /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.override
/home/zhang/lede/scripts/kconfig.pl 'm+' '+' /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.target /dev/null /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.override > /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set
mv /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.old
grep -v INITRAMFS /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.old > /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set
rm -rf /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/modules
cmp -s /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.prev || { cp /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config; cp /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.prev; }
export MAKEFLAGS= ; [ -d /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/user_headers ] || make -C /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/zhang/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 16:22:04 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/zhang/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="aarch64-openwrt-linux-musl-gcc"  INSTALL_HDR_PATH=/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/user_headers headers_install
grep '=[ym]' /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.config.set | LC_ALL=C sort | /home/zhang/lede/staging_dir/host/bin/mkhash md5 > /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.vermagic
touch /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.configured
rm -f /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/vmlinux /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/System.map
make -C /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/zhang/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 16:22:04 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/zhang/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="aarch64-openwrt-linux-musl-gcc" olddefconfig
make[5]: Entering directory '/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158'
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:486:warning: multi-line strings not supported
.config:4448:warning: symbol value 'm' invalid for NF_CT_PROTO_GRE
#
# configuration written to .config
#
make[5]: Leaving directory '/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158'
make -C /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158 KCFLAGS="-fmacro-prefix-map=/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/zhang/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Dec 11 16:22:04 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/zhang/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.158 CC="aarch64-openwrt-linux-musl-gcc" Image modules
make[5]: Entering directory '/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158'
  SYNC    include/config/auto.conf.cmd
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:486:warning: multi-line strings not supported
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      init/do_mounts.o
  CC      init/init_task.o
  AR      init/built-in.a
  CC      arch/arm64/net/bpf_jit_comp.o
  AR      arch/arm64/net/built-in.a
  AR      arch/arm64/built-in.a
  CC      kernel/fork.o
  CC      kernel/exit.o
  CC      kernel/sysctl.o
  CC      kernel/pid.o
  CC      kernel/extable.o
  CC      kernel/nsproxy.o
  CC      kernel/cred.o
  CC      kernel/sched/core.o
  CC      kernel/sched/loadavg.o
  CC      kernel/sched/clock.o
  CC      kernel/sched/cputime.o
  CC      kernel/sched/idle.o
  CC      kernel/sched/fair.o
  CC      kernel/sched/rt.o
  CC      kernel/sched/deadline.o
  CC      kernel/sched/wait.o
  CC      kernel/sched/wait_bit.o
  CC      kernel/sched/swait.o
  CC      kernel/sched/completion.o
  CC      kernel/sched/cpupri.o
  CC      kernel/sched/cpudeadline.o
  CC      kernel/sched/topology.o
  CC      kernel/sched/stop_task.o
  CC      kernel/sched/pelt.o
  CC      kernel/sched/cpuacct.o
  CC      kernel/sched/membarrier.o
  AR      kernel/sched/built-in.a
  CC      kernel/kallsyms.o
  CC      kernel/cgroup/cgroup.o
  AR      kernel/cgroup/built-in.a
  CC      kernel/seccomp.o
  CC      kernel/bpf/core.o
  CC      kernel/bpf/syscall.o
  CC      kernel/bpf/verifier.o
  CC      kernel/bpf/inode.o
  CC      kernel/bpf/helpers.o
  CC      kernel/bpf/bpf_iter.o
  CC      kernel/bpf/map_iter.o
  CC      kernel/bpf/task_iter.o
  CC      kernel/bpf/prog_iter.o
  CC      kernel/bpf/hashtab.o
  CC      kernel/bpf/arraymap.o
  CC      kernel/bpf/lpm_trie.o
  CC      kernel/bpf/local_storage.o
  CC      kernel/bpf/ringbuf.o
  CC      kernel/bpf/trampoline.o
  CC      kernel/bpf/btf.o
  CC      kernel/bpf/dispatcher.o
  CC      kernel/bpf/devmap.o
  CC      kernel/bpf/cpumap.o
  CC      kernel/bpf/bpf_local_storage.o
  CC      kernel/bpf/offload.o
  CC      kernel/bpf/net_namespace.o
  CC      kernel/bpf/cgroup.o
  CC      kernel/bpf/reuseport_array.o
  CC      kernel/bpf/bpf_struct_ops.o
  AR      kernel/bpf/built-in.a
  AR      kernel/built-in.a
  CC      mm/memcontrol.o
  AR      mm/built-in.a
  CC      fs/namei.o
  CC      fs/select.o
  CC      fs/file.o
  CC      fs/fs_context.o
  CC      fs/eventpoll.o
  CC      fs/io_uring.o
  CC      fs/io-wq.o
  CC      fs/proc/namespaces.o
  CC      fs/proc/proc_net.o
  AR      fs/proc/built-in.a
  CC      fs/sysfs/mount.o
  AR      fs/sysfs/built-in.a
  CC      fs/9p/vfs_super.o
  CC      fs/9p/vfs_inode.o
  CC      fs/9p/vfs_inode_dotl.o
  CC      fs/9p/vfs_addr.o
  CC      fs/9p/vfs_file.o
  CC      fs/9p/vfs_dir.o
  CC      fs/9p/vfs_dentry.o
  AR      fs/9p/built-in.a
  AR      fs/built-in.a
  CC      ipc/mqueue.o
  AR      ipc/built-in.a
  CC      security/keys/keyring.o
  CC      security/keys/process_keys.o
  CC      security/keys/request_key.o
  AR      security/keys/built-in.a
  CC      security/commoncap.o
  AR      security/built-in.a
  CC      crypto/algapi.o
  CC      crypto/aead.o
  CC      crypto/geniv.o
  CC      crypto/skcipher.o
  CC      crypto/ahash.o
  CC      crypto/shash.o
  CC      crypto/algboss.o
  CC      crypto/rng.o
  AR      crypto/built-in.a
  CC [M]  crypto/acompress.o
  CC [M]  crypto/scompress.o
  LD [M]  crypto/crypto_acompress.o
  CC [M]  crypto/crypto_user_base.o
  LD [M]  crypto/crypto_user.o
  CC [M]  crypto/authenc.o
  CC [M]  crypto/authencesn.o
  CC [M]  crypto/af_alg.o
  CC [M]  crypto/algif_hash.o
  CC [M]  crypto/algif_skcipher.o
  CC [M]  crypto/algif_rng.o
  CC [M]  crypto/algif_aead.o
  CC      drivers/base/core.o
  CC      drivers/base/property.o
  AR      drivers/base/built-in.a
  CC      drivers/net/mii.o
  CC      drivers/net/Space.o
  CC      drivers/net/loopback.o
  CC      drivers/net/virtio_net.o
  CC      drivers/net/ethernet/smsc/smc91x.o
  AR      drivers/net/ethernet/smsc/built-in.a
  AR      drivers/net/ethernet/built-in.a
  CC      drivers/net/net_failover.o
  AR      drivers/net/built-in.a
  CC [M]  drivers/net/macvlan.o
  CC [M]  drivers/net/tun.o
  CC [M]  drivers/net/ppp/ppp_generic.o
  CC [M]  drivers/net/ppp/ppp_async.o
  CC [M]  drivers/net/ppp/pppox.o
  CC [M]  drivers/net/ppp/pppoe.o
  CC [M]  drivers/net/slip/slhc.o
  CC      drivers/leds/trigger/ledtrig-netdev.o
  AR      drivers/leds/trigger/built-in.a
  AR      drivers/leds/built-in.a
  CC      drivers/of/of_net.o
drivers/of/of_net.c: In function 'of_get_mac_address_mtd':
drivers/of/of_net.c:102:33: warning: unused variable 'pdev' [-Wunused-variable]
  102 |         struct platform_device *pdev = of_find_device_by_node(np);
      |                                 ^~~~
  AR      drivers/of/built-in.a
  AR      drivers/built-in.a
  CC      net/core/sock.o
  CC      net/core/request_sock.o
  CC      net/core/skbuff.o
  CC      net/core/datagram.o
  CC      net/core/stream.o
  CC      net/core/scm.o
  CC      net/core/gen_stats.o
  CC      net/core/gen_estimator.o
  CC      net/core/net_namespace.o
  CC      net/core/secure_seq.o
  CC      net/core/flow_dissector.o
  CC      net/core/sysctl_net_core.o
  CC      net/core/dev.o
/home/zhang/lede/tmp/ccqbZuZh.s: Assembler messages:
/home/zhang/lede/tmp/ccqbZuZh.s:1719: Error: symbol `__kstrtab_dev_set_threaded' is already defined
/home/zhang/lede/tmp/ccqbZuZh.s:1721: Error: symbol `__kstrtabns_dev_set_threaded' is already defined
/home/zhang/lede/tmp/ccqbZuZh.s:1727: Error: symbol `__ksymtab_dev_set_threaded' is already defined
make[7]: *** [scripts/Makefile.build:286: net/core/dev.o] Error 1
make[6]: *** [scripts/Makefile.build:503: net/core] Error 2
make[5]: *** [Makefile:1837: net] Error 2
make[5]: Leaving directory '/home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158'
make[4]: *** [Makefile:21: /home/zhang/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.158/.modules] Error 2
make[4]: Leaving directory '/home/zhang/lede/target/linux/armvirt'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/zhang/lede/target/linux'
time: target/linux/compile#92.11#9.47#101.61
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/zhang/lede'
make[1]: *** [target/Makefile:23: /home/zhang/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/zhang/lede'
make: *** [/home/zhang/lede/include/toplevel.mk:231：world] 错误 2

**Comment by Karmylr** [comment]
n1没有openwrt吧

**Comment by Z139724** [comment]
有的呀

**Comment by Z139724** [comment]
编译完成了，谢谢大佬
