### ISSUE TITLE
最新的源码编译后的mwan3,mwan3helper进行多线配置时dnsmasq报错。

### ISSUE THREAD

**Issue by nakes** [coolsnowwolf/lede#10614]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：最新的源码编译后的mwan3,mwan3helper进行多线配置dnsmasq报错。未配置mwan3时一切正常。
Wed Dec 14 18:57:25 2022 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-mwan3.d: No such file or directory
Wed Dec 14 18:57:25 2022 daemon.crit dnsmasq[1]: FAILED to start up
Wed Dec 14 18:57:25 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：
Wed Dec 14 18:57:25 2022 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-mwan3.d: No such file or directory
Wed Dec 14 18:57:25 2022 daemon.crit dnsmasq[1]: FAILED to start up
Wed Dec 14 18:57:25 2022 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

除这3行反复出现外没有其他异常日志

**Comment by coolsnowwolf** [comment]
fixed
