### ISSUE TITLE
samba4网络共享会自动有两个共享目录sda1 sdb1，删除两个目录重开机后又出现，有什么办法删除后不自动恢复？

### ISSUE THREAD

**Issue by joedai007** [coolsnowwolf/lede#10618]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：samba4网络共享会自动有两个共享目录sda1 sdb1，删除两个目录重开机后又出现，有什么办法删除后不自动恢复？

B：另外有时删除两个目录后，编辑模板内容变空，不知道怎么回事？

### (2) 路由器型号和固件版本

A：x86 OpenWrt  R22.12.1

### (3) 详细日志

A：

![QQ截图20221215103915](https://user-images.githubusercontent.com/103228836/207768303-2fcd04cf-0321-4d65-b2fd-7d0b7fa0f5f9.jpg)

**Comment by ecrasy** [comment]
不要编译autosamba
否则这玩意会自动共享你挂载的block分区

**Comment by joedai007** [comment]
> 不要编译autosamba
> 否则这玩意会自动共享你挂载的block分区
谢谢！是不是就算编译samba4,也取消autosamba这一项就可以了？

**Comment by starxu1971** [comment]
> > 不要编译 autosamba
> > 否则这玩意会自动共享你挂载的 block 分区
> 
> 谢谢！是不是就算编译 samba4, 也取消 autosamba 这一项就可以了？
没错取消autosanba, 然后选samba4就行。

**Comment by WYC-2020** [comment]
去掉那是下下策，最好的改法是
![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png)
这样

**Comment by joedai007** [comment]
> 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样

samba4没有自动共享这项啊

**Comment by WYC-2020** [comment]
> > 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样
> 
> samba4没有自动共享这项啊

自己修改 几句话的事

**Comment by joedai007** [comment]
> 软件包里面直接卸载autosamba

好的，我试试

**Comment by WYC-2020** [comment]
> > 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样
> 
> samba4没有自动共享这项啊

![image](https://user-images.githubusercontent.com/34025388/207831097-9262e0b9-b699-4d59-a9b2-5eabb1509804.png)
这样增加即可

**Comment by joedai007** [comment]
> > > 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样
> > 
> > 
> > samba4没有自动共享这项啊
> 
> ![image](https://user-images.githubusercontent.com/34025388/207831097-9262e0b9-b699-4d59-a9b2-5eabb1509804.png) 这样增加即可

谢谢！

**Comment by joedai007** [comment]
> > > > 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样
> > > 
> > > 
> > > samba4没有自动共享这项啊
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34025388/207831097-9262e0b9-b699-4d59-a9b2-5eabb1509804.png) 这样增加即可
> 
> 谢谢！
![image](https://user-images.githubusercontent.com/103228836/229270159-cc1d920d-9c8c-4a7f-936e-efc793cfabff.png)
大佬，添加的这项是英文的，怎么变成中文，谢谢！

**Comment by joedai007** [comment]
> > > > 去掉那是下下策，最好的改法是 ![image](https://user-images.githubusercontent.com/34025388/207822826-34750dde-3eca-42aa-a5bd-1821898e6323.png) 这样
> > > 
> > > 
> > > samba4没有自动共享这项啊
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34025388/207831097-9262e0b9-b699-4d59-a9b2-5eabb1509804.png) 这样增加即可
> 
> 谢谢！

![image](https://user-images.githubusercontent.com/103228836/229270241-9cf9ec4e-24bd-4250-bec9-f22618b41072.png)
大佬，添加的这项是英文的，怎么改成中文，谢谢！
