### ISSUE TITLE
最近几版，经再次测试，10月8日后内核和feeds更新后，mwan3工作不正常

### ISSUE THREAD

**Issue by wtfr-dot** [coolsnowwolf/lede#10624]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
最近几版（发现问题时是从5.15.82开始）因科学上网突然卡顿中断，排除线路原因后，发现是mwan3工作不正常造成的，我使用的是联通移动双宽带，所以使用了mwan3，但是没有使用多拨，除了单纯指定了几个内网设备走特定的网络外，包括科学上网都是走的均衡模式
### (1) 具体问题

A：当我使用新固件在1~2天后科学上网会突然卡顿中断，依次查找原因，进入状态--负载均衡，在接口界面上显示两个外网都在线，但是点详细信息后，界面就转圈卡死了，无法进入详细信息界面，这时到网络--负载均衡的设置界面去，点击保存，提示正在保存应用信息，然后一直转圈卡死，再进入系统--启动项，想重启mwan3，结果点击了启动项后界面转圈卡死，进不了启动项菜单，通过ssh进入后台用命令行重启mwan3，命令输入后卡死，无法重启mwan3，通过重启防火墙和科学上网软件清空ipset（我使用的passwall，这时界面显示是正常工作的）都无效，除了科学上网，国内上网没见异常，重启路由器后整个系统恢复正常。

### (2) 路由器型号和固件版本

A：x86自编译最新固件，主要从5.15.82后开始出现此问题

### (3) 详细日志

A：出现问题后系统日志没有错误信息，内核日志也没有错误信息

**Comment by fxxccp** [comment]
5.15.83的mwan3设置后保存时一直转圈，似乎自从dnsmasq更新到2.8.7后bug接二连三。

**Comment by cncqcyc** [comment]
5.15.82之前的版本也有2.87版dnsmasq，但使用没有什么问题，所以没感觉是dnsmasq的问题，一直以来的固件都有这样一个问题：就是第一次启动新固件，当我在防火墙的自定义设置里将53端口重定向注释后重启防火墙，这时mwan3的详细信息就没有负载均衡的具体信息，只有重启mwan3或者在负载均衡设置里直接保存应用一下才正常，我一直不把它当作bug，也是使用新固件时首先要做的步骤，之前也没有发现过mwan3保存转圈卡死的情况，也没有启动项都进不去的情况，因为国内dns通过了dnsmasq转发，但国内访问正常，所以dnsmasq工作正常，科学上网没有经过dnsmasq转发，但都经过mwan3的分流处理，科学上网软件也没有更新，设置没有变过，所以基本上确定是mwan3的问题，猜想是不是更新的某个组件造成与mwan3的兼容性问题，请大侠门帮忙分析一下

**Comment by WYC-2020** [comment]
进入死循环了

**Comment by cncqcyc** [comment]
看防火墙的版本号2022-02-17-4cd7d4f3-3，应该没有更新，mwan3版本号2.8.8-2，这个不知道是不是更新了，我用passwall清空防火墙规则也没法恢复正常，只有重启路由器才行

**Comment by nakes** [comment]
状态里面点负载均衡系统日志就被 Dump terminated刷屏了
Fri Dec 16 16:49:49 2022 daemon.err uhttpd[2106]: sh: write error: Broken pipe
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
Fri Dec 16 16:49:55 2022 daemon.err uhttpd[2106]: Dump terminated
不知道是不是同样的问题。这几个版本mwan3问题太大了

**Comment by cncqcyc** [comment]
我的没有任何错误信息，就是负载均衡详细信息打不开卡死，启动项打不开卡死，重启mwan3卡死，这时cpu和ram占用都正常，应该是mwan3跟某个组件冲突造成死循环了，我装的组件没有变过，并且没有什么更新，因此应该是底层更新造成了冲突

**Comment by cncqcyc** [comment]
刚才我重新编译了新固件，退回到5.15.81,commit：5052e70，feeds更新到最新状态，结构第一次启动重启防火墙后mwan3就卡死了，故障复现，dnsmaq是2.86，防火墙2.88，同时对比我正常工作的之前编译的5.15.81，luci版本为ba1f838，dnsmaq、mwan3和防火墙版本都一样，应该是luci更新的某个组件与mwan3冲突造成卡死

**Comment by cncqcyc** [comment]
刚刚新编译了一个固件，内核保持最新5.15.83，feeds的packages回退到10月8日，故障复现，看来应该是10月8日后内核和feeds更新造成的

**Comment by chiyu521** [comment]
你看看路由器里的系统 启动项  是不是也进不去 一直转圈

**Comment by chiyu521** [comment]
困扰我好多天了 我单线多播 启动项卡死 MWAN3卡死 找不到原因  楼主找到解决办法了吗? 要回滚到哪个版本是没有问题的?

**Comment by cncqcyc** [comment]
我描述里面有提到启动项也卡死进不去，目前没找到原因，我最近以最新的源码编译了一版，直接在源码就把防火墙自定义部分注释了，这样初次启动不用手动修改和重启防火墙，运行一天没问题，要持续观察

**Comment by chiyu521** [comment]
问题应该在firewall dnsmasq 和 mwan3 中的不兼容吧  个人感觉 是firewall和dnsmasq 冲突  导致DNS错误 所以mwan3不好用 最近的源码firewall和dnsmasq都有升级 所以问题不好找

**Comment by chiyu521** [comment]
有人测试没 最新的源码编译正常不?

**Comment by SouHong** [comment]
@chiyu521 把Turbo AAC关了，重启后再试试

**Comment by fxxccp** [comment]
> @chiyu521 把Turbo AAC关了，重启后再试试

与Turbo AAC无关，没编译Turbo AAC还是问题依旧。

**Comment by fxxccp** [comment]
> 有人测试没 最新的源码编译正常不?

问题依旧

**Comment by chiyu521** [comment]
还是用12.8的固件吧 问题没找到 刷完最新的 然后故障依旧  对了 我是单线多播 没编译IPV6

**Comment by imkenf** [comment]
我也是遇到这个问题，折腾了近期几个版本也是无解，内核试过5.10.148、5.15.85、6.1.6左右，我目前环境是3个wan口，而且开了mwan3以后只有1个wan口能nat，其他口能ping但也有部分连接不上nat端口的情况，只要是修改firewall、mwan3、Turbo ACC（多了个兼容和高性能模式）等保存就肯定是无限转圈圈，不懂楼上几位兄弟解决了吗？准备换openwrt官网版本试试了。印象中5.10.145之前貌似还是正常的，近期也没留意突然更新就崩了。

**Comment by cncqcyc** [comment]
我现在是编译阶段就把防火墙的dns转发注释掉，因为使用了预配置文件编译，所以启动后不需要操作防火墙、wan3等，现在一直这样用着，运行正常

**Comment by sjkhsl** [comment]
> 我现在是编译阶段就把防火墙的dns转发注释掉，因为使用了预配置文件编译，所以启动后不需要操作防火墙、wan3等，现在一直这样用着，运行正常

单线多拨，指定某些ip有指定接口，不行～无法正常工作～

**Comment by sjkhsl** [comment]
> 

feeds和packages怎么回退？我查资料，git reset --hard:可以回退，这个回退的是lede库吧？luci、packages什么的怎么回退啊？

**Comment by sjkhsl** [comment]
> 刚刚新编译了一个固件，内核保持最新5.15.83，feeds的packages回退到10月8日，故障复现，看来应该是10月8日后内核和feeds更新造成的

feeds和packages怎么回退？我查资料，git reset --hard:可以回退，这个回退的是lede库吧？luci、packages什么的库怎么回退啊？

**Comment by mozuipi** [comment]
> 我也是遇到这个问题，折腾了近期几个版本也是无解，内核试过5.10.148、5.15.85、6.1.6左右，我目前环境是3个wan口，而且开了mwan3以后只有1个wan口能nat，其他口能ping但也有部分连接不上nat端口的情况，只要是修改firewall、mwan3、Turbo ACC（多了个兼容和高性能模式）等保存就肯定是无限转圈圈，不懂楼上几位兄弟解决了吗？准备换openwrt官网版本试试了。印象中5.10.145之前貌似还是正常的，近期也没留意突然更新就崩了。

兄弟最后搞定了没？应该要回退到哪个时间段才正常？

**Comment by mozuipi** [comment]
> > 有人测试没 最新的源码编译正常不?
> 
> 问题依旧

还是如此，我内核换成5.10.165 还是不行！

**Comment by cncqcyc** [comment]
> 

在feeds.conf.default里把packages和luci两个源限定到需要的那个comment

**Comment by cncqcyc** [comment]
> > 刚刚新编译了一个固件，内核保持最新5.15.83，feeds的packages回退到10月8日，故障复现，看来应该是10月8日后内核和feeds更新造成的
> 
> feeds和packages怎么回退？我查资料，git reset --hard:可以回退，这个回退的是lede库吧？luci、packages什么的库怎么回退啊？

在feeds.conf.default里把packages和luci两个源限定到需要的那个comment

**Comment by mozuipi** [comment]
> > > 刚刚新编译了一个固件，内核保持最新5.15.83，feeds的packages回退到10月8日，故障复现，看来应该是10月8日后内核和feeds更新造成的
> > 
> > 
> > feeds和packages怎么回退？我查资料，git reset --hard:可以回退，这个回退的是lede库吧？luci、packages什么的库怎么回退啊？
> 
> 在feeds.conf.default里把packages和luci两个源限定到需要的那个comment

刚才把lede重新退回到10月8日之前的版本，luci、packages保持最新版。貌似没有出现保存一直转圈的情况！但是状态里面点负载均衡系统日志还是 Dump terminated刷屏。版本是5.15.77！本来还想luci、packages都退回到10月8日之前的版本。看样子是没必要了

**Comment by mozuipi** [comment]
[sync with upstream](https://github.com/coolsnowwolf/lede/commit/5a8163e07baa09440ca9304d00f5cc1cdb980d5b)
编译了数个版本测试，从上面的版本开始mwan3就开始卡死了！

**Comment by 1014982466** [comment]
+1，x86，最新编译，6.1.X内核，双WAN口。无网易云，无Turbo ACC，添加第二个WAN口进入mwan3会一直一直转圈

**Comment by imkenf** [comment]
> > 我也是遇到这个问题，折腾了近期几个版本也是无解，内核试过5.10.148、5.15.85、6.1.6左右，我目前环境是3个wan口，而且开了mwan3以后只有1个wan口能nat，其他口能ping但也有部分连接不上nat端口的情况，只要是修改firewall、mwan3、Turbo ACC（多了个兼容和高性能模式）等保存就肯定是无限转圈圈，不懂楼上几位兄弟解决了吗？准备换openwrt官网版本试试了。印象中5.10.145之前貌似还是正常的，近期也没留意突然更新就崩了。
> 
> 兄弟最后搞定了没？应该要回退到哪个时间段才正常？

我现在暂时换回openwrt官方22.03最新版本，全部正常了，包括以前那些bug，如pppoe，我三根外网线重启一个网口全部其他都重启的情况也没有了，连续连接6day都不带掉线的，就是切换成fw4防火墙麻烦点，有部分比较老的插件要稍微调整一下，不过还是能兼容fw3规则。lede目前版本对多wan支持不太好，感觉。

**Comment by mozuipi** [comment]
> > > 我也是遇到这个问题，折腾了近期几个版本也是无解，内核试过5.10.148、5.15.85、6.1.6左右，我目前环境是3个wan口，而且开了mwan3以后只有1个wan口能nat，其他口能ping但也有部分连接不上nat端口的情况，只要是修改firewall、mwan3、Turbo ACC（多了个兼容和高性能模式）等保存就肯定是无限转圈圈，不懂楼上几位兄弟解决了吗？准备换openwrt官网版本试试了。印象中5.10.145之前貌似还是正常的，近期也没留意突然更新就崩了。
> > 
> > 
> > 兄弟最后搞定了没？应该要回退到哪个时间段才正常？
> 
> 我现在暂时换回openwrt官方22.03最新版本，全部正常了，包括以前那些bug，如pppoe，我三根外网线重启一个网口全部其他都重启的情况也没有了，连续连接6day都不带掉线的，就是切换成fw4防火墙麻烦点，有部分比较老的插件要稍微调整一下，不过还是能兼容fw3规则。lede目前版本对多wan支持不太好，感觉。

我现在退回到大雕的[R22.11.13](https://github.com/coolsnowwolf/lede/releases/tag/20220716)版本，目前一切正常！

**Comment by chiyu521** [comment]
源码使用2022年12月8日以前的 就不会有问题  具体原因不明 就是启动项不能正常启动 不知道什么时候能修复

**Comment by longjindong** [comment]
请问有解决方案了吗？？

**Comment by longjindong** [comment]
大神能告诉我们怎么解决一下这个问题吗？？

**Comment by chenxuan5858** [comment]
一样问题，暂时无解，除了回退版本

**Comment by vvstar1982** [comment]
问题依然存在

**Comment by wtfr-dot** [comment]
我已经转向openwrt官方版本了，mwan3目前只支持iptables，如果使用nftables需要桥接，但这会与某些插件不兼容，我编译openwrt-22.03 iptables版使用起来没有任何问题，编译openwrt-23.05 nftables版会与passwall有兼容性问题。我估计目前的lede也是因为兼容性引起的。

**Comment by Linkcy97** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/72639933/0f519e3d-de73-4ea0-911c-76624902c23b)
问题依旧存在

**Comment by Linkcy97** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/72639933/9c223d82-2bb8-4f2b-8f67-3e51d5bfc3bc)
问题依旧存在
