### ISSUE TITLE
奇怪的现象/etc/config/firewall 一直打转

### ISSUE THREAD

**Issue by shenyz** [coolsnowwolf/lede#10623]
最近编译的内核82 83版本，只要修改了防火墙的通信规则，或者修改其它配置，保存应用，涉及到/etc/config/firewall的，极大概率下次再保存应用就会出现卡死现象，就是/etc/config/firewall 一直打转。每次配置过程都会卡在这一步 无法自动完成。系统--启动项就进不去，最后出现bad gateway。其它菜单正常进入。
辛苦大佬帮忙看看。

**Comment by firkerword** [comment]
有个情况，但是看日志又无异常，只是保存的时候一直转圈 ，实际上已经保存上了

**Comment by hxlls** [comment]
删除网易云解锁或者关闭网易云解锁就行了

**Comment by shenyz** [comment]
> 可能根目录被误挂成只读了



> 删除网易云解锁或者关闭网易云解锁试试

真的是它的锅

**Comment by WYC-2020** [comment]
还有这种骚操作

**Comment by WYC-2020** [comment]
稍微修复了一下，是这个解锁的脚本有问题，导致死循环了

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/208014019-0d9bb185-2a33-432f-a52e-5f68159aff3c.png)
照这样改下，然后重启防火墙看下解锁能解锁不

**Comment by coolsnowwolf** [comment]
fixed

**Comment by WYC-2020** [comment]
> ![image](https://user-images.githubusercontent.com/34025388/208014019-0d9bb185-2a33-432f-a52e-5f68159aff3c.png) 照这样改下，然后重启防火墙看下解锁能解锁不

忘记说了还有一个地方也要改
![image](https://user-images.githubusercontent.com/34025388/208022016-13659158-969a-485f-ab94-1ff89e7038b9.png)

**Comment by shenyz** [comment]
> fixed

刚刚编译了，不好意思，还是卡
![image](https://user-images.githubusercontent.com/2944410/208023857-12ed0d06-83fe-4341-89fd-c69142da7896.png)

**Comment by coolsnowwolf** [comment]
这个有可能是他的 https dns 的网址被墙了

**Comment by coolsnowwolf** [comment]
内核82 83版本 也不是这里的内核

**Comment by WYC-2020** [comment]
@shenyz 拿去用，亲测没任何问题
[luci-app-unblockmusic.tar.gz](https://github.com/coolsnowwolf/lede/files/10243308/luci-app-unblockmusic.tar.gz)

**Comment by shenyz** [comment]
> @shenyz 拿去用，亲测没任何问题 [luci-app-unblockmusic.tar.gz](https://github.com/coolsnowwolf/lede/files/10243308/luci-app-unblockmusic.tar.gz)

感谢

**Comment by shenyz** [comment]
> 内核82 83版本 也不是这里的内核

感谢
