### ISSUE TITLE
6.1内核自动挂载ntfs磁盘时，iocharset参数不对，导致无法访问中文目录

### ISSUE THREAD

**Issue by cuiyf5516** [coolsnowwolf/lede#10635]
![image](https://user-images.githubusercontent.com/48861298/208288416-e2ef2ef8-bcdc-4a6c-a705-97be17049c5a.png)

看着是自动挂载时文件系统直接识别为ntfs3，而不是ntfs，没通过mount.ntfs来进行挂载（iocharset会指定为utf-8）

看一下各位大佬有没有什么好的解决方法

_Originally posted by @cuiyf5516 in https://github.com/coolsnowwolf/lede/issues/10631#issuecomment-1356729744_

**Comment by tttt2001tttt** [comment]
同样遇到无法识别，已经换回旧固件，只能等修复吧

**Comment by mzl0408** [comment]
同样的问题，不只是6.1的问题，我用的5.15编译也是，应该是最近源码问题

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/208820307-db687c11-8e68-46f2-af3e-f2a5db2b629a.png)
我这边测试 没问题哈哈，不过我用的samba4

**Comment by mzl0408** [comment]
> ![image](https://user-images.githubusercontent.com/34025388/208820307-db687c11-8e68-46f2-af3e-f2a5db2b629a.png) 我这边测试 没问题哈哈，不过我用的samba4
是不是源码更新了，我自从前几天彻底删除源码重新编译后就一直不行

**Comment by cuiyf5516** [comment]
> ![image](https://user-images.githubusercontent.com/34025388/208820307-db687c11-8e68-46f2-af3e-f2a5db2b629a.png) 我这边测试 没问题哈哈，不过我用的samba4

挂载到某个iocharset后添加的文件肯定没有编码问题呀，像我这种被挂载到不同的iocharset后就因为编码问题不能正常显示文件名
![image](https://user-images.githubusercontent.com/48861298/209053198-44b15d11-6630-451d-8c65-4f885e71117e.png)

**Comment by cuiyf5516** [comment]
![image](https://user-images.githubusercontent.com/48861298/209101906-e4895695-bf51-4f40-bd7b-9022fad71066.png)
fstools的最新修改，不再需要实现mount.ntfs脚本的方式来自动挂载，这样脚本里手动指定的iocharset也不会生效。
![image](https://user-images.githubusercontent.com/48861298/209101735-7e896c62-58ff-4311-8684-0174b6ae8320.png)
如果需要就把fstools的最新修改回滚一下再编译，或者只能手动指定类型为ntfs重新mount了。

PS：或者考虑提供修改CONFIG_NLS_DEFAULT参数的选项？

**Comment by coolsnowwolf** [comment]
fixed 

https://github.com/coolsnowwolf/lede/commit/317d92dd3e0ebb07b5343ffc8ecd4db8fae36b2d

**Comment by WYC-2020** [comment]
> > ![image](https://user-images.githubusercontent.com/34025388/208820307-db687c11-8e68-46f2-af3e-f2a5db2b629a.png) 我这边测试 没问题哈哈，不过我用的samba4
> 
> 挂载到某个iocharset后添加的文件肯定没有编码问题呀，像我这种被挂载到不同的iocharset后就因为编码问题不能正常显示文件名 ![image](https://user-images.githubusercontent.com/48861298/209053198-44b15d11-6630-451d-8c65-4f885e71117e.png)

什么场景会用到一个磁盘挂载到不同编码上？现在编码那么多解决这个下一个说不定一样也会这样

**Comment by WYC-2020** [comment]
l大的修改也就是fat ntfs固定用utf8也还不是丢失了你所谓的多种编码

**Comment by cuiyf5516** [comment]
> l大的修改也就是fat ntfs固定用utf8也还不是丢失了你所谓的多种编码

觉得理解错我的问题了，这个问题是因为原来自动挂载因为有mount.ntfs中指定了utf-8所以一直没有问题，但是因为fstools最新版的修改不会再通过mount.ntfs挂载了，所以挂载时iocharset参数用的值是CONFIG_NLS_DEFAULT，所以会出现编码问题。

l大的修改就是为了达到跟以前一样的效果，自动挂载ntfs磁盘时默认的iocharset就是固定成utf-8。

**Comment by cuiyf5516** [comment]
> fixed
> 
> [317d92d](https://github.com/coolsnowwolf/lede/commit/317d92dd3e0ebb07b5343ffc8ecd4db8fae36b2d)

verified
