### ISSUE TITLE
请教大佬们，同步源码后编译的固件没了WIFI

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#10648]
IPQ807X_ax3600

4天前编译的固件没有问题，今天同步后再编译只有ALOT一个无线网卡，其它2个无线网卡消失了

**Comment by lovehackintosh** [comment]
发一下日志还有ssh进去`lsmod | grep ath`看一下mod

**Comment by coolsnowwolf** [comment]
目前官方的 6.1 无线驱动还没有支持 ath11k ahb
