### ISSUE TITLE
Action构建出错

### ISSUE THREAD

**Issue by feilongproject** [coolsnowwolf/lede#10643]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在通过`Action`进行构建时报错, 初步推断原因是`lib32gcc1`这个包在`Ubuntu`最新版被废弃, 经测试, 当`Ubuntu`版本为`20.04`时不会报错

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：[这里是本`repo`最近的一次`Action`](https://pipelines.actions.githubusercontent.com/serviceHosts/a4df3dfe-b80a-4a4d-99ef-d340ad5efa0c/_apis/pipelines/1/runs/1157/signedlogcontent/2?urlExpires=2022-12-19T05%3A24%3A31.6477928Z&urlSigningMethod=HMACV1&urlSignature=VBjBBJ8QDrC8Z0Zr3YDQeuXpHWMpGmM%2BZwOCJARbw28%3D)

**Comment by w311ang** [comment]
> A：[这里是本`repo`最近的一次`Action`](https://pipelines.actions.githubusercontent.com/serviceHosts/a4df3dfe-b80a-4a4d-99ef-d340ad5efa0c/_apis/pipelines/1/runs/1157/signedlogcontent/2?urlExpires=2022-12-19T05%3A24%3A31.6477928Z&urlSigningMethod=HMACV1&urlSignature=VBjBBJ8QDrC8Z0Zr3YDQeuXpHWMpGmM%2BZwOCJARbw28%3D)

过期了
