### ISSUE TITLE
刚才编译出错了请教一下什么原因

### ISSUE THREAD

**Issue by smdx** [coolsnowwolf/lede#10640]
刚才编译出错了请教一下什么原因，exit code 2.谢谢

![Screenshot-2022-12-19_023035](https://user-images.githubusercontent.com/9279217/208313562-eff2e6bb-7067-4c1b-9e70-15287f2fd3ae.jpg)

![Screenshot-2022-12-19_021555](https://user-images.githubusercontent.com/9279217/208313566-17dc0bb2-fbee-470c-b56f-90fb6a32e623.jpg)

**Comment by Ra2-IFV** [comment]
你選擇的有些軟件包互相沖突
kmod-fast-classifier <> kmod-shortcut-fe-cm

**Comment by starxu1971** [comment]
kmod-shortcut-fe-cm 如果事X86不要选这个

**Comment by smdx** [comment]
> 你選擇的有些軟件包互相沖突 kmod-fast-classifier <> kmod-shortcut-fe-cm



> kmod-shortcut-fe-cm 如果是X86不要选这个，这是高通芯片用的。

非常感谢，明白了。修改一下配置重新编译
