### ISSUE TITLE
在编译选项下打开firewall4后，编译出错，找不到kmod_nf_flow.ko模块

### ISSUE THREAD

**Issue by hicaoc** [coolsnowwolf/lede#10657]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：尝试编译 firewall4 ，使用nftables，编译出错， 没有正确编译出 nf_flow,ko模块，打包kmod-nft-offload出错
咨询下，lede是否全面支持 nftables， openwrt在21.03后切换到了nftables
lede如果还不支持，未来是否有计划切换到nftables? 

### (2) 路由器型号和固件版本

A：虚拟机编译

### (3) 详细日志

A：

**Comment by aiamadeus** [comment]
没有任何计划

**Comment by hicaoc** [comment]
谢谢
