### ISSUE TITLE
编译出错，小白看不懂

### ISSUE THREAD

**Issue by tangbutiansiji** [coolsnowwolf/lede#10665]
make[3]: Leaving directory '/home/tangda/lede/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/host-compile#141.23#15.95#1282.46
make[2]: Leaving directory '/home/tangda/lede'
make[1]: *** [package/Makefile:110: /home/tangda/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/tangda/lede'
make: *** [/home/tangda/lede/include/toplevel.mk:231: world] Error 2

**Comment by lovehackintosh** [comment]
日志没发全，看不出问题
