### ISSUE TITLE
最新版本硬盘挂载不上了

### ISSUE THREAD

**Issue by mzl0408** [coolsnowwolf/lede#10672]
上午看着网络共享中不显示中文文件夹的问题说fix了，然后马上删除源码重新编译，结果出来硬盘怎么弄也挂载不上，这个是还需要别的操作吗？

**Comment by cuiyf5516** [comment]
更新代码后再试一下吧，应该是没有默认编译ntfs3驱动导致的，我提的pr合过去了应该没有问题了。

**Comment by mzl0408** [comment]
> 更新代码后再试一下吧，应该是没有默认编译ntfs3驱动导致的，我提的pr合过去了应该没有问题了。

哦哦，马上试一遍
