### ISSUE TITLE
ath10K－ct在編譯X86，6.1內核時出錯

### ISSUE THREAD

**Issue by dbsjacky** [coolsnowwolf/lede#10674]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
編譯X86固件，內核6.1，“ath10K-ct”報錯
### (1) 具体问题

A：編譯6.1固件時“ath10K-ct”出錯

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：make[5]: *** [scripts/Makefile.build:250: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ath10k-ct-regular/ath10k-ct-2022-05-13-f808496f/ath10k-5.15/core.o] Error 1
make[4]: *** [Makefile:1992: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ath10k-ct-regular/ath10k-ct-2022-05-13-f808496f/ath10k-5.15] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.1'
make[3]: Leaving directory '/workdir/openwrt/package/kernel/ath10k-ct'
make[3]: *** [Makefile:125: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/ath10k-ct-regular/ath10k-ct-2022-05-13-f808496f/.built] Error 2
time: package/kernel/ath10k-ct/regular/compile#1.46#0.28#1.72
ERROR: package/kernel/ath10k-ct failed to build (build variant: regular).
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/Makefile:116: package/kernel/ath10k-ct/compile] Error 1
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by Ra2-IFV** [comment]
請給出完整的log
