### ISSUE TITLE
No rule to make target 'drivers/net/phy/motorcomm.o', needed by 'drivers/net/phy/built-in.a'.  Stop.

### ISSUE THREAD

**Issue by QYKing233** [coolsnowwolf/lede#10681]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
实体机编译OrangePI-R1-PLUS-LTS错误
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

OrangePI-R1-PLUS-LTS

### (3) 详细日志

make[8]: *** No rule to make target 'drivers/net/phy/motorcomm.o', needed by 'drivers/net/phy/built-in.a'.  Stop.
make[7]: *** [scripts/Makefile.build:503: drivers/net/phy] Error 2
make[6]: *** [scripts/Makefile.build:503: drivers/net] Error 2
make[5]: *** [Makefile:1837: drivers] Error 2
make[5]: Leaving directory '/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.161'
make[4]: *** [Makefile:26: /media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.161/.modules] Error 2
make[4]: Leaving directory '/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/target/linux'
time: target/linux/compile#705.50#68.47#859.32
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede'
make[1]: *** [target/Makefile:23: /media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede'
make: *** [/media/king/Datas/openwrt/orange-pi-r1-plus-lts/lede/include/toplevel.mk:231：world] 错误 2

**Comment by hong0980** [comment]
你是5.10内核我5.15内核替换用https://github.com/immortalwrt/immortalwrt/tree/master/target/linux/rockchip能启动网卡，默认我是不能启动。
