### ISSUE TITLE
FastRhino R68S OpenWrt R22.11.13 / LuCI Master版下面通过软件包下载的syncdial和mwan3好象有问题

### ISSUE THREAD

**Issue by tianjincat** [coolsnowwolf/lede#10699]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：目前在FastRhino R68S OpenWrt R22.11.13版下通过软件包安装的syncdial和mwan3，能正常单线双拨，vwan1和vwan2都能正常获取到pppoe IP地址。
但：
1、多线多拨的 "当前在线接口数量：为0"
2、mwan3负载均衡的接口状态为已禁用，详细信息处显示 interface vwan1 is error and tracking is active

在这种情况下，到启动项中重启mwan3服务后，mwan3负载均衡的接口状态显示为在线，能正常使用

### (2) 路由器型号和固件版本

路由器版本号为：FastRhino R68S OpenWrt R22.11.13
mwan3版本为2.10.13-1
luci-app-mwan3版本为git-22.259.47290-a14e49c-1
luci-app-syncdial版本号为2.0-25

### (3) 详细日志

A：

是否从软件包下载的syncdial与mwan3与此版本Openwrt不匹配导致？

**Comment by CYaNu** [comment]
mwan3helper?

**Comment by tianjincat** [comment]
> mwan3helper

mwan3helper也装了，但没有启用mwan3helper
