### ISSUE TITLE
刚刚刷了昨晚编译的固件 故障依旧

### ISSUE THREAD

**Issue by chiyu521** [coolsnowwolf/lede#10706]
X86  7200U 软路由

刷回12.8日的源码 一切正常 具体错误原因不明 

现象描述:
无错误相关日志 具体现象是貌似启动卡到什么地方死循环不继续走了 
点不开启动项 拨号成功但是无法上网 autocore SSR DOCKER 均没运行 
修改设置NAT和防火墙的时候 会提示正在保存 卡死  无法保存 

个人感觉是firewall和dnsmasq没启动

**Comment by long1215** [comment]
Turbo ACC 问题  关了就好了

**Comment by chiyu521** [comment]
Turbo ACC里 具体哪项??

**Comment by chiyu521** [comment]
20230102重新编译 还是死循环 没办法设置TURBOAC  之前关闭了SFE hw_flow sw_flow 故障依旧 怀疑是DNS缓存和DNSMASQ冲突
