### ISSUE TITLE
关于R7800 Lan速度不正常问题

### ISSUE THREAD

**Issue by takeru94** [coolsnowwolf/lede#1071]
最近多次尝试编译，发现无论大佬的版本还是官方master分支以及18.04分支都存在问题。
主要表现在rx及其不正常，单线程只有18mbps，多线程也不超过100mbps
但是tx很正常，跑的满1000mbps
然后挂载硬盘读写只有个位数，比ar9344还要慢，属于根本没法用级别了。
具体可以看这个：
https://www.right.com.cn/forum/thread-456121-1-1.html

除此以外lede17.01表现完全没有问题，官方18.04.2编译的固件也同样存在此问题。
玩ipq806x的比较少，有没有大佬帮忙解决一下

**Comment by takeru94** [comment]
买了第二台7800，同样存在一样问题，排除硬件问题，而且很奇怪，日志也看不到哪里有问题

**Comment by qyh214** [comment]
@takeru94 如果方便的话，可以把多余的一台7800借给大雕，进行专门适配调校下，具体你可以在群里和他聊聊

**Comment by takeru94** [comment]
近期已经修复了，lan能双向950M了

**Comment by lan542662** [comment]
大吊威武

takeru94 <notifications@github.com> 于2019年6月12日周三 下午12:41写道：
