### ISSUE TITLE
请教如何解决Intel i915集成显卡问题

### ISSUE THREAD

**Issue by gztingting** [coolsnowwolf/lede#10717]
最新的X86-64, 内核版本5.15.86 Luci版本R23.1.1
启动时非常慢，大概要一分多钟才启动结束，半年前编译的一个固件大概10~20秒就启动结束了
查看内核日志，发现是显卡驱动问题：
[    2.968175] i915 0000:00:02.0: [drm] Unknown revid 0x06
[    2.973470] i915 0000:00:02.0: [drm] Incompatible option enable_guc=3 - GuC submission is N/A
[    2.982378] i915 0000:00:02.0: [drm] couldn't get memory information
[    2.989521] i915 0000:00:02.0: Direct firmware load for i915/glk_dmc_ver1_04.bin failed with error -2
[    2.990370] i915 0000:00:02.0: Direct firmware load for i915/glk_guc_62.0.0.bin failed with error -2
[    2.998764] i915 0000:00:02.0: Falling back to sysfs fallback for: i915/glk_dmc_ver1_04.bin
[    3.007903] i915 0000:00:02.0: Falling back to sysfs fallback for: i915/glk_guc_62.0.0.bin
[   63.661026] i915 0000:00:02.0: [drm] GuC firmware i915/glk_guc_62.0.0.bin: fetch failed with error -110
[   63.661032] i915 0000:00:02.0: [drm] Failed to load DMC firmware i915/glk_dmc_ver1_04.bin. Disabling runtime power management.
[   63.661036] i915 0000:00:02.0: [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   63.670435] i915 0000:00:02.0: [drm] GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   63.710010] i915 0000:00:02.0: [drm] GuC is uninitialized
[   63.729066] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[   63.737512] ACPI: video: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
[   63.745384] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input1
[   63.755955] loop: module loaded

以上错误是修改了 target/linux/x86/config-5.15，添加以下代码导致的：
CONFIG_DUMMY_CONSOLE=y
CONFIG_64BIT=y
CONFIG_DRM=y
CONFIG_DRM_I915=y
CONFIG_DRM_I915_GVT=y
意图是把intel集成显卡驱动加上。

以上这个问题，如何解决?

另外还有一个硬盘分区错误，日志如下：
[   64.464252] GPT:Primary header thinks Alt. header is not at the end of the disk.
[   64.472066] GPT:3310112 != 62533295
[   64.475778] GPT:Alternate GPT header not at the end of the disk.
[   64.482134] GPT:3310112 != 62533295
[   64.485804] GPT: Use GNU Parted to correct GPT errors.
不知道如何解决.

以上，请教大神，非常感谢！

**Comment by aiamadeus** [comment]
选上 i915-firmware
