### ISSUE TITLE
【中国大陆IP段】更新失败！

### ISSUE THREAD

**Issue by forever2019** [coolsnowwolf/lede#10710]
## 1.关于你要提交的问题

使用23.1.1最新分支编译的，开启SSR之后，中国大陆IP段更新失败，关闭SSR后能更新成功。

![QQ截图20230102190406](https://user-images.githubusercontent.com/49540243/210223309-0ad59fdc-cd14-42a7-963a-c92d40932ee3.jpg)

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (2) 路由器型号和固件版本

![QQ截图20230102190835](https://user-images.githubusercontent.com/49540243/210223428-dbad898e-04e0-41e2-acb1-bc5de4bb0242.jpg)

### (3) 详细日志

A： 系统、内核，无日志输出

**Comment by chobitsos** [comment]
隔壁了解一下

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/210291228-2fc8fe2e-faea-45a9-b102-00f26a015438.png)
一切正常

**Comment by starxu1971** [comment]
高级设置里换个数据源

**Comment by suanfalalala** [comment]
也是同样问题1.14号刚刚编译完的
