### ISSUE TITLE
ipv6-helper 导致DHCP v4失效

### ISSUE THREAD

**Issue by ecrasy** [coolsnowwolf/lede#10725]
反馈bug/问题模板，提建议请删除

## 1. DHCP v4 失效
ipv6-helper 模块依赖的odhcpd-ipv6only和odhcpd冲突
如果选择ipv6-helper则无法选择odhcpd
但是odhcpd-ipv6only会使得DHCP v4失效
DHCP v4分配地址失败
DHCP v6则没有问题
以前这个模块是不会影响到DHCP v4
同样的config文件
最新源码则会出现DHCP v4无法分配地址的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：测试发现odhcpd-ipv6only会导致DHCP v4失效
但是odhcpd-ipv6only和odhcpd冲突
无法同时选择编译安装
只能通过手动强制将ipv6-helper 模块的依赖改为odhcpd
这时DHCP v4和v6版本均运作正常

### (2) 路由器型号和固件版本

A：路由器 x86
固件版本r0-fa691af8

### (3) 详细日志

A：无

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/210710990-d0e0c6b0-acb0-43a4-8d35-154d0b2d45b8.png)
![image](https://user-images.githubusercontent.com/34025388/210711039-898bb651-0e04-4a60-962e-332d6dc600b3.png)
测试可以选择啊，并且他们的Makefile也没配置冲突选项，不存在选择了一个不能选择另外一个的情况

**Comment by fishg** [comment]
> ![image](https://user-images.githubusercontent.com/34025388/210710990-d0e0c6b0-acb0-43a4-8d35-154d0b2d45b8.png)
> ![image](https://user-images.githubusercontent.com/34025388/210711039-898bb651-0e04-4a60-962e-332d6dc600b3.png)
> 测试可以选择啊，并且他们的Makefile也没配置冲突选项，不存在选择了一个不能选择另外一个的情况
实际这样同时选编译会报错：
Configuring ca-certificates.
Configuring unzip.
Configuring luci-app-openclash.
Configuring kmod-ipt-conntrack-extra.
Configuring perlbase-filehandle.
Configuring luci-lib-iCollected errors:
 * check_data_file_clashes: Package odhcpd wants to install file /mnt/sdb/code/r5slede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/odhcpd
	But that file is already provided by package  * odhcpd-ipv6only
 * check_data_file_clashes: Package odhcpd wants to install file /mnt/sdb/code/r5slede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/uci-defaults/15_odhcpd
	But that file is already provided by package  * odhcpd-ipv6only
 * check_data_file_clashes: Package odhcpd wants to install file /mnt/sdb/code/r5slede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/sbin/odhcpd
	But that file is already provided by package  * odhcpd-ipv6only
 * check_data_file_clashes: Package odhcpd wants to install file /mnt/sdb/code/r5slede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/sbin/odhcpd-update
	But that file is already provided by package  * odhcpd-ipv6only
 * opkg_install_cmd: Cannot install package odhcpd.
pkg.

另外有odhcpd 和 dnsmasq又是什么关系？

**Comment by WYC-2020** [comment]
那你这个明显就是编译出错嘛，一开始看你这个issue 感觉就是说不能选择，晕，问题要描述清楚

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/210743110-80056aa8-7d76-4424-be31-ca601a488daa.png)
 应该是这句话的问题，他们分属于不同包 结果最终安装的位置以及安装的程序一模一样 不冲突才有鬼

**Comment by WYC-2020** [comment]
通过查看这个项目的CMakefile  大体知道是什么意思了，提供了只编译ipv6选项，和ipv6+ipv4 也就是full版本，所以他们最终编译出来的程序都是一个程序，所以目前op这样写没问题，但是最好加入这两个包的互斥
![image](https://user-images.githubusercontent.com/34025388/210745570-78cf230a-aa53-443e-a014-b6ff7018d969.png)

**Comment by WYC-2020** [comment]
https://forum.openwrt.org/t/what-is-the-role-of-odhcpd-dnsmasq/121641/4 
看着 dnsmasq和odhcpd他们之间 本身就冲突，你选择
![image](https://user-images.githubusercontent.com/34025388/210751328-db487805-ff0d-42e5-a842-758ce165bf16.png)
这两个一样冲突，现在op模式是 dnsmasq管理ipv4 用odhcpd 管理ipv6，你可以试下 直接吧odhcpd关闭，开启dnsmasq的ipv6

**Comment by ggllioio** [comment]
现在版本默认勾选 Build with DHCPv6 support. 原来老版本是默认没有勾这个的。
想用ipv6，去掉这条，勾选ipv6 helper即可。
openwrt官方就是这么处理的，dnsmasq负责v4，odhcpd负责v6.

**Comment by ecrasy** [comment]
进一步测试发现
如果将所有odhcpd v4和v6的依赖都强制去掉
只保留dnsmasq
则DHCP v4和v6都可以正常运作
并且luci页面关于dhcp的设置可以正常生效。

测试还发现
如果强行将odhcpd-ipv6only依赖改为odhcpd
DHCP v4和v6可以正常运作
但是luci页面关于dhcp的很多设置不生效。

建议ipv6-helper去掉对odhcpd-ipv6only等的依赖
odhcpd-ipv6only会影响dnsmasq的dhcp v4功能
odhcpd模块和luci的dhcp页面设置也缺乏关联。

**Comment by Darks41** [comment]
不知道我的问题是不是也属于这一类，最近编译出来的固件刷上去之后打开网页都非常慢，有些网页直接是开不了的，还有一些手机APP比如支付宝也用不了，按照楼上大神的建议把Build with DHCPv6 support去掉还是不行，后面自己在LAN口的IPV6设置那里把DHCPv6 服务设为已禁用才解决

**Comment by SuperXiao666** [comment]
发现一个问题，编译时选择dnsmasq-full后，dhcp-server的IPV4服务会挂，要在软件包中卸载dnsmasq-full，只安装dnsmasq后dhcp-server(IPV4)才正常分发地址，在只有dnsmasq-full情况下，dhcp-server的IPV4服务使用一段时间后直接挂掉，而dhcp-server的IPV6服务正常分发。
