### ISSUE TITLE
MTU显示问题请教

### ISSUE THREAD

**Issue by yidianyipie** [coolsnowwolf/lede#10749]
Hi Team,

最近发现一个问题，就是在luci页面设置的MTU值跟ifconfig 出来的不一致
![image](https://user-images.githubusercontent.com/25215114/211206604-4cd4638a-ad9a-43cd-8c27-6332eb166cc6.png)

![image](https://user-images.githubusercontent.com/25215114/211206656-418b58a2-b4b4-4c7b-9210-f77c4d47cedc.png)

经过多次的实验，网页端设置的值，比ifconfig 出来的值要大8

请问这个是为何，或者有什么办法来处理？

BR

**Comment by a904055262** [comment]
pppoe拨号不得占用8个字节啊

**Comment by gztingting** [comment]
> pppoe拨号不得占用8个字节啊

这么说luci页面里不用修改默认的MTU值囖，openwrt网络设置那里有个MSS CLAMPING选项，打√即可，对吧。

**Comment by XinSSS** [comment]
想问下楼主你的是什么主题啊?

**Comment by yidianyipie** [comment]
> > pppoe拨号不得占用8个字节啊
> 
> 这么说luci页面里不用修改默认的MTU值囖，openwrt网络设置那里有个MSS CLAMPING选项，打√即可，对吧。

我记得之前好像不是这样的，先这么着吧，主要是最近发现wan口总是掉线，所以才想到会不会是mtu的问题


BR
Robin

**Comment by yidianyipie** [comment]
> 想问下楼主你的是什么主题啊?

引用了第三方库的一个
https://github.com/sypopo/luci-theme-argon-mc.git

**Comment by XinSSS** [comment]
> 引用了第三方库的一个 https://github.com/sypopo/luci-theme-argon-mc.git

好的，谢谢
