### ISSUE TITLE
断电启动后，国内ip无法访问

### ISSUE THREAD

**Issue by xaotag** [coolsnowwolf/lede#10752]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：断电重启后，国内ipv4网站无法访问。 ipv6网站和国外正常，dns解析正常，关闭`fw3 和 openclash`均无效
![image](https://user-images.githubusercontent.com/40427877/211459275-c8f8fee7-4ebc-450a-9afa-58e4a74e0809.png)
openwrt 内部正常
![image](https://user-images.githubusercontent.com/40427877/211459375-558665b2-a9cc-4c30-b8fb-a04802eabf5e.png)

### (2) 路由器型号和固件版本

A：x86 j4125 多口软路由 ，OpenWrt R22.12.1 / LuCI Master (git-22.354.59335-6a1c418)

**Comment by xaotag** [comment]
wireshark 抓包 ，百度得知是数据包超时，但由于水平有限不知道原因
![image](https://user-images.githubusercontent.com/40427877/211467024-e6a7f26c-3b95-4981-9a0b-ca5d6fc4d584.png)

**Comment by MageDelfador** [comment]
可能是NAT的问题
看看iptables -L -t nat

**Comment by xaotag** [comment]
@MageDelfador 我已经重刷固件，当时的情况是。 国内ipv4 无法访问，但是 ipv6和墙外没问题。

**Comment by xaotag** [comment]
老哥如果知道iptables 具体指令，我想在虚拟机中复现一下
