### ISSUE TITLE
为什么每分钟都会AAAA查询default.lan

### ISSUE THREAD

**Issue by FanxJK** [coolsnowwolf/lede#10755]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：每分钟都定时AAAA查询default.lan

### (2) 路由器型号和固件版本

A：x86_64 ESXi

### (3) 详细日志

<img width="900" alt="11111" src="https://user-images.githubusercontent.com/22773968/211553391-0e2a025a-c0b5-4269-866b-5c18905e3c96.png">

**Comment by yanxin152133** [comment]
局域网部署的吗
