### ISSUE TITLE
云编译kmod-mmc-spi报错

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/lede#10769]
### LOG
```log
make[3]: *** [modules/spi.mk:27: /workdir/openwrt/bin/targets/x86/64/packages/kmod-mmc-spi_6.1.6-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#2.80#0.26#3.05
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.
```
### actionlink
https://github.com/smallprogram/OpenWrtAction/actions/runs/3920876384/jobs/6702755007

**Comment by hgh188** [comment]
搞了3天 同样问题

**Comment by smallprogram** [comment]
> 搞了3天 同样问题

临时解决方案，取消一下试试,好像是在kernel  SPI Support里面

**Comment by ecrasy** [comment]
微软的Ubuntu镜像服务器down掉几天了
会不会和这个有关？
```
root@Ubuntu:~ # ping azure.archive.ubuntu.com -c 10
PING cloud-mirror-lb.westus.cloudapp.azure.com (40.81.13.82) 56(84) bytes of data.

--- cloud-mirror-lb.westus.cloudapp.azure.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9220ms
```
我是手动改了镜像才能编译：
sudo sed -i 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' /etc/apt/sources.list

**Comment by smallprogram** [comment]
> 微软的Ubuntu镜像服务器down掉几天了 会不会和这个有关？
> 
> ```
> root@Ubuntu:~ # ping azure.archive.ubuntu.com -c 10
> PING cloud-mirror-lb.westus.cloudapp.azure.com (40.81.13.82) 56(84) bytes of data.
> 
> --- cloud-mirror-lb.westus.cloudapp.azure.com ping statistics ---
> 10 packets transmitted, 0 received, 100% packet loss, time 9220ms
> ```
> 
> 我是手动改了镜像才能编译：
> 
> ```
> sudo sed -i 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' /etc/apt/sources.list
> ```

跟这个没关系，我是Github Action

**Comment by coolsnowwolf** [comment]
x64  不需要这个的

**Comment by smallprogram** [comment]
> x64 不需要这个的

感谢大雕

**Comment by WYC-2020** [comment]
这个是那个模块限制有问题，模块的脚本限制5.15，所以自然你6.1编译不过并且5.15 6.1 已经去除了CONFIG_OF限制，参考这个提交https://lore.kernel.org/all/20210419112459.25241-6-andriy.shevchenko@linux.intel.com/，所以是否能把5.4 5.10的也去掉这个限制哈哈
