### ISSUE TITLE
建议ssr plus+访问控制IP黑白名单添加支持域名

### ISSUE THREAD

**Issue by Lancenas** [coolsnowwolf/lede#1077]
建议ssr plus+访问控制IP黑白名单添加支持域名，方便外网ddns域名访问。

**Comment by abc9878** [comment]
同建议。否则大陆白名单模式会很麻烦。

**Comment by sqliuchang** [comment]
同求域名白名单

**Comment by lan542662** [comment]
没有白名单前可以把ip更新地址换成自己的地址，自己修改ip段。

sqliuchang <notifications@github.com> 于 2019年2月24日周日 16:06写道：

**Comment by xtwz** [comment]
同建议，白名单。 如果开启SSR 360和搜狗 走的SSR。

**Comment by huyi51462** [comment]
同求，IP黑白名单有时候不能满足需求，域名黑白名单可以稳定一些。

**Comment by Thanolee** [comment]
同求，QNAP更新DDNS时会走到代理，还有其他不太确定，支持域名会方便一些

**Comment by HuiGesGitHub** [comment]
同求 +1

**Comment by 404user** [comment]
大陆白名单 苹果的服务器都连不上，502错误了。
