### ISSUE TITLE
AMD GX-415GA 6.1内核 无限重启

### ISSUE THREAD

**Issue by yumaoss** [coolsnowwolf/lede#10772]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

5.15内核没有问题，今天编译完成的最新内核6.16刷入U盘无限重启

### (2) 路由器型号和固件版本

AMD GX-415GA SOC with Radeon(tm) HD Graphics x 4C 4T

### (3) 详细日志

只能发个不完整的截图了
到 drm amdgpu kernel modesetting enabled 就重启了

![捕获](https://user-images.githubusercontent.com/58129947/212556142-1072e136-5819-409a-900d-bb9bccce32ad.PNG)

**Comment by WYC-2020** [comment]
那就别编译这个gpu 试下撒

**Comment by yumaoss** [comment]
> 那就别编译这个gpu 试下撒

感谢，编译的时候 不选择它，可以开机使用了
