### ISSUE TITLE
msd_lite看电视卡成PPT，但udpxy没有问题

### ISSUE THREAD

**Issue by MageDelfador** [coolsnowwolf/lede#10778]
我试了下，关闭udpxy，打开msd_lite，电视和电脑上的VLC播放的时候画面和声音全都卡成PPT，但能持续播放，msd_lite没有异常的日志。换回udpxy一切正常。

大家都没遇到这个问题吗？

msd_lite我用的默认配置参数
https://github.com/rozhuk-im/msd_lite/blob/master/conf/msd_lite.conf
只改了下那个ifname,改成pppoe-IPTV
后来尝试改了其他参数，但不起任何作用。

**Comment by moonerick** [comment]
在5.15下面没有任何问题，6.1我测试了一会也没任何问题，但6.x后我的adguardhome出问题了

**Comment by MageDelfador** [comment]
研究了一下，是msd_lite的bug，刚刚提交了PR
https://github.com/rozhuk-im/msd_lite/pull/5
