### ISSUE TITLE
能否为shadowsockr plus+ 加入原版协议支持？

### ISSUE THREAD

**Issue by KangKai1982** [coolsnowwolf/lede#1078]
如题
鉴于ssr已不再更新，能否为shadowsocksr plus+插件加入原版ss以及相应的chacha20-itef-poly1305以及obfs支持？

谢谢

**Comment by sqliuchang** [comment]
编译时候在ssr plus中要选中include shadowsocks new version

**Comment by KangKai1982** [comment]
谢谢，我看看

**Comment by tufu9441** [comment]
即使选择了shadowsocks new version，也没有找到有能填写obfs参数的地方，请问是没有集成还是我自己没有安装完全？
