### ISSUE TITLE
kmod-igb-intel编译始终出错，已经禁用kmod-igb选项

### ISSUE THREAD

**Issue by SoPudge** [coolsnowwolf/lede#10789]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
kmod-igb-intel编译始终出错，已经禁用kmod-igb选项

kmod-igb-intel编译始终出错，已经禁用kmod-igb选项，报错节选如下
In function 'igb_alloc_q_vector':
/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.c:1144:9: error: too many arguments to function 'netif_napi_add'

### (2) 路由器型号和固件版本

A：

x86，内核5.15

### (3) 详细日志

A：

make[3]: Leaving directory '/workdir/openwrt/package/lean/autosamba'
time: package/lean/autosamba/compile#0.13#0.03#0.16
make[3]: Entering directory '/workdir/openwrt/package/lean/ddns-scripts_aliyun'
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/ddns-scripts_aliyun-1.0.3/.pkgdir/ddns-scripts_aliyun/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.ddns-scripts_aliyun_installed
echo "ddns-scripts_aliyun" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/ddns-scripts_aliyun.default.install
make[3]: Leaving directory '/workdir/openwrt/package/lean/ddns-scripts_aliyun'
time: package/lean/ddns-scripts_aliyun/compile#0.13#0.03#0.17
make[3]: Entering directory '/workdir/openwrt/package/lean/ddns-scripts_dnspod'
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/ddns-scripts_dnspod-1.0.2/.pkgdir/ddns-scripts_dnspod/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.ddns-scripts_dnspod_installed
echo "ddns-scripts_dnspod" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/ddns-scripts_dnspod.default.install
make[3]: Leaving directory '/workdir/openwrt/package/lean/ddns-scripts_dnspod'
time: package/lean/ddns-scripts_dnspod/compile#0.15#0.03#0.18
make[3]: Entering directory '/workdir/openwrt/package/lean/default-settings'
mkdir -p /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/default-settings-2/.pkgdir/default-settings/. /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.default-settings_installed
echo "default-settings" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/default-settings.default.install
make[3]: Leaving directory '/workdir/openwrt/package/lean/default-settings'
time: package/lean/default-settings/compile#0.13#0.03#0.16
make[3]: Entering directory '/workdir/openwrt/package/lean/igb-intel'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.igb-5.10.2.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "igb-5.10.2.tar.gz" "6ef2c26c18acb898d693040b56b27316" "" "http://downloads.sourceforge.net/project/e1000/igb%20stable/5.10.2/"    '
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/.built_check
make -C /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.1.7 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl=target-x86_64_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-x86_64_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="x86_64-openwrt-linux-musl-" ARCH="x86" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Jan 19 06:03:33 2023" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/cryptodev-linux.symvers /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8125.symvers /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/fullconenat.symvers /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/button-hotplug.symvers /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8168.symvers /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/symvers/shortcut-fe.symvers" KERNELRELEASE=6.1.7 M=/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src modules
make[4]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.1.7'
  CC [M]  /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.o
/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.c: In function 'igb_alloc_q_vector':
/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.c:1144:9: error: too many arguments to function 'netif_napi_add'
 1144 |         netif_napi_add(adapter->netdev, &q_vector->napi,
      |         ^~~~~~~~~~~~~~
In file included from /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.c:9:
./include/linux/netdevice.h:2583:1: note: declared here
 2583 | netif_napi_add(struct net_device *dev, struct napi_struct *napi,
      | ^~~~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:250: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src/igb_main.o] Error 1
make[4]: *** [Makefile:1992: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/src] Error 2
make[3]: *** [Makefile:45: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/kmod-igb-intel-5.10.2/.built] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-6.1.7'
make[3]: Leaving directory '/workdir/openwrt/package/lean/igb-intel'
time: package/lean/igb-intel/compile#1.29#0.21#1.50
    ERROR: package/lean/igb-intel failed to build.
make[2]: *** [package/Makefile:116: package/lean/igb-intel/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by coolsnowwolf** [comment]
需要适配新的API。 现在看来这个驱动没优势，可以 drop 掉了
