### ISSUE TITLE
关闭ipv6支持

### ISSUE THREAD

**Issue by Just4lyl** [coolsnowwolf/lede#10782]
请问大佬们，为什么现在的Global build settings里已经找不到enable ipv6 support这个选项了？？ 导致编译出来的固件里出厂就带wan6,强迫症很不习惯。

**Comment by rockhome** [comment]
是哦，怎么解决了

**Comment by AX200** [comment]
没有这个选项，我都不会设置上网了

**Comment by 8680** [comment]
老哥解决了吗? 同强迫症😭

**Comment by Fyred** [comment]
Extra-packages->ipv6helper
行吗？

**Comment by 8680** [comment]
> Extra-packages->ipv6helper 行吗？

不行，默认就是没勾选的

**Comment by oxygen427** [comment]
谢谢 PT主机也需要这个选项

**Comment by 8680** [comment]
https://github.com/openwrt/openwrt/issues/11926#issuecomment-1415292282
此选项已停用，不再受支持。

**Comment by cejpo001** [comment]
所以是现在这个固件不支持 IPv6了吗？

**Comment by kousyougi** [comment]
在 config/Config-build.in 檔案裡面找

> 　　config IPV6
　　　　def_bool y

這一段

然後把 def_bool y 改成 def_bool n，改好之後再 make menuconfig。
目前用極精簡的config可以編譯，使用正常。
多加其他功能或是之後變動太大有可能會不能編譯成功。

如果是用actions編譯，把替換的指令寫進diy-part2.sh即可。

**Comment by oxygen427** [comment]
谢谢您
我试过了 确实可以

kousyougi ***@***.***> 于2023年8月11日周五 22:25写道：
