### ISSUE TITLE
建议更改国内首选代码源为mirrors.ustc.edu.cn

### ISSUE THREAD

**Issue by wwng2333** [coolsnowwolf/lede#10783]
阿里云半夜1点限速128KB/s，ustc则可以跑到10MB/s
![image](https://user-images.githubusercontent.com/17147265/213250645-6ff68228-78ff-430a-a39c-1bdd02f0a32b.png)
![image](https://user-images.githubusercontent.com/17147265/213250660-44f4ef9e-cdd2-46fa-95ac-7cd2c1b2b309.png)

**Comment by wwng2333** [comment]
pull/10784

**Comment by WYC-2020** [comment]
没必要换掉阿里云 ，完全可以吧这个作为第一个压入就行，阿里云放到第二，这样感觉更好
