### ISSUE TITLE
The cpu arch type of one-cloud S805 uses cortex-a7/neon-vfpv4 instead of cortex-a5/vfpv4

### ISSUE THREAD

**Issue by shawnchain** [coolsnowwolf/lede#10791]
https://github.com/coolsnowwolf/lede/blob/ae17e3b40df0f388f5e6dbfe07c5c1e769da0b9d/target/linux/meson/meson8b/target.mk#L12

Hello,
I would like to know why the cpu arch type of onecloud s805 is cortex-a5/vfpv4 and should it be run faster if we switch to cortex-a7/neon-vfpv4 ?

Cheers

**Comment by aiamadeus** [comment]
Because s805 is cortex-a5: https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/meson8b.dtsi#L23
