### ISSUE TITLE
虚拟机中把lede作为旁路DNS，可以去广告，但是$$不起作用

### ISSUE THREAD

**Issue by sevilx** [coolsnowwolf/lede#108]
主要还是想用去广告和$$的功能，在虚拟机中把lede作为二级路由，下面的客户端都可以有以上两种功能，但是把lede作为旁路DNS，客户端中把lede作为DNS服务器和网关；客户端只能去广告，却不能用$$.自己怀疑是DNS转发模式的问题，如能得到大雕的解决回复就好了，谢谢！

**Comment by coolsnowwolf** [comment]
必须的，不可能起作用的
