### ISSUE TITLE
日志出现lsblk: /dev/nvme0n11: not a block device

### ISSUE THREAD

**Issue by wangqn** [coolsnowwolf/lede#10807]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题
只要点开磁盘管理，日志就会出现：
daemon.err uhttpd[3167]: lsblk: /dev/nvme1n11: not a block device
daemon.err uhttpd[3167]: lsblk: /dev/nvme0n11: not a block device

### (2) 路由器型号和固件版本

CW56-58 最新版固件

### (3) 详细日志
Wed Jan 25 14:05:32 2023 daemon.err uhttpd[3167]: lsblk: /dev/nvme1n11: not a block device
Wed Jan 25 14:05:32 2023 daemon.err uhttpd[3167]: lsblk: /dev/nvme0n11: not a block device
Wed Jan 25 14:06:22 2023 daemon.err uhttpd[3167]: lsblk: /dev/nvme0n11: not a block device
Wed Jan 25 14:06:22 2023 daemon.err uhttpd[3167]: lsblk: /dev/nvme1n11: not a block device
<img width="314" alt="屏幕截图 2023-01-25 140745" src="https://user-images.githubusercontent.com/10090475/214492684-91518e9a-ef4a-45e6-a4a9-12587aaae1d0.png">

**Comment by coolsnowwolf** [comment]
lsblk 不识别非 block 的设备，忽略即可
