### ISSUE TITLE
编译时如何指定不使用国内的源，而使用默认国外的源？

### ISSUE THREAD

**Issue by falconwoods** [coolsnowwolf/lede#10800]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by lovehackintosh** [comment]
`wget https://github.com/openwrt/openwrt/raw/master/scripts/download.pl -O scripts/download.pl`

**Comment by embeddedlove** [comment]
> `wget https://github.com/openwrt/openwrt/raw/master/scripts/download.pl -O scripts/download.pl`

大神求更6.1.8

**Comment by lovehackintosh** [comment]
可以
