### ISSUE TITLE
最新版源码 Domywifi dw33d 无法编译出squashfs固件

### ISSUE THREAD

**Issue by geerda123** [coolsnowwolf/lede#1083]
如图所示，全部为默认参数，没有增加插件，无法编译出squashfs固件，只有一个root固件。
![sshot-1](https://user-images.githubusercontent.com/18500636/53342869-f5c16980-3949-11e9-91d8-5da8518ef27a.png)
![sshot-2](https://user-images.githubusercontent.com/18500636/53342878-f823c380-3949-11e9-97b7-88fa6cc2d618.png)

**Comment by coolsnowwolf** [comment]
内核大小超过限制 8KB 了，需要放弃 ZRAM 支持
