### ISSUE TITLE
make[3] -C package/lean/default-settings compile  卡住

### ISSUE THREAD

**Issue by deplives** [coolsnowwolf/lede#10841]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
最近一段时间，x86 平台。不管是 action 云编译还是本地编译都有概率卡在
make[3] -C package/lean/default-settings compile

具体表现为：
action 云编译
编译没有报错，日志走到
<img width="728" alt="20230201-Google Chrome-OpenWrt Compile Schedule · deplivesOpenWrt-CI@65d55c7-005520@2x" src="https://user-images.githubusercontent.com/53208952/215975706-d7fc567e-33f3-4576-abd5-388c0c40018c.png">
然后就一直不动了，最后 6 个小时后被自动取消

本地编译也是，编译到
make[3] -C package/lean/default-settings compile
就再没有日志输出了，一直卡住。最长我尝试过卡了十几个小时，手动终止编译后没有固件产生。

**Comment by WYC-2020** [comment]
贴了当没贴，难道编译的时候 就不知道加 V=s
