### ISSUE TITLE
Golang版本偏低

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#10857]
最新的Xray-core的编译需要Go1.20以上的编译环境，而feeds中的golang版本低于1.20，致反复编译无法通过。

可否百忙之中抽空升级一下golang版本，不胜感激。

@coolsnowwolf

**Comment by guhill1** [comment]
+1, 我也遇到相同问题，麻烦更新一下吧，急需

**Comment by WYC-2020** [comment]
等我消息

**Comment by 0xDion** [comment]
同问题，Xray-core编译报错

**Comment by bi4tms** [comment]
> 等我消息

坐等大佬公布调整方法

**Comment by xiaotan8** [comment]
好像镜像都没发布1.20版。

**Comment by WYC-2020** [comment]
试过了 升级倒是可以升，并且用1.20的确实能编译通过，但是其他很多用go的都会编译错误，因为1.20 还没普及，pw那边 有提交xray patch 建议暂时可以用那个方式搞，等大部分用go的包都升级到1.20 在升级go 要不然得不偿失，因为一个包导致其他包都的打patches

**Comment by WYC-2020** [comment]
[fix_go_120.tar.gz](https://github.com/coolsnowwolf/lede/files/10671245/fix_go_120.tar.gz)
用这个直接覆盖 就可以了 @bi4tms

**Comment by guoguo163** [comment]
> [fix_go_120.tar.gz](https://github.com/coolsnowwolf/lede/files/10671245/fix_go_120.tar.gz) 用这个直接覆盖就可以了@bi4tms

![批注 2023-02-08 170721](https://user-images.githubusercontent.com/34234063/217485516-0d330032-3932-4ca7-bba4-b7e9d0e4b12b.jpg)
我这个是因为没删掉010-compatible-with-go-1.18+.patch 吗

**Comment by WYC-2020** [comment]
> > [fix_go_120.tar.gz](https://github.com/coolsnowwolf/lede/files/10671245/fix_go_120.tar.gz) 用这个直接覆盖就可以了@bi4tms
> 
> ![批注 2023-02-08 170721](https://user-images.githubusercontent.com/34234063/217485516-0d330032-3932-4ca7-bba4-b7e9d0e4b12b.jpg) 我这个是因为没删掉010-compatible-with-go-1.18+.patch 吗

是的 最好是吧原来的都删除 然后用我这个 直接放过去，当然你也可以 用那个patch 不用我这个，那个patch 修复的比较全 包含很多版本，我没修复那么多

**Comment by jmmes** [comment]
> > > [fix_go_120.tar.gz](https://github.com/coolsnowwolf/lede/files/10671245/fix_go_120.tar.gz) 用这个直接覆盖就可以了@bi4tms
> > 
> > 
> > ![批注 2023-02-08 170721](https://user-images.githubusercontent.com/34234063/217485516-0d330032-3932-4ca7-bba4-b7e9d0e4b12b.jpg) 我这个是因为没删掉010-compatible-with-go-1.18+.patch 吗
> 
> 是的 最好是吧原来的都删除 然后用我这个 直接放过去，当然你也可以 用那个patch 不用我这个，那个patch 修复的比较全 包含很多版本，我没修复那么多

请问patch在哪下呢？同遇到类似问题了！
