### ISSUE TITLE
编译涉及到v2ray时出错，发现是指向v2ray要下载的v2ray-linux-64.zip地址发生变化

### ISSUE THREAD

**Issue by jiushibushuo** [coolsnowwolf/lede#1086]
请在源码中修正指向的错误，谢谢！

**Comment by hcym** [comment]
不知道是不是错误，一直非常非常慢，也不是放在dl目录，不能像其它包一样用浏览器下载替代

**Comment by SouHong** [comment]
我换成最新版本了。

**Comment by liudorangefly** [comment]
源码中的v2ray core版本为4.15.1在v2ray的release列表中4.15.1版本已经删除无法下载,将源码中的v2ray版本号改为最新版本即可下载

**Comment by jiushibushuo** [comment]
源码已修正，重新updagte即可
