### ISSUE TITLE
WARNING: Makefile 'package/feeds/luci/luci-app-n2n/Makefile' has a dependency on 'n2n'

### ISSUE THREAD

**Issue by rookieis** [coolsnowwolf/lede#10864]
之前一直编译正常，这次准备二次编译一下，运行以下。menuconfig什么都没改
cd lede
git pull
./scripts/feeds update -a
./scripts/feeds install -a
运行到这里报错：
WARNING: Makefile 'package/feeds/luci/luci-app-n2n/Makefile' has a dependency on 'n2n', which does not exist
Installing all packages from feed packages.
WARNING: Not overriding core package 'n2n'; use -f to force
WARNING: Not overriding core package 'v2ray-geodata'; use -f to force
Installing all packages from feed luci.
WARNING: Not overriding core package 'luci-app-qbittorrent-simple'; use -f to force
Installing all packages from feed routing.
Installing all packages from feed telephony.

make defconfig
运行到这里报错：
**WARNING: Makefile 'package/feeds/luci/luci-app-n2n/Makefile' has a dependency on 'n2n', which does not exist**
请问啥问题额

**Comment by xiankaiyao** [comment]
同问，解决了吗
