### ISSUE TITLE
ShadowsocksR Plus +编译时在哪选？

### ISSUE THREAD

**Issue by qq253044370** [coolsnowwolf/lede#1087]
在luci-application里没有啊。在哪里选上？？
选择的是 luci-app-ssr-plus，SS/SSR/v2ray luci interface。
但是编译好之后，路由里没有找到啊。

**Comment by kejiso** [comment]
需要芝麻开门

**Comment by kejiso** [comment]
> 在luci-application里没有啊。在哪里选上？？
> 选择的是 luci-app-ssr-plus，SS/SSR/v2ray luci interface。
> 但是编译好之后，路由里没有找到啊。

需要芝麻开门

**Comment by lan542662** [comment]
芝麻开门

**Comment by bear110** [comment]
> 芝麻开门

什么意思啊？

**Comment by lan542662** [comment]
先在这里搜索问题有没有答案再发表问题。

bear110 <notifications@github.com> 于2019年3月1日周五 下午12:02写道：

**Comment by ntgeralt** [comment]
ssh或终端连上路由
神秘代码芝麻开门
echo 0xDEADBEEF > /etc/config/google_fu_mode

**Comment by jiushibushuo** [comment]
编译的时候在哪里改下可以不用刷好再输入代码？

**Comment by aldslvda** [comment]
马克一下。。。
