### ISSUE TITLE
按照最新代码编译的op，开机半小时左右，接口界面什么信息都不显示

### ISSUE THREAD

**Issue by kenwestern** [coolsnowwolf/lede#10875]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
按照最新代码编译的op，开机半小时左右，实际网络是通的的，但接口界面wan、lan接口都在但连接速率、收发包数等什么信息都不显示，就像没连接一样，概览中的网络也显示未连接。

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：OpenWrt R23.1.1

### (3) 详细日志
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.700844,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.700877,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.700935,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.700953,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.701010,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]: [2023/02/06 08:40:23.701027,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:40:23 2023 daemon.err smbd[20807]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:40:24 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:27 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:30 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:33 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:37 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:40 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:43 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:40:46 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.656842,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.656889,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.656958,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.656978,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.657044,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.657062,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.692982,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.693015,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.693073,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.693091,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.693148,  0] ../../lib/param/loadparm.c:816(lpcfg_map_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Unknown parameter encountered: "write mode"
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]: [2023/02/06 08:45:23.693165,  0] ../../lib/param/loadparm.c:1896(lpcfg_do_service_parameter)
Mon Feb  6 08:45:23 2023 daemon.err smbd[21526]:   Ignoring unknown parameter "write mode"
Mon Feb  6 08:46:02 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:05 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:08 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:11 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:12 2023 kern.info kernel: [24306.406956] igc 0000:06:00.0 eth5: NIC Link is Down
Mon Feb  6 08:46:14 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:18 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:21 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable
Mon Feb  6 08:46:23 2023 kern.info kernel: [24317.967162] igc 0000:06:00.0 eth5: NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX/TX
Mon Feb  6 08:46:24 2023 daemon.err zerotier-one[24488]: connect: Host is unreachable

A：

**Comment by chenzhitong** [comment]
多按几次回车，就看到 OPENWRT 字样了
