### ISSUE TITLE
WARNING: Not overriding core package 'lua-maxminddb'; use -f to force

### ISSUE THREAD

**Issue by squaly1** [coolsnowwolf/lede#10888]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译vssr出错
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
用lede的代码加上vssr插件，每次输入./scripts/feeds install -a就会出现错误，
WARNING: Not overriding core package 'lua-maxminddb'; use -f to force

我再用./scripts/feeds install -a -f 安装，出现
Overriding core package 'lua-maxminddb' with version from opentopd

./scripts/feeds update lua-maxminddb
./scripts/feeds install -a -p lua-maxminddb

没任何提示我就开始编译，最好还是出错，vssr那边没人，只好来这里问，谢谢。

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：

make[3]: *** [Makefile:56: /home/squaly/lede/build_dir/target-x86_64_musl/hysteria-1.3.2/.built] Error 1
make[3]: Leaving directory '/home/squaly/lede/feeds/helloworld/hysteria'
time: package/feeds/helloworld/hysteria/compile#0.91#0.35#0.58
    ERROR: package/feeds/helloworld/hysteria failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/hysteria/compile] Error 1
make[2]: Leaving directory '/home/squaly/lede'
make[1]: *** [package/Makefile:110: /home/squaly/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/squaly/lede'
make: *** [/home/squaly/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
算不出来
