### ISSUE TITLE
你们有没有试过v2ray ws tls 模式，路由不正常工作

### ISSUE THREAD

**Issue by ntgeralt** [coolsnowwolf/lede#1088]
看v2ray日志，显示时间差几个小时，好像是时区不同。
但路由主页下面的时间又是和我PC显示的一样，
v2ray 不勾选 允许不安全，就不能正常工作……

请问怎么修正。

**Comment by zhegexiaohuozi** [comment]
我也遇到了，自己按官方简单粗暴的重写了 `package/lean/luci-app-v2ray-pro/root/etc/init.d/v2raypro`

**Comment by xlf1234** [comment]
是证书问题吧

xiaohuo <notifications@github.com> 于2019年3月14日周四 下午4:47写道：

**Comment by lijun0326** [comment]
允许不安全肯定是证书的问题。
你把WebSocket Header这项填写成正确的服务器域名，不行的话直接用浏览器访问一下你梯子的服务器地址看下证书是否正确

**Comment by ntgeralt** [comment]
chrome提示证书正常，v2rayng 小火箭皆无需允许不安全。日志时间不正常的都会导致证书不工作。内置时区错误。
