### ISSUE TITLE
编译uqmi出现dev.c.o失败

### ISSUE THREAD

**Issue by xuexiao-weizi** [coolsnowwolf/lede#10884]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
有这个错误，但是没有解决
### (1) 具体问题

A：编译uqmi出现dev.c.o失败

### (2) 路由器型号和固件版本

A：aarch64_cortex-a53  固件

### (3) 详细日志

FAILED: CMakeFiles/uqmi.dir/dev.c.o
/home/zhiwei/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.2.0_musl/bin/aarch64-openwrt-linux-musl-gcc -DDEBUG  -Os -pipe -march=armv8-a+crypto -mtune=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40=uqmi-2022-05-04-56cb2d40 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/zhiwei/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include -ffunction-sections -fdata-sections -DNDEBUG   -Os -ggdb -Wall -Werror --std=gnu99 -Wmissing-declarations -Wno-enum-conversion -g3 -MD -MT CMakeFiles/uqmi.dir/dev.c.o -MF CMakeFiles/uqmi.dir/dev.c.o.d -o CMakeFiles/uqmi.dir/dev.c.o -c /home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c
/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c: In function 'qmi_request_wait':
/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c:217:23: error: storing the address of local variable 'complete' in '*req.complete' [-Werror=dangling-pointer=]
  217 |         req->complete = &complete;
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~
/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c:208:14: note: 'complete' declared here
  208 |         bool complete = false;
      |              ^~~~~~~~
/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c:208:14: note: 'req' declared here
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:51: /home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/.built] Error 1
make[3]: Leaving directory '/home/zhiwei/lede/package/network/utils/uqmi'
time: package/network/utils/uqmi/compile#0.31#0.05#2.04
    ERROR: package/network/utils/uqmi failed to build.
make[2]: *** [package/Makefile:116: package/network/utils/uqmi/compile] Error 1
make[2]: Leaving directory '/home/zhiwei/lede'
make[1]: *** [package/Makefile:110: /home/zhiwei/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhiwei/lede'
make: *** [/home/zhiwei/lede/include/toplevel.mk:231: world] Error 2

**Comment by 097** [comment]
看起来是代码写得有问题，被编译器发现了：

/home/zhiwei/lede/build_dir/target-aarch64_cortex-a53_musl/uqmi-2022-05-04-56cb2d40/dev.c:217:23: error: storing the address of local variable 'complete' in '*req.complete' [-Werror=dangling-pointer=]

**Comment by lovehackintosh** [comment]
apply 这个PR #10825

**Comment by dfbucy090** [comment]
同问，小白看不懂就问，大佬都是怎么解决

N1和X86编译都不行了，开始都出现
mkdir -p /root/lede/dl
SHELL= flock /root/lede/tmp/.fortify-headers-1.1.tar.gz.flock -c '      /root/lede/scripts/download.pl "/root/lede/dl" "fortify-headers-1.1.tar.gz" "6ba5d860a2d2ba4c3346924b93930c34856eafe148bdbdf271ecab8065201fb6" "" "https://dl.2f30.org/releases"    '
mkdir -p /root/lede/dl
SHELL= flock /root/lede/tmp/.linux-5.15.94.tar.xz.flock -c '    /root/lede/scripts/download.pl "/root/lede/dl" "linux-5.15.94.tar.xz" "da9270dbe64ddf1db13c70470957ff6796eb996d867bb4aed7d14a70e1c65a72" "" "@KERNEL/linux/kernel/v5.x"    '
bash: line 1: aarch64-openwrt-linux-musl-gcc: command not found
bash: line 1: aarch64-openwrt-linux-musl-gcc: command not found
+ curl -f --connect-timeout 20 --retry 5 --location https://mirrors.aliyun.com/gnu/gdb/gdb-12.1.tar.xz
bash: line 1: aarch64-openwrt-linux-musl-gcc: command not found
+ curl -f --connect-timeout 20 --retry 5 --location https://mirrors.aliyun.com/gnu/binutils/binutils-2.39.tar.xz


mkdir -p /home/fangqin094/lede/dl
SHELL= flock /home/fangqin094/lede/tmp/.linux-5.15.94.tar.xz.flock -c '         /home/fangqin094/lede/scripts/download.pl "/home/fangqin094/lede/dl" "linux-5.15.94.tar.xz" "da9270dbe64ddf1db13c70470957ff6796eb996d867bb4aed7d14a70e1c65a72" "" "@KERNEL/linux/kernel/v5.x"    '
bash: line 1: x86_64-openwrt-linux-musl-gcc: command not found
+ curl -f --connect-timeout 20 --retry 5 --location https://mirrors.aliyun.com/gnu/binutils/binutils-2.39.tar.xz
+ curl -f --connect-timeout 20 --retry 5 --location https://mirrors.aliyun.com/gnu/gdb/gdb-12.1.tar.xz
bash: line 1: x86_64-openwrt-linux-musl-gcc: command not found
bash: line 1: x86_64-openwrt-linux-musl-gcc: command not found

结果是

touch /home/fangqin094/lede/staging_dir/hostpkg/stamp/.ruby_installed
make[3]: Leaving directory '/home/fangqin094/lede/feeds/packages/lang/ruby'
time: package/feeds/packages/ruby/host-compile#343.05#58.31#775.89
make[2]: Leaving directory '/home/fangqin094/lede'
make[1]: *** [package/Makefile:110: /home/fangqin094/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/fangqin094/lede'
make: *** [/home/fangqin094/lede/include/toplevel.mk:231: world] Error 2

**Comment by xuexiao-weizi** [comment]
全部rm之后，全新编译解决！！！
