### ISSUE TITLE
aliddns无法更新ip

### ISSUE THREAD

**Issue by yuanyue456** [coolsnowwolf/lede#1090]
![qq 20190302123627](https://user-images.githubusercontent.com/3966509/53677246-cfa01e80-3ce7-11e9-9789-7de58cef1377.png)
一直重复，无法更新ip

固件版本 | OpenWrt R9.2.14 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

**Comment by yuanyue456** [comment]
固件版本 | OpenWrt R9.2.14 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

**Comment by wolfgangsk07** [comment]
也遇到过同样问题

**Comment by yuanyue456** [comment]
> 也遇到过同样问题

請問你如何解決？
