### ISSUE TITLE
iStore

### ISSUE THREAD

**Issue by zou0804** [coolsnowwolf/lede#10905]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译后的lede，web界面中iStore显示未对齐
Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
编译最新版的lede，刷入x86工控机，web界面左边的功能栏中istore显示未对齐
### (1) 具体问题

A：
![image](https://user-images.githubusercontent.com/38002490/219529575-50478531-08a2-41c4-939b-cc00a8df82e4.png)

### (2) 路由器型号和固件版本

A：路由器：x86工控机
     固件版本：OpenWrt R23.1.1 / LuCI Master (git-23.040.60681-9fc2e34)

### (3) 详细日志

A：

**Comment by starxu1971** [comment]
這個不是大雕做的找上游作者
