### ISSUE TITLE
求不要更新了，老子教不动了

### ISSUE THREAD

**Issue by ForgotFun** [coolsnowwolf/lede#1092]
Lean大神你好，我是佐须之男，<跟着佐大学OpenWrt开发入门培训班>视频教程的作者。
学员们都非常喜欢你的代码，天天问我有关lean固件编译相关的问题，我每天解答学员问题到凌晨3点，求你不要更新了，我太累了想早点休息。

**Comment by KFERMercer** [comment]
> Lean大神你好，我是佐须之男，<跟着佐大学OpenWrt开发入门培训班>视频教程的作者。
> 学员们都非常喜欢你的代码，天天问我有关lean固件编译相关的问题，我每天解答学员问题到凌晨3点，求你不要更新了，我太累了想早点休息。

是真的，我就是编译器

**Comment by ctr54188** [comment]
原来这也解答，哈哈
快更新，快更新，明天报名佐大培训班

**Comment by scllen** [comment]
像佐大这么精♂壮的男子不应该说累嘛~

**Comment by redchenjs** [comment]
:joy:

**Comment by qq253044370** [comment]
本来不清楚佐大是谁，这一发帖，就知道了。我觉得你发完这个，会有更多的人问你。

**Comment by lan542662** [comment]
情场失意，商场得意，佐大棒棒哒

**Comment by dongfangy2011** [comment]
佐大这么年轻都受不了了，哈哈哈

**Comment by nobk** [comment]
你做教学可以自己克隆一个不更新的分支来教啊，我们要自己用的怎么可能因为你的教学而不更新。

**Comment by ctr54188** [comment]
> 
> 
> 你做教学可以自己克隆一个不更新的分支来教啊，我们要自己用的怎么可能因为你的教学而不更新。

没看懂吧，好好再想想

**Comment by coolsnowwolf** [comment]
皮

**Comment by suoZhangEmbedded** [comment]
听闻，过来打卡！

**Comment by wujunze** [comment]
哈哈哈  太皮了

**Comment by teapethu** [comment]
这两人。。。。谁是分身？

**Comment by caissonfiv** [comment]
皮

**Comment by evangelion015** [comment]
够皮

**Comment by SixGodNero** [comment]
连佐大这么精壮的男子都受不了lean的日更了吗
