### ISSUE TITLE
linux-firmware什么的hash值不对，无法通过编译

### ISSUE THREAD

**Issue by sss132919** [coolsnowwolf/lede#10923]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
有可能你从备用地址下载下来的，就可能出现hash 不对，直接skip 跳过 别检测
