### ISSUE TITLE
怎么升级linux内核

### ISSUE THREAD

**Issue by Eay5** [coolsnowwolf/lede#10939]
## 1.关于你要提交的问题
1.除了提交linux内核版本号和Hash.还需要提交什么吗?

**Comment by baodp** [comment]
同问，我也想提交最新内核到X86。能给教程吗？我们很有空。

**Comment by aoxueos** [comment]
https://forgotfun.org/openwrt-training.html

**Comment by baodp** [comment]
> https://forgotfun.org/openwrt-training.html

别这样！！ 有没有开源的教程！！

**Comment by WYC-2020** [comment]
> 同问，我也想提交最新内核到X86。能给教程吗？我们很有空。

这种玩意 你稍微看下别人升级提交的commit 就会的，并且提之前请测试，很多时候更新了都会出各种奇葩问题，特别是大版本更新
