### ISSUE TITLE
5.15编译quectel_cm_5G报错

### ISSUE THREAD

**Issue by Mousehk** [coolsnowwolf/lede#10931]
报错内容:
make[3]: *** [Makefile:50: /home/mouse/lede/build_dir/target-x86_64_musl/linux-x86_64/quectel-CM-5G-1.0/.prepared_5f6481de54d7c23b9de2a001d3ad14e4_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/mouse/lede/package/wwan/driver/quectel_cm_5G'
time: package/wwan/driver/quectel_cm_5G/compile#0.68#0.23#0.87
    ERROR: package/wwan/driver/quectel_cm_5G failed to build.
make[2]: *** [package/Makefile:116: package/wwan/driver/quectel_cm_5G/compile] Error 1
make[2]: Leaving directory '/home/mouse/lede'
make[1]: *** [package/Makefile:110: /home/mouse/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mouse/lede'
make: *** [/home/mouse/lede/include/toplevel.mk:231：world] 错误 2

**Comment by coolsnowwolf** [comment]
fixed
