### ISSUE TITLE
依赖包g++-multilib，libc6-dev-i386找不到

### ISSUE THREAD

**Issue by jepson66** [coolsnowwolf/lede#10946]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
1.在安装编译依赖时候报错了，找不到g++-multilib，libc6-dev-i386，
2.本人环境mac m1处理器 虚拟机 ubuntu22.04

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志
<img width="570" alt="image" src="https://user-images.githubusercontent.com/108441697/222105691-950cf1e0-5377-4f41-a4aa-2eefa5b74f97.png">

A：

**Comment by minfengyk** [comment]
M系列芯片电脑上ARM版Ubuntu 22安装依赖教程

一、安装编译所需依赖
       ssh登陆Ubuntu，输入：
sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext \
git gperf haveged help2man intltool libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

二、安装arm系统依赖
       gcc-multilib 、g++-multilib、 libc6-dev-i386在arm系统里对应的依赖

sudo apt install gcc-multilib-i686-linux-gnu gcc-multilib-s390x-linux-gnu gcc-multilib-x86-64-linux-gnu gcc-multilib-x86-64-linux-gnux32

sudo apt install g++-multilib-i686-linux-gnu g++-multilib-s390x-linux-gnu g++-multilib-x86-64-linux-gnu g++-multilib-x86-64-linux-gnux32

sudo apt install libc6-dev-i386-amd64-cross libc6-dev-i386-cross libc6-dev-i386-x32-cross

三、安装go
       输入：sudo apt install golang-go

四、配置go环境
       编辑.config，这是一个隐藏文件，就在lede目录下：
1、输入：gedit .config
2、找到CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT=””这行，在双引号中填入/usr/bin/go

⚠️：编译时不要勾选naiveproxy
