### ISSUE TITLE
大麦33d 5g驱动与ttyd冲突

### ISSUE THREAD

**Issue by Anklerwa** [coolsnowwolf/lede#1095]
大麦33d，r9在编译时勾选ttyd，刷入固件后没有5g驱动，多次全新编译都是这样。改用r8（没有ttyd）刷入后，手动安装ttyd，原本能用的5g立马不能用了。估计是ttyd与5g驱动有冲突。

**Comment by sqliuchang** [comment]
咦，我也编译了TTYD，没问题啊
主机型号	DomyWifi DW33D CPU:720Mhz
固件版本	OpenWrt R9.2.14 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

**Comment by Anklerwa** [comment]
> 咦，我也编译了TTYD，没问题啊
> 主机型号	DomyWifi DW33D CPU:720Mhz
> 固件版本	OpenWrt R9.2.14 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

我 r8  r9 都是这样子，难不成是我gg版的个别问题？
