### ISSUE TITLE
kmod-fs-antfs 求助

### ISSUE THREAD

**Issue by lixiangmo** [coolsnowwolf/lede#10963]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：
WARNING: Makefile 'package/feeds/packages/antfs-mount/Makefile' has a dependency on 'kmod-fs-antfs', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.

**Comment by dudulongg** [comment]
我也有这个警告，但是不影响编译

**Comment by ChrisLiu0343** [comment]
me too

**Comment by xuelide** [comment]
之前都编译好好的，昨天编译我也遇到了。

**Comment by Studiocn** [comment]
我今天也遇到了咋解决
