### ISSUE TITLE
提示kmod-fs-antfs不存在

### ISSUE THREAD

**Issue by rongcenter** [coolsnowwolf/lede#10961]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (3) 详细日志

xx@xx:~/lede$ ./scripts/feeds install -a
Collecting package info: package/feeds/packages/udp-broadcast-relay-redux-openwrCollecting package info: done
Collecting target info: done
WARNING: Makefile 'package/feeds/packages/antfs-mount/Makefile' has a dependency on 'kmod-fs-antfs', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.

**Comment by Beginner-Go** [comment]
@1582130940 你似乎忘记 cherry 这个[commit](https://github.com/openwrt/packages/commit/8027ea5c0ff02535c3665fa430774f721f58634f)

**Comment by DNW345** [comment]
我还以为我自己的问题。把整个LEDE删除了才看到你发

**Comment by rongcenter** [comment]
> 我还以为我自己的问题。把整个LEDE删除了才看到你发

直接删了

**Comment by Studiocn** [comment]
我也遇到了这么解决这个警告

**Comment by 1582130940** [comment]
> @1582130940 你似乎忘记 `cherry` 这个[commit](https://github.com/openwrt/packages/commit/8027ea5c0ff02535c3665fa430774f721f58634f)
> 
> 顺便 `cherry` 下 `openssl 3.0`

https://github.com/coolsnowwolf/packages/pull/656
另外，主线我合并了，treewide被关了，麻烦自行pick吧
https://github.com/coolsnowwolf/lede/pull/10953
