### ISSUE TITLE
开启解锁网易云灰色歌曲的插件防火墙 Turbo ACC 网络设置保存不上

### ISSUE THREAD

**Issue by liuyanantj** [coolsnowwolf/lede#10969]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译选择了解锁网易云灰色歌曲的插件，该插件在开启状态，进行防火墙和 Turbo ACC 网络设置 设置一次能保存配置，第二次就开在应用中  无法保存配置，设置其他插件也是先显示应用防火墙配置，就一直卡着  只有重启之后关闭网易云音乐才能重新设置

### (2) 路由器型号和固件版本

A：x86 R4S都有此情况

### (3) 详细日志

A：无日志

**Comment by WYC-2020** [comment]
这个问题我以前就说过了，自己找下
