### ISSUE TITLE
SSR Plus+ 服务器能增加协议吗？

### ISSUE THREAD

**Issue by Leslie-Wong** [coolsnowwolf/lede#1097]
现在只有origin一个，能加上其他协议吗？
列如：auth_chain_a，auth_sha1_v4，auth_aes128_sha1等等。

SSR Python 服务器介面上少了「混淆参数」这一栏。

**Comment by coolsnowwolf** [comment]
服务器这端并不需要 混淆参数

**Comment by ynkmsnake** [comment]
在添加节点的地方也没有设置混淆的地方，我买的节点是带obfs的，这个参数不设置，连接有问题
