### ISSUE TITLE
ksmbd build fail

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#10977]
last commit:

```
Applying` ./patches/01-keep_kmod_metadata.patch using plaintext:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/glob.h
|+++ b/glob.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/01-keep_kmod_metadata.patch!
make[3]: *** [Makefile:77: /home/builder/lede_x86/build_dir/target-x86_64_musl/linux-x86_64/ksmbd-3.4.7/.prepared_fdcfbd1e0c0f35be08baee143a27add0_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/builder/lede_x86/package/kernel/ksmbd'
time: package/kernel/ksmbd/compile#0.12#0.16#0.27
    ERROR: package/kernel/ksmbd failed to build.
make[2]: *** [package/Makefile:116: package/kernel/ksmbd/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2
`builder@Build-Server:/home/builder/lede_x86$
```

**Comment by hzjnet** [comment]
> last commit:
> 
> ```
> Applying` ./patches/01-keep_kmod_metadata.patch using plaintext:
> can't find file to patch at input line 3
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |--- a/glob.h
> |+++ b/glob.h
> --------------------------
> No file to patch.  Skipping patch.
> 1 out of 1 hunk ignored
> Patch failed!  Please fix ./patches/01-keep_kmod_metadata.patch!
> make[3]: *** [Makefile:77: /home/builder/lede_x86/build_dir/target-x86_64_musl/linux-x86_64/ksmbd-3.4.7/.prepared_fdcfbd1e0c0f35be08baee143a27add0_6664517399ebbbc92a37c5bb081b5c53] Error 1
> make[3]: Leaving directory '/home/builder/lede_x86/package/kernel/ksmbd'
> time: package/kernel/ksmbd/compile#0.12#0.16#0.27
>     ERROR: package/kernel/ksmbd failed to build.
> make[2]: *** [package/Makefile:116: package/kernel/ksmbd/compile] Error 1
> make[2]: Leaving directory '/home/builder/lede_x86'
> make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
> make[1]: Leaving directory '/home/builder/lede_x86'
> make: *** [/home/builder/lede_x86/include/toplevel.mk:231：world] 错误 2
> `builder@Build-Server:/home/builder/lede_x86$
> ```

换成openwrt master版本的正常
