### ISSUE TITLE
OrangePi R1 Plus LTS无法使用WAN口

### ISSUE THREAD

**Issue by BaichenXianchen** [coolsnowwolf/lede#10980]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：OrangePi R1 Plus LTS无法使用WAN口，貌似是YT8531C无法驱动

### (2) 路由器型号和固件版本

A：OrangePi R1 Plus LTS  6.1/5.15

### (3) 详细日志

A：

**Comment by QYKing233** [comment]
刚才移植orangepi-linux里的官方驱动本地编译的内核6.1.5版本的固件双网卡正常工作，但是我不会打补丁，你可以看看官方提交的yt8531C支持，自己改下。或者你编译5.10内核的，lede里的patch是能打上的。

**Comment by QYKing233** [comment]
![IMG_20230312_075631.jpg](https://user-images.githubusercontent.com/61415390/224516834-eb4d0662-db5e-4255-ab3c-1aeb7c8741ca.jpg)

**Comment by BaichenXianchen** [comment]
那我先试一下

**Comment by QYKing233** [comment]
> 那我先试一下

我的仓库里有编译好的固件

**Comment by BaichenXianchen** [comment]
谢谢了

**Comment by Gabrielxzx** [comment]
你好，问下现在问题解决了吗？我的编译后WAN口也无法使用

**Comment by QYKing233** [comment]
> 你好，问下现在问题解决了吗？我的编译后WAN口也无法使用

我仓库有你可以下载用。

**Comment by BaichenXianchen** [comment]
> > 那我先试一下
> 
> 我的库房里有编译好的固件

是否能给我一份添加修改YT8531 patch的教程，我需要自己编译固件

**Comment by BaichenXianchen** [comment]
@coolsnowwolf YT8531C网卡有什么好的解决方案

**Comment by BaichenXianchen** [comment]
问题已经解决
