### ISSUE TITLE
请教一下各位，酸酸乳plus 怎么设置才能全局代理

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#1098]
请教一下各位，酸酸乳plus 怎么设置才能全局代理

就是像以前的ywb94的旧ssr，和后来的ssr pro， 还有别的基于ywb94的修改的ssr那样，设置全局代理模式全部走ssr代理

**Comment by jindaxia** [comment]
访问控制LAN里面 可以把你的IP地址添加到  全局里面

**Comment by sqliuchang** [comment]
楼上说的对，测试确实是全局代理
