### ISSUE TITLE
求万能的大雕增加一个k2p的512m内存支持啊

### ISSUE THREAD

**Issue by shuiyuechangchun** [coolsnowwolf/lede#1100]
本人是新手小白，之前编译了op r8，刷上去以后可用内存只有120m，但是路由器实际内存有512m。本人不会修改源代码。求万能的大雕帮忙直接在源代码中修改，万分感谢。

**Comment by uglee** [comment]
修改dts文件对应内存的参数即可，参考Newifi-D2。
memory@0 {
		device_type = "memory";
		reg = <0x0 0x1c000000>, <0x20000000 0x4000000>;

点到为止，还不会就没办法了

**Comment by shuiyuechangchun** [comment]
> 修改dts文件对应内存的参数即可，参考Newifi-D2。
> memory@0 {
> device_type = "memory";
> reg = <0x0 0x1c000000>, <0x20000000 0x4000000>;
> 
> 点到为止，还不会就没办法了

大哥，我真不会啊，看不懂啊，所以求雕大集成啊

**Comment by shuiyuechangchun** [comment]
> 修改dts文件对应内存的参数即可，参考Newifi-D2。
> memory@0 {
> device_type = "memory";
> reg = <0x0 0x1c000000>, <0x20000000 0x4000000>;
> 
> 点到为止，还不会就没办法了

大佬，请问是这个文件吗：/lede/target/linux/ramips/dts/MT7621.dts
