### ISSUE TITLE
btbcm.ko' is missing

### ISSUE THREAD

**Issue by vipboddy** [coolsnowwolf/lede#11019]
ERROR: module '/home/lucky/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.103/drivers/bluetooth/btbcm.ko' is missing.
make[2]: *** [modules/other.mk:73: /home/lucky/lede/bin/targets/x86/64/packages/kmod-bluetooth_5.15.103-1_x86_64.ipk] Error 1
make[2]: Leaving directory '/home/lucky/lede/package/kernel/linux'
time: package/kernel/linux/compile#54.67#15.96#269.13
    ERROR: package/kernel/linux failed to build.
make[1]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1

**Comment by coolsnowwolf** [comment]
fixed

**Comment by catsimple** [comment]
git pull [https://github.com/coolsnowwolf/lede/commit/756cf526a691bc95ce43d91e8d7b5ee6a8cc126a](url)
make clean后问题依旧

**Comment by mahakalaya** [comment]
> git pull make clean后问题依旧

+1

**Comment by WYC-2020** [comment]
那样修复是不行的，亲测所有内核 5.4 5.10 5.15 6.1
![image](https://user-images.githubusercontent.com/34025388/226796469-2c400275-2d20-4918-beaa-4d91b25fd00d.png)
![image](https://user-images.githubusercontent.com/34025388/226796479-860c9b83-e410-449b-a3a6-fe70998ee22e.png)
![image](https://user-images.githubusercontent.com/34025388/226796495-447767c8-54e9-4a8e-8341-731e51c60b2a.png)

**Comment by mahakalaya** [comment]
> 那样修复是不行的，亲测所有内核 5.4 5.10 5.15 6.1 ![image](https://user-images.githubusercontent.com/34025388/226796469-2c400275-2d20-4918-beaa-4d91b25fd00d.png) ![image](https://user-images.githubusercontent.com/34025388/226796479-860c9b83-e410-449b-a3a6-fe70998ee22e.png) ![image](https://user-images.githubusercontent.com/34025388/226796495-447767c8-54e9-4a8e-8341-731e51c60b2a.png)

WCY老大修复一下嘛

**Comment by 744287383** [comment]
`SHELL= flock /home/cattle/Downloads/lede/tmp/.root-copy.flock -c 'cp -fpR /home/cattle/Downloads/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/packages/.pkgdir/kernel/. /home/cattle/Downloads/lede/staging_dir/target-aarch64_cortex-a53_musl/root-armvirt/'
touch /home/cattle/Downloads/lede/staging_dir/target-aarch64_cortex-a53_musl/root-armvirt/stamp/.kernel_installed
Package kmod-bluetooth is missing dependencies for the following libraries:
btbcm.ko
make[3]: *** [modules/other.mk:74: /home/cattle/Downloads/lede/bin/targets/armvirt/64/packages/kmod-bluetooth_5.15.104-1_aarch64_cortex-a53.ipk] Error 1
make[3]: Leaving directory '/home/cattle/Downloads/lede/package/kernel/linux'
time: package/kernel/linux/compile#2.61#0.25#2.84
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/home/cattle/Downloads/lede'
make[1]: *** [package/Makefile:110: /home/cattle/Downloads/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/cattle/Downloads/lede'
make: *** [/home/cattle/Downloads/lede/include/toplevel.mk:231：world] 错误 2
`
我这个好像也是这个错误

**Comment by sxml** [comment]
大佬们 怎么解决呢？


Package kmod-bluetooth is missing dependencies for the following libraries:
btbcm.ko
make[3]: *** [modules/other.mk:73: /workdir/openwrt/bin/targets/armvirt/64/packages/kmod-bluetooth_5.15.104-1_aarch64_cortex-a53.ipk] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#4.07#0.46#4.50
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by WYC-2020** [comment]
这个l不是已经删除了么 你们自己在distclean 在menuconfig 一下 就好了，如果不想用删除版本 就像我上面图那样改，我自己是保留了的
