### ISSUE TITLE
bananapi_bpi-r3-sdcard.img.gz is too big

### ISSUE THREAD

**Issue by dd-bpir3** [coolsnowwolf/lede#11012]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
BPI-R3编译时候提示bananapi_bpi-r3-sdcard.img.gz is too big
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
每次编译都是提文件太大，无法生成文件。openwrt编译时候没提示此问题
### (1) 具体问题
怎么修改文件得大小

### (2) 路由器型号和固件版本

A：
路由器型号  bananapi_bpi-r3 

固件版本 OpenWrt R23.3.3 / LuCI Master (git-23.073.60660-cec860d)

### (3) 详细日志

A：
WARNING: Image file /home/yph/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/tmp/openwrt-mediatek-filogic-bananapi_bpi-r3-sdcard.img.gz is too big: 79560704 > 46137344

**Comment by licsber** [comment]
编译的时候有一个镜像大小选项 自己调大

**Comment by dd-bpir3** [comment]
> 编译的时候有一个镜像大小选项 自己调大

Root filesystem partition sizeRoot filesystem partition size已经调整到1024不好用，没找到单独修改SD得固件大小选项，但是openwrt得不提示。

**Comment by WYC-2020** [comment]
你这个怕是 root 调太大了，检测固件大小的时候 直接不通过，你改小或者默认 编译看下，最好是别私自取调那个大小，基本是l写的 就行了，这种硬路由的 各种分区大小用默认，因为硬路由有硬盘大小限制并且相对偏移这些，最好就默认编译，你要做的就是选择编译那些luci 这个不像x86 软路由那样 可以随便调

**Comment by dd-bpir3** [comment]
> 你这个怕是 root 调太大了，检测固件大小的时候 直接不通过，你改小或者默认 编译看下，最好是别私自取调那个大小，基本是l写的 就行了，这种硬路由的 各种分区大小用默认，因为硬路由有硬盘大小限制并且相对偏移这些，最好就默认编译，你要做的就是选择编译那些luci 这个不像x86 软路由那样 可以随便调

用默认得不提示了不过报错了
make[7]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libbacktrace'
make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libbacktrace'
make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcpp'
make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcody'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcody'
make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libdecnumber'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libdecnumber'
make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/gcc'
/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/./gcc/xgcc -B/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/./gcc/ -xc++ -nostdinc /dev/null -S -o /dev/null -fself-test=/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0/gcc/testsuite/selftests
xgcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.
make[6]: *** [/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0/gcc/cp/Make-lang.in:196: s-selftest-c++] Error 1
make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/gcc'
make[5]: *** [Makefile:4448: all-gcc] Error 2
make[5]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final'
make[4]: *** [Makefile:976: all] Error 2
make[4]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final'
make[3]: *** [Makefile:91: /home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/.built] Error 2
make[3]: Leaving directory '/home/yph/lede/toolchain/gcc/final'
time: toolchain/gcc/final/compile#1.54#0.86#2.31
    ERROR: toolchain/gcc/final failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/gcc/final/compile] Error 1
make[2]: Leaving directory '/home/yph/lede'
make[1]: *** [toolchain/Makefile:93: /home/yph/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/yph/lede'
make: *** [/home/yph/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
> > 你这个怕是 root 调太大了，检测固件大小的时候 直接不通过，你改小或者默认 编译看下，最好是别私自取调那个大小，基本是l写的 就行了，这种硬路由的 各种分区大小用默认，因为硬路由有硬盘大小限制并且相对偏移这些，最好就默认编译，你要做的就是选择编译那些luci 这个不像x86 软路由那样 可以随便调
> 
> 用默认得不提示了不过报错了 make[7]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libbacktrace' make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libbacktrace' make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcpp' test -f config.h || (rm -f stamp-h1 && make stamp-h1) make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcpp' make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcody' make[6]: Nothing to be done for 'all'. make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libcody' make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libdecnumber' make[6]: Nothing to be done for 'all'. make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/libdecnumber' make[6]: Entering directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/gcc' /home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/./gcc/xgcc -B/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/./gcc/ -xc++ -nostdinc /dev/null -S -o /dev/null -fself-test=/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0/gcc/testsuite/selftests xgcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory compilation terminated. make[6]: *** [/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0/gcc/cp/Make-lang.in:196: s-selftest-c++] Error 1 make[6]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/gcc' make[5]: *** [Makefile:4448: all-gcc] Error 2 make[5]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final' make[4]: *** [Makefile:976: all] Error 2 make[4]: Leaving directory '/home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final' make[3]: *** [Makefile:91: /home/yph/lede/build_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/gcc-11.3.0-final/.built] Error 2 make[3]: Leaving directory '/home/yph/lede/toolchain/gcc/final' time: toolchain/gcc/final/compile#1.54#0.86#2.31 ERROR: toolchain/gcc/final failed to build. make[2]: *** [toolchain/Makefile:97: toolchain/gcc/final/compile] Error 1 make[2]: Leaving directory '/home/yph/lede' make[1]: *** [toolchain/Makefile:93: /home/yph/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2 make[1]: Leaving directory '/home/yph/lede' make: *** [/home/yph/lede/include/toplevel.mk:231: world] Error 2

你这个错误 是另外原因导致的 ，建议你clean 然后重新配置 在编译看看，看你这个错误 像是工具链哪里有问题

**Comment by dd-bpir3** [comment]
> 你clean 然后重新配置 在编
