### ISSUE TITLE
有关混合订阅的问题

### ISSUE THREAD

**Issue by ntgeralt** [coolsnowwolf/lede#1102]
你好，刚发现个问题，环境是使用ssrpanel 包含ssr和vmess的混合订阅2ssr+2vmess。ssr apk和ios小火箭无此问题。

![desktop screenshot 2019 03 07 - 22 41 07 92](https://user-images.githubusercontent.com/8230651/53964612-a38efe00-412a-11e9-89b0-29e16128ffb0.png)

**Comment by coolsnowwolf** [comment]
不支持这种格式的

**Comment by ntgeralt** [comment]
我知道不支持vmess连接，可以隐藏掉，不显示乱码更好呀
