### ISSUE TITLE
wsl2 Ubuntu 22.0.4 LTS 编译报错

### ISSUE THREAD

**Issue by realabertian** [coolsnowwolf/lede#11028]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A： python 使用的是 Ubuntu22.0.4LTS apt 默认安装的, 编译报错

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
mkdir -p /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/aber/Projects/lede-20221001/tmp/.root-copy.flock -c 'cp -fpR /home/aber/Projects/lede-20221001/build_dir/target-x86_64_musl/linux-x86_64/shortcut-fe/.pkgdir/kmod-shortcut-fe-cm/. /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/'
touch /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-shortcut-fe-cm_installed
echo "kmod-shortcut-fe-cm" >> /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/pkginfo/shortcut-fe.default.install
make[3]: Leaving directory '/home/aber/Projects/lede-20221001/package/lean/shortcut-fe/shortcut-fe'
time: package/lean/shortcut-fe/shortcut-fe/compile#0.15#0.03#0.17
make[3]: Entering directory '/home/aber/Projects/lede-20221001/feeds/luci/applications/luci-app-turboacc'
mkdir -p /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/aber/Projects/lede-20221001/tmp/.root-copy.flock -c 'cp -fpR /home/aber/Projects/lede-20221001/build_dir/target-x86_64_musl/luci-app-turboacc/.pkgdir/luci-app-turboacc/. /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/'
touch /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-app-turboacc_installed
echo "luci-app-turboacc" >> /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/pkginfo/luci-app-turboacc.default.install
mkdir -p /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/aber/Projects/lede-20221001/tmp/.root-copy.flock -c 'cp -fpR /home/aber/Projects/lede-20221001/build_dir/target-x86_64_musl/luci-app-turboacc/.pkgdir/luci-i18n-turboacc-zh-cn/. /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/'
touch /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-i18n-turboacc-zh-cn_installed
echo "luci-i18n-turboacc-zh-cn" >> /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/pkginfo/luci-app-turboacc.default.install
make[3]: Leaving directory '/home/aber/Projects/lede-20221001/feeds/luci/applications/luci-app-turboacc'
time: package/feeds/luci/luci-app-turboacc/compile#0.28#0.04#0.32
make[3]: Entering directory '/home/aber/Projects/lede-20221001/package/lean/ucl'mkdir -p /home/aber/Projects/lede-20221001/dl
SHELL= flock /home/aber/Projects/lede-20221001/tmp/.ucl-1.03.tar.gz.flock -c '  /home/aber/Projects/lede-20221001/scripts/download.pl "/home/aber/Projects/lede-20221001/dl" "ucl-1.03.tar.gz" "b865299ffd45d73412293369c9754b07637680e5c826915f097577cd27350348" "" "http://www.oberhumer.com/opensource/ucl/download"    '
make[3]: Leaving directory '/home/aber/Projects/lede-20221001/package/lean/ucl'
time: package/lean/ucl/host-compile#0.19#0.02#0.19
make[3]: Entering directory '/home/aber/Projects/lede-20221001/package/lean/upx'mkdir -p /home/aber/Projects/lede-20221001/dl
SHELL= flock /home/aber/Projects/lede-20221001/tmp/.upx-2022-01-15.tar.gz.flock -c '     /home/aber/Projects/lede-20221001/scripts/dl_github_archive.py --dl-dir="/home/aber/Projects/lede-20221001/dl" --url="https://github.com/upx/upx.git" --version="a46b63817a9c6ad5af7cf519332e859f11558592" --subdir="upx-2022-01-15-a46b6381" --source="upx-2022-01-15.tar.gz" --hash="x" || (         echo "Checking out files from the git repository..."; mkdir -p /home/aber/Projects/lede-20221001/tmp/dl && cd /home/aber/Projects/lede-20221001/tmp/dl && rm -rf upx-2022-01-15-a46b6381 && [ \! -d upx-2022-01-15-a46b6381 ] && git clone  https://github.com/upx/upx.git upx-2022-01-15-a46b6381 && (cd upx-2022-01-15-a46b6381 && git checkout a46b63817a9c6ad5af7cf519332e859f11558592 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd upx-2022-01-15-a46b6381 && git log -1 --format='\''@%ct'\''` && rm -rf upx-2022-01-15-a46b6381/.git &&         tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c upx-2022-01-15-a46b6381 |  gzip -nc > /home/aber/Projects/lede-20221001/tmp/dl/upx-2022-01-15.tar.gz && mv /home/aber/Projects/lede-20221001/tmp/dl/upx-2022-01-15.tar.gz /home/aber/Projects/lede-20221001/dl/ && rm -rf upx-2022-01-15-a46b6381; );     '
Traceback (most recent call last):
  File "/home/aber/Projects/lede-20221001/scripts/dl_github_archive.py", line 19, in <module>
    import ssl
  File "/home/aber/Projects/lede-20221001/staging_dir/hostpkg/lib/python3.10/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
Checking out files from the git repository...
Cloning into 'upx-2022-01-15-a46b6381'...
remote: Enumerating objects: 36934, done.
remote: Counting objects: 100% (326/326), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 36934 (delta 151), reused 259 (delta 132), pack-reused 36608
Receiving objects: 100% (36934/36934), 62.41 MiB | 11.90 MiB/s, done.
Resolving deltas: 100% (29679/29679), done.
fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592
make[3]: *** [Makefile:67: /home/aber/Projects/lede-20221001/dl/upx-2022-01-15.tar.gz] Error 128
make[3]: Leaving directory '/home/aber/Projects/lede-20221001/package/lean/upx'
time: package/lean/upx/host-compile#4.36#1.27#7.57
    ERROR: package/lean/upx [host] failed to build.
make[2]: *** [package/Makefile:114: package/lean/upx/host/compile] Error 1
make[2]: Leaving directory '/home/aber/Projects/lede-20221001'
make[1]: *** [package/Makefile:110: /home/aber/Projects/lede-20221001/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/aber/Projects/lede-20221001'
make: *** [/home/aber/Projects/lede-20221001/include/toplevel.mk:230: world] Error 2

**Comment by realabertian** [comment]
是否自行编译一个带 ssl 模块的python, 还是说Ubuntu已经提供了相关的包

**Comment by WYC-2020** [comment]
这不是明显的提示么，你这个upx 是哪里的源，提示没有这个树了 自己更新下fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592

**Comment by realabertian** [comment]
> 这不是明显的提示么，你这个upx 是哪里的源，提示没有这个树了 自己更新下fatal: reference is not a tree: a46b63817a9c6ad5af7cf519332e859f11558592

编译的 20221001, 那这个版本的 upx 配置的版本不对, 我修改下试试看
