### ISSUE TITLE
有大佬可以看一下360v6吗？

### ISSUE THREAD

**Issue by Ho-Lay** [coolsnowwolf/lede#11036]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
     有类似的issue

360v6可以通过编译，但用Uboot刷之后不断重启，有大佬可以修复一下吗？

**Comment by zfdx123** [comment]
看一下启动log，用ttl

**Comment by Ho-Lay** [comment]
> 看一下启动log，用ttl

我没有用ttl刷，我试过编译 lean大佬的“[openwrt-gl-ax1800](https://github.com/coolsnowwolf/openwrt-gl-ax1800)”源，这个“openwrt-gl-ax1800”可以正常编译正常刷正常开机

我试过先刷“openwrt-gl-ax1800”编译出来的“factory.ubi”，正常开机后再刷现在这个“lede”源的“sysupgrade”，一样是刷之后无限重启，无法正常开机

我怀疑可能是 dts 文件的问题，之后比对过这个“lede”源和“openwrt-gl-ax1800”源 ipq60xx 的 dts 文件

由于小弟我学识浅薄，比对这个两个文件后发现差别太多，所以无从下手，希望有大佬可以修复一下

**Comment by zheshifandian** [comment]
是让你用ttl看log然后发出来，不是让你用ttl刷机
