### ISSUE TITLE
怎么添加USB自动挂载和网络共享?

### ISSUE THREAD

**Issue by forever8938** [coolsnowwolf/lede#1103]
机器是新3。
我选了extra package里的automount，autosamba，还有kernel里的kmod-fs-exfat。然后luci里除了luci-app-samba其他全部取消。
编译出来根本就没有网络共享的菜单，也不能自动挂载exfat。打开软件包一看，luci-app-samba已经装上了，USB挂载的包也都装了。
还有，内存显示是不会刷新的，不会动。

**Comment by Hentioe** [comment]
@coolsnowwolf 我刚编译了最新版本，除了选择了 `Target System` 和 `Target Profile` 以外没有动过任何配置，我的情况也是不会自动挂载 USB。不仅如此，连 USB 设备（通常是 `/dev/sda1`）都没有显示。我升级前一个多月前的版本是正常的。

**Comment by xun188** [comment]
同样问题，编译了，在已经安装版本里也看到了luci-app-samba，但是服务界面就是没有

**Comment by forever8938** [comment]
请问是否care这个问题，谢谢

**Comment by forever8938** [comment]
关，继续关。
