### ISSUE TITLE
最新编译的R2S固件用作旁路由，使用ShadowSocksR Plus+不能科学上网

### ISSUE THREAD

**Issue by felixxiao99** [coolsnowwolf/lede#11031]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新编译的R2S固件作为旁路由使用，使用ShadowSocksR Plus+不能科学上网，只能访问国内网站
年前编译的固件在相同旁路由设置下是可以科学上网的

另外：个人感觉问题应该是出在ShadowSocksR Plus+插件上，除了自编译固件有这个问题，我也下载了骷髅头大神的R2S固件，早期的版本(1月17号)设置旁路由能科学上网，用最新的固件(3月23号 )也不能科学上网

### (2) 路由器型号和固件版本

A：
路由器型号：NanoPi R2S
固件版本：OpenWrt R23.3.3 Compiled by xiaofei / LuCI Master (git-23.082.27304-adda8b2)
内核版本：5.15.104

### (3) 详细日志

A：
![系统日志](https://user-images.githubusercontent.com/50790338/227688858-c6c31c17-74ab-4775-b826-4fff6b58f97a.png)

**Comment by Elda1994** [comment]
老哥，请问你后来解决了么？我遇到了跟你一样的问题，但是我的固件是N1作为旁路由，也是ssr一直无法连通。求你的解决办法。

**Comment by chengcanghao** [comment]
> 老哥，请问你后来解决了么？

你 r2s 是不是用 openwrt.ai 编译的最新固件也出现了旁路由用不了 ssrplus 的问题了？
