### ISSUE TITLE
Openwrt使用p3terx编译失败 超过6小时，但只改了一行参数，请帮忙看看

### ISSUE THREAD

**Issue by carlliuxx** [coolsnowwolf/lede#11038]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：使用https://github.com/P3TERX/Actions-OpenWrt编译的，之前都好好的，3个小时多点就完成了，但是这次增加了网易云音乐，就显示超过6小时被取消，请大家帮忙看看什么原因？尝试了多次，都不行

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：The job running on runner GitHub Actions 2 has exceeded the maximum execution time of 360 minutes.

![111](https://user-images.githubusercontent.com/52060495/228104297-f5d1e24f-52d7-4b9d-8d1d-ef6940ba0d19.PNG)
![image](https://user-images.githubusercontent.com/52060495/228104456-1a1d9acf-085d-4657-8c60-e06468448b26.png)
![image](https://user-images.githubusercontent.com/52060495/228104568-6230891d-7042-4c96-b096-7a151c59bf8d.png)

**Comment by EnnawYang** [comment]
node太耗时了

**Comment by carlliuxx** [comment]
> node太耗时了

所以只能本地编译了么？:(

**Comment by Cathgao** [comment]
本地只编译插件

**Comment by WYC-2020** [comment]
我也编译了node 也就耗时一共也就耗时4个多小时
![image](https://user-images.githubusercontent.com/34025388/228156119-ac683d01-48a7-463c-979b-11f76e39ee54.png)
你是编译了多少插件，我都算编译的比较多了，也就四个多小时 哈哈

**Comment by jjm2473** [comment]
node编译要半天

**Comment by carlliuxx** [comment]
> 本地只编译插件

请问怎么只编译插件呀？小白~求指教~

**Comment by carlliuxx** [comment]
> > 本地只编译插件
> 
> 请问怎么只编译插件呀？小白~ 求指教~


查到了，这样？对么？
#在 luci -> application 选中插件，开始编译
    make package/luci-app-unblockneteasemusic/compile V=s
