### ISSUE TITLE
AX6编译报错 -ax6.dts: No such file or directory

### ISSUE THREAD

**Issue by biglihao** [coolsnowwolf/lede#11030]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
ax6编译最后提示 -ax6.dts: No such file or directory
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：cc1: fatal error: /home/runner/work/lede/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.176/arch/arm64/boot/dts/qcom/-ax6.dts: No such file or directory

### (2) 路由器型号和固件版本

A：Redmi ax6

### (3) 详细日志

A：cc1: fatal error: /home/runner/work/lede/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.176/arch/arm64/boot/dts/qcom/-ax6.dts: No such file or directory
compilation terminated.
make[5]: *** [Makefile:18: /home/runner/work/lede/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/image--ax6.dtb] Error 1
make[5]: Leaving directory '/home/runner/work/lede/lede/target/linux/ipq807x/image'
make[4]: *** [Makefile:26: install] Error 2
make[4]: Leaving directory '/home/runner/work/lede/lede/target/linux/ipq807x'
make[3]: Leaving directory '/home/runner/work/lede/lede/target/linux'
make[3]: *** [Makefile:11: install] Error 2
time: target/linux/install#27.37#8.32#35.33
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/runner/work/lede/lede'
make[1]: *** [target/Makefile:24: /home/runner/work/lede/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/runner/work/lede/lede'
make: *** [/home/runner/work/lede/lede/include/toplevel.mk:231: world] Error 2

**Comment by ddvcx** [comment]
我也是
