### ISSUE TITLE
编译时去除automount，启动后仍然报错：squashfs: Unknown parameter 'discard'

### ISSUE THREAD

**Issue by catfishuang** [coolsnowwolf/lede#11049]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

有类似的issue，但是解决方案无效，已去除了automount 甚至autosamba，编译后启动仍然报如下错误。

### (1) 具体问题

A：编译正常一次性通过，系统启动后显示如下错误信息

Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.306180] squashfs: Unknown parameter 'discard'
Sat Apr  1 18:50:52 2023 kern.info kernel: [   43.307185] F2FS-fs (sda128): Magic Mismatch, valid(0xf2f52010) - read(0x89e45589)
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.307442] F2FS-fs (sda128): Can't find valid F2FS filesystem in 1th superblock
Sat Apr  1 18:50:52 2023 kern.info kernel: [   43.307836] F2FS-fs (sda128): Magic Mismatch, valid(0xf2f52010) - read(0x2e48937b)
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.308088] F2FS-fs (sda128): Can't find valid F2FS filesystem in 2th superblock
Sat Apr  1 18:50:52 2023 kern.warn kernel: [   43.308479] exFAT-fs (sda128): mounting with "discard" option, but the device does not support discard
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309111] exFAT-fs (sda128): invalid boot record signature
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309339] exFAT-fs (sda128): failed to read boot sector
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309743] exFAT-fs (sda128): failed to recognize exfat type
Sat Apr  1 18:50:59 2023 user.notice nlbwmon: Reloading nlbwmon due to ifup of loopback (lo)
Sat Apr  1 18:51:05 2023 daemon.info procd: Instance wsdd2::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sat Apr  1 18:51:14 2023 user.notice firewall: Reloading firewall due to ifup of wan6 (eth1)
Sat Apr  1 18:51:14 2023 user.notice nlbwmon: Reloading nlbwmon due to ifup of wan6 (eth1)
Sat Apr  1 18:51:22 2023 kern.err kernel: [   73.411708] squashfs: Unknown parameter 'discard'
Sat Apr  1 18:51:22 2023 kern.err kernel: [   73.412231] /dev/sda1: Can't open blockdev

### (2) 路由器型号和固件版本

A：
路由器型号：Exsi 6.7虚拟机 x86-64-generic  或者物理机（j1900主板）
固件版本：拉取的最新版本，menuconfig中除了automount，autosamba两个包，其余保持默认选择

固件版本 | OpenWrt R23.3.3 / LuCI Master (git-23.087.57160-8186ccc)
内核版本 | 5.15.104

### (3) 详细日志

A：日志如下

Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.306180] squashfs: Unknown parameter 'discard'
Sat Apr  1 18:50:52 2023 kern.info kernel: [   43.307185] F2FS-fs (sda128): Magic Mismatch, valid(0xf2f52010) - read(0x89e45589)
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.307442] F2FS-fs (sda128): Can't find valid F2FS filesystem in 1th superblock
Sat Apr  1 18:50:52 2023 kern.info kernel: [   43.307836] F2FS-fs (sda128): Magic Mismatch, valid(0xf2f52010) - read(0x2e48937b)
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.308088] F2FS-fs (sda128): Can't find valid F2FS filesystem in 2th superblock
Sat Apr  1 18:50:52 2023 kern.warn kernel: [   43.308479] exFAT-fs (sda128): mounting with "discard" option, but the device does not support discard
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309111] exFAT-fs (sda128): invalid boot record signature
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309339] exFAT-fs (sda128): failed to read boot sector
Sat Apr  1 18:50:52 2023 kern.err kernel: [   43.309743] exFAT-fs (sda128): failed to recognize exfat type
Sat Apr  1 18:50:59 2023 user.notice nlbwmon: Reloading nlbwmon due to ifup of loopback (lo)
Sat Apr  1 18:51:05 2023 daemon.info procd: Instance wsdd2::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sat Apr  1 18:51:14 2023 user.notice firewall: Reloading firewall due to ifup of wan6 (eth1)
Sat Apr  1 18:51:14 2023 user.notice nlbwmon: Reloading nlbwmon due to ifup of wan6 (eth1)
Sat Apr  1 18:51:22 2023 kern.err kernel: [   73.411708] squashfs: Unknown parameter 'discard'
Sat Apr  1 18:51:22 2023 kern.err kernel: [   73.412231] /dev/sda1: Can't open blockdev

![lede error](https://user-images.githubusercontent.com/18095865/229262641-e0c91839-3023-4a0a-be2e-12ebd3de3ccb.jpg)

**Comment by potoo0** [comment]
你好，我也遇到这部分日志了，怎么解决的呀？
