### ISSUE TITLE
请问这个依赖问题怎么解决？

### ISSUE THREAD

**Issue by aheig** [coolsnowwolf/lede#11059]
反馈bug/问题模板，提建议请删除
内核
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
内核依赖问题
### (1) 具体问题

A：WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist

### (2) 路由器型号和固件版本

A：最新master   x86-64

### (3) 详细日志

A：WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist

**Comment by edhnt455** [comment]
出现同样问题
