### ISSUE TITLE
5.10内核刷死了，5.4是好的

### ISSUE THREAD

**Issue by qwerttvv** [coolsnowwolf/lede#11068]
https://github.com/coolsnowwolf/lede/commit/977bf86ccde81d4c4db5963e45d0eb92b239f6f2

机器是newifi d2，闭源驱动，新内核直接刷死

**Comment by licsber** [comment]
现在revert回去了 但是为啥呢 有日志吗 tty的

**Comment by yuanshus** [comment]
我也遇到同样问题，重新编译又不会改内核版本，有同志解决了这个问题吗？
