### ISSUE TITLE
L大大，树莓派3B，frp和kcptun编译不过啊，下载地址不对

### ISSUE THREAD

**Issue by caonimac** [coolsnowwolf/lede#1107]
https://github.com/fatedier/frp/releases/download/v0.21.0/frp_0.21.0_linux_.tar.gz

没有自动加arm或者arm64上去。

感谢感谢。

![QQ图片20190309120916](https://user-images.githubusercontent.com/35394132/54066770-f377dd00-4270-11e9-953b-dc45c0a3518a.png)

**Comment by caonimac** [comment]
wget 到dl目录也不行

**Comment by coolsnowwolf** [comment]
这两个都没有 arm8 的官方编译版本

**Comment by coolsnowwolf** [comment]
解决了frp

**Comment by caonimac** [comment]
感谢，下次编译时我再把kcptun的错误截图发上来。
