### ISSUE TITLE
K2P高格魔改，SSR +  OBS Studio无法实现youtube推流直播

### ISSUE THREAD

**Issue by ntgeralt** [coolsnowwolf/lede#1109]
padavan老毛子改华硕固件，只要开了游戏udp，则能正常推流。
k2p 18-12月魔改则怎么设置udp转发都无法实现youtube推流，提示无法连接服务器。
但电脑能打开youtube。应该udp没转发全。

**Comment by coolsnowwolf** [comment]
高恪没有 UDP 转发模块

**Comment by ntgeralt** [comment]
好的

**Comment by ntgeralt** [comment]
之前搞错，发现padavan tcp 1:65535  代理转发，不用开udp转发，也能推流。
