### ISSUE TITLE
R4S 最新代码编译后烧录 TF 不引导

### ISSUE THREAD

**Issue by BenjaminX** [coolsnowwolf/lede#11103]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新编译后的 R4S 固件，烧录 TF，开机不引导。

### (2) 路由器型号和固件版本

A：R4S + 最新 lede 代码

### (3) 详细日志

A：

**Comment by xcf13363175** [comment]
M68S 也是一样

**Comment by VIKINGYFY** [comment]
我也遇到了，R4S

**Comment by Travel2Here** [comment]
+1 完全没反应 只有电源灯亮…

**Comment by gswangmd-gssi** [comment]
今晚编译的R5S固件，也是不能启动！

**Comment by qyh214** [comment]
你们的内核分区是默认的32MB吗

**Comment by BenjaminX** [comment]
https://github.com/coolsnowwolf/lede/pull/11121

疑似已回滚，待测试。

**Comment by lysgwl** [comment]
> 今晚编译的R5S固件，也是不能启动！

你的R5s现在搞定了吗？刷istoreos就没问题，自编译的openwrt就是启动不了呢？不知道什么问题。
