### ISSUE TITLE
关于ShadowSocksR Plus+使用v2ray服务器得性能问题

### ISSUE THREAD

**Issue by ddvcx** [coolsnowwolf/lede#1110]
我之前编译得Lean大固件，使用v2ray客户端，打开youtube页面秒开， 4k流畅
现在用Lean大编译得潘多拉固件，自带得是ShadowSocksR Plus+，使用v2ray服务器，720p都经常要缓冲，而且打开youtube页面也要30秒以上
v2ray服务器和设置都没变过，mkcp+自动加密，路由器为Newifi-D2
请问怎样设置才能让ShadowSocksR Plus+用v2ray服务器和直接用v2ray一样流畅

**Comment by coolsnowwolf** [comment]
chrome 浏览器的问题，浏览器关闭 quic 即可

**Comment by ddvcx** [comment]
> chrome 浏览器的问题，浏览器关闭 quic 即可

谢谢大大回复，问题解决了
