### ISSUE TITLE
RK系列芯片卡刷以后均无法引导启动

### ISSUE THREAD

**Issue by VIKINGYFY** [coolsnowwolf/lede#11119]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
RK系列芯片均无法引导启动，怀疑是这个[提交](https://github.com/coolsnowwolf/lede/commit/bb084c1d09e7b81ba4eda974ab0d7abcd6e3a114)还未撤回导致的。
从这个[提交](https://github.com/coolsnowwolf/lede/commit/e9553e8101981f7283bc34dfe0244320c44fbef7)开始，RK系列就无法编译通过，最近撤回了2个相关改动后能稳定编译通过，但还是卡刷后无法引导启动（仅电源灯在亮，其他均没有亮）。

### (2) 路由器型号和固件版本

A：
R4S、R5C、R66S、R68S

### (3) 详细日志

A：

**Comment by BenjaminX** [comment]
同样的问题

**Comment by BenjaminX** [comment]
这个 patch 修改量不小，感觉需要具体适配检查花不少功夫了。

**Comment by VIKINGYFY** [comment]
> 这个 patch 修改量不小，感觉需要具体适配检查花不少功夫了。

我觉得直接撤回就行了呗，还省事😂

**Comment by Travel2Here** [comment]
不少人同样情况来反馈，希望共建者们给点回复，共同交流发现、解决问题~

**Comment by WYC-2020** [comment]
怀疑什么直接撤回 自己编译了再试就知道，确定了撤回某个就好了 直接告知提交这个commit的人就行，或者直接pr

**Comment by BenjaminX** [comment]
回滚修复了

**Comment by hyy-666** [comment]
现在最新的源码应该没有问题了吧？
