### ISSUE TITLE
R5S 编译错误

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#11112]
make[3]: Leaving directory '/home/gswangmd/lede/package/boot/arm-trusted-firmware-rockchip'
time: package/boot/arm-trusted-firmware-rockchip/rk3568/compile#0.17#0.02#0.16
make[3]: Entering directory '/home/gswangmd/lede/package/boot/uboot-envtools'
mkdir -p /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/gswangmd/lede/tmp/.root-copy.flock -c 'cp -fpR /home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-2023.01/.pkgdir/uboot-envtools/. /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.uboot-envtools_installed
echo "uboot-envtools" >> /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/pkginfo/uboot-envtools.default.install
make[3]: Leaving directory '/home/gswangmd/lede/package/boot/uboot-envtools'
time: package/boot/uboot-envtools/compile#0.26#0.07#0.27
make[3]: Entering directory '/home/gswangmd/lede/package/boot/arm-trusted-firmware-rockchip-vendor'
make[3]: Leaving directory '/home/gswangmd/lede/package/boot/arm-trusted-firmware-rockchip-vendor'
time: package/boot/arm-trusted-firmware-rockchip-vendor/rk3328/compile#0.19#0.00#0.18
make[3]: Entering directory '/home/gswangmd/lede/package/boot/uboot-rockchip'
rm -f /home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04/.built
touch /home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04/.built_check
make  -C /home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04 CROSS_COMPILE=aarch64-openwrt-linux-musl- DTC="/home/gswangmd/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.104/scripts/dtc/dtc" HOSTCC="gcc" HOSTCFLAGS="-O2 -I/home/gswangmd/lede/staging_dir/host/include -I/home/gswangmd/lede/staging_dir/hostpkg/include -I/home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/host/include -I/home/gswangmd/lede/staging_dir/host/include -I/home/gswangmd/lede/staging_dir/hostpkg/include -I/home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/host/include -std=gnu11" HOSTLDFLAGS="-L/home/gswangmd/lede/staging_dir/host/lib -L/home/gswangmd/lede/staging_dir/hostpkg/lib -L/home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/host/lib" LOCALVERSION="-OpenWrt-r5892-8a9cd422f" STAGING_PREFIX="/home/gswangmd/lede/staging_dir/host" PKG_CONFIG_PATH="/home/gswangmd/lede/staging_dir/host/lib/pkgconfig" PKG_CONFIG_LIBDIR="/home/gswangmd/lede/staging_dir/host/lib/pkgconfig" PKG_CONFIG_EXTRAARGS="--static" V='' BL31=/home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31.elf ROCKCHIP_TPL=/home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04/rk3568_ddr_1560MHz_v1.13.bin
make[4]: Entering directory '/home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04'
  UPD     include/config/uboot.release
  UPD     include/generated/version_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
make -f ./scripts/Makefile.build obj=scripts/dtc
  HOSTCC  tools/mkenvimage.o
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/fit_image.o
  HOSTCC  tools/image-host.o
  HOSTCC  tools/dumpimage.o
  HOSTLD  tools/dumpimage
  HOSTCC  tools/mkimage.o
  HOSTLD  tools/mkimage
  CC      cmd/version.o
  AR      cmd/built-in.o
  CC      common/fdt_support.o
  AR      common/built-in.o
  CC      env/common.o
  AR      env/built-in.o
  CC      lib/efi_loader/dtbdump.o
  LD      lib/efi_loader/dtbdump_efi.so
  OBJCOPY lib/efi_loader/dtbdump.efi
  CC      lib/efi_loader/initrddump.o
  LD      lib/efi_loader/initrddump_efi.so
  OBJCOPY lib/efi_loader/initrddump.efi
  CC      lib/smbios.o
  AR      lib/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  RELOC   u-boot-nodtb.bin
  CAT     u-boot-dtb.bin
  COPY    u-boot.bin
  SYM     u-boot.sym
  CC      spl/common/spl/spl.o
  AR      spl/common/spl/built-in.o
  CC      spl/common/fdt_support.o
  AR      spl/common/built-in.o
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl-nodtb.bin
  CAT     spl/u-boot-spl-dtb.bin
  COPY    spl/u-boot-spl.bin
  SYM     spl/u-boot-spl.sym
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  BINMAN  .binman_stamp
Wrote map file './simple-bin.map' to show errors
binman: Node '/binman/simple-bin/fit': subnode 'images/@atf-SEQ': Failed to read ELF file: Python: No module named 'elftools'
make[4]: *** [Makefile:1108: .binman_stamp] Error 1
make[4]: Leaving directory '/home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04'
make[3]: *** [Makefile:334: /home/gswangmd/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2023.04/.built] Error 2
make[3]: Leaving directory '/home/gswangmd/lede/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r5s-rk3568/compile#3.80#0.37#4.02
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r5s-rk3568).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:110: /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:231: world] Error 2
gswangmd@WMD-HOME:~/lede$

**Comment by Travel2Here** [comment]
最近大家都是这个问题，装好新增的依赖，make dirclean（不是make clean），j1编译。尝试一下，我是这样就正常了。

**Comment by gswangmd-gssi** [comment]
我试试，谢谢！

**Comment by Travel2Here** [comment]
> > 最近大家都是这个问题，装好新增的依赖，make dirclean（不是make clean），j1编译。尝试一下，我是这样就正常了。
> 
> 你好·，如何安装新增的依赖呢

小哥 认真看commit的描述 ，或者看首页说明。
