### ISSUE TITLE
最近MTK开源的似乎都没了无线?

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#11123]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
CR660X  JDCloud_re-sp-01b  小米4A千兆版，新编译的 都是没无线，怎么回事？  小米/红米2100  闭源的正常有无线  

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by zzh151223** [comment]
> 都没人遇到我这个情况吗？为什么我编译的都没了无线，刷回以前的版本就有无线了

我的是有无线但用不了，扫不了信号页改不了频段，和没网卡一样

**Comment by aiamadeus** [comment]
lean 干的，我晚点给你改回来。

**Comment by lztxi** [comment]
AX6S 也有这样的情况，已经在用老版本了

**Comment by yuzhe1129** [comment]
怎么回事……

**Comment by ttmi9002** [comment]
要用开源无线驱动，需要勾选以前的无线驱动，并且不MTK HW的相关项都去掉，就能恢复用之前的开源无线驱动

**Comment by ttmi9002** [comment]
要用开源无线驱动，需要勾选以前的无线驱动，并且把MTK HW的相关项都去掉，就能恢复用之前的开源无线驱动

**Comment by yuzhe1129** [comment]
> 要用开源无线驱动，需要勾选以前的无线驱动，并且把MTK HW的相关项都去掉，就能恢复用之前的开源无线驱动

以前都是默认不用选的啊，现在开源驱动都要勾选了？
