### ISSUE TITLE
tun.ko is missing

### ISSUE THREAD

**Issue by sheiy** [coolsnowwolf/lede#11130]
请教下编译官方的固件(https://github.com/openwrt/openwrt/tree/openwrt-22.03)添加kmod-tun后提示这个，是需要额外再添加啥呢？
<img width="998" alt="image" src="https://user-images.githubusercontent.com/12210038/232957108-8d19101f-a4c8-4662-bc07-cbf7afd21e24.png">

**Comment by WYC-2020** [comment]
这恐怕你的去官方问，这边编译都是没问题的，看有人编译官方的没，看他们有没遇到
