### ISSUE TITLE
已安装mt7921e驱动但无法使用

### ISSUE THREAD

**Issue by zzh151223** [coolsnowwolf/lede#11131]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：最新版6.1.22已安装mt7921e驱动，但无线里面所有东西都是空的
![image](https://user-images.githubusercontent.com/47099284/232983222-5b1c19b6-255c-4ec9-a5c6-46307759ce62.png)
这个是自动生成的无线配置
![image](https://user-images.githubusercontent.com/47099284/232983295-455d8a18-ebf3-4167-b416-c9189c0987b4.png)
这个是我手动根据pci设备写入的配置
![image](https://user-images.githubusercontent.com/47099284/232983659-5956b815-5326-490d-a133-985935d738d0.png)
![image](https://user-images.githubusercontent.com/47099284/232983393-4e270fcc-d027-49b2-a0e1-8c624eaf3ac5.png)
都无法使用

### (2) 路由器型号和固件版本

A：x86_6.1.24

### (3) 详细日志

A：

**Comment by aiamadeus** [comment]
很明显你没有选 wpad-openssl

**Comment by zzh151223** [comment]
> 很明显你没有选 wpad-openssl

新版本我不知道，老版本就算没装也能选模式、频宽什么的，也能搜索信号，只是连不上而已，现在是什么都搞不了，新版本改了？
