### ISSUE TITLE
强烈要求ssr增加域名白名单

### ISSUE THREAD

**Issue by yunmi323** [coolsnowwolf/lede#1113]
强烈要求ssr增加域名白名单！强烈要求ssr增加域名白名单！强烈要求ssr增加域名白名单！他大爷gov。cn网站有时候自动翻，一翻就被档在外面，只能停止ssr！

**Comment by coolsnowwolf** [comment]
早已添加了，自动白名单，更新下版本即可

**Comment by BROBIRD** [comment]
3月22日编译的版本，依然没有域名白名单？？？？

**Comment by 404user** [comment]
我也想要添加白名单
