### ISSUE TITLE
OpenWRT在Actions编译过程中因磁盘空间不足从而编译失败，如何清理磁盘空间？

### ISSUE THREAD

**Issue by AkarinLiu** [coolsnowwolf/lede#11159]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
### (1) 具体问题

A：我运行了两次Action，但是以失败告终，发生如下错误：
- You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB

### (2) 路由器型号和固件版本

A：X86_64

### (3) 详细日志

A：[logs_4.zip](https://github.com/coolsnowwolf/lede/files/11340614/logs_4.zip)

### (4) 项目地址
A: https://github.com/AkarinWRT/openwrt.git

**Comment by AkarinLiu** [comment]
@coolsnowwolf

**Comment by aiamadeus** [comment]
、

**Comment by elonj** [comment]
遇到同样问题，请问你是怎么解决的？

**Comment by AkarinLiu** [comment]
@elonj 发现GitHub是有磁盘容量限制的（14GB），我编译的太大，GitHub没法继续编译了。所以我直接在codespace预先更新软件包，然后运行`make menuconfig`配置好，最后交给GitHub Actions，让它自动编译。

**Comment by elonj** [comment]
> @elonj 发现GitHub是有磁盘容量限制的（14GB），我编译的太大，GitHub没法继续编译了。所以我直接在codespace预先更新软件包，然后运行`make menuconfig`配置好，最后交给GitHub Actions，让它自动编译。

我试试，谢谢

**Comment by xuexijiaoben** [comment]
> @elonj 发现GitHub是有磁盘容量限制的（14GB），我编译的太大，GitHub没法继续编译了。所以我直接在codespace预先更新软件包，然后运行`make menuconfig`配置好，最后交给GitHub Actions，让它自动编译。

请问这个具体怎么操作呀，codespace这个是啥，谢谢啦

**Comment by AkarinLiu** [comment]
Codespace 是GitHub基于CodeServer的在线IDE，Codespace会打开一个网页端IDE，不需要安装杂七杂八的软件。

________________________________
