### ISSUE TITLE
编译前期配置问题 求助。

### ISSUE THREAD

**Issue by lbbboy** [coolsnowwolf/lede#1115]
1.wifi国家代码在哪里修改？默认是00 查了很多都不行。求助。
2.R8 网络存储加速的包在R9里是哪个？R9 SMB太不稳定，最快就能跑50+MB/S。R8 100MB/S。
3.aria2 R8 R9速度都很慢。这个怎么解决？tracker 已加。

**Comment by Zxilly** [comment]
aria2的bt协议，没人上传你哪里有下载
