### ISSUE TITLE
最新6.1.25源码无法驱动QCNFA765

### ISSUE THREAD

**Issue by Y-ZD-heheka** [coolsnowwolf/lede#11164]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：使用lede最新6.1.25源码无法驱动QCNFA765网卡

### (2) 路由器型号和固件版本

A：X86_64，kernel 6.1.25，PVE虚拟机直通QCNFA765

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/57650701/235283353-10c0f3e4-b56e-4600-93f2-c70d1f0cac74.png)
![image](https://user-images.githubusercontent.com/57650701/235283360-f8ca9c88-1c51-4313-952b-8073d03d8539.png)
![image](https://user-images.githubusercontent.com/57650701/235283369-d9b59664-611d-46ec-8578-12642075accc.png)
无线中点扫描没有东西
![image](https://user-images.githubusercontent.com/57650701/235283394-21a1cf10-4f37-47d2-b923-3ac986623ded.png)
选择的固件
![image](https://user-images.githubusercontent.com/57650701/235283413-1a822a68-bec7-4ab9-b181-d4d9822388d4.png)
![image](https://user-images.githubusercontent.com/57650701/235283421-618fcdae-3730-459a-902c-e996142b7582.png)

**Comment by Y-ZD-heheka** [comment]
![image](https://user-images.githubusercontent.com/57650701/235283614-d63f4f8e-4d16-4c4c-a017-018106c1ae48.png)
![image](https://user-images.githubusercontent.com/57650701/235283619-e769f35e-cce0-4169-9e7c-5556a9cc67d1.png)
换上QCNFA765后内存占用高了30MB

**Comment by Y-ZD-heheka** [comment]
大佬还是驱动不起来啊

**Comment by Kisoul** [comment]
> 大佬还是驱动不起来啊

解决了吗？怎么解决的？

**Comment by Y-ZD-heheka** [comment]
> > 大佬还是驱动不起来啊
> 
> 解决了吗？怎么解决的？

我现在用immortal，把ath11k pci相关的驱动选上就能驱动
