### ISSUE TITLE
[已解決]URL 访问请求，下载失败，鏡像也失敗

### ISSUE THREAD

**Issue by sinaamos** [coolsnowwolf/lede#11160]
## 1.关于你要提交的问题
编译错误，无法访问URL
Q：是否搜索了issue (使用 "x" 选择)
* [× ] 没有类似的issue

### (1) 具体问题

A：PVE虚拟机ubuntu server22.04，编译失败，查询过错误，都是和下载失败，下载错误有关。
当需要从URL下载时就出些一些404错误导致下载失败。
已是全局科学环境。

### (2) 路由器型号和固件版本

A：X86_64， generic

### (3) 详细日志

A：
`**curl: (22) The requested URL returned error: 404**
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/upx-3.96.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
**Download failed.**
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/upx-3.96.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
**No more mirrors to try - giving up**.
upx-3.96.tar.xz: Download from https://github.com/upx/upx.git failed
IncompleteRead(0 bytes read)
Checking out files from the git repository...
Cloning into 'upx-3.96'...
remote: Enumerating objects: 37245, done.
remote: Counting objects: 100% (637/637), done.
remote: Compressing objects: 100% (271/271), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 4340 bytes of body are still expected
`

**Comment by aiamadeus** [comment]
你网络问题，真正下载地址在前面。

**Comment by sinaamos** [comment]
> 你网络问题，真正下载地址在前面。

google了下這個問題，我下在了這個文件，然後上傳到/lede/dl 不知道行不行

**Comment by sinaamos** [comment]
下載該文件，上傳到/lede/dl后編譯成功了
