### ISSUE TITLE
日志里面全是这个，是被黑了么

### ISSUE THREAD

**Issue by helllkz** [coolsnowwolf/lede#11186]
X86的，一般重启一天以内就有了，ps看进程还是有ash啥的，因为已经重启了，目前还没有
![image](https://user-images.githubusercontent.com/14025168/236628875-cf91554b-abe0-40aa-afd4-16bebd28789c.png)

**Comment by helllkz** [comment]
看了下，系统定时任务里面有这个，每分钟执行一次，不知道是哪儿来的

**Comment by WYC-2020** [comment]
那肯定是什么垃圾插件 加入的呗，打开脚本看下在干嘛，看有特征没知道是那个软件

**Comment by helllkz** [comment]
就是没这个文件，都不知道哪儿来的，反正先删除定时任务
