### ISSUE TITLE
开启tcp fastopen出错

### ISSUE THREAD

**Issue by rule2c** [coolsnowwolf/lede#1120]
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8640]: initializing ciphers... chacha20-ietf-poly1305
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8640]: listening at 0.0.0.0:1234
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8640]: tcp port reuse enabled
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8640]: running from root user
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: initializing ciphers... chacha20-ietf-poly1305
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: listening at 0.0.0.0:1234
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: UDP relay enabled
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: udp port reuse enabled
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: TCP relay disabled
Sun Mar 17 13:11:03 2019 daemon.info /usr/bin/ss-redir[8665]: running from root user
Sun Mar 17 13:11:03 2019 daemon.info pdnsd[8683]: pdnsd-1.2.9b-par starting.
Sun Mar 17 13:11:04 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sun Mar 17 13:11:04 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sun Mar 17 13:11:44 2019 daemon.err /usr/bin/ss-redir[8640]: failed to set TCP_FASTOPEN_CONNECT

**Comment by hcym** [comment]
怪了，大雕的能开fasttcp，就是没什么效果，官方op编译的死活打不开这个功能
