### ISSUE TITLE
Linksys EA8500固件可用空间不足，/ROM 和/overly目录能否扩容。

### ISSUE THREAD

**Issue by Hirro029** [coolsnowwolf/lede#11225]
1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
没有类似的issue

2. 详细叙述
(1) 具体问题
A：Linksys EA8500 自定义包编译的的固件刷机/overly目录可用空间只有不到1M，编译时选择软件包超过32M的固件无法刷机。/ROM 和/overly目录能否扩容。

(2) 路由器型号和固件版本
A：Linksys EA8500

(3) 详细日志
A：![无标题](https://github.com/coolsnowwolf/lede/assets/134217849/48d3d2c5-1785-4aa4-97e6-78cc18c3c133)

**Comment by coolsnowwolf** [comment]
这个是官方 uboot 定义的，不可改变

**Comment by WYC-2020** [comment]
别玩硬路由了，硬路由很多局限性的，特别是在每个分区的大小上面，玩软路由吧 几百块的事哈哈

**Comment by Hirro029** [comment]
> 这个是官方 uboot 定义的，不可改变

好的，谢谢！
