### ISSUE TITLE
drivers/net/phy/ar8327.ko] undefined!

### ISSUE THREAD

**Issue by vipboddy** [coolsnowwolf/lede#11250]
ERROR: modpost: missing MODULE_LICENSE() in drivers/net/phy/ar8327.o
ERROR: modpost: "ar8xxx_sw_set_flush_arl_table" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_get_arl_table" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_get_arl_age_time" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_set_arl_age_time" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_get_mirror_source_port" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_set_mirror_source_port" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_get_mirror_monitor_port" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_set_mirror_monitor_port" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_get_mirror_tx_enable" [drivers/net/phy/ar8327.ko] undefined!
ERROR: modpost: "ar8xxx_sw_set_mirror_tx_enable" [drivers/net/phy/ar8327.ko] undefined!
WARNING: modpost: suppressed 32 unresolved symbol warnings because there were too many)
make[5]: *** [scripts/Makefile.modpost:133: modules-only.symvers] Error 1
make[5]: *** Deleting file 'modules-only.symvers'
make[4]: *** [Makefile:1826: modules] Error 2
make[4]: Leaving directory '/home/lucky/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.112'
make[3]: *** [Makefile:29: /home/lucky/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.112/.modules] Error 2
make[3]: Leaving directory '/home/lucky/lede/target/linux/x86'
make[2]: *** [Makefile:11: compile] Error 2
make[2]: Leaving directory '/home/lucky/lede/target/linux'
time: target/linux/compile#49.62#9.34#58.43
    ERROR: target/linux failed to build.
make[1]: *** [target/Makefile:30: target/linux/compile] Error 1
make[1]: Leaving directory '/home/lucky/lede'
make: *** [/home/lucky/lede/include/toplevel.mk:231: target/compile] Error 2

**Comment by WYC-2020** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/34025388/d77057cd-395d-477e-9ba1-c080dc4c285d)
![image](https://github.com/coolsnowwolf/lede/assets/34025388/3adb1787-8bac-4c72-ad81-c49fbabd479a)
如此修复，其他几个内核一样这样修复，应该是提交不完全
