### ISSUE TITLE
能否将luci更新到官方openwrt的最新版本

### ISSUE THREAD

**Issue by lin20121221** [coolsnowwolf/lede#1126]

**Comment by hcym** [comment]
确实如此，wireguard的二维码不能显示，官方的可以，不过官方的比较花俏，感觉比老主题费劲

**Comment by coolsnowwolf** [comment]
官方的luci 那个回滚机制我很讨厌，而且更费资源，暂时没觉得有必要性

**Comment by fuqiang03** [comment]
如果机器性能够 , 可以尝试,但是10个插件得跪一半,

**Comment by lin20121221** [comment]
主要是喜欢新版本luci的状态页显示内容

**Comment by fuqiang03** [comment]
可以自己改啊  新版的 对index面页进行了拆分 和归类 修改难度不打

**Comment by lin20121221** [comment]
嗯，有空试试，谢谢

**Comment by fuqiang03** [comment]
![QQ截图20190329150349](https://user-images.githubusercontent.com/26851715/55215637-6c959f00-5235-11e9-8a25-c2a3371468a8.png)
看了下 从外观上看 细微的变化 直接3个插件跪下了

**Comment by uglee** [comment]
官方那个机制很讨厌，我也不喜欢。
