### ISSUE TITLE
云编译6.1内核变成了5.15

### ISSUE THREAD

**Issue by Wyatt323** [coolsnowwolf/lede#11276]
之前按照下面的配置可以编译出6.1内核的固件，但是最近好像编译出来的都是5.15的
![image](https://github.com/coolsnowwolf/lede/assets/71224625/ede2a080-ce99-4e53-aed9-b37394c7ece6)

**Comment by aiamadeus** [comment]
https://github.com/coolsnowwolf/lede/commit/c79f780fca370ab98c3b2158c2f1129c5b91ee11
自己看，取消 testing 才是 6.1
