### ISSUE TITLE
Lede OpenWrt version.

### ISSUE THREAD

**Issue by butinhi** [coolsnowwolf/lede#11282]
Why I built Lede OpenWrt is SNAPSHOT? I did not see it before

<a href="https://ibb.co/CHdX23H"><img src="https://i.ibb.co/4VyDdnV/A-nh-chu-p-ma-n-hi-nh-2023-06-07-231603.png" alt="A-nh-chu-p-ma-n-hi-nh-2023-06-07-231603" border="0"></a>

**Comment by WYC-2020** [comment]
Compiled by yourself? Check to see if default-settings is installed. This package will modify the version information. It is selected by default. I don’t know how you did it.
![image](https://github.com/coolsnowwolf/lede/assets/34025388/47ce5ea0-bd2b-4ae2-bda9-45d8307ca9c1)

**Comment by butinhi** [comment]
> Compiled by yourself? Check to see if default-settings is installed. This package will modify the version information. It is selected by default. I don’t know how you did it. ![image](https://user-images.githubusercontent.com/34025388/244245166-47ce5ea0-bd2b-4ae2-bda9-45d8307ca9c1.png)

Yes, I complied by myself. I changed default language to auto from zzz-default-settings and luci-base.

**Comment by butinhi** [comment]
> Compiled by yourself? Check to see if default-settings is installed. This package will modify the version information. It is selected by default. I don’t know how you did it. ![image](https://user-images.githubusercontent.com/34025388/244245166-47ce5ea0-bd2b-4ae2-bda9-45d8307ca9c1.png)

I see it. I unchecked it from menu config. But if checked it some settings will be default when upgrade new fw.
