### ISSUE TITLE
最近R68S云编译出错（已解决）

### ISSUE THREAD

**Issue by lwb1978** [coolsnowwolf/lede#11283]
最近云编译R68S估计出错，同样的编译环境和config在4月初以前编译没任何问题，错误日志片段如下：
make -f ./scripts/Makefile.build obj=scripts/dtc
  CC      env/common.o
  AR      env/built-in.o
  CC      lib/efi_loader/dtbdump.o
  LD      lib/efi_loader/dtbdump_efi.so
  OBJCOPY lib/efi_loader/dtbdump.efi
  CC      lib/efi_loader/initrddump.o
  LD      lib/efi_loader/initrddump_efi.so
  OBJCOPY lib/efi_loader/initrddump.efi
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  RELOC   u-boot-nodtb.bin
  CAT     u-boot-dtb.bin
  COPY    u-boot.bin
  SYM     u-boot.sym
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  BINMAN  .binman_stamp
binman: Node '/binman/simple-bin/fit': subnode 'images/@atf-SEQ': Failed to read ELF file: Python: No module named 'elftools'
Wrote map file './simple-bin.map' to show errors
make[4]: *** [Makefile:1108: .binman_stamp] Error 1
make[3]: *** [Makefile:325: /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-r66s-rk3568/u-boot-2023.04/.built] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-r66s-rk3568/u-boot-2023.04'
make[3]: Leaving directory '/workdir/openwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/r66s-rk3568/compile#2.57#0.83#3.60
    ERROR: package/boot/uboot-rockchip failed to build (build variant: r66s-rk3568).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by WYC-2020** [comment]
真是伸手党，你稍微用elftools关键字在issue搜索一下就能找到解决方法的

https://github.com/coolsnowwolf/lede/issues/11209#issue-1708890606

**Comment by lwb1978** [comment]
> 真是伸手党，你稍微用elftools关键字在issue搜索一下就能找到解决方法的
> 
> [#11209 (comment)](https://github.com/coolsnowwolf/lede/issues/11209#issue-1708890606)

谢谢，添加python3-pyelftools依赖后已解决

**Comment by chika0801** [comment]
> > 真是伸手党，你稍微用elftools关键字在issue搜索一下就能找到解决方法的
> > [#11209 (comment)](https://github.com/coolsnowwolf/lede/issues/11209#issue-1708890606)
> 
> 谢谢，添加python3-pyelftools依赖后已解决

请问我是编译R66S遇到和你一样的报错。你说的` 添加python3-pyelftools依赖后已解决`

请问具体的命令，方法能分享一下吗？
