### ISSUE TITLE
SSRPLUS+ 回国配置文件

### ISSUE THREAD

**Issue by stevenzhu25** [coolsnowwolf/lede#1129]
您好，

请问现在如果要添加其他网站进入“海外用户回国模式”，还是直接修改"/etc/dnsmasq.oversea/overaea_list.conf" 嘛？

我尝试修改了此文件并且添加了如下4行
```
server=/bilibili.com/127.0.0.1#5335
server=/hdslb.com/127.0.0.1#5335
ipset=/hdslb.com/oversea
ipset=/bilibili.com/oversea
```
之后重启了DNSMASQ和Shadowsocksr… 但是仍旧无法用SSR访问哔哩哔哩…

**Comment by 505575853** [comment]
[使用这个版本](https://github.com/505575853/lede/tree/R9/package/lean/luci-app-ssr-plus)

**Comment by stevenzhu25** [comment]
您好 ，@505575853 这版本编译不动哇

**Comment by stevenzhu25** [comment]
@505575853  我把整个系统重新都编译了....弄完更新就好了

多谢.
