### ISSUE TITLE
编译出来的K2P不能用，求解

### ISSUE THREAD

**Issue by Zhang-Shijun** [coolsnowwolf/lede#1130]
编译出来的K2P固件，能通过breed刷进去，路由器的灯为蓝色，用网线连接路由器也能够获取到ip地址，但是呢，无论如何都进不了后台，尝试使用telnet，ssh都连接不上。浏览器输入192.168.1.1进不去，chrome，safari浏览器，Edge都换过。 当然，更加没有wifi。 信号都没有，估计是没有无线驱动的。

有没有哪个兄弟自己编译的可以用的。

**Comment by Zhang-Shijun** [comment]
忘了说，我用的是斐讯分区刷进去的。

**Comment by 505575853** [comment]
因为没有无线驱动，还没开源

**Comment by Zhang-Shijun** [comment]
无线驱动没有，也不至于不能进后台吧

**Comment by cnZary** [comment]
能用，但是没无线
