### ISSUE TITLE
6.1.30+以后遇到一个ipv6相关的内核core，不知道怎么解

### ISSUE THREAD

**Issue by littoy** [coolsnowwolf/lede#11302]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：内核异常

### (2) 路由器型号和固件版本

A：intel 7505 x86_64 + pve kvm host

### (3) 详细日志

A：
Sun Jun 11 23:02:41 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:02:41 2023 kern.info kernel: [39210.778735] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:02:41 2023 kern.info kernel: [39210.780515] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:03:01 2023 kern.info kernel: [39231.230004] igc 0000:05:00.0 eth5: NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
Sun Jun 11 23:03:01 2023 kern.info kernel: [39231.232791] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:03:01 2023 kern.info kernel: [39231.234056] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:03:01 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:03:15 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:03:15 2023 kern.info kernel: [39245.340970] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:03:15 2023 kern.info kernel: [39245.342422] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:03:18 2023 kern.info kernel: [39247.621179] igc 0000:05:00.0 eth5: NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
Sun Jun 11 23:03:18 2023 kern.info kernel: [39247.623059] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:03:18 2023 kern.info kernel: [39247.623981] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:03:18 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:03:49 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:03:49 2023 kern.info kernel: [39278.783265] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:03:49 2023 kern.info kernel: [39278.784302] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:03:52 2023 kern.info kernel: [39282.107399] igc 0000:05:00.0 eth5: NIC Link is Up 2500 Mbps Full Duplex, Flow Control: RX/TX
Sun Jun 11 23:03:52 2023 kern.info kernel: [39282.109761] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:03:52 2023 kern.info kernel: [39282.111063] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:03:52 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:16:47 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:16:47 2023 kern.info kernel: [40056.879874] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:16:47 2023 kern.info kernel: [40056.881702] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:16:49 2023 kern.info kernel: [40059.088058] igc 0000:05:00.0 eth5: NIC Link is Up 10 Mbps Half Duplex, Flow Control: None
Sun Jun 11 23:16:49 2023 kern.info kernel: [40059.090302] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:16:49 2023 kern.info kernel: [40059.091758] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:16:49 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:16:50 2023 kern.info kernel: [40059.511731] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:16:50 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:16:50 2023 kern.info kernel: [40060.099637] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:16:54 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:16:54 2023 kern.info kernel: [40063.523816] igc 0000:05:00.0 eth5: NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
Sun Jun 11 23:16:54 2023 kern.info kernel: [40063.524879] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:16:54 2023 kern.info kernel: [40063.525354] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:17:18 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:17:18 2023 kern.info kernel: [40087.994321] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:17:18 2023 kern.info kernel: [40087.995991] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:17:20 2023 kern.info kernel: [40090.230494] igc 0000:05:00.0 eth5: NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX
Sun Jun 11 23:17:20 2023 kern.info kernel: [40090.232615] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:17:20 2023 kern.info kernel: [40090.233612] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:17:20 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:17:23 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:17:23 2023 kern.info kernel: [40093.174017] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:17:23 2023 kern.info kernel: [40093.174883] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:17:27 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:17:27 2023 kern.info kernel: [40096.574134] igc 0000:05:00.0 eth5: NIC Link is Up 2500 Mbps Full Duplex, Flow Control: RX/TX
Sun Jun 11 23:17:27 2023 kern.info kernel: [40096.575504] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:17:27 2023 kern.info kernel: [40096.576213] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:21:46 2023 kern.info kernel: [40355.969080] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:21:46 2023 kern.info kernel: [40355.971393] br-switch: port 6(eth5) entered disabled state
Sun Jun 11 23:21:46 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:21:48 2023 daemon.notice netifd: Network device 'eth5' link is up
Sun Jun 11 23:21:48 2023 kern.info kernel: [40358.172964] igc 0000:05:00.0 eth5: NIC Link is Up 10 Mbps Half Duplex, Flow Control: None
Sun Jun 11 23:21:48 2023 kern.info kernel: [40358.174528] br-switch: port 6(eth5) entered blocking state
Sun Jun 11 23:21:48 2023 kern.info kernel: [40358.175263] br-switch: port 6(eth5) entered forwarding state
Sun Jun 11 23:21:49 2023 kern.info kernel: [40359.116622] igc 0000:05:00.0 eth5: NIC Link is Down
Sun Jun 11 23:21:49 2023 daemon.notice netifd: Network device 'eth5' link is down
Sun Jun 11 23:21:49 2023 kern.info kernel: [40359.176511] br-switch: port 6(eth5) entered disabled state
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.484929] ------------[ cut here ]------------
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.485419] WARNING: CPU: 1 PID: 19 at inet_sock_destruct+0x194/0x1c0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.485879] Modules linked in: pppoe ppp_async l2tp_ppp i915 wireguard video sch_fq_pie pppox ppp_mppe ppp_generic mt7921e mt7921_common mt7915e mt76_connac_lib mt76 mac80211 libchacha20poly1305 ipt_REJECT curve25519_x86_64 chacha_x86_64 cfg80211 ax88179_178a zstd xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_socket xt_recent xt_quota xt_policy xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_iprange xt_hl xt_helper xt_hashlimit xt_esp xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_cgroup xt_bpf xt_addrtype xt_TPROXY xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_IPMARK xt_HL xt_FLOWOFFLOAD xt_DSCP xt_CT xt_CLASSIFY wmi via_velocity usbnet ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda tulip ts_fsm ts_bm tcp_bbr slhc sch_pie sch_cake rtl8150 r8168 r8152 r8125 poly1305_x86_64 pcnet32 nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.485925]  nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_log_syslog nf_flow_table nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast ts_kmp nf_conntrack_amanda nf_conncount mlx5_core mlx4_en mlx4_core mdev macvlan lzo_rle lzo libcurve25519_generic libchacha ipvlan iptable_raw iptable_nat iptable_mangle iptable_filter ipt_ah ipt_ECN ip_tables iommu_v2 igc iavf i40e forcedeth e1000e drm_display_helper drm_buddy crc_ccitt compat_xtables compat cls_flower br_netfilter bnx2x bnx2 alx act_vlan 8139too 8139cp ntfs3 cls_bpf act_bpf sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact configs sg evdev i2c_dev cryptodev xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.491026]  ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ipmac ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set st ip6table_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6t_NPT ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 nfsv4 nfsd nfs bonding ip_gre gre ixgbe igbvf e1000 amd_xgbe mdio_devres dummy sit mdio l2tp_netlink l2tp_core udp_tunnel ip6_udp_tunnel ipcomp6 xfrm6_tunnel esp6 ah6 xfrm4_tunnel ipcomp esp4 ah4 ipip tunnel6 tunnel4 ip_tunnel udp_diag tcp_diag raw_diag inet_diag rpcsec_gss_krb5 auth_rpcgss veth tun nbd xfrm_user xfrm_ipcomp af_key xfrm_algo virtiofs fuse lockd sunrpc grace hfs cifs oid_registry cifs_md4 cifs_arc4 asn1_decoder dns_resolver md_mod nls_utf8 nls_cp950 nls_cp936 ena shortcut_fe_ipv6 shortcut_fe crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha512_ssse3 sha512_generic sha1_ssse3
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.496627]  sha1_generic seqiv jitterentropy_rng drbg md5 hmac echainiv des_generic libdes deflate cts cmac authencesn authenc arc4 crypto_acompress nls_iso8859_1 nls_cp437 uas sdhci_pltfm xhci_plat_hcd fsl_mph_dr_of ehci_platform ehci_fsl igb vfat fat exfat btrfs zstd_decompress zstd_compress zstd_common xxhash xor raid6_pq lzo_decompress lzo_compress dm_mirror dm_region_hash dm_log dm_crypt dm_mod dax button_hotplug mii libphy tpm cbc sha256_ssse3 sha256_generic libsha256 encrypted_keys trusted
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.505736] CPU: 1 PID: 19 Comm: ksoftirqd/1 Not tainted 6.1.33 #0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.506316] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.16.1-0-g3208b098f51a-prebuilt.qemu.org 04/01/2014
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.507011] RIP: 0010:inet_sock_destruct+0x194/0x1c0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.507501] Code: bc 24 40 01 00 00 e8 db e3 ef ff 49 8b bc 24 88 00 00 00 e8 ce e3 ef ff 5b 41 5c 5d c3 4c 89 e7 e8 51 4c ed ff e9 70 ff ff ff <0f> 0b eb c3 0f 0b 41 8b 84 24 54 01 00 00 85 c0 74 9d 0f 0b 41 8b
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.509215] RSP: 0018:ffffc900000afda8 EFLAGS: 00010206
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.509721] RAX: 0000000000000b00 RBX: ffff88800c25ccc0 RCX: 0000000000000007
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.510258] RDX: 0000000000000000 RSI: 0000000000000b00 RDI: ffff88800c25ccc0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.511171] RBP: ffffc900000afdb8 R08: ffff88800954b500 R09: 000000000020000f
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.512245] R10: 0000000040000000 R11: 0000000000000002 R12: ffff88800c25cc00
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.512986] R13: ffff888002d31540 R14: ffffc900000afe28 R15: ffff88807dd253f8
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.514111] FS:  0000000000000000(0000) GS:ffff88807dd00000(0000) knlGS:0000000000000000
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.517487] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.518175] CR2: 00007f46611b84c0 CR3: 000000000240a006 CR4: 0000000000370ee0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.518784] Call Trace:
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.519313]  <TASK>
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.519657]  ? show_regs.part.0+0x1e/0x20
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.520042]  ? show_regs.cold+0x8/0xd
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.520448]  ? __warn+0x72/0xc0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.520839]  ? inet_sock_destruct+0x194/0x1c0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.521371]  ? report_bug+0xf1/0x140
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.521737]  ? handle_bug+0x46/0x80
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.522087]  ? exc_invalid_op+0x1d/0x70
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.522467]  ? asm_exc_invalid_op+0x1f/0x30
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.522851]  ? inet_sock_destruct+0x194/0x1c0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.523277]  inet6_sock_destruct+0x1a/0x20
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.523651]  __sk_destruct+0x27/0x180
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.523995]  rcu_core+0x28f/0x6a0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.524367]  rcu_core_si+0xd/0x10
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.524701]  __do_softirq+0xc1/0x1ec
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.525155]  run_ksoftirqd+0x28/0x40
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.525517]  smpboot_thread_fn+0xdf/0x1d0
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.525862]  kthread+0xe2/0x110
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.526222]  ? sort_range+0x30/0x30
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.526538]  ? kthread_complete_and_exit+0x20/0x20
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.526893]  ret_from_fork+0x1f/0x30
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.527210]  </TASK>
Mon Jun 12 08:06:15 2023 kern.warn kernel: [71823.527448] ---[ end trace 0000000000000000 ]---
Mon Jun 12 08:11:06 2023 authpriv.info dropbear[5153]: Child connection from 192.168.125.32:50767
Mon Jun 12 08:11:06 2023 authpriv.notice dropbear[5153]: Pubkey auth succeeded for 'root' with ssh-rsa key SHA256:37RoS1zkDfuYSTf+3aQTaROzT0I6Y68UsJ0ccGWnfio from 192.168.125.32:50767
Mon Jun 12 08:12:19 2023 daemon.notice ttyd[10753]: [2023/06/12 08:12:19:8845] N: rops_handle_POLLIN_netlink: DELADDR
Mon Jun 12 08:12:19 2023 daemon.notice ttyd[10753]: [2023/06/12 08:12:19:8871] N: rops_handle_POLLIN_netlink: DELADDR
Mon Jun 12 08:16:51 2023 authpriv.info dropbear[5153]: Exit (root) from <192.168.125.32:50767>: Disconnect received

**Comment by littoy** [comment]
反馈kernel bug了

**Comment by KevinMX** [comment]
6.6 内核下此问题似乎已经解决。
继续观测中。
