### ISSUE TITLE
ssr plus 服务器监听ipv6

### ISSUE THREAD

**Issue by Creedowl** [coolsnowwolf/lede#1132]
由于校园网网络环境复杂，拿到的公网ipv6没法向下再分，想要开一个ss服务器从公网访问内网，但目前ss服务器只监听ipv4，希望添加ipv6监听

**Comment by hcym** [comment]
服务端应该可以把，客户端一直用的ipv6

**Comment by Creedowl** [comment]
服务端不行啊，只监听v4


hcym <notifications@github.com> 于 2019年3月25日周一 下午8:37写道：

**Comment by MeIsReallyBa** [comment]
自己改下配置文件就行了。嫌麻烦的话就编译时选择ss-server，再自己手动启动。

**Comment by gq59421** [comment]
如何修改配置文件？
