### ISSUE TITLE
需求：加入IPv6 Pass-Throughout功能

### ISSUE THREAD

**Issue by a843161264** [coolsnowwolf/lede#1133]
目的：构造 IPv4路由（NAT）+ IPv6交换机
用途：适用于IPv4需要认证，而IPv6可自动获取的双栈网络
思路：将 WAN 接口 + LAN 接口（包括WLAN）桥接，屏蔽掉网桥上的IPv4数据包，让IPv6的数据包利用该网桥从路由器中直接通过（Luci中自动实现，打勾勾就行的那种）

**Comment by lijun0326** [comment]
https://github.com/cvmiller/v6brouter
自己丢进init.rc就行
