### ISSUE TITLE
R2C编译失败

### ISSUE THREAD

**Issue by facerleo** [coolsnowwolf/lede#11338]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：有遇到类似问题的盆友吗

### (2) 路由器型号和固件版本

A：R2C

### (3) 详细日志

A：
![image](https://github.com/coolsnowwolf/lede/assets/86334632/4b9599e8-4540-402c-8773-d063afd569ce)

**Comment by WYC-2020** [comment]
基础环境缺东西，用elftools搜索，以前又说如何解决

**Comment by 159321** [comment]
U-boot下载不完整
