### ISSUE TITLE
最新代码，编译时发现target system缺失rockchip

### ISSUE THREAD

**Issue by Travel2Here** [coolsnowwolf/lede#11350]
设备类型没有rockchip了~~啥情况？
清过缓存也如此~

<img width="469" alt="image" src="https://github.com/coolsnowwolf/lede/assets/99887507/c01709af-1e0c-4bd1-ab81-fdf33c1b49c7">

**Comment by Travel2Here** [comment]
> ![image](https://github.com/coolsnowwolf/lede/assets/34025388/bbd321a0-3fd0-4afa-8e74-5bc7befc896e)
> 
> 

奇怪 我下午pull了一下就这样，缓存也清了…依然没有

**Comment by Travel2Here** [comment]
没人解吗?
<img width="469" alt="image" src="https://github.com/coolsnowwolf/lede/assets/99887507/0f675fd6-29ee-4e56-90da-e4039a7f0e9a">

**Comment by nuo12138** [comment]
> 没人解吗?

![截图_20230705165236](https://github.com/coolsnowwolf/lede/assets/41539650/edde422c-81d4-443d-8816-42c034f45018)
![截图_20230705165334](https://github.com/coolsnowwolf/lede/assets/41539650/939c6c5c-a3b6-4ce5-9a48-6a8f6da73f0b)
怎么可能没有，我3号才编译了固件，这个是新拉的代码

**Comment by nuo12138** [comment]
找不到的话建议删了重新啦源码编译

**Comment by WYC-2020** [comment]
是看不懂别人的答复么，都给你贴图说了 有，还在这里一直问，都不检查是否是自己的问题

**Comment by Travel2Here** [comment]
> 找不到的话建议删了重新啦源码编译

神奇 删了重拉正常咯 ，可我啥也没干只是更新…
