### ISSUE TITLE
shortcut-fe可能和docker存在冲突

### ISSUE THREAD

**Issue by loydcheung** [coolsnowwolf/lede#11359]
x86系统，Turbo ACC 里面shortcut-fe 开启后，docker 下面所有容器的网络都不通，关掉就恢复正常。不知各位大佬是不是也有遇到。

**Comment by Travel2Here** [comment]
编译的时候去掉它得了，我反正对比过好多版 开与不开没什么体验差异，精简原则。
至于影响docker bridge网络与否 没验证，因为习惯用host网络，没有影响；

**Comment by WYC-2020** [comment]
这玩意再性能不够的机器上开 才会有提升，现在的软路由基本都是性能过剩的 ，所以没必要开这个玩意，自己安慰自己而已

**Comment by loydcheung** [comment]
> 编译的时候去掉它得了，我反正对比过好多版 开与不开没什么体验差异，精简原则。
> 
> 至于影响docker bridge网络与否 没验证，因为习惯用host网络，没有影响；

我两个容器，一个用bridge，一个用macvlan，开了shortcut-fe都受影响网络不通。

**Comment by loydcheung** [comment]
好的，听两位建议我直接编译的时候去除得了。
