### ISSUE TITLE
内置的PPTP VPN服务器问题

### ISSUE THREAD

**Issue by BROBIRD** [coolsnowwolf/lede#1135]
使用版本：X86_64
我从WAN口连接之后，无法发送 QQ/TIM 消息，游戏（ LOL，OW ）可以匹配，但是无法连接，表现为无法进入游戏。
我初步怀疑是 UDP 协议连接问题，请问有人遇到这种情况吗？如何解决？
P.S 之前使用 hiboy 的 padavan 固件的时候，PPTP VPN连接下是正常的，他使用的 pptp 实现是`accel-pptp`（应该是现在的 `accel-ppp` ），是否是这个原因？
谢谢！

**Comment by coolsnowwolf** [comment]
和 SFE 的兼容问题，把 SFE 加速关闭即可

**Comment by BROBIRD** [comment]
关闭SFE之后问题解决
