### ISSUE TITLE
请教关于ssr-plus的问题

### ISSUE THREAD

**Issue by BROBIRD** [coolsnowwolf/lede#1137]
0.ssr-plus GFWList模式情况下，对于不在GFWList中的域名，默认是如何处理的？为什么我访问`*.gov.cn`会显示我在通过代理访问？
1.如果我想修改ssr-plus这个软件包并提交pull request，我应该如何解密修改`shadowsocksr.lua`？

谢谢

**Comment by dongjuanyong** [comment]
gfwlist里正则表达式的处理有问题，这一条：

> @@||gov.cn

本来是跳过代理的规则，处理成了走代理的规则，不过似乎别的@@又不都是有问题，很迷……

**Comment by coolsnowwolf** [comment]
最新版本不会了，请 git pull 更新版本即可

**Comment by BROBIRD** [comment]
@coolsnowwolf 我是3月22日编译的，在那之后有过修改吗？看了一下`luci-app-ssr-plus`这个包最后修改时间是一个月之前啊？谢谢！

**Comment by BROBIRD** [comment]
@coolsnowwolf 
https://github.com/coolsnowwolf/lede/blob/master/package/lean/ipset-lists/files/etc/gfwlist/china-banned#L1752
这一行多了个`gov.cn`

**Comment by BROBIRD** [comment]
`kknews.cc`也走了代理

**Comment by Chandler-Lu** [comment]
@coolsnowwolf 不知道可否支持一下ss的协议，simple_obfs_tls和simple_obfs_http，谢谢～
