### ISSUE TITLE
mt7621编译修改内核为5.15后刷入设备无法启动

### ISSUE THREAD

**Issue by lushangkan** [coolsnowwolf/lede#11395]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在target/linux/ramips/Makefile中修改linux版本为5.15编译刷入设备后无法启动，System灯一直亮蓝色，插网线到电脑后无法通过dhcp获取ip，没有接收到的数据包，手动修改ip后无法访问后台

### (2) 路由器型号和固件版本

A：红米AC2100 master/dff0d35

### (3) 详细日志

A：无，编译日志:https://github.com/lushangkan/lede-mt7621/actions/runs/5596551510

**Comment by padavanonly** [comment]
编译日志一点用也没有

**Comment by shenlijun** [comment]
应该还不支持5.15
![微信截图_20230721194621](https://github.com/coolsnowwolf/lede/assets/8860591/303cd1bd-af22-4cdf-a734-70161b9d9ad4)

**Comment by linfangrong** [comment]
现在支持了吗
