### ISSUE TITLE
求教：Openwrt主题左侧菜单Istore显示异常，请问这问题可以在源码什么文件夹下进行更正？

### ISSUE THREAD

**Issue by SterlingCarter** [coolsnowwolf/lede#11419]
在编译OpenWRT固件时，集成了自己比较喜欢的部分主题（如：Netgrar、Edge、Argon等），但是在主题实际应用过程中发现这些主题与Istore存在匹配性问题，某些主题导致Istore左前方不显示图标，或者Istore文字显示的位置非常靠近页面左侧（如下图左侧红框内所示）。
**1、故在此虚心请教，这样的显示异常请问在源码中什么地方可以进行修改？
2、或者请大神可以针对这几款主题和Istore进行适配，不胜感激。**
![1](https://github.com/coolsnowwolf/lede/assets/66172871/d2a3ea77-5374-4342-a08c-f114e7d019c0)
![2](https://github.com/coolsnowwolf/lede/assets/66172871/c62c90b1-5e6d-43d3-bdd7-ffb4609e0a75)

**Comment by nuo12138** [comment]
你应该去对应主题开发者下面发请求而不是这里
