### ISSUE TITLE
希添大雕加一下长按reset恢复出厂设置

### ISSUE THREAD

**Issue by libinanshu** [coolsnowwolf/lede#1142]
如题	TP-Link Archer C7 v3 CPU:720Mhz，没有复位功能好不方便呀

**Comment by coolsnowwolf** [comment]
支持的啊

**Comment by libinanshu** [comment]
但是WDR7500 V3 无论编译Archer C7 v3 还是Archer C7 v2复位按键都不起作用，必须要进入breed或者系统恢复，就改了一下默认LAN IP 其他系统方面的也没动过呀

**Comment by LGA1150** [comment]
刷别的路由器的固件，就别指望所有功能正常
你的情况就是 reset 按键 GPIO 不一样
