### ISSUE TITLE
ssr plus加载节点是否为单线程？

### ISSUE THREAD

**Issue by itfish92** [coolsnowwolf/lede#1143]
订阅了三个机场，节点一多加载ssr plus特别慢。n3700的软路由得加载一分钟，G4560得10秒钟。是否可以调用多线程加载节点列表呢？这样可以快一些。谢谢大雕一直一来的固件支持

**Comment by coolsnowwolf** [comment]
lua 的处理效率问题，确实是单线程的

**Comment by itfish92** [comment]
> lua的处理效率问题，确实是单线程的

感谢大雕解答
