### ISSUE TITLE
ShadowSocksR Plus+ 开启udp后，windows系统无法时间同步

### ISSUE THREAD

**Issue by Mitchell08** [coolsnowwolf/lede#11448]
ShadowSocksR Plus+ 开启udp后，windows系统无法时间同步

![image](https://github.com/coolsnowwolf/lede/assets/13077075/c709496b-f3fa-4e8a-8eb2-bc58432093e4)

![image](https://github.com/coolsnowwolf/lede/assets/13077075/6c3f0d2e-75e5-4f08-bdb9-f04fce11eaa5)

关闭udp后，windows系统就可以时间同步了，大家有遇到同样问题吗，请教可能是什么原因？

**Comment by minlang112** [comment]
未发现异常，可以同步

**Comment by Cathgao** [comment]
跟ssrp没一厘钱关系，就是微软的NTP服务器日常难用。你换成阿里腾讯的NTP一点问题都不会有
