### ISSUE TITLE
稍微修改了一下luci-app-v2ray，求问下是否可以加入一次commit

### ISSUE THREAD

**Issue by crotoc** [coolsnowwolf/lede#1145]
不常玩github，也不太懂这个机制，所以来问一下。我经常用到unblock-youku的功能，因为L大的包里的设置主要针对的是gfw的，所以我仿照gfw的设置修改了一下，详情看看https://github.com/crotoc/luci-app-v2ray。如果L大觉得没有意义，那就忽略这条信息。谢谢了！

**Comment by Zxilly** [comment]
改好了之后直接发起PR不就好了。。。
git总要学的，不可能永远不用
