### ISSUE TITLE
N1 盒子

### ISSUE THREAD

**Issue by hcym** [coolsnowwolf/lede#1148]
各位大侠，n1怎么适配的？

**Comment by yonggedebaqi** [comment]
N1 要是有双LAN1000M就好了

**Comment by hcym** [comment]
那就不是八十块了，其实单臂路由也还行，就是麻烦一点

**Comment by hcym** [comment]
搞定，性能强悍无比

**Comment by shenzt68** [comment]
@hcym 怎么适配的？说一下

**Comment by hcym** [comment]
就是论坛帖子里的，qemu里面armv8，选择需要的功能，最好用官方的编译，性能高一点，用大雕源码确实多一些功能，方便一些，但是那个相关offload什么的一概不要选，有毛病，只要bbr，用原版v2ray，速度和高配电脑相当

**Comment by aff2018** [comment]
make menuconfig
n1要怎么选？
