### ISSUE TITLE
ShadowSocksR Plus+ Netflix 分流服务器 中转代理转发的相关问题

### ISSUE THREAD

**Issue by YixiaoOrg** [coolsnowwolf/lede#11509]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
ShadowSocksR Plus+，开启了Netflix 分流服务器，没有开启分流服务器（前置）代理
但是还是有流量通过主服务器去请求Netflix 分流服务器，

尝试解决：把 Netflix 分流服务器（vless协议）的服务器地址由域名改成ip地址，这个问题就解除了

不知道为什么

### (2) 路由器型号和固件版本

OpenWrt R22.7.19 / LuCI Master (git-22.200.61437-0c3c82f)

### (3) 详细日志

无

**Comment by wwowwyu** [comment]
改了ip地址还是走主服务器，还有什么地方出错的？
