### ISSUE TITLE
20f23ca 以后的代码P&W R619AC 128M都无法启动

### ISSUE THREAD

**Issue by dengxin6** [coolsnowwolf/lede#11518]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：git reset --hard 20f23ca 之前能行，后面的代码，包括全新clone，都启动不了

### (2) 路由器型号和固件版本

A：
P&W R619AC 128M
OpenWrt R23.7.7
5.4.250

### (3) 详细日志

A：无法启动，没有日志

**Comment by qpzr** [comment]
编译出这个名字的固件openwrt-ipq40xx-generic-8dev_habanero-dvk-squashfs-sysupgrade.bin
我还犹豫了一下是不是搞错了，幸好没强行撸进去更新，不然我也翻车。

**Comment by dengxin6** [comment]
为什么被关了呢   没人用竞斗云了吗？

**Comment by xywf221** [comment]
我还以为只有我遇到这个问题了。
