### ISSUE TITLE
PVE 重启 openwrt 后 read-only file system

### ISSUE THREAD

**Issue by MochiXu** [coolsnowwolf/lede#11533]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

截止这个 issue 创建的时候，我使用了你的 master 分支编译了 ext combined 镜像，然后交给 PVE 运行。

在首次运行时可正常写入文件，重启系统后就无法写入了。
必须要重新 mount 根目录才行
<img width="613" alt="image" src="https://github.com/coolsnowwolf/lede/assets/42711279/546427c9-2a7c-423e-a00c-e4dbabc1a77b">

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by 1582130940** [comment]
https://github.com/coolsnowwolf/lede/issues/10317
参考这个，首次重启后删挂载点可解
