### ISSUE TITLE
源码不支持Hinlink H28k么？target profile中只有H66k/HK68K/H69K

### ISSUE THREAD

**Issue by leochien0102** [coolsnowwolf/lede#11551]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：Target System选择rockchip，Target Profile中Hinlink只有H66k/HK68K/H69K

### (2) 路由器型号和固件版本

A：Hinlink H28K

### (3) 详细日志

A：

**Comment by aiamadeus** [comment]
不支持，等 rk 开源了再说
