### ISSUE TITLE
烦请大佬百忙中抽空升级一下go的版本

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#11560]
新版的hysteria要求1.21版的go，而目前go为1.20版，烦请大佬百忙中抽空升级一下

**Comment by yanxin152133** [comment]
好像已经是1.21版本的了
![image](https://github.com/coolsnowwolf/lede/assets/43341537/1fa7e7a8-81e0-4083-92a4-75c5feebee27)

**Comment by binge8** [comment]
已经更新了啊[f937504](https://github.com/coolsnowwolf/packages/commit/f937504996886608d3803b63cc6288790bc6a19e)
