### ISSUE TITLE
选了kcptun，编译出来ssrplus里没有kcptun

### ISSUE THREAD

**Issue by forever8938** [coolsnowwolf/lede#1156]
最新源码编译的，软件包里可以看到kcptun-client 20190401-1已经安装。

**Comment by cnsilvan** [comment]
新的界面并不显示kcptun 换老版本的ssr+ 插件试试

**Comment by chquse** [comment]
ssr+里面是使用ssr-kcptun的，新源码编译出来是kcptun-client，所以要把kcptun-client改名为ssr-kcptun就出来了。
或者改源码，使编译出来的名字统一为其中一个，比如都是ssr-kcptun。

**Comment by cnsilvan** [comment]
> ssr+里面是使用ssr-kcptun的，新源码编译出来是kcptun-client，所以要把kcptun-client改名为ssr-kcptun就出来了。
> 或者改源码，使编译出来的名字统一为其中一个，比如都是ssr-kcptun。

使用kcptun 官方库改名替换试成功了 替换成功后 界面自己就显示了？我换了低一个版本的插件 界面就有显示kcptun

**Comment by cnsilvan** [comment]
现在解决v2ray 使用不了 不知道为什么。@chquse

**Comment by chquse** [comment]
改名是成功了，但最好由L大从源头解决。
没用V2，不是很清楚哦。

**Comment by coolsnowwolf** [comment]
已修复
