### ISSUE TITLE
最新源码编译C-LIFE XG1出错

### ISSUE THREAD

**Issue by SilenceAkarin** [coolsnowwolf/lede#11564]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：先前的源码编译没有问题，更新到最新源码后编译报错

### (2) 路由器型号和固件版本

A：C-LIFE XG1 linux-5.4.257

### (3) 详细日志

A：
akarin@Akarin-PC:~/lede$ make PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin  V=s -j1
make[2]: Entering directory '/home/akarin/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/akarin/lede/scripts/config'
make[1]: Entering directory '/home/akarin/lede'
make[2]: Entering directory '/home/akarin/lede'
make[3]: Entering directory '/home/akarin/lede/target/linux'
make[4]: Entering directory '/home/akarin/lede/target/linux/ramips'
rm -f /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/localversion
/home/akarin/lede/scripts/kconfig.pl  + /home/akarin/lede/target/linux/generic/config-5.4 /home/akarin/lede/target/linux/ramips/mt7621/config-5.4 > /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/akarin/lede/.config >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target
/home/akarin/lede/scripts/package-metadata.pl kconfig /home/akarin/lede/tmp/.packageinfo /home/akarin/lede/.config 5.4 > /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.override
/home/akarin/lede/scripts/kconfig.pl 'm+' '+' /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.target /dev/null /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.override > /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set
mv /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.old
grep -v INITRAMFS /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.old > /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set
rm -rf /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/modules
cmp -s /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.prev || { cp /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config; cp /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.prev; }
export MAKEFLAGS= ; [ -d /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/user_headers ] || make -C /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257 KCFLAGS="-fmacro-prefix-map=/home/akarin/lede/build_dir/target-mipsel_24kc_musl=target-mipsel_24kc_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/akarin/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mipsel-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Sep 30 09:44:03 2023" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/akarin/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.257 CC="mipsel-openwrt-linux-musl-gcc"  INSTALL_HDR_PATH=/home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/user_headers headers_install
grep '=[ym]' /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.config.set | LC_ALL=C sort | /home/akarin/lede/staging_dir/host/bin/mkhash md5 > /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.vermagic
touch /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.configured
rm -f /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/vmlinux /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/System.map
make -C /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257 KCFLAGS="-fmacro-prefix-map=/home/akarin/lede/build_dir/target-mipsel_24kc_musl=target-mipsel_24kc_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/akarin/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mipsel-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Sep 30 09:44:03 2023" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/akarin/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.257 CC="mipsel-openwrt-linux-musl-gcc" olddefconfig
make[5]: Entering directory '/home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257'
/bin/sh: 1: mipsel-openwrt-linux-musl-gcc: not found
/bin/sh: 1: mipsel-openwrt-linux-musl-gcc: not found
scripts/kconfig/conf  --olddefconfig Kconfig
scripts/Kconfig.include:35: compiler 'mipsel-openwrt-linux-musl-gcc' not found
make[6]: *** [scripts/kconfig/Makefile:73: olddefconfig] Error 1
make[5]: *** [Makefile:597: olddefconfig] Error 2
make[5]: Leaving directory '/home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257'
make[4]: *** [Makefile:24: /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.modules] Error 2
make[4]: Leaving directory '/home/akarin/lede/target/linux/ramips'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/akarin/lede/target/linux'
time: target/linux/compile#0.23#0.01#0.23
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/akarin/lede'
make[1]: *** [target/Makefile:23: /home/akarin/lede/staging_dir/target-mipsel_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/akarin/lede'
make: *** [/home/akarin/lede/include/toplevel.mk:231: world] Error 2

**Comment by JuiChao** [comment]
+1
