### ISSUE TITLE
k2p ykl1 编译出错

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#11585]
Building targets
runtime/cgo
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'

make[3]: *** [Makefile:67: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/frp-0.51.3/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/frp'
time: package/feeds/packages/frp/compile#0.81#0.27#0.81
    ERROR: package/feeds/packages/frp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/frp/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

X86编译没有这问题

**Comment by yanxin152133** [comment]
frp换个老版本的试试

**Comment by mitsukileung** [comment]
> frp换个老版本的试试

好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功


![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)

![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)

**Comment by yanxin152133** [comment]
> > frp换个老版本的试试
> 
> 好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功
> 
> 
> ![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)
> 
> ![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)
> 
> 
我之前用的0.37

**Comment by yanxin152133** [comment]
> > frp换个老版本的试试
> 
> 好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功
> 
> 
> ![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)
> 
> ![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)
> 
> 

我前段时间也碰到0.47版本的别人编译不了我能编译的情况

**Comment by mitsukileung** [comment]
> > > frp换个老版本的试试
> > 
> > 
> > 好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功
> > ![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)
> > ![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)
> 
> 我前段时间也碰到0.47版本的别人编译不了我能编译的情况

配置文件什么的都没有改过，刚刚又试了下5.10内核，还是一样的问题

**Comment by yanxin152133** [comment]
> > > > frp换个老版本的试试
> > > 
> > > 
> > > 好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功
> > > ![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)
> > > ![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)
> > 
> > 
> > 我前段时间也碰到0.47版本的别人编译不了我能编译的情况
> 
> 配置文件什么的都没有改过，刚刚又试了下5.10内核，还是一样的问题

试了下0.44版本可以正常编译。
![image](https://github.com/coolsnowwolf/lede/assets/43341537/53d2a683-3deb-4e43-9637-36d090e7091c)
![image](https://github.com/coolsnowwolf/lede/assets/43341537/ce8d489a-5e59-4dad-b1c9-57b6b61ca3db)

**Comment by mitsukileung** [comment]
> > > > > frp换个老版本的试试
> > > > 
> > > > 
> > > > 好像和FRP版本没有多大关系，9月16日编译ykl1的时候也可以用 0.5.13 编译成功
> > > > ![屏幕截图 2023-10-11 194113](https://github.com/coolsnowwolf/lede/assets/38887306/fd434f9d-b989-4ea4-8870-5aa0c0deef7f)
> > > > ![屏幕截图 2023-10-11 194152](https://github.com/coolsnowwolf/lede/assets/38887306/d6e97e0f-be90-4767-bcb4-61d8b3a0b489)
> > > 
> > > 
> > > 我前段时间也碰到0.47版本的别人编译不了我能编译的情况
> > 
> > 
> > 配置文件什么的都没有改过，刚刚又试了下5.10内核，还是一样的问题
> 
> 试了下0.44版本可以正常编译。 ![image](https://user-images.githubusercontent.com/43341537/274810202-53d2a683-3deb-4e43-9637-36d090e7091c.png) ![image](https://user-images.githubusercontent.com/43341537/274810404-ce8d489a-5e59-4dad-b1c9-57b6b61ca3db.png)

X86 编译一直都是正常呀，就是MTK编译出错

**Comment by liwenjie119** [comment]
![Screenshot_2023-10-21-18-34-51-160_com android browser](https://github.com/coolsnowwolf/lede/assets/25956275/23c753c9-5214-4607-9b2f-c35c30836734)
同样的问题，已经有好一段时间了，之前以为是frp的问题，但是去看frp官方mips有release，说明源码应该没问题，不知道是不是gcc冲突

**Comment by luzheng123** [comment]
我也遇到完全一样的问题，找不到原因，期待有大佬

**Comment by liwenjie119** [comment]
仍然卡在这里，不清楚具体原因

**Comment by mitsukileung** [comment]
只有等大佬们了
