### ISSUE TITLE
”kmod-video-core“编译失败

### ISSUE THREAD

**Issue by lxg2001** [coolsnowwolf/lede#11601]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：”kmod-video-core“编译失败

### (2) 路由器型号和固件版本

A：x86_64，最新源码

### (3) 详细日志

A：
`Package kmod-video-core is missing dependencies for the following libraries:`
`mc.ko`

**Comment by yanxin152133** [comment]
https://github.com/coolsnowwolf/lede/issues/8669

这日志真“详细”
