### ISSUE TITLE
最新源码编译报错 lzma: invalid option -- '0' 

### ISSUE THREAD

**Issue by SilenceAkarin** [coolsnowwolf/lede#11607]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：lzma: invalid option -- '0' 尝试回滚lzma旧版本，更新新版本和卸载重装都不能解决这个问题

### (2) 路由器型号和固件版本

A：C-LIFE XG1 

### (3) 详细日志

A：
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:476:warning: multi-line strings not supported
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  GEN     usr/initramfs_data.cpio.lzma
lzma: invalid option -- '0'
make[6]: *** [usr/Makefile:63: usr/initramfs_data.cpio.lzma] Error 1
make[5]: *** [Makefile:1750: usr] Error 2
make[5]: Leaving directory '/home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257'
make[4]: *** [Makefile:45: /home/akarin/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.257/.image] Error 2
make[4]: Leaving directory '/home/akarin/lede/target/linux/ramips'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/akarin/lede/target/linux'
time: target/linux/install#13.35#2.55#14.47
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/akarin/lede'
make[1]: *** [target/Makefile:24: /home/akarin/lede/staging_dir/target-mipsel_24kc_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/akarin/lede'
make: *** [/home/akarin/lede/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
WSL 问题自行解决
