### ISSUE TITLE
avahi error怎么解决

### ISSUE THREAD

**Issue by yunmi323** [coolsnowwolf/lede#1161]
make[3]: Entering directory '/home/coolmo/openwrt/newifi3/lede/feeds/packages/libs/avahi'
mkdir -p /home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp
SHELL= flock /home/coolmo/openwrt/newifi3/lede/tmp/.root-copy.flock -c 'cp -fpR /home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/.pkgdir/libavahi-client/. /home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/'
touch /home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp/.libavahi-client_installed
mkdir -p /home/coolmo/openwrt/newifi3/lede/bin/targets/ramips/mt7621/packages /home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/ipkg-mipsel_24kc/libavahi-compat-libdnssd/CONTROL /home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/pkginfo
install -d -m0755 /home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/ipkg-mipsel_24kc/libavahi-compat-libdnssd/usr/lib
cp -fpR /home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/ipkg-install/usr/lib/libdns_sd.so.* /home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/ipkg-mipsel_24kc/libavahi-compat-libdnssd/usr/lib/
cp: cannot stat '/home/coolmo/openwrt/newifi3/lede/build_dir/target-mipsel_24kc_musl/avahi/dbus/avahi-0.6.32/ipkg-install/usr/lib/libdns_sd.so.*': No such file or directory
Makefile:399: recipe for target '/home/coolmo/openwrt/newifi3/lede/bin/packages/mipsel_24kc/packages/libavahi-compat-libdnssd_0.6.32-3_mipsel_24kc.ipk' failed
make[3]: *** [/home/coolmo/openwrt/newifi3/lede/bin/packages/mipsel_24kc/packages/libavahi-compat-libdnssd_0.6.32-3_mipsel_24kc.ipk] Error 1
make[3]: Leaving directory '/home/coolmo/openwrt/newifi3/lede/feeds/packages/libs/avahi'
time: package/feeds/packages/avahi/dbus/compile#0.17#0.13#0.53
package/Makefile:107: recipe for target 'package/feeds/packages/avahi/compile' failed
make[2]: *** [package/feeds/packages/avahi/compile] Error 2
make[2]: Leaving directory '/home/coolmo/openwrt/newifi3/lede'
package/Makefile:103: recipe for target '/home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/coolmo/openwrt/newifi3/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/coolmo/openwrt/newifi3/lede'
/home/coolmo/openwrt/newifi3/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by qxj** [comment]
目前的trunk安装luci-app-shairplay的时候，还是同样的error。
