### ISSUE TITLE
全新下载源码，R4S编译util-linux报错

### ISSUE THREAD

**Issue by zhucaidan** [coolsnowwolf/lede#11612]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：使用全新下载的源码使用Ubuntu 22.04编译，未选择任何插件只选了设备为R4S，单线程编译时util-linux报错

### (2) 路由器型号和固件版本

A：nanopi-R4S

### (3) 详细日志

A：
/home/openwrt/lede/staging_dir/host/bin/python3 /home/openwrt/lede/staging_dir/host/bin/meson.py  --buildtype plain --native-file /home/openwrt/lede/build_dir/target-aarch64_generic_musl/util-linux-2.38.1/openwrt-native.txt --cross-file /home/openwrt/lede/build_dir/target-aarch64_generic_musl/util-linux-2.38.1/openwrt-cross.txt -Dsystemd=disabled -Dtinfo=disabled -Dcryptsetup=disabled -Dlibutil=disabled -Dlibutempter=disabled -Dlibpcre2-posix=disabled -Dlibuser=disabled -Duse-tty-group=false -Duse-tls=false -Dbuild-python=disabled -Dbuild-zramctl=disabled -Dbuild-fsck=disabled -Dbuild-wipefs=disabled -Dbuild-fallocate=disabled -Dbuild-setpriv=disabled -Dbuild-hardlink=disabled -Dbuild-cramfs=disabled -Dbuild-bfs=disabled -Dbuild-minix=disabled -Dbuild-fdformat=disabled -Dbuild-lslogins=disabled -Dbuild-wdctl=disabled -Dbuild-cal=disabled -Dbuild-switch_root=disabled -Dbuild-pivot_root=disabled -Dbuild-lsmem=disabled -Dbuild-lsirq=disabled -Dbuild-irqtop=disabled -Dbuild-chmem=disabled -Dbuild-ipcrm=disabled -Dbuild-rfkill=disabled -Dbuild-tunelp=disabled -Dbuild-kill=disabled -Dbuild-last=disabled -Dbuild-utmpdump=disabled -Dbuild-line=disabled -Dbuild-mesg=disabled -Dbuild-raw=disabled -Dbuild-vipw=disabled -Dbuild-newgrp=disabled -Dbuild-chfn-chsh=disabled -Dbuild-login=disabled -Dbuild-nologin=disabled -Dbuild-sulogin=disabled -Dbuild-su=disabled -Dbuild-runuser=disabled -Dbuild-ul=disabled -Dbuild-pg=disabled -Dbuild-write=disabled -Dbuild-bash-completion=disabled -Dbuild-pylibmount=disabled -Dreadline=disabled -Dmagic=disabled -Dncursesw=enabled /home/openwrt/lede/build_dir/target-aarch64_generic_musl/util-linux-2.38.1/openwrt-build /home/openwrt/lede/build_dir/target-aarch64_generic_musl/util-linux-2.38.1/openwrt-build/..
bash: line 1: /home/openwrt/lede/staging_dir/host/bin/python3: No such file or directory
make[2]: *** [Makefile:878: /home/openwrt/lede/build_dir/target-aarch64_generic_musl/util-linux-2.38.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 127
make[2]: Leaving directory '/home/openwrt/lede/package/utils/util-linux'
time: package/utils/util-linux/compile#0.16#0.02#0.18
    ERROR: package/utils/util-linux failed to build.
make[1]: *** [package/Makefile:116: package/utils/util-linux/compile] Error 1
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:231：package/util-linux/compile] 错误 2

**Comment by aiamadeus** [comment]
make distclean
