### ISSUE TITLE
ssrplus的游戏模式完全没效果

### ISSUE THREAD

**Issue by forever8938** [coolsnowwolf/lede#1162]
打开以后状态里显示“游戏模式UDP中继”运行中。
看进程有个/usr/bin/ss-redir -c /var/etc/shadowsocksr_u.json -U -f /var/run/ssr-reudp.pid，但是CPU占用始终为0。
游戏里的延迟也没区别。
加速的是PS4游戏，NAT类型是2。

**Comment by coolsnowwolf** [comment]
有增强模式
