### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghmole** [coolsnowwolf/lede#11631]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
make V=sc

lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/fanctrl: line 6: /lib/functions/system.sh: No such file or directory
mkdir: cannot create directory '/etc/config': Permission denied

B:

lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 10: uci: command not found

### (2) 路由器型号和固件版本

A：R5S

### (3) 详细日志

A：
Configuring arp-scan.
Setting flags for package libc to hold.
Setting flags for package libgcc1 to hold.
Setting flags for package libatomic1 to hold.
Setting flags for package libstdcpp6 to hold.
Setting flags for package libpthread to hold.
Setting flags for package librt to hold.
cp -fpR /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root.orig-rockchip

Please install the arp-scan-database package in order to let arp-scan
display additional information about vendor/manufacturer for each
discovered device.

/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/fanctrl: line 6: /lib/functions/system.sh: No such file or directory
mkdir: cannot create directory '/etc/config': Permission denied
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 10: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 11: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 12: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 13: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 14: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 15: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 16: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 17: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 18: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 19: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 20: uci: command not found
/home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/guest-wifi: line 21: uci: command not found
Enabling adbyby
Enabling aria2
Enabling arpbind
Enabling autoreboot
Enabling avahi-daemon
Enabling boot
Enabling cgroupfs-mount
Enabling cpufreq
Enabling cron
Enabling dbus
Enabling ddns
Enabling dnsmasq
Enabling dockerd
Enabling dockerman
Enabling done
Enabling dropbear
Enabling etherwake
./etc/init.d/fanctrl: line 6: /lib/functions/system.sh: No such file or directory
Enabling fanctrl
Enabling firewall
Enabling fstab
Enabling gpio_switch
mkdir: cannot create directory '/etc/config': Permission denied
./etc/init.d/guest-wifi: line 10: uci: command not found
./etc/init.d/guest-wifi: line 11: uci: command not found
./etc/init.d/guest-wifi: line 12: uci: command not found
./etc/init.d/guest-wifi: line 13: uci: command not found
./etc/init.d/guest-wifi: line 14: uci: command not found
./etc/init.d/guest-wifi: line 15: uci: command not found
./etc/init.d/guest-wifi: line 16: uci: command not found
./etc/init.d/guest-wifi: line 17: uci: command not found
./etc/init.d/guest-wifi: line 18: uci: command not found
./etc/init.d/guest-wifi: line 19: uci: command not found
./etc/init.d/guest-wifi: line 20: uci: command not found
./etc/init.d/guest-wifi: line 21: uci: command not found
Enabling guest-wifi
Enabling haveged
Enabling kms
Enabling led
Enabling log
Enabling mia
Enabling miniupnpd
Enabling network
Enabling nlbwmon
Enabling openssl
Enabling p910nd
Enabling qbittorrent
Enabling qos
Enabling rpcd
Enabling shadowsocksr
Enabling shairport-sync
Enabling sysctl
Enabling sysfixtime
Enabling sysntpd
Enabling system
Enabling ttyd
Enabling turboacc
Enabling ucitrack
Enabling uhttpd
Enabling umount
Enabling urandom_seed
Enabling urngd
Enabling usb_printer
Enabling usbmode
Enabling vsftpd
Enabling wpad
Enabling wrtbwmon
sed -i "s/Installed-Time: .*/Installed-Time: 1698848930/" /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/status
rm -rf /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/boot /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/tmp/* /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/info/*.postinst* /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/lists/* /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/var/lock/*.lock
find /home/ukxu/op/lean/lede/build_dir/target-aarch64_generic_musl/root-rockchip/ -mindepth 1 -execdir touch -hcd "@1698848930" "{}" +
find: The relative path '~/.local/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
make[2]: *** [package/Makefile:73: package/install] Error 1
make[2]: Leaving directory '/home/ukxu/op/lean/lede'
make[1]: *** [package/Makefile:111: /home/ukxu/op/lean/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/ukxu/op/lean/lede'
make: *** [/home/ukxu/op/lean/lede/include/toplevel.mk:231: world] Error 2

**Comment by lxg2001** [comment]
The relative path '~/.local/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find. Please remove that entry from $PATH
