### ISSUE TITLE
ShadowsocksR Plus+ 一直显示not running

### ISSUE THREAD

**Issue by lbmzly** [coolsnowwolf/lede#1164]
求助大佬!!!弄一天了一直这样,网件R6250,bcm53xx
![20190413191609](https://user-images.githubusercontent.com/49586756/56078997-f1311180-5e20-11e9-8181-7321637ba850.png)
![20190413191619](https://user-images.githubusercontent.com/49586756/56078998-f1c9a800-5e20-11e9-9bc7-5278f983010f.png)
![20190413191621](https://user-images.githubusercontent.com/49586756/56078999-f1c9a800-5e20-11e9-9d35-4597ab1aced3.png)
![20190413191625](https://user-images.githubusercontent.com/49586756/56079001-f1c9a800-5e20-11e9-8115-c915ee8ee44b.png)
![image](https://user-images.githubusercontent.com/49586756/56079018-0efe7680-5e21-11e9-8eb5-6337fc99d83f.png)

**Comment by zxlhhyccc** [comment]
是不是没有把v2tcl编译进去吧

**Comment by lbmzly** [comment]
> 是不是没有把v2tcl编译进去吧

没有找到这个v2tcl文件啊,还请大佬指导一下!!!

**Comment by lan542662** [comment]
删除重新全局编译吧，我这正常，说明是个别问题

lbmzly <notifications@github.com> 于2019年4月15日周一 上午1:01写道：
