### ISSUE TITLE
[请教] 如何在编译时选择openssl版本

### ISSUE THREAD

**Issue by ipsumy** [coolsnowwolf/lede#11655]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

当前编译的固件中openssl版本为3.0.12，似乎无法支持MD5
![图片](https://github.com/coolsnowwolf/lede/assets/131156018/d16f10fe-9570-45a5-ad7c-f89915f2346e)

希望可以学习如何切换版本为openssl1.1进行编译测试

### (2) 路由器型号和固件版本

X86

### (3) 详细日志

无

**Comment by ipsumy** [comment]
在 openwrt 22.03 代码中找到了openssl1.1.1，编译测试后正常，不确定是否会有其他异常

**Comment by xiaowonet** [comment]
> openssl1.1.1

请问具体的解决方法

**Comment by ipsumy** [comment]
> > openssl1.1.1
> 
> 请问具体的解决方法

Openwrt 22.03 版本源码中是1.1.1版本，替换相同编译目录下的openssl文件夹
https://github.com/openwrt/openwrt/tree/openwrt-22.03/package/libs/openssl

make clean
make download ...
然后编译
