### ISSUE TITLE
磊科n60 phy2 phy3 wlan2 wlan3 重启变化

### ISSUE THREAD

**Issue by jwkinko** [coolsnowwolf/lede#11672]
磊科n60 phy2 phy3 wlan2 wlan3 重启后变成phy0 phy1 wlan0 wlan1 ，导致一个无线中继路由器连不上n60了，是兼容问题吗？

**Comment by xiangfeidexiaohuo** [comment]
target/linux/mediatek/filogic/base-files/etc/board.d/02_network

	netcore,n60)
		ucidef_set_interfaces_lan_wan "lan0 lan1 lan2 lan3" eth1

你这么改 试试

**Comment by jwkinko** [comment]
不好用

**Comment by jwkinko** [comment]
> target/linux/mediatek/filogic/base-files/etc/board.d/02_network
> 
> 	netcore,n60)
> 		ucidef_set_interfaces_lan_wan "lan0 lan1 lan2 lan3" eth1
> 
> 你这么改 试试

不好用

**Comment by aiamadeus** [comment]
开启无线加速后要重启再设置 WiFi

**Comment by jwkinko** [comment]
> 开启无线加速后要重启再设置 WiFi
原来这样明白了！
