### ISSUE TITLE
咨询下，最新版本如何编译出SSR PLUS

### ISSUE THREAD

**Issue by franksz11** [coolsnowwolf/lede#11671]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述

平台Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-144-generic x86_64)
1、已修改feeds.conf.default打开了src-git helloworld https://github.com/fw876/helloworld.git
2、make menuconfig 没有看到luci-app-ssr-plus
3、进路由设置echo 0xDEADBEEF > /etc/config/google_fu_mode，也没有看到ssr-plus

### (1) 具体问题

A：如2

### (2) 路由器型号和固件版本

A：x86，编译最新固件

### (3) 详细日志

A：

**Comment by lyin888** [comment]
src-git helloworld https://github.com/fw876/helloworld;main

**Comment by FMJYY23** [comment]
git clone --depth=1 -b main https://github.com/fw876/helloworld package/helloworld

**Comment by star-o0O** [comment]
> 做过了
> 
> > src-git helloworld https://github.com/fw876/helloworld;main

看清楚点，带尾巴的，别瞄一眼就做过了，差着远呢

**Comment by yanxin152133** [comment]
https://github.com/kenzok8/openwrt-packages

**Comment by harrison-guo-chn** [comment]
src-git helloworld https://github.com/fw876/helloworld;main
分支变了，网上的教程可没更新的哦

**Comment by yanxin152133** [comment]
搞不懂你们是需要酸酸乳还是helloworld
![image](https://github.com/coolsnowwolf/lede/assets/43341537/119fad83-d988-49a3-94c9-1628ef206f2f)
![image](https://github.com/coolsnowwolf/lede/assets/43341537/1b087189-bee0-4cd6-9eea-d06241583647)

**Comment by Maxswang** [comment]
@franksz11  在feeds.conf.default 文件 添加以下两行内容： 
```shell
src-git kenzo https://github.com/kenzok8/openwrt-packages
src-git small https://github.com/kenzok8/small
```
添加以后执行以下命令：
```shell
 ./scripts/feeds update -a
./scripts/feeds install -a
```
