### ISSUE TITLE
shadowsocksr plus+ gfw模式  成全局模式了

### ISSUE THREAD

**Issue by luogu** [coolsnowwolf/lede#11685]
我的OpenWRT 的SSR+， 选的是GFW，或，绕开中国，都成了全局模式了。
在保存并应用后，前几分钟能正常，访问百度 搜 IP  能显示国内IP，但过了几分钟，再搜IP 就会显示国外IP了。
请问是什么原因呀。

**Comment by Rurikobaka** [comment]
建議用 ip.skk.moe 查看 IP Info

**Comment by luogu** [comment]
是的，全是国外的IP

**Comment by wqzvic88** [comment]
啊，我也是这个问题，一下子把我的流量全耗光了，只能先用绕过中国大陆ip模式。

**Comment by luogu** [comment]
> 啊，我也是这个问题，一下子把我的流量全耗光了，只能先用绕过中国大陆ip模式。 update1: 改完绕过大陆模式，一开始有用，过了会儿ip.skk.moe里面又全变成代理的ip了 update2: 把openwrt的固件更新到esir的高大上 2023 V2版，问题貌似解决了

对，我跟你的情况一样，切换成绕过中国，刚开始是可以，但过几分钟就不行了，又成全局模式了。
我还没有升级openwrt的固件
