### ISSUE TITLE
R4S reboot 无法启动

### ISSUE THREAD

**Issue by rsyrsyrsy** [coolsnowwolf/lede#11682]
自己default下编译的R4S固件，没有加任何其他插件，reboot命令shutdown后无法启动，需要重新插拔电源上电启动，请问有人遇到过类似问题么？

**Comment by Rurikobaka** [comment]
https://github.com/Kwiboo/linux-rockchip/commit/0d32911

很久以前遇到的時候遇到過類似問題搜索過，你確定一下你的 TF 卡是否沒問題
