### ISSUE TITLE
4.19.34内核编译出错，4.14版本正常！

### ISSUE THREAD

**Issue by abclai** [coolsnowwolf/lede#1169]
最新的4.19.43内核编译出错，4.14内核版本正常！配置文件一样！个人怀疑和kmod-fs-exfat有关系啦，但是也尝试编译的时候不选kmod-fs-exfat也一样，会发生错误！

**Comment by abclai** [comment]
> 最新的4.19.34内核编译出错，4.14内核版本正常！配置文件一样！个人怀疑和kmod-fs-exfat有关系啦，但是也尝试编译的时候不选kmod-fs-exfat也一样，会发生错误！

**Comment by abclai** [comment]
之前4.19.25编译正常！只是最近更新之后就发生错误啦

**Comment by dongjuanyong** [comment]
给个错误日志呗，虽然估计不是内核模块版本冲突就是依赖代码下载的问题
