### ISSUE TITLE
L大，能否将msd_lite加入插件库

### ISSUE THREAD

**Issue by richaradlee** [coolsnowwolf/lede#11722]
从网上找了一个，感觉比udpxy好用，cpu占用率也少

谢谢

**Comment by WYC-2020** [comment]
别人package 仓库九个月之前就添加这个玩意了 你自己没发现而已 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/19639542-5c16-4e93-9e69-76607e8d5100)

**Comment by richaradlee** [comment]
已解决~
