### ISSUE TITLE
Turbo ACC显示不正常

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#11747]
### 详细叙述

Turbo ACC显示不正常，如图，一直卡在正在收集数据。如果不选软件流量分载就显示正常
![1704432828529](https://github.com/coolsnowwolf/lede/assets/53508344/349f74f9-0f86-4a0f-a845-58aa953668d6)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

。

**Comment by yanxin152133** [comment]
引用下别人的评论
https://github.com/coolsnowwolf/lede/issues/11751#issuecomment-1880417326
