### ISSUE TITLE
ShadowSocksR Plus+中的本地端口

### ISSUE THREAD

**Issue by yhm97** [coolsnowwolf/lede#1175]
看见添加节点的时候有一个本地端口，想着能不能和SwitchyOmega一起用
但是Swithyomega插件 设置socks5 192.168.1.1 1234，无法访问外网
用sstap测试，提示认证失败，请确认账号和密码

不知道是不是有密码，我试了试root password都不对

这个本地端口能不用给Swithyomega和sstap用，该咋用

**Comment by coolsnowwolf** [comment]
这个不是 socks5，是 任意门

socks5 有另外的选项

**Comment by yhm97** [comment]
😂编译的时候没把socks选上，找半天没找到以为这个就是。大佬说有设置又去看看了选上弄好了

不过任意门有啥妙用，不知道这个东西😊

**Comment by cary5082** [comment]
怎么设置的呀。求问

**Comment by cary5082** [comment]
> 这个不是 socks5，是 任意门
> 
> socks5 有另外的选项

哪个选项呀。怎么打开，求问。。我在高级里看到sock5代理，写了端口后就是显示未运行。
