### ISSUE TITLE
编译出错 2024-01-12

### ISSUE THREAD

**Issue by xuanranran** [coolsnowwolf/lede#11763]
### 详细叙述

ERROR: package/feeds/packages/acl failed to build.
ERROR: package/feeds/packages/coreutils failed to build.
ERROR: package/utils/f2fs-tools failed to build (build variant: default)
ERROR: package/libs/libselinux failed to build.

### 重复 issue

- [x] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

ERROR: package/feeds/packages/acl failed to build.
ERROR: package/feeds/packages/coreutils failed to build.
ERROR: package/utils/f2fs-tools failed to build (build variant: default)
ERROR: package/libs/libselinux failed to build.

**Comment by binge8** [comment]
+1

**Comment by free-diy** [comment]
+1

**Comment by hcym** [comment]
晕车，acl
大雕请你慢慢的飞

**Comment by ywt114** [comment]
+1

**Comment by coolsnowwolf** [comment]
rm -rf staging_dir
