### ISSUE TITLE
musl 1.2.4 出现新的编译问题

### ISSUE THREAD

**Issue by xuanranran** [coolsnowwolf/lede#11768]
### 详细叙述

ERROR: package/utils/mdadm failed to build.
ERROR: package/feeds/packages/btrfs-progs failed to build.

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

ERROR: package/utils/mdadm failed to build.
ERROR: package/feeds/packages/btrfs-progs failed to build.

**Comment by qiyuey** [comment]
make[4]: Entering directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
    [CC]     mkfs/rootdir.o
In file included from mkfs/rootdir.c:19:
./kerncompat.h:142: warning: "__bitwise__" redefined
  142 | #define __bitwise__
      |
In file included from ./kerncompat.h:35,
                 from mkfs/rootdir.c:19:
/home/yuchuan/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/linux/types.h:25: note: this is the location of the previous definition
   25 | #define __bitwise__ __bitwise
      |
mkfs/rootdir.c: In function 'btrfs_mkfs_shrink_fs':
mkfs/rootdir.c:917:23: error: storage size of 'file_stat' isn't known
  917 |         struct stat64 file_stat;
      |                       ^~~~~~~~~
make[4]: *** [Makefile:414: mkfs/rootdir.o] Error 1
make[4]: Leaving directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
make[3]: *** [Makefile:100: /home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1/.built] Error 2
make[3]: Leaving directory '/home/yuchuan/lede/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#0.09#0.02#0.10
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[2]: Leaving directory '/home/yuchuan/lede'
make[1]: *** [package/Makefile:110: /home/yuchuan/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yuchuan/lede'
make: *** [/home/yuchuan/lede/include/toplevel.mk:231: world] Error 2

**Comment by qiyuey** [comment]
`make[4]: Entering directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
    [CC]     mkfs/rootdir.o
In file included from mkfs/rootdir.c:19:
./kerncompat.h:142: warning: "__bitwise__" redefined
  142 | #define __bitwise__
      |
In file included from ./kerncompat.h:35,
                 from mkfs/rootdir.c:19:
/home/yuchuan/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/linux/types.h:25: note: this is the location of the previous definition
   25 | #define __bitwise__ __bitwise
      |
mkfs/rootdir.c: In function 'btrfs_mkfs_shrink_fs':
mkfs/rootdir.c:917:23: error: storage size of 'file_stat' isn't known
  917 |         struct stat64 file_stat;
      |                       ^~~~~~~~~
make[4]: *** [Makefile:414: mkfs/rootdir.o] Error 1
make[4]: Leaving directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
make[3]: *** [Makefile:100: /home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1/.built] Error 2
make[3]: Leaving directory '/home/yuchuan/lede/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#0.09#0.02#0.10
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[2]: Leaving directory '/home/yuchuan/lede'
make[1]: *** [package/Makefile:110: /home/yuchuan/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yuchuan/lede'
make: *** [/home/yuchuan/lede/include/toplevel.mk:231: world] Error 2`

**Comment by binge8** [comment]
一样的报错。云编译新环境，新拉的config

**Comment by Nicepaul** [comment]
也报错了，本地编译
make[2]: Leaving directory '/home/julien/x64/lede'
make[1]: *** [toolchain/Makefile:93: /home/kkk/x64/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/kkk/x64/lede'
make: *** [/home/kkk/x64/lede/include/toplevel.mk:231: world] Error 2

**Comment by free-diy** [comment]
+1

**Comment by 1105384898** [comment]
一样的
make[4]: *** [Makefile:414: mkfs/rootdir.o] Error 1
make[4]: Leaving directory '/home/yangyang/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1'
make[3]: *** [Makefile:100: /home/yangyang/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1/.built] Error 2
make[3]: Leaving directory '/home/yangyang/lede/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#9.91#2.25#12.88
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[2]: Leaving directory '/home/yangyang/lede'
make[1]: *** [package/Makefile:110: /home/yangyang/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yangyang/lede'
make: *** [/home/yangyang/lede/include/toplevel.mk:231：world] 错误 2

**Comment by AndyLin2020** [comment]
赶上大军

xvasprintf.c:(.text+0x35): undefined reference to `__vsprintf_chk'
collect2: error: ld returned 1 exit status
make[8]: *** [Makefile:1287: as-new] Error 1
make[8]: Leaving directory '/home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40/gas'
make[7]: *** [Makefile:1664: all-recursive] Error 1
make[7]: Leaving directory '/home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40/gas'
make[6]: *** [Makefile:1010: all] Error 2
make[6]: Leaving directory '/home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40/gas'
make[5]: *** [Makefile:5472: all-gas] Error 2
make[5]: Leaving directory '/home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40'
make[4]: *** [Makefile:1005: all] Error 2
make[4]: Leaving directory '/home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40'
make[3]: *** [Makefile:112: /home/andy/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40/.built] Error 2
make[3]: Leaving directory '/home/andy/lede/toolchain/binutils'
time: toolchain/binutils/compile#47.19#70.33#133.66
    ERROR: toolchain/binutils failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/binutils/compile] Error 1
make[2]: Leaving directory '/home/andy/lede'
make[1]: *** [toolchain/Makefile:93: /home/andy/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/andy/lede'
make: *** [/home/andy/lede/include/toplevel.mk:231：world] 错误 2

**Comment by menphy1989** [comment]
configure: error: --with-zstd was given, but pkgconfig/libzstd.pc is not found
make[5]: *** [Makefile:3018: configure-bfd] Error 1
make[5]: Leaving directory '/home/ubuntu/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40'
make[4]: *** [Makefile:1005: all] Error 2
make[4]: Leaving directory '/home/ubuntu/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40'
make[3]: *** [Makefile:112: /home/ubuntu/lede/build_dir/toolchain-x86_64_gcc-11.3.0_musl/binutils-2.40/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/lede/toolchain/binutils'
time: toolchain/binutils/compile#5.57#0.95#6.12
    ERROR: toolchain/binutils failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/binutils/compile] Error 1
make[2]: Leaving directory '/home/ubuntu/lede'
make[1]: *** [toolchain/Makefile:93: /home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/lede'
make: *** [/home/ubuntu/lede/include/toplevel.mk:231：world] 错误 2

**Comment by WYC-2020** [comment]
> make[4]: Entering directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1' [CC] mkfs/rootdir.o In file included from mkfs/rootdir.c:19: ./kerncompat.h:142: warning: "**bitwise**" redefined 142 | #define **bitwise** | In file included from ./kerncompat.h:35, from mkfs/rootdir.c:19: /home/yuchuan/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/linux/types.h:25: note: this is the location of the previous definition 25 | #define **bitwise** __bitwise | mkfs/rootdir.c: In function 'btrfs_mkfs_shrink_fs': mkfs/rootdir.c:917:23: error: storage size of 'file_stat' isn't known 917 | struct stat64 file_stat; | ^~~~~~~~~ make[4]: *** [Makefile:414: mkfs/rootdir.o] Error 1 make[4]: Leaving directory '/home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1' make[3]: *** [Makefile:100: /home/yuchuan/lede/build_dir/target-x86_64_musl/btrfs-progs-v5.16.1/.built] Error 2 make[3]: Leaving directory '/home/yuchuan/lede/feeds/packages/utils/btrfs-progs' time: package/feeds/packages/btrfs-progs/compile#0.09#0.02#0.10 ERROR: package/feeds/packages/btrfs-progs failed to build. make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1 make[2]: Leaving directory '/home/yuchuan/lede' make[1]: *** [package/Makefile:110: /home/yuchuan/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/yuchuan/lede' make: *** [/home/yuchuan/lede/include/toplevel.mk:231: world] Error 2

https://github.com/coolsnowwolf/lede/issues/11771看这个贴子
