### ISSUE TITLE
编译过程中途停止不动，cpu没占用

### ISSUE THREAD

**Issue by ggzz0** [coolsnowwolf/lede#11786]
### 详细叙述

具体看日志

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

amd 2700 ,b450m

### 详细日志

make V=s -j1 时的问题日志
touch /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc.installed
mkdir -p /gg/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /gg/lede/tmp/.root-copy.flock -c 'cp -fpR /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/.pkgdir/libc/. /gg/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /gg/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.libc_installed
mkdir -p /gg/lede/bin/targets/rockchip/armv8/packages /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc/CONTROL /gg/lede/staging_dir/target-aarch64_generic_musl/pkginfo
install -d -m0755 /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc/lib
cp -fpR /gg/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib/libgcc_s.so.* /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc/lib/
find /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="aarch64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="aarch64-openwrt-linux-musl-nm" STRIP="/gg/lede/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/gg/lede/scripts/strip-kmod.sh" PATCHELF="/gg/lede/staging_dir/host/bin/patchelf" /gg/lede/scripts/rstrip.sh /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc
rstrip.sh: /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc/lib/libgcc_s.so.1: shared object
(cd /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /gg/lede/bin/targets/rockchip/armv8/packages
/gg/lede/staging_dir/host/bin/fakeroot /gg/lede/staging_dir/host/bin/bash /gg/lede/scripts/ipkg-build -m "" /gg/lede/build_dir/target-aarch64_generic_musl/toolchain/ipkg-aarch64_generic/libgcc /gg/lede/bin/targets/rockchip/armv8/packages

在这里停住不动,cpu占用很低。
在debian 11,12上试过，都是这样。

**Comment by ggzz0** [comment]
ctrl+c 之后：

^Cmake[3]: *** [Makefile:737: /gg/lede/bin/targets/rockchip/armv8/packages/libgcc1_11.3.0-4_aarch64_generic.ipk] Error 130
time: package/libs/toolchain/compile#0.20#0.17#4168.61
make[1]: *** [package/Makefile:110: /gg/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Interrupt
make: *** [/gg/lede/include/toplevel.mk:231: world] Interrupt

**Comment by WYC-2020** [comment]
内存和cpu  磁盘 搞的什么配置

**Comment by ggzz0** [comment]
> 内存和cpu 磁盘 搞的什么配置
amd 2700 cpu ,4g内存，120g硬盘

**Comment by WYC-2020** [comment]
> > 内存和cpu 磁盘 搞的什么配置
> > amd 2700 cpu ,4g内存，120g硬盘

内存搞8G试试

**Comment by ggzz0** [comment]
> 内存搞8G试试
一样，还是在那里停住。

**Comment by ggzz0** [comment]
> 内存搞8G试试

一样，还是在那里停住
