### ISSUE TITLE
openwrt启动时报下面错误，请问这是什么造成的错误

### ISSUE THREAD

**Issue by free-diy** [coolsnowwolf/lede#11792]
### 详细叙述

![image](https://github.com/coolsnowwolf/lede/assets/71208560/387c6619-4792-4503-8ccd-903a869d80f0)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

![image](https://github.com/coolsnowwolf/lede/assets/71208560/5547e34f-340b-45bd-aaa1-c1b3a80efc75)

**Comment by coolsnowwolf** [comment]
字面上的意思，docker 的 overlayfs 不能运行在已经 overlay 的文件系统上面，必须转到 ext4

**Comment by free-diy** [comment]
> 字面上的意思，docker 的 overlayfs 不能运行在已经 overlay 的文件系统上面，必须转到 ext4

嗯，谢谢大神帮我找到原因。
