### ISSUE TITLE
/etc/init.d/firewall调用shadowsocksr.include导致开机时ssr-redir重复执行

### ISSUE THREAD

**Issue by monsterzzzz** [coolsnowwolf/lede#118]
firewall start=19，后面ssrpro start=99，开机时执行firewall时会调用ssrpro restart，后面又会执行一次ssrpro，导致ssr-redir重复执行，请修改一下脚本，谢谢

**Comment by coolsnowwolf** [comment]
目前不打算修改，因为没有影响使用
