### ISSUE TITLE
新编译的OpenWrt 如何设置可以让局域网内 PPTP 连接穿透

### ISSUE THREAD

**Issue by yflwz** [coolsnowwolf/lede#11809]
### 详细叙述

最近自己编译了一个斐讯K3的固件，主要是有自己的需求，VPN服务编译了l2tp ipsec pptp，这些服务端都测试过可以正常使用，只是到最后发现网域网下面的手机和电脑都不能使用PPTP客户端连公司的PPTP服务器了。也看了官方的文档说要安装kmod-nf-nathelper-extra和kmod-ipt-raw等，我查了一下编译的时候本身已经有安装上，查找问题里发现同样问题的解决办法也试过加上，https://github.com/coolsnowwolf/lede/issues/329，但是还是用不了。
![屏幕截图 2024-01-20 215229](https://github.com/coolsnowwolf/lede/assets/19662528/4d2821b5-1bf9-4062-8b5e-8199854f58f3)
![屏幕截图 2024-01-20 215548](https://github.com/coolsnowwolf/lede/assets/19662528/60fe7d4b-5a8d-445b-a1a6-5b70a51b7d8e)
![屏幕截图 2024-01-20 220730](https://github.com/coolsnowwolf/lede/assets/19662528/cb56bb91-3267-42f2-b352-11318f04a8c8)
![屏幕截图 2024-01-20 221039](https://github.com/coolsnowwolf/lede/assets/19662528/7c53aa83-0292-466b-96b2-3cfdc253ac48)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

斐讯K3

### 详细日志

系统日志和内核日志没有相关信息

**Comment by coolsnowwolf** [comment]
固件默认已支持

**Comment by yflwz** [comment]
好的，已经解决，和固件无关，是因为走了openclash代理。
