### ISSUE TITLE
aliyundrive-webdav报错

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#11800]
### 详细叙述

昨天开始编译报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86，armv8

### 详细日志

```bash
time: package/feeds/packages/rust/host-compile#0.89#2.81#6.08
make[3]: Entering directory '/home/runner/work/op/op/openwrt/feeds/packages/multimedia/aliyundrive-webdav'
rm -rf /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav.installed /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav
mkdir -p /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav
install -d -m0755 /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav/usr/bin
install -m0755 /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/target/x86_64-unknown-linux-musl/stripped/aliyundrive-webdav /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav/usr/bin/
install: cannot stat '/home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/target/x86_64-unknown-linux-musl/stripped/aliyundrive-webdav': No such file or directory
make[3]: *** [Makefile:57: /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/aliyundrive-webdav-2.3.2/.pkgdir/aliyundrive-webdav.installed] Error 1
make[3]: Leaving directory '/home/runner/work/op/op/openwrt/feeds/packages/multimedia/aliyundrive-webdav'
time: package/feeds/packages/aliyundrive-webdav/compile#0.16#0.06#0.18
    ERROR: package/feeds/packages/aliyundrive-webdav failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/aliyundrive-webdav/compile] Error 1
make[2]: Leaving directory '/home/runner/work/op/op/openwrt'
make[1]: *** [package/Makefile:110: /home/runner/work/op/op/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/op/op/openwrt'
make: *** [/home/runner/work/op/op/openwrt/include/toplevel.mk:231: world] Error 2
```

**Comment by hztbhtbh** [comment]
使用Actions云编译也是报错，不知道怎么修改，请各位大佬有时间看一下
![屏幕截图 2024-01-18 141447](https://github.com/coolsnowwolf/lede/assets/104251804/7f850231-6e04-4505-93c2-ade4fff8ebbd)
![屏幕截图 2024-01-18 141745](https://github.com/coolsnowwolf/lede/assets/104251804/acd24998-d4d2-497f-bcc6-e1ba639472b6)

**Comment by WYC-2020** [comment]
这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 
failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable')
然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好.
这个aliyundrive-webdav错误 这样修复一下：
![image](https://github.com/coolsnowwolf/lede/assets/34025388/c1d0e07a-c08b-4314-995d-6f655949ff23)
以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧

**Comment by WYC-2020** [comment]
话说alist不香吗 哈哈

**Comment by WYC-2020** [comment]
failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable'  这个问题也搞定了靠，就是本地g++ 版本太低了升级一下即可，在这里留一个记录吧，方便其他人也遇到类似问题

**Comment by schen39** [comment]
> 说alist不香吗哈哈

最新代码alist启动不了，之前的可以

**Comment by WYC-2020** [comment]
> > 说alist不香吗哈哈
> 
> 最新代码alist启动不了，之前的可以

我的可以启动

**Comment by schen39** [comment]
> > > 说alist不香吗哈哈
> > 
> > 
> > 最新代码alist启动不了，之前的可以
> 
> 我的可以启动

3.3.0吗？最新代码？

**Comment by WYC-2020** [comment]
> > > > 说alist不香吗哈哈
> > > 
> > > 
> > > 最新代码alist启动不了，之前的可以
> > 
> > 
> > 我的可以启动
> 
> 3.3.0吗？最新代码？

![image](https://github.com/coolsnowwolf/lede/assets/34025388/345398e4-ecb9-4439-b0aa-4a470e3857bd)
你说的这个版本吧，可以撒 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/c00bc1be-e46d-436e-b451-880ea50c12e2)

**Comment by schen39** [comment]
> > > > > 说alist不香吗哈哈
> > > > 
> > > > 
> > > > 最新代码alist启动不了，之前的可以
> > > 
> > > 
> > > 我的可以启动
> > 
> > 
> > 3.3.0吗？最新代码？
> 
> ![image](https://private-user-images.githubusercontent.com/34025388/297992948-345398e4-ecb9-4439-b0aa-4a470e3857bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTEzMjYsIm5iZiI6MTcwNTY1MTAyNiwicGF0aCI6Ii8zNDAyNTM4OC8yOTc5OTI5NDgtMzQ1Mzk4ZTQtZWNiOS00NDM5LWIwYWEtNGE0NzBlMzg1N2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA3NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwODQ0Y2ExOTc3Y2EzMTcyOTI4MDk2ZWNhODNkYTBmYTgzMDhjYzVhYmNhMDAxM2FhMDBjNTI2ODE0MmIyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OAu75xD1eRp7C7h-hOoS1_JSXricoSTxM3n9hArwFD0) 你说的这个版本吧，可以撒 ![image](https://private-user-images.githubusercontent.com/34025388/297993101-c00bc1be-e46d-436e-b451-880ea50c12e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTEzMjYsIm5iZiI6MTcwNTY1MTAyNiwicGF0aCI6Ii8zNDAyNTM4OC8yOTc5OTMxMDEtYzAwYmMxYmUtZTQ2ZC00MzZlLWI0NTEtODgwZWE1MGMxMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA3NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMmVjNjdkODMyZGE1OWNlODc5YjNhMDJjMTk4MzI4ZGNkZjVkMzUzZWMyYTkzMzE2Yzg3YmZlMmJlYzQ3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DY1ZAcbseGd-ks_vQxDGKZlBq96y-AUSa-C7tfD-lY0)

是的，为啥我的启动不了，晚上我再试试

**Comment by hztbhtbh** [comment]
> 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MDEsIm5iZiI6MTcwNTY3MjUwMSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGUxMGQ2MjJjZWRmMmJjZDk3NjE5MGY3ODZiNGJhMmI5MmYzNjIyMjA3MzhiZjVjYmJiZWI4MzFjYjE0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfN9wcd201l5Q0-Tv81ZujztkKb_Vz0zvPIYZnuxpEI) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧

请问云编译怎么修改呢？

**Comment by binge8** [comment]
sed -i 's/stripped/release/g' feeds/packages/multimedia/aliyundrive-webdav/Makefile

> > 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MDEsIm5iZiI6MTcwNTY3MjUwMSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGUxMGQ2MjJjZWRmMmJjZDk3NjE5MGY3ODZiNGJhMmI5MmYzNjIyMjA3MzhiZjVjYmJiZWI4MzFjYjE0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfN9wcd201l5Q0-Tv81ZujztkKb_Vz0zvPIYZnuxpEI) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧
> 
> 请问云编译怎么修改呢？

**Comment by hztbhtbh** [comment]
> sed -i 's/stripped/release/g' feeds/packages/multimedia/aliyundrive-webdav/Makefile
> 
> > > 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MDEsIm5iZiI6MTcwNTY3MjUwMSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGUxMGQ2MjJjZWRmMmJjZDk3NjE5MGY3ODZiNGJhMmI5MmYzNjIyMjA3MzhiZjVjYmJiZWI4MzFjYjE0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfN9wcd201l5Q0-Tv81ZujztkKb_Vz0zvPIYZnuxpEI) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧
> > 
> > 
> > 请问用P3TERX/Actions-OpenWrt云编译怎么修改呢？之前都设置好了，能编译成功了，这几天就是编译aliyunwebdav就报错。

**Comment by hztbhtbh** [comment]
> sed -i 's/stripped/release/g' feeds/packages/multimedia/aliyundrive-webdav/Makefile
> 
> > > 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MDEsIm5iZiI6MTcwNTY3MjUwMSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGUxMGQ2MjJjZWRmMmJjZDk3NjE5MGY3ODZiNGJhMmI5MmYzNjIyMjA3MzhiZjVjYmJiZWI4MzFjYjE0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfN9wcd201l5Q0-Tv81ZujztkKb_Vz0zvPIYZnuxpEI) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧

**Comment by hztbhtbh** [comment]
谢谢各位，用手机看的没有注意到，哈哈，我已经关闭重复的issues了

**Comment by NeedforGit** [comment]
> sed -i 's/stripped/release/g' feeds/packages/multimedia/aliyundrive-webdav/Makefile
> 
> > > 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzI4MDEsIm5iZiI6MTcwNTY3MjUwMSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzNTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGUxMGQ2MjJjZWRmMmJjZDk3NjE5MGY3ODZiNGJhMmI5MmYzNjIyMjA3MzhiZjVjYmJiZWI4MzFjYjE0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfN9wcd201l5Q0-Tv81ZujztkKb_Vz0zvPIYZnuxpEI) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧
> > 
> > 
> > 请问云编译怎么修改呢？

感谢！

**Comment by zhangj3** [comment]
> failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable' 这个问题也搞定了靠，就是本地g++ 版本太低了升级一下即可，在这里留一个记录吧，方便其他人也遇到类似问题

你好，请问下您是怎么修复的？ 我按照这个升级了g++http://pointborn.com/article/2023/6/12/2175.html 后还是报错

![image](https://github.com/coolsnowwolf/lede/assets/49198958/6630cb44-5373-470c-b93c-2e7ca0406057)

**Comment by ddcatgg** [comment]
同问

**Comment by ddcatgg** [comment]
> > failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable' 这个问题也搞定了靠，就是本地g++ 版本太低了升级一下即可，在这里留一个记录吧，方便其他人也遇到类似问题
> 
> 你好，请问下您是怎么修复的？ 我按照这个升级了g++http://pointborn.com/article/2023/6/12/2175.html 后还是报错
> 
> ![image](https://private-user-images.githubusercontent.com/49198958/302176342-6630cb44-5373-470c-b93c-2e7ca0406057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NTkyNzQsIm5iZiI6MTcwNzQ1ODk3NCwicGF0aCI6Ii80OTE5ODk1OC8zMDIxNzYzNDItNjYzMGNiNDQtNTM3My00NzBjLWI5M2MtMmU3Y2EwNDA2MDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDA2MDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MDY5NTNkYzc3MzM0ZDkyNmM1OGZkMTNkNTM5MjY5NzA0ZDdiMTZjZTZhODA3N2M1ZmQ5M2MyYWI0MzExNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZuoLQXsDOZkOl-N07DDo57hlwzNtvdnfpIPPXOh3NGU)

同问

**Comment by coolsnowwolf** [comment]
> > failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable' 这个问题也搞定了靠，就是本地g++ 版本太低了升级一下即可，在这里留一个记录吧，方便其他人也遇到类似问题
> 
> 你好，请问下您是怎么修复的？ 我按照这个升级了g++http://pointborn.com/article/2023/6/12/2175.html 后还是报错
> 
> ![image](https://private-user-images.githubusercontent.com/49198958/302176342-6630cb44-5373-470c-b93c-2e7ca0406057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODQzMzgsIm5iZiI6MTcwODU4NDAzOCwicGF0aCI6Ii80OTE5ODk1OC8zMDIxNzYzNDItNjYzMGNiNDQtNTM3My00NzBjLWI5M2MtMmU3Y2EwNDA2MDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA2NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNmUyNjhmMWE3NDNlMGM5YWRlMTAzYjczMTNlMjA2ZmQ0MmRmZWUzZWY3N2RlMmFjNDQ1YTNmOWI4MTY3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KFtx53U1tE5JmgJJ3WEQZ_q0z0RTpJRTpW1Twy6Ibbg)

需要 g++ 9 以上，主系统

**Comment by hztbhtbh** [comment]
我这边是虚拟机安装ubuntu18出现的问题，然后我直接换成ubuntu20或者更高版本就不存在这个问题了，可能ubuntu20里的g++也升级了吧

**Comment by Zurisepinoy** [comment]
> 这错误都是小问题，最大的问题是 rust这玩意编译 可能会遇到 类似这种错误 failed to parse bitcode for LTO module: Invalid alignment value (Producer: 'LLVM17.0.6-rust-1.75.0-stable' Reader: 'LLVM 17.0.6-rust-1.75.0-stable') 然后这种可能就是gcc适配有问题，因为 rust好像是下载的预编译好的llvm，在用预编译的工具链来编译的时候 就会出现这个问题 gcc13 是肯定了，这个时候只能开启不用预编译的 自己编译多增加一个小时，其他gcc没试过，看你们都走到这里才出错 那就是你们rust这玩意没出错运气好. 这个aliyundrive-webdav错误 这样修复一下： ![image](https://private-user-images.githubusercontent.com/34025388/297692622-c1d0e07a-c08b-4314-995d-6f655949ff23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODM2NTEsIm5iZiI6MTcyMzI4MzM1MSwicGF0aCI6Ii8zNDAyNTM4OC8yOTc2OTI2MjItYzFkMGUwN2EtYzA4Yi00MzE0LTk5NWQtNmY2NTU5NDlmZjIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA5NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmNlODg5YjEzZTU1YjlkNWNmNTJjNjJkZGNiYzVlYzJkN2U2OGJiYjMxYTY0ZmQ3NTcwNGQ3YTY4MzQyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8cCTZmkhGZHdEKlKHiskxkGWNZPuvpUjZEdcsXMkOM) 以前这个阿里云是直接下载现成的不需要编译的不知道什么原因改成编译的，可能现成的不行吧

![1](https://github.com/user-attachments/assets/40d9a5ca-744f-45a2-8267-6e8be3f26e34)

你好，请问我这个也是gcc适配的问题吗，但我试过了gcc 9 11 13,都失败了
