### ISSUE TITLE
Actions云编译aliyundrive-webdav报错

### ISSUE THREAD

**Issue by hztbhtbh** [coolsnowwolf/lede#11804]
### 详细叙述

用P3TERX/Actions-OpenWrt云编译，修改过build-openwrt.yml后，添加config文件后都编译成功了，这两天出现编译到aliyundrive-webdav报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

![111](https://github.com/coolsnowwolf/lede/assets/104251804/66df5878-ae90-460a-b1e3-e9b0a91012b2)
不知道在下图中怎么修改
![IMG_20240119_220244](https://github.com/coolsnowwolf/lede/assets/104251804/8bf09625-2d32-414d-9801-1e9fc41797f5)

**Comment by WYC-2020** [comment]
多上心嘛，另外一个issue不是有吗非要单独提一些重复的
