### ISSUE TITLE
能科学上网，但是chrome自身无法更新

### ISSUE THREAD

**Issue by xayane** [coolsnowwolf/lede#11806]
### 详细叙述

本人采用的SSR+，无passwall和smartdns
自建梯子，一直以来都能科学上网，最近突然发现家里台式机的chrome无法更新。
我尝试着关闭广告过滤，关闭ipv6解析。chrome还是无法更新，但是打开google、油管、twitter都没问题。
我排查了下，发现dl.google.com这个可以正常解析，但是就是无法打开网页。
这个是什么原因造成的呢，我怎么排查是什么阻止了我打开dl.google.com

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

小马软路由 cpu N3160

### 详细日志

暂无编译日志

**Comment by Cathgao** [comment]
小知识，Chrome更新没有墙

**Comment by xayane** [comment]
> 小知识，Chrome更新没有墙

我到今天才知道。。。更新没有被墙。。。

**Comment by xayane** [comment]
无意间，我同事的一台电脑，在我家可以更新chrome。我发现他的dns用的114。
我才对比了下发现，我的软路由把dl.google.com解析到了国外。感觉应该是分流的问题，用了ip.cn也显示我在国外。
