### ISSUE TITLE
最近更新了uqmi， arm编译就一直失败

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#11811]
### 详细叙述

arm 云编译出错导致超时，X86表示没有影响

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

R4S R86S

### 详细日志

make[3] -C package/network/utils/uqmi compile
    ERROR: package/network/utils/uqmi failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/runner/work/AutoLede/AutoLede/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/home/runner/work/AutoLede/AutoLede/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/runner/work/AutoLede/AutoLede/openwrt/scripts/config'

**Comment by hzjnet** [comment]
确实有问题

**Comment by WYC-2020** [comment]
那是因为那样修不行的，随时gcc12以上需要这样修，但是低版本是不行的，我修复是记录gcc主版本然后进行比较进行修复的

**Comment by WYC-2020** [comment]
关于这个 我以前就说过了修复方法 ，在这里，只是你们没人搞而已，https://github.com/coolsnowwolf/lede/pull/10825

**Comment by WYC-2020** [comment]
然后改成这样 就能兼容目前所有的gcc 
 ifneq ($(filter $(GCC_MAJOR_VERSION),12 13),)
	TARGET_CFLAGS += -Wno-error=dangling-pointer -Wno-error=maybe-uninitialized
endif

**Comment by sxml** [comment]
本地没编译条件 用Actions OpenWrt 云编译好麻烦 一会这报错那报错 之前还acpid 现在又uqmi.都不测试直接上的？

**Comment by FlawShatter** [comment]
> ifneq (
> (
> �
> �
> �
> �
> �
> �
> (GCC_MAJOR_VERSION),12 13),)
> TARGET_CFLAGS += -Wno-error=dangling-pointer -Wno-error=maybe-uninitialized
> endif

前几天学你更新gcc13，有些包报重复使用已释放的指针😂（C++的哪些，比如ssr-lib），原来是差这一句，感谢感谢👍

**Comment by liwenjie119** [comment]
> 然后改成这样 就能兼容目前所有的gcc ifneq ((filter(GCC_MAJOR_VERSION),12 13),) TARGET_CFLAGS += -Wno-error=dangling-pointer -Wno-error=maybe-uninitialized endif

 就等大佬提交合并了，比较小白看了之前的那个提交没太看明白

**Comment by qqsir-dev** [comment]
我在我自己的仓库试着改，但是没成功，水平不行。还是等大佬吧！
