### ISSUE TITLE
daemon.err uhttpd[4129]: sh: out of range

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#11828]
### 详细叙述

系统日志经常出现这个错误什么情况，软路由6.6.14
daemon.err uhttpd[4129]: sh: out of range
daemon.err uhttpd[4129]: sh: out of range

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

不是编译错误，刷完固件的系统日志

**Comment by coolsnowwolf** [comment]
无所谓

**Comment by binge8** [comment]
好的，谢谢。
