### ISSUE TITLE
x86 6.6内核编译  kmod-fs-cifs 缺少库

### ISSUE THREAD

**Issue by King-Of-Knights** [coolsnowwolf/lede#11825]
### 详细叙述

提示缺少相应的库，sudo apt 已经最新

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

```
make[2]: Entering directory '/home/saber/Desktop/lede/package/kernel/linux'
Package kmod-fs-cifs is missing dependencies for the following libraries:
asn1_decoder.ko
dns_resolver.ko
netfs.ko
nls_ucs2_utils.ko
oid_registry.ko
make[2]: *** [modules/fs.mk:142: /home/saber/Desktop/lede/bin/targets/x86/64/packages/kmod-fs-cifs_6.6.13-1_x86_64.ipk] Error 1
```

**Comment by WYC-2020** [comment]
重复issue很舒服吗

**Comment by King-Of-Knights** [comment]
@WYC-2020 呃，我看今天下午正式发布了，以为编译没有问题了。。。

**Comment by WYC-2020** [comment]
> @WYC-2020 呃，我看今天下午正式发布了，以为编译没有问题了。。。

放心问题多的很，特别是模块方面的，你看嘛明天issue绝对炸 哈哈，慢慢修，有的玩，你这个 看第二个issue 有说怎么处理

**Comment by King-Of-Knights** [comment]
@WYC-2020 感谢大佬了，那就等修复了

**Comment by GreatMichaelLee** [comment]
> > @WYC-2020 呃，我看今天下午正式发布了，以为编译没有问题了。。。
> 
> 放心问题多的很，特别是模块方面的，你看嘛明天issue绝对炸 哈哈，慢慢修，有的玩，你这个 看第二个issue 有说怎么处理

哈哈，旧病成良医，这个issue是我翻以前刚上6.1的时候出现同样的问题上找出来的一毛一样的修改。同时支持的内核版本多，就是这么挠头。

**Comment by King-Of-Knights** [comment]
@GreatMichaelLee any suggestion？

**Comment by GreatMichaelLee** [comment]
> @GreatMichaelLee any suggestion？

多看issue啊，看我提的issue啊, W大佬已经截图给了啊，本地照着改就行了，不急的话就等大佬们提交了，哈哈
