### ISSUE TITLE
libopenssl-legacy 依赖问题

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#11836]
### 详细叙述

helloworld  提示依赖找不到

并且，广告屏蔽大师 Plus+ 只要启用网络就断了。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

Create index file './feeds/packages.index' 
Create index file './feeds/luci.index' 
Create index file './feeds/routing.index' 
Create index file './feeds/telephony.index' 
Create index file './feeds/helloworld.index' 
Create index file './feeds/Alist.index' 
WARNING: Makefile 'package/feeds/helloworld/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/helloworld/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/helloworld/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/helloworld/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/helloworld/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed helloworld.
Installing all packages from feed Alist.

**Comment by ilxp** [comment]
同样编译报错。

**Comment by WYC-2020** [comment]
你们自己openssl 回退过吧 我记得不错的话 这个是openssl 3 后面新做的一个模块 老的协议 必须依赖这个玩意

**Comment by caixin1218** [comment]
> 你们自己openssl 回退过吧 我记得不错的话 这个是openssl 3 后面新做的一个模块 老的协议 必须依赖这个玩意

没有回退，git pull 
./scripts/feeds update -a   
./scripts/feeds install -a
之后就是这样的。

**Comment by WYC-2020** [comment]
那应该这里有才对撒 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/e827e709-ba71-4091-9047-7c27a022e1b2)
不可能会出现没有这个包哦

**Comment by caixin1218** [comment]
> > 你们自己openssl 回退过吧 我记得不错的话 这个是openssl 3 后面新做的一个模块 老的协议 必须依赖这个玩意
> 
> 没有回退，git pull ./scripts/feeds update -a ./scripts/feeds install -a 之后就是这样的。

![image](https://github.com/coolsnowwolf/lede/assets/88958866/cb4f1810-28fb-4de5-b53d-8f1cdc7564b8)

还真的没有

**Comment by WYC-2020** [comment]
你怕是有毒吧哈哈，我看l的仓库 openssl就有这玩意 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/1c88e771-2384-412a-b637-d70fe6fe4e41)

**Comment by caixin1218** [comment]
> 你怕是有毒吧哈哈，我看l的仓库 openssl就有这玩意 ![image](https://private-user-images.githubusercontent.com/34025388/300326549-1c88e771-2384-412a-b637-d70fe6fe4e41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTk1NjAsIm5iZiI6MTcwNjQ5OTI2MCwicGF0aCI6Ii8zNDAyNTM4OC8zMDAzMjY1NDktMWM4OGU3NzEtMjM4NC00MTJhLWI2MzctZDcwZmU2ZmU0ZTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNjc5YjMwZDQyMmU2YTc2MTg4YjNmMzRkN2NlMjQ4OGExY2FjMzhmYzBmZGM3MTE5NGU3NDBhNDQ0MDRhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PQ2_7afNEJlAcAIjB7_NEEaw3xoyW3gZjW1RqQ11Lk)

你真幽默，我也看到了，但就不知道是什么原因，makd distclean 都干过没用。

**Comment by caixin1218** [comment]
> 你怕是有毒吧哈哈，我看l的仓库 openssl就有这玩意 ![image](https://private-user-images.githubusercontent.com/34025388/300326549-1c88e771-2384-412a-b637-d70fe6fe4e41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTk1NjAsIm5iZiI6MTcwNjQ5OTI2MCwicGF0aCI6Ii8zNDAyNTM4OC8zMDAzMjY1NDktMWM4OGU3NzEtMjM4NC00MTJhLWI2MzctZDcwZmU2ZmU0ZTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMzQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNjc5YjMwZDQyMmU2YTc2MTg4YjNmMzRkN2NlMjQ4OGExY2FjMzhmYzBmZGM3MTE5NGU3NDBhNDQ0MDRhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PQ2_7afNEJlAcAIjB7_NEEaw3xoyW3gZjW1RqQ11Lk)

如果 没有Helloworld 就没有问题。

**Comment by WYC-2020** [comment]
怕不是什么配置 导致 openssl没有全部打开选项吧 你是默认config配置 都不能看到这个玩意？

**Comment by caixin1218** [comment]
> 怕不是什么配置 导致 openssl没有全部打开选项吧 你是默认config配置 都不能看到这个玩意？

rm -rf    feeds   .config  还是看不到

**Comment by caixin1218** [comment]
![微信截图_20240129115520](https://github.com/coolsnowwolf/lede/assets/88958866/39c853ec-40e3-475c-8e47-a442cd1abe3d)
还是这样，应该是源码哪个地方问题。

**Comment by WYC-2020** [comment]
可怜的孩子

**Comment by 725216** [comment]
一样的问题
Configuring ppp-mod-pppoe.
Configuring dnsmasq-full.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-ssr-plus-zh-cn:
 * 	libopenssl-legacy
 * opkg_install_cmd: Cannot install package luci-i18n-ssr-plus-zh-cn.
Makefile:154: recipe for target 'package_install' failed
make[2]: *** [package_install] Error 255
Makefile:112: recipe for target '_call_image' failed
make[1]: *** [_call_image] Error 2
Makefile:207: recipe for target 'image' failed
make: *** [image] Error 2
