### ISSUE TITLE
6.1内核下quectel-MHI编译失败

### ISSUE THREAD

**Issue by xosadmin** [coolsnowwolf/lede#11846]
### 详细叙述

在6.1内核下quectel-MHI的pcie_mhi编译失败，使用5.5内核编译正常。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

photonicat

### 详细日志

make -C "/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.75" ARCH="arm64" CROSS_COMPILE="aarch64-openwrt-linux-musl-" CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2=pcie_mhi-3.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" M="/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2"  modules
make[4]: Entering directory '/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.75'
  CC [M]  /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_init.o
  CC [M]  /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_main.o
  CC [M]  /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_pm.o
  CC [M]  /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_boot.o
/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_boot.c: In function '__mhi_download_rddm_in_panic':
/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_boot.c:203:23: error: implicit declaration of function 'prandom_u32'; did you mean 'prandom_u32_max'? [-Werror=implicit-function-declaration]
  203 |         sequence_id = prandom_u32() & BHIE_RXVECSTATUS_SEQNUM_BMSK;
      |                       ^~~~~~~~~~~
      |                       prandom_u32_max
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:250: /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/core/mhi_boot.o] Error 1
make[4]: *** [Makefile:2014: /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2] Error 2
make[4]: Leaving directory '/home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.75'
make[3]: *** [Makefile:50: /home/user/lean/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/pcie_mhi-3.2/.built] Error 2
make[3]: Leaving directory '/home/user/lean/package/wwan/driver/quectel_MHI'
time: package/wwan/driver/quectel_MHI/compile#4.54#0.53#5.14
    ERROR: package/wwan/driver/quectel_MHI failed to build.
make[2]: *** [package/Makefile:116: package/wwan/driver/quectel_MHI/compile] Error 1
make[2]: Leaving directory '/home/user/lean'
make[1]: *** [package/Makefile:110: /home/user/lean/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/lean'
make: *** [/home/user/lean/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
尴尬了我x86 试了一下 没错 有不想编译 你那个平台 哈哈

**Comment by WYC-2020** [comment]
刚亲测了和你相同的平台和内核 没有任何问题 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/59e5c748-4fc0-45b0-8cf4-ac953e0e04d4)

**Comment by xosadmin** [comment]
好的，我更新下源码再试试看

**Comment by xosadmin** [comment]
> 刚亲测了和你相同的平台和内核 没有任何问题 ![image](https://private-user-images.githubusercontent.com/34025388/301016229-59e5c748-4fc0-45b0-8cf4-ac953e0e04d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTQ1MDAsIm5iZiI6MTcwNjcxNDIwMCwicGF0aCI6Ii8zNDAyNTM4OC8zMDEwMTYyMjktNTllNWM3NDgtNGZjMC00NWIwLThjZjQtYWM5NTNlMGUwNGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE1MTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZGNjZjM0NzljNzk2OGQ5ZTlkMzNmMmQyZDJmZTljMDkxYTFlNTcwYTY3YWNiZTBhMDQ5OTUzMDRlYjdkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TGop_szQQyaitiZfyKiUKv2pMH1N5P2xB7N_T-4VF0U)

我更新了源码，编译还是存在相同的问题。请问这和编译环境有关系吗？请问您的编译环境是？

**Comment by suizhenmin** [comment]
卡在了同一个地方，同样的报错

**Comment by xosadmin** [comment]
> 在隔壁找到了原因
> 
> sudo apt install clang

您最后编译成功了吗？我安装了这个包后编译光影猫的固件，仍然存在相同的问题。

**Comment by suizhenmin** [comment]
> > 在隔壁找到了原因
> > sudo apt install clang
> 
> 您最终编译成功了吗？我安装了这个包后编译了photonicat的固件，仍然存在相同的问题。

我安装后编译成功了
