### ISSUE TITLE
关于802.11r的一点建议和疑问？

### ISSUE THREAD

**Issue by xunqiuhuiyi** [coolsnowwolf/lede#1187]
关于R9新版的802.1r有几点小的建议，希望大雕测试
1、建议所有AP的SSID使用相同信道，设备相互范围最好能少重复区域，单必须要有重复区域，这样切换的时候不容易丢包，也比较快，大多300MS以内；
2、建议FT协议使用air  大概找了下说明 air既兼容ds的有线  又带无线 认证更快 具体多设备的情况下 更流畅
3、关于5G和2.4G同SSID漫游的情况下，手机（华为P30P）优先连接的2.4G 然后各个点位切换就是2.4G ，个人把AP一些开5G一些开2.4G测试，5G切换2.4G很流畅，但是2.4G切不回5G，这里就出现2个问题，一是优选5G，二是2.4G切回5G，希望大雕可以测试下，谢谢

**Comment by xlighting2017** [comment]
切换/漫游的选择权在 STA 也就是终端手上，不在AP侧

**Comment by zxlhhyccc** [comment]
R9新版有802.1r吗？我怎么没找到呢？请问在是哪个包？
