### ISSUE TITLE
MT7622平台内核编译失败

### ISSUE THREAD

**Issue by hpx502766238** [coolsnowwolf/lede#11870]
### 详细叙述

内核编译失败

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

XiaomiRedmiAX6S

### 详细日志

rm -f /home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/image-mt7622-bananapi-bpi-r64.dtb.tmp
aarch64-openwrt-linux-musl-cpp -nostdinc -x assembler-with-cpp  -I/home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.148/arch/arm64/boot/dts/mediatek -I/home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.148/arch/arm64/boot/dts/mediatek/include -I/home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.148/include/ -undef -D__DTS__  -o /home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/image-mt7622-bananapi-bpi-r64-pcie1.dtb.tmp /home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.148/arch/arm64/boot/dts/mediatek/mt7622-bananapi-bpi-r64-pcie1.dts
cc1: fatal error: /home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/linux-5.15.148/arch/arm64/boot/dts/mediatek/mt7622-bananapi-bpi-r64-pcie1.dts: No such file or directory
compilation terminated.
make[5]: *** [Makefile:36: /home/mrhpx/openwrt-lean/lede/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/image-mt7622-bananapi-bpi-r64-pcie1.dtb] Error 1
make[5]: Leaving directory '/home/mrhpx/openwrt-lean/lede/target/linux/mediatek/image'
make[4]: *** [Makefile:18: install] Error 2
make[4]: Leaving directory '/home/mrhpx/openwrt-lean/lede/target/linux/mediatek'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/mrhpx/openwrt-lean/lede/target/linux'
time: target/linux/install#26.12#2.08#28.41
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/mrhpx/openwrt-lean/lede'
make[1]: *** [target/Makefile:24: /home/mrhpx/openwrt-lean/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/mrhpx/openwrt-lean/lede'
make: *** [/home/mrhpx/openwrt-lean/lede/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
已修复
