### ISSUE TITLE
 mediatek 6.1

### ISSUE THREAD

**Issue by mirthlesslk** [coolsnowwolf/lede#11890]
### 详细叙述

大佬加油！！

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

6086

### 详细日志

Hunk #3 FAILED at 44.
1 out of 6 hunks FAILED -- saving rejects to file arch/arm64/boot/dts/mediatek/mt7622-rfb1.dts.rej
Patch failed!  Please fix /workdir/openwrt/target/linux/mediatek/patches-6.1/100-dts-update-mt7622-rfb1.patch!
make[4]: *** [Makefile:29: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.77/.prepared_ae6bd946efdcf7b689cc2c052715bd68] Error 1
make[3]: *** [Makefile:11: compile] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/mediatek'
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#12.22#5.48#15.65
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by shigechuanqi** [comment]
最近的更新是这样的可以先恢复到历史版本...
