### ISSUE TITLE
360T7重置按键无效

### ISSUE THREAD

**Issue by hongCchao** [coolsnowwolf/lede#11900]
### 详细叙述

360T7编译的固件 reset按键功能无效  路由器修改错误配置后 无法reset按钮还原默认配置

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

qihoo360t7

### 详细日志

360T7编译的固件 reset按键功能无效  路由器修改错误配置后 无法reset按钮还原默认配置

**Comment by aiamadeus** [comment]
https://github.com/coolsnowwolf/lede/commit/2843c0b9112fe6515a2e3a56fd78d155a2607d62 修过了，自己再检查下内核日志
