### ISSUE TITLE
使用最新的源码编译AX3600没有WiFi

### ISSUE THREAD

**Issue by sxf5487** [coolsnowwolf/lede#11903]
### 详细叙述

使用最新的源码编译AX3600没有WiFi，其他功能正常，大佬能修复下吗？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

小米 ax3600

### 详细日志

编制正常完成。

**Comment by mitsukileung** [comment]
ax6编译出来的固件WIFI正常

**Comment by sxf5487** [comment]
我使用的是最新源码，6.1的内存，你ax6是哪个版本的内核啊，谢谢！

**Comment by sxf5487** [comment]
> ax6编译出来的固件WIFI正常

我使用的是最新源码，6.1的内核，你ax6是哪个版本的内核啊，谢谢！

**Comment by mitsukileung** [comment]
我是昨天才更新源码编译的，现在ax6内核不是只有6.1，还有其他内核可选吗？
