### ISSUE TITLE
ARMVirt 编译出错

### ISSUE THREAD

**Issue by leochien0102** [coolsnowwolf/lede#11902]
### 详细叙述

编译ARM Virtual Machine，64bit， Generic EFI Boot，256Mib Kernel partion size，768Mib Root filesystem partition size

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

N1

### 详细日志

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 1048576
        compressed data, compressed metadata, compressed fragments,
        no xattrs, compressed ids
        duplicates are removed
Filesystem size 43675.83 Kbytes (42.65 Mbytes)
        24.45% of uncompressed filesystem size (178663.10 Kbytes)
Inode table size 29096 bytes (28.41 Kbytes)
        20.66% of uncompressed inode table size (140806 bytes)
Directory table size 38696 bytes (37.79 Kbytes)
        41.95% of uncompressed directory table size (92243 bytes)
Number of duplicate files found 411
Number of inodes 4217
Number of files 3415
Number of fragments 59
Number of symbolic links  452
Number of device nodes 1
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 349
Number of ids (unique uids + gids) 1
Number of uids 1
        root (0)
Number of gids 1
        root (0)
/home/leochien/workspace/openwrt_lean/staging_dir/host/bin/make_ext4fs -L rootfs -l 805306368 -b 4096 -m 0 -J -T 1708169411 /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.ext4 /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/root-armvirt/
Creating filesystem with parameters:
    Size: 805306368
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 0
    Label: rootfs
    Blocks: 196608
    Block groups: 6
    Reserved blocks: 0
    Reserved block group size: 47
Created filesystem with 4226/49152 inodes and 50908/196608 blocks
rm -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-initramfs-kernel.bin
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/vmlinux-initramfs /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-initramfs-kernel.bin
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-initramfs-kernel.bin /home/leochien/workspace/openwrt_lean/bin/targets/armvirt/64/openwrt-armvirt-64-generic-initramfs-kernel.bin
DEVICE_ID="generic" SOURCE_DATE_EPOCH=1708169411 FILE_NAME="openwrt-armvirt-64-generic-initramfs-kernel.bin" FILE_DIR="/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp" FILE_TYPE="kernel" FILE_FILESYSTEM="initramfs" DEVICE_IMG_PREFIX="openwrt-armvirt-64-generic" DEVICE_VENDOR="" DEVICE_MODEL="" DEVICE_VARIANT="" DEVICE_ALT0_VENDOR="" DEVICE_ALT0_MODEL="" DEVICE_ALT0_VARIANT="" DEVICE_ALT1_VENDOR="" DEVICE_ALT1_MODEL="" DEVICE_ALT1_VARIANT="" DEVICE_ALT2_VENDOR="" DEVICE_ALT2_MODEL="" DEVICE_ALT2_VARIANT="" DEVICE_ALT3_VENDOR="" DEVICE_ALT3_MODEL="" DEVICE_ALT3_VARIANT="" DEVICE_ALT4_VENDOR="" DEVICE_ALT4_MODEL="" DEVICE_ALT4_VARIANT="" DEVICE_TITLE="Generic EFI Boot" DEVICE_PACKAGES="kmod-amazon-ena kmod-e1000e kmod-mvpp2 kmod-vmxnet3 kmod-fsl-dpaa2-net kmod-sfp kmod-phy-aquantia kmod-phy-marvell kmod-dwmac-imx kmod-fsl-fec kmod-thunderx-net kmod-i2c-mux-pca954x kmod-gpio-pca953x kmod-rtc-rx8025 partx-utils" TARGET="armvirt" SUBTARGET="64" VERSION_NUMBER="SNAPSHOT" VERSION_CODE="r6439-0ea4b6430" SUPPORTED_DEVICES="" /home/leochien/workspace/openwrt_lean/scripts/json_add_image_info.py /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/json_info_files/openwrt-armvirt-64-generic-initramfs-kernel.bin.json
rm -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/vmlinux /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin /home/leochien/workspace/openwrt_lean/bin/targets/armvirt/64/openwrt-armvirt-64-generic-kernel.bin
[ -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin -a -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.ext4 ]
dd if=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.ext4 >> /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz
1572864+0 records in
1572864+0 records out
805306368 bytes (805 MB, 768 MiB) copied, 1.90273 s, 423 MB/s
dd if=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz of=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz.new bs=805306368 conv=sync
1+0 records in
1+0 records out
805306368 bytes (805 MB, 768 MiB) copied, 0.439197 s, 1.8 GB/s
mv /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz.new /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz
/home/leochien/workspace/openwrt_lean/staging_dir/host/bin/gzip -f -9n -c /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz  > /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz.new
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-rootfs.img.gz /home/leochien/workspace/openwrt_lean/bin/targets/armvirt/64/openwrt-armvirt-64-generic-ext4-rootfs.img.gz
DEVICE_ID="generic" SOURCE_DATE_EPOCH=1708169411 FILE_NAME="openwrt-armvirt-64-generic-ext4-rootfs.img.gz" FILE_DIR="/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp" FILE_TYPE=rootfs FILE_FILESYSTEM="ext4" DEVICE_IMG_PREFIX="openwrt-armvirt-64-generic" DEVICE_VENDOR="" DEVICE_MODEL="" DEVICE_VARIANT="" DEVICE_ALT0_VENDOR="" DEVICE_ALT0_MODEL="" DEVICE_ALT0_VARIANT="" DEVICE_ALT1_VENDOR="" DEVICE_ALT1_MODEL="" DEVICE_ALT1_VARIANT="" DEVICE_ALT2_VENDOR="" DEVICE_ALT2_MODEL="" DEVICE_ALT2_VARIANT="" DEVICE_ALT3_VENDOR="" DEVICE_ALT3_MODEL="" DEVICE_ALT3_VARIANT="" DEVICE_ALT4_VENDOR="" DEVICE_ALT4_MODEL="" DEVICE_ALT4_VARIANT="" DEVICE_TITLE="Generic EFI Boot" DEVICE_PACKAGES="kmod-amazon-ena kmod-e1000e kmod-mvpp2 kmod-vmxnet3 kmod-fsl-dpaa2-net kmod-sfp kmod-phy-aquantia kmod-phy-marvell kmod-dwmac-imx kmod-fsl-fec kmod-thunderx-net kmod-i2c-mux-pca954x kmod-gpio-pca953x kmod-rtc-rx8025 partx-utils" TARGET="armvirt" SUBTARGET="64" VERSION_NUMBER="SNAPSHOT" VERSION_CODE="r6439-0ea4b6430" SUPPORTED_DEVICES="" /home/leochien/workspace/openwrt_lean/scripts/json_add_image_info.py /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/json_info_files/openwrt-armvirt-64-generic-ext4-rootfs.img.gz.json
[ -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin -a -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.squashfs ]
dd if=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.squashfs >> /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz
87351+1 records in
87351+1 records out
44724048 bytes (45 MB, 43 MiB) copied, 0.100073 s, 447 MB/s
dd if=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz of=/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz.new bs=805306368 conv=sync
0+1 records in
1+0 records out
805306368 bytes (805 MB, 768 MiB) copied, 0.366682 s, 2.2 GB/s
mv /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz.new /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz
/home/leochien/workspace/openwrt_lean/staging_dir/host/bin/gzip -f -9n -c /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz  > /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz.new
cp /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz /home/leochien/workspace/openwrt_lean/bin/targets/armvirt/64/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz
DEVICE_ID="generic" SOURCE_DATE_EPOCH=1708169411 FILE_NAME="openwrt-armvirt-64-generic-squashfs-rootfs.img.gz" FILE_DIR="/home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp" FILE_TYPE=rootfs FILE_FILESYSTEM="squashfs" DEVICE_IMG_PREFIX="openwrt-armvirt-64-generic" DEVICE_VENDOR="" DEVICE_MODEL="" DEVICE_VARIANT="" DEVICE_ALT0_VENDOR="" DEVICE_ALT0_MODEL="" DEVICE_ALT0_VARIANT="" DEVICE_ALT1_VENDOR="" DEVICE_ALT1_MODEL="" DEVICE_ALT1_VARIANT="" DEVICE_ALT2_VENDOR="" DEVICE_ALT2_MODEL="" DEVICE_ALT2_VARIANT="" DEVICE_ALT3_VENDOR="" DEVICE_ALT3_MODEL="" DEVICE_ALT3_VARIANT="" DEVICE_ALT4_VENDOR="" DEVICE_ALT4_MODEL="" DEVICE_ALT4_VARIANT="" DEVICE_TITLE="Generic EFI Boot" DEVICE_PACKAGES="kmod-amazon-ena kmod-e1000e kmod-mvpp2 kmod-vmxnet3 kmod-fsl-dpaa2-net kmod-sfp kmod-phy-aquantia kmod-phy-marvell kmod-dwmac-imx kmod-fsl-fec kmod-thunderx-net kmod-i2c-mux-pca954x kmod-gpio-pca953x kmod-rtc-rx8025 partx-utils" TARGET="armvirt" SUBTARGET="64" VERSION_NUMBER="SNAPSHOT" VERSION_CODE="r6439-0ea4b6430" SUPPORTED_DEVICES="" /home/leochien/workspace/openwrt_lean/scripts/json_add_image_info.py /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/json_info_files/openwrt-armvirt-64-generic-squashfs-rootfs.img.gz.json
[ -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/generic-kernel.bin -a -f /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/root.ext4 ]
rm -fR /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot
install -d -m0755 /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/boot/grub
sed -e 's#@SERIAL_CONFIG@#serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1 --rtscts=off#g' -e 's#@TERMINAL_CONFIG@#terminal_input serial; terminal_output serial#g' -e 's#@ROOTPART@#root=PARTUUID=d954e8d3-02 rootwait#g' -e 's#@GPT_ROOTPART@#root=PARTUUID=d954e8d3-e8f4-8ac3-4b86-c63ee5d40402 rootwait#g' -e 's#@CMDLINE@# earlycon#g' -e 's#@TIMEOUT@#0#g' -e 's#@TITLE@#OpenWrt#g' ./grub-efi.cfg > /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/boot/grub/grub.cfg
cp -fpR /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/vmlinux /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/boot/vmlinux
cp -fpR /home/leochien/workspace/openwrt_lean/staging_dir/target-aarch64_generic_musl/root-armvirt/boot/. /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/boot/
cp: cannot stat '/home/leochien/workspace/openwrt_lean/staging_dir/target-aarch64_generic_musl/root-armvirt/boot/.': No such file or directory
make[5]: [Makefile:114: /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz] Error 1 (ignored)
install -d -m0755 /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/efi/boot
cp -fpR /home/leochien/workspace/openwrt_lean/staging_dir/target-aarch64_generic_musl/image/grub2/bootaa64.efi /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz.boot/efi/boot/
cp: cannot stat '/home/leochien/workspace/openwrt_lean/staging_dir/target-aarch64_generic_musl/image/grub2/bootaa64.efi': No such file or directory
make[5]: *** [Makefile:114: /home/leochien/workspace/openwrt_lean/build_dir/target-aarch64_generic_musl/linux-armvirt_64/tmp/openwrt-armvirt-64-generic-ext4-combined.img.gz] Error 1
make[5]: Leaving directory '/home/leochien/workspace/openwrt_lean/target/linux/armvirt/image'
make[4]: *** [Makefile:18: install] Error 2
make[4]: Leaving directory '/home/leochien/workspace/openwrt_lean/target/linux/armvirt'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/leochien/workspace/openwrt_lean/target/linux'
time: target/linux/install#177.51#10.44#142.91
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/leochien/workspace/openwrt_lean'
make[1]: *** [target/Makefile:24: /home/leochien/workspace/openwrt_lean/staging_dir/target-aarch64_generic_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/leochien/workspace/openwrt_lean'
make: *** [/home/leochien/workspace/openwrt_lean/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
已修复
