### ISSUE TITLE
大佬们，这是什么问题    ERROR: package/feeds/packages/v2dat failed to build.

### ISSUE THREAD

**Issue by authon** [coolsnowwolf/lede#11929]
### 详细叙述

编译出现这个，请问怎么解决

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

 make[3] -C feeds/packages/libs/gperf host-compile
 make[3] -C feeds/packages/utils/v2dat compile
    ERROR: package/feeds/packages/v2dat failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/Ledemaster/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/Ledemaster/openwrt/scripts/config'
make[1]: Entering directory '/Ledemaster/openwrt'
make[2]: Entering directory '/Ledemaster/openwrt'
make[3]: Entering directory '/Ledemaster/openwrt/target/linux'
make[4]: Entering directory '/Ledemaster/openwrt/target/linux/x86'

**Comment by lmxslpc** [comment]
让人算命么

**Comment by authon** [comment]
> 让人算命么

还需要i什么吗，就是v2dat编译失败

**Comment by Jejz168** [comment]
删掉这个v2dat，直接用mosdns中的v2dat

**Comment by authon** [comment]
> 删掉这个v2dat，直接用mosdns中的v2dat

没有选择编译mosdns

**Comment by Jejz168** [comment]
> > 删掉这个v2dat，直接用mosdns中的v2dat
> 
> 
> 
> 没有选择编译mosdns

CGO_ENABLED=0改为CGO_ENABLED=1

**Comment by authon** [comment]
> CGO_ENABLED=0

请问在哪设置

**Comment by authon** [comment]
> > > 删掉这个v2dat，直接用mosdns中的v2dat
> > 
> > 
> > 没有选择编译mosdns
> 
> CGO_ENABLED=0改为CGO_ENABLED=1

请问在哪设置

**Comment by xuexijiaoben** [comment]
sed -i 's/CGO_ENABLED=0/CGO_ENABLED=1/g' feeds/packages/net/mosdns/Makefile

你试试

**Comment by authon** [comment]
> sed -i 's/CGO_ENABLED=0/CGO_ENABLED=1/g' feeds/packages/net/mosdns/Makefile
> 
> 你试试

出现这个

**Comment by lxg2001** [comment]
> > sed -i 's/CGO_ENABLED=0/CGO_ENABLED=1/g' feeds/packages/net/mosdns/Makefile
> > 
> > 你试试
> 
> 出现这个
> sed: can't read feeds/packages/net/mosdns/Makefile: No such file or directory

sed -i 's/CGO_ENABLED=0/CGO_ENABLED=1/g' /Ledemaster/openwrt/feeds/packages/net/mosdns/Makefile

**Comment by mygithub1981** [comment]
我也一样情况，报错都一模一样，我是选了mosdns的。

**Comment by woni928** [comment]
已经解决
sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

**Comment by windybird** [comment]
> 已经解决 sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile

有这个？我都没找到
