### ISSUE TITLE
feeds install的时候有warning

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#11923]
### 详细叙述

这几个是什么呀？最近这一两天才出来的，强迫症，怎么resolve?

builder@Build-Server:/home/builder/lede_x86$ ./scripts/feeds install -a
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-mem2mem', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed helloworld.
Installing all packages from feed passwall.
Installing all packages from feed luci_passwall.
Installing all packages from feed openclash.
Installing all packages from feed istore.
Installing all packages from feed opentopd.
builder@Build-Server:/home/builder/lede_x86$

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

builder@Build-Server:/home/builder/lede_x86$ ./scripts/feeds install -a
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-mem2mem', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-video-dma', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed helloworld.
Installing all packages from feed passwall.
Installing all packages from feed luci_passwall.
Installing all packages from feed openclash.
Installing all packages from feed istore.
Installing all packages from feed opentopd.
builder@Build-Server:/home/builder/lede_x86$

**Comment by WYC-2020** [comment]
什么玩意 搜索l仓库package/kernel/linux下所有模块 就没那个模块 依赖 你说的这个什么kmod-video-dma，不知道自己有到哪里搞了什么模块 怕不是组合的吧

**Comment by GreatMichaelLee** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/20067401/427c7d38-63de-4a89-81f7-e07fcfeee10c)
![image](https://github.com/coolsnowwolf/lede/assets/20067401/55bc76fb-2594-409d-b1c8-da3961092da8)

menuconfig里找的这几个不知道是啥

**Comment by kxdn3** [comment]
云编译，同有这个错误

**Comment by WYC-2020** [comment]
没遇到你们这些杂七杂八的问题 自己排查

**Comment by Lujiang0111** [comment]
强迫症+1
看了一下是 92238a38e65f12bf4a0afd3da0c14976b8c3919a 导致的，切换回 5945bf489fa831f6f990832c27739ad2598a2b34 即可。

**Comment by WYC-2020** [comment]
> 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。

我感觉不像，我更新了这个提交 也没你们那个问题 哈哈
![image](https://github.com/coolsnowwolf/lede/assets/34025388/b1a02bf2-bfe5-4db0-af07-dcea8fe79e0d)
这个我memconfig 都搜不到这玩意，不知道你们如何玩的哈哈

**Comment by WYC-2020** [comment]
我的就是这样 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/cee36042-96f5-4923-b3af-c57b6f39e996)
不知道你们这玩意是怎么来的

**Comment by WYC-2020** [comment]
> 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。

看了下确实是这个 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/e4e70d87-b23a-4099-bdd6-3bd49ab5a10d)
但是我这边 有合并这个 没报这个 哈哈 见鬼

**Comment by GreatMichaelLee** [comment]
> > 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。
> 
> 看了下确实是这个 ![image](https://private-user-images.githubusercontent.com/34025388/308508102-e4e70d87-b23a-4099-bdd6-3bd49ab5a10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTU1MDMsIm5iZiI6MTcwOTExNTIwMywicGF0aCI6Ii8zNDAyNTM4OC8zMDg1MDgxMDItZTRlNzBkODctYjIzYS00MDk5LWJkZDYtM2JkNDlhYjVhMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNWI0ZDJkNDM2MDYzNzMxMDI2NzA5ZWM1ZjI1M2E2YzFkN2U2ZDhlODljZDM3OTc2ZTZlZDUzNzhhNTI5NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KKDGg_BK0U6iD6AkOnzUGX2i_mIUqmOUErHRZp2-CKI) 但是我这边 有合并这个 没报这个 哈哈 见鬼

你 rm -rf ./tmp && make clean试试

**Comment by WYC-2020** [comment]
靠 删除tmp 重新install 就能复现了哈哈 这是缺少这两个模块，等会看下如何休下

**Comment by fynhnt** [comment]
> rm -rf ./tmp && make clean

请问老大怎么切换，命令是什么，小白求支援。

**Comment by fynhnt** [comment]
> 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。

请问老大怎么切换，命令是什么，小白求支援。

**Comment by swxk521** [comment]
> > 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。
> 
> 请问老大怎么切换，命令是什么，小白求支援。

lede/package/kernel/linux/modules/video.mk
这个文件结尾加上下面代码
`define KernelPackage/video-mem2mem
  SUBMENU:=$(VIDEO_MENU)
  TITLE:=Memory 2 Memory device support
  HIDDEN:=1
  DEPENDS:=+kmod-video-videobuf2
  KCONFIG:= \
    CONFIG_V4L_MEM2MEM_DRIVERS=y \
    CONFIG_V4L2_MEM2MEM_DEV
  FILES:= $(LINUX_DIR)/drivers/media/$(V4L2_DIR)/v4l2-mem2mem.ko
  AUTOLOAD:=$(call AutoLoad,66,v4l2-mem2mem)
  $(call AddDepends/video)
endef

define KernelPackage/video-mem2mem/description
  Memory 2 memory device support
endef

$(eval $(call KernelPackage,video-mem2mem))

define KernelPackage/video-dma
  SUBMENU:=$(VIDEO_MENU)
  TITLE:=Video DMA support
  HIDDEN:=1
  DEPENDS:=+kmod-video-videobuf2
  KCONFIG:= \
	CONFIG_VIDEOBUF2_DMA_CONTIG \
	CONFIG_VIDEOBUF2_DMA_SG
  FILES:= $(LINUX_DIR)/drivers/media/common/videobuf2/videobuf2-dma-*.ko
  AUTOLOAD:=$(call AutoLoad,66,videobuf2-dma-contig videobuf2-dma-sg)
  $(call AddDepends/video)
endef

define KernelPackage/video-dma/description
  Video DMA support
endef

$(eval $(call KernelPackage,video-dma))`

**Comment by Lujiang0111** [comment]
> > 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。
> 
> 请问老大怎么切换，命令是什么，小白求支援。

```shell
git clone https://github.com/coolsnowwolf/lede
cd lede
git checkout 5945bf489fa831f6f990832c27739ad2598a2b34
```

**Comment by fynhnt** [comment]
> > > 强迫症+1 看了一下是 [92238a3](https://github.com/coolsnowwolf/lede/commit/92238a38e65f12bf4a0afd3da0c14976b8c3919a) 导致的，切换回 [5945bf4](https://github.com/coolsnowwolf/lede/commit/5945bf489fa831f6f990832c27739ad2598a2b34) 即可。
> > 
> > 
> > 请问老大怎么切换，命令是什么，小白求支援。
> 
> ```shell
> git clone https://github.com/coolsnowwolf/lede
> cd lede
> git checkout 5945bf489fa831f6f990832c27739ad2598a2b34
> ```

感谢大佬，马上去试试。
