### ISSUE TITLE
克隆LEDE源码出错

### ISSUE THREAD

**Issue by jonwhoo** [coolsnowwolf/lede#11936]
### 详细叙述

克隆LEDE源码出错，是怎么回事，以前没碰到过：
Cloning into 'lede'...
remote: Enumerating objects: 135354, done.
remote: Counting objects: 100% (30479/30479), done.
remote: Compressing objects: 100% (6434/6434), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOFs:   9% (12182/135354), 58.08 MiB | 12.91 MiB/s
fatal: index-pack failed

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

VM虚拟机，20.04系统

### 详细日志

还没到该阶段

**Comment by Michaol** [comment]
换梯

**Comment by caixin1218** [comment]
明显的网络故障，先多拉几次，不行换梯子节点。

**Comment by jonwhoo** [comment]
谢谢，解决了，换可靠节点，全局，OK！
