### ISSUE TITLE
最新代码运行异常

### ISSUE THREAD

**Issue by mirthlesslk** [coolsnowwolf/lede#11947]
### 详细叙述

今天更新之后编译出来的固件运行异常，5.15，6.1都是，下附5.15的日志

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

6086

### 详细日志

[日志.txt](https://github.com/coolsnowwolf/lede/files/14473121/default.txt)
[日志2.txt](https://github.com/coolsnowwolf/lede/files/14473122/2.txt)

**Comment by qqsir-dev** [comment]
刚编译出来的x86固件一直在重启，也抓不到日志。。。

**Comment by DL53** [comment]
编译出的ax6s固件直接无法更新。。。

**Comment by swxk521** [comment]
action 中途错误

**Comment by gssiwmd** [comment]
R5S也是一样

**Comment by Link-ee** [comment]
我PVE KVM OP拨号就卡死重启，之前6.6就是这样，现在6.1.80也开始了

**Comment by aiamadeus** [comment]
刚 push 了一个修复，你们再试试。。

**Comment by WYC-2020** [comment]
稳如老狗
