### ISSUE TITLE
docker网络页面错误

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#11960]
### 详细叙述

/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute cbi dispatcher target for entry '/admin/docker/networks'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/dockerman/networks.lua:44: attempt to index field 'Config' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

无

**Comment by tignioj** [comment]
同样的错误。

**Comment by wuyuqq** [comment]
同样的错误。+1

**Comment by firkerword** [comment]
我还以为就我有这个毛病

**Comment by dph5199278** [comment]
找上游，上游已解决

**Comment by caixin1218** [comment]
> 找上游，上游已解决

刚刚测试过，还没有解决。

**Comment by dph5199278** [comment]
> > 找上游，上游已解决
> 
> 刚刚测试过，还没有解决。

上游的这个[提交](https://github.com/lisaac/luci-app-dockerman/commit/7292955a1b415bb60fa2e403bb3a437b4b7f7846)，我试过是可以的

**Comment by caixin1218** [comment]
外部分支，只能手工替换？

**Comment by caixin1218** [comment]
外部分支，只能手工替换？

**Comment by HHJLKK** [comment]
> 外部分支，只能手工替换？ 两个文件都替换了，还不行啊。

自己也是手工替换的，然后重新编译就可以了。
![image](https://github.com/coolsnowwolf/lede/assets/32214003/231c933e-ad5e-4e2f-957f-6e730cec1353)

**Comment by oyksoft** [comment]
补丁在我这试了，没用，还是报错。虽然已经合并到了 https://github.com/coolsnowwolf/luci/ 。不知道其它人情况怎么样

**Comment by shu0802** [comment]
docker容器启动不了，如何解决。提示如下：
![image](https://github.com/coolsnowwolf/lede/assets/43750373/7cbea988-0721-4aea-a58f-caff191e7cf8)

**Comment by caixin1218** [comment]
> > 外部分支，只能手工替换？ 两个文件都替换了，还不行啊。
> 
> 自己也是手工替换的，然后重新编译就可以了。 ![image](https://private-user-images.githubusercontent.com/32214003/311434606-231c933e-ad5e-4e2f-957f-6e730cec1353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjUwODIsIm5iZiI6MTcxMDA2NDc4MiwicGF0aCI6Ii8zMjIxNDAwMy8zMTE0MzQ2MDYtMjMxYzkzM2UtYWQ1ZS00ZTJmLTk1N2YtNmU3MzBjZWMxMzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzM3MTIxMmI2MGY1MGRhNTI3MDFiNDA5NmI5ODFmNzY5ZjNjOTJhOTUyNGUyMTA1ZGE3NTc1Nzg2NmU5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8F34qSBL2T9izioy2UzgZzGVA7P0LeQLNKy5K7fPaI)

docker未启动时网络页面可以打开，但docker启动后网络界面就打不开了。

**Comment by HHJLKK** [comment]
> > > 外部分支，只能手工替换？ 两个文件都替换了，还不行啊。
> 
> > 
> 
> > 自己也是手工替换的，然后重新编译就可以了。 ![image](https://private-user-images.githubusercontent.com/32214003/311434606-231c933e-ad5e-4e2f-957f-6e730cec1353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjUwODIsIm5iZiI6MTcxMDA2NDc4MiwicGF0aCI6Ii8zMjIxNDAwMy8zMTE0MzQ2MDYtMjMxYzkzM2UtYWQ1ZS00ZTJmLTk1N2YtNmU3MzBjZWMxMzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzM3MTIxMmI2MGY1MGRhNTI3MDFiNDA5NmI5ODFmNzY5ZjNjOTJhOTUyNGUyMTA1ZGE3NTc1Nzg2NmU5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8F34qSBL2T9izioy2UzgZzGVA7P0LeQLNKy5K7fPaI)
> 
> 
> 
> docker未启动时网络页面可以打开，但docker启动后网络界面就打不开了。

修这个bug的新代码已合并，代码重新pull 重新编译。
就没这个问题了

**Comment by dph5199278** [comment]
> > > 外部分支，只能手工替换？ 两个文件都替换了，还不行啊。
> > 
> > 
> > 自己也是手工替换的，然后重新编译就可以了。 ![image](https://private-user-images.githubusercontent.com/32214003/311434606-231c933e-ad5e-4e2f-957f-6e730cec1353.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjUwODIsIm5iZiI6MTcxMDA2NDc4MiwicGF0aCI6Ii8zMjIxNDAwMy8zMTE0MzQ2MDYtMjMxYzkzM2UtYWQ1ZS00ZTJmLTk1N2YtNmU3MzBjZWMxMzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA5NTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzM3MTIxMmI2MGY1MGRhNTI3MDFiNDA5NmI5ODFmNzY5ZjNjOTJhOTUyNGUyMTA1ZGE3NTc1Nzg2NmU5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8F34qSBL2T9izioy2UzgZzGVA7P0LeQLNKy5K7fPaI)
> 
> docker未启动时网络页面可以打开，但docker启动后网络界面就打不开了。

![image](https://github.com/coolsnowwolf/lede/assets/5254255/cc658ab5-861c-4b05-afa5-1591dea257d0)
![image](https://github.com/coolsnowwolf/lede/assets/5254255/dfb98ba5-b016-43b7-b372-1efcdf7b5e95)
![image](https://github.com/coolsnowwolf/lede/assets/5254255/654841d3-358a-4f95-85d2-4e046f179e42)

我这边正常，报错信息还是一样的？
不行就全清了，重新再编译一次
```
# 目录全清了
make dirclean
```

**Comment by wuyuqq** [comment]
今天编译 docker 网络页面已经可以正常打开显示了。
