### ISSUE TITLE
最新编译出错

### ISSUE THREAD

**Issue by qq1316237299** [coolsnowwolf/lede#11973]
### 详细叙述

最新编译出错![QQ截图20240311151625](https://github.com/coolsnowwolf/lede/assets/42686656/f03057c8-04cc-4c40-8f3e-68d3c896b302)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/acl/v2geo/v2geo.pb.go:10:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/acl/v2geo/v2geo.pb.go:11:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/acl/compile.go:11:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/acl/matchers.go:7:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/internal/utils/qr.go:6:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/obfs/salamander.go:9:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/dns_https.go:9:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../extras/outbounds/dns_standard.go:8:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/server.go:17:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/server.go:18:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/client.go:14:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/client.go:15:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/client.go:16:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
../../app/cmd/root.go:12:2: github.com/apernet/quic-go@v0.41.1-0.20240301003057-e18162de481d: Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout

Makefile:59: recipe for target '/home/qq1316237299/lede/build_dir/target-x86_64_musl/hysteria-app-v2.3.0/.built' failed
make[3]: *** [/home/qq1316237299/lede/build_dir/target-x86_64_musl/hysteria-app-v2.3.0/.built] Error 1
make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/hysteria'
time: package/feeds/passwall_packages/hysteria/compile#0.29#0.21#60.35
    ERROR: package/feeds/passwall_packages/hysteria failed to build.
package/Makefile:114: recipe for target 'package/feeds/passwall_packages/hysteria/compile' failed
make[2]: *** [package/feeds/passwall_packages/hysteria/compile] Error 1
make[2]: Leaving directory '/home/qq1316237299/lede'
package/Makefile:110: recipe for target '/home/qq1316237299/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/qq1316237299/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/qq1316237299/lede'
/home/qq1316237299/lede/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2
![QQ截图20240311151625](https://github.com/coolsnowwolf/lede/assets/42686656/8928af3f-0caa-42cf-8852-bb2f6d65b4d4)

**Comment by techblack** [comment]
网络环境不够科学

**Comment by qq1316237299** [comment]
> 网络环境不够科学

![QQ截图20240311152325](https://github.com/coolsnowwolf/lede/assets/42686656/f8d047f0-4cbd-46e3-9c2c-3f2fa0fc1f3e)

**Comment by yuhongwei380** [comment]
机器挂代理去跑；

**Comment by qq1316237299** [comment]
> 机器挂代理去跑；

挂了还是没用啊兄弟

**Comment by qq1316237299** [comment]
> 1:443: i/o timeout
> ../../extras/outbounds/acl/v2geo/v2geo.pb.go:11:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../extras/outbounds/acl/compile.go:11:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../extras/outbounds/acl/matchers.go:7:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../app/internal/utils/qr.go:6:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../extras/obfs/salamander.go:9:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../extras/outbounds/dns_https.go:9:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../extras/outbounds/dns_standard.go:8:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../app/cmd/server.go:17:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../app/cmd/server.go:18:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod": dial tcp 142.250.188.241:443: i/o timeout
> ../../app/cmd/client.go:14:2: github.com/apernet/[quic-go@v0.41.1-0.20240301003057-e18162de481d](mailto:quic-go@v0.41.1-0.20240301003057-e18162de481d): Get "[https://proxy.go](https://proxy.golang.org/github.com/apernet/quic-go/@v/v0.41.1-0.20240301003057-e18162de481d.mod)

![QQ截图20240311175637](https://github.com/coolsnowwolf/lede/assets/42686656/774874a9-8987-4d28-b265-d04e86142fb9)
现在是这个错误

**Comment by yuhongwei380** [comment]
重新git clone整个项目，重新编译试试看吧，我看你这图里都报缺文件了
![image](https://github.com/coolsnowwolf/lede/assets/44333391/a52e863b-841c-48c8-884f-aea45b578b3b)

**Comment by qq1316237299** [comment]
> 重新git clone整个项目，重新编译试试看吧，我看你这图里都报缺文件了 ![image](https://private-user-images.githubusercontent.com/44333391/311662847-a52e863b-841c-48c8-884f-aea45b578b3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTE4NTksIm5iZiI6MTcxMDE1MTU1OSwicGF0aCI6Ii80NDMzMzM5MS8zMTE2NjI4NDctYTUyZTg2M2ItODQxYy00OGM4LTg4NGYtYWVhNDViNTc4YjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NmFhOWUyOWY5ZmZkMzM2MGY2YmI3MTFjYTM2ZGJjZGQ4MzNkOWIzZTA4MzU3MWNhZmQzZWNhNjMzZDhhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Q7AvcitRiYtPWkcu7zE8iyBVmb_buNKYKXQWSStNDI)

哦哦 谢谢

**Comment by lxg2001** [comment]
echo "export GO111MODULE=on" >> ~/.profile
echo "export GOPROXY=https://goproxy.cn" >> ~/.profile
source ~/.profile

**Comment by lxg2001** [comment]
`echo "export GO111MODULE=on" >> ~/.profile`
`echo "export GOPROXY=https://goproxy.cn" >> ~/.profile`
`source ~/.profile`

**Comment by qq1316237299** [comment]
> [lxg2001](/lxg2001)

哇，大佬啊 ，可以编译了
