### ISSUE TITLE
最新内核6.6编译出错。

### ISSUE THREAD

**Issue by cyzzc-1288** [coolsnowwolf/lede#11978]
### 详细叙述

最新内核6.6编译出错。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

![image](https://github.com/coolsnowwolf/lede/assets/82692177/103a768c-ae8b-4b34-86ee-3764dc738bf3)
请问各位大佬要怎么处理？

**Comment by kxdn3** [comment]
一样

**Comment by caixin1218** [comment]
我也是一样的+1

**Comment by Beginner-Go** [comment]
我看看是怎么个事
