### ISSUE TITLE
ax6s

### ISSUE THREAD

**Issue by sss132919** [coolsnowwolf/lede#11976]
### 详细叙述

ax6s的配置文件编译完成后，刷机后作为主路由的情况下，接在lan口的设备之间无法互访，即lan1的PC无法访问lan2的NAS设备，怀疑是内网交换芯片的功能没有配置。
请问这个问题是否会解决，或者请大佬告知该如何解决这个问题。
倒是没有搜到类似的问题

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

redmi-ax6s

### 详细日志

额，编译倒是没啥问题。倒是添加了mtk官方的switch软件包无法通过编译。所以选择了源码自带的kmod-swconfig,然后再软件源里下载了swconfig。

**Comment by FreshKai** [comment]
我觉得你这个描述没人能解决你的问题，因为有效信息量不足。

1. 无法互访指的是同一网段下的网络不通还是对应的服务无法访问？
2. 对应的终端通过有线还是无线接入路由器没有提及。
3. 日志没有的话不同终端互ping起码来个无法互访的有效信息。

> 在没有错误日志的情况下诊断任何问题无异于闭眼开车
