### ISSUE TITLE
红米AX5 JDC编译成功后生成的固件无法刷入机器

### ISSUE THREAD

**Issue by FreshKai** [coolsnowwolf/lede#11971]
### 详细叙述

编译成功得到红米AX5 JDC相应固件使用以下方法均无法完美刷入机器。

1. 通过UBoot更新factory.bin固件，自动重启后还是原来的固件，新的固件并没有刷入机器。
2. 通过网页WebUI备份/升级刷写新的sysupgrade.bin固件提示不支持所上传的映像文件格式，请选择适合当前平台的通用映像文件。
3. 使用命令将sysupgrade.bin固件上传到路由器后强制更新重启可以进入新的固件，也可以进行设置从而上网，但是重启就会无法开机。
强制更新的命令为`sysupgrade -n -F openwrt-qualcommax-ipq60xx-redmi_ax5-jdcloud-squashfs-sysupgrade.bin`
![强行升级OpenWRT](https://github.com/coolsnowwolf/lede/assets/81074258/cfcbac02-c6cc-42ac-90e3-4918b9a0087c)

通过第3种方式强制更新会提示设备不匹配，本机支持设备为**redmi,ax5-jdcloud**，固件对应信息为**ap-cp03-c1**

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

红米AX5 JDC（Xiaomi Redmi Router AX5_JDC IPQ6018/AP-CP03-C1）

### 详细日志

编译是成功的，附使用`make V=s -j1`命令编译的完整日志
[log.txt](https://github.com/coolsnowwolf/lede/files/14553261/log.txt)

**Comment by aiamadeus** [comment]
IPQ6 的开源并没有到可以日用的地步
