### ISSUE TITLE
ERROR: package/feeds/packages/v2dat failed to build

### ISSUE THREAD

**Issue by woni928** [coolsnowwolf/lede#11984]
### 详细叙述

2024-0313 n1云编译报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

n1-openwort

### 详细日志

![v2dat](https://github.com/coolsnowwolf/lede/assets/28220733/5b01f551-e9e8-4554-b193-1b085639ab47)

**Comment by lxg2001** [comment]
packages/utils/v2dat/Makefile删掉`GO_PKG_TARGET_VARS:=$(filter-out CGO_ENABLED=%,$(GO_PKG_TARGET_VARS)) CGO_ENABLED=0`
这一行，但你是云编译，要等人提交了

**Comment by lxg2001** [comment]
packages/utils/v2dat/Makefile删掉`GO_PKG_TARGET_VARS:=$(filter-out CGO_ENABLED=%,$(GO_PKG_TARGET_VARS)) CGO_ENABLED=0`这一行，但你是云编译，要等人提交了

**Comment by lxg2001** [comment]
feeds/packages/utils/v2dat/Makefile删掉`GO_PKG_TARGET_VARS:=$(filter-out CGO_ENABLED=%,$(GO_PKG_TARGET_VARS)) CGO_ENABLED=0`这一行，但你是云编译，要等人提交了

**Comment by woni928** [comment]
已经自己解决
sed -i 's#GO_PKG_TARGET_VARS.*# #g' feeds/packages/utils/v2dat/Makefile
