### ISSUE TITLE
小米路由器3和3g编译错误

### ISSUE THREAD

**Issue by noviachen** [coolsnowwolf/lede#11996]
### 详细叙述

之前的版本还是正常的，从前天开始编译失败。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Xiaomi Mi Router R3, Xiaomi Mi Router 3G

### 详细日志

SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/packages/.pkgdir/kernel/. /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/root-ramips/'
touch /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp/.kernel_installed
NOTICE: module '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.270/crypto/aead.ko' is built-in.
ERROR: module '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.270/crypto/geniv.ko' is missing.
make[3]: *** [modules/crypto.mk:51: /workdir/openwrt/bin/targets/ramips/mt7621/packages/kmod-crypto-aead_5.4.270-1_mipsel_24kc.ipk] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#2.97#0.22#3.18
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by wozualong** [comment]
MT7621设备编译一样都出现这个报错
