### ISSUE TITLE
Realtek R8168网卡千兆协商速率led灯只亮一个

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/lede#12008]
### 详细叙述

Realtek R8168网卡，在百兆速率协商全双工的状态下，数据灯绿色闪烁，状态灯黄色常亮，而在千兆协商速率全双工下，数据灯熄灭不亮，状态灯黄色常亮。功能是一切正常的
我看了lean的R8168网卡驱动，其中的[led patch](https://github.com/coolsnowwolf/lede/blob/4fb3ef83647ec4ea935d02a5a70003f88c27fe07/package/lean/r8168/patches/100-add-LED-configuration-from-OF.patch#L1-L42)实在不会改，求大佬修复一下

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86 CPU:N3160  网卡驱动：r8168 Gigabit Ethernet driver 8.052.01-NAPI loaded

### 详细日志

非编译问题

**Comment by coolsnowwolf** [comment]
这个是写在 dts 中的，默认行为问你 x86 的生产商了

**Comment by smallprogram** [comment]
> 这个是写在 dts 中的，默认行为问你 x86 的生产商了

好的
