### ISSUE TITLE
img.gz不解压上传升级失败

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#12004]
### 详细叙述

不保留配置情况下，img.gz固件以前不用解压可以直接上传升级，现在必须解压成img固件才能上传升级，不解压的话上传到一半就失败。保留配置就能上传

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

无

**Comment by WYC-2020** [comment]
这一直没这个问题

**Comment by binge8** [comment]
> 这一直没这个问题

多次测试，谷歌浏览器上传一半就找不到网页，用edge浏览器就没问题 ，是我哪里设置有问题吗

**Comment by smallprogram** [comment]
很有可能你的存储坏了，我之前遇到过，换个硬盘就好了

**Comment by binge8** [comment]
> 很有可能你的存储坏了，我之前遇到过，换个硬盘就好了

别闹，我说了换个浏览器就没问题，只是谷歌浏览器有问题

**Comment by WYC-2020** [comment]
那不清楚了 我谷歌试过没这个问题哈哈
