### ISSUE TITLE
Adbyby Plus+ 未运行

### ISSUE THREAD

**Issue by aiastia** [coolsnowwolf/lede#1200]
Adbyby Plus+ 未运行

树莓派 编译的  然后其他没发现什么问题 就这个 软件 启动不了

**Comment by zxlhhyccc** [comment]
你是最新版编译的么？你时间正常吗？

**Comment by aiastia** [comment]
是的 ，今天上午编译的，。时间同步过了。

**Comment by zxlhhyccc** [comment]
我编译的时间怎么同步不了呢？

**Comment by aiastia** [comment]
> 我编译的时间怎么同步不了呢？

请另外开一个 issues?
