### ISSUE TITLE
这个报错怎么解决？？

### ISSUE THREAD

**Issue by 392377870** [coolsnowwolf/lede#12009]
### 详细叙述

这个报错怎么解决？？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/openwrt-19810729/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/openwrt-19810729/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" /usr/bin/env bash ../../lang/golang//golang-build.sh cache_cleanup
touch /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.built
rm -rf /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd.installed /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd
mkdir -p /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/usr/bin/
install -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/bundles/binary-daemon/dockerd /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/usr/bin/
install -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/bundles/binary-daemon/docker-proxy /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/usr/bin/
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/opt/docker/
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/init.d
install -m0755 ./files/dockerd.init /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/init.d/dockerd
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/config
install -m0600 ./files/etc/config/dockerd /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/config/dockerd
# Must be after systcl 11-br-netfilter.conf from kmod-br-netfilter
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/sysctl.d
install -m0644 ./files/etc/sysctl.d/sysctl-br-netfilter-ip.conf /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/etc/sysctl.d/12-br-netfilter-ip.conf
touch /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd.installed
mkdir -p /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/openwrt-19810729/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.pkgdir/dockerd/. /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.dockerd_installed
removed '/home/openwrt-19810729/lede/bin/packages/x86_64/packages/dockerd_25.0.3-1_x86_64.ipk'
mkdir -p /home/openwrt-19810729/lede/bin/targets/x86/64/packages /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/CONTROL /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/pkginfo
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/usr/bin/
install -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/bundles/binary-daemon/dockerd /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/usr/bin/
install -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/bundles/binary-daemon/docker-proxy /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/usr/bin/
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/opt/docker/
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/init.d
install -m0755 ./files/dockerd.init /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/init.d/dockerd
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/config
install -m0600 ./files/etc/config/dockerd /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/config/dockerd
# Must be after systcl 11-br-netfilter.conf from kmod-br-netfilter
install -d -m0755 /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/sysctl.d
install -m0644 ./files/etc/sysctl.d/sysctl-br-netfilter-ip.conf /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/etc/sysctl.d/12-br-netfilter-ip.conf
find /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="x86_64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="x86_64-openwrt-linux-musl-nm" STRIP="x86_64-openwrt-linux-musl-strip --strip-all" STRIP_KMOD="/home/openwrt-19810729/lede/scripts/strip-kmod.sh" PATCHELF="/home/openwrt-19810729/lede/staging_dir/host/bin/patchelf" /home/openwrt-19810729/lede/scripts/rstrip.sh /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd
rstrip.sh: /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/usr/bin/docker-proxy: executable
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
rstrip.sh: /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/usr/bin/dockerd: executable
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
(cd /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_dockerd_conffiles" > conffiles;  echo "$V_Package_dockerd_postinst" > postinst-pkg; chmod 0755 postinst-pkg; echo "$V_Package_dockerd_prerm" > prerm-pkg; chmod 0755 prerm-pkg; )
install -d -m0755 /home/openwrt-19810729/lede/bin/packages/x86_64/packages
/home/openwrt-19810729/lede/staging_dir/host/bin/fakeroot /home/openwrt-19810729/lede/staging_dir/host/bin/bash /home/openwrt-19810729/lede/scripts/ipkg-build -m "" /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd /home/openwrt-19810729/lede/bin/packages/x86_64/packages
Packaged contents of /home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/ipkg-x86_64/dockerd into /home/openwrt-19810729/lede/bin/packages/x86_64/packages/dockerd_25.0.3-1_x86_64.ipk
echo "dockerd" >> /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/pkginfo/dockerd.default.install
rm -rf /home/openwrt-19810729/lede/tmp/stage-dockerd
mkdir -p /home/openwrt-19810729/lede/tmp/stage-dockerd/host /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/packages
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/openwrt-19810729/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/openwrt-19810729/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/docker/docker" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/docker/docker/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3" GO_BUILD_DIR="/home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.go_work/build" GO_BUILD_BIN_DIR="/home/openwrt-19810729/lede/build_dir/target-x86_64_musl/dockerd-25.0.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash ../../lang/golang//golang-build.sh install_src "/home/openwrt-19810729/lede/tmp/stage-dockerd"
find /home/openwrt-19810729/lede/tmp/stage-dockerd -name '*.la' | xargs -r rm -f; 
if [ -f /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/packages/dockerd.list ]; then /home/openwrt-19810729/lede/scripts/clean-package.sh "/home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/packages/dockerd.list" "/home/openwrt-19810729/lede/staging_dir/target-x86_64_musl"; fi
if [ -d /home/openwrt-19810729/lede/tmp/stage-dockerd ]; then (cd /home/openwrt-19810729/lede/tmp/stage-dockerd; find ./ > /home/openwrt-19810729/lede/tmp/stage-dockerd.files); 	SHELL= flock /home/openwrt-19810729/lede/tmp/.staging-dir.flock -c ' mv /home/openwrt-19810729/lede/tmp/stage-dockerd.files /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/packages/dockerd.list && cp -fpR /home/openwrt-19810729/lede/tmp/stage-dockerd/* /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/; '; fi
rm -rf /home/openwrt-19810729/lede/tmp/stage-dockerd
touch /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/stamp/.dockerd_installed
make[3]: Leaving directory '/home/openwrt-19810729/lede/feeds/packages/utils/dockerd'
time: package/feeds/packages/dockerd/compile#192.24#147.25#219.46
make[2]: Leaving directory '/home/openwrt-19810729/lede'
make[1]: *** [package/Makefile:110: /home/openwrt-19810729/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt-19810729/lede'
make: *** [/home/openwrt-19810729/lede/include/toplevel.mk:231：world] 错误 2

**Comment by WYC-2020** [comment]
算不出来
