### ISSUE TITLE
N1使用的ssr-plus的一些问题

### ISSUE THREAD

**Issue by Hitiko** [coolsnowwolf/lede#1202]
RT，我弄了个N1挂U盘当旁路由，但是发现ssr-plus无法启用节点
节点配置为chacha20/aes-256-ctr + auth_aes128_md5 + http_simple/tls1.2_ticket_auth

**Comment by hcym** [comment]
看不懂，我就用的v2，动态端口加个mkcp，你要做的是ssr或者ss混淆的话没必要n1，和普通路由区别不大，稳定性还是有点事

**Comment by Hitiko** [comment]
> 看不懂，我就用的v2，动态端口加个mkcp，你要做的是ssr或者ss混淆的话没必要n1，和普通路由区别不大，稳定性还是有点事

主要还是看中N1的性能，K2P那辣鸡MT7621实在跑不高速度
要是实在不行我就只能去用armbian了

**Comment by hcym** [comment]
你能搞定armbian当然用原生好啊，我是搞不动透明单口才用的op，继续努力脱离op
