### ISSUE TITLE
uboot-sunxi failed to build

### ISSUE THREAD

**Issue by Gabrielxzx** [coolsnowwolf/lede#12039]
### 详细叙述

编译sunxi处理器的板子，编译至uboot-sunxi时失败

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

orangepi_zero / orangepi_zero_plus

### 详细日志

[job-logs.txt](https://github.com/coolsnowwolf/lede/files/14812013/job-logs.txt)

**Comment by WYC-2020** [comment]
目测是这个提交导致的，暂时的话撤销掉这个提交吧 [5c5b7af071ac3a429a40162dce9b777bc37a7fc9](https://github.com/coolsnowwolf/lede/commit/5c5b7af071ac3a429a40162dce9b777bc37a7fc9) 应该不会影响你目前编译的这个型号

**Comment by WYC-2020** [comment]
如果不想撤回也可以这样
![image](https://github.com/coolsnowwolf/lede/assets/34025388/1a6bc6fb-3ba6-4572-94fa-1fab4e228e74)
 但是不确定功能是否正常，不怕死的可以试试，最好就是等l修复因为他添加的所以应该是知道如何修的

**Comment by Gabrielxzx** [comment]
> 如果不想撤回也可以这样 ![image](https://private-user-images.githubusercontent.com/34025388/318356413-1a6bc6fb-3ba6-4572-94fa-1fab4e228e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODEyNTgsIm5iZiI6MTcxMTk4MDk1OCwicGF0aCI6Ii8zNDAyNTM4OC8zMTgzNTY0MTMtMWE2YmM2ZmItM2JhNi00NTcyLTk0ZmEtMWZhYjRlMjI4ZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE0MTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZDFiMDUzYjAzYmYzOTdjNDgxOGVjZmQ0MDk2ZmMyNDg3NmE2MzM2Zjc1ODMyYTM0Nzk2NzM1ZDNmOTE4NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5O_p8ew0zOp5POuhqfJTpmSJylKnRYl7i0XgSAZfWnk) 但是不确定功能是否正常，不怕死的可以试试，最好就是等l修复因为他添加的所以应该是知道如何修的

好的，感谢。
知道有人关注这个就好。

**Comment by coolsnowwolf** [comment]
修复了
