### ISSUE TITLE
希望增加haproxy http mode 部分 luci的界面

### ISSUE THREAD

**Issue by shelliao** [coolsnowwolf/lede#1203]
由于需要使用haproxy进行负载均衡和节点存活判断，所以需要使用haproxy http 模式，希望开发haproxy http mode 下的luci
不能用tcp模式的原因是已经嵌套了CDN在前面，无法用tcp来检查cdn端的存活状态

**Comment by jiushibushuo** [comment]
> 由于需要使用haproxy进行负载均衡和节点存活判断，所以需要使用haproxy http 模式，希望开发haproxy http mode 下的luci
> 不能用tcp模式的原因是已经嵌套了CDN在前面，无法用tcp来检查cdn端的存活状态

我编了一个带Luci-haproxy的固件，方便给个联系方式吗？

**Comment by primroses2006** [comment]
大神,这个功能我也急需. 因为节点太多,他经常换,很累.
如果能做这个负载均衡就好用多了

**Comment by shelliao** [comment]
我在编译的时候，发现如果我用以下的haproxy  luci 无法覆盖原有的haproxy luci ，有无办法修改以下，让两个luci都能支持，并可以自定义选择那个进行编译？
https://github.com/honwen/luci-app-haproxy-tcp
