### ISSUE TITLE
红米 AX5 启用 PASSWALL2 后，编译出错

### ISSUE THREAD

**Issue by krysof** [coolsnowwolf/lede#12044]
### 详细叙述

sing-box ../init.d/sing-box 777 0 0' line 358
make[7]: *** [usr/Makefile:77: usr/initramfs_data.cpio] Error 255
make[7]: *** Deleting file 'usr/initramfs_data.cpio'
make[6]: *** [scripts/Makefile.build:500: usr] Error 2
make[5]: *** [Makefile:2010: .] Error 2
make[5]: Leaving directory '/home/kryso/Desktop/lede/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.1.83'
make[4]: *** [Makefile:44: /home/kryso/Desktop/lede/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.1.83/.image] Error 2
make[4]: Leaving directory '/home/kryso/Desktop/lede/target/linux/qualcommax'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/kryso/Desktop/lede/target/linux'
time: target/linux/install#22.99#20.62#21.58
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/kryso/Desktop/lede'
make[1]: *** [target/Makefile:24: /home/kryso/Desktop/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/kryso/Desktop/lede'
make: *** [/home/kryso/Desktop/lede/include/toplevel.mk:231: world] Error 2

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

红米 AX5

### 详细日志

sing-box ../init.d/sing-box 777 0 0' line 358
make[7]: *** [usr/Makefile:77: usr/initramfs_data.cpio] Error 255
make[7]: *** Deleting file 'usr/initramfs_data.cpio'
make[6]: *** [scripts/Makefile.build:500: usr] Error 2
make[5]: *** [Makefile:2010: .] Error 2
make[5]: Leaving directory '/home/kryso/Desktop/lede/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.1.83'
make[4]: *** [Makefile:44: /home/kryso/Desktop/lede/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.1.83/.image] Error 2
make[4]: Leaving directory '/home/kryso/Desktop/lede/target/linux/qualcommax'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/kryso/Desktop/lede/target/linux'
time: target/linux/install#22.99#20.62#21.58
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/kryso/Desktop/lede'
make[1]: *** [target/Makefile:24: /home/kryso/Desktop/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/kryso/Desktop/lede'
make: *** [/home/kryso/Desktop/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
算不出来 j1日志
