### ISSUE TITLE
6.6内核不支持 Intel Corporation Ethernet Controller X710网卡

### ISSUE THREAD

**Issue by cococle** [coolsnowwolf/lede#12043]
### 详细叙述

6.6内核不支持 Intel Corporation Ethernet Controller X710网卡

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

6.6内核不支持 Intel Corporation Ethernet Controller X710网卡

**Comment by qingtian110** [comment]
假的，6.6 内核支持 ie40

![image](https://github.com/coolsnowwolf/lede/assets/87856890/c1f7cfa3-3dc0-4421-af0e-96e6d539eabe)

**Comment by WYC-2020** [comment]
有这玩意还不支持 ?
![image](https://github.com/coolsnowwolf/lede/assets/34025388/bf866676-32ff-4096-b77c-bb93689c2765)

**Comment by qingtian110** [comment]
> 有这玩意还不支持 ?
> ![image](https://private-user-images.githubusercontent.com/34025388/319006779-bf866676-32ff-4096-b77c-bb93689c2765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTMzNDYsIm5iZiI6MTcxMjI5MzA0NiwicGF0aCI6Ii8zNDAyNTM4OC8zMTkwMDY3NzktYmY4NjY2NzYtMzJmZi00MDk2LWI3N2MtYmI5MzY4OWMyNzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA0NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTMwZTM5NmI5YjA2MDY4MzNjMGQ3NWJlOTZlZTlmYWE5YmVmY2M3ZGI3MWE2ZWVhZmVjZTA4MTIzYzU2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stqvcLb3EggfjkAi6EB_9nbawvrufMZUlU0hQwa6vu4)

它需要的是  kmod-ie40    不是vf
