### ISSUE TITLE
最近的源码dockerman貌似有重大bug

### ISSUE THREAD

**Issue by Pacio** [coolsnowwolf/lede#12054]
### 详细叙述

开启docker网速掉一半以上
关闭就恢复正常

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

G8505

### 详细日志

![image](https://github.com/coolsnowwolf/lede/assets/6836705/2d6c5510-f439-471b-9ecb-b81ac80ec1f9)

**Comment by joyplayer** [comment]
那个版本？25.0.3 经测试没有问题，一直稳定运行中，一个mysql、一个centos7 跑应用稳定如老狗~

**Comment by Pacio** [comment]
> 那个版本？25.0.3 经测试没有问题，一直稳定运行中，一个mysql、一个centos7 跑应用稳定如老狗~

都是最新源码编译的，插件都是最新版

**Comment by Pacio** [comment]
经过测试大概率是docker跑网心云的问题~估计被运营商针对了
