### ISSUE TITLE
daemon.err uhttpd[2345]: sh: write error: Broken pipe 好久了的老问题了

### ISSUE THREAD

**Issue by Pacio** [coolsnowwolf/lede#12053]
### 详细叙述

![image](https://github.com/coolsnowwolf/lede/assets/6836705/942663b0-1555-4484-8e4c-d350fc3b76f0)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

G8505

### 详细日志

如图

**Comment by Hyyyy11** [comment]
所以这是啥问题？我也发现日志里面有一些这样的报错

**Comment by Travel2Here** [comment]
同，时不时出现，想弄清楚
