### ISSUE TITLE
请问如何让系统日志不记录sing-box的信息

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#12060]
### 详细叙述

我没有找到设置系统日志文件或者有什么方法修改，因为安装了passwall不用sing-box，在系统日志里面总是出现以下信息，sing-box: /bin/sh: can't open '/etc/rc.common
': No such file or directory
有没有方法可以让系统日志里面不出现这段信息，因为它的出现会让系统日志下拉条出现异常

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rr

### 详细日志

sing-box: /bin/sh: can't open '/etc/rc.common
': No such file or directory

**Comment by WYC-2020** [comment]
算不出，日志不全，并且这个问题你该去passwall 那边
