### ISSUE TITLE
file "staging_dir/target-aarch64_generic_musl/image/rk3568_ddr_1560MHz_v1.18.bin"  not exist

### ISSUE THREAD

**Issue by ghmole** [coolsnowwolf/lede#12063]
### 详细叙述

the file not exist, but I found a file name  **rk3568_ddr_1560MHz_v1.21.bin** in the same directory, is it anything wrong?

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

h68k

### 详细日志

make -f ./scripts/Makefile.build obj=spl/fs
  ./tools/mkimage -f auto -A arm -T firmware -C none -O u-boot -a 0x00a00000 -e 0x00a00000 -p 0x0 -n "U-Boot 2023.07-rc6-OpenWrt-r6547+29-c897f32a4 for evb_rk3568 board" -E  -b arch/arm/dts/rk3568-opc-h68k.dtb  -d u-boot-nodtb.bin u-boot.img >/dev/null  && cat /dev/null
  ./tools/mkimage -f auto -A arm -T firmware -C none -O u-boot -a 0x00a00000 -e 0x00a00000 -p 0x0 -n "U-Boot 2023.07-rc6-OpenWrt-r6547+29-c897f32a4 for evb_rk3568 board" -E  -b arch/arm/dts/rk3568-opc-h68k.dtb  -d u-boot-nodtb.bin u-boot-dtb.img >/dev/null  && cat /dev/null
  ./tools/binman/binman   --toolpath ./tools  build -u -d u-boot.dtb -O . -m  -I . -I . -I ./board/rockchip/evb_rk3568 -I arch/arm/dts -a of-list="rk3568-opc-h68k"  -a atf-bl31-path=/home/diddle/works/lede/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.43.elf -a tee-os-path= -a opensbi-path= -a default-dt="rk3568-opc-h68k" -a scp-path= -a rockchip-tpl-path=/home/diddle/works/lede/staging_dir/target-aarch64_generic_musl/image/rk3568_ddr_1560MHz_v1.18.bin -a spl-bss-pad= -a tpl-bss-pad=1 -a spl-dtb=y -a tpl-dtb= -a pre-load-key-path=
binman: [Errno 2] No such file or directory: '/home/diddle/works/lede/staging_dir/target-aarch64_generic_musl/image/rk3568_ddr_1560MHz_v1.18.bin'
make[4]: *** [Makefile:1111: .binman_stamp] Error 1
make[4]: Leaving directory '/home/diddle/works/lede/build_dir/target-aarch64_generic_musl/u-boot-opc-h68k-rk3568/u-boot-2023.07'
make[3]: *** [Makefile:392: /home/diddle/works/lede/build_dir/target-aarch64_generic_musl/u-boot-opc-h68k-rk3568/u-boot-2023.07/.built] Error 2
make[3]: Leaving directory '/home/diddle/works/lede/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/opc-h68k-rk3568/compile#4.44#1.39#5.76
    ERROR: package/boot/uboot-rockchip failed to build (build variant: opc-h68k-rk3568).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/diddle/works/lede'
make[1]: *** [package/Makefile:110: /home/diddle/works/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/diddle/works/lede'
make: *** [/home/diddle/works/lede/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
git pull
