### ISSUE TITLE
loongarch64编译失败

### ISSUE THREAD

**Issue by cangkuai** [coolsnowwolf/lede#12071]
### 详细叙述

除了型号都完全默认的情况下编译失败

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

loongarch64

### 详细日志

![Snipaste_2024-04-13_16-16-36](https://github.com/coolsnowwolf/lede/assets/33569578/45273fcf-9099-4f6a-91e8-16862ce26356)

**Comment by coolsnowwolf** [comment]
已修复
