### ISSUE TITLE
全志和瑞芯微芯片  使用SD卡的设备烧录后无法启动

### ISSUE THREAD

**Issue by Gabrielxzx** [coolsnowwolf/lede#12070]
### 详细叙述

RT
使用SD卡的设备烧录后无法启动

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

orangepi_zero / orangepi_zero_plus / orangepi_zero3 / nanopi_neo2 / nanopi_r2c

### 详细日志

编译正常，但烧录进SD后无法启动。

串口看了orangepi_zero的启动日志如下：

> Connecting to COM3...
Connected.
U-Boot SPL 2024.01-OpenWrt-r0-373bf02 (Apr 11 2024 - 06:09:38 +0000)
DRAM: 512 MiB
Trying to boot from MMC1

然后就没了，确认SD卡正常，烧录回老固件可启动，也更换了SD卡测试
已经测试纯净编译，使用lede最新源码和默认配置，烧录后也无法启动。

另外附上启动正常的log
[正常启动日志.log](https://github.com/coolsnowwolf/lede/files/14965561/default.log)

LEDE 讨论区里有人提了类似问题
https://github.com/coolsnowwolf/lede/discussions/12065

**Comment by coolsnowwolf** [comment]
看起来像是 TF 的高速卡兼容问题，和 uboot 的

**Comment by Gabrielxzx** [comment]
> 看起来像是 TF 的高速卡兼容问题，和 uboot 的

可以看看nanopi_neo2的串口日志做参考，和orangepi_zero还不一致

> U-Boot SPL 2024.01-OpenWrt-r0-373bf02 (Apr 11 2024 - 06:09:38 +0000)
DRAM: 512 MiB
Trying to boot from MMC1
NOTICE:  BL31: v2.10.0	(release):OpenWrt v2.10-1 (sunxi-a64)
NOTICE:  BL31: Built : 06:09:38, Apr 11 2024
NOTICE:  BL31: Detected Allwinner H5 SoC (1718)
NOTICE:  BL31: Found U-Boot DTB at 0x20a40e8, model: FriendlyARM NanoPi NEO 2
NOTICE:  PMIC: Assuming H5 reference regulator design

**Comment by coolsnowwolf** [comment]
> 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行

你尝试 revert ATF 版本试试

**Comment by MilesPoupart** [comment]
> > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> 
> 你尝试 revert ATF 版本试试

好 俺把这几个commit revert了试试看
![image](https://github.com/coolsnowwolf/lede/assets/32707318/f58c2292-a1a4-4a72-b784-1358a83e9b2b)

**Comment by Gabrielxzx** [comment]
> > > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> > 
> > 
> > 你尝试 revert ATF 版本试试
> 
> 好 俺把这几个commit revert了试试看 ![image](https://private-user-images.githubusercontent.com/32707318/322477880-f58c2292-a1a4-4a72-b784-1358a83e9b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTAxOTEsIm5iZiI6MTcxMzE4OTg5MSwicGF0aCI6Ii8zMjcwNzMxOC8zMjI0Nzc4ODAtZjU4YzIyOTItYTFhNC00YTcyLWI3ODQtMTM1OGE4M2U5YjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjA4YzUwZjJmYTA4N2U2NWZmODUzYjM4MzI4ODU4YzMzNmY5NGE2YTIwZjExYjhlZjAzMzIxMWU4NGVmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2kB_bNAEOTLaNByVeElBwMbkZ4G0D5iLqigJj9MZMvI)

有效果记得来反馈下啊(づ ●─● )づ

**Comment by MilesPoupart** [comment]
> > > > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> > > 
> > > 
> > > 你尝试 revert ATF 版本试试
> > 
> > 
> > 好 俺把这几个commit revert了试试看 ![image](https://private-user-images.githubusercontent.com/32707318/322477880-f58c2292-a1a4-4a72-b784-1358a83e9b2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTAxOTEsIm5iZiI6MTcxMzE4OTg5MSwicGF0aCI6Ii8zMjcwNzMxOC8zMjI0Nzc4ODAtZjU4YzIyOTItYTFhNC00YTcyLWI3ODQtMTM1OGE4M2U5YjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE0MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjA4YzUwZjJmYTA4N2U2NWZmODUzYjM4MzI4ODU4YzMzNmY5NGE2YTIwZjExYjhlZjAzMzIxMWU4NGVmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2kB_bNAEOTLaNByVeElBwMbkZ4G0D5iLqigJj9MZMvI)
> 
> 有效果记得来反馈下啊(づ ●─● )づ

![image](https://github.com/coolsnowwolf/lede/assets/32707318/49e815ee-1072-4049-8a69-051fe45ad4b4)
revert这四个commit之后开出来了（r2s）

**Comment by sijyun** [comment]
我的 R2S 恢復,這一項就可以了.  

arm-trusted-firmware-rockchip-vendor: add RK3528/RK3588 support

**Comment by lysgwl** [comment]
编译了好几个版本的Rockchip芯片固件，r2s设备确实是无法启动。是因为升级了内核原因造成的吗？不太确认。

**Comment by lysgwl** [comment]
> 我的 R2S 恢復,這一項就可以了.
> 
> arm-trusted-firmware-rockchip-vendor: add RK3528/RK3588 support

增加了选项，也是不可以的。你是怎么操作的？

**Comment by sijyun** [comment]
> > 我的 R2S 恢復,這一項就可以了.
> > arm-trusted-firmware-rockchip-vendor: add RK3528/RK3588 support
> 
> 增加了选项，也是不可以的。你是怎么操作的？


前置準備好後, (我是用自己電腦編譯)

**動作**
git revert 3b681972500466d5ea56c1e5cea428954687c6f2
make menuconfig
make V=s ( -j=1 可選用)

**確認**
git status

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   package/boot/arm-trusted-firmware-rockchip-vendor/Makefile
        modified:   package/boot/arm-trusted-firmware-rockchip-vendor/atf-version.mk
        deleted:    package/boot/arm-trusted-firmware-rockchip-vendor/pack-firmware.sh
        modified:   package/boot/uboot-rockchip/Makefile

![r2s-k6 1 87-0420](https://github.com/coolsnowwolf/lede/assets/58562726/aa582a72-bce5-4fee-9ea7-17e76f0b1ac9)

**Comment by lysgwl** [comment]
> > > 我的 R2S 恢復,這一項就可以了.
> > > arm-trusted-firmware-rockchip-vendor: add RK3528/RK3588 support
> > 
> > 
> > 增加了选项，也是不可以的。你是怎么操作的？
> 
> 前置準備好後, (我是用自己電腦編譯)
> 
> **動作** git revert [3b68197](https://github.com/coolsnowwolf/lede/commit/3b681972500466d5ea56c1e5cea428954687c6f2) make menuconfig make V=s ( -j=1 可選用)
> 
> **確認** git status
> 
> Changes to be committed: (use "git restore --staged ..." to unstage) modified: package/boot/arm-trusted-firmware-rockchip-vendor/Makefile modified: package/boot/arm-trusted-firmware-rockchip-vendor/atf-version.mk deleted: package/boot/arm-trusted-firmware-rockchip-vendor/pack-firmware.sh modified: package/boot/uboot-rockchip/Makefile
> 
> ![r2s-k6 1 87-0420](https://private-user-images.githubusercontent.com/58562726/324045036-aa582a72-bce5-4fee-9ea7-17e76f0b1ac9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1Nzg5NjksIm5iZiI6MTcxMzU3ODY2OSwicGF0aCI6Ii81ODU2MjcyNi8zMjQwNDUwMzYtYWE1ODJhNzItYmNlNS00ZmVlLTllYTctMTdlNzZmMGIxYWM5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZDVmZDAyMTgwNDliZTkxZjZhODllNDdkYjU2MWMzNjdiZjUwZTliODU3MjM2Mjc1ZmM3OThhMGIzZDkxMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKmhDXmJ7rAhV16o45ND9zCO1BZcRSkq1QJvgnYGueI)

额，嗖嘎，你是回退了，是吧。我还以为增加一个rockchip选项。昨天我增加了一个选项，也是不行。

**Comment by Gabrielxzx** [comment]
SUNXI：
git revert e4172db --no-edit
RK：
git revert f788f35 --no-edit
git revert 3b68197 --no-edit

回退后可以启动

**Comment by Gabrielxzx** [comment]
> > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> 
> 你尝试 revert ATF 版本试试

SUNXI：
git revert e4172db --no-edit
RK：
git revert https://github.com/coolsnowwolf/lede/commit/f788f35b36162cf0a780aa5d98bafeb70341ba63 --no-edit
git revert https://github.com/coolsnowwolf/lede/commit/3b681972500466d5ea56c1e5cea428954687c6f2 --no-edit

revert后可以启动

**Comment by facerleo** [comment]
现在还是不行吗

**Comment by Gabrielxzx** [comment]
> > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> 
> 你尝试 revert ATF 版本试试

大佬帮忙看看吧，RK的能跑了，但SUNXI还是无法bringup

**Comment by Gabrielxzx** [comment]
> > > 也有类似的问题 4月4号源码编译的r2s固件可以启动 4月13号编译的不行
> > 
> > 
> > 你尝试 revert ATF 版本试试
> 
> 大佬帮忙看看吧，今天更新后，RK的能跑了，但SUNXI还是无法bringup

大佬帮忙瞅瞅吧，SUNXI的板子确实无法启动，已经测试确认删除261-sunxi-add-popstick-defconfig.patch就可以启动。
rm -rf package/boot/uboot-sunxi/patches/261-sunxi-add-popstick-defconfig.patch
