### ISSUE TITLE
lede 编译后后台默认页面是刷新固件页面

### ISSUE THREAD

**Issue by hansedong** [coolsnowwolf/lede#12078]
### 详细叙述

不太清楚哪里配置有问题，不论是 nginx 还是 uhttpd 都是如下，打开后台，页面如下：
![image](https://github.com/coolsnowwolf/lede/assets/3860021/1530b924-aa52-403d-989b-c64de65fd629)

正常来说，应该是进入管理后台，也就是右下角「管理权」按钮才会进入后台。想知道我哪里的配置可能有问题？

完整的 .config 需要的话我也可以贴出来，直接复制到这里，github 提示文本太大不允许提交。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

正常编译成功，没有错误日志

**Comment by aiamadeus** [comment]
你试试换个浏览器或者清除缓存？

**Comment by hansedong** [comment]
> 你试试换个浏览器或者清除缓存？

无痕模式也试过了，一样的
