### ISSUE TITLE
kmodloader: 1 module could not be probed  kmodloader: - jitterentropy_rng - 0

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#12099]
### 详细叙述

 jitterentropy_rng在Linux6.6内核下不能正确启动，之前的Linux6.1并未提示过相关错误，请问要如何解决

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Rockchip Nanopi

### 详细日志

kmodloader: 1 module could not be probed
kmodloader: - jitterentropy_rng - 0

jitterentropy: Initialization failed with host not compliant with requirements: 9

**Comment by coolsnowwolf** [comment]
修复了
