### ISSUE TITLE
如何自定义修改生成的固件名称呢？

### ISSUE THREAD

**Issue by lysgwl** [coolsnowwolf/lede#12093]
### 详细叙述

固件编译完成后，默认生成的固件名称都是统一的名称。如何在生成的固件镜像名称后面加入年月日或者其他信息呢？如何实现？？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

r2s

### 详细日志

无

**Comment by hzjnet** [comment]
配置文件里面启用2行：
CONFIG_VERSION_DIST="LEDExxxx"
CONFIG_VERSION_NUMBER="cools-M-d20231218"

**Comment by VIKINGYFY** [comment]
参考我的项目
https://github.com/VIKINGYFY/OpenWRT-CI

**Comment by lysgwl** [comment]
> 参考我的项目 https://github.com/VIKINGYFY/OpenWRT-CI

收到，好的，谢谢。

**Comment by fynhnt** [comment]
> 配置文件里面启用2行： CONFIG_VERSION_DIST="LEDExxxx" CONFIG_VERSION_NUMBER="cools-M-d20231218"

请问大神，本地编译这两行插入到哪个配置文件？
