### ISSUE TITLE
编译报错 bash: po2lmo: command not found

### ISSUE THREAD

**Issue by tossp** [coolsnowwolf/lede#121]
```
 make[3] -C package/lean/adbyby compile
patchelf: patchelf.cc:320: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::parse() [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym]: Assertion `shstrtabIndex < shdrs.size()' failed.
 make[3] -C package/lean/default-settings compile
bash: po2lmo: command not found
bash: po2lmo: command not found
bash: po2lmo: command not found
bash: po2lmo: command not found
make[3]: *** [/builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/default-settings/.prepared_123d41d7ab95c714e087c2ba4737a3ff_6664517399ebbbc92a37c5bb081b5c53] Error 127
make[2]: *** [package/lean/default-settings/compile] Error 2
make[1]: *** [/builds/zh/lede-k3/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [world] Error 1
``

**Comment by QuectelWB** [comment]
install -d -m0755 /home/test/lede/build_dir/target-mipsel_24kc_musl/default-settings-3/.pkgdir/default-settings/usr/lib/lua/luci/i18n
po2lmo ./po/zh-cn/default.po /home/test/lede/build_dir/target-mipsel_24kc_musl/default-settings-3/.pkgdir/default-settings/usr/lib/lua/luci/i18n/default.zh-cn.lmo
bash: po2lmo: command not found
Makefile:39: recipe for target '/home/test/lede/build_dir/target-mipsel_24kc_musl/default-settings-3/.pkgdir/default-settings.installed' failed
make[3]: *** [/home/test/lede/build_dir/target-mipsel_24kc_musl/default-settings-3/.pkgdir/default-settings.installed] Error 127
make[3]: Leaving directory '/home/test/lede/package/lean/default-settings'
time: package/lean/default-settings/compile#0.07#0.05#0.12
    ERROR: package/lean/default-settings failed to build.
package/Makefile:114: recipe for target 'package/lean/default-settings/compile' failed
make[2]: *** [package/lean/default-settings/compile] Error 1
make[2]: Leaving directory '/home/test/lede'
package/Makefile:110: recipe for target '/home/test/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/test/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/test/lede'
/home/test/lede/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2

Same with me.

 sudo apt-get install gettext -y
could not not resolve it.
