### ISSUE TITLE
编译docker失败，请问该如何解决？

### ISSUE THREAD

**Issue by rhmokey** [coolsnowwolf/lede#12109]
### 详细叙述

编译docker失败，去掉docker后编译没有问题，但是需要docker，请问该如何解决？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

Collected errors:
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/config/dockerd
        But that file is already provided by package  * dockerd
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/dockerd
        But that file is already provided by package  * dockerd
 * opkg_install_cmd: Cannot install package luci-app-docker.
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/config/dockerd
        But that file is already provided by package  * dockerd
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/dockerd
        But that file is already provided by package  * dockerd
 * opkg_install_cmd: Cannot install package luci-i18n-docker-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/luna/lede'
make[1]: *** [package/Makefile:111: /home/luna/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/luna/lede'
make: *** [/home/luna/lede/include/toplevel.mk:231: world] Error 2Collected errors:
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/config/dockerd
        But that file is already provided by package  * dockerd
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/dockerd
        But that file is already provided by package  * dockerd
 * opkg_install_cmd: Cannot install package luci-app-docker.
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/config/dockerd
        But that file is already provided by package  * dockerd
 * check_data_file_clashes: Package luci-app-docker wants to install file /home/luna/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/dockerd
        But that file is already provided by package  * dockerd
 * opkg_install_cmd: Cannot install package luci-i18n-docker-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/luna/lede'
make[1]: *** [package/Makefile:111: /home/luna/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/luna/lede'
make: *** [/home/luna/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
你这明显就是冲突吗 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/040f461a-bdc5-4a76-86b0-eb07c8ac2fb7)
是不是这两个都选了，只能选一个 别什么都一股脑 全选
