### ISSUE TITLE
ttyd一直不能用

### ISSUE THREAD

**Issue by kevinCSDN** [coolsnowwolf/lede#12103]
### 详细叙述

![2704c9a70ff32cebfc720adb4a94e2ff-topaz-enhance-6x-sharpen](https://github.com/coolsnowwolf/lede/assets/81788909/61bd7145-7165-4e41-ba15-7b0bbaeeae46)
好几个版本都提示这个问题

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

无

**Comment by xydche** [comment]
软件包管理器中安装bash

**Comment by WYC-2020** [comment]
怎么玩的哦 后台 的bash 都能没得，搞上 在看下 是否正常

**Comment by kevinCSDN** [comment]
解决了，感谢上面三位大佬，utilities-shells-bash选上就行了
