### ISSUE TITLE
fuse-devel 新增依赖报错

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#12119]
### 详细叙述

fuse-devel 新增依赖报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

# sudo apt install -y    fuse-devel
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package fuse-devel

**Comment by Junpenchen** [comment]
同样无法定位到软件包fuse-devel

**Comment by evenwangcn** [comment]
一样的问题

**Comment by smallprogram** [comment]
+1

**Comment by cloud-wyf** [comment]
+1
