### ISSUE TITLE
用haiibo脚本编译的lede怎么选择指定内核啊

### ISSUE THREAD

**Issue by CC13594759** [coolsnowwolf/lede#12118]
### 详细叙述

用haiibo脚本编译的lede怎么选择指定内核啊

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

mrkaio m68s plus

### 详细日志

用haiibo脚本编译的lede怎么选择指定内核啊

**Comment by kxdn3** [comment]
# 改为6.6内核
sed -i 's/KERNEL_PATCHVER:=.*/KERNEL_PATCHVER:=6.6/g' ./target/linux/x86/Makefile

**Comment by oppen123** [comment]
编辑你的config目录并加上
CONFIG_TESTING_KERNEL=y
CONFIG_LINUX_6_6=y
