### ISSUE TITLE
全新系统，总是报这个错误 ERROR: package/feeds/packages/v2dat failed to build.

### ISSUE THREAD

**Issue by lpflhh** [coolsnowwolf/lede#12117]
### 详细叙述

Building targets
runtime/cgo
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'

make[3]: *** [Makefile:48: /home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.built] Error 1
make[3]: Leaving directory '/home/abc/lede/feeds/packages/utils/v2dat'
time: package/feeds/packages/v2dat/compile#0.49#0.17#0.35
    ERROR: package/feeds/packages/v2dat failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/v2dat/compile] Error 1

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

newifi3

### 详细日志

make[3]: Leaving directory '/home/abc/lede/feeds/packages/net/mosdns'
time: package/feeds/packages/mosdns/compile#0.07#0.03#0.11
make[3]: Entering directory '/home/abc/lede/feeds/packages/utils/v2dat'
mkdir -p /home/abc/lede/dl
SHELL= flock /home/abc/lede/tmp/.v2dat-2022-12-15.tar.gz.flock -c '  	/home/abc/lede/scripts/download.pl "/home/abc/lede/dl" "v2dat-2022-12-15.tar.gz" "skip" "" "https://codeload.github.com/urlesistiana/v2dat/tar.gz/47b8ee51fb528e11e1a83453b7e767a18d20d1f7?"    '
rm -f /home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.built
touch /home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/abc/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/abc/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/urlesistiana/v2dat" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/urlesistiana/v2dat/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7" GO_BUILD_DIR="/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.go_work/build" GO_BUILD_BIN_DIR="/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.go_work/build/bin/linux_mipsle" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/abc/lede/staging_dir/target-mipsel_24kc_musl/usr/share/gocode/src" GOOS="linux" GOARCH="mipsle" GO386="" GOAMD64="" GOARM="" GOMIPS="softfloat" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7=v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/include -I/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include/fortify -I/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7=v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.go_work/build" GOCACHE="/home/abc/lede/tmp/go-build" GOMODCACHE="/home/abc/lede/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash ../../lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1714564814' -linkmode external -extldflags '-L/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/abc/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"     -installsuffix "softfloat"     
Finding targets

Building targets
runtime/cgo
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'

make[3]: *** [Makefile:48: /home/abc/lede/build_dir/target-mipsel_24kc_musl/v2dat-47b8ee51fb528e11e1a83453b7e767a18d20d1f7/.built] Error 1
make[3]: Leaving directory '/home/abc/lede/feeds/packages/utils/v2dat'
time: package/feeds/packages/v2dat/compile#0.49#0.17#0.35
    ERROR: package/feeds/packages/v2dat failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/v2dat/compile] Error 1
make[2]: Leaving directory '/home/abc/lede'
make[1]: *** [package/Makefile:110: /home/abc/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/abc/lede'
make: *** [/home/abc/lede/include/toplevel.mk:231：world] 错误 2

**Comment by WYC-2020** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/34025388/f126371d-d94b-4d82-82ea-5329500e6719)
这样改下试试 PKG_USE_MIPS16:=0
