### ISSUE TITLE
请教各位大佬，编译时如何加入tailscale

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#12111]
### 详细叙述

如题，在luci界面没有发现tailscale的选项，但是在package/net中有tailcale，请教在哪里勾选后可以编译入固件

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

如题

**Comment by guochan2019** [comment]
menuconfig - network - vpn - tailscale勾选编译，此插件没有luci界面，需要ssh后台配置，使用前先科普

**Comment by bi4tms** [comment]
> menuconfig - network - vpn - tailscale勾选编译，此插件没有luci界面，需要ssh后台配置，使用前先科普

感谢
