### ISSUE TITLE
编译armvirt固件报错

### ISSUE THREAD

**Issue by kingmoon3** [coolsnowwolf/lede#12132]
### 详细叙述

最近编译armvirt固件一直没成功过，4月份还没有问题的

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

晶晨s905d

### 详细日志

make[5]: Entering directory '/Ledemaster/openwrt/build_dir/target-aarch64_generic_musl/linux-armvirt_64/linux-5.15.158'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      net/ethernet/eth.o
net/ethernet/eth.c: In function 'eth_gro_receive':
net/ethernet/eth.c:443:42: error: 'eth' undeclared (first use in this function); did you mean 'eh'?
  443 |                 if (eth_check_local_mask(eth->h_dest, dev->dev_addr,
      |                                          ^~~
      |                                          eh
net/ethernet/eth.c:443:42: note: each undeclared identifier is reported only once for each function it appears in
net/ethernet/eth.c:443:55: error: 'dev' undeclared (first use in this function); did you mean 'cdev'?
  443 |                 if (eth_check_local_mask(eth->h_dest, dev->dev_addr,
      |                                                       ^~~
      |                                                       cdev
make[7]: *** [scripts/Makefile.build:289: net/ethernet/eth.o] Error 1
make[6]: *** [scripts/Makefile.build:552: net/ethernet] Error 2
make[5]: *** [Makefile:1907: net] Error 2
make[5]: Leaving directory '/Ledemaster/openwrt/build_dir/target-aarch64_generic_musl/linux-armvirt_64/linux-5.15.158'
make[4]: *** [Makefile:20: /Ledemaster/openwrt/build_dir/target-aarch64_generic_musl/linux-armvirt_64/linux-5.15.158/.modules] Error 2
make[4]: Leaving directory '/Ledemaster/openwrt/target/linux/armvirt'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/Ledemaster/openwrt/target/linux'
time: target/linux/compile#6.76#2.71#9.38
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/Ledemaster/openwrt'
make[1]: *** [target/Makefile:23: /Ledemaster/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/Ledemaster/openwrt'
make: *** [/Ledemaster/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by ywt114** [comment]
+1
5.15.158还没修好
