### ISSUE TITLE
qemu 9.0 build fail on GCC 13

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#12147]
### 详细叙述

rt, build failed with ERROR of `unknown option --disable-hax`

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0/ -name config.sub | xargs -r -n1 cp --remove-destination /home/builder/lede_x8
6/scripts/config.sub; AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -f
no-plt -fhonour-copts   -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0=qemu-9.0.0 -Wformat -
Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_6
4-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-m
usl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-
objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CFLAGS="-Os -pipe -fno-caller-saves -fno-
plt -fhonour-copts   -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0=qemu-9.0.0 -Wformat -Wer
ror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts   -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0=qemu-9.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/usr/include -I/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/include/fortify -I/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/include   " LDFLAGS="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/lib   -znow -zrelro -Wl,--as-needed "   ./configure --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --cross-prefix=x86_64-openwrt-linux-musl- --host-cc="gcc" --disable-fortify-source --disable-stack-protector --extra-cflags="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts   -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0=qemu-9.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " --extra-cxxflags="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts   -fmacro-prefix-map=/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0=qemu-9.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " --extra-ldflags="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-13.2.0_musl/lib   -znow -zrelro "  --enable-vhost-crypto --enable-vhost-kernel --enable-vhost-net --enable-vhost-user --enable-vhost-user-blk-server --enable-vhost-vdpa  --disable-bochs --disable-cloop --disable-dmg --disable-qcow1 --disable-vdi --disable-vvfat --disable-qed --disable-parallels  --disable-user --disable-bsd-user --disable-linux-user --enable-system  --disable-hax --disable-hvf --disable-whpx --disable-xen --enable-kvm --enable-tcg  --disable-cocoa --disable-gtk --disable-sdl --disable-sdl-image --disable-spice --disable-virglrenderer --disable-vnc --disable-vnc-jpeg --disable-vnc-sasl --disable-vte --enable-curses --enable-iconv  --enable-coroutine-pool --enable-crypto-afalg --enable-live-block-migration --enable-membarrier --enable-replication --enable-lto --enable-tools  --audio-drv-list='' --disable-attr --disable-auth-pam --disable-brlapi --disable-bzip2 --disable-cap-ng --disable-capstone --disable-containers --disable-curl --disable-debug-info --disable-debug-mutex --disable-debug-tcg --disable-docs --disable-fuse --disable-gcrypt --disable-download --disable-glusterfs --disable-gnutls --disable-guest-agent-msi --disable-libiscsi --disable-libnfs --disable-libpmem --disable-libssh --disable-libusb --disable-linux-aio --disable-linux-io-uring --disable-lzfse --disable-lzo --disable-modules --disable-module-upgrades --disable-mpath --disable-netmap --disable-nettle --disable-numa --disable-opengl --disable-plugins --disable-pvrdma --disable-qom-cast-debug --disable-rbd --disable-rdma --disable-sanitizers --disable-seccomp --disable-smartcard --disable-snappy --disable-sparse --disable-strip --disable-tcg-interpreter --disable-tpm --disable-usb-redir --disable-vde --disable-virtfs --disable-werror --disable-xen-pci-passthrough --disable-xkbcommon --disable-zstd --disable-selinux --disable-oss --disable-alsa --disable-pa --disable-vduse-blk-export --disable-libdw  --target-list='  ' ; fi; )
Using './build' as the directory for build output
ERROR: unknown option --disable-hax
Try '/home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0/configure --help' for more information
make[3]: *** [Makefile:457: /home/builder/lede_x86/build_dir/target-x86_64_musl/qemu-9.0.0/.configured_696283a80b29635d0ff98dd8c9c795ba] Error 1

**Comment by TheLastManT1** [comment]
找到lede/feeds/packages/utils/qemu下的makefile，编辑文件，删除--disable-hax这一行。也就是339行
