### ISSUE TITLE
一直卡在这里，不知道咋回事。。。

### ISSUE THREAD

**Issue by cntink** [coolsnowwolf/lede#12141]
### 详细叙述

![PixPin_2024-05-07_18-20-45](https://github.com/coolsnowwolf/lede/assets/22174761/9c3a3c71-4e94-4dd4-85d7-821134244b42)
咋回事啊，好像是卡下载，但是又不是每次都一样，节点换了N个，始终过不去，怎么办啊！

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X64

### 详细日志

mkdir -p /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/cntink/Desktop/lede/tmp/.root-copy.flock -c 'cp -fpR /home/cntink/Desktop/lede/build_dir/target-x86_64_musl/luci-app-docker/.pkgdir/luci-app-docker/. /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-app-docker_installed
echo "luci-app-docker" >> /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-docker.default.install
mkdir -p /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/cntink/Desktop/lede/tmp/.root-copy.flock -c 'cp -fpR /home/cntink/Desktop/lede/build_dir/target-x86_64_musl/luci-app-docker/.pkgdir/luci-i18n-docker-zh-cn/. /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.luci-i18n-docker-zh-cn_installed
echo "luci-i18n-docker-zh-cn" >> /home/cntink/Desktop/lede/staging_dir/target-x86_64_musl/pkginfo/luci-app-docker.default.install
make[3]: Leaving directory '/home/cntink/Desktop/lede/feeds/luci/applications/luci-app-docker'
time: package/feeds/luci/luci-app-docker/compile#0.09#0.10#0.20
100  560k    0  560k    0     0    166      0 --:--:--  0:57:34 --:--:--     0

**Comment by binge8** [comment]
梯子不行
