### ISSUE TITLE
编译卡Text Base (TEXT BASE) [] (NEW)

### ISSUE THREAD

**Issue by Lemon1151** [coolsnowwolf/lede#12146]
### 详细叙述

![(F4%P0K5{@HTRF50SC Z19F](https://github.com/coolsnowwolf/lede/assets/149338935/afe1cb03-07ea-4f5a-8b46-215a82c735be)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

XIAOBAO

### 详细日志

Text Base (TEXT BASE) [] (NEW)

**Comment by WYC-2020** [comment]
记得不错前几天也有一个这种的，自己去看看 https://github.com/coolsnowwolf/lede/issues/12140

**Comment by WYC-2020** [comment]
根据 uboot改名是v2023.01-rc1  l这边uboot-rockchip中的版本是2023.07 应该是没问题的才对，刚我也亲自编译了一下 这个型号 没遇到你说的那个问题，都是一把过，自己用下万能大法
