### ISSUE TITLE
我想刷回原版固件 请问需要什步骤

### ISSUE THREAD

**Issue by oneole** [coolsnowwolf/lede#12153]
### 详细叙述

我今天在刷回ImmortalWrt的固件时网页显示“不支持所上传的映像文件格式，请选择适合当前平台的通用映像文件。” 所以我是需要什么别的步骤刷回去还是要进maskrom模式才能刷回去。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Nanopi R6s

### 详细日志

null

**Comment by ZGNCZMY** [comment]
这种问题你应该去论坛问的

**Comment by oneole** [comment]
> 这种问题你应该去论坛问的

好的 谢谢！
