### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by ChaingTsung** [coolsnowwolf/lede#12151]
### 详细叙述

configure.ac:70: error: require Automake 1.16.3, but have 1.15.1

我把宿主机automake升级到了最新
```
automake (GNU automake) 1.16.5
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```
还是不行

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

xiguapi v3

### 详细日志

...
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/luci/protocols/luci-proto-ipip'
time: package/feeds/luci/luci-proto-ipip/compile#0.23#0.10#0.32
make[3]: Entering directory '/home/yoki/XiguaPi4/package/network/utils/umbim'
mkdir -p /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/yoki/XiguaPi4/tmp/.root-copy.flock -c 'cp -fpR /home/yoki/XiguaPi4/build_dir/target-aarch64_generic_musl/umbim-2019-09-11-184b707d/.pkgdir/umbim/. /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.umbim_installed
echo "umbim" >> /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/pkginfo/umbim.default.install
make[3]: Leaving directory '/home/yoki/XiguaPi4/package/network/utils/umbim'
time: package/network/utils/umbim/compile#0.20#0.06#0.24
make[3]: Entering directory '/home/yoki/XiguaPi4/feeds/luci/protocols/luci-proto-mbim'
mkdir -p /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/yoki/XiguaPi4/tmp/.root-copy.flock -c 'cp -fpR /home/yoki/XiguaPi4/build_dir/target-aarch64_generic_musl/luci-proto-mbim/.pkgdir/luci-proto-mbim/. /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.luci-proto-mbim_installed
echo "luci-proto-mbim" >> /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/pkginfo/luci-proto-mbim.default.install
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/luci/protocols/luci-proto-mbim'
time: package/feeds/luci/luci-proto-mbim/compile#0.23#0.15#0.37
make[3]: Entering directory '/home/yoki/XiguaPi4/feeds/packages/libs/pcre2'
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/packages/libs/pcre2'
time: package/feeds/packages/pcre2/host-compile#0.21#0.09#0.26
make[3]: Entering directory '/home/yoki/XiguaPi4/feeds/packages/libs/glib2'
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/packages/libs/glib2'
time: package/feeds/packages/glib2/host-compile#0.24#0.09#0.31
make[3]: Entering directory '/home/yoki/XiguaPi4/feeds/packages/libs/libxml2'
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/packages/libs/libxml2'
time: package/feeds/packages/libxml2/host-compile#0.21#0.11#0.27
make[3]: Entering directory '/home/yoki/XiguaPi4/feeds/packages/libs/libxslt'
CFLAGS="-O2 -I/home/yoki/XiguaPi4/staging_dir/host/include -I/home/yoki/XiguaPi4/staging_dir/hostpkg/include -I/home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/host/include" CPPFLAGS="-I/home/yoki/XiguaPi4/staging_dir/host/include -I/home/yoki/XiguaPi4/staging_dir/hostpkg/include -I/home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/host/include" CXXFLAGS="" LDFLAGS="-L/home/yoki/XiguaPi4/staging_dir/host/lib -L/home/yoki/XiguaPi4/staging_dir/hostpkg/lib -L/home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/host/lib" make -j1 -C /home/yoki/XiguaPi4/build_dir/hostpkg/libxslt-1.1.39
make[4]: Entering directory '/home/yoki/XiguaPi4/build_dir/hostpkg/libxslt-1.1.39'
 cd . && /usr/bin/env bash /home/yoki/XiguaPi4/build_dir/hostpkg/libxslt-1.1.39/missing automake-1.15 --foreign
configure.ac:70: error: require Automake 1.16.3, but have 1.15.1
make[4]: *** [Makefile:462: Makefile.in] Error 1
make[4]: Leaving directory '/home/yoki/XiguaPi4/build_dir/hostpkg/libxslt-1.1.39'
make[3]: *** [Makefile:165: /home/yoki/XiguaPi4/build_dir/hostpkg/libxslt-1.1.39/.built] Error 2
make[3]: Leaving directory '/home/yoki/XiguaPi4/feeds/packages/libs/libxslt'
time: package/feeds/packages/libxslt/host-compile#0.49#0.19#0.70
    ERROR: package/feeds/packages/libxslt [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/libxslt/host/compile] Error 1
make[2]: Leaving directory '/home/yoki/XiguaPi4'
make[1]: *** [package/Makefile:110: /home/yoki/XiguaPi4/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yoki/XiguaPi4'
make: *** [/home/yoki/XiguaPi4/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
自己不知道哪里搞的缝合，l官方不是早就1.16.5了，这种版本不适配 我都不知道说了多少次了 升级宿主机没用，别人是用的lede的工具链集中的的automake，自己吧tools下面的automake升级，不知道从何时开始，只要版本不适配你们都以为是宿主机版本不对导致的
