### ISSUE TITLE
请求修复RA5JDC设备

### ISSUE THREAD

**Issue by f1owkang** [coolsnowwolf/lede#12179]
### 详细叙述

听您说是uboot 参数问题，我尝试自己修复了RA5的设备树。但是无法编译通过，又尝试移植了https://github.com/JiaY-shi/openwrt 的仓库，也是出现很多问题例如
`  CC      drivers/thermal/thermal_trip.o
drivers/thermal/thermal_trip.c: In function '__thermal_zone_get_trip':
drivers/thermal/thermal_trip.c:118:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  118 |         if (!tz || trip_id < 0 || trip_id >= tz->num_trips || !trip)
      |         ^~
drivers/thermal/thermal_trip.c:121:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  121 |                 if (tz->trips) {
      |                 ^~
`
种种无奈请求大佬修复或者指点一下，感激不尽

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

RA50

### 详细日志

lede正常编译，编译固件无法启动

**Comment by f1owkang** [comment]
这里是LEDE编译固件刷入之后产生的日志，刚启动之后一会儿死机
[   13.747209] EXT4-fs (loop0): mounted filesystem with ordered data mode. Quota mode: disabled.
[   13.747397] block: attempting to load /tmp/ext4_cfg/upper/etc/config/fstab
[   13.754892] block: unable to load configuration (fstab: Entry not found)
[   13.761536] block: attempting to load /tmp/ext4_cfg/etc/config/fstab
[   13.768399] block: unable to load configuration (fstab: Entry not found)
[   13.774797] block: attempting to load /etc/config/fstab
[   13.783414] block: unable to load configuration (fstab: Entry not found)
[   13.786336] block: no usable configuration
[   13.793605] EXT4-fs (loop0): unmounting filesystem.
[   13.798546] loop0: detected capacity change from 0 to 231464
[   13.851367] loop0: detected capacity change from 231464 to 102568
[   13.855040] EXT4-fs (loop0): mounted filesystem with ordered data mode. Quota mode: disabled.
[   13.979154] block: attempting to load /tmp/ext4_cfg/upper/etc/config/fstab
[   13.979248] block: unable to load configuration (fstab: Entry not found)
[   13.985015] block: attempting to load /tmp/ext4_cfg/etc/config/fstab
[   13.991930] block: unable to load configuration (fstab: Entry not found)
[   13.998150] block: attempting to load /etc/config/fstab
[   14.004854] block: unable to load configuration (fstab: Entry not found)
[   14.009778] block: no usable configuration
[   14.017653] mount_root: overlay filesystem has not been fully initialized yet
[   14.021417] mount_root: switching to ext4 overlay
[   14.030894] overlayfs: null uuid detected in lower fs '/', falling back to xino=off,index=off,nfs_export=off.
[   14.037720] urandom-seed: Seed file not found (/etc/urandom.seed)
Scanning for Btrfs filesystems
[   14.459796] procd: - early -
[   14.459899] procd: - watchdog -
[   15.080391] procd: - watchdog -
[   15.132556] procd: - ubus -
[   15.322555] procd: - init -
Please press Enter to activate this console.
[   15.833179] urngd: v1.0.2 started.
[   16.466189] kmodloader: loading kernel modules from /etc/modules.d/*
[   16.557935] NET: Registered PF_ALG protocol family
[   16.568800] FS-Cache: Loaded
[   16.570006] CacheFiles: Loaded
[   16.572523] Key type dns_resolver registered
[   16.605932] NET: Registered PF_RXRPC protocol family
[   16.605970] Key type rxrpc registered
[   16.609961] Key type rxrpc_s registered
[   16.616170] kAFS: Red Hat AFS client v0.1 registering.
[   16.751369] kAFS: failed to register: -97
[   16.857637] tun: Universal TUN/TAP device driver, 1.6
[   16.868229] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   16.961197] cryptodev: driver 1.13 loaded.
[   16.964768] ntfs3: Max link count 4000
[   16.964805] ntfs3: Enabled Linux POSIX ACLs support
[   17.001160] Bridge firewalling registered
[   17.001820] Loading modules backported from Linux version v6.1.24-0-g0102425ac76b
[   17.004157] Backport generated by backports.git v5.15.92-1-44-gd6ea70fafd36
[   17.059383] NET: Registered PF_QIPCRTR protocol family
[   17.065238] usbcore: registered new interface driver ums-alauda
[   17.066312] usbcore: registered new interface driver ums-cypress
[   17.071008] usbcore: registered new interface driver ums-datafab
[   17.077195] usbcore: registered new interface driver ums-freecom
[   17.083212] usbcore: registered new interface driver ums-isd200
[   17.089119] usbcore: registered new interface driver ums-jumpshot
[   17.094726] usbcore: registered new interface driver ums-karma
[   17.101121] usbcore: registered new interface driver ums-sddr09
[   17.106786] usbcore: registered new interface driver ums-sddr55
[   17.112674] usbcore: registered new interface driver ums-usbat
[   17.130302] xt_time: kernel timezone is -0000
[   17.150693] PPP generic driver version 2.4.2
[   17.151764] PPP MPPE Compression module registered
[   17.154976] NET: Registered PF_PPPOX protocol family
[   17.166919] ath11k c000000.wifi: ipq6018 hw1.0
[   17.166954] ath11k c000000.wifi: FW memory mode: 1
[   17.170581] remoteproc remoteproc0: powering up cd00000.remoteproc
[   17.175964] remoteproc remoteproc0: Booting fw image IPQ6018/q6_fw.mdt, size 7340
[   17.857692] remoteproc remoteproc0: remote processor cd00000.remoteproc is now up
[   17.858944] ath11k c000000.wifi: qmi ignore invalid mem req type 3
[   17.864794] ath11k c000000.wifi: chip_id 0x0 chip_family 0x4 board_id 0xff soc_id 0xffffffff
[   17.870253] ath11k c000000.wifi: fw_version 0x250a04b8 fw_build_timestamp 2021-12-20 07:20 fw_build_id WLAN.HK.2.5.0.1-01208-QCAHKSWPL_SILICONZ-1
[   17.879404] kAFS: Red Hat AFS client v0.1 registering.
[   18.071383] kAFS: failed to register: -97
[   18.241740] kmodloader: 1 module could not be probed
[   18.241859] kmodloader: - kafs - 0
[   37.794262] EXT4-fs (mmcblk0p22): recovery complete
[   37.794305] EXT4-fs (mmcblk0p22): mounted filesystem with ordered data mode. Quota mode: disabled.
[   37.797972] ext4 filesystem being mounted at /mnt/mmcblk0p22 supports timestamps until 2038 (0x7fffffff)
[   37.810312] EXT4-fs (mmcblk0p24): recovery complete
[   37.816633] EXT4-fs (mmcblk0p24): mounted filesystem with ordered data mode. Quota mode: disabled.
[   37.829309] EXT4-fs (mmcblk0p25): recovery complete
[   37.830249] EXT4-fs (mmcblk0p25): mounted filesystem with ordered data mode. Quota mode: disabled.
[   41.626789] nss-dp 3a001200.dp2 lan1: PHY Link up speed: 1000
[   41.627480] br-lan: port 1(lan1) entered blocking state
[   41.631585] br-lan: port 1(lan1) entered disabled state
[   41.636790] device lan1 entered promiscuous mode
[   41.650593] br-lan: port 2(lan2) entered blocking state
[   41.650642] br-lan: port 2(lan2) entered disabled state
[   41.654981] device lan2 entered promiscuous mode
[   41.664561] br-lan: port 3(lan3) entered blocking state
[   41.664711] br-lan: port 3(lan3) entered disabled state
[   41.669908] device lan3 entered promiscuous mode
[   42.495757] br-lan: port 4(wlan0) entered blocking state
[   42.495801] br-lan: port 4(wlan0) entered disabled state
[   42.500428] device wlan0 entered promiscuous mode
[   42.505657] br-lan: port 4(wlan0) entered blocking state
[   42.510044] br-lan: port 4(wlan0) entered forwarding state
[   42.515679] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   42.623170] br-lan: port 5(wlan1) entered blocking state
[   42.623214] br-lan: port 5(wlan1) entered disabled state
[   42.627771] device wlan1 entered promiscuous mode
[   42.632999] br-lan: port 5(wlan1) entered blocking state
[   42.637453] br-lan: port 5(wlan1) entered forwarding state
[   42.642989] br-lan: port 1(lan1) entered blocking state
[   42.648140] br-lan: port 1(lan1) entered forwarding state
[   42.654162] br-lan: port 4(wlan0) entered disabled state
[   42.664157] br-lan: port 5(wlan1) entered disabled state
[   42.726623] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   42.726813] br-lan: port 5(wlan1) entered blocking state
[   42.732080] br-lan: port 5(wlan1) entered forwarding state
[   43.030759] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   43.030984] br-lan: port 4(wlan0) entered blocking state
[   43.036290] br-lan: port 4(wlan0) entered forwarding state
[   51.610773] qcom-q6v5-wcss-pil cd00000.remoteproc: fatal error received: 
[   51.610773] QC Image Version: QC_IMAGE_VERSION_STRING=WLAN.HK.2.5.0.1-01208-QCAHKSWPL_SILICONZ-1
[   51.610773] Image Variant : IMAGE_VARIANT_STRING=6018.wlanfw.evalQ
[   51.610773] 
[   51.610773] NOC_error.c:474 NOCError: FATAL ERRORparam0 :zero, param1 :zero, param2 :zero.
[   51.610773] Thread ID      : 0x0000006f  Thread name    : ABTIST182  Process ID     : 0
[   51.610773] Register:
[   51.610773] SP : 0x4af81ef8
[   51.610773] FP : 0x4af81f00
[   51.610773] PC : 0x4ac8d548
[   51.610773] SSR : 0x00000008
[   51.610773] BADVA : 0x00020000
[   51.610773] LR : 0x4ac8cce4
[   51.610773] 
[   51.610773] Stack Dump
[   51.610773] from : 0x4af81ef8
[   51.610773] to   : 0x4af81fd0
[   51.610773] 
[   51.657671] remoteproc remoteproc0: crash detected in cd00000.remoteproc: type fatal error
[   51.679940] remoteproc remoteproc0: handling crash #1 in cd00000.remoteproc
[   51.687965] remoteproc remoteproc0: recovering cd00000.remoteproc

Format: Log Type - Time(microsec) - Message - Optional Info
Log Type: B - Since Boot(Power On Reset),  D - Delta,  S - Statistic
S - QC_IMAGE_VERSION_STRING=BOOT.XF.0.3-00077-IPQ60xxLZB-2
S - IMAGE_VARIANT_STRING=IPQ6018LA
S - OEM_IMAGE_VERSION_STRING=crm-ubuntu64
S - Boot Interface: eMMC
S - Secure Boot: Off
S - Boot Config @ 0x000a602c = 0x000002e3
S - JTAG ID @ 0x000a607c = 0x001390e1
S - OEM ID @ 0x000a6080 = 0x00000000
S - Serial Number @ 0x000a4128 = 0x3f7c9a2a
S - OEM Config Row 0 @ 0x000a4188 = 0x0000000000000000
S - OEM Config Row 1 @ 0x000a4190 = 0x0000000000000000
S - Feature Config Row 0 @ 0x000a4130 = 0x0000800018200021
S - Feature Config Row 1 @ 0x000a4138 = 0x02c3e83783000009
S - PBL Patch Ver: 1
S - I-cache: On
S - D-cache: On
B -      3413 - PBL, Start
B -       592 - bootable_media_detect_entry, Start
B -      4339 - bootable_media_detect_success, Start
B -     32254 - elf_loader_entry, Start
B -     32425 - auth_hash_seg_entry, Start
B -     33407 - auth_hash_seg_exit, Start
B -     33904 - elf_segs_hash_verify_entry, Start
B -     61721 - elf_segs_hash_verify_exit, Start
B -     66147 - auth_xbl_sec_hash_seg_entry, Start
B -     66289 - auth_xbl_sec_hash_seg_exit, Start
B -     72834 - xbl_sec_segs_hash_verify_entry, Start
B -     72835 - xbl_sec_segs_hash_verify_exit, Start
B -     73764 - PBL, End
B -     65239 - SBL1, Start
B -    205295 - GCC [RstStat:0x2, RstDbg:0x420100] WDog Stat : 0x4
B -    207735 - clock_init, Start
D -      2897 - clock_init, Delta
B -    216367 - boot_flash_init, Start
D -     55022 - boot_flash_init, Delta
B -    274683 - sbl1_ddr_set_default_params, Start
D -       244 - sbl1_ddr_set_default_params, Delta
B -    281118 - boot_config_data_table_init, Start
D -      2165 - boot_config_data_table_init, Delta - (575 Bytes)
B -    290268 - CDT Version:2,Platform ID:8,Major ID:3,Minor ID:2,Subtype:0
B -    295819 - Image Load, Start
D -      6588 - OEM_MISC Image Loaded, Delta - (0 Bytes)
B -    305152 - Image Load, Start
D -      5063 - PMIC Image Loaded, Delta - (0 Bytes)
B -    313021 - sbl1_ddr_set_params, Start
B -    317993 - CPR configuration: 0x366
B -    321195 - Pre_DDR_clock_init, Start
D -       213 - Pre_DDR_clock_init, Delta
D -         0 - sbl1_ddr_set_params, Delta

**Comment by f1owkang** [comment]
最近找到内核6.6的可用

**Comment by FreshKai** [comment]
您好，有RA50 JDC修复后的固件吗？
我看您主页仓库中的[OpenWrt](https://github.com/f1owkang/OpenWrt)中的描述支持JDC-AX5，是这个吗？
 @f1owkang

**Comment by f1owkang** [comment]
> 您好，有RA50 JDC修复后的固件吗？ 我看您主页仓库中的[OpenWrt](https://github.com/f1owkang/OpenWrt)中的描述支持JDC-AX5，是这个吗？ @f1owkang

是的，但是需要自己稍加修改

**Comment by FreshKai** [comment]
> > 您好，有RA50 JDC修复后的固件吗？ 我看您主页仓库中的[OpenWrt](https://github.com/f1owkang/OpenWrt)中的描述支持JDC-AX5，是这个吗？ @f1owkang
> 
> 是的，但是需要自己稍加修改

指的是配置文件吗？还是需要在代码层面改动呢？

**Comment by f1owkang** [comment]
> > > 您好，有RA50 JDC修复后的固件吗？ 我看您主页仓库中的[OpenWrt](https://github.com/f1owkang/OpenWrt)中的描述支持JDC-AX5，是这个吗？ @f1owkang
> > 
> > 
> > 是的，但是需要自己稍加修改
> 
> 指的是配置文件吗？还是需要在代码层面改动呢？

配置文件

**Comment by FreshKai** [comment]
> > > > 您好，有RA50 JDC修复后的固件吗？ 我看您主页仓库中的[OpenWrt](https://github.com/f1owkang/OpenWrt)中的描述支持JDC-AX5，是这个吗？ @f1owkang
> > > 
> > > 
> > > 是的，但是需要自己稍加修改
> > 
> > 
> > 指的是配置文件吗？还是需要在代码层面改动呢？
> 
> 配置文件

好的，感谢您的工作
