### ISSUE TITLE
vccio_acodec: disabling

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#12185]
### 详细叙述

在系统日志和内核日志中出现vccio_acodec: disabling，内核为Linux6.6，请问这会有什么影响吗

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Nanopi R5S

### 详细日志

vccio_acodec: disabling

**Comment by aiamadeus** [comment]
没有任何影响。
