### ISSUE TITLE
红米ac2100编译出错

### ISSUE THREAD

**Issue by bobandbrony** [coolsnowwolf/lede#12194]
### 详细叙述

https://y5hwpw3fsi.feishu.cn/docx/UO0wdHReDoUdewxwlpGckSjin3d
使用这个教程部署部署的

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

红米ac2100  cpu是mtk7621at

### 详细日志

make[4]: Entering directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
mipsel-openwrt-linux-musl-gcc -std=c99 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1=dns2tcp-1.1.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -c libev/ev.c -o libev/ev.o
libev/ev.c:2139:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^~~~~~~~~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:4260: Error: opcode not supported on this processor: mips2 (mips2) `sync'
{standard input}:4535: Error: opcode not supported on this processor: mips2 (mips2) `sync'
make[4]: *** [Makefile:25: libev/ev.o] Error 1
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
make[3]: *** [Makefile:45: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/small/dns2tcp'
time: package/feeds/small/dns2tcp/compile#0.36#0.08#0.42
    ERROR: package/feeds/small/dns2tcp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/dns2tcp/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by WYC-2020** [comment]
xiaorouji 那边更新有问题 
![image](https://github.com/coolsnowwolf/lede/assets/34025388/275103ac-5815-4717-9ef0-774bac5a2818)
PKG_USE_MIPS16:=0这个保留 在编译试试

**Comment by bobandbrony** [comment]
https://github.com/bobandbrony/OpenWrt-
在这里编译，该如何操作呢

**Comment by bobandbrony** [comment]
云编译依然不行，但本地编译成功了
![image](https://github.com/coolsnowwolf/lede/assets/129247570/beb98349-2c6b-4a71-9d52-a5b328339750)
谢谢！

**Comment by Asyncload** [comment]
> 云编译依然不行，但本地编译成功了
> ![image](https://github.com/coolsnowwolf/lede/assets/129247570/beb98349-2c6b-4a71-9d52-a5b328339750)
> 谢谢！

你本地编译修改了哪里？

**Comment by eearphon** [comment]
> xiaorouji 那边更新有问题 ![image](https://private-user-images.githubusercontent.com/34025388/334054673-275103ac-5815-4717-9ef0-774bac5a2818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzYwOTcsIm5iZiI6MTcxNzAzNTc5NywicGF0aCI6Ii8zNDAyNTM4OC8zMzQwNTQ2NzMtMjc1MTAzYWMtNTgxNS00NzE3LTllZjAtNzc0YmFjNWEyODE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAyMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYWQzZmY4NmE3NDY3YmU0ZDg1NTgwODExMjU5NWJhNmY0MTBhMjYxYzlkZjU2OTE3OWFkODA4ZGNhMDQ5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v_o5x8Yg-QDTgmbnMDl1s5tSMECXdsMAwpy5W3WoGSU) PKG_USE_MIPS16:=0这个保留 在编译试试

谢谢，加回这句编译成功，newifi-d1
