### ISSUE TITLE
最近出现的情况

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#12195]
### 详细叙述

这个界面是这样的，以前不是，请问大佬这是哪里出了问题啊。编译是正常的。
![26-5-2024](https://github.com/coolsnowwolf/lede/assets/88958866/f39ed876-4d61-441d-a7e7-f56c5b198aba)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

没有

**Comment by WYC-2020** [comment]
自己显示问题，是ssh连接的么 重启一下 然后重新链接ssh 试试 ，如果是ubuntu 桌面版 重启一下 如果是vm虚拟机重新安装一下虚拟机的那个linux 驱动
