### ISSUE TITLE
ar71xx最新的源码usb支持装不上

### ISSUE THREAD

**Issue by 739669495** [coolsnowwolf/lede#122]
root@LEDE:~# opkg update
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_core
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/base/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_base
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/base/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_luci
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/luci/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_packages
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_routing
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/routing/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_telephony
Downloading http://downloads.lede-project.org/releases/17.01.3/packages/mips_24k                           c/telephony/Packages.sig
Signature check passed.
root@LEDE:~# opkg install kmod-usb-core
Package kmod-usb-core (4.9.54-1) installed in root is up to date.
root@LEDE:~# opkg install kmod-usb-ohci
Installing kmod-usb-ohci (4.4.89-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/kmod-usb-ohci_4.4.89-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-                           usb-ohci:
 *      kernel (= 4.4.89-1-45d282495a15974d60f8edb091d0e2a9) *
 * opkg_install_cmd: Cannot install package kmod-usb-ohci.
root@LEDE:~# opkg install kmod-usb-uhci
Installing kmod-usb-uhci (4.4.89-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/kmod-usb-uhci_4.4.89-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-                           usb-uhci:
 *      kernel (= 4.4.89-1-45d282495a15974d60f8edb091d0e2a9) *
 * opkg_install_cmd: Cannot install package kmod-usb-uhci.
root@LEDE:~# opkg install kmod-usb-storage
Installing kmod-usb-storage (4.4.89-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/kmod-usb-storage_4.4.89-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-                           usb-storage:
 *      kernel (= 4.4.89-1-45d282495a15974d60f8edb091d0e2a9) *  kernel (= 4.4.89                           -1-45d282495a15974d60f8edb091d0e2a9) *
 * opkg_install_cmd: Cannot install package kmod-usb-storage.
root@LEDE:~# opkg install kmod-usb2
Package kmod-usb2 (4.9.54-1) installed in root is up to date.
root@LEDE:~# opkg install block-mount
Package block-mount (2017-07-31-8ab4fda6-1) installed in root is up to date.
root@LEDE:~# opkg install block-hotplug
Unknown package 'block-hotplug'.
Collected errors:
 * opkg_install_cmd: Cannot install package block-hotplug.
root@LEDE:~# opkg install block-extroot
Unknown package 'block-extroot'.
Collected errors:
 * opkg_install_cmd: Cannot install package block-extroot.
root@LEDE:~# opkg install  kmod-fs-ext4
Installing kmod-fs-ext4 (4.4.89-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.3/targets/ar71xx/ge                           neric/packages/kmod-fs-ext4_4.4.89-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-                           fs-ext4:
 *      kernel (= 4.4.89-1-45d282495a15974d60f8edb091d0e2a9) *  kernel (= 4.4.89                           -1-45d282495a15974d60f8edb091d0e2a9) *  kernel (= 4.4.89-1-45d282495a15974d60f8e                           db091d0e2a9) *  kernel (= 4.4.89-1-45d282495a15974d60f8edb091d0e2a9) *

**Comment by coolsnowwolf** [comment]
内核版本不一样，请编译时候选定
