### ISSUE TITLE
大神们这又是哪里的问题

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#12201]
### 详细叙述

依赖全部安装正常

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

x86_64-openwrt-linux-musl-gcc -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-use -fprofile-correction -I./Include/internal -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I./Include -I. -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -c /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.c -o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.o -DPy_BUILD_CORE_MODULE -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1
cc1: note: someone does not honour COPTS correctly, passed 3 times
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.c: In function '_ctypes_alloc_callback':
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.c:464:1: warning: '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.gcda' profile count data file not found [-Wmissing-profile]
  464 | }
      | ^
x86_64-openwrt-linux-musl-gcc -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-use -fprofile-correction -I./Include/internal -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I./Include -I. -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -c /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.c -o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.o -DPy_BUILD_CORE_MODULE -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1
cc1: note: someone does not honour COPTS correctly, passed 3 times
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.c: In function 'buffer_info':
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.c:2031:1: warning: '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.gcda' profile count data file not found [-Wmissing-profile]
 2031 | };
      | ^
x86_64-openwrt-linux-musl-gcc -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-use -fprofile-correction -I./Include/internal -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I./Include -I. -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -c /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.c -o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.o -DPy_BUILD_CORE_MODULE -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1
cc1: note: someone does not honour COPTS correctly, passed 3 times
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.c: In function '_ctypes_get_fielddesc':
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.c:1627:1: warning: '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.gcda' profile count data file not found [-Wmissing-profile]
 1627 | ffi_type ffi_type_pointer = { sizeof(void *), VOID_P_ALIGN, FFI_TYPE_POINTER };
      | ^~~~~~~~
x86_64-openwrt-linux-musl-gcc -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-use -fprofile-correction -I./Include/internal -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I./Include -I. -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include -I/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Include -I/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -c /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.c -o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.o -DPy_BUILD_CORE_MODULE -DHAVE_FFI_PREP_CIF_VAR=1 -DHAVE_FFI_PREP_CLOSURE_LOC=1 -DHAVE_FFI_CLOSURE_ALLOC=1
cc1: note: someone does not honour COPTS correctly, passed 3 times
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.c: In function 'PyCStructUnionType_update_stgdict':
/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.c:898:1: warning: '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.gcda' profile count data file not found [-Wmissing-profile]
  898 | }
      | ^
x86_64-openwrt-linux-musl-gcc -shared -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/_ctypes.o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callbacks.o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/callproc.o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/cfield.o build/temp.linux-x86_64-3.10/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Modules/_ctypes/stgdict.o -L. -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/x86_64-openwrt-linux-musl/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc -lffi -ldl -o build/lib.linux-x86_64-3.10/_ctypes.cpython-310.so

The necessary bits to build these optional modules were not found:
_tkinter             nis                                    
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                 pwd                  time              
zlib                                                        

running build_scripts
copying /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Tools/scripts/pydoc3 -> build/scripts-3.10
copying /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Tools/scripts/idle3 -> build/scripts-3.10
copying /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Tools/scripts/2to3 -> build/scripts-3.10
renaming build/scripts-3.10/pydoc3 to build/scripts-3.10/pydoc3.10
renaming build/scripts-3.10/idle3 to build/scripts-3.10/idle3.10
renaming build/scripts-3.10/2to3 to build/scripts-3.10/2to3-3.10
x86_64-openwrt-linux-musl-gcc -c -Wno-unused-result -Wsign-compare -DNDEBUG -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7=Python-3.10.7 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include   -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-use -fprofile-correction -I./Include/internal  -I. -I./Include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify -I/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include   -fPIC -DPy_BUILD_CORE -o Programs/_testembed.o ./Programs/_testembed.c
cc1: note: someone does not honour COPTS correctly, passed 3 times
./Programs/_testembed.c: In function 'main':
./Programs/_testembed.c:1901:1: warning: '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Programs/_testembed.gcda' profile count data file not found [-Wmissing-profile]
 1901 | }
      | ^
x86_64-openwrt-linux-musl-gcc -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/ubuntu/peaceful/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -L/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7 -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/usr/lib -L/ubuntu/peaceful/staging_dir/target-x86_64_musl/lib -fno-semantic-interposition -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g  -Xlinker -export-dynamic -o Programs/_testembed Programs/_testembed.o -L. -lpython3.10 -ldl  -lpthread -lm -lz   -lm 
make[5]: Leaving directory '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7'
make[4]: Leaving directory '/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7'
# Use host pip to install python-setuptools
/ubuntu/peaceful/staging_dir/hostpkg/bin/pip3.10 --disable-pip-version-check --cache-dir "/ubuntu/peaceful/dl/pip-cache" install --ignore-installed --root=/ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/install-setuptools --prefix=/usr /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/Lib/ensurepip/_bundled/setuptools-63.2.0-py3-none-any.whl
bash: line 1: /ubuntu/peaceful/staging_dir/hostpkg/bin/pip3.10: cannot execute: required file not found
make[3]: *** [Makefile:383: /ubuntu/peaceful/build_dir/target-x86_64_musl/Python-3.10.7/.built] Error 127
make[3]: Leaving directory '/ubuntu/peaceful/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/compile#1007.40#49.75#1060.73
    ERROR: package/feeds/packages/python3 failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/python3/compile] Error 1
make[2]: Leaving directory '/ubuntu/peaceful'
make[1]: *** [package/Makefile:110: /ubuntu/peaceful/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/ubuntu/peaceful'
make: *** [/ubuntu/peaceful/include/toplevel.mk:231: world] Error 2

**Comment by coldrook** [comment]
+1,the same issue

**Comment by WYC-2020** [comment]
apt install python3-pyelftools

**Comment by caixin1218** [comment]
> apt install python3-pyelftools

不是这个问题，已经安装好了 apt install python3-pyelftools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyelftools is already the newest version (0.30-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Asyncload** [comment]
> +1,the same issue
Me too

**Comment by WYC-2020** [comment]
> > apt install python3-pyelftools
> 
> 不是这个问题，已经安装好了 apt install python3-pyelftools Reading package lists... Done Building dependency tree... Done Reading state information... Done python3-pyelftools is already the newest version (0.30-1). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

那无能为力我这边 吧python3 所有模块都选了 编译都不会出错  x86

**Comment by caixin1218** [comment]
> > > apt install python3-pyelftools
> > 
> > 
> > 不是这个问题，已经安装好了 apt install python3-pyelftools Reading package lists... Done Building dependency tree... Done Reading state information... Done python3-pyelftools is already the newest version (0.30-1). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 
> 那无能为力我这边 吧python3 所有模块都选了 编译都不会出错 x86

重新拉取源码，默认编译没有问题，只要加了驱动、模块、插件就一定有问题。但相同的config 以前没有问题。

**Comment by WYC-2020** [comment]
> > > > apt install python3-pyelftools
> > > 
> > > 
> > > 不是这个问题，已经安装好了 apt install python3-pyelftools Reading package lists... Done Building dependency tree... Done Reading state information... Done python3-pyelftools is already the newest version (0.30-1). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> > 
> > 
> > 那无能为力我这边 吧python3 所有模块都选了 编译都不会出错 x86
> 
> 重新拉取源码，默认编译没有问题，只要加了驱动、模块、插件就一定有问题。但相同的config 以前没有问题。

初步怀疑是插件那个有问题 你一个个排除 看下是那个呗 我这边没法复现没法看

**Comment by syb999** [comment]
错误日志里已经告诉你缺少，_tikinter和nis 这2个模块：
The necessary bits to build these optional modules were not found:
_tkinter nis
说明环境里缺少依赖库，需要安装各自的依赖后,再次编译:
sudo apt-get update
sudo apt-get install tk-dev libnsl2
