### ISSUE TITLE
开源驱动无线限速，有线能跑满，什么原因？

### ISSUE THREAD

**Issue by xseven121** [coolsnowwolf/lede#12200]
### 详细叙述

openwrt官方版的无线测试，连接速率866，却限速到100-120，怎么设置都不顶用。L大的编译出来的好像是闭源驱动，能跑满500的宽带，只是有个小bug，重启不能启动wifi。查了很多资料，没找到限速的原因，有没有知道的？
另外，主要是想组mesh，easymesh在闭源驱动上好像不能kvr漫游。
### 重复 issue

- [x] 没有类似的 issue

### 具体型号

redmi ac2100

### 详细日志

none

**Comment by aiamadeus** [comment]
不是限速，开源驱动在 mt7621 上性能不行

**Comment by xseven121** [comment]
> 不是限速，开源驱动在 mt7621 上性能不行

好吧，那没辙了。现在只能这样了
