### ISSUE TITLE
麻烦删除https://github.com/vividmuse/TPTJS-SDK库

### ISSUE THREAD

**Issue by johnbian** [coolsnowwolf/lede#12216]
### 详细叙述

你好，麻烦删除https://github.com/vividmuse/TPTJS-SDK库。这个公司已经要求下架，不得对外开放了。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

麻烦删除https://github.com/vividmuse/TPTJS-SDK库

### 详细日志

麻烦删除https://github.com/vividmuse/TPTJS-SDK库

**Comment by WYC-2020** [comment]
什么玩意，l这边有引入这个库？
