### ISSUE TITLE
关于R6S固件问题

### ISSUE THREAD

**Issue by kevin198346** [coolsnowwolf/lede#12226]
### 详细叙述

看到大神的网站的固件是23.6.9，我在电报群里下载的固件是23.11.23，我把固件弄到sd卡后，重新启动进入后台后，运行正常，发现重新启动或者断电后再重新启动，软路由恢复出厂设置。由于用大神固件非常稳定，想知道有什么地方可以下载最新的r6s最新的固件。盼回复。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

r6s

### 详细日志

恢复出厂设置

**Comment by yanxin152133** [comment]
自己编译丰衣足食 ：）

**Comment by kevin198346** [comment]
不会啦，算了用用istore is

Kevin Dai


cyx ***@***.***>于2024年7月15日 周一11:05写道：
