### ISSUE TITLE
softethervpn5

### ISSUE THREAD

**Issue by mumuou** [coolsnowwolf/lede#12228]
### 详细叙述

packages/net/softethervpn5 最新代码翻车了。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

erro

**Comment by binge8** [comment]
[不测试闭着眼上传](https://github.com/coolsnowwolf/packages/commit/797fcdd4f7fff6866c7177f93abfe4a9c444b9cb)

**Comment by HHJLKK** [comment]
https://github.com/coolsnowwolf/packages/pull/826 修好了，不好意思哈

**Comment by WYC-2020** [comment]
> 不测试闭着眼上传[+1](https://github.com/coolsnowwolf/packages/commit/797fcdd4f7fff6866c7177f93abfe4a9c444b9cb)

很多都是去个隔壁照搬，从来不测试已经见惯不怪了
