### ISSUE TITLE
ARM CPU使用率出现两个%

### ISSUE THREAD

**Issue by Gabrielxzx** [coolsnowwolf/lede#12234]
### 详细叙述

如图，最新版本更新后，CPU使用率出现两个%，
应该是https://github.com/coolsnowwolf/lede/commit/aeb660ba58b89b8f9eb05cc1c81d9aad7d66946e 更新后带来的
![image](https://github.com/coolsnowwolf/lede/assets/27126997/fc44da4a-4c42-4fe5-b1a9-a8e22a93ab01)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

FastRhino R66S

### 详细日志

无需日志

**Comment by zht713** [comment]
树莓派4B同样 “CPU使用率出现两个%”

**Comment by luxiaok** [comment]
```
cpu_usage="$(top -n1 | awk '/^CPU/ {printf("%d%", 100 - $8)}')"
echo -n "CPU: ${cpu_usage}%"
```

是多了一个百分号
