### ISSUE TITLE
系统日志被daemon.err dawn: ubus_call_umdns()=ubus.c@1385 Failed to look up test object for umdns刷屏

### ISSUE THREAD

**Issue by dragon888888888888** [coolsnowwolf/lede#12231]
### 详细叙述

最早搜到这个问题是2019年的，一直没有解决办法。 5.15虽然也有这个问题，用原版openwrt  package/network/services/umdns/files下的umdns.json和umdns.init替换掉LEDE版里的2个文件，编译后解决。但6.6内核这样做没有作用，系统日志一直被这个错误刷屏。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

光影猫

### 详细日志

已编译成功

**Comment by dragon888888888888** [comment]
按上面的方法重编译又线刷了一次，虽然不再报错。不过仍被daemon.notice hostapd: wlan0: BEACON-REQ-TX-STATUS aa:aa:aa:aa:aa:aa 6 ack=1 daemon.notice hostapd: wlan0: BEACON-RESP-RX aa:aa:aa:aa:aa:aa 1aa 0000000000000000000000008000000000000000000000000000
daemon.notice hostapd: wlan0: BEACON-REQ-TX-STATUS aa:aa:aa:aa:aa:aa 6 ack=1 daemon.notice hostapd: wlan0: BEACON-RESP-RX aa:aa:aa:aa:aa:aa 2aa 0000000000000000000000008000000000000000000000000000
daemon.notice hostapd: wlan0: BEACON-REQ-TX-STATUS aa:aa:aa:aa:aa:aa 6 ack=1 daemon.notice hostapd: wlan0: BEACON-RESP-RX aa:aa:aa:aa:aa:aa 3aa 0000000000000000000000008000000000000000000000000000
daemon.notice hostapd: wlan0: BEACON-REQ-TX-STATUS aa:aa:aa:aa:aa:aa 6 ack=1 daemon.notice hostapd: wlan0: BEACON-RESP-RX aa:aa:aa:aa:aa:aa 4aa 0000000000000000000000008000000000000000000000000000
daemon.notice hostapd: wlan0: BEACON-REQ-TX-STATUS aa:aa:aa:aa:aa:aa 6 ack=1 daemon.notice hostapd: wlan0: BEACON-RESP-RX aa:aa:aa:aa:aa:aa 5aa 0000000000000000000000008000000000000000000000000000
这种刷屏

**Comment by yanxin152133** [comment]
是不是这个原因
![image](https://github.com/coolsnowwolf/lede/assets/43341537/84e2a45f-c155-4779-9cb9-c2a68fc9b59f)

**Comment by dragon888888888888** [comment]
不是，离路由器2米左右，终端没有掉线

**Comment by yanxin152133** [comment]
aa:aa:aa:aa:aa:aa 6 ack=1   这个是蓝牙？我看别人的都是其他的
![image](https://github.com/coolsnowwolf/lede/assets/43341537/d3dd94c6-f812-4b3d-9fda-9945c9ed4129)

**Comment by dragon888888888888** [comment]
> aa:aa:aa:aa:aa:aa 6 ack=1 这个是蓝牙？我看别人的都是其他的 ![image](https://private-user-images.githubusercontent.com/43341537/338843082-d3dd94c6-f812-4b3d-9fda-9945c9ed4129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODg3NTQsIm5iZiI6MTcxODE4ODQ1NCwicGF0aCI6Ii80MzM0MTUzNy8zMzg4NDMwODItZDNkZDk0YzYtZjgxMi00YjNkLTlmZGEtOTk0NWM5ZWQ0MTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEwMzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOTdiM2ZhYzZkYjQ4NzUwZTcxZmNlOGY2NGMxMzc4MTRjNGI2YTI5YTg5OWM4N2VjNTg3YTI2MjAxYjM5MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EFpurDtOTe9tyqDAG2D8T3BByPpxBZnrZUYzqmRP0k)

有蓝牙，但是根本就没有选蓝牙驱动

**Comment by dragon888888888888** [comment]
找到方法了，把DAWN删除就没问题了，不知道这个有什知用，编译时是必选的

**Comment by xuexijiaoben** [comment]
谢谢啦，1385这个我这儿也一直有，留言学习一下，
