### ISSUE TITLE
云编译linux fail to build

### ISSUE THREAD

**Issue by xiaouex** [coolsnowwolf/lede#12238]
### 详细叙述

今天同步代码编译新固件出现的问题，看了下error的地方好像是跟led驱动有关的？不太懂，求指教

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rax3000m

### 详细日志

make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
make[1]: Entering directory '/workdir/openwrt'
make[2]: Entering directory '/workdir/openwrt'
make[3]: Entering directory '/workdir/openwrt/target/linux'
make[4]: Entering directory '/workdir/openwrt/target/linux/mediatek'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/localversion
/workdir/openwrt/scripts/kconfig.pl  + /workdir/openwrt/target/linux/generic/config-6.1 /workdir/openwrt/target/linux/mediatek/filogic/config-6.1 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /workdir/openwrt/.config >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target
/workdir/openwrt/scripts/package-metadata.pl kconfig /workdir/openwrt/tmp/.packageinfo /workdir/openwrt/.config 6.1 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.override
/workdir/openwrt/scripts/kconfig.pl 'm+' '+' /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.target /dev/null /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.override > /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set
mv /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.old
grep -v INITRAMFS /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.old > /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set
echo "# CONFIG_INITRAMFS_PRESERVE_MTIME is not set" >> /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set
rm -rf /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/modules
cmp -s /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.prev || { cp /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config; cp /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.prev; }
export MAKEFLAGS= ; [ -d /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/user_headers ] || make -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Jun 15 15:22:45 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=6.1.92 CC="aarch64-openwrt-linux-musl-gcc"  INSTALL_HDR_PATH=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/user_headers headers_install
grep '=[ym]' /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.config.set | LC_ALL=C sort | /workdir/openwrt/staging_dir/host/bin/mkhash md5 > /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.vermagic
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.configured
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/vmlinux /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/System.map
make -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Jun 15 15:22:45 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=6.1.92 CC="aarch64-openwrt-linux-musl-gcc" olddefconfig
make[5]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92'
#
# No change to .config
#
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92'
make -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Jun 15 15:22:45 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=6.1.92 CC="aarch64-openwrt-linux-musl-gcc" Image dtbs modules
make[5]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92'
  CALL    scripts/checksyscalls.sh
  CC      drivers/net/phy/mediatek-ge-soc.o
drivers/net/phy/mediatek-ge-soc.c:1187:57: warning: 'enum led_brightness' declared inside parameter list will not be visible outside of this definition or declaration
 1187 |                                          u8 index, enum led_brightness value)
      |                                                         ^~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1187:72: error: parameter 3 ('value') has incomplete type
 1187 |                                          u8 index, enum led_brightness value)
      |                                                    ~~~~~~~~~~~~~~~~~~~~^~~~~
drivers/net/phy/mediatek-ge-soc.c:1186:12: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 1186 | static int mt798x_phy_led_brightness_set(struct phy_device *phydev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c: In function 'mt798x_phy_led_brightness_set':
drivers/net/phy/mediatek-ge-soc.c:1195:66: error: 'LED_OFF' undeclared (first use in this function)
 1195 |         return mt798x_phy_hw_led_on_set(phydev, index, (value != LED_OFF));
      |                                                                  ^~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1195:66: note: each undeclared identifier is reported only once for each function it appears in
In file included from ./include/linux/bits.h:6,
                 from ./include/linux/bitops.h:6,
                 from ./include/linux/bitmap.h:8,
                 from drivers/net/phy/mediatek-ge-soc.c:3:
drivers/net/phy/mediatek-ge-soc.c: At top level:
drivers/net/phy/mediatek-ge-soc.c:1198:54: error: 'TRIGGER_NETDEV_FULL_DUPLEX' undeclared here (not in a function)
 1198 | static const unsigned long supported_triggers = (BIT(TRIGGER_NETDEV_FULL_DUPLEX) |
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1199:54: error: 'TRIGGER_NETDEV_HALF_DUPLEX' undeclared here (not in a function)
 1199 |                                                  BIT(TRIGGER_NETDEV_HALF_DUPLEX) |
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1200:54: error: 'TRIGGER_NETDEV_LINK' undeclared here (not in a function)
 1200 |                                                  BIT(TRIGGER_NETDEV_LINK)        |
      |                                                      ^~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1201:54: error: 'TRIGGER_NETDEV_LINK_10' undeclared here (not in a function)
 1201 |                                                  BIT(TRIGGER_NETDEV_LINK_10)     |
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1202:54: error: 'TRIGGER_NETDEV_LINK_100' undeclared here (not in a function)
 1202 |                                                  BIT(TRIGGER_NETDEV_LINK_100)    |
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1203:54: error: 'TRIGGER_NETDEV_LINK_1000' undeclared here (not in a function)
 1203 |                                                  BIT(TRIGGER_NETDEV_LINK_1000)   |
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1204:54: error: 'TRIGGER_NETDEV_RX' undeclared here (not in a function)
 1204 |                                                  BIT(TRIGGER_NETDEV_RX)          |
      |                                                      ^~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1205:54: error: 'TRIGGER_NETDEV_TX' undeclared here (not in a function)
 1205 |                                                  BIT(TRIGGER_NETDEV_TX));
      |                                                      ^~~~~~~~~~~~~~~~~
./include/vdso/bits.h:7:44: note: in definition of macro 'BIT'
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                            ^~
drivers/net/phy/mediatek-ge-soc.c:1495:18: error: 'struct phy_driver' has no member named 'led_blink_set'
 1495 |                 .led_blink_set  = mt798x_phy_led_blink_set,
      |                  ^~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1495:35: error: initialization of 'int (*)(struct phy_device *, struct ethtool_modinfo *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int *, long unsigned int *)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int *, long unsigned int *)'} [-Werror=incompatible-pointer-types]
 1495 |                 .led_blink_set  = mt798x_phy_led_blink_set,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1495:35: note: (near initialization for 'mtk_socphy_driver[0].module_info')
drivers/net/phy/mediatek-ge-soc.c:1496:18: error: 'struct phy_driver' has no member named 'led_brightness_set'
 1496 |                 .led_brightness_set = mt798x_phy_led_brightness_set,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1497:18: error: 'struct phy_driver' has no member named 'led_hw_is_supported'
 1497 |                 .led_hw_is_supported = mt798x_phy_led_hw_is_supported,
      |                  ^~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1497:40: error: initialization of 'int (*)(struct phy_device *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int)'} [-Werror=incompatible-pointer-types]
 1497 |                 .led_hw_is_supported = mt798x_phy_led_hw_is_supported,
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1497:40: note: (near initialization for 'mtk_socphy_driver[0].cable_test_start')
drivers/net/phy/mediatek-ge-soc.c:1498:18: error: 'struct phy_driver' has no member named 'led_hw_control_set'
 1498 |                 .led_hw_control_set = mt798x_phy_led_hw_control_set,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1498:39: error: initialization of 'int (*)(struct phy_device *, const struct phy_tdr_config *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int)'} [-Werror=incompatible-pointer-types]
 1498 |                 .led_hw_control_set = mt798x_phy_led_hw_control_set,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1498:39: note: (near initialization for 'mtk_socphy_driver[0].cable_test_tdr_start')
drivers/net/phy/mediatek-ge-soc.c:1499:18: error: 'struct phy_driver' has no member named 'led_hw_control_get'
 1499 |                 .led_hw_control_get = mt798x_phy_led_hw_control_get,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1499:39: error: initialization of 'int (*)(struct phy_device *, bool *)' {aka 'int (*)(struct phy_device *, _Bool *)'} from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int *)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int *)'} [-Werror=incompatible-pointer-types]
 1499 |                 .led_hw_control_get = mt798x_phy_led_hw_control_get,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1499:39: note: (near initialization for 'mtk_socphy_driver[0].cable_test_get_status')
drivers/net/phy/mediatek-ge-soc.c:1512:18: error: 'struct phy_driver' has no member named 'led_blink_set'
 1512 |                 .led_blink_set  = mt798x_phy_led_blink_set,
      |                  ^~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1512:35: error: initialization of 'int (*)(struct phy_device *, struct ethtool_modinfo *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int *, long unsigned int *)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int *, long unsigned int *)'} [-Werror=incompatible-pointer-types]
 1512 |                 .led_blink_set  = mt798x_phy_led_blink_set,
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1512:35: note: (near initialization for 'mtk_socphy_driver[1].module_info')
drivers/net/phy/mediatek-ge-soc.c:1513:18: error: 'struct phy_driver' has no member named 'led_brightness_set'
 1513 |                 .led_brightness_set = mt798x_phy_led_brightness_set,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1514:18: error: 'struct phy_driver' has no member named 'led_hw_is_supported'
 1514 |                 .led_hw_is_supported = mt798x_phy_led_hw_is_supported,
      |                  ^~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1514:40: error: initialization of 'int (*)(struct phy_device *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int)'} [-Werror=incompatible-pointer-types]
 1514 |                 .led_hw_is_supported = mt798x_phy_led_hw_is_supported,
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1514:40: note: (near initialization for 'mtk_socphy_driver[1].cable_test_start')
drivers/net/phy/mediatek-ge-soc.c:1515:18: error: 'struct phy_driver' has no member named 'led_hw_control_set'
 1515 |                 .led_hw_control_set = mt798x_phy_led_hw_control_set,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1515:39: error: initialization of 'int (*)(struct phy_device *, const struct phy_tdr_config *)' from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int)'} [-Werror=incompatible-pointer-types]
 1515 |                 .led_hw_control_set = mt798x_phy_led_hw_control_set,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1515:39: note: (near initialization for 'mtk_socphy_driver[1].cable_test_tdr_start')
drivers/net/phy/mediatek-ge-soc.c:1516:18: error: 'struct phy_driver' has no member named 'led_hw_control_get'
 1516 |                 .led_hw_control_get = mt798x_phy_led_hw_control_get,
      |                  ^~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1516:39: error: initialization of 'int (*)(struct phy_device *, bool *)' {aka 'int (*)(struct phy_device *, _Bool *)'} from incompatible pointer type 'int (*)(struct phy_device *, u8,  long unsigned int *)' {aka 'int (*)(struct phy_device *, unsigned char,  long unsigned int *)'} [-Werror=incompatible-pointer-types]
 1516 |                 .led_hw_control_get = mt798x_phy_led_hw_control_get,
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/phy/mediatek-ge-soc.c:1516:39: note: (near initialization for 'mtk_socphy_driver[1].cable_test_get_status')
drivers/net/phy/mediatek-ge-soc.c: In function 'mt798x_phy_led_brightness_set':
drivers/net/phy/mediatek-ge-soc.c:1196:1: error: control reaches end of non-void function [-Werror=return-type]
 1196 | }
      | ^
cc1: some warnings being treated as errors
make[9]: *** [scripts/Makefile.build:250: drivers/net/phy/mediatek-ge-soc.o] Error 1
make[8]: *** [scripts/Makefile.build:503: drivers/net/phy] Error 2
make[7]: *** [scripts/Makefile.build:503: drivers/net] Error 2
make[6]: *** [scripts/Makefile.build:503: drivers] Error 2
make[5]: *** [Makefile:2010: .] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92'
make[4]: *** [Makefile:21: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.modules] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/mediatek'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#2.08#0.71#2.74
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by xiaouex** [comment]
推测与13号的commit有关
![1](https://github.com/coolsnowwolf/lede/assets/36121363/b813c602-3053-4615-a0b4-0b7700cb6b6c)

**Comment by aiamadeus** [comment]
现在呢，这仓库年久失修真 TM 难同步

**Comment by xiaouex** [comment]
> 现在呢，这仓库年久失修真 TM 难同步

解决了，编译成功
