### ISSUE TITLE
Openwrt加入Docker启动时报错OverlayFs xxxx not supported as upper

### ISSUE THREAD

**Issue by wisebuilder** [coolsnowwolf/lede#12230]
### 详细叙述

luci加入docker之后，启动报错：
[   21.801699] br-lan: port 1(eth1) entered blocking state
[   21.802512] br-lan: port 1(eth1) entered forwarding state
[   22.797610] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   32.261652] overlayfs: filesystem on '/opt/check-overlayfs-support2618463341/upper' not supported as upperdir
[   33.241805] traps: check[4982] general protection fault ip:8049007 sp:ffeb4b20 error:402 in check[8049000+1000]

然后docker无法使用

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

pve虚拟机

### 详细日志

无

**Comment by yanxin152133** [comment]
![image](https://github.com/coolsnowwolf/lede/assets/43341537/ff991f54-fe59-4760-9d19-54e378c96d7b)

https://github.com/coolsnowwolf/lede/issues/8698
