### ISSUE TITLE
mt7981 turboacc 硬件加速开启失败

### ISSUE THREAD

**Issue by xiaouex** [coolsnowwolf/lede#12244]
### 详细叙述

机型rax3000m，开关两个流量分载选项，硬件加速选项消失；在不关闭流量分载的情况下打开无线硬件加速 保存、应用配置，路由器重启后硬件加速选项又被关闭了，具体表现看小视频

https://github.com/coolsnowwolf/lede/assets/36121363/190067c7-3aed-4a4a-bebf-bbee7080c54c

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rax3000m

### 详细日志

无

**Comment by WYC-2020** [comment]
这玩意都不是l这边的固件
