### ISSUE TITLE
filogic 6.1编译报错

### ISSUE THREAD

**Issue by mirthlesslk** [coolsnowwolf/lede#12240]
### 详细叙述

发哥6.1内核编译报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

6086

### 详细日志

make[9]: *** [scripts/Makefile.build:250: drivers/net/phy/mediatek-ge-soc.o] Error 1
make[8]: *** [scripts/Makefile.build:503: drivers/net/phy] Error 2
make[7]: *** [scripts/Makefile.build:503: drivers/net] Error 2
make[6]: *** [scripts/Makefile.build:503: drivers] Error 2
make[5]: *** [Makefile:2010: .] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92'
make[4]: Leaving directory '/workdir/openwrt/target/linux/mediatek'
make[4]: *** [Makefile:21: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.1.92/.modules] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
make[3]: *** [Makefile:11: compile] Error 2
time: target/linux/compile#2.07#0.75#2.77
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by xiaouex** [comment]
试试新的commit，我刚反馈这款芯片最新代码编译出问题，刚才已经有新的commit了
