### ISSUE TITLE
防火墙端口转发udp失效

### ISSUE THREAD

**Issue by ragingbulld** [coolsnowwolf/lede#12255]
### 详细叙述

开启shortcut-fe或者高性能全锥型nat均会导致防火墙端口转发udp失效

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

当我开启高性能全锥型nat的情况下，防火墙的udp的端口转发会失效
同样，当我开启shortcut-fe ecm的情况下，防火墙的udp的端口转发也会失效
tcp正常转发

**Comment by coolsnowwolf** [comment]
已修复

**Comment by ragingbulld** [comment]
> 已修复

拉取了最新的源码，好像还是会失效
