### ISSUE TITLE
tools 下的程序都升级一下版本

### ISSUE THREAD

**Issue by joyplayer** [coolsnowwolf/lede#12250]
### 详细叙述

tools 下的程序都升级一下版本

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

tools 下的程序都升级一下版本，一些自定义的插件无法编译，tools 离得一些工具版本过低

**Comment by aiamadeus** [comment]
不升，天天花时间编译工具链烦死了

**Comment by caixin1218** [comment]
> 不升，天天花时间编译工具链烦死了

下个版本一出不升问题就很多。
