### ISSUE TITLE
开启shortcut-fe或者高性能全锥型nat均会导致防火墙端口转发udp失效

### ISSUE THREAD

**Issue by ragingbulld** [coolsnowwolf/lede#12254]
### 详细叙述

开启shortcut-fe或者高性能全锥型nat均会导致防火墙端口转发udp失效

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

开启shortcut-fe或者高性能全锥型nat均会导致防火墙端口转发udp失效

**Comment by aiamadeus** [comment]
那你试试换 flow offload 呢
