### ISSUE TITLE
WARNING: Not overriding core package 'csstidy'; use -f to force

### ISSUE THREAD

**Issue by caixin1218** [coolsnowwolf/lede#12260]
### 详细叙述

WARNING: Not overriding core package 'csstidy'; use -f to force

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

WARNING: Not overriding core package 'csstidy'; use -f to force

**Comment by sijyun** [comment]
./scripts/feeds install -af
試試.
