### ISSUE TITLE
softetherVPN系统占用异常

### ISSUE THREAD

**Issue by psonys** [coolsnowwolf/lede#12274]
### 详细叙述

![1](https://github.com/coolsnowwolf/lede/assets/56349369/b0d41e4f-caea-412c-9003-ddf3b7750a10)
![2](https://github.com/coolsnowwolf/lede/assets/56349369/4c06ede7-2dc4-43d8-ae0a-4bed4d3b5395)
自从softetherVPN更新后，不定时的softether会导致CPU占用异常，远程连接失效。
系统使用6.6内核。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

畅网1235U

### 详细日志

编译正常

**Comment by DragonOneY** [comment]
这是softethervpn的问题，回滚到5.01.9674-1就好了。
cd lede
git checkout master
git pull
git checkout -b rollback-softethervpn-5.01.9674-1
cd feeds/packages/net/softethervpn5
git checkout 7d89c09430930e3bf9b487333f0a18dd117f46af

**Comment by psonys** [comment]
Debian:~/lede/feeds/packages/net/softethervpn5$ git checkout 7d89c09430930e3bf9b487333f0a18dd117f46af
fatal: 引用不是一个树：7d89c09430930e3bf9b487333f0a18dd117f46af

**Comment by 625045508** [comment]
这鬼问题，煎熬我好几天，最后也是降版本编译好了
