### ISSUE TITLE
6.1内核x86异常重启

### ISSUE THREAD

**Issue by Jack9708** [coolsnowwolf/lede#12285]
### 详细叙述

之前用6.1.85内核稳定运行了两个月，最近编译6.1.94内核已经遇到三次异常重启了，重启时间没有规律，隔几天就会重启。
x86物理机安装（4415U），没有使用虚拟机，两次编译的软件包是一致的，且升级时没有保留配置。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

4415U

### 详细日志

未抓到重启前的日志

**Comment by lirg-111** [comment]
是不是用了Turbo ACC？

**Comment by Turing-China** [comment]
![微信截图_20240702084922](https://github.com/coolsnowwolf/lede/assets/107291340/4a964ac8-93ff-4532-8ef5-6658d4209cb0)
同样的问题 未编译Turbo ACC  编译了op-vm-tools  使用ESXI8.0虚拟机安装
