### ISSUE TITLE
ipq40xx编译5.10.220内核出错

### ISSUE THREAD

**Issue by venpong** [coolsnowwolf/lede#12288]
### 详细叙述

ACRH17用Github Action云编译固件报错,日志如图
![Snipaste_2024-07-01_10-37-00](https://github.com/coolsnowwolf/lede/assets/14030911/edf8b6cd-5771-4bee-b2dc-9d96cfabbd76)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

ACRH17

### 详细日志

`
make[3]: Entering directory '/workdir/openwrt/feeds/packages/libs/udns'
mkdir -p /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/udns-0.4/.pkgdir/libudns/. /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/'
touch /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp/.libudns_installed
echo "libudns" >> /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/udns.default.install
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/libs/udns'
time: package/feeds/packages/udns/compile#0.12#0.07#0.17
make[3]: Entering directory '/workdir/openwrt/package/kernel/cryptodev-linux'
rm -f /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/.built
touch /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/.built_check
make -C /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi=target-arm_cortex-a7+neon-vfpv4_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Jun 30 20:48:30 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/symvers/gpio-button-hotplug.symvers" KERNELRELEASE=5.10.220 KERNEL_DIR="/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220"
make[4]: Entering directory '/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13'
make -C /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220 M=/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13 ARCH=arm CROSS_COMPILE=arm-openwrt-linux-muslgnueabi- modules
make[5]: Entering directory '/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220'
  CC [M]  /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/ioctl.o
/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/ioctl.c: In function 'cryptodev_ioctl':
/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/ioctl.c:937:25: error: implicit declaration of function 'ksys_close'; did you mean 'sys_close'? [-Werror=implicit-function-declaration]
  937 |                         ksys_close(fd);
      |                         ^~~~~~~~~~
      |                         sys_close
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:286: /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/ioctl.o] Error 1
make[5]: *** [Makefile:1832: /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13] Error 2
make[4]: *** [Makefile:30: build] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220'
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13'
make[3]: *** [Makefile:61: /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/cryptodev-linux-cryptodev-linux-1.13/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/package/kernel/cryptodev-linux'
time: package/kernel/cryptodev-linux/compile#1.00#0.19#1.17
    ERROR: package/kernel/cryptodev-linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/cryptodev-linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
`

**Comment by hzjnet** [comment]
你这是重复提交了，cryptodev-linux编译问题，见：https://github.com/coolsnowwolf/lede/issues/12283

**Comment by venpong** [comment]
> 你这是重复提交了，cryptodev-linux编译问题，见：#12283

好的，那我关掉
