### ISSUE TITLE
SSR Plus使用SS客户端，但Socks5使用的是ssr-local导致Socks5无效

### ISSUE THREAD

**Issue by kedzlcy** [coolsnowwolf/lede#1228]
节点类型选择Shadowsocks New Version，加密方式选择 acs-256-gcm。 

{
    "server": "xx.xx.xx.xx",
    "server_port": 10086,
    "local_address": "0.0.0.0",
    "local_port": 1234,
    "password": "xx",
    "timeout": 60,
    "method": "aes-256-gcm",
    "reuse_port": true,
    "fast_open": true
}

在路由器中ps显示下面进程。

/usr/bin/ss-redir -c /var/etc/shadowsocksr.json -f /var/run/ssr-retcp_1.pid
/usr/bin/ss-redir -c /var/etc/shadowsocksr.json -f /var/run/ssr-retcp_2.pid
/usr/bin/ssr-local -c /var/etc/shadowsocksr_s.json -u -l 1080 -b 0.0.0.0 -f /var/run/ssr-local.pid

杀死ssr-local 后启动下面脚本后SOCKS5服务正常运行。
/usr/bin/ss-local -c /var/etc/shadowsocksr.json -u -l 1080 -b 0.0.0.0 -f /var/run/ss-local.pid

**Comment by coolsnowwolf** [comment]
嗯，这里确实没考虑，后面修复吧

**Comment by kedzlcy** [comment]
SOCKS5服务在SSR PLUS客户端属于禁用的状态下，仍然会开机自启动。
在kill掉ssr-local的情况下，修改SSR PLUS里的客户端，服务器节点，访问控制，高级设置，服务端都会重新拉起ssr-local进程。

SOCKS5代理会出现无法选择服务器，但服务属于启动状态的情况。

希望在SSR Plus的服务端加入SS Server的选项，支持 acs-256-gcm。

**Comment by coolsnowwolf** [comment]
SOCKS5服务在SSR PLUS客户端属于禁用的状态下，仍然会开机自启动

这个是有意这样设计的，因为有些人不需要透明代理啊，就需要 socks5

**Comment by 505575853** [comment]
https://github.com/505575853/lede/tree/R9/package/lean/luci-app-ssr-plus
