### ISSUE TITLE
关于网络唤醒一个小问题

### ISSUE THREAD

**Issue by zhanglinku** [coolsnowwolf/lede#1229]
网络唤醒界面现存的地址都是目前开机的机器。 
然而需要唤醒的机器MAC地址也都无法显示， 需要手工输入mac地址。
能显示的地址就没什么用了。 
能否记忆需要唤醒机器的MAC地址呢？

**Comment by lxwq** [comment]
![image](https://user-images.githubusercontent.com/51162826/65472848-074efd80-dea8-11e9-9647-becf27f0d8d3.png)

**Comment by lxwq** [comment]
为毛我的里面什么都没有？还没测试手动输入MAC能不能唤醒，但就算能唤醒，一个一个输入也太麻烦了啊，
以前都是正常的，最近更新到4.19内核后问题有很多，
