### ISSUE TITLE
默认缺少shairport软件包

### ISSUE THREAD

**Issue by honnbin** [coolsnowwolf/lede#123]
大屌，最新的源码选了了luci shairport，但是没有shairport包，需要手动添加进去

**Comment by timiil** [comment]
有啊，不是在Sound里边吗？ 不过有3个，不知道选那个了

**Comment by honnbin** [comment]
luci shairport默认支持的是老版的shairport，几年前就没有更新了，sound里面是新的shairport sync，luci不支持

**Comment by timiil** [comment]
确实是honnbin说的这样，我安装了sound里面新的ssl版本，honnbin兄是怎么把对应合适的luci补上的？ 请赐教！

**Comment by honnbin** [comment]
下载旧版的shairport包就可以，后来还是换了shairplay，反正都一个功能

不过还是希望能有新版的luci
