### ISSUE TITLE
最新代码编译报错

### ISSUE THREAD

**Issue by liuyanantj** [coolsnowwolf/lede#12302]
### 详细叙述

7.3的代码  编译报错  日志如下 请帮忙看看

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

Dist build-manifest-1.78.0-x86_64-unknown-linux-gnu
	finished in 0.109 seconds
WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes made to the bootstrap configurations.
NOTE: to silence this warning, add `change-id = 121754` at the top of `config.toml`
NOTE: this message was printed twice to make it more likely to be seen
Build completed successfully in 0:06:22
touch /home/tc/lede/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/.built
( cd /home/tc/lede/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/build/dist ; for targz in *.tar.gz; do /home/tc/lede/staging_dir/host/bin/libdeflate-gzip -dc "$targz" | tar -xf - ; done ; find . -mindepth 2 -maxdepth 2 -type f -name install.sh -execdir bash '{}' --prefix=/home/tc/lede/staging_dir/target-x86_64_musl/host --disable-ldconfig \; ; )
install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rust-std-x86_64-unknown-linux-gnu'

    rust std installed.

install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'cargo'

    cargo installed.

install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rustc'

    rustc installed.

install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'build-manifest'

    build manifest installed.

install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rust-src'

    rust src installed.

install: creating uninstall script at /home/tc/lede/staging_dir/target-x86_64_musl/host/lib/rustlib/uninstall.sh
install: installing component 'rust-std-x86_64-unknown-linux-musl'

    rust std installed.

mkdir -p /home/tc/lede/staging_dir/hostpkg/stamp
touch /home/tc/lede/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/.built
touch /home/tc/lede/staging_dir/hostpkg/stamp/.rust_installed
make[3]: Leaving directory '/home/tc/lede/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#2811.89#737.71#413.67
make[2]: Leaving directory '/home/tc/lede'
make[1]: *** [package/Makefile:110: /home/tc/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/tc/lede'
make: *** [/home/tc/lede/include/toplevel.mk:231：world] 错误 2

**Comment by xibaolai** [comment]
一样的错误提示，请教怎么解决了？
