### ISSUE TITLE
京东亚瑟云ax1800 pro编译好后无法通过uboot安装

### ISSUE THREAD

**Issue by jeasonliang** [coolsnowwolf/lede#12303]
### 详细叙述

京东亚瑟云ax1800pro 128G 已经开启了ssh 通过面包多买了coolsonowwolf老大的Uboot,成功刷入了,网上试验了下istoreos的系统,,可以使用,自行利用github Actions编译也成功了,但是在uboot上传编译好的lede固件一直亮红灯,无法启用, 有没有类似故障的朋友?  .config的配置文件如下:(篇幅有限,我只贴架构 等重要的)
#
# Automatically generated file; DO NOT EDIT.
# OpenWrt Configuration
#
CONFIG_MODULES=y
CONFIG_HAVE_DOT_CONFIG=y
CONFIG_HOST_OS_LINUX=y
CONFIG_TARGET_qualcommax=y
CONFIG_TARGET_qualcommax_ipq60xx=y
CONFIG_TARGET_qualcommax_ipq60xx_DEVICE_jdcloud_re-ss-01=y
CONFIG_HAS_SUBTARGETS=y
CONFIG_HAS_DEVICES=y
CONFIG_TARGET_BOARD="qualcommax"
CONFIG_TARGET_SUBTARGET="ipq60xx"
CONFIG_TARGET_PROFILE="DEVICE_jdcloud_re-ss-01"
CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"
CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53"
CONFIG_CPU_TYPE="cortex-a53"
CONFIG_LINUX_6_1=y
CONFIG_DEFAULT_ath11k-firmware-ipq6018=y
CONFIG_DEFAULT_autocore-arm=y
CONFIG_DEFAULT_base-files=y
CONFIG_DEFAULT_block-mount=y
CONFIG_DEFAULT_busybox=y
CONFIG_DEFAULT_ca-bundle=y
CONFIG_DEFAULT_ca-certificates=y
CONFIG_DEFAULT_coremark=y
CONFIG_DEFAULT_curl=y
CONFIG_DEFAULT_ddns-scripts_aliyun=y
CONFIG_DEFAULT_ddns-scripts_dnspod=y
CONFIG_DEFAULT_default-settings=y
CONFIG_DEFAULT_dnsmasq-full=y
CONFIG_DEFAULT_dropbear=y
CONFIG_DEFAULT_e2fsprogs=y
CONFIG_DEFAULT_firewall=y
CONFIG_DEFAULT_fstools=y
CONFIG_DEFAULT_ip-full=y
CONFIG_DEFAULT_ipq-wifi-jdcloud_ax1800pro=y
CONFIG_DEFAULT_ipset=y
CONFIG_DEFAULT_iptables=y
CONFIG_DEFAULT_iptables-mod-extra=y
CONFIG_DEFAULT_iptables-mod-tproxy=y
CONFIG_DEFAULT_iwinfo=y
CONFIG_DEFAULT_kmod-ath11k-ahb=y
CONFIG_DEFAULT_kmod-fs-ext4=y
CONFIG_DEFAULT_kmod-gpio-button-hotplug=y
CONFIG_DEFAULT_kmod-ipt-raw=y
CONFIG_DEFAULT_kmod-leds-gpio=y
CONFIG_DEFAULT_kmod-nf-nathelper=y
CONFIG_DEFAULT_kmod-nf-nathelper-extra=y
CONFIG_DEFAULT_kmod-qca-nss-dp=y
CONFIG_DEFAULT_kmod-qca-nss-drv=y
CONFIG_DEFAULT_kmod-qca-nss-drv-bridge-mgr=y
CONFIG_DEFAULT_kmod-qca-nss-drv-pppoe=y
CONFIG_DEFAULT_kmod-qca-nss-drv-vlan=y
CONFIG_DEFAULT_kmod-qca-nss-ecm=y
CONFIG_DEFAULT_kmod-qca-ssdk=y
CONFIG_DEFAULT_kmod-tun=y
CONFIG_DEFAULT_kmod-usb-dwc3=y
CONFIG_DEFAULT_kmod-usb-dwc3-qcom=y
CONFIG_DEFAULT_kmod-usb3=y
CONFIG_DEFAULT_libc=y
CONFIG_DEFAULT_libgcc=y
CONFIG_DEFAULT_libustream-openssl=y
CONFIG_DEFAULT_logd=y
CONFIG_DEFAULT_losetup=y
CONFIG_DEFAULT_luci=y
CONFIG_DEFAULT_luci-app-accesscontrol=y
CONFIG_DEFAULT_luci-app-arpbind=y
CONFIG_DEFAULT_luci-app-autoreboot=y
CONFIG_DEFAULT_luci-app-ddns=y
CONFIG_DEFAULT_luci-app-filetransfer=y
CONFIG_DEFAULT_luci-app-nlbwmon=y
CONFIG_DEFAULT_luci-app-ssr-plus=y
CONFIG_DEFAULT_luci-app-turboacc=y
CONFIG_DEFAULT_luci-app-upnp=y
CONFIG_DEFAULT_luci-app-vlmcsd=y
CONFIG_DEFAULT_luci-app-vsftpd=y
CONFIG_DEFAULT_luci-app-wol=y
CONFIG_DEFAULT_mtd=y
CONFIG_DEFAULT_netifd=y
CONFIG_DEFAULT_nss-firmware-ipq6018=y
CONFIG_DEFAULT_opkg=y
CONFIG_DEFAULT_ppp=y
CONFIG_DEFAULT_ppp-mod-pppoe=y
CONFIG_DEFAULT_procd=y
CONFIG_DEFAULT_procd-ujail=y
CONFIG_DEFAULT_uboot-envtools=y
CONFIG_DEFAULT_uci=y
CONFIG_DEFAULT_uclient-fetch=y
CONFIG_DEFAULT_urandom-seed=y
CONFIG_DEFAULT_urngd=y
CONFIG_DEFAULT_wpad-openssl=y
CONFIG_HAS_FPU=y
CONFIG_AUDIO_SUPPORT=y
CONFIG_GPIO_SUPPORT=y
CONFIG_PCI_SUPPORT=y
CONFIG_PCIE_SUPPORT=y
CONFIG_USB_SUPPORT=y
CONFIG_RTC_SUPPORT=y
CONFIG_USES_DEVICETREE=y
CONFIG_USES_INITRAMFS=y
CONFIG_USES_SQUASHFS=y
CONFIG_EMMC_SUPPORT=y
CONFIG_NAND_SUPPORT=y
CONFIG_ARCH_64BIT=y
CONFIG_VIRTIO_SUPPORT=y
CONFIG_aarch64=y
CONFIG_ARCH="aarch64"

#
# Target Images
#
CONFIG_TARGET_ROOTFS_INITRAMFS=y
CONFIG_TARGET_INITRAMFS_COMPRESSION_ZSTD=y
CONFIG_EXTERNAL_CPIO=""
#
# Root filesystem images
#
# CONFIG_TARGET_ROOTFS_EXT4FS is not set
CONFIG_TARGET_ROOTFS_SQUASHFS=y
CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=1024
CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
CONFIG_TARGET_UBIFS_JOURNAL_SIZE=""

#
# Image Options
#
# CONFIG_TARGET_ROOTFS_PERSIST_VAR is not set
# end of Target Images

# CONFIG_EXPERIMENTAL is not set

#
# Global build settings
#
CONFIG_JSON_OVERVIEW_IMAGE_INFO=y
# CONFIG_ALL_NONSHARED is not set
# CONFIG_ALL_KMODS is not set
# CONFIG_ALL is not set
# CONFIG_BUILDBOT is not set
CONFIG_SIGNED_PACKAGES=y
CONFIG_SIGNATURE_CHECK=y
CONFIG_DOWNLOAD_CHECK_CERTIFICATE=y

#
# General build options
#
# CONFIG_DISPLAY_SUPPORT is not set
# CONFIG_BUILD_PATENTED is not set
# CONFIG_BUILD_NLS is not set
CONFIG_SHADOW_PASSWORDS=y
# CONFIG_CLEAN_IPKG is not set
# CONFIG_IPK_FILES_CHECKSUMS is not set
# CONFIG_INCLUDE_CONFIG is not set
# CONFIG_REPRODUCIBLE_DEBUG_INFO is not set
# CONFIG_COLLECT_KERNEL_DEBUG is not set

#
# Kernel build options
#
CONFIG_KERNEL_BUILD_USER=""
CONFIG_KERNEL_BUILD_DOMAIN=""
CONFIG_KERNEL_PRINTK=y
CONFIG_KERNEL_SWAP=y
# CONFIG_KERNEL_PROC_STRIPPED is not set
CONFIG_KERNEL_DEBUG_FS=y
# CONFIG_KERNEL_ARM_PMU is not set
# CONFIG_KERNEL_PERF_EVENTS is not set
# CONFIG_KERNEL_PROFILING is not set
# CONFIG_KERNEL_UBSAN is not set
# CONFIG_KERNEL_KASAN is not set
# CONFIG_KERNEL_KCOV is not set
# CONFIG_KERNEL_TASKSTATS is not set
CONFIG_KERNEL_KALLSYMS=y
# CONFIG_KERNEL_FTRACE is not set
CONFIG_KERNEL_DEBUG_KERNEL=y
CONFIG_KERNEL_DEBUG_INFO=y
CONFIG_KERNEL_DEBUG_INFO_REDUCED=y
CONFIG_KERNEL_FRAME_WARN=2048
# CONFIG_KERNEL_DEBUG_VIRTUAL is not set
# CONFIG_KERNEL_DYNAMIC_DEBUG is not set
# CONFIG_KERNEL_KPROBES is not set
# CONFIG_KERNEL_BPF_EVENTS is not set
CONFIG_KERNEL_AIO=y
CONFIG_KERNEL_IO_URING=y
CONFIG_KERNEL_FHANDLE=y
CONFIG_KERNEL_FANOTIFY=y
# CONFIG_KERNEL_BLK_DEV_BSG is not set
# CONFIG_KERNEL_HUGETLBFS is not set
# CONFIG_KERNEL_HUGETLB_PAGE is not set
CONFIG_KERNEL_MAGIC_SYSRQ=y
# CONFIG_KERNEL_DEBUG_PINCTRL is not set
# CONFIG_KERNEL_DEBUG_GPIO is not set
CONFIG_KERNEL_COREDUMP=y
CONFIG_KERNEL_ELF_CORE=y
# CONFIG_KERNEL_PROVE_LOCKING is not set
# CONFIG_KERNEL_SOFTLOCKUP_DETECTOR is not set
# CONFIG_KERNEL_DETECT_HUNG_TASK is not set
# CONFIG_KERNEL_WQ_WATCHDOG is not set
# CONFIG_KERNEL_DEBUG_ATOMIC_SLEEP is not set
# CONFIG_KERNEL_DEBUG_VM is not set
CONFIG_KERNEL_PRINTK_TIME=y
# CONFIG_KERNEL_SLABINFO is not set
# CONFIG_KERNEL_PROC_PAGE_MONITOR is not set
# CONFIG_KERNEL_KEXEC is not set
# CONFIG_USE_RFKILL is not set
# CONFIG_USE_SPARSE is not set
# CONFIG_KERNEL_DEVTMPFS is not set
CONFIG_KERNEL_KEYS=y
# CONFIG_KERNEL_PERSISTENT_KEYRINGS is not set
# CONFIG_KERNEL_KEYS_REQUEST_CACHE is not set
# CONFIG_KERNEL_BIG_KEYS is not set
CONFIG_KERNEL_CGROUPS=y
# CONFIG_KERNEL_CGROUP_DEBUG is not set
CONFIG_KERNEL_FREEZER=y
# CONFIG_KERNEL_CGROUP_FREEZER is not set
# CONFIG_KERNEL_CGROUP_DEVICE is not set
# CONFIG_KERNEL_CGROUP_HUGETLB is not set
CONFIG_KERNEL_CGROUP_PIDS=y
CONFIG_KERNEL_CGROUP_RDMA=y
CONFIG_KERNEL_CGROUP_BPF=y
CONFIG_KERNEL_CPUSETS=y
# CONFIG_KERNEL_PROC_PID_CPUSET is not set
CONFIG_KERNEL_CGROUP_CPUACCT=y
CONFIG_KERNEL_RESOURCE_COUNTERS=y
CONFIG_KERNEL_MM_OWNER=y
CONFIG_KERNEL_MEMCG=y
CONFIG_KERNEL_MEMCG_SWAP=y
# CONFIG_KERNEL_MEMCG_SWAP_ENABLED is not set
CONFIG_KERNEL_MEMCG_KMEM=y
# CONFIG_KERNEL_CGROUP_PERF is not set
CONFIG_KERNEL_CGROUP_SCHED=y
CONFIG_KERNEL_FAIR_GROUP_SCHED=y
CONFIG_KERNEL_CFS_BANDWIDTH=y
CONFIG_KERNEL_RT_GROUP_SCHED=y
CONFIG_KERNEL_BLK_CGROUP=y
# CONFIG_KERNEL_CFQ_GROUP_IOSCHED is not set
CONFIG_KERNEL_BLK_DEV_THROTTLING=y
# CONFIG_KERNEL_BLK_DEV_THROTTLING_LOW is not set
# CONFIG_KERNEL_DEBUG_BLK_CGROUP is not set
# CONFIG_KERNEL_NET_CLS_CGROUP is not set
# CONFIG_KERNEL_CGROUP_NET_CLASSID is not set
# CONFIG_KERNEL_CGROUP_NET_PRIO is not set
CONFIG_KERNEL_NAMESPACES=y
CONFIG_KERNEL_UTS_NS=y
CONFIG_KERNEL_IPC_NS=y
CONFIG_KERNEL_USER_NS=y
CONFIG_KERNEL_PID_NS=y
CONFIG_KERNEL_NET_NS=y
CONFIG_KERNEL_DEVPTS_MULTIPLE_INSTANCES=y
CONFIG_KERNEL_POSIX_MQUEUE=y
CONFIG_KERNEL_SECCOMP_FILTER=y
CONFIG_KERNEL_SECCOMP=y
CONFIG_KERNEL_IP_MROUTE=y
CONFIG_KERNEL_IP_MROUTE_MULTIPLE_TABLES=y
CONFIG_KERNEL_IP_PIMSM_V1=y
CONFIG_KERNEL_IP_PIMSM_V2=y
CONFIG_KERNEL_MPTCP=y
CONFIG_KERNEL_IPV6=y
CONFIG_KERNEL_IPV6_MULTIPLE_TABLES=y
CONFIG_KERNEL_IPV6_SUBTREES=y
CONFIG_KERNEL_IPV6_MROUTE=y
CONFIG_KERNEL_IPV6_MROUTE_MULTIPLE_TABLES=y
CONFIG_KERNEL_IPV6_PIMSM_V2=y
CONFIG_KERNEL_IPV6_SEG6_LWTUNNEL=y
# CONFIG_KERNEL_LWTUNNEL_BPF is not set
CONFIG_KERNEL_MPTCP_IPV6=y

 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

京东亚瑟云ax1800pro 128G

### 详细日志

编译成功了的
![416edc16](https://github.com/coolsnowwolf/lede/assets/27670071/a07d6417-b62b-469c-b172-cda16f9579f7)

**Comment by coolsnowwolf** [comment]
recovery 安装

**Comment by jeasonliang** [comment]
recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!

**Comment by jeasonliang** [comment]
> > recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!
> 
> 请教一下 “recovery 安装”是怎么操作的啊。因为我现在遇到的情况跟是一摸一样，能编译，但是刷不上

编译后有个openwrt-qualcommax-ipq60xx-jdcloud_re-ss-01-squashfs-recovery.bin的文件 在Uboot界面下 上传刷机

**Comment by Cipher2020** [comment]
> > > recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!
> > 
> > 
> > 请教一下 “recovery 安装”是怎么操作的啊。因为我现在遇到的情况跟是一摸一样，能编译，但是刷不上
> 
> 编译后有个openwrt-qualcommax-ipq60xx-jdcloud_re-ss-01-squashfs-recovery.bin的文件 在Uboot界面下 上传刷机

谢谢，我试试看。

**Comment by forzaseb** [comment]
> recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!

target/linux/qualcommax/image/ipq60xx.mk
![QQ截图20240707000344](https://github.com/coolsnowwolf/lede/assets/78002777/8b369212-cd1b-4971-b63c-bfc2b7227be3)
23行后面加入IMAGE/sysupgrade.bin/squashfs := append-rootfs | pad-to 64k | sysupgrade-tar rootfs=$$$$@ | append-metadata这一行试试，我的AX5JDC是这样解决的

**Comment by hulisang** [comment]
亚瑟的设备名不是jdc_ax1800_pro吗，为什么config里是jdcloud_re-ss-01

**Comment by jeasonliang** [comment]
> > recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!
> 
> target/linux/qualcommax/image/ipq60xx.mk ![QQ截图20240707000344](https://private-user-images.githubusercontent.com/78002777/346284923-8b369212-cd1b-4971-b63c-bfc2b7227be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDk5OTAsIm5iZiI6MTcyMDcwOTY5MCwicGF0aCI6Ii83ODAwMjc3Ny8zNDYyODQ5MjMtOGIzNjkyMTItY2QxYi00OTcxLWI2M2MtYmZjMmI3MjI3YmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE0NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDllZWMzYzhjZDkzNzY0OTEwYjQyOGE4ZDY4MDIwM2EwZjcyNGY4OGE5OTUzNzMxNTVlOGNkN2FkNjQ1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLJOtG3N4PAdpyGHMbHgB8o3OWTNe68vdOSvvNNFyhY) 23行后面加入IMAGE/sysupgrade.bin/squashfs := append-rootfs | pad-to 64k | sysupgrade-tar rootfs=$$$$@ | append-metadata这一行试试，我的AX5JDC是这样解决的

谢谢!我没有用实体机编译 ,用的GitHub云编译!还是要感谢你的指点!

**Comment by Cipher2020** [comment]
> > > recovery 安装成功,但是无法保存配置,更改好后,openwt一断电重新启动就又恢复到了初始状态!
> > 
> > 
> > target/linux/qualcommax/image/ipq60xx.mk ![QQ截图20240707000344](https://private-user-images.githubusercontent.com/78002777/346284923-8b369212-cd1b-4971-b63c-bfc2b7227be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDk5OTAsIm5iZiI6MTcyMDcwOTY5MCwicGF0aCI6Ii83ODAwMjc3Ny8zNDYyODQ5MjMtOGIzNjkyMTItY2QxYi00OTcxLWI2M2MtYmZjMmI3MjI3YmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE0NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MDllZWMzYzhjZDkzNzY0OTEwYjQyOGE4ZDY4MDIwM2EwZjcyNGY4OGE5OTUzNzMxNTVlOGNkN2FkNjQ1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLJOtG3N4PAdpyGHMbHgB8o3OWTNe68vdOSvvNNFyhY) 23行后面加入IMAGE/sysupgrade.bin/squashfs := append-rootfs | pad-to 64k | sysupgrade-tar rootfs=$$$$@ | append-metadata这一行试试，我的AX5JDC是这样解决的
> 
> 谢谢!我没有用实体机编译 ,用的GitHub云编译!还是要感谢你的指点!

  现在作者已经修复了这个问题，已经是可以保存设置了，我已经编译好了，当然你也可以云编译，目前的小问题是有些插件编译不进去，这是我的固件https://github.com/Cipher2020/peterx0323/actions/runs/9885226647
