### ISSUE TITLE
block: unable to load configuration (fstab: Entry not found)

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#12308]
### 详细叙述

Linux6.6内核，最新拉取
系统日志提示以下信息
老大，最新的编译还是会出现下面的这个，请问如何解决。。
user.err kernel: [ 6.189547] block: unable to load configuration (fstab: Entry not found)
user.info kernel: [ 6.190183] block: attempting to load /tmp/overlay/etc/config/fstab
user.err kernel: [ 6.190827] block: unable to load configuration (fstab: Entry not found)
user.info kernel: [ 6.191458] block: attempting to load /etc/config/fstab
user.err kernel: [ 6.194568] block: unable to load configuration (fstab: Entry not found)
user.err kernel: [ 6.195213] block: no usable configuration
user.info kernel: [ 6.195682] block: attempting to load /etc/config/fstab
user.err kernel: [ 6.196197] block: unable to load configuration (fstab: Entry not found)
user.err kernel: [ 6.196826] block: no usable configuration

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Nanopi

### 详细日志

正常编译

**Comment by coolsnowwolf** [comment]
忽略即可，这个是在读取 exroot ，新的机制
