### ISSUE TITLE
关于issues被无故close的问题

### ISSUE THREAD

**Issue by SuzukiHonoka** [coolsnowwolf/lede#1231]
发现lean也是一个很怠情的人。
自己能解决的就回复，
不能解决的就直接close，
一句话都不说，
看了被closed的列表发现一言不合被close的issues还挺多，
还真是厉害。

**Comment by wangxin6** [comment]
翻看了一些issue是没有全局翻墙造成的，被直接关的。

**Comment by coolsnowwolf** [comment]
重复的问题和没有附加任何日志的 issue，均属无效

随随便便的提问，当然就是随随便便的关闭

**Comment by SuzukiHonoka** [comment]
好的。
以后发issues会附上日志的。
