### ISSUE TITLE
红米AX6000 编译后没有无线信号

### ISSUE THREAD

**Issue by Turing-China** [coolsnowwolf/lede#12319]
### 详细叙述

红米AX6000 编译后没有无线信号；其他功能正常；使用最新6.6内核编译;编译时间7月8日
不知有没有大哥遇到过;是我编译什么地方没选对吗；我看无线驱动也有

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

红米AX6000

### 详细日志

![1](https://github.com/coolsnowwolf/lede/assets/107291340/0575c131-421d-4d36-b39e-7e0dba09e09a)
![2](https://github.com/coolsnowwolf/lede/assets/107291340/732b25eb-7f4d-4b15-be55-90ed0153868a)
![3](https://github.com/coolsnowwolf/lede/assets/107291340/8c546219-0371-42fb-a380-d7d7e5f6cf6f)
![4](https://github.com/coolsnowwolf/lede/assets/107291340/beb1fbe6-d157-473e-b21a-848b13a95a55)
![5](https://github.com/coolsnowwolf/lede/assets/107291340/1f5f0a3c-a1c2-4155-b304-73b6ae92eab9)

**Comment by coolsnowwolf** [comment]
终端不连上去有什么信号？

**Comment by Turing-China** [comment]
> 终端不连上去有什么信号？

终端看不到信号呀，搜索不到路由器的WIFI
