### ISSUE TITLE
v2ray 路由配置功能与rules 功能luci界面 开发请求

### ISSUE THREAD

**Issue by shelliao** [coolsnowwolf/lede#1232]
v2ray 官方描述中有提及路由与策略配置功能，可以实现1个inbound多个outbound，或者多个inbound多个outbound，并且通过rules来实现匹配

https://www.v2ray.com/chapter_02/03_routing.html

现希望在luci中实现一个inbound，多个outbound，并通过规则（例如url等）实现根据url进行分流（如url1去outbound1，url2去outbound2）

**Comment by hanxi** [comment]
v2ray 的配置太复杂了，我建议给个输入框，粘贴json进去更合适，这样就不会再有这种需求了。
