### ISSUE TITLE
rax3000m emmc版本的网口只有4和千兆口。编译出来多了1个2.5G网口

### ISSUE THREAD

**Issue by xsj520** [coolsnowwolf/lede#12326]
### 详细叙述

![Screenshot_20240712-061306_Samsung Internet](https://github.com/user-attachments/assets/75e478af-bc59-4f9e-981f-deb078c77762)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rax3000m emmc版

### 详细日志

无

**Comment by xsj520** [comment]
![Screenshot_20240712-061306_Samsung Internet](https://github.com/user-attachments/assets/1116fb4a-a567-4068-82be-65a57f595f0d)

**Comment by Cathgao** [comment]
那个是CPU内部接口，无视就行

**Comment by QYKing233** [comment]
那你赚大了
