### ISSUE TITLE
云编译固件问题，luci分支openwrt23.05

### ISSUE THREAD

**Issue by lanruihua026** [coolsnowwolf/lede#12339]
### 详细叙述

编译固件时发现lean源码luci主分支版本过老，遂切换到luci的openwrt23.05分支，编译过程中即使去掉luci-app-vsftpd这个插件，仍然报这个错误，请教一下各位大佬应如何解决，十分感谢！
![屏幕截图 2024-07-16 225629](https://github.com/user-attachments/assets/c2c73d1f-06c9-42dc-a656-0973d5aaea68)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

FastRhino R68s

### 详细日志

Collected errors:
Configuring uhttpd-mod-ubus.
 * check_data_file_clashes: Package vsftpd wants to install file /workdir/openwrt/build_dir/target-aarch64_generic_musl/root-rockchip/etc/init.d/vsftpd
	But that file is already provided by package  * vsftpd-alt
 * check_data_file_clashes: Package vsftpd wants to install file /workdir/openwrt/build_dir/target-aarch64_generic_musl/root-rockchip/usr/sbin/vsftpd
	But that file is already provided by package  * vsftpd-alt
 * opkg_install_cmd: Cannot install package vsftpd.

**Comment by yanxin152133** [comment]
vsftpd-alt  vsftpd冲突？

**Comment by lanruihua026** [comment]
> vsftpd-alt vsftpd冲突？

![image](https://github.com/user-attachments/assets/bafa1309-51cf-4588-a9d5-f9a48011d45e)
昨天重新把配置文件删除掉，只选了几个插件编译就通过了，感觉是某些插件会存在连带冲突，但是没办法直接从日志上看出来，只能一个个试

**Comment by lanruihua026** [comment]
<img width="1236" alt="屏幕截图 2024-07-17 102928" src="https://github.com/user-attachments/assets/ed826fba-7bf1-414e-b4cd-a7dbbe5b41d9">

**Comment by kxdn3** [comment]
请教云编译时候怎么切换到23.05的？

**Comment by lanruihua026** [comment]
> 请教云编译时候怎么切换到23.05的？

![屏幕截图 2024-07-20 161627](https://github.com/user-attachments/assets/ccb01102-b598-4776-86d3-a5d0fb00c97b)
Lede的feed default做如下修改，然后连同.config文件一同上传到GitHub上，再用action进行云编译

**Comment by lanruihua026** [comment]
https://github.com/P3TERX/Actions-OpenWrt
我用的这个仓库来进行编译

**Comment by magic-monkey** [comment]
Network - File Transfer - vsftpd-alt 这个选项去掉应该就好了
