### ISSUE TITLE
软路由SSRP 订阅链接后节点很少，只有三个。而使用 shadowrocket APP 订阅后得以得到 50 个左右节点。

### ISSUE THREAD

**Issue by lishengxuelong** [coolsnowwolf/lede#12340]
### 详细叙述

如题。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

华硕 TY6202

### 详细日志

不知道怎么看

**Comment by hcym** [comment]
新版本是这样的，去年的老版本正常工作

**Comment by lishengxuelong** [comment]
> 新版本是这样的，去年的老版本正常工作

那可以退回到旧版本吗
