### ISSUE TITLE
发哥bug

### ISSUE THREAD

**Issue by mirthlesslk** [coolsnowwolf/lede#12354]
### 详细叙述

e7646d4更新后，固件编译无报错，但是刷入固件之后不停的重启无法进入系统

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

6086

### 详细日志

编译能通过无报错，但不停的重启

**Comment by lanruihua026** [comment]
我是编译了 kmod usb rndis，插上随身WiFi后一直重启，断电后重新上电才恢复。

**Comment by caixin1218** [comment]
电源是多少A的

**Comment by lanruihua026** [comment]
12v1a



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月23日 10:22 |
| 收件人 | ***@***.***> |
| 抄送至 | Lan ***@***.***>***@***.***> |
| 主题 | Re: [coolsnowwolf/lede] 发哥bug (Issue #12354) |

电源是多少A的

**Comment by caixin1218** [comment]
> 12v1a
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年07月23日 10:22 | | 收件人 | ***@***.***> | | 抄送至 | Lan ***@***.***>***@***.***> | | 主题 | Re: [coolsnowwolf/lede] 发哥bug (Issue #12354) | 电源是多少A的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

换个2A以上的电源就没有问题了，我之前也是这样的。
