### ISSUE TITLE
云编译选择内核版本

### ISSUE THREAD

**Issue by lanruihua026** [coolsnowwolf/lede#12355]
### 详细叙述

大佬您好，我想问一下云编译如何选择使用最新的6.6内核，我的软路由是电犀牛R68S，目前选择配置好编译出来的是6.1.98版本
![image](https://github.com/user-attachments/assets/7f226260-1606-43ad-9b8f-5a25299a5d0e)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

FastRhino R68S

### 详细日志

问题求助

**Comment by mitsukileung** [comment]
sed -i 's/KERNEL_PATCHVER:=6.1/KERNEL_PATCHVER:=6.6/g' target/linux/rockchip/Makefile
