### ISSUE TITLE
libsodium更新后shadowsocksr-libev无法启动

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#12369]
### 详细叙述

如题，libsodium更新至1.0.19后shadowsocksr-libev无法启动，提示缺少libsodium.so.23
上一个版本无此问题，如有可能烦请大佬回滚
@coolsnowwolf 
@aiamadeus 
十分感谢

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

同上

**Comment by aiamadeus** [comment]
... make clean 即可

**Comment by bi4tms** [comment]
> ... make clean 即可

大佬，make clean后重新编译吗
