### ISSUE TITLE
K3 源码 drivers/net/phy/b53 编译错误

### ISSUE THREAD

**Issue by ramblerSY** [coolsnowwolf/lede#12360]
### 详细叙述

类型的问题如下:https://github.com/coolsnowwolf/lede/issues/12304
r7800出现交换芯片驱动的错误?影响了k3?
错误如下:
drivers/net/phy/b53/b53_common.c: In function 'b53_configure_ports_of':
drivers/net/phy/b53/b53_common.c:512:25: error: too many arguments to function 'of_get_phy_mode'
  512 |                         of_get_phy_mode(pn, &mode);
      |                         ^~~~~~~~~~~~~~~
In file included from drivers/net/phy/b53/b53_common.c:29:
./include/linux/of_net.h:13:12: note: declared here
   13 | extern int of_get_phy_mode(struct device_node *np);
      |            ^~~~~~~~~~~~~~~

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

K3

### 详细日志

Run cd openwrt
4 thread compile
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] tools/compile
 make[2] package/cleanup
 make[3] -C tools/flock compile
 make[3] -C tools/xz compile
 make[3] -C tools/sed compile
 make[3] -C tools/patch compile
 make[3] -C tools/libdeflate compile
 make[3] -C tools/tar compile
 make[3] -C tools/m4 compile
 make[3] -C tools/autoconf-archive compile
 make[3] -C tools/ninja compile
 make[3] -C tools/expat compile
 make[3] -C tools/zlib compile
 make[3] -C tools/cpio compile
 make[3] -C tools/lzma compile
 make[3] -C tools/make-ext4fs compile
 make[3] -C tools/mtools compile
 make[3] -C tools/patch-image compile
 make[3] -C tools/squashfskit4 compile
 make[3] -C tools/sstrip compile
 make[3] -C tools/zip compile
 make[3] -C tools/meson compile
 make[3] -C tools/pkgconf compile
 make[3] -C tools/zstd compile
 make[3] -C tools/libressl compile
 make[3] -C tools/autoconf compile
 make[3] -C tools/elfutils compile
 make[3] -C tools/automake compile
 make[3] -C tools/missing-macros compile
 make[3] -C tools/libtool compile
 make[3] -C tools/dosfstools compile
 make[3] -C tools/cmake compile
 make[3] -C tools/flex compile
 make[3] -C tools/e2fsprogs compile
 make[3] -C tools/fakeroot compile
 make[3] -C tools/gengetopt compile
 make[3] -C tools/mklibs compile
 make[3] -C tools/mtd-utils compile
 make[3] -C tools/patchelf compile
 make[3] -C tools/gmp compile
 make[3] -C tools/bison compile
 make[3] -C tools/bc compile
 make[3] -C tools/findutils compile
 make[3] -C tools/mkimage compile
 make[3] -C tools/util-linux compile
 make[3] -C tools/mpfr compile
 make[3] -C tools/padjffs2 compile
 make[3] -C tools/quilt compile
 make[3] -C tools/mpc compile
 make[3] -C tools/firmware-utils compile
 make[2] toolchain/compile
 make[3] -C toolchain/fortify-headers compile
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/gcc/initial compile
 make[3] -C toolchain/kernel-headers compile
 make[3] -C toolchain/musl compile
 make[3] -C toolchain/gcc/final compile
 make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:[23](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:24)1: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
make[1]: Entering directory '/workdir/openwrt'
make[2]: Entering directory '/workdir/openwrt'
make[3]: Entering directory '/workdir/openwrt/target/linux'
make[4]: Entering directory '/workdir/openwrt/target/linux/bcm53xx'
rm -f /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/localversion
/workdir/openwrt/scripts/kconfig.pl  + /workdir/openwrt/target/linux/generic/config-5.4 /workdir/openwrt/target/linux/bcm53xx/config-5.4 > /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /workdir/openwrt/.config >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target
/workdir/openwrt/scripts/package-metadata.pl kconfig /workdir/openwrt/tmp/.packageinfo /workdir/openwrt/.config 5.4 > /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.override
/workdir/openwrt/scripts/kconfig.pl 'm+' '+' /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.target /dev/null /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.override > /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set
mv /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.old
grep -v INITRAMFS /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.old > /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set
echo "# CONFIG_INITRAMFS_PRESERVE_MTIME is not set" >> /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set
rm -rf /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/modules
cmp -s /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.prev || { cp /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config; cp /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.prev; }
export MAKEFLAGS= ; [ -d /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/user_headers ] || make -C /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi=target-arm_cortex-a9_musl_eabi -fno-caller-saves -falign-functions=32" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Wed Jul [24](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:25) 13:30:03 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.278 CC="arm-openwrt-linux-muslgnueabi-gcc"  INSTALL_HDR_PATH=/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/user_headers headers_install
grep '=[ym]' /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.config.set | LC_ALL=C sort | /workdir/openwrt/staging_dir/host/bin/mkhash md5 > /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.vermagic
touch /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.configured
rm -f /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/vmlinux /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/System.map
make -C /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi=target-arm_cortex-a9_musl_eabi -fno-caller-saves -falign-functions=32" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Wed Jul 24 13:30:03 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.278 CC="arm-openwrt-linux-muslgnueabi-gcc" olddefconfig
make[5]: Entering directory '/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278'
scripts/kconfig/conf  --olddefconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:476:warning: multi-line strings not supported
#
# No change to .config
#
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278'
make -C /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278 KCFLAGS="-fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi=target-arm_cortex-a9_musl_eabi -fno-caller-saves -falign-functions=32" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Wed Jul 24 13:30:03 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.278 CC="arm-openwrt-linux-muslgnueabi-gcc" zImage dtbs modules
make[5]: Entering directory '/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      drivers/net/phy/b53/b53_common.o
drivers/net/phy/b53/b53_common.c: In function 'b53_configure_ports_of':
drivers/net/phy/b53/b53_common.c:512:[25](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:26): error: too many arguments to function 'of_get_phy_mode'
  512 |                         of_get_phy_mode(pn, &mode);
      |                         ^~~~~~~~~~~~~~~
In file included from drivers/net/phy/b53/b53_common.c:29:
./include/linux/of_net.h:13:12: note: declared here
   13 | extern int of_get_phy_mode(struct device_node *np);
      |            ^~~~~~~~~~~~~~~
make[9]: *** [scripts/Makefile.build:[26](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:27)2: drivers/net/phy/b53/b53_common.o] Error 1
make[8]: *** [scripts/Makefile.build:497: drivers/net/phy/b53] Error 2
make[7]: *** [scripts/Makefile.build:497: drivers/net/phy] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/net] Error 2
make[5]: *** [Makefile:1750: drivers] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.[27](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:28)8'
make[4]: *** [Makefile:32: /workdir/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/linux-bcm53xx_generic/linux-5.4.278/.modules] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/bcm53xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#5.15#2.99#7.98
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:[30](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:31): target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:2[31](https://github.com/ramblerSY/P3TERX-Actions-OpenWrt/actions/runs/10089503812/job/27897076657#step:12:32): world] Error 2

**Comment by ramblerSY** [comment]
看了相关的修改 https://github.com/coolsnowwolf/lede/blob/master/target/linux/generic/files/drivers/net/phy/ar8216.c
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 5, 0)
	of_get_phy_mode(priv->pdev->of_node, &phy_if_mode);
#else
	phy_if_mode = of_get_phy_mode(priv->pdev->of_node);
#endif
k3好像用到的内核版本是linux-5.4.278， 没找到对应k3在哪里修改

**Comment by coolsnowwolf** [comment]
已修复
