### ISSUE TITLE
编译提示cannot find dependency iptables-mod-fullconenat for firewall

### ISSUE THREAD

**Issue by dd-bpir3** [coolsnowwolf/lede#12371]
### 详细叙述

每次编译到package/install过不去提示错误

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

bpi-r3

### 详细日志

* pkg_hash_check_unresolved: cannot find dependency iptables-mod-fullconenat for firewall
 * pkg_hash_fetch_best_installation_candidate: Packages for firewall found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for default-settings:
 * 	iptables-mod-fullconenat
 * opkg_install_cmd: Cannot install package default-settings.
 * check_conflicts_for: The following packages conflict with firewall:
 * check_conflicts_for: 	firewall4 * 
 * opkg_install_cmd: Cannot install package firewall.
 * check_data_file_clashes: Package vsftpd wants to install file /home/yph/lede/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/etc/init.d/vsftpd
	But that file is already provided by package  * vsftpd-alt
 * check_data_file_clashes: Package vsftpd wants to install file /home/yph/lede/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/usr/sbin/vsftpd
	But that file is already provided by package  * vsftpd-alt
 * opkg_install_cmd: Cannot install package vsftpd.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/yph/lede'
make[1]: *** [package/Makefile:111: /home/yph/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/yph/lede'
make: *** [/home/yph/lede/include/toplevel.mk:231: world] Error 2

**Comment by yanxin152133** [comment]
vsftpd-alt和vsftpd 冲突了

**Comment by yanxin152133** [comment]
https://github.com/coolsnowwolf/lede/issues/12339

**Comment by dd-bpir3** [comment]
> vsftpd-alt和vsftpd 冲突了




> vsftpd-alt和vsftpd 冲突了

vsftpd-alt和vsftpd是我切换23.05造成的，切换回去还是提示上面错误。

**Comment by yanxin152133** [comment]
> > vsftpd-alt和vsftpd 冲突了
> 
> > vsftpd-alt和vsftpd 冲突了
> 
> vsftpd-alt和vsftpd是我切换23.05造成的，切换回去还是提示上面错误。

万能大法试试

**Comment by dd-bpir3** [comment]
> > > vsftpd-alt和vsftpd 冲突了
> > 
> > 
> > > vsftpd-alt和vsftpd 冲突了
> > 
> > 
> > vsftpd-alt和vsftpd是我切换23.05造成的，切换回去还是提示上面错误。
> 
> 万能大法试试
没好使

**Comment by dd-bpir3** [comment]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency iptables-mod-fullconenat for firewall
 * pkg_hash_fetch_best_installation_candidate: Packages for firewall found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for default-settings:
 *      iptables-mod-fullconenat
 * opkg_install_cmd: Cannot install package default-settings.
 * check_conflicts_for: The following packages conflict with firewall:
 * check_conflicts_for:         firewall4 * 
 * opkg_install_cmd: Cannot install package firewall.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/yph/lede'
make[1]: *** [package/Makefile:111: /home/yph/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/yph/lede'
make: *** [/home/yph/lede/include/toplevel.mk:231: world] Error 2
