### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by kingsoft2019** [coolsnowwolf/lede#1237]
lean的固件非常好用，zerotier很稳定。但是大家千万不要设置错误，设置错误，会瘫痪，要重新刷机。

**Comment by sirfromprc** [comment]
很好，大屌喜欢被夸

**Comment by xunqiuhuiyi** [comment]
> lean的固件非常好用，zerotier很稳定。但是大家千万不要设置错误，设置错误，会瘫痪，要重新刷机。

不需要重新刷机，你就手动设置ip 进去以后 关闭zt 关闭进程 重启路由器就可以了
