### ISSUE TITLE
lede雷神加速器插件游戏内延迟很高

### ISSUE THREAD

**Issue by HOT-POT1** [coolsnowwolf/lede#12386]
### 详细叙述

就拿绝地求生来说，win10客户端就50左右延迟，路由器插件直接120左右，路由器是京东云百里ax6000，cpu是mt7986

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

京东云百里ax6000

### 详细日志

![photo_2024-08-05_10-12-37](https://github.com/user-attachments/assets/0590ffe0-ef16-448e-b92a-ef096cfbfc94)
不知道其他网友测试的怎么样

**Comment by Rivens7** [comment]
这个延迟看着应该是没有加速上，应该是裸连了

**Comment by coolsnowwolf** [comment]
APP 里面有打开加速么？ 要设置加速的游戏类型的

**Comment by HOT-POT1** [comment]
> APP 里面有打开加速么？ 要设置加速的游戏类型的

开了，不开延迟可不止这一点延迟，而且会一直显示丢包10%，最开始还是70左右，后面用就100多了

**Comment by lovexiaofan123** [comment]
关Shortcut-FE 流量分载
然后NAT开高性能模式

**Comment by HOT-POT1** [comment]
> 关Shortcut-FE 流量分载 然后NAT开高性能模式

好像没啥关系，也有可能加速器服务器节点有问题，不过app上不能选节点，功能太少

**Comment by NeedforGit** [comment]
雷神这个app有时候就是不稳定，有时候加速不起作用，需要重启一下，特别是开那个tun模式，更加不稳定。
再等等后续更新吧。
