### ISSUE TITLE
求教，这个云编译错误是哪里问题

### ISSUE THREAD

**Issue by free-diy** [coolsnowwolf/lede#12389]
### 详细叙述

快编译结束了，突然报错，请问这是哪里出问题了？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

Configuring kmod-e1000e.
Configuring luci-i18n-upnp-zh-cn.
Configuring alsa-ucm-conf.
Configuring alsa-utils.
Configuring kmod-button-hotplug.
Configuring smartdns.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring kmod-ipt-nat.
Configuring iptables-zz-legacy.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:168: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

**Comment by aiamadeus** [comment]
iptables-zz-legacy ??? 这里没有这个包
