### ISSUE TITLE
自编译的R4S设备固件，开机后lan口配置似乎不对

### ISSUE THREAD

**Issue by banana121** [coolsnowwolf/lede#12392]
### 详细叙述

自编译的R4S设备固件，可以正常开机，开机后lan口配置似乎不对，PC插lan口无法获取ip，指示灯也不闪烁。wan看起来正常，但连接不上lan口，无法确认系统启动的具体状态。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

nanopi R4S

### 详细日志

无，编译安装正常。

**Comment by yanxin152133** [comment]
wan口设置成lan口也是这样吗

**Comment by banana121** [comment]
> wan口设置成lan口也是这样吗
厉害，我都没想到，交换了一下，至少能登录路由了。初步差了一下ifconfig，没看到eth1

root@OpenWrt:~# ifconfig
br-lan    Link encap:Ethernet  HWaddr 04:91:62:F0:4B:86
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fdb8:8d96:36e4::1/60 Scope:Global
          inet6 addr: fe80::691:62ff:fef0:4b86/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2431 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1715 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:239416 (233.8 KiB)  TX bytes:601150 (587.0 KiB)

eth0      Link encap:Ethernet  HWaddr 04:91:62:F0:4B:86
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2484 errors:0 dropped:12 overruns:0 frame:0
          TX packets:1851 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:275944 (269.4 KiB)  TX bytes:607934 (593.6 KiB)
          Interrupt:43

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:274 errors:0 dropped:0 overruns:0 frame:0
          TX packets:274 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:21193 (20.6 KiB)  TX bytes:21193 (20.6 KiB)

**Comment by banana121** [comment]
> wan口设置成lan口也是这样吗

应该是默认没有勾选网络驱动，我把驱动编译进去就好了，多谢！

**Comment by banana121** [comment]
> > > wan口设置成lan口也是这样吗
> > 
> > 
> > 应该是默认没有勾选网络驱动，我把驱动编译进去就好了，多谢！
> 
> 遇到了一样的问题，请问你是勾选了哪个驱动，就好了呀？

时间有点久了，好像是r8169的驱动。

**Comment by quanlook** [comment]
https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R4S

3.2 R4S 标准版与 R4S 企业版区别
R4S企业版内置 EEPROM 芯片（型号：24AA025E48T），该芯片具有全局唯一的 MAC 地址。这是一个永久且不可篡改的地址。R4S
标准版没有内置 EEPROM 芯片，其 MAC 地址由软件实用程序生成。除此之外，两个版本的硬件配置相同。

标准版没有内置 MAC 地址的 EEPROM 芯片，而企业版有。标准版和企业版都使用相同的网络芯片（RealTek RTL8211E 和 R8111H）。更多详细信息，请参阅以下屏幕截图。建议零售用户选择标准版，建议企业用户选择企业版。

提示：大多数现有的嵌入式 ARM 开发板（例如 RPi 3B）的 MAC 地址都是通过软件实用程序生成的。这通常不会影响网络通信。全局唯一的 MAC 地址在复杂的网络环境下能够带来更佳的网络性能，尤其适用于管理多个网络设备并执行 IP 绑定等操作的大型企业级应用。EEPROM

芯片的位置： NanoPi R4S 企业版具有全局唯一的 MAC 地址，该地址默认分配给 CPU 内部的以太网接口（rtl8211e），设备名称为 eth0。该设备在 PCB 板上名为“LAN2”，在板子外壳上名为“WAN”。这已在 FriendlyWrt 中默认配置。 在 FriendlyWrt 官网上查看 MAC 地址： 在命令行工具中查看： 如何查看是否为全局唯一的 MAC 地址：
