### ISSUE TITLE
编译出来只有几兆

### ISSUE THREAD

**Issue by nonicknamelala** [coolsnowwolf/lede#1239]
大佬，论坛上下载的固件有个问题，有时候拨号总是拨不上去，pppd进程一直在那卡着，也无法停止进程。后来我尝试按照你的步骤编译，到了make menuconfig这一步完全不知道怎么配置啊，后来我百度了一下，大概设置了前面三四项，编译过程大概有两三个小时，可是完成后只有几兆的bin文件，应该是有问题的，刷上去后路由器也没法启动。请问可以指点一下吗？谢谢了！
---
另外，我发现如果光猫重启后，wan口不会自动重拨，查了一下，加了如下参数好像解决了。
/etc/config/network
        option keepalive '5 5'

**Comment by Zxilly** [comment]
几m有什么问题吗。。。你还想几G不成，机型说下，.config发下

**Comment by nonicknamelala** [comment]
> 
> 
> 几m有什么问题吗。。。你还想几G不成，机型说下，.config发下

这个几兆的文件刷了以后k2p无法启动，论坛里下载的固件都是十几兆啊。.config配置如下，其他都是默认
Target System 选择 MediaTek Ralink MIPS
Subtarget 选择 MT7621 based boards
Target Profile 选择 Phicomm K2P

**Comment by Zxilly** [comment]
十几m都是加了东西，系统本身就5-6m，比如v2ray一项就8m多

**Comment by Zxilly** [comment]
make menuconfig 会英语就够了啊，说得都很明白

**Comment by nonicknamelala** [comment]
> 
> 
> make menuconfig 会英语就够了啊，说得都很明白

对于菜鸟来说这些配置选项本身就不明白，不是中英文的问题。或者说，哪位大佬能不能把k2p的配置共享一下，多谢了！
