### ISSUE TITLE
编译完成K2P的固件后，刷入路由器无法启动。不知道什么原因，有和我一样情况的吗？

### ISSUE THREAD

**Issue by mlw221** [coolsnowwolf/lede#124]
不知道什么原因，有和我一样情况的吗？回头有空接上TTL 把信息导出看一下。

**Comment by hcym** [comment]
K2也是一样，其它的都不错
问题是我的K2用各种各样的lede都无法启动
只好编译Padavan

**Comment by kmahyyg** [comment]
marked,watched

**Comment by hzjnet** [comment]
热 我也是

**Comment by coolsnowwolf** [comment]
Breed 里面有分区格式选择，公版和斐讯，自己选择，肯定有一个适合的

**Comment by chd1998** [comment]
刷机时候内存选斐讯布局。。。
