### ISSUE TITLE
recipe for target 'world' failed

### ISSUE THREAD

**Issue by PoorerImmune** [coolsnowwolf/lede#1241]
編譯多次，已確認安裝必要的依賴套件，但如下問題反覆出現
![錯誤](https://user-images.githubusercontent.com/48857142/57005233-d6281500-6c08-11e9-9ec2-13aad9435414.png)
錯誤記錄檔如下：
[cmake_bootstrap.log](https://github.com/coolsnowwolf/lede/files/3133784/cmake_bootstrap.log)
問題到底出在哪？

**Comment by Zxilly** [comment]
g++被关闭了，试着更新g++或者检查依赖

**Comment by PoorerImmune** [comment]
@Zxilly g++已是最新，且APT沒有顯示相依性問題。我在另一台伺服器上嘗試過，遇到的錯誤也是完全相同。

**Comment by PoorerImmune** [comment]
@Zxilly 已找到問題所在。
![空間不足](https://user-images.githubusercontent.com/48857142/57016169-4192d680-6c4b-11e9-8682-fcb63e12994a.png)
原因是伺服器記憶體空間不足所致，g++編譯期間需要佔用大量的記憶體，致使編譯程式被迫終止。
