### ISSUE TITLE
Xiaomi Redmi Router AX6000自动重启

### ISSUE THREAD

**Issue by smithe-ma** [coolsnowwolf/lede#12423]
### 详细叙述

每24小时内会莫名其妙重启

主机名	OpenWrt
主机型号	Xiaomi Redmi Router AX6000 (CpuMark : 27777.777778 Scores)
架构	ARMv8 Processor x 4 (45.2°C)
固件版本	OpenWrt R24.7.7 / LuCI Master (git-24.182.36151-66d29de)
内核版本	6.1.97 

开启如下设置：
软件流量分载
基于软件的 Routing/NAT 分载
硬件流量分载
需要硬件 NAT 支持，目前 mt762x 已实现
MTK 无线硬件加速
需要硬件支持，目前 Filogic 8x0 已实现
BBR 拥塞控制算法
使用 BBR 拥塞控制算法可以有效提升 TCP 网络性能 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Xiaomi Redmi Router AX6000

### 详细日志

内核日志

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 6.1.97 (admin@iZj6c7khbkoi3ts19wnkjrZ) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r6769-665cedd25) 11.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP Sat Jul 13 15:02:08 2024
[    0.000000] Machine model: Xiaomi Redmi Router AX6000
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000042ffffff]
[    0.000000]   node   0: [mem 0x0000000043000000-0x000000004302ffff]
[    0.000000]   node   0: [mem 0x0000000043030000-0x000000004fbfffff]
[    0.000000]   node   0: [mem 0x000000004fc00000-0x000000004ffbffff]
[    0.000000]   node   0: [mem 0x000000004ffc0000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.2
[    0.000000] percpu: Embedded 18 pages/cpu s33768 r8192 d31768 u73728
[    0.000000] pcpu-alloc: s33768 r8192 d31768 u73728 alloc=18*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: GIC system register CPU interface
[    0.000000] CPU features: kernel page table isolation disabled by kernel configuration
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Kernel command line: console=ttyS0,115200n1 loglevel=8 firmware=1 uart_en=1
[    0.000000] Unknown kernel command line parameters "firmware=1 uart_en=1", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 497108K/524288K available (8448K kernel code, 910K rwdata, 2432K rodata, 448K init, 292K bss, 27180K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GICv3: GIC: Using split EOI/Deactivate mode
[    0.000000] GICv3: 640 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GICv3: GICv3 features: 16 PPIs
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x000000000c080000
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 13.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x2ff89eacb, max_idle_ns: 440795202429 ns
[    0.000000] sched_clock: 56 bits at 13MHz, resolution 76ns, wraps every 4398046511101ns
[    0.000120] Calibrating delay loop (skipped), value calculated using timer frequency.. 26.00 BogoMIPS (lpj=130000)
[    0.000128] pid_max: default: 32768 minimum: 301
[    0.000332] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000338] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.001012] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.001308] cblist_init_generic: Setting adjustable number of callback queues.
[    0.001311] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.001398] rcu: Hierarchical SRCU implementation.
[    0.001400] rcu: 	Max phase no-delay instances is 1000.
[    0.001684] smp: Bringing up secondary CPUs ...
[    0.001943] Detected VIPT I-cache on CPU1
[    0.001987] cacheinfo: Unable to detect cache hierarchy for CPU 1
[    0.001994] GICv3: CPU1: found redistributor 1 region 0:0x000000000c0a0000
[    0.002021] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.002278] Detected VIPT I-cache on CPU2
[    0.002311] cacheinfo: Unable to detect cache hierarchy for CPU 2
[    0.002315] GICv3: CPU2: found redistributor 2 region 0:0x000000000c0c0000
[    0.002326] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.002577] Detected VIPT I-cache on CPU3
[    0.002607] cacheinfo: Unable to detect cache hierarchy for CPU 3
[    0.002611] GICv3: CPU3: found redistributor 3 region 0:0x000000000c0e0000
[    0.002620] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.002645] smp: Brought up 1 node, 4 CPUs
[    0.002649] SMP: Total of 4 processors activated.
[    0.002651] CPU features: detected: 32-bit EL0 Support
[    0.002653] CPU features: detected: CRC32 instructions
[    0.002678] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.002680] CPU: All CPU(s) started at EL2
[    0.002682] alternatives: applying system-wide alternatives
[    0.005130] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.005146] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.005282] pinctrl core: initialized pinctrl subsystem
[    0.005794] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.006049] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.006069] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.006087] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.006417] thermal_sys: Registered thermal governor 'fair_share'
[    0.006420] thermal_sys: Registered thermal governor 'bang_bang'
[    0.006421] thermal_sys: Registered thermal governor 'step_wise'
[    0.006423] thermal_sys: Registered thermal governor 'user_space'
[    0.006477] ASID allocator initialised with 65536 entries
[    0.006793] pstore: Registered ramoops as persistent store backend
[    0.006795] ramoops: using 0x10000@0x42ff0000, ecc: 0
[    0.013916] cryptd: max_cpu_qlen set to 1000
[    0.014547] SCSI subsystem initialized
[    0.014623] libata version 3.00 loaded.
[    0.015513] clocksource: Switched to clocksource arch_sys_counter
[    0.016066] NET: Registered PF_INET protocol family
[    0.016148] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.016532] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.016543] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.016549] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.016570] TCP bind hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    0.016660] TCP: Hash tables configured (established 4096 bind 4096)
[    0.016780] MPTCP token hash table entries: 512 (order: 1, 12288 bytes, linear)
[    0.016813] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.016823] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.016908] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.016926] PCI: CLS 0 bytes, default 64
[    0.017779] workingset: timestamp_bits=46 max_order=17 bucket_order=0
[    0.020690] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.020699] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.046373] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.047040] printk: console [ttyS0] disabled
[    0.067193] 11002000.serial: ttyS0 at MMIO 0x11002000 (irq = 116, base_baud = 2500000) is a ST16650V2
[    0.770440] printk: console [ttyS0] enabled
[    0.775189] mtk_rng 1020f000.rng: registered RNG driver
[    0.780647] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.789031] loop: module loaded
[    0.793301] spi spi0.0: setup: ignoring unsupported mode bits a00
[    0.799646] spi-nand spi0.0: ESMT SPI NAND was found.
[    0.804686] spi-nand spi0.0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
[    0.814046] Signature found at block 1023 [0x07fe0000]
[    0.819175] NMBM management region starts at block 960 [0x07800000]
[    0.829932] First info table with writecount 0 found in block 960
[    0.849237] Second info table with writecount 0 found in block 963
[    0.855400] NMBM has been successfully attached
[    0.860112] 8 fixed-partitions partitions found on MTD device spi0.0
[    0.866466] Creating 8 MTD partitions on "spi0.0":
[    0.871240] 0x000000000000-0x000000100000 : "BL2"
[    0.877091] 0x000000100000-0x000000140000 : "Nvram"
[    0.882455] 0x000000140000-0x000000180000 : "Bdata"
[    0.887818] 0x000000180000-0x000000380000 : "Factory"
[    0.894771] 0x000000380000-0x000000580000 : "FIP"
[    0.901338] 0x000000580000-0x0000005c0000 : "crash"
[    0.906704] 0x0000005c0000-0x000000600000 : "crash_log"
[    0.912369] 0x000000600000-0x000007400000 : "ubi"
[    1.139859] mtk_soc_eth 15100000.ethernet eth0: mediatek frame engine at 0xffffffc009400000, irq 121
[    1.149409] i2c_dev: i2c /dev entries driver
[    1.154850] mtk-wdt 1001c000.watchdog: Watchdog enabled (timeout=31 sec, nowayout=0)
[    1.163331] NET: Registered PF_INET6 protocol family
[    1.168946] Segment Routing with IPv6
[    1.172616] In-situ OAM (IOAM) with IPv6
[    1.176574] NET: Registered PF_PACKET protocol family
[    1.181684] 8021q: 802.1Q VLAN Support v1.8
[    1.186922] pstore: Using crash dump compression: deflate
[    1.244513] mt7530-mdio mdio-bus:1f: configuring for fixed/2500base-x link mode
[    1.253392] mt7530-mdio mdio-bus:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[    1.262772] mt7530-mdio mdio-bus:1f lan4 (uninitialized): PHY [mt7530-0:01] driver [MediaTek MT7531 PHY] (irq=125)
[    1.283611] mt7530-mdio mdio-bus:1f lan3 (uninitialized): PHY [mt7530-0:02] driver [MediaTek MT7531 PHY] (irq=126)
[    1.303702] mt7530-mdio mdio-bus:1f lan2 (uninitialized): PHY [mt7530-0:03] driver [MediaTek MT7531 PHY] (irq=127)
[    1.323759] mt7530-mdio mdio-bus:1f wan (uninitialized): PHY [mt7530-0:04] driver [MediaTek MT7531 PHY] (irq=128)
[    1.334773] device eth0 entered promiscuous mode
[    1.339414] DSA: tree 0 setup
[    1.343685] UBI: auto-attach mtd7
[    1.347010] ubi0: default fastmap pool size: 40
[    1.351524] ubi0: default fastmap WL pool size: 20
[    1.356314] ubi0: attaching mtd7
[    3.259988] ubi0: scanning is finished
[    3.288217] ubi0: attached mtd7 (name "ubi", size 110 MiB)
[    3.293700] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    3.300566] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    3.307336] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    3.314276] ubi0: good PEBs: 880, bad PEBs: 0, corrupted PEBs: 0
[    3.320264] ubi0: user volume: 3, internal volumes: 1, max. volumes count: 128
[    3.327466] ubi0: max/mean erase counter: 8/4, WL threshold: 4096, image sequence number: 0
[    3.335794] ubi0: available PEBs: 0, total reserved PEBs: 880, PEBs reserved for bad PEB handling: 19
[    3.344992] ubi0: background thread "ubi_bgt0d" started, PID 411
[    3.354683] block ubiblock0_1: created from ubi0:1(rootfs)
[    3.360184] ubiblock: device ubiblock0_1 (rootfs) set to be root filesystem
[    3.367206] clk: Disabling unused clocks
[    3.390048] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    3.397341] Freeing unused kernel memory: 448K
[    3.401812] Run /sbin/init as init process
[    3.405906]   with arguments:
[    3.408858]     /sbin/init
[    3.411549]   with environment:
[    3.414673]     HOME=/
[    3.417024]     TERM=linux
[    3.419716]     firmware=1
[    3.422406]     uart_en=1
[    4.005521] random: crng init done
[    4.381554] init: Console is alive
[    4.385053] init: - watchdog -
[    5.432599] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    5.582505] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    5.596407] init: - preinit -
[    7.438510] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/2500base-x link mode
[    7.446986] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[    7.455618] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   11.982609] mount_root: loading kmods from internal overlay
[   11.995275] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[   12.002500] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[   12.622843] block: attempting to load /tmp/overlay/upper/etc/config/fstab
[   12.629700] block: unable to load configuration (fstab: Entry not found)
[   12.636420] block: attempting to load /tmp/overlay/etc/config/fstab
[   12.642709] block: unable to load configuration (fstab: Entry not found)
[   12.649425] block: attempting to load /etc/config/fstab
[   12.669149] block: unable to load configuration (fstab: Entry not found)
[   12.675888] block: no usable configuration
[   12.683708] UBIFS (ubi0:2): Mounting in unauthenticated mode
[   12.689447] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 494
[   12.823836] UBIFS (ubi0:2): recovery needed
[   13.114302] UBIFS (ubi0:2): recovery completed
[   13.118803] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs_data"
[   13.126621] UBIFS (ubi0:2): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   13.136515] UBIFS (ubi0:2): FS size: 64757760 bytes (61 MiB, 510 LEBs), max 520 LEBs, journal size 3301376 bytes (3 MiB, 26 LEBs)
[   13.148144] UBIFS (ubi0:2): reserved for root: 3058669 bytes (2986 KiB)
[   13.154739] UBIFS (ubi0:2): media format: w5/r0 (latest is w5/r0), UUID 413E7FC1-6538-438F-BCB5-1D521438F3E1, small LPT model
[   13.173779] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   13.202456] block: extroot: not configured
[   13.206637] UBIFS (ubi0:2): un-mount UBI device 0
[   13.211335] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops
[   13.223948] UBIFS (ubi0:2): Mounting in unauthenticated mode
[   13.229679] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 497
[   13.538143] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs_data"
[   13.545966] UBIFS (ubi0:2): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   13.555859] UBIFS (ubi0:2): FS size: 64757760 bytes (61 MiB, 510 LEBs), max 520 LEBs, journal size 3301376 bytes (3 MiB, 26 LEBs)
[   13.567485] UBIFS (ubi0:2): reserved for root: 3058669 bytes (2986 KiB)
[   13.574078] UBIFS (ubi0:2): media format: w5/r0 (latest is w5/r0), UUID 413E7FC1-6538-438F-BCB5-1D521438F3E1, small LPT model
[   13.603860] mount_root: loading kmods from internal overlay
[   13.621237] kmodloader: loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[   13.635161] kmodloader: done loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[   13.828423] block: attempting to load /tmp/overlay/upper/etc/config/fstab
[   13.848329] block: extroot: not configured
[   13.853724] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   13.860828] block: extroot: not configured
[   13.870721] mount_root: switching to ubifs overlay
[   13.913864] overlayfs: null uuid detected in lower fs '/', falling back to xino=off,index=off,nfs_export=off.
[   13.974852] urandom-seed: Seeding with /etc/urandom.seed
[   14.122775] procd: - early -
[   14.125748] procd: - watchdog -
[   14.858175] procd: - watchdog -
[   14.870646] procd: - ubus -
[   15.068590] procd: - init -
[   16.629292] kmodloader: loading kernel modules from /etc/modules.d/*
[   16.864845] urngd: v1.0.2 started.
[   16.888476] NET: Registered PF_ALG protocol family
[   16.897248] tun: Universal TUN/TAP device driver, 1.6
[   16.921393] cryptodev: driver 1.13 loaded.
[   16.927781] crypto-safexcel 10320000.crypto: EIP97:230(0,1,4,4)-HIA:270(0,5,5),PE:150/433(alg:7fcdfc00)/0/0/0
[   16.958447] Loading modules backported from Linux version v6.1.24-0-g0102425ac76b
[   16.965959] Backport generated by backports.git v5.15.92-1-44-gd6ea70fafd36
[   16.986698] xt_time: kernel timezone is -0000
[   17.009124] mt798x-wmac 18000000.wifi: attaching wed device 0 version 2
[   17.091774] platform 15010000.wed: MTK WED WO Firmware Version: DEV_000000, Build Time: 20221012175005
[   17.101165] platform 15010000.wed: MTK WED WO Chip ID 00 Region 3
[   17.687321] mt798x-wmac 18000000.wifi: HW/SW Version: 0x8a108a10, Build Time: 20221012174648a
[   17.687321] 
[   18.024214] mt798x-wmac 18000000.wifi: WM Firmware Version: ____000000, Build Time: 20221012174725
[   18.063300] mt798x-wmac 18000000.wifi: WA Firmware Version: DEV_000000, Build Time: 20221012174937
[   18.171110] mt798x-wmac 18000000.wifi: registering led 'mt76-phy0'
[   18.179141] mt798x-wmac 18000000.wifi: registering led 'mt76-phy1'
[   22.014884] PPP generic driver version 2.4.2
[   22.019896] PPP MPPE Compression module registered
[   22.025252] NET: Registered PF_PPPOX protocol family
[   22.038971] kmodloader: done loading kernel modules from /etc/modules.d/*
[   29.648510] mtk_soc_eth 15100000.ethernet eth0: Link is Down
[   29.659649] mtk_soc_eth 15100000.ethernet eth0: configuring for fixed/2500base-x link mode
[   29.668075] mtk_soc_eth 15100000.ethernet eth0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   29.668878] mt7530-mdio mdio-bus:1f lan2: configuring for phy/gmii link mode
[   29.684146] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   29.690577] br-lan: port 1(lan2) entered blocking state
[   29.695811] br-lan: port 1(lan2) entered disabled state
[   29.703741] device lan2 entered promiscuous mode
[   29.714414] mt7530-mdio mdio-bus:1f lan3: configuring for phy/gmii link mode
[   29.724117] br-lan: port 2(lan3) entered blocking state
[   29.729355] br-lan: port 2(lan3) entered disabled state
[   29.736258] device lan3 entered promiscuous mode
[   29.743930] mt7530-mdio mdio-bus:1f lan4: configuring for phy/gmii link mode
[   29.753589] br-lan: port 3(lan4) entered blocking state
[   29.758818] br-lan: port 3(lan4) entered disabled state
[   29.765812] device lan4 entered promiscuous mode
[   29.774228] mt7530-mdio mdio-bus:1f wan: configuring for phy/gmii link mode
[   29.788714] mt7530-mdio mdio-bus:1f wan: Link is Up - 100Mbps/Full - flow control off
[   29.796595] IPv6: ADDRCONF(NETDEV_CHANGE): wan: link becomes ready
[   32.350545] br-lan: port 4(wlan0) entered blocking state
[   32.355889] br-lan: port 4(wlan0) entered disabled state
[   32.361413] device wlan0 entered promiscuous mode
[   35.306951] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   35.313458] br-lan: port 4(wlan0) entered blocking state
[   35.318794] br-lan: port 4(wlan0) entered forwarding state
[   35.324449] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   35.454345] br-lan: port 5(wlan1) entered blocking state
[   35.459734] br-lan: port 5(wlan1) entered disabled state
[   35.465286] device wlan1 entered promiscuous mode
[   35.470125] br-lan: port 5(wlan1) entered blocking state
[   35.475429] br-lan: port 5(wlan1) entered forwarding state
[   36.325648] br-lan: port 5(wlan1) entered disabled state
[   36.624145] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   36.630640] br-lan: port 5(wlan1) entered blocking state
[   36.635964] br-lan: port 5(wlan1) entered forwarding state

**Comment by Turing-China** [comment]
我的重启不会;但是编译好了手机和电脑都找不到WIFI信号

**Comment by smithe-ma** [comment]
@aiamadeus 怎么升级6.1.100，重新编译最新的版本吗？

**Comment by aiamadeus** [comment]
没机子没启动日志修不了，不关这两个 commit 事
又不是我强行更新 6.x 内核的，别一直 at 我。。

**Comment by Turing-China** [comment]
> @Turing-China 2.4和5G一切正常。网络都是好的。就是莫名奇妙重启。我装的东西很少。你也是这个内核和版本吗

@smithe-ma 你重新编译最新内核就是最新的版本  另外我5.5 6.1 6.6内核都试过 全部都是能看到WIFI配置 但是搜索不到WIFI信号;你是云编译的吗?能不能把config 文件发一下；感谢
