### ISSUE TITLE
如何选择openwrt防火墙版本

### ISSUE THREAD

**Issue by lanruihua026** [coolsnowwolf/lede#12424]
### 详细叙述

默认编译出来的是firewall4，但因为特殊需求要切换为firewall3也就是iptable，不然luci-app-firewall不支持编辑自定义iptable规则

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

1

**Comment by yanxin152133** [comment]
https://openwrt.org/zh-cn/doc/uci/firewall
