### ISSUE TITLE
试过几十次了，老是卡在这个地方

### ISSUE THREAD

**Issue by Ikaros520544** [coolsnowwolf/lede#12429]
### 详细叙述

系统：ubuntu24.04LTS
CPU：I7-7700K
内存：24GB

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kmod-drm-kms-helper/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-drm-kms-helper_installed
echo "kmod-drm-kms-helper" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/linux.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp

SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kmod-drm-suballoc-helper/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-drm-suballoc-helper_installed
echo "kmod-drm-suballoc-helper" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/linux.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp

SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kmod-drm-amdgpu/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-drm-amdgpu_installed
echo "kmod-drm-amdgpu" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/linux.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp

SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kmod-drm-i915/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-drm-i915_installed
echo "kmod-drm-i915" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/linux.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp

SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kmod-amd-xgbe/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kmod-amd-xgbe_installed
echo "kmod-amd-xgbe" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/linux.default.install
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/kernel/linux'
time: package/kernel/linux/compile#4.38#0.96#5.49
make[3]: Entering directory '/home/ikaros/桌面/lede/package/system/ubox'
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/ubox-2022-08-13-4c7b720b/.pkgdir/ubox/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.ubox_installed
echo "ubox" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/ubox.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/ubox-2022-08-13-4c7b720b/.pkgdir/getrandom/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.getrandom_installed
echo "getrandom" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/ubox.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/ubox-2022-08-13-4c7b720b/.pkgdir/logd/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.logd_installed
echo "logd" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/ubox.default.install
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/system/ubox'
time: package/system/ubox/compile#0.22#0.10#0.31
make[3]: Entering directory '/home/ikaros/桌面/lede/package/libs/ncurses'
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/libs/ncurses'
time: package/libs/ncurses/host-compile#0.09#0.09#0.17
make[3]: Entering directory '/home/ikaros/桌面/lede/package/libs/zlib'
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/zlib-1.2.13/.pkgdir/zlib/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.zlib_installed
echo "zlib" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/zlib.default.install
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/libs/zlib'
time: package/libs/zlib/compile#0.19#0.10#0.27
make[3]: Entering directory '/home/ikaros/桌面/lede/package/libs/ncurses'
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/ncurses-6.4/.pkgdir/terminfo/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.terminfo_installed
echo "terminfo" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/ncurses.default.install
mkdir -p /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp
echo '6' | cmp -s - /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/libncurses.version || { echo '6' > /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/libncurses.version;  cp /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/libncurses.version /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/libncursesw.version;  } 
SHELL= flock /home/ikaros/桌面/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/ncurses-6.4/.pkgdir/libncurses/. /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.libncurses_installed
echo "libncurses" >> /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/pkginfo/ncurses.default.install
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/libs/ncurses'
time: package/libs/ncurses/compile#0.13#0.10#0.20
make[3]: Entering directory '/home/ikaros/桌面/lede/package/utils/util-linux'
rm -f /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/.configured_*
rm -f /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/stamp/.util-linux_installed
/home/ikaros/桌面/lede/staging_dir/host/bin/sed -e "s|@CC@|'gcc',|" -e "s|@CXX@|'g++',|" -e "s|@PKGCONFIG@|/home/ikaros/桌面/lede/staging_dir/host/bin/pkg-config|" -e "s|@CMAKE@|/home/ikaros/桌面/lede/staging_dir/host/bin/cmake|" -e "s|@PYTHON@|/home/ikaros/桌面/lede/staging_dir/host/bin/python3|" -e "s|@CFLAGS@|'-O2', '-I/home/ikaros/桌面/lede/staging_dir/host/include', '-I/home/ikaros/桌面/lede/staging_dir/hostpkg/include', '-I/home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/host/include', '-I/home/ikaros/桌面/lede/staging_dir/host/include', '-I/home/ikaros/桌面/lede/staging_dir/hostpkg/include', '-I/home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/host/include',|" -e "s|@CXXFLAGS@|'-I/home/ikaros/桌面/lede/staging_dir/host/include', '-I/home/ikaros/桌面/lede/staging_dir/hostpkg/include', '-I/home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/host/include',|" -e "s|@LDFLAGS@|'-L/home/ikaros/桌面/lede/staging_dir/host/lib', '-L/home/ikaros/桌面/lede/staging_dir/hostpkg/lib', '-L/home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/host/lib',|" -e "s|@PREFIX@||" < /home/ikaros/桌面/lede/staging_dir/host/lib/meson/openwrt-native.txt.in > /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-native.txt
/home/ikaros/桌面/lede/staging_dir/host/bin/sed -e "s|@CC@|'x86_64-openwrt-linux-musl-gcc',|" -e "s|@CXX@|'x86_64-openwrt-linux-musl-g++',|" -e "s|@AR@|x86_64-openwrt-linux-musl-gcc-ar|" -e "s|@STRIP@|x86_64-openwrt-linux-musl-strip|" -e "s|@NM@|x86_64-openwrt-linux-musl-gcc-nm|" -e "s|@PKGCONFIG@|/home/ikaros/桌面/lede/staging_dir/host/bin/pkg-config|" -e "s|@CMAKE@|/home/ikaros/桌面/lede/staging_dir/host/bin/cmake|" -e "s|@PYTHON@|/home/ikaros/桌面/lede/staging_dir/host/bin/python3|" -e "s|@CFLAGS@|'-Os', '-pipe', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-fmacro-prefix-map=/home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1=util-linux-2.38.1', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include',|" -e "s|@CXXFLAGS@|'-Os', '-pipe', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-fmacro-prefix-map=/home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1=util-linux-2.38.1', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/include', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include/fortify', '-I/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/include',|" -e "s|@LDFLAGS@|'-L/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib', '-L/home/ikaros/桌面/lede/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib', '-znow', '-zrelro',|" -e "s|@ARCH@|"x86_64"|" -e "s|@CPU@|"generic"|" -e "s|@ENDIAN@|little|" < /home/ikaros/桌面/lede/staging_dir/host/lib/meson/openwrt-cross.txt.in > /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-cross.txt
/home/ikaros/桌面/lede/staging_dir/host/bin/python3 /home/ikaros/桌面/lede/staging_dir/host/bin/meson.py  --buildtype plain --native-file /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-native.txt --cross-file /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-cross.txt -Dsystemd=disabled -Dtinfo=disabled -Dcryptsetup=disabled -Dlibutil=disabled -Dlibutempter=disabled -Dlibpcre2-posix=disabled -Dlibuser=disabled -Duse-tty-group=false -Duse-tls=false -Dbuild-python=disabled -Dbuild-zramctl=disabled -Dbuild-fsck=disabled -Dbuild-wipefs=disabled -Dbuild-fallocate=disabled -Dbuild-setpriv=disabled -Dbuild-hardlink=disabled -Dbuild-cramfs=disabled -Dbuild-bfs=disabled -Dbuild-minix=disabled -Dbuild-fdformat=disabled -Dbuild-lslogins=disabled -Dbuild-wdctl=disabled -Dbuild-cal=disabled -Dbuild-switch_root=disabled -Dbuild-pivot_root=disabled -Dbuild-lsmem=disabled -Dbuild-lsirq=disabled -Dbuild-irqtop=disabled -Dbuild-chmem=disabled -Dbuild-ipcrm=disabled -Dbuild-rfkill=disabled -Dbuild-tunelp=disabled -Dbuild-kill=disabled -Dbuild-last=disabled -Dbuild-utmpdump=disabled -Dbuild-line=disabled -Dbuild-mesg=disabled -Dbuild-raw=disabled -Dbuild-vipw=disabled -Dbuild-newgrp=disabled -Dbuild-chfn-chsh=disabled -Dbuild-login=disabled -Dbuild-nologin=disabled -Dbuild-sulogin=disabled -Dbuild-su=disabled -Dbuild-runuser=disabled -Dbuild-ul=disabled -Dbuild-pg=disabled -Dbuild-write=disabled -Dbuild-bash-completion=disabled -Dbuild-pylibmount=disabled -Dreadline=disabled -Dmagic=disabled -Dncursesw=enabled /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-build /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-build/..
The Meson build system
Version: 0.61.5
Source dir: /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1
Build dir: /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/openwrt-build
Build type: cross build
Project name: util-linux
Project version: 2.38.1
C compiler for the host machine: x86_64-openwrt-linux-musl-gcc (gcc 11.3.0 "x86_64-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r6827-9541a7af4) 11.3.0")
C linker for the host machine: x86_64-openwrt-linux-musl-gcc ld.bfd 2.40.0
C compiler for the build machine: gcc (gcc 13.2.0 "gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0")
C linker for the build machine: gcc ld.bfd 2.42
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: generic
Target machine cpu family: x86_64
Target machine cpu: generic
Dependency bash-completion skipped: feature build-bash-completion disabled
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Checking if "wchar_t support" compiles: YES 
Library m found: YES
Dependency tinfo skipped: feature tinfo disabled
Found pkg-config: /home/ikaros/桌面/lede/staging_dir/host/bin/pkg-config (1.9.3)
Traceback (most recent call last):
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/mesonmain.py", line 148, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 294, in run
    app.generate()
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 185, in generate
    self._generate(env)
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/msetup.py", line 229, in _generate
    intr.run()
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/interpreter.py", line 2554, in run
    super().run()
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 148, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 173, in evaluate_codeblock
    raise e
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 166, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 181, in evaluate_statement
    self.assignment(cur)
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 566, in assignment
    value = self.evaluate_statement(node.value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 179, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/interpreterbase.py", line 454, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 768, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 5 more times]
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 96, in wrapped
    ret = f(*wrapped_args, **wrapped_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 115, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreterbase/decorators.py", line 276, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/interpreter.py", line 1577, in func_dependency
    d = df.lookup(kwargs)
        ^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/dependencyfallbacks.py", line 347, in lookup
    dep = func(kwargs, func_args, func_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/interpreter/dependencyfallbacks.py", line 90, in _do_dependency
    dep = dependencies.find_external_dependency(name, self.environment, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/dependencies/detect.py", line 114, in find_external_dependency
    d = c()
        ^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/dependencies/pkgconfig.py", line 96, in __init__
    self._set_libs()
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/dependencies/pkgconfig.py", line 372, in _set_libs
    ret, out, err = self._call_pkgbin(libcmd, env=env)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/dependencies/pkgconfig.py", line 157, in _call_pkgbin
    cache[(self.pkgbin, targs, fenv)] = self._call_pkgbin_real(args, env)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/dependencies/pkgconfig.py", line 115, in _call_pkgbin_real
    p, out, err = Popen_safe(cmd, env=env)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ikaros/桌面/lede/staging_dir/host/bin/meson.py/mesonbuild/mesonlib/universal.py", line 1397, in Popen_safe
    o, e = p.communicate(write)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 2153, in _communicate
    stdout = self._translate_newlines(stdout,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1086, in _translate_newlines
    data = data.decode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 16: invalid continuation byte

../../../build_dir/target-x86_64_musl/util-linux-2.38.1/meson.build:214:0: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
make[3]: *** [Makefile:878: /home/ikaros/桌面/lede/build_dir/target-x86_64_musl/util-linux-2.38.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 2
make[3]: Leaving directory '/home/ikaros/桌面/lede/package/utils/util-linux'
time: package/utils/util-linux/compile#1.23#0.16#1.42
    ERROR: package/utils/util-linux failed to build.
make[2]: *** [package/Makefile:116: package/utils/util-linux/compile] Error 1
make[2]: Leaving directory '/home/ikaros/桌面/lede'
make[1]: *** [package/Makefile:110: /home/ikaros/桌面/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ikaros/桌面/lede'
make: *** [/home/ikaros/桌面/lede/include/toplevel.mk:231：world] 错误 2
ikaros@Ikaros:~/桌面/lede$

**Comment by science2468** [comment]
https://github.com/science2468/immortalwrt-IB/releases/tag/lede-x64-2024-08-22-04-22-19   现成的

**Comment by rrkai** [comment]
就不能放在纯字母目录......

**Comment by xyz201704** [comment]
目录里不能有中文
