### ISSUE TITLE
编译遇到错误

### ISSUE THREAD

**Issue by aepub** [coolsnowwolf/lede#12441]
### 详细叙述

 系统及机型：22.04.4 LTS (GNU/Linux 6.8.0-40-generic x86_64)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86/64

### 详细日志

+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/rustc-1.78.0-src.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:110: /home/genuo/openwrt/dl/rustc-1.78.0-src.tar.xz] Error 2
make[3]: Leaving directory '/home/genuo/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#0.93#0.67#1453.87
    ERROR: package/feeds/packages/rust [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/rust/host/compile] Error 1
make[2]: Leaving directory '/home/genuo/openwrt'
make[1]: *** [package/Makefile:110: /home/genuo/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/genuo/openwrt'
make: *** [/home/guo/openwrt/include/toplevel.mk:231：world] 错误 2

**Comment by science2468** [comment]
https://github.com/science2468/immortalwrt-IB/releases/tag/lede-x64-2024-09-01-04-23-33    别编译了，用现成的吧
________________________________
发件人: Guo ***@***.***>
发送时间: 2024年9月1日 18:22
收件人: coolsnowwolf/lede ***@***.***>
抄送: Subscribed ***@***.***>
主题: [coolsnowwolf/lede] 编译遇到错误 (Issue #12441)


详细叙述

 系统及机型：22.04.4 LTS (GNU/Linux 6.8.0-40-generic x86_64)

重复 issue

  *    没有类似的 issue

具体型号

x86/64

详细日志

  *   curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/rustc-1.78.0-src.tar.xz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 153 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:110: /home/genuo/openwrt/dl/rustc-1.78.0-src.tar.xz] Error 2
make[3]: Leaving directory '/home/genuo/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#0.93#0.67#1453.87
ERROR: package/feeds/packages/rust [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/rust/host/compile] Error 1
make[2]: Leaving directory '/home/genuo/openwrt'
make[1]: *** [package/Makefile:110: /home/genuo/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/genuo/openwrt'
make: *** [/home/guo/openwrt/include/toplevel.mk:231：world] 错误 2

―

**Comment by science2468** [comment]
那里面不是有sdk嘛，用sdk也能编译插件
________________________________
发件人: Guo ***@***.***>
发送时间: Sunday, September 1, 2024 8:51:28 PM
收件人: coolsnowwolf/lede ***@***.***>
抄送: 山茱萸 ***@***.***>; Comment ***@***.***>
主题: Re: [coolsnowwolf/lede] 编译遇到错误 (Issue #12441)


有些自己用的插件，否则我也不去编译了！

―

**Comment by science2468** [comment]
是你用的插件无法用sdk编译还是没有你用的sdk？
________________________________
发件人: Guo ***@***.***>
发送时间: 2024年9月1日 21:06
收件人: coolsnowwolf/lede ***@***.***>
抄送: 山茱萸 ***@***.***>; Comment ***@***.***>
主题: Re: [coolsnowwolf/lede] 编译遇到错误 (Issue #12441)


我用的SDK还真没有！

―
