### ISSUE TITLE
photonicat

### ISSUE THREAD

**Issue by Namia-A** [coolsnowwolf/lede#12448]
### 详细叙述

6.1.6.6报错不知道能不能解决，在天灵那边能5.1编译

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

photonicat

### 详细日志

![IMG_0259](https://github.com/user-attachments/assets/2208152d-e858-4298-a666-f713f642304e)

**Comment by yanxin152133** [comment]
![image](https://github.com/user-attachments/assets/f60bef72-cdea-4813-8a6b-a7ff465368d5)

**Comment by Namia-A** [comment]
> make V=s -j1
> 
> ![image](https://github.com/user-attachments/assets/f60bef72-cdea-4813-8a6b-a7ff465368d5)
> 
> 

我用的gthub编译的

**Comment by yanxin152133** [comment]
> > make V=s -j1
> > ![image](https://private-user-images.githubusercontent.com/43341537/364606415-f60bef72-cdea-4813-8a6b-a7ff465368d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDY3MDUsIm5iZiI6MTcyNTUwNjQwNSwicGF0aCI6Ii80MzM0MTUzNy8zNjQ2MDY0MTUtZjYwYmVmNzItY2RlYS00ODEzLThhNmItYTdmZjQ2NTM2OGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDAzMjAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMzM3MDczN2YyNDNiYTkwZjhiYjNlOTIzMTc2NWViODk3YmU1MWNhYzAxMGIwMWYzZTk3MzRjYjExYTg0NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrG0yopV_-YUVLj1Fm0286XWVjB1Jq7yKWOVaVM2w2w)
> 
> 我用的gthub编译的

那就先学会Google 或者百度 再来发问题

**Comment by yanxin152133** [comment]
翻了下你的GitHub，没找到有相关的编译记录
![image](https://github.com/user-attachments/assets/db799de0-82ff-4036-80ae-8cb5493ecbe5)

**Comment by Namia-A** [comment]
> 翻了下你的GitHub，没找到有相关的编译记录
> 
> ![image](https://github.com/user-attachments/assets/db799de0-82ff-4036-80ae-8cb5493ecbe5)
> 
> 

抱歉，我原始记录已经删了这个只是最开始的截图，我只是想知道这个错误的原理是什么，我才知道如何去改。

**Comment by Namia-A** [comment]
> > 翻了下你的GitHub，没找到有相关的编译记录
> > 
> > ![image](https://github.com/user-attachments/assets/db799de0-82ff-4036-80ae-8cb5493ecbe5)
> > 
> > 
> 
> 抱歉，我原始记录已经删了这个只是最开始的截图，我只是想知道这个错误的原理是什么，我才知道如何去改。

在求教个问题就是，大雕的群咧，被解散就找不到家了😂
