### ISSUE TITLE
求助大佬，编译成功的X86镜像，在群晖的VMM无法启动

### ISSUE THREAD

**Issue by badgv** [coolsnowwolf/lede#12454]
### 详细叙述

虚拟机启动后卡在这里：
![image](https://github.com/user-attachments/assets/b89ae34b-3c55-4b87-9047-5746bdfd1e0e)

尝试过下面这些镜像，都是卡在这里：
![image](https://github.com/user-attachments/assets/e710f760-f7f0-4040-97ce-7847b46178c0)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

编译成功，没有报错信息，但是编译过程中有如下提示：
![image](https://github.com/user-attachments/assets/80505163-f67b-472f-b392-32ba9c25dd39)

**Comment by badgv** [comment]
忘记说了，上面的镜像是今天刚编译的，机器是群晖920+，J4125的，用去年编译的镜像，在VMM能正常启动

**Comment by zorrose82** [comment]
前面有个帖儿，J4205也是这个问题，把内核由6.6改成6.1，就好了……亲测成功

**Comment by badgv** [comment]
> 前面有个帖儿，J4205也是这个问题，把内核由6.6改成6.1，就好了……亲测成功

谢谢大佬，晚上回去试试

**Comment by badgv** [comment]
> 前面有个帖儿，J4205也是这个问题，把内核由6.6改成6.1，就好了……亲测成功

重新编译了6.1内核的，5.15内核的，都还是这样启动不了，搞不定了。。。

**Comment by badgv** [comment]
> 前面有个帖儿，J4205也是这个问题，把内核由6.6改成6.1，就好了……亲测成功

发现我好像是误解了，以前的OP启动的时候，虚拟机容器会弹一堆东西，现在的OP启动时候，不会弹这些东西，但是等时间长点后，能正常加载网络，所以结论是群晖的VMM还是可以启动的
