### ISSUE TITLE
新版本的固件不能上网,包括6.6.50,6.1.100

### ISSUE THREAD

**Issue by guhill1** [coolsnowwolf/lede#12459]
### 详细叙述

新版本的固件不能上网(国内不能上),架构是x86,包括6.6.50,6.1.100,之前相同配置可以上网,
查看系统日志显示 
kern.info kernel: [   43.820963] ipset[4244]: segfault at 7bd93efe ip.

貌似和turbo acc shortcut FE 或者 kmod-fast-classifier 有关,请大佬看看怎么回事.
现在刷9月8日的版本可以正常上网.

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86-64

### 详细日志

Fri Sep 13 13:56:01 2024 daemon.notice netifd: wan (4176): uci: Entry not found
Fri Sep 13 13:56:01 2024 daemon.notice netifd: wan (4176): sh: out of range
Fri Sep 13 13:56:01 2024 daemon.err odhcp6c[4183]: Failed to send RS (Address not available)
Fri Sep 13 13:56:01 2024 user.notice mwan3[4174]: Using firewall mask 0x3F00
Fri Sep 13 13:56:01 2024 user.notice mwan3[4174]: Max interface count is 60
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.781303] ipset[4229]: segfault at ffffffff92e88f02 ip 00007f5d2488d67a sp 00007ffe92e87718 error 5 in libc.so[7f5d24848000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.782917] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.785783] ipset[4230]: segfault at ffffffff97062f00 ip 00007f9e00eb667a sp 00007ffe97062488 error 5 in libc.so[7f9e00e71000+55000] likely on CPU 1 (core 1, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.788513] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 daemon.info pppd[4204]: Plugin pppoe.so loaded.
Fri Sep 13 13:56:01 2024 daemon.info pppd[4204]: PPPoE plugin from pppd 2.4.9
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.804026] ipset[4242]: segfault at 74ab7efa ip 00007f64c7bb467a sp 00007ffd74ab5fc8 error 4 in libc.so[7f64c7b6f000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.811868] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.815838] ipset[4243]: segfault at 5bceeefd ip 00007fb36183f67a sp 00007fff5bceea68 error 4 in libc.so[7fb3617fa000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.818029] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.820963] ipset[4244]: segfault at 7bd93efe ip 00007fe5f6f6e67a sp 00007ffc7bd937b8 error 4 in libc.so[7fe5f6f29000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.822571] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.825263] ipset[4245]: segfault at ffffffffb24b4eff ip 00007f717c23c67a sp 00007fffb24b3f78 error 5 in libc.so[7f717c1f7000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.826911] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.830192] ipset[4246]: segfault at 5b95aef8 ip 00007f8b0012467a sp 00007ffd5b9593b8 error 4 in libc.so[7f8b000df000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.831929] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.834746] ipset[4248]: segfault at ffffffffcf52bef9 ip 00007f3c352a467a sp 00007fffcf52b188 error 5 in libc.so[7f3c3525f000+55000] likely on CPU 2 (core 2, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.836966] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.840859] ipset[4249]: segfault at ffffffffff2efefc ip 00007fe3912f967a sp 00007ffcff2ee508 error 5 in libc.so[7fe3912b4000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.843722] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.846487] ipset[4250]: segfault at ffffffffc5485efd ip 00007ff3ce5b567a sp 00007fffc5484c58 error 5 in libc.so[7ff3ce570000+55000] likely on CPU 0 (core 0, socket 0)
Fri Sep 13 13:56:01 2024 kern.info kernel: [   43.848582] Code: 8d 14 3e 48 f7 d6 48 21 f2 48 09 d0 4c 85 c8 75 0a 48 83 c3 08 eb d5 48 83 c3 01 0f b6 03 84 c0 74 a0 39 c8 75 f1 eb 9a 31 c0 <0f> b6 0c 07 0f b6 14 06 38 d1 75 0c 48 83 c0 01 84 d2 75 ec 31 c0
Fri Sep 13 13:56:02 2024 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)

**Comment by eearphon** [comment]
root@OpenWrt:~# cat /etc/os-release 
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r6843-82ffc84e2"
OPENWRT_BOARD="x86/64"
OPENWRT_ARCH="x86_64"
OPENWRT_TAINTS="no-all busybox"
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt SNAPSHOT r6843-82ffc84e2"


同样log：
ipset[25428]: segfault at 599e7ef8 ip 00007fc6b4f6267a sp 00007ffe599e6c78 error 4 in libc.so[7fc6b4f1d000+55000] likely on CPU 
3 (core 0, socket 6)

**Comment by eearphon** [comment]
晕，一下子回滚重来这么多啊

**Comment by guhill1** [comment]
> 晕，一下子回滚重来这么多啊

现在编译是没问题了
