### ISSUE TITLE
make menuconfig 时， rootfs -> tar.gz 选项无法生成文件 openwrt-x86-64-generic-rootfs.tar.gz

### ISSUE THREAD

**Issue by nining** [coolsnowwolf/lede#12463]
### 详细叙述

某个版本之前编译时都会生成一个文件系统的tar.gz包：openwrt-x86-64-generic-rootfs.tar.gz
现在发现无论怎么选都没这个文件生成了。另外也不生成了 ext4 的。

···
*** Root filesystem archives ***                                                                                                  
[*] cpio.gz 
[*] tar.gz 
*** Root filesystem images *** 
[*] ext4  --->  
[*] squashfs  --->                          
[*] GZip images
···

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

无任何报错

**Comment by science2468** [comment]
cat .config | grep “ext4”
________________________________
发件人: nining ***@***.***>
发送时间: 2024年9月13日 21:40
收件人: coolsnowwolf/lede ***@***.***>
抄送: Subscribed ***@***.***>
主题: [coolsnowwolf/lede] make menuconfig 时， rootfs -> tar.gz 选项无法生成文件 openwrt-x86-64-generic-rootfs.tar.gz (Issue #12463)


详细叙述

某个版本之前编译时都会生成一个文件系统的tar.gz包：openwrt-x86-64-generic-rootfs.tar.gz
现在发现无论怎么选都没这个文件生成了。另外也不生成了 ext4 的。

・・・
*** Root filesystem archives ***
[] cpio.gz
[] tar.gz
*** Root filesystem images ***
[] ext4 --->
[] squashfs --->
[*] GZip images
・・・

重复 issue

  *    没有类似的 issue

具体型号

x86_64

详细日志

无任何报错

―
