### ISSUE TITLE
make menuconfig找不到r6s了

### ISSUE THREAD

**Issue by wkao2077** [coolsnowwolf/lede#12480]
### 详细叙述

make menuconfig找不到r6s了，之前有

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

friendlyarm_nanopi-r6s

### 详细日志

无

**Comment by lanruihua026** [comment]
我印象当中是只到R5s，R6s这个开发板有点冷门，可以刷istore os

**Comment by wkao2077** [comment]
R6S是R5S的升级款，不冷门，openwrt和iwt的主线快照版本已经支持了，lean的上个月还支持的，我编译过一个版本

**Comment by love-dy** [comment]
希望lean大佬早点支持，准备入手r6s，r4s运行 iwt 总是卡卡的感觉，不光luci2卡，网速也卡，感觉不丝滑，还是lean的丝滑，

**Comment by sijyun** [comment]
已經有支援了. R24.09.09

**Comment by Cathgao** [comment]
> R6S是R5S的升级款，不冷门，openwrt和iwt的主线快照版本已经支持了，lean的上个月还支持的，我编译过一个版本

你编译过你找下commit加回来呗

**Comment by wkao2077** [comment]
试过了，再编译始终报错

估计删除了相关代码

**Comment by coolsnowwolf** [comment]
晚一点回归

**Comment by love-dy** [comment]
惊喜，已经支持h28k了
