### ISSUE TITLE
R2S/R4S 5.15 内核编译失败

### ISSUE THREAD

**Issue by fxxccp** [coolsnowwolf/lede#12486]
### 详细叙述

最近编译R2S/R4S均编译失败，日志中有如下错误信息：
Error: arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi:107.1-5 Label or path gpu not found
Error: arch/arm64/boot/dts/rockchip/rk3568-radxa-e25.dts:110.1-19 Label or path display_subsystem not found
FATAL ERROR: Syntax error parsing input tree

烦请大佬分析原因何在，谢谢！

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

R2S/R4S，5.15内核

### 详细日志

 make[3] -C toolchain/musl compile
 make[3] -C toolchain/gcc/final compile
 make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/workdir/openwrt/scripts/config'
  OBJCOPY arch/arm64/boot/Image
  DTC     arch/arm64/boot/dts/rockchip/rk3568-radxa-e25.dtb
**Error: arch/arm64/boot/dts/rockchip/rk3568-radxa-cm3i.dtsi:107.1-5 Label or path gpu not found
Error: arch/arm64/boot/dts/rockchip/rk3568-radxa-e25.dts:110.1-19 Label or path display_subsystem not found
FATAL ERROR: Syntax error parsing input tree**
make[7]: *** [scripts/Makefile.lib:347: arch/arm64/boot/dts/rockchip/rk3568-radxa-e25.dtb] Error 1
make[6]: *** [scripts/Makefile.build:552: arch/arm64/boot/dts/rockchip] Error 2
make[5]: *** [Makefile:1449: dtbs] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.162'
make[4]: *** [Makefile:26: /workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.162/.modules] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#8.75#4.84#13.46
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

详细日志截图如下，点开图片后再次点击图片可放大：
![logo](https://github.com/user-attachments/assets/ee59341b-c454-4c84-9a11-3aaa994ab169)

**Comment by yanxin152133** [comment]
https://github.com/coolsnowwolf/lede/issues/12367

**Comment by coolsnowwolf** [comment]
本来不想继续支持 5.15 内核了。。。。已修复，转  6.6 吧
