### ISSUE TITLE
i226v网卡无法调整速率到2.5G

### ISSUE THREAD

**Issue by zl827154659** [coolsnowwolf/lede#12484]
### 详细叙述

驱动正常，两个i226v的接口均无法通过ethtool设置speed为2500，但support mode里面又有，设置完之后还是1000M
![image](https://github.com/user-attachments/assets/04fe5f3d-cc04-4d52-ab8c-dc701db0cab6)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

i226-v

### 详细日志

root@OpenWrt:~# dmesg | grep eth0
[   13.462251] igc 0000:06:10.0 eth0: MAC: a8:b8:e0:01:00:27
[   22.706814] igc 0000:06:10.0 eth0: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[   22.946566] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

**Comment by aiamadeus** [comment]
需要 ethtool-full，ethtool 配不了 2.5G

**Comment by zl827154659** [comment]
应该是物理设备原因，光猫不是2.5G，就算强行设置了也会报错。目前内网下的设备已经打通了2.5G
