### ISSUE TITLE
一直出现这个错误是咋回事？

### ISSUE THREAD

**Issue by drw2005** [coolsnowwolf/lede#12528]
### 详细叙述

Lede18.06 内核版本 6.6.54

昨天开始出现大量这个错误

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86-64

### 详细日志

Thu Oct 10 09:52:47 2024 daemon.err odhcp6c[10023]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Thu Oct 10 09:54:45 2024 daemon.err odhcp6c[10023]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Thu Oct 10 09:56:58 2024 daemon.err odhcp6c[10023]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Thu Oct 10 09:59:06 2024 daemon.err odhcp6c[10023]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Thu Oct 10 10:01:14 2024 daemon.err odhcp6c[10023]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)

**Comment by yanxin152133** [comment]
Failed to send SOLICIT message to ff02::1:2 (Permission denied)
复制这句话直接google，看出来的结果哪条适合你
![image](https://github.com/user-attachments/assets/1df37483-c0ba-40e4-8bb9-fce73d1de72c)

**Comment by drw2005** [comment]
> Failed to send SOLICIT message to ff02::1:2 (Permission denied) 复制这句话直接google，看出来的结果哪条适合你 ![image](https://private-user-images.githubusercontent.com/43341537/375932059-1df37483-c0ba-40e4-8bb9-fce73d1de72c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTYwMTUsIm5iZiI6MTcyODcxNTcxNSwicGF0aCI6Ii80MzM0MTUzNy8zNzU5MzIwNTktMWRmMzc0ODMtYzBiYS00MGU0LThiYjktZmNlNzNkMWRlNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZWZhMDJiYjVkNTMzZmU4MGMxZGY4ZGZhNGQ5YzAwZThmNGIzYmI1OTM3NTc0NzUzM2ExZDYwZjUzMGVhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QCJttgkNK3f1eoGQ-s-jR6p6l9xIxQj08Pl9w7KzxsY)

谢谢啦
