### ISSUE TITLE
亚瑟ax1800pro 能编译 能进uboot ，安装不了带factory和recovery

### ISSUE THREAD

**Issue by Potterli20** [coolsnowwolf/lede#12526]
### 详细叙述

亚瑟ax1800pro 能编译 能进uboot ，安装不了带factory和recovery

### 重复 issue

- [ ] 没有类似的 issue

### 具体型号

jdc ax1800pro

### 详细日志

亚瑟ax1800pro 能编译 能进uboot ，安装不了带factory和recovery

uboot的版本是24.05.05
有什么办法呢？
recovery 那个还能亮蓝灯，网口和wifi都不工作
使用默认配置也不行

**Comment by coolsnowwolf** [comment]
和 uboot + gpt 的分区有关

**Comment by coolsnowwolf** [comment]
考虑换个 uboot 吧 ：https://mbd.pub/o/bread/ZJeXk59v
