### ISSUE TITLE
ax6s最新master分支代码编译后无法使用

### ISSUE THREAD

**Issue by Seryta** [coolsnowwolf/lede#12527]
### 详细叙述

基于master分支编译了适用于Redmi AX6S的固件，其中factory刷入时报错`Failed to get erase block status`，这一点根据查询到的资料看，应该是文件太大了，换成官方的即可。

但是刷入`sysupgrade`之后就变砖了，蓝灯常亮但是无法dhcp获取地址无法访问后台，自动获取更上层的地址。

之前使用的是其他人编译的固件，一开始没有问题，直到我没有印象的某一个版本开始出现这种情况（翻了一下240419还可以）。我以为是那个人编译的有问题，直到今天自己编译……

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Redmi AX6S MT7622B

### 详细日志

无

**Comment by 453974158** [comment]
自编译factory.bin用不了可以先刷入openwrt官方的（https://firmware-selector.openwrt.org/），再通过sysupgrade输入自编译固件。
然后就会发现有线接口与5G wifi全都用不了。

**Comment by lztxi** [comment]
可以试试我的方法
1.把 master/target/linux/mediatek/Makefile文件里的 6.1 改成5.15
2.把 master/target/linux/mediatek/dts/mt7622-xiaomi-redmi-router-ax6s.dts 文件替换成 [immortalwrt](https://[raw.githubusercontent.com/immortalwrt/immortalwrt/refs/heads/openwrt-23.05/target/linux/mediatek/dts/mt7622-xiaomi-redmi-router-ax6s.dts](https://raw.githubusercontent.com/immortalwrt/immortalwrt/refs/heads/openwrt-23.05/target/linux/mediatek/dts/mt7622-xiaomi-redmi-router-ax6s.dts))

**Comment by coolsnowwolf** [comment]
6.x 之后内核太大了，超过了小米官方定义的大小
