### ISSUE TITLE
最新的源码更新到24.10.24之后没有适配firewall4防火墙吗？

### ISSUE THREAD

**Issue by wixxm** [coolsnowwolf/lede#12549]
### 详细叙述

如题，更新了新的源码之后第一时间重新编译，但是发现没有对firewall4的支持，还是用不了很多新插件。。。是我设置的问题还是源码没有支持额
![屏幕截图 2024-10-18 133503](https://github.com/user-attachments/assets/a97c8360-e3f3-4411-aac5-12c3d5d35667)
![屏幕截图 2024-10-18 134246](https://github.com/user-attachments/assets/bf8502c6-ea61-4a41-91cf-937b160a6fe2)
![屏幕截图 2024-10-18 133327](https://github.com/user-attachments/assets/5b1ebe50-9aae-47dc-810f-67a4fe47fde5)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86/64

### 详细日志

如题

**Comment by hcym** [comment]
兵荒马乱的，就等等吧
不过我今天编译的正常使用，只有一个haproxy没有luci，基本没影响

**Comment by wixxm** [comment]
> 兵荒马乱的，就等等吧 不过我今天编译的正常使用，只有一个haproxy没有luci，基本没影响

你更新之后编译出来的版本好是多少，我的怎么是24.9.18 不是 24.10.24

**Comment by coolsnowwolf** [comment]
这不还没到 10/24 号嘛~~  目前以更成熟的 fw3 为主， fw4 需要自行选择
