### ISSUE TITLE
autocore-arm 编译失败

### ISSUE THREAD

**Issue by BenjaminX** [coolsnowwolf/lede#12548]
### 详细叙述

最新的分支代码
![SCR-20241018-juhz](https://github.com/user-attachments/assets/6f95674d-3da7-404c-8f85-8aa7df031489)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

R4S

### 详细日志

make[3]: Entering directory '/workdir/openwrt/package/lean/autocore'
rm -rf /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm.installed /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm
mkdir -p /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/etc
install -m0644 ./files/arm/index.htm /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/etc/index.htm
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/etc/uci-defaults
install -m0755 ./files/60-autocore-reload-rpcd /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/etc/uci-defaults/
install -m0755 ./files/arm/090-cover-index_htm /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/etc/uci-defaults/
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/sbin
install -m0755 ./files/arm/sbin/cpuinfo /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/sbin/cpuinfo
install -m0755 ./files/arm/sbin/ethinfo /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/sbin/ethinfo
install -m0755 ./files/arm/sbin/usage /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/sbin/usage
install -m0755 ./files/arm/tempinfo /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm/sbin/tempinfo
install: cannot stat './files/arm/tempinfo': No such file or directory
make[3]: *** [Makefile:81: /workdir/openwrt/build_dir/target-aarch64_generic_musl/autocore-arm/autocore/.pkgdir/autocore-arm.installed] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/lean/autocore'
time: package/lean/autocore/arm/compile#0.20#0.07#0.26
    ERROR: package/lean/autocore failed to build (build variant: arm).
make[2]: *** [package/Makefile:116: package/lean/autocore/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by NaiHeKK** [comment]
好像是L大路径写错了

./files/arm/tempinfo应该是./files/arm/sbin/tempinfo
