### ISSUE TITLE
rust报错

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#12543]
### 详细叙述

rust报错

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x64，armv8

### 详细日志

```bash
2024-10-16T17:52:00.5351586Z make[3]: Entering directory '/mnt/openwrt/feeds/packages/lang/rust'
2024-10-16T17:52:00.6372725Z CARGO_HOME=/home/runner/work/op/op/openwrt/dl/cargo TARGET_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/rust-1.78.0=rust-1.78.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" python3 /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/x.py --build-dir /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/build --config /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/config.toml dist build-manifest cargo llvm-tools rustc rust-std rust-src
2024-10-16T17:52:00.6822295Z ##[group]Building bootstrap
2024-10-16T17:52:00.7325970Z     Finished dev [unoptimized] target(s) in 0.04s
2024-10-16T17:52:00.7360794Z ##[endgroup]
2024-10-16T17:52:00.7444193Z WARNING: The `change-id` is missing in the `config.toml`. This means that you will not be able to track the major changes made to the bootstrap configurations.
2024-10-16T17:52:00.7445470Z NOTE: to silence this warning, add `change-id = 121754` at the top of `config.toml`
2024-10-16T17:52:00.9328017Z downloading https://ci-artifacts.rust-lang.org/rustc-builds/9b00956e56009bab2aa15d7bff10916599e3d6d6/rust-dev-1.78.0-x86_64-unknown-linux-gnu.tar.xz
2024-10-16T17:52:01.3706449Z curl: (22) The requested URL returned error: 404
2024-10-16T17:52:01.3729333Z ERROR: failed to download llvm from ci
2024-10-16T17:52:01.3730083Z 
2024-10-16T17:52:01.3730340Z     HELP: There could be two reasons behind this:
2024-10-16T17:52:01.3731414Z         1) The host triple is not supported for `download-ci-llvm`.
2024-10-16T17:52:01.3732475Z         2) Old builds get deleted after a certain time.
2024-10-16T17:52:01.3733508Z     HELP: In either case, disable `download-ci-llvm` in your config.toml:
2024-10-16T17:52:01.3734155Z 
2024-10-16T17:52:01.3734308Z     [llvm]
2024-10-16T17:52:01.3734756Z     download-ci-llvm = false
2024-10-16T17:52:01.3735228Z     
2024-10-16T17:52:01.3740905Z Build completed unsuccessfully in 0:00:00
2024-10-16T17:52:01.3808192Z make[3]: *** [Makefile:110: /home/runner/work/op/op/openwrt/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/.built] Error 1
2024-10-16T17:52:01.3809289Z make[3]: Leaving directory '/mnt/openwrt/feeds/packages/lang/rust'
```

**Comment by evenwangcn** [comment]
+1

**Comment by wstanfeng** [comment]
+1

**Comment by xjm1285** [comment]
+1

**Comment by SpeedPartner** [comment]
源码链接有问题,都unknow了

**Comment by aiastia** [comment]
同

**Comment by sundog315** [comment]
+1

**Comment by wanansany** [comment]
+1

**Comment by SpeedPartner** [comment]
该更新rust版本了吧

**Comment by lizi99-88** [comment]
我编译京东云亚瑟也出现了同样的错误，rust是个什么东西，有知道的科普一下。

**Comment by hzjnet** [comment]
大家试试这个：RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup install stable

**Comment by xayane** [comment]
> 大家试试这个：RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup install stable 然后设置环境变量： [source.crates-io] replace-with = 'mirror'
> 
> [source.mirror] registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"
> 
> 然后从新登陆再编译

看原理是更改了下载地址。
请问下，云编译的也可以更改这个吗？

**Comment by hzjnet** [comment]
> > 大家试试这个：RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup rustup install stable 然后设置环境变量： [source.crates-io] replace-with = 'mirror'
> > [source.mirror] registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"
> > 然后从新登陆再编译
> 
> 看原理是更改了下载地址。 请问下，云编译的也可以更改这个吗？

云编译就不用更改地址了 缺省就行了； 上面有2个操作：1是更改源地址 2是安装系统的rust语言和设置对应环境，你只需用第二步即可吧

**Comment by evenwangcn** [comment]
SSR+ 不用的话，先去掉，不要编译进去它先。这个是shadowsocks-rust用到

**Comment by hzjnet** [comment]
> 一样的报错 等修复ERROR: package/feeds/packages/rust [host] failed to build.

用我的方法在上面环境配置文件中添加~/.cargo/config.toml错误提示段：
[llvm]
download-ci-llvm = false

完整的配置文件如下：
cat ~/.cargo/config.toml 
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"

[llvm]
download-ci-llvm = false
 未重新登陆，昨晚改好后编译今朝看结果如下：
![image](https://github.com/user-attachments/assets/5f5e6fb9-8566-4168-bc1a-52405833df09)

说明我的方法是可行的，我的环境如下：
ub20ip20:/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ find bin|grep shadowsocksr-libev-ssr|xargs ls -l 
-rw-r--r-- 1 hzjnet hzjnet  3589 Oct 18 18:05 bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocksr-libev-ssr-check_2.5.6-42_arm_cortex-a15_neon-vfpv4.ipk
-rw-r--r-- 1 hzjnet hzjnet 60605 Oct 18 18:05 bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocksr-libev-ssr-local_2.5.6-42_arm_cortex-a15_neon-vfpv4.ipk
-rw-r--r-- 1 hzjnet hzjnet  3004 Oct 18 18:05 bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocksr-libev-ssr-nat_2.5.6-42_arm_cortex-a15_neon-vfpv4.ipk
-rw-r--r-- 1 hzjnet hzjnet 55238 Oct 18 18:05 bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocksr-libev-ssr-redir_2.5.6-42_arm_cortex-a15_neon-vfpv4.ipk
-rw-r--r-- 1 hzjnet hzjnet 64331 Oct 18 18:05 bin/packages/arm_cortex-a15_neon-vfpv4/base/shadowsocksr-libev-ssr-server_2.5.6-42_arm_cortex-a15_neon-vfpv4.ipk

ub20ip20:/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ lsb_release -ra
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

ub20ip20:/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ go env
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/hzjnet/.cache/go-build'
GOENV='/home/hzjnet/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/hzjnet/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/hzjnet/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/snap/go/10719'
GOSUMDB='sum.golang.google.cn'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/10719/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.8'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3665132178=/tmp/go-build -gno-record-gcc-switches'
hzjnet@ub20ip20:/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ cargo -V
cargo 1.81.0 (2dbb1af80 2024-08-20)

ub20ip20:/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ cmake --version
cmake version 3.30.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

/openwrt/openwrt-lede-cools-M-down-20241018-2-ipq806x$ clang --version
Ubuntu clang version 18.1.8 (++20240731025011+3b5b5c1ec4a3-1~exp1~20240731145104.143)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by NaiHeKK** [comment]
云编译在build前面加上可正常编译
```    - name: Fix Rust
      run: |
        cd openwrt
        sed -i 's/--set=llvm.download-ci-llvm=true/--set=source.crates-io.replace-with=mirror \\\
        --set=source.mirror.registry=sparse+https:\/\/mirrors.bfsu.edu.cn\/crates.io-index\/ \\\
        --set=llvm.download-ci-llvm=false/' package/feeds/packages/rust/Makefile
```

**Comment by binge8** [comment]
> 云编译在build前面加上可正常编译
> 
> ```
>       run: |
>         cd openwrt
>         sed -i 's/--set=llvm.download-ci-llvm=true/--set=source.crates-io.replace-with=mirror \\\
>         --set=source.mirror.registry=sparse+https:\/\/mirrors.bfsu.edu.cn\/crates.io-index\/ \\\
>         --set=llvm.download-ci-llvm=false/' package/feeds/packages/rust/Makefile
> ```

我怎么咋看咋觉得你是来误人子弟的，你自己亲测过能行？

**Comment by NaiHeKK** [comment]
> > 云编译在build前面加上可正常编译
> > ```
> >       run: |
> >         cd openwrt
> >         sed -i 's/--set=llvm.download-ci-llvm=true/--set=source.crates-io.replace-with=mirror \\\
> >         --set=source.mirror.registry=sparse+https:\/\/mirrors.bfsu.edu.cn\/crates.io-index\/ \\\
> >         --set=llvm.download-ci-llvm=false/' package/feeds/packages/rust/Makefile
> > ```
> 
> 我怎么咋看咋觉得你是来误人子弟的，你自己亲测过能行？

![image](https://github.com/user-attachments/assets/9a5d1cd9-e5ce-4feb-84f2-d7dc64db2353)

**Comment by NaiHeKK** [comment]
> > 云编译在build前面加上可正常编译
> > ```
> >       run: |
> >         cd openwrt
> >         sed -i 's/--set=llvm.download-ci-llvm=true/--set=source.crates-io.replace-with=mirror \\\
> >         --set=source.mirror.registry=sparse+https:\/\/mirrors.bfsu.edu.cn\/crates.io-index\/ \\\
> >         --set=llvm.download-ci-llvm=false/' package/feeds/packages/rust/Makefile
> > ```
> 
> 我怎么咋看咋觉得你是来误人子弟的，你自己亲测过能行？

所以你把这玩意放哪了

**Comment by NaiHeKK** [comment]
> > 云编译在build前面加上可正常编译
> > ```
> >       run: |
> >         cd openwrt
> >         sed -i 's/--set=llvm.download-ci-llvm=true/--set=source.crates-io.replace-with=mirror \\\
> >         --set=source.mirror.registry=sparse+https:\/\/mirrors.bfsu.edu.cn\/crates.io-index\/ \\\
> >         --set=llvm.download-ci-llvm=false/' package/feeds/packages/rust/Makefile
> > ```
> 
> 我怎么咋看咋觉得你是来误人子弟的，你自己亲测过能行？

还是说你压根就没试？

**Comment by coolsnowwolf** [comment]
修复了

**Comment by lovestudygithub** [comment]
> [@hzjnet](https://github.com/hzjnet) 我终于知道你这个怎么用了 ，我这个小白找了半天路径 /home/用户名/HomeLede/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/Cargo.toml 在这个里面 直接添加就行 另外 /home/用户名/HomeLede/build_dir/target-x86_64_musl/host/rustc-1.78.0-src/config.toml里面的download-ci-llvm = true 也要改 false

编译immortalwrt时也碰到这个问题了，也是修改/home/tony/immortalwrt/build_dir/target-x86_64_musl/host/rustc-1.xx.x-src/路径下面的Cargo.toml和config.toml，Cargo.toml里面在第一行插入：
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.bfsu.edu.cn/crates.io-index/"

[llvm]
download-ci-llvm = false

原来的行下移。

修改config.toml:
[llvm]

# Currently, we only support this when building LLVM for the build triple.
#
# Note that many of the LLVM options are not currently supported for
# downloading. Currently only the "assertions" option can be toggled.
download-ci-llvm = true
改成：
[llvm]

# Currently, we only support this when building LLVM for the build triple.
#
# Note that many of the LLVM options are not currently supported for
# downloading. Currently only the "assertions" option can be toggled.
download-ci-llvm = false

修改是给小白的，大神略过。

非常感谢@hzjnet和@mylove3385两个大兄弟！！！
