### ISSUE TITLE
防火墙没拦截wan6方向访问设备80 443端口

### ISSUE THREAD

**Issue by yanzhx7** [coolsnowwolf/lede#12558]
### 详细叙述

设备rax3000m，默认ipv6配编译，测试发现防火墙没拦截wan6方向访问设备80 443端口，防火墙默认禁止wan入站，也没有开放443 80端口，
同样配置编译r3g固件，防火墙也没拒绝wan6方向访问设备80 443.

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rax3000m

### 详细日志

无

**Comment by TaneikaMacedo** [comment]
18 sec ago Mujib Zalmay ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media. ◉Free(✧VIDEO𝕊✧ＸＸＸ✧𝙵𝚞𝚕𝚕 ORIGINAL)◉ One Girl one Frog Viral ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ Update LINK On Social Media 𝕏𝘛𝘸𝘪𝘵𝘵𝘦𝘳

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://nowviral.pages.dev/?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://nowviral.pages.dev/?vidzm4)

Mujib Zalmay's latest video has taken the internet by storm, sparking lively discussions across various social media platforms. The rising digital influencer, known for her captivating content—especially her recent Spiderman-themed video—has experienced a massive surge in popularity. Fans are eagerly awaiting the full version, while audiences flock to Instagram, X (formerly Twitter), and Discord to engage with her latest creation.

As excitement continues to grow, fans are actively sharing their thoughts online, highlighting the crucial role social media plays in propelling creators like Mujib Zalmay into the spotlight. With her unique style and creative approach, she has made a significant impact on the digital scene, leaving fans excited for what’s to come next. The viral success of her video further underscores the power of social media in boosting visibility and fostering stronger connections between creators and their audiences.

.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
10 sec ago Mujib Zalmay ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media. ★(ＮＯＷ~𝐅𝐔𝐋𝐋*:.VIDEO𝕊) Mujib Zalmay Viral ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ Update Files Trending On Social Media X Telegram

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://nowviral.pages.dev/?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://nowviral.pages.dev/?vidzm4)


Mujib Zalmay's latest video has taken the internet by storm, sparking lively discussions across various social media platforms. The rising digital influencer, known for her captivating content—especially her recent Spiderman-themed video—has experienced a massive surge in popularity. Fans are eagerly awaiting the full version, while audiences flock to Instagram, X (formerly Twitter), and Discord to engage with her latest creation.

As excitement continues to grow, fans are actively sharing their thoughts online, highlighting the crucial role social media plays in propelling creators like Mujib Zalmay into the spotlight. With her unique style and creative approach, she has made a significant impact on the digital scene, leaving fans excited for what’s to come next. The viral success of her video further underscores the power of social media in boosting visibility and fostering stronger connections between creators and their audiences.

.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
