### ISSUE TITLE
编译完成ssh连接固件的时候提示-ash: /usr/bin/zsh: not found

### ISSUE THREAD

**Issue by wixxm** [coolsnowwolf/lede#12559]
### 详细叙述

![屏幕截图 2024-10-20 145159](https://github.com/user-attachments/assets/8f43ff62-da57-46ad-831b-48af9cd07762)
如题使用ssh连接的时候有这样一个提醒，是哪个设置有问题嘛？ 会影响系统运行吗？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86/64

### 详细日志

如题

**Comment by aiamadeus** [comment]
很明显你的固件把默认 sh 改了
