### ISSUE TITLE
新版luci，upnp插件ip不显示

### ISSUE THREAD

**Issue by 1105384898** [coolsnowwolf/lede#12554]
### 详细叙述

![QQ20241019-091901](https://github.com/user-attachments/assets/9a50349d-e2bf-4316-8e8e-c5fa386ac519)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

![Uploading QQ20241019-092353.png…]()

**Comment by 1105384898** [comment]
![Uploading QQ20241019-092353.png…]()

**Comment by DanielChen008** [comment]
请教：这是选择哪个主题的 Luci ？

**Comment by 1105384898** [comment]
> 请教：这是选择哪个主题的 Luci ？

argon啊

**Comment by DanielChen008** [comment]
> > 请教：这是选择哪个主题的 Luci ？
> 
> argon啊

感谢，我昨晚编译选择的是用了几年的那个 NetGear 主题，刷固件后发现主题崩了，今晚回家用这个主题试试。

**Comment by 1105384898** [comment]
> > > 请教：这是选择哪个主题的 Luci ？
> > 
> > 
> > argon啊
> 
> 感谢，我昨晚编译选择的是用了几年的那个 NetGear 主题，刷固件后发现主题崩了，今晚回家用这个主题试试。

没事，现在应该只有默认或者argon可以，更新了luci2老的主题不兼容了

**Comment by Azbuzz** [comment]
能解决吗

**Comment by trainSu** [comment]
同样的问题

**Comment by coffeelb** [comment]
同样的问题，但是这个UPNP有生效吗，如果有生效但是不显示也无所谓了

**Comment by coffeelb** [comment]
> 没生效

是的，我也测试了没生效

**Comment by XinSSS** [comment]
新版本这个插件好像失效了。
不知道会不会修哎😮‍💨
