### ISSUE TITLE
请教各位大佬，新版luci中如何启用wireguard

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#12551]
### 详细叙述

拉取最新源码默认采用23.05的luci，请教各位应该如何启用wireguard
@coolsnowwolf 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

同上

**Comment by YEYEv50** [comment]
LuCI , Protocols , 倒数第二 luci-proto-wireguard........................... Support for WireGuard VPN

**Comment by bi4tms** [comment]
> LuCI , Protocols , 倒数第二 luci-proto-wireguard........................... Support for WireGuard VPN

感谢
