### ISSUE TITLE
编译后的产物是空文件

### ISSUE THREAD

**Issue by ncswwxb74** [coolsnowwolf/lede#12567]
### 详细叙述

可以编译但是编译后的文件拿出来刷不上，去tridnet看了一下结果99.9%是null bytes，我想意思应该就是保存了空文件。并且三个文件一起压缩了一下只剩85kb了。
make menuconfig的时候只调了target system、subtarget、target profile。
![image](https://github.com/user-attachments/assets/2d01c27f-283e-4887-9eb1-89c0a8ab3bea)
是还需要调些什么吗？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

京东云亚瑟

### 详细日志

编译应该是成功了的。

**Comment by coolsnowwolf** [comment]
rm -rf bin 重新生成

**Comment by ncswwxb74** [comment]
只删bin/的话好像编译速度很快，但结果还是空文件

**Comment by ncswwxb74** [comment]
编译ax1800pro在make menuconfig时除了target system、subtarget、target profile以外有什么必选项吗

**Comment by coolsnowwolf** [comment]
没有了

**Comment by ncswwxb74** [comment]
那么该怎么解决这个问题呢，需要我打包一下发给你吗？
实际上我也就只改了make menuconfig里面关于选择固件的三个选项啊。
