### ISSUE TITLE
新版好多apk不兼容，请问有没有老版本镜像可编译呢？

### ISSUE THREAD

**Issue by wstanfeng** [coolsnowwolf/lede#12568]
### 详细叙述

新版好多apk不兼容，请问有没有老版本镜像可编译呢？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

暂无日志

**Comment by xingshu1990** [comment]
是不是6.6内核？
自行改/home/wpc/lede/target/linux/【自己需要的架构】/Makefile中的KERNEL_PATCHVER:=
这个是内核版本，限定到6.6 或者6.1版本编译后试试。
