### ISSUE TITLE
系统几个使用问题请教

### ISSUE THREAD

**Issue by smithe-ma** [coolsnowwolf/lede#12563]
### 详细叙述

今天编译了最近的X86 OP。在6口物理机中使用，有几个小问题。1、第一次通过页面进入系统，系统默认eth0为br-lan，WAN口为eth1。我在系统里修改WAN口为eth5,wan6也同步改为eth5。在系统端口状态还是只显示eth0,eht1，别的网口插上网线正常使用，也不会显示，永远只显示eth0和eth1。2、系统页面没有物理网口绑定修改，百度后才知道在network配置文件里修改。不知道是取消了，还是我没有找到。
请大神指点。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

| OpenWrt R24.9.18 / LuCI openwrt-23.05 branch git-24.293.38472-3c6a9fd

### 详细日志

型号 | Default string Default string/Default string - Intel(R) Celeron(R) CPU 4205U @ 1.80GHz : 2C2T
架构 | 1100.000 MHz +44.0°C (high = +100.0°C, crit = +100.0°C) +43.0°C (high = +100.0°C, crit = +100.0°C)
目标平台 | x86/64
固件版本 | OpenWrt R24.9.18 / LuCI openwrt-23.05 branch git-24.293.38472-3c6a9fd
内核版本 | 6.6.56

**Comment by TaneikaMacedo** [comment]
18 sec ago Mujib Zalmay ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media. ◉Free(✧VIDEO𝕊✧ＸＸＸ✧𝙵𝚞𝚕𝚕 ORIGINAL)◉ Mujib Zalmay Viral ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ Update LINK On Social Media 𝕏𝘛𝘸𝘪𝘵𝘵𝘦𝘳

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://nowviral.pages.dev/?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://nowviral.pages.dev/?vidzm4)

Mujib Zalmay's latest video has taken the internet by storm, sparking a wave of excitement and discussion across social media platforms. The rising digital influencer, known for her captivating and creative content—especially her recent Spiderman-themed video—has experienced an explosive surge in popularity. Fans are eagerly awaiting the full version, while viewers flock to Instagram, X (formerly Twitter), and Discord to share reactions and engage with her latest masterpiece.

The overwhelming buzz surrounding the video highlights the massive role social media plays in propelling creators like Mujib Zalmay into the limelight. With her fresh approach and unique style, she has not only captured attention but also inspired countless fans. This viral success serves as a powerful reminder of how social media can amplify visibility and deepen the connection between creators and their audiences.

With such a major hit on her hands, fans are left eagerly anticipating what Mujib has in store next—knowing it will undoubtedly be another game-changer!
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

10 sec ago Mujib Zalmay ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media. ★(ＮＯＷ~𝐅𝐔𝐋𝐋*:.VIDEO𝕊) Mujib Zalmay Viral ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ Update Files Trending On Social Media X 𝕏𝘛𝘸𝘪𝘵𝘵𝘦𝘳

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://nowviral.pages.dev/?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://nowviral.pages.dev/?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://nowviral.pages.dev/?vidzm4)


Mujib Zalmay's latest video has taken the internet by storm, sparking a wave of excitement and discussion across social media platforms. The rising digital influencer, known for her captivating and creative content—especially her recent Spiderman-themed video—has experienced an explosive surge in popularity. Fans are eagerly awaiting the full version, while viewers flock to Instagram, X (formerly Twitter), and Discord to share reactions and engage with her latest masterpiece.

The overwhelming buzz surrounding the video highlights the massive role social media plays in propelling creators like Mujib Zalmay into the limelight. With her fresh approach and unique style, she has not only captured attention but also inspired countless fans. This viral success serves as a powerful reminder of how social media can amplify visibility and deepen the connection between creators and their audiences.

With such a major hit on her hands, fans are left eagerly anticipating what Mujib has in store next—knowing it will undoubtedly be another game-changer!
.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

**Comment by smithe-ma** [comment]
再请教一个问题。我在网上买了第三方生产的mt7621A设备，5个端口，16M闪存，256内存。厂家默认刷的17版本的原厂的openwrt。现在我在编译的时候，没法编译出来update的固件。只有一个内核部件。我不知道是不是我编译的插件多了，还是怎么回事。另外，那个kernel
part size 和 root filesystem size设置多大。

coolsnowwolf ***@***.***> 於 2024年11月20日週三 下午1:58寫道：
