### ISSUE TITLE
關於LEDE路由器的透明代理

### ISSUE THREAD

**Issue by PoorerImmune** [coolsnowwolf/lede#1257]
我已經啟用了ShadowsocksR Plus，但是設定之後並沒有起到代理的效果，我是不是還有什麼設定工作沒做，比如防火牆什麼的（我不懂iptables）。
我的需求是在該路由器上做一個透明代理，讓區域網路內的所有流量均由代理程式決定是否走代理通道。
![嚙誕歹蕭 1](https://user-images.githubusercontent.com/48857142/57095746-25c02b00-6d46-11e9-91cb-2417a5eb1bf2.png)
![嚙誕歹蕭 2](https://user-images.githubusercontent.com/48857142/57095750-29ec4880-6d46-11e9-94f3-250922e633c8.png)

**Comment by BROBIRD** [comment]
检查下你自己的SSR连接是否正常
