### ISSUE TITLE
这个固件支持mt7620的无线hwnat吗

### ISSUE THREAD

**Issue by e0r** [coolsnowwolf/lede#12570]
### 详细叙述

我发现7620可以用bonding突破100M网口的限制，可惜官方openwrt没无线hwnat，老毛子又有bug没能解决
不知道这个固件支持mt7620的无线hwnat吗

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

K1

### 详细日志

www

**Comment by aiamadeus** [comment]
7620 7621 都没有无线 hwnat
