### ISSUE TITLE
新版的DDNS不太正常

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#12586]
### 详细叙述

设置DDNS的时候显示没有安装服务
<img width="1331" alt="Screenshot 2024-10-23 at 12 21 37 AM" src="https://github.com/user-attachments/assets/72a4f272-703c-44bf-aa46-b129a83d457c">

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86 软路由 云编译

### 详细日志

没有编译错误日志

**Comment by Jason6111** [comment]
需要手动在安装列表 对吧 我以为是我一人的问题呢

**Comment by xeyesen** [comment]
我的也是这样，之前的配置能运行，就是点修改啥都改不了，ddns供应商空的

**Comment by drw2005** [comment]
同样的情况，都已正常安装，但是没有DDNS服务。
这个有没有解决办法啊？用不了啦！

**Comment by Jason6111** [comment]
> 同样的情况，都已正常安装，但是没有DDNS服务。 这个有没有解决办法啊？用不了啦！

软件列表 刷新 然后搜cloudflare 手动安装下ddns-scripts-cloudflare 先这么用都后续L大修复呗

**Comment by drw2005** [comment]
> > 同样的情况，都已正常安装，但是没有DDNS服务。 这个有没有解决办法啊？用不了啦！
> 
> 软件列表 刷新 然后搜cloudflare 手动安装下ddns-scripts-cloudflare 先这么用都后续L大修复呗

谢谢指点。

**Comment by drw2005** [comment]
> > 同样的情况，都已正常安装，但是没有DDNS服务。 这个有没有解决办法啊？用不了啦！
> 
> 软件列表 刷新 然后搜cloudflare 手动安装下ddns-scripts-cloudflare 先这么用都后续L大修复呗

发现服务列表里找不到aliyun，明明ddns-scripts_aliyun 1.0.3-1已经安装了。

**Comment by Jason6111** [comment]
> > > 同样的情况，都已正常安装，但是没有DDNS服务。 这个有没有解决办法啊？用不了啦！
> > 
> > 
> > 软件列表 刷新 然后搜cloudflare 手动安装下ddns-scripts-cloudflare 先这么用都后续L大修复呗
> 
> 发现服务列表里找不到aliyun，明明ddns-scripts_aliyun 1.0.3-1已经安装了。

我把官方的ddns那个挪过来在测试了

**Comment by evenwangcn** [comment]
+1，同样的问题，ddns-scripts没有安装，要手动安装。等L大修复。
