### ISSUE TITLE
雷神加速器编译不出中文包

### ISSUE THREAD

**Issue by l4326769** [coolsnowwolf/lede#12585]
### 详细叙述

编译luci-app-leigod-acc,无法编译出luci-i18n-leigod-acc-zh-cn

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rk3399

### 详细日志

无

**Comment by l4326769** [comment]
docker只有配置一栏，而且只有几个按钮

**Comment by l4326769** [comment]
把feeds中的luci包，从2305切换回主线，修复了这个问题

**Comment by miaoermua** [comment]
> 把feeds中的luci包，从2305切换回主线，修复了这个问题

要等 lean 修，另外使用雷神加速器插件建议搭配雷神管理器使用，目前仓库里面还是 pre 版本，不建议使用，最近雷神那边貌似有新版本修复了一些问题，我这里会对接一下
