### ISSUE TITLE
登录后多个页面js报错

### ISSUE THREAD

**Issue by jixuuse** [coolsnowwolf/lede#12584]
### 详细叙述

![图片](https://github.com/user-attachments/assets/30a384bd-6bd4-4ba6-a6a1-1c28ac8caa8a)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

没有

**Comment by DanielChen008** [comment]
昨晚编译后发现用了好几年的 NetGear 主题崩了，变成完全不认识的样子…

**Comment by coolsnowwolf** [comment]
luci js 没啥主题可用的，和老的都不兼容

**Comment by coolsnowwolf** [comment]
![image](https://github.com/user-attachments/assets/96c5177b-7ead-4fbf-8963-13f5794ba16e)
make clean 后编译，别选其他主题

**Comment by oyksoft** [comment]
原主题都失效了啊？
