### ISSUE TITLE
mt7925网卡如何配置双频宽并发

### ISSUE THREAD

**Issue by IDeLoveYou** [coolsnowwolf/lede#12590]
### 详细叙述

我查看了openwrt的mt76仓库的commit记录，发现添加了对mt7925网卡 mol 的支持，但我对这块不是很了解。麻烦指点一下，我该如何配置才能使用 mol 呢，我想同时走2.4ghz和5ghz。

我改了 /etc/confg/wireless 文件，但依旧只能使用一个频宽，即使是双频宽双 ssid 也不行。
以下是我改的 wireless 文件，麻烦指点一下。

```

config wifi-device 'radio0'
	option type 'mac80211'
	option path '3c0000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option channel '36'
	option band '5g'
	option country 'US'
	option legacy_rates '1'
	option mu_beamformer '0'
	option htmode 'HE160'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'

config wifi-device 'radiox0'
	option type 'mac80211'
	option path '3c0000000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0'
	option country 'US'
	option legacy_rates '1'
	option mu_beamformer '0'
	option band '2g'
	option channel 'auto'
	option htmode 'HE80'

config wifi-iface 'default_radiox0'
	option device 'radiox0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt1'
	option encryption 'none'

```

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

mt7925网卡

### 详细日志

无

**Comment by aiamadeus** [comment]
支持 mlo 没那么简单，要 mac80211 和 host apd 也支持，也就是说现在还不支持。

**Comment by IDeLoveYou** [comment]
> 支持 mlo 没那么简单，要 mac80211 和 hostapd 也支持，也就是说现在还不支持。

那请问现在支持双频宽吗，我家老的设备需要走 2.4ghz

**Comment by IDeLoveYou** [comment]
想请问一下这张网卡是不支持同时使用2.4ghz和5ghz两个频宽吗，现在家里的智能音响连不上wifi，换成2.4ghz又感觉没有5ghz快

**Comment by aiamadeus** [comment]
不支持 dbdc，你就不能搞个路由器么，别为难一个笔记本网卡了。。。

**Comment by IDeLoveYou** [comment]
> 不支持 dbdc，你就不能搞个路由器么，别为难一个笔记本网卡了。。。

好的，那我换一张网卡吧，我入手了一张 mt7916，但我不清楚它支不支持蓝牙，我想换一张支持 2.4ghz 和 5ghz 双频并发还有蓝牙的网卡，请问有什么推荐的吗，想买一张好一点的
