### ISSUE TITLE
新版luci phtunnel运行出错！

### ISSUE THREAD

**Issue by dghuig** [coolsnowwolf/lede#12591]
### 详细叙述

新版luci phtunnel运行后点选状态显示以下错误！！
Bad Gateway
The process did not produce any response

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

AArch64

### 详细日志

Bad Gateway
The process did not produce any response

**Comment by dghuig** [comment]
用旧版本的Luci编译就正常！

**Comment by mygithub1981** [comment]
我也一样的情况
