### ISSUE TITLE
Could you plz sync with upstream to fix the KRACK Vul.?

### ISSUE THREAD

**Issue by kmahyyg** [coolsnowwolf/lede#126]
https://github.com/lede-project/source/commit/2f701194c29da50bfda968a83c6609843f74a7f4

https://github.com/lede-project/source/commit/2127425434046ae2b9f02fdbbdd37cac447af19c

https://github.com/lede-project/source/commit/c5f97c9372da3229350184fb263c97d9ea8944c5

Please get sync with upstream to help users prevent from attacking.
I'm so glad to use your LEDE firmware.

Thanks a lot.

**Comment by coolsnowwolf** [comment]
already update
