### ISSUE TITLE
新版luci没有 文件传输 

### ISSUE THREAD

**Issue by pata166** [coolsnowwolf/lede#12609]
### 详细叙述

之前默认的插件不兼容嘛？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

同上

**Comment by pata166** [comment]
luci-app-filetransfer

**Comment by guochan2019** [comment]
新版貌似已经不需要这个了，在软件包界面，直接可以上传并安装

**Comment by coolsnowwolf** [comment]
正解

**Comment by coolsnowwolf** [comment]
![image](https://github.com/user-attachments/assets/6b3c585a-7269-438e-994f-d994e149ebce)
