### ISSUE TITLE
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist

### ISSUE THREAD

**Issue by cgbb0** [coolsnowwolf/lede#12602]
### 详细叙述

环境：阿里云轻量服务器，debian11
完全按照readme全新安装，有很多类似报错
不仅是我的服务器，在P3TERX的action里也有一样的报错，甚至内容一模一样
![image](https://github.com/user-attachments/assets/6d90f103-c4be-44ee-affb-614eab6f4679)
![image](https://github.com/user-attachments/assets/319eb8ed-e97e-4021-a8f1-e1a95f6e6987)
[xsh281D.tmp.txt](https://github.com/user-attachments/files/17529854/xsh281D.tmp.txt)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'pciutils', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba4', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'wget-ssl', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'wget-ssl', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/qat/libs/eudev/Makefile' has a dependency on 'libkmod', which does not exist
WARNING: Makefile 'package/qat/libs/eudev/Makefile' has a build dependency on 'gperf/host', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/libs/libselinux/Makefile' has a dependency on 'libpcre2', which does not exist
WARNING: Makefile 'package/libs/libselinux/Makefile' has a build dependency on 'pcre2/host', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-gobinetmodem/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'miniupnpd', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'conntrack', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'conntrackd', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'jq', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-leigod-acc/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a dependency on 'pciutils', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-pcimodem/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-spdmodem/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a dependency on 'luci-lua-runtime', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a build dependency on 'csstidy/host', which does not exist
WARNING: Makefile 'package/wwan/app/luci-app-usbmodem/Makefile' has a build dependency on 'luasrcdiet/host', which does not exist
WARNING: Makefile 'package/lean/mt/drivers/mt7615d/Makefile' has a dependency on 'maccalc', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libtins', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libyaml-cpp', which does not exist
WARNING: Makefile 'package/lean/pcat-manager/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/pcat-manager/Makefile' has a dependency on 'libgpiod', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/firmware/quantenna/Makefile' has a dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/firmware/quantenna/Makefile' has a build dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/wwan/driver/quectel_MHI/Makefile' has a dependency on 'pciids', which does not exist
WARNING: Makefile 'package/wwan/driver/quectel_MHI/Makefile' has a dependency on 'pciutils', which does not exist
WARNING: Makefile 'package/network/services/samba36/Makefile' has a dependency on 'libaio', which does not exist
Installing all packages from feed packages.

**Comment by superabbite1** [comment]
我也这个问题

**Comment by bluecoast-sj** [comment]
is your project  copy from other?
