### ISSUE TITLE
瑞莎E20C编译(23.05 luci）选择luci-app-dockerman后，编译出来并没有带docker

### ISSUE THREAD

**Issue by zlxyc** [coolsnowwolf/lede#12605]
### 详细叙述

1、瑞莎E20C编译（23.05 luci）选择luci-app-dockerman后，编译出来并没有带docker,仅仅只是有了luci-app-dockerman。点开dockerman只有配置选项，而且配置选项是空白的。

2、而手动安装docker后。扩容docker分区，在挂载点那里，也没有“作为 Docker 数据分区使用"这个选项

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

瑞莎E20C

### 详细日志

无

**Comment by xingshu1990** [comment]
1、瑞莎E20C编译选择luci-app-dockerman后，编译出来并没有带docker,仅仅只是有了luci-app-dockerman。点开dockerman只有配置选项，而且配置选项是空白的。

2、而手动安装docker后。扩容docker分区，在挂载点那里，也没有“作为 Docker 数据分区使用"这个选项

——————
第一个问题：应该是选中的luci-app-dockerman没有带docker-ce（docker内核），原先我编译docker的时候也试过。
后来用的是其他软件仓库，见https://github.com/kenzok8/small/issues/148（双仓库一键命令）

第二个问题：较为方便的方法是，使用diskman直接扩容并转格式，然后用挂载点挂载。
另如果是程序编译出来的dockerman，自动创建挂载/opt/docker.
