### ISSUE TITLE
默认ntp服务器time.ustc.edu.cn是挂的

### ISSUE THREAD

**Issue by qwerttvv** [coolsnowwolf/lede#12601]
### 详细叙述

time.ustc.edu.cn
在联通和移动都不可用，电信和教育网未知

还有 ntp.ntsc.ac.cn 这个垃圾三天两头挂，而且换过几次运营商了

建议ntp如下

cn.pool.ntp.org
ntp.neu.edu.cn
ntp.aliyun.com
ntp.tencent.com

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

non

### 详细日志

non

**Comment by aiamadeus** [comment]
![image](https://github.com/user-attachments/assets/92c3b939-e9c2-41ad-ab19-3257cc65d0b4)
不是有 ntp1.aliyun.com 和 ntp.tencent.com 吗
这个是按顺序的，有个挂了也不影响
cn.pool.ntp.org 是最垃圾的。。
