### ISSUE TITLE
大雕修完的DDNS插件获取接口有点问题

### ISSUE THREAD

**Issue by ostrichii** [coolsnowwolf/lede#12603]
### 详细叙述

![屏幕截图 2024-10-27 113810](https://github.com/user-attachments/assets/610246e4-6bea-4b67-a5b0-14386fd98efd)
选择IP来源为接口的时候，无法读取接口列表

### 重复 issue

- [x] 没有类似的 issue

### 具体型号

x86

### 详细日志

无需日志

**Comment by coolsnowwolf** [comment]
OK，待修复

**Comment by ostrichii** [comment]
再补充一个问题
![image](https://github.com/user-attachments/assets/8db23170-1518-47b4-b79e-b505c3b195e6)
