### ISSUE TITLE
编译包含SoftEtherVPN的固件时报错镜像无效且无法访问

### ISSUE THREAD

**Issue by CarterJimmy** [coolsnowwolf/lede#1260]
make menuconfig时选中了SoftEtherVPN Bridge，Server以及client。然而编译过程中报错404。
  随后重新编辑menuconfig，只选中SoftEther Server并预先下载源码（`make download V=s`),然而还是报错404。复制链接至浏览器后确认为无效链接。
  希望可以更新一下相关地址，或者给出解决方案谢谢。
![图像 2019-5-3，12 53](https://user-images.githubusercontent.com/7923743/57122491-a4ee4700-6db8-11e9-8b90-3c754ea668ed.JPG)
![图像 2019-5-3，14 15](https://user-images.githubusercontent.com/7923743/57122492-a586dd80-6db8-11e9-8af2-3d3e371b72e6.JPG)
![图像 2019-5-3，14 40](https://user-images.githubusercontent.com/7923743/57122493-a586dd80-6db8-11e9-88ad-80352c5c82d1.JPG)

**Comment by xinxijishuwyq** [comment]
https://github.com/Andy2244/openwrt-extra/tree/master/softethervpn5
上游更新过了，坐等大雕跟进

**Comment by CarterJimmy** [comment]
@xinxijishuwyq 大雕的R9.1.5跟进了没？

**Comment by xinxijishuwyq** [comment]
> @xinxijishuwyq 大雕的R9.1.5跟进了没？

没有，自己从那边撸过来吧。。
我不知道怎么给这边提交😂

**Comment by fronttang** [comment]
> @xinxijishuwyq 大雕的R9.1.5跟进了没？

好像这个也编译失败。

**Comment by CarterJimmy** [comment]
> > @xinxijishuwyq 大雕的R9.1.5跟进了没？
> 
> 好像这个也编译失败。

除了SoftEtherVPN编译报错外，noddos好像也会报错，取消选中后不知道是不是因为还是用依赖库残留的缘故，还是报错

**Comment by fronttang** [comment]
> > > @xinxijishuwyq 大雕的R9.1.5跟进了没？
> > 
> > 
> > 好像这个也编译失败。
> 
> 除了SoftEtherVPN编译报错外，noddos好像也会报错，取消选中后不知道是不是因为还是用依赖库残留的缘故，还是报错

删除lean 下面的 softethervpn5 ,用上https://github.com/Andy2244/openwrt-extra/tree/master/softethervpn5 的，编译成功了。

**Comment by CarterJimmy** [comment]
> > > > @xinxijishuwyq 大雕的R9.1.5跟进了没？
> > > 
> > > 
> > > 好像这个也编译失败。
> > 
> > 
> > 除了SoftEtherVPN编译报错外，noddos好像也会报错，取消选中后不知道是不是因为还是用依赖库残留的缘故，还是报错
> 
> 删除lean 下面的 softethervpn5 ,用上https://github.com/Andy2244/openwrt-extra/tree/master/softethervpn5 的，编译成功了。

谢谢，稍后尝试一下。
成功就关Issue

**Comment by CarterJimmy** [comment]
> > > > @xinxijishuwyq 大雕的R9.1.5跟进了没？
> > > 
> > > 
> > > 好像这个也编译失败。
> > 
> > 
> > 除了SoftEtherVPN编译报错外，noddos好像也会报错，取消选中后不知道是不是因为还是用依赖库残留的缘故，还是报错
> 
> 删除lean 下面的 softethervpn5 ,用上https://github.com/Andy2244/openwrt-extra/tree/master/softethervpn5 的，编译成功了。

![Screenshot_1](https://user-images.githubusercontent.com/7923743/57983809-e9eccb80-7a90-11e9-8fbb-34930d6b2f1c.png)
还是不行啊
