### ISSUE TITLE
v2ray 配置文件自动添加字符 \，导致不能正常使用

### ISSUE THREAD

**Issue by wspzf** [coolsnowwolf/lede#1261]
例如我在WebSocket Path填的: /123/  ,在/etc/config/shadowsocksr生成的配置文件是正常的，
但是在/var/etc/v2-ssr-retcp.json和/var/etc/v2-ssr-reudp.json里的配置文件变成了"path": "\\/123\\/"，导致连接失败。
如果没有字符：/就不会生成字符：\

**Comment by coolsnowwolf** [comment]
关注下，有可能是 lua 转义的时候自动带入的

**Comment by coolsnowwolf** [comment]
已解决
