### ISSUE TITLE
DDNS 高级设置不生效

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#12613]
### 详细叙述

如图，DDNS的高级设置里，IP地址源的设置只能变更一次，例如从网络变更为URL，可以保存但好像没有生效， 再次变更任意选项后保存也不生效了。再次变更就一直无法生效了。老版之前也是这个问题。
<img width="859" alt="Screenshot 2024-10-28 at 8 29 36 PM" src="https://github.com/user-attachments/assets/efc9bbf3-93c9-4c4e-a382-b0e2d94a1636">

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86 软路由

### 详细日志

看不到设置操作日志，只有系统日志里的记录
Mon Oct 28 20:19:25 2024 user.notice ddns-scripts[19995]: AliDDNS: PID '19995' exit normal at 2024-10-28 20:19
Mon Oct 28 20:19:25 2024 user.notice ddns-scripts[25985]: aliyun: PID '25985' started at 2024-10-28 20:19
Mon Oct 28 20:19:25 2024 user.notice ddns-scripts[25984]: AliDDNS: PID '25984' started at 2024-10-28 20:19
Mon Oct 28 20:19:25 2024 user.notice ddns-scripts[19996]: aliyun: PID '19996' terminated by 'SIGTERM' at 2024-10-28 20:19
Mon Oct 28 20:19:25 2024 user.warn ddns-scripts[25984]: AliDDNS: NO valid IP found
Mon Oct 28 20:19:25 2024 user.warn ddns-scripts[25984]: AliDDNS: Error in 'expand_ipv6()' - invalid IPv6 found: '' expanded: ''
Mon Oct 28 20:23:32 2024 user.notice ddns-scripts[25984]: AliDDNS: PID '25984' exit normal at 2024-10-28 20:23
Mon Oct 28 20:23:32 2024 user.notice ddns-scripts[2852]: AliDDNS: PID '2852' started at 2024-10-28 20:23
Mon Oct 28 20:23:32 2024 user.notice ddns-scripts[2853]: aliyun: PID '2853' started at 2024-10-28 20:23
Mon Oct 28 20:23:32 2024 user.notice ddns-scripts[25985]: aliyun: PID '25985' terminated by 'SIGTERM' at 2024-10-28 20:23
Mon Oct 28 20:23:32 2024 user.warn ddns-scripts[2852]: AliDDNS: NO valid IP found
Mon Oct 28 20:23:32 2024 user.warn ddns-scripts[2852]: AliDDNS: Error in 'expand_ipv6()' - invalid IPv6 found: '' expanded: ''
Mon Oct 28 20:23:51 2024 user.notice ddns-scripts[2852]: AliDDNS: PID '2852' exit normal at 2024-10-28 20:23
Mon Oct 28 20:23:52 2024 user.notice ddns-scripts[9411]: aliyun: PID '9411' started at 2024-10-28 20:23
Mon Oct 28 20:23:52 2024 user.notice ddns-scripts[9410]: AliDDNS: PID '9410' started at 2024-10-28 20:23
Mon Oct 28 20:23:52 2024 user.notice ddns-scripts[2853]: aliyun: PID '2853' terminated by 'SIGTERM' at 2024-10-28 20:23
Mon Oct 28 20:23:52 2024 user.warn ddns-scripts[9410]: AliDDNS: NO valid IP found
Mon Oct 28 20:23:52 2024 user.warn ddns-scripts[9410]: AliDDNS: Error in 'expand_ipv6()' - invalid IPv6 found: '' expanded: ''

**Comment by coolsnowwolf** [comment]
老脚本和新版 DDNS 不兼容了，待修复
