### ISSUE TITLE
新版的qBittorrent问题

### ISSUE THREAD

**Issue by hzmax0416** [coolsnowwolf/lede#12612]
### 详细叙述

我的qBittorrent用不了了 你们的可以吗？菜单里直接不显示了,但是软件包里显示有

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

...

**Comment by coolsnowwolf** [comment]
![image](https://github.com/user-attachments/assets/f751bdc5-26b6-4dae-bfe6-588655e43d28)
![image](https://github.com/user-attachments/assets/383a284b-eb4e-4124-ad88-cbb33e7e01cd)

已修复
