### ISSUE TITLE
新版固件里编译选项中没有一线多拨和docker，我是个例吗？

### ISSUE THREAD

**Issue by cntink** [coolsnowwolf/lede#12618]
### 详细叙述

一线多拨的“luci-app-syncdial”找不到了，docker也没有了。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

N100

### 详细日志

null

**Comment by coolsnowwolf** [comment]
用 dockerman 即可

**Comment by Jason6111** [comment]
安我的mwan3做叠加没问题
![IMG_4188](https://github.com/user-attachments/assets/5545885c-3020-45fd-a69c-ae333b5e4deb)
