### ISSUE TITLE
有没有人发现使用SSRPLUS 添加URL很难保存地址啊？

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#12620]
### 详细叙述

就发现用了23.05后编译的固件使用SSR 在URL地址框输入地址后保存应用后是保存不了地址的，解决方法就是先输入到地址框然后点+添加多一行框，保存应用就可以保存URL地址了，你们是不是这样啊，我记得以前都是直接输入后就直接保存就了

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

没有

**Comment by yuzhe1129** [comment]
![搜狗截图24年10月26日2302_2](https://github.com/user-attachments/assets/1603f762-e293-47df-b7ca-44f8c2edf5a8)
就像这样，要添加多一行 才能保存地址

**Comment by coolsnowwolf** [comment]
luci 版本的问题
