### ISSUE TITLE
ttyd必须重新安装依赖后才能正常运行

### ISSUE THREAD

**Issue by cntink** [coolsnowwolf/lede#12622]
### 详细叙述

ttyd设置好后一直报错：“Tue Oct 29 23:14:16 2024 kern.info kernel: [ 1810.095555] traps: ttyd[12585] general protection fault ip:7fa90f6efe33 sp:7fff2a47f9a8 error:0 in libc.so[7fa90f6df000+4b000]”
尝试重装“libwebsockets libuv”后正常：
opkg update
opkg install libwebsockets libuv --force-reinstall

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

N100 X64

### 详细日志

RT

**Comment by aiamadeus** [comment]
你编译环境有问题吧，make clean？
