### ISSUE TITLE
R4S编译错误

### ISSUE THREAD

**Issue by whatpig** [coolsnowwolf/lede#12625]
### 详细叙述

新拉取的仓库 -j1编译出来的错误

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

R4s

### 详细日志

<pre>Makefile.am:167:   &apos;aminclude_static.am&apos; included from here
aminclude_static.am:90: warning: addprefix --prefix ,$(CODE_COVERAGE_DIRECTORY: non-POSIX variable name
aminclude_static.am:90: (probably a GNU make extension)
Makefile.am:167:   &apos;aminclude_static.am&apos; included from here
aminclude_static.am:100: warning: &apos;:=&apos;-style assignments are not portable
Makefile.am:167:   &apos;aminclude_static.am&apos; included from here
aminclude_static.am:100: warning: AM_DISTCHECK_CONFIGURE_FLAGS was already defined in condition TRUE, which includes condition CODE_COVERAGE_ENABLED ...
Makefile.am:167:   &apos;aminclude_static.am&apos; included from here
Makefile.am:21: ... &apos;AM_DISTCHECK_CONFIGURE_FLAGS&apos; previously defined here
doc/Makefile.am: error: required file &apos;build-aux/depcomp&apos; not found
doc/Makefile.am:   &apos;automake --add-missing&apos; can install &apos;depcomp&apos;
make[4]: *** [Makefile:2258: Makefile.in] Error 1
make[4]: Leaving directory &apos;/home/admin/r4s/lede/build_dir/target-aarch64_generic_musl/gnutls-3.8.3&apos;
make[3]: *** [Makefile:270: /home/admin/r4s/lede/build_dir/target-aarch64_generic_musl/gnutls-3.8.3/.built] Error 2
make[3]: Leaving directory &apos;/home/admin/r4s/lede/feeds/packages/libs/gnutls&apos;
time: package/feeds/packages/gnutls/compile#76.95#7.12#83.52
    ERROR: package/feeds/packages/gnutls failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/gnutls/compile] Error 1
make[2]: Leaving directory &apos;/home/admin/r4s/lede&apos;
make[1]: *** [package/Makefile:110: /home/admin/r4s/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory &apos;/home/admin/r4s/lede&apos;
make: *** [/home/admin/r4s/lede/include/toplevel.mk:231：world] 错误 2
</pre>

**Comment by xuanranran** [comment]
+1
