### ISSUE TITLE
uu加速器无法启动

### ISSUE THREAD

**Issue by qyh214** [coolsnowwolf/lede#12630]
### 详细叙述

23.05中uu加速器即使启用，显示也没在运行中……

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

FriendlyElec NanoPi R4S

### 详细日志

n/a

**Comment by wi11iamzhao** [comment]
试了一下确实是：
![image](https://github.com/user-attachments/assets/e8242f40-5229-4c7c-a6d9-dff91fea0a02)

**Comment by zorrose82** [comment]
我ssh，run了 /etc/init.d/uuplugin  就启动了，然后还关不掉。可能是页面没有正常触发命令导致的

**Comment by coolsnowwolf** [comment]
已修复
