### ISSUE TITLE
openwrt添加了docker插件，ipv6测试不通

### ISSUE THREAD

**Issue by wherss1** [coolsnowwolf/lede#12638]
### 详细叙述

最新版openwrt添加了docker插件，电脑网络里IPv6地址是正常获取到，在网页里ipv6测试显示不通，卸载docker,ipv6就恢复正常

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

无日志

**Comment by loydcheung** [comment]
我也发现了同样的问题，有docker在ipv6实际都用不了，但主页overview和接口那些显示都正常。

另外docker还有个问题是刚刷完第一次启动的菜单是残缺的，只有一个配置，要重启一次，其他那些完整的才会出来
