### ISSUE TITLE
今天编译的新版本，DDNS里找不到aliyun服务了。。。

### ISSUE THREAD

**Issue by drw2005** [coolsnowwolf/lede#12631]
### 详细叙述

ddns- scripts-aliyun已经安装
28号的版本还正常，今天升级后就没有了。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

r2s

### 详细日志

无需日志

**Comment by guochan2019** [comment]
我编译完连DDNS都找不到了，明明选了，编译出来就是没有

**Comment by coolsnowwolf** [comment]
需要更新 feeds

**Comment by swxk521** [comment]
> 需要更新 feeds

旧版luci编译后cloudflare不显示，软件包显示cloudflare安装了，回退ddns版本后正常。
