### ISSUE TITLE
MT7620 / MT7621 无线读取不到噪声参数

### ISSUE THREAD

**Issue by luxiaok** [coolsnowwolf/lede#12645]
#### Lede
84cd7b8 (2024-11-05)

#### 内核版本

* 5.4.284
* 5.10.221

### 问题描述

**获取不到无线的噪声参数。**

该问题有一段时间了，目前主要就`MT7620` 、`MT7621`两个系列的机型有该问题，跟最近的大版本切换以及 ramips 内核版本切换应该都木有关系，但不知道什么原因导致的。

#### LuCI Web 界面

`网络` -> `无线` -> `已连接的站点` 不显示**噪声**参数：
![R4A-已连接的站点](https://github.com/user-attachments/assets/5db4c235-f80a-420a-8b71-f8de02a15c07)

#### 终端

命令行：
```shell
iwinfo wlan0 assoclist
```

同样也不显示噪声参数：

![r4a-g-iwinfo-不显示噪声](https://github.com/user-attachments/assets/58321308-1e5f-4d8b-a749-e99c690bce1c)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Xiaomi-R4A-Gigabit-v1、Xiaomi-Mini

### 详细日志

暂无报错日志

**Comment by coolsnowwolf** [comment]
MT76 本身的老问题
