### ISSUE TITLE
k2 not enough memory

### ISSUE THREAD

**Issue by jason19659** [coolsnowwolf/lede#1267]
not enough memory
stack traceback:
	/usr/lib/lua/luci/http/protocol.lua:133: in function '__appendval'
	/usr/lib/lua/luci/http/protocol.lua:346: in function 'store'
	/usr/lib/lua/luci/http/protocol.lua:423: in function 'snk'
	/usr/lib/lua/luci/ltn12.lua:300: in function 'step'
	/usr/lib/lua/luci/ltn12.lua:309: in function </usr/lib/lua/luci/ltn12.lua:305>
	(tail call): ?
	(tail call): ?
	/usr/lib/lua/luci/http.lua:126: in function '_parse_input'
	/usr/lib/lua/luci/http.lua:39: in function </usr/lib/lua/luci/http.lua:37>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:155: in function 'require_post_security'
	/usr/lib/lua/luci/dispatcher.lua:405: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

**Comment by hanxi** [comment]
是不是装多了插件？K2我建议不要装去广告的和$$R
