### ISSUE TITLE
提示part too big 

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/lede#127]
AR71有3个型号 c58 c60 942N  ,mtk7620也有几个型号同样问题

**Comment by coolsnowwolf** [comment]
这个是因为 K4.9 内核比 K4.4 大 100KB导致分区刚好放不下内核

**Comment by coolsnowwolf** [comment]
而且吧，有些 7620 默认是 4M 的，AR71xx 也是，别选太多组件
