### ISSUE TITLE
DDNS中的cloudfalre是否已可以正常使用

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#12703]
### 详细叙述

看到[‎net/cloudflared已经更新，DDNS中的cloudfalre模块是否已经可以正常使用
烦请使用的大佬告知，谢谢
@coolsnowwolf 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

同上

**Comment by loydcheung** [comment]
可以用。
另外我发现其实ddns-go更好用

**Comment by sleel** [comment]
1小时前测试 还不行

**Comment by drw2005** [comment]
也是cloudfalre解析，该设置的都设置了，一直不能自动更新IP，哪位知道是哪里原因吗？
![Image](https://github.com/user-attachments/assets/6b3c0e9c-f4e8-40b9-8c29-a8d0bc9d7d0e)
