### ISSUE TITLE
smartdns能否嵌入里面呢

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#1277]
smartdns使用后，过然上网速度快了，请问能否把smartdns放入呢

**Comment by Zxilly** [comment]
smartdns非开源软件，无法保证安全
而且他的原理获取最快IP并不一定能提升体验

**Comment by zxlhhyccc** [comment]
> smartdns非开源软件，无法保证安全
> 而且他的原理获取最快IP并不一定能提升体验

smartdns已经搞定可以使用
