### ISSUE TITLE
kernel升级到4.19.37后USB口丢了

### ISSUE THREAD

**Issue by tsasan** [coolsnowwolf/lede#1279]
如题：用4.14.114编译的，可以自动挂载移动硬盘，只是中文文件名丢失，只显示英文文件名。
pull新版本后，升级到4.19.37内核，编译后插上移动硬盘，连硬盘灯都不亮了。
还好我看中的酸酸乳还能正常喝。

求大神们出手指点。谢谢！

**Comment by tsasan** [comment]
硬件是 NETGEAR 7500V2 512M
编译环境是 ubuntu 14.06 32bit 
源码是 lean 大的 lede 分支。

**Comment by kob** [comment]
你得手动把USB支持的相关选项选上

**Comment by tsasan** [comment]
选上了，base里的，kernel里的，util里的，包括automount,autosamba的脚本，都选上了。

后来我又用以前编译成功可以成功挂载移动硬盘的生成的映像文件夹中的config.in的配置，作为.config，重新编译新内核，编译过程还是成功的，就是USB硬盘挂上后连电源灯（硬盘的指示灯）都不会亮了。

以前版本的内核编译成功后，挂载移动硬盘灯（硬盘指示灯）亮，挂载也没问题，共享也没问题，就是中文文件名都不显示。

再以前从网上下载过一个更老版本的编译好的固件，里面没有zerotier，但是各项功能都正常。这次就是为了加上zerotier。登录到路由器上安装zerotier提示内核版本太低，不支持，这才重新搭环境重新编译的。结果一直没有完全成功。

**Comment by yonggedebaqi** [comment]
我自己编译的完全没有问题，挂载硬盘中文显示正常。SSH登录支持显示中文输入。
![SSH支持中文](https://user-images.githubusercontent.com/43800614/57580702-83d7d580-74df-11e9-9d72-afa3faf2f638.png)

**Comment by yonggedebaqi** [comment]
硬盘中文都显示正常
![SSH支持中文1](https://user-images.githubusercontent.com/43800614/57581026-cdc2ba80-74e3-11e9-9e34-aad73dd76b15.png)

**Comment by yonggedebaqi** [comment]
wn系统访问路由器移动硬盘中文也是正常的。
![ssh2](https://user-images.githubusercontent.com/43800614/57581047-580b1e80-74e4-11e9-893a-988657354ff7.jpg)

**Comment by myeveryheart** [comment]
@kob 请教，USB支持的相关选项选上，具体是哪些？

**Comment by tsasan** [comment]
> 你得手动把USB支持的相关选项选上
请问kob兄，应该选哪些？我选的可能不对。

**Comment by tsasan** [comment]
> 硬盘中文都显示正常
> ![SSH支持中文1](https://user-images.githubusercontent.com/43800614/57581026-cdc2ba80-74e3-11e9-9e34-aad73dd76b15.png)

天啊，请问怎么做到的？

**Comment by kob** [comment]
参考这，打开usb支持https://blog.csdn.net/wynter_/article/details/78949502

**Comment by tsasan** [comment]
> 参考这，打开usb支持https://blog.csdn.net/wynter_/article/details/78949502

谢谢！我去试试看。

**Comment by tsasan** [comment]
终于成功了。谢谢上面大神的指导。原来错在没做 make kernel_menuconfig配置，另外支持中文还需那个 40-mount 脚本。
