### ISSUE TITLE
编译时候怎么修改LAN改WAN

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#12852]
### 详细叙述

由于我的兆能M2 WAN口变百兆而已了，所以想把LAN改为WAN，由于菜单没有了交换机选项了，不知道怎么在界面改WAN，能不能在编译时候把其中一个LAN改WAN

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

兆能M2

### 详细日志

0000

**Comment by coolsnowwolf** [comment]
eth 直接设置就行，要什么交换机？

**Comment by yuzhe1129** [comment]
> eth 直接设置就行，要什么交换机？

不会设置啊，能否讲解一下
或者SSH命令一条命令执行，  把LAN1改为WAN的命令
