### ISSUE TITLE
能否在旧版luci中添加ddns-go支持

### ISSUE THREAD

**Issue by bi4tms** [coolsnowwolf/lede#12874]
### 详细叙述

因为要使用“解锁网易云灰色歌曲”，故一直使用旧版luci
最新源码已经修复ddns-scripts中cloudflare v4 script，但在menuconfig->network->ip address and names中选中ddns-scripts-cloudflare后编译的DDNS的服务提供商中并无cloudflare可选
请教如何解决这个问题
如需使用ddns-go能否在旧版luci中添加支持
@coolsnowwolf 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

同上

**Comment by pangzhaoyhy** [comment]
请问如何切回旧版luci

**Comment by bi4tms** [comment]
> 请问如何切回旧版luci

在“feeds.conf.default”文件中注释掉luci23.05这一行即可

**Comment by pangzhaoyhy** [comment]
> > 请问如何切回旧版luci
> 
> 在“feeds.conf.default”文件中注释掉luci23.05这一行即可

再请问如何在云编译中切回老版luci

**Comment by coolsnowwolf** [comment]
可以

**Comment by bi4tms** [comment]
> 可以

感谢大佬

**Comment by bi4tms** [comment]
> 可以

冒昧催更一下 @coolsnowwolf
