### ISSUE TITLE
希望大佬添加主题

### ISSUE THREAD

**Issue by haig233** [coolsnowwolf/lede#1288]
https://github.com/rosywrt/luci-theme-rosy
这个主题蛮漂亮的，希望添加

**Comment by KFERMercer** [comment]
自行在feeds.conf.default中增加订阅条目`src-git luci_theme_rosy https://github.com/rosywrt/luci-theme-rosy`即可

**Comment by zxlhhyccc** [comment]
这个主题好像对某些路由不太友好，比如斐讯k3
