### ISSUE TITLE
✮[𝕏𝚆𝙰𝚃𝙲𝙷:⊱ᐯIᗪEO𝚂]✮ 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 Viral Exclusive ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ 𝙻𝚒𝚗𝚔 On Social Media 𝕏𝘛𝘸𝘪𝘵𝘵𝘦𝘳 【KHJ87B﻿ＸＸＸ】

### ISSUE THREAD

**Issue by suzetttowles** [coolsnowwolf/lede#12890]
### 详细叙述

20 sec ago 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media. ✮[𝕏𝚆𝙰𝚃𝙲𝙷:⊱ᐯIᗪEO𝚂]✮ 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 Viral Exclusive ᴠɪᴅᴇᴏ ʟᴇᴀᴋᴇᴅ 𝙻𝚒𝚗𝚔 On Social Media 𝕏𝘛𝘸𝘪𝘵𝘵𝘦𝘳 【KHJ87B﻿ＸＸＸ】

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://videoleaked.pages.dev/reload.html?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://videoleaked.pages.dev/reload.html?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://videoleaked.pages.dev/reload.html?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://videoleaked.pages.dev/reload.html?vidzm4)

𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗's latest video has taken the internet by storm, sparking widespread discussions across various social media platforms. The rising digital influencer, renowned for her captivating content—especially her recent Spiderman-themed video—has seen a significant boost in popularity, with fans eagerly anticipating the full release. Audiences are flocking to Instagram, X (formerly Twitter), and Discord to engage with her newest creation.

As excitement continues to grow, fans are actively sharing their thoughts online, highlighting how vital social media is in helping creators like 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 gain recognition. With her unique style and creative approach, she has made a notable impact on the digital scene, leaving her followers eager to see what she’ll do next. The viral success of her video underscores the powerful role social media plays in amplifying visibility and creating stronger connections between creators and their audiences.

.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
20 sec ago 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 ʟᴇᴀᴋᴇᴅ ᴠɪᴅᴇᴏ Viral On Social Media.

[𝑾𝒂𝒕𝒄𝒉 🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅 𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://videoleaked.pages.dev/reload.html?vidzm1)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄) 𝖶𝖺𝗍𝖼𝗁](https://videoleaked.pages.dev/reload.html?vidzm2)

[🟢 ➤ ➤ ➤ 🌐 𝖢𝗅𝗂𝖼𝗄 𝖧𝖾𝗋𝖾 𝖳𝗈 𝗅𝗂𝗇𝗄 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺 𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇𝗄)](https://videoleaked.pages.dev/reload.html?vidzm3)

[🔴 ➤► 𝖣𝖮𝖶𝖭𝖫𝖮𝖠𝖣👉👉 (𝖥𝗎𝗅𝗅 𝖵𝗂𝗋𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝖫𝗂𝗇 𝗄)](https://videoleaked.pages.dev/reload.html?vidzm4)

𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗's latest video has taken the internet by storm, sparking widespread discussions across various social media platforms. The rising digital influencer, renowned for her captivating content—especially her recent Spiderman-themed video—has seen a significant boost in popularity, with fans eagerly anticipating the full release. Audiences are flocking to Instagram, X (formerly Twitter), and Discord to engage with her newest creation.

As excitement continues to grow, fans are actively sharing their thoughts online, highlighting how vital social media is in helping creators like 𝙳𝚘𝚕𝚙𝚑𝚒𝚗 𝙰𝚢𝚊𝚗 gain recognition. With her unique style and creative approach, she has made a notable impact on the digital scene, leaving her followers eager to see what she’ll do next. The viral success of her video underscores the powerful role social media plays in amplifying visibility and creating stronger connections between creators and their audiences.

.

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rh vbn 7yhgghg

### 详细日志

dgfgf

fgd

make[2]: Circular package/kernel/ath10k-ct/compile <- package/kernel/mac80211/compile dependency dropped.
make[3]: Entering directory '/workdir/openwrt/package/kernel/ath10k-ct'
make[3]: *** No rule to make target '/workdir/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/mac80211-backport/backport/autoconf.h', needed by '/workdir/openwrt/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/ath10k-ct-regular/ath10k-ct-2022-05-13-f808496f/.configured_68b329da9893e34099c7d8ad5cb9c940'. Stop.
make[3]: Leaving directory '/workdir/openwrt/package/kernel/ath10k-ct'
time: package/kernel/ath10k-ct/regular/compile#0.16#0.06#0.20
ERROR: package/kernel/ath10k-ct failed to build (build variant: regular).
make[2]: *** [package/Makefile:116: package/kernel/ath10k-ct/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

基于master分支编译了适用于Redmi AX6S的固件，其中factory刷入时报错Failed to get erase block status，这一点根据查询到的资料看，应该是文件太大了，换成官方的即可。

但是刷入sysupgrade之后就变砖了，蓝灯常亮但是无法dhcp获取地址无法访问后台，自动获取更上层的地址。

之前使用的是其他人编译的固件，一开始没有问题，直到我没有印象的某一个版本开始出现这种情况（翻了一下240419还可以）。我以为是那个人编译的有问题，直到今天自己编译……

**Comment by fahmidajahan24** [comment]
csde

<a href="https://bit.ly/3YXjl9E" rel="nofollow">

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/972cf266-440d-4b43-9b74-f4d71430ce2c" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>



cvbxcdf
