### ISSUE TITLE
京东云亚瑟编译的固件无法获取到IP，也没有WiFi

### ISSUE THREAD

**Issue by Kuron88** [coolsnowwolf/lede#12909]
### 详细叙述

京东云亚瑟编译的固件无法获取到IP，拉的全新的源码，编译的时候就修改了下默认的IP,把192.168.1.1改成了192.168.2.1编译固件不会报错，编译完刷入到机器中就无法获取到IP，也没有WiFi出来，路由器指示灯已经启动完成，从切换到luci2之后才有这样的情况的，我也试过换回到luci1就没有这样的问题

补充：我把默认主题修改成了argon的主题，其他的就没动了

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

AX1800 PRO亚瑟

### 详细日志

无日志

**Comment by jw10126121** [comment]
后来怎么解决？
