### ISSUE TITLE
请求解决zerotier重启后重新生成MAC ID的问题

### ISSUE THREAD

**Issue by IHIDCHAOS** [coolsnowwolf/lede#1293]
在openwrt环境中zerotier1.2.12，运行zerotier连接后，如果重启，zerotier会丢失配置而自动生成新的mac，导致每次重启需要在官网重新添加设备。原因是zerotier配置保存在/var/lib中，而这个位置在openwrt上是重启丢失的，希望Lean大能解决一下

**Comment by zxlhhyccc** [comment]
自己修改一下代码就可以了。。。。。

**Comment by zxlhhyccc** [comment]
> 在openwrt环境中zerotier1.2.12，运行zerotier连接后，如果重启，zerotier会丢失配置而自动生成新的mac，导致每次重启需要在官网重新添加设备。原因是zerotier配置保存在/var/lib中，而这个位置在openwrt上是重启丢失的，希望Lean大能解决一下

![BW%@)_BY7@7OT{`MD{S@NZM](https://user-images.githubusercontent.com/45259624/57566576-bd85df00-7400-11e9-8753-c9768c816164.png)
改这里

**Comment by IHIDCHAOS** [comment]
@zxlhhyccc 晚上改一下验证，感谢回复。
