### ISSUE TITLE
x86-64 frp编译失败

### ISSUE THREAD

**Issue by davinyue** [coolsnowwolf/lede#12953]
### 详细叙述

x86-64使用6.1内核编译选择frpc和frps插件时编译失败了

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86-64

### 详细日志

Finding targets
../../pkg/transport/message.go:22:2: no required module provides package github.com/fatedier/golib/errors; to add it:
	go get github.com/fatedier/golib/errors
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/internal/ciphersuite/ciphersuite.go:11:2: no required module provides package github.com/pion/dtls/v2/internal/ciphersuite/types; to add it:
	go get github.com/pion/dtls/v2/internal/ciphersuite/types
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/crypto/ciphersuite/cbc.go:14:2: no required module provides package github.com/pion/dtls/v2/internal/util; to add it:
	go get github.com/pion/dtls/v2/internal/util
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/protocol/handshake/message_certificate_request.go:9:2: no required module provides package github.com/pion/dtls/v2/pkg/crypto/clientcertificate; to add it:
	go get github.com/pion/dtls/v2/pkg/crypto/clientcertificate
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/protocol/handshake/message_certificate_request.go:11:2: no required module provides package github.com/pion/dtls/v2/pkg/crypto/signature; to add it:
	go get github.com/pion/dtls/v2/pkg/crypto/signature

Building targets
../../pkg/transport/message.go:22:2: no required module provides package github.com/fatedier/golib/errors; to add it:
	go get github.com/fatedier/golib/errors
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/internal/ciphersuite/ciphersuite.go:11:2: no required module provides package github.com/pion/dtls/v2/internal/ciphersuite/types; to add it:
	go get github.com/pion/dtls/v2/internal/ciphersuite/types
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/crypto/ciphersuite/cbc.go:14:2: no required module provides package github.com/pion/dtls/v2/internal/util; to add it:
	go get github.com/pion/dtls/v2/internal/util
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/protocol/handshake/message_certificate_request.go:9:2: no required module provides package github.com/pion/dtls/v2/pkg/crypto/clientcertificate; to add it:
	go get github.com/pion/dtls/v2/pkg/crypto/clientcertificate
../../../../../dl/go-mod-cache/github.com/pion/dtls/v2@v2.2.7/pkg/protocol/handshake/message_certificate_request.go:11:2: no required module provides package github.com/pion/dtls/v2/pkg/crypto/signature; to add it:
	go get github.com/pion/dtls/v2/pkg/crypto/signature

make[3]: *** [Makefile:71: /home/davin/lede/x86/lede/build_dir/target-x86_64_musl/frp-0.51.3/.built] Error 1
make[3]: Leaving directory '/home/davin/lede/x86/lede/feeds/packages/net/frp'
time: package/feeds/packages/frp/compile#0.40#0.37#0.34
    ERROR: package/feeds/packages/frp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/frp/compile] Error 1
make[2]: Leaving directory '/home/davin/lede/x86/lede'
make[1]: *** [package/Makefile:110: /home/davin/lede/x86/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/davin/lede/x86/lede'
make: *** [/home/davin/lede/x86/lede/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
测试编译没有问题，请检查科学上网设备
