### ISSUE TITLE
R2S刷最新固件上电反复重启

### ISSUE THREAD

**Issue by chen-wilde** [coolsnowwolf/lede#12964]
### 详细叙述

micro usb版R2S刷最新[固件](https://github.com/chen-wilde/Auto-LEDE/releases/tag/NanoPi_R2S-2024.11.11-1658)SYS灯闪烁之后灭灯反复重启，换了TF卡和3A的电源照旧 #11692

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

NanoPi R2S

### 详细日志

DDR 20241018 fwver: v1.20
ID:0x805 N
ln
DDR4
333MHz
Bus Width=32 Col=10 Bank=4 Bank Group=2 Row=15 CS=1 Die Bus-Width=16 Size=1024MB
ddrconfig:14
OUT
Boot1 Release Time: May 13 2019 17:34:36, version: 2.50
ChipType = 0x11, 243
mmc2:cmd1,20
emmc reinit
mmc2:cmd1,20
emmc reinit
mmc2:cmd1,20
SdmmcInit=2 1
mmc0:cmd5,20
SdmmcInit=0 0
BootCapSize=0
UserCapSize=7580MB
FwPartOffset=2000 , 0
StorageInit ok = 33110
Raw SecureMode = 0
SecureInit read PBA: 0x4
SecureInit read PBA: 0x404
SecureInit read PBA: 0x804
SecureInit read PBA: 0xc04
SecureInit read PBA: 0x1004
SecureInit ret = 0, SecureMode = 0
atags_set_bootdev: ret:(0)
GPT 0x337a9f0 signature is wrong
recovery gpt...
GPT 0x337a9f0 signature is wrong
recovery gpt fail!
LoadTrust Addr:0x4000
No find bl30.bin
No find bl32.bin
Load uboot, ReadLba = 2000
hdr 000000000337a3b0 + 0x0:0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

Load OK, addr=0x200000, size=0xce710
RunBL31 0x40000
INFO:    Preloader serial: 2
NOTICE:  BL31: v1.3(release):5315ffb0a
NOTICE:  BL31: Built : 10:45:58, Oct 19 2021
NOTICE:  BL31:Rockchip release version: v1.3
INFO:    ARM GICv2 driver initialized
INFO:    Using opteed sec cpu_context!
INFO:    boot cpu mask: 1
INFO:    plat_rockchip_pmu_init: pd status 0xe
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x200000
INFO:    SPSR = 0x3c9

U-Boot 2024.10-OpenWrt-r6993-dd5c39cba (Nov 11 2024 - 05:22:04 +0000) OpenWrt

Model: FriendlyElec NanoPi R2S
DRAM:  1 GiB (effective 1022 MiB)
PMIC:  RK805 (on=0x40, off=0x01)
Core:  243 devices, 29 uclasses, devicetree: separate
MMC:   mmc@ff500000: 1
Loading Environment from MMC... Reading from MMC(1)... *** Warning - bad CRC, using default environment

In:    serial@ff130000
Out:   serial@ff130000
Err:   serial@ff130000
Model: FriendlyElec NanoPi R2S
Net:   eth0: ethernet@ff540000
Hit any key to stop autoboot:  0
No EFI system partition
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
** Booting bootflow '<NULL>' with efi_mgr
Loading Boot0000 'mmc 1' failed
EFI boot manager: Cannot load any image
Boot failed (err=-14)
** Booting bootflow 'mmc@ff500000.bootdev.part_1' with script
47609 bytes read in 6 ms (7.6 MiB/s)
17526792 bytes read in 762 ms (21.9 MiB/s)
Moving Image from 0x2080000 to 0x2200000, end=3380000
## Flattened Device Tree blob at 01e00000
   Booting using the fdt blob at 0x1e00000
Working FDT set to 1e00000
   Loading Device Tree to 000000003cecd000, end 000000003cedb9f8 ... OK
Working FDT set to 3cecd000

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 6.6.58 (runner@fv-az1986-673) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r6971-897572506) 11.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP PREEMPT Mon Nov 11 05:22:04 2024
[    0.000000] KASLR enabled
[    0.000000] Machine model: FriendlyElec NanoPi R2S
[    0.000000] earlycon: uart8250 at MMIO32 0x00000000ff130000 (options '')
[    0.000000] printk: bootconsole [uart8250] enabled
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000200000-0x000000003fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000200000-0x000000003fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000200000-0x000000003fffffff]
[    0.000000] On node 0, zone DMA: 512 pages in unavailable ranges
[    0.000000] cma: Reserved 64 MiB at 0x0000000038e00000 on node -1
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 20 pages/cpu s41512 r8192 d32216 u81920
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: kernel page table isolation forced ON by KASLR
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] CPU features: detected: ARM erratum 845719
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Kernel command line: console=ttyS2,1500000 earlycon=uart8250,mmio32,0xff130000 root=PARTUUID=5452574f-02 rw rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 257544
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: SWIOTLB bounce buffer size adjusted to 0MB
[    0.000000] software IO TLB: area num 4.
[    0.000000] software IO TLB: mapped [mem 0x000000003ea80000-0x000000003eb80000] (1MB)
[    0.000000] Memory: 941412K/1046528K available (9408K kernel code, 2460K rwdata, 2892K rodata, 2240K init, 742K bss, 39580K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000001] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.002004] Console: colour dummy device 80x25
[    0.002559] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=96000)
[    0.003520] pid_max: default: 32768 minimum: 301
[    0.009081] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.009785] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.017235] RCU Tasks: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.018073] RCU Tasks Trace: Setting shift to 2 and lim to 1 rcu_task_cb_adjust=1.
[    0.019259] rcu: Hierarchical SRCU implementation.
[    0.019713] rcu:     Max phase no-delay instances is 1000.
[    0.021723] smp: Bringing up secondary CPUs ...
[    0.023144] Detected VIPT I-cache on CPU1
[    0.023329] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.024540] Detected VIPT I-cache on CPU2
[    0.024712] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.025753] Detected VIPT I-cache on CPU3
[    0.025919] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.026094] smp: Brought up 1 node, 4 CPUs
[    0.029478] SMP: Total of 4 processors activated.
[    0.029922] CPU features: detected: 32-bit EL0 Support
[    0.030403] CPU features: detected: CRC32 instructions
[    0.031020] CPU: All CPU(s) started at EL2
[    0.031428] alternatives: applying system-wide alternatives
[    0.050376] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.051320] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.058006] pinctrl core: initialized pinctrl subsystem
[    0.061399] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.063753] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.064660] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.065566] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.067715] thermal_sys: Registered thermal governor 'step_wise'
[    0.067731] thermal_sys: Registered thermal governor 'power_allocator'
[    0.068381] cpuidle: using governor menu
[    0.069618] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.070422] ASID allocator initialised with 32768 entries
[    0.071850] Serial: AMBA PL011 UART driver
[    0.091651] gpio gpiochip0: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.092832] rockchip-gpio ff210000.gpio: probed /pinctrl/gpio@ff210000
[    0.094372] gpio gpiochip1: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.095486] rockchip-gpio ff220000.gpio: probed /pinctrl/gpio@ff220000
[    0.096596] gpio gpiochip2: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.097782] rockchip-gpio ff230000.gpio: probed /pinctrl/gpio@ff230000
[    0.098872] gpio gpiochip3: Static allocation of GPIO base is deprecated, use dynamic allocation.
[    0.099959] rockchip-gpio ff240000.gpio: probed /pinctrl/gpio@ff240000
[    0.107305] Modules: 2G module region forced by RANDOMIZE_MODULE_REGION_FULL
[    0.107995] Modules: 0 pages in range for non-PLT usage
[    0.108002] Modules: 519808 pages in range for PLT usage
[    0.110265] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.111407] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
[    0.111991] HugeTLB: registered 32.0 MiB page size, pre-allocated 0 pages
[    0.112622] HugeTLB: 0 KiB vmemmap can be freed for a 32.0 MiB page
[    0.113207] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.113878] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
[    0.114465] HugeTLB: registered 64.0 KiB page size, pre-allocated 0 pages
[    0.115094] HugeTLB: 0 KiB vmemmap can be freed for a 64.0 KiB page
[    0.119080] cryptd: max_cpu_qlen set to 1000
[    0.124295] iommu: Default domain type: Translated
[    0.124777] iommu: DMA domain TLB invalidation policy: strict mode
[    0.125515] gpio-regulator sdmmcio-regulator: Failed to register regulator: -517
[    0.126068] SCSI subsystem initialized
[    0.127036] usbcore: registered new interface driver usbfs
[    0.127607] usbcore: registered new interface driver hub
[    0.128199] usbcore: registered new device driver usb
[    0.129667] scmi_core: SCMI protocol bus registered
[    0.132477] clocksource: Switched to clocksource arch_sys_counter
[    0.133794] VFS: Disk quotas dquot_6.6.0
[    0.134276] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.144179] NET: Registered PF_INET protocol family
[    0.144967] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.149126] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    0.150024] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.150763] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.151613] TCP bind hash table entries: 8192 (order: 6, 262144 bytes, linear)
[    0.152723] TCP: Hash tables configured (established 8192 bind 8192)
[    0.154165] MPTCP token hash table entries: 1024 (order: 2, 24576 bytes, linear)
[    0.155137] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.155800] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.157062] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.157648] PCI: CLS 0 bytes, default 64
[    0.160940] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.166375] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.166938] jffs2: version 2.2 (NAND) (SUMMARY) (ZLIB) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.174960] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.176005] io scheduler mq-deadline registered
[    0.188023] dma-pl330 ff1f0000.dma-controller: Loaded driver for PL330 DMAC-241330
[    0.188811] dma-pl330 ff1f0000.dma-controller:       DBUFF-128x8bytes Num_Chans-8 Num_Peri-20 Num_Events-16
[    0.193895] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.197777] printk: console [ttyS2] disabled
[    0.198778] ff130000.serial: ttyS2 at MMIO 0xff130000 (irq = 21, base_baud = 1500000) is a 16550A
[    0.199691] printk: console [ttyS2] enabled
[    0.199691] printk: console [ttyS2] enabled
[    0.200569] printk: bootconsole [uart8250] disabled
[    0.200569] printk: bootconsole [uart8250] disabled
[    0.214999] loop: module loaded
[    0.215324] mtip32xx Version 1.3.1
[    0.222399] rk_gmac-dwmac ff540000.ethernet: IRQ eth_wake_irq not found
[    0.223023] rk_gmac-dwmac ff540000.ethernet: IRQ eth_lpi not found
[    0.223790] rk_gmac-dwmac ff540000.ethernet: PTP uses main clock
[    0.227327] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    0.227886] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[    0.228835] xhci-hcd xhci-hcd.0.auto: hcc params 0x0220fe64 hci version 0x110 quirks 0x0000008002000010
[    0.229740] ehci-platform ff5c0000.usb: EHCI Host Controller
[    0.229760] ohci-platform ff5d0000.usb: Generic Platform OHCI controller
[    0.229779] xhci-hcd xhci-hcd.0.auto: irq 25, io mem 0xff600000
[    0.230096] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    0.230122] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[    0.230147] xhci-hcd xhci-hcd.0.auto: Host supports USB 3.0 SuperSpeed
[    0.231253] hub 1-0:1.0: USB hub found
[    0.233527] hub 1-0:1.0: 1 port detected
[    0.234610] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    0.236225] hub 2-0:1.0: USB hub found
[    0.236663] hub 2-0:1.0: 1 port detected
[    0.237684] ehci-platform ff5c0000.usb: new USB bus registered, assigned bus number 3
[    0.237698] ohci-platform ff5d0000.usb: new USB bus registered, assigned bus number 4
[    0.237820] usbcore: registered new interface driver usb-storage
[    0.238087] i2c_dev: i2c /dev entries driver
[    0.238602] ehci-platform ff5c0000.usb: irq 26, io mem 0xff5c0000
[    0.239324] ohci-platform ff5d0000.usb: irq 27, io mem 0xff5d0000
[    0.249650] rk808-regulator rk808-regulator.2.auto: there is no dvs0 gpio
[    0.250314] rk808-regulator rk808-regulator.2.auto: there is no dvs1 gpio
[    0.252505] ehci-platform ff5c0000.usb: USB 2.0 started, EHCI 1.00
[    0.254154] hub 3-0:1.0: USB hub found
[    0.254576] hub 3-0:1.0: 1 port detected
[    0.277014] rk808-rtc rk808-rtc.4.auto: registered as rtc0
[    0.279279] rk808-rtc rk808-rtc.4.auto: setting system clock to 2016-01-21T08:50:43 UTC (1453366243)
[    0.285221] dw_wdt ff1a0000.watchdog: No valid TOPs array specified
[    0.289544] cpu cpu0: EM: created perf domain
[    0.292186] sdhci: Secure Digital Host Controller Interface driver
[    0.293006] sdhci: Copyright(c) Pierre Ossman
[    0.293439] Synopsys Designware Multimedia Card Interface Driver
[    0.294291] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.294836] dwmmc_rockchip ff500000.mmc: IDMAC supports 32-bit address mode.
[    0.295499] dwmmc_rockchip ff500000.mmc: Using internal DMA controller.
[    0.296087] dwmmc_rockchip ff500000.mmc: Version ID is 270a
[    0.296735] dwmmc_rockchip ff500000.mmc: DW MMC controller at irq 41,32 bit host data width,256 deep fifo
[    0.297009] ledtrig-cpu: registered to indicate activity on CPUs
[    0.298657] usbcore: registered new interface driver usbhid
[    0.299156] usbhid: USB HID core driver
[    0.304849] hw perfevents: enabled with armv8_cortex_a53 PMU driver, 7 counters available
[    0.305135] hub 4-0:1.0: USB hub found
[    0.305947] hub 4-0:1.0: 1 port detected
[    0.307424] NET: Registered PF_INET6 protocol family
[    0.309667] Segment Routing with IPv6
[    0.310054] In-situ OAM (IOAM) with IPv6
[    0.310473] NET: Registered PF_PACKET protocol family
[    0.310946] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    0.312074] 8021q: 802.1Q VLAN Support v1.8
[    0.342640] rk_gmac-dwmac ff540000.ethernet: IRQ eth_wake_irq not found
[    0.343251] rk_gmac-dwmac ff540000.ethernet: IRQ eth_lpi not found
[    0.343922] rk_gmac-dwmac ff540000.ethernet: PTP uses main clock
[    0.344891] rk_gmac-dwmac ff540000.ethernet: clock input or output? (input).
[    0.345522] rk_gmac-dwmac ff540000.ethernet: TX delay(0x24).
[    0.346021] rk_gmac-dwmac ff540000.ethernet: RX delay(0x18).
[    0.346529] rk_gmac-dwmac ff540000.ethernet: integrated PHY? (no).
[    0.347105] rk_gmac-dwmac ff540000.ethernet: clock input from PHY
[    0.352652] rk_gmac-dwmac ff540000.ethernet: init for RGMII
[    0.353842] rk_gmac-dwmac ff540000.ethernet: User ID: 0x10, Synopsys ID: 0x35
[    0.354503] rk_gmac-dwmac ff540000.ethernet:         DWMAC1000
[    0.354965] rk_gmac-dwmac ff540000.ethernet: DMA HW capability register supported
[    0.355621] rk_gmac-dwmac ff540000.ethernet: RX Checksum Offload Engine supported
[    0.356276] rk_gmac-dwmac ff540000.ethernet: COE Type 2
[    0.356757] rk_gmac-dwmac ff540000.ethernet: TX Checksum insertion supported
[    0.357372] rk_gmac-dwmac ff540000.ethernet: Wake-Up On Lan supported
[    0.357940] rk_gmac-dwmac ff540000.ethernet: Normal descriptors
[    0.358460] rk_gmac-dwmac ff540000.ethernet: Ring mode enabled
[    0.358973] rk_gmac-dwmac ff540000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    0.507297] rk3328-dmc-freq dmc: current ATF version 0x101
[    0.507514] dwmmc_rockchip ff500000.mmc: IDMAC supports 32-bit address mode.
[    0.508595] dwmmc_rockchip ff500000.mmc: Using internal DMA controller.
[    0.509194] dwmmc_rockchip ff500000.mmc: Version ID is 270a
[    0.509751] dwmmc_rockchip ff500000.mmc: DW MMC controller at irq 41,32 bit host data width,256 deep fifo
[    0.512856] clk: Disabling unused clocks
[    0.515139] dw-apb-uart ff130000.serial: forbid DMA for kernel console
[    0.528555] mmc_host mmc0: Bus speed (slot 0) = 400000Hz (slot req 400000Hz, actual 400000HZ div = 0)
[    0.540942] Waiting for root device PARTUUID=5452574f-02...
[    0.572571] usb 2-1: new SuperSpeed USB device number 2 using xhci-hcd
[    0.625722] mmc_host mmc0: Bus speed (slot 0) = 150000000Hz (slot req 150000000Hz, actual 150000000HZ div = 0)
[    0.891901] dwmmc_rockchip ff500000.mmc: Successfully tuned phase to 10
[    0.892545] mmc0: new ultra high speed SDR104 SDHC card at address aaaa
[    0.894436] mmcblk0: mmc0:aaaa SA08G 7.40 GiB
[    0.897551]  mmcblk0: p1 p2
[    0.917861] VFS: Mounted root (squashfs filesystem) readonly on device 179:2.
[    0.919770] Freeing unused kernel memory: 2240K
[    0.920242] Run /sbin/init as init process
[    1.065217] init: Console is alive
[    1.065785] init: - watchdog -
[    1.518018] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    1.539008] raid6: skipped pq benchmark and selected neonx8
[    1.539538] raid6: using neon recovery algorithm
[    1.548094] xor: measuring software checksum speed
[    1.549554]    8regs           :  3356 MB/sec
[    1.550912]    32regs          :  3382 MB/sec
[    1.552348]    arm64_neon      :  3123 MB/sec
[    1.552740] xor: using function: 32regs (3382 MB/sec)
[    1.643817] Btrfs loaded, zoned=no, fsverity=no
[    1.654423] gpio_button_hotplug: loading out-of-tree module taints kernel.
[    1.659849] usbcore: registered new interface driver uas
[    1.660858] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    1.664906] init: - preinit -
[    2.052756] random: jshn: uninitialized urandom read (4 bytes read)
[    2.089950] random: jshn: uninitialized urandom read (4 bytes read)
[    2.153345] random: jshn: uninitialized urandom read (4 bytes read)
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[    4.027662] rockchip-pm-domain ff100000.syscon:power-controller: failed to get ack on domain 'hevc', val=0x88220
[    4.540443] mount_root: loading kmods from internal overlay
[    4.566458] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[    4.571486] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[    4.706995] block: attempting to load /tmp/overlay/upper/etc/config/fstab
[    4.707769] block: unable to load configuration (fstab: Entry not found)
[    4.708443] block: attempting to load /tmp/overlay/etc/config/fstab
[    4.709203] block: unable to load configuration (fstab: Entry not found)
[    4.709868] block: attempting to load /etc/config/fstab
[    4.713529] block: unable to load configuration (fstab: Entry not found)
[    4.714293] block: no usable configuration
[    4.714841] block: attempting to load /etc/config/fstab
[    4.715406] block: unable to load configuration (fstab: Entry not found)
[    4.716061] block: no usable configuration
[    4.717438] loop0: detected capacity change from 0 to 14680064
[    4.752655] loop0: detected capacity change from 14680064 to 14369536
[    4.936611] F2FS-fs (loop0): Mounted with checkpoint version = 58061f05
[    4.938394] mount_root: loading kmods from internal overlay
[    4.958970] kmodloader: loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[    4.960774] kmodloader: done loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[    4.986427] block: attempting to load /tmp/overlay/upper/etc/config/fstab
[    4.995776] mount_root: switched to extroot
[    5.219619] EXT4-fs (mmcblk0p1): warning: mounting unchecked fs, running e2fsck is recommended
[    5.223108] EXT4-fs (mmcblk0p1): mounted filesystem 84173db5-fa99-e35a-95c6-28613cc79ea9 r/w without journal. Quota mode: none.
[    5.242108] EXT4-fs (mmcblk0p1): unmounting filesystem 84173db5-fa99-e35a-95c6-28613cc79ea9.
[    5.249413] urandom-seed: Seed file not found (/etc/urandom.seed)
Scanning for Btrfs filesystems
[    5.519164] procd: - early -
[    5.519648] procd: - watchdog -
[    6.131348] procd: - watchdog -
[    6.137523] procd: - ubus -
[    6.191145] random: ubusd: uninitialized urandom read (4 bytes read)
[    6.193764] random: ubusd: uninitialized urandom read (4 bytes read)
[    6.195066] random: ubusd: uninitialized urandom read (4 bytes read)
[    6.199961] procd: - init -
Please press Enter to activate this console.
[    6.562859] urngd: v1.0.2 started.
[    6.582954] random: crng init done
[    6.583324] random: 26 urandom warning(s) missed due to ratelimiting
[    7.249866] ------------[ cut here ]------------
[    7.249991] Unable to handle kernel paging request at virtual address ffff3a80050f5480
[    7.249995] Unable to handle kernel paging request at virtual address ffff3a8001087400
[    7.250000] Mem abort info:
[    7.250001]   ESR = 0x0000000096000004
[    7.250003]   EC = 0x25: DABT (current EL), IL = 32 bits
[    7.250007]   SET = 0, FnV = 0
[    7.250009]   EA = 0, S1PTW = 0

**Comment by aiamadeus** [comment]
https://github.com/coolsnowwolf/lede/commit/f0ab317249c09032fd78ecf2216b1fdde825630f
revert 这个试一下

**Comment by chen-wilde** [comment]
> [f0ab317](https://github.com/coolsnowwolf/lede/commit/f0ab317249c09032fd78ecf2216b1fdde825630f) revert 这个试一下

解决了，谢谢佬

**Comment by chaichunyang** [comment]
> > r2s遇到同样问题，请问如何解决的？我看commit已经被l revert了。今天最新编译的固件，上电后闪灯，常亮，闪灯，灭，反复如此
> 
> 确实又重启了，我看 [af207e5](https://github.com/coolsnowwolf/lede/commit/af207e5f62bb88247e647483c07a4ea9ca33d318) 又改回去了

确实，再revert这个又行了，看来是这个版本不能兼容。
