### ISSUE TITLE
rockchip  KING3399

### ISSUE THREAD

**Issue by 392377870** [coolsnowwolf/lede#12988]
### 详细叙述

KING3399 最新源码的固件编译出来刷好后，已经无法启动了

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rockchip  KING3399

### 详细日志

KING3399 最新源码的固件编译出来刷好后，已经无法启动了

**Comment by coolsnowwolf** [comment]
日志？

**Comment by 392377870** [comment]
> 記錄？

编译固件没有报错，刷完不启动，还真不好去哪里搞出日志

**Comment by coolsnowwolf** [comment]
现在看看？

**Comment by Kuron88** [comment]
亚瑟也这样，编译的时候都是正常的，刷到固件就无法分配IP地址，WiFi也没有，但是看路由器的指示灯是启动了的

**Comment by 392377870** [comment]
> 现在看看？

还是一样，编译成功，刷入后不能启动
