### ISSUE TITLE
A：[163804.964712] br-lan: received packet on eth1 with own address as source address (addr:ea:ec:03:bc:ea:2b, vlan:0)

### ISSUE THREAD

**Issue by written143** [coolsnowwolf/lede#12989]
### 详细叙述

主路由r4s 
lan口连接了ap模式的红米ax6000
2个红米ax1800连到红米ax6000
组有线mesh
每隔一段时间就会出现A：[163804.964712] br-lan: received packet on eth1 with own address as source address (addr:ea:ec:03:bc:ea:2b, vlan:0)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

r4s

### 详细日志

![image](https://github.com/user-attachments/assets/fbf6fd20-24af-417b-bdf4-96cb3ed13320)

**Comment by coolsnowwolf** [comment]
有这个报错就肯定有环路
