### ISSUE TITLE
question about the pdnsd-alt

### ISSUE THREAD

**Issue by tacuar** [coolsnowwolf/lede#130]
firstly thank you for your contribution and the very nice coding of the SSR with pdnsd.

at this  moment when start running SSR , it creates the pdnsd pid , while the SSR is closed , the pdnsd stop running forever and even can not be found in startup.

is it possible to have a option that even SSR is not running, but we still can use the Pdnsd running and can be configured? for example, when the SSR is not running, we first have a china-list.conf in /etc/dnsmasq.d , and all through 114dns, besides this, other domains are through pdnsd, moreover, the pdnsd can even use the upstream dns of dnscrypt-proxy if possible.

i'm not sure if this would be reasonable or , can be useful if i want to accelerate domestic and abroad web broswsing when the SSR is not running ?

and when the SSR start running, everything is fine besides only one error notice of pdnsd in system log : 
Cache file /var/pdnsd/pdnsd.cache ignored because of incompatible version identifier

**Comment by fuqiang03** [comment]
添加一个luci即可
