### ISSUE TITLE
在官方openwrt运行问题

### ISSUE THREAD

**Issue by feika** [coolsnowwolf/lede#1300]
编译好的ssr-plus和frpc两个luci界面在官方openwrt上安装并且配置好后都显示ssr-plus frpc未运行，而在终端里面手动运行ssr和frpc却是OK的， 想知道原因在哪里

**Comment by coolsnowwolf** [comment]
不兼容 trunk 版本的 luci

**Comment by feika** [comment]
那是要在官方的SDK编译还是就只能刷你的固件

**Comment by coolsnowwolf** [comment]
luci 问题，用 18.06 的 luci 就好了
