### ISSUE TITLE
rockchip r3s rk3566无法启动

### ISSUE THREAD

**Issue by phpebe** [coolsnowwolf/lede#13001]
### 详细叙述

最新版和旧分支均能正常编译成功，写入r3s之后无法启动.

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

rockchip r3s

### 详细日志

编译正常

**Comment by 392377870** [comment]
看来rk系列不是一个出问题。我的KING3399也是编译完成后刷入不能启动
