### ISSUE TITLE
软件包刷新列表失败

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#13000]
### 详细叙述

近期的拉取编译，手动选择使用18.06 luci后无法刷新软件包列表，不知道是不是跟luci有关系，https://downloads.openwrt.org确定是可以正常访问的，
OPKG 配置
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

nanopi

### 详细日志

Downloading https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_generic/base/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/aarch64_generic/base/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_generic/luci/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/aarch64_generic/luci/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_generic/routing/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/aarch64_generic/routing/Packages.gz

Downloading https://downloads.openwrt.org/snapshots/packages/aarch64_generic/telephony/Packages.gz
*** Failed to download the package list from https://downloads.openwrt.org/snapshots/packages/aarch64_generic/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_generic/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_generic/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_generic/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://downloads.openwrt.org/snapshots/packages/aarch64_generic/telephony/Packages.gz, wget returned 8.

**Comment by TaneikaMacedo** [comment]
dssvxgd

**Comment by xingshu1990** [comment]
Downloading https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz
手动打开 https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/
CTRL+F 搜索Packages.gz，未搜索到
其他同理。

**Comment by xingshu1990** [comment]
> > Downloading https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz 手动打开 https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/ CTRL+F 搜索Packages.gz，未搜索到 其他同理。下载https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/Packages.gz手动打开https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/packages/ CTRL+F 搜索Packages.gz，未搜索到其他同理。
> 
> 没明白，，Packages.gz不存在，是哪里做过修改了吗？

---

不清楚，我的也是昨天发现https://mirrors.cloud.tencent.com 腾讯的源有问题，不能访问，结果换成其他源了
#src/gz openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/bcm27xx/bcm2710/packages
#src/gz openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/base
#src/gz openwrt_kenzo https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/kenzo
#src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/aarch64_cortex-a53/luci
#src/gz openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages
#src/gz openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/routing
#src/gz openwrt_small https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/small
#src/gz openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/telephony

src/gz openwrt_core https://downloads.openwrt.org/releases/18.06.9/targets/brcm2708/bcm2710/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/18.06.9/packages/aarch64_cortex-a53/telephony

**Comment by gitbruc** [comment]
这问题咋不解决啊，折磨了我一晚上

**Comment by justamanm** [comment]
同样
看了下，每个订阅地址下都没有Packages.gz，只有packages.adb、packages.adb.asc和packages.adb.sig
![Snipaste_2024-11-15_19-08-55](https://github.com/user-attachments/assets/ea58dffe-f7b4-4f57-b8a2-168d4e4e0c53)
问了下chatgpt

> 新格式的包索引文件：

packages.adb 是一种新的包索引格式，可能用于更高效的包管理。
packages.adb.asc 是 GPG 签名文件，用于验证 packages.adb 的完整性。
packages.adb.sig 同样是验证文件。
源可能已切换格式： 
某些镜像可能已切换为支持 adb 索引格式的系统，而不再使用传统的 Packages.gz

**Comment by xingshu1990** [comment]
> 这样强行换源 会导致
> 
> > 同样 看了下，每个订阅地址下都没有Packages.gz，只有packages.adb、packages.adb.asc和packages.adb.sig ![Snipaste_2024-11-15_19-08-55](https://private-user-images.githubusercontent.com/49265026/386572101-ea58dffe-f7b4-4f57-b8a2-168d4e4e0c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzM2OTgsIm5iZiI6MTczMTY3MzM5OCwicGF0aCI6Ii80OTI2NTAyNi8zODY1NzIxMDEtZWE1OGRmZmUtZjdiNC00ZjU3LWI4YTItMTY4ZDRlNGUwYzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyMjMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTkzMWI0M2YzZjRiMzU4ZGVhYjUwMWZmYmQ2ZTFkNmU2NjUyYWZhMzg4YjQ4Nzc0NjY4MWM4NTU1M2U0ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LZwQv7VvOUazOjiwdvWDtfm8cLJ4rO1B8HQ5wpbSFok) 问了下chatgpt
> > > 新格式的包索引文件：
> > > packages.adb 是一种新的包索引格式，可能用于更高效的包管理。
> > > packages.adb.asc 是 GPG 签名文件，用于验证 packages.adb 的完整性。
> > > packages.adb.sig 同样是验证文件。
> > > 源可能已切换格式：
> > > 某些镜像可能已切换为支持 adb 索引格式的系统，而不再使用传统的 Packages.gz
> > 
> > 
> > 我试了下换成清华源就行了
> > ```shell
> > cd /etc/opkg/
> > cp distfeeds.conf distfeeds.conf.bak
> > sed -i 's_mirrors.tencent.com/lede/snapshots_mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5_g' /etc/opkg/distfeeds.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 换完后的地址（树莓派4b）
> > ```
> > src/gz openwrt_core https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/targets/bcm27xx/bcm2711/packages
> > src/gz openwrt_base https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/base
> > src/gz openwrt_kenzo https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/kenzo
> > src/gz openwrt_luci https://mirrors.tencent.com/lede/releases/18.06.9/packages/aarch64_cortex-a72/luci
> > src/gz openwrt_oldpackages https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/oldpackages
> > src/gz openwrt_packages https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/packages
> > src/gz openwrt_routing https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/routing
> > src/gz openwrt_small https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/small
> > src/gz openwrt_telephony https://mirrors.tuna.tsinghua.edu.cn/lede/releases/23.05.5/packages/aarch64_cortex-a72/telephony
> > ```
> 
> 这样强行换源会导致安装的ipk与内核的Linux版本不一致：pkg_hash_check_unresolved: cannot find dependency kernel


中间的23.05.5  换成18.06.9试试，
另外
kenzo  small 这两个没mirrors.tuna.tsinghua.edu.cn源吧，要注释掉的。

**Comment by Travel2Here** [comment]
同 显然是服务器目录没了…

**Comment by Travel2Here** [comment]
清华的里面也404了

**Comment by coolsnowwolf** [comment]
上游改成 apk 的数据库了

**Comment by gitbruc** [comment]
> 修复了，用 v24.10 格式吧

Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Upgrading docker on root from 27.0.2-1 to 27.3.1-r1...
Downloading https://mirrors.tencent.com/lede/releases/24.10-SNAPSHOT/packages/x86_64/packages/docker_27.3.1-r1_x86_64.ipk
Collected errors:
 * opkg_download: Failed to download https://mirrors.tencent.com/lede/releases/24.10-SNAPSHOT/packages/x86_64/packages/docker_27.3.1-r1_x86_64.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download docker. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package docker.

**Comment by wbpluto** [comment]
[OpenWrt 重大变更公告：包管理器已从opkg 更改为apk](https://linux.do/t/topic/263612)

**Comment by ilyfairy** [comment]
> [OpenWrt 重大变更公告：包管理器已从opkg 更改为apk](https://linux.do/t/topic/263612)

apk怎么提示文件或目录不存在
```
# apk update
ERROR: Unable to read database: No such file or directory
ERROR: Failed to open apk database: No such file or directory

# apk version
ERROR: Unable to read database: No such file or directory
ERROR: Failed to open apk database: No such file or directory
```
