### ISSUE TITLE
newifid2不能开机了

### ISSUE THREAD

**Issue by qwerttvv** [coolsnowwolf/lede#13002]
### 详细叙述

刚编译，我试了4个版本
5.4+lua luci
5.4+js luci
5.10+lua luci
5.10+js luci
都是刷完了不能正常开机，得进breed

上一次之前我是10月初编译的5.4+lua luci是好的，可以正常使用，现在配置什么的哪里都没改，就起不来了

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

newifi d2

### 详细日志

可以正常编译，刷机后不能启动了

**Comment by aiamadeus** [comment]
没有串口日志？

**Comment by coolsnowwolf** [comment]
没有内核日志看不到原因

**Comment by coolsnowwolf** [comment]
测试其他的 7621 没问题，这个要看日志了
