### ISSUE TITLE
x86 docker版本编译不通过，编译了6个小时，都不成功。

### ISSUE THREAD

**Issue by lysgwl** [coolsnowwolf/lede#13017]
### 详细叙述

配置文件文件如下：
[seed.txt](https://github.com/user-attachments/files/17782712/seed.txt)

最终出现的错误如下：
![Snipaste_2024-11-16_08-35-04](https://github.com/user-attachments/assets/6176be1a-589e-4eb5-af89-1c0063713cc9)

编译x86 docker版本时，不通过。去除了docker后，就没有问题。

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

pve虚拟机设备

### 详细日志

![Snipaste_2024-11-16_08-35-04](https://github.com/user-attachments/assets/2e885b42-d403-4454-a590-c1b4ca82cc47)

**Comment by qingtian110** [comment]
你都超时了。GitHub action 不适用于插件全家桶、高大全对、内置插件越多越牛逼系列。

**Comment by lysgwl** [comment]
> 你都超时了。GitHub action 不适用于插件全家桶、高大全对、内置插件越多越牛逼系列。

问题我找见了，编译没几个插件，问题出在golang的版本上。引用外部插件造成的。再试试看行不行。

**Comment by lysgwl** [comment]
> 你都超时了。GitHub action 不适用于插件全家桶、高大全对、内置插件越多越牛逼系列。

编译一晚上，还是出错了。如果不加docker，就没问题，就可以编译通过。以下是错误截图：
![Snipaste_2024-11-17_11-04-52](https://github.com/user-attachments/assets/1fe938b1-27d6-432e-95b3-733596feb7d7)

以下配置为不包含docker的配置，就可以编译通过：
[seed.txt](https://github.com/user-attachments/files/17788715/seed.txt)

就奇了怪了，前一阵还可以用，这几天就突然不行了。大神帮我瞅瞅把。

**Comment by lxl6125** [comment]
磁盘空间不足，换个工作目录吧，/mnt 这么大的空间为啥不用
![Screenshot_20241118_204544_com vivaldi browser](https://github.com/user-attachments/assets/4bf217e5-ca1c-44eb-84ff-ae09b63408db)
