### ISSUE TITLE
OpenVPN 服务器 无法正常加载

### ISSUE THREAD

**Issue by richaradlee** [coolsnowwolf/lede#13013]
### 详细叙述

X86 云编译最新固件，OpenVPN服务器插件无法启动，请问各位是否碰到？如何解决？
![屏幕截图 2024-11-15 085847](https://github.com/user-attachments/assets/6d7a98ec-e053-48a4-bf7b-80ef2fa736d4)
![屏幕截图 2024-11-15 085814](https://github.com/user-attachments/assets/9b267c11-d6a5-4947-aa41-08be063afc16)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

没有

**Comment by richaradlee** [comment]
Fri Nov 15 09:18:03 2024 daemon.warn openvpn(rikki)[1530]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Fri Nov 15 09:18:03 2024 daemon.warn openvpn(rikki)[1530]: --cipher is not set. Previous OpenVPN version defaulted to BF-CBC as fallback when cipher negotiation failed in this case. If you need this fallback please add '--data-ciphers-fallback BF-CBC' to your configuration and/or add BF-CBC to --data-ciphers.
Fri Nov 15 09:18:03 2024 daemon.notice openvpn(rikki)[1530]: OpenVPN 2.5.8 x86_64-openwrt-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
Fri Nov 15 09:18:03 2024 daemon.notice openvpn(rikki)[1530]: library versions: OpenSSL 3.0.15 3 Sep 2024, LZO 2.10
Fri Nov 15 09:18:03 2024 daemon.warn openvpn(rikki)[1530]: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
Fri Nov 15 09:18:03 2024 daemon.warn openvpn(rikki)[1530]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Nov 15 09:18:03 2024 daemon.err openvpn(rikki)[1530]: OpenSSL: error:0480006C:PEM routines::no start line
Fri Nov 15 09:18:03 2024 daemon.err openvpn(rikki)[1530]: OpenSSL: error:0A080009:SSL routines::PEM lib
Fri Nov 15 09:18:03 2024 daemon.err openvpn(rikki)[1530]: Cannot load inline certificate file
Fri Nov 15 09:18:03 2024 daemon.notice openvpn(rikki)[1530]: Exiting due to fatal error
Fri Nov 15 09:18:21 2024 daemon.warn openvpn(myvpn)[2049]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Fri Nov 15 09:18:26 2024 daemon.warn openvpn(myvpn)[2125]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Fri Nov 15 09:18:31 2024 daemon.warn openvpn(myvpn)[2188]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Fri Nov 15 09:18:36 2024 daemon.warn openvpn(myvpn)[2245]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
Fri Nov 15 09:18:41 2024 daemon.warn openvpn(myvpn)[2297]: WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.

**Comment by richaradlee** [comment]
4个证书没有生成的问题，已搞定。

**Comment by 0758jian** [comment]
> 4个证书没有生成的问题，已搞定。

建议你不要用luci-app-openvpn-server来启动服务，因为所以证书都是通用的，别人知道你IP和端口，直接就能连上你的openvpn服务。要用就用luci-app-openvpn插件，手创证书手动上传
