### ISSUE TITLE
luci 23.05依赖报错

### ISSUE THREAD

**Issue by lucky-beans** [coolsnowwolf/lede#13019]
### 详细叙述

运行./scripts/feeds install -a后
报错WARNING package/feeds/luci/luci-app-oscam/Makefile' has a dependency on 'oscam', which does not exist

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

feeds换回稳定的luci 18.06就没问题了

**Comment by yujieli001** [comment]
各种问题，不完美
