### ISSUE TITLE
动态DNS添加ddns-scripts_cloudflare.com-v4编译不进去

### ISSUE THREAD

**Issue by hahztbh** [coolsnowwolf/lede#13014]
### 详细叙述

lede新拉取源代码编译动态DNS添加ddns-scripts_cloudflare.com-v4编译不进去
![1](https://github.com/user-attachments/assets/169433a2-d494-4d4a-8984-b46eae90a8f9)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86_64

### 详细日志

lede新拉取源代码编译动态DNS添加ddns-scripts_cloudflare.com-v4编译不进去

**Comment by bi4tms** [comment]
这个好像是ddns-go的脚本，需要打掉在旧版luci中提供支持才能使用
@coolsnowwolf

**Comment by coolsnowwolf** [comment]
修复了
