### ISSUE TITLE
OpenWrt R9.5.1版本中 ShadowSocksR Plus+ 能不能加个负载均衡

### ISSUE THREAD

**Issue by primroses2006** [coolsnowwolf/lede#1302]
由于订阅的服务器较多,自动切换有没有什么规则吗?

能否增加个负载均衡功能,订阅的服务器几个捆绑成一个服务器,万分感谢.

**Comment by primroses2006** [comment]
HAProxy  Nginx 任意一种都行.

**Comment by coolsnowwolf** [comment]
UDP 怎么做？而且负载均衡带来的 IP 到处飘的问题，实际上会造成延迟变大很多，如何解决？

还有，节点里面既有ss，也有 ssr和 v2 ，如果需要负载均衡又有几百个节点，是否都需要开起来对应的进程？

**Comment by myeveryheart** [comment]
如果每次请求都走负载均衡，确实不好。
如果折中一下，固定时间（比如一小时）自动重选节点（比如ping最低的？），这样是否满足楼主的需要。

**Comment by coolsnowwolf** [comment]
ping 不代表节点质量，有些节点根本不让 ping

**Comment by myeveryheart** [comment]
原来如此，学习了。

**Comment by norikohxb** [comment]
L大您好，现在openwrt里面的ShadowSocksR Plus+菜单的主服务器里面的负载均衡其实是不能用的对吧，至少对于我的2个v2ray服务器是不可以用的，这个我理解是对的吗？
但是自动切换里面的 检查周期和超时时间是可以修改的，自动切换是有用的，但是负载均衡是无用的对吧？
