### ISSUE TITLE
固件刷了不分配IP，WiFi也没有，用TTL把启动的日志读出来了，大佬们修修

### ISSUE THREAD

**Issue by Kuron88** [coolsnowwolf/lede#13020]
### 详细叙述

固件刷了不分配IP，WiFi也没有

用TTL把启动的日志读出来了，大佬们修修

编译的过程是没有报错的，就是固件出来之后直接uboot刷fac固件就不启动，从旧版的保存配置升级sys的那个就可以正常用

uboot大雕的新版2024-4-9号的

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

AX1800 PRO亚瑟

### 详细日志

Format: Log Type - Time(microsec) - Message - Optional Info
Log Type: B - Since Boot(Power On Reset),  D - Delta,  S - Statistic
S - QC_IMAGE_VERSION_STRING=BOOT.XF.0.3-00100-IPQ60xxLZB-1
S - IMAGE_VARIANT_STRING=IPQ6018LA
S - OEM_IMAGE_VERSION_STRING=crm-ubuntu124
S - Boot Interface: eMMC
S - Secure Boot: Off
S - Boot Config @ 0x000a602c = 0x000002e3
S - JTAG ID @ 0x000a607c = 0x001390e1
S - OEM ID @ 0x000a6080 = 0x00000000
S - Serial Number @ 0x000a4128 = 0x3cdbf81e
S - OEM Config Row 0 @ 0x000a4188 = 0x0000000000000000
S - OEM Config Row 1 @ 0x000a4190 = 0x0000000000000000
S - Feature Config Row 0 @ 0x000a4130 = 0x0000800018200021
S - Feature Config Row 1 @ 0x000a4138 = 0x02c3e83783000009
S - PBL Patch Ver: 1
S - I-cache: On
S - D-cache: On
B -      3413 - PBL, Start
B -       592 - bootable_media_detect_entry, Start
B -      4339 - bootable_media_detect_success, Start
B -     91750 - elf_loader_entry, Start
B -     91923 - auth_hash_seg_entry, Start
B -     92904 - auth_hash_seg_exit, Start
B -     93398 - elf_segs_hash_verify_entry, Start
B -    119327 - elf_segs_hash_verify_exit, Start
B -    123517 - auth_xbl_sec_hash_seg_entry, Start
B -    123661 - auth_xbl_sec_hash_seg_exit, Start
B -    130208 - xbl_sec_segs_hash_verify_entry, Start
B -    130209 - xbl_sec_segs_hash_verify_exit, Start
B -    131138 - PBL, End
B -    109617 - SBL1, Start
B -    252540 - GCC [RstStat:0x0, RstDbg:0x600000] WDog Stat : 0x4
B -    254980 - clock_init, Start
D -      3782 - clock_init, Delta
B -    264618 - boot_flash_init, Start
D -     52246 - boot_flash_init, Delta
B -    319335 - sbl1_ddr_set_default_params, Start
D -       244 - sbl1_ddr_set_default_params, Delta
B -    325770 - boot_config_data_table_init, Start
D -      2165 - boot_config_data_table_init, Delta - (575 Bytes)
B -    334890 - CDT Version:2,Platform ID:8,Major ID:3,Minor ID:2,Subtype:1
B -    340441 - Image Load, Start
D -      6618 - OEM_MISC Image Loaded, Delta - (0 Bytes)
B -    349774 - Image Load, Start
D -      5063 - PMIC Image Loaded, Delta - (0 Bytes)
B -    357673 - sbl1_ddr_set_params, Start
B -    362645 - CPR configuration: 0x555
B -    365847 - Pre_DDR_clock_init, Start
D -       213 - Pre_DDR_clock_init, Delta
D -         0 - sbl1_ddr_set_params, Delta
B -    400190 - Image Load, Start
D -       549 - APDP Image Loaded, Delta - (0 Bytes)
B -    418765 - Image Load, Start
D -       518 - QTI_MISC Image Loaded, Delta - (0 Bytes)
B -    421418 - Image Load, Start
D -       793 - Auth Metadata
D -       702 - Segments hash check
D -     11804 - QSEE Dev Config Image Loaded, Delta - (36458 Bytes)
B -    435082 - Image Load, Start
D -      6557 - Auth Metadata
D -     10492 - Segments hash check
D -     92720 - QSEE Image Loaded, Delta - (1419168 Bytes)
B -    528321 - Image Load, Start
D -       610 - Auth Metadata
D -       946 - Segments hash check
D -     14884 - RPM Image Loaded, Delta - (102800 Bytes)
B -    544577 - Image Load, Start
D -       702 - Auth Metadata
D -      3233 - Segments hash check
D -     30104 - APPSBL Image Loaded, Delta - (581336 Bytes)
B -    603229 - SBL1, End
D -    494008 - SBL1, Delta
S - Flash Throughput, 42000 KB/s  (2141009 Bytes,  50315 us)
S - Core 0 Frequency, 800 MHz
S - DDR Frequency, 466 MHz

U-Boot 2016.01 (Apr 09 2024 - 19:22:47 +0800)

DRAM:  smem ram ptable found: ver: 2 len: 4
512 MiB
NAND:  Nand Flash error. Status = 80
Reset cmd status failed
SF: Unsupported flash IDs: manuf 00, jedec 0000, ext_jedec 0000
ipq_spi: SPI Flash not found (bus/cs/speed/mode) = (0/0/48000000/0)
0 MiB
MMC:   <NULL>: 0 (eMMC)
PCI0 is not defined in the device tree
In:    serial@78B1000
Out:   serial@78B1000
Err:   serial@78B1000
machid: 8030201
eth5 MAC Address from ART is not valid
Net:   MAC0 addr:dc:d8:7b:20:4f:4a
PHY ID1: 0x4d
PHY ID2: 0xd0b1
EDMA ver 1 hw init
Num rings - TxDesc:1 (0-0) TxCmpl:1 (0-0)
RxDesc:1 (15-15) RxFill:1 (7-7)
ipq6018_edma_alloc_rings: successfull
ipq6018_edma_setup_ring_resources: successfull
ipq6018_edma_configure_rings: successfull
ipq6018_edma_hw_init: successfull
eth0
Hit any key to stop autoboot:  0

MMC read: dev # 0, block # 16418, count 12288 ... 12288 blocks read: OK
## Loading kernel from FIT Image at 44000000 ...
   Using 'config@cp03-c2' configuration
   Trying 'kernel-1' kernel subimage
     Description:  ARM64 OpenWrt Linux-6.1.112
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x440000e8
     Data Size:    5064996 Bytes = 4.8 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x41000000
     Entry Point:  0x41000000
     Hash algo:    crc32
     Hash value:   9c418f6c
     Hash algo:    sha1
     Hash value:   80b91f24311d1c08d90c815174b314c5dacf996e
   Verifying Hash Integrity ... crc32+ sha1+ OK
## Loading fdt from FIT Image at 44000000 ...
   Using 'config@cp03-c2' configuration
   Trying 'fdt-1' fdt subimage
     Description:  ARM64 OpenWrt jdcloud_ax1800-pro device tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x444d4b50
     Data Size:    35389 Bytes = 34.6 KiB
     Architecture: AArch64
     Hash algo:    crc32
     Hash value:   49c313a9
     Hash algo:    sha1
     Hash value:   c271671e43079c0ca033074943a931affa344e42
   Verifying Hash Integrity ... crc32+ sha1+ OK
   Booting using the fdt blob at 0x444d4b50
   Uncompressing Kernel Image ... OK
   Loading Device Tree to 484f4000, end 484ffa3c ... OK
Could not find PCI in device tree
Using machid 0x8030201 from environment

Starting kernel ...

Jumping to AARCH64 kernel via monitor
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x51af8014]
[    0.000000] Linux version 6.1.112 (kurom@mac) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 11.3.0 r7005-f43ae1934) 11.3.0, GNU ld (GNU Binutils) 2.42) #0 SMP Fri Nov 15 07:57:32 2024
[    0.000000] Machine model: JDCloud AX1800 Pro / RE-SS-01
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000040ffffff]
[    0.000000]   node   0: [mem 0x0000000041000000-0x000000004a0fffff]
[    0.000000]   node   0: [mem 0x000000004a100000-0x000000004a4fffff]
[    0.000000]   node   0: [mem 0x000000004a500000-0x000000004a5fffff]
[    0.000000]   node   0: [mem 0x000000004a600000-0x000000004e3fffff]
[    0.000000]   node   0: [mem 0x000000004e400000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 18 pages/cpu s36456 r8192 d29080 u73728
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Kernel command line: console=ttyMSM0,115200n8 root=PARTUUID=cfaa8042-22e1-e95b-cc13-b1d505d9ab48 gpt rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 416924K/524288K available (8128K kernel code, 896K rwdata, 2284K rodata, 1280K init, 298K bss, 107364K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GICv2m: range[mem 0x0b00a000-0x0b00affc], SPI[448:479]
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 and mmio timer(s) running at 24.00MHz (virt/virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000001] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000150] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.000163] pid_max: default: 32768 minimum: 301
[    0.000625] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000638] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.002593] cblist_init_generic: Setting adjustable number of callback queues.
[    0.002601] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.002806] rcu: Hierarchical SRCU implementation.
[    0.002810] rcu:     Max phase no-delay instances is 1000.
[    0.003490] smp: Bringing up secondary CPUs ...
[    0.004178] Detected VIPT I-cache on CPU1
[    0.004299] CPU1: Booted secondary processor 0x0000000001 [0x51af8014]
[    0.004977] Detected VIPT I-cache on CPU2
[    0.005069] CPU2: Booted secondary processor 0x0000000002 [0x51af8014]
[    0.005716] Detected VIPT I-cache on CPU3
[    0.005806] CPU3: Booted secondary processor 0x0000000003 [0x51af8014]
[    0.005874] smp: Brought up 1 node, 4 CPUs
[    0.005883] SMP: Total of 4 processors activated.
[    0.005888] CPU features: detected: 32-bit EL0 Support
[    0.005893] CPU features: detected: CRC32 instructions
[    0.005959] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.005966] CPU: All CPU(s) started at EL1
[    0.005969] alternatives: applying system-wide alternatives
[    0.014299] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.014326] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.014563] pinctrl core: initialized pinctrl subsystem
[    0.015714] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.016271] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.016313] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.016362] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.016712] thermal_sys: Registered thermal governor 'step_wise'
[    0.016940] cpuidle: using governor menu
[    0.017246] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.017334] ASID allocator initialised with 65536 entries
[    0.079152] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.079165] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
[    0.079172] HugeTLB: registered 32.0 MiB page size, pre-allocated 0 pages
[    0.079177] HugeTLB: 0 KiB vmemmap can be freed for a 32.0 MiB page
[    0.079183] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.079187] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
[    0.079193] HugeTLB: registered 64.0 KiB page size, pre-allocated 0 pages
[    0.079197] HugeTLB: 0 KiB vmemmap can be freed for a 64.0 KiB page
[    0.081557] SCSI subsystem initialized
[    0.081754] usbcore: registered new interface driver usbfs
[    0.081793] usbcore: registered new interface driver hub
[    0.081828] usbcore: registered new device driver usb
[    0.082113] qcom_scm: convention: smc arm 64
[    0.083474] clocksource: Switched to clocksource arch_sys_counter
[    0.084689] NET: Registered PF_INET protocol family
[    0.084847] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.085702] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.085722] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.085735] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.085785] TCP bind hash table entries: 4096 (order: 5, 131072 bytes, linear)
[    0.085930] TCP: Hash tables configured (established 4096 bind 4096)
[    0.086143] MPTCP token hash table entries: 512 (order: 1, 12288 bytes, linear)
[    0.086204] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.086230] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.086405] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.086451] PCI: CLS 0 bytes, default 64
[    0.087147] hw perfevents: enabled with armv8_cortex_a53 PMU driver, 7 counters available
[    0.088784] workingset: timestamp_bits=46 max_order=17 bucket_order=0
[    0.094145] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.094158] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.097095] qcom-qmp-usb-phy 78000.ssphy: supply vdda-phy not found, using dummy regulator
[    0.097275] qcom-qmp-usb-phy 78000.ssphy: supply vdda-pll not found, using dummy regulator
[    0.098991] qcom-qusb2-phy 79000.qusb: supply vdd not found, using dummy regulator
[    0.099115] qcom-qusb2-phy 79000.qusb: supply vdda-pll not found, using dummy regulator
[    0.099158] qcom-qusb2-phy 79000.qusb: supply vdda-phy-dpdm not found, using dummy regulator
[    0.099351] qcom-qusb2-phy 79000.qusb: Registered Qcom-QUSB2 phy
[    0.103004] bam-dma-engine 704000.dma-controller: num-channels unspecified in dt
[    0.103020] bam-dma-engine 704000.dma-controller: num-ees unspecified in dt
[    0.107186] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.107855] msm_serial 78b1000.serial: msm_serial: detected port #0
[    0.107891] msm_serial 78b1000.serial: uartclk = 1843200
[    0.107995] 78b1000.serial: ttyMSM0 at MMIO 0x78b1000 (irq = 21, base_baud = 115200) is a MSM
[    0.108025] msm_serial: console setup on port #0
[    0.847714] printk: console [ttyMSM0] enabled
[    0.852850] msm_serial: driver initialized
[    0.862091] loop: module loaded
[    0.876127] i2c_dev: i2c /dev entries driver
[    0.881076] sdhci: Secure Digital Host Controller Interface driver
[    0.881127] sdhci: Copyright(c) Pierre Ossman
[    0.886195] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.892583] remoteproc remoteproc0: releasing cd00000.remoteproc
[    0.898763] NET: Registered PF_INET6 protocol family
[    0.903409] Segment Routing with IPv6
[    0.907357] In-situ OAM (IOAM) with IPv6
[    0.910878] NET: Registered PF_PACKET protocol family
[    0.914879] Bridge firewalling registered
[    0.919755] 8021q: 802.1Q VLAN Support v1.8
[    0.926118] mmc0: SDHCI controller on 7804000.mmc [7804000.mmc] using ADMA 64-bit
[    0.947015] cpufreq: cpufreq_online: CPU0: Running at unlisted initial frequency: 799999 KHz, changing to: 864000 KHz
[    0.948617] remoteproc remoteproc0: cd00000.remoteproc is avai▒[    0.963403] Waiting for root device PARTUUID=cfaa8042-22e1-e95b-cc13-b1d505d9ab48...
[    1.027927] mmc0: new HS200 MMC card at address 0001
[    1.028763] mmcblk0: mmc0:0001 SLD64G 57.1 GiB
[    1.060513] GPT:Primary header alternate_lba != Alt. header my_lba
[    1.060546] GPT:8683519 != 119783423
[    1.065616] GPT:last_usable_lbas don't match.
[    1.069313] GPT:8683486 != 119783390
[    1.073582] GPT:num_partition_entries don't match: 0x14 != 0x18
[    1.077215] GPT:partition_entry_array_crc32 values don't match: 0x1d12f38b != 0xe22aa402
[    1.082864] GPT:Primary header thinks Alt. header is not at the end of the disk.
[    1.091220] GPT:8683519 != 119783423
[    1.098575] GPT: Use GNU Parted to correct GPT errors.
[    1.102173]  mmcblk0: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17
[    1.109232] mmcblk0boot0: mmc0:0001 SLD64G 4.00 MiB
[    1.115568] mmcblk0boot1: mmc0:0001 SLD64G 4.00 MiB
[    1.120005] mmcblk0rpmb: mmc0:0001 SLD64G 4.00 MiB, chardev (247:0)
[    1.152647] VFS: Mounted root (squashfs filesystem) readonly on device 179:17.
[    1.153367] Freeing unused kernel memory: 1280K
[    1.158920] Run /sbin/init as init process
[    1.312984] init: Console is alive
[    1.313151] init: - watchdog -
[    2.255638] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    2.278592] raid6: skipped pq benchmark and selected neonx8
[    2.278630] raid6: using neon recovery algorithm
[    2.284100] xor: measuring software checksum speed
[    2.291736]    8regs           :  2521 MB/sec
[    2.296350]    32regs          :  2522 MB/sec
[    2.301024]    arm64_neon      :  2361 MB/sec
[    2.301199] xor: using function: 32regs (2522 MB/sec)
[    2.386641] Btrfs loaded, crc32c=crc32c-generic, zoned=no, fsverity=no
[    2.469419] ssdk_dt_parse_interrupt[941]:INFO:intr-gpio does not exist
[    2.526088] malibu_phy_api_ops_init[2082]:INFO:qca probe malibu phy driver succeeded!
[    2.883889] __adpt_hppe_uniphy_psgmii_mode_set[1194]:INFO:uniphy 0 psgmii channel selection
[    3.109689] regi_init[2525]:INFO:Initializing CPPE Done!!
[    3.109782] regi_init[2574]:INFO:qca-ssdk module init succeeded!
[    3.116456] EDMA ver 1 hw init
[    3.120353] EDMA HW Reset completed succesfully
[    3.123022] Num rings - TxDesc:1 (23-23) TxCmpl:1 (23-23)
[    3.127445] RxDesc:1 (15-15) RxFill:1 (7-7)
[    3.133359] dp2: ppe offload disabled: 0 for macid 2
[    3.136982] dp2: Switch attached to macid 2 status: 0
[    3.142590] Generic PHY 90000.mdio-1:01: attached PHY driver (mii_bus:phy_addr=90000.mdio-1:01, irq=POLL)
[    3.148047] dp3: ppe offload disabled: 0 for macid 3
[    3.156700] dp3: Switch attached to macid 3 status: 0
[    3.161869] Generic PHY 90000.mdio-1:02: attached PHY driver (mii_bus:phy_addr=90000.mdio-1:02, irq=POLL)
[    3.167574] dp4: ppe offload disabled: 0 for macid 4
[    3.176251] dp4: Switch attached to macid 4 status: 0
[    3.181407] Generic PHY 90000.mdio-1:03: attached PHY driver (mii_bus:phy_addr=90000.mdio-1:03, irq=POLL)
[    3.187147] dp5: ppe offload disabled: 0 for macid 5
[    3.195762] dp5: Switch attached to macid 5 status: 0
[    3.200942] Generic PHY 90000.mdio-1:04: attached PHY driver (mii_bus:phy_addr=90000.mdio-1:04, irq=POLL)
[    3.206723] **********************************************************
[    3.215289] * NSS Data Plane driver
[    3.221691] **********************************************************
[    3.245094] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    3.245145] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 1
[    3.250386] xhci-hcd xhci-hcd.1.auto: hcc params 0x0220fe65 hci version 0x110 quirks 0x0000008000010010
[    3.257101] xhci-hcd xhci-hcd.1.auto: irq 37, io mem 0x08a00000
[    3.266550] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    3.272309] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 2
[    3.277878] xhci-hcd xhci-hcd.1.auto: Host supports USB 3.0 SuperSpeed
[    3.285907] hub 1-0:1.0: USB hub found
[    3.292055] hub 1-0:1.0: 1 port detected
[    3.296155] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    3.300262] hub 2-0:1.0: USB hub found
[    3.307959] hub 2-0:1.0: 1 port detected
[    3.316432] usbcore: registered new interface driver usb-storage
[    3.317634] usbcore: registered new interface driver uas
[    3.321818] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.331898] init: - preinit -
[    8.703467] random: crng init done
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
[   11.154244] mount_root: loading kmods from internal overlay
[   11.178328] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[   11.182210] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[   11.338875] block: attempting to load /tmp/overlay/upper/etc/config/fstab
[   11.338977] block: unable to load configuration (fstab: Entry not found)
[   11.344703] block: attempting to load /tmp/overlay/etc/config/fstab
[   11.351465] block: unable to load configuration (fstab: Entry not found)
[   11.357646] block: attempting to load /etc/config/fstab
[   11.365338] block: unable to load configuration (fstab: Entry not found)
[   11.369323] block: no usable configuration
[   11.376413] block: attempting to load /etc/config/fstab
[   11.380185] block: unable to load configuration (fstab: Entry not found)
[   11.385403] block: no usable configuration
[   11.392766] loop0: detected capacity change from 0 to 2097152
[   11.433479] loop0: detected capacity change from 2097152 to 1862528
[   11.458557] mount_root: failed to mount -t f2fs /dev/loop0 /tmp/overlay: No such device
touch: /etc/bench.log: Read-only file system
caldata:  failed to extract calibration data from /dev/mmcblk0p15
[   11.543645] procd: - early -
[   11.543800] procd: - watchdog -
[   12.089194] procd: - watchdog -
[   12.089419] procd: - ubus -
[   12.245357] procd: - init -
Please press Enter to activate this console.
[   12.630259] urngd: v1.0.2 started.
[   13.073678] kmodloader: loading kernel modules from /etc/modules.d/*
[   13.141662] NET: Registered PF_ALG protocol family
[   13.151995] tun: Universal TUN/TAP device driver, 1.6
[   13.251395] NSS DDR size is 0x1000000
[   13.251426] ffffffc000d7a280: NSS core 0 DDR from 40000000 to 41000000
[   13.262225] gre: GRE over IPv4 demultiplexor driver
[   13.263394] ip_gre: GRE over IPv4 tunneling driver
[   13.284830] NSS DDR size is 0x1000000
[   13.284872] ffffffc000d7a280: nss core 0 booted successfully
[   13.310560] cryptodev: driver 1.13 loaded.
[   13.312482] nss_vlan_mgr_init_module[1926]:Module (Build Build Id: 11/15/24, 11:09:44) loaded
[   13.319881] PPP generic driver version 2.4.2
[   13.323318] NET: Registered PF_PPPOX protocol family
[   13.332341] ntfs3: Enabled Linux POSIX ACLs support
[   13.334616] usbcore: registered new interface driver cdc_wdm
[   13.339785] usbcore: registered new interface driver qmi_wwan_q
[   13.343748] usbcore: registered new interface driver qmi_wwan_f
[   13.350879] mhi_init Quectel_Linux_PCIE_MHI_Driver_V1.3.6
[   13.370941] usbcore: registered new interface driver cdc_acm
[   13.370979] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[   13.376929] usbcore: registered new interface driver cdc_ether
[   13.384919] usbcore: registered new interface driver cdc_ncm
[   13.390044] Loading modules backported from Linux version v6.1.24-0-g0102425ac76b
[   13.395175] Backport generated by backports.git v5.15.92-1-44-gd6ea70fafd36
[   13.404539] hso: drivers/net/usb/hso.c: Option Wireless
[   13.409392] usbcore: registered new interface driver hso
[   13.415407] usbcore: registered new interface driver huawei_cdc_ncm
[   13.423769] usbcore: registered new interface driver ipheth
[   13.480334] PPP MPPE Compression module registered
[   13.481685] PPTP driver version 0.8.5
[   13.487216] usbcore: registered new interface driver qmi_wwan
[   13.489191] NET: Registered PF_QIPCRTR protocol family
[   13.495867] usbcore: registered new interface driver rndis_host
[   13.499771] usbcore: registered new interface driver sierra_net
[   13.508662] usbcore: registered new interface driver ums-alauda
[   13.511630] usbcore: registered new interface driver ums-cypress
[   13.517518] usbcore: registered new interface driver ums-datafab
[   13.523594] usbcore: registered new interface driver ums-freecom
[   13.529599] usbcore: registered new interface driver ums-isd200
[   13.535838] usbcore: registered new interface driver ums-jumpshot
[   13.541219] usbcore: registered new interface driver ums-karma
[   13.547787] usbcore: registered new interface driver ums-sddr09
[   13.553278] usbcore: registered new interface driver ums-sddr55
[   13.559250] usbcore: registered new interface driver ums-usbat
[   13.566091] usbcore: registered new interface driver usbserial_generic
[   13.569701] usbserial: USB Serial support registered for generic
[   13.601418] xt_time: kernel timezone is -0000
[   13.602768] usbcore: registered new interface driver cdc_mbim
[   13.648303] ath11k c000000.wifi: ipq6018 hw1.0
[   13.648345] ath11k c000000.wifi: FW memory mode: 1
[   13.652014] remoteproc remoteproc0: powering up cd00000.remoteproc
[   13.670817] remoteproc remoteproc0: Booting fw image IPQ6018/q6_fw.mdt, size 7340
[   14.499176] remoteproc remoteproc0: remote processor cd00000.remoteproc is now up
[   14.500463] ath11k c000000.wifi: qmi ignore invalid mem req type 3
[   14.506105] usbcore: registered new interface driver option
[   14.506336] ath11k c000000.wifi: chip_id 0x0 chip_family 0x4 board_id 0xff soc_id 0xffffffff
[   14.511785] usbserial: USB Serial support registered for GSM modem (1-port)
[   14.517220] ath11k c000000.wifi: fw_version 0x250a04b8 fw_build_timestamp 2021-12-20 07:20 fw_build_id WLAN.HK.2.5.0.1-01208-QCAHKSWPL_SILICONZ-1
[   14.532921] usbcore: registered new interface driver qcserial
[   14.545884] usbserial: USB Serial support registered for Qualcomm USB modem
[   14.551850] kmodloader: done loading kernel modules from /etc/modules.d/*
[   14.728812] ath11k c000000.wifi: qmi failed to load CAL data file:cal-ahb-c000000.wifi.bin
[   14.728891] ath11k c000000.wifi: failed to load board data file: -12
[   40.700446] ECM init
[   40.700522] ECM database jhash random seed: 0x2545ccc4
[   40.703082] ECM init complete
[3383]: <msg> ModemManager (version 1.22.0) starting in system bus...

**Comment by xchename** [comment]
你的问题解决了吗？这边编译成功，刷rec进去，也是不分配地址，网络无法识别

**Comment by Kuron88** [comment]
这个大雕修复了

**Comment by xchename** [comment]
> 这个大雕修复了

大神，在问下你的luci切换指的时feed源里的切换还是makemenu里的切换？
