### ISSUE TITLE
ffmpeg编译报错

### ISSUE THREAD

**Issue by oppen321** [coolsnowwolf/lede#13034]
### 详细叙述

ffmpeg编译报错，感觉应该是ffmpeg版本的问题

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

libavcodec/x86/mathops.h: Assembler messages:
libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
lto-wrapper: fatal error: x86_64-openwrt-linux-musl-gcc returned 1 exit status
compilation terminated.
/home/runner/work/Lede-update/Lede-update/openwrt/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[4]: *** [ffbuild/library.mak:119: libavcodec/libavcodec.so.59] Error 1
make[4]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt/build_dir/target-x86_64_musl/ffmpeg-audio-dec/ffmpeg-5.1.2'
make[3]: *** [Makefile:754: /home/runner/work/Lede-update/Lede-update/openwrt/build_dir/target-x86_64_musl/ffmpeg-audio-dec/ffmpeg-5.1.2/.built] Error 2
make[3]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt/feeds/packages/multimedia/ffmpeg'
time: package/feeds/packages/ffmpeg/audio-dec/compile#2.52#0.27#2.86
    ERROR: package/feeds/packages/ffmpeg failed to build (build variant: audio-dec).
make[2]: *** [package/Makefile:116: package/feeds/packages/ffmpeg/compile] Error 1
make[2]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt'
make[1]: *** [package/Makefile:110: /home/runner/work/Lede-update/Lede-update/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt'
make: *** [/home/runner/work/Lede-update/Lede-update/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
解决了， binutil 2.41 的兼容性问题
