### ISSUE TITLE
88f6281 CPU编译的特殊软件内置的v2ray版本不对，不能启动。

### ISSUE THREAD

**Issue by flexyangjie** [coolsnowwolf/lede#1305]
自己编译的kirkwood 88f6281 CPU的R9.5.1最新版。特殊软件内置的v2yay不能启动。提示：
Illegal instruction“经查检发现v2ray文件是armv7的，这个88f6281 CPU是 armv5.用lede/package/lean/v2ray/files/arm/v2yra替换 /usr/bin/v2ray/的同名文件就可以了。但是用该文件替换编译目录的同名文件再编译后还是变成了原来一样的

**Comment by coolsnowwolf** [comment]
还真是，漏了 armv5 的支持

**Comment by coolsnowwolf** [comment]
修复了

**Comment by flexyangjie** [comment]
哇，这么快就修复了。再请教一下，修复后我该怎么操作再编译呢？

**Comment by shjohnnyyu** [comment]
git pull
