### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by AugustLiu** [coolsnowwolf/lede#13076]
### 详细叙述

curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:46: /home/august-linux/lede/dl/srelay-0.4.8p3.tar.gz] Error 2
make[3]: Leaving directory '/home/august-linux/lede/package/lean/srelay'
time: package/lean/srelay/compile#0.41#0.21#847.27
    ERROR: package/lean/srelay failed to build.
make[2]: *** [package/Makefile:116: package/lean/srelay/compile] Error 1
make[2]: Leaving directory '/home/august-linux/lede'
make[1]: *** [package/Makefile:110: /home/august-linux/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/august-linux/lede'
make: *** [/home/august-linux/lede/include/toplevel.mk:231：world] 错误 2

another problem:How can I add the chinese ?

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

MTK7688

### 详细日志

curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:46: /home/august-linux/lede/dl/srelay-0.4.8p3.tar.gz] Error 2
make[3]: Leaving directory '/home/august-linux/lede/package/lean/srelay'
time: package/lean/srelay/compile#0.41#0.21#847.27
    ERROR: package/lean/srelay failed to build.
make[2]: *** [package/Makefile:116: package/lean/srelay/compile] Error 1
make[2]: Leaving directory '/home/august-linux/lede'
make[1]: *** [package/Makefile:110: /home/august-linux/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/august-linux/lede'
make: *** [/home/august-linux/lede/include/toplevel.mk:231：world] 错误 2

**Comment by coolsnowwolf** [comment]
rm -f /home/august-linux/lede/dl/srelay-0.4.8p3.tar.gz
