### ISSUE TITLE
使用LEDE   23.05源码编译固件无法拉取passwall最新版本

### ISSUE THREAD

**Issue by pata166** [coolsnowwolf/lede#13080]
### 详细叙述

feeds.conf.default添加src-git passwall https://github.com/xiaorouji/openwrt-passwall
src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2
后一直拉取的[4.78-3]
之后更新的版本无法拉取
虚拟机重新全新安装，再编译也是一样

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

尝试了全新安装的虚拟机重新编译也是

**Comment by oppen321** [comment]
rm -rf feeds/luci/applications/luci-app-passwall
rm -rf feeds/luci/applications/luci-app-passwall2
rm -rf feeds/luci/applications/luci-app-openclash
移除lede的luci库里的插件就可以了
