### ISSUE TITLE
有办法可以远程命令行修改默认主题吗

### ISSUE THREAD

**Issue by xianshanlai** [coolsnowwolf/lede#13102]
### 详细叙述

刷完固件后登录后台页面报下面错了，我怀疑是我编译新固件时没有勾选之前固件用的主题，但是刷固件时又选择了保存当前配置。当前控制台进不去了，但是路由器上网正常，想请教下这种情况该如何处理，谢谢！
![eb393d98d27b87851c7e1b26f2e69b4](https://github.com/user-attachments/assets/63bc65d8-7631-48d9-921c-5d4a3f770e8a)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86-64

### 详细日志

编译时没有问题

**Comment by xingshu1990** [comment]
通过ssh等其他方式连接上openwrt

nano /etc/config/luci
或vi /etc/config/luci

下面显示的是已经安装的模板，上方1这里改动默认的模板。
![image](https://github.com/user-attachments/assets/3522fbd5-4cb8-4551-ae6d-9af82ff052e5)

**Comment by xianshanlai** [comment]
解决了，谢谢

**Comment by xingshu1990** [comment]
> 解决了，谢谢

不客气
