### ISSUE TITLE
二次编译git pull提示您当前不在一个分支上

### ISSUE THREAD

**Issue by peng6767** [coolsnowwolf/lede#13107]
### 详细叙述

内核版本 | 6.6.35
OpenWrt R24.6.6

ppp$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0 (from 0)
展开对象中: 100% (7/7), 619 字节 | 103.00 KiB/s, 完成.
来自 https://github.com/coolsnowwolf/lede
   6b5e1a552..af098a176  master     -> origin/master
您当前不在一个分支上。
请指定您要合并哪一个分支。
详见 git-pull(1)。

    git pull <远程> <分支>

ppp$ git branch -a
* (HEAD detached at 847b81b67)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

同志们怎样同步支线？？？？？？？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

X86

### 详细日志

ppp$ git pull
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0 (from 0)
展开对象中: 100% (7/7), 619 字节 | 103.00 KiB/s, 完成.
来自 https://github.com/coolsnowwolf/lede
   6b5e1a552..af098a176  master     -> origin/master
您当前不在一个分支上。
请指定您要合并哪一个分支。
详见 git-pull(1)。

    git pull <远程> <分支>

ppp$ git branch -a
* (HEAD detached at 847b81b67)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by 19901019** [comment]
我比较简单粗暴，直接回退好几个提交，然后再git pull

**Comment by coolsnowwolf** [comment]
git reset
