### ISSUE TITLE
自内核6.6.58之后的更新导致passwall失效

### ISSUE THREAD

**Issue by XXXstyle** [coolsnowwolf/lede#13100]
### 详细叙述

截至到内核6.6.58更新一切正常，之后更新到最新后passwall无法使用，请问是最近的更新有修改防火墙相关之类的吗
Linux 6.6.62
LUCI 18.06

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

Nanopi R5S

### 详细日志

未记录相关问题

**Comment by suizhenmin** [comment]
我这边最后一个能用的版本是上个月23号编译的版本，再之后就启动不了了，也不知2边是哪边的问题

**Comment by jdnt** [comment]
楼主的情况是passwall启动以后的问题吗，我之前遇到类似的问题。因为是做旁路，当时发现客户端是正常的，但是openwrt无法获取正确的dns解析。最后发现问题出在/etc/dnsmasq.conf中，把lan口的dns加进去就行了。目前6.6.62+passwall24.11.18一切正常。

**Comment by GreatMichaelLee** [comment]
参考我提到bug的讨论线程：

https://github.com/xiaorouji/openwrt-passwall/issues/3508

**Comment by henryyifan** [comment]
小白插个嘴，半年多没更新了，今天晚上编译了一下最新的版本之后，SSRP也不能用，不知道是否有一样的情况？

**Comment by coolsnowwolf** [comment]
> 小白插个嘴，半年多没更新了，今天晚上编译了一下最新的版本之后，SSRP也不能用，不知道是否有一样的情况？

SSR Plus 是因为 Xray 格式大改了, 需要单独重置下 SSR Plus 配置，/etc/init.d/shadowsocksr reset

**Comment by henryyifan** [comment]
> > 小白插个嘴，半年多没更新了，今天晚上编译了一下最新的版本之后，SSRP也不能用，不知道是否有一样的情况？
> 
> SSR Plus 是因为 Xray 格式大改了, 需要单独重置下 SSR Plus 配置，/etc/init.d/shadowsocksr reset

感谢lean大佬出现回复！

**Comment by coolsnowwolf** [comment]
感觉还是软件适配的问题， XXR Plus 一切正常

**Comment by GreatMichaelLee** [comment]
> 感觉还是软件适配的问题， XXR Plus 一切正常

大佬们比国足还厉害，让我这个小白一愣一愣的，哈哈

![image](https://github.com/user-attachments/assets/4f527029-3e1a-4fe9-836a-5bdd6fad713c)

**Comment by xiaorouji** [comment]
6.6.62 內核，iptables 的確有問題。MARK等 mod 無法正常工作。
6.12 內核，一切正常。

**Comment by coolsnowwolf** [comment]
已修复 6.6 的 mark mod 问题
![image](https://github.com/user-attachments/assets/4b1a2789-adcb-4af3-a5c7-61d92a824bac)

**Comment by drw2005** [comment]
> > 小白插个嘴，半年多没更新了，今天晚上编译了一下最新的版本之后，SSRP也不能用，不知道是否有一样的情况？
> 
> SSR Plus 是因为 Xray 格式大改了, 需要单独重置下 SSR Plus 配置，/etc/init.d/shadowsocksr reset

原来如此，我试试。
