### ISSUE TITLE
x86固件分区

### ISSUE THREAD

**Issue by kentYang1124** [coolsnowwolf/lede#1310]
我编译Lean的9.5.1的x86源码，修改了分区大小，把那个90MB的改大了，结果编译出来的固件，只要一重启，配置就会变回最初的缺省设置。如果不动分区的大小，编译出来的固件没有问题。想知道是不是不能变动那2个分区的大小？还是其他地方也需要修改呢？

**Comment by lifetyper** [comment]
参考这个问题：
https://github.com/coolsnowwolf/lede/issues/348

在 > Kernel modules > Filesystems 选上 kmod-fs-f2fs 就可以了

**Comment by lifetyper** [comment]
简单的说，不选这个，overlay加载失败，就自动挂载到tmp(内存)去了，所以一重启内存清空，配置也就丢了。

**Comment by kentYang1124** [comment]
谢谢，回去再试一下

**Comment by kentYang1124** [comment]
可以了
