### ISSUE TITLE
缺失snd-hda-scodec-component.ko模块

### ISSUE THREAD

**Issue by oppen321** [coolsnowwolf/lede#13113]
### 详细叙述

从报错信息中可以看出，kmod-sound-hda-codec-realtek 依赖于内核模块 snd-hda-scodec-component.ko，但在编译环境中缺失了该文件

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86 6.12内核

### 详细日志

SHELL= flock /home/runner/work/Lede-update/Lede-update/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/runner/work/Lede-update/Lede-update/openwrt/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kernel/. /home/runner/work/Lede-update/Lede-update/openwrt/staging_dir/target-x86_64_musl/root-x86/'
touch /home/runner/work/Lede-update/Lede-update/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.kernel_installed
Package kmod-sound-hda-codec-realtek is missing dependencies for the following libraries:
snd-hda-scodec-component.ko
make[3]: *** [modules/sound.mk:390: /home/runner/work/Lede-update/Lede-update/openwrt/bin/targets/x86/64/packages/kmod-sound-hda-codec-realtek_6.12-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt/package/kernel/linux'
time: package/kernel/linux/compile#3.39#0.47#3.83
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt'
make[1]: *** [package/Makefile:110: /home/runner/work/Lede-update/Lede-update/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/Lede-update/Lede-update/openwrt'
make: *** [/home/runner/work/Lede-update/Lede-update/openwrt/include/toplevel.mk:231: world] Error 2

**Comment by coolsnowwolf** [comment]
已修复 6.12 支持
