### ISSUE TITLE
树莓派3B编译不过

### ISSUE THREAD

**Issue by mouchanchan** [coolsnowwolf/lede#13121]
### 详细叙述

编译报错如下
Applying /home/vagrant/lede/target/linux/bcm27xx/patches-6.6/950-0297-staging-vchiq_arm-Add-36-bit-address-support.patch using plaintext: 
patching file drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c
Hunk #2 FAILED at 119.
Hunk #3 succeeded at 143 (offset -5 lines).
Hunk #4 succeeded at 178 (offset -5 lines).
Hunk #5 succeeded at 338 (offset -5 lines).
Hunk #6 succeeded at 352 (offset -5 lines).
Hunk #7 succeeded at 450 (offset -5 lines).
Hunk #8 succeeded at 505 (offset -5 lines).
Hunk #9 succeeded at 527 (offset -5 lines).
Hunk #10 succeeded at 557 (offset -5 lines).
Hunk #11 succeeded at 598 (offset -5 lines).
Hunk #12 succeeded at 611 (offset -5 lines).
Hunk #13 succeeded at 1818 (offset -13 lines).
Hunk #14 succeeded at 1851 (offset -13 lines).
1 out of 14 hunks FAILED -- saving rejects to file drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c.rej
Patch failed!  Please fix /home/vagrant/lede/target/linux/bcm27xx/patches-6.6/950-0297-staging-vchiq_arm-Add-36-bit-address-support.patch!
make[4]: *** [Makefile:43: /home/vagrant/lede/build_dir/target-aarch64_cortex-a53_musl/linux-bcm27xx_bcm2710/linux-6.6.63/.prepared_cae474d470e179ed5f5fa3239f7f85a8] Error 1
make[4]: Leaving directory '/home/vagrant/lede/target/linux/bcm27xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/vagrant/lede/target/linux'
time: target/linux/compile#9.12#9.54#18.18
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/vagrant/lede'
make[1]: *** [target/Makefile:23: /home/vagrant/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/vagrant/lede'
make: *** [/home/vagrant/lede/include/toplevel.mk:231: world] Error 2

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

树莓派3B

### 详细日志

Applying /home/vagrant/lede/target/linux/bcm27xx/patches-6.6/950-0297-staging-vchiq_arm-Add-36-bit-address-support.patch using plaintext: 
patching file drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c
Hunk #2 FAILED at 119.
Hunk #3 succeeded at 143 (offset -5 lines).
Hunk #4 succeeded at 178 (offset -5 lines).
Hunk #5 succeeded at 338 (offset -5 lines).
Hunk #6 succeeded at 352 (offset -5 lines).
Hunk #7 succeeded at 450 (offset -5 lines).
Hunk #8 succeeded at 505 (offset -5 lines).
Hunk #9 succeeded at 527 (offset -5 lines).
Hunk #10 succeeded at 557 (offset -5 lines).
Hunk #11 succeeded at 598 (offset -5 lines).
Hunk #12 succeeded at 611 (offset -5 lines).
Hunk #13 succeeded at 1818 (offset -13 lines).
Hunk #14 succeeded at 1851 (offset -13 lines).
1 out of 14 hunks FAILED -- saving rejects to file drivers/staging/vc04_services/interface/vchiq_arm/vchiq_arm.c.rej
Patch failed!  Please fix /home/vagrant/lede/target/linux/bcm27xx/patches-6.6/950-0297-staging-vchiq_arm-Add-36-bit-address-support.patch!
make[4]: *** [Makefile:43: /home/vagrant/lede/build_dir/target-aarch64_cortex-a53_musl/linux-bcm27xx_bcm2710/linux-6.6.63/.prepared_cae474d470e179ed5f5fa3239f7f85a8] Error 1
make[4]: Leaving directory '/home/vagrant/lede/target/linux/bcm27xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/vagrant/lede/target/linux'
time: target/linux/compile#9.12#9.54#18.18
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/vagrant/lede'
make[1]: *** [target/Makefile:23: /home/vagrant/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/vagrant/lede'
make: *** [/home/vagrant/lede/include/toplevel.mk:231: world] Error 2

**Comment by WYC-2020** [comment]
这patch 需要修复，坐等他们修复吧
