### ISSUE TITLE
cpu频率

### ISSUE THREAD

**Issue by kentYang1124** [coolsnowwolf/lede#1312]
刷了lean最新的R9.5.1 x86_64的固件，发现cpu的频率一直保持在基础频率，不会自动降频，是没有这个功能吗？之前用的koolshare的lede，是可以动态调整的

**Comment by coolsnowwolf** [comment]
支持的，用最新代码编译

**Comment by kentYang1124** [comment]
在menuconfig里面需要修改什么吗？我保持默认选择是否可以？

**Comment by kentYang1124** [comment]
用了最新的源码编译了，还是不会动态调整

**Comment by kentYang1124** [comment]
我终于发现频率是会调整，但是概况页面的cpu信息里面的频率不会变，一直是固定的值。不知道为什么luci.sys.exec("grep 'MHz' /proc/cpuinfo.....")这段语句拿不到正确的值。
