### ISSUE TITLE
RT-ACRH17 编译qbittorrent 失败

### ISSUE THREAD

**Issue by ashaaf** [coolsnowwolf/lede#13134]
### 详细叙述

编译 qbittorrent，提示 libtorrent-rasterbar 版本需要大于 1.2.19  
![image](https://github.com/user-attachments/assets/7cbda269-a88d-49ff-b9ec-ee75414139b8)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

RT-ACRH17

### 详细日志

![image](https://github.com/user-attachments/assets/8e8e670a-3062-416e-8f05-7b252efe4ad6)

**Comment by coolsnowwolf** [comment]
已解决
