### ISSUE TITLE
编译固件出现图片问题，有大佬知道怎么解决么

### ISSUE THREAD

**Issue by xiaomayi755259** [coolsnowwolf/lede#13135]
### 详细叙述

![20241128_155541](https://github.com/user-attachments/assets/d29379fa-4957-477e-9533-e8a3a629e4c4)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86/64

### 详细日志

![20241128_155541](https://github.com/user-attachments/assets/bc2fc92c-244b-41e3-804c-9e1f27a464c3)

**Comment by chen-wilde** [comment]
换默认主题

**Comment by t96mytell** [comment]
主题

**Comment by coolsnowwolf** [comment]
别用 lua 版本的主题
