### ISSUE TITLE
源码已经支持ARRIS SBR-AC3200P了，但是编译好了不知道怎么刷

### ISSUE THREAD

**Issue by xuansongzhang** [coolsnowwolf/lede#1314]
已经用源码编译好了ARRIS SBR-AC3200P的固件，求刷机方法，谢谢！

**Comment by xuansongzhang** [comment]
看来暂时没人刷过，再等等看。

**Comment by F7bonacci** [comment]
> 看来暂时没人刷过，再等等看。

大佬刷成功了吗？

**Comment by xuansongzhang** [comment]
> > 看来暂时没人刷过，再等等看。
> 
> 大佬刷成功了吗？

要拆机在CFE下用TFTP刷机。目前ARRIS的OpenWrt无线驱动版本太旧，不好用，不建议刷OpenWrt，我已经刷回原厂固件了。

**Comment by F7bonacci** [comment]
> > > 看来暂时没人刷过，再等等看。
> > 
> > 
> > 大佬刷成功了吗？
> 
> 要拆机在CFE下用TFTP刷机。目前ARRIS的OpenWrt无线驱动版本太旧，不好用，不建议刷OpenWrt，我已经刷回原厂固件了。

想刷一下试试，方便把你的刷机包发我一下吗，neal_yu@163.com,感谢。
