### ISSUE TITLE
X86最新源码5.15内核本地编译报错

### ISSUE THREAD

**Issue by minfengyk** [coolsnowwolf/lede#13161]
### 详细叙述

我是在Ubuntu22，大佬更新readme后，安装最新依赖环境下，X86下5.15内核本地编译报错，多次编译同样错误

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

VMware - Intel(R) Core(TM) i3-7100U CPU软路由

### 详细日志

SHELL= flock /home/minfeng/lede/tmp/.root-copy.flock -c 'cp -fpR /home/minfeng/lede/build_dir/target-x86_64_musl/linux-x86_64/packages/.pkgdir/kernel/. /home/minfeng/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/minfeng/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.kernel_installed
ERROR: module '/home/minfeng/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.173/fs/smb/server/ksmbd.ko' is missing.
make[3]: *** [modules/fs.mk:395: /home/minfeng/lede/bin/targets/x86/64/packages/kmod-fs-ksmbd_5.15.173-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/minfeng/lede/package/kernel/linux'
time: package/kernel/linux/compile#2.29#0.10#2.43
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/home/minfeng/lede'
make[1]: *** [package/Makefile:110: /home/minfeng/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/minfeng/lede'
make: *** [/home/minfeng/lede/include/toplevel.mk:231: world] Error 2

**Comment by yanxin152133** [comment]
把smb取消勾选编译试试，如果你不用共享文件那个功能的话
![image](https://github.com/user-attachments/assets/bb30f07f-8445-4fc1-a8cd-67e8d9b12926)

**Comment by yanxin152133** [comment]
或者试试这个
![image](https://github.com/user-attachments/assets/ab947b90-e47f-4179-9c85-5f5870659139)

**Comment by minfengyk** [comment]
> 或者试试这个 ![image](https://private-user-images.githubusercontent.com/43341537/392213296-ab947b90-e47f-4179-9c85-5f5870659139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODMzNjMsIm5iZiI6MTczMzI4MzA2MywicGF0aCI6Ii80MzM0MTUzNy8zOTIyMTMyOTYtYWI5NDdiOTAtZTQ3Zi00MTc5LTljODUtNWY1ODcwNjU5MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAzMzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYWY5MzA3MDE4OGU3MjM3N2YyMTQwYzQwNzY0YTQ4MmJkZmJjMDY2MWU0OTUwM2M1YWQ2YTY2YTYxZDczYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eO1Jpm9Z6PbVu8j8MjyBGYzkqVkXVktWimOyKXVDoMk)

感谢指点！我是看大佬更新了依赖，在纯净的ubuntu22下，全新安装依赖，拉取源码环境下编译的。多次编译仍然报错，应该不是缓存问题。请教如果需要保留磁盘共享功能情况下，怎么解决？

**Comment by coolsnowwolf** [comment]
已经可以了 5.15 内核没有这个 kmod, 统一用 oot 的版本吧

**Comment by minfengyk** [comment]
> 已经可以了 5.15 内核没有这个 kmod, 统一用 oot 的版本吧

已经成功编译了，感谢大佬🙏
