### ISSUE TITLE
网络中的主机名可以取消编译吗？

### ISSUE THREAD

**Issue by hahztbh** [coolsnowwolf/lede#13171]
### 详细叙述

请问各位大佬，Lede固件中主机名插件可以不编译吗？可以的话应该在make menuconfig中取消那个名称呢，我找不到🙏
![IMG_20241205_161606_276](https://github.com/user-attachments/assets/3b939ad2-e232-4ddf-bce5-5a3b1db43d69)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86_64

### 详细日志

不需要日志

**Comment by coolsnowwolf** [comment]
这个是 dhcp dnsmasq 的一个基本功能
