### ISSUE TITLE
6.12崩溃

### ISSUE THREAD

**Issue by Jejz168** [coolsnowwolf/lede#13180]
### 详细叙述

帮忙看看是什么问题
用的1806编译

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

[系统日志.txt](https://github.com/user-attachments/files/18046240/default.txt)
[内核日志.txt](https://github.com/user-attachments/files/18046241/default.txt)

**Comment by coolsnowwolf** [comment]
说过了，6.12 上游还不支持 nfsd

**Comment by Jejz168** [comment]
> 说过了，6.12 上游还不支持 nfsd

谢谢大雕
