### ISSUE TITLE
最新6.1.119编译报错

### ISSUE THREAD

**Issue by shjy10000** [coolsnowwolf/lede#13189]
### 详细叙述

6.6.63是可以一把过的，换成了test kenerl后变成了6.1.119,然后编译的时候就一直报这个错误

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

radxa e25

### 详细日志

/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/rk3588-armsom-sige7.dts:10:10: fatal error: rk3588.dtsi: No such file or directory
   10 | #include "rk3588.dtsi"
      |          ^~~~~~~~~~~~~
compilation terminated.
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/rk3576-armsom-sige5.dts:14:10: fatal error: rk3576.dtsi: No such file or directory
   14 | #include "rk3576.dtsi"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[5]: *** [Makefile:82: /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3576-armsom-sige5.dtb] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [Makefile:82: /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3588-armsom-sige7.dtb] Error 1
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3528-armsom-sige1.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3528-armsom-sige1.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-photonicat.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-photonicat.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-xiaobao-nas-v1.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-xiaobao-nas-v1.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-rsb4810.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-rsb4810.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-armsom-sige3.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-armsom-sige3.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/scripts/dtc/dtc -O dtb -i/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/ -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address    -o /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-dlfr100.dtb /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-dlfr100.dtb.tmp
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/rk3568-photonicat.dts:492.3-13: Warning (reg_format): /mmc@fe2c0000/sdio_wifi@1:reg: property has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-photonicat.dtb: Warning (i2c_bus_reg): Failed prerequisite 'reg_format'
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-photonicat.dtb: Warning (spi_bus_reg): Failed prerequisite 'reg_format'
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/rk3568-photonicat.dts:491.14-496.4: Warning (avoid_default_addr_size): /mmc@fe2c0000/sdio_wifi@1: Relying on default #address-cells value
/home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.1.119/arch/arm64/boot/dts/rockchip/rk3568-photonicat.dts:491.14-496.4: Warning (avoid_default_addr_size): /mmc@fe2c0000/sdio_wifi@1: Relying on default #size-cells value
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3528-armsom-sige1.dtb.tmp
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-photonicat.dtb.tmp
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-dlfr100.dtb.tmp
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3399-xiaobao-nas-v1.dtb.tmp
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-rsb4810.dtb.tmp
rm -f /home/sh/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/image-rk3568-armsom-sige3.dtb.tmp
make[5]: Leaving directory '/home/sh/lede/target/linux/rockchip/image'
make[4]: *** [Makefile:24: install] Error 2
make[4]: Leaving directory '/home/sh/lede/target/linux/rockchip'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/home/sh/lede/target/linux'
time: target/linux/install#12.27#5.50#4.70
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/install] Error 1
make[2]: Leaving directory '/home/sh/lede'
make[1]: *** [target/Makefile:24: /home/sh/lede/staging_dir/target-aarch64_generic_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/sh/lede'
make: *** [/home/sh/lede/include/toplevel.mk:231：world] 错误 2

**Comment by aiamadeus** [comment]
test 内核后面会换 6.12，现在用 6.1 没意义

**Comment by shjy10000** [comment]
> 新适配的型号已经不支持6.1了，老型号也跟着报错

确实，其他低版本的也会报错

**Comment by coolsnowwolf** [comment]
RK3576 和 RK3528 已经不再支持老内核了
