### ISSUE TITLE
luci首页显示可以优化一下。

### ISSUE THREAD

**Issue by yulinsoft** [coolsnowwolf/lede#13194]
### 详细叙述

luci首页显示可以优化一下。现在显示有两个温度。
![批注 2024-12-09 212919](https://github.com/user-attachments/assets/3af949fa-a5b5-4728-8864-523f0d69dfb5)

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

N1

### 详细日志

界面优化

**Comment by xingshu1990** [comment]
可自行修改：/usr/lib/lua/luci/view/admin_status/index.htm
谷歌搜索：温度 /usr/lib/lua/luci/view/admin_status/index.htm 或者openwrt /usr/lib/lua/luci/view/admin_status/index.htm

位置
![image](https://github.com/user-attachments/assets/ae8a6cd6-6a97-4ee6-8655-cbf5e14bad5e)

**Comment by yulinsoft** [comment]
感谢你的回复。

> 可自行修改：/usr/lib/lua/luci/view/admin_status/index.htm 谷歌搜索 /usr/lib/lua/luci/view/admin_status/index.htm 或者openwrt /usr/lib/lua/luci/view/admin_status/index.htm 至于里面具体怎么修改，要么看别人的教程，要么先全文丢给AI让其翻译，或者直接修改 然后先自行测试。 注意此文档先备份，以便后面覆盖。 免得修改后，不知道修改了什么地方，又不知道怎么修复。
