### ISSUE TITLE
网卡驱动问题，X86的2019-5-4版本，网卡是Atheros AR8132，未找到合适的驱动。

### ISSUE THREAD

**Issue by brryaa** [coolsnowwolf/lede#1319]
Lean,
问题如题，安装后本机网卡不响应，疑为缺驱动。之前用18.06官版也是需要加装驱动。外接网卡usb网卡能配置之后opkg update全通过，但是opkg install kmod-atl1e报错，如附图。请帮忙看看。谢谢。
![photo5107301871630002192](https://user-images.githubusercontent.com/42986711/57907429-fe25a280-78af-11e9-9503-41541ac95f46.jpg)

**Comment by coolsnowwolf** [comment]
编译时选上
