### ISSUE TITLE
make download还是有问题

### ISSUE THREAD

**Issue by hicom-omni** [coolsnowwolf/lede#13197]
### 详细叙述

好多天了，每次到下载这2个包就不行

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86-64

### 详细日志

![1](https://github.com/user-attachments/assets/3f02ffe3-9a22-4d2d-b6ce-053a4dfbd2e1)
![2](https://github.com/user-attachments/assets/ab427822-ccb4-4b92-8655-fcbfdb4f1c01)

**Comment by yanxin152133** [comment]
这个问题应该前几天刚提过
https://github.com/coolsnowwolf/lede/issues/13173#issuecomment-2521911246

**Comment by xingshu1990** [comment]
> 这个问题应该前几天刚提过 [#13173 (comment)](https://github.com/coolsnowwolf/lede/issues/13173#issuecomment-2521911246)

是提过，不过我不知道这个编译是哪个插件，所以不知道上面我说的内容，是否可行_,

**Comment by yanxin152133** [comment]
![image](https://github.com/user-attachments/assets/1f0e71b8-767c-476a-bae0-1b8fc2d5497c)

**Comment by hicom-omni** [comment]
> > 这个问题应该前几天刚提过 [#13173 (comment)](https://github.com/coolsnowwolf/lede/issues/13173#issuecomment-2521911246)
> 
> 是提过，不过我不知道这个编译是哪个插件，所以不知道上面我说的内容，是否可行_,

怎么解决的？

**Comment by xingshu1990** [comment]
> > > 这个问题应该前几天刚提过 [#13173 (comment)](https://github.com/coolsnowwolf/lede/issues/13173#issuecomment-2521911246)
> > 
> > 
> > 是提过，不过我不知道这个编译是哪个插件，所以不知道上面我说的内容，是否可行_,
> 
> 怎么解决的？

就是上面另外那位朋友发的，我在已经结贴的帖子里的回复：自行尝试解压，单独编译。

**Comment by coolsnowwolf** [comment]
这个是你用了第三方的库的问题

**Comment by aiamadeus** [comment]
![image](https://github.com/user-attachments/assets/660839ea-f7f5-46fb-b79d-f81c430bfaa5)
单纯你网络问题

**Comment by hicom-omni** [comment]
> 这个是你用了第三方的库的问题

腾讯云硅谷或HK的机器，16核32G，22.04 Ubuntu系统

安装依赖时出现2次粉色屏幕全部直接回车

在cd lede后输入2条命令：
sed -i "/helloworld/d" "feeds.conf.default"
echo "src-git helloworld https://github.com/fw876/helloworld.git;main" >> "feeds.conf.default"

进入make menuconfig后未修改任何内容直接保存

make download -j8还是报错

**Comment by hicom-omni** [comment]
> 这个是你用了第三方的库的问题
换用阿里云下载成功了，哎

**Comment by coolveyron** [comment]
> > 这个是你用了第三方的库的问题
> > 换用阿里云下载成功了，哎

我已经找到原因了，与第三方库关系也不大，主要问题还在腾讯云上，你试试直接用OpenWrt官方的包进行编译看看，什么也不改，git下来直接按照步骤编译，你就知道为啥了。嘿嘿!

**Comment by hicom-omni** [comment]
> > > 这个是你用了第三方的库的问题
> > > 换用阿里云下载成功了，哎
> 
> 我已经找到原因了，与第三方库关系也不大，主要问题还在腾讯云上，你试试直接用OpenWrt官方的包进行编译看看，什么也不改，git下来直接按照步骤编译，你就知道为啥了。嘿嘿!

年纪大了，懒得搞了，啥原因啊？

**Comment by coolveyron** [comment]
> > > > 这个是你用了第三方的库的问题
> > > > 换用阿里云下载成功了，哎
> > 
> > 
> > 我已经找到原因了，与第三方库关系也不大，主要问题还在腾讯云上，你试试直接用OpenWrt官方的包进行编译看看，什么也不改，git下来直接按照步骤编译，你就知道为啥了。嘿嘿!
> 
> 年纪大了，懒得搞了，啥原因啊？

腾讯云的所有服务器已经无法正常编译openwrt，换阿里云吧。所有腾讯云的服务器都无法下载部分组件。

核心问题在git.openwrt.org上，能ping通，但是返回的是假地址，是无法从git.openwrt.org中获取正确的组件hash，所以下载都出错。

已经问过腾讯云的客服了，他们知道，说是运营商的问题，正在积极协调解决。

美区？香港？日本？都是运营商的问题？我没搞明白他们的网络出口的架构是啥样的。还是服务器都在国内，走GFW后再通过他们自己的专线到其他境外服务器？GFW给屏蔽了？但是阿里云没问题啊。

不懂腾讯云的操作是不是故意而为之。
