### ISSUE TITLE
请教：编译intel-microcode会不会导致CPU性能下降？

### ISSUE THREAD

**Issue by jyy508** [coolsnowwolf/lede#13201]
### 详细叙述

最近发现LEDE这边把intel-microcode微码更新到最新了，早有耳闻英特尔最新微码会导致性能下降，该不该编译进去？因为LEDE现在编译默认勾选了微码，如果不编译会不会有啥坏处？

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86

### 详细日志

无

**Comment by coolsnowwolf** [comment]
会的，尽量使用 AMD 的 CPU
