### ISSUE TITLE
6.12内核下xr_usb_serial_common 模块编译缺少头文件

### ISSUE THREAD

**Issue by ntbowen** [coolsnowwolf/lede#13227]
### 详细叙述

fatal error: asm/unaligned.h: No such file or directory

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

photonicat

### 详细日志

make[3]: Entering directory '/home/ntbowen/openwrt/lede/feeds/packages/libs/xr_usb_serial_common'
mkdir -p /home/ntbowen/openwrt/lede/dl
SHELL= flock /home/ntbowen/openwrt/lede/tmp/.usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz.flock -c '  	/home/ntbowen/openwrt/lede/scripts/download.pl "/home/ntbowen/openwrt/lede/dl" "usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz" "f8572929a66d2eeadc80ef68fb26d5b7a824b87b7959352ff44ad4b3a29dfb78" "" || (  /home/ntbowen/openwrt/lede/scripts/dl_github_archive.py --dl-dir="/home/ntbowen/openwrt/lede/dl" --url="https://github.com/kasbert/epsolar-tracer" --version="90ad530166f096347a5a57b6f9eb21c422a40fd9" --subdir="usb-serial-xr_usb_serial_common-2023-03-21-90ad5301" --source="usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz" --hash="f8572929a66d2eeadc80ef68fb26d5b7a824b87b7959352ff44ad4b3a29dfb78" || ( 	echo "Checking out files from the git repository..."; mkdir -p /home/ntbowen/openwrt/lede/tmp/dl && cd /home/ntbowen/openwrt/lede/tmp/dl && rm -rf usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 && [ \! -d usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 ] && git clone  https://github.com/kasbert/epsolar-tracer usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 && (cd usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 && git checkout 90ad530166f096347a5a57b6f9eb21c422a40fd9 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 && git log -1 --format='\''@%ct'\''` && rm -rf usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 | 	xz -zc -7e > /home/ntbowen/openwrt/lede/tmp/dl/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz && mv /home/ntbowen/openwrt/lede/tmp/dl/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz /home/ntbowen/openwrt/lede/dl/ && rm -rf usb-serial-xr_usb_serial_common-2023-03-21-90ad5301; );  )    '
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  850k  100  850k    0     0   299k      0  0:00:02  0:00:02 --:--:--  299k
touch /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.prepared_1fd9de38234cfef27db9892eeded2f48_6664517399ebbbc92a37c5bb081b5c53_check
. /home/ntbowen/openwrt/lede/include/shell.sh; xzcat /home/ntbowen/openwrt/lede/dl/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301.tar.xz | tar -C /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301

Applying ./patches/0001-fix-kernel-6.6-builds.patch using plaintext: 
patching file xr_usb_serial_common-1a/xr_usb_serial_common.c
touch /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.prepared_1fd9de38234cfef27db9892eeded2f48_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.configured_*
rm -f /home/ntbowen/openwrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.xr_usb_serial_common_installed
(cd /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/./; if [ -x ./configure ]; then find /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/ -name config.guess | xargs -r chmod u+w; find /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/ -name config.guess | xargs -r -n1 cp --remove-destination /home/ntbowen/openwrt/lede/scripts/config.guess; find /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/ -name config.sub | xargs -r chmod u+w; find /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/ -name config.sub | xargs -r -n1 cp --remove-destination /home/ntbowen/openwrt/lede/scripts/config.sub; AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301=usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD="aarch64-openwrt-linux-musl-ld.bfd" NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301=usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301=usb-serial-xr_usb_serial_common-2023-03-21-90ad5301 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/home/ntbowen/openwrt/lede/staging_dir/toolchain-aarch64_generic_gcc-13.3.0_musl/usr/include -I/home/ntbowen/openwrt/lede/staging_dir/toolchain-aarch64_generic_gcc-13.3.0_musl/include -I/home/ntbowen/openwrt/lede/staging_dir/toolchain-aarch64_generic_gcc-13.3.0_musl/include/fortify " LDFLAGS="-L/home/ntbowen/openwrt/lede/staging_dir/toolchain-aarch64_generic_gcc-13.3.0_musl/usr/lib -L/home/ntbowen/openwrt/lede/staging_dir/toolchain-aarch64_generic_gcc-13.3.0_musl/lib -fuse-ld=bfd -znow -zrelro "   ./configure --target=aarch64-openwrt-linux --host=aarch64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.built
touch /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.built_check
make  -C "/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.5" ARCH="arm64" CROSS_COMPILE="aarch64-openwrt-linux-musl-" M="/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/xr_usb_serial_common-1a" modules
make[4]: Entering directory '/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.5'
  CC [M]  /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/xr_usb_serial_common-1a/xr_usb_serial_common.o
/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/xr_usb_serial_common-1a/xr_usb_serial_common.c:51:10: fatal error: asm/unaligned.h: No such file or directory
   51 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:229: /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/xr_usb_serial_common-1a/xr_usb_serial_common.o] Error 1
make[5]: *** [/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.5/Makefile:1937: /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/xr_usb_serial_common-1a] Error 2
make[4]: *** [Makefile:224: __sub-make] Error 2
make[4]: Leaving directory '/home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-6.12.5'
make[3]: *** [Makefile:42: /home/ntbowen/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/usb-serial-xr_usb_serial_common-2023-03-21-90ad5301/.built] Error 2
make[3]: Leaving directory '/home/ntbowen/openwrt/lede/feeds/packages/libs/xr_usb_serial_common'
time: package/feeds/packages/xr_usb_serial_common/compile#0.39#0.25#3.45
    ERROR: package/feeds/packages/xr_usb_serial_common failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/xr_usb_serial_common/compile] Error 1
make[2]: Leaving directory '/home/ntbowen/openwrt/lede'
make[1]: *** [package/Makefile:110: /home/ntbowen/openwrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ntbowen/openwrt/lede'
make: *** [/home/ntbowen/openwrt/lede/include/toplevel.mk:231：world] 错误 2

**Comment by coolsnowwolf** [comment]
fixed
