### ISSUE TITLE
kodexporer下载的存储路径变量是否取错

### ISSUE THREAD

**Issue by zcluo** [coolsnowwolf/lede#1322]
lede/package/lean/luci-app-kodexplorer/luasrc/model/cbi/kodexplorer/api.lua

214行的local client_file = get_config_option("storage_directory", "/mnt/sda1/kodexplorer")
storage_directory是不是应该是project_directory？

**Comment by zcluo** [comment]
get_config_option函数好像也有问题

**Comment by zcluo** [comment]
改了页面的项目存放目录点了应用，下载还是把路径放到/mnt/sda1/kodexporer下

**Comment by ope087** [comment]
nginx的端口也没有跟随设置

**Comment by Lienol** [comment]
的确是有这个问题，因为之前写着写着没写了。已修复。。。等大雕同步
