### ISSUE TITLE
为什么 v2ray 路径是 /usr/bin/v2ray/v2ray

### ISSUE THREAD

**Issue by funnypro** [coolsnowwolf/lede#1324]
如题

按照标准来说应该不需要那个 v2ray 文件夹吧？

**Comment by zcluo** [comment]
还是需要这个目录里面还又geo.data等好几个文件

**Comment by funnypro** [comment]
我看了下，目录里只有v2ray这一个文件啊

**Comment by coolsnowwolf** [comment]
以前是需要好几个文件的，所以预留了

以后也需要 v2ray server

**Comment by funnypro** [comment]
那是否会在 PATH 追加 /usr/bin/v2ray 或者在 /usr/bin 增加 v2rayc/v2rays 软链接对应 /usr/bin/v2ray 下的客户端与服务端？

虽然说个人比较推荐后者

**Comment by cnekol** [comment]
请问为何我的v2ray在/usr/bin/v2ray下只是v2ray一个文件？ 这个文件时v2ray core吗？目前在想后面更新的事情，但一直找不到相关的位置。

**Comment by funnypro** [comment]
> 下只是v2ray一个文件？ 这个文件

目前来说，似乎只是 v2ray 的客户端
