### ISSUE TITLE
usb3.0如何关闭

### ISSUE THREAD

**Issue by kentYang1124** [coolsnowwolf/lede#1325]
openwrt r9，newifi3的机型，没有那个优化中心吗？要怎么可以开关usb3.0？

**Comment by zxlhhyccc** [comment]
加一个USB3管理插件就行。。。。

**Comment by kentYang1124** [comment]
可以说一下这个插件，在menuconfig里面叫什么吗？谢谢

**Comment by ttxl123** [comment]
@zxlhhyccc  编译 了一个，现在2.4G不正常，几秒钟一断，怀疑是usb3.0的锅，求指导怎样关闭，谢谢了。。。

**Comment by wsltshh** [comment]
> 可以说一下这个插件，在menuconfig里面叫什么吗？谢谢

所以我也想知道，到底有没有，有的话选哪个？
