### ISSUE TITLE
希望默认开启nano设备的全部分区

### ISSUE THREAD

**Issue by kuretru** [coolsnowwolf/lede#133]
如题，希望WNDR4300默认开启所有分区，即#33相同的问题

**Comment by cym422948** [comment]
在make menuconfig前输入以下指令 调整分区即可
sed -i  s/'23552k(ubi),25600k@0x6c0000(firmware)'/'120832k(ubi),122880k@0x6c0000(firmware)'/ target/linux/ar71xx/image/legacy.mk
