### ISSUE TITLE
网站的百度盘失效,能不能给个OpenWrt R9.5.1 for x86/x64 下载链接?

### ISSUE THREAD

**Issue by woshizwn** [coolsnowwolf/lede#1338]
网站的百度盘失效,能不能给个OpenWrt R9.5.1 for x86/x64 下载链接?

**Comment by kentYang1124** [comment]
链接: https://pan.baidu.com/s/1YtJk3u58bmb1gk1ylyMipA 提取码: s31t

**Comment by willisworley** [comment]
> 链接: https://pan.baidu.com/s/1YtJk3u58bmb1gk1ylyMipA 提取码: s31t

老鸟，能不能再分享一次

**Comment by kentYang1124** [comment]
链接: https://pan.baidu.com/s/1dL0WJ8BlGkjr-L_BkL-biQ 提取码: 06xn




------------------ 原始邮件 ------------------
发件人: "Willis Worley"<notifications@github.com>;
发送时间: 2019年6月9日(星期天) 下午2:16
收件人: "coolsnowwolf/lede"<lede@noreply.github.com>;
抄送: "kent yang"<281646256@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [coolsnowwolf/lede] 网站的百度盘失效,能不能给个OpenWrt R9.5.1 for x86/x64 下载链接? (#1338)



 
链接: https://pan.baidu.com/s/1YtJk3u58bmb1gk1ylyMipA 提取码: s31t
  
老鸟，能不能再分享一次

**Comment by xin8157** [comment]
同求分享，谢谢
