### ISSUE TITLE
SSR Plus+ 不走代理的局域网LAN IP是不是无效？

### ISSUE THREAD

**Issue by S0MEW0LF** [coolsnowwolf/lede#1340]
我局域网内有两台NAS机器，IP地址分别都添加到了“不走代理的局域网LAN IP”里面。
我在SSR Plus+的运行模式是“绕过中国大陆IP模式”，因为现在很多PT站点都是放在国外，但是其实直连是没有问题的，今天我突然发现PT站点BT客户端上面显示的是我v2ray服务器的IP地址，而不是我真实的国内地址。BT客户端是运行在NAS机器上的，例如IP是192.168.1.100，是已经添加进了“不走代理的局域网LAN IP”设置里面的。
这个v2ray本来是很稳定的，我还奇怪怎么每隔几天服务器都突然慢和连接不上，原来是一直有走BT流量，因为这个服务器不是自己控制的，也暂时不能添加跳过BT流量的设置。
这是不是“不走代理的局域网LAN IP”这个设置没有生效呢？
能否像官方的SS那样，添加一个只代理制定端口的设置呢？例如只代理22-1023之间的端口。

**Comment by lifetyper** [comment]
你的adbyby plus开了全局模式吧，这两个有冲突，把adbyby plus的全局模式关掉就行了。
没细看具体是iptables哪里冲突，也许是bug，也许根本上也冲突也没法避免。

**Comment by S0MEW0LF** [comment]
是的，我的adbyby plus开了全局模式。谢谢解答，用plus+过滤模式应该没有这个问题吧？

**Comment by lifetyper** [comment]
你有这问的功夫，自己试一下都应该把这个issue close了。
