### ISSUE TITLE
重启路由器，ssr plus总是未运行状态

### ISSUE THREAD

**Issue by bigbighill** [coolsnowwolf/lede#1342]
重启路由器，ssr plus总是未运行状态，要手动启动？默认如此还是bug？

**Comment by bigbighill** [comment]
/etc/rc.d/S60flowoffload:  * Running script '/var/etc/shadowsocksr.include'
Sun May 26 11:42:09 2019 daemon.notice procd: /etc/rc.d/S60flowoffload:    ! Skipping due to path error: No such file or directory

**Comment by bigbighill** [comment]
```
Sun May 26 16:16:19 2019 daemon.notice procd: /etc/rc.d/S60flowoffload:  * Running script '/var/etc/shadowsocksr.include'
Sun May 26 16:16:19 2019 daemon.notice procd: /etc/rc.d/S60flowoffload:    ! Skipping due to path error: No such file or directory

```
系统日志只有这两条
1、重启路由后，/var/etc/shadowsocksr.include 这个文件确实没有
2、/etc/init.d/shadowsockr start 后这个文件就出现了。
3、启动项目里 90 shadowsocksr

**Comment by bigbighill** [comment]
新路由3 newifi3 d2

**Comment by bigbighill** [comment]
没有办法，只好在启动项中 exit 0上方添加
/etc/init.d/shadowsocksr start

**Comment by qyh214** [comment]
> 
> 
> 没有办法，只好在启动项中 exit 0上方添加
> /etc/init.d/shadowsocksr start

我尝试了重启，似乎无法复现，我这两天再测试下最新的，你尝试下清除所有配置后再试试。另外请提供下你使用的固件的提交hash

**Comment by jliveusa** [comment]
同样遇到这个问题，要手动启动才可以开启ssrplus，用的官方openwrt

**Comment by orange-cat-fantacy** [comment]
俺也一样

**Comment by KimBin** [comment]
很简单 需要在“服务器” tab 里 启动服务器，就可以了。有gfw列表会自动选择的。

**Comment by orange-cat-fantacy** [comment]
thinks qwq



在 2020-04-02 00:24:16，"kimbin" <notifications@github.com> 写道：

很简单 需要在“服务器” tab 里 启动服务器，就可以了。有gfw列表会自动选择的。

**Comment by rc452860** [comment]
修改`/etc/init.d/shadowsocksr`和`/usr/bin/ssr-rules`中替换`iptables `为`iptables -w `注意空格。

**Comment by rc452860** [comment]
> 修改`/etc/init.d/shadowsocksr`和`/usr/bin/ssr-rules`中替换`iptables `为`iptables -w `注意空格。

该问题极有可能是因为iptables锁导致的。通过查询openwrt日志`loadread`，搜索`shadow`关键字
```
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:01 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:02 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:02 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:02 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sat Jan  1 20:43:02 2022 user.err ssr-rules[2783]: Can't redirect, please check the iptables.
Sat Jan  1 20:43:02 2022 daemon.notice procd: /etc/rc.d/S95shadowsocksr: ssr-rules[2783]: Can't redirect, please check the iptables.
```
发现如下日志。

**Comment by Jeremy-JM** [comment]
> thinks qwq 在 2020-04-02 00:24:16，"kimbin" <notifications@github.com> 写道： 很简单 需要在“服务器” tab 里 启动服务器，就可以了。有gfw列表会自动选择的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你是没理解到问题。问题说的是，已经配置好SSR，重启路由后，SSR未自动运行好。

**Comment by whc23mj** [comment]
修改/etc/init.d/shadowsocksr中的START=99

**Comment by Jeremy-JM** [comment]
> > thinks qwq 在 2020-04-02 00:24:16，"kimbin" [notifications@github.com](mailto:notifications@github.com) 写道： 很简单 需要在“服务器” tab 里 启动服务器，就可以了。有gfw列表会自动选择的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 你是没理解到问题。问题说的是，已经配置好SSR，重启路由后，SSR未自动运行好。

问题出在，70版本的img，安装出来，系统空间太小了，如果使用FileBrowser或者可道云，又不修改默认配置，会导致上述问题和一些其他奇怪的问题。

**Comment by zorrose82** [comment]
最近版本又出现了，设置了每周3-5点重启机器，结果每次ssrplus起不来，以前都要登陆web进去点一下ssrplus确认就好了
我直接在计划任务里加了一行，6点重启一下ssrplus
00 5 * * 3 sleep 5 && touch /etc/banner && reboot
00 6 * * 3  /etc/init.d/shadowsocksr  restart
