### ISSUE TITLE
full cone nat可否提供关闭的选项？

### ISSUE THREAD

**Issue by MeIsReallyBa** [coolsnowwolf/lede#1343]
以前有段时间记得是可以关闭的。7621弱鸡路由器。lede 17.01和op18.06都测了下，开启full cone nat后，在迅雷这种大量udp连接的下载情形时，无线有线性能都存在一定程度的下降。

**Comment by coolsnowwolf** [comment]
这样啊。。。那为你增加这个选项吧，在“ 防火墙” 这里设置

![image](https://user-images.githubusercontent.com/31687149/58385173-cdb3d600-801e-11e9-815e-c0cd863eb6b4.png)

**Comment by MeIsReallyBa** [comment]
感谢支持

**Comment by xizhi560** [comment]
除了这里设置会影响nat，还有什么地方会改善nat吗？
