### ISSUE TITLE
软件源用哪个呀?默认的 openwrt.proxy.ustclug 不能用

### ISSUE THREAD

**Issue by jkzxccc** [coolsnowwolf/lede#1347]
如题, opkg update 更新不了, 也打不开网页

**Comment by libinanshu** [comment]
https://openwrt.proxy.ustclug.org/

https

https

https

**Comment by jkzxccc** [comment]
> https://openwrt.proxy.ustclug.org/
> 
> https
> 
> https
> 
> https

果真,  改了之后腰不酸腿不疼了!!!

**Comment by rlad2333** [comment]
> https://openwrt.proxy.ustclug.org/
> 
> https
> 
> https
> 
> https

finally.  yes
