### ISSUE TITLE
固件内核更新到4.14了吗，刚才编译了一下，怎么还是4.9？

### ISSUE THREAD

**Issue by ZhaoqiangCn** [coolsnowwolf/lede#1352]
是哪里有设置开关选择吗？

**Comment by libinanshu** [comment]
编译切换内核：
打开LEDE目录/target/linux/架构/Makefile
KERNEL_PATCHVER:=4.9
具体支持内核版本
include/kernel-version.mk

**Comment by ZhaoqiangCn** [comment]
> 编译切换内核：
> 打开LEDE目录/target/linux/架构/Makefile
> KERNEL_PATCHVER:=4.9
> 具体支持内核版本
> include/kernel-version.mk

感谢
