### ISSUE TITLE
luci-app-hd-idle  不显示

### ISSUE THREAD

**Issue by Mattraks** [coolsnowwolf/lede#1356]
luci-app-hd-idle
选择编译后图形界面不显示，卸载后再默认源中下载安装可以显示使用
x86-x64

**Comment by zxlhhyccc** [comment]
会显示，名字叫硬盘休眠

**Comment by Mattraks** [comment]
我知道是叫硬盘休眠 该源码编译出来的不显示

**Comment by xun188** [comment]
删除lean/default-settings/files/zzz-default-settings文件中的再编译，或者自己编辑下/usr/lib/lua/luci/controller/samba.lua，把nas改回来
rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
