### ISSUE TITLE
ssr plus的编译选项在最新代码里不见了

### ISSUE THREAD

**Issue by WROIATE** [coolsnowwolf/lede#1357]
![image](https://user-images.githubusercontent.com/44677306/58471862-737a5880-8177-11e9-9ebf-3e636280e8e3.png)
不太清楚为啥ssr plus的选项没了，有谁能说一下嘛？

**Comment by signigelchan** [comment]
Love&Peace👇 .

**Comment by WROIATE** [comment]
> Love&Peace👇 .

是直接没了？还是有芝麻开门？

**Comment by signigelchan** [comment]
> > Love&Peace👇 .
> 
> 是直接没了？还是有芝麻开门？

我也是最近发现的。

**Comment by WROIATE** [comment]
> > > Love&Peace👇 .
> > 
> > 
> > 是直接没了？还是有芝麻开门？
> 
> 我也是最近发现的。
lean不会是被喝茶了吧。。。

**Comment by cuishitian77** [comment]
确实是没有了。不知道怎么回事，还是坐等答复吧

**Comment by hanxi** [comment]
https://github.com/coolsnowwolf/lede/commit/b5daaadc0c6c17397efbc4d5c281c75b2bc571d7#commitcomment-33616316

**Comment by cuishitian77** [comment]
谢了，找到了。

**Comment by dongfangy2011** [comment]
> 谢了，找到了。

怎么找到了，我找不到

**Comment by hanxi** [comment]
> > 谢了，找到了。
> 
> 怎么找到了，我找不到

看我发的链接啊

**Comment by WROIATE** [comment]
> [b5daaad#commitcomment-33616316](https://github.com/coolsnowwolf/lede/commit/b5daaadc0c6c17397efbc4d5c281c75b2bc571d7#commitcomment-33616316)

感谢！
