### ISSUE TITLE
The amule compilations error on ar71xx platform

### ISSUE THREAD

**Issue by wheretoteardown** [coolsnowwolf/lede#136]
The amule compilations error on ar71xx platform with the newest code , reverted to kernel 4.4, while the previous version worked well.

Here is the error report:

configure.ac:342: warning: gl_XSIZE is m4_require'd but not m4_defun'd
/home/yhk/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/intl.m4:25: AM_INTL_SUBDIR is expanded from...
/home/yhk/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/gettext.m4:57: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_FCNTL_O_FLAGS is m4_require'd but not m4_defun'd
/home/yhk/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/intl.m4:25: AM_INTL_SUBDIR is expanded from...
/home/yhk/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/gettext.m4:57: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
Running autoheader
configure.ac:342: warning: gl_VISIBILITY is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_LOCK is m4_require'd but not m4_defun'd
aclocal.m4:2289: gt_INTL_SUBDIR_CORE is expanded from...
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_TYPE_WCHAR_T is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_PRINTF_POSIX is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_XSIZE is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_FCNTL_O_FLAGS is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
Running autoconf
configure.ac:342: warning: gl_VISIBILITY is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_LOCK is m4_require'd but not m4_defun'd
aclocal.m4:2289: gt_INTL_SUBDIR_CORE is expanded from...
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_TYPE_WCHAR_T is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_PRINTF_POSIX is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_XSIZE is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_FCNTL_O_FLAGS is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
Creating pixmaps Makefile.am
Running automake --foreign -a -c -f
configure.ac:342: warning: gl_VISIBILITY is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_LOCK is m4_require'd but not m4_defun'd
aclocal.m4:2289: gt_INTL_SUBDIR_CORE is expanded from...
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_TYPE_WCHAR_T is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gt_PRINTF_POSIX is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_XSIZE is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: gl_FCNTL_O_FLAGS is m4_require'd but not m4_defun'd
aclocal.m4:2103: AM_INTL_SUBDIR is expanded from...
aclocal.m4:1536: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...
configure.ac:342: the top level
configure.ac:342: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:342: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:342: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:475: error: required file 'intl/Makefile.in' not found
Makefile.am:4: error: required directory ./intl does not exist
src/Makefile.am:72: warning: source file 'kademlia/utils/UInt128.cpp' is in a subdirectory,
src/Makefile.am:72: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/Makefile.am:97: warning: source file 'kademlia/kademlia/Entry.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/kademlia/Indexed.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/kademlia/SearchManager.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:97: warning: source file 'kademlia/routing/RoutingBin.cpp' is in a subdirectory,
src/Makefile.am:97: but option 'subdir-objects' is disabled
src/Makefile.am:123: warning: source file 'extern/wxWidgets/listctrl.cpp' is in a subdirectory,
src/Makefile.am:123: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Kademlia.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Prefs.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/Search.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/kademlia/UDPFirewallTester.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/net/KademliaUDPListener.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/net/PacketTracking.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/routing/Contact.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/Makefile.am:140: warning: source file 'kademlia/routing/RoutingZone.cpp' is in a subdirectory,
src/Makefile.am:140: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../CFile.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../SafeFile.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../OtherFunctions.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../Tag.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/utils/fileview/Makefile.am:3: warning: source file '../../kademlia/utils/UInt128.cpp' is in a subdirectory,
src/utils/fileview/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/ExternalConnector.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/OtherFunctions.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/RLE.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/NetworkFunctions.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/LoggerConsole.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
src/webserver/src/Makefile.am:3: warning: source file '$(top_srcdir)/src/UPnPBase.cpp' is in a subdirectory,
src/webserver/src/Makefile.am:3: but option 'subdir-objects' is disabled
unittests/muleunit/Makefile.am:2: warning: source file '$(top_srcdir)/src/libs/common/MuleDebug.cpp' is in a subdirectory,
unittests/muleunit/Makefile.am:2: but option 'subdir-objects' is disabled
unittests/muleunit/Makefile.am:2: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/muleunit/Makefile.am:2: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/SafeFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/MemFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/Tag.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:51: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:51: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/kademlia/utils/UInt128.cpp' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:19: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:19: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/SafeFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/CFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/MemFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/kademlia/utils/UInt128.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/Tag.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:40: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:40: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:25: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:25: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:25: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:25: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/NetworkFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/LibSocket.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/libs/common/Format.cpp' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:34: warning: source file '$(top_srcdir)/src/libs/common/strerror_r.c' is in a subdirectory,
unittests/tests/Makefile.am:34: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:43: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:43: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:43: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:43: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:28: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:28: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:28: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:28: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/Path.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/StringFunctions.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
unittests/tests/Makefile.am:46: warning: source file '$(top_srcdir)/src/libs/common/TextFile.cpp' is in a subdirectory,
unittests/tests/Makefile.am:46: but option 'subdir-objects' is disabled
make[3]: *** [Makefile:111: /home/yhk/lede/build_dir/target-mips_24kc_musl/aMule-2.3.2/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/yhk/lede/package/lean/amule'
make[2]: *** [package/Makefile:111: package/lean/amule/compile] Error 2
make[2]: Leaving directory '/home/yhk/lede'
make[1]: *** [package/Makefile:105: /home/yhk/lede/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yhk/lede'
make: *** [/home/yhk/lede/include/toplevel.mk:209: world] Error 2

**Comment by AndyX-Net** [comment]
Same Error...
