### ISSUE TITLE
跪求大雕增加adbyby plus的规则源。

### ISSUE THREAD

**Issue by shuiyuechangchun** [coolsnowwolf/lede#1370]
如题，求大雕集成规则源，可以拦截大部分广告，我浏览器插件用的就是这两个。
1、https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt
2、http://git.oschina.net/halflife/list/raw/master/ad3.txt
[附上贴吧地址。https://tieba.baidu.com/p/4951429693](url)
跪求大雕集成啊

**Comment by ihuaer** [comment]
可以添加第三方规则
