### ISSUE TITLE
各位大神，帮我看看这个是什么问题，编译了3-4次每次都是提示这个问题。

### ISSUE THREAD

**Issue by lzx2009vb** [coolsnowwolf/lede#1378]
系统环境：Ubuntu14.04LTS
按照readme操作

make[6]: *** [src/CMakeFiles/noddos.dir/noddos.cxx.o] Error 1
make[6]: Leaving directory `/home/xuan/lede/build_dir/target-x86_64_musl/noddos-0.5.5'
make[5]: *** [src/CMakeFiles/noddos.dir/all] Error 2
make[5]: Leaving directory `/home/xuan/lede/build_dir/target-x86_64_musl/noddos-0.5.5'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/xuan/lede/build_dir/target-x86_64_musl/noddos-0.5.5'
make[3]: *** [/home/xuan/lede/build_dir/target-x86_64_musl/noddos-0.5.5/.built] Error 2
make[3]: Leaving directory `/home/xuan/lede/feeds/packages/net/noddos'
time: package/feeds/packages/noddos/compile#5.07#0.74#11.91
make[2]: *** [package/feeds/packages/noddos/compile] Error 2
make[2]: Leaving directory `/home/xuan/lede'
make[1]: *** [/home/xuan/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/xuan/lede'
make: *** [world] 错误 2

**Comment by OldTaoge** [comment]
错误的重点在你复制的上方
