### ISSUE TITLE
关于:iptables v1.8.2 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)

### ISSUE THREAD

**Issue by aesirteam** [coolsnowwolf/lede#1380]
iptables v1.8.2 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by aesirteam** [comment]
pull最新代码，设备MT7621 xiaomi R3G

**Comment by hcym** [comment]
n1也是如此，不过用的是官方源码
