### ISSUE TITLE
可道云nginx配置文件

### ISSUE THREAD

**Issue by sjikdaq231** [coolsnowwolf/lede#1382]
请问可道云是不是不支持ipv6端口访问？
可道云nginx的配置文件难道不是etc/nginx/nginx.conf? 
打开nginx.conf在里面没看到在路由界面设置的端口配置，请问是在哪里设置端口可以ipv6 访问呢？

**Comment by alphavip** [comment]
/usr/sbin/nginx -c /var/etc/kodexplorer/nginx.conf

**Comment by alphavip** [comment]
> 请问可道云是不是不支持ipv6端口访问？
> 可道云nginx的配置文件难道不是etc/nginx/nginx.conf?
> 打开nginx.conf在里面没看到在路由界面设置的端口配置，请问是在哪里设置端口可以ipv6 访问呢？

/usr/sbin/nginx -c /var/etc/kodexplorer/nginx.conf
