### ISSUE TITLE
SSPLUS没了

### ISSUE THREAD

**Issue by andy19801210** [coolsnowwolf/lede#1383]
大雕老师，以后还会有么？

**Comment by zxlhhyccc** [comment]
等5月35日过后会有。。。。

**Comment by hcym** [comment]
过去啦，期待

**Comment by fefz** [comment]
还没有

**Comment by pho-coder** [comment]
为啥没了啊

**Comment by lxwq** [comment]
commits,find old version,copy to lean folder

**Comment by Mr-xn** [comment]
@andy19801210 @zxlhhyccc @hcym @fefz @pho-coder 

`cd lede`，and then :
`git checkout 2915c44a11ca0ee40b51ff5d9c18a0da1951e170`
`luci-app-ssr-plus` will back agian in `package/lean/luci-app-ssr-plus`
and you can copy the dir of `luci-app-ssr-plus` and `git pull` the code to the latest


> commits,find old version,copy to lean folder

**Comment by lifetyper** [comment]
有这闲工夫瞎等都不能去学一下git基本操作？

**Comment by lan542662** [comment]
> 有这闲工夫瞎等都不能去学一下git基本操作？

大哥就服你，哈哈哈，我学好了，然后ssr-plus也来了，大雕的编译，让我学会了
1. 安装archlinux 2. git操作 3. linux基础命令4. 搜索和提问解决问题 5. 国家和社会问题的个人应对方法 

lean == 万恶之源
