### ISSUE TITLE
SIP002 URIs

### ISSUE THREAD

**Issue by nameless3721** [coolsnowwolf/lede#1384]
如果以后还弄xxrplus的话能否增加对SIP002 URIs的支持呢 让xx也能订阅到

**Comment by coolsnowwolf** [comment]
这个是啥？ 有描述吗？

**Comment by nameless3721** [comment]
> 这个是啥？ 有描述吗？

https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html  解析Base64的订阅链接到ss里面  我看到好像是支持解析Base64 但是ss的Base64文件不会解析进去ss里面

**Comment by adamw92** [comment]
同求……现在机场陆续开始用SIP002提供订阅了

**Comment by nameless3721** [comment]
可以了谢谢
