### ISSUE TITLE
请问一下这些 patch 会 upstream 吗？

### ISSUE THREAD

**Issue by zhizhouzh** [coolsnowwolf/lede#1385]
非常感谢作者一直维护更新这个优秀的开源项目，想请问一下作者有计划把 patch upstream 到上游去吗？如果 patch 只是在本地的话，会仔细 review 的人的很少，大部分人都是取下来编译一下。但很少人会仔细去阅读代码。但如果推到上游，相当于全世界的人都在看这些 patch，一定会有一些收获。

**Comment by hcym** [comment]
有就感谢啦

**Comment by coolsnowwolf** [comment]
官方要求多多，很多 patch 都未必会接受
