### ISSUE TITLE
有个bug，就是那个上网时间控制，菜单栏里有有两个时间控制菜单，编译时一关，就会关掉两个

### ISSUE THREAD

**Issue by snakwu** [coolsnowwolf/lede#1386]
有个bug，就是那个上网时间控制，菜单栏里有有两个时间控制菜单，编译时一关，就会关掉两个

**Comment by ddzzhen** [comment]
it means relationship about them.

**Comment by snakwu** [comment]
应该是基于之前的加强版吧,但不需要出现两个菜单吧

**Comment by coolsnowwolf** [comment]
缓存问题，删除 tmp 目录

**Comment by snakwu** [comment]
重刷再重置原厂配置都一样

**Comment by snakwu** [comment]
rm: can't remove 'tmp': Resource busy

**Comment by snakwu** [comment]
@coolsnowwolf 这问题无解吗?还是解决了?我看你把我问题关闭了!
