### ISSUE TITLE
/var文件夹

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#1389]
/var文件夹被软连接到 /tmp文件夹，重启路由后里面的数据会被清空，一些监控数据也被清除了。
想问一下这样设计有什么用意吗？

**Comment by coolsnowwolf** [comment]
兼容某些软件而已

**Comment by lxwq** [comment]
我直接把软链接删除了，建了实体文件夹，目前视乎没什么问题，不知道长时间运行会不会有什么影响，
