### ISSUE TITLE
可否提供一个修改dnsmasq缓存时间的入口？

### ISSUE THREAD

**Issue by BROBIRD** [coolsnowwolf/lede#1393]
默认的缓存时间太长了，有的时候改了解析记录要好久才能在设备上生效，直接改配置文件的话可以暂时起作用，但是一重启、或者修改dnsmasq配置，保存之后就失效了。
相关配置项：
```
max-cache-ttl
min-cache-ttl
```

**Comment by xlighting2017** [comment]
1. `killall -SIGHUP dnsmasq` 可以马上清缓存；
2.  这两个配置项 好像不在 UCI 配置中，你需要 自己去 修改 默认配置，否则每次重启还是会失效
默认配置 参考 `/etc/init.d/dnsmasq`
