### ISSUE TITLE
能否更新一下迅雷快鸟到1.05版本？

### ISSUE THREAD

**Issue by lifetyper** [coolsnowwolf/lede#1398]
现在的快鸟1.03版本在断开重连的时候经常出现812错误，1.05已经是新的300协议了，能否更新一下？

**Comment by xia1258** [comment]
这个是由于每次运行都会生成不同的peerID，但是却没有正常退出。
新版本的也有这个问题，需要自己动手修改源码，给他一个固定的peerID

**Comment by lifetyper** [comment]
> 这个是由于每次运行都会生成不同的peerID，但是却没有正常退出。
> 新版本的也有这个问题，需要自己动手修改源码，给他一个固定的peerID

谢谢，只需要把peerID写死就可以了吗？我回头试试。

**Comment by lifetyper** [comment]
试了一下，写死peerID后确实好多了，重启光猫后就可以正常提速，不像之前只能等服务器断开。
