### ISSUE TITLE
希望大雕解决一下https过滤

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#1405]
https广告越来越多，无论hosts还是adbyby 都不能解决了，现在https改如何解决。电脑端通过脚本修改web html很是使用，但手机端都是app该如何是好。所以，根本上就是解决https的问题，请大雕好好研究一下造福人类。

**Comment by lifetyper** [comment]
https过滤的本质是劫持https，不用问了，lean不会考虑的。

**Comment by gbaoye** [comment]
> https过滤的本质是劫持https，不用问了，lean不会考虑的。

呵呵

**Comment by xiangfeigao** [comment]
办法总比困难多，有什么好办法吗。现在都用vpn .啊不是dguard

**Comment by hcym** [comment]
目前hosts还行，优酷百度的都是域名屏蔽
