### ISSUE TITLE
L大退回去后MWAN3出问题了

### ISSUE THREAD

**Issue by bxh64** [coolsnowwolf/lede#141]
内核退回后MWAN3出问题了，我还以为是没清除设置。清除重刷多试了几次。表面貌似一切正常，就是网速不叠加。幸好之前的版本编译好的有留着。刷回去后就叠加正常

**Comment by bxh64** [comment]
我的机子是网件4300

**Comment by gavin219** [comment]
同样的问题，等待L的修复吧

**Comment by bxh64** [comment]
最新的25号的又编了一次，还是叠加失效的。又换回老版本了

**Comment by bxh64** [comment]
今天加了oscam，本想体验一下，顺便看看修复了内核是不是带宽叠加也好了。结果加了oscam编译都不能通过。编译了5次，4个小时，全程是重新开始的。继续留在老版本。

**Comment by bxh64** [comment]
好吧，不死心又重头编译了两次，添加了OSCAM是编不过的

**Comment by bxh64** [comment]
28号去除了OSCAM,一次通过。不过带宽叠加还是失效的。只能用回之前老版本。

**Comment by gavin219** [comment]
去掉ipv6就ok了
