### ISSUE TITLE
自编译的ssrplus中v2ray订阅不太正常

### ISSUE THREAD

**Issue by jonsonjordan** [coolsnowwolf/lede#1410]
用最新源码编译的，解锁了ssrplus。自建的v2ray服务器信息填到ssrplus里运行正常，机场的订阅节点手机上使用正常，用ssrplus能更新订阅，正常显示节点信息，可是使用机场节点后ssrplus状态就一直显示未运行，也不能科学，请问需要编译哪些依赖进去？已附上机场节点的配置
![1](https://user-images.githubusercontent.com/9877792/60003739-e5be5a00-969d-11e9-856c-9370e558abc0.jpg)
![2](https://user-images.githubusercontent.com/9877792/60003752-ea830e00-969d-11e9-888d-06806c38a9ed.jpg)
![3](https://user-images.githubusercontent.com/9877792/60003753-ea830e00-969d-11e9-8f43-f3198b42b499.jpg)
![4](https://user-images.githubusercontent.com/9877792/60003756-eb1ba480-969d-11e9-862b-d4b248279042.jpg)

**Comment by angelsclare** [comment]
加密方式是否与服务器匹配？

**Comment by jonsonjordan** [comment]
> 加密方式是否与服务器匹配？transport的几个方式多感觉也也没有选择对。

经你提醒，我对比了手机订阅和路由订阅的服务器信息，发现路由订阅导入的配置里丢失了‘websocket host’信息，填上就可以了，算是v2ray订阅功能的一个小bug吧

**Comment by tty228** [comment]
我仓库那里有个修复版的

**Comment by tty228** [comment]
我仓库上有个修复过的，
[https://github.com/tty228/lede/tree/master/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr](url)

主要是 `subscribe.sh` 这个文件

**Comment by jonsonjordan** [comment]
> https://github.com/tty228/lede/tree/master/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr
多谢

**Comment by wang3stone** [comment]
> > https://github.com/tty228/lede/tree/master/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr
> > 多谢

没有了？
一样的问题， SSR Plus 用不了V2ray

**Comment by Linkcy97** [comment]
> 

编译的时候选上v2ray核心
