### ISSUE TITLE
级路由器3 hc5861选择安装UnblockMusic和彩蛋软件编译好后无法生成bin包

### ISSUE THREAD

**Issue by angelsclare** [coolsnowwolf/lede#1412]
级路由器3  hc5861选择安装UnblockMusic和彩蛋软件编译好后无法生成bin包，编译过程也没有报错！去掉UnblockMusic，能生成bin包！
系统是Ubuntu14
磁盘 20G
内存 6G

**Comment by lphgor** [comment]
应该是固件文件大小超了吧？

**Comment by angelsclare** [comment]
那要怎么解决尼？

**Comment by angelsclare** [comment]
> 应该是固件文件大小超了吧？

那要怎么解决尼？

**Comment by coolsnowwolf** [comment]
这个组件 5M 多，改 ROM 吧

**Comment by AmibaWorld** [comment]
20G 硬盘 太小了，我原来用20G的，成功几率很小，改至少40G 以上，成功几率提高

**Comment by angelsclare** [comment]
> 20G 硬盘 太小了，我原来用20G的，成功几率很小，改至少40G 以上，成功几率提高

又时间试试
