### ISSUE TITLE
请问下编译的时候如何更改内核版本

### ISSUE THREAD

**Issue by ckxt** [coolsnowwolf/lede#1415]
大雕，请问下编译的时候怎么样更改固件的内核版本啊，谢谢

**Comment by lxwq** [comment]
编译切换内核：
打开LEDE目录/target/linux/架构/Makefile
KERNEL_PATCHVER:=4.9
具体支持内核版本
include/kernel-version.mk

但是想问一下，4.9&4.14&4.19分别有什么功能上的区别吗？

**Comment by hcym** [comment]
试试看看效果

**Comment by sqliuchang** [comment]
> 但是想问一下，4.9&4.14&4.19分别有什么功能上的区别吗？
我遇到的情况是ar71xx在4.9下有SFE，4.14就没有，batman-adv在不同内核下的版本也不一样
