### ISSUE TITLE
ssr plus里的soccks端口怎么生效？

### ISSUE THREAD

**Issue by cary5082** [coolsnowwolf/lede#1419]
我看v2ray高级设置里有一个socks5的代理，我设置了一个端口，保存并应用后。在状态里始终没是未运行。不知道怎么运行。。我是希望有一个sock5的端口v2ray一直在监听。然后我在switchOmega里设置一个ip和这个端口就行了。不知道怎么操作呀。

**Comment by zxlhhyccc** [comment]
> 我看v2ray高级设置里有一个socks5的代理，我设置了一个端口，保存并应用后。在状态里始终没是未运行。不知道怎么运行。。我是希望有一个sock5的端口v2ray一直在监听。然后我在switchOmega里设置一个ip和这个端口就行了。不知道怎么操作呀。

正常。。。。

**Comment by cary5082** [comment]
但是不生效呀。。。我用sock5的这个端口不能用呀。应该怎么操作呢。

**Comment by coolsnowwolf** [comment]
v2ray 的 socks5 并没有支持

**Comment by voicegao** [comment]
> v2ray 的 socks5 并没有支持

https://github.com/kuoruan/openwrt-v2ray

支持的啊
