### ISSUE TITLE
友善 NanoPi Neo Plus2 全志H5 编译完成之后，没有无线网络

### ISSUE THREAD

**Issue by tjaol** [coolsnowwolf/lede#1420]
如题，编译完成后，SD卡刷，一切正常，LuCI 没有 “无线“ 菜单的部分，这块板子上的是 (AMPAK) 正基 AP6212 WiFi/蓝牙模块，有什么方法或者如何加入该设备驱动，重新编译lede，能让它正常使用?

**Comment by tjaol** [comment]
问题解决，加入博通驱动，解决了

**Comment by vernesong** [comment]
> 问题解决，加入博通驱动，解决了

你好，能说下具体应该安装哪个包吗

**Comment by EstFoxs** [comment]
@tjaol 选的哪个驱动，哪个包？谢谢
