### ISSUE TITLE
大雕现在做生意，抽个时间更新一下内核呗！！另外，请大雕增加适配石像鬼qos的相关模块。。。

### ISSUE THREAD

**Issue by zxlhhyccc** [coolsnowwolf/lede#1422]
大雕现在做生意，抽个时间更新一下内核呗！！另外，请大雕增加适配石像鬼qos的相关模块。。。

**Comment by hcym** [comment]
做大买卖啦，哈哈😄，还是官方编译加两个插件完事

**Comment by zxlhhyccc** [comment]
> 做大买卖啦，哈哈😄，还是官方编译加两个插件完事

官方的luci没有大雕反应流畅。。。。
