### ISSUE TITLE
@coolsnowwolf 这问题无解吗?还是解决了?我看你把我问题关闭了!谢谢

### ISSUE THREAD

**Issue by snakwu** [coolsnowwolf/lede#1423]
@coolsnowwolf 这问题无解吗?还是解决了?我看你把我问题关闭了!谢谢谢 #1386

**Comment by coolsnowwolf** [comment]
并没有这个问题，估计是cache

**Comment by snakwu** [comment]
但我按你方法，删除掉tmp也同样问题，我也查过make菜单，里面只有一个选项，选上就出现两个时间控制，如果关掉两个都不见了

**Comment by owen-gu** [comment]
原来我也出现过， 但在后来自动好了

**Comment by snakwu** [comment]
这么神奇？是怎么情况下自动好了

**Comment by 82kg** [comment]
> 这么神奇？是怎么情况下自动好了

make clean  清除上次编译内容
git pull              同步更新大雕源码
./scripts/feeds update -a && ./scripts/feeds install -a   更新FEEDS
rm -rf ./tmp && rm -rf .config     清除编译配置和缓存
