### ISSUE TITLE
最新版本构建后df命令显示不全挂载的点

### ISSUE THREAD

**Issue by solosky** [coolsnowwolf/lede#1427]
如下截图：
![image](https://user-images.githubusercontent.com/480111/60395218-fae62d80-9b62-11e9-84b7-3299d50e19fb.png)

**Comment by sqliuchang** [comment]
我昨晚刚编译了ar71xx的没问题。。

**Comment by SDNGer** [comment]
![20190701114645](https://user-images.githubusercontent.com/44763845/60409388-fa4aa700-9bf5-11e9-9f81-c6522406471f.png)
没问题

**Comment by solosky** [comment]
抱歉，我第一次编译，选择了ramfs，才是这个结果。
