### ISSUE TITLE
上月30日clone后 编译发现<不可描述之工具>不见了

### ISSUE THREAD

**Issue by nAnderYang** [coolsnowwolf/lede#1429]
是敏感时期下掉了 还是永久移除了呢？

**Comment by zhangyongkuanhan** [comment]
git clone https://github.com/SuLingGG/luci-app-ssr-plus package/lean/luci-app-ssr-plus

**Comment by zhangyongkuanhan** [comment]
用这个添加进去就行了

**Comment by zhangyongkuanhan** [comment]
编译完刷进路由用神秘代码开启echo  0xDEADBEEF > /etc/config/google_fu_mode

**Comment by nAnderYang** [comment]
多谢指教。马上重新 编译看看
