### ISSUE TITLE
希望添加IP限速功能

### ISSUE THREAD

**Issue by willaytoun** [coolsnowwolf/lede#1430]
路由是两个网口，lan口接AP。如果一台电脑看高清视频或者下载的话其它设备就特别卡，试了下在AP里限速不过没有作用，所以希望添加给设备限速的功能。

**Comment by tty228** [comment]
SQM 了解一下

**Comment by willaytoun** [comment]
SQM是限制接口速度的吧，我的路由只有两个网口一个wan一个lan，lan口接AP。如果用SQM的话是不能具体到接AP的某一个设备的(比如三个手机和一个电脑都连wifi)，也就是说这样是把整个这个AP的速度都限制了。

**Comment by tty228** [comment]
SQM 本来就自带 QOS 功能啊，流控不比限速强吗

**Comment by willaytoun** [comment]
![image](https://user-images.githubusercontent.com/43229736/60426345-0dc23600-9c27-11e9-8a69-158ad0b36c16.png)
在哪里设置啊？

**Comment by zxlhhyccc** [comment]
> 路由是两个网口，lan口接AP。如果一台电脑看高清视频或者下载的话其它设备就特别卡，试了下在AP里限速不过没有作用，所以希望添加给设备限速的功能。

编译或安装网速控制插件。。。。

**Comment by willaytoun** [comment]
请问网速控制插件哪里找，我找了好半天也没找到。。。
