### ISSUE TITLE
编译netgear evg2000报错

### ISSUE THREAD

**Issue by chinapengwei** [coolsnowwolf/lede#1432]
﻿下面是编译evg2000时报的错，我之前成功编译过wndr3800的固件，应该不是环境或其他什么问题，下面问题不知道如何解决。
drivers/gpio/gpiolib-of.c: In function 'of_gpiochip_add':
drivers/gpio/gpiolib-of.c:510:12: error: too few arguments to function 'of_gpiochip_scan_gpios'
   status = of_gpiochip_scan_gpios(chip);
            ^~~~~~~~~~~~~~~~~~~~~~
drivers/gpio/gpiolib-of.c:247:5: note: declared here
 int of_gpiochip_scan_gpios(struct gpio_chip *chip, unsigned int start,
     ^~~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:326: recipe for target 'drivers/gpio/gpiolib-of.o' failed
make[7]: *** [drivers/gpio/gpiolib-of.o] Error 1
scripts/Makefile.build:585: recipe for target 'drivers/gpio' failed
make[6]: *** [drivers/gpio] Error 2
Makefile:1038: recipe for target 'drivers' failed
make[5]: *** [drivers] Error 2
make[5]: Leaving directory '/home/pengwei/lede/build_dir/target-mips_mips32_musl/linux-brcm63xx_generic/linux-4.14.127'
Makefile:28: recipe for target '/home/pengwei/lede/build_dir/target-mips_mips32_musl/linux-brcm63xx_generic/linux-4.14.127/.image' failed
make[4]: *** [/home/pengwei/lede/build_dir/target-mips_mips32_musl/linux-brcm63xx_generic/linux-4.14.127/.image] Error 2
make[4]: Leaving directory '/home/pengwei/lede/target/linux/brcm63xx'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/pengwei/lede/target/linux'
time: target/linux/install#721.11#78.60#786.12
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/pengwei/lede'
target/Makefile:19: recipe for target '/home/pengwei/lede/staging_dir/target-mips_mips32_musl/stamp/.target_install' failed
make[1]: *** [/home/pengwei/lede/staging_dir/target-mips_mips32_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/pengwei/lede'
/home/pengwei/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by pzxiaoyi** [comment]
和你报错一模一样，18、16、14 都试过了，不知道什么原因了。
