### ISSUE TITLE
OpenWrt R9.6.19  6in4 

### ISSUE THREAD

**Issue by ubuntu1977vip** [coolsnowwolf/lede#1433]
OpenWrt R9.6.19   06-28编译， 6in4 连通HE后有ipv6 ，  但ipv6-test.com无ipv6地址，
xx-net用不了。以前使用PandoraBox，6in4 连通HE后，不用设就可科学上网。不知道是设置还是差依赖包？？？其他使用一切正常

**Comment by ubuntu1977vip** [comment]
OpenWrt R9.6.19 / LuCI Master (git-19.146.62144-fd6fdb2)       newifi-D2

**Comment by shenzt68** [comment]
同样有此问题。我移动宽带，自动分配ipv6，ipv6-test测试无ipv6地址，无法访问外网ipv6.baidu.com等域名，也不能直接访问外网ipv6地址。本路由器的ipv6可从外网访问。为什么？请大雕解决！
