### ISSUE TITLE
编译时出现这个问题，不知道该怎么解决，求帮助

### ISSUE THREAD

**Issue by man2018** [coolsnowwolf/lede#1436]
user1@myubuntu:~/lede$ make -j1 V=s
make[1]: Entering directory `/home/user1/lede'
make[2]: Entering directory `/home/user1/lede'
+ mkdir -p /home/user1/lede/staging_dir/target-x86_64_musl
+ cd /home/user1/lede/staging_dir/target-x86_64_musl
+ mkdir -p bin lib include stamp
mkdir -p /home/user1/lede/build_dir/target-x86_64_musl/stamp
touch /home/user1/lede/staging_dir/target-x86_64_musl/.prepared
+ mkdir -p /home/user1/lede/staging_dir/host
+ cd /home/user1/lede/staging_dir/host
+ mkdir -p bin lib include stamp
mkdir -p /home/user1/lede/build_dir/host/stamp /home/user1/lede/staging_dir/host/include/sys
install -m0644 /home/user1/lede/tools/include/*.h /home/user1/lede/staging_dir/host/include/
install -m0644 /home/user1/lede/tools/include/sys/*.h /home/user1/lede/staging_dir/host/include/sys/
ln -sf lib /home/user1/lede/staging_dir/host/lib64
touch /home/user1/lede/staging_dir/host/.prepared
make[3]: Entering directory `/home/user1/lede/tools/flock'
make[3]: Leaving directory `/home/user1/lede/tools/flock'
time: tools/flock/compile#0.01#0.02#0.04
make[3]: Entering directory `/home/user1/lede/tools/sed'
make[3]: Leaving directory `/home/user1/lede/tools/sed'
time: tools/sed/compile#0.02#0.02#0.04
make[3]: Entering directory `/home/user1/lede/tools/patch'
CFLAGS="-O2 -I/home/user1/lede/staging_dir/host/include " CPPFLAGS="-I/home/user1/lede/staging_dir/host/include " CXXFLAGS="" LDFLAGS="-L/home/user1/lede/staging_dir/host/lib " make  -C /home/user1/lede/build_dir/host/patch-2.7.6  
make[4]: Entering directory `/home/user1/lede/build_dir/host/patch-2.7.6'
make  all-recursive
make[5]: Entering directory `/home/user1/lede/build_dir/host/patch-2.7.6'
Making all in lib
make[6]: Entering directory `/home/user1/lede/build_dir/host/patch-2.7.6/lib'
make  all-am
make[7]: Entering directory `/home/user1/lede/build_dir/host/patch-2.7.6/lib'
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT argmatch.o -MD -MP -MF .deps/argmatch.Tpo -c -o argmatch.o argmatch.c
mv -f .deps/argmatch.Tpo .deps/argmatch.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT backupfile.o -MD -MP -MF .deps/backupfile.Tpo -c -o backupfile.o backupfile.c
mv -f .deps/backupfile.Tpo .deps/backupfile.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT backup-find.o -MD -MP -MF .deps/backup-find.Tpo -c -o backup-find.o backup-find.c
mv -f .deps/backup-find.Tpo .deps/backup-find.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT bitrotate.o -MD -MP -MF .deps/bitrotate.Tpo -c -o bitrotate.o bitrotate.c
mv -f .deps/bitrotate.Tpo .deps/bitrotate.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT cloexec.o -MD -MP -MF .deps/cloexec.Tpo -c -o cloexec.o cloexec.c
mv -f .deps/cloexec.Tpo .deps/cloexec.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT opendir-safer.o -MD -MP -MF .deps/opendir-safer.Tpo -c -o opendir-safer.o opendir-safer.c
mv -f .deps/opendir-safer.Tpo .deps/opendir-safer.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT dirname.o -MD -MP -MF .deps/dirname.Tpo -c -o dirname.o dirname.c
mv -f .deps/dirname.Tpo .deps/dirname.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT basename.o -MD -MP -MF .deps/basename.Tpo -c -o basename.o basename.c
mv -f .deps/basename.Tpo .deps/basename.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT dirname-lgpl.o -MD -MP -MF .deps/dirname-lgpl.Tpo -c -o dirname-lgpl.o dirname-lgpl.c
mv -f .deps/dirname-lgpl.Tpo .deps/dirname-lgpl.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT basename-lgpl.o -MD -MP -MF .deps/basename-lgpl.Tpo -c -o basename-lgpl.o basename-lgpl.c
mv -f .deps/basename-lgpl.Tpo .deps/basename-lgpl.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT exitfail.o -MD -MP -MF .deps/exitfail.Tpo -c -o exitfail.o exitfail.c
mv -f .deps/exitfail.Tpo .deps/exitfail.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT chmodat.o -MD -MP -MF .deps/chmodat.Tpo -c -o chmodat.o chmodat.c
mv -f .deps/chmodat.Tpo .deps/chmodat.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT chownat.o -MD -MP -MF .deps/chownat.Tpo -c -o chownat.o chownat.c
mv -f .deps/chownat.Tpo .deps/chownat.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT fd-hook.o -MD -MP -MF .deps/fd-hook.Tpo -c -o fd-hook.o fd-hook.c
mv -f .deps/fd-hook.Tpo .deps/fd-hook.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT fd-safer-flag.o -MD -MP -MF .deps/fd-safer-flag.Tpo -c -o fd-safer-flag.o fd-safer-flag.c
mv -f .deps/fd-safer-flag.Tpo .deps/fd-safer-flag.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT dup-safer-flag.o -MD -MP -MF .deps/dup-safer-flag.Tpo -c -o dup-safer-flag.o dup-safer-flag.c
mv -f .deps/dup-safer-flag.Tpo .deps/dup-safer-flag.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT filenamecat-lgpl.o -MD -MP -MF .deps/filenamecat-lgpl.Tpo -c -o filenamecat-lgpl.o filenamecat-lgpl.c
mv -f .deps/filenamecat-lgpl.Tpo .deps/filenamecat-lgpl.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT getprogname.o -MD -MP -MF .deps/getprogname.Tpo -c -o getprogname.o getprogname.c
mv -f .deps/getprogname.Tpo .deps/getprogname.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT hard-locale.o -MD -MP -MF .deps/hard-locale.Tpo -c -o hard-locale.o hard-locale.c
mv -f .deps/hard-locale.Tpo .deps/hard-locale.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT hash.o -MD -MP -MF .deps/hash.Tpo -c -o hash.o hash.c
mv -f .deps/hash.Tpo .deps/hash.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT gl_linked_list.o -MD -MP -MF .deps/gl_linked_list.Tpo -c -o gl_linked_list.o gl_linked_list.c
mv -f .deps/gl_linked_list.Tpo .deps/gl_linked_list.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT localcharset.o -MD -MP -MF .deps/localcharset.Tpo -c -o localcharset.o localcharset.c
mv -f .deps/localcharset.Tpo .deps/localcharset.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT malloca.o -MD -MP -MF .deps/malloca.Tpo -c -o malloca.o malloca.c
mv -f .deps/malloca.Tpo .deps/malloca.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT nstrftime.o -MD -MP -MF .deps/nstrftime.Tpo -c -o nstrftime.o nstrftime.c
mv -f .deps/nstrftime.Tpo .deps/nstrftime.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT openat-die.o -MD -MP -MF .deps/openat-die.Tpo -c -o openat-die.o openat-die.c
mv -f .deps/openat-die.Tpo .deps/openat-die.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT parse-datetime.o -MD -MP -MF .deps/parse-datetime.Tpo -c -o parse-datetime.o parse-datetime.c
mv -f .deps/parse-datetime.Tpo .deps/parse-datetime.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT progname.o -MD -MP -MF .deps/progname.Tpo -c -o progname.o progname.c
mv -f .deps/progname.Tpo .deps/progname.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT quotearg.o -MD -MP -MF .deps/quotearg.Tpo -c -o quotearg.o quotearg.c
mv -f .deps/quotearg.Tpo .deps/quotearg.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/user1/lede/staging_dir/host/include   -O2 -I/home/user1/lede/staging_dir/host/include  -MT renameat2.o -MD -MP -MF .deps/renameat2.Tpo -c -o renameat2.o renameat2.c
In file included from /usr/include/x86_64-linux-gnu/sys/syscall.h:31:0,
                 from renameat2.c:29:
renameat2.c: In function 'renameat2':
renameat2.c:81:22: error: '__NR_renameat2' undeclared (first use in this function)
   ret_val = syscall (SYS_renameat2, fd1, src, fd2, dst, flags);
                      ^
renameat2.c:81:22: note: each undeclared identifier is reported only once for each function it appears in
make[7]: *** [renameat2.o] Error 1
make[7]: Leaving directory `/home/user1/lede/build_dir/host/patch-2.7.6/lib'
make[6]: *** [all] Error 2
make[6]: Leaving directory `/home/user1/lede/build_dir/host/patch-2.7.6/lib'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/user1/lede/build_dir/host/patch-2.7.6'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/user1/lede/build_dir/host/patch-2.7.6'
make[3]: *** [/home/user1/lede/build_dir/host/patch-2.7.6/.built] Error 2
make[3]: Leaving directory `/home/user1/lede/tools/patch'
time: tools/patch/compile#1.53#0.32#1.85
make[2]: *** [tools/patch/compile] Error 2
make[2]: Leaving directory `/home/user1/lede'
make[1]: *** [/home/user1/lede/staging_dir/target-x86_64_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynyyynynnyyynnyy] Error 2
make[1]: Leaving directory `/home/user1/lede'
make: *** [world] Error 2

**Comment by Zhang-Shijun** [comment]
这么跟你说的，其实你报错，发这里几乎没人理你的，那些真正会的大佬，包括lean本人。这东西并没有lean说的那么好，肯定能编译成功，我开着全局梯子，最新源码，该安装的工具安装了，失败了make distclean什么的都做。没有一次成功的，唯一一次成功的，斐讯分区刷进去后都是进不去路由器后台的，换上其他固件，马上没问题。我并没有诋毁lean以及lean的劳动成果的意思，只是实话是说。有问题，自己解决吧，或者等着哪天哪位大佬大发慈悲愿意给你解答。

**Comment by jackiezhang29** [comment]
梯子的问题
