### ISSUE TITLE
建议增加SSR P+快速批量修改“自动切换”功能

### ISSUE THREAD

**Issue by HuiGesGitHub** [coolsnowwolf/lede#1461]
如果有上百个甚至更多节点，每一条都要点击修改，进入设置界面取消勾选“自动切换”，再保存退出，非常繁琐。建议能够批量修改。

**Comment by iKenzo** [comment]
“高级设置”

**Comment by HuiGesGitHub** [comment]
> “高级设置”

iKenzo，你没有认真看我的描述。我的付费订阅里有200+节点，但是有很多不同的倍率（从0.5倍到5倍不等），我只希望在低倍率的节点中“自动切换”，所以在大佬的版本中，需要手动关闭200+个节点的“自动切换”功能，如果可以批量修改，就最好不过了。

**Comment by YefanWu** [comment]
是的,自动订阅节点乱跳是个问题.

**Comment by coolsnowwolf** [comment]
这个提议不错

**Comment by adamw92** [comment]
这种情况去直接改config会方便很多…

**Comment by hpqqph** [comment]
我也是哦，高级设置关闭自动切换，半夜更新完节点又自动乱跳了。我还以为是节点被封～不过这个plus+还是很好用的！
