### ISSUE TITLE
节点多卡顿

### ISSUE THREAD

**Issue by nameless3721** [coolsnowwolf/lede#1462]
k2p  潘多拉的话订阅了100+节点还是很流畅但是用源码编译的ssr plus+会比较卡顿读进度条一样 

![test339](https://user-images.githubusercontent.com/50364156/61120175-4c81a700-a4d7-11e9-9bc5-0bf1fc01582c.gif)
潘多拉有啥加成么

**Comment by zu1k** [comment]
我也发现这个问题了，不知道为啥

**Comment by coolsnowwolf** [comment]
luci 版本对节点的处理问题

**Comment by nameless3721** [comment]
新版速度的确快很多100多节点不卡顿了
