### ISSUE TITLE
谁知道最早的能用的ssr能订阅、测试连通功能完好的版本

### ISSUE THREAD

**Issue by davidtwgit** [coolsnowwolf/lede#1464]
天天没有鸟事，把版本搞得这么高，32m路由器没法用。。。

**Comment by libinanshu** [comment]
> 天天没有鸟事，把版本搞得这么高，32M路由器没法用......

请自行前往有害垃圾桶等待接受处理

**Comment by davidtwgit** [comment]
> > 天天没有鸟事，把版本搞得这么高，32M路由器没法用......
> 
> 请自行前往有害垃圾桶等待接受处

> > 天天没有鸟事，把版本搞得这么高，32M路由器没法用......
> 
> 请自行前往有害垃圾桶等待接受处理

Brain damage

**Comment by Zhang-Shijun** [comment]
> 天天没有鸟事，把版本搞得这么高，32m路由器没法用。。。

同意你的说法

**Comment by libinanshu** [comment]
> > > 天天没有鸟事，把版本搞得这么高，32M路由器没法用......
> > 
> > 
> > 请自行前往有害垃圾桶等待接受处
> 
> > > 天天没有鸟事，把版本搞得这么高，32M路由器没法用......
> > 
> > 
> > 请自行前往有害垃圾桶等待接受处理
> 
> Brain damage

你有卵事你自己做啊，免费用人家的东西说点话还不客气，阴阳怪气的，你怕是脑子进水哦

**Comment by BraveSail** [comment]
憨批

**Comment by LitCcc** [comment]
16M的k2p都能用，自己不会用不要怪版本

**Comment by tt5397194** [comment]
https://github.com/tt5397194/lede-ssr
