### ISSUE TITLE
如何通过menuconfig 调整 分区大小

### ISSUE THREAD

**Issue by 82kg** [coolsnowwolf/lede#1467]
根目录 /  , 临时区 /tmp , 他们的大小如何通过 menuconfig来调整啊？

另外，假如我编译了最新版的 lean大的固件，可以通过  【系统】-->【备份/升级】-->【刷写新的固件】来直接升级固件吗？都是 squashfs 格式的固件

**Comment by zwczou** [comment]
target image -> root file system size （倒数第二个
