### ISSUE TITLE
ssr+ 和端口转发冲突

### ISSUE THREAD

**Issue by windyin** [coolsnowwolf/lede#1476]
只要一打开SSR Plus + ,  openwrt上设置的端口转发就失效了，  关闭SSR Plus+ 就能恢复。很奇怪
iptables NAT表如下

![image](https://user-images.githubusercontent.com/912743/61433550-32781680-a966-11e9-9449-7e024d88dbdb.png)
![image](https://user-images.githubusercontent.com/912743/61433570-3b68e800-a966-11e9-8162-b827fbc07f54.png)

**Comment by zxlhhyccc** [comment]
换端口。。。。

**Comment by windyin** [comment]
> 换端口。。。。

换什么端口？ 默认的1234？

**Comment by coolsnowwolf** [comment]
具体是哪些端口？

**Comment by aqswaqsw** [comment]
我也想知道换哪些端口

**Comment by mrclock** [comment]
貌似不是端口转发失效。而是V2转发在系统转发前执行了。你用绕过国内IP试试看。你的转发就生效了。然后你到服务器上去看。不用绕过国内ip的话，会有大量的连接日志。

**Comment by mrclock** [comment]
> 具体是哪些端口？

大雕，我的情况是，即使这个端口在转发没被配置。比如1433，这个端口扫的人很多，只要外网有人扫这个端口，V2服务器上就会产生大量连接日志(用绕开国内IP不会出现)。也就是访问路由外网ip任一端口都会转发到V2的服务器上，不管是否被配置了转发。

我是X86的。

**Comment by mrclock** [comment]
我先执行下，看看。
iptables -t nat -F
iptables -t nat -X GLOBAL

**Comment by zcluo** [comment]
我好像也有这个问题

发自我的 iPhone

**Comment by feeler29** [comment]
同样遇到这个问题

**Comment by guzhiyong** [comment]
也遇到同样的问题，打开ssr+以后在内网的设备无法通过公网ip访问路由器，Transmission的51413端口在防火墙里打开了，检测却是关闭

**Comment by zidane114** [comment]
遇到同样问题，折腾了一整个下午。。只要ssr+一开，所有的端口转发都失效，怎么解？

**Comment by bilijinshi** [comment]
> 
> 
> 遇到同样问题，折腾了一整个下午。。只要ssr+一开，所有的端口转发都失效，怎么解？

同样问题，开了ssr+后，被ssr+处理的目标地址，防火墙规则不生效了（原来是匹配MAC地址并REJECT）
