### ISSUE TITLE
luci-app-accesscontrol还会修复吗

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#1478]
上网时间控制一直不起做用，

**Comment by rtcmay** [comment]
我也是,以前是有效的.

**Comment by coolsnowwolf** [comment]
具体如何无效？ 严格模式启用了么？

**Comment by springsunx** [comment]
好像是支持ipv6的客户端用ipv6的应用不起作用

**Comment by coolsnowwolf** [comment]
不支持 ipv6 的

**Comment by lxwq** [comment]
我在网络中限制一台下级路由的上网时段，比如开始时间07：00结束时间20：00，但这台路由在这个时段以外还是可以上网，LEDE主路由网段192.168.1.1下级路由192.168.3.1，严格模式已经启用也是不行，没有编译ipv6
