### ISSUE TITLE
bcm27xx--brcm2709/2710/2711(32bit)--树莓派4B 编译错误

### ISSUE THREAD

**Issue by EuropeanWithSSR** [coolsnowwolf/lede#1482]
[make.log](https://github.com/coolsnowwolf/lede/files/3414601/make.log)

[config.txt](https://github.com/coolsnowwolf/lede/files/3414535/config.txt)

因为树莓派4B只有32bit的选项中显示有，64bit的选项里没有树莓派4B，不知道选64bit的树莓派4B能不能用，所以编译32bit的。

**Comment by coolsnowwolf** [comment]
gcc 版本问题，暂时 18.06 的 gcc 不支持 -m64 选项

合并到 19.07 分支再更新
