### ISSUE TITLE
大雕我爱你，能否增加cloudflare.com动态DNS支持

### ISSUE THREAD

**Issue by shinyzgj** [coolsnowwolf/lede#1484]
大雕我爱你，能否增加cloudflare.com动态DNS支持。毕竟这是唯一一个国外的，还没被墙能用的了。

**Comment by lphgor** [comment]
cloudflare.com是lede自带的，只是默认没有选中。
make menuconfig，依次进入
Network  -> IP Addresses and Names，
选中 ddns-scripts_cloudflare.com-v4 即可。
