### ISSUE TITLE
SSR-Plus删除节点功能异常

### ISSUE THREAD

**Issue by Heartbeats1104** [coolsnowwolf/lede#1487]
K2P固件，R9.7.6源码编译，其他功能正常，SSR-Plus中删除所有节点按钮无法正常工作（其实之前的版本一直都有这个BUG），之前好像有人反馈过，但是大雕把人家issue给屏蔽了。

**Comment by coolsnowwolf** [comment]
测试是可以用的

**Comment by Zhang-Shijun** [comment]
> 测试是可以用的
哇，不是吧，大雕，难道只有我们两个人的固件不能用？ 点击删除所有服务器按钮，过一会之后刷新，真的一个节点都没有删除。

**Comment by coolsnowwolf** [comment]
除了 K2P，其他都可以
