### ISSUE TITLE
N1编译的树莓派3B 64位系统 ssr未运行，希望能修复一下，谢谢！

### ISSUE THREAD

**Issue by cattypapa** [coolsnowwolf/lede#1489]
我的ss配置没问题，但是它就是没办法运行，我是昨天在外国vps第一次编译的，所以源码肯定是最新的，芝麻开门以后，ssr无法运行，就是没办法运行...真的没办法运行，希望修复一下！

**Comment by coolsnowwolf** [comment]
有日志么？

**Comment by cattypapa** [comment]
没有日志...就是编译完，芝麻开门以后，把节点配置信息全部填好，启动节点，启动完成，ssr显示未运行...

**Comment by cattypapa** [comment]
节点配置完全没问题，不存在配置错误，我检查过多遍。

**Comment by forsan-co** [comment]
> 节点配置完全没问题，不存在配置错误，我检查过多遍。

我好像也遇到过，你把设备接入WAN 网络后，再点击启动试试

**Comment by cattypapa** [comment]
> > 节点配置完全没问题，不存在配置错误，我检查过多遍。
> 
> 我好像也遇到过，你把设备接入WAN 网络后，再点击启动试试

好的
