### ISSUE TITLE
刚刚更新源码，编译出来D2固件刷入无法启动反复重启

### ISSUE THREAD

**Issue by hgh188** [coolsnowwolf/lede#1491]
编译过程都正常

**Comment by hgh188** [comment]
NEWIFI3   望修复

**Comment by hzdrro** [comment]
[mt76: fix kernel Oops by updating to the latest version](https://github.com/coolsnowwolf/lede/commit/26a3952b51b9492185970ed5f55e9370b9e5fa9a)
这个commit之后好像修复了
