### ISSUE TITLE
关于一个Wake On Lan的小BUG，在移动端浏览器里不能自定义输入MAC地址

### ISSUE THREAD

**Issue by f0restt** [coolsnowwolf/lede#1495]
这点非常难受，因为WOL是我的刚需。希望能尽快修复谢谢。

**Comment by coolsnowwolf** [comment]
具体手机系统，浏览器等截图

**Comment by f0restt** [comment]
> 具体手机系统，浏览器等截图

iOS设备  iphone 6s 和 ipad Air ，用 safari 和 chrome 都试过，点击弹出MAC选择框，选择首尾两个"undefined"都无法自主输入MAC，无法弹出手机键盘，单击还是会弹出MAC选择框。

**Comment by shikkoku** [comment]
’iOS12.3.1‘ ’iPhone 6s Plus‘ ‘Safari’ 遇到同样问题，可以复现。

**Comment by f0restt** [comment]
> `iOS 12.3.1` `iPhone 6s Plus` `Safari` 遇到同样问题，可以复现。

我自己找到了解决办法，方法如下：
选最最后一个"undefined"以后，不点击“完成”按钮，直接点击MAC地址选择框，则可以切换到自定义输入状态。

**Comment by f0restt** [comment]
是个非常小的BUG，知道方法后不影响使用，如果大雕有空的话也可以顺道解决下，谢谢。
