### ISSUE TITLE
ssr plus + v2ray 节点下 GFW 用户自定义列表 无效

### ISSUE THREAD

**Issue by f0restt** [coolsnowwolf/lede#1496]

**Comment by agutools** [comment]
主机型号	Newifi-D2
架构	MediaTek MT7621 ver:1 eco:3
固件版本	OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.253.55227-14d2f9b)
内核版本	4.14.131
——————
SSR节点下出现同样的问题
