### ISSUE TITLE
S-Sr不能用gfw列表模式

### ISSUE THREAD

**Issue by Warden630** [coolsnowwolf/lede#1499]
如题，用v2，全局，绕过ip模式都可以用，GFW列表模式无法出国。同时，用绕过ip模式，电脑国内外都可以用，但手机打不开国内网站，真是好奇怪，百思不得其解。
我是x86版本装进虚拟机，单网卡做旁路由。请大大关注！

**Comment by Warden630** [comment]
刚发现更奇怪的问题，用绕过ip模式，电脑可以用。但手机打不开国内网站

**Comment by coolsnowwolf** [comment]
dns 指向路由器

**Comment by Warden630** [comment]
客户机DNS指向LEDE了，GFW列表模式还是出不了国，真是太奇怪了

**Comment by thesadboy** [comment]
同样的问题N1做的旁路由，哈哈

**Comment by f0restt** [comment]
> dns 指向路由器

我也是一样的问题，我用SCP连接上去搜索*gfw*，发现./etc    ./mnt/loop0/upper/etc    ./overlay/upper/etc    ./rom/etc     四个目录下皆有同名文件，但是唯独 ./rom/etc下没有我添加的自定义的gfw内容，所以不知道是不是这个原因，还希望L大解决一下，谢谢。

**Comment by Warden630** [comment]
用白名单模式的话，有线连接的电脑和机顶盒都可以上，手机用wifi连只能看国外，国内网站看不了，实在想不通是什么原因。。。

**Comment by Welkin-Totoro** [comment]
启用 Dnsforwarder

**Comment by Hscpro** [comment]
+1   虽说没有你们那么严重 ，但是会有部分国内网站载入缓慢。重启插件后恢复过阵子还是一样

**Comment by Henry-Rou** [comment]
我也是同样的问题，还没有解决吗？
