### ISSUE TITLE
7.3.2版本断网

### ISSUE THREAD

**Issue by 83874327** [coolsnowwolf/lede#15]
7.3.2版本光猫已改192.168.2.1，但是路由器192.168.1.1重启后WAN口有IP无MAC地址，但是有线无线均断网

**Comment by coolsnowwolf** [comment]
关闭光猫 DHCP

**Comment by coolsnowwolf** [comment]
PPPOE 都没有 MAC 地址，这个正常的

**Comment by 83874327** [comment]
![qq 20170908144054](https://user-images.githubusercontent.com/31736443/30199142-f12bde1a-94a3-11e7-8ff1-38316682e6ea.png)
光猫关闭DHCP，路由重启依旧不可以上网

**Comment by 83874327** [comment]
![default](https://user-images.githubusercontent.com/31736443/30199261-7f0b8d16-94a4-11e7-89f4-045a275202e6.png)
