### ISSUE TITLE
MIWIFI ROUTER R3 刷入无法正常启动

### ISSUE THREAD

**Issue by hanandjun** [coolsnowwolf/lede#1505]
您好，首先问一下有哪些可以交流的地方，qq群已禁止加入。

环境是在Mac上，为了不出玄学问题，所以用了docker，镜像是这个小伙伴的：
https://hub.docker.com/r/timiil/coolsnowwolf-lede-builder

make menuconfig 只是单纯的选了mi router r3，然后编译出来其中有kernel1.bin 和 rootfs0.bin。通过在官方固件下刷入 kernel1 和 rootfs0,启动和下面用 tftp 刷入的一样。

从 u-boot 刷入是把 kernel1.bin 和 rootfs0.bin 拼在了一起。命令是从一篇博客上看到的：

https://blog.ysc3839.com/archives/2018/03/miwifi-r3-ttl-recovery.html

```
dd if=/dev/zero bs=4M count=1 | tr "\000" "\377" > padded_kernel.bin
dd if=kernel.bin of=padded_kernel.bin conv=notrunc
cat padded_kernel.bin rootfs.bin > kernel_rootfs.bin
```

下面的输出是从tftp刷入之后打印的，烦请大佬过目，看一下是哪里出了问题，感谢！！！

Filename 'kernel_rootfs.bin'.������IMEOUT_COUNT=10,Load address: 0x80100000
Loading����Got ARP REPLY, set server/gtwy �����dr (00:0e:c6:b3:e3:f3)
Got it
Got ARP REQUESԬ����urn our IP
T #�####�#################�########�########�##�###############��##
	 ######�##########�#############�######�############�#�##��######�
	 ########################�###�############��######�###############
	 ############�#�#�################################################
	 �#########�############�###�###�###�###############�#�#####��####
	 ###�#####################��#####�#�####�###�#####��#######�######
	 #####��#####�#�############�###############�######�####�#########
	 ####�#######�#�#############�####�#�#�###########################
	 #��###���####�##�##�####��######�########�##########�######�####�
	 ############################�###�##############################�#
	 ##############�#########�#�#########�############�###############
	 ##�#####�#�#��#################�##########��#####################
	 ##########################��##�#�##########�#�##############�####
	 ######��#################�########�######�####��###��######�#####
	 ###�#######�#####################�####�##########################�
	 ###�#�########�###�##�#####�#################################�###
	 ##�#####�############################�#�#########################
	 ##########�#######�#�###########################�#############�##
	 ######�#�##�#��###########�#######���##�######���#######�########
	 #########�#############�###################�#####�##��##�#######���	 ###�######################��##############�########�##########�##����#########�#######�##########�##�###########################�####�
	 #########�########################�########��###�#�##############����#####�##########�############################�####�##############
	 ###�#####�#�#############�#######�#############################�#
	 ###��#####�###�###�###########�#########�###################�####
	 ############�###�######�###########�#############################
	 #######�######��#############�########�###�###########�##########
	 ####�####################�######################################�
	 ###########�################################�##�############�####
	 #######�#########�####################################�#�########
	 #�#�##�#######��########�####��##############�##########�###�###�
	 #��################�###########�##########�##########�###########
	 #�################
done
Bytes trans�����d = 11403264 (ae0000 hex)
NetBootFileXferSize�����e0000
 ������g image to 0x200000
ranand_erase_write: offs:200������ount:ae0000
............�..�.......................................................................Done!
 Writing image to ������00
ranand_erase_write: offs:600000, count:ae0000��...��....................�...................................���...���..............�..Done!
## Booting image at bc200000 ...
   Image Name:   MIPS OpenWrt Linux-4.14.131
   Data Size:    1607812 Bytes =  1.5 MB    �����mage Type:   MIPS Linux Kernel Image (lzma compres��䩊
   Load�����ess: 80000000
   Entry Point:  80000000
....��......�............   Verifying Checksum ... OK
   Uncompressing Kernel Image ... OK
commandline uart_en=1 factory_mode=0 ������8m
No initrd
## Giving linux memsize in MB������
Starting kernel ...

[    0.000000] Linux version 4.14.131 (root@6f64�湸�14.6f646f98a314) (gcc version 7.4.0 (OpenWrt GCC ������r1246-d5107528)) #0 Fri Jul 26 09:43:35 2019
[  ������0000] Board has DDR2
[    0.000000] Analog PMU s����hw control
[    0.000000] Digital PMU set to hw �����ol
[    0.000000] SoC Type: MediaTek MT7620A ver:�����:6
[    0.000000] bootconsole [early0] enabled
[�����.000000] CPU0 revision is: 00019650 (MIPS 24KEc)
[    0.000000] M��Ӻ�machine is Xiaomi Mi Router R3
[    0.000000] Determined physical RAM map:
[ �����000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Ini����ot found or empty - disabling initrd
[    0.00000�ݠ��imary instruction cache 64kB, VIPT, 4-way, linesi�堳��bytes.
[    0.000000] Primary data cache 32kB, 4����PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.00000�ݠ���ormal   [mem 0x0000000000000000-0x0000000007fffff�ݍ�۠   0.000000] Movable zone start for each node
[ ������00000] Early memory node ranges
�۠���0.000000] Initmem setup node 0 [mem 0x00000000000������0x0000000007ffffff]
[    0.000000] random: get_r������bytes called from start_kernel+0x90/0x478 with cr������t=0
[    0.0000��ݠ�uilt 1 zonelists, mobility grouping on.  Total pag�󺠳2512
[    0.000000] Kernel command line: console=���Ӱ,115200 rootfstype=squashfs,jffs2
[  �����00000] PID hash table entries: 512 (order: -1, 204�����es)
[ ������00000] Dentry cache hash table entries: 16384 (or���4, 65536 bytes)
[    0.000000] Inode-c�����ash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=0001氰�
�[    0.000000] Memory: 124620K/13107�ˠ��ailable (3746K kernel code, 174K rwdata, 868K roda�ᬠ�96K init, 207K bss, 6452K reserved, 0K cma-reserv�䩍�۠   0.000000] SLUB: HWalign=32, Order=0-3, MinObje��󽰬 CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 256��۠   0.000000] CPU Clock: 580MHz
[    0.000000] clocksource: systick:����� 0xffff max_cycles: 0xffff, max_idle_ns: 58326150����[    0.000000] systick: enable autosleep mode
[ ������00000] systick: running - mult: 214748, shift: 32��[  ������0000] clocksource: MIPS: mask: 0xffffffff max_cyc��󺠰xffffffff, max_idle_ns: 6590553264 ns
[    0.000���ݠ�ched_clock: 32 bits at 290MHz, resolution 3ns, wr����very 7405115902ns
[    0.007587] Calibrating delay ����.. 385.84 BogoMIPS (lpj=1929216)
[    0.073552] p�����x: default: 32768 minimum: 301
[    0.078263] Mount-cache hash �����entries: 1024 (order: 0, 4096 bytes)
[    0.0846��ݠ��untpoint-cache hash table entries: 1024 (order: 0������ bytes)
[    0.097828] clocksource: jiffies: mask: 0xf������f max_cycles: 0xffffffff, max_idle_ns: 1911260446������0 ns
[    0.107380] futex hash table entries: 25������er: -1, 3072 bytes)
[    0.113353] pinctrl core: initiali����inctrl subsystem
[    0.118952] NET: Registered protocol family 1���[    0.607681] PCI host bridge /pcie@1014000�����ges:
[    0.612303]  MEM 0x0000000020000000..0x0������02fffffff
[    0.617348]   IO 0x0000000010160000����0000001016ffff
�[    0.645473] rt2880_gpio 1000060������: registering 24 irq handlers
[   ������797] rt2880_gpio 10000638.gpio: registering 16 gp���[    0.657227] rt2880_g���000638.gpio: registering 16 irq handlers
[    0.664025] PCI host bridge to bus 0000������    0.668000] pci_bus 0000:00: root bus resource ������x20000000-0x2fffffff]
[    0.674616] pci_bus 000����� root bus resource [io  0xffffffff]
[    0.680377ݠ���_bus 0000:00: root bus resource [??? 0x00000000 fl���x0]
[    0.686958] pci_bus 0000:00: No busn resou����ound for root bus, will use [bus 00-ff]
[    0.695136] pci 0000:00:00.0: br�����onfiguration invalid ([bus 00-00]), reconfiguring��[    0.703573] pci 0000:00:00.0:���Ҡ0: no space for [mem size 0x80000000]
[    0.7099��ݠ�ci 0000:00:00.0: BAR 0: failed to assign [mem size���000000]
[    0.716702] pci 0000:00:00.0: BAR 8: ������ed [mem 0x20000000-0x200fffff]
[    0.723312] pc頰���:00:00.0: BAR 9: assigned [mem 0x20100000-0x201ff�����ef]
[    0.730307] pci 0000:00:00.0: BAR 1: assi�����mem 0x20200000-0x2020ffff]
[    0.736928] pci 00������00.0: BAR 0: assigned [mem 0x20000000-0x200fffff ������
[    0.744015] pci 0000:01:00.0: BAR 6: assigne����� 0x20100000-0x2010ffff pref]
[    0.751033] pci ������0:00.0: PCI bridge to [bus 01]
[    0.755837] pc頰���:00:00.0:   bridge window [mem 0x20000000-0x200ff���ݍ
                                                                           [    0.762442] pci 0000:00:00.0:   bridge window ����0x20100000-0x201fffff pref]
[    0.773764] clocksource: Switched to clocksou����ystick
[    0.780072] NET: Registered protocol f����� 2
 ۠���0.785201] TCP established hash table entries: 102������er: 0, 4096 bytes)
[    0.791926] TCP bind hash �����entries: 1024 (order: 0, 4096 bytes)
[    0.798152] TCP: Hash tables con�����ed (established 1024 bind 1024)
[    0.804442] UDP hash table en����� 256 (order: 0, 4096 bytes)
[    0.810073] UDP-L�����sh table entries: 256 (order: 0, 4096 bytes)
[    0.816446] ��Ժ��egistered protocol family 1
[    0.823465] rt-timer 10000100.tim���aximum frequency is 1220Hz
�    0.830176] Crashlog allocated RAM at address 0�氰�00
[ ������37029] workingset: timestamp_bits=30 max_order=15������t_order=0
[    0.849068] squashfs: version 4.0 (2�����1/31) Phillip Lougher
[    0.854715] jffs2: versi��2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY)��㩠2001-2006 Red Hat, Inc.
[    0.874394] io scheduler noop ������ered
[    0.878141] io scheduler deadline regist���䠨default)
 ۠   0.884061] Serial: 8250/16550 driver, 2 ports, ��Ѡ�haring disabled
[    0.891225] console [ttyS0] �����led
[    0.894742ݠ����0c00.uartlite: ttyS0 at MMIO 0x10000c00 (irq = 20������_baud = 2500000) is a Palmchip BK-3103
[    0.904361] console [ttyS0] enabled
[    0.904361] console [ttyS0] enabled
[    0.911395] bootconsole [early0] disabled
[    0.911395] bootconsole [early0] disabled
[    0.920137] cacheinfo: Failed to find cpu0 device node
[    0.925424] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.932885] libphy: Fixed MDIO Bus: probed
[    0.948067] gsw: setting port4 to ephy mode
[    0.952387] mtk_soc_eth 10100000.ethernet eth0 (uninitialized): port 4 link up (100Mbps/Full duplex)
[    0.961799] mtk_soc_eth 10100000.ethernet: generated random MAC address 2a:28:d3:b1:ce:b5
[    0.970252] mtk_soc_eth 10100000.ethernet: loaded mt7620 driver
[    0.977001] mtk_soc_eth 10100000.ethernet eth0: mediatek frame engine at 0xb0100000, irq 5
[    0.985989] rt2880_wdt 10000120.watchdog: Initialized
[    0.992497] NET: Registered protocol family 10
[    1.001131] Segment Routing with IPv6
[    1.005066] NET: Registered protocol family 17
[    1.009654] 8021q: 802.1Q VLAN Support v1.8
[    1.016937] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    1.024650] Please append a correct "root=" boot option; here are the available partitions:
[    1.033175] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    1.042730] Rebooting in 1 seconds..

U-Boot 1.1.3����� 15 2016 - 17:46:32)

Board: Ralink APSoC DRAM:������MB
Power on memory test. Memory size= 128 MB...OK!
relocate_cod����nter at: 87fb8000
����le ephy clock...done. rf reg 29 = 5
SSC disabled.�����***************************
Software System Reset�����rred
******************************
!!! nand pag����e = 2048, addr len=4
..=================�����======================
--------------------------------------------
A��à��20_MP (Port5<->None)
DRAM_CONF_FROM: Auto-detect���DRAM_TYPE: DDR2
DRAM component: 1024 Mbits
DRA͠��� 16 bit
Total memory: 128 MBytes
Flash componen����D Flash
Date:Apr 15 2016  Time:17:46:32
=======������===============================
icache: sets:51������s:4, linesz:32 ,total:65536
dcache: sets:256, wa�󺴬�linesz:32 ,total:32768

 ##### The CPU freq = ������Z ####
 estimate memory size =128 Mbytes

Please choose�����peration:
   3: Boot system code via Flash (default).via T��Ю��
   ������r boot command line interface.
   9: Load Boot L�����code then write to Flash via TFTP.
 � 0
     ������3: System Boot system code via Flash.
Booti�����tem 2
..ranand_erase_wr��庠�ffs:40000, count:20000
.Done!
done
## Booting i�����t bc600000 ...
   Image Name:   MIPS OpenWrt Linu�����4.131
   Image Type:   MIPS Linux Kernel Image (l����ompressed)
   Data Size:    1607812 Bytes =  1.5 ���  Load Address: 80000000
   Entry Point:  800000�����..............�......��.   Veri����� Checksum ... OK
   Uncompress����ernel Image ... OK
commandline uart_en=1 factory_mode=0 m������m
No initrd
## Giving linux memsize in MB,�����
Starting kernel ...

[    0.000000] Linux version 4.14.13�����ot@6f646f98a314.6f646f98a314) (gcc version 7.4.0 (�����rt GCC 7.4.0 r1246-d5107528)) #0 Fri Jul 26 09:43������19
[    0.000000] Board has DDR2
[    0.000000]������g PMU set to hw control
[    0.000000] Digital P�ՠ��� to hw control
[    0.000000] SoC Type: MediaTek��Է��0A ver:2 eco:6
[    0.000000] bootconsole [early�ݠ���bled
[    0.000000] CPU0 revision is: 00019650 (���Ӡ�4KEc)
[  ������0000] MIPS: machine is Xiaomi Mi Router R3
[    0.000000] Determined physical���͠�ap:
[    0.000000]  memory: 08000000 @ 00000000 ������e)
�۠���0.000000] Primary instruction cache 64kB, VIPT, 4���� linesize 32 bytes.
[    0.000000] Primary data c����32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] Zone ranges:
�۠�� 0.000000] Movable zone start for each node000-0x0000000007ffffff]
[    �����000] Early memory node ranges
[    0.000000]   no�堠�0: [mem 0x0000000000000000-0x0000000007ffffff]
[ �����000000] Initmem setup node 0 [mem 0x00000000000000�����0000000007ffffff]
[    0.000000] ran�����get_random_bytes called from start_kernel+0x90/0x4�����th crng_init=0
 ۠���0.000000] Built 1 zonelists, mobility grouping on.�����al pages: 32512
[    0.000000] Kernel command lin庠��nsole=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 512 (ord�򺠭1, 2048 bytes)
[    0.000000] Dentry cache hash table entries������4 (order: 4, 65536 bytes)
[    0.0000��ݠ��ode-cache hash table entries: 8192 (order: 3, 327������es)
[    0.000000] Wri�����rrCtl register=0001f000
[    0.000000] Readback ������ register=0001f000
[    0.0000��ݠ��mory: 124620K/131072K available (3746K kernel cod嬠���K rwdata, 868K rodata, 196K init, 207K bss, 6452K������ved, 0K cma-reserved)
[    0.000000] SLUB: HWalig�� Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[  �����00000] NR_IRQS: 256
[    0.000000] CPU Clock: 5�����
                                [    0.00000�ݠ��ocksource: systick: mask: 0xffff max_cycles: 0xfff欠��x_idle_ns: 583261500 ns
[    0.000000] systick: e����� autosleep mode
[    0.000000] systick: running -�����: 214748, shift: 32
[    0.000000] clocksource: MIPS: ���� 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6�����3264 ns
[    0.000012] sched_clock: 32 bits at 29���� resolution 3ns, wraps every 7405115902ns
 ۠�� 0.007587] Calibrating delay loop... 385.84 BogoM��Ӡ��pj=1929216)
[    0.073557] pid_max: default: 327������imum: 301
 ۠�� 0.078268] Mount-cache hash table entries: 1024 (����� 0, 4096 bytes)
[    0.084652] Mountpoint-cache �����able entries: 1024 (order: 0, 4096 bytes)
[    0.09783�ݠ���cksource: jiffies: mask: 0xffffffff max_cycles: 0������fff, max_idle_ns: 19112604462750000 ns
[    0.10����ݠfutex hash table entries: 256 (order: -1, 3072 by��󩍊[  �����13358] pinctrl core: initialized pinctrl subsystem��[    0.118957ݠ��Ժ Registered protocol family 16
[    0.385632] PCI host bridge /pcie������000 ranges:
[    0.390255]  MEM 0x00000000200000�����x000000002fffffff
[    0.395300]   IO 0x000000001�����00..0x000000001016ffff
[ ������17964] rt2880_gpio 10000600.gpio: registering 24 �����
                                                              [    0.423427ݠ��80_gpio 10000600.gpio: registering 24 irq handler�[    0.429750] rt2880_gpio 10000638.gp�ﺠ��gistering 16 gpios
[  �����35180] rt2880_gpio 10000638.gpio: registering 16 i����ndlers
[    0.441977] PCI ho�����dge to bus 0000:00
[    0.445953] pci_bus 0000:0������t bus resource [mem 0x20000000-0x2fffffff]
[    ������69] pci_bus 0000:00: root bus resource [io  0xfff�����]
[    0.458330] pci_bus 0000:00: root bus resour��ۿ?? 0x00000000 flags 0x0]
[    0.464910] pci_bus 0�����0: No busn resource found for root bus, will use [���0-ff]
[    0.473088] pci 0000:00:0�����bridge configuration invalid ([bus 00-00]), reconf�����ng
 ۠�  0.481526] pci 0000:00:00.0: BAR 0: no space for�����size 0x80000000]
[    0.487944] pci 0000:00:00.0����Ҡ0: failed to assign [mem size 0x80000000]
[    0������5] pci 0000:00:00.0: BAR 8: assigned [mem 0x20000������200fffff]
[    0.501265] pci 0000:00:00.0: BAR 9������gned [mem 0x20100000-0x201fffff pref]
[    0.508���ݠ�ci 0000:00:00.0: BAR 1: assigned [mem 0x20200000-������ffff]
[    0.514881] pci 0000:01:00.0: BAR 0: as�����d [mem 0x20000000-0x200fffff 64bit]
[    0.521968ݠ��� 0000:01:00.0: BAR 6: assigned [mem 0x20100000-0x2�����ff pref]
[    0.528986] pci 0000:00:00.0: PCI bri����o [bus 01]
[    0.533790] pci 0000:00:00.0:   bri����indow [mem 0x20000000-0x200fffff]
[    0.540395] ��頰000:00:00.0:   bridge window [mem 0x20100000-0x20������ pref]
[    0.551717ݠ����ksource: Switched to clocksource systick
[    0.558025] NET: Registered protocol family 2��[    ������54] TCP established hash table entries: 1024 (ord�򺠰� 4096 bytes)
[    0.569877] TCP bind hash table �����es: 1024 (order: 0, 4096 bytes)
[    0.576103] TCP: Hash ta����configured (established 1024 bind 1024)
[    0.582393] UDP hash t����entries: 256 (order: 0, 4096 bytes)
[    0.588025ݠ���-Lite hash table entries: 256 (order: 0, 4096 byte󩍊[    0.594398] NET: R������red protocol family 1
[    0.601414] rt-timer 10������.timer: maximum frequency is 1220Hz
 ۠���0.608125] Crashlog allocated RAM at address 0x3f0������[    0.615112] wo������et: timestamp_bits=30 max_order=15 bucket_order=0��[    0.627���ݠ�quashfs: version 4.0 (2009/01/31) Phillip Lougher��۠�� 0.632796] jffs2: version 2.2 (NAND) (SUMMARY) (L������RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, In㮍�[    0.652476] io scheduler noop ������ered
[    0.656223] io scheduler deadline regist���䠨default)
[    0.662147] Serial: 8250/16550 driver,�����rts, IRQ sharing disabled
[   ������307] console [ttyS0] disabled
[    0.672826] 10000c00.uartli�庠��yS0 at MMIO 0x10000c00 (irq = 20, base_baud = 250����� is a Palmchip BK-3103
[    0.682449] console [ttyS0] enabled
[    0.682449] console [ttyS0] enabled
[    0.689479] bootconsole [early0] disabled
[    0.689479] bootconsole [early0] disabled
[    0.698225] cacheinfo: Failed to find cpu0 device node
[    0.703512] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.710973] libphy: Fixed MDIO Bus: probed
[    0.726143] gsw: setting port4 to ephy mode
[    0.730464] mtk_soc_eth 10100000.ethernet eth0 (uninitialized): port 4 link up (100Mbps/Full duplex)
[    0.739874] mtk_soc_eth 10100000.ethernet: generated random MAC address c6:0f:3d:5d:9e:c2
[    0.748326] mtk_soc_eth 10100000.ethernet: loaded mt7620 driver
[    0.755075] mtk_soc_eth 10100000.ethernet eth0: mediatek frame engine at 0xb0100000, irq 5
[    0.764063] rt2880_wdt 10000120.watchdog: Initialized
[    0.770570] NET: Registered protocol family 10
[    0.779207] Segment Routing with IPv6
[    0.783143] NET: Registered protocol family 17
[    0.787730] 8021q: 802.1Q VLAN Support v1.8
[    0.795015] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    0.802729] Please append a correct "root=" boot option; here are the available partitions:
[    0.811254] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    0.820808] Rebooting in 1 seconds..

**Comment by hanandjun** [comment]
烦请大佬过目，看一下是哪里出了问题

**Comment by hanandjun** [comment]
感谢

**Comment by qinfeng8848** [comment]
我分享一下我的方法：
1.先刷breed-mt7621-xiaomi-r3g.bin
2.然后在刷入openwrt-ramips-mt7621-mir3g-squashfs-kernel.bin
3.最后ssh登陆到openwrt 
root@OpenWrt:/tmp# mtd write openwrt-ramips-mt7621-mir3g-squashfs-kernel1.bin kernel_stock
root@OpenWrt:/tmp# mtd write openwrt-ramips-mt7621-mir3g-squashfs-kernel1.bin kernel
root@OpenWrt:/tmp# mtd write openwrt-ramips-mt7621-mir3g-squashfs-rootfs0.bin ubi

**Comment by hanandjun** [comment]
@qinfeng8848 你好，试了一下还是不行，但是很感谢你的解答。
我对比了一下启动日志，发现正常的启动应该是会在
[    0.950617] 8021q: 802.1Q VLAN Support v1.8
之后有
[    0.959774] UBI: auto-attach mtd9
所以，这个可能是要在 kernel 开启什么选项，我会继续探索

**Comment by hanandjun** [comment]
不过连分区都没打印出来，这是什么问题呢

**Comment by hanandjun** [comment]
已刷入，剩下的再慢慢探索，感谢

**Comment by LiuJiangshan** [comment]
> 已刷入，剩下的再慢慢探索，感谢

能正常使用吗？

**Comment by hanandjun** [comment]
@LiuJiangshan 能启动，不能正常使用😅，可以到打开的 #1523 讨论
