### ISSUE TITLE
k2p自适应闪存内存

### ISSUE THREAD

**Issue by Leisuredpootle** [coolsnowwolf/lede#1507]
lean大，你好，我发现您在恩山发的k2p固件帖子说自适应内存闪存，但我在这套源码没有看见相关代码，请问能不能将自适应内存闪存的逻辑代码发到GitHub。如果已经包含在这套代码内，麻烦您直接回复我已经包含。在这里感谢lean大您的付出！谢谢

**Comment by ntlf9t** [comment]
照官方源码改就行，我发群里的ke2p最新的那个可以自适应内存了

**Comment by ntlf9t** [comment]
[https://github.com/openwrt/openwrt/commit/6d91ddf5175d2eac3c4bc4a404cc0f5dd44cf25b](url)
[https://github.com/openwrt/openwrt/commit/a2c19f1d2f658367e6d62a6bdcfc72f12f23e43e](url)

**Comment by Leisuredpootle** [comment]
请问是直接合并这两个commit吗？
