### ISSUE TITLE
SSR PLUS V2RAY 小BUG

### ISSUE THREAD

**Issue by jobber2955** [coolsnowwolf/lede#1508]
固件版本	OpenWrt R9.7.6 / LuCI openwrt-18.06 branch (git-19.200.68674-a388be0)

具体描述： 解密完，安装了LUCI-FILETRANSFER及LUA-CJSON后，可以正常使用V2RAY。但一旦切换到全局、大陆IP、海外模式后，状态栏中测试谷歌连接性都是失败，然而实际上是可用的。

并不会影响正常使用，只是状态显示有问题。

**Comment by coolsnowwolf** [comment]
luci v2ray pro版本太老了，不再支持

**Comment by jobber2955** [comment]
> luci v2ray pro版本太老了，不再支持

好的，感谢大佬，能麻烦告知一下是否有对V2RAY的解决方案吗？K3的CPU没有FPU，那就意味着无法使用V2RAY了吗？

**Comment by coolsnowwolf** [comment]
SSR Plus 已经支持 V2RAY
