### ISSUE TITLE
make: *** No rule to make target '/root/lede/include/toplevel.mk'.

### ISSUE THREAD

**Issue by kench233** [coolsnowwolf/lede#1511]
admin@vultr:/root/lede$ make -j1 V=s
Makefile:32: /root/lede/include/debug.mk: Permission denied
Makefile:33: /root/lede/include/depends.mk: Permission denied
Makefile:34: /root/lede/include/toplevel.mk: Permission denied
make: stat: /root/lede/include/toplevel.mk: Permission denied
make: stat: /root/lede/include/depends.mk: Permission denied
make: stat: /root/lede/include/debug.mk: Permission denied
make: *** No rule to make target '/root/lede/include/toplevel.mk'.  Stop.
用的vultr 1c2G的机子，服务器系统ubuntu16.04，源码是今日刚同步的

**Comment by lphgor** [comment]
Permission denied
你是不是在root账户下面同步，然后新建了一个普通账户admin来编译的？

**Comment by coolsnowwolf** [comment]
权限问题
