### ISSUE TITLE
内核更换问题

### ISSUE THREAD

**Issue by Heartbeats1104** [coolsnowwolf/lede#1513]
大雕，请问使用您的源码，如何更换第内核啊？比如降低为 3.14 的，因为有些插件，使用大于 openwrt 15.05 以上的 SDK编译出来的，在大于 3.14 的高内核下无法运行，会提示 not found。

**Comment by adamw92** [comment]
> 
编译切换内核：
打开LEDE目录/target/linux/架构/Makefile
KERNEL_PATCHVER:=4.9
具体支持内核版本
include/kernel-version.mk
>

**Comment by Heartbeats1104** [comment]
我问的是怎么更换到3.14内核，别看见你会一点点的就乱答，OK?  相应架构Makefile里的全是4.x的内核，这谁都知道。更换为4.X内核方法，Google一大堆，谁还会来这里问？

**Comment by coolsnowwolf** [comment]
没那么简单，要自己写内核 patch backport 回去的

**Comment by adamw92** [comment]
> 我问的是怎么更换到3.14内核，别看见你会一点点的就乱答，OK? 相应架构Makefile里的全是4.x的内核，这谁都知道。更换为4.X内核方法，Google一大堆，谁还会来这里问？

友好度满分

**Comment by MeIsReallyBa** [comment]
就你这态度谁想回答

**Comment by Heartbeats1104** [comment]
> 就你这态度谁想回答

哦豁？我这态度？我这态度怎么了？我请教大雕，对大雕用的是您，用的是请问等词。我问过你？还是问了哪个其他人。我叫adamw92这位兄弟别不看问题，答非所问，我态度就有问题？你怕不是傻子吧？

**Comment by vft9nesd** [comment]
> > 就你这态度谁想回答
> 
> 哦豁？我这态度？我这态度怎么了？我请教大雕，对大雕用的是您，用的是请问等词。我问过你？还是问了哪个其他人。我叫adamw92这位兄弟别不看问题，答非所问，我态度就有问题？你怕不是傻子吧？

硬核选手

**Comment by 24kcsplus** [comment]
> > 就你这态度谁想回答
> 
> 哦豁？我这态度？我这态度怎么了？我请教大雕，对大雕用的是您，用的是请问等词。我问过你？还是问了哪个其他人。我叫adamw92这位兄弟别不看问题，答非所问，我态度就有问题？你怕不是傻子吧？

逆天
