### ISSUE TITLE
ssrplus自动检测谷歌连通性误判导致一直不停切换节点

### ISSUE THREAD

**Issue by bin20088** [coolsnowwolf/lede#1515]
用你的源码编译的op，量子空间加了https://github.com/Baozisoftware/luci-app-koolproxy   这个KP去广告。去广告效果不错，但是开了这个KP会导致你的ssrplus谷歌连通性检测误判，然后一直不停的切换节点。实际是可以扶墙的。怎么能修复下。谢谢

**Comment by coolsnowwolf** [comment]
不支持 ks 的任何插件，自己负责

**Comment by bin20088** [comment]
好吧，那可不可以给个解决思路？

**Comment by hahach** [comment]
用这个lede里自带的去广告啊。
