### ISSUE TITLE
动态域名如何及时更新ip

### ISSUE THREAD

**Issue by fyfh** [coolsnowwolf/lede#1517]
ssr plus只有一个节点，动态ip，填写域名，不能及时更新ip，何解？

**Comment by mrclock** [comment]
这是DNS缓存的关系。不可能每调用一次都去解析一下的。

**Comment by sqliuchang** [comment]
楼上好机智…我都是控制好ip变化的时间点，所有设备一起重启。
dns缓存的话你可以搜索一下dnsmasq的配置教程，里面有缓存时间和缓存大小的设置，比如这个
https://cloud.tencent.com/developer/article/1174717

**Comment by wangxin6** [comment]
使用resolveip
https://openwrt.org/packages/pkgdata_lede17_1/resolveip

建立watchdog的脚本。wget定时国外站点和国内站点。如果国内和国外都不通，重启dnsmasq。如果国内通，国外不通，resolveip解析动态域名，获取新的IP，再重启SS和dnsmasq
