### ISSUE TITLE
R9 8.5 的adbyby plus+ 和网易云冲突问题。

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#1518]
adbyby plus+ 和网易云冲突，在commit 95d74fb 后ADbyby plus +的plus+ 模式已经得到解决，但是全局模式下好像还是有冲突，会引进网易云解锁的ipset 不能劫持，解锁不了灰色音乐，能否解决？

**Comment by shikkoku** [comment]
https://github.com/coolsnowwolf/lede/commit/7f39235eb5908eb8d1d831c569d6ad820fdc2ec0
