### ISSUE TITLE
今天的版本编译完没有adbyby plus

### ISSUE THREAD

**Issue by hahach** [coolsnowwolf/lede#1520]
今天晚上的版本编译完后发现没有adbyby plus。编译之前改动过make menuconfig 加过东西，但是没有动过adbyby plus。编译完发现没有这个以后又去menuconfig里面找了半天没找到...

然后直接打开.config 文件，查找结果如下
CONFIG_DEFAULT_luci-app-adbyby-plus=y
这个应该是对的吧？
有人知道什么情况吗

**Comment by hahach** [comment]
之前加东西主要是加 nano，pciutils 之类的软件，luci的没动过

**Comment by xiangfeigao** [comment]
确实没有啦

**Comment by hcym** [comment]
有吧，中午编译的x64有的，从来没用过

**Comment by hahach** [comment]
> 有吧，中午编译的x64有的，从来没用过

你看看你的是不是adbyby，我说的是adbyby plus

**Comment by hahach** [comment]
> 确实没有啦

那看来我不是个例啊，我看了下lean最近几次提交，乍一看没看到关于这个的改动啊

**Comment by hahach** [comment]
备份好.config 重新clone，重新make menuconfig，结果又正常了，有点迷。
