### ISSUE TITLE
请问面向Proxmox（PVE）/EXSi编译的时候，目标应选择哪个？

### ISSUE THREAD

**Issue by Fr33raNg3r** [coolsnowwolf/lede#1527]
PVE和EXSi的目标都选X86？
麻烦告知一下。

**Comment by hahach** [comment]
x86 64

**Comment by Fr33raNg3r** [comment]
> x86 64

感谢，没有专门针对虚拟机的目标编译吗？ROS就有CHR

**Comment by hahach** [comment]
> > x86 64
> 
> 感谢，没有专门针对虚拟机的目标编译吗？ROS就有CHR

我没弄过ROS，估计他的这个选项是添加虚拟机的一些驱动吧？
我看了这个openwrt的配置文件里面基本上虚拟机需要的驱动都有，如果你是pve的，最多再加一个qemu-guest-agent，虽然这个东西也没什么重要作用。

**Comment by coolsnowwolf** [comment]
选上 qow 格式， x86 64

**Comment by Fr33raNg3r** [comment]
> 选上 qow 格式， x86 64

感谢L大。
