### ISSUE TITLE
树莓派4B编译报错

### ISSUE THREAD

**Issue by 1021683053** [coolsnowwolf/lede#1535]
![image](https://user-images.githubusercontent.com/7711802/62713669-b1c1ad00-ba2f-11e9-904e-2d312954c03b.png)

**Comment by lphgor** [comment]
看红框上面2行
`you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)`
不能使用root账户编译，
或者可以强制跳过检查：
`export FORCE_UNSAFE_CONFIGURE=1`

**Comment by 1021683053** [comment]
@lphgor 忘记了，三克油
