### ISSUE TITLE
关于ssr plus内的v2ray使用233boy 脚本v2ray ws tls工作不正常

### ISSUE THREAD

**Issue by ntgeralt** [coolsnowwolf/lede#1539]
有朋友在ssr plus用233boy ws tls模式正常的吗？我在k2p官改正常用，PC和手机也正常用，不知为何唯独 ssr plus 233 boy ws tls一直不能工作，谷歌等404，测试超时（已勾选insecure）。输入其他ws tls 节点则能正常工作。

**Comment by mrclock** [comment]
233boy的一件脚本，我也在用。我可以连，但是会有大量连接被转发到服务器上。不知道你是啥问题？

**Comment by coolsnowwolf** [comment]
已修复使用 v2ray 的时候，大量连接被转发到服务器上的问题。 
GFW模式的和 V2RAY 之间特有的问题。
