### ISSUE TITLE
这个是什么错误，搜不到

### ISSUE THREAD

**Issue by tty-tty** [coolsnowwolf/lede#154]
/bin/bash: line 1: 16197 Killed                  build/genautomata /abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0/gcc/common.md /abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0/gcc/config/mips/mips.md insn-conditions.md > tmp-automata.cmake[6]: *** [s-automata] Error 137make[6]: Leaving directory `/abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0-final/gcc'make[5]: *** [all-gcc] Error 2make[5]: Leaving directory `/abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0-final'make[4]: *** [all] Error 2make[4]: Leaving directory `/abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0-final'make[3]: *** [/abcabc/lede/build_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/gcc-5.4.0-final/.built] Error 2make[3]: Leaving directory `/abcabc/lede/toolchain/gcc/final'make[2]: *** [toolchain/gcc/final/compile] Error 2make[2]: Leaving directory `/abcabc/lede'make[1]: *** [/abcabc/lede/staging_dir/toolchain-mipsel_24kc_gcc-5.4.0_musl/stamp/.toolchain_compile] Error 2make[1]: Leaving directory `/abcabc/lede'make: *** [world] Error 2

我在vps安装的ubuntu 14.04，          斐讯K2P
--

**Comment by lphgor** [comment]
第一行，提示进程被结束了。应该是vps内存不足。
