### ISSUE TITLE
autoreboot

### ISSUE THREAD

**Issue by RealKiro** [coolsnowwolf/lede#1549]
![image](https://user-images.githubusercontent.com/33367701/63206813-6aea4c00-c0ee-11e9-95f8-0745995b09ec.png)
最新编译的固件 ”定时重启“ 点击后就是这样子，so is a bug ?

**Comment by lysssssss** [comment]
修复星期天的BUG里每天重启那句代码出错了，L大已经回滚了。
可以自己在计划任务里添加重启暂时代替
