### ISSUE TITLE
错误提示recipe for target ‘prereq’ failed

### ISSUE THREAD

**Issue by jdjingdian** [coolsnowwolf/lede#1555]
路由器：小米r3p
在ubuntu 16.04和18.04都按步骤尝试过，一直提示
recipe for target ‘prereq’ failed

**Comment by jdjingdian** [comment]
![](https://i.loli.net/2019/08/20/UMSr2DnEGbliY38.jpg)

**Comment by allenfoxtc** [comment]
make menuconfig 之后保存配置没？保存的话 /lede下会有个.config文件
