### ISSUE TITLE
树莓派型号设备显示错误

### ISSUE THREAD

**Issue by SuLingGG** [coolsnowwolf/lede#1558]
拉取最新源码后，在平台选择 Brcm27xx，CPU选择 2708，2709/2710/2711，2710 这三个选项时，型号列表中只能看到一个 Default 的选项，无法像以前一样选择树莓派的具体型号(2B，3b，3b+)，而选择 Default 后很多预置编译参数都为空，比如 Firmware，网卡驱动等，无法正常编译。请求修复。

**Comment by 0758jian** [comment]
我3B+就是这样default选，编译成功安装也成功，估计是你环境问题

**Comment by forsan-co** [comment]
我也看见和以前不同，照样编译出来，但是升级失败，还没有重新刷过

**Comment by SuLingGG** [comment]
> 我3B+就是这样default选，编译成功安装也成功，估计是你环境问题

如果选择 Default ，最基础的: 网卡驱动都是空的，编译出来的固件应该不能用。
并且我始终都是在 Docker 下编译的，全新拉取源码，应该不存在环境的问题。

**Comment by jdjingdian** [comment]
> > 我3B+就是这样default选，编译成功安装也成功，估计是你环境问题
> 
> 如果选择 Default ，最基础的: 网卡驱动都是空的，编译出来的固件应该不能用。
> 并且我始终都是在 Docker 下编译的，全新拉取源码，应该不存在环境的问题。

没想到在这看到了大佬，想用您的固件装在我的树莓派3b+上，结果发现好像没有DNScrypt-Proxy插件，就想自己编译一个，没想到遇到了相同的问题，没有了树莓派的预置编译参数
