### ISSUE TITLE
新版luci-app-ssr-plus插件要如何重新安装？

### ISSUE THREAD

**Issue by KuniJiwa** [coolsnowwolf/lede#1561]
删掉原先的ssrplus后，插件上传后无法直接安装，请教下如何只能装下列依赖包

> root@OpenWrt:~# opkg install luci-app-ssr-plus_1-98_all.ipk
Installing luci-app-ssr-plus (1-98) to root...
Collected errors:
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
>* 	luasocket * 	lua-cjson * 	kcptun-client * 	shadowsocksr-libev-ssr-local * 
>* opkg_install_cmd: Cannot install package luci-app-ssr-plus.

**Comment by coolsnowwolf** [comment]
缺依赖包
