### ISSUE TITLE
luci-app-ssr-plus安装报错 uci: Entry not found

### ISSUE THREAD

**Issue by pcccccc** [coolsnowwolf/lede#1562]
安装luci-app-ssr-plus 时报错：uci: Entry not found。在菜单内看不到应用入口，但是在软件包中可以找到。
日志`root@Openwrt:/# opkg install luci-app-ssr-plus_1-98_all.ipk                                                                 
Installing luci-app-ssr-plus (1-98) to root...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Installing shadowsocks-libev-config (3.3.1-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/shadowsocks-libev-config_3.3.1-1_x86_64.ipk
Installing shadowsocks-libev-ss-redir (3.3.1-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/packages/shadowsocks-libev-ss-redir_3.3.1-1_x86_64.ipk
Configuring shadowsocks-libev-config.
Configuring shadowsocks-libev-ss-redir.
Configuring luci-app-ssr-plus.
uci: Entry not found`
平台X64

**Comment by coolsnowwolf** [comment]
不是报错

**Comment by pcccccc** [comment]
那在菜单里咋看不到选项呢。。

**Comment by pcccccc** [comment]
> 不是报错

那在菜单里咋看不到选项呢。。

**Comment by xman55555** [comment]
![2019-08-24_174328](https://user-images.githubusercontent.com/3001600/63635592-baa0b880-c696-11e9-8f7d-99bd2b66f5e3.png)
这种包找不到要怎么手动下载呢?

**Comment by richcup** [comment]
luci-app-ssr-plus安装报错
uci: Entry not found
uci: Entry not found
uci: Entry not found
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/dhcp is different from the conffile in the new package. The new conffile will be placed at /etc/config/dhcp-opkg.
服務端頁面 ( 無法顯示) 其它都正常
![1](https://user-images.githubusercontent.com/56370288/66977491-051d3080-f05b-11e9-8300-b000d56b4da6.jpg)
![1-1](https://user-images.githubusercontent.com/56370288/66977492-051d3080-f05b-11e9-8097-bb3fef435d7e.jpg)


Failed to execute arcombine dispatcher target for entry '/admin/services/shadowsocksr/server'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/shadowsocksr/server.lua:7: module 'luci.model.ipkg' not found:
如何修復

**Comment by gause555** [comment]
先运行opkg update正常就可以解决继续安装

**Comment by sobossceo** [comment]
Installing luci-app-ssr-plus (1-100) to root...
Configuring luci-app-ssr-plus.
uci: Entry not found
uci: Parse error (invalid command) at line 1, byte 0

**Comment by 70599** [comment]
`uci: Entry not found`是因为luci-app-ssr-plus把非uci配置文件，例如`black.list`之类的放入了`/etc/config`路径下导致的。
这个警告信息本身不影响插件运行。
如果不能运行请排查其他因素。
