### ISSUE TITLE
luci-app-ssr-plus 不显示

### ISSUE THREAD

**Issue by azazjjyjjy** [coolsnowwolf/lede#1563]
编译完了，ssr 服务也在运行，软件包里也有luci ssr,但是路由器界面没有显示，怎么操作呢？

**Comment by azazjjyjjy** [comment]
echo 0xDEADBEEF > /etc/config/google_fu_mode

**Comment by stevenliuit** [comment]
能不能在编译的时候指定啊

**Comment by lphgor** [comment]
@stevenliuit 
你可以预先在源代码的`package/lean/luci-app-ssr-plus/root/etc/config`目录下面，新建一个文件，文件名`google_fu_mode`，内容`0xDEADBEEF`，再编译就可以了。

**Comment by stevenliuit** [comment]
谢啦 知道了
