### ISSUE TITLE
u盘无法挂载到/overlay

### ISSUE THREAD

**Issue by dzhuqi** [coolsnowwolf/lede#1566]

**Comment by dzhuqi** [comment]
问题已经解决。少了好几个依赖包

**Comment by dzhuqi** [comment]
偶尔可以挂载上/overlay ，一般都是挂不上，etc/。。。fastp里面配置看起来正常，就是软件包那没有变化，挂载点也没有挂上/overlay

**Comment by rufengsuixing** [comment]
如果是mismatch，需要删除u盘根目录或者U盘/etc下的.extrootuuid文件，或者手动填入id
参考
https://openwrt.org/docs/guide-user/additional-software/extroot_configuration
