### ISSUE TITLE
不支持我的DELL D3100 USB3.0 DOCK 上的千兆网卡

### ISSUE THREAD

**Issue by ethan-www** [coolsnowwolf/lede#1567]
我这边有两台新3，刷遍论坛所有基于lean的固件都不认我的DELL USB3.0 DOCK上的千兆网卡。
网卡速度设自动或千兆时会不停的闪断（网络电览拔出），网卡速度设为100M时就能正常联网，

但是同一台路由，同样的网线，同样的网卡，官方原版固件/PandoraBox/高恪，都能自动识别联网DELL网卡千兆模式。breed环境下也是能正常的自动识别连接我的网卡的千兆模式。

我有一次刷了老毛子的固件，老毛子固件交换机网卡里有个省电的钩钩，
钩上了省电的钩钩后也会出现像LEAN系列固件一样千兆不停闪断的现像，
不知道是不是这里引起的，但是LEAN固件里没有这个选项
感觉是网卡驱动或配置有些不兼容，

LEAN系列的功能要完善些，但是连不了我的千兆网卡是硬伤，此问题有无解么？

**Comment by hcym** [comment]
这个不要什么驱动，就是兼容喽，用op官方编译看看，大雕的就是x86比较好，其它的我都是用官方，除了gfwlist不太方便，性能肯定比大雕的好一点点

**Comment by ope087** [comment]
看看cdc 和ncm的驱动有没有装全吧,没有的话只能自己编译了
