### ISSUE TITLE
pppoe获取ipv6后不会自动生成v6接口

### ISSUE THREAD

**Issue by colinhd8** [coolsnowwolf/lede#1568]
官方文档[https://openwrt.org/docs/guide-user/network/ipv6/start](https://openwrt.org/docs/guide-user/network/ipv6/start)有一段这样的内容(图片貌似需要科学上网才可以看到)：
![QQ图片20190823113823](https://user-images.githubusercontent.com/5259758/63565198-8f38a380-c59a-11e9-96ba-e5836ea1f501.png)
，而其它固件实际使用下来也确实是这样的：
![1](https://user-images.githubusercontent.com/5259758/63566233-de80d300-c59e-11e9-97a5-0cb45fb8b97f.png)
但大雕的固件中(本周一获取最新源码编译的)是这样的(没有_6的接口)
![2](https://user-images.githubusercontent.com/5259758/63566282-0b34ea80-c59f-11e9-8049-ed7a9fd8a6ac.png)
当然，在概览页是可以看到V6信息的：
![3](https://user-images.githubusercontent.com/5259758/63566380-7bdc0700-c59f-11e9-84ca-68294d8591e1.png)

这是因为luci版本旧的原因吗？有啥方法可以保持和官方的一致呢？

**Comment by rufengsuixing** [comment]
不用生成也能用，一个接口能有v4和v6同时存在，关了吧

**Comment by colinhd8** [comment]
已确认其实是有生成了_6接口，只是没在页面上显示，应该是luci比较旧的原因。
