### ISSUE TITLE
在ssr服务器端口为443时，使用绕过中国大陆ip模式会失效。

### ISSUE THREAD

**Issue by azuse** [coolsnowwolf/lede#157]
gfwlist模式和全局模式都没有问题。
如果服务器端口从443端口换成别的就没有问题。
使用相同的ssr配置在手机和电脑客户端上都能连接。

**Comment by laiyelo** [comment]
我这也遇到了同样的问题，端口是443时，绕过中国大陆ip模式失效，换成别的端口就OK

**Comment by chongnaxiao** [comment]
确实如此，我编译几次都这样，以为自己哪里搞错了。
奇怪的是lean自己编译的R7.3.3是正常的。
