### ISSUE TITLE
ShadowSocksR Plus+插件 IPV6 支持？

### ISSUE THREAD

**Issue by wherelse** [coolsnowwolf/lede#1570]
在配置里填入ipv6域名或者地址服务连接，WAN已获取到ipv6地址，服务器检查一直无法通过，是否能添加对ipv6域名的支持？

**Comment by hcym** [comment]
一直支持，没问题的

**Comment by wherelse** [comment]
> 一直支持，没问题的
拨号wan6已经获取到ipv6地址了，可是服务器就一直ping不通，不知道是不是有其他原因

**Comment by hcym** [comment]
路由wan能ping通6就好，我的lan口还没有ipv6也不影响使用
