### ISSUE TITLE
【国内IP段】数据库一直无法在线更新

### ISSUE THREAD

**Issue by Fr33raNg3r** [coolsnowwolf/lede#1571]
请教【国内IP段】数据库
为何一直无法在线更新

**Comment by wuyi-ligux** [comment]
是不是选了绕开大陆ip模式？我这里要互换才能更新

**Comment by SDNGer** [comment]
![QQ截图20190825212515](https://user-images.githubusercontent.com/44763845/63650599-e1d2b500-c77e-11e9-94a5-6588258432d2.png)

**Comment by Fr33raNg3r** [comment]
![image](https://user-images.githubusercontent.com/15374658/63683172-48fa7300-c82c-11e9-8469-734d90d60a09.png)
之前选的GFW模式，换成全局模式后更新就正常了，谢谢。
@wuyi-ligux

**Comment by h6fYe34KFSiH** [comment]
apnic.net
好用用的这个服务器，设置成走代理就可以了，不用全局

**Comment by jackalwoo** [comment]
换成全局模式就可以更新了
