### ISSUE TITLE
glibc 下载有问题

### ISSUE THREAD

**Issue by doumeki** [coolsnowwolf/lede#1573]

**Comment by doumeki** [comment]
glibc 下载不下来，请求的是一个不存在的tar(2.27)文件，好像新版本的openwert已经改了。

这个版本改了下载文件后编译出错

**Comment by xiuluo** [comment]
你需要挂全局梯子。

**Comment by doumeki** [comment]
> 你需要挂全局梯子。

应该不是，返回403的错，我去看了下那个地址，列表里的确没有glibc-2.27-xxxx 的一堆东西，我猜本身文件名组合就有问题？
你可以试下编译的时候c lib 选中glibc 而不是musl, 在advance config option--> toolchain-->c library
