### ISSUE TITLE
SSR plus更换节点之后必须重启路由器或者在启动项里重启ssr才可以科学上网

### ISSUE THREAD

**Issue by Zack0617** [coolsnowwolf/lede#1574]
复制ssr plus软件到原版OPENWRT（1806和1907）下编译，设置好ssr参数（更换节点或者设置其他选项）之后，点应用并保存，等待较长时间也不能科学上网，只能重启路由器或者在启动项里重启一下ssr才能科学上网，但在lede1701下编译没有这个问题，应用并保存之后马上就可以科学上网。不知道这个问题在在新版本（1806和1907）下如何解决，请大佬帮忙解答 下，谢谢！

**Comment by shikkoku** [comment]
不能是仅仅复制那么简单吧。何况LEAN的OPENWRT内核版本和1806、1907不完全一样。LUCI版本也是。

**Comment by Zack0617** [comment]
可能只有大雕本人知道根本原因了……

**Comment by admi-229133** [comment]
我的表示没有这个问题

**Comment by Zack0617** [comment]
@admi-229133  复制ssr plus源码在官方lede1701下编译没有这个问题，或者直接用lean全套源码编译也没有问题。

**Comment by Kyo628** [comment]
我也是把ssr+复制到官方编译了，但是访问国内是正常。貌似卡在dns解析。

**Comment by Zack0617** [comment]
@Kyo628 国内是正常的，没有问题
