### ISSUE TITLE
无法安装wireguard

### ISSUE THREAD

**Issue by freeasbird** [coolsnowwolf/lede#1575]
最近准备在Linksys wrt1900 acs v2上测试wireguard, 发现无法安装, 不知道哪里设置有问题. 有什么办法吗? 

root@OpenWrt:~# opkg install wireguard
Installing wireguard (0.0.20190702-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a9_vfpv3/base/wireguard_0.0.20190702-1_arm_cortex-a9_vfpv3.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for wireguard:
 *      kernel (= 4.19.66-1-3c0902c22336f8577180341472db3bce) *         kernel (= 4.19.66-1-3c0902c22336f8577180341472db3bce) *        kernel (= 4.19.66-1-3c0902c22336f8577180341472db3bce) * 
 * opkg_install_cmd: Cannot install package wireguard.
root@OpenWrt:~# uname -a
Linux OpenWrt 4.19.66 #0 SMP Sat Aug 17 05:19:21 2019 armv7l GNU/Linux

**Comment by hcym** [comment]
这个编译好点，不然全是内核一级的依赖，麻烦
