### ISSUE TITLE
R7800 5G 无线不正常

### ISSUE THREAD

**Issue by azazjjyjjy** [coolsnowwolf/lede#1578]
目前默认配置编译完后，2.4G正常，5G的无线radio0除非选择美国 149信道不然无法启动。。
这是什么原因？只能用这个信道么

**Comment by hcym** [comment]
不清楚了，我是只用5，一直正常，149干扰多，用了比较冷门的56，哈哈，

**Comment by azazjjyjjy** [comment]
> 不清楚了，我是只用5，一直正常，149干扰多，用了比较冷门的56，哈哈，

我的选其他的5G都开不出来

**Comment by hcym** [comment]
不应该，149段随便吧，36－48可能地区要选us或者新加坡澳洲，56只能选澳洲新加坡，美国都不行的，不光7800，新三和ac58u都可以的，新三还是mt76的。用官方最新版本编译的肯定行，大雕的驱动老一些，失效概率大

**Comment by shenzt68** [comment]
K3用官方无线驱版，5G无法加密码
