### ISSUE TITLE
newifiD2固件无法安装mariadb-server，因libgcc冲突而无法安装libgcc1依赖

### ISSUE THREAD

**Issue by kailanguage** [coolsnowwolf/lede#1580]
根据报错删除/lib/libgcc_s.so.1整个系统崩溃，opkg无法卸载libgcc，也不能安装libgcc1

之后我在固件编译时直接添加mariadb数据库，安装成功，但在初始化数据库时一直无法成功，各方面配置没有问题，内存也充足。后来查看系统日志发现是mariadb存在内存地址错误，然后我卸载程序，再也无法通过opkg安装，显示依然是libgcc1无法安装的问题。

**Comment by rufengsuixing** [comment]
opkg install --force-overwrite xxx
如果不行就进入/usr/lib/opkg/info/status 删除掉和你安装冲突的应用的hold标签
