### ISSUE TITLE
zerotier

### ISSUE THREAD

**Issue by zyh6111** [coolsnowwolf/lede#1585]
最新版本的源码下编译出的x86-64固件，在群晖虚拟机中运行，软路由开启zerotier后，群晖cpu占用率相比之前编译的版本高百分之二十多（之前占用率百分之1左右），再一个就是页面提交更改之后响应速度不如之前版本流畅、顺滑，希望大雕能改进一下。

**Comment by kd142718** [comment]
zerotier的1.4.0有CPU占用比较高更新到1.4.2就好了。
/lede/feeds/packages/net/zerotier 编辑 Makefile   PKG_VERSION:=1.4.2  PKG_HASH:=557a444127812384265ec97232bae43dce1d4b1545ddd72e2b1646c971dad7c5
