### ISSUE TITLE
BitComet下载时负载高，K2P路由器卡死

### ISSUE THREAD

**Issue by xynu617** [coolsnowwolf/lede#1586]
8月30日晚上用最新代码编译的，插件只选了SSR-PLUS，ADBYBY-PLUS KMS服务器 Turbo ACC UPNP，去掉了无线驱动，只要电脑一开BitComet，路由器概况界面的活动连接数和实时负载就飙升，连接数最高到5000多，负载到7左右，然后就无法访问路由器了，关掉BitComet过一会路由器就会恢复
![搜狗截图19年08月31日1325_1](https://user-images.githubusercontent.com/53331950/64060107-ea9e0d80-cbfa-11e9-968c-1031c5c1873c.jpg)
![微信截图_20190831132804](https://user-images.githubusercontent.com/53331950/64060110-ee319480-cbfa-11e9-8d4d-ea9c4b8adc5a.jpg)

**Comment by ope087** [comment]
SSR-PLUS，ADBYBY-PLUS , Turbo ACC ,UPNP一个一个关了试试

**Comment by wuypinfo** [comment]
换N1来下载。路由都被累死了。

**Comment by coolsnowwolf** [comment]
CPU 拉不住这么多 UDP Fullcone 了，升级 CPU 或者关闭 Fullcone 。建议升级 CPU

**Comment by xynu617** [comment]
> CPU 拉不住这么多 UDP Fullcone 了，升级 CPU 或者关闭 Fullcone 。建议升级 CPU

多谢大雕，关了FullCone-NAT果然就好了
