### ISSUE TITLE
开启BBR加速时SSR+的速度会极大下降

### ISSUE THREAD

**Issue by Xerxes-2** [coolsnowwolf/lede#1587]
最近几个版本出现这个问题，开启BBR加速之后SSR+的速度会降低到4000kbps以下

**Comment by zxlhhyccc** [comment]
> 最近几个版本出现这个问题，开启BBR加速之后SSR+的速度会降低到4000kbps以下

BBR加速是用于服务器的，除非你路由作为服务器，但是使用魔改BBR可以加速。。。。

**Comment by czb1994** [comment]
个人感觉路由器对外做服务器（ipsec或者私有云）可以开bbr，没有对外做服务器bbr真的会有减速buff

**Comment by rufengsuixing** [comment]
对外服务器开了bbr，350kb，没开3.5mb
233
