### ISSUE TITLE
导入配置，如何实现三种格式？

### ISSUE THREAD

**Issue by wuypinfo** [coolsnowwolf/lede#1589]
![TIM截图20190901141140](https://user-images.githubusercontent.com/46482182/64072523-9e1e0500-ccc2-11e9-8a4c-1d44dd8a2ef7.jpg)

前天clone后，编译，就只有ssr一种格式。如何实现支持三种？

**Comment by shikkoku** [comment]
一直都是一种格式，你可能是装了第三方魔改的ssrplus插件才会有三种格式。
