### ISSUE TITLE
用户自定义GFW-List 每次升级以后就还原了

### ISSUE THREAD

**Issue by tossp** [coolsnowwolf/lede#159]
升级的时候勾选保留配置，但升级后ssr的自定义GFW-List 还是被还原了

**Comment by azuse** [comment]
用户自定义gfw-list是保存在/etc/shadowsocksr/里的，备份配置和升级的时候并没有保留这个文件夹里的文件。

**Comment by tossp** [comment]
原来是这样的，谢谢
