### ISSUE TITLE
编译完的后使用无法保存配置

### ISSUE THREAD

**Issue by dndnt** [coolsnowwolf/lede#1593]
不知道什么原因，PVE下和VMware下都试过了，直接挂qcow2和vmdisk或者是img写入磁盘都试过，改完设置重启后就是初始化的。
[.config](https://github.com/coolsnowwolf/lede/files/3563417/default.config.zip)

**Comment by ope087** [comment]
kmod-fs-squashfs,kmod-fs-f2fs选上试试

**Comment by dndnt** [comment]
谢谢ope087的帮助。
目前问题解决了，具体什么原因引起的，可能是加载qcow2后调整过容量导致写保护，可有可能是kmod-fs-squashfs,kmod-fs-f2fs没选上，我dirclean后重新编译挂载，未改容量的情况下正常了。
以上内容供大家参考。
