### ISSUE TITLE
麻烦老大替换一下ssrurl，这样可以导入三种链接。

### ISSUE THREAD

**Issue by wuypinfo** [coolsnowwolf/lede#1594]
不能通用，替换后不行。

**Comment by shikkoku** [comment]
完全不明白你再说什么

**Comment by wuypinfo** [comment]
![TIM截图20190902182630](https://user-images.githubusercontent.com/46482182/64108424-53c68200-cdaf-11e9-88f7-9881a3b63b82.jpg)
大多数固件编译出来只支持ssr的链接倒入，少数可以倒入三种。虽然可以订阅，你有没有发现，删除订阅死链接很恼人？

**Comment by shikkoku** [comment]
![Annotation 2019-09-03 102347](https://user-images.githubusercontent.com/4697177/64139851-eeb56f80-ce34-11e9-97e3-d96a8cd10fa6.jpg)
你是指希望能在SSR PLUS+的新建节点这里增加导入ss、vmess类型链接导入是吗，麻烦描述清楚点。

**Comment by wuypinfo** [comment]
我希望能在SSR PLUS+的新建节点这里增加导入ss、vmess类型链接导入。
[导入三种链接.zip](https://github.com/coolsnowwolf/lede/files/3567525/default.zip)
这里有2个ssrurl，mix的是可以匹配目前该源文件。另外一个是潘多拉固件分离的，你直接运行就能看到。如果放入路由，去掉mix，还原为ssrurl.htm

**Comment by adamw92** [comment]
> 我希望能在SSR PLUS+的新建节点这里增加导入ss、vmess类型链接导入。
> [导入三种链接.zip](https://github.com/coolsnowwolf/lede/files/3567525/default.zip)
> 这里有2个ssrurl，mix的是可以匹配目前该源文件。另外一个是潘多拉固件分离的，你直接运行就能看到。如果放入路由，去掉mix，还原为ssrurl.htm

感谢~直接替换mix的版本之后SS可以导入了，目前导入正常，方便了不少…
