### ISSUE TITLE
pdnsd 通过网页操作挂掉问题

### ISSUE THREAD

**Issue by 275761919** [coolsnowwolf/lede#1599]
关联问题：https://github.com/coolsnowwolf/lede/issues/817
一通过网页操作或者重启ssr后pdnsd就会挂掉，用`netsate`查看也没有5335端口占用
用`nslookup google.com 127.0.0.1#5335`当然也查不到ip了

但是通过shell执行命令`/etc/init.d/shadowsocksr restart`或者`kill`掉`pdnsd`进程再单独执行命令`pdnsd` -c /var/etc/pdnsd.conf -d` 就恢复正常了

**Comment by 275761919** [comment]
是用openwrt-sdk官方固件编译和openwrt-imagebuilder生成固件的。

**Comment by 275761919** [comment]
使用 dnsforwarder 替代，监听在5335端口，ssr-plus 配置成使用本机5335的那个选项。

**Comment by 275761919** [comment]
或者按照 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=339256 这个贴子一通乱操作也可以了。。。。

**Comment by Maskia** [comment]
pdnsd-ctl status看是莓有tcp查询线程...所以比较好奇你按照帖子改了什么

**Comment by txdywy** [comment]
赞!重启pdnsd管用!

**Comment by hcym** [comment]
不觉名莉
