### ISSUE TITLE
SSR能否实现不同无线终端走不同SSR节点？

### ISSUE THREAD

**Issue by TeddyDSS** [coolsnowwolf/lede#1602]
共有3个无线终端，路由已填写3个不同的SSR节点1,2,3！！请问下如何实现无线终端1走SSR节点1，无线终端2走SSR节点2，无线终端3走SSR节点3？ 盼大佬回复！

**Comment by ope087** [comment]
只能分正常和游戏两种可以按ip设置,或者再挂个旁路由
