### ISSUE TITLE
qb打开web控制页面无法跳转

### ISSUE THREAD

**Issue by zcluo** [coolsnowwolf/lede#1603]
qb打开web控制页面无法跳转到控制页，变成一个下载document 的提示

**Comment by Kinodi** [comment]
需要手动输入

**Comment by zcluo** [comment]
> 需要手动输入

是ip加端口就可以嘛后面还跟什么路径嘛？

**Comment by zxlhhyccc** [comment]
> qb打开web控制页面无法跳转到控制页，变成一个下载document 的提示

你用https重定向可以。。。。

**Comment by zcluo** [comment]
可以进入控制台，但拷贝pt的链接放到qb上下，一点开始就挂了。。。

**Comment by zxlhhyccc** [comment]
> 可以进入控制台，但拷贝pt的链接放到qb上下，一点开始就挂了。。。

升级。。。我现在使用的是4.1.7最新版本。。。

**Comment by zcluo** [comment]
> > 可以进入控制台，但拷贝pt的链接放到qb上下，一点开始就挂了。。。
> 
> 升级。。。我现在使用的是4.1.7最新版本。。。

自己下编译包嘛？

**Comment by zcluo** [comment]
换了可以了，lean能否升下qb到4.1.7

**Comment by ope087** [comment]
我提交了升级和问题修复,他还没合并,还升级了boost和qt5支持ssl,不然geoip和搜索插件都不能用

**Comment by zcluo** [comment]
> 我提交了升级和问题修复,他还没合并,还升级了boost和qt5支持ssl,不然geoip和搜索插件都不能用

👍
