### ISSUE TITLE
SSR+节点的顺序发生变化时会断开之前连的节点重连其它节点

### ISSUE THREAD

**Issue by willaytoun** [coolsnowwolf/lede#1604]
我这边两个机场订阅(40个节点).每天早上5点自动更新订阅,有时候会增减几个节点或者顺序发生变化，这时候就会切换连接的节点，切换之后有时整个机场的节点都不能用。

**Comment by zry118** [comment]
免费4k机场：http://www.vwall.gq/auth/register?code=0BKG
