### ISSUE TITLE
公司环境下SSR plus+性能问题

### ISSUE THREAD

**Issue by alechsu** [coolsnowwolf/lede#1607]
固件家用完全没有问题，但是公司用特别是ip route模式下就无法上网了，就像是堵住了一样，看了下，公司设备在250台左右，平时每天在线5000-6000条并发连接，因为是外企很大一部分链接应该是连到境外诸如office365云服务。请高手指教有没有可以调整SSR plus+插件性能的地方，或者插件的设计性能就不能满足这样的并发数？谢谢！

**Comment by poemsiu** [comment]
你的路由器性能够不够，cpu占用如何

**Comment by alechsu** [comment]
路由器性能不可能不够的，Dell R630 虚拟服务器

**Comment by rampageX** [comment]
haproxy 做负载均衡

**Comment by alechsu** [comment]
所以这是服务端的性能问题？不是SSR plus+的问题？

**Comment by coolsnowwolf** [comment]
感觉是服务器端性能不足的问题，htop 截个图看看

**Comment by coolsnowwolf** [comment]
如果是客户端问题，其实可以启用更多的 SS/SSR 线程数解决，例如 16/32，自动内核级负载均衡的

**Comment by alechsu** [comment]
![Openwrt](https://user-images.githubusercontent.com/22169946/64408503-8925e500-d0b9-11e9-96cc-9041625de754.JPG)

**Comment by alechsu** [comment]
上面贴图是gfwlist模式下的htop，可运行，但是切换到ip route外网就断了。。。。我觉得不是机器性能的为题，可能是ip route 模式的性能问题？或者ip route有bug，大并发量下面会当？

**Comment by lifetyper** [comment]
SSR服务器端都是python版的，只能利用单核CPU的性能，并发数一多，完全可能在你客户端崩掉之前服务端就挂了。

**Comment by alechsu** [comment]
不太懂python，我用v2ray也是一样，所以这些翻墙方案都不是设计给公司用的？

**Comment by lifetyper** [comment]
> 不太懂python，我用v2ray也是一样，所以这些翻墙方案都不是设计给公司用的？

公司不是应该拉专线？还用SSR给全公司翻墙，网管是想喝茶了？

**Comment by coolsnowwolf** [comment]
服务器端的性能问题了，需要在服务器端用 tcpreuseport 解决

**Comment by alechsu** [comment]
> > 不太懂python，我用v2ray也是一样，所以这些翻墙方案都不是设计给公司用的？
> 
> 公司不是应该拉专线？还用SSR给全公司翻墙，网管是想喝茶了？

因为到海外分公司的专线带宽有限，并且我也试过了从专线连接分公司的ssr服务器，gfwlist模式没啥问题，但是切换到ip route模式没几秒种就死。。。

**Comment by lifetyper** [comment]
> > > 不太懂python，我用v2ray也是一样，所以这些翻墙方案都不是设计给公司用的？
> > 
> > 
> > 公司不是应该拉专线？还用SSR给全公司翻墙，网管是想喝茶了？
> 
> 因为到海外分公司的专线带宽有限，并且我也试过了从专线连接分公司的ssr服务器，gfwlist模式没啥问题，但是切换到ip route模式没几秒种就死。。。
找rixcloud定制企业版的服务吧

**Comment by alechsu** [comment]
> 服务器端的性能问题了，需要在服务器端用 tcpreuseport 解决

问题最终解决了，确实是插件的并发能力被系统默认限制了，我在ssr插件的启动脚本（/etc/init.d/shadowsocksr）里面加了两条命令：ulimit -n 1000000 和 ulimit -p 65000 （怀疑只需要ulimit -n就行了）然后服务端也打开linux默认限制后，绕过大陆模式非常稳定了，另外我在设置v2ray时候用了mux参数来控制总体连到vps的连接数。
![image](https://user-images.githubusercontent.com/22169946/65215074-d2752c00-dade-11e9-94d5-78100b9e2981.png)
