### ISSUE TITLE
网卡驱动

### ISSUE THREAD

**Issue by small32** [coolsnowwolf/lede#1615]
请问大佬，系统里带的ixgbe驱动是什么版本的？我用版本查看命令查看不了

不知道这个ixgbe驱动支持X540/X550不

**Comment by hcym** [comment]
对应关系看一看，普通的都有，你这个没注意

**Comment by small32** [comment]
主要是想上万兆，所以想了解下，老型号的万兆网卡82599是支持的，但是新的X540，X550不知道能用不
