### ISSUE TITLE
ssr+ 在大陆白名单模式下无法访问苹果ID服务器 显示502错误。求教。

### ISSUE THREAD

**Issue by 404user** [coolsnowwolf/lede#1618]
全局模式，大陆白名单也好，都无法打开appleid.apple.com，提示502错误，想请问一下大佬这个是BUG吗？

**Comment by lifetyper** [comment]
换个节点

**Comment by 404user** [comment]
> 换个节点

你好，我是自建的Google云的V2RAY，HK的点。这样和节点没关系吧？因为我用路由器关掉SSR+后，用电脑上的V2RAY客户端打开，都没问题呀。

**Comment by jobber2955** [comment]
你的plus，v2ray的服务器，能使用gfw或者大陆IP模式吗？
我的只能使用全局模式，而且不管什么模式，状态里都是显示谷歌不能联通，百度可以，端口也可以

**Comment by 404user** [comment]
> 你的plus，v2ray的服务器，能使用gfw或者大陆IP模式吗？
> 我的只能使用全局模式，而且不管什么模式，状态里都是显示谷歌不能联通，百度可以，端口也可以

几种模式都可以上。大陆白名单就是苹果的ID服务器网站打不开。
