### ISSUE TITLE
最近接口老是出问题！

### ISSUE THREAD

**Issue by outemancut** [coolsnowwolf/lede#1620]
Fri Sep 13 15:21:03 2019 kern.info kernel: [ 7839.852946] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
Fri Sep 13 15:21:17 2019 kern.info kernel: [ 7853.904488] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up

前面的系统日志，后面的是内核日志

[ 7545.121235] pppoe-wan: renamed from ppp0
[ 7582.843845] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
[ 7596.979442] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
[ 7839.852946] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
[ 7853.904488] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up

**Comment by rufengsuixing** [comment]
相当于啥也没说，只是接口被拔插了
