### ISSUE TITLE
如何适配MT7628 meizu_mini_pro？

### ISSUE THREAD

**Issue by happy201807** [coolsnowwolf/lede#1623]
您好，

请问如何添加对搭载cpu mt7628/ 无线mt7628+7610的meizu_mini_pro/R13P(只有一个WAN口)的支持？

有看到是支持同芯片的hc5661a，但是没有这款,请问能否添加支持？

**Comment by rufengsuixing** [comment]
看看op源码有没有你型号的dts文件

**Comment by happy201807** [comment]
您好，按照您的方法，已经参考hc5761a适配了meizu_mini_pro这款设备，可以连上两个WiFi，但是flash似乎无法正确识别，软件包显示可用为0B，还得请教下这个怎么解决？

> 
> 
> 看看op源码有没有你型号的dts文件，自行加入，然后修改mt7628.mk源码

您好，按照您的方法，已经参考hc5761a适配了meizu_mini_pro这款设备，可以连上两个WiFi，但是flash似乎无法正确识别，软件包显示可用为0B，还得请教下这个怎么解决？

**Comment by dysl357085918** [comment]
> 

软件包的可用性为0可能是你没有修改完全。我这边修改了正常。参考hc5761a的dts文件中引用了一个dtsi文件，那个里面说明了闪存。需要修改那里
