### ISSUE TITLE
IPsec服务器，android9能连接成功，但无法使用。

### ISSUE THREAD

**Issue by zhouyan0571** [coolsnowwolf/lede#1630]
内网192.168.123.x

设置 192.168.111.50/24 
DNS 192.168.111.1
可以访问内网下各个主机以及路由
无法访问百度以及谷歌

设置 192.168.123.50/24 
DNS 192.168.123.1
无法访问内网下各个主机以及路由
无法访问百度以及谷歌
该设置下ios可以正常访问内网以及谷歌和百度

根据ipsec资料修改/etc/ipsec.conf
未找到sha2-truncbug=条目
并且luci中修改配置后重启
所有手动修改的配置丢失

**Comment by czb1994** [comment]
同样的问题miui和类原生安卓9.0都一样，b站无论是客户端还是网页无法播放视频，ios一切正常，最重要的是没有报错的日志文件，或者我不知道去哪里找，路由器上面没有错误的日志

**Comment by ilasx** [comment]
我的怎么设置都不能上外网。。。
