### ISSUE TITLE
libelf的下载地址已失效

### ISSUE THREAD

**Issue by likanchen** [coolsnowwolf/lede#1632]
解决方法是将tools/libelf/Makefile的第16行从 PKG_SOURCE_URL:=http://www.mr511.de/software/ 改为 PKG_SOURCE_URL:=https://fossies.org/linux/misc/old/

**Comment by Zxilly** [comment]
建议直接发起Pull Request

**Comment by likanchen** [comment]
> 建议直接发起Pull Request
在此处记录，因为发现几个makefile下载链接失效导致编译停止的问题，全部找到后再pull request
