### ISSUE TITLE
luci-app-ipsec-server 在源码里怎么找不到

### ISSUE THREAD

**Issue by ihuaer** [coolsnowwolf/lede#1633]
ipsec 服务器插件 怎么在源码里找不到呢
谁能帮我下

**Comment by zhouyan0571** [comment]
https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-ipsec-vpnd

**Comment by ihuaer** [comment]
> https://github.com/coolsnowwolf/lede/tree/master/package/lean/luci-app-ipsec-vpnd

感谢，原来改名了

**Comment by gqbre** [comment]
现在 luci-app-ipsec-vpnd 也找不到了 @coolsnowwolf
