### ISSUE TITLE
研发请求：实现SSR/V2多通道并行

### ISSUE THREAD

**Issue by shelliao** [coolsnowwolf/lede#1636]
背景：希望能实现不同站点实现不同多业务应用转发，例如耐飞跑a通道，油管跑b通道，其他跑c通道。分流的设置已经在HAProxy上设置好，就坐等多通道功能开发出来后实现按需分流量
功能需求：
1. 在服务器节点中，每个节点加入同时启用勾选项，以标识这个节点可以同时启动隧道
2. 在客户端主服务器下拉菜单中添加同时启动标识节点选项
3. 希望能同时支持ssr与v2，优先支持ssr
4. 希望能支持各架构平台

**Comment by redchenjs** [comment]
顺便发个PR就更好了:joy:

**Comment by ntgeralt** [comment]
每次开会，最先阵亡的是酸酸+乳。没什么必要花大精力研发些迟早淘汰的协议

**Comment by shelliao** [comment]
> 每次开会，最先阵亡的是酸酸+乳。没什么必要花大精力研发些迟早淘汰的协议
调整ssr的设置，可以避开很多问题，不是只单纯使用默认设置，按照正常的思路，肯定会很容易被抓

**Comment by rufengsuixing** [comment]
没意义应用场景太少，代码复杂度成倍提高，想要你可以自己启动几个ss或者v2ray自己负载均衡开心

**Comment by wastelandx** [comment]
说话跟喝水一样的

**Comment by benjaminbnuz** [comment]
OpenClash应该能满足这个需求
