### ISSUE TITLE
最新编译的固件总是出现DNS污染

### ISSUE THREAD

**Issue by yhj39300** [coolsnowwolf/lede#1638]
![`29VU4{CJ99Z{NBUN2EEO7X](https://user-images.githubusercontent.com/22695307/65152026-c2673900-da59-11e9-95d3-b0285f65ea4d.png)
服务器可以连通，大概看youtube 十几分钟然后就没速度。DNS被污染出现这种现象！

**Comment by brick713** [comment]
额，你这个图看不出来是 dns 污染啊

**Comment by shikkoku** [comment]
无法复现

**Comment by hcym** [comment]
大雕的gfwlist模式是有点事，不光是大雕，另外几个大佬的源码也是喜欢转圈，现在又是猪瘟闹心，干脆用chn模式，费点流量稳定多了
