### ISSUE TITLE
GFW 用户自定义列表，无效

### ISSUE THREAD

**Issue by gbaoye** [coolsnowwolf/lede#1641]
我用V2玩游戏，添加游戏网址无效，在访问控制里添加指定IP也无效，是不是我用错了姿势
109.239.140.0/24，/24是什么东西

**Comment by wangxin6** [comment]
代表从109.239.140.0到109.239.140.255这256个host

**Comment by gbaoye** [comment]
> 代表从109.239.140.0到109.239.140.255这256个host

24代表256，那20，22呢，快告诉我，快点，我又学到了新知识

**Comment by isxiaojian** [comment]
> > 代表从109.239.140.0到109.239.140.255这256个主机
> 
> 24代表256，那20,22呢，快告诉我，快点，我又学到了新知识
24/22/24 代表掩码位长度 

采用20位掩码 可用地址有4096个
第一个可用是109.239.128.1
最后一个可用是109.239.143.254
掩码是109.239.143.254
广播是109.239.143.255

22位掩码可一自己算、或者自己找网络ip地址计算器算一下就行了
