### ISSUE TITLE
树莓派编译冲突

### ISSUE THREAD

**Issue by ok000305** [coolsnowwolf/lede#1642]
cc1plus: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
每次编译都显示这个，我也只够了几个luci插件，我不知道如何解决这个冲突

**Comment by rampageX** [comment]
https://forum.kodi.tv/showthread.php?tid=315143

**Comment by ok000305** [comment]
这编译的并不是一个东西，我无法在openwrt文件夹里找到可以修改这个的文件
