### ISSUE TITLE
L大可以把shadowvpn加入到SS Plus吗，游戏可能用到！

### ISSUE THREAD

**Issue by yhj39300** [coolsnowwolf/lede#1649]
![QQ截图20190921193646](https://user-images.githubusercontent.com/22695307/65372813-6560c280-dca7-11e9-9b5f-35a609648e7d.png)

**Comment by tanpengsccd** [comment]
胸带 玩游戏 你用的哪个加速阿？兼容v2ray 而且可以支持udp的那种。最近玩apex

**Comment by rufengsuixing** [comment]
不需要吧，vpn直接路由就好了，不会像代理这样麻烦

**Comment by rookietribe** [comment]
@tanpengsccd 试试 https://github.com/NetchX/Netch
