### ISSUE TITLE
编译了后没有找到ssr选项 

### ISSUE THREAD

**Issue by stevenliuit** [coolsnowwolf/lede#1650]
编译完后没有找到ssr选项
![image](https://user-images.githubusercontent.com/4044994/65373274-d905ce00-dcad-11e9-8ef5-b20f834c7b82.png)
![image](https://user-images.githubusercontent.com/4044994/65373278-dc00be80-dcad-11e9-8834-8e492fc4d98a.png)

**Comment by stl88083365** [comment]
百度搜索神秘代码

**Comment by stevenliuit** [comment]
咋解决啊

**Comment by shikkoku** [comment]
Duplicate of #1563

**Comment by RoweV194** [comment]
这个问题在关闭问题中能找到
