### ISSUE TITLE
关于MT7603鸡血驱动的问题

### ISSUE THREAD

**Issue by tufu9441** [coolsnowwolf/lede#1656]
请教一下lintel和Lean大神给Newifi D2（新路由3）做的Pandorabox固件中所使用的MT7603鸡血驱动是否有公开的版本，自己能否编译？目前在网上只找到了这个MT7603的闭源驱动，不知道是不是：https://github.com/Nossiac/mtk-openwrt-feeds

**Comment by hcym** [comment]
是不是2.4好一点？我的新三一直用的开源，5G非常好，比ac58u还好，只是比k2p差点意思

**Comment by tufu9441** [comment]
@hcym MT7603本来就是2.4G的芯片。

**Comment by hcym** [comment]
哦，那是我不懂，路由也从来不用2.4，光猫凑合用足够
