### ISSUE TITLE
关于LED灯显示问题

### ISSUE THREAD

**Issue by admi-229133** [coolsnowwolf/lede#1657]
今天发现lucihttp更新了 去更新了一下 总体还不错就是LED灯触发器缺少pb_internet这个驱动程序支持所以并没有起作用在源码里面也没有找到

**Comment by lxwq** [comment]
「系统」－「LED配置」这个菜单如何取消掉啊，用不到，
![image](https://user-images.githubusercontent.com/51162826/65476179-a11ca780-deb4-11e9-81a1-0eea68f62045.png)

**Comment by shikkoku** [comment]
我之前在编译的时候选了一堆LED选项是有内容的，今天再编译完成这里就空白了。
