### ISSUE TITLE
新版LuCI不兼容

### ISSUE THREAD

**Issue by admi-229133** [coolsnowwolf/lede#1658]
LuCI Master (git-19.265.58015-b31beb5)版本下安装NFT-QOS限速类型选择Dynamic 无法保存应用

**Comment by admi-229133** [comment]
计划任务自带命令也无效！

**Comment by shikkoku** [comment]
LuCI Master (git-19.146.62144-fd6fdb2) OpenWrt R9.9.15 X86-64是这个版本，你是从哪个源编译的？

**Comment by admi-229133** [comment]
> LuCI Master（git-19.146.62144-fd6fdb2）OpenWrt R9.9.15 X86-64是这个版本，你是从哪个源编译的？

那你先别更新新版的LUCI有问题

**Comment by shikkoku** [comment]
你不是去Openwrt的官方源升级了luci吧？很多不兼容的。

**Comment by ope087** [comment]
lean最近应该是更新过luci库的,我最近一次编译也更新了,好像是有点问题,比如说ssr-plus状态里的谷歌联通性检查永远是连接错误,我用旧版本试了是没问题的

**Comment by shikkoku** [comment]
OpenWrt R9.10.1 / LuCI Master (git-19.268.50099-562a894) 😂，是有一些第三方的luci-app出现了无法保存配置的问题。

**Comment by admi-229133** [comment]
> OpenWrt R9.10.1 / LuCI Master (git-19.268.50099-562a894) 😂，是有一些第三方的luci-app出现了无法保存配置的问题。

你自己去提交问题啊 你跟我说有啥用
