### ISSUE TITLE
需要给某个IP限速，SQM真的不会用网上搜的看不懂，希望加个傻话化的功能

### ISSUE THREAD

**Issue by willaytoun** [coolsnowwolf/lede#1661]
想要给某个特定的IP限速(比如192.168.1.100)，SQM真的无从入手网上也搜过相关资料代码什么的看不懂(图1)
![SQM配置](https://user-images.githubusercontent.com/43229736/65483139-c23dc200-decd-11e9-86ed-d8c38c86bdbb.png)
希望价格傻话化的功能(图2)
![TD限速](https://user-images.githubusercontent.com/43229736/65483160-d41f6500-decd-11e9-8356-40f40be2ab18.png)
如果有SQM的教程麻烦大家发个链接我学一下，感谢

**Comment by ope087** [comment]
nft-qos解君愁
