### ISSUE TITLE
V2RAY TLS1.3支持问题

### ISSUE THREAD

**Issue by v8866** [coolsnowwolf/lede#1662]
固件为Sep 17, 2019.
V2RAY服务器为4.20版本的WebSocket+TLS+Web模式 服务器WEB只开TLS1.3 反代..连接不成功.

**Comment by 07031218** [comment]
和插件没有关系，你检查下VPS端v2ray的config.json和Nginx的conf文件。应该是这2处配置错误。

**Comment by v8866** [comment]
> 和插件没有关系，你检查下VPS端v2ray的config.json和Nginx的的CONF文件。应该是这2处配置错误。

配置应该没问题吧。电脑版的能用…路由器不行

**Comment by 0x5826** [comment]
allow insecure要设置成yes，openwrt证书库可能不认let't encrypt证书
