### ISSUE TITLE
建议: 55R++插件可以换一个名字

### ISSUE THREAD

**Issue by KFERMercer** [coolsnowwolf/lede#1670]
现阶段55, 55r已经可以被GFW识别, 这两种技术也处在淘汰边缘. 55R++作为一个集爬梯大成的雕wrt的拳头产品, 没必要用其中的一个功能组件的名字为整个插件命名. 建议换成一个更具`内涵`的名字, 这样也更有利于隐藏其功能, 防止查水表. 这里有一个例子: 

`luci-app-vagina`  `阴道`

取`阴兵借道`之意

望采纳

**Comment by coolsnowwolf** [comment]
这个。。。

**Comment by redchenjs** [comment]
。。。

**Comment by mlpzaq9998** [comment]
6啊 大兄弟 你真妙

**Comment by ulpyuxa** [comment]
大兄弟，您的文采实在是太好了。大雕不用都不好意思了。

**Comment by lpflhh** [comment]
那还不如直接叫大雕插件

backup <notifications@github.com> 于 2019年9月26日周四 15:47写道：

**Comment by dongfangy2011** [comment]
楼上的建议最好，我赞成

**Comment by antidoom** [comment]
其实不是ssr被识别，而是白名单加黑名单一起来的。而且各技术论坛卧底很多。哪家开了服务他们很快会知道。比较大型的主机商都在黑名单。

**Comment by 0x5826** [comment]
我也觉得现在叫这个名字很尴尬其实本质上它只是ss ssr v2ray不如起一个综合一点的名字

**Comment by bjmxie** [comment]
妙啊妙啊

**Comment by luckyjinx** [comment]
您是真的秀

**Comment by yanghong0** [comment]
阴道，我感觉你是在针对大雕。
