### ISSUE TITLE
酸酸乳BUG

### ISSUE THREAD

**Issue by admi-229133** [coolsnowwolf/lede#1671]
不知道是不是luci-theme-argon这个主题的BUG还是酸酸乳自身的BUG，我用luci-theme-argon这个主题在服务器节点那里删除所有服务器左边空白区可以触发删除 很大一部分空白区域都可以触发删除！Powered by LuCI Master (git-19.268.50099-562a894) ！

**Comment by coolsnowwolf** [comment]
主题的bug

**Comment by admi-229133** [comment]
> 主题的错误

好吧 不过DHCP/DNS里面那个顺序分配 IP是不是无效果的 勾上了保存也不起作用，还有一点把 使用 all-servers 并发查询 这个勾上也出现一个未汉化的选项
