### ISSUE TITLE
大佬有空可以修复一下单线并发多拨功能吗？

### ISSUE THREAD

**Issue by mlpzaq9998** [coolsnowwolf/lede#1673]
现在MT7621路由器唯一单线并发多拨能用的就是高恪了 但固件臃肿，不支持插件，连usb都没了，单线并发多拨还是不少人需要的，期待修复，马上转战lede

**Comment by tinnlux** [comment]
单线多拨一直是好的，从来没坏过

**Comment by mlpzaq9998** [comment]
> 单线多拨一直是好的，从来没坏过

是好的没问题 但是有的地区需要单线并发多拨 并发是坏的
