### ISSUE TITLE
最近编译的LAN口顺序反了

### ISSUE THREAD

**Issue by RealKiro** [coolsnowwolf/lede#1676]
![image](https://user-images.githubusercontent.com/33367701/65739463-e7be0c00-e117-11e9-8ba1-38c03a471d85.png)
新3 MTK7621
以前编译 交换机分配WAN是按照LAN标志的顺序选择，最近两天更新源码编译后LAN口反着来了；不知你们是这样吗？

**Comment by admi-229133** [comment]
恩 确实是反过来的！
