### ISSUE TITLE
酸酸乳 ++ 在GFW下无法出国

### ISSUE THREAD

**Issue by huangjackey1111** [coolsnowwolf/lede#1680]
在GFW下无法出国，但是绕过大陆IP模式却可以，不知道为什么，PC DNS也是指向路由的。

**Comment by huangjackey1111** [comment]
是不是和IPV6有冲突呢？

**Comment by hcym** [comment]
是的，经常出现，用路由模式吧

**Comment by huangjackey1111** [comment]
> 是的，经常出现，用路由模式
感觉就是和什么有冲突的样子，但不知道是什么。
是不是负载均衡？或者是什么。。不清楚。
