### ISSUE TITLE
酸酸乳绕过中国IP模式FullCone-NAT无效

### ISSUE THREAD

**Issue by outemancut** [coolsnowwolf/lede#1682]
酸酸乳使用绕过中国大陆IP模式用NAT类型测试工具测试FullCone-NAT发现开启无效果，而用GFW模式测试则正常有效果！

**Comment by dongfangy2011** [comment]
但是我两种方式用移动网络一直出不去

**Comment by huangjackey1111** [comment]
> 酸酸乳使用绕过中国大陆IP模式用NAT类型测试工具测试FullCone-NAT发现开启无效果，而用GFW模式测试则正常有效果！

你和我刚好反过来。
