### ISSUE TITLE
NanoPi R1

### ISSUE THREAD

**Issue by EstFoxs** [coolsnowwolf/lede#1686]
每次编译烧录TF卡，系统不识别，编译后的两个文件一个才32M ，一个120M，整个过程都是全局网络，折腾了一天，要崩溃了。@tjaol 提到 WiFi/蓝牙模块 是 (AMPAK) 正基 AP6212，网上查询的资料是AP6212：采用博通bcm43438主芯片

**Comment by speedyworldclub** [comment]
should be bcm43430

**Comment by weareware** [comment]
> 每次编译烧录TF卡，系统不识别，编译后的两个文件一个才32M ，一个120M，整个过程都是全局网络，折腾了一天，要崩溃了。@tjaol 提到 WiFi/蓝牙模块 是 (AMPAK) 正基 AP6212，网上查询的资料是AP6212：采用博通bcm43438主芯片

你后来怎么解决的，我现在也遇到了

**Comment by weareware** [comment]
> 每次编译烧录TF卡，系统不识别，编译后的两个文件一个才32M ，一个120M，整个过程都是全局网络，折腾了一天，要崩溃了。@tjaol 提到 WiFi/蓝牙模块 是 (AMPAK) 正基 AP6212，网上查询的资料是AP6212：采用博通bcm43438主芯片

大佬，我对比了别人的boot分区和我编译的boot分区，感觉少了很多东西，请问你后来解决了吗
