### ISSUE TITLE
关于编译mosquitto求教

### ISSUE THREAD

**Issue by madcat0513** [coolsnowwolf/lede#1692]
想编译luci-app-mosquitto进固件，但是make menuconfig里根本看不到这个选项，官方倒是能找到这个包的，不过依赖啥的太麻烦，装不上啊

**Comment by stl88083365** [comment]
下载地址放上来看看。

**Comment by madcat0513** [comment]
https://openwrt.proxy.ustclug.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/luci/luci-app-mosquitto_git-19.270.39227-355223e-1_all.ipk
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a15_neon-vfpv4/luci/luci-app-mosquitto_git-19.271.67895-cf887ba-1_all.ipk

**Comment by stl88083365** [comment]
L大的源码里有这个客户端啊  用  / 查看。

**Comment by madcat0513** [comment]
没看懂，请问具体怎么操作？

**Comment by stl88083365** [comment]
make menuconfig,然后 按键盘上的   “/”   按钮  输入你要搜索的

**Comment by madcat0513** [comment]
~/openwrt/lean$ cat .config |grep mosquitto
# CONFIG_PACKAGE_lua-mosquitto is not set
# CONFIG_PACKAGE_libmosquitto-nossl is not set
# CONFIG_PACKAGE_libmosquitto-ssl is not set
# CONFIG_PACKAGE_mosquitto-client-nossl is not set
# CONFIG_PACKAGE_mosquitto-client-ssl is not set
# CONFIG_PACKAGE_mosquitto-nossl is not set
# CONFIG_PACKAGE_mosquitto-ssl is not set
还是没luci-app-mosquitto
