### ISSUE TITLE
zerotier编译不过去

### ISSUE THREAD

**Issue by jovishow** [coolsnowwolf/lede#1695]
正常make编译到zerotier后，报错如下：
make[3] -C feeds/packages/net/zerotier compile
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [world] Error 1

再次执行make -j1 V=s报错如下:
mipsel-openwrt-linux-musl-g++: error: unrecognized command line option '-mmacosx-version-min=10.7'
mipsel-openwrt-linux-musl-g++: error: unrecognized command line option '-stdlib=libc++'
make[4]: *** [node/C25519.o] Error 1
make[3]: *** [/Volumes/CompilerHD/lede/build_dir/target-mipsel_24kc_musl/ZeroTierOne-1.4.6/.built] Error 2
make[3]: Leaving directory `/Volumes/CompilerHD/lede/feeds/packages/net/zerotier'
time: package/feeds/packages/zerotier/compile#0.24#0.12#0.69
make[2]: *** [package/feeds/packages/zerotier/compile] Error 2
make[2]: Leaving directory `/Volumes/CompilerHD/lede'
make[1]: *** [/Volumes/CompilerHD/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/Volumes/CompilerHD/lede'
make: *** [world] Error 2

查了下/lede/build_dir/target-mipsel_24kc_musl/ZeroTierOne-1.4.6/make-mac.mk的文件中的代码，与github上一致，不知如何处理
1.else
        CFLAGS?=-Ofast -fstack-protector-strong
        CFLAGS+=$(ARCH_FLAGS) -Wall -flto -fPIE -mmacosx-version-min=10.7 -DNDEBUG$
        STRIP=strip
endif

2.CXXFLAGS=$(CFLAGS) -std=c++11 -stdlib=libc++

在menuconfig已关闭 network->VPN和luCI->Application后，执行make -j1 V=s仍然报错如下信息：
make[2]: Leaving directory `/Volumes/CompilerHD/lede'
make[1]: *** [/Volumes/CompilerHD/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/Volumes/CompilerHD/lede'
make: *** [world] Error 2

**Comment by hanandjun** [comment]
兄台，还是老老实实在linux下跑吧，mac下我之前把所有用到这货的地方都在default列表里排除了，要是懂的话直接改改代码。或者你设置即使报错了还是继续编译，但是我没试过编译出来的能不能用

**Comment by xiufeiwu** [comment]
我解决了，把Makefile里的
ifeq ($(OSTYPE),Darwin)
	include make-mac.mk
改为
ifeq ($(OSTYPE),Darwin)
	include make-linux.mk
竟然过了，我猜是用了homebrew安装了gnu的gcc，所以源码里解决macos编译的mk文件不适用；使用linux的就编译通过了
