### ISSUE TITLE
ssrplus能否添加域名白名单？

### ISSUE THREAD

**Issue by Bnosora** [coolsnowwolf/lede#1696]
希望能添加一个域名白名单，配合大陆白名单模式比较方便。或许还能顺便解决dnspod插件的冲突问题？（把获取ip的域名加入域名白名单避免获取到错误的公网ip）

顺便一问，目前的gfwlist能否像pc上的pac文件一样在域名前添加@@当作白名单用？

**Comment by jackytang** [comment]
我也挺想要这个功能

**Comment by greennyreborn** [comment]
dnspod 插件已经支持自定义命令来获取ip，你可以使用国内的域名来获取ip
