### ISSUE TITLE
ssrplus sock5 问题

### ISSUE THREAD

**Issue by thkrobe** [coolsnowwolf/lede#1698]
请教一下，我在ssrplus开启sock5代理后，用chrome SwitchyOmega设置代理访问，网站都无法打开，先是提示已经建立安全连接，但是网页就是不加载。
用Proxifier的代理服务器检查也是一样，已经连接到服务器，网页访问失败。
查看系统日志，在开启sock5代理有这么一行错误Invalid cipher name: chacha20-ietf-poly1305, use rc4-md5 instead
还有什么需要配置的吗？

**Comment by ope087** [comment]
不支持那个加密让你用后面那个替换
