### ISSUE TITLE
关于进一步优化ssr关于bt下载的问题

### ISSUE THREAD

**Issue by wybb** [coolsnowwolf/lede#1702]
最新版本在使用“绕过中国大陆IP”模式的时候，加入了端口过滤，这个的确是个相对稳妥的办法，但是还存一个需要改进的地方，虽然bt客户端之间不会使用80，但bt的tracker服务器使用80/443端口却很普遍

假如bt连接境外tracker服务器，“绕过中国大陆IP”模式走的肯定还是ssr，会导致tracker服务器不能正确获取你的外部ip地址（却获取了代理的ip），从而你在tracker上注册的外部IP不正确而无法被连接（类似lowid，bt下载的大忌）

当然在目前情况下，可以考虑手动解析tracker服务器的ip，并将ip填入"不走代理的WAN IP"的白名中，但考虑到tracker的dns可能修改ip，这么做不够灵活方便。

建议添加一个通用的 **"域名白名单"**功能，这个做法其实类似于GFW黑名单。只需要额外添加一个ipsets表，将白名单中的域名解析放入该表中，该表的优先级高于GFW表（类似于不走代理的WAN IP表），进入该表的IP地址一定不会产生绕行。

这样简单的把bt网站（或tracker服务器）的域名填入到白名单中，就可以规避绕行的问题。

**Comment by shNanChen** [comment]
我是`dnsmasq`解析`tracker`服务器到`ipset`，然后插入`iptables RETURN`，实现绕行。
手动当然是没那么方便

**Comment by hineH** [comment]
建议你去Google找一些iptables匹配bt流量的规则，匹配到的流量直接直连。
因为机场也是这么干的，他们能识别到的你本地都能先识别出来。
别忘了编译的时候加上iptables-mod-filter

端口过滤不太好，可能会导致流量泄漏。

**Comment by lifetyper** [comment]
把tracker的IP加入白名单就行了
