### ISSUE TITLE
k2p的无线驱动是哪一个

### ISSUE THREAD

**Issue by OpenWeb321** [coolsnowwolf/lede#171]
选了MT76  貌似没用，驱动不了

**Comment by wheretoteardown** [comment]
MT7615单独的一个包，没有包含在这套代码里面，用它还要对内核进行修改

**Comment by zhaibin18** [comment]
@wheretoteardown 求细节，请问哪里有单独MT7615的包？

**Comment by SeanLared** [comment]
同问啊，k2p的无线没有。。。

**Comment by tofuliang** [comment]
又找到这个
https://github.com/Nossiac/mtk-openwrt-feeds

**Comment by tinnlux** [comment]
@tofuliang 大佬！求教详细教程。。

**Comment by tofuliang** [comment]
@tinnlux 不是大佬,我只是找到,我也不会用...
