### ISSUE TITLE
$$R PLUS 建议！

### ISSUE THREAD

**Issue by admi-229133** [coolsnowwolf/lede#1713]
希望$$R PLUS的V2R能加入vmess链接导入！

**Comment by shikkoku** [comment]
看上去新版本已经支持，请git pull后尝试编译。https://github.com/coolsnowwolf/lede/commit/a99a8179b4bcc888d886ba6b9ee7bce65c96ea9c

**Comment by admi-229133** [comment]
> 看起来新版本已经支持，请git pull后[尝试](https://github.com/coolsnowwolf/lede/commit/a99a8179b4bcc888d886ba6b9ee7bce65c96ea9c)编译[。a99a817](https://github.com/coolsnowwolf/lede/commit/a99a8179b4bcc888d886ba6b9ee7bce65c96ea9c)

是的已经编译使用了 非常好用 大佬还是有非常认真看建议的
