### ISSUE TITLE
我针对luci-app-ssr-plus修改client-config.lua文件339行 true 改为 false，源码中有375行。

### ISSUE THREAD

**Issue by ExtremeOrange** [coolsnowwolf/lede#1717]
我针对luci-app-ssr-plus修改client-config.lua文件339行 true 改为 false，源码中有375行。
使用kcptun-linux-arm-20190109.tar.gz中的client_linux_arm5改名为ssr-kcptun放到K3相应路径中。

_Originally posted by @SouHong in https://github.com/coolsnowwolf/lede/issues/1074#issuecomment-468681179_

**Comment by SouHong** [comment]
现在不改源码的情况下使用kcptun-linux-arm-20190109.tar.gz中的client_linux_arm5改名为kcptun-client放到K3相应路径中 /usr/bin/kcptun-client，今天试也下可以运行。
现在源码的位置是369行。我没有改使用/usr/bin/kcptun-client -r x.x.x.x:4000 -l :16000 --nocomp是可以看到运行中。
