### ISSUE TITLE
webdav（go）不能运行，请求给个makefile

### ISSUE THREAD

**Issue by slitilanber** [coolsnowwolf/lede#1720]
https://github.com/hacdias/webdav.git的weddav server 很方便使用但release 不能在musl编译的系统OpenWrt/alpinelinux上直接使用。猜测是需要glibc的支持（alpinelinux上装上glibc可以正常运行）。请求给个glibc 软件包的makefile 或这个webdav的musl编译makefile。

**Comment by ope087** [comment]
go的程序你可以自己编译带运行库的就好

**Comment by slitilanber** [comment]
搞定，多谢
