### ISSUE TITLE
wrt3200acm 无法切换分区

### ISSUE THREAD

**Issue by 4860575** [coolsnowwolf/lede#1728]
以前可以通过命令或页面切换分区。现在不可以了。并有如下错误提示
root@Gavin:~# fw_printenv boot_part
Cannot parse config file '/etc/fw_env.config': No such file or directory

**Comment by 1312564541** [comment]
我前面也遇到这个问题，L大在2019年10月19日更新了代码，刚刚用上了，分区切换已经恢复正常，我设备是1900ac v1，但出现新的问题，就是没有了无线。

**Comment by 4860575** [comment]
上传日志看看。我还没有编译
