### ISSUE TITLE
有人知道为什么最新编译出来的ssr-plus状态页面会错乱吗？该如何修复？

### ISSUE THREAD

**Issue by ziyangdaoren** [coolsnowwolf/lede#1732]
![批注 2019-10-11 133401](https://user-images.githubusercontent.com/29200223/66626736-eb7b8380-ec2b-11e9-8cb8-962f21ba2c0c.png)

**Comment by admi-229133** [comment]
换个主题就好了  就是那么容易修复

**Comment by rookietribe** [comment]
找到 css 文件，自己改下样式就好了

**Comment by tinnlux** [comment]
我想知道为什么ssr连接速度这么慢，cpu占用很低，同一个节点在电脑上的软件就100m/s，路由器只有9m/s，关键是占用率十分的低

**Comment by ziyangdaoren** [comment]
好吧确实是这个主题的锅，换了主题就好了

**Comment by ope087** [comment]
界面出问题的时候首先换回默认主题,可以省很多问题
