### ISSUE TITLE
nlbwmon 占用单核心满载

### ISSUE THREAD

**Issue by rufengsuixing** [coolsnowwolf/lede#1735]
![图片](https://user-images.githubusercontent.com/22387141/66655957-9c574200-ec6f-11e9-944c-cd45421a0e57.png)

**Comment by outemancut** [comment]
PKG_SOURCE_DATE:=2019-06-13
PKG_SOURCE_VERSION:=e921ca0af9957d3cb05797acfb8bde4d7d2278e5
PKG_MIRROR_HASH:=1f6ed5086e978beeba4c22c255b4ed893d598119c3f2c03061501464910ea421
更新这个版本后就正常了
