### ISSUE TITLE
不能输出路由器ai-br100 的固件 

### ISSUE THREAD

**Issue by hiliuyj** [coolsnowwolf/lede#1737]
如题: 不能输出路由器ai-br100 的固件
可以在 make menuconfig 选 7620 / ai-br100, 但make后没有输出相应固件, 以前是可以输出的.

**Comment by outemancut** [comment]
自己选的插件过多 ，固件无法生成！

**Comment by hiliuyj** [comment]
谢谢， 查报错了.
8M的flash , 只是在缺省的选项里，里面增选 ssr + ， 就不行了.
