### ISSUE TITLE
无法增加服务器节点

### ISSUE THREAD

**Issue by Einic** [coolsnowwolf/lede#1745]
http://192.168.1.1/cgi-bin/luci/admin/services/shadowsocksr/servers/cfg064a8f
![image](https://user-images.githubusercontent.com/50362911/66731010-92a82700-ee87-11e9-8e15-3069253c7054.png)

**Comment by coolsnowwolf** [comment]
你用的所谓移植版吧？

**Comment by Einic** [comment]
> 你用的所谓移植版吧？
问题已经排查，少了ipkg依赖模块；但目前出现服务不断自动重启；资源监控正常
