### ISSUE TITLE
关于ssr-local进程启动的socks5代理一些疑问

### ISSUE THREAD

**Issue by chrisqin** [coolsnowwolf/lede#1748]
L大你好。
我现在的需求场景是只需要使用SSR-PLUS内的socks5代理，开启代理后客户端可以正常使用SOCKS5代理进行连接，但防火墙做了允许公网访问。
因为SS-PLUS内置SOCKS5代理不能设置用户密码所以安全性得不到保障，请问有什么办法可以加入SOCKS5的认证么？

**Comment by coolsnowwolf** [comment]
用 Tiniproxy 做这个的前端
