### ISSUE TITLE
procd-ujail导致开机CPU占用100%

### ISSUE THREAD

**Issue by slitilanber** [coolsnowwolf/lede#1751]
R9.10.10，N3150 CPU开机占用100%，几十秒后自动重启。pkill -9 ujail后恢复正常。 在其他机器上，没问题。

**Comment by coolsnowwolf** [comment]
你被人植入木马了

**Comment by slitilanber** [comment]
不至于中木马吧，把同一写好的U盘放到笔记本电脑上测试没问题。之前编译的版本，没加procd-ujail，都没这问题。这次鬼使神差地编译进去了，就出现问题。可能是我的主板问题吧。机器是小众2盘NAS，有双网口，拿来做软路由了
