### ISSUE TITLE
In a X86 router in which main ssd changed to sdb, upgrade from web failed to detect the real main ssd.

### ISSUE THREAD

**Issue by wolfgangsk07** [coolsnowwolf/lede#1754]
In my X86 router( j1900), I have a 32G ssd and a 1T hhd, and I have installed my openwrt to 32G ssd. However, don't know why, when I wanted to upgrade openwrt from luci, the luci is always going to istall to my 1T hhd. 

My 32G ssd was assigned sdb NOT sda, maybe this is the cause?

Could we use UUID when upgrade in luci?

**Comment by hcym** [comment]
熟悉linux的话用一个live系统盘启动，然后把img镜像dd到内置盘就行，保险起见拔掉所有其它硬盘，我的j1900就是这样，非常方便，win系统可能要用什么pe系统盘，道理一样，看你顺手

**Comment by ope087** [comment]
It doesn't matter,the info displayed on webpage is wrong,you can proceed.
But it's a really bug.

**Comment by coolsnowwolf** [comment]
显示问题而已，请忽略即可

**Comment by wolfgangsk07** [comment]
Thanks to all. I will try it next time.
