### ISSUE TITLE
OpenWRT下的Docker发布的端口外网访问问题

### ISSUE THREAD

**Issue by evilchris** [coolsnowwolf/lede#1756]
在OpenWRT下部署的Docker
发布的端口
在外网可以直接访问
哪怕防火墙没开端口

非Docker不受影响

**Comment by evilchris** [comment]
原来这样...可以了
编辑/etc/init.d/dockerd
在/usr/bin/dockerd后面加上 --iptables=false
然后重启docker就好了

**Comment by coolsnowwolf** [comment]
docker官方没有要fix的意思，而这个issue已经存在了快三年了......

**Comment by coolsnowwolf** [comment]
已增加选项解决
