### ISSUE TITLE
4.14.148/149,更新v2ray订阅链接问题

### ISSUE THREAD

**Issue by tengyuankoo** [coolsnowwolf/lede#1758]
服务器更新订阅全部空白，进不去客户端和高级设置选项卡
![photo_2019-10-16_02-36-58](https://user-images.githubusercontent.com/56631063/66905942-5ae0e100-f039-11e9-8d1e-9b347830df1f.jpg)

**Comment by tengyuankoo** [comment]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/admin/services/shadowsocksr'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocksr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:18: bad argument #1 to 'upper' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by coolsnowwolf** [comment]
不要保留配置升级
