### ISSUE TITLE
【需求】店里经常来人连wifi，SSR+如何就让自己的几个设备可以科学上网，其它人连的话不用每次都在访问控制设置（不走代理的局域网LAN IP）

### ISSUE THREAD

**Issue by willaytoun** [coolsnowwolf/lede#1765]
店里是软路由接AP。因为经常有顾客连wifi，所以就想固定几个IP是走代理的，剩下的设备每次连接wifi后默认是不走代理的。这个功能应该是经常有新设备连或者设备很多 就有几个走代理的话会很有用。

**Comment by coolsnowwolf** [comment]
用子网掩码，黑白名单IP 即可

**Comment by willaytoun** [comment]
感谢l大回复  这个具体要怎么操作呢，我还有点不明白，我的网络知识基本上都是用openwrt之后哪里不会了网上找教程学，这个网上有没有教程或者扫盲贴。
  我的设想是 lan控制访问有两个模式，一个是所有设备默认都能连，然后黑名单IP不能连；另一个模式是所有设备默认不能连，然后白名单IP可以连，这样比较傻瓜话(适合我 哈哈)
