### ISSUE TITLE
SS-obfs类型订阅失败

### ISSUE THREAD

**Issue by lyafancn** [coolsnowwolf/lede#1768]
![1](https://user-images.githubusercontent.com/53136737/66977535-ec536000-f0d8-11e9-927d-a42d9fdbd98c.png)

**Comment by lyafancn** [comment]
![2](https://user-images.githubusercontent.com/53136737/66977592-2290df80-f0d9-11e9-8871-a54a3916593e.png)

**Comment by lyafancn** [comment]
用的群里这个固件

**Comment by lyafancn** [comment]
![3](https://user-images.githubusercontent.com/53136737/66977695-84514980-f0d9-11e9-9290-6d1a6bc40eda.png)

**Comment by coolsnowwolf** [comment]
不支持 ss 订阅

**Comment by adamw92** [comment]
ssr+本身不支持ss的混淆，订阅为什么要支持…
