### ISSUE TITLE
ssr plus能不能添加trojan支持？

### ISSUE THREAD

**Issue by lifetyper** [coolsnowwolf/lede#1770]
https://github.com/trojan-gfw/trojan

https://github.com/trojan-gfw/openwrt-trojan

这个项目现在慢慢的也有不少人在用了，在抗封锁上还是很有意思的。

**Comment by coolsnowwolf** [comment]
先观望，要加入其实很简单，XXR Plus 架构化

**Comment by 0x5826** [comment]
他的抗封锁其实就是利用https封装流量，跟V2的nginx+tls+ws那种方式过墙是类似的

**Comment by hcym** [comment]
没什么必要，心理作用，这两天我也没用aes，就是普通c20，也没事，前面折腾aes512还有tls，ws，速度慢了不说，死人节一样疯，有一个根本没用的节点也被疯

**Comment by hcym** [comment]
哦，这次最严重的时候，我的节点除了ipv6基本挂了。用的瓦工机场，就是标准ss，没有任何混淆，换了两次ip，非常稳定

**Comment by sirfromprc** [comment]
希望添加上吧，多一种选择

**Comment by yunjie-li** [comment]
+1

**Comment by gbmeco** [comment]
+1 希望还是加上吧。

**Comment by f3404923** [comment]
+1

**Comment by wentijianihao** [comment]
+1

**Comment by KevinMX** [comment]
观望中，不知trojan在没有AES加速的设备上速度如何？

**Comment by sharkskin** [comment]
希望在ssr中能增加trojan协议，trojan速度比v2ray更快，而且部署简单。ss和ssr很容易被阻断，一会通一会挂的，受不了。trojan就很稳定

**Comment by EnnawYang** [comment]
> 希望在ssr中能增加trojan协议，trojan速度比v2ray更快，而且部署简单。ss和ssr很容易被阻断，一会通一会挂的，受不了。trojan就很稳定

？

**Comment by bsharkl** [comment]
目前我的三台服务器被封，还是希望增加trojan协议

**Comment by sail456852** [comment]
看来trojan大法好

**Comment by waynon** [comment]
这个issue最后怎么样了？

**Comment by waynon** [comment]
> 这个issue最后怎么样了？

原来已经fix了呀
