### ISSUE TITLE
smartdns部分替换dnsmasq的脚本

### ISSUE THREAD

**Issue by rufengsuixing** [coolsnowwolf/lede#1771]
闭源软件pr是不可能的了，
ss需要调节dns解析方式为5335的dns服务
需要修改dns转发为127.0.0.1:5335，并且忽略解析文件
当然smartdns的端口要为5335，并且将解析国外dns的DNS服务器所属组标记waiguo防止dns泄露

#!/bin/sh
sed -i '/#programaddconfig/,$d' /etc/smartdns/custom.conf
echo "#programaddconfig" >> /etc/smartdns/custom.conf
for file in `ls -d /tmp/dnsmasq.d/*`
do
	sed -i 's/^conf-dir=/#conf-dir=/g' $file
	awk -F = '/#conf-dir/{print $2}' $file >> /tmp/sddc
	#可以添加address或者ipset support
done
[ ! -d /tmp/smartdns ]&& mkdir /tmp/smartdns
rm -f /tmp/smartdns/*
let count=0
while read line
do
    for file in `ls $line`
    do
		let count=count+1;
		#awk -F '/' '$1==ipset={gsub(/ipset=/,"ipset ")}'
		sed 's/ipset=/ipset /g;s/address=/address /g;s/server=/server /g;s/0\.0\.0\.0/#/g;s/127\.0\.0\.1#5335/waiguo/g;s/127\.0\.0\.1/#/g;' $line/$file>>/tmp/smartdns/$count$file
        echo conf-file /tmp/smartdns/$count$file >> /etc/smartdns/custom.conf
    done
done < /tmp/sddc
rm -f /tmp/sddc
/etc/init.d/smartdns restart

最后/etc/init.d/dnsmasq restart切换生效

**Comment by coolsnowwolf** [comment]
smartdns 下，App Store，一些P2SP下载什么的只能获取到一个ip，不能完成多 CDN 多并发下载，导致下载速度反而更慢

**Comment by rufengsuixing** [comment]
dnsmasq并没有对dns返回的ip进行排序的操作，导致可能访问到cdn的国外ip，在我这里的表现就是搜狗手机版有概率跳到国外甚至要求输入图片验证码进行验证是否机器人
