### ISSUE TITLE
希望适配8M-16M Flash精简内核

### ISSUE THREAD

**Issue by z826540272** [coolsnowwolf/lede#1778]
默认编译的MT7621固件打开了很多内核功能,
这些内核功能平时用不到但是增大了内核体积
导致剩余的空间比较紧张.
编译V2+SSR+unblockMusic后基本无剩余空间.
而且在menu config界面也无法关闭这些内核集成选项,这些选项保持 - *- 状态,无法取消勾选.
希望添加在menu中添加一个选项,比如 精简内核的选项,在不影响基本功能的情况下尽量砍掉用不到的内核功能. 或者解锁那些无法取消勾选的 内核编译选项.

**Comment by outemancut** [comment]
还是算了吧 这种路由想同时运行V2R跟node.js?这两个一起运行 运存都得60M起步了 还有其它软件不需要占用了？
