### ISSUE TITLE
建议V2ray 更新订阅的时候不要更改自动更改加密方式为AUTO

### ISSUE THREAD

**Issue by z826540272** [coolsnowwolf/lede#1779]
V2ray支持客户端指定加密方式,在数量众多的低配置路由器上,None加密方式的速度比Auto快得多,网速瓶颈不在加密方式上.
目前修改了加密方式后每次更新订阅的时候又会重置为Auto方式,导致速率峰值在我的MT7621设备上大概40mbps
希望更新订阅不会影响自己修改的加密方式

**Comment by outemancut** [comment]
Auto自动加密方式不行？要手动加密？反正我这没什么影响 你可以用完整版的V2R 精简版的或许火力不够大

**Comment by rufengsuixing** [comment]
我记得auto就是在低配置上直接用chacha20兼顾速度与安全

**Comment by coolsnowwolf** [comment]
修改了，以订阅为准吧，如果要调整，自己修改 /usr/share/shadowsocksr/subscribe.sh auto 为 none。

官方推荐 auto

![image](https://user-images.githubusercontent.com/31687149/67148028-474da880-f2cd-11e9-9900-c408ae4174f8.png)
