### ISSUE TITLE
make menuconfig没有aliyunddns，但.config里面默认为Y

### ISSUE THREAD

**Issue by dunkeng** [coolsnowwolf/lede#1785]
make[3] -C package/lean/ddns-scripts_aliyun compile

grep aliyun .config
CONFIG_DEFAULT_ddns-scripts_aliyun=y
CONFIG_PACKAGE_ddns-scripts_aliyun=y

**Comment by coolsnowwolf** [comment]
内置了 支持，在原生界面中
