### ISSUE TITLE
树莓派4B 使用最新commit編譯依舊無Wifi

### ISSUE THREAD

**Issue by bob771025** [coolsnowwolf/lede#1786]
![擷取](https://user-images.githubusercontent.com/4236843/67109172-8662f780-f202-11e9-93bb-cea207381503.PNG)
![擷取2](https://user-images.githubusercontent.com/4236843/67109175-895de800-f202-11e9-933e-8194a787b6c9.PNG)

目前已使用最新commit編譯 依舊無Wifi
謝謝

**Comment by coolsnowwolf** [comment]
mac80211 的版本问题，用新版的
