### ISSUE TITLE
mwlwifi: probe of 0000:02:00.0 failed with error -5 [Linksys WRT1900AC v1]

### ISSUE THREAD

**Issue by 1312564541** [coolsnowwolf/lede#1793]
老大你好，今天git pull后编译了个固件并刷进路由器，但发现没有了无线信号以及管理页面里也没有无线的菜单，设备基本信息如下：
主机名	OpenWrt
主机型号	Linksys WRT1900AC
架构	ARMv7 Processor rev 2 (v7l) x 2
固件版本	OpenWrt R9.10.10 / LuCI Master (git-19.287.23581-bba07aa)
内核版本	4.19.79

查看系统日志，有以下错误：
mwlwifi: probe of 0000:02:00.0 failed with error -5
[mwlwifi error日志.txt](https://github.com/coolsnowwolf/lede/files/3746296/mwlwifi.error.txt)

劳烦L大了

**Comment by coolsnowwolf** [comment]
已解决
