### ISSUE TITLE
歌华链L1 10.19日代码编译固件无法启动

### ISSUE THREAD

**Issue by marcosteam** [coolsnowwolf/lede#1795]
生成的sysupgrade文件通过breed刷入后无法开机。也不知道怎么获取日志。
已确认通过科学上网下载了所有源文件。

**Comment by ubuntu1977vip** [comment]
新3同现象

**Comment by coolsnowwolf** [comment]
重新拉代码测试下

**Comment by hcym** [comment]
哦，今天新3用的官方1907加ssr，躲过一劫

**Comment by 1715173329** [comment]
> 重新拉代码测试下

其实直接给mt76升下级就好了。。没必要把mac80211退回去。。

**Comment by marcosteam** [comment]
> 重新拉代码测试下

已修复
