### ISSUE TITLE
linksys 的 re6500 默认配置没有生成 squashfs-sysupgrade.bin

### ISSUE THREAD

**Issue by bear-shen** [coolsnowwolf/lede#1797]
Op : [https://openwrt.org/toh/linksys/re6500](url)

机器环境是vmware的虚拟机，ubuntu x64 14.04 ，8g+6c
同一个环境下小米pro3和ubnt的erx都可以编译完成并正常取到 squashfs 的包（三者都是7621系列，暂时没试过别的）

在 target images 里选择了 squashfs （默认就选的），但是生成的包只有 
```
config.seed
openwrt-imagebuilder-ramips-mt7621.Linux-x86_64.tar.xz
openwrt-ramips-mt7621-device-re6500.manifest
openwrt-ramips-mt7621-re6500-initramfs-kernel.bin
sha256sums
```
只在 network 里选择了 6in4 ，没有碰其他配置
清除配置项重新编译也没有用……
不知道有木有人遇到一样的问题？

话说 re6500 这个 flash 我看默认只有 8M ，官方的包大小倒是合适，这个生成出来是否是要改的？

**Comment by outemancut** [comment]
取消不必要的插件就会编译出来了 编译出来的固件比你闪存都大

**Comment by bear-shen** [comment]
> 取消不必要的插件就会编译出来了 编译出来的固件比你闪存都大

😅啥都不加的跑一遍过了。。。白板一块也吃掉7.8M，这洋垃圾的规格果然还是不那么顶用。。。
谢兄台。。。
