### ISSUE TITLE
Raspberry Pi Model B Rev 2刷完10月17号的LEDE只能使用全局翻墙

### ISSUE THREAD

**Issue by bull1012** [coolsnowwolf/lede#1798]
Raspberry Pi Model B Rev 2刷完10月17号的LEDE只能使用全局翻墙，无法分流。gfwlist和绕过局域网和大陆无法使用。

**Comment by blackjelly** [comment]
用最新版本试试。

**Comment by bull1012** [comment]
刚刷完v2ray 无法运行，刷完v2ray内核后才能使用，而且也是只能用全局翻墙，其他模式不起作用呢
