### ISSUE TITLE
能否加个gnu镜像,每次下载都好慢

### ISSUE THREAD

**Issue by daofeng2015** [coolsnowwolf/lede#18]
参考蝈蝈的  [https://github.com/981213/lede_src/commit/2344fca488c0d240d59e19b0d407175608fe0bc7#diff-37328c94ce7b51e93bffc95f34083ae7](url)

**Comment by tomerilery** [comment]
全局爱国出墙，速度就上去了，编译不出墙，成功率接近零

**Comment by daofeng2015** [comment]
然而我可以不出墙编译成功，，，

**Comment by coolsnowwolf** [comment]
加了
