### ISSUE TITLE
编译acrh17的固件，编译错误

### ISSUE THREAD

**Issue by YuchengWang** [coolsnowwolf/lede#1802]
错误详情如下：
``make[4]: Entering directory '/home/ycwang/work/ycwang/desktop/router/lede/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.4.0_musl_eabi/binutils-2.31.1'
make[5]: Entering directory '/home/ycwang/work/ycwang/desktop/router/lede/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.4.0_musl_eabi/binutils-2.31.1'
make[6]: Entering directory '/home/ycwang/work/ycwang/desktop/router/lede/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.4.0_musl_eabi/binutils-2.31.1/libiberty'
if [ x"" != x ]; then \
  gcc -c -DHAVE_CONFIG_H   -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE  ./fibheap.c -o pic/fibheap.o; \
else true; fi
if [ x"" != x ]; then \
  gcc -c -DHAVE_CONFIG_H   -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE   ./fibheap.c -o noasan/fibheap.o; \
else true; fi
gcc -c -DHAVE_CONFIG_H   -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE ./fibheap.c -o fibheap.o
./fibheap.c: In function 'fibheap_replace_key_data':
./fibheap.c:38:24: error: 'LONG_MIN' undeclared (first use in this function)
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
./fibheap.c:220:30: note: in expansion of macro 'FIBHEAPKEY_MIN'
   if (okey == key && okey != FIBHEAPKEY_MIN)
                              ^~~~~~~~~~~~~~
./fibheap.c:38:24: note: each undeclared identifier is reported only once for each function it appears in
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
./fibheap.c:220:30: note: in expansion of macro 'FIBHEAPKEY_MIN'
   if (okey == key && okey != FIBHEAPKEY_MIN)
                              ^~~~~~~~~~~~~~
./fibheap.c: In function 'fibheap_delete_node':
./fibheap.c:38:24: error: 'LONG_MIN' undeclared (first use in this function)
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
./fibheap.c:261:36: note: in expansion of macro 'FIBHEAPKEY_MIN'
   fibheap_replace_key (heap, node, FIBHEAPKEY_MIN);
                                    ^~~~~~~~~~~~~~
Makefile:752: recipe for target 'fibheap.o' failed
make[6]: *** [fibheap.o] Error 1
make[6]: Leaving directory '/home/ycwang/work/ycwang/desktop/router/lede/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.4.0_musl_eabi/binutils-2.31.1/libiberty'
Makefile:8014: recipe for target 'all-libiberty' failed
make[5]: *** [all-libiberty] Error 2
''

应该是gcc的工具链编译时，找不到linux kernel headers的头文件造成的。

**Comment by coolsnowwolf** [comment]
用 Ubuntu 14.04 编译即可
