### ISSUE TITLE
IPSec VPN 服务器功能开启且设备连接后无法正常解析域名

### ISSUE THREAD

**Issue by tinnlux** [coolsnowwolf/lede#1804]
大佬，IPSec VPN 服务器功能开启且设备连接后无法正常解析域名，直接访问ip地址则无问题。求修复。
路由器是newifi3，最新源码，开fullnat，其余Turbo ACC 功能全部关闭。

**Comment by coolsnowwolf** [comment]
升级到 iOS 13 即可

**Comment by tinnlux** [comment]
但是Android手机也不行啊。。Android版本Android P
