### ISSUE TITLE
使用最新源码编译后树莓派 4B 无法启动

### ISSUE THREAD

**Issue by SuLingGG** [coolsnowwolf/lede#1810]
拉取最新源码(9a20d3e7e235d3c4c357925d9c88ddb75a37e762)后尝试编译:

发现之前#1558 的 Bug 已解决，但在使用 bcm2711 平台的配置编译树莓派 4B 的 OpenWrt 时，上电后树莓派无法启动，2711 的固件在 4B 上表现为绿灯只闪烁一两秒后再无闪烁；

使用 bcm 2709 平台的配置编译 32 位树莓派固件时，同一个镜像在 3B 上可以正常启动/正常使用，但在 4B 上启动不了，2709 的固件在 4B 上表现为绿灯正常闪动，但无 WiFi 热点，使用网线将树莓派连接到电脑时，无法获取到 IP 地址。

望修复~

**Comment by coolsnowwolf** [comment]
已修复
