### ISSUE TITLE
SSR+能否添加混淆设置

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#1815]
在SSR-Plus里SS模式里没有混淆参数obfs-tls、obfs-http、混淆主机名等设置
现在有不少机场将SS节点都添加上混淆参数和主机名才能使用，能否能将SS节点设置完善一下，有不少人迫着使用ssr+魔改，希望能增加相关功能。

**Comment by liunice** [comment]
感觉这个功能很需要，支持~

**Comment by adamw92** [comment]
simple-obfs已经转向v2pay-plugin了…
不如请求增加v2ray-plugin的支持。

**Comment by dengchan0416** [comment]
SS还有很多机场使用obfs-tls，obfs-http

**Comment by outemancut** [comment]
一般都是SSR跟V2R 谁还用SS

**Comment by Shifuya** [comment]
同希望支持这个功能，

**Comment by snowleopardw** [comment]
同希望支持这个功能

**Comment by jh0072110** [comment]
> 在SSR-Plus里SS模式里没有混淆参数obfs-tls、obfs-http、混淆主机名等设置
> 现在有不少机场将SS节点都添加上混淆参数和主机名才能使用，能否能将SS节点设置完善一下，有不少人迫着使用ssr+魔改，希望能增加相关功能。

请问魔改可以从哪里下？有木有传送门

**Comment by Karmylr** [comment]
为什了关了？这个插件死活不肯升级吗？还是去用passwall吧
