### ISSUE TITLE
多拨的掉线检测和动态DNS错误

### ISSUE THREAD

**Issue by gddfczl** [coolsnowwolf/lede#1821]
使用20191020代码编译，路由器斐讯K3。1、使用多线多拨中的单线多拨功能，设置2个WAN口，勾选掉线检测，最低在线接口数量2，拨号只拨上1个WAN口，不会重播，掉线检测不起作用。重启后故障依旧。2、使用动态DNS，设置好勾选启用，进程ID不启动，必须手动点击，才会出现PID，重启后故障依旧。

**Comment by coolsnowwolf** [comment]
1. 这个功能的 API 在新版本不存在了 2.测试不存在
