### ISSUE TITLE
 ssr+ User-Agent 为 Mozilla 导致的 rixCloud API 订阅问题

### ISSUE THREAD

**Issue by yfu1900** [coolsnowwolf/lede#1822]
ssr+在订阅rixcloud时返回403错误，经与rixcloud沟通存在这样的问题，具体如下

https://rixcloudkb.io/kb/openwrt-coolsnowwolf-troubleshooting/

**Comment by ope087** [comment]
2018年的版本,楼主你用的是哪年的的版本,现在用的是这个"User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"agent啊

**Comment by ope087** [comment]
2018年的commit,楼主你用的是哪个版本,现在用的是这个"User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"agent啊
