### ISSUE TITLE
ssr+的UA为Mozilla导致订阅URL被拦截

### ISSUE THREAD

**Issue by yvesyc** [coolsnowwolf/lede#1828]
你好，
由于其使用的 User-Agent 为 Mozilla，此 UA 不符合任何正常浏览器 / 网络工具的 UA，并被认为存在风险而导致 rixCloud WAF 拦截了此请求。特来请求更改请求使用的 UA，即使是 curl 和 wget 等工具的默认 UA，这样就不会被拦截。

详细位置：
此问题发生于此 Repo 中该文件的第 63 行：
https://github.com/coolsnowwolf/lede/blob/734df71303969e171fd12a2efa2779f29c82b3cf/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.sh#L63

非常感谢~

**Comment by coolsnowwolf** [comment]
你的版本太老了，认真看看新代码

**Comment by yvesyc** [comment]
> 你的版本太老了，认真看看新代码

收到，谢谢
