### ISSUE TITLE
v2ray服务器的socks5不需要用户名密码一样使用

### ISSUE THREAD

**Issue by aiden-5154** [coolsnowwolf/lede#1837]

**Comment by aiden-5154** [comment]
{
   "outbound": {
     "protocol": "freedom"
   },
   "log": {
     "loglevel": "warning"
   },
   "outboundDetour": [
     {
       "protocol": "blackhole",
       "tag": "blocked"
     }
   ],
   "inbound": {
     "1": false,
     "2": {
       "settings": {
         "accounts": [
           {
             "pass": "password",
             "user": "123"
           }
         ],
         "auth": "password"
       }
     },
     "port": 10086,
     "protocol": "socks",
     "streamSettings": {
       "security": "none"
     }
   }
 }

**Comment by coolsnowwolf** [comment]
已解决
