### ISSUE TITLE
X86_64重启的时候PPPOE拨不上号，再重启一次就能拨上号了。

### ISSUE THREAD

**Issue by ldy8182** [coolsnowwolf/lede#1839]
OpenWrt R9.10.10 / LuCI Master (git-19.293.50056-8ba0208)
内核:4.9.196
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/3755431/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/3755432/default.txt)
不知道还需要提交什么信息，需要什么我再补充，L大辛苦了。

**Comment by ldy8182** [comment]
WAN口的网卡是USB3.0千兆网卡，贝尔金Belkin USB 3.0 千M 1000M USB3.0网卡AX88179芯片 USB 3.0 TO Gigabit Ethernet Adapter B2B048

**Comment by outemancut** [comment]
切换4.14内核编译试试

**Comment by ziyangdaoren** [comment]
4.19.79内核版本的也有这个问题，设置了自动重启，每次重启后都拨不上号，需要手动点一下wan口连接才拨上。

**Comment by ldy8182** [comment]
4.19.81内核下重启能拨上号了
