### ISSUE TITLE
R7800 有无线信号 密码也正确却连不上,不设密码处于获取IP地址中。

### ISSUE THREAD

**Issue by anglabace** [coolsnowwolf/lede#184]
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/1474537/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/1474538/default.txt)

**Comment by anglabace** [comment]
R7800 有无线信号 密码也正确却连不上,不设密码处于获取IP地址中。有线也会出现这个问题
设定成固定IP 是可以正常访问。或者DHCP里做绑定也会正常下发IP访问。

**Comment by ClayMoreBoy** [comment]
R7800 不能刷这个固件 只能刷17.01那个

**Comment by anglabace** [comment]
@ClayMoreBoy 
R7800 可以刷这个昨夜用默认的参数编译的可以正常使用。
但是貌似添加 6rd 6in4 6to4 
dnsmasq-full 中dhcpv6 support DNSSEC support
odhcp6c 和 odhcpd
出现的问题

**Comment by cuijin1985** [comment]
2G和5G不能一起开，一段时间后2.4G的wifi会掉线，5G没问题。

**Comment by cuijin1985** [comment]
出现了同样的问题了，密码正确连不上。
