### ISSUE TITLE
ssr server 能否添加监听iPv6地址的选项

### ISSUE THREAD

**Issue by jsnjycwyz** [coolsnowwolf/lede#1842]
看了下ssr server的配置文件在tmp里，每次启动都会创建，就没办法自己把 "server_ipv6": "::" 选项加进去了，可不可以在luci界面添加一个iPv6的选项，或者默认监听本地v6，谢谢大雕

**Comment by jsnjycwyz** [comment]
改了init.d里的启动文件替换成了"server":["[::0]", "0.0.0.0"],实现了同时监听，希望指点下如何在编译的时候就修改这个文件

**Comment by outemancut** [comment]
lede/package/lean/luci-app-ssr-plus/root/etc/

**Comment by jsnjycwyz** [comment]
非常感谢！

> lede/package/lean/luci-app-ssr-plus/root/etc/
