### ISSUE TITLE
如何修改配置文件使编译后的网卡、lan ip适合自己使用

### ISSUE THREAD

**Issue by Suxwx** [coolsnowwolf/lede#1845]
感谢源码，用google云ubuntu成功编译。

编译后下载奇慢，后来用gdrive上传再下载速度就没问题。

有个问题想请教下，查了很多资料，但是都查不到。

如何修改配置文件使编译后的网卡、lan ip以便适合自己使用，这样省去了第一次进入系统去修改的问题。（既然是自己编译的，就为了自己使用）。

感谢！

**Comment by outemancut** [comment]
目录搜config_generate这个文件到99行修改

**Comment by Zack0617** [comment]
lean文件夹下有个default settings，打开那个文件，把你的ip 网关，DNS设置在里面，然后编译，刷机后就可以直接使用了，不用再设置

**Comment by coolsnowwolf** [comment]
files 大法
