### ISSUE TITLE
GDOCK compile error

### ISSUE THREAD

**Issue by inlyt** [coolsnowwolf/lede#1848]
[GDOCK log.txt](https://github.com/coolsnowwolf/lede/files/3761023/GDOCK.log.txt)

**Comment by coolsnowwolf** [comment]
make clean ，同时体积不要超过 15MB

**Comment by AmadeusGhost** [comment]
一样编译失败

**Comment by AmadeusGhost** [comment]
> make clean ，同时体积不要超过 15MB

竞斗云的dts好像有问题

**Comment by inlyt** [comment]
> > make clean，同时体积不要超过15MB
> 
> 竞斗云的dts好像有问题

是的是有问题的。

**Comment by Aes64X** [comment]
> 
> 
> [GDOCK log.txt](https://github.com/coolsnowwolf/lede/files/3761023/GDOCK.log.txt)

apt-get install device-tree-compiler

**Comment by inlyt** [comment]
> > [GDOCK log.txt](https://github.com/coolsnowwolf/lede/files/3761023/GDOCK.log.txt)
> 
> apt-get install device-tree-compiler

Thank you
