### ISSUE TITLE
网络带宽监视器-备份恢复，无法选择备份文件

### ISSUE THREAD

**Issue by alanleb** [coolsnowwolf/lede#1854]
![Snip20191024_4](https://user-images.githubusercontent.com/4159074/67446662-e8c55900-f643-11e9-82cd-f0f4b217ab96.png)

**Comment by Her0R0cket** [comment]
备份文件后缀时tar.gz,主要识别gz,请检查你的备份文件的后缀

**Comment by alanleb** [comment]
Luci自动生成的备份文件后缀，都是.tar，不是tar.gz
