### ISSUE TITLE
请问能否在SSR plus的LAN口IP访问控制中增加GFWlist模式选项

### ISSUE THREAD

**Issue by lucky-beans** [coolsnowwolf/lede#1858]
之前LAN口IP给下载机用不经过代理模式，但是经常会遇到需要下载地址无法访问或者tracker服务器404这种尴尬情况。我研究了一下control那页附近的代码想自己改进一下，猜想LAN口访问控制里的模式应该和路由器主模式选项类似但是没找到头绪，想请大佬帮忙,先谢谢。

**Comment by outemancut** [comment]
需要代理的端口选择仅常用端口就不会跑P2P流量 不会用看都不会看？

**Comment by lucky-beans** [comment]
下载机并不只有P2P流量，下载时使用的端口有很多，我的描述没有写非常清楚很抱歉
