### ISSUE TITLE
softethervpn编译不过

### ISSUE THREAD

**Issue by P0lari5** [coolsnowwolf/lede#1859]
修改/lede/feeds/packages/net/softethervpn/Makefile
PKG_NAME:=softethervpn
PKG_VERSION:=4.29-9680
PKG_VERREL:=rtm
PKG_VERDATE:=2019.02.28
PKG_RELEASE:=1

PKG_SOURCE:=softether-src-v$(PKG_VERSION)-$(PKG_VERREL).tar.gz
PKG_SOURCE_URL:=http://www.softether-download.com/files/softether/v$(PKG_VERSION)-$(PKG_VERREL)-$(PKG_VERDATE)-tree/Source_Code/
PKG_HASH:=e6035fa7d9aaf59bdb342cd7ab5ecfdff89811a875f62a3230208cdc8a4e26e4

X86的4.25编译不过，改4.29-9680解决，能同步更新下么

**Comment by coolsnowwolf** [comment]
发个 PR
