### ISSUE TITLE
ssr 无法手动更新国内数据库

### ISSUE THREAD

**Issue by hauntek** [coolsnowwolf/lede#1866]
ssr 无法手动更新国内数据库

源码：package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua

第100行：
refresh_cmd="wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest'  2>/dev/null| awk -F\\| '/CN\\|ipv4/ { printf(\"%s/%d\\n\", $4, 32-log($5)/log(2)) }' > /tmp/china_ssr.txt"

**Comment by outemancut** [comment]
![QQ图片20191025094330](https://user-images.githubusercontent.com/53339509/67536991-2ab9d200-f70c-11e9-8a5a-7459fe49d12e.png)
没问题 正常更新！
