### ISSUE TITLE
请求添加mentohust

### ISSUE THREAD

**Issue by Dragon-Lu** [coolsnowwolf/lede#1869]
L大可以考虑将mentohust加入插件么，校园网环境下非常有用，谢谢。
另外，可以对mentohust添加多网口支持么，这样一个寝室只用一台路由器就可以使用所有人的账号了。

**Comment by coolsnowwolf** [comment]
无法调试，也没人维护，删除了

**Comment by Dragon-Lu** [comment]
那L大可否考虑一下minieap？这个支持的认证协议也有好几个，也比较稳定。

**Comment by AmadeusGhost** [comment]
mentohust：https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk
luci：https://github.com/BoringCat/luci-app-mentohust
可以编译的时候自己加进去。

**Comment by Dragon-Lu** [comment]
> mentohust：https://github.com/KyleRicardo/MentoHUST-OpenWrt-ipk
> luci：https://github.com/BoringCat/luci-app-mentohust
> 可以编译的时候自己加进去。

非常感谢，我已经编译过在使用了，我只是想看L大能否将这个插件直接加在仓库里，毕竟有这个需求的人还是有一些的。

**Comment by 1170400506** [comment]
学生党希望集成+1
