### ISSUE TITLE
upnp版本问题

### ISSUE THREAD

**Issue by lesliedu** [coolsnowwolf/lede#1870]
两台Mac需要将5900端口通过upnp对外发布，在Openwrt页面上显示正常，一个是5900，一个是5901；但是两台电脑显示的映射端口都是5900，导致从外网无法访问。

miniupnp更新至新版问题解决

**Comment by dolphinpaopao** [comment]
请问如何升级upnp，更改后编译提示还需要升级101-no-ssl-uuid.patch，请问这个文件需要如何更改才能编译成功，感谢。

**Comment by lesliedu** [comment]
opkg update
opkg install miniupnpd --force-overwrite
