### ISSUE TITLE
新入手华为凌霄４核1GHz WS5200, 请问Ｌ大是否最近考虑加入固件？

### ISSUE THREAD

**Issue by aesirteam** [coolsnowwolf/lede#1872]
CPU 华为HI5651T　4cores 1GHz  (Arm Cortex-A53)
内存: NT5CC64M16GP-DI，DDR3 128MB容量。
闪存: MX30LF1G18AC-TI，128MB NAND FLASH
5G芯片: Hi1151，2x2mimo 867Mbps
PA/LNA: 5G型号LX5589B　2.4G型号SKY85330-11
官方号称４天线４个独立功放，200多元性价比还行！

狂想：
 凌霄也是arm系列，lede是否有可能做固件支持？

谢谢Ｌ大

**Comment by Aes64X** [comment]
> 
> 
> CPU 华为HI5651T　4cores 1GHz (Arm Cortex-A53)
> 内存: NT5CC64M16GP-DI，DDR3 128MB容量。
> 闪存: MX30LF1G18AC-TI，128MB NAND FLASH
> 5G芯片: Hi1151，2x2mimo 867Mbps
> PA/LNA: 5G型号LX5589B　2.4G型号SKY85330-11
> 官方号称４天线４个独立功放，200多元性价比还行！
> 
> 狂想：
> 凌霄也是arm系列，lede是否有可能做固件支持？
> 
> 谢谢Ｌ大

这玩意是闭源的

**Comment by coolsnowwolf** [comment]
... 想太多了
