### ISSUE TITLE
容器无法上网

### ISSUE THREAD

**Issue by evilchris** [coolsnowwolf/lede#1873]
已经make clean重新编译
但是结果是容器依然无法连上外网
但可以被动访问

**Comment by CirnoSalt** [comment]
见本人issues中的解决方案：
[https://github.com/coolsnowwolf/lede/issues/1760](url)
希望能帮到你：）

**Comment by evilchris** [comment]
1. Edit  /etc/sysctl.conf
Add the following

net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1

2. Network > Firewall 
        accept Forward
3. Restart firewall
4. Restart Dockerd
