### ISSUE TITLE
kcptun配置界面有BUG

### ISSUE THREAD

**Issue by muziling** [coolsnowwolf/lede#188]
配置两个kcp server，在kcp luci界面，服务器下拉选择另第二个server， 重启kcp，新的服务器地址不生效，还是使用第一次配置的server。

**Comment by HiGarfield** [comment]
settings.lua末尾加

local apply = luci.http.formvalue("cbi.apply")
if apply then
	os.execute("/etc/init.d/kcptun restart >/dev/null 2>&1 &")
end
