### ISSUE TITLE
k2p编译错误

### ISSUE THREAD

**Issue by remewb** [coolsnowwolf/lede#1882]
OpenWrt Linux-4.14.149' -d /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin.new
Image Name:   MIPS OpenWrt Linux-4.14.149
Created:      Fri Oct 25 17:15:00 2019
Image Type:   MIPS Linux Kernel Image (lzma compressed)
Data Size:    2081687 Bytes = 2032.90 KiB = 1.99 MiB
Load Address: 80001000
Entry Point:  80001000
mv /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin.new /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin
[ -f /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin -a -f /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/root.squashfs ]
dd if=/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/k2p-kernel.bin >> /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin
4065+1 records in
4065+1 records out
2081751 bytes (2.1 MB, 2.0 MiB) copied, 0.00750127 s, 278 MB/s
dd if=/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/root.squashfs >> /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin
31495+1 records in
31495+1 records out
16125492 bytes (16 MB, 15 MiB) copied, 0.0594526 s, 271 MB/s
/home/wang/lede/staging_dir/host/bin/padjffs2 /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin  4 8 16 64 128 256
padding image to 0115e000
padding image to 01160000
padding image to 01180000
echo '{  "supported_devices":["k2p"], "version": { "dist": "OpenWrt", "version": "SNAPSHOT", "revision": "r1592-a27bc590", "board": "ramips" } }' | fwtool -I - /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin
[ ! -s "/home/wang/lede/key-build" -o ! -s "/home/wang/lede/key-build.ucert" -o ! -s "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin" ] || { cp "/home/wang/lede/key-build.ucert" "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin.ucert" ; usign -S -m "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin" -s "/home/wang/lede/key-build" -x "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin.sig" ; ucert -A -c "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin.ucert" -x "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin.sig" ; fwtool -S "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin.ucert" "/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin" ; }
WARNING: Image file /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin is too big
cp /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin /home/wang/lede/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin
cp: cannot stat '/home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin': No such file or directory
Makefile:162: recipe for target '/home/wang/lede/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin' failed
**make[5]: [/home/wang/lede/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin] Error 1 (ignored)**

**Comment by lphgor** [comment]
```WARNING: Image file /home/wang/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/tmp/openwrt-ramips-mt7621-k2p-squashfs-sysupgrade.bin is too big```
选的功能太多了，固件大小超过了
