### ISSUE TITLE
编译集成luci-app-amule报错

### ISSUE THREAD

**Issue by zhi1992** [coolsnowwolf/lede#189]
./autogen.sh: 42: ./autogen.sh: autopoint: not found
grep: po/Makefile.in.in: No such file or directory
autopoint does not honor dataroot variable, patching.
sed: can't read po/Makefile.in.in: No such file or directory
./autogen.sh: 49: ./autogen.sh: cannot create intl/Makefile.in.tmp: Directory nonexistent
sed: can't read po/Makefile.in.in: No such file or directory
Running aclocal -I m4
configure.ac:342: warning: gl_VISIBILITY is m4_require'd but not m4_defun'd
/home/du/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/intl.m4:25: AM_INTL_SUBDIR is expanded from...
/home/du/lede/staging_dir/target-mips_24kc_musl/usr/share/aclocal/gettext.m4:57: AM_GNU_GETTEXT is expanded from...
m4/nls.m4:78: MULE_CHECK_NLS is expanded from...

**Comment by fuqiang03** [comment]
Makefile.in.in这个文件不存在，需要检查源码包，是否有这个文件。
