### ISSUE TITLE
刚拉的源码报错 

### ISSUE THREAD

**Issue by outemancut** [coolsnowwolf/lede#1893]
/root/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.3.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /root/lede/staging_dir/host/lib/libjson-c.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/blockd.dir/build.make:85: recipe for target 'blockd' failed
make[6]: *** [blockd] Error 1
make[6]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/fstools-2019-03-28-ff1ded63'
CMakeFiles/Makefile2:257: recipe for target 'CMakeFiles/blockd.dir/all' failed
make[5]: *** [CMakeFiles/blockd.dir/all] Error 2
make[5]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/fstools-2019-03-28-ff1ded63'
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/fstools-2019-03-28-ff1ded63'
Makefile:135: recipe for target '/root/lede/build_dir/target-mipsel_24kc_musl/fstools-2019-03-28-ff1ded63/.built' failed
make[3]: *** [/root/lede/build_dir/target-mipsel_24kc_musl/fstools-2019-03-28-ff1ded63/.built] Error 2
make[3]: Leaving directory '/root/lede/package/system/fstools'
time: package/system/fstools/compile#1.81#0.57#2.47
package/Makefile:107: recipe for target 'package/system/fstools/compile' failed
make[2]: *** [package/system/fstools/compile] Error 2
make[2]: Leaving directory '/root/lede'
package/Makefile:103: recipe for target '/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/lede'
/root/lede/include/toplevel.mk:216: recipe for target 'world' failed

**Comment by coolsnowwolf** [comment]
fix
