### ISSUE TITLE
wrt1900ac v2  ，install -a的时候出现的。

### ISSUE THREAD

**Issue by lmguy** [coolsnowwolf/lede#19]
WARNING: No feed for package 'libsqlite2' found, maybe it's already part of the                                                                                                              standard packages?
WARNING: No feed for package 'flite' found, maybe it's already part of the stand                                                                                                             ard packages?
WARNING: No feed for package 'libyuv' found, maybe it's already part of the stan                                                                                                             dard packages?
WARNING: No feed for package 'libilbc' found, maybe it's already part of the sta                                                                                                             ndard packages?
WARNING: No feed for package 'libmemcached' found, maybe it's already part of th                                                                                                             e standard packages?
WARNING: No feed for package 'libsilk' found, maybe it's already part of the sta                                                                                                             ndard packages?
WARNING: No feed for package 'libg7221' found, maybe it's already part of the st                                                                                                             andard packages?
WARNING: No feed for package 'freeradius-client' found, maybe it's already part                                                                                                              of the standard packages?
Installing package 'freeswitch-

**Comment by xingsiyue** [comment]
这个可以不用管。
