### ISSUE TITLE
还是一样编译不过去了 

### ISSUE THREAD

**Issue by outemancut** [coolsnowwolf/lede#1908]
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
  CCLD     sntp
/root/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.3.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.3.0/../../../../mipsel-openwrt-linux-musl/bin/ld: cannot find -levent_pthreads
collect2: error: ld returned 1 exit status
Makefile:887: recipe for target 'sntp' failed
make[8]: *** [sntp] Error 1
make[8]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13/sntp'
Makefile:1049: recipe for target 'all-recursive' failed
make[7]: *** [all-recursive] Error 1
make[7]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13/sntp'
Makefile:677: recipe for target 'all' failed
make[6]: *** [all] Error 2
make[6]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13/sntp'
Makefile:666: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13'
Makefile:598: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13'
Makefile:155: recipe for target '/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13/.built' failed
make[3]: *** [/root/lede/build_dir/target-mipsel_24kc_musl/ntp-4.2.8p13/.built] Error 2
make[3]: Leaving directory '/root/lede/feeds/packages/net/ntpd'
time: package/feeds/packages/ntpd/compile#47.09#11.47#60.26
package/Makefile:107: recipe for target 'package/feeds/packages/ntpd/compile' failed
make[2]: *** [package/feeds/packages/ntpd/compile] Error 2
make[2]: Leaving directory '/root/lede'
package/Makefile:103: recipe for target '/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/root/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/root/lede'
/root/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by letmekillthemall** [comment]
ntp的程序可能还没更完，再等等吧
