### ISSUE TITLE
自动故障切换功能失效

### ISSUE THREAD

**Issue by jacklei2008** [coolsnowwolf/lede#1914]
以前的版本没有问题，最近的几个版本，具体从哪个版本开始出现这个问题，也测试不出来了。因为总是用最新的GIT PULL.
所以只能受累看一下，SSR+中的故障自动切换功能，是否还有效？谢谢

**Comment by jacklei2008** [comment]
忘记说环境了。4.9内核，最后一次git pull应该是在昨天晚上。

**Comment by coolsnowwolf** [comment]
一直有效
