### ISSUE TITLE
sysupgrade格式固件如何编译啊

### ISSUE THREAD

**Issue by helllkz** [coolsnowwolf/lede#1919]
版本升级了，想保留配置升级，但是需要上传一个 sysupgrade 格式的固件映像文件以替换当前运行的固件，我编译出来没有这个呢
目前我用的PVE的qcow2格式的，uefi-gpt的

**Comment by ITdesk01** [comment]
make V=99，出不了自行检查报错，有没有限制固件大小

**Comment by helllkz** [comment]
我是X86的，应该没限制问题的，menuconfig里面也没看到有sysupgrade相关选项呢？

**Comment by coolsnowwolf** [comment]
默认就是保留配置的，MBR 格式
