### ISSUE TITLE
剛pull的，錯誤信息如下

### ISSUE THREAD

**Issue by WillLamMe** [coolsnowwolf/lede#1921]
Package libblobmsg-json is missing dependencies for the following libraries:
libjson-c.so.4
Makefile:105: recipe for target '/home/wade/lede/bin/packages/x86_64/base/libblobmsg-json_2018-07-25-c83a84af-2_x86_64.ipk' failed
make[3]: *** [/home/wade/lede/bin/packages/x86_64/base/libblobmsg-json_2018-07-25-c83a84af-2_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/wade/lede/package/libs/libubox'
time: package/libs/libubox/compile#0.78#0.67#1.41
package/Makefile:107: recipe for target 'package/libs/libubox/compile' failed
make[2]: *** [package/libs/libubox/compile] Error 2
make[2]: Leaving directory '/home/wade/lede'
package/Makefile:103: recipe for target '/home/wade/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/wade/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wade/lede'
/home/wade/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by coolsnowwolf** [comment]
最新 hostbuild 变化较大，建议整个目录删除后重新构建
