### ISSUE TITLE
Nps内网穿透界面是这样的？哪怎么玩？

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#1923]
![image](https://user-images.githubusercontent.com/17406910/67689628-8dde8980-f9d6-11e9-8f05-6be416a406c3.png)

**Comment by Aes64X** [comment]
暂时先别用这个。。。。这是其他人提交给大雕的

**Comment by Her0R0cket** [comment]
nps其实挺好用的,在服务端生成ID,客户端只要带服务器ip,端口和id参数启动就好,配置可以在nps的网页里添加.和frp还是不一样的

**Comment by mjyhj** [comment]
最近git pull了一次，还是一样的
