### ISSUE TITLE
commits 1cf0ac 所遇问题

### ISSUE THREAD

**Issue by ksong008** [coolsnowwolf/lede#1926]
硬件：n3865 6口211网卡x86_64,物理直刷。
所遇问题：4.14，4.19内核，修改lan ip地址或者设置wan后ppoe拨号就自动重启。
编译过程:git pull ,update feed，make dirclean后清除tmp和config编译。
在上版本内核未遭遇此问题，不知是个人原因还是新内核问题

**Comment by coolsnowwolf** [comment]
最新 hostbuild 变化较大，建议整个目录删除后重新构建
