### ISSUE TITLE
固件大小异常

### ISSUE THREAD

**Issue by Aes64X** [coolsnowwolf/lede#1935]
![QQ截图20191029234331](https://user-images.githubusercontent.com/47932152/67784203-5dfeb700-faa6-11e9-9487-7dc4dd08b978.jpg)
D1的固件，flash一共32mb，之前一直正常14+mb左右，今天突然来个32。。。。。。无论删除任何部件，总大小出来都是32.......

**Comment by Aes64X** [comment]
过程无任何异常

**Comment by Aes64X** [comment]
newifi D1 mt7621 256内存  32mb存储

**Comment by Aes64X** [comment]
> 
> 
> wrt3200也发现这个问题。貌似升级gcc后出现的问题

你写进去了？？？能启动不？

**Comment by Aes64X** [comment]
之前x86固件大小我一直用的EXT4格式256mb大小，不知道哪次git pull之后突然提示我分区空间不足？？？- -！

**Comment by 4860575** [comment]
我没有刷机。

**Comment by xnxy2012** [comment]
试试呗，不行ttl弄回来

**Comment by Aes64X** [comment]
我尝试刷进去了，没死。。。正常启动

**Comment by Aes64X** [comment]
别选docker。。。。这玩意有毒，我在x86上选了docker，然后编译D1的，固件大小直接32。。。。。重拉代码，直接编译D1，大小正常

**Comment by Aes64X** [comment]
不是病毒的毒。。。比喻而已 - -#
