### ISSUE TITLE
建议添加SSD订阅支持

### ISSUE THREAD

**Issue by marcosteam** [coolsnowwolf/lede#1938]
项目地址：[TheCGDF/SSD](https://github.com/TheCGDF/SSD-Windows)
目前大多数用户使用的还是商家提供的服务，因此需要快速导入大量节点时十分需要订阅，但众所周知，支持订阅的SSR原作者已经停止开发，且不兼容SS最新的AEAD流加密。建议Lean可以添加SSD（依附于原版SS）订阅规则的解析支持！

**Comment by coolsnowwolf** [comment]
SSR 为什么要兼容 SS ?

**Comment by garypang13** [comment]
> 项目地址：[TheCGDF/SSD](https://github.com/TheCGDF/SSD-Windows)
> 目前大多数用户使用的还是商家提供的服务，因此需要快速导入大量节点时十分需要订阅，但众所周知，支持订阅的SSR原作者已经停止开发，且不兼容SS最新的AEAD流加密。建议Lean可以添加SSD（依附于原版SS）订阅规则的解析支持！

只支持SS,不支持SSR和V2Ray的飞机场就不要考虑了,

**Comment by outemancut** [comment]
不是V2R跟SSR的 就差不多可以淘汰了

**Comment by marcosteam** [comment]
> SSR 为什么要兼容 SS ?

并不是说要兼容SS，目前大多数的机场面板已经添加了SSD订阅，我更偏向于SS最新的AEAD加密，所以只是提个建议

**Comment by adamw92** [comment]
> > SSR 为什么要兼容 SS ?
> 
> 并不是说要兼容SS，目前大多数的机场面板已经添加了SSD订阅，我更偏向于SS最新的AEAD加密，所以只是提个建议

一般能提供ssd订阅链接的，ss订阅链接都是sip002格式的，然后目前是支持sip002的订阅的…
