### ISSUE TITLE
編譯QEMU ARM Virtual Machine > ARMv8 跑到go-1.12.1出錯了

### ISSUE THREAD

**Issue by Mattaclp** [coolsnowwolf/lede#1939]
嘗試過替換go1.12.5.src.tar版本也一樣
請求L大看看~謝謝

( cd /home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/src ; GOROOT_FINAL=/home/ubuntu/lede/staging_dir/hostpkg/lib/go-cross  GOROOT_BOOTSTRAP=/home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.go_bootstrap CC=gcc CXX=g++  bash make.bash --no-banner ; )
Building Go cmd/dist using /home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.go_bootstrap.
Building Go toolchain1 using /home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.go_bootstrap.
go build bootstrap/cmd/compile/internal/ssa: /home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.go_bootstrap/pkg/tool/linux_amd64/6g: signal: killed
go tool dist: FAILED: /home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.go_bootstrap/bin/go install -gcflags=-l -tags=math_big_pure_go compiler_bootstrap bootstrap/cmd/...: exit status 1
Makefile:271: recipe for target '/home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.built' failed
make[3]: *** [/home/ubuntu/lede/build_dir/hostpkg/go-1.12.1/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/lede/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#221.97#49.67#158.98
package/Makefile:107: recipe for target 'package/feeds/packages/golang/host/compile' failed
make[2]: *** [package/feeds/packages/golang/host/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/lede'
package/Makefile:103: recipe for target '/home/ubuntu/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/lede'
/home/ubuntu/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
![SSS](https://user-images.githubusercontent.com/51333346/67831699-20d40c80-fb1a-11e9-8174-47f24da68d4e.jpg)

**Comment by coolsnowwolf** [comment]
go tool dist 下载依赖失败了，没被墙吧？

**Comment by Mattaclp** [comment]
我把他刪除了，然後他重新下載，也是編譯失敗，我這個是在甲骨文vps上編譯的，不知道是否vps環境問題導致

**Comment by Keith2002** [comment]
![Error 2 03](https://user-images.githubusercontent.com/53608272/68530139-89a05d80-0340-11ea-8707-6665575ace13.PNG)
我也出现了GoLang的问题  试了3次了还是报错
