### ISSUE TITLE
编译完没有选的包为什么还能看到

### ISSUE THREAD

**Issue by moweiraul** [coolsnowwolf/lede#1950]
编译完在/etc/init.d/下，很多没有选择的包还是可以看到，比如docker，vsftpd等等，然后查询安装的软件包，是能看到的，只是并不完全（可能只有一两个包，但是这个应用可能要更多的包才算彻底安装）

**Comment by moweiraul** [comment]
> 你只是没有选luci 依赖不会取消吧 只要你勾过luci-app-xxx

那有没有办法编译的时候把相应的依赖包也去掉

**Comment by hyird** [comment]
> > 你只是没有选luci 依赖不会取消吧 只要你勾过luci-app-xxx
> 
> 那有没有办法编译的时候把相应的依赖包也去掉

自己搜索 取消掉

**Comment by z826540272** [comment]
重新建个config,config需要一次配置好,否则后期配置不会自己取消依赖
