### ISSUE TITLE
R619AC固件无法在openwrt WEB模式下刷机升级。

### ISSUE THREAD

**Issue by georip** [coolsnowwolf/lede#1957]
大雕您好！ 使用您的源码编译了r619ac的固件。在u-boot刷入编译的ubi固件正常，运行非常正常稳定。进入openwrt进行编译的bin固件更新后。路由器就挂了。。只有再进U-BOOT刷入UBI固件就正常。请您查证，修复！谢谢

**Comment by yinzhefuyun** [comment]
最好挂了能ttl提供log

**Comment by georip** [comment]
> 最好挂了能ttl提供log

拆这个r619ac比较费劲，等新车到了，复现提取TTL LOG。

**Comment by openwrt-diy** [comment]
我的华硕RT-ACRH17 也是和楼主的一个情况，十月底才出现这种情况。也是只有在Opboot下才能刷机。LUCI界面刷机后反复重启，断线，获取不到IP. 当后来可以正常进路由后，发现的版本还是之前的，根本没有更新。
另外一个情况是，电脑网卡获取IP后，当WAN插入网线，马上重启死机。

**Comment by AmadeusGhost** [comment]
已根据https://github.com/LGA1150/openwrt pr

**Comment by openwrt-diy** [comment]
参照上面的修正代码，测试RT-ACRH17WEB模式下刷机升级依然不成功，重启后还是原来的固件。

**Comment by AmadeusGhost** [comment]
> 参照上面的修正代码，测试**RT-ACRH17** WEB模式下刷机升级依然不成功，重启后还是原来的固件。

那个是给竞斗云用的，acrh17不一样，最好另外开一个issue并提供ttl日志。

**Comment by georip** [comment]
经过刷机测试，升级bug成功修复！感谢大雕修复源码！感谢AmadeusGhost！

**Comment by AmadeusGhost** [comment]
> 经过刷机测试，升级bug成功修复！感谢大雕修复源码！感谢AmadeusGhost！

应该感谢 @LGA1150 ,竞斗云都是他适配的。
