### ISSUE TITLE
请添加kmod-i40e和kmod-i40evf的网卡驱动

### ISSUE THREAD

**Issue by RGGGong** [coolsnowwolf/lede#1958]
L大你好，我的网卡是万兆X710。我在旧版本（9.10.17）中可以驱动，在新版本（9.10.25）中无法驱动。我在旧版中查下到该网卡驱动是kmod-i40e和kmod-i40evf，在新版本编译的时候找不到这两个驱动，请您添加在源码里，谢谢了~~

**Comment by coolsnowwolf** [comment]
supported
