### ISSUE TITLE
ssr-plus pdnsd的问题

### ISSUE THREAD

**Issue by hanwenzhang** [coolsnowwolf/lede#1963]
修改了ssr的配置保存之后pdns没有正常启动，进程有，但是没有监听端口。改为监听本地5335端口，dns查询返回的时间不正常。

**Comment by txdywy** [comment]
也遇到这个问题

**Comment by txdywy** [comment]
#1599

kill掉pdnsd进程再单独执行命令pdnsd -c /var/etc/pdnsd.conf -d 管用
