### ISSUE TITLE
关于ss plus+未运行问题

### ISSUE THREAD

**Issue by toni-l** [coolsnowwolf/lede#1965]
编译没报错，ss plus+不需要开门命令可以直接看到，但是加入节点一直显示未运行。。。

**Comment by Her0R0cket** [comment]
是不是没选主服务器

**Comment by toni-l** [comment]
> 是不是没选主服务器

节点加入可以选择，但是一直显示未启动，另外GFW列表貌似也更新不正常了

**Comment by AmadeusGhost** [comment]
> > 是不是没选主服务器
> 
> 节点加入可以选择，但是一直显示未启动，另外GFW列表貌似也更新不正常了

GFW更新可以参照这个pr：https://github.com/coolsnowwolf/lede/pull/1967
或者把githubusercontent.com加进黑名单

**Comment by king9039** [comment]
请问楼主解决了嘛？我也遇到了，我用前面几个版本的不保存数据刷回去也不行，用了10月12编译的没问题

**Comment by toni-l** [comment]
> 请问楼主解决了嘛？我也遇到了，我用前面几个版本的不保存数据刷回去也不行，用了10月12编译的没问题

没有，暂时先用之前的了
