### ISSUE TITLE
艰难啊，这次是boost了

### ISSUE THREAD

**Issue by vincentchen** [coolsnowwolf/lede#1968]
![Screenshot_2019-11-02-12-36-20-546_com sonelli juicessh](https://user-images.githubusercontent.com/329461/68066158-4e18f880-fd6e-11e9-813e-4b338ded7696.jpg)

**Comment by Her0R0cket** [comment]
把boost退回到1.69,新boost下rblibtorrent编译失败

**Comment by vincentchen** [comment]
不行啊，实在没脾气了
![Screenshot_2019-11-02-17-59-04-508_com sonelli juicessh](https://user-images.githubusercontent.com/329461/68069373-7b7b9b80-fd9a-11e9-8b3d-c1e6f9c915ea.jpg)

**Comment by toni-l** [comment]
这个要配置编译环境变量，比较麻烦，别折腾了

**Comment by Her0R0cket** [comment]
> 
> 
> 不行啊，实在没脾气了
> ![Screenshot_2019-11-02-17-59-04-508_com sonelli juicessh](https://user-images.githubusercontent.com/329461/68069373-7b7b9b80-fd9a-11e9-8b3d-c1e6f9c915ea.jpg)

你是不是没隐藏patch?

**Comment by Her0R0cket** [comment]
看日志好像已经编译完成,复制文件的时候缺失文件失败了

**Comment by Her0R0cket** [comment]
1.69不能只改版本,makefile差别还是很大的
