### ISSUE TITLE
ssr plus+ wan ip 控制错误

### ISSUE THREAD

**Issue by xingweizzxx** [coolsnowwolf/lede#1969]
/usr/bin/ssr-rules脚本在解析强制走代理的wan ip 和不代理wan ip上
我感觉有点小缺陷
根据/usr/bin/ssr-rules的代码,强制走代理的wan,必须在gfw模式上才会写入ipset的gfwlist
而不代理的wan ip,只会在绕过中国ip模式,才会写入到ipset的ss_spec_wan_ac

小弟感觉,wan ip的控制,应该所有模式都应该支持吧.

**Comment by xingweizzxx** [comment]
for ip in $WAN_BP_IP; do ipset -! add whitelist $ip; done
for ip in $WAN_FW_IP; do ipset -! add blacklist $ip; done
我现在加入了这两句,先用现成的whitelist和blacklist

**Comment by coolsnowwolf** [comment]
嗯，加入了黑白名单的逻辑后，是应该这么改的吧

**Comment by coolsnowwolf** [comment]
这个其实本来是想回国模式不受这个黑白名单的影响

**Comment by xingweizzxx** [comment]
@coolsnowwolf 大佬更新的快啊,哈哈
