### ISSUE TITLE
SSR Plus 服务端无法通过ipv6访问

### ISSUE THREAD

**Issue by CirnoSalt** [coolsnowwolf/lede#1972]
已有原生ipv6接入环境，testv6正常，
可以通过公网ipv6地址访问路由器后台并且ping通，防火墙已放行，
但SSR自带服务端功能在局域网内测试使用v4地址可以连接，使用v6地址无法连接。
经查阅资料ssr服务端支持：
```
"server_ipv6": "::"
"dns_ipv6": true
```
两个选项，望plus插件能加入，以满足公网ipv6直连需求。

**Comment by cnsilvan** [comment]
same here

**Comment by Iy204** [comment]
测试了好久没法用。防火墙里转发也不行。
