### ISSUE TITLE
aria2一直是正在收集数据状态

### ISSUE THREAD

**Issue by chuds001** [coolsnowwolf/lede#1975]
aria2 一直是正在收集数据状态，卸载后安装非自己编译的就正常，比较发现Aria2 配置在bitTorrent的配置不同

**Comment by Her0R0cket** [comment]
menuconfig 里aria2有个详细配置的子项,去把里面子项目都选上试试看

**Comment by kltk** [comment]
[https://github.com/coolsnowwolf/luci/pull/7/files](https://github.com/coolsnowwolf/luci/pull/7/files)
