### ISSUE TITLE
遇到错误小白看不懂  请大佬给指点指点  从来几次了

### ISSUE THREAD

**Issue by qq9568488** [coolsnowwolf/lede#1977]
Makefile:26252: recipe for target '.obj/qsslsocket_openssl_symbols.o' failed
make[7]: *** [.obj/qsslsocket_openssl_symbols.o] Error 1
make[7]: Leaving directory '/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1/qtbase/src/network'
Makefile:272: recipe for target 'sub-network-make_first' failed
make[6]: *** [sub-network-make_first] Error 2
make[6]: Leaving directory '/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1/qtbase/src'
Makefile:50: recipe for target 'sub-src-make_first' failed
make[5]: *** [sub-src-make_first] Error 2
make[5]: Leaving directory '/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1/qtbase'
Makefile:70: recipe for target 'module-qtbase-make_first' failed
make[4]: *** [module-qtbase-make_first] Error 2
make[4]: Leaving directory '/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1'
Makefile:225: recipe for target '/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1/.built' failed
make[3]: *** [/home/bjian/openwrt/source/build_dir/target-x86_64_musl/qt-everywhere-src-5.13.1/.built] Error 2
make[3]: Leaving directory '/home/bjian/openwrt/source/package/lean/qt5'
time: package/lean/qt5/compile#871.59#51.62#918.99
package/Makefile:111: recipe for target 'package/lean/qt5/compile' failed
make[2]: *** [package/lean/qt5/compile] Error 2
make[2]: Leaving directory '/home/bjian/openwrt/source'
package/Makefile:107: recipe for target '/home/bjian/openwrt/source/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/bjian/openwrt/source/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/bjian/openwrt/source'
/home/bjian/openwrt/source/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by coolsnowwolf** [comment]
qt5 目前还不兼容 openssl 1.1 新版，待修复

**Comment by qq9568488** [comment]
bjian@ubuntu:~$ openssl version
OpenSSL 1.0.2g  1 Mar 2016

**Comment by Her0R0cket** [comment]
> 
> 
> qt5 目前还不兼容 openssl 1.1 新版，待修复

??我编译过了啊,而且虚拟机测试qB是可以下载geoip库的,没有ssl支持是无法更新IP库的
![图片](https://user-images.githubusercontent.com/33145975/68080917-2f833200-fe40-11e9-89e1-7eaf14df98f1.png)

**Comment by rhww** [comment]
同样这个问题编译不过，我以为只有我有这个问题呢。

**Comment by kktt007** [comment]
你们太幸福了，还有男神回复，我的编译不通过都不知道找谁。我就是空格君~~
