### ISSUE TITLE
编译mtk 7260只能用4.14内核吗？4.14内核的编译链编译的改mac地址不生效。

### ISSUE THREAD

**Issue by nature2608** [coolsnowwolf/lede#1978]
一样的的源码编译ar71xx，mt7260，ar71xx是4.9内核，mt7260是4.14内核，编译完发现proto-dhcp里面的文件跟luci-base的不符合，mt7260修改wan口mac地址只会修改wan.macaddr,不会修改wan_dev。macaddr，因此导致mentohust等无法识别正确的wan口mac，请问有什么解决办法吗。

经过排查不是内核的问题，不是很明白wan_dev这个是怎么产生的，而ar71xx没有

**Comment by liujixings** [comment]
直接修改/etc/config/network 里面的mac地址就行了，在uci里面改不生效

**Comment by nature2608** [comment]
@liujixings 我知道这样可以改，可能你没看清楚我的问题。我在ar71xx，4.9内核下是可以正常修改的，而mt7260，4.14下不行，对比发现是编译toolchain里带的proto-dhcp等不同。

**Comment by hyird** [comment]
> @liujixings 我知道这样可以改，可能你没看清楚我的问题。我在ar71xx，4.9内核下是可以正常修改的，而mt7260，4.14下不行，对比发现是编译toolchain里带的proto-dhcp等不同。

mtk的机器 在luci 改不了的

**Comment by nature2608** [comment]
@hyird 难怪，后面我写了个脚本直接用ifconfig 设置man，再把network的config同时修改。
