### ISSUE TITLE
最新版固件启动时间特别长，需要三分钟才能进入界面

### ISSUE THREAD

**Issue by ldy8182** [coolsnowwolf/lede#1981]
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/3801487/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/3801488/default.txt)

**Comment by killDevils** [comment]
我遇到了相同问题。开机后约150秒才能访问 LuCi。

**Comment by ldy8182** [comment]
11.9号最新版没问题了
