### ISSUE TITLE
SS Plus针对V2ray的HTTP伪装无效

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/lede#1984]
### 测试源码版本
**Commits 1642**
### 测试问题

代理方式|模式|结果
-|-|-
V2ray mkcp代理|无为装模式|正常
V2ray mkcp代理|各类伪装模式|正常
V2ray TCP代理|无伪装模式|正常
**V2ray TCP代理**|**http伪装+http host**|**失败**

V2ray TCP htto伪装+http Host 客户端测试正常

请求修复该问题

**Comment by zhaoxp520** [comment]
TCP+http用不了这个之前反馈过了~不过iss直接被L大关闭了
换ws+tls吧~这个不错

**Comment by smallprogram** [comment]
> TCP+http用不了这个之前反馈过了~不过iss直接被L大关闭了 换ws+tls吧~这个不错

我反馈问题，希望能得到解决
