### ISSUE TITLE
请教下如何打开SSR？

### ISSUE THREAD

**Issue by Leadrive** [coolsnowwolf/lede#1989]
newifi3，刷的openwrt-lean-R8.1.10.24-ramips-mt7621-newifi-d2-squashfs-sysupgrade(v2ray pro).bin
配置上显示SSR没有运行。
执行 echo 0xDEADBEEF > /etc/config/google_fu_mode 后，刷新还是没有。

请问该如何打开吗？在恩山没搜索到，只好在这提问，谢谢各位。

另外，我是自己开了VPS，能提供个配置参考吗？非常感谢！

**Comment by shikkoku** [comment]
你的版本是一年前的，装个新点的吧。

**Comment by Leadrive** [comment]
下载最新代码，重新编译，烧进板子后，还是显示SSR没有运行。
logread，好像也没看到什么错误。
请问哪里还有小窍门吗？谢谢。

**Comment by Leadrive** [comment]
弄好了。需要在服务器添加节点，才能开启。
