### ISSUE TITLE
11.3源码编译4.19内核出错

### ISSUE THREAD

**Issue by Raytheon-S** [coolsnowwolf/lede#1993]
L大，我按教程下载了最新的源码，确保网络通畅的情况下，编译不能成功。如果去/target/linux/x86里更改Makefile为4.9，就能成功编译。要怎么解决这个问题？

**Comment by Raytheon-S** [comment]
![W](https://user-images.githubusercontent.com/57355869/68122734-fc2acb00-ff45-11e9-9019-b667de80b04a.jpg)

**Comment by yclin20** [comment]
怎么这么多人问这个问题，在关闭的issues里找找

**Comment by helianling** [comment]
我也是同样的问题，用默认内核4.19编译遇到同样的问题。

**Comment by Kinodi** [comment]
全新编译   一次过
