### ISSUE TITLE
可否为ssrplus加入simple-obfs和v2ray-plugin支持呢？

### ISSUE THREAD

**Issue by jh0072110** [coolsnowwolf/lede#1997]
鉴于ssr停止开发那么久，现在除了v2，在维护的版本只有ss-libev版本了，ss新增加（其实增加了好久了）的混淆特性到现在ssrplus都不支持呢…请问可否添加simple-obfs和v2ray-plugin的支持？查看了之前的issue，插件里new version并不支持该特性，感谢大佬。

**Comment by zcluo** [comment]
大佬上次在电报表示不想支持😂

**Comment by LitCcc** [comment]
支持一下，ss-libev最近几次更新还是挺稳的

**Comment by jh0072110** [comment]
> 大佬上次在电报表示不想支持😂

额，这不是正统大道么，不想资瓷什么鬼…

**Comment by jiushibushuo** [comment]
混淆就是歪门邪道，建议支持Trojan
