### ISSUE TITLE
解锁网易云音乐更新版本后不显示运行主程序版本

### ISSUE THREAD

**Issue by z826540272** [coolsnowwolf/lede#1998]
目前运行主程序版本:
空白

日志:
HTTP Server running @ http://0.0.0.0:5200
HTTPS Server running @ https://0.0.0.0:5201
更新前是
HTTP Server running @ http://0.0.0.0:5200
HTTPS Server running @ https://0.0.0.0:5201
HTTPS Server running @ https://0.0.0.0:5202

**Comment by coolsnowwolf** [comment]
再更新一次
