### ISSUE TITLE
大家有YouTube APP可以观看 无法登陆的现象吗

### ISSUE THREAD

**Issue by qiboshi19** [coolsnowwolf/lede#1999]
如题

**Comment by hcym** [comment]
一直正常，不行的话试试路由模式

**Comment by xiaofami** [comment]
同样遇到此问题，浏览器一切正常，唯独Android YTB 客户端在登录状态下打开直接显示请检查您的网络连接，清空数据后打开能看视频，但是点击登录还是会出现请检查您的网络连接

**Comment by hcym** [comment]
app走的可能不止80 443

**Comment by xiaofami** [comment]
> app走的可能不止80 443

重启手机就好了……只切换飞行模式不行
