### ISSUE TITLE
(建议)希望能加入lede-modhostapd

### ISSUE THREAD

**Issue by MeISbug** [coolsnowwolf/lede#2]
请参见 
https://forum.lede-project.org/t/how-to-automatically-disconnect-client-when-rssi-is-low/6352

https://github.com/mk248/lede-modhostapd

可以让无线有自动剔除弱信号设备的功能，对所有设备有效

希望大神能加到固件里去，非常感谢

**Comment by coolsnowwolf** [comment]
我研究看看，感谢

**Comment by coolsnowwolf** [comment]
lede 后面的 hostapd 变化太大，不兼容了
