### ISSUE TITLE
Openwrt如何隐藏（不显示）已安装的软件？

### ISSUE THREAD

**Issue by Nicepaul** [coolsnowwolf/lede#2002]
Openwrt中的怎么隐藏特定的软件？比如隐藏SSR，但是可以IP/cgi-bin/luci/admin/services/shadowsocksr打开进行设置。  我给表弟设置好软路由了，不想让他乱改，所以关键软件想隐藏起来。

**Comment by outemancut** [comment]
这个还不简单？直接删掉LUCI管理

**Comment by Nicepaul** [comment]
> 这个还不简单？直接删掉LUCI管理

能详细说一下吗？小白不懂啊

**Comment by lifetyper** [comment]
改一次打一次
