### ISSUE TITLE
mvebu 4.9.65编译还是有错误

### ISSUE THREAD

**Issue by gavin219** [coolsnowwolf/lede#201]
mkdir -p /home/gavin/lede/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu
xzcat /home/gavin/lede/dl/linux-4.9.65.tar.xz | tar -C /home/gavin/lede/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu -xf -
xzcat: /home/gavin/lede/dl/linux-4.9.65.tar.xz: Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
make[4]: *** [/home/gavin/lede/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu/linux-4.9.65/.prepared_fefbd5bd4aa3ebf973e34f05840fe94b] Error 2
make[4]: Leaving directory `/home/gavin/lede/target/linux/mvebu'
make[3]: *** [compile] Error 2
make[3]: Leaving directory `/home/gavin/lede/target/linux'
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory `/home/gavin/lede'
make[1]: *** [/home/gavin/lede/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory `/home/gavin/lede'
make: *** [world] Error 2

**Comment by daofeng2015** [comment]
你这个文件下载错误，删除了重新下
