### ISSUE TITLE
verysync的Makefile版本要更新了1.2.5官方已经从网站上撤了

### ISSUE THREAD

**Issue by 0x5826** [coolsnowwolf/lede#2013]
verysync的Makefile版本要更新了，1.2.5官方已经从网站上撤了，现在是1.2.7和1.2.8

**Comment by bin000000** [comment]
是的，1.2.4和1.2.5都已经下载不到了，编译肯定报错。我改成1.2.7或者1.2.8都没问题，编译正常使用正常
