### ISSUE TITLE
能否自动删除订阅里面的无效节点？

### ISSUE THREAD

**Issue by 878779616** [coolsnowwolf/lede#2021]
订阅里面虽然有很多个节点，但是有些是ping都ping不通的，同步的时候是否可以自动过滤掉？

**Comment by outemancut** [comment]
我觉得你最好还能发个PR好一点！

**Comment by cdcvip** [comment]
有想法就去实现他！

**Comment by 878779616** [comment]
> 我觉得你最好还能发个PR好一点！

逗我么，自己去网上找了一些免费的订阅地址，我发啥PR？互联网圈的人，互联网思维？
