### ISSUE TITLE
It seems openvswitch lost some definition in some .h file/ for RaspberryPi3B

### ISSUE THREAD

**Issue by sunberchou** [coolsnowwolf/lede#2022]
/home/sunber/sunber-wrt/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-brcm2708_bcm2709/openvswitch-2.8.2/lib/dhparams.c
### 26:4: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
  dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
    ^~

**Comment by ShooreshHalland** [comment]
I face the same problem when I try to cross-compile it to **arm-linux-gnueabi**

```
lib/dhparams.c:26:4: error: dereferencing pointer to incomplete type ‘DH’ {aka ‘struct dh_st’}
  dh->p=BN_bin2bn(dh1024_p,sizeof(dh1024_p),NULL);
```
