### ISSUE TITLE
meijutt.com这个站打不开

### ISSUE THREAD

**Issue by hzdlive** [coolsnowwolf/lede#2023]
http://www.meijutt.com
这个网站，我把SSR PLUS关掉后就可以打开这个网站的

**Comment by raiuka** [comment]
这个网站本身就不存在了，关了你的issue吧

**Comment by hzdlive** [comment]
> 这个网站本身就不存在了，关了你的issue吧

http://www.meijutt.com
这个网站，我把SSR PLUS关掉后就可以打开这个网站的

**Comment by Waterman1997** [comment]
![1](https://ae01.alicdn.com/kf/H7519d6f4439745ce99cb99a56a2b139b4.png)
![2](https://ae01.alicdn.com/kf/H0a8552972f4242578aa019cafae6f126o.png)

**Comment by hzdlive** [comment]
那奇怪了，我的打不开

**Comment by Waterman1997** [comment]
> 那奇怪了，我的打不开

我也打不开，不走代理的WAN IP 加这两IP就可以打开了

**Comment by hzdlive** [comment]
www.meijutt.com的wan IP是你截图的那个吗？

**Comment by Waterman1997** [comment]
> [www.meijutt.com的wan](http://www.meijutt.com%E7%9A%84wan) IP是你截图的那个吗？

是

**Comment by hzdlive** [comment]
> > [www.meijutt.com的wan](http://www.meijutt.com%E7%9A%84wan) IP是你截图的那个吗？
> 
> 是

加入后我也没能打开。

**Comment by hzdlive** [comment]
> > [www.meijutt.com的wan](http://www.meijutt.com%E7%9A%84wan) IP是你截图的那个吗？
> 
> 是

怎么设定不走代理的域名呢？
