### ISSUE TITLE
frp客户端的token配置名称不对

### ISSUE THREAD

**Issue by ZqinKing** [coolsnowwolf/lede#2026]
需要修改/etc/init.d/frp文件，
start() 下
echo "token=${token}" >>$tmpconf =>>echo "privilege_token=${token}" >>$tmpconf

**Comment by yclin20** [comment]
和版本有关吧，我用token使用正常

**Comment by zxlhhyccc** [comment]
> 需要修改/etc/init.d/frp文件，
> start() 下
> echo "token=${token}" >>$tmpconf =>>echo "privilege_token=${token}" >>$tmpconf

你的服务端设置问题，需要设置token而不是privilege_token

**Comment by ZqinKing** [comment]
> > 需要修改/etc/init.d/frp文件，
> > start() 下
> > echo "token=${token}" >>$tmpconf =>>echo "privilege_token=${token}" >>$tmpconf
> 
> 你的服务端设置问题，需要设置token而不是privilege_token

这样子咩。服务端有一年多了。都忘了当初怎么设置的了。
