### ISSUE TITLE
ssr-Plus 访问控制 域名白/黑名单 如何正确使用？

### ISSUE THREAD

**Issue by killDevils** [coolsnowwolf/lede#2029]
我想禁止学生上 YouTube 。

“绕过中国大陆IP”模式下，把 youtube.com 填入到 “域名白名单”，“保存并应用”，并没有起作用。
(按理说，在国内，强制 youtube.com 直连就相当于屏蔽。)

是不是用法错误？这个功能刚刚发布，网上完全没有相关说明。

请好朋友们帮帮忙简单写写具体用法

**Comment by outemancut** [comment]
禁止不写进黑名单？

**Comment by weibin22** [comment]
也想请教这个问题，黑白名单到底怎么用

**Comment by blacktea17** [comment]
同问，直接写了没用，是否有域名写入规则

**Comment by nopain1573** [comment]
同问

**Comment by yangjiey2k** [comment]
我也想知道。。。

**Comment by leonliao78** [comment]
> 我想禁止学生上 YouTube 。

youtube可能会把你列入黑名单

**Comment by gavin8857** [comment]
还不如直接设置学生的IP为不走代理简单些
