### ISSUE TITLE
编译出来的固件刷不了

### ISSUE THREAD

**Issue by vincentchen** [coolsnowwolf/lede#2030]
提示 不支持所上传的映像文件格式，请选择适合当前平台的通用映像文件。
k2p和17都有这个问题

**Comment by outemancut** [comment]
自己不会进不死breed刷？非得从系统更新？

**Comment by Her0R0cket** [comment]
贴出你的文件名吧

**Comment by vincentchen** [comment]
openwrt-ipq40xx-asus_rt-acrh17-squashfs-sysupgrade.bin
多编译了几个，大小126兆，到OP刷上传到37%就挂了，在系统刷提示不支持所上传的映像文件格式
k2p是在系统刷提示不支持所上传的映像文件格式，还没试breed刷

**Comment by Her0R0cket** [comment]
126M? acrh17虽然有128m,但还有其他预留的分区的吧,k2p硬改的flash也就32m

**Comment by vincentchen** [comment]
k2p是默认的，10来m
