### ISSUE TITLE
linksys wrt32x 新版固件wan口无论ppoe还是DHCP都会无限重启

### ISSUE THREAD

**Issue by ITdesk01** [coolsnowwolf/lede#2031]
截至到20191109今天的固件，一旦刷进去，wan口有连接线的时候直接会重启，然后不断重启，ppoe和DHCP我都试过了

**Comment by ITdesk01** [comment]
已知，在10月27日编译的固件都正常

**Comment by AmibaWorld** [comment]
沃出现，无法拨号，ppoe 貌似没有运行

**Comment by ITdesk01** [comment]
> 沃出现，无法拨号，ppoe 貌似没有运行

不运行还好，我是直接拨号就重启，我的R7800更惨，直接拨号不运行，DHCP直接重启......

**Comment by ITdesk01** [comment]
换了一个源码又好了。。。
