### ISSUE TITLE
$$R没有实现 option lan_ac_mode 'w'

### ISSUE THREAD

**Issue by doumeki** [coolsnowwolf/lede#2043]
修改config下的配置文件为w模式也无法使ssr-rules 的代码走到 case w|W)下,求实现白名单模式(默认全部block).

**Comment by coolsnowwolf** [comment]
特意去掉的，以免造成逻辑上的混肴

**Comment by king9039** [comment]
> 特意去掉的，以免造成逻辑上的混肴

大佬，为什么最近几个版本V2Ray启动不了呢？$$都可以
