### ISSUE TITLE
fdisk死活安装不好

### ISSUE THREAD

**Issue by lovezm** [coolsnowwolf/lede#2044]
root@OpenWrt:~# fdisk -l
Error relocating /usr/lib/libfdisk.so.1: secure_getenv: symbol not found
Error relocating /usr/lib/libblkid.so.1: secure_getenv: symbol not found
Error relocating /usr/lib/libsmartcols.so.1: secure_getenv: symbol not found
卸载了 这四个 然后安装还是不行

**Comment by coolsnowwolf** [comment]
ssl 版本不对

**Comment by lovezm** [comment]
卸载重装最新的可以吗 还是编译的

**Comment by lovezm** [comment]
重新编译了包 还是安装不了fdisk 求救 L大

**Comment by comcj** [comment]
我也出现这个情况  Error relocating /usr/lib/libfdisk.so.1: blkid_wipe_all: symbol not found
