### ISSUE TITLE
ShadowsocksR Plus+ NOT RUNNING

### ISSUE THREAD

**Issue by daqinKnight** [coolsnowwolf/lede#2052]
１、重新编译后，ShadowsocksR Plus+ NOT RUNNING　一直报ShadowsocksR Plus+ NOT RUNNING
![image](https://user-images.githubusercontent.com/30095839/68578282-a9549480-04ac-11ea-8449-ac1960f305f9.png)

２、主机型号	NETGEAR WNR2200　架构	Atheros AR7241 rev 1

３、服务器情况：
![image](https://user-images.githubusercontent.com/30095839/68578463-06e8e100-04ad-11ea-924f-b21322406fb9.png)
４、系统状态情况
![image](https://user-images.githubusercontent.com/30095839/68578506-1bc57480-04ad-11ea-965a-1421d895a3cb.png)
５、日志情况
![image](https://user-images.githubusercontent.com/30095839/68578554-34358f00-04ad-11ea-9dc6-876525bee509.png)

６、大神，这个会是什么问题？该如何处理呢？

**Comment by hgh188** [comment]
![捕获](https://user-images.githubusercontent.com/45268614/68584525-c98b5000-04ba-11ea-921c-879d4bdeba97.PNG)
![捕获1](https://user-images.githubusercontent.com/45268614/68584532-cabc7d00-04ba-11ea-8ce3-57418cdcd939.PNG)
一切正常 最新源码

**Comment by coolsnowwolf** [comment]
luci 版本不对

**Comment by daqinKnight** [comment]
大神在看一下什么问题
1、重新编译一下（主机型号 NETGEAR WNR2200　架构 Atheros AR7241 rev 1），安装报错如下：
root@OpenWrt:/tmp# opkg install luci-app-ssr-plus_1-125_all.ipk 
Installing luci-app-ssr-plus (1-125) to root...
Configuring luci-app-ssr-plus.
uci: Entry not found
uci: Entry not found
uci: Parse error (invalid command) at line 1, byte 0
uci: Entry not found
Collected errors:
 * resolve_conffiles: Existing conffile /etc/dnsmasq.ssr/gfw_list.conf is different from the conffile in the new package. The new conffile will be placed at /etc/dnsmasq.ssr/gfw_list.conf-opkg.
2、系统还是不能运行
![image](https://user-images.githubusercontent.com/30095839/68741189-f6a94100-0627-11ea-9fe4-82c67d5123ec.png)

![image](https://user-images.githubusercontent.com/30095839/68741332-4b4cbc00-0628-11ea-8d9e-04b7c6982bee.png)

**Comment by daqinKnight** [comment]
已经OK ，重新编译后，刷入自己编译后的openwrt 
![image](https://user-images.githubusercontent.com/30095839/68911302-74d42780-078f-11ea-866b-d147e0a991f5.png)

**Comment by daqinKnight** [comment]
稳定运行2天后出现这个问题？什么情况？
![image](https://user-images.githubusercontent.com/30095839/69005369-448db400-095c-11ea-962a-54474fae6843.png)
