### ISSUE TITLE
AR71xx 4.14内核编译错误

### ISSUE THREAD

**Issue by libinanshu** [coolsnowwolf/lede#2054]
![捕获](https://user-images.githubusercontent.com/44538423/68605917-454fc180-04e8-11ea-9021-fa1bd0b48ffd.PNG)

**Comment by gsblay** [comment]
我也一样，内核选 4.9 重新编译，可以通过！4.14 无法通过。
类似的，ipq806x 选 4.19 内核也无法编译成功，选 4.14 就可以通过编译！
