### ISSUE TITLE
Ubuntu18.04LTS系统第一次编译，报错如下，请指点

### ISSUE THREAD

**Issue by GitMasterArm** [coolsnowwolf/lede#2056]
ERROR: module '/home/jry/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-4.19.79-1/net/mac80211/mac80211.ko' is missing.
Makefile:561: recipe for target '/home/jry/lede/bin/targets/x86/64/packages/kmod-mac80211_4.19.81+4.19.79-1-1_x86_64.ipk' failed
make[3]: *** [/home/jry/lede/bin/targets/x86/64/packages/kmod-mac80211_4.19.81+4.19.79-1-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/jry/lede/package/kernel/mac80211'
time: package/kernel/mac80211/compile#18.87#3.06#422.77
package/Makefile:107: recipe for target 'package/kernel/mac80211/compile' failed
make[2]: *** [package/kernel/mac80211/compile] Error 2
make[2]: Leaving directory '/home/jry/lede'
package/Makefile:103: recipe for target '/home/jry/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/jry/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jry/lede'
/home/jry/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by GitMasterArm** [comment]
![image](https://user-images.githubusercontent.com/45396912/68635782-92598500-0534-11ea-9981-bf1c3a4f9535.png)

**Comment by ksong008** [comment]
先默认跑一次，再添加删除插件

**Comment by Albert-Zhan** [comment]
x86-64编译这个版本需要换内核，内核换成4.9就可以了，跟插件无关的。

**Comment by Albert-Zhan** [comment]
![微信截图_20191112103423](https://user-images.githubusercontent.com/17407006/68636938-2aa53900-0538-11ea-8ca1-83170220535b.png)

**Comment by d975xbx** [comment]
x64一直都是4.19编译的，和选那个内核没什么关系

**Comment by GitMasterArm** [comment]
是下面动作吗：
1.git clone https://github.com/coolsnowwolf/lede 命令下载好源代码
2.通过WinSCP找到Makefile文件，修改保存
3.再进入PuTTY，执行./scripts/feeds update -a以后的命令吗？

**Comment by Albert-Zhan** [comment]
已经有代码了

**Comment by Albert-Zhan** [comment]
已经有代码了

**Comment by Albert-Zhan** [comment]
已经编译过了先

**Comment by greennyreborn** [comment]
> x64一直都是4.19编译的，和选那个内核没什么关系.
> 默认编译一遍就好

是说 make menuconfig 后不改参数先编译一遍，然后再重新再改插件，参数就行了？

**Comment by Albert-Zhan** [comment]
> 是下面的动作吗：
> 1.git clone https://github.com/coolsnowwolf/lede命令下载好源代码
> 2.通过WinSCP找到Makefile文件，修改保存
> 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？

已经编译过的:
rm -rf ./tmp
rm -rf ./staging_dir
rm -rf ./build_dir
rm -rf ./bin
然后修改Makefile，在编译就可以。

**Comment by GitMasterArm** [comment]
https://github.com/coolsnowwolf/lede/issues/2056#issuecomment-552712540
按你的办法再试一次，完成后汇报哈

**Comment by GitMasterArm** [comment]
> > 是下面的动作吗：
> > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > 2.通过WinSCP找到Makefile文件，修改保存
> > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> 
> 已经编译过的:
> rm -rf ./tmp
> rm -rf ./staging_dir
> rm -rf ./build_dir
> rm -rf ./bin
> 然后修改Makefile，在编译就可以。

按你的办法试一次，完成后汇报哈

**Comment by GitMasterArm** [comment]
> > > 是下面的动作吗：
> > > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > > 2.通过WinSCP找到Makefile文件，修改保存
> > > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> > 
> > 
> > 已经编译过的:
> > rm -rf ./tmp
> > rm -rf ./staging_dir
> > rm -rf ./build_dir
> > rm -rf ./bin
> > 然后修改Makefile，在编译就可以。
> 
> 按你的办法试一次，完成后汇报哈

这次报错是
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/shadowsocks-libev-3.3.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to downloads.openwrt.org port 443: Network is unreachable
Download failed.
我能自己下载shadowsocks-libev-3.3.1.tar.gz，拷贝到dl目录下吗？

**Comment by Albert-Zhan** [comment]
> > > > 是下面的动作吗：
> > > > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > > > 2.通过WinSCP找到Makefile文件，修改保存
> > > > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> > > 
> > > 
> > > 已经编译过的:
> > > rm -rf ./tmp
> > > rm -rf ./staging_dir
> > > rm -rf ./build_dir
> > > rm -rf ./bin
> > > 然后修改Makefile，在编译就可以。
> > 
> > 
> > 按你的办法试一次，完成后汇报哈
> 
> 这次报错是
> 
> * curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/shadowsocks-libev-3.3.1.tar.gz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>   Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to downloads.openwrt.org port 443: Network is unreachable
>   Download failed.
>   我能自己下载shadowsocks-libev-3.3.1.tar.gz，拷贝到dl目录下吗？

可以的，然后在执行，make -j1 V=s

**Comment by GitMasterArm** [comment]
> make -j1 V=s
成了，谢谢！！
![image](https://user-images.githubusercontent.com/45396912/68657399-9aceb180-056e-11ea-8b05-e32b9fc9234a.png)

**Comment by GitMasterArm** [comment]
> > > > > 是下面的动作吗：
> > > > > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > > > > 2.通过WinSCP找到Makefile文件，修改保存
> > > > > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> > > > 
> > > > 
> > > > 已经编译过的:
> > > > rm -rf ./tmp
> > > > rm -rf ./staging_dir
> > > > rm -rf ./build_dir
> > > > rm -rf ./bin
> > > > 然后修改Makefile，在编译就可以。
> > > 
> > > 
> > > 按你的办法试一次，完成后汇报哈
> > 
> > 
> > 这次报错是
> > 
> > * curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/shadowsocks-libev-3.3.1.tar.gz
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >   Dload  Upload   Total   Spent    Left  Speed
> >   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to downloads.openwrt.org port 443: Network is unreachable
> >   Download failed.
> >   我能自己下载shadowsocks-libev-3.3.1.tar.gz，拷贝到dl目录下吗？
> 
> 可以的，然后在执行，make -j1 V=s

![image](https://user-images.githubusercontent.com/45396912/68657478-c782c900-056e-11ea-9914-e70356a70f63.png)
成了，谢谢！！！

**Comment by Albert-Zhan** [comment]
> > > > > > 是下面的动作吗：
> > > > > > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > > > > > 2.通过WinSCP找到Makefile文件，修改保存
> > > > > > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> > > > > 
> > > > > 
> > > > > 已经编译过的:
> > > > > rm -rf ./tmp
> > > > > rm -rf ./staging_dir
> > > > > rm -rf ./build_dir
> > > > > rm -rf ./bin
> > > > > 然后修改Makefile，在编译就可以。
> > > > 
> > > > 
> > > > 按你的办法试一次，完成后汇报哈
> > > 
> > > 
> > > 这次报错是
> > > 
> > > * curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/shadowsocks-libev-3.3.1.tar.gz
> > >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > >   Dload  Upload   Total   Spent    Left  Speed
> > >   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to downloads.openwrt.org port 443: Network is unreachable
> > >   Download failed.
> > >   我能自己下载shadowsocks-libev-3.3.1.tar.gz，拷贝到dl目录下吗？
> > 
> > 
> > 可以的，然后在执行，make -j1 V=s
> 
> ![image](https://user-images.githubusercontent.com/45396912/68657478-c782c900-056e-11ea-9914-e70356a70f63.png)
> 成了，谢谢！！！

看了一下今天L大的代码貌似已经修复了4.19内核编译mac80211错误的问题了，你可以更新最新代码编译4.19的试下。

**Comment by GitMasterArm** [comment]
> > > > > > > 是下面的动作吗：
> > > > > > > 1.git clone [https://github.com/coolsnowwolf/lede命令下载好源代码](https://github.com/coolsnowwolf/lede%E5%91%BD%E4%BB%A4%E4%B8%8B%E8%BD%BD%E5%A5%BD%E6%BA%90%E4%BB%A3%E7%A0%81)
> > > > > > > 2.通过WinSCP找到Makefile文件，修改保存
> > > > > > > 3.再进入PuTTY，执行。/scripts/feedsupdate -a以后的命令吗？
> > > > > > 
> > > > > > 
> > > > > > 已经编译过的:
> > > > > > rm -rf ./tmp
> > > > > > rm -rf ./staging_dir
> > > > > > rm -rf ./build_dir
> > > > > > rm -rf ./bin
> > > > > > 然后修改Makefile，在编译就可以。
> > > > > 
> > > > > 
> > > > > 按你的办法试一次，完成后汇报哈
> > > > 
> > > > 
> > > > 这次报错是
> > > > 
> > > > * curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/shadowsocks-libev-3.3.1.tar.gz
> > > >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > > >   Dload  Upload   Total   Spent    Left  Speed
> > > >   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (7) Failed to connect to downloads.openwrt.org port 443: Network is unreachable
> > > >   Download failed.
> > > >   我能自己下载shadowsocks-libev-3.3.1.tar.gz，拷贝到dl目录下吗？
> > > 
> > > 
> > > 可以的，然后在执行，make -j1 V=s
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45396912/68657478-c782c900-056e-11ea-9914-e70356a70f63.png)
> > 成了，谢谢！！！
> 
> 看了一下今天L大的代码貌似已经修复了4.19内核编译mac80211错误的问题了，你可以更新最新代码编译4.19的试下。

好，我试一下。

**Comment by GitMasterArm** [comment]
> x64一直都是4.19编译的，和选那个内核没什么关系.
> 默认编译一遍就好

默认编译一次成功了，我要再添加或删除组件怎么做，请高手指点一下呀

**Comment by TerryWang159** [comment]
> > x64一直都是4.19编译的，和选那个内核没什么关系.
> > 默认编译一遍就好
> 
> 默认编译一次成功了，我要再添加或删除组件怎么做，请高手指点一下呀

1.  命令  make menuconfig    
2  选择你要的插件或者组件， 
3 网络如果不好的话，请预下载一下文件（在dl 文件夹下），命令 make download V=s ,失败的文件手动下载 放到dl文件下 。 如果你的网络足够好，也可以忽略这一步直接进入第四步.
4.  命令 make -j1 V=s

**Comment by iamggs** [comment]
经典mac80211错误，解决办法看：
https://github.com/coolsnowwolf/lede/issues/2254
