### ISSUE TITLE
BaiduPCS-go 无法下载源码，编译失败

### ISSUE THREAD

**Issue by txx6843046** [coolsnowwolf/lede#2057]
机器已经科学上网了，编译过程中切换几次下载路径都无法下载源码。如图：
![abcd](https://user-images.githubusercontent.com/53639028/68637952-10208f00-053b-11ea-9a26-0db31777b01b.png)

**Comment by lyin888** [comment]
手动下载后扔进dl目录重新编译

**Comment by txx6843046** [comment]
> 手动下载后扔进dl目录重新编译

我用浏览器访问了这些目录下面，根本就没有这个源码文件了

**Comment by Kinodi** [comment]
> > 手动下载后扔进dl目录重新编译
> 
> 我用浏览器访问了这些目录下面，根本就没有这个源码文件了

https://github.com/liuzhuoling2011/baidupcs-web/releases  这里下载
