### ISSUE TITLE
ZeroTier未设置接口直接开启导致网络被防火墙封死。

### ISSUE THREAD

**Issue by ZqinKing** [coolsnowwolf/lede#2059]
/etc/zerotier.start 脚本中未校验zt0是否取到对应的zerotier接口。导致防火墙配置异常，进而导致网络无法使用。只能重刷。

**Comment by ju0594** [comment]
我也是开了zerotier直接就连不上只能重刷，我还以为是和什么东西冲突，原来如此呀~

**Comment by oudoubleyang** [comment]
ZeroTier 建议不装luci界面 按照[官方wiki](https://github.com/mwarning/zerotier-openwrt/wiki) 进行配置 难度不高也更稳定

**Comment by ZqinKing** [comment]
> 我也是开了zerotier直接就连不上只能重刷，我还以为是和什么东西冲突，原来如此呀~

先建一个接口，在配置号防火墙，在开启Zerotier就不会异常

**Comment by ZqinKing** [comment]
> 我也是开了zerotier直接就连不上只能重刷，我还以为是和什么东西冲突，原来如此呀~

先建一个接口，在配置号防火墙，在开启Zerotier就不会异常
