### ISSUE TITLE
点击：查看流量：，系统挂掉 ----

### ISSUE THREAD

**Issue by TerryWang159** [coolsnowwolf/lede#2069]
![image](https://user-images.githubusercontent.com/57702599/68771655-612ba280-0663-11ea-8c12-7a1027fadee7.png)

![image](https://user-images.githubusercontent.com/57702599/68771723-815b6180-0663-11ea-969f-3ccb4dae48b9.png)

错误 LOG 如下： 
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute template dispatcher target for entry '/admin/status/realtime/bandwidth'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'admin_status/bandwidth'.
A runtime error occured: /usr/lib/lua/luci/model/network/proto_4x6.lua:61: attempt to call method 'register_error_code' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by coolsnowwolf** [comment]
不要添加ipv6
