### ISSUE TITLE
R619AC(竞斗云2.0)  2.4G WiFi灯不亮

### ISSUE THREAD

**Issue by lqctanghaolan0** [coolsnowwolf/lede#2072]
R619AC(竞斗云2.0)  2.4G WiFi灯不亮

**Comment by georip** [comment]
的确2.4g WIFI灯不亮

**Comment by AmadeusGhost** [comment]
用大佬源码：https://github.com/LGA1150/openwrt/tree/exp编译即可。

**Comment by lqctanghaolan0** [comment]
> 用大佬源码：[https](https://github.com/LGA1150/openwrt/tree/exp) : [//github.com/LGA1150/openwrt/tree/exp](https://github.com/LGA1150/openwrt/tree/exp)编译即可。

这个我试过，多拨没lean的稳定，自带lean，但是SSR不能用没效果

**Comment by Hnmtc** [comment]
2.4gwifi和sd卡冲突
