### ISSUE TITLE
目前发现装了docker的话单口路由ssr+的udp会变UdpBlocked

### ISSUE THREAD

**Issue by nameless3721** [coolsnowwolf/lede#2074]
![docker](https://user-images.githubusercontent.com/50364156/68860277-90f2ad00-072c-11ea-8d46-89a9cd6f36cb.gif)
弄成伪双口模式就正常 或者不编译docker进去单口也是正常的 NanoPi NEO 2 和x64的虚拟机都能复现

**Comment by irol765** [comment]
> ![码头工人](https://user-images.githubusercontent.com/50364156/68860277-90f2ad00-072c-11ea-8d46-89a9cd6f36cb.gif)
> 弄成伪双口模式就正常或不编译docker进去单口也是正常的NanoPi NEO 2和x64的虚拟机都能复现

我也发现这个问题了，请大佬看看啊。玩游戏很不方便啊。

**Comment by trysh** [comment]
Lean R9.11.23 x86
SSR Plus+
ss节点用客户端测试是支持udp的。但是在SSR Plus+中启用了udp，游戏中的udp却不走代理
