### ISSUE TITLE
factory大小是否有解

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#2075]
以前对factory重来没有质疑过，总以为刷进去，然后update就完事。最近又开始思考factory固件生成问题，试着参考了许多人意见，还是不能生成。
极路由4，我把空间128M全部用上了，update固件发现你选择多少软件，都能生成，唯独factory不出来，目前update32M，factory到底应该设为多大（fw_size），如何生成，请大家指点。

**Comment by ExtremeOrange** [comment]
这个我也遇到过 但是factory并不影响刷机 用sysupgrade一样可以从boot刷机
