### ISSUE TITLE
请问从的lede和openwrt有什么区别？

### ISSUE THREAD

**Issue by viagram** [coolsnowwolf/lede#2081]
一直用你的lede源码编译固件，刚看到你也在维护一个openwrt，请问它们有什么区别？谢谢！

**Comment by outemancut** [comment]
LEDE是17.01后面合并了而已 现在都叫OPENWRT  没有什么区别！

**Comment by viagram** [comment]
> LEDE是17.01后面合并了而已 现在都叫OPENWRT 没有什么区别！
这个我知道，我是问@coolsnowwolf 他这两份源码的区别。大概了解了一下，这样形容：lede是开发版，openwrt是稳定版。不知道这样理解对不对。

**Comment by yinzhefuyun** [comment]
> > LEDE是17.01后面合并了而已 现在都叫OPENWRT 没有什么区别！
> > 这个我知道，我是问@coolsnowwolf 他这两份源码的区别。大概了解了一下，这样形容：lede是开发版，openwrt是稳定版。不知道这样理解对不对。

差不多是这个意思lede和openwrt内容都是openwrt的源码，只不过lede每天都会更新，openwrt一年更新一次

**Comment by Zack0617** [comment]
> > > LEDE是17.01后面合并了而已 现在都叫OPENWRT 没有什么区别！
> > > 这个我知道，我是问@coolsnowwolf 他这两份源码的区别。大概了解了一下，这样形容：lede是开发版，openwrt是稳定版。不知道这样理解对不对。
> 
> 差不多是这个意思lede和openwrt内容都是openwrt的源码，只不过lede每天都会更新，openwrt一年更新一次

这个解释…………

**Comment by viagram** [comment]
@coolsnowwolf 他这几天好像这些忙，lede很少更新了，前段时间一天提交好多。
希望有时间来介绍一下。谢谢。

**Comment by smallprogram** [comment]
lean是基于Openwrt的分支版本，加入一些自己的东西比如SSR plus等，OpenWrt的源代码也是每天都在更新，维护人数也相当多。目前原版OpenWrt稳定版本是18.06，想要稳直接上原版，自己写插件。

**Comment by viagram** [comment]
> lean是基于Openwrt的分支版本，加入一些自己的东西比如SSR plus等，OpenWrt的源代码也是每天都在更新，维护人数也相当多。目前原版OpenWrt稳定版本是18.06，想要稳直接上原版，自己写插件。

我说的lede和openwrt指的是@coolsnowwolf 下的lede和openwrt。

**Comment by smallprogram** [comment]
> > lean是基于Openwrt的分支版本，加入一些自己的东西比如SSR plus等，OpenWrt的源代码也是每天都在更新，维护人数也相当多。目前原版OpenWrt稳定版本是18.06，想要稳直接上原版，自己写插件。
> 
> 我说的lede和openwrt指的是@coolsnowwolf 下的lede和openwrt。

lede是尝鲜版，openwrt是稳定版

**Comment by viagram** [comment]
> > > lean是基于Openwrt的分支版本，加入一些自己的东西比如SSR plus等，OpenWrt的源代码也是每天都在更新，维护人数也相当多。目前原版OpenWrt稳定版本是18.06，想要稳直接上原版，自己写插件。
> > 
> > 
> > 我说的lede和openwrt指的是@coolsnowwolf 下的lede和openwrt。
> 
> lede是尝鲜版，openwrt是稳定版

谢谢解答

**Comment by waynon** [comment]
我发现coolsnowwolf的lede仓库没有fork之前的commit历史，那怎么拉取上游的官方openwrt中的commit？

**Comment by ForgotFun** [comment]
大家如果对OpenWrt开发感兴趣的话，可以关注下佐大的OpenWrt培训班。
https://forgotfun.org/2018/04/openwrt-training-2018.html
