### ISSUE TITLE
SSR Plus+不能使用gfw模式，其他模式正常，求解决

### ISSUE THREAD

**Issue by Eskimocat** [coolsnowwolf/lede#2086]
之前一直用lede的koolss，某天突然发现无法科学上网了，无论什么模式，无奈更换为openwrt，但在使用时发现若使用gfw模式则无法科学上网，其他模式正常，规则已更新，家里使用了两个网管交换机，不过光猫直连也不行，不知道是什么原因，因为经常bt下载，所以很不方便，希望有朋友能帮忙解决，谢谢。

**Comment by Her0R0cket** [comment]
状态里面更新过gfw列表没

**Comment by Eskimocat** [comment]
> 状态里面更新过gfw列表没

更新了，规则是5207

**Comment by Eskimocat** [comment]
更新了
