### ISSUE TITLE
ssr plus+ gfw不能用 其他模式正常

### ISSUE THREAD

**Issue by Eskimocat** [coolsnowwolf/lede#2094]
之前一直用lede的koolss，某天突然发现无法科学上网了，无论什么模式，无奈更换为openwrt，但在使用时发现若使用gfw模式则无法科学上网，其他模式正常，规则已更新，家里使用了两个网管交换机，不过光猫直连也不行，不知道是什么原因，因为经常bt下载，所以很不方便，希望有朋友能帮忙解决，谢谢。

**Comment by icksky** [comment]
是否开了广告屏蔽之类的 好像会冲突

**Comment by Eskimocat** [comment]
确实如此，我用的kpr plus 应该如何设置避免冲突呢

**Comment by Eskimocat** [comment]
> 是否开了广告屏蔽之类的 好像会冲突

确实如此，我用的kpr plus 应该如何设置避免冲突呢

**Comment by icksky** [comment]
记得之前有撇到过 你网上看看 或者等其他人帮你把 我也不懂

**Comment by Eskimocat** [comment]
> 记得之前有撇到过 你网上看看 或者等其他人帮你把 我也不懂

谢谢你，我找一找，大佬用的什么去广告和科学技术

**Comment by WoChen5770** [comment]
kpr plus 有个规则把谷歌和YouTube都屏蔽了，所以上不了

**Comment by Eskimocat** [comment]
> kpr plus 有个规则把谷歌和YouTube都屏蔽了，所以上不了

那应该怎么办呢？

**Comment by WoChen5770** [comment]
> > kpr plus 有个规则把谷歌和YouTube都屏蔽了，所以上不了
> 
> 那应该怎么办呢？

不用kpr啊，不是有adbyby吗

**Comment by Eskimocat** [comment]
感觉不如kpr厉害
