### ISSUE TITLE
K3 无线不能用了, 刷了官改固件没问题, 但是官改不好用 求助

### ISSUE THREAD

**Issue by icksky** [coolsnowwolf/lede#2102]
我怀疑跟我硬件多少有点关系, 之前自编译后是可以用的, 后面不知道为什么 2.4G连不上,  现在干脆5G也不行了. 然后刷了官改. 两个无线都正常, 用了一段时间也没问题. 但是感觉不是很好用. 重点是我发现好像有后门...所以还是希望用回lede. 不知道是不是驱动或者设置的问题呢? 希望有大佬能帮忙解答

**Comment by icksky** [comment]
补充一下: 官改是一个群里下载的, 有可能是二次修改的...

**Comment by shenyz** [comment]
我的最新r9119正常，留个邮箱我发给试试，刷之前最好恢复出厂，然后清空浏览器缓存，刷了后再次恢复出厂

**Comment by icksky** [comment]
> 我的最新r9119正常，留个邮箱我发给试试，刷之前最好恢复出厂，然后清空浏览器缓存，刷了后再次恢复出厂

多谢~ icksky4=>gmail

**Comment by icksky** [comment]
> 我的最新r9119正常，留个邮箱我发给试试，刷之前最好恢复出厂，然后清空浏览器缓存，刷了后再次恢复出厂

@shenyz 多谢~很抱歉这么晚才回复. 我试了一下 2.4G的无线可以出来了, 但是连接不上, 显示**验证错误**. 
PS: 最早的时候我也是可以的, 后面也是出现了验证错误, 再之后干脆2.4G直接不见了.

**Comment by icksky** [comment]
### 找到不能用的原因了

是因为我**插了优盘**, 之所以官改可以用, 是因为官改默认关闭了 USB3.0. 再次感谢 @shenyz 

所以我们这个固件怎么关闭USB3.0啊  我看默认是开启的?
