### ISSUE TITLE
安装后客户端列表为空

### ISSUE THREAD

**Issue by TigerDen96** [coolsnowwolf/lede#2108]
<img src = 'https://ftp.bmp.ovh/imgs/2019/11/2e4b6594ebd18e5e.png' />
已安装全部必要的ipk组件，如上图所示，客户端列表为空，无法进行任何设置。其他例如“服务器节点”、“访问控制”、“高级设置” 等均显示出来并可以设置，请问是什么原因呢？

**Comment by coolsnowwolf** [comment]
不要继承配置
