### ISSUE TITLE
ssr-plus ipt规则需要改进

### ISSUE THREAD

**Issue by rufengsuixing** [coolsnowwolf/lede#2110]
Chain SS_SPEC_WAN_AC (2 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             match-set whitelist dst
SS_SPEC_WAN_FW  all  --  anywhere             anywhere             match-set blacklist dst
SS_SPEC_WAN_FW  all  --  anywhere             anywhere             match-set fplan src
RETURN     all  --  anywhere             ipipipi
SS_SPEC_WAN_FW  all  --  anywhere             anywhere             match-set gfwlist dst
SS_SPEC_WAN_FW  all  --  anywhere             anywhere             match-set gmlan src ! match-set china dst
RETURN     all  --  anywhere             anywhere             match-set china dst
gfwlist模式
每个包要匹配一下china再return 没必要

**Comment by coolsnowwolf** [comment]
因为之前有人恶意将非 gfwlist 的域名提交到 gfwlist
