### ISSUE TITLE
web ui not found some app menu

### ISSUE THREAD

**Issue by buxiaomo** [coolsnowwolf/lede#2112]
I select the luci-app-aria2, aria2ng, and aria2 on `make menuconfig` command , and `make` command not have error message, but i'm not found the aria2 menu in the web ui, what's the problem

![photo_2019-11-21 21 04 01](https://user-images.githubusercontent.com/24752547/69340791-3664ce00-0ca3-11ea-9f5e-eae1e45a7d07.jpeg)

**Comment by buxiaomo** [comment]
I try to delete the `/tmp/luci-indexcache` file, but is not ok

**Comment by EnnawYang** [comment]
跟我树莓派4B一样，没有网络硬盘选项

**Comment by buxiaomo** [comment]
samba have this problem too

**Comment by buxiaomo** [comment]
> 跟我树莓派4B一样，没有网络硬盘选项

How did you solve it

**Comment by EnnawYang** [comment]
> > 跟我树莓派4B一样，没有网络硬盘选项
> 
> How did you solve it
no（

**Comment by EnnawYang** [comment]
> > 跟我树莓派4B一样，没有网络硬盘选项
> 
> How did you solve it

No （

**Comment by EnnawYang** [comment]
> samba have this problem too

“网络硬盘”选项下的app都不会显示，我之前编译过好几次都是这样，我现在换了设备了不知道有没有修复

**Comment by buxiaomo** [comment]
> > samba have this problem too
> 
> “网络硬盘”选项下的app都不会显示，我之前编译过好几次都是这样，我现在换了设备了不知道有没有修复

some time, I saw samba on this menu, but more time I not found it

**Comment by KFERMercer** [comment]
不兼容luci2 需要手动切换到services下

**Comment by EnnawYang** [comment]
> 不需要自己手动添加luci-app-aria2, luci trunk 本身就有这个插件.
> 
> lean/openwrt下的aria2不兼容luci2, 硬要用的话需要在源码中手动切换到services下

那类似于asmba、kodexploer、硬盘休眠之类的也需要这么操作对吧

**Comment by KFERMercer** [comment]
嗯

**Comment by buxiaomo** [comment]
> 不需要自己手动添加luci-app-aria2, luci trunk 本身就有这个插件.
> 
> lean/openwrt下的aria2不兼容luci2, 硬要用的话需要在源码中手动切换到services下

how to change the app to services mode

**Comment by coolsnowwolf** [comment]
不要漏了 vsftp 的 luci

**Comment by buxiaomo** [comment]
> 不要漏了 vsftp 的 luci

 i select luci-app-vsftp, this ok , but samba and aria2 is not ok

**Comment by buxiaomo** [comment]
how to change the app to services mode

**Comment by EnnawYang** [comment]
> > 不要漏了 vsftp 的 luci
> 
> i select luci-app-vsftp, this ok , but samba and aria2 is not ok

![Snipaste_2019-11-26_12-39-51](https://user-images.githubusercontent.com/6705663/69599975-e04cad80-1049-11ea-811e-5ceb935523a1.png)
我的加上ftp之后就能正常显示了
