### ISSUE TITLE
最新源码编译后ssr-pluss  v2ray不可用？

### ISSUE THREAD

**Issue by neilxie79** [coolsnowwolf/lede#2113]
最新源码编译出来的固件，ssr-plus节点类型只能用shadowsocksR模式了？只有这一种选项，v2ray模式不支持了？ 设备是orange pi zero plus
![image](https://user-images.githubusercontent.com/40767986/69346607-0a9b1580-0cae-11ea-91ab-d71d8f079218.png)

**Comment by mrclock** [comment]
默认没编译V2的啊。你勾选了吗？

**Comment by neilxie79** [comment]
确实没有勾选，之前编译的时候默认是编译V2的。谢谢！我回家在试试。
