### ISSUE TITLE
Newifi-D2 今天也是不能正常启动

### ISSUE THREAD

**Issue by hgh188** [coolsnowwolf/lede#2116]
昨天Revert "kernel: bump to 4.9.202, 4.14.154, 4.19.84"就正常  今天又不能正常启动了

**Comment by hgh188** [comment]
翻出miwifi-mini试了试   也是一样

**Comment by ntlf9t** [comment]
自己把mac80211降回去

**Comment by coolsnowwolf** [comment]
git pull 后再编译，把 ttl 日志传上来

**Comment by coolsnowwolf** [comment]
已修复
