### ISSUE TITLE
现在系统都支持什么万兆网卡~那个小螃蟹2.5G支持不

### ISSUE THREAD

**Issue by evilchris** [coolsnowwolf/lede#2119]
其实我就来问个问题....
现在系统都支持什么万兆网卡
那个小螃蟹2.5G支持不

**Comment by pV-nRT** [comment]
自己编译的时候扒一扒驱动，我记得有支持一些10G和40G的网卡，关键看你是什么网卡型号

**Comment by coolsnowwolf** [comment]
不支持的， RTL8125 需要 Linux 5.2 内核，除非 backport 吧

**Comment by coolsnowwolf** [comment]
已经backport 支持了 ， r8125 驱动
