### ISSUE TITLE
建议把argon主题更新到最新版

### ISSUE THREAD

**Issue by li-xunhuan** [coolsnowwolf/lede#2121]
## 建议把argon主题更新到最新版

**Comment by outemancut** [comment]
自己去下载源码自己替换再自己编译就是了

**Comment by DavidDen** [comment]
> ## 建议把argon主题更新到最新版

你可以修改源码然后直接发PR，lean合并即可

**Comment by L-vivi** [comment]
默认主题是netgear，设置为其他主题，每次设备重启都会恢复为默认主题

**Comment by Biggulu** [comment]
> 默认主题是netgear，设置为其他主题，每次设备重启都会恢复为默认主题

`/etc/uci-defaults/30_luci-theme-netgear`
删除或者编辑成自己喜欢的主题即可

**Comment by RainCat1998** [comment]
> > 默认主题是netgear，设置为其他主题，每次设备重启都会恢复为默认主题
> 
> `/etc/uci-defaults/30_luci-theme-netgear`
> 删除或者编辑成自己喜欢的主题即可

感谢
