### ISSUE TITLE
大雕，ACC启动后在系统日志出现失败的提示，请问什么情况？有什么影响吗？见截图！

### ISSUE THREAD

**Issue by zxlhhyccc** [coolsnowwolf/lede#2124]
![M{D4O}8ZICV18L7%@JI5RBM](https://user-images.githubusercontent.com/45259624/69435688-fec95500-0d7a-11ea-8762-5b2d010ee478.png)

**Comment by coolsnowwolf** [comment]
你缺了一个补丁

**Comment by zxlhhyccc** [comment]
> 你缺了一个补丁

请问大雕缺少哪个补丁？
