### ISSUE TITLE
科学网络里面访问控制，黑白名单填写了没有作用呢？

### ISSUE THREAD

**Issue by realsteam** [coolsnowwolf/lede#2128]
想强制某个域名走科学网络，但是无论填写黑还是白名单都没作用呢？

**Comment by realsteam** [comment]
不太清楚到底是白名单是强制走，还是黑名单是强制走，能否给个说明呢。我黑白名单都添加过，貌似都不行，没有效果

**Comment by DavidDen** [comment]
> 不太清楚到底是白名单是强制走，还是黑名单是强制走，能否给个说明呢。我黑白名单都添加过，貌似都不行，没有效果

黑走代理，白不走
Black list website will be proxy, white list website will go directly.

**Comment by realsteam** [comment]
> > 不太清楚到底是白名单是强制走，还是黑名单是强制走，能否给个说明呢。我黑白名单都添加过，貌似都不行，没有效果
> 
> 黑走代理，白不走
> Black list website will be proxy, white list website will go directly.

谢谢解答
