### ISSUE TITLE
[x64]R9.11.23+ssr plus 1.125下更新V2ray订阅失败

### ISSUE THREAD

**Issue by iamggs** [coolsnowwolf/lede#2132]
1、今日下午全新编译的R9.11.23，核心是4.19.85，ssr plus下添加v2ray订阅链接后更新提示：

`Sat Nov 23 19:57:49 2019 user.err shadowsocksr_subscribe[17072]: https://***** 订阅数据获取失败 错误代码: 8`

2、同一个订阅地址，在旧环境R9.10.24+ssr plus 1.125下更新、使用正常；
3、尝试从更新正常的R9.10.24通下过刷写新固件的方式升级到R9.11.23，v2ray重现订阅失败；
4、现已退回到R9.10.24，使用正常。

**Comment by EnnawYang** [comment]
我的没问题

**Comment by iamggs** [comment]
> 我的没问题

你是用今天下午最新的代码编译的x64的R9.11.23么？我这儿用这个无论是全新部署，还是旧固件升级上来都会重现这个问题。更觉给ssr plus无关，ssr plus的代码很久没改动过了。

**Comment by iamggs** [comment]
找到问题所在了，来补个说明：
在后一版的编译中，选中了ipv6helper，部署后自动启用了ipv6支持，在ssr+中更新订阅列表时，主动解析成了ipv6，而订阅服务器不支持ipv6，所以导致无法下载更新列表。
