### ISSUE TITLE
lean解答一下吧，我对于这个问题很困惑

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#2134]
一直都是在恩山下载别人编译好的openwrt
但是我发现有的是可以直接用主路由翻墙的，这种op一个局域网只能有一个，因为如果有2个绑架主路由就会网络怪怪的
还有另外一种是必须用op的ip作为网关才可以翻墙。这种你一个局域网想要启用几个就启用几个。
请问这两种方式的op，究竟在编译的过程中是哪个选项导致会挟持主路由和不挟持主路由

lean能否在百忙中抽空解答一下

**Comment by vaxoyik58** [comment]
这个和编译的选项没关系吧，第一种就是正常的路由通过WAN连接上级，第二种是旁路由通过LAN连接同级。

**Comment by norikohxb** [comment]
这个是哪个选项或者哪个功能叫什么名字？现在恩山的编译好的几乎也就是两种了。

**Comment by JoeHoy233** [comment]
网络，防火墙，自定义规则，把
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
去掉就不会劫持dns了

**Comment by norikohxb** [comment]
这个代码应该是去掉dns劫持的
那么那个网关劫持呢？
怎么破？
