### ISSUE TITLE
openwrt固件samba和ftp查看FAT32格式U盘文件中文乱码

### ISSUE THREAD

**Issue by yu13740000** [coolsnowwolf/lede#2136]
如题，刷了好多版本的openwrt固件，samba和ftp查看u盘文件，只要中文名字的就乱码，U盘文件系统FAT32，百度搜了很多方法都没有解决办法。
硬路由上Pandorabox和老毛子固件，同样这个U盘，不乱码。
请大佬指点一下。

**Comment by yu13740000** [comment]
root@OpenWrt:~# umount /mnt/sdb1
root@OpenWrt:~# mount -t vfat -o iocharset=utf8 /dev/sdb1  /mnt/sdb1
这种临时挂载utf8的方法是可以显示中文的，但是一重启路由，或者拔插U盘后就又乱码了

**Comment by z826540272** [comment]
系统,挂载点,重新添加挂载,修改挂载参数

**Comment by yu13740000** [comment]
感谢支招，刚刚试了一下，还是乱码，请问你自己测试过吗？

**Comment by HiGarfield** [comment]
挂载点参数改为
iocharset=utf8,umask=0000,dmask=0000,fmask=0000

**Comment by yu13740000** [comment]
请问这个参数加在哪里

**Comment by HiGarfield** [comment]
> 请问这个参数加在哪里

/etc/fstab

**Comment by yu13740000** [comment]
感谢，测试了一下，挂载参数添加了iocharset = utf8在u盘插上重启openwrt后，确实能显示中文，但是热拔插U盘后就还是乱码了

**Comment by coolsnowwolf** [comment]
auto-fs 的锅，别编译进去

**Comment by yu13740000** [comment]
谢谢

**Comment by yu13740000** [comment]
谢谢大雕兄！

**Comment by zhg-em** [comment]
> 谢谢大雕兄！

编译菜单中找不到auto-fs的选项呀！

**Comment by ferre-han** [comment]
auto-fs 是个什么鬼

**Comment by likingzi** [comment]
我也遇见了类似问题,加上iocharacter也不行
