### ISSUE TITLE
群炸了

### ISSUE THREAD

**Issue by 12101111** [coolsnowwolf/lede#2139]
RT，README里的群中午炸了

**Comment by carrtohu** [comment]
刚发现，炸了，说是违规被封。不知道一个技术群哪个老哥违的规。有啥新动向吗？

**Comment by EnnawYang** [comment]
> 刚发现，炸了，说是违规被封。不知道一个技术群哪个老哥违的规。有啥新动向吗？

README已更新群号

**Comment by carrtohu** [comment]
> 
> 
> > 刚发现，炸了，说是违规被封。不知道一个技术群哪个老哥违的规。有啥新动向吗？
> 
> README已更新群号

看到了，又是5元😂
