### ISSUE TITLE
最近的版本用opkg装软件报错如图

### ISSUE THREAD

**Issue by fujie-xiyou** [coolsnowwolf/lede#2143]
![image](https://user-images.githubusercontent.com/23140941/69491860-0ea97c00-0ed6-11ea-899b-9ee68e94cb1c.png)
貌似是一些东西编译的时候依赖版本很高  然后源里面安装软件依赖低版本。。。这导致编译完几乎再装不成任何软件了。。。

**Comment by hcym** [comment]
编译前都想好，别说大雕的，官方1806稳定版安装什么驱动也是七死八活

**Comment by fujie-xiyou** [comment]
> 编译前都想好，别说大雕的，官方1806稳定版安装什么驱动也是七死八活

哦哦，这样啊  懒得编译想用现成的，结果缺好多东西。。。不过以前版本至少装个curl 不至于报错。。现在已经严峻到这种地步了吗。。

**Comment by Her0R0cket** [comment]
和官方源包名不一致,只有一个包的话可以强制安装

**Comment by fujie-xiyou** [comment]
> 和官方源包名不一致,只有一个包的话可以强制安装

好吧  我试试看  谢谢你
