### ISSUE TITLE
SSR +的V2ray加密方式，allowInsecure，TLS导入参数时不正确

### ISSUE THREAD

**Issue by willaytoun** [coolsnowwolf/lede#2155]
刷11月24号l大编译的固件（openwrt-R9.11.24-x64-combined-squashfs）
1、V2用网址导入时实际是AUTO（导入是NONE），allowInsecure实际是√（导入没有），TLS实际是√ （引入没有）
2、下面的Url是随便填测试几个参数问题，不能正常连接:，如果需要正常用的可以私发作者做测试
具体信息如下图：
3、另外用Url导入节点不保存直接点[返回至概况]-->[未保存配置]-->[放弃]-->[返回]，页面直接崩溃
固件概况
![11 25概况](https://user-images.githubusercontent.com/43229736/69514333-e24d3880-0f85-11ea-9cfd-c19db92c64b9.png)
V2ray客户端导入时参数
![v2客户端参数](https://user-images.githubusercontent.com/43229736/69514793-779cfc80-0f87-11ea-9e4b-7b6581b9aac1.png)
SSR+导入时问题
![11 25v2导入参数时](https://user-images.githubusercontent.com/43229736/69514814-8be0f980-0f87-11ea-9a14-60841f49d111.png)
测试用的Url：vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIua1i+ivleWvvOWFpeWPguaVsCjkuI3lj6/ov54pIiwNCiAgImFkZCI6ICJhYmMuc2F2ZWZpbGUudGsiLA0KICAicG9ydCI6ICI4MDgwIiwNCiAgImlkIjogIjM2NGNlODFjLTcyNjAtNDNlYi1hZmVkLTg0YzI1N2NkY2MxMyIsDQogICJhaWQiOiAiMiIsDQogICJuZXQiOiAid3MiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAid3d3LmJhaWR1LmNvbSIsDQogICJwYXRoIjogIi92MnJheSIsDQogICJ0bHMiOiAidGxzIg0KfQ==

**Comment by LitCcc** [comment]
确实是这样，需要手动修改，另外最好给关键参数打下码

**Comment by willaytoun** [comment]
这些参数都已经改过了并不能连接，你那边用手机看概况里接口以下会不会出现抖动

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/70590587-29862b00-1c0e-11ea-86c0-1605cf6e7dea.png)
自己解密看就知道了，并没有你说的auto和 insecure

**Comment by willaytoun** [comment]
这就奇怪了，您用windows的v2rayN导入看一下，加密方式确实是auto，allowInsecure有可能是默认的话是true。ws+tls加密方式为auto我用v2rayN和ssr+试过很多次了，解密也确实是您的那样，但是二者导入后的参数就是不一样。
