### ISSUE TITLE
那个DNS加速，能否在LUCI加上控制缓存时间

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#2156]
那个DNS加速，能否在LUCI加上控制缓存时间，可能是因为可能是照顾比较差性能的路由，所以好像刷新时间设置的比较长，但是在X86上，这个性能可以不用考虑，所以是否能做个可以自己设置刷新时间的呢？

**Comment by MxCen** [comment]
能支持TCP和端口，TLS就更好了哈哈
