### ISSUE TITLE
更新后eth显示仍未解决

### ISSUE THREAD

**Issue by EnnawYang** [coolsnowwolf/lede#2160]
#2153 具体的还是这个问题

**Comment by L-vivi** [comment]
恢复出厂设置试试

**Comment by hcym** [comment]
x86的都正常，两个千兆口图标看得怪怪的。包括内置ar无线网卡都行，n1的无线反而挂了

**Comment by ldy8182** [comment]
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/3886648/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/3886649/default.txt)
开机后刚开始可以显示eth和信息，切换别的界面再切回来就不显示了
![shou](https://user-images.githubusercontent.com/24645236/69542181-db461a80-0fc5-11ea-8ec7-e31b95b036f0.png)

**Comment by ldy8182** [comment]
最新版解决问题了

**Comment by EnnawYang** [comment]
> 最新版解决问题了

刚刚那个吗  我晚点试试

**Comment by EnnawYang** [comment]
> 最新版解决问题了

还是一样

**Comment by yocosweet** [comment]
> 一样

刚编译。跟你一样的情况

**Comment by lesliedu** [comment]
现在还是这样，Exsi虚拟机

**Comment by coolsnowwolf** [comment]
make clean

**Comment by EnnawYang** [comment]
> make clean

我每次编译之前都会make clean的
