### ISSUE TITLE
LXC Containers 无法获取Template列表

### ISSUE THREAD

**Issue by gaoruiqiang3003** [coolsnowwolf/lede#2163]
点击后无任何反应。x86-64的

**Comment by slitilanber** [comment]
改清华源

**Comment by zhg-em** [comment]
x86-64的是没有问题的，但x86-32的确实无法获取Template列表 ！

**Comment by gaoruiqiang3003** [comment]
> 改清华源
用的就是清华的
mirrors.tuna.tsinghua.edu.cn/lxc-images
但x86-64的是不行的。已经测试过好几个版本了，
ARMv7 Processor rev 4 (v7l) x 4这个架构是正常的。

**Comment by slitilanber** [comment]
别考虑列表了，直接下载镜像下来，永不失败
