### ISSUE TITLE
“网络储存”菜单不显示

### ISSUE THREAD

**Issue by P3TERX** [coolsnowwolf/lede#2166]
去掉`luci-app-vsftpd`后编译，`网络储存`菜单不显示。
![image](https://user-images.githubusercontent.com/25927179/69592254-56dcb180-1030-11ea-801d-11dc6118b23f.png)

**Comment by EnnawYang** [comment]
#2112

**Comment by star-o0O** [comment]
依赖luci-app-vsftpd
