### ISSUE TITLE
编译固件没选vpn，为什么ipsec的进程还会启动呢

### ISSUE THREAD

**Issue by 82kg** [coolsnowwolf/lede#2167]
![TIM图片20191126102743](https://user-images.githubusercontent.com/31686230/69594650-f5b8dc00-1037-11ea-9650-612bcfd499f3.png)
如图上述两个进程，luci都没vpn 还是会启动。

![TIM截图20191126102943](https://user-images.githubusercontent.com/31686230/69594772-5a743680-1038-11ea-83dd-9283a9a19cd2.jpg)
不用VPN的话 ，防火墙里的这两个规则可以删掉么

**Comment by Her0R0cket** [comment]
luci只是web界面,你取消了luci-app,但没取消它所依赖的应用

**Comment by kktt007** [comment]
我也看到了。我们取消的只是他的luci-app，但是系统最小配合和你选择的依赖需要他。Lean大的固件其实蛮精简的了。我这个强迫症也不挑剔了。你看默认需要设置的都被lean强制选择了。

**Comment by 82kg** [comment]
> 我也看到了。我们取消的只是他的luci-app，但是系统最小配合和你选择的依赖需要他。Lean大的固件其实蛮精简的了。我这个强迫症也不挑剔了。你看默认需要设置的都被lean强制选择了。

我把这两个进程关掉了，好像也没啥影响么，防火墙里的这两个规则可以删除么

**Comment by EnnawYang** [comment]
vpn没有需求的话network里面可以取消掉的

**Comment by 82kg** [comment]
> vpn没有需求的话network里面可以取消掉的

我以为只要luci里取消掉就行了，多谢啊
