### ISSUE TITLE
ryzen patch导致的编译失败？

### ISSUE THREAD

**Issue by lifetyper** [coolsnowwolf/lede#2169]
刚跟新的版本，编译失败，看log似乎是patch文件的问题？

Applying /home/lifetyper/lede/target/linux/x86/patches-4.19/011-tune_lzma_options.patch using plaintext:
patching file scripts/Makefile.lib
patching file arch/x86/include/asm/boot.h

Applying /home/lifetyper/lede/target/linux/x86/patches-4.19/100-fix_cs5535_clockevt.patch using plaintext:
patching file drivers/clocksource/cs5535-clockevt.c

Applying /home/lifetyper/lede/target/linux/x86/patches-4.19/200-pcengines-apu2-reboot.patch using plaintext:
patching file arch/x86/kernel/reboot.c

Applying /home/lifetyper/lede/target/linux/x86/patches-4.19/700-fix-ryzen-tr3-mce.patch using plaintext:
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/arch/x86/kernel/cpu/mce/amd.c b/arch/x86/kernel/cpu/mce/amd.c
|index 4f790c375580..ee0f211b5074 100644
|--- a/arch/x86/kernel/cpu/mce/amd.c
|+++ b/arch/x86/kernel/cpu/mce/amd.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patch unexpectedly ends in middle of line
Patch failed!  Please fix /home/lifetyper/lede/target/linux/x86/patches-4.19/700-fix-ryzen-tr3-mce.patch!
Makefile:29: recipe for target '/home/lifetyper/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.85/.prepared_afa800306a0f3bcd85f11643a300b9ed' failed
make[4]: *** [/home/lifetyper/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.85/.prepared_afa800306a0f3bcd85f11643a300b9ed] Error 1
make[4]: Leaving directory '/home/lifetyper/lede/target/linux/x86'
Makefile:13: recipe for target 'compile' failed
make[3]: *** [compile] Error 2

**Comment by pV-nRT** [comment]
我也出现了同样得错误
