### ISSUE TITLE
[bug]斐讯K3无线驱动信道设置问题

### ISSUE THREAD

**Issue by PaTTeeL** [coolsnowwolf/lede#217]
斐讯K3，昨晚刚刷的lede，默认把无线设置的channel改成了auto，设了个密码，其他都没动，保存之后无线死活都是未启动，折腾了半天发现原来是信道设置问题，2.4g只要设置在1-11以外（12、13和auto），无线就无法启动，模式也是Client，改成AP（也就是Master）也没用，就是无线没信号而且保持Client模式，5G也是一样的毛病，现在就只能都手工设置信道。求修复auto和超出11以外的设置问题~~

**Comment by pchaos** [comment]
无线国家类别设置的是什么？

**Comment by highfly22** [comment]
我也遇到了相同问题。无线国家类别设置了CN，US，AU都不行。

k2p mleaf的1.5版也遇到了这个情况，但是可以通过设置Support Channel来解决。
