### ISSUE TITLE
ESXi虚拟里添加5个及以上的网口时显示不正常

### ISSUE THREAD

**Issue by yocosweet** [coolsnowwolf/lede#2170]
ESXi虚拟里添加5个及以上的网口时显示不正常

**Comment by EnnawYang** [comment]
我的是实体机，四个网口，最后一个接口显示不正常

**Comment by yocosweet** [comment]
> 我的是实体机，四个网口，最后一个接口显示不正常

如果添加4个网口，最后一个显示半双工，如果添加5个网口，概况界面的内存，接口等界面不显示

**Comment by coolsnowwolf** [comment]
运行 ethinfo

**Comment by dolphinpaopao** [comment]
![eth](https://user-images.githubusercontent.com/20945941/69617852-d3dd4a80-1073-11ea-9efe-489391528db7.png)
![ifconfig](https://user-images.githubusercontent.com/20945941/69617863-d770d180-1073-11ea-9506-b42bd7a4274c.png)
共3个网口，同样问题，最后一个没有使用的网口显示不正常。

**Comment by dolphinpaopao** [comment]
![log](https://user-images.githubusercontent.com/20945941/69618302-a47b0d80-1074-11ea-86ce-9f0d259f6953.png)
![net](https://user-images.githubusercontent.com/20945941/69618307-a6dd6780-1074-11ea-9f63-c38ab0fc7677.png)

**Comment by coolsnowwolf** [comment]
你们都在用老版本

**Comment by dolphinpaopao** [comment]
> 你们都在用老版本

老大，今天早上才全新git pull编译的啊，刚看了今天下午好像又更新了，我晚上再试试后汇报。

**Comment by coolsnowwolf** [comment]
估计是从第5个网口开始的显示代码有问题。话说你们真变态啊，有需要那么多wan 么

**Comment by dolphinpaopao** [comment]
> 估计是从第5个网口开始的显示代码有问题。话说你们真变态啊，有需要那么多wan 么

我只有3个网口，网上的成品软路由很多都是4网口或者更多啊。
