### ISSUE TITLE
Ubuntu 14.04 编译后生成不了sysupgrade 和 factory 文件

### ISSUE THREAD

**Issue by daqinKnight** [coolsnowwolf/lede#2171]
主机型号 NETGEAR WNR2200　架构 Atheros AR7241
用Ubuntu 14.04.1 编译
编译成功，但是编译成功后如下图：没有生成sysupgrade 和 factory 这个包。。 请问是否有解？
![image](https://user-images.githubusercontent.com/30095839/69610789-793df180-1067-11ea-95ce-0b44065791ae.png)

**Comment by coolsnowwolf** [comment]
固件太大了

**Comment by daqinKnight** [comment]
@coolsnowwolf  boss  能否把默认固件搞到8M 内，小路由没办法弄啊。。

**Comment by coolsnowwolf** [comment]
你改好后提交
