### ISSUE TITLE
6网口主机，首页的CPU内存网口信息无法显示

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#2172]
我注意到系统日志里有这么两行，希望对修复bug有帮助
Tue Nov 26 14:32:24 2019 daemon.notice procd: /etc/rc.d/S99autocore: net.core.rps_sock_flow_entries = 16384
Tue Nov 26 14:32:24 2019 daemon.notice procd: /etc/rc.d/S99autocore: /etc/rc.common: line 34: can't create /tmp/sysinfo/model: nonexistent directory

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/69648918-300d9200-10a7-11ea-8afd-602c84e7027d.png)

**Comment by coolsnowwolf** [comment]
修复了，支持无穷个网卡的显示了

**Comment by BOBINIUNIU** [comment]
感谢回复，我把之前的代码都删掉，重新git clone，正在编译，等下测试bug是否修复
P.S 大佬们现在都是用的万兆设备了吗。。。
