### ISSUE TITLE
qemu-ga BUG

### ISSUE THREAD

**Issue by cntzjjs** [coolsnowwolf/lede#2179]
make menuconfig  选中了 qemu-ga
编译中提示失败：lede\build_dir\target-x86_64_musl\qemu-4.1.1\ipkg-install\ qemu-ga 4.1.1-x86./ipk无此文件
编译失败

**Comment by cntzjjs** [comment]
解决办法：
0c08379 (https://github.com/project-openwrt/lean-lede/commit/0c08379d80c7718c7da7d560bfb578bc205fe224): 

qemu-ga: fix path by LEAN-ESX中
修改 utils/qemu/Makefile：

$(INSTALL_BIN) $(PKG_INSTALL_DIR)/qemu-ga $(1)/usr/bin为
$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/qemu-ga $(1)/usr/bin
即可

**Comment by iamggs** [comment]
mark一下，我也需要qemu-ga.
