### ISSUE TITLE
编译时暂停，出现选项TSX enable mode

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#2185]
编译时暂停,出现三个选项
TSX enable mode
1. off (X86_INTEL_TSX_MODE_OFF) (NEW)
2. on (X86_INTEL_TSX_MODE_ON) (NEW)
3. auto (X86_INTEL_TSX_MODE_AUTO) (NEW)
choice[1-3?]:
必须要手动选择一下才会继续编译，之前没有这种情况的

![VirtualBox_Ubuntu_27_11_2019_11_52_43](https://user-images.githubusercontent.com/21336893/69692498-36cef000-110d-11ea-97d9-8aee26d4a36d.png)

**Comment by coolsnowwolf** [comment]
这个是 Intel 的最新漏洞补丁，自己选下要安全还是要 AMD

**Comment by BOBINIUNIU** [comment]
代码是重新clone的，换了ubuntu 14 编译仍然有这个问题，希望大佬看一下。

**Comment by BOBINIUNIU** [comment]
Intel TSX 技术 爆出有安全问题，我是选择的OFF，能自动选择就好了，要不每次编译的时候都在这里停住。谢大佬回复。

**Comment by yunjie-li** [comment]
请问下这个是否可以通过修改相关配置来默认选择？我想在fork的代码中修改为自动选择，这样才能云编译
