### ISSUE TITLE
x86-64编译失败，4.9内核

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#2186]
全新git clone编译的，已经试过3次了，同样的错误
![VirtualBox_Ubuntu_27_11_2019_12_39_35](https://user-images.githubusercontent.com/21336893/69694395-916b4a80-1113-11ea-9e79-1d33d164fcb2.png)

**Comment by jeremy168** [comment]
做一次make clean重編看看
再不行我都砍掉整個lede重來一次,我這幾天不知道重頭幾十次囉!

**Comment by BOBINIUNIU** [comment]
找到原因了，是我选择组件的问题，去掉wpad 那个组件就好了
