### ISSUE TITLE
编译MD5不同

### ISSUE THREAD

**Issue by shellwewasw** [coolsnowwolf/lede#2187]
请教一下，同一个.config连续编译3次，为什么每次的md5都会不一样？MD5不是只和内容有关吗？
难道每次文件都不一样吗？
每次都是make -j1 V=s
![Snipaste_2019-11-27_15-11-48](https://user-images.githubusercontent.com/58248234/69701607-47d92a80-1128-11ea-9ac3-ba19b080134c.png)

**Comment by coolsnowwolf** [comment]
对的

**Comment by vaxoyik58** [comment]
有想法。。。从来没考虑过这种问题。。。。

**Comment by redchenjs** [comment]
每次编译生成的img都略有不同，比如说kernel的生成时间戳
