### ISSUE TITLE
ACRH17无线加密选择WPA2-PSK/WPA3-SAE Mixed Mode模式不显示加密方式

### ISSUE THREAD

**Issue by solionw** [coolsnowwolf/lede#2196]
![image](https://user-images.githubusercontent.com/39520925/69786538-9a344d00-11f5-11ea-8cd5-cb9e5eac7733.png)
![image](https://user-images.githubusercontent.com/39520925/69786571-a91aff80-11f5-11ea-9135-965bd9326ec9.png)

**Comment by coolsnowwolf** [comment]
暂时不支持 mixed
