### ISSUE TITLE
能否请教下怎么在LEDE snap里添加您的自定义包?

### ISSUE THREAD

**Issue by juyyao** [coolsnowwolf/lede#22]
能否请教下怎么在LEDE snap里添加您的自定义包?
我拉进package后在make menuconfig菜单里死活找不到您的自定义包,不知为啥?

**Comment by coolsnowwolf** [comment]
先更新 feed

**Comment by coolsnowwolf** [comment]
这个不会的，将 lean 整个文件夹拉进去 package 即可

**Comment by AndyX-Net** [comment]
楼主删除tmp文件夹然后再清理feeds试试.

rm -rf ./tmp/
./scripts/feeds clean -a
./scripts/feeds update -a
./scripts/feeds install -a
