### ISSUE TITLE
[需求]LEDE的DHCP服务器高级设置中新增DHCP option force项

### ISSUE THREAD

**Issue by PaTTeeL** [coolsnowwolf/lede#220]
在interface的lan设置中，dhcp服务器的高级选项是可以设置DHCP 选项（DHCP option）的，但因为iptv的缘故，需要设置3项dhcp option，分别为：
dhcp-option-force=125,00:00:00:00:10:02:06:48:47:57:2d:43:54:0a:02:20:00:0b:02:00:55
dhcp-option=28
dhcp-option=15
其中的28和15都没有问题，但无法在管理页面实现dhcp-option-force，写入的125选项虽然dhcp包测试中可以获取，但实际4K IPTV在获取DHCP地址时无法辨认125选项，IPTV组播的内网IP（也就是VLAN）获取失败，请求在管理页面加入DHCP option force的录入框，方便更多的人配置iptv的内网认证信息。

**Comment by Igloo302** [comment]
支持一下
