### ISSUE TITLE
OpenWrt CI 在线集成编译环境使用教程

### ISSUE THREAD

**Issue by KFERMercer** [coolsnowwolf/lede#2200]
# 借助 GitHub Actions 的 OpenWrt 在线集成自动编译.

## 实时编译状态: [![Build](https://img.shields.io/github/workflow/status/coolsnowwolf/lede/OpenWrt-CI/master)](https://github.com/coolsnowwolf/lede/actions?query=workflow%3AOpenWrt-CI)

支持自动定制固件, 自动调整依赖及生成配置文件, 无需上传配置. 兼容 [coolsnowwolf/lede](https://github.com/coolsnowwolf/lede) 以及 OpenWrt trunk.

同时支持自动合并推送上游提交 (也就是自动更新), 直接把`merge-upstream.yml`放入`.github/workflows/`即可 (默认上游为 coolsnowwolf/lede, 高级玩家请自行改写).

感谢[P3TERX](https://github.com/P3TERX/Actions-OpenWrt)珠玉在前.

---

> ### 这个CI脚本和[P3TERX/Actions-OpenWrt](https://github.com/P3TERX/Actions-OpenWrt)的同样是云编译, 有什么不同?

这个 CI 脚本可以帮助你在你的 OpenWrt 分支下构建当前库的Op固件, 无需上传配置文件, 不依赖外挂配置脚本, 真正的一次配置终生使用.

P3TERX/Actions-OpenWrt 的优势在于, 其可以独立于文件库存在, 可以快速搭建起可用的编译配置; 同时对新手极其友好. 但是由于 OpenWrt make configure 自身机制的缘故, 生成的配置文件鲁棒性较差, 需要经常重新生成上传配置, 有形中加重了维护负担, 使得使用起来不是很`优雅`, **但是强烈建议基础薄弱的玩家使用.**

> ### 这个CI脚本适合哪些人?

- 正在维护自己的 OpenWrt 分支的大佬/初学者/玩家 (可以快速测试自己的代码)
- 伸手党
- 没有精力维持一个专用编译机的佛系人士

### 在一切开始前, 你需要的是:

- GitHub 账号
- 申请使用 GitHub Actions
- [基本的Git技能](https://www.liaoxuefeng.com/wiki/896043488029600)
- 自己的OpenWrt分支 ([Lean源](https://github.com/coolsnowwolf/lede)或者[官方源](https://github.com/openwrt/openwrt/))
- 脑子

### 相关文章: 作者-糖炒栗子 

- [面向小白的Github_Action使用workflow自动编译lean_openwrt教程](https://zhuanlan.zhihu.com/p/94402324)
- [关于Github Action自动编译Lean_Openwrt的配置修改问题](https://zhuanlan.zhihu.com/p/94527343)

### 4. 定制固件:

> 如果你希望定制你的固件:

代码里的注释部分详细介绍了如何在脚本中客制化你的固件. 简单来说, 你只需要解除注释相应行即可.

我已经准备一个[正确的编写示例](https://github.com/KFERMercer/OpenWrt-by-lean/blob/CI-demo/.github/workflows/openwrt-ci.yml), 此配置基于 Lean 最新代码, 开启了所有预先写好的定制选项, 同时已经[经过测试](https://github.com/KFERMercer/OpenWrt-by-lean/commit/d31390d3e7b5f178d4e3456d401ded557c207398/checks?check_suite_id=334570354)可用. 如果你缺乏对自己的信心, 可以随意借鉴.

### 5. 大功告成.

集成编译环境会自动开始编译. 现在返回你的库首页, 点击页面上方的`Actions`按钮就可以查看进度.

> ### 如何下载到编译完成的固件?

进入`Actions`标签页后, 如果相应的集成活动顺利完成 (显示为绿色), 点击页面右上方的`Artifacts`即可看到你的固件 (通常是一个压缩包). 点击即可开始下载.

**Comment by pingod** [comment]
我的workflow一直显示 (Unnamed workflow),不知道为啥,GitHub官方问题??

**Comment by KFERMercer** [comment]
> 我的workflow一直显示 (Unnamed workflow),不知道为啥,GitHub官方问题??

你改了什么地方?

**Comment by pingod** [comment]
添加了一个workflow示例模板文件,我把这个文件添加或者删除都不行,都是显示Unnamed workflow

**Comment by d975xbx** [comment]
感谢大神，可以删除虚拟机了。

**Comment by lyafancn** [comment]
大佬，我不用X64，你的实例脚本里的x64怎么替换别的CPU(就是给个其他的CPU设备的TARGET_参数列表吧。)不知道哪里有TARGTE_的不同参数。

**Comment by lyafancn** [comment]
![image](https://user-images.githubusercontent.com/53136737/69877736-fb474800-12fd-11ea-8f2e-b7acec4b7c99.png)
我想要修改x64为A53处理器的架构，但是这里貌似没有arm v8

**Comment by redchenjs** [comment]
armv8就是aarch64

**Comment by KFERMercer** [comment]
> ![image](https://user-images.githubusercontent.com/53136737/69877736-fb474800-12fd-11ea-8f2e-b7acec4b7c99.png)
> 我想要修改x64为A53处理器的架构，但是这里貌似没有arm v8

建议直接复制config.seed或者.config最开始的target部分

**Comment by lyafancn** [comment]
> > ![image](https://user-images.githubusercontent.com/53136737/69877736-fb474800-12fd-11ea-8f2e-b7acec4b7c99.png)
> > 我想要修改x64为A53处理器的架构，但是这里貌似没有arm v8
> 
> 建议直接复制config.seed或者.config最开始的target部分

我强烈建议您再写一个文档，列出不同设备的这个部分：
![image](https://user-images.githubusercontent.com/53136737/69878966-38610980-1301-11ea-8e6c-c2240a4581ce.png)

**Comment by lyafancn** [comment]
![image](https://user-images.githubusercontent.com/53136737/69879433-64c95580-1302-11ea-9ca7-7f965b8bfc1d.png)
只需要这三项对吗？其他的像这样的要吗？
CONFIG_TARGET_BOARD="sunxi"
CONFIG_TARGET_SUBTARGET="cortexa53"
CONFIG_TARGET_PROFILE="DEVICE_sun50i-h5-nanopi-neo2"
CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"

**Comment by lyafancn** [comment]
CONFIG_TARGET_PREINIT_IFNAME=""
CONFIG_TARGET_PREINIT_IP="192.168.1.1"
CONFIG_TARGET_PREINIT_NETMASK="255.255.255.0"
CONFIG_TARGET_PREINIT_BROADCAST="192.168.1.255"
CONFIG_TARGET_INIT_PATH="/usr/sbin:/usr/bin:/sbin:/bin"
CONFIG_TARGET_INIT_ENV=""
CONFIG_TARGET_INIT_CMD="/sbin/init"
CONFIG_TARGET_INIT_SUPPRESS_STDERR=y
还有这些要吗？

**Comment by KFERMercer** [comment]
> ![image](https://user-images.githubusercontent.com/53136737/69879433-64c95580-1302-11ea-9ca7-7f965b8bfc1d.png)
> 只需要这三项对吗？其他的像这样的要吗？
> CONFIG_TARGET_BOARD="sunxi"
> CONFIG_TARGET_SUBTARGET="cortexa53"
> CONFIG_TARGET_PROFILE="DEVICE_sun50i-h5-nanopi-neo2"
> CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"

比如要编译ACRH 17的固件, 只需要这两行:
```
CONFIG_TARGET_ipq40xx=y
CONFIG_TARGET_ipq40xx_DEVICE_asus_rt-acrh17=y
```

**Comment by lyafancn** [comment]
> > CONFIG_TARGET_PREINIT_IFNAME=""
> > CONFIG_TARGET_PREINIT_IP="192.168.1.1"
> > CONFIG_TARGET_PREINIT_NETMASK="255.255.255.0"
> > CONFIG_TARGET_PREINIT_BROADCAST="192.168.1.255"
> > CONFIG_TARGET_INIT_PATH="/usr/sbin:/usr/bin:/sbin:/bin"
> > CONFIG_TARGET_INIT_ENV=""
> > CONFIG_TARGET_INIT_CMD="/sbin/init"
> > CONFIG_TARGET_INIT_SUPPRESS_STDERR=y
> > 还有这些要吗？
> 
> 不需要.
> 
> > ![image](https://user-images.githubusercontent.com/53136737/69879433-64c95580-1302-11ea-9ca7-7f965b8bfc1d.png)
> > 只需要这三项对吗？其他的像这样的要吗？
> > CONFIG_TARGET_BOARD="sunxi"
> > CONFIG_TARGET_SUBTARGET="cortexa53"
> > CONFIG_TARGET_PROFILE="DEVICE_sun50i-h5-nanopi-neo2"
> > CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53"
> 
> 对. 通常来说你在menuconfig下需要做出多少次选泽就需要多少行, 所以nanopi 2只需要这三行就够了:
> 
> ```
> CONFIG_TARGET_sunxi_cortexa53_DEVICE_sun50i-h5-nanopi-neo2=y
> CONFIG_TARGET_sunxi_cortexa53=y
> CONFIG_TARGET_sunxi=y
> ```
> 
> 比如要编译ACRH 17的固件, 只需要这两行:
> 
> ```
> CONFIG_TARGET_ipq40xx=y
> CONFIG_TARGET_ipq40xx_DEVICE_asus_rt-acrh17=y
> ```

我觉得这些都背不下来，所有设备的。。。您看看再写个这块的所有设备参数文档？嘻嘻嘻嘻

**Comment by KFERMercer** [comment]
> 我觉得这些都背不下来，所有设备的。。。您看看再写个这块的所有设备参数文档？嘻嘻嘻嘻
我也没背, 需要什么设备只需要去make一个配置文件看一下就好了啊, 反正这种事是一劳永逸的.

**Comment by lyafancn** [comment]
> > 我觉得这些都背不下来，所有设备的。。。您看看再写个这块的所有设备参数文档？嘻嘻嘻嘻
> 
> 我也没背, 需要什么设备只需要去make一个配置文件看一下就好了啊, 反正这种事是一劳永逸的.
> 话说回来, 配置选项的命名仔细看一下你就会发现规律.

嗯嗯。
那我再问下几个问题：
1.我配置的自定义的Neo2固件编译，那么可以同时再添加一个编译其他的设备固件的workflow脚本吗？（可以的话，是怎么添加呢？在workflow目录下新建一个其他的比如op-acrh17.yml就可以了？）
2.FORK一次代码后，任意一个workflow脚本都可以自动同步大雕的commit并且开始按照脚本编译吗？不需要重新FORK吧?.....我不太会用git，不知道怎么同步大雕的源码且不覆盖我的自定义的workflow的yml。

**Comment by pingod** [comment]
现在可以了,是GitHub官方的锅
https://www.githubstatus.com/incidents/39ynqr1xb3s0

**Comment by KFERMercer** [comment]
> > > 我觉得这些都背不下来，所有设备的。。。您看看再写个这块的所有设备参数文档？嘻嘻嘻嘻
> > 
> > 
> > 我也没背, 需要什么设备只需要去make一个配置文件看一下就好了啊, 反正这种事是一劳永逸的.
> > 话说回来, 配置选项的命名仔细看一下你就会发现规律.
> 
> 嗯嗯。
> 那我再问下几个问题：
> 1.我配置的自定义的Neo2固件编译，那么可以同时再添加一个编译其他的设备固件的workflow脚本吗？（可以的话，是怎么添加呢？在workflow目录下新建一个其他的比如op-acrh17.yml就可以了？）
> 2.FORK一次代码后，任意一个workflow脚本都可以自动同步大雕的commit并且开始按照脚本编译吗？不需要重新FORK吧?.....我不太会用git，不知道怎么同步大雕的源码且不覆盖我的自定义的workflow的yml。

① 对
② 不能, 需要手动合并. 这个脚本专注当前库, 如果想要代码, 可以再脚本中添加一个拉取代码的命令, 但是我不建议你这么做. 同步上游不会覆盖下游更改.


> 现在可以了,是GitHub官方的锅
> https://www.githubstatus.com/incidents/39ynqr1xb3s0

github的bug都让你找着了😂

**Comment by z826540272** [comment]
> > > > 我觉得这些都背不下来，所有设备的。。。您看看再写个这块的所有设备参数文档？嘻嘻嘻嘻
> > > 
> > > 
> > > 我也没背, 需要什么设备只需要去make一个配置文件看一下就好了啊, 反正这种事是一劳永逸的.
> > > 话说回来, 配置选项的命名仔细看一下你就会发现规律.
> > 
> > 
> > 嗯嗯。
> > 那我再问下几个问题：
> > 1.我配置的自定义的Neo2固件编译，那么可以同时再添加一个编译其他的设备固件的workflow脚本吗？（可以的话，是怎么添加呢？在workflow目录下新建一个其他的比如op-acrh17.yml就可以了？）
> > 2.FORK一次代码后，任意一个workflow脚本都可以自动同步大雕的commit并且开始按照脚本编译吗？不需要重新FORK吧?.....我不太会用git，不知道怎么同步大雕的源码且不覆盖我的自定义的workflow的yml。
> 
> ① 对
> ② 不能, 需要手动合并. 这个脚本专注当前库, 如果想要代码, 可以再脚本中添加一个拉取代码的命令, 但是我不建议你这么做. 同步上游不会覆盖下游更改.
> 
> 如果你只是想编译最新固件, 可以用[P3TERX/Actions-OpenWrt](https://github.com/P3TERX/Actions-OpenWrt)
> 
> > 现在可以了,是GitHub官方的锅
> > https://www.githubstatus.com/incidents/39ynqr1xb3s0
> 
> github的bug都让你找着了😂

4点同时编译,GitHub算力被撸完

**Comment by d975xbx** [comment]
如果大雕源码更新，要怎么自动编译？

**Comment by BROBIRD** [comment]
每个项目每个月只有2000分钟的免费时间，如果每天都运行一次的话，是不够用的。

**Comment by KFERMercer** [comment]
> 每个项目每个月只有2000分钟的免费时间，如果每天都运行一次的话，是不够用的。

请问可否提供一下信息来源?
我查到的文档里是这样说明的, 没有看到每月使用时间相关的限制:
![image](https://user-images.githubusercontent.com/37098748/69903665-8a745e80-13d7-11ea-9f6d-fced92f6a42a.png)

**Comment by BROBIRD** [comment]
@KFERMercer 抱歉看错了，上述限制是针对私有仓库的

**Comment by d975xbx** [comment]
大神，怎么在CI脚本中添加pull上游代码的动作？

**Comment by z826540272** [comment]
> 大神，怎么在CI脚本中添加pull上游代码的动作？

你用另一个脚本就是最新版编译

**Comment by d975xbx** [comment]
这个吗？https://github.com/P3TERX/Actions-OpenWrt

**Comment by xunqiuhuiyi** [comment]
谢谢UP主的分享 想请教下 如果我拥有多台路由 是否可以同时自动化编译多个固件呢？还是说需要建立多个自动编译化脚本？如果我修改了openwrt-ci.yml 在Action建立多个脚本 更新以后 他是按照我最近修改还是？

**Comment by KFERMercer** [comment]
> 谢谢UP主的分享 想请教下 如果我拥有多台路由 是否可以同时自动化编译多个固件呢？还是说需要建立多个自动编译化脚本？如果我修改了openwrt-ci.yml 在Action建立多个脚本 更新以后 他是按照我最近修改还是？主要是我不太会使用git 如果我workflow目录下创建多个.yml脚本，是不是workflow脚本都可以自动同步大雕的commit并且开始按照脚本编译呢？

同时建立多个flow, 每个flow都会执行. 不过既然你不太会用git, 那这种需求建议使用[P3TERX/Actions-OpenWrt](https://github.com/P3TERX/Actions-OpenWrt).

**Comment by adaaaaaa** [comment]
老哥，不行啊。。。你最近一次改代码之后，GG了。。。

` Uploading artifact 'OpenWrt firmware' from '/home/runner/work/lede/lede/artifact/' for run #21
Uploading 0 files
File upload complete.
Uploaded '0' bytes from '/home/runner/work/lede/lede/artifact/' to server`

固件大小直接为0了。。。

**Comment by KFERMercer** [comment]
> 老哥，不行啊。。。你最近一次改代码之后，GG了。。。
> 
> ` Uploading artifact 'OpenWrt firmware' from '/home/runner/work/lede/lede/artifact/' for run #21 Uploading 0 files File upload complete. Uploaded '0' bytes from '/home/runner/work/lede/lede/artifact/' to server`
> 
> 固件大小直接为0了。。。

刚才又更新了,, 之前一条命令写错了

**Comment by adaaaaaa** [comment]
不行啊，你是说前6，7小时那个改动吗？。。。还是这样啊。。。😂😂😂
你那边可以了？？

**Comment by KFERMercer** [comment]
> 不行啊，你是说前6，7小时那个改动吗？。。。还是这样啊。。。😂😂😂
> 你那边可以了？？

刚刚更新

**Comment by adaaaaaa** [comment]
好的，我又去抄作业了。。。😂😂😂

**Comment by adaaaaaa** [comment]
你确定这次没问题了吧？？😂😂😂

**Comment by KFERMercer** [comment]
> 你确定这次没问题了吧？？😂😂😂

刚看了下你的CI, 写的非常山炮. 建议去看小白教程: https://github.com/coolsnowwolf/lede/issues/2225

**Comment by adaaaaaa** [comment]
结合你们两家所长啊。。。怎么就山炮了呢？？😂😂😂

**Comment by KFERMercer** [comment]
> 结合你们两家所长啊。。。怎么就山炮了呢？？😂😂😂

基本语法都错了

**Comment by adaaaaaa** [comment]
最初的模板就是你的呢。。。整个编译过程也没有报错啊？？🙃

**Comment by adaaaaaa** [comment]
给个栗子我看看哪里不对了？？

**Comment by adaaaaaa** [comment]
除了中间加一点插件，软件，驱动。。。其他基本完全照抄啊。。。😂😂😂

**Comment by KFERMercer** [comment]
> 最初的模板就是你的呢。。。整个编译过程也没有报错啊？？🙃

>给个栗子我看看哪里不对了？？

>除了中间加一点插件，软件，驱动。。。其他基本完全照抄啊。。。😂😂😂

我怀疑你这个编出来的配置根本就不会生效, 而且有多个包之间互相冲突. 如果你不需要某项配置, 除了你想强制关闭应该在后面添加` is not set`外, 其余的应该就直接删掉对应行而不是注释.

**Comment by adaaaaaa** [comment]
收到，谢谢，我马上去改。。。至少也是简介好看一点。。。😂😂😂

**Comment by adaaaaaa** [comment]
对了，我设置是计划9点UTC，每星期五执行的，为什么没有生效，而是立刻就开始编译了呢？？

**Comment by adaaaaaa** [comment]
老哥，好像还是不太行哦。。。编译出的固件大小有问题。。。之前都是190多M的，现在只剩90多了。。。无论是按照你后来让我改的，还是之前照你修改的配置文件改的。。。都是一样大小。。。
然后，压缩包解压出错。。。

**Comment by KFERMercer** [comment]
> 老哥，好像还是不太行哦。。。编译出的固件大小有问题。。。之前都是190多M的，现在只剩90多了。。。无论是按照你后来让我改的，还是之前照你修改的配置文件改的。。。都是一样大小。。。
> 然后，压缩包解压出错。。。

![image](https://user-images.githubusercontent.com/37098748/69964417-5c188f80-154d-11ea-862d-f57457a89874.png)

**Comment by adaaaaaa** [comment]
cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_PAD=y
          CONFIG_VDI_IMAGES=y
          EOF

这里有什么问题不？为什么不能编译出VDI镜像？

**Comment by powskey** [comment]
# 编译ipq40XX固件:

          # cat >> .config <<EOF

          # CONFIG_TARGET_ipq40xx=y

          # CONFIG_TARGET_ipq40xx_DEVICE_p2w_r619ac-128m=y

          # EOF
我这样写的，为什么编译出来的不是竞斗云的固件？是不是哪里错了？

**Comment by redchenjs** [comment]
就因为这个CI好多萌新乱开PR都开到官方OpenWrt上去了

**Comment by z826540272** [comment]
> 就因为这个CI好多萌新乱开PR都开到官方OpenWrt上去了

说实话这ci难用多此一举，不如原来的那个

**Comment by KFERMercer** [comment]
> 就因为这个CI好多萌新乱开PR都开到官方OpenWrt上去了

今天新加了自动更新CI, 不再需要手动pr了.

**Comment by adaaaaaa** [comment]
能不能把编译时候实际用到的config文件也导出来，一起打包下载了？？
这次看到又添加了一些新的驱动，这些是我不需要的。。。
我想要下次编译的时候，禁止这些新的驱动添加到固件里面。。。
但是，我又不想在本地启动虚拟机来git pull。。。我都打算删掉虚拟机了。。。

**Comment by kang-mk** [comment]
牛逼感谢

**Comment by peter-tank** [comment]
照着撸了个最近的官包，打128M 大内存补丁后的 WNDR4300 和 WNDR3700 好像哪里不对，2小时后出来 firmware 600M，熟悉的[指点指点](https://github.com/peter-tank/openwrt/blob/v19.07.0-rc2_netgear_wndr/.github/workflows/main.yml)

**Comment by KFERMercer** [comment]
> 照着撸了个最近的官包，打128M 大内存补丁后的 WNDR4300 和 WNDR3700 好像哪里不对，2小时后出来 firmware 600M，熟悉的[指点指点](https://github.com/peter-tank/openwrt/blob/v19.07.0-rc2_netgear_wndr/.github/workflows/main.yml)

槽点太多以至于不知道从哪里开始吐. 

简单来说就是逻辑混乱, 拉取了错误的库到错误的位置, 配置文件根本没有, 加上你的CI和你的库不兼容. 但是神奇的是, 最后的编译失败并不是CI脚本造成的. 

玩转高阶操作之前, 希望能做好前期知识积累.


> 能不能把编译时候实际用到的完整版的config文件也导出来，一起打包下载了？？
> 这次看到又添加了一些新的驱动，这些是我不需要的。。。
> 我想要下次编译的时候，禁止这些新的驱动添加到固件里面。。。
> 但是，我又不想在本地启动虚拟机来git pull。。。我都打算删掉虚拟机了。。。

这个很容易就可以做到. 
说句题外话, 有件事可能需要告诉你一下, 我会更新在最近你提的那个issue里, 希望你这段时间能保持留意.

**Comment by bonnyandsky** [comment]
你好，请问怎么把你的merge-upstream.yml文件放到我的目录下？我看好像没办法下载，

**Comment by peter-tank** [comment]
@KFERMercer 怎么从trunk抓指定tag的版本 ？
我从 github 和 git.openwrt.org clone 或wget *.tar.gz 后 git checkout 各种玩法，死活都是内核不对版。。。只有 master 才是最正确的

**Comment by KFERMercer** [comment]
> @KFERMercer 怎么从trunk抓指定tag的版本 ？
> 我从 github 和 git.openwrt.org clone 或wget *.tar.gz 后 git checkout 各种玩法，死活都是内核不对版。。。只有 master 才是最正确的

由于没看到错误信息所以猜不出来

**Comment by sunlanhao** [comment]
你好，请问我想通过云编译加入魔改版的ssr，这样添加代码可以吗？ 
![S@%~V0A} DBH%ZA)XE)LP5M](https://user-images.githubusercontent.com/30642187/70383829-8b952500-19af-11ea-9691-7af1337de301.png)
![jo](https://user-images.githubusercontent.com/30642187/70383828-8afc8e80-19af-11ea-9d7b-97e47bbb5369.png)

**Comment by KFERMercer** [comment]
> 你好，请问我想通过云编译加入魔改版的ssr，这样添加代码可以吗？
> ![S@%~V0A} DBH%ZA)XE)LP5M](https://user-images.githubusercontent.com/30642187/70383829-8b952500-19af-11ea-9691-7af1337de301.png)
> ![jo](https://user-images.githubusercontent.com/30642187/70383828-8afc8e80-19af-11ea-9d7b-97e47bbb5369.png)

不知道, 没用过这个

**Comment by i6o6i** [comment]
Nano pi R1s的CPU的配置在哪？

**Comment by bonnyandsky** [comment]
我做了一个分支，名字叫ledenew，我打算以后同步L大的代码都用分支来同步，请问openwrt-ci.yml和merge-upstream.yml需要修改对应那些字段

**Comment by Crazy365** [comment]
请教大佬，我在编译时需要手动输入一个 Y 进行确认（见下面日志），现在自动化无法输入，导致编译失败。不知有没有办法自动输入？
Support legacy servers which use less secure dialects (CIFS_ALLOW_INSECURE_LEGACY) [Y/n/?] (NEW) aborted!

**Comment by Crazy365** [comment]
@KFERMercer 请教大佬，我在编译时需要手动输入一个 Y 进行确认（见下面日志），现在自动化无法输入，导致编译失败。不知有没有办法自动输入？
Support legacy servers which use less secure dialects (CIFS_ALLOW_INSECURE_LEGACY) [Y/n/?] (NEW) aborted!

**Comment by KFERMercer** [comment]
> @KFERMercer 请教大佬，我在编译时需要手动输入一个 Y 进行确认（见下面日志），现在自动化无法输入，导致编译失败。不知有没有办法自动输入？
> Support legacy servers which use less secure dialects (CIFS_ALLOW_INSECURE_LEGACY) [Y/n/?] (NEW) aborted!

已修复

**Comment by Crazy365** [comment]
> > @KFERMercer 请教大佬，我在编译时需要手动输入一个 Y 进行确认（见下面日志），现在自动化无法输入，导致编译失败。不知有没有办法自动输入？
> > Support legacy servers which use less secure dialects (CIFS_ALLOW_INSECURE_LEGACY) [Y/n/?] (NEW) aborted!
> 
> 已修复

还是过不去，这里好像必须有输入才行。

**Comment by KFERMercer** [comment]
加一行:
```
CONFIG_CIFS_ALLOW_INSECURE_LEGACY=y
```

**Comment by Crazy365** [comment]
> > 还是过不去，这里好像必须有输入才行。
> 
> 加一行:
> 
> ```
> CONFIG_CIFS_ALLOW_INSECURE_LEGACY=y
> ```

试了一下，还是不行

**Comment by peter-tank** [comment]
```yml

    - name: Firmware build_env keys set
      uses: actions/cache@master
      id: build_env
      with:
        path: .
        key: ${{ runner.os }}-openwrt-build-${{ hashFiles('**/.config') }}

    - name: Try make package/pkg/compile in cache
      if: steps.build_env.outputs.cache-hit != 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        make package/nun-lean-pkg/compile source=path/to/source V=s

```
这样是不是就可以利用之前有编译环境增加编译自己的包？应该还不到2G限制吧。

**Comment by KFERMercer** [comment]
> 试了一下，还是不行

手里k3没法测试. 真不行就把`V=s`删掉. 会强制选择默认. 

> ```yaml
>     - name: Firmware build_env keys set
>       uses: actions/cache@master
>       id: build_env
>       with:
>         path: .
>         key: ${{ runner.os }}-openwrt-build-${{ hashFiles('**/.config') }}
> 
>     - name: Try make package/pkg/compile in cache
>       if: steps.build_env.outputs.cache-hit != 'true'
>       env:
>         DEBIAN_FRONTEND: noninteractive
>       run: |
>         make package/nun-lean-pkg/compile source=path/to/source V=s
> ```
> 
> 这样是不是就可以利用之前有编译环境增加编译自己的包？应该还不到2G限制吧。

image builder..理论上可以.. 但是如果大雕修改工具链之类的话可能会翻车...

我没试过所以没发言权

**Comment by peter-tank** [comment]
那暂时还是指定自己的SDK，单独编译了。
```yml

    - name: Dowload SDK
      env:
        DIY_SH: 'diy.sh'
        DEBIAN_FRONTEND: noninteractive
        suites: 352651872
        artifacts: 647105
        base: 'https://github.com/peter-tank/openwrt'
        src: 'Openwrt\ SDK/openwrt-sdk-ar71xx-nand_gcc-7.5.0_musl.Linux-x86_64.tar.xz'
      run: |
        git rm -frq -- .
        git reset -q -- $DIY_SH
        git checkout -q -- $DIY_SH
        wget -q -T30 -Osdk.zip.o "$base/suites/$suites/artifacts/$artifacts"
        unzip -l sdk.zip.o
        (unzip -C -p sdk.zip.o "$src") | (tar -xJf -)
        mv openwrt*/* ./
        ls -la
```

**Comment by peter-tank** [comment]
下载SDK单独编译GFW相关的包，花费的时间40分钟左右(包括前10分钟固定的主机环境配置)，在SDK环境再跑cacke麻烦不说，意义也不大：
- Post Openwrt sdk_env keys set 1m 45s
  - [warning]Cache size of ~898 MB (941676180 B) is over the 400MB limit, not saving cache.
  1. Post job cleanup.
  1. /bin/tar -cz -f /home/runner/work/_temp/5f03190e-0520-4650-862e-d0bb11cad872/cache.tgz -C /home/runner/work/openwrt/openwrt .
  - [warning]Cache size of ~898 MB (941676180 B) is over the 400MB limit, not saving cache.

**Comment by xinpenghan** [comment]
编译x86框架的，固件里多了一个LED 配置，软路由不需要这个，要怎么删除呢？
加里下面这这些，都不行
# CONFIG_PACKAGE_kmod-ledtrig-gpio is not set
# CONFIG_PACKAGE_kmod-ledtrig-timer is not set
# CONFIG_PACKAGE_kmod-leds-gpio is not set
# CONFIG_PACKAGE_kmod-ledtrig-default-on is not set
# CONFIG_PACKAGE_kmod-ledtrig-netdev is not set
# CONFIG_PACKAGE_kmod-ledtrig-usbdev is not set
# CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set

**Comment by xinpenghan** [comment]
编译x86，添加以下php环境插件，编译后安装，发现编译后的固件里并没有php环境的以下插件  ，这个要怎么解决呢？       
          CONFIG_PACKAGE_php7-fpm=y
          CONFIG_PACKAGE_php7-mod-curl=y
          CONFIG_PACKAGE_php7-mod-gd=y
          CONFIG_PACKAGE_php7-mod-iconv=y
          CONFIG_PACKAGE_php7-mod-json=y
          CONFIG_PACKAGE_php7-mod-mbstring=y
          CONFIG_PACKAGE_php7-mod-opcache=y
          CONFIG_PACKAGE_php7-mod-session=y
          CONFIG_PACKAGE_php7-mod-zip=y

**Comment by lbbboy** [comment]
[编译错误](https://github.com/lbbboy/lede/commit/d4b6b91ac9c1afe5827031a18874885ef292a094/checks?check_suite_id=365803092)

麻烦帮排查下错误原因，弄了几次没能解决，谢谢。

**Comment by peter-tank** [comment]
> [编译错误](https://github.com/lbbboy/lede/commit/d4b6b91ac9c1afe5827031a18874885ef292a094/checks?check_suite_id=365803092)
> `.config:95:warning: unexpected data: make defconfig 53 Error opening terminal: unknown. 54 /home/runner/work/lede/lede/include/toplevel.mk:136: recipe for target 'menuconfig' failed 55 make[1]: *** [menuconfig] Error 1 56 make[1]: Leaving directory '/home/runner/work/lede/lede' 57 /home/runner/work/lede/lede/include/toplevel.mk:97: recipe for target '.config' failed 58 make: *** [.config] Error 2`

应当像这样保留注释吧：
https://github.com/coolsnowwolf/lede/blob/2252757369baf3c2f526c5c7c3f6e9d57cdd2e79/.github/workflows/openwrt-ci.yml#L100-L105

**Comment by KFERMercer** [comment]
缩进错误

**Comment by xynu617** [comment]
[自动更新lean源码失败](https://github.com/xynu617/lede/actions)

**Comment by KevinZjYang** [comment]
请问这个怎么修改内核呢？

**Comment by KFERMercer** [comment]
> [自动更新lean源码失败](https://github.com/xynu617/lede/actions)
> 从2天前开始的，自动更新的代码没动过

https://github.com/KFERMercer/OpenWrt-CI/issues/36#issuecomment-567799868

> 请问这个怎么修改内核呢？

需要修改文件

**Comment by KevinZjYang** [comment]
@KFERMercer 请问具体咋操作啊，有相关的教程吗？或者要修改的文件在哪里？

**Comment by xinpenghan** [comment]
编译了几次Samba4，都是错误，以及强制不编译Samba了，为什么还是错误呢？

**Comment by yulinsoft** [comment]
> > > 还是过不去，这里好像必须有输入才行。
> > 
> > 
> > 加一行:
> > ```
> > CONFIG_CIFS_ALLOW_INSECURE_LEGACY=y
> > ```
> 
> 试了一下，还是不行

这个问题你解决了吗，我也是困在这里了。

**Comment by llfj** [comment]
CIFS_ALLOW_INSECURE_LEGACY 也是一样 要手动输入Y 无法自动化。。怎么解决

**Comment by dache123** [comment]
> 缩进错误



> 缩进错误

想修改成别的机型该怎么写呢？有范例吗？
