### ISSUE TITLE
softether5在windows上用管理软件登录按钮都是灰色的

### ISSUE THREAD

**Issue by omegatao** [coolsnowwolf/lede#2209]
![image](https://user-images.githubusercontent.com/11746995/69866059-fd99aa00-12dd-11ea-819b-cf0e9d3d1de6.png)
如图，除了本地网桥设置以外其它按钮都是灰色，是软件有什么问题吗？

**Comment by xinxijishuwyq** [comment]
禁用softethervpn5-bridge，或者直接不编译这个包（只编译softethervpn5-server和softethervpn5-libs）

**Comment by omegatao** [comment]
> 禁用softethervpn5-bridge，或者直接不编译这个包（只编译softethervpn5-server和softethervpn5-libs）

按照这个方法完美解决
