### ISSUE TITLE
[需求]斐讯K3：能否在系统概况页面中显示cpu、2.4g芯片和5g芯片的温度？

### ISSUE THREAD

**Issue by PaTTeeL** [coolsnowwolf/lede#221]
貌似在其他openwrt中看到有温度显示，lede中找不到哪里显示温度，唯一能看的温度还是/sys/devices/virtual/thermal/thermal_zone0/temp里面，看不到2.4G和5G芯片的温度，求补充温度读数并显示在系统概况页面中。

**Comment by lyin888** [comment]
同求
