### ISSUE TITLE
能否整合luci-app-acme

### ISSUE THREAD

**Issue by once375ml** [coolsnowwolf/lede#2210]
求整合luci-app-acme，这是我没有放下官方openwrt死心塌地转投你的Lede唯一理由。

**Comment by M1A6I3L** [comment]
有这个的。选择luci-app-uhttpd后luci-app-acme就会出现。

**Comment by lilunxm12** [comment]
> 有这个的。选择luci-app-uhttpd后luci-app-acme就会出现。

我选了也没出现,请问是哪里姿势不对吗?
acme和acme-dnsapi都已经选了
