### ISSUE TITLE
GFW 用户自定义列表没了

### ISSUE THREAD

**Issue by tamplin** [coolsnowwolf/lede#2217]
昨天编译了一下K3，发现没有GFW 用户自定义列表
![image](https://user-images.githubusercontent.com/18260656/69894742-e5b63a80-135e-11ea-8f11-7f940c1f5c88.png)

**Comment by Her0R0cket** [comment]
黑名单了解下

**Comment by hong0980** [comment]
在luci里注释了，要找回来把两个--去了就行，说功能和黑白名单重复了。
