### ISSUE TITLE
编译列表中的zerotier选项不在了

### ISSUE THREAD

**Issue by qiangwushuang** [coolsnowwolf/lede#2218]
最近的源码中luci-app-zerotier选项不在了，web管理界面中也无对应选项，但是运行后台是有zerotier存在的。
![图片](https://user-images.githubusercontent.com/6835840/69894979-d2a56980-1362-11ea-8723-10d6d0471813.png)

**Comment by Aes64X** [comment]
在的，想想你改动了什么东西。

**Comment by qiangwushuang** [comment]
确实是我环境的问题。
