### ISSUE TITLE
SSR功能建议

### ISSUE THREAD

**Issue by JinQzzz** [coolsnowwolf/lede#222]
希望绕过大陆IP可以自定义忽略地址或IP，购物不便。
比如https://cn.gamersgate.com/ 会自动跳到 https://www.gamersgate.com/ ，这两个站货币和价格都不同。

**Comment by 70599** [comment]
这类网站不能穷举，只能你自己添加维护

**Comment by JinQzzz** [comment]
@70599 luci 上加自定义按钮, 谁说穷举了...
