### ISSUE TITLE
qb又编译失败了，新版的编译有问题

### ISSUE THREAD

**Issue by feifan1113** [coolsnowwolf/lede#2220]

**Comment by feifan1113** [comment]
![image](https://user-images.githubusercontent.com/57245399/69895635-1a31f280-136f-11ea-9138-d8047bb183f1.png)

**Comment by Her0R0cket** [comment]
../../../../staging_dir/target-x86_64_musl/usr/include/QtCore/qprocess.h:49:1: error: 'QT_FEATURE_processenvironment' was not declared in this scope
 QT_REQUIRE_CONFIG(processenvironment);
 ^
../../../../staging_dir/target-x86_64_musl/usr/include/QtCore/qprocess.h:49:1: note: suggested alternative: 'QT_FEATURE_process'
In file included from ../../../../staging_dir/target-x86_64_musl/usr/include/QtNetwork/QNetworkAccessManager:1:0,
                 from ./base/net/downloadmanager.h:34,
                 from app/application.cpp:68:
../../../../staging_dir/target-x86_64_musl/usr/include/QtNetwork/qnetworkaccessmanager.h:161:45: error: 'QNetworkRequest::RedirectPolicy' has not been declared
     void setRedirectPolicy(QNetworkRequest::RedirectPolicy policy);
                                             ^~~~~~~~~~~~~~
../../../../staging_dir/target-x86_64_musl/usr/include/QtNetwork/qnetworkaccessmanager.h:162:22: error: 'RedirectPolicy' in 'class QNetworkRequest' does not name a type
     QNetworkRequest::RedirectPolicy redirectPolicy() const;
                      ^~~~~~~~~~~~~~
Makefile:2220: recipe for target 'application.o' failed

完整的是这样的奇怪的是6dcd971 升级4.1.9.1还编译成功,然后73b0fb4降级4.1.9还失败了

**Comment by Her0R0cket** [comment]
应该是支持mips后挂了,早上已经clean了,等等改下makefile到前一版试试

**Comment by Aes64X** [comment]
昨晚编译时 qt5 是正常的，请尝试重新拉取源码，记得保留dl文件，有几个小问题是 qt5 相关的几个依赖下载校验码有误，改skip后正常编译。

**Comment by Her0R0cket** [comment]
qt5正常,这是qbittorrent的

**Comment by feifan1113** [comment]
> 应该是支持mips后挂了,早上已经clean了,等等改下makefile到前一版试试

不搞了 试了编译两次都不行

**Comment by Aes64X** [comment]
make download V=s 一遍，看看有没有回复校验码错误的，我记得有2个，估计是校验错误就没下载。

**Comment by feifan1113** [comment]
> 校验错误

如果找到是检验码错误，那要怎么改才能编译通过？

**Comment by Aes64X** [comment]
> > 校验错误
> 
> 如果找到是检验码错误，那要怎么改才能编译通过？

搜索出错的文件，定位到目录，校验值 =skip  就行了
估计是大雕改了版本号忘记了校验值

**Comment by feifan1113** [comment]
> > > 校验错误
> > 
> > 
> > 如果找到是检验码错误，那要怎么改才能编译通过？
> 
> 搜索出错的文件，定位到目录，校验值 =skip 就行了
> 估计是大雕改了版本号忘记了校验值

![image](https://user-images.githubusercontent.com/57245399/69897677-3d1dd000-138a-11ea-8c68-2efbaa23cc29.png)
这样算不算报错

**Comment by feifan1113** [comment]
> > > > 校验错误
> > > 
> > > 
> > > 如果找到是检验码错误，那要怎么改才能编译通过？
> > 
> > 
> > 搜索出错的文件，定位到目录，校验值 =skip 就行了
> > 估计是大雕改了版本号忘记了校验值
> 
> ![image](https://user-images.githubusercontent.com/57245399/69897677-3d1dd000-138a-11ea-8c68-2efbaa23cc29.png)
> 这样算不算报错

![image](https://user-images.githubusercontent.com/57245399/69897697-7eae7b00-138a-11ea-9f3c-691bbad551cc.png)

**Comment by feifan1113** [comment]
> > > > > 校验错误
> > > > 
> > > > 
> > > > 如果找到是检验码错误，那要怎么改才能编译通过？
> > > 
> > > 
> > > 搜索出错的文件，定位到目录，校验值 =skip 就行了
> > > 估计是大雕改了版本号忘记了校验值
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/57245399/69897677-3d1dd000-138a-11ea-8c68-2efbaa23cc29.png)
> > 这样算不算报错
> 
> ![image](https://user-images.githubusercontent.com/57245399/69897697-7eae7b00-138a-11ea-9f3c-691bbad551cc.png)

仔细看了一下 貌似没报错，算了不搞了 ，等大雕修复

**Comment by EnnawYang** [comment]
建议重新git clone

**Comment by d975xbx** [comment]
actions云编译没问题的

**Comment by zcluo** [comment]
没问题，我之前用ubuntu19一直编译有问题，昨天搞个个ubuntu14 lts64位，没什么毛病了就

**Comment by feifan1113** [comment]
> 没问题，我之前用ubuntu19一直编译有问题，昨天搞个个ubuntu14 lts64位，没什么毛病了就

我二次编译出的问题

**Comment by dovegq** [comment]
ubuntu 19 一样的问题

**Comment by Her0R0cket** [comment]
![图片](https://user-images.githubusercontent.com/33145975/69908726-0e573680-142a-11ea-878e-13a565036bac.png)

CONFIGURE_VARS += \
	QT_QMAKE="$(TOOLCHAIN_DIR)/bin" \
	PKG_CONFIG_PATH="$(TOOLCHAIN_DIR)/lib/pkgconfig"

编译失败的话在qbittorrent的makefile里加上这一段就可以了
我用的ubuntu18.04,看回复好像非16的系统需要这些变量

**Comment by feifan1113** [comment]
> ![图片](https://user-images.githubusercontent.com/33145975/69908726-0e573680-142a-11ea-878e-13a565036bac.png)
> 
> CONFIGURE_VARS +=
> QT_QMAKE="$(TOOLCHAIN_DIR)/bin"
> PKG_CONFIG_PATH="$(TOOLCHAIN_DIR)/lib/pkgconfig"
> 
> 编译失败的话在qbittorrent的makefile里加上这一段就可以了
> 我用的ubuntu18.04,看回复好像非16的系统需要这些变量

我又重建了虚拟机 重新编译，大雕说删除lede重新编译，就怕又不行，

**Comment by Her0R0cket** [comment]
我直接编译失败了,然后加了这段就成功了,然后删了这段编译又失败,最好加上这段生成固件成功

**Comment by Her0R0cket** [comment]
我直接编译失败了,然后加了这段就成功了,然后删了这段编译又失败,最后加上这段生成固件成功

**Comment by feifan1113** [comment]
> 我直接编译失败了,然后加了这段就成功了,然后删了这段编译又失败,最后加上这段生成固件成功

。。。我的机子还在编译。。。。没加这段

**Comment by feifan1113** [comment]
> > 我直接编译失败了,然后加了这段就成功了,然后删了这段编译又失败,最后加上这段生成固件成功
> 
> 。。。我的机子还在编译。。。。没加这段

我现在加上看看  还没到编译QB的部分 应该能赶上

**Comment by feifan1113** [comment]
> 我直接编译失败了,然后加了这段就成功了,然后删了这段编译又失败,最后加上这段生成固件成功

![image](https://user-images.githubusercontent.com/57245399/69910243-dd373000-1442-11ea-9002-6280303c71f1.png)


![image](https://user-images.githubusercontent.com/57245399/69910244-e3c5a780-1442-11ea-8694-079c5452d645.png)
是加到这个吧？

**Comment by Her0R0cket** [comment]
是的,但前面那两条线是什么情况?finalshell按tab键的标志?

**Comment by Her0R0cket** [comment]
刚虚拟机里试了下luci界面配置全了,但是会覆盖webui里的设置,这个就比较尬了

**Comment by feifan1113** [comment]
> 是的,但前面那两条线是什么情况?finalshell按tab键的标志?

我用的Sublime Text2这个软件，能显示makefile的tab符，用来找出导致makefile报错的空格符合

**Comment by feifan1113** [comment]
> 刚虚拟机里试了下luci界面配置全了,但是会覆盖webui里的设置,这个就比较尬了

意思是加的那两段会有问题？

**Comment by Her0R0cket** [comment]
> 
> 
> > 刚虚拟机里试了下luci界面配置全了,但是会覆盖webui里的设置,这个就比较尬了
> 
> 意思是加的那两段会有问题？
不是,这次luci界面完善了,但这样就不能在webui里改了

**Comment by feifan1113** [comment]
> > > 刚虚拟机里试了下luci界面配置全了,但是会覆盖webui里的设置,这个就比较尬了
> > 
> > 
> > 意思是加的那两段会有问题？
> 
> 不是,这次luci界面完善了,但这样在webui里改配置,再启动就被覆盖了

会不会是权限的原因

**Comment by coolsnowwolf** [comment]
建议统一到 ubuntu 14 ，不然这里会有不同的行为

**Comment by Her0R0cket** [comment]
> 
> 
> 建议统一到 ubuntu 14 ，不然这里会有不同的行为


之前一直用的16,这个月才升的18,我是从16复制过来的,16我还是保留了的.
其实就是想试试版本不一样到底有没有差别,没想到会在这个地方翻车!

**Comment by dovegq** [comment]
> > 建议统一到 ubuntu 14 ，不然这里会有不同的行为
> 
> 之前一直用的16,这个月才升的18,我是从16复制过来的,16我还是保留了的.
> 其实就是想试试版本不一样到底有没有差别,没想到会在这个地方翻车!

我一直18编的好好的，也是在qt上翻车了

**Comment by feifan1113** [comment]
> 建议统一到 ubuntu 14 ，不然这里会有不同的行为

![image](https://user-images.githubusercontent.com/57245399/70007527-90229d80-15ab-11ea-9675-3b1273d032fe.png)
二次编译最新的源码，qb会报错，然后用回之前我修改过的makefile就不会报错。很奇怪，对比过更新后的qb的makefile和我手动修改的makefile，也是加的那三行代码，内容一样的，是不是二次编译才会出问题？

**Comment by coolsnowwolf** [comment]
更新 gcc 后解决了
