### ISSUE TITLE
编译成功，ssr+pus中的V2ray用不了

### ISSUE THREAD

**Issue by tristesky** [coolsnowwolf/lede#2233]
我昨天编译好了1900acs固件并成功刷入，SSR能正常使用，但是添加v2ray，会显示v2ray未运行。

**Comment by zxlhhyccc** [comment]
> 我昨天编译好了1900acs固件并成功刷入，SSR能正常使用，但是添加v2ray，会显示v2ray未运行。

v2ray降级吧。。。。4.21.0及以上版本好像有问题。。。

**Comment by eallion** [comment]
我昨天也搞了好久，还以为我是 VPS 坏掉了。

**Comment by weiyongwill** [comment]
> > 我昨天编译好了1900acs固件并成功刷入，SSR能正常使用，但是添加v2ray，会显示v2ray未运行。
> 
> v2ray降级吧。。。。4.21.0及以上版本好像有问题。。。

怎么设置v2ray降级，昨天搞到半夜，没搞好，今天好困

**Comment by dolphinpaopao** [comment]
x86最新编译没有问题

**Comment by iamggs** [comment]
x86下v2ray 4.21.3毫无问题。
