### ISSUE TITLE
请求加入luci-app-rtorrent，凑齐qBittorrent，rtourrent，transmission的webgui三件套

### ISSUE THREAD

**Issue by once375ml** [coolsnowwolf/lede#2235]
地址：https://github.com/wolandmaster/luci-app-rtorrent.git

**Comment by coolsnowwolf** [comment]
有 QBT 就够了， TR 都可以淘汰了其实

**Comment by once375ml** [comment]
> 有 QBT 就够了， TR 都可以淘汰了其实

WNDR4700 跑不动啊

昨晚试了下transmission 调内存，还是觉得QB好用。

QB速度一上来（9MB/s），控制页面都刷不出来了。目前开了512M swap 内存问题不大了 主要是CPU
