### ISSUE TITLE
SSR Plus 的小BUG

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#2253]
就是在新版的V2RAY 的WS+TLS 状态下，端口检测正常，但是在谷歌连通性检查下，是无法连接，但是服务器是实际可用的，在老的版本中没有这个问题。不懂是不是个例或者是BUG？

**Comment by mrtonychz** [comment]
> 就是在新版的V2RAY 的WS+TLS 状态下，端口检测正常，但是在谷歌连通性检查下，是无法连接，但是服务器是实际可用的，在老的版本中没有这个问题。不懂是不是个例或者是BUG？

兄弟，你后来是怎么解决的啊

**Comment by hxlls** [comment]
都什么年代了，更新就完事了，都更新了几十个版本，早没这问题了

**Comment by mrtonychz** [comment]
> 都什么年代了，更新就完事了，都更新了几十个版本，早没这问题了

我貌似还有这个问题。电脑版r2ray也无法访问网站。是我搭建的问题吗，还是我域名的问题
