### ISSUE TITLE
error on line 351 at column 25: AttValue: " or ' expected

### ISSUE THREAD

**Issue by hostage007** [coolsnowwolf/lede#228]
adbyby
酸酸乳
KMS
等插件界面有如下报错

This page contains the following errors:
error on line 351 at column 25: AttValue: " or ' expected
Below is a rendering of the page up to the first error.

生成时间：2017-12-13 00:31:25
版本标识：d669b0caba35ec0f5c0f42eff4abf82b8d95140b
执行主机：nas-zh
主机标签：nas, linux

**Comment by jiechic** [comment]
![fireshot capture 2 - tsk3 - shadowsoc_ - http___192 168 1 1_cgi-bin_luci_admin_services_shadowsocksr](https://user-images.githubusercontent.com/518977/33995181-ca893b40-e0a2-11e7-95e3-ce36e2c79f7c.png)

**Comment by tossp** [comment]
换个主题，不用默认的就没这个提示

**Comment by jiechic** [comment]
对于我们这种不研究主题的人来说，默认足够，所以不知道这个是主题导致的bug，ths 楼上

**Comment by hostage007** [comment]
更新后已解决
