### ISSUE TITLE
强烈要求ShadowSocksR Plus+加入Trojan代理,变四合一

### ISSUE THREAD

**Issue by lqhorochi** [coolsnowwolf/lede#2290]
强烈要求ShadowSocksR Plus+加入Trojan,变四合一.
Trojan代理已经存活了一年多,有需求加入SSR PLUS+插件里
速度和存活几率大都跟V2ray+TLS+CDN差不多,不分上下
希望大雕考虑一下Trojan的加入,大雕可以到Trojan项目了解一下
简单来说就是一个socks5代理!

Trojan项目地址：
   https://github.com/trojan-gfw/trojan

**Comment by coolsnowwolf** [comment]
已初步加入，未测试

**Comment by eallion** [comment]
https://github.com/trojan-gfw/openwrt-trojan

**Comment by github-szhang** [comment]
正确配置之后无法启用

**Comment by github-szhang** [comment]
> 已初步加入，未测试

正确配置后，trojan无法启动，提示配置错误，同样配置小火箭正常

**Comment by rookietribe** [comment]
@coolsnowwolf 
trojan无法启动，显示 `[FATAL] fatal: wrong run_type in config file`

手动修改 `/usr/share/shadowsocksr/gentrojanconfig.lua` 里面的 `run_type`，重新编译，trojan可以启动，无错误输出，但是 XXR Plus 显示未运行。
