### ISSUE TITLE
关于luci-app-cifsd

### ISSUE THREAD

**Issue by chiyu521** [coolsnowwolf/lede#2295]
编译且安装完成了  有两个疑问
这个和原本的SMB冲突不 包括SMB自动挂载
是不是如果只是使用他 可以去掉SMB 3.6 4.0
第二就是使用luci-app-cifsd 按照官方的命令 无法添加用户 和密码
root@OpenWrt:~# cifsadmin -a root
-ash: cifsadmin: not found

**Comment by EnnawYang** [comment]
cifsuseradd -a xxx 不要使用root用户

**Comment by chiyu521** [comment]
我禁用了 SMB3.6&nbsp; 然后&nbsp;单独跑cifsd&nbsp;也按照你说的&nbsp;设置了&nbsp;输入了新的用户名和密码&nbsp;依然不让访问&nbsp;尴尬~~

**Comment by EnnawYang** [comment]
我也有不能访问的问题 也没搜索到相关的配置教程 所以我放弃了

**Comment by hgh188** [comment]
我一样是反复找教程也不能访问  所以只能够也放弃了 WIN 10

**Comment by pk49800** [comment]
我也有同样的问题，可以添加用户但访问不了，用户名密码都是对的
