### ISSUE TITLE
求增加vip视频解析功能

### ISSUE THREAD

**Issue by sevilx** [coolsnowwolf/lede#231]
现在好流行通过链接解析腾讯爱奇艺优酷等视频网站的vip资源，能不能做成一个插件的功能呢把这些视频给解析了，最好可以自定义解析链接，有了这个黑科技就牛X了

**Comment by mjyhj** [comment]
自己把规则编译进去不就好

**Comment by sevilx** [comment]
PC看没问题啊，但是ios，安卓等设备呢？有了这个ipad，手机都能看了啊
