### ISSUE TITLE
请求给一个树莓派4b的openwrt-ci配置

### ISSUE THREAD

**Issue by aaaisan** [coolsnowwolf/lede#2319]
`cat >> .config <<EOF
 CONFIG_TARGET_x86=y
 CONFIG_TARGET_x86_64=y
 CONFIG_TARGET_x86_64_Generic=y
 EOF`
请问这里如何修改？谢谢！

**Comment by lphgor** [comment]
```
CONFIG_TARGET_brcm2708=y
CONFIG_TARGET_brcm2708_bcm2711=y
CONFIG_TARGET_brcm2708_bcm2711_DEVICE_rpi-4=y
```

**Comment by aaaisan** [comment]
> ```
> CONFIG_TARGET_brcm2708=y
> CONFIG_TARGET_brcm2708_bcm2711=y
> CONFIG_TARGET_brcm2708_bcm2711_DEVICE_rpi-4=y
> ```

thx
