### ISSUE TITLE
EA6350v3 could not boot since switch to kernel 4.19.x

### ISSUE THREAD

**Issue by chd1998** [coolsnowwolf/lede#2327]
image is ok,and could flash on the device.
but could not boot...
Is there any solution?  
Thanx in advance!

**Comment by coolsnowwolf** [comment]
ttl log ?

**Comment by chd1998** [comment]
No TTL log, I am using Web GUI to flash the firmware

**Comment by chd1998** [comment]
I switched the kernel to 4.14 again, then it booted and worked
