### ISSUE TITLE
求教如何在云编译的时候加入魔改版的SSR

### ISSUE THREAD

**Issue by sunlanhao** [coolsnowwolf/lede#2338]
已经按照糖炒栗子大神的教程添加了 git clone https://github.com/sunlanhao/luci-app-ssr-plus-jo.git 
请问L大 固件定制部分下面默认的SSR 还需要做什么修改吗？ 
![S@%~V0A} DBH%ZA)XE)LP5M](https://user-images.githubusercontent.com/30642187/70383267-af536d80-19a5-11ea-968b-e72366533255.png)
![4CRJJ00 8IF15}BHVDCJ HF](https://user-images.githubusercontent.com/30642187/70383266-af536d80-19a5-11ea-9e33-aef5bffefe7c.png)

**Comment by EnnawYang** [comment]
包名都不一样好吗 当然要改

**Comment by sunlanhao** [comment]
> 包名都不一样好吗 当然要改
我把名字替换成魔改版的名字可以吗？   这个还需要添加依赖吗
![jo](https://user-images.githubusercontent.com/30642187/70383356-63092d00-19a7-11ea-8d47-d9f03e3558e7.png)

**Comment by EnnawYang** [comment]
> > 包名都不一样好吗 当然要改
> > 我把名字替换成魔改版的名字可以吗？   这个还需要添加依赖吗
> > ![jo](https://user-images.githubusercontent.com/30642187/70383356-63092d00-19a7-11ea-8d47-d9f03e3558e7.png)

依赖不清楚，魔改版的我没用过

**Comment by kang-mk** [comment]
我也想知道

**Comment by sunlanhao** [comment]
> 我也想知道

等大佬来指点迷津

**Comment by saoba1982** [comment]
我也一直没成功加入过软件，不知道怎么回事.
