### ISSUE TITLE
关掉服务器节点订阅和管理仍然会自动更新

### ISSUE THREAD

**Issue by simplove** [coolsnowwolf/lede#2341]
![1](https://user-images.githubusercontent.com/2135481/70385451-3fe27b80-19af-11ea-89af-1838c5da327e.jpg)
自动更新前面的勾取消，每天仍然会更新gfwlist.
这个不起作用呀

**Comment by jxph1123** [comment]
gfwlist更新没毛病，服务器节点不会更新，没问题的

**Comment by simplove** [comment]
> gfwlist更新没毛病，服务器节点不会更新，没问题的
按字面的理解，勾取消之后，**### 不会更新服务器订阅和GFW列表**。
而且重点是我不需要它自动更新GFW列表，这点很关键。

**Comment by coolsnowwolf** [comment]
fixed
