### ISSUE TITLE
opkg相关问题反馈

### ISSUE THREAD

**Issue by MxCen** [coolsnowwolf/lede#2346]
自建了软件源，在线进行opkg安装时候，软件可正常完成安装使用，但是存在报错，不知道是不是脚本指令比较老，但是UCI版本比较新，导致报错。报错截图和SHH内容如下。

SHH中使用OPKG install XXX：

> Configuring adbyby.
> Configuring coreutils-nohup.
> Configuring luci-app-adbyby-plus.
> sed: /etc/crontabs/root: No such file or directory
> stop mem mode
> udhcpc: started, v1.30.0
> udhcpc: sending discover
> **udhcpc: no lease, failing
> uci: Entry not found
> uci: Entry not found
> uci: Parse error (invalid command) at line 1, byte 0
> uci: Entry not found**

**Comment by Narizgnaw** [comment]
同uci: Entry not found 。我也纳闷是什么情况，求大佬路过解答一下。
