### ISSUE TITLE
关于ssr的一些疑问

### ISSUE THREAD

**Issue by fastboom** [coolsnowwolf/lede#235]
夭寿啦！！！用的是R7 4.1的k2p固件,在同一wifi下S-S R开 gfwlist模式，电脑有线无线全都能用chromebook无线全能用，而手机不能用2.4G的。5g的可以。我室友一台电脑也不能用2.4G的扶墙，要是开绕开大陆ip那就全都能用了。。。。可我的手机只有2.4g。是不是我的防火墙有问题，可我用的是默认的防火墙设置啊，已经重装了，但是没有用。。。。

**Comment by paldier** [comment]
/etc/init.d/ssrpro restart 看看有没有报错吧可能和ipset有关
