### ISSUE TITLE
希望LEAN大能看到 , pptp服务器 导致防火墙 流量规则全部放行

### ISSUE THREAD

**Issue by yshx8** [coolsnowwolf/lede#2354]
希望LEAN大能看到 , pptp服务器 导致防火墙 流量规则全部放行

编译固件 如果包含了 pptp服务器 那么防火墙 会引用一个L大编写的 规则, 这个规则会导致 自己在WEB 界面提交的 流量规则全部放行

**Comment by coolsnowwolf** [comment]
并不会
