### ISSUE TITLE
软件包里的oscam编译出来无法启动

### ISSUE THREAD

**Issue by kunxiang1** [coolsnowwolf/lede#237]
命令行启动出现以下错误：
root@LEDE:~# oscam
WARNING: oscam.conf line 14 section [monitor] is ignored (support not compiled in).
Warning: keyword 'cccdisableautoblock' in reader section not recognized
启动项里显示禁用，无法启动。

**Comment by coolsnowwolf** [comment]
启动路径问题，待修复

**Comment by coolsnowwolf** [comment]
已修复

**Comment by kunxiang1** [comment]
root@OpenWrt:~# oscam
WARNING: oscam.conf line 20 section [monitor] contains unknown setting 'appendchaninfo=0'
Warning: keyword 'cccdisableautoblock' in reader section not recognized


还是不行。已git pull
