### ISSUE TITLE
Luci-app-upnp功能好像没有用

### ISSUE THREAD

**Issue by FriesAkuma** [coolsnowwolf/lede#2375]
luci-app-upnp(zh-cn) miniupnpd都完全安装,在路由上查看后,活动的UPNP重定向依然为 没有活动的重定向。(在迅雷打开后这里应该会有的)
![img](https://user-images.githubusercontent.com/52157853/70507302-07859d80-1b67-11ea-96ae-06b9d1ac22eb.png)

**Comment by ksong008** [comment]
你又没启动upnp，怎么会生效

**Comment by FriesAkuma** [comment]
> 你又没启动upnp，怎么会生效

UPNP功能启用了啊

**Comment by a1768623020** [comment]
> > 你又没启动upnp，怎么会生效
> 
> UPNP功能启用了啊

大哥，请把第一个选框勾上才算启用ヽ(ー_ー)ノ

**Comment by FriesAkuma** [comment]
> > > 你又没启动upnp，怎么会生效
> > 
> > 
> > UPNP功能启用了啊
> 
> 大哥，请把第一个选框勾上才算启用ヽ(ー_ー)ノ

行了,解决了,编译的时候不带上源码里的upnp,去openwrt上弄官方的装上可用了
![TIM截图20191210220456](https://user-images.githubusercontent.com/52157853/70536087-1b49f780-1b99-11ea-8cd8-b73ac9003cc7.png)
