### ISSUE TITLE
请求整合IPTV HELPER到固件，单线融合IPTV到家庭局域网

### ISSUE THREAD

**Issue by georip** [coolsnowwolf/lede#2388]
大雕您好！
      请求您有空整合iptv helper到固件，可帮助从光猫桥接单线复用，恢复IPTV收看的朋友！ 谢谢您！
下面是项目地址
https://github.com/riverscn/openwrt-iptvhelper

**Comment by bonnyandsky** [comment]
iptv各地的做法不一样，上海就很复杂，要ab双面认证，光方案就有好几个可以实现。
1：光猫桥接，iptv接光猫下面
2：光猫桥接，iptv接路由下面
3：光猫桥接，iptv接路由下面，路由接2条线到光猫
4：单线复用。
我知道的好相就这几个方案了。然后我用过1和2.结果1没成功，现在用的是2.应该属于单臂路由模式？

**Comment by outemancut** [comment]
人家源码LUCI都有贴出来了 你自己下载压缩包解压把前面两个放LEDE文件夹不就好了？
