### ISSUE TITLE
adbyby内存模式下服务初始化脚本与内存模式初始化脚本循环调用无限重启

### ISSUE THREAD

**Issue by cary-zhou** [coolsnowwolf/lede#2396]
/etc/init.d/adbyby start启动的时候会执行/usr/share/adbyby/admem.sh脚本，在网络正常的情况下while循环内部将使$wget_ok变量等于1，第二次循环时跳出，然后执行到"sleep 10 && /etc/init.d/adbyby restart"又会重新执行/usr/share/adbyby/admem.sh脚本，然后又会重新执行"/etc/init.d/adbyby restart"，无限循环。。。将会导致dnsmasq服务也跟着无限重启。
大佬有空给修复一下BUG

**Comment by caicaicai21** [comment]
确实有这个情况，但是我昨天才发现。

**Comment by guoyuc** [comment]
一样的情况, 系统Log里dnsmasq每隔10秒重启一次
