### ISSUE TITLE
我需要编译一个8M vixmini版本，减少LuCI里的项目，可是不能减少到8M

### ISSUE THREAD

**Issue by qinfeng8848** [coolsnowwolf/lede#2405]
我需要编译一个8M vixmini版本，希望可以用Sha*******R Plus+
去试着减少LuCI里的项目，可是不能减少到8M
请问，还需要减少哪些

**Comment by ihuaer** [comment]
至少编译出来18M的样子

**Comment by qinfeng8848** [comment]
luCI只留Sha*******R Plus+   有10M
