### ISSUE TITLE
在新路由3中生成的固件中无法使用TAP虚拟网卡与eth0.1 （lan）口上网

### ISSUE THREAD

**Issue by chinamore** [coolsnowwolf/lede#2426]
我想知道这是为什么，我在使用tap全局的时候，建了tap，物理网卡我选择了无线，无线没有任何问题，但是与lan口也就是 eth0.1 连接的时候，所有的lan口均无法上网，我定义了静态路由，没有丝毫改善

**Comment by coolsnowwolf** [comment]
描述不清
