### ISSUE TITLE
12.24最新源码编译大麦DW33D 出错

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#2428]
git pull 后默认编译，出错，提示如下
uild/genautomata /home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/common.md /home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/config/mips/mips.md \
          insn-conditions.md > tmp-automata.c
/bin/bash: line 1: 20889 Killed                  build/genautomata /home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/common.md /home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/config/mips/mips.md insn-conditions.md > tmp-automata.c
make[5]: *** [s-automata] Error 137
make[5]: Leaving directory `/home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/gcc'
make[4]: *** [all-gcc] Error 2
make[4]: Leaving directory `/home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial'
make[3]: *** [/home/ling/lede/build_dir/toolchain-mips_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/.built] Error 2
make[3]: Leaving directory `/home/ling/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#5.19#3.59#31.53
make[2]: *** [toolchain/gcc/initial/compile] Error 2
make[2]: Leaving directory `/home/ling/lede'
make[1]: *** [/home/ling/lede/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory `/home/ling/lede'
make: *** [world] 错误 2

**Comment by coolsnowwolf** [comment]
内存满了
