### ISSUE TITLE
关于Trojan问题

### ISSUE THREAD

**Issue by Zhang-Shijun** [coolsnowwolf/lede#2432]
通过查看 trojan的自启动文件，/etc/init.d/trojan可以看到，配置文件路径是 /etc/trojan.json.
但是在SSRPlus中添加节点后，那里是看不到节点的。而且，/etc/trojan.json.的配置是server，我们用的是client版，里面配置都不一样，手动删除/etc/trojan.json全部内容以后，将trojan搭建好的配置文件复制进去。可以使用。
直接执行 /usr/sbin/trojan 二进制文件，甚至都提示找不到某些文件。
还有一个就是，一经切换节点，再换回来，Trojan。连通性是不行的。

路由器为K2P。 最新源码。

**Comment by coolsnowwolf** [comment]
不需要调用 /etc/init.d/trojan
