### ISSUE TITLE
FreeNAS下Bhyve虚拟机时钟变快

### ISSUE THREAD

**Issue by benjaminbnuz** [coolsnowwolf/lede#2436]
## 症状：
一分钟比60秒短，时间总是块变快，NTP是正常的，但是同步之后过一会还是会快。
## 影响：
v2ray ws + tls 无法正常工作
## 硬件平台：
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)
但是在固件内CPU显示为
1666.000 MHz 
## 软件平台
FreeNAS-11.2-U7
## 编译来源：
Actions

网上暂时只找到一篇相关的帖子：https://blog.csdn.net/u011007991/article/details/52872257

**Comment by coolsnowwolf** [comment]
虚拟机 rtc 的问题。换 kvm
