### ISSUE TITLE
WRT系列没有无线选项

### ISSUE THREAD

**Issue by schen39** [coolsnowwolf/lede#244]
WRT1900ACV2用R7.5.1代码编译出来的固件没有无线选项，4.4和4.9一样都没有无线，R7.5代码编译时没有问题

**Comment by gavin219** [comment]
我是wrt3200，如果使用lean的代码编译运行超不过24小时。现在使用官方的git+lean的包。完美了

**Comment by schen39** [comment]
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/1611361/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/1611362/default.txt)

1月8号最新源码编译出来还是没有无线选项
