### ISSUE TITLE
上网时间控制插件，只要开启所有设备不能上网。

### ISSUE THREAD

**Issue by snakwu** [coolsnowwolf/lede#2440]
上网时间控制插件，只要开启所有设备不能上网。什么cpu模式也开了，我就连列表不加mac，只要打开上网时间控制，就所有设备上不了网！

**Comment by coolsnowwolf** [comment]
并不会 已测试

**Comment by snakwu** [comment]
那搞不明白是什么问题，也无日志显示，折腾了一天，对了我网络有v2ray，有双wan，有ipv6，只要打开上网控制开关，所有设备无法上网，但能访问openwrt页面

**Comment by snakwu** [comment]
同时也开了dbs转发

**Comment by outemancut** [comment]
并没有问题！好用的很

**Comment by snakwu** [comment]
我也不明原因

**Comment by snakwu** [comment]
对了，我是软路由，虚拟机环境，还接有交换机，有划vlan

**Comment by coolsnowwolf** [comment]
不能重现

**Comment by snakwu** [comment]
是否我编译时少了什么依赖或iptables mod

**Comment by snakwu** [comment]
L大,问题是在  iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53 -m comment --comment "Rule For Control"
  iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53 -m comment --comment "Rule For Control"
这两行iptables上面,只要这两个一添加,全部设备不能上网!

**Comment by chisenin** [comment]
今天也遇到同样的问题，开了上网时间控制插件，电脑无法获得IP,但是手机可以，控制的手机照样上网，其它设备则不能，手工设置电脑IP,可以访问openwrt设置页面，但无法上网。之前一直没有用过这个插件，一直没有问题。固件是今天编译的，也不知道是否有其它的编译依赖没解决

> 

主机名 | OpenWrt
-- | --
主机型号 | Intel(R) Celeron(R) CPU N3150 @ 1.60GHz : 4 Core 4 Thread
CPU 信息 | 1600.072 MHz +45.0°C (high = +90.0°C, crit = +90.0°C)
固件版本 | OpenWrt R20.7.1 / LuCI Master (git-20.191.36863-eee6bae)
内核版本 | 4.19.123
本地时间 | Sat Jul 25 21:27:52 2020
运行时间 | 0h 37m 21s
平均负载 | 0.64, 0.24, 0.09
CPU 使用率（%） | 3 %

config.seed文件内容

CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_Generic=y

# CONFIG_EFI_IMAGES is not set

CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_OPENSSL=y
CONFIG_LIBCURL_PROXY=y
CONFIG_NGINX_HEADERS_MORE=y
CONFIG_NGINX_HTTP_ACCESS=y
CONFIG_NGINX_HTTP_AUTH_BASIC=y
CONFIG_NGINX_HTTP_AUTOINDEX=y
CONFIG_NGINX_HTTP_BROWSER=y
CONFIG_NGINX_HTTP_CACHE=y
CONFIG_NGINX_HTTP_CHARSET=y
CONFIG_NGINX_HTTP_EMPTY_GIF=y
CONFIG_NGINX_HTTP_FASTCGI=y
CONFIG_NGINX_HTTP_GEO=y
CONFIG_NGINX_HTTP_GZIP=y
CONFIG_NGINX_HTTP_LIMIT_CONN=y
CONFIG_NGINX_HTTP_LIMIT_REQ=y
CONFIG_NGINX_HTTP_MAP=y
CONFIG_NGINX_HTTP_MEMCACHED=y
CONFIG_NGINX_HTTP_PROXY=y
CONFIG_NGINX_HTTP_REFERER=y
CONFIG_NGINX_HTTP_REWRITE=y
CONFIG_NGINX_HTTP_SCGI=y
CONFIG_NGINX_HTTP_SPLIT_CLIENTS=y
CONFIG_NGINX_HTTP_SSI=y
CONFIG_NGINX_HTTP_UPSTREAM_HASH=y
CONFIG_NGINX_HTTP_UPSTREAM_IP_HASH=y
CONFIG_NGINX_HTTP_UPSTREAM_KEEPALIVE=y
CONFIG_NGINX_HTTP_UPSTREAM_LEAST_CONN=y
CONFIG_NGINX_HTTP_USERID=y
CONFIG_NGINX_HTTP_UWSGI=y
CONFIG_NGINX_NAXSI=y
CONFIG_NGINX_PCRE=y
CONFIG_OPENSSL_WITH_COMPRESSION=y
CONFIG_OPENSSL_WITH_DTLS=y
CONFIG_OPENSSL_WITH_EC2M=y
CONFIG_OPENSSL_WITH_NPN=y
CONFIG_PACKAGE_6in4=y
CONFIG_PACKAGE_amd64-microcode=y

# CONFIG_PACKAGE_ath10k-firmware-qca9888 is not set

# CONFIG_PACKAGE_ath10k-firmware-qca988x is not set

# CONFIG_PACKAGE_ath10k-firmware-qca9984 is not set

# CONFIG_PACKAGE_bnx2-firmware is not set

CONFIG_PACKAGE_boost-date_time=y

# CONFIG_PACKAGE_brcmfmac-firmware-43602a1-pcie is not set

CONFIG_PACKAGE_brook=y
CONFIG_PACKAGE_ca-bundle=y
CONFIG_PACKAGE_chinadns-ng=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_broken_rtc=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_haproxy=y
CONFIG_PACKAGE_intel-microcode=y
CONFIG_PACKAGE_ip6tables=y
CONFIG_PACKAGE_ipv6helper=y
CONFIG_PACKAGE_iucode-tool=y
CONFIG_PACKAGE_kcptun-client=y

# CONFIG_PACKAGE_kmod-8139cp is not set

# CONFIG_PACKAGE_kmod-8139too is not set

# CONFIG_PACKAGE_kmod-bnx2 is not set

# CONFIG_PACKAGE_kmod-i40e is not set

# CONFIG_PACKAGE_kmod-i40evf is not set

# CONFIG_PACKAGE_kmod-igb is not set

# CONFIG_PACKAGE_kmod-igbvf is not set

CONFIG_PACKAGE_kmod-ipt-nat6=y
CONFIG_PACKAGE_kmod-iptunnel=y

# CONFIG_PACKAGE_kmod-ixgbe is not set

# CONFIG_PACKAGE_kmod-mlx4-core is not set

# CONFIG_PACKAGE_kmod-mlx5-core is not set

CONFIG_PACKAGE_kmod-nf-nat6=y

# CONFIG_PACKAGE_kmod-pcnet32 is not set

CONFIG_PACKAGE_kmod-sit=y
CONFIG_PACKAGE_kmod-usb-printer=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libfreetype=y
CONFIG_PACKAGE_libjpeg=y
CONFIG_PACKAGE_libltdl=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libpng=y
CONFIG_PACKAGE_libsqlite3=y
CONFIG_PACKAGE_libwebsockets-full=y

# CONFIG_PACKAGE_luci-app-ddns is not set

# CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set

CONFIG_PACKAGE_luci-app-kodexplorer=y
CONFIG_PACKAGE_luci-app-passwall=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_kcptun=y
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
CONFIG_PACKAGE_luci-app-smartdns=y

# CONFIG_PACKAGE_luci-app-ssr-plus is not set

# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2 is not set

# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server is not set

# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan is not set

# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray is not set

# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin is not set

CONFIG_PACKAGE_luci-app-ttyd=y

# CONFIG_PACKAGE_luci-app-upnp is not set

# CONFIG_PACKAGE_luci-app-wol is not set

# CONFIG_PACKAGE_luci-app-xlnetacc is not set

# CONFIG_PACKAGE_luci-app-zerotier is not set

CONFIG_PACKAGE_luci-i18n-kodexplorer-zh-cn=y
CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-theme-material=y
CONFIG_PACKAGE_nginx=y
CONFIG_PACKAGE_odhcp6c=y
CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
CONFIG_PACKAGE_odhcpd-ipv6only=y
CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
CONFIG_PACKAGE_p910nd=y
CONFIG_PACKAGE_php7=y
CONFIG_PACKAGE_php7-fpm=y
CONFIG_PACKAGE_php7-mod-curl=y
CONFIG_PACKAGE_php7-mod-gd=y
CONFIG_PACKAGE_php7-mod-hash=y
CONFIG_PACKAGE_php7-mod-iconv=y
CONFIG_PACKAGE_php7-mod-json=y
CONFIG_PACKAGE_php7-mod-mbstring=y
CONFIG_PACKAGE_php7-mod-mysqlnd=y
CONFIG_PACKAGE_php7-mod-opcache=y
CONFIG_PACKAGE_php7-mod-pdo=y
CONFIG_PACKAGE_php7-mod-pdo-mysql=y
CONFIG_PACKAGE_php7-mod-pdo-sqlite=y
CONFIG_PACKAGE_php7-mod-session=y
CONFIG_PACKAGE_php7-mod-sqlite3=y
CONFIG_PACKAGE_php7-mod-zip=y
CONFIG_PACKAGE_smartdns=y
CONFIG_PACKAGE_tcping=y
CONFIG_PACKAGE_trojan-go=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_zoneinfo-asia=y
CONFIG_PHP7_LIBFREETYPE=y
CONFIG_SQLITE_FTS3=y
CONFIG_SQLITE_RTREE=y
CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_TARGET_ROOTFS_PARTSIZE=112
CONFIG_TROJAN_GO_COMPRESS_UPX=y
CONFIG_V2RAY_COMPRESS_GOPROXY=y
CONFIG_LIBSODIUM_MINIMAL=y
CONFIG_PACKAGE_etherwake=y
CONFIG_PACKAGE_iptables-mod-ipsec=y
CONFIG_PACKAGE_kmod-crypto-acompress=y
CONFIG_PACKAGE_kmod-crypto-cbc=y
CONFIG_PACKAGE_kmod-crypto-deflate=y
CONFIG_PACKAGE_kmod-crypto-des=y
CONFIG_PACKAGE_kmod-crypto-echainiv=y
CONFIG_PACKAGE_kmod-crypto-hmac=y
CONFIG_PACKAGE_kmod-crypto-iv=y
CONFIG_PACKAGE_kmod-crypto-md5=y
CONFIG_PACKAGE_kmod-crypto-rng=y
CONFIG_PACKAGE_kmod-crypto-sha256=y
CONFIG_PACKAGE_kmod-crypto-wq=y

# CONFIG_PACKAGE_kmod-ip-vti is not set

# CONFIG_PACKAGE_kmod-ip6-vti is not set

CONFIG_PACKAGE_kmod-ipsec=y
CONFIG_PACKAGE_kmod-ipsec4=y
CONFIG_PACKAGE_kmod-ipsec6=y
CONFIG_PACKAGE_kmod-ipt-ipsec=y
CONFIG_PACKAGE_kmod-iptunnel6=y
CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
CONFIG_PACKAGE_kmod-tun=y

# CONFIG_PACKAGE_kmod-xfrm-interface is not set

CONFIG_PACKAGE_libev=y
CONFIG_PACKAGE_libevent2=y
CONFIG_PACKAGE_libminiupnpc=y
CONFIG_PACKAGE_libnatpmp=y
CONFIG_PACKAGE_libnet-1.2.x=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libsodium=y
CONFIG_PACKAGE_microsocks=y
CONFIG_PACKAGE_miniupnpd=y
CONFIG_PACKAGE_redsocks2=y
CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
CONFIG_PACKAGE_simple-obfs=y
CONFIG_PACKAGE_strongswan=y
CONFIG_PACKAGE_strongswan-charon=y
CONFIG_PACKAGE_strongswan-ipsec=y
CONFIG_PACKAGE_strongswan-minimal=y
CONFIG_PACKAGE_strongswan-mod-aes=y
CONFIG_PACKAGE_strongswan-mod-gmp=y
CONFIG_PACKAGE_strongswan-mod-hmac=y
CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
CONFIG_PACKAGE_strongswan-mod-nonce=y
CONFIG_PACKAGE_strongswan-mod-pubkey=y
CONFIG_PACKAGE_strongswan-mod-random=y
CONFIG_PACKAGE_strongswan-mod-sha1=y
CONFIG_PACKAGE_strongswan-mod-socket-default=y
CONFIG_PACKAGE_strongswan-mod-stroke=y
CONFIG_PACKAGE_strongswan-mod-updown=y
CONFIG_PACKAGE_strongswan-mod-x509=y
CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
CONFIG_PACKAGE_strongswan-mod-xcbc=y
CONFIG_PACKAGE_tcpping=y
CONFIG_PACKAGE_wol=y
CONFIG_PACKAGE_zerotier=y

# CONFIG_PCAP_HAS_NETFILTER is not set

# CONFIG_PCAP_HAS_USB is not set

# CONFIG_SIMPLE_OBFS_STATIC_LINK is not set

CONFIG_STRONGSWAN_ROUTING_TABLE="220"
CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"

# CONFIG_ZEROTIER_ENABLE_DEBUG is not set

# CONFIG_ZEROTIER_ENABLE_SELFTEST is not set

**Comment by chisenin** [comment]
昨天我以为是控制上网时间插件的问题，今天我把那插件卸载了，用smartdns和passwall时，一样出现在这个问题。初步估计是这两个插件配合有问题。或者是这两个插件和L大的源码兼容性问题。单独用smartdns/passwall,初次设置之后正常，但是只要修改了设置，保存&应用之后就一定会出现这个问题。后面没有再测试下去，折腾的时间太久了。
