### ISSUE TITLE
自编译的lede，DHCP问题导致重启后无网络。

### ISSUE THREAD

**Issue by MRDHR** [coolsnowwolf/lede#2446]
问题描述：编译的LEDE，安装后的第一次启动并配置完网络无问题。重启软路由后DHCP分配的默认网关和dns服务器会变成本网段的127

拿我本地环境的举例：
软路由 关闭ipv6 dhcp
lan 静态ip：192.168.2.1
第一次启动后获取的网络信息
ip 192.168.2.2
子网掩码 255.255.255.0
默认网关 192.168.2.1
dns服务器 192.168.2.1

重启路由器后获取到的网络信息
ip 192.168.2.2
子网掩码 255.255.255.0
默认网关 192.168.2.127
dns服务器 192.168.2.127

编译时 只增加了organ主题，其他均为默认配置。
试过openwrt官网的版本，只要将dnsmasq替换为dnsmasq-full也会出现相同的问题。网上也搜索过，暂时未找到答案。请大佬解疑。

**Comment by coolsnowwolf** [comment]
同一段有其他 DHCP服务器

**Comment by coolsnowwolf** [comment]
例如vmware 的

**Comment by MRDHR** [comment]
我的电脑，有virtual box，但是虚拟机均未启动并且没有dhcp服务器。遇到这种情况，可以在路由器强行配置dns服务器和默认网关么？

**Comment by MRDHR** [comment]
![QQ截图20191215232730](https://user-images.githubusercontent.com/5576916/70864925-86793c80-1f92-11ea-80e0-a45162c08a3c.png)
我尝试下改成这样，下次重启后再来报告情况。

**Comment by MRDHR** [comment]
通过修改lan的dhcp 勾选强制选项，成功解决了该问题。
