### ISSUE TITLE
自编译 x86_64网易云音乐无法运行

### ISSUE THREAD

**Issue by happyzhang1995** [coolsnowwolf/lede#2448]
![image](https://user-images.githubusercontent.com/55052017/70864553-fa651600-1f8d-11ea-9f63-c23d9ca9482f.png)
![image](https://user-images.githubusercontent.com/55052017/70864594-8414e380-1f8e-11ea-8429-aa4049c72c91.png)

点击手动更新后下方版本号消失，且无法启用网易云音乐，单独执行/usr/share/UnblockNeteaseMusic/update_core.sh文件提示
Error relocating /usr/bin/node: SSL_CTX_set_next_proto_select_cb: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_next_protos_advertised_cb: symbol not found
Error relocating /usr/bin/node: SSL_get0_next_proto_negotiated: symbol not found

**Comment by happyzhang1995** [comment]
感觉可能是node的问题，提示无法识别命令格式

**Comment by coolsnowwolf** [comment]
make clean
