### ISSUE TITLE
主机名不支持中文，改如何设置

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#2452]
路由hc5962,。

1. 随着无线客户端数量的增多，很多客户端的主机名是中文，不能正常显示。编译前该如何操作？

2. 同时，有些名称我需要自己编辑，以便知道是哪个设备，请问我该如何简便的操作？网络菜单主机名自定义吗？
如果是这样的话，我建议程序能否自动把所有dhcp的主机名全部复制到网络菜单中的主机名中，这样可以简单编辑名称，岂不方便？
3、如何简便的把不该进来的无线客户端加入黑名单，有好用的luci吗？

**Comment by shanyanhai** [comment]
@xiangfeigao 大佬们好像不搞这个功能，你有第三方解决方案了吗？

**Comment by shanyanhai** [comment]
> @xiangfeigao 大佬们好像不搞这个功能，你有第三方解决方案了吗？

中文主机名的这个
