### ISSUE TITLE
64M内存的MT7621机型出现的内存问题

### ISSUE THREAD

**Issue by keke1023** [coolsnowwolf/lede#2453]
机型是中兴的E8820V2，7621+64M内存，内存确实有点小，但是其他64M内存的机型貌似也没有遇到这个问题
具体症状是负载突然升高，高到5-10都有可能，查看进程主要是kworker，而且可能在一段时间后恢复
使用的功能测试过不同的搭配，多拨+ss（很少出现），多拨+trojan（经常出现），纯trojan（较少出现），纯ss（较少出现）
因为情况出现的不是很规律，所以不清楚具体触发的原因，猜测可能是内存不够导致的，刚运行起来貌似都好好的，负载也很低，内存看起来也剩20多M，但是不知道什么时候就突然卡住了，ssh上去看负载超高
最后贴一下关于这部分的内核日志，烦请各位帮我判断一下问题是出在机子自身内存不够，还是内核问题，还是trojan或者ss问题？前面是13秒正常启动日志，然后就到了6000秒的异常状态
[ 6203.346150] swapper/0: page allocation failure: order:0, mode:0x1080020(GFP_ATOMIC), nodemask=(null)
[ 6203.346605] swapper/3: page allocation failure: order:0
[ 6203.355296] swapper/0 cpuset=/
[ 6203.360513] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6203.360534]  mems_allowed=0
[ 6203.363572] (null)
[ 6203.368440] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.158 #0
[ 6203.371212] swapper/3 cpuset=
[ 6203.373205] Stack :
[ 6203.379271] /
[ 6203.382211]  00000000
[ 6203.384293]  mems_allowed=0
[ 6203.385852]  00000000 01080020 80071de8 805f0000 80588da4 00000000 00000000
[ 6203.397815]         805531c8 83809cb4 805c2e2c 805c29a7 8054dfd0 00000001 83809c58 ac07f587
[ 6203.406147]         00000000 00000000 80740000 00000124 00000029 00000003 00000001 6c756e28
[ 6203.414478]         83809a9c 805d0000 00058c34 00000000 00000000 805f0000 00000000 00000000
[ 6203.422808]         80e6d1c0 805c01c8 01080020 00000000 00000001 802ce230 00000000 80730000
[ 6203.431145]         ...
[ 6203.433585] Call Trace:
[ 6203.436047] [<8000c700>] show_stack+0x58/0x100
[ 6203.440481] [<80489734>] dump_stack+0xa4/0xe0
[ 6203.444836] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6203.449261] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6203.454807] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6203.459753] [<8033b5f0>] fe_poll+0x33c/0x804
[ 6203.464010] [<8037ec74>] net_rx_action+0x150/0x30c
[ 6203.468791] [<804a8620>] __do_softirq+0x128/0x2ec
[ 6203.473485] [<8002fc64>] irq_exit+0xac/0xc8
[ 6203.477654] [<802817ec>] plat_irq_dispatch+0xfc/0x138
[ 6203.482682] [<80007608>] except_vec_vi_end+0xb8/0xc4
[ 6203.487623] [<80008fd0>] r4k_wait_irqoff+0x1c/0x24
[ 6203.492407] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.158 #0
[ 6203.492496] Mem-Info:
[ 6203.498476] Stack : 00000000 00000000 01080020 80071de8 805f0000 80588da4 00000000
[ 6203.500781] active_anon:2369 inactive_anon:58 isolated_anon:0
[ 6203.500781]  active_file:821 inactive_file:1600 isolated_file:12
[ 6203.500781]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 6203.500781]  slab_reclaimable:490 slab_unreclaimable:2791
[ 6203.500781]  mapped:1461 shmem:342 pagetables:115 bounce:0
[ 6203.500781]  free:766 free_pcp:42 free_cma:0
[ 6203.500788]  00000000
[ 6203.508357] Node 0 active_anon:9476kB inactive_anon:232kB active_file:3284kB inactive_file:6400kB unevictable:0kB isolated(anon):0kB isolated(file):48kB mapped:5844kB dirty:0kB writeback:0kB shmem:1368kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 6203.540403]         805531c8 8380fc94 8383518c 805c29a7 8054dfd0 00000001
[ 6203.542708] Normal free:3064kB min:8192kB low:10240kB high:12288kB active_anon:9476kB inactive_anon:232kB active_file:3284kB inactive_file:6400kB unevictable:0kB writepending:0kB present:65536kB managed:58256kB mlocked:0kB kernel_stack:720kB pagetables:460kB bounce:0kB free_pcp:168kB local_pcp:12kB free_cma:0kB
[ 6203.565246]  8380fc38 ac07f587
[ 6203.565258]         00000000 00000000
[ 6203.572029] lowmem_reserve[]:
[ 6203.599421]  80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6203.602482]  0
[ 6203.606117]         8380fa7c 805d0000 00078377 00000000 00000000 805f0000
[ 6203.609094]  0
[ 6203.615234]  00000000
[ 6203.616896]  0
[ 6203.623634]  00000000
[ 6203.627535]         00000000 805c01c8 01080020 00000000 00000000
[ 6203.629211] Normal: 
[ 6203.631464]  802ce230
[ 6203.637449] 9*4kB 
[ 6203.639602]  0000000c
[ 6203.641856] (UM) 
[ 6203.643850]  8073000c
[ 6203.646123] 0*8kB 
[ 6203.650268] 2*16kB 
[ 6203.652259]        
[ 6203.652267] (ME) 
[ 6203.654347]  ...
[ 6203.656443] 11*32kB 
[ 6203.660163] (E) 
[ 6203.662328] Call Trace:
[ 6203.662330] 8*64kB (UME) 
[ 6203.664178] [<8000c700>] show_stack+0x58/0x100
[ 6203.666602] 5*128kB 
[ 6203.669198] [<80489734>] dump_stack+0xa4/0xe0
[ 6203.673603] (E) 
[ 6203.675788] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6203.680108] 4*256kB 
[ 6203.681932] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6203.686350] (ME) 
[ 6203.688519] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6203.694041] 1*512kB (E) 
[ 6203.695994] [<829790d0>] mt76_dma_attach+0xb4c/0x10f8 [mt76]
[ 6203.700936] 0*1024kB 
[ 6203.703961] swapper/3: 
[ 6203.709105] 0*2048kB 0*4096kB 
[ 6203.711387] page allocation failure: order:0
[ 6203.713817] = 3108kB
[ 6203.716864] , mode:0x1080020(GFP_ATOMIC), nodemask=(null)
[ 6203.721131] 2782 total pagecache pages
[ 6203.723303] swapper/3 cpuset=
[ 6203.728692] 0 pages in swap cache
[ 6203.732409] /
[ 6203.735362] Swap cache stats: add 0, delete 0, find 0/0
[ 6203.738663]  mems_allowed=0
[ 6203.738684] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.158 #0
[ 6203.740242] Free swap  = 0kB
[ 6203.745431] Stack : 00000000
[ 6203.748231] Total swap = 0kB
[ 6203.754274]  00000000
[ 6203.757155] 16384 pages RAM
[ 6203.759999]  01080020
[ 6203.762861] 0 pages HighMem/MovableOnly
[ 6203.765115]  80071de8
[ 6203.767904] 1820 pages reserved
[ 6203.770146]  805f0000
[ 6203.773964] swapper/0: 
[ 6203.776208]  80588da4 00000000 00000000
[ 6203.776222]         805531c8
[ 6203.779355] page allocation failure: order:0
[ 6203.781608]  8380fc94
[ 6203.784039] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6203.787843]  8383518c 805c29a7 8054dfd0 00000001 8380fc38 ac07f587
[ 6203.790730] (null)
[ 6203.797242] swapper/0 cpuset=
[ 6203.802078]        
[ 6203.808237] /
[ 6203.810221]  00000000
[ 6203.813171]  mems_allowed=0
[ 6203.815249]  00000000 80740000 00000124 00000030 202c3020 656c6564 30206574
[ 6203.828794]         8380fa7c 805d0000 000b3882 00000000 00000000 805f0000 00000000 00000000
[ 6203.837145]         00000000 805c01c8 01080020 00000000 00000002 802ce230 0000000c 8073000c
[ 6203.845492]         ...
[ 6203.847933] Call Trace:
[ 6203.850387] [<8000c700>] show_stack+0x58/0x100
[ 6203.854820] [<80489734>] dump_stack+0xa4/0xe0
[ 6203.859178] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6203.863614] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6203.869176] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6203.874141] [<829790d0>] mt76_dma_attach+0xb4c/0x10f8 [mt76]
[ 6203.879797] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.158 #0
[ 6203.880260] swapper/3: page allocation failure: order:0
[ 6203.885871] Stack : 00000000 00000000 01080020
[ 6203.891091] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6203.891103]  80071de8
[ 6203.895517] (null)
[ 6203.900361]  805f0000 80588da4 00000000 00000000
[ 6203.902635] swapper/3 cpuset=
[ 6203.904627]         805531c8 83809cb4 805c2e2c 805c29a7 8054dfd0 00000001
[ 6203.909253] /
[ 6203.912193]  83809c58
[ 6203.918969]  mems_allowed=0
[ 6203.920506]  ac07f587
[ 6203.927790]         00000000 00000000 80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6203.936141]         83809a9c 805d0000 000d6cb5 00000000 00000000 805f0000 00000000 00000000
[ 6203.944488]         00000000 805c01c8 01080020 00000000 00000000 802ce230 00000000 80730000
[ 6203.952835]         ...
[ 6203.955275] Call Trace:
[ 6203.957725] [<8000c700>] show_stack+0x58/0x100
[ 6203.962158] [<80489734>] dump_stack+0xa4/0xe0
[ 6203.966513] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6203.970944] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6203.976501] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6203.981453] [<8033b5f0>] fe_poll+0x33c/0x804
[ 6203.985716] [<8037ec74>] net_rx_action+0x150/0x30c
[ 6203.990504] [<804a8620>] __do_softirq+0x128/0x2ec
[ 6203.995199] [<8002fc64>] irq_exit+0xac/0xc8
[ 6203.999376] [<802817ec>] plat_irq_dispatch+0xfc/0x138
[ 6204.004412] [<80007608>] except_vec_vi_end+0xb8/0xc4
[ 6204.009362] [<80008fd0>] r4k_wait_irqoff+0x1c/0x24
[ 6204.014149] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.158 #0
[ 6204.014249] swapper/0: 
[ 6204.020218] Stack : 00000000 00000000
[ 6204.022665] page allocation failure: order:0
[ 6204.022675]  01080020
[ 6204.026349] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6204.030559]  80071de8
[ 6204.032814] (null)
[ 6204.037659]  805f0000 80588da4 00000000 00000000
[ 6204.037682]        
[ 6204.039941] swapper/0 cpuset=
[ 6204.041937]  805531c8
[ 6204.046555] /
[ 6204.048612]  8380fc94
[ 6204.051559]  mems_allowed=0
[ 6204.053811]  8383518c 805c29a7 8054dfd0 00000001 8380fc38 ac07f587
[ 6204.066572]         00000000 00000000 80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6204.074923]         8380fa7c 805d0000 00003745 00000000 00000000 805f0000 00000000 00000000
[ 6204.083274]         00000000 805c01c8 01080020 00000000 00000000 802ce230 0000000c 8073000c
[ 6204.091624]         ...
[ 6204.094065] Call Trace:
[ 6204.096515] [<8000c700>] show_stack+0x58/0x100
[ 6204.100948] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.105299] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.109732] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.115288] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.120251] [<829790d0>] mt76_dma_attach+0xb4c/0x10f8 [mt76]
[ 6204.125905] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.158 #0
[ 6204.126212] swapper/3: 
[ 6204.131977] Stack : 00000000
[ 6204.134423] page allocation failure: order:0
[ 6204.134426]  00000000 01080020
[ 6204.137312] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6204.141541]  80071de8
[ 6204.144573] (null)
[ 6204.149416]  805f0000 80588da4 00000000 00000000
[ 6204.151690] swapper/3 cpuset=
[ 6204.158280] /
[ 6204.161214]        
[ 6204.161226]  mems_allowed=0
[ 6204.162787]  805531c8 83809cb4 805c2e2c 805c29a7 8054dfd0 00000001 83809c58 ac07f587
[ 6204.175378]         00000000 00000000 80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6204.183728]         83809a9c 805d0000 0001ebd1 00000000 00000000 805f0000 00000000 00000000
[ 6204.192075]         00000000 805c01c8 01080020 00000000 00000000 802ce230 00000000 80730000
[ 6204.200424]         ...
[ 6204.202864] Call Trace:
[ 6204.205313] [<8000c700>] show_stack+0x58/0x100
[ 6204.209747] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.214102] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.218536] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.224091] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.229043] [<8033b5f0>] fe_poll+0x33c/0x804
[ 6204.233304] [<8037ec74>] net_rx_action+0x150/0x30c
[ 6204.238091] [<804a8620>] __do_softirq+0x128/0x2ec
[ 6204.242782] [<8002fc64>] irq_exit+0xac/0xc8
[ 6204.246955] [<802817ec>] plat_irq_dispatch+0xfc/0x138
[ 6204.251992] [<80007608>] except_vec_vi_end+0xb8/0xc4
[ 6204.256942] [<80008fd0>] r4k_wait_irqoff+0x1c/0x24
[ 6204.261730] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.158 #0
[ 6204.261836] swapper/0: 
[ 6204.267799] Stack : 00000000 00000000 01080020 80071de8
[ 6204.270252] page allocation failure: order:0
[ 6204.270264]  805f0000
[ 6204.275461] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6204.279698]  80588da4 00000000 00000000
[ 6204.279718]        
[ 6204.281977] (null)
[ 6204.286819]  805531c8 8380fc94 8383518c 805c29a7 8054dfd0 00000001
[ 6204.290658] swapper/0 cpuset=
[ 6204.292739]  8380fc38
[ 6204.294735] /
[ 6204.300881]  ac07f587
[ 6204.303845]  mems_allowed=0
[ 6204.306080]         00000000 00000000 80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6204.321016]         8380fa7c 805d0000 0003fe62 00000000 00000000 805f0000 00000000 00000000
[ 6204.329367]         00000000 805c01c8 01080020 00000000 00000000 802ce230 0000000c 8073000c
[ 6204.337716]         ...
[ 6204.340157] Call Trace:
[ 6204.342606] [<8000c700>] show_stack+0x58/0x100
[ 6204.347040] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.351393] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.355825] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.361383] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.366351] [<829790d0>] mt76_dma_attach+0xb4c/0x10f8 [mt76]
[ 6204.372004] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.158 #0
[ 6204.372355] swapper/3: 
[ 6204.378081] Stack : 00000000 00000000
[ 6204.380541] page allocation failure: order:0
[ 6204.380552]  01080020
[ 6204.384197] , mode:0x1080020(GFP_ATOMIC), nodemask=
[ 6204.388430]  80071de8 805f0000 80588da4 00000000
[ 6204.390705] (null)
[ 6204.395552]  00000000
[ 6204.400150] swapper/3 cpuset=
[ 6204.404393] /
[ 6204.407336]        
[ 6204.407356]  mems_allowed=0
[ 6204.408912]  805531c8 83809cb4 805c2e2c 805c29a7 8054dfd0 00000001 83809c58 ac07f587
[ 6204.421501]         00000000 00000000 80740000 00000124 30232038 6465746e 312e3420 35312e34
[ 6204.429851]         83809a9c 805d0000 0005ad24 00000000 00000000 805f0000 00000000 00000000
[ 6204.438200]         00000000 805c01c8 01080020 00000000 00000000 802ce230 00000000 80730000
[ 6204.446552]         ...
[ 6204.448993] Call Trace:
[ 6204.451455] [<8000c700>] show_stack+0x58/0x100
[ 6204.455892] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.460253] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.464685] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.470242] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.475194] [<8033b5f0>] fe_poll+0x33c/0x804
[ 6204.479459] [<8037ec74>] net_rx_action+0x150/0x30c
[ 6204.484248] [<804a8620>] __do_softirq+0x128/0x2ec
[ 6204.488949] [<8002fc64>] irq_exit+0xac/0xc8
[ 6204.493124] [<802817ec>] plat_irq_dispatch+0xfc/0x138
[ 6204.498161] [<80007608>] except_vec_vi_end+0xb8/0xc4
[ 6204.503110] [<80008fd0>] r4k_wait_irqoff+0x1c/0x24
[ 6204.507901] CPU: 3 PID: 0 Comm: swapper/3 Not tainted 4.14.158 #0
[ 6204.508022] warn_alloc_show_mem: 6 callbacks suppressed
[ 6204.508034] Mem-Info:
[ 6204.513972] Stack :
[ 6204.519213] active_anon:2369 inactive_anon:58 isolated_anon:0
[ 6204.519213]  active_file:821 inactive_file:1600 isolated_file:12
[ 6204.519213]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 6204.519213]  slab_reclaimable:490 slab_unreclaimable:2791
[ 6204.519213]  mapped:1461 shmem:342 pagetables:115 bounce:0
[ 6204.519213]  free:766 free_pcp:42 free_cma:0
[ 6204.521427]  00000000
[ 6204.523557] Node 0 active_anon:9476kB inactive_anon:232kB active_file:3284kB inactive_file:6400kB unevictable:0kB isolated(anon):0kB isolated(file):48kB mapped:5844kB dirty:0kB writeback:0kB shmem:1368kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 6204.555596]  00000000 01080020 80071de8 805f0000 80588da4 00000000 00000000
[ 6204.555631]        
[ 6204.557925] Normal free:3064kB min:8192kB low:10240kB high:12288kB active_anon:9476kB inactive_anon:232kB active_file:3284kB inactive_file:6400kB unevictable:0kB writepending:0kB present:65536kB managed:58256kB mlocked:0kB kernel_stack:720kB pagetables:460kB bounce:0kB free_pcp:168kB local_pcp:12kB free_cma:0kB
[ 6204.580451]  805531c8 8380fc94 8383518c 805c29a7 8054dfd0 00000001 8380fc38
[ 6204.587413] lowmem_reserve[]:
[ 6204.589493]  ac07f587
[ 6204.616916]  0
[ 6204.626775]  0
[ 6204.629018]        
[ 6204.630668]  0
[ 6204.632318]  00000000
[ 6204.636045]  00000000 80740000 00000124 30232038 6465746e 312e3420
[ 6204.638323] Normal: 
[ 6204.638327]  35312e34
[ 6204.644481] 9*4kB 
[ 6204.646645]         8380fa7c 805d0000 0007bffd 00000000 00000000
[ 6204.648928] (UM) 
[ 6204.650924]  805f0000
[ 6204.656910] 0*8kB 
[ 6204.658806]  00000000
[ 6204.661062] 2*16kB 
[ 6204.663056]  00000000
[ 6204.665311] (ME) 
[ 6204.667392]         00000000 805c01c8 01080020 00000000
[ 6204.669671] 11*32kB 
[ 6204.671579]  00000000
[ 6204.676788] (E) 
[ 6204.678945]  802ce230
[ 6204.679633] logd: page allocation failure: order:0, mode:0x1080020(GFP_ATOMIC), nodemask=(null)
[ 6204.679652] logd cpuset=/ mems_allowed=0
[ 6204.681200] 8*64kB 
[ 6204.683024]  0000000c
[ 6204.685280] (UME) 
[ 6204.693924]  8073000c
[ 6204.693930]         ...
[ 6204.693940] Call Trace:
[ 6204.693964] [<8000c700>] show_stack+0x58/0x100
[ 6204.697860] 5*128kB 
[ 6204.699939] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.702186] (E) 
[ 6204.704197] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.706451] 4*256kB 
[ 6204.708876] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.711295] (ME) 
[ 6204.715720] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.717891] 1*512kB 
[ 6204.722232] [<829790d0>] mt76_dma_attach+0xb4c/0x10f8 [mt76]
[ 6204.724033] (E) 
[ 6204.728462] CPU: 2 PID: 1046 Comm: logd Not tainted 4.14.158 #0
[ 6204.728470] Stack :
[ 6204.730671] 0*1024kB 
[ 6204.736232]  00000000 80730000 00000000 00000000 805f0000 80588da4
[ 6204.738205] 0*2048kB 
[ 6204.743140]  00000000
[ 6204.745307] 0*4096kB 
[ 6204.750928]  00000000
[ 6204.750933]         805531c8 8380dbd4 82a61d8c 805c29a7 8054dfd0 00000001
[ 6204.752779] = 3108kB
[ 6204.758656]  8380db78 ac07f587
[ 6204.758664]         00000000 00000000 80740000 51404643 00000004
[ 6204.760768] 2782 total pagecache pages
[ 6204.763013]  804a088c a7bf570d
[ 6204.769184] 0 pages in swap cache
[ 6204.771420]  000aac50
[ 6204.773678] Swap cache stats: add 0, delete 0, find 0/0
[ 6204.775925]         00000000 805d0000 0000025e 80760000 80000000 805f0000 00000000
[ 6204.778207] Free swap  = 0kB
[ 6204.784946]  00000000
[ 6204.787137] Total swap = 0kB
[ 6204.790154]        
[ 6204.796144] 16384 pages RAM
[ 6204.799851]  82a28bc0
[ 6204.802882] 0 pages HighMem/MovableOnly
[ 6204.806167]  805c01c8 01080020 00000000 00000003 805c0000 00000008 80730008
[ 6204.808447] 1820 pages reserved
[ 6204.813637]         ...
[ 6204.852534] Call Trace:
[ 6204.854997] [<8000c700>] show_stack+0x58/0x100
[ 6204.859435] [<80489734>] dump_stack+0xa4/0xe0
[ 6204.863792] [<800dcc54>] warn_alloc+0xcc/0x15c
[ 6204.868219] [<800dd988>] __alloc_pages_nodemask+0xbf8/0xd78
[ 6204.873766] [<800ddd4c>] page_frag_alloc+0x14c/0x178
[ 6204.878735] [<80366db0>] __netdev_alloc_skb+0xc4/0x16c
[ 6204.883996] [<8292e594>] ieee80211_csa_is_complete+0x7c0/0xba0 [mac80211]
[ 6232.213093] sh invoked oom-killer: gfp_mask=0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null),  order=1, oom_score_adj=0
[ 6232.226726] sh cpuset=/ mems_allowed=0
[ 6232.230549] CPU: 2 PID: 24799 Comm: sh Not tainted 4.14.158 #0
[ 6232.236390] Stack : 00000000 00000001 015080c0 80071de8 805f0000 80588da4 00000000 00000000
[ 6232.244832]         805531c8 8265bc1c 83b9838c 805c29a7 8054dfd0 00000001 8265bbc0 ac07f587
[ 6232.253233]         00000000 00000000 80740000 00009f48 00000000 00000285 00000007 00000000
[ 6232.261637]         00000000 805d0000 00038495 00000000 80000000 805f0000 00000000 80558b28
[ 6232.270055]         0000003d 805c01c8 0000007d 00000001 00000001 802ce230 00000008 80730008
[ 6232.278477]         ...
[ 6232.280965] Call Trace:
[ 6232.283463] [<8000c700>] show_stack+0x58/0x100
[ 6232.287934] [<80489734>] dump_stack+0xa4/0xe0
[ 6232.292341] [<800d8e98>] dump_header+0x98/0x1f0
[ 6232.296960] [<800d7fe4>] oom_kill_process+0xf0/0x618
[ 6232.301956] [<800d8d4c>] out_of_memory+0x2e8/0x320
[ 6232.306809] [<800dd794>] __alloc_pages_nodemask+0xa04/0xd78
[ 6232.312428] [<80028cbc>] copy_process.part.8+0x110/0x1674
[ 6232.317857] [<8002a3b4>] _do_fork+0xe0/0x360
[ 6232.322157] [<8002a694>] sys_fork+0x24/0x30
[ 6232.326393] [<80015578>] syscall_common+0x34/0x58
[ 6232.331990] Mem-Info:
[ 6232.334322] active_anon:2397 inactive_anon:58 isolated_anon:0
[ 6232.334322]  active_file:105 inactive_file:153 isolated_file:0
[ 6232.334322]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 6232.334322]  slab_reclaimable:510 slab_unreclaimable:2787
[ 6232.334322]  mapped:23 shmem:342 pagetables:117 bounce:0
[ 6232.334322]  free:2952 free_pcp:41 free_cma:0
[ 6232.366331] Node 0 active_anon:9588kB inactive_anon:232kB active_file:504kB inactive_file:892kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:92kB dirty:0kB writeback:0kB shmem:1368kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
[ 6232.388715] Normal free:12448kB min:8192kB low:10240kB high:12288kB active_anon:9588kB inactive_anon:232kB active_file:492kB inactive_file:632kB unevictable:0kB writepending:0kB present:65536kB managed:58256kB mlocked:0kB kernel_stack:736kB pagetables:468kB bounce:0kB free_pcp:164kB local_pcp:60kB free_cma:0kB
[ 6232.416149] lowmem_reserve[]: 0 0 0
[ 6232.419728] Normal: 280*4kB (UMEH) 191*8kB (UMH) 181*16kB (UMEH) 90*32kB (UMEH) 30*64kB (UMEH) 9*128kB (UEH) 1*256kB (H) 1*512kB (H) 0*1024kB 0*2048kB 0*4096kB = 12264kB
[ 6232.435746] 957 total pagecache pages
[ 6232.439428] 0 pages in swap cache
[ 6232.442748] Swap cache stats: add 0, delete 0, find 0/0
[ 6232.447997] Free swap  = 0kB
[ 6232.450874] Total swap = 0kB
[ 6232.453753] 16384 pages RAM
[ 6232.456568] 0 pages HighMem/MovableOnly
[ 6232.460397] 1820 pages reserved
[ 6232.463535] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[ 6232.472120] [  527]     0   527      307       10       4       0        0             0 ubusd
[ 6232.480755] [  528]     0   528      232        7       3       0        0             0 askfirst
[ 6232.489653] [ 1046]     0  1046      313       30       4       0        0             0 logd
[ 6232.498222] [ 1067]     0  1067      407       22       4       0        0             0 rpcd
[ 6232.506813] [ 1135]     0  1135      270        7       4       0        0             0 dropbear
[ 6232.515758] [ 1202]     0  1202      437       39       4       0        0             0 netifd
[ 6232.524465] [ 1655]     0  1655      394       32       4       0        0             0 uhttpd
[ 6232.533964] [ 2370]     0  2370      443       34       4       0        0             0 hostapd
[ 6232.542824] [ 2396]     0  2396      443       31       4       0        0             0 hostapd
[ 6232.551680] [ 2813]     0  2813      313       31       5       0        0             0 pppd
[ 6232.560285] [ 2824]     0  2824      313       32       4       0        0             0 pppd
[ 6232.568843] [ 2827]     0  2827      313       32       4       0        0             0 pppd
[ 6232.577386] [ 3424]     0  3424      305       11       3       0        0             0 ntpd
[ 6232.585919] [ 3973]     0  3973      329       36       4       0        0             0 sh
[ 6232.594261] [ 4322]     0  4322      329       36       3       0        0             0 sh
[ 6232.602651] [ 4703]     0  4703      329       36       5       0        0             0 sh
[ 6232.611033] [18607]     0 18607      305        9       3       0        0             0 crond
[ 6232.619673] [18758]     0 18758     2462      918       7       0        0             0 trojan
[ 6232.628403] [18794] 65534 18794      381        0       4       0        0             0 pdnsd
[ 6232.639174] [18809]     0 18809      324       30       4       0        0             0 sh
[ 6232.650049] [18914]   453 18914      852      538       5       0        0             0 dnsmasq
[ 6232.661336] [18926]     0 18926      307       12       5       0        0             0 sh
[ 6232.671084] [24795]     0 24795      335       41       3       0        0             0 sh
[ 6232.679480] [24799]     0 24799      315       20       4       0        0             0 sh
[ 6232.687852] [24829]     0 24829      304        7       4       0        0             0 sleep
[ 6232.696482] [24844]     0 24844      306        9       4       0        0             0 sleep
[ 6232.705075] [24849]     0 24849      306        9       3       0        0             0 sleep
[ 6232.713748] [24850]     0 24850      306        9       4       0        0             0 sleep
[ 6232.722386] Out of memory: Kill process 18758 (trojan) score 61 or sacrifice child
[ 6232.730018] Killed process 18758 (trojan) total-vm:9848kB, anon-rss:3668kB, file-rss:0kB, shmem-rss:4kB
[ 6232.760392] oom_reaper: reaped process 18758 (trojan), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by coolsnowwolf** [comment]
内存被无线和 Trojan 耗尽了，编译时去掉无线，MTK 的驱动虽然很差，但吃内存比 AR71xx 和 高通的 多多了

**Comment by keke1023** [comment]
@coolsnowwolf 谢谢大佬亲自解答，那我就还是改下内存再测试，猜测也是内存不够，但是没想到是无线驱动在助攻。。
