### ISSUE TITLE
最近编译出来的固件端口转发好像失效了

### ISSUE THREAD

**Issue by alanch522** [coolsnowwolf/lede#2456]
设置端口转发后，只有软路由本身能外网访问，其他设备不管什么端口都无效

**Comment by coolsnowwolf** [comment]
不能重现

**Comment by rogerjx87** [comment]
> 设置端口转发后，只有软路由本身能外网访问，其他设备不管什么端口都无效

建议检查一下防火墙设置，0201版本默认的防火墙是不允许转发的，需要彻底放开或者自行添加放行规则。
