### ISSUE TITLE
编译失败，看了日志 NPS的锅。大佬请查看一下

### ISSUE THREAD

**Issue by com388488** [coolsnowwolf/lede#2460]
![图片](https://user-images.githubusercontent.com/54615116/70882555-1e1a7180-200b-11ea-844f-c25abfddc95f.png)

**Comment by lihaixin** [comment]
我也和你一样的情况，使用最新的源码，也是提示同样的错误，勾选就luci-app-nps就出现此错误，取消就可以编译通过
