### ISSUE TITLE
R619AC 2019年12月16日代码编译不过 menuconfig 全部默认设置 

### ISSUE THREAD

**Issue by joybin08** [coolsnowwolf/lede#2463]
-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk01.1-c1.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-ap.dk01.1-c1.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk01.1-c1.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk01.1-c1.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk01.1-c1.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-r619ac.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac-128m.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-r619ac-128m.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac-128m.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac-128m.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-r619ac-128m.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk04.1-c1.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-ap.dk04.1-c1.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk04.1-c1.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk04.1-c1.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-ap.dk04.1-c1.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-hugo-ac1200.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-hugo-ac1200.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-hugo-ac1200.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-hugo-ac1200.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4019-hugo-ac1200.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-nbg6617.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4018-nbg6617.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-nbg6617.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-nbg6617.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-nbg6617.dtb.tmp
arm-openwrt-linux-muslgnueabi-cpp -nostdinc -x assembler-with-cpp -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/include -I/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/include/ -undef -D__DTS__  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-wre6606.dtb.tmp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4018-wre6606.dts
/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc/dtc -O dtb -i/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/ -Wno-unit_address_vs_reg -Wno-unit_address_vs_reg -Wno-simple_bus_reg -Wno-unit_address_format -Wno-pci_bridge -Wno-pci_device_bus_num -Wno-pci_device_reg  -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-wre6606.dtb /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-wre6606.dtb.tmp
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/image-qcom-ipq4018-wre6606.dtb.tmp
mkdir -p /home/user/lede/bin/targets/ipq40xx/generic /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp
/home/user/lede/staging_dir/host/bin/mksquashfs4 /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/root.squashfs -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2 -Xbcj arm -b 256k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/root.squashfs, block size 262144.
Pseudo file "/dev" exists in source filesystem "/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/dev".
Ignoring, exclude it (-e/-ef) to override.
[=====================================================================================================-] 3191/3191 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 262144
        compressed data, compressed metadata, compressed fragments,
        no xattrs, compressed ids
        duplicates are removed
Filesystem size 26604.70 Kbytes (25.98 Mbytes)
        37.25% of uncompressed filesystem size (71430.79 Kbytes)
Inode table size 26708 bytes (26.08 Kbytes)
        21.35% of uncompressed inode table size (125082 bytes)
Directory table size 36110 bytes (35.26 Kbytes)
        42.48% of uncompressed directory table size (85003 bytes)
Number of duplicate files found 373
Number of inodes 3706
Number of files 3032
Number of fragments 96
Number of symbolic links  456
Number of device nodes 1
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 217
Number of ids (unique uids + gids) 1
Number of uids 1
        root (0)
Number of gids 1
        root (0)
rm -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb
cp /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/zImage-initramfs /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb
/home/user/lede/scripts/mkits.sh -D p2w_r619ac-128m -o /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb.its -k /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb -d /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/arch/arm/boot/dts/qcom-ipq4019-r619ac-128m.dtb -C none -a 0x80208000 -e 0x80208000 -c config@10 -A arm -v 4.14.158
PATH=/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/host/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/host/bin:/home/user/lede/staging_dir/host/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/MentorGraphics/9.5PADS/SDD_HOME/common/win32/bin:/mnt/c/MentorGraphics/9.5PADS/SDD_HOME/common/win32/lib:/mnt/c/MentorGraphics/9.5PADS/MGC_HOME.ixn/bin:/mnt/c/MentorGraphics/9.5PADS/MGC_HOME.ixn/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/Program:Files:(x86)/Intel/Intel(R):Management:Engine:Components/DAL:/mnt/c/Program:Files/Intel/Intel(R):Management:Engine:Components/DAL:/mnt/c/Users/tengbin1/AppData/Local/Microsoft/WindowsApps:/snap/bin mkimage -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb.its /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb.new
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `PATH=/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/linux-4.14.158/scripts/dtc:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/host/bin:/home/user/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-7.5.0_musl_eabi/bin:/home/user/lede/staging_dir/host/bin:/home/user/lede/staging_dir/host/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/MentorGraphics/9.5PADS/SDD_HOME/common/win32/bin:/mnt/c/MentorGraphics/9.5PADS/SDD_HOME/common/win32/lib:/mnt/c/MentorGraphics/9.5PADS/MGC_HOME.ixn/bin:/mnt/c/MentorGraphics/9.5PADS/MGC_HOME.ixn/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/Program:Files:(x86)/Intel/Intel(R):Management:Engine:Components/DAL:/mnt/c/Program:Files/Intel/Intel(R):Management:Engine:Components/DAL:/mnt/c/Users/tengbin1/AppData/Local/Microsoft/WindowsApps:/snap/bin mkimage -f /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb.its /home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb.new'
Makefile:364: recipe for target '/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb' failed
make[5]: *** [/home/user/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/tmp/openwrt-ipq40xx-p2w_r619ac-128m-initramfs-fit-zImage.itb] Error 1
make[5]: Leaving directory '/home/user/lede/target/linux/ipq40xx/image'
Makefile:26: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/user/lede/target/linux/ipq40xx'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/user/lede/target/linux'
time: target/linux/install#103.28#115.48#243.17
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/user/lede'
target/Makefile:19: recipe for target '/home/user/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_install' failed
make[1]: *** [/home/user/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/user/lede'
/home/user/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by shenzt68** [comment]
同样问题
