### ISSUE TITLE
NEW WIFI3共享SAMBA服务无法使用

### ISSUE THREAD

**Issue by tdp251** [coolsnowwolf/lede#2469]
usb挂载正常 SAMBA服务匿名拒绝访问 开启root用户可以访问 但看不到U盘文件 读写也被拒绝 求解？

安装的包：
kmod-usb-core 
kmod-usb3
kmod-usb-storage
kmod-usb-storage-extras
block-mount
kmod-usb-uhci
kmod-usb-ohci
kmod-fs-exfat
kmod-fs-ext4
kmod-fs-ntfs
kmod-fs-vfat
block-mount
block
luci-app-samba
luci-i18n-samba-en
samba36-server

**Comment by coolsnowwolf** [comment]
不接受 MTK 问题的提交，自己解决
