### ISSUE TITLE
coremark这个程序容易崩溃！

### ISSUE THREAD

**Issue by outemancut** [coolsnowwolf/lede#2477]
计划任务里面没有0 4 * * * /etc/coremark.sh
然后主机型号后面会出现一串处理器之类的字符
Phicomm K2P (CpuMark : 4599.727849 Scores)
--

![image](https://user-images.githubusercontent.com/53339509/70957960-b7509300-20b2-11ea-844c-64a761dbb6ed.png)

**Comment by EnnawYang** [comment]
这个是跑分程序，跑分完成之后就不会出现在计划任务里面，重启过后才会重新出现

**Comment by DongfeiSay** [comment]
> 这个是跑分程序，跑分完成之后就不会出现在计划任务里面，重启过后才会重新出现

为什么都要跑个分呢

**Comment by HEXtoDEC** [comment]
> > 这个是跑分程序，跑分完成之后就不会出现在计划任务里面，重启过后才会重新出现
> 
> 为什么都要跑个分呢

…我从谷歌而来

这个程序莫名其妙的占用资源，翻完之后发现没卵用，就直接remove了。
