### ISSUE TITLE
AdGuard Home未运行

### ISSUE THREAD

**Issue by yunmi323** [coolsnowwolf/lede#2481]
启用了AdGuard Home显示未运行，更新下面显示no config no bin，是没有内核吗？

**Comment by Aes64X** [comment]
你是用了那个复杂的控制界面吧，那只是个控制面板，简介里说检测不到会自动下载，应该是可写文件系统下。建议还是加一个或者用那个简版的。

**Comment by yunmi323** [comment]
> 你是用了那个复杂的控制界面吧，那只是个控制面板，简介里说检测不到会自动下载，应该是可写文件系统下。建议还是加一个或者用那个简版的。

大雕集成是复杂版？哪里有简版？
不会自动下载。。。手动下载了主程序改好程序路径，提示没有config，坑啊

**Comment by EnnawYang** [comment]
大雕没有集成adg
