### ISSUE TITLE
使用SDK编译ipt2socks提示的错误信息，有人有解决办法吗？libuv能顺利编译出来

### ISSUE THREAD

**Issue by Mackerly** [coolsnowwolf/lede#2484]
CROSS="mips-openwrt-linux-musl-" ARCH="mips" LIBS="-l:libuv_a.a" ;
make[3]: Entering directory '/home/ddddd/Desktop/sdk/sdk/build_dir/target-mips_24kc_musl/ipt2socks/ipt2socks-1.0.2-e6c9b60444bfe2f30830619aacbc67d26ee1015e'
mips-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -pthread  -s -o ipt2socks ipt2socks.o lrucache.o netutils.o  -l:libuv_a.a
/home/ddddd/Desktop/sdk/sdk/staging_dir/toolchain-mips_24kc_gcc-7.3.0_musl/bin/../lib/gcc/mips-openwrt-linux-musl/7.3.0/../../../../mips-openwrt-linux-musl/bin/ld: cannot find -l:libuv_a.a
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:23: ipt2socks] Error 1
make[3]: Leaving directory '/home/ddddd/Desktop/sdk/sdk/build_dir/target-mips_24kc_musl/ipt2socks/ipt2socks-1.0.2-e6c9b60444bfe2f30830619aacbc67d26ee1015e'
make[2]: *** [Makefile:49: /home/ddddd/Desktop/sdk/sdk/build_dir/target-mips_24kc_musl/ipt2socks/ipt2socks-1.0.2-e6c9b60444bfe2f30830619aacbc67d26ee1015e/.built] Error 2
make[2]: Leaving directory '/home/ddddd/Desktop/sdk/sdk/package/ipt2socks'
time: package/ipt2socks/compile#0.20#0.04#0.55
make[1]: *** [package/Makefile:113: package/ipt2socks/compile] Error 2
make[1]: Leaving directory '/home/ddddd/Desktop/sdk/sdk'
make: *** [/home/ddddd/Desktop/sdk/sdk/include/toplevel.mk:211: package/ipt2socks/compile] Error 2

**Comment by wk8838299** [comment]
同样遇到这个问题
