### ISSUE TITLE
ssr plus状态正常，但是手机链接wifi后无法翻墙

### ISSUE THREAD

**Issue by YuzhouZhang** [coolsnowwolf/lede#2488]
![微信截图_20191218123054](https://user-images.githubusercontent.com/8024428/71055905-47193e80-2192-11ea-8926-77535b40511f.png)
`

Wed Dec 18 12:24:27 2019 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Dec 18 12:24:27 2019 daemon.warn hostapd: wlan0: Could not connect to kernel driver
Wed Dec 18 12:24:27 2019 daemon.err hostapd: Using interface wlan0 with hwaddr b8:27:eb:cc:2d:47 and ssid "OpenWrt"
Wed Dec 18 12:24:27 2019 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->ENABLED
Wed Dec 18 12:24:27 2019 daemon.notice hostapd: wlan0: AP-ENABLED
Wed Dec 18 12:24:27 2019 daemon.notice netifd: Network device 'wlan0' link is up
Wed Dec 18 12:24:27 2019 daemon.notice netifd: lan (1350): udhcpc: performing DHCP renew
Wed Dec 18 12:24:27 2019 daemon.notice netifd: lan (1350): udhcpc: sending discover
Wed Dec 18 12:24:28 2019 daemon.notice netifd: lan (1350): udhcpc: sending select for 192.168.31.151
Wed Dec 18 12:24:28 2019 daemon.notice netifd: lan (1350): udhcpc: lease of 192.168.31.151 obtained, lease time 43200
Wed Dec 18 12:24:28 2019 daemon.notice netifd: Interface 'lan' is now up
Wed Dec 18 12:24:28 2019 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Wed Dec 18 12:24:47 2019 daemon.info hostapd: wlan0: STA 96:af:ac:24:0e:9d IEEE 802.11: associated
Wed Dec 18 12:24:47 2019 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 96:af:ac:24:0e:9d
Wed Dec 18 12:24:47 2019 daemon.info hostapd: wlan0: STA 96:af:ac:24:0e:9d WPA: pairwise key handshake completed (WPA)
Wed Dec 18 12:24:47 2019 daemon.info hostapd: wlan0: STA 96:af:ac:24:0e:9d WPA: group key handshake completed (WPA)
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2061]: initializing ciphers... chacha20-ietf-poly1305
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2061]: listening at 0.0.0.0:1234
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2061]: tcp port reuse enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2061]: running from root user
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2063]: initializing ciphers... chacha20-ietf-poly1305
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2063]: listening at 0.0.0.0:1234
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2063]: tcp port reuse enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2063]: running from root user
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2065]: initializing ciphers... chacha20-ietf-poly1305
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2065]: listening at 0.0.0.0:1234
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2065]: tcp port reuse enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2065]: running from root user
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2067]: initializing ciphers... chacha20-ietf-poly1305
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2067]: listening at 0.0.0.0:1234
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2067]: tcp port reuse enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2067]: running from root user
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: initializing ciphers... chacha20-ietf-poly1305
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: listening at 0.0.0.0:1234
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: UDP relay enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: udp port reuse enabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: TCP relay disabled
Wed Dec 18 12:24:49 2019 daemon.info /usr/bin/ss-redir[2092]: running from root user
Wed Dec 18 12:24:50 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Dec 18 12:24:50 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses

`

![微信截图_20191218122746](https://user-images.githubusercontent.com/8024428/71055769-d540f500-2191-11ea-91ac-b11e4eb6bad0.png)

![image](https://user-images.githubusercontent.com/8024428/71055814-f6a1e100-2191-11ea-8110-466ca6a6b5c4.png)

**Comment by coolsnowwolf** [comment]
手机DNS 问题
