### ISSUE TITLE
L大,还请麻烦你查一下那个上网时间控制插件.

### ISSUE THREAD

**Issue by snakwu** [coolsnowwolf/lede#2491]
我发现问题是出在这两行iptables上面,只要一添加,就全部设备不能上网

iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53 -m comment --comment "Rule For Control"
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53 -m comment --comment "Rule For Control"

**Comment by coolsnowwolf** [comment]
你的 DNS 有问题，例如装了 smartdns 之类

**Comment by snakwu** [comment]
我没有安装任何的dns在openwrt上面，要说有的就只有pdns，我的dns在op的dhcp设置里面直接转发到一鼐非53端口的dns服务器上的

**Comment by coolsnowwolf** [comment]
默认

**Comment by snakwu** [comment]
我先表述一下我的环境吧：
19168.188.100，这个是我的一个安装了coerdns的一台dns服务机用的是8853端口的，然后在oprnwrt里面的dhcp设置设置dns转发到192.168.188.100：8853上面去，然后其他所有设备的dns都是设置为openwrt的地址也就是192.168.188.1

**Comment by coolsnowwolf** [comment]
这就是原因了

**Comment by snakwu** [comment]
然后我测试，我直接不转dns,同样问题

**Comment by snakwu** [comment]
其实,我所有设备都是用53请求的openwrt本身为dns
