### ISSUE TITLE
请问lede menuconfig 多了个XIAOMI R3G V2是做什么的?

### ISSUE THREAD

**Issue by yonggedebaqi** [coolsnowwolf/lede#2497]
请问lede menuconfig 多了个XIAOMI R3G V2是做什么的?

**Comment by fr0zenrain** [comment]
小米即将出的新型号吧？

昨天自己编了一下，breed刷入提示无法识别固件，我打算放弃了，不编固件了，要什么就在路由上编了，编整个系统太蛋疼了。

**Comment by yonggedebaqi** [comment]
多谢

**Comment by caicaicai21** [comment]
我看了下OpenWrt的说明，XIAOMI R3G V2好像是小米4A千兆版的国外版本(16M FLASH+128M RAM)，不是小米3G，小米3G选XIAOMI R3G就行了。
https://openwrt.org/toh/xiaomi/mir3g
