### ISSUE TITLE
smartdns +trojan走5335端口似乎通不了

### ISSUE THREAD

**Issue by realsteam** [coolsnowwolf/lede#2498]
开了smartdns端口是5335，科学网络使用5335端口的dns+trojan，访问ip能通墙，但是访问域名不通，检查状态也是错误，但是TG可以上，是设置问题，还是其他bug呢？国内各个网页访问都正常

**Comment by coolsnowwolf** [comment]
如果用 smartdns，一切dns 内在问题自己解决。如果你搞不清楚内在逻辑的话，就用内置

**Comment by qdmc2010** [comment]
若干年后，我也遇到了这个问题。V2ray能通，trojan不行

**Comment by oversxxx** [comment]
又过了N久，我也遇到类似问题，6053端口，v2ray可以出国，trojan却不行。关闭smartdns，就都正常了
