### ISSUE TITLE
Failed at building Zen Core Architecture.

### ISSUE THREAD

**Issue by RayYu1993** [coolsnowwolf/lede#2500]
It was success to build a normal x86_64 version, but always failed at AMD Ryzen (The Zen Core Architecture) subtarget. I tried different version of ubuntu, they all failed with same error:

`ERROR: module '/home/yu_lei199309/lede/build_dir/target-x86_64_znver1_musl/linux-x86_zen/linux-4.19.88/arch/x86/crypto/twofish-i586.ko' is missing.
modules/crypto.mk:581: recipe for target '/home/yu_lei199309/lede/bin/targets/x86/zen/packages/kmod-crypto-misc_4.19.88-1_x86_64_znver1.ipk' failed
make[3]: *** [/home/yu_lei199309/lede/bin/targets/x86/zen/packages/kmod-crypto-misc_4.19.88-1_x86_64_znver1.ipk] Error 1
make[3]: Leaving directory '/home/yu_lei199309/lede/package/kernel/linux'
time: package/kernel/linux/compile#3.47#0.38#3.84
package/Makefile:107: recipe for target 'package/kernel/linux/compile' failed
make[2]: *** [package/kernel/linux/compile] Error 2
make[2]: Leaving directory '/home/yu_lei199309/lede'
package/Makefile:103: recipe for target '/home/yu_lei199309/lede/staging_dir/target-x86_64_znver1_musl/stamp/.package_compile' failed
make[1]: *** [/home/yu_lei199309/lede/staging_dir/target-x86_64_znver1_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/yu_lei199309/lede'
/home/yu_lei199309/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
`

**Comment by coolsnowwolf** [comment]
solved
