### ISSUE TITLE
Luci的刷新软件包不可用

### ISSUE THREAD

**Issue by HinataKato** [coolsnowwolf/lede#2503]
CLI的wget可用HTTPS下载，opkg update也无错误，升级 ca-bundle，ca-certificates 也不行
全是
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.

**Comment by Her0R0cket** [comment]
wget里把ssl选上

**Comment by HinataKato** [comment]
> wget里把ssl选上

有具体点的路径吗，我的是GitHubAction编译…

**Comment by Her0R0cket** [comment]
看了下菜单,wget默认是支持ssl的版本,你要在你编译文件里添上这一行
CONFIG_PACKAGE_libustream-openssl=y

具体哪里,我只看看了置顶issues里的说明,应该是放在常用软件包下

**Comment by HinataKato** [comment]
> 看了下菜单,wget默认是支持ssl的版本,你要在你编译文件里添上这一行
> CONFIG_PACKAGE_libustream-openssl=y
> 
> 具体哪里,我只看看了置顶issues里的说明,应该是放在常用软件包下

我试过手动装这个，可是网页还是不能更新，所以是必须编译到固件里面吗
