### ISSUE TITLE
小白求助~运行 make package/feeds/luci/luci-base/compile V=99失败

### ISSUE THREAD

**Issue by alvinxhc** [coolsnowwolf/lede#2509]
alvin@ubuntu-trusty-1:~/lede$ make package/feeds/luci/luci-base/compile V=99 -j1make[1]: Entering directory `/home/alvin/lede'
make[2]: Entering directory `/home/alvin/lede/feeds/luci/modules/luci-base'
make[2]: Leaving directory `/home/alvin/lede/feeds/luci/modules/luci-base'
time: package/feeds/luci/luci-base/host-compile#0.06#0.01#1.32
make[2]: Entering directory `/home/alvin/lede/package/libs/toolchain'
rm -rf /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
mkdir -p /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc
install -d -m0755 /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /home/alvin/lede/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so* /home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/home/alvin/lede/staging_dir/toolchain-x86_64_gcc-7.5.0_musl/lib/ld-musl-*.so*': No such file or directory
make[2]: *** [/home/alvin/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory `/home/alvin/lede/package/libs/toolchain'
time: package/libs/toolchain/compile#0.03#0.00#0.12
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory `/home/alvin/lede'
make: *** [package/feeds/luci/luci-base/compile] Error 2

已运行./scripts/feeds update -a &&  ./scripts/feeds install -a

**Comment by coolsnowwolf** [comment]
先编译一次
