### ISSUE TITLE
编译过程中有个在线资源包不存在了，请问如何更改

### ISSUE THREAD

**Issue by hnxxd** [coolsnowwolf/lede#2512]
下面这个包已经不存在了，其他版本的包都在
https://downloads.sourceforge.net/boost/boost/1.71.0/boost_1_71_0.tar.bz2
如何把编译的时候指定上面的包改成
https://downloads.sourceforge.net/boost/boost/1.72.0/boost_1_72_0.tar.bz2

**Comment by Her0R0cket** [comment]
boost_1_71_0.tar.bz2  用这个包名搜下下载链接,手动下载,扔到dl目录下,云编译的话当我没说,因为这个配置文件在packages源里,你要改的话要fork packages源,还要改编译配置文件

**Comment by 1715173329** [comment]
不必担心，boost拥有多个下载源
即使一个下载源出现问题，也可以使用其他源正常下载
