### ISSUE TITLE
管理界面软件包安装后无配置菜单

### ISSUE THREAD

**Issue by zqdongxw** [coolsnowwolf/lede#2518]
在编译选项配置时，标记为M的插件，在luci管理界面上找不到功能菜单（这是正常的吧），在软件包安装里单独安装后还是找不到配置菜单，比如aria2。而且，在页面进行软件安装时时常会出现Bad Gateway的情况。
相关尝试：1、重启管理界面服务  2、 重启设备      仍然无效。
目前正重新配置编译。

**Comment by coolsnowwolf** [comment]
废了，只装软件不装luci 当然不会有luci

**Comment by zqdongxw** [comment]
意思是说要同时安装 aria2 和 luci-app-aria2   对吧？
