### ISSUE TITLE
能否优化PKG_SOURCE_VERSION,让软件包始终保持最新

### ISSUE THREAD

**Issue by garypang13** [coolsnowwolf/lede#2524]
很多Makefile文件中的PKG_SOURCE_VERSION都没及时更新,导致很多软件包都是老版本,能否增加选项,比如PKG_SOURCE_VERSION:=latest 就是默认下载最新的源码.而不是必须填写 commit id, 我试了直接去掉PKG_SOURCE_VERSION发现有些软件包会报错,有些软件包没问题,会下载最新的源码.

**Comment by garypang13** [comment]
把/include/download.mk 206行
git checkout $(VERSION) && \  改为 git checkout $(VERSION) ; \ 
软件包Makefile文件中的PKG_SOURCE_VERSION:=latest就会默认下载最新源码,

**Comment by keivenliao** [comment]
最新的，有可能会引起兼容性问题哦。 还是确定稳定了。再升级会比较稳妥吧。
