### ISSUE TITLE
发现挂载设置的一个坑，希望可以修复这个问题！

### ISSUE THREAD

**Issue by xinpenghan** [coolsnowwolf/lede#2535]
1、初安装固件后，我有时候会在安装一些插件，这样就需要完整备份overlay文件夹，达到完整备份配置。但是初安装的时候overlay文件夹是挂载在根目录的。

2、但是千万不要在挂载点设置里点保存和应用按钮，如果点击保存应用后，挂载配置文件就会更改，然后重启路由器，发现overlay文件夹的挂载路径就会变成/rom/overlay。

3、如果重新刷固件，在使用点挂载保存按钮备份前生成的备份文件恢复固件设置时，就会使之前安装的软件全部都丢失。因为overlay目录路径不正确。如果不知道的这个的人只能重新设置非常麻烦。

希望可以修复这个问题，谢谢！

**Comment by ch1993128** [comment]
每次手动挂载samba的飘过。。。。双硬盘挂载也有问题
