### ISSUE TITLE
今天新编译固件 发现ddns aliyun的没有了

### ISSUE THREAD

**Issue by BB-pig** [coolsnowwolf/lede#2538]
![BaiduShurufa_2019-12-21_21-55-57](https://user-images.githubusercontent.com/57258094/71308904-bb770a80-243c-11ea-9bd6-71c6f4a3d05f.png)

**Comment by hxlls** [comment]
要自己勾选。。

**Comment by BB-pig** [comment]
12-02编译都还有的  今晚重新编译 懵了 找不到 也不知在哪勾选  谷歌下看看先

**Comment by BB-pig** [comment]
12-02编译都还有的今晚重新编译懵了找不到也不知在哪插入谷歌下看看先
