### ISSUE TITLE
编译x86一直报错 下面是错误信息  编译硬路由的就没问题 内核是4.9

### ISSUE THREAD

**Issue by tieba123** [coolsnowwolf/lede#2539]
x86_64-openwrt-linux-musl-g++ -Os -pipe '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=0' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DHAVE_OPENSSL=1' -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I../src -I/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj/gen -I../deps/v8/include -I../deps/cares/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/.deps//home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_debug_options.o.d.raw  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1:node-v8.16.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/pc/openwrt/staging_dir/target-x86_64_musl/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include/fortify -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include  -c -o /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_debug_options.o ../src/node_debug_options.cc
  x86_64-openwrt-linux-musl-g++ -Os -pipe '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=0' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DHAVE_OPENSSL=1' -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I../src -I/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj/gen -I../deps/v8/include -I../deps/cares/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/.deps//home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_encoding.o.d.raw  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1:node-v8.16.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/pc/openwrt/staging_dir/target-x86_64_musl/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include/fortify -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include  -c -o /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_encoding.o ../src/node_encoding.cc
  x86_64-openwrt-linux-musl-g++ -Os -pipe '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=0' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DHAVE_OPENSSL=1' -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I../src -I/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj/gen -I../deps/v8/include -I../deps/cares/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/.deps//home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_file.o.d.raw  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1:node-v8.16.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/pc/openwrt/staging_dir/target-x86_64_musl/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include/fortify -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include  -c -o /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_file.o ../src/node_file.cc
  x86_64-openwrt-linux-musl-g++ -Os -pipe '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_OPENSSL_SYSTEM_CERT_PATH=""' '-DHAVE_INSPECTOR=0' '-D__POSIX__' '-DNODE_USE_V8_PLATFORM=1' '-DHAVE_OPENSSL=1' -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I../src -I/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj/gen -I../deps/v8/include -I../deps/cares/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/.deps//home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_http2.o.d.raw  -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1:node-v8.16.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/pc/openwrt/staging_dir/target-x86_64_musl/usr/include -I/home/pc/openwrt/staging_dir/target-x86_64_musl/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/usr/include -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include/fortify -I/home/pc/openwrt/staging_dir/toolchain-x86_64_gcc-7.4.0_musl/include  -c -o /home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_http2.o ../src/node_http2.cc
../src/node_http2.cc: In constructor 'node::http2::Http2Options::Http2Options(node::Environment*, node::http2::nghttp2_session_type)':
../src/node_http2.cc:148:5: error: 'nghttp2_option_set_max_outbound_ack' was not declared in this scope
     nghttp2_option_set_max_outbound_ack(options_, 10000);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node_http2.cc:148:5: note: suggested alternative: 'nghttp2_option_set_no_auto_ping_ack'
     nghttp2_option_set_max_outbound_ack(options_, 10000);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     nghttp2_option_set_no_auto_ping_ack
node_lib.target.mk:158: recipe for target '/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_http2.o' failed
make[5]: *** [/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/out/Release/obj.target/node_lib/src/node_http2.o] Error 1
rm c369c5fb329d51b06fabfba1ed164bcf0a9024cf.intermediate
Makefile:88: recipe for target 'node' failed
make[4]: *** [node] Error 2
make[4]: Leaving directory '/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1'
Makefile:133: recipe for target '/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/.built' failed
make[3]: *** [/home/pc/openwrt/build_dir/target-x86_64_musl/node-v8.16.1/.built] Error 2
make[3]: Leaving directory '/home/pc/openwrt/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#1232.80#89.02#1314.30
package/Makefile:107: recipe for target 'package/feeds/packages/node/compile' failed
make[2]: *** [package/feeds/packages/node/compile] Error 2
make[2]: Leaving directory '/home/pc/openwrt'
package/Makefile:103: recipe for target '/home/pc/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/pc/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/pc/openwrt'
/home/pc/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by hcym** [comment]
4.9不应该，4.19的不能用mac80211，其它的包括4.14都没问题
