### ISSUE TITLE
nodejs能否添加上这几个？

### ISSUE THREAD

**Issue by nature2608** [coolsnowwolf/lede#2546]
从别的地方拷过来的makefile都不能编译成功
[我是从这里拷的](https://github.com/nxhack/openwrt-node-packages/tree/lede-17.01)
希望能添加：
1、node-hap-nodejs
2、node-node-red-contrib-homekit
3、node-node-red
感谢~

**Comment by outemancut** [comment]
https://github.com/nxhack/openwrt-node-packages/tree/openwrt-18.06 里面有的你就加

**Comment by nature2608** [comment]
@outemancut 是有，但是编译不过
