### ISSUE TITLE
为什么有的可以自定义DNS，有的没有了？？

### ISSUE THREAD

**Issue by ppp47** [coolsnowwolf/lede#2552]
![没有自定义](https://user-images.githubusercontent.com/59086679/71344124-ac0ed300-259c-11ea-8f57-eb28c8c509c8.PNG)
![有自定义](https://user-images.githubusercontent.com/59086679/71344125-ac0ed300-259c-11ea-9d00-e8d9137d3253.PNG)

**Comment by coolsnowwolf** [comment]
因为就是不想你自定义，默认list 的就已经是最好的 DNS 服务器了

**Comment by eallion** [comment]
台北101
```
101.101.101.101
```

**Comment by ppp47** [comment]
> 台北101
> 
> ```
> 101.101.101.101
> ```
没有自定义添加不进去啊。

**Comment by ppp47** [comment]
> 因为就是不想你自定义，默认列表的就已经是最好的DNS服务器了

还是希望有自定义的选项。。
