### ISSUE TITLE
无线网卡启动时间过长

### ISSUE THREAD

**Issue by mzjdy** [coolsnowwolf/lede#2553]
大吊，我的x86-64版本，网卡是QCA9880，启动的时侯会有如下提示：
[    9.238077] ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/QCA988X/hw2.0/firmware-6.bin failed with error -2
[    9.238473] ath10k_pci 0000:05:00.0: Falling back to user helper
[    9.241382] firmware ath10k!QCA988X!hw2.0!firmware-6.bin: firmware_loading_store: map pages failed
[    9.283284] ath10k_pci 0000:05:00.0: qca988x hw2.0 target 0x4100016c chip_id 0x043202ff sub 0000:0000
[    9.283587] ath10k_pci 0000:05:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[    9.284926] ath10k_pci 0000:05:00.0: firmware ver 10.2.4-1.0-00041 api 5 features no-p2p,raw-mode,mfp,allows-mesh-bcast crc32 f43fa422
[    9.318424] ath10k_pci 0000:05:00.0: Direct firmware load for ath10k/QCA988X/hw2.0/board-2.bin failed with error -2
[    9.318741] ath10k_pci 0000:05:00.0: Falling back to user helper
[    9.320653] firmware ath10k!QCA988X!hw2.0!board-2.bin: firmware_loading_store: map pages failed
[    9.322194] ath10k_pci 0000:05:00.0: board_file api 1 bmi_id N/A crc32 bebc7c08
[   10.466215] ath10k_pci 0000:05:00.0: htt-ver 2.1 wmi-op 5 htt-op 2 cal otp max-sta 128 raw 0 hwcrypto 1
[   10.581403] ath: EEPROM regdomain: 0x0
[   10.581405] ath: EEPROM indicates default country code should be used
[   10.581406] ath: doing EEPROM country->regdmn map search

但是在那个Falling back to user helper处会卡两分钟才走下去
我看到恩山上有个555的哥们编绎你的固件不会在这里卡两分钟，请问大吊有没有什么方法修改一下，我摸索了个把月还没找到原因，实在是没辙了

**Comment by AmadeusGhost** [comment]
关掉Falling back to user helper
