### ISSUE TITLE
希望多添加几个主题

### ISSUE THREAD

**Issue by ppp47** [coolsnowwolf/lede#2555]
例如
https://github.com/openwrt-develop/luci-theme-atmaterial
https://github.com/rosywrt/luci-theme-rosy
https://github.com/LuttyYang/luci-theme-material
https://github.com/jerrykuku/luci-theme-argon
https://github.com/apollo-ng/luci-theme-darkmatter
https://github.com/yichya/luci-theme-xeye
https://github.com/ArthurDrc/luci-theme-greenshit
https://github.com/ComputerFanboy/luci-bootstrap-dark-css
https://github.com/Aeneon/luci-theme-nightstrap
https://github.com/yichya/luci-theme-openwrt-custom
https://github.com/john-shine/luci-theme-darkmatter

**Comment by sqliuchang** [comment]
自己clone到package文件夹就行了啊

**Comment by ppp47** [comment]
> 自己clone到package文件夹就行了啊
我去试一下
