### ISSUE TITLE
make[5]: config/install-sh: Command not found

### ISSUE THREAD

**Issue by liuquanhao** [coolsnowwolf/lede#2556]
按照wiki，编译出错了，编译的是glinet-usb150
系统：
`vagrant@vagrant-ubuntu-trusty-64:~/lede$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
`

history：
`
  148  proxychains4 git clone https://github.com/coolsnowwolf/lede
  149  ls
  150  cd lede/
  151  ls
  152  sudo chown vagrant:vagrant -R .
  153  ls -al
  154  ./scripts/feeds update -a
  155  ./scripts/feeds install -a
  156  make clean
  157  make deconfig
  158  make menuconfig
  159  sudo chown vagrant:vagrant -R .
  160  proxychains4 make -j1 V=s
`
报错信息：
`
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
make[5]: Entering directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/lib/ext2fs'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/lib/ext2fs'
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
making all in intl
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
make[5]: Entering directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/intl'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/intl'
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
making install in e2fsck
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
make[5]: Entering directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/e2fsck'
[proxychains] DLL init: proxychains-ng 4.14-git-8-gb8fa2a7
	MKDIR_P /home/vagrant/lede/staging_dir/host/bin /home/vagrant/lede/staging_dir/host/share/man/man8
make[5]: config/install-sh: Command not found
make[5]: *** [installdirs] Error 127
make[5]: Leaving directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5/e2fsck'
make[4]: *** [install-progs-recursive] Error 1
make[4]: Leaving directory `/home/vagrant/lede/build_dir/host/e2fsprogs-1.44.5'
make[3]: *** [/home/vagrant/lede/staging_dir/host/stamp/.e2fsprogs_installed] Error 2
make[3]: Leaving directory `/home/vagrant/lede/tools/e2fsprogs'
time: tools/e2fsprogs/compile#18.30#7.22#128.95
make[2]: *** [tools/e2fsprogs/compile] Error 2
make[2]: Leaving directory `/home/vagrant/lede'
make[1]: *** [/home/vagrant/lede/staging_dir/target-mips_24kc_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnnyyyyyyyyyyyyyyyyyyyynnyynynyyyynnyyy] Error 2
make[1]: Leaving directory `/home/vagrant/lede'
make: *** [world] Error 2
`

**Comment by coolsnowwolf** [comment]
make clean
