### ISSUE TITLE
R752, 0109最新源码，EA8500编译成功，无线设备也可以连上，但是。。。

### ISSUE THREAD

**Issue by chd1998** [coolsnowwolf/lede#256]
所有无线设备无法上网，稍晚上日志。。。

**Comment by chd1998** [comment]
R753,0111最新源码，编译成功后，又出现同样的问题：无线设备可以连上，但是无法上网。。。

**Comment by gavin219** [comment]
检查一下lan的设置。我的wrt3200也是.lan的物理接口为eth0，但是在物理设置里多了一个eth0.1，去掉就ok了

**Comment by chd1998** [comment]
好的，谢谢。我检查一下。。。
