### ISSUE TITLE
Adbyby Plus+处理过的流量能否再次转发？

### ISSUE THREAD

**Issue by fs20sc** [coolsnowwolf/lede#2565]
路由用广告屏蔽大师 plus+来给电视盒子过滤广告，看了下iptable，是把tcp流量转发给adbyby来处理 ，不过，想再把这个流量交给ss/v2ray/clash等，再做分流，从iptable上着手，貌似无法实现了。
不知道Adbyby Plus+内部能否加多一个转发选项？通过的流量直接再转发到某个端口？这样子再次分流就方便多了。

**Comment by coolsnowwolf** [comment]
你单独对盒子开全局就行了，会再自动交给 XXR Plus 转发分流
