### ISSUE TITLE
如何编译群晖vmm虚拟机用的lede固件?

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#2567]
网上搜了下各种帖子,看到的都是用koolshare的lede固件,但是我不想用koolshare的,我想用大雕的固件自己编译，然后搜了下不知道怎么编译出来给vmm虚拟机用的固件，请问可否指导一下？

**Comment by BG4QXW** [comment]
Github actions

**Comment by bonnyandsky** [comment]
胡乱编译了一个x86 64的固件，然后跑到群晖虚拟机里面装了下，居然可以用。
