### ISSUE TITLE
希望ssr里的sock5 代理，建议加上v2ray的节点可用

### ISSUE THREAD

**Issue by xiaoluoabc123** [coolsnowwolf/lede#2572]
希望ssr里的sock5 代理，建议加上v2ray的节点,现在选v2ray，sock5不能用，全局浏览器和游戏加速很不房版

**Comment by zhanghao1989** [comment]
V2ray 服务器 搭建socks

**Comment by cnclg** [comment]
记的原来有一个朋友做了一个lua,现在找不到了。有需要楼主可以搜索一下。

**Comment by coolsnowwolf** [comment]
选择 V2ray 服务器 编译，里面就有
