### ISSUE TITLE
建议集成 OpenClash 

### ISSUE THREAD

**Issue by soffchen** [coolsnowwolf/lede#2574]
方便一些需要订阅或者自定义 clash 配置的

https://github.com/vernesong/OpenClash

**Comment by eallion** [comment]
自己动手。。

**Comment by eallion** [comment]
![FlameShot_2019-12-25_132837](https://user-images.githubusercontent.com/1698841/71433495-7b54a800-271a-11ea-88e7-d0409bb8cc6b.png)

官方 [README.md](https://github.com/vernesong/OpenClash/blob/master/README.md#%E7%BC%96%E8%AF%91) 已经写得很清楚了

**Comment by soffchen** [comment]
> ![FlameShot_2019-12-25_132837](https://user-images.githubusercontent.com/1698841/71433495-7b54a800-271a-11ea-88e7-d0409bb8cc6b.png)
> 
> 官方 [README.md](https://github.com/vernesong/OpenClash/blob/master/README.md#%E7%BC%96%E8%AF%91) 已经写得很清楚了

这个我也会呀，这不是给大家方便刷嘛。
