### ISSUE TITLE
torjan无法运行？

### ISSUE THREAD

**Issue by aaaisan** [coolsnowwolf/lede#2580]
填写了服务器，端口，密码后无法连接，请问ssr++的torjan配置文件在哪里？

**Comment by chchia** [comment]
trojan 可以运行，先确保服务器可连接（用客户端先试试），可试看我以下的配置。

![image](https://user-images.githubusercontent.com/1291771/71444623-b0c6b900-274d-11ea-9d0f-92a383771c48.png)
