### ISSUE TITLE
ssr黑白名单域名无效问题

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#2588]
在这边域名怎么填写？比如说我想让https://github.com/始终通过代理，是填写github.com就可以了么？
如果有www开头的网址呢？*.baidu.com这样？我试了下好像不起作用

![QQ图片20191226111538](https://user-images.githubusercontent.com/30990861/71455696-27f16100-27d1-11ea-9faa-d26ca11b03f8.png)

**Comment by snakwu** [comment]
.github.com

**Comment by lphgor** [comment]
看自带的列表，应该直接填一级域名就好了。
https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-ssr-plus/root/etc/config/gfw.list

**Comment by bonnyandsky** [comment]
> 看自带的列表，应该直接填一级域名就好了。
> https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-ssr-plus/root/etc/config/gfw.list

看了下github默认已经在列表里面了，所以应该会自动走代理喽？可是我下载编译好的固件还是很慢，开全局代理就快了。

**Comment by lphgor** [comment]
> 看了下github默认已经在列表里面了，所以应该会自动走代理喽？可是我下载编译好的固件还是很慢，开全局代理就快了。

从github下载，需要添加这个域名：
`githubusercontent.com`

**Comment by bonnyandsky** [comment]
> githubusercontent.com

我刚才用一个没用的节点设置了代理。然后哦用baidu做测试，结果没效果

**Comment by hcym** [comment]
白名单有效，黑的没用过不知道，应该差不多吧

**Comment by xinpenghan** [comment]
我一般用访问控制设置强制走代理的域名

**Comment by xinpenghan** [comment]
试试这个配置
github.com
gstatic.com
avatars0.githubusercontent.com
avatars1.githubusercontent.com
avatars2.githubusercontent.com
avatars3.githubusercontent.com
githubapp.com
www.ipip.net
ipip.net
ggpht.com
googleapis.com
githubusercontent.com
googletagmanager.com
googlevideo.com
gstatic.com
ytimg.com
youtube.com
youtube-nocookie.com
youtubeeducation.com
youtu.be
yt.be

**Comment by bonnyandsky** [comment]
> 试试这个配置，我正好更新一下
> github.com
> gstatic.com
> avatars0.githubusercontent.com
> avatars1.githubusercontent.com
> avatars2.githubusercontent.com
> avatars3.githubusercontent.com
> actions.githubusercontent.com
> github.githubassets.com
> api.github.com
> gist.github.com
> help.github.com
> github-cloud.s3.amazonaws.com
> user-images.githubusercontent.com
> live.github.com
> githubapp.com
> githubassets.com
> schema.org
> [www.ipip.net](http://www.ipip.net)
> ipip.net
> ggpht.com
> googleapis.com
> githubusercontent.com
> googletagmanager.com
> googlevideo.com
> gstatic.com
> ytimg.com
> youtube.com
> youtube-nocookie.com
> youtubeeducation.com
> youtu.be
> yt.be

修改在那个文件

**Comment by xinpenghan** [comment]
> > 试试这个配置，我正好更新一下
> > github.com
> > gstatic.com
> > avatars0.githubusercontent.com
> > avatars1.githubusercontent.com
> > avatars2.githubusercontent.com
> > avatars3.githubusercontent.com
> > actions.githubusercontent.com
> > github.githubassets.com
> > api.github.com
> > gist.github.com
> > help.github.com
> > github-cloud.s3.amazonaws.com
> > user-images.githubusercontent.com
> > live.github.com
> > githubapp.com
> > githubassets.com
> > schema.org
> > [www.ipip.net](http://www.ipip.net)
> > ipip.net
> > ggpht.com
> > googleapis.com
> > githubusercontent.com
> > googletagmanager.com
> > googlevideo.com
> > gstatic.com
> > ytimg.com
> > youtube.com
> > youtube-nocookie.com
> > youtubeeducation.com
> > youtu.be
> > yt.be
> 
> 修改在那个文件

在ShadowSocksR Plus+ 里找到访问控制添加强制走代理的域名，将下面这些添加进去
刚新调整了一下，gfw模式下用github应该没问题了
github.com
gstatic.com
github.githubassets.com
translate.googleapis.com
avatars0.githubusercontent.com
avatars1.githubusercontent.com
avatars2.githubusercontent.com
avatars3.githubusercontent.com
actions.githubusercontent.com
user-images.githubusercontent.com
api.github.com
gist.github.com
help.github.com
github-cloud.s3.amazonaws.com
live.github.com
githubapp.com
githubassets.com
schema.org
www.ipip.net
ipip.net
ggpht.com
googleapis.com
googletagmanager.com
googlevideo.com
gstatic.com
ytimg.com
youtube.com
youtube-nocookie.com
youtubeeducation.com
youtu.be
yt.be

**Comment by ManaStuDent** [comment]
不知道有没有人遇到过添加白名单了，Chrome浏览器无效，Safari 火狐有效。

**Comment by qq280948982** [comment]
我也这个问题，在Black domain list里填写了想要强制使用代理的域名，但是迟终没有走代理

**Comment by maodou38** [comment]
没什么用啊 根本就  我强制走代理写了个baidu.com 还是走直连
