### ISSUE TITLE
R7.5.3 gettext version Error

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#259]
make[3]: Entering directory '/home/waterun/lede-lean/lede/feeds/packages/libs/gdbm'
rm -f /home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/.built
touch /home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/.built_check
make -j1 -C /home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11 BINOWN=`id -u` BINGRP=`id -g` DESTDIR="/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/ipkg-install" all install
make[4]: Entering directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11'
make  all-recursive
make[5]: Entering directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11'
Making all in po
make[6]: Entering directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/po'
*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19
Makefile:181: recipe for target 'check-macro-version' failed
make[6]: *** [check-macro-version] Error 1
make[6]: Leaving directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/po'
Makefile:453: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11'
Makefile:385: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11'
Makefile:69: recipe for target '/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/.built' failed
make[3]: *** [/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/.built] Error 2
make[3]: Leaving directory '/home/waterun/lede-lean/lede/feeds/packages/libs/gdbm'
package/Makefile:105: recipe for target 'package/feeds/packages/gdbm/compile' failed
make[2]: *** [package/feeds/packages/gdbm/compile] Error 2
make[2]: Leaving directory '/home/waterun/lede-lean/lede'
package/Makefile:101: recipe for target '/home/waterun/lede-lean/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/waterun/lede-lean/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/waterun/lede-lean/lede'
/home/waterun/lede-lean/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by sonusyws** [comment]
一样问题

**Comment by kingyan** [comment]
'/home/waterun/lede-lean/lede/build_dir/target-x86_64_musl/gdbm-1.11/po
这个目录下的Makefile.in.in文件里的第一行版本号，把0.18改成0.19
