### ISSUE TITLE
GFW列表一直都是5207条？

### ISSUE THREAD

**Issue by iamggs** [coolsnowwolf/lede#2603]
感觉一直都是5207条，就没更新过了，你们呢？

> 【GFW列表】数据库 5207 条记录
> 【国内IP段】数据库 8470 条记录

**Comment by ManaStuDent** [comment]
同问，在系统目录下，GFW文件在哪里？
/etc/config/gfw.list
/mnt/loop0/upper/etc/config/gfw.list
/overlay/upper/etc/config/gfw.list
/rom/etc/config/gfw.list
都只有 53 行数据，5207 条的数据文件应该在哪里编辑？

**Comment by MxCen** [comment]
一样的。没有更新。

**Comment by GDZmax** [comment]
好像更新源地址，不在更新了，得换一个在更新的源地址才行，等着大佬更新更换这个地址
