### ISSUE TITLE
SSR Plus配搭smartdns问题

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#2605]
只想smardns解释国内网站,翻出去就走SSR plus DNS解释用PDNSD,WAN口DNS是电信拨号分配出来的DNS,LAN口DNS设为:192.168.1.1,我用nslookup youtube.com解释出来只有一个IP,翻出去好像在走smartdns,还是这样设置是正确的
![image](https://user-images.githubusercontent.com/41529838/71509624-e9d66900-28c6-11ea-8250-1ef1a719e723.png)

![image](https://user-images.githubusercontent.com/41529838/71509526-995f0b80-28c6-11ea-9af2-127580465592.png)

![image](https://user-images.githubusercontent.com/41529838/71509534-a2e87380-28c6-11ea-9514-544fdda30e17.png)

![image](https://user-images.githubusercontent.com/41529838/71509708-3e79e400-28c7-11ea-8806-b68aacb5cd74.png)

**Comment by xinpenghan** [comment]
smartdns只解析国内，就不应该加国外dns了，smartdns设置重定向为上游，然后查看Dnsmasq 里面的DNS 转发设置是否设置成功，然后清理电脑dns缓存再试

**Comment by dengchan0416** [comment]
@xinpenghan 请问怎样查看Dnsmasq设置
