### ISSUE TITLE
请教各位大神，问个小白的问题，咱们升级内核具体作用是什么呢？

### ISSUE THREAD

**Issue by xinpenghan** [coolsnowwolf/lede#2607]
请教各位大神，问个小白的问题，咱们升级内核具体作用是什么呢？是提高性能和稳定性吗？现在我默认编译的是固件是4.19.88，不知道有啥区别，是否需要更新固件重新编译？

**Comment by Aes64X** [comment]
帅啊~~~

**Comment by slitilanber** [comment]
就是为了帅，😄😄😄😄。

**Comment by Her0R0cket** [comment]
升级强迫症和楼上回答

**Comment by coolsnowwolf** [comment]
有些上游的补丁，例如解决无线延迟问题，稳定性问题，安全性修复，或者新版驱动需要新版本的内核

内核是最底层的支持。你说升级来干嘛呢
