### ISSUE TITLE
Linksys EA8500 最新编译4.19内核的固件没有2.4G无线

### ISSUE THREAD

**Issue by xraylf** [coolsnowwolf/lede#2608]
Linksys EA8500 最新编译用4.19内核的固件没有2.4GHz无线，只有5ＧHz无线，请问用同样设备的大神有遇到过吗？

**Comment by ferre-han** [comment]
r7800直接Wi-Fi无法启动😂

**Comment by wfb2222wfb** [comment]
同R7800刷完，没有WIFI，有大神解决一下吗

**Comment by AmadeusGhost** [comment]
我提交revert了，#2593 中的ipq806x部分你们试试。

**Comment by xraylf** [comment]
> 我提交revert了，#2593 中的ipq806x部分你们试试。

谢谢了，已经退回旧版本，等大雕修复。

**Comment by ferre-han** [comment]
ipq806x官方的4.19内核非常完美
