### ISSUE TITLE
aliddns 解析到ssr服务器了

### ISSUE THREAD

**Issue by slitilanber** [coolsnowwolf/lede#2610]
今天git clone的源码，全新编译。三种模式下，ddns 都解析到ssr 服务器了。有解决办法么？

**Comment by hxlls** [comment]
证明你的DDNS 服务器地址是在GFW内

**Comment by slitilanber** [comment]
抱歉，没描述清楚。

DDNS: 阿里云买的域名+云解析。

问题: 
内网ping ddns, 返回的是路由器的公网IP,
外网ping ddns, 返回的BWG上的vps IP. 

以前的版本（1-123）只有全局才会解析到BWG上的vps, gfw和绕过都能正确解析。

**Comment by sososoyoung** [comment]
看 ddns log, 是否能正确获取 到路由公网 ip

**Comment by coolsnowwolf** [comment]
ip 来源选接口

**Comment by slitilanber** [comment]
@coolsnowwolf 多谢，IP来源选借口就好了

**Comment by socekin** [comment]
> @coolsnowwolf 多谢，IP来源选接口就好了

IP来源在哪里设置？我用的DNSPOD的解析服务，有同样的设置吗？
