### ISSUE TITLE
路由器拨号问题

### ISSUE THREAD

**Issue by Misaka00073** [coolsnowwolf/lede#2615]
最近发现好像每隔三天左右会自己重新拨号一次，之前用asus的68u是用的koolshare版，好像没有出现过自动重拨的问题，网络是电信的。
这是自带的自动重拨，还是设置的问题，如果是有自动重拨号能不能设置关闭，版本是11月3日自行编译的版本，编译配置只有一些梯子和网易云等插件，其他非插件配置项都没有动过，直接默认编译

**Comment by coolsnowwolf** [comment]
上游强制重拨的
