### ISSUE TITLE
LEDE如何作为NTP服务器使用？

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#2620]
选项上已经打勾了，但是局域网里面的机器设置路由的ip地址作为ntp服务器对时提示失败。
![QQ图片20191229122004](https://user-images.githubusercontent.com/30990861/71552322-caaa1980-2a35-11ea-9146-d35c972122bc.png)
![QQ图片20191229122024](https://user-images.githubusercontent.com/30990861/71552323-caaa1980-2a35-11ea-9319-410cd505fe60.png)

**Comment by Aes64X** [comment]
检查你的电脑系统，我测试正常。况且你的提示是：客户端无法发出请求。而不是服务端拒绝或找不到服务端。
