### ISSUE TITLE
动态DNS问题

### ISSUE THREAD

**Issue by 61555012** [coolsnowwolf/lede#2622]
大佬你好，最近的源码MT7621系列编译出来动态DNS里没有aliyun和dnspod。同样的源码编译出来的ARMv8系列没问题，希望修复

**Comment by lphgor** [comment]
这是前几天为了给小内存设备腾空间，精简掉的。有需要的话可以自己添加回去。

如果是云编译的，在配置文件里面加上这2行：
```
CONFIG_PACKAGE_ddns-scripts_aliyun=y
CONFIG_PACKAGE_ddns-scripts_dnspod=y
```

如果是自己编译的，`make menuconfig`以后，进入`Network` -> `IP Addresses and Name`，选中`ddns-scripts_aliyun`和`ddns-scripts_dnspod`即可。
