### ISSUE TITLE
最新	OpenWrt 17.01.4 R7.5.3 By Lean  双分区启动切换不能用了

### ISSUE THREAD

**Issue by sirfromprc** [coolsnowwolf/lede#263]
我的EA8500，编译最新	OpenWrt 17.01.4 R7.5.3 By Lean  双分区启动切换不能用了。2个分区都是备选状态。选择另一个系统只会重启。fw_printenv boot_part 显示分区命令也不能用，提示Cannot parse config file: No such file or directory

还有也不能刷写其他版本了，只能30大法回到旧版本

**Comment by chd1998** [comment]
我已经回滚到commit adf2b22了

**Comment by sirfromprc** [comment]
/etc/fw_env.config 文件没有，手工创建w_env.config并写入入/dev/mtd10 0x0 0x20000 0x20000  可以了

**Comment by coolsnowwolf** [comment]
修复了~

**Comment by sirfromprc** [comment]
@coolsnowwolf  又编译了下，还是以前的样子。后把package/boot/uboot-envtools/files/ipq 34行`linksys,ea8500)`改为`ea8500)`编译了下，这次一切正常，没有问题了，大屌再修复下
