### ISSUE TITLE
编译过不了，麻烦大家给看一看什么原因，是因为外网不畅，还是因为机器环境

### ISSUE THREAD

**Issue by s3pc** [coolsnowwolf/lede#2634]
我在实体机器上装了ubuntu18 X64 ,用了X86软路由安装koolshare固件，v2ray的梯子，编译过程最后出现了一下提示，这大概是哪里出现了问题？

Connecting to sources.openwrt.org (sources.openwrt.org)|148.251.151.136|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-29 15:38:18 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Makefile:202: recipe for target '/home/j1900/lede/dl/qt-everywhere-opensource-src-5.9.8.tar.xz' failed
make[3]: *** [/home/j1900/lede/dl/qt-everywhere-opensource-src-5.9.8.tar.xz] Error 2
make[3]: Leaving directory '/home/j1900/lede/package/lean/qt5'
time: package/lean/qt5/compile#0.15#0.03#20.46
package/Makefile:107: recipe for target 'package/lean/qt5/compile' failed
make[2]: *** [package/lean/qt5/compile] Error 2
make[2]: Leaving directory '/home/j1900/lede'
package/Makefile:103: recipe for target '/home/j1900/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/j1900/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/j1900/lede'
/home/j1900/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
j1900@j1900-ST80G:~/lede$

**Comment by EnnawYang** [comment]
这个包挂代理下不下来的 自行复制链接用浏览器下载然后放入dl目录即可

**Comment by s3pc** [comment]
Thanks
