### ISSUE TITLE
能否在package中加入luci-app-openclash, 哪位能解释一下clash的机制！

### ISSUE THREAD

**Issue by aesirteam** [coolsnowwolf/lede#2638]
当前是手工在package/lean目录下拉取了luci-app-openclash代码，再编译固件，一切都OK！
另外使用smartdns作为自定义域名解析！
通过clash与ssr+使用对比（纯粹个人主观感受，不对勿喷）：
a. clash进油管直接能上3w并能稳定向上,而ssr+要慢慢升中间有分辨率切换;
b.clash油管视频切换基本秒开，而ssr+会loading

clash基于策略组和规则是什么实现机制，谁能解释一下？谢谢

**Comment by greennyreborn** [comment]
这个 openclash 是不是不能设置局域网ip的规则

**Comment by aesirteam** [comment]
我现在通过smartdns做个办公网OA域名组与外网的自动分流，现在两面的都快！
内网域名指定group为office, 再加规则nameserver   abc.xyz/office就实现分流了

将openclash的自定义dns指向smartdns
openclash会在dnsmasq添加dns转发
当前域名解析 client 53 --> dnsmasq --> 127.0.0.1#7874 clash --> 127.0.0.1:6053 smartdns

感觉openclash自带的dns就够了，主要想用smartdns做OA域名分流
