### ISSUE TITLE
1月12日的更新后，E4200v2 / EA4500升级包升级失败

### ISSUE THREAD

**Issue by zuni11** [coolsnowwolf/lede#264]
按照往常编译后，选择保留设置升级，一切按照往常的操作，但是路由器不会自己重启动，过一会儿wan就断了，lan IP可以ping通，lan ssh 密码错，web没有显示，最后只能断电重新启动，这时系统回到未升级的状态，配置保留。

**Comment by coolsnowwolf** [comment]
修复了

**Comment by zuni11** [comment]
感谢大雕回复，但是刚更新了1.15日的，照旧不行哦，我准备清空设置试试。

**Comment by zuni11** [comment]
报告 还是不行哦。。。。和一楼故障一样
