### ISSUE TITLE
cannot run v2ray 

### ISSUE THREAD

**Issue by caoli5288** [coolsnowwolf/lede#2646]
cpu: mtk7621a
model: ghl-r-001

```
# ./v2ray
Illegal instruction
```

any ideas?

**Comment by gorquan** [comment]
编译的时候开启FPU就可以了
` 
  │ Symbol: KERNEL_MIPS_FPU_EMULATOR [=y]                                                                                                                                                                       
  │ Type  : boolean                                                                                                                                                                                             
  │ Prompt: Compile the kernel with MIPS FPU Emulator                                                                                                                                                           
  │   Location:                                                                                                                                                                                                 
  │     -> Global build settings                                                                                                                                                                                
  │ (1)   -> Kernel build options 
`
