### ISSUE TITLE
整个openwrt项目的开发者操作指南和wiki

### ISSUE THREAD

**Issue by ch1993128** [coolsnowwolf/lede#2650]
https://openwrt.org/docs/guide-developer/start

**Comment by ch1993128** [comment]
对英文不敏感可以用谷歌chorme整个网页翻译

**Comment by onepow** [comment]
nice,  support well

**Comment by me2in** [comment]
https://openwrt.org/start?id=zh/docs/guide-developer/start  
本身就有中文的

**Comment by ForgotFun** [comment]
<跟着佐大学OpenWrt开发>培训班，LEAN力荐官方教程。
http://forgotfun.org/2018/04/openwrt-training-2018.html

**Comment by stock169** [comment]
官方openwrt编译又不困难，关键是遇到问题怎么解决，还有各种新的矿难机怎么适配这个就有些难度了

**Comment by xinpenghan** [comment]
这个不可以用吗？自己完善一下，https://github.com/openwrt/openwrt

**Comment by Ai1954** [comment]
大佬建议增添一个Adguard Home。

**Comment by jonsonjordan** [comment]
这个项目编译门槛不高，有点儿linux操作基础就能上手，而且我现实中是桌面运维+网管，开发确实一窍不通，等我学好了shell再仔细研究吧

**Comment by ch1993128** [comment]
哪里是编译指南哦，哎，麻烦仔细看下。
