### ISSUE TITLE
ipq806x下的luci-app-samba 无法取消

### ISSUE THREAD

**Issue by qinwei0077** [coolsnowwolf/lede#2664]
我的r7800下的luci-app-samba 就和防火墙无法取消一样，导致增加luci-app-samba时错误

**Comment by EnnawYang** [comment]
你怎么不说把autosamba去掉

**Comment by dolphinpaopao** [comment]
提交issue前请善用搜索并提供详细log，不要随意提交，谢谢。

**Comment by hgh188** [comment]
一直正常编译~~自己找原因

**Comment by stock169** [comment]
samba4和samba3和cifsd请3选一

**Comment by hgh188** [comment]
![捕获](https://user-images.githubusercontent.com/45268614/71655789-930fda00-2d73-11ea-81fb-b6ad3c4a135f.PNG)

**Comment by qinwei0077** [comment]
r7800 下 luci-app-samba无法取消

**Comment by EnnawYang** [comment]
> r7800 下 luci-app-samba无法取消

Extra packages  ---> <*> autosamba 先去掉

**Comment by ferre-han** [comment]
我也是R7800编译没什么问题 ,你是装samba4出问题的吧,如果是就取消3啊

**Comment by ferre-han** [comment]
有需要我的固件发给你
