### ISSUE TITLE
在PVE虚拟机中的X64 EFI 的OP 会出现线程识别异常

### ISSUE THREAD

**Issue by shinyzgj** [coolsnowwolf/lede#2668]
在PVE虚拟机中的X64 EFI 的OP 会出现线程识别异常
同样的虚拟机配置下，使用大雕源码傻瓜编译的。具体表现为，线程数比实际划拨给虚拟子机的均会翻倍。
例如我分给虚拟机是双核单线程 实际2个线程。在OP中显示为2核双线程 总计为4线程。
我的固件编译时间为1月1日
PVE版本是6.1

**Comment by Aes64X** [comment]
这不是一个问题，处理器如果支持超线程是会这样显示，处理器请尝试HOST模式。

**Comment by shinyzgj** [comment]
确实支持超线程，但是我划分给这个子机实际是1核2线程。
到了OP里就显示成了2核4线程。不知道是否有其他深度影响

**Comment by inlolo** [comment]
你可以试试cpu直通，cpu指向host

**Comment by bingo235** [comment]
支持超线程的CPU会这样显示。cpu类型选host，不要选kvm64，可以正常识别
