### ISSUE TITLE
求指教 如何让所有域名(不区分国外国内) 都走代理解析

### ISSUE THREAD

**Issue by fewpiwork** [coolsnowwolf/lede#2670]
求指教 如何让所有域名(不区分国外国内) 都走代理解析

运行在全局模式下的ssr plus+ 透明代理 自建v2ray

![image](https://user-images.githubusercontent.com/32926982/71674653-bd36bb80-2db6-11ea-9db0-82ced7726efb.png)

**Comment by fewpiwork** [comment]
目的是消除dns不符合
![image](https://user-images.githubusercontent.com/32926982/71674699-e8b9a600-2db6-11ea-85c7-cd21bb76dacd.png)

**Comment by OROKIN** [comment]
这种问题也来开 issue ，服了

**Comment by inlolo** [comment]
这种测试没有意义，你自己google和baidu里面搜索一下ip，看看已经翻墙

**Comment by hyird** [comment]
全局的dns 应该都是走隧道了，这种测试并无太大意义

**Comment by dolphinpaopao** [comment]
issue不是用来处理这种问题的，请善用搜索和论坛等渠道，不要随意开issue，感谢。提交issue同时请附带详细log。

**Comment by peterwjp2017** [comment]
走全局试试
