### ISSUE TITLE
DDNS 显示已注册的 IP 地址bug

### ISSUE THREAD

**Issue by inlolo** [coolsnowwolf/lede#2674]
测试了一下google的ddns，发现已注册的 IP 地址是已经过时的ip
<img width="1332" alt="1" src="https://user-images.githubusercontent.com/9018340/71706246-acba2b80-2e1e-11ea-9851-369f7032e40e.png">
后台日志显示已经更新了ip
<img width="1179" alt="2" src="https://user-images.githubusercontent.com/9018340/71706255-bb084780-2e1e-11ea-9138-cdf852dfdf90.png">
到google后台也显示更新了最新ip
<img width="1020" alt="3" src="https://user-images.githubusercontent.com/9018340/71706265-c78ca000-2e1e-11ea-99bb-850f24549117.png">

**Comment by inlolo** [comment]
实际功能使用没问题

**Comment by coolsnowwolf** [comment]
DNS 缓存问题。这里看到是路由器本身的缓存，有时间差

**Comment by inlolo** [comment]
> DNS 缓存问题。这里看到是路由器本身的缓存，有时间差

是本身缓存问题

**Comment by jiuub** [comment]
> DNS 缓存问题。这里看到是路由器本身的缓存，有时间差

我也碰到这问题了，我发现其实是Turbo ACC 网络加速下的DNS加速导致的, 关闭该功能就正常获取IP了。我想问问能否nslookup时，指定DNS服务器，解决这个缓存问题
