### ISSUE TITLE
讨论 ssr-plus和flow-offload重启问题和samba中文乱码问题

### ISSUE THREAD

**Issue by ferre-han** [coolsnowwolf/lede#2676]
ssr-plus、flow-offload设置后不能直接重启，需要到"启动项"里面选择相应模块重启.
samba 中文乱码除了编译内核还有其他方法吗?
大家来分享一下你们的解决办法

**Comment by inlolo** [comment]
ssr-plus默认就是自动启动的

**Comment by pikachullk** [comment]
其实点击一下保存并应用不是重启了？ssr plus好像是的～flowoff不知道～按道理也重启了呀

**Comment by ferre-han** [comment]
可能我的固件不能重启吧,我是在官方里面加入了雕神的源码,换个线路都要去启动项里面手动操作一下,使用trojan还不能使用SmartDNS.真滴愁鸭

**Comment by hahaher123** [comment]
官方固件加大雕ssr plus是这样的，必须用/etc/init.d/shadowsocksr restart来重启才行。至于为啥会这样就搞不懂了。

**Comment by ferre-han** [comment]
> 官方固件加大雕ssr plus是这样的，必须用/etc/init.d/shadowsocksr restart来重启才行。至于为啥会这样就搞不懂了。

这位胸带有经验啊 我Google了有不少人出现这种情况都木有解决办法,我看这个问题在雕神github里讨论很有意义鸭

**Comment by shenzt68** [comment]
这个情况据说把procd锁有关

**Comment by coolsnowwolf** [comment]
权限问题。trunk 版本的luci默认不再具有读写关键目录权限，需要显式声明，所以无法完成提交

**Comment by ferre-han** [comment]
> 权限问题。trunk 版本的luci默认不再具有读写关键目录权限，需要显式声明，所以无法完成提交

感谢雕神的回复,估计很多人会Google到这个issues,一定会有很大帮助.
