### ISSUE TITLE
有办法添加luci-app-wifidog的支持吗？

### ISSUE THREAD

**Issue by xosadmin** [coolsnowwolf/lede#2678]
如题，从github上clone了一个源码，但是尝试了各种方法都没法在Menuconfig中看到...

**Comment by panzhitian** [comment]
文件放好位置后，运行一遍feed install那个命令

**Comment by ch1993128** [comment]
git clone 到package包里面就可以看到了，位置不对吧

**Comment by xosadmin** [comment]
> 文件放好位置后，运行一遍feed install那个命令

运行过了，就是没有出现…

**Comment by SharerMax** [comment]
1. 用的那个版本的代码
2. 做了什么配置
3. 添加的代码是啥
4. 做过哪些尝试
5. 有什么日志

你这啥都没有，别人也没法帮你啊
