### ISSUE TITLE
闭源驱动没有弱信号踢出，没有802.11r，不能搜索其他无线做桥接

### ISSUE THREAD

**Issue by llfj** [coolsnowwolf/lede#2679]
闭源驱动没有弱信号踢出，不能搜索其他无线做桥接
无线驱动 弱信号踢出 还是你之前编译的K2 或K2P的潘多拉的那种 

已连接客户端RSSI下限：
客户端RSSI限制：

这种最好用。。。。

**Comment by Aes64X** [comment]
请不要在issues中提出这种问题。

**Comment by llfj** [comment]
有很多人和我一样不清楚，在这里问一下，你回答了，以后不懂得，一看就清楚了。谢谢解答。

**Comment by ch1993128** [comment]
闭源是一种很坑的东西，歪曲了的封装亦如此。可能不是不做吧，闭源上游没有提供接口？

**Comment by coolsnowwolf** [comment]
低调。。。
