### ISSUE TITLE
请教关于编译环境的问题（Ubuntu 17.10 / macOS 10.13.2）

### ISSUE THREAD

**Issue by allenfoxtc** [coolsnowwolf/lede#268]
请问是不是目前版本不支持Ubuntu 17.10或macOS 10.13.2(homebrew)下的编译呢？

我在Ubuntu 17.10下编译lede或openwrt，都会卡在libubox的blobmsg_json.c处提示找不到json/json.h（也可能是JSONC未定义导致没去找json.h），需要手工改成json-c/json.h，编译到后边又提示miniupnpd找不到libiptc.so.0依赖

在macOS下倒是能编译过上面两个，但后面会卡在scoket.h重新定义这个警告（导致struct sockaddr和struct sockaddr_in缺少xxx_len的属性）然后编译不通过

不过在Ubuntu 16.04下面编译是没问题的

**Comment by coolsnowwolf** [comment]
我在 17.10 也失败了

**Comment by chd1998** [comment]
我的17.10正常

**Comment by chd1998** [comment]
不过编译后，55R选了，没有出现，准备手动装
