### ISSUE TITLE
动态dns插件不能自动更新

### ISSUE THREAD

**Issue by yl1725** [coolsnowwolf/lede#2682]
pppoe上网，每次换ip的时候，没法成功自动更新，插件提示：不支持使用 TCP 进行 DNS 解析
向 DNS 服务器查询时，BusyBox 的 nslookup 和 hostip 不支持使用 TCP 而不是默认的 UDP！
- 您应该为 DNS 请求安装“bind-host”或“knot-host”或“drill”软件包。
日志如下，有些信息进行了隐藏
 221839       : verbose mode  : 0 - run normal, NO console output
 221839       : check interval: 600 seconds
 221839       : force interval: 259200 seconds
 221839       : retry interval: 60 seconds
 221839       : retry counter : 0 times
 221839       : No old process
 221839       : last update: never
 221839       : Detect registered/public IP
 221839       : #> /usr/bin/nslookup *****.top  >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 221839  WARN : NO valid IP found
 221839  info : Starting main loop at 2020-01-04 22:18
 221839       : Detect local IP on 'network'
 221839       : Local IP '112.248.62.209' detected on network 'wan'
 221839       : Update needed - L: '112.248.62.209' <> R: ''
 221839       : parsing script '/usr/lib/ddns/update_aliyun_com.sh'
 221839       : #> /usr/bin/wget-ssl -nv -t 1 -O /var/run/ddns/ipv4.dat -o /var/run/ddns/ipv4.err --no-proxy 'http://alidns.aliyuncs.com/?Action=DescribeSubDomainRecords&SubDomain=******.top&Format=JSON&Version=2015-01-09&AccessKeyId=******&SignatureMethod=HMAC-SHA1&Timestamp=2020-01-04T14%3A18%3A39Z&SignatureVersion=1.0&SignatureNonce=b5b7a170-ca4c-49ae-a055-e1988d96dd47&Signature=n1n8M7LO6owTyoIW0A1yS%2BoGUQQ%3D'
 221840       : 获取到解析记录: {"PageNumber":1,"TotalCount":0,"PageSize":20,"RequestId":"584B76C3-CF1A-4EF3-9DCC-1C7949C7CF4A","DomainRecords":{"Record":[]}}
 221840       : 解析记录不存在
 221843       : #> /usr/bin/wget-ssl -nv -t 1 -O /var/run/ddns/ipv4.dat -o /var/run/ddns/ipv4.err --no-proxy 'http://alidns.aliyuncs.com/?Action=AddDomainRecord&DomainName=top&RR=******&Type=A&Value=112.248.62.209&Format=JSON&Version=2015-01-09&AccessKeyId=******&SignatureMethod=HMAC-SHA1&Timestamp=2020-01-04T14%3A18%3A43Z&SignatureVersion=1.0&SignatureNonce=a16ebb5e-efd2-40ee-a276-c5237adb6126&Signature=cAMJz9FoaGqT%2FV1kubtMEgcXuaQ%3D'
 221843 ERROR : wget 错误代码: '8'
 221844       : http://alidns.aliyuncs.com/?Action=AddDomainRecord&DomainName=top&RR=&******Type=A&Value=112.248.62.209&Format=JSON&Version=2015-01-09&AccessKeyId=******&SignatureMethod=HMAC-SHA1&Timestamp=2020-01-04T14%3A18%3A43Z&SignatureVersion=1.0&SignatureNonce=a16ebb5e-efd2-40ee-a276-c5237adb6126&Signature=cAMJz9FoaGqT%2FV1kubtMEgcXuaQ%3D:
2020-01-04 22:18:43 ERROR 400: Bad Request.
 221844  WARN : 传输失败 - 1/0 在 60 秒后重试
小白水平，上网搜了一下，发现相关帖子很少，有人遇到过类似问题，但是没有解决方案。。求大神指点

**Comment by nevertoday** [comment]
您应该为 DNS 请求安装“bind-host”或“knot-host”或“drill”软件包
 
 
 我也是这种，， 导致ddns 有时候解析完全不是正确的ipv4

**Comment by Fyred** [comment]
请问后来如何解决的啊？
