### ISSUE TITLE
Wan->Lan speed with Turbo ACC 

### ISSUE THREAD

**Issue by tsg2k2** [coolsnowwolf/lede#2694]
I have 1gpbs connection which I could utilize fully with my other router (~900+mbps real traffic).
Max speed I get with Phicomm K3 and this build is ~550mbps with flow offloading enabled. I'm getting the same numbers with official openwrt 19.07rc2 build.  Any way to fix this issue? Thanks.

**Comment by jamesho0** [comment]
maybe you need to use X86 devices

**Comment by tsg2k2** [comment]
Why is it closed without comments? I have R6300V2 (weaker Broadcom hardware) with FreshTomato and it gives me full wire speed with CTF enabled.
