### ISSUE TITLE
commit 311编译错

### ISSUE THREAD

**Issue by vincentchen** [coolsnowwolf/lede#270]
make[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/form'
gcc -I../ncurses -DHAVE_CONFIG_H -I. -I../include -I/root/lede/staging_dir/host/include -I/root/lede/staging_dir/host/usr/include -I/root/lede/staging_dir/hostpkg/include -I/root/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/include -D_GNU_SOURCE -DNDEBUG -O2 -I/root/lede/staging_dir/host/include -I/root/lede/staging_dir/host/usr/include -I/root/lede/staging_dir/hostpkg/include -I/root/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/include  --param max-inline-insns-single=1200 -c ../form/frm_scale.c -o ../objects/frm_scale.o
../form/frm_scale.c: In function 'scale_form':
../form/frm_scale.c:56:12: error: 'E_BAD_ARGUMENT' undeclared (first use in this function)
     RETURN(E_BAD_ARGUMENT);                                                                   ^
../form/frm_scale.c:56:12: note: each undeclared identifier is reported only once for each function it appears in
../form/frm_scale.c:59:12: error: 'E_NOT_CONNECTED' undeclared (first use in this function)
     RETURN(E_NOT_CONNECTED);
            ^                                                                      ../form/frm_scale.c:66:10: error: 'E_OK' undeclared (first use in this function)
   RETURN(E_OK);
          ^
make[5]: *** [../objects/frm_scale.o] Error 1                                      make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/form'         make[4]: *** [libs] Error 2
make[4]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0'
make[3]: *** [/root/lede/build_dir/hostpkg/ncurses-6.0/.built] Error 2             make[3]: Leaving directory `/root/lede/package/libs/ncurses'
make[2]: *** [package/libs/ncurses/host/compile] Error 2
make[2]: Leaving directory `/root/lede'
make[1]: *** [/root/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/root/lede'
make[1]: Leaving directory `/root/lede'                                            Build failed - please re-run with -j1 to see the real error message
make: *** [world] Error 1
root@ubuntu:~/lede# ls
17.config      Config.in           key-build      README       toolchain
acrh17.config  dl                  key-build.pub  rules.mk     tools
bin            feeds               LICENSE        scripts      update.sh
BSDmakefile    feeds.conf.default  Makefile       staging_dir  vincent.sh
build_dir      include             nohup.out      target       x64.config
config         k3.config           package        tmp
root@ubuntu:~/lede# cp x64.config .config
root@ubuntu:~/lede# rm nohup.out
root@ubuntu:~/lede# nohup make -j2 V=s&
[1] 6852
root@ubuntu:~/lede# nohup: ignoring input and appending output to ‘nohup.out’

root@ubuntu:~/lede# tail -f nohup.out
touch /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76/.configuredrm -f /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76/vmlinux /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76/System.map
make -C /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76 HOSTCFLAGS="-O2 -I/root/lede/staging_dir/host/include -I/root/lede/staging_dir/host/usr/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="x86_64-openwrt-linux-musl-" ARCH="x86" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sun Jan 14 23:53:04 2018" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/root/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=4.9.76 CC="x86_64-openwrt-linux-musl-gcc" modules
make[5]: Entering directory `/root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  Building modules, stage 2.
  MODPOST 183 modules
make[5]: Leaving directory `/root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76'
touch /root/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.9.76/.modules
make -C image compile TARGET_BUILD=
make[5]: Entering directory `/root/lede/target/linux/x86/image'
make[5]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[5]: Nothing to be done for `compile'.
make[5]: Leaving directory `/root/lede/target/linux/x86/image'
make[4]: Leaving directory `/root/lede/target/linux/x86'
make[3]: Leaving directory `/root/lede/target/linux'
make[2]: Leaving directory `/root/lede'
export MAKEFLAGS= ;make -w -r diffconfig
make[2]: Entering directory `/root/lede'
make[2]: Entering directory `/root/lede'
make[3]: Entering directory `/root/lede/package/libs/toolchain'
mkdir -p /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /root/lede/tmp/.root-copy.flock -c 'cp -fpR /root/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/. /root/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.libc_installed
echo "libc" >> /root/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
mkdir -p /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /root/lede/tmp/.root-copy.flock -c 'cp -fpR /root/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libgcc/. /root/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.libgcc_installed
echo "libgcc" >> /root/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
mkdir -p /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /root/lede/tmp/.root-copy.flock -c 'cp -fpR /root/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libstdcpp/. /root/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.libstdcpp_installedecho "libstdcpp" >> /root/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
mkdir -p /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /root/lede/tmp/.root-copy.flock -c 'cp -fpR /root/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/libpthread/. /root/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.libpthread_installed
echo "libpthread" >> /root/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
mkdir -p /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /root/lede/tmp/.root-copy.flock -c 'cp -fpR /root/lede/build_dir/target-x86_64_musl/toolchain/.pkgdir/librt/. /root/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /root/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.librt_installed
echo "librt" >> /root/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
make[3]: Leaving directory `/root/lede/package/libs/toolchain'
make[3]: Entering directory `/root/lede/package/libs/ncurses'
make -C /root/lede/build_dir/hostpkg/ncurses-6.0 libs
make[4]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0'
cd include && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libs
make[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/include'
make[5]: Nothing to be done for `libs'.
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/include'
cd ncurses && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libs
make[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/ncurses'
make[5]: Nothing to be done for `libs'.
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/ncurses'
cd progs && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libsmake[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/progs'
make[5]: Nothing to be done for `libs'.
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/progs'
cd panel && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libsmake[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/panel'
make[5]: Nothing to be done for `libs'.
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/panel'
cd menu && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libs
make[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/menu'
make[5]: Nothing to be done for `libs'.
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/menu'
cd form && make -w DESTDIR="" RPATH_LIST="/root/lede/staging_dir/hostpkg/lib" libs
make[5]: Entering directory `/root/lede/build_dir/hostpkg/ncurses-6.0/form'
gcc -I../ncurses -DHAVE_CONFIG_H -I. -I../include -I/root/lede/staging_dir/host/include -I/root/lede/staging_dir/host/usr/include -I/root/lede/staging_dir/hostpkg/include -I/root/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/include -D_GNU_SOURCE -DNDEBUG -O2 -I/root/lede/staging_dir/host/include -I/root/lede/staging_dir/host/usr/include -I/root/lede/staging_dir/hostpkg/include -I/root/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/include  --param max-inline-insns-single=1200 -c ../form/frm_scale.c -o ../objects/frm_scale.o
tmp/.config-package.in:58109:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:58109:   symbol PACKAGE_iptables is selected by PACKAGE_shadowsocksr-libev-alt
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:90069:   symbol PACKAGE_shadowsocksr-libev-alt is selected by PACKAGE_luci-app-shadowsocksr-pro
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:38487:   symbol PACKAGE_luci-app-shadowsocksr-pro depends on PACKAGE_iptables
../form/frm_scale.c: In function 'scale_form':
../form/frm_scale.c:56:12: error: 'E_BAD_ARGUMENT' undeclared (first use in this function)
     RETURN(E_BAD_ARGUMENT);
            ^
../form/frm_scale.c:56:12: note: each undeclared identifier is reported only once for each function it appears in
../form/frm_scale.c:59:12: error: 'E_NOT_CONNECTED' undeclared (first use in this function)
     RETURN(E_NOT_CONNECTED);
            ^
../form/frm_scale.c:66:10: error: 'E_OK' undeclared (first use in this function)
   RETURN(E_OK);
          ^
make[5]: *** [../objects/frm_scale.o] Error 1
make[5]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0/form'
make[4]: *** [libs] Error 2
make[4]: Leaving directory `/root/lede/build_dir/hostpkg/ncurses-6.0'
make[3]: *** [/root/lede/build_dir/hostpkg/ncurses-6.0/.built] Error 2
make[3]: Leaving directory `/root/lede/package/libs/ncurses'
make[2]: *** [package/libs/ncurses/host/compile] Error 2
make[2]: Leaving directory `/root/lede'
make[1]: *** [/root/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
tmp/.config-package.in:58109:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:58109:   symbol PACKAGE_iptables is selected by PACKAGE_shadowsocksr-libev-alt
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:90069:   symbol PACKAGE_shadowsocksr-libev-alt is selected by PACKAGE_luci-app-shadowsocksr-pro
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:38487:   symbol PACKAGE_luci-app-shadowsocksr-pro depends on PACKAGE_iptables
make[2]: Leaving directory `/root/lede'
make[1]: Leaving directory `/root/lede'
Build failed - please re-run with -j1 to see the real error message
make: *** [world] Error 1

**Comment by coolsnowwolf** [comment]
make clean
