### ISSUE TITLE
编译K2T内核4.19.91的时候报错implicit declaration of function 'kmemleak_free'

### ISSUE THREAD

**Issue by maskedeken** [coolsnowwolf/lede#2702]
原因是arch/mips/kernel/module.c这个文件引用的slab.h已经去掉了#include <kmemleak.h>的代码

**Comment by Aes64X** [comment]
K2T这个玩意。。。。没改内存还是建议老的AR71XX+4.9内核吧。。。ath79+4.19爆到怀疑机生

**Comment by maskedeken** [comment]
> 
> 
> K2T这个玩意。。。。没改内存还是建议老的AR71XX+4.9内核吧。。。ath79+4.19爆到怀疑机生

那不会，我刷了OpenWrt 19.07，很流畅

**Comment by AmadeusGhost** [comment]
已修复

**Comment by Aes64X** [comment]
> 已修复

thk
