### ISSUE TITLE
路由宝reboot重启死机，拔电源没事。

### ISSUE THREAD

**Issue by ghostry** [coolsnowwolf/lede#272]
如题。
设备信息
CPU	MediaTek MT7620A ver 2, eco 6
内存	128MB DDR2
Flash	Macronix MX25L25635E @ 24MHz (32MB)
以太网	MediaTek MT7620A built-in 5-port 10/100M switch
时钟频率	CPU: 580MHz, Bus: 193MHz
编译日期	2018-01-07 [git-cc5b8b8]
版本	1.1 (r1169)

另外ttl怎么输出的都是\x0f8\x06这种东西。没有可读字符啊。

**Comment by ghostry** [comment]
extroot到sd卡后，遇到很多Illegal instruction和Segmentation fault错误。

**Comment by HiGarfield** [comment]
32M闪存LEDE软重启有bug。LEDE官方的锅，应该向LEDE官方提交。

**Comment by uglee** [comment]
32m闪存不能软复位，这个锅可以去网上搜patch即可
