### ISSUE TITLE
aMule 自动退出

### ISSUE THREAD

**Issue by lbbboy** [coolsnowwolf/lede#2720]
启动两秒进程就自杀了！然后又在自启。其他人能正常使用吗？

OpenWrt SNAPSHOT, r0-a2bef4b

**Comment by Her0R0cket** [comment]
把upnp禁用了

**Comment by Her0R0cket** [comment]
amule内的upnp

**Comment by coolsnowwolf** [comment]
已修复，测试后回复

**Comment by Her0R0cket** [comment]
刚更新编译试了,还是不行

还是和以前一样,到这里就结束了
![图片](https://user-images.githubusercontent.com/33145975/72218328-f9b3a580-3574-11ea-9717-4096fa030265.png)
日志到这里  Created Client UDP-Socket at port 34242
但是不会循环重启了

正常的运行的话应该是
![图片](https://user-images.githubusercontent.com/33145975/72218343-16e87400-3575-11ea-900f-5a4db2fdbf83.png)
日志是 amuled: forking to background - see you
