### ISSUE TITLE
DDNS怎么不支持阿里云了？

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#2722]
DDNS怎么不支持阿里云了？

找不到aliyun.com的提供商了

**Comment by kwamenf** [comment]
Network->IP Addresses and Names ->ddns-scripts_aliyun/ddns-scripts_dnspod

**Comment by jy3344511** [comment]
> Network->IP Addresses and Names ->ddns-scripts_aliyun/ddns-scripts_dnspod

在编译的过程中，这两项ddns-scripts_aliyun、ddns-scripts_dnspod，是否都要打*号，进行编译？？？？

**Comment by qiaowenbin** [comment]
合并了 默认是支持的 直接添加DDNS就可以
用户名填AccessKey ID   密码填Access Key Secret
