### ISSUE TITLE
通过自动PR保持最新状态

### ISSUE THREAD

**Issue by Mattraks** [coolsnowwolf/lede#2723]
通过自动PR保持最新状态
https://github.com/apps/pull
安装完毕选择需要同步的仓库或者同步全部仓库
https://github.com/settings/installations/6094997

**Comment by coolsnowwolf** [comment]
各位不要再将自己的垃圾 action 推送给我了，关不过来了，请根据这个操作自动合并更新

**Comment by hcym** [comment]
也是不会，好好学习方法

**Comment by dolphinpaopao** [comment]
何其繁多的垃圾issue和PR就会发现，伸手党永不言败。

**Comment by ZForest000** [comment]
使用自动PR会导致修改的openwrt-ci.yml和merge-upstream.yml被还原，请问有什么方法可以避免吗？

**Comment by letmekillthemall** [comment]
使用之前切记**备份**，如果自己的fork有个人改动，还是别用了，这东西会把你的改动**全部清除掉**，整个仓库就变成了镜像仓库

**Comment by sky123456789sky** [comment]
建议大家直接在码云建立仓库 然后合并只用点一下 改掉feeds.conf.default 速度飞起啊
