### ISSUE TITLE
请问可以添加NVME的驱动吗？

### ISSUE THREAD

**Issue by michael6555** [coolsnowwolf/lede#2728]

**Comment by sqliuchang** [comment]
有人刷op还用nvme硬盘的吗…是真土豪啊

**Comment by michael6555** [comment]
用16g的傲腾，三十块算土豪吗？

发自我的iPhone

**Comment by sqliuchang** [comment]
> 用16g的傲腾，三十块算土豪吗？ 发自我的iPhone

可以，很机智，原来傲腾还可以这么用！
但是看起来默认是选中了nvme驱动的啊
https://github.com/coolsnowwolf/lede/blob/4730b1260e3f3f72ca7771e0744c1ef50e4d1bb7/target/linux/x86/config-4.19#L84

**Comment by michael6555** [comment]
> > 用16g的傲腾，三十块算土豪吗？ 发自我的iPhone
> 
> 可以，很机智，原来傲腾还可以这么用！
> 但是看起来默认是选中了nvme驱动的啊
> https://github.com/coolsnowwolf/lede/blob/4730b1260e3f3f72ca7771e0744c1ef50e4d1bb7/target/linux/x86/config-4.19#L84

默认有开的话，开机找不到系统

**Comment by jackiezhang29** [comment]
> 有人刷op还用nvme硬盘的吗…是真土豪啊

我貌似就是950 pro

**Comment by michael6555** [comment]
> > 有人刷op还用nvme硬盘的吗…是真土豪啊
> 
> 我貌似就是950 pro

你的用950pro能开机吗？

**Comment by jackiezhang29** [comment]
> > > 有人刷op还用nvme硬盘的吗…是真土豪啊
> > 
> > 
> > 我貌似就是950 pro
> 
> 你的用950pro能开机吗？

我是win2019+hyperv

**Comment by coolsnowwolf** [comment]
EFI 的 IMG 才能支持 NVME

**Comment by michael6555** [comment]
> EFI 的 IMG 才能支持 NVME

怎样才能编译成EFI的？

**Comment by MxCen** [comment]
Target Images  --->Build EFI GRUB images (Linux x86 or x86_64 host only)

**Comment by michael6555** [comment]
> Target Images --->Build EFI GRUB images (Linux x86 or x86_64 host only)
编译x86_64版本CONFIG_EFI_IMAGES=y是默认的，能说简单明了一点吗?

**Comment by MxCen** [comment]
make menuconfig 里面选起Target Images --->Build EFI GRUB images (Linux x86 or x86_64 host only)，编译出来的固件包efi的就是。
