### ISSUE TITLE
请问下  安装官方源 提示内核过低  怎么解决了

### ISSUE THREAD

**Issue by graytoowolf** [coolsnowwolf/lede#2743]

**Comment by AmadeusGhost** [comment]
鬼知道，建议先去学下怎么提问。

**Comment by KFERMercer** [comment]
刷一个高内核固件. 顺便建议楼上先去学下怎么说话.

**Comment by graytoowolf** [comment]
> 称

我已经用的L大的最新版了  

内核版本 | 4.14.160
安装官方源 有的软件居然需要 4.14.161 + 
-- | --

**Comment by coolsnowwolf** [comment]
kmod 一定是不兼容的，就算是版本相同

**Comment by graytoowolf** [comment]
> kmod一定是不兼容的，就算是版本相同

好的 谢谢 
把需要的选上  我重新编译了
