### ISSUE TITLE
编译 go 时发生错误

### ISSUE THREAD

**Issue by SuLingGG** [coolsnowwolf/lede#2744]
为树莓派编译32位固件时，在编译 go (Docker 的依赖) 时，发生如附件所示的错误，望修复~
[ErrorLog.txt](https://github.com/coolsnowwolf/lede/files/4048901/ErrorLog.txt)

**Comment by coolsnowwolf** [comment]
你的机器内存不足，无法修复

**Comment by SuLingGG** [comment]
> 你的机器内存不足，无法修复

重启了下机器好了，应该就是内存不够的锅，谢谢 Lean 大~

**Comment by SuLingGG** [comment]
> 请问硬盘没空间?

硬盘有空间的，应该就是内存不足的缘故。
