### ISSUE TITLE
可否支持CloudflareDDNS

### ISSUE THREAD

**Issue by virualv** [coolsnowwolf/lede#2747]
能抽空帮忙看一下能否添加cloudflare的ddns支持吗，目前使用的人还是挺多的
> 由于国内的大环境，一般的dns服务商的个人域名如果未备案都会被阻断。如TX的某pod
> 之前也尝试使用openwrt官方的ddns，但是最终没有搞定（比较菜）
> 所以希望L大可以支持一下cloudflaredns，**谢谢**

可参考
[EngrZhou/CloudFlare-DDNS-Script](https://github.com/EngrZhou/CloudFlare-DDNS-Script)
[openwrt 官方](https://github.com/openwrt/packages/blob/openwrt-18.06/net/ddns-scripts/files/update_cloudflare_com_v4.sh)

*如果大佬实在没有时间就算了，再次感谢L大提供这么好用的固件，谢谢*

**Comment by KevinMX** [comment]
``$ make menuconfig``
进入Network >>  IP Addresses and Names 
勾选``ddns-scripts_cloudflare.com-v4``。
需提前勾选luci-app-ddns。

**Comment by virualv** [comment]
好的谢谢
