### ISSUE TITLE
如何把openwrt固件升级至最新呢？

### ISSUE THREAD

**Issue by hnxxd** [coolsnowwolf/lede#2756]
如题

**Comment by guochan2019** [comment]
这里不发布固件，请自行百度编译教程，然后按教程和首页readme学习使用方法

**Comment by xinpenghan** [comment]
看平台了，x86直接下载就可以，最新固件下载
https://github.com/coolsnowwolf/lede/suites/395765333/artifacts/1070391

**Comment by fgprodigal** [comment]
问一下，新编译出来的镜像怎么更新到软路由里，不会每次编译都重建一次软路由吧
