### ISSUE TITLE
curl 运行错误

### ISSUE THREAD

**Issue by bzzjh** [coolsnowwolf/lede#2759]
版本：R9.12.31
运行命令,报错
root@OpenWrt:~# curl 
**Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_next_proto_select_cb: symbol not found**

我看了这个issues:
https://github.com/coolsnowwolf/lede/issues/739
libmbedtls也已经安装了
root@OpenWrt:~# opkg install libmbedtls
Package libmbedtls (2.16.3-2) installed in root is up to date.

root@OpenWrt:~# opkg install libcurl
Package libcurl (7.66.0-1) installed in root is up to date.

root@OpenWrt:~# opkg install curl
Package curl (7.66.0-1) installed in root is up to date.

**Comment by bzzjh** [comment]
更新源代码，重新编译了，已经解决，谢谢！

**Comment by alphavip** [comment]
我更新源代码重新编译还是这个错误
不知道什么原因

**Comment by alphavip** [comment]
难道要clean一下重新编译吗
