### ISSUE TITLE
L大 能支持3.18内核吗

### ISSUE THREAD

**Issue by Resurrection2981** [coolsnowwolf/lede#2762]
内核3.19取消了对3.18的支持，导致我一部分软件不能用，请问能支持3.18或者说LEDE有方法降级吗?

**Comment by hzjnet** [comment]
就是哈，不过难！

**Comment by AmadeusGhost** [comment]
没看懂你的意思...4.19？
3.18早就被移除了，太旧了，内核和设备都太旧了

**Comment by letmekillthemall** [comment]
3.18内核早就淘汰了，应该是你早点迁移到4内核才对

**Comment by AmadeusGhost** [comment]
> 3.18内核早就淘汰了，应该是你早点迁移到4内核才对

早就是4.x内核了

**Comment by yonggedebaqi** [comment]
发红包给L大，私下帮你适配

**Comment by Resurrection2981** [comment]
> 发红包给L大，私下帮你适应

没有联系方式关键

**Comment by Resurrection2981** [comment]
> 3.18内核早就淘汰了，应该是你早点迁移到4内核才对

校园网用的拨号程序貌似3.18后用不了

**Comment by Resurrection2981** [comment]
> 没看懂你的意思... 4.19？
> 3.18早就被移除了，太旧了，内核和设备都太旧了

校园网的拨号程序在3.18后运行不了…

**Comment by AmadeusGhost** [comment]
那就改写拨号程序，回到3.18是不现实的。

**Comment by ch1993128** [comment]
。。。咋回3.18。。。。。。。奇怪的要求
