### ISSUE TITLE
1.8版本，LEAN源码，端口回流有问题。

### ISSUE THREAD

**Issue by vojaly** [coolsnowwolf/lede#2763]
在内网，用WAN口PPPOE拨号获得IP地址（公网IP）和域名，能访问路由器设置页面，但是不能访问内网NAS，已经给NAS做了端口映射。

在外网，用IP和域名都能正常访问路由器和NAS。

并且已经卸载DOCKER。

**Comment by ydwzjw521** [comment]
同样的问题，同问，有啥解决办法么？

**Comment by wz2869058** [comment]
是docker的问题，如果没有特殊需求，编译一个没有docker的固件即可解决问题

**Comment by WROIATE** [comment]
如果能安着docker解决就好了，那样我连nas都不用了直接一体

**Comment by tanst** [comment]
这个问题新版本解决了吗？还是不了了之？

**Comment by ydwzjw521** [comment]
在主机名里添加了下域名和对应的ip就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tanst <notifications@github.com&gt;
发送时间: 2020年2月24日 22:58
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: ydwzjw521 <5056540@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] 1.8版本，LEAN源码，端口回流有问题。 (#2763)




这个问题新版本解决了吗？还是不了了之？
