### ISSUE TITLE
UnblockNeteaseMusic(Go version)

### ISSUE THREAD

**Issue by Javascript-Ninja** [coolsnowwolf/lede#2764]
More suitable for running on arm and mips devices, faster than nodejs version, doesn't need FPU.
[package](https://github.com/cnsilvan/UnblockNeteaseMusic)
[luci-app](https://github.com/project-openwrt/luci-app-unblockneteasemusic-go)

**Comment by AmadeusGhost** [comment]
But it takes up more volume than before, and did you get the author's authorization?

**Comment by Javascript-Ninja** [comment]
[package license](https://github.com/project-openwrt/luci-app-unblockneteasemusic-go/blob/master/LICENSE)
[luci-app license](https://github.com/cnsilvan/UnblockNeteaseMusic/blob/master/LICENSE)

**Comment by coolsnowwolf** [comment]
我倒是建议用 lua + httpclient 方式兼容 ，效率也更高
