### ISSUE TITLE
Zerotier插件有问题，加入一个网络以后，在Zerotier里面看不到

### ISSUE THREAD

**Issue by Charles-Mao-71** [coolsnowwolf/lede#2766]
可以开启，显示可以加入，但是加入后在Zerotier官网账户里面看不到路由的ip，在软路由的Zerotier界面，有一个接口信息里面是空的。

**Comment by caicaicai21** [comment]
我的Zerotier正常，我建议你还是先看看Zerotier如何使用再说吧。

**Comment by Charles-Mao-71** [comment]
我使用的上一个版本 的软路由，是没有问题的。用了现在用的这个版本，出现这个问题。zerotier在其他的机器上的没有问题。并不是我的使用有问题。而且这个版本的ROM我下载的也是经过发布者的MD5验证的。

**Comment by momonoshiori** [comment]
不是自己编译的去找编译的人吧，对方有没有改什么谁也不知道，你这里也没有提供任何错误日志，这里并不会发布编译好的固件

**Comment by zinbers** [comment]
https://zerotier.atlassian.net/wiki/spaces/SD/overview 或许对你有帮助

**Comment by ZqinKing** [comment]
一直没问题在用，修改后支持moon

**Comment by hn315** [comment]
我也遇到相同问题
