### ISSUE TITLE
Proxychains 会导致Python 2.7编译出现问题 Proxychains Caused IPv6 Error When Compiling Python 2.7

### ISSUE THREAD

**Issue by Ghost-Assassin** [coolsnowwolf/lede#2767]
OS: Ubuntu 16.04 x86_64

![image](https://user-images.githubusercontent.com/25316415/72236109-79428280-3610-11ea-9018-fe28669449b2.png)

暂时不要使用Proxychains，使用其他替代方式来代理curl和git.
Don't Use Proxychain when you having this issue, use alternative methods for curl and git.

# curl
```
export http_proxy=http://localhost:1080
export https_proxy=https://localhost:1080
# or socks5
export http_proxy=socks5h://localhost:1080
export https_proxy=socks5h://localhost:1080
```

# git
```
git config --global http.proxy http://localhost:1080
git config --global https.proxy https://localhost:1080
```

请根据实际情况修改等号右侧地址
Please modify the proxy address to match your case.

**Comment by AmadeusGhost** [comment]
可以先用proxychains make download，下载完再后编译。
