### ISSUE TITLE
AC58U 升级恢复都不行..

### ISSUE THREAD

**Issue by simenty** [coolsnowwolf/lede#277]
AC58U 卡在这个版本升级.恢复都不行..
无论web升级还是sysupgrade强刷,都是提示错误.
![2](https://user-images.githubusercontent.com/34025356/35083602-e78237d2-fc5a-11e7-88b8-d248f43b652f.jpg)
![11](https://user-images.githubusercontent.com/34025356/35083605-e89b7a3e-fc5a-11e7-9dc2-b132de5f66f3.jpg)

**Comment by allenfoxtc** [comment]
我也是这个问题 后来进uboot刷factory包再回复配置就好了

**Comment by simenty** [comment]
怎么进入uboot刷?

**Comment by allenfoxtc** [comment]
@simenty 我不知道你的是啥型号 我的是极路由4 进入uboot方法是断电 上电时候按住reset键 等led是红灯常亮时候 用网线连然后访问192.168.1.1就可以了

**Comment by simenty** [comment]
@allenfoxtc 好忧桑

**Comment by daofeng2015** [comment]
好像是提升没有升级文件，检查下官方的这个文件在哪，去源码makefile找找，可能遗漏了
