### ISSUE TITLE
小马V1直装op-X64出现大量错误日志

### ISSUE THREAD

**Issue by nicepass** [coolsnowwolf/lede#2773]
Tue Jan 14 12:30:27 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
Tue Jan 14 12:30:27 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
Tue Jan 14 12:30:28 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
Tue Jan 14 12:30:28 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
Tue Jan 14 12:30:29 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
Tue Jan 14 12:30:29 2020 daemon.err uhttpd[4353]: Cannot get device settings: No such device
编译的插件如下图：

![1214](https://user-images.githubusercontent.com/50690714/72314587-7dcb7180-36ca-11ea-9926-0e015d1c4fd8.jpg)

**Comment by EnnawYang** [comment]
同机器 没问题

**Comment by nicepass** [comment]
格掉硬盘重新安装还是会报这个错误

**Comment by 0x5826** [comment]
能正常用就没问题
