### ISSUE TITLE
为什么新编译的固件xiaomi mini R3G D2 N1这几个固件都不能保存配置？

### ISSUE THREAD

**Issue by feizaibufei** [coolsnowwolf/lede#2774]
为什么新编译的固件xiaomi mini R3G D2 N1这几个固件都不能保存配置？

**Comment by feizaibufei** [comment]
设置好了，重启路由器配置都没有了

**Comment by git-maven** [comment]
下次发issues之前要搜索有没有类似的问题，同样的问题我前几天就发过
需要刷一次sys那个升级文件

**Comment by yonggedebaqi** [comment]
没看到也

**Comment by caicaicai21** [comment]
你刷的是initramfs-kernel固件？如果你编译之后只生成这个固件，那么是你编译的固件插件太多，导致固件太大。

**Comment by yonggedebaqi** [comment]
谢谢，在研究一下
