### ISSUE TITLE
内网访问外网域名失败

### ISSUE THREAD

**Issue by shshunlan** [coolsnowwolf/lede#2775]
内网主机能ping通域名，域名已绑定到网关。
内网通过域名访问网关（端口已转发，不是80端口），失败。
内网通过域名访问网关端口映射的内网主机，失败。

防火墙做端口转发时，已开通NAT lookback 。

以上2种失败，在外网访问域名时全部正常。

另：dhcp/DNS 设置时，去掉 “丢弃 RFC1918 上行响应数据” 勾选，一样失败。

版本：4.19.91  lusty编译

**Comment by alepennyq** [comment]
是Docker的锅，编译一个没有Docker的版本即可。

**Comment by shshunlan** [comment]
请问，去除docker软件能否成功？

**Comment by vlanbin** [comment]
#2103
重新编译不带docker的版本，或者不要初始化docker

**Comment by shshunlan** [comment]
没有初始化过docker，docker也手动停止了，还是不行。

**Comment by qiaowenbin** [comment]
确认是docker的锅
我也遇到了同样的问题
刚编译了一个不带docker的固件 直接恢复正常了
