### ISSUE TITLE
SSR服务器是否能加入redirect重定向参数？

### ISSUE THREAD

**Issue by edmundzhong888** [coolsnowwolf/lede#2781]
因为有需求人在外的时候通过SSR连回到公司再科学上网，之前一直用该功能，所以一直被KS绑架了，今天编译了L大的固件速度有明显的提升，已经把原来KS上的功能全部转移过来了，但就差这个“重定向”的功能了，试过ssh 修改json，但一重启SSR服务json会被重写了，不知道L大能否集成一个带redirect参数的ssr服务端？感谢L大的源码，感谢你提供的一些便捷。

**Comment by coolsnowwolf** [comment]
具体是改什么选项？

**Comment by coolsnowwolf** [comment]
有单独的 ssr server - python 版本，建议用那个，是全功能的

**Comment by edmundzhong888** [comment]
谢谢老大的回复！按老大的方式重新编译一个试试。

**Comment by edmundzhong888** [comment]
重新编译了一个加入了 ssr server - python 版本的模块，但LUCI里还是没有「redirect」配置选项？请指点为盼

**Comment by edmundzhong888** [comment]
已经搞掂了！不需要重定向了，谢谢L大的回复。
