### ISSUE TITLE
编译斐讯K3的固件加入amule APP编译报错缺少libbfd-2.27.so库

### ISSUE THREAD

**Issue by ZGNCZMY** [coolsnowwolf/lede#279]
这是编译的日志

**Comment by ZGNCZMY** [comment]
[build.log](https://github.com/coolsnowwolf/lede/files/1645557/build.log)

**Comment by Moekr** [comment]
amule的Makefile里DEPENDS部分加上`+libbfd`

**Comment by ZGNCZMY** [comment]
谢谢.编译成功了

**Comment by tinnlux** [comment]
求教怎么添加依赖+libbfd。。我刚入门，谢谢了！
