### ISSUE TITLE
luci aria2 tr 菜单不显示

### ISSUE THREAD

**Issue by dreamwrt** [coolsnowwolf/lede#28]
default-settings里面是把aria2 tr之类的单独放到一个名为 nas 的菜单下，这个菜单默认是没有的，所以导致aria2 tr 之类的菜单不能显示出来

**Comment by ypjalt** [comment]
在/lede/feeds/luci/modules/luci-mod-admin-full/luasrc/controller/admin/index.lua下
手动添加
这一行下面entry({"admin", "services"}, firstchild(), _("Services"), 40).index = true添加
entry({"admin","vpn"},firstchild(),_("VPN"),41).index=true
	entry({"admin","nas"},firstchild(),_("NAS"),42).index=true
要是lean来句脚本就更好了。

**Comment by coolsnowwolf** [comment]
嗯，我默认集成 vsftpd，就自动创建这个菜单。

建议你也集成吧，就几十KB，很实用~

**Comment by coolsnowwolf** [comment]
都放一起菜单太长了。。。。。强迫症
