### ISSUE TITLE
KcpTun 配置对小白不太友好

### ISSUE THREAD

**Issue by qiaowenbin** [coolsnowwolf/lede#2802]
kcptun设置有点过于简易了 小白看了比较蒙
希望大雕能把常用的设置项目做页面修改设置
或者直接加一点可以在KcpTun参数添加的修改配置的说明。。。

我就是那个蒙了的 实话实说有点白
一开始装了kcptun但是无效，后来服务端全默认才勉强跑起来，但是效果不好 
改了服务端的配置之后kcptun直接无效了   
翻到github之后才发现可以加参数改默认配置  破机场起飞
纯小白估计得蒙圈好久 蒙完之后估计也跑不起来
大佬有空的话可以做个修改简易化~  加个说明也行嘛~

**Comment by sqliuchang** [comment]
自己去看kcptun的文档啊，kcptun文档写的很清楚
就那10个以内的参数需要按需调整，其他的都默认就可以了

**Comment by qiaowenbin** [comment]
> 自己去看kcptun的文档啊，kcptun文档写的很清楚
> 就那10个以内的参数需要按需调整，其他的都默认就可以了
嗯 我的设置已经搞定
主要是对不太懂的人来说 看上去有些迷茫  不知道从哪下手

**Comment by coolsnowwolf** [comment]
还是推荐看下文档，KCP 目前用的人越来越少了，也没必要做的很多选项了

**Comment by ch1993128** [comment]
本来就不友好，ssr要自己写配置，和大雕说的一样，推荐看文档。

但确实好用
