### ISSUE TITLE
lean大的make menuconfig把adbyby编译到friendlywrt里面好像不生效

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#2816]
lean大的make menuconfig把adbyby编译到friendlywrt里面好像不生效

**Comment by norikohxb** [comment]
按照lean大的方式把dnsmasq full全部都加上去了，那个adbyby还是无效状态， 现在在系统日志里面都找不到了

**Comment by hahaher123** [comment]
到/etc/init.d/下去看看adbyby是否有运行权限。我把lean大源码放到官方源码里编译就有这现象，很多程序没有运行权限。

**Comment by norikohxb** [comment]
已经按照你的思路解决问题了，非常感谢你！
