### ISSUE TITLE
各种偿试无法解决的奇葩问题

### ISSUE THREAD

**Issue by Aromalct** [coolsnowwolf/lede#2817]
**使用环境：**
华为P20 EMUI8.1
**固件环境：**
ESXI6.7，ROS主路由，Openwrt旁路由
**故障现象：**
Lean大最新源码自编译的固件装好后（OpenWrt R9.12.31，内核：4.19.93，不仅是这个版本，之前的版本也偿试过），用华为P20看youtube视频——有时进首页即一直转圈，进不去；最常碰到的是切换视频经常会卡在前面几秒，即点开时可看，但过几秒（5～10秒不等）就卡住转圈圈，有时转一会就能播放，大部分情况是一直转圈，但关闭wifi再开马上就能播放。
**偿试排除：**
1、用11月7日自编译的Openwrt固件（OpenWrt R9.10.24，内核：4.19.81），在同样使用平台及固件使用环境下，P20上无上述故障；
2、用E大1.1小包，在同样使用平台及固件使用环境下，P20上无上述故障；
3、P20上使用V2ray客户端代理，上述故障消失；
4、近期自编译的固件（含上面所说最新的和近半个月的自编译固件——一直在偿试）虽在P20上有上述情况，但在电脑端、IOS端无上述情况；
5、新编译的固件无论包含11月7日固件SSR Plus+的配置，还是编译完再重新设置，故障都是一样的；
6、P20上的google play服务卸载更新后重新安装后，上述现象仍然存在；
7、新固件在Ubuntu 14、16、18上均编译过（含本地编译环境或云编译环境），P20的上述现象仍然存在；
8、无论是新固件还是老固件，在SSR Plus+中查看日志稳得一逼；
9、新固件用华为mate 8看视频，同样也存在上述情况；
10、网上大量搜索及ISSUES中未看到有类似问题；
**个人怀疑：**
是不是编译组件选择的问题、依赖问题等，因为11月7日自编译固件的.config已覆盖无法找回了。我的组件选择详见https://github.com/Aromalct/AutoBuild-OpenWrt/blob/master/x86_64.config 有没有大神帮看下是不是配置问题抑或是其他问题。若觉得还没描述清楚或要看什么日志，我也可以提供（只是我也不知道提供什么日志给大家）

**Comment by klever1988** [comment]
拿掉smartdns

ros好用吗 openwrt做主路由不好使吗
