### ISSUE TITLE
树莓派3B，SSR PLUS+界面打开错误

### ISSUE THREAD

**Issue by netseraph** [coolsnowwolf/lede#2818]
使用树莓派配置，编译成功。
刷入树莓派3B，配置无线后可以正常上网。
此时基本功能正常，SSR+界面可以正常打开，导入SS（使用的是Just My Socks)配置后,SSR PLUS+界面无法打开，提示如下错误：
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/admin/services/shadowsocksr'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocksr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua:20: bad argument #1 to 'upper' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by coolsnowwolf** [comment]
订阅的格式有问题，找机场
