### ISSUE TITLE
Adbyby和小米电视会员冲突

### ISSUE THREAD

**Issue by digitxp** [coolsnowwolf/lede#282]
这个问题困扰了好几个版本了。
开启Adbyby之后，小米电视的会员状态就刷不出来了，会员影片也没法观看。

今天用笨办法试了一下，似乎是和Adbyby默认黑名单里面的这条规则有关系：
abss.pandora.xiaomi.com

删掉了之后，小米电视会员就正常了。

因为无法访问上面的这个网址，也搜不到关于这个网址的有用信息，所以不能确定这是否只是我的个案。

写在这里供大神参考。

**Comment by mmd1989** [comment]
有时还会干扰米家智能设备的的登陆，米家app的登陆
