### ISSUE TITLE
V2 vmess 链接 参数传递异常。

### ISSUE THREAD

**Issue by my5xhni** [coolsnowwolf/lede#2820]
![V2 参数](https://user-images.githubusercontent.com/16264838/72707278-0484c080-3b9b-11ea-9617-587f9376402f.png)

大佬反馈一个问题，就是  导入VMESS链接，下面（加密方式 ---- Mux）的参数基本都没有被正确传递，上面（别名 ---- UUID）的是对的，下面的 参数要么传递错误，要么就不传递。

软件环境：

路由器
OpenWrt x86 R9.12.03, 内核版本 4.19.91, luci-app-ssr-plus | 1-131 ,v2ray | 4.21.3-1

Windows
Client: v2rayN _ v3.5      发布地址：https://github.com/2dust/v2rayN/releases

测试方法：网站上有的JSON下载打开，对比导入结果，v2rayN下面的参数传递 偶尔会有一丢丢问题，但是基本都是正确的，路由器端导入链接 就是我上面叙述的问题。

目前我是路由器直接导入vmess链接，没有链接的用W客户端扫描二维码，然后再用W客户端导出vmess链接，最后导入路由，最后对比JSON进行修改。

或许就是大佬所说的，目前没有统一的标准导致混乱，如果可以的话，还是请大佬 对比JSON把参数传递的问题解决一下吧。

辛苦了。

**Comment by Mattraks** [comment]
已修复 #2815
