### ISSUE TITLE
ssr-plus希望加入SSRoT

### ISSUE THREAD

**Issue by Basstorm** [coolsnowwolf/lede#2825]
v2早就有over TLS技术了，现在ssr也已经实现，大雕可以考虑一下？
https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki

**Comment by shikkoku** [comment]
这技术好像还没广泛铺开应用。

**Comment by coolsnowwolf** [comment]
其实如果用这个还不如老老实实 v2 算了
