### ISSUE TITLE
昨天更新的去广告规则会造成小米手机的WIFI 检测不正常。

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#2826]
昨天更新的去广告规则会造成小米手机的WIFI 检测不正常。就算能正常上网，都会提示wifi 无法正常连接，解决办法是去掉广告屏蔽大师 Plus+的强制走代理的域名里面的connect.rom.miui.com这条规则，问题解决，希望下次更新修复下

**Comment by jdjh520** [comment]
adbyebye规则更新之后小米应用商店打来开 好多小米应用连不上网了
