### ISSUE TITLE
luci里面勾选哪个可以让内网的客户端拨号到lean的openwrt，并且可以控制带宽流量的？

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#2827]
luci里面勾选哪个可以让内网的客户端拨号到lean的openwrt，并且可以控制带宽流量的？

学会了编译lean大的好东西，然后又学会了编译R1S的lean大的好东西，渐渐萌生想要用lean大加持的软路由替换出租房的磊科路由器。

出租房内的用户是要拨号上网到openwrt，然后还需要给他做一个限速。
不知道lean大的luci配置里面有没有可以勾选的。勾选完了以后可以让出租房的用户能以pppoe上网。

如果有知道的大神请赐教，在这里先行感谢了。

**Comment by norikohxb** [comment]
另外再请教一下，R1S因为自带2.4G，如果想要对2.4G的这个wifi，增加一个mac地址过滤的方式，
请问需要在编译的时候勾选lean大的什么选项？方便的话一并赐教。

**Comment by coolsnowwolf** [comment]
这个需求不太适合 OpenWrt 上面实现，建议ikuai之类

**Comment by norikohxb** [comment]
谢谢lean大的答复，我不提pppoe服务器+留空了，就是2.4G的那个R1S的wifi，是否可以mac地址过滤？

**Comment by coolsnowwolf** [comment]
自带

**Comment by norikohxb** [comment]
感谢感谢，非常感谢你的回答。感觉你是很忙的大神。
