### ISSUE TITLE
`架构` 处显示为 `?`

### ISSUE THREAD

**Issue by lyvivian0077** [coolsnowwolf/lede#2830]
用的nanoPi NEO2 编译的, `架构`处 显示为 `?`
请问这里怎么解决呢?

![2020-01-21 12 24 38](https://user-images.githubusercontent.com/12222794/72773020-250b5400-3c49-11ea-8232-90db153e08d1.png)

**Comment by coolsnowwolf** [comment]
ARMv8 的读取问题，不影响使用

**Comment by lyvivian0077** [comment]
我个人就是有点强迫症, 希望在以后的更新中能够解决此处问题.
