### ISSUE TITLE
能不能把hello world的安装ipk单独提取一下出来？

### ISSUE THREAD

**Issue by wilsonxu123** [coolsnowwolf/lede#2833]
能不能把hello world的安装ipk单独提取一下出来？

**Comment by lariboo** [comment]
hello world不是lean大雕源码里的插件。

**Comment by ch1993128** [comment]
。。。。。。推荐一本书
《B智能路由器开发指南》，张勇智，李章明出版，中国工信出版集团

奇怪的要求总是给别人提，又是没有利益关系的，基本都不会被满足。多自己做做，通过渠道找知识，哪怕是买呢，花不了多少钱

**Comment by ch1993128** [comment]
说话不好听哈，别介意，介意说一句我马上删

**Comment by wilsonxu123** [comment]
> hello world不是lean大雕原始里的插件。

那请问有什么办法提取吗？
