### ISSUE TITLE
广告屏蔽大师 Plus+ 开启后WiFi“已连接但无法连接互联网”

### ISSUE THREAD

**Issue by goukey** [coolsnowwolf/lede#2834]
小米手机，多台都同一个状况。无论用全局还是推荐模式都是一样。
关闭广告屏蔽大师 Plus+后正常。
怀疑是某规则屏蔽了miui检测连接情况的网址，请问谁知道是哪个网址，我放白名单里面。

**Comment by sundog315** [comment]
同求

**Comment by 9l** [comment]
#2826 看这里，这个问题昨天已经修复了 #2831 

另外如果小米手机自带应用商店不正常的话，app.market.xiaomi.com 这个域名加入白名单

**Comment by goukey** [comment]
修复了？？？
我确实是前天刚编译的，这是让我再编译一次啊

**Comment by 9l** [comment]
你在那个adblock文件里删掉 connet.rom.miui.com 域名也行
