### ISSUE TITLE
make menuconfig

### ISSUE THREAD

**Issue by flowlife** [coolsnowwolf/lede#284]
最新的menuconfig里面没有841n 和941n的机型

**Comment by ivyfm2** [comment]
最后支持 841n 941n 的 commit id 号是a75d5c7bfbe04c50d9bcc1c5742824dcfa34fa70

**Comment by AndyX-Net** [comment]
这个问题我问过了，参见https://github.com/coolsnowwolf/lede/issues/294

只是丢失了自定义的882Nv1和941Nv7之类的，希望可以在以后的版本中再加上。。。
