### ISSUE TITLE
R20.1.24-SSR PLUS不能启动，已经回退到12.31正常。

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#2850]
R20.1.24-SSR PLUS不能启动，已经回退到12.31正常。用的是V2ray。

**Comment by hcym** [comment]
这两天看到一通乱搞，过一阵子再说，现在用的官方的，感觉多核均衡比较好用

**Comment by KFERMercer** [comment]
没问题. 清除编译文件后重新编译

**Comment by momonoshiori** [comment]
清除编译文件后重新编译，SSR PLUS的V2ray还是不能用，SSR一直是正常的。

**Comment by klever1988** [comment]
# /usr/bin/v2ray/v2ray 
Illegal instruction

**Comment by blizzardster** [comment]
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading github.com/gorilla/websocket v1.4.1
go: extracting github.com/gorilla/websocket v1.4.1
go: downloading google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
go: downloading golang.org/x/text v0.3.0
go: extracting golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
卡这里了，

**Comment by d975xbx** [comment]
> 没问题. 清除编译文件后重新编译
编译没问题，问题是SSR PLUS里面的v2ray不能启动。
