### ISSUE TITLE
编译出来的固件会无限重启

### ISSUE THREAD

**Issue by wxs-dev** [coolsnowwolf/lede#2858]
机型：歌华链
硬件版本：v0.4

编译出来的固件在v0.3上能正常开机和使用，用在v0.4机子上就无限重启
放假回家，忘记带工具了，无法ttl看开机日志

**Comment by segadrive** [comment]
建议先factory刷固件，然后再升级自制固件

**Comment by wxs-dev** [comment]
> 建议先factory刷固件，然后再升级自制固件

尝试过，但不行

**Comment by AmadeusGhost** [comment]
v0.4和v0.3的区别是什么？没ttl日志不好分析。

**Comment by 467815891a** [comment]
有解决方法了吗，我有一台换了flash的newifi d1，刷老版本固件可以开机，一切正常。git pull之后就不能了，一直重启

**Comment by AmadeusGhost** [comment]
> 有解决方法了吗，我有一台换了flash的newifi d1，刷老版本固件可以开机，一切正常。git pull之后就不能了，一直重启

你换了flash的话，dts也要像 https://github.com/coolsnowwolf/lede/issues/3894#issuecomment-601795973 那样改下
