### ISSUE TITLE
建议关闭V2RAY中的Mux默认设置

### ISSUE THREAD

**Issue by xuesumin** [coolsnowwolf/lede#2861]
不少机场的v2ray订阅不支持Mux，所以一旦使用后，v2ray无法正常使用，需要手动一个个把Mux设置取消才能用。

谢谢大牛们的付出，新年快乐！

**Comment by klever1988** [comment]
从订阅地址添加节点的时候，mux默认就是关闭的。

**Comment by xuesumin** [comment]
> 从订阅地址添加节点的时候，mux默认就是关闭的。

奇怪，我就是从订阅地址添加的，全部自动开了mux。

**Comment by SharerMax** [comment]
嗯  不知道啥时候被改成默认开启了。。
