### ISSUE TITLE
建议将readme中的建议编译系统改为Ubuntu 18.04＋

### ISSUE THREAD

**Issue by KFERMercer** [coolsnowwolf/lede#2863]
Ubuntu 14.04 已于 2019-04-25 停止支持, 安全性和稳定性已经无法保证, 而且不如新版本易用.

在本主干分支正与trunk分支19.07合并的今天, 继续使用Ubuntu 14.04会降低编译成功率.

CI环境的稳定成功运行已经证明了用Ubuntu 18.04编译op没有问题.

最新的v2ray已经无法用旧版本的upx进行压缩, 以后此类问题会慢慢增多.

综上, 建议将readme中的建议编译系统改为Ubuntu 18.04＋.

**Comment by gsblay** [comment]
反馈一下：
        原生的18.04即使upgrade以后，安装的 upx 是 3.94 的，V2选压缩编译时，是没问题，但编译的结果在实体机运行时，V2ray 无法正常运行 ！

**Comment by KFERMercer** [comment]
3.96 压缩后能正常用. 难道版本不对压出来不能用? 神奇

**Comment by gsblay** [comment]
我的18.04是新的，upgrade以后，代码也是新拉的，但就是实体机运行不行。

**Comment by KFERMercer** [comment]
那这件事就变得复杂了, 刚刚在置顶上已经写明的需要3.95以上版本了, 感谢反馈.
