### ISSUE TITLE
提个小小建议

### ISSUE THREAD

**Issue by chacha20** [coolsnowwolf/lede#2865]
自建节点有几个，机场有几个，订阅更新后自建节点和机场就混合在一起了。希望能把自己添加的节点和机场节点分开显示，因为机场节点几十个，删除起来太困难了，而清除节点的话又把自建节点给清空了，操作实在很困难。：）

**Comment by chacha20** [comment]
哦忘了写package了。package名称是luci-app-ssr-plus。

**Comment by luckyyyyy** [comment]
可以提个PR 自己的没有hashkey 订阅的会有
