### ISSUE TITLE
编译完成了没有生成img文件咋办？

### ISSUE THREAD

**Issue by JackEHolmes** [coolsnowwolf/lede#2866]
[*] squashfs
Target Profile (Raspberry Pi 4B)

make[3]: Leaving directory `/home/jack/lede/feeds/packages/lang/golang/golang'
make[2]: Leaving directory `/home/jack/lede'
make[1]: Leaving directory `/home/jack/lede'

这是编译完成了吗？
怎么没有看到可以刷入树莓派的img文件
/lede/bin/targets/brcm2708/bcm2711# ls
config.seed  packages

**Comment by lyin888** [comment]
固件过大了吧

**Comment by AmadeusGhost** [comment]
![rpi](https://user-images.githubusercontent.com/42570690/73149381-03ecac80-40fc-11ea-941a-9fa9074e4a6f.png)
你试一下看看

**Comment by JackEHolmes** [comment]
> 固件过大了吧

那要怎么设置呢？

**Comment by JackEHolmes** [comment]
> ![rpi](https://user-images.githubusercontent.com/42570690/73149381-03ecac80-40fc-11ea-941a-9fa9074e4a6f.png)
> 你试一下看看

试过了，还是没有生成img文件

**Comment by KnowledegAndAction** [comment]
错误信息没贴全吧

**Comment by pbwind** [comment]
我也是。 
编译N1的固件的时候，不生成img。
但是生成tar.gz ，但是这个文件太小了。 只有10M不到。

**Comment by hcym** [comment]
n1就是这样格式，没有v2的话只有6M大小。
