### ISSUE TITLE
libcurl， libopenssl， libstdcpp的问题

### ISSUE THREAD

**Issue by yulinsoft** [coolsnowwolf/lede#2868]
使用19.07的软件源安装php7时，提示libcurl4， libopenssl1.1， libstdcpp6这几个库安装失败，其实这几个库编译时已经加上了，只是后面没有带数字版本号，应该只是包名的变化，19.07把这几个包加了个版本号，导致安装时文件冲突。虽然强制安装不影响使用，但感觉这类基础包还是应该跟进官方，不知道提的对不对。

**Comment by hyird** [comment]
自己编译安装吧  依赖的问题
