### ISSUE TITLE
luci里面的wrtbwmon插件貌似新版已经不能用了

### ISSUE THREAD

**Issue by idelame** [coolsnowwolf/lede#2869]
监测局域网下的其他机器的网速已经不准.不知是这个的原因还是依赖于nlbwmon有问题了.

**Comment by yulinsoft** [comment]
要关掉flowoffload里的硬件加速才行。

**Comment by idelame** [comment]
> 要关掉flowoffload里的硬件加速才行。

只能这样吗? 之前的版本貌似不用关也可以用.
