### ISSUE TITLE
ssr的订阅更新计划任务问题

### ISSUE THREAD

**Issue by fgprodigal** [coolsnowwolf/lede#2870]
每次计划任务更新订阅，只更新出来第一个订阅源的节点，手动更新则没问题。

年后计划把crontab加上日志跟一下是啥问题

**Comment by luckyyyyy** [comment]
因为可能那个时候 更新尝试了5次 还是无法链接上订阅地址 导致的

日志的确没加 这个问题可以提一下有什么好的办法

**Comment by fgprodigal** [comment]
我自己在crontab后面加了日志输出，观察两天先
