### ISSUE TITLE
docker选择bridge不能连外网，选择host没问题

### ISSUE THREAD

**Issue by tcsr200722** [coolsnowwolf/lede#2872]
使用lisaac/luci-app-dockerman建立容器，选择bridge不能连外网，选择host没问题
https://github.com/lisaac/luci-app-dockerman.git

**Comment by 9l** [comment]
能联网那就是没问题，你的docker设置有问题咯

**Comment by tcsr200722** [comment]
https://www.right.com.cn/forum/thread-1209004-1-1.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "QING LIU"<notifications@github.com&gt;; 
发送时间: 2020年1月27日(星期一) 下午2:58
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;; 
抄送: "350524166"<350524166@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [coolsnowwolf/lede] docker选择bridge不能连外网，选择host没问题 (#2872)




能联网那就是没问题，你的docker设置有问题咯

**Comment by tcsr200722** [comment]
解决方案：
然后vim /etc/sysctl.conf，添加下列内容：
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
后台修改设置：
Luci>网络>防火墙>转发：接受
Luci>状态>防火墙>重启防火墙
最后ssh执行service dockerd restart

**Comment by 962978926** [comment]
感谢，已用改方法解决。但想请教一下编译时如何把full cone nat的转发选项设置为默认打开。

**Comment by tcsr200722** [comment]
lede/package/network/config/firewall/files/firewall.config里面修改即可

**Comment by warrenhoo** [comment]
打开这个转发后 会不会整个LAN 下的客户端就是裸奔在互联网了呢？WAN到LAN的防火墙全部失效的意思
