### ISSUE TITLE
ssr plus+能否增加均衡负载？

### ISSUE THREAD

**Issue by vigwos** [coolsnowwolf/lede#2875]
ssr plus+能否增加均衡负载？

**Comment by 88adong88** [comment]
可以啊，提交你的代码即可

**Comment by programmejava** [comment]
ssr本身应该没有load balance 功能 。我现在用的是haproxy或者nginx的stream负载均衡，
    而且haproxy只能tcp ,好处是现在openwrt里有haproxy ，nginx 可以tcp udp但路由器上的nginx没有负载均衡的模块，所以只能上虚拟机了
          现在这个固件里有luci-app-haproxy这个功能 ，编译里选择就可以，用起来不难，前提是你的机场端口加密要一致；
        如果不一致，可以考虑上虚拟机  pve esxi 之类，中间加一层  建立几个虚拟机，虚拟机里连不同机场，然后再开服务端，端口加密统一设置 。也就是说在中间这一层服务里里同时存在客户端和服务器端 ，这样一来成本比较高了。生命不息折腾不止。
     我曾搞过前面wireguard连vps  再开上ssr服务端 路由器ssr客户端连接虚拟机，实现负载均衡。由于wireguard只能是udp容易被isp  qos。
