### ISSUE TITLE
ipv6环境下v2ray无法运行

### ISSUE THREAD

**Issue by jzh33** [coolsnowwolf/lede#2880]
IPv6配置ok，获取地址正常，上网正常，v2ray无法运行，重刷纯IPv4固件v2ray正常运行，不知道是个什么原因，v2ray日志无错误，显示started，但实际并没运行。

**Comment by hcym** [comment]
害得pc登录还要验证码
target.mk里面
DEFAULT_PACKAGES.router:=dnsmasq-full iptables ip6tables firewall odhcpd-ipv6only odhcp6c kmod-ipt-offload kmod-tcp-bbr
大雕没有odhcpd-ipv6only odhcp6c 
安装也行，最好编译时加，免得内核依赖麻烦

**Comment by hcym** [comment]
路由里ping一下
通就ok，不用管lan

**Comment by jzh33** [comment]
谢谢我去试试，重新编译一下固件。

**Comment by qq523407234** [comment]
我没这问题，ipv6helper勾上就完事儿了，其他依赖自动装的
