### ISSUE TITLE
SSR Plus+如何设置成默认lan全不代理 只有指定lan ip才代理

### ISSUE THREAD

**Issue by loyle5** [coolsnowwolf/lede#2881]
SSR Plus+如何设置成默认lan全不代理 只有指定lan ip才代理
LAN IP访问控制那里怎么设置呢?

**Comment by 88adong88** [comment]
SSR PLUS-Lan ip访问控制-不走代理的Lan ip列表里，把整个网段ip一个一个添加进去，复制粘贴也就10分钟吧

**Comment by loyle5** [comment]
> SSR PLUS-Lan ip访问控制-不走代理的Lan ip列表里，把整个网段ip一个一个添加进去，复制粘贴也就10分钟吧

就是不想这么麻烦才问还有没有其他的解决办法呀

**Comment by coolsnowwolf** [comment]
子网掩码

**Comment by OUZYcn** [comment]
> SSR Plus+如何设置成默认lan全不代理 只有指定lan ip才代理
> LAN IP访问控制那里怎么设置呢?

192.168.1.0/24 可用IP就是254个，你自己查去：
https://tool.chinaz.com/tools/subnetmask
