### ISSUE TITLE
能不能开发一个比较方便的wiregurd分流控制端

### ISSUE THREAD

**Issue by jocongmin** [coolsnowwolf/lede#2882]
感觉wiregurd网络接口太难用了，能不能开发一个luci方便控制分流wiregurd

**Comment by hcym** [comment]
去年前年不错，k2能跑满百兆，而且cpu极低，我也说了几次，今年不行了，好像是udp卡住了，有人用tcp转换的，太复杂就怕怕没用。偶尔手机用用，还是ipv6，ipv4的死活不通
