### ISSUE TITLE
让编译机全局科学上网的一种解决办法

### ISSUE THREAD

**Issue by jdjingdian** [coolsnowwolf/lede#2883]
如果编译时本身路由器没有科学上网功能，只能挂XXR等代理的话，可以通过以下代码
`git config --global http.proxy 'socks5://127.0.0.1:1080' `
`git config --global https.proxy 'socks5://127.0.0.1:1080'`
`export ALL_PROXY=socks5://127.0.0.1:1080`
`source /etc/profile`
让终端和git的上网流量全部走本地socks5代理

**Comment by 88adong88** [comment]
我的方法是把编译机的ip 加入全局代理Lan ip列表里 

位置在SSR plus-访问控制-Lan ip访问控制-全局代理Lan ip
