### ISSUE TITLE
访问控制无效

### ISSUE THREAD

**Issue by zydycjr** [coolsnowwolf/lede#2885]
白名单 黑名单 ip 以及 域名 都是无效的。

**Comment by zydycjr** [comment]
在 GFW列表手动加入域名也是没有生效不知道原因为何

**Comment by 9l** [comment]
你啥版本的，编译了最新版的吗？

**Comment by zydycjr** [comment]
是的

**Comment by 9l** [comment]
我这没问题，访问控制域名可以用现在，域名你怎么写，来些截图看看

**Comment by zydycjr** [comment]
![image](https://user-images.githubusercontent.com/24642591/73599897-3ecf6400-4584-11ea-8b2e-1d04bae62d3f.png)
![image](https://user-images.githubusercontent.com/24642591/73599902-4858cc00-4584-11ea-9897-ebb39c3053cb.png)

**Comment by zydycjr** [comment]
请看截图 都不起作用

**Comment by zydycjr** [comment]
![image](https://user-images.githubusercontent.com/24642591/73599908-5c9cc900-4584-11ea-92ab-ad8dc0bc831c.png)

**Comment by 9l** [comment]
你这是自己编译的固件么，改了啥，加了啥

看看这个 #2771
