### ISSUE TITLE
SSR Plus+ 可否在 `运行模式` 中添加 `自定义模式`

### ISSUE THREAD

**Issue by lyvivian0077** [coolsnowwolf/lede#2886]
#### SSR Plus+ 可否在 `运行模式` 中添加 `自定义模式`

@coolsnowwolf 

- 我用SSR只有特定的几个网站需要走代理, 现有的4个模式都不适合我
- 能否添加一个 `自定义模式`, 在 `黑白名单` 中添加自己想代理的网站或IP

**Comment by CYaNu** [comment]
关闭ssr ++的自动更新  ssh你的路由器 修改 ./etc/dnsmasq.ssr/gfw_list.conf 里的内容
为你想要的那几个网站 代理模式选gfw 记得清空同目录的gfw_base.conf可以保证其他网站一点不翻墙

**Comment by lyvivian0077** [comment]
@CYaNu 
谢谢你的解答.
这种方法我竟然没有想到... Orz

但还是觉得有点麻烦,毕竟要SSH
如果能在WebUI上解决的话,会更完美一些.毕竟偶尔会有更新几个需要代理的网站.
