### ISSUE TITLE
酷软v2ray无法添加233脚本自动生成的WS+TLS模式json字符串。

### ISSUE THREAD

**Issue by shaowenjie** [coolsnowwolf/lede#2887]
bash <(curl -s -L https://git.io/v2ray.sh)这个脚本生成的WS+tls模式代理，域名解析成功。使用梅林的科学上网填入端口 代理域名等也能正常识别翻墙，使用v2rayn等工具也可以正常代理，但是使用v2ray link生成的JSON字符串放到LEDE的V2RAY插件中就出现代理节点添加失败 无法开启V2RAY节点的情况。谁有同样的情况麻烦告知下如何解决

**Comment by hxlls** [comment]
走错门了，兄弟，这里没酷软，也没lede
