### ISSUE TITLE
ddns远程访问

### ISSUE THREAD

**Issue by qyq3553867** [coolsnowwolf/lede#2888]
公网ip.设置好了端口转发，nas也开启了ddns远程访问，外网访问有时能连接上有时不行，这是怎么回事呢大佬？以前用ks上好像没这个问题呀，该怎么设置呢？

**Comment by inlolo** [comment]
具体哪家的ddns服务，如果有时候能上，看看多久拨号一次

**Comment by qyq3553867** [comment]
> 具体哪家的ddns服务，如果有时候能上，看看多久拨号一次

群晖的呀

**Comment by inlolo** [comment]
那你不是使用openwrt内置ddns服务，你应该问群辉技术支持

**Comment by qyq3553867** [comment]
> 那你不是使用openwrt内置ddns服务，你应该问群辉技术支持

之前用的ks的lede没有不能上的问题呀

**Comment by qyq3553867** [comment]
> openwrt内置ddns服务

内置的要钱的吗？

**Comment by inlolo** [comment]
> > openwrt内置ddns服务
> 
> 内置的要钱的吗？

去申请个免费的呗
