### ISSUE TITLE
squashfs-tools编译出错

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#2895]
config选中
CONFIG_PACKAGE_squashfs-tools-mksquashfs=y
CONFIG_PACKAGE_squashfs-tools-unsquashfs=y
编译的时候会出错

make[3]: Entering directory '/home/liwenjie/lede/feeds/packages/utils/squashfs-tools'
rm -f /home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/.built
touch /home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/.built_check
make -C /home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/squashfs-tools CC="aarch64-openwrt-linux-musl-gcc" EXTRA_CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3:squashfs-tools-4.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/usr/include -I/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/include -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/usr/include -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/include/fortify -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/include" EXTRA_LDFLAGS="-L/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/usr/lib -L/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/lib -L/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/usr/lib -L/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib -znow -zrelro" AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3:squashfs-tools-4.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CROSS="aarch64-openwrt-linux-musl-" ARCH="aarch64" XATTR_SUPPORT= XZ_SUPPORT=1 LZO_SUPPORT=1 LZ4_SUPPORT=1 mksquashfs unsquashfs
make[4]: Entering directory '/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/squashfs-tools'
aarch64-openwrt-linux-musl-gcc  -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3:squashfs-tools-4.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/usr/include -I/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/include -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/usr/include -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/include/fortify -I/home/liwenjie/lede/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/include -I. -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DCOMP_DEFAULT=\"gzip\" -Wall -DGZIP_SUPPORT -DXZ_SUPPORT -DLZO_SUPPORT -DLZ4_SUPPORT   -c -o mksquashfs.o mksquashfs.c
mksquashfs.c: In function 'create_inode':
mksquashfs.c:996:24: error: called object 'major' is not a function or function pointer
   unsigned int major = major(buf->st_rdev);
                        ^~~~~
mksquashfs.c:996:16: note: declared here
   unsigned int major = major(buf->st_rdev);
                ^~~~~
mksquashfs.c:997:24: error: called object 'minor' is not a function or function pointer
   unsigned int minor = minor(buf->st_rdev);
                        ^~~~~
mksquashfs.c:997:16: note: declared here
   unsigned int minor = minor(buf->st_rdev);
                ^~~~~
mksquashfs.c:1020:24: error: called object 'major' is not a function or function pointer
   unsigned int major = major(buf->st_rdev);
                        ^~~~~
mksquashfs.c:1020:16: note: declared here
   unsigned int major = major(buf->st_rdev);
                ^~~~~
mksquashfs.c:1021:24: error: called object 'minor' is not a function or function pointer
   unsigned int minor = minor(buf->st_rdev);
                        ^~~~~
mksquashfs.c:1021:16: note: declared here
   unsigned int minor = minor(buf->st_rdev);
                ^~~~~
mksquashfs.c: In function 'dir_scan2':
mksquashfs.c:3559:17: warning: implicit declaration of function 'makedev' [-Wimplicit-function-declaration]
   buf.st_rdev = makedev(pseudo_ent->dev->major,
                 ^~~~~~~
<builtin>: recipe for target 'mksquashfs.o' failed
make[4]: *** [mksquashfs.o] Error 1
make[4]: Leaving directory '/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/squashfs-tools'
Makefile:89: recipe for target '/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/.built' failed
make[3]: *** [/home/liwenjie/lede/build_dir/target-aarch64_generic_musl/squashfs-tools-4.3/.built] Error 2
make[3]: Leaving directory '/home/liwenjie/lede/feeds/packages/utils/squashfs-tools'
time: package/feeds/packages/squashfs-tools/compile#0.29#1.67#2.30
package/Makefile:107: recipe for target 'package/feeds/packages/squashfs-tools/compile' failed
make[2]: *** [package/feeds/packages/squashfs-tools/compile] Error 2
make[2]: Leaving directory '/home/liwenjie/lede'
package/Makefile:103: recipe for target '/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/home/liwenjie/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/liwenjie/lede'
/home/liwenjie/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by AmadeusGhost** [comment]
已提交相关pr
