### ISSUE TITLE
为何最新版V2Ray只能使用TCP模式，不能使用mKcp+WechatVideo模式？

### ISSUE THREAD

**Issue by pirately** [coolsnowwolf/lede#2899]
请问，为何最新版V2Ray只能使用TCP模式，不能使用mKcp+WechatVideo模式？
V2Ray版本为4.22.1-6，固件为 R20.1.24，内核为4.19.98，x86
表现为，用TCP模式，连接测试显示OK，并且能出国留学。但是用mKcp模式，则连接测试显示fail，不过能ping延迟照样显示，但是不能出国留学。
请问这是为何？
电脑本身用V2RayN，手机用其他代理软件都是mKcp没有问题的。
软路由都是格盘全新装的最新编译的固件。

**Comment by EstFoxs** [comment]
mkcp正常使用
![2020-01-31_095102](https://user-images.githubusercontent.com/1283711/73506065-5a652e00-440f-11ea-973c-2a36a826b7fd.jpg)

**Comment by pirately** [comment]
> mkcp正常使用，不过个人感觉1.24版mkcp的速度慢了不少，经过这几天的使用，慢了将近2/3

![mKcp](https://user-images.githubusercontent.com/57277605/73511239-ef702300-441f-11ea-84cd-f6140c013d6c.png)
![mKcp fail](https://user-images.githubusercontent.com/57277605/73511245-f39c4080-441f-11ea-850a-0e6eb8ec12c3.png)
![Tcp](https://user-images.githubusercontent.com/57277605/73511248-f7c85e00-441f-11ea-8ee2-8328b72fe66e.png)
![Tcp OK](https://user-images.githubusercontent.com/57277605/73511252-fa2ab800-441f-11ea-94e1-e26a04427263.png)

mKcp和TCP截图。我是换了运营商也一样。难不成和系统有关系？您在VPS上用的是什么系统？我用的是Debian

**Comment by EstFoxs** [comment]
> > mkcp正常使用，不过个人感觉1.24版mkcp的速度慢了不少，经过这几天的使用，慢了将近2/3
> > ![2020-01-31_095102](https://user-images.githubusercontent.com/1283711/73506065-5a652e00-440f-11ea-973c-2a36a826b7fd.jpg)
> 
> 这是我的截图：
> ![mKcp](https://user-images.githubusercontent.com/57277605/73511239-ef702300-441f-11ea-84cd-f6140c013d6c.png)
> ![mKcp fail](https://user-images.githubusercontent.com/57277605/73511245-f39c4080-441f-11ea-850a-0e6eb8ec12c3.png)
> ![Tcp](https://user-images.githubusercontent.com/57277605/73511248-f7c85e00-441f-11ea-8ee2-8328b72fe66e.png)
> ![Tcp OK](https://user-images.githubusercontent.com/57277605/73511252-fa2ab800-441f-11ea-94e1-e26a04427263.png)
> 
> mKcp和TCP截图。我是换了运营商也一样。难不成和系统有关系？您在VPS上用的是什么系统？我用的是Debian

debian系统也有，centos也有
都正常

**Comment by pirately** [comment]
> 
> debian系统也有，centos也有
> 都正常

那您用的是哪个vps服务商？

**Comment by coolsnowwolf** [comment]
测试可用

**Comment by TheAutomatic** [comment]
我和楼主一样，tcp完全没问题；手机v2rayNG客户端跑mKCP也没问题，K3路由器lede跑mKCP不行

**Comment by hcym** [comment]
kcp可以，用的n1和x86，k3和r7800有点吃力，效果要看线路的，用瓦工还是tcp好，用vurlt和cc什么kcp好一些

**Comment by TheAutomatic** [comment]
> kcp可以，用的n1和x86，k3和r7800有点吃力，效果要看线路的，用瓦工还是tcp好，用vurlt和cc什么kcp好一些

我用的是Azure香港服务器，想弄ws+tls来着，域名ssl证书死活不给签发

**Comment by verOn1204** [comment]
> > debian系统也有，centos也有
> > 都正常
> 
> 那您用的是哪个vps服务商？

请问有解决么？我也碰到这个问题了
