### ISSUE TITLE
反馈一个无线连接的问题，望高手指教

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#290]
刷了默认配置的固件，2.4g当信号弱点，手机大概在两格信号左右时，连接路由器会提示身份验证问题，然后一直反复连接不上，有时候信号弱点也会自己掉线。只有当距离近点，信号强点，才一切正常。有高手知道怎么回事吗，望指教，感谢！

**Comment by plutoghost** [comment]
iphone? 苹果设备从ios8以后连2.4g wifi信号弱到不能忍而且时断时续

**Comment by jxph1123** [comment]
安卓手机
