### ISSUE TITLE
网易云只对windows的PC端有效

### ISSUE THREAD

**Issue by tefiszx** [coolsnowwolf/lede#2903]
今天才发现unblockneteasemusic这个插件，只能解锁windows版的网易云客户端。对UWP版、手机版的（安卓客户端，ios的没试），网页版的，都不能解锁。

**Comment by jzh33** [comment]
我iOS，MacOS都没弄成功，uwp版显示是亮的但还是播放不了，所以我就没折腾了。

**Comment by coolsnowwolf** [comment]
认真看说明，和 HTTPS 证书有关
