### ISSUE TITLE
2月1日编译的新版本upnp无列表显示了

### ISSUE THREAD

**Issue by idelame** [coolsnowwolf/lede#2906]
没有之前的各个机器打通的ip和端口的显示了,只显示没有活动的重定向,别人有这样的情况吗?

刚发现dhcp里面也不显示了...重新编译也是如此

**Comment by kl9800** [comment]
我也是，
而且在DHCP里给某设备设置了固定IP，不生效，
比如我设置的是192.168.1.3，但实际上该设备获取到的IP是192.168.1.149，
而且在“路由表”里面看到这台设备有2个IP（分别是192.168.1.149与192.168.1.3）

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/73671951-fc726800-46e6-11ea-85cc-ced3aedd11c7.png)
你说的这个？没问题

**Comment by idelame** [comment]
对  一个都不显示  但实际是upnp重定向成功的.

**Comment by idelame** [comment]
看了很多文章 都说是新版的miniupnp有问题,官方不建议使用upnp,但又没有其他的可替代,怎么换回旧版的miniupnp?

**Comment by AmadeusGhost** [comment]
> 看了很多文章 都说是新版的miniupnp有问题,官方不建议使用upnp,但又没有其他的可替代,怎么换回旧版的miniupnp?

本来就是旧版的，个人倾向于是太旧了
