### ISSUE TITLE
强制DHCP服务好像不起作用

### ISSUE THREAD

**Issue by guitengyue** [coolsnowwolf/lede#2909]
家里原来有一个无线中继AP（同网段），发现勾上这个选项后，还是被中继的AP的dhcp给获取过去了；
然后改方案，关闭中继AP的DHCP，结果发现AP出去的wifi信号无法获取同级主路由的DHCP信息，原来的LEDE固件全部正常

**Comment by 9l** [comment]
你ap设置有问题吧

**Comment by guitengyue** [comment]
中继ap 应该没问题 我用koolshare的lede 一切正常





------------------ 原始邮件 ------------------
发件人: QING LIU <notifications@github.com&gt;
发送时间: 2020年2月2日 10:54
收件人: coolsnowwolf/lede <lede@noreply.github.com&gt;
抄送: guitengyue <guitengyue@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[coolsnowwolf/lede] 强制DHCP服务好像不起作用 (#2909)




你ap设置有问题吧
