### ISSUE TITLE
有个BUG，刷新软件源后提示和图标不消失 【问题解决】

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#2918]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/73602338-30497280-45ad-11ea-926c-dd126b607c35.png)

**Comment by hyird** [comment]
这。。。。。。。。。。。。。。。。

**Comment by hxlls** [comment]
最新源码编译测试没问题，请更新，还有，图标这玩意，好像这套源码没有啊，你确认没走错门？
附上截图：
![image](https://user-images.githubusercontent.com/43886952/73604892-7533d000-45d2-11ea-9919-fc3ab63ae5b1.png)

**Comment by lloyd18** [comment]
> 最新源码编译测试没问题，请更新，还有，图标这玩意，好像这套源码没有啊，你确认没走错门？
> 附上截图：
> ![image](https://user-images.githubusercontent.com/43886952/73604892-7533d000-45d2-11ea-9919-fc3ab63ae5b1.png)
> ![image](https://user-images.githubusercontent.com/43886952/73604939-d2c81c80-45d2-11ea-8cf9-42872ee8f922.png)

可能是我说得不够清楚，可以刷新列表，但是刷新后这个提示是不是该消失了，但它一直在啊，请看标注的地方

**Comment by hxlls** [comment]
这个重来不会消失，为什么你认为他需要消失？

**Comment by lloyd18** [comment]
> 这个重来不会消失，为什么你认为他需要消失？

![1](https://user-images.githubusercontent.com/10294460/73605034-15d6bf80-45d4-11ea-95ea-501075ee1f41.png)

**Comment by hxlls** [comment]
测试了，软件源问题，之前没认真看，自己修改下源配置就行了

**Comment by lloyd18** [comment]
> 测试了，软件源问题，之前没认真看，自己修改下源配置就行了

请问怎么改，不懂

**Comment by hxlls** [comment]
配置，把option check_signature 注释掉或者删除，这个是软件签名

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/73605154-abbf1a00-45d5-11ea-8c96-8535ef3f0bb3.png)
你也可以把这个玩意去掉重新编译，大概位置是
![image](https://user-images.githubusercontent.com/43886952/73605165-c5606180-45d5-11ea-86eb-c7e9f7819df4.png)

**Comment by lloyd18** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/73605154-abbf1a00-45d5-11ea-8c96-8535ef3f0bb3.png)
> 你也可以把这个玩意去掉重新编译，大概位置是
> ![image](https://user-images.githubusercontent.com/43886952/73605165-c5606180-45d5-11ea-86eb-c7e9f7819df4.png)

非常感谢，方法有用
