### ISSUE TITLE
R7800 firmware ath10k-ct日志好多kern.warn

### ISSUE THREAD

**Issue by hubbylei** [coolsnowwolf/lede#2920]
Feb  1 12:09:04 kern.warn kernel: [70574.486624] ath10k_pci 0000:01:00.0: Unknown eventid: 40955
这种日志好多 但可以正常使用 求大指点为怎么解决-.-!

**Comment by AmadeusGhost** [comment]
确定用的是```kmod-ath10k-ct```和```ath10k-firmware-qca9984-ct```嘛
```kmod-ath10k```和```ct firmware```混用会出现这种情况

**Comment by hubbylei** [comment]
我用默认配置编译的 应该是kmod-ath10k-ct和ath10k-firmware-qca9984-ct吧?

**Comment by hubbylei** [comment]
我看了下配置好像是混用了,我重新编译下,谢谢大神
