### ISSUE TITLE
树莓派4 无法初始化Docker

### ISSUE THREAD

**Issue by Troyshen94** [coolsnowwolf/lede#2921]
自行编译了树莓派4的固件
初始化Docker时候把脚本中的sda改成TF卡的路径mmcblk0

但是提示无法写入，现在我是插了一个U盘来初始化，不知道我要怎么操作才能用上TF卡里面剩下的空间

**Comment by SharerMax** [comment]
用分区工具自己分区，然后在挂载点挂载新分区，用途选docker
