### ISSUE TITLE
编译到一半（编译开始大约1~2小时后）出现交互选项，应该怎么做？

### ISSUE THREAD

**Issue by SciUnivMoring** [coolsnowwolf/lede#2926]
![a](https://user-images.githubusercontent.com/31263957/73606425-1035a580-45e5-11ea-9dac-b6ac83cfcabc.png)

**请问应该选哪个？n还是m？前面几个自动选了n，到这里就停下了。**

所有的源码都是今天刚拉取的（完全按照readme.md来的）

**Comment by blankhang** [comment]
我按了回车....

**Comment by josephzjw** [comment]
我也出现这个状况，现在50G磁盘满了，之前已经`make clean`过了..

**Comment by 4593645** [comment]
什么机器环境？

**Comment by kl9800** [comment]
> 什么机器环境？

乌班图18

**Comment by qdfansanyblog** [comment]
一样出现这个选项，选的n回车

**Comment by hue715** [comment]
出现交互前出现以下警报：（用make menuconfig保存的.config)
make[5]: Entering directory '/home/tom/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.98'
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --syncconfig Kconfig
net/sched/Kconfig:44: warning: menuconfig statement without prompt
.config:3202:warning: override: M586MMX changes choice state
.config:4192:warning: symbol value 'm' invalid for NF_NAT_REDIRECT
.config:5933:warning: override: SPARSEMEM_MANUAL changes choice state
*
* Restart config...
*
*
* PHY Device support and infrastructure
*
PHY Device support and infrastructure (PHYLIB) [M/y/?] m

**Comment by SciUnivMoring** [comment]
> 什么机器环境？

Ubuntu 18.04 LTS

**Comment by josephzjw** [comment]
我后来发现好像是我的硬盘满了，我 `make dirclean`， `make clean` 以后重新编译好像就行了
