### ISSUE TITLE
编译后出现登陆web界面不需要密码的情况

### ISSUE THREAD

**Issue by authon** [coolsnowwolf/lede#2927]
2号晚在线编译的固件，集成了passwall。刷好后登陆web界面不输密码回车就进入管理页面，里面的全部设置修改好后都无法保存。哪位大神知道什么情况

**Comment by WinRose-C** [comment]
你是不是编译成内存固件了哦？

**Comment by authon** [comment]
> 你是不是编译成内存固件了哦？

哪里的设置问题吗
