### ISSUE TITLE
端口转发好像有点问题

### ISSUE THREAD

**Issue by Paris0-0** [coolsnowwolf/lede#2928]
设置了端口转发后，如果内外网端口一致速度正常，但如果端口不一致，上传速度正常，下载速度很慢很慢，弄了很久搞不懂问题出在哪，只能暂时把端口都设置成一样的

**Comment by trackycn** [comment]
我最新版本编译的, 不带 Docker, 端口转发必须内外网端口一样才可以转发, 不一样的话无法转发。我把 Flow Offloading 关闭后恢复正常, 你也试试看关闭 Flow Offloading 后速度是不是恢复!

**Comment by Paris0-0** [comment]
确实，关了以后速度就挺正常的，感谢🙏

**Comment by xydche** [comment]
> 我最新版本编译的, 不带 Docker, 端口转发必须内外网端口一样才可以转发, 不一样的话无法转发。我把 Flow Offloading 关闭后恢复正常, 你也试试看关闭 Flow Offloading 后速度是不是恢复!

确实是这样，端口一样正常，不一样的无法转发。我还以为是转发设置问题😅
