### ISSUE TITLE
luci-app-frp在openwrt19.07下Failed to execute cbi dispatcher target for entry '/admin/services/frp'的错误，编译时需要修改哪些地方？

### ISSUE THREAD

**Issue by Mackerly** [coolsnowwolf/lede#2929]
Failed to execute cbi dispatcher target for entry '/admin/services/frp'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/frp/frp.lua:2: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/frp/frp.lua:2: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:943: in function </usr/lib/lua/luci/dispatcher.lua:937>

![image](https://user-images.githubusercontent.com/26422146/73625259-0496bd00-467f-11ea-851e-eba1fe6f622f.png)

**Comment by haxc** [comment]
https://www.right.com.cn/forum/thread-306836-1-1.html
用这个
