### ISSUE TITLE
这到底是咋啦，

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#2935]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/73666749-3db24a00-46de-11ea-82a4-f69746de463a.png)
依赖全没了？

**Comment by 9l** [comment]
没问题啊，之后会自己安装这些依赖的

**Comment by lloyd18** [comment]
> 没问题啊，之后会自己安装这些依赖的

好吧，编译了一遍，没问题
