### ISSUE TITLE
使用git pull之后在make menuconfig中丢失了很多设备显示

### ISSUE THREAD

**Issue by AndyX-Net** [coolsnowwolf/lede#294]
问题关闭

**Comment by AndyX-Net** [comment]
抱歉问题已经解决，查询了target/linux/ar71xx/image/目录发现使用了tiny分项。。。

选择make menuconfig -> Subtarget ->Deviece with small flash选项之后在Target Profile中即可见。

但是之前自定义的882Nv1和941Nv7都没有了比较可惜，希望能再次添加上。

**Comment by amoboy** [comment]
请问编译出的来固件没有squashfs......也没有factory.bin.....求解

**Comment by AndyX-Net** [comment]
@amoboy 查询你输出的错误信息，预计可能是包过大(错误信息中包含 **_TOO_** BIG 字样)。也就是说这经常发生于4M 大小的FLASH固件上，放不了太多东西。
