### ISSUE TITLE
静态地址分配,租期infinite 错误

### ISSUE THREAD

**Issue by zuozhehao** [coolsnowwolf/lede#2941]
静态地址分配,租期设置为`infinite`,实际则是90d的数据。

![1](https://user-images.githubusercontent.com/4464252/73722268-15b7fa80-4761-11ea-9e61-3b6208879cbf.png)

静态地址分配
![2](https://user-images.githubusercontent.com/4464252/73722286-20728f80-4761-11ea-9605-126155e0cd53.png)

ssh 看配置文件
![3](https://user-images.githubusercontent.com/4464252/73722411-64659480-4761-11ea-8f17-e463559e8f60.png)

---
30几个设备目前出现这样问题的都是苹果设备(手机，平板，电脑)，不确定是凑巧还是什么问题。其他非苹果设备均显示正常`无限制`

**Comment by Jefffish09** [comment]
@zuozhehao 您好，我也发现同样问题，请问解决or找到原因了吗？
