### ISSUE TITLE
ssr-plus使用v2ray相关

### ISSUE THREAD

**Issue by xj999** [coolsnowwolf/lede#2942]
主机型号：Phicomm PSG1208
--
架构：MediaTek MT7620A ver:2 eco:6 x 1
固件版本：OpenWrt R20.1.24 / LuCI Master (git-20.032.31649-0d31472)
编译只选了mtk和设备 1208 其余默认
刷到路由器上后 在ssr-plus上导入v2链接
![image](https://user-images.githubusercontent.com/5276662/73723297-ab548980-4763-11ea-8715-040bb2534fe3.png)
无法正确识别   请问应该如何使用   是否是编译的时候需要多操作什么

**Comment by caoli5288** [comment]
这个u性能太差，跑v2ray能跑到你路由器断网的，别想了

**Comment by AmadeusGhost** [comment]
v2需要在luci-app-xxr-plus那选上
不过k2配置太低了，8M flash能不能编译进去都是问题

**Comment by badcrazy** [comment]
V2ray的包有没有编译进去？另外7620的配置要稳定的话，去广告，翻墙这类还是算了
