### ISSUE TITLE
docker装jellyfin硬解相关参考

### ISSUE THREAD

**Issue by wooleo** [coolsnowwolf/lede#2947]
默认编译是没有显卡驱动的，添加后可以实现硬解

make kernel_menuconfig

进去后选Device Drivers ->Graphics support ，选中 Direct Rendering Manager、Intel 8xx/9xx****

重新编译安装后，可以在/dev/dri下看到显卡设备。

**Comment by hcym** [comment]
op接显卡看什么？我的声卡显卡usb驱动还有软路由的wifi驱动都是特地去掉了

**Comment by wooleo** [comment]
> op接显卡看什么？我的声卡显卡usb驱动还有软路由的wifi驱动都是特地去掉了

核显只做 解码串流给移动设备，只做运算，不连接设备

**Comment by hxlls** [comment]
显卡可以直接用docker 调用进行挂载转码，不过转码这玩意对CPU使用比较蛋疼再有些片源可能会引起CPU满载，造成网络故障

**Comment by wooleo** [comment]
> 显卡可以直接用docker 调用进行挂载转码，不过转码这玩意对CPU使用比较蛋疼再有些片源可能会引起CPU满载，造成网络故障

是的，不支持硬解的片源会导致cpu占用率过高，可以docker限制cpu避免。不少人是高性能软路由，多个玩具多份快乐

**Comment by R3pl4c3r** [comment]
mark一下

**Comment by KFERMercer** [comment]
mark
