### ISSUE TITLE
编译时libuhttpd报错

### ISSUE THREAD

**Issue by mbax2zf2** [coolsnowwolf/lede#2953]
编译时libuhttpd 2.0.3报错，upstream_printf()函数报错，too many arguments for [-Werror=format-extra-args]，错误原因是libuhttpd/src/utils.c文件49行多了一个len参数，手动修正后编译跑下去了。
作者在2.2.2版本提交了修复，https://github.com/zhaojh329/libuhttpd/commit/390ed1865d7e54ad40c978af1a651e 
有人遇到过和我一样的情况么，大佬看看是否需要更新libuhttpd修复一下

**Comment by mbax2zf2** [comment]
79行也有一个= =不知道到底为啥，求助

**Comment by hyird** [comment]
我也遇到了 tnnd 坑的我不要不要的 我以为是系统问题 装了好多次了

**Comment by hyird** [comment]
能自己修正代码  牛逼 啊  我只会google。。

**Comment by hyird** [comment]
这个在feeds里面 只能去官方openwrt提交pr了
