### ISSUE TITLE
WNDR3800用ATH79编译的固件，2.4G wifi速度明显慢于AR71xx分支

### ISSUE THREAD

**Issue by PlumWolf** [coolsnowwolf/lede#2962]
WNDR3800使用AR71xx分支编译的固件，2.4G wifi，强制40Mhz，最好的状态可以跑到10MB/s，ATH79分支编译的固件，同样打开40Mhz，最好的只能跑到3.5MB/s，求解。

**Comment by coolsnowwolf** [comment]
对啊，4.9 内核更适合 ar71xx 啊

**Comment by PlumWolf** [comment]
> 
> 
> 对啊，4.9 内核更适合 ar71xx 啊

内核能影响这么大吗？没想到会比4.19的ath79慢这么多，不知道ath79用4.14编译能不能达到ar71xx 4.14的相同速度。

**Comment by PlumWolf** [comment]
> 
> 
> 对啊，4.9 内核更适合 ar71xx 啊

测试了一下，ar71xx和ath79同用4.14内核编译，AR71xx分支编译出来的依旧快得多。这是为啥啊……

**Comment by AmadeusGhost** [comment]
官方有个相关的kmod-owl-loader的更改，我忘了改，明天再改下发上来
