### ISSUE TITLE
最近一段时间数次更新，编译后的K2P固件，刷入丢无线配置，是否。。。？

### ISSUE THREAD

**Issue by mcucore** [coolsnowwolf/lede#2966]
如题，如涉及不可讨论就当没看到，谢谢！

**Comment by AmadeusGhost** [comment]
k2p比较特殊，用的是闭源驱动
![image](https://user-images.githubusercontent.com/42570690/73997544-c577ad00-4999-11ea-8ccb-726759476b75.png)

**Comment by mcucore** [comment]
用这2字合适吗？你应该说用了XX驱动，谢谢！~关键是也没看到换驱动啊，怎么配置就丢了

**Comment by mcucore** [comment]
现在编译的版本完全保存不了配置了，斐讯布局，是我固件太大?

**Comment by AmadeusGhost** [comment]
> 现在编译的版本完全保存不了配置了，斐讯布局，是我固件太大?

再刷一次sysupgrade.bin试试

**Comment by mcucore** [comment]
重刷还是不行，我已经刷回2月3日编译的版本

**Comment by AmadeusGhost** [comment]
> 重刷还是不行，我已经刷回2月3日编译的版本

不是重刷，是breed刷完固件后进备份/升级那刷sysupgrade.bin

**Comment by mcucore** [comment]
> > 重刷还是不行，我已经刷回2月3日编译的版本
> 
> 不是重刷，是breed刷完固件后进备份/升级那刷sysupgrade.bin

配置可以保存了，无线参数是否保存没测试，谢谢！
