### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#2973]
make[5]: Leaving directory '/home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169'
cmp -s /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/vmlinux /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/vmlinux.debug || { aarch64-openwrt-linux-musl-objcopy -O binary -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/vmlinux /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/vmlinux; aarch64-openwrt-linux-musl-objcopy -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/vmlinux /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/vmlinux.elf; cp -fpR /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/vmlinux /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/vmlinux.debug;  cp -fpR /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/arch/arm64/boot//Image /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/Image;  }
touch /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.14.169/.image
make -C image compile install TARGET_BUILD=
make[5]: Entering directory '/home/q/lede/target/linux/sunxi/image'
make[5]: Nothing to be done for 'compile'.
mkdir -p /home/q/lede/bin/targets/sunxi/cortexa53 /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp
/home/q/lede/staging_dir/host/bin/mksquashfs4 /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/root-sunxi /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/root.squashfs -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 256k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1
rm -f /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin
cp /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/Image /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/root.squashfs, block size 262144.
Pseudo file "/dev" exists in source filesystem "/home/q/lede/build_dir/target-aarch64_cortex-a53_musl/root-sunxi/dev".
Ignoring, exclude it (-e/-ef) to override.
[=============================================================\] 2851/2851 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 262144
	compressed data, compressed metadata, compressed fragments,
	no xattrs, compressed ids
	duplicates are removed
Filesystem size 65736.19 Kbytes (64.20 Mbytes)
	23.74% of uncompressed filesystem size (276892.66 Kbytes)
Inode table size 20802 bytes (20.31 Kbytes)
	23.21% of uncompressed inode table size (89632 bytes)
Directory table size 25048 bytes (24.46 Kbytes)
	43.18% of uncompressed directory table size (58003 bytes)
Number of duplicate files found 250
Number of inodes 2493
Number of files 1873
Number of fragments 80
Number of symbolic links  461
Number of device nodes 1
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 158
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
[ -f /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin -a -f /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/root.squashfs ]
rm -f /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot
mkfs.fat /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot -C 20480
mkfs.fat 4.1 (2017-01-24)
mcopy -i /home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot /home/q/lede/staging_dir/target-aarch64_cortex-a53_musl/image/sun50i-h5-nanopi-neo2-boot.scr ::boot.scr
/home/q/lede/staging_dir/target-aarch64_cortex-a53_musl/image/sun50i-h5-nanopi-neo2-boot.scr: No such file or directory
Makefile:46: recipe for target '/home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz' failed
make[5]: *** [/home/q/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz] Error 1
make[5]: Leaving directory '/home/q/lede/target/linux/sunxi/image'
Makefile:32: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/q/lede/target/linux/sunxi'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/q/lede/target/linux'
time: target/linux/install#796.44#92.91#292.62
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/q/lede'
target/Makefile:19: recipe for target '/home/q/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install' failed
make[1]: *** [/home/q/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/q/lede'
Build failed - please re-run with -j1 to see the real error message
/home/q/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 1
q@q-VirtualBox:~/lede$

**Comment by AmadeusGhost** [comment]
#2976 你试试
