### ISSUE TITLE
编译后5G无线可以开启，2.4G不能开启，机型斐讯k2

### ISSUE THREAD

**Issue by chxpgg** [coolsnowwolf/lede#2989]

**Comment by AmadeusGhost** [comment]
恢复出厂设置呢？k2这块没什么改动

**Comment by chxpgg** [comment]
恢复出厂也是一样的，我在恩山上面也下载过一个人近期编译的k2固件，下载下来也是5G能用，2.4G不能用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AmadeusGhost"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月8日(星期六) 中午11:36
收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送:&nbsp;"奋斗小青年、"<601620006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] 编译后5G无线可以开启，2.4G不能开启，机型斐讯k2 (#2989)




恢复出厂设置呢？k2这块没什么改动

**Comment by AmadeusGhost** [comment]
系统日志给下？

**Comment by chxpgg** [comment]
家里有设备不支持5g的，后来换成padavan了



---原始邮件---
发件人: "AmadeusGhost"<notifications@github.com&gt;
发送时间: 2020年2月8日(周六) 中午11:56
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送: "chxpgg"<601620006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [coolsnowwolf/lede] 编译后5G无线可以开启，2.4G不能开启，机型斐讯k2 (#2989)



系统日志给下？
