### ISSUE TITLE
默认配置 编译报错

### ISSUE THREAD

**Issue by PoiYuudachi** [coolsnowwolf/lede#2997]
rm -f /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin
cp /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/Image /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin
[ -f /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/sun50i-h5-nanopi-neo2-kernel.bin -a -f /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/root.squashfs ]
rm -f /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot
mkfs.fat /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot -C 20480
mkfs.fat 4.1 (2017-01-24)
mcopy -i /home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz.boot /home/poi/lede/staging_dir/target-aarch64_cortex-a53_musl/image/sun50i-h5-nanopi-neo2-boot.scr ::boot.scr
/home/poi/lede/staging_dir/target-aarch64_cortex-a53_musl/image/sun50i-h5-nanopi-neo2-boot.scr: No such file or directory
Makefile:46: recipe for target '/home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz' failed
make[5]: *** [/home/poi/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/tmp/openwrt-sunxi-cortexa53-sun50i-h5-nanopi-neo2-squashfs-sdcard.img.gz] Error 1
make[5]: Leaving directory '/home/poi/lede/target/linux/sunxi/image'
Makefile:32: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/poi/lede/target/linux/sunxi'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/poi/lede/target/linux'
time: target/linux/install#15.38#3.70#16.40
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/poi/lede'
target/Makefile:19: recipe for target '/home/poi/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install' failed
make[1]: *** [/home/poi/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/poi/lede'
/home/poi/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by hyird** [comment]
多线程编译的吧
