### ISSUE TITLE
大神，編譯X86，保存掛載點出錯

### ISSUE THREAD

**Issue by ctw8989** [coolsnowwolf/lede#3]
首先感謝大神的無私貢獻，用您的源碼編譯X86_64，當保存掛載點就會出現下面的信息：
/usr/lib/lua/luci/util.lua:623: Unable to establish ubus connection stack traceback: [C]: in function 'assert' /usr/lib/lua/luci/util.lua:623: in function 'ubus' /usr/lib/lua/luci/dispatcher.lua:172: in function 'session_retrieve' /usr/lib/lua/luci/dispatcher.lua:382: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:121: in function

官方的也一樣

**Comment by coolsnowwolf** [comment]
切换回到 官方 17.01.2 的 feeds 了，你可以再次 feed update 编译一次看看

**Comment by ctw8989** [comment]
大哥，刚试了下，还是不行，保存后还会出错
编译3800，4300这些都没问题
不会是和我用Ubuntu  16 编译有关吧

**Comment by coolsnowwolf** [comment]
亲测没有问题，14 LTS 编译.

LUA 依赖你的 local，请使用合适的版本编译

**Comment by ctw8989** [comment]
那就奇怪了，我又换了虚拟机，也按照你的方法建编译环境啦，死活都不行，出错后连WEB都进不了
提示如下：
/usr/lib/lua/luci/dispatcher.lua:478: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/util.lua:623: Unable to establish ubus connection
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:478: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

而且在adbyby页面点  重启adbyby   时，也提示：
Bad Gateway
The process did not produce any response

**Comment by ctw8989** [comment]
@coolsnowwolf  L大，我真是服了，无论如何试，也试过恩山上的所谓菜鸟包，还是一样。你看能不能把你的编译x86_64的 .config文件发我一份，估计是有什么包我没选上！拜托了。
ctw8989@gmail.com   谢谢！！

**Comment by ctw8989** [comment]
XX了，原来是我刷错固件了

**Comment by coolsnowwolf** [comment]
好吧~
