### ISSUE TITLE
请问用Mac可以编译吗？

### ISSUE THREAD

**Issue by McJayFeng** [coolsnowwolf/lede#3012]
我有一台Mac，请问可以编译吗？

**Comment by zhangbw2016** [comment]
我用过mac编译 总是在编译fullcontent的时候报错：*** No rule to make target 'tools/objtool/objtool'

**Comment by luckyyyyy** [comment]
mac编译比较麻烦 请参考openwrt官方手册
没有经验请勿尝试，并不是说跟着手册就可以没有问题。

https://openwrt.org/docs/guide-developer/buildroot.exigence.macosx

**Comment by qlmyang-boop** [comment]
我用的Mac 连接 Google VPS，编译超快。

**Comment by McJayFeng** [comment]
> 我用的Mac 连接 Google VPS，编译超快。

我在AWS编译了一下，编译了半天🤣

**Comment by 9l** [comment]
github action 多省心

**Comment by ch1993128** [comment]
mac也可以装ubuntu

**Comment by McJayFeng** [comment]
> mac编译比较麻烦 请参考openwrt官方手册
> 没有经验请勿尝试，并不是说跟着手册就可以没有问题。
> 
> https://openwrt.org/docs/guide-developer/buildroot.exigence.macosx

上次看了文档，几年前的文档了，感觉MacOS10.15不一定能用，昨天干脆装了个Ubuntu的虚拟机

**Comment by McJayFeng** [comment]
> mac也可以装ubuntu

哈哈哈是的，昨天装好了~

**Comment by zhaianan** [comment]
mac可以编译的

**Comment by zhaianan** [comment]
https://p3terx.com/archives/compiling-openwrt-with-macos.html可以参考这个

**Comment by McJayFeng** [comment]
> [https://p3terx.com/archives/compiling-openwrt-with-macos.html可以参考这个](https://p3terx.com/archives/compiling-openwrt-with-macos.html%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA)

嗯嗯，多谢多谢~ 上次看了 https://openwrt.org/docs/guide-developer/buildroot.exigence.macosx 这个文档，最近的更新也是16年了，所以感觉会失败，于是就直接装了个Ubuntu的虚拟机
