### ISSUE TITLE
luci配置端口转发不生效，点击保存&应用没有任何内容，配置文件中也没有相关配置

### ISSUE THREAD

**Issue by NanFour** [coolsnowwolf/lede#3017]
近日发现luci配置端口转发不生效，点击保存&应用界面没有任何内容，配置文件中也没有相关配置，系统日志中也没有相关错误信息，如上，感谢各位大佬的辛勤。

![QQ图片20200209213657](https://user-images.githubusercontent.com/32979064/74103129-7641a000-4b84-11ea-8ba5-ede823ddbffc.png)

**Comment by luckyyyyy** [comment]
ssh 进去 执行 ps 把内容发出来看一下

**Comment by NanFour** [comment]
> ssh 进去 执行 ps 把内容发出来看一下

![QQ截图20200209215649](https://user-images.githubusercontent.com/32979064/74103471-244e4980-4b87-11ea-8fc7-1e0a3f0c8299.png)
![QQ截图20200209215705](https://user-images.githubusercontent.com/32979064/74103474-2a442a80-4b87-11ea-9692-1e70545b407c.png)
如上。

**Comment by luckyyyyy** [comment]
哦 那和这个无关 我以为有和另外一个相同的问题

**Comment by NanFour** [comment]
> 哦 那和这个无关 我以为有和另外一个相同的问题

刚又发现luci添加静态路由后，/etc/config/network生成了相关配置文件，但ip route list 中并没有生成相关路由条目，shell下用ip route add添加条目后倒是可以生效。

**Comment by luckyyyyy** [comment]
> > 哦 那和这个无关 我以为有和另外一个相同的问题
> 
> 刚又发现luci添加静态路由后，/etc/config/network生成了相关配置文件，但ip route list 中并没有生成相关路由条目，shell下用ip route add添加条目后倒是可以生效。

因为在Lienol的固件 我发现有网易云restart导致的fw死锁，导致任何后续操作都不生效的问题，你这里我没看到。

**Comment by NanFour** [comment]
> > > 哦 那和这个无关 我以为有和另外一个相同的问题
> > 
> > 
> > 刚又发现luci添加静态路由后，/etc/config/network生成了相关配置文件，但ip route list 中并没有生成相关路由条目，shell下用ip route add添加条目后倒是可以生效。
> 
> 因为在Lienol的固件 我发现有网易云restart导致的fw死锁，导致任何后续操作都不生效的问题，你这里我没看到。

谢谢你的回复。

**Comment by coolsnowwolf** [comment]
点击 “添加”

**Comment by NanFour** [comment]
> 点击 “添加”

🤣见笑了，操作问题。
