### ISSUE TITLE
偶尔会出现这个 br-lan: received packet on eth0 with own address as source address 

### ISSUE THREAD

**Issue by owen-gu** [coolsnowwolf/lede#3018]
帮忙看一下， 谢谢，
偶尔会出现, 网络正常使用

![image](https://user-images.githubusercontent.com/52304619/74114784-19c39c80-4be7-11ea-9ab7-735e9b5b75e3.png)

**Comment by owen-gu** [comment]
![image](https://user-images.githubusercontent.com/52304619/74115198-e84bd080-4be8-11ea-9016-ffda90cf4f5a.png)

**Comment by CYaNu** [comment]
mac地址冲突 找环境中的mac冲突源 比如用容器或者虚拟机生成的虚拟口mac地址
