### ISSUE TITLE
路由后端PPTP客户端拔号619

### ISSUE THREAD

**Issue by okboy-cn** [coolsnowwolf/lede#302]
路由刷机后，后端PC机PPTP拔号提示619错误，加入kmod-ipt-nathelper-extra也无法解决问题。原版固件没此问题，求解决办法。

**Comment by zouyujia** [comment]
同样遇到问题

**Comment by LGA1150** [comment]
更新解决方法：
编译时选上 kmod-ipt-raw 内核模块
将以下命令复制到自定义防火墙规则中
`iptables -t raw -A PREROUTING -p tcp --dport 1723 -j CT --helper pptp`
