### ISSUE TITLE
编译出错麻烦帮看看

### ISSUE THREAD

**Issue by feizaibufei** [coolsnowwolf/lede#3028]
Building Go cmd/dist using /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/.go_bootstrap.
Building Go toolchain1 using /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/.go_bootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
touch /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/.built
rm -rf /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/openwrt
rm -f /home/openwrt/lede/staging_dir/hostpkg/bin/go
rm -f /home/openwrt/lede/staging_dir/hostpkg/bin/gofmt
rm -rf /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross
rm -rf /home/openwrt/lede/staging_dir/hostpkg/share/go-cross
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/share/go-cross
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/api /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/
ln -sf ../../share/go-cross/api /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
install -m0644 -p /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/VERSION /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
for file in AUTHORS CONTRIBUTING.md CONTRIBUTORS LICENSE PATENTS README README.md; do if [ -f /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/$file ]; then install -m0644 -p /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/$file /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/ ; fi ; done
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/bin
install -m0755 -p /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/bin/* /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/bin/
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/pkg/linux_amd64 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg/
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg/tool/linux_amd64
install -m0755 -p /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/pkg/tool/linux_amd64/* /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg/tool/linux_amd64/
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/share/go-cross
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/lib /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/
ln -sf ../../share/go-cross/lib /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/misc /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/
ln -sf ../../share/go-cross/misc /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/src /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/
ln -sf ../../share/go-cross/src /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/test /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/
ln -sf ../../share/go-cross/test /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/
find /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/src/ \! -type d -a \( -name '*.bat' -o -name '*.rc' \) -delete
if [ -d /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/pkg/include ]; then install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg ; install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/pkg ; cp -fpR /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/pkg/include /home/openwrt/lede/staging_dir/hostpkg/share/go-cross/pkg/ ; ln -sf ../../../share/go-cross/pkg/include /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg/ ; fi
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/bin
ln -sf ../lib/go-cross/bin/go /home/openwrt/lede/staging_dir/hostpkg/bin/go
ln -sf ../lib/go-cross/bin/gofmt /home/openwrt/lede/staging_dir/hostpkg/bin/gofmt
rm -rf /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/pkg/linux_amd64
install -d -m0755 /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/openwrt
install -m0755 ./files/go-gcc-helper /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/openwrt/
ln -sf go-gcc-helper /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/openwrt/gcc
ln -sf go-gcc-helper /home/openwrt/lede/staging_dir/hostpkg/lib/go-cross/openwrt/g++
mkdir -p /home/openwrt/lede/staging_dir/hostpkg/stamp
touch /home/openwrt/lede/build_dir/hostpkg/go-1.13.6/.built
touch /home/openwrt/lede/staging_dir/hostpkg/stamp/.golang_installed
make[3]: Leaving directory '/home/openwrt/lede/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#331.63#66.03#314.74
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:103: /home/openwrt/lede/staging_dir/target-aarch64_generic_glibc/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:218：world] 错误 2

**Comment by ch1993128** [comment]
基本所有的编译报错都是文件下载不完整，少数是包选重了，不大调lean的预制包不会报错
