### ISSUE TITLE
会加入Mellanox ConnectX2的万兆网卡驱动吗?

### ISSUE THREAD

**Issue by lqhorochi** [coolsnowwolf/lede#3030]
会加入Mellanox ConnectX2的万兆网卡驱动吗?价格很香,估计很多人已入手,但是没有驱动,无法识别,麻烦加入!!!
驱动下载地址:
https://cn.mellanox.com/products/adapter-ethernet-sw

**Comment by hxlls** [comment]
自己选择啊，
![image](https://user-images.githubusercontent.com/43886952/74175225-55ef0f80-4c70-11ea-9707-24145a0aaf9e.png)

**Comment by lqhorochi** [comment]
> 自己选择啊，
> ![image](https://user-images.githubusercontent.com/43886952/74175225-55ef0f80-4c70-11ea-9707-24145a0aaf9e.png)
> ![image](https://user-images.githubusercontent.com/43886952/74175311-8b93f880-4c70-11ea-979e-275e3ba62342.png)

好的,谢谢!~~
