### ISSUE TITLE
希望增加对cifs文件系统支持

### ISSUE THREAD

**Issue by xiaoqingfeng999** [coolsnowwolf/lede#3032]
目前默认不包含对CIFS文件系统支持，挂载Windows等CIFS协议网络文件协议资源时会失败，希望添加。

**Comment by AmadeusGhost** [comment]
编译前自己选上kmod-fs-cifs和luci-app-cifsd

**Comment by Aes64X** [comment]
> 目前默认不包含对CIFS文件系统支持，挂载Windows等CIFS协议网络文

默认未勾选但包含的组件请不要在这里提出，请自己动动手，作者也没空去维护默认列表，请自己关闭这个Issues，类似问题请到论坛提出。
