### ISSUE TITLE
NAT环回不生效

### ISSUE THREAD

**Issue by MarsGao** [coolsnowwolf/lede#3035]
防火墙→端口转发/etc/config/firewall中，NAT环回默认开启，但不生效。不知道是不是firewall写iptable时有问题。

**Comment by yangsongli** [comment]
某个插件导致的 你自己排查

**Comment by coolsnowwolf** [comment]
和 NET NS 内核选项有关，Docker 会自动选上这个

**Comment by BROBIRD** [comment]
@coolsnowwolf `CONFIG_KERNEL_NET_NS`这一项需要设置为`n`吗？

**Comment by trackycn** [comment]
我这边测试, 如果勾选 Docker, NAT 环回全部失效。

如果不勾选的话, 内外网相同端口的可以成功, 不相同的不行。

关闭 Flow Offloading 后, 一切正常

**Comment by helllkz** [comment]
@trackycn 我也是这个问题，但是关闭Flow offloading过后，过段时间还是会失效，然后就是再启用然后禁用

**Comment by trackycn** [comment]
> @trackycn 我也是这个问题，但是关闭Flow offloading过后，过段时间还是会失效，然后就是再启用然后禁用

我关了一切正常, 测试了六天了, 你如果关了还不行, 试试看在路由器里tcpdump抓包看看请求是在哪里断了。我之前打开 Flow offloading, 抓包发现不同端口下的 NAT 回环只有第一个 HTTP 请求有响应, 之后的都不回了。

**Comment by helllkz** [comment]
> > @trackycn 我也是这个问题，但是关闭Flow offloading过后，过段时间还是会失效，然后就是再启用然后禁用
> 
> 我关了一切正常, 测试了六天了, 你如果关了还不行, 试试看在路由器里tcpdump抓包看看请求是在哪里断了。我之前打开 Flow offloading, 抓包发现不同端口下的 NAT 回环只有第一个 HTTP 请求有响应, 之后的都不回了。

@trackycn 一样的，我看nginx的日志也只有一个访问，之后的都没了
