### ISSUE TITLE
使用docker编译

### ISSUE THREAD

**Issue by whlsxl** [coolsnowwolf/lede#3037]
写了个Dockerfile。
对于有服务器，尤其是海外服务器的小伙伴，自己编译还是很方便的。
感兴趣的朋友可以看下。
https://github.com/whlsxl/lede_docker

**Comment by jiushibushuo** [comment]
有CI以后意义不大了

**Comment by whlsxl** [comment]
> 有CI以后意义不大了

的确是，个人爱好吧。

**Comment by whlsxl** [comment]
不过说实话，用CI，还是有点浪费github的服务器资源。。。
