### ISSUE TITLE
编译K3固件成功，但miniDLNA 状态显示有问题！

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#304]
miniDLNA 状态
无论有没有挂载，永远是：正在收集数据。
如果挂载移动硬盘，miniDLNA是工作的。

**Comment by shenzt68** [comment]
![image](https://user-images.githubusercontent.com/17406910/36151832-d0f43318-1103-11e8-9b41-2ce791a2a918.png)
难道就是我一个人遇到这个问题？
此问题虽然不影响使用，但之于有强迫症的人有的受不了！

**Comment by fuqiang03** [comment]
不是你一个人的问题哦、
我也遇到过 不过我在控制页面 加入了 默认禁止启动 就好了

**Comment by shenzt68** [comment]
怎么默认禁止启动？

**Comment by fuqiang03** [comment]
首次开机 后 启用按钮已经选上 但是 服务并没有运行 可以添加 默认禁止启动

**Comment by fuqiang03** [comment]
![tim 20180218214457](https://user-images.githubusercontent.com/26851715/36352504-f23e85bc-14b1-11e8-84c5-12b57b758d46.png)
