### ISSUE TITLE
无法挂载移动硬盘

### ISSUE THREAD

**Issue by kongzheng333** [coolsnowwolf/lede#3042]
![image](https://user-images.githubusercontent.com/58472000/74246549-a96c6680-4d1f-11ea-8836-a1f780591a36.png)
如图 虽然挂载点中可以看到设备但是无法成功挂载 固件是二月九日action自动编译的X86版本 移动硬盘文件系统是ntfs 下面是日志文件内容

Tue Feb 11 22:35:49 2020 daemon.err block: No "mount.ntfs" utility available
Tue Feb 11 22:35:49 2020 daemon.err block: mounting /dev/sdb1 (ntfs) as /mnt/sdb1 failed (2) - No such file or directory

**Comment by coolsnowwolf** [comment]
新的 nfts 内核驱动问题，我修复下
