### ISSUE TITLE
编译报错的过来看下

### ISSUE THREAD

**Issue by ch1993128** [coolsnowwolf/lede#3046]
make menuconfig以后

搭好稳定的梯子，国外ip全部走梯子
搭好稳定的梯子，国外ip全部走梯子
搭好稳定的梯子，国外ip全部走梯子
搭好稳定的梯子，国外ip全部走梯子
搭好稳定的梯子，国外ip全部走梯子

多次make download -j4 V=s
直到显示完全下载完毕

不动预制包，基本报错都是文件不完整

**Comment by ch1993128** [comment]
最近大雕还加入国内下载源了，已经做的很多了

**Comment by qiming-kooboo** [comment]
国外 VPS 上编译报错的飘过～
