### ISSUE TITLE
samba4 配置无法保存

### ISSUE THREAD

**Issue by chongnaxiao** [coolsnowwolf/lede#305]
luci-app-samba4 安装后，在添加共享中设置，可写/只读 无效，保存后没有写入配置文件。

**Comment by d975xbx** [comment]
我是samba4选中编译过不去，去掉就能过。

**Comment by clistant** [comment]
我也是编译报错。无论选中samba还是samba4都报错。这两个貌似是同一个啊。

**Comment by chongnaxiao** [comment]
我samba4可以编译成功，Ubuntu 16.04.3, 4G内存，也可以运行，实测读和写的速度都比samba3.6高10%到20%。只是管理界面有问题，添加共享后无法配置成只读，保存后没有写入配置文件。而3.6没有这个问题。
