### ISSUE TITLE
antfs-mount .ntfs-3g 冲突

### ISSUE THREAD

**Issue by EstFoxs** [coolsnowwolf/lede#3052]
* check_data_file_clashes: Package ntfs-3g wants to install file /home/bbq/lede/build_dir/target-x86_64_musl/root-x86/sbin/mount.ntfs
        But that file is already provided by package  * antfs-mount
 * opkg_install_cmd: Cannot install package ntfs-3g.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/bbq/lede'
make[1]: *** [package/Makefile:104: /home/bbq/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/bbq/lede'
make: *** [/home/bbq/lede/include/toplevel.mk:218: world] Error 2
bbq@bbq:~/lede$
取消其中一个 比如ntfs-3g 可通过编译

**Comment by jxph1123** [comment]
取消ntfs-3g
