### ISSUE TITLE
有没有人编译 4.19.101 内核的，遇到系统不稳定的？

### ISSUE THREAD

**Issue by tty228** [coolsnowwolf/lede#3062]
设备是斐讯 K3 ，内核版本号为 4.19.101

表现为时不时的重启，时间从刚刚重启结束几分钟到运行了 4~5 小时
偶尔会在 /tmp 目录下生成部分 *.core 文件（有一次刷完固件没插网线，adbyby 生成的 *.core 文件挤爆了内存，然后系统就卡死了）
试了两天看到有 adbyby  、UnblockNeteaseMusic 生成过这种文件
但不是每次重启都会这样，很多时候毫无预兆就重启了

试过卸载或关闭 adbyby 、UnblockNeteaseMusic、 SSR等插件，问题依旧
现在回滚到了 4.19.98 ，4.19.101 之前的最后一个版本，运行了2个小时，不知道还会不会重启
（玄学感觉比之前好了一点，之前基本刷完固件就重启个一两次）
（https://github.com/coolsnowwolf/lede/pull/2940）

**Comment by kawon7317** [comment]
树莓派4表示很稳

**Comment by tty228** [comment]
> 树莓派4表示很稳

那我再找找原因

**Comment by dovegq** [comment]
x86很稳

**Comment by tty228** [comment]
问题找到了，我编译一个插件的时候，自动选中附带的内核文件
取消插件的编译并不会自动取消内核的编译
所以才会卸载重编译都无效

**Comment by KFERMercer** [comment]
依赖树污染:smile:
