### ISSUE TITLE
SSR PLUS增加sock5透明代理的可行性？

### ISSUE THREAD

**Issue by MeIsReallyBa** [coolsnowwolf/lede#3063]
最近发现一个基于大雕的修改的 https://github.com/xsm1997/luci-app-ssr-plus。
不同在于用了一个类似本仓库已有的ipt2socks，将sock5转成了iptables流量，实现了透明代理。用这个的意义在于树莓派啥的arm设备跑酸酸 V2+开sock5 server，可以降低非arm主路由的压力。
本人测试N1跑V2，7621做透明代理，至少是单线程60M，多线程200M的水平。

**Comment by coolsnowwolf** [comment]
v2 自己就有这个功能，不需要再加一个进程了
