### ISSUE TITLE
是编译iptables-1.8.2报错吗

### ISSUE THREAD

**Issue by feizaibufei** [coolsnowwolf/lede#3069]
L= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-conntrack-extra/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-conntrack-extra_installed
echo "iptables-mod-conntrack-extra" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-extra/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-extra_installed
echo "iptables-mod-extra" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-ipopt/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-ipopt_installed
echo "iptables-mod-ipopt" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-ipsec/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-ipsec_installed
echo "iptables-mod-ipsec" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-nat-extra/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-nat-extra_installed
echo "iptables-mod-nat-extra" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/iptables-mod-tproxy/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.iptables-mod-tproxy_installed
echo "iptables-mod-tproxy" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/ip6tables/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.ip6tables_installed
echo "ip6tables" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
echo '1.8.2' | cmp -s - /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libip4tc.version || echo '1.8.2' > /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libip4tc.version
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/libip4tc/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.libip4tc_installed
echo "libip4tc" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
echo '1.8.2' | cmp -s - /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libip6tc.version || echo '1.8.2' > /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libip6tc.version
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/libip6tc/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.libip6tc_installed
echo "libip6tc" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
mkdir -p /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp
echo '1.8.2' | cmp -s - /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libxtables.version || echo '1.8.2' > /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libxtables.version
SHELL= flock /home/openwrt/lede/tmp/.root-copy.flock -c 'cp -fpR /home/openwrt/lede/build_dir/target-aarch64_generic_musl/linux-armvirt_64/iptables-1.8.2/.pkgdir/libxtables/. /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/'
touch /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/root-armvirt/stamp/.libxtables_installed
echo "libxtables" >> /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/pkginfo/iptables.default.install
make[3]: Leaving directory '/home/openwrt/lede/package/network/utils/iptables'
time: package/network/utils/iptables/compile#29.88#9.43#38.71
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:103: /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:218：world] 错误 2

**Comment by coolsnowwolf** [comment]
make clean
