### ISSUE TITLE
最新版本antfs下载失败

### ISSUE THREAD

**Issue by helllkz** [coolsnowwolf/lede#3070]
更新到最新版本，修复antfs和ntfs-3g冲突那个bug的吧，现在找不到这个下载文件，404，浏览器打开这2个服务器，就没有antfs这个源文件的

+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/antfs-2020-02-10-b41ba529.tar.xz
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/antfs-2020-02-10-b41ba529.tar.xz
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.

**Comment by coolsnowwolf** [comment]
你被墙了

**Comment by sky123456789sky** [comment]
我也没有 源文件里也是看不到这个文件

**Comment by tty228** [comment]
解压，放到 DL 文件夹
[antfs.zip](https://github.com/coolsnowwolf/lede/files/4202351/antfs.zip)

**Comment by ihuaer** [comment]
> 解压，放到 DL 文件夹
> [antfs.zip](https://github.com/coolsnowwolf/lede/files/4202351/antfs.zip)

多谢老哥，我编译试试
