### ISSUE TITLE
动态dns不能正常运行，已经安装了bind-host

### ISSUE THREAD

**Issue by zzsx644** [coolsnowwolf/lede#3077]
Error relocating /usr/bin/host: isc_socket_attach: symbol not found
Error relocating /usr/bin/host: dns_log_init: symbol not found
Error relocating /usr/bin/host: dns_rdata_freestruct: symbol not found
Error relocating /usr/bin/host: isc_buffer_free: symbol not found
Error relocating /usr/bin/host: isc_task_create: symbol not found
Error relocating /usr/bin/host: isc_socket_ipv6only: symbol not found
Error relocating /usr/bin/host: dst_lib_init: symbol not found
Error relocating /usr/bin/host: cfg_obj_asstring: symbol not found
Error relocating /usr/bin/host: dns_fixedname_initname: symbol not found
Error relocating /usr/bin/host: dns_rdataset_current: symbol not found
Error relocating /usr/bin/host: dns_compress_init: symbol not found
Error relocating /usr/bin/host: isc_app_block: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_fromin6: symbol not found
Error relocating /usr/bin/host: isc_nonce_buf: symbol not found
Error relocating /usr/bin/host: dns_message_peekheader: symbol not found
Error relocating /usr/bin/host: isc_netaddr_totext: symbol not found
Error relocating /usr/bin/host: dns_rdata_tostruct: symbol not found
Error relocating /usr/bin/host: isc_result_totext: symbol not found
Error relocating /usr/bin/host: dns_rdataset_makequestion: symbol not found
Error relocating /usr/bin/host: dns_rdataclass_format: symbol not found
Error relocating /usr/bin/host: dns_name_copy: symbol not found
Error relocating /usr/bin/host: irs_resconf_getndots: symbol not found
Error relocating /usr/bin/host: dns_message_buildopt: symbol not found
Error relocating /usr/bin/host: cfg_parse_file: symbol not found
Error relocating /usr/bin/host: isc_timer_touch: symbol not found
Error relocating /usr/bin/host: dns_fixedname_name: symbol not found
Error relocating /usr/bin/host: dns_tsigkey_createfromkey: symbol not found
Error relocating /usr/bin/host: isc_netaddr_format: symbol not found
Error relocating /usr/bin/host: dns_message_findname: symbol not found
Error relocating /usr/bin/host: isc_commandline_reset: symbol not found
Error relocating /usr/bin/host: isc__mempool_get: symbol not found
Error relocating /usr/bin/host: isc_mempool_create: symbol not found
Error relocating /usr/bin/host: cfg_map_getname: symbol not found
Error relocating /usr/bin/host: isc_task_detach: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_pf: symbol not found
Error relocating /usr/bin/host: isc_taskmgr_create: symbol not found
Error relocating /usr/bin/host: isc_socket_connect: symbol not found
Error relocating /usr/bin/host: dns_message_setopt: symbol not found
Error relocating /usr/bin/host: isc_event_allocate: symbol not found
Error relocating /usr/bin/host: dns_rdataset_first: symbol not found
Error relocating /usr/bin/host: bind9_getaddresses: symbol not found
 230746  WARN : Get registered/public IP for 'openwrt.zzsx644.xyz' failed - retry 5/0 in 60 seconds
 230847       : #> /usr/bin/host -t A openwrt.zzsx644.xyz  >/var/run/ddns/namecheap.dat 2>/var/run/ddns/namecheap.err
 230847 ERROR : BIND host error: '127'
 230847       : Error loading shared library libdns.so.1311: No such file or directory (needed by /usr/bin/host)
Error loading shared library libirs.so.1301: No such file or directory (needed by /usr/bin/host)
Error loading shared library libbind9.so.1302: No such file or directory (needed by /usr/bin/host)
Error loading shared library libisccfg.so.1302: No such file or directory (needed by /usr/bin/host)
Error loading shared library libisc.so.1310: No such file or directory (needed by /usr/bin/host)
Error relocating /usr/bin/host: dns_message_create: symbol not found
Error relocating /usr/bin/host: dst_key_setbits: symbol not found
Error relocating /usr/bin/host: isc_event_free: symbol not found
Error relocating /usr/bin/host: dns_message_settsigkey: symbol not found
Error relocating /usr/bin/host: isc_socket_detach: symbol not found
Error relocating /usr/bin/host: dns_message_destroy: symbol not found
Error relocating /usr/bin/host: isc_app_finish: symbol not found
Error relocating /usr/bin/host: dns_tsigkey_create: symbol not found
Error relocating /usr/bin/host: dns_tsig_verify: symbol not found
Error relocating /usr/bin/host: isc_task_send: symbol not found
Error relocating /usr/bin/host: dns_name_invalidate: symbol not found
Error relocating /usr/bin/host: isc_commandline_index: symbol not found
Error relocating /usr/bin/host: dns_name_format: symbol not found
Error relocating /usr/bin/host: isc_hex_totext: symbol not found
Error relocating /usr/bin/host: dst_lib_destroy: symbol not found
Error relocating /usr/bin/host: dns_message_nextname: symbol not found
Error relocating /usr/bin/host: isc_buffer_getuint16: symbol not found
Error relocating /usr/bin/host: dns_rdata_init: symbol not found
Error relocating /usr/bin/host: isc_net_disableipv6: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_format: symbol not found
Error relocating /usr/bin/host: isc_mem_stats: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_getport: symbol not found
Error relocating /usr/bin/host: cfg_parser_create: symbol not found
Error relocating /usr/bin/host: isc_time_now: symbol not found
Error relocating /usr/bin/host: isc_app_shutdown: symbol not found
Error relocating /usr/bin/host: isc_log_destroy: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_any: symbol not found
Error relocating /usr/bin/host: isc_timermgr_destroy: symbol not found
Error relocating /usr/bin/host: dns_fixedname_init: symbol not found
Error relocating /usr/bin/host: dns_message_gettemprdata: symbol not found
Error relocating /usr/bin/host: dns_rdataset_next: symbol not found
Error relocating /usr/bin/host: isc_socketmgr_create: symbol not found
Error relocating /usr/bin/host: irs_resconf_destroy: symbol not found
Error relocating /usr/bin/host: dns_name_countlabels: symbol not found
Error relocating /usr/bin/host: isc_buffer_reserve: symbol not found
Error relocating /usr/bin/host: isc_timermgr_create: symbol not found
Error relocating /usr/bin/host: cfg_map_get: symbol not found
Error relocating /usr/bin/host: isc_socket_sendto2: symbol not found
Error relocating /usr/bin/host: isc_file_exists: symbol not found
Error relocating /usr/bin/host: irs_resconf_getsearchlist: symbol not found
Error relocating /usr/bin/host: isc_socket_socketevent: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacsha256_name: symbol not found
Error relocating /usr/bin/host: dns_name_destroy: symbol not found
Error relocating /usr/bin/host: dns_rdata_fromstruct: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_fromin: symbol not found
Error relocating /usr/bin/host: dns_rdatalist_tordataset: symbol not found
Error relocating /usr/bin/host: dns_message_gettempname: symbol not found
Error relocating /usr/bin/host: isc_time_microdiff: symbol not found
Error relocating /usr/bin/host: isc__mem_free: symbol not found
Error relocating /usr/bin/host: isc_socket_send: symbol not found
Error relocating /usr/bin/host: isc_random_uniform: symbol not found
Error relocating /usr/bin/host: isc_parse_uint32: symbol not found
Error relocating /usr/bin/host: isc_buffer_allocate: symbol not found
Error relocating /usr/bin/host: dns_message_gettemprdatalist: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_compare: symbol not found
Error relocating /usr/bin/host: isc_time_seconds: symbol not found
Error relocating /usr/bin/host: isc_mem_setname: symbol not found
Error relocating /usr/bin/host: dns_name_copynf: symbol not found
Error relocating /usr/bin/host: isc_net_probeipv4: symbol not found
Error relocating /usr/bin/host: dns_log_setcontext: symbol not found
Error relocating /usr/bin/host: dns_name_isabsolute: symbol not found
Error relocating /usr/bin/host: dst_key_free: symbol not found
Error relocating /usr/bin/host: dns_message_getquerytsig: symbol not found
Error relocating /usr/bin/host: isc_socket_create: symbol not found
Error relocating /usr/bin/host: dns_message_rendersection: symbol not found
Error relocating /usr/bin/host: isc_socket_cancel: symbol not found
Error relocating /usr/bin/host: isc__mempool_put: symbol not found
Error relocating /usr/bin/host: isc_mempool_setfillcount: symbol not found
Error relocating /usr/bin/host: dns_rootname: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacsha512_name: symbol not found
Error relocating /usr/bin/host: cfg_parser_destroy: symbol not found
Error relocating /usr/bin/host: isc_socket_dscp: symbol not found
Error relocating /usr/bin/host: isc_buffer_copyregion: symbol not found
Error relocating /usr/bin/host: isc_error_runtimecheck: symbol not found
Error relocating /usr/bin/host: isc_mempool_setfreemax: symbol not found
Error relocating /usr/bin/host: dns_message_firstname: symbol not found
Error relocating /usr/bin/host: dns_message_gettsig: symbol not found
Error relocating /usr/bin/host: dns_message_addname: symbol not found
Error relocating /usr/bin/host: isc_log_setcontext: symbol not found
Error relocating /usr/bin/host: isc_hex_decodestring: symbol not found
Error relocating /usr/bin/host: isc_taskmgr_destroy: symbol not found
Error relocating /usr/bin/host: dns_tsigkey_detach: symbol not found
Error relocating /usr/bin/host: isc_serial_ge: symbol not found
Error relocating /usr/bin/host: dns_rdatatype_format: symbol not found
Error relocating /usr/bin/host: dns_rdatatype_fromtext: symbol not found
Error relocating /usr/bin/host: isc_interval_set: symbol not found
Error relocating /usr/bin/host: irs_resconf_getnameservers: symbol not found
Error relocating /usr/bin/host: isc_app_onrun: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacsha1_name: symbol not found
Error relocating /usr/bin/host: isc_app_start: symbol not found
Error relocating /usr/bin/host: dns_message_getopt: symbol not found
Error relocating /usr/bin/host: isc_time_nanoseconds: symbol not found
Error relocating /usr/bin/host: dns_message_renderend: symbol not found
Error relocating /usr/bin/host: dns_message_currentname: symbol not found
Error relocating /usr/bin/host: isc_socket_bind: symbol not found
Error relocating /usr/bin/host: dns_name_fromstring2: symbol not found
Error relocating /usr/bin/host: isc_log_create: symbol not found
Error relocating /usr/bin/host: dns_message_setquerytsig: symbol not found
Error relocating /usr/bin/host: isc_base64_decodestring: symbol not found
Error relocating /usr/bin/host: isc_commandline_argument: symbol not found
Error relocating /usr/bin/host: dns_message_findtype: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_ismulticast: symbol not found
Error relocating /usr/bin/host: dns_name_equal: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacsha224_name: symbol not found
Error relocating /usr/bin/host: isc_timer_reset: symbol not found
Error relocating /usr/bin/host: dst_key_alg: symbol not found
Error relocating /usr/bin/host: dns_name_clone: symbol not found
Error relocating /usr/bin/host: isc_assertion_failed: symbol not found
Error relocating /usr/bin/host: isc_timer_detach: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_anyofpf: symbol not found
Error relocating /usr/bin/host: isc_netaddr_fromsockaddr: symbol not found
Error relocating /usr/bin/host: dns_rdataclass_fromtext: symbol not found
Error relocating /usr/bin/host: isc__mutex_init: symbol not found
Error relocating /usr/bin/host: dns_rdatalist_init: symbol not found
Error relocating /usr/bin/host: dst_key_name: symbol not found
Error relocating /usr/bin/host: isc_task_setname: symbol not found
Error relocating /usr/bin/host: isc_socket_recv: symbol not found
Error relocating /usr/bin/host: isc_mempool_destroy: symbol not found
Error relocating /usr/bin/host: isc_net_disableipv4: symbol not found
Error relocating /usr/bin/host: dns_message_renderbegin: symbol not found
Error relocating /usr/bin/host: dns_name_init: symbol not found
Error relocating /usr/bin/host: cfg_obj_destroy: symbol not found
Error relocating /usr/bin/host: isc_app_isrunning: symbol not found
Error relocating /usr/bin/host: dns_rdata_totext: symbol not found
Error relocating /usr/bin/host: cfg_type_sessionkey: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacsha384_name: symbol not found
Error relocating /usr/bin/host: isc_log_usechannel: symbol not found
Error relocating /usr/bin/host: isc_mem_debugging: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_any6: symbol not found
Error relocating /usr/bin/host: dns_rdataset_totext: symbol not found
Error relocating /usr/bin/host: isc_app_unblock: symbol not found
Error relocating /usr/bin/host: dns_message_parse: symbol not found
Error relocating /usr/bin/host: dns_byaddr_createptrname: symbol not found
Error relocating /usr/bin/host: dns_compress_invalidate: symbol not found
Error relocating /usr/bin/host: dns_result_register: symbol not found
Error relocating /usr/bin/host: dns_tsig_hmacmd5_name: symbol not found
Error relocating /usr/bin/host: isc_mem_create: symbol not found
Error relocating /usr/bin/host: dns_name_concatenate: symbol not found
Error relocating /usr/bin/host: dns_message_puttempname: symbol not found
Error relocating /usr/bin/host: dst_key_fromnamedfile: symbol not found
Error relocating /usr/bin/host: isc_timer_create: symbol not found
Error relocating /usr/bin/host: isc_log_setdebuglevel: symbol not found
Error relocating /usr/bin/host: dns_rdata_reset: symbol not found
Error relocating /usr/bin/host: isc_mem_destroy: symbol not found
Error relocating /usr/bin/host: dns_name_fromtext: symbol not found
Error relocating /usr/bin/host: isc_app_run: symbol not found
Error relocating /usr/bin/host: dst_context_destroy: symbol not found
Error relocating /usr/bin/host: isc_random16: symbol not found
Error relocating /usr/bin/host: dns_message_setpadding: symbol not found
Error relocating /usr/bin/host: dns_message_gettemprdataset: symbol not found
Error relocating /usr/bin/host: isc_commandline_parse: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_eqaddr: symbol not found
Error relocating /usr/bin/host: isc_net_probeipv6: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_equal: symbol not found
Error relocating /usr/bin/host: isc__mem_allocate: symbol not found
Error relocating /usr/bin/host: dns_name_fullcompare: symbol not found
Error relocating /usr/bin/host: isc_mempool_setname: symbol not found
Error relocating /usr/bin/host: isc_socketmgr_destroy: symbol not found
Error relocating /usr/bin/host: irs_resconf_load: symbol not found
Error relocating /usr/bin/host: isc_socket_attach: symbol not found
Error relocating /usr/bin/host: dns_log_init: symbol not found
Error relocating /usr/bin/host: dns_rdata_freestruct: symbol not found
Error relocating /usr/bin/host: isc_buffer_free: symbol not found
Error relocating /usr/bin/host: isc_task_create: symbol not found
Error relocating /usr/bin/host: isc_socket_ipv6only: symbol not found
Error relocating /usr/bin/host: dst_lib_init: symbol not found
Error relocating /usr/bin/host: cfg_obj_asstring: symbol not found
Error relocating /usr/bin/host: dns_fixedname_initname: symbol not found
Error relocating /usr/bin/host: dns_rdataset_current: symbol not found
Error relocating /usr/bin/host: dns_compress_init: symbol not found
Error relocating /usr/bin/host: isc_app_block: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_fromin6: symbol not found
Error relocating /usr/bin/host: isc_nonce_buf: symbol not found
Error relocating /usr/bin/host: dns_message_peekheader: symbol not found
Error relocating /usr/bin/host: isc_netaddr_totext: symbol not found
Error relocating /usr/bin/host: dns_rdata_tostruct: symbol not found
Error relocating /usr/bin/host: isc_result_totext: symbol not found
Error relocating /usr/bin/host: dns_rdataset_makequestion: symbol not found
Error relocating /usr/bin/host: dns_rdataclass_format: symbol not found
Error relocating /usr/bin/host: dns_name_copy: symbol not found
Error relocating /usr/bin/host: irs_resconf_getndots: symbol not found
Error relocating /usr/bin/host: dns_message_buildopt: symbol not found
Error relocating /usr/bin/host: cfg_parse_file: symbol not found
Error relocating /usr/bin/host: isc_timer_touch: symbol not found
Error relocating /usr/bin/host: dns_fixedname_name: symbol not found
Error relocating /usr/bin/host: dns_tsigkey_createfromkey: symbol not found
Error relocating /usr/bin/host: isc_netaddr_format: symbol not found
Error relocating /usr/bin/host: dns_message_findname: symbol not found
Error relocating /usr/bin/host: isc_commandline_reset: symbol not found
Error relocating /usr/bin/host: isc__mempool_get: symbol not found
Error relocating /usr/bin/host: isc_mempool_create: symbol not found
Error relocating /usr/bin/host: cfg_map_getname: symbol not found
Error relocating /usr/bin/host: isc_task_detach: symbol not found
Error relocating /usr/bin/host: isc_sockaddr_pf: symbol not found
Error relocating /usr/bin/host: isc_taskmgr_create: symbol not found
Error relocating /usr/bin/host: isc_socket_connect: symbol not found
Error relocating /usr/bin/host: dns_message_setopt: symbol not found
Error relocating /usr/bin/host: isc_event_allocate: symbol not found
Error relocating /usr/bin/host: dns_rdataset_first: symbol not found
Error relocating /usr/bin/host: bind9_getaddresses: symbol not found
 230925  WARN : Get registered/public IP for 'openwrt.zzsx644.xyz' failed - retry 6/0 in 60 seconds

**Comment by coolsnowwolf** [comment]
编译时加入 bind （其实没必要

**Comment by zzsx644** [comment]
> 编译时加入 bind （其实没必要

感谢，虽然我还是不太明白
