### ISSUE TITLE
transmission web端假死

### ISSUE THREAD

**Issue by BlacK201** [coolsnowwolf/lede#3081]
transmission的web端在开始下载后一段时间就会无法刷新，也没法重新加载，只能重新打开transmission，在web端卡死的时候，transmission-daemon进程CPU占用一直是25%。
是因为我直接下载到外置NTFS硬盘的关系吗？有没有熟悉的老哥说一说怎么回事

**Comment by coolsnowwolf** [comment]
和 NTFS 有关，新的 NTFS 驱动对内存需求很大

**Comment by BlacK201** [comment]
> 和 NTFS 有关，新的 NTFS 驱动对内存需求很大

旧版的是那个ntfs3g么？新的驱动比起旧的有什么优势呢？如果我换回旧的驱动能不能改善这种情况
