### ISSUE TITLE
最新代码编译树莓派3B成功，烧录系统后，启动不了，界面在彩色屏

### ISSUE THREAD

**Issue by guoxf** [coolsnowwolf/lede#3085]

**Comment by hyird** [comment]
有屏幕的驱动么

**Comment by Guwalgiyakuan** [comment]
我是刚编译好新源码，树莓派连接电脑 192.168.1.1 打不开。ssh 也上不去。

**Comment by hcym** [comment]
应该没问题，n1可以

**Comment by kawon7317** [comment]
编译的是64位的吧，手动修改boot分区里面的config文件，添加一行arm_64bit=1即可

**Comment by Guwalgiyakuan** [comment]
> 我是刚编译好新源码，树莓派连接电脑 192.168.1.1 打不开。ssh 也上不去。

LuCI Master (git-20.045.63360-69eac90) / OpenWrt R20.1.24 
最新编译的已经修复不能登录 192.168.1.1 的问题了

**Comment by guoxf** [comment]
> 编译的是64位的吧，手动修改boot分区里面的config文件，添加一行arm_64bit=1即可

选了32位的

**Comment by guoxf** [comment]
> 有屏幕的驱动么

没有任何输出

**Comment by AmadeusGhost** [comment]
现在的代码可以启动吗？格式化一遍sd卡再刷入试试。

**Comment by blizzardster** [comment]
> > 有屏幕的驱动么
> 
> 没有任何输出

我也遇到了，请问你解决了吗
