### ISSUE TITLE
新版Docker(docker manager)pull error及解决方法

### ISSUE THREAD

**Issue by R3pl4c3r** [coolsnowwolf/lede#3088]
新版docker在docker pull时
![Snipaste_2020-02-14_20-52-16](https://user-images.githubusercontent.com/30682790/74533698-1c1e5180-4f6d-11ea-9b92-52d4e02210b8.png)
虽然显示pull成功，但是找不到images。
![Snipaste_2020-02-14_20-52-35](https://user-images.githubusercontent.com/30682790/74533669-0ad54500-4f6d-11ea-8aab-406db3973ce4.png)
在命令行pull之后发现
![Snipaste_2020-02-14_20-54-14](https://user-images.githubusercontent.com/30682790/74533991-cf874600-4f6d-11ea-80cf-afb95f319307.png)
是没有文件夹，创建文件夹并pull后
![Snipaste_2020-02-14_20-55-39](https://user-images.githubusercontent.com/30682790/74534054-e7f76080-4f6d-11ea-98c6-7aebdf0913f9.png)
可以pull成功，但仍存在一个问题，就是在docker run时，会显示
`docker: Error response from daemon: failed to update store for object type *libnetwork.endpointCnt: Key not found in store.`

**Comment by R3pl4c3r** [comment]
此时输入
`rm -rf /var/lib/docker`
再重启docker，开启container即可解决问题

**Comment by bdhjiajia** [comment]
谢谢分享

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolsnowwolf** [comment]
mark

**Comment by KFERMercer** [comment]
👍

**Comment by RealKiro** [comment]
![image](https://user-images.githubusercontent.com/33367701/74719362-d6180500-526e-11ea-9c61-125e96adcab6.png)

我的luci界面不正常，重编译升级还是一样，该怎么办？

**Comment by RealKiro** [comment]
![image](https://user-images.githubusercontent.com/33367701/74719362-d6180500-526e-11ea-9c61-125e96adcab6.png)

我的luci界面不正常，重编译升级还是一样，该怎么办？

**Comment by R3pl4c3r** [comment]
@coolsnowwolf 其实原来要是装过docker并挂载过/opt，其实可以新装之后先挂载原有的/opt，之后直接在启动项重启docker就恢复正常了，没必要执行上面的那些步骤
The issue was closed due to solution.
