### ISSUE TITLE
最新编译的ShadowSocksR Plus+ 使用V2RAY无法启动，log一直自动显示 Started！

### ISSUE THREAD

**Issue by Roger0822** [coolsnowwolf/lede#3093]
![image](https://user-images.githubusercontent.com/10806888/74561003-be0c6100-4fa2-11ea-89c7-284e674cb09a.png)
![image](https://user-images.githubusercontent.com/10806888/74561025-c95f8c80-4fa2-11ea-86bc-fad44bc30b34.png)

日志自动跳Started！

**Comment by d975xbx** [comment]
一样，
https://github.com/coolsnowwolf/lede/issues/3083

**Comment by coolsnowwolf** [comment]
v2ray 执行失败了，看看自己的 cpu 架构

**Comment by d975xbx** [comment]
源码已经更新，问题解决
