### ISSUE TITLE
adbyby规则更新地址已更改

### ISSUE THREAD

**Issue by RodmanWang** [coolsnowwolf/lede#3095]
原地址已经无法更新了，导致视频规则仍然是19.12.22，实际已更新，新的地址如下:
https://adbyby.coding.net/p/xwhyc-rules/d/xwhyc-rules/git/raw/master/lazy.txt
https://adbyby.coding.net/p/xwhyc-rules/d/xwhyc-rules/git/raw/master/video.txt

麻烦大佬固件源码更新下，我手动替换地址，不知道为啥重启就不行了

**Comment by coolsnowwolf** [comment]
最好发个 PR

**Comment by RodmanWang** [comment]
我不太会github，看不懂啥意思，这个两个地址是官方群2月2日更新的
![QQ截图20200215210038](https://user-images.githubusercontent.com/19368219/74588365-eba2ea00-5036-11ea-867e-ff391e450638.png)

**Comment by azazjjyjjy** [comment]
现在这个地址点进去还是19.12.22的，所以这个是最新的
