### ISSUE TITLE
"自动更新服务器订阅"功能的BUG

### ISSUE THREAD

**Issue by Bintel** [coolsnowwolf/lede#3096]
"服务器节点故障自动切换"已关闭.
当订阅节点数量有改变时, 将会导致:

1. 主服务器会自动换成其他服务器(即不会记忆更新订阅前所使用的的服务器)
2. 新增的节点将会显示在节点列表的末尾而不是按照订阅顺序重新排序

望修复, 谢谢!

**Comment by tone88** [comment]
遇到了同样的情况！

**Comment by coolsnowwolf** [comment]
这个是因为节点的 hash 改变了，为了继续能服务，会从新列表中选择一个可用的服务器作为节点

**Comment by tone88** [comment]
以前好像没遇到过这问题，新增的节点也不会直接加到末尾

**Comment by coolsnowwolf** [comment]
因为现在服务器的备注会变，例如有些机场显示（XXX，剩余XXMB 流量）。这样会被视为新节点

**Comment by AmibaWorld** [comment]
可否添加 批量删除 fail 的节点呢，谢谢

**Comment by luckyyyyy** [comment]
我尝试修复下，但是不一定可以成功，可以在观察一下。

**Comment by luckyyyyy** [comment]
新增的节点将会显示在节点列表的末尾而不是按照订阅顺序重新排序

这个可能不太好做，方法只有清空原有的而不是增量。

这样会导致cfgid变化，其他用到cfgid的地方都要重新set，引发的问题更多。

**Comment by haoqwenie** [comment]
![Snipaste_2023-12-31_11-02-28](https://github.com/coolsnowwolf/lede/assets/35169879/e6a42df3-6446-4de5-875d-c90c700421e8)
只可以检测延迟，可以上网，但无法显示是否联通，是否会影响自动切换功能导致一直进行切换？
