### ISSUE TITLE
针对 SSR PLUS 的几个改进小建议

### ISSUE THREAD

**Issue by Bintel** [coolsnowwolf/lede#3099]
在使用过程中发现了一些不太方便或是可以进一步改善的地方, 不知道有没有实现的可能:

1. 由于(#3096 ), 建议把"自动更新服务器订阅、GFW列表和CHN路由表"选项拆分为"自动更新服务器订阅"与"自动更新GFW列表和CHN路由表"

2. 加入一个入口(按钮或链接)把程序当前所使用的GFW列表和CHN路由表完整显示出来, 以方便快速解决"我访问的xxx.com这个网站是不是正在走代理?"这个问题.

3. 使用户可以编辑程序所使用的GFW列表和CHN路由表的URL.

2. "访问控制"建议按照当前反过来的方式编辑规则, 也就是针对内网某个IP设置运行模式, 而不是在某个运行模式下加入内网IP, 比如指定192.168.1.100走绕过中国大陆IP模式, 192.168.1.200走全局模式, 而不是在全局模式下加入某个IP. 如果这个功能不打算做的话, 希望加入缺失的"绕过中国大陆IP模式".

3. "启动自动切换"功能可以根据根据关键字识别进行分组或是用户手动分组, 比如所有香港节点在一组, 日本节点在一组, 在组内进行自动切换.

**Comment by edmondfr** [comment]
我也提一个小建议。
订阅的站点服务器，默认全部都是允许自动切换的，建议改成默认不允许切换。
因为速度快的服务器只是少数，默认全部允许切换会经常换到速度一般的服务器。交由用户自己勾选比较方便。

**Comment by hxlls** [comment]
程序走什么线路这个东西就比较难解决，这个需要DPI识别，openwrt目前没有人维护这种东西
还有这个切换机制，其实你可用设置成一个常用的快的，这个就是你用的主线路，如果快的崩了，恢复后在设定的时间内会自动切换回来，不会乱跳的，所以我觉得没必要纠结
