### ISSUE TITLE
IPv6打开路由器端口无效

### ISSUE THREAD

**Issue by Ge0Lin** [coolsnowwolf/lede#3118]
想利用IPv6访问路由器的某个端口，但是在防火墙 - 通信规则-打开路由器端口中的设置并没有起到作用。
补充：是开启SSR Plus的ShadowSocksR 服务端情况下。

**Comment by hcym** [comment]
好像最近改过相关码，不能ping6的域名，活见鬼

**Comment by ron159** [comment]
同遇到ipv6问题，最新代码编译的固件能正确拨号获取前缀，也能分发给本地其他主机，但是提示“无Internet访问权限“，切换到基于1-24日代码编译的固件正常，ipv6-test.com之类的测试网站能测试通过。
参看近期提交里有对ipv6相关代码进行提交，不知道是不是这个原因，坐等解决

**Comment by hcym** [comment]
改动多了乱了，今天编译的pdnsd失效大增，还是退到去年的过日子吧
