### ISSUE TITLE
网络断流

### ISSUE THREAD

**Issue by Guan921** [coolsnowwolf/lede#3119]
Turbo ACC网络加速中的Flow Offloading启用，就会不定时的断流

**Comment by kl9800** [comment]
请问怎么监测断流？我也想试试有没有这个情况

**Comment by Guan921** [comment]
> 请问怎么监测断流？我也想试试有没有这个情况

就上网上着好好的就没网了，过一会又自己好了，或者自己在openwrt的网络接口中把WAN口从新连接一下就好了，实测关闭了Turbo ACC中的Flow Offloading就不会出现这种情况
![微信图片编辑_20200216133129](https://user-images.githubusercontent.com/53667795/74599708-60226b00-50c1-11ea-98b3-760930ec30b0.jpg)

**Comment by kl9800** [comment]
观察了一下午，没问题…
