### ISSUE TITLE
git 安装失败 已解决

### ISSUE THREAD

**Issue by z5984** [coolsnowwolf/lede#3123]
我想在我的软路由上安装git服务端
但出现了以下报错

root@OpenWrt:/# opkg install git
Installing git (2.25.0-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/git_2.25.0-1_x86_64.ipk
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Installing libopenssl1.1 (1.1.1d-2) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base/libopenssl1.1_1.1.1d-2_x86_64.ipk
Collected errors:
 * check_data_file_clashes: Package libopenssl1.1 wants to install file /usr/lib/libcrypto.so.1.1
        But that file is already provided by package  * libopenssl
 * check_data_file_clashes: Package libopenssl1.1 wants to install file /usr/lib/libssl.so.1.1
        But that file is already provided by package  * libopenssl
 * opkg_install_cmd: Cannot install package git.

**Comment by SharerMax** [comment]
建议你用luci界面安装

**Comment by AmadeusGhost** [comment]
编译的时候选上git就行了，opkg install容易冲突

**Comment by slitilanber** [comment]
opkg install git --force-overwrite

**Comment by z5984** [comment]
> opkg install git --force-overwrite

root@OpenWrt:~# opkg install git --force-overwrite
Installing git (2.25.0-1) to root...
Collected errors:
 * opkg_download_pkg: Package git is not available from any configured src.
 * opkg_install_pkg: Failed to download git. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package git.
root@OpenWrt:~#

**Comment by z5984** [comment]
> 编译的时候选上git就行了，opkg install容易冲突

我用了别人编译好的固件

**Comment by z5984** [comment]
> 建议你用luci界面安装

Thank you !

**Comment by servicehost** [comment]
@zhou-daxia 请问一下你是怎么解决的？我现在也遇到这个问题。

**Comment by zhou-daxia** [comment]
> @zhou-daxia 请问一下你是怎么解决的？我现在也遇到这个问题。

我是在web上的 系统->软件包 里安装的

**Comment by servicehost** [comment]
> 
> 
> > @zhou-daxia 请问一下你是怎么解决的？我现在也遇到这个问题。
> 
> 我是在web上的 系统->软件包 里安装的

谢谢，但现在官方源不知怎么了，git、node、libopenssl1.1.. 等全消失了.. 连安装都安不了。
