### ISSUE TITLE
ssrplus新增加的【广告屏蔽】数据库和adbyby的功能是否一样？

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#3127]
ssrplus新增加的【广告屏蔽】数据库和adbyby的功能是否一样？
两个各自是什么区别？
有没有人能阐明一下，不胜感谢

**Comment by snakwu** [comment]
adbyby功能不能处理ssr的数据,所以,对出外无效

**Comment by norikohxb** [comment]
也就是ssrplus新增的广告屏蔽是针对翻墙部分的，那么他的黑名单lishi是否应该以国外网站的黑名单为准，不应该再有中国网站的了吧，不然不是存在判断资源的浪费吗？
