### ISSUE TITLE
网易云音乐手机APP 端不能劫持的解决办法

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#3130]
网易云音乐经常手机端不设置代理，不能劫持，所以解锁不了灰色的，查了下，是APP端回访问223.252.199.10，这个IP地址，所以直接把这个地址加入ADP 黑名单，禁止访问，实测不需要设置代理啥的，IOS 和安卓就正常劫持了

**Comment by coolsnowwolf** [comment]
除了这个静态IP还有其他吗？

**Comment by hxlls** [comment]
目前没有了，我加了后实测生效的

**Comment by hxlls** [comment]
https://jixun.moe/netease-android-hosts-bypass/ 这个是参考的链接。

**Comment by 1-github-1** [comment]
> 网易云音乐经常手机端不设置代理，不能劫持，所以解锁不了灰色的，查了下，是APP端回访问223.252.199.10，这个IP地址，所以直接把这个地址加入ADP黑名单，禁止访问，实测不需要设置代理啥的，IOS和安卓就正常劫持了

你好  问下 我是劫持了之后还是访问不了  你现在有出现这样的情况吗
