### ISSUE TITLE
Turbo ACC 网络加速界面显示bug吗？？

### ISSUE THREAD

**Issue by keivenliao** [coolsnowwolf/lede#3145]
![image](https://user-images.githubusercontent.com/12838693/74622399-9b817000-517b-11ea-8726-5a49b6ee0d45.png)

如上图，即使全部取消，fullcone nat 也会是运行中状态，这个是bug吗？

**Comment by asushugo** [comment]
![image](https://user-images.githubusercontent.com/18640537/74622558-472ac000-517c-11ea-90e4-511a8c2b345d.png)
开关在这呢

**Comment by keivenliao** [comment]
谢谢！

**Comment by czjesda** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/18640537/74622558-472ac000-517c-11ea-90e4-511a8c2b345d.png)
> 开关在这呢
图片打不开，可以重新发一下么？

**Comment by 9l** [comment]
图片打不开的，将这个域名加到 gfw 列表里

`user-images.githubusercontent.com`
