### ISSUE TITLE
能不能把mux默认为关闭？

### ISSUE THREAD

**Issue by Raymondhhh90** [coolsnowwolf/lede#3146]
Mux 是为了减少 TCP 的握手延迟而设计，而非提高连接的吞吐量。使用 Mux 看视频、下载或者测速通常都有反效果。
https://www.v2ray.com/chapter_02/mux.html

**Comment by lloyd18** [comment]
V2rayN都是默认开启的

**Comment by SharerMax** [comment]
最新的是默认关闭

**Comment by MeIsReallyBa** [comment]
我开着看YouTube和关了差不多接近10w，但是看图片感觉快点。
