### ISSUE TITLE
docker根目录会自动挂载到overlayfs:/overlay

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#3147]
这点空间根本不够用，想挂载到别的分区都不行了，之前也不会这样。
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/74625562-b2c65a80-5187-11ea-8e9d-2dba85d5bcad.jpg)

**Comment by RealKiro** [comment]
自己按照原来的教程改分区
