### ISSUE TITLE
nanopi r2s的rk3328源码这里有,大雕可以同步一下吗?

### ISSUE THREAD

**Issue by lqhorochi** [coolsnowwolf/lede#3153]
nanopi r2s的rk3328源码这里有,大雕可以同步一下吗?
https://github.com/friendlyarm/friendlywrt
同步一下他的源码,就可以编译到nanopi r2s

**Comment by hxlls** [comment]
SDK不一样

**Comment by Aes64X** [comment]
> nanopi r2s的rk3328源码这里有,大雕可以同步一下吗?
> https://github.com/friendlyarm/friendlywrt
> 同步一下他的源码,就可以编译到nanopi r2s

官方提供的那个可以直接用啊，他们跟的19.07
另外，你提供设备给作者，或许可以。（我就这么一说）

**Comment by kl9800** [comment]
请问在  make menuconfig 的里面，怎么选中这个RK3328 ？找半天没找到呀

**Comment by maryjeck** [comment]
https://github.com/klever1988/nanopi-openwrt

这个可以看看，据说明是跟的lean大神的
