### ISSUE TITLE
斐迅K3的WIFI虚拟多个设备时不正常

### ISSUE THREAD

**Issue by marstone** [coolsnowwolf/lede#316]
现象是：
- 虚拟的多个设备均无法使用
- ap模式时客户端可以搜到信号但无法连接；sta模式的路由器无法连上
- 同样配置，如果删掉一个，另一个均可正常工作
- 同样配置，在其他型号路由器（Atheros，OpenWRT CC）可正常工作
- 2.4G（radio0）和5G（radio1）均不正常

参考配置： /etc/config/wireless 
config wifi-device 'radio0'
        option type 'mac80211'
        option ...

config wifi-iface
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option ...

config wifi-iface
        option device 'radio0'
        option network 'wan'
        option mode 'sta'
        option ...

**Comment by prohut** [comment]
这个问题我也碰到了，我记得以前是可以用的

**Comment by wheretoteardown** [comment]
brcmfmac驱动的锅，不支持sta+ap模式。
