### ISSUE TITLE
2月17日更新git pull后编译出现这些错误，请问需要怎么改正

### ISSUE THREAD

**Issue by azxcvjj** [coolsnowwolf/lede#3166]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	kcptun-client
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/install] Error 255
make[2]: Leaving directory `/home/liu/lede'
make[1]: *** [/home/liu/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/liu/lede'
make: *** [world] 错误 2

**Comment by panther706** [comment]
选上kcptun-client
