### ISSUE TITLE
更新到openwrt r20.1.24 之后 ss plus+ 只有ssr能正常，ss和v2ray都不能工作

### ISSUE THREAD

**Issue by qinfeng8848** [coolsnowwolf/lede#3168]
更新到openwrt r20.1.24 之后 ss plus+ 只有ssr能正常，ss和v2ray都不能工作

![](https://tva1.sinaimg.cn/large/0082zybpgy1gc0ft10ak2j30xs094gn4.jpg)
https://tva1.sinaimg.cn/large/0082zybpgy1gc0fs2p5kij30xs094gn4.jpg

**Comment by yidaofeitop** [comment]
同样的问题出现在最新版本2020年10月5日，查找issue只能查到说一个彩蛋，但是试过也没有用！

路由器：wndr4700
