### ISSUE TITLE
ssr plus中的v2ray可否加入tcp的http伪装支持呢?

### ISSUE THREAD

**Issue by git-maven** [coolsnowwolf/lede#3173]
由于合租的v2ray只开了tcp的http伪装所以
请求L大
ssr plus中的v2ray可否加入tcp的http伪装支持呢?

**Comment by SharerMax** [comment]
现在就支持啊

**Comment by git-maven** [comment]
> 好吧 并不支持，应该是没弄完
> 可以让合租的小伙伴试试其它的伪装模式先

记得以前有人说有的后来被删了
现在我也在找以前的ssrplus版本

**Comment by coolsnowwolf** [comment]
可以贴上具体的 json 或者 vmess 链接看看

**Comment by git-maven** [comment]
> 可以贴上具体的 json 或者 vmess 链接看看

vmess://eyJhaWQiOiAxNiwgInBvcnQiOiA3ODk1LCAidHlwZSI6ICJodHRwIiwgInBhdGgiOiAiIiwgInYiOiAiMiIsICJwcyI6ICIiLCAidGxzIjogIm5vbmUiLCAiaWQiOiAiNWE3ZWZlYWEtNTMzNC0xMWVhLWE1OTUtMDAxNjNlMDA2NzBkIiwgImFkZCI6ICIxNDkuMTI5LjQ0LjEyIiwgImhvc3QiOiAiZG5zLndlaXhpbi5jb20iLCAibmV0IjogInRjcCJ9

L大你试试
这个配置在手机版的V2rayNG和电脑版的V2rayNG中均能联网的

**Comment by coolsnowwolf** [comment]
支持的，需要 允许 insecure 不安全的方式才能连接

**Comment by smallprogram** [comment]
> 支持的，需要 允许 insecure 不安全的方式才能连接

允许了insecure也还是不行
