### ISSUE TITLE
ADP 怎么编译加入规则订阅？

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#3174]
https://github.com/privacy-protection-tools/anti-AD 这个规则看起来不错，并且已经有多种支持，想加入adp使 去广告过滤效果更好点

**Comment by goukey** [comment]
装个adguard home添加规则用吧

**Comment by hxlls** [comment]
不需要ADG，浪费资源，本来就支持dnsmasq的配置，为啥要装个这么占用资源的东西

**Comment by coolsnowwolf** [comment]
这个去广告的订阅目前迁移到 SSR Plus+ 中了

例如你这个需求，在 SSR Plus+ 的去广告订阅中，输入

https://gitee.com/privacy-protection-tools/anti-ad/raw/master/easylist.txt

![image](https://user-images.githubusercontent.com/31687149/74716026-bc73bf00-5268-11ea-9afa-0150621f1f7d.png)

然后更新去广告条目：
![image](https://user-images.githubusercontent.com/31687149/74716089-d7deca00-5268-11ea-810d-0e06cb2330f5.png)

然后应用重启 SSR Plus+ 即可马上生效

**Comment by hxlls** [comment]
SSRP的广告订阅在国内也可以生效么？

**Comment by coolsnowwolf** [comment]
当然，全局生效

**Comment by hxlls** [comment]
OK,这太好了

**Comment by hcym** [comment]
新玩具，感谢各位帅哥

**Comment by lltcom** [comment]
订阅的规则可以设置几条么，默认是1条

**Comment by kawon7317** [comment]
太好了

**Comment by jxph1123** [comment]
建议可以自己再新加地址，只有一条，能自己多增加就更好了，可以淘汰ADBYBY了。

**Comment by coolsnowwolf** [comment]
加多条支持只会被滥用而已，好用的一条即可

**Comment by d975xbx** [comment]
https的过滤效果感觉不如浏览器插件

**Comment by d975xbx** [comment]
![1](https://user-images.githubusercontent.com/21034764/74725173-7c1c3d00-5278-11ea-91b7-56b55b2039d3.png)
去不掉，浏览器插件可以

**Comment by dolphinpaopao** [comment]
个人使用证明，目前浏览器插件才是最完善的，路由器开启这些功能或多或少都会出现一下莫名其妙的影响。测试过，最不受人待见的D2550，不开过滤广告什么插件，完全可以满足500M宽带+油管15W↑。

**Comment by china0532** [comment]
给大家推荐个浏览器去广告插件adblock-plus过滤广告很强，就是不能在路由器上用，只有手机版，和浏览器版

**Comment by SharerMax** [comment]
> 这个去广告的订阅目前迁移到 SSR Plus+ 中了
> 
> 例如你这个需求，在 SSR Plus+ 的去广告订阅中，输入
> 
> https://gitee.com/privacy-protection-tools/anti-ad/raw/master/easylist.txt
> 
> ![image](https://user-images.githubusercontent.com/31687149/74716026-bc73bf00-5268-11ea-9afa-0150621f1f7d.png)
> 
> 然后更新去广告条目：
> ![image](https://user-images.githubusercontent.com/31687149/74716089-d7deca00-5268-11ea-810d-0e06cb2330f5.png)
> 
> 然后应用重启 SSR Plus+ 即可马上生效

有点问题，更新的规则生成的ad.conf 在/etc/dnsmasq.ssr 下，dnsmasq 运行时使用的是/tmp/etc/dnsmasq.ssr 下的，更新完可能要重启一下才能生效

**Comment by jackiezhang29** [comment]
是不是adblock plus在编译的时候，就不需要添加了？现在用大雕集成广告过滤的ssr+就行？

**Comment by hxlls** [comment]
> 是不是adblock plus在编译的时候，就不需要添加了？现在用大雕集成广告过滤的ssr+就行？

按照道理上是可以的，我看了下规则好像比较详尽，并且利用的也是dnsmasq 来做HOST 类型的去广告，并且很大部分规则和ADP应该是有重复的。所以觉得取消ADP应该也没太大问题

**Comment by jxph1123** [comment]
SSR Plus+ 去广告还有点问题，会导致有些网站打不开或者打开延时，我又取消了。
