### ISSUE TITLE
Trojan协议不能导入信息

### ISSUE THREAD

**Issue by panther706** [coolsnowwolf/lede#3175]
如题，WNDR4300，其它协议可以导入。你们的可以吗？还是个案？手动输入可以连上。

**Comment by SharerMax** [comment]
可否贴一下链接

**Comment by coolsnowwolf** [comment]
没链接怎么解决？

**Comment by panther706** [comment]
> 没链接怎么解决？

trojan://k8aPbf@92.118.45.156:443?allowInsecure=1&peer=jpo156.ovod.me#%E5%85%8D%E8%B4%B9%C2%B7T%C2%B7%E6%97%A5%E6%9C%ACO%C2%B7156

**Comment by SharerMax** [comment]
这都啥，我觉得还是按照这个来重新实现一波吧

`trojan://password@remote_host:remote_port`

https://github.com/trojan-gfw/trojan-url

**Comment by coolsnowwolf** [comment]
机场主又自创标准了。。。明明有官方的

trojan://password@remote_host:remote_port

https://github.com/trojan-gfw/trojan-url
