### ISSUE TITLE
./scripts/feeds install -a 时提示没有ethtool

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#318]
WARNING: Makefile 'package/feeds/packages/aircrack-ng/Makefile' has a dependency on 'ethtool', which does not exist
WARNING: Makefile 'package/feeds/packages/jool/Makefile' has a dependency on 'ethtool', which does not exist
在make menuconfig时也有这些。然而我已经安装了

**Comment by AndyX-Net** [comment]
同样，即使重新下载源代码也是这样的。。。也许是某些代码与feeds源冲突？

**Comment by yup8719** [comment]
同样出现这个问题
