### ISSUE TITLE
ssR Plus+重启后无法自动自动

### ISSUE THREAD

**Issue by himho** [coolsnowwolf/lede#3181]
OpenWrt R20.2.15 / LuCI Master (git-20.049.31824-820652f) 编译后软路由重启后ssr无法自动启动，修改启动优先级也无效果。而且SSR在软路由启动会有小几率会启动成功的现象。
 原来以为是自己编译问题 后来编译了很多次都只这种现象。

**Comment by monsterzzzz** [comment]
同感

**Comment by hxlls** [comment]
这个好像是，路由重启SSRP 不会自动运行了，应该是BUG

**Comment by himho** [comment]
> 这个好像是，路由重启SSRP 不会自动运行了，应该是BUG

咱也不知道耶不敢瞎说啊 ~等吧

**Comment by xiaozizi58** [comment]
我取消编译turbo acc网络加速这个模块重启后就没事了

**Comment by georip** [comment]
最近的版本的确是这样。

**Comment by himho** [comment]
> 我取消编译turbo acc网络加速这个模块重启后就没事了

加速模块影响不少东西！实时流量监测在不安装PPTP的情况下，打开flow加速就会不准确。只有在安装pptp的情况下打开flow ，实时监测才准！

**Comment by himho** [comment]
> 我取消编译turbo acc网络加速这个模块重启后就没事了
我刚才试了一下，取消flow加速还是有出现的几率！所以跟加速模块关系不大！
