### ISSUE TITLE
每次重启都要手动启用WiFi？

### ISSUE THREAD

**Issue by cccsyz** [coolsnowwolf/lede#3183]
你们有遇到这种情况吗？还有网易云音乐是只需要把luci-app-unblockneteasemusic选上吗？我只选这一个无法使用。。

**Comment by dovegq** [comment]
要看内核日志排查。
还有有些设备网卡配置可能 是不对 自己确定设备网卡型号 然后
/package/kernel/网卡型号/files/lib/wifi/网卡型号.sh
大概是这个路径看看 是不是set wireless.radio${devidx}.disabled=1
