### ISSUE TITLE
请问L大,关于SSR-Plus的内网客户端分流代理控制优先级问题!

### ISSUE THREAD

**Issue by snakwu** [coolsnowwolf/lede#3193]
![image](https://user-images.githubusercontent.com/5343595/74812627-cfe95d80-532e-11ea-8cdb-86e7a1eed7ce.png)
1,如果内网客户端分流代理控制选择停用,下面的不走代理的局域网LAN IP和全局代理的LAN IP
,还会生效吗?
2,如果内网客户端分流代理控制选择仅允许列表内的主机,全局代理的LAN IP我加进去一个ip,这时,这个ip还会走全局吗?

**Comment by snakwu** [comment]
已解决!

**Comment by azazjjyjjy** [comment]
请问这个选项是什么意思？局域网有服务器可以用来分流？
