### ISSUE TITLE
开启了网易云音乐解锁后，无法QQ登录网易云音乐UWP版

### ISSUE THREAD

**Issue by xieshiyudada** [coolsnowwolf/lede#3194]
开启了网易云音乐解锁后，无法QQ登录网易云音乐UWP版。

**Comment by xieshiyudada** [comment]
打开网易云音乐官网，也会有影响。

**Comment by coolsnowwolf** [comment]
是啊，因为 443 被劫持了，需要安装证书了

**Comment by xieshiyudada** [comment]
安装了证书也不行。那个CA根证书，是无效的。

**Comment by nivalxer** [comment]
Windows下，下载根证书后，安装到受信任的根证书办法机构就可以了。
![image](https://user-images.githubusercontent.com/6287552/74824056-acc8a900-5342-11ea-98e4-1efe52e5cd61.png)
![image](https://user-images.githubusercontent.com/6287552/74824114-c10ca600-5342-11ea-879a-2e602092d35a.png)

**Comment by xieshiyudada** [comment]
谢谢大佬
