### ISSUE TITLE
ext4格式硬盘自动挂载后权限问题导致smb匿名用户没有权限访问，以下sdb1为目标盘

### ISSUE THREAD

**Issue by tomerilery** [coolsnowwolf/lede#32]
root@LEDE:/mnt# df -h -T
Filesystem           Type            Size      Used Available Use% Mounted on
/dev/root            squashfs       13.0M     13.0M         0 100% /rom
tmpfs                tmpfs         250.3M      2.6M    247.7M   1% /tmp
/dev/ubi0_1          ubifs          14.0M    276.0K     13.0M   2% /overlay
overlayfs:/overlay   overlay        14.0M    276.0K     13.0M   2% /
ubi1:syscfg          ubifs          29.6M    276.0K     27.8M   1% /tmp/syscfg
tmpfs                tmpfs         512.0K         0    512.0K   0% /dev
/dev/ubi1_0          ubifs          29.6M    276.0K     27.8M   1% /mnt/ubi1_0
tmpfs                tmpfs         250.3M      2.6M    247.7M   1% /usr/share/adbyby/data
/dev/sda1            fuseblk       465.8G    156.5G    309.3G  34% /mnt/sda1
/dev/sdb1            ext4           14.1G    592.4M     12.7G   4% /mnt/sdb1
root@LEDE:/mnt# ls -al
drwxr-xr-x      1 root     root           352 Sep 10 09:33 .
drwxr-xr-x      1 root     root           544 Jun  9 05:02 ..
drwxrwxrwx    1 root     root       12288 Sep 10 09:54      sda1
drwx------       5 1000   1000        4096 Sep  9 22:35       sdb1
drwxr-xr-x       9 root     root          848 Sep  7 16:40       ubi1_0
root@LEDE:/mnt#
smb设置里文件夹的权限已经是0777了，访问smb服务器，打开sdb1文件夹会提示没有权限访问，而sda1为NTFS系统，则正常读写。
作者的设计思路在插入硬盘后自动设置smb匿名共享，但是现在ext4文件系统挂载目录权限导致不能全自动了

**Comment by coolsnowwolf** [comment]
这个和你格式化 ext4 的时候分配的权限有关，脚本只会修改 Samba 权限而不会更改 ext4 权限
