### ISSUE TITLE
已经成功编译过多次,今天单独编译ssr plus出现如下提示

### ISSUE THREAD

**Issue by wlxj5** [coolsnowwolf/lede#3200]
在网络上实在是找不到类似的方案了 所以才在这里提问了 
![image](https://user-images.githubusercontent.com/60879497/74828048-632f8c80-5349-11ea-88e3-810354e6297e.png)

**Comment by SharerMax** [comment]
upx 未生成的问题
```
rm  .config
rm -rf /tmp
```
然后**重头**来一遍

**Comment by wlxj5** [comment]
> upx 未生成的问题
> 
> ```
> rm  .config
> rm -rf ./tmp
> ```
> 
> 然后**重头**来一遍

按照您的操作 没有成功

**Comment by SharerMax** [comment]
> 按照您的操作 没有成功

make tools/install V=s
看看upx构建没

**Comment by wlxj5** [comment]
> > 按照您的操作 没有成功
> 
> make tools/install V=s
> 看看upx构建没

网速比较慢,尝试了两次 按照您的方法
make tools/install V=s
然后再重新编译就可以了

谢谢您的热心解答
