### ISSUE TITLE
今天更新的dns TTL 功能好像我没找到luci 界面设置

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#3202]
今天更新的dns TTL 功能好像我没找到luci 界面设置，这个是我眼神不行了？还是没加上？

**Comment by xiaozizi58** [comment]
没加上吧 刚git pull 编译出来的版本还是2.80.9

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/74844013-c6c8b280-5367-11ea-8784-71c8fc1c6af2.png)
不对啊，我好像看到我编译的是2.80.12了啊，但是我没再luci 界面找到对应的设置入口

**Comment by xiaozizi58** [comment]
我的软件包里面还是2.80.9 编译机里面确实有2.80.12的版本但是编译进路由器的还是2.80.9  我是x64

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/74846077-e01f2e00-536a-11ea-91a8-90042fcd7ceb.png)
我重新编译了，确认是12版的，但是还是没找到，可能是没写luci?

**Comment by SharerMax** [comment]
rm -rf bin/*
重新编译

**Comment by hxlls** [comment]
rm 掉bin文件夹后重新编译解决了
