### ISSUE TITLE
建议-增强“作为备用节点”功能的可控性

### ISSUE THREAD

**Issue by JeremyPeng** [coolsnowwolf/lede#3204]
Lean大，现有备用节点切换机制中，由于默认勾选了所有可订阅的节点作为备用节点，对于某些带有特权流量和高倍率流量的机场，不太友好。那些节点速度和连接性可能都是最好的，但需要用户付出更高代价...像我这种乞丐党就不敢用了。对此我有2个建议：

1.  在订阅节点的界面，添加一个开关，控制订阅节点是否默认加入备选节点。（当节点数量到达20+时一个一个去关也是很恐怖的操作）

2. 订阅节点中“是否作为备用节点”的选项，一旦更改，再次更新节点订阅，不会被刷新掉。（不然每次自动更新，或手动更新后，都要去设置一边）

希望L大能考虑加入～

**Comment by coolsnowwolf** [comment]
已实现：

![image](https://user-images.githubusercontent.com/31687149/74896375-17bfc180-53cf-11ea-9265-8184648a8627.png)

**Comment by JeremyPeng** [comment]
谢大佬，瞬间实现了小愿望
