### ISSUE TITLE
CIFSD共享服务器访问不了

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#3207]
win10系统，网上邻居识别不了，有人说用IP访问，共享/mnt/sda1，在我的电脑中输入\\\192.168.0.170\mnt\sda1，也访问不了。

**Comment by jy3344511** [comment]
有人说用IP访问，共享/mnt/sda1，在我的电脑中输入：\\192.168.1.170\mnt\sda1，也访问不了。

**Comment by R3pl4c3r** [comment]
> 
> 
> win10系统，网上邻居识别不了，有人说用IP访问，共享/mnt/sda1，在我的电脑中输入\\192.168.0.170\mnt\sda1，也访问不了。

假如共享名是data，共享目录是/mnt/sda1，那么应该访问\\your.ip\data，而不是\\your.ip\mnt\sda1
遇到问题先去百度或Google，少发垃圾issue。
此issue建议立刻关闭。

**Comment by z826540272** [comment]
\\192.168.0.170
