### ISSUE TITLE
目前ssr+自带的广告屏蔽规则会导致千牛登录异常[非淘宝/天猫卖家无视即可]

### ISSUE THREAD

**Issue by EnnawYang** [coolsnowwolf/lede#3208]
具体症状例如无法正常加载团队列表，挂起状态，千牛首页模块等等，关闭广告过滤或者更换其它订阅链接后可以正常登录，如果要正常使用千牛的话建议更换下订阅链接，或者关闭广告屏蔽
![Snipaste_2020-02-20_09-58-41](https://user-images.githubusercontent.com/6705663/74894435-edb7d080-53c9-11ea-8e86-1436ed7a7155.png)
![Snipaste_2020-02-20_09-59-03](https://user-images.githubusercontent.com/6705663/74894437-ee506700-53c9-11ea-994b-56b259c92c1b.png)

**Comment by hcym** [comment]
是不是要和adb＋一起用的？

**Comment by EnnawYang** [comment]
> 是不是要和adb＋一起用的？

不用

**Comment by coolsnowwolf** [comment]
建议上 https://github.com/privacy-protection-tools/anti-AD 提交一个issue ，让作者看看怎么处理

**Comment by EnnawYang** [comment]
> 建议上 https://github.com/privacy-protection-tools/anti-AD 提交一个issue ，让作者看看怎么处理

嗯 刚过去提issue了
