### ISSUE TITLE
编译出来的固件只能支持8线程和8组网卡队列

### ISSUE THREAD

**Issue by cowboy910** [coolsnowwolf/lede#3209]
编辑出来的固件很好用，但只能支持8线程和8组队列，有办法修改吗？希望能够填加到40线程，希望能够指导一下方向，谢谢。

信息如下：

主机名 | OpenWrt
-- | --
主机型号 | Intel(R) Xeon(R) CPU E5-2650L v2 @ 1.70GHz : 4 Core 8 Thread
CPU信息 | 1695.912 MHz
固件版本 | OpenWrt R20.2.15 / LuCI Master (git-20.049.31824-820652f)
内核版本 | 4.19.101

**Comment by 9l** [comment]
40线程可以起飞了，路由器中的战斗鸡

**Comment by cowboy910** [comment]
我下载了koolshare 的LEDE v2.31 版本，同一环境能够识别40线程和40网卡队列，来证硬件测试环意。
我有尝试make kernel_menuconfig 进行修改一些选择，但由于选项好多不了解，也末能成功。百度能够查到的资料也不多。

**Comment by coolsnowwolf** [comment]
目前对 Intel CPU 进行了限制，更换 AMD 的 CPU 即可开启最大双路 256 线程

**Comment by hcym** [comment]
编译效果明显，路由跑ss什么的没什么区别吧？

**Comment by cowboy910** [comment]
经过长时间测试，发现单线多拔的成功率与网队列数有关，所以新购买了Intel X540 网卡进行测试，而网卡队列需要CPU 线程的支持，所以就卡在这里。

**Comment by coolsnowwolf** [comment]
可以更换 Ryzen 平台试试，目前对 Intel 有限制，等 Intel CPU 修复了漏洞再说

**Comment by cowboy910** [comment]
感谢回复，手上没有AMD平台， Intel CPU 存在什么漏洞会影响到吗？我想查阅一下资料，看有没有办法解决。
