### ISSUE TITLE
【Request】SSR+加入kumasocks支持

### ISSUE THREAD

**Issue by martin0607** [coolsnowwolf/lede#3214]
由于MT7621性能不足，在本机跑V2RAY速度有瓶颈，所以在群晖docker上部署了客户端并开启sock5代理，kumasocks刚好能让局域网的其他设备连接socks5代理，大大降低CPU用量。
https://github.com/xsm1997/openwrt-kumasocks

**Comment by coolsnowwolf** [comment]
SSR Plus 自带了 SOCKS5 代理，认真看

**Comment by coolsnowwolf** [comment]
如果是透明代理 socks， ip2socks 也自带了

**Comment by dolphinpaopao** [comment]
一言不合就开issue真的是佛了，事先搜索或者咨询一下真的那么那么难吗。

**Comment by martin0607** [comment]
> 一言不合就开issue真的是佛了，事先搜索或者咨询一下真的那么那么难吗。

你牛你去搜搜看能搜到什么:D

**Comment by dolphinpaopao** [comment]
> > 一言不合就开issue真的是佛了，事先搜索或者咨询一下真的那么那么难吗。
> 
> 你牛你去搜搜看能搜到什么:D

![lean](https://user-images.githubusercontent.com/20945941/74936511-381a6b00-5425-11ea-81cb-e7ebd2a81b0b.png)
您还别说，我还真去搜了一下呢。也看到答案了。
