### ISSUE TITLE
请教下Ubuntu的neteasemusic怎么劫持

### ISSUE THREAD

**Issue by zwillhill** [coolsnowwolf/lede#3216]
cp CA.crt /usr/share/ca-certificates/x-net.crt

拷贝证书到/usr/share/ca-certificates/下

sudo chmod a+r /usr/share/ca-certificates/x-net.crt

修改权限

sudo dpkg-reconfigure ca-certificates 

安装证书
————————————————
按照上面操作安装了证书劫持无效，显示网络无法连接，Ubuntu版本18.04，Neteasemusic客户端版本1.2，chrome网页版显示证书错误，忽略后也是无法解锁

**Comment by nivalxer** [comment]
Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
网页已信任，未找到客户端下载链接，未测试客户端
![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)

**Comment by zwillhill** [comment]
> Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> 网页已信任，未找到客户端下载链接，未测试客户端
> ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)

谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
低版本好像装不上，这个能装，但是没有代理设置功能。

**Comment by nivalxer** [comment]
> > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > 网页已信任，未找到客户端下载链接，未测试客户端
> > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> 
> 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> 低版本好像装不上，这个能装，但是没有代理设置功能。

用你发的客户端试了一下，正常。
![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)

**Comment by zwillhill** [comment]
> > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > 
> > 
> > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > 低版本好像装不上，这个能装，但是没有代理设置功能。
> 
> 用你发的客户端试了一下，正常。
> ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)

感谢测试！难道还是证书的问题？我再研究研究

**Comment by shi429101906** [comment]
> > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > 
> > 
> > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > 低版本好像装不上，这个能装，但是没有代理设置功能。
> 
> 用你发的客户端试了一下，正常。
> ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)

大佬，安卓上的也无法劫持， 这个有没有解决办法呢

**Comment by zwillhill** [comment]
> > > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > > 
> > > 
> > > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > > 低版本好像装不上，这个能装，但是没有代理设置功能。
> > 
> > 
> > 用你发的客户端试了一下，正常。
> > ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> > ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)
> 
> 大佬，安卓上的也无法劫持， 这个有没有解决办法呢

安卓直接下载生成的证书安装就可以啦，

**Comment by shi429101906** [comment]
> > > > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > > > 
> > > > 
> > > > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > > > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > > > 低版本好像装不上，这个能装，但是没有代理设置功能。
> > > 
> > > 
> > > 用你发的客户端试了一下，正常。
> > > ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> > > ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)
> > 
> > 
> > 大佬，安卓上的也无法劫持， 这个有没有解决办法呢
> 
> 安卓直接下载生成的证书安装就可以啦，

安装证书没有卵用， 安卓和ubuntu18一个样， 用了博客里写的加上代理， 也和上面的问题一样， 无法连接。  现在可以正常使用的只有win10的uwp版><

**Comment by nivalxer** [comment]
> > > > > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > > > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > > > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > > > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > > > > 
> > > > > 
> > > > > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > > > > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > > > > 低版本好像装不上，这个能装，但是没有代理设置功能。
> > > > 
> > > > 
> > > > 用你发的客户端试了一下，正常。
> > > > ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> > > > ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)
> > > 
> > > 
> > > 大佬，安卓上的也无法劫持， 这个有没有解决办法呢
> > 
> > 
> > 安卓直接下载生成的证书安装就可以啦，
> 
> 安装证书没有卵用， 安卓和ubuntu18一个样， 用了博客里写的加上代理， 也和上面的问题一样， 无法连接。 现在可以正常使用的只有win10的uwp版><

没有安卓机可以测试，能提供一下安卓的版本号么？
空了我试试x86的模拟器看看。

**Comment by zwillhill** [comment]
> > > > > > > Chrome等网页在Ubuntu下要信任证书还需要使用certutil导入到stores中
> > > > > > > 参考：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
> > > > > > > 网页已信任，未找到客户端下载链接，未测试客户端
> > > > > > > ![image](https://user-images.githubusercontent.com/6287552/74922791-b584b200-540a-11ea-843c-928bf8ef3777.png)
> > > > > > 
> > > > > > 
> > > > > > 谢谢，按链接里操作，chrome证书没问题了。客户端还是显示网络错误
> > > > > > 1.2.1版本（和深度合作开发，应该是以前的官方版）http://zitian.jb51.net:81/201906/tools/netease-cloud-music_ubuntu_jb51.deb
> > > > > > 低版本好像装不上，这个能装，但是没有代理设置功能。
> > > > > 
> > > > > 
> > > > > 用你发的客户端试了一下，正常。
> > > > > ![image](https://user-images.githubusercontent.com/6287552/75010914-59c53200-54b9-11ea-82f7-3b1546f030bf.png)
> > > > > ![image](https://user-images.githubusercontent.com/6287552/75010990-782b2d80-54b9-11ea-856e-b0997aeb9737.png)
> > > > 
> > > > 
> > > > 大佬，安卓上的也无法劫持， 这个有没有解决办法呢
> > > 
> > > 
> > > 安卓直接下载生成的证书安装就可以啦，
> > 
> > 
> > 安装证书没有卵用， 安卓和ubuntu18一个样， 用了博客里写的加上代理， 也和上面的问题一样， 无法连接。 现在可以正常使用的只有win10的uwp版><
> 
> 没有安卓机可以测试，能提供一下安卓的版本号么？
> 空了我试试x86的模拟器看看。

大佬方便写个导入Ubuntu证书的简易教程不？我是搞不定Ubuntu的证书了，网上搜了好多教程来来回回弄好几遍啦

**Comment by nivalxer** [comment]
> https://thomas-leister.de/en/how-to-import-ca-root-certificate/

就是我之前回复的这个：https://thomas-leister.de/en/how-to-import-ca-root-certificate/
不过看反馈好像没成功，我这边虚拟机是OK的。

**Comment by shi429101906** [comment]
@nivalxer 我使用的是小米mix 2s, 系统版本号这两天刚更新, MUI11.0.1, 之前的版本10， 手机和ubuntu都安装了证书不起作用， https://www.maxlicheng.com/github/232.html， 使用这里的自定义代理， 网易将无法上网。 openwrt的版本是esir2月1日编译的高大全版
