### ISSUE TITLE
libncurses6 与 源里的libncurses 有冲突

### ISSUE THREAD

**Issue by kalagxw** [coolsnowwolf/lede#3227]
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/mips_24kc/base/libncurses6_6.1-5_mips_24kc.ipk
Collected errors:
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libformw.so.6
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libformw.so.6.1
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libmenuw.so.6
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libmenuw.so.6.1
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libncursesw.so.6
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libncursesw.so.6.1
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libpanelw.so.6
        But that file is already provided by package  * libncurses
 * check_data_file_clashes: Package libncurses6 wants to install file /usr/lib/libpanelw.so.6.1
        But that file is already provided by package  * libncurses
 * opkg_install_cmd: Cannot install package vim.

**Comment by coolsnowwolf** [comment]
已解决
