### ISSUE TITLE
nut-server服务问题

### ISSUE THREAD

**Issue by mm2231031** [coolsnowwolf/lede#3228]
平台：x86_64
固件版本：LuCI Master (git-20.050.46852-a2b0e0c) / OpenWrt R20.2.15
问题：使用nut-server监听UPS时，提示连接问题，查看内核日志，发现UPS正常连接
`root@GordonRT:~# dmesg |grep -i ups
[    2.148616] hid-generic 0003:051D:0002.0001: hiddev96,hidraw0: USB HID v1.00 Device [American Power Conversion Back-UPS RS 550G FW:857.L7 .I USB FW:L7  ] on usb-0000:00:1d.0-1.1/input0
[   26.532577] cgroup: runc (8056) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.`

检查发现是驱动权限问题，使用`upsdrvctl -u nut start`重启驱动，无法使用非root用户启动，只能手动修改设备文件权限，或者以root用户运行nut-server才可以正常连接，并且upsdrvctl 命令无法和和nut-server关联运行，只能将命令加入rc.local临时解决，后来查阅官方资料，发现这些问题已经在主线修复，希望L大能将相关代码和主线同步
资料：https://openwrt.org/docs/guide-user/services/ups/software.nut

**Comment by coolsnowwolf** [comment]
fix
