### ISSUE TITLE
Netflix dns设置无效

### ISSUE THREAD

**Issue by jackiezhang29** [coolsnowwolf/lede#3230]
原本通过vps设置v2ray的dns分流，Netflix走dns代理53，其他翻墙走公共dns，一切正常。

今天看到lean更新了源码，支持本地自定义Netflix的dns，立马编译更新+设置。但实际情况却失败了，观看Netflix显示使用了代理，无法观看。

**Comment by coolsnowwolf** [comment]
这个只对部分剧生效，有些还是认源IP的

**Comment by roy63258015** [comment]
netflix最新验证规则，原创独占剧不检测ip，非独占剧检测ip

**Comment by jackiezhang29** [comment]
大雕，部分原创现在也不需要dns验证了，直接可以看
