### ISSUE TITLE
建议更换README的推荐系统为Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by AmadeusGhost** [coolsnowwolf/lede#3234]
Ubuntu 14.04 LTS的5年支持已经过了，有些包确实过旧不适合编译，像编译sunxi的uboot还有切换到python3都会有问题，随着同步官方op源码，此类问题会越来越多，所以还是推荐Ubuntu 18.04 LTS好点，而且Actions也证明了Ubuntu 18.04可以稳定编译。

**Comment by coolsnowwolf** [comment]
有道理

**Comment by EstFoxs** [comment]
ubuntu 19 编译环境速度更快

**Comment by hcym** [comment]
应该没问题，用了差不多一年了，年底再看看20.04

**Comment by AmadeusGhost** [comment]
> ubuntu 19 编译环境速度更快

19不是LTS（

**Comment by KFERMercer** [comment]
建议等20.04一步到位

**Comment by EstFoxs** [comment]
> 建议等20.04一步到位

4月底才发布稳定版，还有两月

**Comment by jyy5206** [comment]
用 Ubuntu 18.04.3 Desktop 版本编译了半年多了
一直很稳定

用的是笔记本电脑 Win10 + Ubuntu 双系统
缺省进入Win10
需要编译时切换进入 Ubuntu

亲测建议：
不要用 Win10 里面的 Hyper-V 虚拟机
慢的要死~

**Comment by ZForest000** [comment]
用WIN10的也可以考虑WSL安装Ubuntu 18.04 LTS

**Comment by xydche** [comment]
> 用 Ubuntu 18.04 LTS Desktop 版本编译了半年多了
> 一直很稳定
> 
> 用的是笔记本电脑 Win10 + Ubuntu 双系统
> 缺省进入Win10
> 需要编译时，重启切换到 Ubuntu
> 
> 亲测建议：
> 不要用 Win10 里面的 Hyper-V 虚拟机
> 慢的要死~

还行吧，hyper v感觉挺快的啊。主要是方便，编译的时候电脑该干麻干麻

**Comment by rageq** [comment]
> 
> 
> 用 Ubuntu 18.04 LTS Desktop 版本编译了半年多了
> 一直很稳定
> 
> 用的是笔记本电脑 Win10 + Ubuntu 双系统
> 缺省进入Win10
> 需要编译时，重启切换到 Ubuntu
> 
> 亲测建议：
> 不要用 Win10 里面的 Hyper-V 虚拟机
> 慢的要死~

不妨试试win10自带的WLS2，比WLS提升不少，虚拟机，双系统什么的太臃肿了
WLS2还支持升级内核，1804可以升级到1910

**Comment by amilys** [comment]
debian10 也可以

**Comment by amilys** [comment]
> > 用 Ubuntu 18.04 LTS Desktop 版本编译了半年多了
> > 一直很稳定
> > 用的是笔记本电脑 Win10 + Ubuntu 双系统
> > 缺省进入Win10
> > 需要编译时，重启切换到 Ubuntu
> > 亲测建议：
> > 不要用 Win10 里面的 Hyper-V 虚拟机
> > 慢的要死~
> 
> 不妨试试win10自带的WLS2，比WLS提升不少，虚拟机，双系统什么的太臃肿了
> WLS2还支持升级内核，1804可以升级到1910

win的linux子系统文件不分大小写，容易出错

**Comment by eskimokk** [comment]
> > > 用 Ubuntu 18.04 LTS Desktop 版本编译了半年多了
> > > 一直很稳定
> > > 用的是笔记本电脑 Win10 + Ubuntu 双系统
> > > 缺省进入Win10
> > > 需要编译时，重启切换到 Ubuntu
> > > 亲测建议：
> > > 不要用 Win10 里面的 Hyper-V 虚拟机
> > > 慢的要死~
> > 
> > 
> > 不妨试试win10自带的WLS2，比WLS提升不少，虚拟机，双系统什么的太臃肿了
> > WLS2还支持升级内核，1804可以升级到1910
> 
> win的linux子系统文件不分大小写，容易出错

亲测wsl（ubuntu 18.04 LTS）编译可用
