### ISSUE TITLE
请求提供精简的defconfig选项

### ISSUE THREAD

**Issue by z5n0w** [coolsnowwolf/lede#324]
我只是想给路由添加sfe驱动，提高nat效率
默认选上了adbyby ss 以及一大堆用不上的功能
除了sfe我需要的仅仅是
像image builder那样的基础功能
Current Target: "ar71xx (Generic)"
Default Packages: base-files libc libgcc busybox dropbear mtd uci opkg netifd fstools uclient-fetch logd kmod-gpio-button-hotplug swconfig kmod-ath9k wpad-mini uboot-envtools dnsmasq iptables ip6tables ppp ppp-mod-pppoe firewall odhcpd odhcp6c
Available Profiles:

Default:
    Default Profile (all drivers)
    Packages: kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-ledtrig-usbport

**Comment by ZeaKyX** [comment]
请问有解决吗

**Comment by hcym** [comment]
就是lncloud目录里面target文件改动，改完再删除.config，然后再重新makemenu就行了，也是论坛学的，一直都在用，不然功能实在太多太多
