### ISSUE TITLE
Adbyby plus+ 当运行模式选为手动代理时 客户端过滤模式设置失效

### ISSUE THREAD

**Issue by JeremyPeng** [coolsnowwolf/lede#3240]
adbyby plus+里依据文字理解，运行模式选为手动代理，在客户端过滤模式设置里添加设备行为应该是可以生效的，但实际上是没有作用的，必须要把运行模式设置为Plus+或者全过滤，客户端过滤模式才生效，是不是bug？
![2020-02-21 14 44 18](https://user-images.githubusercontent.com/4402112/75010675-aa885b00-54b8-11ea-9a04-b61bf5aeaf43.jpg)

**Comment by coolsnowwolf** [comment]
就是这样设计的，手动 = 全手动设置代理，不会生成代理规则

**Comment by JeremyPeng** [comment]
如果希望实现其他设备都不使用过滤，只有指定设备启用过滤，貌似就无法配置了...
