### ISSUE TITLE
希望恢复acrh17的 160MHZ支持 新版本无法开启了

### ISSUE THREAD

**Issue by oldyangyagn** [coolsnowwolf/lede#3248]
希望恢复acrh17的 160MHZ支持 新版本无法开启了 17的160是一个亮点 希望继续支持

**Comment by oldyangyagn** [comment]
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/4235745/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/4235746/default.txt)

**Comment by coolsnowwolf** [comment]
fix

**Comment by LeeMenHin** [comment]
> fix

最新编译的在开启160mhz后，5g就会连接不上，手机电脑都少
