### ISSUE TITLE
编译多次，出现不同的情况

### ISSUE THREAD

**Issue by yespy** [coolsnowwolf/lede#3253]
开全局科学上网，为啥还是会有的访问失败

1：实际是可以访问git.openwrt.org这个地址的
curl: (35) Unknown SSL protocol error in connection to mirror2.openwrt.org:443
Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'ustream-ssl-2018-07-30-23a3f283'...
fatal: unable to access 'https://git.openwrt.org/project/ustream-ssl.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
make[3]: *** [/home/rucent/lede/dl/ustream-ssl-2018-07-30-23a3f283.tar.xz] Error 128
make[3]: Leaving directory `/home/rucent/lede/package/libs/ustream-ssl'
time: package/libs/ustream-ssl/openssl/compile#0.13#0.02#3.09
make[2]: *** [package/libs/ustream-ssl/compile] Error 2
make[2]: Leaving directory `/home/rucent/lede'
make[1]: *** [/home/rucent/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/rucent/lede'
make: *** [world] Error 2
rucent@ubuntu:~/lede$
====================================================================
2：
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.sourceforge.net/boost/boost/1.71.0/boost_1_71_0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 95.4M  100 95.4M    0     0  2440k      0  0:00:40  0:00:40 --:--:-- 2283k
Could not generate file hash
make[3]: *** [/home/rucent/lede/dl/boost_1_71_0.tar.bz2] Error 255
make[3]: Leaving directory `/home/rucent/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#1.38#1.72#45.65
make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
make[2]: Leaving directory `/home/rucent/lede'
make[1]: *** [/home/rucent/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/rucent/lede'
make: *** [world] Error 2
rucent@ubuntu:~/lede$
===============================================================
3：
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 95.4M  100 95.4M    0     0  8126k      0  0:00:12  0:00:12 --:--:-- 13.0M
Could not generate file hash
make[3]: *** [/home/rucent/lede/dl/boost_1_71_0.tar.bz2] Error 255
make[3]: Leaving directory `/home/rucent/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#1.34#1.40#17.53
make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
make[2]: Leaving directory `/home/rucent/lede'
make[1]: *** [/home/rucent/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/rucent/lede'
make: *** [world] Error 2
rucent@ubuntu:~/lede$ Could not generate file hash
make[3]: *** [/home/rucent/lede/dl/boost_1_71_0.tar.bz2] Error 255
make[3]: Leaving directory `/home/rucent/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#1.34#1.40#17.53
make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
make[2]: Leaving directory `/home/rucent/lede'
make[1]: *** [/home/rucent/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/rucent/lede'
make: *** [world] Error 2
Could: command not found
rucent@ubuntu:~/lede$ make[3]: *** [/home/rucent/lede/dl/boost_1_71_0.tar.bz2] Error 255
make[3]:: command not found
rucent@ubuntu:~/lede$ make[3]: Leaving directory `/home/rucent/lede/feeds/packages/libs/boost'
> time: package/feeds/packages/boost/host-compile#1.34#1.40#17.53
> make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
> make[2]: Leaving directory `/home/rucent/lede'
> make[1]: *** [/home/rucent/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
> make[1]: Leaving directory `/home/rucent/lede'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 5: syntax error: unexpected end of file
make[3]:: command not found
rucent@ubuntu:~/lede$ make: *** [world] Error 2
No command 'make:' found, did you mean:
 Command 'make' from package 'make' (main)
 Command 'makeg' from package 'xutils-dev' (main)
make:: command not found

**Comment by hyird** [comment]
dl的问题就自行下载 放在dl文件夹就行了
