### ISSUE TITLE
服务器端BBR 在透明代理的情况下不生效吗？

### ISSUE THREAD

**Issue by crabhit** [coolsnowwolf/lede#3257]
服务器端打开了BBR
路由器上用的SSR Plus+
似乎BBR的加速效果并没有生效，在路由器上只能跑到70Mbps
如果直接在电脑上跑小火箭能跑到400Mbps

**Comment by JeremyPeng** [comment]
这和路由器开启bbr有什么关系…难道你windows的 pc能开bbr？还是哪个客户端能修改系统的tcp链接模式了？bbr只需要在服务器节点开启有实际效果，客户端开启基本没有什么实际价值。
v2ray需要CPU的计算能力，x86软路由，可以接近pc表现。

**Comment by EnnawYang** [comment]
路由器性能很好吗？

**Comment by crabhit** [comment]
> 你的硬路由器性能很好吗？跟pc比？
硬路由虽然不支持AES指令 但是路由的CPU并没有跑满 在50%左右
