### ISSUE TITLE
有没有人知道这是怎么回事啊？？

### ISSUE THREAD

**Issue by ppp47** [coolsnowwolf/lede#3266]
https://whoer.net/zh#
同一个节点在pc上使用代理软件与在op路由器上使用，怎么会出现两种DNS检测结果？？？
还是说我的路由器设置的有问题。

在pc使用
![2](https://user-images.githubusercontent.com/59086679/75090116-bb110200-559a-11ea-9e49-5f298f99a68a.PNG)
![1](https://user-images.githubusercontent.com/59086679/75090119-c19f7980-559a-11ea-96da-a054e8b6151a.PNG)

在op路由器上使用
![3](https://user-images.githubusercontent.com/59086679/75090129-daa82a80-559a-11ea-8e2d-bde5a1fd98db.PNG)
![4](https://user-images.githubusercontent.com/59086679/75090188-67eb7f00-559b-11ea-9516-20dc2db5344d.PNG)

**Comment by monsterzzzz** [comment]
感觉是DNS解析问题，如果全通过代理解析IP，就不会出现这个

**Comment by ppp47** [comment]
> 感觉是DNS解析问题，如果全通过代理解析IP，就不会出现这个

我不懂，请问具体该怎样操作呢？

**Comment by 9l** [comment]
你直接用路由器上网的么？
电脑上dns没问题就行了，别自寻烦恼

**Comment by ppp47** [comment]
> 你直接用路由器上网的么？
> 电脑上dns没问题就行了，别自寻烦恼

我是把op路由器连上电脑进行上网的

**Comment by ppp47** [comment]
> https://whoer.net/zh#
> 同一个节点在pc上使用代理软件与在op路由器上使用，都是全局代理,怎么会出现两种DNS检测结果？？？
> 还是说我的路由器设置的有问题。
> 
> 在pc使用
> ![2](https://user-images.githubusercontent.com/59086679/75090116-bb110200-559a-11ea-9e49-5f298f99a68a.PNG)
> ![1](https://user-images.githubusercontent.com/59086679/75090119-c19f7980-559a-11ea-96da-a054e8b6151a.PNG)
> 
> 在op路由器上使用
> ![3](https://user-images.githubusercontent.com/59086679/75090129-daa82a80-559a-11ea-8e2d-bde5a1fd98db.PNG)
> ![4](https://user-images.githubusercontent.com/59086679/75090188-67eb7f00-559b-11ea-9516-20dc2db5344d.PNG)

**Comment by 9l** [comment]
你路由开全局模式试试

**Comment by ppp47** [comment]
> 你路由开全局模式试试

是开全局模式的
![11](https://user-images.githubusercontent.com/59086679/75110434-1ad5de80-5669-11ea-8d4a-461e382b46fa.PNG)
