### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#3270]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for alsa-utils:
 * 	libncursesw6.1
 * opkg_install_cmd: Cannot install package alsa-utils.
make[2]: *** [package/install] Error 255

make[2]: Leaving directory `/home/widly/lede'

make[1]: *** [/home/widly/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2

make[1]: Leaving directory `/home/widly/lede'

make: *** [world] 错误 2

上面是报错信息，请问大佬这是什么原因导致，如何解决？谢谢！

**Comment by SharerMax** [comment]
#3262
