### ISSUE TITLE
大佬啊，brook无法使用

### ISSUE THREAD

**Issue by shiyindebcd** [coolsnowwolf/lede#328]
斐讯k3，ubuntu16.04，编译时在luci里面加了brook，其它都没动
编译好后brook无法连接，brook是用的群里的一键 代码部署的，服务器是谷歌云
brook手机端和windows端能正常使用，就路由端连不上
重新编译了三遍还是没用

**Comment by dexlx** [comment]
x86编译刷入虚拟机也无法使用

**Comment by 505575853** [comment]
brook 默认禁止启动的吧

**Comment by dexlx** [comment]
@505575853  试过了么？

**Comment by wheretoteardown** [comment]
开启FPU模拟了？

**Comment by lxyza** [comment]
输入地址和密码，但是还是不能上google，什么情况

**Comment by lxyza** [comment]
我还在用呢

coolsnowwolf <notifications@github.com> 于2018年10月6日周六 下午1:34写道：
