### ISSUE TITLE
后端pptp无法连接，即使防火墙已经放开gre协议，求大佬回复！谢谢！

### ISSUE THREAD

**Issue by zouyujia** [coolsnowwolf/lede#329]
除了pptp问题，之前听说有机场大佬用的都是$$加obfs插件，从来没有封过，发现自己如果安装插件无法运行，提示缺少libmcrypt.so.0，求大佬的解决方案，按照这个里面的教程安装的https://cokebar.info/archives/664

**Comment by LGA1150** [comment]
这是 4.9 分支的已知 bug

**Comment by LGA1150** [comment]
更新解决方法：
编译时选上 kmod-ipt-raw 内核模块
将以下命令复制到自定义防火墙规则中
`iptables -t raw -A PREROUTING -p tcp --dport 1723 -j CT --helper pptp`

**Comment by LGA1150** [comment]
又爬了一下 LEDE 论坛的楼，发现最简单的解决方法是：
编译时选择 kmod-nf-nathelper-extra
添加 `net.netfilter.nf_conntrack_helper=1` 到 /etc/sysctl.conf
