### ISSUE TITLE
上个版本编译正常，今天更新代码出现新的问题。

### ISSUE THREAD

**Issue by feizaibufei** [coolsnowwolf/lede#3291]
Collected errors:
 * check_data_file_clashes: Package ntfs-3g wants to install file /home/openwrt/lede/build_dir/target-aarch64_generic_musl/root-armvirt/sbin/mount.ntfs
	But that file is already provided by package  * antfs-mount
 * opkg_install_cmd: Cannot install package automount.
 * check_data_file_clashes: Package ntfs-3g wants to install file /home/openwrt/lede/build_dir/target-aarch64_generic_musl/root-armvirt/sbin/mount.ntfs
	But that file is already provided by package  * antfs-mount
 * opkg_install_cmd: Cannot install package ntfs-3g.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:108: /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:227：world] 错误 2

**Comment by AmadeusGhost** [comment]
不选上`antfs-mount`，或者`rm .config`重新选

**Comment by d975xbx** [comment]
![antfs](https://user-images.githubusercontent.com/21034764/75109500-e78e5200-565e-11ea-9743-77b3b06fe0b0.png)
找不到的话，打开.config
is not set然后注释掉

**Comment by feizaibufei** [comment]
多谢

**Comment by you-mu** [comment]
个人经验
编译前 rm -rf ./tmp
如果报错不明朗,我就make clean , 然后再开始.

**Comment by FoxDring** [comment]
这是antfs-mount和ntfs-3g冲突，选前者。但如果ntfs-3g被锁定，需要取消Extra packages ---> automount，再回到Utilities ---> Filesystem 就可以取消ntfs-3g了。

**Comment by feizaibufei** [comment]
多谢@FoxDring

**Comment by txdywy** [comment]
同样问题，赞

feizaibufei <notifications@github.com> 于 2020年2月27日周四 下午7:48写道：
