### ISSUE TITLE
smb4在 mt7621上 编译失败

### ISSUE THREAD

**Issue by hyird** [coolsnowwolf/lede#3293]
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/sbin/eventlogadm (from bin/default/source3/utils/eventlogadm.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/sharesec (from bin/default/source3/utils/sharesec.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/ntlm_auth (from bin/default/source3/utils/ntlm_auth.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/dbwrap_tool (from bin/default/source3/utils/dbwrap_tool.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/testparm (from bin/default/source3/utils/testparm.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/net (from bin/default/source3/utils/net.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/mvxattr (from bin/default/source3/utils/mvxattr.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/bin/smbstatus (from bin/default/source3/utils/smbstatus.inst)
+ install /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/sbin/nmbd (from bin/default/source3/nmbd/nmbd.inst)
Waf: Leaving directory `/home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/bin/default'
'install' finished successfully (2m22.493s)
touch /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/.built
mkdir -p /home/hyird/lede/bin/targets/ramips/mt7621/packages /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-mipsel_24kc/samba4-libs/CONTROL /home/hyird/lede/staging_dir/target-mipsel_24kc_musl/pkginfo
install -d -m0755 /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-mipsel_24kc/samba4-libs/usr/lib
cp -fpR /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/lib/*.so* /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-mipsel_24kc/samba4-libs/usr/lib/
# rpath-install
cp -fpR /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-install/usr/lib/samba /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-mipsel_24kc/samba4-libs/usr/lib/
find /home/hyird/lede/build_dir/target-mipsel_24kc_musl/samba-4.11.6/ipkg-mipsel_24kc/samba4-libs -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package samba4-libs is missing dependencies for the following libraries:
libpam.so.0
make[2]: *** [Makefile:441: /home/hyird/lede/bin/packages/mipsel_24kc/base/samba4-libs_4.11.6-1_mipsel_24kc.ipk] Error 1
make[2]: Leaving directory '/home/hyird/lede/package/lean/samba4'
time: package/lean/samba4/compile#930.42#115.82#188.36
make[1]: *** [package/Makefile:113: package/lean/samba4/compile] Error 2
make[1]: Leaving directory '/home/hyird/lede'
make: *** [/home/hyird/lede/include/toplevel.mk:227：package/samba4/compile] 错误 2

自己也编译了  x64  能过

**Comment by hue715** [comment]
应该是没选择依赖libpam
