### ISSUE TITLE
新版本国内DNS UDP没有了

### ISSUE THREAD

**Issue by neverj1019** [coolsnowwolf/lede#3294]
刚更新完新PASSWALL固件后发现没法科学上网了，检查了下国内DNS UDP这栏没有了，是否默认用lan口的DNS解析国内地址了？换回之前的固件没问题

**Comment by d975xbx** [comment]
PASSWALL这个东东，lean的固件默认是没有的。建议问原作者。

**Comment by dolphinpaopao** [comment]
走错片场了，应该用的他人编译固件吧？请咨询发布者。

**Comment by Aes64X** [comment]
> 刚更新完新PASSWALL固件后发现没法科学上网了，检查了下国内DNS UDP这栏没有了，是否默认用lan口的DNS解析国内地址了？换回之前的固件没问题

老哥，出门右转打出租车，你这来的地名不对。
