### ISSUE TITLE
SSR+LAN访问控制问题

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#3296]
我在全局代理的LAN IP先了本机的IP地址,百度查IP时候,还是能显示电信IP.
![image](https://user-images.githubusercontent.com/41529838/75109995-71401e80-5663-11ea-86e9-a0f0e203c933.png)

![image](https://user-images.githubusercontent.com/41529838/75110011-8cab2980-5663-11ea-8d06-64f1981fe04f.png)

![image](https://user-images.githubusercontent.com/41529838/75110018-9fbdf980-5663-11ea-83de-4eb248393457.png)

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/75110065-3ee2f100-5664-11ea-8acf-d4a46340c236.png)
shi'c实测没问题

**Comment by 9l** [comment]
没毛病，网站trace你ip机制的问题，用全局模式就是正常的，用访问控制ip138就是能获得你的真实ip

**Comment by wafm0708** [comment]
刚刚修改配置的时候会有差不多10分钟的生效时间，整个访问控制都是一样的
