### ISSUE TITLE
付费QQ交流群

### ISSUE THREAD

**Issue by jfdnet** [coolsnowwolf/lede#3297]
看了一下才19个人
这样还有意义么？

**Comment by coolsnowwolf** [comment]
我的群没有这么少人的，基本都是满人 你可能加错了

**Comment by 9l** [comment]
进了李鬼群吧 呵呵

**Comment by hyird** [comment]
加错群了吧 ，大碉群天天炸

**Comment by shenzt68** [comment]
我被炸外来几次了

**Comment by jfdnet** [comment]
不好意思 大概搞错了
SSR-plus 比 passwall 稳定多了
还很搞笑的是 在passwall的群提到 SSR-plus 立马被踢出群了
那群主是有多脆弱

**Comment by phc1003** [comment]
> 不好意思 大概搞错了
> SSR-plus 比 passwall 稳定多了
> 还很搞笑的是 在passwall的群提到 SSR-plus 立马被踢出群了
> 那群主是有多脆弱
提到关键字了
