### ISSUE TITLE
概况-网络不能显示多WAN状态

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#3298]
我的宽带能四拨,在IPv4 WAN 状态里只能显示其中一个,怎样才能显示全部接口.
![imge](https://user-images.githubusercontent.com/41529838/75113790-a8c2c100-568b-11ea-806b-23747b70820b.png)

![image](https://user-images.githubusercontent.com/41529838/75113876-9006db00-568c-11ea-813b-8bd15a23b960.png)

**Comment by AmadeusGhost** [comment]
IPv4 WAN只会显示一个（物理上上的wan口），其它的是mwan

**Comment by 9l** [comment]
你这不就是显示的四个么，四个 pppoe

**Comment by 82kg** [comment]
> 你这不就是显示的四个么，四个 pppoe

他说是的在首页显示 所有WAN口信息

**Comment by tty228** [comment]
首页显示的话，替换掉 `/usr/lib/lua/luci/view/admin_status` 目录文件
[index.zip](https://github.com/coolsnowwolf/lede/files/4243363/index.zip)

**Comment by dengchan0416** [comment]
@AmadeusGhost 四个中其中还有一个是物理的WAN口联通的,一条电信3多拨,另一条联通1拨

**Comment by AmadeusGhost** [comment]
> @AmadeusGhost 四个中其中还有一个是物理的WAN口联通的,一条电信3多拨,另一条联通1拨

我知道你意思，但是IPv4 WAN这个地方是显示物理wan口的，其他是显示到mwan那，此项目默认屏蔽了mwan3在首页上的显示，楼上的dalao已经给你替换文件了

**Comment by dengchan0416** [comment]
@tty228 请问是这样吗?
![image](https://user-images.githubusercontent.com/41529838/75244820-73db7900-5807-11ea-8635-ad13cef6466d.png)

**Comment by wafm0708** [comment]
> 我的宽带能四拨,在IPv4 WAN 状态里只能显示其中一个,怎样才能显示全部接口.
> ![imge](https://user-images.githubusercontent.com/41529838/75113790-a8c2c100-568b-11ea-806b-23747b70820b.png)
> 
> ![image](https://user-images.githubusercontent.com/41529838/75113876-9006db00-568c-11ea-813b-8bd15a23b960.png)

请问多线多拨的插件是什么

**Comment by elfive** [comment]
> /usr/lib/lua/luci/view/admin_status

谢谢，不过你那个在最新的openwrt和luci下面似乎不会在首页->概况->IPv4 WAN 状态那里显示多WAN的信息。
按照这个[提交](https://github.com/openwrt/luci/commit/a13748d4145edd3edc70e462714a115f7c99470e)修改可以试试。
