### ISSUE TITLE
RTL8169驱动无法加载

### ISSUE THREAD

**Issue by Kotori-0912** [coolsnowwolf/lede#3299]
今天git pull后编译出来的版本无法加载RTL8169驱动，编译时已经确定kmod-r8169是勾选上的，编译过程无任何错误，不保留配置更新后没有看到加载8169驱动信息，使用ifconfig查看网络信息也只有lo接口无eth接口

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/75116289-b3885080-56a1-11ea-8ca2-911ecda221ad.png)
默认选择就已经有驱动

**Comment by Kotori-0912** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/75116289-b3885080-56a1-11ea-8ca2-911ecda221ad.png)
> 默认选择就已经有驱动

我用KVM虚拟机直通RTL8169网卡但是无法加载，上一个版本是能正常加载
![Screenshot_20200224-012608](https://user-images.githubusercontent.com/25550007/75116709-05cb7080-56a6-11ea-83e4-6127180796fa.jpg)
![Screenshot_20200224-012858](https://user-images.githubusercontent.com/25550007/75116714-15e35000-56a6-11ea-95ab-75addece9d1f.jpg)

**Comment by hyird** [comment]
r8169-firmware | 20191215-1 | 22827 | RealTek RTL8169 firmware
你这个装了么

**Comment by Kotori-0912** [comment]
> r8169-firmware | 20191215-1 | 22827 | RealTek RTL8169 firmware
> 你这个装了么

r8169-firmware这个有安装到

**Comment by Kotori-0912** [comment]
删除全部源代码重新拉去后再次编译，情况解决，可能与上次强行覆盖导致源代码有问题
