### ISSUE TITLE
koolproxy全局模式与ssr冲突？

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#330]
如题。单开koolproxy全局模式或ssr代理，并无问题。同时开，mac上网正常，但iphone不能上网。如果开koolproxy黑名单模式，同时开ssr代理，则无问题。why?

**Comment by d975xbx** [comment]
2.如果你自认为 Koolshare 论坛或者其固件的脑残粉，本人不欢迎你使用本源代码。所以如果你是，那么使用过程中遇到任何问题本人概不回应。

**Comment by uglee** [comment]
如果你自认为 Koolshare 论坛或者其固件的脑残粉，本人不欢迎你使用本源代码。所以如果你是，那么使用过程中遇到任何问题本人概不回应。～～～～～～～～～～～

**Comment by uglee** [comment]
iptables慢慢捋吧，都是这里冲突的锅。
