### ISSUE TITLE
精简无线驱动后出现依赖不存在的提示

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#3303]
因为我的软路由不支持无线，所以将所有无线驱动都不勾选，make menuconfig后有如下提示：
WARNING: Makefile 'package/kernel/mac80211/Makefile' has a dependency on 'hostapd-common', which does not exist
取消勾选无线驱动后，Network里的wpad、hostapd-common会自动同步取消勾选，为什么还会出现上述提示？

**Comment by gpeditmsc1986** [comment]
我这边没有出现这样的问题，一直编译都没有无线驱动，可能你自己选错了，这个是我的配置文件。
[配置.txt](https://github.com/coolsnowwolf/lede/files/4243604/default.txt)

**Comment by lariboo** [comment]
> 我这边没有出现这样的问题，一直编译都没有无线驱动，可能你自己选错了，这个是我的配置文件。
> [配置.txt](https://github.com/coolsnowwolf/lede/files/4243604/default.txt)

感谢大佬提供资料，我自查下原因所在吧。谢谢！
