### ISSUE TITLE
openwrt好像没有ac的功能，大佬有没有想过增加此类功能

### ISSUE THREAD

**Issue by ITdesk01** [coolsnowwolf/lede#3304]
https://github.com/ycsunjane/acctl
Openwrt ac 控制器(acctl)， 包含服务端和客户端两大块。支持以下特性:

同一网段，二层发现，自动配置ip
自动二层/三层发送控制信息
二层主动探测网络中ap，可接管其他ac控制ap
客户端主动链接，并保持长链接

**Comment by hzjnet** [comment]
这种功能支持

**Comment by 4860575** [comment]
那个项目好久没有维护了。也不知道还能不能用。

**Comment by tanst** [comment]
这是路由器应该有的功能

**Comment by 9l** [comment]
集客ac

**Comment by ITdesk01** [comment]
> 这种功能支持

暂时没有发现，我现在的想法，openwrt能够有个ac的功能，比如主路由加上ac插件，其他ap刷ap插件，刷了ap插件的机器可以由ac这台机器统一管理

**Comment by mjyhj** [comment]
好主意，谁来写？
