### ISSUE TITLE
trojan只能工作在全局模式

### ISSUE THREAD

**Issue by shake** [coolsnowwolf/lede#3305]
我这边无论如何设置，trojan只能工作在全局模式，GFW和大陆IP地址都无效。

https://www.bandwh.com/net/51.html

遇到的问题和上面文章一样，只能全局。我使用的是3天前的代码build 。

**Comment by 9l** [comment]
我这没问题

**Comment by shake** [comment]
我是采用旁路由的模式，当采用GFW模式的时候，无法打开国内的网站。很邪门。难道这个还和使用方式有关，主路由没问题？

**Comment by EnnawYang** [comment]
> 我是采用旁路由的模式，当采用GFW模式的时候，无法打开国内的网站。很邪门。难道这个还和使用方式有关，主路由没问题？

那应该是你接口没设置好

**Comment by js882829** [comment]
恢复出厂设置 或者重刷 不要保留配置

EnnawYang <notifications@github.com> 于 2020年2月24日周一 18:48写道：

**Comment by hcym** [comment]
单臂路由要搞定vlan，和普通路由一样用就行了，不然的话活受罪

**Comment by CYaNu** [comment]
其实旁路由/单臂路由 需要添加WAN口 WAN口和LAN是一个物理接口 LAN口关闭桥接 WAN口不配置协议 防火墙里面加个LAN to LAN规则 就行了

**Comment by shake** [comment]
谢谢大家指导。重新刷机，对比设置，应该是lan接口，把桥接去掉，就可以了。后续好好整理一下。
