### ISSUE TITLE
用safari或chrome打开管理页面不显示功能栏

### ISSUE THREAD

**Issue by deviclee** [coolsnowwolf/lede#3309]
用safari或chrome打开管理页面不显示功能栏。 无法打开功能栏进行选择性操作。特别是遇到需要切换节点，手机无法支撑。

**Comment by yangjiey2k** [comment]
点击openwrt logo

**Comment by badcrazy** [comment]
主题用material，我一直用这个，bootstrap对移动设备太不友好了
