### ISSUE TITLE
DHCP/DNS-高级设置-禁止解释 IPv6 DNS 记录

### ISSUE THREAD

**Issue by YanD006888** [coolsnowwolf/lede#3310]
禁止解释 IPv6 DNS 记录应该是解析不是解释

大佬字打错了  望更改

**Comment by YanD006888** [comment]
没有看到smartdns插件了呢  解析国内用呢，不单独开贴了   望加上   每次编译都需要拖入也很麻烦

**Comment by FoxDring** [comment]
请教如何拖入编译smartdns？
