### ISSUE TITLE
请求添加C301 32M固件支持 旧版本的完美补丁在新版中有BUG

### ISSUE THREAD

**Issue by y0IkE** [coolsnowwolf/lede#3314]
旧版完美C301 32M双flash固件补丁地址：https://www.right.com.cn/forum/thread-148928-1-1.html
自己尝试在您的版本中添加相应补丁代码，可以成功编译跟运行，但有几个bug无法修复：

BUG：
1、空闲空间百分比显示不准确
2、2.4g wifi设备重启后无法加载（刷固件第一次重启是正常的）

还请作者修改并添加完美版32M双flash固件补丁

**Comment by lcq3328** [comment]
表示关注，隔离期在家里折腾C301，16M的flash刷诸多模块以及力不从心了

**Comment by y0IkE** [comment]
我有自己搬砖代码编译好的32M固件：https://www.right.com.cn/forum/thread-2933344-1-1.html

就是有实际空间百分比显示不准确的BUG

**Comment by lcq3328** [comment]
哈哈，原来也是才折腾的固件，我说前几天怎么没搜搜到这个帖子，我去体验戏下

**Comment by cnqdmght** [comment]
> 我有自己搬砖代码编译好的32M固件：https://www.right.com.cn/forum/thread-2933344-1-1.html
> 
> 就是有实际空间百分比显示不准确的BUG

能更新下固件，增加个unpn和 zerotier 么
