### ISSUE TITLE
更新的dockerman 0.3.0不对劲

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#3315]
未分类到services下
自动格式化脚本没了
英文！
可能内存显示错误

**Comment by KFERMercer** [comment]
https://github.com/coolsnowwolf/lede/pull/3316

**Comment by lloyd18** [comment]
> #3316

PR没问题了，但是有个旧版luci的bug，导致内存显示不正确，我的4G内存就显示2G
https://github.com/openwrt/luci/issues/3293#issue-521972274
