### ISSUE TITLE
编译选中最新的解锁网易云音乐，就会报错，

### ISSUE THREAD

**Issue by silime** [coolsnowwolf/lede#3317]
![72BB9BFA-52CA-42FF-8247-2352E9F0DA0F](https://user-images.githubusercontent.com/60662669/75213173-4b7e5b00-57c4-11ea-84f7-7c7675338fb6.jpeg)
编译到node-v12.15.0就报错了

**Comment by mjyhj** [comment]
更新依赖
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib linux-libc-dev:i386

不行再make clean

**Comment by waterun** [comment]
> 更新依赖
> sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib linux-libc-dev:i386
> 
> 不行再make clean

Mj牛，我也折腾了半天，还以为是bug
