### ISSUE TITLE
有一个疑问，为啥upnp无效

### ISSUE THREAD

**Issue by BNO1GLEAM** [coolsnowwolf/lede#3320]
迅雷可以自己添加转发进去，比特彗星和tran就不行，要手动在防火墙制定端口来进行转发，感觉好麻烦

**Comment by coolsnowwolf** [comment]
因为这个版本的 upnp 就是兼容迅雷的啊

迅雷用的是老版本 upnp v1，兼容了迅雷就不兼容其他了

**Comment by BNO1GLEAM** [comment]
> 因为这个版本的 upnp 就是兼容迅雷的啊
> 
> 迅雷用的是老版本 upnp v1，兼容了迅雷就不兼容其他了

原来是这样啊，那就要手动在防火墙添加端口转发咯

**Comment by R3pl4c3r** [comment]
你可以试试qBittorrent，UPnP可以自动转发

**Comment by d975xbx** [comment]
用qBittorrent或者主路由用ros，把upnp交给ros

**Comment by eaglesas** [comment]
我拿来挂赚钱宝和小融，upnp不能用，加防火墙也不能用，但是插威联通加防火墙后就能用，哪位大佬有没有可以解决的办法？

**Comment by R3pl4c3r** [comment]
> 我拿来挂赚钱宝和小融，upnp不能用，加防火墙也不能用，但是插威联通加防火墙后就能用，哪位大佬有没有可以解决的办法？

你直接端口映射不就完了，人家用啥端口你映射啥端口就好了啊

**Comment by R3pl4c3r** [comment]
> 我拿来挂赚钱宝和小融，upnp不能用，加防火墙也不能用，但是插威联通加防火墙后就能用，哪位大佬有没有可以解决的办法？

你直接端口映射不就完了，人家用啥端口你映射啥端口就好了啊
