### ISSUE TITLE
疑似BUG报告：使用自建v2ray ws tls时速度很慢

### ISSUE THREAD

**Issue by hahaher123** [coolsnowwolf/lede#3322]
我在使用lean大的ssr plus+大陆白名单模式时发现用自建的v2ray ws tls时速度很慢，使用其他科学插件看youtube时大概在1W3左右，使用ssr plus+时一直只有2K上下，试过很多次都是这样。

今天我突发异想，把v2ray使用的域名加入到访问控制的不走代理域名里，看youtube的速度变得和使用其他科学插件一致，同样是1W3左右。

不知是否在用大陆白名单+v2ray ws tls模式时需要一个排除机制来避免冲突？或者有其他什么原因导致异常。

**Comment by coolsnowwolf** [comment]
直接 chrome 浏览器关闭 quic 即可

**Comment by hahaher123** [comment]
> 直接 chrome 浏览器关闭 quic 即可

lean大，我chrome的quic是关闭的
