### ISSUE TITLE
2020.02.25编译选中dockerman注意事项及未知问题

### ISSUE THREAD

**Issue by R3pl4c3r** [coolsnowwolf/lede#3325]
![Snipaste_2020-02-25_14-18-38](https://user-images.githubusercontent.com/30682790/75220197-d027a400-57d9-11ea-8e1b-f8f61bb673fd.png)
如图，已经编译好的版本，选中dockerman还不行，还需选中docker-ce，目前未测试。下面这个是2020.02.24编译选择的diffconfig
[diffconfig.txt](https://github.com/coolsnowwolf/lede/files/4248356/diffconfig.txt)
下面这个是2020.02.25编译选择的diffconfig
[diffconfig.txt](https://github.com/coolsnowwolf/lede/files/4248364/diffcon.txt)
`make menuconfig`选择的一模一样，但是今天的比昨天的少了40行，其他问题未知。

**Comment by KFERMercer** [comment]
https://github.com/coolsnowwolf/lede/commit/d1e791952adf40c2faa4126988d2b2d4d595e81d

**Comment by R3pl4c3r** [comment]
#3321 估计解决了，看 @KFERMercer 怎么说
