### ISSUE TITLE
ssr plus+ 订阅无法同步问题及初步判断

### ISSUE THREAD

**Issue by js882829** [coolsnowwolf/lede#3329]
ssr plus+ 订阅无法同步问题及初步判断
 问题描述：SSR订阅无法更新
重现步骤：
   1。添加一个SSR服务器节点，别名留空。
   2。删除其他SSR订阅
   3。更新订阅
   4。列表中无新订阅添加，日志中能看到下载了所有订阅节点。
问题分析：
  猜测是程序在获取节点并进行比对的时候，对别名为空的节点判断造成了异常。导致整个流程结束。

**Comment by coolsnowwolf** [comment]
fix
