### ISSUE TITLE
psg1208编译错误

### ISSUE THREAD

**Issue by untitledtxt** [coolsnowwolf/lede#3336]
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:35: recipe for target '/home/antony/lede/build_dir/host/gmp-6.1.2/.configured' failed
make[3]: *** [/home/antony/lede/build_dir/host/gmp-6.1.2/.configured] Error 1
make[3]: Leaving directory '/home/antony/lede/tools/gmp'
time: tools/gmp/compile#6.29#3.33#9.75
tools/Makefile:161: recipe for target 'tools/gmp/compile' failed
make[2]: *** [tools/gmp/compile] Error 2
make[2]: Leaving directory '/home/antony/lede'
tools/Makefile:159: recipe for target '/home/antony/lede/staging_dir/target-mipsel_24kc_musl/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynnynynnyyyynynyyy' failed
make[1]: *** [/home/antony/lede/staging_dir/target-mipsel_24kc_musl/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynnynynnyyyynynyyy] Error 2
make[1]: Leaving directory '/home/antony/lede'
/home/antony/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

修改过luci列表，make clean 之后重新执行也是同样报错

**Comment by lizhenglin2002** [comment]
我这X86的经常编译了第一次，第二次就不行了，显示ERROR2

**Comment by royalwei** [comment]
export FORCE_UNSAFE_CONFIGURE=1

**Comment by royalwei** [comment]
出错输入这个再继续编译就行

**Comment by lizhenglin2002** [comment]
> 错误输入这个再继续编译就行

麻烦帮我看看这是什么原因的错误
![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307156-fc006380-5885-11ea-8672-db09951d0168.jpg)

**Comment by royalwei** [comment]
> > 错误输入这个再继续编译就行
> 
> 麻烦帮我看看这是什么原因的错误
> ![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307156-fc006380-5885-11ea-8672-db09951d0168.jpg)
删掉.config重新编译，因为大雕某次更新中返回了ntfs-3g，不再用antfs-mount了

**Comment by lizhenglin2002** [comment]
> > > 错误输入这个再继续编译就行
> > 
> > 
> > 麻烦帮我看看这是什么原因的错误
> > ![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307156-fc006380-5885-11ea-8672-db09951d0168.jpg)
> > 删掉.config重新编译，因为大雕某次更新中返回了ntfs-3g，不再用antfs-mount了

请问是在哪里删除

**Comment by royalwei** [comment]
> > > > 错误输入这个再继续编译就行
> > > 
> > > 
> > > 麻烦帮我看看这是什么原因的错误
> > > ![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307156-fc006380-5885-11ea-8672-db09951d0168.jpg)
> > > 删掉.config重新编译，因为大雕某次更新中返回了ntfs-3g，不再用antfs-mount了
> 
> 请问是在哪里删除

rm .config

**Comment by lizhenglin2002** [comment]
> > > > > 错误输入这个再继续编译就行
> > > > 
> > > > 
> > > > 麻烦帮我看看这是什么原因的错误
> > > > ![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307156-fc006380-5885-11ea-8672-db09951d0168.jpg)
> > > > 删掉.config重新编译，因为大雕某次更新中返回了ntfs-3g，不再用antfs-mount了
> > 
> > 
> > 请问是在哪里删除
> 
> rm .config

好的谢谢
