### ISSUE TITLE
新版小娱XY-C5固件 重启概率性丢失配置

### ISSUE THREAD

**Issue by chenyangcyx** [coolsnowwolf/lede#3338]
2020.02.25编译的小娱的XY-C5固件（MediaTek Ralink MIPS - MT7621 - XiaoYu XY-C5），刷上之后进行设置，有概率丢失设置，在web界面重启之后一切恢复原始设置

我的操作是这样的，先修改了下登录密码，然后VLAN里面添加了几个VLAN（因为要多拨），再在“接口”添加了几个WAN……最后配置MWAN3。之后，我重启了下路由器，发现一切配置恢复成原来的了。于是我按照之前的操作每走一步重启下确保保存了配置，有时候会在设置VLAN那一步重启后丢失，有时候是添加了WAN接口重启就丢失的，有概率性。

无奈之下，刷了自己在02.18编译的固件，一切都没有问题。
怀疑是这之间的某次变动修改了什么功能导致的？不知道有没有人有相同的问题。

**Comment by bigbighill** [comment]
新三路由用的2.25版本编译的也有类似丢失配置的问题，折腾死人了。

**Comment by coolsnowwolf** [comment]
没看到日志

**Comment by nicepass** [comment]
C5+1
设置了LAN口的IP地址然后重启，所有设置还原成初始原始状态，配置没有保存。

**Comment by mitsukileung** [comment]
K2P断电重启，有时候不能启动，就算启动成功也会回到复位状态。

**Comment by coolsnowwolf** [comment]
没看到日志 ，关闭了
