### ISSUE TITLE
c301开启ssr v2ray后luci界面卡死，cpu占用超高

### ISSUE THREAD

**Issue by y0IkE** [coolsnowwolf/lede#3341]
c301开启ssr v2ray后luci界面卡死，cpu占用超高

无法打开路由器后台界面或打开很慢，多次后发现代理开启后luci进程占用cpu超高

打开后台地址显示：
Bad Gateway
The process did not produce any response

**Comment by badcrazy** [comment]
9344这么孱弱的性能你就放过他吧

**Comment by y0IkE** [comment]
都超频到了750

**Comment by y0IkE** [comment]
问题已经找到：开ssr时luci-app-sfe  #Turbo ACC网络加速（flowoffload二选一） 插件会导致CPU耗尽问题

**Comment by coolsnowwolf** [comment]
内存不足 请升级内存为 128M+

**Comment by y0IkE** [comment]
c301本身就是128M内存
