### ISSUE TITLE
为啥总是第二次编译就失败

### ISSUE THREAD

**Issue by lizhenglin2002** [coolsnowwolf/lede#3348]
![photo_2020-02-26_09-02-53](https://user-images.githubusercontent.com/22312968/75307201-1f2b1300-5886-11ea-9a2f-e0f07f263b14.jpg)
这是分支passwall的编译，总是第一次编译就成功，第二次就失败。Lean主源码也是这问题

**Comment by coolsnowwolf** [comment]
写着呢 不能同时选两个ntfs驱动

**Comment by lizhenglin2002** [comment]
> 写着呢 不能同时选两个ntfs驱动

好的，谢谢解答

**Comment by FoxDring** [comment]
这是antfs-mount和ntfs-3g冲突，选前者。但如果ntfs-3g被锁定，需要取消Extra packages ---> automount，再回到Utilities ---> Filesystem 就可以取消ntfs-3g了。

**Comment by lizhenglin2002** [comment]
> 这是antfs-mount和ntfs-3g冲突，选前者。但如果ntfs-3g被锁定，需要取消Extra packages ---> automount，再回到Utilities ---> Filesystem 就可以取消ntfs-3g了。

OK，已经解决
