### ISSUE TITLE
关于新版 解锁网易云音乐免费白嫖 FLAC 无损音乐的说明

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#3358]
1. 必须更新 feeds 后编译，Node 必须为 10+ 版本，目前已经升级到 v12.15
2. FLAC 音源目前只支持 酷我 和 咪咕 ，但 咪咕  的匹配歌名经常出错
3. 这个版本的 Node 比较吃内存，路由器内存剩余少于 128MB+ 的路由器慎重。。。

PS：无损就是好

![image](https://user-images.githubusercontent.com/31687149/75342147-ce8cd780-58d0-11ea-9743-4efd54eb7626.png)

![image](https://user-images.githubusercontent.com/31687149/75342185-de0c2080-58d0-11ea-8453-79fd89b1b143.png)

**Comment by lphgor** [comment]
可以更新一下go版，也支持酷我无损了

**Comment by wspzf** [comment]
解锁网易云音乐有三个插件，用哪个呢？
现在默认是mini

**Comment by shu0802** [comment]
ios手机端支持效果如何

**Comment by mjyhj** [comment]
> 解锁网易云音乐有三个插件，用哪个呢？
> 现在默认是mini

标准版是本地node解锁
GO版是适合K3这种不支持FPU的
MINI版适合8M,16M这种小固件的，在大佬上的公益服务器解锁，本地代理过去

**Comment by zgs360** [comment]
怎么使用啊？windwos客户端端口设置多少？

**Comment by xxp2277** [comment]
@coolsnowwolf 请问有办法将所有歌曲（即网易云音乐中未变灰的低音质歌曲）替换为无损么？

**Comment by 4593645** [comment]
请问那个menuconfig 选项是解锁网易云？

**Comment by xxp2277** [comment]
> 
> 
> 请问那个menuconfig 选项是解锁网易云？

这3个都是luci-app-unblockmusic luci-app-unblockneteasemusic-go luci-app-unblockneteasemusic-mini
