### ISSUE TITLE
关于update_dnspod_cn.sh IPv6和IPv4同时解析一个域名时的问题

### ISSUE THREAD

**Issue by CyangHH** [coolsnowwolf/lede#3360]
最近路由器可以获得 ipv6 了，打算做一下 ipv6 的动态解析

因为 ipv4 用的 dnspod 解析，打算在此基础之上修改

发现 ipv4 和 ipv6 不能同时设定解析？

ipv4 解析更新后再修改 ipv6，之前的 ipv4 就被直接替换掉了

在控制台面板直接设定是可行的不存在这个问题

我的姿势不对？

ipv4 解析使用 https://dnsapi.cn/Record.Ddns 指定 A 记录 record_type=A

ipv6 解析使用 https://dnsapi.cn/Record.Modify 指定 AAAA 记录 record_type=AAAA&value=$ipv6

两者都返回成功，但是 ipv4 被后一条请求替换掉了

via ：https://www.v2ex.com/t/514398

*注：我遇到的问题差不多 就直接引用这个了

**Comment by Aspiriniii** [comment]
需要指定recordID，现在脚本是拿subdomain去查询的。
