### ISSUE TITLE
uPnP运行不正常

### ISSUE THREAD

**Issue by xiaoqingfengATGH** [coolsnowwolf/lede#3364]
MiniuPnPd运行不正常，
OpenWrt 19.07原版正常。

现象，支持upnp软件无法发现路由器，也无法进行端口映射。

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/75355345-4ebf3700-58e9-11ea-9cff-cfcd1e72f98c.png)
s实测正常，请自己检查

**Comment by xiaoqingfengATGH** [comment]
Upnp已经不好用很久了，之前拿到了几个lede版本，刷入路由器，发现BitComet，EMule报找不到upnp路由错误。

最近一次验证 2020.2.26 lede master代码，自行编译。
![image](https://user-images.githubusercontent.com/31612198/75358483-eaeb3d00-58ed-11ea-9ced-09d49f640a91.png)

IP：192.168.5.247 开启upnp
![image](https://user-images.githubusercontent.com/31612198/75358842-7a90eb80-58ee-11ea-9fe3-b2587f26ea36.png)

同网段启动一台原版OpenWrt 19.07，IP：192.168.5.252 开启upnp
![image](https://user-images.githubusercontent.com/31612198/75358754-5e8d4a00-58ee-11ea-937b-a9d3b7afc08a.png)

同网段Windows10 使用upnpc进行搜索，只能搜索到192.168.5.252，找不到LEDE的 192.168.5.247
![image](https://user-images.githubusercontent.com/31612198/75358998-b035d480-58ee-11ea-851a-a9b0fb74c49f.png)
如果关闭原版OpenWrt 19.07，执行upnpc，会无法搜索到upnp设备
![image](https://user-images.githubusercontent.com/31612198/75359191-03a82280-58ef-11ea-9f1e-45daf59e18bb.png)

**Comment by coolsnowwolf** [comment]
这个是个选择题

因为只有一个版本的 UPNPD 兼容迅雷所有版本

如果选了官方的 UPNPD，那么迅雷就各种异常，2选1 ，你们觉得呢

**Comment by coolsnowwolf** [comment]
另外，编译了 MWAN3 后 UPNP 会失效，卸载就好了

![image](https://user-images.githubusercontent.com/31687149/75366243-669eb700-58f9-11ea-8048-b8ce6f145291.png)

**Comment by zhanghao1989** [comment]
放两个upnp 😀 一个官方，一个迅雷。

**Comment by ntlf9t** [comment]
多线用户或者多lan口都会造成upnp失效需要自己改配置文件

**Comment by xiaoqingfengATGH** [comment]
@ntf9t 您的意思是修改配置文件可以使得MWAN3和 upnpd同时生效？能解释下修改方法吗？

**Comment by xiaoqingfengATGH** [comment]
> 另外，编译了 MWAN3 后 UPNP 会失效，卸载就好了
> 
> ![image](https://user-images.githubusercontent.com/31687149/75366243-669eb700-58f9-11ea-8048-b8ce6f145291.png)

有一个其他情况，编译了Lienol维护的OpenWrt，编译时，同时加入了MWAN3和miniUpnpd，使用相同的测试方法，内网IP 192.168.5.247
![image](https://user-images.githubusercontent.com/31612198/75401574-7cce6680-593d-11ea-802a-3735a9ef5854.png)
![image](https://user-images.githubusercontent.com/31612198/75401904-7391c980-593e-11ea-8b96-39cfa227219d.png)

没有修改过任何配置文件，测试upnp有效。
![image](https://user-images.githubusercontent.com/31612198/75401770-139b2300-593e-11ea-9179-f5ac50dc400d.png)

Lienol 版本内核低于目前master的。
![image](https://user-images.githubusercontent.com/31612198/75401724-fcf4cc00-593d-11ea-91f0-97de1262f5e0.png)

**Comment by xiaoqingfengATGH** [comment]
> 多线用户或者多lan口都会造成upnp失效需要自己改配置文件

补充一下，昨天测试使用的官方OpenWrt 19.07版本也同时安装了mwan3和miniupnpd。从测试结果来看，运行正常。

![image](https://user-images.githubusercontent.com/31612198/75402598-3595a500-5940-11ea-9239-e4efde838600.png)
![image](https://user-images.githubusercontent.com/31612198/75402616-4514ee00-5940-11ea-8c00-02a096ec4671.png)

**Comment by coolsnowwolf** [comment]
那就去掉支持迅雷的那个版本？ 反正我也懒得支持了

**Comment by xiaoqingfengATGH** [comment]
看了下运行正常的Lienol的miniunpnpd和lede的miniupnpd，版本不同
左侧是Lienol右侧是lede
![image](https://user-images.githubusercontent.com/31612198/75410272-536e0480-5956-11ea-9a57-3dff2f7094f9.png)

**Comment by xiaoqingfengATGH** [comment]
> 那就去掉支持迅雷的那个版本？ 反正我也懒得支持了

两个共存，可行吗？

**Comment by coolsnowwolf** [comment]
已更换，as your wish

![image](https://user-images.githubusercontent.com/31687149/75413921-e95b5c80-5961-11ea-8c6c-414b66ea849c.png)

迅雷全家桶用不了 UPNP的，勾一下 v1 看看是否有效

不能共存

**Comment by knightridersimon** [comment]
wan3+upnp, 迅雷54321等端口正常，但是群辉检测不行。

**Comment by coolsnowwolf** [comment]
2 选一

**Comment by xiaoqingfengATGH** [comment]
经过测试只将UPNP升级是无效的。

请同时将MWAN3也升级，即可共存。
MWAN3版本如下：
![image](https://user-images.githubusercontent.com/31612198/75428303-efae0080-5982-11ea-89af-59f3d7ac3417.png)

**Comment by xhqpp** [comment]
> @ntf9t 您的意思是修改配置文件可以使得MWAN3和 upnpd同时生效？能解释下修改方法吗？

请问多拨负载均衡和upnp同时生效的方法能说下吗？
