### ISSUE TITLE
iptables v1.8.2 (legacy): Couldn't load match `set':No such file or directory

### ISSUE THREAD

**Issue by lersh** [coolsnowwolf/lede#3366]
我运行是docker版的openwrt，但是发现ssr plus透明代理不成功，多次试验后，发现似乎是在ssr-rules时出错，一条条执行命令，发现提示这个错误，iptables v1.8.2 (legacy): Couldn't load match `set':No such file or directory
请问怎么解决这个问题？

**Comment by lersh** [comment]
cat /proc/net/ip_tables_matches
后发现没有set的行

**Comment by coolsnowwolf** [comment]
缺 ipt 模块

**Comment by coolsnowwolf** [comment]
set 模块

**Comment by lersh** [comment]
你好，请问要如何安装ipt和set模块？

**Comment by lersh** [comment]
我在.config文件里搜索了下，好像并没有iptables-mod-set这样的组件

**Comment by lersh** [comment]
好吧，我知道为什么了，docker里的/proc/net/ip_tables_matches是共享宿主机的，我宿主机是jetson nano的官方编译的ubuntu 18.04。缺少xt_set模块。jetson nano简直是神坑……
