### ISSUE TITLE
UnblockNeteaseMusic 插件如何使用

### ISSUE THREAD

**Issue by zgs360** [coolsnowwolf/lede#3369]
UnblockNeteaseMusic 插件如何使用

**Comment by brick713** [comment]
https://github.com/project-openwrt/luci-app-unblockneteasemusic 看官方的教程

**Comment by keivenliao** [comment]
我昨天发现，我用手机VPN回家后，也能unblock，Android、apple 均可。。惊喜！

**Comment by WROIATE** [comment]
> 我昨天发现，我用手机VPN回家后，也能unblock，Android、apple 均可。。惊喜！

!!怎么做到的？求教！
