### ISSUE TITLE
Brook无法运行

### ISSUE THREAD

**Issue by wu113** [coolsnowwolf/lede#337]
make menuconfig
Advanced configuration option (for developers) --> Target options --> Use software floating point by default
make kernel_menuconfig
Kernel Type --> MIPS FPU Emulator
路由器是Netgear R6220，昨天开了fpu重新编译了，新编译的固件其他功能正常，就是Brook无法运行，重新编译3次都不行。我用Brook的window版客户端能正常连接服务器，正常翻墙。

**Comment by microten** [comment]
同样 我也遇到了这个问题 不知道缺少什么组件 ar71xx

**Comment by vvxiang** [comment]
我的一启动保存就无法连网，机器跟你们的不同，编译的别的可以用，配置管理都进不去，只能重刷机

**Comment by honnbin** [comment]
同理，我也是无法运行

**Comment by honnbin** [comment]
x86 编译的brook一起动就断网，web也进不去
