### ISSUE TITLE
使用make oldconfig再编译出来的版本号比原来的降低了是什么原因？

### ISSUE THREAD

**Issue by shu0802** [coolsnowwolf/lede#3371]
如题内容，特贴图如下
![5b0301ca1f9b52c35a01f5b67f12c52](https://user-images.githubusercontent.com/43750373/75404975-27975280-5947-11ea-910d-79d60267a55f.png)
![14a6ece04be67faaba5fd4adac1904b](https://user-images.githubusercontent.com/43750373/75404979-2a924300-5947-11ea-99a9-d788c4936301.png)

**Comment by DongfeiSay** [comment]
新的有bug，回退了
