### ISSUE TITLE
竞斗云选中网易云音乐解锁后 编译报错

### ISSUE THREAD

**Issue by smous** [coolsnowwolf/lede#3376]
依赖更新到最新的了, 编译还是会报错
日志如下: 
![Snipaste](https://user-images.githubusercontent.com/8821735/75413589-e6ac3780-5960-11ea-9e89-92065f8b5f2b.jpg)

**Comment by coolsnowwolf** [comment]
内存没有 8G

**Comment by smous** [comment]
> 内存没有 8G

我是用WSl子系统进行编译的, 本机内存32G...
![image](https://user-images.githubusercontent.com/8821735/75414038-2e7f8e80-5962-11ea-99ab-c58a307c2d8a.png)

**Comment by jxph1123** [comment]
和我一样错误。。

**Comment by coolsnowwolf** [comment]
wsl路径问题 修改

**Comment by jxph1123** [comment]
![2020-02-27 15-23-54屏幕截图](https://user-images.githubusercontent.com/35351787/75421430-34329f80-5975-11ea-8705-a64e63a6b3b7.png)

**Comment by coolsnowwolf** [comment]
认真看首页
