### ISSUE TITLE
请问大佬 为啥我编译官方版openwrt 时n2n和ramfree 是英文界面

### ISSUE THREAD

**Issue by vbzc** [coolsnowwolf/lede#3381]
大佬 你好，我把n2n和ramfree 放入到官方的package目录下，编译后发现 这两个软件的界面是英文的，以前我记得是中文的，而且 opkg list-installed 命令，没有找到luci-i18n-n2n_v2-zh-cn和 luci-i18n-ramfree-zh-cn这两个文件。

请问大佬 是不是 我哪里没做对，导致没有中文呀？谢谢

**Comment by hue715** [comment]
官方默认的luci.mk是检索po文件夹下的zh_Hans，大佬的po文件夹下中文为zh-cn，需要修改。

**Comment by vbzc** [comment]
@hue715 谢谢答复，我改了文件夹的名称，重新编译后发现 还是英文。

**Comment by hue715** [comment]
> @hue715 谢谢答复，我改了文件夹的名称，重新编译后发现 还是英文。

我试了一下，把文件夹zh-cn改成zh-Hans，配置文件中的中文可以选上。（luci > modules > translations > chinese（zh_Hans））。你看看自己的配置文件中有没有。
<img width="577" alt="截屏2020-03-01下午9 14 15" src="https://user-images.githubusercontent.com/22958922/75626398-3c533f00-5c02-11ea-8211-a086b063546a.png">
<img width="577" alt="截屏2020-03-01下午9 13 54" src="https://user-images.githubusercontent.com/22958922/75626403-42e1b680-5c02-11ea-9cbe-cf4d446172f6.png">

**Comment by vbzc** [comment]
@hue715 谢谢回复，原来是我把安装码包放在openwrt/package/zc 目录下，造成编译后没有中文界面的。移到 openwrt/package下，就可以了。以前我也是这样做的，没问题呀，不知道怎么回事？
