### ISSUE TITLE
UnblockNeteaseMusic 无损音质flac(默认)网易云网页版不能正常播放

### ISSUE THREAD

**Issue by DongfeiSay** [coolsnowwolf/lede#3384]
客户端正常

**Comment by DongfeiSay** [comment]
用其他音源又没有酷我的齐全，现在的酷我是无损音质导致网页版不能播放，建议加一个不是无损音质的酷我音源

**Comment by DongfeiSay** [comment]
真的求给个选择啊，一些人真的确实不需要无损怎么高端的音质，缓存时间还长，还导致不能的在网页版上解锁了，高音质就很不错了😥

**Comment by DongfeiSay** [comment]
竞标失败，罢了

**Comment by mjyhj** [comment]
要不要使用flac，只是一个环境变量。而现在默认启动解锁就使用了这个参数。
另外只有酷我 咪咕 QQ音源支持
最好的做法是LUCI添加一个选项，是否使用FLAC。
这样就可以自由选择了

**Comment by DongfeiSay** [comment]
> 要不要使用flac，只是一个环境变量。而现在默认启动解锁就使用了这个参数。
> 另外只有酷我 咪咕 QQ音源支持
> 最好的做法是LUCI添加一个选项，是否使用FLAC。
> 这样就可以自由选择了。
> 
> 你要是不会改，可以直接使用这个LUCI，代替大雕源上的
> https://github.com/project-openwrt/luci-app-unblockneteasemusic

现在的云解锁版本可以自定义服务器，但是我不知道该怎么部署和现有节点同款的UnblockNeteaseMusic😭
