### ISSUE TITLE
ssr plus+ 订阅有时同步不全

### ISSUE THREAD

**Issue by ll-Beethoven-ll** [coolsnowwolf/lede#3386]
同一名称，配置不同的节点（v2和xxr），在不同订阅链接下，会有自动去重名节点的情况发生，有些节点名称前会有【delete】显示

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by coolsnowwolf** [comment]
并不会 不可能有这个代码出现

**Comment by tone88** [comment]
我也遇到一个订阅自动更新的问题，有时自动更新订阅后会丢失某一订阅连接内的所有节点。已经遇到好几次了，由于只有一个机场（一个ssr订阅，一个v2ray订阅）没法测试其它机场是不是也有这问题。
