### ISSUE TITLE
今晚想尝试Trojan的新特性，然而更新编译后它挂掉了

### ISSUE THREAD

**Issue by guochan2019** [coolsnowwolf/lede#3389]
如题，x86软路由，Trojan为自己在谷歌云搭建，更新前正常，编译过程正常，更新完后Trojan断掉，各种尝试，刷回更新前的固件，又正常了。
想问一下，新版是否需要服务端的支持。得重新部署？

**Comment by AmibaWorld** [comment]
服务端 最新版本是1.14.1

**Comment by guochan2019** [comment]
> 服务端 最新版本是1.14.1，找到旧版本文件位置，下载新版替换旧版本文件即可

服务端早先已经更新到1.14.1

**Comment by guochan2019** [comment]
下午抽空在服务器重新部署1.14.1版本+TLS1.3，测试客户端和老固件均顺利通过，新固件就是不通，新人，找不到问题所在

**Comment by 9l** [comment]
我这没问题

**Comment by 9l** [comment]
你用自签证书还是let's encrypt的证书，allowInsecure 选了么

**Comment by guochan2019** [comment]
> 你用自签证书还是let's encrypt的证书，allowInsecure 选了么，端口密码没错吧

let's encrypt的证书，站点设置没有问题，旧固件trojan一直在用，看到有人反应跟我差不多的问题，应该不是个例，等大神们再研究吧，先用V2Ray

**Comment by guochan2019** [comment]
晚上又重新编译一次，奇怪，没有相关代码更新，居然好了。

**Comment by dxl208** [comment]
要固件支持tls1.3，不然就会卡，无法播放youtube视频，亲测原因就出在对tls1.3因为torjan强制tls1.3
