### ISSUE TITLE
新编译UPNP无法使用。

### ISSUE THREAD

**Issue by BlackTouma** [coolsnowwolf/lede#3399]
**平台：MTK**
**设备：斐讯K2P**

**问题：**昨天新编译的固件，UPNP开启，但无法生效使用，列表一直为空。

**Comment by SharerMax** [comment]
![image](https://user-images.githubusercontent.com/9065684/75536555-7b419300-5a50-11ea-889a-0957f1f3cd4d.png)

**Comment by hhyygg2009** [comment]
我也是，以前那个版本是支持bitcomet的

**Comment by hyird** [comment]
> 我也是，以前那个版本是支持bitcomet的

我今天试了下，现在那个也是可以的

**Comment by naoki66** [comment]
新版本无问题，也解决了MWAN兼容性（需要自己更新mwan），挺好的。

**Comment by chenhao6938** [comment]
我也发现了，upnp不起作用了，迅雷一只没有映射端口。

**Comment by LeeMenHin** [comment]
有什么软件可以测试

**Comment by loonyd** [comment]
> 有什么软件可以测试

我是用群晖的外部访问那里的路由器设置来测试的，如果upnp ok的话会直接找到upnp路由器

**Comment by fonlan** [comment]
> > 有什么软件可以测试
> 
> 我是用群晖的外部访问那里的路由器设置来测试的，如果upnp ok的话会直接找到upnp路由器

那个好像是群晖不支持Openwrt的upnp，换成爱快群晖就能正常识别了。Openwrt的话你试下爱奇艺，应该会创建名为HCDN的upnp服务。

**Comment by loonyd** [comment]
> > > 有什么软件可以测试
> > 
> > 
> > 我是用群晖的外部访问那里的路由器设置来测试的，如果upnp ok的话会直接找到upnp路由器
> 
> 那个好像是群晖不支持Openwrt的upnp，换成爱快群晖就能正常识别了。Openwrt的话你试下爱奇艺，应该会创建名为HCDN的upnp服务。

支持的，我用koolshare的去年9.30的2.33版完美支持，我另外一台k2p用的l大的20.2.15编译的固件也是完美支持，但有的就不支持，我自己也不会编译，所以只能一个一个尝试

**Comment by loonyd** [comment]
> > > > 有什么软件可以测试
> > > 
> > > 
> > > 我是用群晖的外部访问那里的路由器设置来测试的，如果upnp ok的话会直接找到upnp路由器
> > 
> > 
> > 那个好像是群晖不支持Openwrt的upnp，换成爱快群晖就能正常识别了。Openwrt的话你试下爱奇艺，应该会创建名为HCDN的upnp服务。
> 
> 支持的，我用koolshare的去年9.30的2.33版完美支持，我另外一台k2p用的l大的20.2.15编译的固件也是完美支持，但有的就不支持，我自己也不会编译，所以只能一个一个尝试

<img width="662" alt="Xnip2020-02-29_21-41-21" src="https://user-images.githubusercontent.com/33145562/75608638-47439c00-5b3c-11ea-9df0-e420ceab7633.png">

**Comment by DavidDen** [comment]
> 新版本无问题，也解决了MWAN兼容性（需要自己更新mwan），挺好的。

想问问是在/feeds/packages/net/mwan3/makefile里面作出更改嘛？因为里面没有网址，我看不到最新的版本号。请问能否提供一下版本号？谢谢
