### ISSUE TITLE
编译X86虚拟机用固件报错

### ISSUE THREAD

**Issue by makevb** [coolsnowwolf/lede#34]
/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909/src/options.c:301: undefined reference to `__stack_chk_fail_local'
options.o:/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909/src/options.c:61: more undefined references to `__stack_chk_fail_local' follow
make[6]: *** [socket.so.3.0-rc1] Error 1

make[6]: Leaving directory `/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909/src'

make[5]: *** [linux] Error 2

make[5]: Leaving directory `/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909/src'

make[4]: *** [linux] Error 2

make[4]: Leaving directory `/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909'
make[3]: *** [/home/make/lede/build_dir/target-i386_pentium4_musl/luasocket-3.0-rc1-20130909/.built] Error 2

make[3]: Leaving directory `/home/make/lede/feeds/packages/lang/luasocket'

make[2]: *** [package/feeds/packages/luasocket/compile] Error 2

make[2]: Leaving directory `/home/make/lede'

make[1]: *** [/home/make/lede/staging_dir/target-i386_pentium4_musl/stamp/.package_compile] Error 2

make[1]: Leaving directo

准备编译成VMHD文件在虚拟机下使用

**Comment by coolsnowwolf** [comment]
lua 编译问题，和你环境有关，请严格安装 Ubuntu 14 LTS
