### ISSUE TITLE
LEDE 支持的 高通 IPQ4019 设备型号

### ISSUE THREAD

**Issue by cyrilkong** [coolsnowwolf/lede#340]
隔壁的 @ptpt52 写好了支持 IPQ4019 的设备包括一些 RT-ACRH 的，目前使用率比较高的有 ACRH17，希望能跟进到新的 release

**Comment by coolsnowwolf** [comment]
这个是我最早做支持的，产品发布第二天就支持了，谢谢

**Comment by cyrilkong** [comment]
感谢大神，不忘你的热心努力

**Comment by cyrilkong** [comment]
大神，你的 repo update 之后尝试 make menuconfig 没有发现支持 Qualcom ipq40xx 的 Target system，应该要在哪里找到 ACRH17 的 build target

**Comment by cyrilkong** [comment]
ipq80xx 芯片裡面找到支持 acrch17 的編譯 target，issue closed，謝謝
