### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by feedeve** [coolsnowwolf/lede#341]
编译很多次都没有成功。
期间尝试用 16.04 X64编译失败    换会14.04 x64 编译失败。 后来发现要用普通账户编译切回普通用户编译依旧失败。   L 大说空间不足，从NFS划了一块1TB磁盘  单核编译通宵最后还是失败了。
环境  14.04 X64  内存 2G 系统16G  NFS 1TB     

Packaged contents of /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/ddns-scripts_aliyun-1.0.0/ipkg-all/ddns-scripts_aliyun into /home/feedeve/nfs/lede/lede/bin/packages/x86_64/base/ddns-scripts_aliyun_1.0.0-1_all.ipk
echo "ddns-scripts_aliyun" >> /home/feedeve/nfs/lede/lede/staging_dir/target-x86_64_musl/pkginfo/ddns-scripts_aliyun.default.install
make[3]: Leaving directory `/home/feedeve/nfs/lede/lede/package/lean/ddns-scripts_aliyun'
make[3]: Entering directory `/home/feedeve/nfs/lede/lede/package/lean/default-settings'
touch /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/.prepared_1917e651e447759090f8d3debd90dfaa_6664517399ebbbc92a37c5bb081b5c53_check
po2lmo /home/feedeve/nfs/lede/lede/package/lean/default-settings/i18n/advanced-reboot.zh-cn.po /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/advanced-reboot.zh-cn.lmo;  po2lmo /home/feedeve/nfs/lede/lede/package/lean/default-settings/i18n/default.zh-cn.po /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/default.zh-cn.lmo;  po2lmo /home/feedeve/nfs/lede/lede/package/lean/default-settings/i18n/more.zh-cn.po /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/more.zh-cn.lmo;  po2lmo /home/feedeve/nfs/lede/lede/package/lean/default-settings/i18n/sqm.zh-cn.po /home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/sqm.zh-cn.lmo;
bash: po2lmo: command not found
bash: po2lmo: command not found
bash: po2lmo: command not found
bash: po2lmo: command not found
make[3]: *** [/home/feedeve/nfs/lede/lede/build_dir/target-x86_64_musl/default-settings/.prepared_1917e651e447759090f8d3debd90dfaa_6664517399ebbbc92a37c5bb081b5c53] Error 127
make[3]: Leaving directory `/home/feedeve/nfs/lede/lede/package/lean/default-settings'
make[2]: *** [package/lean/default-settings/compile] Error 2
make[2]: Leaving directory `/home/feedeve/nfs/lede/lede'
make[1]: *** [/home/feedeve/nfs/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/feedeve/nfs/lede/lede'
make: *** [world] Error 2
feedeve@ubuntu14:~/nfs/lede/lede$

**Comment by paldier** [comment]
添加依赖luci，或者先取消default-settings编译出luci后在编译
