### ISSUE TITLE
SSR无法获取订阅数据

### ISSUE THREAD

**Issue by cablew** [coolsnowwolf/lede#3412]
树莓派4B上运行的openwrt。在shadowsocksr plus+中添加订阅。尝试多次更新，均失败。错误代码如下。openwrt的其它服务未发现异常。请问是什么错误，要怎么解决？谢谢

![ssr](https://user-images.githubusercontent.com/1415167/75556603-7e04ae00-5a79-11ea-927d-38d9948e84e9.JPG)

**Comment by 9l** [comment]
你openwrt可以上网么，你这是dns有问题吧

**Comment by cablew** [comment]
> 你openwrt可以上网么，你这订阅地址在浏览器中能正常开么，你这是dns有问题吧
谢谢回复。我发现了这个问题。确实，我openwrt设置设置有问题。
