### ISSUE TITLE
内核4.19.101如何升级到106？

### ISSUE THREAD

**Issue by Hansen1018** [coolsnowwolf/lede#3414]
我这几天看到已经有人开始编译4.19.106内核了，我的还是4.19.101，最新的源码

**Comment by hcym** [comment]
x86和arm的没问题，其他的可能有情况吧，大雕退回去了，无所谓的事，乌龟不会变飞机

**Comment by Hansen1018** [comment]
> x86和arm的没问题，其他的可能有情况吧，大雕退回去了，无所谓的事，乌龟不会变飞机

我是x86的 为啥是101？

**Comment by hyird** [comment]
不知道为啥要在意那个小版本号，有啥加成么
自己去看看commit你就明白了

**Comment by hcym** [comment]
官方5.4了，有点😭

**Comment by lonee6** [comment]
改成107也没问题的，我是X64.

LINUX_VERSION-4.19 = .107

LINUX_KERNEL_HASH-4.19.107 = 654BAC198D38E03E7BFF9E2642B01F498DC0FA5D06198EDD14BC30FE7FBF0240
