### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by 404user** [coolsnowwolf/lede#3417]
![批注 2020-02-29 132012](https://user-images.githubusercontent.com/7830579/75601494-a5e62700-5af6-11ea-9644-1e4605dc878c.png)

SSR+的广告屏蔽源，在界面里点更新没反应，但是用命令行可以更新。

**Comment by hahaher123** [comment]
我没这个问题，界面里直接就能更新

**Comment by 404user** [comment]
> 我没这个问题，界面里直接就能更新

前几天的版本也我也可以，但是OpenWrt R20.2.15 / LuCI Master (git-20.058.13156-2faf063) 这个版本不行，前天的也是不行。

**Comment by 404user** [comment]
刚刚试了一下莫名的好了。
