### ISSUE TITLE
ssrplus高级设置里socks代理没有用户名密码认证

### ISSUE THREAD

**Issue by feng1992** [coolsnowwolf/lede#3421]
socks代理里没有用户密码认证，没有安全认证不敢开代理

**Comment by EnnawYang** [comment]
v2ray server了解下

**Comment by feng1992** [comment]
作用不一样，v2ray肯定可以，有时候仅需要代理上tg

**Comment by DongfeiSay** [comment]
> v2ray server了解下

socks server多小 v2ray server多大看一下吧，路由器flash可撑不起
