### ISSUE TITLE
游戏模式出现Udpblocked要咋处理?

### ISSUE THREAD

**Issue by yyzh** [coolsnowwolf/lede#3432]
最新版4.19.106内核的,在游戏模式UDP中继服务器里选了SS节点后再在运行模式里选绕过中国大陆IP模式或者全局模式都会出Udpblocked,而用GFW列表模式就不走SS节点,模式虽然变成FullCone了,但是ip是宽带的ip,没走隧道.转成用koolshare的就正常走隧道出FullCone.这要咋搞啊?难道又得要换回去koolshare版的?

**Comment by coolsnowwolf** [comment]
不要编译 Docker，会导致 NET NS 出现以上问题

**Comment by yyzh** [comment]
@coolsnowwolf 没有上Docker的,我之前搜索帖子找到了这个
https://github.com/coolsnowwolf/lede/issues/1996
就没点Docker,但是用NatTypeTester测试一样是Udpblocked我也试了恩山上其他人最近出的新编译的精简版固件,都有这个问题出现.旧的就没试了,太多了.
