### ISSUE TITLE
三次编译都失败

### ISSUE THREAD

**Issue by TomNotchYmk** [coolsnowwolf/lede#3436]
![image](https://user-images.githubusercontent.com/52726263/75612207-6eaa6100-5b5c-11ea-8197-8d83e0776026.png)
编译机器配置：
谷歌云1核vps，香港C区（其实应该与这个没多大关系）
系统：Ubuntu 14.04 64位

此函数无缺省默认值，或者调用错误。

**Comment by lamu0102** [comment]
阿里云c区不行啊。而且也不适合编译

**Comment by AmadeusGhost** [comment]
不要选olsrd这个包，似乎上游源码有问题

**Comment by TomNotchYmk** [comment]
> 阿里云c区不行啊。而且也不适合编译

我初次编译就是用的同一台机器，而且这明显不是阿里云的问题。

**Comment by yinzhefuyun** [comment]
命令行输入 sudo apt-get update ，然后输入
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib linux-libc-dev:i386
