### ISSUE TITLE
大神好，make menuconfig 设置的型号是R8000，为什么生成的是bcm53xx平台所有型号路由器固件？

### ISSUE THREAD

**Issue by abclevel** [coolsnowwolf/lede#3446]
CONFIG_TARGET_bcm53xx=y
CONFIG_TARGET_bcm53xx_DEVICE_netgear-r8000=y
CONFIG_TARGET_BOARD="bcm53xx"

[config.txt](https://github.com/coolsnowwolf/lede/files/4273278/config.txt)

**Comment by Aes64X** [comment]
bcm53xx arm 下选择 Multiple devices 后再选择详细型号
Target Profile (Multiple devices)
Target Devices

**Comment by ckxt** [comment]
target profile 你没有选你的机型，那么默认就是全型号编译了

**Comment by lqhorochi** [comment]
反正编译出来没有无线的,曾经编译过

**Comment by abclevel** [comment]
型号选的是r8000,这是配置文件对应的代码CONFIG_TARGET_bcm53xx_DEVICE_netgear-r8000=y

**Comment by abclevel** [comment]
> 反正编译出来没有无线的,曾经编译过

无线信号正常

**Comment by abclevel** [comment]
> target profile 你没有选你的机型，那么默认就是全型号编译了

型号选的是r8000,这是配置文件对应的代码CONFIG_TARGET_bcm53xx_DEVICE_netgear-r8000=y

**Comment by abclevel** [comment]
每次云编译生成固件快500兆，下载半天
