### ISSUE TITLE
wr720n v3 不支持吗？

### ISSUE THREAD

**Issue by Mcxunyun666** [coolsnowwolf/lede#3448]
TP-LINK WR720N V3不支持吗？
CPU: ar9331

**Comment by Aes64X** [comment]
32mb ram  去百度远古版本吧

**Comment by bigguyong** [comment]
已经改过16+64了，但是默认设备清单找不到，求支持

**Comment by Mcxunyun666** [comment]
看到tiny-tp-link.mk有720nv3了，但似乎编译时还是找不到，patch-4.9里写的是 TP-Link wr720n v3 is not set.
---原始邮件---
发件人:"coolsnowwolf"<notifications@github.com>
发送时间:2020年3月2日 星期一 下午10:5
收件人:"coolsnowwolf/lede"<lede@noreply.github.com>
抄送:"Mcxunyun666"<mcxunyun666@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [coolsnowwolf/lede] wr720n v3 不支持吗？ (#3448)

Closed#3448.

&mdash;

**Comment by Mcxunyun666** [comment]
是config-4.9.mk有wr720nv3但被注释掉了。写的是TP-LINK_WR720NV3 is not set.
config-4.14中也没有。
说明下：我希望能加回支持的原因是希望让这些老设备能得到新生。毕竟总有些DIY玩家会把他们爆改的。我改了32m rom + 128 mb ram 但找不到新固件去刷，自己编译也没有找到支持的源码。所以才会找l大来帮忙。希望l大能重新加回支持，安慰下我们这些爱好者。幸苦了。
---原始邮件---
发件人:"coolsnowwolf"<notifications@github.com>
发送时间:2020年3月2日 星期一 下午10:5
收件人:"coolsnowwolf/lede"<lede@noreply.github.com>
抄送:"Mcxunyun666"<mcxunyun666@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [coolsnowwolf/lede] wr720n v3 不支持吗？ (#3448)

Closed#3448.

&mdash;
