### ISSUE TITLE
xl2tpd 无法安装

### ISSUE THREAD

**Issue by fireflyzhu** [coolsnowwolf/lede#3452]
错误如下：

Installing xl2tpd (1.3.15-3) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/xl2tpd_1.3.15-3_x86_64.ipk

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for xl2tpd:
 * 	kernel (= 4.19.106-1-64a02cde927a1a7ef5a971ac534653d2)
 * opkg_install_cmd: Cannot install package xl2tpd.

**Comment by AmadeusGhost** [comment]
出现这种提示需要编译的时候选上这个软件包
