### ISSUE TITLE
frpc穿透在部分设备上占用异常

### ISSUE THREAD

**Issue by DongfeiSay** [coolsnowwolf/lede#3454]
使用设备：newifi3 mt7621a 版本都是0.31.2.，不知其他mt7621a机型是否会有这个问题
新3
![路由3](https://user-images.githubusercontent.com/49421020/75625999-8a664380-5bfe-11ea-8017-99b2773ee415.JPG)
x86
![x86](https://user-images.githubusercontent.com/49421020/75625906-6ce4aa00-5bfd-11ea-8cb2-f65e9d2af7d4.JPG)
如图，newifi3的frpc进程VSZ高达656m，%VSZ高达131%？  x86的可以看到是正常的占用情况

另外协议类型选择kcp甚至会将Load average负载均衡值将长久增加0.4-1(1-1.6徘徊)，x86的也会增加了0.2-0.3，是否正常？

新3 tcp
![新3 tcp](https://user-images.githubusercontent.com/49421020/75626378-204f9d80-5c02-11ea-80f2-b070651b7f21.JPG)

**Comment by DongfeiSay** [comment]
> 使用设备：newifi3 mt7621a版本都是0.31.2.，不知其他mt7621a机型是否会有这个问题 如图，newifi3的frpc进程VSZ高达656m，%VSZ高达131%？86的可以看到是正常的占用情况
> ![路由3](https://user-images.githubusercontent.com/49421020/75625999-8a664380-5bfe-11ea-8017-99b2773ee415.JPG)
> ![x86](https://user-images.githubusercontent.com/49421020/75625906-6ce4aa00-5bfd-11ea-8cb2-f65e9d2af7d4.JPG)
> 
> 另外协议类型选择kcp甚至会将Load average负载均衡值将长久增加0.4-1(1-1.6徘徊)，x86的也会增加了0.2-0.3，是否正常？
> ![新3 tcp](https://user-images.githubusercontent.com/49421020/75626378-204f9d80-5c02-11ea-80f2-b070651b7f21.JPG)

**Comment by coolsnowwolf** [comment]
这些没有 fpu 的 处理器靠模拟运行的，占用都很高

**Comment by uoow** [comment]
> 这些没有 fpu 的 处理器靠模拟运行的，占用都很高

![image](https://user-images.githubusercontent.com/46880270/75890488-69edf180-5e69-11ea-80e8-e5acde31b655.png)
L大，请问FRP这个错误提示是不是bug？1月的版本使用是正常的，回来编译新版本后，FRP就连不了；确认过服务端与路由的多路复用设置是一样的。
