### ISSUE TITLE
全局模式为什么不是所有流量都走代理

### ISSUE THREAD

**Issue by 93336644** [coolsnowwolf/lede#3456]
例如“justmysocks.net”，用全局模式也无法访问，要加到“强制走代理的域名才能访问”。
openwrt装在vmware，单网卡旁路由。ssrplus使用trojan节点全局模式。

**Comment by makepoloSeton** [comment]
这是因为只有GFWlist和强制走代理的域名才会使用pdnsd通过隧道解析域名，没在GFWlist的域名是使用国内dns解析，国内dns把一些网址墙了，无法正确解析，所以你才打不开

**Comment by 93336644** [comment]
是的，我摸索了两天发现的情况跟你说的一样。
我现在的解决办法是把openwrt自定义dns指向自己搭的DNS2SOCKS，这样通过DNS2SOCKS把openwrt没在GFWlist里的域名也通过墙外的vps解析了，貌似可以解决这个问题。。
或者有没有更简单的方法让全局模式的所有流量包括dns解析的都走代理呢？

**Comment by makepoloSeton** [comment]
将国内dns改为国外dns，同时将改dns的ip加入访问控制中强制走代理的WAN IP

**Comment by 93336644** [comment]
按照您的方法，我将openwrt作为lan/wan口的dns设置为8.8.8.8，dhcp/dns中dns转发也设置为8.8.8.8；
然后将8.8.8.8加入ssrplus的“强制走代理的WAN IP”中，客户端windows电脑的dns设置为openwrt的地址或者8.8.8.8，依然是没有效果，不能打开被dns污染的网站。
