### ISSUE TITLE
解决卡顿无法播放YouTube视频原因在ssrpuls+对trojan tls1.3支持

### ISSUE THREAD

**Issue by dxl208** [coolsnowwolf/lede#3460]
要客户端支持tls1.3，不然就会卡，或者无法播放youtube视频，亲测原因就出在对tls1.3的支持，因为有脚本torjan强制tls1.3

**Comment by shu0802** [comment]
卡顿问题解决了没有？

**Comment by dxl208** [comment]
> 卡顿问题解决了没有？

我还没有更新好固件，我起床后试试

**Comment by hcym** [comment]
不知道你的客户端，我的盒子路由手机电脑都可以，就是手机只能有一个节点，麻烦

**Comment by dxl208** [comment]
> 不知道你的客户端，我的盒子路由手机电脑都可以，就是手机只能有一个节点，麻烦
我用老版本不支持tls1.3的小火箭直连，非常卡顿，还不能播放视频，更新到支持tls1.3的版本后非常流畅视频随便拉秒开，你装的trojan是包含了tls1.3的吗，我用的脚本强行tls1.3·，如果不是，那应该没影响。

**Comment by babylife** [comment]
Trojan真是越来越流行了

**Comment by coolsnowwolf** [comment]
目前 1.14 已经支持 TLS1.3

**Comment by hcym** [comment]
我那懂什么tls，就是这几天部署的，有几个是自签证书，都正常使用
