### ISSUE TITLE
ttyd终端会使空闲运行的newifi3平均负载永久保持在0.5-0.6

### ISSUE THREAD

**Issue by DongfeiSay** [coolsnowwolf/lede#3479]
这边排查了好久才找到原来问题居然会是出在小小的ttyd身上，之前包括不限于可能是某驱动导致的，可能是某插件需要fpu只能靠模拟运行导致的，可能是某个内核的版本有问题导致的，在我之前的小米mini x86ttyd都是毫无一丁点影响的 偶然看到koolshare的某贴15L说的把webshell设置从默认的ttyd改为sshellinabox后恢复正常，不然我可能真的找不到原因了

不清楚其他的7621芯片机型是否会这样
这可让我有丶烦躁

开启ttyd
![newifi3 开启ttyd](https://user-images.githubusercontent.com/49421020/75675342-f067cf00-5cc1-11ea-8662-94f5cebcd850.JPG)

关闭ttyd
![newifi3 关闭ttyd](https://user-images.githubusercontent.com/49421020/75675351-f8277380-5cc1-11ea-8c31-a15f236f6fb0.JPG)

**Comment by DongfeiSay** [comment]
![newifi 开启ttyd感人](https://user-images.githubusercontent.com/49421020/75675660-84399b00-5cc2-11ea-85f5-db46da67cd0c.JPG)
有时甚至直接飘到1+

**Comment by DongfeiSay** [comment]
话题这里就直接结束了 我也不想说什么了，为什么会这样哦也不知道，想修就修吧，有确实是本应该不该出现的问题出现了 和一些不完善的地方 我这些没技术的小白只能发现 提出一些存在的bug 稍微提供一些信息来希望能让op变得更完善 罢了

**Comment by DongfeiSay** [comment]
话题这里就直接结束了我也不想说什么了，为什么会这样哦也不知道，想修就修吧，有确实是本应该不该出现的问题出现了和一些不完善的地方我这些没技术的小白只能发现提出一些存在的bug 稍微提供一些信息来希望能让op变得更完善罢了

**Comment by hcym** [comment]
用这些稀奇古怪的干嘛，默认设置里面我只保留一个科学一个docker

**Comment by jxph1123** [comment]
我也是这样，不过我后面直接没编译这个了，没啥用。

**Comment by ricksuzade-maker** [comment]
实测发现在x86平台下也存在这个问题，直接屏蔽了算了。
