### ISSUE TITLE
可否增加QNA-UC5G1T的usb外置网卡的AQC111U驱动，内含链接。

### ISSUE THREAD

**Issue by int2e** [coolsnowwolf/lede#3487]
[`问题链接`](https://github.com/coolsnowwolf/lede/issues/3468#issue-573740520)
那个问题点错点成关闭了

您给我留个地址，我给您邮寄一个卡过去，可以吗？ @coolsnowwolf

**Comment by yangjiey2k** [comment]
我觉得你想的有点多
