### ISSUE TITLE
SSR  Plus+ 现在支持 SOCK5 的服务器节点，可以将主路由的运算分担给其它机器

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#3490]
搞了个新功能， SSR Plus 现在支持 SOCK5 的服务器节点了，而且也是多线程的

例如你可以把 Trojan 或者 V2RAY 开在内网的一台 Windows 下载机上面，开启允许 SOCK5 局域网代理接入

这样，你的弱鸡主路由器的 SSR Plus 就能连接到这台 SOCKS5 服务上面，运算都在这台 Windows 机器上面了，主路由只负责转发

这样就无需所谓的旁路由了，而且可以利用下载机/NAS 强大的多余性能分担

而且旁路由就算死机，也不会影响你正常上网了~~

![image](https://user-images.githubusercontent.com/31687149/75699337-4735ce80-5ceb-11ea-9fd8-408742fbfae0.png)

![image](https://user-images.githubusercontent.com/31687149/75699356-4dc44600-5ceb-11ea-8dbf-c71c726721d2.png)

![image](https://user-images.githubusercontent.com/31687149/75699371-53219080-5ceb-11ea-864a-b2f71a43212f.png)

**Comment by luckyyyyy** [comment]
哈哈 这个没毛病 套娃 分摊

**Comment by hcym** [comment]
花了半年才学会hanwckf的单臂，这个要一年了

**Comment by wujunze** [comment]
弱鸡主路由建议扔掉  哈哈哈

**Comment by makepoloSeton** [comment]
大雕为我们这些穷鬼实在是太费心费力了（大雾）

**Comment by ddvcx** [comment]
不服不行

**Comment by cncaihua** [comment]
弱机的AR9331表示还能再玩3年，然后还想把垃圾堆里的BCM6358找出来试试。

**Comment by Myoko** [comment]
这个功能好！大雕辛苦了！

**Comment by sancome** [comment]
很实用的功能，支持！

**Comment by WellsWang** [comment]
太好了，这个应该能解决我那个Trojan总是时断时续的问题

**Comment by haxc** [comment]
> 弱机的AR9331表示还能再玩3年，然后还想把垃圾堆里的BCM6358找出来试试。

我也有一块 bcm6369吃灰，当年编译的固件lan用不了，要拿出来擦一擦了

**Comment by BOBINIUNIU** [comment]
你们搞的这个东西啊，一颗赛艇。但是个人觉得扶墙的木桶应该是线路而不是路由性能吧。
弱鸡路由建议咸鱼出掉然后入手x86主机。

**Comment by coolsnowwolf** [comment]
已支持 Socks5 用户名密码

![image](https://user-images.githubusercontent.com/31687149/75743884-8dbc1500-5d4d-11ea-8c52-48c2c29e4153.png)

**Comment by babylife** [comment]
不错不错，现在就差均衡负载模块了吧，其他感觉和passwall都一样了

**Comment by darkrain88** [comment]
HAproxy 怎么使用最新的源码 , 求带

用几个vps 来聚合trojan的流量

**Comment by WellsWang** [comment]
@coolsnowwolf 能否看下这个ISSUE?
https://github.com/coolsnowwolf/lede/issues/3327
Trojan莫名其妙时断时续，当然现在有SOCKS5代理我可以用来workaround，但是我还是想知道原因，是否能给些建议或者告知debug方法
有其他朋友也遇到类似情况。

**Comment by hcym** [comment]
遇到，很痛苦😭，好像tcp和udp节点类型不一致的概率大，我是尽量保持一个类型，感觉好一些。

**Comment by yannanfeigithub** [comment]
编译的K2P重启动，路由器配置被重置，怎么办？

**Comment by gfonline** [comment]
我也遇到了相似的时断时续的问题，在手机和电脑客户端没有出现这个问题

**Comment by lipwah** [comment]
为什么重新编译都没有socks5

**Comment by gfonline** [comment]
最新版本的的编译选项里ssr plus软件包里并没有socks5的选项啊？

**Comment by fishbless** [comment]
这个号，弱鸡主路由有救了

**Comment by shu0802** [comment]
SOCKS5这个怎么用？是不是按大雕的做法后，就可以把里面所有的节点都能用上？

**Comment by shu0802** [comment]
SOCKS5这个怎么用？是不是按大雕的做法后，就可以把里面所有的节点都能用上？

**Comment by mailsex** [comment]
很实用的功能，支持！

**Comment by cdcchen** [comment]
这个功能并不实用啊，需要一直开着这台windows电脑。如果有一台nas那是再好不过了。

**Comment by zhouym233** [comment]
在menuconfig里找不到sock5相关选项，编译后添加节点时也没有sock5选项，求解
