### ISSUE TITLE
诊断工具-》网络工具-》ping facebook.com

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#3491]
PING facebook.com (157.240.13.35): 56 data bytes

--- facebook.com ping statistics ---
5 packets transmitted, 0 packets received, 100% packet loss

这个是不是bug，翻墙可以，trojan可以，v2ray可以。局域网机器都可以上。
就是在op做诊断facebook.com
100%loss

**Comment by kiss2u** [comment]
我的情况类似。。。

**Comment by eekon** [comment]
学学CCNA第一阶段，你就不会问这么白痴的问题了，你又不是用tcping

**Comment by SharerMax** [comment]
https://www.jianshu.com/p/12a520c76ca9
ping 用的是ICMP协议，这个协议默认是不走代理的
ssr目前只会代理TCP（默认），UDP（需开启）

**Comment by lizhenglin2002** [comment]
ping一般不用TCP的啊

**Comment by norikohxb** [comment]
也就是说这个诊断工具是留给不翻墙网站测试用的？

**Comment by lizhenglin2002** [comment]
是的

norikohxb <notifications@github.com> 于 2020年3月4日周三 17:41写道：

**Comment by norikohxb** [comment]
弱弱问一下，这个诊断工具，其实为什么不开发出，墙外墙内都可以诊断，不是更好吗？
