### ISSUE TITLE
SSR Plus+  Trojan 多线程： 请问单核双线程N280 cpu,是不是选择自动即可？

### ISSUE THREAD

**Issue by babylife** [coolsnowwolf/lede#3495]
线程和进程我困扰了，更困扰的是我没理解其和cpu内核之间的联系。 

谢谢大佬们

**Comment by hcym** [comment]
16或者32应该没事，我用n1和5020u随便开，用ac58u不能超32，不然立马卡死，效果吗还是线路最重要，其次稳定

**Comment by keivenliao** [comment]
X86 软路由一般设置多少比较合适？我的CPU是  ：1265L

**Comment by SharerMax** [comment]
不知道就自动

**Comment by babylife** [comment]
目前选择的是自动，N280是32位CPU不支持64位。哈哈

**Comment by hcym** [comment]
瓶颈还是线路，而且早晚波动大，其次的其次才是路由器，自动省心
