### ISSUE TITLE
替换UPnP的方法

### ISSUE THREAD

**Issue by R3pl4c3r** [coolsnowwolf/lede#3498]
L大默认的miniupnpd的版本是2.0.20170421，如果想更换为官方的2.1.20191006-2，那么需要去[这里](https://github.com/openwrt/packages/tree/master/net/miniupnpd)下载miniupnpd的所有文件，然后删除`lede/feeds/packages/net/miniupnpd`这个文件夹并替换为官方的那个miniupnpd文件夹，之后再编译出来的就是2.1.20191006-2版本

**Comment by lloyd18** [comment]
感谢分享~

**Comment by hue715** [comment]
可以申请pr，更新一下。

**Comment by R3pl4c3r** [comment]
> 可以申请pr，更新一下。

大雕有一段时间是最新版，但是几天前又回退到老版本了，所以这个得自己来

**Comment by hhyygg2009** [comment]
我试过替换官方的upnp，还是用不了

**Comment by yubanmeiqin9048** [comment]
> L大默认的miniupnpd的版本是2.0.20170421，如果想更换为官方的2.1.20191006-2，那么需要去[这里](https://github.com/openwrt/packages/tree/master/net/miniupnpd)下载miniupnpd的所有文件，然后删除`lede/feeds/packages/net/miniupnpd`这个文件夹并替换为官方的那个miniupnpd文件夹，之后再编译出来的就是2.1.20191006-2版本

那我想替换会原来的LEAN大的2017版的咋整
