### ISSUE TITLE
如何让luci概况显示cpu型号及温度

### ISSUE THREAD

**Issue by gavin219** [coolsnowwolf/lede#35]
编译的时候需要选择那些项或修改什么才能让luci的概况显示cpu的型号及温度？

**Comment by coolsnowwolf** [comment]
修改 feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm 即可，你可以参考我的固件

**Comment by sirfromprc** [comment]
对大屌热心回复表示敬意

**Comment by d975xbx** [comment]
不会该。可不可以把你的index.htm复制，然后编译呢？

**Comment by gavin219** [comment]
@coolsnowwolf 已经搞定。3Q
