### ISSUE TITLE
SoftEther VPN连至路由器，无法通过SSR+的GFW模式翻墙

### ISSUE THREAD

**Issue by Fyred** [coolsnowwolf/lede#3501]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue
A：* [是 ] 没有类似的issue

### (1) 具体问题

A：公司win10电脑通过SoftEther VPN的L2tp模式连回家里openwrt路由器，无法打开google等网站，在SSR+中将“GFW模式”切换为“绕过大陆ip模式”，google等网站才能正常访问。

家中内网电脑则无此问题，GFW模式一切正常。

安卓手机通过SoftEther VPN的L2tp模式连回家里，也无此问题。

公司电脑之前由win7更换为win10，以前win7配合R9.12.31及更老版本也无此问题。

### (2) 路由器型号和固件版本

A：OpenWrt R20.2.15，3月1日代码编译

### (3) 详细日志

A：无

**Comment by joketans** [comment]
我3.1 号凌晨pull的一个版本有这个现象，大家反馈都没问题。3.2号pull下来重新编译后，这个现象就没有了。还是pull最新的编译一个吧。lol
