### ISSUE TITLE
SSR+的广告屏蔽订阅不会翻墙

### ISSUE THREAD

**Issue by ddvcx** [coolsnowwolf/lede#3502]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue
A：* [是 ] 没有类似的issue

### (1) 具体问题

A：因为默认列表很多网站都打开有问题
我用的订阅地址为https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt
githubusercontent.com已经添加到强制走代理列表，并且能正常用浏览器打开该网址。
但是点更新时，一直失败，就算设置成全局模式也无法更新成功
默认列表能正常更新

### (2) 路由器型号和固件版本

A：Newifi3，OpenWrt R20.2.15 / LuCI Master (git-20.047.54228-e6b2608)

### (3) 详细日志

A：

**Comment by Mattraks** [comment]
这个订阅内就没有hosts格式内容
