### ISSUE TITLE
rtl8152 usb网卡编译缺少usbcore.ko问题

### ISSUE THREAD

**Issue by yangsongli** [coolsnowwolf/lede#3511]
如图下 昨天还是好的
![image](https://user-images.githubusercontent.com/52395039/75762902-66c60900-5d76-11ea-89f8-086fc67ad049.png)
![image](https://user-images.githubusercontent.com/52395039/75762910-6cbbea00-5d76-11ea-8b55-9a4b78eca497.png)
Target System (QEMU ARM Virtual Machine) Subtarget (ARMv8 multiplatform)
最新源码

**Comment by leaplu** [comment]
大雕修好了 可以了

**Comment by yangsongli** [comment]
> 大雕修好了可以了

看到了 谢谢提醒
