### ISSUE TITLE
用了luci-app-ssr-plus里面的广告过滤问题。

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#3518]
用了luci-app-ssr-plus里面的广告过滤后，安卓手机打开部分网页，如淘宝等，网页打不开，提示服务器错误，关闭luci-app-ssr-plus里面的广告过滤后正常。

**Comment by swxk521** [comment]
哪里面我觉的不加广告的好，还去去掉那个功能

**Comment by bin20088** [comment]
我这都正常啊

**Comment by ricksuzade-maker** [comment]
别动不动就说让别人删掉这个功能，你不用不等于别人不用，好吗？

**Comment by jxph1123** [comment]
我这手机有些网站打不开，电脑正常，不知道为啥。。。

**Comment by ricksuzade-maker** [comment]
这难道不是你手机的问题吗？ 路由器又不认你是电脑还是手机，他只负责转发。。。

**Comment by bin20088** [comment]
我这都正常啊 

> 别动不动就说让别人删掉这个功能，你不用不等于别人不用，好吗？

说的好

**Comment by hxlls** [comment]
不用自己把勾选去掉很难么？为啥要删掉？大把人需求这个功能
