### ISSUE TITLE
官方OpenWrt 18.06.8使用广告屏蔽大师 Plus+不能更新规则

### ISSUE THREAD

**Issue by S0MEW0LF** [coolsnowwolf/lede#3523]
使用的是整个lede编译后在lede/bin/packages/x86_64/base上面找到的adbyby_2.7-20181023_x86_64.ipk，luci-app-adbyby-plus_2.0-45_all.ipk，luci-i18n-adbyby-plus-zh-cn_2.0-45_all.ipk，我的是软路由。
我是小白，也不太懂这个，尝试了一下SSH里面运行升级命令，结果：
root@OpenWrt:~# /usr/share/adbyby/adupdate.sh
/usr/share/adbyby/adupdate.sh: line 6: wget-ssl: not found
MD5 not match! Need update!
/usr/share/adbyby/adupdate.sh: line 28: wget-ssl: not found
/usr/share/adbyby/adupdate.sh: line 28: wget-ssl: not found

**Comment by tuTuStream** [comment]
`wget-ssl: not found` 很明显啊，安装wget 就好了。
![图片](https://user-images.githubusercontent.com/45327576/75833397-e2b26680-5df3-11ea-993f-5087c5289752.png)

**Comment by SharerMax** [comment]
少依赖 找一下编译后生成的 wget 的ipk，也安装上
