### ISSUE TITLE
IPQ806X NSS驱动支持讨论

### ISSUE THREAD

**Issue by LeeMenHin** [coolsnowwolf/lede#3524]
目前只有Pandorabox和quarkysg的源码支持NSS驱动:
IPQ806x NSS协处理器支持
IPQ806x NSS-Crypto(NSS加密优化)
NSS ECM offload(NSS转发加速)

现在编译出来的IPQ806X系列都因为NSS驱动缺少，导致比官方固件速度慢了一截。

在看了pandorabox 和 openwrt 论坛讨论关于NSS 驱动的讨论，我们是否也开始在这个branch 支持NSS驱动呢?

建议详细看了讨论贴再看源码

从开始这里是NSS驱动的讨论原贴:
https://forum.openwrt.org/t/ipq806x-nss-drivers/12613

这里是那个版主添加NSS的源码:
https://github.com/quarkysg/openwrt

**Comment by mcucore** [comment]
支持各位大牛，搞完顺手IPQ4019也解决了！

**Comment by LeeMenHin** [comment]
IPQ401X 沒有相關
