### ISSUE TITLE
求救 

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#3525]
ssr昨晚换成了大陆白名单模式，突然不能上网了，gfw模式没问题

“Wed Mar  4 08:49:11 2020 daemon.err dnscrypt-proxy[3138]: dnscrypt-proxy Unable to retrieve server certificates”

与dnscrypt-proxy有关吗？

x86  J1900

**Comment by coolsnowwolf** [comment]
魔改版请找作者

**Comment by kl9800** [comment]
不改了，就是当初觉得新鲜随便装了个，DNSforward也搞了一个，干脆拆了再编一个好了
