### ISSUE TITLE
能提供下Actions的配置文件列表吗？云编译想编译ar9331的wr702n的固件。

### ISSUE THREAD

**Issue by Mcxunyun666** [coolsnowwolf/lede#3528]
如题，actions云编译有一个一个配置文件，能给个含义吗？

**Comment by iyuangang** [comment]
先在本地 `make menuconfig` 选择好需要的功能后保存。这一步就会生成 `.config` 文件。在这个文件里查看你需要的功能，配置到 `action` 里就好了。
不过L大这个已经预先配置好了，直接fork 就能正常编译成功。

**Comment by touzi** [comment]
openwrt-ci.yml 文件中已经看不到那部分代码了.
