### ISSUE TITLE
如何正确Pull requests，不给大神们添乱。

### ISSUE THREAD

**Issue by stephenchou888** [coolsnowwolf/lede#3535]
Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue
![1](https://user-images.githubusercontent.com/48269736/75849922-093ac680-5e21-11ea-85ca-d6f71df0d043.png)
![2](https://user-images.githubusercontent.com/48269736/75849928-0b048a00-5e21-11ea-8ad2-57ae1a7e1bca.png)
![3](https://user-images.githubusercontent.com/48269736/75849931-0b9d2080-5e21-11ea-87a4-1e57758daf58.png)

**Comment by R3pl4c3r** [comment]
请先阅读以下内容再决定是否发起pull request

[关于拉取请求 - GitHub Help](https://help.github.com/cn/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

>拉取请求可让您在 GitHub 上向他人告知**您已经推送到仓库中分支的更改**。 在拉取请求打开后，您可以与协作者讨论并审查潜在更改，在更改合并到基本分支之前添加跟进**提交**。

你当前的操作会 **向** *Lean的代码* 中 **提交** *你的代码* 。如果你想同步Lean的代码到你的仓库请看以下内容

[同步fork的项目的代码 - 教程](https://blog.csdn.net/qq1332479771/article/details/56087333)
