### ISSUE TITLE
关于IPV6 DNS问题

### ISSUE THREAD

**Issue by chiyu521** [coolsnowwolf/lede#3537]
最近发现IPV6无法使用了  就检测了一下 
发现是AAAA DNS 返回问题 不知道如何解决~ 优先返回V4其次返回V6
![TIM截图20200304140629](https://user-images.githubusercontent.com/45763178/75850299-ed83f000-5e21-11ea-962f-7841c3525eec.png)

**Comment by R3pl4c3r** [comment]
> 最近发现IPV6无法使用了 就检测了一下
> 发现是AAAA DNS 返回问题 不知道如何解决~ 优先返回V4其次返回V6
> ![TIM截图20200304140629](https://user-images.githubusercontent.com/45763178/75850299-ed83f000-5e21-11ea-962f-7841c3525eec.png)

在dnsmasq高级设置里面取消勾选禁止解析AAAA即可

**Comment by chiyu521** [comment]
感谢楼上 我去测试~

**Comment by chiyu521** [comment]
测试成功 感谢~
