### ISSUE TITLE
V2ray permission denied 无法运行

### ISSUE THREAD

**Issue by barton0426** [coolsnowwolf/lede#355]
K3 R7.6.1版
安装后 在luci-app-v2ray中启动，一直显示未启动
在shell中运行v2ray 提示permission denied
chmod 777 v2ray后 依然permission denied
求助

**Comment by lm317379829** [comment]
从github下载对应cpu的文件替换试试。

**Comment by crackself** [comment]
shell 启动试试  ./usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json 。
我通过命令可以运行，但是luci界面选项显示空白

**Comment by lm317379829** [comment]
楼上应该是没有装luci-app-filetransfer。

**Comment by crackself** [comment]
@lm317379829 luci-app-filetransfer不是写明“LuCI page for IPK upload”，用来上传ipk安装文件的吗，和v2ray运行有关?

**Comment by clswang** [comment]
我的也不能运行，在/etc/v2ray/下面没有config.json是不是需要手动添加，luci-app-filetransfer查看已经安装。

**Comment by crackself** [comment]
config.json是从config转换来的，要c-json软件包才可以，你看看有没有安装了

**Comment by barton0426** [comment]
感谢crackself地解决方案 @crackself
能够运行了 不过总感觉哪里不太对 不如我自己修改的sspro速度快

**Comment by clswang** [comment]
软件包里找不到lua-cjson, make menuconfig里也找不到，any advise.

**Comment by barton0426** [comment]
update了吗？我刚刚安装的 就搜json试试

**Comment by clswang** [comment]
opkg update后找到lua-cjson,thanks.

**Comment by lm317379829** [comment]
@clswang  可以在.config文件中找找，或者直接在v2ray的makefile文件中添加对应依赖。

**Comment by lm317379829** [comment]
@crackself 用来上传配置文件。

**Comment by zq133** [comment]
把端口改一下就行了
