### ISSUE TITLE
刷机显示fb: switching to inteldrmfb from simple后卡死

### ISSUE THREAD

**Issue by nanwangjkl** [coolsnowwolf/lede#3552]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

无论是自己编译的包还是上网下载他人编好的包，刷入后都显示fb: switching to inteldrmfb from simple，然后就不动了。上网搜了一下好像跟VGA或者HDMI输出口有关系，编译的时候需要额外选什么驱动吗？

### (2) 路由器型号和固件版本

康耐信4网口J1900
Intel(R) Celeron(R) CPU J1900 @ 1.99GHz
2020-03-04编译版本

### (3) 详细日志
![微信图片_20200304214748](https://user-images.githubusercontent.com/4200349/75885996-79b60780-5e62-11ea-8433-3daf216524df.jpg)

**Comment by hxlls** [comment]
因为驱动了GPU 所以TTY 不显示了把，但是实际上是正常的如果不需要GPU 驱动，
再内核选项把915的对应的驱动取消就行了

**Comment by nanwangjkl** [comment]
确实，系统是正常的，只是显示输出不正常
