### ISSUE TITLE
使用自定义dns地址的情况下，pdnsd和dns2socks使用大陆白名单不能上外网

### ISSUE THREAD

**Issue by fefz** [coolsnowwolf/lede#3553]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

已经使用新规则，ssr+开启大陆白名单模式，自定义DNS服务地址和代理服务地址相同，无法上外网，但是GFW模式正常。如果不选择自定义DNS地址，那么pdnsd和dns2socks模式都可以正常代理。

### (2) 路由器型号和固件版本

A：ssr+ 160-7 版本

### (3) 详细日志

A：

**Comment by hcym** [comment]
没有问题，前面有个人也是说的，吓了一跳，感觉比pdnad稳定一些

**Comment by fefz** [comment]
> 没有问题，前面有个人也是说的，吓了一跳，感觉比pdnad稳定一些

我更新了下，不知道情况一样不。

**Comment by okoklai** [comment]
碰到了和你一样的情况，我的解决方法是，在“访问控制”——“WAN IP访问控制”标签中，添加一个“强制走代理的WAN IP”，地址就填你的节点地址。至此问题解决。
