### ISSUE TITLE
微力同步 占满内置空间问题

### ISSUE THREAD

**Issue by xjtdy888** [coolsnowwolf/lede#3556]
https://github.com/coolsnowwolf/lede/blob/19c07d3c26f3bb82b8c9013df0b55cf380f74dd1/package/lean/luci-app-verysync/root/etc/init.d/verysync#L12

您好，使用微力同步非常好用，但是发现会把内置的空间占满，和微力作者沟通后，说是这个-home路径的问题 -home指定了索引存储位置，应该使用外置磁盘，请大佬支持一下，可以在界面上选择存储位置

**Comment by hxlls** [comment]
自己挂载的地方改下不就行了？把你的磁盘改成挂载到home 下，完事

**Comment by mjyhj** [comment]
-home 只是指定配置的路径，同步时的缓存也是在这个路径下，所以改到外置磁盘是对的。
另外，本体的二进制也比较大，也经常自动更新，也建议挂载到外置储存，或者挂载到内存模式里运行
