### ISSUE TITLE
随机重启问题请教

### ISSUE THREAD

**Issue by momonoshiori** [coolsnowwolf/lede#3557]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
今天重新编译固件会无规律重启，前一段时间(大概2月25号)编译的没有问题，请问下是我这里的硬件问题吗？ 2次编译插件选项一样，感谢
### (1) 具体问题

A：无规律重启，几十分钟到几小时都有发生过

### (2) 路由器型号和固件版本

A：买的主板上面自带CPU是N3700

### (3) 详细日志

A：重启后日志被清空了

**Comment by hcym** [comment]
这个启动uefi什么的注意事项，硬件应该没事

**Comment by momonoshiori** [comment]
大概是硬件问题，昨天去掉核显驱动后就没重启了，估计CPU是ES的核显有什么问题
