### ISSUE TITLE
R6850编译错误

### ISSUE THREAD

**Issue by edboffical** [coolsnowwolf/lede#3560]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
想编译R6850的固件 选了v2ray和trojan 编译错误
### (1) 具体问题

A：

一直编译错误

### (2) 路由器型号和固件版本

A：

网件R6850 target-mipsel_24kc

### (3) 详细日志

A：admin@iZj6c4zttul0nhhy4xsx6yZ:~/lede$ make -j1 V=s
time: target/linux/prereq#0.24#0.00#0.45
make[1]: Entering directory '/home/admin/lede'
make[2]: Entering directory '/home/admin/lede'
+ mkdir -p /home/admin/lede/staging_dir/target-mipsel_24kc_musl
+ cd /home/admin/lede/staging_dir/target-mipsel_24kc_musl
+ mkdir -p bin lib include stamp
mkdir -p /home/admin/lede/build_dir/target-mipsel_24kc_musl/stamp
touch /home/admin/lede/staging_dir/target-mipsel_24kc_musl/.prepared
+ mkdir -p /home/admin/lede/staging_dir/host
+ cd /home/admin/lede/staging_dir/host
+ mkdir -p bin lib include stamp
mkdir -p /home/admin/lede/build_dir/host/stamp /home/admin/lede/staging_dir/host/include/sys
install -m0644 /home/admin/lede/tools/include/*.h /home/admin/lede/staging_dir/host/include/
install -m0644 /home/admin/lede/tools/include/sys/*.h /home/admin/lede/staging_dir/host/include/sys/
ln -sf lib /home/admin/lede/staging_dir/host/lib64
touch /home/admin/lede/staging_dir/host/.prepared
make[3]: Entering directory '/home/admin/lede/tools/flock'
make[3]: Leaving directory '/home/admin/lede/tools/flock'
time: tools/flock/compile#0.00#0.00#0.04
make[3]: Entering directory '/home/admin/lede/tools/xz'
make[3]: Leaving directory '/home/admin/lede/tools/xz'
time: tools/xz/compile#0.00#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/sed'
make[3]: Leaving directory '/home/admin/lede/tools/sed'
time: tools/sed/compile#0.00#0.00#0.07
make[3]: Entering directory '/home/admin/lede/tools/patch'
make[3]: Leaving directory '/home/admin/lede/tools/patch'
time: tools/patch/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/tar'
make[3]: Leaving directory '/home/admin/lede/tools/tar'
time: tools/tar/compile#0.00#0.00#0.08
make[3]: Entering directory '/home/admin/lede/tools/m4'
make[3]: Leaving directory '/home/admin/lede/tools/m4'
time: tools/m4/compile#0.00#0.00#0.08
make[3]: Entering directory '/home/admin/lede/tools/autoconf'
make[3]: Leaving directory '/home/admin/lede/tools/autoconf'
time: tools/autoconf/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/pkg-config'
make[3]: Leaving directory '/home/admin/lede/tools/pkg-config'
time: tools/pkg-config/compile#0.00#0.00#0.07
make[3]: Entering directory '/home/admin/lede/tools/automake'
make[3]: Leaving directory '/home/admin/lede/tools/automake'
time: tools/automake/compile#0.01#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/missing-macros'
make[3]: Leaving directory '/home/admin/lede/tools/missing-macros'
time: tools/missing-macros/compile#0.00#0.00#0.03
make[3]: Entering directory '/home/admin/lede/tools/libtool'
make[3]: Leaving directory '/home/admin/lede/tools/libtool'
time: tools/libtool/compile#0.00#0.00#0.08
make[3]: Entering directory '/home/admin/lede/tools/gmp'
make[3]: Leaving directory '/home/admin/lede/tools/gmp'
time: tools/gmp/compile#0.02#0.01#0.20
make[3]: Entering directory '/home/admin/lede/tools/mpfr'
make[3]: Leaving directory '/home/admin/lede/tools/mpfr'
time: tools/mpfr/compile#0.00#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/mpc'
make[3]: Leaving directory '/home/admin/lede/tools/mpc'
time: tools/mpc/compile#0.00#0.00#0.07
make[3]: Entering directory '/home/admin/lede/tools/libelf'
make[3]: Leaving directory '/home/admin/lede/tools/libelf'
time: tools/libelf/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/expat'
make[3]: Leaving directory '/home/admin/lede/tools/expat'
time: tools/expat/compile#0.00#0.00#0.07
make[3]: Entering directory '/home/admin/lede/tools/flex'
make[3]: Leaving directory '/home/admin/lede/tools/flex'
time: tools/flex/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/bison'
make[3]: Leaving directory '/home/admin/lede/tools/bison'
time: tools/bison/compile#0.01#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/mklibs'
make[3]: Leaving directory '/home/admin/lede/tools/mklibs'
time: tools/mklibs/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/libressl'
make[3]: Leaving directory '/home/admin/lede/tools/libressl'
time: tools/libressl/compile#0.02#0.01#0.16
make[3]: Entering directory '/home/admin/lede/tools/cmake'
make[3]: Leaving directory '/home/admin/lede/tools/cmake'
time: tools/cmake/compile#0.07#0.14#1.37
make[3]: Entering directory '/home/admin/lede/tools/zlib'
make[3]: Leaving directory '/home/admin/lede/tools/zlib'
time: tools/zlib/compile#0.00#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/sstrip'
make[3]: Leaving directory '/home/admin/lede/tools/sstrip'
time: tools/sstrip/compile#0.00#0.00#0.04
make[3]: Entering directory '/home/admin/lede/tools/make-ext4fs'
make[3]: Leaving directory '/home/admin/lede/tools/make-ext4fs'
time: tools/make-ext4fs/compile#0.00#0.01#0.14
make[3]: Entering directory '/home/admin/lede/tools/e2fsprogs'
make[3]: Leaving directory '/home/admin/lede/tools/e2fsprogs'
time: tools/e2fsprogs/compile#0.00#0.04#0.36
make[3]: Entering directory '/home/admin/lede/tools/mtd-utils'
make[3]: Leaving directory '/home/admin/lede/tools/mtd-utils'
time: tools/mtd-utils/compile#0.00#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/mkimage'
make[3]: Leaving directory '/home/admin/lede/tools/mkimage'
time: tools/mkimage/compile#0.05#0.13#1.31
make[3]: Entering directory '/home/admin/lede/tools/firmware-utils'
make[3]: Leaving directory '/home/admin/lede/tools/firmware-utils'
time: tools/firmware-utils/compile#0.00#0.00#0.05
make[3]: Entering directory '/home/admin/lede/tools/patch-image'
make[3]: Leaving directory '/home/admin/lede/tools/patch-image'
time: tools/patch-image/compile#0.00#0.00#0.04
make[3]: Entering directory '/home/admin/lede/tools/findutils'
make[3]: Leaving directory '/home/admin/lede/tools/findutils'
time: tools/findutils/compile#0.01#0.01#0.11
make[3]: Entering directory '/home/admin/lede/tools/quilt'
make[3]: Leaving directory '/home/admin/lede/tools/quilt'
time: tools/quilt/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/padjffs2'
make[3]: Leaving directory '/home/admin/lede/tools/padjffs2'
time: tools/padjffs2/compile#0.00#0.00#0.04
make[3]: Entering directory '/home/admin/lede/tools/mm-macros'
make[3]: Leaving directory '/home/admin/lede/tools/mm-macros'
time: tools/mm-macros/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/bc'
make[3]: Leaving directory '/home/admin/lede/tools/bc'
time: tools/bc/compile#0.00#0.00#0.07
make[3]: Entering directory '/home/admin/lede/tools/gengetopt'
make[3]: Leaving directory '/home/admin/lede/tools/gengetopt'
time: tools/gengetopt/compile#0.00#0.01#0.08
make[3]: Entering directory '/home/admin/lede/tools/patchelf'
make[3]: Leaving directory '/home/admin/lede/tools/patchelf'
time: tools/patchelf/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/mtools'
make[3]: Leaving directory '/home/admin/lede/tools/mtools'
time: tools/mtools/compile#0.00#0.00#0.05
make[3]: Entering directory '/home/admin/lede/tools/dosfstools'
make[3]: Leaving directory '/home/admin/lede/tools/dosfstools'
time: tools/dosfstools/compile#0.00#0.00#0.05
make[3]: Entering directory '/home/admin/lede/tools/ucl'
make[3]: Leaving directory '/home/admin/lede/tools/ucl'
time: tools/ucl/compile#0.01#0.00#0.08
make[3]: Entering directory '/home/admin/lede/tools/upx'
make[3]: Leaving directory '/home/admin/lede/tools/upx'
time: tools/upx/compile#0.01#0.00#0.09
make[3]: Entering directory '/home/admin/lede/tools/kernel2minor'
make[3]: Leaving directory '/home/admin/lede/tools/kernel2minor'
time: tools/kernel2minor/compile#0.00#0.00#0.06
make[3]: Entering directory '/home/admin/lede/tools/lzma'
make[3]: Leaving directory '/home/admin/lede/tools/lzma'
time: tools/lzma/compile#0.00#0.00#0.10
make[3]: Entering directory '/home/admin/lede/tools/squashfskit4'
make[3]: Leaving directory '/home/admin/lede/tools/squashfskit4'
time: tools/squashfskit4/compile#0.00#0.00#0.05
make[3]: Entering directory '/home/admin/lede/tools/zip'
make[3]: Leaving directory '/home/admin/lede/tools/zip'
time: tools/zip/compile#0.00#0.00#0.07
make[2]: Leaving directory '/home/admin/lede'
make[2]: Entering directory '/home/admin/lede'
make[3]: Entering directory '/home/admin/lede/toolchain/gdb'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/home/admin/lede/toolchain/gdb'
time: toolchain/gdb/compile#0.00#0.00#0.01
make[3]: Entering directory '/home/admin/lede/toolchain/binutils'
make[3]: Nothing to be done for 'compile'.
make[3]: Leaving directory '/home/admin/lede/toolchain/binutils'
time: toolchain/binutils/compile#0.00#0.00#0.01
make[3]: Entering directory '/home/admin/lede/toolchain/gcc/initial'
export SHELL="bash"; make CFLAGS="-O2 -I/home/admin/lede/staging_dir/host/include " CFLAGS_FOR_TARGET="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CXXFLAGS_FOR_TARGET="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" GOCFLAGS_FOR_TARGET="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro"  -C /home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial all-build-libiberty all-gcc all-target-libgcc
make[4]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libiberty'
make[6]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libiberty/testsuite'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libiberty/testsuite'
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libiberty'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libiberty'
make[6]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libiberty/testsuite'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libiberty/testsuite'
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libiberty'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/lto-plugin'
make  all-am
make[6]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/lto-plugin'
make[6]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/lto-plugin'
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/lto-plugin'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/intl'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/intl'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/fixincludes'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/fixincludes'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/build-x86_64-pc-linux-gnu/libcpp'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/zlib'
true "AR_FLAGS=rc" "CC_FOR_BUILD=gcc" "CFLAGS=-O2 -I/home/admin/lede/staging_dir/host/include " "CXXFLAGS=-g -O2" "CFLAGS_FOR_BUILD=" "CFLAGS_FOR_TARGET=-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS=-static-libstdc++ -static-libgcc " "LIBCFLAGS=-O2 -I/home/admin/lede/staging_dir/host/include " "LIBCFLAGS_FOR_TARGET=-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" "MAKE=make" "MAKEINFO=/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0/missing makeinfo --split-size=5000000 " "PICFLAG=" "PICFLAG_FOR_TARGET=" "SHELL=/bin/bash" "EXPECT=expect" "RUNTEST=runtest" "RUNTESTFLAGS=" "exec_prefix=/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl" "infodir=/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/share/info" "libdir=/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/lib" "prefix=/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl" "tooldir=/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/mipsel-openwrt-linux-musl" "AR=ar" "AS=as" "CC=gcc" "CXX=g++" "LD=ld" "LIBCFLAGS=-O2 -I/home/admin/lede/staging_dir/host/include " "NM=nm" "PICFLAG=" "RANLIB=ranlib" "DESTDIR=" DO=all multi-do # make
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/zlib'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libbacktrace'
make  all-am
make[6]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libbacktrace'
true  DO=all multi-do # make
make[6]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libbacktrace'
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libbacktrace'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libcpp'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libdecnumber'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/libdecnumber'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/fixincludes'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/fixincludes'
make[5]: Entering directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/gcc'
build/genautomata /home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/common.md /home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/config/mips/mips.md \
  insn-conditions.md > tmp-automata.c
/bin/bash: line 1: 14614 Killed                  build/genautomata /home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/common.md /home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0/gcc/config/mips/mips.md insn-conditions.md > tmp-automata.c
Makefile:2278: recipe for target 's-automata' failed
make[5]: *** [s-automata] Error 137
make[5]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/gcc'
Makefile:4210: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
make[4]: Leaving directory '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial'
Makefile:36: recipe for target '/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/.built' failed
make[3]: *** [/home/admin/lede/build_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/gcc-7.5.0-initial/.built] Error 2
make[3]: Leaving directory '/home/admin/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#4.54#0.42#6.00
toolchain/Makefile:98: recipe for target 'toolchain/gcc/initial/compile' failed
make[2]: *** [toolchain/gcc/initial/compile] Error 2
make[2]: Leaving directory '/home/admin/lede'
toolchain/Makefile:96: recipe for target '/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/stamp/.toolchain_compile' failed
make[1]: *** [/home/admin/lede/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/admin/lede'
/home/admin/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by FoxDring** [comment]
类似的错误

**Comment by tmpaxx** [comment]
erx同样的错误
/home/admin/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by edboffical** [comment]
> erx同样的错误
> /home/admin/lede/include/toplevel.mk:225: recipe for target 'world' failed
> make: *** [world] Error 2

你们找到问题了吗 我换了个机器编译还是错误

**Comment by edboffical** [comment]
用github actions去编译就不会出错了 应该是编译环境的问题

**Comment by tmpaxx** [comment]
我找到问题了，因为我用的WIN10 UBUNTU的APP编译的，有个文件夹的目录会导致编译失败，用虚拟机就可以了。
________________________________
