### ISSUE TITLE
小米路由器R3G 只有一个5G无线

### ISSUE THREAD

**Issue by threekidney** [coolsnowwolf/lede#3562]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
编译完刷机之后无线设置里面只有一个5G，2G的没有了
### (1) 具体问题
编译完刷机之后无线设置里面只有一个5G，2G的没有了
A：

### (2) 路由器型号和固件版本
小米路由器R3G
R20.2.15
A：

### (3) 详细日志

A：

**Comment by jxph1123** [comment]
你看看是不是没有选kmod-mt7603，最后实在不行就清除配置文件重新编译呗。
