### ISSUE TITLE
IPQ40XX 竟斗云无法QMI驱动EC20模块

### ISSUE THREAD

**Issue by hackjun8** [coolsnowwolf/lede#3563]
竟斗云无法驱动EC20模块
（测试于最新的4.14内核）

ec20 4G模块默认GobiNet or QMI WWAN 模式
检查了大神的源代码都有集成 没有做其他改动

并且根据网上资料lede根目录运行了make menuconfig
配置的环境有
Kernel modules >>
	USB Support >>
		<*> Kmod -usb-core
		-*-Kmod -usb-net
		-*- kmod-usb-net-cdc-ether
		<*> kmod-usb-net-cdc-mbim
		-*- kmod-usb-net-cdc-ncm
		<*> kmod-usb-net-cdc-subset
		<*>kmod-usb-net-qmi-wwan
		<*>Kmod-usb-ohci     //这个选项一定要勾选，否则可能无法在系统中查看设备
		<*>Kmod-usb-serial
		<*>Kmod-usb-serial-option
		<*>Kmod-usb-serial-wwan
		<*>kmod-usb-uhci
		<*>Kmod-usb2
其他包括luci、NetWork、Utilities相关等等

再编译成功 始终无法驱动，求大神指点迷津

根据小白的《OPENWRT开发》提到的文章配置的https://blog.csdn.net/hunzhangzui9837/article/details/85916965

**Comment by neowong** [comment]
https://www.huakings.cn/post/198.html  据说要改造供电的
