### ISSUE TITLE
新版SSR DNS2SOCKS问题

### ISSUE THREAD

**Issue by sky137818221** [coolsnowwolf/lede#3566]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：使用新版SSR 在GFW模式下 DNS2SOCKS解析方式无法正常解析，在切换回PDNSD之后，可以正常解析
切换回PDNSD并再次切换到DNS2SOCKS后 域名可正常访问 且状态中google连接测试正常
测试使用的域名
www.youtube.com
www.google.com
wikipedia.org
重启路由之后 第一次直接使用DNS2SOCKS解析仍无法完成
未保留配置重新刷写固件之后 仍出现该问题

### (2) 路由器型号和固件版本

A：X86-64
R20.2.15
内核版本4.19.106

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
那就不要用这样的方式
