### ISSUE TITLE
编译SSR 提示dns2socks 

### ISSUE THREAD

**Issue by yonggedebaqi** [coolsnowwolf/lede#3569]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	dns2socks
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:108: /home/openwrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:227：world] 错误 2

**Comment by wgedu** [comment]
清除之后再编译，
