### ISSUE TITLE
LUCI程序选择里没有PPTP server了

### ISSUE THREAD

**Issue by FishSlide** [coolsnowwolf/lede#3571]
硬件为 720N-v4, 16MB /64MB 的配置。
之前4.14.169版本，menuconfig 编译的时候还能在程序选项里看到pptp server，刷固件之后能在VPN栏里看到配置选项。今天git pull更新后，menuconfig 程序选项里pptp server 没有了，编译之后刷固件也没有PPTP栏目了。
请问是漏掉了还是取消了？

**Comment by tone88** [comment]
出于安全考虑已经砍掉了

**Comment by FishSlide** [comment]
好的，了解了，谢谢

**Comment by Blueskyhou** [comment]
请问下，我在局域网里面NAS 建立PPTP服务器，然后进行端口转发，也不能成功， 1723的端口是封掉了吗，需要怎么才能打开。
