### ISSUE TITLE
添加Intel核显来硬件解码的方法（不用make kernel_menuconfig）

### ISSUE THREAD

**Issue by R3pl4c3r** [coolsnowwolf/lede#3575]
由于核显输出有BUG，L大回退了代码（commit: 533ef89b743079e796d31f36e872ea5fa295fb89 ），但又想使用核显硬解的朋友可以下载这个[config-4.19](https://raw.githubusercontent.com/coolsnowwolf/lede/1c6e4da87a1e20c0d810dc8dcbdf373764edd3d9/target/linux/x86/config-4.19)文件（commit: 1c6e4da87a1e20c0d810dc8dcbdf373764edd3 ），并替换现有的target/linux/x86/config-4.19文件，再编译即可

**Comment by sofair** [comment]
其实make kernel_menuconfig 也是修改这个文件（当然和你选的Target相关），具体参见Openwrt 官方的make kernel_menuconfig”。

**Comment by Fyred** [comment]
什么bug？
