### ISSUE TITLE
建议通过ssrplus查询DNS后丢弃v6地址

### ISSUE THREAD

**Issue by JilunSama** [coolsnowwolf/lede#3576]
目前使用的国外节点绝大部分是v4IP，因此返回的ipv6地址在一些情况下会发生问题，比如我在使用最新的socks5代理，通过privoxy转换成HTTP代理后设置手机的APN实现中转，这时在连接Google等网站时由于ssrplus查询的结果包含v6地址，导致在经中转连接目标地址时只会尝试使用v6进行连接，而国外VPS没有v6从而导致连接失败
在dnsmasq中已经存在了查询DNS只返回A记录的选项，但在国内许多地区没有公网ipv4只有ipv6的前提下，在连接自己其他的主机时还会用到DNS去解析AAAA记录，所以是否可以考虑丢弃ssrplus查询DNS返回的AAAA记录

**Comment by ZqinKing** [comment]
1、在Lan口配置的DHCPv6里面通告IPv6 DNS填写Lan口上的IPv6地址。
2、在dnsmasq中配置转发即可，如1.1.1.1#53。
实际上跟ssrplus没有关系。正常IPv6获取到的DNS服务器是运营商给的，走的就是IPv6。ssrplus压根就没管。
