### ISSUE TITLE
qBittorrent webui无启动页面

### ISSUE THREAD

**Issue by EstFoxs** [coolsnowwolf/lede#3577]
固件版本20200305 路由型号86_64
没有按键，通过ip也无法访问
![2020-03-05_145812](https://user-images.githubusercontent.com/1283711/75956215-5e92d880-5ef2-11ea-8748-a97fa80c75eb.jpg)
Transmission 没有这个问题

**Comment by bin20088** [comment]
并不存在。一切正常X86

**Comment by EstFoxs** [comment]
那奇怪了，晚点重新刷机

**Comment by EstFoxs** [comment]
> 并不存在。一切正常X86

确定正常？刚才重刷了，也不行啊

**Comment by bin20088** [comment]
QQ群里我传的固件，随便测。这玩意还糊你？
![QQ截图20200305184420](https://user-images.githubusercontent.com/53508344/75974425-b3921700-5f11-11ea-8432-c23c79d3ff74.jpg)

**Comment by bin20088** [comment]
![QQ截图20200305184802](https://user-images.githubusercontent.com/53508344/75974544-ef2ce100-5f11-11ea-8caf-1fa6a4b16259.jpg)
![QQ截图20200305184821](https://user-images.githubusercontent.com/53508344/75974548-f0f6a480-5f11-11ea-9d3d-6ac5cb93a68c.jpg)

**Comment by EstFoxs** [comment]
重新拉包了，已经在编译，一会测试

**Comment by EstFoxs** [comment]
不行，我还了三台软路由都这个问题，你内核多少

**Comment by bin20088** [comment]
@EstFoxs 106
