### ISSUE TITLE
luci-app-v2ray无法运行报错

### ISSUE THREAD

**Issue by crackself** [coolsnowwolf/lede#358]
把相关包和依赖转移到lede-17.01.4分支，wndr4300v1，编译后运行，界面显示未启动，同时界面显示没用详细内容：
![default](https://user-images.githubusercontent.com/16448332/38765183-8bb7b76e-3fef-11e8-888e-fa1578e93b9f.JPG)
查看系统日志，提示错误：
Sat Apr 14 14:22:47 2018 daemon.err uhttpd[1354]: /usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher target for entry '/admin/services/v2ray'.

**Comment by crackself** [comment]
已解决 #355

**Comment by qqj147258** [comment]
请问是如何解决的？
