### ISSUE TITLE
如何创建多个不连续端口的防火墙规则

### ISSUE THREAD

**Issue by unwenliu** [coolsnowwolf/lede#3580]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

自建防火墙规则可以使用`-`作为连接符匹配一段的端口，类似于这样
![](https://i.loli.net/2020/03/05/U7aDZgyF3GkNL2I.png)

但是我想要匹配多个不连续的端口，怎么创建呢，我尝试的使用`,`作为连接符，结果无法保存
![](https://i.loli.net/2020/03/05/5nMKe3mkXZWxajy.png)

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by guochan2019** [comment]
可以分开设置呀,难道我理解的不对?

**Comment by unwenliu** [comment]
使用空格作为连接符就行了，(lll￢ω￢)
