### ISSUE TITLE
端口转发问题

### ISSUE THREAD

**Issue by yangtfu** [coolsnowwolf/lede#3587]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：防火墙内使用端口转发，且非LEDE自身端口的情况下，wan lan必须设置同一端口才能成功，不同端口不成功个

### (2) 路由器型号和固件版本

A：x86 OpenWrt R20.2.15 / LuCI Master (git-20.062.50551-a6189c5)

### (3) 详细日志

A：

**Comment by hxlls** [comment]
编译了docker 或者MWAN3进去了把

**Comment by yangtfu** [comment]
> 编译了docker 或者MWAN3进去了把

没有啊，就加了ipv6和guest wifi

**Comment by guoyuc** [comment]
我遇到过一样的问题, 但只有装在虚拟机里并使用virtio网卡才有这个情况, 换了网卡类型或者用实体机裸装就没问题了.
