### ISSUE TITLE
DHCP分配列表显示不全

### ISSUE THREAD

**Issue by jiayouzl** [coolsnowwolf/lede#3589]
最新版固件,家里的设备明明已经分配到了IP并且能访问,但是在DHCP列表里有几个不显示.都在同一网段下的.

**Comment by jiayouzl** [comment]
分别设备是小米3Pro路由器还有一个是tp-link的TL-WDA6332RE.明明分配到了IP也能访问设置,但在路由器后台不显示.

**Comment by swzeng** [comment]
DHCP列表下显示的是DHCP 服务器分配出去的租约
你有两个设备，可能都开了DHCP，你说的这个路由器后台，应该是某一个路由器吧，所以只显示了这个路由器分配出去的租约，所以不全

**Comment by jiayouzl** [comment]
> DHCP列表下显示的是本DHCP 服务器分配出去的租约
> 你有两个设备，可能都开了DHCP服务器，你说的这个路由器后台，应该是某一个路由器吧，所以只显示了这个路由器的DHCP服务器分配出去的租约，所以不全

额2个AP的DHCP全关了,不是你说的问题引起的.

**Comment by Fyred** [comment]
路由器重启前分配的吧？还没续租就不显示

**Comment by jiayouzl** [comment]
> 路由器重启前分配的吧？还没续租就不显示

那有什么办法让路由器在显示呢?谢谢

**Comment by jiayouzl** [comment]
> 路由器重启前分配的吧？还没续租就不显示

但是也不对,我软路由已经2天没重启过了,DHCP只有12小时有效期,也没有显示出来.
