### ISSUE TITLE
编译错误：tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynnynynnyyyynynyyy

### ISSUE THREAD

**Issue by LeeMenHin** [coolsnowwolf/lede#3591]
`configure: WARNING: cannot find uuid library required for mkfs.ubifs
configure: mtd-utils can optionally be built without mkfs.ubifs
configure: WARNING: cannot find ZLIB library required for mkfs programs
configure: mtd-utils can optionally be built without mkfs.ubifs
configure: mtd-utils can optionally be built without mkfs.jffs2
configure: error: missing one or more dependencies
Makefile:53: recipe for target '/home/peter/桌面/lede/build_dir/host/mtd-utils-2.0.2/.configured' failed
make[3]: *** [/home/peter/桌面/lede/build_dir/host/mtd-utils-2.0.2/.configured] Error 1
make[3]: Leaving directory '/home/peter/桌面/lede/tools/mtd-utils'
time: tools/mtd-utils/compile#7.09#0.97#8.88
tools/Makefile:161: recipe for target 'tools/mtd-utils/compile' failed
make[2]: *** [tools/mtd-utils/compile] Error 2
make[2]: Leaving directory '/home/peter/桌面/lede'
tools/Makefile:159: recipe for target '/home/peter/桌面/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynnynynnyyyynynyyy' failed
make[1]: *** [/home/peter/桌面/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynnynynnyyyynynyyy] Error 2
make[1]: Leaving directory '/home/peter/桌面/lede'
`

**Comment by lloyd18** [comment]
不要把源码放在桌面
