### ISSUE TITLE
ssrplus的socks代理服务端可否支持ipv6的监听

### ISSUE THREAD

**Issue by JilunSama** [coolsnowwolf/lede#3593]
想在公网部署socks5代理回家，但没有v4公网只有v6公网，目前socks代理服务端只监听0.0.0.0，可否支持同时监听在[::]的主机

**Comment by ZqinKing** [comment]
可以使用zerotier建立P2P的点对点隧道，后续在zerotier的虚拟接口上进行代理。zerotier是可以使用ipv6进行点对点隧道建立的。
