### ISSUE TITLE
求大神解決，編譯過程中dhcpv6 和 smaba4出現問題

### ISSUE THREAD

**Issue by bdgsfs** [coolsnowwolf/lede#3595]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：是否是因為缺少某些組件？

### (2) 路由器型号和固件版本

A：編譯問題

### (3) 详细日志

A：Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-samba4:
 *      samba4-libs
 * opkg_install_cmd: Cannot install package luci-app-samba4.
 * check_conflicts_for: The following packages conflict with samba4-server:
 * check_conflicts_for:         samba36-server *
 * opkg_install_cmd: Cannot install package samba4-server.
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/etc/hotplug.d/ntp/25-dnsmasqsec
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/etc/init.d/dnsmasq
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/dnsmasq/dhcp-script.sh
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/usr/sbin/dnsmasq
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/usr/share/acl.d/dnsmasq_acl.json
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/dhcpbogushostname.conf
        But that file is already provided by package  * dnsmasq-full
 * check_data_file_clashes: Package dnsmasq-dhcpv6 wants to install file /home/dashenyang/lede/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/rfc6761.conf
        But that file is already provided by package  * dnsmasq-full
 * opkg_install_cmd: Cannot install package dnsmasq-dhcpv6.
make[2]: *** [package/install] Error 255
make[2]: Leaving directory `/home/dashenyang/lede'
make[1]: *** [/home/dashenyang/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/dashenyang/lede'
make: *** [world] Error 2

**Comment by wgedu** [comment]
samba4和samba36只能安装一个

**Comment by leaplu** [comment]
dnsmasq-full  samba36-server 取消勾选

**Comment by bdgsfs** [comment]
> samba4和samba36只能安装一个

感謝

**Comment by bdgsfs** [comment]
> dnsmasq-full samba36-server 取消勾选

感謝
