### ISSUE TITLE
Configure my own anti DNS pollution server

### ISSUE THREAD

**Issue by Limezy** [coolsnowwolf/lede#3597]
Hi, in the ShadowSocksR Plus+ Settings menu, I would like to setup an anti DNS pollution server that is not in that list (for example CleanBrowsing DNS)

![image](https://user-images.githubusercontent.com/24638389/75998671-231cfc00-5f3c-11ea-9ad7-799121a44e58.png)

How can I do that ?
Or can I setup the V2Ray client to use my V2Ray server DNS resolution ?
Thanks !

**Comment by jerryrat** [comment]
hi,  in SSR+, you can input  customization DNS
![image](https://user-images.githubusercontent.com/19183369/76043217-cf3d0200-5f91-11ea-9117-a02b7c3ea850.png)

**Comment by iyuangang** [comment]
> Hi, in the ShadowSocksR Plus+ Settings menu, I would like to setup an anti DNS pollution server that is not in that list (for example CleanBrowsing DNS)
> 
> ![image](https://user-images.githubusercontent.com/24638389/75998671-231cfc00-5f3c-11ea-9ad7-799121a44e58.png)
> 
> How can I do that ?
> Or can I setup the V2Ray client to use my V2Ray server DNS resolution ?
> Thanks !

<img width="588" alt="图片" src="https://user-images.githubusercontent.com/20696803/76045699-dadff700-5f98-11ea-9035-7193e1888adf.png">
You may set your DNS server like this.

**Comment by iyuangang** [comment]
If you can not find the custom input quote, change browser or upgrade `ssr plus + `
