### ISSUE TITLE
科学模块每天早上都会断，需要手动重启

### ISSUE THREAD

**Issue by xucn** [coolsnowwolf/lede#3598]
最新版本，自建，之前没有此问题，最近更新后才出现的此问题，每天早上都不能翻，需要手动重启科学模块

**Comment by lylxoooooo** [comment]
我也遇到了这个问题，每天睡得晚，所以观察到应该每天晚上凌晨两点的时候自动更新以后，xxRplus就会停止工作

**Comment by gpeditmsc1986** [comment]
从来都是手动更新，没有问题

**Comment by lylxoooooo** [comment]
> 从来都是手动更新，没有问题

手动更新没有问题，就是自动更新会导致XXRplus停止运行。

**Comment by WickedZX** [comment]
试试关闭订阅···········

**Comment by lylxoooooo** [comment]
> 试试关闭订阅···········

在这个bug修复之前，只能先关闭自动更新了
