### ISSUE TITLE
只更新ssr-plus+插件怎么操作啊

### ISSUE THREAD

**Issue by aheig** [coolsnowwolf/lede#3599]
每次更新版本要重刷的话太麻烦，路由器只更新ssr-plus+插件怎么操作啊，用什么命令？

**Comment by jerryrat** [comment]
重刷保留设置多大个事。。实在不行 选 [m] 打包编译 不集成。

**Comment by martin0607** [comment]
只编译ssr

**Comment by iyuangang** [comment]
用github actions 自动编译就可以了啊。
如果觉得复杂，可以看看我的项目 [OpenWrt Stable + Lean's package](https://github.com/iyuangang/openwrt)  `actions` 怎么写的。
如果还是操作不来，可以直接下载我的项目 `actions` 打包好的 `artifacts` 有编译完成的 `ssr plus +` 完整包及依赖包。
