### ISSUE TITLE
ShadowSocksR Plus+ 自动更新后关闭的问题

### ISSUE THREAD

**Issue by Hyejeongdd** [coolsnowwolf/lede#3602]
1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
A：类似Issue见 #3598 

### (1) 具体问题

A：ShadowSocksR Plus+ 启用了自动更新2：00以后 在更新以后进入关闭状态 修改自动更新时间后 不会复现

### (2) 路由器型号和固件版本

A：ASUS ACRH17 OpenWrt R20.2.15 / LuCI Master (git-20.058.13156-2faf063)

### (3) 详细日志

A：https://gist.github.com/Hyejeongdd/649a3ba33e33ae1d0345b10ff2c70fd4

**Comment by coolsnowwolf** [comment]
没有订阅地址，不知道

**Comment by DongfeiSay** [comment]
大雕疯狂暗示：给我整一个
