### ISSUE TITLE
新版SSR Prp无法通过导入链接方式添加Trojan节点

### ISSUE THREAD

**Issue by minfengyk** [coolsnowwolf/lede#3606]
反馈bug/问题模板，提建议请删除

新版SSR Prp无法通过导入链接方式添加Trojan节点

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译的今天最新固件，新版SSR Prp无法通过导入链接方式添加Trojan节点，老版本可以的。

### (2) 路由器型号和固件版本

A：x86 64位

### (3) 详细日志

A：没有日志显示

**Comment by Fyred** [comment]
机场抽了吧？

**Comment by minfengyk** [comment]
没有啊，passwall就加上了，同一个机场。两个软件没同时运行。

**Comment by coolsnowwolf** [comment]
没有提交 URL 和日志，关闭了
