### ISSUE TITLE
DNS 转发 127.0.0.1#5333 更改端口 重启后会重置为默认

### ISSUE THREAD

**Issue by keramist** [coolsnowwolf/lede#3607]
OpenWrt R20.2.15

dnsmasq
DNS 转发 127.0.0.1#5333
设置完 127.0.0.1#1053

docker pihole dns 端口 1053

使用正常
重启后会重置127.0.0.1#5333

**Comment by hxlls** [comment]
这个好像是pdns去查询国外的把，你定向后你的ssrp 就又问题了
