### ISSUE TITLE
请问能不能增加对高通ipq4019的硬件NAT的支持

### ISSUE THREAD

**Issue by nanminnet** [coolsnowwolf/lede#3619]
买开发板的时候介绍是说有硬件NAT引擎的但是烧写了openwrt后在使用中发现硬件nat并没有被启用，请各位大佬解答一下我的疑惑

**Comment by hxlls** [comment]
要支持之前先把对应的驱动找出来啊，要不怎么添加

**Comment by dolphinpaopao** [comment]
拜托，作者不是神仙，什么都无咋个弄。无测试稳定性又如何保证。实际一点。

**Comment by guochan2019** [comment]
Issues是该立规矩了，要不然别说L大，我天天看着都头疼，本来是Issues反馈，现在都快成了项目规划处了

**Comment by nanminnet** [comment]
去外网转了一圈  原来是没有开源的驱动
