### ISSUE TITLE
R7800 R7.6.1内核4.14

### ISSUE THREAD

**Issue by schen39** [coolsnowwolf/lede#362]
手机连接老是出现网络连接失败，
微信视频出现连接失败，部分app连接不了网络，附上系统和内核日志
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/1922054/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/1922055/default.txt)

**Comment by anglabace** [comment]
mwan 连通性检测 别用  g的dns啊 你用国内的不行了。。
