### ISSUE TITLE
SSR PLUS节点会偶尔中断，节点添加选项中有一行向上向下箭头图标显示缺少

### ISSUE THREAD

**Issue by weweyes** [coolsnowwolf/lede#3645]
SSR PLUS节点会偶尔中断，节点添加选项中有一行向上向下箭头图标显示缺少

**Comment by iyuangang** [comment]
1. 节点中断原因很多，机场稳定性，自建服务端稳定性，isp 中断，防火墙识别特征阻滞等。
2. 问题2的截图呢？是什么主题？

**Comment by weweyes** [comment]
问题2：节点添加选项中有一行向上向下箭头图标显示缺少，VMware ESXI  workstation测试过都出现同样问题
<img width="1583" alt="Snipaste_2020-03-08_09-53-05" src="https://user-images.githubusercontent.com/59646715/76155129-caf41e80-6122-11ea-8e3e-16de03a217b8.png">

**Comment by weweyes** [comment]
> 1. 节点中断原因很多，机场稳定性，自建服务端稳定性，isp 中断，防火墙识别特征阻滞等。
> 2. 问题2的截图呢？是什么主题？

问题2：节点添加选项中有一行向上向下箭头图标显示缺少，VMware ESXI workstation测试过都出现同样问题
<img width="1583" alt="Snipaste_2020-03-08_09-53-05" src="https://user-images.githubusercontent.com/59646715/76155258-87021900-6124-11ea-9048-e71dad5b166e.png">
