### ISSUE TITLE
打开比特彗星就断网

### ISSUE THREAD

**Issue by DarkAge2018** [coolsnowwolf/lede#3646]
只要打开比特彗星1.64就断网，wifi接入点会直接消失，过几十秒恢复正常
下载过程中也偶尔会出现这样子的情况
qb最新版和迅雷极速一切正常
[应该不是个例，彗星论坛上也有人反应](https://www.cometbbs.com/t/%E8%BF%99%E4%BA%9Bopenwrt%E7%9A%84%E8%B7%AF%E7%94%B1%E5%99%A8%EF%BC%8C%EF%BC%8Cupnp%E9%83%BD%E4%BC%9A%E5%A4%B1%E8%B4%A5/36469/2?u=blue_kitty)

设备是Newifi-D2 固件是从恩山上下载的，已经试了N个固件了
都是用最近一两个星期的源码编译的，最新3.5号的也是如此

debug模式下的系统日志，10:44和11:00 两次打开和关闭彗星
Sun Mar  8 10:44:01 2020 kern.info kernel: [156504.651140] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sun Mar  8 10:44:01 2020 kern.info kernel: [156504.656950] mt76x2e 0000:01:00.0: Build: 1
Sun Mar  8 10:44:01 2020 kern.info kernel: [156504.661437] mt76x2e 0000:01:00.0: Build Time: 201507311614
Sun Mar  8 10:44:01 2020 kern.info kernel: [156504.689296] mt76x2e 0000:01:00.0: Firmware running!
Sun Mar  8 10:44:01 2020 kern.info kernel: [156504.699023] ieee80211 phy1: Hardware restart was requested
Sun Mar  8 10:44:03 2020 kern.err kernel: [156507.148592] mt76x2e 0000:01:00.0: MCU message 30 (seq 5) timed out
Sun Mar  8 10:44:10 2020 kern.info kernel: [156514.520572] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sun Mar  8 10:44:10 2020 kern.info kernel: [156514.526524] mt76x2e 0000:01:00.0: Build: 1
Sun Mar  8 10:44:10 2020 kern.info kernel: [156514.531407] mt76x2e 0000:01:00.0: Build Time: 201507311614
Sun Mar  8 10:44:10 2020 kern.info kernel: [156514.558348] mt76x2e 0000:01:00.0: Firmware running!
Sun Mar  8 10:44:10 2020 kern.info kernel: [156514.569369] ieee80211 phy1: Hardware restart was requested
Sun Mar  8 10:44:14 2020 kern.err kernel: [156517.720372] mt76x2e 0000:01:00.0: MCU message 2 (seq 8) timed out
Sun Mar  8 10:44:15 2020 kern.err kernel: [156518.748242] mt76x2e 0000:01:00.0: MCU message 30 (seq 9) timed out
Sun Mar  8 10:44:16 2020 kern.err kernel: [156520.268117] mt76x2e 0000:01:00.0: MCU message 3 (seq 11) timed out
Sun Mar  8 10:44:18 2020 kern.err kernel: [156522.108379] mt76x2e 0000:01:00.0: MCU message 31 (seq 13) timed out
Sun Mar  8 10:44:19 2020 kern.err kernel: [156523.148047] mt76x2e 0000:01:00.0: MCU message 31 (seq 14) timed out
Sun Mar  8 10:44:20 2020 kern.err kernel: [156524.188012] mt76x2e 0000:01:00.0: MCU message 31 (seq 15) timed out
Sun Mar  8 10:44:21 2020 kern.err kernel: [156525.228068] mt76x2e 0000:01:00.0: MCU message 31 (seq 1) timed out
Sun Mar  8 10:44:22 2020 kern.err kernel: [156526.267926] mt76x2e 0000:01:00.0: MCU message 31 (seq 2) timed out
Sun Mar  8 10:44:23 2020 kern.err kernel: [156527.307948] mt76x2e 0000:01:00.0: MCU message 31 (seq 3) timed out
Sun Mar  8 10:44:29 2020 kern.info kernel: [156532.779932] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sun Mar  8 10:44:29 2020 kern.info kernel: [156532.785704] mt76x2e 0000:01:00.0: Build: 1
Sun Mar  8 10:44:29 2020 kern.info kernel: [156532.790381] mt76x2e 0000:01:00.0: Build Time: 201507311614
Sun Mar  8 10:44:29 2020 kern.info kernel: [156532.818002] mt76x2e 0000:01:00.0: Firmware running!
Sun Mar  8 10:44:29 2020 kern.info kernel: [156532.828726] ieee80211 phy1: Hardware restart was requested
Sun Mar  8 10:48:29 2020 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED c0:2e:25:d7:d5:73
Sun Mar  8 10:48:29 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 IEEE 802.11: disassociated due to inactivity
Sun Mar  8 10:48:30 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Mar  8 11:00:58 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 IEEE 802.11: authenticated
Sun Mar  8 11:00:58 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 IEEE 802.11: associated (aid 1)
Sun Mar  8 11:00:58 2020 daemon.notice hostapd: wlan1: AP-STA-CONNECTED c0:2e:25:d7:d5:73
Sun Mar  8 11:00:58 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 RADIUS: starting accounting session 034DE1685B0DCA57
Sun Mar  8 11:00:58 2020 daemon.info hostapd: wlan1: STA c0:2e:25:d7:d5:73 WPA: pairwise key handshake completed (RSN)
Sun Mar  8 11:01:59 2020 kern.info kernel: [157583.483678] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sun Mar  8 11:01:59 2020 kern.info kernel: [157583.489534] mt76x2e 0000:01:00.0: Build: 1
Sun Mar  8 11:01:59 2020 kern.info kernel: [157583.494123] mt76x2e 0000:01:00.0: Build Time: 201507311614
Sun Mar  8 11:01:59 2020 kern.info kernel: [157583.524816] mt76x2e 0000:01:00.0: Firmware running!
Sun Mar  8 11:01:59 2020 kern.info kernel: [157583.532794] ieee80211 phy1: Hardware restart was requested
Sun Mar  8 11:02:42 2020 kern.info kernel: [157626.312768] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
Sun Mar  8 11:02:42 2020 kern.info kernel: [157626.318360] mt76x2e 0000:01:00.0: Build: 1
Sun Mar  8 11:02:42 2020 kern.info kernel: [157626.322674] mt76x2e 0000:01:00.0: Build Time: 201507311614____
Sun Mar  8 11:02:42 2020 kern.info kernel: [157626.350379] mt76x2e 0000:01:00.0: Firmware running!
Sun Mar  8 11:02:42 2020 kern.info kernel: [157626.360483] ieee80211 phy1: Hardware restart was requested

内核日志
[156517.720372] mt76x2e 0000:01:00.0: MCU message 2 (seq 8) timed out
[156518.748242] mt76x2e 0000:01:00.0: MCU message 30 (seq 9) timed out
[156520.268117] mt76x2e 0000:01:00.0: MCU message 3 (seq 11) timed out
[156522.108379] mt76x2e 0000:01:00.0: MCU message 31 (seq 13) timed out
[156523.148047] mt76x2e 0000:01:00.0: MCU message 31 (seq 14) timed out
[156524.188012] mt76x2e 0000:01:00.0: MCU message 31 (seq 15) timed out
[156525.228068] mt76x2e 0000:01:00.0: MCU message 31 (seq 1) timed out
[156526.267926] mt76x2e 0000:01:00.0: MCU message 31 (seq 2) timed out
[156527.307948] mt76x2e 0000:01:00.0: MCU message 31 (seq 3) timed out
[156532.779932] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[156532.785704] mt76x2e 0000:01:00.0: Build: 1
[156532.790381] mt76x2e 0000:01:00.0: Build Time: 201507311614____
[156532.818002] mt76x2e 0000:01:00.0: Firmware running!
[156532.828726] ieee80211 phy1: Hardware restart was requested
[157583.483678] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[157583.489534] mt76x2e 0000:01:00.0: Build: 1
[157583.494123] mt76x2e 0000:01:00.0: Build Time: 201507311614____
[157583.524816] mt76x2e 0000:01:00.0: Firmware running!
[157583.532794] ieee80211 phy1: Hardware restart was requested
[157626.312768] mt76x2e 0000:01:00.0: Firmware Version: 0.0.00
[157626.318360] mt76x2e 0000:01:00.0: Build: 1
[157626.322674] mt76x2e 0000:01:00.0: Build Time: 201507311614____
[157626.350379] mt76x2e 0000:01:00.0: Firmware running!
[157626.360483] ieee80211 phy1: Hardware restart was requested

**Comment by coolsnowwolf** [comment]
mtk 的无线驱动死了，关闭无线即可
