### ISSUE TITLE
编译过程成功，但是出现这个什么意思

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#365]
cp -fpR /home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx /home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root.orig-bcm53xx
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/brookpro: line 21: network_get_subnet: command not found
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/brookpro: line 22: network_get_ipaddr: command not found
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/ssrpro: line 22: network_get_subnet: command not found
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/ssrpro: line 23: network_get_ipaddr: command not found
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/v2raypro: line 22: network_get_subnet: command not found
/home/szt/LEDE-source/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/v2raypro: line 23: network_get_ipaddr: command not found

**Comment by Lancenas** [comment]
也碰到同样的情况，解决了吗？
