### ISSUE TITLE
SSR LUCI 界面异常，请教下是遗漏了什么吗？

### ISSUE THREAD

**Issue by yfdoor** [coolsnowwolf/lede#3651]
SSR LUCI 界面异常，请教下是什么问题，是那个依赖的东西没有编译进去吗？
点击菜单的 SSR 后页面显示：

> Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocksr/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:938: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:938: in function </usr/lib/lua/luci/dispatcher.lua:937>

**Comment by coolsnowwolf** [comment]
其他地方的源代码不要在这里发问题
