### ISSUE TITLE
./scripts/feeds update -a  执行这一条失败了

### ISSUE THREAD

**Issue by breadpat** [coolsnowwolf/lede#3652]
大雕  我用的win10版内的ubantu 
./scripts/feeds update -a 执行这一条失败了
希望您在教程内加上sudo apt-get install git-core build-essential libssl-dev libncurses5-dev unzip
这一条命令

**Comment by R3pl4c3r** [comment]
> 大雕 我用的win10版内的ubantu
> ./scripts/feeds update -a 执行这一条失败了
> 希望您在教程内加上sudo apt-get install git-core build-essential libssl-dev libncurses5-dev unzip
> 这一条命令

说了多少遍用虚拟机
