### ISSUE TITLE
1、3.8编译失败，显示mac80211.ko文件丢失； 2，特定情况下qBittorrent与SSR +冲突，且无法恢复

### ISSUE THREAD

**Issue by vodott** [coolsnowwolf/lede#3656]
## 1.关于你要提交的问题
问：是否搜索了issue（使用“ x”选择）
[x]没有类似的问题

### (1) 具体问题
*今天git pull后编译

编译失败，似乎包里少了mac80211.ko这个文件

### (2) 路由器型号和固件版本

主机型号 | Linksys WRT3200ACM
架构 | ARMv7 Processor rev 1 (v7l) x 2
固件版本 | OpenWrt R20.3.5 / LuCI Master (git-20.062.50551-a6189c5)
内核版本 | 4.19.106

### (3) 详细日志

make[3]: Entering directory `/home/zhangqi/lede/package/kernel/mac80211'
removed '/home/zhangqi/lede/bin/targets/mvebu/cortexa9/packages/kmod-mac80211_4.19.106+4.19.98-1-1_arm_cortex-a9_vfpv3.ipk'
mkdir -p /home/zhangqi/lede/bin/targets/mvebu/cortexa9/packages /home/zhangqi/lede/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/backports-4.19.98-1/ipkg-arm_cortex-a9_vfpv3/kmod-mac80211/CONTROL /home/zhangqi/lede/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/pkginfo

ERROR: module '/home/zhangqi/lede/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/linux-mvebu_cortexa9/backports-4.19.98-1/net/mac80211/mac80211.ko' is missing.

make[3]: *** [/home/zhangqi/lede/bin/targets/mvebu/cortexa9/packages/kmod-mac80211_4.19.106+4.19.98-1-1_arm_cortex-a9_vfpv3.ipk] Error 1
make[3]: Leaving directory `/home/zhangqi/lede/package/kernel/mac80211'
time: package/kernel/mac80211/compile#0.05#0.02#0.16
make[2]: *** [package/kernel/mac80211/compile] Error 2
make[2]: Leaving directory `/home/zhangqi/lede'
make[1]: *** [/home/zhangqi/lede/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/zhangqi/lede'
make: *** [world] Error 2

**Comment by lilunxm12** [comment]
我也遇到相同问题

**Comment by vodott** [comment]
> 我也遇到相同问题

您是指第1个问题还是第2个问题？

**Comment by flyfeel** [comment]
同mac80211报错！！

**Comment by ricksuzade-maker** [comment]
time: package/network/services/hostapd/wpad-full-internal/compile#0.92#0.35#1.27
make[3]: Entering directory '/home/runner/work/lede/lede/package/network/utils/iw'
mkdir -p /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/runner/work/lede/lede/tmp/.root-copy.flock -c 'cp -fpR /home/runner/work/lede/lede/build_dir/target-x86_64_musl/iw-tiny/iw-4.14/.pkgdir/iw/. /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.iw_installed
echo "iw" >> /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/pkginfo/iw.tiny.install
make[3]: Leaving directory '/home/runner/work/lede/lede/package/network/utils/iw'
time: package/network/utils/iw/tiny/compile#0.12#0.02#0.14
make[3]: Entering directory '/home/runner/work/lede/lede/package/kernel/mac80211'
mkdir -p /home/runner/work/lede/lede/bin/targets/x86/64/packages /home/runner/work/lede/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-4.19.98-1/ipkg-x86_64/kmod-mac80211/CONTROL /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/pkginfo
ERROR: module '/home/runner/work/lede/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-4.19.98-1/net/mac80211/mac80211.ko' is missing.
Makefile:561: recipe for target '/home/runner/work/lede/lede/bin/targets/x86/64/packages/kmod-mac80211_4.19.106+4.19.98-1-1_x86_64.ipk' failed
make[3]: Leaving directory '/home/runner/work/lede/lede/package/kernel/mac80211'
make[3]: *** [/home/runner/work/lede/lede/bin/targets/x86/64/packages/kmod-mac80211_4.19.106+4.19.98-1-1_x86_64.ipk] Error 1
time: package/kernel/mac80211/compile#0.20#0.05#0.24
package/Makefile:111: recipe for target 'package/kernel/mac80211/compile' failed
make[2]: Leaving directory '/home/runner/work/lede/lede'
make[2]: *** [package/kernel/mac80211/compile] Error 2
package/Makefile:107: recipe for target '/home/runner/work/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/runner/work/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/lede/lede'
/home/runner/work/lede/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2
##[error]Process completed with exit code 2.

**Comment by ricksuzade-maker** [comment]
我刚刚也遇到同样的问题了，不知道咋回事

**Comment by flyfeel** [comment]
大雕 请把mac80211驱动下架 谢谢
4天前有人把这个驱动加上去了。。。。

**Comment by 1715173329** [comment]
mac80211 is working well.

x86_64 mac80211 complilation (based on commit 2ae4662)
![image](https://user-images.githubusercontent.com/22235437/76159617-71f5ac00-615d-11ea-9578-880a6aef601d.png)

ipq40xx mac80211 complilation (based on commit 2ae4662)
![image](https://user-images.githubusercontent.com/22235437/76159636-90f43e00-615d-11ea-9ef6-99ddc77889f4.png)

**Comment by dolphinpaopao** [comment]
目前看到问题的出现频次，x86似乎是问题最少最稳定的平台。

**Comment by tone88** [comment]
同样的问题，正在用默认.config跑，希望能过

**Comment by lilunxm12** [comment]
建议修改标题然后把问题2移到另外的issue,这下面都是说问题1的

**Comment by vodott** [comment]
> 建议修改标题然后把问题2移到另外的问题，这下面都是说问题1的

如你所愿 ;-)

**Comment by lilunxm12** [comment]
@coolsnowwolf 无意冒犯,但是三个小时之内有五个人出现同样问题,这样直接关闭是否不妥?还是说你也试过了没问题?

**Comment by EstFoxs** [comment]
> @coolsnowwolf 无意冒犯,但是三个小时之内有五个人出现同样问题,这样直接关闭是否不妥?还是说你也试过了没问题?
已经正常编译了
