### ISSUE TITLE
OpenVPN Server功能只监听ipv4,没有在ipv6监听 ?

### ISSUE THREAD

**Issue by you-mu** [coolsnowwolf/lede#3657]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：OpenVPN Server功能启用后,端口只在ipv4监听,没有在ipv6监听?

### (2) 路由器型号和固件版本

A：x86  /   (git-20.062.50551-a6189c5) / OpenWrt R20.3.5 

### (3) 详细日志

A：
![2020-03-08_16-09-36](https://user-images.githubusercontent.com/25134898/76159047-8040c980-6157-11ea-8e4f-110b9ee7630e.jpg)

**Comment by segadrive** [comment]
是啊，没有ipv6，着急。如何监听IPV6

**Comment by segadrive** [comment]
希望有大佬能解决这个问题

**Comment by you-mu** [comment]
softetherVPN 的 openvpn 也会出现一致的情况.

**Comment by lunatickochiya** [comment]
这个要先升级openvpn主程序后 修改luci 可以支持的

**Comment by you-mu** [comment]
> 
> 
> 这个要先升级openvpn主程序后 修改luci 可以支持的

感谢大佬升级.
(git-20.062.50551-a6189c5) / OpenWrt R20.3.8  openvpn server已测试 , ipv6正常监听.

想请教一下, softetherVPN 监听为啥也只监听ipv4 ?
