### ISSUE TITLE
ssrplus订阅地址不能输入&

### ISSUE THREAD

**Issue by Alice-space** [coolsnowwolf/lede#3664]
**ssrplus订阅地址不能输入&，输入了会被删除**

**Comment by dovegq** [comment]
我也遇到过，但是有时又自己好了。

**Comment by coolsnowwolf** [comment]
测试可以的，你的 URL 发一下到我邮箱

**Comment by Alice-space** [comment]
抱歉，不太清楚你的邮箱
大致形如
https://域名/link/X4y字符串VEVNr?mu=2&tls

**Comment by coolsnowwolf** [comment]
& 是 url参数的意思 ，如果 & 后面没东西那就被忽略的 。能不能看看url 的定义再说？

**Comment by Alice-space** [comment]
抱歉可能没说清楚
是tls前面的&连同后面的tls一起消失
这两个网址解析下来的东西是不一样的
