### ISSUE TITLE
v2ray 守护日志的详细信息如何查看

### ISSUE THREAD

**Issue by clswang** [coolsnowwolf/lede#367]
v2ray运行后会提示
Bad argument `get'
Try `iptables -h' or 'iptables --help' for more information.

然后几乎没隔几个小时提醒
Problem decteted, restarting V2Ray...

请问是否能查看详细日志。

**Comment by paldier** [comment]
检测不到服务器ip，配置文件里遗漏了

**Comment by clswang** [comment]
看起来我用了heroku免费服务，换了自建的不会有这些错误。谢谢。
