### ISSUE TITLE
qBittorrent的WebUI端口转发配置未生效导致8080端口被转发到WAN

### ISSUE THREAD

**Issue by wspzf** [coolsnowwolf/lede#3673]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：qBittorrent的WebUI端口转发配置在luci里设置的未勾选,保存,
![深度截图_选择区域_20200309105904](https://user-images.githubusercontent.com/43857401/76179598-6904e900-61f6-11ea-88e0-47eadccb97b6.png)
但qBittorrent v4.1.9 Web 用户界面里的配置是勾选的,手动取消,在luci保存也会再次勾选.
![深度截图_选择区域_20200309111059](https://user-images.githubusercontent.com/43857401/76179722-d153ca80-61f6-11ea-9274-444f4500e346.png)
导致导致8080端口被转发到WAN
![深度截图_选择区域_20200309105949](https://user-images.githubusercontent.com/43857401/76179747-e7fa2180-61f6-11ea-8070-7a3e5d0bd23d.png)

### (2) 路由器型号和固件版本

A：

主机型号 Intel(R) Atom(TM) CPU N2600 @ 1.60GHz : 2 Core 4 Thread
固件版本  OpenWrt R20.3.8 / LuCI Master (git-20.062.50551-a6189c5)

### (3) 详细日志

A无

**Comment by R3pl4c3r** [comment]
#3679

**Comment by R3pl4c3r** [comment]
更改/etc/init.d/qbittorrent的第75行
`'UseUPnP:or("true","false"):true' \`改为`'UseUPnP:or("true","false"):false' \`
注意是UseUPnP而不是UPnP
之后重启qbittorrent即可解决问题

**Comment by wspzf** [comment]
> 更改/etc/init.d/qbittorrent的第75行
> `'UseUPnP:or("true","false"):true' \`改为`'UseUPnP:or("true","false"):false' \`
> 注意是UseUPnP而不是UPnP
> 之后重启qbittorrent即可解决问题

感谢!!!,关闭了
