### ISSUE TITLE
莫名占用超高不知道是什么导致的

### ISSUE THREAD

**Issue by zy79937254** [coolsnowwolf/lede#3677]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/4304679/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/4304680/default.txt)

![QQ截图20200309124100](https://user-images.githubusercontent.com/59042792/76183423-43321100-6203-11ea-96e4-43b981820b22.png)

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
看不出
