### ISSUE TITLE
编译samba 错误。

### ISSUE THREAD

**Issue by anglabace** [coolsnowwolf/lede#368]
Collected errors:
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/nmbd
	But that file is already provided by package  * samba4x-server
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/smbd
	But that file is already provided by package  * samba4x-server
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/smbpasswd
	But that file is already provided by package  * samba4x-server
 * opkg_install_cmd: Cannot install package samba36-server.
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/nmbd
	But that file is already provided by package  * samba4x-server
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/smbd
	But that file is already provided by package  * samba4x-server
 * check_data_file_clashes: Package samba36-server wants to install file /home/anglabace/newlede/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/usr/sbin/smbpasswd
	But that file is already provided by package  * samba4x-server
 * opkg_install_cmd: Cannot install package luci-app-samba.
make[2]: *** [package/install] Error 255
make[2]: Leaving directory `/home/anglabace/newlede/lede'
make[1]: *** [/home/anglabace/newlede/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/anglabace/newlede/lede'
Build failed - please re-run with -j1 to see the real error message

**Comment by nimasi** [comment]
3.6和 4.X 不能共存，如果选了 autosamba 就只能用3.6的，
