### ISSUE TITLE
请教各位，如何实现URL重定向

### ISSUE THREAD

**Issue by 404user** [coolsnowwolf/lede#3682]
是这样的，iOS的Safari 默认的谷歌搜索很坑，是打开google.cn，所以每次搜索都会有一个烦人的cn界面让你重定向到google.com.hk 。
小飞机里是可以把google.cn定向到google.com 。但是不知道软路由行不行，请教一下各位。谢谢

**Comment by joketans** [comment]
软路由应该可以改host指向吧，把google.cn 的ip 指到 google.com的ip 试试。我刚用上软路由，不指导能不能改。

**Comment by 404user** [comment]
![image](https://user-images.githubusercontent.com/7830579/76200323-63c29100-622c-11ea-9c97-8a5de42b6119.png)
在这里设置了，不过没效果，不知道还有没其他方法。谢谢


> 软路由应该可以改host指向吧，把google.cn 的ip 指到 google.com的ip 试试。我刚用上软路由，不知道能不能改。

**Comment by hplee0120** [comment]
手机地区改到非大陆就好了。

**Comment by joketans** [comment]
> ![image](https://user-images.githubusercontent.com/7830579/76200323-63c29100-622c-11ea-9c97-8a5de42b6119.png)
> 在这里设置了，不过没效果，不知道还有没其他方法。谢谢 
 提示本地dns要设置到路由地址呢，你设置试试呗

**Comment by 70599** [comment]
@404user 你在iOS设置里把地区改成美国就行了，默认的是com域名。
