### ISSUE TITLE
lede/staging_dir/target-x86_64_musl/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynyynynnyyyynynyyy] Error 2

### ISSUE THREAD

**Issue by ZhaoKunDu** [coolsnowwolf/lede#3685]
make 之后就看到以下错误，请问有见过吗？
ake[3]: Leaving directory `/home/xxx/lede/tools/tar'
time: tools/tar/compile#14.95#11.01#30.48
make[2]: *** [tools/tar/compile] Error 2
make[2]: Leaving directory `/home/xxx/lede'
make[1]: *** [/home/xxx/lede/staging_dir/target-x86_64_musl/stamp/.tools_compile_yynyynnyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynyynynnyyyynynyyy] Error 2
make[1]: Leaving directory `/home/xxx/lede'

**Comment by hhmaomao** [comment]
包损坏，编译前输入make download可解决

**Comment by simplenjoy** [comment]
同样的错误，make download后依然重复出现，有人解决了吗？
