### ISSUE TITLE
内存为何不自动释放

### ISSUE THREAD

**Issue by gavin219** [coolsnowwolf/lede#37]
使用场景1:
硬件：k3，软件版本r6.1
通过samba读写文件时内存剩余13%左右。停止读写一段时间后，内存剩余回复到80%-90%
使用场景2:
硬件：k3，软件版本r7.3.3
通过samba读写文件时内存剩余13%左右。停止读写一段时间后，内存剩余还是13%左右。不释放。
是编译的时候有什么技巧？或者那里有问题呢？虽然不影响使用……

**Comment by coolsnowwolf** [comment]
linux 内核正常调度
