### ISSUE TITLE
DHCP/DNS 重启恢复问题

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#3700]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
*** [ ] 没有类似的issue**
   有类似问题，但是被关闭了

## 2. 详细叙述
无法保存DHCP/DNS
**### (1) 具体问题**
DHCP/DNS里面，修改了“DNS 转发”，保存以后生效，
但是
重启路由以后，“DNS 转发”又恢复成了127.0.0.1#5333
**### (2) 路由器型号和固件版本**
      路由器型号：x86  j1900
      固件版本：OpenWrt R20.3.8 / LuCI Master (git-20.068.29105-b2cf61d)
**### (3) 详细日志**

A：

**Comment by coolsnowwolf** [comment]
就是这么设计的，否则如何 dns 加速？

**Comment by kl9800** [comment]
了解了，谢谢
