### ISSUE TITLE
/etc/init.d/shadowsocksr restart 启动报错

### ISSUE THREAD

**Issue by br7roy** [coolsnowwolf/lede#3709]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：
/etc/init.d/shadowsocksr restart 启动报错
自由门inbound未建立监听

### (2) 路由器型号和固件版本

A：
型号 NETGEAR WNDR3700v4
固件 OpenWrt 19.07.2 r10947-65030d81f3 / LuCI openwrt-19.07 branch git-20.057.55219-13dd17f

### (3) 详细日志

A：
2020-03-10 19:50:49 V2Ray 4.22.1 (OpenWrt) Lean (go1.14 linux/mips) Started!
2020-03-10 19:50:30  Started!
2020-03-10 19:49:46  Started!
	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:10: in main chunk
	[C]: in function 'require'
stack traceback:
	no file '/usr/lib/lua/loadall.so'
	no file '/usr/lib/lua/uci.so'
	no file './uci.so'
	no file '/usr/lib/lua/uci/init.lua'
	no file '/usr/lib/lua/uci.lua'
	no file '/usr/share/lua/uci/init.lua'
	no file '/usr/share/lua/uci.lua'
	no file './uci.lua'
	no field package.preload['uci']
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:10: module 'uci' not found:
	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:10: in main chunk
	[C]: in function 'require'
stack traceback:
	no file '/usr/lib/lua/loadall.so'
	no file '/usr/lib/lua/uci.so'
	no file './uci.so'
	no file '/usr/lib/lua/uci/init.lua'
	no file '/usr/lib/lua/uci.lua'
	no file '/usr/share/lua/uci/init.lua'
	no file '/usr/share/lua/uci.lua'
	no file './uci.lua'
	no field package.preload['uci']
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:10: module 'uci' not found:
2020-03-10 19:49:01  Started!
2020-03-10 19:48:18 V2Ray 4.22.1 (OpenWrt) Lean (go1.14 linux/mips) Started!

**Comment by coolsnowwolf** [comment]
别人的源代码请找原作者
