### ISSUE TITLE
今天开始GFW模式不能用了

### ISSUE THREAD

**Issue by lilong8850** [coolsnowwolf/lede#3711]
今天开始GFW模式不能用了，绕过大陆模式可以用GFW  5207 条记录 更新为最新版，这是咋回事啊

**Comment by Lasx** [comment]
我是早几天就不能用了

**Comment by dolphinpaopao** [comment]
今天晚上19点编译，正常使用。x64平台。

**Comment by hcym** [comment]
基本正常，就是trojian节点不能混用ss，

**Comment by ckxt** [comment]
没有问题，完全正常

**Comment by wsndshx** [comment]
配置为v2ray+gfw+dns2socks，同样不能用了……说是dns解析失败，换用绕过大陆ip模式正常

**Comment by guochan2019** [comment]
昨晚新编译，x86，经测试trojian+gfw+dns2socks，确实出不去了，绕行模式正常

**Comment by martin0607** [comment]
GFW模式我是iOS设备正常，Android全部不行，切换绕中国IP模式倒是正常的。

**Comment by baygixu** [comment]
> GFW模式我是iOS设备正常，Android全部不行，切换绕中国IP模式倒是正常的。

这个蛮好奇是为什么Android的设备会不行

**Comment by martin0607** [comment]
> > GFW模式我是iOS设备正常，Android全部不行，切换绕中国IP模式倒是正常的。
> 
> 这个蛮好奇是为什么Android的设备会不行

我也很奇怪。。不管是Pixel还是Nexus，都不行，感觉是DNS的问题，但是DNS设置并没有什么毛病，不然iOS上也不能用了。。
