### ISSUE TITLE
广告屏蔽大师 Plus+的Adblock Plus 规则数据库无法更新

### ISSUE THREAD

**Issue by ckxt** [coolsnowwolf/lede#3712]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：广告屏蔽大师 Plus+的Adblock Plus 规则数据库无法更新，具体表现为 点击数据库后就一直显示“正在更新，请稍后”

### (2) 路由器型号和固件版本

A：软路由 OpenWrt R20.3.8 / LuCI Master (git-20.062.50551-a6189c5)

### (3) 详细日志

A：系统日志里看不到任何有关的Logs

**Comment by ckxt** [comment]
已更新 就是花的时间比较长  估计是梯子不给力

**Comment by liyuhaolol** [comment]
我也遇到这个问题了，更新卡在“正在更新，请稍候”，你怎么解决的呢？死等么？还有这个网站不在梯子屏蔽列表里吧？开不开梯子有啥区别

**Comment by scadylan** [comment]
做主路由可以更新，做辅助网关不能更新，求解方案。
