### ISSUE TITLE
SSR 订阅在官方luci下订阅失败

### ISSUE THREAD

**Issue by Zack0617** [coolsnowwolf/lede#3719]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：SSR 在官方openwrt 19.07下订阅失败，

### (2) 路由器型号和固件版本

A：3865U软路由+OpenWrt 19.07

### (3) 详细日志

A：
	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:10: in main chunk
	[C]: in function 'require'
stack traceback:
	no file '/usr/lib/lua/loadall.so'
	no file '/usr/lib/lua/uci.so'
	no file './uci.so'
	no file '/usr/lib/lua/uci/init.lua'
	no file '/usr/lib/lua/uci.lua'
	no file '/usr/share/lua/uci/init.lua'
	no file '/usr/share/lua/uci.lua'
	no file './uci.lua'
	no field package.preload['uci']
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:10: module 'uci' not found:

将subscribe文件用162-5中的subscribe替换之后恢复正常

**Comment by coolsnowwolf** [comment]
不是本源代码请不要在这里问
