### ISSUE TITLE
请教如何设置hash,详细见内文

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/lede#372]
比如这个文件package/kernel/mt76/Makefile里面的最后一行如何得到的这个hash值，是针对文件还是目录还是啥？ 具体一点行吗？  谢谢 
PKG_SOURCE_URL:=https://github.com/openwrt/mt76
PKG_SOURCE_PROTO:=git
PKG_SOURCE_DATE:=2018-02-27
PKG_SOURCE_VERSION:=ffa2069e78cf267ce79d7a8820aa0368161ff6e1
PKG_MIRROR_HASH:=dee90d713e3c351ee51da51030e56867fa9bd2eac8f222734d0573223a5e0a41

**Comment by wheretoteardown** [comment]
pkg version填该版本对应commit id，pkg hash写该源码包对应的sha256校验值
