### ISSUE TITLE
MW4530R生成的image大于8MB

### ISSUE THREAD

**Issue by mengxd** [coolsnowwolf/lede#3724]
希望能缺省生成8MB的固件镜像。

**Comment by coolsnowwolf** [comment]
默认大于 8MB 了？

**Comment by haxc** [comment]
> 希望能缺省生成8MB的固件镜像。

请使用带４５３０Ｒ　ｖ１的，新加的默认１６ｍ没有改成８ｍ，ｍａｃ１２００ｒ下面那个

**Comment by ChuckPeng** [comment]
我倒是希望能生成16M的固件，现在的只能生成8M，超过了就不行了。我自己改了这个位置
