### ISSUE TITLE
请教一下关于netgear主题

### ISSUE THREAD

**Issue by Myoko** [coolsnowwolf/lede#3727]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
netgear 主题显示错位
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
关于netgear主题！passwall添加节点显示错位
### (1) 具体问题

在passwall 下添加节点显示错位！能不能修复这个错位的错误？
![QQ截图20200311155959](https://user-images.githubusercontent.com/3013386/76395198-b7aab280-63b1-11ea-81bb-07116baddcf7.png)

**Comment by hxlls** [comment]
你走片场了兄弟，魔改的请到固件作者处提交

**Comment by Myoko** [comment]
主题是L大源码里面自带的！好吧我想应该是L大主题与这个插件兼容性不太好
