### ISSUE TITLE
最新版编译出错

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#3729]
重新清除配置再编译还是一样错误，错误日记如下：
![2020-03-11 16-24-57屏幕截图](https://user-images.githubusercontent.com/35351787/76396891-0c9bf800-63b5-11ea-878d-ab2703885a56.png)

**Comment by hhmaomao** [comment]
你应该是编译前没删除.config重新配置导致的出错吧

**Comment by sirfromprc** [comment]
make clean 下再重新编译

**Comment by AmadeusGhost** [comment]
`make package/kernel/linux/{clean,compile} V=s`之后再编译即可

**Comment by jxph1123** [comment]
好的，谢谢
