### ISSUE TITLE
subscribe 报错。

### ISSUE THREAD

**Issue by rodericliu** [coolsnowwolf/lede#3731]
Hi,

luci-app-ssr-plus: keep subscribe order 这个更新了subscribe.lua后更新列表就报错：

[C]: ?
/usr/share/shadowsocksr/subscribe.lua:23: in main chunk
stack traceback:
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:23: attempt to call method 'get_first' (a nil value)

**Comment by coolsnowwolf** [comment]
把节点全删除再订阅一次即可
