### ISSUE TITLE
Adbyby 无法正常运行

### ISSUE THREAD

**Issue by jasonliu747** [coolsnowwolf/lede#3733]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue （有类似问题但无解决方案）

### (1) 具体问题

A：刚编译最新代码，广告大师一直显示 Adbyby Plus+ 未运行，好像不止一个人遇到类似问题，请问该怎么解决？

### (2) 路由器型号和固件版本

A：FriendlyARM NanoPi NEO 2
OpenWrt R20.3.11 / LuCI Master (git-20.071.17905-38b5cd7)

### (3) 详细日志

A：![image](https://user-images.githubusercontent.com/24452340/76420193-b0e56500-63dc-11ea-9e48-3e9f553d2f44.png)

![image](https://user-images.githubusercontent.com/24452340/76423055-2d7a4280-63e1-11ea-8923-37dca07ad602.png)

**Comment by tcsr200722** [comment]
x86可以正常运行，就是adblock Plus 规则数据库更新不了

**Comment by coolsnowwolf** [comment]
只支持 32bit

**Comment by coolsnowwolf** [comment]
arm 64bit 不能运行

**Comment by jasonliu747** [comment]
原来如此，那请问 @coolsnowwolf 要如何在 Neo2 上面正确运行广告大师呢？

**Comment by coolsnowwolf** [comment]
编译 32bit 的 ARM 版本

**Comment by jasonliu747** [comment]
不好意思再问个问题，我没看到对应 Neo2 的 32bit 版本，请问能说一下编译时该怎么选择吗？谢谢！ @coolsnowwolf

**Comment by lesliedh** [comment]
编译friendlywrt的固件加入adbyby插件可以运行

**Comment by jasonliu747** [comment]
@lesliedh 您也是Neo2吗？

**Comment by lesliedh** [comment]
r1s-h5

**Comment by lesliedh** [comment]
r1s-h5，应该和你的平台差不多
