### ISSUE TITLE
不要默认开放 vlmcsd 到公网

### ISSUE THREAD

**Issue by LGA1150** [coolsnowwolf/lede#374]
每次更新固件，自定义防火墙设置总会多出一行 `iptables -A input_rule -p tcp --dport 1688 -j ACCEPT ## luci-app-vlmcsd`
这等于是把 vlmcsd 默认开放给了公网
据远景论坛某帖，巨硬扫描到了他公开的 KMS，并向他发了警告 http://bbs.pcbeta.com/viewthread-1781885-1-1.html

**Comment by daiaji** [comment]
是有这个问题……
提供选项就行了
不要默认开
各种意义上有安全问题
