### ISSUE TITLE
能否为SSR PLUS增加Socks5 over TLS模式？

### ISSUE THREAD

**Issue by BlackTouma** [coolsnowwolf/lede#3744]
最近发现大雕为SSR PLUS增加了Socks5模式。

不知道大雕可否考虑为其再增加一下Socks5 over TLS的功能呢？

**Comment by VNY0920** [comment]
搭车要求为SSR PLUS的Lan IP访问控制增加个功能，即：能指定某个设备使用为大陆白名单模式（绕过中国大陆IP模式）。
目前无法指定某个具体设备使用大陆白名单模式。
