### ISSUE TITLE
16M固件 带ssr 编译出来太大了 能否有个tiny版的ssr

### ISSUE THREAD

**Issue by vincheese** [coolsnowwolf/lede#3750]

**Comment by mjyhj** [comment]
16M 足够V2+GO版网易云解锁

**Comment by daidaiworm** [comment]
我是k2,8m。为什么不管选择什么配置，编译出来都是14m左右呢？

**Comment by coolsnowwolf** [comment]
ssr plus 本身才 65KB，不能再小了

**Comment by vincheese** [comment]
> ssr plus 本身才 65KB，不能再小了

v2和v2plugin  能否 不强制选择  就这两个占得大

**Comment by vincheese** [comment]
目前不选v2 就编译不过

**Comment by AmadeusGhost** [comment]
> > ssr plus 本身才 65KB，不能再小了
> 
> v2和v2plugin 能否 不强制选择 就这两个占得大

你可以`make menuconfig`的时候不选上啊，本身就没强制

**Comment by vincheese** [comment]
> ssr plus 本身才 65KB，不能再小了

老大 还有个问题  v2 和v2plugin 有关联吗  是不是只选一个就行

**Comment by coolsnowwolf** [comment]
都不用选

**Comment by liwenjie119** [comment]
ssrplus 不用kcptun的话不要选，很占地方

**Comment by DongfeiSay** [comment]
就有关V2端的挺大。。另外几个都很小
