### ISSUE TITLE
同时安装frpc frps 在luci面板Argon主题下有小问题

### ISSUE THREAD

**Issue by DongfeiSay** [coolsnowwolf/lede#3762]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：Argon主题下选择frpc会把服务从展开状态变成收起状态，拉开服务可以看到同时选中了frpc和frps

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：
![6](https://user-images.githubusercontent.com/49421020/76560691-b1fdbb80-64dc-11ea-9b87-398771c6ab1e.JPG)

**Comment by dolphinpaopao** [comment]
这个问题首先应该去主题作者那里反馈啊，修复速度快很多，虽然内置但是是可选而不是默认。上次去主题作者那里看了一下目前是有一些兼容问题。

**Comment by cooguyan** [comment]
自带的argon主题好像不是新版本。主题作者那边已经更新了很多了你可以去看看，就是需要自己编译。这是链接[luci-theme-argon](https://github.com/jerrykuku/luci-theme-argon)

**Comment by KumaTea** [comment]
Material主题也会有这个情况
