### ISSUE TITLE
建议SSR的socks5模式添加域名支持

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#3766]
SSR的socks5模式很有用，可以实现SSR的二级代理，但我试验发现socks5的服务器不能填写域名，只能填ip地址，如果用域名，redsocks2就会报错。所以这个二级代理的功能就大大削弱了。
建议大雕在启动服务时对域名做个解析。谢谢大雕。

**Comment by waterun** [comment]
我本来想用我家里的服务器做SSR服务，公司的op做二级代理，因为公司的线路国际出口不稳定，本来想用这个socks5做代理，家里用的是DDNS动态域名，无奈不能用域名。

**Comment by xiaozizi58** [comment]
我一直可以用域名啊 正常

**Comment by guochan2019** [comment]
用Zerotier曲线救国，使用内网IP

**Comment by waterun** [comment]
> 我一直可以用域名啊 正常

远端是ssr中开启的socks5服务器，本地是ssr使用socks5模式连接，你试试？如果用域名连接远端，服务根本无法运行，用命令行方式运行redsocks2 -c configfile 会提示 ‘type’没有启用，其实是启用了，只不过前面的字段应该是远程的ip地址，使用域名会造成解析错误而已。
