### ISSUE TITLE
求問大神，是否有寬帶多播功能？

### ISSUE THREAD

**Issue by bdgsfs** [coolsnowwolf/lede#3768]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：是否有寬帶多播功能？如果有，在哪裡添加

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by ankygit** [comment]
编译的时候，在luci的application里面选择syncdial 就可以了 。

**Comment by bdgsfs** [comment]
> 编译的时候，在luci的application里面选择syncdial 就可以了 。

非常感謝，我這就去試試
