### ISSUE TITLE
新版SSR节点自动更换有些频繁

### ISSUE THREAD

**Issue by swxk521** [coolsnowwolf/lede#3769]
OpenWrt R20.3.11 / LuCI Master (git-20.071.17905-38b5cd7)

节点稍微不稳定就自动更换了，能不能设置时间长一些

**Comment by dolphinpaopao** [comment]
话说你们真的都不看一下设置就来开issue的吗？真的怪不得对你们意见很大，ssr高级设置里面有超时设置。请不要随意开issue，甚为感谢。issue这个不是作为询问用的。
