### ISSUE TITLE
https端口转发问题

### ISSUE THREAD

**Issue by wangzhi859** [coolsnowwolf/lede#3777]
群辉https转发  内网端口5801到外网5801可以正常访问 但是外网端口转发改成别的就不能访问了  还有21端口和443不能转发到别的端口   
现在用的OpenWrt R9.10.10这个版本是可以随意转发的   试过其他很多版本都不行

**Comment by coolsnowwolf** [comment]
关闭 Flow 或者用 4.9 内核的 SFE 即可

**Comment by wangzhi859** [comment]
怎么关闭flow呀

**Comment by wangzhi859** [comment]
找到了  谢谢啦！
