### ISSUE TITLE
编译出现提示，怎么选

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#3778]
Atlas Scientific OEM SM sensors (ATLAS_PH_SENSOR) [N/m/y/?] n
Bosch Sensortec BME680 sensor driver (BME680) [N/m/y/?] n
AMS CCS811 VOC sensor (CCS811) [N/m/y/?] n
AMS iAQ-Core VOC sensors (IAQCORE) [N/m/y/?] n
SPS30 particulate matter sensor (SPS30) [N/m/y/?] (NEW)

**Comment by coolsnowwolf** [comment]
回车
