### ISSUE TITLE
编译内核选择

### ISSUE THREAD

**Issue by ledewrt** [coolsnowwolf/lede#3783]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
A：编译的时候在config里面CONFIG_LINUX_4_19=y 改为CONFIG_LINUX_4_14=y
但编译出来还是19的内核。不知道哪里出问题了。

**Comment by AmadeusGhost** [comment]
是改target的makefile而不是改config

**Comment by ledewrt** [comment]
ok，多谢
