### ISSUE TITLE
希望ssr-plus添加v2ray服务端

### ISSUE THREAD

**Issue by xghui** [coolsnowwolf/lede#3789]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：希望ssr-plus添加v2ray服务端

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：

**Comment by DongfeiSay** [comment]
下面不是有v2ray server吗？

**Comment by xghui** [comment]
ssr-plus这个插件只集成了ssr服务端，并没有集成v2ray服务端

**Comment by dolphinpaopao** [comment]
个个把作者当神仙，24h待命那种。issue里面90%的都是无效信息。这也叫issue？？明明自带只需编译勾选就完事也来一个issue。况且问题模板第一句就是提建议请删除。论坛QQ群搜索引擎获取答案速度更快。

**Comment by EnnawYang** [comment]
不是有v2ray server吗？？？？

**Comment by xxp2277** [comment]
集成进去干啥，只是为了看起来好看点？
