### ISSUE TITLE
KMS无法自动激活Windows

### ISSUE THREAD

**Issue by cnekol** [coolsnowwolf/lede#3800]
昨日重装了windows系统，发现没有自动激活windows，先前新配时候装系统时候可以自动激活，大概是1903或之前的版本。不知近来KMS是否有更新。

>安装使用MSDN镜像，最新1909版本。
>cn_windows_10_consumer_editions_version_1909_updated_jan_2020_x64_dvd_47161f17
>
>![image](https://user-images.githubusercontent.com/3054962/76675322-0bf0a500-65f3-11ea-9ec1-517537f7f5b0.png)
>![image](https://user-images.githubusercontent.com/3054962/76675343-1c088480-65f3-11ea-8cb3-22ed32d2dbaf.png)

**Comment by EnnawYang** [comment]
亲 您是不是走错地方了呢

**Comment by nikitazep** [comment]
你这不是vl批量注册版

**Comment by dolphinpaopao** [comment]
零售版向来不用kms

**Comment by cnekol** [comment]
抱歉，谢谢楼上同学们提醒。我才想起来是用的零售版本的细节。已使用其他工具激活。
