### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by sundog315** [coolsnowwolf/lede#3803]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [] 没有类似的issue
#3373  #3464 
但两个issue均已关闭且未提出解决方案

### (1) 具体问题

A：node编译错误

### (2) 路由器型号和固件版本

A：newifi d2

### (3) 详细日志

tools/v8_gypfiles/v8_base_without_compiler.host.mk:26: warning: ignoring old recipe for target '/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/obj/gen/inspector-generated-output-root/include/inspector/Schema.h'
  LD_LIBRARY_PATH=/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/lib.host:/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../tools/v8_gypfiles; mkdir -p /home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated; python ../../deps/v8/tools/run.py "/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/bytecode_builtins_list_generator" "/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated/bytecodes-builtins-list.h"
Traceback (most recent call last):
  File "../../deps/v8/tools/run.py", line 12, in <module>
    sys.exit(subprocess.call(sys.argv[1:]))
  File "/home/sd/lede/staging_dir/hostpkg/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/sd/lede/staging_dir/hostpkg/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/sd/lede/staging_dir/hostpkg/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
tools/v8_gypfiles/generate_bytecode_builtins_list.target.mk:13: recipe for target '/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated/bytecodes-builtins-list.h' failed
make[5]: *** [/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/out/Release/obj/gen/generate-bytecode-output-root/builtins-generated/bytecodes-builtins-list.h] Error 1
Makefile:101: recipe for target 'node' failed
make[4]: *** [node] Error 2
make[4]: Leaving directory '/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0'
Makefile:150: recipe for target '/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/.built' failed
make[3]: *** [/home/sd/lede/build_dir/target-mipsel_24kc_musl/node-v12.15.0/.built] Error 2
make[3]: Leaving directory '/home/sd/lede/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#1.04#3.73#5.46
package/Makefile:111: recipe for target 'package/feeds/packages/node/compile' failed
make[2]: *** [package/feeds/packages/node/compile] Error 2
make[2]: Leaving directory '/home/sd/lede'
package/Makefile:107: recipe for target '/home/sd/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/sd/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/sd/lede'
/home/sd/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by tudejun** [comment]
你解决这个问题了吗?我也出现这个问题了.
