### ISSUE TITLE
关于ssr-plus的自定义规则

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#3807]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：大佬好，能不能加一个功能？就是我想自己设置某些网址走哪条线路？
因为现在clash/openclash已有这个功能，
但还是觉得ssr+更稳定更强大并且支持的更多，
如果能有这个功能，感觉会更完美更nb!!
所以能不能考虑一下这个建议？

### (2) 路由器型号和固件版本

A：x86  j1900

### (3) 详细日志

A：无

**Comment by kl9800** [comment]
提这个需求的初衷是，因为如果你是订阅的话，几十条线路，总是用同一个，感觉有点浪费，毕竟那么多线路…

**Comment by coolsnowwolf** [comment]
很难做好，需要大量的改动

**Comment by kl9800** [comment]
好吧，谢谢大佬

**Comment by cppfuns** [comment]
如果能支持就好了，此时一些特殊的项目（openai）限制香港ip了，但是其他的还是优先使用香港的代理，所以希望特定的请求能走单独的代理
