### ISSUE TITLE
7.7下，X86_64为什么没有编译UEFI固件的选项了？

### ISSUE THREAD

**Issue by Fyred** [coolsnowwolf/lede#382]
难道又不支持UEFI启动和Hyper-v二代虚拟机了？

**Comment by saikm01** [comment]
生成Hyper-V的vhd镜像选项也没了。。。

**Comment by saikm01** [comment]
貌似是这条commit改了config/Config-images.in导致[https://github.com/coolsnowwolf/lede/commit/8fe0636b8af76b7ecc652e4cff83206fb0cd9097#diff-b3e5cdd5dfe8af84e9c16fdc53d53a9a](url)

**Comment by pepsing** [comment]
刚发现hyper-v的没有了，不过可以从ext4的转吧
