### ISSUE TITLE
#建议#SSR Plus的Lan IP访问控制增加 指定具体设备使用大陆白名单模式 的功能

### ISSUE THREAD

**Issue by VNY0920** [coolsnowwolf/lede#3824]
搭车要求为SSR PLUS的Lan IP访问控制增加个功能，即：能指定某个设备使用为大陆白名单模式（绕过中国大陆IP模式）。
目前无法指定某个具体设备使用大陆白名单模式。

**Comment by qianxu2001** [comment]
游戏模式就是绕过大陆模式

**Comment by DongfeiSay** [comment]
真要改建议直接贯彻到底，能指定各个设备专门使用什么样的代理方式 gf大陆回国全局游戏

**Comment by naoki66** [comment]
针对某些业务（netfilx）甚至需要全局，但是大部门只需要list就可以了。这个需求真的可以

**Comment by VNY0920** [comment]
switch，路由器开启游戏模式，用UDP中继服务器，nat变为F，
关掉游戏模式的UDP中继服务器后，变成 nat A。 PS4前后无变化，都是nat2.
感觉游戏模式的udp转发没啥卖点啊，难道因为我的udp中继服务器是ssr不是ss？

现在把游戏模式的udp转发关了，游戏机和Apple TV实际上走的是纯粹的大陆白名单，完美。
其他设备gfw模式
