### ISSUE TITLE
config中是不是取消了小米路由器3（R3）的配置么

### ISSUE THREAD

**Issue by maryjeck** [coolsnowwolf/lede#3827]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：找不到R3的配置

### (2) 路由器型号和固件版本

A：小米路由器3（R3）

### (3) 详细日志

A：

**Comment by 4593645** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ ]  没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> A：找不到R3的配置
> 
> ### (2) 路由器型号和固件版本
> A：小米路由器3（R3）
> 
> ### (3) 详细日志
> A：

同问是不是取消了NETGEAR-WNDR3800 自从去年某版本能编译成功后，最新版本一直编译成功就没有生成目标包。是不是大小控制限制了？辛苦大神！
