### ISSUE TITLE
gfw无法起作用

### ISSUE THREAD

**Issue by miroda** [coolsnowwolf/lede#3828]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：gfw开启之后，进入全局模式，腾讯视频等应用显示没有版权无法观看

### (2) 路由器型号和固件版本

A：Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread
OpenWrt R20.3.11 / LuCI Master (git-20.071.17905-38b5cd7)

### (3) 详细日志

A：日志不知道在哪里看

**Comment by SharerMax** [comment]
你在说什么？
> gfw开启之后，进入全局模式 

到底是GFW模式还是全局模式？

**Comment by miroda** [comment]
我开启的是gfw模式，实际上变成了全局模式。

**Comment by SharerMax** [comment]
无法复现
有使用其它服务么

**Comment by miroda** [comment]
我这边一直是这个情况 ，我不知道为何，lean的固件 之前都是好的，后面就不行了。

**Comment by miroda** [comment]
腾讯和国内的服务都被代理了 ，为何？
如何排查这个问题，是否有办法？

**Comment by miroda** [comment]
我就ssr plus+这一个 服务

**Comment by EnnawYang** [comment]
实测并没有发现任何异常

**Comment by miroda** [comment]
是否能有看日志的方法，帮助排查一下这个问题的原因

**Comment by miroda** [comment]
![photo_2020-03-16_18-25-15](https://user-images.githubusercontent.com/2841126/76747110-9849c600-67b3-11ea-9a7c-fce99f57ac11.jpg)

**Comment by miroda** [comment]
![屏幕截图(15)](https://user-images.githubusercontent.com/2841126/76747251-d34bf980-67b3-11ea-842d-9edf9495a271.png)

**Comment by miroda** [comment]
![屏幕截图(17)](https://user-images.githubusercontent.com/2841126/76747367-fb3b5d00-67b3-11ea-85b6-2d210073112d.png)

**Comment by SharerMax** [comment]
看看访问控制，强制代理的域名

**Comment by miroda** [comment]
dlercloud.me
cn.engadget.com
www.keystonejs.com
https://justmysocks.net/

**Comment by miroda** [comment]
找到问题了，最后一行 造成的，去掉就好了 ，啊，受不了了

**Comment by SharerMax** [comment]
这里填的域名不是url，注意一下

miroda <notifications@github.com> 于 2020年3月16日周一 21:46写道：
