### ISSUE TITLE
docker运行反应贼慢，原版openwrt就没问题

### ISSUE THREAD

**Issue by ichris007** [coolsnowwolf/lede#3834]
docker运行openwrt_r9:20.1.24-x86_64，登陆op界面后，反应很慢，改一个设置要等好几秒刷新，我看网上有说是/etc/resolv.conf dns问题，但是本人不是技术人员，不知道怎么改？还请大神明示

**Comment by notepad2** [comment]
嗯，我这里也差不多，我编译了2个版本，网件3700v4和4300v1，硬件其实是一样的，都是打开一个页面刷新要等很久。

**Comment by ZqinKing** [comment]
我上上周编译的没问题，上周编译的也这样，很慢。

**Comment by ichris007** [comment]
@notepad2 @ZqinKing 最后两位是怎么解决这个问题的？

**Comment by notepad2** [comment]
尚未解决。

**Comment by ichris007** [comment]
@notepad2 我换了另一个版本
