### ISSUE TITLE
没人遇到过这个问题吗，来说说我新发现 当手机第一次安装网易云音乐打开能正常解锁，但是当手机杀掉这个进程或者重启之后 就不能解锁了，这是不是某些代码中的bug

### ISSUE THREAD

**Issue by 1-github-1** [coolsnowwolf/lede#3836]
没人遇到过这个问题吗，来说说我新发现 当手机第一次安装网易云音乐打开能正常解锁，但是当手机杀掉这个进程或者重启之后 就不能自动解锁了，需要设置wifi代理才行 
_Originally posted by @1-github-1 in https://github.com/coolsnowwolf/lede/issues/3747#issuecomment-599425434_

**Comment by camino13** [comment]
在下面添加个例外
![image](https://user-images.githubusercontent.com/54771820/76743982-769a1000-67ae-11ea-95ba-0112e7c0bfac.png)

IP地址填入你运行UnblockNeteaseMusic的局域网IP

**Comment by 1-github-1** [comment]
> 在下面添加个例外
> ![图片](https://user-images.githubusercontent.com/54771820/76743982-769a1000-67ae-11ea-95ba-0112e7c0bfac.png)
> 
> IP地址填入您运行UnblockNeteaseMusic的初始化IP

不行啊大神 你的可以吗 我是电脑能正常解锁 手机不设置代理不行

**Comment by xxp2277** [comment]
> 在下面添加个例外
> ![image](https://user-images.githubusercontent.com/54771820/76743982-769a1000-67ae-11ea-95ba-0112e7c0bfac.png)
> 
> IP地址填入你运行UnblockNeteaseMusic的局域网IP

搭车问下，在外面使用ssr连回家里面的路由器，云音乐怎么设置才能解锁。

**Comment by Zack0617** [comment]
> > 在下面添加个例外
> > ![image](https://user-images.githubusercontent.com/54771820/76743982-769a1000-67ae-11ea-95ba-0112e7c0bfac.png)
> > IP地址填入你运行UnblockNeteaseMusic的局域网IP
> 
> 搭车问下，在外面使用ssr连回家里面的路由器，云音乐怎么设置才能解锁。

softether vpn回家，不需要额外设置就可以云音乐解锁。
