### ISSUE TITLE
ipv6无法显示虚拟动态接口

### ISSUE THREAD

**Issue by mgsqz** [coolsnowwolf/lede#3842]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：同一虚拟机平台，用openwrt官方19.07.1版本拨号以及ipv6测试如下
![op-jk](https://user-images.githubusercontent.com/31202580/76777529-44ef6c00-67e3-11ea-99ad-7ab2000d274a.JPG)

![op-v6](https://user-images.githubusercontent.com/31202580/76777545-4a4cb680-67e3-11ea-9ec0-72e040e9d0e6.JPG)

而用commits 87922d5编译的lede（已选择ipv6helper）拨号以及ipv6测试如下
![lede-jk](https://user-images.githubusercontent.com/31202580/76777563-53d61e80-67e3-11ea-805b-f2fffe46f739.JPG)

![lede-v6](https://user-images.githubusercontent.com/31202580/76777569-55074b80-67e3-11ea-861e-e8c09cd9545d.JPG)

dhcpv6设置都是服务器模式+无状态&有状态模式

### (2) 路由器型号和固件版本

A：x86 OpenWrt R20.3.11使用commits 87922d5编译

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
特意的，新功能

**Comment by ckxt** [comment]
ipv6 我用电脑拨号没问题，用op拨号不行 哎...恩山上找了很多教程试了都不行  现在直接放弃了

**Comment by ledewrt** [comment]
大佬禁用了ipv6解析dns服务，所以你网页打不开ipv6.但下载如迅雷可以用ipv6.

**Comment by tanst** [comment]
![image](https://user-images.githubusercontent.com/4686616/76937885-93f6e780-6930-11ea-94bb-040ecc173418.png)
