### ISSUE TITLE
Argon样式问题

### ISSUE THREAD

**Issue by wybb** [coolsnowwolf/lede#3863]
假如没有选择安装luci-app-vsftpd，那么“网络存储”这个菜单会变成“NAS”，而Argon的样式表是对文本硬编码判断的
.main > .main-left > .nav > .slide > .menu[data-title= 网络存储 ]:before{
	content: "\e90c";
}
这就导致了NAS的菜单项缺少图标

简单粗暴一些么就是直接给NAS再加个样式

.main > .main-left > .nav > .slide > .menu[data-title= NAS ]:before{
content: "\e90c";
}

最好还是让没有安装vsftpd的时候也能显示正常的中文菜单名

**Comment by EnnawYang** [comment]
这问题很早就有了 所以现在ftp都是必备的

**Comment by Awrtiger** [comment]
你可以编译的时候，改一下新的，在这里[维护项目](https://github.com/jerrykuku/luci-theme-argon) 反馈一下？

**Comment by wangzhuok** [comment]
你可以自己同步最新的luci-theme-argon
