### ISSUE TITLE
shadowsocks插件

### ISSUE THREAD

**Issue by wangfeng87** [coolsnowwolf/lede#3878]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：最新的ssrplus里shadowsocks插件集成了哪些，例如：GoQuiet；V2ray-plugin；cloak;kcptun

### (2) 路由器型号和固件版本

A：新路由3潘多拉固件

### (3) 详细日志

A：

**Comment by dolphinpaopao** [comment]
??没看懂这是什么issue。
