### ISSUE TITLE
SSR PLUS+更新订阅服务器节点不成功！ 

### ISSUE THREAD

**Issue by xtwz** [coolsnowwolf/lede#3884]
## 1. 详细叙述

1、编译最新版本后，SSR PLUS+更新订阅服务器节点不成功，服务器节点列表空白，之前版本可以正常更新。
2、尝试更换其他机场订阅URL又可以更新成功。  

部分机场的订阅URL更新不了！

**Comment by hxlls** [comment]
要学会提问和反馈，啥都没有，就抛一个更新不了，谁能解决？如果只是为了抱怨而来的，就没必要在issue提了，没人管你的。

**Comment by xtwz** [comment]
我是小白，只能提一些简单的问题。刚刚把订阅URL删掉重新添加又可以了。 谢谢你的回复。

**Comment by R3pl4c3r** [comment]
Please follow the instructions to open your issue. Complaining doesn't take any effects. Only when you paste your log and show your subscription link privately to Lean, can we solve the problem together. Now that the problem has been solved, please close this issue.
