### ISSUE TITLE
如何驱动I2C设备（如：SSD1306 OLED 显示屏(128x64)）

### ISSUE THREAD

**Issue by hedahong** [coolsnowwolf/lede#3885]
## 2. 详细叙述

我想给路由器加个显示屏幕，显示一下信息。

### (1) 具体问题

A： 如何驱动I2C设备（如：SSD1306 OLED 显示屏(128x64)）
比如某宝地址https://detail.tmall.com/item.htm?id=42044259331&ali_refid=a3_430583_1006:1109983619:N:byiy05d59P/xOaGHCwnXCczU4Tsjyaxj:f9ef1aa00cee0c093fe93aed8d756ca8&ali_trackid=1_f9ef1aa00cee0c093fe93aed8d756ca8&spm=a230r.1.14.1&skuId=4288923395698

### (2) 路由器型号和固件版本

A：树莓派3 或4

### (3) 详细日志

A：

**Comment by hyird** [comment]
树莓派是GPIO吧  找找相关的驱动 而且 没有现成的库 要控制GPIO估计得用C 直接操寄存器了
