### ISSUE TITLE
有没有计划集成 AdGuard Home 插件？

### ISSUE THREAD

**Issue by xhqpp** [coolsnowwolf/lede#3886]
有没有计划集成 AdGuard Home 插件？

**Comment by Aes64X** [comment]
没有必要，有相应的源码，自己弄一个复制粘贴就完成了，再不济作者提供了ipk，安装就好。
直接集成其执行文件mips的就高达13+mb，那些32mb空间的路由你让他们怎么办？还有因过滤记录不断吃空间的数据库文件。

**Comment by Aes64X** [comment]
我用的就是配置文件、主程序、工作目录全都跑在外置存储上，路由器本身的存储空间跑AdGuard Home根本不够用。

**Comment by Fyred** [comment]
adbyby已经支持AdGuard Home规则了吧

**Comment by xhqpp** [comment]
哎 现在的手机起步都128GB了 路由器还在32MB挣扎 厂家为了压缩成本能32MB的绝对不会给你64MB 希望软路由出现独立品牌 整个行业都会进行洗牌

**Comment by sky137818221** [comment]
> 哎 现在的手机起步都128GB了 路由器还在32MB挣扎 厂家为了压缩成本能32MB的绝对不会给你64MB 希望软路由出现独立品牌 整个行业都会进行洗牌

了解一下什么叫嵌入式开发 目的 流程
