### ISSUE TITLE
Flow Offloading 貌似有问题

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#3887]
固件为最新版本
详细症状是，开启Flow Offloading 后，进行端口转发，从外网SSH或者进行web 浏览，速度会非常慢，SSH 从LAN 端服务器内下载文件，才0.3M/S左右。但是关闭后下载能达到上传上限，8M/S 做了web 服务器，关闭后响应速度也快很多很多，可以说是缩小的时间是按分钟为单位，基本可以抛弃测试波动的原因
这个问题其实在3.8版本已经发现，期间进行过恢复出厂升级，或者保留配置升级，但是都没解决，但是一直没找到是什么引起的故障，可能更早的版本也存在
固件基本是默认编译，加上了tty 这种不影响网络的一些小功能，无mwan 无docker 
系统日志和内核日志找不到对应的日志显示，所以没法帖出
不懂是不是人有类似的问题？

**Comment by coolsnowwolf** [comment]
建议换 4.14 内核测试看看

**Comment by hxlls** [comment]
好的，我更换试试

**Comment by WayChan** [comment]
请问你更换内核之后有效果吗

**Comment by hxlls** [comment]
没效果，可能是Flow Offloading 和iptable 有冲突，现在选择关闭Flow Offloading，因为这个不单只影响这个，还影响了其他不少的功能
