### ISSUE TITLE
酸酸乳plus内置ad过滤订阅默认地址失效

### ISSUE THREAD

**Issue by azxcvjj** [coolsnowwolf/lede#3888]
酸酸乳plus内置ad过滤订阅默认gitee地址失效，建议跟换至github地址
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

**Comment by Aes64X** [comment]
额。。。。确实诶，再等等？估计码云维护呢吧。

**Comment by starxu1971** [comment]
有啊

**Comment by azxcvjj** [comment]
> 有啊

昨天码云维护。。。
