### ISSUE TITLE
歌华链V0.4编译最新版固件无法启动 无限重启 附带日志

### ISSUE THREAD

**Issue by xjboss** [coolsnowwolf/lede#3894]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：启动不了 会发生无限重启的现象 看起来像是找不到分区？

### (2) 路由器型号和固件版本

A：歌华链 V0.4

### (3) 详细日志

路由器日志：
Boot and Recovery Environment for Embedded Devices
Copyright (C) 2020 HackPascal <hackpascal@gmail.com>
Build date 2020-01-14 [git-b25d507]
Version 1.1 (r1280)

DRAM: 512MB
Platform: MediaTek MT7621A ver 1, eco 3
Board: GeHua GHL-R-001
Clocks: CPU: 880MHz, DDR: 1066MHz, Bus: 293MHz, Ref: 40MHz
Flash: Macronix MX25L25635E (32MB) on mt7621-spi.0
rt2880-eth: MAC address from EEPROM is invalid, using default settings.
rt2880-eth: Using MAC address 00:0c:43:00:00:01
eth0: MediaTek MT7530 Gigabit switch

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ... 0   

Trying to boot firmware from 0x00050000 in flash bank 0 ...
Reading data into memory ...
U-Boot firmware image header detected.
    Image Name:   MIPS OpenWrt Linux-4.14.172
    Data Size:    2021900 Bytes
    Load Address: 80001000
    Entry Point:  80001000
Uncompressing data (LZMA) ... done.
Flushing cache ... done.

Starting kernel at 0x80001000...

[    0.000000] Linux version 4.14.172 (build@UbuntuBuilder) (gcc version 7.5.0 (OpenWrt GCC 7.5.0 r2301-2b09def6)) #0 SMP Thu Mar 19 05:44:18 2020
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is GeHua GHL-R-001
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 1c000000 @ 00000000 (usable)
[    0.000000]  memory: 04000000 @ 20000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   HighMem  [mem 0x0000000010000000-0x0000000023ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000]   node   0: [mem 0x0000000020000000-0x0000000023ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000023ffffff]
[    0.000000] random: get_random_bytes called from start_kernel+0x9c/0x4d8 with crng_init=0
[    0.000000] percpu: Embedded 14 pages/cpu s26832 r8192 d22320 u57344
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130496
[    0.000000] Kernel command line: console=ttyS0,57600 rootfstype=squashfs,jffs2
[    0.000000] PID hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 510960K/524288K available (4791K kernel code, 248K rwdata, 1048K rodata, 1260K init, 254K bss, 13328K reserved, 0K cma-reserved, 262144K highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 256
[    0.000000] CPU Clock: 880MHz
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0xcaf478abb4, max_idle_ns: 440795247997 ns
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 4343773742 ns
[    0.000010] sched_clock: 32 bits at 440MHz, resolution 2ns, wraps every 4880645118ns
[    0.015517] Calibrating delay loop... 586.13 BogoMIPS (lpj=2930688)
[    0.087840] pid_max: default: 32768 minimum: 301
[    0.097204] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.110226] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.126444] Hierarchical SRCU implementation.
[    0.136001] smp: Bringing up secondary CPUs ...
[    6.662802] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    6.662811] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    6.662824] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    6.662968] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.205300] Synchronize counters for CPU 1: done.
[    6.407665] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    6.407675] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    6.407682] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    6.407762] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.326099] Synchronize counters for CPU 2: done.
[    6.526918] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    6.526927] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    6.526935] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    6.527014] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.445665] Synchronize counters for CPU 3: done.
[    0.505267] smp: Brought up 1 node, 4 CPUs
[    0.517196] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.536678] futex hash table entries: 1024 (order: 3, 32768 bytes)
[    0.549261] pinctrl core: initialized pinctrl subsystem
[    0.561098] NET: Registered protocol family 16
[    0.581619] pull PCIe RST: RALINK_RSTCTRL = 0
[    0.890438] release PCIe RST: RALINK_RSTCTRL = 7000000
[    0.900505] ***** Xtal 40MHz *****
[    0.907231] release PCIe RST: RALINK_RSTCTRL = 7000000
[    0.917437] Port 0 N_FTS = 1b105000
[    0.924337] Port 1 N_FTS = 1b105000
[    0.931261] Port 2 N_FTS = 1b102800
[    2.089356] PCIE2 no card, disable it(RST&CLK)
[    2.098047]  -> 21007f2
[    2.102870] PCIE0 enabled
[    2.108068] PCIE1 enabled
[    2.113251] PCI host bridge /pcie@1e140000 ranges:
[    2.122784]  MEM 0x0000000060000000..0x000000006fffffff
[    2.133136]   IO 0x000000001e160000..0x000000001e16ffff
[    2.143497] PCI coherence region base: 0xbfbf8000, mask/settings: 0x60000000
[    2.166955] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.178219] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.189422] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    2.201827] PCI host bridge to bus 0000:00
[    2.209845] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    2.223501] pci_bus 0000:00: root bus resource [io  0xffffffff]
[    2.235240] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    2.248721] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    2.266416] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    2.279449] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.293259] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    2.306388] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.320216] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    2.333694] pci 0000:00:01.0: BAR 8: assigned [mem 0x60100000-0x601fffff]
[    2.347174] pci 0000:00:01.0: BAR 9: assigned [mem 0x60200000-0x602fffff pref]
[    2.361514] pci 0000:00:00.0: BAR 1: assigned [mem 0x60300000-0x6030ffff]
[    2.374999] pci 0000:00:01.0: BAR 1: assigned [mem 0x60310000-0x6031ffff]
[    2.388480] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff]
[    2.401951] pci 0000:00:00.0: PCI bridge to [bus 01]
[    2.411788] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    2.425290] pci 0000:02:00.0: BAR 0: assigned [mem 0x60100000-0x601fffff 64bit]
[    2.439804] pci 0000:02:00.0: BAR 6: assigned [mem 0x60200000-0x6020ffff pref]
[    2.454133] pci 0000:00:01.0: PCI bridge to [bus 02]
[    2.463971] pci 0000:00:01.0:   bridge window [mem 0x60100000-0x601fffff]
[    2.477461] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff pref]
[    2.493230] clocksource: Switched to clocksource GIC
[    2.504706] NET: Registered protocol family 2
[    2.514019] TCP established hash table entries: 2048 (order: 1, 8192 bytes)
[    2.527772] TCP bind hash table entries: 2048 (order: 2, 16384 bytes)
[    2.540556] TCP: Hash tables configured (established 2048 bind 2048)
[    2.553313] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    2.564812] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    2.577499] NET: Registered protocol family 1
[    2.823182] 4 CPUs re-calibrate udelay(lpj = 2924544)
[    2.834499] Crashlog allocated RAM at address 0x3f00000
[    2.845555] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    2.865956] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    2.877487] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    2.899971] random: fast init done
[    2.907495] bounce: pool size: 64 pages
[    2.915000] io scheduler noop registered
[    2.922735] io scheduler deadline registered (default)
[    2.934030] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    2.947913] console [ttyS0] disabled
[    2.955024] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 19, base_baud = 3125000) is a 16550A
[    2.972915] console [ttyS0] enabled
[    2.972915] console [ttyS0] enabled
[    2.986706] bootconsole [early0] disabled
[    2.986706] bootconsole [early0] disabled
[    3.003408] 1e000e00.uartlite3: ttyS1 at MMIO 0x1e000e00 (irq = 20, base_baud = 3125000) is a 16550A
[    3.023649] MediaTek Nand driver init, version v2.1 Fix AHB virt2phys error
[    3.037903] spi-mt7621 1e000b00.spi: sys_freq: 220000000
[    3.049454] m25p80 spi0.0: mx25l25635f (32768 Kbytes)
[    3.059601] 4 fixed-partitions partitions found on MTD device spi0.0
[    3.072265] Creating 4 MTD partitions on "spi0.0":
[    3.081815] 0x000000000000-0x000000030000 : "u-boot"
[    3.092782] 0x000000030000-0x000000040000 : "u-boot-env"
[    3.104363] 0x000000040000-0x000000050000 : "factory"
[    3.115422] 0x000000050000-0x000002000000 : "firmware"
[    3.149199] libphy: Fixed MDIO Bus: probed
[    3.225087] mtk_soc_eth 1e100000.ethernet: generated random MAC address 00:00:00:00:00:00
[    3.241539] libphy: mdio: probed
[    4.648908] mtk_soc_eth 1e100000.ethernet: loaded mt7530 driver
[    4.661400] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 22
[    4.680460] NET: Registered protocol family 10
[    4.690966] Segment Routing with IPv6
[    4.698389] NET: Registered protocol family 17
[    4.707311] 8021q: 802.1Q VLAN Support v1.8
[    4.718161] hctosys: unable to open rtc device (rtc0)
[    4.729113] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    4.744025] Please append a correct "root=" boot option; here are the available partitions:
[    4.760655] 1f00             192 mtdblock0 
[    4.760662]  (driver?)
[    4.773671] 1f01              64 mtdblock1 
[    4.773676]  (driver?)
[    4.786672] 1f02              64 mtdblock2 
[    4.786677]  (driver?)
[    4.799673] 1f03           32448 mtdblock3 
[    4.799678]  (driver?)
[    4.812678] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    4.830794] Rebooting in 1 seconds..
看起来无法找到分区？？？不知道怎么解决

**Comment by yinzhefuyun** [comment]
看来忘记打高通补丁了，firmware又无法解开了

**Comment by AmadeusGhost** [comment]
你可以试下 #3906 中的gehua_ghl-r-001-e

**Comment by ify358** [comment]
2000-3-20 编译了下，也是无限重启

**Comment by AmadeusGhost** [comment]
> 2000-3-20 编译了下，也是无限重启

你可以测试下我的pr，最简单的改法如下：
```
--- a/target/linux/ramips/dts/mt7621_gehua_ghl-r-001.dts
+++ b/target/linux/ramips/dts/mt7621_gehua_ghl-r-001.dts
@@ -49,10 +49,9 @@
 	status = "okay";
 
 	flash@0 {
-		compatible = "mx25l25635f", "jedec,spi-nor";
+		compatible = "jedec,spi-nor";
 		reg = <0>;
 		spi-max-frequency = <25000000>;
-		m25p,fast-read;
 
 		partitions {
 			compatible = "fixed-partitions";
```
![e](https://user-images.githubusercontent.com/42570690/77185184-f1935b80-6b0b-11ea-86c3-0fb4e31d9699.png)

**Comment by xjboss** [comment]
我试试

**Comment by xjboss** [comment]
我这个貌似是MX25L25635F的闪存？？？？芯片上面写着

**Comment by yinzhefuyun** [comment]
> 我这个貌似是MX25L25635F的闪存？？？？芯片上面写着

openwrt官方就没有这个spi驱动

**Comment by AmadeusGhost** [comment]
> 我这个貌似是MX25L25635F的闪存？？？？芯片上面写着
> 但它竟然能正常的运作 反而F的不行

所以就是e的可以正常工作吗？

**Comment by xjboss** [comment]
@AmadeusGhost 是的，但我用的你的PR可能有点问题，有线网连不上，我试试只加补丁。

**Comment by AmadeusGhost** [comment]
> @AmadeusGhost 是的，但我用的你的PR可能有点问题，有线网连不上，我试试只加补丁。

那是我的锅2333，重命名了其它地方没改，既然e能用于f，那我就直接统一为e不拆分成2个了。

**Comment by xjboss** [comment]
或许可能F芯片有好几种版本也说不定，我这个路由的闪存进BREED也说我是MX25L25635E。然后因为MWAN3有问题我试了官方的OPENWRT 19.07，发现也炸了。

**Comment by yinzhefuyun** [comment]
> 或许可能F芯片有好几种版本也说不定，这个改了以后我用起来完全没问题。我这个路由的闪存进BREED也说我是MX25L25635E。然后因为MWAN3有问题我试了官方的OPENWRT 19.07，发现也炸了。

不是看能不能用，你还要测试在web页面点击重启能不能重启，这个才是关键

**Comment by xjboss** [comment]
重启看起来是会出问题  直接卡住了 官方的和这个版本都会这样子

**Comment by yinzhefuyun** [comment]
> 重启看起来是会出问题 直接卡住了 官方的和这个版本都会这样子
操，歌华链轮回了，下一个bug，是不是在web上传bin文件，显示不兼容？
只能等lean的高通spi驱动了

**Comment by AmadeusGhost** [comment]
> 只能等lean的高通spi驱动了

你所说的是指`target/linux/ipq40xx/patches-4.14/303-spi-nor-enable-4B-opcodes-for-mx25l25635f.patch`吧，这个补丁ramips一样有的，而且强制指定为f对部分机子来说会无法启动

**Comment by xjboss** [comment]
我按照给旧版本用的408-spi-nor-m25p-shutdown-for-mx25l25635f.patch C+V乐乐了一个补丁 好像可以用了

[408-spi-nor-m25p-shutdown-for-mx25l25635f.zip](https://github.com/coolsnowwolf/lede/files/4364907/408-spi-nor-m25p-shutdown-for-mx25l25635f.zip)

**Comment by AmadeusGhost** [comment]
> 就发个文件不提交 pull request了，我感觉兼容性可能没那么吼。

看了下x-wrt也是这么处理的，那兼容性应该还好
https://github.com/x-wrt/x-wrt/commit/e0f7d20dda7e55e663d0c24887b5217cf03e0597

**Comment by ify358** [comment]
看到2020-03-21的更新重新编译，今天刷了正常。

**Comment by yinzhefuyun** [comment]
> 看到2020-03-21的更新重新编译，今天刷了正常。

你的正常是正常开机吗？在web下可以点击重启来重启吗？能在web下升级bin文件吗？

**Comment by AmadeusGhost** [comment]
> 就发个文件不提交 pull request了，我感觉兼容性可能没那么吼。

这个跟`target/linux/ramips/patches-4.14/999-fix-m25p-shutdown.patch`差不多吧，就是第一个patch的位置不一样（

**Comment by xjboss** [comment]
哦对我可能搞混了原版和这个版本 这个版本其实并不会重启死机 原版没这个补丁

**Comment by ify358** [comment]
> > 看到2020-03-21的更新重新编译，今天刷了正常。
> 
> 你的正常是正常开机吗？在web下可以点击重启来重启吗？能在web下升级bin文件吗？

breed 刷的sysupgrade   openwrt-ramips-mt7621-gehua_ghl-r-001-squashfs-sysupgrade.bin

**Comment by ify358** [comment]
> > 看到2020-03-21的更新重新编译，今天刷了正常。
> 
> 你的正常是正常开机吗？在web下可以点击重启来重启吗？能在web下升级bin文件吗？

刷完自动重启不行。拔了插头再插可以了

**Comment by caoli5288** [comment]
你个浓眉大眼的也淘了个矿机吗，我也淘了个233
