### ISSUE TITLE
如下错误有啥影响？

### ISSUE THREAD

**Issue by vincentchen** [coolsnowwolf/lede#39]
cp -fpR /root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx /root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root.orig-bcm53xx
/root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
/root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
/etc/init.d/arpbind does not have a START or STOP value
/root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/ssrpro: line 22: network_get_subnet: command not found
/root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/init.d/ssrpro: line 23: network_get_ipaddr: command not found
Create '/root/lede/build_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/etc/filesystems'.
Add 'ntfs-3g' to known filesystems.
./etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
./etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
/etc/init.d/arpbind does not have a START or STOP value
./etc/init.d/ssrpro: line 22: network_get_subnet: command not found
./etc/init.d/ssrpro: line 23: network_get_ipaddr: command not found

**Comment by coolsnowwolf** [comment]
忽略
