### ISSUE TITLE
ssr+能不能给一个自定义gfw订阅地址的选项？

### ISSUE THREAD

**Issue by Benjamin23333** [coolsnowwolf/lede#3902]
既然大陆ip可以自定义订阅地址，那可不可以增加一个gfw列表的自定义订阅地址选项？

**Comment by qianxu2001** [comment]
不行，你看一眼现在用的 gfwlist 里面是什么样就知道了，除非你能找到个结构一样的规则才能替换，否则这一部分代码都要改

**Comment by coolsnowwolf** [comment]
主要是没找到靠谱的第三方更新源

**Comment by Benjamin23333** [comment]
> 主要是没找到靠谱的第三方更新源

我记得passwall的gfw最近更新是三月十号，您要不看看lienol的能不能借用？

**Comment by martin0607** [comment]
https://github.com/hq450/fancyss/tree/master/rules

不知道这套规则怎么样

**Comment by coolsnowwolf** [comment]
信不过

**Comment by agutools** [comment]
也可以在/usr/share/shadowsocksr/update.lua中“自定义”😅

**Comment by stuarthua** [comment]
+1
觉得还是有必要的，不同区域的阻断可能不同，有时会 clone 一份 gfwlist 仓库，base64 Decode 一下，自用，格式相同的情况下还是蛮希望能增加自定义订阅地址的选项的，也方便重置后的云同步
