### ISSUE TITLE
对于使用brcmfmac4366c0的机型，经测试已经没有必要使用k3wifi这个插件了，OpenWrt官方的已经足够好

### ISSUE THREAD

**Issue by likanchen** [coolsnowwolf/lede#3903]
如题，在部分机型比如斐讯k3的编译测试中，无论是使用官方的参数：
BRCMFMAC_4366C0 := $(IEEE8021X) kmod-brcmfmac brcmfmac-firmware-4366c0-pcie
还是使用目前LEAN LEDE的参数：
BRCMFMAC_4366C0 := $(IEEE8021X) kmod-brcmfmac k3wifi
在实际固件测试中已经没有明显差异了，是否表示已经没有必要使用k3wifi这个插件？

**Comment by lwz322** [comment]
我昨天刷的官方固件，5G不支持高信道，上传速度正常，但是下行速度不超过100Mbps
