### ISSUE TITLE
baidupcs web使用bduss登陆失效问题

### ISSUE THREAD

**Issue by hhmaomao** [coolsnowwolf/lede#3904]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：最新编译的x86固件，2020年3月18日编译的固件，编译后发现baidupcs web里面的bduss登陆无法使用，复制bduss后按登陆按键出现不停转圈，无法正常登陆，重启主机后仍然无法解决。

### (2) 路由器型号和固件版本

A：X86路由器

### (3) 详细日志

A：

**Comment by lm317379829** [comment]
这个去baidupcs-web作者哪里去反馈吧。
https://github.com/liuzhuoling2011/baidupcs-web/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by hhmaomao** [comment]
好的，麻烦你
