### ISSUE TITLE
有没有方法在多拨的情况下实现upnp？

### ISSUE THREAD

**Issue by xhqpp** [coolsnowwolf/lede#3910]
实测多拨后upnp就失效了，有没有办法能同时使用的？

**Comment by shenyz** [comment]
实测没有失效
![image](https://user-images.githubusercontent.com/2944410/77221222-c5ff8800-6b82-11ea-9152-ec8bcb50a027.png)
![image](https://user-images.githubusercontent.com/2944410/77221224-d0ba1d00-6b82-11ea-8bb7-0514db678217.png)

**Comment by xhqpp** [comment]
> 实测没有失效
> ![image](https://user-images.githubusercontent.com/2944410/77221222-c5ff8800-6b82-11ea-9152-ec8bcb50a027.png)
> ![image](https://user-images.githubusercontent.com/2944410/77221224-d0ba1d00-6b82-11ea-8bb7-0514db678217.png)

我这里也有映射 但实测是不通的 你这个是通的吗？另外你能测一下v2模式通不通吗？

**Comment by badcrazy** [comment]
我只知道之前是正常的，因为我半年多拨了，现在不知道，不过之前有个人说用所有lean编译的固件都不能开彗星的upnp，但是我测下来是正常的，大部分人正常，个别人确实不正常，所以应该不是源码问题，还是设备和网络环境的关系
