### ISSUE TITLE
广告屏蔽大师 Plus+ 添加新的广告条目

### ISSUE THREAD

**Issue by 5mouth** [coolsnowwolf/lede#3912]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述

在广告屏蔽大师中添加【r2---sn-i3beln7k.googlevideo.com】条目用于过滤移动端（安卓） youtube视频广告。

### (1) 具体问题
在广告屏蔽大师中添加【r2---sn-i3beln7k.googlevideo.com】条目用于过滤移动端（安卓） youtube视频广告。或者可以自定义广告源更新。
A：

### (2) 路由器型号和固件版本
不涉及，本环境使用esxi软路由。
A：

### (3) 详细日志

A：

**Comment by mjyhj** [comment]
广告规则去 adbyby官方提交
