### ISSUE TITLE
请问各位大佬  ipv6 有防火墙吗 应该怎么设置了

### ISSUE THREAD

**Issue by graytoowolf** [coolsnowwolf/lede#3914]
我能访问ipv6 网站.  笔记本链接手机热点 ,设置网页服务器  我电脑能打开. 就是手机 不能用IPV6 访问我路由后台
 请问下要怎么设置了  笔记本 是可以用ipv6 ping通路由后台的 就是打不开

**Comment by lwz322** [comment]
OpenWrt的防火墙默认会拒绝外来的传入连接，大多数路由器系统都是这样的，以确保内网设备不会暴露在公网，所以这方面还是小心

在OpenWrt的LuCi界面的Network->Firewall->Traffic Rules一栏可以看到各种防火墙的规则，可以看到OpenWrt是默认允许外网Ping内网的（Allow-ICMPv6-Forward），为了方便开关，建议为每个需求单独建一条防火墙规则

因为是处理传入连接，所以这里只用到了Input链和Forward链，在Open ports on router（打开路由器端口）默认添加的是Input链的规则，针对的是路由器本机，在New forward rule（打开路由器端口）默认添加的是Forward链的规则，针对的是路由器的下属设备，添加之后还可以进一步设置（端口之类的过滤条件）

部分可以参考：[内网设备的外网访问](https://lwz322.github.io/2019/07/25/IPv6_Home.html#内网设备的外网访问)
