### ISSUE TITLE
小米AX3600支持

### ISSUE THREAD

**Issue by yisiliang** [coolsnowwolf/lede#3916]
以后会支持小米AX3600吗？

**Comment by Aes64X** [comment]
自己去看Op官方主线，2年之内么得，AX3600 锁启动

**Comment by jiayouzl** [comment]
哈哈哈哈AX3600?????逗呢

**Comment by dolphinpaopao** [comment]
漏油器不是x86兼容机，驱动，芯片等限制何其多。所以现在硬漏油是沦为了AP的存在，软+硬方案最灵活。要性能有性能要功能有功能要折腾能折腾。

**Comment by EstFoxs** [comment]
> 自己去看Op官方主线，2年之内么得，AX3600 锁启动

有链接不？瞅瞅去

**Comment by ElectronicElephant** [comment]
等上游支持吧

**Comment by KevinZjYang** [comment]
> > 自己去看Op官方主线，2年之内么得，AX3600 锁启动
> 
> 有链接不？瞅瞅去

https://openwrt.org/zh/toh/start?dataflt%5BBrand*%7E%5D=xiaomi#folded_zh:toh:start_1
