### ISSUE TITLE
菜鸟求助：error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by nnwins** [coolsnowwolf/lede#3917]
不懂怎么设置权限，按网上的要求都做了。。。。。使用平台是虚拟机PVE里面。。。。已经成功实现第一次编译，然后隔开几周，现在就变成这样了

lm@ubuntu:~/lede$ ./scripts/feeds update -a && ./scripts/feeds install -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git;openwrt-19                                                                                                                                .07' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
rm: cannot remove 'tmp/.packageinfo': Permission denied
lm@ubuntu:~/lede$ ./scripts/feeds update -a && ./scripts/feeds install -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git;openwrt-19                                                                                                                                .07' ...
error: cannot open .git/FETCH_HEAD: Permission denied
failed.
rm: cannot remove 'tmp/.packageinfo': Permission denied
lm@ubuntu:~/lede$
lm@ubuntu:~/lede$ sudo chown -R $(lm):admin /lede/.git                                                                                                                                                           lm: command not found
chown: invalid group: ':admin'
lm@ubuntu:~/lede$ sudo chown -R $(lm):root /lede/.git
lm: command not found
chown: cannot access '/lede/.git': No such file or directory

**Comment by madcat0513** [comment]
墙又高了，要继续搬砖。
