### ISSUE TITLE
通过SOCKS5链接后的Netflix不能打开

### ISSUE THREAD

**Issue by fma89** [coolsnowwolf/lede#3923]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
由于A点使用cn2专线，所以B点通过socks5连入A点后再FQ。A B两点的NF ip已经更新（15条）

A点：lean固件+ssr-plus_171-6，GFW模式, NF分流和全局服务器相同，正常观看NF。
         开启SSR+S5 server
B点：lean固件+ssr-plus_171-6, 绕过中国IP，NF分流和全局服务器相同。主服务器节点 连接到A点的 
        Socks5 Server，可以正常打开youtube、facebook。但打开netflix会显示 upsupport country， 
       地址栏后显示的是cn

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
B点 NF 分流选一个节点，而不是跟随全局，哪怕是同一个节点
