### ISSUE TITLE
访问控制里一加入中文域名，就不能正常上网了

### ISSUE THREAD

**Issue by zuo000** [coolsnowwolf/lede#3934]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：在访问控制->强制走代理的域名 里添加中文域名，比如某知名jc域名， 域名.com，就会导致无法正常上网，甚至国内网站都无法正常访问。

### (2) 路由器型号和固件版本

A：J1900 PVE虚拟机x86_64

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
并不支持中文域名
