### ISSUE TITLE
OpenWrt R7.7 (git-18.108.18263-7d55be3) nlbwmon 保存&应用 按钮无效

### ISSUE THREAD

**Issue by 450717565** [coolsnowwolf/lede#394]
nlbwmon点击 保存&应用 按钮无法保存配置，点了之后右上角会提示有未保存的配置，需要在这里面点击 保存&应用 才有效。

**Comment by shenzt68** [comment]
我也是。配置mwan3的规则也是这样的

**Comment by waterun** [comment]
确实有这个问题

**Comment by a843161264** [comment]
shadowsocksR里面的配置同样如此，且客户端代理模式设置无法添加配置。

**Comment by hungleung** [comment]
我的防火墙里面的端口转发 保存并应用也不行。

**Comment by fuqiang03** [comment]
有谁搞定这个问题了吗
![qq 20180509021242](https://user-images.githubusercontent.com/26851715/39774783-7e6b4272-532e-11e8-87e0-14be61e14069.png)
