### ISSUE TITLE
默认参数编译出来bin包大于15.8MB超出flash大小

### ISSUE THREAD

**Issue by Tuskio** [coolsnowwolf/lede#3942]
反馈bug/问题模板，提建议请删除
只是选择了架构和填写了路由器型号，其他的默认，甚至还取消了ssr和adbyby，编译出来的bin包还是超出了路由器flash的大小。。。如果可以删除一些默认的插件，应该在哪里删除  L大佬(@coolsnowwolf) 请告知位置，谢谢。之前删了include/target.mk上一些默认值。
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
存在类似issue[#3170](https://github.com/coolsnowwolf/lede/issues/3170)，但是又不完全一样

### (1) 具体问题

按默认值编译的bin包达到16.3MB超出flash上限15.8MB：

### (2) 路由器型号和固件版本

路由器型号：TP-Link Archer C7 v2 
准备安装的固件版本：目前最新lede-master（openwrt19.07）

### (3) 详细日志

最终编译出的bin包大小：
![image](https://user-images.githubusercontent.com/30797159/77249800-9c2b8b80-6c7e-11ea-9358-1a7ad0f0230b.png)

**Comment by coolsnowwolf** [comment]
其他源代码的自己找对应的作者

**Comment by Tuskio** [comment]
> 其他源代码的自己找对应的作者
我就是用lede-master源码编译的，但是为啥会是这样的结果？？？不是很明白

**Comment by Tuskio** [comment]
1

**Comment by Tuskio** [comment]
> 其他源代码的自己找对应的作者


我发现官方包的编译结果也是16.25MB 看来是openwrt项目的锅，谢谢L大
