### ISSUE TITLE
提个小小的建议，就是现在的samba4.11版本的文件共享问题，希望L大看看，谢谢

### ISSUE THREAD

**Issue by u0225** [coolsnowwolf/lede#3944]
在现在的samba4.11版本时，XP和ubuntu16.04系统还有一些手机的文件浏览器都无法找到共享的文件（win7系统就可以用），可能是版本太新了，和以前的系统不兼容。
samba4.9.2时就都可以用，所有希望可以换回samba4.9.2的版本，谢谢

**Comment by dolphinpaopao** [comment]
更为建议更新系统或者用samba3，早期版本的漏洞或者bug会在新版修复。微软不会因为Windows7不能运行有的软件而停留在xp吧。
