### ISSUE TITLE
计划任务重启无法保存

### ISSUE THREAD

**Issue by vobasf** [coolsnowwolf/lede#3945]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
计划任务重启无法保存
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：在web界面添加计划任务后，重启消失
在/etc/crontabs/root文件中，写入计划任务后，重启也消失

### (2) 路由器型号和固件版本

A：J1900 X86 OpenWrt R20.3.11

### (3) 详细日志

A：暂无

**Comment by aptx17** [comment]
先回车一行，再添加命令。

**Comment by vobasf** [comment]
> 先回车一行，再添加命令。

我就是另起一行添加命令的，刚才试了空一行，还是重启失效。

**Comment by aptx17** [comment]
> > 先回车一行，再添加命令。
> 
> 我就是另起一行添加命令的，刚才试了空一行，还是重启失效。

![手心输入法截图20200323065512428](https://user-images.githubusercontent.com/41042297/77263653-c9eeef80-6cd3-11ea-81c0-08f6132584ce.jpg)
不能啊，下边再加个回车试试，要不就直接改crontab -e。

**Comment by jyy5206** [comment]
我也遇到过此问题。
后来尝试从文头输入，ok了。
从文末输入，也是重启后丢失改动。
试试看？

**Comment by coolsnowwolf** [comment]
看看是不是用了关键字

**Comment by mjyhj** [comment]
部分关键字会被对应LUCI 去掉

**Comment by vobasf** [comment]
> 看看是不是用了关键字

应该是因为关键字adblock的原因，改掉后就没问题了，谢谢~

**Comment by mayichuan2010** [comment]
能讲一下具体是怎么回事吗，关键字adblock是什么？

**Comment by Cathgao** [comment]
reboot也算是关键字吗？我用计划任务做自动重启，重启完就没了

**Comment by taoletsgo** [comment]
> reboot也算是关键字吗？我用计划任务做自动重启，重启完就没了

同问

**Comment by taoletsgo** [comment]
> reboot也算是关键字吗？我用计划任务做自动重启，重启完就没了

问题解决了，去软件包里搜reboot删除别人编译的里面那个定时重启插件
