### ISSUE TITLE
升级到iptables 1.8.4后编译不过去了，，没有libnftnl

### ISSUE THREAD

**Issue by bluehj777** [coolsnowwolf/lede#3946]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
22日iptables升级到1.8.4，nftables模块的
错误日志提示它需要系统安装 libnftnl包，但14版本的
ubuntu 没有这个依赖可以用来安装
之前的1.8.2的iptables一直没有问题的

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hxlls** [comment]
安装libnftnl-dev试试

**Comment by bluehj777** [comment]
14版本里也没有这个，16以上版本才有 @hxlls

**Comment by hzmax0416** [comment]
那是不是要重新安装16以上版本的Ubuntu来编译才行？

**Comment by hxlls** [comment]
不需要
我就是14编译的，屁事都没

**Comment by bluehj777** [comment]
您的编译项目里选择了nftables了吗？

**Comment by coolsnowwolf** [comment]
安装libnftnl-dev试试

**Comment by bluehj777** [comment]
这几天一直在编译都没有问题，今天pull了以后出现的。最后干脆全部删除了编译目录重新克隆了，重新开始。还是这个问题。
google到类似的情况
https://forum.openwrt.org/t/iptables-1-8-3-ar71xx-mikrotik-compiler-error/40244
https://github.com/openwrt/openwrt/pull/2179

**Comment by hxlls** [comment]
我编译的nfs qos 就需要这个吧
![image](https://user-images.githubusercontent.com/43886952/77255376-e2dead00-6ca1-11ea-9bfc-0b6b9eb073ee.png)
![image](https://user-images.githubusercontent.com/43886952/77255381-f12cc900-6ca1-11ea-90b6-3f61777a0603.png)
