### ISSUE TITLE
7621，luci卡，平均负载高

### ISSUE THREAD

**Issue by niceguy3-31** [coolsnowwolf/lede#3950]
新三，这些天pull后编译出来的固件，luci界面特别卡，要好几秒。cpu使用率正常，load average经常3个数字都是3以上。下载云编译11号以前的刷回去就正常，找不到原因，愁

**Comment by EnnawYang** [comment]
ddns卸载试试？ 别问我怎么知道的（

**Comment by niceguy3-31** [comment]
好嘞，晚上回家卸载了试试，谢谢

**Comment by 1049066154** [comment]
已测试,卸载后有效
