### ISSUE TITLE
3.23上午11点左右刷了最新的版本，CPU占用似乎有点不正常

### ISSUE THREAD

**Issue by keivenliao** [coolsnowwolf/lede#3961]
![image](https://user-images.githubusercontent.com/12838693/77298106-4fe75680-6d25-11ea-9c38-237f1bb521d9.png)

忽然发现CPU占用高了不少，进去看了看，是以上两个进程，这个正常吗？

![image](https://user-images.githubusercontent.com/12838693/77297932-026ae980-6d25-11ea-8b93-2f7cf276ec92.png)

**Comment by kl9800** [comment]
我删掉ddns就好了

**Comment by keivenliao** [comment]
> 我删掉ddns就好了

我DDNS是必选项。
刚才重新编译了个版本，貌似可以了， 今晚再观察一下

**Comment by coolsnowwolf** [comment]
tcp ping 的时候占用cpu 比普通ping要多

**Comment by keivenliao** [comment]
> tcp ping 的时候占用cpu 比普通ping要多

感谢大佬回复，问题是为啥一直持续着？不会自己结束进程吗？

**Comment by VNY0920** [comment]
我跟你情况类似，cpu常态使用15~20%。3865U
昨晚在Github云编译的版本。
其实只开了ssr plus+和 softherVPN 两个服务。

**Comment by VNY0920** [comment]
太神奇了，我删掉在软件包里删掉ddns就好了。ddns服务本来就没开启的。

**Comment by VNY0920** [comment]
太神奇了，我在软件包里删掉ddns就好了，cpu使用率掉到个位数。不过ddns服务本来就没开启的。

**Comment by keivenliao** [comment]
今天 刷了之后，tcpping没有了。 但是 ip2socks 还是比较高啊
![image](https://user-images.githubusercontent.com/12838693/77383713-98068780-6dbe-11ea-9b47-0499b11053df.png)

**Comment by VNY0920** [comment]
你这cpu占用率怎么看的？ 不像是top命令。

**Comment by kfen** [comment]
> 太神奇了，我在软件包里删掉ddns就好了，cpu使用率掉到个位数。不过ddns服务本来就没开启的。

问下老哥，我也遇到了同样的问题，删除luci-app-ddns之后，于此相关的软件包是否也一并移除？比如：ddns-scripts_dnspod和ddns-scripts_aliyun?????

**Comment by keivenliao** [comment]
> 你这cpu占用率怎么看的？ 不像是top命令。

就是top啊

**Comment by keivenliao** [comment]
我发现把这个停用了，ipt2socks 就关闭了。

**Comment by VNY0920** [comment]
这个游戏udp中继我也没开。开了后Switch的nat类型会变成nat F，ps4玩实况会连不上服务器。
可能是因为我那个服务器是ssr不是ss类的。
