### ISSUE TITLE
网易音乐解锁证书问题

### ISSUE THREAD

**Issue by whlsxl** [coolsnowwolf/lede#3969]
网易音乐解锁这个功能好想用啊！
不过golang的这个证书直接生成有点不安全。
请教Lean大，这个可不可以改成本地自动生成啊？

**Comment by whlsxl** [comment]
可能需要依赖`openssl`
生成证书脚本，https://github.com/cnsilvan/UnblockNeteaseMusic/blob/master/createCertificate.sh

**Comment by wspzf** [comment]
自己用这个sh在本地生成证书后,把ca.crt  server.crt server.key三个文件替换到/usr/share/UnblockNeteaseMusicGo

**Comment by whlsxl** [comment]
嗯嗯，是的，现在自己生成证书了。
不过这个功能会造成一些安全隐患

**Comment by klever1988** [comment]
自己创建域名证书之后，把根ca的key从路由器删除就没事了

**Comment by whlsxl** [comment]
不是每个人都能搞定的啦。。

**Comment by klever1988** [comment]
在系统导入自制ca就等于埋下隐患，win已经有提示了，跟来自路由器系统还是来自哪里没有关系

**Comment by whlsxl** [comment]
导入自制，还是网上公开的，还是有区别吧
