### ISSUE TITLE
和最新版本Strongwan 5.8.2有冲突

### ISSUE THREAD

**Issue by pafans** [coolsnowwolf/lede#3970]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：无法安装Strongswan 5.8.2

### (2) 路由器型号和固件版本

A：X86, OpenWrt R20.3.19 / LuCI Master (git-20.079.47035-c242d65)

### (3) 详细日志

A：
root@HomeRouter:~# opkg install strongswan-default --force-checksum --force-reinstall
No packages removed.
Installing strongswan-default (5.8.2-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages/strongswan-default_5.8.2-1_x86_64.ipk
Installing libgmp10 (6.1.2-2) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base/libgmp10_6.1.2-2_x86_64.ipk
Collected errors:
 * check_data_file_clashes: Package libgmp10 wants to install file /usr/lib/libgmp.so.10
        But that file is already provided by package  * libgmp
 * check_data_file_clashes: Package libgmp10 wants to install file /usr/lib/libgmp.so.10.3.2
        But that file is already provided by package  * libgmp
 * opkg_install_cmd: Cannot install package strongswan-default.
root@HomeRouter:~#

**Comment by AmadeusGhost** [comment]
这种最好是编译进去。
