### ISSUE TITLE
默认使用tcpping测试节点延迟导致的问题

### ISSUE THREAD

**Issue by tone88** [coolsnowwolf/lede#3975]
最近大雕更新了默认使用tcpping测试节点延迟，而tcpping又巨吃CPU，每次点到“服务器节点”页面的时候CPU占用都会暴增，在没有测试完成的情况下如果切换到SSR P+里其它页面的时候还会经常遇到页面转圈半天没反应的情况。

大雕一直在优化体验，这几天SSR也添加了一些很棒的功能。而tcpping测试节点延迟虽然更加准确了，但是太吃CPU这样的体验感觉不是那么的好。那么能否在“服务器节点”页面添加一个测试延迟的按钮呢？当用户需要查看延迟的时候点一下再开始测试。  因为有时候进“服务器节点”页面修改节点信息或者做其它操作的时候并不一定都需要查看延迟。

下图是正常情况下和在“服务器节点”页面切换时的CPU占用对比，有时占用甚至会升到2.6~3GHz。

![微信截图_20200323224157](https://user-images.githubusercontent.com/47731895/77328801-0401d500-6d58-11ea-92ec-9185d9403ad0.png)
我的硬件环境是  3865U ESXI下跑OP，按理说性能应该不是瓶颈吧。

最后感谢大雕为我们小白提供这么好的项目，大雕辛苦了。

**Comment by agutools** [comment]
建议添加一个总测试按钮，及每个节点均有个单独的测试按钮，默认打开节点页面不自动开始检测（或添加开/关项），并保留/显示上次检测结果。
——多节点机场不敢轻易打开节点页面，但“状态”页的检测又不显示延迟数值😅
