### ISSUE TITLE
lean大我们的lede能否增加文件缓存

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#3980]
lean大我记得在20年前的sygate和其他一些路由器软件有文件缓存
当时什么软件其实我也忘记差不多了。很多路由器软件可以开辟1G或者2G的硬盘空间，比如局域网某个机器访问了nvidia.com下载了最新的驱动
另外一个局域网的客户在第二次访问的时候是直接从本地下载。
现在好像很多路由器都没有这个功能了，是不是因为现在网速快了的缘故

**Comment by coolsnowwolf** [comment]
在家庭大带宽宽带和动态网页时代，已不再必要

**Comment by agutools** [comment]
代理缓存 Squid

**Comment by norikohxb** [comment]
我感觉你说的对。难怪现在你看主流的代理服务器软件已经不兴这个了。
特别是我感觉下载的人多了，文件很多，管理文件，还会耗费路由器的系统资源
不知道你们复制过早期的文字mud的文件夹吗，复制一个文件夹要很久，因为都是一堆小的txt文件，如果频繁的有人读取这种小文件，这些本来是远端服务器的工作，都给了路由器来做文件管理，感觉路由器会累死
