### ISSUE TITLE
Intel 82579LM 网卡 频繁挂起导致断流

### ISSUE THREAD

**Issue by musouking** [coolsnowwolf/lede#3981]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：搜索到了类似情况 https://forum.manjaro.org/t/solved-intel-82579lm-network-driver-hang/94289 等我试完帖子里的方法会继续跟进

### (2) 路由器型号和固件版本

A：笔记本 固件版本R20.2.15 内核4.19.106

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/17735261/77381028-c896f300-6db7-11ea-9210-32e9474a3a65.png)
![image](https://user-images.githubusercontent.com/17735261/77382246-db5ef700-6dba-11ea-9d3a-aaa998b9e8d8.png)

**Comment by musouking** [comment]
似乎进bios关了wake on lan就好了...

**Comment by coolsnowwolf** [comment]
这个是 Intel 网卡的断流硬件 Bug ，只能升级 EPPROM 关闭 Offloading 解决

推荐尽量使用 RTL 的网卡

**Comment by musouking** [comment]
> 这个是 Intel 网卡的断流硬件 Bug ，只能升级 EPPROM 关闭 Offloading 解决
> 
> 推荐尽量使用 RTL 的网卡

改用RTL8153 usb网卡了
