### ISSUE TITLE
阿里云日志异常

### ISSUE THREAD

**Issue by tone88** [coolsnowwolf/lede#3982]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
没有类似的issue

### (1) 具体问题
最新源码编译，DDNS里阿里云日志异常。
全新刷机后手动设置各项配置。

### (2) 路由器型号和固件版本
X86  OpenWrt R20.3.19 / LuCI Master (git-20.068.29105-b2cf61d)

### (3) 详细日志
系统日志截图：
![系统日志](https://user-images.githubusercontent.com/47731895/77381172-2aeff380-6db8-11ea-851e-8389d6cac368.jpg)
动态DDNS日志查看器截图：
![动态DDNS日志查看器](https://user-images.githubusercontent.com/47731895/77381185-2f1c1100-6db8-11ea-93b9-e33d45720425.jpg)

详细日志稍后私发大雕

**Comment by zfh135072** [comment]
同问题，好像泛解析也不行了

**Comment by tone88** [comment]
> 同问题，好像泛解析也不行了

今天早上编译的才遇到这问题，之前的版本没感觉到这问题

**Comment by EnnawYang** [comment]
我的没问题 阿里云、dnspodcn均正常解析，早上编译的

**Comment by tone88** [comment]
> 我的没问题 阿里云、dnspodcn均正常解析，早上编译的

你是物理机还是虚拟机里跑的OP?    

我是在EXSI下跑的OP

**Comment by EnnawYang** [comment]
> > 我的没问题 阿里云、dnspodcn均正常解析，早上编译的
> 
> 你是物理机还是虚拟机里跑的OP?
> 
> 我是在EXSI下跑的OP

物理

**Comment by coolsnowwolf** [comment]
看看是否泛域名，需要用 * 这个符号的

**Comment by tone88** [comment]
> 看看是否泛域名，需要用 * 这个符号的

没有泛域名，刚刚登陆阿里云看解析设置里显示是正常状态
![TIM截图20200324131125](https://user-images.githubusercontent.com/47731895/77390469-06544580-6dd1-11ea-9c8e-e39d215e48c9.jpg)

 路由里的日志一直还在报错！

Tue Mar 24 09:44:41 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 1/0
Tue Mar 24 09:54:41 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 2/0
Tue Mar 24 10:04:42 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 3/0
Tue Mar 24 10:14:42 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 4/0
Tue Mar 24 10:24:43 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 5/0
Tue Mar 24 10:34:44 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 6/0
Tue Mar 24 10:44:44 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 7/0
Tue Mar 24 10:44:44 2020 user.err ddns-scripts[5687]: Aliyun: wget 错误代码: '8'
Tue Mar 24 10:44:44 2020 user.warn ddns-scripts[5687]: Aliyun: 传输失败 - 1/0 在 60 秒后重试
Tue Mar 24 10:55:45 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 8/0
Tue Mar 24 11:05:45 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 9/0
Tue Mar 24 11:15:46 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 10/0
Tue Mar 24 11:25:46 2020 user.warn ddns-scripts[5687]: Aliyun: Updating IP at DDNS provider failed - starting retry 11/0

**Comment by EnnawYang** [comment]
建议再检查下设置

**Comment by tone88** [comment]
> 建议再检查下设置

设置和之前的一样，没有变化的
设置如图：
![TIM截图20200324132328](https://user-images.githubusercontent.com/47731895/77391206-1ff68c80-6dd3-11ea-9626-43c063d8c20b.jpg)

**Comment by EnnawYang** [comment]
> > 建议再检查下设置
> 
> 设置和之前的一样，没有变化的
> 设置如图：
> ![TIM截图20200324132328](https://user-images.githubusercontent.com/47731895/77391206-1ff68c80-6dd3-11ea-9626-43c063d8c20b.jpg)

那我也不太清楚了

**Comment by coolsnowwolf** [comment]
删除ddns配置再添加一次吧

**Comment by tone88** [comment]
> 删除ddns配置再添加一次吧

删除了重新添加也不行，刚刚又重新编译了一次刷机，日志还是报错，搞不懂了。

**Comment by free521521521** [comment]
域名解析实际成功，但是log里显示failed。奇怪
