### ISSUE TITLE
luci-app-ssr-plus自动编译服务端

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#3988]
如图,编译时没有选上服务端,但实际上已经编译了,这是什么原因啊?
![34](https://user-images.githubusercontent.com/51162826/77398180-001a9500-6de2-11ea-9c5b-d5bbd6040f52.PNG)
![35](https://user-images.githubusercontent.com/51162826/77398361-51c31f80-6de2-11ea-9950-08f540bb4a6e.PNG)

**Comment by hxlls** [comment]
luci 而已，就一个皮，没有里面对应的组件又用不了

**Comment by coolsnowwolf** [comment]
目前 socks5 也并入服务端了
