### ISSUE TITLE
Adbyby Plus+第三方订阅规则在升级后会丢失

### ISSUE THREAD

**Issue by fonlan** [coolsnowwolf/lede#3991]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Adbyby Plus+添加第三方订阅规则后每次升级固件后第三方规则数量归0，需要重新手动点击第三方订阅的“更新数据库”。

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：是不是应该把第三方规则的路径加到Makefile的conffiles里？

**Comment by hplee0120** [comment]
请问你们的Adblock Plus 规则数据库自动更新有没有生效，我这边最近新编译的一直是失效的，尝试过6点过后手动更新是正常刷新出新规则的。不手动刷新的话它是不会自动更新的。
