### ISSUE TITLE
关于 ddns 的问题

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#3998]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：大佬好，关于前几天发现的CPU不稳定的情况，我这边拆卸ddns以后，CPU一切变得正常，所以我想问一下，是否真的是ddns的问题导致CPU的问题？2.如果是的话，是否以后会修复？

### (2) 路由器型号和固件版本

A：x86  64   J1900

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
删除 ddns 配置再加回去即可

**Comment by kl9800** [comment]
原来是这样！！灰常感谢！！DDNS确实是很难抛弃的插件，有大用，谢谢谢谢！！！
