### ISSUE TITLE
官方OpenWrt SDK无法编译luci-app-ssr-plus

### ISSUE THREAD

**Issue by caoli5288** [coolsnowwolf/lede#4000]
## 1.关于你要提交的问题
官方OpenWrt SDK无法编译luci-app-ssr-plus

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：使用openwrt-sdk-x86-64编译luci-app-ssr-plus，编译v2ray时报错，报`/staging_dir/host/bin/upx`找不到。

有看到另一个issue说可以复制tools里面的工具源码，但是SDK无法使用这样的方法。

### (2) 路由器型号和固件版本

A：snapshot

### (3) 详细日志

A：

**Comment by openlcc** [comment]
去下载一个3.95版本以上的upx，解压得到upx可执行文件，然后复制到/staging_dir/host/bin/目录下就行了，官方openwrt的SDK就这样操作。

**Comment by caoli5288** [comment]
@openlcc 是可以，已经编译通过了，但还是希望能改进下兼容

**Comment by garypang13** [comment]
关闭压缩  CONFIG_V2RAY_COMPRESS_UPX=n

**Comment by dongjuanyong** [comment]
已经很兼容了好不，加一下这两个commit就行了
a237f50d1dacc543ef3fa2364f696fd67f068c46
d99da91bbee95f85a610a89aded9bfd4a4990c85
