### ISSUE TITLE
X86 CPU高居不下响应迟钝和 luci-app-ddns 有关

### ISSUE THREAD

**Issue by mjyhj** [coolsnowwolf/lede#4004]
/lede/package/lean/autocore/files/index.htm
和
luci-app-ddns
共存就卡

与ddns-scripts，aliddns，dnspod无关

**Comment by hcym** [comment]
x86目录下太多太多插件，不用的话就不要编译，我的只有一个ss加，广告也是用的内置，没有adbyby，什么无线usb驱动硬盘接口都去掉了，很少见到cpu波动
