### ISSUE TITLE
建议将中科大的镜像源修改为阿里源

### ISSUE THREAD

**Issue by marcosteam** [coolsnowwolf/lede#4007]
最近中科大的镜像源十分不稳定，网页加载都要很久才能打开，阿里云会比较稳定一点。

**Comment by lwz322** [comment]
遇到了一样的问题，阿里云有OpenWrt软件源吗？
我换成tuna了

**Comment by marcosteam** [comment]
> 遇到了一样的问题，阿里云有OpenWrt软件源吗？
> 我换成tuna了

没有，需要额外软件源的都是Linux相关库

**Comment by j1n91** [comment]
附议

**Comment by xcc23** [comment]
附议+1

**Comment by AmadeusGhost** [comment]
opkg的吗

**Comment by DongfeiSay** [comment]
阿里nb

**Comment by lyin888** [comment]
浙江大学 | OPENWRT | 开源镜像站地址
http://mirrors.zju.edu.cn/openwrt/

**Comment by Sakurakouji-Runa** [comment]
附议，openwrt.proxy.ustclug.org挂了

**Comment by iamggs** [comment]
唉，openwrt.proxy.ustclug.org的确挂了。

**Comment by Sjhzjxc** [comment]
中科大的源不是这个吗？ https://mirrors.ustc.edu.cn/lede/

**Comment by cnazev** [comment]
> 中科大的源不是这个吗？ https://mirrors.ustc.edu.cn/lede/

Snapshot被重定向到
https://mirrors.bfsu.edu.cn/openwrt/snapshots/targets/  挂了
