### ISSUE TITLE
smaba36文件共享问题

### ISSUE THREAD

**Issue by u0225** [coolsnowwolf/lede#4015]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
由于上次提的那个samba4.11的共享问题。现在编译的时候选兼容性好的samba36的版本，但是现在这个版本的文件共享好像也有问题。
就是电脑打开共享文件夹后只要刷新共享的文件，电脑和软路由（n270）就都会变得非常的卡，电脑和软路由就像没响应一样，软路由的管理界面一直转圈打不开，电脑打开的共享文件夹里也一样一直转圈，都没响应。
要等到自动恢复的话（就是等刷新的过程过去）至少要一、二分钟以上，如果直接禁用网卡或拔掉网线的话就立马恢复正常不卡了。
不知道为什么会这样？

还有一个问题就是x86（32位固件）选samba4.11版本的话编译会报错，x64就不报错。

### (2) 路由器型号和固件版本

昨天更新的源码
n270软路由

A：

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
用到现在了没有你说的这种问题，samba4编译报错的话要先取消samba3，两者冲突

**Comment by u0225** [comment]
我也不知道为什么最近总遇到这样那样的问题，郁闷啊
