### ISSUE TITLE
iOS网易云音乐解锁成功但无法播放

### ISSUE THREAD

**Issue by Kisoul** [coolsnowwolf/lede#4017]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：iOS  的网易云音乐解锁成功，但无法播放，提示“网络不给力，无法继续播放”证书已安装。屏蔽223.252.199.10的方式也试过了。
安卓，Windows都没问题

### (2) 路由器型号和固件版本

A：25号最新编译的x86-64

### (3) 详细日志

A：日志里没有任何反应

**Comment by coolsnowwolf** [comment]
信任证书

**Comment by Kisoul** [comment]
> 信任证书

信任并安装了

**Comment by Kisoul** [comment]
> 信任证书

谢谢，解决了，辛苦

**Comment by michealhansun** [comment]
IOS 14.3  本地wifi下添加证书信任后即可播放歌曲，公网手机流量使用小火箭设置代理好代理，查日记是解锁成功，已经获取了歌曲地址，但是感觉好像没有推送到公网手机上


![image](https://user-images.githubusercontent.com/9845710/106609230-53cc4200-65a0-11eb-9656-163b0739f6df.png)
![image](https://user-images.githubusercontent.com/9845710/106609271-5e86d700-65a0-11eb-8474-8513cda9a4b4.png)
![image](https://user-images.githubusercontent.com/9845710/106609289-634b8b00-65a0-11eb-9655-3736b67ef9d3.png)
![image](https://user-images.githubusercontent.com/9845710/106609311-68103f00-65a0-11eb-9466-88426e4b692f.png)
