### ISSUE TITLE
lububox是否需要更新？

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#4022]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：题目写成lububox了，应该是libubox。在编译时候出错，提示缺少libubox20191228，我搜索源码看了一下libubox是20190616版的，ubox也是，不知道是否也需要更新。我make clean后编译仍有此问题。

### (2) 路由器型号和固件版本

A：newifi3 最新源码

### (3) 详细日志

A：
Configuring kmod-fs-exfat.
ConfiCollected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for base-files:
 *      libubox20191228
 * opkg_install_cmd: Cannot install package base-files.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for relayd:
 *      libubox20191228
 * opkg_install_cmd: Cannot install package relayd.
guring kmod-fuse.

**Comment by stock169** [comment]
一样的问题等修复
