### ISSUE TITLE
更新后需要fullconenat-2019-10-21-0cf3b48f.tar.xz，但是只能下载到fullconenat-2018-12-15-d4daedd0.tar.xz

### ISSUE THREAD

**Issue by honorchen** [coolsnowwolf/lede#4028]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：更新后需要fullconenat-2019-10-21-0cf3b48f.tar.xz，但是只能下载到fullconenat-2018-12-15-d4daedd0.tar.xz

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：make[2]: Entering directory `/home/honor/lede/package/lean/openwrt-fullconenat'
mkdir -p /home/honor/lede/dl
SHELL= flock /home/honor/lede/tmp/.fullconenat-2019-10-21-0cf3b48f.tar.xz.flock -c '  	 /home/honor/lede/scripts/dl_github_archive.py --dl-dir="/home/honor/lede/dl" --url="https://github.com/Chion82/netfilter-full-cone-nat.git" --version="0cf3b48fd7d2fa81d0297d1fff12bbd0580fc435" --subdir="fullconenat-2019-10-21-0cf3b48f" --source="fullconenat-2019-10-21-0cf3b48f.tar.xz" --hash="x" || ( 	echo "Checking out files from the git repository..."; mkdir -p /home/honor/lede/tmp/dl && cd /home/honor/lede/tmp/dl && rm -rf fullconenat-2019-10-21-0cf3b48f && [ \! -d fullconenat-2019-10-21-0cf3b48f ] && git clone  https://github.com/Chion82/netfilter-full-cone-nat.git fullconenat-2019-10-21-0cf3b48f && (cd fullconenat-2019-10-21-0cf3b48f && git checkout 0cf3b48fd7d2fa81d0297d1fff12bbd0580fc435 && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd fullconenat-2019-10-21-0cf3b48f && git log -1 --format='\''@%ct'\''` && rm -rf fullconenat-2019-10-21-0cf3b48f/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c fullconenat-2019-10-21-0cf3b48f | 	xz -zc -7e > /home/honor/lede/tmp/dl/fullconenat-2019-10-21-0cf3b48f.tar.xz && mv /home/honor/lede/tmp/dl/fullconenat-2019-10-21-0cf3b48f.tar.xz /home/honor/lede/dl/ && rm -rf fullconenat-2019-10-21-0cf3b48f; );     '
fullconenat-2019-10-21-0cf3b48f.tar.xz: Download from https://github.com/Chion82/netfilter-full-cone-nat.git failed
fullconenat-2019-10-21-0cf3b48f.tar.xz: Requires sha256sum for verification
Checking out files from the git repository...
Cloning into 'fullconenat-2019-10-21-0cf3b48f'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 223 (delta 2), reused 3 (delta 0), pack-reused 215
Receiving objects: 100% (223/223), 77.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (134/134), done.
Checking connectivity... done.
Note: checking out '0cf3b48fd7d2fa81d0297d1fff12bbd0580fc435'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 0cf3b48... Merge pull request #29 from llccd/master
Packing checkout...

**Comment by ZqinKing** [comment]
临时方案就是手动修改：lede/package/lean/openwrt-fullconenat内Makefile内的URL，在github前面加上www.即可下载，应该是墙没翻好导致的。
