### ISSUE TITLE
又试了一次还是libubox20191228有问题

### ISSUE THREAD

**Issue by stock169** [coolsnowwolf/lede#4036]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：libubox 版本好像不对

### (2) 路由器型号和固件版本

A：竞斗云

### (3) 详细日志

A：Configuring kmod-usb-storage-extras.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring coreutils-nohup.
Configuring luci-lib-fs.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for mtd:
 * 	libubox20191228
 * opkg_install_cmd: Cannot install package mtd.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/pchome/lede'
package/Makefile:108: recipe for target '/home/pchome/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install' failed
make[1]: *** [/home/pchome/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/pchome/lede'
/home/pchome/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by hzmax0416** [comment]
make clean
