### ISSUE TITLE
tcpping指的是tcping吗？

### ISSUE THREAD

**Issue by mzxwt** [coolsnowwolf/lede#4040]
Lean大好！今天在你的openwrt的基础上想加入lienol老大的passwall，但是编译几次都失败。最后发现passwall的依赖是tcping，而Lean大提供的是tcpping。看了一下makefile里的相关信息，发现一个是来自https://github.com/coolsnowwolf/tcping，另一个是来自https://github.com/jlyo/tcping，都是tcping，但是PKG_NAME不同。
想请问一下Lean大，两个是不是一个东西？可不可以把tcpping内的信息改为tcping？是否有其它文件依赖tcpping？

**Comment by coolsnowwolf** [comment]
两个东西，不冲突

**Comment by mzxwt** [comment]
感谢回复
