### ISSUE TITLE
关于 DNS 的问题

### ISSUE THREAD

**Issue by LisonFan** [coolsnowwolf/lede#4044]
这个域名 merlinblog.xyz 不在 GFWList
按照大雕这个 issues -> https://github.com/coolsnowwolf/lede/issues/2551 的说法，应该解析出来的 IP 是正确的，但是解析出来的是被污染的

![_YDG5_W5}F$}W36IGS(4(KG](https://user-images.githubusercontent.com/9424775/77651283-859b7200-6fa7-11ea-8fd3-7e2f04b635cd.jpg)

是哪配置有问题吗？

![Snipaste_2020-03-26_21-21-08](https://user-images.githubusercontent.com/9424775/77651496-d90dc000-6fa7-11ea-81d7-a7af56f5470d.png)
![Snipaste_2020-03-26_21-21-38](https://user-images.githubusercontent.com/9424775/77651503-da3eed00-6fa7-11ea-90ea-1a1f142ed739.png)
![Snipaste_2020-03-26_21-21-26](https://user-images.githubusercontent.com/9424775/77651505-dad78380-6fa7-11ea-94e3-4de7dcca79e4.png)

**Comment by shikiroot** [comment]
dns2socks默认在5335，把dnsmasq的转发改一下，另外最好别开dns加速。

**Comment by LisonFan** [comment]
> dnsmasq

好了，非常感谢

**Comment by LisonFan** [comment]
> dns2socks默认在5335，把dnsmasq的转发改一下，另外最好别开dns加速。

好的， 非常感谢

**Comment by LisonFan** [comment]
> dns2socks默认在5335，把dnsmasq的转发改一下，另外最好别开dns加速。

还是不行，我现在转到 5335 了，出来的还是污染 IP

**Comment by shikiroot** [comment]
dns加速关掉，wan口和lan口dns都改成127.0.0.1。

**Comment by LisonFan** [comment]
> dns加速关掉，wan口和lan口dns都改成127.0.0.1。

dns 加速关了，wan lan 都改了
这样设置的话所有的 DNS 请求都走代理了

**Comment by zcgmt** [comment]
这样设置的行不行

**Comment by zcgmt** [comment]
请问访问访问国外网站可以，
国内网站时好时坏是怎么回事？
