### ISSUE TITLE
QQ 群满了

### ISSUE THREAD

**Issue by crabhit** [coolsnowwolf/lede#4049]
尝试加群看到群满了。

**Comment by ngn999** [comment]
想贡献5块大洋都不给机会

**Comment by EnnawYang** [comment]
> 想贡献5块大洋都不给机会,
> 要不要考虑建一个telegram群?

可以直接捐赠啊，哈哈哈哈哈哈

**Comment by hcym** [comment]
我也没加裙啊，鸡飞狗跳的麻烦，现在页面捐赠方便快捷
