### ISSUE TITLE
取消选择luci/applications/luci-filetransfer会同时取消luci/applications/luci-firewall和luci/collections/luci

### ISSUE THREAD

**Issue by shikiroot** [coolsnowwolf/lede#4050]
### 取消选择luci/applications/luci-filetransfer会同时取消luci/applications/luci-firewall和luci/collections/luci

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### 昨晚的新版本会出现取消选择luci/applications/luci-filetransfer会同时取消luci/applications/luci-firewall和luci/collections/luci的问题，前天的版本没有这个问题。看了一下commit也没发现哪里有问题。大雕有时间看看吧。选了mt7620和mt7621的几个target都有这个问题。

**Comment by EnnawYang** [comment]
测试无此问题

**Comment by shikiroot** [comment]
### 具体型号是phicomm psg1218ax和xiaomi r3g

**Comment by shikiroot** [comment]
### 全部删除重新git后无此问题。应该是pull的时候或者更新feeds的时候出什么问题了。
