### ISSUE TITLE
cpu不高了，可是如果ddns存在，页面就很卡顿

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#4066]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：固件里只要ddns存在，页面就很卡顿，拆卸以后恢复正常

### (2) 路由器型号和固件版本

A：x86  64   j1900

### (3) 详细日志

A：

**Comment by hxlls** [comment]
你编译的有问题吧，DDNS需要的组件没选齐全，或者feed 没更新，我的没发现存在这个问题

**Comment by kl9800** [comment]
我再去试试，从头开始试

**Comment by Myoko** [comment]
没有这个情况

**Comment by kl9800** [comment]
也许是我没执行apt-get闹的，我重新来了一次还没编完

**Comment by kl9800** [comment]
问题已解决，就是因为没有apt-get.....
