### ISSUE TITLE
SSR-PLUS游戏模式UDP中继服务器

### ISSUE THREAD

**Issue by etsam** [coolsnowwolf/lede#4069]
你好，经过几天多次删除IPK 并安装新老固件发现 最新的SSRPLUS游戏模式UDP中继服务器 在玩使命召唤16的时候无法进入服务器

luci-app-ssr-plus  174-8 这个版本之前的都可以

175之后的版本都无法进入游戏，别的代理功能都正常。（早上刚编译的最新的175.3也不行）

不知道LEAN能否帮忙解决一下，谢谢

**Comment by coolsnowwolf** [comment]
已正常，重启下即可
