### ISSUE TITLE
求助！树莓派4编译后概况界面不显示CPU架构和温度 怎么解决？

### ISSUE THREAD

**Issue by IvanSolis1989** [coolsnowwolf/lede#4072]
树莓派4编译后 概况界面不显示CPU架构和温度 怎么解决？是不是需要选择某个插件才可以？

![QQ图片20200328183250](https://user-images.githubusercontent.com/44228691/77821126-bce25e00-7122-11ea-87f6-30e96de53f91.png)

主机名 | RaspberryPi4
-- | --
主机型号 | Raspberry Pi 4 Model B Rev 1.2 (CpuMark : 32739.313218 Scores)
架构 | ? x 4
固件版本 | OpenWrt R20.3.19 / LuCI Master (git-20.085.19816-df13074)
内核版本 | 4.19.108
本地时间 | Sat Mar 28 18:33:48 2020
运行时间 | 12h 3m 28s
平均负载 | 0.42, 0.44, 0.39
CPU 使用率（%） | 3 %

**Comment by EnnawYang** [comment]
忽略即可

**Comment by IvanSolis1989** [comment]
> 忽略即可

但是我想知道下CPU的温度啊 架构不显示都没事

**Comment by Pastechn** [comment]
sed -i 's|pcdata(boardinfo.system or "?")|luci.sys.exec("uname -m") or "?"|g' /usr/lib/lua/luci/view/admin_status/index.htm
参考资料：https://tieba.baidu.com/p/6357010977?red_tag=b1848246377

**Comment by feijj** [comment]
https://github.com/klever1988/lede/blob/master/enable_autocore.diff
解决方案在此
