### ISSUE TITLE
求助！树莓派4编译后ADBYBY 无法启动？ 怎么解决？

### ISSUE THREAD

**Issue by IvanSolis1989** [coolsnowwolf/lede#4075]
![image](https://user-images.githubusercontent.com/44228691/77821352-a3421600-7124-11ea-8620-0822a5eed336.png)

**Comment by hcym** [comment]
说是不支持arm64，我是x86编译过没用过

**Comment by IvanSolis1989** [comment]
> 说是不支持arm64，我是x86编译过没用过

好的 谢谢

**Comment by fankangsong** [comment]
ubuntu 18.4 编译树莓派 b+ （第一代树莓派） 也是这样：

> Adbyby Plus+ 未运行

我的设备型号：
>主机型号 | Raspberry Pi Model B Rev 1 (CpuMark : 1630.639720 Scores)
-- | --
>架构 | ARMv6-compatible processor rev 7 (v6l) x 2
>固件版本 | OpenWrt R20.5.20 / LuCI Master (git-20.141.34051-f750b5f)
>内核版本 | 4.19.122

使用场景：
旁路由科学上网，单网卡 eht0 有线，关掉了 IPV6 和 HDCP。

**Comment by hcym** [comment]
ssr内置更好的，用这个没事找事
