### ISSUE TITLE
MT7621 固件体积问题  求助求助！！！

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#4079]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：现在无论插件多少，甚至只编辑1-2个插件进去，squashfs-factory.bin 永远会是30M，刷不进去极路由4增强版，我该怎么办？

### (2) 路由器型号和固件版本

A：ramips-mt7621-hiwifi_hc5962  

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
hc5962 的 factory.bin  体积是固定的

**Comment by kl9800** [comment]
> hc5962 的 factory.bin 体积是固定的
![image](https://user-images.githubusercontent.com/59386592/77825632-76522b00-7145-11ea-9303-b021ad757c17.png)

可是我2月4号编译的还好好的。。。是近期修改成固定了吗？

**Comment by zanjie1999** [comment]
你应该刷sysupgrade.bin

**Comment by kl9800** [comment]
但是我记得刷完breed以后，刷sysupgrade，提示好像不让刷，具体提示什么我忘了，一会再去试试吧

**Comment by SouHong** [comment]
[openwrt-ramips-mt7621-hiwifi_hc5962-squashfs-factory.zip](https://github.com/coolsnowwolf/lede/files/4401734/openwrt-ramips-mt7621-hiwifi_hc5962-squashfs-factory.zip)
