### ISSUE TITLE
CONFIG_KERNEL_IPV6 is not set会导致qemu-ga编译失败

### ISSUE THREAD

**Issue by TwoBall** [coolsnowwolf/lede#4081]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：CONFIG_KERNEL_IPV6 is not set会导致qemu-ga编译失败

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：error: unknown option --disable-ipv6

**Comment by hcym** [comment]
改哪个干嘛，大雕的本来就是没有ipv6

**Comment by TwoBall** [comment]
> 改哪个干嘛，大雕的本来就是没有ipv6
有些kmod带ipv6的，看起来不简洁
