### ISSUE TITLE
qbittorrent崩溃

### ISSUE THREAD

**Issue by sandyowen** [coolsnowwolf/lede#4082]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
无法打开qbittorrent
### (1) 具体问题

A：开启qbittorrent没有反应

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：Sun Mar 29 08:01:43 2020 daemon.info procd: Instance qbittorrent::qbittorrent.main s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by Her0R0cket** [comment]
进ssh在命令行下运行下,看看有什么错吧
