### ISSUE TITLE
LXD LXC Support in Lean OpenDDWRT

### ISSUE THREAD

**Issue by kanglinyao** [coolsnowwolf/lede#4083]
Is it possible to have LINUX container（LXC,LXD) compiled into OpenWRT?
The LXDUI is a project allows users to manage LXC in a Web UI.
If you have these 2 enabled in OpenWrt, that would be fatastic.

**Comment by hxlls** [comment]
please compile by yourself，
![image](https://user-images.githubusercontent.com/43886952/77842294-39c51480-71c3-11ea-8952-eb01172f9ef5.png)
