### ISSUE TITLE
tubo acc中dns加速的bug以及建议

### ISSUE THREAD

**Issue by royalwei** [coolsnowwolf/lede#4091]
真心感谢大雕的项目，让我和越来越多的小伙伴用上openwrt，其中dns加速我测试了好长时间，但是确实存在问题，导致我帮小伙伴装路由器是都关闭了这个功能，具体有以下几个bug。
使用时间一长会导致dns解析错误，不得不关掉dns加速再开。
动态dns获取的ip不正确，关掉dns加速后正常。
猜测可能由于dns缓存的问题，希望可否加一个选项一键清除掉路由器的dns缓存来解决这个bug
PS：这个问题我用过的软路由，mt7621平台和高通平台出现过。

**Comment by hxlls** [comment]
首先这个不是BUG，这个是缓存的特性，实际上已经生效，但是缓存刷新时间，你的机器没生效而已，肯定这个东西有正面也有负面的效果，自己衡量好坏，在重申一次，这个不是BUG

**Comment by coolsnowwolf** [comment]
DDNS 那边可以设置独立的查询 DNS, 自己看看
