### ISSUE TITLE
请教一下lede的代码更新了以后比如新增功能或者修改的read么哪里看？

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#4092]
请教一下lede的代码更新了以后比如新增功能或者修改的read么哪里看？
我指的不是编译的readme
因为每天几乎都会git pull1-3次
不知道loean大的这个代码更新以后有没有更新到某个readme去
就是可以看到更新了什么修复了什么，什么版本，之类的

**Comment by EnnawYang** [comment]
https://github.com/coolsnowwolf/lede/commits/master
