### ISSUE TITLE
samba共享页面太不美观了,

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#4105]
![samba](https://user-images.githubusercontent.com/51162826/77887608-7b29f280-729d-11ea-9390-4ce31ee6fafb.PNG)
"允许匿名用户"可不可以改宽一些,或改成双行?
翻了原代码,不知道怎么改...

**Comment by lxwq** [comment]
![samba1](https://user-images.githubusercontent.com/51162826/77994305-56488480-735c-11ea-93bf-063346d2ce39.PNG)
改来改去改成这样鸟样子,谁再看看怎么弄

**Comment by EnnawYang** [comment]
换个主题它不香吗

**Comment by lxwq** [comment]
> 换个主题它不香吗

只安装了bootstarp主题,也用习惯这个主题了,

**Comment by lxwq** [comment]
![samba2](https://user-images.githubusercontent.com/51162826/78007114-68ccb900-7370-11ea-88f3-38fd14814b06.PNG)
搞定,总算好看一点了,下图是一点修改,
![samba lua](https://user-images.githubusercontent.com/51162826/78007199-839f2d80-7370-11ea-8d20-fd44325491c5.png)
