### ISSUE TITLE
更新最新SSR PLUS.ipk出错

### ISSUE THREAD

**Issue by liliass** [coolsnowwolf/lede#4106]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ *] 没有类似的issue

### (1) 具体问题
尝试更新最新版的 ssr plus.ipk, 
opkg install ssrplus.ipk
出现error can not find independence.
TCPPING
redsocks
dnssocks2

A：

### (2) 路由器型号和固件版本
固件版本 | OpenWrt R20.2.15 GDQ IPv4 v3.1[2020] Compiled by eSir / LuCI Master (git-20.058.13156-2faf063)
luci-app-ssr-plus | 154-3

A：

### (3) 详细日志

A：请问怎么正确方法更新。？ ？ 
谢谢

**Comment by cym422948** [comment]
git pull 拉取最新源码后再编译一次提取IPK或者整个固件刷入

**Comment by Promix953** [comment]
建议重新编译
现有升级的话需要安装TCPPING，redsocks，dnssocks2这三个依赖再安装ssrp，可能还有别的依赖问题，自找麻烦
