### ISSUE TITLE
resolv.conf中的dns总是被重置到127.0.0.11

### ISSUE THREAD

**Issue by nono8273** [coolsnowwolf/lede#4110]
## 1.resolv.conf中的dns总是被重置到127.0.0.11

旁路由运行openwrt，resolv.conf中的dns总是在重启后被重置为127.0.0.11，即使修改文件属性为444也无解，求教这个怎么改？

不然，openwrt的luci系统打开会很慢，求同袍们指教！谢谢！

**Comment by lin-xh** [comment]
docker中运行的openwrt吧？系统-启动项-本地启动脚本加入下面这段：
cat > /etc/resolv.conf <<EOF
search lan
nameserver 127.0.0.1
options ndots:0
EOF

**Comment by DecaLiu** [comment]
不行，还是会重置，放弃治疗了

**Comment by fryderykhuang** [comment]
哈哈，我也碰到这个问题，我是在容器里面拨号的，主机根本没网络，docker的127.0.0.11自然也无效

**Comment by 716c** [comment]
uci set dhcp.@dnsmasq[0].localuse="0"
