### ISSUE TITLE
用最新的源码，不能安装curl指令

### ISSUE THREAD

**Issue by 1203746884** [coolsnowwolf/lede#4111]
今天编译了最新源码后不能安装curl指令了，在之前直接可以opkg install curl安装成功
这个是今天安装curl给出的提示：
Unknown package 'curl'.
Collected errors:
 * opkg_install_cmd: Cannot install package curl.
有谁能说一下这个问题怎么解决吗？谢谢了！

**Comment by marcosteam** [comment]
是否已经使用`opkg update`命令更新过软件源？

**Comment by 1203746884** [comment]
> 是否已经使用`opkg update`命令更新过软件源？

是的，已经更新过了
我刚刚又在编译的配置界面找到了curl，我直接把它编译进去了，既不用安装了，谢谢了！
