### ISSUE TITLE
编译出来的img可以直接web更新使用，但是.vmdk的虚拟机文件，在虚拟机里不能正常启动，用img转换的vmdk也试过

### ISSUE THREAD

**Issue by 0jack-lei0** [coolsnowwolf/lede#4113]
![QQ图片20200330215922](https://user-images.githubusercontent.com/34858317/77920982-be05bd80-72d1-11ea-8784-b35360d0a42f.png)

**Comment by hhmaomao** [comment]
考虑一下vm里面的虚拟网卡转换一下，把主机的虚拟网卡绑定到vmnet1或其他vmnet，然后vmnet的模式设置为host only，更改后再试试就可以了，一般这个问题存在都是vm的问题，更改一下网卡后一般都没问题

**Comment by hue715** [comment]
有安装open-vm-tools试试吗？

**Comment by 0jack-lei0** [comment]
> 有安装open-vm-tools试试吗？

这个openwrt里不能上网要如何安装tools

**Comment by 0jack-lei0** [comment]
哎，搞一天，还是没有办法

**Comment by hue715** [comment]
> > 有安装open-vm-tools试试吗？
> 
> 这个openwrt里不能上网要如何安装tools

可以考虑在编译时选择open-vm-tools这个包

**Comment by Greeed-islanl** [comment]
最好你用软件转一下嘛好像叫“V2V”

**Comment by lonwern** [comment]
遇到过类似的问题，在虚拟机设置里把虚拟磁盘扩展到1G就可以了

![image](https://user-images.githubusercontent.com/5079364/78318677-f5a58b80-7597-11ea-94a0-d0382344cbfd.png)

**Comment by d975xbx** [comment]
vmkfstools -i centos-original_xxx.vmdk -d thin centos-original_0_新的xxx.vmdk.
转换以后要有两个文件才ok，一个是xxx.vmdk，另一个是xxx flat.vmdk.一起上传到esxi。

**Comment by luxiaok** [comment]
在VM配置里把硬盘类型改成 `IDE` 试试~
