### ISSUE TITLE
3月份以后编译的版本状态页wan口显示的是lan口信息

### ISSUE THREAD

**Issue by badcrazy** [coolsnowwolf/lede#4115]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue
具体什么时候出现不清楚了，讲真没去关注，但是看了下2月24日的一个截图还是正常的，肯定是之后，这个具体是什么原因？真心求教
<img src="https://s1.ax1x.com/2020/03/30/GuNblj.jpg" alt="GuNblj.jpg" border="0" />

**Comment by coolsnowwolf** [comment]
废话，你的 LAN IP 的 网关也是自己

**Comment by badcrazy** [comment]
> 废话，你的 LAN IP 的 网关也是自己

感谢lean大回复，我就是想知道怎么能让这里正确显示wan口，谢谢

**Comment by niceguy3-31** [comment]
我也碰到过，这样还会无法上网，重置下好了

**Comment by shu0802** [comment]
与你的一样
![image](https://user-images.githubusercontent.com/43750373/77981961-c4ca1a00-733d-11ea-9946-b6044744fe85.png)

**Comment by shu0802** [comment]
> 我也碰到过，这样还会无法上网，重置下好了

重置后是什么状态

**Comment by shu0802** [comment]
原来是设置LAN口处原因，这样设置就正常了
![image](https://user-images.githubusercontent.com/43750373/77990706-99065e80-7354-11ea-9328-b75dbb1f59dc.png)

**Comment by xayane** [comment]
master/package/lean/default-settings/files/zzz-default-settings
可以修改默认配置，可以根据自己的需求自定义。
