### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by zlylong** [coolsnowwolf/lede#4129]
DHCP使用说明文字中“可为每个主机单独设定 DHCP 租期的时长，例如：12h、3d、inifinite，分别表示 12 小时、3 天、永久。”
inifinite这个单词拼错了，应该是：infinite

**Comment by EnnawYang** [comment]
![Snipaste_2020-03-31_21-01-36](https://user-images.githubusercontent.com/6705663/78029271-dee21780-7392-11ea-938d-af63ece0b81a.png)

**Comment by zlylong** [comment]
哦。。。。那就可能是我的没更新。。
