### ISSUE TITLE
遇到个奇怪的问题， 请教大家！

### ISSUE THREAD

**Issue by keivenliao** [coolsnowwolf/lede#4133]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题
A：看到今天的comment 提到了 luci-app-cpufreq 我就想看看我的编译里是否包含。
才发现在 Applications 列表里找不到，但是搜索又能搜到，这个是什么情况啊？

![image](https://user-images.githubusercontent.com/12838693/78091350-1c7c8a00-73ff-11ea-9b83-6f54e20c8ad9.png)

![image](https://user-images.githubusercontent.com/12838693/78091378-3027f080-73ff-11ea-9219-0129ab9d29b3.png)

**Comment by EnnawYang** [comment]
不适用于您的机型 亲

**Comment by keivenliao** [comment]
> 不适用于您的机型 亲

x86 的没有这个选项是吗？

**Comment by EnnawYang** [comment]
> > 不适用于您的机型 亲
> 
> x86 的没有这个选项是吗？

暂时不支持x86
