### ISSUE TITLE
编译总是同一个错误，求解~~~

### ISSUE THREAD

**Issue by dec2hex** [coolsnowwolf/lede#4136]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：使用的google云编译的固件，按照说明操作，未做固件修改，老是出现错误，详细见日志。求解。（无论单线程编译还是多线程编译都一样的错误。）

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

collect2: error: ld returned 1 exit status
node.target.mk:166: recipe for target '/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/node' failed
make[5]: *** [/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/node] Error 1
make[5]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
cctest.target.mk:181: recipe for target '/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/cctest' failed
make[5]: *** [/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/cctest] Error 1
collect2: error: ld returned 1 exit status
node_mksnapshot.target.mk:159: recipe for target '/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/node_mksnapshot' failed
make[5]: *** [/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/out/Release/node_mksnapshot] Error 1
rm 6abd235f02f0e37a8f0304158aa988b77e16de0d.intermediate 265a4bfe6d99368fb3965b8e7ec53f7baca327c7.intermediate 3b7e94a4056e200c7fdbd7ccdf0dc72d0b991ffe.intermediate 623dfb3ef18f5e4607d3f9ffd0b8ed5b2528af40.intermediate 96a031982c9275dc603f994ba9e1c63d231fe956.intermediate
Makefile:101: recipe for target 'node' failed
make[4]: *** [node] Error 2
make[4]: Leaving directory '/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0'
Makefile:150: recipe for target '/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/.built' failed
make[3]: *** [/home/endmanteng/lede/build_dir/target-x86_64_musl/node-v12.15.0/.built] Error 2
make[3]: Leaving directory '/home/endmanteng/lede/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#8791.05#532.10#1544.91
package/Makefile:111: recipe for target 'package/feeds/packages/node/compile' failed
make[2]: *** [package/feeds/packages/node/compile] Error 2
make[2]: Leaving directory '/home/endmanteng/lede'
package/Makefile:107: recipe for target '/home/endmanteng/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/endmanteng/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/endmanteng/lede'
Build failed - please re-run with -j1 to see the real error message
/home/endmanteng/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by whlsxl** [comment]
升级依赖，
https://github.com/coolsnowwolf/lede#%E7%BC%96%E8%AF%91%E5%91%BD%E4%BB%A4%E5%A6%82%E4%B8%8B
