### ISSUE TITLE
最新编译的固件在j1900主板上没法重启。

### ISSUE THREAD

**Issue by garygary1** [coolsnowwolf/lede#4137]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：我是翔升的j1900主板，安装官方版和lede都没法重启。

主板装windows可以重启。
不知有什么办法解决。

**Comment by garygary1** [comment]
优盘启动的。

**Comment by ja5onwu** [comment]
进去BIOS 在BIOS主页面有个选择系统的选项,选择Ubuntu

**Comment by garygary1** [comment]
我去试试，这个主板里三个选项，win8.1 win7，android。

**Comment by lloyd18** [comment]
我的之前也是，bios设置一下就好了，默认win7，选linux就好了

**Comment by ja5onwu** [comment]
可能主板不同,有些不同,反正把另外2个选项都试下就好

**Comment by garygary1** [comment]
多谢以上各位。搞定了，我的主板改成android就可以了。
