### ISSUE TITLE
移植SSR plus到原版OpenWrt SNAPSHOT r12787下的问题

### ISSUE THREAD

**Issue by tinnlux** [coolsnowwolf/lede#4143]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：移植ssr plus到原版OpenWrt SNAPSHOT，新增节点的 “导入配置信息”功能失效，在lede下无问题。

### (2) 路由器型号和固件版本

A：测试手头x86、Newifi-D2、lenovo-y1、xiaomi-nano等设备在OpenWrt SNAPSHOT下都有此问题。

### (3) 详细日志

A：无错误日志，无报错。

**Comment by hcym** [comment]
是滴，导入无效，其它还行，可能用1907分支更好

**Comment by dongjuanyong** [comment]
以下patch实验成功：
```
diff --git a/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua b/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
index 0ae7bbe688..7b05ce5cfc 100644
--- a/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
+++ b/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
@@ -19,7 +19,7 @@ local cache = {}
 local nodeResult = setmetatable({}, { __index = cache })  -- update result
 local name = 'shadowsocksr'
 local uciType = 'servers'
-local ucic = uci.cursor()
+local ucic = luci.model.uci.cursor()
 local proxy = ucic:get_first(name, 'server_subscribe', 'proxy', '0')
 local switch = ucic:get_first(name, 'server_subscribe', 'switch', '1')
 local subscribe_url = ucic:get_first(name, 'server_subscribe', 'subscribe_url', {})
```

**Comment by hcym** [comment]
牛叉啦，不过原版还是用原版ss和v2合适，对ipv6友好，就是少了trojian

**Comment by dongjuanyong** [comment]
你说的ipv6友好是指哪方面，dnsmasq屏蔽aaaa查询么，patch都是现成的，考过去改改语句就能用
除了部分内核驱动（不兼容snapshot的5.4内核）别的问题都不大

**Comment by dongjuanyong** [comment]
话说我只用v2（mkcp），配合udp2raw防qos，dnscrypt-proxy做doh查询和aaaa屏蔽，稳定好用

**Comment by haxc** [comment]
> 以下patch实验成功：
> 
> ```
> diff --git a/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua b/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> index 0ae7bbe688..7b05ce5cfc 100644
> --- a/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> +++ b/package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> @@ -19,7 +19,7 @@ local cache = {}
>  local nodeResult = setmetatable({}, { __index = cache })  -- update result
>  local name = 'shadowsocksr'
>  local uciType = 'servers'
> -local ucic = uci.cursor()
> +local ucic = luci.model.uci.cursor()
>  local proxy = ucic:get_first(name, 'server_subscribe', 'proxy', '0')
>  local switch = ucic:get_first(name, 'server_subscribe', 'switch', '1')
>  local subscribe_url = ucic:get_first(name, 'server_subscribe', 'subscribe_url', {})
> ```

可以提交一下pr

**Comment by tinnlux** [comment]
@dongjuanyong 实测失败，你这个补丁是修复不能更新订阅的问题的。修改的文件也是订阅相关。

**Comment by hcym** [comment]
原版用哪个passwall也不错，刚刚用snapshot版本编译了，除了没有内置广告其它和官方融合没问题

**Comment by tty228** [comment]
`sed -i "s/'cbid.shadowsocksr.'/'widget.cbid.shadowsocksr.'/g" /usr/lib/lua/luci/view/shadowsocksr/ssrurl.htm`

**Comment by dongjuanyong** [comment]
subscribe.lua的修改应该对lede没什么影响，ssrurl.htm就不知道了

**Comment by dongjuanyong** [comment]
又看了一眼，input的加个widget.能解决，checkbox的id根本对不上，想正确使用的话必须改用getElementsByName

**Comment by iyuangang** [comment]
> 又看了一眼，input的加个widget.能解决，checkbox的id根本对不上，想正确使用的话必须改用getElementsByName

经测试，可修复。
[#issues7](https://github.com/iyuangang/openwrt/issues/7)

**Comment by dongjuanyong** [comment]
> > 又看了一眼，input的加个widget.能解决，checkbox的id根本对不上，想正确使用的话必须改用getElementsByName
> 
> 经测试，可修复。
> [#issues7](https://github.com/iyuangang/openwrt/issues/7)
> ![图片](https://user-images.githubusercontent.com/20696803/78451840-6f359a80-76ba-11ea-85e1-7134579d3673.png)

你再试试，提示成功没问题，但打勾的那种设置（checkbox）都不会生效，因为id根本不对：
![Untitled1](https://user-images.githubusercontent.com/38952488/78452699-41068980-76bf-11ea-9453-505e3a7483cb.png)
上面那个tls的checkbox的id是cbd31fabcd，你用getElementById抓不到，只能getElementsByName

**Comment by iyuangang** [comment]
> > > 又看了一眼，input的加个widget.能解决，checkbox的id根本对不上，想正确使用的话必须改用getElementsByName
> > 
> > 
> > 经测试，可修复。
> > [#issues7](https://github.com/iyuangang/openwrt/issues/7)
> > ![图片](https://user-images.githubusercontent.com/20696803/78451840-6f359a80-76ba-11ea-85e1-7134579d3673.png)
> 
> 你再试试，提示成功没问题，但打勾的那种设置（checkbox）都不会生效，因为id根本不对：
> ![Untitled1](https://user-images.githubusercontent.com/38952488/78452699-41068980-76bf-11ea-9453-505e3a7483cb.png)
> 上面那个tls的checkbox的id是cbd31fabcd，你用getElementById抓不到，只能getElementsByName

用的getElementsByName

**Comment by dongjuanyong** [comment]
> > > > 又看了一眼，input的加个widget.能解决，checkbox的id根本对不上，想正确使用的话必须改用getElementsByName
> > > 
> > > 
> > > 经测试，可修复。
> > > [#issues7](https://github.com/iyuangang/openwrt/issues/7)
> > > ![图片](https://user-images.githubusercontent.com/20696803/78451840-6f359a80-76ba-11ea-85e1-7134579d3673.png)
> > 
> > 
> > 你再试试，提示成功没问题，但打勾的那种设置（checkbox）都不会生效，因为id根本不对：
> > ![Untitled1](https://user-images.githubusercontent.com/38952488/78452699-41068980-76bf-11ea-9453-505e3a7483cb.png)
> > 上面那个tls的checkbox的id是cbd31fabcd，你用getElementById抓不到，只能getElementsByName
> 
> 用的getElementsByName

那就没问题了，有可能的话希望用lede原版（非19.07或snapshot）的朋友试试PR #4154 能兼容的话就方便了
