### ISSUE TITLE
ssrplus的启用广告屏蔽的正确使用方式？

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#4148]
开启了 ssrplus里面的启用广告屏蔽之后youtube的app客户端是不是就不会有广告了？
还是说到了广告的时候会转圈？

![op去广告](https://user-images.githubusercontent.com/12111990/78213328-f0d3cf80-74e4-11ea-8fc3-0691cde6ee8c.JPG)

**Comment by norikohxb** [comment]
开启这个会不会造成平板+youtube的apk在运行的时候，比如到了要播放广告的阶段，会不会有时候会卡住，就是一直在那边转圈圈。或者这个究竟是什么功效？能实现什么目的？会不会和 广告屏蔽大师adbyby的打钩相冲突。

**Comment by ElectronicElephant** [comment]
首先，我感觉确实需要一定人手来写一些doc

其次，图片里的问题建议你自己试一下。

**Comment by qianxu2001** [comment]
自己测试啊

**Comment by Promix953** [comment]
自己试一下很累吗？

**Comment by norikohxb** [comment]
主要是我自己的谷歌vps也不知什么问题也不是稳定，所以才要咨询一下，因为如果是gcp不稳定，本身就会转圈圈。
