### ISSUE TITLE
维护一下N2N_V2的新版本吧

### ISSUE THREAD

**Issue by BayMaxzhang001** [coolsnowwolf/lede#415]
东拼西凑，找到了别人编译的新版本，希望能加入新的源里，打包在群里。不知道怎么维护。。。。

luci页面有状态显示

luci界面加入了
1.设置本地IP
  添加本地IP绕过相同的NAT问题 
2.设置打洞间隔
  设置NAT打洞间隔（如果不开启这个选项，默认间隔为20秒） 
3.设置检测IP
  开启IP检测功能，当指定IP PING不通时重启N2N

**Comment by fuqiang03** [comment]
有地址没发个

**Comment by SouHong** [comment]
群里没有找到、

**Comment by BayMaxzhang001** [comment]
@fuqiang03 @SouHong  让群管理传了~~ 在看一下~

**Comment by fuqiang03** [comment]
luci 可以移植 二进制 没法改啊
n2n_v2 我在网上找了一遍都是老的源码

**Comment by fuqiang03** [comment]
来张效果图
![qq 20180525004415](https://user-images.githubusercontent.com/26851715/40499536-d035e746-5fb4-11e8-95f8-798eca0df471.png)

**Comment by BayMaxzhang001** [comment]
@fuqiang03  直接用群里包 完美~
