### ISSUE TITLE
enhancement：ShadowSocksR Plus+  列表显示服务器地址的需求

### ISSUE THREAD

**Issue by babylife** [coolsnowwolf/lede#4155]
由于使用订阅地址，多个服务器所有备注都一样 ，如下截图，希望能够在选择节点的列表下拉框上节点后面加上实际服务器地址，也就是把真实地址写在下拉列表中后面紧跟显示，这样可以知道实际的服务器地址以便进行切换选择。附上截图对比，后面是passwall的给老大参考下。 希望老大可以采纳
![image](https://user-images.githubusercontent.com/31977161/78322011-1e318380-75a0-11ea-94cd-a6ed0ad3093a.png)

![image](https://user-images.githubusercontent.com/31977161/78322137-651f7900-75a0-11ea-8381-5941e2ad224b.png)

**Comment by Promix953** [comment]
服务器列表直接点击应用，更直观，还能看延时

**Comment by iyuangang** [comment]
<img width="660" alt="图片" src="https://user-images.githubusercontent.com/20696803/78336209-9492ad80-75c1-11ea-86b7-5888cc326ad3.png">

这边感觉更好一点儿

**Comment by babylife** [comment]
恩 也是个方法 谢谢

**Comment by babylife** [comment]
> 服务器列表直接点击应用，更直观，还能看延时

服务器列表也是一样的描述 不知道哪个节点

**Comment by Promix953** [comment]
> > 服务器列表直接点击应用，更直观，还能看延时
> 
> 服务器列表也是一样的描述 不知道哪个节点

忘了服务器列表的确看不到具体服务器地址。。。
但是为什么会出现节点别名和延迟没有参考意义，需要通过具体地址选择节点的情况？

**Comment by coolsnowwolf** [comment]
![Uploading image.png…]()

其实挺难看的

**Comment by babylife** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/31687149/78379278-b1040980-7604-11ea-9218-f9cdf5a7b196.png)
> 
> 
> 
> 
> 
> 其实挺难看的。。

老大 其实是有点难看，不过是不是加个复选框，显示服务器地址？服务器列表那里也是 别名一列全部一样哈哈

**Comment by qianxu2001** [comment]
建议换机场

**Comment by babylife** [comment]
> 建议换机场

换机场代价有点大

**Comment by Promix953** [comment]
> > 建议换机场
> 
> 换机场代价有点大

所以还是那个问题：为什么节点名字和延迟不能作为选择依据，一定要看机场实际地址？

**Comment by babylife** [comment]
> > > 建议换机场
> > 
> > 
> > 换机场代价有点大
> 
> 所以还是那个问题：为什么节点名字和延迟不能作为选择依据，一定要看机场实际地址？

老大说的也不无道理，

**Comment by babylife** [comment]
机场已更新解决，谢谢！
