### ISSUE TITLE
网件R6350编译OP固件,重启后丢失配置

### ISSUE THREAD

**Issue by ahfncj** [coolsnowwolf/lede#4158]
路由器型号:网件R6350
固件版本:OpenWrt R20.3.19 / LuCI Master (git-20.085.19816-df13074)
故障现象:路由器重启后丢失配置.所有修改的设置全部还原.

**Comment by kl9800** [comment]
也许是固件体积大小到了临界值，比如你的设备说明是允许32M，你编译的固件体积到了30M，会很可能出现重启后一切还原的现象，目前我测试来看，假设你的设备允许32M，那么固件体积大小最好不要超过28M

**Comment by ahfncj** [comment]
> 也许是固件体积大小到了临界值，某些你的设备说明是允许32M，你编译的固件体积到了30M，会很可能出现重启后一切还原的现象，目前我测试来看，假设你的设备允许32M，那么固件体积大小最好不要超过28M

路由器的ROM是128m 固件是33m

**Comment by kl9800** [comment]
我知道，我的极路由也128，但固件只要超过28就不行，好像跟overlayfs有关

**Comment by coolsnowwolf** [comment]
R6350 的分区问题，不是全部 ROM 都给你用的，最大 32MB
