### ISSUE TITLE
ssr-plus 插件，能否加个绑定网卡的选项

### ISSUE THREAD

**Issue by wcsjtu** [coolsnowwolf/lede#4159]
ssr-plus 插件，能否加个绑定网卡的选项， 直接绑定0.0.0.0等于直接开放到公网了， 太不安全了。应该绑定只需要绑定LAN口网卡即可

**Comment by coolsnowwolf** [comment]
绑定0.0.0.0 公网也是不能访问的，除非你自己作死全打开

**Comment by dongjuanyong** [comment]
你难道没开防火墙么？
还是你特地把ssr监听的端口在防火墙上给开放了？

**Comment by Promix953** [comment]
[https://canyouseeme.org/](url)
自己扫描下就知道了

**Comment by wcsjtu** [comment]
嗯， 不开防火墙确实没问题。我看Dropbear 可以选择绑定的网卡， 所以才想这个能不能也加上这个功能， 算是个双保险。。。。。。
