### ISSUE TITLE
最新编译的固件为什么SSR P+不能用gfw模式？

### ISSUE THREAD

**Issue by zatenchan** [coolsnowwolf/lede#4163]
白名单跟全局都正常，就是不能用gfw模式，很奇怪，搭建了dns服务器，所有dns都指向内网的adguard服务器，gfw模式不能用，为什么？

**Comment by garypang13** [comment]
重定向53端口后就只能用白名单模式了.

**Comment by coolsnowwolf** [comment]
adg home 并没有ipset 功能。在turbo acc 加入 adg home ip地址即可。 ps：ssr plus 自带adg home 规则订阅了

**Comment by zatenchan** [comment]
> adg home 并没有ipset 功能。在turbo acc 加入 adg home ip地址即可。 ps：ssr plus 自带adg home 规则订阅了

谢谢lean大神，昨天晚上研究了gfw的原理后把电脑dns指向哦openwrt就正常了，现在有个新问题就是手机无法看YouTube，其他网站跟国外app访问都正常，YouTube页面也能刷新，就是视频没办法加载，把service.google.cn加入强制代理也不行，这是什么原因？最后感谢大神给我们小白提供了这么好的平台，昨天第一次编译成功，加入了透明网桥效率吊打lede。

**Comment by zatenchan** [comment]
> adg home 并没有ipset 功能。在turbo acc 加入 adg home ip地址即可。 ps：ssr plus 自带adg home 规则订阅了

大神，按你的说法把adg的地址加入了acc的dns里，openwrt网关设置成adg，ssr里pdnsd查询试过adg也试过默认8.8.4.4，现在有一个很奇怪的问题就是google能用能访问，youtube页面能刷新，但是视频看不了，accounts.google.com无法访问谷歌账号无法登陆。是我adg设置有问题吗？
