### ISSUE TITLE
J1900 CPU运行一段时间后单核频率会一直在2.4Ghz不降频

### ISSUE THREAD

**Issue by lin1123** [coolsnowwolf/lede#4172]
![批注 2020-04-04 202544](https://user-images.githubusercontent.com/62827465/78450687-0139a500-76b3-11ea-9557-4a52402f0e60.png)
![批注 2020-04-04 202610](https://user-images.githubusercontent.com/62827465/78450691-039bff00-76b3-11ea-8658-c5364a3233be.png)

**Comment by hcym** [comment]
没事超哪个心，我一直开，早4点在光猫后面一分钟重启一次，声音正常cpu正常科学技术正常就行

**Comment by lin1123** [comment]
> 没事超哪个心，我一直开，早4点在光猫后面一分钟重启一次，声音正常cpu正常科学技术正常就行

只是觉得有点奇怪，用其他的固件就没这回事

**Comment by dolphinpaopao** [comment]
感觉这个应该是正常的，有程序后台运行，保证一个核心高频可以避免可能的网络延迟抖动等问题。
