### ISSUE TITLE
迅雷快鸟自3月开始不能用了。

### ISSUE THREAD

**Issue by bdhjiajia** [coolsnowwolf/lede#4180]
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：迅雷快鸟自3月开始不能正常使用了，迅雷貌似采用了更新的方法，不知道大佬们可否更新一波。

### (2) 路由器型号和固件版本

A：所有型号

### (3) 详细日志

A：

**Comment by yjnomm** [comment]
我的正常，正在提速中！
