### ISSUE TITLE
开启下载时候，cpu飙升

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#4197]
Hi Team，

经过一段时间的观察，
一旦开始下载时候，路由器的cpu就开始飙升，下载完成后，便会恢复

![newifi3](https://user-images.githubusercontent.com/25215114/78542783-446a5400-782a-11ea-8612-1384e76539ef.png)

路由器型号 newifi3 d2 

请问，有比较好的解决办法吗？

BR
Robin

**Comment by liliass** [comment]
正常吧？
我的3865U ， 130Mbps 都30-40% load

**Comment by Guxing0321** [comment]
Hi ,

我注意观察了下，就是cpu升高后，确实网络变卡了，
我看到有人使用cpulimt 这个插件，我想问下这个你们建议使用吗
