### ISSUE TITLE
報錯:No package 'protobuf' found

### ISSUE THREAD

**Issue by snowrice** [coolsnowwolf/lede#420]
checking for protobuf >= 2.6.0... no
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

No package 'protobuf' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make[3]: *** [/home/rice/LEDE/WRT1900ac/build_dir/hostpkg/libprotobuf-c-v1.2.1/.configured] Error 1
make[3]: Leaving directory `/home/rice/LEDE/WRT1900ac/feeds/packages/libs/protobuf-c'
time: package/feeds/packages/protobuf-c/host-compile#25.11#3.45#33.43
make[2]: *** [package/feeds/packages/protobuf-c/host/compile] Error 2
make[2]: Leaving directory `/home/rice/LEDE/WRT1900ac'
make[1]: *** [/home/rice/LEDE/WRT1900ac/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/rice/LEDE/WRT1900ac'
make: *** [world] Error 2

但是我明明已經裝了最新版的protobuf,請問如何解決?
OS: Centos 7 x86_x64

**Comment by jeremy7098** [comment]
在compile libprotobuf-c 時,會找 protobuf 的版本, 
可能是因在 compile libprotobuf-c 時,但 protobuf 還未 compile 所導致

我的作法來解決這問題,
1.先下載 新的 sourcecode
2.執行 feeds updata -a 
3.執行 feeds install -a
4.在執行 make menuconfig 時, 除了選擇路由外,再把選擇 libraries--> protobuf
5. make 
這檥應可成功 (因 libprotobuf-c 不會 compile到)

6,成功後,再執行make menuconfig ,選擇你所要的應用後,再make ,就可以了

**Comment by Love4Taylor** [comment]
直接 `make -j1 V=s package/feeds/packages/protobuf/compile` 就行了

**Comment by kill33** [comment]
- 按照楼上的做法单独编译了protobuf，通过后又碰到了protobuf-c编译失败。
- 搜了下发现这是protobuf-c的一个[issue279](https://github.com/protobuf-c/protobuf-c/issues/279),
-- 于是package/feeds/packages/protobuf-c/里把PKG_VERSION改成了1.3.0 PKG_MIRROR_HASH清空
- 然后make -j1 V=s package/feeds/packages/protobuf-c/compile通过
- 最后在全局make V=s -j8就通过了
