### ISSUE TITLE
acrh17 编译4月6日源码，刷机后，改lan地址，无限重启

### ISSUE THREAD

**Issue by wilson-chan2019** [coolsnowwolf/lede#4204]
acrh17 编译4月6日源码，刷机后，改lan地址（我改成了192.168.15.1），无法进入web,然后几分钟自动重启，自动重启后，也是无法进入web，再几分钟又自动重启，如此反复。恢复出厂或重刷再改成192.168.15.1也是这样，无法进入web,然后反复重启。

**Comment by king9039** [comment]
我也是，我还以为是我固件有问题，刷了固件后有线用了4 5个小时都没问题，无线几分钟就自动重启
