### ISSUE TITLE
R7.7.2无线不稳定掉线只能重启路由

### ISSUE THREAD

**Issue by tomerilery** [coolsnowwolf/lede#421]
R7.7.2无线不稳定，才运行了不到24小时，日志就显示无线out of control  所有设备都连不上了，只能重启路由，机子WRT1200AC

**Comment by gavin219** [comment]
最新的wifi驱动，hostpad都有问题，自行将此回滚到上个版本wifi2018-03-05，hostapd-2017-08-24
