### ISSUE TITLE
百度网盘网页版更新

### ISSUE THREAD

**Issue by hhmaomao** [coolsnowwolf/lede#4211]
我发现大神软件包内的百度网盘插件原作者已经好几个月没有更新，也没有更新issues了，是否能尝试更换一个源，如：https://github.com/iikira/BaiduPCS-Go，看了一下支持的系统也很多，作者更新也很勤快

**Comment by Erope** [comment]
先换上我最近修的吧 那个最近都没办法登录了.. https://github.com/Erope/baidupcs-web/releases/
你发的那个是脚本，没WEB端

**Comment by Potterli20** [comment]
@Erope 去跟lede的源pr一下？换一下？

**Comment by hhmaomao** [comment]
感谢大神支持

**Comment by KFERMercer** [comment]
可以用luci做个界面出来, 但是工作量...

**Comment by Erope** [comment]
> @Erope 去跟lede的源pr一下？换一下？

等原作者更新吧

**Comment by Erope** [comment]
> > @Erope 去跟lede的源pr一下？换一下？
> 
> 等原作者更新吧

现在这个只是被逼的用不了才自己改的

**Comment by Potterli20** [comment]
> 
> 
> > > @Erope 去跟lede的源pr一下？换一下？
> > 
> > 
> > 等原作者更新吧
> 
> 现在这个只是被逼的用不了才自己改的

哦哦哦
