### ISSUE TITLE
关于SSR+客户端开启后国内外服务器均无法连接的问题

### ISSUE THREAD

**Issue by 740527654** [coolsnowwolf/lede#4215]
今早上本来是正常运行，从v2节点切换成ssr节点后，不管怎么设置，国内和国外的服务器都无法正常连接了。关闭后国内又可以上网，手机试了一下机场也是正常的。请问这是什么原因呢

**Comment by coolsnowwolf** [comment]
描述不清

**Comment by 740527654** [comment]
> 描述不清
╮（╯＿╰）╭其实就是不知道为啥，我打开SSR后完全无法上网了。但是机场和网络本身是没有问题的。不知道该怎么办。卸载重装么？
![Screenshot_20200407_153928_com huawei browser](https://user-images.githubusercontent.com/63200055/78643028-367a0900-78e6-11ea-83ff-1ea1a3a333bf.jpg)

**Comment by coolsnowwolf** [comment]
你找找作者吧，这里不处理魔改版本

**Comment by 740527654** [comment]
> 你找找作者吧，这里不处理魔改版本

原来这是魔改的我不太清楚。不好意思了
