### ISSUE TITLE
重启软路由以后，显示“ShadowsocksR Plus+ 运行中”，但实际无法使用，“【谷歌】连通性检查”失败

### ISSUE THREAD

**Issue by lovelyOK** [coolsnowwolf/lede#4219]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：ADSL双线负载均衡接入。重启软路由以后，显示“ShadowsocksR Plus+ 运行中”，但实际无法使用，“【谷歌】连通性检查”失败，需要在“ShadowSocksR Plus+ 设置”点击“保存应用”按钮后恢复正常。

### (2) 路由器型号和固件版本

A：4月5日编译版本，J1900 x86

### (3) 详细日志

A：

**Comment by lovelyOK** [comment]
在启动项里面增加：
sleep 60
/etc/init.d/shadowsocksr restart

可以暂时解决这个使用问题。

**Comment by dolphinpaopao** [comment]
作者提到过多线目前会引起很多问题，不好解决。很多ipk并不是为这种环境设计的。

**Comment by lovelyOK** [comment]
> 作者提到过多线目前会引起很多问题，不好解决。很多ipk并不是为这种环境设计的。

你的意思，是不是在SSR+里面把“自动线程”改成“1线程”？

**Comment by dolphinpaopao** [comment]
不是SSR+多线程，是多WAN。

**Comment by lovelyOK** [comment]
> 不是SSR+多线程，是多WAN。

原来如此，谢谢了。

**Comment by dolphinpaopao** [comment]
> > 不是SSR+多线程，是多WAN。
> 
> 原来如此，谢谢了。

不客气。
