### ISSUE TITLE
ACRH17编译更新4月2日以后版本，无线5G疯狂自动掉线

### ISSUE THREAD

**Issue by cindzzic** [coolsnowwolf/lede#4221]
1、ACRH17编译更新4月2日以后版本，无线5G疯狂自动掉线，2.4G不稳定，PC端偶尔ping值1000左右。
Q：是否搜索了issue (使用 "x" 选择)
 [x ] 没有类似的issue（已搜索，无类似issue）
 2、详细叙述
 (1) 具体问题
无线5G疯狂掉线，2.4G不稳定，PC端偶尔ping值1000左右。
 (2) 路由器型号和固件版本
ACRH17，OpenWrt R20.3.19 / LuCI Master (git-20.087.30210-56fe7ae) 
 (3) 详细日志
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/4443880/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/4443881/default.txt)

**Comment by jackberry** [comment]
我确实也遇到同样的问题，你编译了airplay2吗？

**Comment by cindzzic** [comment]
> 
> 
> 我确实也遇到同样的问题，你编译了airplay2吗？

没有；大雕默认配置，增加了aria2，nps，baidupcs

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/78677453-56c3bb00-791a-11ea-8cfc-da331b318eab.png)

OP 官方无线驱动爆炸了。。。

**Comment by cindzzic** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/31687149/78677453-56c3bb00-791a-11ea-8cfc-da331b318eab.png)
> 
> OP 官方无线驱动爆炸了。。。

雕兄，这咋解决？可以在配置文件里选用那个文件名为ath10k-ct的无线驱动不？

**Comment by cindzzic** [comment]
> 
> 
> 我确实也遇到同样的问题，你编译了airplay2吗？

我刚刚选用了这个ath10k-ct驱动编译了下，貌似暂时没问题了
![图片](https://user-images.githubusercontent.com/12590039/78680037-9049f580-791d-11ea-8b05-f7a809a47915.png)
