### ISSUE TITLE
请教下如何扩展overlayfs空间

### ISSUE THREAD

**Issue by shown1985** [coolsnowwolf/lede#4225]
编译R7000固件后刷完，发现overlayfs只有1.7M空间？请问下是哪个姿势刷的不正确啊

**Comment by 9l** [comment]
扩展overlay空间去看esir的视频

**Comment by shown1985** [comment]
> 扩展overlay空间去看esir的视频

好的，谢谢

**Comment by impl1874** [comment]
刷完lede支持无线吗？
