### ISSUE TITLE
Whatsapp 连接中

### ISSUE THREAD

**Issue by liliass** [coolsnowwolf/lede#4226]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ *] 没有类似的issue

### (1) 具体问题

A：打开手机iOS Whatsapp， 提示连接中。而且登不上。 
使用其他iOS的app Shadowrocket, 连接正常。 

### (2) 路由器型号和固件版本

A：

luci-app-ssr-plus | 175-4
-- | --

### (3) 详细日志

A：在Shadowrocket里的log， 显示走 TCP e15.whatsapp.net:5222

**Comment by liliass** [comment]
官方IP段

31.13.64.51/32
31.13.64.53/32
31.13.65.49/32
31.13.65.50/32
31.13.66.51/32
31.13.66.56/32
31.13.67.52/31
31.13.68.48/32
31.13.68.52/32
31.13.70.49/32
31.13.70.50/32
31.13.71.49/32
31.13.71.50/32
31.13.72.48/32
31.13.72.52/32
31.13.73.52/31
31.13.74.52/31
31.13.79.53/32
31.13.79.54/32
31.13.80.48/32
31.13.80.53/32
31.13.81.48/32
31.13.81.53/32
31.13.82.51/32
31.13.82.55/32
31.13.83.49/32
31.13.83.51/32
31.13.84.49/32
31.13.84.51/32
31.13.85.49/32
31.13.85.51/32
31.13.86.49/32
31.13.86.51/32
31.13.87.48/32
31.13.87.51/32
31.13.89.53/32
31.13.89.54/32
31.13.90.49/32
31.13.90.51/32
31.13.91.49/32
31.13.91.51/32
31.13.92.48/32
31.13.92.52/32
31.13.93.53/32
31.13.93.54/32
31.13.94.52/32
31.13.94.54/32
31.13.95.50/32
31.13.95.63/32
50.22.240.160/27
50.23.90.128/27
69.171.239.11/32
69.171.250.52/32
69.171.250.54/32
69.171.255.11/32
102.132.96.54/31
102.132.97.54/31
108.168.174.0/27
108.168.176.192/26
108.168.177.0/27
108.168.180.96/27
108.168.254.65/32
108.168.255.224/32
108.168.255.227/32
157.240.1.53/32
157.240.1.54/32
157.240.2.53/32
157.240.2.54/32
157.240.3.54/31
157.240.6.53/32
157.240.6.54/32
157.240.7.53/32
157.240.7.54/32
157.240.8.53/32
157.240.8.54/32
157.240.9.53/32
157.240.9.54/32
157.240.10.53/32
157.240.10.54/32
157.240.11.53/32
157.240.11.54/32
157.240.12.53/32
157.240.12.54/32
157.240.13.54/31
157.240.14.52/31
157.240.15.53/32
157.240.15.54/32
157.240.16.52/31
157.240.18.52/31
157.240.19.53/32
157.240.19.54/32
157.240.20.52/31
157.240.21.52/31
157.240.22.53/32
157.240.22.54/32
157.240.23.53/32
157.240.23.54/32
157.240.24.54/31
157.240.25.54/31
157.240.26.54/31
157.240.27.54/31
157.240.28.51/32
157.240.28.55/32
157.240.29.53/32
157.240.29.54/32
157.240.30.54/31
157.240.192.52/32
157.240.192.55/32
157.240.193.50/32
157.240.193.55/32
157.240.194.54/31
157.240.195.54/32
157.240.195.56/32
157.240.196.60/31
157.240.201.60/31
158.85.0.96/27
158.85.5.192/27
158.85.46.128/27
158.85.48.224/27
158.85.58.32/27
158.85.58.96/27
158.85.61.192/27
158.85.224.160/27
158.85.233.32/27
169.44.36.0/26
169.44.80.32/27
169.44.82.96/27
169.44.84.128/27
169.45.71.32/27
169.45.87.128/27
169.45.169.192/27
169.45.210.64/27
169.45.214.224/27
169.45.219.224/27
169.45.238.32/27
169.45.242.192/26
169.45.248.96/27
169.45.248.160/27
169.47.5.192/26
169.47.6.64/27
169.47.35.32/27
169.47.40.128/27
169.47.42.96/27
169.47.42.160/27
169.47.42.192/26
169.47.130.96/27
169.47.153.128/25
169.47.198.128/27
169.47.212.160/27
169.53.71.224/27
169.53.81.64/27
169.54.51.32/27
169.54.55.192/27
169.54.222.128/27
169.55.60.148/32
169.55.60.170/32
169.55.67.224/27
169.55.69.160/27
169.55.74.32/27
169.55.75.96/27
169.60.75.128/25
169.60.79.0/24
169.60.147.0/24
169.61.101.0/24
169.62.159.16/28
169.63.64.128/28
169.63.73.32/27
169.63.73.64/26
169.63.76.0/25
173.192.162.32/27
173.192.222.160/27
173.193.230.128/27
173.193.239.0/27
174.36.208.128/27
174.36.210.32/27
174.37.243.64/27
179.60.192.49/32
179.60.192.51/32
179.60.193.52/31
179.60.194.53/32
179.60.194.54/32
179.60.195.49/32
179.60.195.51/32
184.173.136.64/27
184.173.147.32/27
184.173.161.64/32
184.173.173.116/32
185.60.216.53/32
185.60.216.54/32
185.60.217.53/32
185.60.217.54/32
185.60.218.53/32
185.60.218.54/32
185.60.219.53/32
185.60.219.54/32
192.155.212.192/27
198.11.193.182/31
198.11.251.32/27
198.23.80.0/27
208.43.115.192/27

**Comment by liliass** [comment]
luci-app-ssr-plus | 176-2
-- | --


还是有问题

**Comment by liliass** [comment]
luci-app-ssr-plus | 176-2
-- | --


还像又没问题了。。。奇怪

**Comment by byvector** [comment]
我也遇到同样的问题。楼主怎么解决的

**Comment by ldsj007** [comment]
最近换了trojan节点，遇到了这问题，之前用V2没有
