### ISSUE TITLE
挂载 SMB/CIFS 网络共享文件夹，共享名不能带空格

### ISSUE THREAD

**Issue by mjyhj** [coolsnowwolf/lede#4227]
![1](https://user-images.githubusercontent.com/22577418/78709025-95229f80-7945-11ea-97b7-1adf152f69c6.png)
![2](https://user-images.githubusercontent.com/22577418/78709040-98b62680-7945-11ea-8aa1-ed5d12ed9d9d.png)
![3](https://user-images.githubusercontent.com/22577418/78709050-9b188080-7945-11ea-9b2c-e1dbc6536526.png)

**Comment by lizhenglin2002** [comment]
请教一下这个功能怎样设置

**Comment by mjyhj** [comment]
> 请教一下这个功能怎样设置
如图所示啊

图1，是小钢炮的SMB共享。设置好后访问N1的IP 192.168.123.254，不就看到我共享的music文件夹吗？

图2，就是填你路由器去访问那个SMB共享的文件夹的参数IP,共享文件夹名，共享服务端的版本，权限，账户名。  再填上要挂载到路由上的什么路径

图3，成功后就出来了

**Comment by lizhenglin2002** [comment]
我想添加电脑的为啥会失败😭

mjyhj <notifications@github.com>于2020年4月10日 周五23:15写道：

**Comment by lizhenglin2002** [comment]
好的，谢谢

发送自 Windows 10 版邮件应用

发件人: mjyhj
发送时间: 2020年4月10日 下午 11:15
收件人: coolsnowwolf/lede
抄送: LEE LIN; Comment
主题: Re: [coolsnowwolf/lede] 挂载 SMB/CIFS 网络共享文件夹，共享名不能带空格 (#4227)

请教一下这个功能怎样设置
如图所示啊
图1，是小钢炮的SMB共享。设置好后访问N1的IP 192.168.123.254，不就看到我共享的music文件夹吗？
图2，就是填你路由器去访问那个SMB共享的文件夹的参数IP,共享文件夹名，共享服务端的版本，权限，账户名。 再填上要挂载到路由上的什么路径
图3，成功后就出来了

**Comment by nbfhscl** [comment]
请问这个功能需要配置哪些组件

**Comment by kitkw** [comment]
挂载win11共享目录不成功............
请我哪里设置不对了（共享目录密码已关闭）？？
![Screenshot 2022-03-27 033423](https://user-images.githubusercontent.com/31963066/160254617-ded34507-a915-4a23-81f2-146875fbd566.jpg)
![Screenshot 2022-03-27 033257](https://user-images.githubusercontent.com/31963066/160254623-b7e43fcb-2fb1-4286-971b-a9304c5e57a2.jpg)
![Screenshot 2022-03-27 033335](https://user-images.githubusercontent.com/31963066/160254627-384debaf-9c42-48d9-bb68-1810c0faeb88.jpg)

**Comment by ocean521** [comment]
> > 请教一下这个功能怎样设置
> > 如图所示啊
> 
> 图1，是小钢炮的SMB共享。设置好后访问N1的IP 192.168.123.254，不就看到我共享的music文件夹吗？
> 
> 图2，就是填你路由器去访问那个SMB共享的文件夹的参数IP,共享文件夹名，共享服务端的版本，权限，账户名。 再填上要挂载到路由上的什么路径
> 
> 图3，成功后就出来了

楼主，我的问题是将NAS的共享文件夹挂载到OP,挂载目录设置的/mnt/xxx，并将之作为下载目录。但实际下载时，却下载到了/overlay/upper/mnt/xxx，没下载到共享文件夹。是哪里的问题啊
