### ISSUE TITLE
请教关于HaProxy编译以及不选Netflix时不能选择除GFW模式外其他模式的问题

### ISSUE THREAD

**Issue by pirately** [coolsnowwolf/lede#4230]
1. 大雕的固件里面虽然自带luci-app-haproxy-tcp，但是haproxy版本很旧。就算不用luci版本，直接用haproxy内核，也是旧的版本，请问除了软件包里面安装，怎么自行编译内核版本的haproxy(即不带luci)进openwrt？比如这个链接：http://git.haproxy.org/git/haproxy-2.1.git/或者https://github.com/openwrt/packages/tree/master/net/haproxy
2. 为啥用Haproxy不管是负载V2Ray或者是Trojan，如果Netflix分流关闭，则只能用GFW模式，绕过大陆以及全局都不能工作。如果选择Netflix节点，则可以正常工作，但是我加黑白名单，好像没什么效果。请问这是什么原因？

**Comment by Pastechn** [comment]
我也遇到了相同的问题，之前一直用的旧版本，昨天编译了新版固件使用 SSRP 之后发现连接 HAProxy 遇到问题，我是加入了 3 个 SSR 作为主节点，之前一直用的同样的配置，一切正常，新版无论怎么配置都用不了，从 HAProxy 后台可以看到是正常连接了3个节点的，通过查询谷歌的 IP 发现其指向了 93.46.8.90 这个地址，说明防污染服务没有正常启动。
后来我又把 Passwall 加入固件，尝试使用其内置的负载均衡，结果正常，其 HAProxy 版本与 SSRP 相同。
