### ISSUE TITLE
树莓派4B wifi无法开启，信道无法更改 

### ISSUE THREAD

**Issue by evangelion015** [coolsnowwolf/lede#4233]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
树莓派4B开启wifi无法搜索到信号，
### (1) 具体问题

A：树莓派4B无法开启wifi，信道无法更改

### (2) 路由器型号和固件版本

A：树莓派4B 固件x64，固件编译日期2020/04/02

### (3) 详细日志

A：
[ 1801.470078] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[ 1803.599140] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 1803.607470] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 1803.612791] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 1803.621485] ieee80211 phy0: brcmf_run_escan: error (-52)
[ 1803.626818] ieee80211 phy0: brcmf_cfg80211_scan: scan error (-52)
[ 1805.324126] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 1828.018221] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[ 1861.204322] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 1898.989808] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[ 1907.123317] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[ 1940.329581] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 1993.769229] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[ 2026.940279] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

B：
[    7.566993] Bridge firewalling registered
[    7.572889] Loading modules backported from Linux version v5.4.27-0-g585e0cc08069
[    7.580379] Backport generated by backports.git v5.4.27-1-0-gf6e8852f
[    7.617487] usbcore: registered new interface driver ums-alauda
[    7.623836] usbcore: registered new interface driver ums-cypress
[    7.630525] usbcore: registered new interface driver ums-datafab
[    7.637031] usbcore: registered new interface driver ums-freecom
[    7.643536] usbcore: registered new interface driver ums-isd200
[    7.650128] usbcore: registered new interface driver ums-jumpshot
[    7.657029] usbcore: registered new interface driver ums-karma
[    7.663591] usbcore: registered new interface driver ums-sddr09
[    7.669898] usbcore: registered new interface driver ums-sddr55
[    7.676242] usbcore: registered new interface driver ums-usbat
[    7.683330] usbcore: registered new interface driver usbhid
[    7.688901] usbhid: USB HID core driver
[    7.703078] xt_time: kernel timezone is -0000
[    7.725789] PPP generic driver version 2.4.2
[    7.730919] PPP MPPE Compression module registered
[    7.736781] NET: Registered protocol family 24
[    7.754209] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    7.987856] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    8.006467] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Nov 13 2019 04:39:05 version 7.45.198 (r723338 CY) FWID 01-369a6798
[    8.046290] usbcore: registered new interface driver brcmfmac
[    8.054817] kmodloader: done loading kernel modules from /etc/modules.d/*
[    9.943764] bcmgenet: Skipping UMAC reset
[    9.949098] bcmgenet fd580000.genet: configuring instance for external RGMII (no delay)
[    9.959448] br-lan: port 1(eth0) entered blocking state
[    9.964783] br-lan: port 1(eth0) entered disabled state
[    9.970171] device eth0 entered promiscuous mode
[    9.975594] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   11.031559] bcmgenet fd580000.genet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   11.039556] br-lan: port 1(eth0) entered blocking state
[   11.044821] br-lan: port 1(eth0) entered forwarding state
[   11.050837] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   11.134401] netlink: 4 bytes leftover after parsing attributes in process `iw'.
[   13.354376] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   13.361423] br-lan: port 2(wlan0) entered blocking state
[   13.366741] br-lan: port 2(wlan0) entered disabled state
[   13.372422] device wlan0 entered promiscuous mode
[   15.678576] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
[   17.352404] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=55447, -52
[   23.354949] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=55447, -52
[   29.375310] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=55447, -52
[   35.399498] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=55447, -52

**Comment by AmadeusGhost** [comment]
最新源码编译下试试
