### ISSUE TITLE
flowoffload删掉了么?

### ISSUE THREAD

**Issue by hceasy** [coolsnowwolf/lede#4234]
flowoffload这个包被删掉了么?make menuconfig 中找不到了
* [X] 没有类似的issue

**Comment by Lrvineshaw** [comment]
没啊~今天编译还在

**Comment by hceasy** [comment]
![微信截图_20200408184859](https://user-images.githubusercontent.com/4436382/78783838-da42e200-79d6-11ea-8eaa-468f28ccf51c.png)
真是找不到了 feeds update & install 都执行了.

**Comment by hceasy** [comment]
git pull 之后找到了...尴尬

**Comment by Promix953** [comment]
4.9内核是sfe，4.19是flowoffload

**Comment by hceasy** [comment]
> 
> 
> 4.9内核是sfe，4.19是flowoffload

主要还是没拉新代码的问题
