### ISSUE TITLE
ASUS RT-ACRH17 5GWIFI内核频繁报错

### ISSUE THREAD

**Issue by CantonSing** [coolsnowwolf/lede#4235]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Qualcomm Atheros QCA9984型号 5GWIFI内核频繁报错

### (2) 路由器型号和固件版本

A：ASUS RT-ACRH17 OpenWrt 20.4.8

### (3) 详细日志

A：
[  369.270835] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode
[  369.279014] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode
[  369.287156] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode
[  380.348582] ath10k_ahb a000000.wifi: Invalid VHT mcs 15 peer stats
[  726.311393] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode
[  726.311441] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode
[  726.318562] ath10k_pci 0000:01:00.0: received unexpected tx_fetch_ind event: in push mode

B：
[ 2165.275427] ------------[ cut here ]------------
[ 2165.275597] WARNING: CPU: 2 PID: 0 at target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx/ath10k-ct-regular/ath10k-ct-2020-03-25-3d173a47/ath10k-5.4/txrx.c:134 ath10k_txrx_tx_unref+0x52c/0x6f4 [ath10k_core]
[ 2165.279157] Invalid VHT rate, nss: 3  hw_rate: 15 ratecode: 255
[ 2165.297655] Modules linked in: xt_FULLCONENAT pppoe ppp_async ath10k_pci ath10k_core ath pppox ppp_mppe ppp_generic nf_nat_pptp nf_conntrack_pptp mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_socket xt_recent xt_policy xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_esp xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TPROXY xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_FLOWOFFLOAD xt_DSCP xt_CT xt_CLASSIFY usblp ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm slhc nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_proto_gre nf_nat_irc nf_nat_ipv4
[ 2165.352486]  nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast ts_kmp nf_conntrack_amanda nf_conncount macvlan iptable_raw iptable_mangle iptable_filter ipt_ah ipt_ECN ip_tables hwmon crc_ccitt compat asn1_decoder fuse sch_cake tcp_bbr sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred cryptodev xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark
[ 2165.424190]  ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6table_nat ip6t_NPT ip6t_MASQUERADE nf_nat_ipv6 nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 ifb sit xfrm6_mode_tunnel xfrm6_mode_transport xfrm6_mode_beet ipcomp6 xfrm6_tunnel esp6 ah6 xfrm4_tunnel xfrm4_mode_tunnel xfrm4_mode_transport xfrm4_mode_beet ipcomp esp4 ah4 tunnel6 tunnel4 ip_tunnel tun snd_rawmidi snd_seq_device snd_pcm_oss snd_pcm snd_timer snd_mixer_oss snd_hwdep snd_compress snd soundcore xfrm_user xfrm_ipcomp af_key xfrm_algo vfat fat cifs nls_utf8 nls_iso8859_1 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha1_generic sha1_arm_neon sha1_arm
[ 2165.495061]  jitterentropy_rng drbg md5 md4 hmac echainiv ecb des_generic cbc authenc arc4 uas usb_storage leds_gpio xhci_plat_hcd xhci_pci xhci_hcd dwc3 dwc3_qcom sd_mod scsi_mod gpio_button_hotplug ext4 mbcache jbd2 exfat crc32c_generic
[ 2165.517321] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 4.19.108 #0
[ 2165.538163] Hardware name: Generic DT based system
[ 2165.544377] [<c030e2a4>] (unwind_backtrace) from [<c030acf8>] (show_stack+0x10/0x14)
[ 2165.549047] [<c030acf8>] (show_stack) from [<c07af514>] (dump_stack+0x94/0xa8)
[ 2165.556944] [<c07af514>] (dump_stack) from [<c031ffd4>] (__warn+0xd4/0xf0)
[ 2165.563969] [<c031ffd4>] (__warn) from [<c0320028>] (warn_slowpath_fmt+0x38/0x48)
[ 2165.571072] [<c0320028>] (warn_slowpath_fmt) from [<bfa4b578>] (ath10k_txrx_tx_unref+0x52c/0x6f4 [ath10k_core])
[ 2165.578947] [<bfa4b578>] (ath10k_txrx_tx_unref [ath10k_core]) from [<bfa44dd4>] (ath10k_htt_t2h_msg_handler+0x70c/0x11a0 [ath10k_core])
[ 2165.588525] [<bfa44dd4>] (ath10k_htt_t2h_msg_handler [ath10k_core]) from [<bfa9afe0>] (ath10k_pci_htt_rx_cb+0x1c8/0x218 [ath10k_pci])
[ 2165.600834] [<bfa9afe0>] (ath10k_pci_htt_rx_cb [ath10k_pci]) from [<bfa63778>] (ath10k_ce_per_engine_service+0x80/0xd8 [ath10k_core])
[ 2165.612974] [<bfa63778>] (ath10k_ce_per_engine_service [ath10k_core]) from [<bfa6383c>] (ath10k_ce_per_engine_service_any+0x6c/0x98 [ath10k_core])
[ 2165.624801] [<bfa6383c>] (ath10k_ce_per_engine_service_any [ath10k_core]) from [<bfa9cd60>] (ath10k_pci_napi_poll+0x9c/0x13c [ath10k_pci])
[ 2165.637632] [<bfa9cd60>] (ath10k_pci_napi_poll [ath10k_pci]) from [<c069b454>] (net_rx_action+0x138/0x2fc)
[ 2165.650013] [<c069b454>] (net_rx_action) from [<c03021c8>] (__do_softirq+0xe0/0x268)
[ 2165.659642] [<c03021c8>] (__do_softirq) from [<c0324120>] (irq_exit+0x9c/0xfc)
[ 2165.667532] [<c0324120>] (irq_exit) from [<c036394c>] (__handle_domain_irq+0x9c/0xac)
[ 2165.674569] [<c036394c>] (__handle_domain_irq) from [<c0538f90>] (gic_handle_irq+0x5c/0x90)
[ 2165.682466] [<c0538f90>] (gic_handle_irq) from [<c0301a0c>] (__irq_svc+0x6c/0x90)
[ 2165.690600] Exception stack(0xcf863f68 to 0xcf863fb0)
[ 2165.698254] 3f60:                   00000000 00cb404c cfd932c4 c0313b60 ffffe000 c0b04c6c
[ 2165.703297] 3f80: 00000004 c0b04cac c0a40da8 00000000 00000000 00000000 0f354000 cf863fb8
[ 2165.711445] 3fa0: c03082f4 c03082f8 60000013 ffffffff
[ 2165.719621] [<c0301a0c>] (__irq_svc) from [<c03082f8>] (arch_cpu_idle+0x34/0x38)
[ 2165.724659] [<c03082f8>] (arch_cpu_idle) from [<c0345d84>] (do_idle+0xf0/0x200)
[ 2165.732117] [<c0345d84>] (do_idle) from [<c03460f0>] (cpu_startup_entry+0x18/0x20)
[ 2165.739144] [<c03460f0>] (cpu_startup_entry) from [<803023ec>] (0x803023ec)
[ 2165.746839] ---[ end trace 672704852b483514 ]---

C：
[ 2165.758662] ath10k_ahb a000000.wifi: SWBA overrun on vdev 1, skipped old beacon
[ 2165.758815] ath10k_ahb a000000.wifi: SWBA overrun on vdev 0, skipped old beacon
[ 2165.765719] ath10k_ahb a000000.wifi: SWBA overrun on vdev 1, skipped old beacon

**Comment by LeeMenHin** [comment]
??
