### ISSUE TITLE
最新版本ssr路由器重启之后，没有启用，需要再次点击保存&应用

### ISSUE THREAD

**Issue by xzchsia** [coolsnowwolf/lede#424]
路由器添加了每日自动重启维护，reboot之后web页面显示 《ShadowsocksR Pro 运行中》 但是实际没有在启用，重新点击下保存&应用后，就正常了，不知是否正常，最新的Powered by LuCI Master (git-18.138.53009-80cb4fe) / OpenWrt R7.7.2 By Lean版本

**Comment by coolsnowwolf** [comment]
这个是由于你的 ssr 服务器用的是域名，刚重启完你的 pppoe 如果拨号 pppoe的速度比较慢，导致域名还没有解释成为 ip，就会导致 iptables 规则没有建立起来，自然不能科学上网

但其实当拨号拨上了，域名解析为 ip 后几十秒内，这个规则就会自动被建立，也无需人工点击，所以无需在意

**Comment by xzchsia** [comment]
好的，谢谢。
