### ISSUE TITLE
一觉起来，是不是更新规则更新出问题了

### ISSUE THREAD

**Issue by muziling** [coolsnowwolf/lede#4240]
ssr-rules[22142]: Start failed!
ipset v7.1: Error in line 1084: Syntax error: cannot parse 45.114.51.0.1.0: resolving to IPv4 address failed
2020-04-09 02:02:47 更新成功！ 新的总纪录数：9555
2020-04-09 02:00:04 正在更新【国内IP段】数据库
2020-04-09 02:00:04 你已经是最新数据，无需更新！
2020-04-09 02:00:00 正在更新【GFW列表】数据库

梯子是正常的，但路由翻就是不行，看了下日志报这个错。哎

**Comment by muziling** [comment]
china_ssr.txt  就是这个文件自动更新出问题了 ....

**Comment by dolphinpaopao** [comment]
正常，未出现这个问题，自动更新时间设置为白天下午时段试试。

**Comment by EstFoxs** [comment]
你们的v2节点能启动？不到4小时前编译的
