### ISSUE TITLE
CPU核心/线程数问题 ESXi 6.5 X5680

### ISSUE THREAD

**Issue by rshi0212** [coolsnowwolf/lede#4242]
系统：ESXi 6.5
CPU：X5680 6核 12线程 3.33GHz

在虚拟机中选择12线程，但是固件内只显示”1 Core 8 Thread“
虽然性能已经过剩，不知道是显示问题还是实际只用了1核8线程

同样在i7 7500U的工控机里，固件显示是正确的

**Comment by coolsnowwolf** [comment]
Intel CPU 因为漏洞补丁缘故，只能支持 8核 or 8线程

用 AMD Ryzen 即可最多 128线程

**Comment by rshi0212** [comment]
> Intel CPU 因为漏洞补丁缘故，只能支持 8核 or 8线程
> 
> 用 AMD Ryzen 即可最多 128线程

所以不是显示错误，是实际只能用到显示的性能是嘛？

**Comment by rshi0212** [comment]
最新编译的固件 CPU的评分消失了

**Comment by virusflorent** [comment]
> Intel CPU 因为漏洞补丁缘故，只能支持 8核 or 8线程
> 
> 用 AMD Ryzen 即可最多 128线程

L大，请问一下固件内能不能在intel处理器上强行开启超过8线程的支持呢，是在编译时候开还是？
