### ISSUE TITLE
[R20.4.8]LAN接口设置DNS为局域网自建DNS服务后会造成大量垃圾请求

### ISSUE THREAD

**Issue by rhettor** [coolsnowwolf/lede#4244]
系统：ESXi 6.7u3
CPU：Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz : 1 Core 2 Thread
固件版本：OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)
场景：lede作为网关（10.10.10.252），局域网DNS服务（10.10.10.240）

当LAN接口设置自定义DNS为局域网自建DNS服务后会造成大量垃圾请求，dnsmasq的CPU使用率至少在20%以上，甚至会达到99%，但是在自定义DNS设置为公共DNS则不会出现相应问题。

截图1：
[dnsmasq CPU使用率](https://i.loli.net/2020/04/09/9oSEGlhyzpfsHYq.png)
截图2:
[dns请求记录](https://i.loli.net/2020/04/09/BXhYpeV4mqfDcNd.png)
截图3:
[dns请求域名](https://i.loli.net/2020/04/09/FCfKjYnXRJVIc1z.png)

**Comment by Promix953** [comment]
```
|-->lede防火墙将dns请求拦截转发到本机53端口，本机将dns请求发到240，240发送dns请求-->|
^                                                                              v
|--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<--|
```

**Comment by coolsnowwolf** [comment]
因为不是这么玩的，自环了

**Comment by rhettor** [comment]
@coolsnowwolf 但是240并没把252设置为网关，他们的网关都是主路由251

**Comment by 1049066154** [comment]
你是不是在240机器上设置了上游dns为10.10.10.240?

**Comment by rhettor** [comment]
@1049066154 上游是公共dns

**Comment by 1049066154** [comment]
> @1049066154 上游是公共dns
你网络中负责DHCP的那台机器中配置的下发DNS是哪个IP?

**Comment by 1049066154** [comment]
> @1049066154 上游是公共dns

你描述一下你网络中各个设备的连接配置吧

**Comment by rhettor** [comment]
> > @1049066154 上游是公共dns
> 
> 你描述一下你网络中各个设备的连接配置吧

![网络拓扑图](https://i.loli.net/2020/04/12/DoGx9Wm8MXUasET.png)

**Comment by Promix953** [comment]
[https://www.google.com/search?q=lb._dns-sd._udp](url)

**Comment by 1049066154** [comment]
> > > @1049066154 上游是公共dns
> > 
> > 
> > 你描述一下你网络中各个设备的连接配置吧
> 
> ![网络拓扑图](https://camo.githubusercontent.com/aa95192dd46765463a6ded498caf00480793db14/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31322f446f477839576d384d5855617345542e706e67)

![批注 2020-04-12 205827](https://user-images.githubusercontent.com/46583730/79069447-d11c8280-7d00-11ea-9753-300a90a58c6c.jpg)
你这里不能设置127.0.0.1,上游服务器是自己的ip这样就死循环了,而且你的dns程序应该没有完全接管53端口,导致dnsmasq这类自带的服务会使用接口上配置的127.0.0.1,但是接受到请求的还是dnsmasq,然后就陷入死循环

**Comment by hue715** [comment]
> > > @1049066154 上游是公共dns
> > 
> > 
> > 你描述一下你网络中各个设备的连接配置吧
> 
> ![网络拓扑图](https://camo.githubusercontent.com/aa95192dd46765463a6ded498caf00480793db14/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f31322f446f477839576d384d5855617345542e706e67)

试试把Lede防火墙规则中的iptables重定向注释掉
<img width="722" alt="截屏2020-04-19 上午9 27 04" src="https://user-images.githubusercontent.com/22958922/79677096-0dc80c80-8220-11ea-8642-06fc505d1c42.png">
