### ISSUE TITLE
v2ray server跟ssr plus+兼容性问题

### ISSUE THREAD

**Issue by flhs0606** [coolsnowwolf/lede#4245]
我v2ray server跟ssr plus+同时正常开着，每次修改ssr plus+的配置并保存应用后，v2ray server的状态都会打叉，需要重启v2ray server。不知各位有无遇到这种情况？
Thu Apr  9 19:53:35 2020 daemon.warn pdnsd[8800]: Caught signal 15. Exiting.
Thu Apr  9 19:53:35 2020 daemon.info dnsmasq[8897]: exiting on receipt of SIGTERM
Thu Apr  9 19:53:36 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Apr  9 19:53:36 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: started, version 2.80 cachesize 150
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: DNS service limited to local subnets
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC loop-detect inotify dumpfile
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain test
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain onion
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain localhost
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain local
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain invalid
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain bind
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using nameserver 127.0.0.1#5333
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain lan
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: reading /tmp/resolv.conf.auto
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain test
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain onion
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain localhost
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain local
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain invalid
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain bind
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using nameserver 127.0.0.1#5333
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using local addresses only for domain lan
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using nameserver 119.29.29.29#53
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: using nameserver 240e:1f:1::1#53
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: read /etc/hosts - 4 addresses
Thu Apr  9 19:53:36 2020 daemon.info dnsmasq[25067]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:53:36 2020 cron.info crond[25094]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:53:37 2020 daemon.info pdnsd[25354]: pdnsd-1.2.9b-par starting.
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25067]: exiting on receipt of SIGTERM
Thu Apr  9 19:53:37 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Apr  9 19:53:37 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: started, version 2.80 cachesize 150
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: DNS service limited to local subnets
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack ipset no-auth no-DNSSEC loop-detect inotify dumpfile
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain test
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain onion
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain localhost
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain local
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain invalid
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain bind
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5335 for domain mikrotik.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5335 for domain whoer.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbo.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbogo.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbonow.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain huluim.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hulu.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxext.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxso.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxvideo.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflximg.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain netflix.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain netflix.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain yunjiasu-cdn.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain xgslb.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wsngb.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wscdns.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain webluker.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wangsu.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain tlgslb.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain tcdn.qq.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain sz-dns.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain speedupchina.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain speedupchina.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qiniudns.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qiniudn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qingcdn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qcloud.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qbox.me
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain ourwebcdn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using 5433 more nameservers
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: reading /tmp/resolv.conf.auto
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain test
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain onion
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain localhost
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain local
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain invalid
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using local addresses only for domain bind
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5335 for domain mikrotik.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5335 for domain whoer.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbo.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbogo.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hbonow.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain huluim.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain hulu.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxext.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxso.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflxvideo.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain nflximg.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain netflix.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 127.0.0.1#5555 for domain netflix.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain yunjiasu-cdn.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain xgslb.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wsngb.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wscdns.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain webluker.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain wangsu.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain tlgslb.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain tcdn.qq.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain sz-dns.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain speedupchina.net
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain speedupchina.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qiniudns.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qiniudn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qingcdn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qcloud.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain qbox.me
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using nameserver 119.29.29.29#53 for domain ourwebcdn.com
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: using 5435 more nameservers
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:53:37 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses

以上是在ssr plus+点应用的日志，以下是我接着重新把v2ray server开起来的日志。

Thu Apr  9 19:55:23 2020 cron.info crond[26612]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:23 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:23 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:24 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:24 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:24 2020 cron.info crond[26980]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:24 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:24 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:24 2020 cron.info crond[27089]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:25 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:25 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:26 2020 cron.info crond[27360]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:26 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:26 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:27 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:27 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:27 2020 cron.info crond[27743]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:27 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:27 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Thu Apr  9 19:55:27 2020 cron.info crond[27889]: crond (busybox 1.30.0) started, log level 5
Thu Apr  9 19:55:28 2020 daemon.info dnsmasq[25459]: read /etc/hosts - 4 addresses
Thu Apr  9 19:55:28 2020 daemon.info dnsmasq[25459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses

**Comment by EnnawYang** [comment]
没遇到过

**Comment by guochan2019** [comment]
x86，无此情况

**Comment by flhs0606** [comment]
> x86，无此情况

我也是x86，日志也没显示报错，奇怪了。

**Comment by flhs0606** [comment]
把系统日志贴出来了

**Comment by lhy0838** [comment]
R1s-H5，同状况
