### ISSUE TITLE
20.4.8固件的openclash打不开

### ISSUE THREAD

**Issue by mofond** [coolsnowwolf/lede#4247]
日志
/etc/rc.common: line 752: nohup: not found
2020-04-09 18:49:50 OpenClash Can Not Start, Please Check The Error Info And Try Again

请问怎么解决？

**Comment by dolphinpaopao** [comment]
这个不是自带的吧？别人编译的第三方？

**Comment by mofond** [comment]
插件是op通用的，其他编译的固件正常使用，这版订阅配置文件也不能订阅，只能上传，目前发现这两个问题

**Comment by hxlls** [comment]
走错门了，请找插件作者

**Comment by mofond** [comment]
解决了，缺个依赖，刚入门git，见谅了。

**Comment by hyird** [comment]
issue 自己关了呗
