### ISSUE TITLE
MiniDLNA速度慢

### ISSUE THREAD

**Issue by NorwayLuo** [coolsnowwolf/lede#4248]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：Linksys EA8500上接了一个500G的SATA硬盘用来存电影，无论是SMB或MiniDLNA的方式，看电影时的下截速度只有2M，导至高清电影看不了，非常卡，用的播放器是Kodi，但是上传电影到路由器上的硬盘速度可以达到30MB每秒，请问是方案不对，还是配置不对，是否有更好的方案？
谢谢。

**Comment by 9l** [comment]
视频转码效率太低吧

**Comment by NorwayLuo** [comment]
有什么好的方法可以解决这个问题吗？
