### ISSUE TITLE
R7.7.2  K3   WiFi无线未开启或未关联

### ISSUE THREAD

**Issue by ZGNCZMY** [coolsnowwolf/lede#426]
编译时已勾选K3WiFi包，从R7.7刷完机恢复出厂无线菜单消失
- 
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2048384/default.txt)

[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2048398/default.txt)

**Comment by mrclock** [comment]
我也是这个问题，昨天取最新的文件，重新编译了一个版本。先把 etc\config\wireless  删除了，然后更新固件保留配置的。

重新启动后就有openwrt的wifi信号了。后续再改下无线配置就行了。你试试看。

**Comment by ZGNCZMY** [comment]
> 
> 
> 我也是这个问题，昨天取最新的文件，重新编译了一个版本。先把 etc\config\wireless 删除了，然后更新固件保留配置的。
> 
> 重新启动后就有openwrt的wifi信号了。后续再改下无线配置就行了。你试试看。

谢谢
