### ISSUE TITLE
ttyd选中后编译失败

### ISSUE THREAD

**Issue by lonelysoul** [coolsnowwolf/lede#4261]
观察发现，默认下：
libwebsockets-openssl（选中，编译）
libwebsockets-full（默认没有选中，不编译）

经逐个luci-app选中后查看config文件发现：在选中ttyd后，libwebsockets-full被选中；
编译过程中，两个组件冲突，编译失败；

在make menuconfig中取消选中ttyd，libwebsockets-full的未恢复到不选中状态，编译仍然失败；

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/78964647-7b43b100-7b2d-11ea-97ae-49c0de374e1f.png)
没问题
