### ISSUE TITLE
Lan口半双工10Mb/s，请问正常吗？

### ISSUE THREAD

**Issue by xuhaojia** [coolsnowwolf/lede#4268]
AutoBuild编译的最新固件，用作旁路由使用，接口为半双工10Mb/s，使用过程无异常，但就不明白为啥为10Mb/s，正常情况应该是全双工1G/s呀！

![bandicam 2020-04-11 13-30-19-536](https://user-images.githubusercontent.com/33852798/79036293-7f3d0500-7bf9-11ea-9158-eb48f6ae1975.jpg)
![bandicam 2020-04-11 13-28-26-992](https://user-images.githubusercontent.com/33852798/79036296-849a4f80-7bf9-11ea-9c10-e88db42b30c3.jpg)
![bandicam 2020-04-11 13-29-48-014](https://user-images.githubusercontent.com/33852798/79036298-87954000-7bf9-11ea-976b-3211d5e0b920.jpg)

**Comment by coolsnowwolf** [comment]
虚拟机无需理会这个

**Comment by xuhaojia** [comment]
> 虚拟机无需理会这个

好的，明白了！
