### ISSUE TITLE
SSR+Plus 节点过滤

### ISSUE THREAD

**Issue by shao222** [coolsnowwolf/lede#4273]
昨晚编译了最新的固件版本
```Powered by LuCI Master (git-20.088.29068-cebe120) / OpenWrt R20.4.8```
节点可以通过关键词过滤.
但不知有什么方法可以反向操作, 也就是订阅符合关键词的节点?

谢谢!

**Comment by liubangjain** [comment]
哈哈，我正想要这个功能，刚要来提这个建议。大雕大佬，例如订阅里有香港BGP、香港CN2、美国BGP、美国CN2等节点，虽然可通过过滤来去掉不想要的节点，但是如果能有筛选功能可能更加简单，例如筛选含BGP关键字的节点，这样就方便很多了，也的功能不怕更新订阅时机场添加了其他节点而过滤关键字功能又失效。希望添加筛选功能，筛选和过滤组合使用，谢谢。
