### ISSUE TITLE
Luci的一个小Bug

### ISSUE THREAD

**Issue by a13547** [coolsnowwolf/lede#4277]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Luci界面任一插件，包括系统自带软件，当点击“保存&应用”按钮后立刻刷新页面，仍然相当于点击一次“保存&应用”按钮。根据页面出现的提示文字，显示插件正在保存其设置，和点击按钮的的行为一样。

### (2) 路由器型号和固件版本

A：x86_64 r20.4.8

### (3) 详细日志

A：无

**Comment by 1049066154** [comment]
点击保存应用的时候页面会有一个提交的请求,当页面被刷新的时候这个提交请求也会被重新执行,这个不是BUG
