### ISSUE TITLE
udpxy 自带的启动脚本是不是有问题？

### ISSUE THREAD

**Issue by zhongyb** [coolsnowwolf/lede#4284]
最近搞iptv内网的融合，编译了x86_64的固件，但在luci-app-udpxy网页中勾选启用，并填写相关信息后，udpxy不能启动。通过ssh连接路由器后，通过命令 /etc/init.d/udpxy start 也不能启动，也没有任何相关的信息显示出来。通过命令/usr/bin/udpxy -a br-lan -p 4022 -m eth2可正常启动，软件功能也正常。现在怀疑自带的启动脚本有问题，也打开过/etc/init.d/udpxy这个文件，可能本人水平有限，没有发现哪儿有问题。通过搜索，发现其他人也出现过此类问题。现在临时的解决办法就是在/etc/rc.local 手动添加上面的命令。

**Comment by azazjjyjjy** [comment]
我也碰到了同样的问题

**Comment by zhongyb** [comment]
经过多次实验，发现只要勾选详细这个选项，udpxy就不能启动，但去掉这个选项后，一切恢复正常。
