### ISSUE TITLE
ssr设置强制走代理的域名后会导致gfw列表模式无法使用

### ISSUE THREAD

**Issue by zeruns** [coolsnowwolf/lede#4286]
在设置强制走代理的域名后，gfw列表模式无法访问Google，其他模式正常，重启路由器后gfw列表模式恢复正常。
路由器：newifi3
固件为最新编译的

**Comment by hcym** [comment]
那就重启，x86和n1随便折腾，可能性能不够了导致老年痴呆症

**Comment by guochan2019** [comment]
并没有
