### ISSUE TITLE
網易雲音樂可否加入youtube音源

### ISSUE THREAD

**Issue by kai456789** [coolsnowwolf/lede#4287]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：網易雲解鎖 裡面沒有YT音源的選項 可否加入跟自定義cookie

### (2) 路由器型号和固件版本

A：ACRH17

### (3) 详细日志

A：

**Comment by yonggedebaqi** [comment]
直接編譯 YouTube-DL 就可以解析 mp4 m4a

**Comment by kai456789** [comment]
> 直接編譯 YouTube-DL 就可以解析 mp4 m4a

網易雲有YT音源可選的 不是要下載 只是LEAN的LUCI沒寫進去

**Comment by lizhenglin2002** [comment]
> > 直接編譯 YouTube-DL 就可以解析 mp4 m4a
> 
> 網易雲有YT音源可選的 不是要下載 只是LEAN的LUCI沒寫進去

居然还有yt的选项，一直以为没有

**Comment by mjyhj** [comment]
好的

**Comment by kai456789** [comment]
> 好的

感謝 先關閉了
