### ISSUE TITLE
新插件CIFS无法访问，麻烦看下设置的是否正确。

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#4291]
之前用的Samba4，今天更新系统选了luci-app-cifs-mount，重启后也无法挂载，设置截图如下，有知道的帮忙看下，设置是否正确。

![01](https://user-images.githubusercontent.com/49992475/79068712-88ae9600-7cfb-11ea-9593-606b1078a6b5.jpg)

**Comment by EnnawYang** [comment]
这软件是用来挂载远程共享目录的，不是用来共享本机文件的

**Comment by jy3344511** [comment]
> 这软件是用来挂载远程共享目录的，不是用来共享本机文件的

可以将 SMB/CIFS的共享文件夹挂载到本地，这句话是指远程挂载家里软路由上设置的共享文件夹吗？

**Comment by Promix953** [comment]
> > 这软件是用来挂载远程共享目录的，不是用来共享本机文件的
> 
> 可以将 SMB/CIFS的共享文件夹挂载到本地，这句话是指远程挂载家里软路由上设置的共享文件夹吗？

挂载 _**别的机器**_ 的SMB共享出来的文件夹到  _**装了这个系统的这台机器**_ ，不是让你挂载 _**装了这个系统的这台机器**_ 的硬盘上的文件夹！
