### ISSUE TITLE
请问如何修改gfwlist，我想限制网内用户只用SSR访问几个特定的国外网站

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4294]
比如，我只想让网内用户访问twitter.com，其余任何网站都不让其通过SSR访问。用“不走代理的域名”可以实现控制，但是那样我得往里面添加成千上网的网站。

我想如果能直接修改gfwlist，并且关掉自动更新，是不是实现起来简单些。

我找到一个gfwlist.conf，修改了以后试了一下，不起作用。

可能我没找到文件。

请问要如何修改GFWLIST呢

**Comment by Joe-Zhang** [comment]
你该不是网评员吧？这要求太可疑了！

**Comment by kr513268** [comment]
> 你该不是网评员吧？这要求太可疑了！

没毛病，莫名的像网评员

**Comment by nyigt502** [comment]
网飞分流就可以实现了，把默认的网飞分流域名全删了

**Comment by huifukejian** [comment]
自动更新里面有个默认值的， 改的方式很多， 简单点修改文件 /etc/init.d/shadowsocksr 
注释掉下面2行  大概 707行
# cp -rf /etc/ssr/gfw_list.conf /tmp/dnsmasq.ssr/ （这个文件是订阅的gfwlist）   
# cp -rf /etc/ssr/gfw_base.conf /tmp/dnsmasq.ssr/ （这个文件是固件自带的一些域名）   
再到ssrplus+ 把想要代理的域名填到强制走代理的域名里面， 你的需求就达到了
