### ISSUE TITLE
订阅节点重复

### ISSUE THREAD

**Issue by dl250** [coolsnowwolf/lede#4296]
订阅节点出现重复现象，总共37个节点，每点一次订阅他就会多几个重复节点，
![Screenshot_20200413-061133](https://user-images.githubusercontent.com/51826790/79081292-a838c500-7ce1-11ea-983d-7fd70ead6a0a.png)
![Screenshot_20200413-061804](https://user-images.githubusercontent.com/51826790/79081295-af5fd300-7ce1-11ea-9573-3ca9ae069732.png)
![Screenshot_20200413-061041](https://user-images.githubusercontent.com/51826790/79081298-b38bf080-7ce1-11ea-9f7f-82119d7e5714.png)

**Comment by chinassr** [comment]
只有订阅里有一个节点，群组名不一样就会出现重复节点，我用别的科学上网插件，没有这个问题

**Comment by chinassr** [comment]
我把所有节点群组名改成一样还是重复
![Screenshot_20200413-070855](https://user-images.githubusercontent.com/51826790/79082073-a58d9e00-7ce8-11ea-8143-2dab5b5dd323.png)

**Comment by chinassr** [comment]
用其他插件并没有出现重复节点的情况

**Comment by coolsnowwolf** [comment]
这个问机场了，机场的订阅端输出的顺序每次都不同

例如第一次为 server = xx ，port =yy

第二次为 port =yy, server =xx 

这样就是两个不同的节点了
