### ISSUE TITLE
建议整合RK3328平台

### ISSUE THREAD

**Issue by Sinmists** [coolsnowwolf/lede#4298]
最近看到Nanopi R2S开发板很适合以低成本搭建物联网和软路由，在`https://github.com/friendlyarm/friendlywrt`看到了RK3328平台源代码，请问是否能够整合RK3328平台？

**Comment by Xr267** [comment]
同感，期待整合，这样就不用自己拼凑代码了

**Comment by hxlls** [comment]
大雕都说过了，SDK不一样，之前的issue 都有过，自己搜索就行了，何必又单独开一个issue?

**Comment by fanck0605** [comment]
凑好的 [https://github.com/fanck0605/friendlywrt](https://github.com/fanck0605/friendlywrt)
