### ISSUE TITLE
减少插件也不会减少固件体积，再次编译求解

### ISSUE THREAD

**Issue by Qiyue0726** [coolsnowwolf/lede#4305]
第一次编译选了很多插件，导致编译的包太大，然后尝试删除tmp文件夹和config文件，重新配置，减少插件，可就算减少到默认，编译出来的固件都会和第一次的差不多大。
后面只能通过删除bin文件夹和build_dir文件夹，但是由于文件太多，删除就得等上大半天，然后再次编译由于又要生成这些东西又得等大半天，一天就过去了。
不知道我的操作有问题还是只能这样，希望有大佬解答下。

**Comment by DongfeiSay** [comment]
make clean

**Comment by Qiyue0726** [comment]
> make clean

原来还有这个命令，谢谢大佬
