### ISSUE TITLE
请问固件是否支持移远ec20 R2.1 4G模块

### ISSUE THREAD

**Issue by CMCCAdmin** [coolsnowwolf/lede#4306]
请问固件是否支持移远ec20 R2.1 4G模块，支持和的话编译时需要选上那些软件包呢？谢谢。

**Comment by CMCCAdmin** [comment]
搞定了

**Comment by kongmeng8888** [comment]
你好 请问你这是怎么解决4G模块的，我最近需要用到这个，请教你一下！

**Comment by CMCCAdmin** [comment]
https://www.jianshu.com/p/0951be9aa200?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation
大致按照这个重新编译openwrt，内核添加代码部分不用做，因为新内核已经有了，让后在选上luci-proto-qmi就可以，用qmi拨号。

**Comment by caozhengi** [comment]
> https://www.jianshu.com/p/0951be9aa200?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation 大致按照这个重新编译openwrt，内核添加代码部分不用做，因为新内核已经有了，让后在选上luci-proto-qmi就可以，用qmi拨号。

这个教程看起来走的是3G拨号?  性能更好更稳定的是不是应该走QMI方式拨号
