### ISSUE TITLE
谈谈大雕的固件使用感受

### ISSUE THREAD

**Issue by guwang139** [coolsnowwolf/lede#4316]
先说感觉：真特么爽！

经历，自从入手newifi3后一直在寻觅固件（记得上一次还是H618那个年代）。左挑右试感觉潘多拉最值得尝试。19年3月刷了r1812那版。zerotier很好用，usb读写很强，usb2.0移动硬盘读写30MB。usb3能达到70MB帅呆了。ss也能用，但ss总是gfw墙一封就是一个月。换成了v2ray https后稳的一批。。最近刷了R20.3.8版本，卧槽zertier重拨uuid会变的bug修复了。。真好！

感受：固件很好用，特别有ipk的源。真特么爱死它了。装个rsync 备份美滋滋啊。。大部分软件都能找到。什么useradd的包后smb权限控制的更精细的。。。很爽有没有。。。。这种与主流linux系统用法一样的系统真的很爽。不行的地方看看日志，自己调一调配一配。ipk又比较全大爱！

注意点：
1、smb服务重启后所有文件权限变成777属组root 。
2、zerotier 、 v2ray 、 HWNAT之间有影响（HWNAT、zerotier开了后v2ray 能运行但不能爬墙；只开HWNAT，zerotier都正常；只开zerotier 、 v2ray 也正常）。反正宽带没有1G，HWNAT关闭后zerotier 、 v2ray正常，很爽哈哈。

**Comment by hcym** [comment]
确实如此😁，感谢

**Comment by lloyd18** [comment]
关了吧，要是想感谢源码页有二维码
