### ISSUE TITLE
能否加入kmod-mt76x02-usb驱动，官方是支持的吧

### ISSUE THREAD

**Issue by imjunfeng** [coolsnowwolf/lede#4322]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
树莓派4b，编译的时候找不到kmod-mt76x02-usb，想后装又装不上
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：树莓派4b，OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
![mt76](https://user-images.githubusercontent.com/42570690/79286427-1f917300-7ef3-11ea-9084-d941d2331add.png)
是有的，`make menuconfig`用/搜索

**Comment by imjunfeng** [comment]
搜到后怎么添加进去

**Comment by coolsnowwolf** [comment]
HIDDEN :=1 去掉

**Comment by imjunfeng** [comment]
谢谢大神加进去，树莓派4b完美使用，奥利给

**Comment by CMCCAdmin** [comment]
> 谢谢大神加进去，树莓派4b完美使用，奥利给

你用的是什么型号的mt7612u usb无线网卡？

**Comment by imjunfeng** [comment]
> > 谢谢大神加进去，树莓派4b完美使用，奥利给
> 
> 你用的是什么型号的mt7612u usb无线网卡？

华硕的ac55
