### ISSUE TITLE
路由器本身设置为bypass（router_proxy='0'），【谷歌】连通性检查不通过。

### ISSUE THREAD

**Issue by greekstreet** [coolsnowwolf/lede#4324]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
我在路由器上使用Aria2下载，所以设置路由器本身bypass，【谷歌】连通性检查不通过，实际局域网内设备是正常的。

### (1) 具体问题

A：设置路由器本身bypass
`uci set shadowsocksr.@access_control[0].router_proxy='0'`
`uci commit shadowsocksr`
`/etc/init.d/shadowsocksr restart`
B：curl ip.sb显示确实为电信运营商IP，证明路由器本身的流量不走代理。
`curl ip.sb`
C：状态标签页，点击【谷歌】连通性检查，显示连接错误。
D：局域网内设备访问谷歌没有问题，一切正常。

期望行为：不管路由器本身设置是否bypass，【谷歌】连通性检查能正常工作。也即，是否可以直接通过本地代理端口检查谷歌连通性，这样不受规则设置干扰。

其实我觉得路由器本身的代理控制也是不错的功能，还是有使用场景的。

### (2) 路由器型号和固件版本

A：WRT1900ACS，4月14日版本。

### (3) 详细日志

A：无需日志。

**Comment by coolsnowwolf** [comment]
这样自动切换等功能就失效了

**Comment by greekstreet** [comment]
> 这样自动切换等功能就失效了

怪不得luci页面的这部分设置入口注释掉了，鱼和熊掌不可兼得，那就不强求了。
