### ISSUE TITLE
turbo acc的dns加速导致爱奇艺电视版app连不上服务器

### ISSUE THREAD

**Issue by ishadow0** [coolsnowwolf/lede#4332]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：dns加速效果不明显，开了加速一切正常，但几天后电视上的爱奇艺就会访问不了网络，所有爱奇艺源的视频也放不了，其他的app都正常

### (2) 路由器型号和固件版本

A：软路由x64 R20.2.15

### (3) 详细日志

A：无相应日志

**Comment by coolsnowwolf** [comment]
选择合适的 DNS 服务器

**Comment by ilss** [comment]
如果不是 铁通  广电 这种残废宽带，没必要DNS加速。
