### ISSUE TITLE
新版酸酸乳的socks5服务器访问不了内网

### ISSUE THREAD

**Issue by ishadow0** [coolsnowwolf/lede#4333]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：之前用的是R20.2.15版本在公司用switchyomega连socks5，可以直接访问内网ip，ip111检测国内国外访问都是路由器外网ip，google访问是梯子ip。但是昨晚编译的R20.4.8版本socks5服务器增加了全局选项，如果选择梯子那访问所有网站都是走梯子通道，选择与全局模式相同（全局是gfw模式）虽然网站访问正常了，各走各的通道但是内网ip无法访问，并且ip111检测国内国外访问也都是梯子ip

### (2) 路由器型号和固件版本

A：软路由x64   R20.4.8

### (3) 详细日志

A：无相应日志

**Comment by coolsnowwolf** [comment]
分流的 socks5 服务器转到 “服务端” 里面了

**Comment by ishadow0** [comment]
在服务端发现了，但是又衍生出另一个问题，服务端添加socks5必须设置用户名密码，而chrome不支持。另外如果添加ssr服务端，远程pc通过其只能访问内网和墙内的，全局的设置没有作用在“服务端”上
