### ISSUE TITLE
ssr plus 消失了吗，编译出来不见了，哪位解个迷

### ISSUE THREAD

**Issue by AmibaWorld** [coolsnowwolf/lede#4343]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：晚上git pull，结果编译出来ssr plus 不见了，哪位大侠给解惑下

**Comment by AmibaWorld** [comment]
自己close，feeds.config.default取消#，然后重新编译

**Comment by EnnawYang** [comment]
恩？ 自问自答？ interesting

**Comment by AmibaWorld** [comment]
no,顺手又找到了原因了，所以。。。
