### ISSUE TITLE
SSR Plus源码不见了？？？

### ISSUE THREAD

**Issue by smallprogram** [coolsnowwolf/lede#4344]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题
刚pull，发现SSR Plus源码不见了。删了？

![QQ截图20200416224732](https://user-images.githubusercontent.com/6050360/79470709-502cf600-8034-11ea-8ee4-44d5bcf19bee.png)

**Comment by XiaoliChan** [comment]
feeds.conf.default那取消注释那两个即可，然后重新script/feeds update -a

**Comment by XiaoliChan** [comment]
> > feeds.conf.default那取消注释那两个即可，然后重新script/feeds update -a
> 
> 源码被删了

没试过就先别回复....

**Comment by dec2hex** [comment]
交其他人维护了

**Comment by smallprogram** [comment]
了然了
