### ISSUE TITLE
最新的代码是去掉了乳酸菌饮料-plus吗 编译的时候  没看到选项

### ISSUE THREAD

**Issue by newcomein** [coolsnowwolf/lede#4348]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译的时候Applications下面没有乳酸菌饮料-plus

### (2) 路由器型号和固件版本

A：华硕 arch17

### (3) 详细日志

A：

**Comment by kawon7317** [comment]
我也没看到它了。。

**Comment by mingcz0301** [comment]
被干掉了

**Comment by martin0607** [comment]
看看commit就知道了

**Comment by EnnawYang** [comment]
非issue，请关闭

**Comment by marcosteam** [comment]
#4342
