### ISSUE TITLE
ShadowSocksR Plus 访问控制不能正确分流

### ISSUE THREAD

**Issue by h605290713** [coolsnowwolf/lede#4355]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：ShadowSocksR Plus 访问控制不能正确分流

### (2) 路由器型号和固件版本

A：x86  esxi虚拟
      OpenWrt R20.3.19 / LuCI Master (git-20.088.29068-cebe120)
--

### (3) 详细日志

A：目前发现华为mate 30 会出现全局上网，shield tv 酷喵 app 会出现只走国外流量。
正在重新编译最新版本 看看

**Comment by aaaisan** [comment]
重新编译了新版本后你会发现,不只是不能分流那么简单了~

**Comment by h605290713** [comment]
> 重新编译了新版本后你会发现,不只是不能分流那么简单了~
重新编译 和现在版本一样，，，

**Comment by h605290713** [comment]
> 重新编译了新版本后你会发现,不只是不能分流那么简单了~
