### ISSUE TITLE
请问SSR-PLUS模块里，LAN IP访问控制下面，“内网主机列表”有什么用啊？

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4359]
请问SSR-PLUS模块里，LAN IP访问控制下面，“内网主机列表”有什么用啊？

**Comment by Slker** [comment]
结合“内网客户端分流代理控制”来使用

**Comment by mjyhj** [comment]
控制内网哪些IP走 SSR

**Comment by ecco2005** [comment]
> 控制内网哪些IP走 SSR

问题是，这个列表不配置，完全不影响控制内网IP呀

**Comment by ecco2005** [comment]
> 结合“内网客户端分流代理控制”来使用

问题是，这个列表不配置，完全不影响控制内网IP呀

**Comment by martin0607** [comment]
因为你没配置当然不影响
