### ISSUE TITLE
云编译默认支持SSR+不隐藏

### ISSUE THREAD

**Issue by z826540272** [coolsnowwolf/lede#4360]
用 https://github.com/P3TERX/Actions-OpenWrt 云编译脚本
P3TERX脚本灵活性和功能方面优于当前仓库脚本,如果你使用当前仓库脚本,将CONFIG段内容复制到新建.config文件上传即可.
云编译配置文件 diy.sh 写入以下内容即默认开启ssr菜单显示和添加 helloword (SSR+) 仓库内容.
echo 0xDEADBEEF > package/base-files/files/config/google_fu_mode
echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default

**Comment by z826540272** [comment]
上面缺少了一行,完整文件为:
`#!/bin/bash
mkdir package/base-files/files/config
echo 0xDEADBEEF > package/base-files/files/config/google_fu_mode
echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default`

**Comment by garypang13** [comment]
光这样还是不行的,
diy.sh后还需要执行 ./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by FengNning** [comment]
我是这样的
#!/bin/bash
mkdir package/base-files/files/config
echo 0xDEADBEEF > package/base-files/files/config/google_fu_mode
echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
 ./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by garypang13** [comment]
> 我是这样的
> #!/bin/bash
> mkdir package/base-files/files/config
> echo 0xDEADBEEF > package/base-files/files/config/google_fu_mode
> echo "src-git helloworld https://github.com/fw876/helloworld" >> feeds.conf.default
> ./scripts/feeds update -a && ./scripts/feeds install -a

对的,这样就没问题.

**Comment by mjyhj** [comment]
mkdir package/base-files/files/config
echo 0xDEADBEEF > package/base-files/files/config/google_fu_mode

这个config早就已经不需要了，现在没有也不会隐藏的

**Comment by martin0607** [comment]
我是直接在workflow文件里添加这个的
![批注 2020-04-18 212737](https://user-images.githubusercontent.com/32560181/79639013-716c1e80-81bb-11ea-98d0-5cb61756e447.jpg)

**Comment by iamggs** [comment]
> 我是直接在workflow文件里添加这个的
> ![批注 2020-04-18 212737](https://user-images.githubusercontent.com/32560181/79639013-716c1e80-81bb-11ea-98d0-5cb61756e447.jpg)

学习了。

**Comment by madcat0513** [comment]
为啥我改了feeds.conf.default后，menuconfig 里还没出来？

**Comment by tengyuankoo** [comment]
git clone https://github.com/fw876/helloworld package/luci-app-ssr-plus
./scripts/feeds update -a
./scripts/feeds install -a

**Comment by z826540272** [comment]
> git clone https://github.com/fw876/helloworld package/luci-app-ssr-plus
> /scripts/feeds update -a && ./scripts/feeds install -a
不需要更新feeds,因为你直接复制到仓库里了,而不是feed源
