### ISSUE TITLE
请问最新版的源码中找不到ssr+ 迁移到哪里了？

### ISSUE THREAD

**Issue by dreamcmi** [coolsnowwolf/lede#4363]
今天同步的源码 在luci里面找不到ssr+，请问迁移到哪里了？

**Comment by EnnawYang** [comment]
... 翻issue了吗？

**Comment by Twinzo1** [comment]
移到helloworld去了

**Comment by smallerxie** [comment]
[fw876/helloworld](https://github.com/fw876/helloworld)

**Comment by xiehuayi75** [comment]
单独放库了
https://github.com/maxlicheng/luci-app-ssr-plus

**Comment by Marcotso** [comment]
> 单独放库了
> https://github.com/maxlicheng/luci-app-ssr-plus

非最新，还是用fw876的吧

**Comment by Clackz** [comment]
查看这条commits
[https://github.com/coolsnowwolf/lede/commit/af803f2569bbbaac88d001890a8a7646abf0ce0d](url)
