### ISSUE TITLE
昨天给netflix分流域名和IP列表，不能通过备份功能存档吗？

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4366]
昨天往列表里加入了好多IP，然后备份了系统配置，今天恢复了一下系统。

别的地方都恢复，包括SSR-PLUS里面的节点都恢复了。

但是发现netflix的域名和IP列表里，是初始数据

这是BUG?

**Comment by EnnawYang** [comment]
是某人提交了pr改变了列表目录，然后又被改回去了的结果

**Comment by lphgor** [comment]
有人总是喜欢改这个，所以还是自己把需要的文件加到文件备份列表里面吧。
系统 - 备份/升级 - 配置

**Comment by ecco2005** [comment]
> 是某人提交了pr改变了列表目录，然后又被改回去了的结果

什么pr??
