### ISSUE TITLE
lean固件怎么添加passwall

### ISSUE THREAD

**Issue by z826540272** [coolsnowwolf/lede#4369]

**Comment by ecco2005** [comment]
经测试，passwall科学上网的性能，远不如SSR-PLUS。负载均衡功能也没有你想象中的好用

**Comment by guaguagaga** [comment]
负载均衡IP跳来跳去很蛋疼的啊

**Comment by Twinzo1** [comment]
src-git lienol https://github.com/Lienol/openwrt-package

**Comment by Promix953** [comment]
passwall停止开发了

**Comment by DanielChen008** [comment]
passwall 开发者都弃更了，还要了做啥，而且我之前集成后对比过，性能确实不如 ssr-plus

**Comment by z826540272** [comment]
git clone https://github.com/kenzok8/openwrt-packages.git package/openwrt-packages
git clone https://github.com/kenzok8/small.git package/small
解决了,执行上述两行命令后可在menu config菜单中看到luci-app-passwall

**Comment by z826540272** [comment]
> src-git lienol https://github.com/Lienol/openwrt-package
你的这个不对,lienol仓库现在没有passwall

**Comment by M1A6I3L** [comment]
楼上几位也不能一棒子打死PASSWALL啊，性能又不是一切。

至少对我来说多节点代理挺香的，俩设备代理日本，剩下的是香港。

passwall第653个commits就删代码了，需要可以用这位的，正好在652。
https://github.com/cnxzp/openwrt-package

**Comment by badcrazy** [comment]
之前试过，当初奔着均衡去的，但是我的订阅解析出来都是乱码，我就放弃了
