### ISSUE TITLE
删除ssr plus包????

### ISSUE THREAD

**Issue by joesdu** [coolsnowwolf/lede#4381]
删了这个东西,还用OpenWrt干啥哦.🐛🐛🐛

**Comment by guochan2019** [comment]
https://github.com/coolsnowwolf/lede/commit/af803f2569bbbaac88d001890a8a7646abf0ce0d
话说你从来就不看commit么？

**Comment by dolphinpaopao** [comment]
尊重人都做不到还让别人奉献。问号再多也没用。

**Comment by joesdu** [comment]
> 点这个：https://github.com/coolsnowwolf/lede/commit/af803f2569bbbaac88d001890a8a7646abf0ce0d
> 话说你从来就不看commit么？

thanks
