### ISSUE TITLE
uefi-gpt-squashfs固件每次更新都会丢失分区

### ISSUE THREAD

**Issue by winddriver** [coolsnowwolf/lede#4384]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：uefi-gpt-squashfs格式固件，每次更新都会丢失分区信息，导致所有docker相关数据丢失

**Comment by XiaoliChan** [comment]
是的，我也是这样

**Comment by winddriver** [comment]
请问，有什么办法能够保留分区更新固件吗？

**Comment by ziyangdaoren** [comment]
一样的问题

**Comment by qq1316237299** [comment]
uefi不能保留的把 我换回传统就可以保存的

**Comment by jzhou404** [comment]
我也是， 看来是UEFI固件的问题，只要升级，分区就恢复到默认，自己的分区全部丢失

**Comment by cokyrain** [comment]
不仅如此，调整分区大小后的新固件，还会丢失配置

 .config - OpenWrt Configuration
 > Target Images 
        *** Image Options ***                                                           │ │  
  │ │             (**16**) Kernel partition size (in MB)                                                  │ │  
  │ │             (**160**) Root filesystem partition size (in MB)
