### ISSUE TITLE
小米万能遥控器和小爱同学连2.4G wifi每隔几分钟掉一次线 

### ISSUE THREAD

**Issue by Omoinemie** [coolsnowwolf/lede#4388]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：路由器是R3G，刷了自己编译的OPENWRT后小米万能遥控器和小爱同学连2.4G wifi每隔几分钟掉一次线（提示网络连接错误），断流 ，但是手机连上2.4G却没有问题，是不是系统把小米服务器给屏蔽了？没有开屏蔽广告

### (2) 路由器型号和固件版本

A：路由器是R3G

### (3) 详细日志

A：

**Comment by Omoinemie** [comment]
![IMG_20200420_192315](https://user-images.githubusercontent.com/31991443/79746382-7dcbb500-833c-11ea-947d-721afd5d83d8.jpg)
丢包率太高了

**Comment by paulyu666** [comment]
改成固定通道试试，我以前的话说AC-88U只要换信道就会小米智能家居就会掉线
