### ISSUE TITLE
pull到最新版本后菜单中ssr plus没有了

### ISSUE THREAD

**Issue by tufu9441** [coolsnowwolf/lede#4394]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：有段时间没编译了，更新到最新版本代码后，Luci-Applications中找不到luci-app-ssr-plus的选项了，回退到 b97c4e8bb5707c90ba83885e115ba362c418d9b8 后才找回来，是现在食用的姿势有变化了吗？

### (2) 路由器型号和固件版本

A：Newifi D2

### (3) 详细日志

![image](https://user-images.githubusercontent.com/6790361/79731873-7c42c280-8325-11ea-82e6-eaf3d22bd820.png)

**Comment by EnnawYang** [comment]
请仔细翻阅前人的issue

**Comment by guochan2019** [comment]
https://github.com/coolsnowwolf/lede/commit/af803f2569bbbaac88d001890a8a7646abf0ce0d#comments

**Comment by tufu9441** [comment]
> [af803f2#comments](https://github.com/coolsnowwolf/lede/commit/af803f2569bbbaac88d001890a8a7646abf0ce0d#comments)

明白了，感谢两位！
