### ISSUE TITLE
adbyby plus自动失效

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#4402]
不知道为什么经常无故不定时失效,手动关闭后再打开,有时能生效,有时还是不行,出现这种现象已经很长一段时间了,
而且有时点Adblock Plus 规则数据库更新时没有反应,是$$R的问题吗?

**Comment by yangabc123** [comment]
> 不知道为什么经常无故不定时失效,手动关闭后再打开,有时能生效,有时还是不行,出现这种现象已经很长一段时间了,
> 而且有时点Adblock Plus 规则数据库更新时没有反应,是$$R的问题吗?

可能是你开启ipv6了，没办法更新。

**Comment by lxwq** [comment]
> > 不知道为什么经常无故不定时失效,手动关闭后再打开,有时能生效,有时还是不行,出现这种现象已经很长一段时间了,
> > 而且有时点Adblock Plus 规则数据库更新时没有反应,是$$R的问题吗?
> 
> 可能是你开启ipv6了，没办法更新。

编译时就没加入IPV6,
而且是有时能更新,以时更新不到,

**Comment by lxwq** [comment]
似呼是$$R自动切换服务器后广告屏蔽就失效了,到底是谁的锅呢?

**Comment by 908468180** [comment]
我没有ssr和ipv6，但是也会失效，不知道为什么
