### ISSUE TITLE
编译的op k2p 停用wifi，重启又启用

### ISSUE THREAD

**Issue by willisworley** [coolsnowwolf/lede#4404]
## 1.提交的问题

* [ x] 没有类似的issue

## 2. 详细叙述

issue    k2p 停用wifi，重启又启用

A：

### (2) 路由器型号和固件版本

K2P

截图说明：https://s1.ax1x.com/2020/04/21/J35xdx.jpg

[https://s1.ax1x.com/2020/04/21/J35xdx.jpg](url)

**Comment by coolsnowwolf** [comment]
因为 K2P 是单芯片，不存在真正的停用其实。。。

**Comment by willisworley** [comment]
@coolsnowwolf 可是我看吊大的潘多拉，又关掉了，一度陷入了抑郁中

**Comment by kuole-o** [comment]
设置成隐藏的ssid吧  眼不见心不烦

**Comment by willisworley** [comment]
@kuole-o 我测试了一下潘多拉，关闭后添加网络，加入不了。可能不是或者不止隐藏ssid
