### ISSUE TITLE
BUG: trojan订阅地址时，如果地址别名包含空格，则订阅后地址别名只显示空格前的内容

### ISSUE THREAD

**Issue by babylife** [coolsnowwolf/lede#4412]
https://www.right.com.cn/forum/thread-3135031-1-1.html 版本是恩上上的K2P版本
如图所示：应该是 United Status 和hong kong

base64解密后的地址别名：Hong Kong-HK1-1-Rate:0.5

![image](https://user-images.githubusercontent.com/31977161/79949256-d4093700-84a7-11ea-9584-9a36c50a2f81.png)
![image](https://user-images.githubusercontent.com/31977161/79949524-47ab4400-84a8-11ea-9e4c-901c34cd1870.png)

**Comment by ElectronicElephant** [comment]
项目已经易主啦，不是这里维护的啦
