### ISSUE TITLE
树莓派4 自编译刷的系统 开启full cone nat 无法访问百度贴吧

### ISSUE THREAD

**Issue by zhf883680** [coolsnowwolf/lede#4414]
如题 当我关闭 fullconenat时候 可以正常访问百度贴吧

主机名	OpenWrt
主机型号	Raspberry Pi 4 Model B Rev 1.1 (CpuMark : 33405.458756 Scores)
架构	? x 4
固件版本	OpenWrt R9.12.03 / LuCI Master (git-19.338.43082-9e87e69)
内核版本	4.19.88
本地时间	Wed Apr 22 23:05:12 2020
运行时间	41d 3h 6m 36s
平均负载	0.02, 0.04, 0.00

**Comment by hxlls** [comment]
都0202年了。。更新也几百次了，还用老的版本提issues?

**Comment by coolsnowwolf** [comment]
版本太老了，升级吧
