### ISSUE TITLE
请问L大如何把intel集成显卡驱动编译进去

### ISSUE THREAD

**Issue by jinjin327** [coolsnowwolf/lede#4416]
请问L大如何把intel集成显卡驱动编译进去，我只找到个AMD的gpu驱动

**Comment by ElectronicElephant** [comment]
编译进去作甚？

**Comment by mbax2zf2** [comment]
> 编译进去作甚？

对于用带核显的软路由来说，能让plex或者jellyfin这类媒体服务器用核显硬解啊，X86版本的很多都把核显浪费在那里吃电

**Comment by z826540272** [comment]
伪需求,二次转码本来就不必要

**Comment by Cathgao** [comment]
> > 编译进去作甚？
> 
> 对于用带核显的软路由来说，能让plex或者jellyfin这类媒体服务器用核显硬解啊，X86版本的很多都把核显浪费在那里吃电

这类媒体服务器应该在ubuntu之类的发行版跑而不是op

**Comment by slitilanber** [comment]
make kernel_menuconfig
驱动下，把i915加上

**Comment by huangjackey1111** [comment]
是带了显卡驱动的，在Device Drivers ->Graphics support中
