### ISSUE TITLE
更新到最新版本， 本地编译报错，搞了一晚上无解，求助！

### ISSUE THREAD

**Issue by keivenliao** [coolsnowwolf/lede#4418]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [* ] 没有类似的issue

![image](https://user-images.githubusercontent.com/12838693/80045406-dddb7a80-8539-11ea-9b36-40f7c7e0034b.png)

**Comment by lxwq** [comment]
loglog,errlog

**Comment by jw10126121** [comment]
touch /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.built
rm -rf /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc.installed /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc
mkdir -p /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc
install -d -m0755 /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc/lib /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /home/ljw/linOpenwrt/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/lib/ld-musl-*.so* /home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/home/ljw/linOpenwrt/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.5.0_musl/lib/ld-musl-*.so*': No such file or directory
Makefile:618: recipe for target '/home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc.installed' failed
make[2]: *** [/home/ljw/linOpenwrt/openwrt/build_dir/target-mipsel_24kc_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/home/ljw/linOpenwrt/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.10#0.04#0.13
package/Makefile:111: recipe for target 'package/libs/toolchain/compile' failed
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/home/ljw/linOpenwrt/openwrt'
/home/ljw/linOpenwrt/openwrt/include/toplevel.mk:225: recipe for target 'package/feeds/luci/luci-base/compile' failed
make: *** [package/feeds/luci/luci-base/compile] Error 2

**Comment by xnxy2012** [comment]
全局上网，就好了

**Comment by f3404923** [comment]
先开全局梯子，建议rm -rf ./tmp ./build_dir ,然后make download V=s看看是否有包下载错误，最后在make -j1 V=s

**Comment by keivenliao** [comment]
最后， 执行了一次 make clean 再编译就可以了。

**Comment by kktt007** [comment]
> 
> 
> 最后， 执行了一次 make clean 再编译就可以了。

我好了，是否rm -rf ./build_dir和make clean都是必须的,反正通过新版helloworld发现rm-rf ./tmp是必须的。另外我好了

**Comment by ElectronicElephant** [comment]
`rm -rf ./build_dir` 和 `make clean` 都是必须的

**Comment by kktt007** [comment]
> 
> 
> `rm -rf ./build_dir` 和 `make clean` 都是必须的

谢谢，在编译x86固件后再编译R7800,执行了rm -rf./build ./tmp && make clean还不行，然后又加了个make V=s 就好了，已经全局了哎,宝宝心累啊。
