### ISSUE TITLE
nps客户端无法在页面上进行启动

### ISSUE THREAD

**Issue by ZqinKing** [coolsnowwolf/lede#4419]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：配置并保存nps之后，一直未运行。shell登录后执行nps start才能运行npc

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hxlls** [comment]
顺手测试了下，没问题，可能你配置错误或者啥的，尝试不保存配置更新一次试试

**Comment by archyc** [comment]
一直在用，没问题。

**Comment by ivybridgei** [comment]
借楼，希望npc的luci界面可以输入提交服务器域名而不是只能输入ip
