### ISSUE TITLE
/opt/music/没有足够的空间怎么解决？

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#4426]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
/opt/music/没有足够的空间怎么解决？
### (1) 具体问题
/opt/music/没有足够的空间怎么解决？
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
改到其他目录或者挂载
