### ISSUE TITLE
nlbwmon进程CPU使用率过高

### ISSUE THREAD

**Issue by Clackz** [coolsnowwolf/lede#4427]
斐讯k3 版本是到639f363这个commit的编译的，在运行几天后发现路由器CPU使用率过高，top命令查看发现是nlbwmon这个进程占用很高，重启进程后恢复正常，日志中没有发现异常的地方……还需要观察几天看看……
![批注 2020-04-23 201950](https://user-images.githubusercontent.com/42225208/80098799-0c8c3c00-85a0-11ea-8ac3-c8be28180320.png)

**Comment by ElectronicElephant** [comment]
很久以前也遇到过，当时的做法就是直接卸了这个鸡肋😂😂😂

**Comment by stock169** [comment]
这玩意一直有问题的，不定时不定期只要运行时间久了就一定会拖死CPU的，直接卸掉最好

**Comment by hcym** [comment]
还有一个netdata，wan3什么的，自己编译一定要注意去除干净相关依赖包

**Comment by badcrazy** [comment]
是的，我改用bandwidthd了，虽然查看需要ip/bandwidthd，不如nlbw方便，但是不拖cpu

**Comment by zhouym233** [comment]
> 是的，我改用bandwidthd了，虽然查看需要ip/bandwidthd，不如nlbw方便，但是不拖cpu

你好，我想问一下bandwidthd是在编译时添加吗？似乎在编译选项里没有找到。

**Comment by zwillhill** [comment]
同样的问题，卸载完事。问题是menuconfig的时候无法取消，不知道是哪个依赖了。

**Comment by badcrazy** [comment]
> bandwidthd
op官方源就有

**Comment by badcrazy** [comment]
> > 是的，我改用bandwidthd了，虽然查看需要ip/bandwidthd，不如nlbw方便，但是不拖cpu
> 
> 你好，我想问一下bandwidthd是在编译时添加吗？似乎在编译选项里没有找到。

op官方源就有

**Comment by Cathgao** [comment]
建议直接取消编译这个，因为挺鸡肋，统计也不精确

**Comment by 82kg** [comment]
> > 是的，我改用bandwidthd了，虽然查看需要ip/bandwidthd，不如nlbw方便，但是不拖cpu
> 
> 你好，我想问一下bandwidthd是在编译时添加吗？似乎在编译选项里没有找到。

bandwidthd有luci-app的，但是L大好像没加这个包
