### ISSUE TITLE
编译的路由器固件要丢包

### ISSUE THREAD

**Issue by xzjue5** [coolsnowwolf/lede#4429]
编译的小米R3G路由老是要丢包断网，ping外网1000次要丢包100多次，ping内网有时候也会丢包

编译Lienol的OpenWrt 固件就没有这个问题
这个要怎么解决
下面是日志
[ 2438.637536] ------------[ cut here ]------------
[ 2438.642233] WARNING: CPU: 3 PID: 25 at target-mipsel_24kc_musl/linux-ramips_mt7621/mt76-2020-03-10-a94e43f2/mt7603/mac.c:205 mt7603_filter_tx+0x100/0x164 [mt7603e]
[ 2438.656880] Modules linked in: xt_FULLCONENAT pppoe ppp_async pppox ppp_mppe ppp_generic nf_nat_pptp nf_conntrack_pptp mt76x2e mt76x2_common mt76x02_lib mt7603e mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_socket xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TPROXY xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD xt_CT ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_fsm ts_bm slhc nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_redirect nf_nat_proto_gre nf_nat_masquerade_ipv4 nf_nat_irc nf_conntrack_ipv4 nf_nat_ipv4 nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv4 nf_conntrack_tftp
[ 2438.728223]  nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_proto_gre nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast ts_kmp nf_conntrack_amanda mt_wifi macvlan iptable_raw iptable_mangle iptable_filter ip_tables crc_ccitt compat fuse tcp_bbr ledtrig_usbport cryptodev xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6t_NPT ip6t_MASQUERADE nf_nat_masquerade_ipv6 nf_nat nf_conntrack nf_log_ipv6 nf_log_common ip6table_mangle
[ 2438.799401]  ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 sit tunnel4 ip_tunnel snd_rawmidi snd_seq_device snd_pcm_oss snd_pcm snd_timer snd_mixer_oss snd_hwdep snd_compress snd soundcore vfat fat ntfs nls_utf8 nls_iso8859_1 nls_cp437 crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha1_generic ecb authenc usb_storage leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd uhci_hcd ohci_platform ohci_hcd sd_mod scsi_mod gpio_button_hotplug ext4 mbcache jbd2 exfat usbcore nls_base usb_common crc32c_generic
[ 2438.847113] CPU: 3 PID: 25 Comm: kworker/3:0 Not tainted 4.14.176 #0
[ 2438.853510] Workqueue: events rht_deferred_worker
[ 2438.858223] Stack : 8055505c 8fc97afc 805c0000 8fc23b00 805550f0 8eef4330 00000009 000000cd
[ 2438.866599]         8ef00000 8007208c 8fc7b78c 805ca9a7 805c0000 00000001 8fc97ac0 1cc28250
[ 2438.874991]         00000000 00000000 00000000 00008310 00000000 00000193 00000008 00000000
[ 2438.883375]         00000000 805d0000 000d0606 00000000 00000000 805f0000 00000000 8eef4330
[ 2438.891783]         00000009 000000cd 8ef00000 00000001 00000000 802d4c48 0000000c 8073000c
[ 2438.900203]         ...
[ 2438.902672] Call Trace:
[ 2438.905161] [<8000c700>] show_stack+0x58/0x100
[ 2438.909642] [<8048e654>] dump_stack+0xa4/0xe0
[ 2438.914040] [<8002b1e8>] __warn+0xe0/0x114
[ 2438.918153] [<8002b2ac>] warn_slowpath_null+0x1c/0x30
[ 2438.923256] [<8eef4330>] mt7603_filter_tx+0x100/0x164 [mt7603e]
[ 2438.929227] [<8eef4498>] mt7603_wtbl_set_ps+0xa0/0x12c [mt7603e]
[ 2438.935299] [<8eef18ec>] mt7603_sta_ps+0x38/0x3ac [mt7603e]
[ 2438.940923] [<8e593fb4>] mt76_rx_poll_complete+0x474/0x544 [mt76]
[ 2438.947079] [<8e591874>] mt76_dma_cleanup+0x178/0x454 [mt76]
[ 2438.952985] ---[ end trace f4e9c2782416c301 ]---
[ 4334.712091] mt76x2e 0000:02:00.0: MCU message 31 (seq 7) timed out
[ 4336.503628] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4336.509302] mt76x2e 0000:02:00.0: Build: 1
[ 4336.513569] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4336.542102] mt76x2e 0000:02:00.0: Firmware running!
[ 4336.552378] ieee80211 phy1: Hardware restart was requested
[ 4337.592064] mt76x2e 0000:02:00.0: MCU message 31 (seq 9) timed out
[ 4344.544370] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4344.551087] mt76x2e 0000:02:00.0: Build: 1
[ 4344.556168] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4344.582138] mt76x2e 0000:02:00.0: Firmware running!
[ 4344.592622] ieee80211 phy1: Hardware restart was requested
[ 4370.071981] mt76x2e 0000:02:00.0: MCU message 31 (seq 9) timed out
[ 4370.935332] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4370.940824] mt76x2e 0000:02:00.0: Build: 1
[ 4370.945051] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4370.971857] mt76x2e 0000:02:00.0: Firmware running!
[ 4370.983622] ieee80211 phy1: Hardware restart was requested
[ 4381.969575] mt76x2e 0000:02:00.0: MCU message 31 (seq 15) timed out
[ 4384.845145] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4384.850782] mt76x2e 0000:02:00.0: Build: 1
[ 4384.855111] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4384.892646] mt76x2e 0000:02:00.0: Firmware running!
[ 4384.902107] ieee80211 phy1: Hardware restart was requested
[ 4390.392017] mt76x2e 0000:02:00.0: MCU message 31 (seq 9) timed out
[ 4392.558960] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4392.564886] mt76x2e 0000:02:00.0: Build: 1
[ 4392.568983] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4392.591695] mt76x2e 0000:02:00.0: Firmware running!
[ 4392.602035] ieee80211 phy1: Hardware restart was requested
[ 4395.591644] mt76x2e 0000:02:00.0: MCU message 30 (seq 1) timed out
[ 4398.453176] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4398.458844] mt76x2e 0000:02:00.0: Build: 1
[ 4398.463403] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4398.491686] mt76x2e 0000:02:00.0: Firmware running!
[ 4398.501974] ieee80211 phy1: Hardware restart was requested
[ 4401.191605] mt76x2e 0000:02:00.0: MCU message 30 (seq 5) timed out
[ 4402.557126] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4402.562806] mt76x2e 0000:02:00.0: Build: 1
[ 4402.566982] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4402.591618] mt76x2e 0000:02:00.0: Firmware running!
[ 4402.602091] ieee80211 phy1: Hardware restart was requested
[ 4404.636877] mt76x2e 0000:02:00.0: MCU message 30 (seq 9) timed out
[ 4406.636241] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 4406.642151] mt76x2e 0000:02:00.0: Build: 1
[ 4406.646370] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 4406.671589] mt76x2e 0000:02:00.0: Firmware running!
[ 4406.685986] ieee80211 phy1: Hardware restart was requested
[ 6359.369894] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[ 6359.379200] epc = 0043097b in transmission-daemon[400000+3d000]
[ 6359.385515] ra  = 0043097b in transmission-daemon[400000+3d000]
[ 6779.324059] mt76x2e 0000:02:00.0: MCU message 31 (seq 2) timed out
[ 6779.870440] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 6779.876169] mt76x2e 0000:02:00.0: Build: 1
[ 6779.880341] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 6779.905775] mt76x2e 0000:02:00.0: Firmware running!
[ 6779.914413] ieee80211 phy1: Hardware restart was requested
[ 6783.539534] mt76x2e 0000:02:00.0: MCU message 31 (seq 5) timed out
[ 6789.526437] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 6789.532082] mt76x2e 0000:02:00.0: Build: 1
[ 6789.536385] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 6789.587257] mt76x2e 0000:02:00.0: Firmware running!
[ 6789.594062] ieee80211 phy1: Hardware restart was requested
[ 9183.774493] mt76x2e 0000:02:00.0: MCU message 31 (seq 12) timed out
[ 9183.855822] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 9183.861444] mt76x2e 0000:02:00.0: Build: 1
[ 9183.865644] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 9183.894584] mt76x2e 0000:02:00.0: Firmware running!
[ 9183.914589] ieee80211 phy1: Hardware restart was requested
[ 9185.854247] mt76x2e 0000:02:00.0: MCU message 31 (seq 14) timed out
[ 9190.165749] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[ 9190.171650] mt76x2e 0000:02:00.0: Build: 1
[ 9190.176435] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[ 9190.204866] mt76x2e 0000:02:00.0: Firmware running!
[ 9190.224658] ieee80211 phy1: Hardware restart was requested
[11592.948290] mt76x2e 0000:02:00.0: MCU message 31 (seq 9) timed out
[11593.229735] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[11593.235455] mt76x2e 0000:02:00.0: Build: 1
[11593.239662] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[11593.300035] mt76x2e 0000:02:00.0: Firmware running!
[11593.308418] ieee80211 phy1: Hardware restart was requested
[11614.308219] mt76x2e 0000:02:00.0: MCU message 31 (seq 14) timed out
[11633.970859] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[11633.977842] mt76x2e 0000:02:00.0: Build: 1
[11633.983014] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[11634.007993] mt76x2e 0000:02:00.0: Firmware running!
[11634.021285] ieee80211 phy1: Hardware restart was requested
[12848.693427] mt76x2e 0000:02:00.0: MCU message 31 (seq 6) timed out
[12848.924568] mt76x2e 0000:02:00.0: Firmware Version: 0.0.00
[12848.930071] mt76x2e 0000:02:00.0: Build: 1
[12848.935063] mt76x2e 0000:02:00.0: Build Time: 201507311614____
[12848.963132] mt76x2e 0000:02:00.0: Firmware running!
[12848.973331] ieee80211 phy1: Hardware restart was requested
[12981.138225] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
[40165.040374] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
[40176.775471] mtk_soc_eth 1e100000.ethernet eth0: port 2 link down
[40179.944348] mtk_soc_eth 1e100000.ethernet eth0: port 2 link up
[43506.973943] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 77fd6000
[43506.984430] epc = 77f9df2c in libc.so[77f2b000+98000]
[43506.990474] ra  = 77c1b589 in libz.so.1.2.11[77c19000+1e000]
[43564.653616] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[43564.663103] epc = 77f6eba0 in libc.so[77efc000+98000]
[43564.670366] ra  = 77eb4267 in libevent-2.1.so.7.0.0[77e98000+36000]
[43627.268765] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[43627.277941] epc = 77f3cba0 in libc.so[77eca000+98000]
[43627.283387] ra  = 77e82267 in libevent-2.1.so.7.0.0[77e66000+36000]
[43682.670638] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[43682.680253] epc = 77ef5ba0 in libc.so[77e83000+98000]
[43682.685441] ra  = 77e3b267 in libevent-2.1.so.7.0.0[77e1f000+36000]
[43731.029504] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[43731.038859] epc = 77f83ba0 in libc.so[77f11000+98000]
[43731.044203] ra  = 77ec9267 in libevent-2.1.so.7.0.0[77ead000+36000]
[43783.274270] do_page_fault(): sending SIGSEGV to transmission-da for invalid write access to 00000000
[43783.283450] epc = 77fb1ba0 in libc.so[77f3f000+98000]
[43783.288653] ra  = 77ef7267 in libevent-2.1.so.7.0.0[77edb000+36000]

**Comment by jw10126121** [comment]
我的，好像也会这样。。

**Comment by xzjue5** [comment]
> 我的，好像也会这样。。

000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by xzjue5** [comment]
> 我的，好像也会这样。。

用LienoI的就没问题   我现在用lede的固件LienoI的配置  这样就解决丢包了  很稳定
