### ISSUE TITLE
如何编译改了16M闪存的4530Rg固件，默认设置超过了8M就没有sysupgarde的文件输出

### ISSUE THREAD

**Issue by ChuckPeng** [coolsnowwolf/lede#4431]
尝试改过如下参数：
define Device/mc-mw4530r
$(Device/tplink-16mlzma)
DEVICE_TITLE := Mercury MW4530R
DEVICE_PACKAGES := kmod-usb-core kmod-usb2 kmod-usb-ledtrig-usbport
BOARDNAME := MC-MW4530R
DEVICE_PROFILE := MW4530R
TPLINK_HWID := 0x43500001
能生成8M以上的，但刷进去后无法启动

**Comment by lujimmy** [comment]
841v9硬性为8M flsh 修改以下内容
1. target/linux/ar71xx/image/tiny-tp-link.mk 第563行 修改为 $(Device/tplink-8mlzma)
2.target/linux/ar71xx/config-4.14 第 238行修改为 CONFIG_ATH79_MACH_TL_WR841N_V9=y

可参考修改，希望能帮到你！
