### ISSUE TITLE
可以自己试着编译一个了。

### ISSUE THREAD

**Issue by kevinlyliu** [coolsnowwolf/lede#4435]
可以自己试着编译一个了。

_Originally posted by @hlz781105 in https://github.com/coolsnowwolf/lede/issues/4433#issuecomment-619295653_

自己编译一个就会好吗？不懂啊😯

**Comment by hlz781105** [comment]
我这个帖子里面有详细过程

https://github.com/coolsnowwolf/lede/issues/4410
