### ISSUE TITLE
Alcatel RG100A 默认编译出的固件，没有ssr plus 如何添加？

### ISSUE THREAD

**Issue by jiatongwu** [coolsnowwolf/lede#4441]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：Alcatel RG100A 默认编译出的固件，没有ssr plus 如何添加？

### (2) 路由器型号和固件版本

A：Alcatel RG100A

### (3) 详细日志

A：

**Comment by keivenliao** [comment]
建议你先搜索一下issues
