### ISSUE TITLE
更新4-25加强版之后ntfs格式硬盘挂载出错，能识别但挂载不上

### ISSUE THREAD

**Issue by funhao** [coolsnowwolf/lede#4442]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：更新4-25加强版之后ntfs格式硬盘挂载出错，能识别但挂载不上。mount: /dev/sdb2: unknown filesystem type 'ntfs'.

### (2) 路由器型号和固件版本
 
A：E3845软路由，R20.4.8 

### (3) 详细日志

A：

**Comment by 9l** [comment]
加强版是啥玩意？

**Comment by funhao** [comment]
明白
