### ISSUE TITLE
WRT32X 能获取到V6，但是无法上网

### ISSUE THREAD

**Issue by haig233** [coolsnowwolf/lede#4445]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
WRT32X 能获取到V6，但是无法上网
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
WRT32X 能获取到V6，但是无法上网，网络连接里详细信息，看到IPv6是有IP的
![InkedTIM20200426160539_LI.jpg](https://img.pterclub.com/images/2020/04/26/InkedTIM20200426160539_LI.jpg)
### (1) 具体问题

A：看图吧
![InkedTIM20200426160355_LI.jpg](https://img.pterclub.com/images/2020/04/26/InkedTIM20200426160355_LI.jpg)
![TIM20200426160546.png](https://img.pterclub.com/images/2020/04/26/TIM20200426160546.png)
![TIM20200426160528.png](https://img.pterclub.com/images/2020/04/26/TIM20200426160528.png)

### (2) 路由器型号和固件版本

A：WRT32X

**Comment by xzjue5** [comment]
![QQ截图20200426161552](https://user-images.githubusercontent.com/40517748/80301901-5a3fb900-87d9-11ea-96d2-8d8e108b3aa5.png)
把这个删了

**Comment by haig233** [comment]
删了还是不行

**Comment by xzjue5** [comment]
DHCP/DNS-高级设置-禁止解析 IPv6 DNS 记录  取消试试

**Comment by haig233** [comment]
> DHCP/DNS-高级设置-禁止解析 IPv6 DNS 记录 取消试试

也试过了，也不行

**Comment by xzjue5** [comment]
http://www.test-ipv6.com 测试一下

**Comment by haig233** [comment]
> http://www.test-ipv6.com 测试一下

昨晚试了很多种方法，都不行，IP.sb测试都没有V6

**Comment by xzjue5** [comment]
v6的防火墙设置了吗

**Comment by haig233** [comment]
> v6的防火墙设置了吗

需要动防火墙吗
之前4月15号之前编译的固件都是可以直接用的，后面的，就一直用不了V6

**Comment by xzjue5** [comment]
![image](https://user-images.githubusercontent.com/40517748/80303727-9593b500-87e4-11ea-922d-88bea0a26a53.png)
看看是不是这样的

**Comment by zyizhuo** [comment]
问题一样。我发现一个现象，刚启动的几秒内可以ping通外网ipv6，几秒后ping显示“Network unreachable”

**Comment by xzjue5** [comment]
是不是设置了负载均衡

**Comment by haig233** [comment]
> 是不是设置了负载均衡

刚刚刷进去的固件，没改什么

**Comment by xzjue5** [comment]
> > 是不是设置了负载均衡
> 
> 刚刚刷进去的固件，没改什么

看一下有没有负载均衡，有的话就删掉里面的配置

**Comment by zyizhuo** [comment]
我用了一个去掉了一堆组件的精简版后莫名其妙没问题了

**Comment by zyizhuo** [comment]
> 
> 
> 问题一样。我发现一个现象，刚启动的几秒内可以ping通外网ipv6，几秒后ping显示“Network unreachable”

我用了一个去掉了一堆组件的精简版后莫名其妙没问题了。

**Comment by zyizhuo** [comment]
> > 问题一样。我发现一个现象，刚启动的几秒内可以ping通外网ipv6，几秒后ping显示“Network unreachable”
> 
> 我用了一个去掉了一堆组件的精简版后莫名其妙没问题了。

又多了一个线索：用老版本正常的IPv6备份后导入到最新版本后IPv6正常

**Comment by hyird** [comment]
mwan3安装了没有 装了的话就卸载了

**Comment by haig233** [comment]
> mwan3安装了没有 装了的话就卸载了

卸载了能用V6了再装回去么？我需要多拨

**Comment by hyird** [comment]
多拨和v6是冤家 自己改mwan3 恩山有

**Comment by haig233** [comment]
> 多拨和v6是冤家 自己改mwan3 恩山有

就好像我上面说得，我刚刚把固件刷进去，并没有动过Mwan3的设置啊，这个插件只要有都会有影响么

**Comment by hcwang** [comment]
负载均衡中的“策略”，将balanced的备用成员从“不可达”改为“使用默认路由表”试试。

**Comment by shikkoku** [comment]
我刚编译的X86-64版和楼主问题一样。而且我还没有编译mwan3进去。

**Comment by yunmi323** [comment]
有些地方只给v6地址，不能联网。之前广东电信也这样有地址只能上电信官网其他不能上，现在好了还可以看v6线路直播。建议等等吧，工信部要求年底基本弄好。

**Comment by shikkoku** [comment]
> 有些地方只给v6地址，不能联网。之前广东电信也这样有地址只能上电信官网其他不能上，现在好了还可以看v6线路直播。建议等等吧，工信部要求年底基本弄好。

但我编译原版Openwrt IPv6就没有问题，也有其他类似的issue反馈回退旧版本的代码后编译也恢复正常了。

**Comment by zhouym233** [comment]
遇到类似情况。MT7621平台，未编译mwan3，正常获取dhcpv6-pd，ssh到路由去ping公网v6是通的，路由后端的设备能获取公网v6地址但ping不通。

**Comment by zhouym233** [comment]
> 遇到类似情况。MT7621平台，未编译mwan3，正常获取dhcpv6-pd，ssh到路由去ping公网v6是通的，路由后端的设备能获取公网v6地址但ping不通。

https://github.com/coolsnowwolf/lede/issues/3797#issuecomment-600538499
删除重建wan6接口之后重启就好了，玄学.....

**Comment by zyizhuo** [comment]
> 有些地方只给v6地址，不能联网。之前广东电信也这样有地址只能上电信官网其他不能上，现在好了还可以看v6线路直播。建议等等吧，工信部要求年底基本弄好。

刚开机的几秒内可以ping通ipv6外网...用opnsense也没问题

**Comment by haig233** [comment]
> 有些地方只给v6地址，不能联网。之前广东电信也这样有地址只能上电信官网其他不能上，现在好了还可以看v6线路直播。建议等等吧，工信部要求年底基本弄好。

不存在你说的这种可能，我用电脑直连猫或者用路由器原版固件是一切正常的，能访问纯V6网站

**Comment by wushangwei** [comment]
x64也是一样的问题，我发现用新版的固件，路由器端都ping不通v6，我用恩山里lusty编译的固件，5月9号的固件也不行，但是5月1号的固件就可以；5月9号的固件的更新日志里有个内核支持网桥，不知道是不是和这个有关系，因此是不是五月初某次更新影响到了ipv6

**Comment by ZqinKing** [comment]
你是不是把wan6的借口删掉了？如果wan6的接口删掉了的话，防火墙就没有ipv6的放行规则，需要自行手动添加！
