### ISSUE TITLE
luci-app-dockerman 编译报错

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#4452]
ubuntu 20.04，已经编译成功，第一次已经编译进了dockerman，进行二次编译，提示WARNING: Makefile 'package/lean/luci-app-dockerman/Makefile' has a dependency on 'docker-ce', which does not exist，编译报错。

虚拟机ubuntu，有备份，使用新的ubuntu，执行到make menuconfig后，仍然提示WARNING: Makefile 'package/lean/luci-app-dockerman/Makefile' has a dependency on 'docker-ce', which does not exist，编译不了。

**Comment by hyird** [comment]
我的锅,我的锅 只升级了docker-ce 依赖忘了
https://github.com/coolsnowwolf/packages/pull/58
你试试这个pr

**Comment by lloyd18** [comment]
./scripts/feeds update -a
./scripts/feeds install -a

**Comment by jy3344511** [comment]
> ./scripts/feeds update -a
> ./scripts/feeds install -a

系统有备份，都换全新的了，这两步怎么可能没做呢？

**Comment by liwenjie119** [comment]
> > ./scripts/feeds update -a
> > ./scripts/feeds install -a
> 
> 系统有备份，都换全新的了，这两步怎么可能没做呢？

rm -rf ./tmp后再次执行试试

**Comment by KFERMercer** [comment]
已经修好了, 关了吧
