### ISSUE TITLE
关于OpenWrt固件在Telegram发送文件会断网的情况

### ISSUE THREAD

**Issue by XiaoXiao-13** [coolsnowwolf/lede#4454]
测试了下，或许是机场＋移动网络原因。

**Comment by Topcckin** [comment]
X86，+1，打开Google正常，重启plus+就正常了。

**Comment by XiaoXiao-13** [comment]
> X86中+1，打开Google正常，重启plus+就正常了。

不妨试试换个机场测试下，我的大概是机场问题
