### ISSUE TITLE
系统日志 uhttpd 一直在报错

### ISSUE THREAD

**Issue by Myoko** [coolsnowwolf/lede#4459]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
Mon Apr 27 14:56:19 2020 daemon.err uhttpd[2327]: uci: Entry not found
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：x86-64

OpenWrt R20.4.8 / LuCI Master (git-20.117.60969-420c61a)

### (3) 详细日志

A：Mon Apr 27 14:56:19 2020 daemon.err uhttpd[2327]: uci: Entry not found

**Comment by jiawm** [comment]
新编译，多个版本均报以下错误代码
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
Mon Apr 26 04:26:11 2021 daemon.err uhttpd[4392]: Dump terminated
