### ISSUE TITLE
SSR+在开启ipv6后隔一段时间就连不上

### ISSUE THREAD

**Issue by Omoinemie** [coolsnowwolf/lede#4461]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：SSR+在开启ipv6后隔一段时间不用就连不上，需要重启路由器才行，开的是GFW模式，电脑ping谷歌出来的是ipv4地址，下面我还接了个次路由，通过次路由连谷歌是正常的，次路由下面的手机没有ipv6地址。

### (2) 路由器型号和固件版本

A：R3G自编译

### (3) 详细日志

A：

**Comment by Her0R0cket** [comment]
ipv6和饮料命格不合,需要高人找到和平共处之法
