### ISSUE TITLE
关于igmpproxy和omcproxy组播转发功能的期望

### ISSUE THREAD

**Issue by yangtian1129** [coolsnowwolf/lede#4465]
大佬，首先感谢您的无私分享。能否考虑改进下igmpproxy或者omcproxy，目前使用起来ogmcproxy据作者说只能支持官方openwrt，而igmpproxy由于版本太老了和咱们的19.07兼容上有些小bug，会有出现断流现象和端口风暴。我感觉在国内想利用软路由融合或分流iptv的个人需求还是不少的。麻烦了，谢谢！

**Comment by hyird** [comment]
只支持luci19以上

**Comment by hyird** [comment]
有插件界面截图么 我尝试一下

**Comment by hcym** [comment]
就用官方的吧，弄个clash，基本够用，就是没有大雕的方便

**Comment by wchqybs** [comment]
@yangtian1129 有没有解决卡顿的办法

**Comment by mumuou** [comment]
这个可以有，现在就缺这个了~~

**Comment by lexin8** [comment]
这个一直没有修复，真是个头疼了问题，Lienol的源可以正常使用，但是docker运行不正常，要么分流有问题，我是服了，没有一个完美的版本。

**Comment by wchqybs** [comment]
@yangtian1129 @lexin8 你们测试一下这个版本呢https://github.com/iyuangang/openwrt
