### ISSUE TITLE
[建议]是否考虑在x86/64版本里加入DPDK

### ISSUE THREAD

**Issue by s7lx** [coolsnowwolf/lede#4466]
https://www.dpdk.org/
https://lvwenhan.com/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F/496.html
DPDK 本身能提高小包转发的性能，网上也有相关介绍
应该就是很多低端x86芯片的高性能NAT的解决方案了

**Comment by coolsnowwolf** [comment]
DPDK 对实际应用并不适合，光是只能运行在 glibc 和 intel cpu + intel 网卡 就劝退一堆人了

对我们来说，应用层的性能比多并发小包性能更重要
