### ISSUE TITLE
openwrt 挂载google drive 无限硬盘

### ISSUE THREAD

**Issue by willisworley** [coolsnowwolf/lede#4469]
建议，来个挂载google drive 无限硬盘的openwrt 插件，然后samba 共享映射给Windows使用

能支持挂载百毒，微云多种网盘就更好了

**Comment by EnnawYang** [comment]
GD可以诶  百毒等等的就算了吧

**Comment by lloyd18** [comment]
想法不错，rclone了解一下

**Comment by hxlls** [comment]
webdav协议的 可以通过安装davfs2来实现挂载，这个软件在openwrt 官方源已经有，只不过没有luci 界面而已，至于其他协议的，这个就自己查找了

**Comment by ElectronicElephant** [comment]
[Community help needed]
欢迎楼主pr

**Comment by coolsnowwolf** [comment]
已添加 rclone

**Comment by willisworley** [comment]
@lloyd18 @coolsnowwolf 

挂载好像还不好，本地会存一份，占磁盘。像iCloud一样，较长时间不用的文件，删除本地文件，只保留云端，编辑的时候下载就nice
