### ISSUE TITLE
编译出来的X86固件，没有WAN口和WAN6，是怎么回事？

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4471]
我在默认配置的基础上，多选一1个主题，加了几个luci应用，别的没动过。

但是编译出来以后，只有LAN口和VPN口，没有WAN和WAN6。

前段时间编译的方法相同，是有WAN口的

请问这是怎么回事？

**Comment by Her0R0cket** [comment]
什么硬件啊,看看认到几张网卡了,接口里面添加新接口,看看底下有没有eth1,有的话自己加个wan口,或者恢复出厂试试吧.

**Comment by evangelion015** [comment]
自己添加接口，物理设置和防火墙改一下就行了
