### ISSUE TITLE
Applications 里的 ss plus 看不到了么？

### ISSUE THREAD

**Issue by a1392429292** [coolsnowwolf/lede#4472]
如题，没看到有ss plus的选项了。。。

**Comment by EnnawYang** [comment]
哦

**Comment by hwangjunjie** [comment]
能不能直接关闭，怎么老是有人问这个问题

**Comment by a1392429292** [comment]
> 能不能直接关闭，怎么老是有人问这个问题

所以啊，为何总是有人问呢？是隐藏了吗？还是就去掉了以后也不会有了？还是？？？

**Comment by EnnawYang** [comment]
> > 能不能直接关闭，怎么老是有人问这个问题
> 
> 所以啊，为何总是有人问呢？是隐藏了吗？还是就去掉了以后也不会有了？还是？？？

所以能搜到的问题为什么老是有人问呢

**Comment by hwangjunjie** [comment]
![image](https://user-images.githubusercontent.com/2819873/80486868-7042aa80-898e-11ea-9042-621cb4a9bdc7.png)

**Comment by a1392429292** [comment]
> > > 能不能直接关闭，怎么老是有人问这个问题
> > 
> > 
> > 所以啊，为何总是有人问呢？是隐藏了吗？还是就去掉了以后也不会有了？还是？？？
> 
> 所以能搜到的问题为什么老是有人问呢

能够讲一下，为何去掉吗？如果软路由没有了这个功能，软路由意义何在？
是不更新了呢？还是开发者面临违法问题？还是怎样？以后也不会有了吗？

**Comment by EnnawYang** [comment]
> > > > 能不能直接关闭，怎么老是有人问这个问题
> > > 
> > > 
> > > 所以啊，为何总是有人问呢？是隐藏了吗？还是就去掉了以后也不会有了？还是？？？
> > 
> > 
> > 所以能搜到的问题为什么老是有人问呢
> 
> 能够讲一下，为何去掉吗？如果软路由没有了这个功能，软路由意义何在？
> 是不更新了呢？还是开发者面临违法问题？还是怎样？以后也不会有了吗？

敢不敢自己动手搜一下呢，兄弟？
