### ISSUE TITLE
176-7版本ssr有问题

### ISSUE THREAD

**Issue by zheshifandian** [coolsnowwolf/lede#4475]
从昨天开始，谷歌连不上，谷歌连通性检查失败，表现为开了ssr还不如不开

**Comment by zheshifandian** [comment]
谷歌连通失败，反正就是处于报废状态，开了还不如不开(开了连gayhub都打不开)

**Comment by dgulan** [comment]
奇怪的很：自从本次编译之后，V2就再也连接不上。
打开s s r之后，github打不开；关了S S R，github就可以打开。

更奇怪的是：我用winscp可以登录v p s 服务器，但是windows 端的v 2 ray N一样登陆不上。

**Comment by zheshifandian** [comment]
> 奇怪的很：自从本次编译之后，V2就再也连接不上。
> 打开s s r之后，github打不开；关了S S R，github就可以打开。
> 
> 更奇怪的是：我用winscp可以登录v p s 服务器，但是windows 端的v 2 ray N一样登陆不上。
> 
> 因为windows 版本 v 2 ray N客户端一样无法连接，我同样怀疑是不是v2被 土蔷 了？
> winscp可以连接此IP的。

我用大雕的潘多拉，ssr没问题，op就gg
