### ISSUE TITLE
这几天的固件编译出来ssr-plus不见了

### ISSUE THREAD

**Issue by winddriver** [coolsnowwolf/lede#4477]
这几天的固件编译出来ssr-plus不见了，配置文件里肯定是开启了ssr-plus的
![image](https://user-images.githubusercontent.com/3221597/80553264-c00b8b00-89fb-11ea-84ad-0226bbbc6f51.png)
[config.zip](https://github.com/coolsnowwolf/lede/files/4549368/config.zip)

**Comment by winddriver** [comment]
![image](https://user-images.githubusercontent.com/3221597/80553380-40ca8700-89fc-11ea-9441-c0d930355f45.png)
这是固件服务那一栏，里面没有ssr-plus

**Comment by EnnawYang** [comment]
非issue 请关闭

**Comment by winddriver** [comment]
> 非issue 请关闭

这如果不叫问题，请问什么叫问题？

**Comment by a1392429292** [comment]
> > 非issue 请关闭
> 
> 这如果不叫问题，请问什么叫问题？

这里，总是有那么几个人，回答很及时，但就是不正面回答你的问题，无非就是  非issue，搜以往issue。。。。。反正就是不直接回答你的问题，与其有时间答非所问，不如一针见血的回答。

因为 ssr-plus 现在隐藏掉了，详细可以看 
https://github.com/coolsnowwolf/lede/issues/4410#issuecomment-618436351

**Comment by winddriver** [comment]
> > > 非issue 请关闭
> > 
> > 
> > 这如果不叫问题，请问什么叫问题？
> 
> 这里，总是有那么几个人，回答很及时，但就是不正面回答你的问题，无非就是 非issue，搜以往issue。。。。。反正就是不直接回答你的问题，与其有时间答非所问，不如一针见血的回答。
> 
> 因为 ssr-plus 现在隐藏掉了，详细可以看
> [#4410 (comment)](https://github.com/coolsnowwolf/lede/issues/4410#issuecomment-618436351)

感谢解惑，我去试试
