### ISSUE TITLE
frpc无法设置http代理

### ISSUE THREAD

**Issue by BlacK201** [coolsnowwolf/lede#4483]
https://github.com/coolsnowwolf/lede/blob/64c72766f4b009ea7af803ccdd36f2a77a7cb624/package/lean/luci-app-frpc/luasrc/model/cbi/frp/frp.lua#L49-L51

这里按照默认提示应该是填一个http代理链接，但是datatype却是uinteger，导致保存时提示值无效

**Comment by haxc** [comment]
删除掉e.datatype="uinteger" 就可以了
