### ISSUE TITLE
Zerotier授权导致死机

### ISSUE THREAD

**Issue by evangelion015** [coolsnowwolf/lede#4499]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：4月28号更新源码重新编译版本出现此问题，其他插件默认，单独添加ZT也有此问题出现
重新刷写固件后开启ZT没有问题，显示ZT运行中
进入ZT后台，授权前显示版本号为-1,-1,-1  打钩授权之后显示版本号为1.4.6
此时路由器死机，即使重启路由器，只要ZT启动就死机

### (2) 路由器型号和固件版本

A：树莓派4B，OpenWrt R20.4.8 / LuCI Master (git-20.117.60969-420c61a)

### (3) 详细日志

A：软路由断连，web与ssh都无法进入，无法获取日志

**Comment by xsm1997** [comment]
如果你在zerotier后台设置了设备路由，请取消一下。可能是设备id发生变化导致路由混乱。

**Comment by evangelion015** [comment]
后台删除路由表之后正常连接，重新设置即可
