### ISSUE TITLE
最新编译竞斗云路由器固件，仍然不能无线中继！

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#4503]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新编译竞斗云路由器固件，仍然不能无线中继！

### (2) 路由器型号和固件版本

A：竞斗云路由器固件，p2w-128m，20.4.8版本

### (3) 详细日志

A：
日志里有：
Fri May  1 04:02:36 2020 daemon.info procd: Instance nginx::instance1 s in a crash loop 6 crashes, 3 seconds since last crash
Fri May  1 04:02:55 2020 daemon.notice netifd: radio0 (8285): Command failed: Invalid argument
Fri May  1 04:02:56 2020 daemon.notice netifd: radio0 (8321): command failed: Not supported (-95)
Fri May  1 04:03:01 2020 daemon.notice netifd: radio0 (8454): command failed: Not supported (-95)
Fri May  1 04:03:01 2020 user.notice root: ip link set dev wlan0 up
Fri May  1 04:03:03 2020 kern.warn kernel: [  139.806702] ath10k_ahb a000000.wifi: unsupported HTC service id: 1536
Fri May  1 04:03:03 2020 kern.info kernel: [  139.976696] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Fri May  1 04:03:33 2020 daemon.notice netifd: radio0 (8454): Command failed: Request timed out
Fri May  1 04:03:33 2020 daemon.notice netifd: radio0 (8454): Command failed: Not found
Fri May  1 04:03:33 2020 daemon.notice netifd: radio0 (8454): Interface 0 setup failed: WPA_SUPPLICANT_FAILED
Fri May  1 04:03:33 2020 daemon.notice netifd: radio0 (8454): WARNING (wireless_add_process): executable path /usr/sbin/wpad does not match process  path (/proc/exe)
Fri May  1 04:03:33 2020 daemon.notice netifd: radio0 (8454): Command failed: Invalid argument
![image](https://user-images.githubusercontent.com/17406910/80799309-1bdf3b00-8bd9-11ea-8776-47181d1701c9.png)
![image](https://user-images.githubusercontent.com/17406910/80799324-28639380-8bd9-11ea-9915-d759dd92792b.png)

**Comment by jgsports** [comment]
我两个路由器，一个可以，另一个也是最近编译的，无法进行无线中继，后来改了无线信道，虽没错误提示，但终究不能上网

**Comment by waynon** [comment]
开两个一样的issue有意思吗？#4474

**Comment by shenzt68** [comment]
引起大吊注意啊
