### ISSUE TITLE
openwrt上的Rclone插件，有挂载成功的分享下方法，谢谢

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#4510]
在Win10上用Rclone挂载没问题，这两天更新了Rclone插件，在路由器上挂载，按照插件页面说的，把配置文件上传到/etc/rclone，挂载网盘，然后就没有然后了，所以重新创建配置文件挂载，也打不开，有挂载成功的，分享下方法，谢谢。

![01](https://user-images.githubusercontent.com/49992475/80845616-5a5a1180-8c3c-11ea-8e90-12c1d8fc4045.jpg)

**Comment by jinjin327** [comment]
是的，我也是挂载不成功

**Comment by yavg** [comment]
R2S 成功挂载, 但自动启动就是搞不定. 下面是一些我的备注非教程.
我刷的
https://github.com/klever1988/nanopi-openwrt/releases/download/R2S-Lean-2020-09-30/R2S-Lean-2020-09-30-ROM.zip
网关192.168.2.1还是1.1 root password
设置
改密
改为旁路由
关HDCP分配
安rclone
onedrive/rclone/替换大法
加权
用win做好rclone.conf并替换

按自带的教程搞定docker.

开机启动
