### ISSUE TITLE
请问k2p怎么单独关闭5gWiFi？

### ISSUE THREAD

**Issue by gold2wave** [coolsnowwolf/lede#4522]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译了k2p固件，5gwifi开关好像和2.4g是反的，而且每次关闭完重启之后又会自动打开

### (2) 路由器型号和固件版本

A：k2p

### (3) 详细日志

A：无

**Comment by willisworley** [comment]
是的，我编译发现也是这样，l吊有法子解决
