### ISSUE TITLE
重大BUG B70固件编译最新代码2.4G无法中继

### ISSUE THREAD

**Issue by chenxudong2020** [coolsnowwolf/lede#4523]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A： B70固件编译最新代码2.4G无法中继 具体表现为2.4G 搜素添加 勾选 重置网络  添加密码，两次确认后 跳转无线  显示页面
Client 无线显示未关联  

### (2) 路由器型号和固件版本

A：B70 HC5962

### (3) 详细日志

A：无最新日志 可以提取 待后续跟进
以前的版本没有此问题 ，最新的可能跟驱动调整有关

**Comment by AmadeusGhost** [comment]
![client](https://user-images.githubusercontent.com/42570690/80897630-58bc4680-8d2d-11ea-97b1-8219ee605482.png)
实测中继正常，你这一用重大bug二不给图三不给日志是想让我砍你呢还是砍你呢

**Comment by chenxudong2020** [comment]
机型不一样7603e



---原始邮件---
发件人: "AmadeusGhost"<notifications@github.com&gt;
发送时间: 2020年5月3日(周日) 中午11:02
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chenxudong2020"<872603935@qq.com&gt;;
主题: Re: [coolsnowwolf/lede] 重大BUG B70固件编译最新代码2.4G无法中继 (#4523)




 

 实测中继正常，你这一用重大bug二不给图三不给日志是想让我砍你呢还是砍你呢

**Comment by AmadeusGhost** [comment]
> 机型不一样7603e

我问了一个新3的正常啊

**Comment by chenxudong2020** [comment]
机型不一样 这个是nand 不具有可比性 请在b70测试



---原始邮件---
发件人: "AmadeusGhost"<notifications@github.com&gt;
发送时间: 2020年5月3日(周日) 中午11:17
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chenxudong2020"<872603935@qq.com&gt;;
主题: Re: [coolsnowwolf/lede] 重大BUG B70固件编译最新代码2.4G无法中继 (#4523)




  
机型不一样7603e
  
我问了一个新3的正常啊
