### ISSUE TITLE
openwrt如何添加PPPOE服务器

### ISSUE THREAD

**Issue by weweyes** [coolsnowwolf/lede#4530]
请教各位大佬，openwrt如何添加PPPOE服务器？

**Comment by hxlls** [comment]
自己在软件包安装luci-app-rp-pppoe-server和对应的组件

**Comment by hzjixiang** [comment]
> 自己在软件包安装luci-app-rp-pppoe-server和对应的组件

请问对应的组件是啥？ 小白求教
