### ISSUE TITLE
4.19內核部分機種無法2.4G無線無法正常運作

### ISSUE THREAD

**Issue by aaronchin** [coolsnowwolf/lede#4534]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
A：4.19內核無法2.4G無線無法正常運作

### (2) 路由器型号和固件版本

A：Newifi D2 無法正確抓取到2.4G網卡 5G網卡正常
      竟斗雲2.0 R619AC 2.4G網卡無法當作客戶端client

### (3) 详细日志

A：以上兩機種改刷R20.4.8版固件4.14.176內核都沒這些問題

**Comment by shenzt68** [comment]
反正竟斗雲2.0 R619AC 2.4G網卡無法當作客戶端client，一直反复重启

**Comment by AmadeusGhost** [comment]
日志呢？光这样说有用吗？
![client](https://user-images.githubusercontent.com/42570690/80908218-bdd56380-8d50-11ea-93fa-56f6443574d4.png)
同竞斗云，正常使用

**Comment by shenzt68** [comment]
> 日志呢？光这样说有用吗？
> ![client](https://user-images.githubusercontent.com/42570690/80908218-bdd56380-8d50-11ea-93fa-56f6443574d4.png)
> 同竞斗云，正常使用

你试试用2.4G无线中继，就出现问题了

**Comment by aaronchin** [comment]
很凶的老哥 您要的日誌來了 BTW你要不要看下你的內核版本呢
![WeChat圖片編輯_20200508103015](https://user-images.githubusercontent.com/16252372/81363997-36ed0600-9117-11ea-802f-00807925700e.jpg)
![WeChat圖片編輯_20200508103050](https://user-images.githubusercontent.com/16252372/81363999-381e3300-9117-11ea-8370-9e840f91ffba.jpg)
![WeChat圖片編輯_20200508103109](https://user-images.githubusercontent.com/16252372/81364013-3b192380-9117-11ea-8ba3-bfdf9d52e0bf.jpg)
有圖有真相 上面的是4.19版內核的狀況還有日誌
[log.txt](https://github.com/coolsnowwolf/lede/files/4596709/log.txt)
[log1.txt](https://github.com/coolsnowwolf/lede/files/4596711/log1.txt)
下面這個日誌是把2.4G下所有設定都刪除直接客戶端client連接時的日誌
[log3.txt](https://github.com/coolsnowwolf/lede/files/4596718/log3.txt)
下面的是4.14版內核的狀態與日誌
![WeChat圖片編輯_20200508103126](https://user-images.githubusercontent.com/16252372/81364250-c4305a80-9117-11ea-9c90-29015a5673c9.jpg)
![WeChat圖片編輯_20200508103205](https://user-images.githubusercontent.com/16252372/81364270-cc889580-9117-11ea-86ea-56a570ec3226.jpg)
[log4.txt](https://github.com/coolsnowwolf/lede/files/4596723/log4.txt)
以上兩個版本皆為自己編譯的除了內核以外其他設定都是R619AC缺省直設定
大概看了一下 跟我這邊不可以的差異在於他當做client的時候是沒加密的....

**Comment by AmadeusGhost** [comment]
凶啥啊，没有日志就几句话怎么分析问题
我今天全新编译的竞斗云固件中继也是正常的（kernel version 4.19.115）
![client](https://user-images.githubusercontent.com/42570690/81461710-43896100-91e0-11ea-9cea-5de68bca9f46.png)

**Comment by AmadeusGhost** [comment]
> 有圖有真相 上面的是4.19版內核的狀況還有日誌

这个日志还是之前的问题，理论上前几天的commit已修复，要不老哥你全新编译试下？
