### ISSUE TITLE
Netflix分流服务器 不起作用

### ISSUE THREAD

**Issue by yh1272000** [coolsnowwolf/lede#4537]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：我的奈飞不能用香港节点看，把美国节点设置为分流服务器没有作用，只能设置为主服务器才能正常观看。我买的机场美国节点少速度慢，香港节点多速度快，想看奈飞就要手动换节点，或设置美国节点为主服务器。是我的设置有问题吧？

### (2) 路由器型号和固件版本

A：OpenWrt R20.4.8 / LuCI Master (git-20.117.60969-420c61a)

### (3) 详细日志

A：

**Comment by lesliedu** [comment]
香港服务器不能看土耳其申请的Netflix了，，，，，，

**Comment by lynnial** [comment]
> 香港服务器不能看土耳其申请的Netflix了，，，，，，

正解，我让店家给换了hk的账号就能看了，土耳其价格太低店家估计要转战阿根廷了

**Comment by Ghost-yc** [comment]
把游戏udp分流设置成跟主服务器一样 然后再切换一下netflix分流服务器在保存应用就会好
