### ISSUE TITLE
网络防火墙的端口映射如何设置多端口或端口区间映射

### ISSUE THREAD

**Issue by xiaoweb** [coolsnowwolf/lede#4542]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
我想设置一台外网访问局域网内的机器，并且需要转发多个端口，一个一个设置太麻烦了，有没有批量设置或者填写端口区间的方法

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
j1900. 最新版lede

A：

### (3) 详细日志

A：

**Comment by badcrazy** [comment]
区间用-啊

**Comment by xiaoweb** [comment]
> 区间用-啊

你确定吗，我试过好像不行

**Comment by mjyhj** [comment]
10000-20000 25555 36666 48888

**Comment by xiaoweb** [comment]
> 10000-20000 25555 36666 48888

内网入口处填写呢?  如 我外网 5000-6000  -> 5000-6000;  这时候我外网访问 外网:5001 ,内网会对应到5001吗?  还是说路由会自己遍历端口依次走最先通的那个? 比如 5001 -> 5000, 这样?

**Comment by xiaoweb** [comment]
> 10000-20000 25555 36666 48888

如果是5001->5001 这样就很好,  就怕他是 5001->5000  5002->5000 5003->5000... 这样就坑了, 因为这样就算入口可以设置批量,但是lan还是要单独设置一条..
