### ISSUE TITLE
make -j$(($(nproc) + 1)) V=s  参数不懂是什么意思

### ISSUE THREAD

**Issue by jarodvip** [coolsnowwolf/lede#4549]
make -j$(($(nproc) + 1)) V=s   中间的参数是什么意思？如果我想多核心编译是否要写成make -j4 V=S 还是用make -j$(($(nproc) + 1)) V=s

**Comment by bluehj777** [comment]
$(nproc) 就是能自动计算出你用编译机器的内核线程数，比如你在你的编译机器上输入nproc回车看下，是不是返回数字是你的机器的线程数，假设你明确知道你的CPU是8核16线程的，你完全可以直接用make -j16 V=s

**Comment by martin0607** [comment]
自动线程数的意思。
如果你电脑是边编译边玩其他的，全线程编译会很卡，减少几个线程好了。。。空闲时编译么无所谓了。。

**Comment by jarodvip** [comment]
感谢各位大佬

**Comment by Fddh2012** [comment]
上网环境好的话，直接 make不香么？

**Comment by leungyauming** [comment]
如果已解決，請把這個issue關了。

**Comment by xpc0938** [comment]
> 上网环境好的话，直接 make不香么？
直接make默认相当于单线程编译编译速度慢且不打印详细的编译信息。多线程编译速度快，遇到编译错误后还是需要再次用单线程编译定位错误。无论加不加参数，各有各的道理，灵活运用才是好的选择

**Comment by bi4nbn** [comment]
直接make V=s  不惯着它
