### ISSUE TITLE
关于引用 Helloworld 的方式

### ISSUE THREAD

**Issue by yfdoor** [coolsnowwolf/lede#4555]
请教大家个问题，添加 helloworld：
git clone https://github.com/fw876/helloworld.git                 package/lean/luci-app-ssr-plus
或是 feeds.conf.default 定义 src-git helloworld https://github.com/fw876/helloworld

这两种不同的添加有什么区别吗？

**Comment by lloyd18** [comment]
第一个只用来编译，第二个还会把链接放到路由器的"软件包"“软件源”里，建议用第一个

**Comment by yfdoor** [comment]
> 第一个只用来编译，第二个还会把链接放到路由器的"软件包"“软件源”里，建议用第一个

这个是肯定的，可是好像makefile 编译是不是也不太一样。特别是po 本地化文件的过程？
