### ISSUE TITLE
（建议）SSR Plus + 插件能否根据不同设备使用的模式 

### ISSUE THREAD

**Issue by Pluto603** [coolsnowwolf/lede#4557]
大佬
能否在SSRPlus+里增加一个根据不同设备使用不同的翻墙的模式
例如 
电脑1使用全局模式 
PS4 使用大陆白名单模式
路由器使用GFW列表模式

能否实现这个功能呢
十分感谢！

**Comment by smallprogram** [comment]
+1

**Comment by codersluy** [comment]
来错地方了

**Comment by mjyhj** [comment]
不是可以设置IP来控制吗？
你自己不会静态分配吗

**Comment by kyle0363** [comment]
> 不是可以设置IP来控制吗？
> 你自己不会静态分配吗

静态ip可以分配 问题是不同设备使用不同模式
