### ISSUE TITLE
透明网桥模式下SSR+和passwall无法使用Trojan模式访问外网

### ISSUE THREAD

**Issue by 65308920** [coolsnowwolf/lede#4562]
当路由切换到透明网桥模式下，SSR+和Passwall都不能使用Trojan模式访问外网，但是如果切换到SS模式就可以访问外网。
最奇怪的是，如果我用插件自带的检查状态功能，显示外网连接正常，但是到了PC上，就是上不了外网。
我尝试了多个编译版本，都是这样的问题，难道Trojan的工作模式和透明网桥有冲突吗？

**Comment by 65308920** [comment]
已解决，原来是我设置问题，只要把主网关的DNS服务器IP指向软路由即可

**Comment by weige112233** [comment]
> 已解决，我设置问题，只要把主网关的DNS服务器IP指向软路由即可

教教我怎么设置，我也和你一样的问题
