### ISSUE TITLE
RT-ACRH17 切换了官方的无线驱动后还是有问题

### ISSUE THREAD

**Issue by king9039** [coolsnowwolf/lede#4563]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：刚开始有信号，能连上，连上后连接不到网络，再过一阵无线信号消失，然后再恢复，后面再来一阵网，但是网速很慢，最多只有2M出头，延迟很高，然后反复循环。

### (2) 路由器型号和固件版本

A：ASUS RT-ACRH17 
B：固件是7号凌晨拉的最新源码全新编译

### (3) 详细日志

[A：]

1. 
[系统.txt](https://github.com/coolsnowwolf/lede/files/4592784/default.txt)
[内核.txt](https://github.com/coolsnowwolf/lede/files/4592785/default.txt)

**Comment by He333** [comment]
同样的问题 新版本内核没多久到现在好多天了

**Comment by kai456789** [comment]
我是用CT的驅動 BT會掛掉 切回原廠驅動就正常  5號編譯的版本 5G沒問題

**Comment by yulin-li** [comment]
同样的问题，开机之后路由器间歇性重启。

**Comment by runsir** [comment]
同样的情况，已经刷回老版本了

**Comment by SinceZZFa** [comment]
今天的源码也炸裂

**Comment by yinzhefuyun** [comment]
更新后，再次重启路由器试一试

**Comment by fanck0605** [comment]
我似乎也有同样的问题，虽然我用的是rtl8821cu，具，似乎是更新了mac80211导致的。
