### ISSUE TITLE
刷写新的固件以后。frps启用就不勾选了，需要重新勾选保存

### ISSUE THREAD

**Issue by ITdesk01** [coolsnowwolf/lede#4572]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：刷写新的固件以后。frps启用就不勾选了，需要重新勾选保存

![捕获](https://user-images.githubusercontent.com/38835844/81464198-e8606a00-91f1-11ea-837b-d24e3f07b641.JPG)

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
已修复

**Comment by ITdesk01** [comment]
感谢大佬
