### ISSUE TITLE
rclone怎么设置开机自动挂载？？？？？

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#4579]
rclone已成功挂载，但是路由器重启后，又要重新输入挂载的命令，进行挂载。

怎么才能开机自动执行这条命令：rclone mount GoogleDrive:/ /mnt/sda1/连续剧/GoogleDrive --allow-other --allow-non-empty --vfs-cache-mode writes &

**Comment by jinjin327** [comment]
你挂载成功了吗？

**Comment by jinjin327** [comment]
为啥我挂载不成功

**Comment by jy3344511** [comment]
> 为啥我挂载不成功

https://rclone.org/install/


我没用自带的那个rclone，编译的时候，没编译进去，你试下单独安装rclone吧。
