### ISSUE TITLE
重启卡住在Synchronizing SCSI cache

### ISSUE THREAD

**Issue by Jefffish09** [coolsnowwolf/lede#4581]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
_当插上u盘，并挂在成功后，如果软重启（比如web端选择重启）则会卡住在Synchronizing SCSI cache，一直无法重启。当拔掉u盘，又可以正常重启了。_

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
_当插上u盘，并挂在成功后，如果软重启则会卡住在Synchronizing SCSI cache，一直无法重启。当拔掉u盘，又可以正常重启了。_

### (2) 路由器型号和固件版本

_固件是最新版，CPU是j1900的软路由_

### (3) 详细日志

_如图：_
![image](https://user-images.githubusercontent.com/44800122/81520173-21294c00-9376-11ea-9f11-877b82d2fe5e.png)

**Comment by Jefffish09** [comment]
在网上搜索了一下，不是我一个人的个例，也有人遇到过:
https://koolshare.cn/thread-154078-1-1.html
https://koolshare.cn/thread-152054-1-1.html
https://koolshare.cn/thread-134176-1-1.html
https://www.right.com.cn/forum/thread-3441794-1-1.html

**Comment by kenvix** [comment]
同样遇到了此问题，如果是近期构建的（默认内核版本 6.1），降级内核版本到 5.15 可以解决。

**Comment by shenqiming** [comment]
j1900工控机，U盘ventoy引导后，最系统安装到了 硬盘上，正常启动；reboot或者poweroff 也碰到 卡在Synchronizing SCSI cache， 搜了一圈无解，但是有人提到驱动还是bios兼容性可能。 然后在bios看到 OS selection，是windows7，选项里没有linux，遂由windows7改成windows8，故障不再重现，reboot，poweroff都正常了。类似问题的朋友，可以试试改或者linux等其他的选项，如果有的话。
