### ISSUE TITLE
竞斗云使用 ath10k-firmware-qca4019以及ct-htt驱动的wifi问题

### ISSUE THREAD

**Issue by zheshifandian** [coolsnowwolf/lede#4584]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：2.4gwifi和5gwifi只能打开其中一个
开2.4没5g，开5g没2.4
重启后两个wifi全部打开，但是不能修改其中任一，修改必爆掉另外一个

### (2) 路由器型号和固件版本

A：竞斗云2.0-r619ac+最新源码

### (3) 详细日志

A：
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.176 (zheshifandian@HP-Pavilion-15) (gcc version 7.5.0 (OpenWrt GCC 7.5.0 r2534-d9704c2b)) #0 SMP Sun May 10 02:19:36 2020
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: P&W R619AC 128M
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 130560
[    0.000000] free_area_init_node: node 0, pgdat c0a279c0, node_mem_map dfb79000
[    0.000000]   Normal zone: 1152 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 130560 pages, LIFO batch:31
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x3e8 with crng_init=0
[    0.000000] percpu: Embedded 15 pages/cpu s29196 r8192 d24052 u61440
[    0.000000] pcpu-alloc: s29196 r8192 d24052 u61440 alloc=15*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129408
[    0.000000] Kernel command line: ubi.mtd=rootfs root=mtd:rootfs rootfstype=squashfs rootwait root=/dev/ubiblock0_1 rootfstype=squashfs
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 509312K/522240K available (4590K kernel code, 160K rwdata, 1240K rodata, 1024K init, 225K bss, 12928K reserved, 0K cma-reserved, 0K highmem)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xe0800000 - 0xff800000   ( 496 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
[    0.000000]     pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
[    0.000000]     modules : 0xbf000000 - 0xbfe00000   (  14 MB)
[    0.000000]       .text : 0xc0208000 - 0xc077b868   (5583 kB)
[    0.000000]       .init : 0xc0900000 - 0xc0a00000   (1024 kB)
[    0.000000]       .data : 0xc0a00000 - 0xc0a282c0   ( 161 kB)
[    0.000000]        .bss : 0xc0a2a000 - 0xc0a62598   ( 226 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 48.00MHz (virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xb11fd3bfb, max_idle_ns: 440795203732 ns
[    0.000007] sched_clock: 56 bits at 48MHz, resolution 20ns, wraps every 4398046511096ns
[    0.000024] Switching to timer-based delay loop, resolution 20ns
[    0.000245] Calibrating delay loop (skipped), value calculated using timer frequency.. 96.00 BogoMIPS (lpj=480000)
[    0.000265] pid_max: default: 32768 minimum: 301
[    0.000434] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.000451] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.001216] CPU: Testing write buffer coherency: ok
[    0.001981] Setting up static identity map for 0x80300000 - 0x80300060
[    0.002132] Hierarchical SRCU implementation.
[    0.002818] smp: Bringing up secondary CPUs ...
[    0.005666] smp: Brought up 1 node, 4 CPUs
[    0.005687] SMP: Total of 4 processors activated (384.00 BogoMIPS).
[    0.005695] CPU: All CPU(s) started in SVC mode.
[    0.010301] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.010459] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.010484] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.010735] pinctrl core: initialized pinctrl subsystem
[    0.011652] NET: Registered protocol family 16
[    0.011988] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.013030] cpuidle: using governor ladder
[    0.013077] cpuidle: using governor menu
[    0.031598] usbcore: registered new interface driver usbfs
[    0.031664] usbcore: registered new interface driver hub
[    0.031749] usbcore: registered new device driver usb
[    0.031815] pps_core: LinuxPPS API ver. 1 registered
[    0.031825] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.031853] PTP clock support registered
[    0.033154] clocksource: Switched to clocksource arch_sys_counter
[    0.034053] NET: Registered protocol family 2
[    0.034661] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.034724] TCP bind hash table entries: 4096 (order: 3, 32768 bytes)
[    0.034814] TCP: Hash tables configured (established 4096 bind 4096)
[    0.034934] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.034970] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.035175] NET: Registered protocol family 1
[    0.035227] PCI: CLS 0 bytes, default 64
[    0.036924] No memory allocated for crashlog
[    0.037100] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.041176] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.041191] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.045958] io scheduler noop registered
[    0.045977] io scheduler deadline registered (default)
[    0.047849] OF: PCI: host bridge /soc/pci@40000000 ranges:
[    0.047885] OF: PCI:    IO 0x40200000..0x402fffff -> 0x40200000
[    0.047905] OF: PCI:   MEM 0x40300000..0x40ffffff -> 0x40300000
[    1.111054] qcom-pcie 40000000.pci: phy link never came up
[    1.112627] qcom-pcie 40000000.pci: cannot initialize host
[    1.112731] qcom-pcie: probe of 40000000.pci failed with error -110
[    1.114265] bam-dma-engine 8e04000.dma: num-channels unspecified in dt
[    1.114282] bam-dma-engine 8e04000.dma: num-ees unspecified in dt
[    1.115557] tcsr 1949000.tcsr: setting wifi_glb_cfg = 41000000
[    1.115652] tcsr 194b000.tcsr: setting usb hs phy mode select = e700e7
[    1.115728] tcsr 1953000.ess_tcsr: setting ess interface select = 0
[    1.115802] tcsr 1957000.tcsr: setting wifi_noc_memtype_m0_m2 = 2222222
[    1.116462] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    1.117043] msm_serial 78af000.serial: msm_serial: detected port #0
[    1.117091] msm_serial 78af000.serial: uartclk = 1843200
[    1.117144] 78af000.serial: ttyMSM0 at MMIO 0x78af000 (irq = 27, base_baud = 115200) is a MSM
[    1.117169] msm_serial: console setup on port #0
[    1.666407] console [ttyMSM0] enabled
[    1.671327] msm_serial: driver initialized
[    1.679185] loop: module loaded
[    1.680431] nand: device found, Manufacturer ID: 0x01, Chip ID: 0xf1
[    1.681655] nand: AMD/Spansion S34ML01G1
[    1.688315] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    1.692206] 1 fixed-partitions partitions found on MTD device qcom_nand.0
[    1.699562] Creating 1 MTD partitions on "qcom_nand.0":
[    1.706423] 0x000000000000-0x000008000000 : "rootfs"
[    1.732957] random: fast init done
[    1.886851] mtd: device 0 (rootfs) set to be root filesystem
[    1.887446] mtdsplit: no squashfs found in "rootfs"
[    1.892137] spi_qup 78b5000.spi: IN:block:16, fifo:64, OUT:block:16, fifo:64
[    1.905803] m25p80 spi0.0: w25q128 (16384 Kbytes)
[    1.905857] 3 fixed-partitions partitions found on MTD device spi0.0
[    1.909486] Creating 3 MTD partitions on "spi0.0":
[    1.915942] 0x000000000000-0x000000170000 : "Bootloader"
[    1.921238] 0x000000170000-0x000000180000 : "ART"
[    1.926605] 0x000000180000-0x000001000000 : "unused"
[    1.931953] libphy: ipq40xx_mdio: probed
[    1.966685] ESS reset ok!
[    1.999654] ESS reset ok!
[    2.418173] libphy: Fixed MDIO Bus: probed
[    2.421464] i2c /dev entries driver
[    2.423649] sdhci: Secure Digital Host Controller Interface driver
[    2.424546] sdhci: Copyright(c) Pierre Ossman
[    2.430795] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.435683] sdhci_msm 7824900.sdhci: core clock boost failed
[    2.503867] mmc0: SDHCI controller on 7824900.sdhci [7824900.sdhci] using ADMA 64-bit
[    2.514621] NET: Registered protocol family 10
[    2.518425] Segment Routing with IPv6
[    2.518565] NET: Registered protocol family 17
[    2.524279] 8021q: 802.1Q VLAN Support v1.8
[    2.526185] Registering SWP/SWPB emulation handler
[    2.536638] ubi0: attaching mtd0
[    3.685628] random: crng init done
[    3.825758] ubi0: scanning is finished
[    3.839013] ubi0 warning: ubi_eba_init: cannot reserve enough PEBs for bad PEB handling, reserved 10, need 20
[    3.840031] ubi0: attached mtd0 (name "rootfs", size 128 MiB)
[    3.847938] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    3.853661] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    3.860407] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    3.867297] ubi0: good PEBs: 1024, bad PEBs: 0, corrupted PEBs: 0
[    3.874056] ubi0: user volume: 3, internal volumes: 1, max. volumes count: 128
[    3.880289] ubi0: max/mean erase counter: 2/0, WL threshold: 4096, image sequence number: 1589157979
[    3.887429] ubi0: available PEBs: 0, total reserved PEBs: 1024, PEBs reserved for bad PEB handling: 10
[    3.896740] ubi0: background thread "ubi_bgt0d" started, PID 81
[    3.898010] block ubiblock0_1: created from ubi0:1(rootfs)
[    3.911636] hctosys: unable to open rtc device (rtc0)
[    3.924583] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    3.926198] Freeing unused kernel memory: 1024K
[    4.354407] init: Console is alive
[    4.354645] init: - watchdog -
[    5.479128] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    5.566385] exFAT: Version 1.2.9
[    5.587019] SCSI subsystem initialized
[    5.882869] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    5.883045] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
[    5.887976] xhci-hcd xhci-hcd.0.auto: hcc params 0x0228f665 hci version 0x100 quirks 0x0000000002010010
[    5.894932] xhci-hcd xhci-hcd.0.auto: irq 129, io mem 0x08a00000
[    5.905768] hub 1-0:1.0: USB hub found
[    5.910495] hub 1-0:1.0: 1 port detected
[    5.914483] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    5.918104] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
[    5.923461] xhci-hcd xhci-hcd.0.auto: Host supports USB 3.0  SuperSpeed
[    5.931080] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    5.938134] hub 2-0:1.0: USB hub found
[    5.946000] hub 2-0:1.0: 1 port detected
[    5.949850] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    5.953576] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 3
[    5.959048] xhci-hcd xhci-hcd.1.auto: hcc params 0x0220f665 hci version 0x100 quirks 0x0000000002010010
[    5.966456] xhci-hcd xhci-hcd.1.auto: irq 130, io mem 0x06000000
[    5.976444] hub 3-0:1.0: USB hub found
[    5.982033] hub 3-0:1.0: 1 port detected
[    5.985907] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    5.989633] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 4
[    5.994973] xhci-hcd xhci-hcd.1.auto: Host supports USB 3.0  SuperSpeed
[    6.002589] usb usb4: We don't know the algorithms for LPM for this host, disabling LPM.
[    6.011743] hub 4-0:1.0: USB hub found
[    6.021423] hub 4-0:1.0: config failed, hub doesn't have any ports! (err -19)
[    6.026579] usbcore: registered new interface driver usb-storage
[    6.029233] usbcore: registered new interface driver uas
[    6.034483] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    6.044694] init: - preinit -
[    7.802269] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    7.802430] IPv6: ADDRCONF(NETDEV_UP): eth0.1: link is not ready
[    7.807267] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.1: link becomes ready
[    8.793943] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   11.076733] mount_root: loading kmods from internal overlay
[   11.099741] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[   11.100963] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[   11.848581] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 182
[   11.919134] UBIFS (ubi0:2): recovery needed
[   12.607994] UBIFS (ubi0:2): recovery completed
[   12.608140] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs_data"
[   12.611341] UBIFS (ubi0:2): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   12.619293] UBIFS (ubi0:2): FS size: 89772032 bytes (85 MiB, 707 LEBs), journal size 4444160 bytes (4 MiB, 35 LEBs)
[   12.629177] UBIFS (ubi0:2): reserved for root: 4240154 bytes (4140 KiB)
[   12.639403] UBIFS (ubi0:2): media format: w4/r0 (latest is w5/r0), UUID 0D469FDC-1FA9-4B5C-B851-9A38BE153122, small LPT model
[   12.646816] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   12.661282] block: extroot: not configured
[   12.743192] UBIFS (ubi0:2): un-mount UBI device 0
[   12.744275] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops
[   12.753674] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 183
[   12.908338] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs_data"
[   12.908379] UBIFS (ubi0:2): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   12.915198] UBIFS (ubi0:2): FS size: 89772032 bytes (85 MiB, 707 LEBs), journal size 4444160 bytes (4 MiB, 35 LEBs)
[   12.925092] UBIFS (ubi0:2): reserved for root: 4240154 bytes (4140 KiB)
[   12.935325] UBIFS (ubi0:2): media format: w4/r0 (latest is w5/r0), UUID 0D469FDC-1FA9-4B5C-B851-9A38BE153122, small LPT model
[   12.948155] mount_root: loading kmods from internal overlay
[   12.972100] kmodloader: loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[   12.975677] kmodloader: done loading kernel modules from /tmp/overlay/upper/etc/modules-boot.d/*
[   13.533038] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   13.539062] block: extroot: not configured
[   13.605798] mount_root: switching to ubifs overlay
[   13.658723] urandom-seed: Seeding with /etc/urandom.seed
[   13.849953] procd: - early -
[   13.850090] procd: - watchdog -
[   14.568777] procd: - watchdog -
[   14.569581] procd: - ubus -
[   14.698978] procd: - init -
[   15.403857] kmodloader: loading kernel modules from /etc/modules.d/*
[   15.410179] urngd: v1.0.2 started.
[   15.411374] NET: Registered protocol family 38
[   15.428134] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   15.432949] Netfilter messages via NETLINK v0.30.
[   15.434711] ip_set: protocol 6
[   15.457582] cryptodev: driver 1.10 loaded.
[   15.462072] fuse init (API version 7.26)
[   15.466476] Loading modules backported from Linux version v5.4.27-0-g585e0cc08069
[   15.466510] Backport generated by backports.git v5.4.27-1-0-gf6e8852f
[   15.476671] ip_tables: (C) 2000-2006 Netfilter Core Team
[   15.488883] nf_conntrack version 0.5.0 (8192 buckets, 32768 max)
[   15.527778] ctnetlink v0.93: registering with nfnetlink.
[   15.577898] usbcore: registered new interface driver ums-alauda
[   15.579342] usbcore: registered new interface driver ums-cypress
[   15.584130] usbcore: registered new interface driver ums-datafab
[   15.590220] usbcore: registered new interface driver ums-freecom
[   15.596485] usbcore: registered new interface driver ums-isd200
[   15.602401] usbcore: registered new interface driver ums-jumpshot
[   15.607911] usbcore: registered new interface driver ums-karma
[   15.614550] usbcore: registered new interface driver ums-sddr09
[   15.620015] usbcore: registered new interface driver ums-sddr55
[   15.626093] usbcore: registered new interface driver ums-usbat
[   15.647303] xt_time: kernel timezone is -0000
[   15.692872] PPP generic driver version 2.4.2
[   15.694171] PPP MPPE Compression module registered
[   15.697431] NET: Registered protocol family 24
[   15.898870] ath10k_ahb a000000.wifi: Direct firmware load for ath10k/QCA4019/hw1.0/firmware-6.bin 
[   15.898919] ath10k_ahb a000000.wifi: Load Wireless ART files
[   22.302985] firmware ath10k!QCA4019!hw1.0!firmware-6.bin: firmware_loading_store: map pages failed
[   22.623579] ath10k_ahb a000000.wifi: qca4019 hw1.0 target 0x01000000 chip_id 0x003b00ff sub 0000:0000
[   22.623625] ath10k_ahb a000000.wifi: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   22.635502] ath10k_ahb a000000.wifi: firmware ver 10.4-3.6-00140 api 5 features no-p2p,mfp,peer-flow-ctrl,btcoex-param,allows-mesh-bcast,no-ps crc32 ba79b746
[   22.681730] ath10k_ahb a000000.wifi: board_file api 2 bmi_id 0:16 crc32 6ce1f887
[   24.053821] ath10k_ahb a000000.wifi: unsupported HTC service id: 1536
[   24.115057] ath10k_ahb a000000.wifi: htt-ver 2.2 wmi-op 6 htt-op 4 cal pre-cal-file max-sta 512 raw 0 hwcrypto 1
[   24.137691] ath: EEPROM regdomain: 0x0
[   24.137715] ath: EEPROM indicates default country code should be used
[   24.137728] ath: doing EEPROM country->regdmn map search
[   24.137752] ath: country maps to regdmn code: 0x3a
[   24.137767] ath: Country alpha2 being used: US
[   24.137780] ath: Regpair used: 0x3a
[   24.327243] ath10k_ahb a800000.wifi: Direct firmware load for ath10k/QCA4019/hw1.0/firmware-6.bin 
[   24.327298] ath10k_ahb a800000.wifi: Load Wireless ART files
[   24.861447] firmware ath10k!QCA4019!hw1.0!firmware-6.bin: firmware_loading_store: map pages failed
[   24.861760] ath10k_ahb a800000.wifi: qca4019 hw1.0 target 0x01000000 chip_id 0x003b00ff sub 0000:0000
[   24.869426] ath10k_ahb a800000.wifi: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   24.884179] ath10k_ahb a800000.wifi: firmware ver 10.4-3.6-00140 api 5 features no-p2p,mfp,peer-flow-ctrl,btcoex-param,allows-mesh-bcast,no-ps crc32 ba79b746
[   24.927786] ath10k_ahb a800000.wifi: board_file api 2 bmi_id 0:17 crc32 6ce1f887
[   26.288851] ath10k_ahb a800000.wifi: unsupported HTC service id: 1536
[   26.348495] ath10k_ahb a800000.wifi: htt-ver 2.2 wmi-op 6 htt-op 4 cal pre-cal-file max-sta 512 raw 0 hwcrypto 1
[   26.407111] ath: EEPROM regdomain: 0x0
[   26.407194] ath: EEPROM indicates default country code should be used
[   26.407242] ath: doing EEPROM country->regdmn map search
[   26.407332] ath: country maps to regdmn code: 0x3a
[   26.407392] ath: Country alpha2 being used: US
[   26.407442] ath: Regpair used: 0x3a
[   26.450733] kmodloader: done loading kernel modules from /etc/modules.d/*
[   31.342633] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   31.345588] device eth0 entered promiscuous mode
[   31.347879] br-lan: port 1(eth0.1) entered blocking state
[   31.352160] br-lan: port 1(eth0.1) entered disabled state
[   31.358008] device eth0.1 entered promiscuous mode
[   31.365340] br-lan: port 1(eth0.1) entered blocking state
[   31.367543] br-lan: port 1(eth0.1) entered forwarding state
[   31.373266] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   32.252407] ath: EEPROM regdomain: 0x8024
[   32.252417] ath: EEPROM indicates we should expect a country code
[   32.252422] ath: doing EEPROM country->regdmn map search
[   32.252426] ath: country maps to regdmn code: 0x3b
[   32.252435] ath: Country alpha2 being used: AU
[   32.252439] ath: Regpair used: 0x3b
[   32.252446] ath: regdomain 0x8024 dynamically updated by user
[   32.252477] ath: EEPROM regdomain: 0x8024
[   32.252485] ath: EEPROM indicates we should expect a country code
[   32.252494] ath: doing EEPROM country->regdmn map search
[   32.252503] ath: country maps to regdmn code: 0x3b
[   32.252508] ath: Country alpha2 being used: AU
[   32.252511] ath: Regpair used: 0x3b
[   32.252516] ath: regdomain 0x8024 dynamically updated by user
[   32.393257] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   32.394184] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   35.035725] ath10k_ahb a000000.wifi: unsupported HTC service id: 1536
[   35.198103] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   35.203652] br-lan: port 2(wlan0) entered blocking state
[   35.203710] br-lan: port 2(wlan0) entered disabled state
[   35.208801] device wlan0 entered promiscuous mode
[   35.590156] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   35.590373] br-lan: port 2(wlan0) entered blocking state
[   35.595639] br-lan: port 2(wlan0) entered forwarding state
[  237.722425] device wlan0 left promiscuous mode
[  237.722587] br-lan: port 2(wlan0) entered disabled state
[  237.776025] ath10k_ahb a000000.wifi: peer-unmap-event: unknown peer id 1
[  237.776115] ath10k_ahb a000000.wifi: peer-unmap-event: unknown peer id 1
[  239.974112] ath10k_ahb a800000.wifi: unsupported HTC service id: 1536
[  240.099459] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[  240.102954] br-lan: port 2(wlan1) entered blocking state
[  240.104196] br-lan: port 2(wlan1) entered disabled state
[  240.110069] device wlan1 entered promiscuous mode
[  240.612431] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[  240.612945] br-lan: port 2(wlan1) entered blocking state
[  240.617909] br-lan: port 2(wlan1) entered forwarding state

**Comment by garygary1** [comment]
遇到了同样问题。

**Comment by Hey-Leo** [comment]
极路由HC5962也有问题，会出现无线未关联
