### ISSUE TITLE
wdr7500v3刷5月4日固件不能存储配置，重启就复位

### ISSUE THREAD

**Issue by song3108song** [coolsnowwolf/lede#4591]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue
说是在/overlay/work/work/里有残留文件
## 2. 详细叙述
断电后即复位，不能存储配置
### (1) 具体问题

A：断电后即复位，不能存储配置

### (2) 路由器型号和固件版本

A：wdr7500v3，固件是在恩山论坛中帖子提供的蓝奏云下载的，看时间是5月4日22点39
生成。
### (3) 详细日志

A：没留日志

**Comment by 9l** [comment]
那问错地方咯，去问问恩山发固件的个人吧

**Comment by song3108song** [comment]
谢谢你

**Comment by lydasia** [comment]
固件太大了吧，没空间放config，实际上是放在了ram里
