### ISSUE TITLE
关于make config的问题

### ISSUE THREAD

**Issue by Zeezorn** [coolsnowwolf/lede#4593]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：今天（2020.5.12）git pull了一下源码，并且更新了feeds，随后make config发现界面变成逐条项目询问，似乎每条内容都要过一遍，可能有几百条，其中有很多内容并不是很懂，中途就CTRL+C了。如果单独编译一个ipk，只要修改了target system就要全部逐条过一遍，实在繁琐。请问是我的问题，还是有意将make config的配置方法更改了？如果是有意修改了make config的配置方式，在单独编译ipk的情况下，这种新方式是否有简易的配置方法？谢谢。

### (2) 路由器型号和固件版本

A：None

### (3) 详细日志

A：None

**Comment by Zeezorn** [comment]
附上图一张
![1](https://user-images.githubusercontent.com/31385055/81655882-26b38e80-9469-11ea-9c4b-12a4dad37bb5.png)

**Comment by EnnawYang** [comment]
Why not try `make menuconfig`

**Comment by Zeezorn** [comment]
sorry，突然发现这个问题问的好无聊，close~
