### ISSUE TITLE
DDNS变成默认组件了？

### ISSUE THREAD

**Issue by DanielChen008** [coolsnowwolf/lede#4597]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：之前没有留意，最近编译的版本发现启动项里默认就有DDNS了，在软件包里搜索ddns也发现默认已经安装了三个相关的脚本。我重新编译过几次，百分百确定及肯定，我取消了DDNS的默认选中。

### (2) 路由器型号和固件版本

A：x86 软路由
### (3) 详细日志

A：无

**Comment by hplee0120** [comment]
一样的问题，编译时不选ddns，照样有ddns-scripts，ddns-scripts_aliyun，ddns-scripts_dnspod。这三个软件包。

**Comment by lxwq** [comment]
看一下incloud/target.mk

**Comment by EnnawYang** [comment]
选的时候取消luci-app-ddns和这三个脚本不就行了？

**Comment by 9l** [comment]
那几个 ddns-scripts 需要单独取消

**Comment by hcym** [comment]
target和各个设备目录下maker，就这两个地方需要改成自己的，尤其是x86和icq的，默认设置很多插件，

**Comment by DanielChen008** [comment]
> 这几个东西需要自己在Network--IP Addresses and Names里面自己取消勾选

感谢，知道原因并验证了！
