### ISSUE TITLE
【谷歌】连通性检查 失败

### ISSUE THREAD

**Issue by leeivan** [coolsnowwolf/lede#4603]
编译后，【谷歌】连通性检查 失败，ShadowSocksR Plus+ 显示运行中，服务器自建v2ray节点连接OK。使用chrome连接google，显示：
DNS_PROBE_FINISHED_NO_INTERNET
连接国内地址正常
尝试手动重启ShadowSocksR Plus+，也无法解决。

**Comment by DanielChen008** [comment]
我昨晚编译就遇到了，搞了2个多小时才找到原因！
我猜你的梯子也是 v2ray ？ 如果是 v2ray 的话，helloworld 默认把 v2ray 添加节点设置里的Camouflage Type 启用了，默认是 HTTP，改成“无”即可。

**Comment by leeivan** [comment]
没错，修复。多谢 @DanielChen008
