### ISSUE TITLE
SSR+是否可以在DNS模式里添加“不使用”选项

### ISSUE THREAD

**Issue by Peterfire** [coolsnowwolf/lede#4604]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
我的网络环境有点复杂，刷了Openwrt得路由器主要作用是代理，但是DNS是通过内部DNS服务器进行解析，所以希望SSR+得DNS模式上可以选择“不使用”模式，以便于我指定DNS解析走向自己得DNS服务器，希望大佬能解惑，感谢。

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by martin0607** [comment]
那就自定义到自己的IP啊

**Comment by ZqinKing** [comment]
可以分流的dnsmap里设置上有dns服务器为你自建DNS服务器即可。ssr+只有走ssr的域名它才解析
