### ISSUE TITLE
k3编译报错麻烦大佬们看下

### ISSUE THREAD

**Issue by zjh1982** [coolsnowwolf/lede#4607]
Makefile:327: recipe for target '/home/zzx/lede/build_dir/hostpkg/go-1.14/.built' failed
make[3]: *** [/home/zzx/lede/build_dir/hostpkg/go-1.14/.built] Error 1
make[3]: Leaving directory '/home/zzx/lede/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#9.35#4.09#7.59
package/Makefile:111: recipe for target 'package/feeds/packages/golang/host/compile' failed
make[2]: *** [package/feeds/packages/golang/host/compile] Error 2
make[2]: Leaving directory '/home/zzx/lede'
package/Makefile:107: recipe for target '/home/zzx/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/zzx/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zzx/lede'
/home/zzx/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by pmxEr5lZwZ** [comment]
@zjh1982 解决了吗？求分享
