### ISSUE TITLE
4.14.48/R7.7.4 随机断流情况

### ISSUE THREAD

**Issue by digiw** [coolsnowwolf/lede#461]
反馈大雕，原以为k3过热，改散热降低到50度后任有随机断流情况，无意中去菜单：网络--负载均衡 里面，把默认配置的接口和成员都删除后，断流情况消失

**Comment by xzchsia** [comment]
我的是这个版本的K2 的自己编译的，也会出现闪断的情况。

**Comment by digiw** [comment]
@xzchsia 你可以试试我提到的在“负载均衡”里的设置，看这样能否能临时解决闪断问题？

**Comment by xzchsia** [comment]
好的，谢谢，回头回去试试， @digiw
