### ISSUE TITLE
老大！能不能出一版默认支持ipv6的

### ISSUE THREAD

**Issue by zsl722** [coolsnowwolf/lede#4618]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
自己编

**Comment by Michaol** [comment]
好意思这样问嘛？大餐都上好了，还要求喂到嘴里？

**Comment by zsl722** [comment]
小白一个，不会。就是问一下，如果不可以也无所谓！

**Comment by Michaol** [comment]
> 小白一个，不会。就是问一下，如果不可以也无所谓！

先习惯翻一下之前的issue和google一下，都是非常基础的配置。另外这里从来不会放固件的，都是大家按需编译。如果不会编译，要么慢慢学习，要么直接下其他人编译好的。

**Comment by zsl722** [comment]
ok
