### ISSUE TITLE
请把frpc的privilege_token改为token

### ISSUE THREAD

**Issue by ikaroscn** [coolsnowwolf/lede#463]
frp从0.10.0已经开始把privilege_token参数改为token，还不能向后兼容
https://github.com/fatedier/frp#authentication

**Comment by MxCen** [comment]
自己到代码中：lede/package/lean/luci-app-frpc/root/etc/init.d/frp
里面，吧倒数第二个privilege_token参数改为token，编译就可以了~

**Comment by ikaroscn** [comment]
我已经改了编译了，没问题的，是想让别人不会为了这个问题所困扰

**Comment by MxCen** [comment]
7.1日，L大已经更新了。重新GIT就行了~
