### ISSUE TITLE
Insufficient permissions to read UCI configuration.

### ISSUE THREAD

**Issue by PoorerImmune** [coolsnowwolf/lede#4631]
本人使用 x86 的編譯版本，裝到軟路由上後想變更介面語言，於是我額外安裝了語系套件並在 Luci 介面中作了語言切換。之後使用 reboot 指令重新啟動系統，再次進入 Luci 後，有諸多分頁提示
> Insufficient permissions to read UCI configuration.
![image](https://user-images.githubusercontent.com/48857142/82320596-1de13080-9a06-11ea-82cc-792947964a1b.png)
我在網上找了與此相關的問題，但都沒有可靠的解決方案。之後我又把剛安裝的語系套件全部移除，問題依舊。這是不是一個 BUG？如何解決？

**Comment by coolsnowwolf** [comment]
官方的luci 部件需要权限

**Comment by tpunix** [comment]
出现这种问题怎样解决呢?
不从"可用软件包"那里安装任何软件包?
只能重新编译时选择希望的包?

**Comment by PoorerImmune** [comment]
> 出现这种问题怎样解决呢?
> 不从"可用软件包"那里安装任何软件包?
> 只能重新编译时选择希望的包?

這個版本的韌體要麼在編譯時先裝好你所需要的套件，要麼你自己在編譯完成後到軟體倉庫網頁手動下載並安裝所需套件。倘若你透過路由器後台的「軟體包」自動安裝便會發生圖中的例外狀況，修復起來很麻煩，只能重新刷一遍韌體。如果你用 OpenWrt 官方網站提供的韌體則完全不會有這個問題。
