### ISSUE TITLE
请教如何通过CLI 对SSR+ 配置？

### ISSUE THREAD

**Issue by matthuo333** [coolsnowwolf/lede#4633]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
如题，具体是如何通过CLI添加vmess链接、如何修改v2ray配置、如何切换代理点、以及切换后是否成功怎么确定？
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hcym** [comment]
看看目录结构，我都是提前改好再编译，

**Comment by matthuo333** [comment]
> 看看目录结构，我都是提前改好再编译，

但我这实际需要在运营中，变化代理配置，不可能现编译

**Comment by coolsnowwolf** [comment]
可以通过 uci 命令配置

**Comment by matthuo333** [comment]
> 可以通过 uci 命令配置

求大神具体教程
