### ISSUE TITLE
frp占用内存太大？

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#464]
PID       PPID     USER     STAT   VSZ       %VSZ     %CPU     COMMAND
1984     1          root       S          777m    154%      0%         /usr/bin/frpc -c /var/etc/frp/frpc.conf

**Comment by mmd1989** [comment]
Frp运行时间长了是有内存问题

**Comment by LGA1150** [comment]
VSZ 是程序申请的内存，实际上没有那么多
