### ISSUE TITLE
lan口数据包计数数量溢出，导致路由器网络奇慢

### ISSUE THREAD

**Issue by msn1983aa** [coolsnowwolf/lede#4652]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：因为使用了京东云、挂PT等数据量比较大，每隔半个月左右，就会出现lan口统计数据的数据包计数溢出变为负数，此时网络里的设备就会上网超级慢，或者直接断网。

### (2) 路由器型号和固件版本

A：软路由，配置为：J1900+2G+16Gmsata
固件版本：OpenWrt R20.2.15 GDQ IPv4 v3.1[2020] Compiled by eSir / LuCI Master (git-20.058.13156-2faf063)
内核版本 | 4.19.106

### (3) 详细日志

A：
<img src="https://tvax4.sinaimg.cn/large/59236ca5gy1gf15yhrp84j20ko050wfm.jpg" alt="QQ20200522-111404@2x" width="744" data-width="744" data-height="180">

**Comment by hxlls** [comment]
走错门了把，你这种魔改固件不应该找作者么？

**Comment by msn1983aa** [comment]
> 走错门了把，你这种魔改固件不应该找作者么？

esir这个固件没有改，就是加了些软件包直接编译出来的

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/82637250-f0c79480-9c36-11ea-956f-92be95dc7ed5.png)
不改？版本号都改了。。明摆着啊其他还做了什么改就更不用说了

**Comment by coolsnowwolf** [comment]
居然有这个现象？

**Comment by msn1983aa** [comment]
> 居然有这个现象？

因为1月份挂上京东云之后一直上传比较猛（每天100G以上），所以遇到几次了，玩pt或者挂京东云的人应该会遇到，之前19.x版本的时候也有这样的现象。

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/82647255-84559100-9c48-11ea-87b4-28391883363a.png)
![image](https://user-images.githubusercontent.com/43886952/82647385-b5ce5c80-9c48-11ea-9358-dd10287fc7ac.png)

我的一天就过T流量，也没这个问题，这问题真不是这个源码问题

**Comment by msn1983aa** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/82647255-84559100-9c48-11ea-87b4-28391883363a.png)
> ![image](https://user-images.githubusercontent.com/43886952/82647385-b5ce5c80-9c48-11ea-9358-dd10287fc7ac.png)
> 
> 我的一天就过T流量，也没这个问题，这问题真不是这个源码问题

厉害了，您这是数据中心么，这么大流量

**Comment by doumeki** [comment]
> 走错门了把，你这种魔改固件不应该找作者么？
魔改作者和lean可是有PY交易的哦 :)))))))))

**Comment by mjyhj** [comment]
我也出现过一次负数，但是网络好像没问题

**Comment by ElectronicElephant** [comment]
> 
> 
> 居然有这个现象？

可以肯定确实存在统计变负数的现象，我也遇到过，但是网络应该没有问题的。

**Comment by Her0R0cket** [comment]
OpenWrt R20.5.9
![批注 2020-06-04 104814](https://user-images.githubusercontent.com/33145975/83709489-447fa800-a651-11ea-9743-47a7bea55a9c.png)
下挂两个限速玩客云,虽然有负数,但网速没问题.
看看内核日志有没有什么报错

**Comment by msn1983aa** [comment]
> OpenWrt R20.5.9
> ![批注 2020-06-04 104814](https://user-images.githubusercontent.com/33145975/83709489-447fa800-a651-11ea-9743-47a7bea55a9c.png)
> 下挂两个限速玩客云,虽然有负数,但网速没问题.
> 看看内核日志有没有什么报错

您还在挂玩客云啊？项目都死掉了，我都只做下载机用了

**Comment by Her0R0cket** [comment]
> 
> 
> > OpenWrt R20.5.9
> > ![批注 2020-06-04 104814](https://user-images.githubusercontent.com/33145975/83709489-447fa800-a651-11ea-9743-47a7bea55a9c.png)
> > 下挂两个限速玩客云,虽然有负数,但网速没问题.
> > 看看内核日志有没有什么报错
> 
> 您还在挂玩客云啊？项目都死掉了，我都只做下载机用了

我好几个月没看过了,看到有上传就没管了,没想到都废了
