### ISSUE TITLE
GL-MV1000支持（Openwrt官方已支持）

### ISSUE THREAD

**Issue by CWZ7605** [coolsnowwolf/lede#4653]
设备型号：GL-MV1000
Openwrt官方已支持
请及时更新设备清单列表

官方链接：https://openwrt.org/toh/gl.inet/gl.inet_gl-mv1000_brume
官方固件链接：https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa53/

感谢！

**Comment by coolsnowwolf** [comment]
欢迎发 PR

**Comment by lqhorochi** [comment]
GL-MV1000太贵了,买不起,这个价格干脆上软路由

**Comment by CWZ7605** [comment]
搞了一周，愣是没搞成功。作为一个萌新小白，我还需要再努力，让大神见笑了（手动掩面哭

**Comment by Aes64X** [comment]
被同价格x86暴打。。。。。

**Comment by CWZ7605** [comment]
> 
> 
> 被同价格x86暴打。。。。。

同价格x86的体积被吊打

**Comment by shu0802** [comment]
GL的坑有点大，我用https://github.com/gl-inet/openwrt这个编译GL-E750的固件总是出错，反应了也没有人理会

**Comment by shu0802** [comment]
GL的坑有点大，我用 https://github.com/gl-inet/openwrt  这个编译GL-E750的固件总是出错，反应了也没有人理会
