### ISSUE TITLE
编译组件包引用冲突

### ISSUE THREAD

**Issue by bigbugcc** [coolsnowwolf/lede#4655]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：kmod-ath10k和kmod-ath10k-ct组件包冲突

### (2) 路由器型号和固件版本

A：树莓派4B 

### (3) 详细日志

A：Collected errors:
 * check_data_file_clashes: Package kmod-ath10k-ct-smallbuffers wants to install file /home/bigbug/WorkSpace/lede/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/lib/modules/4.19.122/ath10k_core.ko
	But that file is already provided by package  * kmod-ath10k-ct
 * check_data_file_clashes: Package kmod-ath10k-ct-smallbuffers wants to install file /home/bigbug/WorkSpace/lede/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/lib/modules/4.19.122/ath10k_pci.ko
	But that file is already provided by package  * kmod-ath10k-ct
 * opkg_install_cmd: Cannot install package kmod-ath10k-ct-smallbuffers.
 * check_data_file_clashes: Package kmod-ath10k wants to install file /home/bigbug/WorkSpace/lede/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/lib/modules/4.19.122/ath10k_core.ko
	But that file is already provided by package  * kmod-ath10k-ct
 * check_data_file_clashes: Package kmod-ath10k wants to install file /home/bigbug/WorkSpace/lede/build_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/lib/modules/4.19.122/ath10k_pci.ko
	But that file is already provided by package  * kmod-ath10k-ct
 * opkg_install_cmd: Cannot install package kmod-ath10k.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/bigbug/WorkSpace/lede'
make[1]: *** [package/Makefile:108: /home/bigbug/WorkSpace/lede/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/bigbug/WorkSpace/lede'
make: *** [/home/bigbug/WorkSpace/lede/include/toplevel.mk:227: world] Error 2

**Comment by Cathgao** [comment]
自己选择一个，把另一个取消掉

**Comment by bigbugcc** [comment]
> 自己选择一个，把另一个取消掉

是的，目前也只能这样了

**Comment by cattypapa** [comment]
老哥，借楼问你一下，树莓派4b编译的时候，需要选择哪个内核才能有wifi啊？

**Comment by bigbugcc** [comment]
> 老哥，借楼问你一下，树莓派4b编译的时候，需要选择哪个内核才能有wifi啊？

这个要在无线中选添加
