### ISSUE TITLE
ssr+分流问题

### ISSUE THREAD

**Issue by susanooxyz** [coolsnowwolf/lede#4661]
环境：Manjaro + Firefox
最新版ssr+
ssr+ 使用 绕过中国大陆IP模式 时 firefox输入wei.com，taobao.com打开的都是国际版，firefox清楚缓存或者使用隐私模式都是这样。
ssr+使用GFW列表模式则没有上述问题。
使用chrome则没有上面的问题,两种模式都可以正常打开微博和淘宝。
win10中firefox和chrome也是都正常。

不清楚是系统的问题还是ssr+的问题，以前没有这个问题，前几天发现有这个问题，更新到最新版的ssr+后还是如此，只能来这里求助了

**Comment by xxp2277** [comment]
同样有这个问题，不过将taobao.com加入不走代理的域名了。

**Comment by susanooxyz** [comment]
> 同样有这个问题，不过将taobao.com加入不走代理的域名了。
我加了白名单也没用

**Comment by coolsnowwolf** [comment]
Firefox 独有问题？

**Comment by susanooxyz** [comment]
> Firefox 独有问题？

我可能找到原因了，不是ssr+的问题，可能是因为我的firefox不知道从什么时候开启了基于https的dns导致的，取消启用之后，现在看来正常了。多谢大佬的回复
