### ISSUE TITLE
<提议>L大，可以在luci app里添加一个 srelay的socks5代理软件吗

### ISSUE THREAD

**Issue by 82kg** [coolsnowwolf/lede#4667]
luci app里有http代理服务器 tinyproxy 和squid，

但好像没有socks5的代理服务软件，能否在luci app里添加个 socks5代理软件,例如 srelay？

**Comment by dolphinpaopao** [comment]
此项目现在已经删除SSR+。

**Comment by 82kg** [comment]
> 此项目现在已经删除SSR+。

跟ssr 没关系啊，就是普通的代理软件。。。

**Comment by dolphinpaopao** [comment]
> > 此项目现在已经删除SSR+。
> 
> 跟ssr 没关系啊，就是普通的代理软件。。。

我的意思是这里不作此类工具公开讨论，只作为issue反馈，有需求要自行解决。或者利用现有工具。

**Comment by Aes64X** [comment]
> > 此项目现在已经删除SSR+。
> 
> 跟ssr 没关系啊，就是普通的代理软件。。。

茶香飘飘，自行理解。

**Comment by coolsnowwolf** [comment]
srelay 之前集成过，性能不如 XXR Plus 的 MicroSocks 
![image](https://user-images.githubusercontent.com/31687149/82808936-95f39e80-9ebd-11ea-80a5-d6a86ba22dce.png)
