### ISSUE TITLE
dnsmasq和ssr里的广告屏蔽功能冲突

### ISSUE THREAD

**Issue by madcat0513** [coolsnowwolf/lede#4669]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
dnsmasq和ssr里的广告屏蔽功能冲突
### (1) 具体问题
dnsmasq和ssr里的广告屏蔽功能冲突，开了ssr里的广告屏蔽功能就会引起dnsmasq无法启动
A：

### (2) 路由器型号和固件版本

A：5月20号编译版本

### (3) 详细日志

A：Mon May 25 02:14:17 2020 daemon.crit dnsmasq[26871]: bad option at line 1 of /tmp/dnsmasq.ssr/ad.conf.bak
Mon May 25 02:14:17 2020 daemon.crit dnsmasq[26871]: FAILED to start up
Mon May 25 02:14:17 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 22 crashes, 0 seconds since last crash
Mon May 25 02:14:17 2020 cron.info crond[26900]: crond (busybox 1.30.0) started, log level 5
Mon May 25 02:14:17 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon May 25 02:14:17 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon May 25 02:14:18 2020 daemon.crit dnsmasq[27001]: bad option at line 1 of /tmp/dnsmasq.ssr/ad.conf.bak
Mon May 25 02:14:18 2020 daemon.crit dnsmasq[27001]: FAILED to start up

**Comment by 1715173329** [comment]
通常由于你的网络或可用空间等问题，导致去广告规则未被完整下载或转换，进而使 dnsmasq 读取配置文件错误无法启动 

btw, `.bak` 这些应属于备份文件，应当可以删掉
