### ISSUE TITLE
新版本ssr pro 有时候没法正常使用 换回旧版本正常

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#467]

**Comment by sirfromprc** [comment]
我感觉从内核4.9.102后就有异常。如用最新4.9.107内核ssr速度无论是软路由还是硬路由，youtube速率从不超过50Mbps，用4.9.109内核也不正常。我编译新版ssr切到102内核速度就正常，能到100M。用koolshare的x86版本，速度也很好，就是不稳定。新的openwrt内核不知改了什么，导致翻墙网速下降。

**Comment by nimasi** [comment]
好像是dns问题？

**Comment by uglee** [comment]
4.4以后的内核都有问题，感觉这玩意太激进了也不好。毛病很多

**Comment by MxCen** [comment]
一样的问题，楼主解决没有。
