### ISSUE TITLE
zerotier内网穿透，不释放虚拟网络地址。

### ISSUE THREAD

**Issue by kkxkx** [coolsnowwolf/lede#4682]
zerotier建立连接后，如果更换另一个网络连接串后，用ssh查看ifconfig会发现有两个虚拟地址，一次类推。没有释放掉前一个IP，多次更换连接串后，会新建多个Ip并且不释放，需要手动到etc/config/zero/networks.d/ 中删除多余的连接。不然穿透不成功，或者无法打通

**Comment by tone88** [comment]
我也遇到了，手动删除添加了好几次才成功

**Comment by zxlhhyccc** [comment]
> zerotier建立连接后，如果更换另一个网络连接串后，用ssh查看ifconfig会发现有两个虚拟地址，一次类推。没有释放掉前一个IP，多次更换连接串后，会新建多个Ip并且不释放，需要手动到etc/config/zero/networks.d/ 中删除多余的连接。不然穿透不成功，或者无法打通

确实存在这个问题。。。。

**Comment by mjyhj** [comment]
这个LUCI只join，不leave的。还有如果多netword id的话，防火墙规则只会生效一个，LUCI日志也显示不了
