### ISSUE TITLE
默认的中科大源坏了

### ISSUE THREAD

**Issue by dysl357085918** [coolsnowwolf/lede#4687]
openwrt那边的源可以直接用吗？

**Comment by Promix953** [comment]
建议不要用任何源，你就当没这个功能

**Comment by dysl357085918** [comment]
> 建议不要用任何源，你就当没这个功能

又不是人人都把什么都编译进固件，有的包需要的时候才安装，怎么能说源没用呢？

**Comment by dysl357085918** [comment]
已换源
src/gz openwrt_core https://downloads.openwrt.org/snapshots/targets/x86/64/packages
src/gz openwrt_base https://downloads.openwrt.org/snapshots/packages/x86_64/base
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/x86_64/luci
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing https://downloads.openwrt.org/snapshots/packages/x86_64/routing
