### ISSUE TITLE
最新版固件ac2100无法使用2.4g wifi

### ISSUE THREAD

**Issue by cattypapa** [coolsnowwolf/lede#4688]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译了最新版的Ac2100固件，之前的没有5g wifi解决了，现在5g wifi可以使用了，但是2.4g wifi使用不了，调节了各个模式和信道，都是不行。

### (2) 路由器型号和固件版本

A：红米ac2100

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
没有这个路由器，给 lintel 了

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/83101558-2cee6f80-a0e5-11ea-940c-c34a6d666b2b.png)

**Comment by coolsnowwolf** [comment]
不存在你说的问题

**Comment by aloph** [comment]
前天编译的 tp wdr7500 v3,wifi2.4g也有这个问题，无法使用

**Comment by lexin8** [comment]
MT76系列开源驱动都有问题，5G可以连接上但是会间接性打不开网页。据说闭源驱动会好很多
