### ISSUE TITLE
最新编译，luci-app-ttyd编译进去了，不显示

### ISSUE THREAD

**Issue by Atroc-0625** [coolsnowwolf/lede#4691]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：最新编译，luci-app-ttyd编译进去了，不显示

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/83102388-edc11e00-a0e6-11ea-895e-c0e93557ae5f.png)
昨天提交的源码编译的，没问题，自己检查咯

**Comment by Atroc-0625** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/83102388-edc11e00-a0e6-11ea-895e-c0e93557ae5f.png)
> 昨天提交的源码编译的，没问题，自己检查咯


> ![image](https://user-images.githubusercontent.com/43886952/83102388-edc11e00-a0e6-11ea-895e-c0e93557ae5f.png)
> 昨天提交的源码编译的，没问题，自己检查咯
OpenWrt R20.5.20 / LuCI Master (git-20.141.34051-f750b5f).  这是我编译的版本

**Comment by Sakurakouji-Runa** [comment]
我也遇到了同样的问题

**Comment by yuban10703** [comment]
+1

**Comment by cattypapa** [comment]
可能是你没启动
