### ISSUE TITLE
关于SSR-PLUS服务器节点自动切换的问题

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4694]
我的机场有上百个节点，我选择了其中3个进行自动切换。但是，每次机场更新了节点以后，自动切换就全部勾上了。我又得手动一个个取消勾选。能不能在更新节点以后，不改变原来勾选的设置。或者增加一个“全选”的勾选框，这样手动操作也方便点

**Comment by coolsnowwolf** [comment]
不存在你说的这个问题

![image](https://user-images.githubusercontent.com/31687149/83220520-c8471980-a1a5-11ea-91c4-0c51b92d3461.png)
