### ISSUE TITLE
关于ssr-plus上了CDN之后的自动切换问题

### ISSUE THREAD

**Issue by Zeezorn** [coolsnowwolf/lede#4711]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如果节点套上CDN以后，只要能ping通CDN的节点，哪怕关闭VPS，也不会自动切换了？对于CDN用户来说自动切换功能平时关闭比较好？谢谢

### (2) 路由器型号和固件版本

A：无

### (3) 详细日志

A：无

**Comment by garypang13** [comment]
我的变通解决方法是把检测主线路是否恢复可用的等待时间尽量延长,比如半小时.

**Comment by Zeezorn** [comment]
> 我的变通解决方法是把检测主线路是否恢复可用的等待时间尽量延长,比如半小时.
那就是说自动切换的机制是用ping的，只要能ping通，就不会切换，是这样吗？
