### ISSUE TITLE
建议更新一下可道云

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#4722]
今年一月份好像就更新到了新版本，但是luci-app-kodexplorer没有跟进：
http://doc.kodcloud.com/v2/#/help/changeLog
测试了一下新版还挺好用，不过需要添加新的依赖：php7-mod-sqlite3 php7-mod-pdo php7-mod-pdo-sqlite php7-mod-exif

**Comment by coolsnowwolf** [comment]
建议可发个 pr

**Comment by liwenjie119** [comment]
试着自己改luci，没搞定，不懂。只会简单修改和测试，只搞懂了缺的依赖，还是看别的大佬提pr吧

**Comment by liwenjie119** [comment]
> 建议可发个 pr

不懂怎么改lua，不会改下载地址，因此没搞定，尝试了几天也不行，完全不会。
主要是要改这个文件的下载地址，Makefile好改
package/lean/luci-app-kodexplorer/luasrc/model/cbi/kodexplorer/api.lua
