### ISSUE TITLE
pve 下 虚拟机上开启qemu-ga 代理的情况下无法关机

### ISSUE THREAD

**Issue by ptsa** [coolsnowwolf/lede#4724]
编译的时候已经编译qemu-ga 并且已经启用，pve上能获取到ip信息
网上说是qemu-ga 的默认关机命令是shutdown 而openwrt的是poweroff
这个要怎么处理？

**Comment by caicaicai21** [comment]
/sbin 目录下新建名为 shutdown 的文件，赋予 执行权限(chmod +x /sbin/shutdown)
shutdown文件内容：

#!/bin/sh
busybox poweroff

这样既可，已测试可用。
*更新固件之后需要重新编写这个文件。

**Comment by ptsa** [comment]
@coolsnowwolf  能不能直接加入这个，以后编译好就不用改了

**Comment by coolsnowwolf** [comment]
已支持

**Comment by keivenliao** [comment]
这个支持是不是又回滚了？新编译的固件中，又不能shutdown了

**Comment by LOVEChen** [comment]
这个问题又来了
