### ISSUE TITLE
frpc未完全汉化问题

### ISSUE THREAD

**Issue by SterlingCarter** [coolsnowwolf/lede#4727]
在中文情况下，显示Frpc运行状态的文字没有汉化。依旧显示Frcp status和The Frp service is not running及The Frp service is running.希望大神能够将这里进行汉化，谢谢！！
![image](https://user-images.githubusercontent.com/66172871/83654100-3305b400-a5ef-11ea-8fe2-c8fcead2ade6.png)

**Comment by ziyangdaoren** [comment]
翻译更新了，但界面还是英文的

**Comment by hyird** [comment]
> 翻译更新了，但界面还是英文的

翻译分离了  你得重新生成config  编译 luci-i18n-frpc-zh-cn

**Comment by SterlingCarter** [comment]
> > 翻译更新了，但界面还是英文的
> 
> 翻译分离了你得重新生成config编译luci-i18n-frpc-zh-cn

已经重新编译固件，感谢

**Comment by ziyangdaoren** [comment]
> > 翻译更新了，但界面还是英文的
> 
> 翻译分离了 你得重新生成config 编译 luci-i18n-frpc-zh-cn

重新生成的.config中还是没有luci-i18n-frpc-zh-cn，得手动添加CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y才行

**Comment by hyird** [comment]
> > > > > 翻译更新了，但界面还是英文的
> > > > 
> > > > 
> > > > 翻译分离了 你得重新生成config 编译 luci-i18n-frpc-zh-cn
> > > 
> > > 
> > > 重新生成的.config中还是没有luci-i18n-frpc-zh-cn，得手动添加CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y才行
> > 
> > 
> > 要把.config删了
> 
> .config删了make menuconfig重新生成后还是没有luci-i18n-frpc-zh-cn，在.config文件中手动添加CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y 后make menuconfig后save了一下，.config文件中的luci-i18n-frpc-zh-cn又没了，不知道是什么情况。
> [.config.txt](https://github.com/coolsnowwolf/lede/files/4759986/default.config.txt)

不会吧 我自己测了没得问题

**Comment by EnnawYang** [comment]
![Snipaste_2020-06-11_10-58-51](https://user-images.githubusercontent.com/6705663/84340181-b0728b00-abd2-11ea-9264-f1687d0dc3a8.png)
玄学吧，右边是新git clone的，就有

**Comment by hyird** [comment]
> ![Snipaste_2020-06-11_10-58-51](https://user-images.githubusercontent.com/6705663/84340181-b0728b00-abd2-11ea-9264-f1687d0dc3a8.png)
> 玄学吧，右边是新git clone的，就有
rm -rf ./tmp试试

**Comment by EnnawYang** [comment]
> > ![Snipaste_2020-06-11_10-58-51](https://user-images.githubusercontent.com/6705663/84340181-b0728b00-abd2-11ea-9264-f1687d0dc3a8.png)
> > 玄学吧，右边是新git clone的，就有
> rm -rf ./tmp试试

![Snipaste_2020-06-11_11-20-33](https://user-images.githubusercontent.com/6705663/84341508-e2392100-abd5-11ea-919d-5abe4c0793b5.png)
OK，其实我也只是顺手测试下而已，这个东西我用不到

**Comment by hyird** [comment]
> > > ![Snipaste_2020-06-11_10-58-51](https://user-images.githubusercontent.com/6705663/84340181-b0728b00-abd2-11ea-9264-f1687d0dc3a8.png)
> > > 玄学吧，右边是新git clone的，就有
> > > rm -rf ./tmp试试
> 
> ![Snipaste_2020-06-11_11-20-33](https://user-images.githubusercontent.com/6705663/84341508-e2392100-abd5-11ea-919d-5abe4c0793b5.png)
> OK，其实我也只是顺手测试下而已，这个东西我用不到
强迫症 自己要用 就修了修

**Comment by ziyangdaoren** [comment]
> > ![Snipaste_2020-06-11_10-58-51](https://user-images.githubusercontent.com/6705663/84340181-b0728b00-abd2-11ea-9264-f1687d0dc3a8.png)
> > 玄学吧，右边是新git clone的，就有
> rm -rf ./tmp试试

好了

**Comment by SterlingCarter** [comment]
> > 翻译更新了，但界面还是英文的
> 
> 翻译分离了你得重新生成config编译luci-i18n-frpc-zh-cn

实践证明已经完全汉化，且汉化PO包分离，给作者点赞
