### ISSUE TITLE
 v2ray-core 4.23.4 upgrade needed

### ISSUE THREAD

**Issue by wuxiangzhou2010** [coolsnowwolf/lede#4728]
v2ray upstream has released  v4.23.4 with bug fixes, please sync.

## Fix
Issued further fixs for VMess weakness described in v2ray/v2ray-core[#2523](https://github.com/v2ray/v2ray-core/issues/2523) [#2539](https://github.com/v2ray/v2ray-core/issues/2539)
Issued a fix for Fake HTTP Header weakness described in v2ray/v2ray-core[#2537](https://github.com/v2ray/v2ray-core/issues/2537)

please refer to https://github.com/v2ray/v2ray-core/releases/tag/v4.23.4

**Comment by wuxiangzhou2010** [comment]
merged with https://github.com/coolsnowwolf/lede/pull/4725

**Comment by 4209kaiyou** [comment]
我黑群晖 虚拟机openwrt 不知道这么更新 4.23.4  指教一下
