### ISSUE TITLE
ps3netsrv在luci 没找到启动界面

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#4733]
ps3netsrv在luci 没找到启动界面，是没写？还是依附于哪个里面了？

**Comment by AmadeusGhost** [comment]
这个包没有 luci 的

**Comment by hxlls** [comment]
> 这个包没有 luci 的

好吧，我以为是大雕做了luci ，能设定开启还有存放路径的。。。

**Comment by keeno1982** [comment]
我也是编译进去了，但是不知道怎么开，配置在哪
