### ISSUE TITLE
建议加入librespeed,可以内网测速

### ISSUE THREAD

**Issue by lqhorochi** [coolsnowwolf/lede#4735]
项目开源地址：https://github.com/adolfintel/speedtest
希望大雕可以考虑加入

**Comment by KevinMX** [comment]
内网测速iperf3还不够用吗……

**Comment by naoki66** [comment]
librespeed更方便更直观

**Comment by shikkoku** [comment]
https://forum.openwrt.org/t/solved-is-it-possible-to-install-librespeed-speed-test-on-openwrt/65931/7 参考这里

**Comment by ilovesuyy** [comment]
librespeed太大了吧  我在docker里装了下，有400M.。。。

**Comment by shikkoku** [comment]
> librespeed太大了吧 我在docker里装了下，有400M.。。。

https://github.com/saudiqbal/speed-test-openwrt

有精简版的，不过记得装PHP7-cgi

**Comment by 9l** [comment]
php 更大

**Comment by Cathgao** [comment]
你是完全不考虑32M以下flash大小的设备直接塞进去一个NMP环境？

**Comment by martin0607** [comment]
> > librespeed太大了吧 我在docker里装了下，有400M.。。。
> 
> https://github.com/saudiqbal/speed-test-openwrt
> 
> 有精简版的，不过记得装PHP7-cgi

PHP7好像不生效。。不知道为啥
![image](https://user-images.githubusercontent.com/32560181/84846033-7d237680-b080-11ea-94af-68578322ff4d.png)

**Comment by shikkoku** [comment]
> > > librespeed太大了吧 我在docker里装了下，有400M.。。。
> > 
> > 
> > https://github.com/saudiqbal/speed-test-openwrt
> > 有精简版的，不过记得装PHP7-cgi
> 
> PHP7好像不生效。。不知道为啥
> ![image](https://user-images.githubusercontent.com/32560181/84846033-7d237680-b080-11ea-94af-68578322ff4d.png)

你要装PHP7-CGI。

**Comment by martin0607** [comment]
> > > > librespeed太大了吧 我在docker里装了下，有400M.。。。
> > > 
> > > 
> > > https://github.com/saudiqbal/speed-test-openwrt
> > > 有精简版的，不过记得装PHP7-cgi
> > 
> > 
> > PHP7好像不生效。。不知道为啥
> > ![image](https://user-images.githubusercontent.com/32560181/84846033-7d237680-b080-11ea-94af-68578322ff4d.png)
> 
> 你要装PHP7-CGI。

![image](https://user-images.githubusercontent.com/32560181/84873105-5469a400-b0b5-11ea-9ac3-53cb0185d518.png)
CGI是已经装了的，不知道是不是环境变量问题。我看看
