### ISSUE TITLE
本地代理修复 Pandownload 登录失败

### ISSUE THREAD

**Issue by mjyhj** [coolsnowwolf/lede#4738]
5月29号开始，在pandownload上百度账号直接登录不上了，提示bdstoken获取失败，不管是新浪第三方登录，还是QQ第三方登录，都是这个提示

https://github.com/TkzcM/pandownload-login

有兴趣的可以弄到路由上

原来的Pandownload客户端需要修改一下，添加代{过}{滤}理地址在PanData文件夹中找到config.ini，用记事本打开编辑，在proxy=后填http://127.0.0.1:8888

**Comment by hyird** [comment]
py脚本 安装python跑一下就好了吧
