### ISSUE TITLE
我黑群晖 虚拟机openwrt 不知道这么更新 4.23.4  指教一下

### ISSUE THREAD

**Issue by qiuzhongqiang** [coolsnowwolf/lede#4739]
我黑群晖 虚拟机openwrt 不知道这么更新 4.23.4  指教一下

_Originally posted by @4209kaiyou in https://github.com/coolsnowwolf/lede/issues/4728#issuecomment-639242693_

我gitpull后编译，还是老版本。Google也没有答案，不知道怎么搞了。

**Comment by aizhouyi** [comment]
直接删掉本地仓库，从头再来编译得到x86架构文件就可以了

**Comment by qiuzhongqiang** [comment]
好的，明白，谢谢。
