### ISSUE TITLE
ssr问题，去掉“启用DNS TCP防污染”的勾？

### ISSUE THREAD

**Issue by yes2003** [coolsnowwolf/lede#474]
make menuconfig里只选了x86 64编译无错误
ss账号正常
ssr显示绿色的正在运行，但是打不开墙外网页
把 “启用DNS TCP防污染”的勾去掉倒是能打开

刷lean发布在恩山的LEDE-17.01.2-R7.3.3-x64-combined-squashfs版本，里面的ssr就很好用，是新版ssr有问题吗？

**Comment by plutoghost** [comment]
dns问题，手机客户端也有一样的毛病

**Comment by MxCen** [comment]
cp -fpR /home/meng/lede/build_dir/target-mips_24kc_musl/root-ar71xx /home/meng/lede/build_dir/target-mips_24kc_musl/root.orig-ar71xx
/home/meng/lede/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/ssrpro: line 48: network_get_subnet: command not found
/home/meng/lede/build_dir/target-mips_24kc_musl/root-ar71xx/etc/init.d/ssrpro: line 49: network_get_ipaddr: command not found
Create '/home/meng/lede/build_dir/target-mips_24kc_musl/root-ar71xx/etc/filesystems'.
Add 'ntfs-3g' to known filesystems.
./etc/init.d/ssrpro: line 48: network_get_subnet: command not found
./etc/init.d/ssrpro: line 49: network_get_ipaddr: command not found
