### ISSUE TITLE
关于V2Ray-json配置文件中的"allowInsecure"的值始终为ture，无法修改的bug。

### ISSUE THREAD

**Issue by Zeezorn** [coolsnowwolf/lede#4741]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
A：ssrplus-luci界面-->编辑服务器配置-->节点类型V2ray-->允许不安全连接，此选项无论是勾选还是不勾选，在/var/etc/v2-ssr-retcp.json应用的配置文件中"allowInsecure"的值始终为true，无法修改为false。正确情况应该勾选为true，不勾选为false。版本：luci-app-ssr-plus 178-5

### (2) 路由器型号和固件版本
A：路由器型号 | Netgear Nighthawk X4S R7800 & P&W R619AC 128M 均出现此Bug
      固件版本 | OpenWrt R20.5.9 / LuCI Master (git-20.117.60969-420c61a)
      内核版本 | 4.14.180
      V2Ray-core | 4.23.4
      luci-app-ssr-plus | 178-5

### (3) 详细日志
A：无

**Comment by coolsnowwolf** [comment]
已修复
