### ISSUE TITLE
tcpping的问题

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#4745]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：
如果把服务器修改成禁ping模式，
有几率导致软路由里面的tcpping一直运行不结束，
平均每个进程占用cpu25%，
会导致机器过热，
这是第三次发现，
所以上来反映一下，
恳请大佬解决一下，多谢！

### (2) 路由器型号和固件版本

A：j1900，今天新编译的(20200607)

### (3) 详细日志

A：无，看top即可

**Comment by coolsnowwolf** [comment]
没有重现

**Comment by kl9800** [comment]
好吧，
毕竟不是每次禁ping以后都会复现，
因为我的路由器有时候变得巨烫，
然后每次发现以后都直接假死，SSH也进不去，
偶尔有那么几次，我可以进入ssh，第一个就直接看了top，
就看到了那几个tcpping一直在，3个进程把CPU直接占了75%，
重启以后就没问题了，
下次再发现我把top截图贴出来吧，
多谢大佬。

**Comment by kl9800** [comment]
有时候也会这样，一直三声长响，但这样的时候一般是拿不到日志的，大多数发生在夜里2点ssr重启的时候，但是我没用订阅功能，好奇怪…，有时候能进ssh的时候，就是n个tcpping…

**Comment by kl9800** [comment]
这问题比较玄学…感觉不是内存的问题，因为一般开机好几天才会出现，唯一几次能进ssh的时候都是看到了tcpping…
