### ISSUE TITLE
关于 禁止解析 IPv6 DNS 记录，能否设置白名单

### ISSUE THREAD

**Issue by mjyhj** [coolsnowwolf/lede#4749]
这个禁止解析 IPv6 DNS 记录的用途，本身是为了上网冲浪流畅只用IPV4的同时，挂PT可以用IPV6。

但是这样根本就没用，把IPV6解析禁止了，PT连上tracker根本就不走IPV6了，就是因为只解析到IPV4
可以说变相这个功能没用了。

大神们有没有办法，可以设置一些域名白名单能够正常返回解析。这样自己用IPV6 DDNS，和PT站都丢进去就能正常使用了

**Comment by HK-Journalist** [comment]
我也遇到这个问题而且要访问一些ipv6网站不行了。
应该增加黑名单或者白名单。
