### ISSUE TITLE
dnspod插件支持token认证

### ISSUE THREAD

**Issue by sofent** [coolsnowwolf/lede#475]
目前dnspod插件只支持用户名密码验证，请支持token验证
另外希望能支持wan_up的时候更新，而不只是定时检查

**Comment by plutoghost** [comment]
https://github.com/plutoghost/lede/tree/master/package/pluto/luci-app-ardnspod

**Comment by sofent** [comment]
@plutoghost 这个帖子里只有k3的，能放出源码吗？

**Comment by sofent** [comment]
从 @plutoghost 的fork上找到的源码，感谢
