### ISSUE TITLE
请问路由器5k w20型号（拆机看是mt7620a）能刷LEDE吗？

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [coolsnowwolf/lede#4762]
路由器5k w20型号（拆机看是mt7620a），为什么在lede仓库中找不到编译的型号呢？

Target System 选择 MediaTek Ralink MIPS
Subtarget 选择 MT7620 based board
Target profile 应该选择什么呢？里面好像没有找到5K w20字样

这个路由买过来我看有人已经刷了类似潘多拉的界面，应该是能刷的感觉。新人求助

**Comment by coolsnowwolf** [comment]
没人提交这个，欢迎你发个 PR

**Comment by pmxEr5lZwZ** [comment]
PR是什么，应该怎么提交呢？

如果没人提交这个，能刷吗？选择default那个编译可以吗？

**Comment by lunatickochiya** [comment]
用Y1的 貌似可以用~

**Comment by pmxEr5lZwZ** [comment]
@lunatickochiya 用是能用，就是我电源拔了再插，自动就恢复了出厂设置
