### ISSUE TITLE
编译出来接口没有交换机选项，请问要选些什么包才有？

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#477]

**Comment by LGA1150** [comment]
x86?

**Comment by nimasi** [comment]
@LGA1150  ar71xx的  还有mt7620的

**Comment by LGA1150** [comment]
swconfig

**Comment by nimasi** [comment]
问题找到了 修改了dts文件的model导致的 不是没有勾选什么软件包造成的

**Comment by niceguy3-31** [comment]
@nimasi ，我编译出来的也没有，你修改了什么？

**Comment by jiangzm** [comment]
同问 @nimasi @niceguy3-31 ，x86_64编译出来的没有`网络-交换机`，也没改上面提到的配置

**Comment by EnnawYang** [comment]
> 同问 @nimasi @niceguy3-31 ，x86_64编译出来的没有`网络-交换机`，也没改上面提到的配置

你软路由还有交换机芯片？
