### ISSUE TITLE
下载dl库时，我看命令行界面有些链接是404，这样有关系吗？

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [coolsnowwolf/lede#4770]
按照教程一步一步来的

到了这步：make -j8 download V=s 下载dl库（国内请尽量全局科学上网）

下载dl库时，我看命令行界面有些链接是404，这样有关系吗？

还有为什么这步要很久很久？？我上次挂了全局代理了，命令行运行了4个小时还没下载结束，结果就关掉了。

**Comment by EvineDeng** [comment]
有关系，下载不成功会导致编译时仍然要下载，如果还下不下来，就会编译失败。

**Comment by SterlingCarter** [comment]
我发现最近dll文件版下载很困难，有些包下载1Kb就不下载，不能完整下载所有的dll包，希望官方能出一个dll包集合，直接下载来放到里面，
