### ISSUE TITLE
找到一份螃蟹RTL8111/8168的网卡驱动

### ISSUE THREAD

**Issue by martin0607** [coolsnowwolf/lede#4782]
目前的8111/8168网卡用的是8169的驱动，虽然能用，但是感觉不是专用驱动？找到了适配8111/8168的驱动，自己再从螃蟹官网下载更新了下，编译进系统，可以正常识别使用。L大考虑加进去吗？刚好看到加了8125的驱动了
![批注 2020-06-11 201250](https://user-images.githubusercontent.com/32560181/84384149-1e916f00-ac20-11ea-938a-885ce0ce1644.jpg)

**Comment by martin0607** [comment]
驱动的地址，直接放package下：https://github.com/BROBIRD/openwrt-r8168

**Comment by EnnawYang** [comment]
不如发个PR？

**Comment by RayleiLi** [comment]
你好，我想请教一下您如果在编译的时候添加驱动呢？

**Comment by martin0607** [comment]
> 你好，我想请教一下您如果在编译的时候添加驱动呢？

直接克隆到package里然后菜单里选上kmod r8168就好了

**Comment by shikkoku** [comment]
https://github.com/goldkeyber112/openwrt-r8168/releases

有大佬用SDK编译好了IPK包。安装后把r8169的包卸载重启路由即可使用。

**Comment by shikkoku** [comment]
https://github.com/coolsnowwolf/lede/commit/ba8a697b767908a4397e11241b5c394bd29f2d21 已经合并进去了吧？

**Comment by wen-bug** [comment]
> https://github.com/goldkeyber112/openwrt-r8168/releases
> 
> 有大佬用SDK编译好了IPK包。安装后把r8169的包卸载重启路由即可使用。

大佬我安装这个显示没kmod-8168应该怎么弄

**Comment by weiyideai520** [comment]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.188-1-db222399ef90ea6bd3453fe08b323a74) for kmod-r8168
 
 是否可以重新编译个。安装不上了
