### ISSUE TITLE
酸酸乳Plus 彩蛋无法开启

### ISSUE THREAD

**Issue by numbcoder** [coolsnowwolf/lede#4785]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：输入 `echo 0xDEADBEEF > /etc/config/google_fu_mode` 后无法开启 SSR-Plus

### (2) 路由器型号和固件版本

A：X86 64软路由，直接从 GitHub Action下载的每日构建的最新版本 OpenWrt SNAPSHOT, r0-e707c9f

**Comment by mjyhj** [comment]
早就不需要

**Comment by yonggedebaqi** [comment]
新编的固件SSR不能启动

**Comment by numbcoder** [comment]
> 早就不需要

啥意思？

**Comment by xmanwq1** [comment]
action 里面编译的版本 打开怎么没有shadowSocksR ,怎么才能开启啊?

**Comment by samsam-coder** [comment]
同问？GitHub  action 里面编译的版本 没有ssr plus ，明明config里有添加
