### ISSUE TITLE
编译总是提示如下错误导致编译停止、失败告终。

### ISSUE THREAD

**Issue by SterlingCarter** [coolsnowwolf/lede#4786]
最近编译固件的时候总是报同样一个错误，真的不知道该怎么解决这个错误。
好像这个makefiles文件是在编译过程的时候自动生成的，并不是L大源码里面自带的文件，编译倒到这里提示第37行，缺少空格符，以下是错误代码：

Makefiles:37 ***missing separator.   stop.

make[3]: *** [/home/angel/lede/build_dir/target-mipsel_24kc_musl/u-boot-2020.04/ .built] Error 2

make[2]: *** [package/boot/uboot-envtools/compile] Error 2

make[1]: *** [/home/angel/lede/build_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2

make: *** [world] Error 2
![111144u8p6gfdfgrzffv27](https://user-images.githubusercontent.com/66172871/84454315-c47ac300-ac8c-11ea-9e40-91d9f1ba684d.jpg)

**Comment by SterlingCarter** [comment]
怎么没有大神回复呢？

**Comment by cokyrain** [comment]
好像出问题的都是ubuntu 20.04

**Comment by Twinzo1** [comment]
是不是win10子系统

**Comment by SterlingCarter** [comment]
不是win10子系统，用的虚拟机ubuntu 14.6
