### ISSUE TITLE
samba中文乱码，加了cp936没用

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#479]
autosamba和samba36
中文乱码，原生语言支持加了cp936也没有用，samba init 里面utf-8改cp936也没效果

**Comment by coolsnowwolf** [comment]
其实会不会是你原来的文件编码就不是 utf-8 呢

**Comment by nimasi** [comment]
@coolsnowwolf 
我用明月永在的固件，可以正常显示，看他的配置好像就是用的utf-8

**Comment by nimasi** [comment]
文件名都变成了 [数字 大写字母 符号混合] +[~]+[数字或大写字母]的形式，
比如 _50SE2F~3.TXT 、1HO90T~7.DOC  、 _852VC~A.RAR 、_INZBC~F.TXT

**Comment by tomerilery** [comment]
你加上cp437试试

**Comment by nimasi** [comment]
@tomerilery 
 kmod-nls-cp437 在 kmod-fs-vfat被勾选的时候早就自动被勾上了，
而kmod-fs-vfat在automount 和block-mount被勾选的时候就被自动勾上了

**Comment by ferre-han** [comment]
设置自动挂载中文
make kernel_menuconfig
File systems --->
Native Language Support --->
(utf8) Default NLS Option ///此括号内为根据自己需要修改 必须改,网络共享默认中文
<> Simplified Chinese charset (CP936, GB2312) 可以不用改,默认 <> NLS ISO 8859-1 (Latin 1; Western European Languages) 可以不用改,默认
<*> NLS UTF-8 可以不用改,默认
DOS/FAT/NT Filesystems --->
(437) Default codepage for FAT ///此括号内为根据自己需要修改
(utf8) Default iocharset for FAT ///此括号内为根据自己需要修改 必须改,USB默认中文
