### ISSUE TITLE
现在lede还支持v2吗？

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [coolsnowwolf/lede#4793]
小白求教，我想做翻墙路由器的话，路由器连接我的节点，设备自动科学上网。

现在这个版本的lede还支持吗？编译的时候是选v2ray-server那个吗？我看其他视频好像有个include v2ray，新版本反而没有，这是为什么呢？

**Comment by c3RheXJhYmJpdA** [comment]
自行重新編譯去掉注釋添加Helloworld
