### ISSUE TITLE
tcpping & V2的允许不安全连接

### ISSUE THREAD

**Issue by kl9800** [coolsnowwolf/lede#4794]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：1.首先说明一下，前阵子提的那个tcpping的问题，怀疑发生在ssr-p开启状态下手动ssh进入编辑了/etc/shadowsocksr导致，只要不这么干，就没有多个tcpping进程出现，
2.   机器异响怀疑是内存导致，换了条内存目前无复现。

**3.真正要问的问题是，到底应不应该勾选上V2里面的“允许不安全连接”的钩子？？？？？？**

### (2) 路由器型号和固件版本

A： J1900  X86_64  (OpenWrt R20.5.20 / LuCI Master (git-20.141.34051-f750b5f))

### (3) 详细日志

A：

**Comment by Bnosora** [comment]
字面理解，勾上之后就允许不安全的连接，不勾就是不允许不安全的连接。

参考`https://www.v2ray.com/chapter_02/05_transport.html#tlsobject`的allowInsecure项。
这个安不安全和浏览器一样，是指服务器的证书是否可信。服务器有可信证书的情况下最好是不允许。如果你的服务器证书是自签名证书，甚至是过期证书，那你必须允许。

**Comment by kl9800** [comment]
谢谢
