### ISSUE TITLE
EA8500编译失败，请告知原因

### ISSUE THREAD

**Issue by ihuaer** [coolsnowwolf/lede#48]
# Build failed - please re-run with -j1 to see the real error message
怎么回事啊
 @Ub里已经挂蓝灯下载源码编译

> /bin/mkdir -p '/home/lede/lede/staging_dir/host/bin'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/lib'
 /usr/bin/install -c src/yacc '/home/lede/lede/staging_dir/host/bin'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/aclocal'
 /usr/bin/install -c -m 644  lib/liby.a '/home/lede/lede/staging_dir/host/lib'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/doc/bison/examples/calc++'
 /usr/bin/install -c -m 644 m4/bison-i18n.m4 '/home/lede/lede/staging_dir/host/share/aclocal'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/doc/bison'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/bison/m4sugar'
 ( cd '/home/lede/lede/staging_dir/host/lib' && ranlib liby.a )
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/bison'
 /usr/bin/install -c -m 644 data/m4sugar/foreach.m4 data/m4sugar/m4sugar.m4 '/home/lede/lede/staging_dir/host/share/bison/m4sugar'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/bison/xslt'
 /usr/bin/install -c -m 644 data/README data/bison.m4 data/c++-skel.m4 data/c++.m4 data/c-like.m4 data/c-skel.m4 data/c.m4 data/glr.c data/glr.cc data/java-skel.m4 data/java.m4 data/lalr1.cc data/lalr1.java data/location.cc data/stack.hh data/variant.hh data/yacc.c '/home/lede/lede/staging_dir/host/share/bison'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/doc/bison/examples/mfcalc'
 /usr/bin/install -c -m 644 data/xslt/bison.xsl data/xslt/xml2dot.xsl data/xslt/xml2text.xsl data/xslt/xml2xhtml.xsl '/home/lede/lede/staging_dir/host/share/bison/xslt'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/doc/bison/examples/rpcalc'
 /usr/bin/install -c -m 644 AUTHORS COPYING NEWS README THANKS TODO '/home/lede/lede/staging_dir/host/share/doc/bison'
 /usr/bin/install -c -m 644 examples/calc++/calc++-driver.cc examples/calc++/calc++-driver.hh examples/calc++/calc++-scanner.ll examples/calc++/calc++.cc examples/calc++/calc++-parser.yy '/home/lede/lede/staging_dir/host/share/doc/bison/examples/calc++'
 /usr/bin/install -c -m 644 examples/mfcalc/calc.h examples/mfcalc/mfcalc.y '/home/lede/lede/staging_dir/host/share/doc/bison/examples/mfcalc'
 /usr/bin/install -c -m 644 examples/rpcalc/rpcalc.y '/home/lede/lede/staging_dir/host/share/doc/bison/examples/rpcalc'
src/bison --version >doc/bison.help.tmp
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/bin'
src/bison --help   >>doc/bison.help.tmp
./build-aux/move-if-change doc/bison.help.tmp doc/bison.help
  /usr/bin/install -c src/bison '/home/lede/lede/staging_dir/host/bin'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/man/man1'
 /bin/mkdir -p '/home/lede/lede/staging_dir/host/share/info'
 /usr/bin/install -c -m 644 ./doc/bison.info '/home/lede/lede/staging_dir/host/share/info'
 /usr/bin/install -c -m 644 ./doc/bison.1 doc/yacc.1 '/home/lede/lede/staging_dir/host/share/man/man1'
 install-info --info-dir='/home/lede/lede/staging_dir/host/share/info' '/home/lede/lede/staging_dir/host/share/info/bison.info'
This is not dpkg install-info anymore, but GNU install-info
See the man page for ginstall-info for command line arguments
make[7]: Leaving directory `/home/lede/lede/build_dir/host/bison-3.0.4'
make[6]: Leaving directory `/home/lede/lede/build_dir/host/bison-3.0.4'
make[5]: Leaving directory `/home/lede/lede/build_dir/host/bison-3.0.4'
make[4]: Leaving directory `/home/lede/lede/build_dir/host/bison-3.0.4'
install -m0755 ./scripts/yacc /home/lede/lede/staging_dir/host/bin/yacc
mkdir -p /home/lede/lede/staging_dir/host/stamp
touch /home/lede/lede/build_dir/host/bison-3.0.4/.built
touch /home/lede/lede/staging_dir/host/stamp/.bison_installed
make[3]: Leaving directory `/home/lede/lede/tools/bison'
make[2]: Leaving directory `/home/lede/lede'
make[1]: *** [/home/lede/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.tools_compile_yynyyyyynyyyyynyynnyyyynyyyyyyyyyyyyyyynyynynnyyynny] Error 2
make[1]: Leaving directory `/home/lede/lede'

**Comment by coolsnowwolf** [comment]
蓝灯不支持 git 协议，请用 ss-redir
