### ISSUE TITLE
想问下ramips最后个保存应用不用等待的内核版本

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#480]
想问下ramips最后个保存应用不用等待的内核版本是多少
用的4.9.77 编译出来还是新版本的luci 保存应用要等待秒数很烦 而且advance tomato那个主题布局会有问题

**Comment by LGA1150** [comment]
LuCI 关内核版本什么事？想用旧版去改 commit id

**Comment by uglee** [comment]
那不是内核的问题，那是luci的锅。

**Comment by uglee** [comment]
复制老版的feed目录 替换即可
