### ISSUE TITLE
新版可道云应该可用了

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#4807]
根据别人的改的，应该已经可用了
之前有提，[https://github.com/coolsnowwolf/lede/issues/4722](url) ，但是不太会搞，整了几天，在别人的基础上基本是可用了，我自己拉取的lede太乱，没提pr

https://github.com/liwenjie119/luci-app-kodexplorer

**Comment by EnnawYang** [comment]
https://github.com/coolsnowwolf/lede/pull/4788 ，有大佬提过PR了
