### ISSUE TITLE
请问如何扩大编译后img文件的尺寸？

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#4809]
因为装不了少插件，所以默认的文件尺寸不够用，我以前编译的时候，修改某个参数，是可以把文件尺寸变大的。openwrt-x86-64-combined-squashfs.img 这个文件编译后得到的尺寸是300多M

一个多月没折腾了，再次编译，发现文件尺寸固定在70M左右，无法扩大。请问具体在哪个参数里修改呀？

**Comment by ziyangdaoren** [comment]
Target Image ---> Root Filesystem Partition Size

**Comment by ecco2005** [comment]
> Target Image ---> Root Filesystem Partition Size

这参数默认就是160，我第一次编译是70M，然后改成320又编译了一次，还是70M。我记得以前编译也是改的这个参数，不知道这次编译为什么不成功。

**Comment by ecco2005** [comment]
删掉代码，重新git，重新编译以后，尺寸正常了

**Comment by jasonseye** [comment]
rm -rf ./tmp 再次编译就行了
昨晚刚成功调整过
