### ISSUE TITLE
LUCI没有酸酸乳选项

### ISSUE THREAD

**Issue by myleesun** [coolsnowwolf/lede#4814]
## 1.关于你要提交的问题
make menuconfig 的选项中，LUCI没有酸酸乳选项。

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：在ubuntu 16的版本中make menuconfig，找不到酸酸乳+的选项

### (2) 路由器型号和固件版本

A：MW4530R

### (3) 详细日志

A：

**Comment by bulkmilk** [comment]
修改feeds.conf.default
#src-git helloworld https://github.com/fw876/helloworld
取消前面的#号

**Comment by myleesun** [comment]
> 修改feeds.conf.default
> #src-git helloworld https://github.com/fw876/helloworld
> 取消前面的#号

感谢大神
