### ISSUE TITLE
开启DDNS提示Rejected request from RFC1918 IP to public server address的解决方法

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#4817]
开启DDNS后，通过公网IP或动态域名访问路由器时提示“Rejected request from RFC1918 IP to public server address”，将/etc/config/uhttpd 中的option rfc1918_filter 1改成option rfc1918_filter 0可解决这个问题。
如要在编译前解决这个问题，需要把lede/package/network/services/uhttpd/files/uhttpd.config中的option rfc1918_filter 1改为option rfc1918_filter 0。
建议大雕能从源码中更改此处字段，避免类似鄙人一样的小白踩坑。谢谢！

**Comment by hxlls** [comment]
这个是哪里出的日志？为什么我的没有？奇怪了
