### ISSUE TITLE
X86版在内网通过公网IP无法访问内网设备

### ISSUE THREAD

**Issue by zeruns** [coolsnowwolf/lede#4820]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：在内网里使用公网IP访问无法正常访问内网设备，已做端口映射，但在外网可以正常访问，内网只能使用内网IP访问内网设备

### (2) 路由器型号和固件版本

A：X86软路由，CPU：1037U，网卡RTL8111，固件版本：OpenWrt R20.5.20 / LuCI Master (git-20.141.34051-f750b5f) 

### (3) 相关设置截图

A：![2020-06-16_00-38-03.png](https://img.zeruns.tech/2020/06/16/2020-06-16_00-38-03.png)
![2020-06-16_00-38-32.png](https://img.zeruns.tech/2020/06/16/2020-06-16_00-38-32.png)

**Comment by vlanbin** [comment]
可以试试从这两个方面找下原因:
1. 启用端口环回
2. 不要编译docker
#3742

**Comment by zeruns** [comment]
> 可以试试从这两个方面找下原因:
> 
> 1. 启用端口环回
> 2. 不要编译docker
>    #3742

端口环回已开启，docker卸载了，还是一样

**Comment by coolsnowwolf** [comment]
不是卸载 docker，而是别编译进去

**Comment by hxlls** [comment]
如果是X86 ，以上操作建议再加一个。关闭Flow Offloading，你就会发现问题都解决了

**Comment by zeruns** [comment]
> 不是卸载 docker，而是别编译进去

重新编译了，没有把docker编译进去，结果一样

**Comment by zeruns** [comment]
用别人旧版的固件倒没有这个问题

**Comment by hxlls** [comment]
rm .config 后重新选择，不能选上docker 选上后再取消，依赖没有取消的，你怎么编译都没用

**Comment by zeruns** [comment]
> rm .config 后重新选择，不能选上docker 选上后再取消，依赖没有取消的，你怎么编译都没用

我是直接把整个lede文件夹删掉然后重新git，重新编译

**Comment by zeruns** [comment]
在gitee上找到别人fork的R20.4.8版本的编译后就没问题了，确实是新版的BUG

**Comment by WXfeng-boy** [comment]
最新版没问题的，我一直没有编译docker。删除lede，重新git，重新配置config，全新刷机，别保留配置试试吧

**Comment by ptsa** [comment]
> 如果是X86 ，以上操作建议再加一个。关闭Flow Offloading，你就会发现问题都解决了

Flow Offloading x86 以前好像没什么问题， 新版好像不行。 对x86 在没bug的情况下有作用么

**Comment by zeruns** [comment]
> > 如果是X86 ，以上操作建议再加一个。关闭Flow Offloading，你就会发现问题都解决了
> 
> Flow Offloading x86 以前好像没什么问题， 新版好像不行。 对x86 在没bug的情况下有作用么

关闭结果一样

**Comment by lePig** [comment]
同样遇到内网无法通过域名访问的问题。 大家上面说的都试了 好像还是不行

**Comment by zeruns** [comment]
> 同样遇到内网无法通过域名访问的问题。 大家上面说的都试了 好像还是不行

我把R20.4.8版的编译了上传上来了，这个版本没问题：https://blog.zeruns.tech/archives/562.html

**Comment by lePig** [comment]
@zeruns  好的谢谢。 我晚点看看。想问一下，你编译的这个固件除了酸酸乳，还有哪些插件？因为我只需要酸酸乳，如果插件太多 就不准备刷了。

**Comment by zeruns** [comment]
> @zeruns 好的谢谢。 我晚点看看。想问一下，你编译的这个固件除了酸酸乳，还有哪些插件？因为我只需要酸酸乳，如果插件太多 就不准备刷了。

![](https://img.zeruns.tech/2020/06/19/1.gif)

**Comment by lePig** [comment]
@zeruns Thinks

**Comment by zeruns** [comment]
> @zeruns Thanks

看评论区，文章中的是有问题的新版

**Comment by ivybridgei** [comment]
不止是软路由，我用硬路由也遇到这个问题了，5月的源码正常使用，6月末的有问题
