### ISSUE TITLE
最新源码DHCP分配列表 显示异常

### ISSUE THREAD

**Issue by tone88** [coolsnowwolf/lede#4825]
DHCP分配列表 设备信息重复显示，如图：

![photo_2020-06-16_22-35-49](https://user-images.githubusercontent.com/47731895/84788604-e0ca8700-b021-11ea-991f-19604422f743.jpg)

**Comment by liuyanantj** [comment]
的确 我的也是这种情况  暂时不影响上网  不知道什么时候能修复

**Comment by swxk521** [comment]
最新版有异常

**Comment by zjh1982** [comment]
刚想提问，原来不是我一个人的问题，不过开机时间长负载很高

**Comment by WXfeng-boy** [comment]
一样的问题

**Comment by helianling** [comment]
threads=$(cat /proc/cpuinfo | grep 'processor' | wc -l)

	for i in $(seq 1 $threads); do
    procd_open_instance $cfg$i
    procd_set_param command $PROG -C $CONFIGFILE -k -x /var/run/dnsmasq/dnsmasq."${cfg}"."$i".pid
    procd_set_param file $CONFIGFILE
    [ -n "$user_dhcpscript" ] && procd_set_param env USER_DHCPSCRIPT="$user_dhcpscript"
    procd_set_param respawn

    procd_add_jail dnsmasq ubus log
    procd_add_jail_mount $CONFIGFILE $TRUSTANCHORSFILE $HOSTFILE $RFC6761FILE $DHCPBOGUSHOSTNAMEFILE /etc/passwd /etc/group /etc/TZ /dev/null /dev/urandom $dnsmasqconffile $dnsmasqconfdir $resolvfile $user_dhcpscript /etc/hosts /etc/ethers /sbin/hotplug-call $EXTRA_MOUNT $DHCPSCRIPT
    procd_add_jail_mount_rw /var/run/dnsmasq/ $leasefile

    procd_close_instance
	done

**Comment by jlong0983** [comment]
### 同样遇到这个问题，不影响使用



![capture_20200618100559266](https://user-images.githubusercontent.com/43898243/84969959-5468b300-b14c-11ea-8edb-80dd5930d5f7.jpg)

**Comment by xiaoguoyi** [comment]
> 刚想提问，原来不是我一个人的问题，不过开机时间长负载很高

![image](https://user-images.githubusercontent.com/54239687/84972341-3baecc00-b151-11ea-8319-3e70b78cfed7.png)
我这个占用很大，不知道为啥

**Comment by jlong0983** [comment]
> > 刚想提问，原来不是我一个人的问题，不过开机时间长负载很高
> 
> ![image](https://user-images.githubusercontent.com/54239687/84972341-3baecc00-b151-11ea-8319-3e70b78cfed7.png)
> 我这个占用很大，不知道为啥

dnsmasq开多，nlbwmon的统计工作量增加了？猜的，不懂编程，留下了没技术的眼泪

**Comment by lloyd18** [comment]
同样
