### ISSUE TITLE
求教贴! 怎么在lede中编译出docker

### ISSUE THREAD

**Issue by qs-lll** [coolsnowwolf/lede#4828]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

求教贴! 怎么在lede中使用docker

Q：是否搜索了issue (使用 "x" 选择)
* 

- [x]  没有类似的issue

### (1) 具体问题

A：newifi 3 (d2) 可以编译出带docker的固件吗!我尝试了24小时也没结果,故求助

### (2) 路由器型号和固件版本

A：newifi3

### (3) 详细日志

A：luci-application-中无法找到 luci-app-docker(文件夹里是有的 重复拉取了很多遍,并不感觉会漏掉)
      luci-library 中打开了 docker选项

**Comment by martin0607** [comment]
硬路由就不要玩docker了

**Comment by liuyanantj** [comment]
硬件性能和存储空间都不允许的  上软路由可破

**Comment by cattypapa** [comment]
你这个new wifi...还是老老实实做一个ap吧，想上docker，最便宜的方案，买个n1或者r2s

**Comment by qs-lll** [comment]
好吧 我不配
