### ISSUE TITLE
BBR无法安装。

### ISSUE THREAD

**Issue by muziyulin** [coolsnowwolf/lede#483]
你好，BBR加速装不了，请问在编译的时候怎么选择内核14.14以上的版本呢？

**Comment by LGA1150** [comment]
`curl https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/868.patch | patch -p1`
然后 `make menuconfig` 选择 Kernel -> Network support -> kmod-tcp-bbr

**Comment by muziyulin** [comment]
谢谢，用了你的补丁，好了。

**Comment by MxCen** [comment]
curl https://github.com/lede-project/source/commit/dd59498335b0ff99a37b09b9fd30f8388d15bb43.patch | patch -p1

默认使用BBR加速

**Comment by MxCen** [comment]
`curl https://github.com/lede-project/source/commit/dd59498335b0ff99a37b09b9fd30f8388d15bb43.patch | patch -p1`
默认使用BBR
