### ISSUE TITLE
编译出来的文件有好几个bin文件

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [coolsnowwolf/lede#4830]
config.seed
openwrt-ramips-mt7620-asus_rt-n14u.manifest
openwrt-ramips-mt7620-asus_rt-n14u-initramfs-kernel.bin
openwrt-ramips-mt7620-asus_rt-n14u-squashfs-sysupgrade.bin
sha256sums

编译出来有这么多文件，有的型号甚至3个bin，请问这些bin有什么区别吗？有没有必要全部安装

**Comment by jw10126121** [comment]
这是正常的。。各个.bin有自己的作用，建议先去查清楚。。。。

**Comment by ggllioio** [comment]
普通刷机用这个openwrt-ramips-mt7620-asus_rt-n14u-squashfs-sysupgrade.bin

**Comment by Jack-s-cmd** [comment]
squashfs-sysupgrade.bin 普通刷机文件
initramfs-kernel.bin所有的配置在路由器重启后都不能保留
