### ISSUE TITLE
是否应该现在跟进升级到 5.4 内核的意见收集

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#4831]
关于是否应该现在跟进升级到 5.4 内核的意见收集

升级到 5.4 内核将获得：
1. 更及时的内核补丁支持
2. 新硬件的驱动，例如 AMD Zen2 APU 的 GPU 解码，2.5Gbps 各种网卡的支持， 新的 ARM 处理器例如 IPQ8xxx 和 IPQ6xxx 支持等
3. 新的 DSA 网卡模型，例如 MT7503 可以强制指定每一个端口的速率解决掉线问题
.... 等等

升级到 5.4 内核将失去的：
1. 效能。 5.4 内核的 Flow 比 4.19 慢了 10-18% 以上，低端硬件特别明显。
2. 闭源驱动，例如 K2P 的驱动并没有在 5.4 内核中被支持
3. 更多的 Bug ，因为 5.4 不是正式 LTS 内核，也没有 stable release 的 OpenWrt 源码
4. 5.4 内核的 DSA 驱动不支持 VLAN 交换机配置
5. MAC80211 的 5.4 无线驱动目前测试过没有一个版本是好用的，要不就速率极低

附上 AC2100 无线性能测试性能图表， 分别为目前我的 OP 分支，集客， 官方 5.4 Snapshot 无线

![image](https://user-images.githubusercontent.com/31687149/85953706-00a86600-b9a5-11ea-8847-ad48f95e4a51.png)

PS: 5.4 内核寿命延长了，变为 LTS 了

大家意见如何？

**Comment by EuropeanWithSSR** [comment]
不要，k2p再用5年

**Comment by frely** [comment]
没有新硬件，不更新。

**Comment by 5t-RawBeRry** [comment]
做个 5.4  的分支？

**Comment by kisaragychihaya** [comment]
反对，稳定好用才是最要紧

**Comment by benchzjb** [comment]
不追新，路由硬件更换速度不高

**Comment by tianmotrue** [comment]
不要。反对！不更

**Comment by xqiushi** [comment]
不要，稳定才好。

**Comment by 305267382** [comment]
等LTS的内核出来再升级

**Comment by naoki66** [comment]
x64 x86 支持

**Comment by AmadeusGhost** [comment]
个人不建议现在就升级，kernel 5.4 需要 mac80211 5.4 及以上，然而官方现在的无线稳定性和最新 5.7-rc3 的性能都不大好
不说无线的话，其实 5.4 内核在 ipq40xx/x86 上用着也没啥差

**Comment by tjlive** [comment]
反对，或者做个 5.4 的分支

**Comment by scllen** [comment]
不建议更新 5.4 内核

**Comment by martin0607** [comment]
单独x86更新5.4？

**Comment by liuyanantj** [comment]
不建议跟新  没有这方面的需求  大家的网络是不是也没有达到这个级别了

**Comment by alvazhang79** [comment]
个人认为，稳定高效才是王道。

**Comment by bobstone007** [comment]
当前版本很好，稳定又高效

**Comment by Lasx** [comment]
x86的可以试试，硬路由就算了吧

**Comment by hcym** [comment]
armv8的强烈推荐，x86无所谓，看大雕心情😙😂

**Comment by sxf5487** [comment]
不建议更新，如果确实需要的话建议拉个分支。

**Comment by zcluo** [comment]
x64 x86 支持

**Comment by spacerip-per** [comment]
等下一个longterm版本再升级

**Comment by ggllioio** [comment]
等下个lts内核

**Comment by qyh214** [comment]
建议稳定后再更吧，可以放到一个新分支里，或单独一个库里，如果有尝鲜的可以在那里。

路由器在稳定的同时，再提供很棒的功能挺重要的，如果各种蛋疼事情，反而不好。

内核除非变成LTS支持，不然并不建议，不是大家的硬件都能这么快与时俱进的。

**Comment by hxlls** [comment]
可以开test 分支。这样比较好，至于FLOW性能损失这个，因为Flow Offloading引起不少问题，所以我都是直接关闭的，也没看到对实际占用率有什么大影响，所以我认为暂时不需要考虑这个性能

**Comment by aizhouyi** [comment]
不建议升级也不建议新分支，权衡利弊。真有拿最新硬件去玩openwrt的吗，估计非常少非常少。稳定压倒一切，升级非lts内核，升级出更多的bug。做精一个分支我就觉得很赞。

**Comment by IDSSC** [comment]
与其维护一个不确定的内核，还不如花精力搞好现有的

**Comment by duanego** [comment]
nonono

**Comment by star-o0O** [comment]
应该上，不折腾和咸鱼有什么区别

**Comment by Promix953** [comment]
支持X86上5.4
PS：感觉issues里征求这个意见基本就决定了否定的居多

**Comment by mjyhj** [comment]
支持升级，关于那个效能平时都是提升50% 80% 100%什么的
现在才降低10-18%，丝毫不影响，下次再提升个50%即可

**Comment by qxzg** [comment]
不支持，作为一个路由器系统，我认为稳定才是第一要务，其他绝大多数问题都需要给稳定性让路。
况且支持时间这么短，上的话还会花很多时间折腾，感觉有点得不偿失？

**Comment by lxhao61** [comment]
反对，稳定好用才是最要紧!

**Comment by lxhao61** [comment]
> 可以开test 分支。这样比较好，至于FLOW性能损失这个，因为Flow Offloading引起不少问题，所以我都是直接关闭的，也没看到对实际占用率有什么大影响，所以我认为暂时不需要考虑这个性能

就是！我从不编译Flow Offloading！

**Comment by BOBINIUNIU** [comment]
虽然我用x86，性能啥的无所谓，不过建议还是等等再说，万一有内核bug很麻烦，牵一发而动全身。目前的4.19版本已经比较稳定了，想要折腾的自己开分支吧。

**Comment by ihuaer** [comment]
路由器稳定最重要
新功能可以放近测试项目里

**Comment by ITdesk01** [comment]
建议增加新分支，虽然内核时间较短，性能下降，但总体来说可以试试水，为以后新设备铺路，毕竟现在wifi6价格血拼如此低，可以预想的，未来5G 千兆 wifi6

**Comment by KevinMX** [comment]
对于路由器来说，稳定好用才是最重要的，为了追新失去太多不太值得。对于部分设备有必要升级5.4内核的可以考虑单开新分支/单独支持（虽然这样会稍微增大工作量吧，各位辛苦了:）。
（另外，Linux 5.4 LTS不是到2024才会EOL吗？ Link: [The Linux Kernel Archives](https://www.kernel.org/category/releases.html)）

**Comment by PandaEgg** [comment]
反对。稳定好用才是王道

**Comment by jzhou404** [comment]
对于路由器来说，稳定好用才是最重要的. 不建议更新 5.4 内核

**Comment by nivalxer** [comment]
建议等内核LTS。
不过可以考虑先建立分支，包括mac80211、DSA改动相对较大，升级需要花费时间进行适配，可先行在分支上进行测试。

**Comment by maxjove** [comment]
不要

**Comment by waynon** [comment]
https://www.kernel.org/category/releases.html
Linux内核官网上写的不是支持到2025年12月吗？
建议升级到5.4

**Comment by shenzt68** [comment]
可以弄个5.4分支

**Comment by ptsa** [comment]
> 可以弄个5.4分支

+1

**Comment by ricksuzade-maker** [comment]
5.4是官方的LTS内核，稳定性应该没问题，放心用吧

**Comment by pirately** [comment]
支持升级

**Comment by ricksuzade-maker** [comment]
其实理由只有一条，koolshare已经升级5.4了，再不升就被超过了。

**Comment by xtwz** [comment]
不要，稳定才好。

**Comment by stock169** [comment]
升吧

**Comment by Jefffish09** [comment]
不更新。稳定是第一位。要折腾or尝新，可以新开分支。主分支还是要稳住。

**Comment by ricksuzade-maker** [comment]
都玩软路由了，何必在折腾硬路由，直接用原厂固件不就行了吗

**Comment by liwenjie119** [comment]
5.4的生命周期延长到2025年，但是仍然不是lts

**Comment by mumuou** [comment]
X86可以单独搞一个选项到5.4，其它的没有必要~~~

**Comment by biozzl** [comment]
没有新硬件，不更新。

**Comment by lqh280** [comment]
维稳重要，不追新~辛苦了

**Comment by Biglilo** [comment]
5.4是长期更新版本，升噻。

感谢L大和各位开发人员的努力。

**Comment by OldTaoge** [comment]
5.4虽然有很多新特性，但Openwrt项目是针对嵌入式设备的Linux操作系统。
但现在嵌入式设备的性能以及一代机皇K2P的原因，加之支持很短，付出的精力和收益不成正比

**Comment by zcluo** [comment]
> 5.4是长期更新版本，升噻。
> 
> 感谢L大和各位开发人员的努力。

好像续命了

**Comment by xakaff** [comment]
本人亲测 lienaol 5.4.32 master内核三个月使用体验，非上面无脑评论：
1、5.4内核使用非常稳定，无内存泄漏及长期使用网络延迟等不稳定现象，master分支已经非常成熟，为何不更新；
2.、5.4内核比4.19内核的cpu占用率和温度下降20%，4.19内核无主动散热温度50度时，5.4内核在42度左右，新内核效能机制已经体现无疑；
3、linux官方5.4内核已经是长期支持版本，连ubuntu和PVE都已升为此版本或更高版本，为何众人还是痴迷于老版本不做改变，并且我的OMV主机已经官方升为5.6内核并使用非常稳定，openwrt的使用者都是以最新为乐，稳定的同时最求最佳性能也是主要的目标，L大也是新技术的倡导者，个人建议还是有最新内核技术为佳。谢谢L大长期以来给我们带来最新openwrt的体验。谢谢

**Comment by xakaff** [comment]
补充：本人四台路由主机，E2 1275L v3 、E3 1230L v3、J3160、J1900 这四台用在我的四套房子里，不做pve虚拟，单独主机使用。之所以四台主机一直使用lienol固件就是因为L大的固件是4,19，原因就如上面所述。如果大家对lienol master分支固件最后一版有优化就知道其固件的优势，虽然目前早已停止更新。

**Comment by lonee6** [comment]
可以更新啊，毕竟将来都是要支持新硬件的。想稳定的，停留在目前版本就好。

**Comment by fhbyljj** [comment]
> 本人亲测 lienaol 5.4.32 master内核三个月使用体验，非上面无脑评论：
> 1、5.4内核使用非常稳定，无内存泄漏及长期使用网络延迟等不稳定现象，master分支已经非常成熟，为何不更新；
> 2.、5.4内核比4.19内核的cpu占用率和温度下降20%，4.19内核无主动散热温度50度时，5.4内核在42度左右，新内核效能机制已经体现无疑；
> 3、linux官方5.4内核已经是长期支持版本，连ubuntu和PVE都已升为此版本或更高版本，为何众人还是痴迷于老版本不做改变，并且我的OMV主机已经官方升为5.6内核并使用非常稳定，openwrt的使用者都是以最新为乐，稳定的同时最求最佳性能也是主要的目标，L大也是新技术的倡导者，个人建议还是有最新内核技术为佳。谢谢L大长期以来给我们带来最新openwrt的体验。谢谢

同感，希望L大不要被楼上的人忽悠了，最好就软路由单独弄出一个分支，凭什么让我们一部分用户等一群K2P顽固党？？？？？？

**Comment by ricksuzade-maker** [comment]
K2P总归不支持802.11ax新标准，信号再好速率也无法再快，迟早也会被淘汰的，何必恋旧。

**Comment by MeIsReallyBa** [comment]
k2p的5.0.4.0驱动可以支持新内核，新内核改过的部分api在新驱动通过条件编译已经支持了，国外论坛貌似也有人在5.x内核跑起来了。

**Comment by qyh214** [comment]
大雕更新了主帖，表明这个不是LTS版本哎，这可能就不是长久之计了。

**Comment by Cathgao** [comment]
全部的LEDE玩家要为一部分的k2旧硬件玩家让步，让我看呆了。既然5.4是LTS为何不升？玩LEDE不就是追求更新的系统吗？我还玩BCM的光猫呢，是不是还得为我回退到3.X内核？

**Comment by accors** [comment]
没有特别需求可以升级，建议开个新的分支。

**Comment by fhbyljj** [comment]
> 全部的LEDE玩家要为一部分的k2旧硬件玩家让步，让我看呆了。既然5.4是LTS为何不升？玩LEDE不就是追求更新的系统吗？我还玩BCM的光猫呢，是不是还得为我回退到3.X内核？

还有一部分是软路由追求稳定的，然而软路由这东西，玩的不就是折腾？

**Comment by hcym** [comment]
大雕定了吧，改不改都不错都可以。中国人讲民主不是穷开心吗

**Comment by MeIsReallyBa** [comment]
k2p测了下，5.4内核+闭源驱动+CPU 频率1G，iperf3测得wan to 5g速率 580+M，比4.14强点。

**Comment by Cathgao** [comment]
> > 全部的LEDE玩家要为一部分的k2旧硬件玩家让步，让我看呆了。既然5.4是LTS为何不升？玩LEDE不就是追求更新的系统吗？我还玩BCM的光猫呢，是不是还得为我回退到3.X内核？
> 
> 还有一部分是软路由追求稳定的，然而软路由这东西，玩的不就是折腾？

追求稳定的就不会天天来拉源码更新去刷机，刷好了就不会动他了。所以那些说为了稳定而放弃新内核的都是伪需求，一边喊着要稳定一边天天重启刷机，言行不一。

**Comment by conchz** [comment]
不建议更新 5.4 内核，稳定高效最重要

**Comment by lqzhj** [comment]
墙烈要求升级5.4  追新就是玩openwrt精髓之一

**Comment by dovegq** [comment]
x86表示没有更新的必要
下个LTS内核再说吧

**Comment by goofysun** [comment]
5.4 整体其实挺稳定的，只是 官方最新板本的UPNP 不大好用 一直没用。

**Comment by Bnosora** [comment]
如果升5.4不难的话，我认为应该升上去。如果有一定难度（比如各插件需要适配/修bug）我认为不应该升。毕竟5.4和4.19的EOL时间点只差了1年，不管现在换不换，2024/25年就得换新内核了。不如等快到EOL的时候再换最新的LTS版本。

**Comment by sqliuchang** [comment]
我还在奇怪呢，op官方源码早就升级到5.x了，怎么大雕一直没跟进啊。
至少X86先升上去吧，其他架构可以再看看情况，等适配的差不多稳定了再跟进。

**Comment by guolongchu** [comment]
不要升级，反对，我觉得应给等5.4稳定后再升级

**Comment by betaxab** [comment]
支持更新，不能老抱着过时的东西不放，老设备毕竟要淘汰的，x86 10G 网卡及 ARMv8-A 已经成为了主流，如果要顾及老设备，可建立新分支。

**Comment by xxp2277** [comment]
建议新开分支做5.4内核，老内核少维护（修复bug不增加功能）以便使用4.19内核的老设备还能稳定使用。

**Comment by liwenjie119** [comment]
把当前的切到另一个分支，主分支继续升级到5.4吧

**Comment by 9l** [comment]
升

**Comment by zcluo** [comment]
上5.4用DOCKER PLEX硬解没什么问题，4.19运行一段就会挂掉。。。我自己这边是这样不知道别人会不会有类似的问题哈

**Comment by willaytoun** [comment]
个人认为op是在稳定和追新的平衡上偏追新的，如果5.4没有太多BUG的话我支持升到5.4。

**Comment by oXnMe** [comment]
支持升级

**Comment by ilongli** [comment]
既然L大提出了这个issue了，说明是有意愿升的。旧的东西总归要淘汰，我支持升。来到这里的，都是爱折腾的。

**Comment by OldTaoge** [comment]
建议更新，要坚持求新，与时俱进，

**Comment by ggllioio** [comment]
几天没来5.4居然lts了？！那么不用想，升就一个字！

**Comment by crosys** [comment]
更喜欢新的，这也是大势所趋。

**Comment by lyvivian0077** [comment]
生命在于折腾,如果不追求新技术新事物,怎么适应新时代.
旧的设备注定终究是要被淘汰的.
新的kernel是有它存在的理由的.
还有在我看来,那些说要求稳定的人,你用的是AS路由还是Core路由?
一个家用路由,再怎么稳定也无法抗拒断电,断网的意外事件.你家又不是DATA Center.
过几年也许会10G光纤入户时,不知道你们这些人是否还是一样的态度.

**Comment by hyird** [comment]
我只想 packages 大部分包整体先更新一下。

**Comment by hyird** [comment]
另外  K2P在5.4内核上的7615闭源驱动 已经有了
https://github.com/Lienol/openwrt/commit/5c1aa1dc65f11531c71c796ddab50eb8eed482fc

**Comment by chenxudong2020** [comment]
> 关于是否应该现在跟进升级到 5.4 内核的意见收集
> 
> 升级到 5.4 内核将获得：
> 
> 1. 更及时的内核补丁支持
> 2. 新硬件的驱动，例如 AMD Zen2 APU 的 GPU 解码，2.5Gbps 各种网卡的支持， 新的 ARM 处理器例如 IPQ8xxx 和 IPQ6xxx 支持等
> 3. 新的 DSA 网卡模型，例如 MT7503 可以强制指定每一个端口的速率解决掉线问题
>    .... 等等
> 
> 升级到 5.4 内核将失去的：
> 
> 1. 效能。 5.4 内核的 Flow 比 4.19 慢了 10-18% 以上，低端硬件特别明显。
> 2. 闭源驱动，例如 K2P 的驱动并没有在 5.4 内核中被支持
> 3. 更多的 Bug ，因为 5.4 不是正式 LTS 内核，也没有 stable release 的 OpenWrt 源码
> 4. 5.4 内核的 DSA 驱动不支持 VLAN 交换机配置
> 5. MAC80211 的 5.4 无线驱动目前测试过没有一个版本是好用的，要不就速率极低
> 
> PS: 5.4 内核寿命延长了，变为 LTS 了
> 
> 大家意见如何？

做个 5.4 的分支

**Comment by kongfl888** [comment]
没必要，再等半年再说

**Comment by Myoko** [comment]
稳定才是最好的

**Comment by chenxudong2020** [comment]
> 关于是否应该现在跟进升级到 5.4 内核的意见收集
> 
> 升级到 5.4 内核将获得：
> 
> 1. 更及时的内核补丁支持
> 2. 新硬件的驱动，例如 AMD Zen2 APU 的 GPU 解码，2.5Gbps 各种网卡的支持， 新的 ARM 处理器例如 IPQ8xxx 和 IPQ6xxx 支持等
> 3. 新的 DSA 网卡模型，例如 MT7503 可以强制指定每一个端口的速率解决掉线问题
>    .... 等等
> 
> 升级到 5.4 内核将失去的：
> 
> 1. 效能。 5.4 内核的 Flow 比 4.19 慢了 10-18% 以上，低端硬件特别明显。
> 2. 闭源驱动，例如 K2P 的驱动并没有在 5.4 内核中被支持
> 3. 更多的 Bug ，因为 5.4 不是正式 LTS 内核，也没有 stable release 的 OpenWrt 源码
> 4. 5.4 内核的 DSA 驱动不支持 VLAN 交换机配置
> 5. MAC80211 的 5.4 无线驱动目前测试过没有一个版本是好用的，要不就速率极低
> 
> PS: 5.4 内核寿命延长了，变为 LTS 了
> 
> 大家意见如何？更新把早晚的事

**Comment by lloyd18** [comment]
支持升级

**Comment by haig233** [comment]
支持升级！！！！

**Comment by osxdiy** [comment]
支持升级

**Comment by cabbyjing** [comment]
支持升级

**Comment by superstarjlj** [comment]
支持升级

**Comment by one02free** [comment]
**支持升级！**

**Comment by 702781** [comment]
肯定升级好啊！大神，瞧您的了！

**Comment by hzjnet** [comment]
稳定和安全才是最好的，没必要！

**Comment by gause555** [comment]
我觉得可以做个分叉，旧内核的版本可以逐渐减少更新，除非有大的bug和重要功能，新内核版本可以开始跟进这样会比较好

**Comment by Mircc** [comment]
不要，k2p再用5年

**Comment by cnclg** [comment]
支持升级，做个X86的分支，用5.0.

**Comment by hue715** [comment]
X86可以跟进升级到5.4

**Comment by xosadmin** [comment]
稳定为主吧，目前5.4还是SNAPSHOT，不过部分硬件（如x86）可以升级到5.4

**Comment by coolsnowwolf** [comment]
> 另外 K2P在5.4内核上的7615闭源驱动 已经有了
> [Lienol/openwrt@5c1aa1d](https://github.com/Lienol/openwrt/commit/5c1aa1dc65f11531c71c796ddab50eb8eed482fc)

感谢提供这个信息，会再次评估

**Comment by cattypapa** [comment]
为啥不升，赶紧升

**Comment by zerofo** [comment]
升吧

**Comment by chenxudong2020** [comment]
升级 内核支持是逐步完善的，如果不去升级就没法推动



---原始邮件---
发件人: "zerofo"<notifications@github.com&gt;
发送时间: 2020年7月1日(周三) 下午3:00
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"chenxudong2020"<872603935@qq.com&gt;;
主题: Re: [coolsnowwolf/lede] 是否应该现在跟进升级到 5.4 内核的意见收集 (#4831)




 
升吧

**Comment by q-server** [comment]
不要，不追求新的，追求稳定的~

**Comment by liebesu** [comment]
建议两手准备，虽然可能会分配一部分精力，但还是技术还是要折腾的，5.4已经lts，可以分支去做，毕竟技术要迭代的

**Comment by vitalpig** [comment]
5.4已经lts了，支持升级。可以先给5.4另开分支，逐步完善后再转为主分支

**Comment by carlyang1986** [comment]
建议另外开一个分支

**Comment by cg203001** [comment]
升

**Comment by aceslup** [comment]
硬路由才合适升级了吧，暂时等等可好？

**Comment by Pantheon-Paradoxes** [comment]
5.4 up up

**Comment by aglent** [comment]
性能到底是提升还是下降啊？
用的N3540软路由和acrh17硬路由

**Comment by hue715** [comment]
> 硬路由才合适升级了吧，暂时等等可好？
不想体验5.4的，可以去https://github.com/coolsnowwolf/openwrt下载，其中的lede-17.01分支就是老版本openwrt19.07。

**Comment by Margular** [comment]
我认为任何的更新都要考虑兼容性和稳定性，当然更新后能获得新的功能，只能在这之间做一个取舍，是否应该在经过充分的测试之后确认固件无明显BUG后再发行？比起新功能我更关心兼容性和稳定性，毕竟新东西这方面问题会层出不穷，是否可以开一个新分支经过充分测试之后再合入master分支？

**Comment by xiaotian0127** [comment]
x86，支持以下，另外建议新出一分支，把4.19作为一个老版本不更新只维护，5.4作为主分支

**Comment by hue715** [comment]
> x86，支持以下，另外建议新出一分支，把4.19作为一个老版本不更新只维护，5.4作为主分支

要老版本分支，可以去https://github.com/coolsnowwolf/openwrt
下载，其中的lede-17.01分支就是老版本（以前的openwrt 19.07）

**Comment by xiaotian0127** [comment]
> > x86，支持以下，另外建议新出一分支，把4.19作为一个老版本不更新只维护，5.4作为主分支
> 
> 要老版本分支，可以去https://github.com/coolsnowwolf/openwrt
> 下载，其中的lede-17.01分支就是老版本（以前的openwrt 19.07）

thanks！

**Comment by aceslup** [comment]
> > 硬路由才合适升级了吧，暂时等等可好？
> 
> 不想体验5.4的，可以去https://github.com/coolsnowwolf/openwrt
> 下载，其中的lede-17.01分支就是老版本openwrt19.07。

感谢兄台。https://github.com/coolsnowwolf/openwrt 不知道是何时的项目，不过看起来也是大雕的。能再问你个问题吗？lede-17.01分支是老内核。其项目还有个master分支，是什么内容的？

**Comment by hue715** [comment]
> > > 硬路由才合适升级了吧，暂时等等可好？
> > 
> > 
> > 不想体验5.4的，可以去https://github.com/coolsnowwolf/openwrt
> > 下载，其中的lede-17.01分支就是老版本openwrt19.07。
> 
> 感谢兄台。https://github.com/coolsnowwolf/openwrt 不知道是何时的项目，不过看起来也是大雕的。能再问你个问题吗？lede-17.01分支是老内核。其项目还有个master分支，是什么内容的？

你可以看一下commit，大雕最近更新了这个项目，把原来lede的内容合并过去了，那个项目的Master分支是很老的lede系统（17版本）。

**Comment by zeruns** [comment]
建议开新分支两个同时并存

**Comment by zhangguanzhang** [comment]
稳定了就升吧

**Comment by hcym** [comment]
armv8非常好，尤其是haproxy新版也可以默认多线程。负载均衡完美。x86编译过了还没刷，估计没问题，感谢大雕感谢cctv

**Comment by dingpengyu** [comment]
个人认为假如可以保证稳定性的前提下，可以更新5.4的内核。

**Comment by kmahyyg** [comment]
5.4 作为 5.x 上目前第一个 LTS 版本，以我目前长期使用 Arch Linux 保持内核最新的一些体会来说，存在一些不足，很多厂商为了保证功能能进入 LTS 版本，在里面加入了并不完善的代码。建议在确定稳定的情况下升级 5.4 LTS。

升级到高版本内核是未来不可避免的趋势，我们只能顺势而行。高版本内核带来的安全补丁、运行性能优化是我们应该看到的，固然网络性能可能略有下降，但也应该看到其他的面，例如安全，我想每个人都不希望看到自己的路由器成为攻击自己局域网设备的那个攻击集中点。

**Comment by dingpengyu** [comment]
> 5.4 作为 5.x 上目前第一个 LTS 版本，以我目前长期使用 Arch Linux 保持内核最新的一些体会来说，存在一些不足，很多厂商为了保证功能能进入 LTS 版本，在里面加入了并不完善的代码。建议在确定稳定的情况下升级 5.4 LTS。
> 
> 升级到高版本内核是未来不可避免的趋势，我们只能顺势而行。高版本内核带来的安全补丁、运行性能优化是我们应该看到的，固然网络性能可能略有下降，但也应该看到其他的面，例如安全，我想每个人都不希望看到自己的路由器成为攻击自己局域网设备的那个攻击集中点。

支持 +1

**Comment by shu0802** [comment]
首先赞成升级。但是步伐有点大，很多固件的准备工作都没有弄好，这是会对使用者尤其是编译者造成很大的不便。

**Comment by kris2014** [comment]
如果能够保持两条线维护，当然是欢迎了，不过对lean大的压力可定也很大。

刚刚编译了acrh17的固件，发现最新版本的vlan上跟4.x版本比少了一个wan的选项，另外adblock也不能正确加载blocklist。因此我目前的旁路由配置无法正常运作，不得不退回旧版本。

**Comment by ttmi9002** [comment]
老硬件就不要升级5.4了，还是用原来的4.14，留4.14的分支给老硬件使用吧，5.4性能降太多了。。

**Comment by jzhou404** [comment]
周末编译了coolsnowwolf 最新基于5.4的固件， 配置文件和4.19内核的配置兼容有问题。

直接升级无法上网，清除配置然后恢复配置， 看着一切正常， 但无法上网。 

复位， 从0开始重新配置， 才一切正常。 给大家汇报一下。

**Comment by jzhou404** [comment]
个人建议， 出于维护的精力耗费，还是先维持4.19稳定线， 比较好。

驱动， 性能， 都比较成熟了。 等新的硬件多起来， BUG也差不多，闭源驱动也出来了， 再迁移到5.4不迟

**Comment by hcym** [comment]
x64和armv8都非常的好，其他没有用，mtk就是padavan啦🤣
