### ISSUE TITLE
一个小bug，DHCP 租约会显示重复条目

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#4834]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题
DHCP 租约会显示重复条目
应该是跟这条修改有关
dnsmasq: add auto multiple service instances for dns performance boost
A：

### (2) 路由器型号和固件版本
x86   编译于Jun 17, 2020
A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
这个由DNSMAQ 写入的，很难避免，没有进程锁

**Comment by dolphinpaopao** [comment]
> 这个由DNSMAQ 写入的，很难避免，没有进程锁

刚刚看了一下dnsmasq更新到了2.81版本，粗略浏览更新日志里面提到DHCP服务器分配地址改良不知道是否有助于这个问题的缓解。个人使用暂时还没有碰到重复条目。

**Comment by BOBINIUNIU** [comment]
> 这个由DNSMAQ 写入的，很难避免，没有进程锁

不知道是否可以加一段字符串去重的代码来修复这个问题。当然，如果刷新频繁也可能会造成CPU使用率过高。
