### ISSUE TITLE
如何提取LUCI中的IPK文件离线包

### ISSUE THREAD

**Issue by pmxEr5lZwZ** [coolsnowwolf/lede#4837]
我看luci中有很多很好的插件，想请教大神，如何提取luci中的离线安装包？

提取离线包理想中的好处（不知道我这么想对不对）：
1.假如插件原作者跑路删库，那么编译就失败了对吧？离线安装包还能恢复从前的插件
2.插件式管理，假如插件编译过多，体积较大，超过了闪存导致刷不了，如果有离线包，我可以精简编译安装，然后想用哪个插件安装哪个，不想用的再卸载掉
3.【这条不知道这样想对不对】LEDE不管哪个版本，我只要把离线安装包安装进去，就避免了二次编译
4.【这条更不知道这样想对不对】路由器不管哪个型号，我只要把离线安装包安装进去，就避免了二次编译

现在问题来了：如何提取luci中的离线安装包并成为lede可以安装的ipk格式？

**Comment by goldkeyber112** [comment]
你可以编译sdk，以后用sdk再编译ipk

**Comment by zeruns** [comment]
在编译生成的bin文件夹中有很多IPK文件
