### ISSUE TITLE
openwrt/潘多拉跟uu等加速器内网加速ip冲突问题

### ISSUE THREAD

**Issue by Csania-AM** [coolsnowwolf/lede#4841]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：openwrt、潘多拉固件跟PC端uu，腾通加速器对局域网内的PS4/NS加速造成IP冲突，比如我用的腾讯加速器，需要自己在NS上填写IP：10.6.0.1 /网关：10.6.0.2，此时NS提示局域网内已存在对应IP，无法正常连上加速器，打开路由器看路由表内已经存在上述两个IP。经搜索，不止我一个人出现这种情况，网上有人给出的方法如下：
https://zhuanlan.zhihu.com/p/121826205
似乎是使用了静态路由，对IP进行了固定，此方法下会有DNS的问题，当然也有配套的解决方案。但又因为在之前的老毛子固件上是没有出现此问题的，感觉会有更好的解决办法，但是又不知道从何下手，特地过来询问。

### (2) 路由器型号和固件版本

A：路由型号：K2P
      固件版本：PandoraBox R20.3.8 By Lean

**Comment by fhbyljj** [comment]
J1900软路由没遇到过
