### ISSUE TITLE
关于ssrplus的界面语言问题

### ISSUE THREAD

**Issue by Kevin19941121** [coolsnowwolf/lede#4848]
我选择的语言是英文 ssrplus看上去确实是英文
但我发现在添加节点里面 有个导入配置信息 它却是中文显示 这让强迫症的我非常不爽 我真的非常支持大雕 开发了这个特别好的app 但如果不行的话 我只能用回中文界面  但我还是很想知道怎么把它变成全英文界面 还是因为我不会设置
还有一个是在编译大雕固件中 系统语言是中文打星号被锁定的 我想知道如何把它取消 还是取消后会对编译产生影响 我学了一点皮毛 知道如何编译 但还是希望有大神解答！非常感谢！

**Comment by 9l** [comment]
你发个 pr 吧
