### ISSUE TITLE
adbyby占用太大了？

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#485]
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
13866 13862 root     R    44388   9%  20% /usr/share/adbyby/adbyby
    7     2 root     SW       0   0%   1% [ksoftirqd/0]
用的是全局模式。开始占用率不大，随时间增加，占用率越来越大！

**Comment by shenzt68** [comment]
双增加情况：
PID	用户名	命令	CPU 使用率（%）	内存使用率（%）
1226	root	/usr/share/adbyby/adbyby	0%	  0%	
1229	root	/usr/share/adbyby/adbyby	45%	  9%
怎么会出现两个相同进程呢？

**Comment by tomerilery** [comment]
adbyby占用内存本来开销就大，路由能正常运行你管那么多做什么呢，内存不就是拿来用的么
