### ISSUE TITLE
请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成）

### ISSUE THREAD

**Issue by wzbbstx** [coolsnowwolf/lede#4855]
请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成）

驱动地址如下：
https://www.realtek.com/zh-tw/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

**Comment by martin0607** [comment]
就算不集成自己也可以下载替换啊

**Comment by zeruns** [comment]
> 就算不集成自己也可以下载替换啊

可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html

**Comment by zeruns** [comment]
可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html

**Comment by zeruns** [comment]
> 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成）
> 
> 驱动地址如下：
> https://www.realtek.com/zh-tw/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html
文章中的git驱动的地址可以在GitHub搜索这款驱动的源码地址替换上去，刚刚我搜过有的

**Comment by wzbbstx** [comment]
果然是大神。不过俺是编程苦手啊。。。能不能辛苦把8125B的驱动加入呀（之前的8125老驱动无法正常驱动8125B芯片），谢谢了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zeruns"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上9:11
收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送:&nbsp;"风之痕 [̲̅V̲̅I̲̅P̲̅]"<3406508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成） (#4855)





  
就算不集成自己也可以下载替换啊
  
可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html

**Comment by zeruns** [comment]
> 果然是大神。不过俺是编程苦手啊。。。能不能辛苦把8125B的驱动加入呀（之前的8125老驱动无法正常驱动8125B芯片），谢谢了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"zeruns"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月22日(星期一) 晚上9:11 收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;; 抄送:&nbsp;"风之痕 [̲̅V̲̅I̲̅P̲̅]"<3406508@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [coolsnowwolf/lede] 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成） (#4855) 就算不集成自己也可以下载替换啊 可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

详细教程都给出来了，自己动手

**Comment by wzbbstx** [comment]
好吧。大神。这两天我折腾下。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zeruns"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上9:50
收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送:&nbsp;"风之痕 [̲̅V̲̅I̲̅P̲̅]"<3406508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成） (#4855)





  
果然是大神。不过俺是编程苦手啊。。。能不能辛苦把8125B的驱动加入呀（之前的8125老驱动无法正常驱动8125B芯片），谢谢了。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"zeruns"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月22日(星期一) 晚上9:11 收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;; 抄送:&nbsp;"风之痕 [̲̅V̲̅I̲̅P̲̅]"<3406508@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [coolsnowwolf/lede] 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成） (#4855) 就算不集成自己也可以下载替换啊 可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
详细教程都给出来了，自己动手

**Comment by helianling** [comment]
现在代码中的驱动是去年的，只支持8125（A），不支持最新的8125B，把图片中的文件用官网最新的Linux驱动源码（同时支持8125和8125B）全部替换就好了，外层的Makefile建议也改成最新驱动版本号。
![image](https://user-images.githubusercontent.com/31648892/85349676-abe29680-b531-11ea-99f4-b778d22640ef.png)

**Comment by wzbbstx** [comment]
> 现在代码中的驱动是去年的，只支持8125（A），不支持最新的8125B，把图片中的文件用官网最新的Linux驱动源码（同时支持8125和8125B）全部替换就好了，外层的Makefile建议也改成最新驱动版本号。
> ![image](https://user-images.githubusercontent.com/31648892/85349676-abe29680-b531-11ea-99f4-b778d22640ef.png)

谢谢高手指点。晚上回家折腾！！！

**Comment by crosys** [comment]
> > 请Lede大神，早日支持RTL8125B与RTL8125芯片驱动(2.5G网卡，好多主板都集成）
> > 驱动地址如下：
> > https://www.realtek.com/zh-tw/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software
> 
> 可以参考我这篇文章编译其他驱动进去：https://blog.zeruns.tech/archives/565.html
> 文章中的git驱动的地址可以在GitHub搜索这款驱动的源码地址替换上去，刚刚我搜过有的

请教大大，RTL8156的2.5G USB网卡驱动按教程能搞定吗？

**Comment by goldkeyber112** [comment]
已增加支持
#4866

**Comment by laaArmy** [comment]
你好好看看人家叫啥
