### ISSUE TITLE
luci-app-v2ray-server 该插件设定协议为vmess,传输方式为tcp,伪装类型为http时，不生效

### ISSUE THREAD

**Issue by taowazi007** [coolsnowwolf/lede#4860]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：luci-app-v2ray-server 该插件设定协议为vmess,传输方式为tcp,伪装类型为http时，不生效

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：
   "inbound": {
     "port": 12366,
     "protocol": "vmess",
     "streamSettings": {
       "network": "tcp",
       "security": "none"
     },
     "settings": {
       "clients": [
         {
           "id": "fd00927a-b0c2-4629-aef7-d9ff15a9d722",
           "level": 1,
           "alterId": 16
         }
       ]
     }
   },

配置文件无正确设定

**Comment by swxk521** [comment]
有没有大佬修一下
