### ISSUE TITLE
重启恢复配置

### ISSUE THREAD

**Issue by lyj9768** [coolsnowwolf/lede#4869]
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：新编译的固件，每次重启都会恢复出厂设置，又要重新配置一遍（breed刷了kernel，后台不保留配置刷写了一次固件）

### (2) 路由器型号和固件版本

A：k2p，R20.6.18

**Comment by microlao** [comment]
固件太大了，我的也是这样，控制一下插件数量就行了。

**Comment by lyj9768** [comment]
> 固件太大了，我的也是这样，控制一下插件数量就行了。

确实是固件太大了，貌似k2p只容得下四五个插件。。
