### ISSUE TITLE
给我整懵了，都是J1900的软路由，同一个固件，店里那台，我店里每天下班会断电，偶尔早上打开会没法访问国内IP

### ISSUE THREAD

**Issue by fhbyljj** [coolsnowwolf/lede#4883]
### (1) 开机后偶尔无法访问国内IP，怀疑是SSRPLUS+的原因

A：

### (3) 详细日志
刚才出去了一会，回来后发现进不去后台管理页面了，所有设备断网，重启了一下日志没了.............

有相同问题的小伙伴么

**Comment by XiaoliChan** [comment]
我家里的软路由上个星期开始就这样，会自己莫名其妙的断电，有时候开了没多久就自己断电了

配置：
i3 3220 + 华硕的h61

后来怀疑是硬件问题，然后我换了块华南的b75（主要是图那个三年的质保），然后从昨天用到现在都没问题

**Comment by hcym** [comment]
蜗牛一直正常，没什么问题

**Comment by servicehost** [comment]
不要强行断电关机，用poweroff命令

**Comment by yizhilaohuli** [comment]
Compiled by Lusty on Jun.25, 2020

请找固件编译作者。

**Comment by huang826** [comment]
电源不稳？

**Comment by Erope** [comment]
开机后无法访问国内我也遇到过
但可能和SSR+无关
路由器本身可以访问国内/国外，但接入路由器的设备不可以(路由表都是正常的)，流量也可以正常到路由器，但无法正常转发
在开启SSR+后 透明代理实际上是使用路由器访问国外，所以造成这种情况
但具体原因我也不清楚
