### ISSUE TITLE
Generating index for package ./tcping_0.1-2_x86_64.ipk bash: line 6: 8: Bad file descriptor

### ISSUE THREAD

**Issue by zhiwen1987** [coolsnowwolf/lede#4889]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
A：Generating index for package ./tcping_0.1-2_x86_64.ipk
bash: line 6: 8: Bad file descriptor

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：Generating index for package ./tcping_0.1-2_x86_64.ipk
bash: line 6: 8: Bad file descriptor

**Comment by AmadeusGhost** [comment]
这个没影响，忽略即可
