### ISSUE TITLE
大佬的代码可以用openvswitch吗？

### ISSUE THREAD

**Issue by wjn111** [coolsnowwolf/lede#4892]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [√ ] 没有类似的issue

### (1) 具体问题

A：编译openvswitch功能的固件时报错

### (2) 路由器型号和固件版本

A：NETGEAR R6800         代码版本lede-master

### (3) 详细日志

A：报错说kmod_openvswitch与busybox会创建同一个目录

**Comment by hzjnet** [comment]
替换版本后能，最新版本某些模块编译有错，最近正常的配合是：openvswitch-gre-intree_4.14.180+2.11.1
