### ISSUE TITLE
ddns 无法自定义 

### ISSUE THREAD

**Issue by shzxm** [coolsnowwolf/lede#4894]
ddns 
服务提供商 选择 自定义 后
保存并应用 
会还原成默认第一项
![image](https://user-images.githubusercontent.com/9905297/86003877-0b1a3c80-ba45-11ea-87fe-7272f51d175b.png)

![image](https://user-images.githubusercontent.com/9905297/86003898-11a8b400-ba45-11ea-932e-aa9fce97f155.png)

脚本的权限已给
![image](https://user-images.githubusercontent.com/9905297/86004098-5af90380-ba45-11ea-941f-3ce2ce4af493.png)

**Comment by shzxm** [comment]
Openwrt Koolshare mod V2.35 r14297-5efd32232b

**Comment by dolphinpaopao** [comment]
> Openwrt Koolshare mod V2.35 r14297-5efd32232b

..........
koolshare≠coolsnowwolf

**Comment by shzxm** [comment]
emmm……都是同源嘛，所以问下哪位大佬知道问题在哪，或者有没有解决办法

dolphinpaopao <notifications@github.com>於 2020年6月29日 週一，20:51寫道：

**Comment by dolphinpaopao** [comment]
这个是开源项目，就算是同源也不一定能解决问题，我刚试了这里的ddns是可以自定义的。举例koolshare的ddns是0.1的版本有问题，这里的ddns是0.2版本没有问题，那也要去找koolshare那边阿。这边无人能解答。

**Comment by shzxm** [comment]
这不就好了嘛，我去卸载0.1装个0.2

dolphinpaopao <notifications@github.com>於 2020年6月29日 週一，21:19寫道：
