### ISSUE TITLE
网易云音乐解锁灰色音乐无法播放

### ISSUE THREAD

**Issue by xiexiaosheng** [coolsnowwolf/lede#4896]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：网易云音乐解锁灰色音乐。只加载不播放。

光猫拨号可以使用,路由器拨号不能使用。

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：

**Comment by xiexiaosheng** [comment]
光猫拨号可以，路由器拨号不行。

**Comment by xsm1997** [comment]
https://github.com/cnsilvan/UnblockNeteaseMusic/pull/23

已在原项目提交pr，等待合并后，再在本项目提交pr。

**Comment by xsm1997** [comment]
也可自行修改/etc/init.d/unblockmusic，取消UnblockNeteaseMusic运行时的-e flag，应该可以暂时解决windows客户端的问题。

**Comment by xiexiaosheng** [comment]
> [cnsilvan/UnblockNeteaseMusic#23](https://github.com/cnsilvan/UnblockNeteaseMusic/pull/23)
> 
> [pr，]，[pr]（窗口））

但是，我在光猫拨号可以，软路由拨号就不行。

**Comment by hxlls** [comment]
全新重新新编译，全新不保留配置安装就行了，我遇到过

**Comment by WROIATE** [comment]
> 也可自行修改/etc/init.d/unblockmusic，取消UnblockNeteaseMusic运行时的-e flag，应该可以暂时解决windows客户端的问题。

-e应该是为了解决ios的https，但是windows使用-e会出现问题，这个在原项目那可以查到
