### ISSUE TITLE
请教一个编译技巧的问题

### ISSUE THREAD

**Issue by ctw8989** [coolsnowwolf/lede#49]
经过几天的折腾，终于能编译几种架构的固件了，再次感谢大神的源码！！
现在请教一个问题：
      比如我在x86_64 下，   make menuconfig  选好自己要的软件和包，生成了.config，我想把生成的.config设成x86_64下的默认配置，当我从其他架构转回x86_64编译，会自动用回自己的配置。要如何做到呢？
我不知如何表达，大概就是这个意思。谢谢！

**Comment by ctw8989** [comment]
找到了这篇文章，发觉比较麻烦啊
http://blog.csdn.net/weiniliuchao/article/details/50295527

**Comment by coolsnowwolf** [comment]
save config ，然后下次 load 即可

**Comment by ctw8989** [comment]
嗯，也只能make menuconfig里面load一下了
