### ISSUE TITLE
openwrt如何釋放公網IP，獲取新的公網IP (WAN協議: DHCP客戶端)

### ISSUE THREAD

**Issue by hxhwing0522** [coolsnowwolf/lede#4904]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：HK家居網的WAN協議不是PPOE撥號的，是依靠"DHCP客戶端"獲得新的公網IP。
      以前用老毛子固件或其他路由時，每次點擊"斷開網絡"或重啟路由，都能夠獲得新的公網IP。
     不過刷了openwrt後，已經使用斷線﹑關掉WAN口再打開﹑重啟路由等各種方式，WAN口IPV4依然是同一個公網IP，沒法獲得新的公網IP。
     是不是openwrt固件里沒有釋放IP的設置，導致沒法獲得新IP?
     這個對我很重要，有時需要換一個公網IP。因為如果沒法獲得新公網IP，這個公網IP基本都不釋放。以前試過大半年沒重啟路由，依然用著同一個IP。
     希望大佬指點我應該如何才可以獲得釋放公網IP，獲取新的公網IP。

### (2) 路由器型号和固件版本

A：新路由3 D2

### (3) 详细日志

A：都是手動重啟﹑關閉WAN口，沒有相關日志。
WAN口 ipv4怎弄都是同一個IP。

udhcpc -i eth0.2
udhcpc: started, v1.30.0
udhcpc: sending discover
udhcpc: sending select for 219.73.109.XX
udhcpc: lease of 219.73.109.XX obtained, lease time 1800
udhcpc: ifconfig eth0.2 219.73.109.XX netmask 255.255.255.0 broadcast +
udhcpc: setting default routers: 219.73.109.254

**Comment by zerofo** [comment]
固定公网ip  好羡慕

**Comment by hxhwing0522** [comment]
> 固定公网ip 好羡慕

不固定公網更好，隨時換IP。

**Comment by zerofo** [comment]
> > 固定公网ip 好羡慕
> 
> 不固定公網更好，隨時換IP。

得閒無事，做乜要成日換

**Comment by hxhwing0522** [comment]
> > > 固定公网ip 好羡慕
> > 
> > 
> > 不固定公網更好，隨時換IP。
> 
> 得閒無事，做乜要成日換

比如建節點 : )

**Comment by zerofo** [comment]
> > > > 固定公网ip 好羡慕
> > > 
> > > 
> > > 不固定公網更好，隨時換IP。
> > 
> > 
> > 得閒無事，做乜要成日換
> 
> 比如建節點 : )

(>_<) MAC?

**Comment by hxlls** [comment]
自己改MAC 啊，这个的DHCP SERVER 根据MAC 来分配的，你MAC变化后，IP自然变化了，如果不改MAC dhcp server 的缓存生效期间，你是没法获取新的IP地址的

**Comment by hxhwing0522** [comment]
> 自己改MAC 啊，这个的DHCP SERVER 根据MAC 来分配的，你MAC变化后，IP自然变化了，如果不改MAC dhcp server 的缓存生效期间，你是没法获取新的IP地址的

接口 - WAN - 高級設置 - 重设 MAC 地址  這里嗎?
我改過來 好似不怎生效的樣子

**Comment by zerofo** [comment]
> > 自己改MAC 啊，这个的DHCP SERVER 根据MAC 来分配的，你MAC变化后，IP自然变化了，如果不改MAC dhcp server 的缓存生效期间，你是没法获取新的IP地址的
> 
> 接口 - WAN - 高級設置 - 重设 MAC 地址  這里嗎?
> 我改過來 MAC也是沒有變化

隨機一個MAC, 自己改/etc/config/network

**Comment by hxhwing0522** [comment]
> > > 自己改MAC 啊，这个的DHCP SERVER 根据MAC 来分配的，你MAC变化后，IP自然变化了，如果不改MAC dhcp server 的缓存生效期间，你是没法获取新的IP地址的
> > 
> > 
> > 接口 - WAN - 高級設置 - 重设 MAC 地址  這里嗎?
> > 我改過來 MAC也是沒有變化
> 
> 隨機一個MAC, 自己改/etc/config/network

嗯 
不過想看看大佬有沒有更簡單的方法 或將來可以一鍵釋放IP

**Comment by acooler15** [comment]
写个shell脚本？从网上扒个随机MAC生成，然后用uci 命令设置wan_dev的MAC地址并保存，再然后用ifup重启WAN口🤣
