### ISSUE TITLE
flowoffload 改名了？还是剔除了？

### ISSUE THREAD

**Issue by DanielChen008** [coolsnowwolf/lede#4907]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：今天更新源码后编译时发现 Luci 中已经没有 flowoffload 了。

### (2) 路由器型号和固件版本

A：x86 and R2S

### (3) 详细日志

A：

**Comment by WCJ23333** [comment]
同问，少了个flow offload 多了个sfe

**Comment by DanielChen008** [comment]
> 同问，少了个flow offload 多了个sfe

确实，SFE的说明就是 Turbo ACC.
关闭了
