### ISSUE TITLE
希望您能添加CUPS，以实现AirPrint

### ISSUE THREAD

**Issue by hyy-666** [coolsnowwolf/lede#4912]
目前了解到官方的软件源中有相关的ipk，但希望大雕能加到自己的源码中，因为大雕已经实现了AirPlay，加入CUPS可实现AirPrint，同时也能取代USB-Printer实现网络打印机共享

**Comment by hxlls** [comment]
Cups 直接软件包安装啊，不同打印机所用的包都不一样
