### ISSUE TITLE
下载库文件时错误

### ISSUE THREAD

**Issue by WCJ23333** [coolsnowwolf/lede#4925]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：下载库文件时错误,实际上GitHubusercontent的链接可以打开。
![image](https://user-images.githubusercontent.com/35393124/86422477-d8579900-bd0f-11ea-93de-08feebee60df.png)

### (2) 详细日志

A：
make[2]: Entering directory '/home/wcj/lede/feeds/packages/utils/pciutils'
mkdir -p /home/wcj/lede/dl
SHELL= flock /home/wcj/lede/tmp/.pci.ids.0.336.flock -c '       /home/wcj/lede/scripts/download.pl "/home/wcj/lede/dl" "pci.ids.0.336" "94053616c1f9b93540861931fb7891b1b30d6fd21b3e2c1647467527ea38f557" "pci.ids" "@GITHUB/vcrhonek/hwdata/v0.336"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://raw.githubusercontent.com/vcrhonek/hwdata/v0.336/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://raw.githubusercontent.com/vcrhonek/hwdata/v0.336/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://raw.githubusercontent.com/vcrhonek/hwdata/v0.336/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://raw.githubusercontent.com/vcrhonek/hwdata/v0.336/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://raw.githubusercontent.com/vcrhonek/hwdata/v0.336/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/pci.ids
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Makefile:56: recipe for target '/home/wcj/lede/dl/pci.ids.0.336' failed
make[2]: *** [/home/wcj/lede/dl/pci.ids.0.336] Error 2
make[2]: Leaving directory '/home/wcj/lede/feeds/packages/utils/pciutils'
time: package/feeds/packages/pciutils/download#0.19#0.07#4.13
package/Makefile:111: recipe for target 'package/feeds/packages/pciutils/download' failed
make[1]: *** [package/feeds/packages/pciutils/download] Error 2

**Comment by Erope** [comment]
检查curl有没有走代理
如果是路由器开全局试试
