### ISSUE TITLE
最新源码更新后Hello world和AMD Zen选项不见了

### ISSUE THREAD

**Issue by lqhorochi** [coolsnowwolf/lede#4929]
源码更新后Hello world和AMD Zen选项不见了
请问去了哪里呢??
如何可以再次出现???

**Comment by ruderal04o** [comment]
参考了一下重新配置，之前丢失的一些东西可以出来的rm -rf ./tmp && rm -rf .config
make menuconfig
make -j$(($(nproc) + 1)) V=s
