### ISSUE TITLE
更新后x86编译报错

### ISSUE THREAD

**Issue by Margular** [coolsnowwolf/lede#4941]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* 有类似的issue但是不是同一个问题

### (1) 具体问题

Configuring usign.
Configuring htop.
Configuring luci-theme-netgear.
Configuring kmod-i2c-algo-bit.
Configuring kmod-igbvf.
Configuring kmod-forcedeth.
Configuring luci-i18n-base-zh-cn.
Configuring ath10k-firmware-qca9984.
Configuring ath10k-firmware-qca988x.
Configuring fdisk.
Configuring luci-i18n-brook-server-zh-cn.
Configuring kmod-lib-crc7.
Configuring autosamba.
Configuring kmod-e1000e.
Configuring kmod-ath9k-htc.
Configuring luci-i18n-upnp-zh-cn.
Configuring kmod-lib-crc-itu-t.
Configuring kmod-mmc-spi.
Configuring fwtool.
Configuring jsonfilter.
Configuring kmod-igb.
Configuring kmod-ipt-offload.
Configuring kmod-bnx2.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for base-files:
 * 	libubox20170601
 * opkg_install_cmd: Cannot install package base-files.
 * check_data_file_clashes: Package libustream-openssl20200215 wants to install file /home/parallels/sources/lede/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
	But that file is already provided by package  * libustream-mbedtls20200215
 * opkg_install_cmd: Cannot install package libustream-openssl20200215.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for urngd:
 * 	libubox20170601
 * opkg_install_cmd: Cannot install package urngd.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/parallels/sources/lede'
package/Makefile:108: recipe for target '/home/parallels/sources/lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/parallels/sources/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/parallels/sources/lede'
/home/parallels/sources/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

### (2) 路由器型号和固件版本

x86_64 generic

**Comment by liwenjie119** [comment]
更新并make clean再编译试试，我更新到最新源码后makeclean后没问题了

**Comment by kl9800** [comment]
请问最终解决了吗？我也是这个问题

**Comment by asushugo** [comment]
实测make clean后再编译就通过了

**Comment by Margular** [comment]
最后我没编译这个了，可能是ssr和vssr冲突了
