### ISSUE TITLE
5.4挂载点有问题吗？

### ISSUE THREAD

**Issue by kkliu345** [coolsnowwolf/lede#4945]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题
无法挂载硬盘
A：
![微信截图_20200704073634](https://user-images.githubusercontent.com/56249450/86501180-1fee2b80-bdc9-11ea-956c-7bc174240b36.png)
![微信截图_20200704073514](https://user-images.githubusercontent.com/56249450/86501193-3d22fa00-bdc9-11ea-8780-2c4890d0895b.png)

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

**Comment by bin20088** [comment]
有问题，我也遇到了

**Comment by lloyd18** [comment]
我也是
