### ISSUE TITLE
缺少 fuse-utils 依赖导致 luci-app-rclone 编译出错

### ISSUE THREAD

**Issue by wangxin6** [coolsnowwolf/lede#4947]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

缺少 fuse-utils 依赖导致 luci-app-rclone 编译出错
在此之前已经执行
./scripts/feeds clean
./scripts/feeds update -a 
./scripts/feeds install -a

### (1) 具体问题

A：编译出错如附件日志

### (2) 路由器型号和固件版本

A：X86_64

### (3) 详细日志

A：
![Screen Shot](https://user-images.githubusercontent.com/24645789/86502638-eb35a080-bdd7-11ea-97b8-91e52f2e74e4.JPEG)

**Comment by fuokgfw** [comment]
不是写了吗，缺少依赖，都列出来了···,fuse-utils
