### ISSUE TITLE
编译qbittorrent时出错

### ISSUE THREAD

**Issue by wjlin2k** [coolsnowwolf/lede#4949]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译qbittorrent时用到rblibtorrent，这个编译出错

### (2) 路由器型号和固件版本

A：x86-64

### (3) 详细日志

A：

OpenWrt-libtool: compile:  x86_64-openwrt-linux-musl-g++ -DPACKAGE_NAME=\"libtorrent-rasterbar\" -DPACKAGE_TARNAME=\"libtorrent-rasterbar\" -DPACKAGE_VERSION=\"1.1.13\" "-DPACKAGE_STRING=\"libtorrent-rasterbar 1.1.13\"" -DPACKAGE_BUGREPORT=\"arvid@libtorrent.org\" -DPACKAGE_URL=\"http://www.libtorrent.org\" -DPACKAGE=\"libtorrent-rasterbar\" -DVERSION=\"1.1.13\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD=1 "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_SYSTEM=/**/" "-DHAVE_BOOST_CHRONO=/**/" "-DHAVE_BOOST_RANDOM=/**/" -DHAVE_CLOCK_GETTIME=1 -DNDEBUG=1 -DTORRENT_USE_OPENSSL=1 -DHAVE_ICONV=1 -DICONV_CONST= -DBOOST_ASIO_HASH_MAP_BUCKETS=1021 -DBOOST_EXCEPTION_DISABLE=1 -DBOOST_ASIO_ENABLE_CANCELIO=1 -DTORRENT_BUILDING_SHARED=1 -I. -DTORRENT_BUILDING_LIBRARY -I../include -I../ed25519/src -Os -I/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include -I/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include -I/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include -I/home/gly/Lean/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/gly/Lean/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/gly/Lean/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/gly/Lean/build_dir/target-x86_64_musl/rblibtorrent-1.1.13=rblibtorrent-1.1.13 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -std=gnu++14 -ftemplate-depth=120 -Wno-format-zero-length -fvisibility=hidden -fvisibility-inlines-hidden -MT http_connection.lo -MD -MP -MF .deps/http_connection.Tpo -c http_connection.cpp  -fPIC -DPIC -o .libs/http_connection.o
In file included from ../include/libtorrent/http_connection.hpp:41,
                 from http_connection.cpp:33:
/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include/boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
In file included from /home/gly/Lean/staging_dir/target-x86_64_musl/usr/include/boost/asio/write.hpp:1246,
                 from ../include/libtorrent/socket.hpp:57,
                 from ../include/libtorrent/http_connection.hpp:62,
                 from http_connection.cpp:33:
/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include/boost/asio/impl/write.hpp: In instantiation of 'class boost::asio::detail::initiate_async_write_buffer_sequence<libtorrent::socket_type>':
/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include/boost/asio/impl/write.hpp:534:15:   required from 'auto boost::asio::async_write(AsyncWriteStream&, const ConstBufferSequence&, WriteHandler&&, typename std::enable_if<boost::asio::is_const_buffer_sequence<ConstBufferSequence>::value>::type*) [with AsyncWriteStream = libtorrent::socket_type; ConstBufferSequence = boost::asio::mutable_buffers_1; WriteHandler = boost::_bi::bind_t<void, boost::_mfi::mf1<void, libtorrent::http_connection, const boost::system::error_code&>, boost::_bi::list2<boost::_bi::value<boost::shared_ptr<libtorrent::http_connection> >, boost::arg<1> > >; typename std::enable_if<boost::asio::is_const_buffer_sequence<ConstBufferSequence>::value>::type = void]'
http_connection.cpp:278:53:   required from here
/home/gly/Lean/staging_dir/target-x86_64_musl/usr/include/boost/asio/impl/write.hpp:425:54: error: no type named 'executor_type' in 'struct libtorrent::socket_type'
     typedef typename AsyncWriteStream::executor_type executor_type;
                                                      ^~~~~~~~~~~~~
Makefile:937: recipe for target 'http_connection.lo' failed
make[5]: *** [http_connection.lo] Error 1
make[5]: Leaving directory '/home/gly/Lean/build_dir/target-x86_64_musl/rblibtorrent-1.1.13/src'
Makefile:623: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/gly/Lean/build_dir/target-x86_64_musl/rblibtorrent-1.1.13'
Makefile:74: recipe for target '/home/gly/Lean/build_dir/target-x86_64_musl/rblibtorrent-1.1.13/.built' failed
make[3]: *** [/home/gly/Lean/build_dir/target-x86_64_musl/rblibtorrent-1.1.13/.built] Error 2
make[3]: Leaving directory '/home/gly/Lean/package/lean/rblibtorrent'
time: package/lean/rblibtorrent/compile#3.34#0.60#5.67
package/Makefile:111: recipe for target 'package/lean/rblibtorrent/compile' failed
make[2]: *** [package/lean/rblibtorrent/compile] Error 2
make[2]: Leaving directory '/home/gly/Lean'
package/Makefile:107: recipe for target '/home/gly/Lean/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/gly/Lean/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gly/Lean'
/home/gly/Lean/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by asushugo** [comment]
更新到最新代码应该就行了，如果不行试试make clean
