### ISSUE TITLE
更新后的两个问题

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#4953]
1.ntfs格式的移动硬盘不能自动挂载了
2.软件包列表已超过 24 小时未更新的提示永远不消失
![Snipaste_2020-07-04_15-46-33](https://user-images.githubusercontent.com/10294460/86507802-c9571080-be0d-11ea-9126-aff1c07b77ab.png)

之前有过的问题，又出现了。https://github.com/coolsnowwolf/lede/issues/2918#issue-558634654

**Comment by shenyz** [comment]
麻烦看下--防火墙--流量规则 里面正常么，谢谢

![image](https://user-images.githubusercontent.com/2944410/86509077-ded13800-be17-11ea-9c51-d20fc94faabe.png)

**Comment by sonic3366** [comment]
楼主，请问这个问题解决了吗，我也遇到了同样的问题
