### ISSUE TITLE
更新后执行 diffconfig.sh 提示出错

### ISSUE THREAD

**Issue by kiss2u** [coolsnowwolf/lede#4954]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：执行 ./scripts/diffconfig.sh > seeds.config 代码时提示出错，无法生成差异化 seeds.config 文件。

### (2) 路由器型号和固件版本

A：通用版本

### (3) 详细日志

`./scripts/diffconfig.sh: 11: ./scripts/diffconfig.sh: ./scripts/config/conf: not found
can't open file 'tmp/.diffconfig.stage1' at ./scripts/kconfig.pl line 32.
./scripts/diffconfig.sh: 13: ./scripts/diffconfig.sh: ./scripts/config/conf: not found
can't open file 'tmp/.diffconfig.stage2' at ./scripts/kconfig.pl line 32.`

**Comment by fanck0605** [comment]
你更新一下源码，现在好像没报错了，刚试了没问题。
