### ISSUE TITLE
在更新到5.4内核并全新配置之后，在保留配置上传新编译的固件时会发生未选择编译的主题选项还在的情况。

### ISSUE THREAD

**Issue by Fddh2012** [coolsnowwolf/lede#4959]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在更新到5.4内核并全新配置之后，在保留配置上传新编译的固件时会发生未选择编译的主题选项还在的情况。
      注：主题选项虽然还在并能被应用，但主题其实并没有应用成功，但选项会切换过去。

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：没，就这么直接。

**Comment by acooler15** [comment]
最好不保留配置更新一次。

**Comment by Fddh2012** [comment]
> 最好不保留配置更新一次。

有，第一次是不保留全新配置过的，后面再更新编译的时候把另外的主题给取消编译了，再保留更新就出现这情况了。

**Comment by acooler15** [comment]
测试了一下，之前4.14的版本也有这样的情况 ，原因在于主题信息保存在/etc/config/luci 文件中，当保留配置时，luci文件也会保留

**Comment by Fddh2012** [comment]
> 测试了一下，之前4.14的版本也有这样的情况 ，原因在于主题信息保存在/etc/config/luci 文件中，当保留配置时，luci文件也会保留

的确是这样，也就是“无法自动更新主题列表” 目前只能手动修改luci来达到自己想要的效果。毕竟全新配置起来太麻烦了。

**Comment by xiaoqingfengATGH** [comment]
这不是一个缺陷。你重用了配置（/etc/config/luci ）才会这样。
