### ISSUE TITLE
5.4内核，防火墙LuciApp显示内容不正确

### ISSUE THREAD

**Issue by xiaoqingfengATGH** [coolsnowwolf/lede#4970]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：防火墙Luci界面，所有规则“源于”和“位于”字段均显示uci: Entry not found。
![firewall](https://user-images.githubusercontent.com/31612198/86525126-a97b2780-beb5-11ea-99e1-bc714327a0a3.png)

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：无需日志

**Comment by coolsnowwolf** [comment]
已修复
