### ISSUE TITLE
menuconfig选中了transmission，编译出来界面没有

### ISSUE THREAD

**Issue by tjlive** [coolsnowwolf/lede#4972]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
好几位网友都遇到相关的问题。

### (1) 具体问题

A：最新源码，menuconfig选中了transmission，编译出来界面没有 

### (2) 路由器型号和固件版本

A：Newifi-D2

### (3) 详细日志

A：

**Comment by nb12nb34** [comment]
同样问题。。x86-64 一样没有菜单。。有遇到同样问题的吗

**Comment by Ed-11** [comment]
+1

**Comment by EnnawYang** [comment]
![Snipaste_2020-07-05_13-16-42](https://user-images.githubusercontent.com/6705663/86526072-c7e72000-bec1-11ea-94d7-85c92ff05d16.png)

**Comment by tjlive** [comment]
TO EnnawYang
你这个应不是这两天获取的最新源码编译的吧。

**Comment by shu0802** [comment]
是不是编译固件的时候固件大小不够大的原因

**Comment by nb12nb34** [comment]
应该不是吧，已经设置了内核16m，分区300m,所以说应该不是固件大小的问题。。

**Comment by coolsnowwolf** [comment]
需要手动选软件包了，官方 pacakge 就这样

**Comment by tjlive** [comment]
coolsnowwolf 大，请问手工选软件包是什么意思？怎样操作？
从固件上看，它已编译到固件中了，但我怎样拿出来使用？

**Comment by shu0802** [comment]
> 应该不是吧，已经设置了内核16m，分区300m,所以说应该不是固件大小的问题。。
是不是内核小了呢

**Comment by tjlive** [comment]
原来需要在network --> bit ttorrent里面，选择daemon和Web control即可。
多谢L大和各位网友的指点。
