### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by kk3375** [coolsnowwolf/lede#4973]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：NEWIFI D2

### (3) 详细日志
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/libiberty/testsuite'
make[6]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libiberty/testsuite'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libiberty/testsuite'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/libiberty'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libiberty'
make[2]: Leaving directory '/home/my/lede'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make  all-am
make[6]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libdecnumber'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libdecnumber'
true  DO=all multi-do # make
make[6]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/fixincludes'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/libcpp'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/build-x86_64-pc-linux-gnu/fixincludes'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/fixincludes'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/fixincludes'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/libcpp'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/lto-plugin'
make  all-am
make[6]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/lto-plugin'
make[6]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/lto-plugin'
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/lto-plugin'
make[5]: Entering directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/gcc'
g++ -no-pie   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc  -o cc1 c/c-lang.o c-family/stub-objc.o attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o c/c-convert.o c/c-aux-info.o c/c-objc-common.o c/c-parser.o c/c-fold.o c/gimple-parser.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o glibc-c.o \
  cc1-checksum.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a   -L/home/my/lede/staging_dir/host/lib -L/home/my/lede/staging_dir/host/lib -L/home/my/lede/staging_dir/host/lib -lmpc -lmpfr -lgmp -rdynamic -ldl  -L./../zlib -lz
g++ -no-pie   -g -O2 -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc  -o lto1 \
	lto/lto-lang.o lto/lto.o lto/lto-object.o attribs.o lto/lto-partition.o lto/lto-symtab.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a  -L/home/my/lede/staging_dir/host/lib -L/home/my/lede/staging_dir/host/lib -L/home/my/lede/staging_dir/host/lib -lmpc -lmpfr -lgmp -rdynamic -ldl  -L./../zlib -lz libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a 
gimple-fold.o: In function `gimple_fold_stmt_to_constant_1(gimple*, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:6107: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:6112: undefined reference to `mprts_hook'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7133: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7159: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7180: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7206: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7232: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7260: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `fold_stmt_1(gimple_stmt_iterator*, bool, tree_node* (*)(tree_node*))':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4756: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
gimple-fold.o: In function `replace_stmt_with_simplification':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4487: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4420: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4446: undefined reference to `maybe_build_generic_op(tree_code, tree_node*, tree_node**)'
tree-ssa-sccvn.o: In function `vn_nary_build_or_lookup_1(code_helper, tree_node*, tree_node**, bool)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1692: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1706: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1718: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1697: undefined reference to `gimple_resimplify1(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1706: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1703: undefined reference to `gimple_resimplify3(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1700: undefined reference to `gimple_resimplify2(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
tree-ssa-sccvn.o: In function `try_to_simplify':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:3995: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:3997: undefined reference to `mprts_hook'
tree-ssa-sccvn.o: In function `sccvn_dom_walker::before_dom_children(basic_block_def*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:4970: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
tree-cfgcleanup.o: In function `cleanup_control_expr_graph':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-cfgcleanup.c:153: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
collect2: error: ld returned 1 exit status
gimple-fold.o: In function `gimple_fold_stmt_to_constant_1(gimple*, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:6107: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:6112: undefined reference to `mprts_hook'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7133: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7159: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7180: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/lto/Make-lang.in:81: recipe for target 'lto1' failed
)(tree_node*))'
gimple-fold.o:make[5]: *** [lto1] Error 1
 In function `gimple_build(gimple**, unsigned int, built_in_function, make[5]: *** Waiting for unfinished jobs....
tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7206: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7232: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*, tree_node*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:7260: undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
gimple-fold.o: In function `fold_stmt_1(gimple_stmt_iterator*, bool, tree_node* (*)(tree_node*))':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4756: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
gimple-fold.o: In function `replace_stmt_with_simplification':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4487: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4420: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/gimple-fold.c:4446: undefined reference to `maybe_build_generic_op(tree_code, tree_node*, tree_node**)'
tree-ssa-sccvn.o: In function `vn_nary_build_or_lookup_1(code_helper, tree_node*, tree_node**, bool)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1692: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1706: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1718: undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1697: undefined reference to `gimple_resimplify1(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1706: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1703: undefined reference to `gimple_resimplify3(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:1700: undefined reference to `gimple_resimplify2(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
tree-ssa-sccvn.o: In function `try_to_simplify':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:3995: undefined reference to `mprts_hook'
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:3997: undefined reference to `mprts_hook'
tree-ssa-sccvn.o: In function `sccvn_dom_walker::before_dom_children(basic_block_def*)':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-ssa-sccvn.c:4970: undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
tree-cfgcleanup.o: In function `cleanup_control_expr_graph':
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/tree-cfgcleanup.c:153: undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
collect2: error: ld returned 1 exit status
/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/c/Make-lang.in:85: recipe for target 'cc1' failed
make[5]: *** [cc1] Error 1
make[5]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/gcc'
Makefile:4251: recipe for target 'all-gcc' failed
make[4]: *** [all-gcc] Error 2
make[4]: Leaving directory '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial'
Makefile:36: recipe for target '/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/.built' failed
make[3]: *** [/home/my/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/.built] Error 2
make[3]: Leaving directory '/home/my/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#11.16#6.78#10.79
toolchain/Makefile:98: recipe for target 'toolchain/gcc/initial/compile' failed
make[2]: *** [toolchain/gcc/initial/compile] Error 2
make[2]: Leaving directory '/home/my/lede'
toolchain/Makefile:96: recipe for target '/home/my/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/stamp/.toolchain_compile' failed
make[1]: *** [/home/my/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/my/lede'
Build failed - please re-run with -j1 to see the real error message
/home/my/lede/include/toplevel.mk:222: recipe for target 'world' failed

**Comment by kk3375** [comment]
这个是什么报错啊，大佬给解答下，编译不了

**Comment by rohanjuneja** [comment]
May I know if this issue is resolved? And what was the error here?
