### ISSUE TITLE
make menuconfig  IPQ806x没有了ruijie-mtfi-M520的机型配置

### ISSUE THREAD

**Issue by ruihua2018** [coolsnowwolf/lede#4984]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by ruihua2018** [comment]
更新以后make menuconfig  IPQ806x里没有了ruijie-mtfi-M520的机型配置

**Comment by AmadeusGhost** [comment]
不启动，支持了也没用
