### ISSUE TITLE
大量miniupnpd 报错日志

### ISSUE THREAD

**Issue by xiaoguoyi** [coolsnowwolf/lede#4989]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如题

### (2) 路由器型号和固件版本

A：NEWIFI3

### (3) 详细日志

A：Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=488, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=484, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=470, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=456, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=476, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=480, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=408, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:14 2020 daemon.err miniupnpd[8306]: try_sendto failed to send 52 packets
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=7, 192.168.1.1): No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: sendto(udp_notify=8, [fda9:9af8:490d::1]): Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff0e::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff05::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=490, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=486, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=474, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=472, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 kern.err /usr/bin/ssr-redir[11334]: server recv: Connection reset by peer
Mon Jul  6 00:02:44 2020 kern.err /usr/bin/ssr-redir[11329]: server recv: Connection reset by peer
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=458, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=478, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=419, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=482, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=8, len=410, dest=[ff02::c]:1900): sendto: Permission denied
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=488, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=484, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=472, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=470, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=456, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=476, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=417, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=480, dest=239.255.255.250:1900): sendto: No such device
Mon Jul  6 00:02:44 2020 daemon.err miniupnpd[8306]: try_sendto(sock=7, len=408, dest=239.255.255.250:1900): sendto: No such device

**Comment by coolsnowwolf** [comment]
习惯就好，这就是你们都喜欢的ipv6
