### ISSUE TITLE
最新版本编译的固件不可用

### ISSUE THREAD

**Issue by hehhuig** [coolsnowwolf/lede#4993]
反馈bug/问题模板，提建议请删除

## 1.编译成功，但固件不兼容我原来的路由器，反复编译多次仍是如此。

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：固件不兼容

### (2) 路由器型号和固件版本

A：linksys 3200acm rango

### (3) 详细日志

A：

**Comment by piaoyizy** [comment]
Configuring kmod-usb-net.
Configuring kmod-usb-net-asix-ax88179.
Configuring libuclient20160123.
Configuring uclient-fetch.
Configuring opkg.
Configuring kmod-pps.
Configuring kmod-ptp.
Configuring kmod-mlx4-core.
Configuring adbyby.
Configuring kmod-ipt-ipset.
Configuring libmnl0.
Configuring libipset13.
Configuring ipset.
Configuring dnsmasq-full.
Configuring luci-app-adbyby-plus.
Configuring libpcre.
Configuring kmod-crypto-authenc.
Configuring kmod-cryptodev.
Configuring libopenssl1.1.
Configuring wget.
Configuring kmod-bonding.
Configuring kmod-usb-storage-uas.
Configuring ubusd.
Configuring ubus.
Configuring iw.
Configuring wireless-regdb.
Configuring kmod-cfg80211.
Configuring hostapd-common.
Configuring kmod-mac80211.
Configuring kmod-ath.
Configuring kmod-ath10k.
Configuring ddns-scripts.
Configuring ca-certificates.
Configuring ddns-scripts_dnspod.
Configuring kmod-mdio.
Configuring kmod-hwmon-core.
Configuring kmod-ixgbe.
Configuring rpcd.
Configuring busybox.
Configuring kmod-lib-zlib-deflate.
Configuring coremark.
Configuring libustream-openssl20200215.
Configuring luci-lib-ip.
Configuring libubus-lua.
Configuring kmod-nf-conntrack6.
Configuring kmod-nf-reject6.
Configuring kmod-nf-ipt6.
Configuring kmod-ip6tables.
Configuring kmod-ipt-tproxy.
Configuring amdgpu-firmware.
Configuring kmod-nf-nat.
Configuring kmod-ipt-fullconenat.
Configuring kmod-tun.
Configuring libiwinfo-lua.
Configuring v2ray.
Configuring kmod-r8125.
Configuring kmod-lib-zlib-inflate.
Configuring kmod-crypto-acompress.
Configuring kmod-crypto-deflate.
Configuring kmod-crypto-cbc.
Configuring kmod-crypto-des.
Configuring kmod-crypto-echainiv.
Configuring kmod-crypto-hmac.
Configuring kmod-crypto-md5.
Configuring kmod-crypto-sha1.
Configuring kmod-ipsec.
Configuring kmod-iptunnel4.
Configuring kmod-ipsec4.
Configuring kmod-iptunnel6.
Configuring kmod-ipsec6.
Configuring kmod-ipt-ipsec.
Configuring libxtables12.
Configuring libip4tc2.
Configuring libip6tc2.
Configuring iptables.
Configuring iptables-mod-ipsec.
Configuring strongswan.
Configuring strongswan-mod-sha1.
Configuring kmod-rt2x00-lib.
Configuring kmod-rt2x00-usb.
Configuring kmod-lib-crc-ccitt.
Configuring kmod-rt2800-lib.
Configuring rt2800-usb-firmware.
Configuring kmod-rt2800-usb.
Configuring bnx2-firmware.
Configuring luci-app-samba.
Configuring uhttpd-mod-ubus.
Configuring lua.
Configuring luci-lib-nixio.
Configuring luci-lib-jsonc.
Configuring luci-base.
Configuring luci-mod-admin-full.
Configuring luci-theme-bootstrap.
Configuring kmod-ipt-nat.
Configuring iptables-mod-fullconenat.
Configuring firewall.
Configuring luci-app-firewall.
Configuring luci-proto-ppp.
Configuring rpcd-mod-rrdns.
Configuring luci.
Configuring luci-app-autoreboot.
Configuring libopenssl-conf.
Configuring openssl-util.
Configuring kmod-nf-flow.
Configuring luci-lib-fs.
Configuring luci-app-filetransfer.
Configuring luci-i18n-filetransfer-zh-cn.
Configuring getrandom.
Configuring kmod-shortcut-fe.
Configuring kmod-fast-classifier.
Configuring pdnsd-alt.
Configuring kmod-tcp-bbr.
Configuring luci-app-sfe.
Configuring kmod-asn1-decoder.
Configuring ddns-scripts_aliyun.
Configuring brcmfmac-firmware-43602a1-pcie.
Configuring libev.
Configuring libstdcpp6.
Configuring libnghttp2-14.
Configuring libuv1.
Configuring libhttp-parser.
Configuring libcares.
Configuring libatomic1.
Configuring node.
Configuring UnblockNeteaseMusic.
Configuring UnblockNeteaseMusicGo.
Configuring luci-app-unblockmusic.
Configuring kmod-nf-nathelper.
Configuring kmod-slhc.
Configuring kmod-ppp.
Configuring kmod-pppox.
Configuring kmod-pppoe.
Configuring kmod-fb.
Configuring kmod-fb-sys-fops.
Configuring kmod-fb-cfb-copyarea.
Configuring kmod-fb-cfb-fillrect.
Configuring kmod-fb-cfb-imgblt.
Configuring kmod-fb-sys-ram.
Configuring kmod-drm-kms-helper.
Configuring ipt2socks.
Configuring kmod-backlight.
Configuring kmod-drm-ttm.
Configuring kmod-i2c-algo-bit.
Configuring kmod-drm-amdgpu.
Configuring libsysfs2.
Configuring sysfsutils.
Configuring libcap-ng.
Configuring kmod-mlx5-core.
Configuring kmod-lib-crc16.
Configuring kmod-input-core.
Configuring kmod-crypto-crc32c.
Configuring coreutils.
Configuring coreutils-base64.
Configuring libblkid1.
Configuring libsmartcols1.
Configuring partx-utils.
Configuring jshn.
Configuring netifd.
Configuring kmod-ipt-raw.
Configuring kmod-r8168.
Configuring shadowsocks-libev-config.
Configuring boost.
Configuring boost-system.
Configuring boost-program_options.
Configuring boost-date_time.
Configuring trojan.
Configuring vlmcsd.
Configuring luci-app-vlmcsd.
Configuring libminiupnpc.
Configuring libnatpmp1.
Configuring zerotier.
Configuring ubox.
Configuring procd.
Configuring resolveip.
Configuring luci-app-zerotier.
Configuring proto-bonding.
Configuring luci-proto-bonding.
Configuring libncurses6.
Configuring libreadline8.
Configuring bc.
Configuring libsensors5.
Configuring lm-sensors.
Configuring ethtool.
Configuring autocore.
Configuring libevent2-7.
Configuring redsocks2.
Configuring kmod-ath5k.
Configuring luci-i18n-autoreboot-zh-cn.
Configuring dns2socks.
Configuring kmod-8139cp.
Configuring etherwake.
Configuring kmod-input-evdev.
Configuring kmod-hid.
Configuring kmod-hid-generic.
Configuring kmod-usb-hid.
Configuring strongswan-mod-aes.
Configuring vsftpd-alt.
Configuring luci-app-vsftpd.
Configuring luci-i18n-vsftpd-zh-cn.
Configuring luci-i18n-unblockmusic-zh-cn.
Configuring libmbedtls12.
Configuring block-mount.
Configuring kmod-usb-storage-extras.
Configuring kmod-nls-cp437.
Configuring kmod-nls-iso8859-1.
Configuring kmod-nls-utf8.
Configuring kmod-fs-vfat.
Configuring kmod-fs-ext4.
Configuring kmod-fs-exfat.
Configuring kmod-fuse.
Configuring ntfs-3g.
Configuring automount.
Configuring strongswan-mod-xcbc.
Configuring luci-app-ddns.
Configuring strongswan-mod-random.
Configuring ip6tables.
Configuring miniupnpd.
Configuring grub2-efi.
Configuring libsodium.
Configuring v2ray-plugin.
Configuring shadowsocksr-libev-alt.
Configuring iptables-mod-tproxy.
Configuring microsocks.
Configuring shadowsocks-libev-ss-local.
Configuring shadowsocksr-libev-ssr-local.
Configuring shadowsocks-libev-ss-redir.
Configuring simple-obfs.
Configuring libpcap1.
Configuring libnet-1.2.x.
Configuring tcpping.
Configuring shadowsocksr-libev-server.
Configuring luci-app-ssr-plus.
Configuring kmod-mmc.
Configuring fstools.
Configuring luci-i18n-sfe-zh-cn.
Configuring kmod-ath9k-common.
Configuring kmod-ath9k.
Configuring uci.
Configuring grub2.
Configuring strongswan-mod-hmac.
Configuring dropbear.
Configuring kmod-usb-net-asix.
Configuring luci-i18n-samba-zh-cn.
Configuring libgmp10.
Configuring luci-compat.
Configuring strongswan-charon.
Configuring mtd.
Configuring wpad.
Configuring luci-i18n-vlmcsd-zh-cn.
Configuring luci-i18n-zerotier-zh-cn.
Configuring luci-i18n-arpbind-zh-cn.
Configuring strongswan-mod-gmp.
Configuring strongswan-mod-kernel-netlink.
Configuring strongswan-mod-nonce.
Configuring strongswan-mod-pubkey.
Configuring strongswan-mod-socket-default.
Configuring strongswan-ipsec.
Configuring strongswan-mod-stroke.
Configuring strongswan-mod-updown.
Configuring strongswan-mod-x509.
Configuring strongswan-minimal.
Configuring strongswan-mod-xauth-generic.
Configuring luci-app-ipsec-vpnd.
Configuring kmod-sdhci.
Configuring wsdd2.
Configuring urandom-seed.
Configuring libcomerr0.
Configuring ppp.
Configuring luci-i18n-ssr-plus-zh-cn.
Configuring logd.
Configuring luci-app-accesscontrol.
Configuring luci-i18n-accesscontrol-zh-cn.
Configuring kmod-vmxnet3.
Configuring kmod-8139too.
Configuring luci-i18n-ipsec-vpnd-zh-cn.
Configuring openwrt-keyring.
Configuring kmod-pcnet32.
Configuring ath9k-htc-firmware.
Configuring luci-i18n-ddns-zh-cn.
Configuring libss2.
Configuring libext2fs2.
Configuring kmod-i40e.
Configuring kmod-nf-nathelper-extra.
Configuring libfdisk1.
Configuring luci-app-xlnetacc.
Configuring e2fsprogs.
Configuring kmod-e1000.
Configuring luci-i18n-adbyby-plus-zh-cn.
Configuring kmod-crypto-crc32.
Configuring kmod-fs-f2fs.
Configuring luci-app-ramfree.
Configuring luci-i18n-ramfree-zh-cn.
Configuring wol.
Configuring luci-app-wol.
Configuring kmod-usb-net-rtl8150.
Configuring kmod-usb-net-rtl8152.
Configuring kmod-tulip.
Configuring luci-i18n-wol-zh-cn.
Configuring luci-app-upnp.
Configuring ath10k-firmware-qca9888.
Configuring usign.
Configuring htop.
Configuring kmod-igbvf.
Configuring kmod-forcedeth.
Configuring luci-i18n-base-zh-cn.
Configuring ath10k-firmware-qca9984.
Configuring ath10k-firmware-qca988x.
Configuring fdisk.
Configuring kmod-lib-crc7.
Configuring autosamba.
Configuring kmod-e1000e.
Configuring kmod-ath9k-htc.
Configuring luci-i18n-upnp-zh-cn.
Configuring kmod-lib-crc-itu-t.
Configuring kmod-mmc-spi.
Configuring fwtool.
Configuring jsonfilter.
Configuring kmod-igb.
Configuring kmod-ipt-offload.
Configuring kmod-bnx2.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for base-files:
 *      libuci20130104
 * opkg_install_cmd: Cannot install package base-files.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for libiwinfo20200105:
 *      libuci20130104
 * opkg_install_cmd: Cannot install package libiwinfo20200105.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for block-mount:
 *      libuci20130104
 * opkg_install_cmd: Cannot install package block-mount.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for default-settings:
 *      libuci20130104
 * opkg_install_cmd: Cannot install package default-settings.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-vsftpd:
 *      libuci20130104
 * opkg_install_cmd: Cannot install package luci-app-vsftpd.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/root/lede'
make[1]: *** [package/Makefile:108: /root/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/root/lede'
make: *** [/root/lede/include/toplevel.mk:224: world] Error 2

**Comment by OleStore** [comment]
make clean再来一次
