### ISSUE TITLE
奇怪的问题，卡在openwrt / openwrt(failsafe)选项

### ISSUE THREAD

**Issue by OleStore** [coolsnowwolf/lede#4995]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ×] 没有类似的issue

## 2. 详细叙述
通过DD 刷机，无法启动，卡在选项界面

### (2) 路由器型号和固件版本
X86_64
![op](https://user-images.githubusercontent.com/1283711/86546895-72664e00-bf69-11ea-94cf-0f514982b7c8.jpg)

图片是虚拟机的，x86_64物理机 不会自动启动，需要通过键盘确认启动。

**Comment by weiyutf** [comment]
我也有同样的问题

**Comment by OleStore** [comment]
重新拉码更新，大雕更新了，我刚刚编译中
https://github.com/coolsnowwolf/lede/commit/88aed2924e52bda8a2aa29c675edb8a21da41441

**Comment by OleStore** [comment]
刚刷完机 ，老问题
