### ISSUE TITLE
竟斗云又开始刷内核日志了

### ISSUE THREAD

**Issue by stock169** [coolsnowwolf/lede#4998]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
[   49.070170] br-lan: port 3(wlan1) entered forwarding state
[ 1351.261523] ess_edma c080000.edma: IPv6 not supported
[ 1484.175807] ess_edma c080000.edma: IPv6 not supported
[ 1617.280706] ess_edma c080000.edma: IPv6 not supported
[ 1750.410366] ess_edma c080000.edma: IPv6 not supported
[ 1750.623437] ess_edma c080000.edma: IPv6 not supported
[ 1884.067729] ess_edma c080000.edma: IPv6 not supported
[ 2016.733350] ess_edma c080000.edma: IPv6 not supported
[ 5370.687616] ess_edma c080000.edma: IPv6 not supported
[ 5391.850851] ess_edma c080000.edma: IPv6 not supported
[ 5408.234314] ess_edma c080000.edma: IPv6 not supported
[ 5425.983202] ess_edma c080000.edma: IPv6 not supported
[ 5456.043452] ess_edma c080000.edma: IPv6 not supported
[ 5486.738859] ess_edma c080000.edma: IPv6 not supported
[ 5525.653590] ess_edma c080000.edma: IPv6 not supported
[ 5657.827738] ess_edma c080000.edma: IPv6 not supported
[ 5672.127511] ess_edma c080000.edma: IPv6 not supported
[ 5676.943070] ess_edma c080000.edma: IPv6 not supported
[ 5680.391524] ess_edma c080000.edma: IPv6 not supported
[ 6280.656080] ess_edma c080000.edma: IPv6 not supported
[ 6292.311775] ess_edma c080000.edma: IPv6 not supported
[ 6350.842938] ess_edma c080000.edma: IPv6 not supported
[ 6393.850704] ess_edma c080000.edma: IPv6 not supported
[ 6408.160706] ess_edma c080000.edma: IPv6 not supported
[ 6476.433916] ess_edma c080000.edma: IPv6 not supported

几分钟刷满
这个BUG似乎一直存在，有没有可能彻底搞定他，不是只屏蔽错误提示

**Comment by coolsnowwolf** [comment]
这个不是bug，是上游内核集成的功能
