### ISSUE TITLE
你好，编译出错，请问错在哪里？

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#5]
你好，编译出错，请问错在哪里？

![default](https://user-images.githubusercontent.com/21034764/30146335-f989b5e4-93c9-11e7-9bf9-deddb5b6e2f1.JPG)

**Comment by ctw8989** [comment]
出錯用后  make -j1 V=s  可以看得清楚点

**Comment by d975xbx** [comment]
我是GFW模式，试试全局，一会来反馈

**Comment by SouHong** [comment]
检查下ipset-lists选项看看

**Comment by coolsnowwolf** [comment]
ipset-lists 要选上，否则依赖解决不了

**Comment by d975xbx** [comment]
OK。谢谢大神

**Comment by d975xbx** [comment]
编译成功，但是Hyper-V好像不认网卡，启动失败。是不支持吗？

**Comment by MeISbug** [comment]
遇到一样的问题，选上ipset-lists 后编译成功，但是启动失败，网卡获取不了地址。我刷的是arm路由器，非虚拟机

**Comment by coolsnowwolf** [comment]
选择第一代 Hyper-V 虚拟机即可， kmod-tulip 也最好选上

**Comment by MeISbug** [comment]
忘了说出问题的是mvebu，刚看到commit revert mvebu to k4.4，我明天再试试
