### ISSUE TITLE
编译v2ray

### ISSUE THREAD

**Issue by taiziccf** [coolsnowwolf/lede#500]
编译成功后，显示v2ray没有运行（红色字体）。

已经加入luo-jsonc和luci-app-transfer

配置是对的，使用他人编译的固件能正常启动。请问我是还少了什么吗？

**Comment by shijiancat** [comment]
在启动项里禁止酸酸乳pro启动试试？

**Comment by dehim** [comment]
ssh进路由，运行：
/usr/bin/v2ray/v2ray -help
先确认是否能正常返回

**Comment by anglabace** [comment]
luo-jsonc  在哪里选择加入的。

**Comment by shijiancat** [comment]
主界面 language 目录下lua子选项进去   lua-c
json  选中 即可
