### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#5004]
刷了5.4内核后,再次更新时出413提示,如何修改上传文件大小限制?

**Comment by qq635938204** [comment]
cd /etc/nging
vim uci.conf.template
![image](https://user-images.githubusercontent.com/8327799/163347558-439804f1-95b8-4a25-bf8e-aed8f711dab7.png)
![image](https://user-images.githubusercontent.com/8327799/163347616-3921cbf6-a0a4-4921-ad85-5b28e62a46ea.png)
client_max_body_size 512M
