### ISSUE TITLE
MT76系列编译docker

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#5005]
newifi2，红米ac2100这些ramips系列不支持编译docker？

**Comment by EnnawYang** [comment]
硬路由你还想塞个docker进去？

**Comment by lloyd18** [comment]
你试试不就好了

**Comment by lexin8** [comment]
> 你试试不就好了

编译直接被隐藏不显示选项。

**Comment by lexin8** [comment]
> 硬路由你还想塞个docker进去？

newifi2有USB，不知道是硬件不支持还是存储问题被屏蔽掉？

**Comment by AmadeusGhost** [comment]
性能太差了，不支持

**Comment by dl250** [comment]
OpenWrt新三的usb想挂个硬盘完全挂载不了，用老毛子就正常

**Comment by martin0607** [comment]
MT76太差劲了

**Comment by coolsnowwolf** [comment]
想多了，没有 mips 的docker
