### ISSUE TITLE
固件选用GZ的格式输出，压缩包里显示的文件大小和解压出来的不一致

### ISSUE THREAD

**Issue by gsblay** [coolsnowwolf/lede#5017]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：用最新的源码编译，固件选用GZ的格式输出，Windows平台下压缩包里现实的文件大小和解压出来的不一致，但刷入路由，也没出现问题。
以前的版本没有这个问题。

### (2) 路由器型号和固件版本

A：x86-64

### (3) 详细日志

A：

**Comment by gsblay** [comment]
![image](https://user-images.githubusercontent.com/57081416/86695803-749adc00-c03f-11ea-8cd1-128a0dd147bb.png)

**Comment by gsblay** [comment]
我用的是TotalCommander

**Comment by hyy-666** [comment]
近几版貌似都有问题，Ubuntu无法直接用压缩包管理器直接解压，必须右键，应该是又是官方新功能=.=
