### ISSUE TITLE
更新了最新源代码k3屏幕怎么也不能添加进去

### ISSUE THREAD

**Issue by zjh1982** [coolsnowwolf/lede#5029]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Aes64X** [comment]
自己动手（有源码）或  亮出你的捐赠金额截图
