### ISSUE TITLE
稳定版的SQM中文界面出错

### ISSUE THREAD

**Issue by brianzc** [coolsnowwolf/lede#5030]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：稳定版的SQM中文界面出错

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：Collected errors:
 * check_data_file_clashes: Package luci-i18n-sqm-zh-cn wants to install file /home/zc/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/lua/luci/i18n/sqm.zh-cn.lmo
	But that file is already provided by package  * default-settings
 * opkg_install_cmd: Cannot install package luci-i18n-sqm-zh-cn.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/zc/openwrt'
package/Makefile:108: recipe for target '/home/zc/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/zc/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/zc/openwrt'
Build failed - please re-run with -j1 to see the real error message
/home/zc/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by xiaoqingfengATGH** [comment]
应该已经修正了。
更新到最新代码，make clean 后再编译。
