### ISSUE TITLE
升级到5.4.50内核后，netflix分流功能失效。

### ISSUE THREAD

**Issue by cnhz76** [coolsnowwolf/lede#5032]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：在pac和gfw模式下，netflix分流功能均失效。

### (2) 路由器型号和固件版本

A：
主机型号	Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread (CpuMark : 27463.567861 Scores)
CPU 信息	1800.000 MHz
固件版本	OpenWrt R20.7.1 / LuCI Master (git-20.187.38662-0cb730a)
内核版本	5.4.50
### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
亲测有效

**Comment by cnhz76** [comment]
是的。可能是我本地缓存刷新的问题，重启浏览器后有效。谢谢回复！
