### ISSUE TITLE
最新版源码编译的竞斗云固件没有无线

### ISSUE THREAD

**Issue by Sunnice** [coolsnowwolf/lede#5034]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
使用最新源码编译的4.19内核的竞斗云固件没有无线

### (1) 具体问题

A：使用最新源码编译的4.19内核的竞斗云固件没有无线

### (2) 路由器型号和固件版本

A：竞斗云2.0

### (3) 详细日志

A：

**Comment by whlsxl** [comment]
试了很多次，好像是这个包引起的`luci-app-nft-qos`
