### ISSUE TITLE
make menuconfig 显示无法找到ncurses.h

### ISSUE THREAD

**Issue by swhoro** [coolsnowwolf/lede#5047]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：make menuconfig 后会显示无法找到ncurses.h
已经确定安装所有依赖
ubuntu版本为20.04

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/34229589/86997470-b911ad80-c1e0-11ea-9f2c-98cdea732827.png)

**Comment by minlang112** [comment]
试一下  sudo apt-get install libncurses5-dev

**Comment by swhoro** [comment]
> 试一下 sudo apt-get install libncurses5-dev

![image](https://user-images.githubusercontent.com/34229589/86999456-39d2a880-c1e5-11ea-9335-16986d31132a.png)
已经安装

**Comment by minlang112** [comment]
> > 试一下 sudo apt-get install libncurses5-dev
> 
> ![image](https://user-images.githubusercontent.com/34229589/86999456-39d2a880-c1e5-11ea-9335-16986d31132a.png)
> 已经安装

那看起来是pull的库文件有问题，删掉重新git pull吧

**Comment by swhoro** [comment]
> > > 试一下 sudo apt-get install libncurses5-dev
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34229589/86999456-39d2a880-c1e5-11ea-9335-16986d31132a.png)
> > 已经安装
> 
> 那看起来是pull的库文件有问题，删掉重新git pull吧

是整个lede文件夹删掉再clone吗？
还是只删掉某个文件夹呢？
不知道库文件是哪个

**Comment by minlang112** [comment]
> > > > 试一下 sudo apt-get install libncurses5-dev
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/34229589/86999456-39d2a880-c1e5-11ea-9335-16986d31132a.png)
> > > 已经安装
> > 
> > 
> > 那看起来是pull的库文件有问题，删掉重新git pull吧
> 
> 是整个lede文件夹删掉再clone吗？
> 还是只删掉某个文件夹呢？
> 不知道库文件是哪个

整个删除，然后重新git clone吧，保证网络通畅
