### ISSUE TITLE
luci-app-transmission安装成功但是界面不显示

### ISSUE THREAD

**Issue by jinjin327** [coolsnowwolf/lede#5050]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：luci-app-transmission安装成功但是路由器界面界面不显示

### (2) 路由器型号和固件版本

A：x86-64

### (3) 详细日志

A：

**Comment by keeno1982** [comment]
luci-app-transmission是被干掉了吗，我git pull后就看不到了

**Comment by jinjin327** [comment]
> luci-app-transmission是被干掉了吗，我git pull后就看不到了

编译的时候可以看见，编译好以后软件包里也显示安装成功但是界面不显示
