### ISSUE TITLE
默认的配置编译出来没有ipv6

### ISSUE THREAD

**Issue by xh0823** [coolsnowwolf/lede#5054]
默认的编译出来了wan6口没有ipv6地址要选择哪个呢？

**Comment by minlang112** [comment]
请编译时候勾选 ipv6 helper，默认是不带的

**Comment by xh0823** [comment]
> 请编译时候重置ipv6 helper，替代是不带的

是哪个选项呢？55r里面怎么找不到在哪里选择

**Comment by minlang112** [comment]
> > 请编译时候重置ipv6 helper，替代是不带的
> 
> 是哪个选项呢？55r里面怎么找不到在哪里选择

Extra packages —> ipv6helper

**Comment by xh0823** [comment]
ssr怎么搞出来呢 谢谢你说下



---原始邮件---
发件人: "狠心言少"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 晚上8:21
收件人: "coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"xh0823"<309745561@qq.com&gt;;
主题: Re: [coolsnowwolf/lede] 默认的配置编译出来没有ipv6 (#5054)




   
请编译时候重置ipv6 helper，替代是不带的
  
是哪个选项呢？55r里面怎么找不到在哪里选择
  
Extra packages —&gt; ipv6helper

**Comment by keivenliao** [comment]
![image](https://user-images.githubusercontent.com/12838693/87110434-9b544f00-c299-11ea-8791-1ed5d2507f62.png)
![image](https://user-images.githubusercontent.com/12838693/87110464-ac9d5b80-c299-11ea-875f-15f574ba0e5f.png)
![image](https://user-images.githubusercontent.com/12838693/87110483-b921b400-c299-11ea-8b6d-4e0720d81404.png)
![image](https://user-images.githubusercontent.com/12838693/87110504-c8086680-c299-11ea-95f3-8d72e119a53d.png)
![image](https://user-images.githubusercontent.com/12838693/87110549-e2424480-c299-11ea-9b04-e566fd86f94a.png)

编译完毕后，以上几个地方设置一下就应该可以了。

**Comment by hcwang** [comment]
使用以上设置后，SSR Plus是否可以正常使用？多谢！

**Comment by minlang112** [comment]
> 使用以上设置后，SSR Plus是否可以正常使用？多谢！

SSR plus和这个并无任何关系，在git clone之后编辑feeds.conf.default，去掉helloworld那行的#，保存，然后再继续进行feeds的更新配置，然后make menuconfig，在luci的application里就能找到你想要的东西了。

**Comment by hcwang** [comment]
SSR Plus和ipv6有冲突呀，在群里面搜索一下。

**Comment by minlang112** [comment]
> SSR Plus和ipv6有冲突呀，在群里面搜索一下。

没有冲突，可以同时使用。如果开启了IPV6的AAAA解析（默认选项是关闭），部分墙外的双栈网站会优先返回IPV6地址，导致第一次访问的时候返回被污染的结果，多刷新几次就正常了；另部分屏蔽中国IP的双栈网站会因为该问题导致拒绝访问，将此种站点加入强制走代理的列表即可。

**Comment by hcwang** [comment]
我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？

**Comment by NightZy** [comment]
> 我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？

我也遇到同样的问题，并且这个问题在官方原版openwrt中也有

**Comment by NightZy** [comment]
> > 我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？
> 
> 我也遇到同样的问题，并且这个问题在官方原版openwrt中也有，可能是 Softether VPN 配置的问题，求指点

我遇到的问题与你略有不同，我通过 softether vpn 可以获得 ipv6 地址，但不能获得 ipv6 默认网关，所以 ipv6 不能正常使用，我找到了解决方案。
[https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1065#issuecomment-570795731](url)

**Comment by hcwang** [comment]
> > > 我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？
> > 
> > 
> > 我也遇到同样的问题，并且这个问题在官方原版openwrt中也有，可能是 Softether VPN 配置的问题，求指点
> 
> 我遇到的问题与你略有不同，我通过 softether vpn 可以获得 ipv6 地址，但不能获得 ipv6 默认网关，所以 ipv6 不能正常使用，我找到了解决方案。
> [SoftEtherVPN/SoftEtherVPN#1065 (comment)](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1065#issuecomment-570795731)

非常感谢，可否把你的TAP设置的详细步骤发个教程，多谢了！

**Comment by NightZy** [comment]
> > > > 我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？
> > > 
> > > 
> > > 我也遇到同样的问题，并且这个问题在官方原版openwrt中也有，可能是 Softether VPN 配置的问题，求指点
> > 
> > 
> > 我遇到的问题与你略有不同，我通过 softether vpn 可以获得 ipv6 地址，但不能获得 ipv6 默认网关，所以 ipv6 不能正常使用，我找到了解决方案。
> > [SoftEtherVPN/SoftEtherVPN#1065 (comment)](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1065#issuecomment-570795731)
> 
> 非常感谢，可否把你的TAP设置的详细步骤发个教程，多谢了！

除了上面说的解决方案，我并没有进行什么特殊的配置，以下就是步骤了。

1. tap设备的配置
![image](https://user-images.githubusercontent.com/31581596/89210999-ae85e080-d5f3-11ea-840b-a2b7254a4018.png)
2. Openwrt：桥接tap到LAN上
![image](https://user-images.githubusercontent.com/31581596/89211157-f7d63000-d5f3-11ea-9cea-92e0a24de7d5.png)
3. 获取不到ipv6默认网关的解决方法
![image](https://user-images.githubusercontent.com/31581596/89211584-a8dcca80-d5f4-11ea-928f-021c6faecb40.png)

**Comment by hcwang** [comment]
> > > > > 我使用了以上设置，IPV6工作一切正常。另外，使用Softether VPN搭建了一个VPN Server，使用的是TAP类型，将其与LAN网卡进行关联。但通过Softether VPN远程拔上来的设备只能获得LAN的IPV4地址，而无法获得IPV6地址，是有什么地方设置不对吗？
> > > > 
> > > > 
> > > > 我也遇到同样的问题，并且这个问题在官方原版openwrt中也有，可能是 Softether VPN 配置的问题，求指点
> > > 
> > > 
> > > 我遇到的问题与你略有不同，我通过 softether vpn 可以获得 ipv6 地址，但不能获得 ipv6 默认网关，所以 ipv6 不能正常使用，我找到了解决方案。
> > > [SoftEtherVPN/SoftEtherVPN#1065 (comment)](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/1065#issuecomment-570795731)
> > 
> > 
> > 非常感谢，可否把你的TAP设置的详细步骤发个教程，多谢了！
> 
> 除了上面说的解决方案，我并没有进行什么特殊的配置，以下就是步骤了。
> 
> 1. tap设备的配置
>    ![image](https://user-images.githubusercontent.com/31581596/89210999-ae85e080-d5f3-11ea-840b-a2b7254a4018.png)
> 2. Openwrt：桥接tap到LAN上
>    ![image](https://user-images.githubusercontent.com/31581596/89211157-f7d63000-d5f3-11ea-9cea-92e0a24de7d5.png)
> 3. 获取不到ipv6默认网关的解决方法
>    ![image](https://user-images.githubusercontent.com/31581596/89211584-a8dcca80-d5f4-11ea-928f-021c6faecb40.png)

好像你们都没有vlan以及无线给桥接，以下是我的设置。
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1157211/89240708-7ef4c980-d62f-11ea-947c-7ab6d2ab624c.png">

**Comment by yicj** [comment]
正在研究呢，我试试呢。
