### ISSUE TITLE
IPSec 服务器，连接成功只能访问Lan，不能访问其他网站

### ISSUE THREAD

**Issue by victordou** [coolsnowwolf/lede#5055]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：IPSec 服务器，连接成功只能访问Lan，不能访问其他网站

### (2) 路由器型号和固件版本

A：ESXI+x86, 群里大雕的20.7.7 和 自己openwrt-ci编译的20.7.7，IPSec 均有问题。

### (3) 详细日志

A：
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/4896128/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/4896131/default.txt)

**Comment by xcf13363175** [comment]
同样问题，时间长了手机自动断连

**Comment by coolice231** [comment]
中午编译的我这边手机都连接不上了

**Comment by mjyhj** [comment]
本来就是这样

**Comment by keivenliao** [comment]
推荐使用 softether 打包解决方案

**Comment by coolsnowwolf** [comment]
桥接到 LAN是 可以了，出战流量在内核存在问题

暂时使用 4.19 或者  softether 解决吧

**Comment by victordou** [comment]
不升级了，用老版本挺好的。
