### ISSUE TITLE
verysync-linux-amd64-v1.4.3.tar.gz 包错误

### ISSUE THREAD

**Issue by ptsa** [coolsnowwolf/lede#5059]
verysync-linux-amd64-v1.4.3.tar.gz
这个包 下载以后打不开 导致编译错误

**Comment by mjyhj** [comment]
1.4.4啊

**Comment by ptsa** [comment]
编译时候下载的就是这个包

**Comment by hue715** [comment]
verysync的Makefile中有获取最新版本的指令，但指令执行失败（ubuntu20.04测试失败），无法下载最新的代码包。
<img width="702" alt="截屏2020-07-12 上午12 44 55" src="https://user-images.githubusercontent.com/22958922/87229228-18d2a900-c3d9-11ea-88cc-39efd51b4553.png">

### 最新版本失败报错：
<img width="702" alt="截屏2020-07-12 上午12 41 15" src="https://user-images.githubusercontent.com/22958922/87229245-2d16a600-c3d9-11ea-8573-29d1efbae63b.png">

**Comment by EnnawYang** [comment]
> verysync的Makefile中有获取最新版本的指令，但shell指令执行失败（ubuntu20.04测试失败），无法下载最新的代码包。
> <img alt="截屏2020-07-12 上午12 44 55" width="702" src="https://user-images.githubusercontent.com/22958922/87229228-18d2a900-c3d9-11ea-88cc-39efd51b4553.png">
> 
> ### 最新版本失败报错：
> <img alt="截屏2020-07-12 上午12 41 15" width="702" src="https://user-images.githubusercontent.com/22958922/87229245-2d16a600-c3d9-11ea-8573-29d1efbae63b.png">

sudo apt-get install curl
