### ISSUE TITLE
无线国家代码设置为“00-World”时不能开启无线网络

### ISSUE THREAD

**Issue by Vicent-xd** [coolsnowwolf/lede#5062]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
无线国家代码设置为“00-World”时不能开启无线网络

### (2) 路由器型号和固件版本
Phicomm-K3 A1
OpenWrt R20.7.7 / LuCI Master (git-20.191.36863-eee6bae)

### (3) 详细日志
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Line 6: Invalid country_code '00'
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Cannot enable IEEE 802.11d without setting the country_code
Fri Jul 10 10:08:23 2020 daemon.err hostapd: 2 errors found in configuration file '/var/run/hostapd-phy1.conf'
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Failed to set up interface with /var/run/hostapd-phy1.conf
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio1 (1780): Command failed: Invalid argument
Fri Jul 10 10:08:23 2020 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy0.conf (phy wlan0) --> new PHY
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Line 6: Invalid country_code '00'
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Cannot enable IEEE 802.11d without setting the country_code
Fri Jul 10 10:08:23 2020 daemon.err hostapd: 2 errors found in configuration file '/var/run/hostapd-phy0.conf'
Fri Jul 10 10:08:23 2020 daemon.err hostapd: Failed to set up interface with /var/run/hostapd-phy0.conf
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio1 (1780): WARNING (wireless_add_process): executable path /usr/sbin/wpad does not match process  path (/proc/exe)
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio0 (1779): Command failed: Invalid argument
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio1 (1780): Command failed: Invalid argument
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio0 (1779): WARNING (wireless_add_process): executable path /usr/sbin/wpad does not match process  path (/proc/exe)
Fri Jul 10 10:08:23 2020 daemon.notice netifd: radio0 (1779): Command failed: Invalid argument
Fri Jul 10 10:08:24 2020 kern.info kernel: [   20.024772] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
Fri Jul 10 10:08:24 2020 kern.info kernel: [   20.056368] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

**Comment by coolsnowwolf** [comment]
上游代码不再支持
