### ISSUE TITLE
2020-07-09 编译5.4 X86，运行几个小时死机，可复现！

### ISSUE THREAD

**Issue by mcucore** [coolsnowwolf/lede#5063]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

如题，4.19 一直很稳定，昨天重新便宜5.4内核的，结果几个小时后死机了，手动重启能恢复，今天早上发现又死机了，PING不通。刷回4.19貌似没发现问题。日志没有了。有同样情况的吗？N270

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
x86 没有任何调整和测试，也不会再测试

请使用 x64 硬件

**Comment by martin0607** [comment]
x64亲测没有问题。

**Comment by ihuaer** [comment]
x64亲测没有问题

**Comment by jzhou404** [comment]
新内核 X64 单臂路由不能工作，软路由显示都是正常的，接入的电脑都不能访问外网。

换回4.19.122 R20.5.20，恢复正常

**Comment by mcucore** [comment]
路由没接显示器，当时急着用也没法看日志，很有可能是网卡驱动挂了。
问题应该出在RTL8169和RTL8168驱动，我的8110被错误驱动了，去掉8168只选8169时貌似没问题~！
