### ISSUE TITLE
nanopiR2S 编译不显示CPU实时频率和温度

### ISSUE THREAD

**Issue by ghost** [coolsnowwolf/lede#5065]
### (1) 具体问题

A：选择了autocore默认不会编译autocore组件，需要对源码进行更改。
更改文件https://github.com/mapestliu/Lean.OpenWRT/blob/master/All/Autocore.diff
希望可以加入源码中。

**Comment by DanielChen008** [comment]
编译 R2S 时在 make menuconfig 中怎么选？我怎么没找到对应的处理器

**Comment by mapestliu** [comment]
> 编译R2S时在make menuconfig中怎么选？我怎么没找到对应的处理器

1、rockchip
2、rockchip_armv8
3、friendlyarm_nanopi-r2s

**Comment by DanielChen008** [comment]
> > 编译R2S时在make menuconfig中怎么选？我怎么没找到对应的处理器
> 
> 1、rockchip
> 2、rockchip_armv8
> 3、friendlyarm_nanopi-r2s

感谢！最近刚搞了两台R2S，这小玩意挺不错，一个放公司电脑边，一个出差随身带。

**Comment by joesdu** [comment]
> > 编译R2S时在make menuconfig中怎么选？我怎么没找到对应的处理器
> 
> 1、rockchip
> 2、rockchip_armv8
> 3、friendlyarm_nanopi-r2s

这个pi性能怎么样哦，平时温度和CPU占用率一般在多少？

**Comment by DanielChen008** [comment]
> > > 编译R2S时在make menuconfig中怎么选？我怎么没找到对应的处理器
> > 
> > 
> > 1、rockchip
> > 2、rockchip_armv8
> > 3、friendlyarm_nanopi-r2s
> 
> 这个pi性能怎么样哦，平时温度和CPU占用率一般在多少？

1：温度较高，不上散热感觉随时可以到70°；
2：性能适合500M以下宽带接入的用户，我用R2S 在千兆宽带下最多只能跑出560，我不知道其他人怎么跑的，有人说用 Friendly 官方固件可以跑出800-900；
3：CPU占用率倒不高，我在AES下跑4KHDR 60FPS的YouTuBe视频时也才15%不到；
4：优点可能就是小巧了吧，可以塞进弱电箱；
5：家用软路由还是推荐x86一步到位吧，比如我用了3年的 J1900稳的一批，或者后来更火的 3865U;

**Comment by joesdu** [comment]
> > > > 编译R2S时在make menuconfig中怎么选？我怎么没找到对应的处理器
> > > 
> > > 
> > > 1、rockchip
> > > 2、rockchip_armv8
> > > 3、friendlyarm_nanopi-r2s
> > 
> > 
> > 这个pi性能怎么样哦，平时温度和CPU占用率一般在多少？
> 
> 1：温度较高，不上散热感觉随时可以到70°；
> 2：性能适合500M以下宽带接入的用户，我用R2S 在千兆宽带下最多只能跑出560，我不知道其他人怎么跑的，有人说用 Friendly 官方固件可以跑出800-900；
> 3：CPU占用率倒不高，我在AES下跑4KHDR 60FPS的YouTuBe视频时也才15%不到；
> 4：优点可能就是小巧了吧，可以塞进弱电箱；
> 5：家用软路由还是推荐x86一步到位吧，比如我用了3年的 J1900稳的一批，或者后来更火的 3865U;

我目前用的D525,J1900的我用来当作测试服务器了,这个我昨晚也买了一个,主要是小巧.觉得还是挺不错的,加个散热倒是没啥,淘宝几块钱就搞定了.若是这个比较稳的话.还是挺不错,想把我那D525出了.

**Comment by joesdu** [comment]
![image](https://user-images.githubusercontent.com/13188169/88800980-8bb29100-d1db-11ea-8476-2552b08dc2e6.png)
编译出来了两个文件,用哪个比较好哦?这两个有啥区别吗?

**Comment by joesdu** [comment]
最新代码名称好像有了，温度好像还是不行
