### ISSUE TITLE
新代码的无线功率不能手动设置了

### ISSUE THREAD

**Issue by Crazy365** [coolsnowwolf/lede#5066]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

## 2. 详细叙述

使用新代码（1eb3eac387abd6b0a9148f4d2139a2bee6543a49）编译了K3固件，发现无线功率手动设置失效，不管选择哪一档，传输功率一直都显示为31 dBm。

### (1) 具体问题

A：使用新代码（1eb3eac387abd6b0a9148f4d2139a2bee6543a49）编译了K3固件，发现无线功率手动设置失效，不管选择哪一档，传输功率一直都显示为31 dBm。

### (2) 路由器型号和固件版本

A：K3，commit 1eb3eac387abd6b0a9148f4d2139a2bee6543a49

### (3) 详细日志

A：

**Comment by Aes64X** [comment]
K3用Openwrt 啥时候能手动设置功率了？？？

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/87216927-a5984b00-c376-11ea-82cf-5e540d1c6516.png)

**Comment by Crazy365** [comment]
@coolsnowwolf 我设置“无线电功率”为20 dBm，但上面的“传输功率”仍然为31 dBm。

<img width="619" alt="截屏2020-07-11 13 42 39" src="https://user-images.githubusercontent.com/21103136/87217522-a6cc7680-c37c-11ea-91ca-6e231ea2e70f.png">
