### ISSUE TITLE
最新的编译没有luci-app-acme

### ISSUE THREAD

**Issue by wspzf** [coolsnowwolf/lede#5069]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
最新的编译没有luci-app-acme
Q：是否搜索了issue (使用 "x" 选择)
 [ *] 没有类似的issue

### (1) 具体问题

A：最新的编译没有最新的编译没有luci-app-acme，R20.6.18编译时都还有，有什么办法恢复？

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：无

**Comment by openwrt-1983** [comment]
你去老版本里面把它找出来，放进去就可以用了   需要什么东西就把它捞出来放进去

**Comment by wspzf** [comment]
> 你去老版本里面把它找出来，放进去就可以用了 需要什么东西就把它捞出来放进去

老版本里也没有找到这个luci-app-acme，不知道是怎么关联的

**Comment by acooler15** [comment]
好像不能用。

**Comment by acooler15** [comment]
> 好像不能用。官方仓库里有https://github.com/openwrt/luci/blob/master/applications/luci-app-acme

好吧，luci-app-acme太先进了，用的luci2，关于luci2，看这里：https://openwrt.org/docs/techref/luci2
