### ISSUE TITLE
大神请教这怎么处理：谢谢。 TCP: request_sock_TCP: Possible SYN flooding on port 5000. Sending cookies.  Check SNMP counters.

### ISSUE THREAD

**Issue by osxdiy** [coolsnowwolf/lede#5072]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题
kern.info kernel: [31617.809376] TCP: request_sock_TCP: Possible SYN flooding on port 5000. Sending cookies.  Check SNMP counters.

A：

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志
kern.info kernel: [31617.809376] TCP: request_sock_TCP: Possible SYN flooding on port 5000. Sending cookies.  Check SNMP counters.

A：

**Comment by mardock2009** [comment]
net.core.somaxconn = 8192
net.ipv4.tcp_max_syn_backlog = 1024
