### ISSUE TITLE
树莓派4b新编译固件输入开机后未开启AP

### ISSUE THREAD

**Issue by nojd11** [coolsnowwolf/lede#5073]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题
使用issues创建前最新源码编译的固件在开机后并没有开启AP
A：

### (2) 路由器型号和固件版本
路由器型号：树莓派4b
固件/源码版本：2020-07-10最后一次提交的代码
A：

### (3) 详细日志
由于无法登陆后台因此无法截取日志
A：

**Comment by EnnawYang** [comment]
可以插网线登后台设置wifi

**Comment by SuLingGG** [comment]
先 make clean，然后下载这个脚本置于 OpenWrt 项目根目录 (lede 文件夹下)，执行后编译即可。

<https://raw.githubusercontent.com/SuLingGG/OpenWrt-Rpi/master/scripts/enable-rpi4-wifi.sh>

**（仅适用于树莓派 4B）**
