### ISSUE TITLE
v2ray只能使用全局？

### ISSUE THREAD

**Issue by taiziccf** [coolsnowwolf/lede#508]
编译后，只在使用全局才能正常上网。

如果选择了gfw-list或绕过中国IP，结果是任何网站都打不开。

只有选择了全局才能打开所有网站。

有什么办法能让中国IP不走v2ray？我希望所有中国的ip都能直连。

**Comment by kkkgirl** [comment]
遇到的问题一样，gfw-list或绕过中国IP不能生效。

**Comment by xyjzj2001** [comment]
后来是怎么解决的？
