### ISSUE TITLE
app-ocserv编译后ios无法正常连接

### ISSUE THREAD

**Issue by ruderal04o** [coolsnowwolf/lede#5080]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
新版本编译ocserv，openconnect。后用Iphone，anyconnect客户端无法连接。
报错无法连接
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
OpenWrt R20.7.7 
A：

### (3) 详细日志
GnuTLS error (at worker-vpn.c:794): A TLS fatal alert has been received
A：

**Comment by 8023** [comment]
6月1日前的版本好用，7月以后的就有问题了，可以试试旧版本的。
