### ISSUE TITLE
 luci-proto-bonding. ERRO

### ISSUE THREAD

**Issue by naoki66** [coolsnowwolf/lede#5083]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-proto-bonding:
 * 	proto-bonding
 * opkg_install_cmd: Cannot install package luci-proto-bonding.
package/Makefile:65: recipe for target 'package/install' failed

### (2) 路由器型号和固件版本

A：X64

### (3) 详细日志

A：Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-proto-bonding:
 * 	proto-bonding
 * opkg_install_cmd: Cannot install package luci-proto-bonding.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/mnt/dc/lede'
package/Makefile:108: recipe for target '/mnt/dc/lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/mnt/dc/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/mnt/dc/lede'
/mnt/dc/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by minlang112** [comment]
make distclean
然后重新走正常流程
