### ISSUE TITLE
请教各位大神，如何修改菜单的中文翻译，让菜单界面更整齐美观？

### ISSUE THREAD

**Issue by weweyes** [coolsnowwolf/lede#5084]
<img width="708" alt="12223233" src="https://user-images.githubusercontent.com/59646715/87248486-43316e80-c48c-11ea-8aa1-1334a7ae944a.png">
比如，把“网络存储”修改成“存储”，把“宽带监控”修改成“监控”，在源码哪里修改？

**Comment by coolsnowwolf** [comment]
语言包里面有
