### ISSUE TITLE
最近7月10日编译的固件，访问百度、B站全部去了国外IP？

### ISSUE THREAD

**Issue by godfriendedme** [coolsnowwolf/lede#5085]
大佬你好：
最近7月10日编译的固件，访问百度、B站全部去了国外IP？
而回退6月20日编译的固件没有这种问题
是不是我SSR+哪里设置的不正确？

**Comment by minlang112** [comment]
未遇到该问题，建议参考 https://github.com/shadowsocks/shadowsocks-windows/issues/1339

**Comment by houpi** [comment]
用的7月9号的Pandorabox，用的回国模式。微信应该也走到国内来了，发个消息都要转一圈

**Comment by muyeyifeng** [comment]
我也遇到了同样的问题，是7月16日编译的版本，斐讯N1-aarch64。
在55R中开启绕过中国大陆IP模式，则B站**番剧**显示**非常抱歉，根据版权方要求、您所在的地区无法观看本片**，是否意味将B站视频解析到国外去了？
而将55R设置为GFW模式，则无法进入Google，B站番剧可正常观看

**Comment by muyeyifeng** [comment]
我也遇到了同样的问题，是7月16日编译的版本，斐讯N1-aarch64。
在55R中开启绕过中国大陆IP模式，则B站**番剧**显示**非常抱歉，根据版权方要求、您所在的地区无法观看本片**，是否意味将B站视频解析到国外去了？
而将55R设置为GFW模式，则无法进入Google，B站番剧可正常观看
