### ISSUE TITLE
IPv4 WAN 状态显示不正确

### ISSUE THREAD

**Issue by lqh280** [coolsnowwolf/lede#5089]
设置网络LAN口的IPv4网关为192.168.1.1后，路由的：状态>概览,页面下方的网络，IPv4 WAN 状态，显示的是LAN口的IP信息，正常应该是显示WAN口IP信息吧。是哪里有问题？

(如果LAN口的IPv4网关留空不填，显示是WAN口信息)

**Comment by hcym** [comment]
从来没注意，一般设置3.1，避免和光猫冲突，ipv6一直不显示，必需到网络里面看，或者ping6确认😅

**Comment by coolsnowwolf** [comment]
LAN 设置网关就变为 WAN 了，没问题
