### ISSUE TITLE
一个会导致系统直接GG的BUG。

### ISSUE THREAD

**Issue by wbflike** [coolsnowwolf/lede#509]
![image](https://user-images.githubusercontent.com/22762921/44269062-fd4eda00-a265-11e8-86a0-06f304265292.png)
版本如图是32位的系统
![image](https://user-images.githubusercontent.com/22762921/44269091-16578b00-a266-11e8-9a32-d71dd970dd34.png)
当开启Brook后。
![image](https://user-images.githubusercontent.com/22762921/44269108-266f6a80-a266-11e8-9d45-16c046fe0f58.png)
输入服务器IP地址，端口密码点击保存运用。
这个时候WEB服务就失去响应。
重启路由。获取不到dhcp。这种手动IP后能ping通路由器，但是web访问不了，外网也不通。

**Comment by yes2003** [comment]
是的，貌似v2ray和brook都有这问题

**Comment by coolsnowwolf** [comment]
brook 挂了，再看看吧
