### ISSUE TITLE
能不能恢复Pad image to filesystem size选项

### ISSUE THREAD

**Issue by allok1985** [coolsnowwolf/lede#5092]
目前是默认填充固件镜像大小到文件系统大小，我x64固件编译后填充到500M，上传后sysupgrade命令升级部分插件功能不完整

**Comment by coolsnowwolf** [comment]
什么意思

**Comment by allok1985** [comment]
就是编译的固件现在是默认填充到设置大小   能不能像前期在Target Images选项下有Pad image to filesystem size选项，取消后不填充固件

**Comment by coolsnowwolf** [comment]
为什么？

**Comment by allok1985** [comment]
web升级上传.img.gz文件升级不了   解压后img上传用sysupgrade命令升级挂了...
