### ISSUE TITLE
wan口老是掉线

### ISSUE THREAD

**Issue by xiehuayi75** [coolsnowwolf/lede#5096]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
wan口一掉线就重启然后就不拨号了
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
x86
A：

### (3) 详细日志
Tue Jul 14 01:21:03 2020 user.info mwan3track[8962]: Check (ping) success for target "114.114.114.114" on interface wan (pppoe-wan)
Tue Jul 14 01:21:03 2020 user.info mwan3track[8962]: Check (ping) success for target "114.114.115.115" on interface wan (pppoe-wan)
Tue Jul 14 01:21:04 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:05 2020 user.notice mwan3[11715]: Execute ifup event on interface wan (pppoe-wan)
Tue Jul 14 01:21:05 2020 user.notice mwan3[11715]: Starting tracker on interface wan (pppoe-wan)
Tue Jul 14 01:21:05 2020 user.notice mwan3track[8962]: Stopping mwan3track for interface "wan"
Tue Jul 14 01:21:06 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:06 2020 user.info mwan3rtmon[5489]: Detect rtchange event.
Tue Jul 14 01:21:06 2020 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Tue Jul 14 01:21:06 2020 cron.err crond[12541]: crond (busybox 1.31.1) started, log level 5
Tue Jul 14 01:21:06 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:06 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:08 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:09 2020 daemon.info dnsmasq[12635]: Connected to system UBus
Tue Jul 14 01:21:09 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:09 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:10 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:12 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:12 2020 daemon.info dnsmasq[12828]: Connected to system UBus
Tue Jul 14 01:21:12 2020 user.notice root: starting ntpclient
Tue Jul 14 01:21:12 2020 user.notice firewall: Reloading firewall due to ifupdate of wan (pppoe-wan)
Tue Jul 14 01:21:12 2020 user.notice ddns-scripts[12939]: ipv4: PID '12939' started at 2020-07-14 01:21
Tue Jul 14 01:21:12 2020 cron.err crond[13413]: crond (busybox 1.31.1) started, log level 5
Tue Jul 14 01:21:12 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:12 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:13 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:15 2020 daemon.info dnsmasq[15255]: Connected to system UBus
Tue Jul 14 01:21:15 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:15 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:15 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:17 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:18 2020 daemon.info dnsmasq[15778]: Connected to system UBus
Tue Jul 14 01:21:19 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:21 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:23 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:25 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:27 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:28 2020 user.info mwan3rtmon[5489]: Detect rtchange event.
Tue Jul 14 01:21:28 2020 user.notice firewall: Reloading firewall due to ifup of wan6 (pppoe-wan)
Tue Jul 14 01:21:28 2020 cron.err crond[16281]: crond (busybox 1.31.1) started, log level 5
Tue Jul 14 01:21:28 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:28 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:29 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:31 2020 daemon.info dnsmasq[16382]: Connected to system UBus
Tue Jul 14 01:21:31 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 14 01:21:31 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 14 01:21:31 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:33 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:34 2020 daemon.info dnsmasq[16573]: Connected to system UBus
Tue Jul 14 01:21:35 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:37 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:39 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:41 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:43 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:45 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:47 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:49 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:51 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:53 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:55 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:57 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:21:59 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:01 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:03 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:05 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:07 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:09 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:11 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:13 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:15 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Tue Jul 14 01:22:17 2020 daemon.err netdata[5769]: PROCFILE: Cannot open file '/proc/sysvipc/shm'

A：

**Comment by coolsnowwolf** [comment]
卸载mwan3
