### ISSUE TITLE
最近的代码编译出现WARNING

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#5099]
Hi Team,

最近编译固件时候总是发生WARNGING
截图如下：
![warning](https://user-images.githubusercontent.com/25215114/87372363-ee8c1180-c5b9-11ea-95de-10574d786d4a.png)

而且有时候编译也会不成功，请问有什么解决办法吗？

BR
Robin

**Comment by acooler15** [comment]
oldpackages是什么软件源？😶

**Comment by Guxing0321** [comment]
Hi Team,

我是将 git库里面 feeds.conf.default 注释去掉了
在去掉之前也是会有这种warning 

BR
Robin

**Comment by acooler15** [comment]
warning提示，一般都有。

**Comment by Guxing0321** [comment]
Hi acooler15，

也就是说这个不用管了？


BR
Robin

**Comment by acooler15** [comment]
> Hi acooler15，
> 
> 也就是说这个不用管了？
> 
> BR
> Robin

嗯嗯，只要不是ERROR，就不管它

**Comment by Guxing0321** [comment]
Hi acooler15,

好的，收到，谢谢

BR
Robin
