### ISSUE TITLE
突然发现隔壁“/openwrt”仓库源码编译完卡Booting the kernel

### ISSUE THREAD

**Issue by martin0607** [coolsnowwolf/lede#5102]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：使用默认配置，X86_64，编译完，不管是UEFI还是Legacy，都是卡内核，启动不了。编译了不下十次，云编译，主力机编译。不知是否个例，我在VMWare和实体机上都试过了。有时间的话大家看看是否也这样？

### (2) 路由器型号和固件版本

A：X86_64，N3050 + 2GB，coolsnowwolf/openwrt

### (3) 详细日志

A：
![批注 2020-07-14 150941](https://user-images.githubusercontent.com/32560181/87395617-3cb60a80-c5e4-11ea-8a02-91b99f262eee.jpg)

**Comment by EnnawYang** [comment]
劳烦您按下回车

**Comment by martin0607** [comment]
> 劳烦您按下回车

这个回车按进去好像并没有进系统，是以临时账户进的终端。。

**Comment by xiehuayi75** [comment]
人家不是说了这次大版本后界面不会跟从前一样跑字符

**Comment by xx10n31y** [comment]
这也能发issue了?

**Comment by martin0607** [comment]
> 这也能发issue了?

是

**Comment by tikkacn** [comment]
我也遇到了一样的问题，不过我的连提示按回车的信息都没有，只是无限重启。
