### ISSUE TITLE
Report 一个小问题 “ Linksys WRT32x dual boot”

### ISSUE THREAD

**Issue by iKenzo** [coolsnowwolf/lede#5108]
5.4 的 Linksys WRT32x dual boot 貌似不工作，如下：

![Screen Shot 2020-07-15 at 14 27 22](https://user-images.githubusercontent.com/34348620/87511309-aea35800-c6a7-11ea-83e4-b1f7779600a7.png)

**Comment by teapethu** [comment]
一样的问题，ssh下命令行切换可用，LuCI不行。

**Comment by AmadeusGhost** [comment]
luci 并入这个 commit 试试：https://github.com/AmadeusGhost/luci/commit/ab851a1c88a170d5938a4749c23f56c7ddeb6fba
