### ISSUE TITLE
运行9天出现问题

### ISSUE THREAD

**Issue by tengyuankoo** [coolsnowwolf/lede#5111]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：运行9天，5G连接不上提示密码错误，实际密码没改过是对的，重启进后台跳错误信息

### (2) 路由器型号和固件版本

A：红米AC2100 5.4.50

### (3) 详细日志

A：/usr/lib/lua/luci/dispatcher.lua:569: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/usr/lib/lua/luci/dispatcher.lua:569: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
![image](https://user-images.githubusercontent.com/56631063/87555264-cef30700-c6e7-11ea-95bc-e2adfd62553a.png)

**Comment by tengyuankoo** [comment]
固件做AP使用，没选服务插件，应该没有冲突

**Comment by qiqiandfei** [comment]
更改5G信道试试
