### ISSUE TITLE
编译（20G）大容量squashfs-img,实际编译的包大于38g还在继续增长。

### ISSUE THREAD

**Issue by linxuankent** [coolsnowwolf/lede#5114]
给虚拟机分配了200G硬盘都编译满了还不够。以前编译都是正常的，从上周开始编译出现这个问题。
![33333](https://user-images.githubusercontent.com/11692396/87626851-f2f22f00-c75f-11ea-9e8c-14abf59bdd60.png)
![1222](https://user-images.githubusercontent.com/11692396/87626858-f5ed1f80-c75f-11ea-95f8-21117ebd4c34.png)

**Comment by EnnawYang** [comment]
头一次见到设置几十个G大小的固件，按照你这个设置的话img大小正常在30G左右

**Comment by xiehuayi75** [comment]
你逗着玩呢

**Comment by linxuankent** [comment]
> 你逗着玩呢



> 头一次见到设置几十个G大小的固件，按照你这个设置的话img大小正常在30G左右
这下图才是正常编译完的大小，我软路由本身就120G ssd,要不是空间不够我直接编译120g的固件懒得在安装完系统后在分配空间。
我之前也是这么设置的编译出来就应该不会到
![企业微信截图_15948820897616](https://user-images.githubusercontent.com/11692396/87636482-68b3c600-c773-11ea-9e9f-e803943e6f63.png)

**Comment by minlang112** [comment]
为何要如此操作……直接U盘启动，把ssd全部挂载给openwrt岂不美哉

**Comment by mapestliu** [comment]
启用压缩就可以了，我编译64G的也才几十兆
CONFIG_TARGET_IMAGES_GZIP=y

**Comment by linxuankent** [comment]
> CONFIG_TARGET_IMAGES_GZIP = y

晚点试下

**Comment by linxuankent** [comment]
> 为何要如此操作……直接U盘启动，把ssd全部挂载给openwrt岂不美哉

那不就是相当于浪费个u盘一直用着

**Comment by hxlls** [comment]
要升级都要40G的内存，要不升级不了，这是神操作？op 设置的小容量，然后挂载的剩余分区不完事了。

**Comment by linxuankent** [comment]
> 启用压缩就可以了，我编译64G的也才几十兆
> CONFIG_TARGET_IMAGES_GZIP = y

直接在config.in中添加就行了吗？

**Comment by mapestliu** [comment]
.config中，你看看默认有没有启用

**Comment by mapestliu** [comment]
我是写好配置文件去编译，在上面选择不习惯，或者你看看选择项里面有没有。

**Comment by linxuankent** [comment]
> 我是写好配置文件去编译，在上面选择不习惯，或者你看看选择项里面有没有。

可以了谢谢
