### ISSUE TITLE
如何关闭DNS劫持功能

### ISSUE THREAD

**Issue by dodogao** [coolsnowwolf/lede#5119]
目前所有DNS的解析请求都会被路由器劫持。如何设置，才能关闭此功能，只允许发给192.168.1.1的DNS报文被劫持?

**Comment by kd142718** [comment]
防火墙删掉这两行
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

**Comment by dodogao** [comment]
感谢，测试有效
