### ISSUE TITLE
ipq40xx换交换机驱动了吗,比以前那个难用好多

### ISSUE THREAD

**Issue by zjy2200656** [coolsnowwolf/lede#5124]
反馈bug/问题模板，提建议请删除
wan口无法分vlan了,lan口也是

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

2. 详细叙述
分vlan后无法联通

A：

### (2) 路由器型号和固件版本

A：r&w r619ac 128m r20.7,7

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
对，现在用的是官方 op 的，以前是我们自己维护的，因为感觉大家都喜欢官方

**Comment by zjy2200656** [comment]
> 对，现在用的是官方 op 的，以前是我们自己维护的，因为感觉大家都喜欢官方
现在只能用软vlan了,硬件vlan无法连接,也看不到log

**Comment by llfj** [comment]
> 对，现在用的是官方 op 的，以前是我们自己维护的，因为感觉大家都喜欢官方

我没觉得官方有多好啊。你优化的还是很不错的。。。
