### ISSUE TITLE
wireguard

### ISSUE THREAD

**Issue by hcym** [coolsnowwolf/lede#513]
大佬，wireguard能不能加一个路由分流？
也就是和ssr，v2ray一样的ipset功能
码盲实在是搞不掂

**Comment by coolsnowwolf** [comment]
这个没关注

**Comment by LGA1150** [comment]
luci-app-vpn-policy-routing https://github.com/stangri/openwrt_packages
没中文，你可以提交中文翻译 PR
![image](https://user-images.githubusercontent.com/9155358/44920884-a112ac80-ad73-11e8-8b08-60fdb1a1eb73.png)

**Comment by hcym** [comment]
我的妈，太感谢了，中文没所谓，一直英文，基本靠蒙

**Comment by hcym** [comment]
@LGA1150 没有 luci-app-vpn-policy-routing啊，依赖vpn-policy-routing倒是正常添加，luci里面的添加不了吗？看make也没看出端倪，添加其他的第三方都可以选择

**Comment by hcym** [comment]
编译顺利，使用头大大，就想着怎么直接使用ssr等等的现成list。呵呵
