### ISSUE TITLE
编译时luci-application里面显示没有smartdns

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [coolsnowwolf/lede#5133]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：我在 package/lean/ 目录下面看到有smartdns，然后我自己在smartdns下面make了一下。但是luci-application里面依然找不到smartdns，想问一下是什么问题。谢谢各位！
![image](https://user-images.githubusercontent.com/28868457/87858196-bb9da100-c95e-11ea-9e8b-5772e0169c82.png)

### (2) 路由器型号和固件版本

A：Redmi AC2100

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
为什么会有？

**Comment by Ljzkirito** [comment]
lean大佬删除了luci-app-smartdns，需要的话自行添加
https://github.com/pymumu/luci-app-smartdns
