### ISSUE TITLE
ssr plus和nodogsplash冲突

### ISSUE THREAD

**Issue by MannyDo** [coolsnowwolf/lede#5140]
之所以用到nodogsplash这个插件是希望实现在客人连接wifi时弹一个登陆页面（类似于KFC那种），客人点击一下后可以直接上网，现在的问题是，在开启nodogsplash和ssr plus时，连接wifi后只能上内网，不能上外网，但是关闭nodogsplash，开启ssr plus时，内外网均可访问，不知道这里面到底时哪里出了问题。我个人判断时端口方面的问题，因为nodogspalsh会先接管80端口的请求，用于弹出页面，大神能不能给点解决问题的思路啊

主机型号 | Netgear R6220 (CpuMark : 2259.184999 Scores)
-- | --
架构 | MediaTek MT7621 ver:1 eco:3 x 2
固件版本 | OpenWrt R20.2.15 / LuCI Master (git-20.051.42827-3e80fef)
内核版本 | 4.14.169

**Comment by coolsnowwolf** [comment]
理论上无法解决

**Comment by MannyDo** [comment]
> 理论上无法解决

谢谢大佬
