### ISSUE TITLE
openwrt清爽material风格主题分享

### ISSUE THREAD

**Issue by garypang13** [coolsnowwolf/lede#5149]
修改自luci-theme-argon,做了大量细节优化.
截图自Luci19.07,  Luci18.06因为其本分的局限性,显示效果有些许不同,

https://github.com/garypang13/luci-theme-edge/releases

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/1.png)

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/2.png)

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/3.png)

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/4.png)

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/5.png)
<br/>
<br />
<img src="https://user-images.githubusercontent.com/48883331/87935984-a6db1d80-cac4-11ea-9c97-ec0e0ee68520.png" width="550" />

![](https://github.com/garypang13/luci-theme-edge/raw/master/Screenshots/7.png)

**Comment by dolphinpaopao** [comment]
截图概览cpu信息不对呀，i3 7100u是双核四线程不是四核四线程。哈哈，强迫症max。

**Comment by garypang13** [comment]
> 截图概览cpu信息不对呀，i3 7100u是双核四线程不是四核四线程。哈哈，强迫症max。

可能是我套了个PVE的原因吧,

**Comment by EnnawYang** [comment]
18.06浏览日志页面还有点问题，不能上下翻滚

**Comment by dolphinpaopao** [comment]
> > 截图概览cpu信息不对呀，i3 7100u是双核四线程不是四核四线程。哈哈，强迫症max。
> 
> 可能是我套了个PVE的原因吧,

我现在去编译一个试一下。感谢分享。

**Comment by OleStore** [comment]
讲真？花里胡哨的，不喜欢

**Comment by yubanmeiqin9048** [comment]
啊，这，为什么要放到Issues

**Comment by xiaoguoyi** [comment]
系统日志没法翻页
![image](https://user-images.githubusercontent.com/54239687/87961510-5f668880-cae8-11ea-9dd0-e71b05f2a505.png)

**Comment by xiaoguoyi** [comment]
退出没有图标
![image](https://user-images.githubusercontent.com/54239687/87962326-97ba9680-cae9-11ea-8a03-434c1e8e3c10.png)

**Comment by github-xihe** [comment]
这主题挺好看的，不过在18.06还需要打磨打磨，期待完美版

**Comment by OPnb** [comment]
如果是bootstrap那样就完美了

**Comment by keivenliao** [comment]
装一个体验一下

**Comment by chuansao-258** [comment]
> 如果是bootstrap那样就完美了

恋丑你就默认就好了

**Comment by mysteryman2045** [comment]
Newifi D2，06.30那天编译的L大的固件，直接路由器内部文件上传luci-theme-edge_1.6-20200722_19.07.ipk
到路由器安装，后直接页面全白，连登录页面都是。Google Chrome，Firefox，IE浏览器都不好使，恰恰自己路由器SSH没配置，想SSH进路由器指令修改过来也没机会。不得不刚刚重新刷了固件。😭

**Comment by garypang13** [comment]
> Newifi D2，06.30那天编译的L大的固件，直接路由器内部文件上传luci-theme-edge_1.6-20200722_19.07.ipk
> 到路由器安装，后直接页面全白，连登录页面都是。Google Chrome，Firefox，IE浏览器都不好使，恰恰自己路由器SSH没配置，想SSH进路由器指令修改过来也没机会。不得不刚刚重新刷了固件。😭

要确认你用的luci版本,L大的分为luci17,luci18.06,luci19.07,该主题只有luci18.06和luci19.07版本,如果你是Luci17的话就用不了,

**Comment by mysteryman2045** [comment]
> > Newifi D2，06.30那天编译的L大的固件，直接路由器内部文件上传luci-theme-edge_1.6-20200722_19.07.ipk
> > 到路由器安装，后直接页面全白，连登录页面都是。Google Chrome，Firefox，IE浏览器都不好使，恰恰自己路由器SSH没配置，想SSH进路由器指令修改过来也没机会。不得不刚刚重新刷了固件。😭
> 
> 要确认你用的luci版本,L大的分为luci17,luci18.06,luci19.07,该主题只有luci18.06和luci19.07版本,如果你是Luci17的话就用不了,

看了下 luci版本git-20.180.30743-de9fdad-1

**Comment by lloyd18** [comment]
楼主你好，docker图标有吗
![Snipaste_2020-07-24_16-00-34](https://user-images.githubusercontent.com/10294460/88371552-d3de4780-cdc6-11ea-9b5b-b34e1e90e163.png)

**Comment by garypang13** [comment]
> 楼主你好，docker图标有吗
> ![Snipaste_2020-07-24_16-00-34](https://user-images.githubusercontent.com/10294460/88371552-d3de4780-cdc6-11ea-9b5b-b34e1e90e163.png)

有

**Comment by stvber** [comment]
背景换个颜色会好点，太白了
