### ISSUE TITLE
内核版本5.4.50，netdata编译进去以后无法使用

### ISSUE THREAD

**Issue by mnubytpk** [coolsnowwolf/lede#5155]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by minlang112** [comment]
测试可以正常使用，建议提交详细故障描述或截图

**Comment by mnubytpk** [comment]
今天刚刚又编译了一次固件，然后点击“状态”--“实时监控”就显示“连接已重置”
----------------------------------------
All the best!
From Tracy


coolsnowwolf <notifications@github.com> 于2020年7月23日周四 下午12:52写道：

**Comment by hcym** [comment]
这个玩意蛮多cpu的，x86都能看到，体质虚弱的估计会出现不适症状
