### ISSUE TITLE
大麦 dw33d 16m rom 无法编译最新版固件，内核过大，需要调整或者为小rom建立分支停止更新

### ISSUE THREAD

**Issue by geerda123** [coolsnowwolf/lede#5157]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译最新固件，删除没用插件仍然无法编译出bin升级文件。我查询以前issues，有提到过该问题，但查询最新版编译文件跟以前issues解决方法一样，仍然无法编译。有可能固件内核过大，换成5.4内核以前commits也一样问题。希望能开个分支给以前小rom老路由停止内核升级，否则经常无法编译

### (2) 路由器型号和固件版本

A：大麦 dw33d 
![image](https://user-images.githubusercontent.com/18500636/88129837-a7ca9700-cc0b-11ea-82d2-cb10e435a489.png)

**Comment by coolsnowwolf** [comment]
这个固件内核分区非常小，只能 1.375MB 内，但 ROM 分区又很大

**Comment by geerda123** [comment]
我在202003编译过一次默认，可以编译出来文件。现在每天都有升级，不可能都检查。我觉得还是给老版另开个分支，重大更新再push，issue中也能减少不少问题。谁的老路由有问题直接用分支文件

coolsnowwolf <notifications@github.com> 于 2020年7月22日周三 12:18写道：

**Comment by coolsnowwolf** [comment]
请找另外一个稳定版的仓库

**Comment by geerda123** [comment]
自己建了个分支，5月份是最后适合dw33d，再更新意义不大。留给有需要的人

https://github.com/anonymous12357/lede
