### ISSUE TITLE
勾选luci-app-docker编译报错

### ISSUE THREAD

**Issue by yubanmeiqin9048** [coolsnowwolf/lede#5166]
can't load package: package github.com/docker/cli/cmd/docker: 
../.go_work/build/src/github.com/docker/cli/cmd/docker/docker.go:1:1: expected 'package', found 'EOF'
make[3]: *** [Makefile:139: /home/zhang/lede/build_dir/target-aarch64_generic_musl/docker-ce-19.03.12/.built] Error 1
make[3]: Leaving directory '/home/zhang/lede/feeds/packages/utils/docker-ce'
time: package/feeds/packages/docker-ce/compile#0.12#0.02#0.16
make[2]: *** [package/Makefile:113: package/feeds/packages/docker-ce/compile] Error 2
make[2]: Leaving directory '/home/zhang/lede'
make[1]: *** [package/Makefile:107: /home/zhang/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhang/lede'
make: *** [/home/zhang/lede/include/toplevel.mk:224: world] Error 2

**Comment by minlang112** [comment]
../.go_work/build/src/github.com/docker/cli/cmd/docker/docker.go 大概这是个空文件，你可以试试删除它
