### ISSUE TITLE
小米路由器3 2.4gwifi无法驱动

### ISSUE THREAD

**Issue by jhsb** [coolsnowwolf/lede#5167]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
x [ ] 没有类似的issue

### (1) 具体问题

A：小米路由器3无法驱动2.4g wifi
芯片是7620a和7612的组合
编译时已勾选驱动76x0e 76x0u 和76x2

### (2) 路由器型号和固件版本

A：r3 op7.7

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
给个日志有这么难吗？
