### ISSUE TITLE
小米AC2100最新源码编译，负载太高了

### ISSUE THREAD

**Issue by gimgoo** [coolsnowwolf/lede#5173]
如题，用lede最新源码编译的AC2100，开了passwall，网易云，别的没开，平均负载太高了(10.18 , 4.86 , 3.96)，经常死机到后台都进不去。带机3台

**Comment by minlang112** [comment]
top 看下哪个进程的CPU占用率高

**Comment by caoyipeng2008** [comment]
解决了吗，我看关闭了，但是我这里刷了固件只开passwall负载就会很高，而且passwall开启状态不对
