### ISSUE TITLE
网易云音乐解锁的golang版本

### ISSUE THREAD

**Issue by stvber** [coolsnowwolf/lede#5179]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
网易云音乐解锁的golang版本的证书会导致某些启用https网站的的证书劫持，比如it之家
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
x86_64 版本OpenWrt R20.7.7 / LuCI Master (git-20.191.36863-eee6bae)
A：

### (3) 详细日志

A：

**Comment by lovelyOK** [comment]
我使用golang版本，WIN客户端就会出现无法访问网络的现象，不知道哪里没有设置到位。

**Comment by Saxon-Sun** [comment]
bug已经很久了 我现在这个点打开it之家证书也被劫持到163music了 以前也遇到过 不知道什么原因 关了解锁网易云就好了  NodeJs也会这样

**Comment by ivybridgei** [comment]
it之家加载慢的原因终于找到了

**Comment by Saxon-Sun** [comment]
> it之家加载慢的原因终于找到了

什么原因？ 可以PR一下？

**Comment by ivybridgei** [comment]
> > it之家加载慢的原因终于找到了
> 
> 什么原因？ 可以PR一下？

我的意思是，最近一直感觉几个软件不对劲，还以为是宽带的问题，原来是因为网易云插件，关了插件就恢复了

**Comment by 404user** [comment]
豆瓣app iOS端 也会这样，还有汽车之家， 有时候微信朋友圈也会。。。

**Comment by SkyMonkya** [comment]
我也碰见了，百度百科图片全挂了。。知乎部分图片也是，IT之家一直这样
