### ISSUE TITLE
挂载无效，fstab无法使用

### ISSUE THREAD

**Issue by xiaoqingfengATGH** [coolsnowwolf/lede#5198]
尝试挂载新硬盘到/失败，经过检查发现block无法读取/etc/config/fstab的配置。

即使使用 block detect > /etc/config/fstab 生成的配置，路由重启后发现，系统日志仍旧会报错。

[    5.669249] block: attempting to load /etc/config/fstab
[    5.669571] block: unable to load configuration (fstab: Entry not found)
[    5.669631] block: no usable configuration

因为block没有读取到配置，所以fstab中所有配置都失效了。

**Comment by AmadeusGhost** [comment]
那其它配置还在吗？感觉好像是丢配置了

**Comment by xiaoqingfengATGH** [comment]
配置在，不过是block加载时因为出错，就不再读取了。所以无论怎么配置都没用。

看出错信息，貌似是luci问题？

**Comment by zoverdoser** [comment]
扩容overlay遇到了相同的问题

**Comment by coxde** [comment]
同扩容遇到这个问题

**Comment by NicodeSS** [comment]
扩容overlay遇到相同的问题+1，尝试更新block也无法解决

**Comment by chamhaw** [comment]
+1 我也遇到了相同的问题
