### ISSUE TITLE
Update Patch to kernel 5.7

### ISSUE THREAD

**Issue by micron10** [coolsnowwolf/lede#5199]
Hi please sync patch for kernel 5.7

**Comment by FusionPlmH** [comment]
do it by yourself ，stuxxx

**Comment by micron10** [comment]
i need your help  for 2-3 patch to fix bugs with new kernel
other is work fine

**Comment by FusionPlmH** [comment]
we dont want an upsteam version that contain lot of bug an unstable environment ， we aim to provide stable and high performance .

So please close the issue by yourself
