### ISSUE TITLE
r7800突然断电以后导致无法获取IP上网

### ISSUE THREAD

**Issue by ITdesk01** [coolsnowwolf/lede#5203]
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：宿舍突然断电以后，r7800无法获取IP上网，但接口已经ppoe拨号成功
![捕获](https://user-images.githubusercontent.com/38835844/88598332-aaaa0980-d09b-11ea-9269-13d58afac0c1.PNG)

### (2) 路由器型号和固件版本

A：
![捕获01](https://user-images.githubusercontent.com/38835844/88598227-69195e80-d09b-11ea-8b63-0c3a183fbbf0.PNG)

### (3) 详细日志

A：
[断电以后无法上网.zip](https://github.com/coolsnowwolf/lede/files/4984838/default.zip)

**Comment by minlang112** [comment]
尝试手工重启防火墙

**Comment by ITdesk01** [comment]
> 尝试手工重启防火墙

我恢复出厂了，然后恢复上一次的备份文件。现在继续测试了

**Comment by madcat0513** [comment]
求教如何显示cpu温度

**Comment by ITdesk01** [comment]
> 和我同款路由，求教如何显示cpu温度

参考我的脚本代码：https://github.com/openwrtcompileshell/OpenwrtCompileScript
