### ISSUE TITLE
rtl8812au无法启用ap

### ISSUE THREAD

**Issue by jianzhazhukao** [coolsnowwolf/lede#5205]
大神你好，我的设备是nanopi r2s，采用的固件是R2S-Minimal-2020-07-27-ROM。
我的无线网卡是腾达U12，采用rtl8812au。
发现其可以采用client模式，无法启用ap模式
若是尚不支持当我没说，要是bug建议修复。
感谢

**Comment by gyj1109** [comment]
内核原因尚不支持，如需使用请用FriendWrt版本。另外，建议至固件发布地址发布issue。LEDE官方并未支持R2S，R2S-Minimal-2020-07-27-ROM并非由官方编译。
