### ISSUE TITLE
xiaomi R3GV2编译完成之后没有factory固件

### ISSUE THREAD

**Issue by wokilp** [coolsnowwolf/lede#5208]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译完成之后没有factory固件

### (2) 路由器型号和固件版本

A：小米R3GV2

### (3) 详细日志

A：

**Comment by 1049066154** [comment]
R3G的版本没有Factory固件

**Comment by jw10126121** [comment]
小米R3Gv1，刷入不能使用，获取不到ip
