### ISSUE TITLE
编译的squashfs格式固件，重启配置恢复默认配置

### ISSUE THREAD

**Issue by jzhou404** [coolsnowwolf/lede#521]
编译的squashfs格式固件，配置好，运行正常。

一但重启，自己恢复默认配置，所有之前的配置均丢失。

ext4格式的固件一切正常

**Comment by hcym** [comment]
灵异事件，以前的ac58u也有过，刷img格式重启丢失所有配置。用的还是官方源不是lean的。最近似乎没碰到

**Comment by kuretru** [comment]
什么机器啊？我自己的WNDR4300也是这个情况，原因是编译后固件大小>分区空间的大小，把分区扩容后解决了
