### ISSUE TITLE
K2P 使用无线闭源驱动编译，能识别AR7010 USB网卡，但无法启用

### ISSUE THREAD

**Issue by yang1010x** [coolsnowwolf/lede#5211]
### (1) 具体问题

A：K2P 使用无线闭源驱动编译，能识别AR7010 USB网卡，但无法启用。

### (2) 路由器型号和固件版本

A：K2P OpenWrt R20.7.20

**Comment by acooler15** [comment]
安装ar7010的驱动了吗？
