### ISSUE TITLE
r2s新源码编译出固件无法获取ip地址

### ISSUE THREAD

**Issue by r1172464137** [coolsnowwolf/lede#5212]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
r2s设备使用新源码编译的出的固件开机无法获取到ip地址（lan）
### (1) 具体问题

A：make dirclean后重新编译了一次依然无法获取ip（lan）
，最后整个文件夹删了重新克隆了仓库编译还是无法获取
### (2) 路由器型号和固件版本

A：r2s

### (3) 详细日志

A：获取不到ip，手动获取也不行，没得日志

**Comment by asushugo** [comment]
你试试把WAN和LAN对调一下看看行不行，之前有人改正了接口 #5028

**Comment by shensven** [comment]
应验了嘤嘤嘤 https://github.com/coolsnowwolf/lede/commit/f6aacba030fd475c0ef8b3a705a41ceeadb59b40#commitcomment-40496574

**Comment by minlang112** [comment]
之前确实有个强迫症提交了对调接口的pull……

**Comment by r1172464137** [comment]
ok了
