### ISSUE TITLE
Turbo ACC 网络加速设置 DNS加速影响科学上网

### ISSUE THREAD

**Issue by MrVicent** [coolsnowwolf/lede#5213]
Turbo ACC 网络加速设置  DNS加速开了之后 科学上网速度变得非常慢  很多需要科学上网的网页直接打不开
能多次复现
环境是pve虚拟机 i350t4网卡直通 OpenWrt R20.7.20 luci-app-sfe

**Comment by minlang112** [comment]
DNS加速请填写国内上游，不要把四个8之类的境外DNS服务器填在里面

**Comment by 1049066154** [comment]
Turbo ACC跟科学上网是冲突的

**Comment by minlang112** [comment]
> Turbo ACC跟科学上网是冲突的

不冲突啊……用的好好的

**Comment by caicaicai21** [comment]
一般来说，luci-app-sfe 内的 DNS加速 是不会影响 SSP+ 的，因为 SSP+ DNS服务的端口是 5335，而DNS加速服务端口是 5333。
SSP+DNS定向是用dnsmasq规则实现的，如果影响SSP+，那一定是这个地方勾上了，尝试去掉勾选保存试试。
![image](https://user-images.githubusercontent.com/26214093/88884693-bb0fdf00-d269-11ea-8cac-487371c89baf.png)

**Comment by Dimitri2020007** [comment]
sfe dns加速填国内dns，dnsmasq选择忽略解析文件。ssr+使用pdnsd tcp解析，从列表中选国外dns也可以自定义（不会自定义dns的老实选列表）。
