### ISSUE TITLE
大雕你好，OpenWrt-18.06.1下，luci-app-zerotier “启用” 选项无效。

### ISSUE THREAD

**Issue by hzqim** [coolsnowwolf/lede#522]
必须通过 /etc/init.d/zerotier 命令来启停。
谢谢。

**Comment by fuqiang03** [comment]
OpenWrt-18.06 不光这个一个插件哦  部分插件都受18.06的luci影响

**Comment by hzqim** [comment]
@fuqiang03 是吗？
目前我只碰到这个luci有问题。

**Comment by fuqiang03** [comment]
@hzqim 插件安装的太少了，像我这样就可以了
![tim 20180830194404](https://user-images.githubusercontent.com/26851715/44849610-2dc14b80-ac4a-11e8-88ca-e43620b0907b.png)
![tim 20180830194437](https://user-images.githubusercontent.com/26851715/44849612-2e59e200-ac4a-11e8-99a6-96e3a1c049e4.png)
![tim 20180830194449](https://user-images.githubusercontent.com/26851715/44849613-2ef27880-ac4a-11e8-9ac4-60c016316e12.png)
![tim 20180830194458](https://user-images.githubusercontent.com/26851715/44849614-2ef27880-ac4a-11e8-9411-4d407ae486b4.png)

**Comment by arfaWong** [comment]
@fuqiang03 你图里面的光猫访问插件是哪个，可以分享下吗？

**Comment by fuqiang03** [comment]
@arfaWong 
https://github.com/openwrt-develop/openwrt/tree/master/package/mypackages/luci-app-modem-access
