### ISSUE TITLE
研发请求：服务器节点复制与分享功能

### ISSUE THREAD

**Issue by stonemate** [coolsnowwolf/lede#5223]
1. 希望服务器节点可以复制，以便快速修改与添加
2. 希望服务器节点可以显示二维码，以便手机可以扫描添加
3. 服务器节点列表可以导出成ssr链接以便发送給其他人一键添加（适合没有订阅地址的情况下共享）

**Comment by Aes64X** [comment]
出门南北转找项目经理等报价。

**Comment by martin0607** [comment]
一个路由器插件而已。完整功能用PC客户端去。

**Comment by dingpengyu** [comment]
> 1. 希望服务器节点可以复制，以便快速修改与添加
> 2. 希望服务器节点可以显示二维码，以便手机可以扫描添加
> 3. 服务器节点列表可以导出成ssr链接以便发送給其他人一键添加（适合没有订阅地址的情况下共享）
推荐看一下ISSUE_TEMPLATE在发issues

**Comment by lanfenglin** [comment]
没必要

**Comment by caicaicai21** [comment]
这些操作，你服务提供商的网页上没有提供??

**Comment by BGzErol** [comment]
这些用客户端来整不就好了
