### ISSUE TITLE
统计插件 /cgi-bin/luci/admin/statistics/graph 出错

### ISSUE THREAD

**Issue by klever1988** [coolsnowwolf/lede#5225]
![image](https://user-images.githubusercontent.com/56048681/88880090-7599e480-d25e-11ea-827a-792489e83bc6.png)

**Comment by goldkeyber112** [comment]
主题footer权限问题，赋予你用的主题footer权限就好了。

**Comment by klever1988** [comment]
> 主题footer权限问题，赋予你用的主题footer权限就好了。

![image](https://user-images.githubusercontent.com/56048681/88919703-2a9fc180-d29e-11ea-9107-546e35820deb.png)

一样的呀

**Comment by goldkeyber112** [comment]
> > 主题footer权限问题，赋予你用的主题footer权限就好了。
> 
> ![image](https://user-images.githubusercontent.com/56048681/88919703-2a9fc180-d29e-11ea-9107-546e35820deb.png)
> 
> 一样的呀

chmod +x /usr/lib/lua/luci/view/themes/argon/footer.htm

**Comment by goldkeyber112** [comment]
> > > 主题footer权限问题，赋予你用的主题footer权限就好了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56048681/88919703-2a9fc180-d29e-11ea-9107-546e35820deb.png)
> > 一样的呀
> 
> chmod +x /usr/lib/lua/luci/view/themes/argon/footer.htm

单独加footer的权限可能还有问题,如果有
你直接
chmod -R +x /usr/lib/lua/luci/view/themes/argon

**Comment by klever1988** [comment]
这是argon主题代码的错误，作者已经修正

https://github.com/jerrykuku/luci-theme-argon/commit/1d0c40c85c7a3c4673ea45bfb23383d4ac6d6d67#diff-4be01be5457439e9191946ae431eef02
