### ISSUE TITLE
lede 5.4 内核 ，能用在k3路由器上吗？

### ISSUE THREAD

**Issue by pasu0607** [coolsnowwolf/lede#5229]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by mysteryman2045** [comment]
lede/target/linux/bcm53xx/Makefile里 “KERNEL_PATCHVER:=4.19  KERNEL_TESTING_PATCHVER:=5.4” 可以自己在make menuconfig时 Global build settings   ---> 选上Use the testing kernel version 试一试

**Comment by qiangwushuang** [comment]
@pasu0607 请问你试了吗？有没有问题？

**Comment by pasu0607** [comment]
@qiangwushuang 修改内核后编译了以下，能通过，但是固件还没有更新刷到路由器，待测试，应该没有什么问题。

**Comment by wclmgcd** [comment]
> 
> 
> 已经刷入，暂时没有发现问题。

请问一下，用大雕的源码编译，k3screenctrl选择了，但没有是怎么回事？
还有，编译时选择的是K3，但编译后还是一堆同芯片的其他固件
