### ISSUE TITLE
5.4内核启动阶段报错

### ISSUE THREAD

**Issue by KLGIT886** [coolsnowwolf/lede#5235]
[   63.454375] i915 0000:00:02.0: Failed to load DMC firmware i915/glk_dmc_ver1_04.bin. Disabling runtime power management.
[   63.466019] i915 0000:00:02.0: DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
4.19内核没有这个问题
偶尔会有突然死机的情况，不清楚是否和这个有没有关系

**Comment by hppin** [comment]
我的软路由也有一模一样的问题，期待大神能给个解答
