### ISSUE TITLE
taiwanese 太扯了！

### ISSUE THREAD

**Issue by m998001-0** [coolsnowwolf/lede#5252]
世界上不是只有 simplified Chinese ，traditional Chinese 。语言菜单中竟然有taiwanese，哪有什么 taiwanese 官方就是瞎搞！

**Comment by Aes64X** [comment]
> 世界上不是只有 simplified Chinese ，traditional Chinese 。语言菜单中竟然有taiwanese，哪有什么 taiwanese 官方就是瞎搞！

你在错误的位置进行了反馈，请到官方主线发pr或论坛讨论，这里发是没有用的。

**Comment by hcym** [comment]
吃饱了撑的，

**Comment by eallion** [comment]
简中又才几年历史。nt

**Comment by klever1988** [comment]
![image](https://user-images.githubusercontent.com/56048681/89459906-09f2d280-d79c-11ea-9ad9-3aab748e5189.png)
![image](https://user-images.githubusercontent.com/56048681/89459963-1b3bdf00-d79c-11ea-9db3-abb4847d63ea.png)
是traditional chinese无误啊，哪有taiwanese呢

**Comment by lariboo** [comment]
戳中了粉红蛆的G点，打碎了它们的玻璃心。

**Comment by gbaoye** [comment]
咋不用甲骨文

**Comment by yiguihai** [comment]
你随便去提，等下我就给你改回去😂
