### ISSUE TITLE
能否支持 通讯软件 例如WhatsApp Skype 全局代理

### ISSUE THREAD

**Issue by jerryrat** [coolsnowwolf/lede#5257]
1、如题，部分通讯软件无论是 GFW 还是 IP 模式下 都出现 只能发信息 不能发图片、视频、附件的问题

2、以WhatsApp 为例  https://mmh.whatsapp.net/  和 web.WhatsApp.com 以及 WhatsApp.com 经常解析出错，只能在 全局模式下 可以正常 工作

3、多平台、多终端、换DNS都试过，加入IP黑名单、域名黑名单 都不行

4、由L大的 Netflix 有感而发，能不能 针对 通讯软件 走单独的全局通道

万分感谢

**Comment by Aes64X** [comment]
> 1、如题，部分通讯软件无论是 GFW 还是 IP 模式下 都出现 只能发信息 不能发图片、视频、附件的问题
> 
> 2、以WhatsApp 为例 https://mmh.whatsapp.net/ 和 web.WhatsApp.com 以及 WhatsApp.com 经常解析出错，只能在 全局模式下 可以正常 工作
> 
> 3、多平台、多终端、换DNS都试过，加入IP黑名单、域名黑名单 都不行
> 
> 4、由L大的 Netflix 有感而发，能不能 针对 通讯软件 走单独的全局通道
> 
> 万分感谢

您在一个错误的位置进行了反馈，请您移步正确的项目。

**Comment by ldsj007** [comment]
我也遇到了
