### ISSUE TITLE
最新版本DW33D 编译失败

### ISSUE THREAD

**Issue by iceAngle** [coolsnowwolf/lede#5267]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：最新版本源码编译DW33D固件无法生成squashfs-sysupgrade.bin文件

### (2) 路由器型号和固件版本

A：DW33D

### (3) 详细日志

A：

**Comment by Aes64X** [comment]
换机器吧

**Comment by AmadeusGhost** [comment]
建议先换机子吧，我有一台 dw33d 放学校了，只能等回学校再测了

**Comment by wifiway520** [comment]
我的也是失败，不管用lede还是openwrt得仓库要么报错，要么不出固件

**Comment by coolsnowwolf** [comment]
这个机器内核分区为极小的 1.375MB，绝对不能超过这个数，很难再支持了
