### ISSUE TITLE
最近源码，经常出现以下问题

### ISSUE THREAD

**Issue by andyhang1980** [coolsnowwolf/lede#5268]
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libjpeg-turbo', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libjpeg-turbo', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg-turbo', which does not exist

**Comment by wx611975** [comment]
同样的问题

**Comment by minlang112** [comment]
善用搜索功能
https://github.com/coolsnowwolf/lede/issues/5238
