### ISSUE TITLE
编译出现问题

### ISSUE THREAD

**Issue by andyhang1980** [coolsnowwolf/lede#5271]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
ARNING: Makefile 'package/lean/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/lean/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a build dependency on 'libev', which does not exist
WARNING: Makefile 'package/feeds/telephony/sipgrep/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/sngrep/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/spandsp/Makefile' has a dependency on 'libtiff', which does not exist

**Comment by WisdomKwan** [comment]
我的问题和你不一样，不过也是组件缺失的问题：

日志：
```
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libjpeg-turbo', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libjpeg-turbo', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a build dependency on 'libjpeg-turbo', which does not exist
```
