### ISSUE TITLE
求大佬们推荐个能够替换helloworld的插件.

### ISSUE THREAD

**Issue by joesdu** [coolsnowwolf/lede#5275]
我的配置如下.但是感觉所有流量还是走了代理.内地网络有点慢.
![image](https://user-images.githubusercontent.com/13188169/89537798-67366480-d82c-11ea-936a-d50b65269d1f.png)

**Comment by goldkeyber112** [comment]
请不要把这里当贴吧聊天，另外"感觉"是什么定义，有没有走代理你测试下不就知道了。

**Comment by joesdu** [comment]
> 请不要把这里当贴吧聊天，另外"感觉"是什么定义，有没有走代理你测试下不就知道了。

可能是联通的问题，关掉也慢的一匹，MMP😂
