### ISSUE TITLE
您当前服务器不支持PATH_INFO模式

### ISSUE THREAD

**Issue by Gokou-Ruri** [coolsnowwolf/lede#5281]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
#4813 

### (1) 具体问题

A：在Luci上设置好可道云，更新版本成功后进入可道云，配置WebDAV插件的时候弹出提示。用的Github Actions编译的，源码是最新的，config也是git pull以后全新创建的。
![image](https://user-images.githubusercontent.com/26711804/89562519-a8d70780-d84c-11ea-8f4c-2aa5fcc9e1d0.png)
![image](https://user-images.githubusercontent.com/26711804/89563456-0cae0000-d84e-11ea-8c64-a7f8d681ce0b.png)

### (2) 路由器型号和固件版本

| 主机型号 |	Newifi-D2 |
| ------------ | ------------ |
| 架构	| MediaTek MT7621 ver:1 eco:3 x 4 |
| 固件版本 |	OpenWrt R20.7.20 / LuCI Master (git-20.191.36863-eee6bae) |
| 内核版本 |	5.4.51 |

### (3) 详细日志

A：
| 存储设备路径 | /mnt/sda1/ |
| :------------ | :------------ |
| 项目存放目录 | /mnt/sda1/kodbox |

```
#cat /tmp/etc/kodexplorer/nginx.conf

user root root;
worker_processes  1;
pid /var/run/nginx_kodexplorer.pid;
events {
    worker_connections  1024;
}
http {
    include /etc/nginx/mime.types;
    sendfile on;
    keepalive_timeout 65;
    server {
        listen 8080;
        listen [::]:8080;
        server_name  localhost;
        location / {
            root /mnt/sda1/kodbox;
            index index.html index.htm index.php;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        location ~ \.php$ {
            root /mnt/sda1/kodbox;
            try_files $uri = 404; # PHP 文件不存在返回404
            fastcgi_pass unix:/var/run/php7-fpm.sock; # 通过 Unix 套接字执行 PHP
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # 修复 Nginx fastcgi 漏洞
            include /etc/nginx/fastcgi_params;
        }
    }
}

```

**Comment by EnnawYang** [comment]
https://github.com/xiaorouji/openwrt-package/tree/master/lienol/luci-app-kodexplorer 替换下即可

**Comment by Gokou-Ruri** [comment]
> https://github.com/xiaorouji/openwrt-package/tree/master/lienol/luci-app-kodexplorer 替换下即可
> [xiaorouji/openwrt-package#453](https://github.com/xiaorouji/openwrt-package/issues/453)

谢谢大佬！请问这个MIPS路由器能用吗？是不是编译出ipk直接覆盖安装就行？

**Comment by Gokou-Ruri** [comment]
> https://github.com/xiaorouji/openwrt-package/tree/master/lienol/luci-app-kodexplorer 替换下即可
> [xiaorouji/openwrt-package#453](https://github.com/xiaorouji/openwrt-package/issues/453)

谢谢大佬，替换源码编译安装后可以用了，不过不能上传，只能下载，还是不用kodbox了。
