### ISSUE TITLE
树莓派4B新建网卡

### ISSUE THREAD

**Issue by areny7** [coolsnowwolf/lede#5285]
问题:树莓派4B新建网卡后重启系统 网卡会不见，设置的passwall的配置也没了，ssh秘钥也变了

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述

就像重启之后恢复出厂设置了

A：

### (2) 路由器型号和固件版本

A：树莓派4B

### (3) 详细日志

A：重启之后无日志

**Comment by SuLingGG** [comment]
大概率是 SD 卡的问题。尝试在 /root 下新建空文件：

```
touch /root/test.txt 
```

如果返回包含 "Read Only" 的提示说明 SD 卡有问题，建议按以下步骤操作：

1. 将 SD 卡插入电脑，使用 DiskGenius 或者 PartitionGuru 或类似的磁盘管理工具删除 SD 卡中的所有分区；
2. 在 SD 卡中新建一个 Fat32 分区，保存更改并格式化。此时 SD 卡便还原为出厂状态；
3. 使用 Win32 Disk Imager 或者 Etcher 再次将固件写入 SD 卡。

如果以上操作没能解决，建议更换 SD 卡再试。
