### ISSUE TITLE
警告：Makefile‘Package/feed/phone/freeswitc/makefile’依赖于“libjpeg-turbo”，而该依赖于不存在的“libjpeg-turbo”。

### ISSUE THREAD

**Issue by wwz09** [coolsnowwolf/lede#5286]
警告：Makefile‘Package/feed/phone/freeswitc/makefile’依赖于“libjpeg-turbo”，而该依赖于不存在的“libjpeg-turbo”。

**Comment by shanhai2333** [comment]
+1

**Comment by hv54** [comment]
+1

**Comment by hxlls** [comment]
警告而已,又不是错误,有这么纠结么?

**Comment by jxph1123** [comment]
@AmadeusGhost PR好像没通过？

**Comment by Windy-Hill** [comment]
因为官方的telephony新添加了软件包freeswitch，依赖于新的lib库libjpeg-turbo，和大雕无关，你想消除就把官方的packages拉取下来，再单独install这个libjpeg-turbo。
feeds.conf.default添加src-git pkg2 https://git.openwrt.org/feed/packages.git
./scripts/feeds update -a
./scripts/feeds install -a -p 《每个源名称不包括pkg2》
./scripts/feeds install libjpeg-turbo
