### ISSUE TITLE
在使用GFW列表和国内IP段模式时，大概只为能维持几分钟，之后又会自动变为全局模式

### ISSUE THREAD

**Issue by zhanhao93** [coolsnowwolf/lede#5289]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
在使用GFW列表和国内IP段模式时，大概只为能维持几分钟，之后又会自动变为全局模式

Q：是否搜索了issue (使用 "" 选择)
没有类似的issue

### (1) 具体问题

在使用GFW列表和国内IP段模式时，大概只为能维持几分钟，之后又会自动变为全局模式（但是显示仍旧是GFW列表或国内IP段模式）。在更新完GFW列表和国内IP段list后，大概能够在几分钟内维持GFW列表和国内IP段模式，但是之后又会自动变为全局模式（但是显示仍旧是GFW列表或国内IP段模式）。

### (2) 路由器型号和固件版本

A：软路由，刷的openwrt，然后使用的ShadowSocksR Plus+

### (3) 详细日志

A：

**Comment by goldzy123** [comment]
同问题，用的release里的r20.4.8

**Comment by hcym** [comment]
没遇过，要么不行，要么么哒事

**Comment by blesswarrior** [comment]
我也遇到了，群晖日志里面DDNS一直在来回切换。

**Comment by jb892** [comment]
一样的问题，用的release里的r20.4.8
