### ISSUE TITLE
官方主线 bcm53xx 已经切换至 5.4 内核，希望大雕有空时能同步一下

### ISSUE THREAD

**Issue by Crazy365** [coolsnowwolf/lede#5291]

**Comment by Aes64X** [comment]
> _No description provided._

早就包含5.4了，自己动手改。这还要大雕专门update？？？

**Comment by Carrjiang** [comment]
> > _No description provided._
> 
> 早就包含5.4了，自己动手改。这还要大雕专门update？？？

求教如何切换

**Comment by mysteryman2045** [comment]
> > > _No description provided._
> > 
> > 
> > 早就包含5.4了，自己动手改。这还要大雕专门update？？？
> 
> 求教如何切换

Global build settings   ---> 
Use the testing kernel version
