### ISSUE TITLE
syncdial 这什么不加pppconnectcheck这个脚本

### ISSUE THREAD

**Issue by doumeki** [coolsnowwolf/lede#5296]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

01-dialcheck 这个脚本明明要调用这个pppconnectcheck,为什么没有考虑加入这个文件?
在没有这个文件时,mwan3 interfaces输出好像不同步实际拨号的. 如果断开一个macvlan几乎是再拨不上的.
我尝试过rufeng老大的这个脚本,在我的环境终始是断开了又拨号始终存在BUG,最终使用koolshare的这个脚本成功多拨.

**Comment by Henshufu** [comment]
原来是这个原因

**Comment by Lovest20018** [comment]
关注下，这一年多，单线双拨都很累，需要重启很多次。而以前，随便5拨都可以。
