### ISSUE TITLE
使用nginx反代后ttyd和实时监控无法显示

### ISSUE THREAD

**Issue by Rachel-Green** [coolsnowwolf/lede#5298]
使用nginx反代后ttyd和实时监控无法显示，不知道是不是缺了什么资源

**Comment by Rachel-Green** [comment]
location部分如下：
        location = / {
			return 302 http://$host/cgi-bin/luci/;
	   }
        location /cgi-bin/luci/ {
        		client_max_body_size 128m;
        		proxy_pass http://192.168.1.1:8080/cgi-bin/luci/;
        }
        location /luci-static/ {
			alias /www/luci-static/;
	   }

**Comment by ZeaKyX** [comment]
ttyd应该需要websocket的header
#https://github.com/tsl0922/ttyd/issues/268

**Comment by wushenghn** [comment]
ttyd是固定端口7680，nginx反代点ttyd浏览器会打开真实地址，location里要做重定向 ，再加个路径代理ttyd端口

**Comment by wushenghn** [comment]
netdata用的是9090端口 正常打开都是显示内容嵌套的，通过代理访问不到 ttyd和netdata的端口web自然不能显示了
