### ISSUE TITLE
单独编译ipk失败，求指点

### ISSUE THREAD

**Issue by bibifa** [coolsnowwolf/lede#53]
make menuconfig 选择M luci-app-adbyby-plus后
运行make package/lean/luci-adbyby-plus/compile V=99
出错，google半天不得其解，请大神指点
出错信息

make[1]: Entering directory '/home/daker/lede'
make[2]: Entering directory '/home/daker/lede/feeds/luci/modules/luci-base'
make[2]: Leaving directory '/home/daker/lede/feeds/luci/modules/luci-base'
make[2]: Entering directory '/home/daker/lede/package/libs/toolchain'
rm -rf /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc.installed /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc
mkdir -p /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc
install -d -m0755 /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc/lib /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc/usr/bin
cp -fpR /home/daker/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/lib/ld-musl-*.so* /home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/home/daker/lede/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl/lib/ld-musl-*.so*': No such file or directory
Makefile:618: recipe for target '/home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc.installed' failed
make[2]: *** [/home/daker/lede/build_dir/target-mips_24kc_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/home/daker/lede/package/libs/toolchain'
package/Makefile:109: recipe for target 'package/libs/toolchain/compile' failed
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/home/daker/lede'
/home/daker/lede/include/toplevel.mk:207: recipe for target 'package/lean/luci-app-adbyby-plus/compile' failed
make: *** [package/lean/luci-app-adbyby-plus/compile] Error 2

**Comment by coolsnowwolf** [comment]
先编译固件一次，生成 toolchain，才能做你这个操作
