### ISSUE TITLE
编译刷机正常，18.06 v2ray无法启动？

### ISSUE THREAD

**Issue by Lancenas** [coolsnowwolf/lede#530]
BusyBox v1.28.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 18.06-SNAPSHOT, r583-b8577d51
 -----------------------------------------------------

root@OpenWrt:~# /etc/init.d/v2raypro start
WARNING: V2Ray is disabled.
root@OpenWrt:~#

**Comment by lyin888** [comment]
lua-cjson 依赖包有没有安装

**Comment by Lancenas** [comment]
lua-cjson安装了，ss禁用了

**Comment by lyin888** [comment]
系统-启动项 重启 v2ray  试试

**Comment by Lancenas** [comment]
重启没用，另外守护日志没信息

**Comment by lyin888** [comment]
估计编译不完整

**Comment by honnbin** [comment]
除了lua-cjson，还要选择luci-filetransfer什么的

**Comment by Lancenas** [comment]
支持包都安装了，感觉是权限问题，终端启动提示非法引导，没发现怎么解决

**Comment by lyin888** [comment]
你路由型号，CPU型号，应该是你v2ray包编译不完整

**Comment by lyin888** [comment]
![_20180902155758](https://user-images.githubusercontent.com/3062241/44953534-01ffc900-aec9-11e8-9d99-96af0ca048b5.png)

路由 水星MW4530R ，CPU AR9344 
MIPS CPU 编译的时候开启fpu浮点
还有等等暂时记不起来了

**Comment by lyin888** [comment]
v2ray_v3.26_mips_24kc.ipk
完整包有 8.22 MB (8,621,448 字节)

**Comment by XavierPENROSE** [comment]
楼主问题解决了吗
