### ISSUE TITLE
编译正常但无线无法使用

### ISSUE THREAD

**Issue by xxp2277** [coolsnowwolf/lede#5300]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
在https://github.com/coolsnowwolf/lede/pull/5295 合并后拉取代码更新，正常编译结束。首次保留配置刷机后无线无法启动（登录luci界面发现无线所有选项不可用，删除/etc/config/wireless后luci界面的无线菜单不见）；不保留配置刷机启动后也看不见无线菜单（断电重启路由器后依旧无法看见）。
Q：是否搜索了issue (使用 "x" 选择)
* [√  ] 类似的issue
#5293 
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：ar71xx平台，WNDR3800，2020-08-09代码

### (3) 详细日志

A：正常编译日志见https://github.com/xxp2277/WNDR3800/runs/963335020?check_suite_focus=true

**Comment by panther706** [comment]
同样问题

**Comment by AmadeusGhost** [comment]
日志指的是系统启动后的内核日志😂

**Comment by panther706** [comment]
> 日志指的是系统启动后的内核日志😂

[    0.000000] Linux version 4.14.187 (pwh@pwh-machine) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r2843-85808a075)) #0 Sun Aug 9 07:47:50 2020
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001974c (MIPS 74Kc)
[    0.000000] SoC: Atheros AR9344 rev 2
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 08000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] On node 0 totalpages: 32768
[    0.000000] free_area_init_node: node 0, pgdat 805adcc0, node_mem_map 81000020
[    0.000000]   Normal zone: 288 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 32768 pages, LIFO batch:7
[    0.000000] random: get_random_bytes called from start_kernel+0x98/0x4a4 with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line:  board=WNDR4300 console=ttyS0,115200 mtdparts=ar934x-nfc:256k(u-boot)ro,256k(u-boot-env)ro,256k(caldata)ro,512k(pot),2048k(language),512k(config),3072k(traffic_meter),2048k(kernel),121856k(ubi),123904k@0x6c0000(firmware),256k(caldata_backup),-(reserved) rootfstype=squashfs noinitrd
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 123528K/131072K available (4309K kernel code, 182K rwdata, 944K rodata, 188K init, 209K bss, 7544K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] Clocks: CPU:560.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:40.000MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6825930166 ns
[    0.000010] sched_clock: 32 bits at 280MHz, resolution 3ns, wraps every 7669584382ns
[    0.008312] Calibrating delay loop... 278.93 BogoMIPS (lpj=1394688)
[    0.084943] pid_max: default: 32768 minimum: 301
[    0.090139] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.097207] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.107753] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.118271] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.125391] NET: Registered protocol family 16
[    0.131527] MIPS: machine is NETGEAR WNDR4300
[    0.136378] ar71xx: using random MAC address for eth0
[    0.394160] clocksource: Switched to clocksource MIPS
[    0.400803] NET: Registered protocol family 2
[    0.406311] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.413739] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.420564] TCP: Hash tables configured (established 1024 bind 1024)
[    0.427487] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.433720] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.440721] NET: Registered protocol family 1
[    0.445433] PCI: CLS 0 bytes, default 32
[    0.450820] Crashlog allocated RAM at address 0x3f00000
[    0.457982] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.471176] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.477436] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.502191] io scheduler noop registered
[    0.506422] io scheduler deadline registered (default)
[    0.512253] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.519454] console [ttyS0] disabled
[    0.543338] serial8250.0: ttyS0 at MMIO 0x18020000 (irq = 11, base_baud = 2500000) is a 16550A
[    0.552538] console [ttyS0] enabled
[    0.559966] bootconsole [early0] disabled
[    0.572936] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xf1
[    0.579439] nand: Micron NAND 128MiB 3,3V 8-bit
[    0.584042] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.591775] Scanning device for bad blocks
[    0.599864] random: fast init done
[    0.683630] mtd: ar934x-nfc: skipping zero sized partition
[    0.689226] 11 cmdlinepart partitions found on MTD device ar934x-nfc
[    0.695680] Creating 11 MTD partitions on "ar934x-nfc":
[    0.700992] 0x000000000000-0x000000040000 : "u-boot"
[    0.707508] 0x000000040000-0x000000080000 : "u-boot-env"
[    0.715252] 0x000000080000-0x0000000c0000 : "caldata"
[    0.721875] 0x0000000c0000-0x000000140000 : "pot"
[    0.729011] 0x000000140000-0x000000340000 : "language"
[    0.735745] 0x000000340000-0x0000003c0000 : "config"
[    0.743073] 0x0000003c0000-0x0000006c0000 : "traffic_meter"
[    0.750288] 0x0000006c0000-0x0000008c0000 : "kernel"
[    0.757675] 0x0000008c0000-0x000007fc0000 : "ubi"
[    0.764623] 0x0000006c0000-0x000007fc0000 : "firmware"
[    2.113200] random: crng init done
[    2.494958] 0x000007fc0000-0x000008000000 : "caldata_backup"
[    2.503336] libphy: Fixed MDIO Bus: probed
[    2.512903] switch0: Atheros AR8327 rev. 4 switch registered on ag71xx-mdio.0
[    3.188433] libphy: ag71xx_mdio: probed
[    3.815516] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.0:00 [uid=004dd034, driver=Atheros AR8216/AR8236/AR8316]
[    3.826915] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode: rgmii
[    3.835678] NET: Registered protocol family 10
[    3.846193] Segment Routing with IPv6
[    3.850022] NET: Registered protocol family 17
[    3.855272] 8021q: 802.1Q VLAN Support v1.8
[    3.863433] UBI: auto-attach mtd8
[    3.866877] ubi0: attaching mtd8
[    4.041006] UBI: EOF marker found, PEBs from 143 will be erased
[    4.047962] ubi0: scanning is finished
[    4.083330] ubi0: volume 1 ("rootfs_data") re-sized from 9 to 787 LEBs
[    4.091000] ubi0: attached mtd8 (name "ubi", size 119 MiB)
[    4.096633] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    4.103609] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    4.110508] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    4.117581] ubi0: good PEBs: 952, bad PEBs: 0, corrupted PEBs: 0
[    4.123673] ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
[    4.131012] ubi0: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 1667833899
[    4.140285] ubi0: available PEBs: 0, total reserved PEBs: 952, PEBs reserved for bad PEB handling: 20
[    4.149702] ubi0: background thread "ubi_bgt0d" started, PID 343
[    4.157513] block ubiblock0_0: created from ubi0:0(rootfs)
[    4.163090] ubiblock: device ubiblock0_0 (rootfs) set to be root filesystem
[    4.189045] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    4.197263] Freeing unused kernel memory: 188K
[    4.201779] This architecture does not have kernel memory protection.
[    4.892209] init: Console is alive
[    4.896978] init: - watchdog -
[    7.085772] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    7.356718] usbcore: registered new interface driver usbfs
[    7.362358] usbcore: registered new interface driver hub
[    7.367903] usbcore: registered new device driver usb
[    7.399264] ANTFS Module: Version 07.19-b41ba529
[    7.465013] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    7.486779] SCSI subsystem initialized
[    7.502620] ehci-platform: EHCI generic platform driver
[    7.508078] ehci-platform ehci-platform: EHCI Host Controller
[    7.513954] ehci-platform ehci-platform: new USB bus registered, assigned bus number 1
[    7.524101] ehci-platform ehci-platform: irq 3, io mem 0x1b000000
[    7.554226] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00
[    7.562521] hub 1-0:1.0: USB hub found
[    7.567346] hub 1-0:1.0: 1 port detected
[    7.581999] usbcore: registered new interface driver usb-storage
[    7.593828] usbcore: registered new interface driver uas
[    7.601042] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    7.610424] init: - preinit -
[    8.860820] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    9.935430] eth0: link up (1000Mbps/Full duplex)
[    9.940215] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   13.255767] mount_root: loading kmods from internal overlay
[   13.334802] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[   13.343295] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[   13.372891] print_req_error: I/O error, dev mtdblock0, sector 48
[   13.384592] print_req_error: I/O error, dev mtdblock0, sector 88
[   13.517363] print_req_error: I/O error, dev mtdblock4, sector 88
[   13.667189] UBIFS (ubi0:1): default file-system created
[   13.674004] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 454
[   13.877204] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[   13.885204] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   13.895275] UBIFS (ubi0:1): FS size: 98533376 bytes (93 MiB, 776 LEBs), journal size 4952064 bytes (4 MiB, 39 LEBs)
[   13.905887] UBIFS (ubi0:1): reserved for root: 4653974 bytes (4544 KiB)
[   13.912607] UBIFS (ubi0:1): media format: w4/r0 (latest is w5/r0), UUID A34E8319-182A-4A06-8B90-01BD0660A235, small LPT model
[   13.925602] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   13.932863] block: unable to load configuration (fstab: Entry not found)
[   13.939844] block: attempting to load /tmp/ubifs_cfg/etc/config/fstab
[   13.946624] block: unable to load configuration (fstab: Entry not found)
[   13.953527] block: attempting to load /etc/config/fstab
[   13.964830] block: unable to load configuration (fstab: Entry not found)
[   13.971724] block: no usable configuration
[   13.979597] UBIFS (ubi0:1): un-mount UBI device 0
[   13.984520] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" stops
[   13.996604] UBIFS (ubi0:1): background thread "ubifs_bgt0_1" started, PID 457
[   14.195332] UBIFS (ubi0:1): UBIFS: mounted UBI device 0, volume 1, name "rootfs_data"
[   14.203288] UBIFS (ubi0:1): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[   14.213474] UBIFS (ubi0:1): FS size: 98533376 bytes (93 MiB, 776 LEBs), journal size 4952064 bytes (4 MiB, 39 LEBs)
[   14.224188] UBIFS (ubi0:1): reserved for root: 4653974 bytes (4544 KiB)
[   14.231059] UBIFS (ubi0:1): media format: w4/r0 (latest is w5/r0), UUID A34E8319-182A-4A06-8B90-01BD0660A235, small LPT model
[   14.264305] print_req_error: I/O error, dev mtdblock0, sector 48
[   14.275955] print_req_error: I/O error, dev mtdblock0, sector 88
[   14.401396] print_req_error: I/O error, dev mtdblock4, sector 88
[   14.552061] block: attempting to load /tmp/ubifs_cfg/upper/etc/config/fstab
[   14.559371] block: unable to load configuration (fstab: Entry not found)
[   14.566465] block: attempting to load /tmp/ubifs_cfg/etc/config/fstab
[   14.573288] block: unable to load configuration (fstab: Entry not found)
[   14.580279] block: attempting to load /etc/config/fstab
[   14.585797] block: unable to load configuration (fstab: Entry not found)
[   14.592678] block: no usable configuration
[   14.598690] mount_root: overlay filesystem has not been fully initialized yet
[   14.606511] mount_root: switching to ubifs overlay
[   14.683893] urandom-seed: Seed file not found (/etc/urandom.seed)
[   14.822005] eth0: link down
[   14.838666] procd: - early -
[   14.841709] procd: - watchdog -
[   15.469905] procd: - watchdog -
[   15.473429] procd: - ubus -
[   16.032888] procd: - init -
[   17.779013] kmodloader: loading kernel modules from /etc/modules.d/*
[   17.816820] NET: Registered protocol family 38
[   17.891654] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   17.955019] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   17.994536] nf_conntrack version 0.5.0 (2048 buckets, 8192 max)
[   18.076445] urngd: v1.0.2 started.
[   18.313624] Netfilter messages via NETLINK v0.30.
[   18.337929] ip_set: protocol 6
[   18.431725] cryptodev: driver 1.10 loaded.
[   18.448007] Mirror/redirect action on
[   18.485788] u32 classifier
[   18.488545]     input device check on
[   18.492256]     Actions configured
[   18.540812] Loading modules backported from Linux version v5.8-rc2-0-g48778464bb7d
[   18.548558] Backport generated by backports.git v5.8-rc2-1-0-g7a69429b
[   18.597085] ip_tables: (C) 2000-2006 Netfilter Core Team
[   19.004270] usbcore: registered new interface driver ums-alauda
[   19.026469] usbcore: registered new interface driver ums-cypress
[   19.046663] usbcore: registered new interface driver ums-datafab
[   19.056392] usbcore: registered new interface driver ums-freecom
[   19.076838] usbcore: registered new interface driver ums-isd200
[   19.096980] usbcore: registered new interface driver ums-jumpshot
[   19.116385] usbcore: registered new interface driver ums-karma
[   19.137471] usbcore: registered new interface driver ums-sddr09
[   19.156752] usbcore: registered new interface driver ums-sddr55
[   19.176722] usbcore: registered new interface driver ums-usbat
[   19.280875] xt_time: kernel timezone is -0000
[   19.423494] mac80211: Unknown symbol netif_receive_skb_list (err 0)
[   19.468907] PPP generic driver version 2.4.2
[   19.486027] PPP MPPE Compression module registered
[   19.505940] NET: Registered protocol family 24
[   19.637911] mac80211: Unknown symbol netif_receive_skb_list (err 0)
[   19.674811] kmodloader: 2 modules could not be probed
[   19.680061] kmodloader: dependency not loaded mac80211
[   19.694366] kmodloader: - ath9k - 1
[   19.698103] kmodloader: - mac80211 - 0
[   69.523016] print_req_error: I/O error, dev mtdblock0, sector 48
[   69.558254] print_req_error: I/O error, dev mtdblock0, sector 88
[   69.711163] print_req_error: I/O error, dev mtdblock4, sector 88
[   76.190052] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   76.216335] device eth0 entered promiscuous mode
[   76.221771] br-lan: port 1(eth0.1) entered blocking state
[   76.227330] br-lan: port 1(eth0.1) entered disabled state
[   76.233163] device eth0.1 entered promiscuous mode
[   76.264474] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   76.330139] IPv6: ADDRCONF(NETDEV_UP): eth0.2: link is not ready
[   77.216045] eth0: link up (1000Mbps/Full duplex)
[   77.220810] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   77.294329] br-lan: port 1(eth0.1) entered blocking state
[   77.299825] br-lan: port 1(eth0.1) entered forwarding state
[   77.305886] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.2: link becomes ready
[   77.464748] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   78.835606] fast-classifier (PBR safe v2.1.4a): starting up
[   78.841467] fast-classifier: registered

**Comment by rockey2020** [comment]
我也是 ar750s 型号

**Comment by qq635938204** [comment]
树莓派3、4也存在同样问题

**Comment by AmadeusGhost** [comment]
> 树莓派3、4也存在同样问题

你确定？？？这是 4.14，不是 5.4
> mac80211: Unknown symbol netif_receive_skb_list (err 0)

I'll backport this.

**Comment by biozzl** [comment]
我也是无线不可用呢， MW4530R, 老版本编译就没问题
