### ISSUE TITLE
关于开启IPv6后使用网飞的一些问题

### ISSUE THREAD

**Issue by LyricsGod** [coolsnowwolf/lede#5301]
在我开启梯子，观看网飞时发生了一些问题，经过我的查证得知是应为我开启了ipv6，但是代理仅能代理ipv4，所以造成打开网飞时发生重定向错误。在我禁用ipv6后可以正常观看，但是我需要ipv6来使用远程媒体服务器和文件服务器，请问大佬有没有办法能够仅屏蔽掉网飞的ipv6解析。我已在网络搜索了很多资料，但是关于屏蔽特定域名ipv6解析的文章很少，所以才来github求助，希望各位大佬能够帮我解答。

**Comment by coolsnowwolf** [comment]
禁用 IPv6 解析就好了

**Comment by LyricsGod** [comment]
禁用解析之后ddns会出问题

**Comment by helianling** [comment]
> 禁用解析之后ddns会出问题

不是在接口中禁用，是在Dnsmasq中禁用，不解析AAAA勾上，接口LAN中依然有公网IPV6地址，DDNS依然可以获取接口LAN中的IPV6公网地址的，所以并不影响DDNS使用。

**Comment by LyricsGod** [comment]
我用的dynv6，用他的脚本禁用了解析以后就不能上传了，不知道windows下有没有好用的ddns客户端，或者openwrt下能不能上传电脑的ipv6
