### ISSUE TITLE
luci ssr plus missing?

### ISSUE THREAD

**Issue by henrykey** [coolsnowwolf/lede#5310]
更新到最新版，发现有些luci应用没了, 需要专门获取吗？还是要返回前面的版？ 
谢谢！

**Comment by Aes64X** [comment]
> 更新到最新版，发现没有luci app ssr plus, 需要专门获取吗？还是要返回前面的版？
> 谢谢！

需要自己发现，勿在此处提出，不要给开发者召麻烦，也不要给自己找麻烦。
