### ISSUE TITLE
可以增加支持rk3399型号吗

### ISSUE THREAD

**Issue by keeno1982** [coolsnowwolf/lede#5314]
rk3399性能强劲，扩展接口也多，nanopi跟nanopc都不错的，大大有没有考虑添加这个型号呢

**Comment by Aes64X** [comment]
> rk3399性能强劲，扩展接口也多，nanopi跟nanopc都不错的，大大有没有考虑添加这个型号呢

出门东南转找项目部经理，谈需求，聊报价，合适的话您可以选择当场签合同或者约定时间。

**Comment by hcym** [comment]
官方有的话直接用，armv8不用wifi蓝牙基本通用，我的905，912，922都ok，就是不用无线蓝牙而已
