### ISSUE TITLE
How to make builds with a 4.14 kernel

### ISSUE THREAD

**Issue by 9000000** [coolsnowwolf/lede#5317]
By default make builds with the 5.4 kernel  
What should I do if I want to build 4.14 with a kernel?

**Comment by Promix953** [comment]
[https://github.com/coolsnowwolf/openwrt](url)

**Comment by mysteryman2045** [comment]
git checkout 20200416

**Comment by 9000000** [comment]
Thanks everyone

**Comment by klever1988** [comment]
It's not a good way to use outdated code or branch
the perfect ways is changing the values of KERNEL_PATCHVER and KERNEL_TESTING_PATCHVER from 5.4 to 4.19
located in https://github.com/coolsnowwolf/lede/blob/master/target/linux/x86/Makefile
but 4.14 is removed from this branch

if you insist 4.14 you will have to use https://github.com/coolsnowwolf/openwrt
and change the value in https://github.com/coolsnowwolf/openwrt/blob/lede-17.01/target/linux/x86/Makefile bacause the default kernel vesion is 4.19
