### ISSUE TITLE
Do closed source drivers support MU-MIMO?

### ISSUE THREAD

**Issue by 9000000** [coolsnowwolf/lede#5321]
Does the private source driver support MU-MIMO ?

**Comment by FusionPlmH** [comment]
mu-mimo just like a trash technology，useless at the moment

**Comment by AmadeusGhost** [comment]
Yes, it supported, but it's not very useful now.

**Comment by 9000000** [comment]
If the mu-mimo only supports 4 devices then it would be too useless, it would be a mistake to lose money to buy it.
