### ISSUE TITLE
网口上的灯怎么控制

### ISSUE THREAD

**Issue by wsltshh** [coolsnowwolf/lede#5329]
添加新型号支持，目前基本完成，想再做的完整一点
MT7621处理器
五口千兆
每个网口上有两个灯，右边的会亮会闪，左边的没反应
在breed里用命令和openwrt里用脚本都没找到控制这些灯的gpio，前面板的无线灯也不是gpio控制的
我甚至不知道这个灯有啥用，因为我收的二手，收到没注意什么就刷了，现在没有原厂固件可用
我应该怎么判断测试？

**Comment by wsltshh** [comment]
> > > 这个是协商速度灯吧,又没啥影响,另外边你把网线换4芯的应该能亮了
> > 
> > 
> > 二手收回来就刷了通用版padavan，不知道是啥灯也是没辙，也没原厂固件...
> > 我接了USB网卡，虽然是八芯，但是是百兆的，结果也是右边灯有反应，和千兆没区别。
> > 看了些双灯接口机型的dts，看不太懂...
> > 这些灯是没啥影响，就是想弄细致点，也多学点。
> 
> 我的小主机也很奇葩，主板网口只有黄灯亮，pcie扩展网口只有绿灯亮，还都是螃蟹8111的网卡.

x86我到觉得无所谓

**Comment by mysteryman2045** [comment]
Kernel modules---LED modules 下 有很多类型的gpio，我的NewifiD2，默认勾选了第一个，x86里是默认全空。

**Comment by wsltshh** [comment]
> Kernel modules---LED modules 下 有很多类型的gpio，我的NewifiD2，默认勾选了第一个，x86里是默认全空。

我想光选mod应该不管用，x86要广泛兼容，储存空间又无所谓，肯定得全选
