### ISSUE TITLE
WARNING: Makefile 'package/libs/libselinux/Makefile' has a build dependency on 'pcre/host', which does not exist

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#5332]
运行了./scripts/feeds update -a && ./scripts/feeds install -a
出现的一个警告，会有什么影响吗？

**Comment by Her0R0cket** [comment]
package源里有个旧的pcre,现在新pcre转到主源里了.我pull了大雕没合并packages源那边的,你可以自己去package/feeds/packages里把旧的pcre删了,然后删除源码根目录的tmp文件夹,重新运行make menuconfig.

**Comment by minlang112** [comment]
> package源里有个旧的pcre,现在新pcre转到主源里了.我pull了大雕没合并packages源那边的,你可以自己去package/feeds/packages里把旧的pcre删了,然后删除源码根目录的tmp文件夹,重新运行make menuconfig.

嗯，确实是的，删除旧的重新make menuconfig就好了

**Comment by lxwq** [comment]
./feeds/packages/libs/pcre需要删除吗?还是只删除./package/feeds/packages/pcre这个软链接

**Comment by minlang112** [comment]
> ./feeds/packages/libs/pcre需要删除吗?还是只删除./package/feeds/packages/pcre这个软链接

删除软链接就行了
