### ISSUE TITLE
iputils-tracerouter6和iputils-tracerpath6编译不出来

### ISSUE THREAD

**Issue by buildiffuse** [coolsnowwolf/lede#5334]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译时即使选中iputils-tracerouter6 和iputils-tracerpath6，最后还是没有生成

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hyird** [comment]
> > 你本地生成看看， 同步官方 那2个包没有了
> > 谢谢您回复，我用包含的19.07.3旧版本刚测试过了，反正现在ipv6虽能获取但是也使用不了诊断出错了，应该是恶心的运营商问题了。。。。

已经好了 issue可以关了
