### ISSUE TITLE
R2S固件编译成功,但用不了。

### ISSUE THREAD

**Issue by tl768** [coolsnowwolf/lede#5336]
R2S固件能编译成功，但固件卡刷后用不了。刷上有一个网卡灯不亮。也连接不上。默认配置编译也一样。有高手指点一二吗？

**Comment by AmadeusGhost** [comment]
先把 lan 口的网线插上再插电启动试试

**Comment by tl768** [comment]
> 先把 lan 口的网线插上再插电启动试试

网线各种插都试了，不灵呀。

**Comment by asushugo** [comment]
实测没问题

**Comment by mysteryman2045** [comment]
有可能后台IP搞错了。电脑设成自动分配IP，接LAN口看看分配到的啥网段的IP，就知道后台是啥IP了。

**Comment by lifetyper** [comment]
lean这个编译出来的，不带uboot和kernel这些吧，是不是还要额外打包一下才能直接写卡用？
