### ISSUE TITLE
D2550不能软重启，每次软重启就启不来，需要强制关机再启动，断电启动没事。

### ISSUE THREAD

**Issue by maoermin** [coolsnowwolf/lede#5337]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
BIOS 问题
