### ISSUE TITLE
make menuconfig中看不到kmod-shortcut-fe

### ISSUE THREAD

**Issue by Azreulo** [coolsnowwolf/lede#534]
过程是这样的，git clone openwrt，然后git checkout v18.06.1，git clone lean的openwrt，复制shortcut-fe和luci-app-sfe到openwrt/package目录下，feeds update，feeds install，使用openwrt代码make menuconfig，在Network Support下找不到shortcut的项。
而同样的操作，用lean的代码就会出现。

求教这如何解决。

**Comment by SouHong** [comment]
应该需要增加 SFE patch
