### ISSUE TITLE
关于ipv6

### ISSUE THREAD

**Issue by BGzErol** [coolsnowwolf/lede#5345]
想问问L大目前有让ssrp支持ipv6的想法吗
虽然ipv6目前国际路由还是爆炸的，但目前国内路由已经有所改善了，一直过滤v6解析也不是办法
不止L大对ssrp的v6支持是否有计划

**Comment by BGzErol** [comment]
> 打开AAAA解析实际上对扶墙影响不大，SSR里选择境外IP全部走代理，很少遇到仍然无法打开的网站……
看来你用的还是不够久，我这一打开Netflix啥的都走ipv6了，还有一些例如维基百科也会时不时链接被重置

**Comment by dingpengyu** [comment]
> > 打开AAAA解析实际上对扶墙影响不大，SSR里选择境外IP全部走代理，很少遇到仍然无法打开的网站……
> > 看来你用的还是不够久，我这一打开Netflix啥的都走ipv6了，还有一些例如维基百科也会时不时链接被重置

还有假如给wsl的 ubuntu更新系统，并且路由是解析了ipv6的话，这时候的地址就全部是ipv6了速度非常慢。

**Comment by klever1988** [comment]
> > > 打开AAAA解析实际上对扶墙影响不大，SSR里选择境外IP全部走代理，很少遇到仍然无法打开的网站……
> > > 看来你用的还是不够久，我这一打开Netflix啥的都走ipv6了，还有一些例如维基百科也会时不时链接被重置
> 
> 还有假如给wsl的 ubuntu更新系统，并且路由是解析了ipv6的话，这时候的地址就全部是ipv6了速度非常慢。

这跟翻墙有关系吗？ ubuntu镜像源本来就不在gfwlist里面，除非你用的是绕过。
能不能考虑，让dnsmasq只过滤gfwlist域名的ipv6解析。

**Comment by BGzErol** [comment]
> > > > 打开AAAA解析实际上对扶墙影响不大，SSR里选择境外IP全部走代理，很少遇到仍然无法打开的网站……
> > > > 看来你用的还是不够久，我这一打开Netflix啥的都走ipv6了，还有一些例如维基百科也会时不时链接被重置
> > 
> > 
> > 还有假如给wsl的 ubuntu更新系统，并且路由是解析了ipv6的话，这时候的地址就全部是ipv6了速度非常慢。
> 
> 这跟翻墙有关系吗？ ubuntu镜像源本来就不在gfwlist里面，除非你用的是绕过。
> 能不能考虑，让dnsmasq只过滤gfwlist域名的ipv6解析。

感觉让dnsmasq只过滤gfwlist域名的v6解析也挺不错，我一开始也想着能不能配合v6的国内ip表来过滤大陆外的v6地址，但苦于没学过编程不知道从何下手😂

**Comment by jelly0925** [comment]
> > > > > 打开AAAA解析实际上对扶墙影响不大，SSR里选择境外IP全部走代理，很少遇到仍然无法打开的网站……
> > > > > 看来你用的还是不够久，我这一打开Netflix啥的都走ipv6了，还有一些例如维基百科也会时不时链接被重置
> > > 
> > > 
> > > 还有假如给wsl的 ubuntu更新系统，并且路由是解析了ipv6的话，这时候的地址就全部是ipv6了速度非常慢。
> > 
> > 
> > 这跟翻墙有关系吗？ ubuntu镜像源本来就不在gfwlist里面，除非你用的是绕过。
> > 能不能考虑，让dnsmasq只过滤gfwlist域名的ipv6解析。
> 
> 感觉让dnsmasq只过滤gfwlist域名的v6解析也挺不错，我一开始也想着能不能配合v6的国内ip表来过滤大陆外的v6地址，但苦于没学过编程不知道从何下手😂

这个想法不错，希望大佬可以帮忙实现，现在我也是主路由开启ipv6,现在netflix默认解析到ipv6地址了，扶墙失败。
