### ISSUE TITLE
请问能否在ssrp的广告过滤中添加多个规则列表？

### ISSUE THREAD

**Issue by WROIATE** [coolsnowwolf/lede#5347]
希望能够自己添加多个规则，请问未来是否可能实现？如果可行就可以直接不使用类似adguardhome或者adbyby这类插件了

**Comment by jxph1123** [comment]
adbyby感觉没啥用。。

**Comment by Gokou-Ruri** [comment]
建议自己开个项目，把你需要的各规则合并就行了。如果都是DNSMASQ规则，可以直接头尾合并。
可以在路由器里安装git，创建计划任务，定时合并规则并git push，这样连电脑都不用开，ssr里只需要填你自己开的那个项目地址就行。

**Comment by WROIATE** [comment]
> 建议自己开个项目，把你需要的各规则合并就行了。如果都是DNSMASQ规则，可以直接头尾合并。
> 可以在路由器里安装git，创建计划任务，定时合并规则并git push，这样连电脑都不用开，ssr里只需要填你自己开的那个项目地址就行。

如果是不同类型的呢？比如想同时使用adguardhome和dnsmasq的规则

**Comment by xx10n31y** [comment]
不同类型就自己处理成dnsmasq的类型啊。。

**Comment by WROIATE** [comment]
> 不同类型就自己处理成dnsmasq的类型啊。。

额，这个对于有基础的来说是简单。不过还是直接添加链接比较方便平民，该issue只是问一下未来是否有可能支持或实现。

**Comment by coolsnowwolf** [comment]
有可能的，Adbyby Plus 就实现了，当时是不想把 SSRP 做的太复杂而已

**Comment by swxk521** [comment]
大佬看看做做看？，奈何没学过代码,只能一句卧槽，技术有限，提了几次都代码都有问题，被大佬否定了??,留下了没技术的眼泪

**Comment by LoogCP** [comment]
我觉得这个功能是刚需啊，
只有我adbyby打开之后就断网吗？不是WAN口断开那种，就是全局无法上网
