### ISSUE TITLE
请教一下咱们这个op的防火墙的端口转发规则添加以后多久才会生效？是立马生效的吗？

### ISSUE THREAD

**Issue by norikohxb** [coolsnowwolf/lede#5348]
请教一下咱们这个op的防火墙的端口转发规则添加以后多久才会生效？是立马生效的吗？
我感觉删除了之前添加的端口映射，但是连接好像还是在，
必须通过重启，好像才会改变
是不是添加一个新的端口映射要生效必须重启？
或者是删除一个，也是要重启才有效果？
还是要等固定的某个时间？
请问有没有人可以赐教一下，这个不是issue。有人告诉我了我马上close帖子，谢谢了

**Comment by 82kg** [comment]
我X86是立即生效的

**Comment by norikohxb** [comment]
那我估计是因为我的是nano pi r1s的缘故了，难怪不立即生效。

**Comment by FusionPlmH** [comment]
> 我X86是立即生效的

我x86 也不是马上有效

和这里类似问题
#5359
