### ISSUE TITLE
Adbyby plus 的plus模式是不是已经不起作用了？

### ISSUE THREAD

**Issue by kongfl888** [coolsnowwolf/lede#5355]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

1、在lazy规则中手动加入
```
|http://v.baidu.com/staticapi/videoAd.json
```
2、在plus过滤域名中加入（实际上这个已经存在了，不用添加）
```
v.baidu.com
```
3、启动项里重启adbyby
4、打开IE浏览器，先清理缓存记录，重启浏览器再打开上面videoAd.json地址（HTTP）
5、结果一切如故...

ps: 
你还可以使用``ipconfig /flushdns``清除下Windows的dns缓存（路由就不用了，因为重启adbyby时会做这个操作），甚至重连网络再测试
强调使用IE是因为，其他浏览器的去广告扩展可能带了这个规则

**Comment by kongfl888** [comment]
有没有大佬试验一波？

![QQ拼音截图20200825120631](https://user-images.githubusercontent.com/6991229/91122041-d5ec3c80-e6cb-11ea-8eef-0199e44d1fc9.jpg)

**Comment by lxwq** [comment]
这几天一个广告都过滤不了，不知道怎么回事

**Comment by swxk521** [comment]
哪位大神能把ssr里广告完善一下就好了

**Comment by yangabc123** [comment]
全局模式可以去，plus去不了

**Comment by hxlls** [comment]
实测生效,因为ADP 用的是DNS 去广告的方式,需要清除DNS缓存,不懂清除的可以重启你设备,还要重要的一点,全局模式,ADP 模式只有plus+里面的几个特定网站才会去广告
