### ISSUE TITLE
克隆最新源码编译时出问题!!!

### ISSUE THREAD

**Issue by forever2019** [coolsnowwolf/lede#5361]
克隆最新源码编译,在使用以下命令后,卡主不动了.
./scripts/feeds install -a

**Comment by martin0607** [comment]
你不update你install啥

**Comment by jxph1123** [comment]
WARNING: Makefile 'package/libs/libselinux/Makefile' has a build dependency on 'pcre/host', which does not exist
出现警告

**Comment by e703** [comment]
WARNING: Makefile 'package/libs/libselinux/Makefile' has a build dependency on 'pcre/host', which does not exist

但是编译正常，还没有刷机，先弄个虚拟机看看什么问题
