### ISSUE TITLE
nps设置页面不应该校验只能输入ip地址

### ISSUE THREAD

**Issue by gatalon** [coolsnowwolf/lede#5380]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：nps设置界面<服务器>如果输入域名就不能保存设置提示不是ip地址，通过修改nps配置文件可以设置服务器为域名正常使用。不应该限制只能输入ip地址，输入域名也可以正常使用的。

### (2) 路由器型号和固件版本

A：X86 OpenWrt R20.7.20 

### (3) 详细日志

A：无

**Comment by lifetyper** [comment]
/usr/lib/lua/luci/model/cbi/nps.lua

把第15行的“server.datatype="ipaddr"”删掉就行了。
