### ISSUE TITLE
关于使用UPNP会发生卡网的问题

### ISSUE THREAD

**Issue by DanielEcho** [coolsnowwolf/lede#5381]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
类似issue#5020
### (1) 具体问题

A：使用比特彗星添加upnp端口时会导致所有设备在几分钟内无法正常连接网络。具体表现为wifi信号正常，但无法连接到互联网，也无法打开路由器页面。

### (2) 路由器型号和固件版本

A：k2p 固件版本	OpenWrt R20.7.20 / LuCI Master (git-20.223.26773-d18ef13)

### (3) 详细日志

A：

**Comment by dolphinpaopao** [comment]
网卡/cpu性能/宽带连接数限制。设定比特彗星的每秒发送包个数到200-300左右可以解决这个问题。我是物理软路由，开启比特彗星的10s时间观察到整个宽带连接数会飙升到5W个，路由器性能不够肯定会卡。
