### ISSUE TITLE
netdata无限报错

### ISSUE THREAD

**Issue by MGBB** [coolsnowwolf/lede#5384]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题
netdata无限报错
A：

### (2) 路由器型号和固件版本
OpenWrt R20.8.27 / LuCI Master 
A：

### (3) 详细日志
Sat Aug 29 23:24:09 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:11 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:13 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:15 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:17 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:19 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:21 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:23 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:25 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:27 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:29 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:31 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Sat Aug 29 23:24:33 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm
A：

**Comment by hcym** [comment]
从来不编译这个玩意，x86上面都能看到cpu占用，mtk的估计容易卡死

**Comment by mysteryman2045** [comment]
你确定你“是否搜索了issue (使用 "x" 选择)[x ] 没有类似的issue”？？？

**Comment by cs-star** [comment]
删除netdata 相关软件包

**Comment by FusionPlmH** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [x ] 没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> netdata无限报错
> A：
> 
> ### (2) 路由器型号和固件版本
> OpenWrt R20.8.27 / LuCI Master
> A：
> 
> ### (3) 详细日志
> Sat Aug 29 23:24:09 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:11 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:13 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:15 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:17 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:19 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:21 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:23 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:25 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:27 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:29 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:31 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
> Sat Aug 29 23:24:33 2020 daemon.err netdata[3850]: PROCFILE: Cannot open file '/proc/sysvipc/shm
> A：

我也有一模一樣的
