### ISSUE TITLE
连上硬盘，系统启动不了

### ISSUE THREAD

**Issue by JerryBian** [coolsnowwolf/lede#5393]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：主机通过 USB 连接了机械硬盘，启动的时候一直卡在那里，导致系统没有启动成功。

### (2) 路由器型号和固件版本

A：j1900/OpenWrt R20.8.27 / LuCI Master (git-20.223.26773-d18ef13)

### (3) 详细日志

A：
![11](https://user-images.githubusercontent.com/1439095/91732067-4ae2d900-ebda-11ea-9bdf-3bd71b3a93de.png)

上图红框中的就是启动卡壳的那次日志，如果我把硬盘拔掉再启动，就会很顺利的开机运行。不知道什么原因。

**Comment by EnnawYang** [comment]
供电不足？ （猜的

**Comment by JerryBian** [comment]
> 供电不足？ （猜的

没错，你猜对了 👍
