### ISSUE TITLE
内网机器端口转发不出

### ISSUE THREAD

**Issue by snyzf** [coolsnowwolf/lede#5396]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
更新到最新的代码，默认选项编译。具体表现是路由本身的端口能出去公网。内网机器端口转发不出。

### (1) 具体问题

A：更新到最新的代码，默认选项编译。具体表现是路由本身的端口能出去公网。内网机器端口转发不出。

### (2) 路由器型号和固件版本

A：机器型号：newifi D2  
      固件版本：OpenWrt R20.8.27 / LuCI Master (git-20.223.26773-d18ef13)
--

### (3) 详细日志

A：

**Comment by mcucore** [comment]
近半年的防火墙端口转发，貌似TCP都没问题，TCP+UDP时不知为何3389会黑屏断开。

**Comment by snyzf** [comment]
实在查不出问题，好像也就是这几个月的。之前编译过4.14内核版本就没这问题。但现在不懂怎么回到旧版。旧版重新编译各种依赖缺失。

**Comment by VergilGao** [comment]
我现在在公司也ssh不上去家里内网的机器了，晚上回去调试一下看看……感觉也是遇到你这个问题了。

**Comment by snyzf** [comment]
我边着试了几个晚上都没有解决问题。后来编译隔壁Lienol我源码也是一样存在内网端口转发不出。放弃折腾了。

**Comment by snyzf** [comment]
找到临时解决办法。安装socat。
