### ISSUE TITLE
R7.4 版本引导问题

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#54]
编译的squashfs映像，第一次启动过程中，提示rootdisk overlay filesystem has not been formatted yet，然后卡住，需要按回车20次左右才能继续。

**Comment by coolsnowwolf** [comment]
别按，选择 pad image 即可

**Comment by flipphos** [comment]
我选中了pad iamge，出来的vmdk镜像仍然出现同楼主一样的错误。
我之前用Lean的17.01.2 R7.3.2转成vmdk后引导没有问题。

这个R7.4编译生成的squashfs.img反而无法用StarWind 转换成vmdk。
