### ISSUE TITLE
编译时一直有如下警告

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#5402]
WARNING: Makefile 'package/libs/libselinux/Makefile' has a build dependency on 'pcre/host', which does not exist

**Comment by lxwq** [comment]
好像出现有一段时间了,

**Comment by minlang112** [comment]
> 好像出现有一段时间了,

https://github.com/coolsnowwolf/lede/issues/5332

善用搜索

**Comment by pangfeng161** [comment]
碰到也是这样不知道怎样解决

**Comment by lxwq** [comment]
> 碰到也是这样不知道怎样解决
删除./package/feeds/packages/pcre这个软链接
