### ISSUE TITLE
5.4内核的WAN的IPV6的PD租约到期无法自动获取

### ISSUE THREAD

**Issue by abclai** [coolsnowwolf/lede#5405]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：5.4内核的WAN的IPV6的PD租约到期无法自动获取,只能重新拨号或重启，4.19内核好像不会能自动重新获取

### (2) 路由器型号和固件版本

A：X86 OpenWrt R20.8.27

### (3) 详细日志

A：

**Comment by Cathgao** [comment]
竟斗云用的4.19.PD被运营商换了之后依然不会自动更新，需要手动点连接

**Comment by minlang112** [comment]
这个应该是局端的问题，建议设置定时重启

**Comment by abclai** [comment]
> 这个应该是局端的问题，建议设置定时重启

这个暂时不清楚，之前4.19还是5.4内核第一个版本的时候有曾经27天不重启的IPV6的PD自动接续的，但是后面版本更新之后就不行，基本上时间到了IPV4还能自动接续，IPV6直接断掉

**Comment by fhbyljj** [comment]
那就设置一个定时  重新连接某一个端口
