### ISSUE TITLE
问个傻白话题，x86软路由应该买单核性能强的还是多核性能强的？

### ISSUE THREAD

**Issue by itfish92** [coolsnowwolf/lede#5413]
一直以为openwrt吃单核性能，多核性能可以忽略，
但是最近发现多核配置跑ssr plus比较单核跑要效率高些，是不是错觉？
软路由的话，到底单核性能重要还是多核性能重要些？

**Comment by 467815891a** [comment]
如果问你Windows系统是吃单核性能，还是吃多核性能呢？Windows做家用计算机是单核重要还是多核重要些？OP说白了也是一个支持多线程的操作系统，单核性能和多核性能在不同的应用上有不同的表现，选什么完全取决于你的钱包和需求

**Comment by itfish92** [comment]
> 如果问你Windows系统是吃单核性能，还是吃多核性能呢？Windows做家用计算机是单核重要还是多核重要些？OP说白了也是一个支持多线程的操作系统，单核性能和多核性能在不同的应用上有不同的表现，选什么完全取决于你的钱包和需求

多谢大佬指点，那还是综合性能来看吧。以前一直以为单核好就好
