### ISSUE TITLE
关于树莓派3B无法使用sysupgrade更新成功的问题

### ISSUE THREAD

**Issue by kid424** [coolsnowwolf/lede#5414]
Q：是否搜索了issue 
是，找到了 #4108 

### (1) 具体问题

A：树莓派3B修改配置后编译出sysupgrade固件，使用该固件保留配置升级后没有看到新加入的包。在找到的issue里看到这个[commit](https://github.com/coolsnowwolf/lede/commit/f892bcdf96e59ca3d19501fafc2dcd6a4e9ce318)应该是解决了这个问题，但是去查看最新的代码里对应的更改好像都被取消掉了。想问下是这个修改方式不对还是不小心覆盖了。

### (2) 路由器型号和固件版本

A：树莓派3B，版本是刚编译的，commit号7ce9641037b94732aae22df1d838773e215f5c50

### (3) 详细日志

A：确实不知道日志文件在哪里，在/var/log下面似乎没有。如果可以的话麻烦回复下我这个日志可以在哪个路径找到。

**Comment by AmadeusGhost** [comment]
大雕已经整个同步官方了，所以不再需要之前那样处理，日志的话应该得接 ttl 看吧

**Comment by kid424** [comment]
> 大雕已经整个同步官方了，所以不再需要之前那样处理，日志的话应该得接 ttl 看吧

感谢大佬回复，看了下稳定版的修改还在，我树莓派就用稳定版的好了
