### ISSUE TITLE
verysync插件的下载地址挂了

### ISSUE THREAD

**Issue by allok1985** [coolsnowwolf/lede#5419]
verysync插件的下载地址挂了
官方的自己的连接报错
http://releases-cdn.verysync.com/releases/v1.5.5/verysync-linux-amd64-V1.5.5.tar.qz
openwrt源404
https://sources.openwrt.org/verysync-linux-amd64-v1.5.5.tar.gz

**Comment by allok1985** [comment]
大佬  没合并进去啊

**Comment by EnnawYang** [comment]
您很急吗？  很急自己改下吧？
