### ISSUE TITLE
lan禁用ipv6分配长度会导致ipv4 ip也无法分配获取？

### ISSUE THREAD

**Issue by DoveKi** [coolsnowwolf/lede#5427]
为什么大雕固件在lan禁用ipv6分配长度 会导致ipv4 ip也无法获取 直接无法连上路由器只能重置路由
在官方op原版固件禁用ipv6分配长度没这个问题
主要不想看到lan分配ipv6地址 目前用不到ipv6看着烦 有没有全局禁用所有ipv6的方法 
![QQ截图20200907210145](https://user-images.githubusercontent.com/8667391/92390509-8dae2f00-f14d-11ea-826a-6b0208b085d9.png)

**Comment by hxlls** [comment]
实测没问题，可能是你其他编译进去的软件影响，自己排查下

**Comment by DoveKi** [comment]
> 实测没问题，可能是你其他编译进去的软件影响，自己排查下

排查不了 一改就断开连接了 ip无法获取连不上路由 只能重置出厂

**Comment by mjyhj** [comment]
> > 实测没问题，可能是你其他编译进去的软件影响，自己排查下
> 
> 排查不了 一改就断开连接了 ip无法获取连不上路由 只能重置出厂

其他设备呢？自己静态IP呢？

**Comment by lphgor** [comment]
试试在ssh里面用命令行修改呢，网页上修改可能会影响其他的参数
```
uci delete network.lan.ip6assign
uci commit network
/etc/init.d/network reload
```
