### ISSUE TITLE
麻烦给看看什么问题

### ISSUE THREAD

**Issue by ziqqqq** [coolsnowwolf/lede#543]
/home/zl/lede/build_dir/hostpkg/qemu-2.11.1/rules.mak:66: recipe for target 'util/memfd.o' failed
make[4]: *** [util/memfd.o] Error 1
make[4]: Leaving directory '/home/zl/lede/build_dir/hostpkg/qemu-2.11.1'
Makefile:140: recipe for target '/home/zl/lede/build_dir/hostpkg/qemu-2.11.1/.built' failed
make[3]: *** [/home/zl/lede/build_dir/hostpkg/qemu-2.11.1/.built] Error 2
make[3]: Leaving directory '/home/zl/lede/package/lean/qemu-userspace'
time: package/lean/qemu-userspace/host-compile#0.94#0.46#1.36
package/Makefile:107: recipe for target 'package/lean/qemu-userspace/host/compile' failed
make[2]: *** [package/lean/qemu-userspace/host/compile] Error 2
make[2]: Leaving directory '/home/zl/lede'
package/Makefile:103: recipe for target '/home/zl/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/zl/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zl/lede'
/home/zl/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
zl@zl-G41MT-S2:~/lede$

**Comment by taiziccf** [comment]
同样问题
