### ISSUE TITLE
docker容器Ping不通网关

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#5433]
docker建立了macvlan网络，可以正常访问外网，ping不通路由内网。

macvlan 192.168.2.1
openwrt 192.168.1.1
 请问怎么实现？

PS ：经过多天的测试，如果指定容器为192.168.1.X网段也是可以的，但是外网无法端口映射成功！
![1](https://user-images.githubusercontent.com/61616502/92552348-04a11000-f293-11ea-9340-3ca994249812.jpg)

**Comment by hyird** [comment]
macvlan就是这样 容器可以互通 通网
就是通不了宿主机
