### ISSUE TITLE
开了IPV6 解锁网易云经常卡住

### ISSUE THREAD

**Issue by mjyhj** [coolsnowwolf/lede#5434]
这玩意和IPV6有冲突，开了IPV6下歌下载进度条卡住不动。
有没大神LUCI上加个屏蔽网易云的

![微信图片_20200909160749](https://user-images.githubusercontent.com/22577418/92572179-ab4ad800-f2b6-11ea-8442-4a94148eb1a7.jpg)

**Comment by ZeaKyX** [comment]
曾经因为ipv6解锁都不成功，然后就关了
