### ISSUE TITLE
麻烦帮我看下这个编译报错

### ISSUE THREAD

**Issue by jtzgc** [coolsnowwolf/lede#5435]
之前编译都没问题，昨晚更新源码再编译就一直报这个错

![FCFD0B27-C5F0-4B68-B0E2-F3149FEC9EF6](https://user-images.githubusercontent.com/63477893/92614776-03053580-f2ef-11ea-8a26-7835348eb709.jpeg)

**Comment by lxwq** [comment]
我也卡在这,有文件下载不下来,naiveproxy 编译出错,

**Comment by AmadeusGhost** [comment]
缺了 curl 命令， `apt install curl`

**Comment by EnnawYang** [comment]
> 缺了 curl 命令， `apt install curl`

发现群里面不少人都少curl (

**Comment by pangfeng161** [comment]
这个月以来很多人编译出错

**Comment by lxwq** [comment]
curl: (28) Connection timed out after 20000 milliseconds
unzip:  cannot find or open /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip, /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip.zip or /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip.ZIP.
bash: ./gn/out/gn: No such file or directory
ninja: Entering directory `out/Release'
ninja: fatal: chdir to 'out/Release' - No such file or directory
make[3]: *** [Makefile:89: /home/zz/lean/build_dir/target-x86_64_musl/naiveproxy-85.0.4183.83-1/.built] Error 1
make[3]: Leaving directory '/home/zz/lean/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#1.38#0.55#153.12
make[2]: *** [package/Makefile:113: package/feeds/helloworld/naiveproxy/compile] Error 2
没有出国条件,如何下载gn???

**Comment by xtwz** [comment]
install curl  重样出来这个报错

**Comment by stztao** [comment]
> 缺了 curl 命令， `apt install curl`
装过还是依然这个错误，原来一直正常，更新9号的源码后就一直报这个错
