### ISSUE TITLE
无法取消 ddns-scripts

### ISSUE THREAD

**Issue by simonchan6688** [coolsnowwolf/lede#5436]
>反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 &quot;x&quot; 选择)
* [x] 没有类似的issue

## 2. 详细叙述
在luci里取消了此项
 < > luci-app-ddns......... LuCI Support for Dynamic DNS Client (ddns-scripts)      
但是编译固件后依然存在软件表里，在系统-软件包里能看到！
### (1) 具体问题
对于没有公网ip来说，没什么用且可能占用空间！

A：

**Comment by EnnawYang** [comment]
依赖取消了？ 这也算issue？

**Comment by Hey-Leo** [comment]
`ddns-scripts_aliyun`   `ddns-scripts_dnspod`这俩也是默认选上的，自己取消勾选

**Comment by Saxon-Sun** [comment]
ddns-scripts占50kb都不到

**Comment by yubanmeiqin9048** [comment]
提ISSUE之前能不能先上OP官方看看软件包包含依赖，谷歌浏览器都带翻译的

**Comment by coolsnowwolf** [comment]
这个体积不到 50kb，真没必要纠结
