### ISSUE TITLE
sfe和flowoffload 什么区别？

### ISSUE THREAD

**Issue by HUiTHEME** [coolsnowwolf/lede#5438]
最近编译了一次，发现 有一个 luci-app-sfe 和 luci-app-flowoffload 这2个之间什么区别啊？好像都是 Turbo ACC 网络加速设置 ？

**Comment by Fddh2012** [comment]
二选一，推荐用sfe

**Comment by Dimitri2020007** [comment]
sfe的
![86268222-0359-4923-AE76-9B2433D44F85](https://user-images.githubusercontent.com/69845732/93366008-272bbe00-f87d-11ea-8f5e-f33159b78567.png)

flowoffload的
![B33286E3-9266-47CC-A4B0-F43B0DA67790](https://user-images.githubusercontent.com/69845732/93366076-3c085180-f87d-11ea-94a6-d9b127e3bc12.png)

sfe有5个功能（桥接加速，ipv6加速，sfe加速）
flowoffload有4个功能（hwnat，flowoffload加速）
bbr,dns加速是两个都有的。

两个一起开没啥区别，就是多几个加速功能。
可以两个加速都编译进固件的。（x86可以这样子，别的就不知道了。）

**Comment by NagaseKouichi** [comment]
是不是flowoffload对MTK的7621A有硬件加速，sfe只是软件加速？
