### ISSUE TITLE
编译出错，系统是14.04

### ISSUE THREAD

**Issue by yyong201** [coolsnowwolf/lede#544]
checking pkg-config is at least version 0.9.0... yes
checking for protobuf >= 2.6.0... no
configure: error: Package requirements (protobuf >= 2.6.0) were not met:

No package 'protobuf' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make[3]: *** [/home/yangy/lede/build_dir/hostpkg/libprotobuf-c-v1.2.1/.configured] Error 1
make[3]: Leaving directory `/home/yangy/lede/feeds/packages/libs/protobuf-c'
time: package/feeds/packages/protobuf-c/host-compile#37.31#3.68#47.24
make[2]: *** [package/feeds/packages/protobuf-c/host/compile] Error 2

有哪位大侠知道问题出在哪？怎么解决？

**Comment by hcym** [comment]
尽量用18，麻烦少
