### ISSUE TITLE
建议将 curl 加入依赖列表

### ISSUE THREAD

**Issue by Pastechn** [coolsnowwolf/lede#5442]
自从加入了 Naive Proxy 之后 好多因为没有 curl 造成的编译失败 建议大佬把它加入依赖列表

**Comment by 9l** [comment]
什么系统会没有装 curl

**Comment by Pastechn** [comment]
Ubuntu 默认就没有 curl

**Comment by 9l** [comment]
好吧，虚拟机里重装了一下 ubuntu 18.04 和 20.04，18.04 确实没有 curl，20.04 是有 curl 的

**Comment by coolsnowwolf** [comment]
已加入
