### ISSUE TITLE
网易云解锁云解锁版本ip变动失效

### ISSUE THREAD

**Issue by ZeaKyX** [coolsnowwolf/lede#5444]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：云解锁至一个ddns解析的地址，两天变动一次ip，变了ip就失效了，应该是解锁使用iptables只能用ip的缘故，也许用ipset和dnsmasq可以解决？

### (2) 路由器型号和固件版本

A：Lenovo Y1 OpenWrt R20.8.27

### (3) 详细日志

A：无

**Comment by BecodReyes** [comment]
写个脚本定期获取ip更新防火墙就可以了

**Comment by ZeaKyX** [comment]
> 写个脚本定期获取ip更新防火墙就可以了

那不如重启解锁服务
ipset配合的话希望能无缝切换
