### ISSUE TITLE
12号更新，编译v2ray，无法启动v2ray

### ISSUE THREAD

**Issue by lllrrr** [coolsnowwolf/lede#545]
以前的版本不会，现在SSR是正常的，brook和v2ray都无法启动，配置好了也无法使用。期待大雕修复。

**Comment by hcym** [comment]
也是如此，以前的好像多改动几次总能正常，最近的死活不行，好在pc端可以。干脆放弃

**Comment by lllrrr** [comment]
神奇的是，我更新13号的，又编译了一下，又可以用了

**Comment by hcym** [comment]
我的都能启动，连不上，以前是免费的heroku，用了几个月被封号。现在是搬瓦工和v家的，ss和ssr都正常，就是v2不能用路由器。折腾中间还浪费了几个优质ip，唉，不折腾不折腾

**Comment by s0fx2** [comment]
我编译的时候选中v2ray，编译就过不去了，测试了几次

**Comment by hcym** [comment]
编译一直正常，这两天大佬更新频繁，等等再看看，看上去很多都是我期待已久的，泪流满面
