### ISSUE TITLE
DHCP 指定的DNS好像不工作，默认都走路由器了。

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#5457]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Hey-Leo** [comment]
防火墙自定义规则去掉这俩
`iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53`
`iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53`

**Comment by qqsir-dev** [comment]
> 防火墙自定义规则去掉这俩
> `iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53`
> `iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53`

多谢，长知识了，也解决问题了！
