### ISSUE TITLE
咨询下 阿里云DDNS 的 可以同时绑定多个域名吗？

### ISSUE THREAD

**Issue by hubodzyj** [coolsnowwolf/lede#5458]
现在很多引用都建议配置上 https  这样的话就需要 多个二级域名关联到 动态IP 请问要如何实现更新多个二级域名的ip呀。

**Comment by eallion** [comment]
可以。
但是尽量不要绑定 root 域名，有 Bug 。

点击`添加`一个域名后配置即可。理论上是可以绑定无数个。

![2020-09-18_12-03](https://user-images.githubusercontent.com/1698841/93554888-2131fc00-f9a7-11ea-9294-5d2a45fb8f1f.png)

**Comment by eallion** [comment]
可以。
但是尽量不要绑定 root 域名，有 Bug 。

点击`添加`一个域名后配置即可。理论上是可以绑定无数个。

![2020-09-18_12-25](https://user-images.githubusercontent.com/1698841/93555986-28a6d480-f9aa-11ea-8876-da83e11ea4a9.png)
