### ISSUE TITLE
newifi3 最新固件没有802.11r，请问是否支持？

### ISSUE THREAD

**Issue by LemoFire** [coolsnowwolf/lede#5461]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：newifi3 最新固件没有802.11r，请问是否支持？

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by XiaoliChan** [comment]
Please select wapd-openssl instead of wapd-basic.

**Comment by AmadeusGhost** [comment]
闭源驱动不支持，要 kvr 可以换开源驱动

**Comment by LemoFire** [comment]
> 闭源驱动不支持，要 kvr 可以换开源驱动
请问如何换开源驱动呢？

**Comment by LemoFire** [comment]
> 闭源驱动不支持，要 kvr 可以换开源驱动

请问如何换开源驱动呢？

**Comment by LemoFire** [comment]
> Please select wapd-openssl instead of wapd-basic.

Thank you for your help, but it's seemed that not working
