### ISSUE TITLE
transmission提示更新

### ISSUE THREAD

**Issue by PandaEgg** [coolsnowwolf/lede#5467]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A： transmission提示更新了，麻烦大佬更新一下

### (2) 路由器型号和固件版本

A：ALL

### (3) 详细日志

A：v1.6.1

**Comment by eallion** [comment]
自己提一个PR，还可以增加一个贡献值。
