### ISSUE TITLE
14.04 lts make V=99出错

### ISSUE THREAD

**Issue by chaihuo** [coolsnowwolf/lede#547]
报错1：
ar r liblzma.a ZLib.o LZMADecoder.o LZMAEncoder.o LZInWindow.o LZOutWindow.o RangeCoderBit.o InBuffer.o OutBuffer.o FileStreams.o Alloc.o C_FileIO.o CommandLineParser.o CRC.o StreamUtils.o String.o StringConvert.o StringToInt.o Vector.o 
ar: creating liblzma.a
ranlib liblzma.a
make[4]: Leaving directory `/home/bl/netgear/lede/build_dir/host/lzma-4.32/C/7zip/Compress/LZMA_Lib'
CFLAGS="-O2 -I/home/bl/netgear/lede/staging_dir/host/include " CPPFLAGS="-I/home/bl/netgear/lede/staging_dir/host/include " CXXFLAGS="" LDFLAGS="-L/home/bl/netgear/lede/staging_dir/host/lib " make -f makefile.gcc -C /home/bl/netgear/lede/build_dir/host/lzma-4.32/C/7zip/Compress/LZMA_Alone
make[4]: Entering directory `/home/bl/netgear/lede/build_dir/host/lzma-4.32/C/7zip/Compress/LZMA_Alone'
g++ -O2 -Wall -c -I ../../../ LzmaAlone.cpp
LzmaAlone.cpp: In function 'int main2(int, const char**)':
LzmaAlone.cpp:432:36: warning: format not a string literal and no format arguments [-Wformat-security]
         fprintf(stderr, kWriteError);
                                    ^
LzmaAlone.cpp:458:33: warning: format not a string literal and no format arguments [-Wformat-security]
       fprintf(stderr, kReadError);
                                 ^
LzmaAlone.cpp:463:33: warning: format not a string literal and no format arguments [-Wformat-security]
       fprintf(stderr, kReadError);
                                 ^
LzmaAlone.cpp:477:35: warning: format not a string literal and no format arguments [-Wformat-security]
         fprintf(stderr, kReadError);
                                   ^
LzmaAlone.cpp:482:35: warning: format not a string literal and no format arguments [-Wformat-security]
         fprintf(stderr, kReadError);
                                   ^
g++ -O2 -Wall -c -I ../../../ LzmaBench.cpp
In file included from ../LZMA/LZMADecoder.h:6:0,
                 from LzmaBench.cpp:12:
LzmaBench.cpp: In member function 'virtual ULONG CBenchmarkInStream::Release()':
../LZMA/../../../Common/MyCom.h:160:31: warning: deleting object of polymorphic class type 'CBenchmarkInStream' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
   return __m_RefCount; delete this; return 0; }
                               ^
../LZMA/../../../Common/MyCom.h:171:3: note: in expansion of macro 'MY_ADDREF_RELEASE'
   MY_ADDREF_RELEASE
   ^
LzmaBench.cpp:143:3: note: in expansion of macro 'MY_UNKNOWN_IMP'
   MY_UNKNOWN_IMP
报错2：
make[3]: Entering directory `/home/bl/netgear/lede/tools/b43-tools'
. /home/bl/netgear/lede/include/shell.sh; xzcat /home/bl/netgear/lede/dl/b43-tools.tar.xz | tar -C /home/bl/netgear/lede/build_dir/host/b43-tools/.. -xf -
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[3]: *** [/home/bl/netgear/lede/build_dir/host/b43-tools/.prepared725a28beddc720c721883b3ef2c9b4c7_6664517399ebbbc92a37c5bb081b5c53] Error 2
make[3]: Leaving directory `/home/bl/netgear/lede/tools/b43-tools'
time: tools/b43-tools/compile#0.05#0.02#0.14
make[2]: *** [tools/b43-tools/compile] Error 2
make[2]: Leaving directory `/home/bl/netgear/lede'
make[1]: *** [/home/bl/netgear/lede/staging_dir/target-mips_24kc_musl/stamp/.tools_compile_yyyyyyyynyyyyynyynnyyyyyyyyyyyyyyyyyyyynyynynyyyynnyy] Error 2
make[1]: Leaving directory `/home/bl/netgear/lede'
make: *** [world] Error 2

**Comment by kiddrepo** [comment]
使用`make -j1 V=s`重新编译来查看具体错误
