### ISSUE TITLE
咨询一下各位，如何发PR升级最新版的shadowsocks-libev

### ISSUE THREAD

**Issue by ricksuzade-maker** [coolsnowwolf/lede#5471]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：shadowsocks时隔近一年升级了最新版的shadowsocks-libev到最新的3.3.5版本，这是目前唯一还在升级的ss了，如何可以加入到最新的LEDE之中呢，咨询一下各位大佬。

**Comment by qianxu2001** [comment]
我已经提交了 pr，这个要去大雕 packages 仓库提交
