### ISSUE TITLE
日志报错

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#5474]
Wed Sep 16 16:16:17 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:17:10 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:17:10 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:17:18 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:18:17 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:18:36 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:19:18 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:19:50 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:20:19 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:20:33 2020 kern.info kernel: [249408.672369] sh (14257): drop_caches: 3
Wed Sep 16 16:20:37 2020 daemon.err uhttpd[3039]: cat: write error: Broken pipe
Wed Sep 16 16:20:44 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:21:19 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:21:50 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:21:58 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:22:20 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:22:27 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:23:20 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:23:26 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:24:20 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use
Wed Sep 16 16:24:28 2020 user.warn igmpproxy[8530]: MRT_ADD_MEMBERSHIP failed; Errno(98): Address in use

日志报错这个是什么问题？

**Comment by BecodReyes** [comment]
**小白建议多百度**
地址已被使用
