### ISSUE TITLE
Transmission 现在没有软件包了吗? 怎么找不到了 我要如何安装上呀

### ISSUE THREAD

**Issue by cnhap** [coolsnowwolf/lede#5478]
Transmission 现在没有软件包了吗? 怎么找不到了 我要如何 云编译到 固件里面去呀

**Comment by Dimitri2020007** [comment]
克隆lede原码，cd到lede下，更新并安装feeds。make menuconfig。保存config文件。
虚拟机用winscp下载lede目录下的.config文件。
wsl直接进\\$wsl\home\用户名\lede\目录。
记事本或notepad＋＋打开.config文件。
搜索和Transmission有关的项目。
把Transmission那整段复制下来
粘贴到你的脚本就ok了。

**Comment by cnhap** [comment]
> 克隆lede原码，cd到lede下，更新并安装feeds。make menuconfig。保存config文件。
> 虚拟机用winscp下载lede目录下的.config文件。
> wsl直接进\$wsl\home\用户名\lede\目录。
> 记事本或notepad＋＋打开.config文件。
> 搜索和Transmission有关的项目。
> 把Transmission那整段复制下来
> 粘贴到你的脚本就ok了。

若是用actions 编译呢  我没有 搭建虚拟机环境

**Comment by Dimitri2020007** [comment]
用win10的wsl啊，最好是wsl的ubuntu。你用的action编译的软件其实还是make menuconfig生成的.config里头的东西。
