### ISSUE TITLE
多个设备编译报错！patch失败！

### ISSUE THREAD

**Issue by IvanSolis1989** [coolsnowwolf/lede#5484]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

多设备云编译报错！patch报错！错误代码类似

### (2) 路由器型号和固件版本

![image](https://user-images.githubusercontent.com/44228691/93566467-b04b0e00-f9bf-11ea-85c2-a4c3579145cc.png)

树莓派4 K2P K2T B70 MI R3P K3 R2S等设备 
网址：https://github.com/IvanSolis1989/OpenWrt-DIY

### (3) 详细日志

Applying ./patches/010-gcc10.patch using plaintext: 
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

|--- a/src/http.h
|+++ b/src/http.h

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 13
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

|--- a/src/tls.h
|+++ b/src/tls.h

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/010-gcc10.patch!
make[3]: *** [/workdir/openwrt/build_dir/target-aarch64_cortex-a72_musl/shadowsocks-libev-3.3.5/.prepared_813e41c8eec3047cba30468fa06d1691_6664517399ebbbc92a37c5bb081b5c53] Error 1
Makefile:132: recipe for target '/workdir/openwrt/build_dir/target-aarch64_cortex-a72_musl/shadowsocks-libev-3.3.5/.prepared_813e41c8eec3047cba30468fa06d1691_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#0.17#0.07#0.22
make[2]: *** [package/feeds/packages/shadowsocks-libev/compile] Error 2
package/Makefile:111: recipe for target 'package/feeds/packages/shadowsocks-libev/compile' failed
make[1]: *** [/workdir/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by xwcoco** [comment]
同样的问题....

**Comment by qianxu2001** [comment]
似乎是我发的那个更新 ss-libev 的 pr 导致的，等大雕看看吧，我也不确定我那个 pr 没问题。。。

**Comment by qianxu2001** [comment]
应该是 packages 仓库那边 ss-libev 更新导致的问题，大雕好像已经修复了，再编译应该就行了

**Comment by IvanSolis1989** [comment]
是吗。我看看额

**Comment by IvanSolis1989** [comment]
已修复 编译正常 谢谢
