### ISSUE TITLE
怎么切换到之前的源码编译

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#5498]
源码有异常自动重启问题想切换到指定日期的源码，
现在是最新源码，想切换到Commit 3ac0246ce966b4251f1374171524f99a4234b8f0

直接git checkout 3ac0246ce966b4251f1374171524f99a4234b8f0

然后make menuconfig、make -j8 V=s就可以了？

**Comment by pupboss** [comment]
可以是可以，稳妥起见你还可以在 feeds.conf.default 里面指定那一天的依赖 commit hash，有时候新的依赖包和旧的程序不兼容
