### ISSUE TITLE
软路由，为何有这些错误提示

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#5499]
![屏幕截图 2020-09-20 113225](https://user-images.githubusercontent.com/59297839/93693653-4d7b8300-fb35-11ea-89f1-e6563fb4ee37.png)

**Comment by BecodReyes** [comment]
内核信息，忽略即好

**Comment by coolsnowwolf** [comment]
http proxy 的报错

**Comment by Dimitri2020007** [comment]
是dns代理报错了

**Comment by rangerwill** [comment]
我也遇到了

**Comment by rangerwill** [comment]
> 
> 
> 是dns代理报错了，和libcurl.so文件有关。

这个问题应该怎么解决啊...?
最近半个月编译的openwrt都有这个问题   国内网站打不开

**Comment by kurtsong** [comment]
同样遇到了这个问题，重新调整，编译了n次固件未能解决。。如果把https-dns-proxy删掉就好了，但不知道会不会影响使用

**Comment by rangerwill** [comment]
service mwan3 stop
service mwan3 disable
解决

**Comment by rangerwill** [comment]
> 
> 
> service mwan3 stop
> service mwan3 disable
> 解决


无法访问国内网站，国外网站访问正常的解决方式
