### ISSUE TITLE
竞斗云固件没有编译flowoffloading，但是刷完固件进去后为何会出现相关设置未保存的提示？另外，编译的竞斗云固件居然没有无线，不知道是什么原因？

### ISSUE THREAD

**Issue by Sunnice** [coolsnowwolf/lede#5502]
竞斗云固件没有编译flowoffloading，但是刷完固件进去后为何会出现相关设置未保存的提示？另外，编译的竞斗云固件居然没有无线，不知道是什么原因？
![84d9fa2c8ef1b12c08f331c24707c97](https://user-images.githubusercontent.com/44739306/93709813-05c81c00-fb74-11ea-8769-ed350202f377.jpg)

**Comment by AmadeusGhost** [comment]
实测无线正常，你固件做小一点就好（别到将近 100M 这种程度）

**Comment by Sunnice** [comment]
> 实测无线正常，你固件做小一点就好（别到将近 100M 这种程度）

那我可能就是超体积了，谢谢暗云大佬（永远嘀神！

**Comment by Sunnice** [comment]
> 实测无线正常，你固件做小一点就好（别到将近 100M 这种程度）

请问一下大佬我图片上显示flowoffload配置问题是怎么回事呀？我没有编译flowoff插件呀，这个配置未保存的提示每次都有，不论是lede还是稳定版源码.

**Comment by AmadeusGhost** [comment]
> 请问一下大佬我图片上显示flowoffload配置问题是怎么回事呀？我没有编译flowoff插件呀，这个配置未保存的提示每次都有，不论是lede还是稳定版源码.

不保存配置升级试试

**Comment by Sunnice** [comment]
> > 请问一下大佬我图片上显示flowoffload配置问题是怎么回事呀？我没有编译flowoff插件呀，这个配置未保存的提示每次都有，不论是lede还是稳定版源码.
> 
> 不保存配置升级试试

我固件都是从opboot刷的ubi文件，都是不保存配置的。每次进去都有这个，tg群里也有人跟我有相同情况

**Comment by doumeki** [comment]
一样,可以这样改，不过大神可以来看看有什么副作用没

vi /etc/init.d/autocore
sysctl -w net.xxxx 那行前面加#号注释掉

![image](https://user-images.githubusercontent.com/10527841/97801331-f78f1480-1c76-11eb-869a-630bd5e6709c.png)
