### ISSUE TITLE
Applications里没有找到SSR Plus插件选项

### ISSUE THREAD

**Issue by showlee** [coolsnowwolf/lede#5506]
我想单独编译ssr + 插件，怎么在make menuconfig的时候，进入LuCi-Applications后找不到ssr +插件呢？

**Comment by hawie** [comment]
feeds.conf.default

**Comment by Dimitri2020007** [comment]
编辑feeds.conf.default文件，去除helloworld前的注释。然后重新执行./script/feeds update -a 和install -a

**Comment by showlee** [comment]
嗯啦，谢谢楼上两位的不吝赐教！我已经在之前的issues找到答案，谢谢！
