### ISSUE TITLE
编译一直报错

### ISSUE THREAD

**Issue by Yofo-me** [coolsnowwolf/lede#5509]
> [config文件URL:https://github.com/coolsnowwolf/lede/files/5255338/config.txt](https://github.com/coolsnowwolf/lede/files/5255338/config.txt)

> 很奇怪的问题，我没有勾选libevhtp，但一直报错（如图所示）

![image](https://user-images.githubusercontent.com/55388087/93766571-2f06ac00-fc49-11ea-86b6-ba540a7ca074.png)
![image](https://user-images.githubusercontent.com/55388087/93766611-39c14100-fc49-11ea-9c96-de0272e5188b.png)

**Comment by Dimitri2020007** [comment]
make download下载不完整
