### ISSUE TITLE
frp 0.34.0下载地址404

### ISSUE THREAD

**Issue by 759071793** [coolsnowwolf/lede#5512]
frp 0.34.0下载地址404
<img width="733" alt="image" src="https://user-images.githubusercontent.com/23308600/93783002-cf66cb80-fc5d-11ea-892d-4ba26fa7d8c8.png">

**Comment by 759071793** [comment]
找到问题了，是我ssr plus设置的dns解析的问题，原来的cloudflare的dns 1.1.1.1，改为 谷歌的8.8.8.8解析别的下载地址就好了

**Comment by swxk521** [comment]
不是你的问题，frp提交错误，有人改了，还没合并。。

**Comment by 759071793** [comment]
> 不是你的问题，frp提交错误，有人改了，还没合并。。

原来如此，谢谢你，但是我刚刚改了下dns解析，就下载下来了，而且下载地址也变了，难道是刚好改过

**Comment by 759071793** [comment]
> 不是你的问题，frp提交错误，有人改了，还没合并。。

原来如此，谢谢你，但是我刚刚改了下dns解析，就下载下来了，而且下载地址也变了，难道是刚好改过
