### ISSUE TITLE
L大神ShadowSocksR Plus+能否加个负载均衡和分流？

### ISSUE THREAD

**Issue by skym1990** [coolsnowwolf/lede#5514]
浏览网页负载均衡可以吧 浏览网页ip飘没关系的  YouTube一个国家的ip飘不飘也不重要 只要每次自动能换就行 不用每次打开手动更换节点  像passwall
分流+负载均衡均衡完美

**Comment by skydevil88** [comment]
装一个 HAProxy 就可以了。

**Comment by Michaol** [comment]
编译前make menuconfig选上HAProxy不就行了么……

**Comment by Dimitri2020007** [comment]
luci内置的unbound不行吗？mwan3helper不行吗？

**Comment by skym1990** [comment]
带有HAProxy固件 可以发个链接吗

**Comment by Dimitri2020007** [comment]
我咋给你haproxy固件啊？
