### ISSUE TITLE
请教下磁盘占用的问题

### ISSUE THREAD

**Issue by yfdoor** [coolsnowwolf/lede#5522]
运行一段时间，比如3个月左右，就会发现根目录达到了 100%，此时会出现一些问题，例如改变配置无法保存，无法更新DNS 过滤列表等等，请问下有什么办法吗？谢谢

Filesystem                Size      Used Available Use% Mounted on
/dev/root                20.8M     20.8M         0 100% /rom
tmpfs                   496.1M    492.0K    495.6M   0% /tmp
/dev/loop0              473.3M    377.3M         0 100% /overlay
overlayfs:/overlay      473.3M    377.3M         0 100% /
/dev/sda1                15.7M      3.9M     11.5M  25% /boot
/dev/sda1                15.7M      3.9M     11.5M  25% /boot
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by zhujingwei** [comment]
可以扩充/overlay，用空余磁盘空间或者u盘

**Comment by yfdoor** [comment]
> 可以扩充/overlay，用空余磁盘空间或者u盘
请问下那么在编译固件的时候，这两个是需要那个调整大呢？
CONFIG_TARGET_KERNEL_PARTSIZE=24
CONFIG_TARGET_ROOTFS_PARTSIZE=100

**Comment by zhujingwei** [comment]
rootfs
