### ISSUE TITLE
大佬，ssrplus什么时候支持VLESS，还是编译时APP里面要选择上v2ray？

### ISSUE THREAD

**Issue by 31415926pai** [coolsnowwolf/lede#5523]
大佬，ssrplus什么时候支持VLESS，还是编译时APP里面要选择上v2ray？使用VLESS时，停用ss使用v2ray?

**Comment by 31415926pai** [comment]
![无标题](https://user-images.githubusercontent.com/33808765/93893695-86c41680-fd20-11ea-826c-2a04ccf9456b.jpg)
我把v2ray从4.27.5升级到4.28.2是不是只能在v2ray中使用，SSRPLUS中能不能使用VLESS

**Comment by 31415926pai** [comment]
![v](https://user-images.githubusercontent.com/33808765/93894510-66e12280-fd21-11ea-965f-eb9b7b7b4f0b.jpg)
没有注意，早就支持了。
。。。
:)

**Comment by 759071793** [comment]
自己下载内核去替换吧，默认是4.27的内核
