### ISSUE TITLE
请教个关于feeds和LUCI的问题

### ISSUE THREAD

**Issue by recinfo** [coolsnowwolf/lede#5525]
请问，我想修改feeds.conf.default这个文件，比如src-git freifunk https://github.com/freifunk/openwrt-packages.git这句，大概能知道是什么意思，可是一直不明白这个src-git freifunk中的freifunk是哪里来的，如果我添加别的地址，这个地方该写什么？谢谢

比如我想添加src-git xxx https://github.com/ABC/CDE.git，那么我在XXX这个地方应该填写什么？？

另外，L大默认的插件选择界面有很多已经选上的，-*-，前面是这个符号，不能取消选择，我有些选择是我不想要的，该如何取消掉这个选择，再次感谢。

**Comment by 759071793** [comment]
我都是直接进目录git clone，一般不去修改feeds.conf.default文件

**Comment by eallion** [comment]
- xxx 一般填 ABC，就是用户名。一般都要按制作 feeds 的人写的说明文档填。
- 一般需要先取消掉依赖，再才能取消掉插件。有些又互相依赖，有些又一对多依赖，如果不太理解就不要取消。

**Comment by 9l** [comment]
src-git xxx 这个 xxx 应该是 git clone 远端仓库克隆到本地的 xxx 目录下，随便写不和已有的重复就行，一般和远端仓库或仓库作者同名容易辨识
