### ISSUE TITLE
可以修复一下源码ipk包编译的错误吗

### ISSUE THREAD

**Issue by Dimitri2020007** [coolsnowwolf/lede#5526]
错误是这样的：

选择的luci-app太多的时候编译会出错误
提示是:execvp: /usr/bin/env: Argument list too long
一开始以为是软件包冲突我修改了编译时软件包的选项还是会出现那个错误
后来删源码重新clone，重新修改配置还是会出现Argument list too long的错误

我给编译机的配置4核cpu，8g内存，100g的硬盘。
这样的配置编译源码足够吗？

这个错误我搜了下可能有以下需要修改的地方
1.是ulimit stack要修改
2.是openwrt修改的可以避免Argument list too long的错误。
他们修改了include/package-ipkg.mk这个文件。
这是解决那个错误的链接（英文）
https://patchwork.ozlabs.org/project/openwrt/cover/20200219215212.31263-1-cotequeiroz@gmail.com/

本人修改代码的水平有限，能提供的信息只有这些了。

**Comment by 759071793** [comment]
x86没遇到过这种错误
