### ISSUE TITLE
编译X86-32位出错

### ISSUE THREAD

**Issue by freeleeman** [coolsnowwolf/lede#5527]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：编译X86-32位出错

### (2) 路由器型号和固件版本

A：X86-32位

### (3) 详细日志

A：
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/frp-0.34.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
make[3]: *** [/workdir/openwrt/dl/frp-0.34.0.tar.gz] Error 2
Makefile:64: recipe for target '/workdir/openwrt/dl/frp-0.34.0.tar.gz' failed
make[3]: Leaving directory '/workdir/openwrt/package/lean/frp'
time: package/lean/frp/compile#0.21#0.09#1.33
package/Makefile:111: recipe for target 'package/lean/frp/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/lean/frp/compile] Error 2
make[1]: *** [/workdir/openwrt/staging_dir/target-i386_pentium4_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-i386_pentium4_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
make: *** [world] Error 2
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
##[error]Process completed with exit code 2.

**Comment by minlang112** [comment]
makefile里frp的hash写错了，已经有人提pull requests了，你可以先自己去下载https://codeload.github.com/fatedier/frp/tar.gz/v0.34.0 放到dl里面……
