### ISSUE TITLE
 NanoPi R2S无法引导启动

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#5542]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
 [ x] 没有类似的issue

## 2. 详细叙述

使用大雕的源码编译NanoPi R2S固件一切顺利，没有任何报错，但刷入NanoPi R2S后无法引导启动。

### (2) 路由器型号和固件版本

NanoPi R2S

**Comment by hxlls** [comment]
用balenaEtcher直接写GZ 文件，不需要解压

**Comment by lariboo** [comment]
> 用balenaEtcher直接写GZ文件，不需要解压

用老兄说的软件测试了下，依旧无法启动。老兄可有r2s云编译的源码？
