### ISSUE TITLE
编译报错，make download时报错

### ISSUE THREAD

**Issue by ramondelee** [coolsnowwolf/lede#5549]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：最新源码编译报错，make download时报错

### (2) 路由器型号和固件版本

A：R2S

### (3) 详细日志

A：
 make[2] -C package/lean/v2ray download
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download

试了换梯子，用-j1多次多时段都不行

**Comment by Dimitri2020007** [comment]
v2ray模块更新了，手动下载v2ray模块最新版本然后放进lede\dl目录下
