### ISSUE TITLE
稳定版编译报错

### ISSUE THREAD

**Issue by wwz09** [coolsnowwolf/lede#5550]
Makefile'package / feeds / luci / luci-app-https-dns-proxy / Makefile'与'https-dns-proxy'有依赖关系，该依赖关系不存在

**Comment by pangfeng161** [comment]
稳定版下载dns-proxy放到目录,我就是这样才能编译成功

**Comment by Dimitri2020007** [comment]
手动下载dns-proxy放进lede\dl目录下
