### ISSUE TITLE
没有PPTP VPN这个IPK插件了吗？

### ISSUE THREAD

**Issue by wangx2** [coolsnowwolf/lede#5556]
需要这个插件连回家里的网络，不清楚为什么给取消了？

**Comment by yinzhefuyun** [comment]
> 需要这个插件连回家里的网络，不清楚为什么给取消了？

因为出现了0day漏洞，并且官方态度是不修，然后本来我也以为大题小作，直到我回家的时候，我去看我都路由器一个下午全部都是尝试登入的记录然后我也慌了，我也就关闭了，后面lean也取消了

**Comment by goer99** [comment]
是这个漏洞吗：
https://cert.360.cn/warning/detail?id=b41ffdb8a90a58c0c263b84a03ed22fa
http://www.seczk.com/?type=newsinfo&S_id=1675

他们建议升级ppp

**Comment by Dimitri2020007** [comment]
pptp vpn已经淘汰了，换个别的吧
