### ISSUE TITLE
帮我看看，是不是源库文件的错误才导致出问题

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#5559]
Finding targets
go: github.com/armon/go-socks5@v0.0.0-20160902184237-e75332964ef5: Get "https://proxy.golang.org/github.com/armon/go-socks5/@v/v0.0.0-20160902184237-e75332964ef5.mod": dial tcp 172.217.4.81:443: connect: connection refused

Building targets
go: github.com/armon/go-socks5@v0.0.0-20160902184237-e75332964ef5: Get "https://proxy.golang.org/github.com/armon/go-socks5/@v/v0.0.0-20160902184237-e75332964ef5.mod": dial tcp 172.217.4.81:443: connect: connection refused

Cleaning module download cache (golang/go#27455)

Makefile:64: recipe for target '/lede/build_dir/target-mipsel_24kc_musl/frp-0.34.0/.built' failed
make[3]: *** [/lede/build_dir/target-mipsel_24kc_musl/frp-0.34.0/.built] Error 1
make[3]: Leaving directory '/lede/package/lean/frp'
time: package/lean/frp/compile#0.18#0.12#168.22
package/Makefile:111: recipe for target 'package/lean/frp/compile' failed
make[2]: *** [package/lean/frp/compile] Error 2
make[2]: Leaving directory '/lede'
package/Makefile:107: recipe for target '/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/lede'
/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
ub@ubuntun1804:/lede$ 

>  github.com/armon/go-socks5@v0.0.0-20160902184237-e75332964ef5

是不是源文件出问题了，才导致错误

**Comment by Dimitri2020007** [comment]
源文件没有错误，只是你需要挂一个goproxy代理。我曾遇到过这个问题。想解决不难。谷歌去找设置go代理的方法。
