### ISSUE TITLE
[bug] 未知错误，密码未更改！Unknown Error, password not changed!

### ISSUE THREAD

**Issue by eallion** [coolsnowwolf/lede#5563]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

- 在 LuCi 界面修改密码，提示：`未知错误，密码未更改！` 对应英文版：`Unknown Error, password not changed!`

- 通过 SSH `passwd root`修改密码，提示成功，但之后无法登录 LuCi 界面，也无法登录 SSH 了。

### (2) 路由器型号和固件版本

A：x86 release

### (3) 详细日志

A：暂无

原因：初步定位为编译`shadow-utils`所致。
- Utilities
    - shadow-utils

昨天编译的一个固件，正常使用，今天重新编译了固件，仅多选了`shadow-utils`，刷机后就不能修改密码了，退回昨天编译的固件恢复正常。

**Comment by asushugo** [comment]
是不是没空间了？

**Comment by eallion** [comment]
> 是不是没空间了？

应该不是吧

**Comment by Dimitri2020007** [comment]
提供系统出错的日志

**Comment by wushenghn** [comment]
这个毛病一直有web不能改密码，命令改了就登录不了，shadow-utils是账号添加删除修改的一些命令
