### ISSUE TITLE
upnp能创建端口但是qbt 彗星都连不上

### ISSUE THREAD

**Issue by xiaofengcod** [coolsnowwolf/lede#5568]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Dimitri2020007** [comment]
你lede的nat开了fullcone类型吗？

如果是的话就是你所在地区的运营商网络或者gfw屏蔽了bt下载的端口。
这种基本没有可以解决的办法。

**Comment by EvineDeng** [comment]
不要使用6881-6889的端口，大概率是被isp封的。如果切换其他端口还不行，检查一下openwrt上一级的路由器或猫的设置。

**Comment by klsxd** [comment]
https://koolshare.cn/forum.php?mod=viewthread&tid=157946
试试第三种方法

**Comment by fhbyljj** [comment]
一样问题，可我另一个宽带正常，硬件不一样，版本一样，设置一样
