### ISSUE TITLE
请教一下，为什么编译进了802.11kvr选项和wpa3却没有找到在哪设置？

### ISSUE THREAD

**Issue by hahaleyile** [coolsnowwolf/lede#5573]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
802.11kvr我是在 kernel -> 无线驱动那边编译进去的，可以看下我发的buildinfo
wpa3 根据官方资料是只要在无线是ap模式的情况下，编译进去 hostapd-openssl 就行了
但是我好像刷好固件后都没有发现在哪配置
是不是得手动配置？还是说k2p不支持？按理说这些都是软件实现，k2p应该支持的才对

### (2) 路由器型号和固件版本

A： 
| 路由器型号 | 固件版本 |
| --- | --- |
| k2p a2 | LuCI Master (git-20.256.12360-1a54222) / OpenWrt R20.9.15 |

### (3) 详细日志

A：
[logs.zip](https://github.com/coolsnowwolf/lede/files/5298742/logs_15.zip)

**Comment by AmadeusGhost** [comment]
k2p 只能用闭源驱动，直接放弃即可

**Comment by IDeLoveYou** [comment]
请问这个问题你解决了嘛

**Comment by hahaleyile** [comment]
> 请问这个问题你解决了嘛

我记得我当时就没有搞成功，后面也就没继续尝试了
