### ISSUE TITLE
编译错误，请帮帮忙分析！

### ISSUE THREAD

**Issue by sgsek** [coolsnowwolf/lede#5575]
make[2]: *** [package/Makefile:71: package/install] Error 1
make[2]: Leaving directory '/home/sds/lede'
make[1]: *** [package/Makefile:108: /home/sds/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/sds/lede'
make: *** [/home/sds/lede/include/toplevel.mk:224: world] Error 2

**Comment by 759071793** [comment]
dl目录文件没有下载完整

**Comment by Dimitri2020007** [comment]
你源码dl下载完整了吗？

**Comment by xxsunyxx** [comment]
一直hyper v+ubuntu 14, 顶多是重新下载代码,要不每次基本都成功了,hyper v可以用

**Comment by Dimitri2020007** [comment]
我用hyper-v编译一直提示argument list too long的错误
换vmware就没事。

**Comment by datout** [comment]
同样，，云编译报错

**Comment by Dimitri2020007** [comment]
线路够好的话还是推荐本地编译。
