### ISSUE TITLE
希望可以加入luci-proto-ncm 软件包

### ISSUE THREAD

**Issue by jeffok** [coolsnowwolf/lede#5580]
在使用该仓库编译镜像的时候，不能选择luci-proto-ncm 源码中搜索也不存在，希望可以加入，用于usb无线上网卡

在使用官方的opkg install luci-proto-ncm 或使用其它编译好的直接安装，界面都不能正常打开，且不可正常使用。

**Comment by 759071793** [comment]
你这种需求很少有人用到吧，最好还是自己直接clone到lede源码编译

**Comment by badcrazy** [comment]
因为lean的lua版本比官方低，直接用官方的luci程序会出问题，可以尝试安装luci-compat、luci-lib-ipkg这两个包，可以解决一定的兼容问题，但并不能全部解决，你可以试试看

**Comment by lylus** [comment]
本来就有这个包，要想luci里面可以luci-proto-ncm，你需要在首页的网络 netw开头的（英文不会写）里wwan把 comgt（反正是com开头的） 和comgt-ncm 选上，选上后在luci就会有你所说的luci-proto-ncm，好了，不用谢。
