### ISSUE TITLE
如何改斐讯K3  5.4内核的/dev/root分区大小

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [coolsnowwolf/lede#5583]
斐讯K3  5.4内核的/dev/root分区大小默认46M，怎么改大一些？

**Comment by Dimitri2020007** [comment]
<img width="890" alt="捕获" src="https://user-images.githubusercontent.com/69845732/94923701-da87ea00-04ee-11eb-92ae-6898adb74ea7.PNG">

修改root filesystem partition size
单位是MB

**Comment by xiangfeidexiaohuo** [comment]
> <img alt="捕获" width="890" src="https://user-images.githubusercontent.com/69845732/94923701-da87ea00-04ee-11eb-92ae-6898adb74ea7.PNG">
> 
> 修改root filesystem partition size
> 单位是MB

k3固件格式是squashfs，没这么多选项的啊

**Comment by Dimitri2020007** [comment]
我这是x86的。
