### ISSUE TITLE
新版本编译出来的固件，开启 Netflix 分流后会影响 Qnap 的 DDNS

### ISSUE THREAD

**Issue by hi-caicai** [coolsnowwolf/lede#5593]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：在开启 Netfilx 分流以后，在高级设置里，如果选择了 Netfilx 和 AWS ，那么在 Qnap 里的 DDNS 的 IP 会被更新成 Netfilx 分流的主机上面，目测可能是部分的的 IP 导致的，但是新的版本中那个编辑器 IP 的界面没有了，所以也不知道在哪里修改

### (2) 路由器型号和固件版本

A：J1900 ，OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222)

--

**Comment by Ljzkirito** [comment]
你把Qnap的LAN IP设置为**不走代理的局域网LAN IP**看看

**Comment by hi-caicai** [comment]
> 你把Qnap的LAN IP设置为**不走代理的局域网LAN IP**看看

还是一样的，不知道为啥

**Comment by lynnial** [comment]
用软路由的动态dns插件，或者QNAP的IP获取服务器拉入白名单
