### ISSUE TITLE
怎么选4.X的内核？？？

### ISSUE THREAD

**Issue by jzjohn789** [coolsnowwolf/lede#5608]
5.X的太多插件不兼容
想用4.X的。应该怎么选，谢谢

**Comment by Dimitri2020007** [comment]
lean 没有设置源码分支。编译版本内核都是5.x的。
4.x内核的lean固件是这个https://github.com/coolsnowwolf/openwrt.git

还有一个是这https://github.com/Lienol/openwrt.git

**Comment by jzjohn789** [comment]
但是我编译你上面地址的一样报错呢
