### ISSUE TITLE
新版本太好用了，感谢大雕

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#561]
修复了luci，修复了tun tap，各种新功能正常流程，十分感谢。

**Comment by hcym** [comment]
活见久，最近不论官方还是lean大的编译出来都有点状况。命苦

**Comment by hcym** [comment]
看到大雕改动ssr，等几天焚香沐浴后编译。我的就是ssr总是不顺手，还有改动lan后很大概率就挂了。只好退回老老老版本

**Comment by hceasy** [comment]
一直在编译分享asus rt-acrh17的固件,完全跟不上节奏啊 更新那么快 高产似那啥.
