### ISSUE TITLE
为什么单线程编译通过，多线程编译就报错呢？

### ISSUE THREAD

**Issue by cntink** [coolsnowwolf/lede#5610]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：为什么单线程编译通过，多线程编译就报错呢？

### (2) 路由器型号和固件版本

A：x86软路由

### (3) 详细日志

A：每次报错最后一段信息就在编译docker-ce附近，但是单线程编译docker-ce又没问题，编译出来的固件刷入软路由也没有问题，docker也正常！

**Comment by kktt007** [comment]
为什么为什么,大雕也想知道为什么有这么多bug^_^(个人觉的多半是网络原因)

**Comment by programmejava** [comment]
这个估计很多人都遇到过，这个应该是多线程中的线程锁问题，两个线程编译同一个文件时导致互锁，我一般就是make j4 出错继续，直到多线程无法开始的时候再j1

**Comment by smalldickman** [comment]
> 这个估计很多人都遇到过，这个应该是多线程中的线程锁问题，两个线程编译同一个文件时导致互锁，我一般就是make j4 出错继续，直到多线程无法开始的时候再j1

留一个线程不用，（不过有时候还是会中断，也可能是网络问题）
