### ISSUE TITLE
麻烦哪位大神, 帮我解答一些关于，openwrt 应用 python出现错误的问题，非常感谢🙏

### ISSUE THREAD

**Issue by jump-to-jump** [coolsnowwolf/lede#5613]
**具体问题**

A：我的**树莓派4**现在安装了一个散热风扇，它需要通过l2c的接口来控制风扇的运作，我已经安装有python的驱动文件和i2c的驱动，当我用openwrt的驱动运行.py的python文件时 他出现了错误无法运行。

**错误代码**
Traceback (most recent call last):
       File "/mnt/mmcblk0p1/fan/fan.py", line 3, in <module>
             bus = sambus.SMBus(1)
FileNotFoundError: [Errno 2] No such file or directory

**我现在openwrt安装了l2c 的所有固件**
Kernel modules -> I2C Support -> kmod-i2c-algo—pca          # 树莓派 i2c  PCA 9564 interfaces
Kernel modules -> I2C Support -> kmod-i2c-algo—pcf          # 树莓派 i2c  PCF 8584 interfaces
Kernel modules -> I2C Support -> kmod-i2c-bcm2835           # 树莓派 i2c  Broadcom BCM2835 I2C master controller driver
Kernel modules -> I2C Support -> kmod-i2c-core              # 树莓派 i2c 指针40指针硬件支持
Kernel modules -> I2C Support -> kmod-i2c-gpio              # 树莓派 i2c  GPIO-based bitbanging I2C
Kernel modules -> I2C Support -> kmod-i2c-mux               # 树莓派 i2c 指针bus固件支持 bus multiplexing support  
Kernel modules -> I2C Support -> kmod-i2c-mux-pca9541       # 树莓派 i2c 指针bus固件支持 Philips PCA9541 I2C mux/switches
Kernel modules -> I2C Support -> kmod-i2c-mux-pca954x       # 树莓派 i2c 指针bus固件支持 Philips PCA954x I2C mux/switches 
Kernel modules -> I2C Support -> kmod-i2c-pxa               # 树莓派 i2c 指针bus固件支持 Intel PXA I2C bus driver
Kernel modules -> I2C Support -> kmod-i2c-sambus            # 树莓派 i2c 指针bus固件支持 SMBus-specific protocols helper
Kernel modules -> I2C Support -> kmod-i2c-tiny-usb          # 树莓派 i2c 指针bus固件支持 I2C Tiny USB adaptor   

**Python的所有已安装的固件**
Languages -> Python -> docker-compose                     # Docker Compose
Languages -> Python -> python-pip-conf                    # configure file for pip/pip3
Languages -> Python -> python3                            # python 3 语言支持
Languages -> Python -> python-asyncio-src                 # Python 3.8 asyncio module (sources)
Languages -> Python -> python3-sambus                     # sambus库支持

**其他部分插件**
Utilities -> i2c-tools                                   # I2C tools for Linux
Utilities -> kmod                                       # Linux kernel module handling (tools)

**Python 代码**

import smbus
import time
bus = smbus.SMBus(1)

addr = 0x0d
fan_reg = 0x08
state = 0

while True:
    if state == 0:
        bus.write_byte_data(addr, fan_reg, 0x00)
        time.sleep(2)
    elif state == 1:
        bus.write_byte_data(addr, fan_reg, 0x02)
    elif state == 2:
        bus.write_byte_data(addr, fan_reg, 0x03)
    elif state == 3:
        bus.write_byte_data(addr, fan_reg, 0x04)
    elif state == 4:
        bus.write_byte_data(addr, fan_reg, 0x05)
    elif state == 5:
        bus.write_byte_data(addr, fan_reg, 0x06)
    elif state == 6:
        bus.write_byte_data(addr, fan_reg, 0x07)
    elif state == 7:
        bus.write_byte_data(addr, fan_reg, 0x08)
    elif state == 8:
        bus.write_byte_data(addr, fan_reg, 0x09)
    elif state == 9:
        bus.write_byte_data(addr, fan_reg, 0x01)

    state += 1

    if state > 9:
        time.sleep(1)
        state = 0
    time.sleep(1)
    

麻烦有懂的大神解决一下，非常的感谢🙏

**Comment by sxx1314** [comment]
如果用python等调试控制外部io。
还是用armbian之类的宿主系统，再docker一个openwrt即可。  镜像可以自己制作。
openwrt上折腾io非常不舒服，当然你也可以反方向在驱动都编译齐全的情况下把外部io共享给docker。这样你可以保留openwrt为宿主。

**Comment by jump-to-jump** [comment]
> 如果用python等调试控制外部io。
> 还是用armbian之类的宿主系统，再docker一个openwrt即可。 镜像可以自己制作。
> openwrt上折腾io非常不舒服，当然你也可以反方向在驱动都编译齐全的情况下把外部io共享给docker。这样你可以保留openwrt为宿主。

**Comment by jump-to-jump** [comment]
感谢sxx1314, 我试试
