### ISSUE TITLE
希望新版本的v2ray能保留自主上传pb/json配置文件的功能

### ISSUE THREAD

**Issue by dehim** [coolsnowwolf/lede#562]
更新了当前最新版本后，发现v2ray配置页变化了，希望lede能保留以往版本自主上传pb/json配置文件的功能，这个功能对于自主配置的用户很实用。
![image](https://user-images.githubusercontent.com/9805228/45987839-3f114280-c0a6-11e8-99a5-f1df5346b81d.png)

**Comment by yizhuanapp** [comment]
是，刚才找了一圈才发现是去掉了。

**Comment by zhg-em** [comment]
说得在理，这个确实应该保留！

**Comment by coolsnowwolf** [comment]
居然有人用这个功能啊~

**Comment by zcluo** [comment]
一直在用多个服务负载均衡

coolsnowwolf <notifications@github.com> 于 2018年9月27日周四 12:59写道：
