### ISSUE TITLE
#建议# SSR-plus插件，订阅节点关键字过滤能否增加一个取反操作选项

### ISSUE THREAD

**Issue by lePig** [coolsnowwolf/lede#5621]
就是比如，`订阅节点关键字过滤`：`香港/新加坡`。那么在订阅节点的时候只保留**香港节点**和**新加坡节点**。

虽然现在的这个也能实现，但是大部分机场地区挺多的，日本、美国、新加坡、香港、英国、台湾、澳门等等。

因为一般大部分时间只用香港，因为最快。所以每次刷机后都要输入一大坨排除的节点，好烦呐。 

可以在`订阅节点关键字过滤`下面增加一个复选框，文案：`当勾选时，将保留列表中的关键字的节点，否则，将丢弃包含列表里的关键字的节点。`

还是希望L大有空可以采纳一下，感谢您的辛勤付出。

**Comment by Promix953** [comment]
到helloworld反馈
[https://github.com/fw876/helloworld](url)

**Comment by lePig** [comment]
@Promix953 好的 谢谢
