### ISSUE TITLE
关于R20.9.15一键关机

### ISSUE THREAD

**Issue by Tony4402** [coolsnowwolf/lede#5624]
反馈bug/问题模板，提建议请删除

## 1.关于R20.9.15一键关机的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 本人菜鸟一个，无法自己解决该问题。只能反馈了。

A：

### (2) X86平台，技嘉B75主板+I5 4590T

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
> kmod-button-hotplug 组件是不是支持一键关机的组件

顾名思义是支持通过按按钮去触发对应的 hotplug 事件，看看按按钮的时候系统日志有没有打印什么

**Comment by hyird** [comment]
什么环境，虚拟机的话你要装acpid才能关机的
实体的话 看下日志呗
