### ISSUE TITLE
关于wrt1900acs默认软件源的问题

### ISSUE THREAD

**Issue by vikiyi0** [coolsnowwolf/lede#5637]
关于wrt1900acs默认软件源的问题

截至两天前编译的wrt1900acs固件luci源是

src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.8/packages/arm_cortex-a9_vfpv3-d16/luci

然而这个地址并不存在，导致更新软件包列表出错

存在的是
https://mirrors.cloud.tencent.com/lede/releases/18.06.8/packages/arm_cortex-a9_vfpv3/luci
我猜测原本是要使用
https://mirrors.cloud.tencent.com/lede/snapshots/packages/arm_cortex-a9_vfpv3-d16/luci

总之，麻烦修复默认软件源更新出现的错误

**Comment by AmadeusGhost** [comment]
这个问题挺麻烦的其实，上了 5.4 之后 mvebu 的架构发生了点变化，feeds 也跟着变了
但是这边 luci 是基于 18.06 的，改到 snapshot 怕不是一堆人 opkg install luci-xxx 后翻车 😂
