### ISSUE TITLE
如何设置有线中续

### ISSUE THREAD

**Issue by andangel** [coolsnowwolf/lede#5641]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
如何设置有线中续,小米的原固件有选择连接类型里面有有线中续
OpenWRT找不到 是不是我漏装了什么?
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Twinzo1** [comment]
直接插lan口就行了，嫌少一个网口，就自己改一下vlan并修改lan口ip

**Comment by sxx1314** [comment]
> 直接插lan口就行了，嫌少一个网口，就自己改一下vlan并修改lan口ip

其实不用改vlan 直接把wan 改成 lan即可

**Comment by Dimitri2020007** [comment]
无线路由器里面不是有bridge（桥接）或者叫ap啊只要把你无线路由器的上网方式改成那个就行了啊
不需要拔网线。
