### ISSUE TITLE
openvpn服务器证书问题

### ISSUE THREAD

**Issue by Dullxxs** [coolsnowwolf/lede#5642]
默认使用内置的证书，不大安全吧，毕竟大部分人都会把openvpn服务器映射到公网上.

**Comment by pillanangel** [comment]
这个可以自己动手把配置调整下就可以生成定制的证书，搜一下有不少的教程，不难。毕竟luci-app-openvpn为了开箱即用，已经写好的配置。为了安全，还是自己SSH登录进行定制。当然插件本身如果能提供定制的界面就更好了。^_^
