### ISSUE TITLE
请教各位大神，PassWall和Clash怎么安装，要选择哪些选项，谢谢。

### ISSUE THREAD

**Issue by 31415926pai** [coolsnowwolf/lede#5659]
请教各位大神，PassWall和Clash怎么安装，要选择哪些选项，谢谢。

**Comment by hxlls** [comment]
走错片场了，出门左拐。。。。。。

**Comment by Myoko** [comment]
你不应该在这边问这个问题

**Comment by Elletear** [comment]
請自行參照項目說明安裝編譯：clash→https://github.com/vernesong/OpenClash，pass→https://github.com/kenzok8/openwrt-packages

**Comment by Dimitri2020007** [comment]
passwall是lienol的openwrt里的软件，你走错位置了，这只有ssr+

**Comment by 31415926pai** [comment]
> 請自行參照項目說明安裝編譯：clash→https://github.com/vernesong/OpenClash
> pass→https://github.com/kenzok8/openwrt-packages

谢谢分享。
