### ISSUE TITLE
newifid2重启后配置全部消失

### ISSUE THREAD

**Issue by HashimotoSakura** [coolsnowwolf/lede#5666]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：2020.10.15 00:00拉取代码编译输入newifid2 ,保留的配置全部消失，重新配置完成后，重启，配置消失 

### (2) 路由器型号和固件版本

A：newifi D2

### (3) 详细日志

A：null

**Comment by Cathgao** [comment]
你有没有刷错固件，正常要刷sysupgrade

**Comment by HashimotoSakura** [comment]
是刷了sysupgrade，我今晚删了代码重新拉一份编译吧

**Comment by HashimotoSakura** [comment]
重新编译了以后就好了，好奇怪
