### ISSUE TITLE
希望大佬在R2S可以添加上网络接口显示

### ISSUE THREAD

**Issue by dukh1216** [coolsnowwolf/lede#5667]
1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
 [x] 没有类似的issue

 2. 详细叙述

 (1) 具体问题

A：x86软路由上可以看到接口状态，R2S上没有，不方便查看当前连接的速率，所以希望大佬添加支持。
![image](https://user-images.githubusercontent.com/56962531/96060300-b4852100-0ec2-11eb-9013-60e96db163e8.png)

(2) 路由器型号和固件版本

A：R2S

**Comment by llzzll** [comment]
同求
