### ISSUE TITLE
关于网页终端ttyd实现方法改进的一点问题，利用nginx反向代理

### ISSUE THREAD

**Issue by ZeaKyX** [coolsnowwolf/lede#5672]
想要实现类似unraid里的网页终端的效果：
打开 `http://ip或域名/webterminal`，就是ttyd，如果当前为未登录状态就跳转至登录页面
unraid中就是使用的ttyd，并且应该是靠nginx实现的。
现在使用默认配置编译的lean op，安装了nginx-mod-luci，安装后自动关闭uhttpd然后掌管luci
然后在`/etc/nginx/conf.d/luci.locations`中加入[ttyd官方配置](https://github.com/tsl0922/ttyd/wiki/Nginx-reverse-proxy)，可以正常代理
**但是未登录状态下可以直接进入**，且路径不在cgi-bin之下，不知道luci是跳转原理究竟是什么，希望有大神赐教

**Comment by Awrtiger** [comment]
/etc/config/ttdy 配置文件 添加个验证 增加安全性 就是有点麻烦而已。

`option credential [用户名]:[密码]`

**Comment by ZeaKyX** [comment]
> /etc/config/ttdy 配置文件 添加个验证 增加安全性 就是有点麻烦而已。
> 
> `option credential [用户名]:[密码]`

我绕这么一圈就是为了避免这种选择啊，他要是有弹窗登陆也好，浏览器还能自动填

**Comment by Awrtiger** [comment]
> > /etc/config/ttdy 配置文件 添加个验证 增加安全性 就是有点麻烦而已。
> > `option credential [用户名]:[密码]`
> 
> 我绕这么一圈就是为了避免这种选择啊，他要是有弹窗登陆也好，浏览器还能自动填

Google浏览器可以自动填充用户名密码

**Comment by ZeaKyX** [comment]
> > > /etc/config/ttdy 配置文件 添加个验证 增加安全性 就是有点麻烦而已。
> > > `option credential [用户名]:[密码]`
> > 
> > 
> > 我绕这么一圈就是为了避免这种选择啊，他要是有弹窗登陆也好，浏览器还能自动填
> 
> Google浏览器可以自动填充用户名密码

原来是有弹窗的啊，抱歉孤陋寡闻了。这个要端口转发，占用端口号。不过也算勉强满足需求了。

**Comment by Dimitri2020007** [comment]
装了tty的网页版，一片空白是怎么回事啊？
