### ISSUE TITLE
openwrt 分支 19.07.3 更新 19.07.4

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#5677]
一直在用这个分支，非常稳定好用。
官网稳定版更新到了19.07.4，修复了一些安全问题。大佬考虑同步一下代码吗？

**Comment by VergilGao** [comment]
看了一眼仓库，lean的这个库不是R20吗？

**Comment by BOBINIUNIU** [comment]
> 看了一眼仓库，lean的这个库不是R20吗？

我说的是https://github.com/coolsnowwolf/openwrt 分支，大佬最后更新的是19.07.3

**Comment by VergilGao** [comment]
> > 看了一眼仓库，lean的这个库不是R20吗？
> 
> 我说的是https://github.com/coolsnowwolf/openwrt 分支，大佬最后更新的是19.07.3

额，这个不是不更新了吗……

**Comment by AmadeusGhost** [comment]
> 我说的是 https://github.com/coolsnowwolf/openwrt 分支，大佬最后更新的是19.07.3

这个库是之前的稳定版代码（也就是没上 5.4），并不是 19.07
