### ISSUE TITLE
能编译成功，但出现这种提示，请问各位大佬这是什么原因呢？

### ISSUE THREAD

**Issue by weweyes** [coolsnowwolf/lede#5679]
![Snipaste_2020-10-18_17-03-01](https://user-images.githubusercontent.com/59646715/96363362-65f7b100-1166-11eb-8482-1cc37378187e.jpg)

**Comment by Cathgao** [comment]
Action里要清理一些旧指令，以后可能会不支持，到时候就不成功了

**Comment by Dimitri2020007** [comment]
set-env这个旧指令要被github放弃了。更新脚本
