### ISSUE TITLE
R2S下风扇转个不停，这个好解决吗

### ISSUE THREAD

**Issue by hedahong** [coolsnowwolf/lede#5681]
发现风扇不停的在转（即使温度很低），之前用的friendlywrt的固件没有这个问题（cpu温度低的时候风扇会自动停，温度过热才会转），大佬们这个好解决吗？

**Comment by chpos** [comment]
温度转个不停也不是什么坏事

**Comment by hedahong** [comment]
能依据cpu温度 控制 启停 和 转速 就更完美了

**Comment by qq1316237299** [comment]
bios下设置下

**Comment by lifetyper** [comment]
> 
> 
> bios下设置下

你家r2s有bios？

**Comment by hedahong** [comment]
:) 坐等大佬们来解决，友善的代码是否好移植过来

**Comment by Tzwcard** [comment]
可以从friendlywrt的repo上拿脚本然后加到启动里面
https://github.com/friendlyarm/friendlywrt/blob/master-v19.07.1/target/linux/rockchip-rk3328/base-files/usr/bin/start-rk3328-pwm-fan.sh

**Comment by hedahong** [comment]
> 可以从friendlywrt的repo上拿脚本然后加到启动里面
> https://github.com/friendlyarm/friendlywrt/blob/master-v19.07.1/target/linux/rockchip-rk3328/base-files/usr/bin/start-rk3328-pwm-fan.sh
> https://github.com/friendlyarm/friendlywrt/blob/master-v19.07.1/target/linux/rockchip-rk3328/base-files/etc/init.d/fa-rk3328-pwmfan
> 
> 把第一个.sh放到/usr/bin/内 加x权限 然后把第二个放到/etc/init.d/里面 也是加x权限
> 之后把它enable再start就行了
> 
> `/etc/init.d/fa-rk3328-pwmfan enable`
> `/etc/init.d/fa-rk3328-pwmfan start`

🐂B，谢谢。
