### ISSUE TITLE
螃蟹r8125 19号更新的驱动

### ISSUE THREAD

**Issue by gause555** [coolsnowwolf/lede#5684]
有大佬给更新下么，经测试新驱动解决了上个版本2.5g与千兆网卡之间速度跑不满的问题。
https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

**Comment by hxlls** [comment]
自己下载下来，解压后删除SH 文件，丢package 下，编译时候勾选就行了
