### ISSUE TITLE
SSR+ 访问控制 白名单是否有效的问题

### ISSUE THREAD

**Issue by czxinshui** [coolsnowwolf/lede#5691]
SSR+ 访问控制 白名单是否有效的问题
理论上在白名单窗口填入域名是不走代理，走本地网络的，
不过用这个网站测试却没效果
wenku8.net
这个网站限制日本IP浏览，
使用日本节点，开启大陆白名单，访问控制 白名单，填入这个网站，这个网址就打不开，关闭科学上网或者换其他地区的节点就可以：
这样是不是证明 白名单 是无效的？

**Comment by 9l** [comment]
确认这个网站使用 wenku8.net 这个域名直接访问，不会自动跳转到 www.wenku8.net 吗？你在浏览器的地址栏上确认一下，在白名单里加上 www.wenku8.net，打开浏览器的开发者工具，看看这个网站还有哪些二级域名，都要加进去的
