### ISSUE TITLE
编译报错,提示没有文件，如何操作

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#5695]
Configuring luci-i18n-nlbwmon-zh-cn.
Setting flags for package libc to hold.
Setting flags for package libgcc1 to hold.
Setting flags for package libpthread to hold.
Setting flags for package librt to hold.
cp -fpR /lede/build_dir/target-mipsel_24kc_musl/root-ramips /lede/build_dir/target-mipsel_24kc_musl/root.orig-ramips
/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
/lede/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
Enabling adbyby
./etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
./etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
Enabling arpbind

**Comment by Cathgao** [comment]
最新commit的offload代码有问题，等修复
