### ISSUE TITLE
内核编译报错

### ISSUE THREAD

**Issue by HashimotoSakura** [coolsnowwolf/lede#5696]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
 [*] 没有类似的issue

### (1) 具体问题

A：在加入了 passwall和jd自动签到后，尝试编译报错，passwall与jd依赖无异常

### (2) 路由器型号和固件版本

A：newifi D2

### (3) 详细日志

A：mipsel-openwrt-linux-musl-ld: drivers/net/ethernet/ralink/mtk_offload.o: in function `mtk_offload_check_rx':
target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/drivers/net/ethernet/ralink/mtk_offload.c:508: multiple definition of `mtk_offload_check_rx'; drivers/net/ethernet/mediatek/mtk_offload.o:target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/drivers/net/ethernet/mediatek/mtk_offload.c:122: first defined here
mipsel-openwrt-linux-musl-ld: drivers/net/ethernet/ralink/mtk_debugfs.o: in function `mtk_ppe_debugfs_init':
target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/drivers/net/ethernet/ralink/mtk_debugfs.c:103: multiple definition of `mtk_ppe_debugfs_init'; drivers/net/ethernet/mediatek/mtk_ppe_debugfs.o:target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/drivers/net/ethernet/mediatek/mtk_ppe_debugfs.c:104: first defined here
Makefile:1103: recipe for target 'vmlinux' failed
make[5]: *** [vmlinux] Error 1
make[5]: Leaving directory '/home/sakura/workspace/compile/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72'
Makefile:25: recipe for target '/home/sakura/workspace/compile/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/.image' failed
make[4]: *** [/home/sakura/workspace/compile/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.72/.image] Error 2
make[4]: Leaving directory '/home/sakura/workspace/compile/lede/target/linux/ramips'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/sakura/workspace/compile/lede/target/linux'
time: target/linux/install#388.26#36.95#85.45
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/sakura/workspace/compile/lede'
target/Makefile:19: recipe for target '/home/sakura/workspace/compile/lede/staging_dir/target-mipsel_24kc_musl/stamp/.target_install' failed
make[1]: *** [/home/sakura/workspace/compile/lede/staging_dir/target-mipsel_24kc_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/sakura/workspace/compile/lede'
Build failed - please re-run with -j1 to see the real error message
/home/sakura/workspace/compile/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by EnnawYang** [comment]
1.请搜索相关的issue
2.请耐心等待bug修复，或者回退之前的版本
