### ISSUE TITLE
AliDDNS 不能保存高级设置

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#5698]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
高级设置里设置了URL，但是想更改成网络，保存后发现还是回到URL
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
您这描述好详细哦
