### ISSUE TITLE
请问没有生成/tmp/localtime这个文件是哪里的原因

### ISSUE THREAD

**Issue by gaoyaxuan** [coolsnowwolf/lede#5700]
`root@OpenWrt:~# ll /etc/localtime
lrwxrwxrwx    1 root     root            14 Oct 21 14:52 /etc/localtime -> /tmp/localtime
root@OpenWrt:~# cat /tmp/localtime
cat: can't open '/tmp/localtime': No such file or directory`
因为docker需要挂载这个文件来更改容器内部的时间.求赐教

**Comment by VergilGao** [comment]
如果你的docker镜像没有配置时区的环境变量，那就把这俩文件以只读方式挂载进去。
/etc/localtime
/etc/timezone

**Comment by gaoyaxuan** [comment]
> 如果你的docker镜像没有配置时区的环境变量，那就把这俩文件以只读方式挂载进去。
> /etc/localtime
> /etc/timezone

问题是,这两个文件根本不存在!/etc/localtime指向了/tmp/localtime,而/tmp/localtime文件根本不存在的.

**Comment by VergilGao** [comment]
> > 如果你的docker镜像没有配置时区的环境变量，那就把这俩文件以只读方式挂载进去。
> > /etc/localtime
> > /etc/timezone
> 
> 问题是,这两个文件根本不存在!/etc/localtime指向了/tmp/localtime,而/tmp/localtime文件根本不存在的.

奥，查了一下，openwrt用的是uclibc，时区文件是 /etc/TZ
这个就没办法了，除非你切换成glibc，然后手动配置。 <- 大坑

最简单的办法就是自己打包一层，手动安装timezone 然后 ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

**Comment by gaoyaxuan** [comment]
> > > 如果你的docker镜像没有配置时区的环境变量，那就把这俩文件以只读方式挂载进去。
> > > /etc/localtime
> > > /etc/timezone
> > 
> > 
> > 问题是,这两个文件根本不存在!/etc/localtime指向了/tmp/localtime,而/tmp/localtime文件根本不存在的.
> 
> 奥，查了一下，openwrt用的是uclibc，时区文件是 /etc/TZ
> 这个就没办法了，除非你切换成glibc，然后手动配置。 <- 大坑
> 
> 最简单的办法就是自己打包一层，手动安装timezone 然后 ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime


> > > 如果你的docker镜像没有配置时区的环境变量，那就把这俩文件以只读方式挂载进去。
> > > /etc/localtime
> > > /etc/timezone
> > 
> > 
> > 问题是,这两个文件根本不存在!/etc/localtime指向了/tmp/localtime,而/tmp/localtime文件根本不存在的.
> 
> 奥，查了一下，openwrt用的是uclibc，时区文件是 /etc/TZ
> 这个就没办法了，除非你切换成glibc，然后手动配置。 <- 大坑
> 
> 最简单的办法就是自己打包一层，手动安装timezone 然后 ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

好的!谢谢大佬!

**Comment by acooler15** [comment]
安装`zoneinfo-asia`包，然后运行命令`/etc/init.d/system reload`

![image](https://user-images.githubusercontent.com/19186382/107136412-e6246b00-693d-11eb-8c5f-b82f5e150dec.png)

**Comment by MrGengCom** [comment]
> 安装`zoneinfo-asia`包，然后运行命令`/etc/init.d/system reload`
> 
> ![image](https://user-images.githubusercontent.com/19186382/107136412-e6246b00-693d-11eb-8c5f-b82f5e150dec.png)

Great, solve my problem.
