### ISSUE TITLE
今明两天，编译MT7621 K2P 红米AC2100固件一直报错

### ISSUE THREAD

**Issue by NEARWN** [coolsnowwolf/lede#5702]
今明两天，自从编译MT7621 K2P 红米AC2100固件一直报错
Process completed with exit code 2.

**Comment by EnnawYang** [comment]
哦。

**Comment by tufu9441** [comment]
我是这两天编译MT7621 NewifiD2的固件报错，也是Process completed with exit code 2.

**Comment by jjit** [comment]
是这个错误吗：https://github.com/coolsnowwolf/lede/issues/5693
hwnat代码冲突了，AmadeusGhost已经修复了，Lean还没有整合进源码
可以手动照着这个来修改几个文件：
https://github.com/coolsnowwolf/lede/pull/5697/files
