### ISSUE TITLE
修改feeds.conf里面最后一行的一个#号后，./scripts/feeds update -a后一直报错

### ISSUE THREAD

**Issue by xianzai25** [coolsnowwolf/lede#5710]
修改feeds.conf里面最后一行的一个#号后，./scripts/feeds update -a后一直报错如下

Unable to open feeds configuration at ./scripts/feeds line 91.
即使再添加上这个#号也还是这个错误，之前一直没有遇到过

**Comment by ianMonkey-CN** [comment]
同样的问题，我也遇到了，第一次 没有这样的错误，重新编译 第二次 就这样错误了..希望L大能给解答一下 ！感谢
我是执行更新源插件就错误了
