### ISSUE TITLE
更新ss机场错误

### ISSUE THREAD

**Issue by Dimitri2020007** [coolsnowwolf/lede#5713]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：ss机场更新成功，列表没有出现ss地址，出现了以下错误

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：

-----------start-----------
2020-10-25 15:26:20 重启服务成功
2020-10-25 15:26:20 发生错误, 正在恢复服务
	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:448: in main chunk
	[C]: in function 'xpcall'
	/usr/share/shadowsocksr/subscribe.lua:348: in function </usr/share/shadowsocksr/subscribe.lua:297>
	/usr/share/shadowsocksr/subscribe.lua:190: in function 'processData'
	/usr/share/shadowsocksr/subscribe.lua:450: in function </usr/share/shadowsocksr/subscribe.lua:448>
2020-10-25 15:26:20 stack traceback:
2020-10-25 15:26:20 /usr/share/shadowsocksr/subscribe.lua:190: attempt to index field '?' (a nil value)

**Comment by Cathgao** [comment]
来错地方了
