### ISSUE TITLE
是否可以提供release版本的.config文件

### ISSUE THREAD

**Issue by zhaochengwei** [coolsnowwolf/lede#5715]
是否可以提供release版本的.config文件，直接编译出来不是release里面的东西

**Comment by AmadeusGhost** [comment]
要 release 版本就直接默认配置编译，版本号啥的肯定是最新的，除非你把源码都回退到那个时候

**Comment by zhaochengwei** [comment]
这个是由配置项决定的，如果.config没有是编不出来那个release的固件的

> 要 release 版本就直接默认配置编译，版本号啥的肯定是最新的，除非你把源码都回退到那个时候

**Comment by jjit** [comment]
img文件解包，打开 /usr/lib/opkg/status 这个文件
根据status文件里的 Package包的名称来修改 .config文件
或者在make menuconfig里根据status来选中 Package包
就是比较麻烦一些，不如大佬直接给出.config文件来得方便
不过也能解决问题

**Comment by ihuaer** [comment]
> 是否可以提供release版本的.config文件，直接编译出来不是release里面的东西

对比软件包添加吧，虽然慢了点

**Comment by zhaochengwei** [comment]
[config.txt](https://github.com/coolsnowwolf/lede/files/5782430/config.txt)

贴上了我的config欢迎下载使用~
