### ISSUE TITLE
feed install 的时候一大片警告闪过去了，强迫症犯了

### ISSUE THREAD

**Issue by HashimotoSakura** [coolsnowwolf/lede#5724]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：拉代码update feeds后install，一大片黄字警告闪过去了，请问对固件完整性影响大吗？

### (2) 路由器型号和固件版本

A：newifi d2

### (3) 详细日志

A：WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libpng', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/antileech/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/automount/Makefile' has a dependency on 'antfs-mount', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/dnsforwarder/Makefile' has a dependency on 'coreutils-base64', which does not exist
WARNING: Makefile 'package/lean/frp/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libgstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1-libs', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/lean/kcptun/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/libs/libselinux/Makefile' has a dependency on 'musl-fts', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/lean/luci-app-accesscontrol/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-adbyby-plus/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'shairport-sync-openssl', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-amule/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-arpbind/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-baidupcs-web/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifs-mount/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a dependency on 'ksmbd-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cpufreq/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'smartmontools', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'btrfs-progs', which does not exist
WARNING: Makefile 'package/lean/luci-app-dnsforwarder/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a dependency on 'docker-ce', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils-nohup', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'bash', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-filetransfer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-flowoffload/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frpc/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-guest-wifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a dependency on 'haproxy', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-minimal', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-mod-xauth-generic', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-mod-kernel-libipsec', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'nginx', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'unzip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'zoneinfo-asia', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-fpm', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-gd', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-iconv', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-json', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-mbstring', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-opcache', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-session', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-zip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-sqlite3', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-sqlite', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-mysql', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'forked-daapd', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-n2n_v2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a dependency on 'netdata', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nft-qos/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-common', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-relay', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ps3netsrv/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-qbittorrent/Makefile' has a dependency on 'python3', which does not exist
WARNING: Makefile 'package/lean/luci-app-qbittorrent/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ramfree/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a dependency on 'fuse-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-samba4/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-sfe/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a dependency on 'python3', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a dependency on 'ttyd', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-unblockmusic/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a dependency on 'p910nd', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-v2ray-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-verysync/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vlmcsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vsftpd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-webadmin/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a dependency on 'luci-app-nlbwmon', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a dependency on 'zerotier', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-lib-docker/Makefile' has a dependency on 'luci-lib-json', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci-lib-nixio', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a dependency on 'proto-bonding', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-argon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-netgear/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'libpcre2-16', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'icu', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-chrono', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-random', which does not exist
WARNING: Makefile 'package/lean/rclone/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libtasn1', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'attr', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libaio', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libavahi-client', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'python3-cryptodome', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libarchive', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'acl', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'attr', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'libtasn1/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'rpcsvc-proto/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'python3/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'perl/host', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a build dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/tcpping/Makefile' has a dependency on 'libnet-1.2.x', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-program_options', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-date_time', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusic/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusicGo/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/v2ray/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/v2ray-plugin/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/wxbase/Makefile' has a dependency on 'libexpat', which does not exist

**Comment by Ljzkirito** [comment]
你再feed install一次看看，还有没有WARNING
首次feed install都会这样

**Comment by HashimotoSakura** [comment]
再次就没有了，好奇怪

**Comment by jjit** [comment]
因为feeds update，会根据feeds.conf.default文件，下载依赖包到feeds文件夹
还没有放到 package文件夹里，第一次feeds install会先扫描package目录
然后再把 feeds文件夹里的依赖包，通过软连接方式放进 package目录
所以原先已经在 package目录里的插件，第一次会报 缺少一些依赖包
之后再运行 就不会报了，因为 feeds文件夹已经放在 package目录里了

**Comment by HashimotoSakura** [comment]
谢谢，了解了
