### ISSUE TITLE
Naiveproxy 无法编译通过。

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#5725]
反馈bug/问题模板，提建议请删除

自从前天开始，SSR选中Naiveproxy后一直无法编译通过，以前没问题的。

**Comment by afeiy** [comment]
install libtinfo5

**Comment by Elletear** [comment]
開啟新issue前請善用搜索，已經有人提出過該問題  #5694 
并已有解決方案  fw876/helloworld#219

**Comment by gswangmd-gssi** [comment]
已经keyi1编译了，非常感谢。

Elletear <notifications@github.com> 于2020年10月29日周四 上午9:37写道：

**Comment by Dimitri2020007** [comment]
action和实体编译请添加这个软件libtinfo5

**Comment by Cathgao** [comment]
解决了请关闭issue
