### ISSUE TITLE
R7800-R8.1.3-MWAN3与Flow Offload冲突问题

### ISSUE THREAD

**Issue by daidaiwood** [coolsnowwolf/lede#573]
多线负载规则已配置无误
1.Linux Flow Offload Forwarding 转发加速引擎开启
   启动mwan3后网络无法访问，断网，在路由器上ping和tracert也无网络。
2.Linux Flow Offload Forwarding 转发加速引擎关闭
  开启mwan3后，双线负载均衡正常。

ps:不管正常与否 mwan3启动均有报错
     报错如下
 root@AIRouter:~# /etc/init.d/mwan3 start
uci: Entry not found
uci: Entry not found
grep: /var/etc/miniupnpd.conf: No such file or directory
uci: Entry not found
uci: Entry not found
grep: /var/etc/miniupnpd.conf: No such file or directory
uci: Entry not found
uci: Entry not found
grep: /var/etc/miniupnpd.conf: No such file or directory
uci: Entry not found
uci: Entry not found
grep: /var/etc/miniupnpd.conf: No such file or directory

今天重新编译了下新的R8.1.3 发现flow offload即使关掉也不行，mwan3一开启还是断网。

**Comment by maxjove** [comment]
同样有这问题. 没找到原因.... 不知道是不是和mwan3冲突了
