### ISSUE TITLE
小米ac2100 wifi闭源驱动bug

### ISSUE THREAD

**Issue by jx10086** [coolsnowwolf/lede#5734]
## 1.关于你要提交的问题
小米ac2100 wifi闭源驱动bug
## 2. 详细叙述
[ 1916.025041] RtmpOSFileOpen(): Error 2 opening /etc/Wireless/RT2860/RT2860_5G.dat
[ 1924.348306] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 1924.356404] --> Error opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 1924.368969] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2036.343628] RtmpOSFileOpen(): Error 2 opening /etc/Wireless/RT2860/RT2860_5G.dat
[ 2044.663738] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2044.671804] --> Error opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2044.684239] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2886.726925] RtmpOSFileOpen(): Error 2 opening /etc/Wireless/RT2860/RT2860_5G.dat
[ 2895.047884] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2895.055991] --> Error opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2895.068518] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2959.418377] RtmpOSFileOpen(): Error 2 opening /etc/Wireless/RT2860/RT2860_5G.dat
[ 2967.737771] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2967.745837] --> Error opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat
[ 2967.758273] RtmpOSFileOpen(): Error 2 opening /etc_ro/Wireless/SingleSKU_mt7615e-sku.dat

**Comment by AmadeusGhost** [comment]
有点奇怪，不应该去找 `/etc/Wireless/RT2860/RT2860_5G.dat` 这个文件的，我试试能不能修修看 (((
