### ISSUE TITLE
RM2100 闭源 中继跟着上游路由器自动换信道？

### ISSUE THREAD

**Issue by jinglei207** [coolsnowwolf/lede#5737]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：为什么不能自动跟着上游自动换信道？必须手动修改才行？

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by 1715173329** [comment]
那你找个支持的？

**Comment by AmadeusGhost** [comment]
> 那你找个支持的？

这个不能怪用户，luci-app-mtwifi 已经被改坏掉了，原本是支持的。
