### ISSUE TITLE
系统里Attended Sysupgrade正确使用的方式

### ISSUE THREAD

**Issue by Eintler** [coolsnowwolf/lede#5742]
自编译版本，在系统里的Attended Sysupgrade下
![image](https://user-images.githubusercontent.com/3525492/97934879-ebf43880-1db1-11eb-863e-8d05b450527f.png)

一片空白啊。
如何使用呢？

**Comment by ihuaer** [comment]
> 自编译版本，在系统里的Attended Sysupgrade下
> ![image](https://user-images.githubusercontent.com/3525492/97934879-ebf43880-1db1-11eb-863e-8d05b450527f.png)
> 
> 一片空白啊。
> 如何使用
这个是linksys用的。。。。

**Comment by Eintler** [comment]
Thanks

**Comment by siren202101** [comment]
我的也是空白
