### ISSUE TITLE
ddns-scripts_cloudflare.com-v4包能够加入编译选项吗？

### ISSUE THREAD

**Issue by SUNJINZE** [coolsnowwolf/lede#575]
ddns-scripts_cloudflare.com-v4包每次编译完要手动安装上 比较麻烦 希望能够加入ddns-scripts_cloudflare.com-v4包选项  
谢谢

**Comment by breakersun** [comment]
> ddns-scripts_cloudflare.com-v4包每次编译完要手动安装上 比较麻烦 希望能够加入ddns-scripts_cloudflare.com-v4包选项
> 谢谢
@Saxon-Sun 你好，请问下，是如何手动安装的？从openwrt官方源那边下载到ipk，然后用opkg install安装的吗？

**Comment by Saxon-Sun** [comment]
> > ddns-scripts_cloudflare.com-v4包每次编译完要手动安装上 比较麻烦 希望能够加入ddns-scripts_cloudflare.com-v4包选项
> > 谢谢
> > @Saxon-Sun 你好，请问下，是如何手动安装的？从openwrt官方源那边下载到ipk，然后用opkg install安装的吗？

直接更新源后搜索cloudflare包安装即可
