### ISSUE TITLE
Openwrt重启时日志报错，Failed to load DMC firmware i915 

### ISSUE THREAD

**Issue by AlwaysOnline** [coolsnowwolf/lede#5750]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
X
### (1) 具体问题

A：路由器重启时，会卡住系统。

### (2) 路由器型号和固件版本

A：N3450的CPU，内核版本是5.4.72。

### (3) 详细日志

A：

[   60.618277] i915 0000:00:02.0: Failed to load DMC firmware i915/bxt_dmc_ver1_07.bin. Disabling runtime power management.
[   60.619000] i915 0000:00:02.0: DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

**Comment by hyird** [comment]
不用管 I915是核显驱动 用不上的

**Comment by lixiangyu1314** [comment]
我也这样的情况
