### ISSUE TITLE
固件如何处理v2ray自身从服务端解析的dns结果？

### ISSUE THREAD

**Issue by Jingye-Xia** [coolsnowwolf/lede#5754]
v2ray自身会将需要代理的域名发送到v2ray的服务端，经由服务端vps设置的dns服务器进行解析，同时 SSR Plus 也会将需要代理的域名通过 SSR Plus 内部的 PDNSD 走 SSR 的转发工具（SS/SSR/V2 等）建立的隧道到 VPS 节点，然后由 VPS 通过 TCP DNS 查询 8.8.8.8，所以到底最后接受的是哪个结果？

**Comment by coolsnowwolf** [comment]
SSR Plus 内部的 PDNSD，这样各个组件的逻辑是统一的

**Comment by Jingye-Xia** [comment]
> SSR Plus 内部的 PDNSD，这样各个组件的逻辑是统一的

也就是说v2ray解析出来的结果被丢弃了是吗
