### ISSUE TITLE
autocore 编译报错

### ISSUE THREAD

**Issue by stvber** [coolsnowwolf/lede#5757]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
跟这个有点像，作为依赖的lm-sensors无法编译通过
https://github.com/coolsnowwolf/lede/issues/151
### (1) 具体问题
musl/5.4.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
A：

### (2) 路由器型号和固件版本

A：x86_64 R20.10.20

### (3) 详细日志

A：

**Comment by overprince** [comment]
重新部署的机器首次编译也出现了同样的问题, 不通过.

.../bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
prog/sensors/Module.mk:43: recipe for target 'prog/sensors/sensors' failed

自行编译libiconv库后依然报相同错误

首次编译流程严格按照说明进行, 未进行任何默认配置的修改

编译环境: ubuntu 18.4 LTS
内核: 5.10.23

相关日志:
'
x86_64-openwrt-linux-musl-gcc -DETCDIR="\"/etc\"" -I. -I/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Wall -O2 -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Winline -W -Wmissing-prototypes -Wundef -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0=lm-sensors-3-6-0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -c lib/sysfs.c -o lib/sysfs.ao
x86_64-openwrt-linux-musl-gcc -DETCDIR="\"/etc\"" -I. -I/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Wall -O2 -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Winline -W -Wmissing-prototypes -Wundef -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0=lm-sensors-3-6-0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wno-undef -c lib/conf-parse.c -o lib/conf-parse.ao
x86_64-openwrt-linux-musl-gcc -DETCDIR="\"/etc\"" -I. -I/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Wall -O2 -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Winline -W -Wmissing-prototypes -Wundef -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0=lm-sensors-3-6-0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Wno-shadow -Wno-undef -Wno-unused -Wno-missing-prototypes -Wno-sign-compare -c lib/conf-lex.c -o lib/conf-lex.ao
rm -f lib/libsensors.a
x86_64-openwrt-linux-musl-gcc-ar rcvs lib/libsensors.a lib/data.ao lib/general.ao lib/error.ao lib/access.ao lib/init.ao lib/sysfs.ao lib/conf-parse.ao lib/conf-lex.ao
a - lib/data.ao
a - lib/general.ao
a - lib/error.ao
a - lib/access.ao
a - lib/init.ao
a - lib/sysfs.ao
a - lib/conf-parse.ao
a - lib/conf-lex.ao
x86_64-openwrt-linux-musl-gcc -DETCDIR="\"/etc\"" -I. -I/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Wall -O2 -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Winline -W -Wmissing-prototypes -Wundef -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0=lm-sensors-3-6-0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -c prog/sensors/main.c -o prog/sensors/main.ro
x86_64-openwrt-linux-musl-gcc -DETCDIR="\"/etc\"" -I. -I/home/ubuntu/lede/staging_dir/target-x86_64_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include -Wall -O2 -Wstrict-prototypes -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wnested-externs -Winline -W -Wmissing-prototypes -Wundef -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0=lm-sensors-3-6-0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -c prog/sensors/chips.c -o prog/sensors/chips.ro
x86_64-openwrt-linux-musl-gcc  -o prog/sensors/sensors prog/sensors/main.ro prog/sensors/chips.ro -liconv -Llib -lsensors
/home/ubuntu/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.4.0/../../../../x86_64-openwrt-linux-musl/bin/ld: cannot find -liconv
collect2: error: ld returned 1 exit status
prog/sensors/Module.mk:43: recipe for target 'prog/sensors/sensors' failed
make[4]: *** [prog/sensors/sensors] Error 1
make[4]: Leaving directory '/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0'
Makefile:126: recipe for target '/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0/.built' failed
make[3]: *** [/home/ubuntu/lede/build_dir/target-x86_64_musl/lm-sensors-3-6-0/.built] Error 2
make[3]: Leaving directory '/home/ubuntu/lede/feeds/packages/utils/lm-sensors'
time: package/feeds/packages/lm-sensors/compile#2.39#0.32#2.59
package/Makefile:111: recipe for target 'package/feeds/packages/lm-sensors/compile' failed
make[2]: *** [package/feeds/packages/lm-sensors/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/lede'
package/Makefile:107: recipe for target '/home/ubuntu/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/lede'
/home/ubuntu/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
'
