### ISSUE TITLE
SSR-Plus 添加节点时，提示：Request Entity Too Large

### ISSUE THREAD

**Issue by chpos** [coolsnowwolf/lede#5758]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：SSR-Plus 在添加节点时，提示：Request Entity Too Large，我觉得可能是我节点添加过多的原因，这个插件还有这个限制吗？这个限制能不能解除？

### (2) 路由器型号和固件版本

A：R2S，使用lean 源码

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
有上限的，不能超过 1024 个
