### ISSUE TITLE
FFmpeg 怎样才能用？

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#5769]
已经选择 CONFIG_BUILD_PATENTED=y 和H264等相关依赖，但是编译出来还是没法保存视频。

![Snipaste_2020-11-10_17-44-31](https://user-images.githubusercontent.com/10294460/98657096-74f40c80-237c-11eb-91b2-99f6e6e51a97.png)

**Comment by yonggedebaqi** [comment]
你用格式有问题
FFmpeg -i “URL” -c copy “1.mp4”

**Comment by yonggedebaqi** [comment]
如果还是不行加上 user-agent referer

**Comment by lloyd18** [comment]
> 你用格式有问题
> 
> FFmpeg -i “URL” -c copy “1.mp4”

格式没问题，可以不用双引号。

**Comment by lloyd18** [comment]
> 如果还是不行加上 user-agent referer

可以看到，h264处于disable状态，是软件问题。

**Comment by yonggedebaqi** [comment]
试试保存文件MP4改成ts
