### ISSUE TITLE
dropbear 默认需要绑定到LAN，不然会有很大的安全问题。路由器被外网攻击控制

### ISSUE THREAD

**Issue by jindaxia** [coolsnowwolf/lede#5772]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：dropbear 建议默认设置 option Interface 'lan'

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by jindaxia** [comment]
https://github.com/coolsnowwolf/lede/pull/5773

**Comment by Dimitri2020007** [comment]
这个默认不是未设置吗？

**Comment by stvber** [comment]
在/package/network/services/dropbear/dropbear.config里面添加option Interface 'lan'

**Comment by jindaxia** [comment]
> 这个默认不是未设置吗？

未设置就是有问题

**Comment by Dimitri2020007** [comment]
好吧

**Comment by mjyhj** [comment]
防火墙是摆设吗？

**Comment by jindaxia** [comment]
![image](https://user-images.githubusercontent.com/587992/99013181-e73a3c00-258a-11eb-8a8a-7e57c4e5d9bd.png)
这个就是默认配置。直接wan口公网可以通过22端口用默认密码登录

**Comment by 1715173329** [comment]
你自己把防火墙准入设置成允许，怪得了谁？

**Comment by EnnawYang** [comment]
防火墙是摆设吗？
