### ISSUE TITLE
lxc页面显示不正常

### ISSUE THREAD

**Issue by 4860575** [coolsnowwolf/lede#5774]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译了lxc后luci的页面显示不出“ Template”如下图：
![image](https://user-images.githubusercontent.com/24975201/98844131-daccbb00-2486-11eb-8872-cad3bfdbf1bf.png)

### (2) 路由器型号和固件版本

A：rpi-4 
OpenWrt R20.10.20 / LuCI Master (git-20.256.12360-1a54222)

### (3) 详细日志

A：
已经找到原因并提交pr了

**Comment by NagaseKouichi** [comment]
给小娱路由器编译的lede的lxc也有这个问题

**Comment by NagaseKouichi** [comment]
发现编译完的固件里面只有lxc-create、lxc-attach、lxc-console几个命令，lxc-start等很多都没有

**Comment by Dimitri2020007** [comment]
menuconfig>utilities>lxc下全选了吗？

**Comment by 4860575** [comment]
应该不是没选lxc-start的问题。

**Comment by 4860575** [comment]
lxc-create -t download -n alpine -- --server mirrors.tuna.tsinghua.edu.cn/lxc-images  --no-validate
使用命令是可以创建成功的。

**Comment by NagaseKouichi** [comment]
请问LZ你是怎么编译的？只要选中luci-app-lxc和menuconfig>utilities>lxc下面的所有组件就可以吗？

http://www.gnuton.org/blog/2016/02/lxc-on-openwrt/
我看这里写还要进行一些别的设置，你有设置这个吗？

**Comment by 4860575** [comment]
> 请问LZ你是怎么编译的？只要选中luci-app-lxc和menuconfig>utilities>lxc下面的所有组件就可以吗？
> 
> http://www.gnuton.org/blog/2016/02/lxc-on-openwrt/
> 我看这里写还要进行一些别的设置，你有设置这个吗？

1、替换lxc为2.1版本（可以从官方19.07，18.06下载替换），lean包里的lxc是4.0，我测试了4.0不行。2.1没问题；
2、正常编译就可以，选择上内核相应的选项；
3、如果没有/srv/lxc就创建；
4、使用lxc-create -t download -n alpine -- --server mirrors.tuna.tsinghua.edu.cn/lxc-images --no-validate 创建就可以了

**Comment by NagaseKouichi** [comment]
> > 请问LZ你是怎么编译的？只要选中luci-app-lxc和menuconfig>utilities>lxc下面的所有组件就可以吗？
> > http://www.gnuton.org/blog/2016/02/lxc-on-openwrt/
> > 我看这里写还要进行一些别的设置，你有设置这个吗？
> 
> 1、替换lxc为2.1版本（可以从官方19.07，18.06下载替换），lean包里的lxc是4.0，我测试了4.0不行。2.1没问题；
> 2、正常编译就可以，选择上内核相应的选项；
> 3、如果没有/srv/lxc就创建；
> 4、使用lxc-create -t download -n alpine -- --server mirrors.tuna.tsinghua.edu.cn/lxc-images --no-validate 创建就可以了
> ![image](https://user-images.githubusercontent.com/24975201/99959580-3c195600-2dc6-11eb-97ae-8acdad39beef.png)
> ![image](https://user-images.githubusercontent.com/24975201/99959628-505d5300-2dc6-11eb-9c1b-09363375f4e4.png)
> ![image](https://user-images.githubusercontent.com/24975201/99959692-6c60f480-2dc6-11eb-9d0a-9522bcbfa69f.png)

谢谢，我之后试下

**Comment by NagaseKouichi** [comment]
把package/feeds/packages/lxc/里面的文件替换成2.1.1之后，编译报错呢

![QQ截图20201124012348](https://user-images.githubusercontent.com/53267025/99995208-02ac0f00-2df5-11eb-8877-8059805e7491.png)

**Comment by 4860575** [comment]
> 把package/feeds/packages/lxc/里面的文件替换成2.1.1之后，编译报错呢
> 
> ![QQ截图20201124012348](https://user-images.githubusercontent.com/53267025/99995208-02ac0f00-2df5-11eb-8877-8059805e7491.png)
> 
> 我从头编译试试

清理一下编译目录。

**Comment by NagaseKouichi** [comment]
> > 把package/feeds/packages/lxc/里面的文件替换成2.1.1之后，编译报错呢
> > ![QQ截图20201124012348](https://user-images.githubusercontent.com/53267025/99995208-02ac0f00-2df5-11eb-8877-8059805e7491.png)
> > 我从头编译试试
> 
> 清理一下编译目录。

嗯，make dirclean之后编译成功了，谢谢。我去测试下

**Comment by NagaseKouichi** [comment]
已经成功运行了Ubuntu Trusty，和 https://mlapp.cn/375.html 这篇文章说的一样，debian无法启动，提示mount cgroup失败。

另外，我按照LZ说的方法编译后，lxc的luci界面显示正常，下拉菜单可以显示镜像列表。
我用的这个LXC镜像源：mirrors.tuna.tsinghua.edu.cn/lxc-images

**Comment by 4860575** [comment]
> 已经成功运行了Ubuntu Trusty，和 https://mlapp.cn/375.html 这篇文章说的一样，debian无法启动，提示mount cgroup失败。
> 
> 另外，我按照LZ说的方法编译后，lxc的luci界面显示正常，下拉菜单可以显示镜像列表。
> 我用的这个LXC镜像源：mirrors.tuna.tsinghua.edu.cn/lxc-images

那可能我是arm架构的问题

**Comment by NagaseKouichi** [comment]
https://forum.openwrt.org/t/request-for-lxc-support-in-mvebu/58767/4
我找到这个帖子，他通过给lxc-auto.init打补丁，可以解决mount /sys/fs/cgroup/systemd失败的问题。

我试了下，在openwrt启动后再运行下面两行命令也是可以的：
```
mkdir -p /sys/fs/cgroup/systemd
mount -t cgroup -o rw,nosuid,nodev,noexec,relatime,none,name=systemd cgroup /sys/fs/cgroup/systemd
```

运行完就可以正常启动debian和ubuntu高版本的容器了

**Comment by 4860575** [comment]
> https://forum.openwrt.org/t/request-for-lxc-support-in-mvebu/58767/4
> 我找到这个帖子，他通过给lxc-auto.init打补丁，可以解决mount /sys/fs/cgroup/systemd失败的问题。
> 
> 我试了下，在openwrt启动后再运行下面两行命令也是可以的：
> 
> ```
> mkdir -p /sys/fs/cgroup/systemd
> mount -t cgroup -o rw,nosuid,nodev,noexec,relatime,none,name=systemd cgroup /sys/fs/cgroup/systemd
> ```
> 
> 运行完就可以正常启动debian和ubuntu高版本的容器了
> 
> 不知道这个可不可以让LXC4.0正常运行

我看他是19.07版本。lxc版本应该是2.1

**Comment by NagaseKouichi** [comment]
> > https://forum.openwrt.org/t/request-for-lxc-support-in-mvebu/58767/4
> > 我找到这个帖子，他通过给lxc-auto.init打补丁，可以解决mount /sys/fs/cgroup/systemd失败的问题。
> > 我试了下，在openwrt启动后再运行下面两行命令也是可以的：
> > ```
> > mkdir -p /sys/fs/cgroup/systemd
> > mount -t cgroup -o rw,nosuid,nodev,noexec,relatime,none,name=systemd cgroup /sys/fs/cgroup/systemd
> > ```
> > 
> > 
> > 运行完就可以正常启动debian和ubuntu高版本的容器了
> > 不知道这个可不可以让LXC4.0正常运行
> 
> 我看他是19.07版本。lxc版本应该是2.1

嗯，我试了2.1运行上面的命令就可以正常启动debian和ubuntu高版本的容器了

下次有时间在4.0试试
