### ISSUE TITLE
dnsforwarder删库跑路啦

### ISSUE THREAD

**Issue by HoldOnBro** [coolsnowwolf/lede#5777]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如题，导致编译失败

### (2) 路由器型号和固件版本

A：任意型号

### (3) 详细日志

A：dnsforwarder-6.1.15.tar.gz: Download from https://github.com/holmium/dnsforwarder.git failed
5915
dnsforwarder-6.1.15.tar.gz: Requires sha256sum for verification
5916
Checking out files from the git repository...
5917
Cloning into 'dnsforwarder-6.1.15'...
5918
remote: Repository not found.

**Comment by littleBanshee** [comment]
http://web.archive.org/web/20200927072747/https://github.com/holmium/dnsforwarder/

**Comment by HoldOnBro** [comment]
临时上传了一份 https://github.com/HoldOnBro/dnsforwarder
