### ISSUE TITLE
luci-app-v2ray-server 无法启动

### ISSUE THREAD

**Issue by goofysun** [coolsnowwolf/lede#5778]
持续了有几周了，暂时还没导出日志

**Comment by Dimitri2020007** [comment]
用的是不是nginx，如果是就调整/etc/uwsgi/vassals/luci-webui.ini的limit-as参数

改大点

你的v2瑞服务端就能启动了。

**Comment by goofysun** [comment]
@Dimitri2020007 
不是 nginx 的，l大默认的。
刚刚特地试了一下，设置 luci-app-v2ray-server 然后开启服务，系统日志合内核日志没有任何输出。

感觉就像是 界面界面只是操作了界面，没有任何底层调用

**Comment by Dimitri2020007** [comment]
提供下日志

**Comment by goofysun** [comment]
系统日志里没有任何有关的日志，2点56 操作了一次开启 luci-app-v2ray-server ,日志知道 50 后面就没了
![image](https://user-images.githubusercontent.com/1747913/99356415-14695000-28e5-11eb-8205-875081359f0a.png)

**Comment by goofysun** [comment]
![image](https://user-images.githubusercontent.com/1747913/99357828-8fcc0100-28e7-11eb-8b69-11eec75d9c01.png)

不管怎么操作，什么日志都没有
