### ISSUE TITLE
MIR3G在R8.1.2以上版本硬盘读写非常慢 8.1.1则正常

### ISSUE THREAD

**Issue by cym422948** [coolsnowwolf/lede#578]
原本8.1.1有50M/S的速度 编译8.1.2后就只剩5M/S 希望LEAN能修复

**Comment by cym422948** [comment]
都是由samba提供局域网访问

**Comment by yonggedebaqi** [comment]
8.1.3版本192.168.1.2复制文件到192.168.1.3路由器也是好慢。

**Comment by yonggedebaqi** [comment]
![qq 20181003101233aaaaa](https://user-images.githubusercontent.com/43800614/46386596-f9cbc100-c6f4-11e8-90df-ab231b550369.png)
![qq 20181003101247bbbbbbbb](https://user-images.githubusercontent.com/43800614/46386597-f9cbc100-c6f4-11e8-9e63-b8f1b910c5d0.png)

**Comment by yonggedebaqi** [comment]
我想是不是NTFS的问题，不知换EXT4会不会要好点。

**Comment by cym422948** [comment]
> 我想是不是NTFS的问题，不知换EXT4会不会要好点。

我就是EXT4 没用 速度只有个位数 直接用winscp提取硬盘文件也是慢  希望LEAN能修复这个问题

**Comment by yonggedebaqi** [comment]
> > 我想是不是NTFS的问题，不知换EXT4会不会要好点。
> 
> 我就是EXT4 没用 速度只有个位数 直接用winscp提取硬盘文件也是慢 希望LEAN能修复这个问题

EXT4我是外网读取路由器文件速度非常的慢，之前的固件正常。
