### ISSUE TITLE
斐讯k2 刷完后没有2.4g wifi

### ISSUE THREAD

**Issue by z719893361** [coolsnowwolf/lede#5782]
5G WIFI信号很差。没有 2.4G WIFI。

![Screenshot_2020-11-14-07-07-08-040_com mmbox xbrowser pro](https://user-images.githubusercontent.com/38043183/99129270-0b0f8780-2648-11eb-9d92-60a00dd68831.jpg)

**Comment by z719893361** [comment]
![Uploading Screenshot_2020-11-14-07-07-08-040_com.mmbox.xbrowser.pro.jpg…]()

**Comment by AmadeusGhost** [comment]
日志呢？？？

**Comment by langit7** [comment]
same thing  with mir3p,  wifi range so low, if out from room wifi keep disconnected

**Comment by wushenghn** [comment]
the latest code have the same problem. no radio 1

**Comment by lon91ong** [comment]
有解决办法了吗? 刚刚编译的也是这个问题

**Comment by lon91ong** [comment]
参考[我的经验](https://github.com/garypang13/OpenWrt/issues/349), 重新刷入eeprom即可解决!
