### ISSUE TITLE
编译r2s时出错make: *** [/home/lixiang/friendlywrt-rk3328/friendlywrt/include/toplevel.mk:227：world] 错误 2 Command exited with non-zero status 2 you take 1:07.73 to build friendlywrt

### ISSUE THREAD

**Issue by LOVEMEBUT** [coolsnowwolf/lede#5789]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
在编译r2s固件过程中，在1小时多出现报错
### (1) 具体问题
报错内容为：
A：make[1]: Leaving directory '/home/lixiang/friendlywrt-rk3328/friendlywrt'
make: *** [/home/lixiang/friendlywrt-rk3328/friendlywrt/include/toplevel.mk:227：world] 错误 2
Command exited with non-zero status 2
you take 1:07.73 to build friendlywrt

### (2) 路由器型号和固件版本

路由器型号：r2s；固件版本：friendlywrt-rk3328_20200415

### (3) 详细日志
r-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip:luci-lib-ip -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " CXXFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip:luci-lib-ip -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " LDFLAGS="-L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/lib -znow -zrelro " FPIC="-fpic" LUCI_VERSION="git-20.256.12360-1a54222" LUCI_GITBRANCH="LuCI Master" make -C /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/src/ AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip:luci-lib-ip -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CROSS="aarch64-openwrt-linux-musl-" ARCH="aarch64" DESTDIR="/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-install"  install; cp -fpR /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-install/* /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip/; else true; fi
make[4]: Entering directory '/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/src'
aarch64-openwrt-linux-musl-gcc -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/lib -L/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/lib -znow -zrelro  -shared -o ip.so ip.o -llua -lm -lnl-tiny
mkdir -p /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-install/usr/lib/lua/luci
cp ip.so /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-install/usr/lib/lua/luci/ip.so
make[4]: Leaving directory '/home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/src'
find /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="aarch64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="aarch64-openwrt-linux-musl-nm" STRIP="/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/sstrip" STRIP_KMOD="/home/lixiang/friendlywrt-rk3328/friendlywrt/scripts/strip-kmod.sh" PATCHELF="/home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/host/bin/patchelf" /home/lixiang/friendlywrt-rk3328/friendlywrt/scripts/rstrip.sh /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip
rstrip.sh: /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip/usr/lib/lua/luci/ip.so: shared object
(cd /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -x "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -x "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/lixiang/friendlywrt-rk3328/friendlywrt/bin/packages/aarch64_cortex-a53/luci
/home/lixiang/friendlywrt-rk3328/friendlywrt/scripts/ipkg-build -c -o 0 -g 0 /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip /home/lixiang/friendlywrt-rk3328/friendlywrt/bin/packages/aarch64_cortex-a53/luci
Packaged contents of /home/lixiang/friendlywrt-rk3328/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/luci-lib-ip/ipkg-aarch64_cortex-a53/luci-lib-ip into /home/lixiang/friendlywrt-rk3328/friendlywrt/bin/packages/aarch64_cortex-a53/luci/luci-lib-ip_git-20.256.12360-1a54222-1_aarch64_cortex-a53.ipk
echo "luci-lib-ip" >> /home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/luci-lib-ip.default.install
make[3]: Leaving directory '/home/lixiang/friendlywrt-rk3328/friendlywrt/feeds/luci/libs/luci-lib-ip'
time: package/feeds/luci/luci-lib-ip/compile#0.92#0.30#1.24
make[2]: Leaving directory '/home/lixiang/friendlywrt-rk3328/friendlywrt'
make[1]: *** [package/Makefile:107: /home/lixiang/friendlywrt-rk3328/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lixiang/friendlywrt-rk3328/friendlywrt'
make: *** [/home/lixiang/friendlywrt-rk3328/friendlywrt/include/toplevel.mk:227：world] 错误 2
Command exited with non-zero status 2
you take 1:07.73 to build friendlywrt

A：

**Comment by 1715173329** [comment]
自己找友善问去
