### ISSUE TITLE
SSR Plus的问题，自己的VPS在路由端SSR Plus上无法使用，PC端v2ray-n和ios小火箭都正常

### ISSUE THREAD

**Issue by WONGHONGXU** [coolsnowwolf/lede#5792]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：自己的VPS，同样使用Vmess链接添加的节点，PC端v2ray-n和ios小火箭都能正常使用，协议是ws+tls，用的Cloudflare做的解析和CDN加速

### (2) 路由器型号和固件版本

A：路由器是j4105软路由，固件最新编译的lede
      使用R6400加梅林固件的科学上网插件同样无法使用

**Comment by Dimitri2020007** [comment]
你ssr-plus上v2ray节点的ws path和tls主机填的是cdn域名吗？tls啥都不填当然没法用了。
