### ISSUE TITLE
请问如何在源码中添加WAN口？？默认编译X86 openwrt固件中只有LAN口

### ISSUE THREAD

**Issue by freeleeman** [coolsnowwolf/lede#5793]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：请问如何在源码中添加WAN口？？默认编译X86 openwrt固件中只有LAN口，没有WAN，在源码中如何修改添加WAN口？

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

**Comment by freeleeman** [comment]
请问如何在源码中添加WAN口？？默认编译X86 openwrt固件中只有LAN口，没有WAN，在源码中如何修改添加WAN口？

**Comment by hcym** [comment]
单口的都是开机后添加vlan的

**Comment by freeleeman** [comment]
> 单口的都是开机后添加vlan的
在源码中如何修改添加WAN口？？？？

**Comment by doumeki** [comment]
默认就是有的，除非识别不了两个以上的网卡。

**Comment by sxx1314** [comment]
创建wan口之后  自行桥接对应网卡 选择wan防火墙即可  另外默认情况下只要有第二个网口就会自动设置成wan，除非没有第二个网卡驱动/没有识别
