### ISSUE TITLE
修改登录账号跟密码

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#5795]
Hi Team

我想修改登录账号跟密码
参考的教程如下：
https://blog.csdn.net/songshuai0223/article/details/103857650

但是发现一个问题，就是改完后，一旦我这边在页面修改了配置，
点击应用，就会一直加载

![loding](https://user-images.githubusercontent.com/25215114/99163596-f7474c80-273f-11eb-8ef3-00eee54d516a.png)

有办法解决这个问题吗，或者 在编译的时候这个可以怎么改

BR
Robin

**Comment by Guxing0321** [comment]
Hi Team

我发现我是少改了一个文件
https://www.right.com.cn/forum/thread-469400-1-1.html
/usr/lib/lua/luci/controller/admin/servicectl.lua

如果有修改编译的方法，也可以提供下，谢谢

BR
Robin

**Comment by doumeki** [comment]
直接改zzz default 文件就行了, 至于用户名自己试吧，改密码如下：
package/lean/default-settings/files/zzz-default-settings
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow 这行把$1$***替换就OK了
至于密码用的是什么加密方式不知道，自己在虚拟机里改了后复制出来吧。
