### ISSUE TITLE
啥时候更新 v2 vless+xtls支持? 

### ISSUE THREAD

**Issue by caolcsu** [coolsnowwolf/lede#5798]
VLESS XTLS 可以达到当前V2Ray平台的最佳性能

建议更新支持。

**Comment by Dimitri2020007** [comment]
应该说是v2ray-server服务端需要添加vless支持，还有ssr-python服务端的加密、混淆方式、协议也要更新下。

**Comment by fengqi** [comment]
这个最佳性能，有相关测试数据吗？

**Comment by caolcsu** [comment]
> 测试

网上搜索一下。
