### ISSUE TITLE
usb3.0接移动硬盘无法识别

### ISSUE THREAD

**Issue by fyfh** [coolsnowwolf/lede#5808]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：usb3.0接移动硬盘无法识别

### (2) 路由器型号和固件版本

A：极路由4，最新的固件

**Comment by OPnb** [comment]
把硬盘格式化成ext4文件格式

**Comment by fyfh** [comment]
还是不行，u盘可以

**Comment by edmondfr** [comment]
有条件的话，换个硬盘盒试试，有些硬盘盒很坑爹的，死活不认。

**Comment by fyfh** [comment]
已解决，是固件问题
