### ISSUE TITLE
询问竞斗云2.0 2.4Ghz Wifi 链接速度

### ISSUE THREAD

**Issue by gwlim** [coolsnowwolf/lede#5809]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
竞斗云2.0
### (1) 具体问题

A：竞斗云2.0 2.4Ghz Wifi 启动HT40后，最高链接速度是150Mbit，是正常的吗？QCA4019 2x2 无线N 不应该是300Mbps的吗？

### (2) 路由器型号和固件版本

A：竞斗云2.0

### (3) 详细日志

A：

**Comment by yinzhefuyun** [comment]
最高应该是400Mbps，要开启强制40Mhz和启用 256-QAM

**Comment by gwlim** [comment]
我是用AX200链接网路。理论上应该是起码300Mps. 竞斗云2.0 2.4Ghz Wifi只支持 Wireless-N。

**Comment by yinzhefuyun** [comment]
> 我是用AX200链接网路。理论上应该是起码300Mps. 竞斗云2.0 2.4Ghz Wifi只支持 Wireless-N。

要开启强制40Mhz和启用 256-QAM，这两个打开了吗

**Comment by gwlim** [comment]
加了vendor_vht=1能启动HT40但是速度不行，只能达到10Mbit/s左右。

**Comment by sxx1314** [comment]
2.4G 你上wifi6 协商到600M一样跑不了多少速度  受环境影响太大  自行查看环境干扰是否太大

**Comment by gwlim** [comment]
问题是QCA4019开启HT40模式速度要比开启HT20还低。其他路由器开启HT40模式有150-180Mbits/s
