### ISSUE TITLE
管理页面点击登录无反应

### ISSUE THREAD

**Issue by authon** [coolsnowwolf/lede#5812]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：权限安装最新编译的固件，进入登陆界面，可以输入用户名和密码（我记得之前是不能输入用户名的），然后点击登入无反应

### (2) 路由器型号和固件版本

A：PVE安装的软路由

### (3) 详细日志

A：

**Comment by Dimitri2020007** [comment]
重装了对应的ipk吗？

**Comment by authon** [comment]
> 重装了对应的ipk吗？

登陆无反应，无法装ipk吧

**Comment by authon** [comment]
> > 重装了对应的ipk吗？
> 
> 登陆无反应，无法装ipk吧

改了皮肤的原因
