### ISSUE TITLE
Realtek 8812BU Driver for Raspbian 驱动是否支持

### ISSUE THREAD

**Issue by wdkGitHub** [coolsnowwolf/lede#5814]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：Realtek 8812BU Driver for Raspbian 驱动是否支持，如不支持，后序是否会考虑加上

**Comment by AmadeusGhost** [comment]
不支持，对于这种不用通用 API 写的驱动，就算支持了你也无法通过 luci 进行配置，后续也不会考虑加上。

**Comment by wdkGitHub** [comment]
> 不支持，对于这种不用通用 API 写的驱动，就算支持了你也无法通过 luci 进行配置，后续也不会考虑加上。

可以推荐一个支持的usb wifi 吗？

**Comment by Dimitri2020007** [comment]
避开realtek这个坑就是了

**Comment by AmadeusGhost** [comment]
> 可以推荐一个支持的usb wifi 吗？

mt7612u
