### ISSUE TITLE
在开启广告屏蔽大师adbyby plus+后,无法启动passwall的负载均衡

### ISSUE THREAD

**Issue by lzr1264823628** [coolsnowwolf/lede#5817]
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
我启动广告屏蔽大师adbyby plus+后,再启动passwall负载均衡,发现负载均衡的控制界面打不开,查看passwall日志,显示运行成功,到passwall运行状态显示负载均衡没有启动. 这个现象非常好重现

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：newifi D2 OpenWrt R20.10.20 / LuCI Master (git-20.256.12360-1a54222)

### (3) 详细日志

A：无

**Comment by Ljzkirito** [comment]
这不应该问passwall作者？

**Comment by d975xbx** [comment]
passwall不是这里的东西
