### ISSUE TITLE
openwrt-ssr使用不正常

### ISSUE THREAD

**Issue by oso21** [coolsnowwolf/lede#582]
版本：R8.1.4
机器：R7500v2
问题：1.订阅点击后无反应
            2.无法使用gfw模式，ssr-dns隧道或者pdnsd（已安装）都不行（同样设置ip模式正常）
初步排查：问题1是脚本权限问题，加上执行权限就正常；问题2还不清楚原因，可能

**Comment by hcym** [comment]
天杀的，v2自从换了搬瓦工就一直不行，以前用用heroku的，好用的很。现在除了路由器不行，手机和电脑一点问题没有，ipv4或者ipv6都可以。估计还是参数什么的不对劲，哭哭晕倒

**Comment by oso21** [comment]
你用什么协议啊？还有各自的版本要对应升级才行，v2的更新很频繁的

**Comment by hcym** [comment]
协议版本都对应，毕竟手机端pc机ipv4ipv6都在正常使用，而且怕出差错只用的最简单的官方规范，命苦不能怪政府，以前配置还复杂一点，兼顾ss和ssr，不折腾了。已经回到官方的版本，国内外解析都正常了，大雕的国内解析确实慢，不知道怎么办。
