### ISSUE TITLE
无法通过Zerotier访问局域网内的SMB服务

### ISSUE THREAD

**Issue by ZechariahZheng** [coolsnowwolf/lede#5821]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

我的情况：
一台开启了ZeroTier的路由器，一台该路由器下开启了smb服务的win10电脑；现在可以使用内网地址，ping通这台win10电脑，但是无法访问smb服务。我已经把win10防火墙的smb端口全打开了，还是无法访问

### (2) 路由器型号和固件版本

A：newifi3  PandoraBox R20.3.8

**Comment by mjyhj** [comment]
https://jingyan.baidu.com/article/020278115819be1bcc9ce5bf.html

**Comment by ZechariahZheng** [comment]
@mjyhj 已经试过了，没有用。主要是在局域网内可以访问，但是在外网使用zerotier不能访问smb服务，可是远程桌面又是可以的

**Comment by guochan2019** [comment]
应该不是固件的问题，我的x86自有了Zerotier后，就一直可以外网访问SMB，包括手机
