### ISSUE TITLE
没有设置自启动，会在不定时的情况下自行重启

### ISSUE THREAD

**Issue by yuwall** [coolsnowwolf/lede#5822]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

没有设置自启动，会在不定时的情况下自行重启
，该问题是在内核升级到5.0版本后出现的
### (1) 具体问题

A：

没有设置自启动，会在不定时的情况下自行重启
，该问题是在内核升级到5.0版本后出现的

### (2) 路由器型号和固件版本
A：

x86软路由，cpu是j1900

### (3) 详细日志

A：
重启后无日志

**Comment by sxx1314** [comment]
参见
 [每天无规律重启1次以上 #5349](https://github.com/coolsnowwolf/lede/issues/5349#issuecomment-708977359)
