### ISSUE TITLE
关于大流量（PT下载）后断网的解决方法和crontab的一些讨论

### ISSUE THREAD

**Issue by ReddotCleaner** [coolsnowwolf/lede#5847]
最近在使用X86软路由，在pt下载（跑满带宽）的情况下，经常会出现断网的情况，必须重启路由器后才能恢复。在经过查看issues和各种资料后，确定问题源头是QWAN3，卸载后顺利用了两周都没再断网，但是在上周五又出现了一次断网，可能与PT下载无关，但是为了不用每次断网都需要手动处理，所以写了个crontab计划任务，每20分钟检测一次网络情况，网络不通则重启路由器
```DATE=`date +%Y-%m-%d-%H:%M:%S`  ```
```(curl https://www.baidu.com/ && echo $DATE netok >/usr/share/ntwk/nt.log ) || (echo $DATE netdown >/usr/share/ntwk/nt.log && /sbin/reboot)```
脚本顺利执行，也能写入日志，就是每次执行，系统日志都会显示如下出错，所以想来请教下各位大手，谢谢
`Mon Nov 30 14:20:00 2020 cron.err crond[29676]: USER root pid 13593 cmd /usr/share/ntwk/ntrb.sh`

**Comment by Ljzkirito** [comment]
老强迫症了，试试改`/etc/init.d/cron`中`loglevel`参数
