### ISSUE TITLE
如何让强制走代理的域名尽快生效

### ISSUE THREAD

**Issue by a-little-cat** [coolsnowwolf/lede#5856]
## 情景描述
使用ssr plus,临时增加需要走代理的域名
## 操作
在luci-ssr 访问控制 强制走代理的域名中增加新的域名
## 非预期现象
总是需要等待几分钟才会生效,不会立刻生效.
## 已尝试解决方案
目前猜测是dns缓存的原因,尝试了各种关闭缓存的方法
1. 关闭turbo acc中的dns加速
2. 清空pdnsd的缓存:
```sh
pdnsd-ctl empty-cache
```
3. 设置 网络/dhcpdns/高级设置/dns查询缓存的大小  为0
## 目前情况
以上3种方法组合使用,依然不能在添加域名后立刻走代理

不过重启openwrt是有效的..

## sos
愿得一大佬 救我出苦海

**Comment by a-little-cat** [comment]
这个也试过了 win10+chrome
用ipconfig /flushdns刷新本机dns

**Comment by Ljzkirito** [comment]
对于浏览器，使用SwitchyOmega插件如何？
