### ISSUE TITLE
v2ray无法启动

### ISSUE THREAD

**Issue by chaohua27** [coolsnowwolf/lede#586]
机器：C301
版本：r699-fbe98eb
问题：填写正确的IP等参数后，勾选启动，并点配置立即生效，v2ray始终显示程序没有在运行。手工执行
/etc/init.d/v2raypro start也无法启动，输出信息如下：
![image](https://user-images.githubusercontent.com/33476686/46302413-9437e180-c5db-11e8-8f44-359e940b13ff.png)

**Comment by coolsnowwolf** [comment]
端口冲突了，你看看是不是 7070 被其他占用了，例如 SSR

**Comment by chaohua27** [comment]
> 端口冲突了，你看看是不是 7070 被其他占用了，例如 SSR

后台看了下，在启用v2ray的情况下，并没有其他任何程序占用7070端口。
![image](https://user-images.githubusercontent.com/33476686/46483189-a60ec400-c829-11e8-8725-12b34db82864.png)

**Comment by lijun0326** [comment]
同经历过这种情况，感觉是stop的时候没把进程杀死
