### ISSUE TITLE
XRay编译成功，但无法启用

### ISSUE THREAD

**Issue by guochan2019** [coolsnowwolf/lede#5864]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

今天看到老大加入了xRay，一时兴起就编译了新版，编译时Network-Project X启用，生成后SSR+出现选项，弄了一台服务器用了好几个方案，配置后都无法运行。有没有成功的兄弟，求指点

**Comment by hetao8980823** [comment]
手动修改 /etc/init.d/shadowsocksr 第118行 直接改成/usr/bin/xray/xray 多加一个/xray

**Comment by hcym** [comment]
小bug😄
