### ISSUE TITLE
k2p保存无限设置页面出现问题

### ISSUE THREAD

**Issue by linchangyi** [coolsnowwolf/lede#5866]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：k2p路由器修改wifi（2.4g和5g）名称密码等设置，保存并应用（已经成功应用）后页面出错，如下所示
![image](https://user-images.githubusercontent.com/6831676/100917983-dab65d00-3512-11eb-8d81-5157bd27b2e4.png)

### (2) 路由器型号和固件版本

A：路由器：Phicomm K2P  MediaTek MT7621 ver:1 eco:3 x 4
     固件版本：OpenWrt R20.10.20 / LuCI Master (git-20.256.12360-1a54222)

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/6831676/100918196-25d07000-3513-11eb-9826-49c99aee67fc.png)

**Comment by AmadeusGhost** [comment]
```
git revert 047d6ea928c7eae803cdad33aeeb685a48098491
git revert 94a7c8578277f75adc9253691ce7106f60bda4e5
git revert 0a796c092b18cb4601b5b1afac6014acf27099cd
```
这几个 commit revert 掉再编译就不会出现这个情况了
