### ISSUE TITLE
luci-app-frps 客户端文件 报错

### ISSUE THREAD

**Issue by suojiang** [coolsnowwolf/lede#5868]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
frps app设置界面无法成功运行，客户端文件提示错误
客户端文件填写 /etc/config/frps 或者留空都报错提示 “无法获取到客户端版本”
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：贝壳云或者N1 刷入openwrt固件之后，frps app无法运行

### (2) 路由器型号和固件版本

A：贝壳云或者N1  Powered by LuCI Master (git-20.256.12360-1a54222) / OpenWrt R20.10.20

### (3) 详细日志

A：查看附件图

![image](https://user-images.githubusercontent.com/12185015/100957928-5685c900-3556-11eb-8d0f-1b8c9e01f49e.png)

**Comment by Her0R0cket** [comment]
注意,这是客户端文件,不是客户端配置文件,文件指向的是应用程序的地址

**Comment by suojiang** [comment]
> 注意,这是客户端文件,不是客户端配置文件,文件指向的是应用程序的地址

好的，晚些再试试
