### ISSUE TITLE
是否应该使用  trojan-go 替代  trojan ？

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#5871]
trojan-go 的目前发展的速度，功能，和特性都已经完全超越 Trojan，唯一考虑的也就是 Golang 程序的体积了

是否应该开始启用 使用  trojan-go 替代  trojan 呢？

（ 16MB ROM 路由器手动再见吧？）

**Comment by hcym** [comment]
速度快的话就取代吧，没用过，都是原版的，感觉c不应该比go的慢吧？

**Comment by Beginner-Go** [comment]
虽然没用过trojan 你说trojan-go超越了  那就替换吧

**Comment by ZqinKing** [comment]
> 速度快的话就取代吧，没用过，都是原版的，感觉c不应该比go的慢吧？

原版没有设计多线程

**Comment by hackyes** [comment]
可以添加上去啊，要什么就手动编译，让用户自己选择

**Comment by ywyha** [comment]
早就希望有这么一天，早就应该替换了

**Comment by accors** [comment]
可以加一个，让用户选

**Comment by lanfenglin** [comment]
可以加上，让用户选择。

**Comment by Fyred** [comment]
当然用go了，我vps上都换go了，爽的一比

**Comment by lifetyper** [comment]
加上去，然后让用户自己选择编译就行了。

**Comment by Lrvineshaw** [comment]
低端硬路由还是别用go了吧，C语言还是优先

**Comment by realsteam** [comment]
加上去默认不勾选，让编译的用户自己决定是否用

**Comment by lqhorochi** [comment]
加上去,用户自主选择添加插件

**Comment by guochan2019** [comment]
同意增加或替换

**Comment by aueu** [comment]
已经采用多个go程序了
这下子，32M rom路由也要拜拜

**Comment by lqhorochi** [comment]
OpenWrt的Trojan go插件项目
https://github.com/frainzy1477/luci-app-trojan

**Comment by Myoko** [comment]
GO 可以替换 trojan

**Comment by Cathgao** [comment]
go兼容trojan，应该替换

**Comment by BOBINIUNIU** [comment]
看过一个内网环境测试，go的性能 比 trojan无论是单核还是多核都快了将近一倍。支持替换。
现在一个路由器才多少钱，抱着32M不放的是准备当传家宝吗

**Comment by mcbbsandnz** [comment]
我觉得可以加上去让用户来自己选择,trojan-go的性能比原版强很多

**Comment by dingpengyu** [comment]
> 我觉得可以加上去让用户来自己选择,trojan-go的性能比原版强很多

支持

**Comment by eallion** [comment]
可以替换，可以共存，但应该要有 Trojan Go 的选项。

**Comment by Ai1954** [comment]
同意替换，非常赞成

**Comment by one02free** [comment]
同意替换，非常赞成

**Comment by qqhpc** [comment]
支持替换

**Comment by Marcotso** [comment]
支持替换

**Comment by kenyloveg** [comment]
支持替换

**Comment by mcucore** [comment]
换吧，老旧路由就默认别选上TROJAN-GO。

**Comment by Gokou-Ruri** [comment]
支持替换，空间我觉得不是问题，可以overlay嘛，想要多大都行。

**Comment by madogao** [comment]
支持替换，我现在是拿trojan-go直接替换的trojan可执行文件

**Comment by 31415926pai** [comment]
关键是GO可以用CDN，速度再快，网速就是那么多。1000M的宽带+1G的VPS，TROJAN也能跑满。主要是能用CDN

**Comment by 31415926pai** [comment]
其实大部分人不会纠结选择哪一个，用路由器的因为存储不够，会纠结选择哪个。

**Comment by shu0802** [comment]
支持更新

**Comment by lqhorochi** [comment]
直接支持更新Trojan Go吧....稳如狗...

**Comment by ywyha** [comment]
大佬，快点替换啊，等好久了……

**Comment by xmapst** [comment]
支持更新

**Comment by pop2006** [comment]
为什么不支持呢？编译的时候完全可以自己选择啊。

**Comment by wujunze** [comment]
可以加一个，让用户选

**Comment by ywyha** [comment]
@coolsnowwolf  大佬，我看已经加入了trajon-go 可是 MUX选项怎么没有了？……

**Comment by ywyha** [comment]
问下大家的trajon-go的MUX选项 还在吗……
