### ISSUE TITLE
请教一下，最新版刷固件的问题

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#5872]
路由器：小米路由器 3G
处理器：MT7621A
ROM：128MB SLC Nand Flash
内存：256MB DDR3-1200

11月的版本，32M固件，刷入正常，今天编译了最新版，有36M大小，使用PuTTY刷入错误，日志如下：

root@XiaoQiang:~# mtd write /tmp/openwrt-ramips-mt7621-xiaomi_mir3g-squashfs-rootfs0.bin rootfs0
Unlocking rootfs0 ...
Writing from /tmp/openwrt-ramips-mt7621-xiaomi_mir3g-squashfs-rootfs0.bin to rootfs0 ...  [e]Failed to erase block

各位高手能指点下不，是否固件太大还是什么原因，感谢！

**Comment by ihuaer** [comment]
你的固件要小于32M 才可以刷入

**Comment by jxph1123** [comment]
我有128MB的 Flash也不能刷大于32M的固件吗

**Comment by coolsnowwolf** [comment]
不能的，小米分区就是 32MB

**Comment by jxph1123** [comment]
谢谢大佬，看来我得精简下了。。
