### ISSUE TITLE
用最新版编译的时候，ssr+安装包怎么没有了

### ISSUE THREAD

**Issue by sealincn** [coolsnowwolf/lede#5875]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
用最新版编译的时候，ssr+安装包怎么没有了
### (1) 具体问题
用最新版编译的时候，ssr+安装包怎么没有了
A：

### (2) 路由器型号和固件版本
nanopi-r4s，gitclone最新版lede
A：

### (3) 详细日志
配置菜单的软件包选择里没有ssr plus了
A：

**Comment by jjit** [comment]
修改 feeds.conf.default 文件，去掉 helloworld 前面的 #
然后运行 ./scripts/feeds update -a
./scripts/feeds install -a

**Comment by Ljzkirito** [comment]
```
cd lede
sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default
./scripts/feeds update -a && ./scripts/feeds install -a
```

**Comment by sealincn** [comment]
十分感谢
