### ISSUE TITLE
关于ShadowSocksR Plus+选择某些SS服务会出现“ssr redir tcp error.restart!”无法启动的临时解决办法

### ISSUE THREAD

**Issue by caicaicai21** [coolsnowwolf/lede#5877]
经过排查，是subscribe.lua获取订阅之后处理插件参数出现问题，参数不完整导致obfs-local无法启动
修复办法，修改/usr/share/shadowsocksr/subscribe.lua第194行~197行如下图所示
![屏幕截图 2020-12-04 152823](https://user-images.githubusercontent.com/26214093/101134582-95467c80-3645-11eb-8269-e84eec53b328.png)
原来的代码部分：
```
for _, v in pairs(split(query[2], '&')) do
	local t = split(v, '=')
	params[t[1]] = t[2]
end
```
修改后代码部分：
```
for _, v in pairs(split(query[2], '&')) do
	if v:find("plugin") == 1 then
		local idx_pn = v:find("=")
		params[v:sub(1, idx_pn - 1)] = v:sub(idx_pn + 1, #v)
	else
		local t = split(v, '=')
		params[t[1]] = t[2]
	end
end
```
如果你的有类似的问题，可以按照以上内容修改(建议备份原文件，以免出错)。如果你没有类似问题，建议不要修改。
*因为是临时的解决方案，所以暂时没有提交。

**Comment by Cathgao** [comment]
反馈错地方了

**Comment by caicaicai21** [comment]
> 反馈错地方了

那边应该没人看吧。。。
