### ISSUE TITLE
新拉取的，无法MAKE

### ISSUE THREAD

**Issue by souwei168** [coolsnowwolf/lede#5879]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by souwei168** [comment]
新拉取的，无法 MARK

**Comment by EnnawYang** [comment]
然后呢

**Comment by souwei168** [comment]
编译一直报错，晚点我再仔细测试！



服务热线：

137-2867-5839

&nbsp;

QQ:452075208

E-mail：452075208@qq.com

地址：深圳市福田区华强北路与振华路交汇处现代之窗B座28F


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coolsnowwolf/lede"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 上午9:26
收件人:&nbsp;"coolsnowwolf/lede"<lede@noreply.github.com&gt;;
抄送:&nbsp;"深圳市宏顺欣网科技有限公司"<452075208@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] 新拉取的，无法MAKE (#5879)





 
然后呢

**Comment by saltfishh** [comment]
提issue能把环境 log贴出来吗？
就是linus也帮不了你
