### ISSUE TITLE
在纯ipv6环境下 无法通过ssr进行代理

### ISSUE THREAD

**Issue by ChowhaoHQD** [coolsnowwolf/lede#589]
最近运营商开通了ipv6  在路由下能正常获得ipv6地址 。pc端也能获取ipv6。 但是关闭pc端的ipv4协议只用纯v6 环境下无法访问google等网站（不经过ssr ，直连）。在ipv4下正常。请问下需要怎样设置才能在纯v6 环境下经过ssr访问（梯子支持双栈）。
固件版本	OpenWrt R7.7.4 By Lean / LuCI Master (git-18.211.72541-26bbd01)
内核版本	4.14.48
luci-app-ssr-pro	2-28

**Comment by XiGou** [comment]
请问您解决了吗？或者哪个老版本能够正常使用，希望告知。多谢

**Comment by kob** [comment]
这是因为你的ssr服务器不支持V6 吧
