### ISSUE TITLE
找不到腾达AC9的DTS .patch哎？

### ISSUE THREAD

**Issue by AuroraTea** [coolsnowwolf/lede#5893]
* [x] 没有类似的issue

因为是64M ram的，想修改DTS进行编译，但是找不到腾达AC9的DTS哎
话说“031-v4.21-0003-ARM-dts-BCM53573-Relicense-Tenda-AC9-file-to-the-GPL”为什么这个GPL的名字里是BCM53573，它和AC9的BCM47189是什么关系哦~~
感觉BCM的目录和MT相差好大啊

腾达ac9

**Comment by fishtorres** [comment]
博通就不用想了
没驱动的
