### ISSUE TITLE
K2P的WIFI的新界面无法使用英文单词作为密码

### ISSUE THREAD

**Issue by Iy204** [coolsnowwolf/lede#5898]
使用单词密码框直接红，无法保存。

**Comment by AmadeusGhost** [comment]
update feeds 了？

**Comment by KNedwin** [comment]
@AmadeusGhost 我更新 feeds后编译成功开启了wifi，发现 ra0 和rax0接口颠倒了。然后就是无法修改5g网络的信道。

只能用默认的36信道，修改配置文件里的参数到161就算重启也没效果。

**Comment by AmadeusGhost** [comment]
@KNedwin 之前测试的时候是有这些问题，等有空的时候慢慢修正吧😂

**Comment by KNedwin** [comment]
好吧，至少能用😂

**Comment by KNedwin** [comment]
@AmadeusGhost 还有为啥修改ssid保存后，整个wifi就没了呢？  提示：无线未开启或未关联

**Comment by KNedwin** [comment]
或者我该如何编译才能换成原来的闭源驱动界面。。。

**Comment by AmadeusGhost** [comment]
> 还有为啥修改ssid保存后，整个wifi就没了呢？ 提示：无线未开启或未关联

不清楚你那啥情况。。。
> 我该如何编译才能换成原来的闭源驱动界面

git revert 13ec6bcfd6e9d7f3aeb115fb2786d249c7a9e95a

**Comment by Iy204** [comment]
> 
> 
> update feeds 了？

那天使用的就是当天编译的。
今天再编译已经没有问题了，感谢。
