### ISSUE TITLE
请教一下编译斐讯K3固件屏幕显示和adbyby plus问题

### ISSUE THREAD

**Issue by Saimen-Luo** [coolsnowwolf/lede#59]
首先感谢lean大开源该代码，我编译了k3的固件，有两个问题解决不了。
一是屏幕无法正常显示，编译时选择了k3screenctrl 还是不行
![screen1](https://user-images.githubusercontent.com/31783769/30519855-f68e375a-9bd2-11e7-8130-d4e0f44cad00.PNG)
![screen2](https://user-images.githubusercontent.com/31783769/30519856-f6caf5dc-9bd2-11e7-8ba0-00765129bad9.PNG)

二是adbyby plus规则一直无法更新，也过滤不了广告
![adbyby](https://user-images.githubusercontent.com/31783769/30519864-2a94724e-9bd3-11e7-8ef2-89854b39501b.PNG)
![adbyby2](https://user-images.githubusercontent.com/31783769/30519865-2b923e10-9bd3-11e7-8c72-a59054930e17.PNG)

还请不吝赐教！

**Comment by tomerilery** [comment]
adbyby服务器被未知力量攻击了，请手动更新，ssh到路由，执行指令/usr/share/adbyby/adupdate.sh

**Comment by Saimen-Luo** [comment]
@tomerilery 执行命令后规则更新了，adbyby是招谁惹谁了吗？还有你知道屏幕问题怎么解吗？现在是屏幕一直停留在开机界面，一直亮着。

**Comment by gavin219** [comment]
因为没有配置k3screenctrl

**Comment by Saimen-Luo** [comment]
可否细说一下配置方法，是这个luci吗？[https://github.com/Hill-98/luci-app-k3screenctrl](url) @gavin219

**Comment by coolsnowwolf** [comment]
closed 的 issues 里面有写，认真看

**Comment by Saimen-Luo** [comment]
OK，lean大最好在readme标明一下，像我一样不看closed 的 issues的人估计不少。
