### ISSUE TITLE
请问2.4Gwifi，5Gwifi，网口驱动分别是哪几个安装包？

### ISSUE THREAD

**Issue by logernLee** [coolsnowwolf/lede#5900]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：请问2.4Gwifi，5Gwifi，网口驱动分别是源码里面的哪几个安装包？

### (2) 路由器型号和固件版本

A：竟斗云 IPQ4019

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
无线是 kmod-ath10k-ct 和 ath10k-firmware-qca4019-ct，有线的不是软件包

**Comment by logernLee** [comment]
好的    感谢回复

**Comment by logernLee** [comment]
请问这个wifi没有加载上是什么情况呢？
![2Z`D4AU3Q19ZAN{8BPPCIL2](https://user-images.githubusercontent.com/32033997/101713854-73307c80-3ad3-11eb-846a-219527f346bb.png)

**Comment by AmadeusGhost** [comment]
> 请问这个wifi没有加载上是什么情况呢？

选上 ipq-wifi-p2w_r619ac

**Comment by logernLee** [comment]
你好，这个选项已经是选上的。
![@MA6%YKMUM@@WQW Q82095](https://user-images.githubusercontent.com/32033997/101735462-e6021d80-3afc-11eb-80c2-f18ddafe1d32.png)

**Comment by AmadeusGhost** [comment]
看了下日志，你这机子不是竞斗云吧？

**Comment by logernLee** [comment]
板子确实是竟斗云的，外壳上都写着竟斗云，里面默认固件登录进去也是竟斗云的界面。但是就是不知道为啥会出现这个问题--

**Comment by logernLee** [comment]
板子确实是竟斗云的，外壳上都写着竟斗云，里面默认固件登录进去也是竟斗云的界面。但是就是不知道为啥会出现这个问题--

**Comment by AmadeusGhost** [comment]
你试试我编译的固件：https://ws28.cn/f/46ug3eh07se

**Comment by logernLee** [comment]
这个还是有点小问题。。
![XM7ZYD)7R3~GHD$SHKE68{C](https://user-images.githubusercontent.com/32033997/101761310-f0311580-3b16-11eb-9919-c8e9fa398f53.png)

**Comment by logernLee** [comment]
fetch board file的时候开始报错，我的是一开始加载就报错了 。。
