### ISSUE TITLE
GFW列表模式和绕过大陆IP模式

### ISSUE THREAD

**Issue by hekang26** [coolsnowwolf/lede#5907]
使用GFW列表模式无法正常访问网站
使用绕过大陆IP模式没有问题 , 如果使用此方式 , 强制代理和强制不走代理规则列表无法生效  已反复测试过  

访问控制功能完全无法使用

望大佬解答下

**Comment by NagaseKouichi** [comment]
试试运行ipconfig /flushdns

一般过段时间就自己好了

**Comment by hekang26** [comment]
> 试试运行ipconfig /flushdns
> 
> 一般过段时间就自己好了

ipconfig /flushdns  这个命令是win系统的强制刷新DNS命令   跟SSR+的列表规则无关吧?

**Comment by NagaseKouichi** [comment]
我也是GFW列表模式刚开始打不开被墙的网站，不管他过段时间就好了

**Comment by hekang26** [comment]
> 我也是GFW列表模式刚开始打不开被墙的网站，不管他过段时间就好了

十分感谢  兄弟

**Comment by hekang26** [comment]
> 我也是GFW列表模式刚开始打不开被墙的网站，不管他过段时间就好了

大概多久?

**Comment by NagaseKouichi** [comment]
大概一两个小时吧，具体不是很确定

**Comment by hekang26** [comment]
> 大概一两个小时吧，具体不是很确定

那还不如直接更换规则  然后直接重启试试呢...?

**Comment by hekang26** [comment]
> > 大概一两个小时吧，具体不是很确定
> 
> 那还不如直接更换规则 然后直接重启试试呢...?

**Comment by hekang26** [comment]
> > > 大概一两个小时吧，具体不是很确定
> > 
> > 
> > 那还不如直接更换规则 然后直接重启试试呢...?
