### ISSUE TITLE
新版无法忽略TLS地址了？

### ISSUE THREAD

**Issue by ixxmu** [coolsnowwolf/lede#5909]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

###具体问题

同样的v2ray配置ssr plus在路由器无法正常启用了！

最近的ssr plus在配置v2ray时，必须加上TLS域名才能正常启动，之前TLS域名和地址一样时是TLS参数可以留空的。
填上TLS域名之后延迟似乎增加了？

**Comment by xiaobaishu1** [comment]
TLS不用勾上啊！反正我不勾上能用；勾上不想填？
