### ISSUE TITLE
GFW模式不可用

### ISSUE THREAD

**Issue by hekang26** [coolsnowwolf/lede#5910]
GFW模式不可用,绕过大陆IP模式可用

使用GFW模式会打不开任何网站
使用绕过大陆IP模式会导致访问控制功能失效,白名单和黑名单添加网址都不起效

请问如何解决?望大佬指教

**Comment by minlang112** [comment]
你需要先去更新gfw list……

**Comment by hekang26** [comment]
> 你需要先去更新gfw list……

肯定更新过了  显示一万条数据

**Comment by datout** [comment]
一样gfw失效

**Comment by yes2003** [comment]
同gfw无效

**Comment by yes2003** [comment]
Turbo ACC 网络加速 里关掉 DNS加速，貌似好了

**Comment by H0ypothesis** [comment]
我也遇到了这个问题，好像是adbyby与ssr冲突的问题，实测卸载adbyby可以解决问题，但是想要既科学上网又避免广告问题，请问怎么办？
