### ISSUE TITLE
最新源码报错！求解！

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#5913]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：Patch failed!  Please fix /home/kevin/lede/target/linux/rockchip/patches-5.4/200-rockchip-add-support-for-NanoPi-R4S.patch!
Makefile:26: recipe for target '/home/kevin/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.4.79/.prepared_bd725d773a149971bc6c006d25e9f8ec' failed

**Comment by Elletear** [comment]
#5911 已有相关issue

**Comment by d975xbx** [comment]
感谢解答

**Comment by tl768** [comment]
已经修复了
