### ISSUE TITLE
当前版本无法订阅和导入VMESS(V2RAY)配置

### ISSUE THREAD

**Issue by Fddh2012** [coolsnowwolf/lede#5924]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：V2RAY订阅后节点类型被配置成是SSR，也无法通过新建来导入单一节点。 日志中能识别到是V2RAY节点，但节点配置里却是SSR。

### (2) 路由器型号和固件版本

A：X86 OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)

### (3) 详细日志

A：无

**Comment by xiaobaishu1** [comment]
这应该不算BUG吧！你应该是故意给它找点事让它不干活！

**Comment by Ljzkirito** [comment]
可以去[这里](https://github.com/fw876/helloworld/issues)反馈

**Comment by xtwz** [comment]
同样遇问题，订阅V2RAY后，无法运行。之前版本可以

**Comment by RA089** [comment]
V2RAY订阅后节点类型被配置成是SSR，无法启动运行，改回vmess才能启动

**Comment by Fddh2012** [comment]
> V2RAY订阅后节点类型被配置成是SSR，无法启动运行，改回vmess才能启动

我改回vmess去，好像配置细节会丢失，启动不起来。
