### ISSUE TITLE
不知道这是我的个例吗？

### ISSUE THREAD

**Issue by zhaocz086** [coolsnowwolf/lede#597]
check_data_file_clashes: Package shadowsocksr-libev-alt wants to install file /home/zcz/lede_lean/build_dir/target-i386_pentium4_musl/root-x86/usr/bin/ssr-redir
        But that file is already provided by package  * shadowsocksr-libev
 * opkg_install_cmd: Cannot install package shadowsocksr-libev-alt.

**Comment by fy1128** [comment]
冲突。ss 的话，我个人选择了 `shadowsocksr-libev`

所以去掉了 `shadowsocksr-libev-alt` 

包括对应的luci app.
