### ISSUE TITLE
AC58U 8.1.6版本 手机离路由器超过1M后5G就无法连接

### ISSUE THREAD

**Issue by wspzf** [coolsnowwolf/lede#598]
测试过华为mata9和iPhone7，单独开启5G wifi 都一样出现手机离路由器超过1M后5G就无法连接
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2450345/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2450346/default.txt)

**Comment by coolsnowwolf** [comment]
进入 lede 目录后，rm .config 再选择 ac58u 编译一次，内核日志看不到什么问题

**Comment by hcym** [comment]
是的，不行，完全和以前不同。不清楚怎么回事？

**Comment by wspzf** [comment]
编译器就删除过.config和tmp

**Comment by hcym** [comment]
明天继续，看到大佬正在put，但愿信号恢复正常范围

**Comment by wspzf** [comment]
连夜git pull后编译，无线终于正常了，爽歪歪，感谢大雕
