### ISSUE TITLE
部分订阅链接无法获取到列表

### ISSUE THREAD

**Issue by 450717565** [coolsnowwolf/lede#601]
部分订阅链接无法获取到列表，且点击更新按钮后，SSRP会变成没有启用的状态。

http://111.222.333.444/subscribe.php?i=xgfancz&t=ea254c183d177079aaef7bf839f1baf7

主机型号	ASUS RT-ACRH17
固件版本	OpenWrt R8.1.6 By Lean / LuCI openwrt-18.06 branch (git-18.138.53009-80cb4fe)
内核版本	4.14.74

[内核日志10.06.txt](https://github.com/coolsnowwolf/lede/files/2451211/10.06.txt)
[系统日志10.06.txt](https://github.com/coolsnowwolf/lede/files/2451212/10.06.txt)

**Comment by SkyMonkya** [comment]
![image](https://user-images.githubusercontent.com/23414204/46547253-f22b3880-c8fd-11e8-8e29-30f32fe01119.png)

**Comment by shijiancat** [comment]
多用别的订阅链接测试几次  会不会是有些连接失效了
