### ISSUE TITLE
socks 5 全局代理无法启动和正常使用

### ISSUE THREAD

**Issue by dlj390** [coolsnowwolf/lede#6033]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
没有
## 2. 详细叙述
编译最新固件后，Socks 5 全局代理无法正常使用。
### (1) 具体问题

A：2020-12-15 07:43:03 global socks server error.restart!

### (2) 路由器型号和固件版本

A：X86，最新固件版本

### (3) 详细日志

A：2020-12-15 07:43:03 global socks server error.restart!

**Comment by dlj390** [comment]
大家没有同样的问题吗?

**Comment by NagaseKouichi** [comment]
我也有同样的问题

**Comment by dlj390** [comment]
大神们是否能够尽快解决下？？

**Comment by NagaseKouichi** [comment]
> 大神们是否能够尽快解决下？？

https://github.com/fw876/helloworld/pull/285
我看已经解决了，等合并代码吧

**Comment by NagaseKouichi** [comment]
代码合并了，我开始编译了
