### ISSUE TITLE
可以支持新款的mt7621a cpu的路由吗

### ISSUE THREAD

**Issue by rockey2020** [coolsnowwolf/lede#6037]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：glinet 品牌下的 mt1300 路由

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
建议先寄一台机子给开发者再谈会不会支持

**Comment by victoratmaoludotone** [comment]
正好我也刚买了这个。尝试在glinet源码的config中加入ssr的git，编译不成功，不知道咋搞了。。

**Comment by rockey2020** [comment]
openwrt官方已经支持mt1300   lede啥时候可以同步支持呢?

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=d89a7f0120db42d4fae1656e1860ef49523acabb

@hauke @victoratmaoludotone @ynezz @jesset

**Comment by rockey2020** [comment]
@victoratmaoludotone https://downloads.openwrt.org/snapshots/targets/ramips/mt7621/  最新的openwrt预览版支持了
