### ISSUE TITLE
softethervpn异地组网问题

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#6041]
A路由softethervpn开启设置完成后，手机，PC均可使用，怎么在B路由上通过VPN连接上A路由组网呢？
![1](https://user-images.githubusercontent.com/61616502/102330793-f4e94400-3fc4-11eb-9b5e-37acf646f9b4.jpg)

**Comment by onetown** [comment]
softether支持hub和hub的集联, 集联是用的softether自己的ssl vpn协议。
