### ISSUE TITLE
dsmboot如何使用的问题

### ISSUE THREAD

**Issue by sxf5487** [coolsnowwolf/lede#6046]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：我想请问下是否是勾选network下的dsmboot即可，看代码里是5.2的引导，是否可以手动替换成更高版本，非常感谢！

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hxlls** [comment]
使用很简单，首先在网络 dhcp/dns 里面设置tftp 开启，设置对应的文件夹和路径，然后需要网络启动的设备开启PXE就行了
![image](https://user-images.githubusercontent.com/43886952/102696509-e7a0b380-4269-11eb-896c-7eb09b7b47f6.png) 这个是网络引导的效果

**Comment by sxf5487** [comment]
谢谢！
