### ISSUE TITLE
我想把qcawifi编译进系统需要怎么做呢？

### ISSUE THREAD

**Issue by logernLee** [coolsnowwolf/lede#6048]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：我想把qcawifi编译进这个源码里面，由于技术有限，总是编译不成功，请问可以指导一下吗？因为选取里面自带的驱动总是不能驱动wifi

### (2) 路由器型号和固件版本

A：IPQ4019

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
要移植过来的，建议还是拿 lede 17.01 (kernel 4.4) 移植

**Comment by logernLee** [comment]
好的   谢谢  我先试试
