### ISSUE TITLE
V2ray 内存占用过大，运行一段时间后系统崩溃重启

### ISSUE THREAD

**Issue by wspzf** [coolsnowwolf/lede#605]
环境：
型号：AC58U
编译的功能组件：在默认基础上增加了一个主题和V2ray，去掉了VPN、USB打印、FTP、迅雷。
开启V2ray后 V2ray的VSZ超过了780M，
![screenshot_20181006-002444](https://user-images.githubusercontent.com/43857401/46565685-8e782e00-c944-11e8-95b1-af536a9da19a.jpg)

系统负载也非常高，
![default](https://user-images.githubusercontent.com/43857401/46565683-87512000-c944-11e8-98b6-ac3cc761294d.jpg)

运行一段时间后路由器自动重启，周期几分钟到2小时不等。
前几个版本也有一样的情况。

[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2452609/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2452610/default.txt)

**Comment by hcym** [comment]
我的是换了搬瓦工后就不能连接，以前的heroku都可以，即使用友华的跑也正常。

**Comment by ewangsoft** [comment]
这个v2ray虚拟内存问题还没处理吗，之前用这个v2，有解决：https://github.com/kuoruan/luci-app-v2ray/commit/39be0f8554c779ad2146b008a2e72411331528ba
建议有能力的帮忙解决下吧
