### ISSUE TITLE
可以参照杂交r2s的方法编译r4s   我已经编译成功了，并在官方固件ubuntu core的docker中也可以运行了，放到v2ex上各种说怕投毒的，说原版openwrt最好的，叨逼叨半天，，就不放固件了，自己编译

### ISSUE THREAD

**Issue by wifiway520** [coolsnowwolf/lede#6051]
可以参照杂交r2s的方法编译r4s   我已经编译成功了，并在官方固件ubuntu core的docker中也可以运行了，放到v2ex上各种说怕投毒的，说原版openwrt最好的，叨逼叨半天，，就不放固件了，自己编译

_Originally posted by @programmejava in https://github.com/coolsnowwolf/lede/issues/6038#issuecomment-745628040_

**Comment by AmadeusGhost** [comment]
转发过来你想表达什么？？？

**Comment by uioasder** [comment]
???解决问题的地方你当论坛呢？
