### ISSUE TITLE
无规律重启重开一贴

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#6055]
反馈bug/问题模板，提建议请删除

1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
原帖被顶太远了，现在也没有统一的解决办法，所以关闭原帖重开一个。寻求帮助。
原帖：https://github.com/coolsnowwolf/lede/issues/5349
2. 详细叙述
(1) 具体问题
A：X64。3215U，每天无规律重启1次以上，也许有规律，但我没抓到。刷回R20.7.1之前的版本没问题。

(2) 路由器型号和固件版本
A：X64。3215U

(3) 详细日志
A：无，重启丢失

**Comment by NagaseKouichi** [comment]
我关了SFE之后最近没重启了，希望L大能解决一下

**Comment by sxx1314** [comment]
[解决办法 #5349](https://github.com/coolsnowwolf/lede/issues/5349#issuecomment-708977359)

**Comment by binge8** [comment]
确实关闭SFE搞定
