### ISSUE TITLE
 IPQ40xx 超频到 896MHz 稳定性调查反馈

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#6064]
新引入了一个超频的补丁，针对 IPQ40xx 的架构

![image](https://user-images.githubusercontent.com/31687149/102706881-bdcea780-42d0-11eb-9959-9c76c553e768.png)

运行了2天还是挺稳定的，跑分也超过了 1万分，XXR Plus 性能居然也同步增加了 25% ，xray 现在超频arch17 也能 180Mbps+ 了

大家使用该补丁感觉如何？ 欢迎反馈

**Comment by luckyyyyy** [comment]
手上有一台精斗云，丢掉wifi的话就可以刷和这个了。

**Comment by star-o0O** [comment]
用了一天，感觉还是挺稳的，只是状态页的两个温度不显示了，也不知道发生了什么，刚刷上的时候还是有的。

**Comment by yinzhefuyun** [comment]
> 用了一天，感觉还是挺稳的，只是状态页的两个温度不显示了，也不知道发生了什么，刚刷上的时候还是有的。

2.4Gwifi和5Gwifi打开一个显示一个温度

**Comment by gw826943555** [comment]
> 用了一天，感觉还是挺稳的，只是状态页的两个温度不显示了，也不知道发生了什么，刚刷上的时候还是有的。

无线打开了吗 无线打开才会显示温度

**Comment by hcym** [comment]
ac58试试看看，应该可以吧？回头反馈信息

**Comment by mcucore** [comment]
建议别超频了，体质有差异，路由设备稳定第一！需求更高换硬件！

**Comment by NagaseKouichi** [comment]
IPQ40xx有硬件NAT加速么

**Comment by hcym** [comment]
温度高，刷原厂固件做ap了😂

**Comment by mcucore** [comment]
> 温度高，刷原厂固件做ap了😂

为啥原厂，雕多啦不是挺稳定！

**Comment by Cathgao** [comment]
用了两天，目前没发现问题，也没觉得有什么体验改进，因为本来性能就够用了

**Comment by zhang5389** [comment]
用了一天，功能正常，温度稳定。

**Comment by carrneverrun** [comment]
> 手上有一台精斗云，丢掉wifi的话就可以刷和这个了。

筋斗云刷这个系统会使WiFi无效么?

**Comment by yinzhefuyun** [comment]
> > 手上有一台精斗云，丢掉wifi的话就可以刷和这个了。
> 
> 筋斗云刷这个系统会使WiFi无效么?

并不会，他只是不想用无线，所以去掉了WiFi（关闭）

**Comment by xfmly** [comment]
4.14.202，竞斗云43.0°C 44.0°C
5.4，星际宝盒79.0°C 80.0°C
稳定使用

**Comment by hzjnet** [comment]
> 4.14.202，竞斗云43.0°C 44.0°C
> 5.4，星际宝盒79.0°C 80.0°C
> 稳定使用

补充下吧：
主机型号 | ASUS RT-ACRH17 (CpuMark : 9704.174311 Scores)
架构        | ARMv7 Processor rev 5 (v7l) x 4 (896MHz, 59.0°C 59.0°C)
内核版本 | 5.4.79

不知道4.4版本如何弄？要是哪位出个补丁就好了

**Comment by au3300** [comment]
正常使用，稳定！！！
![1](https://user-images.githubusercontent.com/45656560/103115292-ff7a9c00-469c-11eb-8374-81943367cfec.png)

**Comment by xfmly** [comment]
> > 4.14.202，竞斗云43.0°C 44.0°C
> > 5.4，星际宝盒79.0°C 80.0°C
> > 稳定使用
> 
> 补充下吧：
> 主机型号 | ASUS RT-ACRH17 (CpuMark : 9704.174311 Scores)
> 架构 | ARMv7 Processor rev 5 (v7l) x 4 (896MHz, 59.0°C 59.0°C)
> 内核版本 | 5.4.79
> 
> 不知道4.4版本如何弄？要是哪位出个补丁就好了

P&W R619AC 128M (CpuMark : 10225.929122 Scores)
ARMv7 Processor rev 5 (v7l) x 4 (896MHz, 45.0°C 44.0°C)

**Comment by coolsnowwolf** [comment]
看来还是竞斗云散热好啊

**Comment by asushugo** [comment]
> 看来还是竞斗云散热好啊

![image](https://user-images.githubusercontent.com/18640537/103137315-e4427780-4702-11eb-83e6-c057befc857b.png)
我适配的这个 AP 也很稳定哦

**Comment by ZGNCZMY** [comment]
使用一个星期，稳如狗~

**Comment by ZGNCZMY** [comment]
忘了说设备acrh17

**Comment by kilo1220** [comment]
该功能如何启用？为啥我的acrh17还是显示717MHz

**Comment by asushugo** [comment]
> 该功能如何启用？为啥我的acrh17还是显示717MHz

![image](https://user-images.githubusercontent.com/18640537/103436888-b659b780-4c5b-11eb-9b90-60aa1f4ea530.png)

**Comment by ZGNCZMY** [comment]
> 
> 
> 该功能如何启用？为啥我的acrh17还是显示717MHz

有老兄给你截图了

**Comment by kilo1220** [comment]
> > 该功能如何启用？为啥我的acrh17还是显示717MHz
> 
> ![image](https://user-images.githubusercontent.com/18640537/103436888-b659b780-4c5b-11eb-9b90-60aa1f4ea530.png)

感谢~~

**Comment by kilo1220** [comment]
> > 该功能如何启用？为啥我的acrh17还是显示717MHz
> 
> 有老兄给你截图了

感谢~~

**Comment by moqingzhu1** [comment]
现在编译怎么是4.19版，是我编译的问题还是代码问题，同步的大神源码，新手不懂就问，勿喷

**Comment by OPA2604** [comment]
![Uploading 17155271-E955-4FBF-858F-98C3FAD0B171.png…]()

现在室内16度。

**Comment by OPA2604** [comment]
![140A7B1C-8128-4F91-A4BE-B39F56B9D238](https://user-images.githubusercontent.com/70869445/104030779-dca4c780-5206-11eb-93bd-01604a29f952.png)

**Comment by lenghun** [comment]
别折腾超频了,路由稳定优先,如果有需要多这点性能的情况说明是很高负载超频了反而会出各种问题,退一万步讲你真的需要那进breed超不好吗,

**Comment by AmadeusGhost** [comment]
> 别折腾超频了,路由稳定优先,如果有需要多这点性能的情况说明是很高负载超频了反而会出各种问题,退一万步讲你真的需要那进breed超不好吗,

arm 平台的 CPU 工作频率是可以手动更改的，本身固件也是默认频率启动的，稳得一批。再说了 arm 平台哪来的 breed ，，

**Comment by yinzhefuyun** [comment]
> 别折腾超频了,路由稳定优先,如果有需要多这点性能的情况说明是很高负载超频了反而会出各种问题,退一万步讲你真的需要那进breed超不好吗,

默认启动是默认频率，你要进系统，在cpu控制那里再调高频率才可以

**Comment by Marcotso** [comment]
> 看来还是竞斗云散热好啊

老大,铁盒不是盖的

**Comment by 467815891a** [comment]
![image](https://user-images.githubusercontent.com/16792048/105621522-41853200-5e43-11eb-9ed3-950014d4a3e4.png)
星际宝盒散热真的捉鸡，散热片换了还这样。

**Comment by sgsgsg520** [comment]
能不能超个1.2 g

**Comment by Cathgao** [comment]
![QQ截图20210508225207](https://user-images.githubusercontent.com/21031564/117543588-115b4b00-b050-11eb-9969-d782ef501c07.png)
空调房，铁盒子摸起来不温，温度没导到外壳上
