### ISSUE TITLE
建议增加openfortivpn

### ISSUE THREAD

**Issue by pham38** [coolsnowwolf/lede#6065]
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

能否考虑增加openfortivpn?

通过openwrt.org安装openfortivpn可以使用，但此源码luci不支持此协议的接口配置，能否考虑增加？

https://github.com/openwrt/packages/tree/master/net/openfortivpn

https://github.com/openwrt/luci/tree/master/protocols/luci-proto-openfortivpn

**Comment by xiaobaishu1** [comment]
trojan-go都没搞上去这个估计没戏

**Comment by mcbbsandnz** [comment]
现在trojan-go都还在讨论加不加上去,这个还是再等等吧
