### ISSUE TITLE
X86 没有switch选项

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#6071]
Hi Team,

今天编译X86 固件发现没有switch 选项
![no_switch](https://user-images.githubusercontent.com/25215114/102764308-ec727e00-43b5-11eb-9c33-1d812b325765.png)

但是我看到里面接口是有的
![接口2](https://user-images.githubusercontent.com/25215114/102764464-23489400-43b6-11eb-9087-266354b43c52.png)

这个需要怎么操作，在编译的时候，需要添加哪个包

BR
Robin

**Comment by luckyyyyy** [comment]
vlan 用 eth1.XX 这样来模拟

X86没有交换机 都是独立网口

**Comment by Guxing0321** [comment]
Hi luck，

你好，我这边有个需求，是需要将软路由的其他三个lan的口，划成不同的网段，

**Comment by Guxing0321** [comment]
Hi luck，

你好，我这边有个需求，是需要将软路由的其他三个lan的口，划成不同的网段
之前用的是newifi3 d2，里面通过交换机打tag,现在换了软路由，需要怎么设置


BR
Robin

**Comment by luckyyyyy** [comment]
自定义接口 eth1.x 2.x 3.x 其实就是vlan

**Comment by Guxing0321** [comment]
Hi luckyyyyy,

好的，我明白了，

谢谢

BR
Robin
