### ISSUE TITLE
ShadowSocksR PLUS+ 日志一支报下面错误，且时间长了PPPOE也会重新拨号

### ISSUE THREAD

**Issue by gzjacktang** [coolsnowwolf/lede#6074]
x86 软路由 用shadowsocksr plus+翻墙 日志就报下面错误，且时间一长就会导致网络重新拨号

网上搜索了很多包括已有主题，没发现同样问题

具体日志报错如下
Mon Dec 21 22:27:18 2020 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Mon Dec 21 22:27:35 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:27:35 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:27:35 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:27:55 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:27:55 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:27:55 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:28:15 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:28:15 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:28:15 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:28:35 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:28:35 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:28:35 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:28:56 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:28:56 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:28:56 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:29:16 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:29:16 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:29:16 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:29:36 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:29:36 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:29:36 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:29:56 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:29:56 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:29:56 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:30:16 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:30:16 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:30:16 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:30:35 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon Dec 21 22:30:35 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon Dec 21 22:30:37 2020 user.info : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Mon Dec 21 22:30:37 2020 user.err : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Mon Dec 21 22:30:37 2020 user.info : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
Mon Dec 21 22:30:38 2020 daemon.info dnsmasq[8680]: Connected to system UBus
Mon Dec 21 22:30:38 2020 cron.err crond[8714]: crond (busybox 1.31.1) started, log level 5
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9809]: initializing ciphers... aes-128-ctr
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9809]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9809]: listening at 0.0.0.0:1234
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9809]: running from root user
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9811]: initializing ciphers... aes-128-ctr
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9811]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9811]: listening at 0.0.0.0:1234
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9811]: running from root user
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9813]: initializing ciphers... aes-128-ctr
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9813]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9813]: listening at 0.0.0.0:1234
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9813]: running from root user
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9815]: initializing ciphers... aes-128-ctr
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9815]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9815]: listening at 0.0.0.0:1234
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9815]: running from root user
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9893]: initializing ciphers... rc4-md5
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9893]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9893]: listening at 0.0.0.0:4321
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-redir[9893]: running from root user
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-local[9895]: initializing ciphers... rc4-md5
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-local[9895]: tcp port reuse enabled
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-local[9895]: listening at 0.0.0.0:1088
Mon Dec 21 22:30:40 2020 kern.info /usr/bin/ssr-local[9895]: running from root user
Mon Dec 21 22:30:44 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Mon Dec 21 22:30:44 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Mon Dec 21 22:30:47 2020 daemon.info dnsmasq[10164]: Connected to system UBus
Mon Dec 21 22:32:21 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:35:52 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:35:52 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:35:52 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:35:52 2020 kern.err /usr/bin/ssr-redir[9809]: server recv: Connection reset by peer
Mon Dec 21 22:35:52 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:48:58 2020 kern.err /usr/bin/ssr-redir[9813]: server recv: Connection reset by peer
Mon Dec 21 22:48:58 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:48:58 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:58:49 2020 kern.err /usr/bin/ssr-redir[9809]: server recv: Connection reset by peer
Mon Dec 21 22:58:49 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:58:51 2020 kern.err /usr/bin/ssr-redir[9813]: server recv: Connection reset by peer
Mon Dec 21 22:58:51 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9809]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9815]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer
Mon Dec 21 22:59:05 2020 kern.err /usr/bin/ssr-redir[9811]: server recv: Connection reset by peer

刚刚重启了下SSR+，白天的已经全部日志都是这一条了 全是kern.err /usr/bin/ssr-redir[****]: server recv: Connection reset by peer

SSR+ 使用上影响不算很大，SSR+里面日志有没有问题，但是用passwall，或者openclash就没这个报错。

J1900的软路由，求大佬指点

**Comment by jxph1123** [comment]
kern.err /usr/bin/ssr-redir[****]: server recv: Connection reset by peer
我的更新版本后也是这个错误，大概5分钟来次，刷屏了
