### ISSUE TITLE
最新源码K2P  只能拔电源重启，不能软重启

### ISSUE THREAD

**Issue by qjiang888** [coolsnowwolf/lede#6077]
有大佬知道是什么问题吗？？？？？？？

**Comment by SilverHunterLib** [comment]
之前重启之后无法连接路由器的问题还有吗？

**Comment by yulinsoft** [comment]
youku-yk1也有这个问题，换成4.14的内核就可以了，5.4的内核没添加重启补丁，我自己也不会做补丁。

**Comment by chenliangxin** [comment]
> youku-yk1也有这个问题，换成4.14的内核就可以了，5.4的内核没添加重启补丁，我自己也不会做补丁。
我的miwifi-mini也想换4.14。Makefile里面的5.4我已改成4.14，配置文件也有。但编译时一直报错

**Comment by chenliangxin** [comment]
> youku-yk1也有这个问题，换成4.14的内核就可以了，5.4的内核没添加重启补丁，我自己也不会做补丁。

我的miwifi-mini也想换4.14。Makefile里面的5.4我已改成4.14，配置文件也有。但编译时一直报错
