### ISSUE TITLE
release20200408 编译报错

### ISSUE THREAD

**Issue by qingcheng3w** [coolsnowwolf/lede#6080]
### (1) 具体问题

A：Package ip-full is missing dependencies for the following libraries:
libcap.so.2 

### (2) 路由器型号和固件版本
小米mir3g-v2 
A：

### (3) 详细日志

A：make[3]: Leaving directory '/home/xf/lede/package/libs/elfutils'
time: package/libs/elfutils/compile#0.12#0.06#0.29
make[3]: Entering directory '/home/xf/lede/package/network/utils/iproute2'
mkdir -p /home/xf/lede/bin/targets/ramips/mt7621/packages /home/xf/lede/build_dir/target-mipsel_24kc_musl/iproute2-full/iproute2-5.0.0/ipkg-mipsel_24kc/ip-full/CONTROL /home/xf/lede/staging_dir/target-mipsel_24kc_musl/pkginfo
install -d -m0755 /home/xf/lede/build_dir/target-mipsel_24kc_musl/iproute2-full/iproute2-5.0.0/ipkg-mipsel_24kc/ip-full/usr/libexec
install -m0755 /home/xf/lede/build_dir/target-mipsel_24kc_musl/iproute2-full/iproute2-5.0.0/ip/ip /home/xf/lede/build_dir/target-mipsel_24kc_musl/iproute2-full/iproute2-5.0.0/ipkg-mipsel_24kc/ip-full/usr/libexec/ip-full
find /home/xf/lede/build_dir/target-mipsel_24kc_musl/iproute2-full/iproute2-5.0.0/ipkg-mipsel_24kc/ip-full -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package ip-full is missing dependencies for the following libraries:
libcap.so.2
Makefile:202: recipe for target '/home/xf/lede/bin/packages/mipsel_24kc/base/ip-full_5.0.0-1_mipsel_24kc.ipk' failed
make[3]: *** [/home/xf/lede/bin/packages/mipsel_24kc/base/ip-full_5.0.0-1_mipsel_24kc.ipk] Error 1
make[3]: Leaving directory '/home/xf/lede/package/network/utils/iproute2'
time: package/network/utils/iproute2/full/compile#0.12#0.07#0.44
package/Makefile:111: recipe for target 'package/network/utils/iproute2/compile' failed
make[2]: *** [package/network/utils/iproute2/compile] Error 2
make[2]: Leaving directory '/home/xf/lede'
package/Makefile:107: recipe for target '/home/xf/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/xf/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xf/lede'
/home/xf/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by 1607941875** [comment]
同样的问题，兄弟你怎么解决的
