### ISSUE TITLE
小米HD带硬盘的路由器能刷这个固件吗

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6081]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
如果能的话周末开干！
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
不能
