### ISSUE TITLE
开启 IPv6 后，“酸酸乳+”无实际效果

### ISSUE THREAD

**Issue by GWONGJYULEI** [coolsnowwolf/lede#6082]
[x] 没有类似的issue

### (1) 具体问题

A：开启 IPv6 后，“酸酸乳+”可以运行（【谷歌】连通性检查：连接正常），但实际没有FQ效果，关闭 IPv6 后，可运行、有效果

### (2) 路由器型号和固件版本

A：x86_64，R20.12.12（2020.12.22 编译）

### (3) 详细日志

A：抱歉，不知道怎么获取对该 Issues 有用的日志

**Comment by hyird** [comment]
google 从电脑走IPV6了

**Comment by minlang112** [comment]
我同时开着没问题……

**Comment by GWONGJYULEI** [comment]
> 我同时开着没问题……

@minlang112 可以请问一下你是怎么配置IPv6的吗？
