### ISSUE TITLE
酸酸乳启用没多久分流就失效，国内变成走代理

### ISSUE THREAD

**Issue by hyyz17200** [coolsnowwolf/lede#6083]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
[x] 没有类似的issue

### (1) 具体问题

A：编译今日的新版以后升级上去，刚应用时，GFW和IP模式分流都正常。但过上一两分钟就会变成国内地址全部走代理。例如GFW模式时会变成这样：

![QQ截图20201223034224](https://user-images.githubusercontent.com/4502808/102927184-7105ef00-44d1-11eb-87d1-347d10735319.png)

### (2) 路由器型号和固件版本

A：x86_64 
OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)

### (3) 详细日志

A：

**Comment by hyyz17200** [comment]
测试了一下，保留配置降级，退回旧版本
OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222)
一切正常

**Comment by Dimitri2020007** [comment]
ssr+启用gfw模式是不是一开始用都解析失败啊，要等很长时间才反应过来?

**Comment by hyyz17200** [comment]
> ssr+启用gfw模式是不是一开始用都解析失败啊，要等很长时间才反应过来?

老固件都正常的

**Comment by hyyz17200** [comment]
三天前试了编译最新的源码，症状一样，最后还是退回去用了。
