### ISSUE TITLE
adbyby

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#6097]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：**淘宝有些域名被过滤掉了，薅羊毛时把关了WIFI，用流量才行，，，**

### (2) 路由器型号和固件版本

A：Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread (CpuMark : 33779.893286 Scores) 

### (3) 详细日志

A：无

**Comment by xiaobaishu1** [comment]
这玩意可以关闭了
