### ISSUE TITLE
IP-MAC绑定的问题

### ISSUE THREAD

**Issue by lrgcx** [coolsnowwolf/lede#6103]
之前安装过自己编译的4.19和5.4版本（源码都是Lean源码），有几个版本都可以使用IP-MAC绑定和端口转发等设置成功远程唤醒局域网内的群晖NAS，最近编译的固件包括4.19和5.4的都不能远程唤醒NAS了，其他设置都一样没有变化。怀疑是不是IP-mac绑定的问题？请老大明察！

**Comment by programmejava** [comment]
wake on lan跟ip没关系  只是向网络中的mac地址发包 检查网络或者要唤醒的主机

**Comment by lrgcx** [comment]
> 在lan跟ip没关系只是唤醒网络中的mac地址发包检查网络或者要唤醒的主机

ip-mac绑定实际就是ARP绑定，ARP绑定如果没到位的话远程是唤醒不了内网设备的。我的意思是问ARP绑定是否有效？

**Comment by Wilson-coder** [comment]
我发现如果电脑开着机，重启了软路由（苯比如升级固件的时候），之后就没办法实现远程唤醒了。对于要唤醒的电脑，需要把电脑关机之后再重新启动一下软路由，之后才可以远程唤醒。

**Comment by lrgcx** [comment]
> 我发现如果电脑开着机，重启了软路由（重启升级固件的时候），之后就没办法实现远程唤醒了。对于要唤醒的电脑，需要把电脑关机之后再重新启动一下软路由，之后才可以远程唤醒。

刚才按照你说的，路由和nas都关闭，然后先开路由再远程开机还真的可行。哈哈！
