### ISSUE TITLE
为什么无法使用 52 56 60 100... 信道无线中继？

### ISSUE THREAD

**Issue by jinglei207** [coolsnowwolf/lede#6111]
这个问题我在 openwrt官网也提过，但是没得到扫描好的答案。本人在欧洲，有时候会用到这几个信道中继，但是发现无法使用。
如果使用这些频道的话，要么sta 无法使用，要么 ap 将无法使用。这让我很头痛啊，闭源驱动没有这问题，只有开源驱动才有。
我测试过 tp-link c2600 (高通qca 9980) ， RM2100，tp-link archer c7 都这样。
地区我试过 italy, china, US 和 world 都没用。

听说和DFS有关。如果真的是的话，有办法破吗？
这个问题一直纠结我很久，很想知道。求大神能解释一下啊。

**Comment by yinzhefuyun** [comment]
试一试AU澳大利亚
