### ISSUE TITLE
系统日志里面不断打irq内核告警是什么原因？

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#6114]
i3865u,挂了两个玩客云，网络流量比较大，最新的5.x内核的固件，不断地系统日志打下面的玩意，啥意思？

型号：Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread (CpuMark : 26964.852999 Scores)
版本：OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)
内核：5.4.84

Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.343126] ------------[ cut here ]------------
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.348054] WARNING: CPU: 1 PID: 14521 at 0xffffffffa189022a
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.354032] Modules linked in: fast_classifier xt_FULLCONENAT ath9k iwl4965 iwl3945 ath9k_htc ath9k_common xt_connlimit wl18xx wl12xx rtw88_8822ce rtw88_8822c rtw88_8822be rtw88_8822b rtw88_8723de rtw88_8723d rtl8821ae rtl8192se rtl8192de rtl8192cu rtl8192ce rtl8192c_common rtl_usb rtl_pci rt2800usb rt2800pci rt2800mmio rt2800lib rt2500usb rt2500pci rt2400pci qcserial pppoe ppp_async option nf_conncount mt76x0u mt76x0e mt76x0_common l2tp_ppp iwlmvm iwlegacy iwldvm ipw2200 ipw2100 iptable_nat gspca_m5602 gspca_konica gspca_jeilinj gspca_gl860 gspca_finepix gspca_etoms gspca_conex cdc_mbim carl9170 btcoexist brcmsmac brcmfmac b43legacy b43 ath9k_hw ath6kl_usb ath6kl_core ath5k ath10k_pci ath10k_core ath adm8211 zd1211rw xt_state xt_nat xt_helper xt_conntrack xt_connmark xt_connbytes xt_REDIRECT xt_MASQUERADE xt_CT wlcore uvcvideo usb8xxx usb_wwan ti_usb_3410_5052 sr9700 snd_usb_audio snd_hda_intel snd_hda_codec_via snd_hda_codec_realtek snd_hda_codec_hdmi snd_hda_codec_generic snd_hda_codec
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.354057]  smsc95xx sierra_net rtw88_pci rtw88_core rtlwifi rtl8xxxu rtl8812au rtl818x_pci rtl8187 rt73usb rt61pci rt2x00usb rt2x00pci rt2x00mmio rt2x00lib rsi_usb rsi_91x rndis_host qmi_wwan pwc pptp pppox ppp_mppe ppp_generic plusb p54usb p54pci p54common orinoco_pci orinoco nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp nf_nat_amanda nf_nat nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_rtcache nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast nf_conntrack_amanda nf_conntrack mwl8k mwifiex_pcie mwifiex mt7915e mt76x2u mt76x2e mt76x2_common mt76x02_usb mt76x02_lib mt7663u mt7663_usb_sdio_common mt7615e mt7615_common mt7603e mt7601u mt76_usb mt76 mcs7830 mac80211 libipw libertas kalmia iwlwifi ipt_REJECT huawei_cdc_ncm gspca_zc3xx gspca_vc032x gspca_tv8532 gspca_t613 gspca_sunplus gspca_stv06xx gspca_stk014 gspca_sq905c gspca_sq905 gspca_spca561 gspca_spca508
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.444033]  gspca_spca506 gspca_spca505 gspca_spca501 gspca_spca500 gspca_sonixj gspca_sonixb gspca_sn9c20x gspca_se401 gspca_pac7311 gspca_pac207 gspca_ov534_9 gspca_ov534 gspca_ov519 gspca_mr97310a gspca_mars gspca_main dm9601 cp210x ch341 cfg80211 cdc_subset cdc_ncm cdc_ether cdc_eem ax88179_178a ath9k_pci_owl_loader asix amdgpu xt_time xt_tcpudp xt_tcpmss xt_statistic xt_socket xt_recent xt_quota xt_policy xt_pkttype xt_owner xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_esp xt_ecn xt_dscp xt_comment xt_addrtype xt_TPROXY xt_TCPMSS xt_LOG xt_HL xt_DSCP xt_CLASSIFY xr_usb_serial_common wlcore_sdio wireguard videobuf2_v4l2 videobuf2_common via_velocity via_rhine usbserial usbnet usblp ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda tulip ts_kmp ts_fsm ts_bm solos_pci snd_usbmidi_lib snd_intel_nhlt snd_hda_core slhc sky2 skge sis900 sis190 sch_cake rtl8150 regmap_core radeon r8712u(C) r8169 r8168 r8152 r8125 r6040
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.533673]  pegasus pcnet32 niu nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 ne2k_pci mmc_spi mlx5_core mlx4_en mlx4_core macvlan lzo lib80211_crypt_wep lib80211_crypt_tkip lib80211_crypt_ccmp lib80211 kvm_intel kvm kaweth irqbypass iptable_raw iptable_mangle iptable_filter ipt_ah ipt_ECN ipheth ip_tables i40e hso gpu_sched forcedeth exfat ethoc et131x e1000e e100 dmx_usb crc8 crc7 crc_itu_t crc_ccitt cpia2 cordic compat cdc_wdm cdc_acm brcmutil br_netfilter bnx2x bnx2 be2net atl2 atl1e atl1c atl1 asn1_decoder alx 8390 8139too 8139cp fuse tcp_bbr sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred configs videobuf2_vmalloc videobuf2_memops videodev evdev i2c_dev spi_ks8995 siit cryptodev xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.623744]  ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink rtl8306 mvsw61xx ip17xx nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 swconfig nfsv4 nfsv3 nfsd nfs bonding 3c59x ip_gre gre snd_via82xx snd_intel8x0 snd_mpu401_uart ixgbevf ixgbe igbvf igb e1000 snd_ac97_codec ac97_bus ifb dummy mdio l2tp_netlink l2tp_core udp_tunnel ip6_udp_tunnel ipcomp6 xfrm6_tunnel esp6 ah6 xfrm4_tunnel ipcomp esp4 ah4 tunnel6 tunnel4 ip_tunnel hfcpci hfcmulti rpcsec_gss_krb5 auth_rpcgss oid_registry veth tun snd_rawmidi snd_seq_device snd_pcm_oss snd_pcm snd_timer snd_mixer_oss snd_hwdep snd_compress snd soundcore nbd mISDN_dsp l1oip mISDN_core xfrm_user xfrm_ipcomp af_key xfrm_algo vfat fat lockd sunrpc grace cifs dns_resolver dm_mirror dm_region_hash dm_log dm_crypt dm_mod dax br2684 atm bcma raid456 async_raid6_recov async_pq
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.712729]  async_xor async_memcpy async_tx raid10 raid1 raid0 md_mod nls_utf8 nls_iso8859_1 nls_cp437 natsemi eeprom_93cx6 shortcut_fe_ipv6 shortcut_fe crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha256_ssse3 sha256_generic libsha256 sha1_ssse3 sha1_generic seqiv jitterentropy_rng drbg michael_mic md5 md4 hmac ghash_generic gcm echainiv des_generic libdes deflate cts ctr ccm cbc authenc arc4 crypto_acompress uas sdhci_pltfm xhci_plat_hcd fsl_mph_dr_of ehci_platform ehci_fsl btrfs zstd_decompress zstd_compress xxhash xor raid6_pq lzo_decompress lzo_compress libcrc32c antfs tg3 b44 ssb ptp realtek broadcom bcm_phy_lib pps_core mii libphy
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.862852] CPU: 1 PID: 14521 Comm: pidof Tainted: G        WC        5.4.84 #0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.870536] Hardware name: Default string Default string/Default string, BIOS 5.12 09/15/2019
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.879429] RIP: 0010:0xffffffffa189022a
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.883618] Code: b8 89 41 08 48 3b 31 74 b0 8b 46 40 85 c0 74 2d 8d 78 01 48 8d 56 40 f0 0f b1 3a 75 11 48 89 f7 48 87 39 e8 98 d6 ef df eb 8f <0f> 0b eb 8b 85 c0 74 0b 8d 78 01 f0 0f b1 3a 74 e2 eb f1 0f 0b eb
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.903008] RSP: 0018:ffffc9000003c9e0 EFLAGS: 00010282
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.908515] RAX: 0000000000000058 RBX: 0000000000000001 RCX: ffff888258731c58
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.916047] RDX: ffffc9000003ca30 RSI: ffff888261c56948 RDI: ffff888253351500
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.923527] RBP: ffffc9000003c9e0 R08: 0000000000000000 R09: ffffffffa0914480
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.931049] R10: ffff888265d2ca80 R11: 0000000000000020 R12: 0000000000000002
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.938566] R13: ffff888260a87100 R14: ffff888253125400 R15: ffffc9000003ca30
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.946078] FS:  00007f1f3ac5ad48(0000) GS:ffff888266d00000(0000) knlGS:0000000000000000
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.954548] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.960613] CR2: 00000000004327fc CR3: 00000002531f6006 CR4: 00000000003606e0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.968112] Call Trace:
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.970790]  <IRQ>
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.973030]  nf_hook_slow+0x42/0xc0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.976794]  br_nf_hook_thresh+0x6f6/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.982574]  ? br_nf_hook_thresh+0xd0/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.988431]  nf_hook_slow+0x42/0xc0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.992151]  __br_forward+0x8e/0x120
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127864.995964]  ? br_dev_queue_push_xmit+0x180/0x180
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.000941]  deliver_clone+0x32/0x50
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.004776]  br_flood+0x104/0x120
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.008331]  br_handle_frame_finish+0x39d/0x450
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.013143]  ? br_pass_frame_up+0x140/0x140
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.017605]  br_nf_hook_thresh+0xb3/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.023278]  ? br_pass_frame_up+0x140/0x140
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.027722]  br_nf_hook_thresh+0xa3b/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.033504]  ? br_pass_frame_up+0x140/0x140
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.037950]  ? nf_nat_icmp_reply_translation+0x414/0x450 [nf_nat]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.044333]  ? nf_hook_slow+0x42/0xc0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.048242]  br_nf_hook_thresh+0xe54/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.054047]  ? br_nf_hook_thresh+0x910/0x12a0 [br_netfilter]
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.059993]  br_handle_frame+0x17c/0x370
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.064170]  ? br_pass_frame_up+0x140/0x140
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.068617]  ? br_handle_frame_finish+0x450/0x450
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.073598]  __netif_receive_skb_core+0x1fb/0xb40
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.078572]  ? gro_normal_list.part.175+0x19/0x40
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.083552]  __netif_receive_skb_one_core+0x2a/0x70
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.088712]  __netif_receive_skb+0x1e/0x60
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.093077]  process_backlog+0xb0/0x170
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.097164]  __napi_poll+0x2b/0x90
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.100802]  net_rx_action+0xca/0x210
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.104690]  __do_softirq+0xc9/0x20e
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.108503]  irq_exit+0x6f/0x80
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.111880]  do_IRQ+0x54/0xe0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.115091]  common_interrupt+0xf/0xf
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.119031]  </IRQ>
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.121349] RIP: 0010:pid_revalidate+0x1b/0x80
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.126072] Code: 44 ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 55 83 e6 40 48 89 e5 41 55 41 54 53 75 62 48 8b 5f 30 31 f6 45 31 ed 48 8b 7b b8 <e8> 20 fb e8 ff 49 89 c4 48 85 c0 75 0a 5b 44 89 e8 41 5c 41 5d 5d
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.145482] RSP: 0018:ffffc90000a47c20 EFLAGS: 00000246 ORIG_RAX: ffffffffffffffd1
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.157122] RAX: ffffffff8123d610 RBX: ffff888246d48568 RCX: 0000000000000018
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.164624] RDX: 0000000000000003 RSI: 0000000000000000 RDI: ffff8882651e6700
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.172113] RBP: ffffc90000a47c38 R08: 00656e0000657865 R09: 0000000000000003
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.179592] R10: ff9a91ffff9a879a R11: 0000000000000fe0 R12: ffff888238bb7540
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.187120] R13: 0000000000000000 R14: ffff888253711180 R15: ffffc90000a47cb0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.194596]  ? map_files_d_revalidate+0x130/0x130
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.199573]  lookup_fast+0x230/0x270
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.203393]  walk_component+0x35/0x300
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.207406]  ? path_init+0x222/0x2f0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.211244]  path_lookupat.isra.69+0x58/0x1f0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.215890]  filename_lookup.part.85+0x88/0x100
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.220703]  ? __check_object_size+0x18b/0x19c
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.225425]  ? strncpy_from_user+0x4c/0x1b0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.229869]  ? getname_flags+0x4e/0x170
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.233949]  user_path_at_empty+0x39/0x40
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.238215]  do_readlinkat+0x4b/0xe0
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.242053]  ? _cond_resched+0x14/0x30
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.246066]  __x64_sys_readlink+0x1a/0x20
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.250331]  do_syscall_64+0x54/0x380
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.254223]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.259555] RIP: 0033:0x7f1f3ac3f835
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.263366] Code: 89 d1 48 63 f7 6a 00 31 ff 45 31 c9 45 31 c0 48 89 c2 e8 4a 94 ff ff 48 83 c4 18 48 89 c7 e9 d2 e9 fb ff b8 59 00 00 00 0f 05 <48> 89 c7 e9 c3 e9 fb ff 49 89 ca 48 63 ff b8 0b 01 00 00 0f 05 48
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.282825] RSP: 002b:00007ffd1afc5fb8 EFLAGS: 00000206 ORIG_RAX: 0000000000000059
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.290784] RAX: ffffffffffffffda RBX: 00007f1f3ac5bba0 RCX: 00007f1f3ac3f835
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.298239] RDX: 0000000000000050 RSI: 00007f1f3ac5bba0 RDI: 00007ffd1afc5fef
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.305727] RBP: 0000000000000050 R08: 00007f1f3ac5bb90 R09: 8080808080808080
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.313235] R10: 0000000000000000 R11: 0000000000000206 R12: 00007ffd1afc5fef
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.320754] R13: 0000000000000000 R14: 0400000100003e00 R15: 0000000000000000
Sun Dec 27 20:28:01 2020 kern.warn kernel: [127865.328226] ---[ end trace cd52dde72e8fd3c6 ]---

**Comment by Dimitri2020007** [comment]
这个问题是sfe和flowoffload起冲突了

建议sfe和flowoffload二选一

我现在只用sfe

**Comment by galaxyskyknight** [comment]
> 这个问题是sfe和flowoffload起冲突了
> 
> 建议sfe和flowoffload二选一
> 
> 我现在只用sfe

具体哪里操作？sfe和flowoffload是什么？

**Comment by galaxyskyknight** [comment]
好像我的只有turbo sfe没有flowoffload哈。。。不过我有单线双拨倒是真的。但我关了SFE甚至关了Fullcone-NAT，这个日志还是大不停，而且跟你现象一样，偶尔会重启（watchcat已经关掉），丢包很高, 见我反应的另一个issue #6089. net Rx的softirq软中断很多，有drop和overrun.

**Comment by Dimitri2020007** [comment]
make menuconfig>luci>application下保留或者取消luci-app-sfe/flowoffload

drop这个我是启动约1天左右会出现

这个留心下内核日志

不过我sfe和flowoffload二选一之后就没有刷过屏了

若你用的是x86取消掉这个就不会有问题
