### ISSUE TITLE
ssr plus+ 白名单列表问题，感觉白名单未生效

### ISSUE THREAD

**Issue by knight-666** [coolsnowwolf/lede#6120]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：ssr plus+ 配置不走代理白名单 plex.tv  plex客户端在公网ip+端口转发的前提下，还是走了ssr plus+代理
关闭ssr plus+后，plex客户端就可以公网ip+端口转发下访问了

感觉配置了白名单没有生效，这样会导致plex服务无法通过公网ip+端口直连

大佬知道这种怎么解决吗？

### (2) 路由器型号和固件版本

A：

型号 | Intel(R) Pentium(R) CPU J1900
OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f) 
内核版本 | 5.4.84

**Comment by knight-666** [comment]
plex 获取设置公网ip的地址为，plex.tv/pms/:/ip，在开ssr plus+情况下，获取到的是梯子服务器的地址，而在不开ssr plus+情况下，则是正常的，获取到的是公网ip的地址
在配置了ssr plus+ 白名单情况下 该plex.tv/pms/:/ip地址获取到的也是梯子服务器的地址，感觉白名单没有生效

**Comment by SamoyeHN** [comment]
访问控制-》不走代理的域名。添加plex.tv

**Comment by usamr** [comment]
我的K2P和软路由最近都是这个问题，之前还是好好的，不知道怎么设置。
