### ISSUE TITLE
请教下怎样安装NextCloud？

### ISSUE THREAD

**Issue by Gokou-Ruri** [coolsnowwolf/lede#6124]
在网上找的OpenWrt安装NextCloud教程好像都不适用于LEDE，只有OpenWrt原版才能按照那些教程安装。
请问有人在LEDE上安装了NexuCloud吗？可否分享您的经验呢？谢谢！（p.s.是硬路由Newifi3。）

**Comment by hdydy** [comment]
编译的时候勾选docker，装好后用docker部署，不然你路由器固件更新一次就要重装一次，麻烦得一比。
