### ISSUE TITLE
V2RAY 可以出一个教程吗?

### ISSUE THREAD

**Issue by aiyu20181** [coolsnowwolf/lede#613]
## 问题1
- 我把VPS上安装好的地址填进去后无法科学,在PC端挂V2RAY客户端就可以上网.设置了很久,也没搞明白.

## 希望结果
- 是否可以把软件逻辑及教程讲一下好吗?谢谢

**Comment by wspzf** [comment]
百度谷歌是个好工具

**Comment by hcym** [comment]
非常别扭，我也是用带上传配置文件老版本上传一次，再用本地正常配置才用上搬瓦工。可能是文件格式转换问题。感谢大雕感谢上帝

**Comment by iotsys** [comment]
PC端都可以了，那么可能你服务端没配置TLS，则路由上的V2RAY要把TLS也取消掉 @aiyu20181 。如果真是这个问题，那么建议把TLS也配置上，应该更可靠

**Comment by aiyu20181** [comment]
- 我好像是两端都没有配置TLS,现在发现在斐讯K3刷的OpenWrt上,V2Ray要是不指定单个"电脑"内网IP全部走代理的话,是无法科学上网的.
- 而手机这种无线却是好使的,真是很奇怪?各位有什么解决办法吗?

**Comment by madcat0513** [comment]
你们用mkcp能联么？

**Comment by hcym** [comment]
试过mkcp，指望用带宽换速度，结果是卡的不能自理，其它五花八门的姿势也都换过。感觉还是官方默认安装配置最好，简单快捷
