### ISSUE TITLE
为什么这几天编绎k2p的固件都找不到 mt-wifi ？

### ISSUE THREAD

**Issue by pop2006** [coolsnowwolf/lede#6139]
我记得之前是有这个选项的，现在刷不出来了。屏蔽了？如何重新启用啊？

**Comment by NEARWN** [comment]
k2p已经改为闭源驱动了

**Comment by pop2006** [comment]
我还以为这个luci-app-mtwifi 就是闭源驱动，是我理解错了吗？

**Comment by smlemk3** [comment]
> 我还以为这个luci-app-mtwifi 就是闭源驱动，是我理解错了吗？

我也以为这是集成的闭源驱动。。。话说现在找不到了，直接编译就行吗？还是要自己手动到哪下载驱动添加？这项目有没有更新日志呢？哪里修改了都不知道。。。。

**Comment by meego20** [comment]
https://github.com/coolsnowwolf/openwrt
在这里能找到mt-wifi
