### ISSUE TITLE
小米路由器4A千兆版 无限重启

### ISSUE THREAD

**Issue by liuzipeng** [coolsnowwolf/lede#6143]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新源码无限重启

### (2) 路由器型号和固件版本

A：小米路由器4A千兆版

### (3) 详细日志

A：

**Comment by 1715173329** [comment]
There's a workaround for you:
```bash
git checkout 5be81314bb08934fbe03c2e26191b80f021b0d2b^ \
	target/linux/ramips/patches-5.4/102-mt7621-fix-cpu-clk-add-clkdev.patch
```
