### ISSUE TITLE
rtl8156和rtl8156B 不能驱动，如绿联2.5G usb网卡，比亚兹2.5G usb网卡

### ISSUE THREAD

**Issue by liuquan321** [coolsnowwolf/lede#6144]
1月1日最新源码编译的x86固件无法驱动绿联2.5G usb网卡(rtl8156)和比亚兹2.5G usb网卡(8156b)，具体表现为lsusb可以看到设备，但是没有生成eth设备。
```
Bus 001 Device 002: ID 0781:5571 SanDisk Corp. Cruzer Fit
Bus 002 Device 003: ID 0bda:8156 Realtek Semiconductor Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

看上半年的[issue](https://github.com/coolsnowwolf/lede/issues/3457)有聊到因为和千兆的网卡有些冲突暂时关闭了，半年下来8156b的usb网卡性价比越来越高，京东自营已经跌到百元上下，完全可以替代千兆网卡了，是否可以考虑使用螃蟹10月中旬的新8152驱动替换老的8152驱动或给出互斥的两个可选项呢？

**Comment by liuquan321** [comment]
通过patch方式用螃蟹官方驱动替换内核自带驱动成功驱动8156b，大概思路如下
```
tar -xvf linux-5.4.85.tar.xz
cp linux-5.4.85_new
tar -xvf linux-5.4.85.tar.xz
tar -zxvf r8152.53.56-2.14.0.tar
cp -a r8152.53.56-2.14.0/r8152-2.14.0/50-usb-realtek-net.rules linux-5.4.85_new/drivers/net/usb/
cp -a r8152.53.56-2.14.0/r8152-2.14.0/compatibility.h linux-5.4.85_new/drivers/net/usb/
cp -a r8152.53.56-2.14.0/r8152-2.14.0/r8152.c linux-5.4.85_new/drivers/net/usb/

diff -uparN linux-5.4.85/* linux-5.4.85_new/* >988-r8152-2.14.0.patch

cp 988-r8152-2.14.0.patch ../lean/R20/lede/target/linux/generic/pending-5.4/
cd ../lean/R20/lede/ 
make
```

**Comment by helianling** [comment]
8156可以参考8125的相同思路，另外最新的8125B驱动参数改一下可以支持RSS的，不支持8156支不支持。
![image](https://user-images.githubusercontent.com/31648892/103463099-d759ff80-4d64-11eb-9fe5-85d0ec7e6b52.png)

**Comment by liuquan321** [comment]
> 8156可以参考8125的相同思路，另外最新的8125B驱动参数改一下可以支持RSS的，不知道8156支不支持。
> ![image](https://user-images.githubusercontent.com/31648892/103463099-d759ff80-4d64-11eb-9fe5-85d0ec7e6b52.png)

我也参考过这个issue，两者稍有区别，8152的源码默认不在lede源码中而在linux kernel中，这导致两者虽然思路相同但是实际操作差异较大，最终参考 https://forum.openwrt.org/t/2-5g-usb-ethernet-kmod-usb-net-rtl8152/72154/57 完成了编译时替换。目前这个方法存在较大弊端内核版本更新需要重新生成patch。

**Comment by liuquan321** [comment]
> 8156可以参考8125的相同思路，另外最新的8125B驱动参数改一下可以支持RSS的，不知道8156支不支持。
> ![image](https://user-images.githubusercontent.com/31648892/103463099-d759ff80-4d64-11eb-9fe5-85d0ec7e6b52.png)

**Comment by longdahai** [comment]
期待集成

**Comment by yi-ge** [comment]
非常期待集成

**Comment by one02free** [comment]
> 通过patch方式用螃蟹官方驱动替换内核自带驱动成功驱动8156b，大概思路如下
> 
> ```
> tar -xvf linux-5.4.85.tar.xz
> cp linux-5.4.85_new
> tar -xvf linux-5.4.85.tar.xz
> tar -zxvf r8152.53.56-2.14.0.tar
> cp -a r8152.53.56-2.14.0/r8152-2.14.0/50-usb-realtek-net.rules linux-5.4.85_new/drivers/net/usb/
> cp -a r8152.53.56-2.14.0/r8152-2.14.0/compatibility.h linux-5.4.85_new/drivers/net/usb/
> cp -a r8152.53.56-2.14.0/r8152-2.14.0/r8152.c linux-5.4.85_new/drivers/net/usb/
> 
> diff -uparN linux-5.4.85/* linux-5.4.85_new/* >988-r8152-2.14.0.patch
> 
> cp 988-r8152-2.14.0.patch ../lean/R20/lede/target/linux/generic/pending-5.4/
> cd ../lean/R20/lede/ 
> make
> ```
> 
> 方式比较low，有更优雅实现方式的勿忘告知。。。
> 
> 参考: https://forum.openwrt.org/t/2-5g-usb-ethernet-kmod-usb-net-rtl8152/72154/57

你好，我按照你上述提供的方法基于5.4.109生成了patch包，最后要怎样才能编译到Openwrt上？是不是把patch文件放进*/target/linux/generic/pending-5.4/后正常编译就可以了？还需要其他操作吗？

**Comment by liuquan321** [comment]
> > 通过patch方式用螃蟹官方驱动替换内核自带驱动成功驱动8156b，大概思路如下
> > ```
> > tar -xvf linux-5.4.85.tar.xz
> > cp linux-5.4.85_new
> > tar -xvf linux-5.4.85.tar.xz
> > tar -zxvf r8152.53.56-2.14.0.tar
> > cp -a r8152.53.56-2.14.0/r8152-2.14.0/50-usb-realtek-net.rules linux-5.4.85_new/drivers/net/usb/
> > cp -a r8152.53.56-2.14.0/r8152-2.14.0/compatibility.h linux-5.4.85_new/drivers/net/usb/
> > cp -a r8152.53.56-2.14.0/r8152-2.14.0/r8152.c linux-5.4.85_new/drivers/net/usb/
> > 
> > diff -uparN linux-5.4.85/* linux-5.4.85_new/* >988-r8152-2.14.0.patch
> > 
> > cp 988-r8152-2.14.0.patch ../lean/R20/lede/target/linux/generic/pending-5.4/
> > cd ../lean/R20/lede/ 
> > make
> > ```
> > 
> > 
> > 方式比较low，有更优雅实现方式的勿忘告知。。。
> > 参考: https://forum.openwrt.org/t/2-5g-usb-ethernet-kmod-usb-net-rtl8152/72154/57
> 
> 你好，我按照你上述提供的方法基于5.4.109生成了patch包，最后要怎样才能编译到Openwrt上？是不是把patch文件放进*/target/linux/generic/pending-5.4/后正常编译就可以了？还需要其他操作吗？

编译选项中选择8152就可以，新版源码中已经集成了8156驱动不用这么折腾了。

**Comment by one02free** [comment]
> > > 通过patch方式用螃蟹官方驱动替换内核自带驱动成功驱动8156b，大概思路如下
> > > ```
> > > tar -xvf linux-5.4.85.tar.xz
> > > cp linux-5.4.85_new
> > > tar -xvf linux-5.4.85.tar.xz
> > > tar -zxvf r8152.53.56-2.14.0.tar
> > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/50-usb-realtek-net.rules linux-5.4.85_new/drivers/net/usb/
> > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/compatibility.h linux-5.4.85_new/drivers/net/usb/
> > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/r8152.c linux-5.4.85_new/drivers/net/usb/
> > > 
> > > diff -uparN linux-5.4.85/* linux-5.4.85_new/* >988-r8152-2.14.0.patch
> > > 
> > > cp 988-r8152-2.14.0.patch ../lean/R20/lede/target/linux/generic/pending-5.4/
> > > cd ../lean/R20/lede/ 
> > > make
> > > ```
> > > 
> > > 
> > > 方式比较low，有更优雅实现方式的勿忘告知。。。
> > > 参考: https://forum.openwrt.org/t/2-5g-usb-ethernet-kmod-usb-net-rtl8152/72154/57
> > 
> > 
> > 你好，我按照你上述提供的方法基于5.4.109生成了patch包，最后要怎样才能编译到Openwrt上？是不是把patch文件放进*/target/linux/generic/pending-5.4/后正常编译就可以了？还需要其他操作吗？
> 
> 编译选项中取消kmod-usb-net-rtl8152勾选就可以。
> 其实新版源码中已经集成了8156驱动不用这么折腾了，直接如下操作：
> 编译选项中取消`kmod-usb-net-rtl8152`
> 勾选`kmod-usb-net-rtl8152-vendor`
> 编译`make`

你好，我按照你的方法选中kmod-usb-net-rtl8152-vendor编译了新包，但是接口处并没有显示【2500Mb/s全双工】这样的字眼，请问是正常的吗？有什么方法可以检查2.5G正常被识别和使用了呢？

**Comment by liuquan321** [comment]
> > > > 通过patch方式用螃蟹官方驱动替换内核自带驱动成功驱动8156b，大概思路如下
> > > > ```
> > > > tar -xvf linux-5.4.85.tar.xz
> > > > cp linux-5.4.85_new
> > > > tar -xvf linux-5.4.85.tar.xz
> > > > tar -zxvf r8152.53.56-2.14.0.tar
> > > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/50-usb-realtek-net.rules linux-5.4.85_new/drivers/net/usb/
> > > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/compatibility.h linux-5.4.85_new/drivers/net/usb/
> > > > cp -a r8152.53.56-2.14.0/r8152-2.14.0/r8152.c linux-5.4.85_new/drivers/net/usb/
> > > > 
> > > > diff -uparN linux-5.4.85/* linux-5.4.85_new/* >988-r8152-2.14.0.patch
> > > > 
> > > > cp 988-r8152-2.14.0.patch ../lean/R20/lede/target/linux/generic/pending-5.4/
> > > > cd ../lean/R20/lede/ 
> > > > make
> > > > ```
> > > > 
> > > > 
> > > > 方式比较low，有更优雅实现方式的勿忘告知。。。
> > > > 参考: https://forum.openwrt.org/t/2-5g-usb-ethernet-kmod-usb-net-rtl8152/72154/57
> > > 
> > > 
> > > 你好，我按照你上述提供的方法基于5.4.109生成了patch包，最后要怎样才能编译到Openwrt上？是不是把patch文件放进*/target/linux/generic/pending-5.4/后正常编译就可以了？还需要其他操作吗？
> > 
> > 
> > 编译选项中取消kmod-usb-net-rtl8152勾选就可以。
> > 其实新版源码中已经集成了8156驱动不用这么折腾了，直接如下操作：
> > 编译选项中取消`kmod-usb-net-rtl8152`
> > 勾选`kmod-usb-net-rtl8152-vendor`
> > 编译`make`
> 
> 你好，我按照你的方法选中kmod-usb-net-rtl8152-vendor编译了新包，但是接口处并没有显示【2500Mb/s全双工】这样的字眼，请问是正常的吗？有什么方法可以检查2.5G正常被识别和使用了呢？

网卡连上2.5g设备后ethtool 看下设备的实际工作速率
