### ISSUE TITLE
antfs无法写入ntfs格式的硬盘

### ISSUE THREAD

**Issue by jy3344511** [coolsnowwolf/lede#6145]
目前使用配置：Win10+虚拟机+openwrt

问题：数据盘为ntfs格式，上面有很多电影、连续剧，没有多余的硬盘进行资料转移，格式化为ext4。使用antfs，发现可以自动挂载ntfs格式的硬盘，上面的电影、连续剧什么的，都可以正常读取，注意是读取，无法进行写入操作，没有办法复制文件到ntfs格式的硬盘上。

Win10已关闭系统休眠、快速启动等

因在openwrt上，有装docker使用qBittorrent进行下载的需求，怎么解决用antfs挂载ntfs格式硬盘，无法写入的问题。

备注：原来是用PVE的虚拟机+openwrt使用，有块小硬盘是ext4格式的，所以没有问题。但是，现在独立显卡挂了，主板、CPU都没有集成显卡，现在电脑开机后，PVE无法通过浏览器进行管理，才转到Win10的。

Win10使用虚拟机+openwrt的话，因电脑配置不够，直接使用Win10+下载工具进行下载的话，发现CPU负载太高了，直接在openwrt上使用qBittorrent下载，CPU负载低很多。

**Comment by AmadeusGhost** [comment]
> 无法进行写入操作，没有办法复制文件到ntfs格式的硬盘上。

是不是选上了 kmod-fs-ntfs 这个包？

**Comment by jy3344511** [comment]
> > 无法进行写入操作，没有办法复制文件到ntfs格式的硬盘上。
> 
> 是不是选上了 kmod-fs-ntfs 这个包？

没有
