### ISSUE TITLE
newwifi3 没有ssrplus选项

### ISSUE THREAD

**Issue by yuanshus** [coolsnowwolf/lede#6153]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by NagaseKouichi** [comment]
feed软件源改了吗？

**Comment by Elletear** [comment]
1.善用搜索，前期挺多人问的，issue也有答案😥。
2.把feeds文件最后一行的'#’去掉并update&install feeds你就可以看到你想要的了。

**Comment by Dimitri2020007** [comment]
取消feeds.conf.default中最后一段的注释了吗?
编辑package/lean/default-settings/files/zzz-default-settings 末尾exit 0之前添加ssr-plus通关口令

口令请自行谷歌，会fq的都能找到。

**Comment by minlang112** [comment]
这个issue可以关了
