### ISSUE TITLE
X86升级到20200105编译的版本以后，日志提示 Failed to load DMC firmware i915/bxt_dmc_ver1_07.bin

### ISSUE THREAD

**Issue by lovelyOK** [coolsnowwolf/lede#6157]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：X86升级到20200105编译的版本以后，日志提示 Failed to load DMC firmware i915/bxt_dmc_ver1_07.bin

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Wed Jan  6 06:03:13 2021 kern.notice kernel: [   60.558703] i915 0000:00:02.0: Failed to load DMC firmware i915/bxt_dmc_ver1_07.bin. Disabling runtime power management.
Wed Jan  6 06:03:13 2021 kern.notice kernel: [   60.559426] i915 0000:00:02.0: DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

**Comment by zhangj3** [comment]
这是一直都有的，不是升级之后才有的，以前你没注意罢了

缺少核显驱动而已，软路由要不要核显驱动都无所谓

这个issue可以关了
