### ISSUE TITLE
请问怎么把package里lean里面的包拉近toolchain里

### ISSUE THREAD

**Issue by lilarcor** [coolsnowwolf/lede#6176]
请问怎么把package里lean里面的包拉近toolchain里，默认情况下make menuconfig里看不到里面的包，比如dnsforwarder

**Comment by AmadeusGhost** [comment]
toolchain 是工具链啊，咋加这些包啊大佬

**Comment by lilarcor** [comment]
小白不懂，我的意思是make menuconfig里看不到luci app 里的dnsforwarder， 后来发现要把feeds default里的helloworld反注释后，才会有，不知道是不是bug
