### ISSUE TITLE
经过多次实验，最后发现开启DNS加速后就会导致luci界面变得爆卡

### ISSUE THREAD

**Issue by 450717565** [coolsnowwolf/lede#618]
经过多次实验，最后发现开启DNS加速后就会导致luci界面变得爆卡，而且会卡回登陆页面，输入密码登陆后也一样卡。

主机型号 | ASUS RT-ACRH17
固件版本 | OpenWrt R8.1.6 By Lean / LuCI openwrt-18.06 branch (git-18.138.53009-80cb4fe)
内核版本 | 4.14.74

![qq 20181007113720](https://user-images.githubusercontent.com/7755795/46577988-abd0f900-ca25-11e8-8f6d-f34efc806ab0.png)
[内核日志10.07.txt](https://github.com/coolsnowwolf/lede/files/2453606/10.07.txt)
[系统日志10.07.txt](https://github.com/coolsnowwolf/lede/files/2453607/10.07.txt)

**Comment by maxxwall** [comment]
你不是唯一，K3也一样，后来我取消又用默认的114好像不怎么卡了，

**Comment by qyh214** [comment]
开启访客网络，然后我也奇卡无比，并且访客网络也没有网，后来都没网了。停止加速，再删掉访客网络，重启，再开启访客网络，并不卡……R7800
