### ISSUE TITLE
x86 固件网速跑不满问题请教

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#6183]
Hi Team,

我编译的x86固件无法跑满网速，500M只能跑300左右

![test测速](https://user-images.githubusercontent.com/25215114/104140742-d91f6500-53ed-11eb-845c-b492703cd724.png)

编译的配置文件如下，我不确定是不是我哪个组件没加上，导致驱动问题什么的
[x86.txt](https://github.com/coolsnowwolf/lede/files/5793649/x86.txt)

BR
Robin

**Comment by minlang112** [comment]
什么CPU 什么网卡，说下机器配置呢-。-

**Comment by Guxing0321** [comment]
Hi minlang112,

D525的cpu，网卡应该是i211的
![配置信息](https://user-images.githubusercontent.com/25215114/104142910-8303ef00-53f8-11eb-9ac3-f6236e200214.png)

或者，有什么命令可以查看，可以提供下，我来操作

BR
Robin

**Comment by qjiang888** [comment]
D525 只能300多M

**Comment by NagaseKouichi** [comment]
D525 太老了吧，性能太弱了

**Comment by star-o0O** [comment]
应该是CPU性能瓶颈了，开SFE可以千兆

**Comment by sxx1314** [comment]
远古架构  高功低能   不开sfe 200出头就差不多了   开了sfe也不会改善太多

**Comment by Guxing0321** [comment]
Hi 大佬们，

我这边准备上J900 或者 3865U，这两个应该是妥妥的吧

我的那个配置文件需要做修改吗？

BR
Robin

**Comment by qjiang888** [comment]
i3 打底，其他都是垃圾

**Comment by Guxing0321** [comment]
Hi  @sxx1314 @qjiang888 @NagaseKouichi @star-o0O  ，

我这边试过了，sfe打开最高就360Mb的样子。
我这边会来换上好的cpu，已经联系好了，3865U

谢谢大佬们的解答

BR
Robin
