### ISSUE TITLE
如何将ShadowSocksR Plus+ 加入别人的固件内？

### ISSUE THREAD

**Issue by kongbar** [coolsnowwolf/lede#6186]
给路由器增加4G网络的project
https://www.ofmodemsandmen.com/download/Builds/Rooter19072.zip
里面没有酸酸乳，请大神指教如何将你的plus+编译进去，谢谢！

**Comment by xiaobaishu1** [comment]
把Plus源码扔进你的源码 文件夹自己搜

**Comment by kongbar** [comment]
> 把Plus源码扔进你的源码 文件夹自己搜

指导一下，我是小白

**Comment by kongbar** [comment]
> 把Plus源码扔进你的源码 文件夹自己搜



> 把Plus源码扔进你的源码 文件夹自己搜

是不是简单的把lean目录放入package里面就可以了

**Comment by openwrt-try** [comment]
把luci扔到package/lean下就可以了
