### ISSUE TITLE
透明网桥怎么编译，在哪个分类里面

### ISSUE THREAD

**Issue by jump-to-jump** [coolsnowwolf/lede#6188]
1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
没有类似的issue 

### (1) 具体问题

A：我想使用透明网桥搭建旁路由，不知道透明网桥模式在哪个分类里面？

### (2) 路由器型号和固件版本

A：树莓派4b

**Comment by minlang112** [comment]
kmod-br-netfilter
似乎是这个东西，但是我不知道使用方法

**Comment by jump-to-jump** [comment]
好的，非常感谢
