### ISSUE TITLE
dnscache进程自动退出，导致无法DNS解析

### ISSUE THREAD

**Issue by fsyxhua** [coolsnowwolf/lede#6195]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
正常运行一段时间dnscache进程就没有了
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
 PVE虚拟机  x86
Powered by LuCI Master (git-20.343.54716-6fc079f) / OpenWrt R20.12.12
A：

### (3) 详细日志

A：
Wed Jan 13 18:19:42 2021 daemon.info dnsmasq[1591]: Connected to system UBus
Wed Jan 13 18:21:27 2021 daemon.info dnsmasq[2248]: Connected to system UBus
Wed Jan 13 18:21:27 2021 cron.err crond[2284]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:21:27 2021 daemon.info dnsmasq[2364]: Connected to system UBus
Wed Jan 13 18:21:32 2021 daemon.err dnscache[2409]: * 01/13 18:21:32| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:21:32 2021 daemon.err dnscache[2409]: * 01/13 18:21:32| pdnsd: warning: EOF encountered while reading entry count from disk cache file.
Wed Jan 13 18:21:43 2021 daemon.info dnsmasq[2588]: Connected to system UBus
Wed Jan 13 18:21:43 2021 cron.err crond[2623]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:21:48 2021 daemon.err dnscache[2844]: * 01/13 18:21:48| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:21:48 2021 daemon.err dnscache[2844]: * 01/13 18:21:48| pdnsd: warning: EOF encountered while reading entry count from disk cache file.
Wed Jan 13 18:21:50 2021 daemon.info dnsmasq[3049]: Connected to system UBus
Wed Jan 13 18:22:00 2021 daemon.err nlbwmon[2705]: Netlink receive failure: Out of memory
Wed Jan 13 18:22:00 2021 daemon.err nlbwmon[2705]: Unable to dump conntrack: No buffer space available
Wed Jan 13 18:22:27 2021 daemon.info procd: Instance sfe::instance1 s in a crash loop 6 crashes, 39 seconds since last crash
Wed Jan 13 18:22:27 2021 daemon.info dnsmasq[3420]: Connected to system UBus
Wed Jan 13 18:22:27 2021 cron.err crond[3455]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:22:35 2021 daemon.info dnsmasq[3886]: Connected to system UBus
Wed Jan 13 18:23:16 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 18:23:16 2021 daemon.err dnscache[4281]: * 01/13 18:23:16| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:23:16 2021 daemon.err dnscache[4281]: * 01/13 18:23:16| pdnsd: warning: EOF encountered while reading entry count from disk cache file.
Wed Jan 13 18:23:16 2021 daemon.info dnsmasq[4276]: Connected to system UBus
Wed Jan 13 18:23:23 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 18:23:23 2021 daemon.err dnscache[4281]: * 01/13 18:23:23| pdnsd: warning: Caught signal 15. Exiting.
Wed Jan 13 18:23:23 2021 daemon.info dnsmasq[4424]: Connected to system UBus
Wed Jan 13 18:23:29 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 18:23:29 2021 daemon.err dnscache[4597]: * 01/13 18:23:29| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:23:29 2021 daemon.info dnsmasq[4592]: Connected to system UBus
Wed Jan 13 18:25:43 2021 daemon.info dnsmasq[12240]: Connected to system UBus
Wed Jan 13 18:25:43 2021 cron.err crond[12275]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:25:48 2021 daemon.err dnscache[12900]: * 01/13 18:25:48| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:25:50 2021 daemon.info dnsmasq[13247]: Connected to system UBus
Wed Jan 13 18:27:42 2021 authpriv.info dropbear[22954]: Child connection from 192.168.18.10:33356
Wed Jan 13 18:27:46 2021 authpriv.notice dropbear[22954]: Password auth succeeded for 'root' from 192.168.18.10:33356
Wed Jan 13 18:28:54 2021 daemon.info dnsmasq[29210]: Connected to system UBus
Wed Jan 13 18:28:54 2021 cron.err crond[29245]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:28:59 2021 daemon.err dnscache[29871]: * 01/13 18:28:59| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:29:02 2021 daemon.info dnsmasq[30217]: Connected to system UBus
Wed Jan 13 18:38:16 2021 daemon.info dnsmasq[13329]: Connected to system UBus
Wed Jan 13 18:38:16 2021 cron.err crond[13364]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:38:21 2021 daemon.err dnscache[13990]: * 01/13 18:38:21| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:38:23 2021 daemon.info dnsmasq[14337]: Connected to system UBus
Wed Jan 13 18:40:00 2021 cron.err crond[13364]: USER root pid 22742 cmd /etc/init.d/frp restart
Wed Jan 13 18:40:00 2021 user.notice FRPC: Shutting down frp service
Wed Jan 13 18:40:00 2021 authpriv.info dropbear[22954]: Exit (root) from <192.168.18.10:33356>: Disconnect received
Wed Jan 13 18:40:00 2021 user.notice FRPC: Starting frp service
Wed Jan 13 18:41:01 2021 authpriv.info dropbear[27935]: Child connection from 192.168.18.10:33360
Wed Jan 13 18:41:04 2021 authpriv.notice dropbear[27935]: Password auth succeeded for 'root' from 192.168.18.10:33360
Wed Jan 13 18:41:26 2021 daemon.info dnsmasq[30770]: Connected to system UBus
Wed Jan 13 18:41:26 2021 cron.err crond[30805]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:41:31 2021 daemon.err dnscache[31430]: * 01/13 18:41:31| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:41:33 2021 daemon.info dnsmasq[31781]: Connected to system UBus
Wed Jan 13 18:41:41 2021 daemon.info dnsmasq[32675]: Connected to system UBus
Wed Jan 13 18:41:41 2021 cron.err crond[32710]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:41:46 2021 daemon.err dnscache[881]: * 01/13 18:41:46| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:41:48 2021 daemon.info dnsmasq[1251]: Connected to system UBus
Wed Jan 13 18:44:51 2021 daemon.info procd: Instance sfe::instance1 s in a crash loop 6 crashes, 184 seconds since last crash
Wed Jan 13 18:44:51 2021 daemon.info dnsmasq[17209]: Connected to system UBus
Wed Jan 13 18:44:51 2021 cron.err crond[17244]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:44:59 2021 daemon.info dnsmasq[18140]: Connected to system UBus
Wed Jan 13 18:46:03 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 18:46:03 2021 daemon.info dnsmasq[18659]: Connected to system UBus
Wed Jan 13 18:46:53 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 18:46:53 2021 daemon.err dnscache[18994]: * 01/13 18:46:53| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:46:53 2021 daemon.info dnsmasq[18987]: Connected to system UBus
Wed Jan 13 18:47:18 2021 daemon.err uhttpd[2582]: Warning: www.cn86.win resolves to multiple addresses: using only the first one returned by the resolver.
Wed Jan 13 18:48:22 2021 daemon.info dnsmasq[19843]: Connected to system UBus
Wed Jan 13 18:48:22 2021 cron.err crond[19878]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:48:27 2021 daemon.err dnscache[20092]: * 01/13 18:48:27| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:48:29 2021 daemon.info dnsmasq[20279]: Connected to system UBus
Wed Jan 13 18:51:31 2021 daemon.info dnsmasq[21322]: Connected to system UBus
Wed Jan 13 18:51:31 2021 cron.err crond[21357]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:51:36 2021 daemon.err dnscache[21571]: * 01/13 18:51:36| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:51:39 2021 daemon.info dnsmasq[21757]: Connected to system UBus
Wed Jan 13 18:51:47 2021 daemon.info dnsmasq[21999]: Connected to system UBus
Wed Jan 13 18:51:47 2021 cron.err crond[22034]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:51:52 2021 daemon.err dnscache[22254]: * 01/13 18:51:52| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:51:54 2021 daemon.info dnsmasq[22434]: Connected to system UBus
Wed Jan 13 18:54:57 2021 daemon.info dnsmasq[23477]: Connected to system UBus
Wed Jan 13 18:54:57 2021 cron.err crond[23512]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:55:02 2021 daemon.err dnscache[23732]: * 01/13 18:55:02| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:55:04 2021 daemon.info dnsmasq[23918]: Connected to system UBus
Wed Jan 13 18:58:17 2021 daemon.info dnsmasq[24991]: Connected to system UBus
Wed Jan 13 18:58:17 2021 cron.err crond[25026]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 18:58:22 2021 daemon.err dnscache[25246]: * 01/13 18:58:22| pdnsd: info: pdnsd-1.2.9b-par starting.
Wed Jan 13 18:58:24 2021 daemon.info dnsmasq[25431]: Connected to system UBus
Wed Jan 13 19:00:00 2021 cron.err crond[25026]: USER root pid 25900 cmd /etc/init.d/frp restart
Wed Jan 13 19:00:00 2021 user.notice FRPC: Shutting down frp service
Wed Jan 13 19:00:00 2021 user.notice FRPC: Starting frp service
Wed Jan 13 19:01:27 2021 daemon.info procd: Instance sfe::instance1 s in a crash loop 6 crashes, 185 seconds since last crash
Wed Jan 13 19:01:27 2021 daemon.info dnsmasq[26482]: Connected to system UBus
Wed Jan 13 19:01:27 2021 cron.err crond[26517]: crond (busybox 1.31.1) started, log level 8
Wed Jan 13 19:01:35 2021 daemon.info dnsmasq[26921]: Connected to system UBus
Wed Jan 13 19:25:39 2021 daemon.err rmmod: module is not loaded
Wed Jan 13 19:25:39 2021 daemon.info dnsmasq[1155]: Connected to system UBus
Wed Jan 13 19:26:09 2021 daemon.info dnsmasq[1398]: Connected to system UBus

**Comment by coolsnowwolf** [comment]
端口冲突了
