### ISSUE TITLE
Transmission

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#62]
你好大神。编译时勾选Transmission以后，编译好的固件里没有显示。还需要做什么吗？

**Comment by tomerilery** [comment]
你只选择了luci，没有选择app，去Network—BT***里面去找，然后选上再编译

**Comment by d975xbx** [comment]
ok明白了，感谢

**Comment by qiankan520** [comment]
刚才我也遇到这个问题 经过询问大神得知  解决步骤如下
1。sudo apt-get install libglib2.0-dev
2。在network——bt里面选择 deamon-openssl    remote-openssl    web  这三个就可以了

**Comment by tomerilery** [comment]
编译王，我就是你下午找的大神，23333
