### ISSUE TITLE
源码出问题了好像

### ISSUE THREAD

**Issue by x444222** [coolsnowwolf/lede#6201]
反馈bug/问题模板，提建议请删除
./scripts/feeds install -a
WARNING: Makefile 'package/lean/
## 1.关于你要提交的问题
./scripts/feeds install -a
出错
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
./scripts/feeds install -a

WARNING: Makefile 'package/lean/此目录下的全部错误警告
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
https://github.com/EnnawYang/Actions-OpenWrt/runs/1672753874?check_suite_focus=true#step:7:20

**Comment by EnnawYang** [comment]
https://github.com/EnnawYang/Actions-OpenWrt/runs/1672753874?check_suite_focus=true#step:7:20
你指的是这个？ 正常无需理会

**Comment by x444222** [comment]
https://github.com/x444222/openwrt/blob/main/20210116223249.png

截图出来了。新手我也不是很懂，前几天还没有这样的，四天前我还能编译成功现在就这样，重装系统重新来过都不行

**Comment by CYJason2000** [comment]
Update的时候有没有超时或失败？可能是网络问题，开了代理再执行这两条比较好。

**Comment by jjm2473** [comment]
试试 `./script/feeds update -a && ./script/feeds install-a`

**Comment by x444222** [comment]
解决了重复使用  ./script/feeds install-a
