### ISSUE TITLE
K2P 最新源码编译5G不能修改信道

### ISSUE THREAD

**Issue by qjiang888** [coolsnowwolf/lede#6202]
不知道大家有这个问题没有？怎么修改都是36
![666666666666](https://user-images.githubusercontent.com/39437973/104706288-da39f480-5755-11eb-8b92-1d9d3f3f6bbb.png)

**Comment by q397333** [comment]
我这里无问题，你把那个强制40mhz频宽关了试试

**Comment by qjiang888** [comment]
强制40mhz频宽 我是关了的改不了

**Comment by lphgor** [comment]
我这边测试，2.4G的信道选auto，5G就不能改。2.4G手动指定信道，5G的信道也能改了。

**Comment by qjiang888** [comment]
> 我这边测试，2.4G的信道选auto，5G就不能改。2.4G手动指定信道，5G的信道也能改了。

感谢大佬，2.4G不自动 5G可以修改了，非常感谢！！
