### ISSUE TITLE
重启后有大概率需要重新保存&应用DNS才行

### ISSUE THREAD

**Issue by axlexan** [coolsnowwolf/lede#6206]
路由器是Redmi AC2100（之前的新三好像也会有这个现象）

如标题所言需要在flowoffload设置下才可以打开国内的网站

如何修复这个问题

**Comment by Neverends4** [comment]
使用dnsmasq缓存+https-dns-proxy上游没有发现你这个问题，定期重启后dns解析正常。你是不是用了smartdns或者adguard之类的过滤。

**Comment by lanfenglin** [comment]
ssr每次换节点了，DNS就失效了，重启又好了

**Comment by sxx1314** [comment]
感觉是ssrp的问题  确实存在节点失效/重连之后  dns失效的问题

**Comment by hyyz17200** [comment]
我也有过这个问题。
目前我发现的解决方案是：
1. WAN端口里，对端通告的DNS获取勾勾去掉，然后出现的自定义DNS框不填，留空。
2. 在dnsmasq转发设定设定任意你需要的dns地址（flowoffload的dns加速会自动设定它的，我用smartdns所以填127.0.0.1#6053）。之后再把第二页的忽略解析文件打勾即可。

这样设定好以后，我试过重启不需要任何重保存就能通国内外网。 你试试看。
