### ISSUE TITLE
红米AC2100 breed 刷入kernel固件无法访问路由管理页面

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#6219]
Hi team,

我根据下面这个教程，给redmi ac2100 刷了breed
https://www.jianshu.com/p/516c43a59610
但是，当刷了 kernel 包的之后发现，设备无法正常获取ip地址，也无法访问到管理页面

我编译的config文件如下

[redmi2100.txt](https://github.com/coolsnowwolf/lede/files/5835333/redmi2100.txt)

我不确定是我编译的固件的问题，还是哪边配置的问题

BR
Robin

**Comment by EnnawYang** [comment]
没遇到，请检查是否完全按照教程操作没有遗漏

**Comment by NagaseKouichi** [comment]
你的红米的闪存有坏块吗？我的显示坏块768，刷有些大一点的固件也是无法启动，或者反复重启。刷自己编译的容量小一点的openwrt固件倒是可以

**Comment by Guxing0321** [comment]
Hi All,

经过多次尝试，我的内存不存在坏块，
最终是通过先刷一个5M左右的kernel包，然后，在线升级30M左右的sysupgrade包成功的
感谢大佬们的支持

BR
Robin
