### ISSUE TITLE
K2p 无法中继喽。

### ISSUE THREAD

**Issue by aptx486987** [coolsnowwolf/lede#6221]
K2p 无法中继喽。无线扩展完，5G信号不能用，MTWIFI也刷不出来了。

**Comment by brightsm** [comment]
遇到同样问题，根据日志分析，缺少wireless-tools中的iwpriv命令，下载了一个，依然有错误。显示脚本中apcli_5g rax0 connect -s aWiFi-6G -b 4a:a8:01:6b:87:c3 -k 88888888 这一行有错误，apcli_5g notfound，百度了资料apcli_5g这个东东没有找到有用的参考，麻烦管理员看一下。

**Comment by brightsm** [comment]
遇到同样问题，根据日志分析，缺少wireless-tools中的iwpriv命令，下载了一个，依然有错误。显示脚本中apcli_5g rax0 connect -s aWiFi-6G -b 4a:a8:01:6b:87:c3 -k 88888888 这一行有错误，apcli_5g notfound，百度了资料apcli_5g这个东东没有找到有用的参考，麻烦管理员看一下。
