### ISSUE TITLE
关于用 XRAY 替代 Trojan-Go 和 Socks5 Relay  Redirect（Redsocks2）的讨论

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#6226]
最近 XRAY 的更新更好的支持了 Trojan 模式，包括 UDP Fullcone，也更好的支持了 WS

由于 16M ROM 体积限制，如果同时集成 XRAY 和 Trojan-Go 必然会炸

是否应该用 XRAY 替代 Trojan-Go 和 Socks5 Relay Redirect（Redsocks2）呢？

**Comment by zh15933** [comment]
替代吧

**Comment by accors** [comment]
最好替代

**Comment by yushum** [comment]
你问我支持不支持，我说支持。我就明确的告诉你这一点。

**Comment by lhy0838** [comment]
Xray

**Comment by wutaoll** [comment]
支持替代！

**Comment by gjy316** [comment]
必须替代

**Comment by coolsnowwolf** [comment]
顺便替换 SS AEAD 如何？

**Comment by alienaltman** [comment]
放16M一条生路吧

**Comment by 68cs** [comment]
一定要替代

**Comment by feiyue789** [comment]
支持替代

**Comment by SilverHunterLib** [comment]
支持替代

**Comment by zgc** [comment]
代替掉吧

**Comment by kingdapang** [comment]
支持替代！trojan-go已经很久没有更新了，xray还支持trojan xtls 更多黑科技值得拥有！

**Comment by delury** [comment]
替代吧。

**Comment by frely** [comment]
打酱油，不过16M确实可以舍弃了。

**Comment by waterun** [comment]
xray

**Comment by houpi** [comment]
Xray

**Comment by MoeGrid** [comment]
支持替代

**Comment by KC9226** [comment]
xray

**Comment by pegguo** [comment]
trojan go is better!

**Comment by AkinoKaede** [comment]
目前有开发者在为 Xray 添加 SMux，待此项工作完成后，Xray 应该能支持 Trojan-Go 的所有功能。
话说有没有考虑过更好地利用 V2Ray (Xray) 中的路由功能。

**Comment by PaulYoung0265** [comment]
支持替换，搞起来，这样客户端可以简化却又能灵活使用

**Comment by WXfeng-boy** [comment]
支持替代

**Comment by black-head** [comment]
支持替代

**Comment by C222l** [comment]
支持替代！

**Comment by swxk521** [comment]
支持，吧trojan，ss都替换了，精简精简

**Comment by langliang3241** [comment]
支持替代

**Comment by Myoko** [comment]
替换吧

**Comment by xraylf** [comment]
支持替代

**Comment by betaxab** [comment]
低端可以只有 xray。但 16M 不是应该废弃了吗？？？？？？？？？？

**Comment by jiuqi9997** [comment]
我说，支持。强烈支持。

**Comment by Fiber-Five** [comment]
替代

**Comment by luojun853** [comment]
支持替代

**Comment by gsblay** [comment]
支持替代 ！！

**Comment by guanhemeng** [comment]
支持加入xray，那边的开发比较活跃能带来持续的新特性和维护

**Comment by BOBINIUNIU** [comment]
我刚把trojan go 装好，你们又搞出这样一个新玩意。一定要问我支持不支持，我们怎么能不支持大佬？
既然大佬有钦定的意思，那就别按基本法了。16M的路由器？赶紧丢到垃圾桶里去吧，它们本来就应该在那里。

**Comment by NagaseKouichi** [comment]
替代之后还能用Socks5套娃吗？

**Comment by realsteam** [comment]
替换吧，一个能囊括的，就没必要搞多个。

**Comment by haoweili** [comment]
替代吧

**Comment by dolphinpaopao** [comment]
ss移动端目前的支持是比较完善易用的。私人环境，简洁方便的ss还是首选。希望还是能保留ss-libev或者切换到正在积极开发的rust版本，感谢。使用人数众多的机场一般才需要各种混淆套娃规避一定的运营风险。

**Comment by bwtogo** [comment]
支持大佬

**Comment by jxph1123** [comment]
强烈支持统一，节约空间。。

**Comment by martin0607** [comment]
如果是SSR先用Sock5转发是不是就必须勾选Xray了呢？

**Comment by helianling** [comment]
代替吧，xray就该一统天下。

**Comment by helianling** [comment]
建议X86平台空间大，保持不变，其他平台可适度精简。

**Comment by Marcotso** [comment]
支持替换

**Comment by lanfenglin** [comment]
支持替换

**Comment by SamoyeHN** [comment]
已经替代了，256M

**Comment by lanfenglin** [comment]
支持替换

**Comment by NeedforGit** [comment]
目前 Xray 1.22 的 trojan+xtls 玩游戏 貌似还无法 Fullcone, Trojan-go 的可以。所以可不可以晚些时候再替换？让Xray再更新几个版本。

**Comment by lqhorochi** [comment]
既然全面功能,可以替代,越精简越好...喜欢简介方案

**Comment by openwrt-try** [comment]
我说今天怎么编译都体积过大，唉，一声叹息

**Comment by pop2006** [comment]
为什么要替换？不是编译的时候需要什么功能就自己加上去的吗？

**Comment by badO1a5A90** [comment]
> 目前 Xray 1.22 的 trojan+xtls 玩游戏 貌似还无法 Fullcone, Trojan-go 的可以。所以可不可以晚些时候再替换？让Xray再更新几个版本。

从Xray v1.2.1 开始就支持fullcone了。详情可以参见
https://github.com/XTLS/Xray-core/releases/tag/v1.2.1

**Comment by firkerword** [comment]
支持替代

**Comment by Michaol** [comment]
支持Xray

**Comment by Pastechn** [comment]
支持替换 充分考虑小rom

**Comment by djmao** [comment]
大调加入eqos

**Comment by djmao** [comment]
大雕加入eqos

**Comment by y9858** [comment]
换 XRAY全能

**Comment by aceslup** [comment]
xray全能的话，其实可以替换的

**Comment by fxsing** [comment]
支持！！！代替！

**Comment by qxzg** [comment]
资瓷+1

**Comment by 36h** [comment]
替换吧  最好能更新一个在线更新Xray版本

**Comment by nicholassun** [comment]
> 目前 Xray 1.22 的 trojan+xtls 玩游戏 貌似还无法 Fullcone, Trojan-go 的可以。所以可不可以晚些时候再替换？让Xray再更新几个版本。

Xray-core支持的Trojan是Trojan-gfw，可实现Fullcone，且性能在udp over tcp的协议中表现不错

**Comment by zhang5389** [comment]
支持支持。

**Comment by necoic** [comment]
支持替换

**Comment by fengsweet** [comment]
支持替代

**Comment by 467815891a** [comment]
支持！节省空间而且维护也方便

**Comment by willisworley** [comment]
很讨厌xray集成别人的东西，把别人开源优良的东西，打包集成在自己身上，最后自己又出问题。Trojan开发者同意，就当我没说，要有开发的方向啊，我还是蛮喜欢madeye的

**Comment by mcbbsandnz** [comment]
不支持，如果xray出了问题就都出问题了，还不如分开

**Comment by guanhemeng** [comment]
> 很讨厌xray集成别人的东西，把别人开源优良的东西，打包集成在自己身上，最后自己又出问题。Trojan开发者同意，就当我没说，要有开发的方向啊，我还是蛮喜欢madeye的

奇怪的想法，trojan是协议，trojan-gfw/go只是一种实现。v2本来就是个平台，集成了ss/vmess/trojan/mtproto。又不违反开源许可证，你也可以基于它们自己维护个分支。
按照你这种想法，clash和netch它们做的实现有经过上游的许可？

**Comment by Clackz** [comment]
> 很讨厌xray集成别人的东西，把别人开源优良的东西，打包集成在自己身上，最后自己又出问题。Trojan开发者同意，就当我没说，要有开发的方向啊，我还是蛮喜欢madeye的

开源的目的不就是互相交流，促进技术的进步？只要遵守开源协议的行为开发者都是默认同意的吧

**Comment by AkinoKaede** [comment]
> 很讨厌xray集成别人的东西，把别人开源优良的东西，打包集成在自己身上，最后自己又出问题。Trojan开发者同意，就当我没说，要有开发的方向啊，我还是蛮喜欢madeye的

V姐当年的定义就是 All in One，你知道 V2Ray 的 Trojan 是 Trojan-Go 的作者亲自 PR 的吗？V2Ray 在实现这么多协议的时候，甚至不使用第三方库，而是自己重写。

**Comment by SekiBetu** [comment]
> 很讨厌xray集成别人的东西，把别人开源优良的东西，打包集成在自己身上，最后自己又出问题。Trojan开发者同意，就当我没说，要有开发的方向啊，我还是蛮喜欢madeye的

按你的说法，被替换的 Trojan-go 也是"把别人开源优良的东西，打包集成在自己身上"

**Comment by dc021026** [comment]
你好，不知道是我的K2P路由问题还是别的问题  使用https://www.right.com.cn/forum/thread-3135031-1-1.html这个中继正常，别的固件都不行，基本就是搜索到不到中文的wifi，搜到就是字母的，知道哪个连上去也是不行的，请帮看下，也许很多人也有这个问题
