### ISSUE TITLE
xray更新1.2.3 稳定版了

### ISSUE THREAD

**Issue by BOBINIUNIU** [coolsnowwolf/lede#6234]
大佬抽时间更新一下.  另外提一个小建议，如果加入更新执行文件的功能就好了，就不用手动去替换或者重新编译固件了。

**Comment by openwrt-try** [comment]
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

who know why ?
I have already git pull and feeds updated.

**Comment by aorosora** [comment]
编译的时候添加v2ray服务器就好了
