### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by jqglv** [coolsnowwolf/lede#6237]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译的时候，每次都是以详细日志里面的内容结束，这是什么原因？

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：cc1: some warnings being treated as errors

scripts/Makefile.build:261: recipe for target '/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.o' failed
make[5]: *** [/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.o] Error 1
Makefile:1732: recipe for target '/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0' failed
make[4]: *** [/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0] Error 2
make[4]: Leaving directory '/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.91'
Makefile:41: recipe for target '/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/.built' failed
make[3]: *** [/home/mc/openwrt/lede/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/.built] Error 2
make[3]: Leaving directory '/home/mc/openwrt/lede/package/OpenAppFilter/oaf'
time: package/OpenAppFilter/oaf/compile#0.69#0.30#0.96
package/Makefile:111: recipe for target 'package/OpenAppFilter/oaf/compile' failed
make[2]: *** [package/OpenAppFilter/oaf/compile] Error 2
make[2]: Leaving directory '/home/mc/openwrt/lede'
package/Makefile:107: recipe for target '/home/mc/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/mc/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mc/openwrt/lede'
/home/mc/openwrt/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by EnnawYang** [comment]
OpenAppFilter编译错误请到软件作者那边提交issue
