### ISSUE TITLE
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6238]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by feheadls** [comment]
编辑这个文件，package/feeds/helloworld/luci-app-ssr-plus/Makefile，把depend on后面的xray依赖那行删除即可。

**Comment by Cathgao** [comment]
重新feeds update和install

**Comment by SamoyeHN** [comment]
全删了，可以。

**Comment by teapethu** [comment]
说移到feeds里了，但是好像feeds里也没有啊，是L大忘了更新feeds了吗？

**Comment by dlj390** [comment]
same issue！

**Comment by Cathgao** [comment]
去掉feeds里helloword的注释重新update和install就行了，多看看这边和那边的commit

**Comment by dlj390** [comment]
@Cathgao feeds中的注释早就去掉了，update & install也反复做过了，这个问题依旧存在，不太明白你的建议。

**Comment by dlj390** [comment]
解决了，要手动配置个软链接。

**Comment by spypie** [comment]
> 解决了，要手动配置个软链接。

愿闻其详

**Comment by fairok** [comment]
> 
> 
> 解决了，要手动配置个软链接。

这个大哥，怎么配置的啊？我也一样的错误
