### ISSUE TITLE
ros的kvm虚拟openwrt

### ISSUE THREAD

**Issue by sf2322571** [coolsnowwolf/lede#6242]
反馈bug/问题模板，提建议请删除
![QQ截图20210122204415](https://user-images.githubusercontent.com/75937473/105619429-a59cfb80-5e2d-11eb-8b35-68359f6a0f7d.png)
ros的kvm虚拟openwrt会出现卡死  4.19版本的openwrt没有问题 5.4以后的版本就好卡死
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by cdmxp** [comment]
我也是这个问题，现在暂时用老版本，不知道怎么解决
