### ISSUE TITLE
为什么用第三方源编译了PPTP无法运行

### ISSUE THREAD

**Issue by kuyendy** [coolsnowwolf/lede#6244]
L大取消了PPTP，因工作需要必须要用到PPTP，所以从第三方源加入了PPTP，但编译后的固件PPTP启用后始终显示未运行，查看启动项始终是自动启动被禁止，且无法启用，请教是哪里出了问题？

**Comment by gbngbngbn** [comment]
问题已解决，请关闭

**Comment by chchia** [comment]
PPTP有在啊？今天最新pull都还在我一直都有在用。

![image](https://user-images.githubusercontent.com/1291771/105793194-a8c9f000-5fc3-11eb-86df-2317231606af.png)
