### ISSUE TITLE
最新版本有个警告信息。

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#6248]
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

我需要删了后重新拉源码吗

**Comment by zhouym233** [comment]
同问，遇到相同警告

**Comment by star-o0O** [comment]
feeds配置文件里面SSR被注释掉了，取消注释，重新拉取安装feeds

**Comment by jxph1123** [comment]
> 同问，遇到相同警告
> 
> 已解决，
> 先 `rm -rf ./tmp && rm -rf .config`
> 再 `./scripts/feeds update -a && ./scripts/feeds install -a`
> 后恢复正常。

好的谢谢
