### ISSUE TITLE
新老代码是否可以合并使用编译？

### ISSUE THREAD

**Issue by 9E307** [coolsnowwolf/lede#626]
现在源码删掉了大雕开发的特色功能IPK，那我想请问一下我现在自己如果git pull最新版源码，然后把以前保留的那些特色IPK加到最新代码里再去编译。是否就可以在保持更新的同时依然可以用上大雕开发特色功能？

**Comment by LitCcc** [comment]
理论上是可以的，恩山有帖子

**Comment by zcluo** [comment]
为啥删了

发自我的 iPhone
