### ISSUE TITLE
屌大的进

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#6263]
改默认网关为10.1.1.1，下面的
*) ipad=${ipaddr:-"192.168.$((addr_offset++)).1"} ;;
要同步修改为*) ipad=${ipaddr:-"10.1.$((addr_offset++)).1"} ;;
吗？
![Snipaste_2021-01-26_16-51-30](https://user-images.githubusercontent.com/10294460/105822351-f3189480-5ff6-11eb-8f32-a0a583a3d02a.png)

**Comment by Beginner-Go** [comment]
要的

**Comment by lloyd18** [comment]
> 要的

谢谢
