### ISSUE TITLE
编译卡在ssr，提示缺少依赖：xray，前面都正常的，就这两天开始出现这情况

### ISSUE THREAD

**Issue by loydcheung** [coolsnowwolf/lede#6265]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by XiaoliChan** [comment]
```
make dirclean
./scripts/feeds update -a && ./scripts/feeds install -a
```

**Comment by loydcheung** [comment]
delete the helloworld folder and install again will work.

**Comment by tinker-li** [comment]
delete all related folder and install again, in /lede/package/feeds
