### ISSUE TITLE
京东签到今天升级后，又编译不了

### ISSUE THREAD

**Issue by czxinshui** [coolsnowwolf/lede#6269]
mkdir -p /home/water/lede/build_dir/target-x86_64_musl/luci-app-jd-dailybonus-1.0.3/.pkgdir/luci-app-jd-dailybonus
install -d -m0755 /home/water/lede/build_dir/target-x86_64_musl/luci-app-jd-dailybonus-1.0.3/.pkgdir/luci-app-jd-dailybonus/etc/config
install -m0600 ./root/etc/config/jd-dailybonus /home/water/lede/build_dir/target-x86_64_musl/luci-app-jd-dailybonus-1.0.3/.pkgdir/luci-app-jd-dailybonus/etc/config/jd-dailybonus
install: cannot stat './root/etc/config/jd-dailybonus': No such file or directory
Makefile:69: recipe for target '/home/water/lede/build_dir/target-x86_64_musl/luci-app-jd-dailybonus-1.0.3/.pkgdir/luci-app-jd-dailybonus.installed' failed
make[3]: *** [/home/water/lede/build_dir/target-x86_64_musl/luci-app-jd-dailybonus-1.0.3/.pkgdir/luci-app-jd-dailybonus.installed] Error 1
make[3]: Leaving directory '/home/water/lede/package/lean/luci-app-jd-dailybonus'
time: package/lean/luci-app-jd-dailybonus/compile#0.10#0.03#0.17
package/Makefile:111: recipe for target 'package/lean/luci-app-jd-dailybonus/compile' failed
make[2]: *** [package/lean/luci-app-jd-dailybonus/compile] Error 2
make[2]: Leaving directory '/home/water/lede'
package/Makefile:107: recipe for target '/home/water/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/water/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2

**Comment by tcsr200722** [comment]
刚编译，无问题……
