### ISSUE TITLE
红米AC2100WIFI 问题

### ISSUE THREAD

**Issue by czxinshui** [coolsnowwolf/lede#6273]
### (1) 具体问题

A：编译AC2100的固件，在没多拨之前，5g下最高240Mbps左右，用网线测试的时候发现最多跑到240Mbps左右！
多拨之后上传速度叠加成功，下载还是一样在240Mbps左右
还有无线5G设置160MHz，机器重启之后会自动关闭WIFI 需要手动重启
### (2) 路由器型号和固件版本

A：红米AC2100  
OpenWrt R21.1.18

### (3) 详细日志

A：

**Comment by Neverends4** [comment]
无线好像不支持硬件NAT，你用htop之类看测速时是不是单核CPU占满了。
