### ISSUE TITLE
主界面显示连通性和ip地址探针

### ISSUE THREAD

**Issue by ajiter** [coolsnowwolf/lede#6274]
反映N年的问题了。在主界面显示连通性和ip地址探针，求求老大加上吧。要方便很多的。谢谢了。

**Comment by Aes64X** [comment]
何不动手自己发个pr ？不然就是看心情。

**Comment by minlang112** [comment]
自己动手，丰衣足食（不会写代码的我仰望诸位

**Comment by hcym** [comment]
根本不看这些，也没什么鸟用，即使不用负载均衡，也一直开着haproxy，把需要监控的节点加入，网络质量一目了然，
