### ISSUE TITLE
麻烦更新一下npc版本。

### ISSUE THREAD

**Issue by MapesxGM** [coolsnowwolf/lede#6278]
目前源码中npc版本为v0.26.8
最新版本为v0.26.9
编译时把源码中版本该为v0.26.9可以正常编译成功并正常使用，如若方便麻烦更新一下源码中版本，谢谢！

**Comment by ricksuzade-maker** [comment]
已提交PR

**Comment by charley008** [comment]
npc版本已经发布了最新的0.26.10
