### ISSUE TITLE
到底怎么划vlan，愁死了

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#6280]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
虽有，没提出操作可行方案
## 2. 详细叙述
我想划分vlan，但参照openwrt官方文档修改报错

### (1) 具体问题

A：想用大雕的系统，不想用padavan，想通过划分vlan来单线复用iptv
，一直没成功
### (2) 路由器型号和固件版本

A：hc5962

### (3) 详细日志

A：switch报错不存在

**Comment by AmadeusGhost** [comment]
官方 OpenWrt 5.4 内核已经改用 DSA 而不是 swconfig (switch)  了。

**Comment by xiangfeigao** [comment]
查了下，我认为确实是一种进步，与linux统一标准，谢谢
