### ISSUE TITLE
Missing usign

### ISSUE THREAD

**Issue by yeung1981** [coolsnowwolf/lede#6284]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Compilation Error: staging_dir/host/bin/usign No Such File

### (2) 路由器型号和固件版本

A：GL-MV1000

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/69031571/106234747-4deaff80-6234-11eb-90d3-1862351d3404.png)

**Comment by indexofs** [comment]
我也是，你解决了吗？
