### ISSUE TITLE
558不能用了

### ISSUE THREAD

**Issue by muziyulin** [coolsnowwolf/lede#629]
主机名 | OpenWrt
-- | --
主机型号 | Intel(R) Celeron(R) CPU N3160 @ 1.60GHz : 4 Core 4 Thread
CPU温度 | +47.0°C @ 1599.902 MHz
固件版本 | OpenWrt R8.1.5 By Lean / LuCI openwrt-18.06 branch (git-18.138.53009-80cb4fe)
内核版本 | 4.9.131
本地时间 | Mon Oct 8 13:18:27 2018
运行时间 | 0h 18m 17s
平均负载 | 0.01, 0.04, 0.00
2018-10-8凌晨5点突然失联，至今未能用，节点没问题。
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2454749/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2454750/default.txt)
[backup-OpenWrt-2018-10-08.tar.gz](https://github.com/coolsnowwolf/lede/files/2454751/backup-OpenWrt-2018-10-08.tar.gz)

**Comment by nimasi** [comment]
订阅功能可以正常使用吗
