### ISSUE TITLE
请教openwrt能在编译前，直接设置overlay到SD卡吗？

### ISSUE THREAD

**Issue by ajmz** [coolsnowwolf/lede#6292]
如题。

**Comment by sxx1314** [comment]
每张sd卡的uuid和 dev设备名都不同 怎么设置  要么修改uboot从sd卡加载  要么自己写个shell自动扩展overlay

**Comment by ajmz** [comment]
> 每张sd卡的uuid和 dev设备名都不同 怎么设置 要么修改uboot从sd卡加载 要么自己写个shell自动扩展overlay

如果是编译安装好的固件，并且成功overlay到了SD卡，总重新编译呢？
重新编译的固件，uuid和dev设备名会变化吗？
如果没有变化，是否可以在重新编译前，通过修改menuconfig或kernel_menuconfig，或者直接改某个配置文件，输入之前的uuid和dev设备名，实现编译前配置好overlay到SD卡？
对于小内存的硬路由，当然可以编译选择m，只编译不安装，但还是麻烦些。
如果能编译前直接设置，就能menuconfig一次性都选好了。
