### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by birkh8792** [coolsnowwolf/lede#6298]
make[3]: Leaving directory '/home/lic/lede/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/host-compile#0.18#0.04#0.36
make[3]: Entering directory '/home/lic/lede/feeds/helloworld/naiveproxy'
mkdir -p /home/lic/lede/dl
SHELL= flock /home/lic/lede/tmp/.chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata.flock -c '          /home/lic/lede/scripts/download.pl "/home/lic/lede/dl" "chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata" "82e03005e7fb7810a2db7eb9a07bde4c19742ac0b4709ef9e734678d155c04fc" "chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata" "https://storage.googleapis.com.cnpmjs.org/chromium-optimization-profiles/pgo_profiles" "https://storage.googleapis.com/chromium-optimization-profiles/pgo_profiles"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://storage.googleapis.com.cnpmjs.org/chromium-optimization-profiles/pgo_profiles/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1310k    0 1310k    0     0  66027      0 --:--:--  0:00:20 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://storage.googleapis.com/chromium-optimization-profiles/pgo_profiles/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  697k    0  697k    0     0  40571      0 --:--:--  0:00:17 --:--:--     0
curl: (56) Unexpected EOF
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.openwrt.org/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Makefile:139: recipe for target '/home/lic/lede/dl/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata' failed
make[3]: *** [/home/lic/lede/dl/chrome-linux-4324-1610733451-8576f5ff23113bddfb13d417df9ef2a9be1f740d.profdata] Error 2
make[3]: Leaving directory '/home/lic/lede/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#0.31#0.14#42.12
package/Makefile:111: recipe for target 'package/feeds/helloworld/naiveproxy/compile' failed
make[2]: *** [package/feeds/helloworld/naiveproxy/compile] Error 2
make[2]: Leaving directory '/home/lic/lede'
package/Makefile:107: recipe for target '/home/lic/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/lic/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lic/lede'
/home/lic/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
root@lic:/home/lic/lede# git pull
Already up to date.

**Comment by jjit** [comment]
挂代理来编译，或者如果用不到naiveproxy的话
make menuconfig 里取消 naiveproxy
