### ISSUE TITLE
内置Ngrok设置500错误

### ISSUE THREAD

**Issue by 9E307** [coolsnowwolf/lede#630]
在设置Ngrok添加通道的时候，不管填写通道设置与否，保存应用还是直接返回概览，都会反馈：500内部服务器错误

我这里录制了一个gif图片，请参考

![11](https://user-images.githubusercontent.com/20360303/46593720-c4faa800-cb00-11e8-98e0-96b16529e645.gif)

**Comment by 9E307** [comment]
源码版本8.1.6 内核4.14

**Comment by shitizen-x** [comment]
解决了吗老哥，我也遇到这个问题。
