### ISSUE TITLE
系统日志每三个小时产生这个日志怎么关闭？

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6302]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
Sun Jan 31 06:00:00 2021 cron.err crond[4254]: USER root pid 32192 cmd /usr/bin/getnoddosdeviceprofiles;  if [ $? -gt 0 ]; then service noddos reload; fi
Sun Jan 31 09:00:00 2021 cron.err crond[4254]: USER root pid 10236 cmd /usr/bin/getnoddosdeviceprofiles;  if [ $? -gt 0 ]; then service noddos reload; fi
Sun Jan 31 12:00:00 2021 cron.err crond[4254]: USER root pid 20653 cmd /usr/bin/getnoddosdeviceprofiles;  if [ $? -gt 0 ]; then service noddos reload; fi
Sun Jan 31 15:00:00 2021 cron.err crond[4254]: USER root pid 31664 cmd /usr/bin/getnoddosdeviceprofiles;  if [ $? -gt 0 ]; then service noddos reload; fi

没有安装过noddos组件，不知道怎么关闭它
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by XiaoliChan** [comment]
Please check all the entries in you crontab.
