### ISSUE TITLE
SSR PLUS 的GFW模式失效

### ISSUE THREAD

**Issue by datout** [coolsnowwolf/lede#6304]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译了多次，SSR PLUS 的GFW模式失效，无法翻墙，gfw列表也能更新。在绕过大陆模式各异正常访问。

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

**Comment by minlang112** [comment]
提错地方了，请到插件对应的项目页面提交。

**Comment by datout** [comment]
> 提错地方了，请到插件对应的项目页面提交。

好的 了解了
