### ISSUE TITLE
可以在说明里面添加编译前的硬件要求么？

### ISSUE THREAD

**Issue by woalbb** [coolsnowwolf/lede#6313]
我是在家里做nas的小机器上开了个lxc容器扔到里面编译的，一开始出现error不知怎么回事，后来在网络上搜索错误的时候才发现是由于内存或者硬盘不足导致的错误，加大容器的内存和硬盘就可以了。能在说明里面添加编译前的最小硬件需求吗？这样新手不至于因为自己硬件不足导致编译错误而郁闷了。我测试着内存最小1G，硬盘剩余空间要5G以上？请明示，谢谢。

**Comment by mcucore** [comment]
这有啥好写的，既然是编译环境，谁会用连基本系统都跑不清楚的机器。马桶也不用弄个说明书写小于多少厘米屁股会掉进茅坑吧？

**Comment by minlang112** [comment]
建议虚拟机给2G内存，60G-80G的虚拟磁盘空间，其他无所谓……

**Comment by Cathgao** [comment]
没必要，编译本来就是重负载任务，不该拿小霸王来编译

**Comment by gsblay** [comment]
我是虚拟机编译 x86_64 精简 LEDE 的，环境都配置并下载好 DL 目录以后，分配虚拟机16G内存，用NUC8I7 编译，分配4核8线程，耗时2小时；用3960x编译，分配12核，耗时22分钟.
机器不一样，效率差很多！！

**Comment by ricksuzade-maker** [comment]
我本来想用28核56线程的，奈何vmware虚拟机只支持32线程，于是作罢

**Comment by XiaoliChan** [comment]
Why not use **Github Actions Workflow**?
