### ISSUE TITLE
安装ssrp时提示找不到wget-ssl

### ISSUE THREAD

**Issue by zzc1308** [coolsnowwolf/lede#6325]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：在安装luci-app-ssr-plus_183-5_all.ipk包时，提示找不到wget-ssl依赖，但明明是有wget-ssl了，wget-ssl命令行也有提示

### (2) 路由器型号和固件版本

A：GLI-NET MT1300   OpenWrt 19.07.4 r11208-ce6496d796

### (3) 详细日志

A：
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	wget-ssl
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 *

**Comment by XiaoliChan** [comment]
Try to add "`--force-depends`" parameter.
