### ISSUE TITLE
r2s fdisk 报错求助

### ISSUE THREAD

**Issue by vincheese** [coolsnowwolf/lede#6332]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
 [x] 没有类似的issue

### (1) 具体问题

A：fdisk 报错

### (2) 路由器型号和固件版本

A：R2S 21.2.1

### (3) 详细日志

A：
root@OpenWrt:~# fdisk -l
Error relocating /usr/sbin/fdisk: fdisk_label_advparse_parttype: symbol not found
Error relocating /usr/sbin/fdisk: fdisk_label_get_parttype_shortcut: symbol not found
Error relocating /usr/sbin/fdisk: fdisk_label_has_parttypes_shortcuts: symbol not found

**Comment by ZhangStoneRoy** [comment]
same issue. Did u find a solution yet?
