### ISSUE TITLE
i3-3240T刷入5.4内核的固件会一直重启，无法进入路由系统，望大雕能处理下，谢谢！

### ISSUE THREAD

**Issue by Se7enchang** [coolsnowwolf/lede#6335]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Se7enchang** [comment]
i3-3240T x86 刷入新5.4内核的固件会一直重启，接显示器会显示正常启动的前几秒然后就黑屏，路由继续重启，一直循环下去，从老内核的固件直接升级到5.4内核也是同样的问题,不知道是不是兼容性问题还是其他原因，望大雕抽时间看下，谢谢！！！

**Comment by WYC-2020** [comment]
恐怕是你自己没装对吧

**Comment by AmadeusGhost** [comment]
具体描述和日志都没有解决个啥？
