### ISSUE TITLE
UnblockNeteaseMusic  好像还劫持京东的地址

### ISSUE THREAD

**Issue by namebuhtig** [coolsnowwolf/lede#6352]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A： UnblockNeteaseMusic  好像还劫持京东的地址

### (2) 路由器型号和固件版本

A：OpenWrt R21.2.1 / LuCI Master (git-20.343.54716-6fc079f)

### (3) 详细日志

A：打开UnblockNeteaseMusic，放一首歌，再登录jd.com就显示证书不对，点证书就显示是UnblockNeteaseMusic的证书。关掉这个插件就好了。
![Screenshot](https://user-images.githubusercontent.com/4273641/107232013-47def500-6a64-11eb-969b-7022731c6feb.png)

**Comment by namebuhtig** [comment]
我好想明白了，我把京东签到插件删掉后就没问题了。UnblockNeteaseMusic用的nodejs 版本的话好像和京东签到有冲突

**Comment by XiaoliChan** [comment]
Did u mean there are two different version of node have installed ?

**Comment by lydasia** [comment]
以前发现这个还劫持知乎cdn，于是就关掉了。

**Comment by namebuhtig** [comment]
感觉这两个插件都调用nodejs，出差错了

**Comment by XiaoliChan** [comment]
> 感觉这两个插件都调用nodejs，出差错了

Well, the default binary of `UnblockNeteaseMusic` is the GOlang version.

I use it with `JD daily sign in`, it works ordinarily.
