### ISSUE TITLE
希望能加入IP限速插件比如eqos

### ISSUE THREAD

**Issue by djmao** [coolsnowwolf/lede#6354]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by LittleWuXinjiang** [comment]
EQOS，其它源里有提供，但貌似是不是源码太老了、不兼容新版OP了？我尝试编译过，开启后没有任何效果。我现在用SQM，感觉还不错。

**Comment by supppig** [comment]
> EQOS，其它源里有提供，但貌似是不是源码太老了、不兼容新版OP了？我尝试编译过，开启后没有任何效果。我现在用SQM，感觉还不错。

关掉SFE Fast Path再试试

**Comment by xiaobaishu1** [comment]
我用石像鬼QOS固件好用极了迅雷这流氓都能限制![image](https://user-images.githubusercontent.com/53339509/107828873-a2f64c00-6dc4-11eb-8074-e910fbcd60a3.png)

**Comment by hyird** [comment]
> 我用石像鬼QOS固件好用极了迅雷这流氓都能限制![image](https://user-images.githubusercontent.com/53339509/107828873-a2f64c00-6dc4-11eb-8074-e910fbcd60a3.png)

这规则怎么写 看的一脸蒙

**Comment by wlmqwyf** [comment]
> > EQOS，其它源里有提供，但貌似是不是源码太老了、不兼容新版OP了？我尝试编译过，开启后没有任何效果。我现在用SQM，感觉还不错。
> 
> 关掉SFE Fast Path再试试

 我用的是Flow Offload，开启或关闭都没作用。不知道是缺少组件还是怎么回事……

**Comment by xiaobaishu1** [comment]
> > > EQOS，其它源里有提供，但貌似是不是源码太老了、不兼容新版OP了？我尝试编译过，开启后没有任何效果。我现在用SQM，感觉还不错。
> > 
> > 
> > 关掉SFE Fast Path再试试
> 
> 我用的是Flow Offload，开启或关闭都没作用。不知道是缺少组件还是怎么回事……

确实是这样 我就算什么插件都不选就只留一个SQM都一样没什么效果 只有石像鬼QOS有用 迅雷什么都能控制

**Comment by gy39830** [comment]
> 我用石像鬼QOS固件好用极了迅雷这流氓都能限制![image](https://user-images.githubusercontent.com/53339509/107828873-a2f64c00-6dc4-11eb-8074-e910fbcd60a3.png)

求个石像鬼

**Comment by wlmqwyf** [comment]
> > > > EQOS，其它源里有提供，但貌似是不是源码太老了、不兼容新版OP了？我尝试编译过，开启后没有任何效果。我现在用SQM，感觉还不错。
> > > 
> > > 
> > > 关掉SFE Fast Path再试试
> > 
> > 
> > 我用的是Flow Offload，开启或关闭都没作用。不知道是缺少组件还是怎么回事……
> 
> 确实是这样 我就算什么插件都不选就只留一个SQM都一样没什么效果 只有石像鬼QOS有用 迅雷什么都能控制

我这边用的SQM，有不错的效果了。
