### ISSUE TITLE
luci-app-syncdial设置了多拨并上网但不能显示当前在线接口数量！

### ISSUE THREAD

**Issue by zxlhhyccc** [coolsnowwolf/lede#6355]
当前在线接口数量显示为0
![image](https://user-images.githubusercontent.com/45259624/107341707-48c26600-6afa-11eb-9f65-ef95aae985e0.png)

**Comment by star-o0O** [comment]
多拨插件已经很久没有维护了，等一个大佬，我可以提供多线多拨环境供测试。

**Comment by zxlhhyccc** [comment]
> 多拨插件已经很久没有维护了，等一个大佬，我可以提供多线多拨环境供测试。

我是单线多拨环境，可以提供测试！

**Comment by LittleWuXinjiang** [comment]
自己用macvlan创建多个wan口不就行了嘛……
ip link add link （网口） name （新建网口名） type macvlan
就可以了。

**Comment by zxlhhyccc** [comment]
> 自己用macvlan创建多个wan口不就行了嘛……
> ip link add link （网口） name （新建网口名） type macvlan
> 就可以了。

能方便不方便？用插件就方便！！！

**Comment by star-o0O** [comment]
> 自己用macvlan创建多个wan口不就行了嘛……
> ip link add link （网口） name （新建网口名） type macvlan
> 就可以了。

想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。

**Comment by LittleWuXinjiang** [comment]
> > 自己用macvlan创建多个wan口不就行了嘛……
> > ip link add link （网口） name （新建网口名） type macvlan
> > 就可以了。
> 
> 想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。

哦，那感觉很麻烦呢！

**Comment by shu0802** [comment]
> > 自己用macvlan创建多个wan口不就行了嘛……
> > ip link add link （网口） name （新建网口名） type macvlan
> > 就可以了。
> 
> 想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。



> > 自己用macvlan创建多个wan口不就行了嘛……
> > ip link add link （网口） name （新建网口名） type macvlan
> > 就可以了。
> 
> 想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。

> > 自己用macvlan创建多个wan口不就行了嘛……
> > ip link add link （网口） name （新建网口名） type macvlan
> > 就可以了。
> 
> 想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。

> > 自己用macvlan创建多个wan口不就行了嘛……
> > ip link add link （网口） name （新建网口名） type macvlan
> > 就可以了。
> 
> 想用插件的主要原因不是建wan口，主要是并发拨号和掉线重拨，现在掉线重拨（断开并重拨所有wan）已经失效了。其他操作基本都是一次性的都好弄，但拨号就要不停重复操作才行了。

电信双线5拨，一直都正常的使用。只是这个多线仅支持2条线的拨号。
