### ISSUE TITLE
大家有遇到过这种情况吗

### ISSUE THREAD

**Issue by ICLXL** [coolsnowwolf/lede#6358]
![image](https://user-images.githubusercontent.com/30027321/107604579-87c3f900-6c6b-11eb-8549-417ffcac2957.png)

PandoraBox 19.02
newifi3-D2
MTK7621
ssr-plus-1-85
shadowsocksr-libev 2.5.6-3
迫于PandoraBox没找到他们论坛在这来问问大佬们

**Comment by acooler15** [comment]
出什么问题了？

**Comment by ICLXL** [comment]
解决了是因为潘多拉ssr-plush 源 版本落后的问题然后更新的订阅链接存在重复域名和不同端口 导致无法更新
