### ISSUE TITLE
AC58U,刷机后重启进luci出错

### ISSUE THREAD

**Issue by wushuqing** [coolsnowwolf/lede#636]
版本 R8.1.6
ac58u刷机后，断电重启进luci，提示密码错误，ssh和winscp均无法链接。
因无法进入系统无法提供日志。
![1](https://user-images.githubusercontent.com/33998317/46615970-2005bc80-cb4c-11e8-972b-bd0f31cff3c4.png)

**Comment by hcym** [comment]
我也遇到，刷那个trx格式的内存直接崩溃，只好用以前的初始化trx固件重新刷机，再进去刷bin格式的新固件，目前基本正常，462版本的v2ray也运行顺畅。感谢大雕
