### ISSUE TITLE
MTK闭源驱动如何设置MAC白名单？

### ISSUE THREAD

**Issue by OROKIN** [coolsnowwolf/lede#6363]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：MTK闭源驱动如何设置 AP 的 MAC 白名单？是不是只有开源驱动可以设置？

### (2) 路由器型号和固件版本

A：Newifi D2

### (3) 详细日志

A：

**Comment by acooler15** [comment]
设置AccessPolicy和AccessControlList，AccessPolicy的值有0（关闭）、1（白名单）、2（黑名单），AccessControlList的值的格式为`mac地址;mac地址;mac地址`,mac地址英文应小写

**Comment by OROKIN** [comment]
> 设置AccessPolicy和AccessControlList，AccessPolicy的值有0（关闭）、1（白名单）、2（黑名单），AccessControlList的值的格式为`mac地址;mac地址;mac地址`,mac地址英文应小写

谢谢！请问 MAC 地址分隔符应该是 `:`（比如 `00:11:22:33:44:55`） 还是 `-`（比如 `00-11-22-33-44-55`）？

**Comment by acooler15** [comment]
> > 设置AccessPolicy和AccessControlList，AccessPolicy的值有0（关闭）、1（白名单）、2（黑名单），AccessControlList的值的格式为`mac地址;mac地址;mac地址`,mac地址英文应小写
> 
> 谢谢！请问 MAC 地址分隔符应该是 `:`（比如 `00:11:22:33:44:55`） 还是 `-`（比如 `00-11-22-33-44-55`）？

![image](https://user-images.githubusercontent.com/19186382/107844152-048dd900-6e0c-11eb-8ff2-22ddafa90c5d.png)

**Comment by acooler15** [comment]
[mtk_wi-fi_softap_software_programming_guide_v4.6](https://widora.io/_media/mtk_wi-fi_softap_software_programming_guide_v4.6.pdf) 可以看下文档

**Comment by OROKIN** [comment]
> [mtk_wi-fi_softap_software_programming_guide_v4.6](https://widora.io/_media/mtk_wi-fi_softap_software_programming_guide_v4.6.pdf) 可以看下文档

谢谢~
