### ISSUE TITLE
请问一下NAT回流的问题解决了吗

### ISSUE THREAD

**Issue by hipteromyini** [coolsnowwolf/lede#6370]
求教最新版本能否在内网通过wan口ip访问了

**Comment by NagaseKouichi** [comment]
https://github.com/coolsnowwolf/lede/issues/6149

**Comment by firker** [comment]
一直都可以

**Comment by jimgo188** [comment]
好像之前编译了docker就不行，我没加docker就没这个问题。不知现在解决没有
