### ISSUE TITLE
最近出现的由于go程序编译出错而导致固件编译失败的暂时解决方案

### ISSUE THREAD

**Issue by KFERMercer** [coolsnowwolf/lede#6373]
### 注意: 此方法只适合自行编写.config云编译的用户, 本机生成.config上传然后云编译的用户勿用!!!

很简单, 在你的config的最后添加三行代码:

```
# CONFIG_v2ray-plugin_INCLUDE_GOPROXY is not set
# CONFIG_XRAY_CORE_COMPRESS_GOPROXY is not set
# CONFIG_UnblockNeteaseMusicGo_INCLUDE_GOPROXY is not set
```

如图: 

![image](https://user-images.githubusercontent.com/37098748/107910453-6c236000-6f95-11eb-8101-4d8cce2a8dea.png)

**Comment by hcym** [comment]
一直正常编译的，昨天前天用官方master编译golang也是如此，用tun都不行，难怪，😂
