### ISSUE TITLE
机型：极路由B70 问题：WiFi连接一阵子后无法使用 必须重新连接WiFi才可以

### ISSUE THREAD

**Issue by Fsick** [coolsnowwolf/lede#639]
详细描述：
手机及电脑连接WiFi后使用一段时间，WiFi连接正常，但不能使用网络。机型：iPhone7、6s、5s，努比亚z17、z17mini等，电脑：雷神911M。 网络断连时间长短不定。
日志：
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2460535/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2460536/default.txt)
自编译文件：
[hiwifi hc5962.zip](https://github.com/coolsnowwolf/lede/files/2460547/hiwifi.hc5962.zip)

**Comment by Fsick** [comment]
重新编译了最新版本  待测试

**Comment by Fsick** [comment]
编译了最新的版本，问题依旧是这样，必须手动重新连接WiFi。
日志：
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2460796/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2460797/default.txt)
自编译文件：
[hiwifi hc5962.zip](https://github.com/coolsnowwolf/lede/files/2460830/hiwifi.hc5962.zip)

**Comment by myselfghost** [comment]
附议，HC5962，WiFi连接正常，但不能使用网络

**Comment by Fsick** [comment]
> 附议，HC5962，无线网络连接正常，但不能使用网络

MJ大给出的修复方法：DHCP更改租期时长为24H，2.4G和5G信道选为固定信道值。更改后暂时没有问题。
