### ISSUE TITLE
大雕的 PLUS+ ,和PASSWALL ，不能同时编译，不然就无法编译成功

### ISSUE THREAD

**Issue by souwei168** [coolsnowwolf/lede#6394]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[3] diffconfig buildversion feedsversion
 make[2] package/cleanup
 make[2] package/compile
 make[3] -C package/libs/libjson-c host-compile
 make[3] -C package/libs/libubox host-compile
 make[3] -C package/system/opkg host-compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/libnl-tiny compile
 make[3] -C package/libs/libjson-c compile
 make[3] -C package/utils/lua compile
 make[3] -C package/libs/libubox compile
 make[3] -C package/system/ubus compile
 make[3] -C package/system/uci compile
 make[3] -C package/network/config/netifd compile
 make[3] -C package/firmware/linux-firmware compile
 make[3] -C package/firmware/prism54-firmware compile
 make[3] -C package/kernel/linux compile
 make[3] -C package/system/ubox compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/libs/zlib compile
 make[3] -C package/libs/ncurses compile
 make[3] -C package/utils/util-linux compile
 make[3] -C package/system/fstools compile
 make[3] -C package/system/fwtool host-compile
 make[3] -C package/system/fwtool compile
 make[3] -C package/system/procd compile
 make[3] -C package/system/usign host-compile
 make[3] -C package/system/ucert host-compile
 make[3] -C package/utils/jsonfilter compile
 make[3] -C package/system/openwrt-keyring compile
 make[3] -C package/system/usign compile
 make[3] -C package/base-files compile
 make[3] -C package/boot/grub2 host-compile
 make[3] -C package/boot/grub2 compile
 make[3] -C package/boot/grub2 compile
 make[3] -C package/libs/gettext compile
 make[3] -C package/libs/libiconv compile
 make[3] -C package/devel/binutils compile
 make[3] -C feeds/packages/lang/golang/golang host-compile
 make[3] -C package/system/ca-certificates compile
 make[3] -C feeds/helloworld/xray-core compile
 make[3] -C feeds/packages/libs/libmaxminddb compile
 make[3] -C feeds/kenzo/lua-maxminddb compile
 make[3] -C package/libs/mbedtls compile
 make[3] -C package/kernel/cryptodev-linux compile
 make[3] -C package/libs/openssl compile
 make[3] -C package/libs/ustream-ssl compile
 make[3] -C package/libs/uclient compile
 make[3] -C package/libs/uclibc++ compile
 make[3] -C package/libs/pcre compile
 make[3] -C package/lean/wget compile
 make[3] -C feeds/kenzo/luci-app-adguardhome compile
 make[3] -C feeds/luci/modules/luci-base host-compile
 make[3] -C package/utils/lua host-compile
 make[3] -C feeds/kenzo/luci-app-advancedsetting compile
 make[3] -C feeds/luci/libs/luci-lib-ip compile
 make[3] -C feeds/luci/libs/luci-lib-jsonc compile
 make[3] -C feeds/luci/libs/luci-lib-nixio compile
 make[3] -C package/network/utils/iwinfo compile
 make[3] -C package/system/rpcd compile
 make[3] -C feeds/luci/modules/luci-base compile
 make[3] -C package/libs/readline compile
 make[3] -C feeds/packages/utils/bash compile
 make[3] -C feeds/packages/utils/attr compile
 make[3] -C feeds/packages/utils/acl compile
 make[3] -C feeds/packages/libs/libcap compile
 make[3] -C package/libs/gmp compile
 make[3] -C feeds/packages/utils/coreutils compile
 make[3] -C package/network/utils/curl compile
 make[3] -C package/libs/libmnl compile
 make[3] -C package/network/utils/ipset compile
 make[3] -C package/network/utils/iptables compile
 make[3] -C feeds/kenzo/luci-app-clash compile
 make[3] -C package/utils/bzip2 compile
 make[3] -C package/libs/argp-standalone compile
 make[3] -C package/libs/elfutils compile
 make[3] -C package/network/utils/iproute2 compile
 make[3] -C package/network/utils/iproute2 compile
 make[3] -C package/pack/luci-app-eqos-master compile
 make[3] -C feeds/kenzo/luci-app-eqos compile
 make[3] -C feeds/packages/libs/libxml2 compile
 make[3] -C feeds/packages/libs/db47 compile
 make[3] -C feeds/packages/libs/gdbm compile
 make[3] -C feeds/packages/libs/libffi compile
 make[3] -C feeds/packages/lang/ruby host-compile
 make[3] -C feeds/packages/libs/yaml compile
 make[3] -C feeds/packages/lang/ruby compile
 make[3] -C package/network/services/dnsmasq compile
 make[3] -C feeds/kenzo/luci-app-openclash compile
 make[3] -C feeds/kenzo/tcping compile
 make[3] -C feeds/packages/utils/unzip compile
 make[3] -C package/network/utils/resolveip compile
 make[3] -C package/pack/1/openwrt-passwall/ipt2socks compile
 make[3] -C package/pack/1/openwrt-passwall/microsocks compile
 make[3] -C package/pack/1/openwrt-passwall/pdnsd-alt compile
 make[3] -C feeds/packages/libs/c-ares compile
 make[3] -C feeds/packages/libs/libev compile
 make[3] -C feeds/packages/libs/libsodium compile
 make[3] -C feeds/packages/net/shadowsocks-libev compile
 make[3] -C package/pack/1/openwrt-passwall/shadowsocksr-libev compile
 make[3] -C feeds/small/trojan-go compile
 make[3] -C feeds/packages/libs/boost host-compile
 make[3] -C feeds/packages/utils/xz compile
 make[3] -C feeds/packages/devel/ninja host-compile
 make[3] -C feeds/packages/devel/meson host-compile
 make[3] -C feeds/packages/utils/zstd compile
 make[3] -C feeds/packages/lang/python/python-pip-conf compile
 make[3] -C feeds/packages/libs/expat host-compile
 make[3] -C feeds/packages/libs/libffi host-compile
 make[3] -C package/utils/bzip2 host-compile
 make[3] -C feeds/packages/lang/python/python3 host-compile
 make[3] -C feeds/packages/libs/libedit compile
 make[3] -C feeds/packages/libs/sqlite3 compile
 make[3] -C feeds/packages/lang/python/python3 compile
 make[3] -C feeds/packages/libs/boost compile
 make[3] -C feeds/small/trojan-plus compile
 make[3] -C package/pack/1/openwrt-passwall/dns2socks compile
 make[3] -C package/libs/libtool compile
 make[3] -C package/utils/lua5.3 compile
 make[3] -C feeds/packages/net/haproxy compile
 make[3] -C package/pack/1/openwrt-passwall/simple-obfs compile
 make[3] -C package/pack/1/openwrt-passwall/v2ray-plugin compile
 make[3] -C feeds/kenzo/luci-app-passwall compile
 make[3] -C feeds/packages/net/smartdns compile
 make[3] -C feeds/kenzo/luci-app-smartdns compile
 make[3] -C package/libs/libevent2 compile
 make[3] -C package/lean/redsocks2 compile
 make[3] -C package/pack/1/openwrt-passwall/trojan compile
 make[3] -C feeds/kenzo/luci-app-ssr-plus compile
 make[3] -C feeds/packages/lang/luasocket compile
 make[3] -C feeds/kenzo/luci-app-vssr compile
 make[3] -C feeds/kenzo/luci-theme-atmaterial compile
 make[3] -C feeds/kenzo/luci-theme-opentopd compile
 make[3] -C package/lean/openwrt-fullconenat compile
 make[3] -C package/network/config/firewall compile
 make[3] -C feeds/luci/applications/luci-app-firewall compile
 make[3] -C feeds/luci/modules/luci-mod-admin-full compile
 make[3] -C feeds/luci/protocols/luci-proto-ppp compile
 make[3] -C feeds/luci/themes/luci-theme-bootstrap compile
 make[3] -C feeds/luci/libs/rpcd-mod-rrdns compile
 make[3] -C package/network/services/uhttpd compile
 make[3] -C feeds/luci/collections/luci compile
 make[3] -C feeds/packages/net/aria2 compile
 make[3] -C feeds/packages/net/nginx-util compile
 make[3] -C feeds/packages/net/uwsgi compile
 make[3] -C feeds/packages/net/nginx compile
 make[3] -C feeds/packages/net/ariang compile
 make[3] -C feeds/luci/applications/luci-app-aria2 compile
 make[3] -C feeds/packages/libs/libuv compile
 make[3] -C feeds/packages/net/bind compile
 make[3] -C feeds/packages/net/ddns-scripts compile
 make[3] -C feeds/luci/applications/luci-app-ddns compile
 make[3] -C feeds/luci/applications/luci-app-diag-core compile
 make[3] -C feeds/packages/utils/hd-idle compile
 make[3] -C feeds/luci/applications/luci-app-hd-idle compile
 make[3] -C feeds/packages/libs/flac compile
 make[3] -C feeds/packages/libs/libexif compile
 make[3] -C feeds/packages/libs/libid3tag compile
 make[3] -C feeds/packages/libs/libjpeg-turbo compile
 make[3] -C feeds/packages/libs/libogg compile
 make[3] -C feeds/packages/libs/libvorbis compile
 make[3] -C feeds/packages/libs/alsa-lib compile
 make[3] -C package/libs/nettle compile
 make[3] -C feeds/packages/libs/gnutls compile
 make[3] -C feeds/packages/sound/fdk-aac compile
 make[3] -C feeds/packages/sound/lame compile
 make[3] -C feeds/packages/libs/opus compile
 make[3] -C feeds/packages/multimedia/ffmpeg compile
 make[3] -C feeds/packages/multimedia/minidlna compile
 make[3] -C feeds/luci/applications/luci-app-minidlna compile
 make[3] -C feeds/packages/net/mwan3 compile
 make[3] -C feeds/luci/applications/luci-app-mwan3 compile
 make[3] -C feeds/packages/net/nlbwmon compile
 make[3] -C feeds/luci/applications/luci-app-nlbwmon compile
 make[3] -C feeds/luci/applications/luci-app-openvpn compile
 make[3] -C feeds/packages/net/pagekitec compile
 make[3] -C feeds/luci/applications/luci-app-pagekitec compile
 make[3] -C package/network/services/samba36 compile
 make[3] -C feeds/luci/applications/luci-app-samba compile
 make[3] -C feeds/packages/libs/libnatpmp compile
 make[3] -C feeds/packages/net/miniupnpc compile
 make[3] -C feeds/packages/net/transmission compile
 make[3] -C feeds/packages/net/transmission-web-control compile
 make[3] -C feeds/luci/applications/luci-app-transmission compile
 make[3] -C feeds/luci/applications/luci-app-uhttpd compile
 make[3] -C feeds/packages/net/miniupnpd compile
 make[3] -C feeds/luci/applications/luci-app-upnp compile
 make[3] -C feeds/packages/utils/watchcat compile
 make[3] -C feeds/luci/applications/luci-app-watchcat compile
 make[3] -C feeds/packages/net/etherwake compile
 make[3] -C package/lean/wol compile
 make[3] -C feeds/luci/applications/luci-app-wol compile
 make[3] -C feeds/luci/modules/luci-compat compile
 make[3] -C feeds/luci/libs/luci-lib-json compile
 make[3] -C feeds/luci/protocols/luci-proto-ipv6 compile
 make[3] -C feeds/packages/sound/alsa-utils compile
 make[3] -C feeds/packages/kernel/antfs compile
 make[3] -C feeds/packages/utils/antfs-mount compile
 make[3] -C feeds/packages/libs/expat compile
 make[3] -C feeds/packages/utils/dbus compile
 make[3] -C feeds/packages/libs/libdaemon compile
 make[3] -C feeds/packages/libs/avahi compile
 make[3] -C feeds/packages/libs/avahi compile
 make[3] -C feeds/packages/libs/avahi compile
 make[3] -C feeds/packages/utils/bc compile
 make[3] -C feeds/packages/net/bonding compile
 make[3] -C package/libs/lzo compile
 make[3] -C feeds/packages/utils/btrfs-progs compile
 make[3] -C feeds/packages/utils/cgroupfs-mount compile
 make[3] -C feeds/packages/libs/confuse compile
 make[3] -C feeds/packages/utils/runc compile
 make[3] -C feeds/packages/utils/containerd compile
 make[3] -C feeds/packages/lang/dkjson compile
 make[3] -C feeds/packages/utils/libnetwork compile
 make[3] -C feeds/packages/libs/libaio compile
 make[3] -C feeds/packages/utils/lvm2 compile
 make[3] -C feeds/packages/utils/tini compile
 make[3] -C feeds/packages/utils/docker-ce compile
 make[3] -C feeds/packages/libs/libantlr3c compile
 make[3] -C feeds/packages/libs/libgpg-error compile
 make[3] -C feeds/packages/libs/libgcrypt compile
 make[3] -C feeds/packages/libs/libplist compile
 make[3] -C feeds/packages/libs/libunistring compile
 make[3] -C feeds/packages/libs/libwebsockets compile
 make[3] -C feeds/packages/libs/mxml compile
 make[3] -C feeds/packages/libs/protobuf compile
 make[3] -C feeds/packages/libs/protobuf-c compile
 make[3] -C feeds/packages/sound/forked-daapd compile
 make[3] -C feeds/packages/libs/libpng compile
 make[3] -C feeds/packages/libs/freetype compile
 make[3] -C feeds/packages/utils/fuse compile
 make[3] -C feeds/packages/admin/htop compile
 make[3] -C feeds/packages/libs/icu host-compile
 make[3] -C feeds/packages/libs/icu compile
 make[3] -C package/libs/sysfsutils compile
 make[3] -C feeds/packages/net/iputils compile
 make[3] -C feeds/packages/kernel/ksmbd compile
 make[3] -C feeds/packages/libs/glib2 compile
 make[3] -C package/libs/libnl compile
 make[3] -C feeds/packages/net/ksmbd-tools compile
 make[3] -C feeds/packages/libs/libconfig compile
 make[3] -C feeds/packages/libs/libwebp compile
 make[3] -C feeds/packages/libs/tiff compile
 make[3] -C feeds/packages/libs/libgd compile
 make[3] -C feeds/packages/libs/libhttp-parser compile
 make[3] -C feeds/packages/libs/libsoxr compile
 make[3] -C package/libs/libpcap compile
 make[3] -C feeds/packages/libs/libtins compile
 make[3] -C feeds/packages/libs/libupnp compile
 make[3] -C feeds/packages/libs/libyaml-cpp compile
 make[3] -C feeds/packages/libs/musl-fts compile
 make[3] -C feeds/packages/libs/libzip compile
 make[3] -C feeds/packages/utils/lm-sensors compile
 make[3] -C feeds/packages/lang/lua-bencode compile
 make[3] -C feeds/packages/lang/lua-sha2 compile
 make[3] -C feeds/packages/admin/netdata compile
 make[3] -C package/libs/libnfnetlink compile
 make[3] -C package/libs/libnetfilter-conntrack compile
 make[3] -C feeds/packages/net/noddos compile
 make[3] -C package/libs/nghttp2 compile
 make[3] -C feeds/packages/lang/node compile
 make[3] -C feeds/packages/libs/oniguruma compile
 make[3] -C feeds/packages/net/p910nd compile
 make[3] -C feeds/packages/libs/pcre2 compile
 make[3] -C feeds/packages/lang/php7 compile
 make[3] -C package/network/services/shellsync compile
 make[3] -C package/network/utils/linux-atm compile
 make[3] -C package/network/services/ppp compile
 make[3] -C feeds/packages/net/rp-pppoe compile
 make[3] -C package/libs/popt compile
 make[3] -C feeds/packages/sound/shairport-sync compile
 make[3] -C feeds/packages/mail/msmtp compile
 make[3] -C feeds/packages/mail/nail compile
 make[3] -C feeds/packages/utils/smartmontools compile
 make[3] -C feeds/packages/net/strongswan compile
 make[3] -C feeds/packages/utils/ttyd compile
 make[3] -C feeds/packages/net/wsdd2 compile
 make[3] -C feeds/packages/net/zerotier compile
 make[3] -C feeds/packages/utils/zoneinfo compile
 make[3] -C feeds/routing/cjdns compile
 make[3] -C feeds/small/ssocks compile
 make[3] -C feeds/small/v2ray compile
 make[3] -C package/firmware/wireless-regdb compile
 make[3] -C package/kernel/exfat compile
 make[3] -C package/firmware/b43legacy-firmware compile
 make[3] -C package/libs/wolfssl compile
 make[3] -C package/network/services/hostapd compile
 make[3] -C package/network/utils/iw compile
 make[3] -C package/kernel/mac80211 compile
 make[3] -C package/lean/UnblockNeteaseMusic compile
 make[3] -C package/lean/UnblockNeteaseMusicGo compile
 make[3] -C package/lean/adbyby compile
 make[3] -C package/lean/libcryptopp compile
 make[3] -C package/lean/wxbase compile
 make[3] -C package/lean/amule compile
 make[3] -C package/network/utils/ethtool compile
 make[3] -C package/lean/autocore compile
 make[3] -C package/lean/automount compile
 make[3] -C package/lean/autosamba compile
 make[3] -C package/lean/baidupcs-web compile
 make[3] -C package/lean/coremark compile
 make[3] -C package/lean/ddns-scripts_aliyun compile
 make[3] -C package/lean/ddns-scripts_dnspod compile
 make[3] -C package/lean/default-settings compile
 make[3] -C package/lean/shortcut-fe compile
 make[3] -C package/lean/fast-classifier compile
 make[3] -C package/lean/frp compile
 make[3] -C package/network/ipv6/6in4 compile
 make[3] -C package/network/ipv6/odhcp6c compile
 make[3] -C package/network/services/odhcpd compile
 make[3] -C package/lean/ipv6-helper compile
 make[3] -C package/lean/luci-app-accesscontrol compile
 make[3] -C package/lean/luci-app-adbyby-plus compile
 make[3] -C package/lean/luci-app-airplay2 compile
 make[3] -C package/lean/luci-app-amule compile
 make[3] -C package/lean/luci-app-arpbind compile
 make[3] -C package/lean/luci-app-autoreboot compile
 make[3] -C package/lean/luci-app-baidupcs-web compile
 make[3] -C package/lean/luci-app-cifs-mount compile
 make[3] -C package/lean/luci-app-cifsd compile
 make[3] -C package/lean/parted compile
 make[3] -C package/utils/e2fsprogs host-compile
 make[3] -C package/utils/e2fsprogs compile
 make[3] -C package/utils/mdadm compile
 make[3] -C package/lean/luci-app-diskman compile
 make[3] -C package/lean/luci-app-familycloud compile
 make[3] -C package/lean/luci-lib-fs compile
 make[3] -C package/lean/luci-app-filetransfer compile
 make[3] -C package/lean/luci-app-frpc compile
 make[3] -C package/lean/luci-app-frps compile
 make[3] -C package/lean/luci-app-ipsec-vpnd compile
 make[3] -C package/lean/luci-app-kodexplorer compile
 make[3] -C package/lean/luci-app-music-remote-center compile
 make[3] -C package/lean/n2n_v2 compile
 make[3] -C package/lean/luci-app-n2n_v2 compile
 make[3] -C package/lean/luci-app-netdata compile
 make[3] -C package/lean/npc compile
 make[3] -C package/lean/luci-app-nps compile
 make[3] -C package/network/services/openvpn-easy-rsa compile
 make[3] -C package/network/services/openvpn compile
 make[3] -C package/lean/luci-app-openvpn-server compile
 make[3] -C package/libs/libdouble-conversion compile
 make[3] -C package/lean/qt5 compile
 make[3] -C package/lean/rblibtorrent compile
 make[3] -C package/lean/qBittorrent compile
 make[3] -C package/lean/luci-app-qbittorrent compile
 make[3] -C package/lean/luci-app-ramfree compile
 make[3] -C package/lean/rclone compile
 make[3] -C package/lean/rclone-ng compile
 make[3] -C package/lean/rclone-webui-react compile
 make[3] -C package/lean/luci-app-rclone compile
 make[3] -C package/lean/luci-app-sfe compile
 make[3] -C package/libs/readline host-compile
 make[3] -C package/lean/softethervpn5 host-compile
 make[3] -C package/lean/softethervpn5 compile
 make[3] -C package/libs/libiconv-full compile
 make[3] -C package/lean/luci-app-softethervpn compile
 make[3] -C package/lean/luci-app-syncdial compile
 make[3] -C package/lean/luci-app-ttyd compile
 make[3] -C package/lean/luci-app-unblockmusic compile
 make[3] -C package/lean/luci-app-usb-printer compile
 make[3] -C package/lean/uugamebooster compile
 make[3] -C package/lean/luci-app-uugamebooster compile
 make[3] -C package/lean/luci-app-v2ray-server compile
 make[3] -C package/lean/vlmcsd compile
 make[3] -C package/lean/luci-app-vlmcsd compile
 make[3] -C package/lean/vsftpd-alt compile
 make[3] -C package/lean/luci-app-vsftpd compile
 make[3] -C package/lean/luci-app-webadmin compile
 make[3] -C package/lean/luci-app-xlnetacc compile
 make[3] -C package/lean/luci-app-zerotier compile
 make[3] -C package/lean/luci-lib-docker compile
 make[3] -C package/lean/luci-proto-bonding compile
 make[3] -C package/lean/r8125 compile
 make[3] -C package/lean/r8168 compile
 make[3] -C package/network/services/dropbear compile
 make[3] -C package/network/utils/iperf compile
 make[3] -C package/pack/luci-app-jd-dailybonus compile
 make[3] -C package/system/mtd compile
 make[3] -C package/system/opkg compile
 make[3] -C package/system/urandom-seed compile
 make[3] -C package/system/urngd compile
 make[3] -C package/utils/busybox compile
 make[3] -C package/utils/f2fs-tools compile
 make[2] package/install
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/sw/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 1

A：

**Comment by WYC-2020** [comment]
瞎提，不知道已经有人提了？

**Comment by gsblay** [comment]
一女二嫁！晕！！！

**Comment by souwei168** [comment]
看不懂什么意思 ，能不能解决我的问题呢，这次是把编译输出，给贴出来了，有没有大神能看出是哪里问题？

**Comment by souwei168** [comment]
次次都是到这个封包这里，过不去了，不知道是哪里出问题？make[2] package/install
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/sw/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by ismethr** [comment]
#Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on# 这不写的很清楚吗！话说你为什么非要两个都用

**Comment by souwei168** [comment]
谢谢，已经解决 是大雕，删除 V2RAY源码造成的，编译时，去掉V2RAY，就好，改用X2RAY!
