### ISSUE TITLE
大神，自己编译的固件，阿里ddns异常和adbyby手动更新不能保存！用你编译的固件没这个问题

### ISSUE THREAD

**Issue by d975xbx** [coolsnowwolf/lede#64]
自己编译的固件，阿里ddns异常（远端不会更新IP）。adbyby手动更新规则/usr/share/adbyby/adupdate.sh，重启后还是原始规则。
用你编译的固件没这个问题

**Comment by tomerilery** [comment]
远端不能更新ip是你自己的问题，你需要手动删除record_id的值，让客户端重新建立，就可以同步ip了，adbyby更新服务器遭受未知力量的攻击，需要手动更新，issue里面有，你自己好好看看！

**Comment by d975xbx** [comment]
用L大神的固件没有这个问题，远端可以更新，规则重启以后也没事

**Comment by tomerilery** [comment]
重启需要重新更新，规则更新太快会减少flash寿命，L大考虑到不磨损你们的flash，已经把规则切换到/tmp运存里的，重启当然就没有了

**Comment by d975xbx** [comment]
重启需要重新更新？呵呵！
不是你说的原因，换4.4的内核，阿里ddns也好了，adbyby去掉内存运行就好了。

**Comment by coolsnowwolf** [comment]
权限问题
