### ISSUE TITLE
有时在管理页面重启newifid2后wifi处于关闭状态

### ISSUE THREAD

**Issue by iseeyou** [coolsnowwolf/lede#6400]

**Comment by hnrrn** [comment]
哈哈哈。我也是

**Comment by iseeyou** [comment]
> 
> 
> 哈哈哈。我也是

取研究编译padavan了 O(∩_∩)O

**Comment by iseeyou** [comment]
我又回来了~谁知道咋解决

**Comment by liwenjie119** [comment]
遇到过，清除所有数据后，开机没WiFi，还好笔记本在家，有网线能连上开wifi

**Comment by iseeyou** [comment]
> 遇到过，清除所有数据后，开机没WiFi，还好笔记本在家，有网线能连上开wifi

以防万一，我在 本地启动脚本 加上了
`ifconfig ra0 up   #2Gwifi
ifconfig rai0 up  #5Gwifi`
