### ISSUE TITLE
igb-I350-T4网卡问题

### ISSUE THREAD

**Issue by kuangdongliang** [coolsnowwolf/lede#6423]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
通过exsi虚拟机直通了igb-I350-T4网卡，在lede固件找不到相关驱动，只能有82575，请问佬大能否帮忙加上去呢。

Q：是否搜索了issue (使用 "x" 选择)
* [ x"] 没有类似的issue

### (1) 具体问题
通过exsi虚拟机直通了igb-I350-T4网卡，在lede固件找不到相关驱动，只能有82575，请问佬大能否帮忙加上去呢。

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
![1](https://user-images.githubusercontent.com/75053149/108859939-b6a57c00-7628-11eb-8740-4b54269716af.png)

**Comment by dgulan** [comment]
我也是esxi 直通了。
默认编译固件以后，网卡正常工作的。

**Comment by Aes64X** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> 通过exsi虚拟机直通了igb-I350-T4网卡，在lede固件找不到相关驱动，只能有82575，请问佬大能否帮忙加上去呢。
> 
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ x"] 没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> 通过exsi虚拟机直通了igb-I350-T4网卡，在lede固件找不到相关驱动，只能有82575，请问佬大能否帮忙加上去呢。
> 
> A：
> 
> ### (2) 路由器型号和固件版本
> A：
> 
> ### (3) 详细日志
> A：
> ![1](https://user-images.githubusercontent.com/75053149/108859939-b6a57c00-7628-11eb-8740-4b54269716af.png)

你自己告诉了你自己答案，你自己截图里已经告诉你自己了，igb驱动包含i350

**Comment by minlang112** [comment]
5.4内核好像默认勾选igb驱动的吧……
