### ISSUE TITLE
ping 不走全局代理

### ISSUE THREAD

**Issue by 85178617** [coolsnowwolf/lede#6424]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
ssr plus 里面随便填写SSR或者socks5,开启全局代理后,网页和程序确实没有网了,但是cmd里面ping却还可以ping通.

### (1) 具体问题

A：外服游戏如果通过ping来检测真实的IP用来封号,那这全局还有什么意义

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by ismethr** [comment]
建议先了解一下ping

**Comment by galaxyskyknight** [comment]
用socks代理吧，vmess/vless/trojan这些只代理tcp/udp不代理icmp

**Comment by sxx1314** [comment]
放弃icmp 请用tcping

**Comment by dongjuanyong** [comment]
> 用socks代理吧，vmess/vless/trojan这些只代理tcp/udp不代理icmp

我寻思着SOCKS5也只是TCP/UDP代理啊，代理ICMP只能靠VPN

**Comment by FH0** [comment]
首先你得证明游戏通过 ping 来检测 ip，其次用 vpn 类型的代理，openvpn，wireguard 之类的

**Comment by minlang112** [comment]
楼上该说的都说了，ssr这种东西只代理tcp/udp，icmp包该怎么走还是怎么走的

**Comment by fhbyljj** [comment]
ICMP包是不代理的，这是常识
