### ISSUE TITLE
DDNS功能问题

### ISSUE THREAD

**Issue by czxinshui** [coolsnowwolf/lede#6425]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最近看了油管某主播在介绍爱快DDNS功能的时候，发现爱快的DDNS非常强大，能通过mac地址获取内网机器的IPV6地址，（EUI-64）一个设备绑定，其他就可以不用部署了，实属方便！因为在ipv6情况下，内网机器也能够获得公网地址，但是有些机器无法安装DDNS程序，因此也无法用上这个DDNS的功能了。当然也可以通过配合其他插件的方法实现一台机器DDNS，也能访问其他二级路由以下的东西。但是，科技的发展不就是为了让一件麻烦的事变得更简单吗！

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by leungyauming** [comment]
這跟OpenWrt無關，如果你想討論相關問題，建議到QQ或者Telegram群。
