### ISSUE TITLE
当使用vless分享标准，含有path路径不能识别路径

### ISSUE THREAD

**Issue by langzisuifeng** [coolsnowwolf/lede#6429]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：当vless分享链接中含有path协议时，导入分享链接path参数不能识别。
http伪装tcp协议含有path路径
vless://12345678-1234-1234-1234-1234@abc.com:443?encryption=none&security=tls&type=tcp&headerType=http&path=%2fpath2#xtls_fall_tcp
http伪装ws协议含有path路径
vless://9f88698b-7a1e-47c5-851d-2edaa176f915@abc.com:443?encryption=none&security=tls&type=ws&path=%2fpath3#xlts_fall_ws

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by openwrt-try** [comment]
不填可以用不

**Comment by langzisuifeng** [comment]
不填不能用
