### ISSUE TITLE
能否支持 ecryptfs 和cryfs

### ISSUE THREAD

**Issue by liooge** [coolsnowwolf/lede#6442]
##1. 想用加密文件夹功能
##2. 自己搜索了很久尝试了很多方法都不能搞定
### https://github.com/dustinkirkland/ecryptfs-utils

**Comment by jjit** [comment]
有 rclone：https://github.com/coolsnowwolf/lede/tree/master/package/lean/rclone
也支持 加密文件夹，教程：
https://www.bilibili.com/s/video/BV1dZ4y1N7NR
是 win的教程，在 linux里命令也差不多，路径改成linux的就行了

**Comment by liooge** [comment]
> 
> 
> 有 rclone：https://github.com/coolsnowwolf/lede/tree/master/package/lean/rclone
> 也支持 加密文件夹，教程：
> https://www.bilibili.com/s/video/BV1dZ4y1N7NR
> 是 win的教程，在 linux里命令也差不多，路径改成linux的就行了

谢谢。
