### ISSUE TITLE
端口转发没效果

### ISSUE THREAD

**Issue by lanboeh5188** [coolsnowwolf/lede#6452]
编译了个x86版本 
端口转发生效不了 请教下大家有什么解决办法么

**Comment by NagaseKouichi** [comment]
编译了docker？

**Comment by lanboeh5188** [comment]
> 编译了docker？
 是的 和这个有关么

**Comment by NagaseKouichi** [comment]
参考这个：https://github.com/coolsnowwolf/lede/issues/6149

**Comment by luckins** [comment]
为什么我没编译docker还是没有效果

**Comment by lanboeh5188** [comment]
今天又编译了一个 搞定了 我想要的都实现了

________________________________
发件人: Felix_Weng ***@***.***>
发送时间: 2021年3月21日 17:56
收件人: coolsnowwolf/lede ***@***.***>
抄送: lanboeh5188 ***@***.***>; Author ***@***.***>
主题: Re: [coolsnowwolf/lede] 端口转发没效果 (#6452)


为什么我没编译docker还是没有效果

―
