### ISSUE TITLE
请求增加sacd-mpd加ompd或mympd

### ISSUE THREAD

**Issue by coolsuse** [coolsnowwolf/lede#6458]
大雕好
音乐爱好者请求增加sacd-mpd，ompd或mympd，非常感谢。
sacd-mpd库见：https://sourceforge.net/projects/mpd.sacddecoder.p/
mympd库见：https://github.com/jcorporation/mympd

minidlna对sacd的支持 很有用 谢了。

**Comment by Neverends4** [comment]
entware有mpd-full，如果支持你的路由架构，你可以试着手动装entware到路由器，当然init.d脚本启动不起来，可以手动做启动脚本。
