### ISSUE TITLE
5.4 .101的ipv6重启后有，过一会就没有了，5.4 .100正常。

### ISSUE THREAD

**Issue by eycooa** [coolsnowwolf/lede#6468]
[在pve上运行的X64固件，出现这种情况，

**Comment by eycooa** [comment]
是否能按照 kernel: bump 5.4 to 5.4.101 (#6445) 对应修改回去能编译5.4.100？

**Comment by WYC-2020** [comment]
101反正我用起来 也有问题，有时候居然连动态ip都获取不到，重启都不行，然后重新刷了可以，但是不久 又会自动重启，果断回到100，这种小版本号感觉太可怕了，不打算升内核了

**Comment by eycooa** [comment]
也许，我是不正确的，用云编译ipv6是正常的，可能是我自己把rclone和多线负载编译是有问题的。自己电脑rm -rf tmp .config 再make clean再重新编译都会出现ipv6不正常。

**Comment by buildiffuse** [comment]
我也遇到这种情况

> 也许，我是不正确的，用云编译ipv6是正常的，可能是我自己把rclone和多线负载编译是有问题的。自己电脑rm -rf tmp .config 再make clean再重新编译都会出现ipv6不正常。

我也遇到这种情况，，，还以为是自己网络问题，不懂退回低版本内核编译，只能等更新了
