### ISSUE TITLE
ssr plus 订阅功能是正常的吗，使用订阅功能无反应

### ISSUE THREAD

**Issue by nimasi** [coolsnowwolf/lede#648]
不管是否经过代理更新订阅，点击订阅后都得不到返回的服务器节点，试了几个订阅地址都不行。而且ssr plus的日志是无显示的，是否是我编译的有问题。

关于带订阅功能的ssr软件包，github上的以前试过几个，都是无法使用的，代码都不完善，请问这个ssr plus的订阅功能是否测试过可以正常使用？

**Comment by coolsnowwolf** [comment]
没有日志
