### ISSUE TITLE
R2S依然挑卡，路由界面点重启，路由就假死，我看今天修复了，但是貌似还是跟以前一样，不重启

### ISSUE THREAD

**Issue by 279437541** [coolsnowwolf/lede#6487]
R2S依然挑卡，路由界面点重启，路由就假死，我看今天修复了，但是貌似还是跟以前一样，不重启
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by icefruit-j** [comment]
说是修复UHS卡而已

**Comment by y9858** [comment]
我用以前插在诺基亚手机上的闪迪2g tf卡 挺稳定的

**Comment by vincent0214** [comment]
我买了京东的banq 16GB TF（MicroSD）运行了好几个月没出什么问题
