### ISSUE TITLE
V2ray 服务器没法启动。。。

### ISSUE THREAD

**Issue by flyhong666** [coolsnowwolf/lede#6502]
V2ray 服务器没法启动。。。各位，你们的情况呢？
![2021-03-09_193850](https://user-images.githubusercontent.com/76857714/110465496-6c83c680-810f-11eb-83c0-3d73fa98ad7f.png)
![2021-03-09_193910](https://user-images.githubusercontent.com/76857714/110465507-70afe400-810f-11eb-855d-1db560f378ff.png)

**Comment by flyhong666** [comment]
model/cbi/v2ray_server/api/app.lua  这个文件的权限不够，导致没法执行。我在源码将其修改了0755了，但是编译后，op 里面还是0644 ，这个要怎样整啊。那位大佬修一下呗。。。

**Comment by RodmanWang** [comment]
我编译最新版，连版本号都不显示，导致无法启动
