### ISSUE TITLE
网络-DHCP/DNS-DNS 转发 填入DNS后无法保存

### ISSUE THREAD

**Issue by BigDog66** [coolsnowwolf/lede#6516]
利用doker建立了一个AdGuardhome DNS服务器
想把路由DNS指向AdGuard服务器  
在网络-DHCP/DNS-DNS 转发 里面填入AdGuard的IP地址  点击保存后一闪而过 不会保存
利用SSH工具修改了/etc/config/dhcp文件  添加了一行 list server '192.168.1.253'  回到luci刷新了下是有数据了 但不起作用
最后是修改了wan口那里的DNS才起作用。 不知具有没有人碰到和我一样的问题？
编译时安装的插件非常少
![image](https://user-images.githubusercontent.com/69404815/110788551-bc969080-82a9-11eb-80d7-3d8b5f952a03.png)

**Comment by whave** [comment]
遇到同样问题，后研究修改/etc/dnsmasq.conf 添加server=ip#端口号,解决问题

**Comment by grz161** [comment]
是的,我也遇上这个问题,不能保存更改过的地址.
