### ISSUE TITLE
r2s怎么安装homeassistant

### ISSUE THREAD

**Issue by zhzh8015** [coolsnowwolf/lede#6519]
docker ce已运行，成功安装了portainer

有没有人成功安装运行homeassistant呢？

求教程

**Comment by skefy** [comment]
docker pull homeassistant/home-assistant:stable

docker run -d --name="home-assistant" -e "TZ=Asia/Shanghai" -v /root/config/homeassistant:/config --net=host homeassistant/home-assistant:stable
