### ISSUE TITLE
节点更新后只显示部分节点

### ISSUE THREAD

**Issue by xianshanlai** [coolsnowwolf/lede#6524]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：更新节点后，日志显示服务器有30个，但是页面上只显示3个节点

### (2) 路由器型号和固件版本

A：软路由J1900，固件版本：OpenWrt R9.5.1 By Lean / LuCI Master (git-19.121.62139-9ee402e) 

### (3) 详细日志
![微信图片_20210313114403](https://user-images.githubusercontent.com/616578/111017989-70566800-83f1-11eb-8c46-1f9a5fa404aa.png)
![微信图片_20210313114456](https://user-images.githubusercontent.com/616578/111018014-911ebd80-83f1-11eb-8574-34d708e2dd23.png)

A：

**Comment by xianshanlai** [comment]
没人遇到过同样的问题吗😓

**Comment by hn315** [comment]
你的固件版本太旧了吧

**Comment by hcym** [comment]
近期的都正常吧，我是用的上个月的，昨天晚上编译了还没刷
