### ISSUE TITLE
请教各位大佬，frpc中新增的<用户名>这个是干嘛用的？

### ISSUE THREAD

**Issue by weweyes** [coolsnowwolf/lede#6525]
![frpc](https://user-images.githubusercontent.com/59646715/111019782-45bddc80-83fc-11eb-8cf9-d2f67b89db3c.jpg)

**Comment by minlang112** [comment]
大概是frpc_full.ini里的这个字段

# your proxy name will be changed to {user}.{proxy}
user = your_name

**Comment by weweyes** [comment]
> 大概是frpc_full.ini里的这个字段
> 
> # your proxy name will be changed to {user}.{proxy}
> user = your_name

可以任意填写吗？

**Comment by mjyhj** [comment]
例如填了一个用户名，weweyes 
2个设备 K2P和N1
那服务端那边会显示 weweyes.K2P  weweyes.N1

这样可以大概率多人使用的时候，名字确保唯一性
