### ISSUE TITLE
 RTL 2.5Gbps USB netcard 仍然异常

### ISSUE THREAD

**Issue by yi-ge** [coolsnowwolf/lede#6527]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：根据[https://github.com/coolsnowwolf/lede/commit/767dd1dc717e1bac61780917eb85bd9198d03941]，尝试加载了kmod-usb-net-rtl8152-vendor，但是绿联RTL8156 2.5G网卡仍然无法正常驱动。检测不到网卡。

### (2) 路由器型号和固件版本

A：master版本

### (3) 详细日志

A：lsmod |grep 81
root@OpenWrt:/lib/modules/5.4.101# lsmod |grep 8125
r8125                 147456  0

Sat Mar 13 22:34:19 2021 kern.info kernel: [ 1378.641411] usb 4-1: USB disconnect, device number 2
Sat Mar 13 22:34:20 2021 kern.info kernel: [ 1379.405403] usb 4-1: new SuperSpeed Gen 1 USB device number 4 using xhci_hcd
Sat Mar 13 22:34:22 2021 kern.info kernel: [ 1380.893320] usb 4-3: USB disconnect, device number 3
Sat Mar 13 22:34:23 2021 kern.info kernel: [ 1382.689272] usb 4-3: new SuperSpeed Gen 1 USB device number 5 using xhci_hcd

**Comment by yi-ge** [comment]
确认r8125.ko已经载入。

**Comment by yi-ge** [comment]
Bus 004 Device 004: ID 0bda:8156 Realtek USB 10/100/1G/2.5G LAN
Bus 004 Device 005: ID 0bda:8156 Realtek USB 10/100/1G/2.5G LAN

**Comment by 1715173329** [comment]
see #6523

**Comment by yi-ge** [comment]
@1715173329 我没看到。原来如此，谢谢！
