### ISSUE TITLE
R8.1.7 客户端实时流量监测 (暂不兼容SFE和FLOW加速)页面没有显示，一直loading

### ISSUE THREAD

**Issue by daidaiwood** [coolsnowwolf/lede#656]
主机型号 | Netgear Nighthawk X4S R7800
固件版本 | OpenWrt R8.1.7 By Lean / LuCI openwrt-18.06 branch (git-18.138.53009-80cb4fe)
内核版本 | 4.9.132

编译使用的commit：
977f650

点击客户端实时流量界面，界面一直loading
微软edge报的错
![image](https://user-images.githubusercontent.com/43629170/46843232-608f5f80-ce04-11e8-8cde-728d681d9508.png)
谷歌浏览器报的错
![image](https://user-images.githubusercontent.com/43629170/46843259-87e62c80-ce04-11e8-81b0-7b3f5a7ce957.png)

**Comment by coolsnowwolf** [comment]
没有日志
