### ISSUE TITLE
如何在lean的源码中添加新的设备信息

### ISSUE THREAD

**Issue by higeon** [coolsnowwolf/lede#6569]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如何从其他源码中添加新的设备信息到lean的源码中

### (2) 路由器型号和固件版本

A：buffalo wsr-2533dhp2

### (3) 详细日志

A：我的这个路由器wsr-2533dhp2在musashino的源码（ https://github.com/musashino-build/openwrt ）中是被支持的，但在lean的源码中没有。如何才能从musashino的源码中拷贝相关的信息过来，让lean的源码也能支持这台设备？

**Comment by kzw200015** [comment]
为何不把lean的软件包放到你设备的源码里呢
