### ISSUE TITLE
OPENWRT R8.1.7,EA8500的VLAN

### ISSUE THREAD

**Issue by jackyan999** [coolsnowwolf/lede#658]
我的EA8500自R8.1固件后， 如果刷完固件复位就会丢失"启用VLAN"的选项，且这时候WAN显示的状态是不活动的。如果刷完固件不复位WAN和VLAN正常，但使用二，三天后就会莫明发生上述的情况而无法使用了，我试了几种方法，包括删除WAN和VLAN后再重建，情况依然是无法启用。不知道是什么原因造成的，请提供帮助，谢谢！

复位前

<img width="1050" alt="1" src="https://user-images.githubusercontent.com/31766266/46847173-98eb6980-ce15-11e8-839a-750feddc1120.png">

复位后

<img width="1069" alt="2" src="https://user-images.githubusercontent.com/31766266/46847198-aef92a00-ce15-11e8-8237-28744a78e7a0.png">

**Comment by coolsnowwolf** [comment]
没有日志
