### ISSUE TITLE
ac2100 luci接口物理设置看不到无线设备

### ISSUE THREAD

**Issue by liuquan321** [coolsnowwolf/lede#6582]
20号的源码中luci与后端状态似乎不同步。 luci 接口 物理设置里不显示无线设备，但是手动修改network文件将无线设备（ra0，rai1等）分配到其他接口是生效的。

**Comment by EnnawYang** [comment]
请手动到接口中增加无线设备，或者接口设置过后手动重启无线（针对闭源驱动

**Comment by liuquan321** [comment]
> 请手动到接口中增加无线设备，或者手动重启无线（针对闭源驱动

了解，可以理解为这是闭源驱动的一些副作用吗？
