### ISSUE TITLE
京东签到error

### ISSUE THREAD

**Issue by ecco2005** [coolsnowwolf/lede#6584]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：今天刚编译的固件，签到插件也升级到了1.98。手机APP扫码以后，点“手动执行签到”，然后所有签到都提示以下错误。

### (2) 路由器型号和固件版本

A：OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)
--

### (3) 详细日志

A：2021-03-22 22:28:13 Monday

‼️京东商城-京豆发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

**Comment by sxx1314** [comment]
写的很清楚，cookie无效。
