### ISSUE TITLE
AC58U 刷了8.1.7 下载崩溃

### ISSUE THREAD

**Issue by zhanglinku** [coolsnowwolf/lede#659]
![default](https://user-images.githubusercontent.com/44079998/46848490-bff96980-ce1c-11e8-9bbb-2b62a90a9b61.jpg)
刷8.1.6 断电密码不正确，  新版问题已解决。
通过OPBOOT刷factory.trx 依旧崩溃。无法在factory 固件里刷sysupgrade.bin

只能继续在opboot里刷sysupgrade.bin。 并无断电之后密码不正确问题。
其他均正常使用。   只有在迅雷满速下载的时候，路由延迟暴增。随即丢包。 
路由也无法进入。出现如图所示错误。

**Comment by coolsnowwolf** [comment]
内存爆炸了

**Comment by zhanglinku** [comment]
我直接不把这个插件编译进固件。 问题还是依旧
