### ISSUE TITLE
NPS 服务器地址请支持填写域名

### ISSUE THREAD

**Issue by Gipors** [coolsnowwolf/lede#6596]
NPS 内网穿透服务的设置界面【cgi-bin/luci/admin/services/nps】，填写服务器地址时要求 必须是 IPv4 地址，这并不合理，因为很多时候我们用到的只是动态公网 IP。
NPS 现在已经支持域名模式的服务器地址，请修改此处限制，以支持服务器地址填写为【域名】。

另，代码中已有 fprs 和 frpc，已有 NPC 客户端，可否再添加上 NPS 服务器端？多个局域网客户端连接时，NPS 的设置要方便很多。

**Comment by PandaEgg** [comment]
赞同，没有域名很不方便

**Comment by ntlf9t** [comment]
`server=s:taboption("basic",Value,"server_addr",translate("Server"),translate("Must` an IPv4 address"))
--server.datatype="ipaddr"
server.optional=false
server.rmempty=false`

**Comment by hzchzb** [comment]
确实是，我也一直在找支持域名的NPS

**Comment by shenyz** [comment]
先设置成ip可以连通，然后修改、etc/config/nps的配置文件，把server的地址改成域名，重启路由。不用管luci界面server地址是红色的，经测试服务器ip变更过一会是可以正常连接的，暂时的办法
