### ISSUE TITLE
网络-接口状态信息 数据包显示负数

### ISSUE THREAD

**Issue by ostrichii** [coolsnowwolf/lede#6599]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
网络-接口状态信息 数据包显示负数
![image](https://user-images.githubusercontent.com/11986597/112427468-9c200900-8d74-11eb-96fa-4a3646ef4995.png)

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
LAN和WAN接口的数据包显示 为负数
![image](https://user-images.githubusercontent.com/11986597/112427494-a6da9e00-8d74-11eb-9a43-e8f9be609202.png)

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
路由型号：x86 3865u 
固件版本：Powered by LuCI Master (git-21.035.34289-13f96d1) / OpenWrt R21.2.1
A：

### (3) 详细日志

A：

**Comment by Cathgao** [comment]
应该是数据类型溢出

**Comment by coolsnowwolf** [comment]
感谢报告 bug，这个是 jsonc 的 INT64 超过上限了，换用双精度显示就好了。

已修复

![image](https://user-images.githubusercontent.com/31687149/112727361-232fd580-8f5d-11eb-8796-ae7243833fb2.png)

**Comment by ostrichii** [comment]
> 感谢报告 bug，这个是 jsonc 的 INT64 超过上限了，换用双精度显示就好了。
> 
> 已修复
> 
> ![image](https://user-images.githubusercontent.com/31687149/112727361-232fd580-8f5d-11eb-8796-ae7243833fb2.png)

多谢大雕，地球上最快的男人

**Comment by ostrichii** [comment]
这个问题貌似又被带上来了
