### ISSUE TITLE
make memu报错

### ISSUE THREAD

**Issue by SuperPau1** [coolsnowwolf/lede#6603]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
make memu报错
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：feeds.conf.default去掉最后一行的注释，然后make memu就报错了，请问怎么解决

![2](https://user-images.githubusercontent.com/76992050/112588191-ecad6a00-8e39-11eb-9abd-c0780c3a3604.png)
![3](https://user-images.githubusercontent.com/76992050/112588204-f20ab480-8e39-11eb-9167-8f8d1ce713c2.png)

### (2) 路由器型号和固件版本

A：x64

### (3) 详细日志

A：

**Comment by OleStore** [comment]
update& install
建议你看首页说明
https://github.com/coolsnowwolf/lede

**Comment by SuperPau1** [comment]
> update& install
> 建议你看首页说明
> https://github.com/coolsnowwolf/lede

首页没有任何信息，还是说你指的是更新feeds？编译无数次了不可能漏掉这一步的

**Comment by SuperPau1** [comment]
> update& install
> 建议你看首页说明
> https://github.com/coolsnowwolf/lede

为了避免误解，我更新一下，下载源代码后打开feeds.conf.default去掉helloword的注释，update和install feeds后make memu报错

**Comment by 1715173329** [comment]
什么叫报错？没日志让网友给你算命？
