### ISSUE TITLE
ddns 界面很奇怪

### ISSUE THREAD

**Issue by 00LT00** [coolsnowwolf/lede#6604]
## 1.关于你要提交的问题
ddns界面长这样是正常的吗？？？
![image](https://user-images.githubusercontent.com/47566260/112618621-470df100-8e61-11eb-870d-4f283cf15b93.png)

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
按我的理解怎么也要有个添加记录的地方，网上搜的也都是差不多的，唯独我的长这样，是正常的吗，以前没用过，真不知道应该长啥样
![image](https://user-images.githubusercontent.com/47566260/112618241-e4b4f080-8e60-11eb-8985-2ded0bbb7f13.png)

### (2) 路由器型号和固件版本
newifi3 d2 最新源码版本

**Comment by EnnawYang** [comment]
？哪不正常？ 这都能发issue？

**Comment by 00LT00** [comment]
@EnnawYang woc对不起我太蠢了，那个添加前面的框框我填了各种域名都不行，直接一个空白界面，唯独没试过直接填个名字，对不起对不起对不起😭
