### ISSUE TITLE
dnsmasq不定期停止回应

### ISSUE THREAD

**Issue by kenpuluma** [coolsnowwolf/lede#6611]
## 1.关于你要提交的问题
是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
一个困扰了很久的问题，dnsmasq会随机停止回应子网内的dns请求。具体表现为子网内设备使用nslookup和指定dns地址皆提示Unknown Server, 路由器本机nslookup 127.0.0.1并无异常。日志已开启log-queries和log-dhcp，但无法找到任何停止回应期间子网设备的请求。

重启dnsmasq服务可以恢复正常。如果不管会在1-5分钟内自动恢复。

### (2) 路由器型号和固件版本
固件版本 | OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)
Dnsmasq version 2.84rc2

### (3) 详细日志
因无法找到问题源头，没有相关日志内容

**Comment by swxk521** [comment]
我这边是
手机隔夜过后，只能浏览国内网站，但是路由检测没问题，手机无线网重新连一下，科学上网就正常了
