### ISSUE TITLE
https-dns-proxy编译报错

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#6618]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

https-dns-proxy编译报错

### (2) 路由器型号和固件版本

X86 64

### (3) 详细日志
touch /workdir/openwrt/staging_dir/target-x86_64_musl/root-x86/stamp/.libev_installed
echo "libev" >> /workdir/openwrt/staging_dir/target-x86_64_musl/pkginfo/libev.default.install
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/libs/libev'
time: package/feeds/packages/libev/compile#0.15#0.04#0.19
make[3]: Entering directory '/workdir/openwrt/feeds/packages/net/https-dns-proxy'
Makefile:17: ../../devel/ninja/ninja-cmake.mk: No such file or directory
make[3]: *** No rule to make target '../../devel/ninja/ninja-cmake.mk'.  Stop.
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/https-dns-proxy'
time: package/feeds/packages/https-dns-proxy/compile#0.12#0.04#0.15
package/Makefile:111: recipe for target 'package/feeds/packages/https-dns-proxy/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/feeds/packages/https-dns-proxy/compile] Error 2
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
make: *** [world] Error 2
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
Error: Process completed with exit code 2.

经排查，加入passwall报错，删除passwall后正常编译。各位大佬可否遇到？怎么解决的？

**Comment by db-one** [comment]
Makefile:17: ../../devel/ninja/ninja-cmake.mk: No such file or directory
make[3]: *** No rule to make target '../../devel/ninja/ninja-cmake.mk'. Stop.



缺少  ../../devel/ninja/ninja-cmake.mk

你这编译的不是大雕的https-dns-proxy包   大雕里面没这个
![image](https://user-images.githubusercontent.com/20243226/112776252-bbb77a00-9071-11eb-9d97-635fe267ae39.png)
