### ISSUE TITLE
端口转发异常

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#6626]
esxi下安装OpenWrt R21.3.27 / LuCI 17.01内核版本 | 5.4.108

问题：内网无法打开公网IP+端口号访问局域网内的设备，但是路由IP地址的正常。

例如192.168.1.1主路由，100端口转发到192.168.1.1:100，101端口转发到192.168.1.2:101
内外网都正常访问100端口，101端口内网无法访问!

docker编译进去就会这样！目前无解了吗？
https://github.com/coolsnowwolf/lede/issues/6149

**Comment by DYSDF** [comment]
检查下`dhcp`中`重绑定保护`和`允许本机`是否都勾选了

**Comment by lexin8** [comment]
> 检查下`dhcp`中`重绑定保护`和`允许本机`是否都勾选了

实测，默认状态是勾选的，取消勾选后还是同样问题，要取消docker的编译。以往的反馈问题都是这样解决，目前好像没有解决掉这个问题！

**Comment by NagaseKouichi** [comment]
我那个帖子不是已经给出解决方法了……

**Comment by lexin8** [comment]
> 我那个帖子不是已经给出解决方法了……

`运行 sysctl -p`之后自动重启就添加的3条代码就被删了。添加后手动重启就好了！原理是什么，会影响稳定性吗？

**Comment by superliurui** [comment]
socat做端口转发有效
