### ISSUE TITLE
闭源驱动如何使用8021X

### ISSUE THREAD

**Issue by wysizhh** [coolsnowwolf/lede#6631]
开源驱动可以安装WPAD和FreeRADIUS然后设置一下就行。闭源驱动不能用WPAD，按照开源驱动时设置FreeRADIUS后连接不成功。小白请教要怎么安装设置才能用

**Comment by Metric-Void** [comment]
安装luci-app-mtwifi，在它提供的无线界面里面配置闭源驱动

**Comment by wysizhh** [comment]
> 安装luci-app-mtwifi，在它提供的无线界面里面配置闭源驱动

除了下图设置还有其他设置吗?   之后证书要放什么地方?
![image](https://user-images.githubusercontent.com/62669501/113710446-4bb28f00-9716-11eb-9d59-38822fdbeb2d.png)

**Comment by Metric-Void** [comment]
> > 安装luci-app-mtwifi，在它提供的无线界面里面配置闭源驱动
> 
> 除了下图设置还有其他设置吗? 之后证书要放什么地方?
> ![image](https://user-images.githubusercontent.com/62669501/113710446-4bb28f00-9716-11eb-9d59-38822fdbeb2d.png)

有的，需要手动编辑配置文件，下面有个文本框那就是

以及，什么协议的证书？

**Comment by wysizhh** [comment]
> > > 安装luci-app-mtwifi，在它提供的无线界面里面配置闭源驱动
> > 
> > 
> > 除了下图设置还有其他设置吗? 之后证书要放什么地方?
> > ![image](https://user-images.githubusercontent.com/62669501/113710446-4bb28f00-9716-11eb-9d59-38822fdbeb2d.png)
> 
> 有的，需要手动编辑配置文件，下面有个文本框那就是
> 
> 以及，什么协议的证书？

例如我用PEAP认证,就要用到证书啊
