### ISSUE TITLE
云编译 ./scripts/feeds install -a 后很多WARNING  有没有问题呢

### ISSUE THREAD

**Issue by wysizhh** [coolsnowwolf/lede#6636]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：./scripts/feeds install -a 后很多WARNING

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libpng', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/antileech/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/automount/Makefile' has a dependency on 'antfs-mount', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/lean/baidupcs-web/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/dnsforwarder/Makefile' has a dependency on 'coreutils-base64', which does not exist
WARNING: Makefile 'package/lean/frp/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libgstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1-libs', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/lean/kcptun/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a dependency on 'luci-app-nlbwmon', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a dependency on 'zerotier', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-lib-docker/Makefile' has a dependency on 'luci-lib-json', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci-lib-nixio', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a dependency on 'proto-bonding', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-argon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-netgear/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'libpcre2-16', which does not exist
WARNING: Makefile 'package/lean/qt5/Makefile' has a dependency on 'icu', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-chrono', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-random', which does not exist
WARNING: Makefile 'package/lean/rclone/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libtirpc', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libtasn1', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'attr', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libaio', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libavahi-client', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'python3-cryptodome', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'libarchive', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'acl', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a dependency on 'attr', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'libtasn1/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'rpcsvc-proto/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'python3/host', which does not exist
WARNING: Makefile 'package/lean/samba4/Makefile' has a build dependency on 'perl/host', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a build dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/tcpping/Makefile' has a dependency on 'libnet-1.2.x', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-program_options', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-date_time', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusic/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusicGo/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/v2ray-plugin/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/wxbase/Makefile' has a dependency on 'libexpat', which does not exist

**Comment by AmadeusGhost** [comment]
没有，后面 install 了，忽略即可
