### ISSUE TITLE
Nanopi R4S开启SFE一段时间后死机，必须拔插电源重启，可稳定复现

### ISSUE THREAD

**Issue by KC896A** [coolsnowwolf/lede#6640]
以及可否考虑将R4S默认超频至2.2G/1.8G？

**Comment by Aes64X** [comment]
> 以及可否考虑将R4S默认超频至2.2G/1.8G？

默认超频完全没必要，到时又来一大堆什么过热的，加风扇的。如果你会超自己弄就行了。（普遍认为50度即为高温的认知，你是维护者你也不会这么干的。）

**Comment by minlang112** [comment]
嗯？会超自己超就好了，为什么要别人跟你一起超……
