### ISSUE TITLE
SSRPLUS+的访问控制加入中文域名会导致无法上网

### ISSUE THREAD

**Issue by laaArmy** [coolsnowwolf/lede#6643]
I5 8400  ESXI跑的Openwrt      

5.4.105内核的版本

上一个版本也是这样

在访问控制加入中文域名后断网，QQ都挂了

**Comment by liuzipeng** [comment]
自行转码

**Comment by fhbyljj** [comment]
> 自行转码

只是报告个BUG而已，顺道提醒下其他人，因为为了这个BUG我折腾了好两天

**Comment by sxx1314** [comment]
中文域名其实并不是中文，只不过浏览器给你显示成了中文。比较🐔贼的设计.

**Comment by minlang112** [comment]
这个其实不是BUG，中文域名本来其实就不是中文……
