### ISSUE TITLE
编译时大量依赖无法下载，地址显示为空

### ISSUE THREAD

**Issue by wjz2001** [coolsnowwolf/lede#6646]
我的编译环境是：windows下Ubuntu子系统、虚拟机debian10、美国服务器debian10，前两个都挂好了可用代理。
我计划编译psg1208的固件，并且采用默认选项没有额外添加任何插件。但是编译的时候会出现超级大量的错误，然后我发现这些错误的原因都是因为下不下来文件，然后我直接复制网址用浏览器打开结果网址还是空的。请问这是怎么回事？

**Comment by EnnawYang** [comment]
![Snipaste_2021-04-05_11-02-42](https://user-images.githubusercontent.com/6705663/113532634-75789280-95fe-11eb-9e3d-2c663980b331.png)
为什么不问问神奇的海螺呢

**Comment by Cathgao** [comment]
请贴上手相照片，好算
