### ISSUE TITLE
求助 Chelsio T422-CR 网卡驱动

### ISSUE THREAD

**Issue by MrVicent** [coolsnowwolf/lede#6647]
手头有一张 Chelsio T422-CR网卡 4口 2千兆 2万兆 很香的样子
然后发现 默认好像是没有驱动的
所以来求教大佬 如何添加这个网卡的驱动 
编译时要在Kernel modules -> Network Devices 里选择哪个驱动？ 还是需要手动添加之后在做什么操作？

目前使用pve虚拟机，所以能装上pve驱动 或者 直通给openwrt驱动都行
希望有大佬看到 给指条明路~

 在官方网站 https://service.chelsio.com/ 没找到直接的pve和openwrt驱动 只有esxi和redhat驱动 不知能否利用下 
![image](https://user-images.githubusercontent.com/50162258/113532573-42360380-95fe-11eb-997d-5968528b4d8e.png)
![image](https://user-images.githubusercontent.com/50162258/113532605-5aa61e00-95fe-11eb-811a-6378c4f933ac.png)

**Comment by Aes64X** [comment]
> 手头有一张 Chelsio T422-CR网卡 4口 2千兆 2万兆 很香的样子
> 然后发现 默认好像是没有驱动的
> 所以来求教大佬 如何添加这个网卡的驱动
> 编译时要在Kernel modules -> Network Devices 里选择哪个驱动？ 还是需要手动添加之后在做什么操作？
> 
> 目前使用pve虚拟机，所以能装上pve驱动 或者 直通给openwrt驱动都行
> 希望有大佬看到 给指条明路~
> 
> 在官方网站 https://service.chelsio.com/ 没找到直接的pve和openwrt驱动 只有esxi和redhat驱动 不知能否利用下
> ![image](https://user-images.githubusercontent.com/50162258/113532573-42360380-95fe-11eb-997d-5968528b4d8e.png)
> ![image](https://user-images.githubusercontent.com/50162258/113532605-5aa61e00-95fe-11eb-811a-6378c4f933ac.png)

早有定论，请善用搜索：https://github.com/coolsnowwolf/lede/issues/6453
