### ISSUE TITLE
新版迅雷快鸟插件无法保存和运行

### ISSUE THREAD

**Issue by wybb** [coolsnowwolf/lede#6653]
点击“保存&应用”按钮后web界面就处于无限等待状态

**Comment by Beginner-Go** [comment]
之前正常时是那个版本？

**Comment by Mousehk** [comment]
遇到同样问题 无法运行

**Comment by RodmanWang** [comment]
同样问题 无法运行,只要设置了，就一直显示更改中，都不能终止，只能重启

**Comment by Beginner-Go** [comment]
明天我看看能不能修复

**Comment by Mousehk** [comment]
> 之前正常时是那个版本？

上月使用1.0.4版本正常

**Comment by MGBB** [comment]
> 之前正常时是那个版本？

#6637 之前正常的

**Comment by MGBB** [comment]
> > 之前正常时是那个版本？
> 
> #6637 之前正常的

开启快鸟也会使其它的插件也无法保存

**Comment by aaa1230217** [comment]
> 点击“保存＆应用”按钮后web界面就处于无限等待状态

https://github.com/small-5/luci-app-xlnetacc 替换这个修改版，

**Comment by Beginner-Go** [comment]
[https://github.com/Beginner-Go/luci-app-xlnetacc-1] (试试这个版本)

**Comment by Mousehk** [comment]
> [试试这个版本](https://github.com/Beginner-Go/luci-app-xlnetacc-1)

这个版本还是不行一直正在应用更改 然后卡死了

**Comment by Beginner-Go** [comment]
好的 大概知道问题所在了

**Comment by Mousehk** [comment]
> 好的 大概知道问题所在了

大佬能不能把 输入验证码放上 有时不输验证码登录不上去

**Comment by Beginner-Go** [comment]
> > 点击“保存＆应用”按钮后web界面就处于无限等待状态
> 
> https://github.com/small-5/luci-app-xlnetacc 替换这个修改版，

这个版本也有问题 同样的情况
