### ISSUE TITLE
Error compile kmod-batman-adv

### ISSUE THREAD

**Issue by supperchym** [coolsnowwolf/lede#6655]
(1) 具体问题

Error: Process completed with exit code 2 when compile with kmod-batman-adv

(2) 路由器型号和固件版本

Buffalo ag300h
OpenWrt SNAPSHOT r3149-a976a3b7d / LuCI Master git-21.095.59656-3561927/ ath79 coolsnowwolf

(3) 核心日志

rm -f /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/.built
touch /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/.built_check
cat /dev/null > /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/symvers/batman-adv.symvers; for subdir in net/batman-adv; do cat /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/symvers/*.symvers 2>/dev/null > /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/$subdir/Module.symvers; done
make -j1 -C "/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.19.138" KCFLAGS="-ffile-prefix-map=/workdir/openwrt/build_dir/target-mips_24kc_musl=target-mips_24kc_musl" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-mips_24kc_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mips-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Tue Apr  6 02:55:51 2021" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/workdir/openwrt/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/workdir/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KERNELRELEASE=4.19.138 M="/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv" CONFIG_BATMAN_ADV=m CONFIG_BATMAN_ADV_DEBUG=n CONFIG_BATMAN_ADV_BLA=y CONFIG_BATMAN_ADV_DAT=y CONFIG_BATMAN_ADV_MCAST=y CONFIG_BATMAN_ADV_NC=n CONFIG_BATMAN_ADV_BATMAN_V=y CONFIG_BATMAN_ADV_TRACING=n  EXTRA_CFLAGS=" -DCONFIG_BATMAN_ADV=1  -DCONFIG_BATMAN_ADV_BLA=1  -DCONFIG_BATMAN_ADV_DAT=1  -DCONFIG_BATMAN_ADV_MCAST=1  -DCONFIG_BATMAN_ADV_BATMAN_V=1 " NOSTDINC_FLAGS="-I/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv -I/workdir/openwrt/staging_dir/target-mips_24kc_musl/usr/include/mac80211-backport -I/workdir/openwrt/staging_dir/target-mips_24kc_musl/usr/include/mac80211-backport/uapi -I/workdir/openwrt/staging_dir/target-mips_24kc_musl/usr/include/mac80211 -I/workdir/openwrt/staging_dir/target-mips_24kc_musl/usr/include/mac80211/uapi -I/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/include/ -include backport/autoconf.h -include backport/backport.h -include /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/compat-hacks.h -DBATADV_SOURCE_VERSION=\\\"2021.0-openwrt-1\\\"" modules
make[4]: Entering directory '/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.19.138'
  CC [M]  /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.o
/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c: In function 'batadv_mcast_is_report_ipv4':
/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c:964:6: error: too few arguments to function 'ip_mc_check_igmp'
  if (ip_mc_check_igmp(skb) < 0)
      ^~~~~~~~~~~~~~~~
In file included from /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c:20:
./include/linux/igmp.h:133:5: note: declared here
 int ip_mc_check_igmp(struct sk_buff *skb, struct sk_buff **skb_trimmed);
     ^~~~~~~~~~~~~~~~
/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c: In function 'batadv_mcast_is_report_ipv6':
/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c:1030:6: error: too few arguments to function 'ipv6_mc_check_mld'
  if (ipv6_mc_check_mld(skb) < 0)
      ^~~~~~~~~~~~~~~~~
In file included from /workdir/openwrt/staging_dir/target-mips_24kc_musl/usr/include/mac80211-backport/net/addrconf.h:4,
                 from /workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.c:43:
./include/net/addrconf.h:222:5: note: declared here
 int ipv6_mc_check_mld(struct sk_buff *skb, struct sk_buff **skb_trimmed);
     ^~~~~~~~~~~~~~~~~
make[5]: *** [/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.o] Error 1
scripts/Makefile.build:303: recipe for target '/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv/multicast.o' failed
make[4]: *** [_module_/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv] Error 2
Makefile:1528: recipe for target '_module_/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/net/batman-adv' failed
make[3]: *** [/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/.built] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/linux-4.19.138'
Makefile:89: recipe for target '/workdir/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/batman-adv-2021.0/.built' failed
make[3]: Leaving directory '/workdir/openwrt/feeds/routing/batman-adv'
make[2]: *** [package/feeds/routing/batman-adv/compile] Error 2
time: package/feeds/routing/batman-adv/compile#1.16#0.36#1.42
package/Makefile:111: recipe for target 'package/feeds/routing/batman-adv/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/workdir/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
Error: Process completed with exit code 2.

**Comment by AmadeusGhost** [comment]
试试把 https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default#L3 改成 `src-git routing https://git.openwrt.org/feed/routing.git;openwrt-19.07`，或者选择 5.4 内核编译吧
