### ISSUE TITLE
openvpn 连上又马上断开，一直重复

### ISSUE THREAD

**Issue by keeno1982** [coolsnowwolf/lede#6656]
用的是最新的代码编译的，设备是N1，电信外网开放1194端口

openvpn用的模式是tcp server ipv4，其它都是按默认值没有改动。

客户端连接时，可以看到Log是连接上了，但是马上又断开，但是改成udp server ipv4，则可以连上，但是用起来很卡

各位有经验解决的，麻烦传授一下

⏎4/14/2021, 9:49:10 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:10 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:10 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:10 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:10 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:11 AM SSL Handshake: CN=server, TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
⏎4/14/2021, 9:49:11 AM Session is ACTIVE
⏎4/14/2021, 9:49:11 AM Sending PUSH_REQUEST to server...
⏎4/14/2021, 9:49:11 AM EVENT: GET_CONFIG ⏎4/14/2021, 9:49:11 AM EVENT: ASSIGN_IP ⏎4/14/2021, 9:49:11 AM OPTIONS:
0 [route] [192.168.196.0] [255.255.255.0] 
1 [comp-lzo] [adaptive] 
2 [redirect-gateway] [def1] [bypass-dhcp] 
3 [dhcp-option] [DNS] [192.168.196.1] 
4 [route-gateway] [10.8.0.1] 
5 [topology] [subnet] 
6 [ping] [10] 
7 [ping-restart] [120] 
8 [ifconfig] [10.8.0.2] [255.255.255.0] 
9 [peer-id] [0] 
10 [cipher] [AES-256-GCM] 

⏎4/14/2021, 9:49:11 AM PROTOCOL OPTIONS:
  cipher: AES-256-GCM
  digest: NONE
  compress: LZO
  peer ID: 0
⏎4/14/2021, 9:49:11 AM CAPTURED OPTIONS:
Session Name: testman.ga
Layer: OSI_LAYER_3
Remote Address: 117.28.111.192
Tunnel Addresses:
  10.8.0.2/24 -> 10.8.0.1
Reroute Gateway: IPv4=1 IPv6=0 flags=[ ENABLE REROUTE_GW DEF1 BYPASS_DHCP IPv4 ]
Block IPv6: no
Add Routes:
  192.168.196.0/24
Exclude Routes:
DNS Servers:
  192.168.196.1
Search Domains:

⏎4/14/2021, 9:49:15 AM SetupClient: transmitting tun setup list to \\.\pipe\agent_ovpnconnect
{
	"confirm_event" : "6c0e000000000000",
	"destroy_event" : "580e000000000000",
	"tun" : 
	{
		"adapter_domain_suffix" : "",
		"add_routes" : 
		[
			{
				"address" : "192.168.196.0",
				"gateway" : "",
				"ipv6" : false,
				"metric" : -1,
				"net30" : false,
				"prefix_length" : 24
			}
		],
		"block_ipv6" : false,
		"dns_servers" : 
		[
			{
				"address" : "192.168.196.1",
				"ipv6" : false
			}
		],
		"layer" : 3,
		"mtu" : 0,
		"remote_address" : 
		{
			"address" : "117.28.111.192",
			"ipv6" : false
		},
		"reroute_gw" : 
		{
			"flags" : 307,
			"ipv4" : true,
			"ipv6" : false
		},
		"route_metric_default" : -1,
		"session_name" : "testman.ga",
		"tunnel_address_index_ipv4" : 0,
		"tunnel_address_index_ipv6" : -1,
		"tunnel_addresses" : 
		[
			{
				"address" : "10.8.0.2",
				"gateway" : "10.8.0.1",
				"ipv6" : false,
				"metric" : -1,
				"net30" : false,
				"prefix_length" : 24
			}
		]
	},
	"wintun" : false
}
POST np://[\\.\pipe\agent_ovpnconnect]/tun-setup : 200 OK
TAP ADAPTERS:
guid='{1136B6D6-DEE3-451F-A4C1-80C910614645}' index=28 name='Local Area Connection 3'
Open TAP device "Local Area Connection 3" PATH="\\.\Global\{1136B6D6-DEE3-451F-A4C1-80C910614645}.tap" SUCCEEDED
TAP-Windows Driver Version 9.24
ActionDeleteAllRoutesOnInterface iface_index=28
netsh interface ip set interface 28 metric=1
Ok.
netsh interface ip set address 28 static 10.8.0.2 255.255.255.0 gateway=10.8.0.1 store=active
IPHelper: add route 192.168.196.0/24 28 10.8.0.1 metric=-1
netsh interface ip add route 117.28.111.192/32 13 172.16.82.1 store=active
The object already exists.
netsh interface ip add route 0.0.0.0/1 28 10.8.0.1 store=active
Ok.
netsh interface ip add route 128.0.0.0/1 28 10.8.0.1 store=active
Ok.
netsh interface ip set dnsservers 28 static 192.168.196.1 register=primary validate=no
ipconfig /flushdns
Windows IP Configuration
Successfully flushed the DNS Resolver Cache.
TAP handle: c407000000000000
⏎4/14/2021, 9:49:15 AM Connected via TUN_WIN
⏎4/14/2021, 9:49:15 AM LZO-ASYM init swap=0 asym=0
⏎4/14/2021, 9:49:15 AM EVENT: CONNECTED testman.ga:1194 (117.28.111.192) via /TCPv4 on TUN_WIN/10.8.0.2/ gw=[10.8.0.1/]⏎4/14/2021, 9:49:15 AM EVENT: COMPRESSION_ENABLED Compression enabled.  This may be a potential security issue.⏎4/14/2021, 9:49:16 AM Session invalidated: DECRYPT_ERROR
⏎4/14/2021, 9:49:16 AM Client terminated, restarting in 2000 ms...
⏎4/14/2021, 9:49:16 AM SetupClient: signaling tun destroy event
⏎4/14/2021, 9:49:18 AM EVENT: RECONNECTING ⏎4/14/2021, 9:49:18 AM EVENT: RESOLVE ⏎4/14/2021, 9:49:20 AM EVENT: WAIT ⏎4/14/2021, 9:49:20 AM WinCommandAgent: transmitting bypass route to 117.28.111.192
{
	"host" : "117.28.111.192",
	"ipv6" : false
}

⏎4/14/2021, 9:49:21 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:21 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:21 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:21 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:21 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:21 AM Client exception in transport_recv_excode: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
⏎4/14/2021, 9:49:21 AM Client terminated, restarting in 2000 ms...
⏎4/14/2021, 9:49:24 AM EVENT: RECONNECTING ⏎4/14/2021, 9:49:24 AM EVENT: RESOLVE ⏎4/14/2021, 9:49:24 AM EVENT: WAIT ⏎4/14/2021, 9:49:24 AM WinCommandAgent: transmitting bypass route to 117.28.111.192
{
	"host" : "117.28.111.192",
	"ipv6" : false
}

⏎4/14/2021, 9:49:24 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:24 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:24 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:24 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:24 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:25 AM Client exception in transport_recv_excode: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
⏎4/14/2021, 9:49:25 AM Client terminated, restarting in 2000 ms...
⏎4/14/2021, 9:49:27 AM EVENT: RECONNECTING ⏎4/14/2021, 9:49:27 AM EVENT: RESOLVE ⏎4/14/2021, 9:49:27 AM WinCommandAgent: transmitting bypass route to 117.28.111.192
{
	"host" : "117.28.111.192",
	"ipv6" : false
}

⏎4/14/2021, 9:49:27 AM EVENT: WAIT ⏎4/14/2021, 9:49:27 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:27 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:27 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:27 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:27 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:27 AM Client exception in transport_recv_excode: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
⏎4/14/2021, 9:49:27 AM Client terminated, restarting in 2000 ms...
⏎4/14/2021, 9:49:29 AM EVENT: RECONNECTING ⏎4/14/2021, 9:49:29 AM EVENT: RESOLVE ⏎4/14/2021, 9:49:29 AM WinCommandAgent: transmitting bypass route to 117.28.111.192
{
	"host" : "117.28.111.192",
	"ipv6" : false
}

⏎4/14/2021, 9:49:29 AM EVENT: WAIT ⏎4/14/2021, 9:49:30 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:30 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:30 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:30 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:30 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:30 AM Client exception in transport_recv_excode: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
⏎4/14/2021, 9:49:30 AM Client terminated, restarting in 2000 ms...
⏎4/14/2021, 9:49:32 AM EVENT: RECONNECTING ⏎4/14/2021, 9:49:32 AM EVENT: RESOLVE ⏎4/14/2021, 9:49:32 AM EVENT: WAIT ⏎4/14/2021, 9:49:32 AM WinCommandAgent: transmitting bypass route to 117.28.111.192
{
	"host" : "117.28.111.192",
	"ipv6" : false
}

⏎4/14/2021, 9:49:33 AM Connecting to [testman.ga]:1194 (117.28.111.192) via TCPv4
⏎4/14/2021, 9:49:33 AM EVENT: CONNECTING ⏎4/14/2021, 9:49:33 AM Tunnel Options:V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client
⏎4/14/2021, 9:49:33 AM Creds: UsernameEmpty/PasswordEmpty
⏎4/14/2021, 9:49:33 AM Peer Info:
IV_VER=3.git::662eae9a
IV_PLAT=win
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_LZO=1
IV_AUTO_SESS=1
IV_GUI_VER=OCWindows_3.2.2-1455
IV_SSO=openurl
IV_BS64DL=1

⏎4/14/2021, 9:49:33 AM Client exception in transport_recv_excode: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
⏎4/14/2021, 9:49:33 AM Client terminated, restarting in 2000 ms...
⏎

**Comment by galaxyskyknight** [comment]
把Log传出来

**Comment by keeno1982** [comment]
@galaxyskyknight 已经贴上了，帮忙看一下哈
