### ISSUE TITLE
编译时luci-app-nlbwmon无法禁用

### ISSUE THREAD

**Issue by caoli5288** [coolsnowwolf/lede#6659]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：luci-app-nlbwmon无法禁用

### (2) 路由器型号和固件版本

A：master

### (3) 详细日志

A：

**Comment by Cathgao** [comment]
算命？

**Comment by zwillhill** [comment]
你选装了wrtbmon。因为nlbwmon偶尔占用高，我也换过wrtbmon，但是wrtbmon依赖nlbwmon，干脆都不装了。
