### ISSUE TITLE
可否加入socat转发插件

### ISSUE THREAD

**Issue by rhww** [coolsnowwolf/lede#6664]
现在ipv6越来越多了，用socat将ipv6转发到内网ipv4非常方便，不需要对每个客户端的ipv6进行解析，只解析路由器的地址，然后用真个插件转发到内外地址

**Comment by NagaseKouichi** [comment]
软件源里面不是有吗。直接装就可以啊

**Comment by rhww** [comment]
> 软件源里面不是有吗。直接装就可以啊

主要是想一次编译，免得再手动安装

**Comment by NagaseKouichi** [comment]
> > 软件源里面不是有吗。直接装就可以啊
> 
> 主要是想一次编译，免得再手动安装

那在编译的时候直接选上不就可以了

**Comment by NagaseKouichi** [comment]
![image](https://user-images.githubusercontent.com/53267025/114208878-917a8c00-9990-11eb-9239-185e715ec5d4.png)

**Comment by rhww** [comment]
感谢，一直没注意还有个选项，我试试，感谢大佬
