### ISSUE TITLE
手上有只MSG1500，想刷op但不知道可以套用target profile?

### ISSUE THREAD

**Issue by pop2006** [coolsnowwolf/lede#6669]
这个路由器能刷老毛子，但个人比较喜欢op，特来请教一下各位大神。
硬件如下：
瑞斯康达MSG1500  MT7621A+MT7615D+DDR3-256M+128M-NAND-FLASH
诺基亚贝尔A-040W-Q   MT7621A+MT7615D+DDR3-256M+128M-NAND-FLASH
ikuai爱快IK-Q80   MT7621A+MT7615D+DDR3-256M+128M-NAND-FLASH

**Comment by AmadeusGhost** [comment]
需要适配的，其它设备的代码不一定适用。
