### ISSUE TITLE
更新至最新版，防火墙失效

### ISSUE THREAD

**Issue by lesliedu** [coolsnowwolf/lede#6673]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

更新到最新版固件，选择了docker模块，在内网使用ddns地址，无法连接除了路由器以外的web服务器，确认ddns已成功

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by xiaojing110** [comment]
带docker的内网无法ddns   之前就有提起过

**Comment by NagaseKouichi** [comment]
这里有解决方法：https://github.com/coolsnowwolf/lede/issues/6149#issuecomment-753815061
