### ISSUE TITLE
OrangePi R1 plus 启动失败

### ISSUE THREAD

**Issue by garlicsoft** [coolsnowwolf/lede#6675]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译成功，写入sd卡无法启动

### (2) 路由器型号和固件版本

A：OrangePi R1 plus

### (3) 详细日志

A：
 entries: 512 (order: 2, 16384 bytes, linear)
[    0.102688] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.103587] NET: Registered protocol family 1
[    0.104022] PCI: CLS 0 bytes, default 64
[    0.105997] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.115661] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.116200] jffs2: version 2.2 (NAND) (SUMMARY) (ZLIB) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.144727] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.145436] io scheduler mq-deadline registered
[    0.152164] dma-pl330 ff1f0000.dmac: Loaded driver for PL330 DMAC-241330
[    0.152790] dma-pl330 ff1f0000.dmac: .DBUFF-128x8bytes Num_Chans-8 Num_Peri-20 Num_Events-16
[    0.156003] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    0.158534] ff120000.serial: ttyS1 at MMIO 0xff120000 (irq = 12, base_baud = 1500000) is a 16550A
[    0.160203] ff130000.serial: ttyS2 at MMIO 0xff130000 (irq = 13, base_baud = 1500000) is a 16550A
[    0.161160] printk: console [ttyS2] enabled
[    0.161160] printk: console [ttyS2] enabled
[    0.161912] printk: bootconsole [uart8250] disabled
[    0.161912] printk: bootconsole [uart8250] disabled
[    0.164687] rockchip-drm display-subsystem: [drm:rockchip_drm_platform_probe] *ERROR* No available vop found for display-subsystem.
[    0.166315] lima ff300000.gpu: IRQ pmu not found
[    0.166933] lima ff300000.gpu: IRQ ppmmu2 not found
[    0.167373] lima ff300000.gpu: IRQ ppmmu3 not found
[    0.167810] lima ff300000.gpu: IRQ ppmmu4 not found
[    0.168248] lima ff300000.gpu: IRQ ppmmu5 not found
[    0.168683] lima ff300000.gpu: IRQ ppmmu6 not found
[    0.169161] lima ff300000.gpu: IRQ ppmmu7 not found
[    0.169616] lima ff300000.gpu: gp - mali450 version major 0 minor 0
[    0.170223] lima ff300000.gpu: pp0 - mali450 version major 0 minor 0
[    0.170840] lima ff300000.gpu: pp1 - mali450 version major 0 minor 0
[    0.171438] lima ff300000.gpu: IRQ pp2 not found
[    0.171854] lima ff300000.gpu: IRQ pp3 not found
[    0.172269] lima ff300000.gpu: IRQ pp4 not found
[    0.172682] lima ff300000.gpu: IRQ pp5 not found
[    0.173113] lima ff300000.gpu: IRQ pp6 not found
[    0.173529] lima ff300000.gpu: IRQ pp7 not found
[    0.173947] lima ff300000.gpu: l2 cache 8K, 4-way, 64byte cache line, 128bit external bus
[    0.174673] lima ff300000.gpu: l2 cache 64K, 4-way, 64byte cache line, 128bit external bus
[    0.176000] lima ff300000.gpu: bus rate = 163840000
[    0.176443] lima ff300000.gpu: mod rate = 163840000
[    0.177300] [drm] Initialized lima 1.0.0 20190217 for ff300000.gpu on minor 0
[    0.186009] loop: module loaded
[    0.186308] mtip32xx Version 1.3.1
[    0.190060] spi-nor spi0.0: mx25l12805d (16384 Kbytes)
[    0.194281] libphy: Fixed MDIO Bus: probed
[    0.195918] rk_gmac-dwmac ff540000.ethernet: IRQ eth_wake_irq not found
[    0.196510] rk_gmac-dwmac ff540000.ethernet: IRQ eth_lpi not found
[    0.197287] rk_gmac-dwmac ff540000.ethernet: PTP uses main clock
[    0.197863] rk_gmac-dwmac ff540000.ethernet: phy regulator is not available yet, deferred probing
[    0.200226] dwc3 ff600000.dwc3: Failed to get clk 'ref': -2
[    0.201342] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.201921] ehci-platform: EHCI generic platform driver
[    0.204785] ehci-platform ff5c0000.usb: EHCI Host Controller
[    0.205360] ehci-platform ff5c0000.usb: new USB bus registered, assigned bus number 1
[    0.206204] ehci-platform ff5c0000.usb: irq 31, io mem 0xff5c0000
[    0.220891] ehci-platform ff5c0000.usb: USB 2.0 started, EHCI 1.00
[    0.222126] hub 1-0:1.0: USB hub found
[    0.222501] hub 1-0:1.0: 1 port detected
[    0.223379] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.223966] ohci-platform: OHCI generic platform driver
[    0.224813] ohci-platform ff5d0000.usb: Generic Platform OHCI controller
[    0.225481] ohci-platform ff5d0000.usb: new USB bus registered, assigned bus number 2
[    0.226334] ohci-platform ff5d0000.usb: irq 32, io mem 0xff5d0000
[    0.289536] hub 2-0:1.0: USB hub found
[    0.289909] hub 2-0:1.0: 1 port detected
[    0.291286] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    0.291799] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 3
[    0.292687] xhci-hcd xhci-hcd.0.auto: hcc params 0x0220fe64 hci version 0x110 quirks 0x0000000002010010
[    0.293645] xhci-hcd xhci-hcd.0.auto: irq 166, io mem 0xff600000
[    0.295077] hub 3-0:1.0: USB hub found
[    0.295449] hub 3-0:1.0: 1 port detected
[    0.296230] xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
[    0.296736] xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 4
[    0.297475] xhci-hcd xhci-hcd.0.auto: Host supports USB 3.0 SuperSpeed
[    0.298124] usb usb4: We don't know the algorithms for LPM for this host, disabling LPM.
[    0.299373] hub 4-0:1.0: USB hub found
[    0.299754] hub 4-0:1.0: 1 port detected
[    0.300690] usbcore: registered new interface driver usb-storage
[    0.301447] i2c /dev entries driver
[    0.304337] rk808 1-0018: chip id: 0x8050
[    0.312698] rk808-regulator rk808-regulator: there is no dvs0 gpio
[    0.313334] rk808-regulator rk808-regulator: there is no dvs1 gpio
[    0.316396] vdd_log: supplied by vdd_5v
[    0.318345] vdd_arm: supplied by vdd_5v
[    0.318968] vcc_ddr: supplied by vdd_5v
[    0.320504] vcc_io_33: supplied by vdd_5v
[    0.323872] vcc_18: supplied by vcc_io_33
[    0.327393] vcc18_emmc: supplied by vcc_io_33
[    0.330843] vdd_10: supplied by vdd_5v
[    0.340429] rk808-rtc rk808-rtc: registered as rtc0
[    0.347153] energy_model: pd0: hertz/watts ratio non-monotonically decreasing: em_cap_state 1 >= em_cap_state0
[    0.350103] sdhci: Secure Digital Host Controller Interface driver
[    0.350655] sdhci: Copyright(c) Pierre Ossman
[    0.351038] Synopsys Designware Multimedia Card Interface Driver
[    0.352150] dwmmc_rockchip ff500000.dwmmc: IDMAC supports 32-bit address mode.
[    0.352810] dwmmc_rockchip ff500000.dwmmc: Using internal DMA controller.
[    0.353434] dwmmc_rockchip ff500000.dwmmc: Version ID is 270a
[    0.353991] dwmmc_rockchip ff500000.dwmmc: DW MMC controller at irq 28,32 bit host data width,256 deep fifo
[    0.354888] vcc_sd: supplied by vcc_io_33
[    0.373025] mmc_host mmc0: Bus speed (slot 0) = 400000Hz (slot req 400000Hz, actual 400000HZ div = 0)
[    0.386699] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.388628] ledtrig-cpu: registered to indicate activity on CPUs
[    0.389554] usbcore: registered new interface driver usbhid
[    0.390046] usbhid: USB HID core driver
[    0.391538] NET: Registered protocol family 10
[    0.393067] Segment Routing with IPv6
[    0.393470] NET: Registered protocol family 17
[    0.393938] 8021q: 802.1Q VLAN Support v1.8
[    0.410712] rk_gmac-dwmac ff540000.ethernet: IRQ eth_wake_irq not found
[    0.411307] rk_gmac-dwmac ff540000.ethernet: IRQ eth_lpi not found
[    0.411967] rk_gmac-dwmac ff540000.ethernet: PTP uses main clock
[    0.412601] rk_gmac-dwmac ff540000.ethernet: clock input or output? (input).
[    0.413312] rk_gmac-dwmac ff540000.ethernet: TX delay(0x24).
[    0.413823] rk_gmac-dwmac ff540000.ethernet: RX delay(0x18).
[    0.414339] rk_gmac-dwmac ff540000.ethernet: integrated PHY? (no).
[    0.414920] rk_gmac-dwmac ff540000.ethernet: cannot get clock clk_mac_speed
[    0.415529] rk_gmac-dwmac ff540000.ethernet: clock input from PHY
[    0.421093] rk_gmac-dwmac ff540000.ethernet: init for RGMII
[    0.421946] rk_gmac-dwmac ff540000.ethernet: User ID: 0x10, Synopsys ID: 0x35
[    0.422583] rk_gmac-dwmac ff540000.ethernet: .DWMAC1000
[    0.423045] rk_gmac-dwmac ff540000.ethernet: DMA HW capability register supported
[    0.423700] rk_gmac-dwmac ff540000.ethernet: RX Checksum Offload Engine supported
[    0.424356] rk_gmac-dwmac ff540000.ethernet: COE Type 2
[    0.424815] rk_gmac-dwmac ff540000.ethernet: TX Checksum insertion supported
[    0.425479] rk_gmac-dwmac ff540000.ethernet: Wake-Up On Lan supported
[    0.426054] rk_gmac-dwmac ff540000.ethernet: Normal descriptors
[    0.426577] rk_gmac-dwmac ff540000.ethernet: Ring mode enabled
[    0.427096] rk_gmac-dwmac ff540000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    0.428015] libphy: stmmac: probed
[    0.497674] random: fast init done
[    0.499433] rk808-rtc rk808-rtc: setting system clock to 2016-01-21T08:50:08 UTC (1453366208)
[    0.501885] Waiting for root device PARTUUID=5452574f-02...
[    0.632938] usb 4-1: new SuperSpeed Gen 1 USB device number 2 using xhci-hcd
[    0.967223] dwmmc_rockchip ff500000.dwmmc: Busy; trying anyway
[    1.467754] mmc_host mmc0: Timeout sending command (cmd 0x202000 arg 0x0 status 0x80202000)
[    1.504657] mmc0: error -110 whilst initialising SD card
[    2.006082] dwmmc_rockchip ff500000.dwmmc: Busy; trying anyway
[    2.506614] mmc_host mmc0: Timeout sending command (cmd 0x202000 arg 0x0 status 0x80202000)
[    2.521201] mmc_host mmc0: Bus speed (slot 0) = 300000Hz (slot req 300000Hz, actual 300000HZ div = 0)
[    3.052235] dwmmc_rockchip ff500000.dwmmc: Busy; trying anyway
[    3.552768] mmc_host mmc0: Timeout sending command (cmd 0x202000 arg 0x0 status 0x80202000)
[    3.567365] mmc_host mmc0: Bus speed (slot 0) = 200000Hz (slot req 200000Hz, actual 200000HZ div = 0)
[    4.105186] dwmmc_rockchip ff500000.dwmmc: Busy; trying anyway
[    4.605720] mmc_host mmc0: Timeout sending command (cmd 0x202000 arg 0x0 status 0x80202000)
[    4.620321] mmc_host mmc0: Bus speed (slot 0) = 100000Hz (slot req 100000Hz, actual 100000HZ div = 0)
[    5.178334] dwmmc_rockchip ff500000.dwmmc: Busy; trying anyway
[    5.678867] mmc_host mmc0: Timeout sending command (cmd 0x202000 arg 0x0 status 0x80202000)
[   31.708935] vcc_sd: disabling

**Comment by AmadeusGhost** [comment]
要不换张 sd 卡试试吧

**Comment by garlicsoft** [comment]
> 要不换张 sd 卡试试吧


用过balenaEtcher跟dd命令写入过，都失败了。同一张卡用orangepi官方提供的img文件是可以启动的主要是。

**Comment by AmadeusGhost** [comment]
试试看这个 commit 吧：https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7
```
wget https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7.patch
git apply 186da22398ffb786858a15638a7eacb8ce1119d7.patch
```

**Comment by garlicsoft** [comment]
> 试试看这个 commit 吧：[AmadeusGhost@186da22](https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7)
> 
> ```
> wget https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7.patch
> git apply 186da22398ffb786858a15638a7eacb8ce1119d7.patch
> ```

感谢，不过我编译成功了还是无法启动，最后还是用官方提供的openwrt仓库，配合helloworld源编译出来一份包含ssr plus的镜像。
也挺多波折的（主要是官方git版本里的openwrt版本比较低，但是feeds源又有变化，以及ssr需要一些lede的包需要手动拷进去）

**Comment by garlicsoft** [comment]
> 试试看这个 commit 吧：[AmadeusGhost@186da22](https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7)
> 
> ```
> wget https://github.com/AmadeusGhost/lede/commit/186da22398ffb786858a15638a7eacb8ce1119d7.patch
> git apply 186da22398ffb786858a15638a7eacb8ce1119d7.patch
> ```

感谢，不过我编译成功了还是无法启动，最后还是用官方提供的openwrt仓库，配合helloworld源编译出来一份包含ssr plus的镜像。
也挺多波折的（主要是官方git版本里的openwrt版本比较低，但是feeds源又有变化，以及ssr需要一些lede的包需要手动拷进去）

**Comment by BINGHUAice** [comment]
官方提供的固件能够使用不代表编译的lean的固件能够使用，我最近也在折腾R1P，我手里很多张TF卡，我发现不管什么固件总有TF卡不能够引导。除了更换TF卡与固件，这里给出一些自己摸索出来的建议：1：更换写盘工具：比如Win32DiskImager，2：更换固件的打包方式，3：更换TF卡读卡器（没错，这个也会影响，我还遇到了）4：写入固件之前可以尝试格盘，并且软件可以多试几个如SD Card Formatter，LLFTOOL等。

**Comment by garlicsoft** [comment]
> 官方提供的固件能够使用不代表编译的lean的固件能够使用，我最近也在折腾R1P，我手里很多张TF卡，我发现不管什么固件总有TF卡不能够引导。除了更换TF卡与固件，这里给出一些自己摸索出来的建议：1：更换写盘工具：比如Win32DiskImager，2：更换固件的打包方式，3：更换TF卡读卡器（没错，这个也会影响，我还遇到了）4：写入固件之前可以尝试格盘，并且软件可以多试几个如SD Card Formatter，LLFTOOL等。

感谢，我的手上只有两张空闲的tf卡（sandisk）都引导不能，换了官方代码编译出来的固件可以引导。目前暂时先把思路放在lede的机器补丁问题上，之前有替换代码编译完成，但也没能成功引导，可能还有些地方没有注意到。

**Comment by AmadeusGhost** [comment]
要不再试试这个更改吧，不能启动的话最好能有 ttl log 方便分析问题🤣
```
git pull
git revert 6aa3ed2b19a680b406fafade10bf01095f5f18be
wget https://github.com/AmadeusGhost/lede/commit/39833b3bb6a153bc6c6e8600266d9a8d1159233e.patch
git apply 39833b3bb6a153bc6c6e8600266d9a8d1159233e.patch
```
