### ISSUE TITLE
V2Ray Pro 未运行

### ISSUE THREAD

**Issue by lucky0l** [coolsnowwolf/lede#668]
今天自己按默认编译了一下固件，加入了V2Ray Pro，配置是正确的，服务器时间也都是一样的，但是路由上一直显示未运行，这可能会是哪方面的原因呢？

**Comment by lucky0l** [comment]
全部重新编译后解决，加入了network项下的所有V2相关的，然后去掉了SS，只留了SSR和V2

**Comment by qzi** [comment]
> 全部重新编译后解决，加入了network项下的所有V2相关的，然后去掉了SS，只留了SSR和V2

我也是v2ray 4.9 在pandorabox  上安装后未运行，但是不知道你这个步骤怎么弄

v2ray | v4.9.0
-- | --
