### ISSUE TITLE
ssh登录出现错误remote side unexpectedly closed network connection

### ISSUE THREAD

**Issue by Dimitri2020007** [coolsnowwolf/lede#6689]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

编译固件版本是最新源码编译的，没有编译dropbear只编译了openssh，iptables开放lan侧端口允许ssh登录。

系统hyper-v第2代 server2019

i5 10400f+b460

### (1) 具体问题

A：初次设置密码后可以直接通过ssh登录，重启之后再登录就出错了，怎么连都连不上。

### (2) 路由器型号和固件版本

A：x86-64 efi

### (3) 详细日志

A：重启路由后再通过ssh登录出现remote side unexpectedly closed network connection

**Comment by Beginner-Go** [comment]
Fix https://github.com/coolsnowwolf/packages/pull/145
