### ISSUE TITLE
upnp升级一下吧

### ISSUE THREAD

**Issue by swxk521** [coolsnowwolf/lede#6697]
有的客户端下线，端口还在，越来越多。

**Comment by TXH201622** [comment]
现在的UPNP是测试过的最好用的版本，不可能换的。

**Comment by Neverends4** [comment]
> 有的客户端下线，端口还在，越来越多。
默认设置不够合理。试下这个，第一个阈值必须改成1，后面的自动清除时间自己改：
	option clean_ruleset_threshold '1'
	option clean_ruleset_interval '1800'
