### ISSUE TITLE
lede偶尔会自动挂掉上不了网

### ISSUE THREAD

**Issue by idoall** [coolsnowwolf/lede#6699]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：如标题，发现情况是死机了，不定时的隔几天就会出现，通过ESXI能够发现，突然间CPU和内存跑满了。OpenWrt登录不上去，只能通过Exsi重启就好了

### (2) 路由器型号和固件版本

A：软路由，固件版本OpenWrt R20.8.27 / LuCI Master (git-20.223.26773-d18ef13)
--

### (3) 详细日志

A：日志怎么查看？死机再重启以后，日志就没有了

**Comment by Dimitri2020007** [comment]
你这个问题可以报到#6489

**Comment by yjd** [comment]
把 FLOW 加速 禁用。这个我在k2p也遇到。会导致系统重启。

**Comment by idoall** [comment]
> 把 FLOW 加速 禁用。这个我在k2p也遇到。会导致系统重启。

是网络-〉下面的SFE加速关闭吗？

**Comment by yjd** [comment]
是

**Comment by idoall** [comment]
> 是

感谢，先关掉试试看

**Comment by kuole-o** [comment]
最新5.4内核 k2p感觉网速有些慢，更像是dns解析出问题了。豆瓣 知乎这些，加载很慢，图片大多时候崩溃出不来
