### ISSUE TITLE
关于kcptun

### ISSUE THREAD

**Issue by gavin219** [coolsnowwolf/lede#67]
1、源里没有找到kcptun的luci；
2、自己编译的固件（7.4）执行root@Gavin:~# /usr/bin/client_linux_arm7
Illegal instruction
请教如何解决？

**Comment by waterun** [comment]
自己clone https://github.com/kuoruan/luci-app-kcptun 到lean大的package目录，需要改一下makefile，不然编译不进去。
将 include ../../luci.mk 改为
include $(TOPDIR)/feeds/luci/luci.mk
即可

**Comment by waterun** [comment]
2.bin文件luci内可以手动下载和更新
