### ISSUE TITLE
编译时luci-app-samba无法取消

### ISSUE THREAD

**Issue by byl0561** [coolsnowwolf/lede#6703]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译时luci-app-samba无法取消

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译时luci-app-samba无法取消，该组件好像是在NAS模块下，该模块是默认开启的。如果没有这类需求可以取消吗，感觉不太安全

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：N/A

**Comment by EnnawYang** [comment]
` Extra packages  ---> < > autosamba `
` LuCI  ---> 3. Applications  ---> < > luci-app-samba `
自己摸索依赖关系

**Comment by byl0561** [comment]
感谢，之前一直在app里面找，没想到extra里还有
