### ISSUE TITLE
有一些国外域名被劫持到国内dns解析 这个bug存在好久了 

### ISSUE THREAD

**Issue by dddfgeer** [coolsnowwolf/lede#6706]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by hplee0120** [comment]
你的意思是不是部分国外域名实际并没有走ssrp代理 还是被国内dns 解析了，是的话建议你可以试试passwall看看，因为passwall有加了一个chinadns分流，对于国内外的域名是否走代理应该比较准确一点。而ssrp似乎是只有gfw列表的域名才会强制走远程dns查询。其实这个应该不算bug ，应该是插件本身就是这么设计判断的，虽然我也希望ssrp能够加上chinadns
