### ISSUE TITLE
如何才能正确的把CONE NAT编译和启用?

### ISSUE THREAD

**Issue by cn-404-not-found** [coolsnowwolf/lede#6720]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：make menuconfig 都已经选择 Network -> Firewall -> iptables-mod-fullconenat

编译成功后，启用 FullCone-NAT已经可以勾选，但是在Turbo ACC 网络加速设置中，FullCone-还是显示未运行

而且，只要勾选了FullCone-NAT，就无法上网

请问我设置错了什么地方吗，是否需要在编译的时候加入其他插件？

### (2) 路由器型号和固件版本

A：X86 64位

### (3) 详细日志

A：

**Comment by cjw7360** [comment]
* 路由器型号：FriendlyElec NanoPi R4S (1G)
* 固件版本：OpenWrt R21.11.11 / LuCI Master (git-21.329.83689-00cb491)
 
没有编译Turbo ACC，但是编译了BBR并开启了。也是一样的勾选了Firewall下的FullCone-NAT就不能上网了。请问谁知道这是什么情况呢？

其他插件：SQM QoS(未启用)、PassWall(未启用)、Privoxy(未启用)、SmartDNS(未启用)、WireGuard(未启用)、UPnP(启用)以及几个SMB网络存储插件
