### ISSUE TITLE
安装了uHTTPd无法使用https访问

### ISSUE THREAD

**Issue by authon** [coolsnowwolf/lede#6730]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：安装了uHTTPd无法使用https访问

      记得上一次是装好系统后另外装了个ssl 的插件，忘记是啥了，哪位大佬知道

      这次尝试了安装luci-ssl-openssl和luci-ssl，装完后重启uHTTPd，无法访问管理页面

      如果需要使用uHTTPd外网访问https，编译的时候还需要编译什么

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by iPixelOldC** [comment]
额，你这百度下不就有了嘛，咱一直用这个方法。并且为了方便上传，其实还可以装个luci-uhttpd的管理插件。https://www.jianshu.com/p/a40ccb3e8ed6
