### ISSUE TITLE
libfido2 not exist

### ISSUE THREAD

**Issue by doumeki** [coolsnowwolf/lede#6731]
WARNING: Makefile 'package/feeds/packages/openssh/Makefile' has a dependency on 'libfido2', which does not exist
WARNING: Makefile 'package/feeds/packages/openssh/Makefile' has a build dependency on 'libfido2', which does not exist

**Comment by jxph1123** [comment]
同样警告。

**Comment by shedkiss** [comment]
same problem and please fix it ,thanks!

**Comment by Cathgao** [comment]
just ignore it if complie return no error

**Comment by Myoko** [comment]
忽略这个

**Comment by shedkiss** [comment]
if you can help to fix that ?thanks

**Comment by Cathgao** [comment]
> if you can help to fix that ?thanks

No need to fix if no error. It doesn't have any influence on anything

**Comment by CuteTony** [comment]
[packages feed](https://github.com/coolsnowwolf/packages)已经添加 `libcbor` 和 `libfido2` 依赖，不影响。
若不放心再执行一次 `./scripts/feeds update -a && ./scripts/feeds install -a` 即可看到警告消除。
