### ISSUE TITLE
希望LEDE能升级到5.10内核版本了

### ISSUE THREAD

**Issue by uosX** [coolsnowwolf/lede#6736]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by minlang112** [comment]
为什么要追新呢……说不定性能还不如5.4

**Comment by TXH201622** [comment]
5.10的坑你去填

**Comment by BGzErol** [comment]
这玩意不应该追求稳定吗

**Comment by coolsnowwolf** [comment]
没有找到必要性，trunk 版本都还在填坑

**Comment by sanqudui8ban** [comment]
openwrt raspberry wifi 的驱动 用的cfg80211 就是 5.8+的内核，搞得人好尴尬。
