### ISSUE TITLE
SSR Plus+ 开启后出现Out of memory问题

### ISSUE THREAD

**Issue by nikitazep** [coolsnowwolf/lede#6739]
一直用SSR Plus+运行trojan，之前没有问题

使用久了后，经常在打开LEDE ui界面时跳出错误：out of memory，且无法上网

一旦关闭SSR Plus+后，网络恢复正常，但只能连内网

不过SOCKS5 代理服务端（全局）通过SwitchyOmega还能正常使用

**Comment by coolsnowwolf** [comment]
字面意思就是内存耗尽了
