### ISSUE TITLE
Luci-app-ssr-plus 不见了

### ISSUE THREAD

**Issue by dtlics** [coolsnowwolf/lede#6741]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：luci-app-ssr-plus在repo的packages里被移除了？哪个版本移除的呀？想用怎么办？有更好的替代吗？

### (2) 路由器型号和固件版本

A：小米4a 已经成功刷好了 但找不到我需要的插件

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
您刚从煋回来？
