### ISSUE TITLE
请教一个多目标系统编译问题

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#6742]
抱歉，占用一个Issue来请教。 我现在都是在本地编译，但我想同时编译x86和/rockchip，所以问题是

1）请问可以在一次编译里同时完成x86/rockchip的编译嘛
2）如果不可以，那如果是分开先后编译，是每次需要make clean然后重新make menuconfig设定target system profile是吗？还是不用clean,每次重新Load一下不同的config就可以make 了？
3）如果我想并行，我想用两个用户或者screen的方式share同一个git目录并行编译，会有目标文件冲突吗，还是建议git目录分开创建？

**Comment by liwenjie119** [comment]
一般情况下不需要make clean。没有试过同时编译，但是如果都能正常编译通过不出错的情况下，准备好两个config，写个脚本编译完一个接着编译下一个就行。

**Comment by aizhouyi** [comment]
至于同时编译两个固件好像没有
分开编译已经写的很明白了
```shell
rm -rf ./tmp && rm -rf .config
把另外一个.config复制进来就好
make -j$(($(nproc) + 1)) V=s
```
写个自动sh脚本完成上面操作就好了

**Comment by acooler15** [comment]
建议分开两个目录搞，编译openwrt固件都会生成缓存，下次再编译同一CPU架构的固件时可以节省一些时间。
