### ISSUE TITLE
解锁网易云插件 个别设备无效

### ISSUE THREAD

**Issue by MrVicent** [coolsnowwolf/lede#6749]
路由器：斐讯k3 和 红米ac2100
电脑客户端 无需设置代理 直接可用
手机：
杂粮9 不设置代理无法使用、wifi设置5200之后使用正常
杂粮10 不设置代理无法使用 wifi设置5200之后也无法使用
果x ca证书已设置 能解锁灰色歌曲 但无法播放
多次测试都是这种结果
不确定是手机问题还是插件问题 搞得我人迷茫了

**Comment by EnnawYang** [comment]
手机端不要使用过新的版本

**Comment by y9858** [comment]
好像前几天开始完全失效了

**Comment by EnnawYang** [comment]
> 好像前几天开始完全失效了

那可以按照 https://github.com/nondanee/UnblockNeteaseMusic/issues/737 其中的方法改下

**Comment by yubanmeiqin9048** [comment]
我这电脑端也用不了了，手机端老早就用不了了，用的上古版本也不行
