### ISSUE TITLE
编译node包错

### ISSUE THREAD

**Issue by 244099121** [coolsnowwolf/lede#6750]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
但是并未解决
## 2. 详细叙述
本人机器信息：
song@song 
--------- 
OS: Arch Linux x86_64 
Host: 81FW Lenovo Legion Y7000 
Kernel: 5.11.13-xanmod1-1-uksm 
Uptime: 5 hours, 5 mins 
Packages: 1228 (pacman), 15 (flatpak) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 40.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: HighContrastInverse [GTK2/3] 
Icons: McMuse [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
GPU: Intel UHD Graphics 630 
Memory: 7879MiB / 15721MiB

想使用源码编译出sdk用于编译其他插件但是编译到nobe报措
### (1) 具体问题

A：
clone了最新的源码
arch linux平台
按照github的源码下方文章步骤执行编译, 无法通过
已经使用路由器代理全局流量，不存在墙的问题，网络问题
单线程编译nobe报错
![2021-04-24 17-51-34 的屏幕截图](https://user-images.githubusercontent.com/37263156/115954847-be4ca880-a525-11eb-997d-d3d4b3f817e2.png)

### (2) 路由器型号和固件版本

A：J1900 x86平台软陆游

### (3) 详细日志

make[3]: *** [Makefile:158: /home/song/lede/build_dir/target-x86_64_musl/node-v12.18.4/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/song/lede/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#0.19#0.20#0.38
make[2]: *** [package/Makefile:113: package/feeds/packages/node/compile] Error 2
make[2]: Leaving directory '/home/song/lede'
make[1]: *** [package/Makefile:107: /home/song/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/song/lede'
make: *** [/home/song/lede/include/toplevel.mk:224：world] 错误 2

**Comment by EnnawYang** [comment]
倒数9行不是很明显的告诉你原因了么
