### ISSUE TITLE
is:issue is:open    第三方插件编译流程咨询（大老们讲讲 ），我不是反馈问题，没资格

### ISSUE THREAD

**Issue by zhouxiaolong920** [coolsnowwolf/lede#6755]
1. 我目前编译没有问题。
2. 知道lede package下 lean是个相关的第三方插件 
3. 如果我知道UnblockNeteaseMusicGo插件代码有问题。官方还没有修改，我自己修改了。应该修改哪个目录 ？我find了一下很多目录都有同名，以UnblockNeteaseMusicGo为例
     3.1 修改build_dir/target-xxxxx_musl/UnblockNeteaseMusicGo，（是修改这里的代码）
     3.2 我目前是fork一版本。lede package下 lean下的的makefile修改成我的仓库地址，进行编译的
     
     
     
   能不能简单说一下。编译的时候。dl目录的tar包，会被解压到哪？然后在怎么样，怎么样。
   最终编译成。整个流程讲讲。。

跪求。

**Comment by doumeki** [comment]
你make clean一次就知道要改哪个目录下的了。
