### ISSUE TITLE
建议给passwall ssrplus 增加china dns ng解决国外域名劫持到国内dns解析的问题

### ISSUE THREAD

**Issue by dddfgeer** [coolsnowwolf/lede#6759]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by dddfgeer** [comment]
r4s试了好多固件 都有这些毛病 国外域名劫持到国内来解析

**Comment by ZqinKing** [comment]
> r4s试了好多固件 都有这些毛病 国外域名劫持到国内来解析

编个smartdns进去，弄两组解析，一组专门解析国内，一组专门解析国外就ok了。把ssr+的dns解析指向国外那组就可以了。

**Comment by BGzErol** [comment]
按ssrp的逻辑来说本来就是gfw列表里的会通过代理转发到vps那解析，其他的都是走国内解析的，你这问题实际上貌似是正常的解析逻辑（？）。还有passwall现在倒是是默认启动chinadns-ng的了。
（说实话我也觉得ssrp能配个chinadns-ng挺好的，按照原理chinadns-ng的原理来说配合v6路由表能过滤掉所有来自国外的ipv6解析，只留下国内解析，实现ipv6与爬墙完美共存，还能实现最佳国内外cdn，不过我翻了下以前的issues，貌似是大雕怕影响稳定性才没考虑加的）
