### ISSUE TITLE
重新编译出错

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6766]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
Applying ./patches/001-Remove-concurrency-limit.patch using plaintext:
patching file src/net/tools/naive/naive_proxy.cc
Hunk #2 FAILED at 38.
1 out of 2 hunks FAILED -- saving rejects to file src/net/tools/naive/naive_proxy.cc.rej
patching file src/net/tools/naive/naive_proxy_bin.cc
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 299 with fuzz 1.
Patch failed!  Please fix ./patches/001-Remove-concurrency-limit.patch!
make[3]: *** [Makefile:148: /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-90.0.4430.85-4/.prepared_1f0caa767cde5bedf79f70be1e03adff_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/qqsir/lede/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#1.81#0.94#2.75
make[2]: *** [package/Makefile:113: package/feeds/helloworld/naiveproxy/compile] Error 2
make[2]: Leaving directory '/home/qqsir/lede'
make[1]: *** [package/Makefile:107: /home/qqsir/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/qqsir/lede'
make: *** [/home/qqsir/lede/include/toplevel.mk:224: world] Error 2
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
就这点日志让大家帮你算命？

**Comment by EnnawYang** [comment]
> 就这点日志让大家帮你算命？

dalao快帮忙算算（雾
![Snipaste_2021-04-27_19-30-12](https://user-images.githubusercontent.com/6705663/116234299-fefb2a80-a78e-11eb-93a6-91a9c4bb8383.png)

**Comment by qqsir-dev** [comment]
单线程编的，这回可以吗

**Comment by KK2018gh** [comment]
我也遇到这样的编译出错，好像不加SSR就可以了。

**Comment by hxlls** [comment]
这个已经有人提交PR了，在helloword
