### ISSUE TITLE
新增集成插件，个人能力有限折腾多久都运行不起来。

### ISSUE THREAD

**Issue by libinanshu** [coolsnowwolf/lede#6774]
反馈bug/问题模板，提建议请删除

## 1.新增集成插件
https://github.com/garypang13/openwrt-packages/tree/master/luci-app-phtunnel
https://github.com/garypang13/openwrt-packages/tree/master/phtunnel

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：折腾了多久都运行不起来，不知道问题出在哪里。

### (2) 路由器型号和固件版本

A：MIIPS

### (3) 详细日志

A：

**Comment by 1715173329** [comment]
谁写的找谁
你贴的这个地址无非也不过是抄袭来的罢了
