### ISSUE TITLE
L大，建议源码中默认可以用Nginx替换掉uhttp #6498

### ISSUE THREAD

**Issue by uosX** [coolsnowwolf/lede#6776]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
L大，建议源码中默认可以用Nginx替换掉uhttp

Q：是否搜索了issue (使用 "x" 选择)
* [ ] #6498

### (1) 具体问题

A：L大，建议源码中默认可以用Nginx替换掉uhttp #6498
目前已经有相关安全领域在研究uhttp漏洞，出现重大漏洞情况，请提前换成Nginx
https://www.freebuf.com/articles/network/269696.html
A：x86软路由

**Comment by sxx1314** [comment]
听风就是雨

**Comment by hxlls** [comment]
整篇文章就没看到提到有漏洞，只是研究而已，有必要么？

**Comment by galaxyskyknight** [comment]
没有必要，uhttp挺好用的，一键指定证书实现htttps, 我就用这个功能

**Comment by EnnawYang** [comment]
如之前那个issue所讲 没有必要

**Comment by XiaoliChan** [comment]
这篇文章也就是代码审计啊，哪有什么问题，你也可以出一篇“nignx源码分析”
