### ISSUE TITLE
建议: 调整插件的监听地址

### ISSUE THREAD

**Issue by xxxsen** [coolsnowwolf/lede#6781]
看了下, 默认配置下, 很多程序都是直接监听0.0.0.0, 当作为主路由且有公网ip的时候, 这些端口可以直接被外部访问到, 存在一定的风险。

![image](https://user-images.githubusercontent.com/3880276/116564608-b894ff80-a937-11eb-8289-ab9af6359f17.png)

**Comment by EnnawYang** [comment]
防火墙是干啥用的

**Comment by xxxsen** [comment]
@EnnawYang 我的锅, 测试了下, 从外网访问会被reset, 这个单子关了。
