### ISSUE TITLE
固件编译问题

### ISSUE THREAD

**Issue by czw1259** [coolsnowwolf/lede#6783]
大佬怎么今天我在线编译你的源码出来的固件只有一个版本的固件，这个版本没法在线升级啊！以前都是正常的编译出两个版本的固件
![屏幕截图 2021-04-30 181619](https://user-images.githubusercontent.com/75195638/116681966-39a7d180-a9e0-11eb-9123-721908046125.png)

**Comment by EnnawYang** [comment]
固件过大
