### ISSUE TITLE
内核问题请教

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#6785]
Hi Team,

最近发现X86的固件总是报一个内核文件找不到，找了几个帖子，我没找到一个好的解决办法

Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management

![2021-05-02_091118](https://user-images.githubusercontent.com/25215114/116798942-0e0e0f80-aae4-11eb-846c-69f458e767c0.jpg)

BR
Robin

**Comment by sxx1314** [comment]
自行把相应firmware编译进去即可

**Comment by Guxing0321** [comment]
Hi sxx1314，

可以提供下教程不，我这边找了几个链接，都没有说清楚
https://koolshare.cn/thread-178689-1-1.html
![步骤](https://user-images.githubusercontent.com/25215114/116836222-344fb000-abb5-11eb-8346-562d63591479.jpg)
这里面提供的步骤，我没在menuconfig 里面找到

BR
Robin

**Comment by Promix953** [comment]
```
echo 'CONFIG_EXTRA_FIRMWARE="i915/skl_dmc_ver1_27.bin"' >> target/linux/x86/config-5.4
echo 'CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware"' >> target/linux/x86/config-5.4
```

**Comment by Guxing0321** [comment]
Hi @Promix953

好的，我来试下

BR
RobiN

**Comment by Guxing0321** [comment]
Hi @Promix953

添加了两行配置之后，报了一个错误
` No rule to make target '/lib/firmware/i915/kbl_dmc_ver1_04.bin', needed by 'drivers/base/firmware_loader/builtin/i915/kbl_dmc_ver1_04.bin.gen.o'.  Stop.`

![编译](https://user-images.githubusercontent.com/25215114/117006113-91dc1d80-acd7-11eb-836f-0330f7b22db7.jpg)


编译的全部日志如下
[11_Compile the firmware.txt](https://github.com/coolsnowwolf/lede/files/6421163/11_Compile.the.firmware.txt)

请问，我需要怎么操作，还是说哪边少了一步？

BR
Robin

**Comment by Promix953** [comment]
我用的云编译一直是没问题的，这个错误是找不到`kbl_dmc_ver1_04.bin`文件，刚去看了下[https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915](url)是有这个文件的，你检查下自己的环境

**Comment by Promix953** [comment]
想起来了，编译的系统记得安装linux-firmware
`sudo apt install linux-firmware`

**Comment by Guxing0321** [comment]
Hi @Promix953  @sxx1314 ,

我这边找到了解决方案了，修改的代码如下，感谢大佬们的协助
`
# 创建文件夹并下载文件
sudo mkdir /lib/firmware/i915
sudo curl -L https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/i915/kbl_dmc_ver1_04.bin -o /lib/firmware/i915/kbl_dmc_ver1_04.bin

# 添加 'i915/kbl_dmc_ver1_04.bin'
CONFIG_FIRMWARE_IN_KERNEL=y
echo 'CONFIG_FIRMWARE_IN_KERNEL=y' >> target/linux/x86/config-5.4
echo 'CONFIG_EXTRA_FIRMWARE="i915/kbl_dmc_ver1_04.bin"' >> target/linux/x86/config-5.4
echo 'CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware"' >> target/linux/x86/config-5.4

`


BR
Robin

**Comment by newtamax** [comment]
> Hi @Promix953 @sxx1314 ,
> 
> 我这边找到了解决方案了，修改的代码如下，感谢大佬们的协助 `
> 
> ##### 1. 创建文件夹并下载文件
> sudo mkdir /lib/firmware/i915 sudo curl -L https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/i915/kbl_dmc_ver1_04.bin -o /lib/firmware/i915/kbl_dmc_ver1_04.bin
> 
> ##### 2. 添加 'i915/kbl_dmc_ver1_04.bin'
> echo 'CONFIG_FIRMWARE_IN_KERNEL=y' >> target/linux/x86/config-5.4 echo 'CONFIG_EXTRA_FIRMWARE="i915/kbl_dmc_ver1_04.bin"' >> target/linux/x86/config-5.4 echo 'CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware"' >> target/linux/x86/config-5.4
> 
> `
> 
> BR Robin

你好，我也有这个问题，请问你的两个步骤是不是，步骤1是添加文件到自己的编译系统，步骤2是添加支持到openwrt的配置文件？如果是这样，我这么做了还是有出错信息，是我哪里出了问题？谢谢。
