### ISSUE TITLE
v2ray可以用ipv6连接吗？

### ISSUE THREAD

**Issue by TobyTong** [coolsnowwolf/lede#679]
v2ray连上以后看ip111.cn可以获取到VPS的ipv6地址
但是在服务器配置里面输入ipv6地址不能连接
是否可以在服务器配置里面也用上ipv6

**Comment by hcym** [comment]
手机用过，可以
路由器没有v6

**Comment by madcat0513** [comment]
v2一直用的ipv6地址，都很正常，前提是你要有原生的ipv6

**Comment by TobyTong** [comment]
> v2一直用的ipv6地址，都很正常，前提是你要有原生的ipv6

是在路由器上用的吗 ？原生的ipv6是什么意思？那个VPS供应商之前莫名其妙给我换了个主机   那个ip是被墙的     换个IP还要3刀。。。就像能直接用ipv6就直接用了   省的再花钱了

**Comment by TobyTong** [comment]
> 手机用过，可以
> 路由器没有v6

路由器上面是填进去了也没用咯 ？

**Comment by madcat0513** [comment]
我就是路由器上的v2，服务器ipv4也被墙，换ipv6地址就好了，但是你自己要有原生的ipv6的地址

**Comment by TobyTong** [comment]
> 我就是路由器上的v2，服务器ipv4也被墙，换ipv6地址就好了，但是你自己要有原生的ipv6的地址

哦   懂了    应该是我这边电信没给ipv6的问题    我问问去
