### ISSUE TITLE
Redmi CR6608刷lean固件的问题

### ISSUE THREAD

**Issue by idelame** [coolsnowwolf/lede#6794]
CR6608现在可以刷AC2100的pb-boot了，但刷了pb后，无法刷lean的固件，能否支持？

**Comment by idelame** [comment]
CR6608现在可以刷AC2100的pb-boot了，但无法刷lean的固件，能否支持？

**Comment by coolsnowwolf** [comment]
需要更改分区，但这样就刷不会原厂了，等新版 pb-boot 吧

**Comment by idelame** [comment]
不用原厂固件，原厂固件是垃圾。

**Comment by idelame** [comment]
> 需要更改分区，但这样就刷不会原厂了，等新版 pb-boot 吧

不用原厂固件，只想用你的。原厂固件是垃圾。
