### ISSUE TITLE
R7800 SSR plus 外网不稳定

### ISSUE THREAD

**Issue by lan542662** [coolsnowwolf/lede#680]
老版的没有这问题,一连就上,ss plus总是要连3 次以上才上.5 分钟不连外网就处于睡眠状态一样..

**Comment by hcym** [comment]
最近版本的ipset有点怪，我编译时把那个1024的dns缓存取掉才能正常使用

**Comment by nimasi** [comment]
订阅功能可以正常使用吗

**Comment by lan542662** [comment]
@nimasi 不能。大屌说这个看人品。我反正不能

**Comment by lan542662** [comment]
@lyin888 yay

**Comment by hcym** [comment]
今天更新后编译了，基本正常，感谢大雕，嘎嘎嘎
