### ISSUE TITLE
如何解除openwrt下transmission无法连接IPV6生成大量报错日志

### ISSUE THREAD

**Issue by hn315** [coolsnowwolf/lede#6815]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

如何解除openwrt下transmission无法连接IPV6生成大量报错日志

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述

X86 openwrt固件编译进了transmission，用transmission3.00挂PT保种，生成连续错误系统日志。

### (1) 具体问题

openwrt生成的大量连续系统日志，显示没有办法连接外面的ipv6地址。我家所在地移动宽带确实没有下发ipv6地址（会光猫桥接和各种ipv6设置），所以自己禁用（不禁用也会产生错误日志）ipv6。各位大佬，如何去除这个连续报错日志的问题

### (2) 路由器型号和固件版本

X86 openwrt  R21.4.18 内核5.4.115、transmission3.00

### (3) 详细日志

Mon May 10 10:27:14 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:14.247] Couldn't connect socket 44 to 240e:3a1:942c:d850::a6b, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:15 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:15.247] Couldn't connect socket 51 to 2409:8a55:22a0:da20::aaa, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:15 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:15.248] Couldn't connect socket 51 to 240e:388:a16e:5f10::db9, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:15 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:15.248] Couldn't connect socket 44 to 2403:ac00:0:4001::5731, port 39847 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:15 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:15.248] Couldn't connect socket 44 to 2408:8207:2501:d11::afe, port 51614 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:30 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:30.247] Couldn't connect socket 45 to 2408:8207:2501:d11:78b1:6b27:a0c0:b64a, port 51614 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:30 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:30.247] Couldn't connect socket 45 to 2408:8215:d19:5850:b4da:7bdb:3c2d:5f5f, port 40300 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:30 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:30.247] Couldn't connect socket 45 to 2409:8a55:22a0:da20::aaa, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:33 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:33.247] Couldn't connect socket 48 to 240e:398:d4:dff0::fe2, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:33 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:33.248] Couldn't connect socket 57 to 240e:398:d4:dff0::fe2, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:33 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:33.248] Couldn't connect socket 62 to 2409:8a28:10f1:b502:dd4a:18a2:7132:9abd, port 9848 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:36 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:36.247] Couldn't connect socket 48 to 240e:388:a16e:5f10::db9, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:39 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:39.247] Couldn't connect socket 53 to 2a0a:e340:1001:300::1:1, port 61079 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:39 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:39.247] Couldn't connect socket 53 to 2a0a:e340:1001:300::1:1, port 61079 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:40 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:40.247] Couldn't connect socket 53 to 2001:da8:7019:241:b4e2:7182:d6d3:d473, port 28250 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:40 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:40.247] Couldn't connect socket 53 to 2001:da8:7019:241:b4e2:7182:d6d3:d473, port 28250 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:48 2021daemon.err transmission-daemon[22007]: [2021-05-10 10:27:48.247] Couldn't connect socket 38 to 2409:8a1e:53a1:c3f1::e60, port 51413 (errno 13 - Permission denied) (net.c:340)
Mon May 10 10:27:48 2021daemon.err

**Comment by Wilson-coder** [comment]
我最近编译的116内核，Transmission升级到了3.0.11，干脆就无法启动了，看系统日志提示settings.json语法错误，好像是upload-slot设置项参数不对啥的。搜了一下好像也没人提及，只好退回老版本了。

**Comment by hn315** [comment]
transmission连续不断地向openwrt系统日志写入日志，其他的日志根本看不到了。

**Comment by hn315** [comment]
> 我最近编译的116内核，Transmission升级到了3.0.11，干脆就无法启动了，看系统日志提示settings.json语法错误，好像是upload-slot设置项参数不对啥的。搜了一下好像也没人提及，只好退回老版本了。

请问你回退老版本，会出现ransmission连续不断地向openwrt系统日志写入日志的情况吗？谢谢

**Comment by Wilson-coder** [comment]
> > 我最近编译的116内核，Transmission升级到了3.0.11，干脆就无法启动了，看系统日志提示settings.json语法错误，好像是upload-slot设置项参数不对啥的。搜了一下好像也没人提及，只好退回老版本了。
> 
> 请问你回退老版本，会出现ransmission连续不断地向openwrt系统日志写入日志的情况吗？谢谢

有下载任务的时候一样有报警，不过我只是需要下载BT的时候才用，平时不挂PT，所以没有在意。

**Comment by hn315** [comment]
昨天重编的新固件，解决了这个问题。

**Comment by Kisoul** [comment]
> 昨天重编的新固件，解决了这个问题。

请问你是怎么解决的啊？我昨天编译的出现了你这个问题，过一会transmission就卡掉了，进去不了
