### ISSUE TITLE
最近这个版本，helloworld提示依赖丢失

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#6828]
install 的时候，提示依赖丢失，请问如何解决？

builder@BuildServer:~/lede$ ./scripts/feeds install -a
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-check', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist

**Comment by Dimitri2020007** [comment]
相同问题在这里：

https://github.com/fw876/helloworld/issues/520

**Comment by 592732377** [comment]
[#6814 ](https://github.com/coolsnowwolf/lede/pull/6814)

**Comment by galaxyskyknight** [comment]
貌似已修复，可关闭了
