### ISSUE TITLE
ssr plus 服务器端口正常，在别的客户端使用相同端口可以翻墙，但在ssr plus里就不行

### ISSUE THREAD

**Issue by djhdj1** [coolsnowwolf/lede#6830]
1.ssr plus 服务器端口正常，在别的客户端使用相同端口可以翻墙，但在ssr plus里就不行

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

2. ssr plus 服务器端口正常，在别的客户端使用相同端口可以翻墙，但在ssr plus里就不行，参考以下截图
![2021-05-13_212126](https://user-images.githubusercontent.com/57862829/118132644-7f2dbb00-b432-11eb-98aa-fe8c77c3ff32.jpg)
![2021-05-13_212137](https://user-images.githubusercontent.com/57862829/118132668-86ed5f80-b432-11eb-9725-1dcef740258e.jpg)
![2021-05-13_212427](https://user-images.githubusercontent.com/57862829/118132713-953b7b80-b432-11eb-9174-e4e84e3911a7.jpg)
![2021-05-13_213145](https://user-images.githubusercontent.com/57862829/118132754-a1bfd400-b432-11eb-8cdb-b036730c62fb.jpg)

### (3) 详细日志
参考上面的图

**Comment by galaxyskyknight** [comment]
没法帮到你，这种东西因素太多，各处设置太分散，自个儿掌握点调试诊断技术，自个慢慢弄吧

**Comment by Juvenile-lzj** [comment]
我之前的Issues有说到这个问题，ssr plus订阅中转过后的xray节点，TLS host默认还是服务器地址，就导致节点无法使用，需手动将TLS host修改为正确的地址。

**Comment by Pantheon-Paradoxes** [comment]
同样发现这个问题，xray单独会出现这个问题，下次不编xray还是用原来的v2ray trojan试试

**Comment by djhdj1** [comment]
> 我之前的Issues有说到这个问题，ssr plus订阅中转过后的xray节点，TLS host默认还是服务器地址，就导致节点无法使用，需手动将TLS host修改为正确的地址。

请问一下，应该怎么修改啊
