### ISSUE TITLE
想要内置宝塔面板，可以么？

### ISSUE THREAD

**Issue by uosX** [coolsnowwolf/lede#6834]
想要内置宝塔面板，可以么？

**Comment by sxx1314** [comment]
openwrt 并不在宝塔支持范围，并且宝塔的各种组件大多得现编译，用openwrt跑make gcc  各种依赖问题烦死你。推荐直接docker解决，两行命令的事情。

**Comment by NagaseKouichi** [comment]
我用openwrt下的LXC运行的宝塔面板

**Comment by Misaka-Biu** [comment]
没啥必要 可以试试 lxc docker 里面跑宝塔 内置就鸡肋了 毕竟宝塔..

**Comment by uosX** [comment]
你们说的，我都明白，不过主要还是想要在系统物理机集成比较合适，我固件是x86的固件；建议是不是考虑x86固件

**Comment by uosX** [comment]
现在最新的都是PHP8，mysql 8，Nginx 1.20的版本了哈

**Comment by NagaseKouichi** [comment]
LXC也是在物理机上运行的，只是做了隔离，并不是在虚拟机运行，效率没区别

**Comment by kleisth** [comment]
那你干嘛不干脆装linux，装你的宝塔，然后再用docker跑openwrt

**Comment by Guxing0321** [comment]
openwrt装啥宝塔呀
