### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#6836]
![1](https://user-images.githubusercontent.com/61616502/118346873-5102c500-b571-11eb-9402-1580d2291a7b.jpg)
https://sources.cdn.openwrt.org/naiveproxy-90.0.4430.85-6.tar.gz
https://sources.openwrt.org/naiveproxy-90.0.4430.85-6.tar.gz
https://mirror2.openwrt.org/sources/naiveproxy-90.0.4430.85-6.tar.gz

https://mirror2.openwrt.org/sources是可以访问的，整段就打不开
云编译正常，物理机就这样了！

**Comment by AmadeusGhost** [comment]
你网络问题，实际上的下载地址是上面下载失败了的那个 codeload.github.com

**Comment by lexin8** [comment]
> 你网络问题，实际上的下载地址是上面下载失败了的那个 codeload.github.com

换了好几个节点就可以了。
