### ISSUE TITLE
acrh17 wifi 消失、连上无网络

### ISSUE THREAD

**Issue by qianxu2001** [coolsnowwolf/lede#6842]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
如题，测试 2.4GHz 和 5GHz 都会出现，似乎是因为负载高，特别是下 bt 时，频繁复现，几分钟后会恢复，有线网络正常

### (2) 路由器型号和固件版本

A：
OpenWrt R21.4.18 / LuCI Master (git-21.114.56541-974fb04)

### (3) 详细日志

A：
<details>
<summary>系统日志</summary>
<pre><code>Sun May 16 20:52:08 2021 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED a8:7e:ea:6e:78:41
Sun May 16 20:52:08 2021 daemon.info hostapd: wlan0: STA e0:f6:b5:6b:74:21 IEEE 802.11: authenticated
Sun May 16 20:52:08 2021 daemon.notice hostapd: wlan0: STA-OPMODE-MAX-BW-CHANGED e0:f6:b5:6b:74:21 20
Sun May 16 20:52:08 2021 daemon.notice hostapd: wlan0: STA-OPMODE-N_SS-CHANGED e0:f6:b5:6b:74:21 2
Sun May 16 20:52:08 2021 daemon.info hostapd: wlan0: STA e0:f6:b5:6b:74:21 IEEE 802.11: associated (aid 1)
Sun May 16 20:52:08 2021 daemon.notice hostapd: wlan0: AP-STA-CONNECTED e0:f6:b5:6b:74:21
Sun May 16 20:52:08 2021 daemon.info hostapd: wlan0: STA e0:f6:b5:6b:74:21 RADIUS: starting accounting session 45941598DCAB6491
Sun May 16 20:52:08 2021 daemon.info hostapd: wlan0: STA e0:f6:b5:6b:74:21 WPA: pairwise key handshake completed (RSN)
Sun May 16 20:52:19 2021 daemon.info hostapd: wlan1: STA a8:7e:ea:6e:78:41 IEEE 802.11: authenticated
Sun May 16 20:52:19 2021 daemon.info hostapd: wlan1: STA a8:7e:ea:6e:78:41 IEEE 802.11: associated (aid 1)
Sun May 16 20:52:19 2021 daemon.notice hostapd: wlan1: STA-OPMODE-SMPS-MODE-CHANGED a8:7e:ea:6e:78:41 off
Sun May 16 20:52:19 2021 daemon.notice hostapd: wlan1: AP-STA-CONNECTED a8:7e:ea:6e:78:41
Sun May 16 20:52:19 2021 daemon.info hostapd: wlan1: STA a8:7e:ea:6e:78:41 RADIUS: starting accounting session ECD343B05CB13747
Sun May 16 20:52:19 2021 daemon.info hostapd: wlan1: STA a8:7e:ea:6e:78:41 WPA: pairwise key handshake completed (RSN)</code></pre>
</details>
<details>
<summary>内核日志</summary>
<pre><code>[320076.500513] ath10k_ahb a000000.wifi: SWBA overrun on vdev 0, skipped old beacon
[320076.500592] ath10k_ahb a000000.wifi: SWBA overrun on vdev 0, skipped old beacon
[320076.829602] ath10k_ahb a000000.wifi: SWBA overrun on vdev 0, skipped old beacon
[320076.829710] ath10k_ahb a000000.wifi: SWBA overrun on vdev 0, skipped old beacon</code></pre>
</details>

**Comment by ddvcx** [comment]
星际宝盒CM520也是,新版固件无WIFI, 也是IPQ4019
