### ISSUE TITLE
修改network 默认配置

### ISSUE THREAD

**Issue by lexin8** [coolsnowwolf/lede#6844]
想编译一个AP模式的固件，配置好了怎么编译出来就是配置好的状态？
network配置包括了网口跟vlan,

**Comment by lphgor** [comment]
file大法，或者在 [zzz-default-settings](https://github.com/coolsnowwolf/lede/blob/master/package/lean/default-settings/files/zzz-default-settings) 里面用 uci 配置

**Comment by lexin8** [comment]
> file大法，或者在 [zzz-default-settings](https://github.com/coolsnowwolf/lede/blob/master/package/lean/default-settings/files/zzz-default-settings) 里面用 uci 配置

file大法可以配置etc下的文件，其他路径貌似不生效
