### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#6845]
1. luci-app-statistics这个插件，依赖一些collect-mod-*的包，需要在软件源里下载安装，如何在编译的时候就把这些包含在Image里面，同时sysupgrade升级刷Image重启之后就自动安装在系统里了？
2. live system上的/etc/config/***的某个默认应用配置，在编译打包前在哪里修改？

**Comment by galaxyskyknight** [comment]
没人知道吗，还是我问题没表述清楚？

**Comment by EnnawYang** [comment]
![Snipaste_2021-05-18_21-30-47](https://user-images.githubusercontent.com/6705663/118659944-52a5e480-b820-11eb-96cf-1462d5acc7c8.png)

**Comment by galaxyskyknight** [comment]
谢谢楼上，第一个问题解答了。第二个问题呢？某个luci-app得应用配置都在/etc/config/xxx下面，我怎么修改原始default的配置然后编译进image? 还是这里的文件都是刷完image的时候init脚本生成的？
