### ISSUE TITLE
编译报错了，谷歌了大半天没有解决，求助大佬

### ISSUE THREAD

**Issue by cattypapa** [coolsnowwolf/lede#6848]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译报下面的错误
go: finding github.com/pires/go-proxyproto v0.5.0                                                                 |
go: finding golang.org/x/sys v0.0.0-20210415045647-66c3f260301c                                                   |
go: finding github.com/lucas-clemente/quic-go v0.20.1                                                             |
go: finding github.com/gorilla/websocket v1.4.2                                                                   |
go: finding github.com/cheekybits/genny v1.0.0                                                                    |
go: finding golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc                                                |
build github.com/shadowsocks/v2ray-plugin: cannot load io/fs: malformed module path "io/fs": missing dot in first |
path element                                                                                                      |
                                                                                                                  |
Building targets                                                                                                  |
build .: cannot find module for path .                                                                            |
                                                                                                                  |
Cleaning module download cache (golang/go#27455)                                                                  |
                                                                                                                  |
make[3]: *** [Makefile:74: /home/catty/openwrt/build_dir/target-aarch64_generic_musl/v2ray-plugin-4.38.3/.built] E|
rror 1                                                                                                            |
make[3]: Leaving directory '/home/catty/openwrt/feeds/helloworld/v2ray-plugin'                                    |
time: package/feeds/helloworld/v2ray-plugin/compile#0.96#0.73#2.93                                                |
make[2]: *** [package/Makefile:113: package/feeds/helloworld/v2ray-plugin/compile] Error 2
Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by uosX** [comment]
这个我大概知道，你还需要git clone 另一个vssr还是ssrplus的包才行，我就是这么解决的
