### ISSUE TITLE
v2ray 的用户自定义GFW_list里面有m-team.cc，这样默认GFWLIST 会默认PT流量走V2RAY

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#685]

**Comment by d975xbx** [comment]
我的自定义GFW_list里面没有m-team.cc

**Comment by hxlls** [comment]
m-team.cc位于v2ray pro 下的用户自定义列表里面的，删除后保存我的正常，自带更新不会在出现

**Comment by d975xbx** [comment]
你进去看一下，/etc/gfwlist的china-banned有没有m-team.cc？我的v2ray pro 下的用户自定义列表里面没有！

**Comment by zwd2zwd** [comment]
建议到ssr-plus中删除，貌似我的版本只有ssr那边生效，v2ray自定义无法生效，即使点了手动更新
