### ISSUE TITLE
qBittorrent 和 Transmission 无法启动

### ISSUE THREAD

**Issue by sky2016cn** [coolsnowwolf/lede#6851]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [] 没有类似的issue

## 2. 详细叙述
五月份以来编译的新固件，qBittorrent 和 Transmission 都无法正常启动
### (1) 具体问题

A：五月份以来编译的新固件，qBittorrent 和 Transmission 都无法正常启动

### (2) 路由器型号和固件版本

A：x86，5.4.117固件

### (3) 详细日志

A：

**Comment by Wilson-coder** [comment]
QB不清楚，Tr的话试一下在“文件和位置”页面那个umask一项的022改成22，还不行就直接删掉。我昨晚刷新系统之后是直接删掉umask的值，就能启动了，不过后来没有再重启，另外umask不设置，下载分区还是Ext格式的话，可能会影响下载完毕之后的文件操作。你先试一下
