### ISSUE TITLE
最新编译的固件，计划任务cron报错误代码

### ISSUE THREAD

**Issue by cattypapa** [coolsnowwolf/lede#6861]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
在系统日志里面看到的，貌似是计划任务执行失败？我最新编译的Lede固件，之前都没出现过这种问题。错误代码如下。
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Fri May 21 11:08:35 2021 cron.err crond[15816]: crond (busybox 1.33.0) started, log level 5

**Comment by galaxyskyknight** [comment]
这个问题后来是什么原因？怎么解决的？我今天遇到同样的问题

**Comment by cattypapa** [comment]
> 这个问题后来是什么原因？怎么解决的？我今天遇到同样的问题

重新编译了一次固件，好了
