### ISSUE TITLE
同步更新升级linux 4.9.133后AR71XX编译出错

### ISSUE THREAD

**Issue by Lancenas** [coolsnowwolf/lede#687]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sched-cake:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-sched-cake.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-scsi-core:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-scsi-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-aead:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-aead.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-authenc:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-authenc.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-cbc:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-cbc.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-crc32c:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-crc32c.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-deflate:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-deflate.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-des:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-des.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-ecb:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-ecb.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-echainiv:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-echainiv.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-hmac:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-hmac.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-iv:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-iv.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-md5:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-md5.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-sha1:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-sha1.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-ext4:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-fs-ext4.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-vfat:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-fs-vfat.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fuse:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-fuse.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-crc-ccitt:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-lib-crc-ccitt.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-textsearch:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-lib-textsearch.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-macvlan:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-macvlan.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ifb:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ifb.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-reject6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-reject6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-ipt6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-ipt6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-conntrack6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-conntrack6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nat:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nat.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nat6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nat6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-conntrack-extra:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-conntrack-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-ipopt:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-ipopt.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-ipsec:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-ipsec.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-ipset:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-ipset.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-nat:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-nat.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-raw:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-raw.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-nat6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-nat6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-nat-extra:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-nat-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nathelper:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nathelper.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nathelper-extra:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nathelper-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-tproxy:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-tproxy.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-br-netfilter:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-br-netfilter.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-conntrack-netlink:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nf-conntrack-netlink.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nft-core:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nft-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nft-nat:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-nft-nat.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipsec:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipsec.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipsec4:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipsec4.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipsec6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ipsec6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-iptunnel:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-iptunnel.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ip6-tunnel:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ip6-tunnel.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-gre:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-gre.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-gre6:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-gre6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-slhc:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-slhc.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ppp:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-ppp.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-pppox:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-pppox.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-pppoe:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-pppoe.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-mppe:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-mppe.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sched-core:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-sched-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sched:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-sched.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-tcp-bbr:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-tcp-bbr.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-core:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-ledtrig-usbport:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-ledtrig-usbport.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-ehci:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-ehci.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb2:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb2.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-printer:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-printer.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-storage:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-storage.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-storage-extras:
 * 	kernel (= 4.9.133-1-8dd2bdf5dc3b891a36c312a315a4a1cb) * 
 * opkg_install_cmd: Cannot install package kmod-usb-storage-extras.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/lixiao/lede/lede'
package/Makefile:104: recipe for target '/home/lixiao/lede/lede/staging_dir/target-mips_24kc_musl/stamp/.package_install' failed
make[1]: *** [/home/lixiao/lede/lede/staging_dir/target-mips_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/lixiao/lede/lede'
/home/lixiao/lede/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by LGA1150** [comment]
make clean 后再试

**Comment by Lancenas** [comment]
L更新后，今天同步更新后，编译正常无误了
