### ISSUE TITLE
编译package：perf、xr_usb_serial_common 失败

### ISSUE THREAD

**Issue by MedyMa** [coolsnowwolf/lede#6880]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译package：perf、xr_usb_serial_common 失败
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
A：
### (2) 路由器型号和固件版本
A：
### (3) 详细日志
A：
![BUG](https://user-images.githubusercontent.com/75345465/119423593-3204ef80-bd36-11eb-8057-d421df66507c.png)

**Comment by Dimitri2020007** [comment]
遇到相同的问题 +1
