### ISSUE TITLE
bash: x86_64-openwrt-linux-musl-gcc: command not found  

### ISSUE THREAD

**Issue by sayakaextra** [coolsnowwolf/lede#6891]
Q：是否搜索了issue (使用 "x" 选择)
* [√ ] 没有类似的issue

## 2. 详细叙述
首次编译
执行make -j8 download V=s后出现提示
重试很多次make -j8 download V=s
依然会跳出这些提示
会不会对编译造成影响
请求帮助

### (1) 具体问题

A：
![Screenshot 2021-05-27 141208](https://user-images.githubusercontent.com/72708553/119775419-25c79080-bef6-11eb-8949-b6a31c4beeec.png)
![Screenshot 2021-05-27 141238](https://user-images.githubusercontent.com/72708553/119775424-27915400-bef6-11eb-99df-d94863fc6a0d.png)

### (2) 路由器型号和固件版本

A：
X86

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
没有，忽略即可…
