### ISSUE TITLE
 make: *** [world] Error 2  帮助请求

### ISSUE THREAD

**Issue by sayakaextra** [coolsnowwolf/lede#6892]
Q：是否搜索了issue (使用 "x" 选择)
* [ √] 没有类似的issue

## 2. 详细叙述
首次编译出错；
插件选用：
LuCI ---> Applications ---> luci-app-hd-idle
LuCI ---> Applications ---> luci-app-samba
LuCI ---> Applications ---> luci-app-aria2
LuCI ---> Applications ---> luci-app-sfe Turbo ACC
LuCI ---> Applications ---> luci-app-transmission
LuCI ---> Applications ---> luci-app-webadmin
LuCI ---> Applications ---> luci-qbittorrent
LuCI ---> Applications ---> luci-filetransfer
LuCI ---> Applications ---> luci-app-ttyd

### (1) 具体问题

A：Makefile:502: recipe for target '/home/ki/lede/build_dir/hostpkg/boost_1_73_0/.built' failed
make[3]: *** [/home/ki/lede/build_dir/hostpkg/boost_1_73_0/.built] Error 1
make[3]: Leaving directory '/home/ki/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#107.37#127.96#108.76
package/Makefile:111: recipe for target 'package/feeds/packages/boost/host/compile' failed
make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
make[2]: Leaving directory '/home/ki/lede'
package/Makefile:107: recipe for target '/home/ki/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/ki/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ki/lede'
/home/ki/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：
boost-install.generate-cmake-config-version- bin.v2/libs/headers/build/install/boost_headers-config-version.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/include/boost/fusion/container/list/detail/cpp03/preprocessed/list10_fwd.hpp
common.copy /home/ki/lede/staging_dir/hostpkg/include/boost/fusion/container/list/detail/cpp03/preprocessed/list10.hpp
common.copy /home/ki/lede/staging_dir/hostpkg/include/boost/fusion/container/list/detail/cpp03/preprocessed/list.hpp
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_headers-1.73.0/boost_headers-config.cmake
boost-install.generate-cmake-config- bin.v2/libs/program_options/build/install/boost_program_options-config.cmake
boost-install.generate-cmake-config- bin.v2/libs/filesystem/build/install/boost_filesystem-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/program_options/build/install/boost_program_options-config-version.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_filesystem-1.73.0/boost_filesystem-config.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_program_options-1.73.0/boost_program_options-config-version.cmake
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/codecvt_error_category.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/exception.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/directory.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/path.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/operations.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/config_file.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/positional_options.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/utf8_codecvt_facet.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/convert.o
In file included from libs/program_options/src/convert.cpp:22:0:
./boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/options_description.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/cmdline.o
In file included from libs/program_options/src/cmdline.cpp:18:0:
./boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/winmain.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/variables_map.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/path_traits.o
boost-install.generate-cmake-config- bin.v2/libs/regex/build/install/boost_regex-config.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_regex-1.73.0/boost_regex-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/regex/build/install/boost_regex-config-version.cmake
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/windows_file_codecvt.o
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_regex-1.73.0/boost_regex-config-version.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_program_options-1.73.0/boost_program_options-config.cmake
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/utf8_codecvt_facet.o
...on 15500th target...
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/split.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/portability.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/cpp_regex_traits.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/c_regex_traits.o
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/unique_path.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/value_semantic.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/icu.o
gcc.compile.c++ bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/parsers.o
In file included from libs/program_options/src/parsers.cpp:19:0:
./boost/bind.hpp:41:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
 )
 ^
gcc.link.dll bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/libboost_filesystem.so.1.73.0
common.copy /home/ki/lede/staging_dir/hostpkg/lib/libboost_filesystem.so.1.73.0
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_filesystem.so
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_filesystem.so.1
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_filesystem.so.1.73
boost-install.generate-cmake-variant- bin.v2/libs/filesystem/build/gcc-7/release/threading-multi/visibility-hidden/libboost_filesystem-variant-shared.cmake
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/regex_debug.o
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_filesystem-1.73.0/libboost_filesystem-variant-shared.cmake
gcc.link.dll bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/libboost_program_options.so.1.73.0
common.copy /home/ki/lede/staging_dir/hostpkg/lib/libboost_program_options.so.1.73.0
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_program_options.so
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_program_options.so.1
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/regex_raw_buffer.o
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_program_options.so.1.73
boost-install.generate-cmake-variant- bin.v2/libs/program_options/build/gcc-7/release/threading-multi/visibility-hidden/libboost_program_options-variant-shared.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_program_options-1.73.0/libboost_program_options-variant-shared.cmake
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/fileiter.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/w32_regex_traits.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/static_mutex.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/regex_traits_defaults.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/regex.o
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_headers-1.73.0/boost_headers-config-version.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/filesystem/build/install/boost_filesystem-config-version.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_filesystem-1.73.0/boost_filesystem-config-version.cmake
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/usinstances.o
boost-install.generate-cmake-config- bin.v2/libs/system/build/install/boost_system-config.cmake
gcc.compile.c++ bin.v2/libs/system/build/gcc-7/release/threading-multi/visibility-hidden/error_code.o
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_system-1.73.0/boost_system-config.cmake
boost-install.generate-cmake-config-version- bin.v2/libs/system/build/install/boost_system-config-version.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_system-1.73.0/boost_system-config-version.cmake
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/wc_regex_traits.o
gcc.link.dll bin.v2/libs/system/build/gcc-7/release/threading-multi/visibility-hidden/libboost_system.so.1.73.0
boost-install.generate-cmake-variant- bin.v2/libs/system/build/gcc-7/release/threading-multi/visibility-hidden/libboost_system-variant-shared.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/libboost_system.so.1.73.0
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_system.so
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_system-1.73.0/libboost_system-variant-shared.cmake
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_system.so.1
gcc.compile.asm bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/asm/make_x86_64_sysv_elf_gas.o
gcc.compile.asm bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/asm/jump_x86_64_sysv_elf_gas.o
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_system.so.1.73
gcc.compile.asm bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/asm/ontop_x86_64_sysv_elf_gas.o
gcc.compile.c++ bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/posix/stack_traits.o
gcc.archive bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/libboost_context.a
boost-install.generate-cmake-variant- bin.v2/libs/context/build/gcc-7/release/link-static/threading-multi/visibility-hidden/libboost_context-variant-static.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/libboost_context.a
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_context-1.73.0/libboost_context-variant-static.cmake
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/posix_api.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/wide_posix_api.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/cregex.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/instances.o
gcc.compile.c++ bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/winstances.o
gcc.link.dll bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/libboost_regex.so.1.73.0
boost-install.generate-cmake-variant- bin.v2/libs/regex/build/gcc-7/release/threading-multi/visibility-hidden/libboost_regex-variant-shared.cmake
common.copy /home/ki/lede/staging_dir/hostpkg/lib/libboost_regex.so.1.73.0
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_regex.so
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_regex.so.1
ln-UNIX /home/ki/lede/staging_dir/hostpkg/lib/libboost_regex.so.1.73
common.copy /home/ki/lede/staging_dir/hostpkg/lib/cmake/boost_regex-1.73.0/libboost_regex-variant-shared.cmake
...failed updating 1 target...
...updated 15565 targets...
Makefile:502: recipe for target '/home/ki/lede/build_dir/hostpkg/boost_1_73_0/.built' failed
make[3]: *** [/home/ki/lede/build_dir/hostpkg/boost_1_73_0/.built] Error 1
make[3]: Leaving directory '/home/ki/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#107.37#127.96#108.76
package/Makefile:111: recipe for target 'package/feeds/packages/boost/host/compile' failed
make[2]: *** [package/feeds/packages/boost/host/compile] Error 2
make[2]: Leaving directory '/home/ki/lede'
package/Makefile:107: recipe for target '/home/ki/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/ki/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ki/lede'
/home/ki/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by galaxyskyknight** [comment]
很简单，第一次不要用多线程编译，切记！后续增量编译，多线程编译也是玄学（猜测原因可能是多线程是异步编译，导致编译过程中多个线程的编译输出物有相互依赖的地方不能满足先后时序），可能出错，可能不出错，出错了再跑一次也可能就过了。多次躺坑的经验！
