### ISSUE TITLE
绕过大陆IP成了全局模式,GFW模式不稳定有时候不能上境外

### ISSUE THREAD

**Issue by TerryWang159** [coolsnowwolf/lede#6894]
最近发现问题如题, 绕过大陆IP成了全局模式,GFW模式不稳定有时候不能上境外. 就最近出现这问题,以前正常的 .

版本: : Main node:Xray 1.4.2 (Xray, Penetrates Everything.) OpenWrt (go1.16.3 linux/amd64)

**Comment by galaxyskyknight** [comment]
你pdns配置的dns问题，多半

**Comment by TerryWang159** [comment]
> dns
如何理解?可否详细解答一下,多谢了

**Comment by TerryWang159** [comment]
> 
> 
> 你pdns配置的dns问题，多半
SSP的DNS解析方式我是本地的5335转到上游SmartDNS  8.8.8.8 1.1.1.1 1.0.0.1

**Comment by galaxyskyknight** [comment]
不要搞什么smartdns这些玩意，那都是给小白挖坑的，实际没卵用。就用下面这个挺好
![image](https://user-images.githubusercontent.com/66289873/119927538-2f133480-bfac-11eb-9f9a-c70ab44a9f30.png)
