### ISSUE TITLE
编译失败求帮助 

### ISSUE THREAD

**Issue by sayakaextra** [coolsnowwolf/lede#6897]
Q：是否搜索了issue (使用 "x" 选择)
* [√ ] 没有类似的issue

### (1) 具体问题

A：
编译失败
首次编译 
单线程编译；
失败了。

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/72708553/120003637-8515c580-c008-11eb-806a-aac34684bf4f.png)

**Comment by Boos4721** [comment]
`df -h`
没空间了
