### ISSUE TITLE
网络中没有交换机选项，怎么解决

### ISSUE THREAD

**Issue by dukmonki** [coolsnowwolf/lede#6909]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
不是路由器哪来的交换机

**Comment by dukmonki** [comment]
就是以前接口下有交换机选项，可以调节每个接口，设置VLAN。现在没有这个选项了。

**Comment by starxu1971** [comment]
X86没这个选项，直接新建接口就行具体自己搜索
