### ISSUE TITLE
coremark 找不到了？

### ISSUE THREAD

**Issue by zhaocz086** [coolsnowwolf/lede#691]
coremark 是被取消了吗？

**Comment by LGA1150** [comment]
你要找的是不是： connmark

**Comment by zhaocz086** [comment]
commit 29c8928eead91092a13bb0dc58c753b703601e69
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Fri Oct 19 13:26:06 2018 +0800

    re-add luci-app-usb printer

...skipping...
    Bu Fu Pao Ge Fen? CoreMark(r) is an industry-standard benchmark that measures the performance of OpenWrt router
