### ISSUE TITLE
网易云音乐解锁用不了？播放总是提示加载失败

### ISSUE THREAD

**Issue by keeno1982** [coolsnowwolf/lede#6910]
拉的是最新的代码编译的，模式是nodejs，PC客户端代理检测是正常的，点击播放音乐却总是提示加载失败，只有个别歌曲可以播放，怎么破？

**Comment by EnnawYang** [comment]
nodejs的上游已经不维护了

**Comment by keeno1982** [comment]
@EnnawYang 感谢，我试试。这个改动只是nodejs，go的仍然还是不可用吧？

**Comment by EnnawYang** [comment]
> @EnnawYang 感谢，我试试。这个改动只是nodejs，go的仍然还是不可用吧？

go版本不清楚，我没用过

**Comment by keeno1982** [comment]
好，谢谢

**Comment by XiaoliChan** [comment]
Golang version now is unavailable.
