### ISSUE TITLE
求助，UU游戏加速器用不了

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [coolsnowwolf/lede#6911]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
A：运行在旁路由模式下，手机APP绑定失败

### (2) 路由器型号和固件版本
A：树莓派4B ; OpenWrt R21.6.1 / LuCI Master (git-21.114.56541-974fb04)

### (3) 详细日志
A：
![1](https://user-images.githubusercontent.com/38343280/120146716-1ad36f80-c218-11eb-9c1c-15418397d50d.jpg)
![2](https://user-images.githubusercontent.com/38343280/120146727-1dce6000-c218-11eb-8481-ba9247f24370.png)

**Comment by EnnawYang** [comment]
划重点 **旁路由**

**Comment by OldCoding** [comment]
好像从来没有说过支持旁路由的
