### ISSUE TITLE
求助，如何把官方的/feeds/luci/protocols的协议放在L大的固件内？

### ISSUE THREAD

**Issue by mouselcz** [coolsnowwolf/lede#6912]
试过把整个protocols拷贝过去，或者用src-git的试在feeds.conf.default 里面把原luci替换，在编译时会报错，已试过update命令找不到菜单，在menconfig找不到选项。

**Comment by AmadeusGhost** [comment]
官方 luci 那些包很多都改用 js 重写了，就算你编译进去了也用不了。

**Comment by mouselcz** [comment]
> 官方那些包很多都改用js改了，那你也用不了了。

可惜，还想在L大的基础下用到gre这个协议。
