### ISSUE TITLE
芯片支持AES，但编译时不添加添加AES支持是否影响aes性能

### ISSUE THREAD

**Issue by DH-FU** [coolsnowwolf/lede#6919]
RK3399芯片问题
编译固件make kernel_menuconfig中不添加AES支持，对芯片本身支持的aes性能是否产生影响？

**Comment by AmadeusGhost** [comment]
没有，一般存在硬件加密引擎驱动才需要勾选上。

**Comment by suizhenmin** [comment]
请问 aes 支持选项在 kernel_menuconfig 下的哪个选项里
