### ISSUE TITLE
IPV6问题

### ISSUE THREAD

**Issue by lyin888** [coolsnowwolf/lede#692]
现在运营商释放了IPV6，路由拨号可以同时获得IPV4和IPV6，安装odhcpd和odhcp6后，必须在防火墙自定义规则里添加一句 ip6tables -t nat -A POSTROUTING -o eth0.2 -j MASQUERADE   规则，并重启防火墙后客户端才可以获得IPV6地址，请问是缺少依赖包还是内核不同或是openwrt IPV6 天残就这样。

PS 前段时间（大约八月底吧）水星4530 编译出的固件就不需要以上规则就可以获取到IPV6。

还有一个问题  主页已分配的 DHCPv6 租约 为何只显示PC的链接，手机获取到IPV6为何没有显示

![fireshot capture 3 - openwrt - - luci - http___192 168 1 1_cgi-bin_luci_admin_status_overview](https://user-images.githubusercontent.com/3062241/47086253-904ac700-d24b-11e8-954c-9c9fe6ffee68.png)

![fireshot capture 4 - ipv6 - https___ipv6 test-ipv6 com_](https://user-images.githubusercontent.com/3062241/47086476-28e14700-d24c-11e8-9279-52f20e8bc3e7.png)

**Comment by dongjuanyong** [comment]
第一个问题估计是防火墙配置的问题，没看到也不好判断
安卓手机只支持RA，不支持DHCPv6，所以只有自动配置的v6地址，不会从DHCP服务器租地址的
自动配置的v6地址可以从 状态-路由 最下面看到

**Comment by maxxwall** [comment]
PHICOMM K3 內核4.14 
使用默认配置就可以使用，没有你所说的问题

**Comment by LGA1150** [comment]
是否用了mwan3

**Comment by lyin888** [comment]
> 是否用了mwan3

编译了mwan3但未使用

**Comment by shenzt68** [comment]
看来ipv6与mwan3冲突，我也遇到了

**Comment by lyin888** [comment]
去掉mwan3重新编译后，客户端正常获取到IPV6地址了，感谢各位的回答，感谢lean的源码，谢谢！

**Comment by sqliuchang** [comment]
原来是因为mwan3冲突啊，终于明白了，我也是一直dhcpv6租约分配为空
想问一下那个iptable规则是什么意思，添加之后确实有效

**Comment by sqliuchang** [comment]
> iptables规则 是google出来的，什么意思我也不知道

好的，多谢啦，确实有效
