### ISSUE TITLE
编译失败，不知道是哪里的原因，求大神赐教

### ISSUE THREAD

**Issue by yinyouzhu** [coolsnowwolf/lede#6923]
Q：是否搜索了issue (使用 "x" 选择)
* [✅ ] 没有类似的issue
有类似的issue，不过都没有看到什么解决的办法

## 2. 详细叙述
按照教程中的编译步骤一步步的进行，但是最后总是会报错，尝试过取消一些app，但是问题依旧，这个问题已经持续了几个月 
### (1) 具体问题

A：编译失败，屡次尝试都失败。

### (2) 路由器型号和固件版本
A： 软路由 x86 3865u 

### (3) 详细日志

A：
x86_64-openwrt-linux-musl-gcc-ar cr src/libuClibc++.a src/algorithm.o src/iomanip.o src/numeric.o src/map.o src/bitset.o src/eh_alloc.o src/limits.o src/char_traits.o src/stack.o src/deque.o src/stdexcept.o src/queue.o src/valarray.o src/streambuf.o src/del_op.o src/complex.o src/del_opv.o src/utility.o src/vector.o src/new_op.o src/new_opnt.o src/del_opvnt.o src/del_opnt.o src/set.o src/new_opv.o src/iostream.o src/associative_base.o src/del_opvs.o src/new_handler.o src/func_exception.o src/new_opvnt.o src/fstream.o src/exception.o src/ostream.o src/locale.o src/list.o src/ios.o src/del_ops.o src/eh_globals.o src/string.o src/sstream.o src/iterator.o src/istream.o src/abi/abi.o array_type_info.o atexit_arm.o atexit_thread.o bad_alloc.o bad_array_length.o bad_array_new.o bad_cast.o bad_typeid.o class_type_info.o dyncast.o eh_arm.o eh_aux_runtime.o eh_call.o eh_catch.o eh_exception.o eh_personality.o eh_ptr.o eh_term_handler.o eh_terminate.o eh_tm.o eh_throw.o eh_type.o eh_unex_handler.o enum_type_info.o function_type_info.o fundamental_type_info.o guard.o guard_error.o hash_bytes.o nested_exception.o pbase_type_info.o pmem_type_info.o pointer_type_info.o si_class_type_info.o tinfo.o tinfo2.o vec.o vmi_class_type_info.o vterminate.o cp-demangle.o
/home/xiong/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.4.0/../../../../x86_64-openwrt-linux-musl/bin/ar: array_type_info.o: No such file or directory
src/Makefile.in:44: recipe for target 'src/libuClibc++.a' failed
make[4]: *** [src/libuClibc++.a] Error 1
make[4]: Leaving directory '/home/xiong/lede/build_dir/target-x86_64_musl/uClibc++-0.2.5'
Makefile:97: recipe for target '/home/xiong/lede/build_dir/target-x86_64_musl/uClibc++-0.2.5/.built' failed
make[3]: *** [/home/xiong/lede/build_dir/target-x86_64_musl/uClibc++-0.2.5/.built] Error 2
make[3]: Leaving directory '/home/xiong/lede/package/libs/uclibc++'
time: package/libs/uclibc++/compile#0.06#0.02#0.17
package/Makefile:111: recipe for target 'package/libs/uclibc++/compile' failed
make[2]: *** [package/libs/uclibc++/compile] Error 2
make[2]: Leaving directory '/home/xiong/lede'
package/Makefile:107: recipe for target '/home/xiong/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/xiong/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xiong/lede'
/home/xiong/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Boos4721** [comment]
/home/xiong/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/gcc/x86_64-openwrt-linux-musl/8.4.0/../../../../x86_64-openwrt-linux-musl/bin/ar: array_type_info.o: No such file or directory
