### ISSUE TITLE
端口转发的奇怪问题

### ISSUE THREAD

**Issue by doumeki** [coolsnowwolf/lede#6925]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

## 2. 详细叙述
服务器上开了个端口比如8000. 路由设置端口转发8000到lan的8000, 开启NAT回流。这时选择的端口是WAN 到 LAN。
同样再建一个端口转发规则是8000：8000， LAN到LAN。

以上两个规则设置后，从其它局域网机器上访问 路由IP：8000 以及外网访问8000的地址都没有问题。但是服务器本机上却不行。 

因为这个服务器是虚拟机，在HOST机上，都不能访问 路由IP:端口号。但是跳出这个服务器可以访问。

这里说的路由IP包含WAN口和br-lan的IP。

以上简单的说就是 ：在被端口映射的机器上不能访问路由：ip，局域网其它机器以及外网可以。 当然，在任意机器上使用 服务IP:端口 是没有任何问题的。

看有哪位大神解释下为什么？ 

------------------------------------------------------
看来不会有大神来解释， 关了。

**Comment by OldCoding** [comment]
不明白你们为什么在内网下也要搞端口转发，直接内网设备的IP+端口访问是会少块肉嘛
