### ISSUE TITLE
RM AC2100 开启IPV6 relay后，无线自动关闭，且无法使用IPV6 relay

### ISSUE THREAD

**Issue by CKopoer** [coolsnowwolf/lede#6928]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
RM AC2100 开启IPV6 relay后，无线自动关闭，且无法使用IPV6 relay

就算网线连接到后台，也无法正常使用IPV6 relay
Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：LAN口ipv6设置，dhcpv6、ndp、ra都选择relay，保存并应用后无线信号自动消失。
如果使用vim 编辑/etc/config/dhcp，可以使得无线正常使用，但是IPV6 relay依然不能用

### (2) 路由器型号和固件版本

A：目前最新版本（在以前的版本上也有这个问题，官方源码没有无线自动关闭的问题，但是也不能用ipv6 relay） RedMi AC2100

**Comment by EnnawYang** [comment]
因为使用了闭源驱动，接口保存应用之前请现在接口设置处加上无线接口，或者保存应用之后手动重启下无线
