### ISSUE TITLE
概览页面“网口状态”没有了

### ISSUE THREAD

**Issue by swq93** [coolsnowwolf/lede#6934]
* [x ] 没有类似的issue

### (1) 具体问题

A：路由器概览页面缺少“网口状态”显示，以前都有哪个接口速率是多少，我一共是 6个接口

### (2) 路由器型号和固件版本

A：X86 	OpenWrt R21.6.1 / LuCI Master (git-21.114.56541-974fb04)

**Comment by shelken** [comment]
同问，为什么没有呢？
