### ISSUE TITLE
realtek-r8152编译无法通过

### ISSUE THREAD

**Issue by inbogota** [coolsnowwolf/lede#6946]
错误源码：https://paste.ubuntu.com/p/GNqtfKPxHV/

4.19内核，编译时realtek-r8152失败，比对了距离上一次成功编译的改动，发现只有这一处改动 < https://github.com/coolsnowwolf/lede/commit/1024f0ec23f63d2b404b708fab61ff8d3826db9c >

望拨冗修复

**Comment by SuperNG6** [comment]
同样问题，请求修复
