### ISSUE TITLE
Turbo ACC 中 SFE Fast Path 加速 bug

### ISSUE THREAD

**Issue by suizhenmin** [coolsnowwolf/lede#6949]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述

Turbo ACC 组建的兼容问题

### (1) 具体问题

开启 Turbo ACC 中 SFE Fast Path 加速 后，mac 上的 parallels client 软件在默认设置下无法连接远程桌面，需要将图形设置从自适应修改成基本功能，未更换软路由时是不用做这种修改。 关闭 SFE Fast Path 后可以正常连接。

parallels client mac上替代微软远程桌面的一款非常好用的软件。

更换 Turbo ACC 版本使用 FLOW 加速 就正常了。

![1](https://user-images.githubusercontent.com/2957364/121278678-b4300f00-c905-11eb-84cb-8561de059f77.png)

A：

### (2) 路由器型号和固件版本

j4125 2.5G 软路由

OpenWrt R21.6.1 / LuCI Master (git-21.114.56541-974fb04)

### (3) 详细日志

A：后台无日志

**Comment by laaArmy** [comment]
我也发现了
