### ISSUE TITLE
21.02编译好后点击网络-接口报错,望大神帮忙看看是啥问题 

### ISSUE THREAD

**Issue by trombonist852** [coolsnowwolf/lede#6950]
x86软路由,21.02,点继续之后还是会跳,这个应该咋解决?望大神们不吝赐教,感谢!
![IMG_1742](https://user-images.githubusercontent.com/13253090/121298692-df772600-c926-11eb-893d-ce5e7771e133.JPG)

**Comment by EnnawYang** [comment]
为什么不问问官方呢？

**Comment by trombonist852** [comment]
> 为什么不问问官方呢？
在这里问比较亲切 哈哈

**Comment by EnnawYang** [comment]
> > 为什么不问问官方呢？
> > 在这里问比较亲切 哈哈

可这里是18.06啊

**Comment by hcym** [comment]
多了个设备设置，多点几次，或者参考正常工作的配置自己写了，应该没问题

**Comment by trombonist852** [comment]
> > > 为什么不问问官方呢？
> > > 在这里问比较亲切 哈哈
> 
> 可这里是18.06啊

期待有好心的大佬能帮忙看看呢 哈哈  官方issue我去看过了 也有好多反应这个问题的,好像是都在等修复

**Comment by hcym** [comment]
和1907比较多了设备管理，master分支最多跳三四次吧，21.02最多二次
我是记下来直接写成单臂路由，即插即用
x86和armv8都OK，2102肯定绝对完全可以，master分支可能是拼人品

**Comment by trombonist852** [comment]
hcym ***@***.***>于2021年6月9日 周三下午4:38写道：

**Comment by Neverends4** [comment]
21.02对network语法有修改，然后正式使用DSA做某些设备的网络架构，烦死了，VLAN之前用swconfig好好的现在整不出来了
另外21.02rc2出来了，Luci对从swconfig到DSA脚本的升级有改动，你可以试试
另另外…………确实不应该在这里报官方op的issue吧……ʕ⊙ᴥ⊙ʔ

**Comment by trombonist852** [comment]
Neverends ***@***.***>于2021年6月10日 周四下午11:35写道：
