### ISSUE TITLE
如何编译非snapshot版本

### ISSUE THREAD

**Issue by fzxvvc** [coolsnowwolf/lede#6951]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：使用Action-Openwrt在线编译出的固件没有web界面。进入软路由洁面发现编译的版本是snapshot版本，查询资料和自己的设置发现snapshot版本默认不带luci。请问如何编译正常非snapshot版本？

### (2) 路由器型号和固件版本

A：J3455软路由

### (3) 详细日志

A：无

**Comment by EnnawYang** [comment]
本库源码默认有勾选luci

**Comment by fzxvvc** [comment]
> 本库源码默认有勾选luci

了解，但是我没有更改make menuconfig里面的任何设置，依然是snapshot版本，很迷惑啊

**Comment by Neverends4** [comment]
你是不是没搞清楚，这库默认就是snapshot。库里有几个固定日期tag，不过不清楚库主的意图，不能断定是不是稳定版
你是要稳定版的话就去openwrt官方库，编译时选择tag到稳定版即可。

**Comment by coolsnowwolf** [comment]
https://github.com/coolsnowwolf/openwrt 稳定版
