### ISSUE TITLE
luci-app-usb-printer插件语法错误反馈

### ISSUE THREAD

**Issue by HiColinn** [coolsnowwolf/lede#6954]
https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-usb-printer/root/usr/bin/usb_printer_hotplug
这个文件下的第39行,$DEVICES没有用双引号包裹,导致多个USB打印机存在的情况下,p910nd永远绑定/dev/usb/lp0,正常应该是绑定
/dev/usb/lp1,/dev/usb/lp2的,经过测试,加上双引号就好了,希望L大在仓库里改一下,以后大家就不用自己手动改了.
(我已经从群了消失第99999次,...L大加油)
![20210609211519](https://user-images.githubusercontent.com/65964332/121361776-2b968a80-c968-11eb-8d3e-a76083cfd21f.jpg)

**Comment by coolsnowwolf** [comment]
还真是

**Comment by HiColinn** [comment]
> 还真是

L大,我永远找不到家....换了好几个群了,难受

**Comment by mjyhj** [comment]
> > 还真是
> 
> L大,我永远找不到家....换了好几个群了,难受

https://t.me/joinchat/JhKgAA6Hx1uiihA7RaTW1w
TG群永不迷路
