### ISSUE TITLE
解决了rock pi 4B 编译后刷入tf卡无法引导系统的问题

### ISSUE THREAD

**Issue by DH-FU** [coolsnowwolf/lede#6956]
![无标题](https://user-images.githubusercontent.com/76506087/121378723-06107d80-c976-11eb-9fe5-8acf766c6927.jpg)

**Comment by hxlls** [comment]
这个是你写卡的软件问题把，R2S实测没问题，多换几个烧录软件有惊喜

**Comment by adamgonglj** [comment]
我都是直接用.gz的文件直接写的。
