### ISSUE TITLE
关于git编译luci-app-eqos插件文件无执行权限问题咨询下各位大佬

### ISSUE THREAD

**Issue by MapesxGM** [coolsnowwolf/lede#6959]
用最新源（6月10号）码编译R4S固件git clone luci-app-eqos源码编译到固件中无法运行生效（无任何提示），经检查为以下几个文件无执行权限：
/etc/rc.d/S50eqos
/etc/init.d/eqos
/usr/sbin/eqos
更改文件权限后可正常启用并生效，
编译coolsnowwolf/lede中的luci-app-nft-qos也遇到过此问题。
请问下各位大佬有没有遇到过类似情况，是什么问题引起的？该怎么解决？
谢谢！

**Comment by swxk521** [comment]
https://github.com/swxk521/luci-app-eqos
试试我这个，我这边正常，要是不能用的话那就当我没说。

**Comment by MapesxGM** [comment]
> https://github.com/swxk521/luci-app-eqos
> 试试我这个，我这边正常，要是不能用的话那就当我没说。

用你这个版本编译正常，谢谢！
