### ISSUE TITLE
流量被劫持

### ISSUE THREAD

**Issue by ydys168** [coolsnowwolf/lede#6964]
今天收到联通通知，宽带流量异常。然后给发了张图片，这是流量被劫持了吗？联通让我换路由器，不然封我宽带账号。。

![c8e61e899d0562b9b64d2193a4618ac](https://user-images.githubusercontent.com/68474671/121679068-8952e000-caea-11eb-8960-ef9937309445.jpg)

固件版本 | OpenWrt R21.4.18 / LuCI Master (git-21.114.56541-974fb04)

内核版本 5.4.117

**Comment by galaxyskyknight** [comment]
这和这里有什么关系？你是来砸场子的吧…
