### ISSUE TITLE
缓存错误

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6974]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
cache directory                     /home/qqsir/lede/.ccache
primary config                      /home/qqsir/lede/.ccache/ccache.conf
secondary config (readonly)         /home/qqsir/lede/staging_dir/host/etc/ccache.conf
stats updated                       Mon Jun 14 13:57:17 2021
cache hit (direct)                  1827
cache hit (preprocessed)            1556
cache miss                         31172
cache hit rate                      9.79 %
called for link                     1268
called for preprocessing            2785
multiple source files                 25
compiler produced stdout               2
compiler produced empty output       116
compile failed                      2403
ccache internal error                 32
preprocessor error                   750
bad compiler arguments               284
unsupported source language            8
autoconf compile/link               6049
unsupported compiler option           47
unsupported code directive             6
output to stdout                       4
no input file                       1238
cleanups performed                     0
files in cache                     62008
cache size                         781.7 MB
max cache size                       5.0 GB
make[1]: Leaving directory '/home/qqsir/lede'

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by GWONGJYULEI** [comment]
+1。重新开始编译也不行
