### ISSUE TITLE
Kernel 5.10 build failed

### ISSUE THREAD

**Issue by XiaoliChan** [coolsnowwolf/lede#6976]
Kernel 5.10 build failed on target x86, here is the error screenshot:
![image](https://user-images.githubusercontent.com/30458572/121907599-c9ba9400-cd5e-11eb-8362-c84ae947bdac.png)

**Comment by jashok2** [comment]
同遇到错误

**Comment by galaxyskyknight** [comment]
一样。
![image](https://user-images.githubusercontent.com/66289873/122087244-196c8e80-ce37-11eb-9095-1cd0738d1c5b.png)

**Comment by galaxyskyknight** [comment]
麻烦@coolsnowwolf 大佬看看是什么原因，如何修复？

**Comment by XiaoliChan** [comment]
Fixed.
