### ISSUE TITLE
不算问题，求咨询，编译的时候把python和python-pip编译进去

### ISSUE THREAD

**Issue by zhouxiaolong920** [coolsnowwolf/lede#6980]
1. 如何编译的时候。把python和python-pip编译进系统里面。

**Comment by yinzhefuyun** [comment]
在选固件的时候 按“/”还是“\”搜索，找到你要的，然后按搜索结果前面的数字 ，例如（1），你就按键盘1 定位到那里选中你要的就好了

**Comment by zhouxiaolong920** [comment]
感谢，我看到了。在devploy language那里有python，里面有pip,仔细找，我看到了，感谢楼上
