### ISSUE TITLE
请教，刚用了ssrp+ 的trojan，必须修改本地dns才能完全正常（有些站打不开）

### ISSUE THREAD

**Issue by flsxc** [coolsnowwolf/lede#6983]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：用了ssrp+ 的trojan，很好用，速度也很快，youtube飞快；但是有个问题，有些网站打不开；不过我把电脑本地的dns加一条8.8.8.8后，就统统正常了，很是奇怪；本地删除8.8.8.8后，youtube,google还是正常，有些其他站就打不开。

### (2) 路由器型号和固件版本

A：x86的机器刷的openwrt

### (3) 详细日志

A：

**Comment by luodaoyi** [comment]
我也遇到这个问题了 老哥怎么解决的
