### ISSUE TITLE
有很多重复的软件包,

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#6984]
WARNING: Not overriding core package 'frp'; use -f to force
WARNING: Not overriding core package 'kcptun'; use -f to force
WARNING: Not overriding core package 'libcap'; use -f to force
WARNING: Not overriding core package 'musl-fts'; use -f to force
WARNING: Not overriding core package 'nft-qos'; use -f to force
WARNING: Not overriding core package 'proxychains-ng'; use -f to force
WARNING: Not overriding core package 'samba4'; use -f to force
WARNING: Not overriding core package 'softethervpn5'; use -f to force
WARNING: Not overriding core package 'wget'; use -f to force

zz@zz-virtual-machine:~/lede$ find -name wget
./staging_dir/host/bin/wget
./package/feeds/packages/wget
./package/lean/wget
./feeds/packages/net/wget

应该删除哪一个?或者说哪一个是正常维护的?

**Comment by EnnawYang** [comment]
`package/lean/wget`
`feeds/packages/net/wget`
这两个版本一样，不是强迫症的话不用删，其他两个都是软连接，不要动
