### ISSUE TITLE
lvm2编译出错

### ISSUE THREAD

**Issue by baby195lxl** [coolsnowwolf/lede#6988]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：lvm2编译出错，似乎和docker版本更新有关系

### (2) 路由器型号和固件版本

A：N1盒子

### (3) 详细日志

A：![image](https://user-images.githubusercontent.com/48685934/122004812-73456800-cde7-11eb-986e-60873587773e.png)

**Comment by wqzxhpx1988** [comment]
云编译，我也是这个错误lvm2错误

**Comment by baby195lxl** [comment]
> 云编译，我也是这个错误lvm2错误

我查看了一个以前的issue，似乎是docker版本更新的依赖问题

**Comment by wqzxhpx1988** [comment]
你好，请问这个问题lean大佬修复了吗。昨天没有编译

**Comment by baby195lxl** [comment]
> 你好，请问这个问题lean大佬修复了吗。昨天没有编译

我编译还是有点问题，但是LVM2似乎没问题了，是其他地方的错误

**Comment by wqzxhpx1988** [comment]
那我中午编译再试试
