### ISSUE TITLE
is:issue x86关于内核日志。打印  overlayfs: filesystem on '/opt/check-overylayfs-suppport979420607/upper' not supported as uupperdir  

### ISSUE THREAD

**Issue by zhouxiaolong920** [coolsnowwolf/lede#6989]
编译docker-ce进镜像之后
启动。就会有这个warn提示，
我看/opt是默认目录 
docker 配置文件  /etc/docker/daemon.json

我修改过/opt目录 。修改到其它盘的 目录 。也不行。重启还是有这个warning.

docker正常，无论pull还是run
就是有这个提示，看着难受。。。求各位，已经解决的。帮我看看

**Comment by ricksuzade-maker** [comment]
dockerd目录下的配置文件要一起改，这是一个bug，还没修复。

**Comment by zhouxiaolong920** [comment]
@ricksuzade-maker 
你知道怎么个修改吗？我可以重新编译一下。哈哈。
