### ISSUE TITLE
下载出现错误

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#6991]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

gssi@gssiserver:~/lede$ ./scripts/feeds install -a
ERROR: please fix package/network/utils/dpdk/Makefile - see logs/package/network/utils/dpdk/dump.txt for details

**Comment by 13810169** [comment]
我也出现这个错误，但是可以编译成功。
