### ISSUE TITLE
请问如何编译5.10内核啊？

### ISSUE THREAD

**Issue by xyl94k** [coolsnowwolf/lede#6993]
编译出来为啥还是5.4.124，请大佬指点

**Comment by EnnawYang** [comment]
目前为5.4 ，5.10为测试 不建议上

**Comment by xyl94k** [comment]
> 目前为5.4 ，5.10为测试 不建议上

哈哈，请问如何尝鲜一波

**Comment by EnnawYang** [comment]
https://github.com/coolsnowwolf/lede/commit/ba4b3804fa6f2c5b72189e41d9ec6e3481b5256f 已经是5.10了

**Comment by moonerick** [comment]
编译失败 显示aria2错误
