### ISSUE TITLE
重新编译各种错误啊

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#6997]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
install -d -m0755 /home/qqsir/lede/bin/packages/x86_64/helloworld
/home/qqsir/lede/staging_dir/host/bin/fakeroot /home/qqsir/lede/scripts/ipkg-build -m "" /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy /home/qqsir/lede/bin/packages/x86_64/helloworld
Packaged contents of /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy into /home/qqsir/lede/bin/packages/x86_64/helloworld/naiveproxy_91.0.4472.77-1-1_x86_64.ipk
echo "naiveproxy" >> /home/qqsir/lede/staging_dir/target-x86_64_musl/pkginfo/naiveproxy.default.install
make[3]: Leaving directory '/home/qqsir/lede/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#1484.46#81.86#454.72
make[2]: Leaving directory '/home/qqsir/lede'
make[1]: *** [package/Makefile:110: /home/qqsir/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/qqsir/lede'
make: *** [/home/qqsir/lede/include/toplevel.mk:230: world] Error 2

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
1. 日志不完整
2. naiveproxy 不应该在这提issue
