### ISSUE TITLE
error: implicit declaration of function 'gelf_getsymshndx'; did you mean 'gelf_getsym'

### ISSUE THREAD

**Issue by cntink** [coolsnowwolf/lede#6998]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译出错

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/subcmd-config.o
  LD       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/libsubcmd-in.o
  AR       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/libsubcmd.a
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/arch/x86/special.o
  MKDIR    /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/arch/x86/lib/
  GEN      /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/arch/x86/lib/inat-tables.c
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/arch/x86/decode.o
  LD       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/arch/x86/objtool-in.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/weak.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/check.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/special.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/orc_gen.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/orc_dump.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/builtin-check.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/builtin-orc.o
  CC       /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/elf.o
elf.c: In function 'read_symbols':
elf.c:407:8: error: implicit declaration of function 'gelf_getsymshndx'; did you mean 'gelf_getsym'? [-Werror=implicit-function-declaration]
  407 |   if (!gelf_getsymshndx(symtab->data, shndx_data, i, &sym->sym,
      |        ^~~~~~~~~~~~~~~~
      |        gelf_getsym
cc1: all warnings being treated as errors
make[8]: *** [/home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/build/Makefile.build:97: /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/elf.o] Error 1
make[7]: *** [Makefile:59: /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/tools/objtool/objtool-in.o] Error 2
make[6]: *** [Makefile:68: objtool] Error 2
make[5]: *** [Makefile:1947: tools/objtool] Error 2
make[5]: Leaving directory '/home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43'
make[4]: *** [Makefile:28: /home/cntink/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.43/.modules] Error 2
make[4]: Leaving directory '/home/cntink/lede/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/cntink/lede/target/linux'
time: target/linux/compile#13.24#13.69#22.23
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/cntink/lede'
make[1]: *** [target/Makefile:18: /home/cntink/lede/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/cntink/lede'
make: *** [/home/cntink/lede/include/toplevel.mk:230：world] 错误 2

**Comment by doumeki** [comment]
一样的错。

**Comment by nakes** [comment]
一样的错。

**Comment by ZGNCZMY** [comment]
同样报错

**Comment by xiao847** [comment]
一样的问题，make clean  清过了解决不了

**Comment by martin-xj** [comment]
同样报错

**Comment by OleStore** [comment]
elf.c: In function 'read_symbols':
elf.c:407:8: error: implicit declaration of function 'gelf_getsymshndx'; did you                                                                                                                                                              mean 'gelf_getsym'? [-Werror=implicit-function-declaration]
  407 |   if (!gelf_getsymshndx(symtab->data, shndx_data, i, &sym->sym,
      |        ^~~~~~~~~~~~~~~~
      |        gelf_getsym
cc1: all warnings being treated as errors
make[8]: *** [/home/bibi/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-                                                                                                                                                             5.10.43/tools/build/Makefile.build:97: /home/bibi/lede/build_dir/target-x86_64                                                                                                                                                             _musl/linux-x86_64/linux-5.10.43/tools/objtool/elf.o] Error 1
make[7]: *** [Makefile:59: /home/bibi/lede/build_dir/target-x86_64_musl/linux-                                                                                                                                                             x86_64/linux-5.10.43/tools/objtool/objtool-in.o] Error 2
make[6]: *** [Makefile:68: objtool] Error 2
make[5]: *** [Makefile:1947: tools/objtool] Error 2
make[5]: Leaving directory '/home/bibi/lede/build_dir/target-x86_64_musl/linux                                                                                                                                                             -x86_64/linux-5.10.43'
make[4]: *** [Makefile:28: /home/bibi/lede/build_dir/target-x86_64_musl/linux-                                                                                                                                                             x86_64/linux-5.10.43/.modules] Error 2
make[4]: Leaving directory '/home/bibi/lede/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/bibi/lede/target/linux'
time: target/linux/compile#35.43#11.25#80.67
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/bibi/lede'
make[1]: *** [target/Makefile:18: /home/bibi/lede/staging_dir/target-x86_64_mu                                                                                                                                                             sl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/bibi/lede'
make: *** [/home/bibi/lede/include/toplevel.mk:230: world] Error 2
bibi@wong:~/lede$

**Comment by softtip** [comment]
一样的问题，求解

**Comment by OleStore** [comment]
make clean 解决问题。。。

**Comment by chenxuan5858** [comment]
同样问题

**Comment by chenxuan5858** [comment]
内核开启SFE支持有问题感觉是

**Comment by hdm9527** [comment]
> make clean 解决问题。。。

`sed -i "s/Installed-Time: .*/Installed-Time: 1623825693/" /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/status                                                                                                      rm -rf /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/boot /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/tmp/* /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/info/*.postinst* /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/lists/* /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/var/lock/*.lock                                                                                           find /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/ -mindepth 1 -execdir touch -hcd "@1623825693" "{}" + find: The relative path 'Files/WindowsApps/TheDebianProject.DebianGNULinux_1.4.0.0_x64__76v4gfsz19hv4' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH                                                                                                            make[2]: *** [package/Makefile:73: package/install] Error 1                                                             make[2]: Leaving directory '/home/hdm/lede'                                                                             make[1]: *** [package/Makefile:111: /home/hdm/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2  make[1]: Leaving directory '/home/hdm/lede'                                                                             make: *** [/home/hdm/lede/include/toplevel.mk:230：world] 错误 2`  make clean再编译还是这个问题

**Comment by chenxuan5858** [comment]
> > make clean 解决问题。。。
> 
> sed -i "s/Installed-Time: ._/Installed-Time: 1623825693/" /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/status rm -rf /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/boot /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/tmp/_ /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/info/_.postinst_ /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/lists/* /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/var/lock/*.lock
> find /home/hdm/lede/build_dir/target-mipsel_24kc_musl/root-ramips/ -mindepth 1 -execdir touch -hcd "@1623825693" "{}" +
> find: The relative path 'Files/WindowsApps/TheDebianProject.DebianGNULinux_1.4.0.0_x64__76v4gfsz19hv4' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find. Please remove that entry from $PATH
> make[2]: *** [package/Makefile:73: package/install] Error 1
> make[2]: Leaving directory '/home/hdm/lede'
> make[1]: *** [package/Makefile:111: /home/hdm/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
> make[1]: Leaving directory '/home/hdm/lede'
> make: *** [/home/hdm/lede/include/toplevel.mk:230：world] 错误 2
> ###################################################
> make clean再编译还



一样，clean还是错误

**Comment by galaxyskyknight** [comment]
clean没用

**Comment by OleStore** [comment]
make distclean，编译通过

**Comment by hdm9527** [comment]
> make distclean，编译通过

你这命令插件都清掉了，怕不是在坑人

**Comment by OleStore** [comment]
> > make distclean，编译通过
> 
> 你这命令插件都清掉了，怕不是在坑人

这也坑人？普通clean根本不过，我自己也尝试过，索性全部清理，至少我编译过了
