### ISSUE TITLE
减少编译所用空间

### ISSUE THREAD

**Issue by shoucandanghehe** [coolsnowwolf/lede#7004]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
如何减少编译所用空间，使用actions编译，空间不足
本地编译完之后lede目录有27.7g

### (2) 路由器型号和固件版本
x86-64

### (3) 详细日志
System.IO.IOException: No space left on device

**Comment by yinzhefuyun** [comment]
actions不是有84G吗，你不够吗？

**Comment by shoucandanghehe** [comment]
> actions不是有84G吗，你不够吗？

抛去系统和自带的环境
Ubuntu18.04剩余空间22g
![image](https://user-images.githubusercontent.com/51957264/122142736-9ffa8d80-ce82-11eb-95d9-b5fbc1c1d625.png)

**Comment by shoucandanghehe** [comment]
再整理完其他的东西
编译前只剩
![image](https://user-images.githubusercontent.com/51957264/122142823-c7515a80-ce82-11eb-8aa8-f88340ac3e51.png)

**Comment by EnnawYang** [comment]
![Snipaste_2021-06-16_09-13-00](https://user-images.githubusercontent.com/6705663/122142986-10a1aa00-ce83-11eb-995b-221cb4c62d37.png)
可能我用的是假的actions吧

**Comment by yinzhefuyun** [comment]
https://github.com/P3TERX/Actions-OpenWrt  你换新脚本试一试，新脚本都是编译完成检测空间 ，不是编译钱检测空间，以前的脚本挂在空间是有问题，后面改了就多了40G

**Comment by shoucandanghehe** [comment]
@EnnawYang 你用的啥系统

**Comment by EnnawYang** [comment]
> https://github.com/P3TERX/Actions-OpenWrt 你换新脚本试一试，新脚本都是编译完成检测空间 ，不是编译钱检测空间，以前的脚本挂在空间是有问题，后面改了就多了40G

clone阶段也会检测空间的

**Comment by shoucandanghehe** [comment]
@yinzhefuyun 我是自己写的脚本
https://github.com/shoucandanghehe/Auto-Build/tree/OpenWrt

**Comment by EnnawYang** [comment]
> @yinzhefuyun 我是自己写的脚本
> https://github.com/shoucandanghehe/Auto-Build/tree/OpenWrt

你参照现有的脚本改改吧

**Comment by yinzhefuyun** [comment]
> @yinzhefuyun 我是自己写的脚本
> https://github.com/shoucandanghehe/Auto-Build/tree/OpenWrt

这个作者把其他分区的40G软连接给链接过来了，很早以前就发现还有一个分区有40G

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

**Comment by 281677160** [comment]
用P3TERX大神的脚本啊，空间大大的有
![QQ截图20210616092526](https://user-images.githubusercontent.com/66651997/122143887-f1a41780-ce84-11eb-9d21-4137b38b2708.png)

**Comment by shoucandanghehe** [comment]
我懂了
他删了亿堆东西hhhh
https://github.com/P3TERX/Actions-OpenWrt/blob/5703b4ea5d856d0e94ae20818f7c0d59d6d51082/.github/workflows/build-openwrt.yml#L48

**Comment by shoucandanghehe** [comment]
绝了，问题解决
```runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ df -hT $PWD
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4   84G   63G   21G  75% /
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ sudo rm -rf /etc/apt/sources.list.d/*
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ df -hT $PWD
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4   84G   63G   21G  75% /
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ sudo rm -rf /usr/share/dotnet
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ df -hT $PWD
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4   84G   37G   47G  45% /
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ sudo rm -rf /usr/local/lib/android
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ df -hT $PWD
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4   84G   27G   57G  33% /
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ sudo rm -rf /opt/ghc
runner@fv-az76-888:\~/work/Auto-Build/Auto-Build$ df -hT $PWD
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sdb1      ext4   84G   25G   59G  30% /
```

**Comment by Nothend** [comment]
> 
朋友你好，我看你用的“/work/Auto-Build/Auto-Build”这个目录，是在哪里啊，yml文件中如何加入你上面几条删除命令呢？

**Comment by shoucandanghehe** [comment]
> 朋友你好，我看你用的“/work/Auto-Build/Auto-Build”这个目录，是在哪里啊，yml文件中如何加入你上面几条删除命令呢？

参考https://github.com/shoucandanghehe/Auto-OpenWrt/blob/OpenWrt/.github/workflows/Build-x86-64.yml#L23-L29
