### ISSUE TITLE
make download fail for vlmcsd (tar hash not match that requested in Makefile)

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#7012]
please check the hash value is changed or not. I don't believe the download to my local have any interruption.

![image](https://user-images.githubusercontent.com/66289873/122181901-5a5ab680-cebc-11eb-8e99-2c450bca6e18.png)

![image](https://user-images.githubusercontent.com/66289873/122181809-4747e680-cebc-11eb-8584-88ca8b1d9dc2.png)

**Comment by Beginner-Go** [comment]
sha256 no problem , please download again

**Comment by galaxyskyknight** [comment]
so what the hell, I tried multiple times still got the same different hash value, if the file is corrupted by network issue, the hash value should be different every time ,but how could it be every time is the same '9510c....56af'?

![image](https://user-images.githubusercontent.com/66289873/122186898-14ecb800-cec1-11eb-8603-45d545c5c56a.png)

**Comment by Beginner-Go** [comment]
Why don't we have a problem?

**Comment by EnnawYang** [comment]
try using proxy ?

**Comment by galaxyskyknight** [comment]
yes, I am running behind the xray...you know that:)  anyway, the issue gone with 'make distclean'  and re-run make', I dont know what exact reason there, however, these two days the change is so huge and unstable. have to git pull... & pull....

**Comment by AmadeusGhost** [comment]
我也遇到了，暂时没找到哪里问题，makefile 里面的 hash 没错🌚

**Comment by Beginner-Go** [comment]
运行rm -rf build_dir/target-x86_64_musl/vlmcsd-svn1113 和  rm -rf dl/vlmcsd-svn1113.tar.gz试试？ 然后再make download V=s  试试

**Comment by coolsnowwolf** [comment]
先删除之前 dl 里面的包

**Comment by AmadeusGhost** [comment]
> so what the hell, I tried multiple times still got the same different hash value, if the file is corrupted by network issue, the hash value should be different every time ,but how could it be every time is the same '9510c....56af'?

似乎是 CDN 问题，现在应该好了
