### ISSUE TITLE
编译出错，依赖不能满足

### ISSUE THREAD

**Issue by baby195lxl** [coolsnowwolf/lede#7017]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译出错，依赖不能满足

### (2) 路由器型号和固件版本

A：N1盒子

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/48685934/122205897-571ef500-ced3-11eb-875f-6df6d679b48c.png)

**Comment by Dimitri2020007** [comment]
make download 软件包没有下完整

**Comment by baby195lxl** [comment]
> make download 软件包没有下完整

github action应该不存在软件包完整的问题啊
主要是bzip2的依赖无法满足，但是以前编译是可以的

**Comment by coolsnowwolf** [comment]
更新解决了

**Comment by baby195lxl** [comment]
> 更新解决了

谢谢带佬👍
