### ISSUE TITLE
因boost版本不匹配导致trojan编译失败

### ISSUE THREAD

**Issue by lilunxm12** [coolsnowwolf/lede#7019]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：编译失败,看日志是因为编译trojan时找不到boost1.73,但make download的时候并未报错,回朔发现下载的是1.76版本,和trojan依赖的并不一致

### (2) 路由器型号和固件版本

A：ARCH17

### (3) 详细日志

A：
<img width="1828" alt="Screen Shot 2021-06-16 at 8 40 52 PM" src="https://user-images.githubusercontent.com/24297319/122220950-69089400-cee3-11eb-8338-a9fbaa9b32ec.png">
<img width="1916" alt="Screen Shot 2021-06-16 at 8 40 22 PM" src="https://user-images.githubusercontent.com/24297319/122220990-70c83880-cee3-11eb-879c-cfe3fcda1c33.png">

**Comment by lilunxm12** [comment]
@coolsnowwolf 请问为何关闭了呢?我刚刚试了下还是同样的编译错误啊?还是说这个应该在helloworld里提?可是trojan本身确实是在lean里面而非helloworld里啊

**Comment by lilunxm12** [comment]
@coolsnowwolf 推倒重来,重新克隆并安装有新的发现,包括trojan在内有很多makefile报依赖缺失,看样子是改名了?
`
Collecting target info: done
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libpng', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/antileech/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/lean/baidupcs-web/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/dnsforwarder/Makefile' has a dependency on 'coreutils-base64', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'meson/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/lean/frp/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libgstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1-libs', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/lean/luci-app-accesscontrol/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-adbyby-plus/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'shairport-sync-openssl', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-amule/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-arpbind/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-baidupcs-web/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifs-mount/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a dependency on 'ksmbd-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cpufreq/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'parted', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'smartmontools', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'btrfs-progs', which does not exist
WARNING: Makefile 'package/lean/luci-app-dnsforwarder/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a dependency on 'dockerd', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils-nohup', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'bash', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-filetransfer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-flowoffload/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frpc/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-guest-wifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a dependency on 'haproxy', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-minimal', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-mod-xauth-generic', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'nginx', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'unzip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'zoneinfo-asia', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-fpm', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-gd', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-iconv', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-json', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-mbstring', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-opcache', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-session', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-zip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-sqlite3', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-sqlite', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-mysql', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-cgi', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-dom', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'forked-daapd', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-n2n_v2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a dependency on 'netdata', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nft-qos/Makefile' has a dependency on 'nft-qos', which does not exist
WARNING: Makefile 'package/lean/luci-app-nft-qos/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a dependency on 'openvpn-openssl', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a dependency on 'openvpn-easy-rsa', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-common', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-relay', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ps3netsrv/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-qbittorrent/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ramfree/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a dependency on 'fuse-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-samba4/Makefile' has a dependency on 'samba4-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-samba4/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-sfe/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-bridge', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-client', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a dependency on 'python3', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a dependency on 'ttyd', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-unblockmusic/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a dependency on 'p910nd', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-uugamebooster/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-v2ray-server/Makefile' has a dependency on 'unzip', which does not exist
WARNING: Makefile 'package/lean/luci-app-v2ray-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-verysync/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vlmcsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vsftpd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-webadmin/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a dependency on 'luci-app-nlbwmon', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-xlnetacc/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-xlnetacc/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a dependency on 'zerotier', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-lib-docker/Makefile' has a dependency on 'luci-lib-json', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci-lib-nixio', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a dependency on 'proto-bonding', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-argon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-netgear/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/drivers/mt7615d/Makefile' has a dependency on 'maccalc', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libtins', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libyaml-cpp', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/qtbase/Makefile' has a dependency on 'libpcre2-16', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-chrono', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-random', which does not exist
WARNING: Makefile 'package/lean/rclone/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a build dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/tcpping/Makefile' has a dependency on 'libnet-1.2.x', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-program_options', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-date_time', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusic/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusicGo/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/wxbase/Makefile' has a dependency on 'libexpat', which does not exist
`

**Comment by EnnawYang** [comment]
...就你最离谱

**Comment by lilunxm12** [comment]
> 
> 
> > 重新克隆并安装有新的发现,包括trojan在内有很多makefile报依赖缺失
> 
> ...就你最离谱

请问怎么离谱了呢?我也不希望浪费开发者时间,已经尽我力所能及的debug了,所有下载都经过了代理,make download日志我仔细检查了确保没有404等导致下载缺失,编译日志我也看了,确认了是boost版本不匹配,最后也换了新容器重新clone然后编译,复现出来的仍然是boost不匹配的错误,就是有新的发现了而已.如果有哪里做的不好让你觉得我离谱了,请指出
