### ISSUE TITLE
nginx出错

### ISSUE THREAD

**Issue by suixin1314** [coolsnowwolf/lede#7024]
脚本编译到nginx-util-1.5出错
Q：是否搜索了issue (使用 "x" 选择)
* [ √] 没有类似的issue

## 2. 详细叙述
用action编译x86固件

错误如下
CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5=nginx-util-1.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5=nginx-util-1.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include " LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro " make -j1 -C /workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="ccache_cc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5=nginx-util-1.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" CMAKE_COMMAND='/workdir/openwrt/staging_dir/host/bin/cmake' CMAKE_DISABLE_cmake_check_build_system=1 ;
make[4]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
make[5]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
make[6]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
make[6]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
make[6]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
[ 25%] Building CXX object CMakeFiles/nginx-ssl-util-nopcre.dir/nginx-util.cpp.o
In file included from nginx-util.cpp:4:
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:40: error: attributes at the beginning of statement are ignored [-Werror=attributes]
                 case '^': ret += '\\'; [[fallthrough]];
                                        ^
nginx-ssl-util.hpp:170:27: error: attributes at the beginning of statement are ignored [-Werror=attributes]
                 case '_': [[fallthrough]];
                           ^
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
CMakeFiles/nginx-ssl-util-nopcre.dir/build.make:81: recipe for target 'CMakeFiles/nginx-ssl-util-nopcre.dir/nginx-util.cpp.o' failed
                 case '^': ret += '\\'; [[fallthrough]];
make[6]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/nginx-ssl-util-nopcre.dir/all' failed
                           ~~~~^~~~~~~
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
nginx-ssl-util.hpp:170:17: note: here
Makefile:148: recipe for target 'all' failed
                 case '_': [[fallthrough]];
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5'
Makefile:118: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5/.built' failed
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/nginx-util'
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
nginx-ssl-util.hpp: In lambda function:
nginx-ssl-util.hpp:169:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 case '^': ret += '\\'; [[fallthrough]];
                           ~~~~^~~~~~~
nginx-ssl-util.hpp:170:17: note: here
                 case '_': [[fallthrough]];
                 ^~~~
cc1plus: all warnings being treated as errors
make[6]: *** [CMakeFiles/nginx-ssl-util-nopcre.dir/nginx-util.cpp.o] Error 1
make[5]: *** [CMakeFiles/nginx-ssl-util-nopcre.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/nginx-util-1.5/.built] Error 2
time: package/feeds/packages/nginx-util/compile#9.55#0.42#9.56
make[2]: *** [package/feeds/packages/nginx-util/compile] Error 1
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make: *** [world] Error 2
    ERROR: package/feeds/packages/nginx-util failed to build.
package/Makefile:114: recipe for target 'package/feeds/packages/nginx-util/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
package/Makefile:110: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by ziqqqq** [comment]
deepin下newifi d2遇到同样问题。
