### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by la8896** [coolsnowwolf/lede#7027]
![螢幕擷取畫面 2021-06-17 010825](https://user-images.githubusercontent.com/35804411/122263004-8b60d880-cf08-11eb-805f-6fc8701fb053.png)
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：编译出错

### (2) 路由器型号和固件版本

A：x64

### (3) 详细日志

A：ERROR: package/feeds/kenzo/lua-maxminddb failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [world] Error 1
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed

**Comment by Beginner-Go** [comment]
Please do not cross-breed other packages

**Comment by 13810169** [comment]
我也是这个错误

**Comment by c939984606** [comment]
vssr在最新源码会编译错误，先去掉吧
