### ISSUE TITLE
把package过了一遍，发现几处编译失败

### ISSUE THREAD

**Issue by EnnawYang** [coolsnowwolf/lede#7043]
target: x86_64
编译系统: Ubuntu 20.04
日志有点长，所以折叠处理了  
<details>
<summary>package/feeds/packages/jose failed to build.</summary>
<pre><code>
ninja: Entering directory `/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build'
[1/17] Generating jose-b64-dec.1 with a custom command
FAILED: jose-b64-dec.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-b64-dec.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-b64-dec.1.xml" returned non-zero exit status 4

[2/17] Generating jose-b64-enc.1 with a custom command
FAILED: jose-b64-enc.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-b64-enc.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-b64-enc.1.xml" returned non-zero exit status 4

[3/17] Generating jose.1 with a custom command
FAILED: jose.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose.1.xml" returned non-zero exit status 4

[4/17] Generating jose-jwe-enc.1 with a custom command
FAILED: jose-jwe-enc.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-jwe-enc.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-jwe-enc.1.xml" returned non-zero exit status 4

[5/17] Generating jose-alg.1 with a custom command
FAILED: jose-alg.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-alg.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-alg.1.xml" returned non-zero exit status 4

[6/17] Generating jose-jwk-eql.1 with a custom command
FAILED: jose-jwk-eql.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-jwk-eql.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-jwk-eql.1.xml" returned non-zero exit status 4

[7/17] Generating jose-jwe-dec.1 with a custom command
FAILED: jose-jwe-dec.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-jwe-dec.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-jwe-dec.1.xml" returned non-zero exit status 4

[8/17] Generating jose-fmt.1 with a custom command
FAILED: jose-fmt.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-fmt.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-fmt.1.xml" returned non-zero exit status 4

[9/17] Generating jose-jwe-fmt.1 with a custom command
FAILED: jose-jwe-fmt.1 
/usr/bin/a2x -f manpage -D /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/doc/man/jose-jwe-fmt.1.adoc
a2x: ERROR: "xmllint" --nonet --noout --valid "/home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/openwrt-build/jose-jwe-fmt.1.xml" returned non-zero exit status 4

ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:76: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/jose-11/.built] Error 1
time: package/feeds/packages/jose/compile#2.39#0.37#1.00
</code></pre>
</details>

<details>
<summary>package/feeds/packages/tang failed to build.</summary>
<pre><code>
The Meson build system
Version: 0.57.2
Source dir: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/tang-10
Build dir: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/tang-10/openwrt-build
Build type: cross build
WARNING: Unknown options: "build.libdir, build.prefix, build.sbindir"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: tang
Project version: 10
C compiler for the host machine: x86_64-openwrt-linux-musl-gcc (gcc 8.4.0 "x86_64-openwrt-linux-musl-gcc (OpenWrt GCC 8.4.0 r3268-c5fd96d93) 8.4.0")
C linker for the host machine: x86_64-openwrt-linux-musl-gcc ld.bfd 2.34
C compiler for the build machine: gcc (gcc 9.3.0 "gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the build machine: gcc ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: generic
Target machine cpu family: x86_64
Target machine cpu: generic
Found pkg-config: /home/xw/openwrt/lede/staging_dir/host/bin/pkg-config (1.7.3)
Found CMake: NO
Run-time dependency jose found: NO (tried pkgconfig)

../../../../build_dir/target-x86_64_musl/tang-10/meson.build:51:0: ERROR: Dependency "jose" not found, tried pkgconfig

A full log can be found at /home/xw/openwrt/lede/build_dir/target-x86_64_musl/tang-10/openwrt-build/meson-logs/meson-log.txt
make[2]: *** [Makefile:70: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/tang-10/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
time: package/feeds/packages/tang/compile#0.65#0.23#1.18
</code></pre>
</details>

<details>
<summary>package/lean/qttools failed to build.</summary>
<pre><code>
make[3]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1'
cd src/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/src.pro ) && make -f Makefile 
make[4]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile src.pro
cd linguist/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/linguist.pro ) && make -f Makefile 
make[5]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist'
cd lconvert/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lconvert/lconvert.pro ) && make -f Makefile 
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lconvert'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lconvert.pro
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lconvert'
cd lprodump/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lprodump/lprodump.pro ) && make -f Makefile 
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lprodump'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lprodump.pro
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lprodump'
cd lrelease/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease/lrelease.pro ) && make -f Makefile 
cd lrelease-pro/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease-pro/lrelease-pro.pro ) && make -f Makefile 
cd lupdate/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate/lupdate.pro ) && make -f Makefile 
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lrelease.pro
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate'
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease-pro'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lrelease-pro.pro
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lupdate.pro
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease-pro'
cd lupdate-pro/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate-pro/lupdate-pro.pro ) && make -f Makefile 
make[6]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate-pro'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile lupdate-pro.pro
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lrelease'
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate'
make[6]: Nothing to be done for 'first'.
make[6]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist/lupdate-pro'
make[5]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/linguist'
cd qtattributionsscanner/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtattributionsscanner/qtattributionsscanner.pro ) && make -f Makefile 
make[5]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtattributionsscanner'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile qtattributionsscanner.pro
make[5]: Nothing to be done for 'first'.
make[5]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtattributionsscanner'
cd qtplugininfo/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtplugininfo/qtplugininfo.pro ) && make -f Makefile 
make[5]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtplugininfo'
x86_64-openwrt-linux-musl-g++ -c -pipe -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qtbase-everywhere-src-5.15.1=qtbase-everywhere-src-5.15.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -ffunction-sections -fdata-sections -I/home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include --sysroot=/home/xw/openwrt/lede/staging_dir/target-x86_64_musl -O2 -std=c++1z -fno-exceptions -flto -fno-fat-lto-objects -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I/home/xw/openwrt/lede/staging_dir/target-x86_64_musl/usr/include/QtCore -I.moc -I/home/xw/openwrt/lede/staging_dir/hostpkg/mkspecs/devices/linux-generic-g++ -o .obj/qtplugininfo.o qtplugininfo.cpp
In file included from /home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/QtCore/qalgorithms.h:43,
                 from /home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/QtCore/qlist.h:43,
                 from /home/xw/openwrt/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/QtCore/qstringlist.h:41,
                 from /home/xw/openwrt/lede/staging_dir/target-x86_64_musl/usr/include/QtCore/qcommandlineparser.h:43,
                 from /home/xw/openwrt/lede/staging_dir/target-x86_64_musl/usr/include/QtCore/QCommandLineParser:1,
                 from qtplugininfo.cpp:30:
/home/xw/openwrt/lede/staging_dir/target-x86_64_musl/usr/include/QtCore/qjsondocument.h:114:5: error: division by zero in #if
 #if QT_CONFIG(binaryjson) && QT_DEPRECATED_SINCE(5, 15)
     ^~~~~~~~~
make[5]: *** [Makefile:308: .obj/qtplugininfo.o] Error 1
make[5]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src/qtplugininfo'
make[4]: *** [Makefile:100: sub-qtplugininfo-make_first] Error 2
make[4]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/src'
make[3]: *** [Makefile:49: sub-src-make_first] Error 2
make[3]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1'
make[2]: *** [Makefile:54: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qttools-everywhere-src-5.15.1/.built] Error 2
time: package/lean/qttools/compile#1.91#0.25#2.05
</code></pre>
</details>

<details>
<summary>package/lean/qBittorrent failed to build.</summary>
<pre><code>
make[3]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile qbittorrent.pro QMAKE_LRELEASE=
cd src/ && ( test -e Makefile || /home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5/src/src.pro QMAKE_LRELEASE= ) && make -f Makefile 
make[4]: Entering directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5/src'
/home/xw/openwrt/lede/staging_dir/hostpkg/bin/qmake -o Makefile src.pro QMAKE_LRELEASE=
Project MESSAGE: Project is built in RELEASE mode.
Project MESSAGE: Disabling debug output.
lrelease webui/www/translations/webui_ar.ts
/bin/sh: 1: lrelease-qt5: not found
make[4]: *** [Makefile:777: webui/www/translations/webui_ar.qm] Error 127
make[4]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5/src'
make[3]: *** [Makefile:47: sub-src-make_first] Error 2
make[3]: Leaving directory '/home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5'
make[2]: *** [Makefile:78: /home/xw/openwrt/lede/build_dir/target-x86_64_musl/qBittorrent-release-4.3.5/.built] Error 2
time: package/lean/qBittorrent/compile#0.80#0.18#1.30
</code></pre>
</details>

**Comment by coolsnowwolf** [comment]
qttols 和 qbt 是没问题的

**Comment by EnnawYang** [comment]
> qttols 和 qbt 是没问题的

那可能是我没清理直接pull了吧，毕竟跑一遍时间有点长（

**Comment by coolsnowwolf** [comment]
测试所有都通过，没问题

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/122396159-4db48c00-cfaa-11eb-83b2-145f37b4de74.png)

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/122396206-573df400-cfaa-11eb-9c8e-6737efd0ef70.png)

**Comment by EnnawYang** [comment]
🌚尴尬
