### ISSUE TITLE
问题太多了，忍不住借这里吐下槽，升内核后各种问题，即便编译过了跑起来还是各种问题

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#7044]
辛苦developer们尽快排bug~

**Comment by chobitsos** [comment]
就突然更新了内核，真的不太稳，可以换个稳一点的内核吗？

**Comment by baby195lxl** [comment]
吐槽是没用的，你提bug和给点赞助啊

**Comment by galaxyskyknight** [comment]
> 吐槽是没用的，你提bug和给点赞助啊

可以，给个渠道，buy some beer or coffee没问题的。

**Comment by EnnawYang** [comment]
> > 吐槽是没用的，你提bug和给点赞助啊
> 
> 可以，给个渠道，buy some beer or coffee没问题的。

readme有啊

**Comment by galaxyskyknight** [comment]
![image](https://user-images.githubusercontent.com/66289873/122378990-070a6600-cf99-11eb-8f5b-1de3b15ecb17.png)
一杯咖啡，辛苦码农

**Comment by baby195lxl** [comment]
> ![image](https://user-images.githubusercontent.com/66289873/122378990-070a6600-cf99-11eb-8f5b-1de3b15ecb17.png)
> 一杯咖啡，辛苦码农

👍
