### ISSUE TITLE
负载均衡运行报错

### ISSUE THREAD

**Issue by starxu1971** [coolsnowwolf/lede#7045]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
X86
A：

### (3) 详细日志

A：haproxy: line 21: extra_command: not found

**Comment by chobitsos** [comment]
为啥要删除，这个是passwall的依赖包

**Comment by starxu1971** [comment]
我没修改模板不是要删除，其实运行报错，代码 sh: /etc/init.d/haproxy: line 21: extra_command: not found
