### ISSUE TITLE
A lot of warning when feeds install

### ISSUE THREAD

**Issue by galaxyskyknight** [coolsnowwolf/lede#7051]
luke@BuildServer:~/lede_x86_new$ ./scripts/feeds install -a
Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libpng', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/amule/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/antileech/Makefile' has a build dependency on 'libgd', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bc', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'lm-sensors', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'luci-app-samba', which does not exist
WARNING: Makefile 'package/lean/autosamba/Makefile' has a dependency on 'wsdd2', which does not exist
WARNING: Makefile 'package/lean/baidupcs-web/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_aliyun/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/ddns-scripts_dnspod/Makefile' has a dependency on 'ddns-scripts', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-base', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/default-settings/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/dnsforwarder/Makefile' has a dependency on 'coreutils-base64', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'meson/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/network/utils/dpdk/Makefile' has a build dependency on 'ninja/host', which does not exist
WARNING: Makefile 'package/lean/frp/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libgstreamer1', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'gstreamer1-libs', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'glib2', which does not exist
WARNING: Makefile 'package/lean/gmediarender/Makefile' has a dependency on 'libupnp', which does not exist
WARNING: Makefile 'package/lean/ipv6-helper/Makefile' has a dependency on 'luci-proto-ipv6', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/lean/luci-app-accesscontrol/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-adbyby-plus/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a dependency on 'shairport-sync-openssl', which does not exist
WARNING: Makefile 'package/lean/luci-app-airplay2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-amule/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-arpbind/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-app-autoreboot/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-baidupcs-web/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifs-mount/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a dependency on 'ksmbd-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-cifsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-cpufreq/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'parted', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'smartmontools', which does not exist
WARNING: Makefile 'package/lean/luci-app-diskman/Makefile' has a dependency on 'btrfs-progs', which does not exist
WARNING: Makefile 'package/lean/luci-app-dnsforwarder/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a dependency on 'dockerd', which does not exist
WARNING: Makefile 'package/lean/luci-app-docker/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'coreutils-nohup', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'bash', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-familycloud/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-filetransfer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-flowoffload/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frpc/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-frps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-guest-wifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a dependency on 'haproxy', which does not exist
WARNING: Makefile 'package/lean/luci-app-haproxy-tcp/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-minimal', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a dependency on 'strongswan-mod-xauth-generic', which does not exist
WARNING: Makefile 'package/lean/luci-app-ipsec-vpnd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-jd-dailybonus/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'nginx', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'unzip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'zoneinfo-asia', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-fpm', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-gd', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-iconv', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-json', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-mbstring', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-opcache', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-session', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-zip', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-sqlite3', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-sqlite', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-pdo-mysql', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-cgi', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a dependency on 'php7-mod-dom', which does not exist
WARNING: Makefile 'package/lean/luci-app-kodexplorer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/luci-app-mtwifi/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'alsa-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a dependency on 'forked-daapd', which does not exist
WARNING: Makefile 'package/lean/luci-app-music-remote-center/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-mwan3helper/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-n2n_v2/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a dependency on 'netdata', which does not exist
WARNING: Makefile 'package/lean/luci-app-netdata/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a dependency on 'nfs-kernel-server-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-nfs/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nft-qos/Makefile' has a dependency on 'nft-qos', which does not exist
WARNING: Makefile 'package/lean/luci-app-nft-qos/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-nps/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a dependency on 'openvpn-openssl', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a dependency on 'openvpn-easy-rsa', which does not exist
WARNING: Makefile 'package/lean/luci-app-openvpn-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-common', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a dependency on 'rp-pppoe-relay', which does not exist
WARNING: Makefile 'package/lean/luci-app-pppoe-relay/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ps3netsrv/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-qbittorrent/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ramfree/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a dependency on 'fuse-utils', which does not exist
WARNING: Makefile 'package/lean/luci-app-rclone/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-samba4/Makefile' has a dependency on 'samba4-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-samba4/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-sfe/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-bridge', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-client', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a dependency on 'softethervpn5-server', which does not exist
WARNING: Makefile 'package/lean/luci-app-softethervpn/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a dependency on 'python3', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssrserver-python/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a dependency on 'luci-app-mwan3', which does not exist
WARNING: Makefile 'package/lean/luci-app-syncdial/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a dependency on 'ttyd', which does not exist
WARNING: Makefile 'package/lean/luci-app-ttyd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-unblockmusic/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a dependency on 'p910nd', which does not exist
WARNING: Makefile 'package/lean/luci-app-usb-printer/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-uugamebooster/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-v2ray-server/Makefile' has a dependency on 'unzip', which does not exist
WARNING: Makefile 'package/lean/luci-app-v2ray-server/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-verysync/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vlmcsd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-vsftpd/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-webadmin/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a dependency on 'luci-app-nlbwmon', which does not exist
WARNING: Makefile 'package/lean/luci-app-wrtbwmon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-app-xlnetacc/Makefile' has a dependency on 'curl', which does not exist
WARNING: Makefile 'package/lean/luci-app-xlnetacc/Makefile' has a dependency on 'luci-compat', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a dependency on 'zerotier', which does not exist
WARNING: Makefile 'package/lean/luci-app-zerotier/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-lib-docker/Makefile' has a dependency on 'luci-lib-json', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci', which does not exist
WARNING: Makefile 'package/lean/luci-lib-fs/Makefile' has a dependency on 'luci-lib-nixio', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a dependency on 'proto-bonding', which does not exist
WARNING: Makefile 'package/lean/luci-proto-bonding/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-argon/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/luci-theme-netgear/Makefile' has a build dependency on 'luci-base/host', which does not exist
WARNING: Makefile 'package/lean/mt/drivers/mt7615d/Makefile' has a dependency on 'maccalc', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libzstd', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libtins', which does not exist
WARNING: Makefile 'package/network/services/noddos/Makefile' has a dependency on 'libyaml-cpp', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/policycoreutils/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/lean/qtbase/Makefile' has a dependency on 'libpcre2-16', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-chrono', which does not exist
WARNING: Makefile 'package/lean/rblibtorrent/Makefile' has a dependency on 'boost-random', which does not exist
WARNING: Makefile 'package/lean/rclone/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/simple-obfs/Makefile' has a build dependency on 'libev', which does not exist
WARNING: Makefile 'package/lean/tcpping/Makefile' has a dependency on 'libnet-1.2.x', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-system', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-program_options', which does not exist
WARNING: Makefile 'package/lean/trojan/Makefile' has a dependency on 'boost-date_time', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusic/Makefile' has a dependency on 'node', which does not exist
WARNING: Makefile 'package/lean/UnblockNeteaseMusicGo/Makefile' has a build dependency on 'golang/host', which does not exist
WARNING: Makefile 'package/lean/wxbase/Makefile' has a dependency on 'libexpat', which does not exist

**Comment by galaxyskyknight** [comment]
Above happen when I creat a emtpy folder and pull the code, everthing start from original.

**Comment by EnnawYang** [comment]
This is normal for the first installation, just ignore it

**Comment by baalwy** [comment]
it's the same problem until now
