### ISSUE TITLE
5.10内核老旧主板（捷波NF36 2600）好像不能启动

### ISSUE THREAD

**Issue by harleywong** [coolsnowwolf/lede#7063]
5.4内核没有问题
用U盘试了一下新5.10内核固件（i5二代笔记本可以启动）
老旧主板捷波NF36 2600 好像不能启动，因为我这主板不能插显示器，只能看到开机后网口的握手只有100M，估计是没有启动成功。

**Comment by ybist** [comment]
我信步26026也不行了，原厂的bios。

**Comment by minlang112** [comment]
有com口的话可以连上去看看输出信息

**Comment by coolsnowwolf** [comment]
fixed
