### ISSUE TITLE
系统选项里面没有ZRAM选项

### ISSUE THREAD

**Issue by blueveryday** [coolsnowwolf/lede#707]
WR703NV1机型，git更新到最新的源代码。
编译时在base里面选择了ZRAM，但是系统选项里面，找不到帖子里面的ZRAM设置界面。论坛帖子里面不少人反馈这个问题，可能是共同的问题，大雕能不能看看？谢谢。

**Comment by dzhuqi** [comment]
有 在 Base system 最下面

**Comment by agooday** [comment]
在系统里面
