### ISSUE TITLE
新版本多拨负载均衡无效，网速无法叠加

### ISSUE THREAD

**Issue by evenwangcn** [coolsnowwolf/lede#7081]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：升级新版本后，状态菜单下负载均衡页面显示两个MWAN口都是禁用，但网络菜单下接口页面显示连个虚拟WAN都已经拨号上，经测试负载均衡失效了，网速没有叠加，刷回旧版本是好的。

### (2) 路由器型号和固件版本

A：x86软路由，编辑的最新版本

### (3) 详细日志

A：

**Comment by 19901019** [comment]
我的双拨可以叠加，需要在负载均衡把vwan1和vwan2以外全删就可以了。

**Comment by xxp2277** [comment]
同样无法叠加（WNDR3800，单线3拨），状态里3个接口均显示已禁用，多线多拨界面显示当前在线接口数量：0（网络，接口里能看见3个接口均得到正确的ip了，但流量全部走vwan1）。

**Comment by evenwangcn** [comment]
???

**Comment by evenwangcn** [comment]
？？？，这个问题是bug吗？修复了？
