### ISSUE TITLE
请问怎么获取大更新前的那个版本？？

### ISSUE THREAD

**Issue by dukmonki** [coolsnowwolf/lede#7084]
大更新后的版本不少。我的hiwifi 5962 没有无线，还有死机断流情况，需要重启路由。

**Comment by ZeroForce423** [comment]
cd lede
git config --global advice.detachedHead false
git checkout 7883a5d2e672c63c9e992a09e523892f0ed748cf
make dirclean
临时解决方案

**Comment by dukmonki** [comment]
谢谢，什么叫临时解决方案？
