### ISSUE TITLE
新版内核后端口转发luci 界面显示有问题

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#7086]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

![image](https://user-images.githubusercontent.com/43886952/122635612-87ef6c00-d117-11eb-8d9d-cda78a2861cb.png)
在新版内核后，发现一个应该是luci 显示界面问题，在防火墙》端口转发下进行一个转发，在界面上回显示：来自 所有主机 位于 wan 源于 uci: Entry not found
通过 所有路由 IP 在 端口 8000
实际测试端口转发正常。可能只是界面显示的问题，不懂能不能修复？

**Comment by coolsnowwolf** [comment]
fixed
