### ISSUE TITLE
toplevel.mk编译报错。。

### ISSUE THREAD

**Issue by gentle95** [coolsnowwolf/lede#7087]
/home/runner/work/M.T.OpenWrt/M.T.OpenWrt/.config:41: *** missing separator.  Stop.
make: *** [/home/runner/work/M.T.OpenWrt/M.T.OpenWrt/include/toplevel.mk:79: prepare-tmpinfo] Error 2
Error: Process completed with exit code 2.

这个文件编译报错。。
include/toplevel.mk:79: prepare-tmpinfo] Error 2

**Comment by lphgor** [comment]
不是第一行报错了么？把.config删了重新配置一下看看
