### ISSUE TITLE
我也不知道该不该在这打扰，希望有大神看到帮忙解决一下

### ISSUE THREAD

**Issue by brianzc0306** [coolsnowwolf/lede#7088]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

新版源码编译luci-app-godproxy开启规则就出现错误
https://github.com/project-lede/luci-app-godproxy.git

### (3) 详细日志
Sat Jun 19 17:56:01 2021 kern.info kernel: [   78.476726] koolproxy[4313]: segfault at 7f412d9fd900 ip 00007f412d9fd900 sp 00007f412d9fd898 error 15
Sat Jun 19 17:56:01 2021 kern.info kernel: [   78.479640] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 00 2a 41 7f 00 00 41 bb 30 2f 41 00 49 ba e0 d8 9f 2d 41 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 d8 9f 2d 41 7f 00 00 49 ff e3 90 41 7f
Sat Jun 19 17:56:06 2021 daemon.info koolproxy[5191]: koolproxy v3.8.5
Sat Jun 19 17:56:07 2021 kern.info kernel: [   84.723741] koolproxy[5200]: segfault at 7ff803d0a900 ip 00007ff803d0a900 sp 00007ff803d0a898 error 15
Sat Jun 19 17:56:07 2021 kern.info kernel: [   84.726464] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 40 00 f8 7f 00 00 41 bb 30 2f 41 00 49 ba e0 a8 d0 03 f8 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 a8 d0 03 f8 7f 00 00 49 ff e3 90 f8 7f
Sat Jun 19 17:56:13 2021 daemon.info koolproxy[5210]: koolproxy v3.8.5
Sat Jun 19 17:56:14 2021 kern.info kernel: [   91.233127] koolproxy[5221]: segfault at 7f7e58967900 ip 00007f7e58967900 sp 00007f7e58967898 error 15
Sat Jun 19 17:56:14 2021 kern.info kernel: [   91.235854] Code: 00 00 95 34 41 00 00 00 00 00 d8 dc 00 55 7e 7f 00 00 41 bb 30 2f 41 00 49 ba e0 78 96 58 7e 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 78 96 58 7e 7f 00 00 49 ff e3 90 7e 7f
Sat Jun 19 17:56:14 2021 kern.info kernel: [   91.239232] koolproxy[5220]: segfault at 7f7e58992900 ip 00007f7e58992900 sp 00007f7e58992898 error 15
Sat Jun 19 17:56:14 2021 kern.info kernel: [   91.244444] Code: 00 00 95 34 41 00 00 00 00 00 d8 e1 00 55 7e 7f 00 00 41 bb 30 2f 41 00 49 ba e0 28 99 58 7e 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 28 99 58 7e 7f 00 00 49 ff e3 90 7e 7f
Sat Jun 19 17:56:19 2021 daemon.info koolproxy[5231]: koolproxy v3.8.5
A：

**Comment by Karmylr** [comment]
直接关了...
