### ISSUE TITLE
luci-app-cpufreq 设置cpu工作模式的输入参数错误

### ISSUE THREAD

**Issue by dansir118** [coolsnowwolf/lede#7092]
## 1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
### (1) 具体问题
luci-app-cpufreq
 设置cpu工作模式为“performance”时，实际输入参数为“performance 高性能模式（降低游戏转发延迟）”；
设置cpu工作模式为"ondemand"时，实际输入参数为“ondemand 自动平衡模式”。
以上输入参数错误，正确参数应为performance或ondemand。
### (2) 路由器型号和固件版本
ASUS RT-ACRH17/R21.6.14-Linux5.4.125-git_260fbd3
### (3) 详细日志
![QQ截图20210619220008](https://user-images.githubusercontent.com/86155752/122644854-e03f6180-d149-11eb-987d-7c26c8d146cc.png)

**Comment by coolsnowwolf** [comment]
已修复
