### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by wwz09** [coolsnowwolf/lede#7097]
WARNING: Not overriding core package 'dns2socks'; use -f to force
WARNING: Not overriding core package 'ipt2socks'; use -f to force
WARNING: Not overriding core package 'luci-app-jd-dailybonus'; use -f to force
WARNING: Not overriding core package 'luci-theme-argon'; use -f to force
WARNING: Not overriding core package 'microsocks'; use -f to force
WARNING: Not overriding core package 'pdnsd-alt'; use -f to force
WARNING: Not overriding core package 'redsocks2'; use -f to force
WARNING: Not overriding core package 'simple-obfs'; use -f to force
WARNING: Not overriding core package 'trojan'; use -f to force

**Comment by EnnawYang** [comment]
请参照顶置issue
