### ISSUE TITLE
/sbin/urngd 高cpu占用

### ISSUE THREAD

**Issue by cyijun** [coolsnowwolf/lede#7099]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

/sbin/urngd 高cpu占用，在25%-60%反复横跳，于启动103天出现，kill掉进程解决。openwrt docker有相似问题被报告，可能是源码导致。

https://github.com/openwrt/docker/issues/46

### (2) 路由器型号和固件版本

路由器：HLK-7621

版本：OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)
内核：5.4.92

### (3) 详细日志

用grep搜索，内核与系统日志都无相关信息

**Comment by coolsnowwolf** [comment]
等上游更新吧

**Comment by coolsnowwolf** [comment]
先添加了个补丁解决了
