### ISSUE TITLE
斐讯K3开启14信道提示无线未开启或未关联

### ISSUE THREAD

**Issue by PitFather007** [coolsnowwolf/lede#710]
使用机器   斐讯K3，
固件版本 | OpenWrt R8.1.8
内核版本 | 4.14.77
切换日本地区后发现，使用12.13.14信道都会提示无线未开启或未关联

![tim 20181020172435](https://user-images.githubusercontent.com/43899467/47254011-135b5f80-d48e-11e8-9c70-167359adca7d.png)

[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2497995/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2497996/default.txt)

**Comment by coolsnowwolf** [comment]
只有高通能用。。。

**Comment by PitFather007** [comment]
> 只有高通能用...

这样，是不是因为没有开源？
