### ISSUE TITLE
最新提交的Hiwifi C526A 128M相关的内容全部没了

### ISSUE THREAD

**Issue by liuzhongh** [coolsnowwolf/lede#7115]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：最新提交的Hiwifi C526A 128M相关的内容全部没了

### (2) 路由器型号和固件版本

A：Hiwifi C526A

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
没有机器，不再支持

**Comment by AmadeusGhost** [comment]
我之前提交的代码本来就是 128M 版本，没必要在型号后面再加一个 128M 吧…
