### ISSUE TITLE
210-arm64-sve-Disentangle-uapi-asm-ptrace.h 出错

### ISSUE THREAD

**Issue by DamnCrab** [coolsnowwolf/lede#7122]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
有过hunk出错 但文件不同

### (1) 具体问题

A：好像是补丁hunk出错

Applying /home/crab/openwrt/target/linux/generic/backport-4.19/210-arm64-sve-Disentangle-uapi-asm-ptrace.h-from-uapi-as.patch using plaintext: 
patching file arch/arm64/include/uapi/asm/ptrace.h
Hunk #2 FAILED at 129.
1 out of 4 hunks FAILED -- saving rejects to file arch/arm64/include/uapi/asm/ptrace.h.rej
patching file arch/arm64/include/uapi/asm/sigcontext.h
patching file arch/arm64/include/uapi/asm/sve_context.h
Patch failed!  Please fix /home/crab/openwrt/target/linux/generic/backport-4.19/210-arm64-sve-Disentangle-uapi-asm-ptrace.h-from-uapi-as.patch!
make[3]: *** [Makefile:113: /home/crab/openwrt/build_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/linux-4.19/.prepared] Error 1
make[3]: Leaving directory '/home/crab/openwrt/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#2.37#14.76#10.96
make[2]: *** [toolchain/Makefile:100: toolchain/kernel-headers/compile] Error 2
make[2]: Leaving directory '/home/crab/openwrt'
make[1]: *** [toolchain/Makefile:96: /home/crab/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/crab/openwrt'
make: *** [/home/crab/openwrt/include/toplevel.mk:227：world] 错误 2

### (2) 路由器型号和固件版本

A：树莓派3B+

**Comment by lihonfu** [comment]
210-arm64-sve-Disentangle-uapi-asm-ptrace.h-from-uapi-as.patch
怎么解决的?
