### ISSUE TITLE
Wan & Lan dead with 5.10 on ramips

### ISSUE THREAD

**Issue by MrArtemSid** [coolsnowwolf/lede#7123]
Wan & Lan dead with 5.10 on ramips: mt7621: Xiaomi Router AC2100

**Comment by alienaltman** [comment]
> Wan & Lan dead with 5.10 on ramips: mt7621: Xiaomi Router AC2100

I have a similar problem with the NeWifi3 D2 router. Wireless connection is good.

**Comment by coolsnowwolf** [comment]
看起来 4.14 的交换机驱动在 5.10 不能运行了
