### ISSUE TITLE
请问应该如何编译tp-link wr-720n-v4 的固件？

### ISSUE THREAD

**Issue by fishslidenas** [coolsnowwolf/lede#7128]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：请问应该如何编译tp-link wr-720n-v4 的固件？我在/target/linux/image/tiny-tp-link.mk 中没有找到对应的机型，以前是有的，现在没有了。

### (2) 路由器型号和固件版本

A：路由器是  tp-link wr-720n-v4 

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
4MB 系列的官方 OpenWrt 已经全部删除了，用这个库吧

https://github.com/coolsnowwolf/openwrt

**Comment by fishslidenas** [comment]
多谢多谢。我的是硬改内存到了16MB，之前是自己改配置文件的。
再次感谢~
