### ISSUE TITLE
友善 r4s 1GB 固件刷了无法启动

### ISSUE THREAD

**Issue by KLT007** [coolsnowwolf/lede#7132]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

## 2. 详细叙述
友善 r4s 1GB 固件刷了无法启动
### (1) 具体问题

A：最近通过编译最新固件，刷了R4S启动不了，开机没亮，无法启动，不过发现rufus写卡日志第二个分区无法写入

### (2) 路由器型号和固件版本

A：R4S 1GB版本

### (3) 详细日志

A ：Disk image analysis:
  Image has a Zeroed Master Boot Record
  Image is a bootable disk image
Using image: openwrt-rockchip-armv8-friendlyarm_nanopi-r4s-squashfs-sysupgrade (1).img (364.2 MB)

Format operation started
Requesting disk access...
No drive letter was assigned...
Will use 'D:' as volume mountpoint
No partition to delete on disk
Opened \\.\PhysicalDrive1 for exclusive write access
Requesting logical volume handle...
+++++++++++++
Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:1212)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1958, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x5452574F
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: GNU/Linux (0x83)
  Size: 80 MB (83886080 bytes)
  Start Sector: 65536, Boot: Yes
Partition 2:
  Type: GNU/Linux (0x83)
  Size: 1.2 GB (1258291200 bytes)
  Start Sector: 262144, Boot: No

**Comment by EnnawYang** [comment]
1GB version is not supported.

**Comment by KLT007** [comment]
> 1GB version is not supported.

什么时候支持？

**Comment by EnnawYang** [comment]
> > 1GB version is not supported.
> 
> 什么时候支持？

自己换个大点的卡

**Comment by KLT007** [comment]
128G TF卡吗？

**Comment by KLT007** [comment]
是1G内存卡不支持了还是R4S-1G不支持了？

**Comment by EnnawYang** [comment]
> Partition 1:  
> Size: 80 MB (83886080 bytes)
> Partition 2:  
> Size: 1.2 GB (1258291200 bytes)  
> 
总大小超过1G，1G的tf卡当然刷不进

**Comment by EnnawYang** [comment]
你是昨晚群里问的那个？

**Comment by KLT007** [comment]
昨晚我看他也和我一样问题，所以才来问

**Comment by KLT007** [comment]
按你这么说，我用128核重新编译了固件，改了总大小，依然那样问题
Partition 1:
  Type: GNU/Linux (0x83)
  Size: 64 MB (67108864 bytes)
  Start Sector: 65536, Boot: Yes
Partition 2:
  Type: GNU/Linux (0x83)
  Size: 960 MB (1006632960 bytes)
  Start Sector: 262144, Boot: No

**Comment by coolsnowwolf** [comment]
采用了官方的代码，根本不支持 1GB 版本了

**Comment by KLT007** [comment]
> 采用了官方的代码，根本不支持 1GB 版本了

这样啊，感谢回复
