### ISSUE TITLE
close

### ISSUE THREAD

**Issue by softtip** [coolsnowwolf/lede#7137]
close

**Comment by OleStore** [comment]
编译报错

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-input-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-input-core found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-button-hotplug:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-button-hotplug.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-hash
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-hash found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-null
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-null found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-aead
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-aead found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-manager
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-manager found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-cryptodev:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-cryptodev.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-scsi-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-scsi-core found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-scsi-core.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-crc32
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-crc32 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-crypto-crc32.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-crc32c
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-crc32c found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-crypto-crc32c.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-lib-zlib-inflate
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-lib-zlib-inflate found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-lib-zlib-deflate
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-lib-zlib-deflate found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-deflate:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-crypto-deflate.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-ecb
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-ecb found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-crypto-ecb.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-gf128
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-gf128 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-crypto-ghash
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-crypto-ghash found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-gcm:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-crypto-gcm.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-nls-base
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nls-base found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-exfat:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-fs-exfat.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-lib-crc16
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-lib-crc16 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-fs-ext4
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-fs-ext4 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-fs-ext4.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-fs-f2fs
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-fs-f2fs found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-fs-f2fs.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-hwmon-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-hwmon-core found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-hwmon-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-crc16:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-lib-crc16.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-crc32c:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-lib-crc32c.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-igb:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-igb.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-vmxnet3
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-vmxnet3 found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-vmxnet3.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-mppe:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-mppe.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-mmc
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-mmc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-mmc.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sdhci:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-sdhci.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-thermal
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-thermal found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-thermal.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-usb-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-core found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-usb-core.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead) for kmod-usb-storage
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-usb-storage found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-usb-storage.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-storage-extras:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-usb-storage-extras.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ath10k:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package kmod-ath10k.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for automount:
 *      kernel (= 5.10.43-1-a728eeaa77e1426d9ace729123929ead)
 * opkg_install_cmd: Cannot install package automount.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/wang/lede'
make[1]: *** [package/Makefile:111: /home/wang/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/wang/lede'
make: *** [/home/wang/lede/include/toplevel.mk:230: world] Error 2
