### ISSUE TITLE
linux-firmware下载错误

### ISSUE THREAD

**Issue by gavin219** [coolsnowwolf/lede#714]
R818编译固件当下载到linux-firmware的时候总是过不去，发现官方的是2018-10-18，lean的是2018-09-28，但是PKG_SOURCE_VERSION，PKG_MIRROR_HASH完全一样，只有PKG_SOURCE_DATE不一样

**Comment by maxxwall** [comment]
三个站点都没有这个文件，只有这两个
linux-firmware-2018-08-03-7b5835fd.tar.xz          26-Sep-2018 16:50            72060824
linux-firmware-2018-10-18-d8775336.tar.xz          20-Oct-2018 15:11                   0

不过这 clone 好慢

+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.lede-project.org/linux-firmware-2018-09-28-d8775336.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://mirror2.openwrt.org/sources/linux-firmware-2018-09-28-d8775336.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.openwrt.org/sources/linux-firmware-2018-09-28-d8775336.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0     58      0  0:00:03  0:00:03 --:--:--    58
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'linux-firmware-2018-09-28-d8775336'...
remote: Counting objects: 7220, done.
remote: Compressing objects: 100% (238/238), done.
^Crsi.mk:6: recipe for target '/home/msi/lede/dl/linux-firmware-2018-09-28-d8775336.tar.xz' failed
make[3]: *** [/home/msi/lede/dl/linux-firmware-2018-09-28-d8775336.tar.xz] Interrupt
time: package/firmware/linux-firmware/compile#1.95#0.56#4284.68
package/Makefile:103: recipe for target '/home/msi/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/msi/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Interrupt
/home/msi/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] 中断
