### ISSUE TITLE
ipq806x的cpufreq

### ISSUE THREAD

**Issue by missorforget** [coolsnowwolf/lede#7148]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

check_data_file_clashes: Package luci-app-cpufreq wants to install file /home/lede/lean/m520/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/etc/init.d/cpufreq
        But that file is already provided by package  * base-files
 * opkg_install_cmd: Cannot install package luci-app-cpufreq.

### (2) 路由器型号和固件版本

ipq806x-generic-ruijie_rg-mtfi-m520

**Comment by shikkoku** [comment]
https://github.com/coolsnowwolf/lede/commit/55d545b926eb86aa578dc9cb7dc3d7a31f6e37d6

我想和这个有关。

**Comment by missorforget** [comment]
意思是不要用luci-app-cpufreq了

**Comment by missorforget** [comment]
那就不用了
