### ISSUE TITLE
编译到最后出现警告

### ISSUE THREAD

**Issue by ruderal04o** [coolsnowwolf/lede#7155]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
云编译到最后出现警告信息
### (1) 具体问题
make[2] package/index
WARNING: Applying padding in /workdir/openwrt/bin/packages/x86_64/packages/Packages to workaround usign SHA-512 bug!
A：

### (2) 路由器型号和固件版本
x86_64
A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
忽略即可。。

**Comment by IDeLoveYou** [comment]
这是什么情况
