### ISSUE TITLE
Dnspod 出错

### ISSUE THREAD

**Issue by leone424** [coolsnowwolf/lede#7157]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
DDNS 里 Dnspod 出错
Q：是否搜索了issue (使用 "x" 选择)
[ x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：OpenWrt R21.6.22 / LuCI Master (git-21.173.12022-bfe9018)

### (3) 详细日志

A：
![WX20210623-192449](https://user-images.githubusercontent.com/86337954/123088765-b8f1d880-d458-11eb-808a-3103a1d8de94.png)

**Comment by wspzf** [comment]
你不是一个人，我也一样

**Comment by swxk521** [comment]
看看有没有安装wget-ssl组件
没有的话就安装上或编译时加上。
或者等大佬改下DDNS脚本。

**Comment by wspzf** [comment]
> 看看有没有安装 wget-ssl 组件
> 没有的话就安装上或编译时加上。
> 或者等大佬改下 DDNS 脚本。
![image](https://user-images.githubusercontent.com/43857401/123102601-d24e5100-d467-11eb-9163-5a2f98df027e.png)
编译加上这个就可以了

**Comment by wspzf** [comment]
> 看看有没有安装 wget-ssl 组件
> 没有的话就安装上或编译时加上。
> 或者等大佬改下 DDNS 脚本。

![image](https://user-images.githubusercontent.com/43857401/123102601-d24e5100-d467-11eb-9163-5a2f98df027e.png)

编译加上这个就可以了

**Comment by leone424** [comment]
> > 看看有没有安装 wget-ssl 组件
> > 没有的话就安装上或编译时加上。
> > 或者等大佬改下 DDNS 脚本。
> 
> ![image](https://user-images.githubusercontent.com/43857401/123102601-d24e5100-d467-11eb-9163-5a2f98df027e.png)
> 
> 编译加上这个就可以了

按照此方法已解决，感谢！
