### ISSUE TITLE
编译时提示drivers/mmc/host/mtk-mmc/Kconfig不存在

### ISSUE THREAD

**Issue by huasuifengqu** [coolsnowwolf/lede#716]
scripts/kconfig/conf  --silentoldconfig Kconfig
net/sched/Kconfig:44: warning: menuconfig statement without prompt
drivers/mmc/host/Kconfig:903: can't open file "drivers/mmc/host/mtk-mmc/Kconfig"
make[7]: *** [scripts/kconfig/Makefile:40: silentoldconfig] Error 1
make[6]: *** [Makefile:521: silentoldconfig] Error 2

The present kernel configuration has modules disabled.
Type 'make config' and enable loadable module support.
Then build a kernel with module support enabled.

make[5]: *** [Makefile:1291: modules] Error 1
找过了，drivers/mmc/host下面没有mtk-mmc

**Comment by tuanqing** [comment]
同样的错误，大雕已经放弃mtk，😄

**Comment by coolsnowwolf** [comment]
已修复
