### ISSUE TITLE
自定义路由器xid的问题

### ISSUE THREAD

**Issue by hanben2007** [coolsnowwolf/lede#7164]
## 1.关于你要提交的问题
自定义路由器xid的问题

Q：是否搜索了issue (使用 "x" 选择)
搜索了，没有类似的issue

### (1) 具体问题
各位大佬好，受到https://koolshare.cn/thread-160119-1-1.html
这篇帖子启发，希望采用路由器伪装机顶盒的办法获取联通IPTV内网IP，这样也许可以访问回看的相关资源。
我使用的是软路由，按照帖子的模式重新编译了固件，但是发现了很奇怪的现象那就是：
**xid与设置的期望不同**
比如我希望Transaction ID:是0x6eeeb05c，转换为十进制是1861136476，我修改dhcpc.c，将xid赋值为1861136476。
装上软路由后，使用wireshark抓包DHCP请求，发现Transaction ID是0x5cb0ee6e！！，并非期望的值。
多次尝试赋值不同的xid发现如下规律：
1、每一个xid赋值对应一个Transaction ID
2、xid变大，Transaction ID不一定变大，好像毫无规律。
3、只要xid不变，Transaction ID就会一直不变。
我试了一些xid赋值与Transaction ID对照如下
xid                     Transaction ID:
61136476	Transaction ID: 0x5cdea403
861136476	Transaction ID: 0x5ce65333
1861136476	Transaction ID: 0x5cb0ee6e
2861136476	Transaction ID: 0x5c7a89aa
3338638259	Transaction ID: 0xb393ffc6
2167173706	Transaction ID: 0x4a722c81
3038638259	Transaction ID: 0xb3f01db5
2468586177	Transaction ID: 0xc1a22393
2167173707	Transaction ID: 0x4b722c81
2167173709	Transaction ID: 0x4d722c81
2167183709	Transaction ID: 0x5d992c81
2167193709	Transaction ID: 0x6dc02c81
2167194709	Transaction ID: 0x55c42c81
2167193809	Transaction ID: 0xd1c02c81
2167193710	Transaction ID: 0x6ec02c81
2167193711	Transaction ID: 0x6fc02c81

就是说，只要给定一个xid值，就对应一个Transaction ID
为了得到期望的Transaction ID，不可能穷举所有xid吧。。。。。。
请各位大佬看看是否能从代码层面分析一下为啥xid传递到dhcp请求时就变了呢？

另外有没有大佬知道DHCP中的
Option: (57) Maximum DHCP Message Size，以及
Option: (55) Parameter Request Lis
这两项如何自定义？

### (2) 路由器型号和固件版本

目前最新L大大的固件编译的

**Comment by Cathgao** [comment]
> 比如我希望Transaction ID:是0x6eeeb05c，转换为十进制是1861136476，我修改dhcpc.c，将xid赋值为1861136476。
> 装上软路由后，使用wireshark抓包DHCP请求，发现Transaction ID是0x5cb0ee6e！！，并非期望的值。

一眼就看出来是大小端问题...这都没看出来的吗。
`6e ee b0 5c`
`5c b0 ee 6e`
