### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by dalaoshi777** [coolsnowwolf/lede#7167]
ax6
---------
Patch failed!  Please fix /home/dalaoshi777/lede/target/linux/ipq807x/patches-5.10/600-qca-nss-ecm-support-CORE.patch!
make[4]: *** [Makefile:30: /home/dalaoshi777/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.44/.prepared_9e537d2b03d18cb5f3ce8ae622c9680c] Error 1
make[4]: Leaving directory '/home/dalaoshi777/lede/target/linux/ipq807x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/dalaoshi777/lede/target/linux'
time: target/linux/compile#16.37#5.96#16.90
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/dalaoshi777/lede'
make[1]: *** [target/Makefile:18: /home/dalaoshi777/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/dalaoshi777/lede'
make: *** [/home/dalaoshi777/lede/include/toplevel.mk:230：world] 错误 2

**Comment by ldy8182** [comment]
一样的错误

Applying /home/ldy8182/lede/target/linux/ipq807x/patches-5.10/600-qca-nss-ecm-support-CORE.patch using plaintext: 
patching file net/netfilter/nf_conntrack_proto_tcp.c
Hunk #1 FAILED at 32.
1 out of 1 hunk FAILED -- saving rejects to file net/netfilter/nf_conntrack_proto_tcp.c.rej
patching file include/linux/if_bridge.h
Hunk #1 succeeded at 60 with fuzz 2.
Hunk #2 succeeded at 161 (offset 3 lines).
patching file include/linux/if_vlan.h
patching file include/linux/netdevice.h
patching file include/net/ip6_route.h
patching file include/net/neighbour.h
patching file include/net/route.h
patching file net/8021q/vlan_core.c
patching file net/bridge/br_fdb.c
patching file net/bridge/br_if.c
Hunk #4 succeeded at 805 (offset 22 lines).
patching file net/bridge/br_private.h
patching file net/core/neighbour.c
patching file net/ipv4/fib_trie.c
patching file include/net/addrconf.h
patching file net/ipv6/addrconf.c
patching file net/ipv6/ndisc.c
patching file net/ipv6/route.c
Patch failed!  Please fix /home/ldy8182/lede/target/linux/ipq807x/patches-5.10/600-qca-nss-ecm-support-CORE.patch!
make[4]: *** [Makefile:30: /home/ldy8182/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.44/.prepared_a3ed2e287617e1646e3c258b1643a98f] Error 1
make[4]: Leaving directory '/home/ldy8182/lede/target/linux/ipq807x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/ldy8182/lede/target/linux'
time: target/linux/compile#2.19#15.92#12.70
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/ldy8182/lede'
make[1]: *** [target/Makefile:18: /home/ldy8182/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/ldy8182/lede'
make: *** [/home/ldy8182/lede/include/toplevel.mk:230: world] Error 2
