### ISSUE TITLE
大大，新的源码怎么没有tplink wdr6500 v2这个机型了？

### ISSUE THREAD

**Issue by jacelift** [coolsnowwolf/lede#7171]
大大，新的源码怎么没有tplink wdr6500 v2这个机型了？

**Comment by zpj7377327** [comment]
换个源码就行了，tp类很多都被移除了

**Comment by jacelift** [comment]
> 换个源码就行了，tp类很多都被移除了

换哪个源码？lienol的源码也是没有这个型号的，lean的源码之前是有tp这个型号的，最近更新后就没有了！！

**Comment by zpj7377327** [comment]
> > 换个源码就行了，tp类很多都被移除了
> 
> 换哪个源码？lienol的源码也是没有这个型号的，lean的源码之前是有tp这个型号的，最近更新后就没有了！！

换成coolsnowwolf/openwrt，lede里面这个了

**Comment by jacelift** [comment]
> > > 换个源码就行了，tp类很多都被移除了
> > 
> > 换哪个源码？lienol的源码也是没有这个型号的，lean的源码之前是有tp这个型号的，最近更新后就没有了！！
> 
> 换成coolsnowwolf/openwrt，lede里面这个了

这个是17.0版本的啊，之前有wdr6500的是21.0版本的，感觉时光倒流了(●—●)

**Comment by coolsnowwolf** [comment]
同步了官方的代码，tplink 4MB rom 系列都已经被删除了

**Comment by yjd** [comment]
选比较旧的版本编译

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/123840192-a0922a00-d940-11eb-8f70-4088e5758a97.png)

特别优待，重新添加了这个型号的支持，在 ATH79 里面

**Comment by jacelift** [comment]
> ![image](https://user-images.githubusercontent.com/31687149/123840192-a0922a00-d940-11eb-8f70-4088e5758a97.png)
> 
> 特别优待，重新添加了这个型号的支持，在 ATH79 里面

给力，↖(^ω^)↗

**Comment by yqxuezhe** [comment]
请问TPlink-WDR6500 千兆版怎么刷
