### ISSUE TITLE
nginx luci模式的问题

### ISSUE THREAD

**Issue by the55555day** [coolsnowwolf/lede#7191]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：选择 luci nginx 时不管是否选择带 ssl 功能，都会带 ssl ，而且强制跳转443端口没有开关（可以修改配置模板），强制跳转以后防火墙端口转发别的端口会出问题。
B：aria2选中以后，会强制选择ariang uhttpd，即使我选的是 luci nginx ，明明下面的ariang nginx的啊

nginx 比较好配置，希望大大能改进一下这块内容，谢谢。

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：不需要

**Comment by WYC-2020** [comment]
aria2 改成nginx 怕是很多人会疯，这个你可以自己改 吧依赖改下就完事的
