### ISSUE TITLE
新源码编译出来的竞斗云固件没有温度显示。

### ISSUE THREAD

**Issue by HUANGJHON** [coolsnowwolf/lede#7193]
![Screenshot_20210626_173349](https://user-images.githubusercontent.com/63879186/123508933-137f7480-d6a5-11eb-8339-1df04237090b.jpg)

**Comment by Boos4721** [comment]
![](https://i0.hdslb.com/bfs/album/98b0a3c62a3bed7b91fbfe7506748e313cc3a948.png)
?

**Comment by AmadeusGhost** [comment]
你把 WiFi 关掉就没有温度显示了。

**Comment by icsfy** [comment]
> 你把 WiFi 关掉就没有温度显示了。

我这里acrh17同样没有温度显示，wifi是开了的，看日志报错如下：
`
Sat Jun 26 18:50:40 2021 daemon.err uhttpd[3000]: awk: /sys/class/ieee80211/phy*/device/hwmon/hwmon*/temp1_input: No such file or directory
`

**Comment by Boos4721** [comment]
> > 你把 WiFi 关掉就没有温度显示了。
> 
> 我这里acrh17同样没有温度显示，wifi是开了的，看日志报错如下：
> `Sat Jun 26 18:50:40 2021 daemon.err uhttpd[3000]: awk: /sys/class/ieee80211/phy*/device/hwmon/hwmon*/temp1_input: No such file or directory`

![](https://i0.hdslb.com/bfs/album/d9d1bd9c6c6f360419e3f666feb37d4ba0a4178d.jpg)

**Comment by icsfy** [comment]
> > > 你把 WiFi 关掉就没有温度显示了。
> > 
> > 
> > 我这里acrh17同样没有温度显示，wifi是开了的，看日志报错如下：
> > `Sat Jun 26 18:50:40 2021 daemon.err uhttpd[3000]: awk: /sys/class/ieee80211/phy*/device/hwmon/hwmon*/temp1_input: No such file or directory`
> 
> ![](https://camo.githubusercontent.com/01ea06a71cdc26b6291b4a39c45f107e8ad7249f75cb6d802763999be975cdfa/68747470733a2f2f69302e6864736c622e636f6d2f6266732f616c62756d2f643964316264396336633666333630343139653366363636666562333764346261306134313738642e6a7067)

看了下，我这里没有hwmon这个目录：

```
root@OpenWrt:~# ls -A /sys/class/ieee80211/phy*/device
/sys/class/ieee80211/phy0/device:
aer_dev_correctable       device                    local_cpus                reset
aer_dev_fatal             devspec                   max_link_speed            resource
aer_dev_nonfatal          dma_mask_bits             max_link_width            resource0
ari_enabled               driver                    modalias                  revision
broken_parity_status      driver_override           msi_bus                   subsystem
class                     enable                    msi_irqs                  subsystem_device
config                    ieee80211                 net                       subsystem_vendor
consistent_dma_mask_bits  irq                       of_node                   uevent
current_link_speed        leds                      remove                    vendor
current_link_width        local_cpulist             rescan

/sys/class/ieee80211/phy1/device:
driver           driver_override  ieee80211        modalias         of_node          subsystem        uevent
root@OpenWrt:~#
```

**Comment by shikkoku** [comment]
不知默认有无选了autocore-arm

**Comment by minlang112** [comment]
我记得不是某些型号默认把温度监控去掉了么……提升首页显示的流畅性

**Comment by Boos4721** [comment]
> 我记得不是某些型号默认把温度监控去掉了么……提升首页显示的流畅性

https://github.com/coolsnowwolf/lede/blob/master/package/lean/autocore/files/arm/sbin/cpuinfo

**Comment by AmadeusGhost** [comment]
> 我记得不是某些型号默认把温度监控去掉了么……提升首页显示的流畅性

那个是换一种方式读取温度了，不是去掉了。
