### ISSUE TITLE
arm64系统下编译ucl-1.03 acconfig下config.guess文件版本过老

### ISSUE THREAD

**Issue by xiufeiwu** [coolsnowwolf/lede#7194]
建议更新ucl-1.03 acconfig下config.guess,文件版本是2004年的，使用苹果m1安装ubuntu server arm虚拟机编译的时候这个文件导致编译报错，需要手工替换成其他模块的新版本的config.guess

**Comment by coolsnowwolf** [comment]
你可以把 config.guess 适合 M1 编译的文件发上来，或者发个 PR
