### ISSUE TITLE
hello world ssr plus  公开 公示

### ISSUE THREAD

**Issue by jiatongwu** [coolsnowwolf/lede#7208]
vim ./feeds.conf.default
如果没有下面这一行 自己添加上
src-git helloworld https://github.com/fw876/helloworld

**Comment by Boos4721** [comment]
直接echo不就行了

**Comment by chobitsos** [comment]
这人有什么毛病？找个班上不行吗？在这里乱提什么issu？

**Comment by jiatongwu** [comment]
开源 自由的精神
we are gnu !!!

有些人 思想龌龊  没有开源 自由的精神

**Comment by jiatongwu** [comment]
> 这人有什么毛病？找个班上不行吗？在这里乱提什么issu？

你个垃圾   知道什么是自由软件吗？
