### ISSUE TITLE
ddns只有启动的第一次可以成功。其他时候都不行了。

### ISSUE THREAD

**Issue by 13810169** [coolsnowwolf/lede#7209]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
ddns只有创建的第一次成功，后续一直不行。
Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue
* 
### (2) 路由器型号和固件版本
x86_64 5.10.43内核版本
使用的是阿里云的ddns。不管用何种获取方式，都是一样的，只有第一次成功。后续还是这样。

### (3) 详细日志
 223848  info : Update successful - IP '2409:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx' send
 223849  info : Forced update successful - IP: '2409:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx' send
 223849       : Waiting 600 seconds (Check Interval)
 224849       : Detect registered/public IP
 224849       : #> /usr/bin/nslookup 马赛克.xyz  >/var/run/ddns/OpenWrt_WEB.dat 2>/var/run/ddns/OpenWrt_WEB.err
 224849  WARN : NO valid IP found
 224849  WARN : Get registered/public IP for '马赛克.xyz' failed - retry 1/0 in 60 seconds
 224949       : #> /usr/bin/nslookup 马赛克.xyz  >/var/run/ddns/OpenWrt_WEB.dat 2>/var/run/ddns/OpenWrt_WEB.err
 224949  WARN : NO valid IP found
 224949  WARN : Get registered/public IP for '马赛克.xyz' failed - retry 2/0 in 60 seconds
 225049       : #> /usr/bin/nslookup 马赛克.xyz  >/var/run/ddns/OpenWrt_WEB.dat 2>/var/run/ddns/OpenWrt_WEB.err

只有第一次成功，后续一直是这样的，已经跑到50/0了。都是重复的内容

**Comment by yjd** [comment]
新版不清楚，4月份以前的我这边用得好好的。日志有时候会有很多超时错误等。但不影响使用。

**Comment by lonelysoul** [comment]
阿里云的ddns怎么申请呀，不成功。现在用dynu的……

**Comment by missorforget** [comment]
DNS-服务器 填入一个ipv6 dns服务器
