### ISSUE TITLE
编译docker需要选哪些？

### ISSUE THREAD

**Issue by wxs-dev** [coolsnowwolf/lede#7210]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：选了luci-app-docker之后编译失败了，还需要选哪些吗？第一次编译doker

### (2) 路由器型号和固件版本

A：N1

**Comment by gztingting** [comment]
默认已经把依赖勾选了吧，或者在utilities里选择docker，dockerd，dockerd里面加上一些内核、网络、存储选型。

**Comment by birdmanwings** [comment]
请问下编译的时候勾选了luci-app-docker，使用/etc/docker-web的时候还是显示docker: not found，是还需要勾选配置什么呢

> 默认已经把依赖勾选了吧，或者在utilities里选择docker，dockerd，dockerd里面加上一些内核、网络、存储选型。

**Comment by Dimitri2020007** [comment]
docker需要luci-app-docker、luci-lib-docker、utilities里选择docker，dockerd，dockerd里面加上一些内核、网络、存储选型。

**Comment by wxs-dev** [comment]
> docker需要luci-app-docker、luci-lib-docker、utilities里选择docker，dockerd，dockerd里面加上一些内核、网络、存储选型。

![image](https://user-images.githubusercontent.com/58886165/123802068-74b17d00-d91d-11eb-8b97-74e24b629041.png)
我只有这几个，没见到内核、网络、存储选型，这些要在哪选？

**Comment by acooler15** [comment]
> > docker需要luci-app-docker、luci-lib-docker、utilities里选择docker，dockerd，dockerd里面加上一些内核、网络、存储选型。
> 
> ![image](https://user-images.githubusercontent.com/58886165/123802068-74b17d00-d91d-11eb-8b97-74e24b629041.png)
> 我只有这几个，没见到内核、网络、存储选型，这些要在哪选？

同问

**Comment by wxs-dev** [comment]
已解决，删掉了lede重新拉项目，选择luci-app-docker即可
