### ISSUE TITLE
[提醒]关于AX6 AX3600升级注意

### ISSUE THREAD

**Issue by kisaragychihaya** [coolsnowwolf/lede#7220]
commit b9089dbf09ce0c1e8769f43434e7cd9195f69190 之前的固件请勿通过web页面升级，升级必砖，我冒死试了下 可以用sysupgrade 命令 成功升级到带web升级功能的版本

**Comment by sxf5487** [comment]
我想请问下AX6官方固件，已经开启了ssh，如何刷啊，没有一个完整的教程（都是刷qsdk的）

**Comment by kisaragychihaya** [comment]
> 我想请问下AX6官方固件，已经开启了ssh，如何刷啊，没有一个完整的教程（都是刷qsdk的）

qsdk下根据教程修改好分区ubiformat /dev/mtd13 -y -f /tmp/xxxxxx.ubi

**Comment by dubinghai** [comment]
> 改一个参数即可在以前不能 Web 升级的固件页面升级成功，/lib/upgrade/platform.sh 文件，"$part_num" -eq "0" 改为 "$part_num" -eq "1"

ax3600里面没看见$part_num" -eq "0

**Comment by lqx1981** [comment]
> > 改一个参数即可在以前不能 Web 升级的固件页面升级成功，/lib/upgrade/platform.sh 文件，"$part_num" -eq "0" 改为 "$part_num" -eq "1"
> 
> ax3600里面没看见$part_num" -eq "0

我也是找不到啊
