### ISSUE TITLE
5.10.46 DNS自义定隔一段时间就断网

### ISSUE THREAD

**Issue by 279437541** [coolsnowwolf/lede#7224]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
5.10.46版本 DNS 设置自定义的话，隔一段时间久断网了，需要重启路由器才恢复！
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Dimitri2020007** [comment]
有相同情况 +1
