### ISSUE TITLE
大雕优化下adbyby，每次重启路由器，负载就较高。

### ISSUE THREAD

**Issue by sirfromprc** [coolsnowwolf/lede#723]
大雕优化下adbyby，重启路由器后，5分钟负载在1左右，且长时间下不去。需要手工重启下adbyby，负载才会逐渐降低，然后恢复正常。top命令查看，adbyby的cpu占用也不大。就是负载很大。

**Comment by ldy8182** [comment]
我手动重启adbyby负载也不降低.top命令也看不出哪个进程占用cpu高.
![1](https://user-images.githubusercontent.com/24645236/47292782-aafdb100-d63a-11e8-98ac-91453d861808.png)
![2](https://user-images.githubusercontent.com/24645236/47292783-aafdb100-d63a-11e8-97e0-488a06c14d3e.png)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2501339/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2501340/default.txt)

**Comment by ldy8182** [comment]
开内存模式就没问题了,感谢大雕!

**Comment by hcym** [comment]
最近新版本的去广告脚本又恢复正常使用，自然不用这些ad插件，泪流满面
