### ISSUE TITLE
竞斗云ipq40xx-p2w_r619ac-128m中DDNS没有aliyun的选项啦

### ISSUE THREAD

**Issue by may1051** [coolsnowwolf/lede#7234]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
竞斗云ipq40xx-p2w_r619ac-128m中DDNS没有aliyun的选项啦
### (1) 具体问题

A：竞斗云ipq40xx-p2w_r619ac-128m中DDNS没有aliyun的选项啦

### (2) 路由器型号和固件版本

A：ipq40xx-p2w_r619ac-128m，固件编译时间：2021-06-30 17：00

### (3) 详细日志

A：

**Comment by felixxiao99** [comment]
R2S也有这个问题，DDNS没有aliyun的选项，DNSPOD也没有

**Comment by coolsnowwolf** [comment]
自己选上嘛
