### ISSUE TITLE
tp-link-wr703n无限重启

### ISSUE THREAD

**Issue by afeiy** [coolsnowwolf/lede#7242]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：无论是在老版本的web界面不保留配置升级，或是进breed界面升级，均是同样的无限重启。如果进breed界面刷入4.14内核老板则正常。

### (2) 路由器型号和固件版本

A：tp-link-wr703n

### (3) 详细日志

A：进步了luci界面，没有获取到日志。

**Comment by coolsnowwolf** [comment]
703n 有很多个型号， v2 v3 和国外版并不一致

**Comment by afeiy** [comment]
> 703n 有很多个型号， v2 v3 和国外版并不一致

我是硬改的16m，一直用这个源码的v1几年了都没问题，就是这次内核升级后才出现的。
另：刚跑了一个您openwrt库的固件出来，测试也是可用的。

**Comment by Lumia-ESFD** [comment]
我和你一样的问题，硬改16M，总是无限重启，搞了几个星期了没有解决。能留个联系方式给个学习的机会么？我的企鹅290283721

**Comment by afeiy** [comment]
大佬不修这个我就没办法解决，已经改用稳定版openwrt库。
