### ISSUE TITLE
编译完了最新的，固件文件去哪了？？

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#7243]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
在原来的路径下没有啊?? openwrt-x86-64-generic-squashfs-combined.img
有openwrt-x86-64-generic-squashfs-combined-efi.img
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by db-one** [comment]
openwrt-x86-64-generic-squashfs-combined-efi.img
就是你需要的固件

**Comment by db-one** [comment]
x86/x64 默认不再生成 MBR 的镜像（ EFI 镜像也支持 CSM BIOS 方式启动了）

**Comment by Jason6111** [comment]
可以在编译时打开 在target images 里面

**Comment by qqsir-dev** [comment]
谢谢
