### ISSUE TITLE
AX6 sirq占用高的问题

### ISSUE THREAD

**Issue by ldy8182** [coolsnowwolf/lede#7250]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
没有搜到
## 2. 详细叙述
AX6 sirq占用高的问题
### (1) 具体问题

A：开启Turbo ACC 网络加速设置-软件流量分载-全锥形 NAT，sirq占用更高，关闭后会降低一些

### (2) 路由器型号和固件版本

A：Redmi AX6  OpenWrt R21.7.1.100 / LuCI Master (git-21.181.13804-f7b5f6d)

### (3) 详细日志

A：
![QQ图片20210702133326](https://user-images.githubusercontent.com/24645236/124225499-1f05ec00-db3a-11eb-8bff-78648418a09f.png)
![QQ截图20210702133512](https://user-images.githubusercontent.com/24645236/124225619-5bd1e300-db3a-11eb-85fd-9abc9149f1af.png)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/6752305/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/6752306/default.txt)

**Comment by ldy8182** [comment]
很可能是NFT-QoS这个软件的问题，我关掉后重启路由器就正常了

**Comment by coolsnowwolf** [comment]
nss 不兼容 ntf

**Comment by ldy8182** [comment]
感谢大雕，我把这个软件去掉~

**Comment by xsm1997** [comment]
@ldy8182 请问您sirq高的问题是怎么解决的？我没编译NFT-QoS这个软件，软转发时sirq也很高，有20%多，且软转发只有300M左右。

**Comment by ldy8182** [comment]
qos类的都去掉，流量监控也去掉

**Comment by xsm1997** [comment]
@ldy8182 您现在使用时sirq大概是多少呢？

**Comment by ldy8182** [comment]
10%-15%
