### ISSUE TITLE
全新环境全新编译x86   qbittorrent报错

### ISSUE THREAD

**Issue by c939984606** [coolsnowwolf/lede#7253]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A： 全新环境全新编译，qbittorrent报错

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：check_data_file_clashes: Package qbittorrent wants to install file /home/kcui/Openwrt/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/qbittorrent-nox
But that file is already provided by package * qBittorrent-static
opkg_install_cmd: Cannot install package qbittorrent.
make[2]: *** [package/Makefile:70: package/install] Error 255

**Comment by c939984606** [comment]
commit 01e4998f6d4e9604ab101a897acae7a52f20a991

package/lean/qBittorrent-static/Makefile


define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(DL_DIR)/qbittorrent-nox $(1)/usr/bin
endef

**Comment by sheno-Tyes** [comment]
解决了？

**Comment by wangyang8284** [comment]
好像没解决，还是报错

**Comment by openwrt-try** [comment]
> commit [01e4998](https://github.com/coolsnowwolf/lede/commit/01e4998f6d4e9604ab101a897acae7a52f20a991)
> 
> package/lean/qBittorrent-static/Makefile
> 
> define Package/$(PKG_NAME)/install
> $(INSTALL_DIR) $(1)/usr/bin
> $(INSTALL_BIN) $(DL_DIR)/qbittorrent-nox $(1)/usr/bin
> endef

内容跟这上面的一样，
还是报这个错误，不管选不选luci-app-qBittorrent，
求指点

**Comment by sheno-Tyes** [comment]
需要在network->bittorrent,取消勾选qbittorrent或qbittorrent-static,选一个

**Comment by wangyang8284** [comment]
> 需要在network->bittorrent,取消勾选qbittorrent或qbittorrent-static,选一个

感谢感谢！
