### ISSUE TITLE
use -f to force

### ISSUE THREAD

**Issue by lariboo** [coolsnowwolf/lede#7256]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

![0101](https://user-images.githubusercontent.com/36104046/124275175-bbe57b00-db74-11eb-97f8-d0a301788edf.png)

本地ubuntu 18.04.4 LTS编译x86 64固件，执行make menuconfig后提示WARNING: Not overriding core package 'adguardhome'; use -f to force

'adguardhome'位置有时为其他，如v2ray-core、v2ray-plugin等。

想请教下大佬， make menuconfig -f、 make -f menuconfig不可行，-f该如何使用？

### (2) 路由器型号和固件版本

x86 64

**Comment by lariboo** [comment]
![0101](https://user-images.githubusercontent.com/36104046/124275112-a6705100-db74-11eb-813a-94e2727e21d2.png)

**Comment by XiaoliChan** [comment]
./script/feed update -a && ./script/feed install -a -f
