### ISSUE TITLE
ac58u 编译报错

### ISSUE THREAD

**Issue by barton0426** [coolsnowwolf/lede#7257]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：编译报错失败

### (2) 路由器型号和固件版本

A：ac58u 最新commit

### (3) 详细日志

A： * check_data_file_clashes: Package kmod-ath10k-ct-smallbuffers wants to install file /home/runner/work/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/lib/modules/5.4.128/ath10k_core.ko
9033
	But that file is already provided by package  * kmod-ath10k-ct
9034
 * check_data_file_clashes: Package kmod-ath10k-ct-smallbuffers wants to install file /home/runner/work/lede/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/lib/modules/5.4.128/ath10k_pci.ko
9035
	But that file is already provided by package  * kmod-ath10k-ct
9036
 * opkg_install_cmd: Cannot install package kmod-ath10k-ct-smallbuffers.
9037
make[2]: *** [package/Makefile:70: package/install] Error 255
9038
make[1]: *** [package/Makefile:111: /home/runner/work/lede/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
9039
make: *** [/home/runner/work/lede/lede/include/toplevel.mk:230: world] Error 2
9040
make[2]: Leaving directory '/home/runner/work/lede/lede'
9041
make[1]: Leaving directory '/home/runner/work/lede/lede'
9042
Error: Process completed with exit code 2.

**Comment by coolsnowwolf** [comment]
重复了， ath10k 和 ath10k-ct 只能选一个

**Comment by barton0426** [comment]
> 重复了， ath10k 和 ath10k-ct 只能选一个

感谢大雕修复
