### ISSUE TITLE
DNSFilter 在添加3个规则时候出现问题

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#7260]
在添加下面的规则后出现不能运行，如图
![image](https://user-images.githubusercontent.com/43886952/124302305-9d42ac80-db93-11eb-9ff3-d60531b88bcc.png)
系统对应日志
Sat Jul  3 00:10:56 2021 daemon.err uhttpd[3738]: Downloading 'https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/adblock-for-dnsmasq.conf'
Sat Jul  3 00:10:58 2021 daemon.info dnsmasq[12256]: Connected to system UBus
Sat Jul  3 00:11:01 2021 daemon.err uhttpd[3738]: Connecting to 104.16.85.20:443
Sat Jul  3 00:11:01 2021 daemon.err uhttpd[3738]: Writing to '/tmp/ad_tmp/ad_new.conf'
Sat Jul  3 00:11:02 2021 daemon.err uhttpd[3738]: 
/tmp/ad_tmp/ad_new.c  1115k --:--:-- ETA
Sat Jul  3 00:11:02 2021 daemon.err uhttpd[3738]: Download completed (1142776 bytes)
Sat Jul  3 00:11:03 2021 daemon.err uhttpd[3738]: Downloading 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
Sat Jul  3 00:11:03 2021 daemon.err uhttpd[3738]: Connecting to 185.199.110.153:443
Sat Jul  3 00:11:04 2021 daemon.err uhttpd[3738]: Writing to '/tmp/ad_tmp/ad_new.conf'
Sat Jul  3 00:11:04 2021 daemon.err uhttpd[3738]: 
/tmp/ad_tmp/ad_new.c 100% |*******************************|   717k  0:00:00 ETA
Sat Jul  3 00:11:04 2021 daemon.err uhttpd[3738]: Download completed (734446 bytes)
Sat Jul  3 00:11:07 2021 daemon.err uhttpd[3738]: sh: write error: Broken pipe
Sat Jul  3 00:11:27 2021 daemon.err uhttpd[3738]: Downloading 'https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/adblock-for-dnsmasq.conf'
Sat Jul  3 00:11:32 2021 daemon.err uhttpd[3738]: Connecting to 104.16.86.20:443
Sat Jul  3 00:11:32 2021 daemon.err uhttpd[3738]: Writing to '/tmp/ad_tmp/ad_new.conf'
Sat Jul  3 00:11:33 2021 daemon.err uhttpd[3738]:
Sat Jul  3 00:11:33 2021 daemon.err uhttpd[3738]: Download completed (1142776 bytes)
Sat Jul  3 00:11:34 2021 daemon.err uhttpd[3738]: Downloading 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
Sat Jul  3 00:11:34 2021 daemon.err uhttpd[3738]: Connecting to 185.199.111.153:443
Sat Jul  3 00:11:34 2021 daemon.err uhttpd[3738]: Writing to '/tmp/ad_tmp/ad_new.conf'
Sat Jul  3 00:11:35 2021 daemon.err uhttpd[3738]: 
/tmp/ad_tmp/ad_new.c 100% |*******************************|   717k  0:00:00 ETA
Sat Jul  3 00:11:35 2021 daemon.err uhttpd[3738]: Download completed (734446 bytes)
Sat Jul  3 00:11:36 2021 daemon.err uhttpd[3738]: Downloading 'https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt'
Sat Jul  3 00:11:41 2021 daemon.err uhttpd[3738]: Connecting to 176.9.122.53:443
Sat Jul  3 00:11:42 2021 daemon.err uhttpd[3738]: Writing to '/tmp/ad_tmp/ad_new.conf'
Sat Jul  3 00:11:44 2021 daemon.err uhttpd[3738]: 
/tmp/ad_tmp/ad_new.c  45% |**************                 |   847k  0:00:01 ETA
/tmp/ad_tmp/ad_new.c 100% |*******************************|  1858k  0:00:00 ETA
Sat Jul  3 00:11:44 2021 daemon.err uhttpd[3738]: Download completed (1902784 bytes)
Sat Jul  3 00:11:47 2021 daemon.err uhttpd[3738]: sh: write error: Broken pipe

貌似是写入时候错误造成的

**Comment by naoki66** [comment]
老老实实的换成Adbyby Plus+ ，大佬出品，非常稳
