### ISSUE TITLE
OpenVPN界面缺少“上传文件”专栏

### ISSUE THREAD

**Issue by yz2002** [coolsnowwolf/lede#7268]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：OpenVPN界面缺少“上传文件”专栏导致无法上传配置文件

### (2) 路由器型号和固件版本

A：Newifi D2

### (3) 详细日志

A：
LEDE:
![LEDE](https://user-images.githubusercontent.com/55992481/124361669-c54d1100-dc62-11eb-9046-9f77f4f86874.PNG)
官方:
![OpenWrt](https://user-images.githubusercontent.com/55992481/124361741-3bea0e80-dc63-11eb-9800-a93086cb66ca.PNG)

**Comment by shikkoku** [comment]
两者luci版本就不一样

**Comment by yz2002** [comment]
都是lua的版本 L大的很久没有更新了
