### ISSUE TITLE
开启DNS缓存后路由器负载很高，导致路由器不可用

### ISSUE THREAD

**Issue by slipdaly** [coolsnowwolf/lede#7269]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
![image](https://user-images.githubusercontent.com/20242451/124368039-65209400-dc8f-11eb-8b27-fdad14a058fd.png)
DNS解析方式这个是新增的功能吗？开启这个后路由器负载很高，高到最终不可用状态。

### (1) 具体问题

A：开启DNS缓存后路由器负载很高，导致路由器不可用。

### (2) 路由器型号和固件版本

A：
型号：Phicomm PSG1218 rev.A
固件版本：OpenWrt R21.7.1.100 / LuCI Master (git-21.181.13804-f7b5f6d)
内核版本 ：5.4.128

### (3) 详细日志

A：需要什么日志

**Comment by qqsir-dev** [comment]
旧版的Turbo ACC里的DNS Caching设置的是内网 AD Guard Home的IP，新版这样就不行，而且不改设置不打开也不行(不能上网)，一定要用公网DNS才可以，这是问题还是变化? 求解？

**Comment by fuokgfw** [comment]
这两天把两个加速插件合并之后如果开启dns加速，SSR根本就无法使用，也是蛋疼的，如果在DHCP中取消勾选忽略本地文件就可以，重启之后依旧会自动勾选，没办法只能停用加速了

**Comment by minlang112** [comment]
> 如果开启dns加速，SSR根本就无法使用

并未发现“如果开启dns加速，SSR根本就无法使用”的情况，建议详细描述一下问题

**Comment by hxlls** [comment]
重新更新下系统，不要保存配置，这个情况我也遇到过，不保存配置更新之后在手动设置一次没有在出现，疑似残留配置引起的故障

**Comment by fuokgfw** [comment]
直接重新编译的固件，没保存设置，都遇到这问题，没办法，系统日志中找不到问题，DNS加速直接禁用了就行了

**Comment by xcf13363175** [comment]
红米 AX6 编译最新源码固件遇到相同的情况，去掉DNS加速问题解决。

**Comment by slipdaly** [comment]
> 重新更新下系统，不要保存配置，这个情况我也遇到过，不保存配置更新之后在手动设置一次没有在出现，疑似残留配置引起的故障

不保存配置，使用breed刷入，问题依旧，目前去掉了DNS加速。

**Comment by qpzr** [comment]
> > 重新更新下系统，不要保存配置，这个情况我也遇到过，不保存配置更新之后在手动设置一次没有在出现，疑似残留配置引起的故障
> 
> 不保存配置，使用breed刷入，问题依旧，目前去掉了DNS加速。

我的就更直接了，简单粗暴，哈哈
sed -i 's/+pdnsd-alt/+kmod-fast-classifier +kmod-ipt-offload/g' package/lean/luci-app-turboacc/Makefile

**Comment by eva2021hd** [comment]
小娱c5也碰到这个问题。不能上网，luci进不去。家里只能重启。
今天人在碰到这个故障，ssh到路由top查看，发现dnscache占用25%，状态是僵死（z）
8月4日编译
