### ISSUE TITLE
升级5.10内核后发现的2个关于插件问题

### ISSUE THREAD

**Issue by tone88** [coolsnowwolf/lede#7271]
## 升级5.10内核后发现的2个小问题。

 1、WatchCat设置了ping主机地址，但是在测试的时候仍然是ping的8.8.8.8，而且在刷入固件时这个应用的luci界面里没有任何配置，查看配置文件里面却是有的。
2、nlbwmon（实时流量监测）插件报错：
daemon.err nlbwmon[4257]:Netlink receive failure: Out of memory
daemon.err nlbwmon[4257]: Unable to dump conntrack: No buffer space available
大概每3-4个小时就会出现一次这个报错日志。
机器是x86不存在内存不足的问题。

### (3) 详细日志
![Screenshot_20210704-071030](https://user-images.githubusercontent.com/47731895/124369073-6c996a80-dc9a-11eb-9b76-2323146e8822.jpg)

**Comment by PyXiaoxin** [comment]
#7219 可以参考下

**Comment by tone88** [comment]
> #7219 可以参考下

将提交时间设置为3H后  没有再出现报错日志了。

WatchCat的问题难道没有同学遇到吗？
