### ISSUE TITLE
qBittorrent 4.3.6 重启后，已完成种子会从0进度重新开始下载

### ISSUE THREAD

**Issue by wukaisky** [coolsnowwolf/lede#7272]
qBittorrent 相关包移植到OpenWrt 21.02上编译运行，目标设备：x64软路由。
TrueNAS的挂载目录为/mnt/data0/qBittorrent，开了ACL权限控制
openwrt挂载这个目录到openwrt的/mnt/qBittorrent下
openwrt里qb我设置配置文件放在/mnt，下载目录在/mnt/qBittorrent/done，临时目录在/mnt/qBittorrnet/incomplete/目录，以root用户运行

qBittorrent 4.3.6，qtbase 5.15，qttools 5.15，rblibtorrent 1.2.14。
如果下载是分成“完成”（done）与“未完成”（incomplete）文件夹，qb每次启动都会把已完成的重新下载；
如果下载只是一个文件夹，qb每次启动都会重新校验下载文件夹的文件（包括已经完成下载的）。

**Comment by coolsnowwolf** [comment]
qbt 这部分的机制无更改，请用本地文件系统测试

**Comment by PyXiaoxin** [comment]
#7219 可以参考下

**Comment by wukaisky** [comment]
我试了openwrt挂载本地文件系统，qbittorrent运行正常了
