### ISSUE TITLE
京东二维码用手机信号无法更新

### ISSUE THREAD

**Issue by Jason6111** [coolsnowwolf/lede#7275]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：京东插件扫二维码只有在同wifi下正常 用手机信号扫码无法更新

### (2) 路由器型号和固件版本

A：x86 21.7.1.100

### (3) 详细日志

A：

**Comment by kilo1220** [comment]
我也遇到了

**Comment by Jason6111** [comment]
已经解决请关闭

**Comment by kilo1220** [comment]
> 已经解决请关闭

请问是怎么解决的？

**Comment by Jason6111** [comment]
> > 已经解决请关闭
> 
> 请问是怎么解决的？

抱歉 是我自己搞错了 大早上用的wifi 没睡醒

**Comment by Jason6111** [comment]
> > 已经解决请关闭
> 
> 请问是怎么解决的？

只能等大神或源库更新了
