### ISSUE TITLE
编译dw33d nor失败

### ISSUE THREAD

**Issue by screenshot-zz** [coolsnowwolf/lede#7277]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：编译dw33d nor失败  能生成sysupgrade.bin  没有 breed-factory.bin

### (2) 路由器型号和固件版本

A：dw33d

### (3) 详细日志

A：cp /media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/tmp/openwrt-ath79-nand-domywifi_dw33d-nor-squashfs-sysupgrade.bin /media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/bin/targets/ath79/nand/openwrt-ath79-nand-domywifi_dw33d-nor-squashfs-sysupgrade.bin
Makefile:101: *** Missing Build/prepad-okli-kernel.  Stop.
make[5]: Leaving directory '/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/target/linux/ath79/image'
make[4]: *** [Makefile:20: install] Error 2
make[4]: Leaving directory '/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/target/linux/ath79'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/target/linux'
time: target/linux/install#46.94#11.38#55.12
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/install] Error 1
make[2]: Leaving directory '/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede'
make[1]: *** [target/Makefile:19: /media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/staging_dir/target-mips_24kc_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede'
make: *** [/media/halo/0787a116-8348-46bd-ba36-7696c0fd9d92/lede/include/toplevel.mk:230: world] Error 2

**Comment by coolsnowwolf** [comment]
fixed
