### ISSUE TITLE
酸酸乳检查状态页面 google检查失败，但实际是通的，应该是bug

### ISSUE THREAD

**Issue by isSuperman** [coolsnowwolf/lede#7279]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Jason6111** [comment]
我的没遇见过 用的是5.10.46 R21.7.1.100
