### ISSUE TITLE
ntfs3g download failed - newifi-d2/wrt1200ac

### ISSUE THREAD

**Issue by rshi0212** [coolsnowwolf/lede#7281]
ntfs3g download failed - gived up

**Comment by rshi0212** [comment]
编译可以完成。

**Comment by coolsnowwolf** [comment]
早就不需要这个驱动了

**Comment by rshi0212** [comment]
哦，不需要了是吧，但是编译过程中还是尝试下载并显示下载失败

在 2021/7/5 16:24, coolsnowwolf 写道:

**Comment by tone88** [comment]
> 早就不需要这个驱动了

大雕，WatchCat的配置问题有空的时候修复下，辛苦了！
