### ISSUE TITLE
请求弱信号剔除增加阈值手动设置功能

### ISSUE THREAD

**Issue by hxlls** [coolsnowwolf/lede#729]
8.19版本中WIFI加入了弱信号剔除，这个十分好，是否能再增加弱信号剔除的阈值手动设置功能呢？

**Comment by mcucore** [comment]
强烈支持，弱信号剔除和弱信号拒接连接功能很实用！

**Comment by jw10126121** [comment]
强烈支持，弱信号剔除和弱信号拒接连接功能很实用！
