### ISSUE TITLE
X86 32系统5.10.46内核防火墙端口转发失效

### ISSUE THREAD

**Issue by xcf13363175** [coolsnowwolf/lede#7292]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
 [x] 没有类似的issue

### (1) 具体问题

A：3389端口转发无效，使用socat转发成功。重置系统重新配置一样无效。

### (2) 路由器型号和固件版本

A：
<html>
<body>

主机名 | OpenWrt
-- | --
主机型号 | Genuine Intel(R) CPU N270 @ 1.60GHz : 1 Core 2 Thread (CpuMark : 5413.482956 Scores)
CPU 信息 | 1596.239 MHz +32.0°C (crit = +90.0°C)
固件版本 | OpenWrt R21.7.1.100 / LuCI Master (git-21.186.34938-b34c524)
内核版本 | 5.10.46

</body>
</html>

### (3) 详细日志

A：无

**Comment by coolsnowwolf** [comment]
3389 需要关闭 Flow 加速，用 SFE
