### ISSUE TITLE
最新源码编译固件，路由器不能保存配置

### ISSUE THREAD

**Issue by L-vivi** [coolsnowwolf/lede#7294]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：最新源码编译后，路由器固件不能保存配置

### (2) 路由器型号和固件版本

A：AX6

### (3) 详细日志

A：

**Comment by xsm1997** [comment]
AX6最新源码编译，没有遇到不能保存配置的问题。尝试干净编译固件呢？

**Comment by xsm1997** [comment]
AX6最新源码编译，没有遇到不能保存配置的问题。尝试干净编译固件呢？

**Comment by L-vivi** [comment]
> AX6最新源码编译，没有遇到不能保存配置的问题。尝试干净编译固件呢？

尝试rm -rf ./tmp && rm -rf .config重新配置menuconfig不行
回退到commit 6ad4588a9b4f15ee5e526adf006d11c9dabc564c重新编译后恢复正常

**Comment by kisaragychihaya** [comment]
干净编译最好是make distclean

**Comment by zwillhill** [comment]
用actions云编译吧，每次都是全新环境
