### ISSUE TITLE
8125网卡驱动高负载场景下会断流

### ISSUE THREAD

**Issue by MrEsquire** [coolsnowwolf/lede#7300]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
网卡高负载场景下,本地客户端电脑会直接断网,显示无网络链接,大概5秒左右会恢复
本地客户端和路由器都是用的8125网卡,此问题是刷了最新的内核固件才出现.
断流时,其他网口/网卡都正常工作.仅8125出现断流.
客户端的8125插在i350上高负载场景也不会出现断流.
只有客户端的8125插在路由器的8125网卡,协商速率在2.5G才会出现断流
(而且有一点很奇怪,客户端的i211网卡插在路由器的8125网口上时,协商速率最高只有100M,客户端强行指定1G速率时会断网)
**以下是下载时流量突然归零,网络显示未连接的截图**
![`S2CSB(EUO()L@AL~ 4GHDS](https://user-images.githubusercontent.com/20885702/124649671-5faf8d80-decb-11eb-9869-3d04611bb1e0.png)

### (1) 具体问题

A：8125网卡断流

### (2) 路由器型号和固件版本

A：系统:OpenWrt R21.7.1.100 / LuCI Master (git-21.181.13804-f7b5f6d)
      宿主配置: esxi 7.0 Update 2
                      i5-10600
                      i350t4
                      8125
      路由配置:15-10600 (分了6核心 cpumark 18万2,同样的配置比上个内核分数低了2万,上个内核跑分20万5千左右) 
                      i350 x1(vmnext驱动)
                      i350 x3(直通)
                      8125 x1(直通)
### (3) 详细日志

A：
Wed Jul  7 02:41:23 2021 kern.info kernel: [164995.777218] r8125: eth4: link down
Wed Jul  7 02:41:23 2021 daemon.notice netifd: Network device 'eth4' link is down
Wed Jul  7 02:41:23 2021 kern.info kernel: [164995.952553] br-lan: port 4(eth4) entered disabled state
Wed Jul  7 02:41:31 2021 kern.info kernel: [165003.263750] r8125: eth4: link up
Wed Jul  7 02:41:31 2021 kern.info kernel: [165003.264126] br-lan: port 4(eth4) entered blocking state
Wed Jul  7 02:41:31 2021 daemon.notice netifd: Network device 'eth4' link is up
Wed Jul  7 02:41:31 2021 kern.info kernel: [165003.264492] br-lan: port 4(eth4) entered forwarding state
Wed Jul  7 02:44:01 2021 daemon.notice netifd: Network device 'eth4' link is down
Wed Jul  7 02:44:01 2021 kern.info kernel: [165153.398364] br-lan: port 4(eth4) entered disabled state
Wed Jul  7 02:44:01 2021 kern.info kernel: [165153.545970] r8125: eth4: link down
Wed Jul  7 02:44:05 2021 kern.info kernel: [165157.492816] r8125: eth4: link up
Wed Jul  7 02:44:05 2021 kern.info kernel: [165157.493163] br-lan: port 4(eth4) entered blocking state
Wed Jul  7 02:44:05 2021 daemon.notice netifd: Network device 'eth4' link is up
Wed Jul  7 02:44:05 2021 kern.info kernel: [165157.493486] br-lan: port 4(eth4) entered forwarding state

**Comment by EnnawYang** [comment]
我的是8125b，没有发现这个问题，可以看下你的bios设置 `ASPM` 有没有关闭

**Comment by MrEsquire** [comment]
> 我的是8125b，没有发现这个问题，可以看下你的bios设置 `ASPM` 有没有关闭

今晚我回家再排查下
