### ISSUE TITLE
DNSfilter添加规则问题。

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#7301]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：DNSFilter只添加一条过滤规则正常，添加多条规则后不能打开网页。

### (2) 路由器型号和固件版本

A：OpenWrt R21.7.1.100 / LuCI Master (git-21.186.34938-b34c524)

### (3) 详细日志

A：

**Comment by zwillhill** [comment]
是规则合并功能不完善（主要是各个第三方规则本身有很多特殊字符），造成合并后的规则以特殊字符开头，dnsmasq无法识别无法工作 。 #7246 
俩作者俩版本都存在这个问题
small-5的adblock-plus有作者维护合并的规则，但随插件一起开启，不能只开订阅规则。
garypang13的dnsfilter不内建规则，第三方订阅可随意组合。
