### ISSUE TITLE
额外的 HOSTS 文件配置不生效

### ISSUE THREAD

**Issue by slipdalysmall** [coolsnowwolf/lede#7302]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：额外的 HOSTS 文件配置不生效，配置完成后ping github.com没映射到配置文件中的地址，将配置文件内容添加到/etc/hosts中是生效的。

<img width="455" alt="额外hosts1" src="https://user-images.githubusercontent.com/20242451/124679874-d793ad00-def7-11eb-8f6b-9c1e13adf0b1.PNG">
<img width="389" alt="额外hosts2" src="https://user-images.githubusercontent.com/20242451/124680015-1cb7df00-def8-11eb-9a8f-0261e52e076a.PNG">

### (2) 路由器型号和固件版本

A：
型号：Phicomm PSG1218 rev.A
固件版本：OpenWrt R21.7.1.100 / LuCI Master (git-21.181.13804-f7b5f6d)
内核版本 ：5.4.128

### (3) 详细日志

A：
/etc/init.d/dnsmasq restart返回udhcpc: no lease, failing
<img width="273" alt="额外hosts3" src="https://user-images.githubusercontent.com/20242451/124680168-686a8880-def8-11eb-9fec-ca0a24150e50.PNG">

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/124689279-cef8a200-df0a-11eb-812f-d6e83c6236f9.png)
实测没问题，建议自己检查

**Comment by slipdaly** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/124689279-cef8a200-df0a-11eb-812f-d6e83c6236f9.png)
> 实测没问题，建议自己检查，图片上应该能看明白

是我使用的Adbyby Plus+ 有冲突导致的么，我这里确实是不行

**Comment by slipdalysmall** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/124689279-cef8a200-df0a-11eb-812f-d6e83c6236f9.png)
> 实测没问题，建议自己检查，图片上应该能看明白

是我使用的Adbyby Plus+ 有冲突导致的么，我这里确实是不行

**Comment by slipdalysmall** [comment]
> ![image](https://user-images.githubusercontent.com/43886952/124689279-cef8a200-df0a-11eb-812f-d6e83c6236f9.png)
> 实测没问题，建议自己检查，图片上应该能看明白

找到问题了，文件权限没对，权限改为644就OK了，感谢
