### ISSUE TITLE
新路由3 内核5.4.128编译出来无线设置界面有bug

### ISSUE THREAD

**Issue by Thanf-code** [coolsnowwolf/lede#7308]
1.没有保存按钮，修改后无法保存
2.无线安全设置进不去，无法设置wifi密码
![image](https://user-images.githubusercontent.com/82493550/124754382-b9ac6380-df5c-11eb-86ff-7f909fabf104.png)
设备架构：ramips mt7621

**Comment by xcf13363175** [comment]
大概率浏览器问题

**Comment by Thanf-code** [comment]
> 大概率浏览器问题

应该不是浏览器问题  我用手机浏览器打开也是一样的bug

**Comment by shikkoku** [comment]
> > 大概率浏览器问题
> 
> 应该不是浏览器问题 我用手机浏览器打开也是一样的bug
> 我修改了luci ，不知道会不会跟这个有关

我想你应该要在标题和正文说明你都改了些什么，避免误会。

**Comment by Thanf-code** [comment]
> > > 大概率浏览器问题
> > 
> > 
> > 应该不是浏览器问题 我用手机浏览器打开也是一样的bug
> > 我修改了luci ，不知道会不会跟这个有关
> 
> 我想你应该要在标题和正文说明你都改了些什么，避免误会。

是luci的问题
