### ISSUE TITLE
dw33d 无法运行uu

### ISSUE THREAD

**Issue by screenshot-zz** [coolsnowwolf/lede#7309]
dw33d 无法运行uu  已经找客服 由于openwrt没有2个命令 帮忙查查能不能支持 
以下是聊天信息
我：
Uu支持qca9558吗  运行没反应        X86 mt7620 没问题
客服：
你看一下openwrt命令行里面 

readelf -h /bin/cat

或者 file /bin/cat

输出来的内容是啥

如果内容有LSB 就有办法适配 如果内容是MSB 就暂时支持不了

**Comment by coolsnowwolf** [comment]
UU 不支持 MIPS，只支持 MIPSEL
