### ISSUE TITLE
V2ray 缺少 tlsSettings 的 serverName 项

### ISSUE THREAD

**Issue by Love4Taylor** [coolsnowwolf/lede#731]
这会导致 SNI 验证过不了, 在强制 SNI 验证的服务器上会直接无法 TLS 握手, 例如 Apache 以及 打了 Patch 的 Nginx.

**Comment by Catelemmon** [comment]
你可以考虑把百度的DNS服务器加进去

**Comment by Catelemmon** [comment]
噗， 我回错了我开了两个issue，有个人问百度打开很慢，我让他加进去，你v2ray用的是websocket+tls+Apache？我感觉KCP可能要快一些啊

**Comment by Love4Taylor** [comment]
@Catelemmon kcp 不是所有地方都适用啊 我这 UDP 限制很严格都是一段时间之后就封端口了.

**Comment by hcym** [comment]
websocket+tls+Apache这个太复杂没敢试，其他mkcp，http2等等都试了个遍，感觉还是官方默认的最简配置好用
