### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#7310]
反馈bug/问题模板，提建议请删除
编译如果不选Turbo ACC，更新编译的固件后就不能上网，但微信还能用，只是电脑浏览器打不开任何网站。
选了Turbo ACC编译后更新，如果不关闭和再打开Turbo ACC下面的DNS缓存也是不能打开任何网站。实在不明白这是为什么，以前没有这个问题啊，最近更改了Turbo ACC的的选择方式后才出现的，以前的SFE 或者 Flow offload都没有这个问题。
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by NagaseKouichi** [comment]
看看DNS转发那里，原来开启Turbo ACC的DNS缓存之后，会自动设置DNS转发，现在不清楚

**Comment by cncqcyc** [comment]
终于有人反馈了这个问题了，之前我把turbo acc编译进去后会出现断流现象，后来就把它去掉了，结果这两天编译出来的固件无论如何都上不了网，改一下设置又能上，但是很快就不能了，我正在把额外添加的插件去掉来排查，结果就看见你提交的问题，看来应该是如此了

**Comment by qqsir-dev** [comment]
> 看看DNS转发那里，原来开启Turbo ACC的DNS缓存之后，会自动设置DNS转发，现在不清楚

上游DNS必须是公网DNS，内网的一样打不开任何网站
