### ISSUE TITLE
小米路由器wifi不能使用

### ISSUE THREAD

**Issue by makebl** [coolsnowwolf/lede#7312]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
小米R3G无线不能用了，打不开，要么是没有信号！！

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述
原来5.4.113版本时候一直都是正常的，现在的版本都是无线网络不能用！
![image](https://user-images.githubusercontent.com/78850005/124866936-cfb73400-dfef-11eb-891a-d45cb3cceb8f.png)
![image](https://user-images.githubusercontent.com/78850005/124866948-d47be800-dfef-11eb-8ed0-a7173b80a979.png)
![image](https://user-images.githubusercontent.com/78850005/124866958-d9409c00-dfef-11eb-841a-06a0fd6d949a.png)

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by 279437541** [comment]
802.11一直都是0%信号，选择7615无线的话  就打不开，提示上图那个错误，让重建

**Comment by 279437541** [comment]
5.4.113版本的 就一个7615无线，都很正常！最近5.4.12X的版本一直都是在这样的情况
