### ISSUE TITLE
AX6 无线全部设备信号显示均为 0 

### ISSUE THREAD

**Issue by doney0318** [coolsnowwolf/lede#7319]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：全部设备无线信号显示均为 0 

### (2) 路由器型号和固件版本

A：xiaomi redmi AX6，内核版本5.10.46

### (3) 详细日志

A：
![1625793272254](https://user-images.githubusercontent.com/3262032/125009092-6e966b80-e096-11eb-9491-4c65ea843358.jpg)

**Comment by castiel652** [comment]
缺這個 https://patchwork.kernel.org/project/linux-wireless/patch/20210224090241.3098-1-srirrama@codeaurora.org/

**Comment by yz2002** [comment]
把这个patch进去以后只有5G会显示 2.4G还是一样显示0

**Comment by castiel652** [comment]
那我就不知道了
我只有用 5G 所以沒發現到
