### ISSUE TITLE
AX6无法使用缓存

### ISSUE THREAD

**Issue by wuelliott** [coolsnowwolf/lede#7321]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：最新源码编译的红米AX6固件无法使用缓存，https://github.com/immortalwrt/immortalwrt编译的固件可以正常使用。

### (2) 路由器型号和固件版本

A：固件版本 OpenWrt R21.7.1.100，内核版本 5.10.46

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/42060326/125015640-76f4a380-e0a2-11eb-87b7-e24fc230592e.png)

**Comment by coolsnowwolf** [comment]
因为 AX6 目前剩余内存偏少，做了调度，尽量不要去缓存避免 OOM

**Comment by wuelliott** [comment]
> 因为 AX6 目前剩余内存偏少，做了调度，尽量不要去缓存避免 OOM

明白了，感谢解答！
