### ISSUE TITLE
AX3600内存占用过大，造成路由器自动重启，luciapp崩溃

### ISSUE THREAD

**Issue by huah0235** [coolsnowwolf/lede#7324]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：AX3600内存占用过大，设备连接数多一些时，内存仅剩几十MB。稳定性差，有时会自动重启。
同时，如果跑酸酸+，科学上网会变得非常不稳定，经常崩掉，提示"xxx Plus+ 未运行"。
群里讨论听说是NSS的问题，不知道有没有解决方法。

ps，同一套源码AX6编译出来的内存占用就小很多，剩余内存在200MB左右，酸酸+也稳定许多。

### (2) 路由器型号和固件版本

A：AX3600 R21.7.1

### (3) 详细日志

A：
![_Y5HMCZEZ8IG$BJM9GM0{QG](https://user-images.githubusercontent.com/24620648/125033469-ec23a100-e0c1-11eb-8f33-b0e92876aa10.png)

**Comment by ldy8182** [comment]
无线关了吗？

**Comment by huah0235** [comment]
> 无线关了吗？

当然是开着无线

**Comment by ldy8182** [comment]
现在的无线驱动会泄露内存，所以最好关掉

**Comment by wuelliott** [comment]
看来AX3600和AX6都是一样啊，缓存那里都是0MB。

**Comment by Cathgao** [comment]
买个几百块的无线路由器来关掉无线用😳这是什么新玩法
