### ISSUE TITLE
编译rclone报错

### ISSUE THREAD

**Issue by yubanmeiqin9048** [coolsnowwolf/lede#7325]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：如果编译时勾选rclone则会报错，不勾选没事

### (2) 路由器型号和固件版本

A：ARMV8

### (3) 详细日志

A：
Finding targets
go: bazil.org/fuse@v0.0.0-20200407214033-5883e5a4b512: Get "https://proxy.golang.org/bazil.org/fuse/@v/v0.0.0-20200407214033-5883e5a4b512.mod": dial tcp 172.217.160.81:443: i/o timeout

Building targets

**Comment by AmadeusGhost** [comment]
你网络问题，开 goproxy 吧

**Comment by yubanmeiqin9048** [comment]
> 你网络问题，开 goproxy 吧

开着V2，编译其他插件都没问题，就是rclone出错

**Comment by yubanmeiqin9048** [comment]
> 你网络问题，开 goproxy 吧

确实是网络问题，开SOCKS5全局解决了，感谢
