### ISSUE TITLE
编译出来的固件LAN口全部崩溃了

### ISSUE THREAD

**Issue by ixmu** [coolsnowwolf/lede#7327]
反馈bug/问题模板，提建议请删除
##关于你要提交的问题
   使用最新的源码为R6800编译固件，编译出来的固件LAN全部失效，且指示灯没亮（裸固件）
##路由器型号和固件版本
网件R6800
##启动日志
https://gzu.lanzoui.com/i07t2r7podg

**Comment by coolsnowwolf** [comment]
内核太高，选  5.4

**Comment by ixmu** [comment]
成功解决LAN无法使用问题，可以开始考虑适配LED灯了，如果有相关文档，欢迎推荐
