### ISSUE TITLE
恳请添加Dnsfilter的原作者插件

### ISSUE THREAD

**Issue by vsvkhs** [coolsnowwolf/lede#7329]
https://www.right.com.cn/forum/thread-4751081-1-1.html
这是原作者，支持原作者有利于插件后续维护更新吧

**Comment by suizhenmin** [comment]
自己手动添加一个源就好了啊

**Comment by hxlls** [comment]
这个和Adbyby plus 有啥区别？我感觉都一样，ADP 都存在了多久了，从R8还是R9年代都存在了的东西，为啥还要添加一个相似度90%以上的东西？

**Comment by vsvkhs** [comment]
> 自己手动添加一个源就好了啊
lean大添加了dnsfilter支持，原作者贡献忽略了。
