### ISSUE TITLE
dns解析问题

### ISSUE THREAD

**Issue by wtfr-dot** [coolsnowwolf/lede#7340]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：esxi虚拟机安装x86固件，联通移动双网口，固件编译选择了mwan3和mwan3helper
，添加了passwall包含chinadns-ng，turboacc含sfe,bbr,dns缓存.
系统启动后选择dns缓存后可以打开网页，过一会再打开网页提示“err_name_not_resolved”，无法上网，关闭dns缓存又能上网，但是一会又不行，然后关闭passwall里的chinadns-ng也是同样的故障，总之动一下相关的设置就能浏览网页，但过一会又不行有，将turboacc全部关闭也出现同样故障，在5.10内核的早期系统还基本正常，只是大概10几个小时后会出现不能上网的情形，最近更新编译的固件频繁出现无法上网故障，请帮忙分析一下原因，谢谢！
另：单独编译了一个不含passwall，添加了helloword的固件也同样出现类似故障。
### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by cncqcyc** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ x] 没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> A：esxi虚拟机安装x86固件，联通移动双网口，固件编译选择了mwan3和mwan3helper
> ，添加了passwall包含chinadns-ng，turboacc含sfe,bbr,dns缓存.
> 系统启动后选择dns缓存后可以打开网页，过一会再打开网页提示“err_name_not_resolved”，无法上网，关闭dns缓存又能上网，但是一会又不行，然后关闭passwall里的chinadns-ng也是同样的故障，总之动一下相关的设置就能浏览网页，但过一会又不行有，将turboacc全部关闭也出现同样故障，在5.10内核的早期系统还基本正常，只是大概10几个小时后会出现不能上网的情形，最近更新编译的固件频繁出现无法上网故障，请帮忙分析一下原因，谢谢！
> 另：单独编译了一个不含passwall，添加了helloword的固件也同样出现类似故障。
> 
> ### (2) 路由器型号和固件版本
> A：
> 
> ### (3) 详细日志
> A：

目前已经确认mwan3工作不稳定会造成无法上网，在系统的负载均衡上查看状态时，两个wan口都在线，但是查看详细信息会看见两个wan口错误，负载均衡没有工作，重启mwan3后网络恢复正常
