### ISSUE TITLE
WNDR3800开启ZeroTier 运行一段时间后 会自动停止运行！ 

### ISSUE THREAD

**Issue by xtwz** [coolsnowwolf/lede#735]
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2506857/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2506860/default.txt)

开启ZeroTier 运行一段时间后 会自动停止运行，在点击运行后还是一样！
群里也有反应一样的情况，返回至R8.1.7 能正常运行。

**Comment by xtwz** [comment]
![_20181024000139](https://user-images.githubusercontent.com/19466813/47374296-2edd9900-d720-11e8-942c-bd509ffa66b7.png)
刚刚在保存应用后，直接显示未运行！

**Comment by weigang7211** [comment]
跟你一样情况，有解决方法没有
