### ISSUE TITLE
[求助]AX86U梅林官改固件安装fancyss_hnd后，无法添加订阅节点的问题

### ISSUE THREAD

**Issue by divid86** [coolsnowwolf/lede#7381]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：
华硕路由器刷ML官改固件，安装科学上网，然后在【更新管理】界面中粘贴订阅链接，点击【保存并订阅】，显示以下日志内容，【账号设置】里未出现可选择的节点信息。

补充1：【更新管理】中的【规则定时更新任务】已选择开启，并勾选了后面的gfwlist√  chnroute√   CDN√  三个选项。
补充2：订阅链接在浏览器中是可以正确读取的，另外使用相同的链接，可以在PC和安卓平台客户端中正常使用。
补充3：个人判断是【更新管理】中的【订阅地址管理】未能读取订阅链接，因为我尝试了一下不粘贴任何信息，或者是粘贴一个错误的链接，也还是弹出下面一样的日志记录，但至于为何没能正确读取链接就不知道了。

本人在这方面没啥技术积累，还请大神协助，感谢感谢！！

### (2) 路由器型号和固件版本

A：
路由器型号：华硕AX86U    
固件版本：梅林官改固件386.2.4

### (3) 详细日志

A：点击【保存并订阅】之后弹出以下日志信息：

【2021年07月14日 16:33:49】: 开始订阅
【2021年07月14日 16:33:49】: 开始节点数据检查...
【2021年07月14日 16:33:49】: 最大节点序号：
【2021年07月14日 16:33:49】: 共有节点数量：1
【2021年07月14日 16:33:50】: 节点顺序正确，节点配置信息OK！无需调整！
【2021年07月14日 16:33:50】: 收集本地订阅节点信息到临时文件
【2021年07月14日 16:33:50】: 最大节点序号：
【2021年07月14日 16:33:50】: 共有节点数量：0
【2021年07月14日 16:33:50】: 节点排序需要调整!
【2021年07月14日 16:33:50】: -------------------------------------------------------------------
【2021年07月14日 16:33:50】: 一点点清理工作...
【2021年07月14日 16:33:50】: ===================================================================
【2021年07月14日 16:33:50】: 所有订阅任务完成，请等待6秒，或者手动关闭本窗口！
【2021年07月14日 16:33:50】: ===================================================================

**Comment by minlang112** [comment]
你走错地方了
