### ISSUE TITLE
跑docker下应用流量不走ssr

### ISSUE THREAD

**Issue by wxs-dev** [coolsnowwolf/lede#7384]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
设备是N1，做主路由拨号上网
局域网网段192.168.4.0/24
docker是桥接，网段171.31.0.0/16
开ssr plus+后，局域网的手机电脑可以科学上网。但跑docker下应用不能科学上网，可以访问国内的网站
请问这是什么问题？

**Comment by wtbam** [comment]
在ssr里设置强制走代理

**Comment by wxs-dev** [comment]
有没有朋友可以帮忙回答，困扰了好几天，实在没辙了😭

**Comment by acooler15** [comment]
我用的 [dockerman](https://github.com/lisaac/luci-app-dockerman)+ dockerd来管理docker，在ssr的`访问控制-接口控制` 中有一个`docker`接口，勾选上就可以访问了

**Comment by wxs-dev** [comment]
> 我用的 [dockerman](https://github.com/lisaac/luci-app-dockerman)+ dockerd来管理docker，在ssr的`访问控制-接口控制` 中有一个`docker`接口，勾选上就可以访问了（docker容器的网络模式是默认的bridge，其它的没试过）
 
![image](https://user-images.githubusercontent.com/58886165/125959749-426c30d2-3f05-4314-a6ad-7bdde388e920.png)
![image](https://user-images.githubusercontent.com/58886165/125959891-4ee092a5-0456-43c6-bb75-84909492e7d5.png)

我这没有docker接口，好像也没用dockerman

**Comment by acooler15** [comment]
可以试试dockerman呀，感觉挺好用的。。。

**Comment by 643406834** [comment]
environment:
    - http_proxy=http://10.0.0.1:7880
    - HTTP_PROXY=http://10.0.0.1:7880
    - https_proxy=http://10.0.0.1:7880
    - HTTPS_PROXY=http://10.0.0.1:7880
docker应用的环境变量全部指向ssr

**Comment by wxs-dev** [comment]
> environment:
> - http_proxy=http://10.0.0.1:7880
> - HTTP_PROXY=http://10.0.0.1:7880
> - https_proxy=http://10.0.0.1:7880
> - HTTPS_PROXY=http://10.0.0.1:7880
> docker应用的环境变量全部指向ssr

ssr+只能socket5代理
另外还有其他的办法吗，这样的话，每个容器都需要配置这个环境

**Comment by acooler15** [comment]
> > environment:
> > 
> > * http_proxy=http://10.0.0.1:7880
> > * HTTP_PROXY=http://10.0.0.1:7880
> > * https_proxy=http://10.0.0.1:7880
> > * HTTPS_PROXY=http://10.0.0.1:7880
> >   docker应用的环境变量全部指向ssr
> 
> ssr+只能socket5代理
> 另外还有其他的办法吗，这样的话，每个容器都需要配置这个环境

不需要一个个的设置，可以在`~/.docker/config.json`中设置`httpProxy`、`httpsProxy`，然后再重新创建容器。https://docs.docker.com/engine/reference/commandline/cli/#change-the-docker-directory

**Comment by acooler15** [comment]
> > 我用的 [dockerman](https://github.com/lisaac/luci-app-dockerman)+ dockerd来管理docker，在ssr的`访问控制-接口控制` 中有一个`docker`接口，勾选上就可以访问了（docker容器的网络模式是默认的bridge，其它的没试过）
> 
> ![image](https://user-images.githubusercontent.com/58886165/125959749-426c30d2-3f05-4314-a6ad-7bdde388e920.png)
> ![image](https://user-images.githubusercontent.com/58886165/125959891-4ee092a5-0456-43c6-bb75-84909492e7d5.png)
> 
> 我这没有docker接口，好像也没用dockerman

这是我的network配置文件：
```
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd78:4736:6d25::/48'

config interface 'lan'
        option type 'bridge'
        option ifname 'eth0'
        option proto 'static'
        option ipaddr '192.168.123.1'
        option netmask '255.255.255.0'
        option ip6assign '60'

config interface 'docker'
        option ifname 'docker0'
        option proto 'none'
        option auto '0'

config device 'docker0'
        option type 'bridge'
        option name 'docker0'
        list ifname 'docker0'

config interface 'wan'
        option proto 'pppoe'
        option ifname 'eth1'
        option username '0'
        option password '0'
        option ipv6 'auto'
        option peerdns '0'
        option dns '223.5.5.5 223.6.6.6 2400:3200::1 2400:3200:baba::1'
        option keepalive '0'
        option mtu '1480'
```

**Comment by klaus121** [comment]
> 有没有朋友可以帮忙回答，困扰了好几天，实在没辙了😭

解决了吗，换ssr版本吗？

**Comment by Xunflash** [comment]
> 我用的 [dockerman](https://github.com/lisaac/luci-app-dockerman)+ dockerd来管理docker，在ssr的`访问控制-接口控制` 中有一个`docker`接口，勾选上就可以访问了（docker容器的网络模式是默认的bridge，其它的没试过）

有个问题，我需要固定IP，因此自己新建了一个bridge网络，然而这个网络没有父接口，导致ssr勾选上docker0接口无效...
而且我的$HOME目录下面也没有.docker目录..
