### ISSUE TITLE
编译wrt1200ac的问题 以及 新版UUgame无法下载

### ISSUE THREAD

**Issue by rshi0212** [coolsnowwolf/lede#7389]
新版UUgame无法下载

![image](https://user-images.githubusercontent.com/61662344/125669194-d8add522-0bfe-4904-9313-976b5039496e.png)
请问编译wrt1200ac时提示的Architected Timer Support是什么选项，应该选YES还是NO？

![image](https://user-images.githubusercontent.com/61662344/125664615-21164af4-eb9b-4a1a-b1d6-4b448f0fc124.png)

**Comment by 1-bytes** [comment]
目前遇到了和楼主一样的问题... uugamebooster这个包失效了 ，下载是404页面，编译直接不通过

**Comment by HoldOnBro** [comment]
boom

**Comment by adamgonglj** [comment]
同样的问题。

**Comment by LOVEChen** [comment]
SHELL= flock /root/lede/tmp/.uugamebooster-x86_64-v2.12.0.tar.gz.flock -c '     /root/lede/scripts/download.pl "/root/lede/dl" "uugamebooster-x86_64-v2.12.0.tar.gz" "61fffa3e17f21cca78c85b0f0bbcd7ed" "" "http://uu.gdl.netease.com/openwrt-x86_64/v2.12.0/uu.tar.gz?"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://uu.gdl.netease.com/openwrt-x86_64/v2.12.0/uu.tar.gz?/uugamebooster-x86_64-v2.12.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

**Comment by haig233** [comment]
同样，uugame无法下载

**Comment by NagaseKouichi** [comment]
uugame最新版不是2.10.0吗？下载地址里面怎么是2.12.0
