### ISSUE TITLE
安装curl之后，使用时报错

### ISSUE THREAD

**Issue by rengame** [coolsnowwolf/lede#739]
opkg update 
opkg install curl

curl ip.cn

报如下错误：
Error loading shared library libmbedtls.so.10: No such file or directory (needed by /usr/bin/curl)
Error loading shared library libmbedcrypto.so.1: No such file or directory (needed by /usr/bin/curl)
Error loading shared library libmbedtls.so.10: No such file or directory (needed by /usr/lib/libcurl.so.4)
Error loading shared library libmbedcrypto.so.1: No such file or directory (needed by /usr/lib/libcurl.so.4)
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_session_free: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_init: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_min_version: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_config_defaults: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_config_init: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_get_session: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_free: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_max_version: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_config_free: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_get_bytes_avail: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_get_peer_cert: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_setup: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_handshake: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_authmode: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_set_bio: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_get_verify_result: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_read: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_set_session: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_ciphersuites: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_rng: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_list_ciphersuites: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_set_hostname: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_session_init: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_write: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_net_recv: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_own_cert: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_ca_chain: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_ssl_conf_cert_profile: symbol not found
Error relocating /usr/lib/libcurl.so.4: mbedtls_net_send: symbol not found
root@OpenWrt:~#

**Comment by hcym** [comment]
滑稽，一直都编译这个包，从来没用过，看来以后还是不要的好

**Comment by coolsnowwolf** [comment]
不要安装，mbedtls的版本和 trunk 的版本不同了，编译时加入

**Comment by rengame** [comment]
> 不要安装，mbedtls的版本和 trunk 的版本不同了，编译时加入

好的，谢谢。重新编译了。

**Comment by PureWhiteWu** [comment]
@coolsnowwolf hi，这个问题有办法解决么？我刷了今天编译的系统，也遇到了这个问题。

**Comment by searene** [comment]
我也想知道怎么解决，今天也遇到了这个问题

**Comment by searene** [comment]
解决了，执行命令opkg install libmbedtls就行了

**Comment by hyue418** [comment]
> 解决了，执行命令opkg install libmbedtls就行了

点赞啊！
