### ISSUE TITLE
概览--接口里边信息只显示wan1的ip信息，不显示wan2的信息

### ISSUE THREAD

**Issue by S0SL** [coolsnowwolf/lede#7395]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
我有两条宽带配置好网口并使用负载均衡配置好分流可以正常上网，但是概览--接口里边信息只显示wan1的ip信息，不显示wan2的信息。
### (1) 具体问题
A：
概览--接口里边信息只显示wan1的ip信息，不显示wan2的信息

### (2) 路由器型号和固件版本
A：
编译的x86固件
### (3) 详细日志

A：
![9dba744bb0f5351b8b6484fd3c9c614](https://user-images.githubusercontent.com/16398874/125808609-eaad2077-de7b-4885-ab46-720342c8b63f.png)

**Comment by cncqcyc** [comment]
我的也是这样，另外我禁用了ipv6，但mwan3的连接状态里还是有ipv6的信息
