### ISSUE TITLE
Turbo ACC 导致macos 上的 Parallels Client  远程桌面应用无法使用

### ISSUE THREAD

**Issue by suizhenmin** [coolsnowwolf/lede#7398]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [是 ] 没有类似的issue

## 2. 详细叙述
macbook 上使用 Parallels Client 远程桌面 win10 主机，使用旧版Turbo ACC 时候正常，更新到支持 ipv6 的版本后  Parallels Client 远程连接必须在设置中降低显示的设置，导致远程链接非常卡顿。原先是有2个版本可选，现在已经没有旧版了，只有L大的魔改版本了。此问题在局域网内不会出现，只有在外网远程连接时才会出现。

![1](https://user-images.githubusercontent.com/2957364/125878330-f004fee9-d005-4c3a-80c7-5204ec9d1666.png)

只有将图像加速降低到基本功能才能连接

![2](https://user-images.githubusercontent.com/2957364/125878344-39f6c638-6852-4f08-9a7b-7a2d0eb969f6.png)

A：

### (2) 路由器型号和固件版本

![3](https://user-images.githubusercontent.com/2957364/125878473-585f0a30-85e7-4a2c-9397-5cb23cd11c99.png)

A：

### (3) 详细日志

A：

**Comment by suizhenmin** [comment]
原来是2个合并了，可以选择

**Comment by Mitsuhaxy** [comment]
qca-nss-ecm

**Comment by DanielChen008** [comment]
难道我升级固件后，群晖自带的 DDNS 服务（xxx.myds.me:5000）从外面访问不到了也是这个问题？… 回家试试去
