### ISSUE TITLE
发现一个很神奇的事情

### ISSUE THREAD

**Issue by gztingting** [coolsnowwolf/lede#7402]
同样的编译配置，即同一个.config文件，Target Image文件系统有ext4 和选squashfs，得到两个镜像文件，最后分别写盘到软路由ssd硬盘上，占用磁盘空间居然差异大。
我配置的磁盘空间是16+768M，
用  ext4  那个openwrt-x86-64-generic-ext4-combined-efi.img写盘后，剩余空间是215M，
用squashfs那个openwrt-x86-64-generic-squashfs-combined-efi.img写盘后，剩余空间是496M。
后者居然占用更少空间，我原以为适用于硬路由器的squashfs文件格式，怎么折腾，怎么增删修改文件，只要firstboot reset一下就相当于重刷机器了，可能是留了一份出厂设置的文件，理应更占用空间，真没想到啊。

**Comment by starxu1971** [comment]
squashfs是只读系统。系统那块是不动的所以初始占用未必多
