### ISSUE TITLE
docker host正常 默认bridge无网络 打开允许 WAN 访问 Docker 就正常...

### ISSUE THREAD

**Issue by darktitty** [coolsnowwolf/lede#7408]
## 1.关于你要提交的问题

Q：是否搜索了issue
是的 搜过并且试过了所有方法...

### (1) 具体问题

A：最新docker(其实本人一直都存在此问题...) host正常 默认bridge无网络 打开允许 WAN 访问 Docker 就正常... 尝试过网上很多解决办法 包括搜索到的issue 均无效...

### (2) 路由器型号和固件版本

A：x86软路由(两台都试过不行 N3060 N4100) 固件最新 之前很多版也一样的问题

**Comment by wyx1818** [comment]
我也是的，求个解决方案呀

**Comment by junfeng142** [comment]
我的在防火墙打开转发就可以了

**Comment by EnnawYang** [comment]
这个问题建议向官方提issue

**Comment by musouking** [comment]
https://github.com/coolsnowwolf/lede/issues/1760#issuecomment-542985373
试过这个么
