### ISSUE TITLE
能否在ssrplus+添加一个IP分流模式使用pdnsd的选项

### ISSUE THREAD

**Issue by 1779729350** [coolsnowwolf/lede#741]
RT,十分感谢L大

**Comment by 1779729350** [comment]
自己尝试修改了一下client.lua和/init.d/shadowsocksr，并没有起作用，想请教一下pdnsd相关的控制文件还有别的么？

**Comment by vernesong** [comment]
同样有这个需求，国内白名单加PDNSD，因为需要使用到haproxy，而其无法转发UDP

**Comment by coolsnowwolf** [comment]
建议用 SSR Pro 配合
