### ISSUE TITLE
京东签到功能失效了

### ISSUE THREAD

**Issue by adamgonglj** [coolsnowwolf/lede#7421]
反馈bug/问题模板，提建议请删除

京东签到功能已不能正确工作。

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Cathgao** [comment]
算命？我的签到怎么是成功的
![IMG_20210718_184829.jpg](https://user-images.githubusercontent.com/21031564/126064373-98d2115e-213b-4c56-b704-244b822058b1.jpg)

**Comment by adamgonglj** [comment]
咦，有效，那我看看

**Comment by njf1993** [comment]
我也不能正常签到，且无法推送。昨日新编译的包
