### ISSUE TITLE
稳定版4.14编译有警告，怎么去除？

### ISSUE THREAD

**Issue by itfish92** [coolsnowwolf/lede#7426]
经过搜索没有类似的issue

稳定版4.14编译有警告，make menuconfig和make download的时候都会提示：

WARNING: Makefile 'package/feeds/luci/luci-app-transmission/Makefile' has a dependency on 'transmission-daemon-openssl', which does not exist

但是最后都能编译成功， 使用过程貌似也没问题。
这个提示如何解决？路过大神指点一下，本小白虚心请教，多谢各位

**Comment by Cathgao** [comment]
不用管

**Comment by itfish92** [comment]
> 不用管

好嘞，多谢
