### ISSUE TITLE
编译时选择SoftEtherVPN5大雕源码会出现编译失败...日志已贴出

### ISSUE THREAD

**Issue by inlyt** [coolsnowwolf/lede#743]
[编译SoftEtherVPN5.txt](https://github.com/coolsnowwolf/lede/files/2514748/SoftEtherVPN5.txt)
![ubuntu 64 -2018-10-25-19-59-27](https://user-images.githubusercontent.com/35872517/47498670-88fd6c00-d890-11e8-8c72-2ff1864ecf69.png)

**Comment by inlyt** [comment]
[编译SoftEtherVPN5失败日志.txt](https://github.com/coolsnowwolf/lede/files/2514751/SoftEtherVPN5.txt)

**Comment by libinanshu** [comment]
删除这这dl目录下的文件，确保梯子没问题重新编译。

**Comment by inlyt** [comment]
> 删除这这dl目录下的文件，确保梯子没问题重新编译。
梯子肯定是没有问题...
make clean
make distclean都试过了一次..还是不型..原版的倒是没问题..
选择SoftEtherVPN5 server才会出现404...

**Comment by yulinsoft** [comment]
我也遇到了这个问题，官方版是可以编译的，这个版本会失败。
