### ISSUE TITLE
网件R7500固件可用空间不足，/overly目录能否扩容。

### ISSUE THREAD

**Issue by zoumeng** [coolsnowwolf/lede#7430]
1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)

 没有类似的issue
2. 详细叙述
(1) 具体问题
A：网件R7500 V1 不自定义包编译的的固件刷机/overly目录可用空间只有1.6M，编译时选择软件包的固件无法刷机。/overly目录能否扩容。

(2) 路由器型号和固件版本
A：网件R7500 V1

(3) 详细日志
A：

![image](https://user-images.githubusercontent.com/4217271/126096442-02b6aefb-36c4-494d-8ac3-0e06dc84d5d8.png)

**Comment by coolsnowwolf** [comment]
原厂默认 22MB 太小了，我扩大到 104MB 了

![image](https://user-images.githubusercontent.com/31687149/126136440-5c0528d7-e646-4e63-8380-baea1712bd8d.png)
