### ISSUE TITLE
1，希望升级一下Material主题   2，刷写新固件功能不能用

### ISSUE THREAD

**Issue by whfweb** [coolsnowwolf/lede#7435]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

很喜欢Material主题，但相较于openwrt的同名主题略显简陋，希望方便的话能升级一下，毕竟会经常的看到这个界面，美观一些还是要好很多。谢谢~

还有一个就是，刷写新固件功能还是和旧版一样不能用，不知其他人的机型怎么样，我的机子是wrt1900ac-v2

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by haig233** [comment]
主题这种自己都可以吧，还有必要麻烦老雕么

**Comment by whfweb** [comment]
> 主题这种自己都可以吧，还有必要麻烦老雕么

尝试过把openwrt移植过来，编译通过但进不了web界面

**Comment by Neverends4** [comment]
这里的Luci还是18.06，官方好像主题最新都是19.07了
之前在其他issue也说过了？是不是要置个顶……

**Comment by EnnawYang** [comment]
顶置？为啥要顶置？ 又不是不能用.jpg

**Comment by Neverends4** [comment]
刷新固件是有问题
ssh进路由器用cli吧
sysupgrade -v  -n /tmp/sysupgrade.bin
**-n 不保存配置**
