### ISSUE TITLE
最新源码的ssrplus不能启动

### ISSUE THREAD

**Issue by blueveryday** [coolsnowwolf/lede#744]
rules文件里面，81行，语法错误，ipset前面缺少do，添加即可解决。

for ip in $WAN_FW_IP; do ipset -! add gfwlist $ip ; done

编译了几个rom都是这个问题。
不晓得是不是个例。

**Comment by ikokang** [comment]
更新源代码 git pull
更新软件包 ./scripts/feeds update -a
安装软件包 ./scripts/feeds install -a

使用以上命令可以解决你的问题，如果还出错请删除 tmp目录下的所有文件。当前我使用版本号luci-i18n-ssr-plus-zh-cn	1-30正常

**Comment by blueveryday** [comment]
git pull命令更新不了。

**Comment by Lancenas** [comment]
> git pull命令更新不了。

科学上网更新

**Comment by blueveryday** [comment]
好了，谢谢。
