### ISSUE TITLE
希望阿里云DDNS能加入多子域名支持

### ISSUE THREAD

**Issue by libinanshu** [coolsnowwolf/lede#746]
![tim 20181028104819](https://user-images.githubusercontent.com/44538423/47611533-88d4ba80-daa2-11e8-9a26-0a06dd1ca992.png)

**Comment by inlyt** [comment]
魔改Gk
啊哈哈哈

**Comment by yulinsoft** [comment]
我感觉完全没有必要，如果是要多个域名一个IP，直接用CNAME解析更简单，只用更新一个域名，其它域名直接CNAME解析到这个域名就行了。
