### ISSUE TITLE
5.10 x86-64编译新版固件内存占用高，256M内存直接无法启动

### ISSUE THREAD

**Issue by govisgood** [coolsnowwolf/lede#7460]
![image](https://user-images.githubusercontent.com/10335240/126413630-42687dbe-daf1-48de-8c10-7ed6c34c0998.png)

5.10 x86-64固件编译出来的，256M虚拟机跑直接无限重启，报内存不足。

之前5.4的时候256M跑的没问题，同样的编译插件，剩余内存110多M。
![image](https://user-images.githubusercontent.com/10335240/126413796-108e5dac-9a8e-41ae-a1de-aeb3e91fe9bf.png)

**Comment by minlang112** [comment]
如果是虚拟机，多分配点内存吧，如果是实体机扔了吧
