### ISSUE TITLE
nlbwmon日志报内存不足，但是明明可用内存还有很多

### ISSUE THREAD

**Issue by db-one** [coolsnowwolf/lede#7465]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：![image](https://user-images.githubusercontent.com/20243226/126465984-59aa86b6-b837-4b57-ac17-c7ab6aeeec9f.png)
nlbwmon日志报内存不足，但是明明可用内存还有很多
虚拟机下运行的，分了1G内存，空闲内存600-700M左右

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/20243226/126466279-bb77483d-7064-44f3-b8b1-8bf3f9689adc.png)

Wed Jul 21 16:54:02 2021 daemon.err nlbwmon[17653]: Netlink receive failure: Out of memory
Wed Jul 21 16:54:02 2021 daemon.err nlbwmon[17653]: Unable to dump conntrack: No buffer space available

**Comment by qqsir-dev** [comment]
到 /etc/config/下 编辑nlbwmon 按照下面设置就行了
option netlink_buffer_size 10485760

**Comment by db-one** [comment]
好的，谢谢，已经设置好了，再观察一下，翻译了一下大意是

	# The buffer size for receiving netlink conntrack results, in bytes.
	# If the chosen size is too small, accounting information might get
	# lost, leading to skewed traffic counting results

	# 用于接收netlink conntrack结果的缓冲区大小，字节数。
	# 如果选择的大小太小，会计信息可能会被
	# 丢失，导致流量统计结果的偏差

**Comment by Neverends4** [comment]
如果你内网流量大，改了可能也溢出，只能缓解。这貌似是nlbwmon的bug，好几个人提了类似issue但是没更新。

**Comment by db-one** [comment]
改了确实没报错了，希望大佬早日修复
话说溢出会有什么后果，CPU内存占用高吗？

**Comment by EnnawYang** [comment]
早就修改过了 没想到不能满足你们

**Comment by db-one** [comment]
> 早就修改过了 没想到不能满足你们

ᥬ😂᭄ᥬ😂᭄ᥬ😂᭄ᥬ🌚᭄话说我流量也不高啊，基本都是空载状态，也不怎么看视频 看电视，就是工作看看网页

**Comment by bonnyandsky** [comment]
不单单是x86 我mt7621也有这个报错，看了下日志，大概3小时不到一点报错一次。具体看日志
![image](https://user-images.githubusercontent.com/30990861/139819644-c6b358bf-2774-4dcd-9b9c-0ac500000af6.png)
