### ISSUE TITLE
用Hyper V跑无限重启

### ISSUE THREAD

**Issue by Sir-Speed-a-Lot** [coolsnowwolf/lede#7470]
选第二代机器 用转出来efi的vhdx 开机后大约5秒自动重启 无限重启

选第一代机器 貌似没问题

以前的固件都是用第二代没问题 不知大佬是改了哪里。。。

**Comment by qqsir-dev** [comment]
用ESXi

**Comment by xuanyabulema** [comment]
有没有可能是你用的固件的问题

**Comment by Sir-Speed-a-Lot** [comment]
> 有没有可能是你用的固件的问题

后来发现是以前5.4版本时代开512MB内存就够，5.10时候不够了，所以无限重启
