### ISSUE TITLE
编译失败 报错

### ISSUE THREAD

**Issue by CJM88888** [coolsnowwolf/lede#7478]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述 
![WeChat Image_20210722201902](https://user-images.githubusercontent.com/87486596/126638026-dae3458b-3452-495c-b310-1c6af5b7bd15.jpg)

### (1) 具体问题

A：编译失败

### (2) 路由器型号和固件版本r8

A：

### (3) 详细日志

A：

**Comment by Boos4721** [comment]
`你就不能换个好点的梯子`
