### ISSUE TITLE
target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 这个是什么原因？

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#7481]
[package/Makefile:110: /home/xxoo/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xxoo/lede'
make: *** [/home/xxoo/lede/include/toplevel.mk:230: world] Error 2
编译星际宝盒编译出错，请问这个是源码的问题还是什么？

**Comment by EnnawYang** [comment]
不知道

**Comment by acooler15** [comment]
`make -j1 V=sc`
