### ISSUE TITLE
请问关于ipsec和防火墙的问题

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#7482]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ 是] 没有类似的issue

### (1) 具体问题
今天编译了固件
1:ipsec启动后无论是安卓手机还是win10通过局域网，或者外网连接路由器都不成功（因为路由直接拨号了，没有做端口映射），一年多前大雕的源码编译出来可以用的。请问是现在的ipsec出问题了么？
2:路由下挂了一台群晖，用群晖开ipsec服务在局域网内可以正常连上。但是在外网就连不上了（做了udp的500和4500转发到群晖上，其他防火墙设置默认没修改。）请问是防火墙设置有问题么？
A：

### (2) 路由器型号和固件版本

A：路由:xiaoyu c5，固件版本	OpenWrt R21.7.15 / LuCI Master (git-21.200.60006-aa12cbf

### (3) 详细日志

A：

**Comment by galaxyskyknight** [comment]
用n2n多好，比什么openvpn/openconnect/ipsec/softvpn都好
