### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by CJM88888** [coolsnowwolf/lede#7483]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译报错

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：make[4]: Leaving directory '/home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0'
touch /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.built
rm -rf /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark.installed /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark
mkdir -p /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/bin
install -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/coremark /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/bin/
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/etc
install -m0755 ./coremark.sh /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/etc/
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/etc/uci-defaults
install -m0755 ./coremark /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/etc/uci-defaults/xxx-coremark
touch /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark.installed
mkdir -p /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/stamp
SHELL= flock /home/cjm/lede/tmp/.root-copy.flock -c 'cp -fpR /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/.pkgdir/coremark/. /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/'
touch /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/root-bcm53xx/stamp/.coremark_installed
mkdir -p /home/cjm/lede/bin/targets/bcm53xx/generic/packages /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/CONTROL /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/pkginfo
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/bin
install -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/coremark /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/bin/
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/etc
install -m0755 ./coremark.sh /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/etc/
install -d -m0755 /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/etc/uci-defaults
install -m0755 ./coremark /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/etc/uci-defaults/xxx-coremark
find /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="arm-openwrt-linux-muslgnueabi-"  NO_RENAME=1 ; NM="arm-openwrt-linux-muslgnueabi-nm" STRIP="/home/cjm/lede/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/home/cjm/lede/scripts/strip-kmod.sh" PATCHELF="/home/cjm/lede/staging_dir/host/bin/patchelf" /home/cjm/lede/scripts/rstrip.sh /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark
rstrip.sh: /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/bin/coremark: executable
(cd /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_coremark_postinst" > postinst-pkg; chmod 0755 postinst-pkg; )
install -d -m0755 /home/cjm/lede/bin/packages/arm_cortex-a9/packages
/home/cjm/lede/staging_dir/host/bin/fakeroot /home/cjm/lede/scripts/ipkg-build -m "" /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark /home/cjm/lede/bin/packages/arm_cortex-a9/packages
Packaged contents of /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/coremark-1541482bf3e6ef7f5c69f5be76b14537b60833d0/ipkg-arm_cortex-a9/coremark into /home/cjm/lede/bin/packages/arm_cortex-a9/packages/coremark_2021-03-12-1541482b-2_arm_cortex-a9.ipk
echo "coremark" >> /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/pkginfo/coremark.default.install
make[3]: Leaving directory '/home/cjm/lede/feeds/packages/utils/coremark'
time: package/feeds/packages/coremark/compile#24.51#10.99#38.50
make[3]: Entering directory '/home/cjm/lede/feeds/packages/utils/docker'
mkdir -p /home/cjm/lede/dl
SHELL= flock /home/cjm/lede/tmp/.docker-20.10.7.tar.gz.flock -c '       /home/cjm/lede/scripts/download.pl "/home/cjm/lede/dl" "docker-20.10.7.tar.gz" "0a7848b1b5031483de075433506d0448ddf834368d9c73770e453e0b89b49747" "" "https://codeload.github.com/docker/cli/tar.gz/v20.10.7?"    '
touch /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/docker-20.10.7/.prepared_41e618d1055f0dc1d90afd10000c9d28_6664517399ebbbc92a37c5bb081b5c53_check
. /home/cjm/lede/include/shell.sh; gzip -dc /home/cjm/lede/dl/docker-20.10.7.tar.gz | tar -C /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/docker-20.10.7 --strip-components 1 -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/docker-20.10.7
# Verify PKG_GIT_SHORT_COMMIT
( EXPECTED_PKG_GIT_SHORT_COMMIT=$( /home/cjm/lede/feeds/packages/utils/docker/../dockerd/git-short-commit.sh 'github.com/docker/cli' 'v20.10.7' '/home/cjm/lede/tmp/git-short-commit/docker-20.10.7' ); if [ "${EXPECTED_PKG_GIT_SHORT_COMMIT}" != "f0df350" ]; then echo "ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=${EXPECTED_PKG_GIT_SHORT_COMMIT}', found 'PKG_GIT_SHORT_COMMIT:=f0df350'"; exit 1; fi )
Trying remote 'github.com/docker/cli'
fatal: 'github.com/docker/cli' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Trying remote 'https://github.com/docker/cli'
fatal: unable to access 'https://github.com/docker/cli/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Trying remote 'http://github.com/docker/cli'
fatal: unable to access 'http://github.com/docker/cli/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Trying remote 'git@github.com/docker/cli'
fatal: 'git@github.com/docker/cli' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: Expected 'PKG_GIT_SHORT_COMMIT:=', found 'PKG_GIT_SHORT_COMMIT:=f0df350'
make[3]: *** [Makefile:81: /home/cjm/lede/build_dir/target-arm_cortex-a9_musl_eabi/docker-20.10.7/.prepared_41e618d1055f0dc1d90afd10000c9d28_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/cjm/lede/feeds/packages/utils/docker'
time: package/feeds/packages/docker/compile#1.37#5.57#269.19
    ERROR: package/feeds/packages/docker failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/docker/compile] Error 1
make[2]: Leaving directory '/home/cjm/lede'
make[1]: *** [package/Makefile:110: /home/cjm/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/cjm/lede'
make: *** [/home/cjm/lede/include/toplevel.mk:230: world] Error 2

**Comment by EnnawYang** [comment]
网络问题
