### ISSUE TITLE
防火墙 通信规则里的目标地址没有ipv6

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#7489]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [* ] 没有类似的issue

## 2. 详细叙述
看到有的帖子说现在的op防火墙通信规则里面的目标地址已经可以显示ipv6了。可是我刚编译出来的固件，这个目标地址还是只能显示ipv4的地址列表让我选择。请问是什么问题？有什么没添加进编译么？
### (1) 具体问题

这个是今天编译的图片
![1](https://user-images.githubusercontent.com/30990861/126753323-8fd99d90-6ecb-4e80-ba9b-d5d6e4638044.png)

这个是别人发的图片
![1](https://user-images.githubusercontent.com/30990861/126756849-fc72db8f-c528-453f-b4df-a1f7520468c9.png)

**Comment by acooler15** [comment]
官方openwrt有

**Comment by bonnyandsky** [comment]
> 官方openwrt有

原来是这样。谢谢解惑
