### ISSUE TITLE
openwrt稳定版分支最新版源码编译不过

### ISSUE THREAD

**Issue by itfish92** [coolsnowwolf/lede#7491]
看报错和vlmcsd有关

**Comment by bilibilistack** [comment]
SHELL= flock /mnt/sdb1/lede/tmp/.vlmcsd-svn1113.tar.gz.flock -c '       /mnt/sdb1/lede/scripts/download.pl "/mnt/sdb1/lede/dl" "vlmcs                            d-svn1113.tar.gz" "62f55c48f5de1249c2348ab6b96dabbe7e38899230954b0c8774efb01d9c42cc" "" "https://codeload.github.com/Wind4/vlmcsd/tar                            .gz/svn1113?"    '
Hash of the local file vlmcsd-svn1113.tar.gz does not match (file: 9510cf4e48e809b09fea60f29e41d3a0fb0f58257644dc60929ad503e8a156af,                             requested: 62f55c48f5de1249c2348ab6b96dabbe7e38899230954b0c8774efb01d9c42cc) - deleting download.
make[2]: *** [Makefile:45: /mnt/sdb1/lede/dl/vlmcsd-svn1113.tar.gz] Error 2
make[2]: Leaving directory '/mnt/sdb1/lede/package/lean/vlmcsd'
time: package/lean/vlmcsd/download#0.15#0.04#0.19
    ERROR: package/lean/vlmcsd failed to build.
make[1]: *** [package/Makefile:116: package/lean/vlmcsd/download] Error 1
