### ISSUE TITLE
lede最新版本源码adblock、noddos clients访问出错

### ISSUE THREAD

**Issue by ghost** [coolsnowwolf/lede#7492]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

访问adblock、noddos clients出错，使用uhttpd webserver

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：x86_64-efi

kernel ver: 5.10.51

lede ver: R21.7.15/git-21.202.07504-88c61f9

### (3) 详细日志

A：

noddos clients:

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute template dispatcher target for entry '/admin/status/noddos'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'noddos/clients'.
A runtime error occured: [string "/usr/lib/lua/luci/view/noddos/clients.htm"]:16: bad argument #1 to 'input' (/var/lib/noddos/DeviceProfiles.json: No such file or directory)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

adblock:

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute firstchild dispatcher target for entry '/admin/services/adblock'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/adblock/tab_from_cbi'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/adblock/overview_tab.lua:21: attempt to index field 'data' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by liuyanantj** [comment]
adblock的问题我也遇到了  还没修复也没回复 现在暂时用另一个代替了
