### ISSUE TITLE
请求恢复mt7621默认超频1000MHz

### ISSUE THREAD

**Issue by Luastonsu** [coolsnowwolf/lede#7494]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
请求恢复MT7621 CPU的默认超频1000MHz，breed在很早之前的版本中就取消了超频选项
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
Xiaomi Redmi AC2100
A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
然后就有人启不动了…

**Comment by Lrvineshaw** [comment]
夏天还是保守点，我一般天冷才超频

**Comment by Luastonsu** [comment]
> 然后就有人启不动了…

那大佬能不能指导下5.4内核如何超频，现在使用4.14内核总是编译失败

**Comment by Luastonsu** [comment]
> 夏天还是保守点，我一般天冷才超频

就是往冒烟去的，不怕

**Comment by itfish92** [comment]
传家宝k2p的breed超频一直在啊，看了下最新的是2020年的breed

**Comment by hzjixiang** [comment]
体质不同 超频很多不稳定的现象，甚至不能开机！！！如果觉得性能不够建议换ARM的路由

**Comment by Luastonsu** [comment]
> 传家宝k2p的breed超频一直在啊，看了下最新的是2020年的breed

也是mt7621？可能我的breed版本问题

**Comment by Luastonsu** [comment]
> 传家宝k2p的breed超频一直在啊，看了下最新的是2020年的breed

刚更新了breed，还是没有。查询k2p等型号有，小米r3g没有
现在只能从固件编译方面想办法了，毕竟默认880运行开开插件后连luci界面都刷不出来

**Comment by yinzhefuyun** [comment]
联发科去breed超频

**Comment by Luastonsu** [comment]
> 联发科去breed超频

部分mtk路由breed没有超频选项，比如小米r3g

**Comment by LeviMarvin** [comment]
> > 联发科去breed超频
> 
> 部分mtk路由breed没有超频选项，比如小米r3g

是的，我的R3G上Breed一看也没有超频选项，请问除了编译OpenWRT外还有没有办法超频呀

**Comment by lovehackintosh** [comment]
全新克隆一下源码,下载https://raw.githubusercontent.com/coolsnowwolf/lede/5be81314bb08934fbe03c2e26191b80f021b0d2b/target/linux/ramips/patches-5.4/102-mt7621-fix-cpu-clk-add-clkdev.patch这个文件替换到lede/target/linux/ramips/patches-5.4/ ，然后正常编译
