### ISSUE TITLE
K2P 红米2100 R3G，7621怎么选择闭源驱动？

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#7508]
编译了K2P 红米2100 R3G，刷了发现都是开源驱动的，想选闭源驱动试下，请问要点选择哪里才是无线闭源的

**Comment by Boos4721** [comment]
https://github.com/coolsnowwolf/lede/tree/master/package/lean/mt

**Comment by AmadeusGhost** [comment]
k2p 不是默认用的闭源驱动么…

**Comment by coolsnowwolf** [comment]
K2P 是闭源驱动，适配了原生 luci
