### ISSUE TITLE
纯小白，有些问题想要请教

### ISSUE THREAD

**Issue by KevinxYep** [coolsnowwolf/lede#7516]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

1. J4105软路由实体机安装openwrt，有时候会突然重启一下，不知道是什么原因。
2. 在菜单里没有passwall和smartdns，请问这两个插件可以安装吗？

### (1) 具体问题

A：1. J4105软路由实体机安装openwrt，有时候会突然重启一下，不知道是什么原因。
2. 在菜单里没有passwall和smartdns，请问这两个插件可以安装吗？

### (2) 路由器型号和固件版本

A：J4105，Powered by LuCI Master (git-21.200.60006-aa12cbf) / OpenWrt R21.7.15

### (3) 详细日志

A：

**Comment by hcym** [comment]
软故障只能自己仔细观察，哪两个插件可以一起编译，我是一直编译pass的，就为了负载均衡，不然大雕的haproxy不好用就抓瞎了

**Comment by KevinxYep** [comment]
谢谢
