### ISSUE TITLE
感谢大佬，请问怎么实现对R4S 1G版机器的支持！

### ISSUE THREAD

**Issue by dwx1983** [coolsnowwolf/lede#7527]
编译时候有R4S 4G版的选项，但是编译出来固件对1G版机器并不适用，手上只有1G版的机器，而且性能也够用。请问怎么手动实现编译时对1G版机器的支持？谢谢！

**Comment by DanielChen008** [comment]
周末我刚编译过，直接选的 4G 版编译，在 1G 版本后台 upgrade 升级完全 OK 的。
