### ISSUE TITLE
红米k30pro miui 安卓手机pptp连不上openwrt

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#7538]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [* ] 没有类似的issue

## 2. 详细叙述
win10pptp连接没问题，就是手机连不上，不管打开还是关闭ppp加密选项都连接失败（192.168.0.3是vpn路由器lan口的本地地址）
![IMG_20210727_102316](https://user-images.githubusercontent.com/30990861/127085223-33182e5e-8aab-407c-97b7-f58bc3493de8.jpg)
![IMG_20210727_102235](https://user-images.githubusercontent.com/30990861/127085237-1f107525-9877-44b4-8d48-15383ada82fb.jpg)

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：Intel(R) Atom(TM) CPU C2538 @ 2.40GHz : 1 Core 1 Thread
固件版本	OpenWrt R21.7.15 / LuCI Master (git-21.206.25982-60d43ca)

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/127091029-c17626f9-eb6b-4a14-b2c0-8555e8cdb084.png)
