### ISSUE TITLE
不带日志的 issues 都会被关闭，这里不是论坛

### ISSUE THREAD

**Issue by coolsnowwolf** [coolsnowwolf/lede#7539]
![image](https://user-images.githubusercontent.com/31687149/127091385-895b1be7-9103-4094-9f60-ca3d712e7add.png)

**Comment by kingzleshe** [comment]
要不L大开个论坛吧
https://docs.github.com/en/discussions/quickstart

**Comment by bonnyandsky** [comment]
> 要不L大开个论坛吧
> https://docs.github.com/en/discussions/quickstart

这个办法好

**Comment by galaxyskyknight** [comment]
支持，issue用于专门的特定问题diag，带上日志和详细描述, 论坛讨论各种需求和问题求助，两者定位分开。否则只码代码不解答低中高级的各类实用性问题和给与用户支持，了解用户需求，也是闭门造车。

**Comment by VergilGao** [comment]
我看box2d已经开了论坛了，我也觉得开论坛把一些讨论性质的内容分流过去会更好，这样issue区就能专门做bug反馈了。
此外论坛的某些讨论也可以整理下来作为使用文档，丰富社区内容。

**Comment by WYC-2020** [comment]
要么没日志，要么就是多线程的日志，找谁都算不出来
