### ISSUE TITLE
同步 iwinfo: bump version 这个更新后SoftEther VPN 服务器的openvpn连不上

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#7567]
X86
同步这个更新之前没有问题，同步后编译的固件有OPENVPN连不上
[https://raw.githubusercontent.com/mitsukileung/helloworld/1eba19943c80f902cf9895218ea57adc8fe98ca8/Screenshot_20210731_124936.jpg](url)

**Comment by haohaoget** [comment]
确实我也有这个问题，内网ip直接连都连不上但是管理软件可以连上。docker也未运行，还是退回了老版本🌚🌚
