### ISSUE TITLE
上海电信，光猫已设置桥接模式，如何获得ipv6地址？

### ISSUE THREAD

**Issue by PureWhiteWu** [coolsnowwolf/lede#757]
1. 地点：上海
2. ISP：电信
3. 光猫已设置为桥接模式，WAN接口可以通过PPPoE拨号获得ipv4接口

想问一下如何设置可以获得ipv6地址？

希望各位大大抽空帮忙看看，十分感谢！

**Comment by wxlost** [comment]
https://github.com/coolsnowwolf/lede/issues/704

**Comment by wxlost** [comment]
https://github.com/coolsnowwolf/lede/issues/692

**Comment by PureWhiteWu** [comment]
@wxlost 我更新了，不知道为什么直接install没用，要先find再install就好了。。。。
如果我要获取ipv6的话是直接用dhcpv6就好了么？

**Comment by PureWhiteWu** [comment]
实测下来DHCPv6没有获取到地址

**Comment by fsyxhua** [comment]
我的用10月20号的2deb00db70893cb0ae6d454287919ba487dd06d7编译后能，正常获得v6地址，但是更新到最新代码后就不行，不知道哪里有问题，对比了两个版本的软件包都一致，就是版本不一样，不知道是哪里的问题？
