### ISSUE TITLE
make kernel_menuconfig错误

### ISSUE THREAD

**Issue by DH-FU** [coolsnowwolf/lede#7574]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：make kernel_menuconfig 失败

### (2) 路由器型号和固件版本

A：bcm2711 最新固件

### (3) 详细日志

A：make[7]: *** [Makefile:3441: install-data-hook] Error 1
make[7]: Leaving directory '/media/fdh/RJ/A/immortalwrt/build_dir/host/libressl-3.3.3/man'
make[6]: *** [Makefile:854: install-data-am] Error 2
make[6]: Leaving directory '/media/fdh/RJ/A/immortalwrt/build_dir/host/libressl-3.3.3/man'
make[5]: *** [Makefile:806: install-am] Error 2
make[5]: Leaving directory '/media/fdh/RJ/A/immortalwrt/build_dir/host/libressl-3.3.3/man'
make[4]: *** [Makefile:461: install-recursive] Error 1
make[4]: Leaving directory '/media/fdh/RJ/A/immortalwrt/build_dir/host/libressl-3.3.3'
make[3]: *** [Makefile:34: /media/fdh/RJ/A/immortalwrt/staging_dir/host/stamp/.libressl_installed] Error 2
make[3]: Leaving directory '/media/fdh/RJ/A/immortalwrt/tools/libressl'
time: tools/libressl/compile#93.59#28.00#145.28
    ERROR: tools/libressl failed to build.
make[2]: *** [tools/Makefile:162: tools/libressl/compile] Error 1
make[2]: Leaving directory '/media/fdh/RJ/A/immortalwrt'
make[1]: *** [tools/Makefile:158: /media/fdh/RJ/A/immortalwrt/staging_dir/host/stamp/.tools_compile_yyynyynnyyyyynyyyyyynyynnyyynyyyyyyyyyyyyyyyyynynnyyyynynyyyyy] Error 2
make[1]: Leaving directory '/media/fdh/RJ/A/immortalwrt'
make: *** [/media/fdh/RJ/A/immortalwrt/include/toplevel.mk:230：toolchain/install] 错误 2

**Comment by EnnawYang** [comment]
我记得这里好像不是 `immortalwrt` 吧？
