### ISSUE TITLE
如何编译指定版本的qbittorrent

### ISSUE THREAD

**Issue by yubanmeiqin9048** [coolsnowwolf/lede#7576]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：需要编译qbittorrent4.1.9的版本，但仅修改qbittorrent的Makefile版本号为4.1.9.1报错

### (2) 路由器型号和固件版本

A：arm64

### (3) 详细日志

A：
[ ! -d ./src/ ] || cp -fpR ./src/* /home/zhang/lede/build_dir/hostpkg/boost_1_71_0

Applying ./patches/010-mips64-fiber.patch using plaintext: 
patching file boost/fiber/detail/cpu_relax.hpp
Hunk #1 FAILED at 47.
1 out of 1 hunk FAILED -- saving rejects to file boost/fiber/detail/cpu_relax.hpp.rej
Patch failed!  Please fix ./patches/010-mips64-fiber.patch!
make[3]: *** [Makefile:504: /home/zhang/lede/build_dir/hostpkg/boost_1_71_0/.prepareda442706fe3f7efed90e9bf55811c66e0_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/zhang/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#14.00#5.81#37.26
    ERROR: package/feeds/packages/boost [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/boost/host/compile] Error 1
make[2]: Leaving directory '/home/zhang/lede'
make[1]: *** [package/Makefile:110: /home/zhang/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhang/lede'
make: *** [/home/zhang/lede/include/toplevel.mk:230: world] Error 2

**Comment by coolsnowwolf** [comment]
qbittorrent 对特定 qt5 , libqbittorrent , boost 版本都有特定要求，请认真修改代码支持

**Comment by yubanmeiqin9048** [comment]
> qbittorrent 对特定 qt5 , libqbittorrent , boost 版本都有特定要求，请认真修改代码支持

感谢大雕回复，也就是说需要修改qttools，qtbase，rlibqbittorrent , boost 中Makefile的PKG_HASH和PKG_VERSION到对应的版本才行

**Comment by yubanmeiqin9048** [comment]
> qbittorrent 对特定 qt5 , libqbittorrent , boost 版本都有特定要求，请认真修改代码支持

按照您的说法，我将BOOST 的版本修改为1.71.0 将qttools，qtbase文件删掉放入qt5版本5.12.2，OpenSSL版本改为1.1.1d这些修改都参考这次更新#2982结果还是报错
