### ISSUE TITLE
DNSmasq问题

### ISSUE THREAD

**Issue by mrclock** [coolsnowwolf/lede#7581]
最近编译的版本，DNSmasq失效，里面配置了iptv获取b面IP的信息。
切回老版本一切正常。恩山上下了其他大大编译的大雕仓库最新固件，也是同样问题。

**Comment by hcym** [comment]
退回去了，正常使用才是王道，haproxy也是如此

**Comment by mrclock** [comment]
最新版本已经修复这个问题了，应该是修复了DNSmasq.init，关闭issus。
