### ISSUE TITLE
编译报错，请达人指点下

### ISSUE THREAD

**Issue by starambler** [coolsnowwolf/lede#7588]
编译环境github action  ubuntu20.02

报错如下：
Configuring kmod-fs-squashfs.
Configuring kmod-i2c-algo-bit.
Configuring kmod-igb.
Configuring kmod-ipt-offload.
Configuring kmod-bnx2.
Configuring vsftpd.
Configuring urngd.
Configuring libnet-1.2.x.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:109: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
make[1]: Leaving directory '/workdir/openwrt'
Error: Process completed with exit code 2.

**Comment by EnnawYang** [comment]
请提供详细日志

**Comment by starambler** [comment]
Installing vim-fuller (8.2-3) to root...
Installing vsftpd (3.0.3-3) to root...
Package wget-ssl (1.21.1-1) installed in root is up to date.
Package xray-core (1.4.2-1) installed in root is up to date.
Package xray-geodata (1.4.2-1) installed in root is up to date.
Package libyaml (0.2.5-1) installed in root is up to date.
Package zerotier (1.6.5-1) installed in root is up to date.
Configuring libgcc1.
Configuring libc.
Configuring terminfo.
Configuring kernel.
Configuring kmod-crypto-hash.
Configuring kmod-crypto-lib-blake2s.
Configuring kmod-crypto-lib-chacha20.
Configuring kmod-crypto-lib-poly1305.
Configuring kmod-crypto-lib-chacha20poly1305.
Configuring kmod-crypto-kpp.
Configuring kmod-crypto-lib-curve25519.
Configuring kmod-udptunnel4.
Configuring kmod-udptunnel6.
Configuring kmod-wireguard.
Configuring wireguard-tools.
Configuring luci-proto-wireguard.
Configuring libubox20210516.
Configuring libuci20130104.
Configuring liblua5.1.5.
Configuring libuci-lua.
Configuring luci-theme-material.
Configuring libopenssl1.1.
Configuring zlib.
Configuring openssh-sftp-server.
Configuring liblucihttp0.
Configuring libubus20210630.
Configuring cgi-io.
Configuring lua.
Configuring luci-lib-nixio.
Configuring libnl-tiny1.
Configuring luci-lib-ip.
Configuring libjson-c5.
Configuring luci-lib-jsonc.
Configuring liblucihttp-lua.
Configuring luci-lib-base.
Configuring libpthread.
Configuring librt.
Configuring libuuid1.
Configuring libuv1.
Configuring libmnl0.
Configuring netdata.
Configuring libf2fs6.
Configuring mkf2fs.
Configuring libuclient20201210.
Configuring uclient-fetch.
Configuring opkg.
Configuring libcap.
Configuring libwebsockets-full.
Configuring kmod-nf-reject.
Configuring kmod-nf-ipt.
Configuring kmod-ipt-core.
Configuring libxtables12.
Configuring libip4tc2.
Configuring libip6tc2.
Configuring iptables.
Configuring kmod-ipt-extra.
Configuring iptables-mod-extra.
Configuring kmod-nls-base.
Configuring kmod-usb-core.
Configuring luci-app-opkg.
Configuring libblobmsg-json20210516.
Configuring ubusd.
Configuring ubus.
Configuring kmod-crypto-null.
Configuring kmod-crypto-aead.
Configuring kmod-crypto-pcompress.
Configuring kmod-crypto-manager.
Configuring kmod-mdio.
Configuring kmod-pps.
Configuring kmod-ptp.
Configuring kmod-hwmon-core.
Configuring kmod-libphy.
Configuring kmod-ixgbe.
Configuring rpcd.
Configuring busybox.
Configuring kmod-lib-zlib-deflate.
Configuring ddns-scripts-services.
Configuring libelf1.
Configuring libbpf0.
Configuring ip-full.
Configuring kmod-nfnetlink.
Configuring libubus-lua.
Configuring kmod-nf-conntrack.
Configuring kmod-ipt-conntrack.
Configuring kmod-nf-conntrack6.
Configuring kmod-nf-reject6.
Configuring kmod-nf-ipt6.
Configuring kmod-ip6tables.
Configuring kmod-ipt-tproxy.
Configuring libncurses6.
Configuring nano.
Configuring kmod-tun.
Configuring libiwinfo-data.
Configuring libiwinfo20210430.
Configuring libiwinfo-lua.
Configuring ssocks.
Configuring kmod-lib-zlib-inflate.
Configuring kmod-crypto-acompress.
Configuring kmod-crypto-deflate.
Configuring libreadline8.
Configuring bash.
Configuring libgmp10.
Configuring libruby3.0.
Configuring ruby.
Configuring libdb47.
Configuring ruby-dbm.
Configuring vim-fuller.
Configuring bnx2-firmware.
Configuring libpcre.
Configuring libltdl7.
Configuring liblua5.3-5.3.
Configuring libatomic1.
Configuring haproxy.
Configuring kmod-crypto-md5.
Configuring rpcd-mod-file.
Configuring rpcd-mod-luci.
Configuring luci-base.
Configuring luci-mod-system.
Configuring libopenssl-conf.
Configuring openssl-util.
Configuring kmod-nf-flow.
Configuring libwolfssl4.7.0.66253b90.
Configuring libustream-wolfssl20201210.
Configuring kmod-lib-crc-ccitt.
Configuring kmod-usb-ehci.
Configuring kmod-usb2.
Configuring kmod-usb2-pci.
Configuring liblzo2.
Configuring getrandom.
Configuring pdnsd-alt.
Configuring libsodium.
Configuring softethervpn5-libs.
Configuring softethervpn5-client.
Configuring luci-theme-openwrt.
Configuring kmod-crypto-authenc.
Configuring kmod-crypto-cbc.
Configuring kmod-crypto-des.
Configuring kmod-crypto-echainiv.
Configuring kmod-crypto-hmac.
Configuring kmod-crypto-sha1.
Configuring kmod-ipsec.
Configuring libcap-bin.
Configuring libev.
Configuring r8169-firmware.
Configuring luci-theme-bootstrap.
Configuring libprotobuf-c.
Configuring kmod-slhc.
Configuring kmod-ppp.
Configuring kmod-pppox.
Configuring kmod-pppoe.
Configuring ipt2socks.
Configuring libiconv-full2.
Configuring luci-app-wireguard.
Configuring jshn.
Configuring netifd.
Configuring jsonfilter.
Configuring usign.
Configuring openwrt-keyring.
Configuring ubox.
Configuring fstools.
Configuring fwtool.
Configuring base-files.
Configuring kmod-nf-nat.
Configuring kmod-input-core.
Configuring libjson-script20210516.
Configuring ttyd.
Configuring wget-ssl.
Configuring luci-app-adguardhome.
Configuring coreutils.
Configuring coreutils-base64.
Configuring libblkid1.
Configuring libsmartcols1.
Configuring partx-utils.
Configuring ddns-scripts.
Configuring libstdcpp6.
Configuring boost.
Configuring boost-system.
Configuring boost-program_options.
Configuring trojan-plus.
Configuring kmod-iptunnel.
Configuring kmod-iptunnel4.
Configuring kmod-sit.
Configuring 6in4.
Configuring kmod-mii.
Configuring kmod-phy-realtek.
Configuring kmod-r8169.
Configuring shadowsocks-libev-config.
Configuring kmod-usb-ohci.
Configuring libminiupnpc.
Configuring libnatpmp1.
Configuring zerotier.
Configuring procd.
Configuring resolveip.
Configuring luci-app-zerotier.
Configuring kmod-nf-conntrack-netlink.
Configuring nlbwmon.
Configuring kmod-crypto-sha256.
Configuring libnfnetlink0.
Configuring libnetfilter-conntrack3.
Configuring ruby-digest.
Configuring ruby-enc.
Configuring ruby-pstore.
Configuring kmod-nf-nat6.
Configuring dns2socks.
Configuring screen.
Configuring kmod-ipt-ipsec.
Configuring iptables-mod-ipsec.
Configuring luci-mod-status.
Configuring kmod-i2c-core.
Configuring trojan-go.
Configuring libmbedtls12.
Configuring kmod-nls-cp437.
Configuring kmod-nls-iso8859-1.
Configuring kmod-nls-utf8.
Configuring kmod-fs-vfat.
Configuring luci-lib-ipkg.
Configuring rpcd-mod-iwinfo.
Configuring luci-mod-network.
Configuring luci-mod-admin-full.
Configuring luci-app-ddns.
Configuring kmod-usb3.
Configuring kmod-ipt-nat.
Configuring firewall.
Configuring ruby-forwardable.
Configuring libxml2.
Configuring luci-app-firewall.
Configuring ruby-stringio.
Configuring ruby-bigdecimal.
Configuring ruby-date.
Configuring ruby-strscan.
Configuring libyaml.
Configuring ruby-psych.
Configuring ruby-yaml.
Configuring grub2-efi.
Configuring libnettle8.
Configuring kmod-ipt-ipset.
Configuring dnsmasq-full.
Configuring coreutils-nohup.
Configuring ca-bundle.
Configuring libcurl4.
Configuring curl.
Configuring ca-certificates.
Configuring libipset13.
Configuring ipset.
Configuring iptables-mod-tproxy.
Configuring luci-app-openclash.
Configuring v2ray-plugin.
Configuring libgnutls.
Configuring kmod-fs-nfs-common.
Configuring kmod-dnsresolver.
Configuring kmod-fs-nfs.
Configuring kmod-fs-nfs-v3.
Configuring kmod-fs-nfs-v4.
Configuring odhcp6c.
Configuring unzip.
Configuring softethervpn5-server.
Configuring uci.
Configuring grub2.
Configuring dropbear.
Configuring tree.
Configuring softethervpn5-bridge.
Configuring microsocks.
Configuring luci-compat.
Configuring mtd.
Collected errors:
Configuring odhcpd-ipv6only.
 * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
	But that file is already provided by package  * libustream-wolfssl20201210
 * opkg_install_cmd: Cannot install package libustream-openssl20201210.
Configuring libhttp-parser.
Configuring luci-i18n-wireguard-zh-cn.
Configuring urandom-seed.
Configuring luci-proto-ppp.
Configuring certtool.
Configuring kmod-crypto-wq.
Configuring libcomerr0.
Configuring ppp.
Configuring logd.
Configuring xray-core.
Configuring xray-geodata.
Configuring luci-app-softethervpn.
Configuring shadowsocks-libev-ss-local.
Configuring luci-proto-ipv6.
Configuring libudns.
Configuring shadowsocksr-libev-ssr-local.
Configuring openvpn-openssl.
Configuring luci-i18n-ddns-zh-cn.
Configuring simple-obfs.
Configuring libss2.
Configuring libext2fs2.
Configuring luci-app-accesscontrol.
Configuring e2fsprogs.
Configuring kmod-e1000.
Configuring libcares.
Configuring openvpn-easy-rsa.
Configuring libpcap1.
Configuring uhttpd.
Configuring kmod-iptunnel6.
Configuring shadowsocks-libev-ss-redir.
Configuring kmod-ipsec4.
Configuring kmod-ipsec6.
Configuring ip6tables.
Configuring tcping.
Configuring shadowsocks-libev-ss-server.
Configuring shadowsocksr-libev-ssr-redir.
Configuring luci-app-passwall.
Configuring luci-i18n-passwall-zh-cn.
Configuring kmod-forcedeth.
Configuring luci-i18n-base-zh-cn.
Configuring kmod-usb-ohci-pci.
Configuring kmod-crypto-rng.
Configuring uhttpd-mod-ubus.
Configuring rpcd-mod-rrdns.
Configuring luci.
Configuring luci-i18n-opkg-zh-cn.
Configuring kmod-ipt-nat6.
Configuring kmod-e1000e.
Configuring libevent2-7.
Configuring kmod-button-hotplug.
Configuring kmod-fs-squashfs.
Configuring kmod-i2c-algo-bit.
Configuring kmod-igb.
Configuring kmod-ipt-offload.
Configuring kmod-bnx2.
Configuring vsftpd.
Configuring urngd.
Configuring libnet-1.2.x.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/Makefile:69: package/install] Error 255
make[1]: *** [package/Makefile:109: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by EnnawYang** [comment]
libustream-wolfssl与libustream-openssl冲突

**Comment by starambler** [comment]
请问选哪一个？我在试试

**Comment by EnnawYang** [comment]
libustream-openssl是ssrp的依赖，另一个我不知道是哪个的依赖
