### ISSUE TITLE
请问...R4S 1G的版本 在target Profile里面怎么选?

### ISSUE THREAD

**Issue by showme2005** [coolsnowwolf/lede#7590]
请问...R4S 1G的版本 在target Profile里面怎么选?

**Comment by liuyanantj** [comment]
同问啊  貌似新的里面只有4g版本的

**Comment by minlang112** [comment]
本来R4S就是RMB收割机了，还买1G版本的……

**Comment by liuyanantj** [comment]
> 本来R4S就是RMB收割机了，还买1G版本的……

很早买的 当时4G版本的普遍没货  而且做个软路由 1G妥妥的了 还指望着这个做all in one么 希望代码还是能支持下吧

**Comment by liuyanantj** [comment]
还是希望大雕能增加下r4s  1g的支持  毕竟还有一帮子用户呢 万分感谢

**Comment by liuyanantj** [comment]
大雕在热心群友的建议下  已经更新代码支持r4s 1g版本了  可以无脑刷了 貌似还调节了超频的吧 跑分从3.8w到5w了  耍起来呀

**Comment by Jason6111** [comment]
> 请问...R4S 1G的版本 在target Profile里面怎么选?

选4g版应该就行

**Comment by DanielChen008** [comment]
处理器一样，内存不一样，之前显示 XXX 4G，现在 L大已经把4G去掉了，只留了名字。
所以之前其实直接编译4G版本的就可以给 1G 的用，跟 X86 一样呀，那些工控机、网友自己用的旧平台啥的，内存容量五花八门，还不是只管编译 X86 即可。

**Comment by coolsnowwolf** [comment]
楼上的，R4S 1G 和 4G 之前因为补丁问题，是不通刷的 现在更新支持了

**Comment by showme2005** [comment]
> 楼上的，R4S 1G 和 4G 之前因为补丁问题，是不通刷的 现在更新支持了

 感谢大神。。。

**Comment by DanielChen008** [comment]
> 楼上的，R4S 1G 和 4G 之前因为补丁问题，是不通刷的 现在更新支持了

L 大亲自纠错，学习了

**Comment by adamgonglj** [comment]
> 楼上的，R4S 1G 和 4G 之前因为补丁问题，是不通刷的 现在更新支持了

感谢L大
