### ISSUE TITLE
 make[3] -C package/qca/nss/qca-nss-ecm compile     ERROR: package/qca/nss/qca-nss-ecm failed to build (build variant: noload).

### ISSUE THREAD

**Issue by WikiHacker** [coolsnowwolf/lede#7591]
make[3] -C package/qca/nss/qca-nss-ecm compile
    ERROR: package/qca/nss/qca-nss-ecm failed to build (build variant: noload).

r2s and r4s

**Comment by EnnawYang** [comment]
？

**Comment by minlang112** [comment]
why did you compile qca-nss on RK33XX plantform？

**Comment by WikiHacker** [comment]
> why did you compile qca-nss on RK33XX plantform？

Compiling on Ubuntu 20.04 , for device R2S and R4S.
