### ISSUE TITLE
更新内核

### ISSUE THREAD

**Issue by Eay5** [coolsnowwolf/lede#7592]
什么时候更新内核

**Comment by Sauryc** [comment]
IPQ4019同求更新一下内核大版本

**Comment by uniessey** [comment]
自己动动手，把 target/linux/<cpu架构>/Makefile 文件中的KERNEL_PATCHVER:=5.4，改为KERNEL_PATCHVER:=5.10，然后make target/linux/compile 测试是否适配成功。

**Comment by uniessey** [comment]
> 什么时候更新内核

自己动动手，把 target/linux/<cpu架构>/Makefile 文件中的KERNEL_PATCHVER:=5.4，改为KERNEL_PATCHVER:=5.10，然后make target/linux/compile 测试是否适配成功。

**Comment by Eay5** [comment]
好的，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月3日(星期二) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [coolsnowwolf/lede] 更新内核 (#7592)





 
自己动动手，把 target/linux/<cpu架构&gt;/Makefile 文件中的KERNEL_PATCHVER:=5.4，改为KERNEL_PATCHVER:=5.10，然后make target/linux/compile 测试是否适配成功。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
