### ISSUE TITLE
github action 编译报错 ：out of space?请问高手该如何破？

### ISSUE THREAD

**Issue by starambler** [coolsnowwolf/lede#7603]
github action :ubuntu20.04 
日志
make[5]: Entering directory '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND  objtool
  CHK     include/generated/compile.h
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
  LD      .tmp_vmlinux.kallsyms1
  KSYM    .tmp_vmlinux.kallsyms1.o
  LD      .tmp_vmlinux.kallsyms2
  KSYM    .tmp_vmlinux.kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  VOFFSET arch/x86/boot/compressed/../voffset.h
  CC      arch/x86/boot/compressed/misc.o
  OBJCOPY arch/x86/boot/compressed/vmlinux.bin
  XZKERN  arch/x86/boot/compressed/vmlinux.bin.xz
  MKPIGGY arch/x86/boot/compressed/piggy.S
  AS      arch/x86/boot/compressed/piggy.o
  LD      arch/x86/boot/compressed/vmlinux
  ZOFFSET arch/x86/boot/zoffset.h
  AS      arch/x86/boot/header.o
  LD      arch/x86/boot/setup.elf
  OBJCOPY arch/x86/boot/setup.bin
  OBJCOPY arch/x86/boot/vmlinux.bin
  BUILD   arch/x86/boot/bzImage
Setup is 16060 bytes (padded to 16384 bytes).
System is 4865 kB
CRC e579976c
Kernel: arch/x86/boot/bzImage is ready  (#3)
  Building modules, stage 2.
  MODPOST 153 modules
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137'
cmp -s /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/vmlinux /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/vmlinux.debug || { x86_64-openwrt-linux-musl-objcopy -O binary -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/vmlinux /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/vmlinux; x86_64-openwrt-linux-musl-objcopy -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/vmlinux /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/vmlinux.elf; cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/vmlinux /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/vmlinux.debug;  cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/arch/x86/boot//bzImage /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/bzImage;  }
touch /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.137/.image
make -C image compile install TARGET_BUILD=
make[5]: Entering directory '/workdir/openwrt/target/linux/x86/image'
make[5]: Nothing to be done for 'compile'.
mkdir -p /workdir/openwrt/bin/targets/x86/64 /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp
rm -rf /workdir/openwrt/build_dir/target-x86_64_musl/json_info_files
tar -cp --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name --mtime="@1627936966" -C /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/ . | gzip -9n > /workdir/openwrt/bin/targets/x86/64/openwrt-x86-64-generic-rootfs.tar.gz
/workdir/openwrt/staging_dir/host/bin/mksquashfs4 /workdir/openwrt/build_dir/target-x86_64_musl/root-x86 /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2 -Xbcj x86 -b 256k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1
Pseudo file "/dev" exists in source filesystem "/workdir/openwrt/build_dir/target-x86_64_musl/root-x86/dev".
Ignoring, exclude it (-e/-ef) to override.
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs, block size 262144.

[======================================/                       ] 2800/4482  62%
[=============================================================/] 4482/4482 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 262144
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 38858.63 Kbytes (37.95 Mbytes)
	35.02% of uncompressed filesystem size (110959.70 Kbytes)
Inode table size 35338 bytes (34.51 Kbytes)
	21.25% of uncompressed inode table size (166312 bytes)
Directory table size 47664 bytes (46.55 Kbytes)
	43.56% of uncompressed directory table size (109431 bytes)
Number of duplicate files found 374
Number of inodes 4978
Number of files 4229
Number of fragments 149
Number of symbolic links  455
Number of device nodes 1
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 293
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
/workdir/openwrt/staging_dir/host/bin/make_ext4fs -L rootfs -l 109051904 -b 4096 -m 0 -J -T 1627936966 /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.ext4 /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/
error: ext4_allocate_best_fit_partial: failed to allocate 8 blocks, out of space?
Creating filesystem with parameters:
    Size: 109051904
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6656
    Inode size: 256
    Journal blocks: 0
    Label: rootfs
    Blocks: 26624
    Block groups: 1
    Reserved blocks: 0
    Reserved block group size: 7
make[5]: *** [/workdir/openwrt/include/image.mk:334: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.ext4] Error 1
make[4]: *** [Makefile:22: install] Error 2
make[3]: *** [Makefile:11: install] Error 2
make[5]: Leaving directory '/workdir/openwrt/target/linux/x86/image'
make[4]: Leaving directory '/workdir/openwrt/target/linux/x86'
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/install#130.52#8.28#117.75
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/install] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:19: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by EnnawYang** [comment]
RootFS自己扩容下
