### ISSUE TITLE
编译成功的Newifi D1固件不能使用

### ISSUE THREAD

**Issue by sclsyin** [coolsnowwolf/lede#7606]
编译好的固件，通用网页更新时报不能识别的固件。通过Bread刷入后不能启动。

**Comment by huming2207** [comment]
![image](https://user-images.githubusercontent.com/4463497/128281577-ed415bf1-cfc3-41f4-a636-c6468e950d8b.png)

**Comment by sclsyin** [comment]
问题是取不到日志啊。不能开机了怎么取。

**Comment by yaott2020-666** [comment]
文件名，错误截图都可以，不然怎么帮你解决问题

**Comment by sclsyin** [comment]
openwrt-ramips-mt7621-lenovo_newifi-d1-squashfs-sysupgrade.bin 网页更新时报不能识别的固件。
openwrt-ramips-mt7621-lenovo_newifi-d1-initramfs-kernel.bin 使用Bread刷入成功，但不能启动。

**Comment by EnnawYang** [comment]
d1需要刷initramfs ?

**Comment by yaott2020-666** [comment]
openwrt-ramips-mt7621-lenovo_newifi-d1-squashfs-sysupgrade.bin 这个用breed刷入石试试

**Comment by sclsyin** [comment]
OK.晚点试一下!

**Comment by sclsyin** [comment]
![系统日志](https://user-images.githubusercontent.com/22511328/128307435-6f6c5c1d-39a3-4418-b133-03a9e0e214d5.png)

![不支持上传的映像文件格式](https://user-images.githubusercontent.com/22511328/128307402-7219ad7a-5691-468a-8f08-9d1a56468276.png)

**Comment by EnnawYang** [comment]
> 
> 这个是网页更新时错误的截图和系统日志。
> 
前几天MT7621有重要变更，请不要从网页直接更新

**Comment by sclsyin** [comment]
那我从Bread更新，是更新squashfs 还是initramfs ？？？？

**Comment by EnnawYang** [comment]
> squashfs

squashfs

**Comment by sclsyin** [comment]
谢谢，晚上我试一下。
