### ISSUE TITLE
HC5962和Newifi D2问题

### ISSUE THREAD

**Issue by rshi0212** [coolsnowwolf/lede#7607]
昨日编译HC5962和Newifi D2，更新后在更改LAN口默认地址后，WAN口无法获得电信路由器的地址（例如电信路由器地址是192.168.1.1，默认固件也是192.168.1.1，更改LAN地址为10.1.1.1后，WAN口无法获得电信路由器地址）

另外Newwifi D2默认配置又选上了mtwifi，但是默认启动wifi无法启动，需要手动去web里点击启用。mtwifi的web又经常无法响应。

**Comment by EnnawYang** [comment]
咱的D2用的好好的

**Comment by rshi0212** [comment]
你有尝试过 默认设置下 更改lan ip后重启，wan还能拿到ip嘛？

另外默认设置启动 WiFi会自动启动嘛？

在 2021/8/5 11:29, EnnawYang 写道:

**Comment by EnnawYang** [comment]
> 
> 默认设置启动 WiFi会自动启动嘛？ 
> 
设置完lan口请手动重启下无线，目前闭源驱动就这样，另一个问题没遇到

**Comment by rshi0212** [comment]
另外当改了lan ip后，有限可以拿到改后的dhcp ip，手动启动wifi后，连接ip 拿到169私人地址，无法获得dhcp地址，同时wan拿不到上一级路由的dhcp地址

**Comment by rshi0212** [comment]
hc5962症状相同

**Comment by coolsnowwolf** [comment]
@AmadeusGhost 所以说不要管这些 MTK 的事情了，开源 + DSA 就行了
