### ISSUE TITLE
请问爷爷们   酸酸P的自动切换为什么不起作用

### ISSUE THREAD

**Issue by gekkjoe** [coolsnowwolf/lede#7610]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：自动切换不起作用
![image](https://user-images.githubusercontent.com/80162494/128424171-74d5f941-39e0-4c9c-a881-59797b7c4e05.png)
设置成超时10秒的话才切换 等于断线切换

### (2) 路由器型号和固件版本

A：R1S ImmortalWrt 18.06

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
ssrp请到ssrp的库去提issue，并附带日志。而且这边不是ImmortalWrt
