### ISSUE TITLE
建议升级material主题

### ISSUE THREAD

**Issue by whfweb** [coolsnowwolf/lede#7614]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：现在版本的material主题界面太简陋了。

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by ZeaKyX** [comment]
建议 Google 安排设计师给大雕，material design 2.0 都不用了，直接上 Material You 同步谷司全家桶主题
