### ISSUE TITLE
拉取L大最新源码，本地编译提示缺少依赖，编译失败

### ISSUE THREAD

**Issue by minfengyk** [coolsnowwolf/lede#7618]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
拉取L大最新源码，本地编译提示缺少依赖：arm-trusted-firmware-rk3328，编译失败
### (1) 具体问题

x86: revert to kernel 5.4时本地编译成功，截止8月7日0点，发现L大有更新了源码，忍不住追更一次。本地编译提示缺少依赖：arm-trusted-firmware-rk3328，编译失败。
### (2) 路由器型号和固件版本

主机型号 | Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz : 1 Core 2 Thread (CpuMark : 33366.700033 Scores)
CPU 信息 | 2400.000 MHz
固件版本 | OpenWrt R21.7.26 / LuCI Master (git-21.211.30217-03784c3)
内核版本 | 5.10.51

### (3) 详细日志

WARNING: Makefile 'package/boot/uboot-rockchip/Makefile' has a dependency on 'arm-trusted-firmware-rk3328', which does not exist
WARNING: Makefile 'package/boot/uboot-rockchip/Makefile' has a dependency on 'arm-trusted-firmware-rk3328', which does not exist
WARNING: Makefile 'package/boot/uboot-rockchip/Makefile' has a build dependency on 'arm-trusted-firmware-rk3328', which does not exist

**Comment by EnnawYang** [comment]
x86和arm组件没有关系，请把编译失败的日志贴出来
