### ISSUE TITLE
202007后的固件无法启动

### ISSUE THREAD

**Issue by iulo** [coolsnowwolf/lede#7624]
## 1. 202007后的固件无法启动

Q：是否搜索了issue (使用 "x" 选择)
有一个类似的issue https://github.com/coolsnowwolf/lede/issues/5358

## 2. 详细叙述
使用的是esir的精品固件
刷入的方式是：进入pe，diskGenius删除硬盘分区，用`physicalWrite`刷入uefi的img
现象是：重启后有出现`uefi Os`的引导选项，选择后闪一下白色进度条后就黑屏，底部左下角有个白色短横杠，没有其他反应了。

我从2020年的固件开始尝试，发一些规律：
20200701后的固件名字是`generic-squashfs-uefi`， 之前的 `uefi-gpt-squashfs`，gpt的我试了两个固件都是可以的，generic的都不行，会出现上述失败现象

generic刷完后是三个分区，gpt是四个

generic的固件在diskGenius中加载虚拟磁盘时，会提示：GUID备份分区表损坏，gpt的不会

### (1) 具体问题

A：固件刷入后黑屏无法启动

### (2) 路由器型号和固件版本

A：cpu  j3355，emmc 存储的工控机，esir精品固件

### (3) 详细日志

无

**Comment by hxlls** [comment]
![image](https://user-images.githubusercontent.com/43886952/128637480-a0cc3894-45cf-4012-bb8c-74585966fa42.png)
没问题，最新的固件，建议你去找固件作者咨询。
