### ISSUE TITLE
R4s固件无法启动问题反馈

### ISSUE THREAD

**Issue by Secular2020** [coolsnowwolf/lede#7632]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
今天刷了 矮小少缝合怪编译出的L大的R4s 4g 版固件 启动后连接LAN口无法正常获取网关和IP信息.上个版本无此问题.已退回上一版本.

### (2) 路由器型号和固件版本
R4s 4g

### (3) 详细日志
无法正常启动,故没有日志 = =

**Comment by coolsnowwolf** [comment]
是不是 LAN WAN 反了？

**Comment by Secular2020** [comment]
> 网局域网正在进行反向？

插在Wan口上指示灯亮了,但是也是无法获取正常IP和网关的.

**Comment by AmadeusGhost** [comment]
启不动你找编译作者啊🌚

**Comment by Jason6111** [comment]
测试没问题的

**Comment by hxlls** [comment]
1，R2S 这套源码编译的没问题，实测启动正常
2 ，这用三方固件的不去找作者，来这问是什么意思？

**Comment by EnnawYang** [comment]
"矮小少缝合怪"，hhhhhhh，不用多说了

**Comment by DanielChen008** [comment]
我也觉得，有些二次编译的作者可能是在配置里互换了 LAN & WAN 口
不过既然都一只脚跨进门了，首页的编译步骤写的又清楚，可以自己试试在 L大 代码上自己编译呀
自己动手 丰衣足食

**Comment by WYC-2020** [comment]
哈哈 难道缝合怪惹的祸

**Comment by Secular2020** [comment]
> 我也觉得，有些二次编译的作者可能是在配置里互换了 LAN & WAN 口
> 不过既然都一只脚跨进门了，首页的编译步骤写的又清楚，可以自己试试在 L大 代码上自己编译呀
> 自己动手 丰衣足食

嗯,回头自己研究研究吧,感谢大佬们的回复.
