### ISSUE TITLE
官方默认的ntp时间同步不准确，希望可默认指定ntp服务器IP120.25.108.11，110.75.186.248

### ISSUE THREAD

**Issue by imbrolla** [coolsnowwolf/lede#765]
可以在计划任务添加一条链接网络后自动同步本时区时间。

**Comment by tossp** [comment]
没有什么不准一说吧，ntp本来就是授时服务，只有快不快的区别

[中国区服务器](https://www.pool.ntp.org/zone/cn)

```
0.cn.pool.ntp.org
1.cn.pool.ntp.org
2.cn.pool.ntp.org
3.cn.pool.ntp.org
```

**Comment by laincat** [comment]
反正我用的是：

```
time1.aliyun.com
time2.aliyun.com
time3.aliyun.com
time4.aliyun.com
time5.aliyun.com
time6.aliyun.com
time7.aliyun.com
```

**Comment by hcym** [comment]
从来没在意，都是默认东八区

**Comment by imbrolla** [comment]
默认的时间服务器没用的，长时间不会同步正确的时间。

**Comment by liuluo1979** [comment]
修改package/base-files/files/bin/config_generate（搜索add_list system.ntp.server）
ntp.ntsc.ac.cn （国家授时中心的网络授时服务器）
cn.ntp.org.cn
我只用这两个。

**Comment by liuluo1979** [comment]
设置也可以在package/lean/default-settings/files/zzz-default-settings里添加
