### ISSUE TITLE
rt-acrh17固件ssr plus插件异常

### ISSUE THREAD

**Issue by yubanmeiqin9048** [coolsnowwolf/lede#7657]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：源码为8.11（号），一切编译操作皆按照仓库主页操作，编译固件时仅在默认配置的基础上删除和勾选了一些插件，linux系统为Ubuntu 20.04，编译后的固件ssrp插件功能在电脑上一切正常，但是在手机上不正常，表现为除了google以外的外网都可以使用，但唯独google不行

### (2) 路由器型号和固件版本

A：RT-ACRH17

### (3) 详细日志

A：
Wed Aug 11 15:59:14 2021 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 44:d7:91:8e:97:be
Wed Aug 11 15:59:14 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be IEEE 802.11: disassociated
Wed Aug 11 15:59:15 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Wed Aug 11 15:59:16 2021 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Wed Aug 11 15:59:17 2021 user.notice firewall: Reloading firewall due to ifupdate of wan (pppoe-wan)
Wed Aug 11 15:59:28 2021 user.notice firewall: Reloading firewall due to ifup of wan_6 (pppoe-wan)
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.386272] device wlan0 left promiscuous mode
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.386518] br-lan: port 2(wlan0) entered disabled state
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.439119] device wlan1 left promiscuous mode
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.439352] br-lan: port 3(wlan1) entered disabled state
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: Remove interface 'wlan0'
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan0: interface state ENABLED->DISABLED
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED a8:7e:ea:e7:bb:61
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan0: AP-DISABLED
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan0: CTRL-EVENT-TERMINATING
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: Remove interface 'wlan1'
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan1: interface state ENABLED->DISABLED
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan1: AP-DISABLED
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: wlan1: CTRL-EVENT-TERMINATING
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: nl80211: deinit ifname=wlan1 disabled_11b_rates=0
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: nl80211: Failed to remove interface wlan1 from bridge br-lan: Invalid argument
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.483203] ath10k_ahb a000000.wifi: mac flush null vif, drop 0 queues 0xffff
Wed Aug 11 15:59:58 2021 kern.warn kernel: [  162.484978] ath10k_ahb a000000.wifi: peer-unmap-event: unknown peer id 0
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Wed Aug 11 15:59:58 2021 daemon.notice hostapd: nl80211: Failed to remove interface wlan0 from bridge br-lan: Invalid argument
Wed Aug 11 15:59:58 2021 kern.info kernel: [  162.504562] ath10k_pci 0000:01:00.0: mac flush null vif, drop 0 queues 0xffff
Wed Aug 11 15:59:58 2021 kern.warn kernel: [  162.505541] ath10k_pci 0000:01:00.0: peer-unmap-event: unknown peer id 0
Wed Aug 11 15:59:59 2021 daemon.info dnsmasq[5421]: Connected to system UBus
Wed Aug 11 15:59:59 2021 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy1.conf (phy wlan1) --> new PHY
Wed Aug 11 16:00:01 2021 kern.warn kernel: [  165.066498] ath10k_ahb a000000.wifi: 10.4 wmi init: vdevs: 16  peers: 48  tid: 96
Wed Aug 11 16:00:01 2021 kern.warn kernel: [  165.066550] ath10k_ahb a000000.wifi: msdu-desc: 2500  skid: 32
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.113414] ath10k_ahb a000000.wifi: wmi print 'P 48/48 V 16 K 144 PH 176 T 186  msdu-desc: 2500  sw-crypt: 0 ct-sta: 0'
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.114264] ath10k_ahb a000000.wifi: wmi print 'free: 53252 iram: 13432 sram: 35752'
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.459213] ath10k_ahb a000000.wifi: rts threshold -1
Wed Aug 11 16:00:01 2021 kern.warn kernel: [  165.460263] ath10k_ahb a000000.wifi: Firmware lacks feature flag indicating a retry limit of > 2 is OK, requested limit: 4
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.479768] br-lan: port 2(wlan1) entered blocking state
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.479820] br-lan: port 2(wlan1) entered disabled state
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.484638] device wlan1 entered promiscuous mode
Wed Aug 11 16:00:01 2021 daemon.notice hostapd: wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.874362] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.874649] br-lan: port 2(wlan1) entered blocking state
Wed Aug 11 16:00:01 2021 kern.info kernel: [  165.879838] br-lan: port 2(wlan1) entered forwarding state
Wed Aug 11 16:00:01 2021 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy0.conf (phy wlan0) --> new PHY
Wed Aug 11 16:00:02 2021 cron.err crond[3154]: time disparity of 1177 minutes detected
Wed Aug 11 16:00:07 2021 kern.warn kernel: [  171.810297] ath10k_pci 0000:01:00.0: 10.4 wmi init: vdevs: 16  peers: 48  tid: 96
Wed Aug 11 16:00:07 2021 kern.warn kernel: [  171.810344] ath10k_pci 0000:01:00.0: msdu-desc: 2500  skid: 32
Wed Aug 11 16:00:07 2021 kern.info kernel: [  171.892618] ath10k_pci 0000:01:00.0: wmi print 'P 48/48 V 16 K 144 PH 176 T 186  msdu-desc: 2500  sw-crypt: 0 ct-sta: 0'
Wed Aug 11 16:00:07 2021 kern.info kernel: [  171.893423] ath10k_pci 0000:01:00.0: wmi print 'free: 84920 iram: 13156 sram: 11224'
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.271782] ath10k_pci 0000:01:00.0: rts threshold -1
Wed Aug 11 16:00:08 2021 kern.warn kernel: [  172.272301] ath10k_pci 0000:01:00.0: Firmware lacks feature flag indicating a retry limit of > 2 is OK, requested limit: 4
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.282487] br-lan: port 3(wlan0) entered blocking state
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.286775] br-lan: port 3(wlan0) entered disabled state
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.292769] device wlan0 entered promiscuous mode
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->HT_SCAN
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan1: interface state COUNTRY_UPDATE->ENABLED
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan1: AP-ENABLED
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.968711] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.969378] br-lan: port 3(wlan0) entered blocking state
Wed Aug 11 16:00:08 2021 kern.info kernel: [  172.974189] br-lan: port 3(wlan0) entered forwarding state
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan0: interface state HT_SCAN->ENABLED
Wed Aug 11 16:00:08 2021 daemon.notice hostapd: wlan0: AP-ENABLED
Wed Aug 11 16:00:09 2021 daemon.notice netifd: Network device 'wlan1' link is up
Wed Aug 11 16:00:09 2021 daemon.notice netifd: Network device 'wlan0' link is up
Wed Aug 11 16:00:17 2021 daemon.info hostapd: wlan0: STA a8:7e:ea:e7:bb:61 IEEE 802.11: authenticated
Wed Aug 11 16:00:17 2021 daemon.info hostapd: wlan0: STA a8:7e:ea:e7:bb:61 IEEE 802.11: associated (aid 1)
Wed Aug 11 16:00:17 2021 daemon.notice hostapd: wlan0: STA-OPMODE-SMPS-MODE-CHANGED a8:7e:ea:e7:bb:61 off
Wed Aug 11 16:00:17 2021 daemon.notice hostapd: wlan0: AP-STA-CONNECTED a8:7e:ea:e7:bb:61
Wed Aug 11 16:00:17 2021 daemon.info hostapd: wlan0: STA a8:7e:ea:e7:bb:61 RADIUS: starting accounting session ED3AEC644F135CEE
Wed Aug 11 16:00:17 2021 daemon.info hostapd: wlan0: STA a8:7e:ea:e7:bb:61 WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:00:17 2021 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED a8:7e:ea:e7:bb:61
Wed Aug 11 16:00:35 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be IEEE 802.11: authenticated
Wed Aug 11 16:00:35 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be IEEE 802.11: associated (aid 1)
Wed Aug 11 16:00:36 2021 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 44:d7:91:8e:97:be
Wed Aug 11 16:00:36 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be RADIUS: starting accounting session 407466E0AB75A567
Wed Aug 11 16:00:36 2021 daemon.info hostapd: wlan1: STA 44:d7:91:8e:97:be WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:00:36 2021 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED 44:d7:91:8e:97:be
Wed Aug 11 16:00:43 2021 cron.err crond[6040]: crond (busybox 1.33.1) started, log level 5
Wed Aug 11 16:00:44 2021 daemon.info hostapd: wlan1: STA b4:cb:57:00:5a:bb IEEE 802.11: authenticated
Wed Aug 11 16:00:44 2021 daemon.info hostapd: wlan1: STA b4:cb:57:00:5a:bb IEEE 802.11: associated (aid 2)
Wed Aug 11 16:00:44 2021 daemon.notice hostapd: wlan1: AP-STA-CONNECTED b4:cb:57:00:5a:bb
Wed Aug 11 16:00:44 2021 daemon.info hostapd: wlan1: STA b4:cb:57:00:5a:bb RADIUS: starting accounting session EDD5FD4B14E44022
Wed Aug 11 16:00:44 2021 daemon.info hostapd: wlan1: STA b4:cb:57:00:5a:bb WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:00:44 2021 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED b4:cb:57:00:5a:bb
Wed Aug 11 16:00:45 2021 cron.err crond[6274]: crond (busybox 1.33.1) started, log level 5
Wed Aug 11 16:00:51 2021 daemon.err miniupnpd[6580]: could not open lease file: /var/upnp.leases
Wed Aug 11 16:00:51 2021 daemon.notice miniupnpd[6580]: HTTP listening on port 5000
Wed Aug 11 16:00:51 2021 daemon.notice miniupnpd[6580]: Listening for NAT-PMP/PCP traffic on port 5351
Wed Aug 11 16:00:52 2021 daemon.notice miniupnpd[6580]: shutting down MiniUPnPd
Wed Aug 11 16:00:52 2021 daemon.err miniupnpd[6627]: could not open lease file: /var/upnp.leases
Wed Aug 11 16:00:52 2021 daemon.notice miniupnpd[6627]: HTTP listening on port 5000
Wed Aug 11 16:00:52 2021 daemon.notice miniupnpd[6627]: Listening for NAT-PMP/PCP traffic on port 5351
Wed Aug 11 16:01:12 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: authenticated
Wed Aug 11 16:01:12 2021 daemon.notice hostapd: wlan0: STA-OPMODE-N_SS-CHANGED 82:25:18:4a:1e:3c 1
Wed Aug 11 16:01:12 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: associated (aid 2)
Wed Aug 11 16:01:12 2021 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:01:12 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c RADIUS: starting accounting session B353DF48E0B8198D
Wed Aug 11 16:01:12 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:01:12 2021 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 82:25:18:4a:1e:3c
Wed Aug 11 16:01:33 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:01:33 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:01:36 2021 daemon.info dnsmasq[6986]: Connected to system UBus
Wed Aug 11 16:01:36 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:01:36 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:01:40 2021 daemon.info dnsmasq[7184]: Connected to system UBus
Wed Aug 11 16:01:46 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:01:46 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:01:49 2021 daemon.info dnsmasq[7453]: Connected to system UBus
Wed Aug 11 16:01:56 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:01:56 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:02:00 2021 daemon.info dnsmasq[8106]: Connected to system UBus
Wed Aug 11 16:02:19 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:02:19 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:02:22 2021 daemon.info dnsmasq[8677]: Connected to system UBus
Wed Aug 11 16:02:31 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:02:31 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:02:34 2021 daemon.info dnsmasq[9203]: Connected to system UBus
Wed Aug 11 16:02:36 2021 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:02:36 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: disassociated
Wed Aug 11 16:02:37 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c IEEE 802.11: authenticated
Wed Aug 11 16:02:37 2021 daemon.notice hostapd: wlan1: STA-OPMODE-N_SS-CHANGED 82:25:18:4a:1e:3c 2
Wed Aug 11 16:02:37 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c IEEE 802.11: associated (aid 3)
Wed Aug 11 16:02:37 2021 daemon.notice hostapd: wlan0: Prune association for 82:25:18:4a:1e:3c
Wed Aug 11 16:02:37 2021 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:02:37 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c RADIUS: starting accounting session 4BF738EDDEF4138A
Wed Aug 11 16:02:37 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:02:37 2021 daemon.notice hostapd: wlan1: EAPOL-4WAY-HS-COMPLETED 82:25:18:4a:1e:3c
Wed Aug 11 16:02:39 2021 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:02:39 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c IEEE 802.11: disassociated
Wed Aug 11 16:02:40 2021 daemon.info hostapd: wlan1: STA 82:25:18:4a:1e:3c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Wed Aug 11 16:02:46 2021 daemon.notice hostapd: wlan0: STA-OPMODE-N_SS-CHANGED 82:25:18:4a:1e:3c 1
Wed Aug 11 16:02:46 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: authenticated
Wed Aug 11 16:02:46 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: associated (aid 2)
Wed Aug 11 16:02:46 2021 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:02:46 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c RADIUS: starting accounting session B353DF48E0B8198D
Wed Aug 11 16:02:46 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:02:46 2021 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 82:25:18:4a:1e:3c
Wed Aug 11 16:03:46 2021 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:03:46 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: disassociated
Wed Aug 11 16:03:47 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Wed Aug 11 16:04:25 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: authenticated
Wed Aug 11 16:04:25 2021 daemon.notice hostapd: wlan0: STA-OPMODE-N_SS-CHANGED 82:25:18:4a:1e:3c 1
Wed Aug 11 16:04:25 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c IEEE 802.11: associated (aid 2)
Wed Aug 11 16:04:25 2021 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 82:25:18:4a:1e:3c
Wed Aug 11 16:04:25 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c RADIUS: starting accounting session B2D4C3953BD55BBA
Wed Aug 11 16:04:25 2021 daemon.info hostapd: wlan0: STA 82:25:18:4a:1e:3c WPA: pairwise key handshake completed (RSN)
Wed Aug 11 16:04:25 2021 daemon.notice hostapd: wlan0: EAPOL-4WAY-HS-COMPLETED 82:25:18:4a:1e:3c
Wed Aug 11 16:13:43 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:13:43 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:13:47 2021 daemon.info dnsmasq[12444]: Connected to system UBus
Wed Aug 11 16:13:54 2021 daemon.info dnsmasq[12834]: Connected to system UBus
Wed Aug 11 16:13:55 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Aug 11 16:13:55 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Aug 11 16:13:58 2021 daemon.info dnsmasq[13122]: Connected to system UBus

**Comment by 281677160** [comment]
这个问题一般应该都是DNS设置错误导致的吧，我以前试过，不过我忘记了是咋弄好了，反正就DNS问题

**Comment by yubanmeiqin9048** [comment]
> 这个问题一般应该都是DNS设置错误导致的吧，我以前试过，不过我忘记了是咋弄好了，反正就DNS问题

我也没动关于DNS方面的设置，基本就是刷好了，然后订阅，就默认的配置启动

**Comment by 281677160** [comment]
你op的dns设置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 下午4:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [coolsnowwolf/lede] rt-acrh17固件ssr plus插件异常 (#7657)




  
这个问题一般应该都是DNS设置错误导致的吧，我以前试过，不过我忘记了是咋弄好了，反正就DNS问题
  
我也没动关于DNS方面的设置，基本就是刷好了，然后订阅，就默认的配置启动
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yubanmeiqin9048** [comment]
> 你op的dns设置
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月11日(周三) 下午4:37 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [coolsnowwolf/lede] rt-acrh17固件ssr plus插件异常 (#7657) 这个问题一般应该都是DNS设置错误导致的吧，我以前试过，不过我忘记了是咋弄好了，反正就DNS问题 我也没动关于DNS方面的设置，基本就是刷好了，然后订阅，就默认的配置启动 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

![YGZROH5N6EVT96F{@KWL(1F](https://user-images.githubusercontent.com/64676973/128998453-0e163da6-c99d-4096-ba50-9f9ccc776d1a.png)
![YR5JP835Q6TUY7QW`Q23LP8](https://user-images.githubusercontent.com/64676973/128998503-80e1f249-3d45-48a6-a637-60669e9cdfc9.png)

**Comment by 4860575** [comment]
解决办法1、不使用pdnsd，改为dns2socks
或者：修改/etc/init.d/shadowsocksr 注释掉
			reject=::/0;
 			reject_policy=negate;
 			reject_recursively=on;

**Comment by 281677160** [comment]
自定义DNS那些你设置114.114.114.114 223.5.5.5这样两个测试下

**Comment by yubanmeiqin9048** [comment]
> 解决办法1、不使用pdnsd，改为dns2socks
> 或者：修改/etc/init.d/shadowsocksr 注释掉
> reject=::/0;
> reject_policy=negate;
> reject_recursively=on;

通过法一解决了，请问这是什么问题呢？

**Comment by wuiiled** [comment]
> > 解决办法1、不使用pdnsd，改为dns2socks
> > 或者：修改/etc/init.d/shadowsocksr 注释掉
> > reject=::/0;
> > reject_policy=negate;
> > reject_recursively=on;
> 
> 通过法一解决了，请问这是什么问题呢？我想不出是因为什么问题导致的这种情况，因为我看到群里的（acrh17的群）用pdnsd也没问题，基本也是默认配置在用

pdnsd DNS缓存问题
