### ISSUE TITLE
日志有报错，百度了一下，好像是TTYD问题，请各位帮忙看看怎么整

### ISSUE THREAD

**Issue by 281677160** [coolsnowwolf/lede#7662]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Thu Aug 12 00:38:05 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:07 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:09 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 00:38:09 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 00:38:09 2021 daemon.info dnsmasq[7543]: Connected to system UBus
Thu Aug 12 00:38:09 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:11 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:13 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:15 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:17 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:19 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:21 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:22 2021 daemon.info procd: Instance snmpd::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Aug 12 00:38:23 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:25 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:27 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 00:38:29 2021 daemon.info procd: Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Aug 12 00:38:52 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:39:01 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:39:16 2021 daemon.err uhttpd[3954]: sh: iperf3: not found
Thu Aug 12 00:41:00 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:42:02 2021 daemon.err uhttpd[3954]: sh: iperf3: not found
Thu Aug 12 00:43:04 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 00:43:04 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 00:43:04 2021 daemon.info dnsmasq[9858]: Connected to system UBus
Thu Aug 12 00:43:12 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 00:43:12 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 00:43:12 2021 daemon.info dnsmasq[11310]: Connected to system UBus
Thu Aug 12 00:44:04 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:45:15 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:46:13 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:46:23 2021 daemon.err uhttpd[3954]: sh: iperf3: not found
Thu Aug 12 00:47:58 2021 daemon.err uhttpd[3954]: env: can't execute 'python': No such file or directory
Thu Aug 12 00:48:12 2021 daemon.err uhttpd[3954]: killall: iperf3: no process killed
Thu Aug 12 00:56:38 2021 authpriv.info dropbear[14981]: Child connection from 192.168.2.8:53957
Thu Aug 12 00:56:40 2021 authpriv.notice dropbear[14981]: Auth succeeded with blank password for 'root' from 192.168.2.8:53957
Thu Aug 12 00:57:26 2021 authpriv.info dropbear[15205]: Child connection from 192.168.2.8:64241
Thu Aug 12 00:57:26 2021 authpriv.notice dropbear[15205]: Auth succeeded with blank password for 'root' from 192.168.2.8:64241
Thu Aug 12 00:57:31 2021 authpriv.info dropbear[14981]: Exit (root) from <192.168.2.8:53957>: Exited normally
Thu Aug 12 00:57:31 2021 authpriv.info dropbear[15205]: Exit (root) from <192.168.2.8:64241>: Exited normally
Thu Aug 12 00:57:40 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 02:00:00 2021 cron.err crond[6493]: USER root pid 26793 cmd /usr/share/shadowsocksr/ssrplusupdate.sh >/var/log/ssrplus.log
Thu Aug 12 02:00:07 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 02:00:07 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 02:00:07 2021 daemon.info dnsmasq[27153]: Connected to system UBus
Thu Aug 12 02:00:14 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 02:00:14 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 02:00:14 2021 daemon.info dnsmasq[27865]: Connected to system UBus
Thu Aug 12 02:01:00 2021 cron.err crond[6493]: USER root pid 28047 cmd lua /usr/share/ttnode/main.lua
Thu Aug 12 02:03:00 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/system.interrupts/57.db.
Thu Aug 12 02:03:00 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/cpu.cpu1_interrupts/57.db.
Thu Aug 12 02:03:00 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/cpu.cpu1_softirqs/TASKLET.db.
Thu Aug 12 02:11:40 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 02:11:40 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 02:11:40 2021 daemon.info dnsmasq[30277]: Connected to system UBus
Thu Aug 12 02:11:41 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 02:11:41 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 02:11:41 2021 daemon.info dnsmasq[30690]: Connected to system UBus
Thu Aug 12 04:00:00 2021 cron.err crond[6493]: USER root pid 18305 cmd /etc/coremark.sh
Thu Aug 12 04:00:00 2021 cron.err crond[6493]: USER root pid 18306 cmd sync && echo 3 > /proc/sys/vm/drop_caches
Thu Aug 12 04:00:00 2021 kern.info kernel: [12150.549695] ash (18306): drop_caches: 3
Thu Aug 12 08:00:00 2021 cron.err crond[6493]: USER root pid 30191 cmd sync && echo 3 > /proc/sys/vm/drop_caches
Thu Aug 12 08:00:00 2021 kern.info kernel: [26550.681847] ash (30191): drop_caches: 3
Thu Aug 12 08:03:12 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/system.softirqs/HRTIMER.db.
Thu Aug 12 08:03:12 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/cpu.cpu1_softirqs/HRTIMER.db.
Thu Aug 12 08:31:52 2021 daemon.info netdata[6673]: Initializing file /var/cache/netdata/cpu.cpu0_softirqs/HRTIMER.db.
Thu Aug 12 09:23:38 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 09:23:38 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 09:23:38 2021 daemon.info dnsmasq[13401]: Connected to system UBus
Thu Aug 12 09:23:40 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Aug 12 09:23:40 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Aug 12 09:23:40 2021 daemon.info dnsmasq[13815]: Connected to system UBus
Thu Aug 12 09:33:37 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:33:39 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:20 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:22 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:24 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:26 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:28 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:30 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:32 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:34 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 09:51:35 2021 daemon.notice ttyd[6955]: HTTP / - 192.168.2.9
Thu Aug 12 09:51:35 2021 daemon.notice ttyd[6955]: HTTP /token - 192.168.2.9
Thu Aug 12 09:51:35 2021 daemon.notice ttyd[6955]: WS   /ws - 192.168.2.9, clients: 1
Thu Aug 12 09:51:35 2021 daemon.notice ttyd[6955]: started process, pid: 22248
Thu Aug 12 09:51:41 2021 auth.info login[22276]: root login on 'pts/0'
Thu Aug 12 09:53:40 2021 authpriv.info dropbear[22637]: Child connection from 192.168.2.9:55174
Thu Aug 12 09:53:40 2021 authpriv.notice dropbear[22637]: Auth succeeded with blank password for 'root' from 192.168.2.9:55174
Thu Aug 12 09:54:20 2021 authpriv.info dropbear[22796]: Child connection from 192.168.2.9:55177
Thu Aug 12 09:54:20 2021 authpriv.notice dropbear[22796]: Auth succeeded with blank password for 'root' from 192.168.2.9:55177
Thu Aug 12 09:54:26 2021 daemon.notice ttyd[6955]: WS closed from 192.168.2.9, clients: 0
Thu Aug 12 09:54:26 2021 daemon.notice ttyd[6955]: killing process 22248 with signal: 1 (SIGHUP)
Thu Aug 12 09:54:26 2021 daemon.notice ttyd[6955]: process killed with signal 1 (SIGHUP), pid: 22248
Thu Aug 12 09:54:26 2021 daemon.notice ttyd[6955]: HTTP / - 192.168.2.9
Thu Aug 12 09:54:27 2021 daemon.notice ttyd[6955]: HTTP /token - 192.168.2.9
Thu Aug 12 09:54:27 2021 daemon.notice ttyd[6955]: WS   /ws - 192.168.2.9, clients: 1
Thu Aug 12 09:54:27 2021 daemon.notice ttyd[6955]: started process, pid: 22843
Thu Aug 12 09:54:31 2021 auth.info login[22855]: root login on 'pts/0'
Thu Aug 12 09:54:57 2021 daemon.notice ttyd[6955]: WS closed from 192.168.2.9, clients: 0
Thu Aug 12 09:54:57 2021 daemon.notice ttyd[6955]: killing process 22843 with signal: 1 (SIGHUP)
Thu Aug 12 09:54:57 2021 daemon.notice ttyd[6955]: process killed with signal 1 (SIGHUP), pid: 22843
Thu Aug 12 09:54:58 2021 daemon.notice ttyd[6955]: HTTP / - 192.168.2.9
Thu Aug 12 09:54:58 2021 daemon.notice ttyd[6955]: HTTP /token - 192.168.2.9
Thu Aug 12 09:54:58 2021 daemon.notice ttyd[6955]: WS   /ws - 192.168.2.9, clients: 1
Thu Aug 12 09:54:58 2021 daemon.notice ttyd[6955]: started process, pid: 22964
Thu Aug 12 09:55:02 2021 auth.info login[22975]: root login on 'pts/0'
Thu Aug 12 10:03:42 2021 daemon.notice ttyd[6955]: WS closed from 192.168.2.9, clients: 0
Thu Aug 12 10:03:42 2021 daemon.notice ttyd[6955]: killing process 22964 with signal: 1 (SIGHUP)
Thu Aug 12 10:03:42 2021 daemon.notice ttyd[6955]: process killed with signal 1 (SIGHUP), pid: 22964
Thu Aug 12 10:29:51 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 10:29:53 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 10:29:55 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 10:30:20 2021 authpriv.info dropbear[22637]: Exit (root) from <192.168.2.9:55174>: Exited normally
Thu Aug 12 10:30:20 2021 authpriv.info dropbear[22796]: Exit (root) from <192.168.2.9:55177>: Exited normally
Thu Aug 12 10:47:19 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 10:47:21 2021 daemon.err uhttpd[3954]: (standard_in) 1: syntax error
Thu Aug 12 10:50:52 2021 daemon.notice ttyd[6955]: HTTP / - 192.168.2.9
Thu Aug 12 10:50:52 2021 daemon.notice ttyd[6955]: HTTP /token - 192.168.2.9
Thu Aug 12 10:50:52 2021 daemon.notice ttyd[6955]: WS   /ws - 192.168.2.9, clients: 1
Thu Aug 12 10:50:52 2021 daemon.notice ttyd[6955]: started process, pid: 5359
Thu Aug 12 10:50:55 2021 auth.info login[5367]: root login on 'pts/0'
Thu Aug 12 10:55:10 2021 daemon.notice ttyd[6955]: WS closed from 192.168.2.9, clients: 0
Thu Aug 12 10:55:10 2021 daemon.notice ttyd[6955]: killing process 5359 with signal: 1 (SIGHUP)
Thu Aug 12 10:55:10 2021 daemon.notice ttyd[6955]: process killed with signal 1 (SIGHUP), pid: 5359

**Comment by jarod360** [comment]
有啥问题，ttyd正常运行和退出的日志而已
