### ISSUE TITLE
同步最新源码后openvpn客户端连不上SoftEther VPN 服务器

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#7668]
同步最新源码后openvpn客户端连不上SoftEther VPN 服务器，L2TP/IPSEC可以连上

**Comment by ricksuzade-maker** [comment]
是不是端口被openvpn server占了，换个端口试试

**Comment by mitsukileung** [comment]
> 
> 
> 是不是端口被openvpn server占了，换个端口试试

之前也是一样的设置，更新后编译的固件连不上

**Comment by whoshoe** [comment]
更新之后QNAP上的openVPN能连上但内网外网都无法访问。可能是防火墙默认设置有变动。

**Comment by mitsukileung** [comment]
> 
> 
> 更新之后QNAP上的openVPN能连上但内网外网都无法访问。可能是防火墙默认设置有变动。

今天更新了之后又可以了
