### ISSUE TITLE
qca-nss-clients-64编不过

### ISSUE THREAD

**Issue by Leo357449107** [coolsnowwolf/lede#7671]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：qca-nss-clients-64编不过。

### (2) 路由器型号和固件版本

A：ipq807x XIAOMI AX6 
git commit d9bd5b2df1dc4ab7c6624a1227c9fbb0b068428a

### (3) 详细日志

A：
make[3]: Entering directory '/media/leoslion/builddisk/lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.56'
  CC [M]  /home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/nss_connmgr_pppoe.o
/home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/nss_connmgr_pppoe.c: In function 'nss_connmgr_pppoe_connect':
/home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/nss_connmgr_pppoe.c:290:12: error: implicit declaration of function 'bond_get_id'; did you mean 'find_get_pid'? [-Werror=implicit-function-declaration]
   bondid = bond_get_id(opt.dev);
            ^~~~~~~~~~~
            find_get_pid
cc1: all warnings being treated as errors
make[5]: *** [scripts/Makefile.build:280: /home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/nss_connmgr_pppoe.o] Error 1
make[4]: *** [scripts/Makefile.build:497: /home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe] Error 2
make[3]: *** [Makefile:1822: /home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1] Error 2
make[3]: Leaving directory '/media/leoslion/builddisk/lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.56'
make[2]: *** [Makefile:62: /home/leoslion/openwrt/lede-lean/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.built] Error 2

**Comment by zxlhhyccc** [comment]
qca-ssdk你能编译过去？
