### ISSUE TITLE
luci-app-DDNS无法获取到有效的IPV6地址

### ISSUE THREAD

**Issue by yubanmeiqin9048** [coolsnowwolf/lede#7681]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：无法获取到有效IP

### (2) 路由器型号和固件版本

A：ACRH 17

### (3) 详细日志

A：
Get registered/public IP for 'y.eu.org' failed - retry 372/0 in 60 seconds
 090848       : #> /usr/bin/nslookup y.eu.org  >/var/run/ddns/myddns_ipv6.dat 2>/var/run/ddns/myddns_ipv6.err
 090850  WARN : NO valid IP found
 090851  WARN : Get registered/public IP for 'y.eu.org' failed - retry 373/0 in 60 seconds
 090952       : #> /usr/bin/nslookup yuban.eu.org  >/var/run/ddns/myddns_ipv6.dat 2>/var/run/ddns/myddns_ipv6.err
 090955  WARN : NO valid IP found
 090956  WARN : Get registered/public IP for 'y.eu.org' failed - retry 374/0 in 60 seconds
 091058       : #> /usr/bin/nslookup yuban.eu.org  >/var/run/ddns/myddns_ipv6.dat 2>/var/run/ddns/myddns_ipv6.err
 091100  WARN : NO valid IP found
 091101  WARN : Get registered/public IP for 'y.eu.org' failed - retry 375/0 in 60 seconds
 091202       : #> /usr/bin/nslookup y.eu.org  >/var/run/ddns/myddns_ipv6.dat 2>/var/run/ddns/myddns_ipv6.err
 091204  WARN : NO valid IP found
 091204  WARN : Get registered/public IP for 'y.eu.org' failed - retry 376/0 in 60 seconds

**Comment by VergilGao** [comment]
设置时要选获取ip地址的网口，选br-lan

**Comment by yubanmeiqin9048** [comment]
> 设置时要选获取ip地址的网口，选br-lan

从接口获取吗？

**Comment by yubanmeiqin9048** [comment]
找到解决办法了：应该是DNSPOD的问题，在解析记录为泛域名时DNSPOD并不会将顶级域名一起加入解析，需要添加一条@记录才可以，而脚本在检测IP是否变化的过程中是nslookup顶级域名，所以解决办法是添加一条@记录
