### ISSUE TITLE
编译出错...反复多次都是同一个错误,,虚拟机已开全局代理..

### ISSUE THREAD

**Issue by showme2005** [coolsnowwolf/lede#7697]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
用的虚拟机编译的X86,只添加了一个外包就是kenzok8的passwall

### (2) 路由器型号和固件版本
X86
A：

### (3) 详细日志
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh cache_cleanup
touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.built
rm -rf /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core.installed /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core
mkdir -p /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v4" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v4/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1" GO_BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build" GO_BUILD_BIN_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh install_bin "/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-install"
install -d -m0755 /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core/usr/bin/
install -m0755 /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-install/usr/bin/v2ray /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core/usr/bin/
touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core.installed
mkdir -p /home/alen/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/alen/lede/tmp/.root-copy.flock -c 'cp -fpR /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.pkgdir/v2ray-core/. /home/alen/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/alen/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.v2ray-core_installed
mkdir -p /home/alen/lede/bin/targets/x86/64/packages /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/CONTROL /home/alen/lede/staging_dir/target-x86_64_musl/pkginfo
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v4" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v4/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1" GO_BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build" GO_BUILD_BIN_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh install_bin "/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-install"
install -d -m0755 /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/usr/bin/
install -m0755 /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-install/usr/bin/v2ray /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/usr/bin/
find /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="x86_64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="x86_64-openwrt-linux-musl-nm" STRIP="x86_64-openwrt-linux-musl-strip --strip-all" STRIP_KMOD="/home/alen/lede/scripts/strip-kmod.sh" PATCHELF="/home/alen/lede/staging_dir/host/bin/patchelf" /home/alen/lede/scripts/rstrip.sh /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core
rstrip.sh: /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/usr/bin/v2ray: executable
patchelf: no section headers. The input file is probably a statically linked, self-decompressing binary
x86_64-openwrt-linux-musl-strip: error: the input file '/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/usr/bin/v2ray' has no sections
(cd /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/alen/lede/bin/packages/x86_64/small
/home/alen/lede/staging_dir/host/bin/fakeroot /home/alen/lede/scripts/ipkg-build -m "" /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core /home/alen/lede/bin/packages/x86_64/small
Packaged contents of /home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/ipkg-x86_64/v2ray-core into /home/alen/lede/bin/packages/x86_64/small/v2ray-core_4.41.1-1_x86_64.ipk
echo "v2ray-core" >> /home/alen/lede/staging_dir/target-x86_64_musl/pkginfo/v2ray-core.default.install
rm -rf /home/alen/lede/tmp/stage-v2ray-core
mkdir -p /home/alen/lede/tmp/stage-v2ray-core/host /home/alen/lede/staging_dir/target-x86_64_musl/packages
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v4" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v4/infra/control/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1" GO_BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build" GO_BUILD_BIN_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-core-4.41.1/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh install_src "/home/alen/lede/tmp/stage-v2ray-core"
find /home/alen/lede/tmp/stage-v2ray-core -name '*.la' | xargs -r rm -f; 
if [ -f /home/alen/lede/staging_dir/target-x86_64_musl/packages/v2ray-core.list ]; then /home/alen/lede/scripts/clean-package.sh "/home/alen/lede/staging_dir/target-x86_64_musl/packages/v2ray-core.list" "/home/alen/lede/staging_dir/target-x86_64_musl"; fi
if [ -d /home/alen/lede/tmp/stage-v2ray-core ]; then (cd /home/alen/lede/tmp/stage-v2ray-core; find ./ > /home/alen/lede/tmp/stage-v2ray-core.files); 	SHELL= flock /home/alen/lede/tmp/.staging-dir.flock -c ' mv /home/alen/lede/tmp/stage-v2ray-core.files /home/alen/lede/staging_dir/target-x86_64_musl/packages/v2ray-core.list && cp -fpR /home/alen/lede/tmp/stage-v2ray-core/* /home/alen/lede/staging_dir/target-x86_64_musl/; '; fi
rm -rf /home/alen/lede/tmp/stage-v2ray-core
touch /home/alen/lede/staging_dir/target-x86_64_musl/stamp/.v2ray-core_installed
make[3]: Leaving directory '/home/alen/lede/feeds/small/v2ray-core'
time: package/feeds/small/v2ray-core/compile#61.45#8.15#50.64
make[3]: Entering directory '/home/alen/lede/feeds/small/v2ray-plugin'
mkdir -p /home/alen/lede/dl
SHELL= flock /home/alen/lede/tmp/.v2ray-plugin-4.41.0.tar.gz.flock -c '  	/home/alen/lede/scripts/download.pl "/home/alen/lede/dl" "v2ray-plugin-4.41.0.tar.gz" "e23d6bbf828efa9b0ac722b4665c5b3c12df2046879a2efe8ee980a8912bba0b" "" "https://codeload.github.com/teddysun/v2ray-plugin/tar.gz/v4.41.0?"    '
touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.prepared_7ddabf1076ca93a650682be58a9b9153_6664517399ebbbc92a37c5bb081b5c53_check
. /home/alen/lede/include/shell.sh; gzip -dc /home/alen/lede/dl/v2ray-plugin-4.41.0.tar.gz | tar -C /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0
touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.prepared_7ddabf1076ca93a650682be58a9b9153_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.configured_*
rm -f /home/alen/lede/staging_dir/target-x86_64_musl/stamp/.v2ray-plugin_installed
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/shadowsocks/v2ray-plugin" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/shadowsocks/v2ray-plugin/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0" GO_BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build" GO_BUILD_BIN_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh configure
Copying files from /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0 into /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build/src/github.com/shadowsocks/v2ray-plugin
args.go
errors.generated.go
go.mod
go.sum
log.go
log_android.go
main.go
utils.go
utils_android.go

Symlinking directories from /home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src into /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build/src
.../github.com/v2fly

touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.configured_0cb557a10142168c2483aad96ca11527
rm -f /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.built
touch /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/alen/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/alen/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/shadowsocks/v2ray-plugin" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/shadowsocks/v2ray-plugin/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0" GO_BUILD_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build" GO_BUILD_BIN_DIR="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/alen/lede/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOARM="" GOMIPS="" GOMIPS64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0=v2ray-plugin-4.41.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0=v2ray-plugin-4.41.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build" GOCACHE="/home/alen/lede/tmp/go-build" GOMODCACHE="/home/alen/lede/dl/go-mod-cache" GOENV=off /usr/bin/env bash /home/alen/lede/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1629214236' -linkmode external -extldflags '-L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w -X main.VERSION=v4.41.0 -buildid '1629214236' -linkmode external -extldflags '-L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/alen/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
go: github.com/v2fly/v2ray-core/v4@v4.41.0: Get "https://proxy.golang.org/github.com/v2fly/v2ray-core/v4/@v/v4.41.0.mod": EOF

Building targets
no Go files in /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.go_work/build

make[3]: *** [Makefile:75: /home/alen/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.41.0/.built] Error 1
make[3]: Leaving directory '/home/alen/lede/feeds/small/v2ray-plugin'
time: package/feeds/small/v2ray-plugin/compile#0.26#0.15#5.02
    ERROR: package/feeds/small/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/home/alen/lede'
make[1]: *** [package/Makefile:110: /home/alen/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/alen/lede'
make: *** [/home/alen/lede/include/toplevel.mk:230：world] 错误 2

A：

**Comment by ericsnow911** [comment]
应该是引用出问题了，自己手动安装一下golang

**Comment by showme2005** [comment]
> 应该是引用出问题了，自己手动安装一下golang

感谢。。。。按你说的手动安装了一下golang就没有在出错了。。感谢~~~
