### ISSUE TITLE
default-setting.apk 安装错误

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#77]
由于使用大雕的default-setting改自己的包，发现有如下错误:
//usr/lib/opkg/info/default-settings.postinst: .: line 130: 99-default-settings: not found
以为是自己代码的问题，后来卸载大雕的default-setting包重新安装也发现这个错误。

**Comment by tomerilery** [comment]
贴日志，贴操作，什么都没有怎么帮你
