### ISSUE TITLE
同步最新源码后手机使用OPENVPN连接SoftEther VPN 服务器连不上，L2TP没有问题。

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#7710]
X86版本
OPENVPN的连接日志：

14:30:18.522 -- EVENT: CONNECTING

14:30:18.523 -- Tunnel Options:V4,dev-type tun,link-mtu 1557,tun-mtu 1500,proto UDPv4,cipher AES-128-CBC,auth SHA1,keysize 128,key-method 2,tls-client

14:30:18.523 -- Creds: Username/Password

14:30:18.523 -- Peer Info:
IV_VER=3.git:released:662eae9a:Release
IV_PLAT=android
IV_NCP=2
IV_TCPNL=1
IV_PROTO=2
IV_GUI_VER=net.openvpn.connect.android_3.2.4-5891
IV_SSO=openurl
IV_HWADDR=36:39:34:62:35:36:66
IV_SSL=OpenSSL 1.1.1h  22 Sep 2020

14:30:18.563 -- VERIFY FAIL: depth=0, /CN=OpenWrt/O=OpenWrt/OU=OpenWrt/C=US [certificate is not yet valid]

14:30:18.565 -- Transport Error: OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

14:30:18.565 -- EVENT: CERT_VERIFY_FAIL info='OpenSSLContext::SSL::read_cleartext: BIO_read failed, cap=2576 status=-1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed'

14:30:18.573 -- EVENT: DISCONNECTED

**Comment by ricksuzade-maker** [comment]
证书无效，可以忽略证书有限性检测再试试。

**Comment by mitsukileung** [comment]
> 
> 
> 证书无效，可以忽略证书有限性检测再试试。

直接按了“continue”还是不行呀
