### ISSUE TITLE
FriendlyWRT for RK3328 无法顺利编译

### ISSUE THREAD

**Issue by minkaka** [coolsnowwolf/lede#7724]
使用友善官方的RK3328提供的源码，openWRT的版本是19.07.5,尝试整合使用 coolsnowwolf/lede

### (2) 路由器型号和固件版本
NanoPi-R2S
平台 [FriendlyWRT for RK3328](http://wiki.friendlyarm.com/wiki/index.php/How_to_Build_FriendlyWrt/zh#RK3328.E5.B9.B3.E5.8F.B0)    版本  19.07.5  

`repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 \
        -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
repo sync -c  --no-clone-bundle`

feeds.conf.default内容如下：
`src-git packages https://github.com/coolsnowwolf/packages
src-git luci https://github.com/coolsnowwolf/luci
src-git routing https://git.lede-project.org/feed/routing.git
src-git telephony https://git.lede-project.org/feed/telephony.git
src-git helloworld https://github.com/fw876/helloworld
src-git kenzok https://github.com/kenzok8/openwrt-packages
src-git small https://github.com/kenzok8/small
src-git base https://git.lede-project.org/source.git

#src-git routing https://git.openwrt.org/feed/routing.git
#src-git telephony https://git.openwrt.org/feed/telephony.git
#src-git freifunk https://github.com/freifunk/openwrt-packages.git
#src-git video https://github.com/openwrt/video.git
#src-git targets https://github.com/openwrt/targets.git
#src-git management https://github.com/openwrt-management/packages.git
#src-git oldpackages http://git.openwrt.org/packages.git
#src-link custom /usr/src/openwrt/custom-feed
#src-git packages https://git.lede-project.org/feed/packages.git
#src-git luci https://git.lede-project.org/project/luci.git
`

 [参考这里](https://www.right.com.cn/FORUM/thread-3769950-1-1.html)尝试在Hyper-v   Ubuntu20 下编译，

./scripts/feeds install -a 后出现以下报错

`dk@ubuntu20:~/friendlywrt-rk3328/friendlywrt$ ./scripts/feeds install -a
ERROR: please fix package/feeds/packages/attendedsysupgrade-common/Makefile - see logs/package/feeds/packages/attendedsysupgrade-common/dump.txt for details
ERROR: please fix package/feeds/packages/wg-installer/Makefile - see logs/package/feeds/packages/wg-installer/dump.txt for details
Collecting package info: done
WARNING: Makefile 'package/feeds/packages/aircrack-ng/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/apache/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/apache/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/atftp/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/audit/Makefile' has a dependency on 'libaudit', which does not exist
WARNING: Makefile 'package/feeds/packages/audit/Makefile' has a dependency on 'libaudit', which does not exist
WARNING: Makefile 'package/feeds/packages/audit/Makefile' has a dependency on 'libaudit', which does not exist
WARNING: Makefile 'package/lean/autocore/Makefile' has a dependency on 'bcm27xx-userland', which does not exist
WARNING: Makefile 'package/lean/automount/Makefile' has a dependency on 'kmod-fs-exfat', which does not exist
WARNING: Makefile 'package/feeds/packages/bandwidthd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/bcm27xx-eeprom/Makefile' has a dependency on 'bcm27xx-userland', which does not exist
WARNING: Makefile 'package/feeds/packages/bluld/Makefile' has a dependency on 'kmod-leds-uleds', which does not exist
WARNING: Makefile 'package/feeds/packages/chrony/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/chrony/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/coreutils/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/coreutils/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/coreutils/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/crun/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/czmq/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/dnsdist/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/dovecot/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/exim/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/fastd/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/fdm/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/freeradius3/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/freeradius3/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/frr/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/frr/Makefile' has a dependency on 'more', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/gnunet/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/grep/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/haproxy/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/haproxy/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/network/utils/iproute2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/jose/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/kamailio/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/kismet/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/kismet/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/kismet/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/kismet/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
WARNING: Makefile 'package/feeds/packages/libcgroup/Makefile' has a dependency on 'musl-fts', which does not exist
WARNING: Makefile 'package/feeds/packages/libsearpc/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/libwebsockets/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/libwebsockets/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/libwebsockets/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/libyang/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/libzip/Makefile' has a dependency on 'musl-fts', which does not exist
WARNING: Makefile 'package/feeds/packages/lighttpd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/lighttpd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/lighttpd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/lighttpd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/lighttpd/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-e2guardian/Makefile' has a dependency on 'e2guardian', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-noddos/Makefile' has a dependency on 'noddos', which does not exist
WARNING: Makefile 'package/feeds/packages/lvm2/Makefile' has a dependency on 'libselinux', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/lxc/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/mariadb/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/mdnsresponder/Makefile' has a build dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/mg/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/lean/n2n_v2/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/net-snmp/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nfdump/Makefile' has a dependency on 'musl-fts', which does not exist
WARNING: Makefile 'package/network/utils/nftables/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/nginx/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nginx/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nginx-util/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/ntpd/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/ntpd/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/ntpd/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/ntpd/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/open-iscsi/Makefile' has a dependency on 'kmod-iscsi-initiator', which does not exist
WARNING: Makefile 'package/feeds/packages/openvswitch/Makefile' has a dependency on 'kmod-nsh', which does not exist
WARNING: Makefile 'package/feeds/packages/podman/Makefile' has a dependency on 'libselinux', which does not exist
WARNING: Makefile 'package/feeds/packages/postfix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/privoxy/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/pulseaudio/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/pulseaudio/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/python3-libselinux/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/python3-libselinux/Makefile' has a dependency on 'musl-fts', which does not exist
WARNING: Makefile 'package/feeds/packages/python3-libselinux/Makefile' has a dependency on 'libselinux', which does not exist
WARNING: Makefile 'package/feeds/packages/python3-libsemanage/Makefile' has a dependency on 'libsemanage', which does not exist
WARNING: Makefile 'package/feeds/telephony/rtpengine/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/rtpengine/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/samba4/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/samba4/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/seafile-ccnet/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/seafile-server/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/seafile-server/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/sed/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/selinux-python/Makefile' has a dependency on 'libselinux', which does not exist
WARNING: Makefile 'package/feeds/packages/selinux-python/Makefile' has a dependency on 'libsepol', which does not exist
WARNING: Makefile 'package/feeds/packages/semodule-utils/Makefile' has a dependency on 'libsepol', which does not exist
WARNING: Makefile 'package/feeds/packages/semodule-utils/Makefile' has a build dependency on 'libsemanage/host', which does not exist
WARNING: Makefile 'package/feeds/packages/setools/Makefile' has a dependency on 'libselinux', which does not exist
WARNING: Makefile 'package/feeds/packages/setools/Makefile' has a dependency on 'libsepol', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocks-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocks-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocks-libev/Makefile' has a build dependency on 'pcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/sipgrep/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/slang2/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/sngrep/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/snort/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/snort3/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/sqm-scripts/Makefile' has a dependency on 'kmod-nss-ifb', which does not exist
WARNING: Makefile 'package/feeds/packages/sqm-scripts/Makefile' has a dependency on 'kmod-qca-nss-drv-qdisc', which does not exist
WARNING: Makefile 'package/feeds/packages/squid/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/sslh/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/sslh/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/sslh/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/syslog-ng/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/tor/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/tor/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/ulogd/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/uwsgi/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/uwsgi/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/wget/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/wget/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/yara/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zsh/Makefile' has a dependency on 'libcap', which does not exist
WARNING: Makefile 'package/feeds/packages/zsh/Makefile' has a dependency on 'libpcre', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed helloworld.
Installing package 'luci-app-ssr-plus' from helloworld
Installing package 'tcping' from helloworld
Installing package 'shadowsocksr-libev' from helloworld
Installing package 'pcre' from base
Installing package 'naiveproxy' from helloworld
Installing package 'shadowsocks-rust' from helloworld
Installing package 'v2ray-plugin' from helloworld
Installing package 'xray-core' from helloworld
Installing package 'v2ray-core' from helloworld
Installing package 'xray-plugin' from helloworld
Installing all packages from feed kenzok.
Installing package 'AdGuardHome' from kenzok
Installing package 'gost' from kenzok
Installing package 'lua-maxminddb' from kenzok
Installing package 'luci-app-adguardhome' from kenzok
Installing package 'luci-app-advanced' from kenzok
Installing package 'luci-app-aliddns' from kenzok
Installing package 'luci-app-argon-config' from kenzok
Installing package 'luci-app-clash' from kenzok
Installing package 'luci-app-dnsfilter' from kenzok
Installing package 'luci-app-eqos' from kenzok
Installing package 'luci-app-fileassistant' from kenzok
Installing package 'luci-app-gost' from kenzok
Installing package 'luci-app-openclash' from kenzok
Installing package 'libcap' from base
Installing package 'luci-app-passwall' from kenzok
Installing package 'brook' from small
Installing package 'chinadns-ng' from small
Installing package 'hysteria' from small
Installing package 'trojan-go' from small
Installing package 'trojan-plus' from small
Installing package 'luci-app-serverchan' from kenzok
Installing package 'luci-app-smartdns' from kenzok
Installing package 'luci-app-ssr-mudb-server' from kenzok
Installing package 'luci-app-vssr' from kenzok
Installing package 'luci-theme-argon_new' from kenzok
Installing package 'luci-theme-atmaterial_new' from kenzok
Installing package 'luci-theme-edge' from kenzok
Installing package 'luci-theme-ifit' from kenzok
Installing package 'luci-theme-opentomato' from kenzok
Installing package 'luci-theme-opentomcat' from kenzok
Installing package 'luci-theme-opentopd' from kenzok
Installing all packages from feed small.
Installing package 'openssl1.1' from small
Installing package 'ssocks' from small
Installing all packages from feed base.
Installing package 'arm-trusted-firmware-mediatek' from base
Installing package 'arm-trusted-firmware-mvebu' from base
Installing package 'arm-trusted-firmware-rockchip' from base
Installing package 'arm-trusted-firmware-tools' from base
Installing package 'bcm27xx-gpu-fw' from base
Installing package 'bcm27xx-userland' from base
Installing package 'bcm4908img' from base
Installing package 'bcm63xx-cfe' from base
Installing package 'bpftools' from base
Installing package 'checkpolicy' from base
Installing package 'libselinux' from base
Installing package 'libsepol' from base
Installing package 'musl-fts' from base
Installing package 'cypress-firmware' from base
Installing package 'cypress-nvram' from base
Installing package 'firewall4' from base
Installing package 'ucode' from base
Installing package 'gpio-nxp-74hc153' from base
Installing package 'jansson' from base
Installing package 'libaudit' from base
Installing package 'libsemanage' from base
Installing package 'ls-ddr-phy' from base
Installing package 'ltq-dsl-base' from base
Installing package 'mt7621-qtn-rgmii' from base
Installing package 'mt7623n-preloader' from base
Installing package 'policycoreutils' from base
Installing package 'px5g-mbedtls' from base
Installing package 'px5g-wolfssl' from base
Installing package 'ravpower-mcu' from base
Installing package 'refpolicy' from base
Installing package 'secilc' from base
Installing package 'selinux-policy' from base
Installing package 'uboot-mediatek' from base
WARNING: No feed for package 'trusted-firmware-a-mt7622-emmc-2ddr' found
WARNING: No feed for package 'trusted-firmware-a-mt7622-sdmmc-2ddr' found
WARNING: No feed for package 'trusted-firmware-a-mt7622-snand-2ddr' found
WARNING: No feed for package 'trusted-firmware-a-mt7622-snand-1ddr' found
WARNING: No feed for package 'trusted-firmware-a-mt7622-nor-2ddr' found
Installing package 'uboot-ramips' from base
Installing package 'uboot-rockchip' from base
Installing package 'zip' from base
Installing all packages from feed routing.
Installing all packages from feed telephony.
dk@ubuntu20:~/friendlywrt-rk3328/friendlywrt$
 `

**Comment by AmadeusGhost** [comment]
友善官方的代码关这里屁事，去找他们啊。
