### ISSUE TITLE
刷入的固件默认有密码，请问默认密码是什么？

### ISSUE THREAD

**Issue by danuonuo** [coolsnowwolf/lede#7741]

**Comment by danuonuo** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [x] 没有类似的issue
> 
> ## 2. 详细叙述
> 我新刷入的自编译固件，luci要求输入密码，由于我的路由器没有刷breed，导致无法使用，也进不了安全模式。

**Comment by EnnawYang** [comment]
但凡看过readme也不会问出这种问题

**Comment by danuonuo** [comment]
> 但凡看过readme也不至于能问出这种问题

那麻烦你指明一下？我哪没看到吗
