### ISSUE TITLE
内核5.4.142云编译固件反复失败

### ISSUE THREAD

**Issue by aliguoguo** [coolsnowwolf/lede#7757]
反馈bug/问题模板，提建议请删除

1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
[ ] 没有类似的issue

 2. 详细叙述

(1) 具体问题

A：内核5.4.142版本云编译(P3TERX/Actions-OpenWrt这个项目云编译)一直失败，之前的版本云编译全部都没问题能编译成功，并且现在只额外编译openclash插件，其余全是L大内置的，同样反复报错。

 (2) 路由器型号和固件版本

A：极路由1S MT7620 HC5661

(3) 详细日志

A：
build
failed 10 minutes ago in 1h 5m 3s
Search logs
3s
1s
2m 42s
11s
42s
23s
22s
0s
5m 32s
2m 8s
52m 59s
Run cd openwrt
  cd openwrt
  echo -e "$(nproc) thread compile"
  make -j$(nproc) || make -j1 || make -j1 V=s
  echo "::set-output name=status::success"
  grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
  [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
  echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: .config
    DIY_P1_SH: diy-part1.sh
    DIY_P2_SH: diy-part2.sh
    UPLOAD_BIN_DIR: true
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    UPLOAD_RELEASE: false
    TZ: Asia/Shanghai
2 thread compile
 make[1] world
 make[2] tools/compile
 make[2] package/cleanup
 make[3] -C tools/flock compile
 make[3] -C tools/xz compile
 make[3] -C tools/sed compile
 make[3] -C tools/patch compile
 make[3] -C tools/tar compile
 make[3] -C tools/m4 compile
 make[3] -C tools/autoconf-archive compile
 make[3] -C tools/pkgconf compile
 make[3] -C tools/ninja compile
 make[3] -C tools/cpio compile
 make[3] -C tools/lzma compile
 make[3] -C tools/mtools compile
 make[3] -C tools/patch-image compile
 make[3] -C tools/sstrip compile
 make[3] -C tools/ucl compile
 make[3] -C tools/xxd compile
 make[3] -C tools/zip compile
 make[3] -C tools/expat compile
 make[3] -C tools/autoconf compile
 make[3] -C tools/libressl compile
 make[3] -C tools/automake compile
 make[3] -C tools/missing-macros compile
 make[3] -C tools/dosfstools compile
 make[3] -C tools/upx compile
 make[3] -C tools/libtool compile
 make[3] -C tools/cmake compile
 make[3] -C tools/mkimage compile
 make[3] -C tools/mklibs compile
 make[3] -C tools/mm-macros compile
 make[3] -C tools/patchelf compile
 make[3] -C tools/gmp compile
 make[3] -C tools/flex compile
 make[3] -C tools/e2fsprogs compile
 make[3] -C tools/fakeroot compile
 make[3] -C tools/gengetopt compile
 make[3] -C tools/mpfr compile
 make[3] -C tools/bison compile
 make[3] -C tools/mpc compile
 make[3] -C tools/bc compile
 make[3] -C tools/findutils compile
 make[3] -C tools/padjffs2 compile
 make[3] -C tools/quilt compile
 make[3] -C tools/zlib compile
 make[3] -C tools/zstd compile
 make[3] -C tools/firmware-utils compile
 make[3] -C tools/make-ext4fs compile
 make[3] -C tools/mtd-utils compile
 make[3] -C tools/squashfskit4 compile
 make[2] toolchain/compile
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/fortify-headers compile
 make[3] -C toolchain/gcc/initial compile
 make[3] -C toolchain/kernel-headers compile
 make[3] -C toolchain/musl compile
 make[3] -C toolchain/gcc/final compile
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[2] package/compile
 make[3] diffconfig buildversion feedsversion
 make[3] -C package/libs/libjson-c host-compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/libs/toolchain compile
 make[3] -C feeds/packages/lang/ruby host-compile
 make[3] -C feeds/packages/libs/yaml compile
 make[3] -C package/libs/libjson-c compile
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Terminated
Error: Process completed with exit code 143.

**Comment by vsvkhs** [comment]
被没日没夜定时编译玩家玩坏了，我们这些偶尔手动编译自己用的固件也遭殃

**Comment by aliguoguo** [comment]
> 被没日没夜定时编译玩家玩坏了，我们这些偶尔手动编译自己用的固件也遭殃

对啊，云编译真的挺省事的，我都是一两个月才编译一次

**Comment by VergilGao** [comment]
研究了一下，最近云编译如果用老办法，通过tmate ssh进入workflow make menuconfig，大概率会在编译时被github中断，但是不用tmate的话，就可以完成编译，所以很显然，是tmate的问题。
所以我把ssh进入配置这一步单独提出来，make menuconfig之后直接上传.config文件，退出workflow，然后再把.config文件提交，进入自动化workflow过程，这样就可以顺利的完成编译了。

**Comment by fucktimi** [comment]
> 研究了一下，最近云编译如果用老办法，通过tmate ssh进入workflow make menuconfig，大概率会在编译时被github中断，但是不用tmate的话，就可以完成编译，所以很显然，是tmate的问题。
> 所以我把ssh进入配置这一步单独提出来，make menuconfig之后直接上传.config文件，退出workflow，然后再把.config文件提交，进入自动化workflow过程，这样就可以顺利的完成编译了。
> 具体代码可以参考我这里：
> https://github.com/VergilGao/openwrt-compiler/tree/master/.github/workflows
> 我这里其他部分做了一些修改，可能和你们的云编译脚本不一样，但是作为参考还是可以的。

github好坑啊，我也是一直直接编译就能成功，ssh一下就不行了，我一直以为是自己修改的配置有问题，直到现在我试了ssh不改配置，还是失败，正在迷茫，还好给我查到这个issus了。前后浪费了快一星期了。

**Comment by iPixelOldC** [comment]
> 研究了一下，最近云编译如果用老办法，通过tmate ssh进入workflow make menuconfig，大概率会在编译时被github中断，但是不用tmate的话，就可以完成编译，所以很显然，是tmate的问题。 所以我把ssh进入配置这一步单独提出来，make menuconfig之后直接上传.config文件，退出workflow，然后再把.config文件提交，进入自动化workflow过程，这样就可以顺利的完成编译了。 具体代码可以参考我这里： https://github.com/VergilGao/openwrt-compiler/tree/master/.github/workflows 我这里其他部分做了一些修改，可能和你们的云编译脚本不一样，但是作为参考还是可以的。

...原来如此，我用我自己的机器做runner都被取消了，哎
