### ISSUE TITLE
frc客户端依旧不能启动

### ISSUE THREAD

**Issue by oceange8** [coolsnowwolf/lede#7799]
如题，frp最新版更新到0.37.1后，重新编译。
但是路由 frc客户端不能启动，服务端是正常的
原来0.37.0的时候是正常的。
也没有日志，不知道问题在哪里

<img width="326" alt="新建位图图像" src="https://user-images.githubusercontent.com/77355776/131905217-f16b4365-6fda-424d-a4aa-5544d669ad8d.png">

**Comment by yaott2020-666** [comment]
/etc/init.d/frpc start

**Comment by oceange8** [comment]
真的很奇怪，过了2天，今天进去看，居然正常了。
