### ISSUE TITLE
 k2p选择开源驱动只有5g信号，没有2.4g

### ISSUE THREAD

**Issue by chenjinzhe** [coolsnowwolf/lede#7806]
反馈bug/问题模板，提建议请删除

## 1.
k2p选择开源驱动只有5g信号，没有2.4g
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) k2p

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
测过了，没这个问题
