### ISSUE TITLE
编译时如何取消防火墙默认的自定义规则

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#7815]
由于特殊需要，编译时需要取消如下规则？：
 iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
 iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
 [ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
 [ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

在哪里修改呢？

**Comment by loryncien** [comment]
lede/package/lean/default-settings/files/zzz-default-settings

**Comment by gswangmd-gssi** [comment]
thanks

**Comment by zhangguanzhang** [comment]
解决了就把issue关了吧
