### ISSUE TITLE
每次看到Lean改动后，我该如何同步自己的路由器？

### ISSUE THREAD

**Issue by choushui007** [coolsnowwolf/lede#784]
到重新刷固件，还是有别的办法？

**Comment by wangqingzh** [comment]
重新编译 然后更新？

**Comment by 878779616** [comment]
极路由1s H5661 编译好的固件，保留翻Q的App https://share.weiyun.com/5TBR9b9 最新，自取

**Comment by choushui007** [comment]
make[5]: Nothing to be done for 'modules'.
make[5]: Leaving directory '/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78'
cmp -s /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/vmlinux /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/vmlinux.debug || { mipsel-openwrt-linux-musl-objcopy -O binary -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/vmlinux /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/vmlinux; mipsel-openwrt-linux-musl-objcopy -R .reginfo -R .notes -R .note -R .comment -R .mdebug -R .note.gnu.build-id -S /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/vmlinux /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/vmlinux.elf; cp -fpR /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/vmlinux /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/vmlinux.debug;  }
touch /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/.image
make -C image compile install TARGET_BUILD=
make[5]: Entering directory '/home/ce6093/lede/target/linux/ramips/image'
make[5]: Nothing to be done for 'compile'.
mkdir -p /home/ce6093/lede/bin/targets/ramips/mt7620 /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp
/home/ce6093/lede/staging_dir/host/bin/mksquashfs4 /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/root-ramips /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/root.squashfs -nopad -noappend -root-owned -comp xz -Xpreset 9 -Xe -Xlc 0 -Xlp 2 -Xpb 2  -b 256k -p '/dev d 755 0 0' -p '/dev/console c 600 0 0 5 1' -processors 1 -fixed-time 1541834556
rm -f /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin
cp /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/vmlinux /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin
Parallel mksquashfs: Using 1 processor
Creating 4.0 filesystem on /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/root.squashfs, block size 262144.
mipsel-openwrt-linux-musl-cpp -nostdinc -x assembler-with-cpp -I/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/arch/mips/boot/dts -I/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/arch/mips/boot/dts/include -I/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/include/ -undef -D__DTS__  -o /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb.tmp ../dts/HC5661.dts
Pseudo file "/dev" exists in source filesystem "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/root-ramips/dev".
Ignoring, exclude it (-e/-ef) to override.
[|                                                                                              ]    0/3085   0%/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.78/scripts/dtc/dtc -O dtb -i../dts/  -o /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb.tmp
/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb: Warning (pci_bridge): Node /pcie@10140000/pcie@0,0 missing bus-range for PCI bridge
/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb: Warning (unit_address_format): Failed prerequisite 'pci_bridge'
/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb: Warning (pci_device_reg): Failed prerequisite 'pci_bridge'
/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb: Warning (pci_device_bus_num): Failed prerequisite 'pci_bridge'
rm -f /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb.tmp
/home/ce6093/lede/staging_dir/host/bin/patch-dtb /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.dtb
DT size used is default of 16KB
/home/ce6093/lede/staging_dir/host/bin/lzma e /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin -lc1 -lp2 -pb2  /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.new
[=======================|                                                                       ]  784/3085  25%mkimage -A mips -O linux -T kernel -C lzma -a 0x80000000 -e 0x80000000 -n 'MIPS OpenWrt Linux-4.14.78' -d /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.new
Image Name:   MIPS OpenWrt Linux-4.14.78
Created:      Sat Nov 10 07:22:36 2018
Image Type:   MIPS Linux Kernel Image (lzma compressed)
Data Size:    1469891 Bytes = 1435.44 KiB = 1.40 MiB
Load Address: 80000000
Entry Point:  80000000
mv /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin.new /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin
[==============================================================================================-] 3085/3085 100%
Exportable Squashfs 4.0 filesystem, xz compressed, data block size 262144
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 17085.13 Kbytes (16.68 Mbytes)
	28.98% of uncompressed filesystem size (58947.53 Kbytes)
Inode table size 26674 bytes (26.05 Kbytes)
	22.13% of uncompressed inode table size (120552 bytes)
Directory table size 36889 bytes (36.02 Kbytes)
	44.95% of uncompressed directory table size (82061 bytes)
Number of duplicate files found 339
Number of inodes 3589
Number of files 2958
Number of fragments 88
Number of symbolic links  408
Number of device nodes 1
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 222
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
[ -f /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin -a -f /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/root.squashfs ]
dd if=/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/hc5661-kernel.bin >> /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin
2871+1 records in
2871+1 records out
1469955 bytes (1.5 MB, 1.4 MiB) copied, 0.0114794 s, 128 MB/s
dd if=/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/root.squashfs >> /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin
34170+1 records in
34170+1 records out
17495173 bytes (17 MB, 17 MiB) copied, 0.0778171 s, 225 MB/s
/home/ce6093/lede/staging_dir/host/bin/padjffs2 /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin  4 8 16 64 128 256
padding image to 01217000
padding image to 01218000
padding image to 01220000
padding image to 01240000
echo '{  "supported_devices":["hc5661"], "version": { "dist": "OpenWrt", "version": "18.06.1", "revision": "r944-2dc71cc4", "board": "ramips" } }' | fwtool -I - /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin
[ ! -s "/home/ce6093/lede/key-build" -o ! -s "/home/ce6093/lede/key-build.ucert" ] || { cp "/home/ce6093/lede/key-build.ucert" "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin.ucert" ; usign -S -m "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin" -s "/home/ce6093/lede/key-build" -x "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin.sig" ; ucert -A -c "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin.ucert" -x "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin.sig" ; fwtool -S "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin.ucert" "/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin" ; }
WARNING: Image file /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin is too big
cp /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin /home/ce6093/lede/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin
cp: cannot stat '/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin': No such file or directory
Makefile:287: recipe for target '/home/ce6093/lede/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin' failed
make[5]: [/home/ce6093/lede/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-hc5661-squashfs-sysupgrade.bin] Error 1 (ignored)
IPKG_NO_SCRIPT=1 IPKG_INSTROOT=/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/root.orig-ramips TMPDIR=/home/ce6093/lede/build_dir/target-mipsel_24kc_musl/root.orig-ramips/tmp /home/ce6093/lede/staging_dir/host/bin/opkg --offline-root /home/ce6093/lede/build_dir/target-mipsel_24kc_musl/root.orig-ramips --force-postinstall --add-dest root:/ --add-arch all:100 --add-arch mipsel_24kc:200 list-installed > /home/ce6093/lede/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-device-hc5661.manifest
make[5]: Leaving directory '/home/ce6093/lede/target/linux/ramips/image'
make[4]: Leaving directory '/home/ce6093/lede/target/linux/ramips'
make[3]: Leaving directory '/home/ce6093/lede/target/linux'
time: target/linux/install#25.73#3.43#30.89
make[2]: Leaving directory '/home/ce6093/lede'
make[1]: Leaving directory '/home/ce6093/lede'

再次编译，加了V2就出错了，奇怪
