### ISSUE TITLE
编译固件选项里Xiaomi Mi Router R3没有了

### ISSUE THREAD

**Issue by daidaiwood** [coolsnowwolf/lede#7841]
最近编译固件时选项里Xiaomi Mi Router R3没有了。
请问是怎么回事？

**Comment by Dimitri2020007** [comment]
千兆无线，百兆有线的垃圾早就该淘汰了

**Comment by daidaiwood** [comment]
还是有发挥余热的地方的么

**Comment by Dimitri2020007** [comment]
除了刷不死以外已经一无是处

除非你网速在100m以下而且没有任何多拨的需求

**Comment by daidaiwood** [comment]
committed on 13 Jul 
我查到是在这个commit 3625a730463a8adc32790b7af3d7867a1136cbb1
删掉支持的，老大能恢复吗？

**Comment by Dimitri2020007** [comment]
这个我恢复不了

但是我用过这个路由器

**Comment by daidaiwood** [comment]
找到办法了
