### ISSUE TITLE
今天想更新一下LEDE，重新编译，发现以前的hello world没有了，现在怎么让ssrplus+出来啊

### ISSUE THREAD

**Issue by WONGHONGXU** [coolsnowwolf/lede#7843]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by dawn2000** [comment]
echo "src-git helloworld https://github.com/fw876/helloworld.git" >> feeds.conf.default
