### ISSUE TITLE
CONFIG_PACKAGE_luci-app-cpufreq=y 在r2s的rockchip不生效

### ISSUE THREAD

**Issue by zhangguanzhang** [coolsnowwolf/lede#7844]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：r2s编译开了`CONFIG_PACKAGE_luci-app-cpufreq=y`后，但是编译出来的固件没有它，我看编译完的`config.buildinfo`里也没它。`opkg list | grep ` 了下也没找到它

```
CONFIG_TARGET_rockchip=y
CONFIG_TARGET_rockchip_armv8=y
CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r2s=y

CONFIG_TARGET_KERNEL_PARTSIZE=120
CONFIG_TARGET_ROOTFS_PARTSIZE=1200
# CONFIG_TARGET_ROOTFS_TARGZ is not set
CONFIG_TARGET_ROOTFS_EXT4FS=y
CONFIG_TARGET_ROOTFS_SQUASHFS=y

CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
# CONFIG_IB is not set
# CONFIG_IB_STANDALONE is not set
# CONFIG_IMAGEOPT is not set
# CONFIG_MAKE_TOOLCHAIN is not set
# CONFIG_SDK is not set

# CONFIG_HAS_TESTING_KERNEL is not set
CONFIG_PACKAGE_luci-app-cpufreq=y
...
```

### (2) 路由器型号和固件版本

A：r2s , `rk3328`

### (3) 详细日志

A：1

**Comment by Boos4721** [comment]
https://github.com/coolsnowwolf/lede/blob/12d4b91c8bdf49e47105189d7f64ad203939c378/package/lean/luci-app-cpufreq/Makefile#L10

**Comment by zhangguanzhang** [comment]
> https://github.com/coolsnowwolf/lede/blob/12d4b91c8bdf49e47105189d7f64ad203939c378/package/lean/luci-app-cpufreq/Makefile#L10

这个要开啥

**Comment by walker365** [comment]
https://github.com/DHDAXCW/NanoPi-R2S-2021/blob/main/scripts/lean.sh
骷髅头大佬云编译脚本里面cpufreq相关代码可以解决 ，拉取了immortalwrt里面的cpufreq，实测有效，不过编译出来插件名称是cpufreq，下面是相关代码

# Add cpufreq
rm -rf package/lean/luci-app-cpufreq
svn co https://github.com/immortalwrt/luci/trunk/applications/luci-app-cpufreq feeds/luci/applications/luci-app-cpufreq
ln -sf ../../../feeds/luci/applications/luci-app-cpufreq ./package/feeds/luci/luci-app-cpufreq
sed -i 's,1608,1800,g' feeds/luci/applications/luci-app-cpufreq/root/etc/uci-defaults/cpufreq
sed -i 's,2016,2208,g' feeds/luci/applications/luci-app-cpufreq/root/etc/uci-defaults/cpufreq
sed -i 's,1512,1608,g' feeds/luci/applications/luci-app-cpufreq/root/etc/uci-defaults/cpufreq

**Comment by zhangguanzhang** [comment]
有空我看下，感谢回复

**Comment by zhangguanzhang** [comment]
@walker365 你人呢

**Comment by walker365** [comment]
> @walker365 你人呢

回复被删了

**Comment by zhangguanzhang** [comment]
> > @walker365 你人呢
> 
> 回复被删了

我看着是你删除的

**Comment by walker365** [comment]
> Repository owner deleted a comment from [walker365](/walker365) [20小时前](#event-5689778455)

Repository owner deleted a comment from walker365 20 hours ago

Repository owner

**Comment by zhangguanzhang** [comment]
😂好吧，这个contributer真是服了
