### ISSUE TITLE
按照LEAN的方法编译了网件R7500V1固件，刷机报固件错，刷不进去

### ISSUE THREAD

**Issue by fzhy2003** [coolsnowwolf/lede#7851]
## 2. 详细叙述
按照LEAN大侠的编译步骤制作了一个固件，刷机报错，刷不进去，提示固件不是此设备对应的固件，编译时选的是IPQ806X 第二项默认，第三项选择网件R7500V1，机器也是这个型号，编译过程也正常，没报错，请问是什么原因

**Comment by coolsnowwolf** [comment]
TFTP 刷，

**Comment by fzhy2003** [comment]
试过，刷了无限重启

**Comment by fzhy2003** [comment]
刷OPENWRT提供的固件就OK

**Comment by fzhy2003** [comment]
是源码的问题，换了openwrt的源码能刷了

**Comment by tsasan** [comment]
> 是源码的问题，换了openwrt的源码能刷了

请问OPENWRT提供的固件大小是多少M？您编译Lean大源码生成的固件大小是多少M？我用的7500V2，编译生成的固件50-60M，tftp刷进去了，但是不生效。我怀疑是固件尺寸问题。

**Comment by fzhy2003** [comment]
编译完后的固件是8.8M 用TFTP方式刷入，能运行，但服务没有出来，不知道什么原因





黄建松
抚州联硕科技有限公司


 联系我














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coolsnowwolf/lede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 下午5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] 按照LEAN的方法编译了网件R7500V1固件，刷机报固件错，刷不进去 (#7851)





  
是源码的问题，换了openwrt的源码能刷了
  
请问OPENWRT提供的固件大小是多少M？您编译Lean大源码生成的固件大小是多少M？我用的7500V2，编译生成的固件50-60M，tftp刷进去了，但是不生效。我怀疑是固件尺寸问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
