### ISSUE TITLE
nginx ssl生成证书有效期怎么修改

### ISSUE THREAD

**Issue by Dimitri2020007** [coolsnowwolf/lede#7857]
如题

nginx自签证书有效期没有找到修改的位置

**Comment by EnnawYang** [comment]
有效期还能随意改的？

**Comment by Dimitri2020007** [comment]
> 有效期还能随意改的？

修改编译时候用到的config啊

我在uhttpd上成功的修改了有效期

<img width="342" alt="捕获" src="https://user-images.githubusercontent.com/72486732/133060901-9f030d0b-988e-4e4d-88d1-1225ddd6f4cc.PNG">

uhttpd能改的了有效期的话nginx的自签证书也能改的了有效期

**Comment by Dimitri2020007** [comment]
已找到nginx自签证书有效期修改位置

<img width="396" alt="捕获" src="https://user-images.githubusercontent.com/72486732/133065347-99090250-074b-4417-a379-13429e062502.PNG">

issue可以关闭
