### ISSUE TITLE
luci-app-turboacc全锥形状态异常

### ISSUE THREAD

**Issue by WYC-2020** [coolsnowwolf/lede#7858]
在防火墙位置开启启用FullCone-NAT后
![image](https://user-images.githubusercontent.com/34025388/133192135-5c15d4a9-f1f4-4991-9a59-6516c22fdadd.png)

在Turbo ACC 网络加速设置可以看到全锥形运行，但是下面的复选框没有选择，然后重启路由器后全锥形并没有运行，麻烦大佬们看下咋修复一下，谢谢

**Comment by helllkz** [comment]
好像有2个地方可以选，ShortFE里面取消了保存，防火墙也会取消，防火墙勾选了，ShortFE不会勾选，会显示运行就是了，不过我没试过重启

**Comment by WYC-2020** [comment]
@helllkz 应该是从防火墙哪里改了状态后没有同步到turbo的配置里面，可以在检测是否运行的时候 顺便吧这个配置文件也更新 了，同时在更新下界面上面那个复选框就可以了
