### ISSUE TITLE
Watchcat在更新后会丢失配置

### ISSUE THREAD

**Issue by wang1zhen** [coolsnowwolf/lede#7859]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：watchcat在更新固件后会丢失当前配置并恢复默认设置

### (2) 路由器型号和固件版本

A：
<html>
<body>

主机型号 | Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread
-- | --
固件版本 | OpenWrt R21.8.6 / LuCI Master (git-21.238.35254-83494a9)
内核版本 | 5.4.143

</body>
</html>

### (3) 详细日志

A：无具体日志，详细情况如下：

watchcat新添加的配置会被保存在`/etc/config/system`中，如：

```
config watchcat
        option mode 'ping'
        option forcedelay '60'
        option period '10'
        option pinghosts 'baidu.com'
        option pingperiod '12'
```

但在固件更新后（保留系统配置），该段落会丢失，并会自动在`/etc/config`目录下重新生成`watchcat`文件，内容为默认配置，在日志（未保存）中也可以看到确实被启用了，但在web管理界面下没有显示。

**Comment by lphgor** [comment]
[watchcat](https://github.com/coolsnowwolf/packages/tree/master/utils/watchcat) 近期更新过了，把配置文件改到`/etc/config/watchcat`了，但是 [luci-app-watchcat](https://github.com/coolsnowwolf/luci/tree/master/applications/luci-app-watchcat) 没有同步更新，两边不一致
