### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by richarddan** [coolsnowwolf/lede#7860]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：时不时会出现kernel panic，想咨询一下具体定位思路，我自己往下查查。

### (2) 路由器型号和固件版本

A：PVE Virtual Machine X86-64

### (3) 详细日志

A：

Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.393276] ------------[ cut here ]------------
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.399682] WARNING: CPU: 3 PID: 4886 at kthread_is_per_cpu+0x20/0x40
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.400646] Modules linked in: fast_classifier xt_FULLCONENAT ath9k ath9k_htc ath9k_common rt2800usb rt2800lib pppoe ppp_async ath9k_hw ath5k ath10k_pci ath10k_core ath rt2x00usb rt2x00lib pppox ppp_mppe ppp_generic mac80211 iptable_nat ipt_REJECT cfg80211 ax88179_178a asix xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_socket xt_recent xt_quota xt_policy xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_esp xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_cgroup xt_addrtype xt_TPROXY xt_TCPMSS xt_REDIRECT xt_MASQUERADE xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY usbnet ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda tulip ts_fsm ts_bm tcp_bbr slhc rtl8150 r8168 r8152 r8125 pcnet32 nf_tproxy_ipv6 nf_tproxy_ipv4 nf_socket_ipv6 nf_socket_ipv4 nf_reject_ipv4 nf_nat_tftp nf_nat_snmp_basic nf_nat_sip nf_nat_pptp nf_nat_irc nf_nat_h323 nf_nat_ftp
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.400691]  nf_nat_amanda nf_nat nf_log_ipv4 nf_conntrack_tftp nf_conntrack_snmp nf_conntrack_sip nf_conntrack_pptp nf_conntrack_netlink nf_conntrack_irc nf_conntrack_h323 nf_conntrack_ftp nf_conntrack_broadcast ts_kmp nf_conntrack_amanda nf_conncount mmc_spi mlx5_core mlx4_en mlx4_core macvlan libcrc32c iptable_raw iptable_mangle iptable_filter ipt_ah ipt_ECN ip_tables igc i40e forcedeth e1000e crc7 crc_itu_t crc_ccitt compat bnx2 asn1_decoder 8139too 8139cp act_connmark nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 sch_tbf sch_ingress sch_htb sch_hfsc em_u32 cls_u32 cls_tcindex cls_route cls_matchall cls_fw cls_flow cls_basic act_skbedit act_mirred act_gact evdev i2c_dev cryptodev xt_set ip_set_list_set ip_set_hash_netportnet ip_set_hash_netport ip_set_hash_netnet ip_set_hash_netiface ip_set_hash_net ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.411026]  nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 bonding ixgbevf ixgbe igbvf igb e1000 amd_xgbe mdio_devres ifb mdio ipcomp6 xfrm6_tunnel esp6 ah6 xfrm4_tunnel ipcomp esp4 ah4 tunnel6 tunnel4 tun xfrm_user xfrm_ipcomp af_key xfrm_algo nls_utf8 ena shortcut_fe_ipv6 shortcut_fe crypto_user algif_skcipher algif_rng algif_hash algif_aead af_alg sha256_ssse3 sha256_generic libsha256 sha1_ssse3 sha1_generic seqiv jitterentropy_rng drbg md5 hmac echainiv des_generic libdes deflate cmac cbc authenc arc4 crypto_acompress nls_iso8859_1 nls_cp437 vfat fat uas sdhci_pltfm exfat antfs button_hotplug ptp pps_core mii libphy
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.426814] CPU: 3 PID: 4886 Comm: clash Not tainted 5.10.46 #0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.428209] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org 04/01/2014
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.431126] RIP: 0010:kthread_is_per_cpu+0x20/0x40
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.432528] Code: 0f 0b eb d5 0f 0b eb e5 66 90 f6 47 26 20 74 16 48 8b 87 c0 04 00 00 48 85 c0 74 07 48 8b 00 83 e0 01 c3 31 c0 c3 55 48 89 e5 <0f> 0b 48 8b 87 c0 04 00 00 48 85 c0 74 08 48 8b 00 5d 83 e0 01 c3
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.436168] RSP: 0018:ffffc90000c17a70 EFLAGS: 00010046
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.437687] RAX: ffff88807dda0e80 RBX: ffffc90000c17af8 RCX: 0000000000000003
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.438879] RDX: 0000000000000003 RSI: ffffc90000c17af8 RDI: ffff8880030d1b00
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.440012] RBP: ffffc90000c17a70 R08: 0000000000000000 R09: 0000000000000000
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.441108] R10: 0000000000000002 R11: 0000000000000000 R12: ffff8880030d1b00
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.442194] R13: 0000000000000000 R14: 0000000000000000 R15: ffff88807dca0e40
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.443281] FS:  000000c0001b2090(0000) GS:ffff88807dd80000(0000) knlGS:0000000000000000
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.444421] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.445422] CR2: 00007fa2255b4005 CR3: 0000000004f96005 CR4: 0000000000370ee0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.446568] Call Trace:
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.447409]  can_migrate_task+0x159/0x180
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.448313]  load_balance+0x3ce/0xaf0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.449197]  newidle_balance.isra.126+0x155/0x2e0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.450178]  pick_next_task_fair+0x38/0x370
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.451082]  __schedule+0x1a8/0x480
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.451935]  schedule+0x3b/0xa0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.452782]  schedule_timeout+0x191/0x1e0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.453674]  ? wake_up_process+0x10/0x20
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.454554]  wait_for_completion_killable+0xa3/0x140
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.455529]  call_usermodehelper_exec+0x106/0x150
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.456448]  __request_module+0x157/0x340
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.457275]  ? _copy_to_user+0x20/0x30
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.458114]  ? nf_ct_netns_get+0x1c9/0x420 [nf_conntrack]
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.459088]  ? __wake_up_common_lock+0x78/0x90
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.459952]  netlink_create+0xd9/0x240
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.460755]  __sock_create+0xdc/0x170
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.461540]  __sys_socket+0x46/0xc0
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.462266]  __x64_sys_socket+0x15/0x20
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.463073]  do_syscall_64+0x37/0x50
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.463818]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.464621] RIP: 0033:0x4b8976
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.465291] Code: cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc 48 8b 7c 24 10 48 8b 74 24 18 48 8b 54 24 20 48 8b 44 24 08 0f 05 <48> 3d 01 f0 ff ff 76 1b 48 c7 44 24 28 ff ff ff ff 48 c7 44 24 30
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.467460] RSP: 002b:000000c00104f850 EFLAGS: 00000212 ORIG_RAX: 0000000000000029
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.468414] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00000000004b8976
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.469333] RDX: 0000000000000004 RSI: 0000000000000002 RDI: 0000000000000010
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.470240] RBP: 000000c00104f898 R08: 0000000000b38ba0 R09: 0000000000000000
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.471147] R10: 0000000000000000 R11: 0000000000000212 R12: 0000000000000001
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.472035] R13: 0000000000000001 R14: 0000000000000020 R15: ffffffffffffffff
Wed Sep 15 04:06:35 2021 kern.warn kernel: [ 9665.472878] ---[ end trace 78fffdf43c53e299 ]---

**Comment by Kisoul** [comment]
我也有类似的错误，不知道有什么影响
