### ISSUE TITLE
aMule-2.3.2 编译报错

### ISSUE THREAD

**Issue by yonggedebaqi** [coolsnowwolf/lede#7862]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

aMule-2.3.2

### (2) 路由器型号和固件版本

armvirt_64

### (3) 详细日志

make[6]: *** No rule to make target 'libgnuintl.@INTL_LIBTOOL_SUFFIX_PREFIX@a', needed by 'all-no-yes'.  Stop.
make[5]: *** [Makefile:584: all-recursive] Error 1
make[4]: *** [Makefile:491: all] Error 2
make[4]: Leaving directory '/home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/aMule-2.3.2'
make[3]: *** [Makefile:114: /home/openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/aMule-2.3.2/.built] Error 2
make[3]: Leaving directory '/home/openwrt/lede/package/lean/amule'
time: package/lean/amule/compile#26.82#12.35#42.31
    ERROR: package/lean/amule failed to build.
make[2]: *** [package/Makefile:116: package/lean/amule/compile] Error 1
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:110: /home/openwrt/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:230：world] 错误 2

**Comment by Her0R0cket** [comment]
https://github.com/kiddin9/openwrt-packages 这个最底下有编译好的,你看看有可以用的吗?,我编译了x86和,mipsle的是不报错的
