### ISSUE TITLE
没有预设配置的.config文件情况下用Actions编译错误

### ISSUE THREAD

**Issue by Ho-Lay** [coolsnowwolf/lede#7863]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：没有预设的.config文件下编译错误，总是在make[3] -C toolchain/gcc/initial compile之后就出现错误

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：make[2] toolchain/compile
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/fortify-headers compile
 make[3] -C toolchain/gcc/initial compile
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Error: The operation was canceled.

**Comment by 110010110** [comment]
#7757

**Comment by Ho-Lay** [comment]
> 关闭吧，这个是github官方导致的

但是假如把以前编译过的config文件直接拿来用是可以很顺利编译成功

**Comment by 110010110** [comment]
> > 关闭吧，这个是github官方导致的
> 
> 但是假如把以前编译过的config文件直接拿来用是可以很顺利编译成功

Describes the interrupt condition triggered by the online SSH configuration.

**Comment by Ho-Lay** [comment]
> > 但是假如把以前编译过的config文件直接拿来用是可以很顺利编译成功
> 
> Describes the interrupt condition triggered by the online SSH configuration.

我编译的是小米3G的固件，默认的插件，编译到 make[3] -C toolchain/gcc/initial compile 就提示出错退出了，后来我再编译小米mini固件，也一样是默认的插件，但还是编译到make[3] -C toolchain/gcc/initial compile就自动退出
编译小米3G和mini肯定是通过SSH才能选择的

后来我就把上个月成功编译的config文件拿来用，小米3G和mini都顺利编译完成， 因为是用了config文件预设了xiaomi3G和mini，所以这个这个就没有连SSH

不知道是因为连了SSH才导致编译中断还是小米3G和mini的默认插件加了哪个插件才导致编译中断的

**Comment by Ho-Lay** [comment]
测试确定是github SSH的问题

**Comment by leopardciaw** [comment]
> 测试确定是github SSH的问题

如何解决哈。

**Comment by 110010110** [comment]
> 
> 如何解决哈。
Get '.config' in local configuration, and then upload the '.config' file.

**Comment by LarryLi-cn** [comment]
我也遇到这个问题了, 有解决方吗?
