### ISSUE TITLE
最近我编译成功了，为啥输出只有EFI文件

### ISSUE THREAD

**Issue by Hansen1018** [coolsnowwolf/lede#7866]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最近我编译成功了，为啥输出只有EFI文件，之前有两个文件，其中一个没有EFI。哪里设置不对

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by minlang112** [comment]
现在x86的默认仅输出efi引导的img镜像，需要传统方式引导的请自行配置一下

**Comment by Jason6111** [comment]
make menuconfig- target images-build grub images（勾选）

**Comment by coolsnowwolf** [comment]
EFI 兼容 MBR
