### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by jgsports** [coolsnowwolf/lede#7878]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Error: Process completed with exit code 143.

**Comment by EnnawYang** [comment]
Duplicate invalid issue
