### ISSUE TITLE
两天前更新源码后树莓派4b无法成功编译

### ISSUE THREAD

**Issue by 1uca55haw** [coolsnowwolf/lede#7891]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：两天前更新源码后树莓派4b无法成功编译

### (2) 路由器型号和固件版本

A：树莓派4b

### (3) 详细日志

A：
make[5]: *** [Makefile:1179: vmlinux] Error 1
make[4]: *** [Makefile:34: /workdir/openwrt/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/linux-5.10.64/.modules] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/linux-5.10.64'
make[4]: Leaving directory '/workdir/openwrt/target/linux/bcm27xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#5.83#1.36#7.14
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:18: /workdir/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

Run cd openwrt/bin/targets/*/*
/home/runner/work/_temp/991714a8-5b0f-4829-8e0b-da8d63d4db7d.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory
Error: Process completed with exit code 1.

**Comment by lxl6125** [comment]
升级5.10内核的原因，暂时先用5.4内核吧
编辑
target/linux/bcm27xx/Makefile
5.10改成5.4
