### ISSUE TITLE
DW33D没有5GHz无线

### ISSUE THREAD

**Issue by HiGarfield** [coolsnowwolf/lede#79]
已选择ath10k-firmware-qca988x和kmod-ath10k

出问题的内核日志：
[   14.623653] PCI: Enabling device 0000:00:00.0 (0000 -> 0002)
[   14.629570] ath10k_pci 0000:00:00.0: pci irq legacy oper_irq_mode 1 irq_mode 0 reset_mode 0
[   14.845292] ath10k_pci 0000:00:00.0: Direct firmware load for ath10k/pre-cal-pci-0000:00:00.0.bin failed with error -2
[   14.856171] ath10k_pci 0000:00:00.0: Falling back to user helper
[   74.862088] ath10k_pci 0000:00:00.0: Direct firmware load for ath10k/cal-pci-0000:00:00.0.bin failed with error -2
[   74.872615] ath10k_pci 0000:00:00.0: Falling back to user helper
[  134.999641] ath10k_pci 0000:00:00.0: qca988x hw2.0 target 0x4100016c chip_id 0x043202ff sub 0000:0000
[  135.009043] ath10k_pci 0000:00:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[  135.022080] ath10k_pci 0000:00:00.0: firmware ver 10.2.4-1.0-00029 api 5 features no-p2p,raw-mode,mfp,allows-mesh-bcast crc32 88595bb8
[  135.066989] ath10k_pci 0000:00:00.0: board id is not exist in otp, ignore it
[  135.074249] ath10k_pci 0000:00:00.0: Direct firmware load for ath10k/QCA988X/hw2.0/board-2.bin failed with error -2
[  135.084851] ath10k_pci 0000:00:00.0: Falling back to user helper
[  144.692612] firmware ath10k!QCA988X!hw2.0!board-2.bin: firmware_loading_store: map pages failed
[  144.712582] ath10k_pci 0000:00:00.0: board_file api 1 bmi_id N/A crc32 bebc7c08
[  144.836835] ath10k_pci 0000:00:00.0: otp calibration failed: 2
[  144.842775] ath10k_pci 0000:00:00.0: failed to run otp: -22
[  144.848426] ath10k_pci 0000:00:00.0: could not init core (-22)
[  144.854446] ath10k_pci 0000:00:00.0: could not probe fw (-22)

**Comment by daofeng2015** [comment]
有无线啊。选择ath10k-firmware-qca988x就有5G了

**Comment by HiGarfield** [comment]
现增加问题描述：
1、不添加软件包，编译后，5GHz正常。
2、添加N多软件包，编译成全家桶固件之后，启动奇慢。
3、编译出来的全家桶固件刷机完第一次启动，直接没5GHz，第二次（有时候包含第三次）重启，5GHz无线出来了，但无法正常工作。再次重启，5GHz无线正常，并且后面再重启，5GHz也正常。

我怀疑是全家桶固件启动过慢导致某些脚本没有成功执行。
不过代码我不懂，也只是猜测。

**Comment by HiGarfield** [comment]
补充一些我全家桶固件添加的所有软件包：

root@LEDE:~# opkg list
adbyby - 2.7-20170823
aria2 - 1.32.0-3
ath10k-firmware-qca988x - 2017-03-29-956e2609-1
automount - 1-18
autosamba - 1-8
base-files - 174-r78-287575f
blkid - 2.30.1-2
block-mount - 2017-07-31-8ab4fda6-1
busybox - 1.27.2-1
coreutils - 8.23-3
coreutils-base64 - 8.23-3
coreutils-nohup - 8.23-3
ddns-scripts - 2.7.6-17
default-settings - 1.0-21
dnsmasq-full - 2.76-12
dosfstools - 4.1-1
dropbear - 2017.75-3
e2fsprogs - 1.43.5-1
etherwake - 1.09-4
fdisk - 2.30.1-2
firewall - 2017-05-27-a4d98aea-1
fstools - 2017-07-31-8ab4fda6-1
fwtool - 1
hd-idle - 1.04-2
hdparm - 9.50-1
hostapd-common - 2016-12-19-ad02e79d-4
ip-tiny - 4.11.0-1
ip6tables - 1.6.1-1
ipset - 6.32-2
ipset-lists - 20161112
iptables - 1.6.1-1
iptables-mod-conntrack-extra - 1.6.1-1
iptables-mod-ipopt - 1.6.1-1
iptables-mod-nat-extra - 1.6.1-1
iptables-mod-tproxy - 1.6.1-1
iw - 4.9-1
iwinfo - 2017-08-23-c1a03e82-1
jshn - 2017-06-17-fd57eea9-1
jsonfilter - 2016-07-02-dea067ad-1
kernel - 4.4.88-1-4290d981df12e76445f252412db00f26
kmod-ath - 4.4.88+2017-01-31-3
kmod-ath10k - 4.4.88+2017-01-31-3
kmod-ath9k - 4.4.88+2017-01-31-3
kmod-ath9k-common - 4.4.88+2017-01-31-3
kmod-cfg80211 - 4.4.88+2017-01-31-3
kmod-crypto-aead - 4.4.88-1
kmod-crypto-crc32c - 4.4.88-1
kmod-crypto-ecb - 4.4.88-1
kmod-crypto-hash - 4.4.88-1
kmod-crypto-manager - 4.4.88-1
kmod-crypto-null - 4.4.88-1
kmod-crypto-pcompress - 4.4.88-1
kmod-crypto-sha1 - 4.4.88-1
kmod-fast-classifier - 4.4.88-1
kmod-fs-exfat - 4.4.88+2017-01-03-8d291f525ce6d88fe0d8b11b86fd5c2e900401d3-1
kmod-fs-ext4 - 4.4.88-1
kmod-fs-vfat - 4.4.88-1
kmod-fuse - 4.4.88-1
kmod-gpio-button-hotplug - 4.4.88-2
kmod-gre - 4.4.88-1
kmod-ifb - 4.4.88-1
kmod-ip6tables - 4.4.88-1
kmod-ipt-conntrack - 4.4.88-1
kmod-ipt-conntrack-extra - 4.4.88-1
kmod-ipt-core - 4.4.88-1
kmod-ipt-ipopt - 4.4.88-1
kmod-ipt-ipset - 4.4.88-1
kmod-ipt-nat - 4.4.88-1
kmod-ipt-nat-extra - 4.4.88-1
kmod-ipt-tproxy - 4.4.88-1
kmod-iptunnel - 4.4.88-1
kmod-l2tp - 4.4.88-1
kmod-lib-crc-ccitt - 4.4.88-1
kmod-lib-crc16 - 4.4.88-1
kmod-lib-textsearch - 4.4.88-1
kmod-mac80211 - 4.4.88+2017-01-31-3
kmod-macvlan - 4.4.88-1
kmod-mppe - 4.4.88-1
kmod-nf-conntrack - 4.4.88-1
kmod-nf-conntrack6 - 4.4.88-1
kmod-nf-ipt - 4.4.88-1
kmod-nf-ipt6 - 4.4.88-1
kmod-nf-nat - 4.4.88-1
kmod-nf-nathelper - 4.4.88-1
kmod-nf-nathelper-extra - 4.4.88-1
kmod-nfnetlink - 4.4.88-1
kmod-nls-base - 4.4.88-1
kmod-nls-cp437 - 4.4.88-1
kmod-nls-iso8859-1 - 4.4.88-1
kmod-nls-utf8 - 4.4.88-1
kmod-ppp - 4.4.88-1
kmod-pppoe - 4.4.88-1
kmod-pppol2tp - 4.4.88-1
kmod-pppox - 4.4.88-1
kmod-sched-cake - 4.4.88+2017-01-28-9789742c-1
kmod-sched-core - 4.4.88-1
kmod-scsi-core - 4.4.88-1
kmod-shortcut-fe - 4.4.88-1
kmod-slhc - 4.4.88-1
kmod-tun - 4.4.88-1
kmod-udptunnel4 - 4.4.88-1
kmod-udptunnel6 - 4.4.88-1
kmod-usb-core - 4.4.88-1
kmod-usb-ehci - 4.4.88-1
kmod-usb-ledtrig-usbport - 4.4.88-1
kmod-usb-printer - 4.4.88-1
kmod-usb-storage - 4.4.88-1
kmod-usb-storage-extras - 4.4.88-1
kmod-usb2 - 4.4.88-1
lede-keyring - 2017-01-20-a50b7529-1
libblkid - 2.30.1-2
libblobmsg-json - 2017-06-17-fd57eea9-1
libc - 1.1.16-1
libcurl - 7.54.1-1
libevent2 - 2.0.22-1
libext2fs - 1.43.5-1
libfdisk - 2.30.1-2
libgcc - 5.4.0-1
libgcrypt - 1.6.6-1
libgpg-error - 1.12-1
libip4tc - 1.6.1-1
libip6tc - 1.6.1-1
libipset - 6.32-2
libiwinfo - 2017-08-23-c1a03e82-1
libiwinfo-lua - 2017-08-23-c1a03e82-1
libjson-c - 0.12.1-1
libjson-script - 2017-06-17-fd57eea9-1
liblua - 5.1.5-1
liblzo - 2.10-1
libmbedtls - 2.6.0-1
libmnl - 1.0.4-1
libncurses - 6.0-1
libnl-tiny - 0.1-5
libopenssl - 1.0.2l-1
libpcre - 8.41-2
libpthread - 1.1.16-1
librt - 1.1.16-1
libsmartcols - 2.30.1-2
libstdcpp - 5.4.0-1
libubox - 2017-06-17-fd57eea9-1
libubus - 2017-02-18-34c6e818-1
libubus-lua - 2017-02-18-34c6e818-1
libuci - 2017-04-12-c4df32b3-1
libuci-lua - 2017-04-12-c4df32b3-1
libuclient - 2017-09-06-24d6eded-1
libuuid - 2.30.1-2
libxtables - 1.6.1-1
logd - 2017-09-01-b1bc8d5f-1
lua - 5.1.5-1
luci - git-17.266.45847-e3459ff-1
luci-app-adbyby-plus - 2.0-19
luci-app-aliddns - 1.0-1
luci-app-aria2 - 1.0.1-2
luci-app-autoreboot - 1.0-7
luci-app-ddns - 2.4.8-2
luci-app-filetransfer - git-17.265.12218-287575f-1
luci-app-firewall - git-17.266.45847-e3459ff-1
luci-app-hd-idle - git-17.266.45847-e3459ff-1
luci-app-mwan3 - git-17.266.45847-e3459ff-1
luci-app-n2n_v2 - 1.0-1
luci-app-ngrokc - git-17.265.12218-287575f-1
luci-app-openvpn-server - 2.0-16
luci-app-pptp-server - 2.0-7
luci-app-samba - git-17.266.45847-e3459ff-1
luci-app-sfe - 1.0-3
luci-app-shadowsocksr-pro - 2.0-17
luci-app-sqm - 1.1.3-1
luci-app-syncdial - 2.0-22
luci-app-transmission - git-17.266.45847-e3459ff-1
luci-app-upnp - git-17.266.45847-e3459ff-1
luci-app-usb-printer - 1.0-1
luci-app-vlmcsd - 1.0-2
luci-app-vsftpd - 1.0-2
luci-app-watchcat - git-17.266.45847-e3459ff-1
luci-app-wifischedule - git-17.266.45847-e3459ff-1
luci-app-wol - git-17.266.45847-e3459ff-1
luci-base - git-17.266.45847-e3459ff-1
luci-i18n-adbyby-plus-zh-cn - 2.0-19
luci-i18n-aliddns-zh-cn - 1.0-1
luci-i18n-aria2-zh-cn - 1.0.1-2
luci-i18n-autoreboot-zh-cn - 1.0-7
luci-i18n-base-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-ddns-zh-cn - 2.4.8-2
luci-i18n-filetransfer-zh-cn - git-17.265.12218-287575f-1
luci-i18n-firewall-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-hd-idle-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-mwan3-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-n2n_v2-zh-cn - 1.0-1
luci-i18n-ngrokc-zh-cn - git-17.265.12218-287575f-1
luci-i18n-openvpn-server-zh-cn - 2.0-16
luci-i18n-pptp-server-zh-cn - 2.0-7
luci-i18n-samba-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-sfe-zh-cn - 1.0-3
luci-i18n-shadowsocksr-pro-zh-cn - 2.0-17
luci-i18n-transmission-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-upnp-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-usb-printer-zh-cn - 1.0-1
luci-i18n-vlmcsd-zh-cn - 1.0-2
luci-i18n-vsftpd-zh-cn - 1.0-2
luci-i18n-watchcat-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-wifischedule-zh-cn - git-17.266.45847-e3459ff-1
luci-i18n-wol-zh-cn - git-17.266.45847-e3459ff-1
luci-lib-fs - 1.0-1
luci-lib-ip - git-17.266.45847-e3459ff-1
luci-lib-jsonc - git-17.266.45847-e3459ff-1
luci-lib-nixio - git-17.266.45847-e3459ff-1
luci-mod-admin-full - git-17.266.45847-e3459ff-1
luci-proto-ipv6 - git-17.266.45847-e3459ff-1
luci-proto-ppp - git-17.266.45847-e3459ff-1
luci-theme-bootstrap - git-17.266.45847-e3459ff-1
luci-theme-freifunk-generic - git-17.266.45847-e3459ff-1
luci-theme-material - git-17.266.45847-e3459ff-1
miniupnpd - 2.0.20170421-2
mtd - 21
mwan3 - 2.6.6-1
n2n_v2 - 9349-1
netifd - 2017-08-27-7d94ede3-1
ngrokc - 7b645b1-1
ntfs-3g - 2017.3.23-1-fuseint
ntfs-3g-utils - 2017.3.23-1-fuseint
odhcp6c - 2017-09-05-51733a6d-4
odhcpd - 2017-08-16-94e65ee0-1
openssl-util - 1.0.2l-1
openvpn-easy-rsa - 3.0.1-1
openvpn-openssl - 2.4.3-1
opkg - 2017-07-28-4bd8601e-1
p910nd - 0.97-5
pdnsd-alt - 1.2.9a-par-a8e46ccba7b0fa2230d6c42ab6dcd92926f6c21d
ppp - 2.4.7-12
ppp-mod-pppoe - 2.4.7-12
ppp-mod-pppol2tp - 2.4.7-12
pptpd - 1.4.0-3
procd - 2017-08-22-54b46a35-1
resolveip - 2
rpcd - 2016-12-03-0577cfc1-1
rpcd-mod-rrdns - 20170710
samba36-server - 3.6.25-8
shadowsocksr-libev-alt - 2.5.1-1
shellsync - 0.2-1
sqm-scripts - 1.1.3-1
swconfig - 11
tc - 4.11.0-1
terminfo - 6.0-1
transmission-daemon-mbedtls - 2.92+git-4
transmission-web - 2.92+git-4
ubi-utils - 1.5.2-1
uboot-envtools - 2015.10-1
ubox - 2017-09-01-b1bc8d5f-1
ubus - 2017-02-18-34c6e818-1
ubusd - 2017-02-18-34c6e818-1
uci - 2017-04-12-c4df32b3-1
uclient-fetch - 2017-09-06-24d6eded-1
uhttpd - 2016-10-25-1628fa4b-2
uhttpd-mod-ubus - 2016-10-25-1628fa4b-2
usign - 2015-07-04-ef641914-1
vlmcsd - svn1111-1
vsftpd-alt - 3.0.3-5
watchcat - 1-6
webui-aria2 - 2017-05-21-d1ce5b99-1
wget - 1.18-2
wifischedule - 1-2
wpad-mini - 2016-12-19-ad02e79d-4
xl2tpd - devel-20151125-3
yaaw - 2017-04-11-1
zlib - 1.2.11-1

**Comment by coolsnowwolf** [comment]
这个嘛。。。等我买到 DW33D 再看看了

**Comment by HiGarfield** [comment]
第一次启动，/etc/config/wireless 压根就没5GHz。多重启几遍才有。有了之后就没事了。以后不会丢了。
