### ISSUE TITLE
redmi ax3000 路由器适配咨询

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#7904]
Hi team,

最近入手了 redmi ax3000 的路由器设备，我根据编译的教程没找到对应的设备型号
请问，我们这边有支持这个的计划吗，或者，我想自己来做适配，有对应参考的教程不？

BR
Robin

**Comment by S0SL** [comment]
https://openwrt.org/zh/docs/guide-developer/adding_new_device

**Comment by coolsnowwolf** [comment]
目前无支持计划，上游内核尚未完善

**Comment by Guxing0321** [comment]
hi， team,

收到，感谢大佬们的回复，我这边关注下，谢谢

BR
Robin
