### ISSUE TITLE
x86  linux 内核增加emmc后编译异常

### ISSUE THREAD

**Issue by WYC-2020** [coolsnowwolf/lede#7915]
初步怀疑是增加了这个emmc后有的选项没有配置好，导致在编译linux内核的时候不能自动化编译，出现要设置各个选项后进行编译
![image](https://user-images.githubusercontent.com/34025388/134622858-e2cc0c4b-dc96-46d3-8ca1-3ede4cd3dade.png)

**Comment by wx611975** [comment]
增加了这个 选项都不知道该怎么选了 我都默认回车的不知道影不影响

**Comment by qd201211** [comment]
同问题

**Comment by suizhenmin** [comment]
同样问题，不知道要怎么选择
