### ISSUE TITLE
x86 linux 内核增加emmc后编译异常

### ISSUE THREAD

**Issue by qd201211** [coolsnowwolf/lede#7917]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：接 [#7915](https://github.com/coolsnowwolf/lede/issues/7915)，还是会有两个选项需要手动选择。

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：这两个选项分别是
![屏幕截图 2021-09-24 201950](https://user-images.githubusercontent.com/55730160/134673478-b7a7c77d-cf35-4420-8b31-758a1e240726.png)和
![屏幕截图 2021-09-24 202000](https://user-images.githubusercontent.com/55730160/134673489-38cabf5f-140c-4d38-bb9e-6d6e48e2bfbe.png)

望解决下

**Comment by WYC-2020** [comment]
是的我刚也试了一下 确实还没有加完，已经@大佬了 坐等大佬修复
