### ISSUE TITLE
X86 编译发现默认未设置选项

### ISSUE THREAD

**Issue by suizhenmin** [coolsnowwolf/lede#7920]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A
<img width="583" alt="屏幕截图 2021-09-24 224910" src="https://user-images.githubusercontent.com/2957364/134695119-87067cdb-8243-40ce-bc61-e85c16e555fc.png">
：

**Comment by WYC-2020** [comment]
可以关闭了 已经修复了

**Comment by suizhenmin** [comment]
刚修复的么，我同步的下午4点多的编译

**Comment by WYC-2020** [comment]
@suizhenmin 看提交记录

**Comment by WYC-2020** [comment]
或者已有的issue已经关闭了

**Comment by suizhenmin** [comment]
之前有一个issue是提到这个，但我刚编译的时候之前提交的已经修复了
