### ISSUE TITLE
TP C2600 210923版本不停重启

### ISSUE THREAD

**Issue by hzjnet** [coolsnowwolf/lede#7927]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
源码版本：
commit 368e31dc7c5022f98abd2bcf2a0eedc0f1fc37bb (HEAD -> master, origin/master, origin/HEAD)

### (1) 具体问题

A：不停的反复重启,同样R7800刷后也不正常

### (2) 路由器型号和固件版本

A：硬件是：TP C2600 ipq8064 RAM 512M SPI 32M

### (3) 详细日志
A:
U-Boot 2012.07 [Standard IPQ806X.LN,unknown] (Dec 16 2015 - 15:12:29)

smem ram ptable found: ver: 0 len: 5
DRAM:  491 MiB
PCI0 Link Intialized
PCI1 Link Intialized
SF: Detected MX25U25635F with page size 4 KiB, total 32 MiB
  00:01.0     - 17cb:0101 - Bridge device
   01:00.0    - 168c:0040 - Network controller
  02:01.0     - 17cb:0101 - Bridge device
   03:00.0    - 168c:0040 - Network controller
NAND:  ipq_nand: unknown NAND device manufacturer: 0 device: 0
ipq_nand: failed to identify device
SF: Detected MX25U25635F with page size 4 KiB, total 32 MiB
ipq_spi: page_size: 0x100, sector_size: 0x1000, size: 0x2000000
32 MiB
MMC:   
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   MAC1 addr:0:3:7f:ba:db:1
athrs17_reg_init: complete
athrs17_vlan_config ...done
S17c init  done
MAC2 addr:0:3:7f:ba:db:2
eth0, eth1
boot in 2 seconds
FirmwareRecovery: Now doing bootipq
MMC Device 0 not found
MMC Device 0 not found

Loading from nand1, offset 0x1f0000
   Image Name:   ARM OpenWrt Linux-5.4.145
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2947619 Bytes = 2.8 MiB
   Load Address: 42208000
   Entry Point:  42208000
Automatic boot of image at addr 0x44000000 ...
   Image Name:   ARM OpenWrt Linux-5.4.145
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2947619 Bytes = 2.8 MiB
   Load Address: 42208000
   Entry Point:  42208000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OK
info: "mtdparts" not set
Using machid 0x1260 from environment

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.145 (hzjnet@bgsub18ip18) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r3729-368e31dc7)) #0 SMP Thu Sep 23 14:22:07 2021
[    0.000000] CPU: ARMv7 Processor [512f04d0] revision 0 (ARMv7), cr=10c5787d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, PIPT instruction cache
[    0.000000] OF: fdt: Machine model: TP-Link Archer C2600
-------
[    0.063528] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.063560] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.063801] NET: Registered protocol family 1
[    0.063849] PCI: CLS 0 bytes, default 64
[    0.065187] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.072258] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.072276] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.110059] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.111933] qcom-pcie 1b500000.pci: 1b500000.pci supply vdda not found, using dummy regulator
[    0.112079] qcom-pcie 1b500000.pci: 1b500000.pci supply vdda_phy not found, using dummy regulator
[    0.112189] qcom-pcie 1b500000.pci: 1b500000.pci supply vdda_refclk not found, using dummy regulator
[    0.112460] qcom-pcie 1b500000.pci: host bridge /soc/pci@1b500000 ranges:
[    0.112533] qcom-pcie 1b500000.pci:    IO 0x0fe00000..0x0fefffff -> 0x0fe00000
[    0.112572] qcom-pcie 1b500000.pci:   MEM 0x08000000..0x0fdfffff -> 0x08000000
[    0.334437] qcom-pcie 1b500000.pci: Link up
[    0.334619] qcom-pcie 1b500000.pci: PCI host bridge to bus 0000:00
[    0.334642] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.334663] pci_bus 0000:00: root bus resource [io  0x0000-0xfffff] (bus address [0xfe00000-0xfefffff])
[    0.334678] pci_bus 0000:00: root bus resource [mem 0x08000000-0x0fdfffff]
[    0.334743] pci 0000:00:00.0: [17cb:0101] type 01 class 0xff0000
[    0.334920] pci 0000:00:00.0: supports D1
[    0.334936] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    0.339516] PCI: bus0: Fast back to back transfers disabled
[    0.339855] pci 0000:01:00.0: [168c:0040] type 00 class 0x028000
[    0.340212] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    0.341362] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    0.346046] PCI: bus1: Fast back to back transfers disabled
[    0.346135] pci 0000:00:00.0: BAR 8: assigned [mem 0x08000000-0x081fffff]
[    0.346159] pci 0000:01:00.0: BAR 0: assigned [mem 0x08000000-0x081fffff 64bit]
[    0.346287] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    0.346312] pci 0000:00:00.0:   bridge window [mem 0x08000000-0x081fffff]
[    0.347060] pcieport 0000:00:00.0: AER: enabled with IRQ 39
[    0.347628] qcom-pcie 1b700000.pci: 1b700000.pci supply vdda not found, using dummy regulator
[    0.347753] qcom-pcie 1b700000.pci: 1b700000.pci supply vdda_phy not found, using dummy regulator
[    0.347891] qcom-pcie 1b700000.pci: 1b700000.pci supply vdda_refclk not found, using dummy regulator
[    0.348154] qcom-pcie 1b700000.pci: host bridge /soc/pci@1b700000 ranges:
[    0.348219] qcom-pcie 1b700000.pci:    IO 0x31e00000..0x31efffff -> 0x31e00000
[    0.348255] qcom-pcie 1b700000.pci:   MEM 0x2e000000..0x31dfffff -> 0x2e000000
[    0.576109] qcom-pcie 1b700000.pci: Link up
[    0.576265] qcom-pcie 1b700000.pci: PCI host bridge to bus 0001:00
[    0.576286] pci_bus 0001:00: root bus resource [bus 00-ff]
[    0.576301] pci_bus 0001:00: root bus resource [mem 0x2e000000-0x31dfffff]
[    0.576358] pci 0001:00:00.0: [17cb:0101] type 01 class 0xff0000
[    0.576511] pci 0001:00:00.0: supports D1
[    0.576528] pci 0001:00:00.0: PME# supported from D0 D1 D3hot
[    0.581026] PCI: bus0: Fast back to back transfers disabled
[    0.581360] pci 0001:01:00.0: [168c:0040] type 00 class 0x028000
[    0.581740] pci 0001:01:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    0.582981] pci 0001:01:00.0: PME# supported from D0 D3hot D3cold
[    0.583285] pci 0001:01:00.0: 2.000 Gb/s available PCIe bandwidth, limited by 2.5 GT/s x1 link at 0001:00:00.0 (capable of 4.000 Gb/s with 5 GT/s x1 link)
[    0.587721] PCI: bus1: Fast back to back transfers disabled
[    0.587798] pci 0001:00:00.0: BAR 8: assigned [mem 0x2e000000-0x2e1fffff]
[    0.587822] pci 0001:01:00.0: BAR 0: assigned [mem 0x2e000000-0x2e1fffff 64bit]
[    0.587954] pci 0001:00:00.0: PCI bridge to [bus 01-ff]
[    0.587974] pci 0001:00:00.0:   bridge window [mem 0x2e000000-0x2e1fffff]
[    0.588792] pcieport 0001:00:00.0: AER: enabled with IRQ 41
[    0.591586] L2 @ QSB rate. Forcing new rate.
[    0.591816] L2 @ 384000 KHz
[    0.592004] CPU0 @ 800000 KHz
[    0.592017] CPU1 @ QSB rate. Forcing new rate.
[    0.592150] CPU1 @ 384000 KHz
[    0.595969] gsbi 16300000.gsbi: GSBI port protocol: 6 crci: 0
[    0.597375] gsbi 1a200000.gsbi: GSBI port protocol: 3 crci: 0
[    0.599268] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.600134] msm_serial 16340000.serial: msm_serial: detected port #0
[    0.600189] msm_serial 16340000.serial: uartclk = 7372800
[    0.600260] 16340000.serial: ttyMSM0 at MMIO 0x16340000 (irq = 42, base_baud = 460800) is a MSM
[    0.600296] msm_serial: console setup on port #0
[    1.399208] printk: console [ttyMSM0] enabled
[    1.404179] msm_serial: driver initialized
[    1.413556] loop: module loaded
[    1.414817] spi_qup 1a280000.spi: IN:block:16, fifo:64, OUT:block:16, fifo:64
[    1.417021] spi-nor spi0.0: mx25u25635f (32768 Kbytes)
[    1.423192] 25 fixed-partitions partitions found on MTD device spi0.0
[    1.427835] Creating 25 MTD partitions on "spi0.0":
[    1.434431] 0x000000000000-0x000000020000 : "SBL1"
[    1.439512] 0x000000020000-0x000000040000 : "MIBIB"
[    1.444208] 0x000000040000-0x000000060000 : "SBL2"
[    1.448973] 0x000000060000-0x000000090000 : "SBL3"
[    1.453929] 0x000000090000-0x0000000a0000 : "DDRCONFIG"
[    1.458615] 0x0000000a0000-0x0000000b0000 : "SSD"
[    1.463828] 0x0000000b0000-0x0000000e0000 : "TZ"
[    1.468606] 0x0000000e0000-0x000000100000 : "RPM"
[    1.473381] 0x000000100000-0x000000170000 : "fs-uboot"
[    1.477888] 0x000000170000-0x0000001b0000 : "uboot-env"
[    1.483003] 0x0000001b0000-0x0000001f0000 : "radio"
[    1.488046] 0x0000001f0000-0x0000005f0000 : "os-image"
[    1.493006] 0x0000005f0000-0x000001ef0000 : "rootfs"
[    1.498100] mtd: device 12 (rootfs) set to be root filesystem
[    1.503207] 1 squashfs-split partitions found on MTD device rootfs
[    1.508568] 0x000001e50000-0x000001ef0000 : "rootfs_data"
[    1.515017] 0x000001ef0000-0x000001ef0200 : "default-mac"
[    1.520486] 0x000001ef0200-0x000001ef0400 : "pin"
[    1.525796] 0x000001ef0400-0x000001f00000 : "product-info"
[    1.530578] 0x000001f00000-0x000001f10000 : "partition-table"
[    1.535875] 0x000001f10000-0x000001f20000 : "soft-version"
[    1.541753] 0x000001f20000-0x000001f30000 : "support-list"
[    1.547067] 0x000001f30000-0x000001f40000 : "profile"
[    1.552639] 0x000001f40000-0x000001f50000 : "default-config"
[    1.557664] 0x000001f50000-0x000001f90000 : "user-config"
[    1.563484] 0x000001f90000-0x000001fd0000 : "qos-db"
[    1.568679] 0x000001fd0000-0x000001fe0000 : "usb-config"
[    1.573804] 0x000001fe0000-0x000002000000 : "log"
[    1.580395] libphy: ipq8064_mdio_bus: probed
[    1.598426] switch0: Atheros AR8337 rev. 2 switch registered on 37000000.mdio-mii
[    2.425458] ar8327: qca,phy-rgmii-en is not specified
[    2.426053] libphy: Fixed MDIO Bus: probed
[    2.430145] i2c /dev entries driver
[    2.436463] cpuidle: enable-method property 'qcom,kpss-acc-v1' found operations
[    2.437064] cpuidle: enable-method property 'qcom,kpss-acc-v1' found operations
[    2.444943] sdhci: Secure Digital Host Controller Interface driver
[    2.451534] sdhci: Copyright(c) Pierre Ossman
[    2.457697] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.464612] NET: Registered protocol family 10
[    2.469188] Segment Routing with IPv6
[    2.472199] NET: Registered protocol family 17
[    2.475944] Bridge firewalling registered
[    2.481646] l2tp_core: L2TP core driver, V2.0
[    2.484260] l2tp_netlink: L2TP netlink interface
[    2.488648] 8021q: 802.1Q VLAN Support v1.8
[    2.493419] Registering SWP/SWPB emulation handler
[    2.520472] qcom_rpm 108000.rpm: RPM firmware 3.0.16777342
[    2.536762] s1a: Bringing 0uV into 1050000-1050000uV
[    2.537030] s1a: supplied by regulator-dummy
[    2.541044] s1b: Bringing 0uV into 1050000-1050000uV
[    2.545249] s1b: supplied by regulator-dummy
[    2.550204] s2a: Bringing 0uV into 800000-800000uV
[    2.554455] s2a: supplied by regulator-dummy
[    2.558985] s2b: Bringing 0uV into 800000-800000uV
[    2.563474] s2b: supplied by regulator-dummy
[      2.581278] /dev/root: Can't open blockdev
[    2.581303] VFS: Cannot open root device "(null)" or unknown-block(31,12): error -6
[    2.584258] Please append a correct "root=" boot option; here are the available partitions:
[    2.591923] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(31,12)
[    2.600230] CPU1: stopping
[    2.608836] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 5.4.145 #0
[    2.611348] Hardware name: Generic DT based system
[    2.617539] [<c030f954>] (unwind_backtrace) from [<c030b968>] (show_stack+0x14/0x20)
[    2.622138] [<c030b968>] (show_stack) from [<c090e4d8>] (dump_stack+0x94/0xa8)
[    2.630030] [<c090e4d8>] (dump_stack) from [<c030eb80>] (handle_IPI+0x184/0x1b8)
[    2.637071] [<c030eb80>] (handle_IPI) from [<c05dff24>] (gic_handle_irq+0xb4/0xb8)
[    2.644616] [<c05dff24>] (gic_handle_irq) from [<c0301a8c>] (__irq_svc+0x6c/0x90)
[    2.651977] Exception stack(0xdd46bf18 to 0xdd46bf60)
[    2.659534] bf00:                                                       00000000 00000000
[    2.664596] bf20: 1d05d000 ddb9ea80 dd7edc00 00000001 ddb9de30 00000000 00000000 00000000
[    2.672757] bf40: 9afc05e0 99bbf820 00000015 dd46bf68 c0734548 c073454c 80000013 ffffffff
[    2.680912] [<c0301a8c>] (__irq_svc) from [<c073454c>] (cpuidle_enter_state+0x94/0x498)
[    2.689062] [<c073454c>] (cpuidle_enter_state) from [<c0734994>] (cpuidle_enter+0x30/0x4c)
[    2.696872] [<c0734994>] (cpuidle_enter) from [<c034ad84>] (do_idle+0x1d8/0x240)
[    2.705199] [<c034ad84>] (do_idle) from [<c034b094>] (cpu_startup_entry+0x1c/0x20)
[    2.712749] [<c034b094>] (cpu_startup_entry) from [<423024cc>] (0x423024cc)
[    2.720127] Rebooting in 1 seconds.

B：对比前期正常的内核配置：
diff ipq806x/config-5.4.ok target/linux/ipq806x/config-5.4 
33d32
< CONFIG_ARM_CRYPTO=y
104,118d102
< CONFIG_CRYPTO_AES_ARM=y
< CONFIG_CRYPTO_AES_ARM_BS=y
< CONFIG_CRYPTO_ARCH_HAVE_LIB_CHACHA=y
< CONFIG_CRYPTO_ARCH_HAVE_LIB_CURVE25519=y
< CONFIG_CRYPTO_ARCH_HAVE_LIB_POLY1305=y
< CONFIG_CRYPTO_CBC=y
< CONFIG_CRYPTO_CHACHA20=y
< CONFIG_CRYPTO_CHACHA20POLY1305=y
< CONFIG_CRYPTO_CHACHA20_NEON=y
< CONFIG_CRYPTO_CRC32=y
< CONFIG_CRYPTO_CRC32C=y
< CONFIG_CRYPTO_CRC32_ARM_CE=y
< CONFIG_CRYPTO_CRYPTD=y
< CONFIG_CRYPTO_CTR=y
< CONFIG_CRYPTO_CURVE25519_NEON=y
120d103
< CONFIG_CRYPTO_DEV_QCE=y
125,129d107
< CONFIG_CRYPTO_ECB=y
< CONFIG_CRYPTO_GCM=y
< CONFIG_CRYPTO_GF128MUL=y
< CONFIG_CRYPTO_GHASH=y
< CONFIG_CRYPTO_GHASH_ARM_CE=y
136,142d113
< CONFIG_CRYPTO_LIB_CHACHA=y
< CONFIG_CRYPTO_LIB_CHACHA20POLY1305=y
< CONFIG_CRYPTO_LIB_CHACHA_GENERIC=y
< CONFIG_CRYPTO_LIB_CURVE25519_GENERIC=y
< CONFIG_CRYPTO_LIB_DES=y
< CONFIG_CRYPTO_LIB_POLY1305=y
< CONFIG_CRYPTO_LIB_POLY1305_GENERIC=y
147,149d117
< CONFIG_CRYPTO_NHPOLY1305=y
< CONFIG_CRYPTO_NHPOLY1305_NEON=y
< CONFIG_CRYPTO_NULL=y
151,152d118
< CONFIG_CRYPTO_POLY1305=y
< CONFIG_CRYPTO_POLY1305_ARM=y
155,159d120
< CONFIG_CRYPTO_RNG_DEFAULT=y
< CONFIG_CRYPTO_SEQIV=y
< CONFIG_CRYPTO_SHA1=y
< CONFIG_CRYPTO_SHA1_ARM=y
< CONFIG_CRYPTO_SHA1_ARM_NEON=y
161,164d121
< CONFIG_CRYPTO_SHA256_ARM=y
< CONFIG_CRYPTO_SHA512_ARM=y
< CONFIG_CRYPTO_SIMD=y
< CONFIG_CRYPTO_XTS=y
209d165
< CONFIG_GLOB=y
292a249,250
> # CONFIG_MTD_BLOCK is not set
> # CONFIG_MTD_BLOCK_RO is not set
406c364
< CONFIG_QCOM_SCM_DOWNLOAD_MODE_DEFAULT=y
---
> # CONFIG_QCOM_SCM_DOWNLOAD_MODE_DEFAULT is not set
409c367
< CONFIG_QCOM_SOCINFO=y
---
> # CONFIG_QCOM_SOCINFO is not set
454d411
< CONFIG_SOC_BUS=y

经过对比发现：新配置主要起了3个：1 THUMBEE 2 ARM_CRYPTO 3MTD block

核心问题是：
[      2.612145] /dev/root: Can't open blockdev
[    2.612172] VFS: Cannot open root device "(null)" or unknown-block(31,12): error -6
[    2.615127] Please append a correct "root=" boot option; here are the available partitions:
[    2.622809] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(31,12)

编译配置文件中有该选项
cat .config|grep blockdev
CONFIG_PACKAGE_blockdev=y

**Comment by 1582130940** [comment]
把这个commit revert掉再试试
https://github.com/coolsnowwolf/lede/commit/56e6c4b8660f6aa5709e6a2efe941c848e47de1a

**Comment by hzjnet** [comment]
确实如此，R7800和C2600都正常了 谢谢
