### ISSUE TITLE
kcptun 不能使用

### ISSUE THREAD

**Issue by yhj39300** [coolsnowwolf/lede#793]
![qq 20181111133006](https://user-images.githubusercontent.com/22695307/48309485-4ccb4a80-e5b6-11e8-9e30-890ed9f2737d.png)
开了kcptun ip111,cn 可以看见已翻墙，但google youtube 都无法访问

**Comment by yhj39300** [comment]
> ![qq 20181111133006](https://user-images.githubusercontent.com/22695307/48309485-4ccb4a80-e5b6-11e8-9e30-890ed9f2737d.png)
> 开了kcptun ip111,cn 可以看见已翻墙，但google youtube 都无法访问

**Comment by hcym** [comment]
v2里面的mkcp可以，感觉不如官方标准配置
