### ISSUE TITLE
ZTE MF269 活动连接数只有8192

### ISSUE THREAD

**Issue by xfmly** [coolsnowwolf/lede#7950]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
ZTE MF269 活动连接数只有8192，查看了设置文件，数值已经是65535

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：ZTE MF269
       内核：5.10.64

(3) 详细日志

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.10.64 (runner@fv-az275-655) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 8.4.0 r3744-ecab8d5e1) 8.4.0, GNU ld (GNU Binutils) 2.34) #0 SMP Mon Sep 27 14:36:28 2021
[    0.000000] Machine model: ZTE MF269
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000040ffffff]
[    0.000000]   node   0: [mem 0x0000000041000000-0x000000004a5fffff]
[    0.000000]   node   0: [mem 0x000000004a600000-0x000000004e7fffff]
[    0.000000]   node   0: [mem 0x000000004e800000-0x00000000504fffff]
[    0.000000]   node   0: [mem 0x0000000050500000-0x00000000506fffff]
[    0.000000]   node   0: [mem 0x0000000050700000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] On node 0 totalpages: 131072
[    0.000000]   DMA zone: 2048 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 131072 pages, LIFO batch:31
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 20 pages/cpu s41112 r8192 d32616 u81920
[    0.000000] pcpu-alloc: s41112 r8192 d32616 u81920 alloc=20*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Kernel command line: console=ttyMSM0,115200n8 ubi.mtd=rootfs root=mtd:ubi_rootfs rootfstype=squashfs rootwait root=/dev/ubiblock0_1
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 416268K/524288K available (7294K kernel code, 838K rwdata, 1872K rodata, 1280K init, 301K bss, 108020K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	CONFIG_RCU_FANOUT set to non-default value of 32.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] random: get_random_bytes called from start_kernel+0x350/0x570 with crng_init=0
[    0.000000] arch_timer: cp15 and mmio timer(s) running at 19.20MHz (virt/virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000005] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000155] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=76800)
[    0.000171] pid_max: default: 32768 minimum: 301
[    0.000298] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000310] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.001725] rcu: Hierarchical SRCU implementation.
[    0.001871] dyndbg: Ignore empty _ddebug table in a CONFIG_DYNAMIC_DEBUG_CORE build
[    0.002323] smp: Bringing up secondary CPUs ...
[    0.002863] Detected VIPT I-cache on CPU1
[    0.002932] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.003497] Detected VIPT I-cache on CPU2
[    0.003539] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.004142] Detected VIPT I-cache on CPU3
[    0.004181] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.004255] smp: Brought up 1 node, 4 CPUs
[    0.004268] SMP: Total of 4 processors activated.
[    0.004277] CPU features: detected: 32-bit EL0 Support
[    0.004285] CPU features: detected: CRC32 instructions
[    0.004339] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.004348] CPU: All CPU(s) started at EL1
[    0.004370] alternatives: patching kernel code
[    0.011974] KASLR disabled due to lack of seed
[    0.012122] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.012147] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.012303] pinctrl core: initialized pinctrl subsystem
[    0.013385] NET: Registered protocol family 16
[    0.013883] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    0.013922] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.013959] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.014532] thermal_sys: Registered thermal governor 'step_wise'
[    0.016192] cpuidle: using governor ladder
[    0.016444] NET: Registered protocol family 42
[    0.016634] ASID allocator initialised with 65536 entries
[    0.057035] usbcore: registered new interface driver usbfs
[    0.057098] usbcore: registered new interface driver hub
[    0.057157] usbcore: registered new device driver usb
[    0.057420] qcom_scm: convention: smc arm 64
[    0.058791] clocksource: Switched to clocksource arch_sys_counter
[    0.059775] NET: Registered protocol family 2
[    0.059893] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.060460] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.060482] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.060533] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.060610] TCP: Hash tables configured (established 4096 bind 4096)
[    0.060696] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.060722] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.060876] NET: Registered protocol family 1
[    0.060905] PCI: CLS 0 bytes, default 64
[    0.062145] workingset: timestamp_bits=46 max_order=17 bucket_order=0
[    0.065846] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.065860] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.067356] qcom-qmp-phy 78000.phy: supply vdda-phy not found, using dummy regulator
[    0.067509] qcom-qmp-phy 78000.phy: supply vdda-pll not found, using dummy regulator
[    0.067898] qcom-qmp-phy 78000.phy: Registered Qcom-QMP phy
[    0.068535] qcom-qusb2-phy 79000.phy: supply vdda-pll not found, using dummy regulator
[    0.068653] qcom-qusb2-phy 79000.phy: supply vdda-phy-dpdm not found, using dummy regulator
[    0.068822] qcom-qusb2-phy 79000.phy: Registered Qcom-QUSB2 phy
[    0.069971] bam-dma-engine 704000.dma: num-channels unspecified in dt
[    0.069985] bam-dma-engine 704000.dma: num-ees unspecified in dt
[    0.075361] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.075971] msm_serial 78b3000.serial: msm_serial: detected port #0
[    0.076009] msm_serial 78b3000.serial: uartclk = 3686400
[    0.076059] 78b3000.serial: ttyMSM0 at MMIO 0x78b3000 (irq = 22, base_baud = 230400) is a MSM
[    0.076084] msm_serial: console setup on port #0
[    0.720420] printk: console [ttyMSM0] enabled
[    0.725581] msm_serial: driver initialized
[    0.733705] loop: module loaded
[    0.734926] nand: device found, Manufacturer ID: 0xc2, Chip ID: 0xaa
[    0.736376] nand: Macronix MX30UF2G18AC
[    0.742987] nand: 256 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.746539] Block protection check failed
[    0.754457] 30 qcomsmem partitions found on MTD device qcom_nand.0
[    0.758267] Creating 30 MTD partitions on "qcom_nand.0":
[    0.764350] 0x000000000000-0x0000000a0000 : "0:sbl1"
[    0.770705] 0x0000000a0000-0x0000000c0000 : "0:mibib"
[    0.775241] 0x0000000c0000-0x000000100000 : "0:bootconfig"
[    0.780267] 0x000000100000-0x000000140000 : "0:bootconfig1"
[    0.785645] 0x000000140000-0x000000440000 : "0:qsee"
[    0.793129] 0x000000440000-0x000000740000 : "0:qsee_1"
[    0.798312] 0x000000740000-0x000000760000 : "0:devcfg"
[    0.801224] 0x000000760000-0x000000780000 : "0:devcfg_1"
[    0.806299] 0x000000780000-0x0000007a0000 : "0:apdp"
[    0.811801] 0x0000007a0000-0x0000007c0000 : "0:apdp_1"
[    0.816727] 0x0000007c0000-0x000000840000 : "0:rpm"
[    0.821946] 0x000000840000-0x0000008c0000 : "0:rpm_1"
[    0.826715] 0x0000008c0000-0x0000008e0000 : "0:cdt"
[    0.831678] 0x0000008e0000-0x000000900000 : "0:cdt_1"
[    0.836352] 0x000000900000-0x000000920000 : "0:appsblenv"
[    0.841565] 0x000000920000-0x000000aa0000 : "0:appsbl"
[    0.847936] 0x000000aa0000-0x000000c20000 : "0:appsbl_1"
[    0.852947] 0x000000c20000-0x000000ca0000 : "0:art"
[    0.857699] 0x000000ca0000-0x000000da0000 : "0:ethphyfw"
[    0.862679] 0x000000000000-0x0000000a0000 : "fota-flag"
[    0.867965] 0x0000000a0000-0x000000120000 : "mac"
[    0.872819] 0x000000120000-0x000001520000 : "cfg-param"
[    0.877563] random: fast init done
[    0.896032] 0x000001520000-0x000001b20000 : "log"
[    0.900768] 0x000001b20000-0x000001bc0000 : "oops"
[    0.901608] 0x000001bc0000-0x0000023c0000 : "web"
[    0.910587] 0x0000023c0000-0x0000057c0000 : "rootfs"
[    0.948175] mtd: device 25 (rootfs) set to be root filesystem
[    0.948450] mtdsplit: no squashfs found in "rootfs"
[    0.952920] 0x0000057c0000-0x000005fc0000 : "0:wififw"
[    0.963714] 0x000005fc0000-0x0000078c0000 : "openwrt_data"
[    0.982006] 0x0000078c0000-0x0000096c0000 : "data"
[    1.003925] 0x0000096c0000-0x00000f9c0000 : "fota"
[    1.084638] spi_qup 78b5000.spi: IN:block:16, fifo:64, OUT:block:16, fifo:64
[    1.085469] spi-nor spi0.0: en25s64 (8192 Kbytes)
[    1.091044] 19 fixed-partitions partitions found on MTD device spi0.0
[    1.095399] Creating 19 MTD partitions on "spi0.0":
[    1.101784] 0x000000000000-0x000000050000 : "0:SBL1"
[    1.107009] 0x000000050000-0x000000060000 : "0:MIBIB"
[    1.112094] 0x000000060000-0x000000080000 : "0:BOOTCONFIG"
[    1.117033] 0x000000080000-0x0000000a0000 : "0:BOOTCONFIG1"
[    1.122446] 0x0000000a0000-0x000000220000 : "0:QSEE"
[    1.127882] 0x000000220000-0x0000003a0000 : "0:QSEE_1"
[    1.133131] 0x0000003a0000-0x0000003b0000 : "0:DEVCFG"
[    1.138071] 0x0000003b0000-0x0000003c0000 : "0:DEVCFG_1"
[    1.143170] 0x0000003c0000-0x0000003d0000 : "0:APDP"
[    1.148643] 0x0000003d0000-0x0000003e0000 : "0:APDP_1"
[    1.153619] 0x0000003e0000-0x000000420000 : "0:RPM"
[    1.158531] 0x000000420000-0x000000460000 : "0:RPM_1"
[    1.163329] 0x000000460000-0x000000470000 : "0:CDT"
[    1.168504] 0x000000470000-0x000000480000 : "0:CDT_1"
[    1.173186] 0x000000480000-0x000000490000 : "0:APPSBLENV"
[    1.178395] 0x000000490000-0x000000550000 : "0:APPSBL"
[    1.183812] 0x000000550000-0x000000610000 : "0:APPSBL_1"
[    1.188852] 0x000000610000-0x000000650000 : "0:ART"
[    1.194293] 0x000000650000-0x0000006d0000 : "0:ETHPHYFW"
[    1.205129] spmi spmi-0: PMIC arbiter version v2 (0x20010000)
[    1.205987] pmd9655_s3: supplied by e-smps1-reg
[    1.210179] pmd9655_s4: supplied by e-smps1-reg
[    1.214608] pmd9655_ldo11: supplied by e-smps1-reg
[    1.219633] libphy: Fixed MDIO Bus: probed
[    1.224251] libphy: ipq4019_mdio: probed
[    1.229306] i2c /dev entries driver
[    1.235788] cpufreq: cpufreq_online: CPU0: Running at unlisted initial frequency: 800000 KHz, changing to: 1017600 KHz
[    1.236651] sdhci: Secure Digital Host Controller Interface driver
[    1.245755] sdhci: Copyright(c) Pierre Ossman
[    1.251875] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.258542] remoteproc remoteproc0: cd00000.q6v5_wcss is available
[    1.262841] NET: Registered protocol family 10
[    1.268585] Segment Routing with IPv6
[    1.272503] NET: Registered protocol family 17
[    1.276215] Bridge firewalling registered
[    1.280516] 8021q: 802.1Q VLAN Support v1.8
[    1.295892] ubi0: attaching mtd25
[    1.512319] ubi0: scanning is finished
[    1.518109] ubi0: attached mtd25 (name "rootfs", size 52 MiB)
[    1.518138] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    1.522858] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    1.529610] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    1.536468] ubi0: good PEBs: 416, bad PEBs: 0, corrupted PEBs: 0
[    1.543236] ubi0: user volume: 3, internal volumes: 1, max. volumes count: 128
[    1.549489] ubi0: max/mean erase counter: 4/2, WL threshold: 4096, image sequence number: 1629559814
[    1.556524] ubi0: available PEBs: 0, total reserved PEBs: 416, PEBs reserved for bad PEB handling: 40
[    1.565821] ubi0: background thread "ubi_bgt0d" started, PID 839
[    1.566556] block ubiblock0_1: created from ubi0:1(rootfs)
[    1.585768] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    1.586394] Freeing unused kernel memory: 1280K
[    1.614974] Run /sbin/init as init process
[    1.614992]   with arguments:
[    1.614996]     /sbin/init
[    1.614998]   with environment:
[    1.615001]     HOME=/
[    1.615004]     TERM=linux
[    2.041697] init: Console is alive
[    2.041810] init: - watchdog -
[    2.173473] random: crng init done
[    2.862848] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    2.984975] ANTFS Module: Version 07.19-b41ba529
[    2.997854] genirq: irq_chip msmgpio did not update eff. affinity mask of irq 105
[    3.001400] SCSI subsystem initialized
[    3.013446] usbcore: registered new interface driver usb-storage
[    3.014342] usbcore: registered new interface driver uas
[    3.018722] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.033423] init: - preinit -
[    8.033738] mount_root: loading kmods from internal overlay
[    8.044130] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[    8.046470] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[    9.815241] block: attempting to load /etc/config/fstab
[    9.816307] block: unable to load configuration (fstab: Entry not found)
[    9.819308] block: no usable configuration
[    9.833621] UBIFS (ubi0:2): default file-system created
[    9.834082] UBIFS (ubi0:2): Mounting in unauthenticated mode
[    9.837736] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 969
[    9.883971] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs_data"
[    9.884004] UBIFS (ubi0:2): LEB size: 126976 bytes (124 KiB), min./max. I/O unit sizes: 2048 bytes/2048 bytes
[    9.890796] UBIFS (ubi0:2): FS size: 7618560 bytes (7 MiB, 60 LEBs), journal size 1015809 bytes (0 MiB, 6 LEBs)
[    9.900683] UBIFS (ubi0:2): reserved for root: 359843 bytes (351 KiB)
[    9.910572] UBIFS (ubi0:2): media format: w5/r0 (latest is w5/r0), UUID 60501F23-B02F-4C46-B77B-F2DD2027A2B1, small LPT model
[   11.297877] block: attempting to load /etc/config/fstab
[   11.297963] block: unable to load configuration (fstab: Entry not found)
[   11.302096] block: no usable configuration
[   11.309948] mount_root: overlay filesystem has not been fully initialized yet
[   11.313064] mount_root: switching to ubifs overlay
[   11.324483] overlayfs: "xino" feature enabled using 2 upper inode bits.
[   11.326099] urandom-seed: Seed file not found (/etc/urandom.seed)
[   11.464163] procd: - early -
[   11.464218] procd: - watchdog -
[   12.104513] procd: - watchdog -
[   12.105377] procd: - ubus -
[   12.263183] procd: - init -
[   12.508245] kmodloader: loading kernel modules from /etc/modules.d/*
[   12.547228] NET: Registered protocol family 38
[   12.644004] ssdk_switch_device_num_init[1159]:INFO:ess-switch dts node number: 1
[   12.644108] ssdk_dt_get_switch_node[970]:INFO:ess-switch DT exist!
[   12.650521] ssdk_dt_parse_access_mode[856]:INFO:switch_access_mode: local bus
[   12.656480] ssdk_dt_parse_access_mode[869]:INFO:switchreg_base_addr: 0x3a000000
[   12.663687] ssdk_dt_parse_access_mode[870]:INFO:switchreg_size: 0x1000000
[   12.670798] ssdk_dt_parse_mac_mode[295]:INFO:mac mode = 0x0
[   12.677737] ssdk_dt_parse_mac_mode[304]:INFO:mac mode1 = 0xf
[   12.683150] ssdk_dt_parse_mac_mode[313]:INFO:mac mode2 = 0xf
[   12.689042] ssdk_dt_parse_phy_info[659]:INFO:[PORT 5] port_mac_sel = QGMAC_PORT
[   12.694689] ssdk_dt_parse_phy_info[659]:INFO:[PORT 6] port_mac_sel = QGMAC_PORT
[   12.701837] ssdk_dt_parse_uniphy[332]:INFO:ess-uniphy DT exist!
[   12.709576] ssdk_plat_init start
[   12.763881] ssdk_gcc_clock_init[1033]:INFO:SSDK gcc clock init successfully!
[   12.764845] HPPE initializing...
[   12.770471] ssdk_phy_driver_init[328]:INFO:dev_id = 0, phy_adress = 0, phy_id = 0xffffffff phytype doesn't match
[   12.773609] ssdk_phy_driver_init[328]:INFO:dev_id = 0, phy_adress = 1, phy_id = 0xffffffff phytype doesn't match
[   12.783793] ssdk_phy_driver_init[328]:INFO:dev_id = 0, phy_adress = 2, phy_id = 0xffffffff phytype doesn't match
[   12.793928] ssdk_phy_driver_init[328]:INFO:dev_id = 0, phy_adress = 3, phy_id = 0xffffffff phytype doesn't match
[   12.804427] qca808x_phy_api_ops_init[2208]:INFO:qca probe qca808x phy driver succeeded!
[   12.833596] regi_init[3567]:INFO:Initializing HPPE!!
[   13.050808] ssdk_ppe_reset_init[1265]:INFO:ppe reset successfully!
[   13.054059] qca_hppe_tdm_hw_init[684]:INFO:tdm setup num=96
[   13.056204] qca_hppe_portctrl_hw_init[110]:INFO:Hawkeye PPE port initializing
[   15.477845] ssdk_switch_register[1718]:INFO:Chip version 0x1500
[   15.477880] qca_link_polling_select[1315]:INFO:link-polling-required node does not exist
[   15.482583] ssdk_switch_register[1744]:INFO:polling is selected
[   15.490907] regi_init[3571]:INFO:Initializing HPPE Done!!
[   15.496610] regi_init[3631]:INFO:qca-ssdk module init succeeded!
[   15.506841] EDMA ver 1 hw init
[   15.508389] EDMA HW Reset completed succesfully
[   15.511073] Num rings - TxDesc:1 (23-23) TxCmpl:1 (7-7)
[   15.515475] RxDesc:1 (15-15) RxFill:1 (7-7)
[   15.520996] GMAC5(ffffff80024218c0) Invalid MAC@ - using da:e9:e3:8d:34:5c
[   15.729652] GMAC6(ffffff8004b968c0) Invalid MAC@ - using 8a:d8:1f:5f:a5:f5
[   15.934488] **********************************************************
[   15.934521] * NSS Data Plane driver
[   15.939926] **********************************************************
[   15.971032] qca-nss 39000000.nss: Direct firmware load for qca-nss0.bin failed with error -2
[   15.971070] qca-nss 39000000.nss: Falling back to sysfs fallback for: qca-nss0.bin
[   16.092887] nss_driver - fw of size 776324  bytes copied to load addr: 40000000, nss_id : 0
[   16.095047] Supported Frequencies - 
[   16.095056] 187.2 MHz 
[   16.100095] 748.8 MHz 
[   16.103875] 1.4976 GHz 
[   16.106029] 
[   16.110817] ffffffc008b4d680: set sdma ffffff8003fed100
[   16.112572] ffffffc008b4d680: meminfo init succeed
[   16.136626] qca-nss 39400000.nss: Direct firmware load for qca-nss1.bin failed with error -2
[   16.136665] qca-nss 39400000.nss: Falling back to sysfs fallback for: qca-nss1.bin
[   16.153639] node size 2 # items 4
[   16.153673] memory: 40000000 536870912 (avl 441593856) items 4 active_cores 2
[   16.155990] addr/size storage words 2 2 # words 4 in DTS, ddr size 1000000
[   16.163086] ffffffc008b4d680: nss core 0 booted successfully
[   16.325498] nss_driver - fw of size 291560  bytes copied to load addr: 40800000, nss_id : 1
[   16.326461] Supported Frequencies - 
[   16.326468] 187.2 MHz 
[   16.332696] 748.8 MHz 
[   16.336482] 1.4976 GHz 
[   16.338638] 
[   16.343419] ffffffc008b54ec0: set sdma ffffff8003fed600
[   16.345142] ffffffc008b54ec0: meminfo init succeed
[   16.350189] debugfs: Directory 'dynamic_if' with parent 'stats' already present!
[   16.354895] debugfs: File 'n2h' in directory 'strings' already present!
[   16.362438] debugfs: File 'drv' in directory 'strings' already present!
[   16.372722] node size 2 # items 4
[   16.375373] memory: 40000000 536870912 (avl 441827328) items 4 active_cores 2
[   16.378856] addr/size storage words 2 2 # words 4 in DTS, ddr size 1000000
[   16.385970] ffffffc008b54ec0: nss core 1 booted successfully
[   16.504247] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[   16.540966] cryptodev: driver 1.11 loaded.
[   16.543635] PPP generic driver version 2.4.2
[   16.544787] NET: Registered protocol family 24
[   16.552031] Loading modules backported from Linux version v5.10.42-0-g65859eca4dff
[   16.552637] Backport generated by backports.git v5.10.42-1-0-gbee5c545
[   16.590064] PPP MPPE Compression module registered
[   16.592144] usbcore: registered new interface driver ums-alauda
[   16.594596] usbcore: registered new interface driver ums-cypress
[   16.600867] usbcore: registered new interface driver ums-datafab
[   16.606905] usbcore: registered new interface driver ums-freecom
[   16.612792] usbcore: registered new interface driver ums-isd200
[   16.618788] usbcore: registered new interface driver ums-jumpshot
[   16.624359] usbcore: registered new interface driver ums-karma
[   16.630889] usbcore: registered new interface driver ums-sddr09
[   16.636430] usbcore: registered new interface driver ums-sddr55
[   16.642324] usbcore: registered new interface driver ums-usbat
[   16.657811] xt_time: kernel timezone is -0000
[   16.692657] remoteproc remoteproc0: powering up cd00000.q6v5_wcss
[   16.749503] remoteproc remoteproc0: Booting fw image IPQ8074/q6_fw.mdt, size 668
[   17.869199] remoteproc remoteproc0: remote processor cd00000.q6v5_wcss is now up
[   17.871766] ath11k c000000.wifi: qmi ignore invalid mem req type 3
[   17.871848] kmodloader: done loading kernel modules from /etc/modules.d/*
[   17.881819] ath11k c000000.wifi: chip_id 0x0 chip_family 0x0 board_id 0x292 soc_id 0xffffffff
[   17.888556] ath11k c000000.wifi: fw_version 0x250684a5 fw_build_timestamp 2021-07-13 10:57 fw_build_id QC_IMAGE_VERSION_STRING=WLAN.HK.2.5.0.1-01100-QCAHKSWPL_SILICONZ-1
[   17.897049] ath11k c000000.wifi: joba-1 patch V2: ATH11K_QUEUE_LEN=2048
[   18.244059] ieee80211 phy0: copying sband (band 1) due to VHT EXT NSS BW flag
[   18.244926] wlan0: Created a NSS virtual interface.
[   18.244957] wlan0: RX-Q and tasklet initialized.
[   18.250185] debugfs: File 'virt_if' in directory 'stats' already present!
[   18.253678] wlan1: Created a NSS virtual interface.
[   18.260162] wlan1: RX-Q and tasklet initialized.
[   31.710806] pmd9655_ldo11: disabling
[   43.581409] ECM init
[   43.581470] ECM database jhash random seed: 0x965b9400
[   43.583798] ECM init complete
[   44.816976] br-lan: port 1(eth0) entered blocking state
[   44.817011] br-lan: port 1(eth0) entered disabled state
[   44.821353] device eth0 entered promiscuous mode
[   45.163173] wlan0: Destroyed NSS virtual interface
[   45.163205] wlan0: RX-Q purged.
[   45.219275] wlan1: Destroyed NSS virtual interface
[   45.219311] wlan1: RX-Q purged.
[   45.428547] debugfs: File 'virt_if' in directory 'stats' already present!
[   45.428702] wlan0: Created a NSS virtual interface.
[   45.434403] wlan0: RX-Q and tasklet initialized.
[   45.464172] debugfs: File 'virt_if' in directory 'stats' already present!
[   45.464327] wlan1: Created a NSS virtual interface.
[   45.470188] wlan1: RX-Q and tasklet initialized.
[   45.476082] br-lan: port 2(wlan0) entered blocking state
[   45.479642] br-lan: port 2(wlan0) entered disabled state
[   45.485380] device wlan0 entered promiscuous mode
[   45.490373] br-lan: port 2(wlan0) entered blocking state
[   45.494785] br-lan: port 2(wlan0) entered forwarding state
[   45.500568] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   45.517977] br-lan: port 3(wlan1) entered blocking state
[   45.518014] br-lan: port 3(wlan1) entered disabled state
[   45.522733] device wlan1 entered promiscuous mode
[   45.527843] br-lan: port 3(wlan1) entered blocking state
[   45.532296] br-lan: port 3(wlan1) entered forwarding state
[   45.664050] br-lan: port 2(wlan0) entered disabled state
[   45.664384] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   51.190343] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   51.190544] br-lan: port 2(wlan0) entered blocking state
[   51.195792] br-lan: port 2(wlan0) entered forwarding state
[   55.409524] device wlan0 left promiscuous mode
[   55.409635] br-lan: port 2(wlan0) entered disabled state
[   55.490101] device wlan1 left promiscuous mode
[   55.490223] br-lan: port 3(wlan1) entered disabled state
[   55.735145] wlan0: Destroyed NSS virtual interface
[   55.735178] wlan0: RX-Q purged.
[   55.787132] wlan1: Destroyed NSS virtual interface
[   55.787166] wlan1: RX-Q purged.
[   56.039723] debugfs: File 'virt_if' in directory 'stats' already present!
[   56.039895] wlan0: Created a NSS virtual interface.
[   56.045679] wlan0: RX-Q and tasklet initialized.
[   56.054257] debugfs: File 'virt_if' in directory 'stats' already present!
[   56.055297] wlan1: Created a NSS virtual interface.
[   56.061854] wlan1: RX-Q and tasklet initialized.
[   56.089403] br-lan: port 2(wlan0) entered blocking state
[   56.089436] br-lan: port 2(wlan0) entered disabled state
[   56.094305] device wlan0 entered promiscuous mode
[   56.099306] br-lan: port 2(wlan0) entered blocking state
[   56.103740] br-lan: port 2(wlan0) entered forwarding state
[   56.128166] br-lan: port 3(wlan1) entered blocking state
[   56.128204] br-lan: port 3(wlan1) entered disabled state
[   56.132911] device wlan1 entered promiscuous mode
[   56.138101] br-lan: port 3(wlan1) entered blocking state
[   56.142503] br-lan: port 3(wlan1) entered forwarding state
[   56.156278] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[   56.445190] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

**Comment by Boos4721** [comment]
https://github.com/coolsnowwolf/lede/blob/0088bb160151d065d184224c9659711e9e133afa/package/qca/nss/qca-nss-ecm-64/Makefile#L50

**Comment by xfmly** [comment]
已经解决，感谢大佬解答。
