### ISSUE TITLE
添加netspeedtest后打开出错

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#7958]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
点开后页面就是下面这样
### (1) 具体问题
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/network/netspeedtest'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/netspeedtest.lua:15: ')' expected near 'translate'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
A：

### (2) 路由器型号和固件版本
软路由
A：

### (3) 详细日志

A：

**Comment by Jason6111** [comment]
一样 求解

**Comment by WYC-2020** [comment]
我重新修改了makefile 没遇到这个问题
![image](https://user-images.githubusercontent.com/34025388/135217768-db298350-ca38-41e3-a1de-565fb1a04312.png)
