### ISSUE TITLE
luci-app-netspeedtest问题

### ISSUE THREAD

**Issue by lxwq** [coolsnowwolf/lede#7959]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：luci-app-netspeedtest

### (2) 路由器型号和固件版本

A：x64

### (3) 详细日志

A：/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/network/netspeedtest'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/netspeedtest.lua:15: ')' expected near 'translate'
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
虚拟机在无外网的情况下测试,打开网页后出现这个错误,正常吗?

**Comment by smallprogram** [comment]
+1

**Comment by WYC-2020** [comment]
我这边没遇到哈哈，不过这程序界面是真丑
![image](https://user-images.githubusercontent.com/34025388/135218137-77adefb9-df44-4df2-a8b5-fee995551755.png)
都不是实时出数据，然人看起来非常不舒服，只有停止服务或者测试完毕了才会出结果
