### ISSUE TITLE
REDME AX6路由器 IPV6中继模式问题

### ISSUE THREAD

**Issue by gtcar2020** [coolsnowwolf/lede#7961]
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/7251756/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/7251757/default.txt)
型号:红米AX6路由器
使用状态:作为二级路由器使用，上级为移动光猫路由一体机，光猫路由一体机拨号，修改/etc/config/dhcp文件,增加以下内容:
config dhcp 'wan6'
        option interface 'wan'
        option ra 'relay'
        option dhcpv6 'relay'
        option ndp 'relay'
        option master '1'
AX6下级设备可以获得ipv6地址，但是AX6路由器会不断自动重启。日志文件如下：

**Comment by Rhystar** [comment]
试试取消编译nss，目前nss-ecm-64和ipv6冲突

**Comment by 1582130940** [comment]
取消编译NSS-ECM，或路由器拨号，目前应该是DHCP模式下IPQ807x无法正常使用IPV6
参考：https://github.com/coolsnowwolf/lede/issues/7811

**Comment by doney0318** [comment]
这个问题我也有，我现在就是因为要用到 ipv6 所以一直没敢用 NSS ，期待大佬早日可以解决这个问题
