### ISSUE TITLE
5.10内核无法拨号

### ISSUE THREAD

**Issue by Luastonsu** [coolsnowwolf/lede#7973]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
红米AC2100路由器，编译testing内核，版本5.10
输入账号密码后拨号，没有任何反应，一直连不通，且没有任何错误信息
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by XiaoliChan** [comment]
No log, no issue.

**Comment by Luastonsu** [comment]
> No log, no issue.

I have looked through the kernel log and system log for this problem. There is no information about this problem.

**Comment by Luastonsu** [comment]
> No log, no issue.

However, I can provide a screenshot of the error at that time
![image](https://user-images.githubusercontent.com/70949583/135700331-6950c857-9b1a-48ea-8220-3a328e2083e0.png)

**Comment by XiaoliChan** [comment]
> However, I can provide a screenshot of the error at that time ![image](https://user-images.githubusercontent.com/70949583/135700331-6950c857-9b1a-48ea-8220-3a328e2083e0.png)

Well, I have no idea what going on :) .

**Comment by AmadeusGhost** [comment]
没有精力支持 5.10，而且 5.10 上默认少了一部分有线驱动。

**Comment by Luastonsu** [comment]
> 没有精力支持 5.10，而且 5.10 上默认少了一部分有线驱动。

所以说5.10内核就抛弃非x86用户了么？

**Comment by AmadeusGhost** [comment]
> 所以说5.10内核就抛弃非x86用户了么？

并没有抛弃，有这个精力可以选择自行修复

**Comment by Luastonsu** [comment]
> > 所以说5.10内核就抛弃非x86用户了么？
> 
> 并没有抛弃，有精力的可以选择自行修复

那还是用着5.4内核养老算了。
