### ISSUE TITLE
最新编译，更新完密码总是会恢复到password

### ISSUE THREAD

**Issue by xeyesen** [coolsnowwolf/lede#7979]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：最新的编译，升级完密码变成默认password，有一些设置也变回默认了

### (2) 路由器型号和固件版本

A：x86软路由，R21.10.1

### (3) 详细日志

A：无

**Comment by smallprogram** [comment]
已经不掉了。昨天晚上feeds更了，有点问题，现在已经修复了

**Comment by cym422948** [comment]
我比你更奇怪 同一个root密码 更新后LUCI界面输入是错误的 SSH下就是正确的 后来谷歌半天才找到办法进去

**Comment by XinSSS** [comment]
我也遇到了这个问题。。。升级后密码被重置了

**Comment by jeasonliang** [comment]
> 我也遇到了这个问题。。。升级后密码被重置了

我也遇到过~！小米4a千兆版的~~！

**Comment by xeyesen** [comment]
升级的时候不要勾选保存配置，更新好后很多东西都要重新设置，后面升级勾选保存配置的情况下，就都正常了，没有出现配置丢失的问题了

**Comment by XinSSS** [comment]
@xeyesen 上次5.4到5.10不保留配置升级了一次, 5.10后来又降级到了5.4, 也是不保留配置, 平常更新都要不保留配置的话要折腾死人了

**Comment by xeyesen** [comment]
@XinSSS 因为经常要更新，每次更完都要恢复下配置也挺麻烦，长痛不如短痛，哈哈
