### ISSUE TITLE
$$R Plus导致bin文件过大，编译多次确定了

### ISSUE THREAD

**Issue by choushui007** [coolsnowwolf/lede#798]
Lean大，我之前安装包原有默认的加上SSR Pro和$$R Plus，这两天看到你又更新就重新编译。一开始加上了V2ray，但是报错说bin文件过大。我menuconfig去掉V2后，依然报大。我后来编译一次后说是$$R Plus有问题，我就把plus取消了，然后就通过编译了。没有plus的前提下，固件大小8M。后来我加上了V2ray，刚好16M。 现在plus代码最终生成的二进制代码应该是超过7M的。能否复检一下？

**Comment by coolsnowwolf** [comment]
rm .confg
