### ISSUE TITLE
RAC2V1K的QSDK驱动在端口转发有bug，不知道其他806x 807x的cpu会不会这样

### ISSUE THREAD

**Issue by 82kg** [coolsnowwolf/lede#7983]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

路由型号：RAC2V1K，Askey RT4230W REV6
固件版本：OpenWrt R21.10.1 / LuCI Master (git-21.273.48290-ff4b0f6)

### （2021-10-04号发现：只在有线连接会这样，无线则不会，猜测是qsdk驱动导致）
最近编译的两版RAC2V1K的固件，带QCA-NSS-ECM-SFE，没编译docker，插件就一个ssr+  和一些常用的

现象是：端口转发里的 NAT环回 功能， 对于转发到本路由的是有效的，转发到内网其他ip的端口时，不生效。

打个比方：路由ip是 192.168.2.1 把80端口映射到外网8088端口，在内网环境使用ddns的域名去访问8088 是可以的

把内网的 192.168.2.2 的80端口映射到外网 8888,端口，nat环回就失效了，无法在内网使用域名去访问。只能用内网ip访问。

![QQ截图20211003210802](https://user-images.githubusercontent.com/31686230/135754987-752fc9f5-e802-4f90-8e7e-a8cb3e0622b5.png)

就如图中，4022,端口，可以在内网用域名访问。5001就不不行。。。

**Comment by Ailick** [comment]
QCA-NSS-ECM-SFE其实目前并不会使用sfe加速，也就是说你勾选SFE FOR ECM与否，并不会导致结果有什么不同，你可以试试不选择sfe编译。
SFE FOR ECM目前还有一些别的问题需要解决，这原因比较复杂，简而言之你遇到的问题与SFE无关。

**Comment by Ailick** [comment]
> > QCA-NSS-ECM-SFE其实目前并不会使用sfe加速，也就是说你勾选SFE FOR ECM与否，并不会导致结果有什么不同，你可以试试不选择sfe编译。 SFE FOR ECM目前还有一些别的问题需要解决，这原因比较复杂，简而言之你遇到的问题与SFE无关。
> 
> lean说旧版没这问题。我晚上回去试试 不勾选 ecm，用旧版的试试。 ![QQ截图20211008153635](https://user-images.githubusercontent.com/31686230/136521462-fa6d9e18-2f96-4fb1-b59b-845cf7603109.png)

有nss的设备可以不用勾选sfe，另外新版sfe也不存在端口转发问题，因为我自己的设备正常运行，你需要担心的是你的防火墙而不是这些转发加速的驱动。
目前806x和807x遇到的问题与sfe-cm无关，sfe for ecm使用的是sfe-drv驱动，并且此驱动目前尚未生效。
