### ISSUE TITLE
求助！编译的AX3600固件，NAT 回环有问题！

### ISSUE THREAD

**Issue by JohyC** [coolsnowwolf/lede#7999]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

路由型号：AX3600
固件版本：OpenWrt R21.10.1 / LuCI Master (git-21.273.48290-ff4b0f6)

### (1) 具体问题

**编译的ax3600固件，nat回环转发不成功！**

ax3600基于lede仓库源码编译的；没有编译docker；

局域网环境中，无法使用ddns后的域名。ssh不能连，web不能访问。
使用手机流量访问就没问题。ssh，web都能成功使用。

ax3600 自己的地址转发出去，能够直接访问！
![image](https://user-images.githubusercontent.com/38210128/135999923-6ad58bcf-0f04-48f6-8c27-5edbc31703b6.png)
路由的LAN口地址为10.0.0.1，端口转发LAN口地址出去，访问不受影响！

nmap扫描发现，所有地址状态都为 **filtered** ！
![image](https://user-images.githubusercontent.com/38210128/136004607-4fa45e70-6bf6-4a1f-bfb4-d45dfad9cfff.png)

bridge防火墙配置没问题！
![image](https://user-images.githubusercontent.com/38210128/135999263-feb6a7bb-0aac-4f77-8084-d7bb017fe110.png)

求助各位大佬！帮忙看看哪里出错了！希望能解决掉nat回环的毛病！

**Comment by zcluo** [comment]
同样问题

**Comment by JohyC** [comment]
> 同样问题

被困扰住了！！！
