### ISSUE TITLE
automount  FAT32 中文乱码

### ISSUE THREAD

**Issue by HiGarfield** [coolsnowwolf/lede#80]
automount  FAT32 中文乱码

**Comment by tomerilery** [comment]
编译的时候自己选上这个包kmod-nls-cp936  防止fat32中文乱码

**Comment by HiGarfield** [comment]
是自动挂载脚本没有指定utf8

**Comment by coolsnowwolf** [comment]
kmod-nls-cp936 可以解决

**Comment by q158073378252010** [comment]
@HiGarfield 请问你是如何解决的？

**Comment by nimasi** [comment]
勾选了cp936也没有用

**Comment by ferre-han** [comment]
设置自动挂载中文
make kernel_menuconfig
File systems --->
Native Language Support --->
(utf8) Default NLS Option ///此括号内为根据自己需要修改 必须改,网络共享默认中文
<> Simplified Chinese charset (CP936, GB2312) 可以不用改,默认 <> NLS ISO 8859-1 (Latin 1; Western European Languages) 可以不用改,默认
<*> NLS UTF-8 可以不用改,默认
DOS/FAT/NT Filesystems --->
(437) Default codepage for FAT ///此括号内为根据自己需要修改
(utf8) Default iocharset for FAT ///此括号内为根据自己需要修改 必须改,USB默认中文
