### ISSUE TITLE
可否为ss添加simple-obfs混淆插件支持？

### ISSUE THREAD

**Issue by scllen** [coolsnowwolf/lede#800]
[https://github.com/shadowsocks/simple-obfs](https://github.com/shadowsocks/simple-obfs)
相比停更的ssr个人感觉ss是更优的选择

**Comment by hcym** [comment]
真的没必要，v2作者说的明明白白。什么伪装混淆的，越复杂越容易出叉叉，wireguard就是一个内核转发，又快又稳资源占用还极低。

**Comment by hcym** [comment]
一直都是基本设置，流量不大，两个瓦工一个vultr同时跑v2和ssr还有wireguard，也还好

**Comment by lunksana** [comment]
> 真的没必要，v2作者说的明明白白。什么伪装混淆的，越复杂越容易出叉叉，wireguard就是一个内核转发，又快又稳资源占用还极低。

wireguard特征明显，好日子估计不多了

**Comment by tufu9441** [comment]
@heistrock 我跟你一样，用的机场也是这个方式，虽然小众但是即使非常时期都很稳。现在裸ss肯定是不行的，而且ssr如果姿势不对的话，也是常常刚搭出来就会被干掉。
