### ISSUE TITLE
在拉取源码，进行updata，日志会提示没有找到文件或目录

### ISSUE THREAD

**Issue by forever2019** [coolsnowwolf/lede#8000]
在拉取源码，进行updata时，日志会提示没有找到文件或目录

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
在运行 ./scripts/feeds update -a 之后，日志提示的

猜测或许是他们的问题
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git

![QQ截图20211005212044](https://user-images.githubusercontent.com/49540243/136031114-ecf3f7e7-3c92-4374-871e-42a57cdc9af5.jpg)

### (2) 路由器型号和固件版本

A：D2550 x86-64

**Comment by ZoldanYao** [comment]
应该是源的问题，我用的是以下的源，可以正常update和install
src-git packages https://github.com/coolsnowwolf/packages
src-git luci https://github.com/coolsnowwolf/luci
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git small https://github.com/kenzok8/small
src-git kenzo https://github.com/kenzok8/openwrt-packages

**Comment by tuzhq** [comment]
遇到同样问题：
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
fatal: unable to access 'https://git.openwrt.org/feed/routing.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
failed.
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
fatal: unable to access 'https://git.openwrt.org/feed/telephony.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
failed.

**Comment by Luastonsu** [comment]
同 还以为是自己网络环境问题

**Comment by Her0R0cket** [comment]
更新下编译系统的软件包,可能ca证书包要更新了

**Comment by DanielChen008** [comment]
sudo apt update
sudo apt upgrade
更新一下即可
