### ISSUE TITLE
最新版本ax6编译报错

### ISSUE THREAD

**Issue by idelame** [coolsnowwolf/lede#8005]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
ZFM269有同样错误提交。
### (1) 具体问题
编译报错
### (2) 路由器型号和固件版本
A：RedMi AX6
### (3) 详细日志
A：Applying /home/im/lede/target/linux/ipq807x/patches-5.10/117-PCI-qcom-add-support-for-IPQ60xx-PCIe-controller.patch using plaintext:
patching file drivers/pci/controller/dwc/pcie-designware.h
patching file drivers/pci/controller/dwc/pcie-qcom.c

Applying /home/im/lede/target/linux/ipq807x/patches-5.10/118-arm64-dts-ipq8074-Fixup-PCIe-dts-nodes.patch using plaintext:
patching file arch/arm64/boot/dts/qcom/ipq8074.dtsi
Hunk #2 FAILED at 703.
Hunk #4 FAILED at 764.
2 out of 6 hunks FAILED -- saving rejects to file arch/arm64/boot/dts/qcom/ipq8074.dtsi.rej
Patch failed!  Please fix /home/im/lede/target/linux/ipq807x/patches-5.10/118-arm64-dts-ipq8074-Fixup-PCIe-dts-nodes.patch!
make[4]: *** [Makefile:31: /home/im/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.10.70/.prepared_f288ada7bb81887634ac0021f1a7ab61] Error 1
make[4]: Leaving directory '/home/im/lede/target/linux/ipq807x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/im/lede/target/linux'
time: target/linux/compile#8.35#7.76#11.14
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/im/lede'
make[1]: *** [target/Makefile:18: /home/im/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/im/lede'
make: *** [/home/im/lede/include/toplevel.mk:230: world] Error 2

**Comment by Boos4721** [comment]
https://github.com/coolsnowwolf/lede/issues/7998#issuecomment-934272190

**Comment by Laputa0** [comment]
me too

**Comment by WYC-2020** [comment]
明显的打补丁失败了，自己修复一下补丁或者看这个补丁还有必要没，搞定就是了
