### ISSUE TITLE
CR660X 十一编译的依然重启，报错和之前一样

### ISSUE THREAD

**Issue by WowRouter** [coolsnowwolf/lede#8010]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
有类似的，但是新内核还是有问题
## 2. 详细叙述
10月1日编译刷机运行到7号，大约重启了3次，错误日志和7月编译的一样
### (1) 具体问题

A：突然重启

### (2) 路由器型号和固件版本

A：CR660X   R21.10.1 内核5.4.145

### (3) 详细日志

A：Thu Oct  7 13:24:06 2021 daemon.warn odhcpd[2136]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Oct  7 13:27:34 2021 daemon.warn odhcpd[2136]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Oct  7 13:37:22 2021 daemon.warn odhcpd[2136]: A default route is present but there is no public prefix on lan thus we don't announce a default route!
Thu Oct  7 13:37:31 2021 kern.alert kernel: [ 7198.848386] CPU 1 Unable to handle kernel paging request at virtual address 0000003f, epc == 8d7a6144, ra == 8d66b674
Thu Oct  7 13:37:31 2021 kern.warn kernel: [ 7198.859021] Oops[#1]:
                                                                                                                     Thu Oct  7 11:38:47 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
之后就重启了
与上一个ISSUES日志重启报错相同https://github.com/coolsnowwolf/lede/issues/7627
会不会与kmod-shortcut-fe-cm 有关？

**Comment by AmadeusGhost** [comment]
你要接 ttl 把 kern.warn 后面这段的日志也发出来才知道为什么会 kp 重启。

**Comment by hzjixiang** [comment]
> 您这个猜测我象征性的给您打个比方，5分钟前吃的kmod-shortcut-fe-cm，现在窜稀，难道不是几个小时前的问题？sfe这东西真要是有问题，开机都难。 你要觉得有sfe问题，你就不要编译它，自己测试一下。

仅是一个猜测，感觉是这个。  删掉了，正在测，目前运行1天9小时了

**Comment by Ailick** [comment]
> > 您这个猜测我象征性的给您打个比方，5分钟前吃的kmod-shortcut-fe-cm，现在窜稀，难道不是几个小时前的问题？sfe这东西真要是有问题，开机都难。 你要觉得有sfe问题，你就不要编译它，自己测试一下。
> 
> 仅是一个猜测，感觉是这个。 删掉了，正在测，目前运行1天9小时了

我用cm的设备已经运行十多天了，其他人的也没有出现重启的问题。而且这次更新本来就是解决5.x内核随机重启的问题。

**Comment by hzjixiang** [comment]
> > > 您这个猜测我象征性的给您打个比方，5分钟前吃的kmod-shortcut-fe-cm，现在窜稀，难道不是几个小时前的问题？sfe这东西真要是有问题，开机都难。 你要觉得有sfe问题，你就不要编译它，自己测试一下。
> > 
> > 
> > 仅是一个猜测，感觉是这个。 删掉了，正在测，目前运行1天9小时了
> 
> 我用cm的设备已经运行十多天了，其他人的也没有出现重启的问题。而且这次更新本来就是解决5.x内核随机重启的问题。

我测试了多个内核版本，基本确定就是CM导致的，删除后不重启了！

**Comment by llfj** [comment]
> 您这个猜测我象征性的给您打个比方，5分钟前吃的kmod-shortcut-fe-cm，现在窜稀，难道不是几个小时前的问题？sfe这东西真要是有问题，开机都难。 你要觉得有sfe问题，你就不要编译它，自己测试一下。

还真别说我的竞斗云，开启Shortcut-FE 就不定时的当机。不开启能稳定运行。头疼，不开启宽带只能300Mbps ,开启之后是700Mbps。是8月份编译的。我准备重新编译一个看看有没有解决这个问题了。

**Comment by hzjixiang** [comment]
> > 您这个猜测我象征性的给您打个比方，5分钟前吃的kmod-shortcut-fe-cm，现在窜稀，难道不是几个小时前的问题？sfe这东西真要是有问题，开机都难。 你要觉得有sfe问题，你就不要编译它，自己测试一下。
> 
> 还真别说我的竞斗云，开启Shortcut-FE 就不定时的当机。不开启能稳定运行。头疼，不开启宽带只能300Mbps ,开启之后是700Mbps。是8月份编译的。我准备重新编译一个看看有没有解决这个问题了。

刚刚看视频偶然看到有人也提到SFE重启的问题（https://www.youtube.com/watch?v=aCQ5MF4UDrU    评论）
