### ISSUE TITLE
编译到最后出现如下错误

### ISSUE THREAD

**Issue by hillwater98** [coolsnowwolf/lede#8017]
sed -i "s/Installed-Time: .*/Installed-Time: 1633582047/" /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/status
rm -rf /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/boot /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/tmp/* /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/info/*.postinst* /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/usr/lib/opkg/lists/* /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/var/lock/*.lock
find /home/wj/lede/build_dir/target-aarch64_generic_musl/root-rockchip/ -mindepth 1 -execdir touch -hcd "@1633582047" "{}" +
find: The relative path 'Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2020.824.0_x64__79rhkp1fndgsc' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
package/Makefile:66: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 1
make[2]: Leaving directory '/home/wj/lede'
package/Makefile:111: recipe for target '/home/wj/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install' failed
make[1]: *** [/home/wj/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/wj/lede'
/home/wj/lede/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by WYC-2020** [comment]
那就慢慢摸索吧，怀疑path问题那就去掉，或者google一下

**Comment by Suwipe** [comment]
PATH="${PATH/'/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2020.824.0_x64__79rhkp1fndgsc:'/}"

**Comment by xiangfeigao** [comment]
怎么解决的，我也碰到这个问题
