### ISSUE TITLE
小米mini升级丢失所有设置，且最新固件设置无法保存，重启以后设置就会丢失

### ISSUE THREAD

**Issue by xiaopang0v0** [coolsnowwolf/lede#8034]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### 如题，最新固件，界面内更新的，更新时选择了保存设置，但是更新后设置丢失，且已有设置无法导入，更改设置以后，重启路由器就会丢失

A：

### (2) 路由器型号和固件版本

A： 小米路由器mini mt7620

**Comment by Neverends4** [comment]
排除固件太大后……你是不是刷成initramfs-kernel了，这个是载入到内存的，只读，相当于过渡固件
