### ISSUE TITLE
 TP-Link TL-WDR6500 v2  编译出来的固件一直在复位启动不了(日志终于导出来了)

### ISSUE THREAD

**Issue by isLaLa** [coolsnowwolf/lede#8038]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
  不能启动系统
A：

### (2) 路由器型号和固件版本
TP-Link TL-WDR6500 v2
A：

### (3) 详细日志
[20:42:39.189]收←◆Press any key to interrupt autoboot ...     3
[20:42:40.189]收←◆Press any key to interrupt autoboot ...     2
[20:42:41.189]收←◆Press any key to interrupt autoboot ...     1
[20:42:42.189]收←◆Press any key to interrupt autoboot ...     0
[20:42:43.188]收←◆

Trying to boot firmware from 0x9f010200 ...
U-Boot firmware image header detected.
    Image Name:   MIPS OpenWrt Linux-5.4.150
    Data Size:    2080249 Bytes
    Load Address: 80060000
    Entry Point:  80060000
Uncompressing data (LZMA) ... 
[20:42:45.386]收←◆done.
Flushing cache ... done.

Starting kernel at 0x80060000...

[    0.000000] Linux version 5.4.150 (qq@qq-virtual-machine) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r3801-53d63e38a)) #0 Wed Oct 13 09:29:11 2021
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is TP-Link TL-WDR6500 v2
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 122000K/131072K available (4994K kernel code, 184K rwdata, 1140K rodata, 1224K init, 196K bss, 9072K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] random: get_random_bytes called from start_kernel+0x358/0x54c with crng_init=0
[    0.000000] CPU clock: 750.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 5096694524 ns
[    0.000006] sched_clock: 32 bits at 375MHz, resolution 2ns, wraps every 5726622718ns

[20:42:45.685]收←◆[    0.008846] Calibrating delay loop... 373.55 BogoMIPS (lpj=1867776)
[    0.075956] pid_max: default: 32768 minimum: 301
[    0.081326] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.089617] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.102320] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.113528] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.121347] pinctrl core: initialized pinctrl subsystem
[    0.128217] NET: Registered protocol family 16

[20:42:45.778]收←◆[    0.161516] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.175912] clocksource: Switched to clocksource MIPS
[    0.182771] NET: Registered protocol family 2
[    0.187896] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.196666] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.206220] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.214917] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.222937] TCP: Hash tables configured (established 1024 bind 1024)
[    0.230287] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.237752] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.245986] NET: Registered protocol family 1
[    0.250965] PCI: CLS 0 bytes, default 32
[    0.258950] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.272627] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.279300] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.305152] pinctrl-single 1804002c.pinmux: 544 pins, size 68
[    0.312753] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.320650] printk: console [ttyS0] disabled
[    0.325536] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 1562500) is a 16550A
[    0.335369] printk: console [ttyS0] enabled
[    0.335369] printk: console [ttyS0] enabled
[    0.344436] printk: bootconsole [early0] disabled
[    0.344436] printk: bootconsole [early0] disabled
[    0.370538] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.375534] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.382117] Creating 4 MTD partitions on "spi0.0":
[    0.387093] 0x000000000000-0x000000010000 : "u-boot"
[    0.393093] 0x000000010000-0x000000fe0000 : "firmware"
[    0.401208] 0x000000fe0000-0x000000ff0000 : "mib0"
[    0.407070] 0x000000ff0000-0x000001000000 : "art"
[    0.414519] libphy: Fixed MDIO Bus: probed

[20:42:46.393]收←◆[    0.777004] ag71xx 19000000.eth: Could not connect to PHY device. Deferring probe.

[20:42:47.072]收←◆[    1.456282] libphy: ag71xx_mdio: probed
[    1.460961] libphy: ar8xxx-mdio: probed

[20:42:47.109]收←◆[    1.492594] switch0: Atheros AR8229 rev. 1 switch registered on mdio.0

[20:42:47.177]收←◆[    1.561496] ag71xx 1a000000.eth: connected to PHY at fixed-0:00 [uid=00000000, driver=Generic PHY]
[    1.571344] eth0: Atheros AG71xx at 0xba000000, irq 5, mode: gmii
[    1.577887] i2c /dev entries driver
[    1.583757] NET: Registered protocol family 10
[    1.593544] Segment Routing with IPv6
[    1.597478] NET: Registered protocol family 17
[    1.602134] 8021q: 802.1Q VLAN Support v1.8
[    1.607307] PCI host bridge /ahb/pcie-controller@18250000 ranges:
[    1.613623]  MEM 0x0000000012000000..0x0000000013ffffff
[    1.619066]   IO 0x0000000000000000..0x0000000000000000
[    1.624613] PCI host bridge to bus 0000:00
[    1.628883] pci_bus 0000:00: root bus resource [mem 0x12000000-0x13ffffff]
[    1.635991] pci_bus 0000:00: root bus resource [io  0x0000]
[    1.641748] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    1.648766] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    1.656980] pci 0000:00:00.0: [168c:003c] type 00 class 0x028000
[    1.663227] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    1.670293] pci 0000:00:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    1.677295] pci 0000:00:00.0: supports D1
[    1.681440] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.688265] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    1.695114] pci 0000:00:00.0: BAR 0: assigned [mem 0x12000000-0x121fffff 64bit]
[    1.702714] pci 0000:00:00.0: BAR 6: assigned [mem 0x12200000-0x1220ffff pref]

[20:42:47.665]收←◆[    2.049452] ag71xx 19000000.eth: connected to PHY at mdio.0:1f:04 [uid=004dd042, driver=Generic PHY]
[    2.059707] eth1: Atheros AG71xx at 0xb9000000, irq 4, mode: mii
[    2.068483] /dev/root: Can't open blockdev
[    2.072729] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    2.080501] Please append a correct "root=" boot option; here are the available partitions:
[    2.089150] 1f00              64 mtdblock0 
[    2.089153]  (driver?)
[    2.095919] 1f01           16192 mtdblock1 
[    2.095921]  (driver?)
[    2.102669] 1f02              64 mtdblock2 
[    2.102671]  (driver?)
[    2.109424] 1f03              64 mtdblock3 
[    2.109426]  (driver?)
[    2.116182] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    2.124712] Rebooting in 1 seconds..

[20:42:48.750]收←◆\0
[20:42:49.411]收←◆
Boot and Recovery Environment for Embedded Devices
Copyright (C) 2017 HackPascal <hackpascal@gmail.com>
Build date 2017-08-31 [git-33d06d8]
Version 1.1 (r1080)

DRAM: 128MB
Platform: Qualcomm Atheros QCA956X rev 0
Board: TP-LINK TL-WDR6500 v2
Clocks: CPU: 750MHz, DDR: 650MHz, AHB: 250MHz, Ref: 25MHz
Flash: Winbond W25Q128 (16MB) on ath79-spi.0
ag71xx-eth: Using MAC address 11:11:17:68:6c:3e

[20:42:49.552]收←◆Waiting for auto-negotiation complete ... 
[20:42:51.049]收←◆OK
eth0: Atheros AR8228/AR8229 rev 1

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ...     5Press any key to interrupt autoboot ...     4
[20:42:52.060]收←◆Press any key to interrupt autoboot ...     3
[20:42:53.060]收←◆Press any key to interrupt autoboot ...     2
[20:42:54.060]收←◆Press any key to interrupt autoboot ...     1
[20:42:55.060]收←◆Press any key to interrupt autoboot ...     0
[20:42:56.059]收←◆

A：

**Comment by AmadeusGhost** [comment]
你日志都不给让人怎么解决

**Comment by isLaLa** [comment]
[20:42:39.189]收←◆Press any key to interrupt autoboot ...     3
[20:42:40.189]收←◆Press any key to interrupt autoboot ...     2
[20:42:41.189]收←◆Press any key to interrupt autoboot ...     1
[20:42:42.189]收←◆Press any key to interrupt autoboot ...     0
[20:42:43.188]收←◆

Trying to boot firmware from 0x9f010200 ...
U-Boot firmware image header detected.
    Image Name:   MIPS OpenWrt Linux-5.4.150
    Data Size:    2080249 Bytes
    Load Address: 80060000
    Entry Point:  80060000
Uncompressing data (LZMA) ... 
[20:42:45.386]收←◆done.
Flushing cache ... done.

Starting kernel at 0x80060000...

[    0.000000] Linux version 5.4.150 (qq@qq-virtual-machine) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r3801-53d63e38a)) #0 Wed Oct 13 09:29:11 2021
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is TP-Link TL-WDR6500 v2
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 122000K/131072K available (4994K kernel code, 184K rwdata, 1140K rodata, 1224K init, 196K bss, 9072K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] random: get_random_bytes called from start_kernel+0x358/0x54c with crng_init=0
[    0.000000] CPU clock: 750.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 5096694524 ns
[    0.000006] sched_clock: 32 bits at 375MHz, resolution 2ns, wraps every 5726622718ns

[20:42:45.685]收←◆[    0.008846] Calibrating delay loop... 373.55 BogoMIPS (lpj=1867776)
[    0.075956] pid_max: default: 32768 minimum: 301
[    0.081326] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.089617] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.102320] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.113528] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.121347] pinctrl core: initialized pinctrl subsystem
[    0.128217] NET: Registered protocol family 16

[20:42:45.778]收←◆[    0.161516] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.175912] clocksource: Switched to clocksource MIPS
[    0.182771] NET: Registered protocol family 2
[    0.187896] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.196666] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.206220] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.214917] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.222937] TCP: Hash tables configured (established 1024 bind 1024)
[    0.230287] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.237752] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.245986] NET: Registered protocol family 1
[    0.250965] PCI: CLS 0 bytes, default 32
[    0.258950] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.272627] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.279300] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.305152] pinctrl-single 1804002c.pinmux: 544 pins, size 68
[    0.312753] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.320650] printk: console [ttyS0] disabled
[    0.325536] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 1562500) is a 16550A
[    0.335369] printk: console [ttyS0] enabled
[    0.335369] printk: console [ttyS0] enabled
[    0.344436] printk: bootconsole [early0] disabled
[    0.344436] printk: bootconsole [early0] disabled
[    0.370538] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.375534] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.382117] Creating 4 MTD partitions on "spi0.0":
[    0.387093] 0x000000000000-0x000000010000 : "u-boot"
[    0.393093] 0x000000010000-0x000000fe0000 : "firmware"
[    0.401208] 0x000000fe0000-0x000000ff0000 : "mib0"
[    0.407070] 0x000000ff0000-0x000001000000 : "art"
[    0.414519] libphy: Fixed MDIO Bus: probed

[20:42:46.393]收←◆[    0.777004] ag71xx 19000000.eth: Could not connect to PHY device. Deferring probe.

[20:42:47.072]收←◆[    1.456282] libphy: ag71xx_mdio: probed
[    1.460961] libphy: ar8xxx-mdio: probed

[20:42:47.109]收←◆[    1.492594] switch0: Atheros AR8229 rev. 1 switch registered on mdio.0

[20:42:47.177]收←◆[    1.561496] ag71xx 1a000000.eth: connected to PHY at fixed-0:00 [uid=00000000, driver=Generic PHY]
[    1.571344] eth0: Atheros AG71xx at 0xba000000, irq 5, mode: gmii
[    1.577887] i2c /dev entries driver
[    1.583757] NET: Registered protocol family 10
[    1.593544] Segment Routing with IPv6
[    1.597478] NET: Registered protocol family 17
[    1.602134] 8021q: 802.1Q VLAN Support v1.8
[    1.607307] PCI host bridge /ahb/pcie-controller@18250000 ranges:
[    1.613623]  MEM 0x0000000012000000..0x0000000013ffffff
[    1.619066]   IO 0x0000000000000000..0x0000000000000000
[    1.624613] PCI host bridge to bus 0000:00
[    1.628883] pci_bus 0000:00: root bus resource [mem 0x12000000-0x13ffffff]
[    1.635991] pci_bus 0000:00: root bus resource [io  0x0000]
[    1.641748] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    1.648766] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    1.656980] pci 0000:00:00.0: [168c:003c] type 00 class 0x028000
[    1.663227] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    1.670293] pci 0000:00:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    1.677295] pci 0000:00:00.0: supports D1
[    1.681440] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.688265] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    1.695114] pci 0000:00:00.0: BAR 0: assigned [mem 0x12000000-0x121fffff 64bit]
[    1.702714] pci 0000:00:00.0: BAR 6: assigned [mem 0x12200000-0x1220ffff pref]

[20:42:47.665]收←◆[    2.049452] ag71xx 19000000.eth: connected to PHY at mdio.0:1f:04 [uid=004dd042, driver=Generic PHY]
[    2.059707] eth1: Atheros AG71xx at 0xb9000000, irq 4, mode: mii
[    2.068483] /dev/root: Can't open blockdev
[    2.072729] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    2.080501] Please append a correct "root=" boot option; here are the available partitions:
[    2.089150] 1f00              64 mtdblock0 
[    2.089153]  (driver?)
[    2.095919] 1f01           16192 mtdblock1 
[    2.095921]  (driver?)
[    2.102669] 1f02              64 mtdblock2 
[    2.102671]  (driver?)
[    2.109424] 1f03              64 mtdblock3 
[    2.109426]  (driver?)
[    2.116182] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    2.124712] Rebooting in 1 seconds..

[20:42:48.750]收←◆\0
[20:42:49.411]收←◆
Boot and Recovery Environment for Embedded Devices
Copyright (C) 2017 HackPascal <hackpascal@gmail.com>
Build date 2017-08-31 [git-33d06d8]
Version 1.1 (r1080)

DRAM: 128MB
Platform: Qualcomm Atheros QCA956X rev 0
Board: TP-LINK TL-WDR6500 v2
Clocks: CPU: 750MHz, DDR: 650MHz, AHB: 250MHz, Ref: 25MHz
Flash: Winbond W25Q128 (16MB) on ath79-spi.0
ag71xx-eth: Using MAC address 80:89:17:68:6c:3e

[20:42:49.552]收←◆Waiting for auto-negotiation complete ... 
[20:42:51.049]收←◆OK
eth0: Atheros AR8228/AR8229 rev 1

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ...     5Press any key to interrupt autoboot ...     4
[20:42:52.060]收←◆Press any key to interrupt autoboot ...     3
[20:42:53.060]收←◆Press any key to interrupt autoboot ...     2
[20:42:54.060]收←◆Press any key to interrupt autoboot ...     1
[20:42:55.060]收←◆Press any key to interrupt autoboot ...     0
[20:42:56.059]收←◆

Trying to boot firmware from 0x9f010200 ...
U-Boot firmware image header detected.
    Image Name:   MIPS OpenWrt Linux-5.4.150
    Data Size:    2080249 Bytes
    Load Address: 80060000
    Entry Point:  80060000
Uncompressing data (LZMA) ... 
[20:42:58.257]收←◆done.
Flushing cache ... done.

Starting kernel at 0x80060000...

[    0.000000] Linux version 5.4.150 (qq@qq-virtual-machine) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r3801-53d63e38a)) #0 Wed Oct 13 09:29:11 2021
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019750 (MIPS 74Kc)
[    0.000000] MIPS: machine is TP-Link TL-WDR6500 v2
[    0.000000] SoC: Qualcomm Atheros QCA956X ver 1 rev 0
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32 bytes
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000007ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 32480
[    0.000000] Kernel command line: console=ttyS0,115200n8 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 122000K/131072K available (4994K kernel code, 184K rwdata, 1140K rodata, 1224K init, 196K bss, 9072K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 51
[    0.000000] random: get_random_bytes called from start_kernel+0x358/0x54c with crng_init=0
[    0.000000] CPU clock: 750.000 MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 5096694524 ns
[    0.000006] sched_clock: 32 bits at 375MHz, resolution 2ns, wraps every 5726622718ns

[20:42:58.556]收←◆[    0.008846] Calibrating delay loop... 373.55 BogoMIPS (lpj=1867776)
[    0.075956] pid_max: default: 32768 minimum: 301
[    0.081328] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.089617] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.102328] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.113528] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.121348] pinctrl core: initialized pinctrl subsystem
[    0.128213] NET: Registered protocol family 16

[20:42:58.648]收←◆[    0.161564] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.175958] clocksource: Switched to clocksource MIPS
[    0.182821] NET: Registered protocol family 2
[    0.187949] IP idents hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.196721] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.206274] TCP established hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.214970] TCP bind hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.222990] TCP: Hash tables configured (established 1024 bind 1024)
[    0.230330] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.237797] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.246032] NET: Registered protocol family 1
[    0.251011] PCI: CLS 0 bytes, default 32
[    0.258991] workingset: timestamp_bits=14 max_order=15 bucket_order=1
[    0.272659] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.279336] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.305226] pinctrl-single 1804002c.pinmux: 544 pins, size 68
[    0.312824] Serial: 8250/16550 driver, 1 ports, IRQ sharing disabled
[    0.320725] printk: console [ttyS0] disabled
[    0.325607] 18020000.uart: ttyS0 at MMIO 0x18020000 (irq = 9, base_baud = 1562500) is a 16550A
[    0.335442] printk: console [ttyS0] enabled
[    0.335442] printk: console [ttyS0] enabled
[    0.344507] printk: bootconsole [early0] disabled
[    0.344507] printk: bootconsole [early0] disabled
[    0.370592] spi-nor spi0.0: w25q128 (16384 Kbytes)
[    0.375588] 4 fixed-partitions partitions found on MTD device spi0.0
[    0.382179] Creating 4 MTD partitions on "spi0.0":
[    0.387155] 0x000000000000-0x000000010000 : "u-boot"
[    0.393158] 0x000000010000-0x000000fe0000 : "firmware"
[    0.401282] 0x000000fe0000-0x000000ff0000 : "mib0"
[    0.407143] 0x000000ff0000-0x000001000000 : "art"
[    0.414597] libphy: Fixed MDIO Bus: probed

[20:42:59.264]收←◆[    0.777050] ag71xx 19000000.eth: Could not connect to PHY device. Deferring probe.

[20:42:59.943]收←◆[    1.456328] libphy: ag71xx_mdio: probed
[    1.461004] libphy: ar8xxx-mdio: probed

[20:42:59.979]收←◆[    1.492637] switch0: Atheros AR8229 rev. 1 switch registered on mdio.0

[20:43:00.049]收←◆[    1.561537] ag71xx 1a000000.eth: connected to PHY at fixed-0:00 [uid=00000000, driver=Generic PHY]
[    1.571391] eth0: Atheros AG71xx at 0xba000000, irq 5, mode: gmii
[    1.577932] i2c /dev entries driver
[    1.583803] NET: Registered protocol family 10
[    1.593580] Segment Routing with IPv6
[    1.597513] NET: Registered protocol family 17
[    1.602170] 8021q: 802.1Q VLAN Support v1.8
[    1.607352] PCI host bridge /ahb/pcie-controller@18250000 ranges:
[    1.613667]  MEM 0x0000000012000000..0x0000000013ffffff
[    1.619112]   IO 0x0000000000000000..0x0000000000000000
[    1.624657] PCI host bridge to bus 0000:00
[    1.628930] pci_bus 0000:00: root bus resource [mem 0x12000000-0x13ffffff]
[    1.636046] pci_bus 0000:00: root bus resource [io  0x0000]
[    1.641803] pci_bus 0000:00: root bus resource [??? 0x00000000 flags 0x0]
[    1.648822] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[    1.657042] pci 0000:00:00.0: [168c:003c] type 00 class 0x028000
[    1.663289] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x001fffff 64bit]
[    1.670355] pci 0000:00:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    1.677358] pci 0000:00:00.0: supports D1
[    1.681503] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    1.688329] pci_bus 0000:00: busn_res: [bus 00-ff] end is updated to 00
[    1.695177] pci 0000:00:00.0: BAR 0: assigned [mem 0x12000000-0x121fffff 64bit]
[    1.702779] pci 0000:00:00.0: BAR 6: assigned [mem 0x12200000-0x1220ffff pref]

[20:43:00.536]收←◆[    2.049498] ag71xx 19000000.eth: connected to PHY at mdio.0:1f:04 [uid=004dd042, driver=Generic PHY]
[    2.059759] eth1: Atheros AG71xx at 0xb9000000, irq 4, mode: mii
[    2.068545] /dev/root: Can't open blockdev
[    2.072792] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    2.080564] Please append a correct "root=" boot option; here are the available partitions:
[    2.089211] 1f00              64 mtdblock0 
[    2.089214]  (driver?)
[    2.095974] 1f01           16192 mtdblock1 
[    2.095976]  (driver?)
[    2.102722] 1f02              64 mtdblock2 
[    2.102724]  (driver?)
[    2.109477] 1f03              64 mtdblock3 
[    2.109479]  (driver?)
[    2.116235] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    2.124765] Rebooting in 1 seconds..

[20:43:01.622]收←◆\0
[20:43:02.282]收←◆
Boot and Recovery Environment for Embedded Devices
Copyright (C) 2017 HackPascal <hackpascal@gmail.com>
Build date 2017-08-31 [git-33d06d8]
Version 1.1 (r1080)

DRAM: 128MB
Platform: Qualcomm Atheros QCA956X rev 0
Board: TP-LINK TL-WDR6500 v2
Clocks: CPU: 750MHz, DDR: 650MHz, AHB: 250MHz, Ref: 25MHz
Flash: Winbond W25Q128 (16MB) on ath79-spi.0
ag71xx-eth: Using MAC address 80:89:17:68:6c:3e

[20:43:02.423]收←◆Waiting for auto-negotiation complete ... 
[20:43:03.928]收←◆OK
eth0: Atheros AR8228/AR8229 rev 1

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ...     5Press any key to interrupt autoboot ...     4
[20:43:04.929]收←◆Press any key to interrupt autoboot ...     3
[20:43:05.929]收←◆Press any key to interrupt autoboot ...     2

**Comment by coolsnowwolf** [comment]
uboot 不能启动现在的格式了，需要联系 uboot 作者

**Comment by isLaLa** [comment]
谢谢
