### ISSUE TITLE
求助：在界面上升级固件后，启动时，报了F2FS-fs相关错误后，就卡在EXTFAT trying to mount...不动了

### ISSUE THREAD

**Issue by xianshanlai** [coolsnowwolf/lede#8039]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 有类似的issue，但是还是无法解决

### (1) 具体问题

A：新编译的X86 64位固件，通过界面升级后启动日志卡在：
F2FS-fs（sda128）:Magic Mismatch, valid(0xf2f52010) - read(0xd44d89e4)
F2FS-fs（sda128）:Cann't find valid F2FS filesystem in 1th superblock
F2FS-fs（sda128）:Magic Mismatch, valid(0xf2f52010) - read(080a345bd)
F2FS-fs（sda128）:Cann't find valid F2FS filesystem in 2th superblock
EXTFAT trying to mount...
不动了，重启无效；
用pe盘启动后按照网上的方法用phydiskwrite重新刷入后，还是一样的问题，请问要如何解决啊，谢谢

### (2) 路由器型号和固件版本

A：路由器为 j1900
      固件版本：r3792-86cec7689 

### (3) 详细日志

A：
F2FS-fs（sda128）:Magic Mismatch, valid(0xf2f52010) - read(0xd44d89e4)
F2FS-fs（sda128）:Cann't find valid F2FS filesystem in 1th superblock
F2FS-fs（sda128）:Magic Mismatch, valid(0xf2f52010) - read(080a345bd)
F2FS-fs（sda128）:Cann't find valid F2FS filesystem in 2th superblock
EXTFAT trying to mount...

**Comment by xianshanlai** [comment]
>
![图片](https://user-images.githubusercontent.com/616578/137062764-cda1fbb8-ce3d-40ef-9a5d-f0badf8a9d1d.png)

**Comment by WYC-2020** [comment]
想什么呢，你怕是第一次玩吧，这个第一次设置好后就不用管了，只要页面能登陆你管他能不能继续，这玩意后台必须回车才会出现shell输入

**Comment by forever2019** [comment]
连接不上路由  无法分配IP   我测试好几次  可能是我编译的问题吧
我还是继续使用 4.3内核吧

**Comment by WYC-2020** [comment]
这个配置ip 到处都是教程 自己去看下

**Comment by xianshanlai** [comment]
> 
> 
> 连接不上路由 无法分配IP 我测试好几次 可能是我编译的问题吧 我还是继续使用 4.3内核吧

我也是。。。

**Comment by xianshanlai** [comment]
> 白得过分的问题。。第一次刷固件吗？这问题关闭吧。。。

被你看出来了，￣^￣゜，不过卡住的问题确实存在啊！万一重启都得键盘按下回车，还得一直备个键盘在旁边。。。
