### ISSUE TITLE
luci-app-turboacc 更新出现系统错误日志

### ISSUE THREAD

**Issue by bob-zebedy** [coolsnowwolf/lede#8042]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

该次 https://github.com/coolsnowwolf/lede/commit/7f7366334cd2fd8d9f6d77b4b8f420ed74c4c9b1 commit 导致系统日志中出现错误 /etc/init.d/turboacc_fss: Permission denied 错误

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

更新最新版本的lede，启动过程中系统日志中产生错误

<img width="1012" alt="Google Chrome-OpenWrt - 系统日志 - LuCI-20211013224913" src="https://user-images.githubusercontent.com/53208952/137157499-d9b7e523-7156-4f6d-bc2d-9e88675b4a57.png">

启动后在启动项中可看到 turboacc_fss 显示为禁用，点击启用后也会产生该错误

<img width="866" alt="Google Chrome-OpenWrt - 启动项 - LuCI-20211013224949" src="https://user-images.githubusercontent.com/53208952/137157626-e54174b3-7583-4d1a-bb44-f8e000cbedf0.png">

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：
x86

### (3) 详细日志

A：
Wed Oct 13 22:28:54 2021 kern.info kernel: [   27.763521] 8021q: adding VLAN 0 to HW filter on device eth2
Wed Oct 13 22:28:54 2021 kern.info kernel: [   27.765243] br-lan: port 2(eth2) entered blocking state
Wed Oct 13 22:28:54 2021 kern.info kernel: [   27.766859] br-lan: port 2(eth2) entered disabled state
Wed Oct 13 22:28:54 2021 kern.info kernel: [   27.768516] device eth2 entered promiscuous mode
Wed Oct 13 22:28:54 2021 daemon.notice procd: /etc/rc.d/S50uhttpd: 4+0 records in
Wed Oct 13 22:28:54 2021 daemon.notice procd: /etc/rc.d/S50uhttpd: 4+0 records out
Wed Oct 13 22:28:54 2021 daemon.notice procd: /etc/rc.d/S60dnsforwarder: luci for dnsforwarder
Wed Oct 13 22:28:54 2021 daemon.notice procd: /etc/rc.d/S60dnsforwarder: dnsforwarder is not enabled
Wed Oct 13 22:28:54 2021 daemon.notice procd: /etc/rc.d/S90turboacc: /etc/rc.common: line 230: /etc/init.d/turboacc_fss: Permission denied

**Comment by deplives** [comment]
找到原因了，我的锅
