### ISSUE TITLE
执行./scripts/feeds install -a时出错

### ISSUE THREAD

**Issue by ferdinand474** [coolsnowwolf/lede#8060]
1.执行./scripts/feeds install -a时出错

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在执行./scripts/feeds install -a时出错
具体变现为出现warning

### (2) 路由器型号和固件版本

A：系统为在vmware15中使用Ubuntu 20.04 LTS x64 科学软件已打开全局
前面的步骤已经正确执行完毕

### (3) 详细日志
`
A：hu666@hu666-virtual-machine:~/lede$ ./scripts/feeds update -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
已经是最新的。
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci' ...
已经是最新的。
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
已经是最新的。
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
已经是最新的。
Create index file './feeds/packages.index' 
Create index file './feeds/luci.index' 
Create index file './feeds/routing.index' 
Create index file './feeds/telephony.index' 
hu666@hu666-virtual-machine:~/lede$ ./scripts/feeds install -a
WARNING: Makefile 'package/feeds/small/brook/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/hysteria/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/trojan-go/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/v2ray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
hu666@hu666-virtual-machine:~/lede$ make menuconfig
WARNING: Makefile 'package/feeds/small/brook/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/hysteria/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/trojan-go/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/v2ray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-core/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/small/xray-plugin/Makefile' has a build dependency on 'upx/host', which does not exist

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.
`

**Comment by Boos4721** [comment]
why not use ***OpenWrt SDK*** to compile luci-base

**Comment by xiaopang0v0** [comment]
请问您有进行 make download V=s吗？

**Comment by Boos4721** [comment]
> 请问您有进行 make download V=s吗？

na he hasnt compile toolchain at firsrt time.

**Comment by Cathgao** [comment]
warning≠error
