### ISSUE TITLE
系统日志的报错，ssr-GFW模式无法正常代理

### ISSUE THREAD

**Issue by edmondfr** [coolsnowwolf/lede#807]
WRT1200ac 编译最新固件，r963-db94837b版本。系统日志报错比以前少了很多，但还有一些。
----------------------------------------------------------------------------------------------------------
Tue Nov 13 01:23:11 2018 user.notice mac80211: Failed command: iw phy phy0 set antenna all all
Tue Nov 13 01:23:11 2018 authpriv.info dropbear[2403]: Not backgrounding
Tue Nov 13 01:23:11 2018 daemon.notice netifd: radio0 (2100): command failed: Not supported (-95)
Tue Nov 13 01:23:11 2018 user.notice mac80211: Failed command: iw phy phy0 set distance 0
Tue Nov 13 01:23:11 2018 user.notice mac80211: Failed command: iw phy phy1 set antenna all all
Tue Nov 13 01:23:11 2018 daemon.notice netifd: radio1 (2101): command failed: Not supported (-95)
Tue Nov 13 01:23:11 2018 user.notice mac80211: Failed command: iw phy phy1 set distance 0
Tue Nov 13 01:23:11 2018 daemon.err hostapd: Configuration file: /var/run/hostapd-phy0.conf
Tue Nov 13 01:23:11 2018 daemon.err hostapd: Configuration file: /var/run/hostapd-phy1.conf
Tue Nov 13 01:23:12 2018 daemon.notice procd: /etc/rc.d/S90vlmcsd: OpenWrt
Tue Nov 13 01:23:12 2018 daemon.notice procd: /etc/rc.d/S90vlmcsd:
Tue Nov 13 01:23:12 2018 kern.debug kernel: [   15.459335] ieee80211 phy0: change: 0xffffffff
------------------------------------------------------------------------------------------------------------

另外，ssr GFW模式下代理无法使用，重启依然。IP模式可以。
奇怪的是，在状态测试栏，google里确是连的通的，就是浏览器网页打不开。

谢谢。

**Comment by lan542662** [comment]
我已经放弃GFW模式了。有未知的隐藏坑。不知道为啥。。还是用IP模式吧
