### ISSUE TITLE
红米ac2100闭源驱动修改lan配置，wifi自动禁用

### ISSUE THREAD

**Issue by pengc-1** [coolsnowwolf/lede#8075]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：红米ac2100使用闭源wifi驱动，在修改lan的任何配置都会导致wifi自动停用

### (2) 路由器型号和固件版本

A：红米ac2100

### (3) 详细日志

A：

**Comment by EnnawYang** [comment]
闭源驱动就这样，自己设置完lan后重启下wifi

**Comment by pengc-1** [comment]
楼上的代码有效谢谢

**Comment by MonwF** [comment]
> 楼上的代码有效谢谢

抱歉，之前的代码有问题，会导致编辑其他接口时出问题，新代码重新编辑了
从 https://github.com/coolsnowwolf/luci/blob/master/modules/luci-base/luasrc/view/cbi/network_ifacelist.htm 还原后，重新执行下吧
