### ISSUE TITLE
make: *** [menuconfig] Error 1

### ISSUE THREAD

**Issue by XuYuQuan0713** [coolsnowwolf/lede#8088]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
make menuconfig出现错误
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7-json', which does not exist
Your display is too small to run Menuconfig!
It must be at least 19 lines by 80 columns.
/home/juzhen/openwrt/lede/include/toplevel.mk:133: recipe for target 'menuconfig' failed

**Comment by kokenot** [comment]
maximize your terminal.

**Comment by XuYuQuan0713** [comment]
解决了，是因为配置的问题，水图那些的你们好像一条狗

**Comment by Karmylr** [comment]
> Your display is too small to run Menuconfig!

没人出来解释？根本不是因为配置。报错”Your display is too small to run Menuconfig!“是ssh界面太小。

**Comment by Boos4721** [comment]
> > Your display is too small to run Menuconfig!
> 
> 没人出来解释？根本不是因为配置。报错”Your display is too small to run Menuconfig!“是ssh界面太小。

**LMFAO**
