### ISSUE TITLE
京东签到插件更新1.0.6，望同步一下

### ISSUE THREAD

**Issue by RealSlakey** [coolsnowwolf/lede#8090]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
京东签到插件更新1.0.6，望同步一下
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
京东签到插件旧版扫码无法获取cookie了，已经更新1.0.6，望同步一下

**Comment by WYC-2020** [comment]
目测不得行的，就改了一处浏览器代理而已，应该不能解决这个扫码问题

**Comment by RealSlakey** [comment]
> 1.0.6可以了吗？单独编译了插件，更新试了一下好像还是不行呐。

我单独编译后第一回试的可以，后面又不行了，现在直接抓包金融app了
