### ISSUE TITLE
能否分享一下编译5.10内核的config参数

### ISSUE THREAD

**Issue by eightsheep67** [coolsnowwolf/lede#8099]
现在action云编译如果手动ssh设置config总是会被系统关闭，导致现在只能用现成的config来编译才能成功。
原来我config里写的是
CONFIG_LINUX_5_10=y
但是现在这个参数不对了，编译出啦还是5.4内核。
有人能分享一下这一行的参数吗？

**Comment by EnnawYang** [comment]
`CONFIG_TESTING_KERNEL=y`  
或者直接改源码

**Comment by eightsheep67** [comment]
> `CONFIG_TESTING_KERNEL=y` 或者直接改源码

是的就是要这个！谢谢！！
