### ISSUE TITLE
建议SSR plus+ 添加纯代理模式

### ISSUE THREAD

**Issue by supppig** [coolsnowwolf/lede#810]
即只启动一个ssr-local。不需要全局模式。
如果故障自动切换也能正常工作的话，那就更好了~~~
可以实现么？

**Comment by coolsnowwolf** [comment]
目前就是这样的。。。

**Comment by supppig** [comment]
> 目前就是这样的。。。

运行模式里面只有“GWF列表模式”和“绕过大陆IP模式”。
没有发现只运行ssr-local的模式啊。。。

我希望的是，正常情况下不能翻墙，但是浏览器设置了代理 192.168.1.1:1080 就全局翻墙。。

**Comment by supppig** [comment]
已经找到了，之前编译少了一个模块。现在好了。
感谢老大！

**Comment by jonirrings** [comment]
咦，啥模块啊？我也想用这种来着。
