### ISSUE TITLE
32位编译后，使用bash,出现time64: symbol not found

### ISSUE THREAD

**Issue by dfbucy090** [coolsnowwolf/lede#8108]
过去安装bash后使用正常，现在编译后，安装bash后出现以下显示
root@OpenWrt:~# chmod +x cf-auto-passwall.sh && bash cf-auto-passwall.sh
Error relocating /bin/bash: __select_time64: symbol not found
Error relocating /bin/bash: __fstat_time64: symbol not found
Error relocating /bin/bash: __getrusage_time64: symbol not found
Error relocating /bin/bash: __stat_time64: symbol not found
Error relocating /bin/bash: __time64: symbol not found
Error relocating /bin/bash: __pselect_time64: symbol not found
Error relocating /bin/bash: __gettimeofday_time64: symbol not found
Error relocating /bin/bash: __localtime64: symbol not found
Error relocating /bin/bash: __lstat_time64: symbol not found
Error relocating /bin/bash: __dlsym_time64: symbol not found
Error relocating /bin/bash: __setitimer_time64: symbol not found

刷过去编译，使用bash正常的留存固件，再次安装bash后，也不能正常使用bash，还是如上显示。请大佬们指点一下，具体怎样解决，本人小白。

**Comment by dfbucy090** [comment]
> > 从openwrt原版里复制一个过来，在 diy.sh 加一下，
> > git clone https://github.com/openwrt/openwrt openwrt-origin rm -rf toolchain/musl /bin/cp -rf openwrt-origin/toolchain/musl toolchain rm -rf openwrt-origin
> 
> 谢谢您，本人小白，是把git clone https://github.com/openwrt/openwrt openwrt-origin rm -rf toolchain/musl /bin/cp -rf openwrt-origin/toolchain/musl toolchain rm -rf openwrt-origin 这些粘贴在diy.sh文件里吗？diy.sh 文件在哪里找？越具体越好，不胜感激。

再次感谢您，用你的方法解决了，在lede目录下，执行你给的命令行，然后编译就解决了，虽然不懂，但是能解决问题很高兴。

**Comment by WYC-2020** [comment]
@AmadeusGhost  建议不要升级，这边升级到1.2.2后编译x86 32位版本会出现很多异常，用原来没升级之前的没有任何异常，x86 64位的用升级后的没有任何问题正常
![image](https://user-images.githubusercontent.com/34025388/143533846-aa21675e-d320-41d4-ae49-db68bd66a587.png)

**Comment by liuchuanheng** [comment]
大佬，你好，我也遇到了同样的问题，我是小白，请问您具体是如何解决的，谢谢您！
Error relocating /bin/bash: __select_time64: symbol not found
Error relocating /bin/bash: __fstat_time64: symbol not found
Error relocating /bin/bash: __getrusage_time64: symbol not found
Error relocating /bin/bash: __stat_time64: symbol not found
Error relocating /bin/bash: __time64: symbol not found
Error relocating /bin/bash: __pselect_time64: symbol not found
Error relocating /bin/bash: __gettimeofday_time64: symbol not found
Error relocating /bin/bash: __localtime64: symbol not found
Error relocating /bin/bash: __lstat_time64: symbol not found
Error relocating /bin/bash: __dlsym_time64: symbol not found
Error relocating /bin/bash: __setitimer_time64: symbol not found
