### ISSUE TITLE
ssrplus中v2ray没有作用

### ISSUE THREAD

**Issue by housemlm** [coolsnowwolf/lede#811]
前天刷了lean大最新的版本，路由器wndr4300v1，用的ssrplus，整合了v2ray,ssr可以正常使用，但是v2ray不行，节点正常，手机，pc端都可以用，ssrplus正常启动无报错。不知道为何。

**Comment by Lancenas** [comment]
wndr4300v1 昨天编译，v2ray可以正常使用。
