### ISSUE TITLE
K2P 5G channel stuck at 36

### ISSUE THREAD

**Issue by protocold** [coolsnowwolf/lede#8123]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：No matter what channel I choose, the 5Ghz channel always stuck at 36 and country US on my K2P. 

### (2) 路由器型号和固件版本

A：K2P A1

### (3) 详细日志

A：

**Comment by victoratmaoludotone** [comment]
same issue on my gli-net mt-1300 device with mt7621 chip.
