### ISSUE TITLE
红米660x 重启问题仍在

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#8137]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
昨天编译的最新版本通过sysupgrade更新，仍存在重启问题。
### (1) 具体问题

A：仍然不定时自动重启，通过syslog-ng抓取日志，但是日志时间差了8个小时，不太对。而且日志中大段hostapd的日志，我看了一下也没看懂，不知道有没有抓到重启相关的日志。日志上传阿里云了

### (2) 路由器型号和固件版本

A：红米6608

### (3) 详细日志

A：https://www.aliyundrive.com/s/84MBMZ7zKFa

**Comment by hzjixiang** [comment]
这不仅仅openwrt的问题，我发现老毛子的PDCN也会重启。可能wifi6(MT7975DN)驱动BUG？
