### ISSUE TITLE
亲爱的，lib32gcc1改名啦

### ISSUE THREAD

**Issue by Xielipton** [coolsnowwolf/lede#8147]
根据文档配置环境发现lib32gcc1被遗弃，被改为lib32gcc-s1，如用原名将无法配置环境
ubuntu server 21.10/ubuntu desktop 21

**Comment by yinzhefuyun** [comment]
首先装好 Ubuntu 64bit，推荐 Ubuntu 20.04 LTS x64

**Comment by 596142041** [comment]
Ubuntu21,无法正常编译,报各种故障,最后还是使用Ubuntu20编译,

**Comment by Boos4721** [comment]
> Ubuntu21,无法正常编译,报各种故障,最后还是使用Ubuntu20编译,

NA, STILLL WORK ON **impish**.
![iShot2021-11-04 22 39 58](https://user-images.githubusercontent.com/43845654/140334278-26b582d3-9e8c-4552-a833-0c07d593b4f8.png)

**Comment by WindyMadman** [comment]
我这边连环境都装不上 更别提编译了  :(

**Comment by WindyMadman** [comment]
我的20.04安装build-essential 提示依赖libc6-dev但是是不可安装的=.=
