### ISSUE TITLE
N1盒子编译出来

### ISSUE THREAD

**Issue by siren202101** [coolsnowwolf/lede#8157]
![image](https://user-images.githubusercontent.com/80493699/139647701-ecd51ddc-993c-4c33-a495-a76a2a38c4f6.png)
新源码编译出来的openwrt-armvirt-64-default-rootfs
要么找不到install-to-emmc.sh,要么运行不了install-to-emmc.sh，运行了又变成这样是什么原理？如何解决？

**Comment by ZqinKing** [comment]
大兄弟，install-to-emmc.sh不是这个项目里带的吧。

**Comment by ZqinKing** [comment]
https://github.com/unifreq/openwrt_packit.git

**Comment by siren202101** [comment]
> https://github.com/unifreq/openwrt_packit.git

   这个有点玄学，我试用使用openwrt_packit.git前两个版本的来打包也是失败
openwrt_packit.git打包旧源码编译的openwrt-armvirt-64-default-rootfs成功，打包新源码编译的openwrt-armvirt-64-default-rootfs失败
就是不知道是那边出的问题所以都问问看

**Comment by yonggedebaqi** [comment]
提示 缺什么补什么再编译

**Comment by kissyouhunter** [comment]
> > https://github.com/unifreq/openwrt_packit.git
> 
> 这个有点玄学，我试用使用openwrt_packit.git前两个版本的来打包也是失败 openwrt_packit.git打包旧源码编译的openwrt-armvirt-64-default-rootfs成功，打包新源码编译的openwrt-armvirt-64-default-rootfs失败 就是不知道是那边出的问题所以都问问看

F大新版的打包没问问题的
三个内核都正常
