### ISSUE TITLE
NEWIFI3-D3 5.10内核编译错误

### ISSUE THREAD

**Issue by hackyes** [coolsnowwolf/lede#8171]
Hunk #10 succeeded at 1231 (offset -236 lines).
2 out of 10 hunks FAILED -- saving rejects to file drivers/net/phy/at803x.c.rej
Patch failed!  Please fix /home/hackyes/lede/target/linux/ramips/patches-5.10/710-at803x.patch!
make[4]: *** [Makefile:33: /home/hackyes/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.77/.prepared_bedd2f94e2638ff831715449e5bab75d] Error 1
make[4]: Leaving directory '/home/hackyes/lede/target/linux/ramips'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/hackyes/lede/target/linux'
time: target/linux/compile#11.03#8.97#15.92
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/hackyes/lede'
make[1]: *** [target/Makefile:18: /home/hackyes/lede/staging_dir/target-mipsel_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/hackyes/lede'
make: *** [/home/hackyes/lede/include/toplevel.mk:230: world] Error 2

**Comment by Boos4721** [comment]
**EZ FOR FIX**
