### ISSUE TITLE
固件编译成功！从breed写入固件ok！但是更改初始密码 WiFi名称 加密协议及lan地址在路由器重新启动后失效！恢复到初始设置！

### ISSUE THREAD

**Issue by jeasonliang** [coolsnowwolf/lede#8174]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
固件编译成功！从breed写入固件ok！但是更改初始密码 WiFi名称 加密协议及lan地址在路由器重新启动后失效！恢复到初始设置！
### (1) 具体问题先前设置的登录密码！WiFi名称加密协议以及lan地址都每一步都点击保存及应用！但是断电重新启动失效！
无法保存系统设置！
A：

### (2) 路由器型号和固件版本
小米4A千兆版本

**Comment by 97xiami** [comment]
你刷的ramdisk文件吧，这个重启后就会恢复默认的
你要刷squashfs的那个才行

**Comment by jeasonliang** [comment]
openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-initramfs-kernel.bin
openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit.manifest
openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
这三个文件 在breed下刷入sysupgrade无法刷入。。。

**Comment by jeasonliang** [comment]
难道是 breed版问题？我是这里下载的
https://breed.hackpascal.net/

**Comment by 97xiami** [comment]
> openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-initramfs-kernel.bin
> openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit.manifest
> openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
> 这三个文件 在breed下刷入sysupgrade无法刷入。。。 

无法刷入是什么意思？报错还是无法开机？

**Comment by jeasonliang** [comment]
> > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-initramfs-kernel.bin
> > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit.manifest
> > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
> > 这三个文件 在breed下刷入sysupgrade无法刷入。。。
> 
> 无法刷入是什么意思？报错还是无法开机？

首先感谢你的回复！
无法开机  黄灯不停闪烁！

**Comment by 97xiami** [comment]
> > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-initramfs-kernel.bin
> > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit.manifest
> > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
> > > 这三个文件 在breed下刷入sysupgrade无法刷入。。。
> > 
> > 无法刷入是什么意思？报错还是无法开机？
> 
> 首先感谢你的回复！
> 无法开机  黄灯不停闪烁！

换个分区刷

**Comment by jeasonliang** [comment]
> > > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-initramfs-kernel.bin
> > > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit.manifest
> > > > openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-squashfs-sysupgrade.bin
> > > > 这三个文件 在breed下刷入sysupgrade无法刷入。。。
> > > 
> > > 
> > > 无法刷入是什么意思？报错还是无法开机？
> > 
> > 
> > 首先感谢你的回复！
> > 无法开机  黄灯不停闪烁！
> 
> 换个分区刷

估计是这个https://www.right.com.cn/FORUM/thread-4052254-1-1.html
