### ISSUE TITLE
mt7621 newifi3内核5.10 编译成功后有线网口不能用

### ISSUE THREAD

**Issue by hackyes** [coolsnowwolf/lede#8175]
全部网口不能连接

**Comment by Henshufu** [comment]
ac2100同样情况。楼主解决了吗？

**Comment by AmadeusGhost** [comment]
不支持 5.10，自行回退。

**Comment by Henshufu** [comment]
> 不支持 5.10，自行回退。

收到。5.4的我用起来一直有个莫名其妙的问题，回退到7月编译的5.10内核版本了。

**Comment by hackyes** [comment]
> ac2100 同样的情况。楼主解决了吗？
我解决了，把交换机干掉，删除了MT7621的旧版驱动，参考openwrt官网的设置可以用

**Comment by lpflhh** [comment]
> > ac2100 同样的情况。楼主解决了吗？
> > 我解决了，把交换机干掉，删除了MT7621的旧版驱动，参考openwrt官网的设置可以用

能详细说一下吗？我也是这个情况
