### ISSUE TITLE
建议Turbo ACC 中的上游DNS服务器填写栏目改为列表式，方便查看

### ISSUE THREAD

**Issue by qiuzhongqiang** [coolsnowwolf/lede#818]
建议Turbo ACC 中的上游DNS服务器填写栏目改为列表式。
现在的情况是，如果填写了多个DNS，长时间后再进入这个功能设置，需要鼠标拖动，才能看到之前到底填写了几个DNS。
请参考图片。
![dns](https://user-images.githubusercontent.com/13807219/48483345-24f61400-e84e-11e8-8fab-7eab66f7073c.PNG)

谢谢大神的付出和努力。

**Comment by qiuzhongqiang** [comment]
你理解错了，我的意思是增加dns服务器时，每个栏格一个dns。图片仅供参考。我不是要bt的tracker.
谢谢！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by coolsnowwolf** [comment]
实际上就是不希望填太多，1-2个最快的即可

**Comment by qiuzhongqiang** [comment]
好的，谢谢回复！
个人建议加上比较方便，因为小弟是移动宽带，希望能多填两个，去改善速度。
