### ISSUE TITLE
RH17架构无线温度无显示问题

### ISSUE THREAD

**Issue by AK201314** [coolsnowwolf/lede#8184]
雕大，用R21.11.11最新源码编译的RH17，架构那里不显示无线温度了呢，开启了呀无线，不知道是代码bug么？请帮忙分析处理下呗

**Comment by ZGNCZMY** [comment]
不知道从哪次更新就这样了，最近WiFi也出了问题，过段时间WiFi就被限速下载速度，反正是做AP已经刷回原厂了

**Comment by AK201314** [comment]
源码没问题，找到原因了，是因为没有勾选arm那个选项
