### ISSUE TITLE
n2n 3.0 release, can we update to it?

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#8205]
hello

I fould n2n has released 3.0 stable in recent days, can we upgrade to this version in Makefile?  thanks.

**Comment by AmadeusGhost** [comment]
Try this: https://github.com/AmadeusGhost/lede/commit/1f2e2432aab345081bcf192bcec405f6c5f6157c

**Comment by zxlhhyccc** [comment]
> Try this: [AmadeusGhost@1f2e243](https://github.com/AmadeusGhost/lede/commit/1f2e2432aab345081bcf192bcec405f6c5f6157c)

经测试，不能运行。。。
![image](https://user-images.githubusercontent.com/45259624/145076971-377db189-930a-4480-9b5c-a0e4a9606d3f.png)
