### ISSUE TITLE
云编译出错 Error: Process completed with exit code 1

### ISSUE THREAD

**Issue by wangyang8284** [coolsnowwolf/lede#8208]
云编译出错：

Collecting package info: feeds/telephony/net/sngrep
Collecting package info: feeds/telephony/net/yate
Collecting package info: merging...

Collecting package info: done
Collecting target info: merging...

Collecting target info: doneCreate index file './feeds/ssrp.index' 
find: ‘feeds/ssrp’: No such file or directory

Collecting package info: merging...

Collecting package info: donefind: ‘feeds/ssrp’: No such file or directory

Collecting target info: merging...

Collecting target info: done
Error: Process completed with exit code 1.

请问该如何解决，感谢！

**Comment by WYC-2020** [comment]
这么明显的提示看不懂？

**Comment by markvlenvision** [comment]
这怎么喷？

**Comment by wangyang8284** [comment]
能看懂，但不知道怎么新建文件夹。。。
