### ISSUE TITLE
编译时不勾选“Enable IPv6 support in packages”，则“Turbo ACC网络加速”不会安装！

### ISSUE THREAD

**Issue by Fyred** [coolsnowwolf/lede#822]
编译时不勾选“Enable IPv6 support in packages”，则WEB管理界面的网络菜单下面就没有“Turbo ACC网络加速”了。

IPv6加速神马的都是浮云，不安装IPv6就让这个选项无效可以吗，别把整个“Turbo ACC网络加速”都阉了啊

请大雕给厌恶IPv6的同学使用“BBR 加速”和“DNS 加速”的机会！！！

**Comment by layefe2315** [comment]
支持这个提议，真想干掉ipv6

**Comment by arfaWong** [comment]
你们都是怎么解决的？

**Comment by wgjwillis** [comment]
我的没有这个问题。关闭“Enable IPv6 support in packages”，也有”Turbo ACC网络加速”。
ar7100平台编译tl-wr1041n v2。
