### ISSUE TITLE
make menuconfig 有问题

### ISSUE THREAD

**Issue by yishan2019** [coolsnowwolf/lede#8224]
新源码的 make menuconfig 有问题,删除了原来的.config后,用make menuconfig配置菜单找不到加进去的各种插件,这是我修改后的fees 文件:
src-git packages https://github.com/coolsnowwolf/packages

src-git luci https://github.com/coolsnowwolf/luci

src-git routing https://git.openwrt.org/feed/routing.git

src-git telephony https://git.openwrt.org/feed/telephony.git

src-git helloworld https://github.com/fw876/helloworld
src-git passwall https://github.com/xiaorouji/openwrt-passwall.git
src-git AdGuardHome https://github.com/AdguardTeam/AdGuardHome
#src-git video https://github.com/openwrt/video.git

#src-git targets https://github.com/openwrt/targets.git

#src-git oldpackages http://git.openwrt.org/packages.git

#src-link custom /usr/src/openwrt/custom-feed
以前都是可以用的,这次新装了Ubuntu都重新装了还是不行!

**Comment by xoomp** [comment]
是的，几个重要工具都没有
