### ISSUE TITLE
系统日志有错误，请帮忙看看问题所在

### ISSUE THREAD

**Issue by 393435992** [coolsnowwolf/lede#8234]
### (1) 问题
总是循环出现以下错误：
daemon.err uhttpd[2079]: sh: yes: unknown operand

### (2) 路由器型号和固件版本

斐讯K3       内核5.4.156

### (3) 看进程是这个
2079	root	/usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -u /ubus -t 60 -T 30 -k 20 -A 1 -n 3 -N 100 -R -p 0.0.0.0:80 -p [::]:80 -I cgi-bin/luci -C /etc/uhttpd.crt -K /etc/uhttpd.key -s 0.0.0.0:443 -s [::]:443

**Comment by hubbylei** [comment]
应该是执行某个脚本的时候出错了

**Comment by jiangmw** [comment]
找到问题了吗？
