### ISSUE TITLE
1. smartdns重启就未运行  2.编译固件版本加入时间,一个X86版本正常,一个R4S版本时间会变成2013年

### ISSUE THREAD

**Issue by showme2005** [coolsnowwolf/lede#8238]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：smartdns在配置好以后,正常使用,但是路由器一重启,smartdns就变成"未运行",但是添加的DNS服务器都还在
B :  还有一个问题.同样的在固件里面加入编译时间的代码,在一台电脑上编译出来的时间正常,但是拿到另一个上面.时间会变成2013 1 18号.编译的时候特意看了一下 ubuntu时间,是正常的
### (2) 路由器型号和固件版本

A：2021-11-12号编译的.X86版本,同样的R4S版本 也出现同样的问题
B: 也是同一时间编译的,一个是X86的正常,一个是R4S的..时间就不对

### (3) 详细日志

A ;系统 日志里面搜索不到smartdns相关的关键字
B:无日志

**Comment by AmadeusGhost** [comment]
时间是启动的时候自动用硬件 rtc 的了，手动同步下时间就好。

**Comment by WYC-2020** [comment]
咋你们说的问题我一个都没遇到过哈哈
