### ISSUE TITLE
rockchip:rk3399 increases the frequency xxxxx 这个提交 把ipq807x系列的温度改没了

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [coolsnowwolf/lede#8242]
也是无语，修了rk3399 就把别的机器温度显示搞没了，红米AX6 主界面就不显示温度了。退回这条提交就好。

**Comment by Boos4721** [comment]
**USE** `awk '{ printf("%.1f°C ", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp`

**Comment by LPDDR6-10000MHz** [comment]
啊这，不好意思哦 已提交 https://github.com/coolsnowwolf/lede/pull/8244

**Comment by 1715173329** [comment]
My script was raped by someone, now it's just a BS.
Reverting all recent changes to it is recommended.
