### ISSUE TITLE
UU 加速器插件是否要求特定 Target System？

### ISSUE THREAD

**Issue by mariohide** [coolsnowwolf/lede#8256]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：选择 Target System 为 ATH79，Make Config 界面，在 LuCI --> Applications 或 Network 中都找不到 uugamebooster 相关的软件包。

### (2) 路由器型号和固件版本

A：路由器型号：Netgear WNDR 3800 固件版本：对此问题无效

### (3) 详细日志

A：无

**Comment by VergilGao** [comment]
aarch64
arm
mipsel
x86_64

**Comment by mariohide** [comment]
> aarch64 arm mipsel x86_64 https://github.com/coolsnowwolf/lede/blob/master/package/lean/uugamebooster/Makefile

感谢！我查询了一下，我的路由器 cpu 架构（mips）确实不受支持。
不知道这是网易的限制还是其他什么限制呢？
