### ISSUE TITLE
Newifi D2默认配置，编辑LAN接口没有无线物理接口选择，保存后无线就关闭了

### ISSUE THREAD

**Issue by VantStark** [coolsnowwolf/lede#8259]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：Newifi D2默认配置，编辑LAN接口没有无线物理接口选择，保存后无线就关闭了，对比K2P，物理接口是有无线的

如果保存前，在自定义接口加上  "ra0 rai0"，再点击保存并应用，无线就不会关闭

![image](https://user-images.githubusercontent.com/8328013/141735800-bc5751af-7e19-44bc-b9c3-1d9f13eada4f.png)

### (2) 路由器型号和固件版本

A：Newifi D2 最新master源码编译

### (3) 详细日志

A：无

**Comment by tuzen2008** [comment]
的确，谢谢VanStark
