### ISSUE TITLE
dockerd校验码更新了

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#8265]
![71MA(9UDAH _QU)J)$G8734](https://user-images.githubusercontent.com/53508344/141979154-63ba273f-b9ba-4ec4-9f3a-6a2174588ea0.png)
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：dockerd校验码更新了，编译报错

### (2) 路由器型号和固件版本

A：x64

### (3) 详细日志

A：

**Comment by Beginner-Go** [comment]
@xiangfeidexiaohuo

**Comment by hgh188** [comment]
![image](https://user-images.githubusercontent.com/45268614/141985253-c50e8fa2-09c9-475b-9675-136a87048ab5.png)

**Comment by Beginner-Go** [comment]
在修了在修了
