### ISSUE TITLE
英特尔i350 t4 网卡兼容性问题

### ISSUE THREAD

**Issue by boshi116** [coolsnowwolf/lede#8269]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：esxi 安装虚拟机 直通i350 t4网卡   opwenert 直接卡死  连带esxi也无法访问  重启之后取消350网卡直通便没有这个问题。直通主板自带219网卡也没问题 。只要直通350网卡便无法使用。内核版本5.4.124没有这个问题。

### (2) 路由器型号和固件版本

A：x86 软路由

### (3) 详细日志

A：

**Comment by ericshunhawk** [comment]
升级esxi7.0之后 问题就能解决, 我遇到了一样的问题.

**Comment by boshi116** [comment]
> 升级esxi7.0之后 问题就能解决, 我遇到了一样的问题.

感谢  升级后解决了

**Comment by tdg2088** [comment]
想问一下你的ESXI7.0里Native igbn network driver for VMware ESXi的版本是多少？
