### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by JeremyLiu313** [coolsnowwolf/lede#8274]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：make error
树莓派4b编译失败 之前编译过新3的固件 然后也使用 rm -rf ./tmp && rm -rf .config命令了
大家帮忙看看 想知道哪里出的错 谢谢了

### (2) 路由器型号和固件版本

A：main commit 树莓派4b brm2711 

### (3) 详细日志

A：
make[5]: Leaving directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/zlib'
make[5]: Entering directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make  all-am
make[6]: Entering directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
true  DO=all multi-do # make
make[6]: Leaving directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make[5]: Leaving directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libbacktrace'
make[5]: Entering directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libcpp'
make[5]: *** No rule to make target 'all'.  Stop.
make[5]: Leaving directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/libcpp'
make[4]: *** [Makefile:6902: all-libcpp] Error 2
make[4]: Leaving directory '/home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial'
make[3]: *** [Makefile:37: /home/kk/lede/build_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/gcc-8.4.0-initial/.built] Error 2
make[3]: Leaving directory '/home/kk/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#0.13#0.00#0.12
    ERROR: toolchain/gcc/initial failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/gcc/initial/compile] Error 1
make[2]: Leaving directory '/home/kk/lede'
make[1]: *** [toolchain/Makefile:93: /home/kk/lede/staging_dir/toolchain-aarch64_cortex-a72_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/kk/lede'
make: *** [/home/kk/lede/include/toplevel.mk:230: world] Error 2

**Comment by WYC-2020** [comment]
万能大法
