### ISSUE TITLE
请求适配袋鼠云路由:dsbox-dsr1

### ISSUE THREAD

**Issue by helenpayne** [coolsnowwolf/lede#8282]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
希望支持这个机型，谢谢
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
没机子不会考虑。
