### ISSUE TITLE
装了最新Openwrt 66但是无法访问4000端口

### ISSUE THREAD

**Issue by buzzhd** [coolsnowwolf/lede#8287]
N1下安装了Openwrt66+，及其Teslamate。当访问http://ip_address::4000, 报错
This site can’t be reachedThe connection was reset.：

进入SSH后 curl，还是显示： 
curl: (56) Recv failure: Connection reset by peer

找了很多网上的posts，但都无法解决。有点说是走了proxy等，但本人小小白，不懂如何搞。看大神能否指点一下帮解决。同样N1装Armbian就可以成功访问这4000端口。所以高度怀疑这个66+固件里有不同的设定。望指教！非常感谢！

**Comment by buzzhd** [comment]
改其他端口，如40001，也是同样的报错message。

**Comment by piigggyyyy** [comment]
请问如何解决呢，N1同遇到4000无法打开，日志显示 waiting for postgres at database:5432
