### ISSUE TITLE
make 报错 recursive dependency detected

### ISSUE THREAD

**Issue by tossp** [coolsnowwolf/lede#83]
如下图，编译出来的固件可用，但是这个错误怎么修复呢
![qq 20170925122316](https://user-images.githubusercontent.com/2138631/30792367-59477ce8-a1ec-11e7-8ae7-021f090fb2cf.jpg)

**Comment by coolsnowwolf** [comment]
这个忽略即可

**Comment by uglee** [comment]
删除/mnt/sdb/lede-v17.01/package/lean/ipset-lists/Makefile里面+luci
这个属于重复引用导致报错。
