### ISSUE TITLE
编译时总是报错，不能进行下一步

### ISSUE THREAD

**Issue by SterlingCarter** [coolsnowwolf/lede#8302]
本人小白，请大神指教。
按照教程输入命令，直到第4步输入以下命令：./scripts/feeds update -a和./scripts/feeds install -a，一直出现下图报错，然后输入make menuconfig命令也不出现图形编辑界面，一直显示如下图报错信息，一直无法解决，请问大神这个问题怎么解决？导致编译无法进行，谢谢
![1637721113(1)](https://user-images.githubusercontent.com/66172871/143161658-3eb8ecdd-fc38-40d7-a71f-04f0a19693d6.jpg)
。

**Comment by WYC-2020** [comment]
这种大佬都会给你直接关闭，你怕是没进行依赖安装吧，哎伤不起，自己ytb上面就有编译步骤，自己看就懂得

**Comment by SterlingCarter** [comment]
> 这些大佬都自己给你直接关闭，你怕是没有进行依赖安装吧，哎伤不起，ytb有这样的暗示步骤，自己看就知道了

我按照步骤来的啊，第二步不就是安装依赖么？下面的图片
![image](https://user-images.githubusercontent.com/66172871/143182169-99607b2f-4378-4839-88df-a4b6972cbf50.png)

**Comment by WYC-2020** [comment]
是全新的 ubuntu 系统？还是什么，这一批安装的时候 有没报错什么之类的
