### ISSUE TITLE
WatchCat 有没有大佬修一修啊。luci界面的参数无法写入配置文件

### ISSUE THREAD

**Issue by 82kg** [coolsnowwolf/lede#8304]
配置文件改到/etc/config/watchcat了，但是 luci-app-watchcat 没有同步更新

关联此issue  #7278

**Comment by WYC-2020** [comment]
有吗？等会我看下勒

**Comment by WYC-2020** [comment]
配置写在system的

**Comment by WYC-2020** [comment]
不知道为啥这样改，后面在细看一下

**Comment by WYC-2020** [comment]
@82kg 已修复

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/143380562-fa9ed8c3-4425-41b8-96df-ff6a44e60383.png)
自己去改

**Comment by WYC-2020** [comment]
还有一个判断配置文件是否存在哪里没改，你自己改下吧，其他就没了，就改这三个地方

**Comment by xyskwjy** [comment]
> @82kg 已修复

源码修复了吗？还是手动自己修？

**Comment by WYC-2020** [comment]
肯定修复源码撒，没有提pr 自己去改 改了提pr @82kg

**Comment by xyskwjy** [comment]
> 肯定修复源码撒，没有提pr 自己去改 改了提pr @82kg

也就是大雕库里的还是没修复。。。pr一下呗

**Comment by WYC-2020** [comment]
我自己仓库改动太多，懒得pr 你自己拿去按我这个改了，你pr吧 ，还有一处改动在这里
![image](https://user-images.githubusercontent.com/34025388/143384121-7d760fa5-f582-40ff-b2cf-bc489a460d6d.png)
我测试了一下没问题，你可以可以测试一下

**Comment by WYC-2020** [comment]
@82kg

**Comment by 82kg** [comment]
> @82kg



> 谢谢大佬，明天测下试试

**Comment by 82kg** [comment]
> 我自己仓库改动太多，懒得pr 你自己拿去按我这个改了，你pr吧 ，还有一处改动在这里 ![image](https://user-images.githubusercontent.com/34025388/143384121-7d760fa5-f582-40ff-b2cf-bc489a460d6d.png) 我测试了一下没问题，你可以可以测试一下

谢谢大佬，明天测试下试试

**Comment by 82kg** [comment]
已经合并到master
