### ISSUE TITLE
像是docker-ce问题

### ISSUE THREAD

**Issue by jwkinko** [coolsnowwolf/lede#8306]
x86软路由 开机提示  
11.7152171 br-lan: port 1(eth0) entered disabled state
11.716944] device eth0 entered promiscuous Mode
13.589346] overlayfs: filesystem on
'/opt/check-overlayfs-support1688671566/
uPper
not supported as upperdir
hippot?-505616) aver laura?"/iTesystem on
*/opt/check-overlayfs-support1201687338/uPper
not supported as upperdir

内核版本5.4.161 编译通过 开机提示错误 
连客户机同一网段 luci ssh都无法登录 上不了网

**Comment by WYC-2020** [comment]
没遇到

**Comment by jwkinko** [comment]
谢谢回复，是虚拟磁盘格式错误。

**Comment by qiyuey** [comment]
@jwkinko 虚拟磁盘格式错误能具体说说是指什么吗
