### ISSUE TITLE
frps为什么显示未运行

### ISSUE THREAD

**Issue by ccc919** [coolsnowwolf/lede#8310]
已经勾选启动却显示未运行
![image](https://user-images.githubusercontent.com/33017878/143468520-e6a0cf96-4b75-4b2e-aff4-5df419bfc5af.png)

**Comment by Beginner-Go** [comment]
我看了最近一次更改，没有问题

**Comment by Beginner-Go** [comment]
fixed https://github.com/coolsnowwolf/lede/pull/8315
