### ISSUE TITLE
openwrt x86 32位uefi 没法启动

### ISSUE THREAD

**Issue by WYC-2020** [coolsnowwolf/lede#8313]
问题如题，是本身就不支持x86 32位uefi启动,还是那里有bug,请大佬指教,64位的没问题
![image](https://user-images.githubusercontent.com/34025388/143518822-49ba1dea-0851-43c1-876c-60127c977c1c.png)
备注：我是再虚拟机里面测试的，vmware

**Comment by coolsnowwolf** [comment]
32bit 不支持 EFI

**Comment by WYC-2020** [comment]
@coolsnowwolf ok确定了那就行，关闭了
