### ISSUE TITLE
dl 库下载不了 节点正常

### ISSUE THREAD

**Issue by zhiwen1987** [coolsnowwolf/lede#8337]
time: package/utils/e2fsprogs/download#0.23#0.05#0.30
make[2]: Leaving directory '/home/bl/lede/package/utils/lua'
time: package/utils/lua/download#0.18#0.05#0.24
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0mkdir -p /home/bl/lede/dl
SHELL= flock /home/bl/lede/tmp/.util-linux-2.37.tar.xz.flock -c '       /home/bl/lede/scripts/download.pl "/home/bl/lede/dl" "util-linux-2.37.tar.xz" "bd07b7e98839e0359842110525a3032fdb8eaf3a90bedde3dd1652d32d15cce5" "" "@KERNEL/linux/utils/util-linux/v2.37"    '
make[2]: Leaving directory '/home/bl/lede/package/utils/util-linux'
time: package/utils/util-linux/download#0.24#0.07#0.31
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 16 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0

**Comment by qingl812** [comment]
我也遇到了一样的问题，请问您解决了吗
