### ISSUE TITLE
请问哪里可以添加luci-app-udpxy？

### ISSUE THREAD

**Issue by ZepEthan** [coolsnowwolf/lede#8348]
另外编译的时候遇到这种错误，不知道怎么解决：

make[3]: Leaving directory '/media/zeknight/temp/openwrt/tools/bison'
time: tools/bison/compile#66.18#26.64#211.61
make[2]: Leaving directory '/media/zeknight/temp/openwrt'
make[1]: *** [tools/Makefile:162: /media/zeknight/temp/openwrt/staging_dir/host/stamp/.tools_compile_yyynyynnyyyynyyyyyynyynnyynynyyyyyyyyyyyyyyyyynynnyyyyyyyyyy] Error 2

**Comment by zhiwen1987** [comment]
我也是一样各种BUG
