### ISSUE TITLE
以后再也不追新了。。。

### ISSUE THREAD

**Issue by jxph1123** [coolsnowwolf/lede#8349]
删了

**Comment by 82kg** [comment]
> 5.4版本用了很多个，各种BUG，卡顿，搞得生不如死，特别是最近几个版本，频繁掉线，感觉5以上版本就是妥妥的负优化。。 今天实在受不了，重新编译了4.14的稳定版。这下世界清净了，连开luci都是瞬开，负载也低，BUG也很少，心情一下舒畅了。。。 所以合适自己的才是最好的，不一定要追新。

4.14在哪里

**Comment by WYC-2020** [comment]
尝鲜就要有尝鲜的代价，哪有这么多抱怨的

**Comment by WYC-2020** [comment]
负优化？别人大佬辛辛苦苦做，没得到肯定还被你这样说，让别人情何以堪
