### ISSUE TITLE
希望不要默认集成dockerman，op docker就是邪教。

### ISSUE THREAD

**Issue by Junpenchen** [coolsnowwolf/lede#8358]

**Comment by WYC-2020** [comment]
你不编译就行了

**Comment by xiechangan123** [comment]
我也发现固件变大了不少。。。虽然我是x86

**Comment by xeyesen** [comment]
为什么docker都没有选了，升级完，接口那边还有一个docker，不想要这个东西

**Comment by realJustinLee** [comment]
> 你不编译就行了

默认加入dockerman，弄好大家端口转发一起死对吧？

**Comment by EnnawYang** [comment]
> > 你不编译就行了
> 
> 默认加入dockerman，弄好大家端口转发一起死对吧？

没问题啊，你不编译进去不就行了？
