### ISSUE TITLE
luci 21.02 首页型号显示异常

### ISSUE THREAD

**Issue by VergilGao** [coolsnowwolf/lede#8361]
![image](https://user-images.githubusercontent.com/8655163/144054626-729fc91b-dbb7-41e3-a6d9-2505cfce19a9.png)
型号那一栏显示的是Default string Default string

虽然我用的是官方的源码和官方的luci分支，但是我这个问题已经找了好久都没有找到解决方案，所以在这里想求助一下，有没有人了解这个型号的取值依据是什么，是不是我缺少了哪个依赖导致这里显示的这个值。

**Comment by j999yp** [comment]
可以借楼问下怎么用21.02的sdk编译lean的软件包吗

**Comment by j999yp** [comment]
> 

感谢回复

**Comment by VergilGao** [comment]
知道了，是主板本来也没提供电脑型号信息
