### ISSUE TITLE
ssplus 里 强制设置指定的域名走代理如何设置？

### ISSUE THREAD

**Issue by jeasonliang** [coolsnowwolf/lede#8365]
![image](https://user-images.githubusercontent.com/27670071/144184064-9a482d23-1bbb-4477-929c-683e9d430b38.png)
域名之间是否需要加英文，号
域名是否要加通配符？例如*.live.com
![image](https://user-images.githubusercontent.com/27670071/144184333-ba41f914-1def-4ef2-8cd3-1bbe765deb84.png)
折腾半天没效果 ！有没有知道的指点一下

**Comment by deplives** [comment]
提问错地方了吧

**Comment by WYC-2020** [comment]
瞎搞
