### ISSUE TITLE
麻烦大佬更新下r8125 的网卡驱动

### ISSUE THREAD

**Issue by suizhenmin** [coolsnowwolf/lede#8366]
螃蟹发布了新版驱动 9.007.01新版驱动，https://www.realtek.com/zh/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software 麻烦大佬更新下

**Comment by wi11iamzhao** [comment]
当前版本应该是9.006.04
https://github.com/coolsnowwolf/lede/commit/658c2f10bcee190ccfe3aac6381cd5359bae716f

**Comment by suizhenmin** [comment]
> 当前版本应该是9.006.04 [658c2f1](https://github.com/coolsnowwolf/lede/commit/658c2f10bcee190ccfe3aac6381cd5359bae716f)
![111111](https://user-images.githubusercontent.com/2957364/144341325-a08e37a4-3b2c-416a-a5f8-1b45b61c1b06.png)

**Comment by AmadeusGhost** [comment]
试试这个：https://github.com/AmadeusGhost/lede/commit/b70ca9a922c83b3d18e047975d98f8fe7ef230be
