### ISSUE TITLE
跪求大佬把luci升级到21.02版

### ISSUE THREAD

**Issue by lzhiye** [coolsnowwolf/lede#8372]
大佬集成的luci依然是18.06版的。。。什么时候才能升级到21.02版啊，体验了一下21.02版的luci，太香了

**Comment by WYC-2020** [comment]
香能有多香

**Comment by WYC-2020** [comment]
一升级一大堆ipk出问题，又噼里啪啦的扔一堆issue

**Comment by AmadeusGhost** [comment]
没有任何必要，还是旧的 18.06 好用。

**Comment by Beginner-Go** [comment]
不用期待 不可能 lua多好用

**Comment by yinzhefuyun** [comment]
你喜欢的是皮肤又不是香不香的东西

**Comment by sundaqiang** [comment]
又没人给21.02适配插件。升毛线升！

**Comment by VergilGao** [comment]
想用21.02就自己编译官方源码，想用啥插件就自己想办法给对应插件做适配。

**Comment by Neverends4** [comment]
如果你只需要passwall和SSR之类的，官方源码加个feed也可以编译成功

**Comment by xiangfeidexiaohuo** [comment]
说实话 21.02卡的要死，没觉得哪里好用。

**Comment by VergilGao** [comment]
> 说实话 21.02卡的要死，没觉得哪里好用。

我倒真没觉得卡在哪了，体感和18.06没啥区别啊，升级只是因为改用官方源编译了

**Comment by breakings** [comment]
21.02官方luci用js 18.06依然用lua

**Comment by wi11iamzhao** [comment]
目前看起来弊大于利，
不像是以前换5.4内核。
或许等到足够多的插件兼容新版本之后更合适

**Comment by r1172464137** [comment]
年少不识lua好，错把js当成宝。

**Comment by minlang112** [comment]
起码目前看来JS没有那么香
