### ISSUE TITLE
the hash of new vlmcsd version is not matching

### ISSUE THREAD

**Issue by waterun** [coolsnowwolf/lede#8379]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：最新git pull版本的vlmcsd（1113）编译时提示哈希值不匹配。。。

### (2) 路由器型号和固件版本

A：Friendly R4S，21.12.01

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
你怕是从这里下载失败https://codeload.github.com/Wind4/vlmcsd/tar.gz/svn1113?vlmcsd-svn1113.tar.gz 从另外的地方下载的，然后hash值不对吧，从这个地址下载的就是正确的 hash没错

**Comment by waterun** [comment]
> 
有可能，我手动下载试试

**Comment by WYC-2020** [comment]
是不是吗？我已经严重怀疑过了。你可以关了 @waterun
