### ISSUE TITLE
今天编译出错busybox下载失败

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#8393]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译busybox下载失败
* [ ] 没有类似的issue

### (1) 具体问题

在编译时候提示busybox下载失败

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志
![2021-12-06 15-31-45 的屏幕截图](https://user-images.githubusercontent.com/41529838/144808235-05f7ae45-ab4c-40f7-b78a-790d5d3f504a.png)
![2021-12-06 15-26-05 的屏幕截图](https://user-images.githubusercontent.com/41529838/144808256-b2e2336c-dc10-40b3-a656-b0a99db9ea7c.png)

**Comment by WYC-2020** [comment]
自己网络的问题

**Comment by dengchan0416** [comment]
我下载了很多次

**Comment by WYC-2020** [comment]
刚下载试的
![image](https://user-images.githubusercontent.com/34025388/144811249-a296b519-e1c9-4ada-9f16-0773e405979e.png)
实在不行 自己手动复制地址出来下载

**Comment by dengchan0416** [comment]
> 刚下载试的 ![image](https://user-images.githubusercontent.com/34025388/144811249-a296b519-e1c9-4ada-9f16-0773e405979e.png) 实在不行 自己手动复制地址出来下载

请问下载好了放到那个目录里

**Comment by hzjnet** [comment]
> > 刚下载试的 ![image](https://user-images.githubusercontent.com/34025388/144811249-a296b519-e1c9-4ada-9f16-0773e405979e.png) 实在不行 自己手动复制地址出来下载
> 
> 请问下载好了放到那个目录里

dl/
