### ISSUE TITLE
切换国内镜像好像错了

### ISSUE THREAD

**Issue by tossp** [coolsnowwolf/lede#84]
https://github.com/coolsnowwolf/lede/blob/287575f96c3bc33bce40fb81e4f34cca87297908/package/lean/default-settings/files/zzz-default-settings#L36

应该是`downloads.lede-project.org`换为`mirrors.ustc.edu.cn/lede`吧？

`sed -i 's/downloads.lede-project.org/mirrors.ustc.edu.cn\/lede/g'  /etc/opkg/distfeeds.conf`

**Comment by coolsnowwolf** [comment]
这个有意的，lede 官方的源挺快的，op 才需要改

**Comment by tossp** [comment]
成都还是有点慢，有时候会卡住

2017年9月26日 11:35，"coolsnowwolf" <notifications@github.com>写道：
