### ISSUE TITLE
nat回环问题

### ISSUE THREAD

**Issue by suizhenmin** [coolsnowwolf/lede#8404]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

自从编译了前面一个默认添加了 docker 的版本。删除掉重新编译，到现在内网一直无法用域名访问已经解析和转发出去的端口，只用用IP

**Comment by suizhenmin** [comment]
全新编译更新后解决。可以关闭了

**Comment by zhangj3** [comment]
自己关闭啊
