### ISSUE TITLE
今天编译了x86_64固件，刷机后，点击ssr plus+后，管理页面出错。

### ISSUE THREAD

**Issue by qiuzhongqiang** [coolsnowwolf/lede#841]
今天编译了x86_64固件，点击ssr plus+后，管理页面出错。请老大帮忙看看是什么问题？
![default](https://user-images.githubusercontent.com/13807219/48704792-6ca3e380-ec32-11e8-9e2f-3d5542708b4e.PNG)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2595087/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2595093/default.txt)

谢谢！

**Comment by cxyzzz** [comment]
恢复出厂设置可以正常使用
