### ISSUE TITLE
git clone https://github.com/coolsnowwolf/lede后的代码，menuconfig 里面没有集成的插件显示

### ISSUE THREAD

**Issue by lovelypp777** [coolsnowwolf/lede#8414]
你好，根据官网提示，udate -a  & install -a 后，menuconfig，没有看到LuCI->Application里面有集成的插件可以选择。
我是想用SSR+和NPS，
不晓得我哪里缺少了步骤，谢谢！

**Comment by minlang112** [comment]
lede只是一个openwrt的代码仓库，SSR+出门左转↓，内有添加方法（英语）
https://github.com/fw876/helloworld

**Comment by lovelypp777** [comment]
但是我看到package/lean下面已经有很多插件代码了，是默认没有被配置进去吗？

**Comment by MortalM** [comment]
这个问题比较简单，自己百度下就能查到。。  或者用paswall 
https://github.com/kenzok8/openwrt-packages
关了issue吧。 让大佬解决真正的问题
