### ISSUE TITLE
麻烦添加 OrangePi R1 Plus LTS 支持

### ISSUE THREAD

**Issue by ZMuSiShui** [coolsnowwolf/lede#8415]
麻烦添加 OrangePi R1 Plus LTS 支持

**Comment by AmadeusGhost** [comment]
我们没机子怎么支持？

**Comment by minlang112** [comment]
> 麻烦添加 OrangePi R1 Plus LTS 支持

青春版，LPDDR3内存，MAC引出的千兆口的PHY换成了YT8531C（苏州某个厂子做的），其他与Orange Pi R1 Plus的配置基本相同，你可以尝试自己添加支持，改动不大。

**Comment by ryulamp** [comment]
希望支持这个板子，价格便宜多了

**Comment by BoBppy** [comment]
这得让@1715173329 帮忙看看吧😂
