### ISSUE TITLE
ShadowsockR Plus+日志错误

### ISSUE THREAD

**Issue by jackiezhang29** [coolsnowwolf/lede#842]
大雕，更新了你最新版的ShadowsockR Plus+以后，你添加了日志功能，除了检测VPS连接问题以外，还更新了日志功能。但更新了以后，我这时常会出现以下日志代码错误。

2018/11/20 04:55:11 [Warning] [3292499077] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 69.171.65.206:443: operation was canceled dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by coolsnowwolf** [comment]
正常，TCP 被断流
