### ISSUE TITLE
Releae 21.11.11编译提示缺少auto.conf和auto.conf.cmd

### ISSUE THREAD

**Issue by lovelypp777** [coolsnowwolf/lede#8422]
编译后期提示如下信息：
make[5]: Entering directory '/home/xxx/work/openwrt/lean/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.156'
Makefile:632: include/config/auto.conf: No such file or directory
Makefile:678: include/config/auto.conf.cmd: No such file or directory
  HOSTCC  scripts/kconfig/conf.o

不过似乎编译还是成功的，不晓得会不会有什么不良影响

**Comment by WYC-2020** [comment]
我这边是5.4.162  有这两个文件

**Comment by lovelypp777** [comment]
搞好了，重新make distclean就好了，谢谢

**Comment by WYC-2020** [comment]
嗯 基本万能大法能解决很多问题 @lovelypp777

**Comment by lon91ong** [comment]
在线编译报了这个错误怎么解决, 版本是5.4.175
在线编译make distclean没什么意义吧?!
