### ISSUE TITLE
LuCI版本里面，缺少打开硬件NAT(HWNAT)的菜单项

### ISSUE THREAD

**Issue by lovelypp777** [coolsnowwolf/lede#8429]
编译了最新版本的lede和2021.11.07，里面均没有hwnat的选项

希望能够在后续的版本里面加上，谢谢！

**Comment by WYC-2020** [comment]
应该有这个？哪个op有这个可以借鉴改呗，这个应该还是底层支持才有用吧

**Comment by lovelypp777** [comment]
从18.06开始 openwrt支持了，只要硬件支持就可以
哪位弄个吗？

**Comment by WYC-2020** [comment]
感觉应该不会加，现在op上面都有一个sfe了 ，应该不会加这个，猜测的哈 ，你可以找一个有这个功能的提交，发出来看看

**Comment by AmadeusGhost** [comment]
有的，在 turboacc 里面，只支持 mtk

**Comment by Neverends4** [comment]
感觉这个功能在5.10内核没用，开了用htop看，下载带宽大时会有紫色的irq，去年的版本完全没有CPU占用
然而去年的版本开了HWNAT会随机重启
