### ISSUE TITLE
wndr4300v1 更新编译后，s-s-r plus 和ddns有冲突

### ISSUE THREAD

**Issue by Lancenas** [coolsnowwolf/lede#843]
ssr plus运行后局域网nas设置的ddns 域名无法连接，停止ssr plus运行，ddns就可以正常连接，这是什么原因造成的？是不是wan IP控制造成的？

**Comment by coolsnowwolf** [comment]
DDNS 获取IP 地址来自端口

**Comment by Lancenas** [comment]
ssr plus+和ddns冲突还是存在，ddns获取IP地址没问题，ssr plus+启动后ddns外网用获取的IP登陆内网nas失败，停止ssr plus+马上登陆正常，用v2ray pro或ssr pro时ddns一切正常。
