### ISSUE TITLE
如果可以，真心希望少改动默认的勾选项。

### ISSUE THREAD

**Issue by sundaqiang** [coolsnowwolf/lede#8431]
先是添加了dockerman，然后在删除。
真心头疼....

**Comment by XinSSS** [comment]
除了luci app下面的docker， 还有luci > collection里面取消勾选， 还有 utilities下面docker开头的全取消

**Comment by sundaqiang** [comment]
> 

我是要docker的，因为默认勾选项的问题改了几次.config。这几天又来一个runc的版本问题。
诶，还是建议搞个稳定版分支，一个月合并dev分支得了。dev爱咋提交就咋提交！！

**Comment by EnnawYang** [comment]
~~隔壁不是有稳定版么~~

**Comment by sundaqiang** [comment]
> ~隔壁不是有稳定版么~

话也不能这样说，这本质上和隔壁也算不上开发版和稳定版本的分支。
主要是有时候每天提交好几次（lede packages luci），就算是内部编译测试过也没法排除自身全部插件兼容性。
分一个月合并的分支也算不上是多麻烦的事！

**Comment by Beginner-Go** [comment]
这边建议用官方op源码 非常稳定😉

**Comment by sundaqiang** [comment]
> 这边建议用官方op源码 非常稳定😉

可以！Very good！

**Comment by NeedforGit** [comment]
> 除了luci app下面的docker， 还有luci > collection里面取消勾选， 还有 utilities下面docker开头的全取消

感谢！
