### ISSUE TITLE
编译后已经选择无线网卡型号，但是没有wpa2加密模式。请问怎么在编译时加入

### ISSUE THREAD

**Issue by noyjcl** [coolsnowwolf/lede#8442]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by AmadeusGhost** [comment]
选上 wpad
