### ISSUE TITLE
12月的代码编译后root分区占用增加100多M，那位大神知道具体增加了什么内容？

### ISSUE THREAD

**Issue by WhiteHDD** [coolsnowwolf/lede#8449]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
12月的代码编译后root分区占用增加100多M。

### (1) 具体问题

A：12月的代码编译后root分区占用增加100多M，那位大神知道具体增加了什么内容？编译配置与之前完全一样，也重新下载的所有代码，这个增量有点大，也超过了缺省160M的rom配置，11月底前编译的版本都没有这个问题。
 
### (2) 路由器型号和固件版本

A：X86 2955U

### (3) 详细日志

![Dingtalk_20211214080200](https://user-images.githubusercontent.com/95892995/146289048-0d41053a-c7f4-4796-8067-504286586cf7.jpg)

**Comment by EnnawYang** [comment]
docker？

**Comment by wi11iamzhao** [comment]
可能是因为某个commit中默认编译了docker
去掉luci-app-docker
还有luci > collection和utilities里面的

**Comment by WYC-2020** [comment]
对比一下 代码 看下makefile是不是新增了什么ipk不就知道了

**Comment by WhiteHDD** [comment]
> 可能是因为某个commit中默认编译了docker 去掉luci-app-docker 还有luci > collection和utilities里面的

已经去掉docker相关的了，docker也占不了那么多

**Comment by zorrose82** [comment]
同问，没改任何配置，11月编译固件gz大小80mb，12月编译128mb

**Comment by XinSSS** [comment]
![Snipaste_2021-12-16_22-18-38](https://user-images.githubusercontent.com/30732527/146388779-25d256e9-95b7-4244-a288-e0330b7275c8.png)

**Comment by Cathgao** [comment]
软件包搜索docker有惊喜

**Comment by WhiteHDD** [comment]
> 即使你的config没有改动， 但如果之前你的固件里没docker的话，这次是会加上去的，不只是luci>app里的docker还有luci>collection和utilities里的相关docker全部去掉再编译一遍试试看

确实不只是docker，这只占一点点。 重新对照了编译后的组件列表，>50增加，应该是版本升级后配置中缺省选上的（类似于docker），慢慢清理了，很多确实用不到的。谢谢各位

**Comment by WhiteHDD** [comment]
确实不只是docker，这只占一点点。 重新对照了编译后的组件列表，>50增加，应该是版本升级后配置中缺省选上的（类似于docker），慢慢清理了，很多确实用不到的。谢谢各位

**Comment by WYC-2020** [comment]
不可能是docker了，docker后面不是被去掉了再说一个docker没那么大

**Comment by WhiteHDD** [comment]
> 不可能是docker了，docker后面不是被去掉了再说一个docker没那么大

是的，新增加的kmod类占多数，谢谢
