### ISSUE TITLE
lean/r8152编译失败

### ISSUE THREAD

**Issue by hubumulity** [coolsnowwolf/lede#8454]

**Comment by greennyreborn** [comment]
我也同样的问题

**Comment by Beginner-Go** [comment]
把 010-compat-skb_mark_not_on_list-was-backported-since-ker.patch 这个patch删除试试

**Comment by hubumulity** [comment]
> 把 010-compat-skb_mark_not_on_list-was-backported-since-ker.patch 这个patch删除试试 在package/lean/r8152/patches里

亲测可用
