### ISSUE TITLE
INTEL I225-V 2.5G网卡大量BUG

### ISSUE THREAD

**Issue by souwei168** [coolsnowwolf/lede#8457]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：网口如果有插网线开机，些网卡无法使用
B：如果多个网卡做桥接，桥接的网卡无法使用

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by dengchan0416** [comment]
我也是遇到这个问题
