### ISSUE TITLE
./scripts/feeds install -a报错

### ISSUE THREAD

**Issue by Jack-Ywn** [coolsnowwolf/lede#8464]
### (1) 具体问题

运行 `./scripts/feeds install -a` 后有如下报错，请问下这些报错提示需要解决吗？谢谢！

### (2) 报错信息如下
![image](https://user-images.githubusercontent.com/72083949/146518904-e4018ac3-77fe-442f-89ee-8e3fbd656046.png)

**Comment by coolsnowwolf** [comment]
晚点修复，和官方同步 meson 的包目前

**Comment by Jack-Ywn** [comment]
好的，谢谢大佬
