### ISSUE TITLE
WARNING: Not overriding core package 'dnsproxy'; use -f to force

### ISSUE THREAD

**Issue by rongcenter** [coolsnowwolf/lede#8467]
xx@xx:~/lede$ ./scripts/feeds install -a
Collecting package info: package/feeds/packages/udp-broadcast-relay-redux-openwrCollecting package info: done
Collecting target info: done
Installing all packages from feed packages.
WARNING: Not overriding core package 'dnsproxy'; use -f to force
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.

**Comment by WYC-2020** [comment]
是否强制覆盖而已，忽略即可，也可以加-f进行覆盖。关闭吧
