### ISSUE TITLE
请问利用Actions编译源码，用U盘刷写固件后，lan口在电脑上显示“未识别的网络”，进不去管理页面是怎么回事呢

### ISSUE THREAD

**Issue by hubumulity** [coolsnowwolf/lede#8473]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：用U盘刷写固件后，lan口在电脑上显示“未识别的网络”，进不去管理页面

### (2) 路由器型号和固件版本

A：J1900

### (3) 详细日志

A：

**Comment by wi11iamzhao** [comment]
请确认lan口配置是否正确，特别是在默认配置的情况下

**Comment by minlang112** [comment]
个别工控板集成的是博通网卡，建议查看一下主板网卡芯片，如果是的话，加上tg3驱动
