### ISSUE TITLE
有没有计划把内核升级到 5.10.XX，现在的内核很多新硬件已经无法正常使用了！

### ISSUE THREAD

**Issue by souwei168** [coolsnowwolf/lede#8475]
有没有计划把内核升级到 5.10.XX，现在的内核很多新硬件已经无法正常使用了！

有没有计划把内核升级到 5.10.XX，现在的内核很多新硬件已经无法正常使用了！

**Comment by WYC-2020** [comment]
自己编译测试内核不就是5.10，默认内核还是5.4香，5.10有段时间默认结果一堆问题，还原到了5.4

**Comment by minlang112** [comment]
可以自己切换到5.10，但是问题比较多

**Comment by souwei168** [comment]
怎么却换






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月18日(星期六) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [coolsnowwolf/lede] 有没有计划把内核升级到 5.10.XX，现在的内核很多新硬件已经无法正常使用了！ (Issue #8475)





 
可以自己切换到5.10，但是问题比较多
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wi11iamzhao** [comment]
可以自己选择内核版本
Global build settings->Use the testing kernel version
