### ISSUE TITLE
如何才能自行添加内核

### ISSUE THREAD

**Issue by gili-gili** [coolsnowwolf/lede#8479]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：需要自行升级（添加）内核，目标是5.15.10

### (2) 路由器型号和固件版本

A：Friendly Elec. NanoPi R4S

### (3) 详细日志

A：无

官网上找到内核了，就是不知道怎么添加，下patch还是完整的，放到哪里......

**Comment by WYC-2020** [comment]
自己看下历史提交看别人怎么提的嘛

**Comment by gili-gili** [comment]
> 自己看下历史提交看别人怎么提的嘛

哪里......我连文件夹都找不到

**Comment by gili-gili** [comment]
没人解答的话过会我自己close吧，不给开发者添堵了
网上搜来搜去实在没教程（捂脸）

**Comment by gili-gili** [comment]
Closed.
