### ISSUE TITLE
反复自动重启的问题

### ISSUE THREAD

**Issue by AXBNG** [coolsnowwolf/lede#8487]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：红米AX6硬改1g内存之后，出现频繁重启的问题，少则几十分钟多则十几小时，开启了多拨，adg和smartdns，禁用了ipv6

### (2) 路由器型号和固件版本

A：红米ax6，最新源码编译固件

### (3) 详细日志

A：重启后日志丢失

**Comment by WYC-2020** [comment]
硬改，那跑不脱

**Comment by AXBNG** [comment]
> 硬改，那跑不脱

确实，但还是希望可以修复

**Comment by WYC-2020** [comment]
应该悬，你这个属于定制，谁知道以后会不会又有有硬改其他的，这个看作者了，并且这个应该是不通用的，改了你这个其他的可能又会出问题，我记得k2p原来就是硬改很凶，然后各种说问题，最终作者直接切掉了

**Comment by minlang112** [comment]
快进到删除小米（笑）

**Comment by AXBNG** [comment]
大佬已修复，感谢，关闭

**Comment by mikejing506** [comment]
楼上老哥神预言了属于是

**Comment by AXBNG** [comment]
> 楼上老哥神预言了属于是

为何要挖坟........(￢_￢)
