### ISSUE TITLE
请求默认配置sftp相关服务，finashell目前连接后没有文件夹显示

### ISSUE THREAD

**Issue by hubumulity** [coolsnowwolf/lede#8488]

**Comment by helianling** [comment]
需要安装以下两个插件:

curl -O https://downloads.openwrt.org/releases/packages-21.02/x86_64/packages/openssh-sftp-server_8.4p1-4_x86_64.ipk

curl -O https://downloads.openwrt.org/releases/packages-21.02/x86_64/packages/vsftpd_3.0.3-3_x86_64.ipk


opkg install   openssh-sftp-server_8.4p1-4_x86_64.ipk  vsftpd_3.0.3-3_x86_64.ipk


/etc/init.d/vsftpd   enable
/etc/init.d/vsftpd   start

**Comment by WYC-2020** [comment]
自己编译的时候开始openssh-server和sftp不就行了，配置文件还得改下
