### ISSUE TITLE
PHICOMM K3 V2RAY PRO 未运行

### ISSUE THREAD

**Issue by sukycqliu** [coolsnowwolf/lede#849]
![image](https://user-images.githubusercontent.com/43068779/48901506-a70abc00-ee90-11e8-8376-afbf12949a26.png)

PHICOMM K3 V2RAY PRO 未运行, 4.3以前的版本都没问题，缺少v2ctl启动不了，SSR PLUS也是一样情况。

**Comment by coolsnowwolf** [comment]
不再支持 K3 这种老旧的 ARM v6 CPU 跑 V2RAY 了

**Comment by sukycqliu** [comment]
> 不再支持 K3 这种老旧的 ARM v6 CPU 跑 V2RAY 了

K3是ARMv7吧

**Comment by clswang** [comment]
GitHub自己下载一个已经编译好的v2ray覆盖解决
