### ISSUE TITLE
最近编译的openvpn server无法启动

### ISSUE THREAD

**Issue by Roger0822** [coolsnowwolf/lede#8492]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：最新编译的openvpn server组件无法启动，主要表现为：

勾选启动，但没启动。
整个路由器重启后，显示有相关进程，并显示已启动，但看上去是死进程，无法使用；无法关闭。

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Beginner-Go** [comment]
有tg吗？

**Comment by Roger0822** [comment]
> 有tg吗？

@Roger0822

**Comment by Beginner-Go** [comment]
这是tg 用户名？

**Comment by Roger0822** [comment]
> 这是tg 用户名？

不好意思TG用的少，要不我➕你。谢谢

**Comment by poromony** [comment]
> > 这是tg 用户名？
> 
> 不好意思TG用的少，要不我➕你。谢谢

请问解决了吗？遇到了同样的问题

**Comment by poromony** [comment]
ssh终端中输入并回车： service openvpn restart

**Comment by coffee0818** [comment]
> ssh终端中输入并回车： service openvpn restart

感谢，确实解决了，但是根本原因是什么呢？
