### ISSUE TITLE
x64 squashfs 在esxi上启动不起来

### ISSUE THREAD

**Issue by muziling** [coolsnowwolf/lede#85]
编译选项target image有星号选中了vmdk  
编译好的bin下有100多兆的img文件和一个8M多的vmdk文件， 
把100多兆的img文件用StarWind V2V Image Converter转换成esxi的格式，在esxi上启动卡住，控制台日志为：
 rootdisk overlay filesystem has not been formatted yet

**Comment by coolsnowwolf** [comment]
第一次启动是选择单核就好了。。。。貌似是上游代码的问题，原因未知

或者用 ext4 格式

**Comment by waterun** [comment]
官方snapshot也一样，所以不是大雕问题，经测试，VMware平台由此问题，hyperv下会自动格式化

**Comment by tanpengsccd** [comment]
最新提交 https://github.com/coolsnowwolf/lede/commit/65b25ceb18d40d9de26d3aac5697a922b68a936f
ext4 也不行，squashfs 用 StarWind V2V Image Converter 转换成 openwrt-x86-64-combined-squashfs.vmdk 也不能启动了
![image](https://user-images.githubusercontent.com/13959880/65816768-5ee7c300-e232-11e9-98c1-5b9a669e224a.png)
