### ISSUE TITLE
nss-dp 导致新建wan口无法正常拨号

### ISSUE THREAD

**Issue by L-vivi** [coolsnowwolf/lede#8500]
## 1.nss-dp 导致新建wan口无法正常拨号

* [x ] 没有类似的issue

### (1) 具体问题

新建wan2口绑定至eth1或者eth2或者eth3网口，始终无法正常拨号
临时解决办法，启动项-关闭qca-nss-ecm，重启路由器，wan2口拨号成功
但是运营商每7天会强制重新拨号一次，这时就无法成功拨号

### (2) 路由器型号和固件版本

路由器型号：AX6
固件版本号：OpenWrt R21.12.1 / LuCI Master (git-21.335.48743-5f363d9)

### (3) 详细日志
[  352.461178] br-wan2: port 1(eth1) entered disabled state
[  352.461760] device eth1 left promiscuous mode
[  352.465764] br-wan2: port 1(eth1) entered disabled state
[  352.489607] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  355.748430] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000
[  370.946973] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  374.056488] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000
[  389.253825] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  392.356544] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000
[  407.543165] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  410.664609] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000
[  425.850741] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  428.964631] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000
[  444.139550] nss-dp 3a001400.dp3 eth1: PHY Link is down
[  447.240673] nss-dp 3a001400.dp3 eth1: PHY Link up speed: 1000

**Comment by XiaoliChan** [comment]
NSS is still buggy in this source code, you can try to use my firmware.
Link: https://www.right.com.cn/forum/thread-6057881-1-1.html
