### ISSUE TITLE
turboacc提示缺少依赖dnsproxy

### ISSUE THREAD

**Issue by Dimitri2020007** [coolsnowwolf/lede#8507]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：更新并安装feeds时出现的，会影响编译吗？

### (2) 路由器型号和固件版本

A：x86_64-efi

### (3) 详细日志

A：

 ./scripts/feeds install -a
Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/lean/luci-app-turboacc/Makefile' has a dependency on 'dnsproxy', which does not exist
Installing all packages from feed packages.
Installing package 'dnsproxy' from packages
Installing package 'geoipupdate' from packages
Installing package 'mosdns' from packages
Installing package 'php8-pecl-dio' from packages
Installing package 'php8-pecl-http' from packages
Installing package 'php8-pecl-raphf' from packages
Installing package 'php8-pecl-imagick' from packages
Installing package 'php8-pecl-krb5' from packages
Installing package 'php8-pecl-mcrypt' from packages
Installing package 'php8-pecl-redis' from packages
Installing package 'php8-pecl-sodium' from packages
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed lienol.
WARNING: Not overriding core package 'luci-app-guest-wifi'; use -f to force
WARNING: Not overriding core package 'luci-app-kodexplorer'; use -f to force
WARNING: Not overriding core package 'luci-app-pppoe-relay'; use -f to force
WARNING: Not overriding core package 'luci-app-pptp-server'; use -f to force
WARNING: Not overriding core package 'luci-app-ramfree'; use -f to force
WARNING: Not overriding core package 'luci-app-softethervpn'; use -f to force
WARNING: Not overriding core package 'luci-app-verysync'; use -f to force
WARNING: Not overriding core package 'verysync'; use -f to force
Installing all packages from feed passwall.
WARNING: Not overriding core package 'dns2socks'; use -f to force
WARNING: Not overriding core package 'ipt2socks'; use -f to force
WARNING: Not overriding core package 'microsocks'; use -f to force
WARNING: Not overriding core package 'pdnsd-alt'; use -f to force
Installing package 'v2ray-geodata' from passwall
Installing all packages from feed helloworld.
Installing package 'v2raya' from helloworld

**Comment by zorrose82** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ ]  没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> A：更新并安装feeds时出现的，会影响编译吗？
> 
> ### (2) 路由器型号和固件版本
> A：x86_64-efi
> 
> ### (3) 详细日志
> A：
> 
> ./scripts/feeds install -a Collecting package info: done Collecting target info: done WARNING: Makefile 'package/lean/luci-app-turboacc/Makefile' has a dependency on 'dnsproxy', which does not exist Installing all packages from feed packages. Installing package 'dnsproxy' from packages Installing package 'geoipupdate' from packages Installing package 'mosdns' from packages Installing package 'php8-pecl-dio' from packages Installing package 'php8-pecl-http' from packages Installing package 'php8-pecl-raphf' from packages Installing package 'php8-pecl-imagick' from packages Installing package 'php8-pecl-krb5' from packages Installing package 'php8-pecl-mcrypt' from packages Installing package 'php8-pecl-redis' from packages Installing package 'php8-pecl-sodium' from packages Installing all packages from feed luci. Installing all packages from feed routing. Installing all packages from feed telephony. Installing all packages from feed lienol. WARNING: Not overriding core package 'luci-app-guest-wifi'; use -f to force WARNING: Not overriding core package 'luci-app-kodexplorer'; use -f to force WARNING: Not overriding core package 'luci-app-pppoe-relay'; use -f to force WARNING: Not overriding core package 'luci-app-pptp-server'; use -f to force WARNING: Not overriding core package 'luci-app-ramfree'; use -f to force WARNING: Not overriding core package 'luci-app-softethervpn'; use -f to force WARNING: Not overriding core package 'luci-app-verysync'; use -f to force WARNING: Not overriding core package 'verysync'; use -f to force Installing all packages from feed passwall. WARNING: Not overriding core package 'dns2socks'; use -f to force WARNING: Not overriding core package 'ipt2socks'; use -f to force WARNING: Not overriding core package 'microsocks'; use -f to force WARNING: Not overriding core package 'pdnsd-alt'; use -f to force Installing package 'v2ray-geodata' from passwall Installing all packages from feed helloworld. Installing package 'v2raya' from helloworld

./scripts/feeds install -af
