### ISSUE TITLE
连结家中WIFI之后，访问家中NAS只能通过家中局域网IP，不能使用域名；在外部网络（手机热点）可以通过域名访问NAS

### ISSUE THREAD

**Issue by felixxiao99** [coolsnowwolf/lede#8508]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：使用最新固件，连结家中WIFI之后，访问家中NAS只能通过家中局域网IP，不能使用域名；在外部网络（手机热点）可以通过域名访问NAS；

### (2) 路由器型号和固件版本

A：X86    OpenWrt R21.12.1  / LuCI Master (git-21.335.48743-5f363d9)

### (3) 详细日志

A：

**Comment by jimgo188** [comment]
编译了docker进去的原因吧~

**Comment by felixxiao99** [comment]
@jimgo188 没有编译docker

**Comment by 990052053** [comment]
把acc加速全部关掉就好了

**Comment by EnnawYang** [comment]
取消重绑定保护试试

**Comment by poromony** [comment]
在 网络→DHCP/DNS→常规设置 中，关闭“重绑定保护”或者把你的域名加入白名单
