### ISSUE TITLE
netdata v1.31.0有问题 希望能换回1.30.1

### ISSUE THREAD

**Issue by Saber9361** [coolsnowwolf/lede#8509]
12月23日最新固件 1.31没有图表显示 手动从luci卸载并下载官方v1.30.1后恢复 希望能将编译源中改为此版本

**Comment by Beginner-Go** [comment]
先忍一阵子，看看以后更新会不会修复

**Comment by Saber9361** [comment]
没问题 仅发此贴做反馈 目前在luci界面手动卸载后从官方库安装v1.30.1后再补齐luci-app和i18n可以正常使用
