### ISSUE TITLE
总是编译错误 

### ISSUE THREAD

**Issue by kistonw** [coolsnowwolf/lede#852]
执行make V=s -j1后 跳出openwrt配置界面 然后设置好了 exit 就出现提示
make[2]: *** No rule to make target '.config', needed by '/root/lede/staging_dir/target-_/stamp/.target_prereq'.  Stop.
/root/lede/include/toplevel.mk:196: recipe for target 'prereq' failed
make[1]: *** [prereq] Error 2
/root/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by jovishow** [comment]
拉取最新的代码也卡在这儿了

**Comment by jovishow** [comment]
环境问题，已解决，mac还是不行，还得Ubuntu
