### ISSUE TITLE
ffmpeg编译失败 为歌华链编译的

### ISSUE THREAD

**Issue by ashesofdream** [coolsnowwolf/lede#8529]
报错日志如下
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_fetch_sub_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_store_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_load_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:124: ffprobe_g] Error 1
make[4]: *** Waiting for unfinished jobs....
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_fetch_sub_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_store_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_load_8'
....../lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: libavformat/libavformat.so: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:124: ffmpeg_g] Error 1

**Comment by wuzhuang123** [comment]
网上说要链接到atomic库，我修改了makefile也不行
