### ISSUE TITLE
openwrt做主路由，外网无法通过openwrt端口转发连接内网的l2tp/ipsec vpn服务器

### ISSUE THREAD

**Issue by bonnyandsky** [coolsnowwolf/lede#8530]
搜索了各种 都没有类似案例
具体情况如下：
j4125的x86平台openwrt做主路由器，内网有一台群晖部署了l2tp/ipsec的vpn服务
openwrt已经做了端口转发和防火墙端口放行设置。见下图：
端口转发
![1](https://user-images.githubusercontent.com/30990861/147478267-05a560e7-2cd9-4912-8a15-b60d66827a64.png)
端口放行
![2](https://user-images.githubusercontent.com/30990861/147478270-96dac43b-7c1d-4ac2-ad64-9067cee0652a.png)
使用手机作为客户端，在局域网连接openwrt拨号的公网ip，可以连上群晖的vpn服务。具体如下 ：
openwrt拨号得到公网ip：116.237.253.101
![5](https://user-images.githubusercontent.com/30990861/147478424-25a9fb89-d4ef-4f02-b8b4-25b0c90b7918.png)
安卓手机设置vpn服务器地址ip：116.237.253.101
![3](https://user-images.githubusercontent.com/30990861/147478494-0917300d-bdd8-4ad9-a288-a3e266203fc7.jpg)
手机在局域网内，连接群晖vpn服务器成功
![4](https://user-images.githubusercontent.com/30990861/147478531-54243abf-be92-4730-abb5-194676d13d9c.jpg)
手机使用5g网络，在外网连接群晖服务器失败
![6](https://user-images.githubusercontent.com/30990861/147478576-486af773-e53e-4550-872a-3d207403168f.jpg)
因为在19年发生过设置了端口转发，实际会有部分端口转发失败的经历。当时在防火墙--自定义规则--内设置下面内容：
iptables -t nat -I PREROUTING -i pppoe-wan -p udp --dport 1701 -j DNAT --to-destination 192.168.0.100:1701
iptables -t nat -I PREROUTING -i pppoe-wan -p udp --dport 500 -j DNAT --to-destination 192.168.0.100:500
iptables -t nat -I PREROUTING -i pppoe-wan -p udp --dport 4500 -j DNAT --to-destination 192.168.0.100:4500
重启op后是可以正常连接群晖上的vpn服务器的。
但是这次设置后，问题依然无法解决。

**Comment by Wilson-coder** [comment]
我用的是Zerotier，没有配置L2TP/IPSec。你自己看一下这个帖子：https://serverfault.com/questions/451381/which-ports-for-ipsec-lt2p

**Comment by bonnyandsky** [comment]
> 我用的是Zerotier，没有配置L2TP/IPSec。你自己看一下这个帖子：https://serverfault.com/questions/451381/which-ports-for-ipsec-lt2p

谢谢，之所以用l2tp是因为windows自带客户端。这样我就不需要额外安装软件了。在任何一台电脑上设置下就可以连接到家里的vpn使用了

**Comment by bonnyandsky** [comment]
经过大佬指点，问题解决了。是加速的问题，SFE关闭就可以连上了。
