### ISSUE TITLE
5.15 内核缺少 mmc_spi.ko 

### ISSUE THREAD

**Issue by sunshineyxc** [coolsnowwolf/lede#8544]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：5.15 内核缺少 mmc_spi.ko 

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：Package kmod-mmc-spi is missing dependencies for the following libraries:
of_mmc_spi.ko
make[3]: *** [modules/spi.mk:27: /home/yxc/lede/bin/targets/x86/64/packages/kmod-mmc-spi_5.15.10-1_x86_64.ipk] Error 1
make[3]: Leaving directory '/home/yxc/lede/package/kernel/linux'
time: package/kernel/linux/compile#2.04#0.19#2.36
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1

**Comment by coolsnowwolf** [comment]
不再需要
