### ISSUE TITLE
dnsfowarder无法启动

### ISSUE THREAD

**Issue by madcat0513** [coolsnowwolf/lede#855]
已git pull到最新 r7800
root@OpenWrt:/# /etc/init.d/dnsforwarder enable
': No such file or directory.common
root@OpenWrt:/# /etc/init.d/dnsforwarder start
': No such file or directory.common
root@OpenWrt:/# /etc/init.d/dnsforwarder restart
': No such file or directory.common
脚本貌似有问题

**Comment by yjnomm** [comment]
我也是这么个情况，和你同一个型号。刚添加dnsfowarder的时候，我就编译出来了，一直显示已禁用，没办法开启。

**Comment by hcym** [comment]
还没用过，也编译用用看看

**Comment by lan542662** [comment]
我也是 R7800 大屌优化的不错

hcym <notifications@github.com> 于2018年11月25日周日 下午10:37写道：
