### ISSUE TITLE
q10pro固件刷机无限重启

### ISSUE THREAD

**Issue by iowclz** [coolsnowwolf/lede#8550]
q10pro固件pb-boot刷机无限重启，breed刷机也是无限重启，刷u-boot固件交换机异常

**Comment by AmadeusGhost** [comment]
你刷了 cr660x 的 pbboot 那只能选 uboot mod 那个型号了。

**Comment by iowclz** [comment]
> 你刷了 cr660x 的 pbboot 那只能选 uboot mod 那个型号了。

刷了uboot-mod,网口获取不到IP了

**Comment by iowclz** [comment]
更换到5.4内核成功,5.10有线网口异常
