### ISSUE TITLE
5.10 内核编译luci 里面找不到wireguard

### ISSUE THREAD

**Issue by Actuallymax** [coolsnowwolf/lede#8561]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述

A：5.10 内核编译luci 里面找不到wireguard，编译完成以后添加网络接口里面也没有wireguard vpn协议

### (2) 路由器型号和固件版本

A：软路由x86

**Comment by lonelysoul** [comment]
是的，我也找不到了，想编译都没有啦。

**Comment by lonelysoul** [comment]
CONFIG_DEFAULT_luci-app-wireguard=y
配置文件里包含，luci里找不到。

**Comment by coolsnowwolf** [comment]
已修复
