### ISSUE TITLE
使用Github Actions编译的固件如何用内核版本号命名

### ISSUE THREAD

**Issue by lon91ong** [coolsnowwolf/lede#8563]
编译脚本参考[P3TERX大侠的项目](https://github.com/P3TERX/Actions-OpenWrt)
目前编译的固件只有刷入后才能知道内核版本号
有没有办法编译完后在文件名中加入内核版本号呢?

**Comment by Jason6111** [comment]
![D7E61EDF-CA6E-433F-814C-B6BA55BA31CA](https://user-images.githubusercontent.com/43496459/147848787-9f86ab20-8318-4e22-8898-885ad26de29e.png)
tag改下名称不就得了

**Comment by kleisth** [comment]
云编译的我不知道，我本地编译的直接改image.mk的IMG_PREFIX那里，加个$(LINUX_VERSION)就行了。。。随便还加了个时间显示。

**Comment by Jason6111** [comment]
在脚本中发布固件用mv重命名下也可以 哈哈哈

**Comment by Jason6111** [comment]
![A587BA40-F65A-4D47-8BD5-AC6C4209CAD0](https://user-images.githubusercontent.com/43496459/147924931-da639699-98cf-4b39-9b24-7577ba65f43e.png)
![42B41CEB-5E2A-42C8-A952-B10E4B401029](https://user-images.githubusercontent.com/43496459/147924941-9e6c8b50-9fc1-4816-aa5d-c7680a675159.png)
mv a b 就可以

**Comment by binge8** [comment]
看我的actions编译的重命名效果
https://github.com/binge8/op/releases
![1641257508(1)](https://user-images.githubusercontent.com/53508344/147995645-cd69690f-9712-4179-a423-5df40b01d0c1.png)
只需修改这一个地方。

**Comment by lon91ong** [comment]
参考 @kleisth 大佬的建议, 最后使用下面的方案解决:
`sed -i ':a;N;$!ba;s/$(BOARD)/&-$(LINUX_VERSION)/1' include/image.mk`
