### ISSUE TITLE
关于feed添加第三方源的问题

### ISSUE THREAD

**Issue by Ra2-IFV** [coolsnowwolf/lede#8565]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：我在feeds.conf.default添加了第三方github仓库，但是在镜像中被自动改成了腾讯云的源，导致不注释掉相关行就更新源会导致错误。我想要在编译时进行更改，应该怎么做？

**Comment by Actuallymax** [comment]
同样遇到这个问题

**Comment by lxl6125** [comment]
Image configuration  ---> Separate feed repositories

**Comment by Ra2-IFV** [comment]
> Image configuration ---> Separate feed repositories

不显示我的自定义源

**Comment by Ra2-IFV** [comment]
> Image configuration ---> Separate feed repositories

不知道为啥又可以了......谢谢
