### ISSUE TITLE
openwrt中没有的内核模块，可以直接把其他Linux的内核模块移植过来编译进openwrt中吗？

### ISSUE THREAD

**Issue by hcjjmt** [coolsnowwolf/lede#8570]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
已经这么做了

**Comment by AmadeusGhost** [comment]
你想表达什么？？？只言片语让算命还是？
