### ISSUE TITLE
小米ax3600编译报错-fatal error: ipq8074-ess.dtsi: No such file or directory

### ISSUE THREAD

**Issue by zcluo** [coolsnowwolf/lede#8574]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述
 gcc -E -Wp,-MMD,arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -x assembler-with-cpp -o arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.dts.tmp arch/arm64/boot/dts/qcom/ipq8072-301w.dts ; ./scripts/dtc/dtc -O dtb -o arch/arm64/boot/dts/qcom/ipq8072-301w.dtb -b 0 -iarch/arm64/boot/dts/qcom/ -i./scripts/dtc/include-prefixes -Wno-interrupt_provider -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-simple_bus_reg -Wno-unique_unit_address -Wno-pci_device_reg  -d arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.dtc.tmp arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.dts.tmp ; cat arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.pre.tmp arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.dtc.tmp > arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d
arch/arm64/boot/dts/qcom/ipq8072-301w.dts:8:10: fatal error: ipq8074-ess.dtsi: No such file or directory
    8 | #include "ipq8074-ess.dtsi"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[7]: *** [scripts/Makefile.lib:326: arch/arm64/boot/dts/qcom/ipq8072-301w.dtb] Error 1
make[6]: *** [scripts/Makefile.build:497: arch/arm64/boot/dts/qcom] Error 2

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
小米AX3600
A：

### (3) 详细日志

A：
 gcc -E -Wp,-MMD,arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -x assembler-with-cpp -o arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.dts.tmp arch/arm64/boot/dts/qcom/ipq8072-301w.dts ; ./scripts/dtc/dtc -O dtb -o arch/arm64/boot/dts/qcom/ipq8072-301w.dtb -b 0 -iarch/arm64/boot/dts/qcom/ -i./scripts/dtc/include-prefixes -Wno-interrupt_provider -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-simple_bus_reg -Wno-unique_unit_address -Wno-pci_device_reg  -d arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.dtc.tmp arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.dts.tmp ; cat arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.pre.tmp arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d.dtc.tmp > arch/arm64/boot/dts/qcom/.ipq8072-301w.dtb.d
arch/arm64/boot/dts/qcom/ipq8072-301w.dts:8:10: fatal error: ipq8074-ess.dtsi: No such file or directory
    8 | #include "ipq8074-ess.dtsi"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[7]: *** [scripts/Makefile.lib:326: arch/arm64/boot/dts/qcom/ipq8072-301w.dtb] Error 1
make[6]: *** [scripts/Makefile.build:497: arch/arm64/boot/dts/qcom] Error 2

**Comment by coolsnowwolf** [comment]
fixed
