### ISSUE TITLE
新编译的固件，启动后内存迅速耗尽，然后系统崩溃

### ISSUE THREAD

**Issue by goodhui** [coolsnowwolf/lede#8577]
反馈bug/问题模板，提建议请删除

具体问题
从1月1日开始新编译的固件，启动后内存迅速耗尽，然后系统崩溃，make clean和完全删除重新编译后都 是同样的问题，

### (2) 路由器型号和固件版本

A：hyper下，计算机CPU I5 10600T

**Comment by loryncien** [comment]
我的也一样情况，配置文件不变，action云编译，最新编译文件 x86_64 k5.4 ，群晖虚拟机测试时，内存掉的很快，最后卡死，上次12月16左右编译的没问题

**Comment by zhaoxp520** [comment]
看来有这个问题的不止我一个
不知道是不是什么插件问题

**Comment by loryncien** [comment]
> 看来有这个问题的不止我一个 不知道是不是什么插件问题

我是缝合的，我也认为大概率是某个插件的导致的，等过段时间在编译试试，还不行的话，再一一排查。
