### ISSUE TITLE
ARM系统编译依赖无法安装

### ISSUE THREAD

**Issue by Luastonsu** [coolsnowwolf/lede#8581]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
Ubuntu无法安装编译所需依赖。
MacBook Air (M1,2020)通过Parallels Desktop 安装ARM版本Ubuntu系统，已经更换国内源，无法安装所需依赖。
详细：
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
注意，选中 'zlib1g-dev' 而非 'libz-dev'
注意，选中 'git' 而非 'git-core'
注意，选中 'upx-ucl' 而非 'upx'
没有可用的软件包 gcc-multilib，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

E: 无法定位软件包 lib32gcc1
E: 无法定位软件包 libc6-dev-i386
E: 软件包 gcc-multilib 没有可安装候选
E: 无法定位软件包 g++-multilib
E: 无法按照正则表达式 g++-multilib 找到任何软件包

**Comment by hzjnet** [comment]
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [x]  没有类似的issue
> 
> ## 2. 详细叙述
> Ubuntu无法安装编译所需依赖。 MacBook Air (M1,2020)通过Parallels Desktop 安装ARM版本Ubuntu系统，已经更换国内源，无法安装所需依赖。 详细： sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync 正在读取软件包列表... 完成 正在分析软件包的依赖关系树 正在读取状态信息... 完成 注意，选中 'zlib1g-dev' 而非 'libz-dev' 注意，选中 'git' 而非 'git-core' 注意，选中 'upx-ucl' 而非 'upx' 没有可用的软件包 gcc-multilib，但是它被其它的软件包引用了。 这可能意味着这个缺失的软件包可能已被废弃， 或者只能在其他发布源中找到
> 
> E: 无法定位软件包 lib32gcc1 E: 无法定位软件包 libc6-dev-i386 E: 软件包 gcc-multilib 没有可安装候选 E: 无法定位软件包 g++-multilib E: 无法按照正则表达式 g++-multilib 找到任何软件包

这么明显的提示啊 依照提示安装即可
