### ISSUE TITLE
RT-ACRH17以任意配置编译刷入后重启就丢失全部设置

### ISSUE THREAD

**Issue by maidmeow4** [coolsnowwolf/lede#8591]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

华硕 RT-ACRH17 使用最新源码编译并刷入后，路由器重启就丢失全部设置

### (2) 路由器型号和固件版本

华硕 RT-ACRH17 使用最新源码编译

### (3) 详细日志

无

**Comment by dysl357085918** [comment]
看看软件包里面可用空间多少，可能是固件太大了吧。

**Comment by maidmeow4** [comment]
@dysl357085918
71% (85.77 MB)，这是以机型默认 `.config` 编译刷入的，也有丢失设置的问题

**Comment by maidmeow4** [comment]
Solved.
Flashed `initramfs` format instead of `squashfs` format. 🤣
