### ISSUE TITLE
x64 515 ntfs3报错无法使用

### ISSUE THREAD

**Issue by xinxijishuwyq** [coolsnowwolf/lede#8600]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：无法启动

### (2) 路由器型号和固件版本

A：vmware软路由

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/1755898/148075630-fc12949c-f112-419f-90e7-f2e7797f4cd3.png)

ntfs3: Unknown parameter 'nls'

**Comment by flyhong666** [comment]
相关依赖包没选上？我的不会报错，但是共享有问题。。。

**Comment by xinxijishuwyq** [comment]
问题依旧

**Comment by flyhong666** [comment]
> 问题依旧

如果那个更新不行的话，那就别折腾5.15内核的了。。。
