### ISSUE TITLE
最新编译5.10  5.15挂在磁盘问题

### ISSUE THREAD

**Issue by nb12nb34** [coolsnowwolf/lede#8609]
5.10不能挂在磁盘，重启后设置不能保存，5.15利用挂载点可以保存，磁盘工具还是不能！求解

**Comment by WYC-2020** [comment]
磁盘工具那是一个什么鬼

**Comment by nb12nb34** [comment]
就是磁盘管理。。 手机操作的，打错了

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/lede/commit/c2690c17b1e16514ae0148d5b904cf70f843c6f0
