### ISSUE TITLE
ssr-plus+下速度偏慢的问题

### ISSUE THREAD

**Issue by iamggs** [coolsnowwolf/lede#861]
宿主机：群晖DS918+
虚拟机：群晖VMM套件，网卡模式virtio
OpenWrt固件：最新编译的coolsnowwolf固件+ssr-plus+和另外一个第三方固件+ssr插件
VPS线路：Google
现象：同一个YouTube源下，前者环境connect speed显示只有7000左右，切无法播放4k视频；后者40000+，4k流畅可随意拖放。

问题：是ssr-plus+有啥特殊的设置么？还是说网卡驱动问题？为这事儿已经连续几天编译了多次，还是没解决问题，望指教，感谢感谢。

**Comment by tinnlux** [comment]
我也有这个问题啊。为什么关闭问题了。

**Comment by mylukin** [comment]
确实很慢，目前没找到原因。
