### ISSUE TITLE
源码同步到最新，X86固件启动后不停循环 ntfs3: unknown parameter 'nls' 

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#8612]
X86版本
5.15内核
不知是否ntfs3-mount的问题？
暂时把automount退回到 [automount: revert to antfs-mount for 5.4/5.10](https://github.com/coolsnowwolf/lede/commit/1bf58b7e182f9b21da79fb3789c3204010adf219) 后启动正常

**Comment by WYC-2020** [comment]
我已经修复了明天给你们patch

**Comment by mitsukileung** [comment]
> 我已经修复了明天给你们patch

多谢大佬！！！

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/lede/commit/c2690c17b1e16514ae0148d5b904cf70f843c6f0

**Comment by mitsukileung** [comment]
> [WYC-2020/lede@c2690c1](https://github.com/WYC-2020/lede/commit/c2690c17b1e16514ae0148d5b904cf70f843c6f0)

可以了，谢谢
