### ISSUE TITLE
关于ssh爆破问题的咨询

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#8635]
Hi team，

最近一段时间，总是在后台日志中看到ssh爆破的信息
![image](https://user-images.githubusercontent.com/25215114/148504557-9df7ace7-ab30-435d-83cd-61c0adace0bb.png)

我查了下，网上有些脚本来自动添加防火墙策略的

我想问下，有没有想关的插件或者工具能帮助更加优雅高效的解决这个问题

BR
Robin

**Comment by EnnawYang** [comment]
![Snipaste_2022-01-07_15-04-18](https://user-images.githubusercontent.com/6705663/148505274-d0ce919d-347a-41af-8fdf-6d7ae51a29b8.png)
![Snipaste_2022-01-07_15-03-45](https://user-images.githubusercontent.com/6705663/148505280-184878d6-ac91-4832-8ed3-c19fc555c3db.png)

**Comment by avsba001** [comment]
fail2ban

**Comment by Guxing0321** [comment]
Hi. EnnawYang,

我这边跟你配置是一样的
![image](https://user-images.githubusercontent.com/25215114/148505783-fc8c3b38-a8fe-4c4e-bf2b-b9264263f2c3.png)

![image](https://user-images.githubusercontent.com/25215114/148505820-eac8d253-3880-48de-bfe2-b2d19ee176b3.png)

我用了ddns，加了一个端口转发，我现在不确定是那边爆破的我22号端口，还是10022端口

![image](https://user-images.githubusercontent.com/25215114/148505954-5cd61f14-b2af-4b9e-b0b0-41dc7bfd9ab3.png)



BR
Robin

**Comment by Guxing0321** [comment]
Hi avsba001

好的，我来研究下 fail2ban相关，谢谢哈


BR
Robin

**Comment by EnnawYang** [comment]
> 
> 我用了ddns，加了一个端口转发，我现在不确定是那边爆破的我22号端口，还是10022端口
> 
> BR Robin

从wan10022访问内网机器的22端口，反正是暴露在公网下的，你可以试下楼上推荐的工具，但我没用过，不过不建议把重要端口暴露出去

**Comment by Guxing0321** [comment]
> > 我用了ddns，加了一个端口转发，我现在不确定是那边爆破的我22号端口，还是10022端口
> > BR Robin
> 
> 从wan10022访问内网机器的22端口，反正是暴露在公网下的，你可以试下楼上推荐的工具，但我没用过，不过不建议把重要端口暴露出去

好的，谢谢哈，我来研究下上面的工具，不行我就给ssh端口禁用了

BR
Robin
