### ISSUE TITLE
主机型号显示问题

### ISSUE THREAD

**Issue by harleywong** [coolsnowwolf/lede#8645]
今天编译了5.15的固件，刷入后主机型号显示有点乱，前几天编译的没这情况。（下面是刷入的同一个固件）
![Snipaste_2022-01-08_16-44-56](https://user-images.githubusercontent.com/34861262/148638046-a1ca968b-502b-48a7-be76-4d051f4aecc5.jpg)
![Snipaste_2022-01-08_16-44-48](https://user-images.githubusercontent.com/34861262/148638075-eea478f8-971b-4afe-9c24-af4ddf8d7783.jpg)

**Comment by WYC-2020** [comment]
明显下面那个是谁自己diy的前面一段

**Comment by Beginner-Go** [comment]
[应该是这个commit导致的](https://github.com/coolsnowwolf/lede/commit/dced95e70556960363c366b8783e5695290186f2)

**Comment by binge8** [comment]
> [应该是这个commit导致的](https://github.com/coolsnowwolf/lede/commit/dced95e70556960363c366b8783e5695290186f2)

一样，前面加了一大堆，怎么取消啊

**Comment by binge8** [comment]
[不是这个？](https://github.com/coolsnowwolf/lede/commit/b143589cf2cba27afb46789146f97ffd765a530f)
怎么取消呢？太累赘

**Comment by wangqn** [comment]
我也要同样的问题，使用最新版编译后型号那边会出现Default string Default string/Default string - 
<img width="776" alt="屏幕截图 2022-01-08 213945" src="https://user-images.githubusercontent.com/10090475/148646312-2afe4f8f-f98a-4921-90e4-cf12820d7dc7.png">

**Comment by wkq2004** [comment]
同样的问题。出现Default string Default string/Default string -

**Comment by jasonqdu** [comment]
我最近编译的前面也是有一串：To be filled by O.E.M. To be filled by O.E.M./To be filled by O.E.M. -

**Comment by musclemm** [comment]
同样的问题。出现Default string Default string
![2022-01-10_225540](https://user-images.githubusercontent.com/61529807/148786705-3f97c82d-6bc6-42a5-883d-382dfa28fcd0.png)

**Comment by wangqn** [comment]
经过实验此方法可以去掉 Default string Default string/Default string -
\package\lean\autocore\files\x86\autocore
`h=${g}' - '${a}${b}${c}${d}${e}${f}` 改成 `h=${a}${b}${c}${d}${e}${f}`

**Comment by wkq2004** [comment]
> 经过实验此方法可以去掉 Default string Default string/Default string - \package\lean\autocore\files\x86\autocore `h=${g}' - '${a}${b}${c}${d}${e}${f}` 改成 `h=${a}${b}${c}${d}${e}${f}`

解决了，谢谢。
