### ISSUE TITLE
x86软路由开机一段时间无法进入luci界面，有时还会断网

### ISSUE THREAD

**Issue by bingsugar** [coolsnowwolf/lede#865]
近期自己编译的x86软路由开机一段时间后无法再次进入luci界面配置路由器。有时路由器后方的所有设备会断网，但电脑ssh连接路由正常，路由器端可以ping通谷歌等dns。所有问题在重启之后就会正常。还望大雕指点一下问题所在。
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2618539/default.txt)
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2618540/default.txt)

**Comment by coolsnowwolf** [comment]
留意下是否环路了

**Comment by bingsugar** [comment]
谢谢大雕，在重新刷机配置后问题已解决
