### ISSUE TITLE
这是我的问题还是代码的问题？之前这里不是显示这个的

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#8665]
![image](https://user-images.githubusercontent.com/20067401/148778371-81f48972-aeb9-4f90-a0b4-c972ecd7ca6c.png)

**Comment by musclemm** [comment]
我的也是

**Comment by musclemm** [comment]
[解决方法](https://github.com/coolsnowwolf/lede/issues/8645#issuecomment-1009271295)

**Comment by GreatMichaelLee** [comment]
能否提交修改到主干?谢谢
