### ISSUE TITLE
kmod-phylink is missing dependencies for the following libraries: libphy.ko

### ISSUE THREAD

**Issue by vipboddy** [coolsnowwolf/lede#8669]
make[2]: Leaving directory '/mnt/sdb1/test/lede/package/firmware/prism54-firmware'
time: package/firmware/prism54-firmware/compile#0.21#0.02#0.22
make[2]: Entering directory '/mnt/sdb1/test/lede/package/kernel/linux'
Package kmod-phylink is missing dependencies for the following libraries:
libphy.ko
make[2]: *** [modules/netdevices.mk:123: /mnt/sdb1/test/lede/bin/targets/x86/64/packages/kmod-phylink_5.15.12-1_x86_64.ipk] Error 1
make[2]: Leaving directory '/mnt/sdb1/test/lede/package/kernel/linux'
time: package/kernel/linux/compile#2.41#0.20#2.59
    ERROR: package/kernel/linux failed to build.
make[1]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[1]: Leaving directory '/mnt/sdb1/test/lede'

**Comment by helmiau** [comment]
try to add `CONFIG_PHYLIB=y` to your config

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/148878211-38aa89ab-f12b-49c5-9646-97afb4de9f71.png)
kmod-phylink miss depends

**Comment by WYC-2020** [comment]
没有问题的，这个libphy默认就是要编译的除非你自己吧他取消了 然后又去选择编译phylink 此时就会出现那个问题，我这边编译都有
![image](https://user-images.githubusercontent.com/34025388/148954126-1c2e2741-0be2-45c6-8db8-cd61bc4fdb50.png)
如果要保证phylink编译默认phy也要编译，你在我上面截图哪里加一个依赖就行了，简单 @helmiau

**Comment by WYC-2020** [comment]
@vipboddy 
![image](https://user-images.githubusercontent.com/34025388/148955504-55bf439f-ac5c-48fe-97b1-e49648943aaf.png)
 加个依赖就可以了

**Comment by vipboddy** [comment]
> @vipboddy ![image](https://user-images.githubusercontent.com/34025388/148955504-55bf439f-ac5c-48fe-97b1-e49648943aaf.png) 加个依赖就可以了

感谢大佬指点
