### ISSUE TITLE
老哥,额安装upnp少libip6tc的.......额要怎么解决

### ISSUE THREAD

**Issue by 1965514404** [coolsnowwolf/lede#868]
find /home/dzc/lede/build_dir/target-mips_24kc_musl/miniupnpd-2.1/ipkg-mips_24kc/miniupnpd -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package miniupnpd is missing dependencies for the following libraries:
libip6tc.so.0
make[3]: *** [/home/dzc/lede/bin/packages/mips_24kc/packages/miniupnpd_2.1-2_mips_24kc.ipk] Error 1
make[3]: Leaving directory `/home/dzc/lede/feeds/packages/net/miniupnpd'
time: package/feeds/packages/miniupnpd/compile#0.28#0.44#0.66
make[2]: *** [package/feeds/packages/miniupnpd/compile] Error 2
make[2]: Leaving directory `/home/dzc/lede'
make[1]: *** [/home/dzc/lede/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/dzc/lede'
make: *** [world] 错误 2
[dzc@ice lede]$

**Comment by wv1124** [comment]
find /home/wv/openwrt/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/iptables-1.8.7/ipkg-mipsel_24kc/iptables -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package iptables is missing dependencies for the following libraries:
libip6tc.so.2
libiptext6.so
make[3]: *** [Makefile:675: /home/wv/openwrt/lede/bin/targets/ramips/mt7620/packages/iptables_1.8.7-1_mipsel_24kc.ipk] Error 1
make[3]: Leaving directory '/home/wv/openwrt/lede/package/network/utils/iptables'
time: package/network/utils/iptables/compile#29.53#4.91#35.99
    ERROR: package/network/utils/iptables failed to build.
make[2]: *** [package/Makefile:116: package/network/utils/iptables/compile] Error 1
make[2]: Leaving directory '/home/wv/openwrt/lede'
make[1]: *** [package/Makefile:110: /home/wv/openwrt/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wv/openwrt/lede'
make: *** [/home/wv/openwrt/lede/include/toplevel.mk:230: world] Error 2
