### ISSUE TITLE
升级到5.10内核后ssrplus链接启动Trojan节点报错

### ISSUE THREAD

**Issue by jashok2** [coolsnowwolf/lede#8682]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：ssrplus链接trojan类型节点报错

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：Main node:Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /var/etc/ssrplus/bin/trojan)

**Comment by deplives** [comment]
出门左转，提错地方了

**Comment by lgh200** [comment]
trojan重新编译就行了

**Comment by WYC-2020** [comment]
这明显的提示 boost sysytem 动态库没找到
