### ISSUE TITLE
wan口pppoe拨号的时候怎么修改wan口mac地址？

### ISSUE THREAD

**Issue by Karmylr** [coolsnowwolf/lede#8686]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：wan口pppoe拨号的时候怎么修改wan口mac地址？

### (2) 路由器型号和固件版本

A：j4125/OpenWrt R22.1.1 / LuCI Master (git-21.335.48743-5f363d9)

### (3) 详细日志

A：

**Comment by Her0R0cket** [comment]
手动操作,/etc/config/network,在wan段落里添一条 option macaddr '00:11:22:33:44:AA' ,把mac地址改成你要的.
