### ISSUE TITLE
pkg_hash_check_unresolved: cannot find dependency ntfs3-mount for automount

### ISSUE THREAD

**Issue by aakkll** [coolsnowwolf/lede#8688]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
 * pkg_hash_check_unresolved: cannot find dependency ntfs3-mount for automount
 * pkg_hash_fetch_best_installation_candidate: Packages for automount found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package automount.

### (2) 路由器型号和固件版本

A：X86  R22.1.1

### (3) 详细日志

A：Configuring kmod-button-hotplug.
Configuring kmod-usb-storage-extras.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring ddns-scripts_freedns_42_pl.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency ntfs3-mount for automount
 * pkg_hash_fetch_best_installation_candidate: Packages for automount found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package automount.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/leung/ll/lede'
make[1]: *** [package/Makefile:111: /home/leung/ll/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/leung/ll/lede'
make: *** [/home/leung/ll/lede/include/toplevel.mk:230：world] 错误 2

**Comment by WYC-2020** [comment]
哎……这是5.15内核的自己取消
