### ISSUE TITLE
关于在恩山发布的GL.iNet AX1800 v1.1 固件 ipk插件编译

### ISSUE THREAD

**Issue by avsba001** [coolsnowwolf/lede#8691]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：【64bit 版本，软件兼容官方Openwrt的 21.02 IPK（选择 SUNXI 和 GCC7.5 编译的 IPK 即可）】，
1.我拉取的是您的lede源，target选择了IPQ60** ,默认是gcc7.*编译， SUNXI 在哪我实在没找到对应文档和选项
2.部分通用arm ipk插件好像也能运行，就是日志会有大量报错，还在测试
### (2) 路由器型号和固件版本

A：GL.iNet AX1800 OpenWrt QSDK v1.1

### (3) 详细日志

A：无

**Comment by coolsnowwolf** [comment]
不需要了，有新版固件了，可以直接用这个源编译的 IPQ6000的 IPK 了
