### ISSUE TITLE
编译能通过，但是文件打包里没有sysupgrade固件，只有内存固件，make menuconfig 有选

### ISSUE THREAD

**Issue by kalagxw** [coolsnowwolf/lede#8693]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by kalagxw** [comment]
补充下是squashfs

**Comment by Ra2-IFV** [comment]
建议再确认下设置对不对，保存到的是不是.config文件
你可以试试把编译的输出保存下来，生成squashfs时有没有error
