### ISSUE TITLE
解锁网易云音乐，解锁程序切换成NodeJS版本，在切换回Go版本，无法保存应用

### ISSUE THREAD

**Issue by felixxiao99** [coolsnowwolf/lede#8696]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：X86_64

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/50790338/149610389-1839fac2-ae11-4726-aa29-f4dba4beb366.png)

**Comment by WYC-2020** [comment]
这个我不是说了咋解决吗，都不看下有没相同的isuue吗
