### ISSUE TITLE
adbyby 添加过滤广告的域名后，对应网站打不开

### ISSUE THREAD

**Issue by muziling** [coolsnowwolf/lede#87]
在adbyby 界面的plus domain里追加过滤网址ddbiquge.com，重启adbyby后，这个网站的小说章节内容，手机端打不开。停止adbyby就能打开，确认是adbyby的问题，adbyby其它选项是默认配置。

以前用其它固件的广告过滤，添加这个网址可以正常访问。

**Comment by ctw8989** [comment]
试了下，可以打开啊
