### ISSUE TITLE
M1 编译出现 g++: error: unrecognized command line option '-m64'

### ISSUE THREAD

**Issue by maomaoinchina** [coolsnowwolf/lede#8701]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A： 
M1 上使用vmware fusion arm64版本，在Ubuntu20.04.03LTS编译，出现如下错误

### (2) 路由器型号和固件版本

A：x86 

### (3) 详细日志

A： g++  -o /home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2/out/Release/obj.host/v8_libbase/deps/v8/src/base/bits.o ../deps/v8/src/base/bits.cc '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DV8_TARGET_ARCH_X64' '-DV8_EMBEDDER_STRING="-node.85"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DOBJECT_PRINT' '-DV8_CONCURRENT_MARKING' '-DV8_ARRAY_BUFFER_EXTENSION' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DV8_SNAPSHOT_COMPRESSION' '-DBUILDING_V8_BASE_SHARED' -I/home/lisu/lede/staging_dir/target-x86_64_musl/usr/include -I../deps/v8 -I../deps/v8/include  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2/out/Release/.deps//home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2/out/Release/obj.host/v8_libbase/deps/v8/src/base/bits.o.d.raw   -c
g++: error: unrecognized command line option '-m64'
make[5]: *** [tools/v8_gypfiles/v8_libbase.host.mk:149: /home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2/out/Release/obj.host/v8_libbase/deps/v8/src/base/bits.o] Error 1
make[4]: *** [Makefile:109: node] Error 2
make[4]: Leaving directory '/home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2'
make[3]: *** [Makefile:204: /home/lisu/lede/build_dir/target-x86_64_musl/node-v14.18.2/.built] Error 2
make[3]: Leaving directory '/home/lisu/lede/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#0.43#0.20#0.52
    ERROR: package/feeds/packages/node failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/node/compile] Error 1
make[2]: Leaving directory '/home/lisu/lede'
make[1]: *** [package/Makefile:110: /home/lisu/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lisu/lede'
make: *** [/home/lisu/lede/include/toplevel.mk:230: world] Error 2

**Comment by MBRjun** [comment]
解决了吗？我有相同问题

```
g++  -o /mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/collationinfo.o ../deps/icu-small/source/tools/toolutil/collationinfo.cpp '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D__STDC_FORMAT_MACROS' '-DU_COMMON_IMPLEMENTATION=1' '-DU_I18N_IMPLEMENTATION=1' '-DU_IO_IMPLEMENTATION=1' '-DU_TOOLUTIL_IMPLEMENTATION=1' '-DU_ATTRIBUTE_DEPRECATED=' '-D_CRT_SECURE_NO_DEPRECATE=' '-DU_STATIC_IMPLEMENTATION=1' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/icu-small/source/common -I../deps/icu-small/source/i18n -I../deps/icu-small/source/tools/toolutil  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -Wno-strict-aliasing -O3 -fno-omit-frame-pointer -fno-exceptions -std=gnu++14 -frtti -MMD -MF /mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1/out/Release/.deps//mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/collationinfo.o.d.raw   -c
g++: error: unrecognized command-line option '-m64'
make[5]: *** [tools/icu/icutools.host.mk:574: /mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/collationinfo.o] Error 1
make[4]: *** [Makefile:113: node] Error 2
make[4]: Leaving directory '/mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1'
make[3]: *** [Makefile:166: /mnt/sda/openwrt/build_dir/target-x86_64_musl/node-v16.15.1/.built] Error 2
make[3]: Leaving directory '/mnt/sda/openwrt/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#111.03#11.06#119.92
    ERROR: package/feeds/packages/node failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/node/compile] Error 1
make[2]: Leaving directory '/mnt/sda/openwrt'
make[1]: *** [package/Makefile:110: /mnt/sda/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/sda/openwrt'
make: *** [/mnt/sda/openwrt/include/toplevel.mk:230: world] Error 2
```
