### ISSUE TITLE
kernel与kmod不兼容

### ISSUE THREAD

**Issue by ic0xgkk** [coolsnowwolf/lede#872]
没有改东西，正常编译，出现了这些问题：
Configuring ppp-mod-pppoe.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package luci.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-nlbwmon:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package luci-app-nlbwmon.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for alsa-lib:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package alsa-lib.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ata-core:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ata-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ata-ahci:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ata-ahci.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-dm:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-dm.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-loop:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-loop.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-scsi-generic:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-scsi-generic.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-crypto-crc32c:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-crypto-crc32c.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-ext4:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-fs-ext4.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-vfat:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-fs-vfat.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-hwmon-core:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-hwmon-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-i2c-core:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-i2c-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-i2c-algo-bit:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-i2c-algo-bit.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-hid:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-hid.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-hid-generic:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-hid-generic.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-crc-ccitt:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-lib-crc-ccitt.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-lib-textsearch:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-lib-textsearch.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-libphy:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-libphy.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-mii:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-mii.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-swconfig:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-swconfig.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-r8169:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-r8169.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-e1000:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-e1000.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-e1000e:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-e1000e.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-igb:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-igb.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-igbvf:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-igbvf.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ixgbe:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ixgbe.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-pcnet32:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-pcnet32.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-macvlan:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-macvlan.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-tulip:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-tulip.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-vmxnet3:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-vmxnet3.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-reject6:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-nf-reject6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-ipt6:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-nf-ipt6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-filter:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-filter.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-ipset:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-ipset.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-raw:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-raw.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-nat-extra:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-nat-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nathelper:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nathelper.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nathelper-extra:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-nf-nathelper-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-tproxy:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-tproxy.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-extra:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ipt-extra.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-udptunnel4:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-udptunnel4.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-udptunnel6:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-udptunnel6.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-vxlan:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-vxlan.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-slhc:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-slhc.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ppp:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-ppp.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-pppox:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-pppox.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-pppoe:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-pppoe.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sched-core:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-sched-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-sched:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-sched.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-tcp-bbr:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-tcp-bbr.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-core:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-usb-core.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-hid:
 * 	kernel (= 4.9.138-1-15628fc9e383336aab61c9d56be1260b) * 
 * opkg_install_cmd: Cannot install package kmod-usb-hid.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255

**Comment by LGA1150** [comment]
重新编译内核
