### ISSUE TITLE
最新版固件K3缺少WiFi设置，没有WiFi信号

### ISSUE THREAD

**Issue by jobber2955** [coolsnowwolf/lede#8730]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
最新版固件K3缺少WiFi设置，没有WiFi信号
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue
搜到类似的issue https://github.com/coolsnowwolf/lede/issues/5237
但按照issue中所说重置后问题依然在
## 2. 详细叙述
从旧版本的固件（.BIN固件的那种）直接在web中清除配置并刷写trx固件，问题出现
### (1) 具体问题

A：缺少WiFi设置，没有WiFi信号

### (2) 路由器型号和固件版本

A：斐讯K3 OpenWrt R21.8.6 / LuCI Master (git-21.211.30217-03784c3)

### (3) 详细日志

A：

**Comment by koogg** [comment]
删掉LEDE文件夹，重新编译吧。我之前也是编译都OK,刷了以后没信号。推倒重来就行了
