### ISSUE TITLE
最新版LEDE源码MOSDNS

### ISSUE THREAD

**Issue by geryson911** [coolsnowwolf/lede#8733]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新版的源码LUCI-APP-MOSDNS无法正常运行，点启动没反应，也没有任何日志

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by geryson911** [comment]
路由器型号X86

**Comment by 1wrt** [comment]
昨天才编译的，没有你所说的问题。

**Comment by geryson911** [comment]
LUCI-APP-MOSDNS能启用？

> 昨天才编译的，没有你所说的问题。
