### ISSUE TITLE
11月30号重新编译后SSR PLUS+ 群晖外网无法访问

### ISSUE THREAD

**Issue by mile3033** [coolsnowwolf/lede#874]
11月30号重新编译后SSR PLUS+ ，V2RAY开GFWLIST,黑群晖外网无法访问,提示证书有问题，貌似绕路到VPS了。换成绕过大陆模式后，黑群晖外网可以访问。

**Comment by Troyshen94** [comment]
我之前有遇到类似情形
后来的解决方案是 直接把黑裙划到不需要翻墙的IP里去了
