### ISSUE TITLE
求助windows  ubuntu编译报错  

### ISSUE THREAD

**Issue by jt8823** [coolsnowwolf/lede#8748]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
Configuring luci.
Configuring default-settings.
Configuring htop.
Configuring kmod-iavf.
Configuring kmod-i2c-algo-bit.
Configuring kmod-igbvf.
Configuring bnx2x-firmware.
Configuring kmod-bnx2x.
Configuring kmod-forcedeth.
Configuring luci-i18n-base-zh-cn.
Configuring kmod-amd-xgbe.
Configuring bc.
Configuring kmod-lib-lzo.
Configuring kmod-amazon-ena.
Configuring kmod-e1000e.
Configuring autocore-x86.
Configuring kmod-button-hotplug.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Setting flags for package libc to hold.
Setting flags for package libgcc1 to hold.
Setting flags for package libstdcpp6 to hold.
Setting flags for package libpthread to hold.
Setting flags for package librt to hold.
cp -fpR /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86 /home/jt8823/lede/build_dir/target-x86_64_musl/root.orig-x86
Enabling autocore
Enabling boot
Enabling cron
Enabling ddns
Enabling dnsmasq
Enabling done
Enabling dropbear
Enabling firewall
Enabling fstab
Enabling gpio_switch
Enabling kms
Enabling led
Enabling lm-sensors
Enabling log
Enabling network
Enabling rpcd
Enabling shadowsocksr
Enabling sysctl
Enabling sysfixtime
Enabling sysfsutils
Enabling sysntpd
Enabling system
Enabling uhttpd
Enabling umount
Enabling urandom_seed
sed -i "s/Installed-Time: .*/Installed-Time: 1642734865/" /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/status
rm -rf /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/boot /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/tmp/* /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/*.postinst* /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/lists/* /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/var/lock/*.lock
find /home/jt8823/lede/build_dir/target-x86_64_musl/root-x86/ -mindepth 1 -execdir touch -hcd "@1642734865" "{}" +
find: The relative path 'Files/Oculus/Support/oculus-runtime' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
make[2]: *** [package/Makefile:73: package/install] Error 1
make[2]: Leaving directory '/home/jt8823/lede'
make[1]: *** [package/Makefile:111: /home/jt8823/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/jt8823/lede'
make: *** [/home/jt8823/lede/include/toplevel.mk:230: world] Error 2

**Comment by EnnawYang** [comment]
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ ]  没有类似的issue
> 
先搜索，再提问
