### ISSUE TITLE
luci-app-ssr-plus 海外模式有问题

### ISSUE THREAD

**Issue by fayswing** [coolsnowwolf/lede#875]
LEAN大   你好    最新的SSR加入了海外模式   很让我们海外游子激动
可是海外用户回国 模式有问题   用海外模式以后    
无论国内网站还是海外网站所有IP都是走的本机IP      除非全局模式可以起效果
智能模式不可以         麻烦LEAN大以后可以更新一下海外模式    谢谢啦

**Comment by sjtuross** [comment]
默认只有这个/etc/dnsmasq.oversea/oversea_list.conf列表中的域名才会走代理，你可以试试y.qq.com，开代理就能播放音乐

你要国内都走代理，可以试试加内网192.168.1.0/24（举例）到增强游戏模式客户端LAN IP

**Comment by asuwa** [comment]
> 还是希望能有国外IP不走代理 国内视频网站走代理的这种比较智能类型的模式
> 在梅林固件上是用的 如果可以互相编辑就好了

请问你的问题是否解决了，我也有相同的需求，在网上爬文了许多还不知道该如何设置？

**Comment by WoodC2011** [comment]
> > 还是希望能有国外IP不走代理 国内视频网站走代理的这种比较智能类型的模式
> > 在梅林固件上是用的 如果可以互相编辑就好了
> 
> 请问你的问题是否解决了，我也有相同的需求，在网上爬文了许多还不知道该如何设置？

你最终解决了吗
