### ISSUE TITLE
netgear_r7800使用5.10.93编译时报错，5.4.172正常

### ISSUE THREAD

**Issue by heiger8231** [coolsnowwolf/lede#8752]
make -C /home/user/lean_netgear_r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.10.93 KCFLAGS="-fmacro-prefix-map=/home/user/lean_netgear_r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi=target-arm_cortex-a15+neon-vfpv4_musl_eabi" HOSTCFLAGS="-O2 -I/home/user/lean_netgear_r7800/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Jan 21 03:14:25 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/user/lean_netgear_r7800/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/user/lean_netgear_r7800/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.93 CC="arm-openwrt-linux-muslgnueabi-gcc" zImage Image dtbs modules
make[5]: Entering directory '/home/user/lean_netgear_r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.10.93'
  DTC     arch/arm/boot/dts/qcom-ipq8062-wg2600hp3.dtb
  SYSNR   arch/arm/include/generated/asm/unistd-nr.h
  GEN     arch/arm/include/generated/asm/mach-types.h
  DTC     arch/arm/boot/dts/qcom-ipq8064-ap161.dtb
  SYSTBL  arch/arm/include/generated/calls-oabi.S
  SYSTBL  arch/arm/include/generated/calls-eabi.S
  DTC     arch/arm/boot/dts/qcom-ipq8064-ea7500-v1.dtb
  DTC     arch/arm/boot/dts/qcom-ipq8064-ea8500.dtb
  DTC     arch/arm/boot/dts/qcom-ipq8064-g10.dtb
Error: arch/arm/boot/dts/qcom-ipq8062.dtsi:97.1-6 Label or path nss0 not found
Error: arch/arm/boot/dts/qcom-ipq8062.dtsi:103.1-6 Label or path nss1 not found
FATAL ERROR: Syntax error parsing input tree
make[6]: *** [scripts/Makefile.lib:326: arch/arm/boot/dts/qcom-ipq8062-wg2600hp3.dtb] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [Makefile:1359: dtbs] Error 2
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/home/user/lean_netgear_r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.10.93'
make[4]: *** [Makefile:29: /home/user/lean_netgear_r7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-5.10.93/.modules] Error 2
make[4]: Leaving directory '/home/user/lean_netgear_r7800/target/linux/ipq806x'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/user/lean_netgear_r7800/target/linux'
time: target/linux/compile#1.52#0.57#1.83
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/user/lean_netgear_r7800'
make[1]: *** [target/Makefile:18: /home/user/lean_netgear_r7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/user/lean_netgear_r7800'
make: *** [/home/user/lean_netgear_r7800/include/toplevel.mk:230：world] 错误 2

**Comment by AmadeusGhost** [comment]
不支持 5.10
