### ISSUE TITLE
强迫症一个时间显示小建议

### ISSUE THREAD

**Issue by tianiue** [coolsnowwolf/lede#8758]
![AKKN7PP~92$)}%_JRF }H}U](https://user-images.githubusercontent.com/61725402/150628513-10d8ef8a-0d2f-4dda-bd0a-a25af12e4bb4.png)
建议换一种显示方式，改成中文和数字
2022年1月22日 星期六 12:00:06
2022/1/22 周六 12:00:06

**Comment by Beginner-Go** [comment]
可以 但没必要

**Comment by hzokdj** [comment]
好提议，期待

**Comment by deplives** [comment]
你可以自行修改对应架构的index，比如x86的是
https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
比如将这一行改为
`localtime  = os.date("%Y-%m-%d %H:%M:%S")`
则为 `2022-01-23 12:45:46` 这种时间格式

**Comment by GreatMichaelLee** [comment]
> 你可以自行修改对应架构的index，比如x86的是
> 
> https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
> 
> 
> 比如将这一行改为
> `localtime = os.date("%Y-%m-%d %H:%M:%S")`
> 则为 `2022-01-23 12:45:46` 这种时间格式

这个建议比上面的有营养

**Comment by tianiue** [comment]
> 你可以自行修改对应架构的index，比如x86的是
> 
> https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
> 
> 
> 比如将这一行改为
> `localtime = os.date("%Y-%m-%d %H:%M:%S")`
> 则为 `2022-01-23 12:45:46` 这种时间格式

请问云编译不修改源码如何添加替换？

**Comment by deplives** [comment]
> tianiue

在你自己的脚本里面sed替换

**Comment by deplives** [comment]
> > 你可以自行修改对应架构的index，比如x86的是
> > https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
> > 
> > 比如将这一行改为
> > `localtime = os.date("%Y-%m-%d %H:%M:%S")`
> > 则为 `2022-01-23 12:45:46` 这种时间格式
> 
> 请问云编译不修改源码如何添加替换？

在你自己的脚本里面用 sed 替换

**Comment by tianiue** [comment]
> > > 你可以自行修改对应架构的index，比如x86的是
> > > https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
> > > 
> > > 比如将这一行改为
> > > `localtime = os.date("%Y-%m-%d %H:%M:%S")`
> > > 则为 `2022-01-23 12:45:46` 这种时间格式
> > 
> > 
> > 请问云编译不修改源码如何添加替换？
> 
> 在你自己的脚本里面用 sed 替换

2022年1月22日 星期六 12:00:06 这个格式不会写

**Comment by deplives** [comment]
> > > > 你可以自行修改对应架构的index，比如x86的是
> > > > https://github.com/coolsnowwolf/lede/blob/744d1ed2c7d79b3554ead609716ebaab6f1ed350/package/lean/autocore/files/x86/index.htm#L63
> > > > 
> > > > 比如将这一行改为
> > > > `localtime = os.date("%Y-%m-%d %H:%M:%S")`
> > > > 则为 `2022-01-23 12:45:46` 这种时间格式
> > > 
> > > 
> > > 请问云编译不修改源码如何添加替换？
> > 
> > 
> > 在你自己的脚本里面用 sed 替换
> 
> 2022年1月22日 星期六 12:00:06 这个格式不会写

你这个啥都要喂到嘴里么，学会用一下搜索引擎
