### ISSUE TITLE
wan口断线

### ISSUE THREAD

**Issue by jwkinko** [coolsnowwolf/lede#8760]
#8737
新编译x86 内核版本5.10.93路由器重启了 记得日志出现
no response to 5 echo-requests  
wan口就断线了
LCP 响应故障阀值 0
LCP 响应间隔 5 都是默认的没改过

**Comment by david5486** [comment]
7800一样有这问题，遇见过两次了。上次是运行六天断线，pppoe重拨无效只有重启设备。
没注意看日志。

**Comment by wi11iamzhao** [comment]
设备信息？详细日志？
