### ISSUE TITLE
dnsmasq占用率高且无法正常解析DNS地址

### ISSUE THREAD

**Issue by zopargr** [coolsnowwolf/lede#8762]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：运行一段时间后，dnsmasq占用率特别高且无法上网，手动kill掉dnsmasq的进程，dnsmasq会自动重启，占用率依然居高不下，只能重启整个路由器解决，然后过了一天又会复现这个问题

### (2) 路由器型号和固件版本

A：X86 固件5.15.16

### (3) 详细日志

A：
![FXK0N6QMZY7 8T`_1Y7G017](https://user-images.githubusercontent.com/45194744/150664914-ce9b0147-5ae2-4ffc-898a-a03b2ebf23c7.png)
![image](https://user-images.githubusercontent.com/45194744/150664920-0ac5b751-898a-4ce4-8afe-27fd63d271f1.png)
![image](https://user-images.githubusercontent.com/45194744/150664928-5e6d1af1-4973-4317-ba87-9e1fecff7a59.png)

**Comment by zhangguanzhang** [comment]
👀 你需要 taskset 绑定限制核心

**Comment by jlzsss** [comment]
好像还是没有修复？

**Comment by zopargr** [comment]
卸载掉socat后恢复正常了，此issue关闭。
