### ISSUE TITLE
armv8 CPU架构、状态不显示

### ISSUE THREAD

**Issue by binge8** [coolsnowwolf/lede#8769]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：armv8，CPU架构、状态不显示，日志报错

### (2) 路由器型号和固件版本

A：x96max+，armv8，用F大的源码打包

### (3) 详细日志

A：看图
![photo_2022-01-24_19-41-55](https://user-images.githubusercontent.com/53508344/150777329-c9e2b2a2-c8a4-4c40-acf3-1d36db8091f1.jpg)
![photo_2022-01-24_19-42-09](https://user-images.githubusercontent.com/53508344/150777348-863d1a63-9ff6-4f5a-af1e-7f85c9b44d6d.jpg)

**Comment by AmadeusGhost** [comment]
杂交的自行解决。
