### ISSUE TITLE
编译出的固件无法保存更改

### ISSUE THREAD

**Issue by xiaolu-lab** [coolsnowwolf/lede#8786]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译出的固件无法保存更改
Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
内存未溢出 我在多个设备尝试都如此 k2p以及我的x86软路由保存更改后重启都会丢失数据

### (1) 具体问题

A：无法保存更改

### (2) 路由器型号和固件版本

A：x86 （不是什么新pc）OpenWrt R21.12.1 
内核用的5.10

### (3) 详细日志

A：未见异常

**Comment by xiaolu-lab** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> 编译出的固件无法保存更改 Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ ]  没有类似的issue
> 
> ## 2. 详细叙述
> 内存未溢出 我在多个设备尝试都如此 k2p以及我的x86软路由保存更改后重启都会丢失数据
> 
> ### (1) 具体问题
> A：无法保存更改
> 
> ### (2) 路由器型号和固件版本
> A：x86 （不是什么新pc）OpenWrt R21.12.1 内核用的5.10
> 
> ### (3) 详细日志
> A：未见异常

**Comment by WYC-2020** [comment]
没遇到过
