### ISSUE TITLE
apache 编译选项错误 --with-apxs

### ISSUE THREAD

**Issue by joyplayer** [coolsnowwolf/lede#8788]
需在apache的Makefile Line 199 添加--with-apxs="$(STAGING_DIR)/usr/bin/apxs" \

**Comment by WYC-2020** [comment]
我这边没加也能编译成功呢，并且mod_cgi.so也生成了

**Comment by joyplayer** [comment]
新年好~
可有生成的.config配置,试了很多次，一直出错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coolsnowwolf/lede"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coolsnowwolf/lede] apache 编译选项错误 --with-apxs (Issue #8788)





 
我这边没加也能编译成功呢，并且mod_cgi.so也生成了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by joyplayer** [comment]
那个是依赖的lib没有自动选上，手动选上就好了
