### ISSUE TITLE
取消桥接以后没法显示总流量

### ISSUE THREAD

**Issue by Karmylr** [coolsnowwolf/lede#8792]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：取消桥接以后没法显示总流量

### (2) 路由器型号和固件版本

A：j4125 OpenWrt R22.1.1

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/69903376/151686887-67ebc358-eaeb-4da9-a8a8-0f7b9f4af8cb.png)

**Comment by lxl6125** [comment]
重启一次呗
维修三步骤：重启，重装，重买

**Comment by Karmylr** [comment]
> 重启一次呗 维修三步骤：重启，重装，重买

卧槽 牛逼
