### ISSUE TITLE
编译完固件sha256sums不更新

### ISSUE THREAD

**Issue by sjtuross** [coolsnowwolf/lede#880]
不知从什么时候开始，编译完固件sha256sums不再更新了

**Comment by tossp** [comment]
L默认给关闭了，自己给补上就行了

**Comment by sjtuross** [comment]
感谢回复，请问在哪儿补？能给个示例吗？

**Comment by sjtuross** [comment]
找到了，在3b5ec66被注释掉了

**Comment by sjtuross** [comment]
找到了，在https://github.com/coolsnowwolf/lede/commit/3b5ec661f91972af275cbd6c398bfa3c88f78358这个commit中被注释掉了

**Comment by sjtuross** [comment]
找到了，https://github.com/coolsnowwolf/lede/commit/3b5ec661f91972af275cbd6c398bfa3c88f78358

在这个commit中被注释掉了
