### ISSUE TITLE
不显示S-SR-plus

### ISSUE THREAD

**Issue by yfeercom** [coolsnowwolf/lede#881]
12月4日编译完成后 服务里面不显示ssr,xiaomimini和wndr4300V1 都不显示

**Comment by zcluo** [comment]
我的也是虚拟机菜单入口没了

**Comment by ziqqqq** [comment]
me too.

**Comment by mymail6** [comment]
New3 和WR1200JS 也都没显示 ssr plus luci界面

**Comment by choushui007** [comment]
极路由1S也不显示，我以为是编译的时候没加上，然后删除 .config。 make manuconfig的时候出错。。。

**Comment by lyin888** [comment]
在推上看到以为推油转发的需要在命令行输入一个命令来解密，命令没来得及保存哪就给删了

**Comment by lyin888** [comment]
删除 package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua文件，然后替换，
现在shadowsocksr.lua被加密了

**Comment by zcluo** [comment]
这是要收费的节奏吗

**Comment by ypdenet** [comment]
我以为我眼瞎 没勾选呢

**Comment by hcym** [comment]
这么有什么意义呢？害得我用小山源码编译了老老版ssr，加密格式太少，又改了服务端的配置，居然比新版本快一点点。滑稽查局

**Comment by lyin888** [comment]
不是收费，天朝你懂得，安全为好

**Comment by lm317379829** [comment]
echo  0xDEADBEEF > /etc/config/google_fu_mode

**Comment by lyin888** [comment]
感谢楼上的

**Comment by zcluo** [comment]
要怎么解密？

**Comment by shenzt68** [comment]
echo 0xDEADBEEF > /etc/config/google_fu_mode
这个能有用？不是老毛子才这么干的吗？

**Comment by choushui007** [comment]
> echo 0xDEADBEEF > /etc/config/google_fu_mode
> 这个能有用？不是老毛子才这么干的吗？

亲测有用，理解一下人家，上面亚历山大

**Comment by coolsnowwolf** [comment]
最近风声紧，作为彩蛋吧~

**Comment by dongfangy2011** [comment]
> > echo 0xDEADBEEF> / etc / config / google_fu_mode 
> > 这个能有用？不是老毛子才这么干的吗？
> 
> 亲测有用，理解一下人家，上面亚历山大

请问： 在哪里输入这个命令呢？直接在路由器里还是再编译环境的Ubuntu里。谢谢

**Comment by choushui007** [comment]
> > > echo 0xDEADBEEF> / etc / config / google_fu_mode
> > > 这个能有用？不是老毛子才这么干的吗？
> > 
> > 
> > 亲测有用，理解一下人家，上面亚历山大
> 
> 请问： 在哪里输入这个命令呢？直接在路由器里还是再编译环境的Ubuntu里。谢谢

电脑端SSH登录路由器，然后照着打即可

**Comment by choushui007** [comment]
> 最近风声紧，作为彩蛋吧~

能否同步一下 openwrt 项目的变动？

**Comment by lucky0l** [comment]
还有这操作，好吧，这个得记录一下，以防止后面忘了又找不到……

**Comment by MxCen** [comment]
马克一下。。。。

**Comment by snowrice** [comment]
怪不得明明編譯了卻看不見，原來要念咒語才能看到

**Comment by ixxxxxx** [comment]
弱弱的问下，`echo 0xDEADBEEF > /etc/config/google_fu_mode`开启后不能添加ss服务器？
是哪里没有设置好吗？
<img width="518" alt="2018-12-10 2 18 50" src="https://user-images.githubusercontent.com/25519487/49714090-8f9c4300-fc86-11e8-921a-ec32d5a41f71.png">

**Comment by wxlost** [comment]
原来是彩蛋...我以为是我编译问题...编译了一天刷了30多次....我...

**Comment by lm317379829** [comment]
> 弱弱的问下，`echo 0xDEADBEEF > /etc/config/google_fu_mode`开启后不能添加ss服务器？
> 是哪里没有设置好吗？
> <img alt="2018-12-10 2 18 50" width="518" src="https://user-images.githubusercontent.com/25519487/49714090-8f9c4300-fc86-11e8-921a-ec32d5a41f71.png">

编译的时候没有选shadowsocks New Version

**Comment by ixxxxxx** [comment]
> > 弱弱的问下，`echo 0xDEADBEEF > /etc/config/google_fu_mode`开启后不能添加ss服务器？
> > 是哪里没有设置好吗？
> > <img alt="2018-12-10 2 18 50" width="518" src="https://user-images.githubusercontent.com/25519487/49714090-8f9c4300-fc86-11e8-921a-ec32d5a41f71.png">
> 
> 编译的时候没有选shadowsocks New Version

貌似是这样的，感谢。

**Comment by rabbired** [comment]
原来是彩蛋，MAKE一下。

**Comment by waybq** [comment]
原来是这样啊，谢谢，今天编译了几次，也刷了几次，都没菜单，但是容量是增加的。原来是这样啊。
谢谢各位了。

**Comment by RicardoKlose** [comment]
居然还有彩蛋，mark一下

**Comment by a1768623020** [comment]
我以为我眼睛瞎了呢。。。原来是彩蛋！谢谢大佬。

**Comment by lan542662** [comment]
@wxlost 你比我还人才。刷30多次。。。有问题找男神。enjoy~

**Comment by yunnan0317** [comment]
纳闷了半天...找着根了

**Comment by whlsxl** [comment]
git checkout -b xx 2915c44a11ca0ee40b51ff5d9c18a0d
Love & Peace!!!

**Comment by mgsqz** [comment]
Mark一下

**Comment by xlbljz** [comment]
原来如此，感谢各位

**Comment by TheProjectM** [comment]
Easter egg

**Comment by qq280948982** [comment]
> echo 0xDEADBEEF > /etc/config/google_fu_mode

输入了彩蛋命令，但是界面上依然没有显示，怎么破？

**Comment by jzjohn789** [comment]
输入了，但是依然没有，是删除了？

**Comment by kktt007** [comment]
> 输入了，但是依然没有，是删除了？

helloworld

**Comment by jzjohn789** [comment]
> > 输入了，但是依然没有，是删除了？
> 
> helloworld

???什么意思

**Comment by xlbljz** [comment]
> 输入了，但是依然没有，是删除了？

排一下安装的错误吧

**Comment by jzjohn789** [comment]
> > 输入了，但是依然没有，是删除了？
> 
> 排一下安装的错误吧

没错的，我现在想装USB打印服务器，一直弄不好，知道怎么弄吗，要重新编译吗

**Comment by xlbljz** [comment]
实在弄不好可以去论坛找现成的固件刷

**Comment by xlbljz** [comment]
> > > 输入了，但是依然没有，是删除了？
> > 
> > 
> > 排一下安装的错误吧
> 
> 没错的，我现在想装USB打印服务器，一直弄不好，知道怎么弄吗，要重新编译吗

实在弄不好可以去论坛找现成的固件刷

**Comment by jzjohn789** [comment]
> > > > 输入了，但是依然没有，是删除了？
> > > 
> > > 
> > > 排一下安装的错误吧
> > 
> > 
> > 没错的，我现在想装USB打印服务器，一直弄不好，知道怎么弄吗，要重新编译吗
> 
> 实在弄不好可以去论坛找现成的固件刷

就是找不到。。。。。。搞通宵了

**Comment by xlbljz** [comment]
> > > > > 输入了，但是依然没有，是删除了？
> > > > 
> > > > 
> > > > 排一下安装的错误吧
> > > 
> > > 
> > > 没错的，我现在想装USB打印服务器，一直弄不好，知道怎么弄吗，要重新编译吗
> > 
> > 
> > 实在弄不好可以去论坛找现成的固件刷
> 
> 就是找不到。。。。。。搞通宵了

恩山无线论坛，上面有很多大神做的固件。

**Comment by jzjohn789** [comment]
> 恩山无线论坛

看看吧

**Comment by jzjohn789** [comment]
> > > > > > 输入了，但是依然没有，是删除了？
> > > > > 
> > > > > 
> > > > > 排一下安装的错误吧
> > > > 
> > > > 
> > > > 没错的，我现在想装USB打印服务器，一直弄不好，知道怎么弄吗，要重新编译吗
> > > 
> > > 
> > > 实在弄不好可以去论坛找现成的固件刷
> > 
> > 
> > 就是找不到。。。。。。搞通宵了
> 
> 恩山无线论坛，上面有很多大神做的固件。

不是说他们弄了一堆后门吗？

**Comment by xlbljz** [comment]
> 不是说他们弄了一堆后门吗？

用人不疑，疑人不用。自己衡量。

**Comment by jzjohn789** [comment]
> > 不是说他们弄了一堆后门吗？
> 
> 用人不疑，疑人不用。自己衡量。

教我一下自编译吧
