### ISSUE TITLE
r7800,刷了openwrt，固件自带ssr plus+插件，开启gfw模式、绕过大陆模式，手机连接wifi能够正常访问google、youtube等网站，但是无法访问hostloc.com和泥巴电影mudvod.tv(以及nbyy.tv)，添加hostloc.com和mudvod.tv(以及nbyy.tv)为强制走代理的域名，通过手机访问，能够打开hostloc.com，但是打开泥巴电影mudvod.tv(以及nbyy.tv)的时候显示This website is using a security service to protect itself from online attacks，error1020，访问被拒绝。如果手机上开启clash通过同一个代理访问泥巴电影，则能够正常访问，请问各位大佬是什么原因，该如何解决。

### ISSUE THREAD

**Issue by iamaguoke** [coolsnowwolf/lede#8824]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by jxph1123** [comment]
我也是这样，编译了很多版本都是，一直编译到升级5.10前，大概5.4.123版本的时候，就能访问了，但是有个问题，翻墙速度基本只有2.5M/S，后面的版本能有5M/S，谁知道翻墙速度上升是啥优化吗

**Comment by lxl6125** [comment]
标题和正文分不清吗？

**Comment by chobitsos** [comment]
建议关闭此issues，去隔壁helloworld提

**Comment by jxph1123** [comment]
用这边的老版本，隔壁的新版本，没有此问题。所以到底哪边问题真不清楚。

**Comment by hiboy007** [comment]
节点问题，网站检测到大量相同的IP的多次访问，认为是有人进行攻击，所以拒绝访问，你可以换一个节点IP试一下，最好能找一个你专用的IP就不会出现这种情况了。

**Comment by jxph1123** [comment]
不是节点问题，我换过很多节点，两个机场都试过，泥巴影院就是打不开。。。用v2rayng哪个节点都能打开。

**Comment by hiboy007** [comment]
我刚试了一下，禁用ipv6就都可以访问了。

**Comment by jxph1123** [comment]
确实估计是IPV6问题，但是IPV6关了后，翻墙速度掉了一大半，所以还是希望大佬修复下。
