### ISSUE TITLE
最新5.4内核在线列表不刷新

### ISSUE THREAD

**Issue by zhanglei2021** [coolsnowwolf/lede#8828]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：在线用户列表只增加不减少

### (2) 路由器型号和固件版本

A：k2p，固件版本OpenWrt R22.1.1，内核5.4.175

### (3) 详细日志

A：没有日志
手动断开路由器2小时，发现概览，网络的在线用户数不变，列表的DHCP分配内离线设备还显示在线

**Comment by WYC-2020** [comment]
我这边测试正常呢，我改成2分钟测试没任何问题，两小时太长了 我就没测试了
