### ISSUE TITLE
WARNING: 'fakeuname/host', which does not exist

### ISSUE THREAD

**Issue by rongcenter** [coolsnowwolf/lede#8831]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
'fakeuname/host', which does not exist

### (2) 路由器型号和固件版本
x86

### (3) 详细日志
Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/feeds/telephony/yate/Makefile' has a build dependency on 'fakeuname/host', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.

**Comment by Beginner-Go** [comment]
应该修好了
