### ISSUE TITLE
ipq60xx编译问题

### ISSUE THREAD

**Issue by BOY-JHY** [coolsnowwolf/lede#8834]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
ipq60xx固件编译不生成IMG
### (1) 具体问题

A：ipq60xx固件编译成功，但不生成IMG，只有一堆IPK。
      make menuconfig就选择了ipq60xx，下面两个选项都只有默认。
      编译环境是VM虚拟机Ubuntu 20.04 LTS x64，外网访问正常。
      是本来就无法编译还是有什么注意点。

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by Cathgao** [comment]
看是不是超出ROM大小上限

**Comment by AmadeusGhost** [comment]
就是给你编译 ipk 用的。
