### ISSUE TITLE
新人求问QQ OP群的答案是什么

### ISSUE THREAD

**Issue by popo4u** [coolsnowwolf/lede#8847]
看到 OP 群，本着兴趣想跟这各位大佬学技术，但是被群密码拒之门外了。
<img width="907" alt="Screen Shot 2022-02-09 at 12 30 32" src="https://user-images.githubusercontent.com/15872851/153122148-168c5077-d1db-4d58-85df-3543ddf2f48c.png">

求好心人告知，不胜感激

**Comment by WYC-2020** [comment]
这玩意随便填就是了啊，进去也没啥用，我都退了一群吹牛的哈哈
