### ISSUE TITLE
sometimes cannot enter luci after reboot

### ISSUE THREAD

**Issue by opsiff** [coolsnowwolf/lede#885]
/usr/lib/lua/luci/dispatcher.lua:609: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/usr/lib/lua/luci/dispatcher.lua:609: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:261: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by choushui007** [comment]
这个我遇过，重启就没事了

**Comment by coolsnowwolf** [comment]
lack of ram
