### ISSUE TITLE
2.9号版本编译报错net/sched/Kconfig:45: warning: menuconfig statement without prompt

### ISSUE THREAD

**Issue by wokilp** [coolsnowwolf/lede#8850]
echo -e "# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set\n# CONFIG_RD_LZ4 is not set" >> /home/test/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175/.config
echo -e "# CONFIG_INITRAMFS_COMPRESSION_ZSTD is not set\n# CONFIG_RD_ZSTD is not set" >> /home/test/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175/.config
cp -fpR /home/test/lede/target/linux/generic/other-files/init /home/test/lede/build_dir/target-mipsel_24kc_musl/root-ramips/init
touch -hcd "@1644370597" /home/test/lede/build_dir/target-mipsel_24kc_musl/root-ramips/init
rm -rf /home/test/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175/usr/initramfs_data.cpio*
make -C /home/test/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175 KCFLAGS="-fmacro-prefix-map=/home/test/lede/build_dir/target-mipsel_24kc_musl=target-mipsel_24kc_musl" HOSTCFLAGS="-O2 -I/home/test/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mipsel-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Wed Feb  9 01:36:37 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/test/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/test/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.175 CC="mipsel-openwrt-linux-musl-gcc"  vmlinux vmlinuz modules
make[5]: Entering directory '/home/test/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175'
scripts/kconfig/conf  --syncconfig Kconfig
**net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:478:warning: multi-line strings not supported**
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      lib/decompress.o
  AR      lib/lib.a

**Comment by WYC-2020** [comment]
没啥影响忽略即可 第一个警告我这边修复了
第二个警告暂时不管，毕竟是linux 源码本身自带的，并且没啥影响
