### ISSUE TITLE
全新编译5.15内核会卡住

### ISSUE THREAD

**Issue by xiaoyouke01** [coolsnowwolf/lede#8856]
![IMG_20220210_085357](https://user-images.githubusercontent.com/71208560/153343744-ac0fc91f-da15-4985-be2a-3bd139614b0b.jpg)
试了几次都卡在这里。

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/lede/commit/f6a5707de03c0a49e6a9c723bdbbb3aea188e11f
https://github.com/WYC-2020/lede/commit/3b42da5a3718822cf115a76ff1f68310ae6a3793
@xiaoyouke01

**Comment by Beginner-Go** [comment]
> [WYC-2020/lede@f6a5707](https://github.com/WYC-2020/lede/commit/f6a5707de03c0a49e6a9c723bdbbb3aea188e11f) [WYC-2020/lede@3b42da5](https://github.com/WYC-2020/lede/commit/3b42da5a3718822cf115a76ff1f68310ae6a3793) @xiaoyouke01

大佬 pr下？
