### ISSUE TITLE
mKCP协议的服务器失败

### ISSUE THREAD

**Issue by the55555day** [coolsnowwolf/lede#886]
mKCP协议的v2ray服务器连接失败，同样的配置在v2ray pro里连接正常

**Comment by hcym** [comment]
应该没问题，我试过几种mkcp外加动态端口都能运行，就是效率比手机弱一点，活见鬼。细节要注意，除了缓冲缓存可以不一致，其它都要一一对应。

**Comment by the55555day** [comment]
试过了，参数完全相同也不通，v2ray pro可以正常通

**Comment by hcym** [comment]
不清楚了，我的三个vps全面转成动态端口加mkcp，还加了微信视频流伪装，感觉快点。据说http2还要好，明天试试看，能不能行

**Comment by tefiszx** [comment]
楼主问题解决了吗？我也遇到和你一模一样的问题了。相同配置ssrplus无法连接，v2raypro连接正常
