### ISSUE TITLE
请问第一次编译要花多长时间

### ISSUE THREAD

**Issue by profei** [coolsnowwolf/lede#888]
请问第一次编译要花多长时间

**Comment by choushui007** [comment]
2个小时左右，虚拟机

**Comment by hcym** [comment]
完全看机器，最快一刻钟，最慢五个钟

**Comment by choushui007** [comment]
> 两三个小时
> 
> ![image](https://user-images.githubusercontent.com/574037/49636208-eadaf500-fa3c-11e8-9fe2-3bd5f10c2975.png)

苹果怎么编译？能否告知一下需要安装什么？
