### ISSUE TITLE
R4S 编译报错 btrfs-progs错误

### ISSUE THREAD

**Issue by ZZMHA227** [coolsnowwolf/lede#8887]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
R4S 编译时， ERROR: package/feeds/packages/btrfs-progs failed to build.
Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：R4S 编译时， ERROR: package/feeds/packages/btrfs-progs failed to build.

### (2) 路由器型号和固件版本

A：R4S

### (3) 详细日志

A：checking for EXT4_EPOCH_MASK defined in ext2fs/ext2_fs.h... yes
checking linux/blkzoned.h usability... yes
checking linux/blkzoned.h presence... yes
checking for linux/blkzoned.h... yes
checking for struct blk_zone.capacity... no
checking for BLKGETZONESZ defined in linux/blkzoned.h... yes
configure: error: linux/blkzoned.h does not provide blk_zone.capacity
make[3]: *** [Makefile:100: /workdir/openwrt/build_dir/target-aarch64_generic_musl/btrfs-progs-v5.16.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#1.28#0.64#1.55
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: Leaving directory '/workdir/openwrt'
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by bleach1991** [comment]
一样

**Comment by Mousehk** [comment]
同样问题

**Comment by tpwonder** [comment]
一样的问题，昨天开始的

**Comment by wekingchen** [comment]
一样的问题，N1盒子：

make[3]: *** [Makefile:100: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/btrfs-progs-v5.16.1/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/utils/btrfs-progs'
time: package/feeds/packages/btrfs-progs/compile#1.46#0.95#1.95
    ERROR: package/feeds/packages/btrfs-progs failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/btrfs-progs/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by btguigui** [comment]
[ipq40xx]，也报错

**Comment by WYC-2020** [comment]
https://github.com/kdave/btrfs-progs/commit/431dc7021c43e43658af436208182f8680e15fe2
@Mousehk 
@wekingchen 
@bleach1991 
@ZZMHA227 
@btguigui

**Comment by tpwonder** [comment]
感觉问题处在btrfs的文件系统支持上，打算先不选择btrfs支持再compile试试看

**Comment by WYC-2020** [comment]
算了我来做一个补丁吧

**Comment by tpwonder** [comment]
> 算了我来做一个补丁吧

Thanks!

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/packages/commit/74b200f20a1a6161b120be383b766e7b0ab1bdec
@Mousehk 
@wekingchen 
@bleach1991 
@ZZMHA227 
@btguigui

**Comment by wekingchen** [comment]
@WYC-2020 谢谢，我试试

rm -rf ./feeds/packages/utils/btrfs-progs
svn co https://github.com/WYC-2020/packages/trunk/utils/btrfs-progs ./feeds/packages/utils/btrfs-progs
