### ISSUE TITLE
很多插件都消失了，发生什么了？

### ISSUE THREAD

**Issue by kleisth** [coolsnowwolf/lede#8903]
不明所以。。。连主题都删完了，发生什么了？是不想再更新了吗？如果是麻烦提前通知下。。。

**Comment by mitsukileung** [comment]
消失？找下之前的PR看看吧

**Comment by AXBNG** [comment]
神tm消失，就算不会看PR你在issue里也能找到别人发的类似问题.......

**Comment by hcym** [comment]
一切正常，正在用test核编译，有点紧张

**Comment by minlang112** [comment]
学医救不了眼神不好
