### ISSUE TITLE
新路由D2 5.4内核升级固件只重启不更新系统

### ISSUE THREAD

**Issue by maxmib** [coolsnowwolf/lede#8904]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：新路由D2升级固件只重启不更新系统,不管是通过web还是ssh 命令，只会重启不会更新系统，只能进breed刷固件或者不保存配置升级，内核版本是5.4到5.4，不是跨大版本升级

### (2) 路由器型号和固件版本

A：

Newifi-D2  目前使用的版本OpenWrt R22.2.2 / LuCI Master (git-22.046.49039-d9baa31)

### (3) 详细日志

A：`root@OpenWrt:/tmp/upload# sysupgrade openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
Sat Feb 19 08:31:51 CST 2022 upgrade: Saving config files...
Sat Feb 19 08:31:52 CST 2022 upgrade: Commencing upgrade. Closing all shell sessions.
`

**Comment by rshi0212** [comment]
你的newifi d2有重启后wifi不自动启动的问题嘛？

**Comment by maxmib** [comment]
> 你的newifi d2有重启后wifi不自动启动的问题嘛？

我不用D2的无线，所以不清楚

**Comment by ayancn** [comment]
用前几天的版本,就是编译出来比最新的大的固件,才能升级成功,同样问题不清楚怎么回事.最新固件编译出来小很多.不能正常更新

**Comment by hackyes** [comment]
> 你的newifi d2有重启后wifi不自动启动的问题嘛？

wifi不能自启还没修复，我也是这种情况，目前在启动那里添加个 /sbin/mtkwifi restart 可以解决

**Comment by maxmib** [comment]
重置后刷新固件再重新配置恢复正常了
