### ISSUE TITLE
是否可以自己添加别的feeds.conf.default文件,用于保存自己的源

### ISSUE THREAD

**Issue by joesdu** [coolsnowwolf/lede#8905]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
每次官方的feeds.conf.default文件发生变化后,都需要重新更改这个文件,是否可以自己添加其他配置文件来保存自己的配置信息,不修改官方的feeds.conf.default
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
云编译 直接替换就是了，不是有现成的列子

**Comment by kiddin9** [comment]
有 feeds.conf 的情况下 就不会使用feeds.conf.default 了.

**Comment by binge8** [comment]
> 云编译 直接替换就是了，不是有现成的列子

麻烦大佬，咨询两个问题

**Comment by xiexiaosheng** [comment]
你可以先把feeds.conf.default 给备份，然后rm -rf feeds.conf.default，然后再git pull

**Comment by binge8** [comment]
> 你可以先把feeds.conf.default 给备份，然后rm -rf feeds.conf.default，然后再git pull

请教大佬，L大源码云编译，feeds.conf.default里添加了另一个仓库feeds，如果有重复软件包，默认是选择L大的，那如果我想选择另一个仓库里的软件包，该怎么操作

**Comment by joesdu** [comment]
> 会使用feeds.conf.default 了
了解了.
