### ISSUE TITLE
mvebu 无线设置系统日志报错

### ISSUE THREAD

**Issue by edmondfr** [coolsnowwolf/lede#891]
Sat Dec  8 12:15:43 2018 user.notice mac80211: Failed command: iw phy phy0 set antenna all all
Sat Dec  8 12:15:43 2018 user.notice mac80211: Failed command: iw phy phy1 set antenna all all
Sat Dec  8 12:15:43 2018 daemon.notice netifd: radio1 (1727): command failed: Not supported (-95)
Sat Dec  8 12:15:43 2018 daemon.notice netifd: radio0 (1726): command failed: Not supported (-95)
Sat Dec  8 12:15:43 2018 user.notice mac80211: Failed command: iw phy phy1 set distance 0
Sat Dec  8 12:15:43 2018 user.notice mac80211: Failed command: iw phy phy0 set distance 0

使用大雕版本编译，系统日志一直都有报错，经常反复出现。而是用官方源码编译则没有这些报错，请教各位老师，是否需要在哪里进行设置？感谢!

**Comment by fuqiang03** [comment]
这个问题我也出现过 按照字面的理解 有些命令没有支持 目前无解中
