### ISSUE TITLE
5.15.23 内核不显示图表了。要咋搞？

### ISSUE THREAD

**Issue by flyhong666** [coolsnowwolf/lede#8913]
5.15.23 内核不显示图表了。要咋搞？之前5.15.15 都正常的。是不是将luci 相关程序大规模挪动后有影响？
![image](https://user-images.githubusercontent.com/76857714/154833697-9c462384-2406-48ea-b4b3-2436120a1b61.png)

**Comment by WYC-2020** [comment]
不可能，移动库和这个没关系

**Comment by flyhong666** [comment]
> 不可能，移动库和这个没关系

那时是情况造成？

**Comment by flyhong666** [comment]
> 不可能，移动库和这个没关系

那时是情况造成？

**Comment by WYC-2020** [comment]
luci 位置变动只会导致 引用的位置变化，不会导致这个问题，除非删除的版本 和那边新加的版本不一致，或者是你源有多个重复的，此时-f 命令不会覆盖不是在lede 目录下的，会根据你源的顺序来使用第一次遇到的哪个包，这个没时间去看，你这个是什么包嘛，我编译看下

**Comment by flyhong666** [comment]
> luci 位置变动只会导致 引用的位置变化，不会导致这个问题，除非删除的版本 和那边新加的版本不一致，或者是你源有多个重复的，此时-f 命令不会覆盖不是在lede 目录下的，会根据你源的顺序来使用第一次遇到的哪个包，这个没时间去看，你这个是什么包嘛，我编译看下

luci-app-vnstat

**Comment by WYC-2020** [comment]
一切正常呢 
![image](https://user-images.githubusercontent.com/34025388/155075150-2985207b-5401-4976-b164-08580aaaef52.png)
![image](https://user-images.githubusercontent.com/34025388/155075168-8b28484a-44fa-45ea-be2a-9ad6436f7290.png)
@flyhong666

**Comment by flyhong666** [comment]
make clean 后也正常了。。。
