### ISSUE TITLE
git clone https://github.com/coolsnowwolf/lede到56%的时候，error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.

### ISSUE THREAD

**Issue by luohuawei168** [coolsnowwolf/lede#8915]
git clone https://github.com/coolsnowwolf/lede下载到56%的时候，就提示error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.

**Comment by 596142041** [comment]
应该是墙的问题吧

**Comment by luohuawei168** [comment]
再试试，换个梯子。
