### ISSUE TITLE
新版ssr-plus+使用GFW模式有很大概率无法从外网访问内网的NAS

### ISSUE THREAD

**Issue by wu113** [coolsnowwolf/lede#894]
[系统日志.txt](https://github.com/coolsnowwolf/lede/files/2660594/default.txt)
[内核日志.txt](https://github.com/coolsnowwolf/lede/files/2660596/default.txt)
新版ssr-plus+使用GFW模式有很大概率无法从外网访问内网的NAS，但是用绕过大陆IP模式就没问题。

**Comment by coolsnowwolf** [comment]
无法判断
