### ISSUE TITLE
package/lean/libcryptopp在线编译失败

### ISSUE THREAD

**Issue by Cptmacmillan2022007** [coolsnowwolf/lede#8942]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：

 ERROR: package/lean/libcryptopp failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1

**Comment by WYC-2020** [comment]
用单线程，这个我记得我修复过，你日志贴单线程的

**Comment by Cptmacmillan2022007** [comment]
我这就是单线程编译的啊

2022.2.24之前的源码编译该组件没有问题

**Comment by Cptmacmillan2022007** [comment]
> @Cptmacmillan2022007 [WYC-2020/lede@6b51bc9](https://github.com/WYC-2020/lede/commit/6b51bc92f9161e9d2fe4e5f8b9890aa3adcc48ab) 参考我这个升级试下，我这边是正常的

对就是libcrypto版本太老没有更新

lean源码的libcrypto版本是5.x

官网最新的已经8.x了

**Comment by Cptmacmillan2022007** [comment]
> 你这个单线程就这么点日志 不可能吧，是云编译的？ @Cptmacmillan2022007

是在线编译的

**Comment by tianiue** [comment]
Configuring luci-i18n-nlbwmon-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/runner/work/lede/lede'
make[1]: *** [package/Makefile:111: /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/runner/work/lede/lede'
make: *** [/home/runner/work/lede/lede/include/toplevel.mk:230: world] Error 2

**Comment by Cptmacmillan2022007** [comment]
已经修复了，可以关闭

**Comment by sxml** [comment]
> > 你这个单线程就这么点日志 不可能吧，是云编译的？ @Cptmacmillan2022007
> 
> 是在线编译的

云编译 经常遇到ERROR: package/lean/libcryptopp failed to build 大佬怎么解决
