### ISSUE TITLE
能否自由选择编译器？

### ISSUE THREAD

**Issue by Canary233** [coolsnowwolf/lede#8943]
自行选择编译器为clang或者gcc

**Comment by WYC-2020** [comment]
工具编译链目前就是gcc，用其他编译链不保证第三方库出各种问题，并且这个op 应该是没有地方指定用另外的工具链吧

**Comment by ZeaKyX** [comment]
内核编译用clang折腾一下可能有点意义

**Comment by Canary233** [comment]
> 工具编译链目前就是gcc，用其他编译链不保证第三方库出各种问题，并且这个op 应该是没有地方指定用另外的工具链吧

只指定内核编译器为clang应该不会影响其他的软件包吧

**Comment by kisaragychihaya** [comment]
Op的编译过程就是先用系统的编译器编译出toolchain里面的编译器 再用toolchain编译器编译系统，，，，，，，感觉折腾没啥意义
