### ISSUE TITLE
云编译显示错误信息，但固件生成了

### ISSUE THREAD

**Issue by felixxiao99** [coolsnowwolf/lede#8950]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：云编译显示错误信息，但固件生成了

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：
 make[3] -C feeds/packages/lang/python/python3 host-compile
 make[3] -C feeds/luci/applications/luci-app-vlmcsd compile
 make[3] -C feeds/packages/libs/glib2 compile
 make[3] -C feeds/packages/utils/lm-sensors compile
 make[3] -C feeds/packages/utils/kmod compile
 make[3] -C feeds/packages/libs/glib2 host-compile
    ERROR: package/feeds/packages/glib2 [host] failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile

**Comment by alan21j** [comment]
make[9]: *** [scripts/Makefile.build:280: drivers/net/ethernet/ralink/mtk_eth_soc.o] Error 1
make[8]: *** [scripts/Makefile.build:497: drivers/net/ethernet/ralink] Error 2
make[7]: *** [scripts/Makefile.build:497: drivers/net/ethernet] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/net] Error 2
make[5]: *** [Makefile:1822: drivers] Error 2
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.100'
make[4]: *** [Makefile:25: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.10.100/.modules] Error 2
make[3]: *** [Makefile:11: compile] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/ramips'
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#3.89#1.21#4.85
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:18: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.







Run cd openwrt/bin/targets/*/*
  cd openwrt/bin/targets/*/*
  rm -rf packages
  echo "FIRMWARE=$PWD" >> $GITHUB_ENV
  echo "::set-output name=status::success"
  shell: /usr/bin/bash -e {0}
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: timecloud.config
    DIY_P1_SH: diy-part1.sh
    DIY_P2_SH: diy-part2.sh
    UPLOAD_BIN_DIR: false
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    UPLOAD_RELEASE: true
    TZ: Asia/Taipei
/home/runner/work/_temp/bb9c77c4-5e8d-47c3-b969-7770562613e4.sh: line 1: cd: openwrt/bin/targets/*/*: No such file or directory
Error: Process completed with exit code 1.



同樣情況，三日前編譯還是正常的，前天開始就出現如上情況了。

**Comment by kvers** [comment]
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Terminated
Error: Process completed with exit code 143.
云编译报错了
