### ISSUE TITLE
刚源码库更新后X86 编译失败

### ISSUE THREAD

**Issue by baodp** [coolsnowwolf/lede#8951]
WARNING: Makefile 'package/feeds/packages/bmx7-dnsupdate/Makefile' has a dependency on 'bmx7', which does not exist
WARNING: Makefile 'package/feeds/packages/bmx7-dnsupdate/Makefile' has a dependency on 'bmx7-json', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-ahcp/Makefile' has a dependency on 'ahcpd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-easymesh/Makefile' has a dependency on 'batctl-default', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-easymesh/Makefile' has a dependency on 'kmod-batman-adv', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr/Makefile' has a dependency on 'olsrd-mod-jsoninfo', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-services/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-services/Makefile' has a dependency on 'olsrd-mod-nameservice', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-viz/Makefile' has a dependency on 'olsrd', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-olsr-viz/Makefile' has a dependency on 'olsrd-mod-txtinfo', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6-json', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx7-json', which does not exist
make[1]: Entering directory '/home/bdp/lede'
make[2]: Entering directory '/home/bdp/lede'
make[2]: Entering directory '/home/bdp/lede'
rm -rf /home/bdp/lede/staging_dir/target-x86_64_musl/root-x86
+ mkdir -p /home/bdp/lede/staging_dir/target-x86_64_musl
+ mkdir -p /home/bdp/lede/staging_dir/host
+ cd /home/bdp/lede/staging_dir/target-x86_64_musl
+ mkdir -p bin lib stamp usr/include usr/lib
+ cd /home/bdp/lede/staging_dir/host
+ mkdir -p bin lib stamp usr/include usr/lib
mkdir -p /home/bdp/lede/build_dir/target-x86_64_musl/stamp
mkdir -p /home/bdp/lede/build_dir/host/stamp /home/bdp/lede/staging_dir/host/include/sys
touch /home/bdp/lede/staging_dir/target-x86_64_musl/.prepared
install -m0644 /home/bdp/lede/tools/include/*.h /home/bdp/lede/staging_dir/host/include/
install -m0644 /home/bdp/lede/tools/include/sys/*.h /home/bdp/lede/staging_dir/host/include/sys/
ln -snf lib /home/bdp/lede/staging_dir/host/lib64
touch /home/bdp/lede/staging_dir/host/.prepared
make[3]: Entering directory '/home/bdp/lede/tools/flock'
make[3]: Leaving directory '/home/bdp/lede/tools/flock'
time: tools/flock/compile#0.01#0.00#0.02
make[3]: Entering directory '/home/bdp/lede/tools/xz'
make[2]: Leaving directory '/home/bdp/lede'
make[3]: Leaving directory '/home/bdp/lede/tools/xz'
time: tools/xz/compile#0.02#0.00#0.04
make[3]: Entering directory '/home/bdp/lede/tools/sed'
make[3]: Leaving directory '/home/bdp/lede/tools/sed'
time: tools/sed/compile#0.02#0.00#0.03
make[3]: Entering directory '/home/bdp/lede/tools/tar'
make[3]: Entering directory '/home/bdp/lede/tools/patch'
make[3]: Leaving directory '/home/bdp/lede/tools/patch'
time: tools/patch/compile#0.02#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/tar'
time: tools/tar/compile#0.02#0.00#0.03
make[3]: Entering directory '/home/bdp/lede/tools/pkgconf'
make[3]: Entering directory '/home/bdp/lede/tools/m4'
make[3]: Entering directory '/home/bdp/lede/tools/ninja'
make[3]: Entering directory '/home/bdp/lede/tools/autoconf-archive'
make[3]: Entering directory '/home/bdp/lede/tools/cpio'
make[3]: Entering directory '/home/bdp/lede/tools/mtools'
make[3]: Entering directory '/home/bdp/lede/tools/lzma'
make[3]: Entering directory '/home/bdp/lede/tools/patch-image'
make[3]: Entering directory '/home/bdp/lede/tools/sstrip'
make[3]: Entering directory '/home/bdp/lede/tools/expat'
make[3]: Entering directory '/home/bdp/lede/tools/xxd'
make[3]: Entering directory '/home/bdp/lede/tools/ucl'
make[3]: Entering directory '/home/bdp/lede/tools/zip'
make[3]: Leaving directory '/home/bdp/lede/tools/patch-image'
time: tools/patch-image/compile#0.05#0.00#0.06
make[3]: Leaving directory '/home/bdp/lede/tools/ninja'
time: tools/ninja/compile#0.06#0.00#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/pkgconf'
time: tools/pkgconf/compile#0.05#0.01#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/xxd'
time: tools/xxd/compile#0.05#0.00#0.06
make[3]: Leaving directory '/home/bdp/lede/tools/mtools'
time: tools/mtools/compile#0.05#0.01#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/sstrip'
time: tools/sstrip/compile#0.06#0.00#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/cpio'
time: tools/cpio/compile#0.06#0.00#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/autoconf-archive'
time: tools/autoconf-archive/compile#0.05#0.02#0.07
make[3]: Leaving directory '/home/bdp/lede/tools/expat'
time: tools/expat/compile#0.05#0.00#0.07
make[3]: Entering directory '/home/bdp/lede/tools/libressl'
make[3]: Entering directory '/home/bdp/lede/tools/meson'
make[3]: Leaving directory '/home/bdp/lede/tools/zip'
make[3]: Leaving directory '/home/bdp/lede/tools/lzma'
time: tools/zip/compile#0.06#0.00#0.07
time: tools/lzma/compile#0.05#0.01#0.08
make[3]: Leaving directory '/home/bdp/lede/tools/ucl'
time: tools/ucl/compile#0.06#0.01#0.08
make[3]: Leaving directory '/home/bdp/lede/tools/m4'
time: tools/m4/compile#0.05#0.03#0.08
make[3]: Entering directory '/home/bdp/lede/tools/upx'
make[3]: Entering directory '/home/bdp/lede/tools/autoconf'
. /home/bdp/lede/include/shell.sh; gzip -dc /home/bdp/lede/dl/meson-0.61.2.tar.gz | tar -C /home/bdp/lede/build_dir/host/meson-0.61.2/.. -xf -
make[3]: Leaving directory '/home/bdp/lede/tools/autoconf'
time: tools/autoconf/compile#0.02#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/upx'
time: tools/upx/compile#0.02#0.00#0.04
make[3]: Entering directory '/home/bdp/lede/tools/missing-macros'
make[3]: Entering directory '/home/bdp/lede/tools/automake'
make[3]: Leaving directory '/home/bdp/lede/tools/libressl'
time: tools/libressl/compile#0.04#0.00#0.06
make[3]: Leaving directory '/home/bdp/lede/tools/missing-macros'
time: tools/missing-macros/compile#0.01#0.00#0.02
make[3]: Entering directory '/home/bdp/lede/tools/cmake'
make[3]: Entering directory '/home/bdp/lede/tools/mkimage'
make[3]: Leaving directory '/home/bdp/lede/tools/automake'
time: tools/automake/compile#0.02#0.00#0.04
make[3]: Entering directory '/home/bdp/lede/tools/libtool'
make[3]: Entering directory '/home/bdp/lede/tools/dosfstools'
make[3]: Leaving directory '/home/bdp/lede/tools/dosfstools'
time: tools/dosfstools/compile#0.02#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/libtool'
time: tools/libtool/compile#0.02#0.00#0.04
make[3]: Entering directory '/home/bdp/lede/tools/flex'
make[3]: Entering directory '/home/bdp/lede/tools/e2fsprogs'
make[3]: Entering directory '/home/bdp/lede/tools/fakeroot'
make[3]: Entering directory '/home/bdp/lede/tools/mklibs'
make[3]: Entering directory '/home/bdp/lede/tools/mm-macros'
make[3]: Entering directory '/home/bdp/lede/tools/patchelf'
make[3]: Entering directory '/home/bdp/lede/tools/gengetopt'
make[3]: Entering directory '/home/bdp/lede/tools/gmp'
make[3]: Leaving directory '/home/bdp/lede/tools/flex'
time: tools/flex/compile#0.04#0.01#0.05
make[3]: Leaving directory '/home/bdp/lede/tools/mklibs'
time: tools/mklibs/compile#0.05#0.00#0.05
make[3]: Leaving directory '/home/bdp/lede/tools/patchelf'
time: tools/patchelf/compile#0.05#0.00#0.05
make[3]: Leaving directory '/home/bdp/lede/tools/mm-macros'
time: tools/mm-macros/compile#0.05#0.00#0.05
make[3]: Leaving directory '/home/bdp/lede/tools/fakeroot'
time: tools/fakeroot/compile#0.05#0.00#0.06
make[3]: Leaving directory '/home/bdp/lede/tools/gengetopt'
time: tools/gengetopt/compile#0.04#0.00#0.06
make[3]: Entering directory '/home/bdp/lede/tools/bison'
[ ! -d ./src/ ] || cp -fpR ./src/* /home/bdp/lede/build_dir/host/meson-0.61.2
touch /home/bdp/lede/build_dir/host/meson-0.61.2/.prepared317fa8f440d029b9460f550b7106033a_6664517399ebbbc92a37c5bb081b5c53
touch /home/bdp/lede/build_dir/host/meson-0.61.2/.configured
touch /home/bdp/lede/build_dir/host/meson-0.61.2/.built
install -d -m0755 /home/bdp/lede/staging_dir/host/bin
/home/bdp/lede/build_dir/host/meson-0.61.2/packaging/create_zipapp.py /home/bdp/lede/build_dir/host/meson-0.61.2 --outfile /home/bdp/lede/staging_dir/host/bin/meson.py
make[3]: Leaving directory '/home/bdp/lede/tools/gmp'
time: tools/gmp/compile#0.06#0.01#0.09
make[3]: Leaving directory '/home/bdp/lede/tools/bison'
time: tools/bison/compile#0.03#0.00#0.04
make[3]: Entering directory '/home/bdp/lede/tools/mpfr'
make[3]: Entering directory '/home/bdp/lede/tools/bc'
make[3]: Entering directory '/home/bdp/lede/tools/findutils'
make[3]: Leaving directory '/home/bdp/lede/tools/e2fsprogs'
time: tools/e2fsprogs/compile#0.05#0.02#0.14
make[3]: Leaving directory '/home/bdp/lede/tools/bc'
time: tools/bc/compile#0.03#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/mpfr'
time: tools/mpfr/compile#0.02#0.01#0.04
make[3]: Entering directory '/home/bdp/lede/tools/mpc'
make[3]: Leaving directory '/home/bdp/lede/tools/findutils'
time: tools/findutils/compile#0.03#0.01#0.05
make[3]: Entering directory '/home/bdp/lede/tools/padjffs2'
make[3]: Entering directory '/home/bdp/lede/tools/quilt'
install -d -m0755 /home/bdp/lede/staging_dir/host/lib/meson
install -m0600 files/openwrt-cross.txt.in /home/bdp/lede/staging_dir/host/lib/meson/
install -m0600 files/openwrt-native.txt.in /home/bdp/lede/staging_dir/host/lib/meson/
/home/bdp/lede/build_dir/host/meson-0.61.2/packaging/create_zipapp.py /home/bdp/lede/build_dir/host/meson-0.61.2 --outfile /home/bdp/lede/staging_dir/host/lib/meson/meson.py
make[3]: Leaving directory '/home/bdp/lede/tools/mpc'
time: tools/mpc/compile#0.02#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/padjffs2'
time: tools/padjffs2/compile#0.02#0.00#0.03
make[3]: Leaving directory '/home/bdp/lede/tools/quilt'
time: tools/quilt/compile#0.02#0.00#0.03
mkdir -p /home/bdp/lede/staging_dir/host/stamp
touch /home/bdp/lede/build_dir/host/meson-0.61.2/.built
touch /home/bdp/lede/staging_dir/host/stamp/.meson_installed
make[3]: Leaving directory '/home/bdp/lede/tools/meson'
time: tools/meson/compile#0.19#0.18#0.37
make[3]: Leaving directory '/home/bdp/lede/tools/mkimage'
time: tools/mkimage/compile#0.06#0.15#0.43
. /home/bdp/lede/include/shell.sh; gzip -dc /home/bdp/lede/dl/cmake-3.22.1.tar.gz | tar -C /home/bdp/lede/build_dir/host/cmake-3.22.1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/bdp/lede/build_dir/host/cmake-3.22.1

Applying ./patches/100-no-testing.patch using plaintext:
patching file Modules/CTest.cmake
patching file Modules/Dart.cmake
patching file Tests/Contracts/VTK/Dashboard.cmake.in
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 25 with fuzz 1.

Applying ./patches/120-curl-fix-libressl-linking.patch using plaintext:
patching file Utilities/cmcurl/CMakeLists.txt
patch unexpectedly ends in middle of line

Applying ./patches/130-bootstrap_parallel_make_flag.patch using plaintext:
patching file bootstrap
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 1423 with fuzz 1.
touch /home/bdp/lede/build_dir/host/cmake-3.22.1/.prepared8c8bb8f34847dc64d9c68969110d069f_6664517399ebbbc92a37c5bb081b5c53
(cd /home/bdp/lede/build_dir/host/cmake-3.22.1/; if [ -x configure ]; then cp -fpR /home/bdp/lede/scripts/config.{guess,sub} /home/bdp/lede/build_dir/host/cmake-3.22.1// && CC="gcc" CFLAGS="-O2 -I/home/bdp/lede/staging_dir/host/include " CXX="g++" CPPFLAGS="-I/home/bdp/lede/staging_dir/host/include " LDFLAGS="-L/home/bdp/lede/staging_dir/host/lib " CONFIG_SHELL="/usr/bin/env bash" CC="gcc" CXX="g++" MAKEFLAGS="--jobserver-auth=3,4 " CXXFLAGS="-O2 -I/home/bdp/lede/staging_dir/host/include " MAKE="/home/bdp/lede/staging_dir/host/bin/ninja"  bash ./configure --parallel="--jobserver-auth=3,4" --prefix=/home/bdp/lede/staging_dir/host ; fi )
---------------------------------------------
CMake 3.22.1, Copyright 2000-2021 Kitware, Inc. and Contributors
C compiler on this system is: gcc -O2 -I/home/bdp/lede/staging_dir/host/include
C++ compiler on this system is: g++ -O2 -I/home/bdp/lede/staging_dir/host/include
---------------------------------------------
Error when bootstrapping CMake:
Cannot find appropriate Makefile processor on this system.
Please specify one using environment variable MAKE.
---------------------------------------------
Log of errors: /home/bdp/lede/build_dir/host/cmake-3.22.1/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
make[3]: *** [Makefile:40: /home/bdp/lede/build_dir/host/cmake-3.22.1/.configured] Error 8
make[3]: Leaving directory '/home/bdp/lede/tools/cmake'
time: tools/cmake/compile#0.71#0.72#1.73
    ERROR: tools/cmake failed to build.
make[2]: *** [tools/Makefile:160: tools/cmake/compile] Error 1
make[2]: Leaving directory '/home/bdp/lede'
make[1]: *** [tools/Makefile:156: /home/bdp/lede/staging_dir/host/stamp/.tools_compile_yyynyynnyyyynyyyyyynyynnyyynyyyyyyyyyyyyyyyyyynynnyyyyyyyyyy] Error 2
make[1]: Leaving directory '/home/bdp/lede'
make: *** [/home/bdp/lede/include/toplevel.mk:230: world] Error 2

**Comment by king1393** [comment]
+1

**Comment by Beginner-Go** [comment]
别急 我看看

**Comment by baodp** [comment]
> 别急 我看看

不急，辛苦了。

**Comment by breakings** [comment]
cmake翻车了

**Comment by Beginner-Go** [comment]
现在试一试，我在本地测试过了 应该正常了

**Comment by baodp** [comment]
> 现在试一试，我在本地测试过了 应该正常了

谢谢，编译通过了。
