### ISSUE TITLE
make download时下载mtk-eip93失败

### ISSUE THREAD

**Issue by yjs507** [coolsnowwolf/lede#8952]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：2月26日pull的最新版本，make download时，下载mtk-eip93失败
看mtk-eip93历史记录，发现原来是有github本地源文件的，2月24日删除了本地源文件，改引用https://github.com/vschagen/mtk-eip93.git 进行下载，但是下载失败，不过还是可以编译成功

### (2) 路由器型号和固件版本

A：路由器wr1200js

### (3) 详细日志

A：详细日志没有了

**Comment by WYC-2020** [comment]
这种下载失败，只要你手工能打开那个源并且有这个仓库 就是你代理的问题，自己排查

**Comment by yjs507** [comment]
> 这种下载失败，只要你手工能打开那个源并且有这个仓库 就是你代理的问题，自己排查

代理是没有问题的
看mtk-iep99的说明
The 999-patch is to add the mtk-eip93 to the Kconfig / Make files in the drivers/crypto folder Add the crypto/mtk-eip93 folder to the linux drivers

OR:

add the 999-patch to the OpenWrt /target/linux/ramips/patch-5.10 folder and the crypto/mtk-eip93 folder to the /target/linux/files/drivers folder

这就不知道怎么搞了

**Comment by WYC-2020** [comment]
你自己说的是下载失败都还没到patch那块，下载不下来只能两个原因要么代理，要么地址有问题

**Comment by yjs507** [comment]
> 你自己说的是下载失败都还没到patch那块，下载不下来只能两个原因要么代理，要么地址有问题

编译openwrt是小白水平，网络肯定无问题的，地址是Makefile里面设置的，怎么打patch之类的不会
刚才又搞了一下，具体download两个错误
-------------------------------------------------------------
SHELL= flock /home/yjs/lede/tmp/.linux-5.11.16.tar.xz.flock -c '        /home/yjs/lede/scripts/download.pl "/home/yjs/lede/dl" "linux-5.11.16.tar.xz" "21163681d130cbce5a6be39019e2c69e44f284855ddd70b1a3bd039249540f43" "" "@KERNEL/linux/kernel/v5.x"    '
grep: /home/yjs/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.4.175/.config: No such file or directory
--------------------------------------------------------------
mtk-eip93-2020-12-10-bb5fd1c8.tar.xz: Download from https://github.com/vschagen/mtk-eip93.git failed
mtk-eip93-2020-12-10-bb5fd1c8.tar.xz: Wrong hash (probably caused by .gitattributes), expecting cb114b29f7e06e817341adb9127c4d053592be53356a64d932cf7ba418606260, got d2a4c5da7fb695e575de4b4335b73dcbfea195ef76791133d36287065a66386b

**Comment by WYC-2020** [comment]
你这个是hash检验失败嘛，不是下载失败，更新一下就可以了
@yjs507

**Comment by WYC-2020** [comment]
@yjs507  https://github.com/WYC-2020/lede/commit/431441fa0ae4f1bc32f68491d18d95faeee6c7b0
