### ISSUE TITLE
sfe能兼容多拨吗

### ISSUE THREAD

**Issue by laobanbiefangcu** [coolsnowwolf/lede#8958]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：单线四拨后，开了sfe，只有wan1的ip可以ping通，其他三个ip ping不通。不开的话，cpu占用会变高，nat转发效率变低

### (2) 路由器型号和固件版本

A：x86，cpu i5 11500，内核5.15.25

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
不开sfe那ip能ping通几个嘛，你这问题描述的答非所问啊

**Comment by laobanbiefangcu** [comment]
> 不开sfe那ip能ping通几个嘛，你这问题描述的答非所问啊

不开sfe能ping通，上行也能叠加，但是cpu使用率会变高。开了后，只能ping通一个ip，上行叠加不了

**Comment by WYC-2020** [comment]
https://www.right.com.cn/forum/thread-333361-1-1.html  看下这个吧，或者你直接去sfe 的仓库提问看下吧
@laobanbiefangcu

**Comment by laobanbiefangcu** [comment]
> https://www.right.com.cn/forum/thread-333361-1-1.html 看下这个吧，或者你直接去sfe 的仓库提问看下吧 @laobanbiefangcu

好的，非常感谢！
