### ISSUE TITLE
云编译5.10内核出错

### ISSUE THREAD

**Issue by tianiue** [coolsnowwolf/lede#8959]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
[开始编译固件.txt](https://github.com/coolsnowwolf/lede/files/8148794/default.txt)

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/155911614-a1dcf44c-e846-4bd0-a560-456c19ba3b87.png)
老问题了 搜索相关的issue 这个问题遇到的最多
