### ISSUE TITLE
同步最新源后，make defconfig问题

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#8968]
同步最新源后出现
X86
oyko@ubuntu:~/lede$ make defconfig
tmp/.config-package.in:88750:error: recursive dependency detected!
tmp/.config-package.in:88750:	symbol PACKAGE_amule is selected by PACKAGE_antileech
tmp/.config-package.in:88778:	symbol PACKAGE_antileech is selected by PACKAGE_amule
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

**Comment by WYC-2020** [comment]
自己到哪里更新的组合哦，PACKAGE_antileech这个玩意应该没有哦

**Comment by mitsukileung** [comment]
> 自己到哪里更新的组合哦，PACKAGE_antileech这个玩意应该没有哦

我没有选这个插件，更新后就这样了

**Comment by yunxi993** [comment]
我也去试试

**Comment by Beginner-Go** [comment]
似乎好了
