### ISSUE TITLE
X86  最新更新源码库以后，默认配置 编译不了

### ISSUE THREAD

**Issue by baodp** [coolsnowwolf/lede#8969]
Applying /home/bdp/lede/target/linux/generic/pending-5.15/530-jffs2_make_lzma_available.patch using plaintext:
patching file fs/jffs2/Kconfig
patching file fs/jffs2/Makefile
patching file fs/jffs2/compr.c
patching file fs/jffs2/compr.h
patching file fs/jffs2/compr_lzma.c
patching file fs/jffs2/super.c
patching file include/linux/lzma.h
patching file include/linux/lzma/LzFind.h
patching file include/linux/lzma/LzHash.h
patching file include/linux/lzma/LzmaDec.h
patching file include/linux/lzma/LzmaEnc.h
patching file include/linux/lzma/Types.h
patching file include/uapi/linux/jffs2.h
patching file lib/Kconfig
patching file lib/Makefile
patching file lib/lzma/LzFind.c
patching file lib/lzma/LzmaDec.c
patching file lib/lzma/LzmaEnc.c
patching file lib/lzma/Makefile

Applying /home/bdp/lede/target/linux/generic/pending-5.15/532-jffs2_eofdetect.patch using plaintext:
patching file fs/jffs2/build.c
patching file fs/jffs2/scan.c

Applying /home/bdp/lede/target/linux/generic/pending-5.15/600-netfilter_conntrack_flush.patch using plaintext:
patching file net/netfilter/nf_conntrack_standalone.c

Applying /home/bdp/lede/target/linux/generic/pending-5.15/610-netfilter_match_bypass_default_checks.patch using plaintext:
patching file include/uapi/linux/netfilter_ipv4/ip_tables.h
patching file net/ipv4/netfilter/ip_tables.c

Applying /home/bdp/lede/target/linux/generic/pending-5.15/611-netfilter_match_bypass_default_table.patch using plaintext:
patching file net/ipv4/netfilter/ip_tables.c

Applying /home/bdp/lede/target/linux/generic/pending-5.15/612-netfilter_match_reduce_memory_access.patch using plaintext:
patching file net/ipv4/netfilter/ip_tables.c

Applying /home/bdp/lede/target/linux/generic/pending-5.15/613-netfilter_optional_tcp_window_check.patch using plaintext:
patching file net/netfilter/nf_conntrack_proto_tcp.c
patching file net/netfilter/nf_conntrack_standalone.c
patch: **** malformed patch at line 54:  };

Patch failed!  Please fix /home/bdp/lede/target/linux/generic/pending-5.15/613-netfilter_optional_tcp_window_check.patch!
make[4]: *** [Makefile:35: /home/bdp/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.25/.prepared_0e58b68b26aed9e2e80f0abc457e1a20] Error 1
make[4]: Leaving directory '/home/bdp/lede/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/bdp/lede/target/linux'
time: target/linux/compile#7.20#6.19#10.85
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/bdp/lede'
make[1]: *** [target/Makefile:18: /home/bdp/lede/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/bdp/lede'
make: *** [/home/bdp/lede/include/toplevel.mk:230: world] Error 2

**Comment by WYC-2020** [comment]
是新提交的pr有问题

**Comment by qqsir-dev** [comment]
一样的问题

**Comment by knlvz** [comment]
我也遇到了这个编译错误

**Comment by hicaoc** [comment]
同样的错误

**Comment by hicaoc** [comment]
> revert [2d15f51](https://github.com/coolsnowwolf/lede/commit/2d15f51c44b1e884488658c89a4eb13581099507) 这个提交，或者自己合并一下lede 新增的哪个pr，我这边没有测试，你们可以测试一下，我用另外一个方法修复了下这个问题 [WYC-2020/lede@f60db60](https://github.com/WYC-2020/lede/commit/f60db604f07165d5cd8f7a98be6890180c790513)

新的那个pr可以解决，已经编译过

**Comment by WYC-2020** [comment]
@hicaoc 嗯可以，我暂时不改了就用我目前哪个修改方法

**Comment by Dawneng** [comment]
我直接滚回上一次提交

**Comment by baodp** [comment]
好了 有人更新了。能编译了。
