### ISSUE TITLE
dnsforwarder仍然不能正确运行！

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#897]
![image](https://user-images.githubusercontent.com/17406910/49717131-fc1c3f80-fc90-11e8-8a1d-b0bdc68c90a3.png)

**Comment by shenzt68** [comment]
即使重启后，也不能运行dnsforwarder

**Comment by d975xbx** [comment]
一样的问题，ssr v2 今天编译的固件也不能运行。echo 0xDEADBEEF > /etc/config/google_fu_mode

**Comment by hcym** [comment]
v2能运行啊！不过要重启两次，也没有开彩蛋。呵呵

**Comment by d975xbx** [comment]
plus里面的v2不能运行，不知道什么原因。已经回滚到以前的固件。
