### ISSUE TITLE
Q10pro5.10版本,无线正常,网口全部失灵,日志显示 Failed to connect to the switch

### ISSUE THREAD

**Issue by iowclz** [coolsnowwolf/lede#8973]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
Q10pro5.10版本,无线正常,网口全部失灵,日志显示交换机初始化问题
### (1) 具体问题
Q10pro5.10版本,无线正常,网口全部失灵,日志显示交换机初始化问题
A：

### (2) 路由器型号和固件版本
Q10PRO
A：

### (3) 详细日志
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.822767] xt_time: kernel timezone is -0000
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.880598] mt7621-pci 1e140000.pcie: bus=1 slot=0 irq=24
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.886029] pci 0000:00:00.0: enabling device (0006 -> 0007)
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.891712] mt7915e_hif 0000:01:00.0: enabling device (0000 -> 0002)
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.898559] mt7621-pci 1e140000.pcie: bus=2 slot=1 irq=25
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.904048] pci 0000:00:01.0: enabling device (0006 -> 0007)
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.909740] mt7915e 0000:02:00.0: enabling device (0000 -> 0002)
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.939934] mt7915e 0000:02:00.0: HW/SW Version: 0x8a108a10, Build Time: 20201105222230a
Wed Mar  2 02:21:23 2022 kern.info kernel: [   16.939934]
Wed Mar  2 02:21:23 2022 kern.info kernel: [   17.268261] mt7915e 0000:02:00.0: WM Firmware Version: ____000000, Build Time: 20201105222304
Wed Mar  2 02:21:23 2022 kern.info kernel: [   17.302479] mt7915e 0000:02:00.0: WA Firmware Version: DEV_000000, Build Time: 20201105222323
Wed Mar  2 02:21:23 2022 kern.info kernel: [   17.472337] PPP generic driver version 2.4.2
Wed Mar  2 02:21:23 2022 kern.info kernel: [   17.478619] PPP MPPE Compression module registered
Wed Mar  2 02:21:23 2022 kern.info kernel: [   17.484894] NET: Registered protocol family 24
Wed Mar  2 02:21:23 2022 user.info kernel: [   17.503737] kmodloader: done loading kernel modules from /etc/modules.d/*
Wed Mar  2 02:21:23 2022 kern.notice kernel: [   18.341948] random: crng init done
Wed Mar  2 02:21:23 2022 daemon.notice procd: /etc/rc.d/S13openssl: Generating engines.cnf
Wed Mar  2 02:21:23 2022 daemon.notice procd: /etc/rc.d/S13openssl: Enabling engine devcrypto
Wed Mar  2 02:21:24 2022 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Mar  2 02:21:24 2022 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
**Wed Mar  2 02:21:44 2022 daemon.notice procd: /etc/rc.d/S20network: Failed to connect to the switch. Use the "list" command to see which switches are available.**
Wed Mar  2 02:21:44 2022 daemon.notice wpa_supplicant[1691]: Successfully initialized wpa_supplicant
Wed Mar  2 02:21:44 2022 daemon.err block: No "mount.ubi" utility available
Wed Mar  2 02:21:44 2022 daemon.err block: mounting /dev/mtdblock7 (ubi) as /mnt/mtdblock7 failed (25) - Not a tty
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: 8021ad
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: 8021q
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: macvlan
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: veth
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: bridge
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: Network device
Wed Mar  2 02:21:44 2022 user.notice : Added device handler type: tunnel
Wed Mar  2 02:21:45 2022 cron.err crond[1814]: crond (busybox 1.35.0) started, log level 5
Wed Mar  2 02:21:45 2022 daemon.err uhttpd[1880]: socket(): Address family not supported by protocol
Wed Mar  2 02:21:45 2022 daemon.err uhttpd[1880]: socket(): Address family not supported by protocol
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'loopback' is enabled
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'loopback' is setting up now
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'loopback' is now up
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'lan' is enabled
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'lan' is setting up now
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'lan' is now up
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Network device 'lo' link is up
Wed Mar  2 02:21:47 2022 daemon.notice netifd: Interface 'loopback' has link connectivity
Wed Mar  2 02:21:48 2022 daemon.info procd: - init complete -
Wed Mar  2 02:21:48 2022 authpriv.info dropbear[2382]: Not backgrounding
Wed Mar  2 02:21:48 2022 daemon.info urandom_seed[2267]: Seed saved (/etc/urandom.seed)
Wed Mar  2 02:21:49 2022 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy0.conf (phy wlan0) --> new PHY
Wed Mar  2 02:21:50 2022 kern.info kernel: [   54.974938] br-lan: port 1(wlan0) entered blocking state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   54.980343] br-lan: port 1(wlan0) entered disabled state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   54.986107] device wlan0 entered promiscuous mode
Wed Mar  2 02:21:50 2022 kern.info kernel: [   54.991620] br-lan: port 1(wlan0) entered blocking state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   54.996975] br-lan: port 1(wlan0) entered forwarding state
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Mar  2 02:21:50 2022 daemon.notice netifd: bridge 'br-lan' link is up
Wed Mar  2 02:21:50 2022 daemon.notice netifd: Interface 'lan' has link connectivity
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.003357] br-lan: port 1(wlan0) entered disabled state
Wed Mar  2 02:21:50 2022 daemon.notice netifd: bridge 'br-lan' link is down
Wed Mar  2 02:21:50 2022 daemon.notice netifd: Interface 'lan' has link connectivity loss
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.019364] br-lan: port 1(wlan0) entered blocking state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.024771] br-lan: port 1(wlan0) entered forwarding state
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy1.conf (phy wlan1) --> new PHY
Wed Mar  2 02:21:50 2022 daemon.notice netifd: bridge 'br-lan' link is up
Wed Mar  2 02:21:50 2022 daemon.notice netifd: Interface 'lan' has link connectivity
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.273508] br-lan: port 2(wlan1) entered blocking state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.278884] br-lan: port 2(wlan1) entered disabled state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.284598] device wlan1 entered promiscuous mode
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.289738] br-lan: port 2(wlan1) entered blocking state
Wed Mar  2 02:21:50 2022 kern.info kernel: [   55.295076] br-lan: port 2(wlan1) entered forwarding state
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: wlan1: interface state COUNTRY_UPDATE->HT_SCAN
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: wlan0: interface state COUNTRY_UPDATE->ENABLED
Wed Mar  2 02:21:50 2022 daemon.notice hostapd: wlan0: AP-ENABLED
Wed Mar  2 02:21:51 2022 daemon.notice hostapd: wlan1: interface state HT_SCAN->ENABLED
Wed Mar  2 02:21:51 2022 daemon.notice hostapd: wlan1: AP-ENABLED
Wed Mar  2 02:21:52 2022 daemon.notice netifd: Network device 'wlan1' link is up
Wed Mar  2 02:21:52 2022 daemon.notice netifd: Network device 'wlan0' link is up
Wed Mar  2 02:22:11 2022 daemon.info hostapd: wlan1: STA a4:c4:94:ae:50:fb IEEE 802.11: authenticated
Wed Mar  2 02:22:11 2022 daemon.info hostapd: wlan1: STA a4:c4:94:ae:50:fb IEEE 802.11: associated (aid 1)
Wed Mar  2 02:22:11 2022 daemon.notice hostapd: wlan1: AP-STA-CONNECTED a4:c4:94:ae:50:fb
Wed Mar  2 02:22:11 2022 daemon.info hostapd: wlan1: STA a4:c4:94:ae:50:fb RADIUS: starting accounting session CBE720C24E4C603B
Wed Mar  2 02:22:11 2022 daemon.notice hostapd: wlan1: STA-OPMODE-SMPS-MODE-CHANGED a4:c4:94:ae:50:fb off
Wed Mar  2 02:22:47 2022 daemon.err uhttpd[1880]: Failed to connect to the switch. Use the "list" command to see which switches are available.
Wed Mar  2 02:22:52 2022 daemon.err uhttpd[1880]: Failed to connect to the switch. Use the "list" command to see which switches are available.
Wed Mar  2 02:22:57 2022 daemon.err uhttpd[1880]: Failed to connect to the switch. Use the "list" command to see which switches are available.

A：

**Comment by AmadeusGhost** [comment]
换回 5.4 内核即可...
