### ISSUE TITLE
请问一下这错误怎样解缺！

### ISSUE THREAD

**Issue by HAN5201** [coolsnowwolf/lede#8977]
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/hweight.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/clear_page_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/copy_page_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/copy_user_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/getuser.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/memcpy_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/memmove_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/memset_64.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/putuser.o' being placed in section `__ksymtab_strings'
x86_64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/x86/lib/retpoline.o' being placed in section `__ksymtab_strings'

**Comment by WYC-2020** [comment]
这是警告，和节有关 不用在意
