### ISSUE TITLE
自动挂载ntfs磁盘分区失败，因为缺少/sbin/mount.ntfs这个软链接

### ISSUE THREAD

**Issue by cary-zhou** [coolsnowwolf/lede#8985]
/sbin/mount.ntfs这个软链接，源文件应该是/usr/bin/ntfs-3g
![image](https://user-images.githubusercontent.com/12585727/156411285-5f32ee6a-1757-4aa8-b35e-d20bb9594f38.png)
ntfs-3g的makefile文件只创建了/sbin/mount.ntfs-3g，但未创建/sbin/mount.ntfs，按如下修改ntfs-3g的makefile文件重新编译固件
即可实现开机自动挂载ntfs格式的分区：
![image](https://user-images.githubusercontent.com/12585727/156412141-c991c0d1-77f3-4077-a946-1cd53a516bb4.png)

**Comment by Beginner-Go** [comment]
提个pr？😁

**Comment by WYC-2020** [comment]
直接修改上一条指令就行了吧，没必要搞那么多软连接吧，3g应该是不会有人用了

**Comment by coolsnowwolf** [comment]
ntfs-3g 已经淘汰了，用新的 ntfs3

**Comment by cary-zhou** [comment]
原来如此，感谢指导。
