### ISSUE TITLE
不管怎样都无法更新源码请问怎样解缺！

### ISSUE THREAD

**Issue by HAN5201** [coolsnowwolf/lede#8986]
Run [ -e files ] && mv files openwrt/files
sed: -e expression #1, char 25: unterminated `s' command
Error: Process completed with exit code 1.

**Comment by baodp** [comment]
我是删了重新来。

**Comment by ggllioio** [comment]
把/dl复制出来，整个文件夹删了重来

**Comment by HAN5201** [comment]
我是云编译怎样删
