### ISSUE TITLE
执行make menuconfig报错

### ISSUE THREAD

**Issue by lxnmail** [coolsnowwolf/lede#8995]
make menuconfig
Collecting package info: done
WARNING: Makefile 'package/feeds/packages/podman/Makefile' has a dependency on 'uci-firewall', which does not exist
WARNING: Makefile 'package/feeds/packages/podman/Makefile' has a dependency on 'uci-firewall', which does not exist
configuration written to .config

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

全新的编译环境，报错如上图所示。

**Comment by Dawneng** [comment]
packages 库那边更新了这个导致的

**Comment by Beginner-Go** [comment]
别急 等会我去弄

**Comment by chaochao666666** [comment]
> packages 库那边更新了这个导致的
请问如何解决呢？我也遇到了一样的问题。谢谢。

**Comment by Dawneng** [comment]
> > packages 库那边更新了这个导致的
> > 请问如何解决呢？我也遇到了一样的问题。谢谢。

更新即可   已经滚回了

**Comment by chaochao666666** [comment]
谢谢，我去试试，会的真快。

**Comment by unpredictablexxm** [comment]
我把库全都更新了一遍，但是还是不行欸...
