### ISSUE TITLE
今天编译遇到新问题,麻烦各位帮忙看一下

### ISSUE THREAD

**Issue by dengchan0416** [coolsnowwolf/lede#8997]
![photo_2022-03-04_08-48-49](https://user-images.githubusercontent.com/41529838/156678060-cb87ecaf-cd48-4ca1-ac73-016440358198.jpg)

WARNING: Not overriding core package 'dante'; use -f to force
今天编译遇到这个问题怎样解决。昨天还好好的

**Comment by WYC-2020** [comment]
这算什么问题，也就包重复而已，看下提示都清楚的
