### ISSUE TITLE
编译错误，求解决

### ISSUE THREAD

**Issue by mrw79** [coolsnowwolf/lede#9]
checking for mempcpy... (cached) yes
checking for memrchr... yes
checking whether mkdir handles trailing slash... yes
checking whether mkdir handles trailing dot... yes
checking for mkdtemp... yes
checking whether mkfifo rejects trailing slashes... yes
checking whether mknod can create fifo without root privileges... configure: error: in `/root/lede/build_dir/host/tar-1.29':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
See `config.log' for more details
Makefile:30: recipe for target '/root/lede/build_dir/host/tar-1.29/.configured' failed
make[3]: *** [/root/lede/build_dir/host/tar-1.29/.configured] Error 1
make[3]: Leaving directory '/root/lede/tools/tar'
tools/Makefile:148: recipe for target 'tools/tar/compile' failed
make[2]: *** [tools/tar/compile] Error 2
make[2]: Leaving directory '/root/lede'
tools/Makefile:146: recipe for target '/root/lede/staging_dir/target-mips_24kc_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnyyyyyyyyyyyyyyyyyyyynyynynyyyynny' failed
make[1]: *** [/root/lede/staging_dir/target-mips_24kc_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnyyyyyyyyyyyyyyyyyyyynyynynyyyynny] Error 2
make[1]: Leaving directory '/root/lede'
/root/lede/include/toplevel.mk:207: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by MeISbug** [comment]
不要用root用户编译
先在root用户下:
adduser XXX
然后用XXX用户登录，重新编译
