### ISSUE TITLE
编译问题make menuconfig

### ISSUE THREAD

**Issue by dsyo2008** [coolsnowwolf/lede#9001]
make menuconfig时发现了passwall不在luci里，确实加feeds更新没问题。前几天一直正常，现在习惯清理并更新，然后发现这passwall不在luci里。那passwall关issues，没法反馈，只好在这里反馈。非常感谢

**Comment by WYC-2020** [comment]
我这里一切正常，你怕是用的源有问题

**Comment by dsyo2008** [comment]
> 我这里一切正常，你怕是用的源有问题

你是哪个源？我是用xiaorouji的passwall，清理并更新后没问题，但是不在luci真奇怪

**Comment by WYC-2020** [comment]
> > 我这里一切正常，你怕是用的源有问题
> 
> 你是哪个源？我是用xiaorouji的passwall，清理并更新后没问题，但是不在luci真奇怪

小肉鸡的

**Comment by dsyo2008** [comment]
> > > 我这里一切正常，你怕是用的源有问题
> > 
> > 
> > 你是哪个源？我是用xiaorouji的passwall，清理并更新后没问题，但是不在luci真奇怪
> 
> 小肉鸡的

= =一样啊，我为什么找不到luci里毛？

**Comment by WYC-2020** [comment]
> > > > 我这里一切正常，你怕是用的源有问题
> > > 
> > > 
> > > 你是哪个源？我是用xiaorouji的passwall，清理并更新后没问题，但是不在luci真奇怪
> > 
> > 
> > 小肉鸡的
> 
> = =一样啊，我为什么找不到luci里毛？

你是不是没有install哦，不行就make distclean后全新搞

**Comment by dsyo2008** [comment]
> 

当然，其实是删除源，重新拉源，然后软件源更新并安装正常，没任何错误，结果luci没找到passwall真见鬼

**Comment by WYC-2020** [comment]
> > 
> 
> 当然，其实是删除源，重新拉源，然后软件源更新并安装正常，没任何错误，结果luci没找到passwall真见鬼

不会吧，我一个小时前还用过勒，难道你姿势不对哈哈

**Comment by dsyo2008** [comment]
> > > 
> > 
> > 
> > 当然，其实是删除源，重新拉源，然后软件源更新并安装正常，没任何错误，结果luci没找到passwall真见鬼
> 
> 不会吧，我一个小时前还用过勒，难道你姿势不对哈哈

绝对操作没问题
![图片](https://user-images.githubusercontent.com/3739056/156755559-c7b4a4ac-1300-4899-ad8d-9fd886b2637b.png)

**Comment by momonoshiori** [comment]
自己去项目地址看，Special circumstances, stop open.

**Comment by dsyo2008** [comment]
> 

卧槽，才发现了。。。又失去这项目，难道继续用SSRP么

**Comment by lxl6125** [comment]
https://github.com/xiaorouji/openwrt-passwall/tree/3aff3af88536227d12fb7206992af64ff21cf4d2/
手动下载吧，2022-03-03 23:55最后更新的

**Comment by WYC-2020** [comment]
还好我有fork仓库的习惯，我仓库应该是最新的

**Comment by dsyo2008** [comment]
> 

我用了你的源OK了哈

**Comment by yjs507** [comment]
> 

这个要怎么搞呀，刚学编译，不懂怎么操作

**Comment by violetice** [comment]
> 你是不是没有install哦，不行就make distclean后全新搞

我今天也这样，就是没有install，笑死。
