### ISSUE TITLE
发现个窍门，请大佬验证一下

### ISSUE THREAD

**Issue by isDaKai** [coolsnowwolf/lede#9002]
如果要编译SSRP或者passwall
在执行完  ./scripts/feeds install -a 之后
可以再加一个命令 ./scripts/feeds uninstall luci-app-shadowsocks-libev
把这个卸载掉
避免在执行make download的时候和这两个插件内置的起冲突报错

同理
如果想加入jerrykuku / luci-theme-argon 这个作者的主题的话
也应执行  ./scripts/feeds uninstall luci-theme-argon
删掉lean大佬内置的 argon
而不是去
cd lede/package/lean  
rm -rf luci-theme-argon 

经过我个人实践
再也没有报错过
每次都是一次编译成功
望大佬验证一下
我这么做是不是多此一举

**Comment by WYC-2020** [comment]
多余操作，带上-f都能解决的，搞那么复杂

**Comment by isDaKai** [comment]
> 多余操作，带上-f都能解决的，搞那么复杂

我向你敬礼salute！
