### ISSUE TITLE
x86_64选using test kernel 不生效，还是5.4内核

### ISSUE THREAD

**Issue by zcluo** [coolsnowwolf/lede#9008]
x86_64选using test kernel 不生效，还是5.4内核

**Comment by WYC-2020** [comment]
动都没动过那块 你怕是姿势不对

**Comment by lxl6125** [comment]
因为现在默认是5.15，test kernel是5.4
https://github.com/coolsnowwolf/lede/commit/fd9249dacbe3cea152feb55645ecd92b40ef16f3
