### ISSUE TITLE
Change --filter-aaaa to --filter-AAAA for dnsmasq?

### ISSUE THREAD

**Issue by HiGarfield** [coolsnowwolf/lede#9009]
https://github.com/coolsnowwolf/lede/blob/e7d93121027a00319173e12885e071df568b018b/package/network/services/dnsmasq/patches/911-dnsmasq-filter-aaaa%2Bhttps%2Bunknown.patch#L91

The upstream version of dnsmasq uses --filter-AAAA

Ref:
https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=37a70d39e0cd49f086b757937fa8735e6263cd7a

**Comment by WYC-2020** [comment]
这个问题不大，你要看服务脚本怎么写的，l的服务脚本 和这个代码里的 是匹配的不用管其他人的
![image](https://user-images.githubusercontent.com/34025388/156886538-77a205a7-d615-4f1c-8c6c-28dc34769f4d.png)
@HiGarfield  可以关闭了

**Comment by HiGarfield** [comment]
>
