### ISSUE TITLE
V2ray为什么不显示了

### ISSUE THREAD

**Issue by ldy8182** [coolsnowwolf/lede#901]
编译的时候选了，也执行特殊命令了，v2ray就是不显示
![1](https://user-images.githubusercontent.com/24645236/49798057-50501e00-fd7c-11e8-8eb7-e8b2337c5062.png)

**Comment by ldy8182** [comment]
![2](https://user-images.githubusercontent.com/24645236/49798127-7e356280-fd7c-11e8-8f16-dbd70c79f561.png)

**Comment by shenzt68** [comment]
make clean
make -j1 V=s

**Comment by choushui007** [comment]
rm .config  ,重新 make menuconfig 一下
