### ISSUE TITLE
编译5.15内核 backports是5.10内核的

### ISSUE THREAD

**Issue by ligehhh** [coolsnowwolf/lede#9015]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：backports是5.10内核的

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：
SHELL= flock /home/lihh/lede/tmp/.backports-5.10.42-1.tar.xz.flock -c '  	/home/lihh/lede/scripts/download.pl "/home/lihh/lede/dl" "backports-5.10.42-1.tar.xz" "6876520105240844fdb32d1dcdf2bfdea291a37a96f16c892fda3776ba714fcb" "" "@KERNEL/linux/kernel/projects/backports/stable/v5.10.42/"    '
rm -f /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.built
touch /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.built_check
. /home/lihh/lede/include/shell.sh; var2file "V_mac80211_config" /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.config
make -C "/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1" KCFLAGS="-fmacro-prefix-map=/home/lihh/lede/build_dir/target-x86_64_musl=target-x86_64_musl" HOSTCFLAGS="-O2 -I/home/lihh/lede/staging_dir/host/include -I/home/lihh/lede/staging_dir/hostpkg/include -I/home/lihh/lede/staging_dir/target-x86_64_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="x86_64-openwrt-linux-musl-" ARCH="x86" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Mar  5 02:10:45 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/lihh/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/lihh/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/button-hotplug.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/cryptodev-linux.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8125.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8152.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/siit.symvers" KERNELRELEASE=5.15.26 EXTRA_CFLAGS="-I/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/include -fmacro-prefix-map=/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1=backports-5.10.42-1  -I/home/lihh/lede/staging_dir/target-x86_64_musl/usr/include/qca-nss-drv" KLIB_BUILD="/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.26" MODPROBE=true KLIB=/lib/modules/5.15.26 KERNEL_SUBLEVEL=15 KBUILD_LDFLAGS_MODULE_PREREQ= allnoconfig
make[4]: Entering directory '/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1'
make[5]: 'Kconfig.versions' is up to date.
make[6]: 'conf' is up to date.
boolean symbol CRYPTO_LIB_ARC4 tested for 'm'? test forced to 'n'
.config:11:warning: override: reassigning to symbol ATH10K
.config:12:warning: override: reassigning to symbol ATH10K_PCI
.config:38:warning: override: reassigning to symbol LIBERTAS
.config:40:warning: override: reassigning to symbol LIBERTAS
.config:45:warning: override: reassigning to symbol MWIFIEX
#
# configuration written to .config
#
make[4]: Leaving directory '/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1'
rm -rf /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/modules
make  -C "/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1" KCFLAGS="-fmacro-prefix-map=/home/lihh/lede/build_dir/target-x86_64_musl=target-x86_64_musl" HOSTCFLAGS="-O2 -I/home/lihh/lede/staging_dir/host/include -I/home/lihh/lede/staging_dir/hostpkg/include -I/home/lihh/lede/staging_dir/target-x86_64_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="x86_64-openwrt-linux-musl-" ARCH="x86" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Sat Mar  5 02:10:45 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/lihh/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/lihh/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/button-hotplug.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/cryptodev-linux.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8125.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/r8152.symvers /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/symvers/siit.symvers" KERNELRELEASE=5.15.26 EXTRA_CFLAGS="-I/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/include -fmacro-prefix-map=/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1=backports-5.10.42-1  -I/home/lihh/lede/staging_dir/target-x86_64_musl/usr/include/qca-nss-drv" KLIB_BUILD="/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.26" MODPROBE=true KLIB=/lib/modules/5.15.26 KERNEL_SUBLEVEL=15 KBUILD_LDFLAGS_MODULE_PREREQ= modules
make[4]: Entering directory '/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1'
make[5]: 'Kconfig.versions' is up to date.
make[7]: 'Kconfig.versions' is up to date.
make[8]: 'conf' is up to date.
boolean symbol CRYPTO_LIB_ARC4 tested for 'm'? test forced to 'n'
#
# configuration written to .config
#
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/drivers/net/wireless/admtek/adm8211.o
/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/drivers/net/wireless/admtek/adm8211.c:31:25: error: expected declaration specifiers or '...' before string constant
 MODULE_SUPPORTED_DEVICE("ADM8211");
                         ^~~~~~~~~
make[10]: *** [scripts/Makefile.build:277: /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/drivers/net/wireless/admtek/adm8211.o] Error 1
make[9]: *** [scripts/Makefile.build:540: /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/drivers/net/wireless/admtek] Error 2
make[8]: *** [scripts/Makefile.build:540: /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/drivers/net/wireless] Error 2
make[7]: *** [Makefile:1868: /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1] Error 2
make[6]: *** [Makefile.build:13: modules] Error 2
make[5]: *** [Makefile.real:93: modules] Error 2
make[4]: *** [Makefile:121: modules] Error 2
make[4]: Leaving directory '/home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1'
make[3]: *** [Makefile:584: /home/lihh/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.built] Error 2
make[3]: Leaving directory '/home/lihh/lede/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#1.07#0.29#1.31
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
make[2]: *** [package/Makefile:116: package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/lihh/lede'
make[1]: *** [package/Makefile:110: /home/lihh/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lihh/lede'
make: *** [/home/lihh/lede/include/toplevel.mk:230：world] 错误 2

**Comment by WYC-2020** [comment]
又是这个问题，看其他issue有说解决方案
