### ISSUE TITLE
这是个什么网站？srclinkapp.biz？

### ISSUE THREAD

**Issue by shenzt68** [coolsnowwolf/lede#903]
![image](https://user-images.githubusercontent.com/17406910/49840599-0d7b5e00-fdef-11e8-98dc-47f40a1e08fb.png)
我每次登录路由器时，都发现要连接srclinkapp.biz？

**Comment by jonirrings** [comment]
从[这个分析](https://www.hybrid-analysis.com/sample/2a0491abbd28fa9b93c767832d9bf2dce0bf4df3b6de4cb139991198ed74dbcd?environmentId=100)看，可能是malware，至于到底是你浏览器被劫持了还是路由器被劫持了就不得而知了。
