### ISSUE TITLE
IPQ807X平台下小米的几个device没有了啊？

### ISSUE THREAD

**Issue by xiufeiwu** [coolsnowwolf/lede#9040]
选择IPQ807X后，TargetProfile下只有Multiple Devices ，QNAP 301w，ZTE MF269这几个了，小米的AX3600 AX6都没了，什么原因啊，被谁删了

**Comment by WYC-2020** [comment]
自己看提交，需要自己revert回来就是了

**Comment by Kaze1027** [comment]
小米系列相关代码现由“ax6机友会”陈超等大佬私有化闭源了

**Comment by kisaragychihaya** [comment]
找E大去

**Comment by Pacio** [comment]
https://github.com/robimarko/openwrt/tree/ipq807x-5.15
可以先用这个顶一下，老外奋力更新中

**Comment by WYC-2020** [comment]
哈哈，我倒是无所谓的，毕竟都是玩x86软路由，这总不会变成闭源了吧，哈哈

**Comment by Kaze1027** [comment]
> 一个开源东西搞成闭源收费真要脸

拜托，谁收费了？去了解一下陈超一干人就懂了，lean自己的代码，想删就删，有什么问题？
陈超等人白嫖了lean的固件不说谢谢就算了，反过来还骂，咱不伺候这种傻x

**Comment by WYC-2020** [comment]
> > 一个开源东西搞成闭源收费真要脸
> 
> 拜托，谁收费了？去了解一下陈超一干人就懂了，lean自己的代码，想删就删，有什么问题？ 陈超等人白嫖了lean的固件不说谢谢就算了，反过来还骂，咱不伺候这种傻x

都啥跟啥哦 你是把我的意思高反了吧 哈哈

**Comment by WYC-2020** [comment]
> https://github.com/robimarko/openwrt/tree/ipq807x-5.15 可以先用这个顶一下，老外奋力更新中

这个可以，等会我就把这个整合到我的仓库中去
