### ISSUE TITLE
编译错

### ISSUE THREAD

**Issue by jimjimbco** [coolsnowwolf/lede#9042]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：Applying ./patches/ath11k/983-ath11k-Enable-VHT-for-2G.patch using plaintext: 
patching file drivers/net/wireless/ath/ath11k/mac.c
Hunk #1 succeeded at 1838 (offset 245 lines).
Hunk #2 succeeded at 3932 (offset 380 lines).
patching file drivers/net/wireless/ath/ath11k/wmi.c
Hunk #1 succeeded at 361 (offset 15 lines).

Applying ./patches/ath11k/998-ath11k-Enable-512MB-profile-in-ath11k.patch using plaintext: 
patching file drivers/net/wireless/ath/ath11k/Kconfig
patching file drivers/net/wireless/ath/ath11k/hw.h
patching file drivers/net/wireless/ath/ath11k/qmi.c
Hunk #1 succeeded at 2677 (offset 2 lines).
patching file drivers/net/wireless/ath/ath11k/qmi.h
patching file local-symbols
Hunk #1 succeeded at 154 (offset 1 line).
patching file drivers/net/wireless/ath/ath11k/core.h
Hunk #1 succeeded at 740 (offset 6 lines).
patching file drivers/net/wireless/ath/ath11k/dp.h
patching file drivers/net/wireless/ath/ath11k/dp_tx.c
Hunk #1 succeeded at 270 (offset 8 lines).
Hunk #2 succeeded at 317 (offset 8 lines).
Hunk #3 succeeded at 349 (offset 8 lines).
Hunk #4 succeeded at 630 (offset 8 lines).

Applying ./patches/rt2x00/001-rt2x00-driver-compile-with-kernel-5.15.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 succeeded at 992 with fuzz 2 (offset -5 lines).

Applying ./patches/rt2x00/002-rt2x00-define-RF5592-in-init_eeprom-routine.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2800lib.c

Applying ./patches/rt2x00/100-rt2x00_options.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/Kconfig

Applying ./patches/rt2x00/501-rt2x00-allow-to-build-rt2800soc-module-for-RT3883.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/Kconfig

Applying ./patches/rt2x00/601-rt2x00-introduce-rt2x00_platform_h.patch using plaintext: 
patching file include/linux/rt2x00_platform.h
patching file drivers/net/wireless/ralink/rt2x00/rt2x00.h

Applying ./patches/rt2x00/602-rt2x00-introduce-rt2x00eeprom.patch using plaintext: 
patching file local-symbols
Hunk #1 succeeded at 334 (offset 1 line).
patching file drivers/net/wireless/ralink/rt2x00/Kconfig
patching file drivers/net/wireless/ralink/rt2x00/Makefile
patching file drivers/net/wireless/ralink/rt2x00/rt2800lib.h
patching file drivers/net/wireless/ralink/rt2x00/rt2800soc.c
patching file drivers/net/wireless/ralink/rt2x00/rt2x00.h
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 succeeded at 1409 (offset 3 lines).
Hunk #2 succeeded at 1556 (offset 3 lines).
patching file drivers/net/wireless/ralink/rt2x00/rt2x00eeprom.c
patching file drivers/net/wireless/ralink/rt2x00/rt2x00lib.h
patching file drivers/net/wireless/ralink/rt2x00/rt2x00soc.c

Applying ./patches/rt2x00/603-rt2x00-of_load_eeprom_filename.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2x00eeprom.c

Applying ./patches/rt2x00/604-rt2x00-load-eeprom-on-SoC-from-a-mtd-device-defines-.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/Kconfig
patching file drivers/net/wireless/ralink/rt2x00/rt2x00eeprom.c

Applying ./patches/rt2x00/606-rt2x00-allow_disabling_bands_through_platform_data.patch using plaintext: 
patching file include/linux/rt2x00_platform.h
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 succeeded at 1015 (offset 3 lines).
patching file drivers/net/wireless/ralink/rt2x00/rt2x00.h

Applying ./patches/rt2x00/607-rt2x00-add_platform_data_mac_addr.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 FAILED at 990.
1 out of 1 hunk FAILED -- saving rejects to file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c.rej
patching file include/linux/rt2x00_platform.h
Patch failed!  Please fix ./patches/rt2x00/607-rt2x00-add_platform_data_mac_addr.patch!
make[3]: *** [Makefile:593: /home/hp/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.prepared_eed7bb2b5d054e4a1a9ab46e3c17e405_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/hp/lede/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#0.78#1.12#1.42
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
make[2]: *** [package/Makefile:116: package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/hp/lede'
make[1]: *** [package/Makefile:110: /home/hp/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hp/lede'
make: *** [/home/hp/lede/include/toplevel.mk:230: world] Error 2

**Comment by jimjimbco** [comment]
Applying ./patches/rt2x00/603-rt2x00-of_load_eeprom_filename.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2x00eeprom.c

Applying ./patches/rt2x00/604-rt2x00-load-eeprom-on-SoC-from-a-mtd-device-defines-.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/Kconfig
patching file drivers/net/wireless/ralink/rt2x00/rt2x00eeprom.c

Applying ./patches/rt2x00/606-rt2x00-allow_disabling_bands_through_platform_data.patch using plaintext: 
patching file include/linux/rt2x00_platform.h
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 succeeded at 1015 (offset 3 lines).
patching file drivers/net/wireless/ralink/rt2x00/rt2x00.h

Applying ./patches/rt2x00/607-rt2x00-add_platform_data_mac_addr.patch using plaintext: 
patching file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c
Hunk #1 FAILED at 990.
1 out of 1 hunk FAILED -- saving rejects to file drivers/net/wireless/ralink/rt2x00/rt2x00dev.c.rej
patching file include/linux/rt2x00_platform.h
Patch failed!  Please fix ./patches/rt2x00/607-rt2x00-add_platform_data_mac_addr.patch!
make[3]: *** [Makefile:593: /home/hp/lede/build_dir/target-x86_64_musl/linux-x86_64/backports-5.10.42-1/.prepared_eed7bb2b5d054e4a1a9ab46e3c17e405_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/hp/lede/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#0.78#1.12#1.42
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
make[2]: *** [package/Makefile:116: package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/hp/lede'
make[1]: *** [package/Makefile:110: /home/hp/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hp/lede'
make: *** [/home/hp/lede/include/toplevel.mk:230: world] Error 2

**Comment by WYC-2020** [comment]
缝缝补补哈哈

**Comment by jimjimbco** [comment]
部分插件有问题，已编译

**Comment by dzhl** [comment]
> 部分插件有问题，已编译

我也遇到类似问题，请问是什么插件导致的呢
