### ISSUE TITLE
自從由antfs轉做ntfs3之後，挂不到ntfs的硬盤

### ISSUE THREAD

**Issue by alan21j** [coolsnowwolf/lede#9051]
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_thunder_timecloud=y

嘗試挂載硬盤，顯示如下：

block: check_filesystem: /usr/bin/ntfsfix not found
block: mount.ntfs: mount: /mnt/sda1: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.
block: mount.ntfs: failed with status 8192
block: mounting /dev/sda1 (ntfs) as /mnt/sda1 failed (22) - Invalid argument

是不是要再安裝antfs？

**Comment by WYC-2020** [comment]
我这边x86亲测没问题

**Comment by alan21j** [comment]
已經解決，把硬盤取下到windows掃描一次，再插回去重啓就沒事了，麻煩大家了。

**Comment by uniessey** [comment]
您好，我看到您使用了mt7621芯片搭配NTFS3，请教一下，您使用了5.15内核吗？

**Comment by coolsnowwolf** [comment]
文件系统有错误（例如不正常的拔掉USB）需要 check 后才会自动挂载，除非用 force 强制挂载

**Comment by nalipiaoxiang** [comment]
还是大佬们牛逼,,找到这里才解决,差点就格式化解决了
