### ISSUE TITLE
使用最新版本5.15 DoorNet2默认配置编译后led灯问题

### ISSUE THREAD

**Issue by qijian1105** [coolsnowwolf/lede#9067]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
没有类似的issue
## 2. 详细叙述
使用最新版本5.15 DoorNet2默认配置编译后led配置选项中只有mmc0:: 选项了，没有green：lan 、green：wan、red:sys选项了。
重新用5.4版本编译后就有了。
### (1) 具体问题

A：使用最新版本5.15 DoorNet2默认配置编译后led配置选项中只有mmc0:: 选项了，没有green：lan 、green：wan、red:sys选项了。
重新用5.4版本编译后就有了。

### (2) 路由器型号和固件版本

A： DoorNet2

### (3) 详细日志

A：
这是5.4版本下的 /sys/class/leds/ 文件

root@OpenWrt:/sys/class/leds# ll
drwxr-xr-x    2 root     root             0 Mar 14 10:49 ./
drwxr-xr-x   55 root     root             0 Mar 14 10:49 ../
lrwxrwxrwx    1 root     root             0 Mar 14 10:49 green:lan -> ../../devices/platform/gpio-leds/leds/green:lan/
lrwxrwxrwx    1 root     root             0 Mar 14 10:49 green:wan -> ../../devices/platform/gpio-leds/leds/green:wan/
lrwxrwxrwx    1 root     root             0 Mar 14 10:49 mmc0:: -> ../../devices/platform/fe330000.sdhci/leds/mmc0::/
lrwxrwxrwx    1 root     root             0 Mar 14 10:49 red:sys -> ../../devices/platform/gpio-leds/leds/red:sys/

这是5.15版本下的 /sys/class/leds/ 文件
root@OpenWrt:/sys/class/leds# ll
drwxr-xr-x    2 root     root             0 Mar 14 12:34 ./
drwxr-xr-x   55 root     root             0 Mar 14 12:34 ../
lrwxrwxrwx    1 root     root             0 Mar 14 12:34 mmc0:: -> ../../devices/platform/fe330000.mmc/leds/mmc0::/
root@OpenWrt:/sys/class/leds#

**Comment by LPDDR6-10000MHz** [comment]
5.15暂时适配不够好，还要等一段时间吧。。。用5.4多省事，5.10对超频不好友。实测
