### ISSUE TITLE
建议：取消ipq806x默认选择UnblockNeteaseMusic来避免依赖node

### ISSUE THREAD

**Issue by AldarisX** [coolsnowwolf/lede#9070]
ipq806x默认选择UnblockNeteaseMusic导致依赖了node，建议取消该依赖来减轻编译时的压力

**Comment by AldarisX** [comment]
// 我现在ipq806x node编译还会报错

**Comment by minlang112** [comment]
这个和压力不压力没啥关系啊，可能是你的编译机没有32位glibc库？

**Comment by AldarisX** [comment]
> 这个和压力不压力没啥关系啊，可能是你的编译机没有32位glibc库？

主要是编译node太花时间了一般也用不上，需要用的自己也会选，作为默认值我觉得就不太合适了

**Comment by AldarisX** [comment]
> 这个和压力不压力没啥关系啊，可能是你的编译机没有32位glibc库？

重装系统后好像是忘了32位的库了 (╯‵□′)╯︵┻━┻
