### ISSUE TITLE
究竟要如何开启ipv6？光猫桥接

### ISSUE THREAD

**Issue by HanzChen** [coolsnowwolf/lede#9076]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：按网上的教程开启IPV6，wan6是获取到了240e开头的地址，但是lan口和里面的设备都没有获取到。

### (2) 路由器型号和固件版本

A：x86，自行编译

### (3) 详细日志

光猫桥接模式，使用华硕ax86u用native是可以完美获取ipv6地址的。
但是用软路由就死活不行
设置如下

<img width="828" alt="image" src="https://user-images.githubusercontent.com/59546710/158541938-7e492639-25be-4a71-9297-5cb1c3d0ecf4.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/59546710/158542060-fa5afdc1-33a2-4d35-9518-3bd6215bb062.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/59546710/158542120-540ba4ef-f8b6-45bd-867d-ce5a588486b8.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/59546710/158542153-d2d2ff55-8878-49c8-b661-fc172061aa64.png">
<img width="1732" alt="image" src="https://user-images.githubusercontent.com/59546710/158542187-41623a6e-3ea9-4a53-b4d7-3cb289555ed0.png">
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/59546710/158542255-0701243f-632a-4a51-93ab-c90e7b8628f3.png">

**Comment by WYC-2020** [comment]
软路由自身拨号，wan6 口没用吧，wan 就能获取到ipv6

**Comment by frely** [comment]
Base system  ---> 
    Build with DHCPv6 support.
Extra packages  ---> 
    ipv6helper

**Comment by HanzChen** [comment]
> Base system ---> Build with DHCPv6 support. Extra packages ---> ipv6helper

Already done this. The problem here is that WAN6 shows a valid IPV6, but all LAN devices have no IPV6...
已经这么做了，现在的主要是lan设备无法获取有效的ipv6...

**Comment by WYC-2020** [comment]
> > Base system ---> Build with DHCPv6 support. Extra packages ---> ipv6helper
> 
> Already done this. The problem here is that WAN6 shows a valid IPV6, but all LAN devices have no IPV6... 已经这么做了，现在的主要是lan设备无法获取有效的ipv6...

确定你的宽带运营商提供了ipv6 支持

**Comment by frely** [comment]
> > 基础系统 ---> 使用 DHCPv6 支持构建。额外的软件包---> ipv6helper
> 
> 已经这样做了。这里的问题是，WAN6显示了有效的IPV6，但是所有的LAN设备都没有IPV6…… 已经完成了，现在的主要是设备无法获取有效的ipv6……

openwrt的默认配置不要动，获取不到ipv6的话检车下光猫的ipv6配置。

**Comment by HanzChen** [comment]
> > > Base system ---> Build with DHCPv6 support. Extra packages ---> ipv6helper
> > 
> > 
> > Already done this. The problem here is that WAN6 shows a valid IPV6, but all LAN devices have no IPV6... 已经这么做了，现在的主要是lan设备无法获取有效的ipv6...
> 
> 确定你的宽带运营商提供了ipv6 支持

确定的，使用华硕路由器是完美支持IPV6，所有子设备都能正确获取。

**Comment by HanzChen** [comment]
> 使用华硕路由器是完美支持IPV6，所有子设备都能正确获取。

所以其实不需要“DHCPv6 ”和“ ipv6helper”？

**Comment by WYC-2020** [comment]
> > 使用华硕路由器是完美支持IPV6，所有子设备都能正确获取。
> 
> 所以其实不需要“DHCPv6 ”和“ ipv6helper”？

https://www.youtube.com/watch?v=aVv64eXk50s 自己参考一下 这个ytb 很多教程的，我家里运营商不支持 所以就没搞ipv6

**Comment by WYC-2020** [comment]
> > 使用华硕路由器是完美支持IPV6，所有子设备都能正确获取。
> 
> 所以其实不需要“DHCPv6 ”和“ ipv6helper”？

必须要要的

**Comment by frely** [comment]
昨天最新编译的固件，使用默认配置拨号后lan设备就有ipv6了。
Base system ---> Build with DHCPv6 support.
Extra packages ---> ipv6helper

![Snipaste_2022-03-16_17-30-31](https://user-images.githubusercontent.com/40338481/158559843-58d3e52a-f435-48f8-b25c-8c2e1dcd6884.jpg)

**Comment by HanzChen** [comment]
> 昨天最新编译的固件，使用默认配置拨号后lan设备就有ipv6了。 Base system ---> Build with DHCPv6 support. Extra packages ---> ipv6helper
> 
> ![Snipaste_2022-03-16_17-30-31](https://user-images.githubusercontent.com/40338481/158559843-58d3e52a-f435-48f8-b25c-8c2e1dcd6884.jpg)

好的我再试试看

**Comment by breakings** [comment]
我是光猫桥接，硬路由拨号。
![Screenshot_20220316_180436](https://user-images.githubusercontent.com/25475074/158565857-e66732c7-4ee3-433f-ae48-2612d92afc6f.png)

**Comment by HanzChen** [comment]
重新编译后解决问题。。
Base system ---> Build with DHCPv6 support. 
Extra packages ---> ipv6helper
![image](https://user-images.githubusercontent.com/59546710/158587367-5ecdc2e7-9347-43c2-8594-e15a560bcca5.png)
