### ISSUE TITLE
mt7621的无线是不支持hwnat么

### ISSUE THREAD

**Issue by DoveKi** [coolsnowwolf/lede#9081]
之前是200M宽带没注意，最近升了500M发现无线不能跑满，无线跑到250M左右cpu就占用100%瓶颈了
有线hwnat下没问题，cpu无占用
试了Flow Offloading和SFE都一样，无线cpu都是跑250m就满载100%
是我设置问题还是mtk无线都不支持hwnat
无线驱动用的是开源驱动

**Comment by AmadeusGhost** [comment]
mt7621 并不支持无线 hwnat。

**Comment by nanchuci** [comment]
用老毛子吧！

**Comment by WYC-2020** [comment]
这个好像https://github.com/x-wrt/x-wrt/issues/119 这个的支持了没验证，或者说不知道是哪个提交 ，可以考虑能不能迁移过来
