### ISSUE TITLE
为什么最新的版本会不断断开有线连接？

### ISSUE THREAD

**Issue by hgh188** [coolsnowwolf/lede#909]
无线没问题

**Comment by hgh188** [comment]
Fri Dec 14 22:57:20 2018 kern.info kernel: [22554.551616] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Fri Dec 14 22:57:23 2018 kern.info kernel: [22558.309272] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up
Fri Dec 14 22:57:24 2018 kern.info kernel: [22558.634771] mtk_soc_eth 1e100000.ethernet eth0: port 3 link down
Fri Dec 14 22:57:26 2018 kern.info kernel: [22561.179267] mtk_soc_eth 1e100000.ethernet eth0: port 3 link up

**Comment by hgh188** [comment]
早几个版本都正常

**Comment by signigelchan** [comment]
遇到相同的问题。

**Comment by chenhao6938** [comment]
这个问题这么早就有了啊。到现在还有。
