### ISSUE TITLE
feeds.conf.default内，如何指定软件包分支

### ISSUE THREAD

**Issue by Canary233** [coolsnowwolf/lede#9095]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
如题
### (1) 具体问题

A：如题

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by 286700234** [comment]
我也想知道怎么退回去

**Comment by Boos4721** [comment]
src-git `name` `url`;`branches`
