### ISSUE TITLE
退回指定版本后，全部都是错误，而且编译出来的固件也不能用，无法识别网络

### ISSUE THREAD

**Issue by 286700234** [coolsnowwolf/lede#9096]
退回2021年7月12日	
5.4.128版本：git reset --hard 4641e712d0e7e51dfa34771887d571d96688af63
我用这个退回后，编译全部都出错，不知道改怎么解决了
请求大佬们指点下，因为我用这个版本编译的660X固件不会重启，而更新后的，到最新的5.4.185的内核都还是会自动重启

**Comment by 1054009064** [comment]
换个功率大一点的电源吧，原厂那个扔了

**Comment by WYC-2020** [comment]
出错又不贴错误日志，你是让别人猜吗

**Comment by britneyjeanspears** [comment]
出错又不贴错误日志，你是让别人猜吗

**Comment by DoveKi** [comment]
隔这么久的回退肯定不能用的，feeds那些都是版本配套的，你可以把所有feeds回退到同时期的

**Comment by siren202101** [comment]
> 退回2021年7月12日 5.4.128版本：git reset --hard [4641e71](https://github.com/coolsnowwolf/lede/commit/4641e712d0e7e51dfa34771887d571d96688af63) 我用这个退回后，编译全部都出错，不知道改怎么解决了 请求大佬们指点下，因为我用这个版本编译的660X固件不会重启，而更新后的，到最新的5.4.185的内核都还是会自动重启

大佬，退回版本，版本号到哪里看？
