### ISSUE TITLE
小米路由R3G，相同固件有的能启动有的无法启动？

### ISSUE THREAD

**Issue by ttmi9002** [coolsnowwolf/lede#9109]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：6台小米路由器R3G，有的能启动，有的无法启动

### (2) 路由器型号和固件版本

A：小米路由器R3G，OpenWrt R22.3.13 / LuCI Master (git-22.068.45502-a50e601)
      内核  5.4.185

### (3) 详细日志

A：

**Comment by DoveKi** [comment]
breed启动参数看看

**Comment by ttmi9002** [comment]
环境变量编辑
xiaomi.r3g.bootfw     2

**Comment by ttmi9002** [comment]
> breed启动参数看看

其他都是默认的，只添加下面一条
环境变量编辑
xiaomi.r3g.bootfw 2

同样的breed设置，有的能启动，有的启动不了。v4.14 内核没有出现过这个问题
