### ISSUE TITLE
构建过程中busybox与procd在/sbin/init 处冲突

### ISSUE THREAD

**Issue by ltrsunny** [coolsnowwolf/lede#9144]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：busybox与procd均在默认配置中开启，但在完成构建时会报错冲突

### (2) 路由器型号和固件版本

A：
MediaTek MT7629 rfb AP
Bananapi BPi-R2 (MT7623)
均不成功

### (3) 详细日志

A：
```
 * check_data_file_clashes: Package busybox wants to install file /home/dev/lede/build_dir/target-arm_cortex-a7_musl_eabi/root-mediatek/sbin/init
        But that file is already provided by package  * procd
 * opkg_install_cmd: Cannot install package busybox.
```

**Comment by qwq233** [comment]
老哥是怎么解决的 我也遇到这问题了

**Comment by ltrsunny** [comment]
> 老哥是怎么解决的 我也遇到这问题了

放弃了，非必要不自己编译
