### ISSUE TITLE
nft-qos 插件保存&应用不生效

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#9148]
rt, nft-qos插件，在luci里面点击保存和应用后并不立刻对静态IP地址的rate limit生效，需要手工在shell里运行“service nft-qos restart" 才能生效，能否麻烦大大在luci的插件里加一点代码，每次保存和应用的时候在最后调一下相关init脚本里的服务重启的function修复一下，每次配置完或者重启完后不立刻生效有点烦....

多谢！

**Comment by evfun** [comment]
这个issue老早就有人提了，但一直没修。我用luci-app-command凑合用了

**Comment by WYC-2020** [comment]
这玩意自己参考另外插件修复一下即可

**Comment by GreatMichaelLee** [comment]
> 这玩意自己参考另外插件修复一下即可

另外插件是？

**Comment by Beginner-Go** [comment]
https://github.com/coolsnowwolf/lede/commit/57f538e8c5d6b5f14d695c5afcd9ea17a8e95141
应该是这个

**Comment by GreatMichaelLee** [comment]
> [57f538e](https://github.com/coolsnowwolf/lede/commit/57f538e8c5d6b5f14d695c5afcd9ea17a8e95141) 应该是这个

大佬能不能辛苦改一下给nft-qos呢，我不懂代码啊，哈哈，不知为不知。

**Comment by GreatMichaelLee** [comment]
求老大修复一下...-_-!

**Comment by GreatMichaelLee** [comment]
> 求老大修复一下...-_-!

没人修吗.....

**Comment by GreatMichaelLee** [comment]
这个问题貌似已经提交修复了，老大可以关了。

**Comment by yishion819** [comment]
> 这个问题貌似已经提交修复了，老大可以关了。感谢！

请问你是用的L大修复的nft qos源码编译的？

**Comment by GreatMichaelLee** [comment]
是的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 晚上10:44
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [coolsnowwolf/lede] nft-qos 插件保存&amp;应用不生效 (Issue #9148)




  
这个问题貌似已经提交修复了，老大可以关了。感谢！
  
请问你是用的L大修复的nft qos源码编译的？
