### ISSUE TITLE
ERROR: package/network/utils/iw failed to build (build variant: tiny)

### ISSUE THREAD

**Issue by hugcabbage** [coolsnowwolf/lede#9149]
iw今天更新后，编译报错。
ramips机型，内核选择的是5.10

**Comment by Womsxd** [comment]
一样，编译报错，红米ac2100
`make[4]: Entering directory '/home/womsxd/Desktop/lede/build_dir/target-mipsel_24kc_musl/iw-tiny/iw-5.16'
mipsel-openwrt-linux-musl-gcc -L/home/womsxd/Desktop/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/usr/lib -L/home/womsxd/Desktop/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib -znow -zrelro -Wl,--gc-sections -flto bitrate.o connect.o event.o genl.o hwsim.o ibss.o info.o interface.o iw.o link.o mesh.o mpath.o mpp.o phy.o ps.o reason.o reg.o sar.o scan.o sections.o station.o status.o survey.o util.o version.o -lm -lnl-tiny -o iw
/home/womsxd/Desktop/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/lib/gcc/mipsel-openwrt-linux-musl/8.4.0/../../../../mipsel-openwrt-linux-musl/bin/ld: /home/womsxd/Desktop/lede/tmp/ccdMOsjx.ltrans0.ltrans.o: in function `set_sar_specs.lto_priv.57':
<artificial>:(.text+0x7298): undefined reference to `NLA_PUT_S32'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:115: iw] Error 1
make[4]: Leaving directory '/home/womsxd/Desktop/lede/build_dir/target-mipsel_24kc_musl/iw-tiny/iw-5.16'
make[3]: *** [Makefile:75: /home/womsxd/Desktop/lede/build_dir/target-mipsel_24kc_musl/iw-tiny/iw-5.16/.built] Error 2
make[3]: Leaving directory '/home/womsxd/Desktop/lede/package/network/utils/iw'
time: package/network/utils/iw/tiny/compile#1.36#0.08#1.44
    ERROR: package/network/utils/iw failed to build (build variant: tiny).
make[2]: *** [package/Makefile:116: package/network/utils/iw/compile] Error 1
make[2]: Leaving directory '/home/womsxd/Desktop/lede'
make[1]: *** [package/Makefile:110: /home/womsxd/Desktop/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/womsxd/Desktop/lede'
make: *** [/home/womsxd/Desktop/lede/include/toplevel.mk:230：world] 错误 2
`
