### ISSUE TITLE
最新编译后，保存的配置不生效

### ISSUE THREAD

**Issue by rongcenter** [coolsnowwolf/lede#9167]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
A：
Commits:624a9f9703d46f1913ee0504756814dda23ef94a
helloword和Adbyby Plus+
这2个只要任何保存1次，不重启，保存的配置不生效。重启后，保存1次，第2次也不生效的情况？？
是因为用了[jerrykuku](https://github.com/jerrykuku)的主题吗？

Commits:fc527f12dc986cc36410130d3d9df29cdf9f3547
这个是正常的。
### (2) 路由器型号和固件版本

A：
x86_64
### (3) 详细日志

A：
无日志输出。

**Comment by rongcenter** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/6003357/161118448-39bfe223-80c4-4636-b733-38caa94b7bcf.png">
前面是“正在应用更改”，然后直接是这个界面。

**Comment by tone88** [comment]
确实，好几个都是这情况 。

**Comment by rongcenter** [comment]
#9163 解决了，这个引起的。

**Comment by rongcenter** [comment]
已修复，正常了

**Comment by WYC-2020** [comment]
也就补丁的类型不对而已，导致格式化是出错修正一下即可的
