### ISSUE TITLE
4.1 编译的 mt7621A，5GWiFi 无法联网

### ISSUE THREAD

**Issue by modelsun** [coolsnowwolf/lede#9168]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：5GWiFi无法联网，2.4 无问题。
还有baidupcs-Web  build失败

### (2) 路由器型号和固件版本

A：hiwifi  hc5962

### (3) 详细日志

A：

**Comment by wuzhuang123** [comment]
同样的，不只5G，所有无线都是，连接上前5秒可以，然后ping不同网关，打开任何页面都是DNS错误。有线正常。

**Comment by WYC-2020** [comment]
慢慢修吧，十之八九驱动升级的原因，毕竟从5.10一下切换到5.15

**Comment by modelsun** [comment]
> 同样的，不只5G，所有无线都是，连接上前5秒可以，然后ping不同网关，打开任何页面都是DNS错误。有线正常。

嗯，2.4G 没长时间用就换回旧版本了， 感觉比5G能长一丢丢
