### ISSUE TITLE
怎么在编译的时候自定义kernel version

### ISSUE THREAD

**Issue by RukawaKaede** [coolsnowwolf/lede#917]
在自己编译完固件，安装完后，后续想要使用opkg安装新软件，会报kernel version不一致的错误：
```
Configuring kmod-fs-ntfs.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-ntfs:
 * 	kernel (= 4.14.63-1-a6ec9c2a1f53fed4bcb3063055b4e2fe) *
```

**Comment by RukawaKaede** [comment]
![image](https://user-images.githubusercontent.com/10842904/50049978-ef816680-012a-11e9-9aa6-cdf319aa0c00.png)

系统信息

**Comment by LGA1150** [comment]
这个需要编译时集成

**Comment by lyin888** [comment]
https://github.com/coolsnowwolf/lede/commit/111fb6c665f855a1c08ab5279edf3f5612ddff90

**Comment by littlesker** [comment]
恩山有个帖子，你可以看一下

**Comment by RukawaKaede** [comment]
结合以上的几个回答，经过搜索后发现以下有用链接：

https://www.right.com.cn/forum/thread-269954-1-1.html

对应的linux kernel 4.14.63的hash值在以下链接中有（google 关键字：openwrt LINUX_KERNEL_HASH 4.14.63）：

https://git.telliq.com/gtu/openwrt/commit/e4bad5f0ac9b8e6602181a51b1f97e39bef0595b
