### ISSUE TITLE
最近总是在make install这里出错

### ISSUE THREAD

**Issue by chd1998** [coolsnowwolf/lede#9172]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
github 云编译中最近总是这个错误
Q：是否搜索了issue (使用 "x" 选择)
* [ X] 没有类似的issue

## 2. 详细叙述
最后显示make install错误
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
x86-64
A：

### (3) 详细日志
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin
cp /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/bzImage /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin
cp /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin /workdir/openwrt/bin/targets/x86/64/openwrt-x86-64-generic-kernel.bin
[ -f /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/generic-kernel.bin -a -f /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs ]
dd if=/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.squashfs >> /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz
74693+1 records in
74693+1 records out
38243291 bytes (38 MB, 36 MiB) copied, 0.185705 s, 206 MB/s
dd if=/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz of=/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz.new bs=10737418240 conv=sync
make[5]: *** [Makefile:152: /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz] Killed
make[5]: *** Deleting file '/workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-x86-64-generic-squashfs-rootfs.img.gz'
make[5]: Leaving directory '/workdir/openwrt/target/linux/x86/image'
make[4]: *** [Makefile:29: install] Error 2
make[4]: Leaving directory '/workdir/openwrt/target/linux/x86'
make[3]: *** [Makefile:11: install] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/install#94.78#15.61#116.30
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/install] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:19: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.target_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.
A：

**Comment by WYC-2020** [comment]
从来没遇到过。看自己空间是否足够
