### ISSUE TITLE
turboacc 设置出错

### ISSUE THREAD

**Issue by WhiteHDD** [coolsnowwolf/lede#9179]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
MenuConfig里luci的turboacc设置选ecm后出错，如图1

![屏幕截图 2022-04-03 112000](https://user-images.githubusercontent.com/95892995/161409961-e1b4b52c-8087-4c5f-ab3b-c4116c3cfce1.png)

图2状态下编译后，部分不选，仍然会编译进去，而且shortcutfe会随系统缺省启动
![屏幕截图 2022-04-03 112048](https://user-images.githubusercontent.com/95892995/161410066-33baa22b-9c6a-4a4e-be97-8aeecdf6f9d7.png)

重新编译过2次，问题一样，感觉有点混乱～ 是否该整理一下？

**Comment by 1054009064** [comment]
这个是给 ipq806x ipq807x 用的

**Comment by WhiteHDD** [comment]
> 这个是给 ipq806x ipq807x 用的

是说设置显示，和组件编译管理有错误，这个我一般也不用，看着别扭～

**Comment by 1054009064** [comment]
> 是说设置显示，和组件编译管理有错误，这个我一般也不用，看着别扭～

引入这个的作者有解释过，你往以前的翻翻吧

**Comment by WYC-2020** [comment]
这个我好像以前优化过
