### ISSUE TITLE
如何自己更新v2ray

### ISSUE THREAD

**Issue by the55555day** [coolsnowwolf/lede#918]
如何自己更新package包里的v2ray版本？

**Comment by lyin888** [comment]
https://github.com/coolsnowwolf/lede/commit/48473537926de84f45f03fdfefc1d932181501d6

**Comment by the55555day** [comment]
> [4847353](https://github.com/coolsnowwolf/lede/commit/48473537926de84f45f03fdfefc1d932181501d6)

感谢，不过我用替换法试了一下，ssh进去，直接执行v2ray执行文件看版本号，的确是4.9了，虽然ipk显示是4.5。说明替换法是可行的。
