### ISSUE TITLE
为何今天更新环境 提示不能连接了？ amd64的包

### ISSUE THREAD

**Issue by ppyohhh** [coolsnowwolf/lede#9183]
重新用虚拟机更新ubantu为何环境配置提示连接不到amd64的包？ 你们有这个情况吗？
![20220403_180858](https://user-images.githubusercontent.com/102891822/161422451-3f08fe8b-2a9a-4e94-8bad-292e78612713.jpg)

**Comment by Dawneng** [comment]
换个国内镜像源

**Comment by ppyohhh** [comment]
> 换个国内镜像源

阿里？

**Comment by ppyohhh** [comment]
> 换个国内镜像源

谢谢
