### ISSUE TITLE
最新版本NEWIFI D2编译不选择luci-app-mtwifi会没有“无线”设置，选择后wifi会自动停止

### ISSUE THREAD

**Issue by iowi** [coolsnowwolf/lede#9185]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by zhoujinshi** [comment]
我测试过，不是自动启动问题，是设置lan口IP后就自动启动失败了，通过ssh进去修改的lan的IP就是正常的。

**Comment by zhoujinshi** [comment]
不过mtwifi这个插件不能设置[802.11k/v/r] 移动域无法配置

**Comment by iowi** [comment]
不要mtwifi如何设置才能有无线选项？

**Comment by zhoujinshi** [comment]
不选好像是通用wifi管理模块

**Comment by iowi** [comment]
> 不选好像是通用wifi管理模块，通用模块有这些配置

不选“网络”那就没有“无线”

**Comment by zhoujinshi** [comment]
是的，很纠结😣，不知道通知wifi模块怎么配置，网络一片空白，我复制别的配置使用云编译计算中。

**Comment by zhoujinshi** [comment]
lede以外其他的分支可以openwrt-immortalwrt，要对比下参数

**Comment by zhoujinshi** [comment]
6in4 - 26
adbyby - 2.7-2
appfilter - 5.0.1-2021-06-28-81f2e7ab-1
automount - 3
banip - 0.7.10-3
base-files - 1521-r19235-e80786fa7e
blkid - 2.36.1-2
block-mount - 2021-01-04-c53b1882-1
boost - 1.75.0-3
boost-date_time - 1.75.0-3
boost-program_options - 1.75.0-3
boost-system - 1.75.0-3
btrfs-progs - 5.11-1
busybox - 1.33.2-32
ca-bundle - 20210119-1
cgi-io - 2021-09-08-98cef9dd-20
cjdns - v21-3
collectd - 5.12.0-10
collectd-mod-cpu - 5.12.0-10
collectd-mod-interface - 5.12.0-10
collectd-mod-iwinfo - 5.12.0-10
collectd-mod-load - 5.12.0-10
collectd-mod-memory - 5.12.0-10
collectd-mod-network - 5.12.0-10
collectd-mod-rrdtool - 5.12.0-10
coreutils - 8.32-6
coreutils-base64 - 8.32-6
curl - 7.80.0-1
ddns-scripts - 2.8.2-12
ddns-scripts-services - 2.8.2-12
default-settings - 1.1-12
default-settings-chn - 1.1-12
dkjson - 2.5-4
dns2socks - 2.1-2
dnsmasq-full - 2.85-50
dropbear - 2020.81-2
e2fsprogs - 1.45.6-2
firewall - 2021-03-23-61db17ed-1
frpc - 0.38.0-1
fstools - 2021-01-04-c53b1882-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2020-10-25-9ef88681-2
hostapd-common - 2020-06-08-5a8b3662-40
ip-full - 5.11.0-3
ip6tables - 1.8.7-1
ip6tables-mod-nat - 1.8.7-1
ipset - 7.6-1
ipt2socks - 1.1.3-2
iptables - 1.8.7-1
iptables-mod-conntrack-extra - 1.8.7-1
iptables-mod-fullconenat - 2019-10-21-0cf3b48f-1
iptables-mod-ipopt - 1.8.7-1
iptables-mod-tproxy - 1.8.7-1
iptvhelper - 0.1.1-1
ipv6helper - 1.0-4
iw - 5.9-8fab0c9e-3
iwinfo - 2021-04-30-c45f0b58-2.1
jshn - 2021-05-16-b14c4688-2
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.4.182-1-bc0dff8c2e556008127cbce7b8bf977b
kmod-asn1-decoder - 5.4.182-1
kmod-cfg80211 - 5.4.182+5.10.85-1-1
kmod-crypto-acompress - 5.4.182-1
kmod-crypto-aead - 5.4.182-1
kmod-crypto-arc4 - 5.4.182-1
kmod-crypto-authenc - 5.4.182-1
kmod-crypto-crc32c - 5.4.182-1
kmod-crypto-ecb - 5.4.182-1
kmod-crypto-hash - 5.4.182-1
kmod-crypto-kpp - 5.4.182-1
kmod-crypto-lib-blake2s - 5.4.182-1
kmod-crypto-lib-chacha20 - 5.4.182-1
kmod-crypto-lib-chacha20poly1305 - 5.4.182-1
kmod-crypto-lib-curve25519 - 5.4.182-1
kmod-crypto-lib-poly1305 - 5.4.182-1
kmod-crypto-manager - 5.4.182-1
kmod-crypto-null - 5.4.182-1
kmod-crypto-pcompress - 5.4.182-1
kmod-crypto-sha1 - 5.4.182-1
kmod-crypto-user - 5.4.182-1
kmod-cryptodev - 5.4.182+1.11-ramips-1
kmod-fs-btrfs - 5.4.182-1
kmod-fs-exfat - 5.4.182+5.14.1-1
kmod-fs-ext4 - 5.4.182-1
kmod-fs-vfat - 5.4.182-1
kmod-fuse - 5.4.182-1
kmod-gpio-button-hotplug - 5.4.182-3
kmod-ifb - 5.4.182-1
kmod-ip6tables - 5.4.182-1
kmod-ipt-conntrack - 5.4.182-1
kmod-ipt-conntrack-extra - 5.4.182-1
kmod-ipt-core - 5.4.182-1
kmod-ipt-fullconenat - 5.4.182+2019-10-21-0cf3b48f-1
kmod-ipt-ipopt - 5.4.182-1
kmod-ipt-ipset - 5.4.182-1
kmod-ipt-nat - 5.4.182-1
kmod-ipt-nat6 - 5.4.182-1
kmod-ipt-offload - 5.4.182-1
kmod-ipt-raw - 5.4.182-1
kmod-ipt-tproxy - 5.4.182-1
kmod-iptunnel - 5.4.182-1
kmod-iptunnel4 - 5.4.182-1
kmod-leds-gpio - 5.4.182-1
kmod-lib-crc-ccitt - 5.4.182-1
kmod-lib-crc16 - 5.4.182-1
kmod-lib-crc32c - 5.4.182-1
kmod-lib-lzo - 5.4.182-1
kmod-lib-raid6 - 5.4.182-1
kmod-lib-textsearch - 5.4.182-1
kmod-lib-xor - 5.4.182-1
kmod-lib-zlib-deflate - 5.4.182-1
kmod-lib-zlib-inflate - 5.4.182-1
kmod-lib-zstd - 5.4.182-1
kmod-mac80211 - 5.4.182+5.10.85-1-1
kmod-macvlan - 5.4.182-1
kmod-mppe - 5.4.182-1
kmod-mt76-core - 5.4.182+2021-12-03-678071ef-4
kmod-mt7603 - 5.4.182+2021-12-03-678071ef-4
kmod-mt76x02-common - 5.4.182+2021-12-03-678071ef-4
kmod-mt76x2 - 5.4.182+2021-12-03-678071ef-4
kmod-mt76x2-common - 5.4.182+2021-12-03-678071ef-4
kmod-nf-conntrack - 5.4.182-1
kmod-nf-conntrack-netlink - 5.4.182-1
kmod-nf-conntrack6 - 5.4.182-1
kmod-nf-flow - 5.4.182-1
kmod-nf-ipt - 5.4.182-1
kmod-nf-ipt6 - 5.4.182-1
kmod-nf-nat - 5.4.182-1
kmod-nf-nat6 - 5.4.182-1
kmod-nf-nathelper - 5.4.182-1
kmod-nf-nathelper-extra - 5.4.182-1
kmod-nf-reject - 5.4.182-1
kmod-nf-reject6 - 5.4.182-1
kmod-nfnetlink - 5.4.182-1
kmod-nft-bridge - 5.4.182-1
kmod-nft-core - 5.4.182-1
kmod-nft-netdev - 5.4.182-1
kmod-nls-base - 5.4.182-1
kmod-nls-cp437 - 5.4.182-1
kmod-nls-iso8859-1 - 5.4.182-1
kmod-nls-utf8 - 5.4.182-1
kmod-oaf - 5.4.182+5.0.1-2021-06-28-81f2e7ab-1
kmod-ppp - 5.4.182-1
kmod-pppoe - 5.4.182-1
kmod-pppox - 5.4.182-1
kmod-sched-connmark - 5.4.182-1
kmod-sched-core - 5.4.182-1
kmod-scsi-core - 5.4.182-1
kmod-sit - 5.4.182-1
kmod-slhc - 5.4.182-1
kmod-tcp-bbr - 5.4.182-1
kmod-tun - 5.4.182-1
kmod-udptunnel4 - 5.4.182-1
kmod-udptunnel6 - 5.4.182-1
kmod-usb-core - 5.4.182-1
kmod-usb-ledtrig-usbport - 5.4.182-1
kmod-usb-printer - 5.4.182-1
kmod-usb-storage - 5.4.182-1
kmod-usb-storage-extras - 5.4.182-1
kmod-usb3 - 5.4.182-1
kmod-wireguard - 5.4.182-1
libattr - 2.4.48-2
libblkid1 - 2.36.1-2
libblobmsg-json20210516 - 2021-05-16-b14c4688-2
libbpf0 - 5.10.10-2
libc - 1.1.24-3
libcap - 2.43-1
libcomerr0 - 1.45.6-2
libcurl4 - 7.80.0-1
libelf1 - 0.180-1
libev - 4.31-1
libext2fs2 - 1.45.6-2
libgcc1 - 8.4.0-3
libgd - 2.3.0-3
libgmp10 - 6.2.1-1
libip4tc2 - 1.8.7-1
libip6tc2 - 1.8.7-1
libipset13 - 7.6-1
libiwinfo-data - 2021-04-30-c45f0b58-2.1
libiwinfo-lua - 2021-04-30-c45f0b58-2.1
libiwinfo20210430 - 2021-04-30-c45f0b58-2.1
libjpeg-turbo - 2.0.6-1
libjson-c5 - 0.15-2
libjson-script20210516 - 2021-05-16-b14c4688-2
libltdl7 - 2.4.6-2
liblua5.1.5 - 5.1.5-9
liblucihttp-lua - 2021-06-11-3dc89af4-1
liblucihttp0 - 2021-06-11-3dc89af4-1
liblzo2 - 2.10-4
libmbedtls12 - 2.16.12-19
libminiupnpc - 2.2.1-1
libmnl0 - 1.0.4-2
libmount1 - 2.36.1-2
libnatpmp1 - 20150609-3
libncurses6 - 6.2-3
libnetfilter-conntrack3 - 1.0.8-1
libnettle8 - 3.6-1
libnfnetlink0 - 1.0.1-4
libnftnl11 - 1.1.8-1
libnghttp2-14 - 1.43.0-1
libnl-tiny1 - 2020-08-05-c291088f-2
libopenldap - 2.4.57-1
libopenssl-conf - 1.1.1n-1
libopenssl1.1 - 1.1.1n-1
libpcre - 8.44-3
libpng - 1.6.37-10
libpthread - 1.1.24-3
libreadline8 - 8.1-1
librrd1 - 1.0.50-3
librt - 1.1.24-3
libsasl2 - 2.1.27-4
libsmartcols1 - 2.36.1-2
libsodium - 1.0.18-2022-02-27-2e9b4c47-1
libsqlite3-0 - 3330000-1
libss2 - 1.45.6-2
libstdcpp6 - 8.4.0-3
libubox20210516 - 2021-05-16-b14c4688-2
libubus-lua - 2021-06-30-4fc532c8-2
libubus20210630 - 2021-06-30-4fc532c8-2
libuci-lua - 2021-04-14-4b3db117-5
libuci20130104 - 2021-04-14-4b3db117-5
libuclient20201210 - 2021-05-14-6a6011df-1
libudns - 0.4-1
libustream-openssl20201210 - 2022-01-16-868fd881-1
libuuid1 - 2.36.1-2
libuv1 - 1.40.0-3
libwebp - 1.1.0-2
libwebsockets-full - 3.1.0-2
libwolfssl5.1.1.7a924b25 - 5.1.1-stable-2
libxtables12 - 1.8.7-1
logd - 2020-10-25-9ef88681-2
lsblk - 2.36.1-2
lua - 5.1.5-9
lua-bencode - 2.2.0-1
lua-sha2 - 0.2.0-1
luasocket - 2019-04-21-733af884-1
luci - git-22.077.20494-a30223d
luci-app-accesscontrol - 1
luci-app-adbyby-plus - 2.0
luci-app-aliddns - 0.3.0
luci-app-appfilter - 5.0.1
luci-app-argon-config - 0.9
luci-app-autoreboot - 1.0
luci-app-banip - git-22.077.20494-a30223d
luci-app-cjdns - 1.3-8
luci-app-ddns - git-22.077.20494-a30223d
luci-app-diskman - 0.2.11
luci-app-eqos - 1.0.0
luci-app-filetransfer - git-22.077.20494-a30223d
luci-app-firewall - git-22.077.20494-a30223d
luci-app-frpc - git-22.077.20494-a30223d
luci-app-guest-wifi - 1.0
luci-app-iptvhelper - 0.1.1
luci-app-mwan3 - git-22.077.20494-a30223d
luci-app-nft-qos - git-22.077.20494-a30223d
luci-app-opkg - git-22.077.20494-a30223d
luci-app-pppoe-relay - 1.0
luci-app-pppoe-server - 1
luci-app-qos - git-22.077.20494-a30223d
luci-app-rp-pppoe-server - git-22.077.20494-a30223d
luci-app-smartdns - 1.2020.30
luci-app-socat - git-22.077.20494-a30223d
luci-app-ssr-plus - 184
luci-app-statistics - git-22.077.20494-a30223d
luci-app-syncdial - 2.0
luci-app-timecontrol - 1.0
luci-app-ttyd - git-22.077.20494-a30223d
luci-app-turboacc - git-22.077.20494-a30223d
luci-app-uhttpd - git-22.077.20494-a30223d
luci-app-usb-printer - 1.0
luci-app-vnstat2 - git-22.077.20494-a30223d
luci-app-webadmin - 1.0
luci-app-wireguard - git-22.077.20494-a30223d
luci-app-zerotier - 1.0
luci-base - git-22.077.20494-a30223d
luci-compat - git-22.077.20494-a30223d
luci-i18n-accesscontrol-zh-cn - git-22.077.20494-a30223d
luci-i18n-adbyby-plus-zh-cn - git-22.077.20494-a30223d
luci-i18n-aliddns-zh-cn - git-22.077.20494-a30223d
luci-i18n-appfilter-zh-cn - git-22.077.20494-a30223d
luci-i18n-argon-config-zh-cn - git-22.077.20494-a30223d
luci-i18n-autoreboot-zh-cn - git-22.077.20494-a30223d
luci-i18n-banip-zh-cn - git-22.077.20494-a30223d
luci-i18n-base-zh-cn - git-22.077.20494-a30223d
luci-i18n-ddns-zh-cn - git-22.077.20494-a30223d
luci-i18n-diskman-zh-cn - git-22.077.20494-a30223d
luci-i18n-eqos-zh-cn - git-22.077.20494-a30223d
luci-i18n-filetransfer-zh-cn - git-22.077.20494-a30223d
luci-i18n-firewall-zh-cn - git-22.077.20494-a30223d
luci-i18n-frpc-zh-cn - git-22.077.20494-a30223d
luci-i18n-guest-wifi-zh-cn - git-22.077.20494-a30223d
luci-i18n-iptvhelper-zh-cn - git-22.077.20494-a30223d
luci-i18n-mwan3-zh-cn - git-22.077.20494-a30223d
luci-i18n-nft-qos-zh-cn - git-22.077.20494-a30223d
luci-i18n-opkg-zh-cn - git-22.077.20494-a30223d
luci-i18n-pppoe-relay-zh-cn - git-22.077.20494-a30223d
luci-i18n-pppoe-server-zh-cn - git-22.077.20494-a30223d
luci-i18n-qos-zh-cn - git-22.077.20494-a30223d
luci-i18n-rp-pppoe-server-zh-cn - git-22.077.20494-a30223d
luci-i18n-smartdns-zh-cn - git-22.077.20494-a30223d
luci-i18n-socat-zh-cn - git-22.077.20494-a30223d
luci-i18n-ssr-plus-zh-cn - git-22.077.20494-a30223d
luci-i18n-statistics-zh-cn - git-22.077.20494-a30223d
luci-i18n-timecontrol-zh-cn - git-22.077.20494-a30223d
luci-i18n-ttyd-zh-cn - git-22.077.20494-a30223d
luci-i18n-turboacc-zh-cn - git-22.077.20494-a30223d
luci-i18n-uhttpd-zh-cn - git-22.077.20494-a30223d
luci-i18n-usb-printer-zh-cn - git-22.077.20494-a30223d
luci-i18n-vnstat2-zh-cn - git-22.077.20494-a30223d
luci-i18n-webadmin-zh-cn - git-22.077.20494-a30223d
luci-i18n-wireguard-zh-cn - git-22.077.20494-a30223d
luci-i18n-zerotier-zh-cn - git-22.077.20494-a30223d
luci-lib-base - git-22.077.20494-a30223d
luci-lib-fs - 1.0-2
luci-lib-ip - git-22.077.20494-a30223d
luci-lib-ipkg - git-22.077.20494-a30223d
luci-lib-jsonc - git-22.077.20494-a30223d
luci-lib-nixio - git-22.077.20494-a30223d
luci-mod-admin-full - git-22.077.20494-a30223d
luci-mod-network - git-22.077.20494-a30223d
luci-mod-status - git-22.077.20494-a30223d
luci-mod-system - git-22.077.20494-a30223d
luci-proto-ipv6 - git-22.077.20494-a30223d
luci-proto-ppp - git-22.077.20494-a30223d
luci-proto-wireguard - git-22.077.20494-a30223d
luci-theme-argon - 2.2.9
luci-theme-bootstrap - git-22.077.20494-a30223d
microsocks - 1.0.3-1
mtd - 26
mwan3 - 2.10.13-1
netifd - 2021-10-30-8f82742c-1
nft-qos - 1.0.6-2
nftables-nojson - 0.9.6-2
ntfs-3g - 2017.3.23-1-fuseint
odhcp6c - 2021-01-09-53f07e90-16
odhcpd-ipv6only - 2021-07-18-bc9d317f-3
openssl-util - 1.1.1n-1
openwrt-keyring - 2022-01-22-57304d01-2
opkg - 2021-06-13-1bf042dd-1
p910nd - 0.97-9
parted - 3.4-1
pdnsd-alt - 1.2.9b-par-2
ppp - 2.4.8.git-2020-10-03-6
ppp-mod-pppoe - 2.4.8.git-2020-10-03-6
procd - 2021-03-08-2cfc26f8-1
qos-scripts - 1.3.1-31
resolveip - 2
rp-pppoe-common - 3.14-2
rp-pppoe-relay - 3.14-2
rp-pppoe-server - 3.14-2
rpcd - 2022-02-19-8d26a1ba-1
rpcd-mod-file - 2022-02-19-8d26a1ba-1
rpcd-mod-iwinfo - 2022-02-19-8d26a1ba-1
rpcd-mod-luci - 20210614
rpcd-mod-rrdns - 20170710
rrdtool1 - 1.0.50-3
shadowsocks-libev-config - 3.3.5-1
shadowsocks-libev-ss-local - 3.3.5-1
shadowsocks-libev-ss-redir - 3.3.5-1
shadowsocksr-libev-ssr-check - 2.5.6-9
shadowsocksr-libev-ssr-local - 2.5.6-9
shadowsocksr-libev-ssr-redir - 2.5.6-9
shellsync - 0.2-2
simple-obfs-client - 0.0.5-1
smartdns - 8.2021.27-1
smartmontools - 7.2-1
socat - 1.7.3.4-2
tc-mod-iptables - 5.11.0-3
tc-tiny - 5.11.0-3
tcping - 0.3-1
terminfo - 6.2-3
trojan - 1.16.0-2
ttyd - 1.6.3-3
ubi-utils - 2.1.2-1
ubox - 2020-10-25-9ef88681-2
ubus - 2021-06-30-4fc532c8-2
ubusd - 2021-06-30-4fc532c8-2
uci - 2021-04-14-4b3db117-5
uclibcxx - 0.2.5-3
uclient-fetch - 2021-05-14-6a6011df-1
uhttpd - 2021-03-21-15346de8-2
uhttpd-mod-ubus - 2021-03-21-15346de8-2
urandom-seed - 3
urngd - 2020-01-21-c7f7b6b6-2
usign - 2020-05-23-f1f65026-1
vnstat2 - 2.9-1
vnstati2 - 2.9-1
wget-ssl - 1.21.1-1
wireguard-tools - 1.0.20210223-2
wireless-regdb - 2021.08.28-1
wpad-basic-wolfssl - 2020-06-08-5a8b3662-40
xray-core - 1.5.4-1
zerotier - 1.6.6-2
zlib - 1.2.11-3
