### ISSUE TITLE
ipsec-server l2tp黑名单问题。

### ISSUE THREAD

**Issue by liangchaofu** [coolsnowwolf/lede#9189]
## 2. 详细叙述
l2tp黑名单会出现这个提醒
ipsec-server/online returns SimpleForm but is dispatched via cbi,
please change admin/services/ipsec-server/online to use the form()action instead
### (1) 具体问题
把ipsec-secver 改到服务那里了。

### (2) 路由器型号和固件版本
x86

### (3) 详细日志
![image](https://user-images.githubusercontent.com/70999087/161501884-decfeb17-d51e-4358-996e-6d35fe368734.jpg)

**Comment by liangchaofu** [comment]
用的是原版21.02.1

**Comment by WYC-2020** [comment]
你这个怕是登录过期了，重新登录就可以吧

**Comment by liangchaofu** [comment]
已解决，修改下文件就好了。
