### ISSUE TITLE
K2T刷最新固件会假死

### ISSUE THREAD

**Issue by littlesker** [coolsnowwolf/lede#919]
2018年12月17日
K2T刷最新编译固件会假死，刚通电可以访问路由器管理页面，过一会直接卡死，网路也不能访问

**Comment by tuanqing** [comment]
内存泄漏

**Comment by littlesker** [comment]
不知道什么情况 原来的4.9内核没问题，但是现在L大说现在不支持编译4.9，然后回退到4.14.78也不可以
