### ISSUE TITLE
哪位大佬有删除小米支持前的fork?

### ISSUE THREAD

**Issue by small-white-rabbit** [coolsnowwolf/lede#9191]
我原来下的以为出问题了删掉重下了，结果后面就没了，自己添加支持只有一个总是重启的Aiot天线，跪求一个lede的之前的fork，或者继承lede的，试过boose47的 感觉玩游戏不够稳定，所以还是想找到lede的

**Comment by WYC-2020** [comment]
自己不会revert吗
