### ISSUE TITLE
编译时如何选择特定版本内核

### ISSUE THREAD

**Issue by danuonuo** [coolsnowwolf/lede#9208]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：我希望使用5.15的内核版本，然而当我按照教程编译后内核却是5.4.188的

### (2) 路由器型号和固件版本

A：Xiaomi Mi Router 3G (CpuMark : 5145.190854 Scores)
      OpenWrt R22.4.1 / LuCI Master (git-22.095.24346-72703c8)

### (3) 详细日志

A：即使make menuconfig里启用enable experimental features也没用。

谢谢

**Comment by sbwcwfhv001** [comment]
为什么没有人评论，哈哈

**Comment by WYC-2020** [comment]
这种问题鬼才评论，再说有类似的issue没有立刻关闭都是好的

**Comment by ZGNCZMY** [comment]
这种问题....

**Comment by liwenjie119** [comment]
不是在general build options--enable testing kernel吗
