### ISSUE TITLE
勾选编译iso文件就报错

### ISSUE THREAD

**Issue by SHMILYCXY** [coolsnowwolf/lede#9213]
Checking 'mkisofs'... failed.

: Please install mkisofs.

make[6]: *** [/home/shmilycxy/lede/include/prereq.mk:9: prereq] Error 1
make[5]: *** [Makefile:27: image-prereq] Error 2
make[4]: *** [Makefile:11: prereq] Error 2
time: target/linux/prereq#0.30#0.11#0.39
    ERROR: target/linux failed to build.
make[3]: *** [target/Makefile:25: target/linux/prereq] Error 1
make[2]: *** [target/Makefile:17: /home/shmilycxy/lede/staging_dir/target-x86_64_musl/stamp/.target_prereq] Error 2
make[1]: *** [/home/shmilycxy/lede/include/toplevel.mk:208: prereq] Error 2
make: *** [/home/shmilycxy/lede/include/toplevel.mk:228: world] Error 2

**Comment by coolsnowwolf** [comment]
Please install mkisofs.
