### ISSUE TITLE
编译成功 但刷写的时候提示 Image metadata not present

### ISSUE THREAD

**Issue by sirstrone** [coolsnowwolf/lede#9222]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [] 没有类似的issue

### (1) 具体问题
A：编译成功 用lede-web 刷写后未重启
用ssh 刷写后 提示:
```
root@OpenWrt:~# sysupgrade -v -n /tmp/openwrt-x86-64-generic-squashfs-combined-efi.img 
Sun Apr 10 21:30:26 CST 2022 upgrade: Image metadata not present
Sun Apr 10 21:30:26 CST 2022 upgrade: Invalid image type
```

### (2) 路由器型号和固件版本
A： x86_64

### (3) 详细日志

A：
log 和 kernel 看上去没有啥有效信息 
.config
[config.txt](https://github.com/coolsnowwolf/lede/files/8459097/config.txt)

**Comment by coolsnowwolf** [comment]
版本差异太大，用 sysupgrade -F
