### ISSUE TITLE
依然无法通过编译

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#9237]
(cd mt76-2022-04-07-506bb060 && git checkout 506bb0605e3e2fa4c5285e6c8866167691a6d71b && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd mt76-2022-04-07-506bb060 && git log -1 --format='\''@%ct'\''` && rm -rf mt76-2022-04-07-506bb060/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c mt76-2022-04-07-506bb060 | 	xz -zc -7e > /home/gswangmd/lede/tmp/dl/mt76-2022-04-07-506bb060.tar.xz && mv /home/gswangmd/lede/tmp/dl/mt76-2022-04-07-506bb060.tar.xz /home/gswangmd/lede/dl/ && rm -rf mt76-2022-04-07-506bb060; );  )    '
rm -f /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/.built
touch /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/.built_check
make  -C "/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.4.188" KCFLAGS="-fmacro-prefix-map=/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl" HOSTCFLAGS="-O2 -I/home/gswangmd/lede/staging_dir/host/include -I/home/gswangmd/lede/staging_dir/hostpkg/include -I/home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Mon Apr 11 07:53:18 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/gswangmd/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/gswangmd/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/symvers/cryptodev-linux.symvers /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/symvers/shortcut-fe.symvers /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/symvers/mac80211.symvers" KERNELRELEASE=5.4.188 CONFIG_MT76_USB=m CONFIG_MT76x02_LIB=m CONFIG_MT76x02_USB=m CONFIG_MT76x0_COMMON=m CONFIG_MT76x0U=m CONFIG_MT76x2_COMMON=m CONFIG_MT76x2U=m CONFIG_MT76_CONNAC_LIB=m CONFIG_MT7615_COMMON=m CONFIG_MT7663_USB_SDIO_COMMON=m CONFIG_MT7663U=m M="/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060" NOSTDINC_FLAGS="-nostdinc  -isystem /home/gswangmd/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/lib/gcc/aarch64-openwrt-linux-musl/8.4.0/include -I/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060 -I/home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport/uapi -I/home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211-backport -I/home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211/uapi -I/home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211 -include backport/autoconf.h -include backport/backport.h -DCONFIG_MAC80211_MESH" modules
make[4]: Entering directory '/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.4.188'
  CC [M]  /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/main.o
In file included from /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/../mt76_connac.h:7,
                 from /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/../mt76_connac_mcu.h:7,
                 from /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/mt7615.h:11,
                 from /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/main.c:12:
/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/../mt76.h:16:10: fatal error: linux/soc/mediatek/mtk_wed.h: No such file or directory
 #include <linux/soc/mediatek/mtk_wed.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:262: /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615/main.o] Error 1
make[5]: *** [scripts/Makefile.build:497: /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/mt7615] Error 2
make[4]: *** [Makefile:1734: /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060] Error 2
make[4]: Leaving directory '/home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.4.188'
make[3]: *** [Makefile:469: /home/gswangmd/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/mt76-2022-04-07-506bb060/.built] Error 2
make[3]: Leaving directory '/home/gswangmd/lede/package/kernel/mt76'
time: package/kernel/mt76/compile#0.94#0.12#1.17
    ERROR: package/kernel/mt76 failed to build.
make[2]: *** [package/Makefile:116: package/kernel/mt76/compile] Error 1
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:110: /home/gswangmd/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:230: world] Error 2
gswangmd@WMD-HOME:~/lede$

**Comment by WYC-2020** [comment]
万能大法重新来，我测过没问题
