### ISSUE TITLE
5.4.188固件编译问题，请求帮助

### ISSUE THREAD

**Issue by zbluekuma** [coolsnowwolf/lede#9245]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
固件编译，选择kernel5.4版本，编译错误，5.10和5.15版本编译正常
### (1) 具体问题

A：删除了一次lede文件夹，重新git clone也还是不行。

### (2) 路由器型号和固件版本

A：ARRIS SBR-AC1750路由器（QCA9880+QCA9558+QCA8337）

### (3) 详细日志

A：make[1]: Entering directory '/home/cnz/lede'
make[2]: Entering directory '/home/cnz/lede'
make[3]: Entering directory '/home/cnz/lede/target/linux'
make[4]: Entering directory '/home/cnz/lede/target/linux/ath79'
rm -f /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/localversion
/home/cnz/lede/scripts/kconfig.pl  + + /home/cnz/lede/target/linux/generic/config-5.4 /home/cnz/lede/target/linux/ath79/config-5.4 /home/cnz/lede/target/linux/ath79/nand/config-default > /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/cnz/lede/.config >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target
/home/cnz/lede/scripts/package-metadata.pl kconfig /home/cnz/lede/tmp/.packageinfo /home/cnz/lede/.config 5.4 > /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.override
/home/cnz/lede/scripts/kconfig.pl 'm+' '+' /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.target /dev/null /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.override > /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set
mv /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.old
grep -v INITRAMFS /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.old > /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set
rm -rf /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/modules
cmp -s /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.prev || { cp /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config; cp /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.prev; }
export MAKEFLAGS= ; [ -d /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/user_headers ] || make -C /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188 KCFLAGS="-fmacro-prefix-map=/home/cnz/lede/build_dir/target-mips_24kc_musl=target-mips_24kc_musl" HOSTCFLAGS="-O2 -I/home/cnz/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mips-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Tue Apr 12 04:59:09 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/cnz/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/cnz/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.188 CC="mips-openwrt-linux-musl-gcc" INSTALL_HDR_PATH=/home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/user_headers headers_install
grep '=[ym]' /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.config.set | LC_ALL=C sort | /home/cnz/lede/staging_dir/host/bin/mkhash md5 > /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.vermagic
touch /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.configured
rm -f /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/vmlinux /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/System.map
make -C /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188 KCFLAGS="-fmacro-prefix-map=/home/cnz/lede/build_dir/target-mips_24kc_musl=target-mips_24kc_musl" HOSTCFLAGS="-O2 -I/home/cnz/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mips-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Tue Apr 12 04:59:09 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/cnz/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/cnz/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.188 CC="mips-openwrt-linux-musl-gcc" olddefconfig
make[5]: Entering directory '/home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188'
scripts/kconfig/conf  --olddefconfig Kconfig
net/sched/Kconfig:45: warning: menuconfig statement without prompt
net/Kconfig:478:warning: multi-line strings not supported
drivers/mfd/Kconfig:2016:warning: multi-line strings not supported
#
# No change to .config
#
make[5]: Leaving directory '/home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188'
make -C /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188 KCFLAGS="-fmacro-prefix-map=/home/cnz/lede/build_dir/target-mips_24kc_musl=target-mips_24kc_musl" HOSTCFLAGS="-O2 -I/home/cnz/lede/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="mips-openwrt-linux-musl-" ARCH="mips" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Tue Apr 12 04:59:09 2022" KBUILD_BUILD_VERSION="0" HOST_LOADLIBES="-L/home/cnz/lede/staging_dir/host/lib" KBUILD_HOSTLDLIBS="-L/home/cnz/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.4.188 CC="mips-openwrt-linux-musl-gcc" all modules
make[5]: Entering directory '/home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188'
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      drivers/mtd/nand/raw/ar934x_nand.o
drivers/mtd/nand/raw/ar934x_nand.c: In function 'ar934x_nfc_cmdfunc':
drivers/mtd/nand/raw/ar934x_nand.c:723:16: error: 'struct nand_ecc_ctrl' has no member named 'engine_type'
   if (nand->ecc.engine_type == NAND_ECC_ENGINE_TYPE_ON_HOST) {
                ^
drivers/mtd/nand/raw/ar934x_nand.c:723:32: error: 'NAND_ECC_ENGINE_TYPE_ON_HOST' undeclared (first use in this function); did you mean 'NAND_CI_CELLTYPE_SHIFT'?
   if (nand->ecc.engine_type == NAND_ECC_ENGINE_TYPE_ON_HOST) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                NAND_CI_CELLTYPE_SHIFT
drivers/mtd/nand/raw/ar934x_nand.c:723:32: note: each undeclared identifier is reported only once for each function it appears in
drivers/mtd/nand/raw/ar934x_nand.c: In function 'ar934x_nfc_attach_chip':
drivers/mtd/nand/raw/ar934x_nand.c:1331:15: error: 'struct nand_ecc_ctrl' has no member named 'engine_type'
  if (nand->ecc.engine_type == NAND_ECC_ENGINE_TYPE_ON_HOST) {
               ^
drivers/mtd/nand/raw/ar934x_nand.c:1331:31: error: 'NAND_ECC_ENGINE_TYPE_ON_HOST' undeclared (first use in this function); did you mean 'NAND_CI_CELLTYPE_SHIFT'?
  if (nand->ecc.engine_type == NAND_ECC_ENGINE_TYPE_ON_HOST) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               NAND_CI_CELLTYPE_SHIFT
drivers/mtd/nand/raw/ar934x_nand.c:1335:22: error: 'struct nand_ecc_ctrl' has no member named 'engine_type'
  } else if (nand->ecc.engine_type != NAND_ECC_ENGINE_TYPE_SOFT) {
                      ^
drivers/mtd/nand/raw/ar934x_nand.c:1335:38: error: 'NAND_ECC_ENGINE_TYPE_SOFT' undeclared (first use in this function); did you mean 'NAND_CI_CELLTYPE_SHIFT'?
  } else if (nand->ecc.engine_type != NAND_ECC_ENGINE_TYPE_SOFT) {
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
                                      NAND_CI_CELLTYPE_SHIFT
In file included from ./include/linux/dma-mapping.h:7,
                 from drivers/mtd/nand/raw/ar934x_nand.c:15:
drivers/mtd/nand/raw/ar934x_nand.c:1336:50: error: 'struct nand_ecc_ctrl' has no member named 'engine_type'
   dev_err(dev, "unknown ECC mode %d\n", nand->ecc.engine_type);
                                                  ^
./include/linux/device.h:1742:32: note: in definition of macro 'dev_err'
  _dev_err(dev, dev_fmt(fmt), ##__VA_ARGS__)
                                ^~~~~~~~~~~
drivers/mtd/nand/raw/ar934x_nand.c:1338:32: error: 'NAND_ECC_ALGO_BCH' undeclared (first use in this function); did you mean 'NAND_ECC_BCH'?
  } else if ((nand->ecc.algo != NAND_ECC_ALGO_BCH) &&
                                ^~~~~~~~~~~~~~~~~
                                NAND_ECC_BCH
drivers/mtd/nand/raw/ar934x_nand.c:1339:25: error: 'NAND_ECC_ALGO_HAMMING' undeclared (first use in this function); did you mean 'NAND_ECC_HAMMING'?
      (nand->ecc.algo != NAND_ECC_ALGO_HAMMING)) {
                         ^~~~~~~~~~~~~~~~~~~~~
                         NAND_ECC_HAMMING
drivers/mtd/nand/raw/ar934x_nand.c: In function 'ar934x_nfc_probe':
drivers/mtd/nand/raw/ar934x_nand.c:1428:11: error: 'struct nand_ecc_ctrl' has no member named 'engine_type'
  nand->ecc.engine_type = NAND_ECC_ENGINE_TYPE_ON_HOST; /* default */
           ^
drivers/mtd/nand/raw/ar934x_nand.c:1428:26: error: 'NAND_ECC_ENGINE_TYPE_ON_HOST' undeclared (first use in this function); did you mean 'NAND_CI_CELLTYPE_SHIFT'?
  nand->ecc.engine_type = NAND_ECC_ENGINE_TYPE_ON_HOST; /* default */
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          NAND_CI_CELLTYPE_SHIFT
make[9]: *** [scripts/Makefile.build:262: drivers/mtd/nand/raw/ar934x_nand.o] Error 1
make[8]: *** [scripts/Makefile.build:497: drivers/mtd/nand/raw] Error 2
make[7]: *** [scripts/Makefile.build:497: drivers/mtd/nand] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/mtd] Error 2
make[5]: *** [Makefile:1734: drivers] Error 2
make[5]: Leaving directory '/home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188'
make[4]: *** [Makefile:21: /home/cnz/lede/build_dir/target-mips_24kc_musl/linux-ath79_nand/linux-5.4.188/.modules] Error 2
make[4]: Leaving directory '/home/cnz/lede/target/linux/ath79'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/cnz/lede/target/linux'
time: target/linux/compile#6.77#4.53#10.83
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/cnz/lede'
make[1]: *** [target/Makefile:18: /home/cnz/lede/staging_dir/target-mips_24kc_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/cnz/lede'
make: *** [/home/cnz/lede/include/toplevel.mk:230: world] Error 2

**Comment by WYC-2020** [comment]
到时贴一张 选择的图片撒，或者config 撒 不是每个人都完全知道 每个平台在那个位置，知道怎么选

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/lede/commit/5da8b41f04ee78834767e2624b9be08ca0892690
@zbluekuma

**Comment by zbluekuma** [comment]
> 到时贴一张 选择的图片撒，或者config 撒 不是每个人都完全知道 每个平台在那个位置，知道怎么选

 @谢谢好心人，大法师！
