### ISSUE TITLE
建议增加zte_e8820s路由器的硬改spi（16m）的对应dts和mk文件

### ISSUE THREAD

**Issue by jin3014test2** [coolsnowwolf/lede#9246]
曾经刷高恪，后来想恢复openwrt

**Comment by wuzhuang123** [comment]
![image](https://user-images.githubusercontent.com/48048965/162983081-af10ef70-b798-4d3d-945b-0c46f744ee1c.png)
这是我迅雷下载宝16M改32M的文件，16M是0xfb0000,32M是0x1fb0000,根据容量减去前面的0x50000得出。然后在mk文件里是
32448k,也就是0x1fb0000。
![image](https://user-images.githubusercontent.com/48048965/162984434-bbd8f0fd-e9c0-4085-becd-712038cdc554.png)
一个简单的办法就是直接在这两个数值上加上增加的容量32-16=16MB。

**Comment by jin3014test2** [comment]
库里e8820s的dts是nand的，是否可以直接把nand段直接替换为库里8820v2的spi字段（和你这个下载宝一摸一样），然后mk文件也参照这个写？

**Comment by wuzhuang123** [comment]
抱歉，这个不清楚机理，可能需要改启动代码的。
