### ISSUE TITLE
编译错误mt

### ISSUE THREAD

**Issue by xiangfeigao** [coolsnowwolf/lede#9249]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译报错

### (2) 路由器型号和固件版本

A：hc5962极路由4

### (3) 详细日志

A：-- Build files have been written to: /DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688
touch /DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688/.configured
MAKEFLAGS="" /DiskB/lede/staging_dir/host/bin/ninja  -j1 -C /DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688
ninja: Entering directory `/DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688'
[35/42] Building C object CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o
FAILED: CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o
/DiskB/lede/staging_dir/host/bin/gcc -Dblobmsg_json_EXPORTS  -O2 -I/DiskB/lede/staging_dir/host/include -I/DiskB/lede/staging_dir/hostpkg/include -I/DiskB/lede/staging_dir/target-mipsel_24kc_musl/host/include -DNDEBUG -fPIC   -Wall -Werror -Wextra -Werror=implicit-function-declaration -Wformat -Werror=format-security -Werror=format-nonliteral -Os -std=gnu99 -g3 -Wmissing-declarations -Wno-unused-parameter -MD -MT CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o -MF CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o.d -o CMakeFiles/blobmsg_json.dir/blobmsg_json.c.o -c /DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688/blobmsg_json.c
/DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688/blobmsg_json.c:23:11: fatal error: json/json.h: No such file or directory
  #include <json/json.h>
           ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:116: /DiskB/lede/build_dir/hostpkg/libubox-2021-05-16-b14c4688/.built] Error 1
make[3]: Leaving directory '/DiskB/lede/package/libs/libubox'
time: package/libs/libubox/host-compile#2.07#0.35#2.66
    ERROR: package/libs/libubox [host] failed to build.
make[2]: *** [package/Makefile:114: package/libs/libubox/host/compile] Error 1
make[2]: Leaving directory '/DiskB/lede'
make[1]: *** [package/Makefile:110: /DiskB/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/DiskB/lede'

**Comment by WYC-2020** [comment]
万能大法
