### ISSUE TITLE
家长控制插件

### ISSUE THREAD

**Issue by w461481838** [coolsnowwolf/lede#9251]
有没有能在特定时间段屏蔽某些域名的插件啊。用来限制孩子的访问内容的插件，求大佬推荐

**Comment by 7noemo** [comment]
内置了吧 luci-app-oaf

**Comment by lxwq** [comment]
> 

这个好像早就没人维护了,作者做商业开发啦,

**Comment by 7noemo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ihuaer** [comment]
> 

使用商业固件比如爱快，openwrt当旁路由或者二级路由使用

**Comment by w461481838** [comment]
luci-app-oaf 没有定时功能，我想设置11:30-15:00 和 23:00-08:00 才屏蔽

**Comment by w461481838** [comment]
换个商业固件吗。。。我现在的lede已经做了很多设置，不想换固件。没有的话，看来只好多买一个路由器了。。。

**Comment by w461481838** [comment]
换个商业固件吗。。。我现在的lede已经做了很多设置，不想换固件。没有适合的插件的话，看来只好多买一个路由器了。。。

**Comment by WYC-2020** [comment]
这插件不重要 重要的是特征库如果特征库在更新 这插件就是好的，插件说白了就一个皮，你应该看那个特征库是否在更新

**Comment by WYC-2020** [comment]
https://github.com/destan19/OpenAppFilter  并且这个应该是有定时的功能的 自己去看下

**Comment by ihuaer** [comment]
> 换个商业固件吗。。。我现在的lede已经做了很多设置，不想换固件。没有适合的插件的话，看来只好多买一个路由器了。。。

lede不动，lan口再加装个爱快或者高格路由器二级路由器，你要的功能都能实现，

**Comment by 7noemo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
