### ISSUE TITLE
原版openwrt21.02 5.4.154 能用ntfs3吗。ntfs-3g有点慢。

### ISSUE THREAD

**Issue by liangchaofu** [coolsnowwolf/lede#9258]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
原版openwrt21.02 5.4.154 能用ntfs3吗。ntfs-3g有点慢。
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
原版openwrt21.02 5.4.154 能用ntfs3吗。ntfs-3g有点慢。
### (1) 具体问题
原版openwrt21.02 5.4.154 能用ntfs3吗。ntfs-3g有点慢。
A：

### (2) 路由器型号和固件版本
x86-64
A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
ntfs3-oot不香？

**Comment by WYC-2020** [comment]
我有一个修改版，能支持5.4 5.10 5.15

**Comment by liangchaofu** [comment]
ntfs3-oot能用吗？  5.4

**Comment by WYC-2020** [comment]
你在逗我，这驱动本来就是支持5.4 5.10的，本来就是给他们用的，5.15是不支持的，但是可以修改后就可以支持

**Comment by liangchaofu** [comment]
![捕获](https://user-images.githubusercontent.com/70999087/163667408-17cae0aa-fb9d-4549-adfc-a5351fc2b27e.JPG)
下载这三个放在package就变依旧可以了吧。

**Comment by liangchaofu** [comment]
已搞掂，谢谢大佬指点。速度反应快多了。
