### ISSUE TITLE
希望更新下mwlfifi驱动

### ISSUE THREAD

**Issue by liuleisail** [coolsnowwolf/lede#926]
https://github.com/kaloz/mwlwifi

已经更新到1210了，不过现在编译的好像是3月份的。

**Comment by gavin219** [comment]
PKG_SOURCE_DATE:=2018-12-18
PKG_SOURCE_VERSION:=c2c8244d8fea5d59762cb14438ded00bf6d5965c
PKG_MIRROR_HASH:=60fc25814349fccfbce7981a7d299665334829a70bf2310b3b87064cec5c6388
