### ISSUE TITLE
关于 promiscuous mode

### ISSUE THREAD

**Issue by iory123** [coolsnowwolf/lede#9261]
每次都是自动进入这个模式：

[    8.497840] 8021q: adding VLAN 0 to HW filter on device eth0
[    8.499132] br-lan: port 1(eth0) entered blocking state
[    8.500164] br-lan: port 1(eth0) entered disabled state
[    8.501261] device eth0 entered promiscuous mode
[    8.550855] iavf 0000:13:00.0: Failed to add VLAN filter, error IAVF_ERR_PARAM

能否设置在启动时不自动进入promiscuous mode（混杂模式）？相同环境在Ubuntu下测试就不会自动进入这个模式，是不是openwrt强制在此模式下

**Comment by coolsnowwolf** [comment]
br-lan 是网桥，默认里面的 eth 就是混杂模式

**Comment by iory123** [comment]
大佬，有办法不进入这个模式吗？

**Comment by iory123** [comment]
自己想办法吧
