### ISSUE TITLE
网口的mac地址是在什么文件中读取的还是随机计算的？

### ISSUE THREAD

**Issue by jin3014test2** [coolsnowwolf/lede#9263]
我编译的8820s固件，实际的网口地址：wan口是eeprom中的指定位置（0xe006），但lan口地址数值在eeprom中找不到。5g口在eeprom的0x0004处，2.4g口的地址数值在eeprom找不到。这找不到的地址数值是随机计算来的么？

**Comment by WYC-2020** [comment]
网卡的mac地址 那是出厂设定全球唯一的

**Comment by Subdue0** [comment]
> 我编译的8820s固件，实际的网口地址：wan口是eeprom中的指定位置（0xe006），但lan口地址数值在eeprom中找不到。5g口在eeprom的0x0004处，2.4g口的地址数值在eeprom找不到。这找不到的地址数值是随机计算来的么？

一般有5G就会根据5G计算出其他地址，你可以看看它们的地址其实非常相似，只是个别不同
