### ISSUE TITLE
collect2: error: ld returned 1 exit status这个是什么错误

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#9265]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
开始只要几个插件而已出现错误后面去掉了所有的插件还是一样的错误，请问这个 怎么回事，路由也开着大陆IP模式 梯子没问题的啊，这个怎么回事？
### (1) 具体问题

A： 编译失败

### (2) 路由器型号和固件版本
 
A：  小米4

### (3) 详细日志

A：
/usr/bin/ld: /home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/gcc/./gtype-c.h:167: undefined reference to `gt_clear_caches_gt_ubsan_h()'
/usr/bin/ld: c/c-lang.o:(.rodata+0x70): undefined reference to `gt_pch_rs_gt_ubsan_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0xc8): undefined reference to `gt_ggc_rd_gt_tree_iterator_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0xd0): undefined reference to `gt_ggc_rd_gt_tree_phinodes_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x1c8): undefined reference to `gt_ggc_r_gt_tree_chkp_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x1d0): undefined reference to `gt_ggc_r_gt_tree_ssa_address_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x1e8): undefined reference to `gt_ggc_r_gt_tree_scalar_evolution_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x1f0): undefined reference to `gt_ggc_r_gt_tree_profile_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x1f8): undefined reference to `gt_ggc_r_gt_tree_nested_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x238): undefined reference to `gt_ggc_r_gt_trans_mem_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x248): undefined reference to `gt_ggc_r_gt_asan_h'
/usr/bin/ld: c/c-lang.o:(.rodata+0x250): undefined reference to `gt_ggc_r_gt_ubsan_h'
/usr/bin/ld: c-family/c-dump.o: in function `c_dump_tree(void*, tree_node*)':
/home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/c-family/c-dump.c:42: undefined reference to `dump_string(dump_info*, char const*)'
collect2: error: ld returned 1 exit status
make[5]: *** [/home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0/gcc/c/Make-lang.in:85: cc1] Error 1
make[5]: Leaving directory '/home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/gcc'
make[4]: *** [Makefile:4251: all-gcc] Error 2
make[4]: Leaving directory '/home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial'
make[3]: *** [Makefile:37: /home/bbb/lede/build_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/gcc-8.4.0-initial/.built] Error 2
make[3]: Leaving directory '/home/bbb/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#15.29#111.43#91.87
    ERROR: toolchain/gcc/initial failed to build.
make[2]: *** [toolchain/Makefile:97: toolchain/gcc/initial/compile] Error 1
make[2]: Leaving directory '/home/bbb/lede'
make[1]: *** [toolchain/Makefile:93: /home/bbb/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/home/bbb/lede'
make: *** [/home/bbb/lede/include/toplevel.mk:230：world] 错误 2

**Comment by WYC-2020** [comment]
自己万能大法试下，还有错误再说
