### ISSUE TITLE
编译固件完成，怎么SSR界面是空白的？

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#9268]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：https://github.com/fw876/helloworld 源码是用他的，编译完成 发现SSR界面怎么是空白的，怎么回事
https://www.right.com.cn/forum/thread-8222959-1-1.html 论坛发帖问了
### (2) 路由器型号和固件版本
  
A：小米4

### (3) 详细日志

[A：

**Comment by WYC-2020** [comment]
少配置文件？

**Comment by coolsnowwolf** [comment]
高级配置，还原配置。你继承了其他人的配置了
