### ISSUE TITLE
ipq8071怎么编译

### ISSUE THREAD

**Issue by yuanlun1983** [coolsnowwolf/lede#9274]
小米ax6,ax3600,以前有ipq8071系cpu编译选项，现在怎么没了？要怎么编译呢？

**Comment by mitsukileung** [comment]
找以前的PR，自己加回去吧

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/163951666-de096135-1c31-43be-af5f-dcbf08136944.png)
是这玩意？

**Comment by yuanlun1983** [comment]
> ![image](https://user-images.githubusercontent.com/34025388/163951666-de096135-1c31-43be-af5f-dcbf08136944.png) 是这玩意？
怎么弄的呢？

**Comment by yuanlun1983** [comment]
> 找以前的PR，自己加回去吧

什么是pr，能说具体点吗？

**Comment by WYC-2020** [comment]
这玩意被删除了，有人搞闭源了 自然被删除了

**Comment by yuanlun1983** [comment]
> 这玩意被删除了，有人搞闭源了 自然被删除了

那这cpu平台的机器都不能编译了？

**Comment by WYC-2020** [comment]
> > 这玩意被删除了，有人搞闭源了 自然被删除了
> 
> 那这cpu平台的机器都不能编译了？
嗯哼说白了就是不支持了，就这个提交删除了，你可以恢复但是是否有bug未知，我仓库是恢复了，但是从来没用过
https://github.com/coolsnowwolf/lede/commit/edbd8d2e9839357f3a4f0a06174d243f362b1544
