### ISSUE TITLE
使用pdnsd，访问有些网页的时候会先访问失败，过一会刷新后才能打开

### ISSUE THREAD

**Issue by Gleeeeeman** [coolsnowwolf/lede#9276]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：现在使用的是passwall，dns用的是passwall中自带的“pdnsd 通过TCP节点请求DNS”，其他的都是默认设置。
局域网客户端获取到的dns地址是指向路由器地址的。
现在出现了一个问题，就是访问有一些网站的时候，会先显示找不到dns，然后网页访问失败。过一会再刷新才会刷新出页面。
关掉pdnsd之后就没有这个问题。

### (2) 路由器型号和固件版本

A：OpenWrt R21.11.11

### (3) 详细日志

A：无

**Comment by WYC-2020** [comment]
隔壁
