### ISSUE TITLE
mtk-eip93 fails to build on testing kernel 5.15 mt7621

### ISSUE THREAD

**Issue by Stkrx** [coolsnowwolf/lede#9304]
make[5]: *** [scripts/Makefile.build:277: /home/moises/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93-2020-12-10-bb5fd1c8/src/eip93-core.o] Error 1
make[4]: *** [Makefile:1868: /home/moises/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93-2020-12-10-bb5fd1c8/src] Error 2
make[4]: Leaving directory '/home/moises/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/linux-5.15.35'
make[3]: *** [Makefile:61: /home/moises/lede/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/mtk-eip93-2020-12-10-bb5fd1c8/.built] Error 2
make[3]: Leaving directory '/home/moises/lede/package/lean/mtk-eip93'
time: package/lean/mtk-eip93/compile#0.86#0.10#0.90
    ERROR: package/lean/mtk-eip93 failed to build.
make[2]: *** [package/Makefile:116: package/lean/mtk-eip93/compile] Error 1
make[2]: Leaving directory '/home/moises/lede'
make[1]: *** [package/Makefile:110: /home/moises/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/moises/lede'
make[1]: Leaving directory '/home/moises/lede'
make: *** [/home/moises/lede/include/toplevel.mk:230: world] Error 2

**Comment by WYC-2020** [comment]
看我仓库
