### ISSUE TITLE
最新版的ubuntu会报错。

### ISSUE THREAD

**Issue by sincere518** [coolsnowwolf/lede#9306]
最新版的ubuntu会报错。
CMake Error at /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:123 (set):
  Syntax error in cmake code at

    /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:123

  when parsing string

    ;/home/user\�\�\�\�\�\�/openwrt/lede/staging_dir/host/lib

  Invalid escape sequence \�
Call Stack (most recent call first):
  /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:150 (_pkgconfig_set)
  /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:165 (_pkgconfig_invoke)
  /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:637 (_pkgconfig_invoke_dyn)
  /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  /home/user/桌面/openwrt/lede/staging_dir/host/share/cmake-3.22/Modules/FindOpenSSL.cmake:134 (pkg_check_modules)
  CMakeLists.txt:6 (INCLUDE)

**Comment by liangchaofu** [comment]
不要有中文 空格
