### ISSUE TITLE
编译libubox-2021-05-16-b14c4688多次报错

### ISSUE THREAD

**Issue by Jernin** [coolsnowwolf/lede#9307]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：大佬您好，我已经试了一天了。由于英语很差，大概好像的意思是/home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/lua/uloop.c没有这个文件？但是我很确定有这个文件，而且我看了下好的dl包也是正常的 求大佬帮助

### (2) 路由器型号和固件版本

A：X86  仓库最新代码

### (3) 详细日志

A：make[3]: Entering directory '/home/jernin/lede/package/libs/libubox'
mkdir -p /home/jernin/lede/dl
SHELL= flock /home/jernin/lede/tmp/.libubox-2021-05-16-b14c4688.tar.xz.flock -c '  	/home/jernin/lede/scripts/download.pl "/home/jernin/lede/dl" "libubox-2021-05-16-b14c4688.tar.xz" "7dd1db1e0074a9c7c722db654cce3111b3bd3cff0bfd791c4497cb0f6c22d3ca" "" || (  	echo "Checking out files from the git repository..."; mkdir -p /home/jernin/lede/tmp/dl && cd /home/jernin/lede/tmp/dl && rm -rf libubox-2021-05-16-b14c4688 && [ \! -d libubox-2021-05-16-b14c4688 ] && git clone  https://git.openwrt.org/project/libubox.git libubox-2021-05-16-b14c4688 && (cd libubox-2021-05-16-b14c4688 && git checkout b14c4688612c05c78ce984d7bde633bce8703b1e && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd libubox-2021-05-16-b14c4688 && git log -1 --format='\''@%ct'\''` && rm -rf libubox-2021-05-16-b14c4688/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c libubox-2021-05-16-b14c4688 | 	xz -zc -7e > /home/jernin/lede/tmp/dl/libubox-2021-05-16-b14c4688.tar.xz && mv /home/jernin/lede/tmp/dl/libubox-2021-05-16-b14c4688.tar.xz /home/jernin/lede/dl/ && rm -rf libubox-2021-05-16-b14c4688;  )    '
rm -f /home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/.built
touch /home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/.built_check
MAKEFLAGS="" /home/jernin/lede/staging_dir/host/bin/ninja  -j1 -C /home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688 
ninja: Entering directory `/home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688'
[1/6] Building C object lua/CMakeFiles/uloop_lua.dir/uloop.c.o
FAILED: lua/CMakeFiles/uloop_lua.dir/uloop.c.o 
/home/jernin/lede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/bin/x86_64-openwrt-linux-musl-gcc -DJSONC -Duloop_lua_EXPORTS -I/home/jernin/lede/staging_dir/target-x86_64_musl/usr/include/json-c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688=libubox-2021-05-16-b14c4688 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/jernin/lede/staging_dir/target-x86_64_musl/usr/include -DNDEBUG -fPIC   -Wall -Werror -Wextra -Werror=implicit-function-declaration -Wformat -Werror=format-security -Werror=format-nonliteral -Os -std=gnu99 -g3 -Wmissing-declarations -Wno-unused-parameter -Os -Wall -Werror --std=gnu99 -g3 -I.. -MD -MT lua/CMakeFiles/uloop_lua.dir/uloop.c.o -MF lua/CMakeFiles/uloop_lua.dir/uloop.c.o.d -o lua/CMakeFiles/uloop_lua.dir/uloop.c.o -c /home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/lua/uloop.c
/home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/lua/uloop.c:21:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:113: /home/jernin/lede/build_dir/target-x86_64_musl/libubox-2021-05-16-b14c4688/.built] Error 1
make[3]: Leaving directory '/home/jernin/lede/package/libs/libubox'
time: package/libs/libubox/compile#0.18#0.09#0.30
    ERROR: package/libs/libubox failed to build.
make[2]: *** [package/Makefile:116: package/libs/libubox/compile] Error 1
make[2]: Leaving directory '/home/jernin/lede'
make[1]: *** [package/Makefile:110: /home/jernin/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jernin/lede'
make: *** [/home/jernin/lede/include/toplevel.mk:230：world] 错误

**Comment by WYC-2020** [comment]
自己问题，这要是炸了早就爆出来了，自己万能大法试
