### ISSUE TITLE
luci-app-store插件不能自动更新

### ISSUE THREAD

**Issue by HiJwm** [coolsnowwolf/lede#9312]
老大使用你的源码istore不能自动更新，点击更新无反应。使用另外一个Lieonl的源码编译luci-app-store可以自动更新。请老大排查以下，辛苦

**Comment by uclee888** [comment]
是lienol吧

**Comment by breakings** [comment]
这东西没任何意义 忽悠小白么

**Comment by HiJwm** [comment]
应用商店，建议有能力修复的大佬修复一下

**Comment by EnnawYang** [comment]
这东西没啥意义

**Comment by Myoko** [comment]
这玩意儿不就是KS的那个玩意儿吗！感觉没什么意义
