### ISSUE TITLE
containerd-1.5.11 hash value error

### ISSUE THREAD

**Issue by GreatMichaelLee** [coolsnowwolf/lede#9315]
Makefile里Hash值不对，导致编译出错

![image](https://user-images.githubusercontent.com/20067401/165231477-f3b723a2-95d2-4989-954b-c11419efaf7c.png)

![image](https://user-images.githubusercontent.com/20067401/165231606-d114e88c-af98-464f-b0c7-60d0ffb2bf36.png)

**Comment by breakings** [comment]
这值这两天有变动,自动手动改下也不难吧

**Comment by WYC-2020** [comment]
这种鬼玩意，搞毛了直接跳过hash

**Comment by GreatMichaelLee** [comment]
> 这种鬼玩意，搞毛了直接跳过hash

赞

**Comment by Wilson-coder** [comment]
> 这值这两天有变动,自动手动改下也不难吧

Report Bug，是开源社区赖以生存的基础。如果每个人遇到了问题都是自己默默修改代码自己用，或者单纯依赖开发者自己发现Bug，那就不用搞开源社区了。

**Comment by GreatMichaelLee** [comment]
> > 这值这两天有变动,自动手动改下也不难吧
> 
> Report Bug，是开源社区赖以生存的基础。如果每个人遇到了问题都是自己默默修改代码自己用，或者单纯依赖开发者自己发现Bug，那就不用搞开源社区了。

坐等一堆大佬来喷你，哈哈。估计他们又会说，你贡献了多少代码，你行你上之类的，所以我作为伸手党，大佬损我时我都只点赞的，哈哈哈。

**Comment by hong0980** [comment]
sed -i "s/\(PKG_HASH\|PKG_MD5SUM\|PKG_MIRROR_HASH\).*/\1:=skip/" feeds/packages/utils/containerd/Makefile
