### ISSUE TITLE
[Request] Update mtk-eip93 to final version.

### ISSUE THREAD

**Issue by Stkrx** [coolsnowwolf/lede#9318]
https://github.com/vschagen/mtk-eip93/tree/final

LEDE current stays at 12/2020 git commit, latest commit on final branch 10/2021.

**Comment by WYC-2020** [comment]
那个版本好像是直接内嵌到linux内核中，不是作为第三方包

**Comment by Stkrx** [comment]
Sorry :)

**Comment by WYC-2020** [comment]
> Sorry :)

看仓库我已经加入，你有胆子可以去测试一下
