### ISSUE TITLE
编译错误：eudev 3.2.10 下载 dl 库过不去

### ISSUE THREAD

**Issue by AstralHope** [coolsnowwolf/lede#9336]
## 1.关于你要提交的问题

Q：eudev 3.2.10 下载 dl 库过不去
* [x] 没有类似的issue

### (1) 具体问题

A：`make download -j8`报错，找到eudev的修改https://github.com/coolsnowwolf/lede/commit/3a2c790a9f83f455bc8639a2208d028456045a75 后退回`eudev 3.2.9`就过去了，手动下载3.2.10可以下载下来，hash校验也是对的，可能是什么原因导致的？

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：
```shell
 make[2] -C package/utils/mdadm download
 make[2] -C package/utils/util-linux download
    ERROR: package/qat/libs/eudev failed to build.
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download
```

**Comment by EnnawYang** [comment]
`Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on`

**Comment by AstralHope** [comment]
> `Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on`

试过好多次了，全清了重编译一样这样报错，版本退回去就能过

**Comment by WYC-2020** [comment]
又让人猜老火

**Comment by Licolnlee** [comment]
> 又让人猜老火

广西老表？
