### ISSUE TITLE
编译时，TroubleACC选择Include Shortcut-FE for ECM和选择Include Shortcut-FE有什么区别啊

### ISSUE THREAD

**Issue by Lixuhuilll** [coolsnowwolf/lede#9337]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by GreatMichaelLee** [comment]
谷歌了一下，貌似ECM是给自带ASIC芯片的路由用的（即能刷openwrt的硬路由，像小米那些）。也不知道是不是。供参考。

**Comment by minlang112** [comment]
> 谷歌了一下，貌似ECM是给自带ASIC芯片的路由用的（即能刷openwrt的硬路由，像小米那些）。也不知道是不是。供参考。

准确的说是给高通芯片的用的
