### ISSUE TITLE
ZTE E8820S 默认设置编译2.4g led灯不工作。

### ISSUE THREAD

**Issue by bauw2008** [coolsnowwolf/lede#9359]
## 1.关于你要提交的问题
中兴e8820s 默认设置编译后2.4g 灯不工作。

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
master分支默认设置编译能正常启动，无线工作正常，2.4g灯不能正常工作，LED 配置WiFi 2.4参数无效。看了下不知道是不是闭源驱动的原因。
另外platform.sh没添加e8820s，不能更新使用sysupgrade.bin。

### (2) 路由器型号和固件版本

型号 | ZTE E8820S
架构 | MediaTek MT7621 ver:1 eco:3 x 4
固件版本 | OpenWrt R22.4.1 / LuCI Master (git-22.121.65028-2a5da72)
内核版本 | 5.4.191

**Comment by WYC-2020** [comment]
@bauw2008  https://github.com/WYC-2020/lede/commit/3f4ed17091c2a17078f073a8d8a3de7cc77f2e64
测试看下

**Comment by bauw2008** [comment]
这个问题已经解决，是7603e闭源驱动控制的led灯，重新编译成功解决。

**Comment by WYC-2020** [comment]
> 这个问题已经解决，是7603e闭源驱动控制的led灯，重新编译成功解决。

那行，因为我看官方op有这个添加的pr参考那个搞的
