### ISSUE TITLE
k2p编译出错，看错误地方是在安装mtwifi插件出问题

### ISSUE THREAD

**Issue by Hess488** [coolsnowwolf/lede#9380]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
云编译出错，看错误地方是在安装mtwifi插件出问题
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如下面错误代码所示，看报错地方是安装mtwifi这个插件出问题了。luci-app-mtwifi这个插件应该是闭源驱动吧。除了选这个插件之外其他有关驱动的地方没动过，因为我看别人说最新版openwrt直接勾选mtwifi这个插件就是用闭源驱动了，不需要去MTK选项那里取消什么东西,求大佬指教一下怎么解决万分感谢

### (2) 路由器型号和固件版本

A：K2p路由器，ubuntu上编译最新的openwrt

### (3) 详细日志

A：Collected errors:
 * check_conflicts_for: The following packages conflict with mt_wifi:
 * check_conflicts_for: 	kmod-mt7615d_dbdc * 
 * opkg_install_cmd: Cannot install package mt_wifi.
 * check_conflicts_for: The following packages conflict with mt_wifi:
 * check_conflicts_for: 	kmod-mt7615d_dbdc * 
 * opkg_install_cmd: Cannot install package luci-app-mtwifi.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/heshusen/lede'
make[1]: *** [package/Makefile:111: /home/heshusen/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/heshusen/lede'
make: *** [/home/heshusen/lede/include/toplevel.mk:230：world] 错误 2

**Comment by EnnawYang** [comment]
您这是开源闭源一起上啊，不冲突就怪了

**Comment by AmadeusGhost** [comment]
按默认配置来就行，别选其它驱动。

**Comment by Hess488** [comment]
> 按默认配置来就行，别选其它驱动。

我在选了 luci-app-mtwifi插件的情况下把kmod-mt7615d_dbdc取消了就能正常编译了，但是我看那个地方还勾选了个kmod-mt7615d，需要把这个也取消勾选吗。kmod-mt7615d_dbdc跟kmod-mt7615d两者有啥区别吗，我想要的是闭源驱动

**Comment by Hess488** [comment]
我在选了 luci-app-mtwifi插件的情况下把kmod-mt7615d_dbdc取消了就能正常编译了，但是我看那个地方还勾选了个kmod-mt7615d，需要把这个也取消勾选吗。kmod-mt7615d_dbdc跟kmod-mt7615d两者有啥区别吗，我想要的是闭源驱动



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: AmadeusGhost ***@***.***&gt;
发送时间: 2022年5月10日 10:09
收件人: coolsnowwolf/lede ***@***.***&gt;
抄送: Hess488 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[coolsnowwolf/lede] k2p编译出错，看错误地方是在安装mtwifi插件出问题 (Issue #9380)





 
按默认配置来就行，别选其它驱动。
