### ISSUE TITLE
brcm2708_bcm2709编译错误

### ISSUE THREAD

**Issue by forsan-co** [coolsnowwolf/lede#939]
编译的设备是树莓派2b，尝试了几次，不知道是什么原因，下面是报错的内容：
SYNTAX: ./gen_rpi_sdcard_img.sh <file> <bootfs image> <rootfs image> <bootfs size> <rootfs size>
+ exit 1
Makefile:88: recipe for target '/home/forsan/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-brcm2708_bcm2709/tmp/openwrt-brcm2708-bcm2709-rpi-2-squashfs-factory.img.gz' failed
make[5]: *** [/home/forsan/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-brcm2708_bcm2709/tmp/openwrt-brcm2708-bcm2709-rpi-2-squashfs-factory.img.gz] Error 1
make[5]: Leaving directory '/home/forsan/lede/target/linux/brcm2708/image'
Makefile:34: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/forsan/lede/target/linux/brcm2708'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/forsan/lede/target/linux'
time: target/linux/install#41.15#5.51#39.70
target/Makefile:23: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/forsan/lede'
target/Makefile:19: recipe for target '/home/forsan/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_install' failed
make[1]: *** [/home/forsan/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/forsan/lede'
/home/forsan/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by lijun0326** [comment]
这个报错相当于没发
