### ISSUE TITLE
多wan口的端口转发

### ISSUE THREAD

**Issue by xjsolid** [coolsnowwolf/lede#9391]
我又多个wan口,都有公网IP; 我想将来自不同wan口的访问转发到本地局域网内.
但是端口转发的“外部区域” 处 只能选择 wan/vpn; 其他的wan口不显示,无法选择.

**Comment by GreatMichaelLee** [comment]
wan你可以在接口里选择自己想要的if做不同的bridge. 另外，你可以在防火墙里做SNAT细分流量

**Comment by xjsolid** [comment]
了解了 只要在防火墙基本设置里面 新建区域就行了, 谢谢!
