### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Jack-Ywn** [coolsnowwolf/lede#9392]
## 编译报错

执行`make download -j1 V=s `发现有明显报错内容

## 报错如下
time: target/linux/download#0.05#0.05#0.09
make[1]: Leaving directory '/home/yangwn/lede'
make[1]: Entering directory '/home/yangwn/lede'
make[1]: *** No rule to make target 'or'.  Stop.
make[1]: Leaving directory '/home/yangwn/lede'
make: *** [/home/yangwn/lede/include/toplevel.mk:230: or] Error 2

## 编译固件
x86_64

## 请问下这个报错需要怎么解决？

**Comment by Michaol** [comment]
估计梯子问题

**Comment by Alan996** [comment]
云编译也是报这个错误

**Comment by Jack-Ywn** [comment]
> 估计梯子问题

还真的是梯子的问题，换成了国外节点的虚拟机编译就成功了。3Q
