### ISSUE TITLE
刚刚git pull   5.10.115单线程老是编译不过

### ISSUE THREAD

**Issue by hgh188** [coolsnowwolf/lede#9410]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：
 CC      drivers/net/virtio_net.o
  CC      drivers/net/net_failover.o
  AR      drivers/net/built-in.a
  CC [M]  drivers/net/dummy.o
  CC [M]  drivers/net/ifb.o
  CC [M]  drivers/net/macvlan.o
  CC [M]  drivers/net/tun.o
  CC [M]  drivers/net/veth.o
  CC [M]  drivers/net/vxlan.o
  AR      drivers/firewire/built-in.a
  AR      drivers/cdrom/built-in.a
  CC [M]  drivers/cdrom/cdrom.o
  AR      drivers/auxdisplay/built-in.a
  CC      drivers/usb/phy/phy.o
  CC      drivers/usb/phy/of.o
  AR      drivers/usb/phy/built-in.a
  CC [M]  drivers/usb/phy/phy-generic.o
drivers/usb/phy/phy-generic.c: In function 'usb_phy_gen_create_phy':
drivers/usb/phy/phy-generic.c:271:19: error: implicit declaration of function 'devm_regulator_get_exclusive'; did you mean 'regulator_get_exclusive'? [-Werror=implicit-function-declaration]
  nop->vbus_draw = devm_regulator_get_exclusive(dev, "vbus");
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   regulator_get_exclusive
drivers/usb/phy/phy-generic.c:271:17: warning: assignment to 'struct regulator *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  nop->vbus_draw = devm_regulator_get_exclusive(dev, "vbus");
                 ^
cc1: some warnings being treated as errors
make[8]: *** [scripts/Makefile.build:280: drivers/usb/phy/phy-generic.o] Error 1
make[7]: *** [scripts/Makefile.build:497: drivers/usb/phy] Error 2
make[6]: *** [scripts/Makefile.build:497: drivers/usb] Error 2
make[5]: *** [Makefile:1822: drivers] Error 2
make[5]: Leaving directory '/home/a/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.115'
make[4]: *** [Makefile:21: /home/a/lede/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/linux-5.10.115/.modules] Error 2
make[4]: Leaving directory '/home/a/lede/target/linux/armvirt'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/a/lede/target/linux'
time: target/linux/compile#1564.69#224.20#1919.85
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/a/lede'
make[1]: *** [target/Makefile:18: /home/a/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/a/lede'
make: *** [/home/a/lede/include/toplevel.mk:230：world] 错误 2

**Comment by breakings** [comment]
https://github.com/openwrt/openwrt/commit/7400adae8d86dde3c60752bf66d487aa1b138bc1
