### ISSUE TITLE
R4S 能编译 5.15吗？

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#9417]
选5.4.x 运行没问题，换成5.15 luci就不正常，打不开管理页面。

**Comment by ohbaby30** [comment]
编译正常 使用正常

**Comment by gswangmd-gssi** [comment]
多次反复编译，只有5.4.x能正常运行！

**Comment by violarulan** [comment]
我这里 r4s 5.15 只要开 upnp 状态下，pppoe 重拨就会同时重启 br-lan 导致无法上网（br-lan 无法获取到 v6）
#9403
