### ISSUE TITLE
k2p刷sysuupgrade.bin启动不了，kernel.bin能进去后台，但升级固件时后台直接断开

### ISSUE THREAD

**Issue by JiaRZ** [coolsnowwolf/lede#9418]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：无论先kernel.bin再sysupgrade还是直接sysupgrade都是闪一下红灯然后长蓝，就是启动不了。。。进不了后台；斐讯模式刷kernel.bin能启动进后台，但是升级sysupgrade.bin时点击刷入固件就直接断开了后台连接，无法进入后续升级步骤

### (2) 路由器型号和固件版本

A：k2p最新版master分支

### (3) 详细日志

A：

**Comment by JiaRZ** [comment]
同样的编译，手头上的小米青春版直接刷sysupgrade就正常

**Comment by chobitsos** [comment]
有没一种可能，叫做 breed里的斐讯分区

**Comment by QGB** [comment]
> 有没一种可能，叫做 breed里的斐讯分区

就是刷breed变砖了，怎么办
