### ISSUE TITLE
增加istore之后编译报错，提示缺少ipkg

### ISSUE THREAD

**Issue by GHLiuyb** [coolsnowwolf/lede#9424]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
增加了istore之后编译报错，提示缺少ipkg
### (1) 具体问题

A：添加了https://github.com/linkease/istore

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：
![error](https://user-images.githubusercontent.com/86706862/169695809-ba7ab2e8-4aed-4a54-84ab-8f4dc5eec6ed.jpg)

**Comment by LPDDR6-10000MHz** [comment]
他们插件需要依赖luci-app-ipke，在luci 22.02上才有，如果你这么坚用lede，那就把插件luci-app-ipke打掉可以了

**Comment by GHLiuyb** [comment]
> 他们插件需要依赖luci-app-ipke，在luci 22.02上才有，如果你这么坚用lede，那就把插件的依赖luci-app-ipke打掉可以了

好的，谢谢
