### ISSUE TITLE
请大佬帮忙给硬件适配支持犀牛R68s硬件

### ISSUE THREAD

**Issue by uosX** [coolsnowwolf/lede#9428]
**1.硬件适配支持犀牛R68s硬件**

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

 2. 详细叙述

(1) 具体问题

A：硬件适配支持犀牛R68s硬件

 (2) 路由器型号和固件版本

**R68s 配置列表**
SOC RK3568
内存 LPDDR4 2GB/4GB
硬盘 EMMC 16GB
网口
1G *2 （RTL8211F-CG）
2.5G *2 （RTL8125BG-CG）
接口 USB 3.0 *2
DC 12V-1.5A 5.5mm*2.1mm

 (3) 详细日志

**Comment by AmadeusGhost** [comment]
不是已经适配了？🙄
![de322d54ccd23cf547e690e599cf43c5.jpeg](https://user-images.githubusercontent.com/42570690/169766387-8214b235-1180-46ff-b13d-012e6695776a.jpeg)

**Comment by programmejava** [comment]
他说的是   这是友善的r5s   刚发布

**Comment by uniessey** [comment]
电犀牛不是自称L大亲自操刀的吗？还需要适配？

**Comment by minlang112** [comment]
适配（指用一个可以瞎跑起来的内核强行配上rootfs不管他有多少报错）

**Comment by Neverends4** [comment]
acwifi测了这机子小包转发速率，结果很迷还不如J1900……
估计也是厂商发过去测的，感觉是搬起石头砸自己脚XD
