### ISSUE TITLE
使用测试内核版本编译失败报错

### ISSUE THREAD

**Issue by gevikhn** [coolsnowwolf/lede#9431]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
编译失败，r8152报错
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在配置文件中勾选“Use the testing kernel version”后，编译失败

### (2) 路由器型号和固件版本

A：树莓派4b，R22.5.5

### (3) 详细日志

A：
Applying /home/nanami/lede/target/linux/bcm27xx/patches-5.10/950-0541-rpivid-Switch-to-new-clock-api.patch using plaintext: 
patching file drivers/staging/media/rpivid/rpivid.h
patching file drivers/staging/media/rpivid/rpivid_video.c

Applying /home/nanami/lede/target/linux/bcm27xx/patches-5.10/950-0542-net-usb-r8152-Provide-missing-documentation-for-some.patch using plaintext: 
patching file drivers/net/usb/r8152.c
Hunk #1 FAILED at 898.
Hunk #2 FAILED at 911.
Hunk #3 FAILED at 936.
Hunk #4 FAILED at 950.
Hunk #5 FAILED at 960.
5 out of 5 hunks FAILED -- saving rejects to file drivers/net/usb/r8152.c.rej
Patch failed!  Please fix /home/nanami/lede/target/linux/bcm27xx/patches-5.10/950-0542-net-usb-r8152-Provide-missing-documentation-for-some.patch!
make[4]: *** [Makefile:44: /home/nanami/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/linux-5.10.117/.prepared_bd83ddbaa9cc57d8bee3cf0be74f85d9] Error 1
make[4]: Leaving directory '/home/nanami/lede/target/linux/bcm27xx'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/nanami/lede/target/linux'
time: target/linux/compile#17.86#9.86#23.39
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/nanami/lede'
make[1]: *** [target/Makefile:18: /home/nanami/lede/staging_dir/target-aarch64_cortex-a72_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/nanami/lede'
make: *** [/home/nanami/lede/include/toplevel.mk:230: world] Error 2

**Comment by zhangguanzhang** [comment]
这个patch错误导致的看样子
```
Patch failed! Please fix /home/nanami/lede/target/linux/bcm27xx/patches-5.10/950-0542-net-usb-r8152-Provide-missing-documentation-for-some.patch!
```
