### ISSUE TITLE
r4s 4g 编译成功，但刷上机，机器system灯不亮，系统也没有正常

### ISSUE THREAD

**Issue by willisworley** [coolsnowwolf/lede#9432]
路由器型号和固件版本

r4s 4g

记得以前编译的时候可以选1G版本，4G版本。现在编译出来的镜像不能正常亮机啊

**Comment by gswangmd-gssi** [comment]
我也一样，r4s 4g, 在这里提问几次都没人回答。

**Comment by Ding-Kyoma** [comment]
以前没试过，现在5.15.49没什么问题 ，R4S 4G （mac阉割版）
![截屏2022-06-24 22 22 37](https://user-images.githubusercontent.com/44542198/175570057-2521a8c0-8bbb-4488-91f5-8e4a352b91d1.png)

**Comment by adamgonglj** [comment]
我也是，R4S，lan口和wan不亮
