### ISSUE TITLE
passwall更新订阅后，HAProxy负载均衡再也打不开，重启无效

### ISSUE THREAD

**Issue by RivieraS** [coolsnowwolf/lede#9436]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：passwall,手工更新订阅后，HAProxy负载均衡线路超时，再看看负载均衡页面，进入界面按键消失，虽然可以开关，但运行状态里面，负载均衡都显示未运行。而且重启无效，最后重装了op

（线路没问题）

### (2) 路由器型号和固件版本

A：esxi6.7u3 虚拟op R22.5.5

### (3) 详细日志

A：

**Comment by d975xbx** [comment]
passwall这个东西不是这里。人家都不愿回复你。
