### ISSUE TITLE
老大能否更新mtk7621的hwnat硬件加速

### ISSUE THREAD

**Issue by lwb1978** [coolsnowwolf/lede#9441]
mtk开源了新的hwnat和有线驱动，有网友测试效果明显，老大能否抽空跟进？谢谢。

**Comment by siyu0** [comment]
支持，目前7621的hwnat太残废了。

**Comment by nanchuci** [comment]
不要着急，才出来，会有的！现目前相对说改动太大，还不能兼顾到各个机型！

**Comment by chobitsos** [comment]
> mtk开源了新的hwnat和有线驱动，有网友测试效果明显，老大能否抽空跟进？谢谢。

在guyhub这里吗？

**Comment by uniessey** [comment]
> > mtk开源了新的hwnat和有线驱动，有网友测试效果明显，老大能否抽空跟进？谢谢。
> 
> 在guyhub这里吗？ 话说之前不是搞过一次吗？#5123

我猜测他说的可能是这个：https://forum.openwrt.org/t/use-mtk-sdk-hwnat-driver-to-replace-hw-flow-offload/128120

**Comment by lwb1978** [comment]
> > > mtk开源了新的hwnat和有线驱动，有网友测试效果明显，老大能否抽空跟进？谢谢。
> > 
> > 
> > 在guyhub这里吗？ 话说之前不是搞过一次吗？#5123
> 
> 我猜测他说的可能是这个：https://forum.openwrt.org/t/use-mtk-sdk-hwnat-driver-to-replace-hw-flow-offload/128120

恩山论坛的链接在这：https://www.right.com.cn/forum/thread-8235037-1-1.html

**Comment by liwenjie119** [comment]
期待优化后的新驱动可用

**Comment by ttmi9002** [comment]
有了这个驱动，MTK7621又能再战三年。现在用R3G组网就是HWNAT不稳定无线速度只能跑到300M，新驱动有望提升到500M

**Comment by AmadeusGhost** [comment]
在做了，别急
![-5263b29bb8113129.png](https://user-images.githubusercontent.com/42570690/170533731-abcdaa70-8a56-46d2-b040-9123737c5339.png)

**Comment by chobitsos** [comment]
> 在做了，别急
> ![-5263b29bb8113129.png](https://user-images.githubusercontent.com/42570690/170533731-abcdaa70-8a56-46d2-b040-9123737c5339.png)

大佬，顺便把mt7260的也加上哈

**Comment by 286700234** [comment]
期待做完了之后的效果怎么样
