### ISSUE TITLE
为什么用SSR，怎么很多软件都访问被拒绝了

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#9444]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
小米4
A：

### (3) 详细日志

刚刚编译了小米4的固件 用着SSR，用淘宝软件，怎么 提示  亲，访问被拒绝，  请检查什么是否使用了代理软件，这个怎么解决啊？

**Comment by shu0802** [comment]
> 反馈bug/问题模板，提建议请删除
> 
> ## 1.关于你要提交的问题
> Q：是否搜索了issue (使用 "x" 选择)
> 
> * [ ]  没有类似的issue
> 
> ## 2. 详细叙述
> ### (1) 具体问题
> A：
> 
> ### (2) 路由器型号和固件版本
> 小米4 A：
> 
> ### (3) 详细日志
> 刚刚编译了小米4的固件 用着SSR，用淘宝软件，怎么 提示 亲，访问被拒绝， 请检查什么是否使用了代理软件，这个怎么解决啊？

设置了代理了吧
