### ISSUE TITLE
x86 generic, 显示 random: crng init done后卡住

### ISSUE THREAD

**Issue by rainchensh** [coolsnowwolf/lede#9451]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
openwrt img版本：r4532-95b3b801e; 直接安装于华硕 A2400笔记本；开机启动失败，无法进入系统。但使用openwrt官方X86固件没有问题

### (1) 具体问题

A：开机启动后到屏幕显示random: crng init done就卡住，按键盘触摸板无反应，无法进入系统命令提示符界面; ssh也连接不上，但插上U盘会显示识别到U盘插入。

### (2) 路由器型号和固件版本

A：固件openwrt-x86-generic-generic-ext4-combined-efi.img版本：r4532-95b3b801e; 直接安装于华硕 A2400笔记本;此机外部接口较多，除常见接口外还有PC卡插槽（PCMCIA）

### (3) 详细日志

A：开机失败，未能获取。

**Comment by wjz304** [comment]
俺也一样

**Comment by rainchensh** [comment]
解决了。是rootfs目录没能加载，原因是grub启动目录里 root的 partuuid填错了。

**Comment by likevkin** [comment]
怎么解决？

**Comment by rainchensh** [comment]
抱歉不记得了。大概是引导程序的位置填错了。













在 2024-12-02 21:09:37，"likevkin" ***@***.***> 写道：

怎么解决？
