### ISSUE TITLE
revert -n edbd8d2e9839357f3a4f0a06174d243f362b1544失败

### ISSUE THREAD

**Issue by cfj521** [coolsnowwolf/lede#9455]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
revert -n edbd8d2e9839357f3a4f0a06174d243f362b1544失败

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
revert -n edbd8d2e9839357f3a4f0a06174d243f362b1544失败
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
xiaomi ax6
最新source revert到edbd8d2e9839357f3a4f0a06174d243f362b1544版本时失败
A：

### (3) 详细日志
 git revert -n edbd8d2e9839357f3a4f0a06174d243f362b1544
Auto-merging target/linux/ipq807x/patches-5.10/900-arm64-dts-add-OpenWrt-DTS-files.patch
CONFLICT (content): Merge conflict in target/linux/ipq807x/patches-5.10/900-arm64-dts-add-OpenWrt-DTS-files.patch
Auto-merging target/linux/ipq807x/image/generic.mk
Auto-merging target/linux/ipq807x/base-files/lib/upgrade/platform.sh
Auto-merging target/linux/ipq807x/base-files/etc/hotplug.d/firmware/11-ath11k-caldata
Auto-merging target/linux/ipq807x/base-files/etc/board.d/02_network
Auto-merging package/firmware/ipq-wifi/Makefile
error: could not revert edbd8d2e9... ipq807x: drop all xiaomi devices support
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'

**Comment by AmadeusGhost** [comment]
![0](https://user-images.githubusercontent.com/42570690/171032360-d852106b-0335-4f3a-bf8a-4344207d7aef.png)
认字吗？
