### ISSUE TITLE
编译package/index出现警告

### ISSUE THREAD

**Issue by qqsir-dev** [coolsnowwolf/lede#9459]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
 make[2] -C package/community/luci-app-unblockneteasemusic compile
 make[1] package/index
WARNING: Applying padding in /home/runner/work/AutoLede/AutoLede/openwrt/bin/packages/x86_64/packages/Packages to workaround usign SHA-512 bug!
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：软路由，云编译，重新编译依旧提示，但不影响编译成功，不知道是什么意思

### (3) 详细日志

A：

**Comment by IDeLoveYou** [comment]
所以这是为什么呢
