### ISSUE TITLE
编译的mt7620 youku 的固件不完整

### ISSUE THREAD

**Issue by daka2017** [coolsnowwolf/lede#946]
编译生成的文件为什么只有update文件，却没有factory文件

**Comment by asushugo** [comment]
是不是固件太大了，没生成？

**Comment by a1768623020** [comment]
我感觉也像，我编译的文件过大也只会生成initramfs-kernel，不会生成sysupgrade，检查一下是不是太大了吧

**Comment by royalwei** [comment]
固件太大了
