### ISSUE TITLE
大佬们，最新源码好像又出现之前拨号重启的情况？

### ISSUE THREAD

**Issue by mitsukileung** [coolsnowwolf/lede#9462]
X86
最新源码好像又出现之前拨号重启的情况？

**Comment by makebl** [comment]
保留配置无限重启

**Comment by XiaoliChan** [comment]
一样情况

**Comment by Paris0-0** [comment]
一样一样

**Comment by XiaoliChan** [comment]
Turbo Acc 切换到 SFE，问题解决

**Comment by mumuou** [comment]
5.15保留配置升级翻车了，无限重启。

**Comment by realJustinLee** [comment]
<img width="1024" alt="Screen Shot 2022-06-01 at 21 49 39" src="https://user-images.githubusercontent.com/17794470/171424035-812a3bc5-3760-4c59-b5cf-7ddb0f43e2cf.png">

**Comment by rongcenter** [comment]
或者用41,41的核没问题

**Comment by jwkinko** [comment]
还跟turbo acc有关系？

**Comment by uniessey** [comment]
我隐约记得，之前提过如果使用新的闭源驱动，需要关闭ACC，不知道是不是和这个有关系，新的闭源驱动性能还不错。

**Comment by rongcenter** [comment]
已经修复了，快去编

**Comment by realJustinLee** [comment]
fixe in 2a33e979c850c9bf214e6713a9e39ada029e2381
