### ISSUE TITLE
r4s每天4天准时关机(cpumark导致)

### ISSUE THREAD

**Issue by capxax** [coolsnowwolf/lede#9468]
如题
手动运行cpumark也会死机
不知道是温度过高的原因还是固件
以前的固件没事
我两周前新刷的固件 会出现这个问题

**Comment by GreatMichaelLee** [comment]
删除/etc/crontab/root里面的有cpumark.sh那一行4点的定时任务就完事，这玩意就是个坑爹货，我以前也遇到了，直接删了解决

**Comment by hxlls** [comment]
coremark跑重启或者死机，证明你的设备在高强度上运行不稳定，降频或者改善散热把

**Comment by 467815891a** [comment]
我的r2s之前也是凌晨突然就宕机了，每天早上起来ping不到。打开弱电箱门之后，这两天就没这个问题了。
但是我的/etc/crontab/root里面没有定时cpumark这一条。

**Comment by uosX** [comment]
我开着空调16度，自带铝合金被动散热外壳，5v4a电源，编译了Lede固件跑coremark都会自动掉电死机；
我觉得要么主板问题，要么固件问题，

**Comment by capxax** [comment]
> 我开着空调16度，自带铝合金被动散热外壳，5v4a电源，编译了Lede固件跑coremark都会自动掉电死机；
> 我觉得要么主板问题，要么固件问题，

应该是固件 半年前点固件没这问题

**Comment by Ding-Kyoma** [comment]
很有可能编译的时候，coremark 默认是32线程导致需要跑很长时间，因为r4s只有6个核心！在`make menuconfig -- Utilities`，把`coremark -- Number of threads`调成6，编译出来的coremark可以跑的更加稳定，分数更高，时间更短。
