### ISSUE TITLE
建议：qbit可否换为增强版？

### ISSUE THREAD

**Issue by liwenjie119** [coolsnowwolf/lede#9473]
https://github.com/c0re100/qBittorrent-Enhanced-Edition
这个增强版star和fork的也挺多，不知道能否替换

**Comment by minlang112** [comment]
该版本似乎PT站点均不可用，没必要换吧

**Comment by ricksuzade-maker** [comment]
这个所谓增强版很多pt站都用不起的，没必要换，也没有实质性能提升
