### ISSUE TITLE
cr660x ramips7621 刷最新5.10源码编译的出现有线lan电脑无法访问web192管理页面

### ISSUE THREAD

**Issue by ayancn** [coolsnowwolf/lede#9475]
cr660x ramips7621 刷最新5.10源码编译的出现有线lan电脑无法访问web192管理页面  源码  kernel: bump 5.10 to 5.10.117 R2.2.5.5
WIFI就是正常

**Comment by nanchuci** [comment]
听说干掉交换机就可以了，再听说你这issue马上要被干掉了！😂

**Comment by AmadeusGhost** [comment]
换回 5.4 即可，要不就别用。

**Comment by ayancn** [comment]
> 换回 5.4 即可，要不就别用。

是目前5.10的问题? 换回5.4确定正常吗

**Comment by ayancn** [comment]
> 听说干掉交换机就可以了，再听说你这issue马上要被干掉了！😂

没加交换机,直接电脑LAN连接路由器LAN口, 为啥要干掉 😂

**Comment by LINGJP** [comment]
> 

他指的是switch......

**Comment by ayancn** [comment]
> > 换回 5.4 即可，要不就别用。
> 
> 是目前5.10的问题? 换回5.4确定正常吗

换最新的5.4也是同样问题没用
