### ISSUE TITLE
> > xiaomi redmi ac2100编译linux内核时报错,日志如下

### ISSUE THREAD

**Issue by crg1433** [coolsnowwolf/lede#9479]
> > xiaomi redmi ac2100编译linux内核时报错,日志如下
> > ERROR: "nd_tbl" [drivers/net/ethernet/mtk/mtk_hnat/mtkhnat.ko]
> 
> 代码里面并没有这个 nd_tbl，所以我也不知道发生了什么

我去build_dir相应的目录中,根本就没有mtkhnat.ko ,系统是archlinux,ubuntu应该也有同样的问题,我去试试

_Originally posted by @lovehackintosh in https://github.com/coolsnowwolf/lede/issues/9450#issuecomment-1146571192_

**Comment by crg1433** [comment]
我编译完成了redmi ac2100   ,链接: https://pan.baidu.com/s/1rs4cYFbGN6mx8dvgg8dFJA?pwd=mn6n 提取码: mn6n 复制这段内容后打开百度网盘手机App，操作更方便哦,但是无线有问题，有空你试试，提供下日志。我上次快速刷别的去了。

**Comment by lovehackintosh** [comment]
谢谢

在 2022年6月4日星期六，crg1433 ***@***.***> 写道：
