### ISSUE TITLE
v2ray : x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by wwng2333** [coolsnowwolf/lede#948]
2018/12/25 12:07:30 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://*.*.*/downloads/):  > x509: certificate signed by unknown authority] > v2ray.com/core/common/retry: all retry attempts failed

在PC上一切正常，怀疑缺少根证书

附上证书链：
![image](https://user-images.githubusercontent.com/17147265/50422071-413f9480-0881-11e9-8f3b-9f33f57387f2.png)

**Comment by matthew728960** [comment]
试试打开 "允许不安全的证书" 选项

**Comment by wwng2333** [comment]
80d6d03b49273bec16a0da30141b85e0debfffd2
