### ISSUE TITLE
编译出的固件ax6s无法使用

### ISSUE THREAD

**Issue by LGinC** [coolsnowwolf/lede#9487]
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译出来的固件刷进去会变砖

### (2) 路由器型号和固件版本

A：红米AX6S R22.5

### (3) 详细日志

A：无
橙灯一闪一闪，无限重启，无wifi 无ip， 最后通过MIWIFIRepairTool.x86才救回来

经搜索发现好像ax6s的需要进行patch

**Comment by LGinC** [comment]
@librec  5.10内核...，你可以从软件包里下载安装软件吗, 软件包里的好像很多都是基于5.15的

**Comment by hcym** [comment]
用官方吧，master和2203都正常，大雕这个魔改太多，除了x86，容易引起不适症状

**Comment by librec** [comment]
> @librec 5.10 内核...，你可以从软件包里下载安装软件吗，软件包里的好像很多都是基于 5.15 的

不可以，我习惯手动编译，你这样的需求建议官方。
