### ISSUE TITLE
各个平台编译教程及踩坑记录

### ISSUE THREAD

**Issue by palemoky** [coolsnowwolf/lede#9489]
端午节耗时三天，从 MacBook Pro 到 Windows11，从 WSL 到虚拟机，再到 Ubuntu 22.04，都编译了一遍，期间踩了不少坑，做了如下的总结，希望能对大家有所帮助

https://palemoky.notion.site/OpenWrt-b758ea53bc824c74bb09d1b90e600e5b

感谢 L 大的开源项目！

**Comment by ihuaer** [comment]
感谢分享

**Comment by fengqi** [comment]
很好的内容，但是这种分享没必要提个issue吧，issue是用来反馈bug的，建议自行关闭。

**Comment by palemoky** [comment]
> 很好的内容，但是这种分享没必要提个 issue 吧，issue 是用来反馈 bug 的，建议自行关闭。

已关闭
