### ISSUE TITLE
是不是最近新固件取消了I210网卡驱动的支持！

### ISSUE THREAD

**Issue by makebl** [coolsnowwolf/lede#9491]
是不是最近新固件取消了I210网卡驱动的支持！
不识别i210网卡，选择添加驱动也没看到i210的驱动

**Comment by WYC-2020** [comment]
igb

**Comment by makebl** [comment]
选择了igb  lspci可以看到网卡但是没有驱动

**Comment by makebl** [comment]
5月21号的时候版本还没问题 5月30号的时候在编译就这样了
