### ISSUE TITLE
防火墙打开端口转发后，v2ray疯狂报错，转发失败，v2日志几分钟就670M

### ISSUE THREAD

**Issue by honnbin** [coolsnowwolf/lede#950]
版本：OpenWrt R8.1.12 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
内核：4.9.146
硬件：J1900+4G+32G SSD
问题：系统打开了upnp，SFE 加速状态，FULLCONE NAT加速，
ShadowSocksR Plus+ 使用的v2ray服务器，v2ray tcp其他未做任何加密
防火墙打开端口转发20-21，8901-9020，9021给ftp使用，未打开ShadowSocksR Plus+ 一切正常，打开之后，端口转发失效，v2ray日志疯狂增长，3分钟达到670M，全部内容都是2018/12/27 07:53:54 [Warning] v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1234: accept4: too many open files，全部相同的报错500万条

**Comment by honnbin** [comment]
ShadowSocksR Plus+ 使用ssr的话，也是正常的，不会触发bug

**Comment by honnbin** [comment]
应当是8900-9020的某个端口和v2ray自带的冲突了，换了ip范围之后就解决了

**Comment by xlighting2017** [comment]
vsftpd.conf 里面可以控制 PASV模式使用的端口

pasv_max_port
The maximum port to allocate for PASV style data connections. Can be used to specify a narrow port range to assist firewalling.
Default: 0 (use any port)

pasv_min_port
The minimum port to allocate for PASV style data connections. Can be used to specify a narrow port range to assist firewalling.
Default: 0 (use any port)

https://linux.die.net/man/5/vsftpd.conf

**Comment by lan542662** [comment]
被你这么一说，好雷人。疯狂报错

**Comment by hcym** [comment]
刚刚编译时直接把日志选项none，我部署服务端都是这样，反正也不懂不看

**Comment by honnbin** [comment]
新版默认取消了v2日志写入，目前测试一天多正常了，旧版我用v2ray pro也测试没问题，估计就是ssplus+ v2ray日志写入的锅，v2ray报连接数过多，日志就疯狂写入。
ftp我用的是filezilla server 0.9.60.2
