### ISSUE TITLE
使用sagernet core替换v2ray xray的问题。

### ISSUE THREAD

**Issue by harleywong** [coolsnowwolf/lede#9500]
在使用sagernet core替换v2ray xray之后，因为固件里面没有了这两个核心，luci-app-v2ray-server缺少了核心，无法使用了。
![image](https://user-images.githubusercontent.com/34861262/172527198-f9bb2b14-5d5d-46ca-a03c-3a7037c20ad5.png)

**Comment by WYC-2020** [comment]
等会看下

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/172571458-7bfe2d89-aca9-4b35-aea2-0f16a102f6c9.png)
![image](https://user-images.githubusercontent.com/34025388/172571481-073a49f7-1ca9-4432-a362-248c97b6b6e2.png)
![image](https://user-images.githubusercontent.com/34025388/172571496-3b0fcff3-10ce-4dc6-b20a-37e2b176ae5f.png)
简单修复了一下其他没看，没时间，测试运行没问题，功能自测 @harleywong

**Comment by WYC-2020** [comment]
几万年的老东西 居然还在用

**Comment by Jason6111** [comment]
你点MANUALLY UPDATE试试 没看见版本号

**Comment by harleywong** [comment]
> 几万年的老东西 居然还在用

感谢，刚刚试了下，可以了！
主要是ssp自带的服务端没有v2相关的配置，在家里路由上开个服务端，公司用个路由器开ssp可以连回家里访问局域网，也不耽误使用公司的局域网。比其他纯vpn软件要方便点。
![image](https://user-images.githubusercontent.com/34861262/172627563-e84aedc7-33fe-41c7-a278-768c064461bd.png)

**Comment by harleywong** [comment]
> 你点MANUALLY UPDATE试试 没看见版本号

根据大佬修改编译后可以了。
