### ISSUE TITLE
luci-app-netdata建议加上中文版

### ISSUE THREAD

**Issue by shu0802** [coolsnowwolf/lede#9515]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：luci-app-netdata中文版加入
![image](https://user-images.githubusercontent.com/43750373/173179217-a22fd7ea-03ee-4b04-9653-2139ecaf71a1.png)

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：

**Comment by Jason6111** [comment]
自己找下有补丁跟用法的 我做过部分汉化
![9D466B56-3621-47D3-BD4C-03613EA322E8](https://user-images.githubusercontent.com/43496459/173186196-d6c85bf1-da88-4455-8880-d9798138d094.jpeg)

**Comment by shu0802** [comment]
> 自己找下有补丁跟用法的 我做过部分汉化 ![9D466B56-3621-47D3-BD4C-03613EA322E8](https://user-images.githubusercontent.com/43496459/173186196-d6c85bf1-da88-4455-8880-d9798138d094.jpeg)

https://github.com/sirpdboy/sirpdboy-package/tree/main/luci-app-netdata 这里有已经汉化好的，我没办法把它折腾到openwrt里面来。

**Comment by suizhenmin** [comment]
> > 自己找下有补丁跟用法的 我做过部分汉化 ![9D466B56-3621-47D3-BD4C-03613EA322E8](https://user-images.githubusercontent.com/43496459/173186196-d6c85bf1-da88-4455-8880-d9798138d094.jpeg)
> 
> https://github.com/sirpdboy/sirpdboy-package/tree/main/luci-app-netdata 这里有已经汉化好的，我没办法把它折腾到openwrt里面来。

这个汉化的很完整，而且也比网上繁体汉化的更准确，希望大神能整合进来

**Comment by shu0802** [comment]
今天早上发现汉化成功了。
![image](https://user-images.githubusercontent.com/43750373/173209520-afd7d77f-1db8-416c-a720-0be18d2e6d47.png)
![image](https://user-images.githubusercontent.com/43750373/173209544-d9f39370-b6d8-4b30-a552-d622055a2b12.png)
