### ISSUE TITLE
make[1]: *** [/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2

### ISSUE THREAD

**Issue by zhiwen1987** [coolsnowwolf/lede#9551]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志
make[8]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools/m4'
make[7]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools/m4'
make[7]: Entering directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools'
make[8]: Entering directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools'
make[8]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/bl/lede/staging_dir/hostpkg/share/doc/gettext/examples/build-aux'
 /bin/mkdir -p '/home/bl/lede/staging_dir/hostpkg/share/gettext'
 /home/bl/lede/staging_dir/host/bin/install -c -m 644 ../build-aux/javacomp.sh.in ../build-aux/javaexec.sh.in ../build-aux/csharpcomp.sh.in ../build-aux/csharpexec.sh.in '/home/bl/lede/staging_dir/hostpkg/share/doc/gettext/examples/build-aux'
 /home/bl/lede/staging_dir/host/bin/install -c ../build-aux/config.rpath '/home/bl/lede/staging_dir/hostpkg/share/gettext'
make[8]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools'
make[7]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools'
make[6]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21/gettext-tools'
make[6]: Entering directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
make[7]: Entering directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
make[7]: Nothing to be done for 'install-exec-am'.
make[7]: Nothing to be done for 'install-data-am'.
make[7]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
make[6]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
make[5]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
make[4]: Leaving directory '/home/bl/lede/build_dir/hostpkg/gettext-0.21'
mkdir -p /home/bl/lede/staging_dir/hostpkg/stamp
touch /home/bl/lede/build_dir/hostpkg/gettext-0.21/.built
touch /home/bl/lede/staging_dir/hostpkg/stamp/.gettext-full_installed
make[3]: Leaving directory '/home/bl/lede/package/libs/gettext-full'
time: package/libs/gettext-full/host-compile#473.08#112.40#591.72
make[2]: Leaving directory '/home/bl/lede'
package/Makefile:110: recipe for target '/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/lede'

A：

**Comment by WYC-2020** [comment]
单线程日志？如果是 那你这个日志没贴到关键位置
