### ISSUE TITLE
今天（12.28）源码编译的固件新三无法启动

### ISSUE THREAD

**Issue by zocs** [coolsnowwolf/lede#956]
newifi d2默认配置编译，修改luci app的配置都编译刷入过，一直不停重启，无法正常启动，
还有群友测试小米mini有同样的问题，恩山也有部分人出现同样的问题
https://www.right.com.cn/forum/thread-389189-1-1.html

**Comment by zocs** [comment]
Ubuntu 18.04.1 LTS，10月14日的breed

**Comment by coolsnowwolf** [comment]
可以启动
