### ISSUE TITLE
云编译出错 红色* Delete workflow runs

### ISSUE THREAD

**Issue by sonytxl** [coolsnowwolf/lede#9578]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：红色* Delete workflow runs

之前一直都正常编译，今天忽然变成这样，其他地方都没有变动过，到数第第三行出错，其它正常，请问各位有遇到同样情况的吗？怎么处理的？谢谢。。

### (2) 路由器型号和固件版本

A：xiaomi3G

### (3) 详细日志

A：
 红色X Delete workflow runs

1    Run GitRML/delete-workflow-runs@main
2     with:
3          retain_days: 1
4          keep_minimum_runs: 3
5          token: ***
6          repository: sonytxl/xiaomiR3G-1
7     env:
8           REPO_URL: https://github.com/coolsnowwolf/lede
9           REPO_BRANCH: master
10         FEEDS_CONF: feeds.conf.default
11         CONFIG_FILE: .config
12         DIY_P1_SH: diy-part1.sh
13         DIY_P2_SH: diy-part2.sh
14         UPLOAD_BIN_DIR: false
15         UPLOAD_FIRMWARE: true
16         UPLOAD_COWTRANSFER: false
17         UPLOAD_WETRANSFER: false
18         UPLOAD_RELEASE: false
19         TZ: Asia/Shanghai
20        DEVICE_NAME: _xiaomi_mi-router-3g
21         FILE_DATE: _202206151255
22         FIRMWARE: /home/runner/work/xiaomiR3G-1/xiaomiR3G-1/openwrt/bin/targets/ramips/mt7621
23 
23    Error: Resource not accessible by integration

之前一直都正常编译，今天忽然变成这样，其他地方都没有变动过，到数第第三行出错，其它正常，请问各位有遇到同样情况的吗？怎么处理的？谢谢。。

**Comment by dfldylan** [comment]
怎么解决的？
