### ISSUE TITLE
R2s默认配置编译报错

### ISSUE THREAD

**Issue by FantasticSkyBaby** [coolsnowwolf/lede#9585]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
[ x ] 没有类似的issue

## 2. 详细叙述
初始化步骤后选择r2s编译，其他不动，在Mac和ubuntu均编译失败报同样错误

### (1) 具体问题

A：
make[3]: Leaving directory '/home/mark/lede/package/utils/e2fsprogs'
time: package/utils/e2fsprogs/compile#36.87#7.53#18.65
make[2]: Leaving directory '/home/mark/lede'
make[1]: *** [package/Makefile:110: /home/mark/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mark/lede'
make: *** [/home/mark/lede/include/toplevel.mk:230: world] Error 2

### (2) 路由器型号和固件版本

A：友善R2s

### (3) 详细日志

A：
echo '2' | cmp -s - /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libss.version || { echo '2' > /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libss.version;  }
SHELL= flock /home/mark/lede/tmp/.root-copy.flock -c 'cp -fpR /home/mark/lede/build_dir/target-aarch64_generic_musl/e2fsprogs-1.46.5/.pkgdir/libss/. /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.libss_installed
echo "libss" >> /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/e2fsprogs.default.install
mkdir -p /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
echo '2' | cmp -s - /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libext2fs.version || { echo '2' > /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libext2fs.version;  }
SHELL= flock /home/mark/lede/tmp/.root-copy.flock -c 'cp -fpR /home/mark/lede/build_dir/target-aarch64_generic_musl/e2fsprogs-1.46.5/.pkgdir/libext2fs/. /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.libext2fs_installed
echo "libext2fs" >> /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/e2fsprogs.default.install
mkdir -p /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/mark/lede/tmp/.root-copy.flock -c 'cp -fpR /home/mark/lede/build_dir/target-aarch64_generic_musl/e2fsprogs-1.46.5/.pkgdir/e2fsprogs/. /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/mark/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.e2fsprogs_installed
echo "e2fsprogs" >> /home/mark/lede/staging_dir/target-aarch64_generic_musl/pkginfo/e2fsprogs.default.install
make[3]: Leaving directory '/home/mark/lede/package/utils/e2fsprogs'
time: package/utils/e2fsprogs/compile#36.87#7.53#18.65
make[2]: Leaving directory '/home/mark/lede'
make[1]: *** [package/Makefile:110: /home/mark/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mark/lede'
make: *** [/home/mark/lede/include/toplevel.mk:230: world] Error 2
mark@Mark‘s-PC:~/lede$

**Comment by yanxin152133** [comment]
/bin/targets 目录下你看看有没有固件，我前几天编译的时候也有这种情况，不过我的是x86 的，这个报错了但是有固件

**Comment by FantasticSkyBaby** [comment]
貌似不是这个问题，附完整单线程编译报错log

#
# configuration written to .config
#
make[4]: Leaving directory '/Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07'
mkdir -p /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/tpl/dts
mkdir -p /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/include/generated
cp -fpR /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/of-platdata/nanopi-r2s-rk3328/dt-plat.c /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/tpl/dts/dt-plat.c
cp -fpR /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/of-platdata/nanopi-r2s-rk3328/dt-structs-gen.h /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/include/generated/dt-structs-gen.h
cp -fpR /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/of-platdata/nanopi-r2s-rk3328/dt-decl.h /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/include/generated/dt-decl.h
/Volumes/OpenWrt/lede/staging_dir/host/bin/sed -i -e 's#CONFIG_MKIMAGE_DTC_PATH=.*#CONFIG_MKIMAGE_DTC_PATH="/Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/scripts/dtc/dtc"#g' /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.config
echo 'CONFIG_IDENT_STRING=" OpenWrt"' >> /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.config
touch /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.built
touch /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.built_check
make  -C /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07 CROSS_COMPILE=aarch64-openwrt-linux-musl- DTC="/Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.10.120/scripts/dtc/dtc" HOSTCC="gcc" HOSTCFLAGS="-O2 -I/Volumes/OpenWrt/lede/staging_dir/host/include -I/Volumes/OpenWrt/lede/staging_dir/hostpkg/include -I/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/include -I/Volumes/OpenWrt/lede/staging_dir/host/include -I/Volumes/OpenWrt/lede/staging_dir/hostpkg/include -I/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/include -std=gnu11" HOSTLDFLAGS="-L/Volumes/OpenWrt/lede/staging_dir/host/lib -L/Volumes/OpenWrt/lede/staging_dir/hostpkg/lib -L/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/lib" V='' BL31=/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/image/rk322xh_bl31_v1.46.elf
make[4]: Entering directory '/Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
ld: warning: directory not found for option '-L/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/lib'
scripts/kconfig/conf  --syncconfig Kconfig
.config:1919:warning: override: reassigning to symbol IDENT_STRING
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  GEN     spl/include/autoconf.mk
  CFG     tpl/u-boot.cfg
  GEN     tpl/include/autoconf.mk
  UPD     include/config/uboot.release
  UPD     include/generated/version_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  UPD     include/generated/dt.h
  CC      lib/asm-offsets.s
  UPD     include/generated/generic-asm-offsets.h
  CC      arch/arm/lib/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  LEX     scripts/dtc/dtc-lexer.lex.c
  YACC    scripts/dtc/dtc-parser.tab.h
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  YACC    scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
ld: warning: directory not found for option '-L/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/lib'
  HOSTCC  tools/gen_eth_addr
  HOSTCC  tools/gen_ethaddr_crc.o
  WRAP    tools/lib/crc8.c
  HOSTCC  tools/lib/crc8.o
  HOSTLD  tools/gen_ethaddr_crc
ld: warning: directory not found for option '-L/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/lib'
  HOSTCC  tools/img2srec
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/os_support.o
  WRAP    tools/lib/crc32.c
  HOSTCC  tools/lib/crc32.o
  HOSTLD  tools/mkenvimage
ld: warning: directory not found for option '-L/Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/host/lib'
  HOSTCC  tools/aisimage.o
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:13:
include/linux/types.h:146:9: error: unknown type name '__u64'; did you mean '__s64'?
typedef __u64 __bitwise __le64;
        ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:13:
include/linux/types.h:147:9: error: unknown type name '__u64'; did you mean '__s64'?
typedef __u64 __bitwise __be64;
        ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:125:42: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __attribute__((const)) __u64 __fswab64(__u64 x)
                                         ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:125:58: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __attribute__((const)) __u64 __fswab64(__u64 x)
                                                         ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:130:12: error: use of undeclared identifier '__u64'
        return (((__u64)__swab32(l)) << 32) | ((__u64)(__swab32(h)));
                  ^
include/linux/byteorder/swab.h:130:42: error: use of undeclared identifier '__u64'
        return (((__u64)__swab32(l)) << 32) | ((__u64)(__swab32(h)));
                                                ^
include/linux/byteorder/swab.h:135:19: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __u64 __swab64p(const __u64 *x)
                  ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:135:41: error: unknown type name '__u64'; did you mean '__s64'?
static __inline__ __u64 __swab64p(const __u64 *x)
                                        ^
/Volumes/OpenWrt/lede/staging_dir/host/include/asm/types.h:19:44: note: '__s64' declared here
__extension__ typedef __signed__ long long __s64;
                                           ^
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:14:
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
        return __arch__swab64p(x);
               ^
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:89:24: note: expanded from macro '__swab64'
(__builtin_constant_p((__u64)(x)) ? \
                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:32:4: note: expanded from macro '___swab64'
        ((__u64)( \
          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:33:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x00000000000000ffULL) << 56) | \
                                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:34:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x000000000000ff00ULL) << 40) | \
                                       ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:4: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                 ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:13: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                          ^
include/linux/byteorder/swab.h:137:9: error: use of undeclared identifier '__u64'
include/linux/byteorder/swab.h:62:30: note: expanded from macro '__arch__swab64p'
#  define __arch__swab64p(x) __swab64(*(x))
                             ^
include/linux/byteorder/swab.h:90:2: note: expanded from macro '__swab64'
 ___swab64((x)) : \
 ^
include/linux/byteorder/swab.h:35:26: note: expanded from macro '___swab64'
                (__u64)(((__u64)(x) & (__u64)0x0000000000ff0000ULL) << 24) | \
                                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[5]: *** [scripts/Makefile.host:112: tools/aisimage.o] Error 1
make[4]: *** [Makefile:1822: tools] Error 2
make[4]: Leaving directory '/Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07'
make[3]: *** [Makefile:192: /Volumes/OpenWrt/lede/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2021.07/.built] Error 2
make[3]: Leaving directory '/Volumes/OpenWrt/lede/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r2s-rk3328/compile#14.47#52.10#64.71
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r2s-rk3328).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/Volumes/OpenWrt/lede'
make[1]: *** [package/Makefile:110: /Volumes/OpenWrt/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/Volumes/OpenWrt/lede'
make: *** [/Volumes/OpenWrt/lede/include/toplevel.mk:230: world] Error 2

**Comment by zhaochina2025** [comment]
怎么解决的，我也这个错误。
