### ISSUE TITLE
qca-nss-ecm-noload报qca-mcs.ko缺失

### ISSUE THREAD

**Issue by Leozaki** [coolsnowwolf/lede#9591]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：qca-nss-ecm-noload报qca-mcs.ko缺失

### (2) 路由器型号和固件版本

A：Ruijie M520

### (3) 详细日志

A：
make[3]: Entering directory '/Volumes/StarkyDisk/lede/package/qca/qca-mcs'
mkdir -p /Volumes/StarkyDisk/lede/dl
SHELL= flock /Volumes/StarkyDisk/lede/tmp/.qca-mcs-2021-10-28-31f5cd4b.tar.xz.flock -c '  	/Volumes/StarkyDisk/lede/scripts/download.pl "/Volumes/StarkyDisk/lede/dl" "qca-mcs-2021-10-28-31f5cd4b.tar.xz" "3e2e25025dc2e771aafe7d8b12f26ac831d123b34bdd7b7e84bd39c1e933491d" "" || (  	echo "Checking out files from the git repository..."; mkdir -p /Volumes/StarkyDisk/lede/tmp/dl && cd /Volumes/StarkyDisk/lede/tmp/dl && rm -rf qca-mcs-2021-10-28-31f5cd4b && [ \! -d qca-mcs-2021-10-28-31f5cd4b ] && git clone  https://source.codeaurora.org/quic/qsdk/oss/lklm/qca-mcs qca-mcs-2021-10-28-31f5cd4b && (cd qca-mcs-2021-10-28-31f5cd4b && git checkout 31f5cd4b83da5a7c0fdca240b4e72677e4523b6e && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd qca-mcs-2021-10-28-31f5cd4b && git log -1 --format='\''@%ct'\''` && rm -rf qca-mcs-2021-10-28-31f5cd4b/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c qca-mcs-2021-10-28-31f5cd4b | 	xz -zc -7e > /Volumes/StarkyDisk/lede/tmp/dl/qca-mcs-2021-10-28-31f5cd4b.tar.xz && mv /Volumes/StarkyDisk/lede/tmp/dl/qca-mcs-2021-10-28-31f5cd4b.tar.xz /Volumes/StarkyDisk/lede/dl/ && rm -rf qca-mcs-2021-10-28-31f5cd4b;  )    '
mkdir -p /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/stamp
SHELL= flock /Volumes/StarkyDisk/lede/tmp/.root-copy.flock -c 'cp -fpR /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-mcs-2021-10-28-31f5cd4b/.pkgdir/kmod-qca-mcs/. /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/'
touch /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/stamp/.kmod-qca-mcs_installed
echo "kmod-qca-mcs" >> /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo/qca-mcs.default.install
make[3]: Leaving directory '/Volumes/StarkyDisk/lede/package/qca/qca-mcs'
time: package/qca/qca-mcs/compile#0.17#0.12#0.35
make[3]: Entering directory '/Volumes/StarkyDisk/lede/package/qca/nss/qca-nss-ecm'
mkdir -p /Volumes/StarkyDisk/lede/dl
SHELL= flock /Volumes/StarkyDisk/lede/tmp/.qca-nss-ecm-9228212b.tar.xz.flock -c '  	/Volumes/StarkyDisk/lede/scripts/download.pl "/Volumes/StarkyDisk/lede/dl" "qca-nss-ecm-9228212b.tar.xz" "02fe4c86c8c88fb15704b1b253ab756a2658f24ce5db64a7909cb60bf9c1cdff" "" || (  echo "Checking out files from the git repository..."; mkdir -p /Volumes/StarkyDisk/lede/tmp/dl && cd /Volumes/StarkyDisk/lede/tmp/dl && rm -rf qca-nss-ecm-9228212b && [ \! -d qca-nss-ecm-9228212b ] && git clone  https://source.codeaurora.org/quic/qsdk/oss/lklm/qca-nss-ecm qca-nss-ecm-9228212b && (cd qca-nss-ecm-9228212b && git checkout 9228212b4238c0d8c296f795948ede8f2ca0242e && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd qca-nss-ecm-9228212b && git log -1 --format='\''@%ct'\''` && rm -rf qca-nss-ecm-9228212b/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c qca-nss-ecm-9228212b | 	xz -zc -7e > /Volumes/StarkyDisk/lede/tmp/dl/qca-nss-ecm-9228212b.tar.xz && mv /Volumes/StarkyDisk/lede/tmp/dl/qca-nss-ecm-9228212b.tar.xz /Volumes/StarkyDisk/lede/dl/ && rm -rf qca-nss-ecm-9228212b;  )    '
mkdir -p /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/stamp
SHELL= flock /Volumes/StarkyDisk/lede/tmp/.root-copy.flock -c 'cp -fpR /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/.pkgdir/kmod-qca-nss-ecm-noload/. /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/'
touch /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/stamp/.kmod-qca-nss-ecm-noload_installed
mkdir -p /Volumes/StarkyDisk/lede/bin/targets/ipq806x/generic/packages /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/CONTROL /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/firewall.d  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/init.d  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/usr/bin  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/lib/netifd/offload  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/config  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/uci-defaults  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/sysctl.d
install -m0644 ./files/qca-nss-ecm.firewall  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/firewall.d/qca-nss-ecm
install -m0755 ./files/qca-nss-ecm.init  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/init.d/qca-nss-ecm
install -m0755 ./files/ecm_dump.sh  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/usr/bin/
install -m0755 ./files/on-demand-down  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/lib/netifd/offload/on-demand-down
install -m0644 ./files/qca-nss-ecm.uci  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/config/ecm
install -m0644 ./files/qca-nss-ecm.defaults  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/uci-defaults/99-qca-nss-ecm
install -m0755 ./files/qca-nss-ecm.sysctl  /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/sysctl.d/qca-nss-ecm.conf
#
# Remove the START line from the init script, so that the symlink
# in the /etc/rc.d directory is not created.
#
sed -i '/START=/d' /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload/etc/init.d/qca-nss-ecm
find /Volumes/StarkyDisk/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-ecm-noload/qca-nss-ecm-9228212b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-nss-ecm-noload -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package kmod-qca-nss-ecm-noload is missing dependencies for the following libraries:
qca-mcs.ko
make[3]: *** [Makefile:297: /Volumes/StarkyDisk/lede/bin/targets/ipq806x/generic/packages/kmod-qca-nss-ecm-noload_5.4.195+9228212b-1_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[3]: Leaving directory '/Volumes/StarkyDisk/lede/package/qca/nss/qca-nss-ecm'
time: package/qca/nss/qca-nss-ecm/noload/compile#0.27#0.21#0.72
    ERROR: package/qca/nss/qca-nss-ecm failed to build (build variant: noload).
make[2]: *** [package/Makefile:116: package/qca/nss/qca-nss-ecm/compile] Error 1
make[2]: Leaving directory '/Volumes/StarkyDisk/lede'
make[1]: *** [package/Makefile:110: /Volumes/StarkyDisk/lede/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/Volumes/StarkyDisk/lede'
make: *** [/Volumes/StarkyDisk/lede/include/toplevel.mk:230: world] Error 2
bash-3.2$ find . -name "qca-mcs.ko"
./build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-mcs-2021-10-28-31f5cd4b/.pkgdir/kmod-qca-mcs/lib/modules/5.4.195/qca-mcs.ko
./build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-mcs-2021-10-28-31f5cd4b/ipkg-arm_cortex-a15_neon-vfpv4/kmod-qca-mcs/lib/modules/5.4.195/qca-mcs.ko
./build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-mcs-2021-10-28-31f5cd4b/qca-mcs.ko
./staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/root-ipq806x/lib/modules/5.4.195/qca-mcs.ko

**Comment by WowRouter** [comment]
make[2] -C package/qca/nss/qca-nss-clients download
 make[2] -C package/qca/nss/qca-nss-drv download
 make[2] -C package/qca/nss/qca-nss-ecm download
    ERROR: package/lean/shortcut-fe/simulated-driver failed to build.
    ERROR: package/qca/nss/qca-nss-clients failed to build.
    ERROR: package/qca/nss/qca-nss-ecm failed to build (build variant: standard).
    ERROR: package/qca/nss/qca-nss-drv failed to build.

**Comment by fangsheng009** [comment]
@Leozaki 请问这个问题，最后是怎么解决的呢？我也遇到这个问题
