### ISSUE TITLE
R4S 精简版问题解决了吗？

### ISSUE THREAD

**Issue by gswangmd-gssi** [coolsnowwolf/lede#9602]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by WYC-2020** [comment]
不可能

**Comment by lxl6125** [comment]
退了吧，商家故意坑人就别指望开源社区给他们擦屁股

**Comment by Ding-Kyoma** [comment]
不是早就解决了么？早在5月份中就修了这个问题 #9059 。我现在就用阉割mac的r4s，没问题！

**Comment by gswangmd-gssi** [comment]
我的问题是：内核采用5.4.x 编译就没问题，用5.15/5.10编译，就会出现CGI界面打不开，提示 bad gateway 。。。。


HooinKyoma ***@***.***> 于2022年6月24日周五 23:55写道：
