### ISSUE TITLE
如何在拉取feeds时添加额外参数

### ISSUE THREAD

**Issue by Canary233** [coolsnowwolf/lede#9611]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：如何在拉取feeds时添加额外参数,如--depth=1，可以减少磁盘占用和下载时间

**Comment by hxlls** [comment]
查看openwrt 文档，里面有
https://openwrt.org/docs/guide-developer/feeds

**Comment by Canary233** [comment]
> 查看openwrt 文档，里面有 https://openwrt.org/docs/guide-developer/feeds

感谢
