### ISSUE TITLE
R7800电源指示灯不亮，wan指示灯不闪

### ISSUE THREAD

**Issue by daidaiwood** [coolsnowwolf/lede#962]
如题
版本如下
主机名 | OpenWrt
-- | --
主机型号 | Netgear Nighthawk X4S R7800
架构 | ARMv7 Processor rev 0 (v7l)
固件版本 | OpenWrt R8.1.12 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
内核版本 | 4.14.90

**Comment by lan542662** [comment]
我刚编译的系统都进不去..看你这两个灯都不亮.那不是和我一样...系统都没进吗..

**Comment by lan542662** [comment]
gl重编译即可。enjoy ~

**Comment by daidaiwood** [comment]
今天最新版编译，电源灯okay了。 wan口灯还是不亮
