### ISSUE TITLE
r2s 编译错误

### ISSUE THREAD

**Issue by smith-jack-songh** [coolsnowwolf/lede#9623]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：r2s编译失败

### (2) 路由器型号和固件版本

A：R2S   Openwrt  R22.5.5

### (3) 详细日志

A：/home/hailey/lede/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/lib/gcc/a                      arch64-openwrt-linux-musl/8.4.0/../../../../aarch64-openwrt-linux-musl/bin/ld: c                      annot find -liconv
collect2: error: ld returned 1 exit status
make[4]: *** [prog/sensors/Module.mk:43: prog/sensors/sensors] Error 1
make[4]: Leaving directory '/home/hailey/lede/build_dir/target-aarch64_generic_m                      usl/lm-sensors-3-6-0'
make[3]: *** [Makefile:129: /home/hailey/lede/build_dir/target-aarch64_generic_m                      usl/lm-sensors-3-6-0/.built] Error 2
make[3]: Leaving directory '/home/hailey/lede/feeds/packages/utils/lm-sensors'
time: package/feeds/packages/lm-sensors/compile#1.99#0.31#2.47
    ERROR: package/feeds/packages/lm-sensors failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/lm-sensors/compile] E                      rror 1
make[2]: Leaving directory '/home/hailey/lede'
make[1]: *** [package/Makefile:110: /home/hailey/lede/staging_dir/target-aarch64                      _generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hailey/lede'
make: *** [/home/hailey/lede/include/toplevel.mk:230: world] Error 2

**Comment by LPDDR6-10000MHz** [comment]
用万能大法 ------->>>>>` make distclean` <<<<<  清理所有，then the next step
```
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
```
