### ISSUE TITLE
小米3G路由器编译出来有线正常，无线连接只有1M，几乎不能用？各位有没有遇到？？

### ISSUE THREAD

**Issue by sonytxl** [coolsnowwolf/lede#9643]
小米3G路由器编译出来有线正常，无线连接只有1M，几乎不能用？各位有没有遇到？？

**Comment by liwenjie119** [comment]
我mt7621的新3和cr660x都这样，退回到更改驱动之前了

**Comment by sonytxl** [comment]
> 我mt7621的新3和cr660x都这样，退回到更改驱动之前了

我是云编译的，没有备份之前的，有什么办法吗？谢谢

**Comment by iamsxm** [comment]
> 
git clone的时候可以指定tag

**Comment by WowRouter** [comment]
刚刚编译的 同样的问题

**Comment by xiangfeigao** [comment]
遇到了，无线速度很慢
