### ISSUE TITLE
2.5G网卡id补充

### ISSUE THREAD

**Issue by Sn0r1axi** [coolsnowwolf/lede#9644]
Bus 004 Device 003: ID 0bda:8156 Realtek Semiconductor Corp. 

刚刚测试6.15固件，确已查到编译了kmod-usb-net-rtl8152
![image](https://user-images.githubusercontent.com/26668216/174221194-1f949061-fb99-4aec-a7c5-12e45df654dc.png)

在8156B网卡连接后并未出现在openwrt首页，也没有出现在接口的物理设置中（应出现WAN4），
![image](https://user-images.githubusercontent.com/26668216/174220869-7f4f975a-865b-467a-96c3-97535ad2163c.png)

但lsusb后能够看到网卡正确接入。
![7K9X)VL{H(W9 C3H%UZ129S](https://user-images.githubusercontent.com/26668216/174220617-5ea361dd-adb1-4f67-80a0-2d8aa45a72c2.png)

_Originally posted by @Sn0r1axi in https://github.com/coolsnowwolf/lede/discussions/9539#discussioncomment-2965461_

**Comment by AmadeusGhost** [comment]
不要选这个，换 r8152-vendor 试试。
