### ISSUE TITLE
MT7621 JCG Q20 改为 swconfig 交换机，WAN 与 WIFI 桥接后的 WIFI 无法获取到 IP 地址

### ISSUE THREAD

**Issue by dsanke** [coolsnowwolf/lede#9658]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：JCG Q20 改为 swconfig 交换机，WAN 与 WIFI 桥接后的 WIFI 无法获取到 IP 地址
用这里（https://github.com/padavanonly/immortalwrt）的源码编译是正常的

### (2) 路由器型号和固件版本

A：JCG Q20
今日最新源码编译，内核用的 5.4
切换新的hwnat之前是正常的

### (3) 详细日志

A：启动后的日志（mac和ip已脱敏处理）
编译配置
dts文件
见附件压缩包

[0627.zip](https://github.com/coolsnowwolf/lede/files/8992785/0627.zip)

**Comment by coolsnowwolf** [comment]
wifi to wan 的 hwnat 和桥接功能有冲突。桥接的时候驱动里面要去掉 rax 接口

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/176370655-50a85a65-0baa-41c4-8d42-a6c7f8694eae.png)
