### ISSUE TITLE
Xiaomi cr660x 配置二级路由后wifi网络问题

### ISSUE THREAD

**Issue by Guxing0321** [coolsnowwolf/lede#9660]
Hello Team,

发现一个问题，就是xiaomi cr6608 路由器刷了lede固件后，配置二级路由，网线连接是没问题的，但是wifi基本上网页打不开
![5a721eb7f936124be0e94f23bde4686](https://user-images.githubusercontent.com/25215114/176076442-70854411-8463-4979-b62f-d9922536c330.png)
![8fa89e340b2b57d8c5451399e256927](https://user-images.githubusercontent.com/25215114/176076466-cfee0182-51e8-41c1-97cf-2fde29c245c3.png)

![31cb12e3fcfda9b4d6b605bf80d8ffb](https://user-images.githubusercontent.com/25215114/176076546-bbccb0ba-092b-480d-a75e-e27cfd5e9130.png)

目前发现的问题，
wifi 连接后ping 114.114.114.114 这种外网地址是可以通的，但是ping www.baidu.com 有时候可以，有时候解析不出来

日志我拷贝出来了，目前没看到明显的相关的报错
[log.txt](https://github.com/coolsnowwolf/lede/files/8997081/log.txt)

希望大佬们帮忙看下，是不是哪边需要改下测试，或者怎么样测试下

BR
Robin

**Comment by 286700234** [comment]
我一级路由都WiFi跟你一样的情况

**Comment by Guxing0321** [comment]
> 我一级路由都WiFi跟你一样的情况

hello， 这个应该不对呀，我记得之前就是这么配置的，也没出啥问题
感觉新的固件版本可能有某个地方需要改配置啥的


BR
Robin

**Comment by Guxing0321** [comment]
我发现了一个解决的办法，
就是回退版本，realease tag: **20220505**

我用的是action编译，
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/25215114/176573686-400cfd0c-e0a8-4647-b01b-fda623f2110d.png">


BR
Robin
