### ISSUE TITLE
lede全默认设置编译失败

### ISSUE THREAD

**Issue by adamgonglj** [coolsnowwolf/lede#9664]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

![微信截图_20220629123636](https://user-images.githubusercontent.com/24622353/176352767-8b1ba456-4aef-476e-a3df-3146fb2723b5.png)

**Comment by adamgonglj** [comment]
参数是全部默认的，仍然编译失败。

**Comment by adamgonglj** [comment]
编译环境是腾讯云8G，Ubuntu 22.04 LTS x86_64(Py3.7.8)

**Comment by EnnawYang** [comment]
默认编译无任何问题，另外能不能不要重复开issue
![Snipaste_2022-06-29_13-03-11](https://user-images.githubusercontent.com/6705663/176355600-3fa5c90f-2b1e-4465-9294-46e6e9fec592.png)

**Comment by adamgonglj** [comment]
我看报错内容不一样，所以开的两个issue.

**Comment by adamgonglj** [comment]
> 默认编译无任何问题，另外能不能不要重复开issue ![Snipaste_2022-06-29_13-03-11](https://user-images.githubusercontent.com/6705663/176355600-3fa5c90f-2b1e-4465-9294-46e6e9fec592.png)

那我应该如何排障呢？

**Comment by 138398wpf** [comment]
你的报错日志介绍的很清楚，error while loading shared libraries 缺少必要的库，建议查一下/usr/local/lib是否包含提示的文件。

**Comment by adamgonglj** [comment]
换系统后编译成功。
