### ISSUE TITLE
新issue，默认设置编译失败

### ISSUE THREAD

**Issue by adamgonglj** [coolsnowwolf/lede#9668]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

目前不理解invalid ELF header是问题如何解决。

![微信截图_20220629184428](https://user-images.githubusercontent.com/24622353/176418946-2d74f711-38f6-4586-9b43-c81d94714aad.png)

**Comment by EnnawYang** [comment]
建议您换个完整点的系统，瞎折腾很累的

**Comment by adamgonglj** [comment]
前几天还可以编译，人都气死了


EnnawYang ***@***.***>于2022年6月29日 周三18:52写道：

**Comment by adamgonglj** [comment]
现在就换系统。

**Comment by adamgonglj** [comment]
换系统后编译成功。
