### ISSUE TITLE
zerotier启动不了

### ISSUE THREAD

**Issue by icsfy** [coolsnowwolf/lede#9679]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：Zerotier 未运行
命令行运行提示 Segmentation fault

### (2) 路由器型号和固件版本

A：ASUS RT-ACRH17 最新代码编译固件

### (3) 详细日志

A：
```
root@OpenWrt:~# zerotier-
zerotier-cli     zerotier-idtool  zerotier-one
root@OpenWrt:~# zerotier-cli --help
Segmentation fault
root@OpenWrt:~# zerotier-one --help
Segmentation fault
root@OpenWrt:~# zerotier-idtool --help
Segmentation fault
root@OpenWrt:~#
```

**Comment by wuzhuang123** [comment]
如果是源码编译的，有可能是交叉编译器的问题。尝试写个demo测试一下。

**Comment by icsfy** [comment]
https://github.com/coolsnowwolf/packages/commit/b09bcb347505050e83e26160f63463fef018c16b
把这单revert之后编译的可以启动起来
