### ISSUE TITLE
SSR PLUS 能否添加前置代理选项

### ISSUE THREAD

**Issue by edmondfr** [coolsnowwolf/lede#968]
老大，SSR PC端的前置代理功能非常好用，对于线路不好的运营商或者小水管的VPS，作为跳板的前置代理作用非常明显，速度提升数以倍计，几百K/秒的连接带宽如果添加前置代理（如阿里云腾讯云代理服务器）后甚至可以流畅观看4K视频。希望能在路由端上添加这一PC端的这个功能，让SSR PLUS 更加无敌，感谢！

**Comment by lan542662** [comment]
叫男神比叫老大管用，不信你试试。

**Comment by dzhuqi** [comment]
确实有效果
