### ISSUE TITLE
R4S

### ISSUE THREAD

**Issue by skaterjuice** [coolsnowwolf/lede#9686]
make[3]: Entering directory '/home/masterbuilder/lede/feeds/packages/libs/libxslt'
make[3]: *** [Makefile:167: /home/masterbuilder/lede/build_dir/hostpkg/libxslt-1.1.34/.configured] Error 1
make[2]: *** [package/Makefile:114: package/feeds/packages/libxslt/host/compile] Error 1
make[1]: *** [package/Makefile:110: /home/masterbuilder/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make: *** [/home/masterbuilder/lede/include/toplevel.mk:230: world] Error 2

**Comment by minlang112** [comment]
遇事不决make clean
