### ISSUE TITLE
R2S刷入新固件不能正常运行

### ISSUE THREAD

**Issue by liumingzh2008** [coolsnowwolf/lede#9689]
我的R2S原先的内核版本是5.4.132，是自己在Ubuntu上编译成功的固件，一直正常运行用到现在，前几日用L大新代码编译成最新的内核版本，刷卡开机在LAN可能正常设置系统，但一插上WAN口网线就会显示WAN没有联网，不能上网，尝试使用几位大神的固件也是一样不能联网，显示WAN不能联网，不知是哪里造成的，刷eSir的R2S固件则没有这个问题。

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/Actions-OpenWrt
我昨天更新的，看r2s可以
