### ISSUE TITLE
SSR用ChinaIP模式报错

### ISSUE THREAD

**Issue by LoveyCat** [coolsnowwolf/lede#97]
你好，套用你的ssr源码集成在官方的lede源码中，更新后的ssr使用ChinaIP模式就会报错，提示ssr-redir找不到，用GFW模式就没问题，上一个版本都没问题，请问能修复吗
![2017-10-01_164855](https://user-images.githubusercontent.com/14886041/31054991-30b7bca8-a6f0-11e7-9c1d-40a4f3052a26.png)

**Comment by coolsnowwolf** [comment]
不负责解决第三方问题，自己解决
