### ISSUE TITLE
udpxy无法保存"Buffer messages","Buffer time","Multicast subscription renew"参数

### ISSUE THREAD

**Issue by envesion** [coolsnowwolf/lede#9702]
无法保存参数如下图所示:
![无标题](https://user-images.githubusercontent.com/37428788/177463786-c067f9c2-d9ce-41ef-a137-4670f2f58d7f.png)

**Comment by coolsnowwolf** [comment]
@Beginner-Go 看看这个？~

**Comment by Beginner-Go** [comment]
晚上看看

**Comment by WYC-2020** [comment]
这玩意是luci 的bug，修复下datatype即可

**Comment by WYC-2020** [comment]
https://github.com/openwrt/luci/issues/5705
