### ISSUE TITLE
ESXI 6.7 下，x64-R22.5.5  cpu 负载较高。

### ISSUE THREAD

**Issue by mailsex** [coolsnowwolf/lede#9706]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
ESXI 6.7 下，x64-R22.5.5  cpu 负载较高。
Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

## 2. 详细叙述
在软路由上，ESXI 版本为6.7.0 Update 3 (Build 15160138)，
虚拟机配置：1cpu、512 RAM，bios 启动。使用 StarWind V2V Image Converter 将openwrt-x64-R22.5.5-generic-squashfs-combined-efi.img 文件转化成 ESXI 磁盘 ，上传至esxi 平台部署。
### (1) 具体问题
同样的虚拟机配置，空负载情况下，x64-R22.5.5 cpu占用比 R21.11.11高不少，如下图
A：
CPU占用截图
![c9f76258b6eecfa760ce81eacc5be49](https://user-images.githubusercontent.com/10483712/177677745-1d4ab94b-d4bd-438c-a574-00d170bd4e59.png)
![1a38b2f1e206042fdcef00d856abd7d](https://user-images.githubusercontent.com/10483712/177677759-fb594093-53ec-4f33-bef4-d05c5f7692b0.png)
网络占用截图
![f40400dc29a99d6cfa8fc907f6255b0](https://user-images.githubusercontent.com/10483712/177677799-91be8a36-0c0f-46e4-a652-ace7d0c1fc2d.png)
![3800587a5ef0b580c707c324c76de97](https://user-images.githubusercontent.com/10483712/177677806-9112db64-d1c0-452c-bdef-264706112aea.png)

### (2) 路由器型号和固件版本

A：MacMini 安装了esxi 6.7，再部署的openwrt，旁路路由模式。上联另一个主路由。

### (3) 详细日志

A：x64-R22.5.5 系统日志
http://216.24.178.186:888/chfs/shared/%E7%B3%BB%E7%BB%9F%E6%97%A5%E5%BF%97.txt
B：x64-R22.5.5 内核日志
http://216.24.178.186:888/chfs/shared/%E5%86%85%E6%A0%B8%E6%97%A5%E5%BF%97.txt

**Comment by WYC-2020** [comment]
这个时候不是应该看那个进程占用高了 这些截图能看出个啥

**Comment by mailsex** [comment]
> 这个时候不是应该看那个进程占用高了 这些截图能看出个啥

进程上看起来差不多。。。。

**Comment by GreatMichaelLee** [comment]
进来看了个寂寞，哈哈
