### ISSUE TITLE
请问哪里还有5.4内核的备份库？

### ISSUE THREAD

**Issue by tiantaichenhui** [coolsnowwolf/lede#9707]
5.15有个问题一直存在：路由器 用X550网卡（其他2.5G网卡未知）无法握手2.5G。 对接电脑2.5G网卡（8125B） 或者无线路由2.5G WAN口（AX86U） 都一样 只能握手千兆。
5.4内核可以完美握手2.5G  
哪位大佬有5.4内核库的备份 请分享下 不胜感谢！

**Comment by coolsnowwolf** [comment]
可以手动改为 5.4 内核

**Comment by tiantaichenhui** [comment]
> 可以手动改为 5.4 内核

谢谢宇宙超级无敌大雕大佬翻牌  在下先去试试看

**Comment by GreatMichaelLee** [comment]
> 可以手动改为 5.4 内核

test kernel 设置为5.4就可以了 /target/linux/x86/Makefile里，如果是其他cpu,找对应的。

**Comment by Shinwar** [comment]
@tiantaichenhui  5.10自动禁用了2.5G和5G协商(和windows驱动一样蠢), 需要手动开启协商, 并且要添加到启动脚本中
开启方式: ethtool -s <ifname> advertise 0x800000000000

**Comment by tiantaichenhui** [comment]
> @tiantaichenhui 5.10中的ixgbe自动禁用了2.5G和5G协商(和windows驱动一样蠢), 需要手动开启协商, 并且要添加到启动脚本中 开启方式: ethtool -s advertise 0x800000000000

谢谢大佬解疑 另外请问5.15 5.19也是这样么？

**Comment by Shinwar** [comment]
是的
