### ISSUE TITLE
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后删除了

### ISSUE THREAD

**Issue by netlovehf** [coolsnowwolf/lede#9720]
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后删除了，以前的luci-app-ssr-plus正常的

**Comment by netlovehf** [comment]
![2424](https://user-images.githubusercontent.com/48405188/178092804-130ccd25-8fdb-4c36-b6a1-8caf9fe80755.jpg)

**Comment by devome** [comment]
问错地方了。

**Comment by minlang112** [comment]
问错地方了，自己关掉吧
