### ISSUE TITLE
x86-5.18内核  kmod-fs-cifs编译失败

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [coolsnowwolf/lede#9721]
x86-5.18内核，kmod-fs-cifs编译失败

Package kmod-fs-cifs is missing dependencies for the following libraries:
asn1_decoder.ko
dns_resolver.ko
oid_registry.ko

**Comment by ricksuzade-maker** [comment]
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-ecb into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-ecb_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-echainiv/lib/modules/5.18.10/echainiv.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-echainiv into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-echainiv_5.18.10-1_aarch64_generic.ipk
NOTICE: module '/home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.18.10/crypto/gf128mul.ko' is built-in.
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-gf128 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-gf128_5.18.10-1_aarch64_generic.ipk
NOTICE: module '/home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.18.10/crypto/ghash-generic.ko' is built-in.
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-ghash into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-ghash_5.18.10-1_aarch64_generic.ipk
NOTICE: module '/home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.18.10/crypto/gcm.ko' is built-in.
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-gcm into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-gcm_5.18.10-1_aarch64_generic.ipk
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-kpp into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-kpp_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-chacha20/lib/modules/5.18.10/libchacha.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-chacha20/lib/modules/5.18.10/chacha-neon.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-chacha20 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-lib-chacha20_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-poly1305/lib/modules/5.18.10/poly1305-neon.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-poly1305 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-lib-poly1305_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-chacha20poly1305/lib/modules/5.18.10/libchacha20poly1305.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-chacha20poly1305 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-lib-chacha20poly1305_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-curve25519/lib/modules/5.18.10/libcurve25519-generic.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-curve25519/lib/modules/5.18.10/libcurve25519.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-lib-curve25519 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-lib-curve25519_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-md4/lib/modules/5.18.10/md4.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-md4 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-md4_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-md5/lib/modules/5.18.10/md5.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-md5 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-md5_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-sha1/lib/modules/5.18.10/sha1_generic.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-sha1 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-sha1_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-sha512/lib/modules/5.18.10/sha512_generic.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-sha512 into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-sha512_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/algif_rng.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/algif_skcipher.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/algif_aead.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/crypto_user.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/algif_hash.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user/lib/modules/5.18.10/af_alg.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-crypto-user into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-crypto-user_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-lzo/lib/modules/5.18.10/lzo_compress.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-lzo/lib/modules/5.18.10/lzo.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-lzo/lib/modules/5.18.10/lzo_decompress.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-lzo into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-lib-lzo_5.18.10-1_aarch64_generic.ipk
NOTICE: module '/home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.18.10/lib/xxhash.ko' is built-in.
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-zstd/lib/modules/5.18.10/zstd_decompress.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-zstd/lib/modules/5.18.10/zstd.ko: relocatable
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-zstd/lib/modules/5.18.10/zstd_compress.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-lib-zstd into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-lib-zstd_5.18.10-1_aarch64_generic.ipk
rstrip.sh: /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-fs-btrfs/lib/modules/5.18.10/btrfs.ko: relocatable
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-fs-btrfs into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-fs-btrfs_5.18.10-1_aarch64_generic.ipk
NOTICE: module '/home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.18.10/fs/nls/nls_base.ko' is built-in.
Packaged contents of /home/zhiliang/scripts/neo3/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/packages/ipkg-aarch64_generic/kmod-nls-base into /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-nls-base_5.18.10-1_aarch64_generic.ipk
Package kmod-fs-cifs is missing dependencies for the following libraries:
asn1_decoder.ko
dns_resolver.ko
oid_registry.ko
make[3]: *** [modules/fs.mk:121: /home/zhiliang/scripts/neo3/lede/bin/targets/rockchip/armv8/packages/kmod-fs-cifs_5.18.10-1_aarch64_generic.ipk] Error 1
make[3]: Leaving directory '/home/zhiliang/scripts/neo3/lede/package/kernel/linux'
time: package/kernel/linux/compile#7.59#1.05#7.31
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/home/zhiliang/scripts/neo3/lede'
make[1]: *** [package/Makefile:110: /home/zhiliang/scripts/neo3/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhiliang/scripts/neo3/lede'
make: *** [/home/zhiliang/scripts/neo3/lede/include/toplevel.mk:230: world] Error 2

**Comment by ricksuzade-maker** [comment]
我也遇到同样问题了

**Comment by ricksuzade-maker** [comment]
不过我是编译的rockchip arm64

**Comment by bookwm** [comment]
我也遇到同样问题了

**Comment by coolsnowwolf** [comment]
已修复
