### ISSUE TITLE
能否支援R8500

### ISSUE THREAD

**Issue by SexySaiki** [coolsnowwolf/lede#973]
十分感谢L大

**Comment by LGA1150** [comment]
https://forum.openwrt.org/t/support-for-netgear-r8500-x8-ac5300/14898

**Comment by LGA1150** [comment]
R8500 的硬件规格跟 K3 差不多，不过固件不一定兼容：

- 分区可能不一样
- R8500 外加了一个 BCM53125S 交换机芯片以提供额外的 LAN 口，我不清楚 OpenWrt 自带的 b53 驱动能否兼容此芯片，但是肯定需要额外的配置

**Comment by sancao2** [comment]
这个我看到Mikefile里面注释，就打开了，编译了之后，刷进去直接变成砖头了。
