### ISSUE TITLE
新三最近编译的固件都是无法启动，

### ISSUE THREAD

**Issue by yuzhe1129** [coolsnowwolf/lede#9733]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

插件我已经去掉了很多了，都没选什么插件，固件编译才10M大小，最近很多天编译的固件都无法启动 开始我以为我加别的源码进来问题的，可这次我都没选别的插件编译刷也是启动不了，

### (2) 路由器型号和固件版本
新三 D2
A：

### (3) 详细日志

Boot and Recovery Environment for Embedded Devices
Copyright (C) 2021 HackPascal <hackpascal@gmail.com>
Build date 2021-12-15 [git-f9b74d0]
Version 1.1 (r1337)

DRAM: 512MB
Platform: MediaTek MT7621A ver 1, eco 3
Board: Newifi D2
Clocks: CPU: 880MHz, DDR: 1040MHz, Bus: 220MHz, Ref: 40MHz
Flash: Macronix MX25L25635E (32MB) on mt7621-spi.0
rt2880-eth: MAC address from EEPROM is invalid, using default settings.
rt2880-eth: Using MAC address 00:0c:43:00:00:01
eth0: MediaTek MT7530 Gigabit switch

Network started on eth0, inet addr 192.168.1.1, netmask 255.255.255.0

Press any key to interrupt autoboot ... 0

Trying to boot firmware from 0x00050000 in flash bank 0 ...
Reading data into memory ...
U-Boot firmware image header detected.
    Image Name:   MIPS OpenWrt Linux-5.4.203
    Data Size:    2543830 Bytes
    Load Address: 80001000
    Entry Point:  80001000
Flushing cache ... done.

Starting kernel at 0x80001000...

OpenWrt kernel loader for MIPS based SoC
Copyright (C) 2011 Gabor Juhos <juhosg@openwrt.org>
Decompressing kernel... done!
Starting kernel at 80001000...

[    0.000000] Linux version 5.4.203 (bbb@ubuntu) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r4646-486587518)) #0 SMP Sun Jul 10 10:13:31 2022
[    0.000000] SoC Type: MediaTek MT7621 ver:1 eco:3
[    0.000000] printk: bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 0001992f (MIPS 1004Kc)
[    0.000000] MIPS: machine is Newifi-D2
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] VPE topology {2,2} total 4
[    0.000000] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.000000] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000fffffff]
[    0.000000]   HighMem  [mem 0x0000000010000000-0x0000000023ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000]   node   0: [mem 0x0000000020000000-0x0000000023ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000023ffffff]
[    0.000000] percpu: Embedded 14 pages/cpu s27152 r8192 d22000 u57344
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 130496
[    0.000000] Kernel command line: console=ttyS0,115200 rootfstype=squashfs,jffs2
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Writing ErrCtl register=00010140
[    0.000000] Readback ErrCtl register=00010140
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 509348K/524288K available (6168K kernel code, 270K rwdata, 1296K rodata, 1276K init, 235K bss, 14940K reserved, 0K cma-reserved, 262144K highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 256
[    0.000000] CPU Overclock PLL: 0xc2005b12
[    0.000000] CPU Clock: 1000MHz
[    0.000000] clocksource: GIC: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 3822520893 ns
[    0.000009] sched_clock: 32 bits at 500MHz, resolution 2ns, wraps every 4294967295ns
[    0.007886] Calibrating delay loop... 666.41 BogoMIPS (lpj=3332096)
[    0.074041] pid_max: default: 32768 minimum: 301
[    0.078822] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.086020] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.096688] rcu: Hierarchical SRCU implementation.
[    0.102123] smp: Bringing up secondary CPUs ...
[    1.606186] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    1.606196] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    1.606208] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    1.606315] CPU1 revision is: 0001992f (MIPS 1004Kc)
[    0.166893] Synchronize counters for CPU 1: done.
[    0.106325] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    0.106333] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    0.106341] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    0.106397] CPU2 revision is: 0001992f (MIPS 1004Kc)
[    0.257722] Synchronize counters for CPU 2: done.
[    2.094852] Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
[    2.094860] Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
[    2.094868] MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
[    2.094932] CPU3 revision is: 0001992f (MIPS 1004Kc)
[    0.342906] Synchronize counters for CPU 3: done.
[    0.372770] smp: Brought up 1 node, 4 CPUs
[    0.381393] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.391178] futex hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.398190] pinctrl core: initialized pinctrl subsystem
[    0.405465] NET: Registered protocol family 16
[    0.442316] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.453884] clocksource: Switched to clocksource GIC
[    0.460659] NET: Registered protocol family 2
[    0.465242] IP idents hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.473010] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.481319] TCP established hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.488913] TCP bind hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.495994] TCP: Hash tables configured (established 2048 bind 2048)
[    0.502397] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.508887] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.516072] NET: Registered protocol family 1
[    0.520361] PCI: CLS 0 bytes, default 32
[    0.753852] 4 CPUs re-calibrate udelay(lpj = 3325952)
[    0.760613] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.777240] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.782977] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.794985] bounce: pool size: 64 pages
[    0.800189] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.806078] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.811843] mt7621_gpio 1e000600.gpio: registering 32 gpios
[    0.818478] Serial: 8250/16550 driver, 3 ports, IRQ sharing disabled
[    0.826297] printk: console [ttyS0] disabled
[    0.830554] 1e000c00.uartlite: ttyS0 at MMIO 0x1e000c00 (irq = 19, base_baud = 3125000) is a 16550A
[    0.839556] printk: console [ttyS0] enabled
[    0.839556] printk: console [ttyS0] enabled
[    0.847807] printk: bootconsole [early0] disabled
[    0.847807] printk: bootconsole [early0] disabled
[    0.859978] spi-mt7621 1e000b00.spi: sys_freq: 250000000
[    0.866369] spi-nor spi0.0: unrecognized JEDEC id bytes: c2 20 1d c2 30 1d
[    0.873249] spi-nor: probe of spi0.0 failed with error -2
[    0.880888] [mtk_hw_init] reset_lock:0, force:0
[    0.885601] [mtk_hw_init] execute fe cold reset
[    0.901633] mtk_soc_eth 1e100000.ethernet: generated random MAC address 26:2d:39:30:a7:11
[    0.910659] mtk_soc_eth 1e100000.ethernet eth0: mediatek frame engine at 0xbe100000, irq 22
[    0.919025] (unnamed net_device) (dummy): netif_napi_add() called with weight 256
[    0.928909] mt7621-pci 1e140000.pcie: Parsing DT failed
[    0.936708] NET: Registered protocol family 10
[    0.942842] Segment Routing with IPv6
[    0.946652] NET: Registered protocol family 17
[    0.951192] Bridge firewalling registered
[    0.955516] 8021q: 802.1Q VLAN Support v1.8
[    0.963393] gpio-export gpio_export: 1 gpio(s) exported
[    1.014004] mt753x 1e110000.gsw: LAN/WAN VLAN setting=llllw
[    1.019684] mt753x 1e110000.gsw: Switch is MediaTek MT7530 rev 1
[    2.463070] rt2880-pinmux pinctrl: pcie is already enabled
[    2.468742] mt7621-pci-phy 1e149000.pcie-phy: PHY for 0xbe149000 (dual port = 1)
[    2.476317] mt7621-pci-phy 1e14a000.pcie-phy: PHY for 0xbe14a000 (dual port = 0)
[    2.483731] mt7621-pci 1e140000.pcie: failed to parse bus ranges property: -22
[    2.590927] mt7621-pci-phy 1e149000.pcie-phy: Xtal is 40MHz
[    2.596504] mt7621-pci-phy 1e14a000.pcie-phy: Xtal is 40MHz
[    2.702024] mt7621-pci 1e140000.pcie: pcie2 no card, disable it (RST & CLK)
[    2.708978] mt7621-pci 1e140000.pcie: PCIE0 enabled
[    2.713850] mt7621-pci 1e140000.pcie: PCIE1 enabled
[    2.718709] mt7621-pci 1e140000.pcie: PCI coherence region base: 0x60000000, mask/settings: 0xf0000002
[    2.728161] mt7621-pci 1e140000.pcie: PCI host bridge to bus 0000:00
[    2.734521] pci_bus 0000:00: root bus resource [io  0x1e160000-0x1e16ffff]
[    2.741362] pci_bus 0000:00: root bus resource [mem 0x60000000-0x6fffffff]
[    2.748223] pci_bus 0000:00: root bus resource [bus 00-ff]
[    2.753718] pci 0000:00:00.0: [0e8d:0801] type 01 class 0x060400
[    2.759745] pci 0000:00:00.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    2.766005] pci 0000:00:00.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    2.772308] pci 0000:00:00.0: supports D1
[    2.776315] pci 0000:00:00.0: PME# supported from D0 D1 D3hot
[    2.782394] pci 0000:00:01.0: [0e8d:0801] type 01 class 0x060400
[    2.788434] pci 0000:00:01.0: reg 0x10: [mem 0x00000000-0x7fffffff]
[    2.794693] pci 0000:00:01.0: reg 0x14: [mem 0x00000000-0x0000ffff]
[    2.800982] pci 0000:00:01.0: supports D1
[    2.804987] pci 0000:00:01.0: PME# supported from D0 D1 D3hot
[    2.812046] pci 0000:00:00.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    2.820050] pci 0000:00:01.0: bridge configuration invalid ([bus 00-00]), reconfiguring
[    2.828238] pci 0000:01:00.0: [14c3:7662] type 00 class 0x028000
[    2.834301] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x000fffff 64bit]
[    2.841092] pci 0000:01:00.0: reg 0x30: [mem 0x00000000-0x0000ffff pref]
[    2.847876] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    2.855326] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    2.860536] pci 0000:00:00.0:   bridge window [io  0x0000-0x0fff]
[    2.866631] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff]
[    2.873388] pci 0000:00:00.0:   bridge window [mem 0x00000000-0x000fffff pref]
[    2.880597] pci_bus 0000:01: busn_res: [bus 01-ff] end is updated to 01
[    2.887409] pci 0000:02:00.0: [14c3:7603] type 00 class 0x028000
[    2.893424] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x000fffff]
[    2.899818] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    2.907277] pci 0000:00:01.0: PCI bridge to [bus 02-ff]
[    2.912486] pci 0000:00:01.0:   bridge window [io  0x0000-0x0fff]
[    2.918581] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff]
[    2.925356] pci 0000:00:01.0:   bridge window [mem 0x00000000-0x000fffff pref]
[    2.932546] pci_bus 0000:02: busn_res: [bus 02-ff] end is updated to 02
[    2.939196] pci 0000:00:00.0: BAR 0: no space for [mem size 0x80000000]
[    2.945797] pci 0000:00:00.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.952726] pci 0000:00:01.0: BAR 0: no space for [mem size 0x80000000]
[    2.959324] pci 0000:00:01.0: BAR 0: failed to assign [mem size 0x80000000]
[    2.966281] pci 0000:00:00.0: BAR 8: assigned [mem 0x60000000-0x600fffff]
[    2.973038] pci 0000:00:00.0: BAR 9: assigned [mem 0x60100000-0x601fffff pref]
[    2.980245] pci 0000:00:01.0: BAR 8: assigned [mem 0x60200000-0x602fffff]
[    2.987022] pci 0000:00:01.0: BAR 9: assigned [mem 0x60300000-0x603fffff pref]
[    2.994229] pci 0000:00:00.0: BAR 1: assigned [mem 0x60400000-0x6040ffff]
[    3.000990] pci 0000:00:01.0: BAR 1: assigned [mem 0x60410000-0x6041ffff]
[    3.007767] pci 0000:00:00.0: BAR 7: assigned [io  0x1e160000-0x1e160fff]
[    3.014543] pci 0000:00:01.0: BAR 7: assigned [io  0x1e161000-0x1e161fff]
[    3.021307] pci 0000:01:00.0: BAR 0: assigned [mem 0x60000000-0x600fffff 64bit]
[    3.028610] pci 0000:01:00.0: BAR 6: assigned [mem 0x60100000-0x6010ffff pref]
[    3.035816] pci 0000:00:00.0: PCI bridge to [bus 01]
[    3.040758] pci 0000:00:00.0:   bridge window [io  0x1e160000-0x1e160fff]
[    3.047535] pci 0000:00:00.0:   bridge window [mem 0x60000000-0x600fffff]
[    3.054310] pci 0000:00:00.0:   bridge window [mem 0x60100000-0x601fffff pref]
[    3.061503] pci 0000:02:00.0: BAR 0: assigned [mem 0x60200000-0x602fffff]
[    3.068278] pci 0000:00:01.0: PCI bridge to [bus 02]
[    3.073218] pci 0000:00:01.0:   bridge window [io  0x1e161000-0x1e161fff]
[    3.079990] pci 0000:00:01.0:   bridge window [mem 0x60200000-0x602fffff]
[    3.086764] pci 0000:00:01.0:   bridge window [mem 0x60300000-0x603fffff pref]
[    3.094751] hctosys: unable to open rtc device (rtc0)
[    3.100601] /dev/root: Can't open blockdev
[    3.104722] VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6
[    3.112164] Please append a correct "root=" boot option; here are the available partitions:
[    3.120488] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    3.128751] Rebooting in 1 seconds..

Boot and Recovery Environment for Embedded Devices
Copyright (C) 2021 HackPascal <hackpascal@gmail.com>
Build date 2021-12-15 [git-f9b74d0]
Version 1.1 (r1337)

DRAM: 512MB
Platform: MediaTek MT7621A ver 1, eco 3
Board: Newifi D2
Clocks: CPU: 880MHz, DDR: 1040MHz, Bus: 220MHz, Ref: 40MHz
Flash: Macronix MX25L25635E (32MB) on mt7621-spi.0
rt2880-eth: MAC address from EEPROM is invalid, using default settings.
rt2880-eth: Using MAC address 00:0c:43:00:00:01
eth0: MediaTek MT7530 Gigabit switch

**Comment by coolsnowwolf** [comment]
内核找不到 spi 上面的 rootfs 分区

**Comment by yuzhe1129** [comment]
> 内核找不到 spi 上面的 rootfs 分区

那么是我编译的问题还是什么？

**Comment by aiamadeus** [comment]
你新三的 spi 闪存出问题了吧

**Comment by uniessey** [comment]
> > 内核找不到 spi 上面的 rootfs 分区
> 
> 那么是我编译的问题还是什么？

我自己遇到过的情况而言，要么是编译的时候出了意外，要么是硬件上有问题了，试试全部删除重新拉取，如果能一次拉取成功，那么一般不会出什么大问题，如果拉取过程总是失败，那么还是有可能出问题的。

**Comment by yuzhe1129** [comment]
> > > 内核找不到 spi 上面的 rootfs 分区
> > 
> > 
> > 那么是我编译的问题还是什么？
> 
> 我自己遇到过的情况而言，要么是编译的时候出了意外，要么是硬件上有问题了，试试全部删除重新拉取，如果能一次拉取成功，那么一般不会出什么大问题，如果拉取过程总是失败，那么还是有可能出问题的。

硬件百分百没问题，路由我都正在用，刷老毛子 6.25号的我编译有是可以启动的，源码已经删除重新下载过了的，

**Comment by harrylwc** [comment]
https://github.com/openwrt/openwrt/issues/10232

**Comment by uniessey** [comment]
> > > > 内核找不到 spi 上面的 rootfs 分区
> > > 
> > > 
> > > 那么是我编译的问题还是什么？
> > 
> > 
> > 我自己遇到过的情况而言，要么是编译的时候出了意外，要么是硬件上有问题了，试试全部删除重新拉取，如果能一次拉取成功，那么一般不会出什么大问题，如果拉取过程总是失败，那么还是有可能出问题的。
> 
> 硬件百分百没问题，路由我都正在用，刷老毛子 6.25号的我编译有是可以启动的，源码已经删除重新下载过了的，

我昨天晚上19：20左右git pull，21：00左右刷进D2，至少到今天早上没发现问题，我继续用用看。

**Comment by hackpascal** [comment]
> [ 0.866369] spi-nor spi0.0: unrecognized JEDEC id bytes: c2 20 1d c2 30 1d

flash没认出来。
根据breed的启动信息，Macronix MX25L25635E对应的的jedec id是c2 20 19，而kernel输出的读取两次的id都不一样，大概率是spi总线不稳，例如频率太高。

**Comment by yuzhe1129** [comment]
> > [ 0.866369] spi-nor spi0.0: unrecognized JEDEC id bytes: c2 20 1d c2 30 1d
> 
> flash没认出来。 根据breed的启动信息，Macronix MX25L25635E对应的的jedec id是c2 20 19，而kernel输出的读取两次的id都不一样，大概率是spi总线不稳，例如频率太高。

闪存正常的啊，你看我楼上的回复6.25编译的固件是正常可以启动的，然后我用了另外一个正在使用OP固件的一台刷了这个固件也是无法启动的

**Comment by hackpascal** [comment]
> > > [ 0.866369] spi-nor spi0.0: unrecognized JEDEC id bytes: c2 20 1d c2 30 1d
> > 
> > 
> > flash没认出来。 根据breed的启动信息，Macronix MX25L25635E对应的的jedec id是c2 20 19，而kernel输出的读取两次的id都不一样，大概率是spi总线不稳，例如频率太高。
> 
> 闪存正常的啊，你看我楼上的回复6.25编译的固件是正常可以启动的，然后我用了另外一个正在使用OP固件的一台刷了这个固件也是无法启动的

我也没说你的闪存有问题啊。我指的是固件里面的spi通信可能有问题

**Comment by aiamadeus** [comment]
> [ 0.000000] CPU Overclock PLL: 0xc2005b12
> [ 0.000000] CPU Clock: 1000MHz

现在超频已经去掉了，重新编译就完事了。
