### ISSUE TITLE
能否加入 PHP WEB SERVER

### ISSUE THREAD

**Issue by chiyu521** [coolsnowwolf/lede#975]
想自己架设个PHP SERVER 但是 找了好多插件 发现没有spawn-fcgi和FastCGI 架设无数次都失败了 哦 对了 现在19.01出来了 大神什么时候动手呢?

**Comment by LGA1150** [comment]
官方源里有 spawn-fcgi
你还可以用 uwsgi-cgi 代替 fastcgi

**Comment by chiyu521** [comment]
我用的是NEWIFI3 D2 路由器 现在刷的是PandoraBox固件 是不是需要重新编译官方的SPAWN 或者UWSGI
CPU是MediaTek MT7621  还有 官方源对应MT7621的地址是?? 感谢大神
