### ISSUE TITLE
在删除 of-platdata 之后，无法成功编译 uboot-rockchip

### ISSUE THREAD

**Issue by nekomi-cn** [coolsnowwolf/lede#9757]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在删除 of-platdata 之后，无法成功编译 uboot-rockchip

### (2) 路由器型号和固件版本

A：OrangePi R1 Plus LTS (5.10、5.15、5.18)

### (3) 详细日志

A：
drivers/ram/rockchip/sdram_rk3328.c: In function 'rk3328_dmc_init':
drivers/ram/rockchip/sdram_rk3328.c:525:20: error: 'struct dtd_rockchip_rk3328_dmc' has no member named 'rockchip_sdram_params'
      (void *)dtplat->rockchip_sdram_params;
                    ^~
make[8]: *** [scripts/Makefile.build:258: tpl/drivers/ram/rockchip/sdram_rk3328.o] Error 1
make[7]: *** [scripts/Makefile.build:398: tpl/drivers/ram/rockchip] Error 2
make[6]: *** [scripts/Makefile.build:398: tpl/drivers/ram] Error 2
make[5]: *** [scripts/Makefile.spl:531: tpl/drivers] Error 2
make[4]: *** [Makefile:2109: tpl/u-boot-tpl] Error 2
make[3]: *** [Makefile:191: /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-orangepi-r1-plus-lts-rk3328/u-boot-2022.07/.built] Error 2
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-orangepi-r1-plus-lts-rk3328/u-boot-2022.07'
make[3]: Leaving directory '/workdir/openwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/orangepi-r1-plus-lts-rk3328/compile#2.95#1.22#3.99
    ERROR: package/boot/uboot-rockchip failed to build (build variant: orangepi-r1-plus-lts-rk3328).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.
[1_build.txt](https://github.com/coolsnowwolf/lede/files/9113402/1_build.txt)

**Comment by celgus** [comment]
How did you fix it?
