### ISSUE TITLE
R22.7.16 友善 r5s  磁盘管理 问题

### ISSUE THREAD

**Issue by zzx** [coolsnowwolf/lede#9788]
DiskMan 磁盘管理 无法识别 usb移动硬盘

**Comment by DHDAXCW** [comment]
https://user-images.githubusercontent.com/74764072/179464975-8f4c54c1-0ad1-40d2-8b9f-baea108d6748.mp4

**Comment by zzx** [comment]
> > DiskMan 磁盘管理 无法识别 usb移动硬盘
> 
> 你看看硬盘正常运行了没再提问

硬盘在N1上能用，安装友善的官方固件也能识别。

**Comment by coolsnowwolf** [comment]
重新下载img 再刷入，refresh 了
