### ISSUE TITLE
luci app samba必选 可以取消吗？

### ISSUE THREAD

**Issue by sheiy** [coolsnowwolf/lede#9798]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/12210038/179653376-cc8723a9-4c5e-4a27-bccf-1ef40d5930d0.png">

**Comment by librec** [comment]
Extra packages - autosamba 取消勾选
就可以取消勾选 luci-app-samba

**Comment by zhangguanzhang** [comment]
```
# 取消默认的 autosamba 依赖的 luci-app-samba 到 slim 里
find  ./target/linux/ -maxdepth 2 -type f  -name Makefile -exec sed -i 's#autosamba##' {} \;
```

**Comment by sheiy** [comment]
感谢
