### ISSUE TITLE
No target configuration for r5s ?

### ISSUE THREAD

**Issue by ifdog** [coolsnowwolf/lede#9801]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ v] 没有类似的issue

### (1) 具体问题
 项目已可支持R5S,但 该配置文件“lede/target/linux/rockchip/image/armv8.mk”中未有R5S的target及subtarget，导致现有的云编译工程里无法自动编译出r5s相关固件。 可否补充R5S的target?
A：

### (2) 路由器型号和固件版本
friendlyarm nanopi r5s

**Comment by aiamadeus** [comment]
rockchip 不开源，无法支持。

**Comment by ifdog** [comment]
> 

大佬，具体rockchip的啥不开源呀？

**Comment by ifdog** [comment]
> rockchip 不开源，无法支持。

大佬，求问，具体啥玩意儿没开源哪。R2S,R4S也是RK的呀，不也能自己编译的吗

**Comment by ifdog** [comment]
好的
