### ISSUE TITLE
5.18编译dnsmasq报错

### ISSUE THREAD

**Issue by learnsometech** [coolsnowwolf/lede#9805]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：编译dnsmasq失败

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志

A：
![2CK{3TO HSX FA
(https://github.com/coolsnowwolf/lede/files/9146238/config.txt)
( B8VJ8VC](https://user-images.githubusercontent.com/76856688/179889380-8e8dffcc-c8e9-4f18-9866-610d68b3b5c0.jpg)
[config.txt](https://github.com/coolsnowwolf/lede/files/9146240/config.txt)

**Comment by WYC-2020** [comment]
万能大法 ，刚编译没任何问题
