### ISSUE TITLE
r9多拨成功率低

### ISSUE THREAD

**Issue by solionw** [coolsnowwolf/lede#981]
x86 64 很多时候只能拨上一条，换OpenWrt仓库r8 stale也是这样 ，r8.1.12多拨就很快。新版本单独拨号感觉也比8.1.12慢

**Comment by liuluo1979** [comment]
我的x86-64也存在这个现象。元旦以前的轻松单线4拨，现在的重启好多次才可以4条都拨上。

**Comment by coolsnowwolf** [comment]
已修复了
