### ISSUE TITLE
5.18内核编译turboacc"Installing packages"部分报错

### ISSUE THREAD

**Issue by Zaphkito** [coolsnowwolf/lede#9810]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：5.18内核中，turboacc会存在在installing中失败的情况

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志

A：
![image](https://user-images.githubusercontent.com/64299266/180113539-014f3bf4-888d-45ff-91a6-db5a368399bf.png)
![image](https://user-images.githubusercontent.com/64299266/180113853-762aefd7-8722-4b6f-a8d8-6a7619451460.png)

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/180117472-10f75db0-903b-418e-95ce-00a821a43005.png)
 二选一不能同时选

**Comment by WYC-2020** [comment]
我搞了一个修改版 可以同时兼容，
![image](https://user-images.githubusercontent.com/34025388/180129445-b48405eb-8a36-490d-83c7-7e47e656b008.png)
需要自己去看，我去除了dns那部分哈 ，想要的 自己参考我这个改

**Comment by xiangfeidexiaohuo** [comment]
> 我搞了一个修改版 可以同时兼容， ![image](https://user-images.githubusercontent.com/34025388/180129445-b48405eb-8a36-490d-83c7-7e47e656b008.png) 需要自己去看，我去除了dns那部分哈 ，想要的 自己参考我这个改

这个有点刷，同时内置几种，有点意思。

**Comment by Zaphkito** [comment]
![image](https://user-images.githubusercontent.com/64299266/180332436-0ad8c92b-b171-455f-bb0e-ad0bf987211f.png)
![image](https://user-images.githubusercontent.com/64299266/180333165-ffa52343-b2ca-44b4-b83e-d551633b89b1.png)

只勾选一个也会出现编译失败的情况，只勾选fcm的话可以完成编译

**Comment by WYC-2020** [comment]
> ![image](https://user-images.githubusercontent.com/64299266/180332436-0ad8c92b-b171-455f-bb0e-ad0bf987211f.png) ![image](https://user-images.githubusercontent.com/64299266/180333165-ffa52343-b2ca-44b4-b83e-d551633b89b1.png)
> 
> 只勾选一个也会出现编译失败的情况，只勾选fcm的话可以完成编译

去除不干净，还有这个的依赖也要去掉，在kernel module哪里，

**Comment by Zaphkito** [comment]
> > > ![image](https://user-images.githubusercontent.com/64299266/180332436-0ad8c92b-b171-455f-bb0e-ad0bf987211f.png) ![image](https://user-images.githubusercontent.com/64299266/180333165-ffa52343-b2ca-44b4-b83e-d551633b89b1.png)
> > > 只勾选一个也会出现编译失败的情况，只勾选fcm的话可以完成编译
> > 
> > 
> > 去除不干净，还有这个的依赖也要去掉，在kernel module哪里，
> 
> 但是我是重新编的config，我再试试好了（

![image](https://user-images.githubusercontent.com/64299266/180340610-ba2b1e83-d413-421a-8b74-fbeb9adb7cdd.png)
![image](https://user-images.githubusercontent.com/64299266/180340632-a69c7b15-8a57-4cb1-9147-cb6136d0285c.png)
只勾选下面的以后这个选项会被强行勾选，取消勾选sfe后才能取消依赖
虽然不清楚是bug还是啥，我直接不勾选sfe得了

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/180341673-ec43ad51-ee7a-4796-9d1c-d1a1ea58d164.png)
这个二选一

![image](https://user-images.githubusercontent.com/34025388/180341731-b53fe0e2-0287-448e-86e6-87f4be315ae4.png)
![image](https://user-images.githubusercontent.com/34025388/180341743-82b0c519-1ba9-44c3-90b2-94d45f6aebed.png)
这两个二选一
@Zaphkito
