### ISSUE TITLE
r5s r22.7.19升级固件问题

### ISSUE THREAD

**Issue by zzx** [coolsnowwolf/lede#9811]
刷写新固件功能不能用。
![Screenshot_20220721-125942](https://user-images.githubusercontent.com/1203513/180134286-67e32ef0-c93c-4c20-a4e8-07261942f240.png)
![Screenshot_20220721-130027](https://user-images.githubusercontent.com/1203513/180134301-6263660d-6c93-41eb-8f61-a6e980378f68.png)

**Comment by coolsnowwolf** [comment]
换个浏览器或者在命令行下升级
