### ISSUE TITLE
在ubuntu22.04虚拟机上编译, Building targets时报错

### ISSUE THREAD

**Issue by pxuebin** [coolsnowwolf/lede#9815]
Building targets
go: github.com/mitchellh/mapstructure@v1.4.2: Get "https://proxy.golang.org/github.com/mitchellh/mapstructure/@v/v1.4.2.mod": dial tcp 142.251.43.17:443: connect: connection refused
go: github.com/mitchellh/mapstructure@v1.4.2: Get "https://proxy.golang.org/github.com/mitchellh/mapstructure/@v/v1.4.2.mod": dial tcp 142.251.43.17:443: connect: connection refused

make[3]: *** [Makefile:86: /home/pxb/work/router/lede/build_dir/target-x86_64_musl/UnblockNeteaseMusic-0.2.13/.built] Error 1
make[3]: Leaving directory '/home/pxb/work/router/lede/feeds/packages/multimedia/UnblockNeteaseMusic-Go'
time: package/feeds/packages/UnblockNeteaseMusic-Go/compile#0.10#0.29#64.02
    ERROR: package/feeds/packages/UnblockNeteaseMusic-Go failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/UnblockNeteaseMusic-Go/compile] Error 1
make[2]: Leaving directory '/home/pxb/work/router/lede'
make[1]: *** [package/Makefile:110: /home/pxb/work/router/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/pxb/work/router/lede'
make: *** [/home/pxb/work/router/lede/include/toplevel.mk:230：world] 错误 2

在ubuntu22.04虚拟机上编译，报如上错误。求大神指点，谢谢

**Comment by zhangguanzhang** [comment]
你的纵云梯不行
