### ISSUE TITLE
大佬有没有考虑加入一个看门狗功能

### ISSUE THREAD

**Issue by a1768623020** [coolsnowwolf/lede#982]
openwrt的电压不太稳定，动不动就假死机了，只能手动拔电源重启，怎么弄个自动重启？

**Comment by a1768623020** [comment]
> 电压不稳定？你用万用表测过？

前端有电压电流表，，当然知道了。

**Comment by LGA1150** [comment]
用 I2C 总线接传感器，系统定时读取电压，在不稳定时重启路由器
考虑到电压不稳时可能已经死机，还可以直接向 SoC 发送 RESET 指令
可能需要飞线
