### ISSUE TITLE
缺少wmi.ko

### ISSUE THREAD

**Issue by vipboddy** [coolsnowwolf/lede#9825]
内核518

Package kmod-hwmon-nct6775 is missing dependencies for the following libraries:
wmi.ko
make[2]: *** [modules/hwmon.mk:333: /mnt/op/lede/bin/targets/x86/64/packages/kmod-hwmon-nct6775_5.18.14-1_x86_64.ipk] Error 1
make[2]: Leaving directory '/mnt/op/lede/package/kernel/linux'
time: package/kernel/linux/compile#14.90#2.90#15.20
    ERROR: package/kernel/linux failed to build.
make[1]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[1]: Leaving directory '/mnt/op/lede'

**Comment by WYC-2020** [comment]
我这边一切正常
![image](https://user-images.githubusercontent.com/34025388/180629546-4031c499-3de5-45f2-bdcb-0268318f1302.png)

**Comment by vipboddy** [comment]
> 我这边一切正常 ![image](https://user-images.githubusercontent.com/34025388/180629546-4031c499-3de5-45f2-bdcb-0268318f1302.png)

大佬忘记说明是5.18，正常吗这个编译

**Comment by WYC-2020** [comment]
> > 我这边一切正常 ![image](https://user-images.githubusercontent.com/34025388/180629546-4031c499-3de5-45f2-bdcb-0268318f1302.png)
> 
> 大佬忘记说明是5.18，正常吗这个编译

我就是5.18
