### ISSUE TITLE
linksys wrt3200编译完以后出现3个无线，2个5G！

### ISSUE THREAD

**Issue by the55555day** [coolsnowwolf/lede#985]
linksys wrt3200编译完以后出现3个无线，2个5G，什么情况 ？

**Comment by coolsnowwolf** [comment]
日志看看

**Comment by gavin219** [comment]
就是3个其中一个0db的。一直这样

**Comment by the55555day** [comment]
@gavin219 有这个，还有一个radio0 ，只支持802.11AC的，三个无线都可以单独设置ssid和密码

**Comment by nivalxer** [comment]
radio2是DFS用的，可以忽略。radio2如果设置为无线的话，一段时间没有设备链接，这个radio会自己关掉的。
用radio1就行了。
