### ISSUE TITLE
DNS解析默认勾选禁止解析IPv6 DNS记录，即使取消勾选待重新启动openwrt后依然恢复勾选禁止ipv6解析

### ISSUE THREAD

**Issue by GeneralPanfeng** [coolsnowwolf/lede#9857]
<img width="1920" alt="2022-07-29" src="https://user-images.githubusercontent.com/29865999/181775890-4bd88a12-bdf9-463a-8ed8-f5ccbae8b130.png">
请问如何允许解析ipv6 dns

**Comment by ddzzhen** [comment]
使用5.10内核编译可以解决
