### ISSUE TITLE
K3编译了最新版本，U盘无法识别，内核日志如下

### ISSUE THREAD

**Issue by JoeHoy233** [coolsnowwolf/lede#987]
[    1.926033] bcma: bus0: Core 11 found: USB 2.0 (manuf 0x4BF, id 0x504, rev 0x07, class 0x0)
[    1.934488] bcma: bus0: Core 12 found: USB 3.0 (manuf 0x4BF, id 0x505, rev 0x07, class 0x0)
[    4.161224] usbcore: registered new interface driver usbfs
[    4.166824] usbcore: registered new interface driver hub
[    4.172276] usbcore: registered new device driver usb
[    4.188569] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.197971] SCSI subsystem initialized
[    4.203704] ehci-platform: EHCI generic platform driver
[    4.209935] bcm_ns_usb2 1800c000.usb2-phy: can't request region for resource [mem 0x1800c000-0x1800cfff]
[    4.219492] bcm_ns_usb2 1800c000.usb2-phy: Failed to map DMU regs
[    4.225691] bcm_ns_usb2: probe of 1800c000.usb2-phy failed with error -16
[    4.234334] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.241185] ohci-platform: OHCI generic platform driver
[    4.246640] ohci-platform 18022000.ohci: Generic Platform OHCI controller
[    4.253521] ohci-platform 18022000.ohci: new USB bus registered, assigned bus number 1
[    4.261571] ohci-platform 18022000.ohci: irq 37, io mem 0x18022000
[    4.334573] hub 1-0:1.0: USB hub found
[    4.338396] hub 1-0:1.0: 2 ports detected
[    4.348500] usbcore: registered new interface driver usb-storage
[    9.865854] usbcore: registered new interface driver ums-alauda
[    9.872757] usbcore: registered new interface driver ums-cypress
[    9.879647] usbcore: registered new interface driver ums-datafab
[    9.886544] usbcore: registered new interface driver ums-freecom
[    9.893670] usbcore: registered new interface driver ums-isd200
[    9.900570] usbcore: registered new interface driver ums-jumpshot
[    9.907524] usbcore: registered new interface driver ums-karma
[    9.914477] usbcore: registered new interface driver ums-sddr09
[    9.921387] usbcore: registered new interface driver ums-sddr55
[    9.928325] usbcore: registered new interface driver ums-usbat
[    9.944170] xt_time: kernel timezone is -0000
[    9.962906] PPP generic driver version 2.4.2
[    9.968188] NET: Registered protocol family 24
[    9.976572] usbcore: registered new interface driver brcmfmac
[   63.270199] usb 1-1: new full-speed USB device number 2 using ohci-platform
[   63.490171] usb 1-1: device descriptor read/64, error -62
[   63.820112] usb 1-1: device descriptor read/64, error -62
[   64.150109] usb 1-1: new full-speed USB device number 3 using ohci-platform
[   64.370108] usb 1-1: device descriptor read/64, error -62
[   64.700116] usb 1-1: device descriptor read/64, error -62
[   64.820322] usb usb1-port1: attempt power cycle
[   65.370120] usb 1-1: new full-speed USB device number 4 using ohci-platform
[   65.810110] usb 1-1: device not accepting address 4, error -62
[   66.020113] usb 1-1: new full-speed USB device number 5 using ohci-platform
[   66.460107] usb 1-1: device not accepting address 5, error -62
[   66.466072] usb usb1-port1: unable to enumerate USB device

**Comment by coolsnowwolf** [comment]
已修复了

**Comment by JoeHoy233** [comment]
感谢，问题已经解决了
