### ISSUE TITLE
【R4S】最近俩天编译的固件无法启动

### ISSUE THREAD

**Issue by skefy** [coolsnowwolf/lede#9870]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
现象：之前一直在用Github Actions自动编译固件使用，但是最近几天编译的固件无法正常开机。具体观察现象：指示灯Sys 有亮，但是Lan、WLan 俩个灯不亮。

config配置文件：https://github.com/skefy/NanoPi-R4S_lede_firmware/blob/main/.lede_config

### (2) 路由器型号和固件版本

A：R4S（非阉割版）

### (3) 详细日志

A：

**Comment by showme2005** [comment]
我的R4S 可以启动.但是温度高得离谱..以前最多48度...最近的固件温度都是70多....
