### ISSUE TITLE
R4S重启就红灯

### ISSUE THREAD

**Issue by keeno1982** [coolsnowwolf/lede#9888]
因为是重启，看不到日志，不好意思。

拉的最新代码编译，不知道从哪个版本时候开始无论页面重启还是通过SSH重启，就是直接红灯，更新固件后的重启也是红灯，必须重新插拔一下电源才能启动，是软重启功能没弄好吗？有同学遇到这个问题吗？如何处理呢？

**Comment by zhangguanzhang** [comment]
https://github.com/coolsnowwolf/lede/issues/9861

**Comment by keeno1982** [comment]
哦，原来是新的版本有问题，希望大佬们修复

**Comment by coolsnowwolf** [comment]
5.19 版本内核中修复了

**Comment by keeno1982** [comment]
@coolsnowwolf 谢谢老大
