### ISSUE TITLE
网卡设备中添加ath10k会编译错误

### ISSUE THREAD

**Issue by zhangyao-20021223** [coolsnowwolf/lede#9896]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by coolsnowwolf** [comment]
没机器，怎么加？

**Comment by aiamadeus** [comment]
它的哥哥 orangepi 3 都还没被支持呢（

**Comment by minlang112** [comment]
建议给开发者赠送开发机

**Comment by zclikezc** [comment]
刚来了欧派3lts

**Comment by LXGMAX** [comment]
1. 给开发者送一个开发设备
2. 自己适配
