### ISSUE TITLE
intel-igb 原厂闭源有线驱动Flow Offloading 加速无效

### ISSUE THREAD

**Issue by a1073185067** [coolsnowwolf/lede#9897]
esxi虚拟机，网口直通，编译已经选择Flow Offloading ，然后测速，发现cpu占用和不勾选Flow Offloading 一样
[
![84L0JNYLE54_DVYP%~RM9JL](https://user-images.githubusercontent.com/18640179/183279465-aba950b2-b158-4f80-ab59-6b219f434c82.png)

**Comment by a1073185067** [comment]
![image](https://user-images.githubusercontent.com/18640179/183279511-e3024958-5149-47b7-be1e-05db1fa1fa3d.png)

**Comment by suizhenmin** [comment]
个人意见 CPU 性能够，Turbo Acc 就不要编译进去了，感觉兼容性有问题。

**Comment by laaArmy** [comment]
这玩意对小包转发提升很大，但一大堆BUG

看你取舍了

**Comment by suizhenmin** [comment]
我mac上用的一款远程桌面软件，只要开了 ACC 远程桌面就 连不上，最后放弃 ACC 了
