### ISSUE TITLE
x86_64加passwall编译的passwall插件dns为什么没有pdnsd解析方式呢。

### ISSUE THREAD

**Issue by Trumpgodie** [coolsnowwolf/lede#9898]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by xiangfeidexiaohuo** [comment]
这个你要去隔壁问吧，在这问，不合理啊。

**Comment by lxl6125** [comment]
好像前段时间password去掉了pdnsd了
