### ISSUE TITLE
希望添加国内ipv6地址块至china_ssr.txt中

### ISSUE THREAD

**Issue by WEANYNWA** [coolsnowwolf/lede#990]
在ipv6环境下，Google和部分其他地址走国内ipv6网，无法分流到代理，导致访问速度奇慢无比。
国内ipv6地址块：http://ipverse.net/ipblocks/data/countries/cn-ipv6.zone

**Comment by jsda** [comment]
光添加地址块还不行的，还要添加ipv6的透明网关，现在脚本没人写，先把ipv6的dns屏蔽就行了。

**Comment by WEANYNWA** [comment]
> 光添加地址块还不行的，还要添加ipv6的透明网关，现在脚本没人写，先把ipv6的dns屏蔽就行了。
> 
> 有动手能力的可以试下这个
> https://blog.yoitsu.moe/tech_misc/lede_and_nat6_and_ss_redir.html

感谢回复及相关资料，等软路由到手后会着手尝试

**Comment by dongjuanyong** [comment]
目前弄ipv4+ipv6双线按gfwlist走透明代理，工作量不小
目前的ipv4按gfwlist走透明代理的实现方式主要是把gfwlist扔给dnsmasq解析后加入特定ipset（这时也可以指定本地pdnsd用tcp查询上游dns），iptables转发目的地为此ipset的包到透明代理端口
上游dns一般会返回aaaa记录即ipv6地址，此时客户端ipv6如果是通的话，会优先连接ipv6地址。直连ipv6被rst或timeout，等fallback到ipv4的时候黄花菜都凉了……
解决方法以下两种：
1. 屏蔽gfwlist中地址的aaaa记录，这个简单，用pdnsd就能实现；
2. 新建一个ipv6的ipset：
> ipset create EXAMPLE_BYPASS_V6 hash:ip family inet6

dnsmasq设置中将解析结果扔到两个ipset中：
> ipset=/domain.com/EXAMPLE_BYPASS_V4,EXAMPLE_BYPASS_V6

ip6tables把ipv4的活再干一遍，不过ipv6不用nat了，这个怎么弄没实际试过，最主要的原因是，偶的vps没ipv6
