### ISSUE TITLE
git pull 自动合并失败，修正冲突然后提交修正的结果。

### ISSUE THREAD

**Issue by lloyd18** [coolsnowwolf/lede#9923]
冲突（add/add）：合并冲突于 package/boot/uboot-rockchip/src/configs/fastrhino-r66s-rk3568_defconfig
自动合并 package/boot/uboot-rockchip/src/configs/fastrhino-r66s-rk3568_defconfig
自动合并 package/boot/uboot-rockchip/Makefile
自动合并失败，修正冲突然后提交修正的结果。

**Comment by lloyd18** [comment]
这怎么解决呢

**Comment by lovehackintosh** [comment]
手动编辑合并失败的那几个文件,然后git add . 再git commit

**Comment by lloyd18** [comment]
谢谢大家，已经重新 clone 来编译了
