### ISSUE TITLE
设置静态地址导致主机名显示不正确

### ISSUE THREAD

**Issue by xltuo** [coolsnowwolf/lede#993]
主机型号 | PHICOMM K3
架构 | ARMv7 Processor rev 0 (v7l)
固件版本 | OpenWrt R9.1.1 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
内核版本 | 4.19.9

在DHCP/DNS菜单中添加一条永不过期的静态地址，DHCP 分配里面显示的主机名不正确

静态地址设置：

![_20190107111444](https://user-images.githubusercontent.com/12935064/50747276-04ef3980-126e-11e9-9bcf-8af1b3b1d875.png)

DHCP列表

![_20190107111527](https://user-images.githubusercontent.com/12935064/50747278-07ea2a00-126e-11e9-9231-f8bd846b2fa3.png)

**Comment by imjonat** [comment]
我的刷了两个版本也都有这个bug，和楼主一样
