### ISSUE TITLE
rpi4编译不过 

### ISSUE THREAD

**Issue by q1379331** [coolsnowwolf/lede#9931]
#
# configuration written to .config
#
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/main.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/backport-5.5.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/backport-5.10.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/backport-5.11.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/backport-5.13.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/backport-5.15.o
  LD [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/compat/compat.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/chip.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwil.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/fweh.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/p2p.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/proto.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/common.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/core.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/firmware.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/feature.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/btcoex.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/vendor.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/pno.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/xtlv.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/bcdc.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/fwsignal.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/commonring.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/flowring.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/msgbuf.o
  CC [M]  /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.o
/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c: In function 'brcmf_sdio_bus_reset':
/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4167:29: error: passing argument 1 of 'mmc_hw_reset' from incompatible pointer type [-Werror=incompatible-pointer-types]
  mmc_hw_reset(sdiodev->func1->card);
               ~~~~~~~~~~~~~~^~~~~~
In file included from /home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:19:
./include/linux/mmc/core.h:176:35: note: expected 'struct mmc_host *' but argument is of type 'struct mmc_card *'
 int mmc_hw_reset(struct mmc_host *host);
                  ~~~~~~~~~~~~~~~~~^~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:262: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.o' failed
make[12]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.o] Error 1
scripts/Makefile.build:497: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac' failed
make[11]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211/brcmfmac] Error 2
scripts/Makefile.build:497: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211' failed
make[10]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom/brcm80211] Error 2
scripts/Makefile.build:497: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom' failed
make[9]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless/broadcom] Error 2
scripts/Makefile.build:497: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless' failed
make[8]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/drivers/net/wireless] Error 2
Makefile:1737: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1' failed
make[7]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1] Error 2
Makefile.build:13: recipe for target 'modules' failed
make[6]: *** [modules] Error 2
Makefile.real:93: recipe for target 'modules' failed
make[5]: *** [modules] Error 2
Makefile:120: recipe for target 'modules' failed
make[4]: *** [modules] Error 2
make[4]: Leaving directory '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1'
Makefile:553: recipe for target '/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/.built' failed
make[3]: *** [/home/op/lede/build_dir/target-aarch64_cortex-a72_musl/linux-bcm27xx_bcm2711/backports-5.15.33-1/.built] Error 2
make[3]: Leaving directory '/home/op/lede/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#13.62#1.25#17.11
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
package/Makefile:114: recipe for target 'package/kernel/mac80211/compile' failed
make[2]: *** [package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/op/lede'
package/Makefile:110: recipe for target '/home/op/lede/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_compile' failed
make[1]: *** [/home/op/lede/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/op/lede'
/home/op/lede/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by gevikhn** [comment]
同样的问题，mac80211编译失败
