### ISSUE TITLE
未检测到 Realtek PCI 网卡

### ISSUE THREAD

**Issue by umarizulkifli** [coolsnowwolf/lede#9955]
反馈错误/问题模板，请删除建议

## 1. 关于你要提交的问题
未检测到以太网适配器

Q：问题是否被搜索（使用“x”选择）
* [x] 没有类似问题

## 2.详细说明
```
Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller [10ec:8136] (rev 02)
```
r8101 的以太网驱动程序不可用
驱动源码：https://github.com/ghostrider-reborn/realtek-r8101-linux-driver
Sources: 
- https://www.realtek.com/en/directly-download?downloadid=40ba896d11ca30a51350cc2ea3b01f3d
- https://github.com/umarizulkifli/r8101/blob/main/r8101-1.037.01.tar.bz2

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

答：联想 S10-3

### (3) 详细日志
```
$ lspci -v
$ lspci -v
Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller [10ec:8136] (rev 02)
$ ifconfig eth0
ifconfig: eth0: error fetching interface information: Device not found
```
A：

**Comment by umarizulkifli** [comment]
Failed to build r8101

`ERROR: package/lean/r8101 failed to build.`

**Comment by zhangj3** [comment]
百兆网卡....别折腾了  跟上主流设备才是王道

**Comment by bihell** [comment]
> 百兆网卡....别折腾了 跟上主流设备才是王道

厉害啊，楼主节俭持家，挺好的。
