### ISSUE TITLE
编译时怎么选择内核版本？

### ISSUE THREAD

**Issue by sjkhsl** [coolsnowwolf/lede#9957]
编译时怎么选择内核版本？

**Comment by firkerword** [comment]
sed -i 's/KERNEL_PATCHVER:=5.15/KERNEL_PATCHVER:=5.19/g' ./target/linux/x86/Makefile

**Comment by sjkhsl** [comment]
> sed -i 's/KERNEL_PATCHVER:=5.15/KERNEL_PATCHVER:=5.19/g' ./target/linux/x86/Makefile

感谢～
