### ISSUE TITLE
Padavan的ssr支持acl语法的去广告

### ISSUE THREAD

**Issue by dzhuqi** [coolsnowwolf/lede#996]
Padavan的ssr支持acl语法的去广告（传说对youtube的4秒广告有疗效），大雕有没有在ssr-plus中加入此功能的计划？

**Comment by xftv5608** [comment]
升级内核后，ssr-plus 菜单不显示了。

**Comment by xftv5608** [comment]
升级内核后，经X86测试的SSR-plus 菜单不显示了。
