### ISSUE TITLE
v2ray的插件可否增加订阅功能

### ISSUE THREAD

**Issue by kangxicome** [coolsnowwolf/lede#999]
ks的v2ray也可以通过vmess直接订阅多个服务器，希望后续可加入...

**Comment by WKZD** [comment]
同求，订阅增加支持v2ray和ss

**Comment by ntgeralt** [comment]
44个Issues， 楼主忙不过来了……

**Comment by lingzhi2262071123** [comment]
订阅来一发

**Comment by alliswell2day** [comment]
我自己改修了，订阅增加支持v2ray和ss。 支持 这个魔改 https://github.com/rico93/ss-panel-v3-mod_Uim 面
![Screenshot_2](https://user-images.githubusercontent.com/16883846/55534577-609f5680-56e7-11e9-879c-e9d7a0782ab2.png)

**Comment by jiushibushuo** [comment]
> 我自己改修了，订阅增加支持v2ray和ss。 支持 这个魔改 https://github.com/rico93/ss-panel-v3-mod_Uim 面
> ![Screenshot_2](https://user-images.githubusercontent.com/16883846/55534577-609f5680-56e7-11e9-879c-e9d7a0782ab2.png)

源码共享一下呗

**Comment by WKZD** [comment]
> 我自己改修了，订阅增加支持v2ray和ss。 支持 这个魔改 https://github.com/rico93/ss-panel-v3-mod_Uim 面
> ![Screenshot_2](https://user-images.githubusercontent.com/16883846/55534577-609f5680-56e7-11e9-879c-e9d7a0782ab2.png)
你改了的在哪？
